### ISSUE TITLE
Fix Docker multi-node setup guide

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#24114] opened 2016-04-11 23:14 UTC
The [Docker (multi-node)](http://kubernetes.io/docs/getting-started-guides/docker-multinode/) setup guide seems to be broken, see http://stackoverflow.com/questions/36559737/kubernetes-docker-multinode-dns-deploy-error-failedmount-failedsync

@brendandburns @resouer @luxas @vishh @kubernetes/docs

**Comment by vishh** [comment] 2016-04-11 23:17
I gave it a try, spent some time hacking/fixing the scripts, and the master node failed to come up. I chose to not sink in any more time until we decide if we want to maintain this guide.

**Comment by janetkuo** [comment] 2016-04-11 23:27
In [table of solutions](http://kubernetes.io/docs/getting-started-guides/#table-of-solutions) the support level of Docker multi-node solution is **Project**, i.e. Kubernetes Committers regularly use this configuration, so it usually works with the latest release of Kubernetes.

**Comment by luxas** [comment] 2016-04-12 04:32
I have a PR up for this already and I'm going to look into this: #21646
The problem is, I don't know where in the project we should store the whole thing as the docs has been moved. Ideally somewhere in cluster/. cc/ @mikedanese 

Another thing I'll work on is getting `curl -sSL http://get.k8s.io/local | bash` working (even for multiple arches) cc/ @fgrzadkowski

**Comment by pwittrock** [comment] 2016-04-22 17:47
Another issue with multinode docker #24654

**Comment by astrolox** [comment] 2016-04-30 14:44
Another related issue #24714

**Comment by bgrant0607** [comment] 2016-06-19 21:57
This should be replaced by kubernetes-anywhere.

**Comment by resouer** [comment] 2016-06-20 02:36
It seems kubernetes-anywhere is bound to weave?

**Comment by luxas** [comment] 2016-06-20 05:01
This issue is stale. It's working now with v1.3 and some alphas as well.

@bgrant0607 I don't agree with you. I took care of it, and now the deployment is working quite well (based on conformance tests), and there will be further improvements to the run-everywhere docker-multinode solution.

I admit that kubernetes-anywhere has a much nicer name, and is probably advertised about better. But it isn't a multiarch solution! I've worked har with these things, and docker-multinode does work exactly the same regardless of machine I deploy it on, my laptop, my Raspberry Pi cluster, my Pine64's (arm64) or whatever. 

Docker-multinode comes built-in with kube-dns and the dashboard nowadays too.

**Comment by luxas** [comment] 2016-06-20 20:29
That said, there are common parts of those two projects, and we could see if it's possible to merge the two deployments, but none of them should be sacrificed

**Comment by luxas** [comment] 2016-06-20 20:30
@resouer I don't either like the Weave dep...

**Comment by mikedanese** [comment] 2016-06-22 18:10
Kubernetes anywhere has merged with min-turnup which doesn't have a Weave dependency so it's possible to deploy a kubernetes cluster with kubernetes-anywhere without weave. The doc needs to be updated.

But why don't you like a weave dependency? I've been considering taking one as it would dramatically simplify the deployment to have a constant and portable solution for the pod network.

**Comment by bgrant0607** [comment] 2016-06-29 03:40
cc @kubernetes/sig-cluster-lifecycle

**Comment by bgrant0607** [comment] 2016-06-29 03:57
@luxas 
docker-multinode has a Flannel dependency. How is that different than a Weave dependency? Eventually we'd like to support all networking options via composition, but we'll need a default, and all options are vendor-specific.

**Comment by errordeveloper** [comment] 2016-07-02 13:55
Good question, Brian. The main technical difference is that flannel wants
to own the same bridge Docker owns, while Weave Net has it's own bridge
that it manages independently. The effect of this is that you don't need
"bootstrap-docker". Secondly, Weave Net provides very robust IPAM
functionality, as well as DNS. Also, Weave Net has other features that
flannel doesn't have, but these are the most relevant ones in this context.

**Comment by jbeda** [comment] 2016-07-02 14:47
In this context extra features can be a disadvantage. There is a danger we
will depend on those features and make it harder to run without them. We
shouldn't lock ourselves in to vendor specific features.

**Comment by roberthbailey** [comment] 2017-04-25 06:32
Closing as we are removing the docker multi-node setup guide.

**Closed by roberthbailey** 2017-04-25 06:32 UTC
Labels: priority/important-soon, sig/cluster-lifecycle, team/ux (deprecated - do not use)
