### ISSUE TITLE
subPath = file bug version 1.5.2

### ISSUE THREAD

**Issue by samiaben88** [kubernetes/kubernetes#46839] opened 2017-06-02 08:24 UTC
Hi,
I deploy kubernetes using ansible on two nodes (1 master and one slave), it brings : version 1.5.2

everything working fine except when I use subpath:

The issue is, I have subPath set to a file in a configmap to map it into the right place in my container. But kubernetes assumes subPath is a directory and always does a mkdir over it. This causes things to fail. 

I already see this issue in (https://github.com/kubernetes/kubernetes/issues/45613 ) but it was about kubernetes version 1.6.3 and the solution was that the update (1.6.4) will correct this.

I'm wondering how can I resolve this, without switching version? and can I use a resent version deployed with ansible ? 

can you help me please

**Comment by samiaben88** [comment] 2017-06-02 08:37
@kubernetes/sig-storage-bugs

**Comment by gnufied** [comment] 2017-06-02 13:24
@wongma7 does 1.5.x also suffers from https://github.com/kubernetes/kubernetes/issues/45613 ?

**Comment by wongma7** [comment] 2017-06-02 13:30
No, I thankfully 😅 did not backport my defective patch to 1.5.x.

I'll look into this later today. If the file exists there should be no problem... If for whatever reason it looks like it doesn't, then *docker* will auto create a directory.

**Comment by wongma7** [comment] 2017-06-05 17:08
@samiaben88 can you post your pod spec please? It worked for me with the following pod and configmap (adapted from the doc example):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.level: very
  special.type: charm
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config/special.level
        subPath: special.level
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
  restartPolicy: Never
```

**Comment by samiaben88** [comment] 2017-06-06 07:46
Hi again, this is my pod spec:

`kind
	:	
Pod
apiVersion
	:	
v1
metadata
		
{10}
name
	:	
rouncube1-1345133109-c05k9
generateName
	:	
rouncube1-1345133109-
namespace
	:	
default
selfLink
	:	
/api/v1/namespaces/default/pods/rouncube1-1345133109-c05k9
uid
	:	
24b409e8-4a8b-11e7-a816-525400225b53
resourceVersion
	:	
335165
creationTimestamp
	:	
2017-06-06T07:38:33Z
labels
		
{2}
pod-template-hash
	:	
1345133109
run
	:	
rouncube1
annotations
		
{1}
kubernetes.io/created-by
	:	
{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"rouncube1-1345133109\",\"uid\":\"24b297fb-4a8b-11e7-a816-525400225b53\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"335139\"}}\n
ownerReferences
		
[1]
0
		
{5}
apiVersion
	:	
extensions/v1beta1
kind
	:	
ReplicaSet
name
	:	
rouncube1-1345133109
uid
	:	
24b297fb-4a8b-11e7-a816-525400225b53
controller
	:	
true
spec
		
{9}
volumes
		
[4]
0
		
{2}
name
	:	
roundcube-1
emptyDir
		
{0}
	
(empty object)
1
		
{2}
name
	:	
roundcube-2
emptyDir
		
{0}
	
(empty object)
2
		
{2}
name
	:	
linshare-data3
configMap
		
{2}
name
	:	
webmailconf
defaultMode
	:	
420
3
		
{2}
name
	:	
default-token-b0kq1
secret
		
{2}
secretName
	:	
default-token-b0kq1
defaultMode
	:	
420
containers
		
[1]
0
		
{7}
name
	:	
rouncube1
image
	:	
docker.io/robbertkl/roundcube
ports
		
[1]
0
		
{2}
containerPort
	:	
80
protocol
	:	
TCP
resources
		
{0}
	
(empty object)
volumeMounts
		
[4]
0
		
{2}
name
	:	
roundcube-1
mountPath
	:	
/var/www/db
1
		
{2}
name
	:	
roundcube-2
mountPath
	:	
/var/log/nginx/log
2
		
{3}
name
	:	
linshare-data3
mountPath
	:	
/var/www/config/config.inc.php
subPath
	:	
config.inc.php
3
		
{3}
name
	:	
default-token-b0kq1
readOnly
	:	
true
mountPath
	:	
/var/run/secrets/kubernetes.io/serviceaccount
terminationMessagePath
	:	
/dev/termination-log
imagePullPolicy
	:	
Always
restartPolicy
	:	
Always
terminationGracePeriodSeconds
	:	
30
dnsPolicy
	:	
ClusterFirst
serviceAccountName
	:	
default
serviceAccount
	:	
default
nodeName
	:	
192.168.99.105
securityContext
		
{0}
	
(empty object)
status
		
{6}
phase
	:	
Pending
conditions
		
[3]
0
		
{4}
type
	:	
Initialized
status
	:	
True
lastProbeTime
	:	
null
lastTransitionTime
	:	
2017-06-06T07:38:33Z
1
		
{6}
type
	:	
Ready
status
	:	
False
lastProbeTime
	:	
null
lastTransitionTime
	:	
2017-06-06T07:38:33Z
reason
	:	
ContainersNotReady
message
	:	
containers with unready status: [rouncube1]
2
		
{4}
type
	:	
PodScheduled
status
	:	
True
lastProbeTime
	:	
null
lastTransitionTime
	:	
2017-06-06T07:38:33Z
hostIP
	:	
192.168.99.105
podIP
	:	
172.16.52.8
startTime
	:	
2017-06-06T07:38:33Z
containerStatuses
		
[1]
0
		
{7}
name
	:	
rouncube1
state
		
{1}
waiting
		
{2}
reason
	:	
RunContainerError
message
	:	
GenerateRunContainerOptions: mkdir /var/lib/kubelet/pods/24b409e8-4a8b-11e7-a816-525400225b53/volumes/kubernetes.io~configmap/linshare-data3/config.inc.php: not a directory
lastState
		
{0}
	
(empty object)
ready
	:	
false
restartCount
	:	
0
image
	:	
docker.io/robbertkl/roundcube
imageID
	:`

**Comment by samiaben88** [comment] 2017-06-06 07:48
hi, this is my pod spec:

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"rouncube1-1345133109","uid":"24b297fb-4a8b-11e7-a816-525400225b53","apiVersion":"extensions","resourceVersion":"335139"}}
  creationTimestamp: 2017-06-06T07:38:33Z
  generateName: rouncube1-1345133109-
  labels:
    pod-template-hash: "1345133109"
    run: rouncube1
  name: rouncube1-1345133109-c05k9
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: rouncube1-1345133109
    uid: 24b297fb-4a8b-11e7-a816-525400225b53
  resourceVersion: "335830"
  selfLink: /api/v1/namespaces/default/pods/rouncube1-1345133109-c05k9
  uid: 24b409e8-4a8b-11e7-a816-525400225b53
spec:
  containers:
  - image: docker.io/robbertkl/roundcube
    imagePullPolicy: Always
    name: rouncube1
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/www/db
      name: roundcube-1
    - mountPath: /var/log/nginx/log
      name: roundcube-2
    - mountPath: /var/www/config/config.inc.php
      name: linshare-data3
      subPath: config.inc.php
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-b0kq1
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 192.168.99.105
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: roundcube-1
  - emptyDir: {}
    name: roundcube-2
  - configMap:
      defaultMode: 420
      name: webmailconf
    name: linshare-data3
  - name: default-token-b0kq1
    secret:
      defaultMode: 420
      secretName: default-token-b0kq1
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-06-06T07:38:33Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-06-06T07:38:33Z
    message: 'containers with unready status: [rouncube1]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-06-06T07:38:33Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: docker.io/robbertkl/roundcube
    imageID: ""
    lastState: {}
    name: rouncube1
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'GenerateRunContainerOptions: mkdir /var/lib/kubelet/pods/24b409e8-4a8b-11e7-a816-525400225b53/volumes/kubernetes.io~configmap/linshare-data3/config.inc.php:
          not a directory'
        reason: RunContainerError
  hostIP: 192.168.99.105
  phase: Pending
  podIP: 172.16.52.8
  startTime: 2017-06-06T07:38:33Z

**Comment by samiaben88** [comment] 2017-06-12 07:05
hi, again, any help please ?

**Comment by wongma7** [comment] 2017-06-12 22:00
I can't reproduce the issue nor figure out what path of code could lead to mkdir from GenerateRunContainerOptions. The error *does* look similar to the 1.6.3 bug but it's not the same.

Did this work on any version before 1.5.2? Is this vanilla kubernetes or some distro of? Can you provide the output of 'kubectl describe pod' and if possible, some kubelet logs capturing around the time the pod is created? Thanks!

**Comment by jwomeara** [comment] 2017-06-22 22:13
Hey, 

I'm experiencing the same issue.  Using the command below, 

`kubectl get deployment kafka -o yaml`

kubectl returns the following config,

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-06-22T22:05:43Z
  generation: 1
  labels:
    cds: kafka
  name: kafka
  namespace: default
  resourceVersion: "3008"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/kafka
  uid: efb80d0a-5796-11e7-904d-525400ba512b
spec:
  replicas: 1
  selector:
    matchLabels:
      cds: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        cds: kafka
    spec:
      containers:
      - command:
        - sh
        - -c
        - df -h; ls -l /kafka/config/; ls -l /kafka/config/server.properties.template;
          cat /kafka/config/server.properties.template
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: ZOOKEEPER_IP
          value: zookeeper
        - name: JMX_PORT
          value: "9999"
        image: ches/kafka:0.10.2.0
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 7203
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kafka/config/server.properties.template
          name: kafka-properties
          readOnly: true
          subPath: server.properties.template
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registrysecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: server.properties.template
            path: server.properties.template
          name: kafka-config
        name: kafka-properties
status:
  conditions:
  - lastTransitionTime: 2017-06-22T22:05:43Z
    lastUpdateTime: 2017-06-22T22:05:43Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

Here's the version string for the Kubernetes cluster I'm running:

`Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

Also, I have a few commands that are running within the container to get some more insight into why the configmap is failing to mount.  

I'm using these commands: 

`df -h; ls -l /kafka/config/; ls -l /kafka/config/server.properties.template; cat /kafka/config/server.properties.template`

and seeing this output in the log:

```
 Filesystem                                                                                          Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-67217493-20123ba9eb5110410ad25b96b7d59165a4d114a88beda0285c02b8da3d4bb133   10G  647M  9.4G   7% /
tmpfs                                                                                               920M     0  920M   0% /dev
tmpfs                                                                                               920M     0  920M   0% /sys/fs/cgroup
/dev/mapper/VolGroup00-LogVol00                                                                      38G  3.0G   35G   9% /data
shm                                                                                                  64M     0   64M   0% /dev/shm
/dev/mapper/VolGroup00-LogVol00                                                                      38G  3.0G   35G   9% /kafka/config/server.properties.template
tmpfs                                                                                               920M   12K  920M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                               920M     0  920M   0% /proc/kcore
tmpfs                                                                                               920M     0  920M   0% /proc/timer_list
tmpfs                                                                                               920M     0  920M   0% /proc/timer_stats
tmpfs                                                                                               920M     0  920M   0% /proc/sched_debug
ls: cannot access /kafka/config/server.properties.template: Permission denied
total 56
-rw-r--r--. 1 kafka kafka  906 Feb 14 17:26 connect-console-sink.properties
-rw-r--r--. 1 kafka kafka  909 Feb 14 17:26 connect-console-source.properties
-rw-r--r--. 1 kafka kafka 2760 Feb 14 17:26 connect-distributed.properties
-rw-r--r--. 1 kafka kafka  883 Feb 14 17:26 connect-file-sink.properties
-rw-r--r--. 1 kafka kafka  881 Feb 14 17:26 connect-file-source.properties
-rw-r--r--. 1 kafka kafka 1074 Feb 14 17:26 connect-log4j.properties
-rw-r--r--. 1 kafka kafka 2061 Feb 14 17:26 connect-standalone.properties
-rw-r--r--. 1 kafka kafka 1147 Mar 31 16:44 consumer.properties
-rw-r--r--. 1 kafka kafka 3846 Mar 31 16:44 log4j.properties
-rw-r--r--. 1 kafka kafka 2185 Mar 31 16:44 producer.properties
-rw-r--r--. 1 kafka kafka 5631 Feb 14 17:26 server.properties
-?????????? ? ?     ?        ?            ? server.properties.template
-rw-r--r--. 1 kafka kafka  992 Mar 31 16:44 tools-log4j.properties
-rw-r--r--. 1 kafka kafka 1021 Mar 31 16:44 zookeeper.properties
ls: cannot access /kafka/config/server.properties.template: Permission denied
cat: /kafka/config/server.properties.template: Permission denied 
```

I apologize for the wall of text, but I figure more information is better than less. Any help is GREATLY appreciated!

**Comment by wongma7** [comment] 2017-06-22 22:20
You're right more is better & I hate to ask for more, but can you confirm you saw the same `message: 'GenerateRunContainerOptions: mkdir /var/lib/kubelet/pods/24b409e8-4a8b-11e7-a816-525400225b53/volumes/kubernetes.io~configmap/linshare-data3/config.inc.php:` event? What is the output of 'kubectl describe pod $deploymentpod'?

**Comment by jwomeara** [comment] 2017-06-22 22:25
Woo!  You caught me just as I was heading out.  The output is below.  If you need anything else, let me know and I'll get that to you tomorrow!  Thanks for the quick response.

```
Name:		kafka-3373530170-8cp35
Namespace:	default
Node:		192.168.61.92/192.168.61.92
Start Time:	Thu, 22 Jun 2017 18:05:43 -0400
Labels:		cds=kafka
		pod-template-hash=3373530170
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"kafka-3373530170","uid":"efb891d6-5796-11e7-bac8-525400ba512b","...
Status:		Running
IP:		10.10.98.3
Controllers:	ReplicaSet/kafka-3373530170
Containers:
  kafka:
    Container ID:	docker://f5f8ce920f124f79f04512fd8506892db747c3bb2ab4136949c99729c5e4ce2a
    Image:		ches/kafka:0.10.2.0
    Image ID:		docker-pullable://docker.io/ches/kafka@sha256:ceeb74771f6b011ad4783d7ce2b8494871f32f8b0740a245a0d5cbc463610648
    Ports:		9092/TCP, 7203/TCP
    Command:
      sh
      -c
      df -h; ls -l /kafka/config/; ls -l /kafka/config/server.properties.template; cat /kafka/config/server.properties.template
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Thu, 22 Jun 2017 18:21:49 -0400
    Ready:		False
    Restart Count:	8
    Environment:
      KAFKA_ADVERTISED_HOST_NAME:	kafka
      ZOOKEEPER_IP:			zookeeper
      JMX_PORT:				9999
    Mounts:
      /kafka/config/server.properties.template from kafka-properties (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bdrb6 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  kafka-properties:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	kafka-config
    Optional:	false
  default-token-bdrb6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-bdrb6
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  17m		17m		1	default-scheduler				Normal		Scheduled	Successfully assigned kafka-3373530170-8cp35 to 192.168.61.92
  17m		17m		1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal		Created		Created container with id ea2911da6176ba5161f87fc7721c77151167fc9e8070de3e69c028bad4b6893a
  17m		17m		1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal		Started		Started container with id ea2911da6176ba5161f87fc7721c77151167fc9e8070de3e69c028bad4b6893a
  17m		17m		1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal		Created		Created container with id d930b4b464a76e7c71d1c61771c1aa4aa5c8bb194f80a2198610d6eeb94cee01
  17m		17m		1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal		Started		Started container with id d930b4b464a76e7c71d1c61771c1aa4aa5c8bb194f80a2198610d6eeb94cee01
  17m		17m		2	kubelet, 192.168.61.92				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 10s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  17m	17m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id 929329113fb33a7fb7f4ac5bec4b7914198c163e47ae7b4621f5a95d89cc841e
  17m	17m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id 929329113fb33a7fb7f4ac5bec4b7914198c163e47ae7b4621f5a95d89cc841e
  17m	17m	2	kubelet, 192.168.61.92				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 20s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  16m	16m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id 504a5a0418951d26e09ad5871a7f8631efca85c4cb6d0c45d344a72c6028826b
  16m	16m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id 504a5a0418951d26e09ad5871a7f8631efca85c4cb6d0c45d344a72c6028826b
  16m	16m	4	kubelet, 192.168.61.92				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 40s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  16m	16m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id d8b6bf1b607f562d62ef439da0208f46f6c72ad1bc08e557e80fab25069a3370
  16m	16m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id d8b6bf1b607f562d62ef439da0208f46f6c72ad1bc08e557e80fab25069a3370
  16m	14m	7	kubelet, 192.168.61.92				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  14m	14m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id 72a3b22f174aa240cb370b92af09fe1636d4416db5b59622e7d5ef5281d46550
  14m	14m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id 72a3b22f174aa240cb370b92af09fe1636d4416db5b59622e7d5ef5281d46550
  14m	12m	13	kubelet, 192.168.61.92				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  11m	11m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id eb2900fc82ae4f7b595e7e770fbdb266c02a19215ee63d7f81090cca7c207e73
  11m	11m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id eb2900fc82ae4f7b595e7e770fbdb266c02a19215ee63d7f81090cca7c207e73
  6m	6m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id eb4c9c70cb58ad531c09ae1b387bff7fa189b0aabb78087b66d516b222f6d66b
  6m	6m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id eb4c9c70cb58ad531c09ae1b387bff7fa189b0aabb78087b66d516b222f6d66b
  1m	1m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Started		Started container with id f5f8ce920f124f79f04512fd8506892db747c3bb2ab4136949c99729c5e4ce2a
  1m	1m	1	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Created		Created container with id f5f8ce920f124f79f04512fd8506892db747c3bb2ab4136949c99729c5e4ce2a
  17m	1m	9	kubelet, 192.168.61.92	spec.containers{kafka}	Normal	Pulled		Container image "ches/kafka:0.10.2.0" already present on machine
  11m	2s	54	kubelet, 192.168.61.92				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kafka pod=kafka-3373530170-8cp35_default(efba960f-5796-11e7-bac8-525400ba512b)"

  17m	2s	82	kubelet, 192.168.61.92	spec.containers{kafka}	Warning	BackOff	Back-off restarting failed container
```

**Comment by jwomeara** [comment] 2017-06-23 12:31
Is there anything else I can provide for you to help with this issue?

**Comment by jwomeara** [comment] 2017-06-26 14:55
*bump*

**Comment by jwomeara** [comment] 2017-06-29 16:01
Has anyone had a chance to look at this?  We are still experiencing the issue using the configuration I provided.  If you aren't able to recreate the issue, could you please provide a working example that I can use as a sanity check?

**Comment by wongma7** [comment] 2017-06-29 16:13
No, but at a glance your error is not the same as op's. I would open a new issue. Please try the pod+configmap I posted.

**Comment by jwomeara** [comment] 2017-06-29 16:26
I think we're dealing with the exact same issue.  We are both trying to mount a file within a configmap to a specific file location within the container.  You can ignore my config information that I posted though because I tried running with your configuration and got the same error.  My kubernetes version information is the same as what I posted before.

The container log says:
` ls: /etc/config/special.level: Permission denied `

I ran the following command:
`kubectl describe pod dapi-test-pod`

and got the following result:
```
Name:		dapi-test-pod
Namespace:	default
Node:		192.168.41.91/192.168.41.91
Start Time:	Thu, 29 Jun 2017 12:21:40 -0400
Labels:		<none>
Annotations:	<none>
Status:		Failed
IP:		
Controllers:	<none>
Containers:
  test-container:
    Container ID:	docker://5882fa23d09411307f9b7c5627d4bc5de97a3551f49c6d72365ca77632752a65
    Image:		gcr.io/google_containers/busybox
    Image ID:		docker-pullable://gcr.io/google_containers/busybox@sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67
    Port:		
    Command:
      /bin/sh
      -c
      ls /etc/config/
    State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Thu, 29 Jun 2017 12:21:43 -0400
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /etc/config/special.level from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-brzfs (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  config-volume:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	special-config
    Optional:	false
  default-token-brzfs:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-brzfs
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  2m		2m		1	default-scheduler					Normal		Scheduled	Successfully assigned dapi-test-pod to 192.168.41.91
  2m		2m		1	kubelet, 192.168.41.91	spec.containers{test-container}	Normal		Pulling		pulling image "gcr.io/google_containers/busybox"
  2m		2m		1	kubelet, 192.168.41.91	spec.containers{test-container}	Normal		Pulled		Successfully pulled image "gcr.io/google_containers/busybox"
  2m		2m		1	kubelet, 192.168.41.91	spec.containers{test-container}	Normal		Created		Created container with id 5882fa23d09411307f9b7c5627d4bc5de97a3551f49c6d72365ca77632752a65
  2m		2m		1	kubelet, 192.168.41.91	spec.containers{test-container}	Normal		Started		Started container with id 5882fa23d09411307f9b7c5627d4bc5de97a3551f49c6d72365ca77632752a65
```

**Comment by wongma7** [comment] 2017-06-29 17:16
I say your issue is not the same because op's pod did not start due to mkdir error whereas yours does start but later fails to access the file with permission denied. I suppose the distinction does not matter to you, but since fixing one most likely won't fix the other, I'd prefer a separate issue.

My best guess is that this has something to do with 'defaultMode' not applying to the configmap file. But I'm not at all familiar with the 'projection' volumes nor how defaultMode works. What happens when you give the pod an fsGroup, does it work? Does your cluster have PSP enabled?

**Comment by shraderdm** [comment] 2017-10-20 06:16
I am having the exact same issue as OP, including the ? ? ?????'s in the ls output. Any updates on this yet?

**Closed** 2018-03-19 08:03 UTC
Labels: lifecycle/rotten, sig/storage
