### ISSUE TITLE
creation of e2e cluster not working with the latest gcloud

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#25199] opened 2016-05-05 14:31 UTC
When I try to create e2e cluster by executing `go run hack/e2e.go -v -build -up`, it fails with the following error:
```
usage: gcloud compute instances describe  NAME [optional flags]
ERROR: (gcloud.compute.instances.describe) unrecognized arguments:
  --fields
  networkInterfaces[0].accessConfigs[0].natIP
```

It seems that the latest version of gcloud (108.0.0) is not handling `--fileds` flag in `gcloud compute instance-groups describe` command.

**Comment by jszczepkowski** [comment] 2016-05-05 14:48
CC @wojtek-t

**Comment by spxtr** [comment] 2016-05-05 15:32
dupe of #25153 should be fixed after rebase

**Closed by spxtr** 2016-05-05 15:32 UTC
Labels: area/test
