### ISSUE TITLE
Installation of 1.13.5 kubeadm and kubelet on Centos/RHEL broken. kubeadm-1.13.5 is installing kubelet-1.18.5 as dependency

### ISSUE THREAD

**Issue by shashankv02** [kubernetes/kubernetes#92586] opened 2020-06-28 19:29 UTC
**What happened**:

When kubeadm-1.13.5, kubelet-1.13.5 yum packages are attempted to be installed together, installation fails with dependency error. When tried individually, it works. But when `kubeadm-1.13.5` package is installed, it is installing `kubelet-1.18.5` instead of `kubelet-1.13.5`. The workaround seems to be installing `kubernetes-cni-0.7.5` along with `kubeadm-1.13.5` and `kubelet-1.13.5`

```
[root@rhel ~]# yum install kubelet-1.13.5 kubeadm-1.13.5
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * elrepo: elrepo.reloumirrors.net
 * epel: download.nus.edu.sg
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.13.5-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.7.5 for package: kubeadm-1.13.5-0.x86_64
---> Package kubelet.x86_64 0:1.13.5-0 will be installed
--> Processing Dependency: kubernetes-cni = 0.7.5 for package: kubelet-1.13.5-0.x86_64
--> Running transaction check
---> Package kubelet.x86_64 0:1.13.5-0 will be installed
--> Processing Dependency: kubernetes-cni = 0.7.5 for package: kubelet-1.13.5-0.x86_64
---> Package kubernetes-cni.x86_64 0:0.8.6-0 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.13.5-0.x86_64 (kubernetes)
           Requires: kubernetes-cni = 0.7.5
           Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
               kubernetes-cni = 0.3.0.1-0.07a8a2
           Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-0
           Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-1
           Available: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
               kubernetes-cni = 0.6.0-0
           Available: kubernetes-cni-0.7.5-0.x86_64 (kubernetes)
               kubernetes-cni = 0.7.5-0
           Installing: kubernetes-cni-0.8.6-0.x86_64 (kubernetes)
               kubernetes-cni = 0.8.6-0
 You could try using --skip-broken to work around the problem
```

Try `kubelet-1.13.5` alone

```
[root@rhel ~]# yum install kubelet-1.13.5
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * elrepo: elrepo.reloumirrors.net
 * epel: download.nus.edu.sg
Resolving Dependencies
--> Running transaction check
---> Package kubelet.x86_64 0:1.13.5-0 will be installed
--> Processing Dependency: kubernetes-cni = 0.7.5 for package: kubelet-1.13.5-0.x86_64
--> Running transaction check
---> Package kubernetes-cni.x86_64 0:0.7.5-0 will be installed
--> Finished Dependency Resolution
```

Try `kubeadm-1.13.5` alone and it installs kubelet-1.18.5 as depedency. 

```
[root@rhel ~]# yum install kubeadm-1.13.5
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * elrepo: elrepo.reloumirrors.net
 * epel: download.nus.edu.sg
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.13.5-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.7.5 for package: kubeadm-1.13.5-0.x86_64
--> Processing Dependency: kubelet >= 1.6.0 for package: kubeadm-1.13.5-0.x86_64
--> Running transaction check
---> Package kubelet.x86_64 0:1.18.5-0 will be installed
---> Package kubernetes-cni.x86_64 0:0.8.6-0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================
 Package                              Arch                         Version                          Repository                        Size
===========================================================================================================================================
Installing:
 kubeadm                              x86_64                       1.13.5-0                         kubernetes                       7.9 M
Installing for dependencies:
 kubelet                              x86_64                       1.18.5-0                         kubernetes                        21 M
 kubernetes-cni                       x86_64                       0.8.6-0                          kubernetes                        18 M

Transaction Summary
===========================================================================================================================================
Install  1 Package (+2 Dependent packages)
```

## Workaround

Install `kubernetes-cni-0.7.5` 

```
[root@rhel ~]# yum install kubernetes-cni-0.7.5 kubeadm-1.13.15 kubelet-1.13.5
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * elrepo: elrepo.reloumirrors.net
 * epel: download.nus.edu.sg
No package kubeadm-1.13.15 available.
Resolving Dependencies
--> Running transaction check
---> Package kubelet.x86_64 0:1.13.5-0 will be installed
---> Package kubernetes-cni.x86_64 0:0.7.5-0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================
 Package                              Arch                         Version                          Repository                        Size
===========================================================================================================================================
Installing:
 kubelet                              x86_64                       1.13.5-0                         kubernetes                        21 M
 kubernetes-cni                       x86_64                       0.7.5-0                          kubernetes                        10 M

Transaction Summary
===========================================================================================================================================
Install  2 Packages

Total download size: 31 M
Installed size: 143 M
Is this ok [y/d/N]:
```
-

**What you expected to happen**:

`yum install kubelet-1.13.5 kubeadm-1.13.5` should not fail. 

`yum install kubeadm-1.13.5` should not install `kubelet-1.18.5` as dependency. 

**How to reproduce it (as minimally and precisely as possible)**:

Try `yum install kubelet-1.13.5 kubeadm-1.13.5`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment] 2020-06-29 11:16
@kubernetes/release-engineering
/sig release
/area release-eng

**Comment by MarkDeckert** [comment] 2020-07-21 22:18
Any update on this? Even with the workaround of pre-installing the correct version of kubelet, you still potentially create an unsupported k8s configuration by having an older-apiserver/newer-kubelet version on one of the masters immediately prior to the upgrade.  There should be an upper bound on the version of the kubelet dependency that is no higher than the version of kubeadm.

**Comment by luissio** [comment] 2020-09-14 10:24
確かに！助けてください！！

**Comment by justaugustus** [comment] 2020-09-14 12:21
/assign @saschagrunert 

Sascha -- can you take a look or assign to someone on @kubernetes/release-engineering to investigate?

The following issues are similar classes of issues for apt/yum:
- https://github.com/kubernetes/kubernetes/issues/92698
- https://github.com/kubernetes/kubernetes/issues/92587
- https://github.com/kubernetes/kubernetes/issues/92586
- https://github.com/kubernetes/kubernetes/issues/92463

**Comment by saschagrunert** [comment] 2020-09-14 12:56
Confirmed, this is still broken. Not completely sure what is the reason…
/help

**Comment by saschagrunert** [comment] 2021-01-11 17:41
It feels we will not come to a solution for those issues until someone is really working on it. I will close it for now, especially since 1.13.x is EOL since a long time.

/close

**Closed** 2021-01-11 17:41 UTC
Labels: area/release-eng, help wanted, kind/bug, sig/release
