### ISSUE TITLE
localsubjectaccessreviews used by something in e2e clusters but not supported in the apiserver

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#38694] opened 2016-12-13 13:06 UTC
I was looking at API sever logs and noticed a stacktrace for usage of not-registered API resource localsubjectaccessreviews. All tests are still passing (to the same extent as they were) which means that we have two problems:
- we don't fail our tests in case of 405's (which I think is bad if unexpected @kubernetes/test-infra-maintainers @dchen1107)
- we partially enabled localsubjectaccessreviews feature (whatever this is) @kubernetes/sig-api-machinery

(you can look at pretty much any recent test run, e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/1365/artifacts/bootstrap-e2e-master/kube-apiserver.log)

cc @wojtek-t @deads2k 

```
I1213 11:54:21.733640       5 panics.go:76] GET /apis/authorization.k8s.io/v1beta1/namespaces/e2e-tests-kubectl-d3rfj/localsubjectaccessreviews: (365.415µs) 405
goroutine 38373 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc420225730, 0x195)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc420225730, 0x195)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x40d85a0, 0xc420338420, 0x0, 0x0, 0x0, 0x0, 0x40d4d60, 0xc420225730, 0xc426d04690, 0x195, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:464 +0x162
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x40b94a0, 0xc426e8bb00, 0x40d85a0, 0xc420338420, 0x0, 0x0, 0x0, 0x0, 0x40d4d60, 0xc420225730, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:481 +0x103
k8s.io/kubernetes/pkg/apiserver.serviceErrorHandler(0x40d85a0, 0xc420338420, 0x195, 0x27dea86, 0x17, 0xc423fd9f80, 0xc422690180)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/serviceerror.go:41 +0x222
k8s.io/kubernetes/pkg/apiserver.InstallServiceErrorHandler.func1(0x195, 0x27dea86, 0x17, 0xc423fd9f80, 0xc422690180)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/serviceerror.go:30 +0x65
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc423fd9f80, 0xc422690180)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:250 +0x110
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc423fd9f50, 0xc423fd9f80, 0xc422690180)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:21 +0x95
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4205e6b40, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:254 +0x497
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42029c7b0, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420389fb0, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/pkg/apiserver/filters.WithAuthorization.func1(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/authorization.go:50 +0x327
net/http.HandlerFunc.ServeHTTP(0xc42022fe00, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithImpersonation.func1(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/impersonation.go:44 +0x1c69
net/http.HandlerFunc.ServeHTTP(0xc42022fe40, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/auth/handlers.WithAuthentication.func1(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:73 +0x2c2
net/http.HandlerFunc.ServeHTTP(0xc4206700a0, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc42066e240, 0x40d4d60, 0xc420225730, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x40d4d60, 0xc420225730, 0xc426d04690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc4203376e0, 0x7fd0c6a591d0, 0xc421f149a0, 0xc426d04690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc42066e2e0, 0x40da3a0, 0xc421f149a0, 0xc426d04690, 0xc4226900c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:89 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:91 +0x1db

logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the server does not allow this method on the requested resource\",\"reason\":\"MethodNotAllowed\",\"details\":{},\"code\":405}\n"
 [[e2e.test/v1.6.0 (linux/amd64) kubernetes/527d502] 104.155.160.14:51143]
```

**Comment by deads2k** [comment] 2016-12-13 14:02
`LocalSubjectAccessReview` is a POST-only endpoint, similar to `SubjectAccessReview`.  It provides the same functionality at a namespace scope so that namespace level admins can figure out who can do what in their namespace.  405 is appropriate for a GET, so that's working correctly and we're fully enabled.

The more interesting question is who is trying to do the GET.

**Comment by liggitt** [comment] 2016-12-19 02:44
probably the test that makes sure no resources exist in a namespace after the namespace is deleted

**Comment by chuckbutler** [comment] 2017-01-27 17:22
We hit similar in a cluster thats running in a staging environment, and the etcd key store was rebooted during a large namespace termination. we were blaming etcd initially for the failure scenario after seeing this stack trace, but some cursory googling brought us here.

The logs in question look like:

```

Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: I0127 21:21:29.906140    1162 panics.go:76] DELETE /apis/authorization.k8s.io/v1beta1/namespaces/production/localsubjectaccessreviews: (698.088µs) 405
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: goroutine 1754 [running]:
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc420db41c0, 0x195)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc420db41c0, 0x195)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x4948a60, 0xc420064c00, 0x0, 0x0, 0x0, 0x0, 0x4945220, 0xc420db41c0, 0xc4228962d0, 0x195, ...)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:463 +0x162
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x49294e0, 0xc4202af880, 0x4948a60, 0xc420064c00, 0x0, 0x0, 0x0, 0x0, 0x4945220, 0xc420db41c0, ...)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:480 +0x103
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/apiserver.serviceErrorHandler(0x4948a60, 0xc420064c00, 0x195, 0x29ab1bc, 0x17, 0xc421d32ae0, 0xc42117a540)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/serviceerror.go:41 +0x222
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/apiserver.InstallServiceErrorHandler.func1(0x195, 0x29ab1bc, 0x17, 0xc421d32ae0, 0xc42117a540)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/serviceerror.go:30 +0x65
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc421d32ae0, 0xc42117a540)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:250 +0x110
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc421d32ab0, 0xc421d32ae0, 0xc42117a540)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:21 +0x95
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420764bd0, 0x4945220, 0xc420db41c0, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:254 +0x497
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x4945220, 0xc420db41c0, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: net/http.HandlerFunc.ServeHTTP(0xc420260010, 0x4945220, 0xc420db41c0, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /usr/local/go/src/net/http/server.go:1726 +0x44
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: net/http.(*ServeMux).ServeHTTP(0xc420761a70, 0x4945220, 0xc420db41c0, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /usr/local/go/src/net/http/server.go:2022 +0x7f
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x4945220, 0xc420db41c0, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: net/http.HandlerFunc.ServeHTTP(0xc4207e0a80, 0x7f1ffee91e00, 0xc42279c058, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /usr/local/go/src/net/http/server.go:1726 +0x44
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7f1ffee91e00, 0xc42279c058, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: net/http.HandlerFunc.ServeHTTP(0xc4207e0b10, 0x7f1ffee91e00, 0xc42279c058, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /usr/local/go/src/net/http/server.go:1726 +0x44
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f1ffee91e00, 0xc42279c058, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: net/http.HandlerFunc.ServeHTTP(0xc420767e20, 0x7f1ffee91e00, 0xc42279c058, 0xc4228962d0)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /usr/local/go/src/net/http/server.go:1726 +0x44
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420767e40, 0x494a7e0, 0xc42279c058, 0xc4228962d0, 0xc42117a420)
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]: logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the server does not allow this method on the requested resource\",\"reason\":\"MethodNotAllowed\",\"details\":{},\"code\":405}\n"
Jan 27 21:21:29 mth-k8smaster-03 kube-apiserver[1162]:  [[kube-controller-manager/v1.5.1 (linux/amd64) kubernetes/82450d0/namespace-controller] 127.0.0.1:56486]
```

Seems related to the associated output above, and will continue searching for symptoms to xlink for a root cause. This has caused pods to become unscheduleable and even local state seems to be broken as existing pods that were running have entered a CrashLoop state. 

This effects the following pods to date:

- kube-dashboard
- default-http-backend
- nginx-ingress-controller


If this appears to be completely unrelated, feel free to disregard and i'll scrub the comment from the thread. I'm surprised this wasn't caught with e2e testing at this time.

**Comment by deads2k** [comment] 2017-01-27 18:40
> This has caused pods to become unscheduleable and even local state seems to be broken as existing pods that were running have entered a CrashLoop state.

Are you sure that a failed delete is causing a crash loop in a pod?  That would be highly unusual.  This was just a namespace controller that didn't respect the verbs for resources, but I highly doubt that affects pods.

**Comment by chuckbutler** [comment] 2017-01-27 20:13
I think this was crossed with other symptoms of the deployment. I'll go ahead and scrub the above, as it was unrelated. Thanks for the follow-up @deads2k

**Comment by liggitt** [comment] 2017-02-13 01:53
closing, e2e attempts to do a subject access review to check for serviceaccount access prior to running a test, but tolerates clusters that don't have it enabled

**Closed by liggitt** 2017-02-13 01:53 UTC
Labels: area/apiserver, area/test, kind/bug, sig/api-machinery
