### ISSUE TITLE
v1.7.4 - Daemonset DESIRED 0 (for node-exporter)

### ISSUE THREAD

**Issue by hartmut-pq** [kubernetes/kubernetes#51785] opened 2017-09-01 09:49 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
```
NAME            DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR   AGE
node-exporter   0         0         0         0            0           <none>          43m
```

**What you expected to happen**:
We have 9 nodes running and therefore would expect 
`Desired Number of Nodes Scheduled: 9`

**How to reproduce it (as minimally and precisely as possible)**:
We haven't had time to try to reproduce on a fresh cluster - but we can reproduce by applying the manifest below to our cluster for any namespace incl. `kube-system` with the same result of 0 desired nodes scheduled.

Note: We have 3 other daemonsets which are working just fine - but no noticeable difference to this one.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.4
- Cloud provider or hardware configuration**: AWS via kops

- manifest:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image:  quay.io/prometheus/node-exporter:v0.14.0
        args:
        - "-collector.procfs=/host/proc"
        - "-collector.sysfs=/host/sys"
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
```

Just in case I restarted `kube-controller-manager` pods and deleted/reapplied the manifest. Didn't help.

How could I debug or get any log / information why the daemonset won't be scheduled for our nodes?

**Comment by hartmut-pq** [comment] 2017-09-01 09:59
I hope @kubernetes/sig-scheduling-bugs is the correct choice?!?

**Comment by hartmut-pq** [comment] 2017-09-01 12:48
Note: we just upgraded to `v1.7.5` and everything is back healthy - the daemonset adapted smoothly to each new 1.7.5 node joining the cluster.
So unsure if I should close or if anyone would still like to have a look or bring some light into the cause?!?

**Comment by resouer** [comment] 2017-09-05 07:31
This is no longer a bug, will close it. Feel free to re-open it whenever you encounter same issue again. Thanks!

**Comment by zapman449** [comment] 2018-01-12 01:55
On my v1.7.10, I can replicate this behavior with `kubectl apply -f file.yaml` with the following:

```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: pd-system
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: registry-proxy
      name: registry-proxy
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        resources:
          requests:
            cpu: 50m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: registry.pd-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
```

If I do `kubectl edit ds registry-proxy` and delete the `last-applied-configuration` annotation, the pods will spawn.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T17:13:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zapman449** [comment] 2018-01-12 01:56
I have a different spin on the above which will deploy successfully, then will deploy at zero, then will deploy successfully.......

**Comment by zapman449** [comment] 2018-01-12 01:58
More info:

```
$ kubectl -n pd-system describe ds registry-proxy
Name:		registry-proxy
Selector:	name=registry-proxy
Node-Selector:	<none>
Labels:		name=registry-proxy
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"name":"registry-proxy","namespace":"pd-system"},"spec":{"template":...
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

**Comment by justinsb** [comment] 2018-01-12 14:35
Reopening.

@resouer what was the commit that addressed this?

**Comment by bsalamat** [comment] 2018-01-13 01:48
Couple of things to mention:
1. DaemonSets are not scheduled by scheduler. They are scheduled by DaemonSet controller. So, this is not a scheduler bug.
2. If DS controller finds that a node is not feasible for a DS Pod, for example because the node does not have enough resources, has port conflict, etc., it won't create a pod for the node. So, in order to debug this issue we need to know states of the nodes as well.

**Comment by zapman449** [comment] 2018-01-13 20:44
I'm happy to provide the above detail.  However, considering that the pods sprang to life immediately when I ran `kubectl -n pd-system annotate ds registry-proxy kubectl.kubernetes.io/last-applied-configuration-`, the nodes had sufficient resources.

**Comment by zapman449** [comment] 2018-01-25 16:12
Hello?

**Comment by mblaschke** [comment] 2018-02-09 13:07
Same problem with 1.9.1 (with node-exporter).

First deployment was fine but only on nodes. We've added later the toleration for all nodes and after that the DS only scheduled Pods on master only. Now without the toleration no Pods are created and desired count is always 0.

Cluster still have resources (10 nodes, 5 master). No errors with "describe".

Deployment via helm prometheus.

**Comment by mblaschke** [comment] 2018-02-09 13:21
Somewhere else was running a node-exporter on hostPort 9100 and that's why the Pods were not created.
If the scheduling starts if you remove/change the hostPort then it's not a Kubernetes bug.

**Closed** 2018-07-09 21:43 UTC
Labels: kind/bug, lifecycle/rotten, sig/apps, sig/cluster-lifecycle, sig/scheduling

**Comment by Shinerrs** [comment] 2018-10-02 07:08
I can confirm this is still an issue in the latest Kubernetes

Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by qurname2** [comment] 2018-12-03 14:44
I have a similar problem in version 1.11.3 on a freshly installed cluster. Any ideas?

**Comment by dimitris-zervas** [comment] 2018-12-13 10:22
Describing the daemonset should give you the "Reason" with more details:

`kubectl describe daemonset daemonset.apps/prometheus-node-exporter`

**Comment by wtan825** [comment] 2019-02-13 09:04
@dimitris-zervas 
Kubernetes
`
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`
NAME                                      DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/prometheus-node-exporter   0         0         0         0            0           <none>          1h

`
Name:           node-exporter
Selector:       app=node-exporter
Node-Selector:  beta.kubernetes.io/os=linux
Labels:         app=node-exporter
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apps/v1beta2","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"node-exporter"},"name":"node-exporter","namespace":"monit...
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=node-exporter
  Service Account:  node-exporter
  Containers:
   node-exporter:
    Image:      quay.io/prometheus/node-exporter:v0.17.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --web.listen-address=127.0.0.1:9100
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --path.rootfs=/host/root
      --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
      --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    Limits:
      cpu:     250m
      memory:  180Mi
    Requests:
      cpu:        102m
      memory:     180Mi
    Environment:  <none>
    Mounts:
      /host/proc from proc (rw)
      /host/root from root (ro)
      /host/sys from sys (rw)
   kube-rbac-proxy:
    Image:      quay.io/coreos/kube-rbac-proxy:v0.4.0
    Port:       9100/TCP
    Host Port:  9100/TCP
    Args:
      --secure-listen-address=$(IP):9100
      --tls-cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      --upstream=http://127.0.0.1:9100/
    Limits:
      cpu:     20m
      memory:  40Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      IP:     (v1:status.podIP)
    Mounts:  <none>
  Volumes:
   proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:
   sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
   root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:
Events:            <none>


`

**Comment by wtan825** [comment] 2019-02-13 09:31
This works. https://bugzilla.redhat.com/show_bug.cgi?id=1608288

**Comment by avdhoot** [comment] 2019-04-01 12:44
Changing port(host/node) worked for me.

**Comment by georgasa** [comment] 2020-01-31 17:43
The same bug exists still in v1.12.10:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"archive", BuildDate:"2019-11-28T14:04:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"archive", BuildDate:"2019-11-27T12:59:25Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

[root@cbam-2d3e049ae69b4565aaaaf976331-infra-node-0 ~]# kubectl describe ds smsf-sms
Name:           smsf-sms
Selector:       app=smsf-sms
Node-Selector:  nodetype=smsf
Labels:         app=smsf-sms
Annotations:    ctrl: {"ip": "dynamic"}
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{"ctrl":"{\"ip\": \"dynamic\"}","oam":"{\"ip\": \"dynamic\...
                oam: {"ip": "dynamic"}
**Desired Number of Nodes Scheduled: 0**
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed

The related nodes are healthy (with sufficient resources) and other deamonsets have been scheduled successfully there.
