### ISSUE TITLE
Issues while bringing up kubernetes dashboard GUI on master

### ISSUE THREAD

**Issue by praoreo** [kubernetes/kubernetes#31799] opened 2016-08-31 17:14 UTC
We are trying to setup a multinode kubernetes cluster with 1 master and multiple worker nodes in ubuntu 14.04.  --register-node=true and --register-schedulable=false is set while installing the kubernetes master so as to make the master not schedulable. Hence the kubernetes dashboard pod got scheduled on one of the available worker nodes. However we want the dashboard to be running on master. 

As a work around started kubernetes dashboard as a docker container on master by using following command. 

docker run --net=host --rm -it gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0-beta1 --apiserver-host http://127.0.0.1:8080

Though the kubernetes dashboard is accessible, the page displayed internalerror and got refreshed automatically with the following error logs.

Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from XXX.XX.XX.X
Getting lists of all workloads
Getting pod metrics
the server could not find the requested resource (get daemonsets.extensions)
[2016-08-31T03:08:56Z] Outcoming response to XXX.XX.XX.X with 500 status code

When I tried with a different dashboard image(livew.io/kubernetes-dashboard), I could successfully access kubernetes dashboard gui. 

Can someone clarify the following.

1) Why the google kubernetes dashboard image didnt work in standalone docker container? Is their a different dashboard image that I need to pick? 
2) Is their a better way to start kubernetes-dashboard GUI on master.

kubectl version
Client Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}

docker version

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by praoreo** [comment] 2016-09-02 19:05
@bryk Could you please help.

**Comment by bryk** [comment] 2016-09-05 05:53
1. What release `livew.io/kubernetes-dashboard` corresponds to? 

> Is their a better way to start kubernetes-dashboard GUI on master.
2. You could pass KUBE_CONFIG file to it instead of specifying --apiserver-host param. The file is the same you use for kubectl. Other than that, this is a good way.
3. Anyway, why do you want to run the UI on master?

**Comment by praoreo** [comment] 2016-09-06 16:23
@bryk 
I could not make out which release the livew.io/kubernetes-dashboard corresponds to. Only supported functionalities are creating and viewing the pods deployed.

In our setup all the control functionalities are centralized into the master and it has an public IP address assigned to one of its interfaces. Hence we want the dashboard also to be hosted on the master so that it can be accessed using public IP.

Could you please your thoughts on why I am getting internal error while trying to run below docker command?

**Comment by bryk** [comment] 2016-09-07 07:17
@praoreo I think the problem is with your cluster version. It is 0.19, which is very old. Current stable is 1.3 and 1.4 is just coming out. Can you update?

**Comment by liggitt** [comment] 2017-05-27 20:36
the reported cluster is not a supported version. closing due to age.

**Closed by liggitt** 2017-05-27 20:36 UTC
Labels: area/kubectl, sig/node
