### ISSUE TITLE
dnsmasq container in kube-dns rc spec missing resource limits

### ISSUE THREAD

**Issue by ravilr** [kubernetes/kubernetes#32178] opened 2016-09-07 02:33 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): NA

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Kubernetes version** (use `kubectl version`): HEAD/1.4.0.beta

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
[kube-dns](https://github.com/kubernetes/kubernetes/blob/1e7120f02cc39798eb3d2ac0a4e7e8c0e80792ca/cluster/addons/dns/skydns-rc.yaml.base) spec here doesn't specify any resource limits for dnsmasq container.  With kubelet eviction turned on, this might put the container under best effort class and could get evicted?

**What you expected to happen**:
resource limits for dnsmasq container defined. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by ravilr** [comment] 2016-09-08 17:43
@girishkalele @thockin

**Comment by MrHohn** [comment] 2016-09-09 23:34
Duplicate of #29055.

**Comment by girishkalele** [comment] 2016-09-13 17:00
@ravilr #29055 tracks this issue - we need to figure out what is a reasonably correct value for the dnsmasq cache size (the --cache-limit arg, which is currently hardcoded to 1000) and then find a safe and close memory and cpu resource limit for the dnsmasq container.

**Comment by xiangpengzhao** [comment] 2017-06-20 10:45
Since this is a dup of #29055 and that one is closed, we can close this one.

/sig network
/cc @thockin

**Closed** 2017-06-20 16:59 UTC
Labels: area/kubectl, sig/network, team/cluster (deprecated - do not use)
