### ISSUE TITLE
`kubectl delete cronjob xxx` do not delete all jobs related with the cron job

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#42627] opened 2017-03-07 08:09 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
In https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/cron-jobs.md#deleting-a-cron-job , it mentioned that the `kubectl delete cronjob xxx` will stops new jobs from being created. However, running jobs won't be stopped, and no jobs or their pods will be deleted. To clean up those jobs and pods, you need to list all jobs created by the cron job, and delete them all.

This is not convenient for an end user, as there may be thousands of running jobs generated by a cron job and the end user may need a script to delete all jobs.

Why not delete all of the jobs related with cron job when deleting a cron job?

**What you expected to happen**:
All jobs related with cron job should be deleted when delete a cron job.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by kargakis** [comment] 2017-03-07 16:46
Dupe of https://github.com/kubernetes/kubernetes/issues/31553 - fixed in https://github.com/kubernetes/kubernetes/pull/42177

**Closed by kargakis** 2017-03-07 16:46 UTC

**Comment by davidghiurco** [comment] 2018-06-13 20:18
How come I am still seeing this issue in the following versions:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-31T19:01:20Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

After I delete a cronjob (using helm),
I run kubectl get cronjob and see no jobs.
However the jobs currently spawned by the cronjob remain orphaned. I configured the jobs to have a backoffLimit of 0 (meaning, if the job fails, do not retry) and an activeDealineSeconds of 55 seconds, meaning after 55 seconds, it should be terminated. (note, these orphaned jobs currently host pods which have failed with a non-zero status code)

The jobs aren't spawning new pods, because the pod restartPolicy is set to Never. 

Is this behavior intended? Is this meant to be dealt with by just setting the failedJobsHistoryLimit to 0?

**Comment by enisoc** [comment] 2018-06-14 18:21
@davidghiurco If you still have some orphaned Jobs, can you show the `metadata` section from `kubectl get job <job> -o yaml`?

In particular, I'm interested in seeing the state of the `finalizers`, `deletionTimestamp`, and `ownerReferences` fields in `metadata` to determine if it could be related to https://github.com/kubernetes/kubernetes/issues/59676.

**Comment by davidghiurco** [comment] 2018-06-20 20:05
Note that after figuring out how to properly set the successfulJobsHistoryLimit and failedJobsHistoryLimit properties on the CronJob spec, I was able to get this a bit more under control. But I still would expect that when I delete a cronJob, (which, in production terms means undeploying my application), that the job resources associated would be cleaned up. Since the pods get cleaned up anyways, the job is just garbage left behind that I have to manually delete.

I'd expect the successfulJobsHistoryLimit and failedJobsHistoryLimit fields to control the number of job histories kept for ACTIVE job deployments (ones for which there exists an active and deployed cronjobs) but not for cronjobs which have been undeployed.

Here's the entire yaml output. It doesn't seem to show any of the metadata fields you are looking for.
`
↳ kubectl get job name-redacted-1529523720 -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2018-06-20T19:42:02Z
  labels:
    controller-uid: 015a0bc8-74c2-11e8-bcd3-0a7c49813cca
    job-name: name-redacted-1529523720
  name: name-redacted-1529523720
  namespace: <redacted>
  resourceVersion: "260703902"
  selfLink: /apis/batch/v1/namespaces/redacted/jobs/name-redacted-1529523720
  uid: 015a0bc8-74c2-11e8-bcd3-0a7c49813cca
spec:
  activeDeadlineSeconds: 55
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 015a0bc8-74c2-11e8-bcd3-0a7c49813cca
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 015a0bc8-74c2-11e8-bcd3-0a7c49813cca
        job-name: name-redacted-1529523720
    spec:
      containers:
      - env:
        - name: REDACTED
          value: redacted
        - name: REDACTED1
          value: redacted
        image: <redacted>
        imagePullPolicy: IfNotPresent
        name: <redacted>
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: 2018-06-20T19:42:58Z
    lastTransitionTime: 2018-06-20T19:42:58Z
    message: Job was active longer than specified deadline
    reason: DeadlineExceeded
    status: "True"
    type: Failed
  failed: 1
  startTime: 2018-06-20T19:42:03Z
`

**Comment by janetkuo** [comment] 2018-06-20 21:52
@davidghiurco based on your comment here https://github.com/kubernetes/kubernetes/pull/42177#issuecomment-397073837
> I delete the object using helm.
`helm delete --purge <helm_release_name>`

It's likely that `helm delete` uses orphan deletion option. v1beta1 CronJobs API will orphan depedents by default if deletionOptions.propagationPolicy isn't specified. 

For more details on deletion options: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy
