### ISSUE TITLE
/logs Kubelet endpoint does not work.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15222] opened 2015-10-07 11:29 UTC
When going to
```
https://XXX.XXX.XXX.XXX/api/v1/proxy/nodes/kubernetes-minion-cc6s/logs/kubelet.log
```

I'm getting `404: Page Not Found` response. Plain `logs/` correctly prints all *available* log files.

cc @dchen1107 @yujuhong @davidopp

**Comment by gmarek** [comment] 2015-10-08 07:46
@dchen1107 please triage.

**Comment by lavalamp** [comment] 2015-10-08 22:23
This worked the last time I tried it. Isn't there an e2e that tests this?

**Comment by yujuhong** [comment] 2015-10-09 00:52
Not that I know of. #12811 seemed to be the last PR touching the endpoints. cc @vishh

**Comment by davidopp** [comment] 2015-10-29 00:11
ping?

**Comment by dchen1107** [comment] 2015-10-29 00:31
I don't think this is an issue at node. I believe kubectl proxy is broken for this.

**Comment by lavalamp** [comment] 2015-10-29 01:09
@gmarek can you still reproduce this?

**Comment by gmarek** [comment] 2015-10-29 06:46
Yup - every single time.

**Comment by yujuhong** [comment] 2015-10-29 17:16
I don't think it's kube proxy that's broken because I got the same 404 error when accessing the endpoint directly on the node...

**Comment by gmarek** [comment] 2015-10-29 17:37
OK, changing title of the issue - I didn't check kubelet directly.

**Comment by davidopp** [comment] 2015-10-29 19:26
Does this mean 'kubectl get logs' is also broken?

**Comment by davidopp** [comment] 2015-10-29 19:26
Sorry I mean 'kubectl logs'

**Comment by liggitt** [comment] 2015-10-29 19:35
`kubectl log` doesn't hit `/logs/*` on the kubelet, it plumbs to `/containerLogs/...`

**Comment by dchen1107** [comment] 2015-10-30 21:30
Yes, it only affects daemon's log, not container logs. 

I verified it after syncing to HEAD, and it is indeed broken at Kubelet level. Re-assign it back me.

**Closed** 2015-10-31 17:55 UTC
Labels: kind/bug, priority/P1, team/node
