### ISSUE TITLE
runSchedulerNoPhantomPodsTest integration flake

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#14421] opened 2015-09-23 12:31 UTC
Yet again [shippable](https://app.shippable.com/builds/56028d3347225d0e0098e50f) failure:
```
I0923 11:49:47.763856   17089 config.go:252] Setting pods for source file
I0923 11:49:47.836513   17089 config.go:252] Setting pods for source api
I0923 11:49:47.837142   17089 replication_controller.go:403] Finished syncing controller "test/nginx-controller" (138.134us)
I0923 11:49:47.837915   17089 manager.go:223] Status for pod "nginx-controller-b3m1f_test" updated successfully
I0923 11:49:48.768413   17089 config.go:252] Setting pods for source file
F0923 11:49:49.268912   17089 integration.go:917] FAILED: pod never started running timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:55
  'KUBE_API_VERSIONS="v1,experimental/v1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:55 runTests(...)
  2: ./hack/test-integration.sh:69 main(...)
```

**Comment by davidopp** [comment] 2015-10-19 17:42
This failure is happening during the setup for what the test is really trying to test. It is failing just creating a pod and waiting for it to run. Other tests would be failing if this were really a bug, so I am confident that this is not a real bug.

As for why the test is flaking, I don't  know. I was unable to reproduce the failure. I might just increase the timeout and call it a day.

**Comment by soltysh** [comment] 2015-10-19 19:33
:+1: for increasing the timeout.

**Comment by wojtek-t** [comment] 2015-11-25 14:51
I think this was fixed by https://github.com/kubernetes/kubernetes/pull/14681
I didn't see that failure since then.

I'm closing this one - feel free to open a new bug if you observe this again.

**Closed by wojtek-t** 2015-11-25 14:51 UTC
Labels: kind/flake, priority/P1, team/control-plane, team/test-infra
