### ISSUE TITLE
Could not mount more than one gcePersistentDisk volume

### ISSUE THREAD

**Issue by hernanliendo** [kubernetes/kubernetes#11391] opened 2015-07-16 19:30 UTC
Hey guys,

having a hard time trying to mounting more than one *gcePersistentDisk*. This is my rc script:

```javascript
{
  "kind": "ReplicationController",
  "apiVersion": "v1",
  "metadata": {
    "name": "artifactory",
    "labels": {
      "name": "artifactory"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "name": "artifactory"
    },
    "template": {
      "metadata": {
        "labels": {
          "name": "artifactory"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "artifactory-3-9-2",
            "image": "jfrog-docker-registry.bintray.io/artifactory/artifactory-oss:3.9.2",
            "ports": [
              {
                "name": "ngnix-port",
                "containerPort": 80
              },
              {
                "name": "web-port",
                "containerPort": 8081
              }
            ],
            "volumeMounts": [
              {
                "name": "artifactory-disk-data",
                "mountPath": "/var/opt/jfrog/artifactory/data"
              },
              {
                "name": "artifactory-disk-etc",
                "mountPath": "/var/opt/jfrog/artifactory/etc"
              }
            ],
            "env": [
              {
                "name": "ARTIFACTORY_USER",
                "value": "root"
              },
              {
                "name": "TOMCAT_USER",
                "value": "root"
              },
              {
                "name": "USER",
                "value": "root"
              }
            ],
            "resources": {}
          }
        ],
        "volumes": [
          {
            "name": "artifactory-disk-data",
            "gcePersistentDisk": {
              "pdName": "artifactory-disk-data",
              "fsType": "ext4"
            }
          },
          {
            "name": "artifactory-disk-etc",
            "gcePersistentDisk": {
              "pdName": "artifactory-disk-etc",
              "fsType": "ext4"
            }
          }
        ]
      }
    }
  }
}
```

I have no problems if removing this part from it:

```javascript
              {
                "name": "artifactory-disk-etc",
                "mountPath": "/var/opt/jfrog/artifactory/etc"
              }
```

I'm running on a Google Container Engine cluster

Thanks!

**Comment by ArtfulCoder** [comment] 2015-07-16 20:00
Does it run if you remove {
                "name": "artifactory-disk-data",
                "mountPath": "/var/opt/jfrog/artifactory/data"
              }

**Comment by hernanliendo** [comment] 2015-07-22 08:41
Yeap. it works that way.

It is also not working when mounting more than GDE disk even though those disks are from different pods (and same unique cluster)

I tried rebooting the instance but I only get one of the disks mounted. Also tried manually attaching them, no luck though.

**Comment by hernanliendo** [comment] 2015-07-22 08:45
In other words, it seems that:

On the same unique cluster, first started pod successfully uses a GCE disk.
After that no more pods or containers will have access to **another** GDE disk

Hope this helps

**Comment by saad-ali** [comment] 2015-09-23 21:36
@hernanliendo I tried to repro this issue but was not able to.

Specifically, I created two GCE PDs. I mounted both to the same container/pod at the same time in different mount locations. I wrote data to both PD mount locations (from inside the container) and read it back (also from inside the container) to verify that it is working as intended. For good, measure, I also deleted the pod and recreated it, and verified the data was intact on both disks.

Can you still repro this? If so, can you be more specific as to what exact errors you are seeing and what your repro steps are.

Thanks!

**Comment by davidopp** [comment] 2015-10-16 07:09
This was marked v1.1 and downgraded to P2 on the same day. :-) Is it a 1.1 blocker?

**Comment by saad-ali** [comment] 2015-10-16 18:46
Nope not a v1.1 blocker. Removing 1.1 tag.

**Comment by saad-ali** [comment] 2015-11-19 22:35
@hernanliendo, we fixed a bunch of stability issues with GCE PDs in v1.1 (see #11561, #15258, and #16053). Please give v1.1+ a try, and let me know if you run into any issues.

I'm going to close this issue for now, if you run into it again feel free to reopen it.

**Closed by saad-ali** 2015-11-19 22:35 UTC
Labels: area/platform/gce, area/storage, area/volumes, priority/P2, team/cluster
