### ISSUE TITLE
Kubelet detects and handles OUT-OF-DISK situation

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#4135] opened 2015-02-04 23:44 UTC
cc/ @vmarmol @thockin @bgrant0607 @brendandburns 

cAdvisor reports node's disk capacity and usage already, but very accurate, but still a good start. Kubelet should use such stats, and

1) Fires OUT-OF-DISK event
2) kubectl describe nodes <id> should have such information (#4075) 
3) Rejects incoming requests from master until OUT-OF-DISK situation is resolved. @davidopp Can scheduler handles such rejection? 

On kubelet side, we should reserve some space to prevent a real disk full issue; otherwise the user cannot even ssh into the machine to create authorized_keys file for user (might not be big deal since the ones for admin created long before we run into such issue). 

Alternative proposals being discussed: 

backup /var/lib/docker by a separate pd volume: no for now due to cost issue. Need confirm

**Comment by bgrant0607** [comment] 2015-02-04 23:49
The scheduler doesn't handle rejection gracefully, but should. We'll need to find a way to communicate the information. We should ensure the rejected pods don't enter the running phase.

**Comment by vishh** [comment] 2015-02-05 00:12
#3888 is related. +1 on firing the event at the least. Out of storage space is hard to detect as of now.

**Comment by davidopp** [comment] 2015-02-05 22:12
I assume what we want for the scheduler part is for Kubelet to report an "out of disk" NodeCondition in the NodeStatus, and the scheduler to use that as a signal to not schedule onto the machine?

(Longer-term do we plan to have Kubelet automatically kill a container when the machine runs out of disk space? That seems like a better solution because probably once the machine runs out of disk, all the containers on the machine are going to break if you don't free up some disk space quickly.)

**Comment by thockin** [comment] 2015-02-06 00:13
I think yes, but we're entering new territory - the node being able to
"die" without actually dying.

**Comment by dchen1107** [comment] 2015-02-06 00:31
@davidopp Yes, for 1.0 release, we should report "out of disk" NodeCondition, and hope scheduler can pick up such information. 

@thockin Yes, we are getting into reportable_free vs real_free too.

**Comment by davidopp** [comment] 2015-02-06 00:52
@dchen1107  can you ping this issue when you have surfaced out-of-disk in Kuebelet /healthz? If you think it may take a while, then we can start working on the scheduler part in parallel, but if you think it will not take long (like maybe a week) then it's probably easier for us to wait on the node controller/scheduler part until it's exposed in /healthz.

(Please correct me if I'm misunderstanding, but it looks like NodeController picks up the problems from /healthz: DoCheck() in NodeController() calls s.kubeletClient.HealthCheck(node.Name) )

**Comment by bgrant0607** [comment] 2015-02-13 03:22
NodeStatus should be collected from Kubelet or it should report it proactively -- whatever we do for PodStatus.

The scheduler should be resilient to rejections, in general, and choose a different node.

If we want the scheduler to respond to out-of-disk specifically, we should really plumb resource usage into the scheduler.

**Comment by davidopp** [comment] 2015-02-13 04:52
Let's focus on what we need for 1.0, as there are various long-term debates we could get into here that aren't worth having right now. Making the scheduler resilient to rejections is not a 1.0 feature IMO. Nor is plumbing resource usage into the scheduler. I think we should go with what Dawn suggested for now, and then as soon as we have time change it to plumbing resource usage into the scheduler, which is more work. I'm sure we'll want to block scheduling based on other NodeConditions in the future anyway.

**Comment by ddysher** [comment] 2015-02-13 04:59
So the plan is to have Kubelet *patch* NodeStatus for out-of-disk condition? Or just report via some sort of metrics for other component to detect the problem?

I feel like the second approach is more in line with our current structure.  Kubelet is the authoritive place for pod status, not node status.  It is not the place to calculate reportable_free.  But practially, we'll have less letency if kubelet reports NodeStatus proactively.

Our scheduler interface only has one method `Schedule(api.Pod, MinionLister)`.  It is really just a open-control system.  I think we should have a feedback loop to respond to schedule failure, or even extend the interface with more fine-grained methods.  Plumbing resource usage is one way, could we introduce PodPhase=Rejected and have scheduler act accordingly?

**Comment by bgrant0607** [comment] 2015-02-13 05:17
@davidopp I'm fine with a NodeCondition for now.

@ddysher Kubelet is absolutely the place to compute reportable_free.

Let's not introduce a new PodPhase. If a pod gets rejected, it can just be marked as Failed, with a more specific reason and message.

Let's not change healthz -- that's a generic probing mechanism used in multiple places. Any data reported back should be via an API handler.

**Comment by yujuhong** [comment] 2015-02-13 20:49
I spoke to @bgrant0607 and @dchen1107. I will be looking at the master's side of code (scheduler, etc) and how kublet is going to convey the status to the master/nodeController.

**Comment by yujuhong** [comment] 2015-02-17 23:59
After discussing with @dchen1107 and @ddysher, we came to the conclusion that since @ddysher has already started working on the master-side of the code and it's hard to divide work, I will not be working on this issue for now. I'd be happy to jump back in whenever @ddysher needs an extra hand.

**Comment by davidopp** [comment] 2015-03-19 05:00
This issues seems to have fallen through the cracks (last update was a month ago). @ddysher are you planning to work on this in the next week or so? If not, @yujuhong would you be interested in taking over this issue again?

**Comment by vmarmol** [comment] 2015-03-19 15:05
I think @dchen1107 is working on this. She was blocked waiting on some cAdvisor data which is now in.

**Comment by rjnagal** [comment] 2015-03-19 23:57
I merged cadvisor changes for root and docker images disk info some time back. Image GC is using it now. I can take up the kubelet part if @dchen1107 is busy.

**Comment by davidopp** [comment] 2015-03-20 00:05
That would be great.

**Comment by davidopp** [comment] 2015-04-30 22:25
@rjnagal Do you think you'll have time to work on this soon? If not, we have a couple of people who are available.

**Comment by rjnagal** [comment] 2015-04-30 22:51
@dchen1107 had something mostly ready, so I left it with her. Assigning it to myself. I can take what she  already has and finish it up.

**Comment by davidopp** [comment] 2015-04-30 23:26
OK, either one is fine, just wanted to make sure this gets attention since it is for 1.0.

**Comment by davidopp** [comment] 2015-05-11 20:47
@dchen1107 will update the status.

**Comment by rjnagal** [comment] 2015-05-11 20:56
status: I have a working PR. During testing, we found an issue with free capacity being used in kubelet. I'll send out the OOD PR and the capacity fix today.

**Comment by davidopp** [comment] 2015-05-19 20:58
IIUC #8801 / #8861 (which I guess should have been tagged to this issue) don't completely solve the problem, because the scheduler may keep re-scheduling the pod onto the node?

**Comment by davidopp** [comment] 2015-09-29 05:54
We're reviving this one...

The approach we decided on is to add a new NodeCondition called NodeOutOfDisk. It will be set (or cleared) by the Kubelet from setNodeStatus() in kubelet.go. It will use the existing isOutOfDisk() method to determine if the condition should be set or cleared. This may result in the oscillation that @lavalamp was talking about in #12041, but let's wait to see if that actually happens in practice before we decide to do rate-limiting.

Unlike NodeReady==false, NodeOutOfDisk==true will not cause pods to be evicted; it will only cause new pods to not be scheduled onto the node. So in the scheduler, we will modify ConfigFactory.CreateFromKeys() to use a NodeLister that considers not only NodeReady but also NodeOutOfDisk. I think this will require some changes to storeToNodeConditionLister to be able to take more than one NodeConditionType/NodeStatus as the filter.

One thing @mikedanese mentioned was that we should make sure that the components that write the Conditions field of NodeStatus (kubelet and node controller) don't clobber the elements of that array that they aren't updating. For example, when NodeController.tryUpdateNodeStatus() sets NodeReady to Unknown, it should preserve the value of NodeOutOfDisk if it is in the array. This is of course easy to do, but we just need to make sure we're doing it.

@yujuhong @dchen1107 @lavalamp

**Comment by lavalamp** [comment] 2015-09-29 18:25
That sounds like a good plan to me.

I think we should be proactive about the oscillation, though-- adding this condition would actually not have made a difference in the particular case that motivated #12041.

**Comment by yujuhong** [comment] 2015-09-29 19:13
Ideally, the image pulling backoff would lower the probability of such node condition oscillation. On the other hand, the offending pod with a large image would not be rejected and would be retried with backoff indefinitely, if I remember correctly.

**Comment by lavalamp** [comment] 2015-09-29 19:40
Right, the specific case had a pod with a 2GB (!!) image, on a node with a
10GB disk.

**Comment by dchen1107** [comment] 2015-10-06 19:54
https://github.com/google/cadvisor/issues/898

**Comment by stevesloka** [comment] 2015-10-22 15:25
I've been running into a similar issue for a while now, the disk fills up, but the node status is still "Ready", work hangs trying to get scheduled. 

If I can help contribute back would love to and assist solving. Seems like from the comments above a few people already have wip.

**Comment by bgrant0607** [comment] 2016-05-17 06:36
@dchen1107 @vishh Can this be closed?

**Comment by vishh** [comment] 2016-05-17 18:00
Yeah. This can be closed for now.

**Closed by vishh** 2016-05-17 18:00 UTC
Labels: area/cadvisor, area/isolation, area/reliability, area/scheduling, kind/design, priority/P1, team/control-plane, team/node

**Comment by derekchiang** [comment] 2016-11-01 19:14
For posterity, could someone give a summary of the expected behavior of a Kubernetes node when it runs out of disk?

Some specific questions that I have:

* What happens to the pods that need more disk space?  Do they get killed and rescheduled onto other nodes?  From the perspective of the pods themselves, do they get an "out of disk" error?  Or do they simply get killed?
* What happens to the pods that don't need more disk space?  Do they stay on the same node?
* Does Kubelet reclaims the space once it kills some nodes?

**Comment by vishh** [comment] 2016-11-01 21:28
> What happens to the pods that need more disk space? Do they get killed and rescheduled onto other nodes? From the perspective of the pods themselves, do they get an "out of disk" error? Or do they simply get killed?

Disk is not yet isolated. So all pods have access to all the available disk space. When we introduce disk isolation, I'd expect pods to get a "ENOSPACE" error.

> What happens to the pods that don't need more disk space? Do they stay on the same node?

As mentioned above, there is currently no notion of "disk space" for pods. If disk space isn't available on a node, pods will get evicted based on their QoS level. 

> Does Kubelet reclaims the space once it kills some nodes?

I assume you meant kill some "pods" and not "nodes". Kubelet will attempt to reclaim all compute resource as soon as possible once a pod is evicted.

**Comment by alph486** [comment] 2016-12-20 22:29
@vishh 
> I assume you meant kill some "pods" and not "nodes". Kubelet will attempt to reclaim all compute resource as soon as possible once a pod is evicted.

By "compute resources" do you mean disk as well? So its possible that a node with outofdisk=true can be schedulable again shortly?

**Comment by vishh** [comment] 2017-01-03 19:51
Starting from v1.4, one can configure kubelet to evict pods whenever disk
is full. Take a look at this doc for more information -
http://kubernetes.io/docs/admin/out-of-resource/
