### ISSUE TITLE
Should not support HPA for DaemonSet

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#48588] opened 2017-07-07 08:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig apps

**What happened**:
I can create a HPA policy for DaemonSet, this is not right as the DaemonSet do not have `replicas` and the HPA should validate this when create the HPA policy.

**What you expected to happen**:
The HPA should have some validation to make sure we cannot create HPA policy for DaemonSet.

**How to reproduce it (as minimally and precisely as possible)**:
1. HPA file as following:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: DaemonSet
    name: mysql
  targetCPUUtilizationPercentage: 10
```

2. Create the policy.
```
root@pc001:~/cases/ss# kubectl create -f ./hpa.yaml
horizontalpodautoscaler "autoscale" created
root@pc001:~/cases/ss# kubectl get hpa
NAME        REFERENCE         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
autoscale   DaemonSet/mysql   <unknown> / 10%   2         5         0          7s
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by DirectXMan12** [comment] 2017-07-31 15:17
@kubernetes/sig-autoscaling-bugs 

Fixing this properly would require plumbing discovery through the validation logic.

**Comment by deads2k** [comment] 2017-08-01 17:06
Given a loosely coupled, eventually consistent system, I don't think that failing during admission is a suitable solution. Having a Status condition (which may already exist) on the HPA makes sense so that a user can determine, "oh, I have a problem", but failing the resource directly or building a stateful check in validation (which could change over time) doesn't seem reasonable.

**Comment by DirectXMan12** [comment] 2017-08-01 17:10
To follow up on a question from #49093: 

> >    we can't ever (statically) know the entire list of objects that are scalable.
> Sorry, but isn't scalable a feature by design? I can't see what's vague here, please enlighten me.

"Scalability" is defined as the presence of the scale subresource. Therefore, anything without the scale subresource is not scalable.  There is no fixed list of objects guaranteed to be in the cluster.  *Even* if you blacklisted every *known* non-scalable kubernetes object, I could still introduce a non-scalable resource using an aggregated API server.  Even if you whitelisted every known scalable resource, I could still introduce a new scalable resource via an aggregated API server.

Ergo, a static/constant compile-time solution won't work. 

> The alternative approach is defining a object meta unscalable flag. If it's just a problem of a decent amount of refactoring. That's fine. WDYT?

No, there's already a way to do this.  We can simply look for any object in the discovery information that supports the scalable subresource.  However, as @deads2k and @thockin mention, this mostly goes against the conventions and principles that we've adhered to so far in Kubernetes.

> Having a Status condition (which may already exist) on the HPA makes sense so that a user can determine, "oh, I have a problem", but failing the resource directly or building a stateful check in validation (which could change over time) doesn't seem reasonable.

I think I mostly agree with this.  It *might* be nice to have a client-side warning (using discovery), but I'm wary of validating this server side.

**Comment by resouer** [comment] 2017-08-02 14:18
@DirectXMan12 @deads2k Thanks for explanation, its much clearer. 

One question is: how can HAP distinguish this exception status (caused by wrong scale target) from other failing status?

**Comment by DirectXMan12** [comment] 2017-08-02 17:33
We have a status condition on the HPA object (in autoscaling/v2alpha1) for issues fetching the scale, and other conditions for other issues.  A user could use that to see what the problem with their HPA was.

**Comment by resouer** [comment] 2017-08-13 12:32
One thing I would like to add is HPA will actually report if we set DS as HPA's target,
```
AbleToScale   False  
```
that's because we can not get `Scale` from `DaemonSet`.

```
root@haha:~# kubectl describe hpa autoscale
Name:                                                   autoscale
Namespace:                                              default
Labels:                                                 <none>
Annotations:                                            <none>
CreationTimestamp:                                      Sun, 13 Aug 2017 12:27:00 +0000
Reference:                                              DaemonSet/nginx-ds
Metrics:                                                ( current / target )
  resource cpu on pods  (as a percentage of request):   <unknown> / 10%
Min replicas:                                           2
Max replicas:                                           5
Conditions:
  Type          Status  Reason          Message
  ----          ------  ------          -------
  AbleToScale   False   FailedGetScale  the HPA controller was unable to get the target's current scale: User "system:serviceaccount:kube
-system:horizontal-pod-autoscaler" cannot get daemonsets.extensions/scale in the namespace "default". (get daemonsets.extensions nginx-ds
)
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  44s           3s              5       horizontal-pod-autoscaler                       Warning         FailedGetScale  User "system:serv
iceaccount:kube-system:ho
```

And after read thru all the comments here, I think we can close this issue actually. @thockin @DirectXMan12  @deads2k WDYT?

Since we have tell use this target is not scalable.

**Comment by DirectXMan12** [comment] 2017-08-15 18:44
> And after read thru all the comments here, I think we can close this issue actually.

SGTM.

**Comment by WIZARD-CXY** [comment] 2017-09-06 02:38
Maybe add a doc explicitly specify "HPA does not support object that can't scale like DaemonSet" is perfect

**Comment by resouer** [comment] 2017-09-06 02:43
@WIZARD-CXY Make sense, please sent out a doc PR.

**Closed by resouer** 2017-09-06 02:43 UTC
Labels: area/workload-api/daemonset, kind/bug, sig/api-machinery, sig/apps, sig/autoscaling

**Comment by WIZARD-CXY** [comment] 2017-09-06 03:07
@resouer will do sir
