### ISSUE TITLE
Spammy log messages in kubelet: metrics are not supported for MetricsNil Volumes

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#27373] opened 2016-06-14 17:12 UTC
These volumes don't support stats metrics, and yet the errors got printed out periodically for each pod. 

```
I0614 17:01:54.337456   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod kube-proxy-e2e-test-yjhong-minion-group-21rr_kube-system(b7c4ad73450e2cf13c9cb849231754c2) volume kubeconfig: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337464   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod kube-proxy-e2e-test-yjhong-minion-group-21rr_kube-system(b7c4ad73450e2cf13c9cb849231754c2) volume varlog: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337544   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod e2e-image-puller-e2e-test-yjhong-minion-group-21rr_kube-system(0d136a4468db307b8063df140402a70e) volume socket: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337563   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod e2e-image-puller-e2e-test-yjhong-minion-group-21rr_kube-system(0d136a4468db307b8063df140402a70e) volume docker: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337591   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod node-problem-detector-v0.1-oa8xn_kube-system(b9edf393-3187-11e6-8f11-42010af00002) volume log: metrics are not supported for MetricsNil Volumes
```

**Comment by asalkeld** [comment] 2016-09-08 23:48
duplicate of #20676

**Closed** 2016-09-12 18:20 UTC
Labels: kind/cleanup, priority/P2, team/node
