### ISSUE TITLE
ip-masq-agent not scheduling on 1.5 nodes with a 1.7 master

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#47752] opened 2017-06-19 22:02 UTC
https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-gci-1-7-upgrade-master is failing to run the follow up e2es because the ip-masq-agent daemonset is scheduling pods that get stuck in a pending state on 1.5 nodes. This short-circuits the logic for the skewed e2es, and they never run.

from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1-5-gci-1-7-upgrade-master/48

```
I0619 21:07:37.386] Jun 19 21:07:37.386: INFO: The status of Pod ip-masq-agent-6rzsv is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0619 21:07:37.387] Jun 19 21:07:37.386: INFO: The status of Pod ip-masq-agent-8nl2b is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0619 21:07:37.387] Jun 19 21:07:37.386: INFO: The status of Pod ip-masq-agent-vc1m3 is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0619 21:07:37.387] Jun 19 21:07:37.386: INFO: 12 / 15 pods in namespace 'kube-system' are running and ready (600 seconds elapsed)
I0619 21:07:37.388] Jun 19 21:07:37.386: INFO: expected 6 pod replicas in namespace 'kube-system', 6 are Running and Ready.
I0619 21:07:37.388] Jun 19 21:07:37.386: INFO: POD                  NODE                                          PHASE    GRACE  CONDITIONS
I0619 21:07:37.388] Jun 19 21:07:37.386: INFO: ip-masq-agent-6rzsv  gke-bootstrap-e2e-default-pool-1e4a389d-lhgs  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC ContainersNotReady containers with unready status: [ip-masq-agent]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:47:18 +0000 UTC  }]
I0619 21:07:37.388] Jun 19 21:07:37.387: INFO: ip-masq-agent-8nl2b  gke-bootstrap-e2e-default-pool-1e4a389d-7zjd  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC ContainersNotReady containers with unready status: [ip-masq-agent]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:47:19 +0000 UTC  }]
I0619 21:07:37.388] Jun 19 21:07:37.387: INFO: ip-masq-agent-vc1m3  gke-bootstrap-e2e-default-pool-1e4a389d-7139  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:45:05 +0000 UTC ContainersNotReady containers with unready status: [ip-masq-agent]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 20:47:19 +0000 UTC  }]
```

**Comment by dnardo** [comment] 2017-06-19 22:23
So I see that in 1.7.0 we start setting the non-masq-cidr to 0/0

gce/config-default.sh:NON_MASQUERADE_CIDR="0.0.0.0/0"
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L245

We set the addon if non-masq-cidr is 0/0
 if [[ "${NON_MASQUERADE_CIDR:-}" == "0.0.0.0/0" ]]; then
    setup-addon-manifests "addons" "ip-masq-agent"
 fi
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L1708

Also the agent cannot run on nodes prior to 1.7 so this seems to be correct.  Once the nodes are upgraded to 1.7 then the ip-masq agent should be running and should get out of the pending state.
I think this is just a general problem with the way addons are handled.  I may want to enable a new addon when a master is upgraded to 1.7 by default.  That addon may be a DaemonSet that wants to run on nodes meeting a certain criteria.  That criteria may not be met in 1.5 but may be met when they are updated to 1.7.

A few things that come to mind to fix this: 
-Fix the test's expectations to allow this until the nodes are updated to 1.7.
-rollback the PR that made this the default: https://github.com/kubernetes/kubernetes/commit/91ed74c0e9024c16b948fc7b9a67bdd5c052deae.
-set NON_MASQUERADE_CIDR=10.0.0.0/8 in the test properties so that the ip-masq-agent doesn't get added.

**Comment by bowei** [comment] 2017-06-19 22:55
It seems like the most conservative way forward is to revert the PR. Customers who want to use the feature can set the variable (`NON_MASQUERADE_CIDR`) during `kube-up.sh` to be able to get the feature.

What do you guys think?

**Comment by dchen1107** [comment] 2017-06-19 23:21
I think I asked the similar question related to ip-masq-agent, but my question was dropped. At this stage, I think reverting 91ed74c the preferred fix.

**Comment by dchen1107** [comment] 2017-06-20 00:00
ip-masq-agent was a daemonset introduced in 1.7 which I questioned at https://github.com/kubernetes/kubernetes/issues/46651#issuecomment-305866535. The problem is that after master is upgraded to 1.7, addons is trying to schedule ip-masq-agent daemonset to every node no matter which Kubelet version the node is on. The problem is that ip-masq-agent can only run on node with 1.7 release.

**Comment by dnardo** [comment] 2017-06-20 00:18
Even if we fix the test it doesn't fix GKE or any other environment where the master is upgraded to 1.7 and the nodes are < 1.7.  I think the real problem here is that there is no distinction between staging an addon and enabling an addon.  Essentially staging = running. So we end up adding labels to nodes as a  way of keeping the DaemonSet disabled until those labels are added to nodes.  While that works fine for addons that are DaemonDets, it doesn't work for deployments and replica sets.  I feel like this is going to happen again regardless of what we do here with ip-masq-agent.  It also creates a secondary step.  Who applies those addons?  What if they forget? what if it's deleted?

**Comment by roberthbailey** [comment] 2017-06-20 06:52
Fixed by https://github.com/kubernetes/kubernetes/pull/47764 (the formatting wasn't quite right in the IR to auto-close this issue).

**Comment by gmarek** [comment] 2017-06-20 10:59
#47764 got reverted as it broke tests.

**Closed** 2017-06-21 06:26 UTC
Labels: approved-for-milestone, area/upgrade, kind/upgrade-test-failure, priority/critical-urgent, sig/cluster-lifecycle, sig/network
