### ISSUE TITLE
apiserver keeps increasing in memory until it gets oomkilled

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#23323] opened 2016-03-22 10:30 UTC
We have a kubernetes 1.2 cluster where our apiserver keeps getting oomkilled every day or two. This is a pretty small cluster (4 nodes), and we're not sure why it only happens on this cluster. Memory usage constantly grows from less than 100MB at start to over 2GB when it will get oomkilled (the box has 4GB total ram). Restarting apiserver resets its memory usage to less than 100MB.

We have another medium cluster (12 nodes with lots of traffic) where apiserver memory usage is very stable, staying at around 700MB usage. Edit: This cluster got oomkilled as well, the memory growth was just much slower. Takes a few weeks.

I've attached pprof files for both. It seems most of the space usage is in the ugorji json decoder, followed by the etcd cache.

(@balooo was also looking at this with me.)

[memoryleak-pprof.inuse_objects.inuse_space.pb.gz](https://github.com/kubernetes/kubernetes/files/183911/memoryleak-pprof.inuse_objects.inuse_space.pb.gz)
[normal-pprof.inuse_objects.inuse_space.pb.gz](https://github.com/kubernetes/kubernetes/files/183912/normal-pprof.inuse_objects.inuse_space.pb.gz)

**Comment by jsravn** [comment] 2016-03-22 14:12
After some more analysis, this seems to be caused by the fact that we run jenkins slaves on this cluster which builds docker images on the node.

This has a couple effects:
 - Etcd watcher gets sent an updated minion entry much more frequently, as every build changes the list of docker images on the node.
- The etcd watcher entries  balloons in size - 170KB of data across the minions, vs ~20K for our other cluster.

So the size of json entries that need processing are much larger.

It still doesn't explain to me why memory keeps increasing - I'd expect the json decoder to release the memory after processing the etcd watch. But it doesn't seem to happen - memory keeps increasing.

**Comment by jsravn** [comment] 2016-03-22 14:46
In case anyone doesn't want to download the pprof files:

normal (or not - it still has unusual patterns):
```
(pprof) text
675.05MB of 695.72MB total (97.03%)
Dropped 1330 nodes (cum <= 3.48MB)
Showing top 10 nodes out of 101 (cum >= 3.50MB)
      flat  flat%   sum%        cum   cum%
  369.02MB 53.04% 53.04%   369.02MB 53.04%  github.com/ugorji/go/codec.(*jsonDecDriver).DecodeString
  256.68MB 36.89% 89.94%   257.18MB 36.97%  reflect.Value.call
   28.51MB  4.10% 94.03%    28.51MB  4.10%  reflect.New
    6.57MB  0.94% 94.98%     6.57MB  0.94%  github.com/beorn7/perks/quantile.NewTargeted
    5.67MB  0.82% 95.79%     5.67MB  0.82%  io.Copy
    3.59MB  0.52% 96.31%     3.59MB  0.52%  crypto/tls.(*block).reserve
       2MB  0.29% 96.60%   352.52MB 50.67%  k8s.io/kubernetes/pkg/api/v1.(*NodeStatus).codecDecodeSelfFromMap
    1.51MB  0.22% 96.81%     8.08MB  1.16%  github.com/prometheus/client_golang/prometheus.newSummary
       1MB  0.14% 96.96%        9MB  1.29%  k8s.io/kubernetes/pkg/api/v1.(*NodeCondition).codecDecodeSelfFromMap
    0.50MB 0.072% 97.03%     3.50MB   0.5%  k8s.io/kubernetes/pkg/api/resource.(*Quantity).UnmarshalJSON
(pprof) 
```

memoryleak:
```
(pprof) text
1687.05MB of 1707.27MB total (98.82%)
Dropped 1239 nodes (cum <= 8.54MB)
Showing top 10 nodes out of 58 (cum >= 13.64MB)
      flat  flat%   sum%        cum   cum%
 1067.07MB 62.50% 62.50%  1067.07MB 62.50%  github.com/ugorji/go/codec.(*jsonDecDriver).DecodeString
  572.33MB 33.52% 96.02%   572.33MB 33.52%  reflect.Value.call
   29.51MB  1.73% 97.75%    29.51MB  1.73%  reflect.New
   12.14MB  0.71% 98.46%    12.14MB  0.71%  github.com/beorn7/perks/quantile.NewTargeted
       3MB  0.18% 98.64%    23.50MB  1.38%  k8s.io/kubernetes/pkg/api/v1.(*ObjectMeta).codecDecodeSelfFromMap
       2MB  0.12% 98.76%  1041.57MB 61.01%  k8s.io/kubernetes/pkg/api/v1.(*NodeStatus).codecDecodeSelfFromMap
       1MB 0.059% 98.82%    13.14MB  0.77%  github.com/prometheus/client_golang/prometheus.newSummary
         0     0% 98.82%    10.12MB  0.59%  github.com/emicklei/go-restful.(*Container).dispatch
         0     0% 98.82%    10.12MB  0.59%  github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm
         0     0% 98.82%    13.64MB   0.8%  github.com/prometheus/client_golang/prometheus.(*MetricVec).GetMetricWithLabelValues
```

**Comment by jsravn** [comment] 2016-03-22 14:54
It looks like this was made obvious by https://github.com/kubernetes/kubernetes/pull/18248 which exposes images on the node status (which can be a large string as it includes all docker images currently pulled on that node regardless of whether they are running).

**Comment by zhouhaibing089** [comment] 2016-03-22 15:50
If this is caused by image status report, I think @yujuhong may have some thoughts.

**Comment by yujuhong** [comment] 2016-03-22 16:37
> Etcd watcher gets sent an updated minion entry much more frequently, as every build changes the list of docker images on the node.
> The etcd watcher entries balloons in size - 170KB of data across the minions, vs ~20K for our other cluster.
> So the size of json entries that need processing are much larger.

I believe we update node status at a fixed frequency, even though a larger object is expected at each update with the image list.

> 
> It still doesn't explain to me why memory keeps increasing - I'd expect the json decoder to release the memory after processing the etcd watch. But it doesn't seem to happen - memory keeps increasing.

Memory leak seems like a bigger issue. cc @wojtek-t (for the generated code) @lavalamp

**Comment by lavalamp** [comment] 2016-03-22 17:03
@yujuhong Nothing in that limits the number of images reported-- we should probably not have fields that can grow without bound in our API. But I agree it seems likely that there's a memory leak in ugorji-- I'll look for it in a little bit.

**Comment by lavalamp** [comment] 2016-03-22 17:46
So this doesn't look like a leak in ugorji, I think there's just a ton of strings being stored--that's just where they're allocated. Does the memory grow slowly or quickly?

If I get 42kB per minion per OP's report (170kB/4), and we have a cache of 1000 entries, that's ~4.2MB. If I misunderstood and it's 170k per node status, that's still just 170MB. However we may keep more than one copy.

I would expect memory to get up to its max size in 1000*10 seconds, that's under 3 hours. Is it possible that apiserver is using more than its fair share but doesn't get killed until something else spikes?

**Comment by jsravn** [comment] 2016-03-22 18:37
> So this doesn't look like a leak in ugorji, I think there's just a ton of strings being stored--that's just where they're allocated. Does the memory grow slowly or quickly?

It seems to grow slowly. api-server starts out at about 200MB and takes about a day to oom at above 2GB.  The minion entry is 30K. For my non-jenkins clusters it's ~8K. I suspect the watcher gets triggered more often as well since the image list is changing when building docker images constantly. Not sure if kubelet's GC also kicks in here.

**Comment by wojtek-t** [comment] 2016-03-22 19:40
>
If I get 42kB per minion per OP's report (170kB/4), and we have a cache of 1000 entries, that's ~4.2MB. If I misunderstood and it's 170k per node status, that's still just 170MB. However we may keep more than one copy.

I'm pretty sure we can find more than a single copy of an object. But even if we assume say 5 copies of each object (which I think might not be far from the truth), then it's still significantly less than those 2GB.

Regarding memory in all our caches - if the leak was there because of nodes, then we should also observe the leak in the other cluster (probably slower leak, but still). If we don't observe it, I would suspect something different.

@jsravn - are you using official release or you built it yourself?

**Comment by lavalamp** [comment] 2016-03-22 20:07
@jsravn can you get a goroutine dump? (visit `/debug/pprof/goroutine?debug=2`) Maybe something else is going on?

**Comment by jsravn** [comment] 2016-03-23 00:43
@wojtek-t it is built from https://github.com/sky-uk/kubernetes/tree/cirrus-release which was cut from master a couple weeks ago, using `make release`. My plan was to rebase this against more recent master to see if anything fixes it but I didn't see anything obvious in commits since then.

@lavalamp I will get that tomorrow

**Comment by yujuhong** [comment] 2016-03-23 00:52
@jsravn, could you also do some spot/sanity checks of `kubectl get node -o yaml` to see how the image list grows over time?

**Comment by wojtek-t** [comment] 2016-03-23 07:09
@jsravn - ok, if you are using make release that's fine. Basically my fear was that you may be using a different go version that we are using (we observed different performance issues with Go 1.5), but it seems it's not the case.

**Comment by jsravn** [comment] 2016-03-23 10:48
Here's the goroutine and heap dump for this morning 

[goroutines-20160323-1043.txt](https://github.com/kubernetes/kubernetes/files/185805/goroutines-20160323-1043.txt)
[pprof.inuse_objects.inuse_space-20160323-1043.pb.gz](https://github.com/kubernetes/kubernetes/files/185806/pprof.inuse_objects.inuse_space-20160323-1043.pb.gz)

**Comment by jsravn** [comment] 2016-03-23 14:12
@yujuhong I've attached a couple hours of running `kubectl get node -o yaml | wc -l`

[nodeyamlcounts.txt](https://github.com/kubernetes/kubernetes/files/186137/nodeyamlcounts.txt)

**Comment by jsravn** [comment] 2016-03-23 15:52
This revealed another potential problem to us. After the apiserver restarted after oomkill, half of our nodes got marked `NodeNotReady`, I guess because kubelet had been unable to report its status to the apiserver. Despite the nodes being fine themselves - this then caused all of our pods to get rescheduled onto the other nodes.

This seems pretty dangerous - it means apiserver going down could potentially wreak an entire cluster by marking a significant number of nodes as offline. It seems instead there should be some grace period after apiserver restarts where it gives kubelet a chance to report in on all nodes.

**Comment by wojtek-t** [comment] 2016-03-23 16:57
@jsravn - there is grace period - IIRC it is 5 minutes (@gmarek can you confirm?)
So there is something strange happening.
It would be useful if you could give us logs of apiserver and controller manager.

**Comment by yujuhong** [comment] 2016-03-23 16:58
> @yujuhong I've attached a couple hours of running kubectl get node -o yaml | wc -l

Thanks! The number fluctuated over time, indicating that 1) image GC was probably removing some images, and 2) we didn't falsely append the image list. We can rule these two out for now.

**Comment by gmarek** [comment] 2016-03-23 22:04
@jsravn - yes, exactly for this reason we have two failsafes in place. One is 5 minute grace period (NC won't delete anything before it's seen as not ready for 5 minutes). Second is rate limiting the deletion. Currently we allow 10 Nodes to be killed in burst and after that 1 per 10 seconds (or sth. like that) - you can set those numbers by yourself as flags in controller manager (`DeletingPodsBurst ` and `DeletingPodsQPS`), as default numbers are probably not ones that fit your size of the cluster. There's a PR in flight to change those number to some percentage of the size of the cluster.

**Comment by lavalamp** [comment] 2016-03-23 23:13
@wojtek-t @mikedanese does the node controller give some extra time after an apiserver outage? Like, maybe it shouldn't count apiserver-down time as down-time for each node. I imagine a scenario where apiserver went down for > 5 minutes and the instant it came back, node controller started killing pods, but that seems wrong.

**Comment by lavalamp** [comment] 2016-03-23 23:53
OK, I don't see anything obvious in the goroutine list.

**Comment by vishh** [comment] 2016-03-24 00:25
@jsravn: Is docker in docker an option for you?

**Comment by gmarek** [comment] 2016-03-24 09:26
@lavalamp - it currently doesn't. There's a long standing issue #13430 for those things. It never were prioritized high enough for anyone to care though.

**Comment by jsravn** [comment] 2016-03-24 10:09
Having an upper limit on node deletion (from #13430) sounds like a really great idea and would give me more confidence. I think there also should be a grace period after apiserver starts before nodes get deleted (> node sync time).

**Comment by gmarek** [comment] 2016-03-24 10:49
For the former I wrote a small PR (#20979), but it still waits for some love. Currently you can set your Burst value to 1 and QPS to 0.01 (1 machine per 100 seconds) or sth like that.

The latter is more tricky, as it'd require NodeController to know if API server got restarted. In the "local" config, where we're running everything on a single machine we can do that, as local loop shouldn't ever be down. For HA is more complicated and I don't know if we want to do that. @mikedanese

**Comment by lavalamp** [comment] 2016-03-24 20:56
I think node controller needs to watch apiserver's health. We can take this up in a different issue though.

**Comment by jsravn** [comment] 2016-04-04 10:57
@vishh Docker in docker looks promising. However, we saw our apiserver fall over after a couple weeks in our development (non-jenkins) cluster. So the leak seems to be there regardless, it's just made worse for whatever reason in our Jenkins kubernetes where it dies daily. So I don't think it would help us much other than delay the inevitable oom death. Our current workaround is to restart apiserver when it exceeds 1.5GB memory usage.

**Comment by jsravn** [comment] 2016-04-05 15:46
I got apiserver to max out at ~270MB of heap usage by shrinking the etcd cache:

```
diff --git a/pkg/storage/etcd/etcd_helper.go b/pkg/storage/etcd/etcd_helper.go
index f3ef8f8..420854c 100644
--- a/pkg/storage/etcd/etcd_helper.go
+++ b/pkg/storage/etcd/etcd_helper.go
@@ -718,7 +718,7 @@ type etcdCache interface {
        addToCache(index uint64, obj runtime.Object)
 }
 
-const maxEtcdCacheEntries int = 50000
+const maxEtcdCacheEntries int = 50
 
 func getTypeName(obj interface{}) string {
        return reflect.TypeOf(obj).String()
```

Any idea the expected max heap of apiserver w/ a cache of 50k etcd objects? Does the cache expire old objects? Given that a node now contains a string list of all its images - I think this cache size may be too large.

**Comment by gmarek** [comment] 2016-04-05 18:09
cc @wojtek-t

**Comment by mkulke** [comment] 2016-04-06 09:09
We're also seeing increased memory usage of kube-apiserver on a `1.2.0` master:

![2016-04-06-093008_591x318_scrot](https://cloud.githubusercontent.com/assets/273280/14310836/51e080c6-fbe4-11e5-80a9-3b41fadeb059.png)

I did some profiling:

![prof](https://cloud.githubusercontent.com/assets/273280/14311502/098da2dc-fbe8-11e5-9543-eae352ca3fb5.png)

```
go tool pprof -inuse_space http://localhost:8080/debug/pprof/heap
Fetching profile from http://localhost:8080/debug/pprof/heap
Saved profile in /home/kulke/pprof/pprof.localhost:8080.inuse_objects.inuse_space.003.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
322.32MB of 344.98MB total (93.43%)
Dropped 1023 nodes (cum <= 1.72MB)
Showing top 5 nodes out of 99 (cum >= 4.64MB)
      flat  flat%   sum%        cum   cum%
  186.09MB 53.94% 53.94%   186.09MB 53.94%  reflect.Value.call
  103.50MB 30.00% 83.94%   103.50MB 30.00%  github.com/ugorji/go/codec.(*jsonDecDriver).DecodeString
   21.51MB  6.24% 90.18%    21.51MB  6.24%  reflect.New
    6.57MB  1.90% 92.08%     6.57MB  1.90%  github.com/beorn7/perks/quantile.NewTargeted
    4.64MB  1.35% 93.43%     4.64MB  1.35%  io.Copy
```

and

```
go tool pprof -alloc_space http://localhost:8080/debug/pprof/heap
Fetching profile from http://localhost:8080/debug/pprof/heap
Saved profile in /home/kulke/pprof/pprof.localhost:8080.alloc_objects.alloc_space.002.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
26.24GB of 51.09GB total (51.37%)
Dropped 882 nodes (cum <= 0.26GB)
Showing top 5 nodes out of 242 (cum >= 3.11GB)
      flat  flat%   sum%        cum   cum%
    9.17GB 17.95% 17.95%     9.17GB 17.95%  reflect.Value.call
    8.43GB 16.51% 34.46%     8.43GB 16.51%  bytes.makeSlice
    3.52GB  6.89% 41.35%     3.52GB  6.89%  github.com/ugorji/go/codec.(*jsonDecDriver).appendStringAsBytes
    2.72GB  5.33% 46.67%     2.72GB  5.33%  math/big.nat.make
    2.40GB  4.69% 51.37%     3.11GB  6.10%  math/big.nat.divLarge
```

```
go tool pprof http://localhost:8080/debug/pprof/profile
Fetching profile from http://localhost:8080/debug/pprof/profile
Please wait... (30s)
Saved profile in /home/kulke/pprof/pprof.localhost:8080.samples.cpu.003.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) text
790ms of 1090ms total (72.48%)
Showing top 10 nodes out of 305 (cum >= 20ms)
      flat  flat%   sum%        cum   cum%
     490ms 44.95% 44.95%      490ms 44.95%  scanblock
      80ms  7.34% 52.29%       80ms  7.34%  runtime.MSpan_Sweep
      40ms  3.67% 55.96%       40ms  3.67%  runtime.mallocgc
      30ms  2.75% 58.72%       30ms  2.75%  crypto/elliptic.p256ReduceDegree
      30ms  2.75% 61.47%       30ms  2.75%  github.com/ugorji/go/codec.(*bytesDecReader).readn1
      30ms  2.75% 64.22%       30ms  2.75%  math/big.addMulVVW
      30ms  2.75% 66.97%       40ms  3.67%  syscall.Syscall
      20ms  1.83% 68.81%       20ms  1.83%  runtime.atomicstore
      20ms  1.83% 70.64%       40ms  3.67%  runtime.makeslice
      20ms  1.83% 72.48%       20ms  1.83%  runtime.readvarint
```

**Comment by jsravn** [comment] 2016-04-06 14:15
> Does the cache expire old objects?

No, it doesn't, unfortunately... It randomly deletes objects when the cache gets full. This makes a smaller cache size more problematic.

I'm working on a PR to make the cache size configurable. I haven't seen any drawbacks to having a cache size of 50 for my smallish clusters (10s of nodes).

**Comment by wojtek-t** [comment] 2016-04-06 14:26
This is LRU cache, but it's possible that there are few versions of the same object in this cache.

To be honest, once we switch to proto, we probably will be able to get rid of this cache. But short term it makes sense to make its size configurable.

**Comment by jsravn** [comment] 2016-04-06 14:31
> This is LRU cache

Did it change recently? Looking at `util/cache/cache.go`, it just deletes a random item when it gets full. Maybe I'm looking at the wrong place. If it was LRU I'd be happier setting the value lower.
```
func (s *cacheShard) add(index uint64, obj interface{}) bool {
	s.Lock()
	defer s.Unlock()
	_, isOverwrite := s.items[index]
	s.items[index] = obj
	if len(s.items) > s.maxSize {
		var randomKey uint64
		for randomKey = range s.items {
			break
		}
		delete(s.items, randomKey)
	}
	return isOverwrite
}
```

**Comment by wojtek-t** [comment] 2016-04-06 14:41
ohh - maybe you're right - it removes random element
But still, there won't be more than 50k elements

**Comment by lavalamp** [comment] 2016-04-06 18:29
@wojtek-t Do we serve lists out of this cache after removing a random element?

**Comment by lavalamp** [comment] 2016-04-06 18:32
Is this the cache that stores changes from etcd? If so it's very wrong to remove a random element. It must be some other cache?

**Comment by wojtek-t** [comment] 2016-04-06 20:47
@lavalamp - no, it's a different cache

**Comment by wojtek-t** [comment] 2016-04-06 20:47
this cache was already added before 1.0 release

**Comment by mkulke** [comment] 2016-04-12 08:01
I've been watching that for a few days. Memory usage of `kube-apiserver` seems to top out at ~900MB. There's about 50 rc's and services in this cluster, the small CPU spikes and bumps in memory usage correlate with batch-deployments on a "nightly" stage. We also have `1.0.6` clusters of the same size and they use less (~200mb) memory. Not a problem, but maybe the specs for a master should be bumped to 2G min.

![2016-04-12-093959_547x556_scrot](https://cloud.githubusercontent.com/assets/273280/14453381/be273cca-0094-11e6-913b-6d0618840bf1.png)

**Comment by jsravn** [comment] 2016-04-12 11:18
@mkulke it will change based on workload, since it's the deserialized JSON strings of apiserver types. #23914 makes the cache size configurable and also lowers it to 1000 from 50k. In my worst cluster (where it does jenkins builds of docker containers, which bloats the NodeStatus object size), 5000 entries gives me ~1GB max memory footprint, the default 50K oomkilled and kept growing past 2-3GB.

**Comment by albertsun** [comment] 2016-12-21 17:18
We think we've been bitten by this issue in a Kubernetes 1.2 cluster we're running. Does anyone know if this is resolved in later releases of Kubernetes?

**Comment by jsravn** [comment] 2016-12-21 17:19
@albertsun later releases use protobufs so it shouldn't be as big an issue. However the json protocol is still there, so any components (like third party controllers) may still cause the memory bloat.

**Comment by mkulke** [comment] 2016-12-21 20:45
@jsravn @albertsun 

hi, in our case the problem was related to an architectural flaw/oddity with `kube-proxy`. back then, there was only a user-space tcp proxy implementation, which was subject to an DOS scenario: 

We had misbehaving pods deployed in our cluster, which opened a lot of connections and sometimes did not properly close sockets, but leave them in `FIN_WAIT2/CLOSE_WAIT` state. 

kube-proxy was keeping the respective proxy-channels open forever, and thus leaking file handles and goroutines. This behaviour is not really wrong (in fact it can be argued that it's a flaw in the tcp protocol, since whether and when to time out and garbage collect connections in this state is not specified by the spec), but it cannot be handled properly in user-space and will either crash kube-proxy (because it hits fd limits) or cause excessive ram usage (when the max-fd settings are high).

Since then an iptables-based proxy implementation `--proxy-mode iptables` has been added and made the default later. This moves the connection handling to the kernel where it's handled properly and our problem disappeared. Are you using this option?

**Comment by albertsun** [comment] 2016-12-21 22:00
@mkulke Yes, we're using `--proxy-mode=iptables`.

What happened to our cluster seems to match what's described here https://github.com/kubernetes/kubernetes/issues/23323#issuecomment-200406356 very closely. We run each component of the cluster with a Fleet service file on CoreOS instances. Have 3 controller nodes with 4GB of memory each, and 8 worker nodes with 32GB of memory.

This manifested for us first with many nodes marking themselves as `NodeNotReady` and evicting all their pods. This caused (or compounded) a CPU spike in the controller cluster nodes to the point where we couldn't connect to them. Somewhere in that timeframe the scheduler service also died and removed itself instead of restarting. So when the worker nodes eventually came back and marked themselves as ready all pods remained in `Pending` instead of scheduling themselves.

Just poking around in the aftermath, the controller nodes do seem to be using lots of memory and restarting the kube-apiserver process frees it all up and then it again starts to increase slowly.

Anyway, thanks @jsravn sounds like upgrading to a more recent version of Kubernetes is the way to go for us.

**Comment by mikedanese** [comment] 2016-12-21 22:02
This is probably fixed now so I'm going to close.

**Closed by mikedanese** 2016-12-21 22:02 UTC
Labels: sig/api-machinery

**Comment by Starefossen** [comment] 2017-01-09 14:24
We are seeing a slow and steady increase of memory usage for kube-apiserver on Kubernetes v1.5.1 with `--proxy-mode=iptables`.

<img width="1385" alt="screen shot 2017-01-09 at 15 23 46" src="https://cloud.githubusercontent.com/assets/968267/21769582/b673fb3c-d67f-11e6-9808-e7270eaea342.png">

**Comment by gmarek** [comment] 2017-01-09 14:50
I don't think the `proxy-node` is important here, as it shouldn't impact api-server at all.

@smarterclayton @wojtek-t @timothysc

**Comment by wojtek-t** [comment] 2017-01-16 09:50
Do you have a memory profile you could paste here? It would be good to know where we are leaking memory (if we are leaking it - this may just be organic growth that will stop at some point, when we will full all the caches etc.).

**Comment by timothysc** [comment] 2017-01-16 14:01
@wojtek-t @gmarek This original report was kube 1.2...

I'm inclined to let this lay and if there are issues seen in latest revs, folks can reopen.

**Comment by wojtek-t** [comment] 2017-01-16 14:59
Ohh - I though it was a new issue. I agree, we should open another one if this is a new issue.
