### ISSUE TITLE
Recreated nodes don't get PodCIDR immediately

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#25220] opened 2016-05-05 20:20 UTC
I'm still investigating, but it looks like when we recreate nodes with the same name as an old node, the new node can't start Docker properly because it doesn't have a PodCIDR, and must wait ~5 minutes to get one.  My guess is that the NodeController doesn't hand the new node a new PodCIDR until it's been reporting itself Unhealthy for at least 5 minutes.

This is causing unnecessary (I think) disruption during node upgrades.

**Comment by spzala** [comment] 2017-08-09 15:23
@ihmccreery hi, since it's over a year this issue was reported, a gentle touch base on if the issue is still valid with latest k8s release or close it for now, and reopen if someone hit it in future?. Unfortunately I don't have env to recreate otherwise would have tried to verify it myself. Thanks!!

**Closed** 2017-12-13 05:43 UTC
Labels: area/kubelet, area/nodecontroller, area/upgrade, sig/node, team/control-plane (deprecated - do not use)
