### ISSUE TITLE
Unit test flake: k8s.io/kubernetes/pkg/registry/generic/registry TestStoreList panic

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#25691] opened 2016-05-16 21:08 UTC
```
=== RUN   TestStoreList
--- FAIL: TestStoreList (18.93s)
	utils.go:245: Unexpected error in waitUntilUp (timeout on waiting for etcd cluster)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ae450]

goroutine 117 [running]:
panic(0x1d58de0, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.tRunner.func1(0xc82000e360)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1d58de0, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x521
k8s.io/kubernetes/pkg/registry/generic/registry.NewTestGenericStoreRegistry(0xc82000e360, 0x38, 0xc8200e8300)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/registry/store_test.go:93 +0xca0
k8s.io/kubernetes/pkg/registry/generic/registry.TestStoreList(0xc82000e360)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/registry/store_test.go:215 +0x1a2d
testing.tRunner(0xc82000e360, 0x2c26500)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/kubernetes/pkg/registry/generic/registry	19.218s
```

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25540/kubernetes-pull-test-unit-integration/26143/

**Comment by fejta** [comment] 2016-05-23 22:35
Assigning to @smarterclayton per  https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/OWNERS

**Comment by smarterclayton** [comment] 2016-05-24 18:48
@timothysc etcd failed to come up within a reasonable window, i don't see a recent etcd bump, so this seems more likely that CPU was so heavily starved that we didn't start within 5s.

**Comment by smarterclayton** [comment] 2016-05-24 18:49
Dupe of #25278

**Comment by timothysc** [comment] 2016-05-26 19:44
I'll re-open this one to investigate, as the results look different then the other test.

**Comment by timothysc** [comment] 2016-05-27 13:47
So I ran a number of experiments locally and here are my results.  

When running 100's of iterations I had 0 failures.  So I decided to try testing to see what happens when I do too many tests in parallel.  Using a simple script: 

``` 
#!/bin/sh

for i in {1..20}
do
	go test -timeout 120s k8s.io/kubernetes/pkg/registry/generic/registry &
done
```

I can essentially peg my cpu, hit swap, and cause timeouts.  In general, I think a lot of these flakes are due to running too many jobs concurrently.  Ideally, we should use kubernetes to build kubernetes and monitor resource usage.  Also our build+test is a ginormous resource PIG. 

/cc @kubernetes/sig-testing 

I'm going to close this issue and open a new one to try and eliminate the root cause.

**Closed by timothysc** 2016-05-27 13:47 UTC
Labels: kind/flake, team/control-plane
