### ISSUE TITLE
kubectl apply -f of a DaemonSet with an updated container image does not update the pods of the DaemonSet

### ISSUE THREAD

**Issue by jacobgmathew** [kubernetes/kubernetes#29199] opened 2016-07-19 14:17 UTC
I have a DaemonSet configured as follows:

`daemonset.yaml`
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bugreport-daemonset
spec:
  template:
    metadata:
      labels:
        app: bugreport
    spec:
      containers:
      - name: bugreport-container
        image: gcr.io/bug-project/testcontainer:tag0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
```

When I run `kubectl apply -f daemonset.yaml` i can see the pods running on each node.

But if I change the image to `gcr.io/bug-project/testcontainer:tag1` and then run `kubectl apply -f daemonset.yaml` again, the pods are never updated with the new container image.

**Comment by lukaszo** [comment] 2016-07-19 14:37
It's missing feature. It's on the roadmap. For more details see here #22543 and here #15310.

I think you can close it as a duplicate of #22543

**Closed** 2016-07-19 15:30 UTC
