### ISSUE TITLE
[e2e failure] GCE serial and GCI GCE serial are failing to come up

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52286] opened 2017-09-11 16:51 UTC
@kubernetes/kubernetes-release-managers 
@kubernetes/test-infra-maintainers 
@kubernetes/sig-testing-bugs 
/kind e2e-test-failure

GCE serial and GCI GCE serial started failing last evening

https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial

**Comment by krzyzacy** [comment] 2017-09-11 17:18
https://k8s-testgrid.appspot.com/release-1.7-all#gci-gce-serial-release-1-7 is still green, I would suspect something ~last Friday afternoon gets merged

**Comment by dchen1107** [comment] 2017-09-11 18:27
Here is what I found, after a while, the node lost their authorization to connect to API server. I believe this has the same root cause as 

https://github.com/kubernetes/kubernetes/issues/52282#issuecomment-328615038

**Comment by dchen1107** [comment] 2017-09-11 18:29
I am going to revert offending pr (#51844) to see if it helps.

**Closed** 2017-09-12 00:26 UTC
Labels: kind/bug, kind/e2e-test-failure, milestone-labels-complete, priority/critical-urgent, sig/testing
