### ISSUE TITLE
Horizontal pod autoscaling tests don't work

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#14667] opened 2015-09-28 18:11 UTC
```
Horizontal pod autoscaling [Skipped][Autoscaling Suite] should scale from 5 pods to 3 pods and from 3 to 1 (scale resource: Memory)

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:149
Sep 28 09:06:15.915: timeout waiting 10m0s for pods size to be 3

Horizontal pod autoscaling [Skipped][Autoscaling Suite] should scale from 1 pod to 3 pods (scale resource: CPU)

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:42
Sep 28 09:40:07.245: timeout waiting 10m0s for pods size to be 3
```

**Comment by jszczepkowski** [comment] 2015-09-28 19:45
Duplicate of #14656.

**Comment by piosz** [comment] 2015-10-05 18:35
The test failed 9 times in the last 30 runs. Reopening.

**Comment by piosz** [comment] 2015-10-05 18:42
Also the test failed during last 3 runs so increasing the priority.

**Comment by brendandburns** [comment] 2015-10-06 23:47
Two more failures today.  Is this being actively worked on?

**Comment by piosz** [comment] 2015-10-07 05:28
Yes. Both @jszczepkowski and me. We are close to the solution I believe.
7 paź 2015 1:48 AM "Brendan Burns" <notifications@github.com> napisał(a):

**Comment by jszczepkowski** [comment] 2015-10-07 12:55
There are two problems here:
1. resource consumers sometimes get silently killed (unknown resasons),
2. memory limites for resource conusmer were too low.
My PR (#15218) solved the second problem, which is enough to make the test stable. The first problem is still mystery to us.

**Closed** 2015-10-08 05:34 UTC
Labels: area/autoscaling, area/test, kind/flake, priority/P0
