### ISSUE TITLE
Docker in Docker conflicts with kubelet

### ISSUE THREAD

**Issue by julyclyde** [kubernetes/kubernetes#18202] opened 2015-12-04 07:29 UTC
I'm running kubelet 1.03 with Docker 1.7.1 or 1.8.2 on a CentOS 7.1.1503
When I run docker.service alone, without kubelet, the file /proc/PID_OF_DOCKER/cgroup was as below:
10:hugetlb:/
9:perf_event:/
8:blkio:/system.slice
7:net_cls:/
6:freezer:/
5:devices:/system.slice
4:memory:/system.slice
3:cpuacct,cpu:/system.slice
2:cpuset:/
1:name=systemd:/system.slice/docker.service
All of them existed under /sys/fs/cgroup/systemd/ . In this situation, docker-in-docker works.

Then I run kubelet, the file content changed to:
10:hugetlb:/
9:perf_event:/docker-daemon
8:blkio:/docker-daemon
7:net_cls:/
6:freezer:/docker-daemon
5:devices:/docker-daemon
4:memory:/docker-daemon
3:cpuacct,cpu:/docker-daemon
2:cpuset:/docker-daemon
1:name=systemd:/system.slice/docker.service
All of them except 1:name exist under /sys/fs/cgroup/ .

This caused a error when I run another docker container within a privileged docker container.
The error message was:
Error response from daemon: Cannot start container 8faa1dfa3721ce64b01969f3d84a9206c432eb5579462c2464b78acd112cd858: [8] System error: mkdir /sys/fs/docker-daemon: no such file or directory

I attach strace on the inner docker daemon, and caught the fact:
[pid    38] stat("/sys/fs/docker-daemon/docker/e747ddaa11766131c3147a160828ad1b6862e3bde29d82785f9679c3a47fd22e",  <unfinished ...>
it tried to access docker-daemon under /sys/fs/ . Firstly, /sys/fs/ is wrong place, secondly, find /sys/fs/ -name 'docker-daemon' gives nothing.

**Comment by dchen1107** [comment] 2015-12-04 17:02
cc/ @vishh

**Comment by gtaylor** [comment] 2015-12-11 00:20
Looks like we ran into this with Drone running within GKE. Reproducible case outlined on here: https://github.com/drone/drone/issues/1352

**Comment by vishh** [comment] 2015-12-11 00:24
Docker daemon's cgroup should not affect docker containers. This is a bug
in docker that is currently being fixed as part of their v1.10 release. I'm
closing this issue since there is no work to done from Kubelet side.

**Closed by vishh** 2015-12-11 00:24 UTC
Labels: team/node

**Comment by eliaslevy** [comment] 2016-01-22 21:29
@vishh do you know what the issue number is on the Docker side?  I am running into the same issue.

**Comment by vishh** [comment] 2016-01-22 22:36
Docker v1.10-rc1 has a new daemon flag `--cgroup-parent` and we can set
this to `/` in dind, assuming dind container's `/` cgroup is already mapped
to a separate cgroup on the host.

**Comment by eliaslevy** [comment] 2016-01-22 23:08
I upgraded to v1.10-rc1 and it solved my issue.  That said, I am not sure the error I was seeing was related to cgroups.  When I ran docker in debug mode after I upgraded, it went through the migration process, converting layers, images and containers to its new content addressable identification format.  While it did this it generated a couple of error messages that indicate some layers may have been corrupted:

```
DEBU[0000] could not get checksum for "6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8" with tar-split: "stat /var/lib/docker/overlay/6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8: no such file or directory" 
ERRO[0000] could not calculate checksum for "6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8", "stat /var/lib/docker/overlay/6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8: no such file or directory" 
...
ERRO[0008] migration failed for 6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8, err: open /var/lib/docker/graph/6757e4969a952ed6af25b427f646b2e8b8c722a7ab63594de497b8894bb237b8/.migration-diffid: no such file or directory 
...
ERRO[0008] image not migrated                           
```

It is possible these layers become corrupted somehow and that was resulting in the cryptic `System error: mkdir /sys/fs/docker-daemon: no such file or directory` message.  Migration seems to have culled these layers, which is why it may be working now.

**Comment by vishh** [comment] 2016-01-23 00:18
I'd suggest posting this question in the docker-dev mailing list. FYI: I
updated my host daemon recently to v1.10-rc1 and I did not face any issues.

**Comment by aalexand** [comment] 2016-02-03 08:14
@vishh Curious: experimenting with Docker v1.10-rc3 on the host, I am seeing that the cgroup for the inner docker daemon resets to /docker-daemon at some point and from that point I can't start an inner container.  Is this intentional?  Is it kubelet changing the cgroup for any docker daemon process whether it's the outer or an inner one?  I'm using Docker 1.9.1 as the inner Docker.

```
root@81950eac5506:/# cat /proc/109/cgroup 
9:perf_event:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
8:net_cls,net_prio:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
7:freezer:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
6:devices:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
5:memory:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
4:blkio:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
3:cpu,cpuacct:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
2:cpuset:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
1:name=systemd:/system.slice/docker.service

root@81950eac5506:/# cat /proc/109/cgroup 
9:perf_event:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
8:net_cls,net_prio:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
7:freezer:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
6:devices:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
5:memory:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
4:blkio:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
3:cpu,cpuacct:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
2:cpuset:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
1:name=systemd:/system.slice/docker.service

root@81950eac5506:/# cat /proc/109/cgroup 
9:perf_event:/docker-daemon
8:net_cls,net_prio:/docker/81950eac55062e5d8e7b5567d1036e4b146dfe212bdc9263c97347e6ce86b904
7:freezer:/docker-daemon
6:devices:/docker-daemon
5:memory:/docker-daemon
4:blkio:/docker-daemon
3:cpu,cpuacct:/docker-daemon
2:cpuset:/docker-daemon
1:name=systemd:/system.slice/docker.service

root@81950eac5506:/# docker run -ti --privileged busybox
Error response from daemon: Cannot start container 8c20805c8e09641aa19846f502c62b422c826ef5ce5e423c063f8dc3a1ce7286: [8] System error: mkdir /sys/fs/docker-daemon: operation not permit
ted

root@81950eac5506:/# exit
exit
aalexand@instance-4:~$ kubelet --version
Kubernetes v1.0.2
```

**Comment by vishh** [comment] 2016-02-03 22:51
That might be kubelet. It tries to move the docker daemon on the host into
`/docker-daemon` cgroup as of now. This is an issue.

On Wed, Feb 3, 2016 at 12:15 AM, Alexey Alexandrov <notifications@github.com

**Comment by aalexand** [comment] 2016-02-03 22:57
It probably should not move the inner docker process to the docker-daemon
cgroup.  That should probably stay under the container hierarchy so that
it's accounted to the container subtree rather than somewhere else?  And it
seems to confuse docker as /docker-daemon is not under the container cgroup
tree, which is what mounted inside of container's /sys/fs/cgroup.
