### ISSUE TITLE
AWS Feature: Autoscaling of nodes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23480] opened 2016-03-25 12:43 UTC
Our nodes run in an autoscaling group, but we don't currently autoscale them.

We should set up some rules to enable autoscaling.  Ideally we would also publish custom metrics to enable k8s-specific autoscaling, or we would drive autoscaling from within k8s.

**Comment by dmcnaught** [comment] 2016-03-25 14:31
@justinsb it seems like autoscaling k8s nodes makes most sense when the nodes run out of resources for new pods or the horizontal scaling of pods (cpu, ram). I've been wondering if using any AWS metrics for node autoscaling makes sense...

**Comment by binarybana** [comment] 2016-03-25 17:03
I like the proposal language laid out in #15304. From there it seems logical that the autoscaling group (ASG) should be controlled by the small-KAC (Kubernetes autoscaler controller) which gets cluster info from Heapster/apiserver.

Though I don't know who is leading up the small-KAC implementation on the GKE side.

**Comment by a-robinson** [comment] 2016-03-31 03:36
@kubernetes/autoscaling

**Comment by piosz** [comment] 2016-03-31 16:44
Closing as duplicate of #11935

**Closed by piosz** 2016-03-31 16:44 UTC
Labels: area/autoscaling, area/platform/aws, kind/feature, priority/P1, team/control-plane, team/sig-aws
