### ISSUE TITLE
container "runtime" exceeding expected RSS memory

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#28124] opened 2016-06-27 18:56 UTC
We seemed to have curbed the kubelet memory issues in #27456, but the runtime issues remain.

``` console
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:277
Jun 26 21:41:36.956: Memory usage exceeding limits:
 node jenkins-e2e-minion-group-lkou:
 container "runtime": expected RSS memory (MB) < 157286400; got 192192512
node jenkins-e2e-minion-group-vdvc:
 container "runtime": expected RSS memory (MB) < 157286400; got 169332736
node jenkins-e2e-minion-group-zlrc:
 container "runtime": expected RSS memory (MB) < 157286400; got 169558016
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/5807 has a lot of these.

This can likely be de-duped to an auto-filed issue when the soak tests are added to the munger.

**Comment by krousey** [comment] 2016-06-28 15:42
#28124

**Comment by yujuhong** [comment] 2016-06-28 15:59
I created a cluster and ran a scrip to repeatedly create/delete pods overnight, but couldn't reproduce this issue.

Uploaded PR #28131 to enable the debug mode in docker, so that one can run pprof to get more useful information from the soak cluster.

**Comment by krousey** [comment] 2016-06-30 16:13
I redeployed the GCE soak tests yesterday to pick up #28131 to help you debug faster. I verified that docker is running with this flag on the nodes. So as soon as it re-occurs on https://k8s-testgrid.appspot.com/google-soak#soak-continuous-e2e-gce&width=20&sort-by-failures= , you should be able to debug it.

Just out of curiosity, what sort of debugging does that flag enable?

**Comment by yujuhong** [comment] 2016-06-30 20:22
> Just out of curiosity, what sort of debugging does that flag enable?

I know it at least enables the /debug/pprof endpoint.

**Comment by yujuhong** [comment] 2016-07-02 00:33
The new cluster started failing again:

Some information I gathered:

The goroutines:
https://gist.github.com/yujuhong/38109e05df58146a20e8a70a1d6617fa

```console
yjhong@jenkins-e2e-minion-group-7khh:~$ sudo docker ps
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
8ecbadbb6f46        gcr.io/google_containers/elasticsearch:1.9                             "/run.sh"                46 hours ago        Up 46 hours                             k8s_elasticsearch-logging.524a0850_elasticsearch-logging-v1-gszgk_kube-system_b02751b7-3e68-11e6-a6ce-42010af00002_aef430b4
8e234b0c219c        gcr.io/google_containers/fluentd-elasticsearch:1.17                    "td-agent"               46 hours ago        Up 46 hours                             k8s_fluentd-elasticsearch.84b0f49b_fluentd-elasticsearch-jenkins-e2e-minion-group-7khh_kube-system_de9fbcfa2281dda99252c713a8e68fc2_bfad053b
fdeb7d70d33e        gcr.io/google_containers/pause-amd64:3.0                               "/pause"                 46 hours ago        Up 46 hours                             k8s_POD.d8dbe16c_elasticsearch-logging-v1-gszgk_kube-system_b02751b7-3e68-11e6-a6ce-42010af00002_510bc7db
6d624168d5cf        gcr.io/google_containers/node-problem-detector:v0.1                    "/node-problem-detect"   46 hours ago        Up 46 hours                             k8s_node-problem-detector.a543764a_node-problem-detector-v0.1-23nfh_kube-system_ae775d3b-3e68-11e6-a6ce-42010af00002_4d9111c8
7c448374a498        gcr.io/google_containers/kube-proxy:d431921f828b7f8553e4d8450ca71495   "/bin/sh -c 'kube-pro"   46 hours ago        Up 46 hours                             k8s_kube-proxy.6fbe1db6_kube-proxy-jenkins-e2e-minion-group-7khh_kube-system_96efa5796e7a366a7495b065637b8895_b052b0a8
c02c318ab9ee        gcr.io/google_containers/pause-amd64:3.0                               "/pause"                 46 hours ago        Up 46 hours                             k8s_POD.d8dbe16c_node-problem-detector-v0.1-23nfh_kube-system_ae775d3b-3e68-11e6-a6ce-42010af00002_0e60cb8e
fe1695c6db70        gcr.io/google_containers/pause-amd64:3.0                               "/pause"                 46 hours ago        Up 46 hours                             k8s_POD.d8dbe16c_fluentd-elasticsearch-jenkins-e2e-minion-group-7khh_kube-system_de9fbcfa2281dda99252c713a8e68fc2_8884291d
c53f79936721        gcr.io/google_containers/pause-amd64:3.0                               "/pause"                 46 hours ago        Up 46 hours                             k8s_POD.d8dbe16c_kube-proxy-jenkins-e2e-minion-group-7khh_kube-system_96efa5796e7a366a7495b065637b8895_5f0fcbd3
```

```console
$ go tool pprof -inuse_space docker http://localhost:1234/api/v1/proxy/nodes/jenkins-e2e-minion-group-7khh:9191/debug/pprof/heap
Fetching profile from http://localhost:1234/api/v1/proxy/nodes/jenkins-e2e-minion-group-7khh:9191/debug/pprof/heap
Saved profile in /usr/local/google/home/yjhong/pprof/pprof.docker.localhost:1234.inuse_objects.inuse_space.003.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top
30437.39kB of 34022.22kB total (89.46%)
Dropped 1214 nodes (cum <= 170.11kB)
Showing top 10 nodes out of 100 (cum >= 512.81kB)
      flat  flat%   sum%        cum   cum%
 8192.50kB 24.08% 24.08%  8192.50kB 24.08%  github.com/tchap/go-patricia/patricia.NewTrie
 7979.25kB 23.45% 47.53%  7979.25kB 23.45%  reflect.callMethod
 5255.34kB 15.45% 62.98%  5255.34kB 15.45%  regexp.(*bitState).reset
 2112.67kB  6.21% 69.19%  2112.67kB  6.21%  io.copyBuffer
 2048.75kB  6.02% 75.21%  2048.75kB  6.02%  runtime.malg
 2048.12kB  6.02% 81.23% 11264.70kB 33.11%  github.com/docker/docker/pkg/truncindex.(*TruncIndex).addID
 1024.08kB  3.01% 84.24%  9216.58kB 27.09%  github.com/tchap/go-patricia/patricia.(*Trie).put
  747.86kB  2.20% 86.44%   747.86kB  2.20%  github.com/docker/docker/libcontainerd.(*queue).append
  516.01kB  1.52% 87.96%   516.01kB  1.52%  golang.org/x/net/trace.init
  512.81kB  1.51% 89.46%   512.81kB  1.51%  encoding/pem.Decode
```

Will check later(?) to see if the memory uasge keeps increasing

**Comment by yujuhong** [comment] 2016-07-11 17:26
The heap profile shows that  `github.com/tchap/go-patricia/patricia.NewTrie` is slowing accumulating more memory. This can be reproduced by repeatedly creating and deleting containers for thousands of times using docker v1.11 (without kubernetes involved at all). A potentially related issue is found on https://github.com/docker/docker/issues/24420. I didn't try it on docker v1.12 and am not sure if it suffers from the same symptom.

I was able to also reproduce this through unit tests in the `go-patricia` package. On such unit test is https://github.com/tchap/go-patricia/blob/2afe4fa257af06a5379ca7412d6b383876187cb6/patricia/patricia_dense_test.go#L168. I modified the test to use UUIDs as keys and change the order to always insert a key and then delete right away. After running the test for 10 million iterations, the test always fails with an increase of memory usage on the heap. I filed an issue to see if the unit test failure is related, or just a red herring: https://github.com/tchap/go-patricia/issues/24

**Comment by dims** [comment] 2016-07-12 12:02
@yujuhong Is this p0 flake a symptom of this issue? https://github.com/kubernetes/kubernetes/issues/28384

**Comment by yujuhong** [comment] 2016-07-12 16:41
In #28384, both kubelet and runtime exceed the memory limit. This issue is for the "runtime" memory issue, but not for kubelet. The kubelet memory issue seems to be relatively new. I'll look into that as well.

**Comment by yujuhong** [comment] 2016-07-27 23:00
Update: There is a fix posted in https://github.com/tchap/go-patricia/issues/24. W can't patch docker 1.11 anyway, so the soak test will continue failing. 

@dchen1107, this is the docker memory leak I mentioned yesterday.

**Comment by bprashanth** [comment] 2016-08-11 18:40
I though this was a slow leak that only shows up in soak but apparently integration tests are hitting it too: https://github.com/kubernetes/kubernetes/pull/30277, or is that something else, or just a confusing error message?

**Comment by bprashanth** [comment] 2016-08-11 18:41
fwiw the logs from this failure https://github.com/kubernetes/kubernetes/pull/30277#issuecomment-239250641 are https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30277/kubernetes-pull-test-unit-integration/38871/, https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/30277/kubernetes-pull-test-unit-integration/38871. I haven't trawled through them yet.

**Comment by yujuhong** [comment] 2016-08-11 18:47
> I though this was a slow leak that only shows up in soak but apparently integration tests are hitting it too: #30277, or is that something else, or just a confusing error message?

Looks to me like the go runtime was out of memory when building/running testmain
`go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed`
Not sure how this is related to docker

**Comment by krousey** [comment] 2016-09-01 17:49
@yujuhong This is still an issue, and @pwittrock would like to get this passing in the kubernetes-soak-continuous-e2e-gce-1.4 test suite for the release. I know we talked about patching docker at least for the GCE images. Is that still an option? If not, could you sync up with @pwittrock about how to proceed? Thanks.

**Comment by dchen1107** [comment] 2016-09-01 18:28
Patching docker for today's GCE images is not an option. I am considering patching docker in GCI image though. cc/ @aronchick @kubernetes/goog-image

**Comment by yujuhong** [comment] 2016-09-01 19:27
> Patching docker for today's GCE images is not an option. I am considering patching docker in GCI image though. cc/ @aronchick @kubernetes/goog-image

It's already patched in GCI.

**Comment by dchen1107** [comment] 2016-09-01 20:34
Here are the plan I wrote in bot auto-filed flake issue: #28384, #28220:

```
* Increase resource limit for docker runtime at cluster e2e test now.
* Create a separate node soaking test to monitoring both docker and kubelet resource usage with a very high limit. Let Node performance monitoring dashboard collects the stats and show it on the dashboard. cc/ @coufon 
* Once above is finished, remove this test completely from cluster e2e.
```

https://github.com/kubernetes/kubernetes/pull/31899 was merged to stop the bleeding. I will leave this open for rest work.

**Comment by foxish** [comment] 2016-09-07 18:30
These tests are now also failing in case of kubernetes-e2e-gce-gci-serial-release-1.4. 

```
[k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 35 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:278 Sep 7 06:31:00.067: Memory usage exceeding limits: node jenkins-e2e-minion-group-sjbe: container "runtime": expected RSS memory (MB) < 209715200; got 238321664 node jenkins-e2e-minion-group-db62: container "runtime": expected RSS memory (MB) < 209715200; got 258486272 node jenkins-e2e-minion-group-e74g: container "runtime": expected RSS memory (MB) < 209715200; got 248848384 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:153


[k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 100 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:278 Sep 7 07:38:20.013: Memory usage exceeding limits: node jenkins-e2e-minion-group-brl0: container "runtime": expected RSS memory (MB) < 314572800; got 531009536 node jenkins-e2e-minion-group-e74g: container "runtime": expected RSS memory (MB) < 314572800; got 552067072 node jenkins-e2e-minion-group-sjbe: container "runtime": expected RSS memory (MB) < 314572800; got 539709440 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:153
```

**Comment by dchen1107** [comment] 2016-09-07 19:51
@foxish thanks for checking the last failure. Yes, this is known issue, and shouldn't block 1.4 release since GCI default on node is decoupled from the releases.

**Comment by foxish** [comment] 2016-09-07 20:27
@dchen1107 If it's not a release blocker, do you suggest that we disable the test in the 1.4 branch?

cc @pwittrock

**Comment by dchen1107** [comment] 2016-09-08 21:17
Filed https://github.com/kubernetes/kubernetes/issues/32320 to disable the tests for 1.4.

**Comment by derekwaynecarr** [comment] 2017-03-06 15:23
To help clean up the list of flakes for 1.6, I am closing this issue as it does not appear to flake anymore with the increased limits.

**Closed by derekwaynecarr** 2017-03-06 15:23 UTC
Labels: area/docker, area/os/gci, kind/flake, priority/backlog, sig/node
