### ISSUE TITLE
kube-dns and dashboard is crashing with CrashLoopBackOff

### ISSUE THREAD

**Issue by arindam00** [kubernetes/kubernetes#56698] opened 2017-12-01 14:17 UTC
Is this a BUG REPORT or FEATURE REQUEST?:

Uncomment only one, leave it on its own line:

/kind bug
/kind feature
/sig priority
What happened:
I have deployed kubernetes cluster usiing acs-engine in azure . After deployment my kube-dns pods were working perfectly but after two days machine got rebooted Kube-DNS is not working and it went into crashloopbackoff mode.
What you expected to happen:
Kube-DNS pods should be running properly
How to reproduce it (as minimally and precisely as possible):
root@rbcicchcovamw00:/var/log/pods# kubectl logs kube-dns-v20-3003781527-lh28l -n=kube-system kubedns
I1201 12:07:00.729796 1 dns.go:48] version: 1.14.4-2-g5584e04
I1201 12:07:00.732575 1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I1201 12:07:00.732635 1 server.go:113] FLAG: --alsologtostderr="false"
I1201 12:07:00.732659 1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I1201 12:07:00.732669 1 server.go:113] FLAG: --config-map=""
I1201 12:07:00.732684 1 server.go:113] FLAG: --config-map-namespace="kube-system"
I1201 12:07:00.732691 1 server.go:113] FLAG: --config-period="10s"
I1201 12:07:00.732709 1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I1201 12:07:00.732716 1 server.go:113] FLAG: --dns-port="10053"
I1201 12:07:00.732734 1 server.go:113] FLAG: --domain="cluster.local."
I1201 12:07:00.732743 1 server.go:113] FLAG: --federations=""
I1201 12:07:00.732761 1 server.go:113] FLAG: --healthz-port="8081"
I1201 12:07:00.732768 1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I1201 12:07:00.732783 1 server.go:113] FLAG: --kube-master-url=""
I1201 12:07:00.732791 1 server.go:113] FLAG: --kubecfg-file=""
I1201 12:07:00.732807 1 server.go:113] FLAG: --log-backtrace-at=":0"
I1201 12:07:00.732816 1 server.go:113] FLAG: --log-dir=""
I1201 12:07:00.732833 1 server.go:113] FLAG: --log-flush-frequency="5s"
I1201 12:07:00.732840 1 server.go:113] FLAG: --logtostderr="true"
I1201 12:07:00.732855 1 server.go:113] FLAG: --nameservers=""
I1201 12:07:00.732861 1 server.go:113] FLAG: --stderrthreshold="2"
I1201 12:07:00.732877 1 server.go:113] FLAG: --v="2"
I1201 12:07:00.732883 1 server.go:113] FLAG: --version="false"
I1201 12:07:00.732892 1 server.go:113] FLAG: --vmodule=""
I1201 12:07:00.733030 1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I1201 12:07:00.735464 1 server.go:200] Skydns metrics not enabled
I1201 12:07:00.735483 1 dns.go:147] Starting endpointsController
I1201 12:07:00.735492 1 dns.go:150] Starting serviceController
I1201 12:07:00.735619 1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1201 12:07:00.735632 1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I1201 12:07:01.235705 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:01.735803 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:02.235786 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:02.736013 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:03.235806 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:03.735770 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:04.235820 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:04.735811 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:05.235764 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:05.735742 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:06.235768 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:06.735761 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:07.235767 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:07.735763 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:08.235759 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:08.735738 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:09.235769 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:09.735795 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:10.235813 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:10.735763 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E1201 12:07:10.737253 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E1201 12:07:10.737362 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
I1201 12:07:11.235801 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:11.735789 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:12.235784 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:12.735878 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:13.235786 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:13.735757 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:14.235853 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:14.735781 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:15.235746 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:15.735772 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:16.235754 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:16.735879 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:17.235825 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:17.735754 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:18.235850 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:18.735733 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:19.235756 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:19.735757 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:20.235864 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:20.735758 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:21.235755 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 12:07:21.735807 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E1201 12:07:21.739455 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E1201 12:07:21.739547 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
I1201 12:07:22.236120 1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version): 1.7.9
Cloud provider or hardware configuration: Azure
OS (e.g. from /etc/os-release): Ubuntu 16 TSL
Kernel (e.g. uname -a):
Install tools:
Others:

**Comment by dims** [comment] 2017-12-01 17:17
/close

duplicate of https://github.com/kubernetes/kubernetes/issues/56698 ?

**Closed by dims** 2017-12-01 17:17 UTC
Labels: kind/bug, kind/feature, needs-sig

**Comment by maxnitze** [comment] 2018-03-05 11:58
Think there was a type in the last comment. This seems to be a duplicate of #56693 . The other mentioned one is this here. A little confusing :)
