### ISSUE TITLE
"externalTrafficPolicy":"Local" work not fine with Cloud LoadBalancer

### ISSUE THREAD

**Issue by andelwu** [kubernetes/kubernetes#51255] opened 2017-08-24 08:33 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
1. I have a service patch with {"spec":{"externalTrafficPolicy":"Local"}}, But pkg/cloudprovider /cloud.go Interface LoadBalancer call EnsureLoadBalancer/UpdateLoadBalancer with all node in the Cluster.
2. With service having '{"spec":{"externalTrafficPolicy":"Local"}}', Whenever pod reschedule to another node, UpdateLoadBalancer never been called.

**What you expected to happen**:
1. EnsureLoadBalancer/UpdateLoadBalancer need to be called with desired Local traffic node.
2. UpdateLoadBalancer should be called when Local Traffic Policy and pod reschedule to another node.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl patch svc service_name -p '{"spec":{"externalTrafficPolicy":"Local"}}'

**Anything else we need to know?**:
no

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**: private
- OS (e.g. from /etc/os-release): centos 7.2
- Kernel (e.g. `uname -a`): -
- Install tools: binary
- Others:

/sig area/cloudprovider

**Comment by MrHohn** [comment] 2017-08-29 01:07
> 1. EnsureLoadBalancer/UpdateLoadBalancer need to be called with desired Local traffic node.
> 2. UpdateLoadBalancer should be called when Local Traffic Policy and pod reschedule to another node.

Currently the implementation of `externalTrafficPolicy=Local` lays most of the logics on kube-proxy instead of service controller, and service controller has no information about which backend pod is on which node because it doesn't watch pods at all.

For making service controller watch pods, you may want to read the discussions on https://github.com/kubernetes/kubernetes/issues/44203.

**Comment by jhorwit2** [comment] 2017-11-25 21:35
As @MrHohn mentioned, this is expected. The load balancer will contain all the available nodes regardless of what `externalTrafficPolicy` is set to so there is no need to call `UpdateLoadBalancer`. The way that the load balancer knows where to send traffic when `externalTrafficPolicy` is `Local` is via the health check kube-proxy sets up on the `healthCheckNodePort`. If no pods are running on a given node then the health check will respond with a 500. This means that as pods are moved around the load balancer is updated quickly versus having to wait on the node sync loop in the service controller which only runs every 100s. This is explained in the documentation [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer). 

I'm going to close this issue since it's not a bug. If you'd like to continue the discussion I'd recommend adding to the discussion on #44203.
 
/area cloudprovider

/assign
/close

**Closed by jhorwit2** 2017-11-25 21:35 UTC
Labels: area/cloudprovider, kind/bug, sig/network
