### ISSUE TITLE
Data race in pkg/kubelet/nodeshutdown test

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#108707] opened 2022-03-15 15:12 UTC
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

k8s.io/kubernetes/pkg/kubelet/nodeshutdown

### Since when has it been flaking?

Not sure, just saw it today

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108705/pull-kubernetes-unit/1503733519241711616

```
WARNING: DATA RACE
Write at 0x00c0002225a0 by goroutine 100:
  bytes.(*Buffer).tryGrowByReslice()
      /usr/local/go/src/bytes/buffer.go:108 +0xb3
  bytes.(*Buffer).Write()
      /usr/local/go/src/bytes/buffer.go:170 +0x18
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*redirectBuffer).Write()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:948 +0x68
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1074 +0x61d
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x2d4
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printS()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:814 +0x269
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).infoS()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:798 +0x191
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.Verbose.InfoS()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482 +0x83d
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).processShutdownEvent.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:328 +0x6ca
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).processShutdownEvent·dwrap·2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:330 +0x9d

Previous read at 0x00c0002225a0 by goroutine 29:
  bytes.(*Buffer).String()
      /usr/local/go/src/bytes/buffer.go:65 +0x738
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.Test_managerImpl_processShutdownEvent.func4()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:707 +0x71b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Goroutine 100 (running) created at:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).processShutdownEvent()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:303 +0x658
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.Test_managerImpl_processShutdownEvent.func4()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:702 +0x5b7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Goroutine 29 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.Test_managerImpl_processShutdownEvent()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:680 +0x6dc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
```

### Relevant SIG(s)

/sig node

**Comment by alculquicondor** [comment] 2022-03-15 15:12
@smarterclayton @bobbypage

**Comment by jlsong01** [comment] 2022-03-15 16:39
/assign
I would like to take a try

**Comment by aojea** [comment] 2022-03-15 21:40
The tests that use klog are racy 

https://github.com/kubernetes/kubernetes/pull/108553

**Comment by jlsong01** [comment] 2022-03-16 01:20
/unassign
as another two fix prs are already in progress

**Comment by endocrimes** [comment] 2022-03-16 08:48
Duplicate of https://github.com/kubernetes/kubernetes/issues/108040

/close

**Closed** 2022-03-16 08:49 UTC
Labels: sig/node, kind/flake, needs-triage
