### ISSUE TITLE
Configmap mounted with subPath doesn't get reloaded automatically

### ISSUE THREAD

**Issue by kycfeel** [kubernetes/kubernetes#92296] opened 2020-06-19 10:22 UTC
**What happened**:
The configmap mounted with `subPath` is not getting reloaded automatically. 

**What you expected to happen**:
The configmap change gets updated to a mounted pod automatically.

**How to reproduce it (as minimally and precisely as possible)**:
Mount a file stored as configmap to a pod with `subPath`, make a change at the configmap, and watch the change gets updated to the container.

```
 volumeMounts:
          - name: my-config
            mountPath: /etc/myapp/myconfig.conf
            subPath: myconfig.conf
```

```
volumes:
          - name: my-config
             configMap:
                 name: my-config
```
**Anything else we need to know?**:
The automatic configmap reload works well If I don't use `subPath`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2 
- Cloud provider or hardware configuration: DigitalOcean DOKS
- OS (e.g: `cat /etc/os-release`): Debian do-kube-1.16.2-do.1
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-06-19 13:21
/remove-sig api-machinery
/sig storage
/cc @msau42 

This is a duplicate of https://github.com/kubernetes/kubernetes/issues/50345#issuecomment-368630265, which was documented and closed as a known limitation. 

/close

**Closed** 2020-06-19 13:21 UTC
Labels: kind/bug, sig/storage

**Comment by sapeish** [comment] 2020-06-25 22:02
It would help if the `subPath` limitation was also documented in the ConfigMaps section  where no limitation is mentioned and took me hours to get to this thread and understand what was the underlying issue: https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

**Comment by TBBle** [comment] 2020-07-03 08:34
It is documented in the very-similar block of text at https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically. They probably need to be merged or aligned, since they're mostly documenting the exact same concept in two different ways, with different levels of detail.
