### ISSUE TITLE
Kube-proxy should exempt local traffic from going through conntrack

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#109672] opened 2022-04-26 12:56 UTC
### What would you like to be added?

An accept rule should be installed before the conntrack rule exempt local traffic such as requests to localhost:10248/healthz

```
...
-N KUBE-SERVICES
-A INPUT -m comment --comment "kubernetes health check service ports" -j KUBE-NODEPORTS
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -j KUBE-FIREWALL
...
```

### Why is this needed?

Tracking traffic via loop interface seems unnecessary and has extra overhead. Especially when the conntrack table is full, the traffic would be dropped and it causes more problems.

**Comment by linxiulei** [comment] 2022-04-26 15:29
To clarify, the local traffic (localhost to localhost) would firstly go through OUTPUT chain and then INPUT chain. Is it right?

It doesn't matter if it only goes to OUTPUT chain because OUTPUT chain also uses conntrack.

```
-A OUTPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
```

The issue is when the conntrack table is full the localhost health check against kubelet is failed. However, this doesn't really reflect the true problem.

**Comment by aojea** [comment] 2022-04-26 18:23
> The issue is when the conntrack table is full the localhost health check against kubelet is failed.

You should report first the bug, I don't think this is going to solve any problems if you have the conntrack table full, is just one connection

**Comment by linxiulei** [comment] 2022-04-26 18:35
IMHO, this is expected as conntrack table can't be infinite. The applications can exhaust it no matter how big it is. The point is that ideally conntrack table being full should not impact kubelet (and its health check).

**Comment by aojea** [comment] 2022-04-27 07:41
I understand your reasoning, but if you have your conntrack table full, the kubelet probe is going to be the minor of your problems 
We should determine the root cause of the exhaustion of the conntrack table and see if its origin is some architectural problem, but we can not start patching the edge cases or this will not scale ... are we going to add rules for apiserver, controller-manager, ... and the rest of the components?

**Comment by linxiulei** [comment] 2022-04-27 09:27
I agree. My understanding on this problem is:

* Conntrack table exhaustion is inevitable from the workload. K8S should consider the worse scenario if possible to avoid impacts from the workload. Ideally, the communication between K8S components should be fine when conntrack table is full.
* since the conntrack is setup by kube-proxy, the architectural problem could be inside the kube-proxy. For example, we could have an exempt rule before entering rules using conntrack. (kube-proxy already does something similar. See the chain KUBE-NODEPORTS). This exempt rule can be used for all basic kubelet traffic.

**Comment by aojea** [comment] 2022-04-27 14:10
hmm, kube-proxy rules are not creating the conntrack entries, those rules are using the entries ... the kernel enables the conntrack hooks and tracks the protocols, all the NAT kernel modules use those entries to be able to perform the different operations ...

If you want some traffic to not be "tracked" by the kernel you have to use something like
```
iptables -t raw -A PREROUTING <your traffic filter here> -j NOTRACK
```

but if you hit conntrack table limits I think that your system is wrong dimensioned, same as if you have memory, cpu or disk exhausting, you should be able to know the number of conntrack entries you want to handle in advance and configure the limit correctly in advance

**Comment by thockin** [comment] 2022-04-28 20:32
I'm in favor of adding NOTRACK rules if and when we can.  The problem is that it's not always clear when we can do that.

E.g. iptables mod kube-proxy supports nodeports on localhost - we need to track those.  So the rules have to at least check `-d 127.0.0.0/8` AND compare `-p` and `--dport` against all known nodeports.

I seem to recall trying to do this a while back and finding more corner cases.  TCP connections do clear after the connection closes, maybe there's more we can do there.

Can you run `conntrack -L` just to be sure your problems are all localhost?

**Comment by linxiulei** [comment] 2022-04-29 10:42
@aojea ah, I missed that the conntrack is enabled as long as iptables/netfilter is used. Thanks! 

By exempting, I meant to set up the NOTRACK rules for critical traffic so the components relying on those traffic can be more robust for extreme circumstance. However, it's debatable where we should put those NOTRACK rules.

@thockin I don't have the environment now but I'd bet the most usage comes from pods instead of the localhost. So the small traffic through localhost is a victim of conntrack table being full. But they are very important to critical K8S components in the node.

**Comment by dcbw** [comment] 2022-05-26 15:27
@linxiulei you should be able to adjust the conntrack table size with `net.netfilter.nf_conntrack_max`. Is that not an option on your systems?

**Comment by linxiulei** [comment] 2022-05-26 19:47
@dcbw Not really as nf_conntrack_max may be used up no matter how high you specify. Also setting a high value of it will use up memory that is not charged by any pods, so it will impact the whole system.

@thockin I have created NOTRACK iptables rules in my environment and it worked well for local traffic (eg. health check to kubelet). But it is a standalone configuration script that insert the rules. It'd be neat if kube-proxy does that by default.

**Comment by thockin** [comment] 2022-06-09 16:06
Can you provide details on exactly what NOTRACK rules you are using?

**Comment by linxiulei** [comment] 2022-06-10 15:56
Yeah, something like:

```
    iptables -w -t raw -A PREROUTING -s 127.0.0.1 -p tcp --sport 10248 -j NOTRACK
    iptables -w -t raw -A OUTPUT -d 127.0.0.1 -p tcp --dport 10248 -j NOTRACK

    iptables -w -A INPUT -s 127.0.0.1 -p tcp --sport 10248 -j ACCEPT
    iptables -w -A OUTPUT -d 127.0.0.1 -p tcp --dport 10248 -j ACCEPT
```

The 10248 is the port that kubelet's healthz service listens to

**Comment by thockin** [comment] 2022-08-04 00:11
I'm going to triage accept this, because I agree, but it's not as easy as it sounds. :(

**Comment by aojea** [comment] 2023-03-19 13:33
Just for reference as Eric and I were finding new corner cases with the notrack approach, and something important to consider is that if there is some firewalling in place that depends on the connection state, if the connection is no tracked, the returning traffic will not match any ESTABLISHED state, and will be dropped

**Comment by thockin** [comment] 2024-10-24 19:15
Closing in favor of https://github.com/kubernetes/kubernetes/issues/127259 as the accumulator issue.

**Closed by thockin** 2024-10-24 19:15 UTC
Labels: sig/network, kind/feature, triage/accepted
