### ISSUE TITLE
Many CNI Plugins don't properly support DEL

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43488] opened 2017-03-22 01:07 UTC
Started as a tangent of #43014 

Many CNI plugins don't properly handle a `DEL` action on missing resources. The spec says, `Plugins should generally complete a DEL action without error even if some resources are missing`, however many improperly return an error.

I see the steps moving forward to be:
- [x] Modify CNI plugins bundled with Kubernetes to properly support del (flannel already done; bridge, ipvlan, macvlan, and ptp in containernetworking/cni#412)
- [x] Create release of containernetworking/cni
- [x] Build Kubernetes version of CNI using [Makefile](https://github.com/kubernetes/kubernetes/blob/master/build/cni/Makefile)
- [ ] Modify references to CNI version [throughout project](https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=07a8a28637e97b22eb8dfe710eeae1344f69d16e)

Does this make sense?

cc/ @caseydavenport @luxas @calebamiles @yujuhong @janwillies @yujuhong @dchen1107 @djosborne @jbeda @bowei @thockin @feiskyer @aaronlevy @sameo @GheRivero @tomdee @bboreham @cmluciano @dcbw @freehan

**Comment by tomdee** [comment] 2017-03-22 01:11
SGTM - I'm working on the https://github.com/containernetworking/cni/pull/412 right now and can do the CNI release too.

On the 3rd check box ` Build Kubernetes version of CNI using Makefile` - why is that still a thing? Doesn't the CNI project provide the required artifacts as part of its release?

**Comment by thockin** [comment] 2017-03-22 03:35
I just want to say thanks to everyone for jumping on this.

**Comment by bowei** [comment] 2017-03-22 05:15
https://docs.google.com/spreadsheets/d/1Nqa6y4J3kEE2wW_wNFSwuAuADAl74vdN6jYGmwXRBv8/edit#gid=0

**Comment by cmluciano** [comment] 2017-03-22 15:54
I can test out patches as needed. I currently only have test cases for Weave and Calico, but it should not be too difficult to add others.

**Comment by tomdee** [comment] 2017-03-22 16:07
@cmluciano It would be great to get flannel tested too. You probably need a master build of the flannel CNI plugin and possibly some flannel patches to be merged. Feel free to DM on slack if you need more info.

**Comment by luxas** [comment] 2017-03-22 16:11
@tomdee s390x builds are missing still. If that's added, we can switch to v0.5.1 in time for v1.7.
However, I really don't want to bump from v0.3.0-ish to v0.5.0 one day before release.

This is a v1.7 issue to ensure all CNI plugins (including the official) work as intended with Kubernetes and an issue to make sure we update to CNI v0.5.0 w/ spec v0.3.0 in time for v1.7.

I think https://github.com/kubernetes/kubernetes/pull/43474 will solve the short-term solutions.
Also it seems like Weave, Calico and maybe Canal has fixed this as-is. I think Flannel works with https://github.com/kubernetes/kubernetes/pull/43474

**Comment by tomdee** [comment] 2017-03-22 16:13
@luxas I'm a little confused!You mean s390x builds for flanneld?

**Comment by luxas** [comment] 2017-03-22 16:50
@tomdee CNI still needs s390x binaries to be consumable by k8s: https://github.com/containernetworking/cni/releases

Two other conclusions:
1) We should go with https://github.com/kubernetes/kubernetes/pull/43474 as the immediate solution
2) We should upgrade to CNI v0.5.1 (when released( officially for Kubernetes in time for v1.7 and enforce the latest spec (v0.3.0) for all network plugins

**Comment by yujuhong** [comment] 2017-03-22 17:04
> We should go with #43474 as the immediate solution

We should get the PR in (after testing), but this is not a really solution as it only avoids hitting this problem at cluster setup.

**Comment by tomdee** [comment] 2017-03-22 17:37
OK, @luxas that makes sense on the s390x binaries.

I've just released v0.5.1 of CNI, which updates the plugins with the new del behaviour. They should all still be back compatible with the older spec versions so I recommend that K8s takes this CNI release.

https://github.com/containernetworking/cni/releases/tag/v0.5.1

**Comment by cmluciano** [comment] 2017-03-22 17:57
I'm working on a patch for that bump now

**Comment by yujuhong** [comment] 2017-03-22 20:04
Be aware that #43474 has just been merged. If you sync to HEAD, you won't be able to reproduce this problem at cluster setup easily.

**Comment by ixdy** [comment] 2017-03-22 20:15
New `cni` packaged tarball (based on v0.5.1) has been pushed:
```
$ gsutil ls gs://kubernetes-release/network-plugins/*-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff*
gs://kubernetes-release/network-plugins/cni-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
gs://kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
gs://kubernetes-release/network-plugins/cni-arm-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
gs://kubernetes-release/network-plugins/cni-arm64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
gs://kubernetes-release/network-plugins/cni-ppc64le-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
gs://kubernetes-release/network-plugins/cni-s390x-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
```

**Comment by bowei** [comment] 2017-03-22 20:36
@ethernetdan -- can this be closed?

**Comment by cmluciano** [comment] 2017-03-22 21:02
I was trying to update the Godeps to include the new 0.5.1 release. Are the Godeps the wrong place for this?

**Comment by calebamiles** [comment] 2017-03-22 21:27
@bowei we can't close until all the consumers have been updated to point to the new tarballs

**Comment by bgrant0607** [comment] 2017-03-23 20:11
What is the ETA for resolving this?

**Comment by bgrant0607** [comment] 2017-03-23 20:22
Ok, I see that #43546 is at the top of the submit queue.

**Closed** 2017-03-23 21:13 UTC
Labels: sig/network
