### ISSUE TITLE
IPvS option for Kube Proxy routing

### ISSUE THREAD

**Issue by boynux** [kubernetes/kubernetes#38969] opened 2016-12-19 14:43 UTC
Feature request:

Adding IPvS (LVS) option for kube-proxy

Why: 
   IPTables and Userspace proxy both mask the client IP address by doing DNat. IPvS however doesn't do this a initiates the request to the virtual servers with the original client IP. In many cases like HTTP requests it might not be a blocker in more advanced networking and loadbalancing scenarios for example using UPD protocol it's very difficult to use the existing implementations.

IPvS does not require iptables nat feature and can provide more advanced loadbalancing behaviors like round robin and the least requests. There are 3 different ways to use IPvS: Nat, VPN and direct route. "Direct Route" model is the desired implementation as Nat is very similar to existing iptables implantation.

There is already an open pull request for this feature: #38817

**Comment by luxas** [comment] 2016-12-19 15:02
Can you please close this issue and open it in kubernetes/features instead?
Also I would appreciate if you or @mqliang made a formal proposal in kubernetes/community describing the high level goals, implementation details, pros/cons and including some diagrams, explanation in depth about the feature and a roadmap.

I think this is a great feature, and then it should be treated as one as well.
cc @idvoretskyi

**Comment by feiskyer** [comment] 2016-12-20 09:19
Related with https://groups.google.com/forum/#!topic/kubernetes-sig-network/59HG9SlypBc, still on discussion about this feature.

**Comment by boynux** [comment] 2016-12-20 19:36
@luxas Ok, I'll do that whenever I get chance, seems to be quite a bit of work ;)

**Comment by idvoretskyi** [comment] 2016-12-26 15:16
@boynux fixed a minor typo in the title.

Before submitting the new feature, please, start from the README https://github.com/kubernetes/features/blob/master/README.md.

**Comment by DanyC97** [comment] 2017-03-05 06:59
@boynux i guess you never managed to open an issue in n kubernetes/features ? _couldn't find one_

**Comment by boynux** [comment] 2017-03-05 09:15
@DanyC97 Unfortunately not. Been quiet busy.

https://github.com/kubernetes/features/issues/196 
I created that one but still need to create other related docs. @mqliang can you help here please.

**Comment by urzds** [comment] 2017-03-17 12:12
Is this a duplicate of issue #17470?

**Comment by boynux** [comment] 2017-03-18 08:29
Yes it is.

**Comment by brendandburns** [comment] 2017-03-18 21:21
Closing this, since it's a dup and the feature was created...

**Closed by brendandburns** 2017-03-18 21:21 UTC

**Comment by quinton-hoole** [comment] 2017-04-06 15:37
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063
Busy tying the various related issues and PR's together now.
