### ISSUE TITLE
Flake: Pod never became running in Kubernetes e2e suite.Generated release_1_2

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#21403] opened 2016-02-17 18:11 UTC
```
Kubernetes e2e suite.Generated release_1_2 clientset should create pods, delete pods, watch pods (from (junit_24.xml))

Failing for the past 1 build (Since Unstable#28905 )
Took 5 min 7 sec.
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:158
Expected error:
    <*errors.errorString | 0xc20850e0a0>: {
        s: "gave up waiting for pod 'podf9342a69-d526-11e5-a8f5-42010af00003' to be 'running' after 5m0s",
    }
    gave up waiting for pod 'podf9342a69-d526-11e5-a8f5-42010af00003' to be 'running' after 5m0s
not to have occurred
```
And e2e logs:
```
Feb 16 19:36:45.943: INFO: Waiting for pod podf9342a69-d526-11e5-a8f5-42010af00003 in namespace 'e2e-tests-clientset-kx6g0' status to be 'running'(found phase: "Pending", readiness: false) (4m58.478121768s elapsed)
Feb 16 19:36:47.943: INFO: Unexpected error occurred: gave up waiting for pod 'podf9342a69-d526-11e5-a8f5-42010af00003' to be 'running' after 5m0s
[AfterEach] Generated release_1_2 clientset
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:83
```

**Comment by dchen1107** [comment] 2016-02-17 18:32
Can we have more information on why Pod not running here? not resource to schedule? pulling image failed? couldn't start container? :-)

**Comment by pwittrock** [comment] 2016-02-17 19:42
Saw this on e2e-gke-slow [#765](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-slow/765/)

Here are the full logs: 
[e2e-gke-slow.txt](https://github.com/kubernetes/kubernetes/files/135039/e2e-gke-slow.txt)

**Comment by lavalamp** [comment] 2016-02-18 18:30
@caesarxuchao has cycles to investigate

**Comment by caesarxuchao** [comment] 2016-02-19 23:50
https://github.com/kubernetes/kubernetes/pull/20882#issuecomment-185004106

and its gcs:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20882/kubernetes-pull-build-test-e2e-gce/28905/?pli=1

**Comment by caesarxuchao** [comment] 2016-02-20 01:32
For the test failure reported by @mikedanese, it looks like it's kubelet too long time to pull the image, as that's the last event reported by kubelet:
```
Feb 16 19:36:47.953: INFO: event for podf9342a69-d526-11e5-a8f5-42010af00003: {kubelet e2e-gce-builder-2-0-minion-25b0} Pulling: pulling image "gcr.io/google_containers/nginx:1.7.9"
```

kubelet log doesn't show other error. This probably is a dupe of #21029.

**Comment by caesarxuchao** [comment] 2016-02-20 01:46
the log given by @pwittrock is different:
```
STEP: Collecting events from namespace "e2e-tests-pod-disks-pxr98".
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} Pulled: Container image "gcr.io/google_containers/busybox:1.24" already present on machine
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} Created: Created container with docker id 21fcfde0bb2c
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} Started: Started container with docker id 21fcfde0bb2c
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} Killing: Killing container with docker id 21fcfde0bb2c: Need to kill pod.
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} FailedMount: Unable to mount volumes for pod "pd-test-067b053c-d5a4-11e5-99f8-42010af01555_e2e-tests-pod-disks-pxr98(adb9d2e1-d5a5-11e5-9d4a-42010af00007)": Could not attach GCE PD "e2e-fec4f1be-d5a3-11e5-99f8-42010af01555". Timeout waiting for mount paths to be created.
Feb 17 10:54:58.401: INFO: event for pd-test-067b053c-d5a4-11e5-99f8-42010af01555: {kubelet gke-jkns-gke-e2e-slow-afbbba70-node-9353} FailedSync: Error syncing pod, skipping: Could not attach GCE PD "e2e-fec4f1be-d5a3-11e5-99f8-42010af01555". Timeout waiting for mount paths to be created.
```
might be a dup of #20757. @saad-ali could you take a look?

pwittrock's comment: https://github.com/kubernetes/kubernetes/issues/21403#issuecomment-185371214

**Comment by saad-ali** [comment] 2016-02-20 02:11
> @saad-ali could you take a look?

@pwittrock's test run https://github.com/kubernetes/kubernetes/issues/21403#issuecomment-185371214 ran in to https://github.com/kubernetes/kubernetes/issues/19953

Not sure what's going on with https://github.com/kubernetes/kubernetes/pull/20882#issuecomment-185004106

**Comment by caesarxuchao** [comment] 2016-02-21 00:07
I'm closing this issue because the two reported cases are duplication of other flakes.

**Closed by caesarxuchao** 2016-02-21 00:07 UTC
Labels: kind/flake, team/node

**Comment by caesarxuchao** [comment] 2016-02-21 00:08
Thank you @saad-ali for the confirmation.
