### ISSUE TITLE
e2e-gce flake 'Error waiting for all pods to be running and ready'

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21522] opened 2016-02-19 02:22 UTC
>
Running in parallel across 30 nodes

Feb 18 18:00:19.598: INFO: >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config

Feb 18 18:00:19.798: INFO: Waiting up to 10m0s for all pods (need at least 1) in namespace 'kube-system' to be running and ready
Feb 18 18:00:19.872: INFO: The status of Pod fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p is Pending, waiting for it to be either Running or Failed
Feb 18 18:00:19.873: INFO: 19 / 20 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Feb 18 18:00:19.873: INFO: expected 8 pod replicas in namespace 'kube-system', 8 are Running and Ready.
Feb 18 18:00:19.873: INFO: POD                                                 NODE                          PHASE    GRACE  CONDITIONS
Feb 18 18:00:19.873: INFO: fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p  e2e-gce-master-1-minion-wo4p  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-18 17:58:52 -0800 PST ContainersNotReady containers with unready status: [fluentd-elasticsearch]}]
Feb 18 18:00:19.873: INFO: 
Feb 18 18:00:21.902: INFO: The status of Pod fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p is Pending, waiting for it to be either Running or Failed
Feb 18 18:00:21.903: INFO: 19 / 20 pods in namespace 'kube-system' are running and ready (2 seconds elapsed)
Feb 18 18:00:21.906: INFO: expected 8 pod replicas in namespace 'kube-system', 8 are Running and Ready.
Feb 18 18:00:21.906: INFO: POD                                                 NODE                          PHASE    GRACE  CONDITIONS
Feb 18 18:00:21.906: INFO: fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p  e2e-gce-master-1-minion-wo4p  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-18 17:58:52 -0800 PST ContainersNotReady containers with unready status: [fluentd-elasticsearch]}]
Feb 18 18:00:21.906: INFO: 
Feb 18 18:00:23.898: INFO: The status of Pod fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p is Pending, waiting for it to be either Running or Failed
Feb 18 18:00:23.898: INFO: 19 / 20 pods in namespace 'kube-system' are running and ready (4 seconds elapsed)
Feb 18 18:00:23.898: INFO: expected 8 pod replicas in namespace 'kube-system', 8 are Running and Ready.
Feb 18 18:00:23.898: INFO: POD                                                 NODE                          PHASE    GRACE  CONDITIONS
Feb 18 18:00:23.898: INFO: fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p  e2e-gce-master-1-minion-wo4p  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-18 17:58:52 -0800 PST ContainersNotReady containers with unready status: [fluentd-elasticsearch]}]
Feb 18 18:00:23.898: INFO: 

full log:
[e2e-gce-flake.txt](https://github.com/kubernetes/kubernetes/files/137329/e2e-gce-flake.txt)

**Comment by lavalamp** [comment] 2016-02-19 18:36
There's an obvious shadowing bug preventing the actual error message from being shown; I'll send a fix for that.

**Comment by lavalamp** [comment] 2016-02-19 18:50
As for the actual problem here, I will assign to @dchen1107 on the theory that this is related to other issues where nodes seem to not come up.

**Comment by dchen1107** [comment] 2016-02-19 21:44
@lavalamp How do you think this might be related to node not come up? From the initial message, all I can see is that fluentd pod on a node ( fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p) is not ready.

**Comment by bprashanth** [comment] 2016-02-19 23:31
@pwittrock without links to the actual system logs and artifacts debugging is hard. I'm going to assume you meant this failure: https://github.com/kubernetes/kubernetes/pull/21514#issuecomment-186015695. 

This is the kubelet: https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/21514/kubernetes-pull-build-test-e2e-gce/29311/artifacts/104.197.13.197%3A22-kubelet.log?debugUI=CLOUD


AFAICT it never finished pulling the image:
The pod is fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p and I see the pulling event
```
I0219 01:58:53.104004    3461 server.go:587] Event(api.ObjectReference{Kind:"Pod", 
Namespace:"kube-system", Name:"fluentd-elasticsearch-e2e-gce-master-1-minion-wo4p", 
UID:"ca513b83a860f11327241aa95a352f58", APIVersion:"v1", ResourceVersion:"", 
FieldPath:"spec.containers{fluentd-elasticsearch}"}): type: 'Normal' reason: 'Pulling' 
pulling image  "gcr.io/google_containers/fluentd-elasticsearch:1.14"
```

But no corresponding "Successfully pulled" event like I see for the other pods, eg:
```
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"l7-lb-controller-u0quv", 
UID:"2df65584-d6ac-11e5-b7a9-42010af00002", APIVersion:"v1", ResourceVersion:"274", 
FieldPath:"spec.containers{default-http-backend}"}): type: 'Normal' reason: 'Pulled' 
Successfully pulled image "gcr.io/google_containers/defaultbackend:1.0"
```

So I'm going to guess this is a dupe of https://github.com/kubernetes/kubernetes/issues/21029

**Comment by dchen1107** [comment] 2016-02-19 23:42
Yes, you are right. I am closing this as dup of  #21029

**Closed by dchen1107** 2016-02-19 23:42 UTC
Labels: kind/flake, team/node
