### ISSUE TITLE
Unit test flake: k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd TestGet Panic

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#25278] opened 2016-05-06 19:16 UTC
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/24918/kubernetes-pull-test-unit-integration/24658/build-log.txt
```
=== RUN   TestGet
--- FAIL: TestGet (10.34s)
	utils.go:245: Unexpected error in waitUntilUp (timeout on waiting for etcd cluster)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7875d1]

goroutine 319 [running]:
panic(0x1cd8c00, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.tRunner.func1(0xc820324000)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1cd8c00, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x521
k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc820324000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:41 +0x211
k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd.newStorage(0xc820324000, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd/etcd_test.go:35 +0x3f
k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd.TestGet(0xc820324000)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd/etcd_test.go:106 +0x41
testing.tRunner(0xc820324000, 0x2b32d68)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd	21.724s
```

**Comment by jayunit100** [comment] 2016-05-06 19:39
ill try to repro...

**Comment by jayunit100** [comment] 2016-05-06 19:50
i cant reproduce this in isolation

**Comment by jayunit100** [comment] 2016-05-06 19:59
ah 
```
+tcp        0      0 127.0.0.1:41433         0.0.0.0:*               LISTEN      27862/etcd.test     
+tcp        0      0 127.0.0.1:42383         0.0.0.0:*               LISTEN      27862/etcd.test     
```
looks like there are some ports used by this.  even though they're random, maybe thats thte source of the flake?

**Comment by jayunit100** [comment] 2016-05-06 20:17
@Random-Liu i think this is an infrastructure flake.  ive run it several times, and even run it in parallel (run the same test on the same machine multiple times in two terminals) and wasn't able to reproduce it.....  What do you think?

**Comment by fejta** [comment] 2016-05-23 22:29
Assigning to @smarterclayton per https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/OWNERS

**Comment by timothysc** [comment] 2016-05-26 19:42
So I set a script and looped this ~100 times without a single flake.  

In general, I fail to see how
```k8s.io/kubernetes/pkg/registry/persistentvolumeclaim/etcd.newStorage(0xc820324000, 0x0, 0x0, 0x0)``` can even occur because we pass in constants, so how exactly do we get ```0x0```.  The only thing I can think of is the machine that is running tests was resource strapped, which could possibly cause other flakes as well.

Given that we open up an etcd-instance per UT.  How much overlap is allowed on the testing infra? 
/cc @lavalamp 

closing this, please re-open if this re-occurs.

**Closed by timothysc** 2016-05-26 19:42 UTC
Labels: area/test, kind/flake, team/cluster

**Comment by jayunit100** [comment] 2016-05-26 19:59
Definetely saw same thing even running in parallel because ports are random , it's robust as a test so long as infra working
