### ISSUE TITLE
e2e flake: kubectl exec -i nginx bash timed out after 20m

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#23645] opened 2016-03-30 21:18 UTC
An example failure:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/23427/kubernetes-pull-build-test-e2e-gce/33968/build-log.txt

**Comment by fejta** [comment] 2016-03-30 21:43
Where did the infrastructure fail? It isn't obvious because there is only a link to a GCS file.

**Comment by wojtek-t** [comment] 2016-03-30 21:44
Basically - this is timeout of the test - it's not any individual test failure.

**Comment by fejta** [comment] 2016-03-30 21:53
Hmm... it looks like the problem is that it spent 20 minutes (13:53 to 14:14) running `kubectl exec -i nginx bash`:

```sh
Mar 30 13:53:22.839: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nginx]
[It] should support exec
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:227
STEP: executing a command in the container
STEP: executing a command in the container with pseudo-interactive stdin
Mar 30 13:53:23.965: INFO: Running '/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.245.82 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config exec --namespace=e2e-tests-kubectl-x9n97 -i nginx bash'

---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
Mar 30 14:14:14.038: INFO: Waiting up to 1m0s for all nodes to be ready
```

**Comment by ncdc** [comment] 2016-04-01 15:52
Dupe of #23321

**Closed by ncdc** 2016-04-01 15:52 UTC
Labels: kind/flake, priority/P1, team/ux
