### ISSUE TITLE
kube-proxy with endpoint config controller does not propely handle the last endpoint leaving

### ISSUE THREAD

**Issue by sfudeus** [kubernetes/kubernetes#110301] opened 2022-05-31 08:46 UTC
### What happened?

When the last endpoint of a service is removed or goes unhealthy, kube-proxy (in iptables mode) does not clean it properly from iptables. The following output shows the iptables state with an nginx deployment with 1 pod, then the output after the removal, despite empty endpoints/endpointslices lists. 

This happens only with the endpoints config controller, so with FeatureGate EndpointSliceProxying set to false.
The endpoint slice config controller works fine. 

I am aware that this is only affecting legacy code, so I am fine with closing this as WONTFIX. This is mostly for the record and for others observing similarly. 

```
> $ (kind-ise-9887) k exec -it -n kube-system kube-proxy-mrgkm -- iptables-save | grep nginx                                                                                                                                                  -A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SEP-2HN5UWK22YAF6QRS -s 100.64.0.6/32 -m comment --comment "default/nginx" -j KUBE-MARK-MASQ
-A KUBE-SEP-2HN5UWK22YAF6QRS -p tcp -m comment --comment "default/nginx" -m tcp -j DNAT --to-destination 100.64.0.6:80
-A KUBE-SERVICES ! -s 100.64.0.0/16 -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SVC-2CMXP7HKUVJN7L6M -m comment --comment "default/nginx" -j KUBE-SEP-2HN5UWK22YAF6QRS

> $ (kind-ise-9887) k scale deployment nginx --replicas 0                                                                                                                                                                                     deployment.apps/nginx scaled

> $ (kind-ise-9887) k get ep,endpointslices                                                                                                                                                                                                   NAME                   ENDPOINTS          AGE
endpoints/kubernetes   100.65.0.66:6443   7m35s
endpoints/nginx        <none>             5m47s

NAME                                         ADDRESSTYPE   PORTS     ENDPOINTS     AGE
endpointslice.discovery.k8s.io/kubernetes    IPv4          6443      100.65.0.66   7m35s
endpointslice.discovery.k8s.io/nginx-gvjss   IPv4          <unset>   <unset>       5m47s

> $ (kind-ise-9887) k exec -it -n kube-system kube-proxy-mrgkm -- iptables-save | grep nginx                                                                                                                                                  -A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SEP-2HN5UWK22YAF6QRS -s 100.64.0.6/32 -m comment --comment "default/nginx" -j KUBE-MARK-MASQ
-A KUBE-SEP-2HN5UWK22YAF6QRS -p tcp -m comment --comment "default/nginx" -m tcp -j DNAT --to-destination 100.64.0.6:80
-A KUBE-SERVICES ! -s 100.64.0.0/16 -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SVC-2CMXP7HKUVJN7L6M -m comment --comment "default/nginx" -j KUBE-SEP-2HN5UWK22YAF6QRS
```

You see, the KUBE-SVC and KUBE-SEP chains for nginx still exist with DNAT to a non-existing pod. 

### What did you expect to happen?

The KUBE-SEP chains for the service should be removed and the reject should be added, as shown below (this is what happens with the endpoint slice controller).

```
> $ (kind-ise-9887) k exec -it -n kube-system kube-proxy-tdj95 -- iptables-save | grep nginx                                                                                                                                                  -A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx" -m tcp --dport 31930 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SEP-CJVHZCPJP4LTNJKI -s 100.64.0.5/32 -m comment --comment "default/nginx" -j KUBE-MARK-MASQ
-A KUBE-SEP-CJVHZCPJP4LTNJKI -p tcp -m comment --comment "default/nginx" -m tcp -j DNAT --to-destination 100.64.0.5:80
-A KUBE-SERVICES ! -s 100.64.0.0/16 -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 80 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SVC-2CMXP7HKUVJN7L6M -m comment --comment "default/nginx" -j KUBE-SEP-CJVHZCPJP4LTNJKI

> $ (kind-ise-9887) k scale deployment nginx --replicas 0                                                                                                                                                                                     deployment.apps/nginx scaled

> $ (kind-ise-9887) k exec -it -n kube-system kube-proxy-tdj95 -- iptables-save | grep nginx                                                                                                                                                  -A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "default/nginx has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 31930 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 100.72.47.228/32 -p tcp -m comment --comment "default/nginx has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
```

### How can we reproduce it (as minimally and precisely as possible)?

In an empty (e.g. kind) cluster with k8s 1.21, set up a simple nginx deployment with 1 pod and a standard service. 
Add the feature gate to the kube-proxy config:

```
featureGates:
  EndpointSliceProxying: false
```

### Anything else we need to know?

Observed in 1.21 with FeatureGate EndpointSliceProxying set to false, which is locked to true in 1.22. So this will be irrelevant with the EoL of 1.21 in 4 weeks anyway. 

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-03-07T09:03:24Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}```

k exec -it -n kube-system kube-proxy-mrgkm -- kube-proxy --version                                                                                                                                                        Kubernetes v1.21.10
</details>


### Cloud provider

none, on-premise vanilla k8s and/or kind

### OS version

<details>

not relevant, reproducible in kind (e.g. on amd64)

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment] 2022-05-31 08:58
do we know the root cause?

We had an issue with the logic used to detect stale entries https://github.com/kubernetes/kubernetes/pull/106163/commits/909925b492a674bbadb8de9b694eef67cefabdb1 but it will be interesting to know why it only affects endpoints and no slices

**Comment by aojea** [comment] 2022-06-01 10:26
> I would guess the above is unrelated, since this is related to not only non-ready pods/endpoints but deleted pods/endpoints as well. No root cause is known yet, I didn't dig into the code so far.

for a bug fix we should have a test reproducing the issue so we can cover the regressions, you can check in https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier_test.go for some examples, but based on that example I think we should be able to reproduce that behavior with an unit test :thinking:

**Comment by thockin** [comment] 2022-06-09 15:47
Yeah, if this is real, we should fix it.

**Comment by robscott** [comment] 2022-06-09 16:19
Thanks for the detailed bug report @sfudeus! Reading through this bug, it appears that this is limited to kube-proxy's implementation when it is reading from Endpoints, it does not appear to represent any bug within the Endpoints controller itself. If it did represent a bug in Endpoints itself, that would be significant as that is something we want to support long term. From what I can tell this is limited to kube-proxy when reading from Endpoints though. 

This represents non-default configuration that is only possible in a nearly EOL release (1.21). Since the kube-proxy logic that reads from EndpointSlices does not have that issue and is default in 1.19+ and locked to GA in 1.22+, I think we can consider this fixed (or wontfix depending on your interpretation).

/close

**Closed** 2022-06-09 16:19 UTC
Labels: kind/bug, sig/network, needs-triage
