### ISSUE TITLE
Increase Integration Test Coverage

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#5538] opened 2015-03-17 09:57 UTC
@wojtek-t 

PR #5205 introduced a deadlock in kubelet. syncStatus function was holding podLock when calling another function that tried to lock it.
This bug was caught by e2e tests, but should easily be caught by integration tests.

**Comment by wojtek-t** [comment] 2015-03-17 10:35
As discussed offline, this is because running:
hack/test-integration.sh
is not running the "real kubelet" - it is using it's custome fakeKubelet implementation.
That said it's not really "integration test" in a sense that it's not testing all components of the system.

**Comment by vmarmol** [comment] 2015-03-17 17:44
This seems like it would have been caught by an integration test that tested pod status. The issue is probably lack of test coverage at the integration layer. We kinda use e2e for that lately, although there is discussion about improving coverage.

**Comment by yujuhong** [comment] 2015-03-17 19:12
Integration test does run real kubelets using `SimpleRunKubelet()`. The so-called `fakeKubelet` perhaps refers to the `fakeKubeletClient` defined in integration.go?
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L68

fakeKubeletClient is created and then passed to the master so that master can retrieve pod status and nodeinfo, etc. I think it exists because we run *two* real kubelets on the localhost, hence some redirecting magic is needed in this fake client.

FWIW, I added some pod status tests (for static pods) in #5401. These tests should test your PR #5205 properly. You may want to add a new test targeted towards a regular pod to make the failure more obvious.

Another point is that since your PR is to allow kubelet to post the pod status, some code in the `fakeKubeletClient` may be redundant or obsolete. You might want to take a look and remove them.

**Comment by gmarek** [comment] 2015-03-18 15:09
@vmarmol: Is there an issue for improving integration tests? Other thing that gone through them was segfault when trying to schedule nodes with resource limit set. It looks to me that we're currently not in a very good state.

**Comment by vmarmol** [comment] 2015-03-18 17:55
@gmarek I looked but I was unable to find one so we can re-purpose this one for that. The main issue I find is lack of coverage. That's to blame for the last two breakages it could have caught. Arguably, unit tests could have done the same for both errors so far.

**Comment by wojtek-t** [comment] 2015-03-18 18:14
I agree that it't not only the case of integration tests, but also quite low unit tests coverage.
But adding more sophisticated unit tests is also a good move :)

**Comment by yujuhong** [comment] 2015-03-30 16:51
The pod status test coverage is pretty poor (see #6107 from last week). In the integration test, the only related test is the static pod test which only looks for the "Running" status. We should have tests that are dedicated to test various pod status: pending, failed, succeed, etc. Ideally, these should interact with a real apiserver, so integration test would be a good place to start with (or e2e if one prefers).

**Comment by erictune** [comment] 2015-03-30 17:32
A good starting point for a simple integration test is `test/integration/secret_test.go`

Suggestions for new integration tests:
 - start a pod on a kubelet via `pkg/client` (pod doesn't actually run, but kubelet should send right command to docker.)
 -  start a pod on a kubelet via kubectl (pod doesn't actually run, but kubelet should send right command to docker.)
 - fuzz test that creates random objects and makes sure that the response is not a 500 and there is no crash.  delete objects after each is created. 
 - create pods and test that scheduler spreads pods across nodes
 - create pods which have hostPort.  
   - if you have two nodes and 3 pods, one should fail to schedule.
   - if you override scheduler by setting Spec.Host. to same host for two pods, then Kubelet should reject one.
 - create pods with resource requests
  - pod bigger than any node fails to schedule.
  - create many small pods, some fail to schedule
  - bypass scheduler by setting Spec.Host.  Kubelet rejects some pods due to excessive resource requests.
 - replication controller resize increases pods
 - pod deletion causes replication controller to recreate.

**Comment by gmarek** [comment] 2015-08-31 11:04
@quinton-hoole what's the best course of action for this? I don't know what's the current state of integration tests nor if we even care.

**Comment by yujuhong** [comment] 2017-06-01 23:58
Can we close this issue? This is marked as a node issue, and we already have a pretty comprehensive node e2e test suite. I don't know if it makes sense to port them to be integration tests, but a long-standing issue like this doesn't help.

**Comment by gmarek** [comment] 2017-06-02 10:26
Closing due to age.

**Closed by gmarek** 2017-06-02 10:26 UTC
Labels: area/test-infra, priority/backlog, sig/node
