### ISSUE TITLE
Secret keys should allow underscores

### ISSUE THREAD

**Issue by ryanschwartz** [kubernetes/kubernetes#26663] opened 2016-06-01 22:24 UTC
The [Secrets user guide](http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-manually) states that `The data field is a map. Its keys must match DNS_SUBDOMAIN, except that leading dots are also allowed. The values are arbitrary data, encoded using base64.`

This feels like an arbitrary restriction, and it definitely impacts usefulness of being able to mount secrets as volumes - disqualifying keys matching any filename that normally contains underscores (`id_rsa`, `id_dsa`, `authorized_keys`, `sshd_config`, `ssh_host_key`, etc. ad infinitum).

Please consider modifying the criteria for key names to something a bit less restrictive - these aren't URLs and the underscore is an incredibly pervasive character in many standard _UNIX_ filenames.

**Comment by Random-Liu** [comment] 2016-06-01 22:29
@pmorie @bgrant0607 @kubernetes/kube-api

**Comment by derekwaynecarr** [comment] 2016-06-01 22:47
I agree it would be good to support underscore.  

Ideally you could provide a projection for a secret key to its manifested file name.

**Comment by dims** [comment] 2016-06-02 01:14
There's a PR in progress - https://github.com/kubernetes/kubernetes/pull/25458

**Comment by deads2k** [comment] 2016-06-02 13:17
Also, looks like a dupe of https://github.com/kubernetes/kubernetes/issues/6589

**Comment by pmorie** [comment] 2016-06-02 16:30
> Ideally you could provide a projection for a secret key to its manifested file name.

You can already do this.

**Comment by pmorie** [comment] 2016-06-02 16:31
Please see #25285, which will ship in 1.3

**Comment by pmorie** [comment] 2016-06-02 16:33
Docs PR: kubernetes/kubernetes.github.io#478

**Comment by derekwaynecarr** [comment] 2016-06-02 19:46
@pmorie - i couldnt find the PR at the time, I remember us discussing this.   

we should update `kubectl create secret` preserve names now to take advantage of this?

**Comment by thockin** [comment] 2016-08-20 00:15
fixed in 1.4

**Closed by thockin** 2016-08-20 00:15 UTC
Labels: area/api, priority/P2, team/api
