### ISSUE TITLE
v1.1 guide still installing v1.0.3

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#19641] opened 2016-01-14 06:02 UTC
Hi all,

I was looking here today: http://kubernetes.io/v1.1/docs/getting-started-guides/ubuntu-calico.html and it looks like though the docs are for v1.1 the guide is still installing v1.0.3. Is there any plan to change that?

**Comment by bgrant0607** [comment] 2016-01-29 00:45
Dupe of #17887

**Closed by bgrant0607** 2016-01-29 00:45 UTC
Labels: area/os/ubuntu, team/ux
