### ISSUE TITLE
Ingress and TCP 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23291] opened 2016-03-21 18:59 UTC
This is more of an open question, should we teach the Ingress about TCP?

If we fold TCP into Ingress:
- Everything in the Ingress is about entry into the cluster 
- Everything in the Service is intra cluster (ips, algorithms, affinity etc) 
- Type=NodePort will continue to be an escape hatch for Services

This would enable us to leverage the Ingress for things like SSL routing (https://github.com/kubernetes/kubernetes/issues/19333), and leverage Service.Type=Loadbalancer for internal lb (whatever form that takes). 

**How to express type=loadbalancer?**

Create an Ingress like:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  backend:
    serviceName: backendSvc
    servicePort: 80
```

kubectl expose would do this (discussion on https://github.com/kubernetes/kubernetes/issues/17429 needs to converge). 

**How to express SNI?**

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rules-map
spec:
  # SSL routing
  rules:
  - host: www.foo.com
    tcp:
      backend:
        serviceName: svc1
        servicePort: 80
  - host: foo.bar.com
    tcp:
      backend:
        serviceName: svc2
        servicePort: 80
```

If the above spec is defined _with_ a TLS section, the Ingress controller will terminate the connection using SNI to figure out which certs to serve. Discussion on: https://github.com/kubernetes/kubernetes/issues/19333

**Do we need to express TCP frontend ports?**

The challenge here is defining a frontend port that we don't really need for HTTP (:80 and :443 are implicit). One way is:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rules-map
spec:
  rules:
  - host: www.foo.com
    tcp:
      port: 3321
      backend:
        serviceName: svc1
        servicePort: 80
```

Another option is to disallow `port`, the Ingress controller just picks one and writes it to Status (on GCE a port is not needed). All that matters is that TCP traffic reaches the backend. For legacy apps that _need_ a port, they create multiple ingresses with a `ingress.port` annotation that the Ingress controller tries to honor.

@kubernetes/goog-cluster @kubernetes/rh-networking @smarterclayton @aledbf @thockin @therc

**Comment by smarterclayton** [comment] 2016-03-22 04:15
Moderately in favor.

I like ingress as the indicator of external access, since it
simplifies services.  I think it's a little wierd to leave node port
on service in this case, although it would complicate the proxy to
remove it.  I like being able to mix externalIP and NodePort to handle
VIPs, but I'd prefer externalIP under ingress status where we can
control it with authz than under spec of service.

Re-encrypt is a use case we got asked for as much as SNI, as well as
what to do for HTTP endpoint (redirect or deny).

Front end ports feel more like Status than spec (you can ask for them
in spec, but they may not be honored).  Front end ports would be one
way to move NodePort out of service.

**Comment by kokhang** [comment] 2016-04-18 17:10
Hi bprashanth, I am looking at ingress/ingressContoller to provide access to multiple non-http(s) apps from the outside. How would you provide access to many apps which expose the same port? For example, if i want to provide access to two different mysql deployments, in which both expose 3306. How can i do this without having to use random ports for each?  Are you thinking of supplying a vip for every service and have that vip map to the backend app? Thanks

**Comment by sputnik13** [comment] 2016-05-03 21:09
we would really like to see TCP support in Ingress, is there anything we can do to help move this forward beyond an idea?

**Comment by bprashanth** [comment] 2016-05-03 22:21
@sputnik13 a big step forward would be teaching the existing ingress controllers about Type=LoadBalancer behavior (and flag controlling it). It really doesn't make sense to have 2 things that do ingress tcp, but we already have type=lb. When Ingress does TCP the idea is that we'd deprecate Type=Loadbalancer (or repurpose it to mean internal lb). 

So the code in service_controller needs to be moved to an Ingress controller (or the other way around, though I'd rather have just one thing that understands ingress) - if someone creates a tcp ingress or a service of type=loadbalancer, they should get the same thing. I think most people are Ok with tcp ingress as long as we don't have 2 idioms that we support forever that mean the exact same thing.

**Comment by sputnik13** [comment] 2016-05-04 21:15
@bprashanth given existing ingress controllers are contribs, is it necessary that they all come to a common implementation of TCP or are you saying that someone needs to create an ingress controller that supports TCP, then the community can reason about whether to accept it?

I assumed that the path to acceptance would be more along the lines of getting agreement on what the Ingress resource spec would look like (which I think you already did), then creating code for the API to accept those changes to the spec, then flowing that down to ingress controllers...

I'm still quite new to the community so just looking for pointers on how best to help this effort.

**Comment by bprashanth** [comment] 2016-05-04 21:48
So I create a TCP ingress on aws/gce etc, how will that work?     

1. It won't work - not acceptable. Then we don't have a cross platform resource. You can just use config map like the nginx controller currently does. 
2. It won't work till we've ported the code in service_controller that currently fulfills service.Type=Loadbalancer to respect both service.Type=Loadbalancer and TCP Ingress, at which point we deprecated type=loadbalancer
3. We port the code now, then (or in parallel) create a TCP Ingress resouce in the api, so it works from the start

3 > 2
The danger of adding a resource now without doing 2 is that you end up with a messy solution. We can't have 2 ways to do TCP lb, and we can't add a resource that has only 1 backend.

**Comment by sputnik13** [comment] 2016-05-11 22:36
@bprashanth I'm not suggesting that the feature should go out with incomplete implementations, what I'm asking for is some sort of agreement on what the Ingress resource looks like that supports TCP so that we can start implementing it.

FYI, the NGINX ingress controller already does support TCP and UDP ingress via ConfigMap.

I've started a proposal mostly based on what you posted here (https://github.com/sputnik13/kubernetes/blob/l4-ingress-proposal/docs/proposals/l4-ingress.md).  Not sure whether I'm following the correct processes.  If I'm not, please let me know what I can do better.

**Comment by bprashanth** [comment] 2016-05-11 23:00
@sputnik13 That sounds good, please open a pr. Ther's no format per-se, just pattern match existing proposals: https://github.com/kubernetes/kubernetes/tree/master/docs/proposals

Fyi since this is not going to make 1.3 comments will trickle through till the release, but if we have everyone on the same page at the start of 1.4 we should be able to nail it for next-release.

**Comment by pires** [comment] 2016-05-19 13:22
> This is more of an open question, should we teach the Ingress about TCP?

Yes! And @sputnik13 proposal nails it.

**Comment by bprashanth** [comment] 2016-12-01 02:26
@louiscryan

**Comment by jayunit100** [comment] 2017-03-28 16:58
Should we close this issue?...  since the original purpose was to debate the question.  It looks like

- community agrees on tcp/l4 and , 
- L4 proposal was successfully merged

**Comment by kargakis** [comment] 2017-03-28 17:04
@jayunit100 can you post a link to the proposal that was merged?

**Comment by jayunit100** [comment] 2017-03-28 17:08
#25821 above ......?

**Comment by kargakis** [comment] 2017-03-28 17:15
Doesn't look like it got merged.

**Comment by jayunit100** [comment] 2017-03-28 19:53
Ahhh sorry ; closed, not merged: In any case,  Are we all in agreement that the proposal en route will just flesh out details but the community wants ingress to support L4?  If so we still should close.

**Comment by jayunit100** [comment] 2017-03-28 19:55
I.e. My motive here is to establish that we do (or don't) agree on L4 support - and we can debate the implementation in a follow on issue.

**Comment by slaskawi** [comment] 2017-05-08 12:57
Perhaps this proposal (https://github.com/kubernetes/community/pull/446) might be connected (or may partially solve) to this issue.

**Comment by thockin** [comment] 2017-05-31 06:27
We should take this up in 1.8

**Comment by pires** [comment] 2017-05-31 08:37
I want Ingress TCP and would be willing to work on a controller for GCP. The #25821 should be re-opened and agreed upon first.

**Comment by freehan** [comment] 2017-05-31 21:42
L4 Ingress probably makes more sense in the context of federation, maybe?

**Comment by joemiller** [comment] 2017-05-31 22:54
I don't think federation is necessary. This makes a lot of sense for us as we do lots of mTLS client auth which is not possible with the L7 GCP HTTPS LB currently.

**Comment by djsly** [comment] 2017-05-31 23:55
This makes a lot of sense for us as well, we have in house tcp based
protocol that are almost impossible to convert to http that would greatly
benefit from this.

**Comment by nicksardo** [comment] 2017-06-01 00:21
@djsly @joemiller How does this L3/4 via ingress enable your use cases? Why can't you use a service with type=loadbalancer?

**Comment by joemiller** [comment] 2017-06-01 00:33
Nick yes we currently do that. We'd like to move to Ingress in general to
simplify patterns for our internal developers. But you are correct, the
real win for us will be federation + L4 global LB so we can deploy global
mTLS services. I retract my previous statement. This is most valuable for
us in the federation context.

**Comment by djsly** [comment] 2017-06-01 01:43
@nicksardo 
1) The Load Balancer doesn't support SSL termination and we would like to combine our ssl management in the same controller. 
2) We have multiple namespaces in the same cluster exposing the same services, some Cloud provider have limits on the number of PublicIP that can be added by Load Balancer hence using a single point of entry (ingress controller' service) simplify things up a lot.

**Comment by thockin** [comment] 2017-06-01 05:11
Are people willing to give up things like source IPs to get this?

**Comment by pires** [comment] 2017-06-01 06:37
Why would there be the need to give up? For instance, ELB supports PROXY protocol as an opt-in. Doesn't GCLB L4 do something like that as well? I know apps need to accommodate that but it's a trade-off.

I wonder if a Service, which last time I checked in GKE generates a regional GCLB L4, is any different.

**Comment by thockin** [comment] 2017-06-01 06:39
I was ignoring PROXY on purpose, but yes, that is the lengths people will
have to go to :)

**Comment by pires** [comment] 2017-06-01 07:10
I mean, it's the same trade-off as in L7 with the HTTP headers being put in place. But you have a point this will need to be made clear to users.

As a note, just confirmed GCLB L4 does support PROXY v1.
![screen shot 2017-06-01 at 08 09 55](https://cloud.githubusercontent.com/assets/1752631/26668469/c6af9e1a-46a1-11e7-8c41-253f6cf88524.png)

**Comment by thockin** [comment] 2017-06-01 07:19
with HTTP it is explicitly in-protocol.  Proxy is a bolt-on thing.  That's
all I meant.

**Comment by joemiller** [comment] 2017-06-02 14:34
@thockin Yes, we are willing to give up source-ip. We're looking at this mainly for mTLS connections and in those cases we care much more about authenticating the client cert than the source-IP.

**Comment by thockin** [comment] 2017-06-04 19:01
Ok, we can certainly explore this after 1.7, but we need to be careful with
expansion and overall surface area.

**Comment by hiscal2015** [comment] 2017-08-03 02:44
+1 It is wonderful if ingress supports TCP and SNI

**Comment by accnops** [comment] 2017-12-14 10:43
Hi! Is this still being investigated?

I could certainly use this in my projects...

**Comment by pires** [comment] 2017-12-14 12:40
There was a proposal PR but it got closed #25821

**Comment by slaskawi** [comment] 2018-02-02 10:27
I would also love to see an Ingress that supports custom TCP-based protocols. Currently in OpenShift we got it working by using TLS/SNI. However you get a performance hit that was and in some cases (like Data Grids without sensitive data) it is not desirable. Another options to look at are `HTTP/1.1 Upgrade` and TLS/ALPN for switching an HTTP connection to a custom protocol. We'll see how that goes in the future.

Of course I do agree with @thockin that we have a Load-Balancer Services for this but @smarterclayton also has a point that an Ingress indicates that there will be some traffic from the outside world whereas Services seem to be more internal to me.

So again, I know you can achieve this kind of behavior even today but I would love to see a TCP Ingress someday in Kube.

**Comment by bgrant0607** [comment] 2018-02-02 17:58
cc @kubernetes/sig-network-feature-requests @bowei

**Comment by ggprod** [comment] 2018-02-21 22:02
So in the time-being (intil the L4 Ingress feature makes it into a release).  What is the best way to provide an SSL Proxy Load Balancer functionality for pods deployed on GKE?

**Comment by tookko** [comment] 2018-03-23 15:44
It would be great if there was an elegant way to integrate ingress also for other non-HTTP TCP protocols. For example, an IIOP proxy would be needed for CORBA based traffic, a simple L4 proxy cannot handle it.

**Comment by git001** [comment] 2018-05-30 00:43
I have described several ingress controller solutions for kubernetes in my blog post https://www.me2digital.com/blog/2018/05/session-sticky/#kubernetes-ingress all of them can handle http/https/tcp and some of them also udp.

From my point of view are there several available solutions for a generic ingress handler. Doesn't the current solutions solve the question?

**Comment by pires** [comment] 2018-06-07 09:03
@git001 Ingress controllers have to resort to their own solutions to provide such functionality, e.g. [HAProxy Ingress controller uses ConfigMap](https://github.com/jcmoraisjr/haproxy-ingress#tcp-services-configmap). The desire discussed in this thread is to evolve the `Ingress` object, or create a new object, for L4 load-balancing.

**Comment by MichaelSp** [comment] 2018-06-07 11:49
Here is a working solution for SNI: https://github.com/kubernetes/kubernetes/issues/19333#issuecomment-395392064

**Comment by pires** [comment] 2018-06-07 11:57
This is still not L4 Ingress!

**Comment by alexkreidler** [comment] 2019-07-01 13:54
I would love to see a natively supported method in Kubernetes for a L4 ingress. This would make exposing services so much easier.

Thanks everyone for discussing and working on this, but I would really love to see this idea take the next steps towards reality. Hopefully some maintainers pick up on this?

**Comment by mishushakov** [comment] 2019-07-15 13:21
Hey,
I have a bit complicated case here, where this would help. I have set up a mail-server within Kubernetes cluster and to function properly it has to have access the IPs (to do some spam checks, etc.).

Luckily my provider offers a PROXY protocol support for the LoadBalancer, so i have configured it in mail-server i use. I also have application inside of my cluster, which should be able to talk to the mail-server and the problem is, since the mail server is configured to accept PROXY requests, it is no longer able to process non-PROXY requests from my application (because it can't work with PROXY).

The logical way for me to resolve this issue, is to point my TCP traffic to my Ingress, which will then resolve the PROXY request and forward it normally to/from my mail-server. This way i would get the both of two world without any compromise - my mail-server will still be able to get the request IP and my applications would still be able to talk to the mail-server.

Thank you for.

**Comment by mdavid626** [comment] 2020-05-14 12:43
Please add support for TCP/UDP ingress! This is essential!!! If you want to expose e.g. a database with a fixed port with different hostnames or run a load balancer for non-HTTP traffic (e.g. for RabbitMQ).

e.g., two namespaces:
namespace1: db.myhost1.com:27017 (routes to db in namespace1)
namespace2: db.myhost2.com:27017 (routes to db in namespace2)

**Comment by thockin** [comment] 2020-11-04 18:26
This will be covered by the newer Gateway API: https://github.com/kubernetes-sigs/service-apis

**Closed by thockin** 2020-11-04 18:26 UTC
Labels: area/ingress, kind/api-change, kind/feature, lifecycle/frozen, sig/network
