### ISSUE TITLE
kubeadm join success but node not joined.

### ISSUE THREAD

**Issue by kindule** [kubernetes/kubernetes#61224] opened 2018-03-15 14:15 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
`kubeadm join ...` ok, but `kubectl get nodes` not appear the joined node
![image](https://user-images.githubusercontent.com/4156139/37468350-c44bbc10-289d-11e8-8780-237518765e2f.png)
![image](https://user-images.githubusercontent.com/4156139/37468355-ca57cf18-289d-11e8-9d99-20079853f75c.png)

**What you expected to happen**:

kubectl get nodes appear the node.

**How to reproduce it (as minimally and precisely as possible)**:
Just use `kubeadm join --token 0b415f.52831331ff2d780d 10.10.90.118:6443 --discovery-token-ca-cert-hash sha256:f8de0aade3208be5d92a26bd0bc5493636d5200997a3e7025d0bf2ccb0f4d7e9`

**Anything else we need to know?**:
no.

**Environment**:
- Kubernetes version (use `kubectl version`):
master and node with the same version
![image](https://user-images.githubusercontent.com/4156139/37468401-edf36da6-289d-11e8-9dd8-577bc480afc7.png)

- Cloud provider or hardware configuration:
Both baremetal machine 
- OS (e.g. from /etc/os-release):
master and node with the same version
![image](https://user-images.githubusercontent.com/4156139/37468445-052c8c5a-289e-11e8-8aad-9607919e9bb9.png)

- Kernel (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/4156139/37468461-0bf11c22-289e-11e8-8e68-6db6a7fd3e63.png)

- Install tools:
`kubeadm` for my installation

- Others:

**Comment by XANi** [comment] 2018-03-19 14:29
Got the same problem. I can see certs in `kubectl get csr` that are still in `Pending` state; manually approving them does not help

**Comment by yinwoods** [comment] 2018-03-29 09:27
Got the same problem

**Comment by Cheneytt** [comment] 2018-04-23 02:39
Got the same problem. finally, I removed all k8s config `/etc/kubernetes/*`, and then reinstall k8s, succeed. I guess it caused by older version config.

**Comment by Freezzie** [comment] 2018-04-23 15:29
Got the same problem.
Immediately after the creation the workers joined successfully, but after 3 days "kubeadm join" is successfully, but node is not visible in kubernetes.

**Comment by cburki** [comment] 2018-04-26 14:40
Got the same problem but it seems that the token generated during the initialization has expired. Check it by issuing the following command on the master.
`kubeadm token list`
And check the date in the `EXPIRES` column. If it has expired, create a new token.
`kubeadm token create --print-join-command`
You will now be able to join a new node using the given command.

**Comment by TodayyadoT** [comment] 2018-05-08 04:52
Got the same problem.
The hostname of your VMs must be different, or the master couldn't distinguish them.

**Comment by nachimehta** [comment] 2018-06-14 19:04
Copy paste from my stackoverflow [answer](https://stackoverflow.com/a/50864198/2097898): 

I had this problem and it was solved by ensuring that cgroup driver on the _worker_ nodes also were set properly.

check with:

    docker info | grep -i cgroup
    cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

set it with:

    sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" 
    /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

then restart kubelet service and rejoin the cluster:

    systemctl daemon-reload
    systemctl restart kubelet
    kubeadm reset
    kubeadm join ...

Info from docs: https://kubernetes.io/docs/tasks/tools/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-master-node

**Comment by raghu0220** [comment] 2018-08-01 19:24
Having same issue, Installed kubernetes, kubeadm version 1.9.3. 
On master kubeadm init ran successfully and created pods.
[root@kubmst2-2 centos]# kubectl get nodes
NAME                               STATUS    ROLES     AGE       VERSION
kubmst2-2			   Ready     master    4h        v1.9.3

[root@kubmst2-2-centos]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                       READY     STATUS    RESTARTS   AGE
kube-system   etcd-kubmst2-2                      			 1/1       Running   0          4h
kube-system   kube-apiserver-kubmst2-2            			 1/1       Running   0          4h
kube-system   kube-controller-manager-kubmst2-2  			 1/1       Running   0          4h
kube-system   kube-dns-6f4fd4bdf-kpvld                                   3/3       Running   0          4h
kube-system   kube-flannel-ds-amd64-4pwbf                                1/1       Running   0          4h
kube-system   kube-proxy-k69bg                                           1/1       Running   0          4h
kube-system   kube-scheduler-kubmst2-2           			 1/1       Running   0          4h
[root@kubmst2-2-prd centos]#

When i run the kubeadm join command on the node it says successfully established the connection with the apiserver but it doesn't show in the "kubectl get nodes" and it failed to start the kubelet.  
it's failing to create the files
/etc/kubernetes/manifests, /etc/kubernetes/kubelet.conf, /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf, /etc/kubernetes/manifests/etcd.yaml.

**Comment by nachimehta** [comment] 2018-08-07 18:39
You could try copy and pasting the files from your master in the appropriate place on your nodes, but the fact that the files aren't generating seems to be a different issue than is listed here. Try re-installing kubernetes on your nodes? Ensure they are the same version as your master.

**Comment by chxiaowu** [comment] 2018-09-26 08:10
> Got the same problem.
> The hostname of your VMs must be different, or the master couldn't distinguish them.
> Modify other nodes name and then `kubeadm reset` and `kubeadm join`

Thanks！ Using vm， the images are copy. So the hostname are same. changed hostname will be fine.

**Comment by neolit123** [comment] 2018-10-26 22:43
closing this one.
if you have a specific bug or a feature to report against kubeadm use the kubernetes/kubeadm repo.

for questions and support try our support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

thanks
/close

**Closed by neolit123** 2018-10-26 22:43 UTC
Labels: kind/bug, sig/cluster-lifecycle

**Comment by hhyo** [comment] 2018-10-31 10:21
> Got the same problem.
> The hostname of your VMs must be different, or the master couldn't distinguish them.
> Modify other nodes name and then `kubeadm reset` and `kubeadm join`

Thanks！

**Comment by bigbang009** [comment] 2018-11-03 10:02
> Got the same problem but it seems that the token generated during the initialization has expired. Check it by issuing the following command on the master.
> `kubeadm token list`
> And check the date in the `EXPIRES` column. If it has expired, create a new token.
> `kubeadm token create --print-join-command`
> You will now be able to join a new node using the given command.

Is it a bug in kubeadm while token has expired but joining node prompt successfully?

**Comment by spdo88** [comment] 2019-03-11 17:38
Have the same problem on V1.13.3. If I down grade it to V1.12., it works perfectly without any problem.
but it shows the worker  node is running on the get pods command:
10.46.29.98   is the master node
10.46.29.68   is the worker node

# kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                                           READY   STATUS    RESTARTS   AGE   IP            NODE                                   NOMINATED NODE   READINESS GATES
  <snipped>
  <snipped>
kube-system   kube-flannel-ds-amd64-5mpzb                                    1/1     Running   0          19m   10.46.29.98   u0i-0fcd4a53fd74ccde5.u0.ww.conti.de   <none>           <none>
kube-system   kube-proxy-xv4g5                  1/1     Running   0          21m   10.46.29.68   u0i-0fcdxxxxxx.u0.xx.xx.cp,   <none>           <none>
kube-system   kubernetes-dashboard-57df4db6b-hkxv8                  1/1     Running   0          19m   10.244.0.24   u0i-0fcdxxxxxx.xx.xx.com   <none>           <none>
