### ISSUE TITLE
Does Kubernetes-1.1.2 supports ubuntu or debian VM on 'Microsoft Azure' ??

### ISSUE THREAD

**Issue by sharminakteranee** [kubernetes/kubernetes#24793] opened 2016-04-26 11:29 UTC
I tried ubuntu-14.04, 15.10 and debian-jessie images. But clusters not working

**Comment by thockin** [comment] 2016-04-27 03:22
http://kubernetes.io/docs/getting-started-guides/coreos/azure/

The only *documented* instructions are for CoreOS.  That doesn't mean the others can't work, just that nobody has done it and written it down (or at least didn't send it to us)

This topic would be better suited at StackOverflow - it's not a bug or feature request.  I am going to close this issue for now, please feel free to followup if you think this is wrong.

**Closed by thockin** 2016-04-27 03:22 UTC
