### ISSUE TITLE
[Flaky Test] In-tree Volumes: Error getting c-m metrics : the server could not find the requested resource

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#86318] opened 2019-12-16 17:52 UTC
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce
- ci-kubernetes-e2e-gci-gce

**Which test(s) are flaking**:

* [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should support readOnly file specified in the volumeMount [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support file as subpath [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (default fs)] volumes should allow exec of files on the volume
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing single file [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] volumes should store data
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should store data
* [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
* [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support existing directories when readOnly specified in the volumeSource
* [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directories when readOnly specified in the volumeSource
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing single file [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (ext3)] volumes should allow exec of files on the volume
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (ext3)] volumes should store data

**Testgrid link**:
- https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default&width=5&include-filter-by-regex=In-tree&sort-by-flakiness=
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=In-tree&width=5&sort-by-flakiness=

**Reason for failure**:
Failure fetching metrics:
```
Dec 15 22:01:17.942: Error getting c-m metrics : the server rejected our request for an unknown reason (get pods kube-controller-manager-e2e-4fc8c5bbfe-674b9-master:10252)
...
Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "unknown",
                        Field: "",
                    },
                ],
```
```
Dec  4 20:06:05.021: Error getting Kubelet e2e-f19735d0af-674b9-minion-group-l4ln metrics: the server is currently unable to handle the request (get nodes e2e-f19735d0af-674b9-minion-group-l4ln:10250)
...
Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Error trying to reach service: 'dial tcp 10.40.0.4:10250: i/o timeout'",
                        Field: "",
                    },
                ],
```

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics&job=pull-kubernetes-e2e-gce%24&test=sig-storage

This appears to have restarted abruptly around 2/11-2/12

/sig storage
/priority important-soon

**Comment by liggitt** [comment] 2019-12-17 18:52
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1206995563719954438/

**Comment by liggitt** [comment] 2019-12-17 19:27
xref #86312 

I think we have a general failure to start containers reliably. Almost every instance of these test failures contained the pod status error of "OCI runtime start failed: container process is already dead: unknown"

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206995563719954438
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206995563719954438
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206989684341739522
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206963761311649796
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206944256451678211
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206933812953485313
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206930288853127169

**Comment by liggitt** [comment] 2019-12-17 19:31
@kubernetes/sig-node-test-failures

**Comment by liggitt** [comment] 2019-12-17 20:32
after sweeping a bunch of the in-tree test failures, almost all seemed to have https://github.com/kubernetes/kubernetes/issues/86312 as a root cause, triggered by very short-lived containers used to check file content or permissions.

The only test I saw failing that didn't seem to fit that was:

[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent path
```
test/e2e/storage/testsuites/subpath.go:191
Dec 17 19:12:19.924: Unexpected error:
    <*errors.errorString | 0xc0027e44b0>: {
        s: "expected \"content of file \\\"/test-volume/provisioning-9844/test-file\\\": mount-tester new file\" in container output: Expected\n    <string>: content of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/provisioning-9844/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retrying\nto contain substring\n    <string>: content of file \"/test-volume/provisioning-9844/test-file\": mount-tester new file",
    }
    expected "content of file \"/test-volume/provisioning-9844/test-file\": mount-tester new file" in container output: Expected
        <string>: content of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/provisioning-9844/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retrying
    to contain substring
        <string>: content of file "/test-volume/provisioning-9844/test-file": mount-tester new file
occurred
test/e2e/framework/util.go:829
```

examples:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1207004999654051841
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206930288853127169

I'd recommend repurposing this issue to address that specifically and leave the OCI issue for the short-lived container issue

**Comment by MorrisLaw** [comment] 2020-01-30 19:10
I think this is another example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87090/pull-kubernetes-e2e-gce/1222925370781601792/

message:
```
[sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should support readOnly file specified in the volumeMount
```

pr:
https://github.com/kubernetes/kubernetes/pull/87090

**Comment by liggitt** [comment] 2020-02-14 04:04
The "error getting c-m metrics" failures appear to have just restarted:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics

**Comment by liggitt** [comment] 2020-02-14 04:40
/priority critical-urgent

bumping priority since we're seeing significant numbers of failures that just started in the last two days

**Comment by liggitt** [comment] 2020-03-05 19:15
@gnufied this is failing many test runs per day, do you have updated status on this? https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics&job=pull-kubernetes-e2e-gce%24&test=sig-storage

**Comment by gnufied** [comment] 2020-03-05 19:53
I haven't had chance to fully debug this yet. @davidz627 looked into this little bit and he suspected that these tests started to flake same time around https://github.com/kubernetes/kubernetes/pull/85029 was merged. I should be able to take a closer look tomorrow.

**Comment by aojea** [comment] 2020-03-09 19:37
This occurrence https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88934/pull-kubernetes-e2e-gce/1237026445675466753/ fails because it's trying to get the metrics from the kube-controller-manager pod but it is not ready until one minute later
 
```
            Message: "the server could not find the requested resource (get pods kube-controller-manager-e2e-b4cf5dd729-674b9-master:10252)",
 ```

if we grep in the kube-apiserver for the controller pod name we can observe that after the pod is up it starts to get 200 instead of 404

```
I0309 15:05:22.546216       1 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/pods/kube-controller-manager-e2e-b4cf5dd729-674b9-master:10252/proxy/metrics" latency=396.390669ms resp=404 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (default fs)] volumes should allow exec of files on the volume" srcIP="35.188.161.128:38518":
I0309 15:05:25.073291       1 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/pods/kube-controller-manager-e2e-b4cf5dd729-674b9-master:10252/proxy/metrics" latency=92.126104ms resp=404 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directory" srcIP="35.188.161.128:38496":
I0309 15:05:29.247571       1 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/pods/kube-controller-manager-e2e-b4cf5dd729-674b9-master:10252/proxy/metrics" latency=149.299022ms resp=404 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted" srcIP="35.188.161.128:38472":
I0309 15:05:35.389649       1 admission.go:211] getting pod security policies for pod kube-controller-manager-e2e-b4cf5dd729-674b9-master (generate: )
I0309 15:05:35.394447       1 admission.go:135] pod kube-controller-manager-e2e-b4cf5dd729-674b9-master (generate: ) in namespace kube-system validated against provider gce.privileged
I0309 15:05:35.397801       1 admission.go:211] getting pod security policies for pod kube-controller-manager-e2e-b4cf5dd729-674b9-master (generate: )
I0309 15:05:37.160211       1 graph_populator.go:148] updatePod kube-system/kube-controller-manager-e2e-b4cf5dd729-674b9-master for node e2e-b4cf5dd729-674b9-master
I0309 15:05:39.631917       1 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/pods/kube-controller-manager-e2e-b4cf5dd729-674b9-master:10252/proxy/metrics" latency=139.78459ms resp=400 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory" srcIP="35.188.161.128:38478":
I0309 15:05:40.646009       1 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/pods/kube-controller-manager-e2e-b4cf5dd729-674b9-master" latency=250.194561ms resp=200 UserAgent="kubelet/v1.19.0 (linux/amd64) kubernetes/ea63990" srcIP="34.83.30.189:52846":
```

**Comment by liggitt** [comment] 2020-03-10 19:47
keeping open until https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics&job=pull-kubernetes-e2e-gce%24&test=sig-storage shows this is resolved

**Comment by liggitt** [comment] 2020-03-10 22:22
seen again in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89010/pull-kubernetes-e2e-gce/1237448373842219008

**Comment by aojea** [comment] 2020-03-10 22:53
```
I0310 18:56:00.070041    1362 prober.go:133] Liveness probe for "kube-controller-manager-e2e-507247306d-674b9-master_kube-system(0c199f3fb8f138daa4d4f41cf004bb41):kube-controller-manager" succeeded
```

this time the container is running but still it can't find it

```
test/e2e/storage/testsuites/subpath.go:216
Mar 10 18:56:03.621: Error getting c-m metrics : the server could not find the requested resource (get pods kube-controller-manager-e2e-507247306d-674b9-master:10252)
```

**Comment by aojea** [comment] 2020-03-10 23:11
@liggitt the errors comes from the request to the apiserver on

```go
func (g *Grabber) getMetricsFromPod(client clientset.Interface, podName string, namespace string, port int) (string, error) {
```
How can we check that the pod is found and that the apiserver found it?
https://github.com/kubernetes/kubernetes/pull/88982/files#diff-33cbf1a465edc9c1de6150d5e6748177R170

**Comment by liggitt** [comment] 2020-03-11 12:54
the first successful get of /metrics logged by the controller manager in that run is at:
```
I0310 18:56:31.117404       1 httplog.go:90] verb="GET" URI="/metrics" latency=115.951652ms resp=200 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support file as subpath [LinuxOnly]" srcIP="10.40.0.2:54978": 
```

We're also not checking the error in the once.Do to make sure the pod was running, and once running, we should probably then also check the metrics path on the pod. Maybe something like this:

```go
	var err error
	g.waitForControllerManagerReadyOnce.Do(func() {
		if runningErr := e2epod.WaitForPodNameRunningInNamespace(g.client, podName, metav1.NamespaceSystem); runningErr != nil {
			err = fmt.Errorf("error waiting for controller manager pod to be running: %w", err)
			return
		}

		var lastMetricsFetchErr error
		if metricsWaitErr := wait.PollImmediate(time.Second, time.Minute, func() (bool, error) {
			_, lastMetricsFetchErr = g.getMetricsFromPod(g.client, podName, metav1.NamespaceSystem, ports.InsecureKubeControllerManagerPort)
			return lastMetricsFetchErr != nil, nil
		}); metricsWaitErr != nil {
			err = fmt.Errorf("error waiting for controller manager pod to be running: %v; %v", err, lastMetricsFetchErr)
			return
		}
	})
	if err != nil {
		return ControllerManagerMetrics{}, err
	}
```

**Comment by liggitt** [comment] 2020-03-12 23:44
still happening:
```
Mar 12 18:52:19.595: Error getting c-m metrics : error waiting for controller manager pod to be running: %!w(<nil>)
Unexpected error:
    <*errors.errorString | 0xc000fd4150>: {
        s: "error waiting for controller manager pod to be running: %!w(<nil>)",
    }
    error waiting for controller manager pod to be running: %!w(<nil>)
```

message logging missed using the correct errors, so the messages aren't helpful:
```diff
--- a/test/e2e/framework/metrics/metrics_grabber.go
+++ b/test/e2e/framework/metrics/metrics_grabber.go
@@ -170,7 +170,7 @@ func (g *Grabber) GrabFromControllerManager() (ControllerManagerMetrics, error)
        podName := fmt.Sprintf("%v-%v", "kube-controller-manager", g.masterName)
        g.waitForControllerManagerReadyOnce.Do(func() {
                if runningErr := e2epod.WaitForPodNameRunningInNamespace(g.client, podName, metav1.NamespaceSystem); runningErr != nil {
-                       err = fmt.Errorf("error waiting for controller manager pod to be running: %w", err)
+                       err = fmt.Errorf("error waiting for controller manager pod to be running: %w", runningErr)
                        return
                }

@@ -179,7 +179,7 @@ func (g *Grabber) GrabFromControllerManager() (ControllerManagerMetrics, error)
                        _, lastMetricsFetchErr = g.getMetricsFromPod(g.client, podName, metav1.NamespaceSystem, ports.InsecureKubeControllerManagerPort)
                        return lastMetricsFetchErr == nil, nil
                }); metricsWaitErr != nil {
-                       err = fmt.Errorf("error waiting for controller manager pod to expose metrics: %v; %v", err, lastMetricsFetchErr)
+                       err = fmt.Errorf("error waiting for controller manager pod to expose metrics: %v; %v", metricsWaitErr, lastMetricsFetchErr)
                        return
                }
        })
```

**Comment by aojea** [comment] 2020-03-13 08:16
@liggitt what's this stack trace in the apiserver? is this related?

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88893/pull-kubernetes-e2e-gce/1238171676051509250/artifacts/e2e-ccb8822d86-674b9-master/kube-apiserver.log

```
I0312 18:50:41.270902       1 httplog.go:90] verb="GET" URI="/apis/metrics.k8s.io/v1beta1?timeout=32s" latency=1.300633ms resp=503 UserAgent="kubectl/v1.19.0 (linux/amd64) kubernetes/95e6759" srcIP="[::1]:43516": 
goroutine 22751 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0078737a0, 0x1f7)
	staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:225 +0xc8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0078737a0, 0x1f7)
	staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc00a3c31a0, 0x1f7)
	staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:228 +0xb2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc002fc1900, 0x1f7)
	staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit.go:219 +0x63
net/http.Error(0x54f3fa0, 0xc012a2b2a8, 0x4730bc4, 0x13, 0x1f7)
	GOROOT/src/net/http/server.go:2019 +0x1f4
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.proxyError(0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600, 0x4730bc4, 0x13, 0x1f7)
	staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:97 +0x57
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc007eb3420, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:126 +0xc2b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc010687580, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x544
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00073e5b0, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x84
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x47213e2, 0xf, 0xc005413ef0, 0xc00073e5b0, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/server/handler.go:154 +0x6b1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc004ef8540, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	GOROOT/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x4de
net/http.HandlerFunc.ServeHTTP(0xc0062e3500, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	GOROOT/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc004ef8580, 0x54f3fa0, 0xc012a2b2a8, 0xc00a40c600)
	GOROOT/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7f984bd99158, 0xc012a2b2a0, 0xc00a40c500)
	staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit.go:110 +0x4b9
net/http.HandlerFunc.ServeHTTP(0xc004ef85c0, 0x7f984bd99158, 0xc012a2b2a0, 0xc00a40c500)
	GOROOT/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f984bd99158, 0xc012a2b2a0, 0xc00a40c300)
	staging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ce
net/http.HandlerFunc.ServeHTTP(0xc003038c80, 0x7f984bd99158, 0xc012a2b2a0, 0xc00a40c300)
	GOROOT/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc014085980, 0xc002006680, 0x55046e0, 0xc012a2b2a0, 0xc00a40c300)
	staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb

logging error output: "service unavailable\n"
```

**Comment by aojea** [comment] 2020-03-14 10:50
again 👀 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85564/pull-kubernetes-e2e-gce/1238630773502775296

```
ï¿½[1mSTEPï¿½[0m: Creating a kubernetes client
Mar 14 01:17:14.922: INFO: >>> kubeConfig: /workspace/.kube/config
ï¿½[1mSTEPï¿½[0m: Building a namespace api object, basename provisioning
Mar 14 01:17:15.245: INFO: Found PodSecurityPolicies; assuming PodSecurityPolicy is enabled.
Mar 14 01:17:15.477: INFO: Found ClusterRoles; assuming RBAC is enabled.
ï¿½[1mSTEPï¿½[0m: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in provisioning-8245
ï¿½[1mSTEPï¿½[0m: Waiting for a default service account to be provisioned in namespace
[It] should be able to unmount after the subpath directory is deleted
  test/e2e/storage/testsuites/subpath.go:439
Mar 14 01:17:15.986: INFO: Could not find CSI Name for in-tree plugin kubernetes.io/local-volume
Mar 14 01:17:16.166: FAIL: Error getting c-m metrics : error waiting for controller manager pod to be running: pods "kube-controller-manager-e2e-1a7f46e1b2-674b9-master" not found
Unexpected error:
```

it seems is not really waiting because it fails just 200 ms after the INFO msg

**Comment by aojea** [comment] 2020-03-14 11:21
It turns out that the method used to wait for the controller manager pod fails if the pod doesn't exist

https://github.com/kubernetes/kubernetes/blob/b290e0b7ab292bd5694e2a95e234ac2d43d3a5c0/test/e2e/framework/pod/resource.go#L148-L153

**Comment by liggitt** [comment] 2020-03-14 12:31
Ah, so first we should wait for the pod to exist, then be ready, then return metrics

**Comment by aojea** [comment] 2020-03-16 17:47
This start to look promising
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics&job=pull-kubernetes-e2e-gce%24&test=sig-storage

**Comment by liggitt** [comment] 2020-03-16 17:53
yes, looks good. thanks for all the work

/close

**Closed by liggitt** 2020-03-16 17:53 UTC
Labels: kind/flake, priority/critical-urgent, priority/important-soon, sig/storage

**Comment by spiffxp** [comment] 2020-03-16 23:00
Fixed by https://github.com/kubernetes/kubernetes/pull/89123
