### ISSUE TITLE
Losing deployment history when replicasets are re-used

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#33844] opened 2016-09-30 16:43 UTC
In 1.4.x

1. Create a deployment, wait for RS-1 to be created
2. Add an environment variable to a container in the pod spec of the Deployment, wait for RS-2 to be created
3. run kubectl rollout history for the deployment, you will see 1 and 2 in the list
4. Remove the environment variable added in step 2
5. run kubectl rollout history

Expected: In step 5 I would ideally like to see 1, 2, 3 in the list and a note on 3 that it was originally number 1.

Actual: number 1 is completely gone from the list, it is no longer in the history.  As a user this would scare me, it looks like loss of data.

**Comment by jwforres** [comment] 2016-09-30 16:43
cc @mfojtik @pmorie

**Comment by pmorie** [comment] 2016-09-30 16:44
This seems very much like a bug to me.  There should be a way to retain the old information without losing it.

**Comment by jwforres** [comment] 2016-09-30 16:47
Yeah any UI trying to display the full history of the deployment is missing the data to do that.

**Comment by jwforres** [comment] 2016-09-30 16:53
cc @spadgett

**Comment by pmorie** [comment] 2016-09-30 16:54
@kubernetes/sig-apps

**Comment by AdoHe** [comment] 2016-09-30 17:10
@jwforres 
```
Remove the environment variable added in step 2
```
how you do this?

**Comment by krmayankk** [comment] 2016-09-30 17:11
Hmm this sounds sure like something hat should be fixed but I am sure this is not a regression and this is the behavior in previous releases as well simply because we use the same rs

**Comment by jwforres** [comment] 2016-09-30 17:35
On Fri, Sep 30, 2016 at 1:11 PM, TonyAdo <notifications@github.com> wrote:

> @jwforres <https://github.com/jwforres>
>
> Remove the environment variable added in step 2
>
> how you do this?
>
In my case the same way I added it in the first place.  We found this
building out the openshift UI around Deployments, we already had
Environment editors for RCs, RSs, basically anything with a pod template
spec.  For kube you should at least be able to reproduce it using kubectl
edit.

**Comment by kargakis** [comment] 2016-10-02 21:38
This is not a bug but it's working as intended. A Kubernetes Deployment adopts a replica set foo if it finds out that its pod template already exist in foo. Personally I regard this behavior as an improvement over the downstream behavior of DeploymentConfigs (rollbacks for DCs are broken in the face of exceeded RC quota). Not sure if and how do we want to fix `rollout history`, losing history has been a known trade-off we seem to be willing to take.

cc: @kubernetes/deployment

**Comment by jwforres** [comment] 2016-10-02 21:56
Yeah the issue here is only about the loss of history.  You could keep
previous revisions that a replica set was used for as a second
field/annotation.

**Comment by kargakis** [comment] 2016-10-02 22:00
Keep a track of all the revisions that a replica set has served is not unreasonable.

**Closed** 2016-10-08 08:32 UTC
Labels: area/deployment, component/deployment, team/ux
