### ISSUE TITLE
staging/src/k8s.io/apiserver/pkg/server/filters Data race

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#101097] opened 2021-04-14 08:51 UTC
#### What happened:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101093/pull-kubernetes-unit/1382237738274656256

``` log
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters: TestErrConnKilledHTTP2 expand_less	0s
=== RUN   TestErrConnKilledHTTP2
==================
WARNING: DATA RACE
Write at 0x00000352f1a8 by goroutine 216:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.captureStdErr.func2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout_test.go:220 +0x5a
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestErrConnKilledHTTP2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout_test.go:367 +0xe3f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1194 +0x202

Previous read at 0x00000352f1a8 by goroutine 60:
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:919 +0xa64
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x28c
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.ErrorDepth()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1451 +0x12d
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logError()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:114 +0x2f
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleError()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:108 +0xa1
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func2.1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:126 +0x125


```

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tallclair** [comment] 2022-04-01 20:41
Duplicate of (already fixed) https://github.com/kubernetes/kubernetes/issues/108043

**Closed by tallclair** 2022-04-01 20:41 UTC
Labels: kind/bug, area/test, sig/api-machinery, triage/accepted
