### ISSUE TITLE
Is it necessary for the kube-apiserver to periodically list services?

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#129069] opened 2024-12-03 11:59 UTC
### What happened?

Is it necessary for the kube-apiserver to periodically list services?
https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/registry/core/service/ipallocator/controller/repair.go#L125-L131
https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/registry/core/service/ipallocator/controller/repair.go#L211

### What did you expect to happen?

The kube-apiserver does not periodically list services.

### How can we reproduce it (as minimally and precisely as possible)?

Currently, metrics statistics show that the kube-apiserver frequently performs list services operations.

### Kubernetes version

<details>

```console
$ kubectl version
# 1.31.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment] 2024-12-03 20:00
If you trace https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/registry/core/service/ipallocator/controller/repair.go#L126

Basically yes, it repairs invalid / corrupted state with allocating IPs to the services.

**Comment by aojea** [comment] 2024-12-03 21:37
That will be solves once KEP-1880 moves to GA , since it uses an informer instaed of listing directly from the API

https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/registry/core/rest/storage_core.go#L128-L147

**Comment by aojea** [comment] 2024-12-04 13:34
I think we can close this, I'm trying to GA KEP-1880 in 1.33 that will remove this problem, but as today is working as intended

/close

**Closed by aojea** 2024-12-04 13:34 UTC
Labels: kind/bug, needs-sig, needs-triage
