### ISSUE TITLE
Refactor select e2e tests and incorporate them into automated upgrade testing

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#35078] opened 2016-10-19 00:00 UTC
We have a super handy framework called ["chaosmonkey"](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/chaosmonkey/chaosmonkey.go) (curiously named despite it having relatively little in common with [Netflix Chaosmonkey](http://techblog.netflix.com/2012/07/chaos-monkey-released-into-wild.html), other than ours modelling upgrades as disruptions).

And we already have a few tests that use that framework to perform automated e2e upgrade tests.  For example we [test services](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_upgrade.go#L145) across cluster upgrades.

So I think that we should focus our effort on expanding the set of automated tests in that suite (as Wojtek, Marek and others have suggested in the past, on the basis that automating the tests actually involved effort comparable to running them manually once).  

For the most part that automation involves:
1.       refactoring the existing e2e tests into three parts (setup, validate, teardown), 
2.       so that we can run them as setup->validate->upgrade->validate->teardown).  
3.       There's more detail [here](https://github.com/kubernetes/kubernetes/issues/15131#issuecomment-145943453).  
4.       That refactoring appears to have already been done for services, at least in part.  
5.       It does not involve a whole lot of work per test. 
6.       We do not need to refactor all e2e tests to get very decent automated coverage.  I have done an analysis [here](https://docs.google.com/spreadsheets/d/1BBriwwyAtp4EzjE53lwyKXcvUNE808DozXiNEZfjtFI/edit#gid=1876580779&vpid=A1) of the tests that need to be refactored in order to reach parity with the manual upgrade testing that was done as part of the v1.4 release.
7.       As an example, Ingress relies on Services and ReplicaSets and Pods.  So an e2e upgrade test of Ingress covers all of those, so some significant extent.

Contact @quinton-hoole if you need further advice on how to proceed. 

cc: @kubernetes/sig-testing @saad-ali @davidopp @matchstick FYI.

@shashidharatd has been tentatively volunteered to do some of this work, although other volunteers would be most welcome.  The work involves refactoring about 12 e2e tests, and is highly parallelizable.

**Comment by quinton-hoole** [comment] 2016-10-27 11:35
Any progress on this yet @shashidharatd ?

**Comment by shashidharatd** [comment] 2016-10-27 11:43
@quinton-hoole, I wasn't able to focus on this task for past few days. Will work on it in next 2 days and update

**Comment by shashidharatd** [comment] 2016-10-27 15:35
I wasn't able to focus on this task for past few days. Will work on it in
next 2 days and update

**Comment by quinton-hoole** [comment] 2016-10-31 21:10
See coverage analysis in https://docs.google.com/spreadsheets/d/1BBriwwyAtp4EzjE53lwyKXcvUNE808DozXiNEZfjtFI/edit#gid=1876580779&vpid=A1

See ~50% coverage in #35697

**Comment by dims** [comment] 2016-11-17 12:47
@quinton-hoole This needs to be triaged as a release-blocker or not for 1.5

**Comment by dims** [comment] 2016-11-18 12:58
@matchstick all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment] 2016-11-19 19:30
Not a release blocker for v1.5.

**Comment by quinton-hoole** [comment] 2016-12-23 00:55
Any progress @shashidharatd ?

**Comment by shashidharatd** [comment] 2016-12-23 13:58
The commits in #35697 were reverted due to a bug which caused the automated upgrade tests in CI to fail. I did find the cause and fixed it. but would like to run the upgrade tests in my local setup before pushing out the changes. somehow setting up the upgrade test environment outside GCE felt daunting and i didn't put much effort in this task of late. I would test the upgrade testcases on GCE itself from v1.4 to v1.5 and update asap.

**Comment by ethernetdan** [comment] 2017-03-13 22:41
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by quinton-hoole** [comment] 2017-03-14 04:23
I believe this issue has been resolved. @krousey @irfanurrehman

**Comment by irfanurrehman** [comment] 2017-03-14 06:04
@shashidharatd worked on this.. :)

**Comment by marun** [comment] 2017-06-12 20:43
Assuming this should not be blocking 1.7.

**Comment by krousey** [comment] 2017-09-05 20:29
This issue was solved for the 1.7 release.

**Closed by krousey** 2017-09-05 20:29 UTC
Labels: area/test-infra, help-wanted, milestone-labels-incomplete, sig/federation
