### ISSUE TITLE
AccessDenied when running cluster/addons/fluentd-elasticsearch/es-controller.yaml

### ISSUE THREAD

**Issue by xcompass** [kubernetes/kubernetes#37030] opened 2016-11-17 21:28 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): elasticsearch

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.6_coreos.0

**Environment**:
- **Cloud provider or hardware configuration**: on premise, vCloud
- **OS** (e.g. from /etc/os-release): CoreOS alpha (1221.0.0)
- **Kernel** (e.g. `uname -a`): Linux f1 4.8.6-coreos #1 SMP Thu Nov 3 04:43:35 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux
- **Install tools**: None. Default installation
- **Others**:

**What happened**:
When I tried to install es-controller.yaml, The containers are created successfully and but terminated with the following error:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.data' (/data/kubernetes-logging)
Likely root cause: java.nio.file.AccessDeniedException: /data/kubernetes-logging
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:259)
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
        at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
        at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:212)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:183)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**What you expected to happen**:
The container runs successfully.

**How to reproduce it** (as minimally and precisely as possible):
in a running kube cluster, run
```
kubectl create -f cluster/addons/fluentd-elasticsearch/es-controller.yaml
```
The pod will restart itself because of the error. The error message is in the container log.

**Anything else do we need to know**:
It seems that when container mount the volume /data, it mounted as root:root (755). However, elasticsearch is running under user elasticsearch. So it couldn't write the files under /data. 
After I run `chown elasticsearch:elasticsearch /data`, the container runs fine.

/cc @Crassirostris

**Comment by Crassirostris** [comment] 2016-11-18 00:08
Thanks for the report!

It works in our tests both with the container-vm and GCI, so I assume the difference lies with the coreos.

From the first glance, it's not how it's supposed to be and should be fixed. Most probably will make a PR & will rebuild an image tomorrow.

**Comment by xcompass** [comment] 2016-11-18 00:13
Thanks.

**Comment by Crassirostris** [comment] 2016-11-18 11:10
@xcompass Actually, [turns out there is `chown` in the Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-image/Dockerfile#L47)

Problem is it's executed before the volume is mounted, which works for some reason on GCI and container-vm. Will follow-up with a PR

**Comment by Crassirostris** [comment] 2016-11-18 11:16
Related discussion in docker repo: https://github.com/docker/docker/issues/2259

**Comment by piosz** [comment] 2016-11-18 16:17
FYI @yifan-gu

**Comment by Crassirostris** [comment] 2016-11-18 16:34
@xcompass As far as I understand from https://github.com/docker/docker/issues/28041 everything should work

Could you please also attach docker version, run the following command manually on the node and copy the output?

```
export ES_IMAGE_ID=`docker run -d -e "MINIMUM_MASTER_NODES=1" gcr.io/google_containers/elasticsearch:v2.4.1`
export ES_IMAGE_IP=`docker inspect --format '{{.NetworkSettings.IPAddress}}' $ES_IMAGE_ID`
curl -XPUT http://${ES_IMAGE_IP}:9200/test/test/1 -d '{}' >> /dev/null
docker logs $ES_IMAGE_ID
```

**Comment by xcompass** [comment] 2016-11-18 23:38
Here you go:
```
compass@f2 ~ $ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64
```
```
compass@f2 ~ $ docker logs $ES_IMAGE_ID
F1118 23:36:27.427306       9 elasticsearch_logging_discovery.go:47] Failed to make client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x1ba4d00, 0xc400000000, 0xc9, 0x18d)
        src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x1b84d20, 0xc400000003, 0xc420088d80, 0x1b21890, 0x22, 0x2f, 0x0)
        src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x1b84d20, 0xc400000003, 0x141c843, 0x19, 0xc4206bbe58, 0x1, 0x1)
        src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x141c843, 0x19, 0xc4206bbe58, 0x1, 0x1)
        src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        src/k8s.io/kubernetes/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go:47 +0xc0a
[2016-11-18 23:36:27,978][INFO ][node                     ] [Dragon Lord] version[2.4.1], pid[17], build[c67dc32/2016-09-27T18:57:55Z]
[2016-11-18 23:36:27,978][INFO ][node                     ] [Dragon Lord] initializing ...
[2016-11-18 23:36:28,404][INFO ][plugins                  ] [Dragon Lord] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2016-11-18 23:36:28,423][INFO ][env                      ] [Dragon Lord] using [1] data paths, mounts [[/data (/dev/sda9)]], net usable_space [110.8gb], net total_space [121.7gb], spins? [possibly], types [ext4]
[2016-11-18 23:36:28,423][INFO ][env                      ] [Dragon Lord] heap size [990.7mb], compressed ordinary object pointers [true]
[2016-11-18 23:36:29,645][INFO ][node                     ] [Dragon Lord] initialized
[2016-11-18 23:36:29,645][INFO ][node                     ] [Dragon Lord] starting ...
[2016-11-18 23:36:29,693][INFO ][transport                ] [Dragon Lord] publish_address {10.2.31.8:9300}, bound_addresses {[::]:9300}
[2016-11-18 23:36:29,697][INFO ][discovery                ] [Dragon Lord] kubernetes-logging/GMi6E4o-SHCvwwhamqQ-qw
[2016-11-18 23:36:32,719][INFO ][cluster.service          ] [Dragon Lord] new_master {Dragon Lord}{GMi6E4o-SHCvwwhamqQ-qw}{10.2.31.8}{10.2.31.8:9300}{master=true}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-11-18 23:36:32,737][INFO ][http                     ] [Dragon Lord] publish_address {10.2.31.8:9200}, bound_addresses {[::]:9200}
[2016-11-18 23:36:32,737][INFO ][node                     ] [Dragon Lord] started
[2016-11-18 23:36:32,759][INFO ][gateway                  ] [Dragon Lord] recovered [0] indices into cluster_state
[2016-11-18 23:36:38,681][INFO ][cluster.metadata         ] [Dragon Lord] [test] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings []
[2016-11-18 23:36:39,001][INFO ][cluster.routing.allocation] [Dragon Lord] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[test][4]] ...]).
[2016-11-18 23:36:39,050][INFO ][cluster.metadata         ] [Dragon Lord] [test] create_mapping [test]
```

**Comment by xcompass** [comment] 2016-11-19 00:06
@Crassirostris I did some more digging. Here is what I found:

* When running directly with docker, the data directory is set to correct user elasticsearch:elasticsearch. 

* When running in kube with emptyDir: {} for /data volume, the data directory has root:root, but permission on the directory is 775. So elasticsearch is able to create the sub dir. 

* When running in kube with hostPath for /data volume, the data directory has root:root and permission is 755. So elasticsearch won't be able to create sub dir and I got the access denied message. The same if I use a persistent volume (Ceph in my case).

Not sure if it is a bug in kube or docker?

**Comment by Crassirostris** [comment] 2016-11-21 09:59
@xcompass Could you please try to use crassirostris/elasticsearch:v2.4.1 to see if it's fixed? Because I cannot reproduce it :)

**Comment by Crassirostris** [comment] 2016-11-22 11:54
@xcompass Did you have a chance to test an image I built?

**Comment by xcompass** [comment] 2016-11-22 19:59
@Crassirostris sorry for the delay. Just got a chance to test it. It works. I used the hostPath option and the directory was created and ownership is correct.

**Comment by Crassirostris** [comment] 2016-11-22 20:10
Great, thanks!

**Closed** 2016-11-22 20:41 UTC
Labels: area/logging, area/os/coreos, priority/P2

**Comment by dobesv** [comment] 2018-02-15 07:07
I'm having this exact problem but I don't understand the solution.  What did you do to fix it?

**Comment by dobesv** [comment] 2018-02-15 07:12
I think I found a workaround that doesn't require building my own image, I just use an initContainer to set ownership of the folder, e.g.:
```
...
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command: ["sysctl", "-w", "vm.max_map_count=262144" ]
        securityContext:
          privileged: true
      - name: chown
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        command: ["chown", "-v", "elasticsearch:elasticsearch", "/data" ]
        volumeMounts:
        - name: storage
          mountPath: /data
      containers:
      - name: es-data
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
...
```
