### ISSUE TITLE
RethinkDB Heartbeat timeouts

### ISSUE THREAD

**Issue by mcadam** [kubernetes/kubernetes#11688] opened 2015-07-22 11:59 UTC
Hello,

I am having problems with the RethinkDB example, I started a cluster of 3 nodes and after a little period of time, I am having Heartbeat timeout errors. I did not have those outside kubernetes, so I am kind of wondering what could go wrong here ?
Every 5 minutes or so I have these timeouts.

Some logs:

error: Heartbeat timeout, killing connection to peer (unknown)
error: Heartbeat timeout, killing connection to peer (unknown)
error: Heartbeat timeout, killing connection to peer (unknown)
Connected to server "rethinkdb_rc_1_16_0_txpil_6zf" f2b29fff-b46f-44b8-94c2-aceff8de928d
Connected to server "rethinkdb_admin_1_16_0_xg0" 7d5778f1-2931-4bfa-aec9-e4786660d83f
Connected to server "rethinkdb_rc_1_16_0_y5s6y_hiv" d77d3eea-02e8-4751-9816-0d40befe23d9
Connected to server "rethinkdb_admin_1_16_0_xg0" 7d5778f1-2931-4bfa-aec9-e4786660d83f

Anyone having those problems ?

Tried on a kubernetes cluster v0.21.1 and on 1.0.1 (AWS Provider), same problem. Even tried new version of RethinkDB 2.0.4, still having the errors. It is not usable as is in production as every time the connection timeouts, the connection is lost and the tables become unavailable until the server is connected again...

Thanks.

If you need more information just ask me, I really need to get rid of this problem as I would like to run my rethinkdb cluster in production IN the kubernetes cluster.

**Comment by vishh** [comment] 2015-07-22 17:01
cc @antmanler 
@mcadam: Are you able to run any other workload successfully?

**Comment by mcadam** [comment] 2015-07-22 18:53
I also run a redis cluster which seems to run fine, i will check the logs tomorrow and see if there are any problems regarding networking timeouts or stuff like that.


--

Cordialement,

Adam Guldemann

**Comment by mcadam** [comment] 2015-07-28 09:58
I have no problem of networking between the redis nodes. I could not find anything related to Rethinkdb except that the docker image is officially supported on Docker version 1.7.1.
They say that support for older versions (down to 1.0) is provided on a best-effort basis.

Maybe the problem comes from here, I will try to do some tests with docker 1.7.1, any news on Kubernetes shipping with the last version of docker (1.7.1) ?

**Comment by mcadam** [comment] 2015-07-31 05:28
Actually I hame also some problems with my redis cluster....


July 31st 2015, 06:04:40.000	[51] 31 Jul 02:04:40.528 # MASTER timeout: no data nor PING received...
July 31st 2015, 06:04:40.000	[51] 31 Jul 02:04:40.528 * MASTER <-> SLAVE sync started
July 31st 2015, 06:04:40.000	[51] 31 Jul 02:04:40.528 * Connecting to MASTER 10.244.1.10:6379
July 31st 2015, 06:04:40.000	[51] 31 Jul 02:04:40.528 * Caching the disconnected master state.
July 31st 2015, 06:04:40.000	[15] 31 Jul 02:04:40.530 # Connection with slave 10.244.3.8:6379 lost.
July 31st 2015, 06:04:40.000	[51] 31 Jul 02:04:40.528 # Connection with master lost.
July 31st 2015, 04:46:40.000	172.20.0.4 - - [31/Jul/2015:00:46:40 +0000] "GET / HTTP/1.1" 200 1351 "-" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.04 (lucid) Firefox/3.6.13"
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.942 * MASTER <-> SLAVE sync started
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.943 * Successful partial resynchronization with master.
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.942 * Connecting to MASTER 10.244.1.10:6379
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.943 * Trying a partial resynchronization (request 77e23e5cc247ff06146dc687b5a90668b1fd75ed:27305972).
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.943 * Master replied to PING, replication can continue...
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.942 * Non blocking connect for SYNC fired the event.
July 31st 2015, 04:23:40.000	[51] 31 Jul 00:23:40.943 * MASTER <-> SLAVE sync: Master accepted a Partial Resynchronization.
July 31st 2015, 04:00:05.000	[2015-07-31 00:00:05,741][INFO ][cluster.metadata ] [Radius] [logstash-2015.07.31] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings [fluentd]
July 31st 2015, 04:00:05.000	[2015-07-31 00:00:05,909][INFO ][cluster.metadata ] [Radius] [logstash-2015.07.31] update_mapping [fluentd] (dynamic)
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.612 * Successful partial resynchronization with master.
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.610 * Non blocking connect for SYNC fired the event.
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.611 * Master replied to PING, replication can continue...
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.612 * MASTER <-> SLAVE sync: Master accepted a Partial Resynchronization.
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.610 * Connecting to MASTER 10.244.1.10:6379
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.610 * MASTER <-> SLAVE sync started
July 31st 2015, 01:54:35.000	[51] 30 Jul 21:54:35.611 * Trying a partial resynchronization (request 77e23e5cc247ff06146dc687b5a90668b1fd75ed:25583689).
July 31st 2015, 01:54:34.000	[51] 30 Jul 21:54:34.754 # Connection with master lost.
July 31st 2015, 01:54:34.000	[51] 30 Jul 21:54:34.754 * Caching the disconnected master state.
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.816 * MASTER <-> SLAVE sync started
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.818 * MASTER <-> SLAVE sync: Master accepted a Partial Resynchronization.
July 31st 2015, 00:06:02.000	[15] 30 Jul 20:06:02.819 * Slave 10.244.3.8:6379 asks for synchronization
July 31st 2015, 00:06:02.000	[15] 30 Jul 20:06:02.819 * Partial resynchronization request from 10.244.3.8:6379 accepted. Sending 7321 bytes of backlog starting from offset 24354134.
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.816 # MASTER timeout: no data nor PING received...
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.816 * Non blocking connect for SYNC fired the event.
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.816 # Connection with master lost.
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.817 * Master replied to PING, replication can continue...
July 31st 2015, 00:06:02.000	[51] 30 Jul 20:06:02.816 * Caching the disconnected master state.

**Comment by mcadam** [comment] 2015-07-31 05:29
It seems sometimes you can't ping other containers, so a lot of stuff that rely on that are going to have issues.

**Comment by mcadam** [comment] 2015-07-31 05:39
Here are a ping request from one container to another for like 5 minutes: 

....
64 bytes from 10.244.1.10: icmp_seq=962 ttl=62 time=0.693 ms
64 bytes from 10.244.1.10: icmp_seq=963 ttl=62 time=0.670 ms
64 bytes from 10.244.1.10: icmp_seq=964 ttl=62 time=0.636 ms
64 bytes from 10.244.1.10: icmp_seq=965 ttl=62 time=0.732 ms
64 bytes from 10.244.1.10: icmp_seq=966 ttl=62 time=0.590 ms
64 bytes from 10.244.1.10: icmp_seq=967 ttl=62 time=0.533 ms
64 bytes from 10.244.1.10: icmp_seq=968 ttl=62 time=0.544 ms
64 bytes from 10.244.1.10: icmp_seq=969 ttl=62 time=0.605 ms
64 bytes from 10.244.1.10: icmp_seq=970 ttl=62 time=0.636 ms
64 bytes from 10.244.1.10: icmp_seq=971 ttl=62 time=0.603 ms
64 bytes from 10.244.1.10: icmp_seq=972 ttl=62 time=0.548 ms
64 bytes from 10.244.1.10: icmp_seq=973 ttl=62 time=0.632 ms
64 bytes from 10.244.1.10: icmp_seq=974 ttl=62 time=0.596 ms
64 bytes from 10.244.1.10: icmp_seq=975 ttl=62 time=0.436 ms
64 bytes from 10.244.1.10: icmp_seq=976 ttl=62 time=0.516 ms
64 bytes from 10.244.1.10: icmp_seq=977 ttl=62 time=0.660 ms
64 bytes from 10.244.1.10: icmp_seq=978 ttl=62 time=0.532 ms
64 bytes from 10.244.1.10: icmp_seq=979 ttl=62 time=0.544 ms
64 bytes from 10.244.1.10: icmp_seq=980 ttl=62 time=0.588 ms
64 bytes from 10.244.1.10: icmp_seq=981 ttl=62 time=0.553 ms
64 bytes from 10.244.1.10: icmp_seq=982 ttl=62 time=0.604 ms
64 bytes from 10.244.1.10: icmp_seq=983 ttl=62 time=0.380 ms
64 bytes from 10.244.1.10: icmp_seq=984 ttl=62 time=0.531 ms
64 bytes from 10.244.1.10: icmp_seq=985 ttl=62 time=0.569 ms
64 bytes from 10.244.1.10: icmp_seq=986 ttl=62 time=0.606 ms
^C--- 10.244.1.10 ping statistics ---
987 packets transmitted, 802 packets received, 18% packet loss
round-trip min/avg/max/stddev = 0.323/0.547/4.269/0.165 ms


I see 18% packet loss, any ideas where that could come from ?

**Comment by mcadam** [comment] 2015-07-31 05:53
If I ping google from the same container 0% packet loss to compare:

64 bytes from 8.8.8.8: icmp_seq=193 ttl=54 time=0.988 ms
64 bytes from 8.8.8.8: icmp_seq=194 ttl=54 time=1.014 ms
64 bytes from 8.8.8.8: icmp_seq=195 ttl=54 time=0.952 ms
64 bytes from 8.8.8.8: icmp_seq=196 ttl=54 time=1.069 ms
64 bytes from 8.8.8.8: icmp_seq=197 ttl=54 time=1.038 ms
64 bytes from 8.8.8.8: icmp_seq=198 ttl=54 time=1.094 ms
64 bytes from 8.8.8.8: icmp_seq=199 ttl=54 time=1.083 ms
64 bytes from 8.8.8.8: icmp_seq=200 ttl=54 time=1.005 ms
64 bytes from 8.8.8.8: icmp_seq=201 ttl=54 time=1.042 ms
64 bytes from 8.8.8.8: icmp_seq=202 ttl=54 time=1.014 ms
^C--- 8.8.8.8 ping statistics ---
203 packets transmitted, 203 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.887/1.027/1.166/0.055 ms

**Comment by thockin** [comment] 2015-07-31 05:54
@justinsb because AWS

This might make a good e2e test - bring up a bunch of pods and ping each other as fast as they can for 30 seconds and look for packet-loss.

@ArtfulCoder @a-robinson @bprashanth

**Comment by mcadam** [comment] 2015-07-31 06:55
So I understand that Kubernetes in only supposed to work correctly on GCE? Isnt it supposed to be production ready for all platforms as of version 1.0?

**Comment by justinsb** [comment] 2015-07-31 14:40
It is supposed to be production ready on AWS.  If it is not, it is my fault, and I/we will fix it :-)  I do think it is fair to say that GCE / GKE have a lot more resources on them, so will be more stable earlier.

Thank you @mcadam for the repro case; I will try to reproduce.  I wonder if this might be the same bug as #11979; if we were breaking the node routes every 5 minutes (maybe that is when AWS refills the quota) then I can well imagine exactly the behaviour you are seeing.

#11979 is also my fault; I was trying to make the node name be the instance id, but had to revert it very late in the release because it broke `kubectl logs` & `kubectl exec`.  And it looks like I missed reverting the change in the route logic there.  I apologize, and we're working on it (thanks @iterion!)

**Comment by justinsb** [comment] 2015-07-31 14:42
Will it cause anyone any problems if I P1 or P0 this?  I think it is really bad, but it only affects AWS, so we don't have to start e.g. paging Googlers or whatever happens when we have a P0.

**Comment by iterion** [comment] 2015-07-31 14:53
@justinsb I *believe* this is all related to the routes issue #12029. I was seeing the same thing on my Redis cluster. I assumed it was an issue with configuration for the cluster, so I investigated all of the normal possible causes. I couldn't find anything wrong and Redis seemed to be fine. After I got the email from AWS about hitting my limits it clicked that these DeleteRoute, CreateRoute loops could be causing the network timeouts and outright failures.

I deployed my fix to my cluster yesterday and saw the number of issues drop to zero. I'm not running RethinkDB but it definitely seems like it could be the same issue.

**Comment by thockin** [comment] 2015-08-01 06:33
On Thu, Jul 30, 2015 at 11:55 PM, Adam Guldemann
<notifications@github.com> wrote:
>
> So I understand that Kubernetes in only supposed to work correctly on GCE? Isnt it supposed to be production ready for all platforms as of version 1.0?

Nobody said that.  It's known to work on AWS, but like any complicated
systems-integration project, there is a combinatoric problem of all
the params and configs in each system - obviously we can't have tested
them all.  Justin does a fantastic job of making AWS work at all, and
we're very thankful for his help, which I might add is DONATED to our
effort.

Please give us the benefit of the doubt - we don't generally ship
obviously broken software.  If it's not working correctly, it's
probably "just" a bug.

**Comment by thockin** [comment] 2015-08-01 06:34
Go ahead and P0 it, and we can track it for a point release.

**Comment by justinsb** [comment] 2015-08-02 14:09
I did some experiments (on AWS):

Just naively pinging across two containers, I was able to observe about 5% packet loss over 3 minutes.  It sounds like the behaviour here was even worse, but I think it may have been compounded by hitting AWS rate limits.  This was with a version just before #12029 merged.

I then tried with a version that incorporated #12029 and ran it overnight; 0% loss:

```
26136 packets transmitted, 26136 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.236/1.295/1177.930/11.609 ms
```

There is still more jitter than I would like, but my current working assumption is that this is AWS networking.  I'm not running on dedicated instances, and I'm running with a 1 gig interconnect (vs the apparently-more-consistent 10 gig connections)

So thank you to @mcadam for providing a very reproducible test-case, and to @iterion for the fix.  This should fix the issue with rethink as well, but I guess I should verify that directly.  I'm also thinking about how to create an e2e test here.

(And thanks also to @thockin for the kind words of support about AWS - I do try, but I definitely did mess up here!)

**Comment by mcadam** [comment] 2015-08-03 05:03
Sorry about my last comment, it was kind of harsh regarding you guys working on makint it work everywhere. I do appreciate the hardwork, it was kind of a bad day with a lot of stuff going wrong (not your fault), I apologize if it was understood like I was complaining. Lots of pressure right now, new product comming out soon, heat from everywhere :)

It seems @justinsb you got it working ? How could I install the fix on my cluster to make some tests also ? If it is not possible I guess I will try a CoreOS based solution for now as I tried on a friend cluster with Kubernetes and CoreOS and he didn't have those pings problem between containers (flannel network). Maybe the coreos stack on AWS will work as well as his on OVH.

**Comment by mcadam** [comment] 2015-08-05 09:16
Where could I retrieve a version of Kubernetes including  that fix? Do you have some builds I could replace on my current cluster ?

**Comment by mbforbes** [comment] 2015-08-17 04:30
@brendandburns @zmerlynn would it be policy-compatible to cherry pick #12029 into a patch release?

**Comment by zmerlynn** [comment] 2015-08-17 15:57
@mbforbes: Seems like it.

**Comment by mbforbes** [comment] 2015-08-17 18:11
@zmerlynn ack, thanks. Who should do this? @mcadam are you willing?

**Comment by mbforbes** [comment] 2015-08-17 18:11
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

**Comment by mcadam** [comment] 2015-08-18 07:54
@mbforbes I never did a cherry pick i would prefer it to be somebody else :)

**Comment by brendandburns** [comment] 2015-10-21 03:51
Closing this as it was cherry-picker into 1.0.4

**Closed by brendandburns** 2015-10-21 03:51 UTC
Labels: area/platform/aws, priority/P0, team/cluster
