### ISSUE TITLE
error:couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: no route to host

### ISSUE THREAD

**Issue by rupsee** [kubernetes/kubernetes#12285] opened 2015-08-05 17:10 UTC
I follwed the Getting Started guide from http://kubernetes.io/v1.0/docs/getting-started-guides/vagrant.html
and tried deploying a vagrant based cluster on RHEL 7, first by building the source code and then when that didn't work, using the curl script. In both cases the cluster seems to be set up and I can do a vagrant ssh to the master and a minion, but running kubectl get pods or for that matter almost all kubectl commands return:

error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: no route to host

I read somewhere that this could happen if your config was faulty, so I tried kubectl.sh config info and this is what I get:
./cluster/kubectl.sh config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
  name: local
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.245.1.2
  name: vagrant
contexts:
- context:
    cluster: local
    user: ""
  name: local
- context:
    cluster: vagrant
    user: vagrant
  name: vagrant
current-context: vagrant
kind: Config
preferences: {}
users:
- name: vagrant
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: vagrant
    username: vagrant

I'd gotten this to work in a different machine successfully with v1beta3. Unfortunately I don't have access to that machine any more so don't know what the configuration had been set to.

Any help would be much appreciated.

Cheers
--Rupa

**Comment by rupsee** [comment] 2015-08-05 17:23
Looking at the config-default .sh file in the vagrant folder, I see that MASTER_IP and KUBE_MASTER_IP is set to 10.245.1.2. However pinging the IP address doesn't work. When I do a vagrant ssh master, and an ifconfig, the eth0 inet address is not 10.245.1.2. either.

**Comment by BenTheElder** [comment] 2015-08-05 20:17
I am having the same problem.
Running `go run hack/e2e.go -v -up` with `KUBERNETES_PROVIDER=vagrant` ends with:
`error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused`

**Comment by derekwaynecarr** [comment] 2015-08-05 20:32
There was a bug in the v1 release that caused network manager to control the eth1 device when it should not have been doing so.  

The fix for that was merged in HEAD a few weeks ago, and the cherry pick to go in the 1.0 release was made last night here: https://github.com/GoogleCloudPlatform/kubernetes/pull/12237

As for e2e, it had passed conformance tests, but I will see if I can reproduce the issue you are seeing now @BenTheElder to determine the cause if I can reproduce at HEAD.

**Comment by derekwaynecarr** [comment] 2015-08-05 20:47
@BenTheElder - I was able to reproduce your error just now.  There must have been some kind of regression in the last day.  I see the kubelet starts on the master, and docker is running, but doing a ```docker ps``` shows no attempt to start the api server container.  I will need to do some digging into what caused the regression in the last day.

**Comment by derekwaynecarr** [comment] 2015-08-05 20:56
@BenTheElder - think I found the offending PR that broke the setup here:
https://github.com/GoogleCloudPlatform/kubernetes/pull/11308

**Comment by BenTheElder** [comment] 2015-08-05 21:04
@derekwaynecarr thanks for checking this out, Is there anything I can do to help sort out the regression?

**Comment by derekwaynecarr** [comment] 2015-08-05 21:08
See fix above.

**Comment by rupsee** [comment] 2015-08-06 09:30
Once there's a fix, downloading the latest source from MASTER or using the curl script again should both work @BenTheElder ?

**Comment by derekwaynecarr** [comment] 2015-08-06 14:15
Latest source from MASTER should work fine.  Please confirm.

**Comment by BenTheElder** [comment] 2015-08-06 17:00
@derekwaynecarr @rupsee Confirmed that latest master is again working, sorry it took so long to get back to you.

**Comment by rupsee** [comment] 2015-08-06 17:44
I'll try it and post here tomorrow, it's  the end of my day here now. Thanks a bunch for the quick turnaround.

**Comment by rupsee** [comment] 2015-08-07 06:15
I still see a similar  issue with a somewhat different error message, "connection refused" instead of "no route to host".

Here's what I did:
 git clone https://github.com/GoogleCloudPlatform/kubernetes.git 
cd kubernetes
make quick-release
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh 

At the bottom of the master and minion updates I see this:

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Wrote config for vagrant to /root/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
......
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Then I tried:

[root@rtpclmperf52 kubernetes]# ./cluster/kubectl.sh get nodes
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused

**Comment by rupsee** [comment] 2015-08-07 06:24
here's part of what I get from ifconfig from the master:
--------------------------------------------------------------------------------------------------------
cbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
 inet 10.246.0.1  netmask 255.255.255.0  broadcast 10.246.0.255
---------------------------------------------------------------------------------------------------------
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
  inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
---------------------------------------------------------------------------------------------------------
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.245.1.2  netmask 255.255.255.0  broadcast 10.245.1.255

**Comment by rupsee** [comment] 2015-08-07 06:31
Here's what "kubectl.sh config view" returns:

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
  name: local
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.245.1.2
  name: vagrant
contexts:
- context:
    cluster: local
    user: ""  
    name: local
- context:
    cluster: vagrant
    user: vagrant
  name: vagrant
current-context: vagrant
kind: Config
preferences: {}
users:
- name: vagrant
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: vagrant
    username: vagrant

**Comment by rupsee** [comment] 2015-08-07 06:40
And finally,I'm on a RHEL 7 box - don't know if that matters.
# lsb_release -i -r
Distributor ID:	RedHatEnterpriseServer
Release:	7.0

**Comment by derekwaynecarr** [comment] 2015-09-10 19:09
@rupsee - I am closing this issue since vagrant should be stable now on HEAD and in the release branches.  Your connection refused error is most likely not being connected to the vboxnet device on your host to your VM that Virtual Box launches.

To check, open Virtual Box and look at the Network Adapter setting for kubernetes-master.

You should see something like the following:

![screenshot from 2015-09-10 15 08 02](https://cloud.githubusercontent.com/assets/6233452/9798249/c23cb724-57cd-11e5-9129-a9b920e5b96f.png)

Make sure your host is connected to that adapter (in my case its vboxnet5)

The other alternative is to just ssh into the master box and use kubectl from there:

$ vagrant ssh master
$ kubectl get nodes

Either way should work well.

Reopen if you continue to have issues.

**Closed by derekwaynecarr** 2015-09-10 19:09 UTC
Labels: area/cluster-lifecycle, area/platform/vagrant, kind/documentation, kind/support, priority/P2, team/control-plane

**Comment by rupsee** [comment] 2015-09-11 01:13
Hi Derek, thanks for getting back. I should have closed this one ... It was
because I hadn't set the KUBERNETRS_MASTER environment variable. None of
the documentation talks about it though. I'd to figure it out from the
cluster scripts in the back folder.
Cheers
Rupa

**Comment by rupsee** [comment] 2015-09-11 01:14
I meant the hack folder, Swype seems to think it knows best!
