### ISSUE TITLE
Running pods fails with AUFS mount errors

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#10959] opened 2015-07-08 23:32 UTC
#10622 

Ocassionaly our e2e tests fail with something like the following

```
INFO: event for dns-test-a6805741-25ac-11e5-8fa6-42010af01555: {kubelet e2e-test-parallel-minion-4c2m} pulled: Successfully pulled image "gcr.io/google_containers/jessie-dnsutils"
INFO: event for dns-test-a6805741-25ac-11e5-8fa6-42010af01555: {kubelet e2e-test-parallel-minion-4c2m} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/b2a84be51ae21ce45bc2cf1ecb944be2b4345c25798af0249260874185622e64-init: invalid argument

INFO: event for dns-test-a6805741-25ac-11e5-8fa6-42010af01555: {kubelet e2e-test-parallel-minion-4c2m} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/6f337451bbaa63fade20e59c88f87a6851412e3b5fb9d9b5d1a6457d1bb4e9f5-init: invalid argument

... many many more then ...

• Failure [311.910 seconds]
DNS
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:310
  should provide DNS for services [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:308

  Expected error:
      <*errors.errorString | 0xc2080e49c0>: {
          s: "gave up waiting for pod 'dns-test-a6805741-25ac-11e5-8fa6-42010af01555' to be 'running' after 5m0s",
      }
      gave up waiting for pod 'dns-test-a6805741-25ac-11e5-8fa6-42010af01555' to be 'running' after 5m0s
  not to have occurred
```

23.251.154.44-22-kubelet.log reports the following

```
E0708 20:05:33.233502    3077 manager.go:1579] Error running pod "nginx_e2e-tests-kubectl-516xc" container "nginx": API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/66a568f6f6922b9ed2e978a31ea2ab77ddf4f65eae2291d0fe5a5a6c50eb875b-init: invalid argument
E0708 20:05:33.329154    3077 manager.go:1579] Error running pod "nginx_e2e-tests-kubectl-516xc" container "nginx": API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/c6257ab9f8ac34c01b68d6b0ad1712981bce6fe8afcd2afd1b3976b3a65bc5fa-init: invalid argument
E0708 20:05:35.510816    3077 manager.go:1579] Error running pod "dns-test-a6805741-25ac-11e5-8fa6-42010af01555_e2e-tests-dns-8q0vk" container "jessie-querier": API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/b2a84be51ae21ce45bc2cf1ecb944be2b4345c25798af0249260874185622e64-init: invalid argument
E0708 20:05:35.609901    3077 manager.go:1579] Error running pod "dns-test-a6805741-25ac-11e5-8fa6-42010af01555_e2e-tests-dns-8q0vk" container "jessie-querier": API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/6f337451bbaa63fade20e59c88f87a6851412e3b5fb9d9b5d1a6457d1bb4e9f5-init: invalid argument
```

Here's the logs from this particular run: https://console.developers.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/3046/

**Comment by krousey** [comment] 2015-07-08 23:33
cc @dchen1107 @roberthbailey @cjcullen

**Comment by krousey** [comment] 2015-07-08 23:51
Seems the message is generated here: https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L392 and boils down to a syscall.Mount call.

[syscall.Mount](https://golang.org/pkg/syscall/#Mount) calls [syscall.BytePtrFromString](https://golang.org/pkg/syscall/#BytePtrFromString) on `data`. From the docs:

> BytePtrFromString returns a pointer to a NUL-terminated array of bytes containing the text of s. If s contains a NUL byte at any location, it returns (nil, EINVAL).

Then syscall.Mount call mount. `man 2 mount`

>**ERRORS**
> >The error values given below result from filesystem type independent errors.  Each filesystem type may have its own special errors and its own special behavior.  See the Linux  kernel  source  code  for details.
> > ...
> >**EINVAL** source  had  an invalid superblock.  Or, a remount (MS_REMOUNT) was attempted, but source was not already mounted on target.  Or, a move (MS_MOVE) was attempted, but source was not a mount point, or was '/'.

They do use MsRemount here: https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L457 So maybe it could be a race condition. I don't really have any idea. It's probably more likely that this is an AUFS specific error.

**Comment by sroze** [comment] 2015-08-30 12:32
FYI, I'm experiencing this in "production" on Google Container Engine too.

**Comment by iameli** [comment] 2015-09-10 21:54
Also experiencing on a vanilla `kube-up` installation on AWS.

**Comment by quinton-hoole** [comment] 2015-09-15 23:18
Tentatively increased priority to P1, as we're receiving quite a few reports of this.  @dchen1107 feel free to disagree and demote if you so wish.

**Comment by dchen1107** [comment] 2015-09-15 23:37
Here is corresponding docker issue: https://github.com/docker/docker/issues/13742

I used to wish docker could fix such issue in its 1.8.X release, but looks like no.

**Comment by dchen1107** [comment] 2015-09-15 23:42
Ahh, the corresponding docker issue for this one should be: https://github.com/docker/docker/issues/14026

**Comment by zviadm** [comment] 2015-09-21 20:38
Fyi I think I was running into very similar issues with docker directly (i.e. without kubernetes). Here is an issue I opened with docker directly: https://github.com/docker/docker/issues/16376

You can try same thing with synchronizing all calls to `docker pull` application side if possible and see if that makes the issue go away.

**Comment by iameli** [comment] 2015-10-06 01:25
I don't have the expertise to say whether or not this is related, but I was encountering this issue constantly and it went away completely when I switched `DOCKER_STORAGE='aufs'` in the Saltstack init script to `DOCKER_STORAGE='aufs-nolvm'`.

Possibly some kind of poor interaction between the LVM set up by Kubernetes' Saltstack and the aforementioned Docker bugs? No idea. Figured I'd document this for anyone else running into this using the `kube-up` AWS.

**Comment by bronger** [comment] 2015-10-06 23:20
Does anybody have a workaround for this on GKE?

**Comment by vishh** [comment] 2015-10-07 16:30
Can we collect the output of `dmesg` from the node whenever this happens again?
@bronger: I'd check the status of docker daemon ```cat /proc/`pidof docker`/status``` and `dmesg`. In the past, machine restarts have fixed this issue.

**Comment by iameli** [comment] 2015-10-08 00:49
I retract my earlier comment, it's happening again. Perhaps a bit less often since I switched to `aufs-nolvm`.

[Here's my dmesg](https://gist.github.com/iameli/611ad345f908248e9440). Looks pretty crazy, actually. I'll follow up on my end and see if I have any pods leaking.

**Comment by sroze** [comment] 2015-10-08 07:13
@iameli probably just because you restarted the Docker daemon, that's my workaround for now: I'm running a daemon on each Docker node and every time is sees this error, it is restarting the local Docker...

**Comment by bronger** [comment] 2015-10-08 08:07
My proc status outout is https://gist.github.com/bronger/6185881357fc069447be
And my dmesg is https://gist.github.com/bronger/c9ccacd88cb2d7a40f95

Both seems to be similar to @iameli's observations.  And restarting the docker daemon solves the issue also for me.

**Comment by saturnism** [comment] 2015-10-13 22:42
restarting the docker daemon on the temporarily fixes my issue as well.

`dmesg` is filled with this line:
```
[7105875.751556] aufs opt_add:782:docker[30564]: lookup failed /var/lib/docker/aufs/diff/840234741900807847ceb6681d36ca0790fcdfd2ed0eee5eda3220e186d408e4 (-2)
```

`status`
```
Name:	docker
State:	S (sleeping)
Tgid:	3359
Ngid:	0
Pid:	3359
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	512
Groups:	
VmPeak:	 1295612 kB
VmSize:	 1295612 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   57444 kB
VmRSS:	   57152 kB
VmData:	 1281860 kB
VmStk:	     136 kB
VmExe:	   13444 kB
VmLib:	       0 kB
VmPTE:	     520 kB
VmSwap:	       0 kB
Threads:	88
SigQ:	1/14829
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	ffffffffffc1feff
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
Seccomp:	0
Cpus_allowed:	1
Cpus_allowed_list:	0
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	612
nonvoluntary_ctxt_switches:	14738
```

**Comment by tylrtrmbl** [comment] 2015-10-18 21:34
> FYI, I'm experiencing this in "production" on Google Container Engine too.

I just noticed this today on GKE. I was able to restart docker. I had to manually `docker pull` all my images after that, but I'm up and running. This is a concerning problem though. :grimacing:

**Comment by vishh** [comment] 2015-10-19 18:22
For Kubernetes v1.2, I plan on validating `overlayfs` to be the default storage driver for Kubernetes deployments. 

Until then would #15856 help @tylrtrmbl @saturnism @bronger ?

**Comment by saturnism** [comment] 2015-10-19 19:34
I'm not sure if #15856 helps (not entirely sure how it determines Docker daemon health?).  In my cases, the docker daemon seems to run just fine.  It can continue to pull other images.  But in order to pull the image that got into a bad state, restarting the daemon works.

**Comment by dchen1107** [comment] 2015-10-19 20:34
@saturnism Please see my comment: https://github.com/kubernetes/kubernetes/pull/15856#issuecomment-149306017 
I have the same concerns as you.

**Comment by vishh** [comment] 2015-10-19 21:29
@dchen1107 suggested subscribing to docker event stream and restarting the daemon if an aufs related error is returned by the daemon. However, we decided to not add that patch for v1.1. 
We will try switching to OverlayFs (#15867) for v1.2. We are also hoping for newer docker releases to resolve docker specific aufs issues.

**Comment by dchen1107** [comment] 2015-10-19 21:31
I also close another attempt for fixing this issue: #15881

There is no reliable way to detect such failure. We also observed the same failure caused by kernel issue, which requires reboot the node completely. In this case, we decided to document such issue for 1.1 as known issue with info on how to remedy. 

I am lowering the priority of the issue and moving it out of 1.1.

**Comment by saturnism** [comment] 2015-10-19 21:55
Serializing pulls seems to help.  Is that an option?
Secondly, I'm not 100% convinced that overlayfs will make fix this issue.

**Comment by vsimon** [comment] 2015-10-19 22:02
Agreeing with the above comment that serializing pulls was the only thing that worked in my case. Haven't seen this issue pop up in many weeks after serializing.

**Comment by iameli** [comment] 2015-10-19 22:35
Is there a easy way to instruct Kubernetes to "serialize pulls"? If I create a pod with three containers, it's going to pull down all three in parallel no matter what I do, right?

**Comment by vishh** [comment] 2015-10-19 22:52
@iameli: AFAIK kubelet does not support serializing docker pulls.

**Comment by saturnism** [comment] 2015-10-20 01:16
@vishh i like where this is going! :+1:

**Comment by derekwaynecarr** [comment] 2015-10-20 12:13
@vishh - we do not want to require the use of OverlayFS for Kube 1.2 at Red Hat

**Comment by vishh** [comment] 2015-10-23 23:12
@derekwaynecarr: That was not the intention either. We currently use Aufs in GCE and GKE. My comment was that we will evaluate overlayfs as an alternative to Aufs on those deployments.

**Comment by vishh** [comment] 2015-10-23 23:13
I'm marking this issue as resolved for now. Serializing images as part of #15914 should hopefully solve this issue. If it happens even after serialization feel free to re-open this issue.

**Closed by vishh** 2015-10-23 23:13 UTC
Labels: priority/P1, team/node

**Comment by jezell** [comment] 2015-12-19 10:53
Was seeing this same problem today resizing instance groups in gke (not in e2e tests but on a production gke cluster running kube 1.1.3 / docker 1.9). So don't think serializing the images has made the problem go away. Kind of a pain to resolve since I had to restart docker daemon and manually repull images down to the node via docker pull to get pods to start.

**Comment by dchen1107** [comment] 2016-05-10 00:12
#23028 for reporting sys oom event through node problem detector. Sample system oom dmesg can be found at https://github.com/kubernetes/kubernetes/issues/10959#issuecomment-146384521
