### ISSUE TITLE
Invalid value: "foregroundDeletion": name is neither a standard finalizer name nor is it fully qualified

### ISSUE THREAD

**Issue by hmarcelodn** [kubernetes/kubernetes#56427] opened 2017-11-27 15:51 UTC
We have a full cluster running in production and suddenly it stopped working with the following error:

> The Deployment "**authapi**" is invalid: metadata.finalizers[0]: Invalid value: "foregroundDeletion": name is neither a standard finalizer name nor is it fully qualified

My current cluster version is:

  
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

On the other hand, we cannot deploy either. The following message appear when kubectl is trying to deploy:

> W1127 15:28:32.999978   42625 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
> The Deployment "authapi" is invalid: metadata.finalizers[0]: Invalid value: "foregroundDeletion": name is neither a standard finalizer name nor is it fully qualified
> /home/builduser/myagent/_work/_temp/kubectlTask/1511796511792/kubectl failed with return code: 1
> 

Any help on this?

**Comment by liggitt** [comment] 2017-11-27 18:45
duplicate of #45764, fixed in #46500 in 1.6.7

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.6.md/#changelog-since-v166

**Closed by liggitt** 2017-11-27 18:45 UTC
Labels: needs-sig
