### ISSUE TITLE
kubernetes-e2e-gke flake due to node unhealthy

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21411] opened 2016-02-17 20:07 UTC
kubernetes-e2e-gke test failed due to node unhealthy:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/1220

>
11:01:36 ERROR: (gcloud.container.clusters.create) Operation [ 11:01:36 name: u'operation-1455734333499-a29e3a49'
11:01:36 operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
11:01:36 selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/249458424157/zones/us-central1-f/operations/operation-1455734333499-a29e3a49'
11:01:36 status: StatusValueValuesEnum(DONE, 3)
11:01:36 statusMessage: u'All cluster resources were brought up, but the cluster API is reporting that node "gke-jkns-gke-e2e-ci-e3558aae-node-v9m4" is unhealthy.'
11:01:36 targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/249458424157/zones/us-central1-f/clusters/jkns-gke-e2e-ci'
11:01:36 zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that node "gke-jkns-gke-e2e-ci-e3558aae-node-v9m4" is unhealthy. 
11:01:36 2016/02/17 11:01:36 e2e.go:307: Error running up: exit status 1
11:01:36 2016/02/17 11:01:36 e2e.go:303: Step 'up' finished in 22m44.815917361s
11:01:36 
2016/02/17 11:01:36 e2e.go:141: Error starting e2e cluster. Aborting.
11:01:36 exit status 1

full text:
[e2e-gke-flake.txt](https://github.com/kubernetes/kubernetes/files/135070/e2e-gke-flake.txt)

**Comment by jlowdermilk** [comment] 2016-02-22 22:15
This is yet another dupe of #20916. If #21703 has not fixed it, we'll reopen the other issue that has more context.

**Closed by jlowdermilk** 2016-02-22 22:15 UTC
Labels: kind/flake, team/gke
