### ISSUE TITLE
"Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host" is flaky at head

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13257] opened 2015-08-27 13:20 UTC
This test is failing pretty frequently at head. It fails with the following message:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:122
Expected
    <string>: 
to equal
    <string>: 8434336239690371650

@kubernetes/goog-testing @quinton-hoole

**Comment by wojtek-t** [comment] 2015-08-27 13:24
cc @saad-ali - who was looking into those tests some time ago

**Comment by saad-ali** [comment] 2015-08-27 17:48
I'll take a look.

This test became unstable starting with Jenkins `kubernetes-e2e-gce` build `8229` which was started at `Aug 26, 2015 12:10:00 PM PST`. This build was "started by timer" and had no new changes. The previous build, `8228`, which was started at `Aug 26, 2015 11:44:28 AM PST` failed to run altogether and was triggered by the following changes:
* #13029 AWS: Add disk size/type defaults to config-test
* #13003 kubelet: trigger pod workers independently
* #13209 fix error in 'rm' path instructions to force restaging 
* #12972 Kubectl describe for experimental HorizontalPodAutoscaler

I will try to narrow down and see if any of these PRs is the culprit.

**Comment by saad-ali** [comment] 2015-08-27 23:07
Looks like this this test was broken by PR #13003

The test `Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host` fails for me locally at head. Once I revert PR #13003 locally the test starts passing.

I'll look to see if there is an easy fix, otherwise we can consider reverting that PR.

CC @yujuhong

**Comment by yujuhong** [comment] 2015-08-27 23:22
Before the PR, kubelet performs cleanup (removing orphaned volumes/ pod directories, etc every 10s). Now these tasks would only be performed every 10s. 
If this is considered not acceptable, I can instruct kubelet to perform the cleanup on every pod deletion. I will also run the test locally to verify this.

**Comment by yujuhong** [comment] 2015-08-28 01:07
I looked into the test more, and here is what I come up with:
  1. We now kill containers with a grace period, defaulting to 30 second if not set. The PD test uses a pod with the busybox image running a sleep command, which does not respond to the sigterm signal, and would only be sigkill'd after 30 seconds.
  2. Kubele might nuke the pod directory even when there are still running containers. This is not a new bug, and I had a PR (#10651) to fix it. This caused the test to fail.
  3. The longer housekeeping period (though needs to be fixed) is probably not at fault in this case.

I will work on (2) and (3).

**Comment by saad-ali** [comment] 2015-08-28 01:11
Thanks for digging in to this @yujuhong 

I'll work on 1

**Comment by yujuhong** [comment] 2015-08-28 01:34
> I'll work on 1
Thanks!

It'd be better if the container would not ignore sigterm for the test and/or the grace period is set to something smaller than the default.

In addition to that, it might be better to use a non-zero grace period in  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pd.go#L101, and then check the apiserver to make sure that kubelet has deleted the pod before moving to the next step. The 0 grace period immediately deletes the pod from the apiserver, but gives no indication whether kubelet has kill the pod or not. The after-test PD detaching might fail for the same reason. Note that this is not necessary if kubelet cleans up fast and frequently enough...

**Comment by brendandburns** [comment] 2015-08-28 03:07
We need to fix this in e2e asap.  Unless someone is directly working on fixing the test, I vote for reverting #13003 until there is a fix in place to make e2e pass.

**Comment by saad-ali** [comment] 2015-08-28 04:07
@yujuhong Regarding 1, now that I think about it, I'd rather leave the test as is: It was written when we noticed that users who were rapidly deleting and recreating a pod were running in to issues with GCE PDs. So by not wait for the volume to actually detach, the test is functioning as intended. Brenden merged #10651, hopefully that fixes the underlying bug.

**Comment by yujuhong** [comment] 2015-08-28 05:38
> We need to fix this in e2e asap. Unless someone is directly working on fixing the test, I vote for reverting #13003 until there is a fix in place to make e2e pass.

@brendandburns, the test was already in the flaky gce suite......shouldn't GKE jenkins exclude the flaky tests as well?

**Comment by yujuhong** [comment] 2015-08-28 05:42
> @yujuhong Regarding 1, now that I think about it, I'd rather leave the test as is: It was written when we noticed that users who were rapidly deleting and recreating a pod were running in to issues with GCE PDs. So by not wait for the volume to actually detach, the test is functioning as intended. Brenden merged #10651, hopefully that fixes the underlying bug.

I am okay with keeping the test as it is, as long as it's clear that the test needs to wait a bit longer than usual. It currently takes ~190s to complete in the parallel-flaky suite.

**Comment by wojtek-t** [comment] 2015-08-28 06:21
Thanks a lot for working on it @saad-ali and @yujuhong - good job in debugging it!

**Comment by ixdy** [comment] 2015-08-28 06:54
> @brendandburns, the test was already in the flaky gce suite......shouldn't GKE jenkins exclude the flaky tests as well?

gke-ci isn't using the configuration in `hack/jenkins/e2e.sh` yet. It should be, but the PR to move the various gke to e2e.sh jobs never got completed. (The result of this is that gke-ci's list of flaky tests is pretty far out of date.)

**Comment by yujuhong** [comment] 2015-08-28 17:25
Let's close this issue now that the PD test is back and running. As the followup, I created a new issue for cleaning up more reliably in kubelet #13311.

**Closed by yujuhong** 2015-08-28 17:25 UTC
Labels: area/test, priority/P1, team/testing

**Comment by saad-ali** [comment] 2015-08-28 17:27
We should also be more careful marking tests flaky. When a test is clearly broken (failing consistently) moving it to flaky just hides the problem and gives a false sense of security.

**Comment by quinton-hoole** [comment] 2015-08-28 23:35
@ixdy is anyone working on the PR to move the GKE tests to the config in hack/jenkins/e2e.sh ?  Do you have a PR number? Perhaps someone can pick up where it left off.

@saad-ali Yes, marking tests as flaky is meant to only be done for truly *flaky* tests, precisely because by virtue of being flaky, they provide no useful signal (if they fail, there's likely no regression, and if they pass, they're likely not fixed yet).  Consistently failing tests however (particularly if they were consistently passing before some point), provide a very strong signal as to what introduced the regression, and whether any proposed fix fixes it.  So that should be used for such debugging, rather than being ignored.

**Comment by ixdy** [comment] 2015-08-28 23:39
There was a PR #10960 that never got finished.

**Comment by wojtek-t** [comment] 2015-08-31 06:39
>
@saad-ali Yes, marking tests as flaky is meant to only be done for truly flaky tests, precisely because by virtue of being flaky, they provide no useful signal (if they fail, there's likely no regression, and if they pass, they're likely not fixed yet). Consistently failing tests however (particularly if they were consistently passing before some point), provide a very strong signal as to what introduced the regression, and whether any proposed fix fixes it. So that should be used for such debugging, rather than being ignored.

I agree - I will try to be more specific next time.
