### ISSUE TITLE
Error creating firewall rule on cluster startup

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20776] opened 2016-02-06 19:01 UTC
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke/512/

```
05:02:43 ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
05:02:43  - Internal Error
05:02:43  
05:02:43 2016/02/06 05:02:43 e2e.go:309: Error running up: exit status 1
05:02:43 2016/02/06 05:02:43 e2e.go:305: Step 'up' finished in 2m40.209174522s
```

@brendandburns this sounds similar to a thing that you fixed with a retry. Maybe time for a gcloud-with-retry script?

**Comment by bprashanth** [comment] 2016-02-07 04:41
Closing as dupe of https://github.com/kubernetes/kubernetes/issues/20306 and the meta issue https://github.com/kubernetes/kubernetes/issues/20576

**Closed by bprashanth** 2016-02-07 04:41 UTC
Labels: kind/flake, team/cluster, team/test-infra
