### ISSUE TITLE
Pod Disk tests are taking too long

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#18778] opened 2015-12-16 19:50 UTC
The four tests in `tests/e2e/pd.go` are taking about 24 minutes to run in `kubernetes-e2e-gce`, which is about a quarter of the time to run the entire suite. The four tests are taking roughly two minutes, three minutes, eight minutes, and ten minutes individually. They are spending the majority of their time waiting for pods to start running.

Should we move these to the slow suite?

Assigned @ixdy but feel free to reassign. I don't know who the proper assignee is here.

**Comment by ixdy** [comment] 2015-12-16 23:08
@saad-ali anything we can do here?

**Comment by saad-ali** [comment] 2015-12-16 23:28
Not much, we're at the mercy of GCE latency. We do multiple attach/detach per test each of which may take many minutes to complete.

See https://github.com/kubernetes/kubernetes/pull/16766 and https://github.com/kubernetes/kubernetes/issues/15382#issuecomment-153268655

**Comment by spxtr** [comment] 2015-12-17 00:41
Should we move these tests to the slow suite?

**Comment by saad-ali** [comment] 2015-12-17 00:53
It looks like the merge bot currently doesn't monitor the `gce-slow` suite. I don't want the tests to be moved there, if that means that failures will be ignored.

If we can get `kubernetes-e2e-gce-slow` added to the list of suites that, if not green, will block the merge queue, then I'm fine with moving the two >5 min run time tests to the slow suite.

**Comment by spxtr** [comment] 2015-12-17 01:54
Merge bot doesn't, but it's in critical builds on Jenkins so the build cop is responsible for keeping it green.

**Comment by saad-ali** [comment] 2015-12-17 05:59
Being in the critical builds list is not sufficient. I really don't want breaking changes slipping in. These tests are stable enough that if they break that is enough of a signal to block further merges.

**Comment by spxtr** [comment] 2015-12-17 17:41
Is there an alternative way to speed this up? `kubernetes-e2e-gce` has been creeping up in run time and it's passing two hours lately.

**Comment by saad-ali** [comment] 2015-12-17 18:35
I looked into ways to speed things up. The bottleneck is the create/attach/detach/delete PD times, which are outside our control. And these tests need to do serial attaches/detaches in order to test those scenarios. Why don't we just move the two slow tests to the slow suite, and make the slow suite one of the suites that the merge-bot watches?

**Comment by ihmccreery** [comment] 2015-12-22 00:06
> Being in the critical builds list is not sufficient.

It needs to be sufficient.  If it isn't, that's a problem we need to resolve.

> Why don't we just move the two slow tests to the slow suite, and make the slow suite one of the suites that the merge-bot watches?

We don't want to block merge-bot on the slow suite because a test flaking blocks the queue for however long it takes to rerun the suite.  With these tests, that suite will be ~3 hours, which is an unacceptably long time to block the merge queue, in my opinion.

Think of non-merge-bot-blocking test suites as "nightly", if that makes sense.  There are just some tests that take too long to block the world on.  This seems to be one of them.

**Comment by saad-ali** [comment] 2015-12-22 05:34
> We don't want to block merge-bot on the slow suite because a test flaking blocks the queue for however long it takes to rerun the suite. With these tests, that suite will be ~3 hours, which is an unacceptably long time to block the merge queue, in my opinion.
Think of non-merge-bot-blocking test suites as "nightly", if that makes sense. There are just some tests that take too long to block the world on. This seems to be one of them.

I'd argue that it's worth fixing/removing the flaky tests in the slow suite first. Once the slow test suite is in a state where a test failure strongly correlates with a regression, then we should have the merge-bot block on the slow suite--even if that means multiple hours to recover, because a failure means a bad PR was merged, and no further PRs should be merged until the offending PR is rolled back. My worry is that if we don't do this, breaking changes to these tests won't be taken as seriously.

That said, I can buy your argument that we can improve the process around monitoring of critical builds so that failures in the slow suite are addressed quickly (i.e. treat the slow suite as a "nightly" build of sorts). I'll leave it up to you guys to make the call.

**Comment by ihmccreery** [comment] 2015-12-22 16:55
> I'd argue that it's worth fixing/removing the flaky tests in the slow suite first.

I totally hear that.  We're doing a lot right now trying to prioritize fixing flakes.  Rest assured that I'll be taking this stuff into account when working on my follow-up to @bprashanth's #17791.

@saad-ali any specific ideas for improving how we monitor critical builds?  What can we do better to be sure that critical builds are taken seriously?

**Comment by saad-ali** [comment] 2015-12-23 02:48
> @saad-ali any specific ideas for improving how we monitor critical builds? What can we do better to be sure that critical builds are taken seriously?

The goal is to minimize the amount of time required to identify a breaking change and get it rolled back. The first part of what you said, "fixing flakes", I think is a critical first step. Once that happens we can empower on-call to hunt down and roll back any PR that causes a regression in a critical build, instead of letting it go since it's probably a flake.

**Comment by spxtr** [comment] 2016-01-05 19:59
These tests got even slower, taking 27 minutes total now. Just to be clear, @saad-ali would you be okay with moving these to slow as things currently stand? I think on-call will roll back any PR that causes a regression in a critical job, especially if it fails twice in a row. The difference is that it will take several hours longer to be fixed in the slow suite, but I think that's an acceptable trade-off for cutting 20 minutes off of kubernetes-e2e-gce.

Would you mind if I assign this issue to you?

**Comment by saad-ali** [comment] 2016-01-06 14:16
> Just to be clear, @saad-ali would you be okay with moving these to slow as things currently stand?

Yes

> Would you mind if I assign this issue to you?

I'm out of office until Monday. If this can wait until then, feel free to assign it to me.

**Closed** 2016-01-13 21:57 UTC
Labels: area/test, priority/P1, team/test-infra
