### ISSUE TITLE
CronJob creates a lot of Job objects

### ISSUE THREAD

**Issue by mikekap** [kubernetes/kubernetes#39815] opened 2017-01-12 18:23 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.4.7

**Environment**:
- **Cloud provider or hardware configuration**: Ubuntu
- **OS** (e.g. from /etc/os-release): 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux ip-10-0-7-241.us-west-2.compute.internal 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Custom (similar to kubernetes the hard way)
- **Others**: I have a `CronJob` (technically `ScheduledJob` in 1.4.7) that runs every minute.

**What happened**:
`kube-apiserver` ran out of memory because there were 12,000 `Job` objects. The `Pod`s were reaped by the controlled manager, but the `Job` objects were still there.

**What you expected to happen**:
`kube-apiserver` doesn't run out of memory.

**How to reproduce it** (as minimally and precisely as possible):
Create a `CronJob` that runs every minute and wait ~ 1 month.

**Anything else do we need to know**:

**Comment by kargakis** [comment] 2017-01-12 19:06
Dupe of https://github.com/kubernetes/kubernetes/issues/34710 cc: @soltysh

**Comment by soltysh** [comment] 2017-01-16 10:59
Yes, it's a duplicate. I'm closing in favor of the other one.

**Closed by soltysh** 2017-01-16 10:59 UTC
