### ISSUE TITLE
Log rotating not enabled - master killed logs filled up

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#27754] opened 2016-06-21 05:03 UTC
Hi all

The logs on the gci master 1.3 beta image are not being rolled.  Just lost my master because `/var/log` was filled up :(  Are we using logrotate?  Because it is not configured.

The cluster is a multi az cluster running on gce, using the default master.  Cluster was created using `kube-up.sh`.

Master version info.

``` console
clove@kubernetes-master /etc $ cat /proc/version
Linux version 4.4.4+ (chrome-bot@build297-m2) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_a2bc87a_4.9.2-r128) ) #1 SMP Fri Jun 17 14:27:45 PDT 2016
```

K8s Version info:

``` console
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-beta.1", GitCommit:"1c7855093eb999c8f3cedb19d3467cd7b691e35e", GitTreeState:"clean", BuildDate:"2016-06-17T00:58:51Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-beta.1", GitCommit:"1c7855093eb999c8f3cedb19d3467cd7b691e35e", GitTreeState:"clean", BuildDate:"2016-06-17T00:53:24Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

cc: @bgrant0607 @andyzheng0831 @kubernetes/goog-image

**Comment by adityakali** [comment] 2016-06-21 16:01
This was recently fixed by PR #27409.

**Comment by chrislovecnm** [comment] 2016-06-21 17:14
I will cherry pick that and keep this open till I test.  Thanks @adityakali

**Comment by bprashanth** [comment] 2016-06-28 23:48
Log rotating once an hour is apparently not enough, reports are coming in of apiserver logs growing to fill up the /var partition on a 1000 node cluster. @kubernetes/sig-scalability @kubernetes/goog-node can we rotate based on size instead?

**Comment by bprashanth** [comment] 2016-06-28 23:55
oh hmm, maybe the fix just wasn't in 1.3 beta. @chrislovecnm what's the output of `sudo systemctl list-timers` on your master?

**Comment by chrislovecnm** [comment] 2016-06-28 23:58
1. We may want to put `/var/log` in its own partition or disk.  Also putting the containers on to its own partition.
2. May want to assess using sizing for masters: SM, MED, LARGE, XL, XXL, etc.  This sizing could include CPU, Memory, Disk, etc.

**Comment by Random-Liu** [comment] 2016-06-28 23:59
@chrislovecnm I still can't get into your master. Can you check whether https://github.com/kubernetes/kubernetes/pull/27409 is included in your master?

**Comment by chrislovecnm** [comment] 2016-06-29 00:03
I have log rolling, from that PR, but if they will up before they get rolled :)  Or do we have problems with the log rolling?

```console
clove@kubernetes-master /etc/logrotate.d $ cat *
/var/lib/docker/containers/*/*-json.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 10M
    daily
    create 0644 root root
}
/var/log/kube-addons.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
/var/log/kube-apiserver.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
/var/log/kube-controller-manager.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
/var/log/kube-proxy.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
/var/log/kube-scheduler.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
```

**Comment by bprashanth** [comment] 2016-06-29 00:04
So whens the next timer? (sudo systemctl list-timers) and what's the size right now (ls -lh)?
It still makes sense to rotate on size, though if you don't have the fix, it probably isn't urgent.

**Comment by chrislovecnm** [comment] 2016-06-29 00:07
```console
NEXT                         LEFT       LAST                         PASSED   UNIT                         ACTIVATES
Wed 2016-06-29 00:21:14 UTC  13min left Tue 2016-06-28 00:21:14 UTC  23h ago  systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Wed 2016-06-29 01:00:00 UTC  52min left Wed 2016-06-29 00:00:00 UTC  7min ago kube-logrotate.timer         kube-logrotate.service

2 timers listed.
```

**Comment by thockin** [comment] 2016-06-29 00:14
5GB for logs is just tooooo small

**Comment by bprashanth** [comment] 2016-06-29 00:16
I thought that was a dynamic sizing based on cluster size. If not it probably should be. Eitherway, 5GB in 1 hour?

**Comment by thockin** [comment] 2016-06-29 00:18
I'm not excusing the size of our log, but 5 GB is pretty stingy by ANY
definition.

**Comment by chrislovecnm** [comment] 2016-06-29 00:25
@thockin not only just logs. That is all of var ...

**Comment by dchen1107** [comment] 2016-06-29 00:34
The default logrotate is daily, hourly. I don't think gci changes that. In this case, even there is a size config like 100M for rotation, I don't think it checks your log file size often enough. Should the low hanging fruit here is make it run hourly? 

Also agreed 5GB is too small for /var ...

**Comment by bprashanth** [comment] 2016-06-29 00:37
I think it *does* run hourly, that's why i asked for the timer list
```
Wed 2016-06-29 01:00:00 UTC  52min left Wed 2016-06-29 00:00:00 UTC  7min ago kube-logrotate.timer         kube-logrotate.service
```

**Comment by thockin** [comment] 2016-06-29 00:38
it should be 100GB, at least

**Comment by Random-Liu** [comment] 2016-06-30 09:21
Just FYI, I'm able to get into the master now.

The /var is not full yet (but may be full soon?):
```
/dev/sda1       5.7G  4.1G  1.7G  72% /var
```

```
/var $ sudo du -h --max-depth=1
4.0K    ./ssl
2.6G    ./log
4.0K    ./db
4.0K    ./spool
4.0K    ./empty
20K     ./cache
970M    ./lib
20K     ./tmp
3.6G    .
```
The disk usage of `/var/lib` is mainly contributed by `overlayfs`.
The disk usage of `/var/log` is mainly contributed by apiserver log and journald.
```
1.7G     ./kube-apiserver.log
979M    ./journal
```
apiserver log did rotate:
```
-rw-r--r--  1 root    root            1.7G Jun 30 09:21 kube-apiserver.log
-rw-r--r--  1 root    root             25M Jun 30 02:00 kube-apiserver.log-20160630.gz
```

**Comment by adityakali** [comment] 2016-07-07 21:37
It seems kubernetes uses 10GB root disk size for clusters with nodes <= 1000 and 50GB otherwise (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L663). GCI reserves 4Gb for its rootfs partitions, and all of the rest will be available for logs, docker containers, user-data (home dirs), etc. 

So I think whats really needed here is to scale disk-size for master (and possibly nodes too?) in a better way.

**Comment by thockin** [comment] 2016-07-08 05:18
I feel like it should be 10x that.

**Comment by bprashanth** [comment] 2016-07-08 17:20
If we're confident that logs are getting rotated every hour, then the rate of log generation is issue for concern. I think we all agree about disk size. Writing logs at that rate at V(2) is going to cause disk performance to degrade.

**Comment by chrislovecnm** [comment] 2016-07-14 19:45
@thockin so what are the actions from this issue?

**Comment by thockin** [comment] 2016-07-15 06:38
@Random-Liu Can I pass this to you to own?  I'll propose:

0-10 nodes: 100GB
10-100 nodes: 250 GB
100-1000 nodes: 500 GB
1000+ nodes: 1000 GB

What do you think?  I think it's better to err on the side of "too big" and maybe dial back when we have data that it is too big.

**Comment by thockin** [comment] 2016-07-15 06:38
I'm tagging this as a 1.4

**Comment by chrislovecnm** [comment] 2016-07-15 22:02
> 0-10 nodes: 100GB
> 10-100 nodes: 250 GB
> 100-1000 nodes: 500 GB
> 1000+ nodes: 1000 GB

1TB is a bit big :)

@thockin  how about
1. volume for logs 
2. volume for dockers images
3. machine sizing for S,M,L,XL deployments (compute / ram, for cross-cloud deployments)

I assume that you don't want LVM, but that is my preference.

**Comment by Random-Liu** [comment] 2016-07-15 22:31
> @Random-Liu Can I pass this to you to own?

@thockin Sure.

Do we want to change the master instance size or use a volume? Which would be better?

**Comment by chrislovecnm** [comment] 2016-07-15 22:42
@Random-Liu volume ... PLEASE ... sugar on top

**Comment by thockin** [comment] 2016-07-15 23:50
Doing it as a volume brings a lot more complexity.  Can we first fix the
problem of running out of space and THEN talk about overall bettering of
the system?

Maybe 1TB is too big  How about 100, 200, 350, 500 ?

**Comment by davidopp** [comment] 2016-07-15 23:56
> machine sizing for S,M,L,XL deployments (compute / ram, for cross-cloud deployments)

Unless I'm misunderstand what you're asking for, there's guidance for that here
http://kubernetes.io/docs/admin/cluster-large/

Please send a PR to update it if you'd like to change or expand the recommendations.
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/cluster-large.md

(I'm not talking about the volume stuff here, just the part of your message that I quoted above.)

**Comment by Random-Liu** [comment] 2016-07-16 00:01
> Unless I'm misunderstand what you're asking for, there's guidance for that here
http://kubernetes.io/docs/admin/cluster-large/

If so, except changing https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L663,  maybe we should also have disk size recommendation in the doc http://kubernetes.io/docs/admin/cluster-large/.

**Comment by Random-Liu** [comment] 2016-07-16 00:02
> Doing it as a volume brings a lot more complexity.  Can we first fix the
problem of running out of space and THEN talk about overall bettering of
the system?

OK. So
* For short term, I'll update https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L663 to make the disk size larger.
* For long term, we should discuss whether to have separate volume for master log.

**Comment by bprashanth** [comment] 2016-07-16 00:11
wait, isn't there a log spam issue? i remember Chris rm -rf'd the directory and in 1h it was full again, before the next logrotate.

**Comment by thockin** [comment] 2016-07-16 00:26
There is ALSO a logspam issue, but running out is sort of bad.

**Comment by chrislovecnm** [comment] 2016-07-16 00:40
@thockin yah How about 100, 200, 350, 500  works better.  

No I don't think there is a big log spam issue, as much the server was busy.  Spam to me is repeated messages that are duplicates, this was just a busy fast server.

**Comment by bprashanth** [comment] 2016-07-16 10:09
Please, that server was idle :) 
A "busy" master is 2000 nodes with continuous pod churn. Production webservers need hourly rotation. IIUC the logs were from plain old node status updates. We need logging handlers that compress insipid frequent requests.

**Comment by thockin** [comment] 2016-07-16 16:02
We need better logs, but also rotating hourly is sort of pathetic.

**Comment by chrislovecnm** [comment] 2016-07-16 18:24
So we need multiple issues here:

1. This issue: increase disk size and rotate logs more often
2. Tuning logging at scale
3. Disk layout of master (LVM or multiple disks)
4. If the installer should include recommendations for sizing masters if we are doing disk sizing, then why are we not doing compute and ram sizing.

Did I miss anything?  Do you want me to open the other issues?

**Comment by adityakali** [comment] 2016-07-17 20:59
> For short term, I'll update https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L663 to make the disk size larger.

We should consider fixing this in next 1.3.x release.

**Comment by adityakali** [comment] 2016-07-17 21:15
Also, looking closely at the logrotate configs, 
/var/log/kube-apiserver.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}

it seems we use "maxsize" to limit the log size. According to manpage (https://github.com/logrotate/logrotate/blob/master/logrotate.8#L324):

> maxsize size
>             Log files are rotated when they grow bigger than size bytes even before
>             the additionally specified time interval (daily, weekly, monthly, 
>             or yearly).  The related size option is  similar  except  that  it 
>              is mutually exclusive with the time interval options, and it causes
>              log files to be rotated without regard for the last rotation time.  
>              When maxsize is used, both the size and timestamp of a log file are                  
>              considered.

i.e., Once the log rotates after first 100Mb in a day, it will not be rotated again on the same day even the size of new logfile reaches 100Mb. Is this how it was intended?

This has been the behavior in 1.2.x as well (with master on debian based container-vm) (https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/logrotate/conf) and has been the same on 1.3.x GCI master/nodes as well (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L95).

If I understand the option correctly, if we want logs to be rotated when either a day has elapsed OR its size has reached 100M, we should probably use "size 100M" instead of "maxsize 100M".

**Comment by alex-mohr** [comment] 2016-07-18 17:20
Thanks @adityakali.

@thockin It's not clear to me there's a "safe" amount to overprovision disk by vs. fixing the configs so rotations keep log usage within expected ranges.  Could you (or someone you find) please address the root cause and get logrotates configured to work as expected?

Given this is affecting 1.3 and we should fix, I switched milestone and increased priority to P0.

**Comment by bprashanth** [comment] 2016-07-18 18:25
The suggested logroate fix sounds simple enough https://github.com/kubernetes/kubernetes/pull/29128

**Comment by thockin** [comment] 2016-07-18 18:33
I am OOO right now.  Please assign back to Lantao, maybe?

**Comment by bprashanth** [comment] 2016-07-18 18:39
Yeah I got the cheap fix in. That should make the rest P1 and probably not cherrypick worthy (because we'd doc recommended disk size).

**Comment by chrislovecnm** [comment] 2016-07-19 01:06
Does anyone have a comment in regards to breaking this issue apart as I recommended above?

**Comment by thockin** [comment] 2016-08-03 07:20
On the Google side I think @Random-Liu owns this - please tell me if you think otherwise, @Random-Liu

**Comment by Random-Liu** [comment] 2016-09-09 04:13
@thockin So do we still need to change node disk size according to the cluster size?

**Comment by fabioy** [comment] 2016-09-21 21:17
I think we should do both dynamic disk size based upon cluster size, AND @chrislovecnm's partitioning idea. We've had masters break because the logs filled up and isolating that failure from the rest would be good.

**Comment by alex-mohr** [comment] 2016-10-14 00:03
@Random-Liu Any idea on when this might land?

**Comment by bprashanth** [comment] 2016-10-14 00:21
I believe /var/ (/var/log/docker,logs) is already a seperate partition that occupies all the bootdisk not used by rootfs. @vishh or @Amey-D will know for sure. We should document the recommended lvm patitioning scheme for on-perm masters, but currently I dont think we have a way to do anything better.

**Comment by alex-mohr** [comment] 2016-10-14 00:27
@bprashanth Propose + implement something that works for GKE and then document it and/or make that the default so others can benefit too?

**Comment by bprashanth** [comment] 2016-10-14 00:31
So GKE+GCI should already have a partitioned /var, limiting the damange. 
The remaining work is:    
1. auto sizing of disk based on cluster size at kube-up time (not sure who is responsible for this, lifecycle? node?), or at least recommending variable disk size.
2. documenting partition scheme for other platforms so log spam doesn't eg: cause 100% root partition and a completely dead node

**Comment by krmayankk** [comment] 2017-05-09 19:57
what is the logrotation story for bare metal deployment. Is logrotate enabled by default for baremetal  ? Is there a configuration in kubelet that allows the logrotation to be tweaked ?

**Comment by vishh** [comment] 2017-05-14 21:13
@crassirostris possible use case for kubelet rotating logs.

**Comment by crassirostris** [comment] 2017-05-14 21:38
@krmayankk Currently there's no thought through story around logging at all. Log rotation is configured by the kubernetes deployment tool, e.g. if you use `kube-up.sh`, it installs and configures logrotate on the nodes but without the ability to configure it without changing the scripts.

It's not a perfect situation and we're working on changing that and formalizing how log rotation and storage management for logs works in Kubernetes and how it should be configured. Hopefully, there'll be an advancement in this field in June and in the next release.

**Comment by krmayankk** [comment] 2017-05-15 02:57
@crassirostris is there a proposal around it ?

**Comment by crassirostris** [comment] 2017-05-15 09:18
@krmayankk The proposal is the goal for this quarter. The plan is to release it for the community to review sometime in June. I'll advertise it as wide as possible, including this issue. Does it sound reasonable?

**Comment by yujuhong** [comment] 2018-01-23 17:54
I think the issue is obsolete, and rotation of non-stdout/stderr container logs is configured differently in different cloud setups.

**Closed by yujuhong** 2018-01-23 17:54 UTC
Labels: area/logging, lifecycle/rotten, priority/critical-urgent, sig/node, team/control-plane (deprecated - do not use)
