### ISSUE TITLE
Secrets should be consumable from pods in volume [Conformance]

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32705] opened 2016-09-14 19:25 UTC
Secrets should be consumable from pods in volume [Conformance]

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by saad-ali** [comment] 2016-09-14 20:11
This is expected behavior. The behavior of secrets was changed as of 1.3, and the 1.2 test is asserting something that is no longer true for 1.3/1.4. 

Dupe of https://github.com/kubernetes/kubernetes/issues/26662 (which we ran in to in 1.3 upgrade testing).

**Comment by saad-ali** [comment] 2016-09-14 20:13
Closing issue as expected behavior.

**Comment by pwittrock** [comment] 2016-09-17 16:21
@saad-ali On Monday, please update the 1.3 / 1.2 test expectations so that we can get rid of this noise in our test grid.  (I can't keep track of the dozen tests we have decided the failures were expected for, and we are going to run into this again when we do upgrade testing against 1.5)

https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-cvm-1.4-upgrade-cluster

**Comment by davidopp** [comment] 2016-09-18 01:50
failing in
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-cvm-1.4-upgrade-cluster

**Comment by saad-ali** [comment] 2016-09-19 18:12
@pwittrock PTAL @ https://github.com/kubernetes/kubernetes/pull/32930

**Comment by saad-ali** [comment] 2016-09-21 23:24
Closing this since PR #32930 is merged and addresses this test

**Closed by saad-ali** 2016-09-21 23:24 UTC
Labels: area/test, component/kubelet, kind/upgrade-test-failure, priority/P0, team/cluster
