### ISSUE TITLE
[KMSv2] update code to mark API as GA in v1.29

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#120309] opened 2023-08-31 12:59 UTC
I think all of the changes will be focused around allowing `v2` as an acceptable value in addition to `v2beta1` (with associated unit/integration tests):

https://github.com/kubernetes/kubernetes/blob/76b06ee239a893dece6eae861090f06df994a878/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go#L55-L56

/sig auth
/triage accepted
/assign ritazh
/milestone v1.29

**Comment by zelenushechka** [comment] 2023-10-15 14:36
Hello @enj @ritazh ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by ritazh** [comment] 2023-10-16 06:21
Yes this is planned. Just waiting for few PRs to get merged first before getting to this one. Thanks for the bump!

**Closed** 2023-10-27 00:23 UTC
Labels: sig/auth, triage/accepted
