### ISSUE TITLE
HPA e2es are failing after upgrade from v1.1 to v1.2.

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20925] opened 2016-02-09 20:28 UTC
See http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/.

I'll leave to @piosz to triage.

**Comment by ihmccreery** [comment] 2016-02-09 20:30
These started failing yesterday, but weren't running prior to yesterday due to anomalies fixed by #20596.

**Comment by piosz** [comment] 2016-02-11 16:28
I took a look into run 389 and there is no logs from controller manager:
```
130.211.115.120:22-kube-controller-manager.log	30 B	inode/x-empty	
```
Is this expected behavior?

**Comment by ihmccreery** [comment] 2016-02-11 18:47
@piosz, yes, this is expected behavior.  I didn't realize we don't collect master logs on GKE, but it's consistent across other jobs.

What are the chances you can diagnose this without those logs?

**Comment by piosz** [comment] 2016-02-11 20:14
The problem here is similar to #20338: lack of resources. HPA test requires 2500m of CPU. In this suite we have only 3 nodes with 1 core each. One of possible solution is to increase the size of nodes there (default in gce is 2 cores node).

Reassigning back to @ihmccreery for the decision.

**Comment by piosz** [comment] 2016-02-12 08:11
Pasting logs as an evidence
```
16:41:17 Feb 10 16:41:17.962: INFO: event for rc-hnrh1: {default-scheduler } FailedScheduling: pod (rc-hnrh1) failed to fit in any node
16:41:17 fit failure on node (gke-upgrade-gke-1-1-master-a7b8a78e-node-6i5r): Node didn't have enough resource: CPU, requested: 500, used: 520, capacity: 1000
16:41:17 fit failure on node (gke-upgrade-gke-1-1-master-a7b8a78e-node-x1zi): Node didn't have enough resource: CPU, requested: 500, used: 800, capacity: 1000
16:41:17 fit failure on node (gke-upgrade-gke-1-1-master-a7b8a78e-node-gucq): Node didn't have enough resource: CPU, requested: 500, used: 600, capacity: 1000
```

**Comment by ihmccreery** [comment] 2016-02-17 19:58
> HPA test requires 2500m of CPU.

Does that mean that HPA also requires 2500m of CPU?  Can we reasonably expect HPA to work on small clusters?

We should have a signal that HPA works in a 'standard' GKE cluster, or put tooling in to make sure it's not deployed on clusters where it's not working.

**Comment by ihmccreery** [comment] 2016-02-17 19:58
> One of possible solution is to increase the size of nodes there (default in gce is 2 cores node).

What is another possible solution, to get signal on a "normal" GKE deployments?

**Comment by piosz** [comment] 2016-02-18 21:17
No. HPA doesn't require any resources itself. This is just a specification of test. The problem is that we are using master proxy to send requests to pods and master proxy uses random load balancing strategy. To avoid flakiness of the test each pod should have enough resources to handle the whole traffic in case we are unlucky and each request is sent to the same pod. That means that if we want to create 5 pods and each is using by average 100m of CPU, each of them should request for 500m of CPU.

Another possibility here is to change the test by I'd like to avoid it.

cc @fgrzadkowski

**Comment by ihmccreery** [comment] 2016-02-18 22:35
> The problem is that we are using master proxy to send requests to pods and master proxy uses random load balancing strategy.

Shouldn't we be able to dial pods directly?  I thought that was the whole point of having proxies.

**Comment by ihmccreery** [comment] 2016-02-19 00:52
Looking into the test, you should be able to pass a pod selector to the `ResourceConsumer` object, and it should be able to make resource consumption requests directly to each pod, instead of relying on the load balancer.

**Comment by piosz** [comment] 2016-02-19 11:02
The test is simulating the real use case:
- service created on top of a group of pods
- user uses service to access the application
- the load is spread across all pods
- hpa observes that the traffic is too high, so decide to increase number of pods
- the load should be then spread across all pods (including the new ones)
- the whole operation should be unnoticeable by users

So we can't send request directly to pods but rather we have to use load balancer.

**Comment by ihmccreery** [comment] 2016-02-19 22:47
I'm skeptical that we favor "real-life-ness" over determinism in our testing.  I've sent #21594 to alleviate the problem, but I still think this test should be written differently.

**Comment by davidopp** [comment] 2016-02-21 04:16
Please remove v1.2 and P0 tags if Ike's PR fixes this.

**Comment by piosz** [comment] 2016-02-22 09:22
@ihmccreery the test is as deterministic as possible. The only undeterministic part here is relying on service level load balancing (when using master proxy to access it). Alternatively we can create a load generator which runs inside of the cluster as a pod. Created issue #21664 for this.

#21594 has fixed the problem partially, but there is still an issue with throttled master proxy requests. #21664 should help with it, but in the meantime we should disabled throttling there.

**Comment by piosz** [comment] 2016-02-22 09:23
```
18:57:28 W0221 18:57:28.106218   26825 request.go:627] Throttling request took 3.908236167s, request: https://104.197.225.156/api/v1/proxy/namespaces/e2e-tests-horizontal-pod-autoscaling-taxat/services/rc/ConsumeCPU?durationSec=30&millicores=20
18:57:28 W0221 18:57:28.306228   26825 request.go:627] Throttling request took 4.108116026s, request: https://104.197.225.156/api/v1/proxy/namespaces/e2e-tests-horizontal-pod-autoscaling-taxat/services/rc/ConsumeCPU?durationSec=30&millicores=20
18:57:28 W0221 18:57:28.506231   26825 request.go:627] Throttling request took 4.30798745s, request: https://104.197.225.156/api/v1/proxy/namespaces/e2e-tests-horizontal-pod-autoscaling-taxat/services/rc/ConsumeCPU?durationSec=30&millicores=20
```

**Comment by piosz** [comment] 2016-02-22 12:28
It seems the throttling was enabled for almost a year and we noticed it recently after #21377 was merged. We haven't had any problems before, so throttling is here not the case.

Still investigating.

**Comment by ihmccreery** [comment] 2016-02-23 18:47
@piosz What's the status of this?

**Comment by piosz** [comment] 2016-02-23 19:53
How can I reproduce locally?

**Comment by piosz** [comment] 2016-02-23 19:59
It seems that in build http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/441/ your PR #21594 was not picked. I can see in logs: `beta.kubernetes.io/instance-type=n1-standard-1`. Could you please re-trigger the suite?

**Comment by piosz** [comment] 2016-02-24 06:05
In run http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/442 we are still using n1-standard-1. @ihmccreery could you please update to use n1-standard-2?

**Comment by ihmccreery** [comment] 2016-02-24 22:47
Ick.  See #21924; I configured it wrong.  Once that goes in, we should be in business.

> How can I reproduce locally?

Deploy a cluster at v1.1, build v1.2 and run the cluster v1.2 upgrade e2e, then run the test.  See https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/job-configs/kubernetes-upgrades.yaml#L171  It's a royal pain, and I apologize for that.  Working on making it better.

**Comment by piosz** [comment] 2016-02-25 06:31
#21924 is merged. Could you please re-trigger suite?

**Comment by piosz** [comment] 2016-02-29 06:32
It seems #21924 helped here. HPA e2e tests are passing in upgrade suite, so closing the issue.

**Closed by piosz** 2016-02-29 06:32 UTC
Labels: area/autoscaling, area/test, area/upgrade, priority/P0, team/control-plane
