### ISSUE TITLE
Kubelet reports Pod status NotReady for the first time after restart

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#106689] opened 2021-11-26 07:01 UTC
### What happened?

Pod status NotReady was reported for the first time after Kubelet restart. And then it goes back to Ready very quickly
As a result, Pod IP is removed from Endpoints by Controller-Manager and added. Caused a certain amount of jitter to the cluster as a whole.

Pod actually works fine

### What did you expect to happen?

Kubelet reports the correct Pod status at the first time after restart

### How can we reproduce it (as minimally and precisely as possible)?

1. Pod with Readiness
2. kubectl get pod -w {the pod}
3. on the node where the Pod is located, restart Kubelet

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux zsm-test-0 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
NONE
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment] 2021-12-01 18:36
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/100277#issuecomment-910517011

If we want to fix this, we need to propose an enhancement/KEP, as it will be a behaviour change.

/close

**Closed** 2021-12-01 18:36 UTC
Labels: kind/bug, sig/node, needs-triage
