### ISSUE TITLE
Clean up all of our Dockerfiles

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#7881] opened 2015-05-07 06:02 UTC
We should make them all FROM either scratch, busybox, or debian:jessie (or ubuntu:14.04 but it is bigger).  I am sad that there is not an ultra-small "just enough debian to run apt-get install" base.

**Comment by thockin** [comment] 2015-05-07 06:08
it looks like debian:jessie is 50MB bigger than wheezy.  Sigh.

**Comment by mbforbes** [comment] 2015-05-07 16:39
huge +1 for the "just enough debian to run apt-get install" base. This has confused me about Docker containers since I first attempted to understand them.

**Comment by kargakis** [comment] 2017-06-02 23:54
@kubernetes/sig-release-misc

**Comment by thockin** [comment] 2017-06-03 22:36
@timstclair in case this wasn't in your inbox - up to you when to close it :)

**Comment by timstclair** [comment] 2017-06-05 20:05
Duplicate of https://github.com/kubernetes/kubernetes/issues/40248

**Closed by timstclair** 2017-06-05 20:05 UTC
Labels: kind/cleanup, priority/backlog, sig/release
