### ISSUE TITLE
[Flaky test] TestStartingResourceVersion

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#96649] opened 2020-11-17 19:32 UTC
**Which jobs are flaking**:

pull-kubernetes-bazel-test

**Which test(s) are flaking**:

`TestStartingResourceVersion`

**Reason for failure**:

```
=== RUN   TestStartingResourceVersion
I1105 23:34:27.424577   25898 client.go:360] parsed scheme: "endpoint"
I1105 23:34:27.424635   25898 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix://localhost:2990678306340884590  <nil> 0 <nil>}]
--- FAIL: TestStartingResourceVersion (0.12s)
panic: interface conversion: runtime.Object is nil, not *example.Pod [recovered]
	panic: interface conversion: runtime.Object is nil, not *example.Pod

goroutine 1316 [running]:
testing.tRunner.func1.1(0x10fa780, 0xc000a23e00)
	/usr/local/go/src/testing/testing.go:1076 +0x30d
testing.tRunner.func1(0xc0008fd800)
	/usr/local/go/src/testing/testing.go:1079 +0x41a
panic(0x10fa780, 0xc000a23e00)
	/usr/local/go/src/runtime/panic.go:969 +0x175
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/tests.TestStartingResourceVersion(0xc0008fd800)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/tests/cacher_test.go:646 +0xd66
testing.tRunner(0xc0008fd800, 0x12cd260)
	/usr/local/go/src/testing/testing.go:1127 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1178 +0x386
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestStartingResourceVersion
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92743/pull-kubernetes-bazel-test/1328727115385802752

/assign @wojtek-t

**Comment by wojtek-t** [comment] 2020-11-17 20:12
OK - I can quite reliably reproduce this problem by adding
`time.Sleep`
before this line:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L1394

This seems to be a test issue (watch being closed as a result of not being able to process stuff on time).
I will think how fix the test and make it not suffer from heavy cpu starvation.

**Comment by wojtek-t** [comment] 2020-11-18 07:37
Opened fix in https://github.com/kubernetes/kubernetes/pull/96662

**Closed** 2020-11-20 03:14 UTC
Labels: kind/flake, sig/api-machinery, triage/accepted
