### ISSUE TITLE
e2e failure: Version Skew: Client and Server version are different

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#19952] opened 2016-01-21 22:04 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4134/ failed with Version Skew: Client and Server version are different

12:01:34 Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.357+61096f49984a17", GitCommit:"61096f49984a1784d32e5c2e4e1de40d1d3e01db", GitTreeState:"clean"}
12:01:34 Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.359+bc55b1a58b8e98", GitCommit:"bc55b1a58b8e98fc30b5e72fe32bf68c1e871d67", GitTreeState:"clean"}

Blocked submit queue merging for an hour.

**Comment by ixdy** [comment] 2016-01-22 20:18
This is almost certainly a dupe of #8705.

**Comment by ihmccreery** [comment] 2016-01-22 21:27
Closing in favor of #8705.

**Closed** 2016-01-22 21:28 UTC
Labels: area/test, kind/flake, priority/P0, team/test-infra
