### ISSUE TITLE
Weird quota and limitrange behavior

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#25484] opened 2016-05-11 16:04 UTC
I'm using HEAD in the master branch with a simple 1 master + 1 slave setup. API server is started with the following flag: `--admission-control=LimitRanger,NamespaceLifecycle,ResourceQuota`.

To reproduce:
```
kubectl create namespace test
kubectl --namespace=test create -f docs/admin/resourcequota/quota.yaml
kubectl --namespace=test create -f docs/admin/limitrange/limits.yaml
kubectl --namespace=test run nginx --image=nginx:latest --requests="cpu=500m,mem=100mi"
```
Of course, no pods will be created because "cpu=500m" exceeds the default value of "cpu=300m". This is expected behavior. However, the unexpected part is when I do a `kubectl describe namespace test`, and the cpu usage was showing:
```
Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			1500m	20
 memory			300Mi	1Gi
```
As each container was supposed to request 500m cpu, this looks like replicaset controller is trying to create more pods after previous ones were rejected, and this causes the quota usage to keep increasing. This will continue until the quota controller runs and reconciliates the actual information (by default it runs every 5 minutes). I'm wondering if this is the intended behavior, as this could cause all the quota to be used up very quickly until the quota controller runs the next time, and effectively, this blocks all the future pod creation.

**Comment by huang195** [comment] 2016-05-11 16:04
@derekwaynecarr thoughts on this?

**Comment by derekwaynecarr** [comment] 2016-05-11 16:52
I tried the scenario as follows:

```
$ cluster/kubectl.sh create namespace test
$ cluster/kubectl.sh create -f docs/admin/resourcequota/quota.yaml --namespace=test
$ cluster/kubectl.sh create -f docs/admin/limitrange/limits.yaml --namespace=test
$ $ cluster/kubectl.sh describe namespace test
Name:	test
Labels:	<none>
Status:	Active

Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			0	20
 memory			0	1Gi
 persistentvolumeclaims	0	10
 pods			0	10
 replicationcontrollers	0	20
 resourcequotas		1	1
 secrets		1	10
 services		0	5

Resource Limits
 Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
 ----		--------	---	---	---------------	-------------	-----------------------
 Pod		memory		6Mi	1Gi	-		-		-
 Pod		cpu		200m	2	-		-		-
 Container	cpu		100m	2	200m		300m		-
 Container	memory		3Mi	1Gi	100Mi		200Mi		-
$ cluster/kubectl.sh run nginx --image=nginx:latest --requests="cpu=500m,memory=100Mi" --namespace=test
$ cluster/kubectl.sh describe rs --namespace=test
Name:		nginx-2871125668
Namespace:	test
Image(s):	nginx:latest
Selector:	pod-template-hash=2871125668,run=nginx
Labels:		pod-template-hash=2871125668
		run=nginx
Replicas:	0 current / 1 desired
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  58s		58s		1	{replicaset-controller }			Warning		FailedCreate	Error creating: Pod "nginx-2871125668-mx6xl" is invalid: spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
  58s		58s		1	{replicaset-controller }			Warning		FailedCreate	Error creating: Pod "nginx-2871125668-o3fqt" is invalid: spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
  39s		39s		1	{replicaset-controller }			Warning		FailedCreate	Error creating: Pod "nginx-2871125668-92zje" is invalid: spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
  10s		10s		1	{replicaset-controller }			Warning		FailedCreate	Error creating: Pod "nginx-2871125668-llfqm" is invalid: spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
$ $ cluster/kubectl.sh describe namespace test
Name:	test
Labels:	<none>
Status:	Active

Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			0	20
 memory			0	1Gi
 persistentvolumeclaims	0	10
 pods			0	10
 replicationcontrollers	0	20
 resourcequotas		1	1
 secrets		1	10
 services		0	5

Resource Limits
 Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
 ----		--------	---	---	---------------	-------------	-----------------------
 Pod		memory		6Mi	1Gi	-		-		-
 Pod		cpu		200m	2	-		-		-
 Container	cpu		100m	2	200m		300m		-
 Container	memory		3Mi	1Gi	100Mi		200Mi		-
```

From what I can gather, this is working as intended.

The pod creation request is being rejected because the limit is defaulting to 300m per the limit range configuration, the request was 500m, and the request cannot be less than the limit for cpu.

Are you sure both your servers have the same set of admission controllers configured?

**Comment by derekwaynecarr** [comment] 2016-05-11 16:58
Apologies, I closed this too early.  I understand the issue.

**Comment by derekwaynecarr** [comment] 2016-05-11 17:02
The root issue is the following:

* make request to create a resource
* admission control intercepts request
 * limit ranger applies defaults
 * quota is updated per the request
* admission control completes
* api server validates the object prior to creation
 * validation fails (in this case it was because limits were less than request)

So yes, this is a known issue that quota can be incremented when you send a resource that fails object validation.  I would love to have a means to validate an object in admission control reliably, but that is not yet possible.

For this particular situation, I could look to have quota reject when it sees a limit < request.  I will open a PR to address that soon.

/cc @lavalamp @smarterclayton - it would be nice if quota had a way to do more reliable object validation in admission flows, maybe we can discuss in sig.

**Comment by huang195** [comment] 2016-05-11 17:09
> Are you sure both your servers have the same set of admission controllers configured?
This is for a non-HA setup. I have only 1 master + 1 slave node, so there's only one admission controller in play here.

What you described above is exactly what I did as well in my local environment, but for me `cluster/kubectl.sh describe namespace test` returned what I described above. One other more direct test without replicaset controller messing around with things is to create a single pod, e.g.:

```
root@k8-haih1:~/kubernetes/docs/admin/limitrange# cat >test.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: "500m"
        memory: 100Mi
EOF
root@k8-haih1:~/kubernetes/docs/admin/limitrange# kubectl --namespace=test create -f test.yaml              
The Pod "nginx" is invalid.
spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
root@k8-haih1:~/kubernetes/docs/admin/limitrange# kubectl describe namespace test              
Name:	test
Labels:	<none>
Status:	Active

Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			500m	20
 memory			100Mi	1Gi
 persistentvolumeclaims	0	10
 pods			1	10
 replicationcontrollers	0	20
 resourcequotas		1	1
 secrets		0	10
 services		0	5

Resource Limits
 Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
 ----		--------	---	---	---------------	-------------	-----------------------
 Pod		cpu		200m	2	-		-		-
 Pod		memory		6Mi	1Gi	-		-		-
 Container	cpu		100m	2	200m		300m		-
 Container	memory		3Mi	1Gi	100Mi		200Mi		-


root@k8-haih1:~/kubernetes/docs/admin/limitrange# kubectl --namespace=test create -f test.yaml 
The Pod "nginx" is invalid.
spec.containers[0].resources.limits[cpu]: Invalid value: "300m": must be greater than or equal to request
root@k8-haih1:~/kubernetes/docs/admin/limitrange# kubectl describe namespace test
Name:	test
Labels:	<none>
Status:	Active

Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			1	20
 memory			200Mi	1Gi
 persistentvolumeclaims	0	10
 pods			2	10
 replicationcontrollers	0	20
 resourcequotas		1	1
 secrets		0	10
 services		0	5

Resource Limits
 Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
 ----		--------	---	---	---------------	-------------	-----------------------
 Pod		cpu		200m	2	-		-		-
 Pod		memory		6Mi	1Gi	-		-		-
 Container	cpu		100m	2	200m		300m		-
 Container	memory		3Mi	1Gi	100Mi		200Mi		-
```

As you can see, each failed pod will keep increasing quota usage.

**Comment by huang195** [comment] 2016-05-11 17:14
A few minutes later after the quota controller runs, we get the state reconciliated:
```
root@k8-haih1:~/kubernetes/docs/admin/limitrange# kubectl describe namespace test
Name:	test
Labels:	<none>
Status:	Active

Resource Quotas
 Name:			quota
 Resource		Used	Hard
 --------		---	---
 cpu			0	20
 memory			0	1Gi
 persistentvolumeclaims	0	10
 pods			0	10
 replicationcontrollers	0	20
 resourcequotas		1	1
 secrets		0	10
 services		0	5

Resource Limits
 Type		Resource	Min	Max	Default Request	Default Limit	Max Limit/Request Ratio
 ----		--------	---	---	---------------	-------------	-----------------------
 Pod		cpu		200m	2	-		-		-
 Pod		memory		6Mi	1Gi	-		-		-
 Container	memory		3Mi	1Gi	100Mi		200Mi		-
 Container	cpu		100m	2	200m		300m		-
```

This is fine if pods are created manually one by one as what I'm doing here, but if the user uses a replicaset to spawn pods, it will automatically create more when desired state doesn't match actual state. This will artificially inflate quota usage than the actual.

**Comment by derekwaynecarr** [comment] 2016-05-11 17:33
@huang195 - right, see my description here: https://github.com/kubernetes/kubernetes/issues/25484#issuecomment-218523426  , and let me know if that makes sense.  I agree this is something we can fix for this particular case (invalid resource requests), but there will continue to be additional cases that are not yet covered (where the pod fails validation for other reasons).

**Comment by huang195** [comment] 2016-05-11 18:01
so what you're saying is if `--admission-control=...,ResourceQuota,AlwaysDeny`, the fix you have in mind won't help. It would be nice to have a callback function for the admission control plugins so that the rejection of a request would invoke these callback functions to perform any cleanups if necessary.

**Comment by derekwaynecarr** [comment] 2016-05-11 18:09
@huang195 - correct, that would be nice.  in the interim, I can look to address your particular scenario where request < limit.  There are pros/cons to call-back, but we explored a post hook in admission control.  I also thought about using reservations with short expiration times (see https://github.com/kubernetes/kubernetes/pull/20113).  In general, we should have better validation on the pod templates that are embedded in controllers, that ideally, maybe this scenario where the request was less than the limit mitigates the problem.  In practice, we discourage having any admission controller later than `ResourceQuota` for this reason.

**Comment by huang195** [comment] 2016-05-11 18:25
Thanks for the pointers @derekparker. You meant limit < request, right? Will take a look at the proposal you linked above. Do you have a link on the post hook mechanism in admission control you mentioned?

**Comment by derekwaynecarr** [comment] 2016-05-11 18:34
@huang195 - there is no proposal yet for a post hook in admission control.

I have a fix for the scenario described here in #25487.

Thanks for the issue report!

**Comment by huang195** [comment] 2016-05-11 18:38
Great, thanks for the quick fix

**Comment by lavalamp** [comment] 2016-05-11 22:32
@derekwaynecarr do we have an issue filed about how admission controller is broken in theory and not just practice?

**Comment by derekwaynecarr** [comment] 2016-05-12 01:26
@lavalamp - I will open an issue that describes the theory problem soon.
Goal would be to reach a model that broke admission controllers into
different phases such that we can have something like the following:

defaulting -> constraints -> validation -> quota -> storage

I am not certain how I would handle a post hook on a request to know if the
storage succeeded or not.   Had some rough thoughts that we can iterate on.

**Comment by lavalamp** [comment] 2016-05-12 05:09
Yeah, quota and storage really ought to be atomic. But we have to make do
with what we have. I think our current admission controller model sorta
works for security purposes but is quite unsuitable for quota.

**Closed** 2016-05-13 22:07 UTC
Labels: priority/P2, team/control-plane
