### ISSUE TITLE
hide metadata.managedFields in `kubectl get -o yaml`

### ISSUE THREAD

**Issue by tringuyen-yw** [kubernetes/kubernetes#91584] opened 2020-05-29 15:01 UTC
**What would you like to be added**: add a new option in `kubectl get --output=yaml` which does NOT show [metadata.managedFields](https://kubernetes.io/docs/reference/using-api/api-concepts/#field-management) in the output.
May be `kubectl get --output=yaml --hideManagedFields` ?

**Why is this needed**: to make the output shorter. As this option is not enabled by default. When the user really wants a shorter output on the console. Mostly to make a quicky review on the user-defined values. This option allows to hide the `metadata.managedFields` which make the screen output shorter and easier to focus on user defined data.

A kind of imitation in the same fashion than `kubectl config view --minify`

/sig api-machinery
/sig usability

**Comment by liggitt** [comment] 2020-05-29 17:47
thanks for the request, closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/90066

/close

**Closed** 2020-05-29 17:47 UTC
Labels: kind/feature, needs-sig
