### ISSUE TITLE
kubectl --export flag doesn't work

### ISSUE THREAD

**Issue by Temikus** [kubernetes/kubernetes#33241] opened 2016-09-22 01:59 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl, get, export, --export, flag

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 
```
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): OS X 10.11.6
- **Kernel** (e.g. `uname -a`): Darwin ... 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
- **Install tools**: gcloud
- **Others**:

**What happened**:
`kubectl get --export` doesn't strip the cluster specific info from resources (self-links, etc.)

**What you expected to happen**:
`kubectl get --export` should provide a cluster-unspecific resource that can be redeployed right away

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
```
temikus λ kubectl get deployments --export -o=yaml > deploy.yaml
temikus λ kubectl get deployments -o=yaml > deploy_false.yaml
temikus λ diff deploy*
##empty line, should actually be a diff
```

**Comment by AdoHe** [comment] 2016-09-22 02:47
@Temikus could you please try `kubectl get deployments --v=9 --export -o=yaml`, this would output the response from apiserver.

**Comment by Temikus** [comment] 2016-09-22 04:16
@AdoHe Sure, here's a partially anonymised response:
````
λ kubectl get deployments --v=9 --export -o=yaml
I0922 14:09:29.344746   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:29.345765   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/api
I0922 14:09:29.900988   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:29.901499   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:29.902131   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:30.547001   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/api 200 OK in 1201 milliseconds
I0922 14:09:30.547024   16042 round_trippers.go:324] Response Headers:
I0922 14:09:30.547030   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:30.547034   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:30 GMT
I0922 14:09:30.547038   16042 round_trippers.go:327]     Content-Length: 133
I0922 14:09:30.547105   16042 request.go:891] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}
I0922 14:09:30.547394   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/apis
I0922 14:09:30.548262   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:30.549008   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:30.719798   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/apis 200 OK in 172 milliseconds
I0922 14:09:30.719824   16042 round_trippers.go:324] Response Headers:
I0922 14:09:30.719829   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:30.719834   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:30 GMT
I0922 14:09:30.719838   16042 round_trippers.go:327]     Content-Length: 824
I0922 14:09:30.719881   16042 request.go:891] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}]}
I0922 14:09:30.721074   16042 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" -H "Accept: application/json, */*" https://xxx.xxx.xxx.xxx/api
I0922 14:09:31.081823   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.082347   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.082997   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.260178   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/api 200 OK in 539 milliseconds
I0922 14:09:31.260204   16042 round_trippers.go:324] Response Headers:
I0922 14:09:31.260210   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:31.260214   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:31 GMT
I0922 14:09:31.260218   16042 round_trippers.go:327]     Content-Length: 133
I0922 14:09:31.260259   16042 request.go:891] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}
I0922 14:09:31.260429   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/apis
I0922 14:09:31.260887   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.261384   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.398876   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/apis 200 OK in 138 milliseconds
I0922 14:09:31.398902   16042 round_trippers.go:324] Response Headers:
I0922 14:09:31.398908   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:31.398912   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:31 GMT
I0922 14:09:31.398916   16042 round_trippers.go:327]     Content-Length: 824
I0922 14:09:31.398957   16042 request.go:891] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}]}
I0922 14:09:31.399882   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/api
I0922 14:09:31.760739   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.761219   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.761876   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.937124   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/api 200 OK in 537 milliseconds
I0922 14:09:31.937150   16042 round_trippers.go:324] Response Headers:
I0922 14:09:31.937156   16042 round_trippers.go:327]     Content-Length: 133
I0922 14:09:31.937160   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:31.937165   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:31 GMT
I0922 14:09:31.937207   16042 request.go:891] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}
I0922 14:09:31.937371   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/apis
I0922 14:09:31.937838   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:31.938358   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.075840   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/apis 200 OK in 138 milliseconds
I0922 14:09:32.075865   16042 round_trippers.go:324] Response Headers:
I0922 14:09:32.075871   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:32.075876   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:32 GMT
I0922 14:09:32.075892   16042 round_trippers.go:327]     Content-Length: 824
I0922 14:09:32.075932   16042 request.go:891] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}]}
I0922 14:09:32.078508   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/api
I0922 14:09:32.438298   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.438788   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.439437   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.612618   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/api 200 OK in 534 milliseconds
I0922 14:09:32.612648   16042 round_trippers.go:324] Response Headers:
I0922 14:09:32.612654   16042 round_trippers.go:327]     Content-Length: 133
I0922 14:09:32.612658   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:32.612662   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:32 GMT
I0922 14:09:32.612702   16042 request.go:891] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}
I0922 14:09:32.612862   16042 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" https://xxx.xxx.xxx.xxx/apis
I0922 14:09:32.613321   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.613767   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:32.751355   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/apis 200 OK in 138 milliseconds
I0922 14:09:32.751381   16042 round_trippers.go:324] Response Headers:
I0922 14:09:32.751387   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:32.751392   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:32 GMT
I0922 14:09:32.751396   16042 round_trippers.go:327]     Content-Length: 824
I0922 14:09:32.751444   16042 request.go:891] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"x.x.x.x/0","serverAddress":"xxx.xxx.xxx.xxx"}]}]}
I0922 14:09:32.751715   16042 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: kubectl/v1.3.7 (darwin/amd64) kubernetes/a2cba27" -H "Accept: application/json, */*" https://xxx.xxx.xxx.xxx/apis/extensions/v1beta1/namespaces/default/deployments?export=true
I0922 14:09:33.122822   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:33.123318   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:33.123935   16042 loader.go:327] Config loaded from file /Users/xxxxxxxx/.kube/config
I0922 14:09:33.299139   16042 round_trippers.go:318] GET https://xxx.xxx.xxx.xxx/apis/extensions/v1beta1/namespaces/default/deployments?export=true 200 OK in 547 milliseconds
I0922 14:09:33.299164   16042 round_trippers.go:324] Response Headers:
I0922 14:09:33.299169   16042 round_trippers.go:327]     Content-Type: application/json
I0922 14:09:33.299173   16042 round_trippers.go:327]     Date: Thu, 22 Sep 2016 04:09:33 GMT
I0922 14:09:33.299233   16042 request.go:891] Response Body: {"kind":"DeploymentList","apiVersion":"extensions/v1beta1","metadata":{"selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments","resourceVersion":"413111"},"items":[{"metadata":{"name":"ci-stack","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/ci-stack","uid":"xxxxxxxx-7593-11e6-a28d-42010af0009c","resourceVersion":"54186","generation":2,"creationTimestamp":"2016-09-08T07:09:30Z","labels":{"app":"ci-stack","version":"0.1"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ci-stack","version":"0.1"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"ci-stack","version":"0.1"}},"spec":{"volumes":[{"name":"gogs-persistent-storage","gcePersistentDisk":{"pdName":"gogs-disk","fsType":"ext4"}},{"name":"jenkins-persistent-storage","gcePersistentDisk":{"pdName":"jenkins-disk","fsType":"ext4"}}],"containers":[{"name":"gogs","image":"gogs/gogs","ports":[{"name":"gogs-web","containerPort":3000,"protocol":"TCP"},{"name":"gogs-ssh","containerPort":22,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"gogs-persistent-storage","mountPath":"/data"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"},{"name":"jenkins","image":"jenkins","ports":[{"name":"jenkins-web","containerPort":8080,"protocol":"TCP"},{"name":"jenkins-agent","containerPort":50000,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"jenkins-persistent-storage","mountPath":"/var"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":1}},{"metadata":{"name":"website","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/website","uid":"xxxxxxxx","resourceVersion":"363843","generation":14,"creationTimestamp":"2016-09-14T02:16:37Z","labels":{"app":"website","version":"master.22"},"annotations":{"deployment.kubernetes.io/revision":"7","kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"Deployment\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"website\",\"creationTimestamp\":null},\"spec\":{\"replicas\":4,\"selector\":{\"matchLabels\":{\"app\":\"website\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"website\",\"version\":\"master.3\"}},\"spec\":{\"containers\":[{\"name\":\"website\",\"image\":\"gcr.io/xxx-xxxx/website:master.3\",\"ports\":[{\"name\":\"website-http\",\"containerPort\":80},{\"name\":\"website-https\",\"containerPort\":443}],\"resources\":{},\"imagePullPolicy\":\"IfNotPresent\"}]}},\"strategy\":{\"type\":\"RollingUpdate\",\"rollingUpdate\":{\"maxUnavailable\":1,\"maxSurge\":1}}},\"status\":{}}"}},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"website"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"website","version":"master.3"}},"spec":{"containers":[{"name":"website","image":"gcr.io/xxx-xxxx/website:master.3","ports":[{"name":"website-http","containerPort":80,"protocol":"TCP"},{"name":"website-https","containerPort":443,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":14,"replicas":4,"updatedReplicas":4,"availableReplicas":4}}]}
I0922 14:09:33.299983   16042 meta.go:86] Calling Accessor on non-internal object: *extensions.DeploymentList
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2016-09-08T07:09:30Z
    generation: 2
    labels:
      app: ci-stack
      version: "0.1"
    name: ci-stack
    namespace: default
    resourceVersion: "54186"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ci-stack
    uid: xxxxxxxx-7593-11e6-a28d-4xxxxxxx
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ci-stack
        version: "0.1"
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ci-stack
          version: "0.1"
      spec:
        containers:
        - image: gogs/gogs
          imagePullPolicy: Always
          name: gogs
          ports:
          - containerPort: 3000
            name: gogs-web
            protocol: TCP
          - containerPort: 22
            name: gogs-ssh
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /data
            name: gogs-persistent-storage
        - image: jenkins
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 8080
            name: jenkins-web
            protocol: TCP
          - containerPort: 50000
            name: jenkins-agent
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var
            name: jenkins-persistent-storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - gcePersistentDisk:
            fsType: ext4
            pdName: gogs-disk
          name: gogs-persistent-storage
        - gcePersistentDisk:
            fsType: ext4
            pdName: jenkins-disk
          name: jenkins-persistent-storage
  status:
    availableReplicas: 1
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "7"
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"website","creationTimestamp":null},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"website"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"website","version":"master.3"}},"spec":{"containers":[{"name":"website","image":"gcr.io/xxx-xxxx/website:master.3","ports":[{"name":"website-http","containerPort":80},{"name":"website-https","containerPort":443}],"resources":{},"imagePullPolicy":"IfNotPresent"}]}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{}}'
    creationTimestamp: 2016-09-14T02:16:37Z
    generation: 14
    labels:
      app: website
      version: master.22
    name: website
    namespace: default
    resourceVersion: "363843"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/website
    uid: xxxxxxxx
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: website
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: website
          version: master.3
      spec:
        containers:
        - image: gcr.io/xxx-xxxx/website:master.3
          imagePullPolicy: IfNotPresent
          name: website
          ports:
          - containerPort: 80
            name: website-http
            protocol: TCP
          - containerPort: 443
            name: website-https
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 4
    observedGeneration: 14
    replicas: 4
    updatedReplicas: 4
kind: List
metadata: {}
```

**Comment by kargakis** [comment] 2016-09-22 12:47
Closing as a dupe of https://github.com/kubernetes/kubernetes/issues/24855

**Closed by kargakis** 2016-09-22 12:47 UTC
Labels: component/kubectl, team/ux
