### ISSUE TITLE
GCE/GKE multizone: volume subpath tests failing

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#61128] opened 2018-03-13 19:33 UTC
https://k8s-testgrid.appspot.com/sig-storage#gce-multizone

/assign
/sig storage
/kind bug

**Comment by liggitt** [comment] 2018-03-13 19:47
/close
duplicate of https://github.com/kubernetes/kubernetes/issues/61101

**Closed by liggitt** 2018-03-13 19:47 UTC
Labels: kind/bug, sig/storage
