### ISSUE TITLE
AWS: cannot mount volumes on C5 instances

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#56273] opened 2017-11-23 04:17 UTC
C5 instances don't mount volumes on the device path, instead they mount them on "random" nvme devices:  http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html

We need to identify the device using the nvme ioctls (directly or indirectly via the nvme command).

**Comment by gnufied** [comment] 2017-11-23 05:33
Do we want this for 1.9? Duplicate of this issue - https://github.com/kubernetes/kubernetes/issues/56155

**Comment by justinsb** [comment] 2017-11-23 06:50
Ah - thanks.  I'm thinking it's going to affect any users using c5 instances, but there might well be more instance types announced at reinvent that use nvme (I have no knowledge, but it seems like a pretty safe bet!)

Prototyping how to handle in https://github.com/kubernetes/kops/pull/3914

We can discuss on #56155 anyway...

**Closed** 2017-11-23 06:50 UTC
Labels: kind/bug, milestone/needs-approval, priority/critical-urgent, sig/aws
