### ISSUE TITLE
metav1.Time fails CRD validation

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#86811] opened 2020-01-03 13:03 UTC
**What happened**:

One of my CRD has a metav1.Time field (this is an embedded partial ObjectMeta)

```
// +optional
CreationTimestamp metav1.Time `json:"creationTimestamp,omitempty"`
```

I am using Kubebuilder to generate CRD yaml. So, it generated the following schema:
https://github.com/kubernetes-sigs/controller-tools/blob/a5fa7b956b85a6e792bc7086fedf7107d62452b1/pkg/crd/known_types.go#L34-L37

Now, if the user does not provide the timestamp (which is common in my case), metav1.Time generates `null` in json format.

https://github.com/kubernetes/apimachinery/blob/4d9f99a835264546b4624ab7cbefc29588b1ed3a/pkg/apis/meta/v1/time.go#L144-L147

This is causing CRD validation failure with a following error message:

```
spec.backend.file.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: "null"
```

YAML used:

```
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  replicas: 1
  version: "1.2.3"
  serviceTemplate:
    spec:
      type: NodePort
  backend:
    file:
      path: "/test/data"
      volumeClaimTemplate:
        metadata:
          name: vault-pvc
        spec:
          accessModes: 
          - "ReadWriteOnce"
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi
  unsealer:
    secretShares: 4
    secretThreshold: 2
    mode:
      kubernetesSecret:
        secretName: vault-keys
```

How do we fix this?

**Comment by tamalsaha** [comment] 2020-01-03 13:03
/sig api-machinery
/area custom-resources

cc: @sttts

**Comment by neolit123** [comment] 2020-01-03 22:25
please read this:
https://github.com/kubernetes-sigs/cluster-api/blob/bf790fc2a53614ff5d3405c83c0de0dd3303bb1f/api/v1alpha2/common_types.go#L46-L67

the cluster-api project ended up implementing a custom `ObjectMeta`.

ideally this should be either fixed on the side of metav1 (make the field "nullable"?) or on the side of kube-builider allowing validation overrides.

googling for this problem returns a number of results in other projects too.

**Comment by tamalsaha** [comment] 2020-01-03 22:32
We have for now also removed the creationTimestamp field from our custom OjectMeta.

**Comment by tamalsaha** [comment] 2020-02-18 19:24
@liggitt do you have any thoughts on this issue?

A side question is what is the proper way to add a time field in spec section that is nullable for now?

**Comment by rajathagasthya** [comment] 2020-02-18 20:45
You could make it `*metav1.Time`.

**Comment by liggitt** [comment] 2020-02-19 15:00
The correct local fix is to make the field a pointer, so it can actually be omitted during serialization. However, that adds significant risk of NPE for all callers that currently do not check whether the field is nil. If we did this, I think we would need to add nil-safe implementations of all the current methods on metav1.Time and time.Time that tolerated a nil receiver and behaved like the zero-value currently does.

I also explored a custom serialization of ObjectMeta that would strip a null serialization, but making ObjectMeta implement MarshalJSON also made all types that inline ObjectMeta (which is all types, currently) implement MarshalJSON, which prevented marshaling the rest of their data.

**Comment by tamalsaha** [comment] 2020-02-19 18:49
Also, I want to note that `metav1.MicroTime` has the same issue with `null`.

**Comment by vincent-pli** [comment] 2020-03-20 01:08
@neolit123 
So you means this issue is caused by `controller-tool`?

**Comment by liggitt** [comment] 2021-03-28 17:57
I think this was resolved by https://github.com/kubernetes/kubernetes/pull/95423 in 1.20

@apelisse , can you confirm?

**Comment by neolit123** [comment] 2021-07-23 05:46
ping @apelisse , PTAL above.
/remove-lifecycle frozen

**Comment by apelisse** [comment] 2021-07-23 18:21
Yep, pretty sure that's fixed.

**Closed by apelisse** 2021-07-23 18:21 UTC
Labels: area/custom-resources, kind/bug, sig/api-machinery
