### ISSUE TITLE
DaemonSet e2e test fails in BeforeEach

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#14909] opened 2015-10-01 15:06 UTC
Daemon set e2e tests fail in ```BeforeEach```. As a result ```AfterEach``` is not created and we are leaking namespace, which is not deleted. This causes other tests to fail.

```
05:34:42 Sep 29 05:34:42.549: INFO: failed to update node due to resource version conflict
05:34:47 Sep 29 05:34:47.550: INFO: failed to update node due to resource version conflict
05:34:52 Sep 29 05:34:52.553: INFO: failed to update node due to resource version conflict
05:34:52 Sep 29 05:34:52.555: INFO: failed to update node due to resource version conflict
05:34:52 • Failure in Spec Setup (BeforeEach) [70.048 seconds]
05:34:52 Daemon set
05:34:52 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:60
05:34:52   should launch a daemon pod on every node of the cluster [BeforeEach]
05:34:52   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:59
05:34:52 
05:34:52   Expected error:
05:34:52       <*errors.errorString | 0xc2080b05b0>: {
05:34:52           s: "timed out waiting for the condition",
05:34:52       }
05:34:52       timed out waiting for the condition
05:34:52   not to have occurred
```

See http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flaky/5531/consoleFull for one example

@quinton-hoole 
@kubernetes/goog-control-plane

**Comment by mikedanese** [comment] 2015-10-01 16:17
Thanks for the report.

cc @sttts 

I wonder if it's safe to force update or force patch the labels here.

**Comment by fgrzadkowski** [comment] 2015-10-01 16:18
@mikedanese I assigned you as I though you worked on deamon controller. If that's not the case, feel free to reassign.

**Comment by mikedanese** [comment] 2015-10-01 16:20
@fgrzadkowski I'm probably the right person for this one.

**Comment by sttts** [comment] 2015-10-01 16:32
Let's switch the update to the "force mode" you proposed. But still I would like to know why this get+update fails. 

I had seen pretty high resource versions, increasing very fast. So maybe we have some other regression that is triggered here.

**Comment by sttts** [comment] 2015-10-01 16:33
High = in the thousands with a cluster only a few minutes old.

**Comment by mikedanese** [comment] 2015-10-01 23:59
too frequent nodestatus updates is #14733

**Comment by mikedanese** [comment] 2015-10-02 00:25
Submitted #14915 as a possible fix. The trick is to make the update retry period not a multiple of the node status sync period.

**Comment by davidopp** [comment] 2015-10-02 00:34
BTW node that I also have #14693 in review but I don't think it's related. (Didn't have time to get back to it yet because I was oncall today.)

**Comment by mikedanese** [comment] 2015-10-05 17:44
I believe this particular flake is fixed. Closing this. There are still flakes in DaemonSet but let's track them in #14072.

**Closed by mikedanese** 2015-10-05 17:44 UTC
Labels: kind/flake, priority/P1, team/control-plane
