### ISSUE TITLE
In-tree CSI Plugin leaking gRPC connections

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#64341] opened 2018-05-25 22:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Reported by @cduchesne 
Number of gRPC on CSI Driver continues to climb, until kubelet is restarted.
```
# ss -x src /var/lib/kubelet/plugins/com.csi-driver/csi.sock  | wc
  12483   99864 1697653
```

after restarting kubelet:
```
# ss -x src /var/lib/kubelet/plugins/com.csi-driver/csi.sock  | wc
      6      48     781
```

**What you expected to happen**:
Number of connections to external CSI driver should not continue to grow indefinitely until Kubelet is restarted.

**How to reproduce it (as minimally and precisely as possible)**:
Have Kubernetes perform node operations against a CSI driver. Watch the number of connections continue to grow over time. Watch the number of connections drop when kubelet is restarted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saad-ali** [comment] 2018-05-25 22:18
CC @vladimirvivien @sbezverk @lpabon

**Comment by dims** [comment] 2018-05-25 22:36
/priority important-soon

@saad-ali please adjust as necessary. looks important to me :)

**Comment by sbezverk** [comment] 2018-05-25 22:46
@saad-ali I loaded hostpath csi driver and I do not see any increment in number of GRPCs. Can I get more details how to reproduce it? Which csi driver was used to reproduce the original problem?

**Comment by sbezverk** [comment] 2018-05-25 22:47
```
[root@kube-3 ~]# ss -x src /var/lib/kubelet/plugins/csi-hostpath/csi.sock  | wc
      1       8     101
[root@kube-3 ~]# ss -x src /var/lib/kubelet/plugins/csi-hostpath/csi.sock  | wc
      1       8     101
[root@kube-3 ~]# ss -x src /var/lib/kubelet/plugins/csi-hostpath/csi.sock  | wc
      1       8     101
[root@kube-3 ~]# ss -x src /var/lib/kubelet/plugins/csi-hostpath/csi.sock  | wc
      1       8     101
```

**Comment by sbezverk** [comment] 2018-05-26 15:26
With some help, I reproduced the issue in my test bed. Now I do see that in-tree csi bits establish more grpc sessions than I would expect, debugging why. I will update the thread later..

**Comment by sbezverk** [comment] 2018-05-26 19:50
It appears for each operation of connecting/disconnecting csi provided volume, 4 connections are leaked. Current code does not closes gRPC connection after the operation is completed.

```
May 26 11:50:47 kube-3.sbezverk.cisco.com kubelet[1431]: E0526 11:50:47.746639    1431 csi_plugin.go:111] ><SB> new connection for NewMounter 85fe7b4a-60fc-11e8-90b5-52540043d374 driver: csi-hostpath volume id: 87e493c3-60fc-11e8-9b8a-ba968e9d22b6

May 26 11:50:47 kube-3.sbezverk.cisco.com kubelet[1431]: E0526 11:50:47.748547    1431 csi_attacher.go:278] ><SB> new connection for Attacher's MountDevice driver: csi-hostpath volume id: pvc-7ffb6271-60fc-11e8-90b5-52540043d374

May 26 11:51:37 kube-3.sbezverk.cisco.com kubelet[1431]: E0526 11:51:37.243354    1431 csi_mounter.go:309] ><SB> new connection for mounter's TearDownAt driver: csi-hostpath volume id: 87e493c3-60fc-11e8-9b8a-ba968e9d22b6

May 26 11:51:37 kube-3.sbezverk.cisco.com kubelet[1431]: E0526 11:51:37.346326    1431 csi_attacher.go:479] ><SB> new connection for Attacher's UnmountDevice driver: csi-hostpath mount path: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-7ffb6271-60fc-11e8-90b5-52540043d374/globalmount
``` 

Since we cannot ensure that the same gRPC connection is used by multiple processes, then the solution could be exposing grpc conn in csiClient so the process using this connection could close it on exit.

**Closed** 2018-06-02 10:58 UTC
Labels: kind/bug, milestone/removed, priority/important-soon, sig/storage
