### ISSUE TITLE
kubelet doesn't recreate mirror pods once their static counterparts have terminated

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#29845] opened 2016-08-01 09:52 UTC
In some test runs I noticed that e2e-image-puller images are reported by Kubelet

```
Logging pods the kubelet thinks is on node jenkins-e2e-minion-group-s9i0 before test
Jul 30 05:41:18.754: INFO: elasticsearch-logging-v1-01e37 from kube-system started at 2016-07-30 04:47:01 -0700 PDT (1 container statuses recorded)
Jul 30 05:41:18.754: INFO:  Container elasticsearch-logging ready: true, restart count 0
Jul 30 05:41:18.754: INFO: heapster-v1.1.0-527143062-i41q6 from kube-system started at 2016-07-30 04:47:01 -0700 PDT (4 container statuses recorded)
Jul 30 05:41:18.754: INFO:  Container eventer ready: true, restart count 0
Jul 30 05:41:18.754: INFO:  Container eventer-nanny ready: true, restart count 0
Jul 30 05:41:18.754: INFO:  Container heapster ready: true, restart count 0
Jul 30 05:41:18.754: INFO:  Container heapster-nanny ready: true, restart count 0
Jul 30 05:41:18.754: INFO: e2e-image-puller-jenkins-e2e-minion-group-s9i0 from kube-system started at <nil> (0 container statuses recorded)
Jul 30 05:41:18.754: INFO: kube-proxy-jenkins-e2e-minion-group-s9i0 from kube-system started at <nil> (0 container statuses recorded)
Jul 30 05:41:18.754: INFO: monitoring-influxdb-grafana-v3-0 from kube-system started at 2016-07-30 04:09:29 -0700 PDT (2 container statuses recorded)
Jul 30 05:41:18.754: INFO:  Container grafana ready: true, restart count 0
Jul 30 05:41:18.754: INFO:  Container influxdb ready: true, restart count 0
Jul 30 05:41:18.754: INFO: node-problem-detector-v0.1-77c91 from kube-system started at 2016-07-30 02:31:34 -0700 PDT (1 container statuses recorded)
Jul 30 05:41:18.754: INFO:  Container node-problem-detector ready: true, restart count 0
Jul 30 05:41:18.754: INFO: fluentd-elasticsearch-jenkins-e2e-minion-group-s9i0 from kube-system started at <nil> (0 container statuses recorded)
```

but not listed when reading from API server:

```
Jul 30 05:41:18.692: INFO: Waiting up to 5m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Jul 30 05:41:18.712: INFO: 2 / 2 pods in namespace "kube-system" are in Success state (0 seconds elapsed)
Jul 30 05:41:18.726: INFO: e2e-image-puller-jenkins-e2e-minion-group-b8in in state Succeeded, ignoring
Jul 30 05:41:18.726: INFO: e2e-image-puller-jenkins-e2e-minion-group-lcln in state Succeeded, ignoring
Jul 30 05:41:18.726: INFO: 25 / 27 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
```

I thought that it may be some problem with garbage collector, but there are no interesting logs coming from `pod_gc`. I don't think it's the cause of the failure, or if it can cause problems, but it's certainly unexpected. Assigning to @davidopp for triage.

It can be seen in https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1825/build-log.txt (look for e2e-image-puller-jenkins-e2e-minion-group-s9i0 in e.g. MaxPods test)
cc @kubernetes/sig-node @kubernetes/goog-control-plane

**Comment by hpejustin** [comment] 2016-08-01 15:38
This may happens when the resource usage of the target nod increased after the pod has been scheduled to it.  Kubelet will predict if the pod should be run via canAdmitPod functions, among all the predicts functions, one is about resource which name is PodFitsResources. This function is also the function which was used by the  scheduler to determine if the pod resource request can be accept.

**Comment by gmarek** [comment] 2016-08-01 16:49
@hpejustin - I don't understand what you just wrote. We shouldn't have too long time with this inconsistency and it should be only in the other direction (API server know, Kubelet not yet).

**Comment by gmarek** [comment] 2016-08-05 13:26
This caused failure of MaxPods https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1825, so it seems like a real thing. @dchen1107 @davidopp

**Comment by gmarek** [comment] 2016-08-08 14:52
To make it clearer:
- kubelet reports `e2e-image-puller-jenkins-e2e-minion-group-s9i0` pod
- api server does not list it (as can be seen by the log about 'success states'), if it were visible it would be listed there no matter what state it is. 

By looking at logs what happened is:
- during `recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster` test Node was unreachable and NodeController evicted all Pods on the Node and deleted them with `deletionOptions = 0` (meaning: delete it from API server without waiting for Kubelet's ack)
```
I0730 11:09:27.783115       5 handlers.go:164] DELETE /api/v1/namespaces/kube-system/pods/kube-proxy-jenkins-e2e-minion-group-s9i0: (22.832268ms) 200 [[kube-controller-manager/v1.4.0 (linux/amd64) kubernetes/f0fa9e5/node-controller] 127.0.0.1:51814]
```
- kubelet reconnected the cluster tried getting the Pod, receiving each time 404 (correctly from the API server perspectiv, I don't know Kubelet's logic well enough, but it seems reasonable)
```
I0730 11:09:28.407309       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/kube-proxy-jenkins-e2e-minion-group-s9i0: (1.194672ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36265]
```
- kubelet issued the delete request as well:
```
I0730 11:09:29.405806       5 handlers.go:164] DELETE /api/v1/namespaces/kube-system/pods/kube-proxy-jenkins-e2e-minion-group-s9i0: (1.533697ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:38709]
```
- kubelet issued Get request, tried to update PodStatus and for some reason succeeded:
```
I0730 11:09:38.409731       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/kube-proxy-jenkins-e2e-minion-group-s9i0: (1.369576ms) 200 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36256]
I0730 11:09:38.420207       5 handlers.go:164] PUT /api/v1/namespaces/kube-system/pods/kube-proxy-jenkins-e2e-minion-group-s9i0/status: (9.472712ms) 200 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36256]
```

That's everything there is in the API server logs. cc @dchen1107 @yujuhong @lavalamp @smarterclayton

**Comment by yujuhong** [comment] 2016-08-08 17:40
kubelet would try to create the mirror pod for kube-proxy since it was actually running on the node after reconnecting with the apiserver. It probably created this pod in one of the following two requests.
```
I0730 11:09:29.419020       5 handlers.go:164] POST /api/v1/namespaces/kube-system/pods: (9.758814ms) 201 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:38709]
I0730 11:09:29.419520       5 handlers.go:164] POST /api/v1/namespaces/kube-system/pods: (7.68156ms) 201 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:38705]
```
I don't see any problem with that. Kubelet needs sometime to report the static pods running on the node after a disruptive test. If scheduler tries to schedule any pods during this window, it may not get the correct usage of the node.

**Comment by gmarek** [comment] 2016-08-08 17:48
ugh - sorry, I pasted wrong pod. It was supposed to be image puller. Sorry for that.

**Comment by dchen1107** [comment] 2016-08-08 19:35
@gmarek I didn't look into the detail of the issue, but here is what I believe:

image-puller is designed to be fire-and-forget pod for our test infrastructure initially, which means its restart policy is never, not always. Once it succeeded, our pod garbage collector will remove it. I don't think kubelet does anything wrong here.

**Comment by yujuhong** [comment] 2016-08-08 20:05
> ugh - sorry, I pasted wrong pod. It was supposed to be image puller. Sorry for that.


apiserver log:
```
I0730 11:08:53.494464       5 handlers.go:164] DELETE /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (31.897732ms) 200 [[kube-controller-manager/v1.4.0 (linux/amd64) kubernetes/f0fa9e5/node-controller] 127.0.0.1:51700]
I0730 11:09:38.407665       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.818941ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36256]
I0730 11:09:48.407122       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.371032ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36256]
I0730 11:09:58.408072       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.295131ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:08.406967       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.172657ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:18.406852       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.10485ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:28.407138       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.331218ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:38.407308       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.133701ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:48.407459       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.506063ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:10:58.407326       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.223315ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:08.407438       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.13601ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:18.406859       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (961.966µs) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:28.406521       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (779.179µs) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:38.406800       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (977.136µs) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:48.406620       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.082702ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:11:58.406820       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.066936ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:08.406198       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.025484ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:18.406282       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.16833ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:28.406073       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.167596ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:38.405907       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.223735ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:48.405936       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.32098ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:12:58.405671       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.334019ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:13:08.405193       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.094025ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:13:18.405373       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.13493ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:13:28.405681       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (1.553282ms) 404 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
I0730 11:13:38.541279       5 handlers.go:164] GET /api/v1/namespaces/kube-system/pods/e2e-image-puller-jenkins-e2e-minion-group-s9i0: (137.445507ms) 200 [[kubelet/v1.4.0 (linux/amd64) kubernetes/f0fa9e5] 10.240.0.4:36255]
```

controller-manager log:
```
I0730 11:04:28.620256       5 controller_utils.go:214] Updating ready status of pod e2e-image-puller-jenkins-e2e-minion-group-s9i0 to false
I0730 11:08:53.460997       5 controller_utils.go:98] Starting deletion of pod e2e-image-puller-jenkins-e2e-minion-group-s9i0
I0730 11:08:53.462902       5 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"e2e-image-puller-jenkins-e2e-minion-group-s9i0", UID:"680aa329-5638-11e6-961e-42010af00002", APIVersion:"v1", ResourceVersion:"11
032", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod e2e-image-puller-jenkins-e2e-minion-group-s9i0 from Node jenkins-e2e-minion-group-s9i0
```

The image puller pod got deleted (evicted by the node controller) around 11:08:53. After that, all the GET requests returned 404. Between 11:13:28 and 11:13:38, *something* recreated the image puller pod. I guess it could be kubelet that recreated the pod, but I can't find any POST in the apiserver log during that window of time, and the apiserver log was full of (potentially unrelated?) errors during that period:
```
E0730 11:13:36.920888       5 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```
The kubelet.log during the same window was also not included in the artifacts. If there were some other disruptive tests during that window (I didn't check), it'd make sense. It'd be good to figure out whether the inconsistency was caused by all sorts of disruptive tests, and whether there was enough time for kubelet recover. Of course, we can also reconsider (again) moving some of the scheduler tests to a more controlled environement (integration test?).

**Comment by gmarek** [comment] 2016-08-08 20:50
Well - moving tests is one thing (I don't have time to do it, but if you want I can review changes), but fixing the problem is another. I don't think that flakyness ratio caused by this is a problem (probably around 1%), so I'd rather not move this test to some other environment because of it - it caught up way too many bugs already.

No disruptive tests should be running in the same time, as it's a serial suite. @ixdy

**Comment by yujuhong** [comment] 2016-08-08 22:58
After pods being evicted, (I think) kubelet didn't recreate the mirror pod for image-puller immediately. It could be that kubelet looked a the dead containers and figured the pod didn't need to be restarted, updated the pod status internally, but didn't know (or simply stopped syncing) that it needed to to recreate the mirror pod. The kubelet.log wasn't collected before the daemon restart, so this is just one theory. @Random-Liu, does this make sense to you?

**Comment by gmarek** [comment] 2016-08-09 07:32
@ixdy - do you know why we might not have logs?

**Comment by yujuhong** [comment] 2016-08-09 19:17
Discussed with @Random-Liu offline. Once the static pod has terminated, kubelet will stop syncing it. This means that if someone deletes the mirror pod, kubelet wouldn't try to recreate it at all.
We could potentially patch kubelet to ensure mirror pods are created, but this would mean another special case for mirror/static pods. I think we need some justification of whether this is worth it before committing to the work. 

@gmarek was this the main cause of test failure, or merely an annoyance that showed up as inconsistency in the build.log? 
I don't think an extra "terminated" pod on the node that scheduler is not aware of should cause any issue.

**Comment by gmarek** [comment] 2016-08-09 20:12
Just an annoyance.

**Comment by gmarek** [comment] 2016-08-09 20:13
It's good that it's nothing serious, though I think that we shouldn't have such inconsistence. I.e. all components should be eventually consistent with what API server thinks.

**Comment by yujuhong** [comment] 2016-08-09 20:18
> It's good that it's nothing serious, though I think that we shouldn't have such inconsistence. I.e. all components should be eventually consistent with what API server thinks.

Agreed. Lowered the priority to p2.

**Comment by gjkim42** [comment] 2021-06-24 14:54
I think this issue has been resolved by https://github.com/kubernetes/kubernetes/pull/32232.

@Random-Liu @yujuhong 
Please reopen this if I am wrong.

/close

**Closed** 2021-06-24 14:54 UTC
Labels: kind/bug, lifecycle/frozen, priority/backlog, sig/node
