### ISSUE TITLE
[Failing test] Unit: FAIL k8s.io/kubernetes/pkg/api/testing

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#102887] opened 2021-06-15 18:56 UTC
##### Error text:
```
FAIL	k8s.io/kubernetes/pkg/api/testing	170.401s

```
#### Recent failures:
[6/15/2021, 8:16:38 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102431/pull-kubernetes-unit/1404819768589946880)
[6/15/2021, 7:15:11 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102873/pull-kubernetes-unit/1404804310688075776)
[6/15/2021, 7:00:17 AM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1404800414800416768)
[6/15/2021, 6:57:13 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102431/pull-kubernetes-unit/1404799778147012608)
[6/15/2021, 6:03:12 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99310/pull-kubernetes-unit/1404786200572596224)

/kind failing-test

Not sure if flake. Gubernator is showing a big spike in failures that started 06/14 around 10:00 ~UTC~ PT.

This seems to be when https://github.com/kubernetes/test-infra/pull/22537 merged.

Failed on my PR: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102821/pull-kubernetes-unit/1404864600213557248

/sig testing

**Comment by BenTheElder** [comment] 2021-06-15 19:27
filed https://github.com/kubernetes/kubernetes/pull/102888

I'm hesistant to bump it all the way back to 240, if you follow back the original PR / issue trail I ran a number of iterations of testing and it really shouldn't take 240s. four minutes is ludicrous for unit testing one package.

**Comment by BenTheElder** [comment] 2021-06-15 19:30
there are 39 failures in the last day in `pull-kubernetes-unit` from `k8s.io/kubernetes/pkg/api/testing TestMain` timeout :/
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=unit#bf11e79583121ff73ec4
/priority critical-urgent

**Comment by lavalamp** [comment] 2021-06-15 23:33
Did any timed-out run produce any logs?

**Comment by BenTheElder** [comment] 2021-06-15 23:35
we capture the test logs but `TestMain` itself doesn't appear to have any.

**Comment by BenTheElder** [comment] 2021-06-15 23:37
e.g. at random:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/1404843241420886016 
=> "raw build-log.txt" =>
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/1404843241420886016/build-log.txt

I'm not sure this code emits any when it fails.

**Comment by lavalamp** [comment] 2021-06-15 23:44
Likely it's timing out on some step, but I would have expected *some* logging from something related -- I was just going to look at the last thing logged and figure that something after that must be the culprit.

Does that log capture stderr and stdout of the test invocations?

**Comment by BenTheElder** [comment] 2021-06-15 23:51
it should, e.g. see a different kind of failure with logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102437/pull-kubernetes-unit/1404519021017042944

we're running with json output formatting then through [gotestsum](https://github.com/gotestyourself/gotestsum) to junit, and prow will capture stdout/stderr of whatever is running within the job as build-log.txt

**Comment by BenTheElder** [comment] 2021-06-16 00:08
reopening to keep an eye on this.

**Comment by BenTheElder** [comment] 2021-06-16 05:10
sigh: 
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102900/pull-kubernetes-unit/1404991522742472704
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102897/pull-kubernetes-unit/1404994908871200768

180s

**Comment by BenTheElder** [comment] 2021-06-16 05:58
it's doing better (all recent runs passed, looks like 3 flakes due to this since the PR merged this afternoon) but we may still want to bump it again
https://prow.k8s.io/?job=pull-kubernetes-unit
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=unit%24&test=k8s.io%2Fkubernetes%2Fpkg%2Fapi%2Ftesting%20TestMain#bf11e79583121ff73ec4

**Comment by BenTheElder** [comment] 2021-06-16 06:43
We're at 100% pass rate the past 3 hours but CI is not very active right now. still just 3 fails.

If we have a similar rate tomorrow morning I'd opt for a small bump (maybe 180s -> 190s) to cover remaining limited flakes still over going all the way back to 4 minutes.

**Comment by lavalamp** [comment] 2021-06-16 15:29
If we knew which sub test was slow when it is slow, that would possibly narrow it down to a haystack small enough to look for needles in.

**Comment by BenTheElder** [comment] 2021-06-16 17:51
@liggitt dug into it locally, https://kubernetes.slack.com/archives/C09QZ4DQB/p1623860506164900

follow up in: https://github.com/kubernetes/kubernetes/pull/102924

**Comment by BenTheElder** [comment] 2021-06-16 19:53
Fairly confident this is now fixed after https://github.com/kubernetes/kubernetes/pull/102924

**Comment by liggitt** [comment] 2021-06-16 22:28
closing as fixed by https://github.com/kubernetes/kubernetes/pull/102924

**Closed by liggitt** 2021-06-16 22:28 UTC
Labels: kind/failing-test, lifecycle/active, priority/critical-urgent, priority/important-soon, sig/api-machinery, sig/testing, triage/accepted

**Comment by BenTheElder** [comment] 2021-06-16 23:20
confirmed https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=unit%24&test=k8s.io%2Fkubernetes%2Fpkg%2Fapi%2Ftesting%20TestMain

**Comment by pacoxu** [comment] 2021-06-17 06:29
```
FAIL	k8s.io/kubernetes/pkg/api/testing	180.422s
```
example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1405195070969221120

**Comment by BenTheElder** [comment] 2021-06-17 06:32
@pacoxu that run happened at `2021-06-16 16:07:56 +0000 UTC`
the fix merged at `2021-06-16T19:48:50Z` https://github.com/kubernetes/kubernetes/pull/102924#event-4900066110

**Comment by pacoxu** [comment] 2021-06-17 07:22
😯 

👌
