### ISSUE TITLE
Record events for entity status changes in apiserver

### ISSUE THREAD

**Issue by simon3z** [kubernetes/kubernetes#6280] opened 2015-04-01 08:36 UTC
Some events like: pod status changes (pending/running/failed), node status changes (ready/schedulable), etc. can be recorded with more consistency by the apiserver (instead of spreading the logic and the messages across different components).

Pros:
- status changes are always logged (even when code changes in other components)
- it's easier to create the correct transaction (see #6055)

Cons:
- we lose the ability to identify the actor who made the change (anyway this is not preventing the components to log or record their own messages)
- apiserver will probably have to read, compare old and new and generate the events (I don't think that apiserver is now reading the entities)

@vmarmol any insight about this possible change?

**Comment by erictune** [comment] 2015-04-01 18:31
We want people to be able to build extensions to kubernetes that affect the lifecycles of pods and nodes. Those extensions need to send their own events about what they are doing with pods and nodes, etc.   We want people to be able to add extensions without having to  modify the apiserver itself.
Therefore, event generation needs to be in the responsible components.

**Comment by erictune** [comment] 2015-04-01 18:47
Also, reliably logging status changes sounds nice, but a lot of us thing it is not a good idea.  Our experience has been that components in a distributed system need to be "level-triggered", not "edge-triggered".  In other words, they need to act on the current state, not on state changes.   Trying to generate events for edges would encourage what we think is a bad practice.

It isn't practical to ensure that components in a distributed system reliably see all state changes in a timely fashion.  Sometimes this is phrased as "exactly once semantics" are impossible.  In kubernetes, we opted for "at-most once".  Doing "at-least once" means keeping a really long history of events.  We don't have space for that many events.

**Comment by simon3z** [comment] 2015-04-01 20:57
> Therefore, event generation needs to be in the responsible components.

@erictune I don't want to take away the ability for components to record events. On the contrary I want people to create components and not care about recording the most trivial events. For example if you're writing a component that is changing the Node status to not-ready or not-schedulable I don't want your component to be responsible to also record events about that but I want apiserver to automatically record them.

Other additional and more specific events will be left to the component to be recorded.

> Our experience has been that components in a distributed system need to be "level-triggered", not "edge-triggered". In other words, they need to act on the current state, not on state changes. Trying to generate events for edges would encourage what we think is a bad practice.

Aren't watches allowing "edge-triggered" components?

**Comment by erictune** [comment] 2015-04-01 21:11
Watches do use "edge-triggered" as an optimization, but any watch client also has to be able to tolerate a drops in to the watch connection.  When a drop happens, the client may have missed events, and has to restart from just the current states ("levels").  To encourage people to think about this, we enforce frequent resets.

**Comment by smarterclayton** [comment] 2017-06-01 17:28
Dupe of both #3692 and the wait command.

**Closed by smarterclayton** 2017-06-01 17:28 UTC
Labels: area/apiserver, kind/design, priority/awaiting-more-evidence, sig/api-machinery
