### ISSUE TITLE
CI hides test-cmd.sh failures

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#17579] opened 2015-11-20 19:25 UTC
When `test-cmd.sh` fails, you see output like "2362 tests run, 8 skipped, 0 failed." in the github box and no external link to details.  

@kubernetes/rh-cluster-infra Can you find the right people for this?  It makes it hard for less frequent contributors.

**Comment by ncdc** [comment] 2015-11-20 19:26
cc @ixdy

**Comment by ixdy** [comment] 2015-11-20 19:50
This is basically a dupe of #17443. There are instructions in https://github.com/kubernetes/kubernetes/issues/17443#issuecomment-157837780 of how to get to the logs, but I know it's painful right now.

**Closed** 2015-11-20 19:51 UTC
