### ISSUE TITLE
e2e flake: `Load capacity [Feature:Performance] should be able to handle 30 pods per node`

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#22324] opened 2016-03-02 00:28 UTC
The e2e test `Load capacity [Feature:Performance] should be able to handle 30 pods per node` fails frequently in the scalability test suite with the error: `/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:144 There should be no high-latency requests Expected : 1 not to be > : 0`

Recent failures:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4961/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4954/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4949/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4916/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4891/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4841/

**Comment by saad-ali** [comment] 2016-03-02 02:03
Another one:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4969/

**Comment by davidopp** [comment] 2016-03-02 05:44
@wojtek-t

**Comment by wojtek-t** [comment] 2016-03-02 07:29
Closing as duplicate of #22340 - this is exactly the same

**Closed by wojtek-t** 2016-03-02 07:29 UTC
Labels: kind/flake, priority/P0, team/control-plane
