### ISSUE TITLE
loadBalancerSourceRanges does not work on Windows

### ISSUE THREAD

**Issue by AbelHu** [kubernetes/kubernetes#120033] opened 2023-08-18 03:00 UTC
### What happened?

Pod CIDR should be added to loadBalancerSourceRanges if there are Pods needing to access the service's LoadBalancer IP for clusters with version v1.25 or above. It will block Linux pods to access the load balancer if the pod CIDR is not added but it will not block Windows pods.

### What did you expect to happen?

Block Windows pods to access the load balancer if the pod CIDR is not added.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a cluster with k8s v1.25.6
2. Create a service with setting loadBalancerSourceRanges which do not include pod cidr
3. Access the service from a Windows pod
4. The access can succeed

### Anything else we need to know?

From the context in [Don't use KUBE-MARK-DROP for LoadBalancerSourceRanges by danwinship · Pull Request #110289 · kubernetes/kubernetes (github.com)](https://github.com/kubernetes/kubernetes/pull/110289) and [Service.Spec.LoadBalancerSourceRanges intent? · Issue #109575 · kubernetes/kubernetes (github.com)](https://github.com/kubernetes/kubernetes/issues/109575), it seems like that it only be implemented on Linux.

### Kubernetes version

1.25.6

### Cloud provider

AKS

### OS version

# On Windows:
10.0.17763.4499

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by daschott** [comment] 2023-08-22 18:25
Yes, I don't think this field is supported on Windows today. +@princepereira as well for confirmation.

**Comment by thockin** [comment] 2023-09-14 16:48
Looking for an update on this, please.

**Comment by jayunit100** [comment] 2023-09-14 17:23
Pretty sure this isn't supported and also we don't test it at all .... I'll confirm

**Comment by jayunit100** [comment] 2023-09-14 18:06
Yeah, confirmed its not implemented in the windows kernel proxy, at least, not as far as i can tell....  

## In the iptables impl, they use CIDR matching in the rules to do this .
In the iptables proxy: you can generally grok how this all works... (inside of the `syncProxyRules` .... 
 
```
allowFromNode := false
			for _, src := range svcInfo.LoadBalancerSourceRanges() {
				// 1) allow traffic from IP's matching this CIDR
				natRules.Write(args, "-s", src, "-j", string(externalTrafficChain))
```
) 

## I dont think we CAN do this in the windows, HNS based proxy? 

To my knowledge the HNS API Doesnt allow any kind of firewall / packet filtering functionality to do this, so we cant implement it easily i think in the windows kernel proxy.

@daschott to confirm?

**Comment by jayunit100** [comment] 2023-09-15 07:16
cc @pramitagautam  @tzifudzi for op-readiness we should doc this

**Comment by daschott** [comment] 2023-09-16 18:27
Hi, the load balancer source ranges is not implemented for Windows... I have not looked at this in detail yet and am not familiar with the feature. 

But HNS does have an ACL policy to allow/deny traffic based on CIDR, would that be suitable?

**Comment by jayunit100** [comment] 2023-09-18 10:07
sgtm, at least for now we can leave this bug open. will discuss in sig-windows this wk.

**Comment by jayunit100** [comment] 2023-09-26 17:26
we'll leave this open. nobody on it yet though.  we think we can impl it w/ the HNS HCLs....

**Comment by thockin** [comment] 2024-01-31 00:59
@MikeZappa87

**Comment by MikeZappa87** [comment] 2024-01-31 01:19
@jayunit100 did this ever get discussed at sig-windows? This issue might have fallen off the wagon. I didn't join sig-windows, do we triage at that meeting?

**Comment by jayunit100** [comment] 2024-01-31 05:12
On one hand we , there is hope for this bc iirc we dug around and looked at the HNS parts and it does appear you could use windows firewall rules to implement some kind of lb source ranges functionality.


... but maybe on the other hand we should leave this as a wontfix.... bc lbsourceranges needs to silently just go away?..... I think some folks  ( @thockin ?) warned us about 6 years ago tho that lbSourceRanges was approaching firewall territory and should
Probably be reconsidered.

**Comment by thockin** [comment] 2024-01-31 18:21
It is borderline firewall BUT it's sort of expected to work, IMO

**Comment by MikeZappa87** [comment] 2024-01-31 18:45
Is this one of these cases where we have tests for this feature for Linux and they are not run on Windows nodes?

**Comment by jayunit100** [comment] 2024-02-04 11:12
1. you can't really test LB source ranges easily at all because of the fact that I think we only test them for GCE

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/providers/gce/firewall.go , 

and I assume that test will go away once we impl the cloud provider migration?

2. Previous issues discussions have concluded I believe that this feature it at cloud provider discretion and may not work, where we interpret cloud provider as "the person setting up the cluster".... which means 

So I'd propose:

"The administrator may know that their windows nodes don't support lb src ranges.... and in that case... the fact that they are not supported is a normal scenario".
 

1) To me that makes a case that this is a **documentation** issue - and maybe a feature request.... but It could go either way.

2) Either way if this is cross platform  we need a cross platform non cloud provider specific test for it as well since cloud provider tests going away.

**Comment by MikeZappa87** [comment] 2024-02-15 17:13
@AbelHu what should we do with this issue? Not sure if I clear path forward exists.

**Closed** 2024-04-15 17:34 UTC
Labels: kind/bug, sig/network, sig/windows, lifecycle/rotten, needs-triage
