### ISSUE TITLE
Flake in ./hack/test-cmd.sh, too few cassandra labels

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#24453] opened 2016-04-19 06:02 UTC
```
21:11:50 FAIL!
21:11:50 Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
21:11:50   Expected: cassandra:cassandra:cassandra:cassandra:
21:11:50   Got:      cassandra:cassandra:
21:11:50 (B
21:11:50 1727 ./hack/test-cmd.sh
21:11:50 (B
```
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/11039/

**Comment by mikedanese** [comment] 2016-04-19 16:02
And again http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/11052/

cc @caesarxuchao @kuberentes/kubectl

**Comment by caesarxuchao** [comment] 2016-04-19 17:04
Last time this test was reported as flaky is #22128, but they seem to be irrelevant.

**Comment by bgrant0607** [comment] 2016-05-03 16:31
Dupe of #24704

**Closed by bgrant0607** 2016-05-03 16:31 UTC
Labels: kind/flake, priority/P1, team/CSI-API Machinery SIG
