### ISSUE TITLE
kubectl: multiple issues of -l/--selector overwrites previous ones

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#55508] opened 2017-11-10 21:20 UTC
Currently if a user specifies multiple `-l` (`--selector`) flags,  only the last one is used and the rest is ignored silently.

Repro steps:

1. `kubectl get pods -l foo=bar -l foo2=bar2 -v=10`
2. Logs show: `GET https://IP-ADDRESS/api/v1/namespaces/default/pods?labelSelector=foo2%3Dbar2`
3. Results bring pods that match `foo2=bar2` selector. `foo=bar` is ignored.

This is unintuitive behavior. We should ideally fail the command saying multiple uses of this flag is not allowed, or combine them with an AND operator and include all selectors specified in the actual query.

Currently, the -l/--selector flag's help message actually makes it clear that usage format is `-l key1=value1,key2=value2`, however I think specifying multiple instances of this flag should error out, instead of being silently ignored.

Similarly `kubectl run hello -l app=hello -l foo=quux --image=nginx` will only create Pod labeled `foo=quux`,  and the `app=hello` option is **ignored**.

/kind bug
/sig cli
kubectl 1.8.2

**Comment by dixudx** [comment] 2017-11-12 14:23
@ahmetb Actually this is not a bug of Kubernetes.

I've already submitted a feature PR to spf13/pflag to enable this scenario.

@kubernetes/sig-cli-misc

**Comment by shiywang** [comment] 2017-11-13 06:11
> prompt multiple flag is not allowed

Agree with @dixudx it should be fixed in spf13, if it's hard to fix in upstream, we can add a warning in help message I think ?

**Closed** 2018-04-13 00:14 UTC
Labels: kind/bug, lifecycle/rotten, sig/cli
