### ISSUE TITLE
Build Failing While Cutting release-1.5 branch with "rsync: could not open password file"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#36000] opened 2016-11-01 20:41 UTC
I'm using anago to cut a `release-1.5` branch and deploy a `v1.5.0-beta.0`. However, it fails with `rsync: could not open password file`.

Detailed error from `anago.log`:
```
────────────────────────────────────────────────────────────────────────────────
anago::common::stepheader(): TAG AND BUILD v1.5.0-beta.0
────────────────────────────────────────────────────────────────────────────────

anago::prepare_tree(): Checking out release-1.5: 
anago::prepare_tree(): git checkout -B release-1.5
Switched to a new branch 'release-1.5'
OK
anago::rev_version_base(): Updating pkg/version/base.go to v1.5.0-beta.0...
anago::rev_version_base(): Formatting pkg/version/base.go: 
anago::rev_version_base(): gofmt -s -w pkg/version/base.go
OK

anago::rev_version_base(): git add pkg/version/base.go
anago::rev_version_base(): Committing pkg/version/base.go: 
anago::rev_version_base(): git commit -m Kubernetes version v1.5.0-beta.0
[release-1.5 b1f0866] Kubernetes version v1.5.0-beta.0
 1 file changed, 3 insertions(+), 3 deletions(-)
OK
anago::prepare_tree(): Tagging Kubernetes beta release v1.5.0-beta.0 on release-1.5: 
anago::prepare_tree(): git tag -a -m Kubernetes beta release v1.5.0-beta.0 v1.5.0-beta.0
OK
anago::common::runstep(): >>>>>>>> anago::prepare_tree() finished in 1s

anago::build_tree(): Building Kubernetes v1.5.0-beta.0 on release-1.5: 
anago::build_tree(): make release
+++ [1101 12:41:03] Verifying Prerequisites....
+++ [1101 12:41:05] Syncing sources to container
rsync: could not open password file /usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/images/kube-build:build-1b266a1658-4-v1.7.1-2/rsyncd.password: No such file or directory (2)
rsync error: syntax or usage error (code 1) at authenticate.c(187) [sender=3.1.0]
make: *** [release] Error 1
FAILED
```

What I've tried so far:
* Ran anago 3 different times, it selected 3 different builds, all failed with this error.
* Stopped/removed all running docker containers, and deleted all docker images before the third attempt, and still ran into the same issue.
* `make clean` followed by `make quick-release` on my sync'd k8s repo completes successfully.

CC @david-mcmahon @ixdy @jbeda @kubernetes/test-infra-admins

**Comment by jbeda** [comment] 2016-11-01 20:54
I'm at an offsite today and won't be able to help debug until later. I'd
run the make separately with more debugging output and see how/why they
file isn't being created.
On Tue, Nov 1, 2016 at 1:42 PM Saad Ali <notifications@github.com> wrote:

I'm using anago to cut a release-1.5 branch and deploy a v1.5.0-beta.0.
However, it fails with rsync: could not open password file.

Detailed error from anago.log:

────────────────────────────────────────────────────────────────────────────────
anago::common::stepheader(): TAG AND BUILD v1.5.0-beta.0
────────────────────────────────────────────────────────────────────────────────

anago::prepare_tree(): Checking out release-1.5:
anago::prepare_tree(): git checkout -B release-1.5
Switched to a new branch 'release-1.5'
OK
anago::rev_version_base(): Updating pkg/version/base.go to v1.5.0-beta.0...
anago::rev_version_base(): Formatting pkg/version/base.go:
anago::rev_version_base(): gofmt -s -w pkg/version/base.go
OK

anago::rev_version_base(): git add pkg/version/base.go
anago::rev_version_base(): Committing pkg/version/base.go:
anago::rev_version_base(): git commit -m Kubernetes version v1.5.0-beta.0
[release-1.5 b1f0866] Kubernetes version v1.5.0-beta.0
 1 file changed, 3 insertions(+), 3 deletions(-)
OK
anago::prepare_tree(): Tagging Kubernetes beta release v1.5.0-beta.0
on release-1.5:
anago::prepare_tree(): git tag -a -m Kubernetes beta release
v1.5.0-beta.0 v1.5.0-beta.0
OK
anago::common::runstep(): >>>>>>>> anago::prepare_tree() finished in 1s

anago::build_tree(): Building Kubernetes v1.5.0-beta.0 on release-1.5:
anago::build_tree(): make release
+++ [1101 12:41:03] Verifying Prerequisites....
+++ [1101 12:41:05] Syncing sources to container
rsync: could not open password file
/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/images/kube-build:build-1b266a1658-4-v1.7.1-2/rsyncd.password:
No such file or directory (2)
rsync error: syntax or usage error (code 1) at authenticate.c(187)
[sender=3.1.0]
make: *** [release] Error 1
FAILED

What I've tried so far:

   - Ran anago 3 different times, it selected 3 different builds, all
   failed with this error.
   - Stopped/removed all running docker containers, and deleted all docker
   images before the third attempt, and still ran into the same issue.
   - make clean followed by make quick-release on my sync'd k8s repo
   completes successfully.

CC @david-mcmahon <https://github.com/david-mcmahon> @ixdy
<https://github.com/ixdy> @jbeda <https://github.com/jbeda>
@kubernetes/test-infra-admins
<https://github.com/orgs/kubernetes/teams/test-infra-admins>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36000>, or mute the thread

**Comment by ixdy** [comment] 2016-11-01 21:15
@saad-ali what happens when you cd into `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes` and run `make release`?

**Comment by ixdy** [comment] 2016-11-01 21:16
can you paste the output of `docker version`?

**Comment by saad-ali** [comment] 2016-11-01 21:26
To clarify, the `v1.6.0-alpha.0` build completes without issue, only the `v1.5.0-beta.0` build fails:
```
────────────────────────────────────────────────────────────────────────────────
TAG AND BUILD v1.6.0-alpha.0
────────────────────────────────────────────────────────────────────────────────

Checking out master: OK
Tagging Kubernetes alpha release v1.6.0-alpha.0 on master: OK
>>>>>>>> anago::prepare_tree() finished in 0s

Building Kubernetes v1.6.0-alpha.0 on master: OK
Moving build _output to /usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output-v1.6.0-alpha.0: OK
>>>>>>>> anago::build_tree() finished in 51m8s

────────────────────────────────────────────────────────────────────────────────
TAG AND BUILD v1.5.0-beta.0
────────────────────────────────────────────────────────────────────────────────

Checking out release-1.5: OK
Updating pkg/version/base.go to v1.5.0-beta.0...
Formatting pkg/version/base.go: OK
Committing pkg/version/base.go: OK
Tagging Kubernetes beta release v1.5.0-beta.0 on release-1.5: OK
>>>>>>>> anago::prepare_tree() finished in 1s

Building Kubernetes v1.5.0-beta.0 on release-1.5: FAILED
Copying /tmp/anago.log to /usr/local/google/saadali/anago-v1.5.0-beta.0: OK

anago: DONE main on saadali-dev Tue Nov  1 12:41:06 PDT 2016 in 1h10s
```

It fails with:
```
────────────────────────────────────────────────────────────────────────────────
anago::common::stepheader(): TAG AND BUILD v1.5.0-beta.0
────────────────────────────────────────────────────────────────────────────────

anago::prepare_tree(): Checking out release-1.5: 
anago::prepare_tree(): git checkout -B release-1.5
Switched to a new branch 'release-1.5'
OK
anago::rev_version_base(): Updating pkg/version/base.go to v1.5.0-beta.0...
anago::rev_version_base(): Formatting pkg/version/base.go: 
anago::rev_version_base(): gofmt -s -w pkg/version/base.go
OK

anago::rev_version_base(): git add pkg/version/base.go
anago::rev_version_base(): Committing pkg/version/base.go: 
anago::rev_version_base(): git commit -m Kubernetes version v1.5.0-beta.0
[release-1.5 b1f0866] Kubernetes version v1.5.0-beta.0
 1 file changed, 3 insertions(+), 3 deletions(-)
OK
anago::prepare_tree(): Tagging Kubernetes beta release v1.5.0-beta.0 on release-1.5: 
anago::prepare_tree(): git tag -a -m Kubernetes beta release v1.5.0-beta.0 v1.5.0-beta.0
OK
anago::common::runstep(): >>>>>>>> anago::prepare_tree() finished in 1s

anago::build_tree(): Building Kubernetes v1.5.0-beta.0 on release-1.5: 
anago::build_tree(): make release
+++ [1101 12:41:03] Verifying Prerequisites....
+++ [1101 12:41:05] Syncing sources to container
rsync: could not open password file /usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/images/kube-build:build-1b266a1658-4-v1.7.1-2/rsyncd.password: No such file or directory (2)
rsync error: syntax or usage error (code 1) at authenticate.c(187) [sender=3.1.0]
make: *** [release] Error 1
FAILED
```

**To answer your questions:**

> can you paste the output of `docker version`?

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

> @saad-ali what happens when you cd into `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes` and run `make release`?

* Only the directory `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output-v1.6.0-alpha.0/` exists.
* The directory `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/` (which is what the build step seems to be looking for when it fails), *does not exist*.

I will run `make release` in `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes` and report back.

**Comment by saad-ali** [comment] 2016-11-01 21:28
> I will run `make release` in `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes` and report back.

It fails with the same error:

```
$ make release
+++ [1101 14:27:21] Verifying Prerequisites....
+++ [1101 14:27:22] Syncing sources to container
rsync: could not open password file /usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/images/kube-build:build-1b266a1658-4-v1.7.1-2/rsyncd.password: No such file or directory (2)
rsync error: syntax or usage error (code 1) at authenticate.c(187) [sender=3.1.0]
make: *** [release] Error 1
```

Which makes sense since the directory `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes/_output/` does not exist.

**Comment by david-mcmahon** [comment] 2016-11-01 21:44
Ah I missed that.  Then this is due to something we're doing in anago.  In order to take advantage of multiple build trees, we build into _output [because we have to](https://github.com/kubernetes/kubernetes/issues/23839) and then mv it to a unique (versioned) name and build the next set of binaries from the same tree.

Unfortunately, the build scripts do not honor a single build directory throughout and it's hardcoded everywhere.  The bug linked above details this.   

This latest bug is another example of hardcoding the build directory.  I'm not sure the best way to deal with this (yet).

**Comment by ixdy** [comment] 2016-11-01 22:01
Ah, I think I understand what's happening then.

The assumptions that `kube::build::build_image` makes are invalid, because the build image still exists but the `$LOCAL_OUTPUT_BUILD_CONTEXT` directory (which is under `_output`) has been moved.

Probably doing a `make clean` between builds in the same tree would fix this issue.

**Comment by saad-ali** [comment] 2016-11-01 22:41
Doing a `make clean` before `make release` in `/usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes` seems to work (build is chugging along at the moment).

Will you make the change in `anago`?

**Comment by saad-ali** [comment] 2016-11-01 23:09
> Doing a make clean before make release in /usr/local/google/saadali/anago-v1.5.0-beta.0/kubernetes seems to work (build is chugging along at the moment).

It eventually failed:

```
$ make clean
+++ [1101 15:31:40] Verifying Prerequisites....
+++ [1101 15:31:46] Removing _output directory
$ make release
+++ [1101 15:31:51] Verifying Prerequisites....
+++ [1101 15:31:51] Building Docker image kube-build:build-1b266a1658-4-v1.7.1-2
+++ [1101 15:31:55] Creating data container kube-build-data-1b266a1658-4-v1.7.1-2
+++ [1101 15:32:09] Syncing sources to container
+++ [1101 15:35:41] Running build command...
+++ [1101 15:36:07] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:36:08] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:36:08] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:36:09] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/libs/go2idl/deepcopy-gen
+++ [1101 15:36:09] linux/amd64: go build started
+++ [1101 15:36:10] linux/amd64: go build finished
+++ [1101 15:36:09] linux/arm: go build started
+++ [1101 15:36:15] linux/arm: go build finished
+++ [1101 15:36:09] linux/arm64: go build started
+++ [1101 15:36:15] linux/arm64: go build finished
+++ [1101 15:36:19] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:36:19] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:36:19] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:36:20] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/libs/go2idl/defaulter-gen
+++ [1101 15:36:20] linux/amd64: go build started
+++ [1101 15:36:20] linux/amd64: go build finished
+++ [1101 15:36:20] linux/arm: go build started
+++ [1101 15:36:20] linux/arm: go build finished
+++ [1101 15:36:20] linux/arm64: go build started
+++ [1101 15:36:20] linux/arm64: go build finished
+++ [1101 15:36:24] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:36:24] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:36:24] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:36:24] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/libs/go2idl/conversion-gen
+++ [1101 15:36:25] linux/amd64: go build started
+++ [1101 15:36:25] linux/amd64: go build finished
+++ [1101 15:36:25] linux/arm: go build started
+++ [1101 15:36:25] linux/arm: go build finished
+++ [1101 15:36:25] linux/arm64: go build started
+++ [1101 15:36:25] linux/arm64: go build finished
+++ [1101 15:36:29] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:36:30] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:36:30] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:36:30] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/libs/go2idl/openapi-gen
+++ [1101 15:36:30] linux/amd64: go build started
+++ [1101 15:36:33] linux/amd64: go build finished
+++ [1101 15:36:30] linux/arm: go build started
+++ [1101 15:36:34] linux/arm: go build finished
+++ [1101 15:36:30] linux/arm64: go build started
+++ [1101 15:36:34] linux/arm64: go build finished
+++ [1101 15:36:39] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:36:39] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:36:39] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:36:39] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-discovery
    plugin/cmd/kube-scheduler
+++ [1101 15:36:39] linux/amd64: go build started
+++ [1101 15:40:36] linux/amd64: go build finished
+++ [1101 15:36:39] linux/arm: go build started
+++ [1101 15:40:24] linux/arm: go build finished
+++ [1101 15:36:39] linux/arm64: go build started
+++ [1101 15:40:21] linux/arm64: go build finished
+++ [1101 15:41:04] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:41:05] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:41:05] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:41:05] Building go targets for {linux/amd64 linux/386 linux/arm linux/arm64 darwin/amd64 darwin/386 windows/amd64 windows/386} in parallel (output will appear in a burst when complete):
    cmd/kubectl
+++ [1101 15:41:05] linux/amd64: go build started
+++ [1101 15:41:29] linux/amd64: go build finished
+++ [1101 15:41:05] linux/386: go build started
+++ [1101 15:42:14] linux/386: go build finished
+++ [1101 15:41:05] linux/arm: go build started
+++ [1101 15:41:29] linux/arm: go build finished
+++ [1101 15:41:05] linux/arm64: go build started
+++ [1101 15:41:28] linux/arm64: go build finished
+++ [1101 15:41:05] darwin/amd64: go build started
+++ [1101 15:42:20] darwin/amd64: go build finished
+++ [1101 15:41:05] darwin/386: go build started
+++ [1101 15:42:14] darwin/386: go build finished
+++ [1101 15:41:05] windows/amd64: go build started
+++ [1101 15:42:22] windows/amd64: go build finished
+++ [1101 15:41:05] windows/386: go build started
+++ [1101 15:42:14] windows/386: go build finished
+++ [1101 15:42:45] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:42:46] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:42:46] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:42:46] Building go targets for {linux/amd64 darwin/amd64 windows/amd64} in parallel (output will appear in a burst when complete):
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1101 15:42:46] linux/amd64: go build started
+++ [1101 15:44:59] linux/amd64: go build finished
+++ [1101 15:42:46] darwin/amd64: go build started
+++ [1101 15:45:19] darwin/amd64: go build finished
+++ [1101 15:42:46] windows/amd64: go build started
+++ [1101 15:45:20] windows/amd64: go build finished


+++ [1101 15:45:56] Generating bindata:
    /go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1101 15:45:57] Multiple platforms requested and available 31G >= threshold 11G, building platforms in parallel
+++ [1101 15:45:57] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1101 15:45:57] Building go targets for {linux/amd64 linux/arm linux/arm64} in parallel (output will appear in a burst when complete):
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
+++ [1101 15:45:57] linux/amd64: go build started
+++ [1101 15:46:38] linux/amd64: go build finished
+++ [1101 15:45:57] linux/arm: go build started
+++ [1101 15:47:16] linux/arm: go build finished
+++ [1101 15:45:57] linux/arm64: go build started
+++ [1101 15:47:17] linux/arm64: go build finished
+++ [1101 15:47:52] Running build command...
Running tests for APIVersion: v1,apps/v1alpha1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1alpha1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1,storage.k8s.io/v1beta1,federation/v1beta1
+++ [1101 15:48:03] Running tests without code coverage
can't load package: package k8s.io/kubernetes/_output-v1.6.0-alpha.0/release-stage/full/kubernetes/examples: code in directory /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/_output-v1.6.0-alpha.0/release-stage/full/kubernetes/examples expects import "k8s.io/kubernetes/examples"
Makefile:118: recipe for target 'test' failed
make: *** [test] Error 1
make: *** [release] Error 1
```

**Comment by jbeda** [comment] 2016-11-02 00:53
What ENV variables are you all setting before you call `make release`?  `build-tools/commons.h` should work well with `OUT_DIR` set to something besides the default (`_output`) except for one issue in the rsync filters.  I'll prepare a PR to fix that part up right now.

**Comment by david-mcmahon** [comment] 2016-11-02 00:58
This should be reproducible outside the kubernetes/release environment.
```
make release
mv _output somethingelse
make release

See also https://github.com/kubernetes/kubernetes/issues/23839 WRT OUT_DIR.

**Comment by jbeda** [comment] 2016-11-02 01:00
I'm on hotel wifi so it will take me a while.  I'll work on this some more in a bit.

**Comment by jbeda** [comment] 2016-11-02 18:22
See #36078 for continuing to improve OUT_DIR.

**Comment by alejandroEsc** [comment] 2017-01-03 17:08
I had hit this issue with docker version 1.12.1 which is what you would get with ubuntu 16.04 if you did `sudo apt-get install docker.io`. However i was able to get over this issue by installing and running 1.12.5.

**Comment by luxas** [comment] 2017-05-30 06:57
Closing this as seems outdated and fixed.
@saad-ali reopen if not.

**Closed by luxas** 2017-05-30 06:57 UTC
Labels: area/build-release, area/release-infra, kind/bug
