### ISSUE TITLE
[e2e failure] [sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56422] opened 2017-11-27 15:39 UTC
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
/area platform/gke
@kubernetes/sig-cluster-lifecycle-test-failures
owns the test
@kubernetes/sig-gcp-test-failures
this looks GKE-specific
@kubernetes/sig-node-test-failures
for the AppArmor cluster

This test has been failing since at least 2017-11-13 for the following jobs:
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.8-gci-master-upgrade-master
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.8-gci-master-upgrade-cluster-parallel
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.8-gci-master-upgrade-cluster
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.8-gci-master-upgrade-cluster-new

These jobs are on the [sig-release-master-upgrade dashboard](https://k8s-testgrid.appspot.com/sig-release-master-upgrade), and prevent us from cutting v1.9.0-beta.1 (kubernetes/sig-release#34). Is there work ongoing to bring this test back to green?

[triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%3AUpgrade%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AClusterUpgrade%5C%5D)

[triage cluster 1a3779e6777a416e5ddf](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%3AUpgrade%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AClusterUpgrade%5C%5D#1a3779e6777a416e5ddf)
```
...ResponseError: code=400, message=Cluster master cannot be upgrade to \\\"1.10.0-alpha.0.55+01c74145c7b655\\\"...
```

[triage cluster 590fed6433270872638b](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%3AUpgrade%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AClusterUpgrade%5C%5D#590fed6433270872638b)
```
...invalid AppArmor profile name: "unconfined"...
```

Sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/729

**Comment by spiffxp** [comment] 2017-11-28 04:15
/reopen
would like to see a green run before considering this closed, I'm not sure triage cluster 1a3779e6777a416e5ddf has been addressed

**Comment by enisoc** [comment] 2017-11-29 19:07
The `Cluster master cannot be upgrade to` error appears to be due to the test projects no longer being whitelisted to be able to jump +2 minor versions (1.8 to master, which is now tagged 1.10.0-alpha.0). @janetkuo is looking into this.

If that's the only problem, then we should see the 1.8-1.9 GKE upgrade tests proceed after the AppArmor error is fixed on those builds.

**Comment by janetkuo** [comment] 2017-11-29 21:57
> The `Cluster master cannot be upgrade to` error appears to be due to the test projects no longer being whitelisted to be able to jump +2 minor versions (1.8 to master, which is now tagged 1.10.0-alpha.0). @janetkuo is looking into this.

Confirmed that this is the issue. An internal fix is underway.

**Comment by janetkuo** [comment] 2017-12-01 01:49
The fix was rolled out around midnight. Just waiting for the latest upgrade tests to finish before closing this.

**Comment by spiffxp** [comment] 2017-12-01 18:24
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by janetkuo** [comment] 2017-12-01 18:25
Verified that the latest `UpgradeTest` and `[sig-cluster-lifecycle]` has passed. Underlying upgrade test failures (`[sig-autoscaling]`) are exposed. Closing this one. New bugs should be opened for the underlying failures.

**Closed by janetkuo** 2017-12-01 18:25 UTC
Labels: area/platform/gke, kind/bug, priority/critical-urgent, priority/failing-test, sig/cluster-lifecycle, sig/gcp, sig/node, status/approved-for-milestone, status/in-progress
