### ISSUE TITLE
e2e flake: kube system pods never schedule on new cluster

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#25082] opened 2016-05-03 16:03 UTC
Couldn't find similar issue, please dedup if there is one.

Cluster came up successfully, but all 175 tests failed, because kube-system pods never scheduled:

```
Kubernetes cluster is running.  The master is running at:

  https://104.197.248.29

The user name and password to use is located in /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config.

... calling validate-cluster
Waiting for 7 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 7 ready nodes. 1 ready nodes, 6 registered. Retrying.
Waiting for 7 ready nodes. 1 ready nodes, 7 registered. Retrying.
Waiting for 7 ready nodes. 1 ready nodes, 7 registered. Retrying.
Waiting for 7 ready nodes. 6 ready nodes, 7 registered. Retrying.
Found 7 node(s).
NAME                           STATUS                     AGE
e2e-gce-master-0-master        Ready,SchedulingDisabled   1m
e2e-gce-master-0-minion-cn1r   Ready                      1m
e2e-gce-master-0-minion-mi7k   Ready                      1m
e2e-gce-master-0-minion-oebh   Ready                      1m
e2e-gce-master-0-minion-oh9e   Ready                      1m
e2e-gce-master-0-minion-sqcc   Ready                      1m
e2e-gce-master-0-minion-vvqp   Ready                      58s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://104.197.248.29
GLBCDefaultBackend is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/default-http-backend
Elasticsearch is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://104.197.248.29/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
....

May  2 08:31:42.356: INFO: Error waiting for all pods to be running and ready: Not all pods in namespace 'kube-system' running and ready within 10m0s


Failure [624.486 seconds]
[BeforeSuite] BeforeSuite 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:139

  May  2 08:31:42.356: Error waiting for all pods to be running and ready: Not all pods in namespace 'kube-system' running and ready within 10m0s

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:131
------------------------------
Failure [624.596 seconds]
[BeforeSuite] BeforeSuite 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:139

  BeforeSuite on Node 1 failed

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:139
------------------------------
Failure [624.525 seconds]
[BeforeSuite] BeforeSuite 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:139
...
````

IIRC, the e2e runner used to wait for kube-system pods before running tests, and bail if they were not all running within a timeout. @spxtr did we change that?

Logs at https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24403/kubernetes-pull-build-test-e2e-gce/37883/

**Comment by fejta** [comment] 2016-05-23 22:26
Assigning to @dchen1107 per team/node label

**Comment by bprashanth** [comment] 2016-05-24 01:29
One weird transient thing:
```
I0502 15:19:39.388298    3385 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-e2e-gce-master-0-minion-oh9e", UID:"375f37688020f253545f29c69bc09e53", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-proxy}"}): type: 'Normal' reason: 'BackOff' Back-off pulling image "gcr.io/google_containers/kube-proxy:fcc8bbd662af5b53ccd7156de4c2fa45"
```

But then
```
I0502 15:19:52.382186    3385 kubelet.go:1278] container: kube-system/kube-proxy-e2e-gce-master-0-minion-oh9e/kube-proxy podIP: "" creating hosts mount: false
I0502 15:19:52.390421    3385 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-e2e-gce-master-0-minion-oh9e", UID:"375f37688020f253545f29c69bc09e53", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-proxy}"}): type: 'Normal' reason: 'Pulled' Container image "gcr.io/google_containers/kube-proxy:fcc8bbd662af5b53ccd7156de4c2fa45" already present on machine
```

Looks like a race somewhwere. 

That said, the cluster didn't come up because of fluentd-elasticsearch-e2e-gce-master-0-minion-oh9e on e2e-gce-master-0-minion-oh9e, and that looks like the old image pull hang.

**Comment by dchen1107** [comment] 2016-05-27 00:14
The problem is that kube-proxy didn't come up due to image is not exist. But it is not related to image pulling hang, instead we are having a version screw again for this release:

```
I0502 15:19:35.971632    3415 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-e2e-gce-master-0-minion-cn1r", UID:"375f37688020f253545f29c69bc09e53", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-proxy}"}): type: 'Normal' reason: 'Pulling' pulling image "gcr.io/google_containers/kube-proxy:fcc8bbd662af5b53ccd7156de4c2fa45"
E0502 15:19:36.130269    3415 pod_workers.go:138] Error syncing pod 375f37688020f253545f29c69bc09e53, skipping: failed to "StartContainer" for "kube-proxy" with ErrImagePull: "Tag fcc8bbd662af5b53ccd7156de4c2fa45 not found in repository gcr.io/google_containers/kube-proxy"
I0502 15:19:36.130734    3415 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-e2e-gce-master-0-minion-cn1r", UID:"375f37688020f253545f29c69bc09e53", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "kube-proxy" with ErrImagePull: "Tag fcc8bbd662af5b53ccd7156de4c2fa45 not found in repository gcr.io/google_containers/kube-proxy"
```

**Comment by dchen1107** [comment] 2016-05-27 00:18
@ixdy Looks like another victim of version screw issue from our build infrastructure:

"Tag fcc8bbd662af5b53ccd7156de4c2fa45 not found in repository gcr.io/google_containers/kube-proxy"

**Comment by ixdy** [comment] 2016-05-27 00:45
Where does that tag even come from? It's not in https://gcr.io/v2/google_containers/kube-proxy/tags/list.

**Comment by dchen1107** [comment] 2016-06-06 18:16
I didn't see any failure due to this kind of version screw. Close this one.

**Closed by dchen1107** 2016-06-06 18:16 UTC
Labels: kind/flake, team/node, team/test-infra
