### ISSUE TITLE
kubectl exec -i exits prematurely

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubernetes#15702] opened 2015-10-15 11:45 UTC
With the current Git version of kubectl (see below), I cannot get an interactive shell in a container:

```
kubectl exec -ti single-container-pod bash
```
just exits after a couple of seconds, without echoing any TTY input.

Similarly,
```
cat large-file | kubectl exec -i single-container-pod -- bash -c "cat > /tmp/test && ls -l /tmp/test"
```
shows that in many cases, the file is not completely transferred.  "large-file" was 1MB in my case, with 6Mbit upload rate.

Client Version: version.Info{Major:"1", Minor:"2+",
GitVersion:"v1.2.0-alpha.1.1092+b8aabbbf4f92f0",
GitCommit:"b8aabbbf4f92f006cd1a118dbfd14d97bb996478",
GitTreeState:"clean"}

**Comment by brendandburns** [comment] 2015-10-15 14:20
This seems like a real bug to me.  We should have an e2e to cover this use case if we don't already, and that will likely help with the repro.

@bronger was this on OSS Kubernetes or Google Container Engine?

**Comment by bronger** [comment] 2015-10-15 14:42
@brendandburns the cluster was GKE.

**Comment by thockin** [comment] 2015-10-15 15:52
@ncdc

**Comment by ncdc** [comment] 2015-10-15 15:55
Ugh, not again.

@bronger can you share your pod spec please?

**Comment by ncdc** [comment] 2015-10-15 15:56
@brendandburns I added some e2es recently that should cover these cases as best as possible in a headless test driver, although the `cat` test doesn't test a large file.

**Comment by ncdc** [comment] 2015-10-15 16:00
`kubectl exec -it` works for me in my local setup. I wonder if this is something that's GKE specific?

**Comment by bronger** [comment] 2015-10-15 16:01
@ncdc see https://gist.github.com/bronger/f982a30a798c473b0e5b

**Comment by ncdc** [comment] 2015-10-15 16:03
@bronger can you share your image, or if not, let me know what it's based on?

**Comment by bronger** [comment] 2015-10-15 16:21
The Dockerfile is https://gist.github.com/bronger/f914700b2dcd13a7b9ca
and "apache_entrypoing.sh" is https://gist.github.com/bronger/11955b3828ce5a9da44b

**Comment by bronger** [comment] 2015-10-15 16:24
The DEBUG=1 output is https://gist.github.com/bronger/28f65a42e4f0964e7802

**Comment by ncdc** [comment] 2015-10-15 17:05
So it looks like it's disconnecting after 8 seconds. Presumably something is timing out somewhere and forcibly closing the connection. I'll try to reproduce on GKE.

**Comment by lavalamp** [comment] 2015-10-15 18:09
@bronger Am I right to deduce that this is a client problem, that it worked until you started using a new kubectl?

**Comment by bronger** [comment] 2015-10-15 18:19
@lavalamp yes.  I still have kubectl 1.0 installed.  With this, it works.  With the freshly compiled, it does not.

**Comment by lavalamp** [comment] 2015-10-15 18:20
OK, thanks. That should make this much easier.

**Comment by ncdc** [comment] 2015-10-15 18:51
I can reproduce on GKE.

**Comment by ncdc** [comment] 2015-10-15 19:04
This was broken by my PR #13322. I'm still investigating.

**Comment by ncdc** [comment] 2015-10-15 19:04
GKE is currently Kube 1.0.6, Docker 1.6.2.

**Comment by ncdc** [comment] 2015-10-15 19:04
And Kube 1.0.6 doesn't have this PR. So it's a newer kubectl client with this PR going up against an older kubelet that doesn't have it.

**Comment by ncdc** [comment] 2015-10-15 19:14
I have identified the root cause. Prior to 13332, the server (kubelet) would call Close() on its half of the stdin stream, because it never writes to it. Note: with spdystream stream's, Close() means "I'm not sending any more data", so it's only a half-close, not a full-close. Because you have a newer client that includes 13332, that client does a read on the stdin stream, not because it expects any data, but to be able to know that the server is done running the exec'd command (https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/remotecommand/remotecommand.go#L191-L209). Unfortunately, it's not possible with the current code in master to use a newer client for exec against a server that doesn't contain 13332.

I will do some brainstorming to see what we can do to address this. Obviously protocol negotiation in the future will address this, but hopefully we can come up with something in the meantime.

cc @smarterclayton

**Comment by ncdc** [comment] 2015-10-15 19:16
cc @liggitt

**Comment by bronger** [comment] 2015-10-15 19:23
I wanted to make use of the
```
echo foo | kubectl exec -i <pod> -- cat
```
trick to copy file to the pod, for debugging purposes.  Since 13332 adresses this, I assume that there is currently no way to use this with current GKE?  Would a modified cat help that terminates after a preset number of bytes are written?

**Comment by ncdc** [comment] 2015-10-15 19:31
I guess you could try that... not sure if it would work, but worth a shot. But piping data to a non-interactive stdin the way you're trying to do is generally broken on 1.0.6 and fixed with the aforementioned PR.

**Comment by lavalamp** [comment] 2015-10-15 20:55
@ncdc How hard is it to cherrypick 13332 into the 1.0 branch? Would that break old clients?

**Comment by ncdc** [comment] 2015-10-15 20:58
@lavalamp I'd have to test it out, both the cherry-picking and to see if anything would break.

**Comment by bgrant0607** [comment] 2015-10-16 02:05
Is it correct that this is a 1.0.x issue rather than a 1.1 issue?

**Comment by ncdc** [comment] 2015-10-16 02:08
It's a 1.1 client not able to exec correctly to a 1.0.6 kubelet server.

**Comment by lavalamp** [comment] 2015-10-16 21:52
@bgrant0607 No, kubectl 1.1 is broken when used w/ 1.0.x apiserver.

**Comment by lavalamp** [comment] 2015-10-16 22:01
The root cause is being tracked in #15726.

**Comment by lavalamp** [comment] 2015-10-19 21:28
I'm thinking of dropping this from the 1.1 release. I will move it out tonight or tomorrow unless one of @ncdc, @bronger, or @bgrant0607 talk me out of it.

**Comment by smarterclayton** [comment] 2015-10-19 21:40
My concern is that a wide range of exec scenarios in 1.0 are broken.  If we
did the minimal change in 1.1 clients to start sending a versioned
subprotocol (which itself is an API change) we'd at least guarantee that we
would know 1.1 clients from 1.0 clients.

**Comment by lavalamp** [comment] 2015-10-19 22:15
I'm less concerned about this than some other things because a user can
work around by using kubectl 1.0.

However, @ncdc, can you comment on the case where there's a 1.1 master with
1.0 kubelets in cluster? Will any version of kubectl succeed with that? If
not then we really probably need to fix something.

**Comment by ncdc** [comment] 2015-10-19 23:44
This issue was opened where the kubelets were running in GKE. I created a new GKE cluster a couple of days ago and it was Kube 1.0.6.

You can use a 1.0.x version of kubectl against a 1.0.6 kubelet and you'll be able to do interactive exec. What won't work is #13394 and #13395, which were fixed by #13322.

I really really really want to get a smallest chunk of "protocol negotiation" into 1.1 if possible. That would essentially be the client adding a desired protocol version header and the server responding with the same header. This would at least set the stage for something we can lock 1.1 to and allow us to do non-breaking changes in the future with newer protocol versions.

I'd like to start on this tonight and see how much progress I can make. How much time do I have before 1.1 closes for real?

**Comment by lavalamp** [comment] 2015-10-19 23:47
@ncdc Possibly as long as the end of the week.

But the specific scenario I'm asking about is kubectl 1.X -> apiserver 1.1
-> kubelet 1.0; is there any X for which this configuration works?

**Comment by ncdc** [comment] 2015-10-19 23:54
@lavalamp the only involvement from the apiserver is to identify the request as an upgrade request and proxy it raw back to the kubelet. I can't think of anything off the top of my head where a 1.1 apiserver would cause problems with exec/attach and a 1.0 kubectl and/or kubelet. The problem is really at the ends: right now kubectl 1.1 needs kubelet 1.1 for exec/attach to function 100% correctly.

kubectl | kubelet | status
----------| ---------- | ---------
1.0 | 1.0 | issues 13394, 13395
1.0 | 1.1 | issues 13394, 13395, possibly others?
1.1 | 1.0 | this issue, 13394, possibly others?
1.1 | 1.1 | no known issues

**Comment by lavalamp** [comment] 2015-10-19 23:56
Thanks for the clarification!

**Comment by bronger** [comment] 2015-10-20 07:54
@lavalamp I have implemented a working provisional solution for me which may exists for as long as it's necessary.

**Comment by lavalamp** [comment] 2015-10-20 16:23
@bronger that's great-- is it something you can put into a PR so we can take a look?

**Comment by bronger** [comment] 2015-10-20 16:57
No, it is a very special workaround.  I needed "exec -i" for copying files into the container, and I use rsync for this now.  I just wanted to say that postponing a solution is no showstopper for me.

**Comment by lavalamp** [comment] 2015-10-20 17:52
Ah, OK. Thanks for the clarification.

**Closed** 2015-10-25 14:26 UTC
Labels: component/apiserver, component/kubectl, kind/bug, priority/P1, team/CSI

**Comment by JeanMertz** [comment] 2016-03-21 14:52
I'm somewhat confused on this issue.

We are still experiencing this problem constantly (ie: `kubectl exec -it` disconnecting every x minutes):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
```

was this only fixed in 1.2, or is this bug still present?

**Comment by ncdc** [comment] 2016-03-21 14:57
@JeanMertz there is an idle timeout in use here. If the client doesn't send any traffic to the container, or the container doesn't send any traffic back to the client for e.g. 5 minutes, the connection will be forcibly closed. Is that what you're seeing?

**Comment by JeanMertz** [comment] 2016-03-21 15:22
@ncdc definitely not. I'm in the middle of typing a query (in this specific use-case) and suddenly I am disconnected only milliseconds after the last command typed. Colleagues of mine are experiencing the same.

**Comment by ncdc** [comment] 2016-03-21 16:59
@JeanMertz where are you running Kubernetes? GCE? GKE? Elsewhere?

**Comment by JeanMertz** [comment] 2016-03-21 22:17
GKE

**Comment by JeanMertz** [comment] 2016-03-21 22:39
I also noticed another downside to this:

Whatever we are doing using `exec` at the time of the disconnect keeps running in the background: meaning we sometimes use a console program to enter our production code, which consumes some amount of memory inside the pod. After a day of disconnects, we have 20 to 30 running unused consoles , and a pod that has reached is memory limit, degrading performance of the actual application running inside the pod.

A good old `kill -9` after `exec`'ing as `sh` solves this problem, but it's annoying nonetheless.

**Comment by Overbryd** [comment] 2017-01-10 11:25
Having the same problem here. Running `v1.5.1`
Connections do not get interrupted when data is being sent. So when I launch an interactive container session, with a script that outputs something every now and then, it seems to work.

Based on that, I created a **nasty workaround** to keep my container sessions going, without my interaction. It is really annoying that these sessions terminate prematurely. They leave garbage behind, that needs to cleaned up in case you are attaching to a running production container.

The workaround (print a space-character ` ` to STDERR every 59 seconds as a background process):

```console
# within your container session
$ while :; do sleep 59; echo -n ' ' >&2; done &
```
See the following output, when I do not launch such a script.
**It demonstrates that an interactive session terminates prematurely within ~ X minutes.**

This is really annoying if you are leveraging this functionality to debug running applications and container installations.

```console
$ time kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
Waiting for pod default/busybox to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
/ # Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
Waiting for pod default/busybox to terminate, status is Running
error: timed out waiting for the condition

real	2m4.657s
```

**Comment by sineer** [comment] 2017-02-15 19:50
I have the same problem using

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}

on GKE...

**Comment by richfromm** [comment] 2017-04-05 17:27
I'm seeing something similar. kubernetes running in AWS EC2. If I `kubectl exec <pod-name> -i -t -- ash`, I get booted after about 60 seconds of no activity. Which is annoyingly short for an interactive session. Is this configurable?

Some message on disconnect might be nice as well. The only visible indication is that my shell prompt changes, and it can be easy to not realize that I'm now back at my local host, and not on the kube pod.

**Comment by smarterclayton** [comment] 2017-04-05 18:22
This is usually the load balancer timeout in front of an apiserver.  Check the timeout from the ELB

**Comment by KIVagant** [comment] 2018-06-06 13:06
Thank you, @smarterclayton.
