### ISSUE TITLE
kubectl kubeconfig flag blows up completions 

### ISSUE THREAD

**Issue by flah00** [kubernetes/kubernetes#32676] opened 2016-09-14 14:56 UTC
**Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+ae4550c", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"not a git tree", BuildDate:"2016-08-30T15:45:50Z", GoVersion:"go1.7", Compiler:"gc", Platform:"darwin/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: Mac OS 10.10
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): `Darwin pcpcpc.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64`
- **Install tools**: brew
- **Others**:

**What happened**:
Using the `kubeconfig` flag seems to break completion. If I use completions, without the flag, I am able to view commands and flags, when I double tab. Once the option is on the command line, completion deletes the entire command string, if I tab.

**What you expected to happen**:
Commands, for kubectl should be displayed. If I do not use the `kubeconfig` flag, completions work as expected.

**How to reproduce it** (as minimally and precisely as possible):
Underscore indicates a single tab

```
$ kubectl completion bash > /tmp/kube
$ source /tmp/kube
$ kubectl --k_
$ kubectl --kubeconfig=
$ kubectl --kubeconfig=_
$ kubectl --kubeconfig=--kubeconfig=__
addons/              credentials/         k8.pem               stack-template.json
cluster.yaml         k8.json              kubeconfig           userdata/
$ kubectl --kubeconfig=--kubeconfig=kubeconfig _-bash: --kubeconfig=: attempted assignment to non-variable (error token is "=")
$ 
```

```
$ kubectl completion bash > /tmp/kube
$ source /tmp/kube
$ kubectl --k_
$ kubectl --kubeconfig=kubeconfig _-bash: --kubeconfig=: attempted assignment to non-variable (error token is "=")
$
```

**Comment by flah00** [comment] 2016-09-14 14:57
Maybe debug output from completion will help? 

[debug.txt](https://github.com/kubernetes/kubernetes/files/472352/debug.txt)

**Comment by pwittrock** [comment] 2016-10-18 21:27
@AdoHe Can you own this or find it an owner?

**Comment by AdoHe** [comment] 2016-10-18 23:41
@pwittrock I will take care of it by myself.

**Comment by pwittrock** [comment] 2016-10-18 23:52
@AdoHe Thanks :)

**Comment by AdoHe** [comment] 2016-11-20 07:58
I took a look at this, the problem exist not only with kubeconfig flag, but all other flags. It happens when you use `kubectl --flag= [command]`, I think the root cause is associate array usage in `__handle_flag` function. @flah00 would you mind give a try with the latest kubectl binary?

**Comment by flah00** [comment] 2016-11-21 18:09
@AdoHe I downloaded 1.4.6, from releases, and it generated the same bash completion as the previous version. I also tried 1.5 beta, and found the same results. In fact, it didn't seem like the `__handle_flag` function changed between any of the releases... 

Should I download kubectl from a location other than kubernetes/kubernetes/releases?

**Comment by AdoHe** [comment] 2016-11-22 01:18
@flah00 Thanks for testing, the root cause is clear, I will fix this asap.

**Comment by AdoHe** [comment] 2016-12-11 10:48
Finally I get some time to recheck this, @flah00 could you please provide your bash version? `echo $BASH_VERSION` will give you that info. If you are using  Mac OS 10.10, I am afraid the completion script will not work.

**Comment by ymqytw** [comment] 2017-03-10 17:18
@AdoHe Do you have a fix for this?

**Comment by flah00** [comment] 2017-03-10 17:54
@AdoHe 
sorry for the delay!
`3.2.57(1)-release`
I've got Mac OS 10.12, fingers crossed

**Comment by grodrigues3** [comment] 2017-03-10 21:56
@pwittrock I'll let you decide the milestone on this one

**Comment by AdoHe** [comment] 2017-03-12 03:53
also related with #29322, target this on 1.7.

**Comment by egeland** [comment] 2017-03-24 02:36
I can confirm that this (still) happens for me on MacOSX 10.12.3:

```
$ kubectl --namespace=default get pod -bash: --namespace=: attempted assignment to non-variable (error token is "=")

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

$ echo $BASH_VERSION
3.2.57(1)-release
```

**Comment by julianvmodesto** [comment] 2017-07-18 14:37
I had to update bash on macOS w/ brew to fix this
```
$ echo $BASH_VERSION
3.2.57(1)-release
```

```
brew install bash
echo $(brew --prefix)"/bin/bash" | sudo tee -a /etc/shells
chsh -s $(brew --prefix)"/bin/bash" $(whoami)
```

**Closed** 2018-03-02 03:19 UTC
Labels: area/kubectl, kind/bug, kind/friction, lifecycle/rotten, sig/cli, team/ux (deprecated - do not use)
