### ISSUE TITLE
Build of Go projects importing kubernetes fail because of missing auto-generated code

### ISSUE THREAD

**Issue by ddgenome** [kubernetes/kubernetes#28920] opened 2016-07-13 22:13 UTC
This commit https://github.com/kubernetes/kubernetes/commit/9eb42ff1089243928da623c33fb28eb07f910436#diff-5c755714d0649f91c00269ed3d88e19c removed files like pkg/api/v1/conversion_generated.go so now simply running `go get -v k8s.io/kubernetes/pkg/api/v1` fails. While there are ways around this if your intent is building kubernetes, if you have a Go project that imports "k8s.io/kubernetes/pkg/api/v1", it fails to build because kubernetes fails to build using the standard Go toolchain. Again, there are workarounds but they are costly when dealing with CI.

Example:

```sh
$ go version
go version go1.6.2 darwin/amd64
$ go get -v k8s.io/kubernetes/pkg/api/v1
Fetching https://k8s.io/kubernetes/pkg/api/v1?go-get=1
Parsing meta tags from https://k8s.io/kubernetes/pkg/api/v1?go-get=1 (status code 200)
get "k8s.io/kubernetes/pkg/api/v1": found meta tag main.metaImport{Prefix:"k8s.io/kubernetes", VCS:"git", RepoRoot:"https://github.com/kubernetes/kubernetes"} at https://k8s.io/kubernetes/pkg/api/v1?go-get=1
get "k8s.io/kubernetes/pkg/api/v1": verifying non-authoritative meta tag
Fetching https://k8s.io/kubernetes?go-get=1
Parsing meta tags from https://k8s.io/kubernetes?go-get=1 (status code 200)
k8s.io/kubernetes (download)
k8s.io/kubernetes/pkg/types
k8s.io/kubernetes/pkg/util/sets
k8s.io/kubernetes/pkg/auth/user
...
k8s.io/kubernetes/pkg/api
k8s.io/kubernetes/pkg/api/v1
# k8s.io/kubernetes/pkg/api/v1
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:248: undefined: autoConvert_api_PodStatusResult_To_v1_PodStatusResult
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:289: undefined: autoConvert_v1_PodStatusResult_To_api_PodStatusResult
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:304: undefined: autoConvert_api_PodTemplateSpec_To_v1_PodTemplateSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:346: undefined: autoConvert_v1_PodTemplateSpec_To_api_PodTemplateSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:363: undefined: autoConvert_api_PodSpec_To_v1_PodSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:382: undefined: autoConvert_v1_PodSpec_To_api_PodSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:405: undefined: autoConvert_api_Pod_To_v1_Pod
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:477: undefined: autoConvert_v1_Pod_To_api_Pod
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:493: undefined: autoConvert_api_ServiceSpec_To_v1_ServiceSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: undefined: autoConvert_v1_Secret_To_api_Secret
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: too many errors
```

/cc @thockin

**Comment by dims** [comment] 2016-07-13 22:16
@ddgenome : we are also talking about this in https://github.com/kubernetes/kubernetes/issues/28890 and @thockin has a PR open as well

**Comment by spxtr** [comment] 2016-07-13 23:42
This is not a dupe of #28890, and I think this one is much more important. From the [golang blog](https://blog.golang.org/generate):

> Just keep in mind that it is for package authors, not clients, if only for the reason that the program it invokes might not be available on the target machine. Also, if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients.

I hate to suggest reverting such a big PR, but this is important.

**Comment by ddgenome** [comment] 2016-07-13 23:48
This does seem separate from #28890, as that is talking about building kubernetes using make and its tools and this is about building with the standard Go toolchain as an import in another project.

**Comment by mml** [comment] 2016-07-13 23:48
cc @lavalamp

**Comment by mml** [comment] 2016-07-13 23:52
Assigning to current buildcop.

**Comment by dims** [comment] 2016-07-13 23:58
@ddgenome @spxtr gotcha. thanks for the context, now i understand.

**Comment by thockin** [comment] 2016-07-14 04:09
I know the "go way of doing things" is to check generated code in.  But the
code in question causes MASSIVE pain in our contribution queue.  That is
why I am trying to do this.

**Comment by thockin** [comment] 2016-07-14 04:10
I am going to close this.  It's not EXACTLY a dup, but I know whats up and I don't need N issues open.

**Closed by thockin** 2016-07-14 04:10 UTC
Labels: priority/P1

**Comment by djsly** [comment] 2016-07-14 17:28
What would be a quick way to fix compilation error for project that imports k8s.io/kubernetes/pkg/api/v1

We are using the golang -onbuild docker image to build our program which calls go get
````
build	14-Jul-2016 13:07:10	[0m[91m# k8s.io/kubernetes/pkg/api/v1
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:248: undefined: autoConvert_api_PodStatusResult_To_v1_PodStatusResult
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:289: undefined: autoConvert_v1_PodStatusResult_To_api_PodStatusResult
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:304: undefined: autoConvert_api_PodTemplateSpec_To_v1_PodTemplateSpec
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:346: undefined: autoConvert_v1_PodTemplateSpec_To_api_PodTemplateSpec
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:363: undefined: autoConvert_api_PodSpec_To_v1_PodSpec
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:382: undefined: autoConvert_v1_PodSpec_To_api_PodSpec
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:405: undefined: autoConvert_api_Pod_To_v1_Pod
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:477: undefined: autoConvert_v1_Pod_To_api_Pod
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:493: undefined: autoConvert_api_ServiceSpec_To_v1_ServiceSpec
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:502: undefined: autoConvert_v1_Secret_To_api_Secret
build	14-Jul-2016 13:07:10	../k8s.io/kubernetes/pkg/api/v1/conversion.go:502: too many errors
error	14-Jul-2016 13:07:12	The command '/bin/sh -c go-wrapper install' returned a non-zero code: 2
````

**Comment by lavalamp** [comment] 2016-07-14 18:00
We intend to publish the client to a separate repository, which will be go-gettable--we're still working out the logistics, though. I'm really sorry this causes pain, but our repository is not really set up to be go-gotten at the moment.

In the short term, can you point at the 1.3 release branch?

Baring that, we could make a go-gettable write-only fork and run a script hourly or something that periodically makes all the generated files and publishes them.

**Comment by djsly** [comment] 2016-07-14 18:23
OK , I will try updating my godeps to use the following
````
"ImportPath": "k8s.io/kubernetes/pkg/api",
                       "Comment": "v1.3.0",
                       "Rev": "283137936a498aed572ee22af6774b6fb6e9fd94"
````

**Comment by djsly** [comment] 2016-07-14 18:39
Unfortunately, it isn't that easy to force a specific version since we are using the automagic from the gaoling docker image :(

````
FROM golang:1.6-onbuild
This image includes multiple ONBUILD triggers which should cover most applications. The build will COPY . /go/src/app, RUN go get -d -v, and RUN go install -v.
````

**Comment by suquant** [comment] 2016-07-15 15:26
+1

**Comment by djsly** [comment] 2016-07-15 15:34
@lavalamp do you guys have an rough ETA ? I would like to see how much effort I should be putting on this knowing that it is still a WIP on your side.

We tried using v1.2.5 but we are hitting the following issue:
https://github.com/kubernetes/kubernetes/issues/23529

while using v1.3.0 we are not getting:
````
godep: Dep (github.com/opencontainers/runc/libcontainer/cgroups) restored, but was unable to load it with error:
        Package (github.com/Sirupsen/logrus) not found
godep: Dep (github.com/opencontainers/runc/libcontainer/configs) restored, but was unable to load it with error:
        Package (github.com/Sirupsen/logrus) not found
````

Fun day it was yesterday :)

**Comment by thockin** [comment] 2016-07-15 15:38
The logrus error is something else - logrus IS vendored by Kubernetes.

**Comment by vtd125** [comment] 2016-07-16 20:04
@djsly Hello - Do you still work at Nuance in Mtl? I've been trying to contact you, but cannot find your email anywhere. Please let me know if you'd be willing to correspond? I'm a student at Brown university and would like to inquire about working at Nuance to a real person instead of the FAQ section of the website
