### ISSUE TITLE
--dry-run needs to be universally supported for operations that modify content

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#17538] opened 2015-11-19 23:22 UTC
List of known offenders:

```
kubectl create -f -
```

**Comment by thockin** [comment] 2015-11-19 23:34
Ideally whole hierarchies like `create` have this defined once, not once per leaf :)

**Comment by bgrant0607** [comment] 2016-03-15 00:14
Dupe of #11488

**Closed by bgrant0607** 2016-03-15 00:14 UTC
Labels: area/usability, component/kubectl, help-wanted, kind/enhancement, priority/P2, team/ux
