### ISSUE TITLE
CAdvisor endpoint taking too long to return metrics for windows nodes

### ISSUE THREAD

**Issue by rashmichandrashekar** [kubernetes/kubernetes#75752] opened 2019-03-27 00:33 UTC
**What happened**:
The endpoint <nodeip>:10255/stats/summary to expose cadvsior metrics takes longer to return metrics when the number of containers are higher. The response time grows linearly with the number of containers running on the node

**What you expected to happen**:
This endpoint should return metrics quickly like it does on linux nodes

**How to reproduce it (as minimally and precisely as possible)**:
Run a http://localhost:10255/stats/summary if running on windows node locally
or run http://<node-ip>:10255/stats/summary if running on a linux node

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14

**Comment by rashmichandrashekar** [comment] 2019-03-27 00:38
@kubernetes/sig-azure-bugs

**Comment by zhiweiv** [comment] 2019-03-27 00:57
It bugs me a long time, Windows nodes disappeared from `kubectl top nodes`, they may appear again sometime. I found below error in metrics-server pod,
`Failed to get kubelet_summary:10.2.0.158:10255 response in time`

**Comment by rhockenbury** [comment] 2019-03-27 03:21
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/74991

**Comment by zhiweiv** [comment] 2019-03-27 04:12
It maybe not my case, #74991 indicates that is caused by a PR in recent days, however my symptom has last couple months.

**Comment by zhiweiv** [comment] 2019-04-02 06:47
DefaultMetricsScrapeTimeout in metrics-server 0.2.1 is 20s, I increased it to 120s, now metrics-server can collect metrics from Windows nodes successfully.

**Comment by PatrickLang** [comment] 2019-08-23 00:06
`kubectl logs -n kube-system metrics-server-...`  will show these failures

```
W0822 23:48:25.000516       1 manager.go:147] Failed to get all responses in time (got 6/7)
W0822 23:48:28.210743       1 manager.go:102] Failed to get kubelet_summary:10.240.0.97:10255 response in time
W0822 23:55:25.000362       1 manager.go:147] Failed to get all responses in time (got 2/7)
W0822 23:55:28.140617       1 manager.go:102] Failed to get kubelet_summary:10.240.0.128:10255 response in time
W0822 23:55:32.789299       1 manager.go:102] Failed to get kubelet_summary:10.240.0.190:10255 response in time
W0822 23:55:35.591537       1 manager.go:102] Failed to get kubelet_summary:10.240.0.97:10255 response in time
W0822 23:55:39.300226       1 manager.go:102] Failed to get kubelet_summary:10.240.0.4:10255 response in time
W0822 23:55:45.443369       1 manager.go:102] Failed to get kubelet_summary:10.240.0.159:10255 response in time
```

**Comment by craiglpeters** [comment] 2019-10-22 01:09
Moving out of 1.17 since the underlying APIs in Docker and hnsshim are the root cause and will be independent of the Kubernetes release. @feiskyer indicates that it may be possible to do some caching in the kubelet

**Comment by porrascarlos802018** [comment] 2020-01-03 14:29
Team , I have a customer very interested, needed to have metrics working as expected on windows nodes , do we have anything to share in regards to final fix for these known problems?

**Comment by PatrickLang** [comment] 2020-01-16 01:03
ok, currently reproducing problem with this:

1. Create a deployment for 15 pods with high CPU load

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burn2
  labels:
    app: burn2
spec:
  replicas: 15
  template:
    metadata:
      name: burn2
      labels:
        app: burn2
    spec:
      containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command:
        - powershell.exe
        - -command
        - "foreach ($loopnumber in 1..8) { Start-Job -ScriptBlock { $result = 1; foreach($mm in 1..2147483647){$res1=1;foreach($num in 1..2147483647){$res1=$mm*$num*1340371};$res1} } } ; get-job | wait-job"
      nodeSelector:
        "beta.kubernetes.io/os": windows
  selector:
    matchLabels:
      app: burn2
```

2. Look at metrics-server logs `kubectl logs -n kube-system metrics-server-...`

```
E0116 00:36:57.368936 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:$
kswpool1000000: unable to fetch metrics from Kubelet akswpool1000000 (10.240.0.66): Get http://10.240.0.66:10255/stats/summary?only_cpu_an$
_memory=true: context deadline exceeded
E0116 00:37:37.184120 1 reststorage.go:135] unable to fetch node metrics for node "akswpool1000000": no metrics known for node
E0116 00:37:48.347883 1 reststorage.go:160] unable to fetch pod metrics for pod default/burn2-5bb4bf998-vfb6s: no metrics known for $
```

3. `kubectl top node` fails because it can't get the stats from the metrics-server

**Comment by PatrickLang** [comment] 2020-02-17 23:37
Fixed in https://github.com/kubernetes/kubernetes/pull/87730

**Closed** 2020-02-19 00:19 UTC
Labels: area/provider/azure, kind/bug, sig/windows

**Comment by zhiweiv** [comment] 2020-02-19 00:46
@PatrickLang 
Will this fix be backported to previous versions?
