### ISSUE TITLE
etcd index out of range during startup

### ISSUE THREAD

**Issue by azye** [kubernetes/kubernetes#93348] opened 2020-07-22 17:32 UTC
**What happened**:

Seemingly in the middle of the night when our test cluster was not under much load but had been running for a while, client connections to the API began failing when using the `client-go` package. When we looked at the cluster, `kubectl` commands yielded: 

```
The connection to the server x.x.x.x:6443 was refused - did you specify the right host or port?
```

When digging further into this, we noticed that `etcd` was crashing and failing on startups:

```
docker logs 763136fa1953
[WARNING] Deprecated '--debug' flag is set to true (use '--log-level=debug' instead
[WARNING] Deprecated '--debug' flag is set to true with inconsistent '--log-level=info' flag
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-07-22 16:50:06.917341 I | etcdmain: etcd Version: 3.4.3
2020-07-22 16:50:06.917370 I | etcdmain: Git SHA: 3cf2f69b5
2020-07-22 16:50:06.917373 I | etcdmain: Go Version: go1.12.12
2020-07-22 16:50:06.917375 I | etcdmain: Go OS/Arch: linux/amd64
2020-07-22 16:50:06.917378 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2020-07-22 16:50:06.917419 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--debug' flag is set to true (use '--log-level=debug' instead
[WARNING] Deprecated '--debug' flag is set to true with inconsistent '--log-level=info' flag
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-07-22 16:50:06.917448 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file =
2020-07-22 16:50:06.917986 I | embed: name = mini-master
2020-07-22 16:50:06.917993 I | embed: data dir = /var/lib/etcd
2020-07-22 16:50:06.917997 I | embed: member dir = /var/lib/etcd/member
2020-07-22 16:50:06.917999 I | embed: heartbeat = 100ms
2020-07-22 16:50:06.918002 I | embed: election = 1000ms
2020-07-22 16:50:06.918004 I | embed: snapshot count = 10000
2020-07-22 16:50:06.918011 I | embed: advertise client URLs = https://x.x.x.x:2379
2020-07-22 16:50:06.918015 I | embed: initial advertise peer URLs = https://x.x.x.x:2380
2020-07-22 16:50:06.918019 I | embed: initial cluster =
panic: runtime error: index out of range

goroutine 160 [running]:
go.etcd.io/bbolt.(*DB).page(...)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:886
go.etcd.io/bbolt.(*Tx).page(...)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:620
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0000ea380, 0x80000000df, 0x1, 0xc00024f1e8)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:625 +0x13a
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0000ea380, 0x7e, 0x0, 0xc00024f1e8)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:634 +0xd4
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0000ea380, 0xc00025d900, 0xc00024f4b8, 0xc00024f488, 0xc0000847e0)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:465 +0xd4
go.etcd.io/bbolt.(*Tx).checkBucket.func2(0x7fe59c2ba1b9, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:490 +0xc0
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0000ea398, 0xc00024f370, 0x0, 0xc00024f340)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:388 +0xfe
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0000ea380, 0xc0000ea398, 0xc00024f4b8, 0xc00024f488, 0xc0000847e0)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:488 +0x146
go.etcd.io/bbolt.(*DB).freepages(0xc0000e4600, 0x0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:1006 +0x1f8
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:313 +0x10e
sync.(*Once).Do(0xc0000e4768, 0xc00024f600)
	/usr/local/go/src/sync/once.go:44 +0xb3
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0000e4600)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:309 +0x56
go.etcd.io/bbolt.Open(0xc00029a340, 0x1c, 0x180, 0xc0000948c8, 0x44402c, 0x100000000000020, 0x0)
	/home/ec2-user/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:286 +0x326
go.etcd.io/etcd/mvcc/backend.newBackend(0xc00029a340, 0x1c, 0x5f5e100, 0x2710, 0x1082f11, 0x5, 0x280000000, 0x0, 0x0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/mvcc/backend/backend.go:154 +0xfe
go.etcd.io/etcd/mvcc/backend.New(...)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/mvcc/backend/backend.go:137
go.etcd.io/etcd/etcdserver.newBackend(0x7ffee5344e67, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc0000ef280, 0x1, 0x1, 0xc0000ef400, ...)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/backend.go:52 +0x1a0
go.etcd.io/etcd/etcdserver.openBackend.func1(0xc000084780, 0xc00029c2c0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/backend.go:73 +0x95
created by go.etcd.io/etcd/etcdserver.openBackend
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/backend.go:72 +0x110
```

**What you expected to happen**:

I expect etcd to not crash or at least recover.

**How to reproduce it (as minimally and precisely as possible)**:

No solid steps to produce this manually. This occurred in the middle of the night when the cluster was not being used.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.17.4
- Cloud provider or hardware configuration: 3 node bare metal cluster with 1 master, 2 workers.
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux mini-master 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-07-22 19:53
/assign @jingyih 

looks like this is already fixed upstream (xref https://github.com/etcd-io/bbolt/issues/152, https://github.com/etcd-io/bbolt/issues/153, https://github.com/etcd-io/etcd/issues/10399), do you know in what version?

**Comment by azye** [comment] 2020-07-22 23:25
i saw that fix and noticed it went into bbolt 1.3.3 which is also the version my log above shows I'm running. So theoretically that issue should fixed in the version I'm running. it does look like its in a similar area.

**Comment by jingyih** [comment] 2020-07-23 16:28
The panic stack trace is different than what has been fixed in https://github.com/etcd-io/bbolt/pull/153

It looks like the panic happens when bbolt is reconstructing freelist from disk.

@azye Is there a way to reproduce this panic?

cc @ptabor @gyuho @jpbetz

**Comment by azye** [comment] 2020-07-23 17:13
@jingyih No specific reproduction steps I can think of. The error happened on a running cluster while it was sitting idle overnight (no crashes occurred to the host machine itself). When we checked the cluster in the morning and were unable to reach the cluster and discovered this error while going through logs. The error provided had to be pulled from docker instead of kubectl.

**Closed** 2020-12-20 19:41 UTC
Labels: area/etcd, kind/bug, lifecycle/rotten, sig/api-machinery
