### ISSUE TITLE
Failing Tests: [sig-storage] 5000-node correctness tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#66376] opened 2018-07-19 10:33 UTC
Failing Job:

[sig-release-master-blocking#gce-scale-correctness](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness)

These tests started flaking recently (they were consistently green for a long time):

- Mounted volume expand[Slow] Should verify mounted devices can be resized
- Volume expand [Slow] Verify if editing PVC allows resize
- Subpath [Volume type: gcePDPVC] should support restarting containers using file as subpath [Slow]
- Subpath [Volume type: gcePDPVC] should fail for new directories when readOnly specified in the volumeSource
- Subpath [Volume type: gcePDPVC] should fail if subpath with backstepping is outside the volume [Slow]
- Volumes PD should be mountable with ext4

Affected runs:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/137
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/138
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/139

/kind bug
/sig storage
/priority important-soon
/milestone v1.12
/cc @tpepper @AishSundar @mohammedzee1000 

@msau42 - Could you PTAL or delegate? Thanks.

**Comment by msau42** [comment] 2018-07-19 15:33
Volume expansion tests have been fixed by https://github.com/kubernetes/kubernetes/pull/66324

**Comment by msau42** [comment] 2018-07-19 15:38
/assign @davidz627 
can you investigate the remaining failures?

**Comment by msau42** [comment] 2018-08-16 13:48
I think the latest failures are caused by gce API rate limiting: https://github.com/kubernetes/kubernetes/issues/67348

/assign @bowei @jingax10

**Comment by msau42** [comment] 2018-08-16 14:03
It seems to only be failing on scalability test suites. I wonder if it's due to some different cidr configuration

**Comment by shyamjvs** [comment] 2018-08-27 09:38
/status approved-for-milestone

Friendly ping. This is affecting release-blocking scalability job.

**Comment by dims** [comment] 2018-08-27 11:54
hey @shyamjvs what needs to be done here? by whom?

**Comment by shyamjvs** [comment] 2018-08-27 14:00
@michelle192837 Could you comment on what needs to be done here and by whom?

**Comment by msau42** [comment] 2018-09-04 19:59
It looks like the latest run on 9/1 has passed.

**Comment by davidz627** [comment] 2018-09-04 21:10
Marking closed as the fixes have been merged and the test runs are now passing
/close

**Closed by davidz627** 2018-09-04 21:10 UTC
Labels: kind/bug, kind/failing-test, milestone/needs-approval, priority/important-soon, sig/scalability, sig/storage, status/approved-for-milestone
