### ISSUE TITLE
Lost container's IP isn't removed from Service's Endpoints

### ISSUE THREAD

**Issue by ScOut3R** [kubernetes/kubernetes#17284] opened 2015-11-14 22:45 UTC
Hey,

I noticed that if a container, which is an endpoint for a service, gets lost (I kill the machine running it) its IP isn't removed from the service's endpoints. At least not under a reasonable timeframe. I have waited probably 60 minutes. 
I was wondering is this intentional? Or am I missing some configuration option?

Kind regards,
Mate

**Comment by thockin** [comment] 2015-11-16 21:25
Can you provide more information?

What version of kubernetes?  Was the node itself marked NotReady?

**Comment by ScOut3R** [comment] 2015-11-16 21:28
@thockin Ah, sorry! I have tested it with version 1.0.6 and 1.1.1. The node was marked NotReady almost right after I shut it down. Is there any test I should do to provide you more information?

**Comment by thockin** [comment] 2015-11-16 22:14
@freehan Can you try to get a repro on this?

**Comment by freehan** [comment] 2015-11-16 22:23
Sure. Let me try it out. 

What is the ideal behavior in this case? IP got removed in X seconds?

**Comment by thockin** [comment] 2015-11-16 22:26
IP should be removed ~instantly once we delete the pod, which should happen
~instantly once we timeout a node.

**Comment by bprashanth** [comment] 2015-11-16 23:47
See https://github.com/kubernetes/kubernetes/issues/8335 IIRC the pod will stay Running till the node controller wacks it after podevictiontimeout (the node will flip to notready in 40s), but something might've changed recently

**Comment by bprashanth** [comment] 2015-11-16 23:49
We can set Ready == false if the node is unreachable. This will also remove it from the service.

**Comment by thockin** [comment] 2015-11-17 01:27
Good point.  node being NotReady is different than pods being killed.
Notready node should probably imply all pods being Notready.

**Comment by freehan** [comment] 2015-11-17 01:30
I am not able to reproduce the problem :(
I am trying this on version 1.1.1 with different service types and with/without RC.

@ScOut3R Can you provide more detail? What is the service type? Is there a RC involved? How many replicas?

**Comment by freehan** [comment] 2015-11-17 01:46
@ScOut3R Are you also using liveness or readiness probe?

**Comment by ScOut3R** [comment] 2015-11-17 08:35
@freehan It's a simple service utilizing the NodePort feature:

```
apiVersion: v1
kind: Service
metadata:
  name: resolver-service
spec:
  ports:
  - port: 53 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    protocol: TCP
    name: dns-tcp
  - port: 53
    protocol: UDP
    name: dns-udp
  type: NodePort
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: resolver
```

The pods are managed by an RC with a replication factor of 2. The two replicas were residing on two different hosts at the time of testing. I am not using liveness or readiness probe for the pods. Could that be a problem?

**Comment by freehan** [comment] 2015-11-17 21:32
Thanks for the detail. Probe should not matter since the node is down. 

I still cannot reproduce the problem. After the node is down, there is a 5 min grace period till the pods get evicted. Once  evicted, endpoints should be updated. 

@ScOut3R After the node is down for 5 minutes, what are the status of pods on that node?

**Comment by freehan** [comment] 2015-11-18 18:38
@ScOut3R The 5 minutes grace period is necessary. You do not want to evict all pods on a node due to a network blip. 

I will add a fix to mark pods NotReady when node turn NotReady. This should remove bad endpoints.

**Comment by ScOut3R** [comment] 2015-11-19 09:02
@freehan Thanks, that would be perfect! The eviction timeout is reasonable, and with the bad endpoints cleanup the loadbalancing should be working just fine!

**Comment by freehan** [comment] 2016-02-01 19:06
Closing this issue. Code fix and e2e tested has been merged.

**Closed by freehan** 2016-02-01 19:06 UTC
Labels: priority/P2, team/cluster, team/control-plane
