### ISSUE TITLE
Something in gke-ci leaks routes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#19779] opened 2016-01-18 03:13 UTC
Just deleted 91 since gke-ci was completely hosed on quota. We hit the limit on http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ci/10377/ so it was some set of suites before that. 
```
19:06:05 client [kubectl]. To install, run
19:06:05   $ gcloud components install kubectl
19:06:05 
19:06:06 ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Insufficient project quota to satisfy request for resource: "ROUTES". The request requires '3.0' and is short '2.0'. The project has a quota of '100.0' with '1.0' available. 
19:06:06 2016/01/17 19:06:06 e2e.go:309: Error running up: exit status 1
19:06:06 2016/01/17 19:06:06 e2e.go:305: Step 'up' finished in 2.107868944s
19:06:06 
2016/01/17 19:06:06 e2e.go:141: Error starting e2e cluster. Aborting.
19:06:06 exit status 1
```

@kubernetes/goog-testing

**Comment by bprashanth** [comment] 2016-01-18 03:14
Actually not sure this is specific to gke, kubernetes-jenkins seems to have a build up of routes as well though it has higher quota

**Comment by ihmccreery** [comment] 2016-01-19 18:35
Note that we [fail on resource leakage](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L645), so we probably saw failed runs at some point.  Not that anyone was necessarily paying attention.

My guess is that when it went yellow/red for other reasons, and no one paid attention to the leaked resource warning/error.

**Comment by ihmccreery** [comment] 2016-01-19 18:36
Long-term, we have #18119 to make this better.

**Comment by bprashanth** [comment] 2016-01-19 19:05
Oddly, when I opened up one of the clusters and checked the before-after routes it didn't seem to show the leaked ones. I didn't dig too deep at this point. It looked like the failed routes were from instances.

**Comment by ixdy** [comment] 2016-01-19 22:02
It also seems like the script doesn't work well on GKE...

Compare e.g.
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gke-ci/10398/artifacts/gcp-resources-cluster-up.txt?debugUI=DEVELOPERS
 vs
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce/10434/artifacts/gcp-resources-cluster-up.txt?debugUI=DEVELOPERS
(cluster
up listing on GKE vs cluster up listing on GCE).

**Comment by lavalamp** [comment] 2016-01-25 17:39
@roberthbailey to delegate-- who owns route controller? Is it @cjcullen?

...but if the leak is because e.g. the suite timed out and the cluster was unceremoniously destroyed, that seems like a test infra problem. @ixdy

**Comment by roberthbailey** [comment] 2016-01-25 17:56
Thanks @lavalamp -- I just wanted to make sure that this wasn't a duplicate of https://github.com/kubernetes/kubernetes/issues/13515 before diving in. I'll take a look at the script to make sure it works properly against GKE clusters.

**Comment by bprashanth** [comment] 2016-01-25 18:29
I don't think it is a dupe because the resources listed in https://github.com/kubernetes/kubernetes/issues/13515 match those required for L4 loadbalancing. I think this is more likely something to do with improper cluster termination.

**Comment by roberthbailey** [comment] 2016-01-25 18:53
Yeah, that was the same conclusion that we came to.

**Comment by roberthbailey** [comment] 2016-01-25 23:39
The script doesn't work at all for GKE since it has an incorrect value for the `INSTANCE_PREFIX` variable. Working on a fix for that issue first.

**Comment by roberthbailey** [comment] 2016-01-29 06:53
The script changes seem to be working, as the gke resources are now being captured: https://console.developers.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gke-ci/10482/artifacts/gcp-resources-cluster-up.txt

**Comment by roberthbailey** [comment] 2016-01-29 22:10
I'm going to close this issue now that I've increased our ability to debug. We also haven't seen a new occurrence of leaked routes in this project since I've been tracking this issue.

**Closed by roberthbailey** 2016-01-29 22:10 UTC
Labels: area/test, kind/flake, priority/P1, team/gke
