### ISSUE TITLE
kubectl apply ignoring changes to spec.initcontainers field

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#47264] opened 2017-06-09 19:28 UTC
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:07Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1409.1.0
- **Kernel** (e.g. `uname -a`): Linux 4.11.2-coreos #1 SMP Tue May 23 22:04:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
`kubectl apply` ignores changes in `spec.initcontainers` field. The `spec.initContainers` field is also mirrored into alpha and beta annotations. I think the annotations from the previous run overwrite the changes specified in `spec.initcontainers` field. If I apply my changes as annotations, it works. Also, there is no `--feature-gates` option in kube-apiserver to turn it off annotations for initcontainers.

**What you expected to happen**:
`spec.initcontainers` changes should trump over annotations

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment with `spec.initcontainer` field populated in pod template. Apply the deployment. Make changes `spec.initcontainer` field and apply again. kubectl says deployment is configured but your changes are not applied

**Comment by mengqiy** [comment] 2017-06-09 23:28
Same issue report in https://github.com/kubernetes/kubectl/issues/27. I believe Strategic Merge Patch works https://github.com/kubernetes/kubectl/issues/27#issuecomment-307497046.
I think this an api machinery issue. @kubernetes/sig-api-machinery-misc

**Comment by dchen1107** [comment] 2017-06-09 23:38
Do we have the same issue in 1.7? 

cc/ @kubernetes/kubernetes-release-managers

**Comment by mengqiy** [comment] 2017-06-09 23:55
Yes.

**Comment by xingzhou** [comment] 2017-06-13 05:18
seems according to the doc, only "Changes to the Init Container spec are limited to the container image field.", IIUC, kubernetes/kubectl#27 is trying to update the image field, if @mengqiy you are not working on this, I can help take a look at the issue.

**Comment by mengqiy** [comment] 2017-06-13 06:06
@xingzhou Thanks for triaging the issue.

**Comment by xingzhou** [comment] 2017-06-28 07:49
@erictune, I think the root cause of this issue is from these lines of code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/conversion.go#L615-L622). While when we try to update a pod object, we need to convert from `v1.Pod` to `api.Pod`, and the code in conversion function always overwrite the values in `pod.Spec.InitContainers` with the value of annotation `pod.beta.kubernetes.io/init-containers`. Therefore, when user changes the values in `pod.Spec.InitContainers`, it won't work.

One solution is to move the logic in the conversion function to pod's storage methods like create/update, in this case, at least we can realize that user is modifying the fields in `pod.Spec.InitContainers`. What's your idea on this?

**Comment by JulianWei** [comment] 2017-07-13 22:43
Is there any workaround?

**Comment by MartinodF** [comment] 2017-07-13 23:33
@JulianWei you can just go back to specifying your init containers using the beta annotation (`pod.beta.kubernetes.io/init-containers`), it works correctly. When this bug is fixed, you will be able to use the stable `InitContainers` field. A bit annoying, but easy to fix :)

**Comment by smarterclayton** [comment] 2017-07-14 00:38
In 1.8 we should remove the beta annotation since init containers are GA.



On Jul 13, 2017, at 7:33 PM, Martino di Filippo <notifications@github.com>
wrote:

@JulianWei <https://github.com/julianwei> you can just go back to
specifying your init containers using the beta annotation (
pod.beta.kubernetes.io/init-containers), it works correctly. When this bug
is fixed, you will be able to use the stable InitContainers field. A bit
annoying, but easy to fix :)

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/47264#issuecomment-315229690>,
or mute the thread

**Comment by JulianWei** [comment] 2017-07-14 02:19
@MartinodF, thank you

**Comment by alc6379** [comment] 2017-08-04 18:48
I don't know if this is relevant or not, but it appears that if you never used annotations at all and have only ever used initContainers in your yaml, apply doesn't seem to touch that, either.

**Comment by 2rs2ts** [comment] 2017-08-24 18:12
The beta annotations do not work for us. We've even tried to delete our daemonset and and only use the beta annotations but changes don't get noticed.

**Comment by kevingessner** [comment] 2017-09-06 16:07
Is there any way this could be fixed for 1.7.x?  Due to this bug, on 1.7 and earlier, the only reliable way to use init containers is to use the `pod.beta.kubernetes.io/init-containers`annotation, not the newer initContainers field.  But in 1.8 (as of 6ec80eac1bd9d9eb1902f7b20bf151541e6a44c6), that annotation is going away.  That means that a given pod spec can't be compatible with both 1.7 (where the annotation is required) and 1.8 (where the annotation is unsupported), without duplicating the init containers.

Fixing this in 1.7.x -- so the initContainers field is supported for updates -- would make the migration smoother, as the initContainers field could be used always.  Is it too late to get this narrow problem fixed in the next 1.7 release?

**Comment by liggitt** [comment] 2017-09-06 16:35
Unfortunately, the annotations have to take precedence as long as 1.5 kubelets are supported, or updates from those kubelets would not correctly update the objects. 1.8 is the earliest that behavior could be dropped.

That conflict between honoring the earliest API representation (via annotations) to preserve skewed compatibility and having an API that isn't insane to use is why annotations are no longer used as an alpha/beta-stage mechanism for new fields.

**Comment by liggitt** [comment] 2017-09-06 16:39
fixed in https://github.com/kubernetes/kubernetes/pull/51816

**Closed by liggitt** 2017-09-06 16:39 UTC
Labels: sig/api-machinery, sig/cli

**Comment by matthiasr** [comment] 2017-09-07 11:05
So do I understand correctly that currently the safe way is to always duplicate the init container between the annotation and the actual field, and then after upgrading to 1.8 drop the annotation?

**Comment by liggitt** [comment] 2017-09-07 13:31
> So do I understand correctly that currently the safe way is to always duplicate the init container between the annotation and the actual field, and then after upgrading to 1.8 drop the annotation?

Correct. Pre-1.8, the information is duplicated in two places in the object, with the annotation taking precedence. 1.8+, only the field is honored. You should set the field for forward compatibility, and set the annotation if you want your changes to be effective against a pre-1.8 server.

**Comment by matthiasr** [comment] 2017-09-07 15:43
Perfect!

**Comment by clhodapp** [comment] 2017-10-24 21:27
Rather than manually duplicating the same content to multiple places, I've found that if you explicitly set both the alpha and the beta annotations to `null`, you can get the desired behavior out of the system in 1.7: initContainer updates will actually take effect and the actual API-level annotations will simply track the initContainers field.

**Comment by kevingessner** [comment] 2017-11-03 13:54
Thanks @clhodapp -- that's super clever, and it works on 1.6 as well.

**Comment by linse** [comment] 2017-11-14 20:29
@clhodapp I'm working with @kevingessner and found today that your fix worked only for existing deployments and not for new ones on 1.6. 
Just in case anyone else gets stuck on this, the error message is misleading (`Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1beta1" cannot be handled as a Deployment: unexpected end of JSON input`) and the config still passes fine with `--dry-run`. So not backwards compatible for us, unfortunately.

**Comment by clhodapp** [comment] 2017-11-14 21:23
Thanks for posting your finding, @linse. It sounds like the only real fix here is updating to 1.8 then.

**Comment by Noah-Huppert** [comment] 2018-06-21 01:19
I am still encountering this issue with Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.0", GitCommit:"c08fe9548257472151a8fa298bd6c3e9ea1b8c09", GitTreeState:"clean", BuildDate:"2018-06-06T11:34:07Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

I have tried setting the alpha and beta annotations to null.

**Comment by apodkutin** [comment] 2018-10-26 08:32
@linse, @clhodapp Actually, there is a way to avoid `Deployment in version "v1beta1" cannot be handled as a Deployment: unexpected end of JSON input)`
If there is no deployment created yet, you can remove:
```
annotations:
  pod.beta.kubernetes.io/init-containers: null
  pod.alpha.kubernetes.io/init-containers: null
```
and left only `initContainers:`, deployment will have been created without errors and init container will be there. 
And if you already have deployment in your namespace you can left:
```
annotations:
  pod.beta.kubernetes.io/init-containers: null
  pod.alpha.kubernetes.io/init-containers: null
```
with `initContainers:` in your descriptor an your deployment will have been updated along with the init container.
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.12", GitCommit:"3bda299a6414b4866f179921610d6738206a18fe", GitTreeState:"clean", BuildDate:"2017-12-29T09:00:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.12", GitCommit:"3bda299a6414b4866f179921610d6738206a18fe", GitTreeState:"clean", BuildDate:"2017-12-29T08:39:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
