### ISSUE TITLE
Very few PRs are merging

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#92937] opened 2020-07-09 15:45 UTC
I opted to open a new issue instead of re-opening https://github.com/kubernetes/kubernetes/issues/90647

The tide pool for kubernetes/kubernetes master is much larger than usual.  Put another way, a lot of PRs are eligible for merge, but they're not getting merged.  This is due to batches of PRs failing tide's retest-prior-to-merge step.

![Screen Shot 2020-07-09 at 8 32 47 AM](https://user-images.githubusercontent.com/49258/87059962-ca49c280-c1be-11ea-8209-25e343a58ffc.png)
(taken from: https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1&from=now-30d&to=now)

Some of this is likely due to a rush to land PRs before today's Code Freeze deadline (ref: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.19#tldr)

Some useful links for troubleshooting
- https://prow.k8s.io/tide-history?repo=kubernetes%2Fkubernetes&branch=master - what tide is doing (trigger / merge events)
- https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch - results of jobs for batches of PRs triggered by tide

Some links for context / prior discussion
- [#testing-ops from yesterday onward](https://kubernetes.slack.com/archives/C7J9RP96G/p1594227886310500)
- [#sig-testing thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1594304440039600)

/priority critical-urgent
/sig release
/sig testing
/milestone v1.19

FYI @kubernetes/ci-signal @kubernetes/release-team

**Comment by spiffxp** [comment] 2020-07-09 15:58
For folks who are concerned their PRs aren't going to land prior to Code Freeze: historically, as long as a PR is eligible for merge prior to Code Freeze, nobody's going to block it or kick it out.

In the past few months when we've encountered stuck merges, one thing that's been done is to apply a /hold to all PRs to see if we can force smaller batches / identify "bad" PRs.  In the event that we need to do this again, it would help if all PR's that are eligible for merge are in the v1.19 milestone.

I applied the v1.19 milestone to PRs matching `is:pr is:open label:lgtm label:approved label:"cncf-cla: yes" -milestone:v1.19 -label:do-not-merge/hold -label:do-not-merge/release-note-label-needed -label:do-not-merge/work-in-progress -label:needs-rebase base:master`.  This means I may have caught some PRs with outstanding test failures that should be addressed, but I'm going to generously assume they're flakes.

**Comment by spiffxp** [comment] 2020-07-09 21:45
So one behavior that's unusual is seeing `TRIGGER_BATCH` events so frequently, just looking at https://prow.k8s.io/tide-history?repo=kubernetes%2Fkubernetes&branch=master right now:
- 12:46
- 12:28
- 12:09
- 12:05
- 12:01
- 11:43
- 11:26
- 10:59
- 10:41
- etc.

We would expect to see this more like 60-120min apart, depending on how long e2e tests take.  

Looking at https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch reveals the status of the actual jobs in the batch:
- first off, there are much fewer actual batches of jobs listed here than triggers, not entirely sure what that means, but it may be attempts to retrigger jobs for the current batch instead of triggering a whole new batch
- second, many of the jobs have a grey triangle listed for their status, and a duration of ~15m30s - clicking through shows these are jobs that end with `Pod pending timeout`

e.g.: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-verify/1281298070046248960 -> prow job yaml
```
status:
  build_id: "1281298070046248960"
  completionTime: "2020-07-09T18:59:29Z"
  description: Pod pending timeout.
  pendingTime: "2020-07-09T18:43:59Z"
  pod_name: 24480ad4-c214-11ea-a4d3-1aa7ea4ca7ab
  startTime: "2020-07-09T18:43:55Z"
  state: error
```

Which comes from https://github.com/kubernetes/test-infra/blob/19165b62dc809df8169b41ce30ff79f509bc50f0/prow/plank/controller.go#L404.  So if a Pod has been stuck in PodPending for longer than 15min (https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L7), it's deleted.

This feels like a capacity/performance issue.  What's taking so long, and why now?

Looking around in slack discussion, there is speculation that `git clone` is taking too long -> https://github.com/kubernetes/test-infra/issues/18226

**Comment by saschagrunert** [comment] 2020-07-10 20:19
Am I correct that the main issue is a race between the tests to be finished? I assume first PR being successful tested on top of the latest master will get merged, whereas *all* other PRs will get retested after that.

If so, then we might solche this issue from a technical perspective by building-up a list of “staging” PRs instead of assuming all of them merged at the same time. Let’s say:

1. All PRs ready to merge (got initially tested successfully) go into `staging`
2. `staging` does only retest 1 PR at the same time, because this one is going to be merged

This way we can safe resources as well as streamline the merge process.

**Comment by spiffxp** [comment] 2020-07-10 23:45
@saschagrunert 
>Am I correct that the main issue is a race between the tests to be finished?

no, the intended behavior is described here: https://github.com/kubernetes/test-infra/issues/13551#issuecomment-646958533 

The problem is that, for the most part, neither the single PR nor batch of PR's are passing all of their jobs.  This happens because tests/jobs are flaky.  Capacity/resource issues are likely to exacerbate this.  I suspect we've been handling more PR traffic than usual during the rush to land before code freeze.  It could also be that PR's have landed which make tests flakier than before.

**Comment by BenTheElder** [comment] 2020-07-11 00:29
> It could also be that PR's have landed which make tests flakier than before.

![image](https://user-images.githubusercontent.com/917931/87212355-e9397900-c2d2-11ea-9beb-21824e89a628.png)

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=DisruptionController%20should%20block%20an%20eviction%20until%20the%20PDB%20is%20updated%20to%20allow%20it

https://github.com/kubernetes/kubernetes/pull/92860#issuecomment-656949226

**Comment by BenTheElder** [comment] 2020-07-11 17:45
The DisruptionController test should be fixed now.
We still have lots of (prow) pod timeouts, that still needs mitigating.

**Comment by BenTheElder** [comment] 2020-07-12 04:18
We merged another batch of 15, and a few singular PRs before that.
Still not very fast at all but, we are merging.

**Comment by spiffxp** [comment] 2020-07-13 21:40
<img width="1276" alt="Screen Shot 2020-07-13 at 2 36 20 PM" src="https://user-images.githubusercontent.com/49258/87356067-47a26980-c516-11ea-84b6-2de7c9bd906b.png">
from https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1&from=now-30d&to=now

The backlog cleared out over the weekend.  I'm not sure what if anything was done to specifically mitigate.  Suspect we may see continued problems as regular weekday PR traffic starts to pick back up.

**Comment by liggitt** [comment] 2020-07-18 23:02
The pool has drained but we are still seeing many many failures which appear to be infra failures:
* pod pending timeouts
* test jobs failing after 1-15 minutes with no build log output - it's unclear if the issue is with the clone, build, or something else…

**Comment by BenTheElder** [comment] 2020-07-19 07:05
Pretty sure it's clone + overloaded node but the logs are ... You can see them if you have access to stackdriver.

Mitigation so far: only helping along a queue test fix. Discussed avoiding clone from scratch but not enough time to actually ship something. I'm pretty behind on my other duties so once the queue drained 🤷‍♂️
Issue for this linked above.

**Comment by liggitt** [comment] 2020-07-20 22:15
> Pretty sure it's clone + overloaded node

I just found podinfo.json... at least for all the integration tests I linked the clonerefs init container looks like it exited successfully:

```
				{
					"name": "clonerefs",
					"state": {
						"terminated": {
							"exitCode": 0,
							"startedAt": null,
							"finishedAt": null
						}
					},
					"lastState": {},
					"ready": true,
					"restartCount": 0,
					"image": "gcr.io/k8s-prow/clonerefs:v20200717-cf288082e1",
					"imageID": "gcr.io/k8s-prow/clonerefs@sha256:e5d53c7cf20a2b5c42e8395184662ee0cde33fbf68b1ff791fab8b6137d5da4c",
					"containerID": "containerd://fa0a25dfbf9b544e812f1df11c2252047cd54b9accb94fc77af5cc2f6bd3a188"
				},
```

am I reading that correctly?

**Comment by liggitt** [comment] 2020-07-20 22:23
according to logs, https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/92416/pull-kubernetes-integration/1284408727339798528/podinfo.json failed on this step of the test script:
```
2020-07-18 15:01:43.130 EDT
+++ [0718 19:01:43] Building go targets for linux/amd64:
Info
2020-07-18 15:01:43.130 EDT
cmd/kube-apiserver
```

**Comment by BenTheElder** [comment] 2020-07-21 22:57
quick changes made today:
- all containers in test-pods in prow request at least 250m cpu unless otherwise specified
- pod-utils (including the clone step) request 100m cpu by default

no limits have been set as of yet.

**Comment by BenTheElder** [comment] 2020-07-22 00:40
Discussed with @liggitt a bit, we also just have excessive default presubmits, see for example everything in
https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=93308 (except cross, which is a sometimes-runs)

I'm going to do some cleanup on this. Some of them should not be controversial.

**Comment by liggitt** [comment] 2020-07-22 00:46
I'd divide those into categories for improvement like this:

immediate: should probably be post-submits or periodics set to notify relevant owners:
* pull-kubernetes-dependencies-canary
* pull-kubernetes-e2e-gce-device-plugin-gpu
* pull-kubernetes-files-remake

significantly overlapping tests ... can we move one to post-submit + notification:
* pull-kubernetes-e2e-gce (cos+docker)
* pull-kubernetes-e2e-gce-ubuntu-containerd (ubuntu+containerd ... already have containerd coverage via kind presubmits)

pair of performance tests (can we have just one performance presubmit?):
* pull-kubernetes-kubemark-e2e-gce-big
* pull-kubernetes-e2e-gce-100-performance

several tests that seem to just check ability to build... can we collapse these somehow:
* pull-kubernetes-bazel-build
* pull-kubernetes-typecheck
* pull-kubernetes-cross

**Comment by BenTheElder** [comment] 2020-07-22 00:50
> pull-kubernetes-dependencies-canary

this appears to exist purely due to testing GOPROXY, which has been enabled by default on all prowjobs for nearly a year, so I'm moving to disable that one.

**Comment by BenTheElder** [comment] 2020-07-22 00:54
filed https://github.com/kubernetes/test-infra/pull/18421 for the most straight-forward one.

> several tests that seem to just check ability to build... can we collapse these somehow:

possibly, bit of context.

cross only runs on some changes, but we could probably adjust which changes and/or move it out of presubmit / make it manual.

typecheck is cross-lite, it ensure the code typechecks for all platforms we target w/o actually compiling.
it may have overlap with the verify job now.

bazel-build only does linux/amd64, and builds allll the things.
the core release artifacts are more or less already build in the various e2e jobs, but the bazel build job also builds anything else that builds under bazel, which is still not everything in the repo ...

it has some overlap with the bazel-test job, which is going to build anything depended on by unit tests.

**Comment by liggitt** [comment] 2020-07-22 13:37
the 1.19 merge pool has drained, and we're actually seeing batches pass now, so I don't think this is release blocking any more. Lowered priority to important-soon, and moving to v1.20. This remains important for CI health, so it would be good to have a concrete criteria for closing this and to make progress on it (or open individual issues for the items/categories mentioned in https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662178519)

/priority important-soon
/milestone v1.20

**Comment by onlydole** [comment] 2020-07-22 21:10
@BenTheElder / @spiffxp / @liggitt - do you know who might be the best assignee or assignees for this ticket going forward?

**Comment by liggitt** [comment] 2020-07-22 21:12
I think a mega ticket like this is probably not very actionable. Individual issues for the categories mentioned in https://github.com/kubernetes/kubernetes/issues/92937#issuecomment-662178519 would be easier to target

**Comment by BenTheElder** [comment] 2020-07-24 00:59
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93264/pull-kubernetes-e2e-kind/1286461110551056384

we still have what appear to be timeout from clonerefs
I still think we probably want to pre-clone k/k in the clonerefs image, but that will require a decent bit of work in test-infra

**Comment by wojtek-t** [comment] 2020-07-24 12:28
> pair of performance tests (can we have just one performance presubmit?):
> pull-kubernetes-kubemark-e2e-gce-big
> pull-kubernetes-e2e-gce-100-performance

I think there is a gain from having both (100-node is a real clusters that is catching real problems), kubemark is 500-node one (so not real cluster, but visibly larger).
What we're going to do though is to speed up the tests significantly [2-3x, excluding cluster creation/deletion] (there is some work towards that already happening as we speak, though it will probably take couple more months...)

**Comment by liggitt** [comment] 2020-07-24 12:49
> I think there is a gain from having both (100-node is a real clusters that is catching real problems), kubemark is 500-node one (so not real cluster, but visibly larger).

Both types of tests have value, but I question whether they are both appropriate for presubmit (both because of duration and cost of running them on every push of every PR when CI infrastructure is already overcommitted)


> What we're going to do though is to speed up the tests significantly [2-3x, excluding cluster creation/deletion] (there is some work towards that already happening as we speak, though it will probably take couple more months...)

That sounds great, but the current state is not really sustainable for O(months)

**Comment by wojtek-t** [comment] 2020-07-24 14:12
We briefly chatted with Jordan offline.

I would be fine with getting rid of one of the presubmits, if we have ability to block merges on postsubmits.
Otherwise, we're risking piling up regressions which are super hard to debug (we were at this stage 2-3 years ago and that was a nightmare).

**Comment by riking** [comment] 2020-07-30 09:00
Perhaps there is space for two categories of presubmits: "run on every push" and the new category "run on merge attempts, and also some pushes"

Or change the definition of "postsubmit" to that second one, and the words to something else. Things that only run on trunk could be "hourly" or "daily".

**Comment by liggitt** [comment] 2020-07-30 13:15
I think the definitions we have today are fine:
* presubmit = runs on PR commits before merge to master
* postsubmit = runs asynchronously after each merge to master
* periodic = runs on HEAD of master at regular intervals

I'm not in favor of turning some of our required presubmits into serial jobs ... we already have O(hours) approve-to-merge delay, and that would make it worse.

**Comment by BenTheElder** [comment] 2020-08-02 22:12
Regarding specifically having a lot running in presubmit:
- I moved `pull-kuberntes-cross` from `run_if_changed` top optional / periodic
- On the master branch (not the older ones) @liggitt moved `verify-files-remake` to optional / periodic
- We're enacting some CI policies https://github.com/kubernetes/test-infra/issues/18551

We still appear to have have 15 jobs running on _every_ PR.

Some of this seems clearly in excess.

All of these run containerd e2e now:
- pull-kubernetes-e2e-gce-ubuntu-containerd (containerd 1.4.0-beta.2)
- pull-kubernetes-e2e-gce (containerd 1.3.2)
- pull-kubernetes-e2e-kind (containerd ~HEAD /  v1.4.0-beta.2-43-gd184a0a3)
- pull-kubernetes-e2e-kind-ipv6 (containerd ~HEAD /  v1.4.0-beta.2-43-gd184a0a3)
- pull-kubernetes-conformance-kind-ga-only-parallel (containerd ~HEAD /  v1.4.0-beta.2-43-gd184a0a3)
- pull-kubernetes-e2e-device-plugin-gpu (containerd 1.3.2)
- pull-kubernetes-kubemark-e2e-gce-big (containerd 1.3.2)
- pull-kubernetes-e2e-gce-100-performance (containerd 1.3.2)

This does not:
- pull-kubernetes-node-e2e (dockerd)


I think we should pick between `pull-kubernetes-e2e-gce` and `pull-kubernetes-e2e-gce-ubuntu-containerd` config and dedupe as `pull-kubernetes-e2e-gce`, these are the same except for containerd version and node OS (which have some overlap with the kind jobs which have recent containerd and ubuntu distro nodes / underlying prow nodes). cc @dims 

I think we should also move `pull-kubernetes-e2e-device-plugin-gpu` to periodic release blocking / presubmit optional (it's very specific and uses special resources). It was added when device plugin was much newer and CI was much smaller.

**Comment by dims** [comment] 2020-08-03 02:28
@BenTheElder i'd prefer using `pull-kubernetes-e2e-gce-ubuntu-containerd` over `pull-kubernetes-e2e-gce`. (COS vs Ubuntu and newer containerd)

**Comment by liggitt** [comment] 2020-08-03 02:31
If we have exposure to ubuntu nodes and newer containerd via pull-kubernetes-e2e-kind, would pull-kubernetes-e2e-gce be a better choice?

**Comment by dims** [comment] 2020-08-03 02:50
@liggitt unfortunately kind does not do a "real" multi-node with cloud init etc :(

**Comment by spiffxp** [comment] 2020-08-04 16:18
https://github.com/kubernetes/test-infra/issues/18530 describes some of the more immediate changes we're making around resource requests etc.  Doesn't cover any of the specifics around shuffling jobs around or optimizing specific jobs being discussed above.

**Comment by BenTheElder** [comment] 2020-08-04 18:09
> @liggitt unfortunately kind does not do a "real" multi-node with cloud init etc :(

- For the purposes of testing Kubernetes, multi-node X operating system is not really relevant. (multi-node logic is not OS specific and happens at a higher layer, also relatively few tests depend on multi-node)
- cloud-init is not something we should be focused on testing in kubernetes presubmit (!)
- The nodes are real enough for the most part. The current gap in test coverage is artificial and will largely be resolved by stabilizing CI capacity (so we can have comparable resources to the GCE VMs we create for cloudy jobs)

That said, I'm in favor of deduplicating `pull-kubernetes-e2e-gce` to be ubuntu node based, for the newer containerd.
The other GCE e2e presubmits are still COS anyhow.

I'll file a PR.

**Comment by spiffxp** [comment] 2020-08-08 00:16
https://github.com/kubernetes/test-infra/issues/18729 covers reevaluating merge-blocking jobs

**Comment by BenTheElder** [comment] 2020-08-20 05:16
moving to https://github.com/kubernetes/test-infra/issues/18729 and https://github.com/kubernetes/test-infra/issues/18551
PRs have been merging and other issues are tracking specific actions being taken forward
/close

**Closed** 2020-08-20 05:16 UTC
Labels: priority/critical-urgent, priority/important-soon, sig/release, sig/testing
