### ISSUE TITLE
StartupProbe seem to only restart/trigger with pod restart

### ISSUE THREAD

**Issue by ckocyigit** [kubernetes/kubernetes#107817] opened 2022-01-27 11:08 UTC
### What happened?

We're running Openshift in a enterprise environment and noticed something strange happening to Deployments with all 3 probes (liveness, readiness and startup). 

If a new pod is beeing rolled out the container within is booting up without issues. However if for some reason (e.g. application error) the container within the same pod is restarting the startupProbe does not seem to trigger and is not preventing the liveness probe to kill the container after its initialDelay.

### What did you expect to happen?

When a new container within the same pod is restarting the startupProbe should also trigger/start to prevent other probes to kill the container prematurally.

### How can we reproduce it (as minimally and precisely as possible)?

Prerequisites:
- A Deployment/DC with 3 or atleast 2 probes (startup and liveness)

Steps to reproduce:
- Wait for the Deployment/Pod to be started and healthy 
- Kill the container within the pod with e.g. "oc/kubectl debug node/<nodename> && crictl stop <container-id>"
- A new container within the pod is starting and should be killed after initialDelays of livenessprobe

### Anything else we need to know?

All the probes use the Container command method.

### Kubernetes version

<details>

```console
Kubernetes Version: v1.19.14+fcff70a
```

</details>

### Cloud provider

<details>
Atos/Red Hat
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Coming Soon
</details>

**Comment by smarterclayton** [comment] 2022-02-01 02:54
Reading the doc (and from vague memory) the startup probe is part of pod initialization, vs container initialization.  However, the website documentation is ambiguous.  No matter what, the api doc and the website doc need to be more specific about intent:

> StartupProbe indicates that the Pod has successfully initialized. If specified, no other probes are executed until this completes successfully.  If this probe fails, the Pod will be restarted, just as if the     livenessProbe failed. This can be used to provide different probe     parameters at the beginning of a Pod's lifecycle, when it might take a long     time to load data or warm a cache, than during steady-state operation. This     cannot be updated. 

(godoc)

**Comment by SergeyKanzhelev** [comment] 2022-02-02 18:47
This might be fixed already in later versions of k8s. 1.19 is out of support in open source. Please try to reproduce on later version

/triage needs-information

**Comment by jmcmeek** [comment] 2022-02-08 02:35
Is this behavior is specific to OpenShift 4.6 - which uses Kubernetes 1.19?  It looks like a change from https://github.com/kubernetes/kubernetes/pull/101093 is missing.

https://github.com/openshift/kubernetes/blame/release-4.6/pkg/kubelet/prober/worker.go#L246-L248 has
```
		// we keep it running to make sure it will work for restarted container.
		if w.probeType == startup {
			return false
```
vs
https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/kubelet/prober/worker.go#L246-L248, which keeps the comment but returns `true`

OpenShift 4.7 matches Kubernetes - assuming no other changes that impact that.

**Comment by wzshiming** [comment] 2022-02-16 13:46
Fixed in https://github.com/kubernetes/kubernetes/pull/101225
You can try to upgrade and try again

**Comment by SergeyKanzhelev** [comment] 2022-02-16 18:31
/close

please re-open if it still repro

**Closed** 2022-02-16 18:32 UTC
Labels: kind/bug, sig/node, triage/needs-information, needs-triage
