### ISSUE TITLE
Flake error: google: could not find default credentials.

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#28608] opened 2016-07-07 15:52 UTC
`error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.` appears in a lot of flakes. Speculation is that the metadata server is slow to respond. 

So far, these are the issues where this message has popped up:

#28569 
#28565 
#28523 
#28507 
#28493 
#28439 
#28437 
#28429 
#28426 
#28420 
#28293 
#27976 
#27839 
#27715 
#27156 
#26715 
#26490 

Sample failed run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/10664

@cjcullen since this is dealing with auth, I'm initially assigning to you. Feel free to reassign to someone more appropriate.

**Comment by krousey** [comment] 2016-07-07 16:44
cc @fejta @spxtr

**Comment by cjcullen** [comment] 2016-07-08 00:02
This has the same root cause at #28612. I'm going to close this as a duplicate.

**Closed by cjcullen** 2016-07-08 00:02 UTC
Labels: kind/flake, priority/P0
