### ISSUE TITLE
Client cert auth does not work when it is the only kind of auth in use.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#25692] opened 2016-05-16 21:13 UTC
User on slack sig-auth channel reported that when only client-cert auth was enabled on the apiserver, that kubelets could not register. 

Slack conversation: 
https://kubernetes.slack.com/archives/sig-auth/p1463428269000258

When basic auth was enabled too (which user does not want on) then kubelets could register fine.
 User showed kubelet config that clearly just uses a client cert, not a password.

This seems like a bug.

Looking at this code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/authenticator/authn.go#L113

it appears we don't use the Union Authenticator if there is only one authenticator.  Seems like this may be source or bug user reported.

**Comment by erictune** [comment] 2016-05-16 21:14
@kubernetes/sig-auth

**Comment by erictune** [comment] 2016-05-16 21:15
Temporary workaround is to enable basic auth or token file with empty file.

**Comment by mward29** [comment] 2016-05-16 21:19
Thank You for validating this @erictune

**Comment by liggitt** [comment] 2016-05-17 01:49
union auth shouldn't be needed for cert auth to work, but I would have expected at least cert and service account token auth, which would have enabled union auth as well.

**Comment by liggitt** [comment] 2017-02-12 05:03
I'm unable to reproduce this. Closing due to age.

**Closed by liggitt** 2017-02-12 05:03 UTC
Labels: priority/backlog, sig/auth, team/control-plane (deprecated - do not use)
