### ISSUE TITLE
Provide an option to disable/mock cadvisor in kubelet

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#16296] opened 2015-10-26 19:44 UTC
Is there a way to disable cadvisor when kubelet starts? I see there's an option to disable cadvisor network port so it doesn't leak certain information, but is there a way to disable cadvisor all together?

**Comment by yujuhong** [comment] 2015-10-27 00:53
@huang195, kubelet relies on cadvisor for machine and container information, and it cannot be turned off as of now. If you are willing to compile kubelet yourself, you can potentially create a [mock](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_fake.go) to stub out cadvisor. Note that you'll have to supply valid fake data too (e.g., https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_test.go#L2314).

**Comment by vishh** [comment] 2015-10-27 01:07
`--cadvisor-port=0` should disable cadvisor from exposing its REST APIs.

**Comment by huang195** [comment] 2015-10-27 14:43
@yujuhong thanks, that's what I was afraid of to be the only way to achieve this :)
@vishh I'm looking to disable cadvisor from running as opposed to disabling its REST APIs.

The reason I want to disable cadvisor is that cadvisor seems to take a lot of cpu within the kubelet process when running say 100 pods on a node, with each pod having nothing more than 2 pause containers (1 is the infrastructure container and 1 is dummy container). I know the default max pod is set to 40, but I wanted to set it to a bigger number and see how it behaves. The system was bogged down pretty bad with docker daemon and kubelet both taking closer to 100% cpu on 2 of 4 cores on my local machine. `go pprof` did show that cadvisor was taking more than 50% of the kubelet's time. 

This is using kubernetes code from the head just a few days ago and running docker 1.8.3 on ubuntu 14.04 64-bit.

**Comment by huang195** [comment] 2015-10-27 14:49
One other thing to worth noting is with a 100 pods per node, kubernetes seems to be very unstable with its persistent state. After creating 100 pods, I tried to delete them, and some were removed when I ran `kubectl get pods`, but a lot of them just get stuck in Terminating state forever. 

Kubelet's log showed the following error message:
kubelet.go:1761] Failed to cleanup terminated pods: not all pods were successfully terminated

When running `docker ps`, all the containers did get killed by the kubelet, but it seems pods are not cleaned up properly in etcd for some reason. What I ended up doing is to remove these pods from etcd manually, and restarting various kubernetes components to get back to a clean state. Yes I did increase max-pods parameter on kubelet, but I was expecting some slow down, but not a mangled state in etcd.

**Comment by yujuhong** [comment] 2015-10-27 14:50
@huang195, FYI, we are working on scaling #pods on the node by improving kubelet and docker cpu usage (#12540).

There is a known cadvisor goroutine leak in kubernetes HEAD, the fix is already in cadvisor and we are updating our godeps to include the new cadvisor (#15805). It's quite likely that your cluster also has this leak if it's from a few days ago.

**Comment by huang195** [comment] 2015-10-27 14:51
@yujuhong that's great to hear! Will track these issues and pull them when they're merged.

**Comment by huang195** [comment] 2015-10-27 14:58
@yujuhong I saw the other issue you pointed to earlier, and it seems this cadvisor behavior was only introduced recently. Instead of waiting things to be merged in the head, is there an older release that is free of this problem? release-1.0 or release-1.1? Thanks!

**Comment by yujuhong** [comment] 2015-10-27 15:01
> When running docker ps, all the containers did get killed by the kubelet, but it seems pods are not cleaned up properly in etcd for some reason. What I ended up doing is to remove these pods from etcd manually, and restarting various kubernetes components to get back to a clean state. Yes I did increase max-pods parameter on kubelet, but I was expecting some slow down, but not a mangled state in etcd.

I suspect this is due to the low QPS limit of apiserver client in kubelet. In order not to overwhelm the apiserver, the QPS is set to a conservative value (5.0) for now. If you have many apiserver requests and the sending rate is too low, the channel might be full and starts dropping requests. Eventually all the requests will be resent, but it may take a long while for them to complete. We are planning to lift this artificial QPS limit and rely on the apiserver backpressure to control the rate (#14955).

**Comment by yujuhong** [comment] 2015-10-27 15:02
> @yujuhong I saw the other issue you pointed to earlier, and it seems this cadvisor behavior was only introduced recently. Instead of waiting things to be merged in the head, is there an older release that is free of this problem? release-1.0 or release-1.1? Thanks!

Yes, both release-1.0 and 1.1 do not have this problem.

**Comment by huang195** [comment] 2015-10-27 15:07
@yujuhong thanks. I will try 1.1 out first and report back if there's any problem.

**Comment by huang195** [comment] 2015-10-27 16:17
@yujuhong You're right on both accounts. I switched from head to release-1.1. By putting a `sleep 1` in between `kubectl delete pod`, I no longer need to manually clean up data in etcd, so it most likely have been the QPS parameter being set too low. 

However, I'm still having a problem with the cadvisor taking so much cpu. After `pprof`, I see cadvisor is still taking 33% cpu time in the kubelet (it was 50%+ using head). It's an improvement, but is there anyway to have it check for fewer things or increase its periodicity so it doesn't take this much resources?

**Comment by yujuhong** [comment] 2015-10-27 16:51
> However, I'm still having a problem with the cadvisor taking so much cpu. After pprof, I see cadvisor is still taking 33% cpu time in the kubelet (it was 50%+ using head). It's an improvement, but is there anyway to have it check for fewer things or increase its periodicity so it doesn't take this much resources?

Could you post the cpu profile graph here? Thanks!

**Comment by huang195** [comment] 2015-10-27 17:13
![kubelet-page-0](https://cloud.githubusercontent.com/assets/8008677/10766174/8c823754-7cac-11e5-97a4-41c8d216fd38.jpg)

**Comment by vishh** [comment] 2015-10-27 18:10
Hmm. It looks like cadvisor is taking about 33% of the cpu time occupied by
the kubelet overall. And nearly 75 % of the time occupied by cadvisor is in
parsing network stats. cAdvisor [PR 870](
https://github.com/google/cadvisor/pull/870/) introduced some changes
around handling network stats. The 're' handling seems to be expensive.

**Comment by huang195** [comment] 2015-10-27 18:16
@vishh if you look at my earlier comment, 33% cpu is already an improvement of what I had earlier. It was 50%+ previously.

**Comment by vishh** [comment] 2015-10-27 18:17
Yeah. We have been identifying old and new issues and fixing them. Thanks
for reporting this issue.

**Comment by yujuhong** [comment] 2015-10-27 18:31
@jimmidyson FYI

**Comment by jimmidyson** [comment] 2015-10-27 19:01
There is probably no need to do the expensive regexp here & can rely on `Sscanf` alone. Btw the current way was an improvement over the old way... I'll get a fix in quickly for this. Do we want this in 1.1?

**Comment by huang195** [comment] 2015-10-27 19:06
I'm just curious of this behavior that I was seeing: when I was looking at cadvisor web ui, I keep seeing spikes every 10 seconds or so. However, cadvisor has 2 housekeeping options, and the global one is 1m, and the per-container one is 1s, by default. This is independent of how many pods I have. Even I lowered the number of pods on the host to 30 pods, I still see this clear 10-sec cpu spike.

**Comment by jimmidyson** [comment] 2015-10-27 20:19
Pushed perf improvement to cadvisor. We'll need to tag & bump cadvisor - I already have an open PR to do that so I'll update that.

**Comment by jimmidyson** [comment] 2015-10-27 20:19
Do we want this in 1.1?

**Comment by yujuhong** [comment] 2015-10-27 20:20
> Do we want this in 1.1?

I don't think we need this in 1.1, given that @huang195 runs 100 pods per node, which is well beyond our limit of 40 pods :)

**Comment by yujuhong** [comment] 2015-10-27 20:21
> Even I lowered the number of pods on the host to 30 pods, I still see this clear 10-sec cpu spike.

kubelet syncs all pods (i.e., running a bunch of docker list/inspect commands) every 10 seconds by default, which'd cause cpu spikes.

**Comment by vishh** [comment] 2015-10-27 20:38
This sounds like a bug fix. So I'd vote for cherry-picking this and
possibly including in a patch release.

**Comment by huang195** [comment] 2015-10-28 15:08
@yujuhong I checked the 10-sec cpu spikes, and it just puzzles me more now :(
cadvisor has an option "housekeeping_interval" that by default is set to 1 second, after I changed this value to 30 seconds, I see the cpu spikes were about once 30 seconds. I then set it to 15 seconds, and the cpu spikes went to every 15 seconds or so. Is PodUpdate impact by "housekeeping_interval" in some way? I didn't see it in the code, but cadvisor's web ui is showing it as such.

**Comment by yujuhong** [comment] 2015-10-28 17:27
@huang195, if you changed the housekeeping interval to 30s, it effectively changed the frequency that cadvisor gathers the stats (memory usage). Since cadvisor would only gather data once every 30 seconds, it's natural you'd only see the spike ever 30 seconds :)

I think the majority of cpu usage should be from kubelet and docker for the periodic syncs. I'd be surprised if it's not. A better experiment would be to change the sync interval in kubelet from 10 seconds to 30 seconds, and you should see the cpu spike freqency changes.

**Comment by huang195** [comment] 2015-10-28 19:58
@yujuhong I think I found the reason for this. As mentioned in the beginning, I'm trying to scale up the number of pods per node well beyond the recommended 40, so I was trying to see if I can get 100 or even 200 pods on a single node (not practical but just for the sake of trying it out). At 100-200 pods per node, the UpdatePod part of the kubelet code that runs every 10 seconds will run continuously (from what I can see, parsing and validating json files that it gets back from docker restapis). This means it will not spike every 10 seconds, but rather occupying cpu continuously. It also explains why when I change housekeeping_interval, the cpu spike interval also changes accordingly, because at those times cadvisor will put extra load on kubelet and docker engine. 

I remember seeing somewhere that json parsing is getting reworked.

**Comment by yujuhong** [comment] 2015-10-28 20:10
@huang195, my 100 pod node actually still shows the 10 second kubelet/docker cpu spikes (+1.5 core difference on a n1-standard-2 gce machine), which I believe are from the periodic pod syncs. If you saw smaller cpu spikes, your explanations would make sense.

> I remember seeing somewhere that json parsing is getting reworked.

Might be #3338.

**Comment by huang195** [comment] 2015-10-29 14:53
@yujuhong that was my initial impression as well that the 10-sec was due to pod syncs as its default time is every 10 seconds. However, after some testing, it seems to be not the case when we're in the 100-200 pods per node range. If you still have your 100-pod node, try to restart your kubelet with housekeeping_interval set to 30 seconds, you will see your 10-sec cpu spikes will be replaced by 30-sec cpu spikes.

cadvisor seems to do something strange with housekeeping_interval, and when this value is set to a small number like 1-5 seconds, it seems to run not every 1-5 seconds, but like 10 seconds. And if the value is set to a larger number, like 30-60 seconds, it seems to honor that. I don't know if this is because of the unusual larger number of pods I'm running per node or other reasons.

**Comment by yujuhong** [comment] 2015-10-29 21:57
@huang195, how did you set the housekeeping_interval for cadvisor and also how did you collect the cpu usage? It'd be nice to know the details to make sure we are on the same page.

To provide more reference points, I collected cpu usage for kubelet and docker with and without cadvisor (using a complete mock).

**CPU USAGE WITH CADVISOR MOCKED OUT, kubelet sync interval: 10s**
![cpu_w_cadvisor_mock](https://cloud.githubusercontent.com/assets/10524058/10830269/fe290474-7e3b-11e5-9f46-d89acf642feb.png)
You can clearly see the 10s cpu spikes and the near-zero cpu usage between spikes (due to the lack of cadvisor). 

**CPU USAGE WITH CADVISOR MOCKED OUT, kubelet sync interval: 100s**
![cpu_sync100s_w_cadvisor_mock](https://cloud.githubusercontent.com/assets/10524058/10831513/53e912ee-7e43-11e5-9f9a-e102e8bb3e61.png)
The major spikes now happens once every 100 seconds.

**CPU USAGE, kubelet sync interval: 10s**
![cpu](https://cloud.githubusercontent.com/assets/10524058/10832660/e8c10d3a-7e49-11e5-99e7-1e2ef6310abb.png)
Clearly, we see 10s-interval spikes, but the overall cpu usage is higher than when cadvisor is mocked out.

**CPU USAGE, kubelet sync interval: 100s**
![cpu_sync100s](https://cloud.githubusercontent.com/assets/10524058/10832683/08f53f90-7e4a-11e5-8de3-0c6b13bd2924.png)
As expected, the docker-daemon cpu usage is relatively low besides the 100s-interval spikes. Surprisingly, though, **kubelet still exhibits small-to-medium spikes frequently**. I'll dig into them more later.

**Comment by yujuhong** [comment] 2015-10-30 00:30
Update: I realized we had many fixes in cadvisor which were merged yesterday to release-1.1, so I reran the test using the latest commit in the branch (cadvisor rev aa6f80814bc6fdb43a0ed12719658225420ffb7d).

Using the new version, running ~100 pods with kubelet periodic sync almost completely turned off (once every hour). In other words, kubelet's cpu usage is mainly from cadvisor, serving states, sync node status, and potentially some cleanup work.
![cpu_newcadvisor](https://cloud.githubusercontent.com/assets/10524058/10835455/e0785bc2-7e5f-11e5-8a03-19593fe257e0.png)

This seems more reasonable than before, and it's clear that kubelet's pod syncing is still the major bottleneck. Besides, a few upcoming changes would address some issues. E.g., the new kubelet metrics API would allow heapster to query stats of all container in one request, which is important as #pods per node scales.

Just FYI, below the cpu profile (over 120s) for this test.
![newcadvisor](https://cloud.githubusercontent.com/assets/10524058/10835666/50824e58-7e62-11e5-9e66-ee11f8ba1528.png)

**Comment by yujuhong** [comment] 2015-10-30 00:37
@huang195, I would suggest you getting the latest release-1.1, as from my experiment, the cadvisor cpu usage changed significantly. If you still run into issues, feel free to ping me.

By the way, I filed https://github.com/google/cadvisor/issues/945 to detect performance regression.

I also find disabling/faking cadvsior in kubelet useful for debugging and tracking resource usage, but I am afraid to add a new flag purely for debugging. Alternatively, we could add something similar to hollow kubelet, but only mock out cadvisor. Or, it'd be nice if we can provide a flag to turn off cadvisor's stats collection (which is the majority of the resource usage), without impacting the normal function required by kubelet (e.g., reporting machine info and disk usage). @kubernetes/goog-node, thoughts?

**Comment by huang195** [comment] 2015-10-30 01:43
@yujuhong thanks for that detailed analysis of the problem. To answer your questions:
1) I was using cadvisor's web ui to look at resource usage, just so that I don't introduce additional load to the system I'm trying to figure out where the overheads are
2) I was specifying housekeeping_interval as a cmdline option when starting kubelet process

What you have shown is similar to what I was seeing as well, but I will try out the latest commit from 1.1 as it seems to quiet down cadvisor's load to the system quite significantly. 

One question - I noticed that your `go pprof` looks very different from the one I posted above. I was pointing mine to http://<kubelet ip>:10248 to collect my cpu profile. How were you collecting your cpu profile?

**Comment by huang195** [comment] 2015-10-30 01:46
@yujuhong one other question: is there an easy way to mock out the cadvisor? It'd be nice to have a flag to specify what monitoring tool to use, e.g., default cadvisor, fake cadvisor, and other monitoring tools. Makes kubelet a bit more modular.

**Comment by huang195** [comment] 2015-10-30 13:37
@yujuhong I see you pointed me to cadvisor.mock previously. I guess you used this one so cadvisor essentially is disabled?

**Comment by yujuhong** [comment] 2015-10-30 15:33
> @yujuhong thanks for that detailed analysis of the problem. To answer your questions:
> 1) I was using cadvisor's web ui to look at resource usage, just so that I don't introduce additional load to the system I'm trying to figure out where the overheads are

This would not work once you disable cadvisor, and it would give you inconsistent stats when you adjust the housekeeping interval in cadvisor. Basically you would be monitoring the stats while changing how you collect stats :)

> 2) I was specifying housekeeping_interval as a cmdline option when starting kubelet process

kubelet doesn't expose this flag. Did you modify kubelet to do that?
> 
> What you have shown is similar to what I was seeing as well, but I will try out the latest commit from 1.1 as it seems to quiet down cadvisor's load to the system quite significantly.
> 
> One question - I noticed that your go pprof looks very different from the one I posted above. I was pointing mine to http://:10248 to collect my cpu profile. How were you collecting your cpu profile?

I think you meant 10250, 10248 is a healthz port :-)

I think the difference came from different cadvisor versions, as I mentioned before, there has been a lot of fixes in cadvisor lately.

**Comment by yujuhong** [comment] 2015-10-30 15:39
> @yujuhong I see you pointed me to cadvisor.mock previously. I guess you used this one so cadvisor essentially is disabled?

Yes, I used the mock to return some valid machine and version info. FYI, the code is https://github.com/kubernetes/kubernetes/compare/master...yujuhong:cadvisor_mock

There is also [fake cadvisor](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_fake.go) that is being used in [kubemark](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubemark/hollow-node.go). kubemark mocks out most the components in kubelet for the cluster scalability test. I haven't tried using only fake cadvisor, so I am not sure if it'd work without any modifications.

**Comment by vishh** [comment] 2015-10-30 15:42
Kubelet is using cadvisor for some of its internal operations like garbage collection and so it is not recommended to mock out cadvisor.

**Comment by yujuhong** [comment] 2015-10-30 15:44
> Kubelet is using cadvisor for some of its internal operations like garbage collection and so it is not recommended to mock out cadvisor.

This is mostly for benchmarking/debuging, etc, and I'd advocate that we should split cadvisor interface into a few, so it's clear what's needed for each component in kubelet.

**Comment by yujuhong** [comment] 2015-10-30 15:46
> Kubelet is using cadvisor for some of its internal operations like garbage collection and so it is not recommended to mock out cadvisor.

Please also see https://github.com/kubernetes/kubernetes/issues/16296#issuecomment-152368025 for the use cases.

**Comment by huang195** [comment] 2015-10-30 19:12
@yujuhong housekeeping_interval was an available option in `kubelet --help`, but I guess the option is passed to cadvisor eventually. I didn't modify any code.

**Comment by huang195** [comment] 2015-10-30 19:17
@vishh Can you explain what do you mean by "kubelet is using cadvisor for internal operations like garbage collection"? I briefly looked at that part of the kubelet code, and it looks like kubelet is using cadvisor to collect information about file system, disk, local machine, images, orphaned containers, etc. When you say garbage collection, you mean things like removing dead containers and removing container images if disk usage is too high, etc.? 

Just for the sake of discussion, let's say I have scripts that periodically scans for dead containers and unused images, and removing them. Will using mocked cadvisor as @yujuhong has done cause any bad side effects?

**Comment by vishh** [comment] 2015-10-30 19:23
Kubelet uses cadvisor to export machine capacity, track filesystem usage, perform garbage collection of old containers and images, monitoring resource usage, etc. I might be missing other use cases. 
Without cadvisor, scheduling will be broken.

Keep in mind that kubelet uses dead containers as a tombstone. So it is not advised to perform image or container GC behind kubelet.

**Comment by yujuhong** [comment] 2015-10-30 19:35
> @yujuhong housekeeping_interval is an available option in kubelet --help (at least when i pulled from the head of release-1.1 yesterday), but I guess the option is passed to cadvisor eventually. I didn't modify any code.

Ah..that's pulled directly from cadvisor. I didn't check the code there. Sorry for the confusion. 

Also, I forgot to mention that when using cadvisor mock, you'll have to gather the stats yourself since cadvisor no longer does that for you. An easy approach is to run a small script to check `/sys/fs` periodically. If you do it every second and only for kubelet and docker, the overhead should be negligible.

**Comment by yujuhong** [comment] 2015-10-30 19:46
> Kubelet uses cadvisor to export machine capacity, track filesystem usage, perform garbage collection of old containers and images, monitoring resource usage, etc. I might be missing other use cases. 
> Without cadvisor, scheduling will be broken.

Clarification: scheduler only looks at the "capacity" of the node as of now; it does not take into account of the actual resource usage. This may change in the future, but for now as long as your mock provides the correct cpu, memory info and disk capacity, scheduler would be fine.

As for garbage collection, only image GC asks cadvisor for docker image FS usage.
Kubelet does use cadvisor to detect Out-of-disk situation and rejects pods (also report in node status in HEAD). The mock would need to provide disk usage in general.

I am not encouraging disabling cadvisor in normal circumstances, but it's certainly useful when studying the performance and resource usage. Apart from essential capacity information (which can be gathered without cadvisor), we should allow container stats collection to be disabled for debugging.

> Keep in mind that kubelet uses dead containers as a tombstone. So it is not advised to perform image or container GC behind kubelet.

Out-of-band container GC could mess up the pod status, causing irregular behaviors in kubelet.

**Comment by huang195** [comment] 2015-10-30 20:32
@vishh @yujuhong thank you for the detailed explanation on the pros and cons on this unusual way of running cadvisor in kubelet

**Comment by yujuhong** [comment] 2015-10-30 23:38
> @vishh @yujuhong thank you for the detailed explanation on the pros and cons on this unusual way of running cadvisor in kubelet

No problem. I am happy to discuss 100 pods scalability issues.

**Comment by tanen01** [comment] 2016-02-04 05:57
I am running v1.1.7 and I can see kubelet using a lot of CPU time. I don't have much pprof expertise, but I think the pprof output below on kubelet shows cadvisor being the main culprit?

```
(pprof) top 10 -cum
0.02s of 7.85s total ( 0.25%)
Dropped 222 nodes (cum <= 0.04s)
Showing top 10 nodes out of 153 (cum >= 2.01s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%      6.23s 79.36%  runtime.goexit
         0     0%     0%      5.42s 69.04%  github.com/google/cadvisor/manager.(*containerData).housekeeping
         0     0%     0%      5.27s 67.13%  github.com/google/cadvisor/manager.(*containerData).housekeepingTick
     0.01s  0.13%  0.13%      5.27s 67.13%  github.com/google/cadvisor/manager.(*containerData).updateStats
         0     0%  0.13%      5.09s 64.84%  github.com/google/cadvisor/container/libcontainer.GetStats
     0.01s  0.13%  0.25%      4.39s 55.92%  github.com/google/cadvisor/container/raw.(*rawContainerHandler).GetStats
         0     0%  0.25%      2.54s 32.36%  github.com/google/cadvisor/container/libcontainer.networkStatsFromProc
         0     0%  0.25%      2.51s 31.97%  github.com/google/cadvisor/container/libcontainer.scanInterfaceStats
         0     0%  0.25%      2.48s 31.59%  github.com/docker/libcontainer/cgroups/fs.(*Manager).GetStats
         0     0%  0.25%      2.01s 25.61%  fmt.Sscanf
```

As pointed out by @huang195 , one way to influence kubelet's CPU usage pattern is to override  --global-housekeeping-interval and --housekeeping-interval. 

I have set these to 5 minutes and 1 minute respectively and I can immediately see kubelet no longer hogging CPU time (similar to what it was in v1.0)

My questions are:
1. Is this currently being treated as a defect and being worked?
2. Are my values for --global-housekeeping-interval and --housekeeping-interval safe? What would be the side effect increasing these intervals?

Thanks

**Comment by timstclair** [comment] 2016-02-04 20:40
> 1. Is this currently being treated as a defect and being worked?
Yes. We've made a lot of improvements to cAdvisor performance in the past few months, but we're also aware that there is more to do. Separating cAdvisor from the Kubelet will help us to isolate these issues and help make more future improvements.

> 2. Are my values for --global-housekeeping-interval and --housekeeping-interval safe? What would be the side effect increasing these intervals?
cAdvisor is primarily used for monitoring right now, so the biggest consequence will be less accurate cluster monitoring. CPU and Memory usage are used for HPA (horizontal pod autoscaling), so you could run into problems if you use that feature. These will also likely become more important in supporting future features.

**Comment by ncdc** [comment] 2016-03-14 19:57
https://github.com/google/cadvisor/pull/1158 should help somewhat with the high cpu issue

**Comment by nwwells** [comment] 2016-08-31 13:38
Hi! Can we get a status check on this? I've just run into this issue, and I'm curious what our options are, and if there's anything we can do to help. FWIW, I've only been bothered by this issue in our development environment, which runs kubernetes on a VirtualBox (via docker-machine). It eats up battery pretty aggressively and keeps the fan spinning.

So, what can I do to help? And failing that, what can I do to work around this issue?

**Comment by timstclair** [comment] 2016-08-31 16:35
The current proposal is to move the bulk of cAdvisor's monitoring responsibilities out of the Kubelet and into a separate Pod. You can follow that discussion here: https://github.com/kubernetes/kubernetes/issues/27097

In the short term, if your primary concern is CPU usage in your development environment, you can set the data collection interval to an arbitrarily large value via some Kubelet flags:

```
--global-housekeeping-interval value             Interval between global housekeepings (default 1m0s)
--housekeeping-interval value                    Interval between container housekeepings (default 10s)
```

Note that those flags are likely to be removed at some point in the future.

**Comment by nwwells** [comment] 2016-09-01 02:06
Thanks!

**Closed** 2018-02-15 13:36 UTC
Labels: area/test, lifecycle/rotten, sig/node, sig/scalability
