### ISSUE TITLE
Kubernetes should support cross-zone cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#4235] opened 2015-02-07 05:41 UTC
Most applications should be running in multiple zones to increase availability. Kubernetes should support it. I imagine this to work in the following way:

1. User sets up cluster in a region in a way that minions are spread evenly across all available zones
2. User creates replication controller for the application with size > 1
3. Scheduler spreads pods within the same replication controller across available zones

That way user gets regional availability for free.

AFAIU this will mostly require changes in how we create cluster and how we schedule pods.

cc @wojtek-t

**Comment by davidopp** [comment] 2015-02-07 06:37
It might be better to build something on top of Kubernetes that that aggregates clusters and provides a unified interface (a smart proxy of sorts), rather than try to make a single Kubernetes cluster span zones. (I'm assuming "zones" are separate failure domains with inter-zone network latency higher than intra-zone.) Keeping clusters autonomous, with all their management components (master components) in the same failure domain and connected by a low-latency network, seems desirable. This is also useful from a software factoring standpoint (we can keep the core Kubernetes code simpler). I think the Kubernetes API is fairly composable, so building something on top could be feasible.

**Comment by bgrant0607** [comment] 2015-02-07 08:17
Aka "multiple resource pools". Some people are also interested in hybrid cloud (on prem and cloud).

Spreading pods across zones is the wrong model in many cases. Multiple tiers/micro-services comprising a service, including backend data, need to be co-deployed and multi-homed, with regional load balancing -- see also #3683 and https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/availability.md.

Anyway, this would need to be exposed as explicit automatic placement. Hiding the placement location is undesirable. `Location` headers on the responses to object creations could indicate the paths of the created resources.

Spreading across multiple clusters within a zone would be reasonable -- there are multiple reasons why one would want to do this. The loose coupling of controllers with the core, especially once we convert ReplicationController to a plugin, would facilitate this.

**Comment by erictune** [comment] 2015-02-07 10:30
See and possibly expand docs/availability.md

**Comment by benmccann** [comment] 2015-09-05 01:34
I'm more familiar with AWS which has availability zones (AZ) and regions. AZs are separate failure domains and there are multiple AZs in a region. You can setup a VPC (virtual network) across AZs within a region, but not across regions. When we talk about zones here, I'm assuming we're talking about something roughly equivalent to an AZ.

I just did a quick search and the first article I saw said latency between machines in an AZ is roughly 3ms and latency within a region but across AZs is about 9ms. I'm not sure what the latency requirement is between machines in a k8s cluster, but having a k8s cluster span AZs within a region doesn't seem prohibitive from a latency perspective (though I may be unfamiliar with requirements here).

The other technical consideration that comes to mind is that you may want to spread services across AZs or keep them within an AZ. The scheduler has a concept of spreading now, but only spreads to avoid instances being located on the same machine. So we would probably want to add an additional scheduling concept.

Are there other challenges I haven't considered? Is adding one more concept to the scheduler enough added complexity that we wouldn't want to do this? [Cluster federation (Ubernetes)](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md) will still be needed for traffic across regions, clouds, etc. but if you want to simply setup a k8s cluster spanning regions in an AZ then it seems like a lot of operational overhead.

**Comment by davidopp** [comment] 2015-09-08 08:12
@benmccann There's a very related discussion in #13056.

**Comment by eliaslevy** [comment] 2015-09-27 01:01
Allow me to second this requirement. Availability zones within AWS are often used as the equivalent of racks within a DC for purposes of availability.  The inter-AZ latencies are low enough for many applications. A federated model, while valuable for cross region clusters, would likely be too complex tightly coupled cross-AZ applications.  E.g. service discovery is likely to be more complicated and potentially leak to the Internet through externally visible DNS names and Internet routable IP addresses, potentially incurring unneeded expense by routing traffic externally.

A cross-AZ cluster needs to be capable of scheduling pods across AZs, but must also be able to optionally preferentially route service connections to within the AZ and only fallback to services across the AZ, so as to lower average latencies and avoid across-AZ networking costs, while allowing for failover.

For what is worth, a cluster in AWS EC2 Container Service can span across AZs.  Alas, their current schedulers are simplistic.  They will simply spread the tasks across the cluster.  That means containers will be spread across AZs if the cluster spans AZs, but you don't have any control over it.  You can write your own scheduler to handle this, and some have done so, but its something that should be backed into the product.  I expect Amazon to make their schedulers AZ aware at some point.

**Comment by quinton-hoole** [comment] 2016-03-01 19:42
I think that we can close this as a duplicate of the various Kubernetes Lite and Kubernetes Proper issues, PR's and the working group (http://tinyurl.com/ubernetes-wg-notes). See also #17059, #19313.

**Closed by quinton-hoole** 2016-03-01 19:42 UTC
Labels: area/api, area/cluster-federation, area/HA, area/usability, kind/design, priority/P2, team/control-plane
