### ISSUE TITLE
Publishing newer kubectl container images

### ISSUE THREAD

**Issue by adleong** [kubernetes/kubernetes#25900] opened 2016-05-19 19:37 UTC
kubectl container images should be published with each release.

**Comment by lavalamp** [comment] 2016-05-19 19:49
We should cut them with a sensible location & tag, e.g. gcr.io/kubernetes/kubectl:1.2.3

**Comment by dims** [comment] 2016-07-20 19:16
Looks like we have something to start with here:
https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container

**Comment by bgrant0607** [comment] 2017-08-31 23:40
Dupe of #16437

**Closed by bgrant0607** 2017-08-31 23:40 UTC
Labels: area/build-release, area/kubectl, area/release-infra, priority/important-soon, sig/release, team/ux (deprecated - do not use)
