### ISSUE TITLE
Proposal to rework examples.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#21817] opened 2016-02-24 00:28 UTC
Today in @kubernetes/sig-testing we discussed the idea of improving the examples over time with a new policy, based on.
- a few, domain driven examples that are artfully curated by developers, i.e., less than 4.
- covering all features in the examples : rather than duplicating the core features using non idiomatic kube techniques.
- converting the existing examples which don't actually "tell a story" into a `blueprints/` directory which might be put into contrib.  
  - That way, if the mongodb community wants to curate their recipes upstream, they can easily do so, without us having to support then in the e2es.

I think this should be done slowly.  For now, I think its great for us to keep maintaining the examples/, as many people continue to use them.  We can work with the @kubernetes/sig-big-data @kubernetes/sig-api-machinery  and @kubernetes/sig-auth and other sigs to make sure the pedagogical elements are all addressed.

**Comment by jayunit100** [comment] 2016-02-24 00:29
cc/ @bparees .  Shall we assign this issue directly to you ?  I'd like to collaborate on it as well.

**Comment by bparees** [comment] 2016-02-24 03:54
How many tests/blogs/docs/etc are going to be broken if we start moving this stuff around?  Does that need to be a consideration?  (tests obviously do, blogs/docs less so)

**Comment by jayunit100** [comment] 2016-02-24 04:00
Don't even have community consensus just an idea.  
I think many blogs (ha, probably including my own) will be broken but I don't think that should be a huge concern.  The technical debt is a bigger issue...

**Comment by ixdy** [comment] 2016-02-27 01:26
External sites probably shouldn't be linking into documentation in master, since it's likely to break, but we can leave breadcrumbs if we remove examples.

Ideally the documented examples and the examples e2e tests should be one and the same. The whole idea behind creating the examples e2e tests in the first place was to verify that the documented examples actually worked - xref #10013.

**Comment by ixdy** [comment] 2016-02-27 01:28
See also #5465, which is basically saying much of the same.

**Comment by timothysc** [comment] 2016-02-29 15:57
FWIW - I think examples should be moved out of kubernetes core repository, and is more suited to live in contrib/helm/etc.  As of today, most are not "examples", they're apps, which should live outside the core.

**Comment by erictune** [comment] 2016-02-29 17:46
Agree with Timothy.
The contrib repository should have its own e2e that makes sure the examples
work against a kubernetes cluster tht is kube-up-ed from the latest stable
release of kubernetes.



On Mon, Feb 29, 2016 at 7:58 AM, Timothy St. Clair <notifications@github.com

**Comment by erictune** [comment] 2016-02-29 17:52
This statement:
"The whole idea behind creating the examples e2e tests in the first place
was to verify that the documented examples actually worked"

I take to mean that the examples e2e test are testing two things at once:
detecting incorrect examples, and detecting regressions of kubernetes code
against examples that used to work.

While it was initially a clever trick to test both things at once, I think
the project is mature enough that these two concerns should be separated.

Kubernetes regressions should be covered primarily by Go-based e2e test
that are owned by the core project, and divided up into files that map to
subteams and feature owners, and are optimized for highly reliable, fast,
and debuggable e2e testing, and are run against every change to the core
code.

Examples testing should focus on detecting invalid changes to examples, or
use of deprecated features, and would run infrequently and would use shell
scripting to execute kubectl commands, to be as close as possible to the
example text.\

**Comment by jayunit100** [comment] 2016-02-29 17:55
Yea, we all agree the examples need to move on to a new place :)

**Comment by bgrant0607** [comment] 2016-05-06 16:32
cc @kubernetes/examples

**Comment by bgrant0607** [comment] 2016-05-06 16:34
See also:
https://github.com/kubernetes/kubernetes/blob/master/examples/README.md
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md

Doc overhaul:
https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12d21f53ed_2_11
https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#heading=h.qfbb9hrqc5xt

**Comment by bgrant0607** [comment] 2016-05-06 16:35
As far as repos go, we also have:
https://github.com/kubernetes/demos-and-tutorials
https://github.com/kubernetes/charts

**Comment by chrislovecnm** [comment] 2016-05-06 17:34
@bgrant0607 we also have https://github.com/kubernetes/contrib ... how do this apply?

**Comment by bgrant0607** [comment] 2016-05-06 18:03
@chrislovecnm I want to nuke contrib: https://github.com/kubernetes/contrib/issues/762

**Comment by chrislovecnm** [comment] 2016-05-06 18:45
@bgrant0607 got yah, but would like to understand more.  I see duplicate work going on there, so I am just confused.

**Comment by chrislovecnm** [comment] 2016-06-01 19:25
Wanted to also mention https://github.com/kubernetes/kubernetes/issues/25889 

A few of challenges that we have:

1. Process for testing and building containers that are used in the examples.
2. Actually testing the technology - parsing log statements does not validate an example.  For instance running a couple `nodetool` and `cqlsh` commands validates Cassandra(C*).  The examples should be smoke tested and exercised.  This is on my plate for C* after 1.3, and the demo I am working on.
3. Possibly automate the releasing of containers.
4. Building containers off of base images that we control.  Ubuntu, Debian, Alpine containers that we vet.  Big security challenge if the base images are not hosted on gcr.io.

**Comment by chrislovecnm** [comment] 2016-07-16 19:03
@bgrant0607 does this work into 1.4 timeline?  At least for improvement of e2e tests?

**Comment by bgrant0607** [comment] 2016-07-18 16:32
cc @erictune @viglesiasce @jeffmendoza @pwittrock

**Comment by jeffmendoza** [comment] 2016-07-19 16:51
I think examples which are educational should be moved to kubernetes/kubernetes.github.io and surfaced as a section of the docs on the website.

Examples that are "blueprints" should be moved to a separate existing or new repo.

Example .yaml files that are used in existing kubernetes tests should be saved in this repo and moved to a test artifacts directory.

**Comment by chrislovecnm** [comment] 2016-07-19 17:55
we have kubernetes/charts in the works as well...  Who can may a preliminary call??

**Comment by erictune** [comment] 2016-07-29 15:32
Agree with what @jeffmendoza said.

There will be no `blueprints/` directory.  Things that don't "tell a story" will go into a charts repository.  We are still sorting out exactly which repository and what the review requirements will be for that repository.  The bar for that repository may be higher, so some things that are currently examples may not make the cut.

**Comment by kargakis** [comment] 2017-05-20 20:27
Superseded by https://docs.google.com/document/d/15eRNrOtofhl1tFyXgZYw3pV4Z9S4PF1TU1iejGnv1f4/edit

More discussion in https://groups.google.com/forum/#!topic/kubernetes-sig-apps/a6VcS3uzeHE

PR that moves the examples in their new home: https://github.com/kubernetes/examples/pull/2

**Closed by kargakis** 2017-05-20 20:27 UTC
Labels: area/example, priority/backlog, sig/apps
