### ISSUE TITLE
Kubelet resource usage tracking flaked after node upgrades from v1.1 to v1.2

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#22370] opened 2016-03-02 17:53 UTC
**Kubelet [Serial] [Slow] regular resource usage tracking for 35 pods per node over 20m0s**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:241 Mar 2 01:13:42.318: CPU usage exceeding limits: node gke-upgrade-gke-1-1-master-29bb566f-node-im5r: container "/kubelet": expected RSS memory (MB) < 78643200; got 79212544*

**Kubelet [Serial] [Slow] regular resource usage tracking for 0 pods per node over 20m0s**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:241 Mar 2 02:39:50.274: CPU usage exceeding limits: node gke-upgrade-gke-1-1-master-29bb566f-node-im5r: container "/kubelet": expected RSS memory (MB) < 73400320; got 88104960*

See http://ci-test.k8s.io/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/461

**Comment by ihmccreery** [comment] 2016-03-02 17:54
@dchen1107 for triage, then we can prioritize.

**Comment by dchen1107** [comment] 2016-03-02 18:16
@yujuhong I am about re-assign this to you since you are checking other resource usage tracking flakiness too. I think this is one of upgrade failures with lowest priority. I marked this as P1 for now to make sure there is no obvious failure in new kubelet source.

**Comment by yujuhong** [comment] 2016-03-02 18:37
> @yujuhong I am about re-assign this to you since you are checking other resource usage tracking flakiness too

I already reassigned it to myself :-)

The kubelet on "gke-upgrade-gke-1-1-master-3e56fd74-node-rnnh" used a lot of memory (140 MB) **even before the test begins**.
```
15:53:58 container        cpu(cores) memory_working_set(MB) memory_rss(MB)
15:53:58 "/"              0.869      1612.91                24.95
15:53:58 "/docker-daemon" 0.510      366.14                 45.29
15:53:58 "/kubelet"       0.263      48.48                  43.84
15:53:58 "/system"        0.120      165.04                 71.05
15:53:58 
15:53:58 Resource usage on node "gke-upgrade-gke-1-1-master-3e56fd74-node-rnnh":
15:53:58 container        cpu(cores) memory_working_set(MB) memory_rss(MB)
15:53:58 "/docker-daemon" 0.096      585.71                 52.74
15:53:58 "/kubelet"       0.213      147.54                 140.28
15:53:58 "/system"        0.011      110.19                 52.68
15:53:58 "/"              0.279      1828.19                24.88
15:53:58 
15:53:58 Resource usage on node "gke-upgrade-gke-1-1-master-3e56fd74-node-rvml":
15:53:58 container        cpu(cores) memory_working_set(MB) memory_rss(MB)
15:53:58 "/"              0.298      1469.35                24.99
15:53:58 "/docker-daemon" 0.059      309.51                 50.14
15:53:58 "/kubelet"       0.181      63.42                  58.22
15:53:58 "/system"        0.129      149.04                 57.18
```

There kubelet.log is incomplete and does not cover the time span where this test was run. I'll add more debugging information in the test.

**Comment by yujuhong** [comment] 2016-03-09 22:04
https://github.com/kubernetes/kubernetes/issues/19014#issuecomment-194510029 could be the root cause.

**Comment by yujuhong** [comment] 2016-03-14 18:25
> #19014 (comment) could be the root cause.

Closing the issue since the goroutine/memory leak in spdy connection has been fixed. Will reopen if the test fails again.

**Closed by yujuhong** 2016-03-14 18:25 UTC
Labels: area/test, area/upgrade, priority/P1, team/node
