### ISSUE TITLE
[v1.1.0-alpha.1] Service port is not released by kube-proxy after deleting an externalIP service

### ISSUE THREAD

**Issue by xfye** [kubernetes/kubernetes#15527] opened 2015-10-13 06:09 UTC
Reproduce steps:
1. Install a V1.1.0-alpha.1 cluster
2. Create a service with the following json file
{
   "kind":"Service",
   "apiVersion":"v1",
   "metadata":{
      "name":"sshd",
      "labels":{
         "name":"sshd"
      }   
   },  
   "spec":{
      "ports": [
        {   
            "port": 48000,
            "targetPort": 22, 
            "protocol": "TCP"
        }   
      ],  
      "selector":{
         "name":"sshd"
      },  
      "externalIPs": [
          "172.30.80.20"
      ]   
   }   
}

3. After the service is created, kube-proxy on node 172.30.80.20 listens on port 48000
# netstat -anp | grep 48000
tcp        0      0 172.30.80.20:48000      0.0.0.0:*               LISTEN      54819/kube-proxy

4. Delete the service by kubectl.
5. After the service is deleted, the port 48000 on  node 172.30.80.20 is still there.
# netstat -anp | grep 48000
tcp        0      0 172.30.80.20:48000      0.0.0.0:*               LISTEN      54819/kube-proxy

**Comment by jijun2** [comment] 2015-10-13 12:28
@mwielgus , @thockin  , Can you assigne me do some simple things of proxy/service ? I want to join k8s development. Thanks.

**Comment by thockin** [comment] 2015-10-20 05:18
Confirmed with the userpsace proxy.

@ArtfulCoder

**Comment by thockin** [comment] 2015-10-20 05:20
does NOT seem to be a problem in the iptables proxier.

**Comment by thockin** [comment] 2015-10-20 05:21
jijun2 this would be a great bug to tackle :)

**Comment by jijun2** [comment] 2015-10-20 06:33
@thockin , @xfye, OK! I will take a try.

**Comment by thockin** [comment] 2015-10-21 17:39
jijun2 are you actively working on this?

**Comment by jijun2** [comment] 2015-10-22 01:11
@thockin ,My main task change to  linux kernel now, but I want fix this in night and this weekend if it is simple, How about ?  Is it urgent ?

**Comment by ArtfulCoder** [comment] 2015-10-22 02:36
i think you will be able to find the bug quickly and mostly likely it will be a simple fix.
Maybe you could take a quick look ?

**Comment by jijun2** [comment] 2015-10-22 03:14
@ArtfulCoder , @thockin  , OK.

**Comment by thockin** [comment] 2015-10-22 06:16
It is a little bit urgent - we're trying to close down changes for our 1.1
release, and this is flagged P0.  I can demote it if we need to, but that
means we're shipping 1.1.0 with this as a known defect.  Not the end of the
world, but not what I want to do.

If you can't pin this down in a few hours, let us know and we can take it
over.

**Comment by jijun2** [comment] 2015-10-22 06:19
@thockin, Thank you for your help,  please take it over.

**Comment by jijun2** [comment] 2015-10-22 12:34
@thockin, I've done my best. Maybe because these isn't a endpoint to use, I only start up a service. 
// We tolerate this, it happens if we are cleaning up a failed allocation

Oct 22 20:16:19 centos-2.localdomain kube-proxy[26855]: I1022 20:16:19.584304   26855 proxier.go:587] Ignoring release on unowned port: {<nil> 48000 TCP}

// Release a claim on a port.  Returns an error if the owner does not match the claim.
// Tolerates release on an unclaimed port, to simplify .
func (proxier *Proxier) releaseNodePort(ip net.IP, port int, protocol api.Protocol, owner proxy.ServicePortName) error {
	proxier.portMapMutex.Lock()
	defer proxier.portMapMutex.Unlock()

	key := portMapKey{ip: ip.String(), port: port, protocol: protocol}
	existing, found := proxier.portMap[key]
	if !found {
		// We tolerate this, it happens if we are cleaning up a failed allocation
		glog.Infof("Ignoring release on unowned port: %v", key)
		return nil
	}
	if existing.owner != owner {
		return fmt.Errorf("Port conflict detected on port %v (unowned unlock).  %v vs %v", key, owner, existing)
	}
	delete(proxier.portMap, key)
	existing.socket.Close()
	return nil
}

**Comment by ArtfulCoder** [comment] 2015-10-22 23:13
I1022 23:11:48.670612   18689 proxier.go:567] Claimed local port 10.240.0.5:443/TCP


I1022 23:12:19.492592   18689 proxier.go:587] Ignoring release on unowned port: {<nil> 443 TCP}

**Comment by jijun2** [comment] 2015-10-23 05:01
Can you give me more details and idea about this bug ? I need to read source code and understand it. If this isn't fixed, I will debug tomorrow!

**Comment by thockin** [comment] 2015-10-23 05:14
I think Abhi found it.

**Comment by jijun2** [comment] 2015-10-23 06:19
OK!

**Comment by thockin** [comment] 2015-10-23 06:25
Thanks though! :)  You can get the next one.

**Comment by ArtfulCoder** [comment] 2015-10-23 15:12
fixed by https://github.com/kubernetes/kubernetes/pull/16137

**Closed** 2015-10-26 16:32 UTC
Labels: area/networking, component/kube-proxy, priority/P0, team/cluster
