### ISSUE TITLE
Update to Go 1.8; eval 1.8beta1

### ISSUE THREAD

**Issue by bradfitz** [kubernetes/kubernetes#38228] opened 2016-12-06 23:46 UTC
Hi, I coordinate Go releases.

Go 1.8beta1 is out now.

This is a request for Kubernetes to test it now, sooner than later. The later you test, the harder and/or less likely we're able to fix bugs.

* Go 1.8 announcement email: https://groups.google.com/d/msg/golang-announce/Wgv6NGcntlQ/JtOV10rwBgAJ
* Go 1.8 release notes: https://beta.golang.org/doc/go1.8

We expect Go 1.8beta2 to be out next week, and the release candidate to be out Jan 1st (per https://github.com/golang/go/wiki/Go-Release-Cycle).

Could somebody run the Kubernetes tests with Go 1.8beta1 in the next week or two? At minimum, just the tests. Performance tests would be a bonus.

Thanks!

/cc @jessfraz who did #35716 recently.

**Comment by jessfraz** [comment] 2016-12-06 23:47
I'll test it out

**Comment by timothysc** [comment] 2016-12-07 23:22
Re-jig'd so we have a single issue vs. several.  

@bradfitz what is the ETA on 1.8 (Jan 31st)?

**Comment by bradfitz** [comment] 2016-12-07 23:45
~Next week is beta2.
~Jan 1st is the first (and hopefully only) release candidate.
~Feb 1st final

Details in https://github.com/golang/go/wiki/Go-Release-Cycle

Bug reports in the next week or two would be ideal. Maybe three.

The later we hear about problems, the harder it is to fix.

**Comment by jessfraz** [comment] 2016-12-08 00:23
@bradfitz ok I've looked into some of the errors and [attached the entire logs](https://gist.github.com/anonymous/075016cec95fe2bf3a67da5b0b4ecd6d):

1. **`os.Rename` is returning `file exists` when it says in the doc `// Rename renames (moves) oldpath to newpath. If newpath already exists, Rename replaces it.`. I tried to see anything that changed to the `os.Rename` function and could not find anything.**

	some (not all) k8s failures:
	```
--- FAIL: TestPlugin (0.01s)
	secret_test.go:455: Expected success, got: rename /tmp/secret_volume_test.027716999/pods/test_pod_uid/volumes/kubernetes.io~secret/test_volume_name /tmp/secret_volume_test.027716999/pods/test_pod_uid/volumes/kubernetes.io~secret/wrapped_test_volume_name.deleting~428139345: file exists
	secret_test.go:458: TearDown() failed, volume path still exists: /tmp/secret_volume_test.027716999/pods/test_pod_uid/volumes/kubernetes.io~secret/test_volume_name
--- FAIL: TestPluginReboot (0.00s)
	secret_test.go:455: Expected success, got: rename /tmp/secret_volume_test.913584252/pods/test_pod_uid3/volumes/kubernetes.io~secret/test_volume_name /tmp/secret_volume_test.913584252/pods/test_pod_uid3/volumes/kubernetes.io~secret/wrapped_test_volume_name.deleting~236941070: file exists
	secret_test.go:458: TearDown() failed, volume path still exists: /tmp/secret_volume_test.913584252/pods/test_pod_uid3/volumes/kubernetes.io~secret/test_volume_name
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/secret	0.339s
```

	Being called from [pkg/volume.RenameDirectory in pkg/volume/volume.go#L235:6](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/volume/volume.go#L235:6)

2. **int overflows in json**

	k8s test errors:
	```
--- FAIL: TestEvaluateTypes (0.00s)
	json_test.go:313: 9223372036854775808: expected
			{"data":9.223372036854776e+18}, got
			{"data":9223372036854776000}
	json_test.go:313: -9223372036854775809: expected
			{"data":-9.223372036854776e+18}, got
			{"data":-9223372036854776000}
FAIL
FAIL	k8s.io/kubernetes/pkg/util/json	0.024s
```

	It's for these test cases in [pkg/util/json/json_test.go#L101](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/util/json/json_test.go#L101) that fail when getting marshal-ed and unmarshal-ed in [pkg/util/json/json_test.go#L279](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/util/json/json_test.go#L279)

3. **`x509.AppendCertsFromPEM` fails with `error setting up localhostCert pool`**

	k8s errors:
	```
--- FAIL: TestDialURL (0.00s)
	dial_test.go:37: error setting up localhostCert pool
FAIL
FAIL	k8s.io/kubernetes/pkg/util/proxy	0.062s
```

	The code where this is called is in [pkg/util/proxy/dial_test.go#L36](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/util/proxy/dial_test.go#L36)
	
4. **`strconv`** [haven't looked more deeply into yet but can later]

	k8s error:
	```
--- FAIL: TestGetEnvAsIntOrFallback (0.00s)
	assertions.go:197: 
                        
	Error Trace:	env_test.go:58
		
	Error:		Not equal: "strconv.ParseInt: parsing \"not-an-int\": invalid syntax" (expected)
			        != "strconv.Atoi: parsing \"not-an-int\": invalid syntax" (actual)
		
	Messages:	An error with value "strconv.ParseInt: parsing "not-an-int": invalid syntax" is expected but got "strconv.Atoi: parsing "not-an-int": invalid syntax". 
		
FAIL
FAIL	k8s.io/kubernetes/pkg/util/env	0.031s
```

5. **`x509`** [haven't looked more deeply into yet but can later]

	k8s error:
	```
panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init.1()
	/usr/local/google/home/jessfraz/.go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/certs.go:10 +0x1e3
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init()
	/usr/local/google/home/jessfraz/.go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/signer.go:88 +0x2eb
k8s.io/kubernetes/pkg/util/httpstream/spdy.init()
	/usr/local/google/home/jessfraz/.go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/upgrade_test.go:94 +0xac
main.init()
	k8s.io/kubernetes/pkg/util/httpstream/spdy/_test/_testmain.go:48 +0x3f
FAIL	k8s.io/kubernetes/pkg/util/httpstream/spdy	0.143s
```
	
6. **[ON US] tls cert config, we need to add the new fields just putting this here as a reminder**

	k8s error:
	```
--- FAIL: TestCloneTLSConfig (0.00s)
	http_test.go:74: New fields seen in http.Transport: [GetClientCertificate GetConfigForClient KeyLogWriter VerifyPeerCertificate originalConfig]
		Add to CopyClientTLSConfig if client-relevant, then add to expected list in TestCopyClientTLSConfig
FAIL
FAIL	k8s.io/kubernetes/pkg/util/net	0.033s
```

	To be added in [pkg/util/net/http.go#L120](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/util/net/http.go#L120)

7. **crazy etcd test panics** https://gist.github.com/anonymous/075016cec95fe2bf3a67da5b0b4ecd6d#file-results-txt-L7866



[results.txt](https://github.com/kubernetes/kubernetes/files/638054/results.txt)

**Comment by jessfraz** [comment] 2016-12-08 00:28
I'm going to try and reproduce in the playground / locally.

**Comment by bradfitz** [comment] 2016-12-08 00:49
(1) is expected. See https://beta.golang.org/doc/go1.8#os and the mention of Rename. This was done to make Rename act the same on Unix as Windows. See golang/go#14527. We should probably add more docs to http://beta.golang.org/pkg/os/#Rename ... Filed https://github.com/golang/go/issues/18240 for that.

(2) is also expected. See https://beta.golang.org/doc/go1.8#encoding_json

(3) is because the cert isn't valid. https://golang.org/pkg/crypto/x509/#CertPool.AppendCertsFromPEM is a kinda crap API in that it can't return an error. 

(4) is a fragile test, string matching an error. For background, @dsnet changed that in golang/go#16980 

(5) Let us know what you find. It's probably the same as (3).

(6) Switch to the new *tls.Config.Clone instead, probably.

(7) Test timeouts? Let me know what you find.

**Comment by jessfraz** [comment] 2016-12-08 00:53
wow thanks! that was fast, you must have a bunch of that just stored in your brain

**Comment by dsnet** [comment] 2016-12-08 00:57
You see enough of the same failures over and over and you learn to identify the probable cause fairly quickly.

I agree with @bradfitz's assessment of the probable failures.

**Comment by dsnet** [comment] 2016-12-08 01:00
Check if there are custom `net.Conn` implementations being used in code related to (7). In the cases where a test timed out, a fair number of them was because the test relied upon a buggy `net.Conn` implementation.

See https://godoc.org/golang.org/x/net/nettest for a tool to test for compliance.

**Comment by bradfitz** [comment] 2016-12-08 01:18
For background on what @dsnet mentioned, see https://beta.golang.org/doc/go1.8#net

**Comment by dims** [comment] 2016-12-09 22:33
@jessfraz Anyway i can help? look like interesting set of issues

**Comment by mkumatag** [comment] 2016-12-10 05:42
@Pensu mention if have faced any other issues on ppc64le with go1.8?

**Comment by jessfraz** [comment] 2016-12-12 18:44
Yeah for sure I'm working off a branch on my fork called go-1.8 I think
I've knocked most out except the net.Conn changes

**Comment by Pensu** [comment] 2016-12-15 06:37
@jessfraz @bradfitz Hi, I have been building kuberentes on ppc64le with go1.8beta1. I am able to build it properly, was hitting an issue with apiserver #38380, that has been resolved now. When I am running unit tests, I am getting the test timing out error:

```
2016-12-15 00:32:01.269823 I | integration: launching node3652351429000202590 (unix://localhost:node3652351429000202590.sock.bridge)
2016-12-15 00:32:01.272634 I | etcdserver: name = node3652351429000202590
2016-12-15 00:32:01.272647 I | etcdserver: data dir = /tmp/etcd853931578
2016-12-15 00:32:01.272655 I | etcdserver: member dir = /tmp/etcd853931578/member
2016-12-15 00:32:01.272663 I | etcdserver: heartbeat = 10ms
2016-12-15 00:32:01.272672 I | etcdserver: election = 100ms
2016-12-15 00:32:01.272682 I | etcdserver: snapshot count = 0
2016-12-15 00:32:01.272697 I | etcdserver: advertise client URLs = unix://127.0.0.1:21002.24144.sock
2016-12-15 00:32:01.272708 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21001.24144.sock
2016-12-15 00:32:01.272724 I | etcdserver: initial cluster = node3652351429000202590=unix://127.0.0.1:21001.24144.sock
2016-12-15 00:32:01.275365 I | etcdserver: starting member 5567ee554e97bf2c in cluster e4b133aca7814ecb
2016-12-15 00:32:01.275413 I | raft: 5567ee554e97bf2c became follower at term 0
2016-12-15 00:32:01.275430 I | raft: newRaft 5567ee554e97bf2c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-12-15 00:32:01.275438 I | raft: 5567ee554e97bf2c became follower at term 1
2016-12-15 00:32:01.287988 I | etcdserver: set snapshot count to default 10000
2016-12-15 00:32:01.288010 I | etcdserver: starting server... [version: 3.0.14, cluster version: to_be_decided]
2016-12-15 00:32:01.288239 I | raft: 5567ee554e97bf2c is starting a new election at term 1
2016-12-15 00:32:01.288304 I | raft: 5567ee554e97bf2c became candidate at term 2
2016-12-15 00:32:01.288315 I | raft: 5567ee554e97bf2c received vote from 5567ee554e97bf2c at term 2
2016-12-15 00:32:01.288334 I | raft: 5567ee554e97bf2c became leader at term 2
2016-12-15 00:32:01.288355 I | integration: launched node3652351429000202590 (unix://localhost:node3652351429000202590.sock.bridge)
2016-12-15 00:32:01.288369 I | raft: raft.node: 5567ee554e97bf2c elected leader 5567ee554e97bf2c at term 2
2016-12-15 00:32:01.288772 I | membership: added member 5567ee554e97bf2c [unix://127.0.0.1:21001.24144.sock] to cluster e4b133aca7814ecb
2016-12-15 00:32:01.288882 I | etcdserver: published {Name:node3652351429000202590 ClientURLs:[unix://127.0.0.1:21002.24144.sock]} to cluster e4b133aca7814ecb
2016-12-15 00:32:01.288958 I | etcdserver: setting up the initial cluster version to 3.0
2016-12-15 00:32:01.289543 N | membership: set the initial cluster version to 3.0
2016-12-15 00:32:01.289599 I | api: enabled capabilities for version 3.0
panic: test timed out after 2m0s
```
 for most of the etcd related tests, as you mentioned. Let me know if I can help in any way resolving these.

**Comment by luxas** [comment] 2016-12-17 18:24
In #38926 I found this in `kube-apiserver`:
```
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x3360b0, 0x56e56a80)
	/usr/local/go/src/runtime/panic.go:481 +0x330
github.com/urfave/cli.HandleAction.func1(0x56e03960)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x328
panic(0x3360b0, 0x56e56a80)
	/usr/local/go/src/runtime/panic.go:443 +0x448
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x56e035e8, 0x56dda890, 0x56e03670)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x13c
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x56e08e70, 0x46433cb0, 0x56e56a80)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x498
main.glob.func8(0x56e42320, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x58
reflect.Value.call(0x2eb600, 0x3f2948, 0x13, 0x3648b8, 0x4, 0x56e03920, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0xeb4
reflect.Value.Call(0x2eb600, 0x3f2948, 0x13, 0x56e03920, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0x84
github.com/urfave/cli.HandleAction(0x2eb600, 0x3f2948, 0x56e42320, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x230
github.com/urfave/cli.Command.Run(0x366cd8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3d0d50, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xcd0
github.com/urfave/cli.(*App).Run(0x56e3a240, 0x56dca070, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x84c
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xbb4
```

Seems like this is that line that's failing: https://github.com/urfave/cli/blob/d53eb991652b1d438abdd34ce4bfa3ef1539108e/app.go#L478
It's not so fun with a bug in a vendored package for our vendored package (we're two levels down now)

I wish I would have found this issue sooner, great stuff here :)

**Comment by bradfitz** [comment] 2016-12-17 19:07
Matching exact strings of error messages, eh?

```go
			s := fmt.Sprintf("%v", r)
			if strings.HasPrefix(s, "reflect: ") && strings.Contains(s, "too many input arguments") {
				err = NewExitError(fmt.Sprintf("ERROR unknown Action error: %v.", r), 2)
			} else {
				panic(r)
			}
```

That's always asking for trouble.

**Comment by luxas** [comment] 2016-12-18 11:23
Seems like we have to bump the version of urfave/cli first in runc and then update the k8s runc godeps, gahh! But at least that match-error-logic seems to be gone at HEAD: https://github.com/urfave/cli/blob/master/app.go#L481

**Comment by dsnet** [comment] 2017-01-14 01:47
The following uses of `http.Hijacker` are invalid. They all ignore the `bufio.ReadWriter` that is returned and proceed to directly read from the connection. Instead, they should handle any buffered data in the `bufio.Reader` (via `brw.Reader.Peek(brw.Reader.Buffered())`) prior to reading from the connection.

A recent CL (https://golang.org/cl/35232) increases the probability that data is buffered in the `bufio.Reader`.

```
github/kubernetes/heapster/vendor/k8s.io/kubernetes/pkg/apiserver/proxy.go:     requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
github/kubernetes/kubernetes/pkg/genericapiserver/api/handlers/proxy.go:        requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
github/kubernetes/kubernetes/pkg/registry/generic/rest/proxy.go:        requestHijackedConn, _, err := requestHijacker.Hijack()
github/kubernetes/kubernetes/pkg/util/httpstream/spdy/upgrade.go:       conn, _, err := hijacker.Hijack()
github/kubernetes/kubernetes/staging/src/k8s.io/client-go/pkg/util/httpstream/spdy/upgrade.go:  conn, _, err := hijacker.Hijack()
github/kubernetes/kubernetes/vendor/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:           conn, _, err := hj.Hijack()
github/kubernetes/kubernetes/vendor/github.com/elazarl/goproxy/https.go:        proxyClient, _, e := hij.Hijack()
```

**Comment by Pensu** [comment] 2017-02-13 07:05
@dsnet Hi, I am trying to look into etcd test panic errors. Do you think it's because of invalid use of http.Hijacker as stated above or should I start looking from somewhere else? @bradfitz @jessfraz

**Comment by jessfraz** [comment] 2017-02-13 18:52
ya I would start there

**Comment by bradfitz** [comment] 2017-02-13 20:23
Please prioritize this if you can. Go 1.8 final is due out this week. It's been over two months with this bug open. We had hoped to hear the Kubernetes was passing with Go 1.8 already (and perhaps learn of bugs you might discover), but we can't hold up the release for it.

I might recommend a new CI builder testing against Go tip in the future, to catch regressions earlier.

**Comment by luxas** [comment] 2017-02-14 14:32
@jessfraz Talked to you some weeks ago, are you gonna bump to go1.8 when it's ready like we thought?
Seems like we have to sort out the Hijacker issue, but apart from that I think it should be pretty straightforward
cc @ixdy @wojtek-t

**Comment by jessfraz** [comment] 2017-02-14 18:37
Yes that is the remaining issue and unfortunately I don't have the
bandwidth to look into right now :(

**Comment by abdasgupta** [comment] 2017-02-15 07:26
@Pensu , it seems, the etcd panic error comes due to "." character in socket name is not supported in golang 1.8 transport. We need to update etcd atleast to this commit (https://github.com/coreos/etcd/pull/7106/commits/6825ffe1a4b69167a4a1fcbdac6612e71aff76ac) to remove the panic while using go1.8.

I will shortly post a patch to update the vendored etcd to this commit in kubernetes.  

Open to any alternative suggestions.

**Comment by bprashanth** [comment] 2017-02-16 02:41
Hmm, I might go off on a bit of a tangent to get some clarification about (5) from https://github.com/kubernetes/kubernetes/issues/38228#issuecomment-265616447, which is hitting this cert: https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/elazarl/goproxy/certs.go#L24. 

Looking at the raw ASN.1
```
$ openssl x509 -in invalid.crt -outform der | openssl asn1parse -inform der -i
  213:d=2  hl=3 l= 157 cons:   SEQUENCE          
  216:d=3  hl=2 l=  11 cons:    SEQUENCE          
  218:d=4  hl=2 l=   9 prim:     OBJECT            :rsaEncryption
  229:d=3  hl=3 l= 141 prim:    BIT STRING      

$ openssl x509 -in valid.crt -outform der | openssl asn1parse -inform der -i
  208:d=2  hl=4 l= 290 cons:   SEQUENCE          
  212:d=3  hl=2 l=  13 cons:    SEQUENCE          
  214:d=4  hl=2 l=   9 prim:     OBJECT            :rsaEncryption
  225:d=4  hl=2 l=   0 prim:     NULL          
```

It looks like the Parameters field is unset, not set to non-NULL. 

The original issue that caused stricter validation had a repro that set it to something invalid:https://github.com/golang/go/issues/16166, which is obviously invalid per RFC. 

Go 1.8 introduced stricter validation by comparing the parameters to ASN.1 NULL (https://github.com/golang/go/commit/59aeac20c0412442848982a9287b4bab66c25682#diff-9b85f40f885de488a06794888f56b047R798). 


But the RFC is confusing as hell. 

The RFC that describes AlgorithmIdentifier, to the best of my googling abilities, appears to be [rfc5280#4.1.1.2](https://tools.ietf.org/html/rfc5280), which says:
```
   AlgorithmIdentifier  ::=  SEQUENCE  {
        algorithm               OBJECT IDENTIFIER,
        parameters              ANY DEFINED BY algorithm OPTIONAL  }
```

And the rfc that describes RSA signatureAlgorithm says 
```
The rsaEncryption OID is intended to be used in the algorithm field
of a value of type AlgorithmIdentifier.  The parameters field MUST
have ASN.1 type NULL for this algorithm identifier.
```
as reported on the bug. 

So is it really wrong to leave the field unset?

**Comment by bprashanth** [comment] 2017-02-16 02:42
Anyway, I'm guessing anyone trying to use later versions of go locally is running into
```
Trying to find master named 'e2e-test-beeps-master'
Looking for address 'e2e-test-beeps-master-ip'
Using master: e2e-test-beeps-master (external IP: 104.154.75.118)
panic: Error parsing builtin CA x509: RSA key missing NULL parameters
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init.1()
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/certs.go:10 +0x1e3
k8s.io/kubernetes/vendor/github.com/elazarl/goproxy.init()
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/signer.go:88 +0x2eb
k8s.io/kubernetes/test/e2e.init()
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:336 +0x1f4
main.init()
	k8s.io/kubernetes/test/e2e/_test/_testmain.go:46 +0x53
```

when they try to run e2es. 

You can regenerate a random valid cert (openssl req -x509 -newkey rsa:2048 -nodes -days 365 -keyout /tmp/temp.key -out /tmp/temp.crt -subj '/CN=localhost') and plug it into the vendored goproxy (https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/elazarl/goproxy/certs.go#L24), instead of reverting to 1.7.

**Comment by abdasgupta** [comment] 2017-02-16 10:38
Sent a PR to update etcd: https://github.com/kubernetes/kubernetes/pull/41546

**Comment by luxas** [comment] 2017-02-17 12:28
sent https://github.com/kubernetes/kubernetes/issues/41636 to upgrade to go1.8, let's see how it goes

**Comment by abdasgupta** [comment] 2017-02-20 19:27
All of the "errors in setting up localhostcertPool" are resolved through this PR https://github.com/kubernetes/kubernetes/pull/41758 while running with go1.8

**Comment by abdasgupta** [comment] 2017-02-24 11:56
A failing test due to a change in JSON marshal in go1.8 for float64 is resolved through this PR https://github.com/kubernetes/kubernetes/pull/42046 . Please find the details in the PR.

**Comment by louyihua** [comment] 2017-03-09 15:15
Hi, @jessfraz
To the problem you mentioned about `os.Rename`, I also met it when compiling openshift with go 1.8.
And after some digging, I finally find what changed in go 1.8 that causes the failure.
The actual changed thing is located in the `rename` function inside `src/os/file_unix.go`. In go 1.7.5, it was written as follows:
```
func rename(oldname, newname string) error {
	e := syscall.Rename(oldname, newname)
	if e != nil {
		return &LinkError{"rename", oldname, newname, e}
	}
	return nil
}
```
However, in go 1.8, it is changed to:
```
func rename(oldname, newname string) error {
	fi, err := Lstat(newname)
	**if err == nil && fi.IsDir() {
		return &LinkError{"rename", oldname, newname, syscall.EEXIST}
	}**
	e := syscall.Rename(oldname, newname)
	if e != nil {
		return &LinkError{"rename", oldname, newname, e}
	}
	return nil
}
```
We can easily notice that the bold lines newly added in go 1.8 **forbid rename a directory into an existing directory**, which is used by the `volume.RenameDirectory` function in kubernetes. So some logic change should be introduced to the `volume.RenameDirectory` function, otherwise very bad things will happen in real world (which we met just a few days ago... we got millions subdirectories inside the volume directory of an orphaned pod after just one night).

**Comment by wojtek-t** [comment] 2017-03-13 09:58
We won't bump Go version in 1.6 release. Moving to 1.7

**Comment by mikedanese** [comment] 2017-03-30 02:07
I'm worried that since we broke TLS unit tests, we are going to break clusters on upgrade to 1.7. Is my fear unfounded? Anyone want to do some analysis?

**Comment by timothysc** [comment] 2017-03-30 16:52
re-poke 1.7 is open.  

Do we have a canonical list of issues here somewhere?

**Comment by mkumatag** [comment] 2017-03-30 17:10
@abdasgupta @Pensu worked on it and know what all hurdles we can get part of 1.8 test. Meanwhile can we get a closure on https://github.com/kubernetes/kubernetes/pull/41427 which is main blocker as of now!

**Comment by elazarl** [comment] 2017-04-05 20:25
(is there a separate issue for the bad certificate of goproxy? I've added a new certificate to goproxy, and I'll be happy to know if there are tools to verify it, unfortunately I do not have a lot of time to work on this issue, so any help would be welcomed)

**Comment by mikkeloscar** [comment] 2017-04-05 22:19
@elazarl and others I have created a PR #44113 to update the goproxy dependency which fixes the crash when running e2e tests as described above.

**Comment by msau42** [comment] 2017-04-14 00:20
I have PR #43878 to fix the emptydir volume os.Rename issue.

**Comment by luxas** [comment] 2017-04-16 15:49
Soo - is there any other issues with go1.8 except for https://github.com/kubernetes/kubernetes/pull/44113 (which is about to merge)?

Otherwise I think we should proceed with https://github.com/kubernetes/kubernetes/pull/41636

**Comment by luxas** [comment] 2017-04-17 08:09
Ran a new round of tests with go1.8 here: https://github.com/kubernetes/kubernetes/pull/41636#issuecomment-294422674

The issue I found was
```
Trying to reach: 'https://10.180.1.129:460/' }],RetryAfterSeconds:0,} Code:503}
4 (0; 147.151362ms): path /api/v1/proxy/namespaces/e2e-tests-proxy-ldvkk/services/https:proxy-service-hv2vc:444/ gave status error: {TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:an error on the server ("Error: 'tls: failed to parse certificate from server: x509: RSA key missing NULL parameters'\nTrying to reach: 'https://10.180.1.129:462/'") has prevented the request from succeeding Reason:InternalError Details:&StatusDetails{Name:,Group:,Kind:,Causes:[{UnexpectedServerResponse Error: 'tls: failed to parse certificate from server: x509: RSA key missing NULL parameters'
Trying to reach: 'https://10.180.1.129:462/' }],RetryAfterSeconds:0,} Code:503}
```

I think that would be a perfect contribution from the community, does @msau42 @mikkeloscar @mkumatag or someone else work on fixing that, please :smile:?

**Comment by timothysc** [comment] 2017-04-17 14:14
Who on the google side is leading this?  I saw the 1.8 gc results, and it was impressive.

**Comment by ixdy** [comment] 2017-04-17 18:11
@timothysc I can push a new cross-build image as needed for #41636, but I'm not really following up on go1.8 issues.

**Comment by mikkeloscar** [comment] 2017-04-17 20:30
I suspect the failing e2e test could be due to the cert used in the image: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/proxy.go#L115

Where are the sources for these images used in the e2e tests?

**Comment by mikedanese** [comment] 2017-04-17 21:03
I don't think this cert issue is one that we can paper over by just updating the certs used in tests. What are the implications for upgrades? Are any malformed certs used in production clusters? This seems like one of those things that you would only find out about after it's too late.

**Comment by luxas** [comment] 2017-04-17 21:07
+1 @mikedanese

@bradfitz can give us some context and probably an upgrade story

**Comment by bradfitz** [comment] 2017-04-17 21:13
That cert error you're seeing is from https://go-review.googlesource.com/c/27312/

**Comment by mikedanese** [comment] 2017-04-17 21:15
@bprashanth gives a good summary of the issue in https://github.com/kubernetes/kubernetes/issues/38228#issuecomment-280213590. In the commit message of https://github.com/golang/go/commit/59aeac2 Adam says golang stopped generating malformed certificates in 2013. Curiously our unit tests started failing, but it seems like it's because we just copied testdata from golang/go that was generated before 2013, ref https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/proxy_test.go#L524-L525. I just want to fully understand the implication, and be sure to have an action-required release note.

**Comment by luxas** [comment] 2017-04-26 17:41
Announcement here: https://groups.google.com/forum/#!topic/kubernetes-dev/0XRRz6UhhTM

**Comment by mikedanese** [comment] 2017-04-26 18:27
Are we sure that all CI images are using 1.8? I'm seeing compile failures for features added in 1.8 still, e.g. https://github.com/kubernetes/kubernetes/pull/44961.

**Comment by ixdy** [comment] 2017-04-26 18:30
yeah, we need a new `kubekins-test` image - https://github.com/kubernetes/test-infra/pull/2521.

**Comment by mikedanese** [comment] 2017-04-28 16:10
Merging that PR gave us a 75% flaky rate on test-go last night. Verify looks fine. I'm going to roll it back.

https://k8s-testgrid.appspot.com/google-unit#test-go

**Comment by mikedanese** [comment] 2017-04-28 16:22
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5198
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5197
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5196
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5195
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5194
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5193
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5192
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5191
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5189
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5188
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5186
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5185
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5184
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5183
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5181
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5180
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5178
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5177
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5176
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5175
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5173
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5172
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5170

**Comment by luxas** [comment] 2017-04-28 17:01
@mikedanese @ixdy Before you rollback, can you see if https://github.com/kubernetes/kubernetes/issues/43922 fixes the problem?

**Comment by mikedanese** [comment] 2017-04-28 17:20
Ok, last two have been green.

**Comment by luxas** [comment] 2017-04-29 14:10
The SPDY problem is resolved now thanks to https://github.com/kubernetes/kubernetes/pull/43922, the test hasn't flaked since the PR was merged.

Closing this as it currently looks like everything's green, we'll reopen once again if things start to fail

**Closed by luxas** 2017-04-29 14:10 UTC
Labels: sig/scalability
