### ISSUE TITLE
Kubernetes, Docker, Calico Compatibility Matrix?

### ISSUE THREAD

**Issue by mmiara** [kubernetes/kubernetes#93351] opened 2020-07-22 19:23 UTC
I have never seen any sort of compatibility matrix for components of open source kubernetes clusters. Does anything like this exist? Components like etcd, networking, storage, coreDNS, and docker/kubernetes themselves would be extremely handy when troubleshooting errors.

**Comment by neolit123** [comment] 2020-07-22 20:50
hello,
there is no compatibility matrix between all the components k8s requires.

but you could still check what are the latest versions k8s supports:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml

this also means that a particular k8s release is e2e tested against those versions.
hope that answers you question.

closing given this is not a bug/feature request.
/close

**Closed** 2020-07-22 20:51 UTC
Labels: needs-sig, triage/support
