### ISSUE TITLE
GCE Upgrade loses api server certs

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#42199] opened 2017-02-27 22:59 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**What happened**:

Upgrade hangs. API server won't start because it doesn't have valid certs.

**What you expected to happen**:

Upgrade succeeds

**How to reproduce it** (as minimally and precisely as possible):

```console
> go run hack/e2e.go --check_version_skew=false --v=t --up --test --test_args="--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci"
```

**Anything else we need to know**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-master/315 is an example. Log from kube-apiserver.log:

```
I0227 22:30:14.951728       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
```

I reproduced this locally and checked the certs:

```console
krousey@e2e-test-krousey-master /etc/srv/kubernetes/pki $ ls -alF             
total 40
drwxr-xr-x 2 root root 4096 Feb 27 21:53 ./
drwxr-xr-x 5 root root 4096 Feb 27 22:05 ../
-rw-r--r-- 1 root root 4451 Feb 27 22:05 apiserver-client.crt
-rw-r--r-- 1 root root 1708 Feb 27 22:05 apiserver-client.key
-rw-r--r-- 1 root root    0 Feb 27 22:05 apiserver.crt
-rw-r--r-- 1 root root    0 Feb 27 22:05 apiserver.key
-rw-r--r-- 1 root root 1233 Feb 27 22:05 ca-certificates.crt
-rw-r--r-- 1 root root 1233 Feb 27 22:05 ca.crt
-rw-r--r-- 1 root root  227 Feb 27 22:05 ca.key
-rw-r--r-- 1 root root 1233 Feb 27 22:05 kubelet.crt
-rw-r--r-- 1 root root 1679 Feb 27 22:05 kubelet.key
-rw-r--r-- 1 root root    0 Feb 27 22:05 serviceaccount.crt
-rw-r--r-- 1 root root    0 Feb 27 22:05 serviceaccount.key
```

apiserver.{crt,key} are empty.

**Comment by krousey** [comment] 2017-02-27 23:00
cc @kubernetes/sig-cluster-lifecycle-bugs @nicksardo

**Comment by skriss** [comment] 2017-03-03 19:07
@krousey @mikedanese Looks like this is still failing?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-master/369/nodelog?junit=junit_runner.xml&wrap=on

**Comment by krousey** [comment] 2017-03-03 19:10
Seems that way.

**Comment by krousey** [comment] 2017-03-06 19:47
cc @ixdy

**Comment by mikedanese** [comment] 2017-03-06 21:16
1.5, to 1.6

**Comment by skriss** [comment] 2017-03-06 23:28
@mikedanese - is this something you are actively looking into? This is blocking all of the GCE upgrade test jobs from running so important to get fixed ASAP. thanks!

**Comment by mikedanese** [comment] 2017-03-07 00:49
As of today I am.

**Comment by skriss** [comment] 2017-03-07 20:11
@mikedanese do you have an update on this? Now that the jobs are set up, this is a blocker for 1.6 upgrade testing. Thanks!

**Comment by mikedanese** [comment] 2017-03-07 20:19
I started looking at this yesterday, figured out what was going wrong. The problem is due to enabling RBAC. There are a couple options to fix. I should have a fix prepared and out for review today or tomorrow.

**Comment by Random-Liu** [comment] 2017-03-09 03:45
With the fix #42675, I hit another problem:
```
Error building core storage: tls: failed to find any PEM data in certificate input
```

Reopen this.

**Comment by mikedanese** [comment] 2017-03-09 17:44
@Random-Liu from release-1.5 to master, I am not able to reproduce.  @krousey verified that this fixed our CI tests.

**Comment by Random-Liu** [comment] 2017-03-09 18:41
@mikedanese Sorry, I forgot that my script is upgrade from 1.5.3 to 1.6.0-beta.1, which doesn't include your fix. Will verify again and close this one if it works. :)

**Comment by Random-Liu** [comment] 2017-03-09 18:44
Wait, it seems that you only changed `upgrade.sh`, then I'm indeed using the latest `upgrade.sh` to upgrade from v1.5.3 to v1.6.0-beta.1. Is there anything missing in v1.6.0-beta.1?

**Comment by krousey** [comment] 2017-03-09 19:09
I think beta.2 rolled up this fix.

**Comment by skriss** [comment] 2017-03-09 21:35
@krousey @mikedanese master-only upgrades seem to be working correctly now, however full-cluster upgrades aren't getting the cluster into a functioning state:

<*errors.errorString | 0xc422c96f10>: {
I0309 08:45:31.969]           s: "failed to get logs from downwardapi-volume-cad0f881-04e7-11e7-986c-0242ac110009 for client-container: the server has asked for the client to provide credentials (get pods downwardapi-volume-cad0f881-04e7-11e7-986c-0242ac110009)",

See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster-new/8?log#log

**Comment by Random-Liu** [comment] 2017-03-09 21:37
OK. It works from v1.5.3 to v1.6.0-beta.2. Close this one. :)

**Comment by mikedanese** [comment] 2017-03-09 21:57
@skriss, looking.... sounds like it might be related :( :(

**Comment by mikedanese** [comment] 2017-03-09 22:30
@liggitt https://github.com/kubernetes/kubernetes/commit/7e98e06e483 broke upgrades since it adds a group to certificates that certificates generated with 1.5 don't have. This is causing:
```
I0309 22:22:31.546055       5 rbac.go:87] RBAC DENY: user "kubecfg" groups [system:authenticated] cannot "get" resource "pods" named "nginx-2371676037-0tm90" in namespace "default"
```

**Comment by liggitt** [comment] 2017-03-09 22:47
upgrades should still have the existing ABAC policy in place

**Comment by mikedanese** [comment] 2017-03-09 22:49
ahh, ok. I'll look into why that's not helping.

**Comment by mikedanese** [comment] 2017-03-09 23:46
Infinity bugs. PTAL at https://github.com/kubernetes/kubernetes/pull/42853

**Comment by ethernetdan** [comment] 2017-03-14 07:42
@mikedanese can this be closed?

**Closed** 2017-03-14 10:12 UTC
Labels: priority/failing-test
