### ISSUE TITLE
[Flaky] CSI mock volume storage capacity exhausted, late binding, with topology

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#90250] opened 2020-04-17 18:40 UTC
**Which jobs are flaking**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=CSI%20mock%20volume%20storage%20capacity%20exhausted%2C%20late%20binding%2C%20with%20topology

**Which test(s) are flaking**:
CSI mock volume storage capacity exhausted, late binding, with topology

**Testgrid link**:

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_mock_volume.go:793
Apr 15 16:54:07.909: while waiting for all CSI calls
Unexpected error:
    <*errors.errorString | 0xc00345a2f0>: {
        s: "error waiting for expected CSI calls: Unexpected CSI call 4: expected NodeUnpublishVolume (0), got NodeStageVolume (0)",
    }
    error waiting for expected CSI calls: Unexpected CSI call 4: expected NodeUnpublishVolume (0), got NodeStageVolume (0)
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_mock_volume.go:870
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by msau42** [comment] 2020-04-17 18:40
@kubernetes/sig-storage-test-failures 
/assign @pohly

**Comment by pohly** [comment] 2020-05-04 17:37
According to https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1252618654105735168/artifacts/_sig-storage_CSI_mock_volume_storage_capacity_exhausted_late_binding_with_topology/csi-mockplugin-0-mock.log, there really are extra calls to `NodeStageVolume` and `NodePublishVolume` that shouldn't be there:
```
gRPCCall: {"Method":"/csi.v1.Controller/CreateVolume","Request":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870","capacity_range":{"required_bytes":1073741824},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"accessibility_requirements":{"requisite":[{"segments":{"io.kubernetes.storage.mock/node":"some-mock-node"}}],"preferred":[{"segments":{"io.kubernetes.storage.mock/node":"some-mock-node"}}]}},"Response":{"volume":{"capacity_bytes":1073741824,"volume_id":"4","volume_context":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870"},"accessible_topology":[{"segments":{"io.kubernetes.storage.mock/node":"some-mock-node"}}]}},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeStageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870","storage.kubernetes.io/csiProvisionerIdentity":"1587483430141-8081-csi-mock-csi-mock-volumes-2142"}},"Response":{},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodePublishVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/globalmount","target_path":"/var/lib/kubelet/pods/30a3a4c3-3cbd-41ac-93c8-2f54d2ffc1b6/volumes/kubernetes.io~csi/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870","storage.kubernetes.io/csiProvisionerIdentity":"1587483430141-8081-csi-mock-csi-mock-volumes-2142"}},"Response":{},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeStageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870","storage.kubernetes.io/csiProvisionerIdentity":"1587483430141-8081-csi-mock-csi-mock-volumes-2142"}},"Response":{},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodePublishVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/globalmount","target_path":"/var/lib/kubelet/pods/30a3a4c3-3cbd-41ac-93c8-2f54d2ffc1b6/volumes/kubernetes.io~csi/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870","storage.kubernetes.io/csiProvisionerIdentity":"1587483430141-8081-csi-mock-csi-mock-volumes-2142"}},"Response":{},"Error":"","FullError":null}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume","Request":{"volume_id":"4","target_path":"/var/lib/kubelet/pods/30a3a4c3-3cbd-41ac-93c8-2f54d2ffc1b6/volumes/kubernetes.io~csi/pvc-b3fd0f8a-c84e-409b-a1ba-6c10a75e1870/mount"},"Response":{},"Error":"","FullError":null}
```

The current theory is that this might be related to kubelet assuming that a CSI driver does real mounts, something that the mock driver (and potentially other) CSI drivers don't do. A fix for that is pending in https://github.com/kubernetes/kubernetes/pull/88759

That this test runs into this randomly is caused by the test doing more strict checking of CSI calls than other tests. The flaky test failures could be avoided by relaxing that checking, but that won't fix the underlying issue.

**Comment by msau42** [comment] 2020-05-06 00:36
I'm not sure I would pin it on the mount check yet. The broader question is why is MountVolume() getting called twice after the first one returns success.

**Closed** 2020-05-19 22:22 UTC
Labels: kind/flake, sig/storage

**Comment by humblec** [comment] 2020-05-27 16:44
@pohly @msau42 is it due that, the timeout of CSI transaction or call is very low where CSI driver takes more time than this timeout?
