### ISSUE TITLE
how to connect Kubernetes and docker container.

### ISSUE THREAD

**Issue by Leo-gred** [kubernetes/kubernetes#71125] opened 2018-11-16 10:55 UTC
i have Kubernetes local cluster. on one of Node, i have added docker containers /(using docker-compose.yaml file.)
if i run "docker ps" i can see all my RUN containers, but i can't add it to the dashuboard in Kubernetes, please help. 
@kubernetes
@Docker

**Comment by zegl** [comment] 2018-11-16 13:44
Duplicate of #71129

**Closed** 2018-11-17 00:48 UTC
Labels: needs-sig
