### ISSUE TITLE
e2e flake: Kubelet didn't started system pods

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22166] opened 2016-02-29 09:38 UTC
The following run of scalability suite failed, because system pods didn't start on one of the nodes:
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4911/build-log.txt

However, when looking into logs, it wasn't problem with node itself - it was ready all the time.
The problem is with this Kubelet:
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-scalability/4911/artifacts/104.154.18.94%3A22-kubelet.log

And when looking into logs, it seems that due to some reasons, neither kube-proxy nor fluentd were started due to lack of image.
There are a bunch of logs like this:

    E0228 19:13:32.279709    3477 pod_workers.go:138] Error syncing pod f18420c15cab3c6b54c0d9ca56c9f872, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: no such image"
    I0228 19:13:32.279761    3477 server.go:600] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-e2e-scalability-minion-yjqm", UID:"f18420c15cab3c6b54c0d9ca56c9f872", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: no such image"

We didn't start neither of those system pods on this node for 10 minutes.
@dchen1107 @yujuhong - can we do something with it?

@kubernetes/goog-node

**Comment by yujuhong** [comment] 2016-03-01 00:46
I checked the logs and besides the obvious "no such image" errors, pleg (the component which lists containers periodically) was completely silent after the docker restart.
```
E0228 19:12:34.233976    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: Get http://unix.sock/containers/json?all=1: read unix /var/run/docker.sock: connection reset by peer
E0228 19:12:34.353685    3477 kubelet.go:2897] Error getting image list: cannot connect to Docker endpoint
E0228 19:12:35.234386    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:36.234762    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:37.235223    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:38.235601    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:39.234332    3477 kubelet.go:2671] Container runtime sanity check failed: docker: failed to get docker version: cannot connect to Docker endpoint
I0228 19:12:39.234522    3477 kubelet.go:2341] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now container runtime is down]
E0228 19:12:39.235874    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:40.236240    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:41.236657    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:42.237113    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0228 19:12:43.237536    3477 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
I0228 19:12:44.197886    3477 container_bridge.go:68] CBR0 doesn't exist, attempting to create it with range: 10.245.22.1/24
I0228 19:12:44.228594    3477 container_bridge.go:58] Recreated cbr0 and restarted docker
I0228 19:12:44.234271    3477 linux.go:254] Didn't find bandwidth interface, creating
I0228 19:12:44.396132    3477 kubelet.go:2341] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now container runtime is down]
```

It stopped complaining about "cannot connect to Docker endpoint", but also never sent any events to the kubelet syncloop beyond that point.
I can only assume that its docker request hung and never returned. Since PLEG is crucial to kubelet's core operations, I uploaded #22233 to include a new health check for it.

I am not sure if this hung request is related to the "no such image" errors though. It seems we've run into this quite a lot recently. Perhaps we can change the docker logging level to INFO for test clusters to see if the image was pulled/deleted? The caveat is that docker logs a lot.

**Comment by dchen1107** [comment] 2016-03-01 18:27
We can temporarily set docker logging level to INFO for most of jenkins projects except the soaking ones. Will send PR to do that shortly.

**Comment by dchen1107** [comment] 2016-03-28 23:18
This failure is due to kube-proxy image is not successfully loaded to docker through docker load.

**Comment by dchen1107** [comment] 2016-03-28 23:20
Docker load sometimes hang. It is a known issue. And the script detects the hang, and restarts the docker. The problem is go away. This won't happen at real production. Since it is rare and not happen lately, I am closing this one for now.

**Closed by dchen1107** 2016-03-28 23:20 UTC
Labels: kind/flake, priority/P1, team/node
