### ISSUE TITLE
We should label master nodes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#28687] opened 2016-07-08 15:39 UTC
We should have a label for the master nodes, so that e.g. daemonsets can select masters

I propose: `roles.kubernetes.io/master: 1` and  `roles.kubernetes.io/node: 1`

(The "obvious" alternative, `kubernetes.io/role: master` does not allow for multiple roles)

**Comment by dims** [comment] 2016-07-26 21:24
1 implies, there could be a 2, 3, 4... So is "roles.kubernetes.io/master: true" any better?

**Comment by bprashanth** [comment] 2016-08-12 18:42
I'd expect daemonsets to just not schedule on unschedulable nodes, is that not the case (it isn't now, I'm asking if that's by design)?

**Comment by Random-Liu** [comment] 2016-08-12 18:44
Currently, there is still no good way avoid DaemonSet running on master.

Even though we've let DaemonSet to respect affinity https://github.com/kubernetes/kubernetes/pull/28803. However, there is no node label to distinguish master and node.

Should we add master and node labels? Or should we just add some kind of mechanism to let DaemonSet respect Unschedulable if we need that.

Ref #30491.

**Comment by timothysc** [comment] 2016-08-12 20:57
imho is DaemonSet does not respect "Unschedulable", then that is a bug.

**Comment by dchen1107** [comment] 2016-08-19 00:22
@mikedanese Could you please take care of this from daemonset? Or some other suggestion on how to handle this? This prevent node-problem-detector from running on e2e tests. Thanks!

**Comment by mikedanese** [comment] 2016-08-19 01:51
> imho is DaemonSet does not respect "Unschedulable", then that is a bug.

Unschedule existing is a bug :) (ref https://github.com/kubernetes/kubernetes/issues/29178). We need more fine grained control here.

The motivating use case for daemonsets is system components (node-problem-detector, log shipper, kube-proxy, sdn agent). Cluster operators want system components to be running and ready before workloads run on a given node. At the time the daemonset was introduced, the only way to gate the scheduler from scheduling to a node is to mark it unscheulable . Thus it could not have satisfied it's motivating use case if it had respected unschedulable.

The fix here is to:
1. enable the PodTolerateNodeTaints predicate to the daemonset controller 
2. add a --register-tainted option to the kubelet
3. deprecate --register-schedulable

**Comment by resouer** [comment] 2016-08-22 08:37
Thanks , @mikedanese Did you already send PR for this? I'd like to track it.

**Comment by caseydavenport** [comment] 2016-08-24 22:54
Is there a PR for this?

**Comment by mikedanese** [comment] 2016-08-30 01:13
Mostly fixed in https://github.com/kubernetes/kubernetes/pull/31647,

**Comment by mikedanese** [comment] 2016-09-05 17:42
This is not going to make it into v1.4 but will be fixed early v1.5.

**Comment by dims** [comment] 2016-11-15 16:08
@mikedanese - switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree, cc @saad-ali @calebamiles)

**Comment by mikedanese** [comment] 2016-11-15 19:12
That's fine.

**Closed** 2016-12-07 06:11 UTC
Labels: component/nodecontroller, kind/bug, priority/P1, team/control-plane, team/node
