### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by mvdan** [kubernetes/kubernetes#23281] opened 2016-03-21 16:17 UTC
Hidden under two levels of docs [here](https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md) coming from `CONTRIBUTING`, you have this:

```
If filing a bug, please include detailed information about how to reproduce the problem, such as:

* Kubernetes version: kubectl version
* Cloud provider, OS distro, network configuration, and Docker version
* Steps to reproduce the problem
```

It would be much better to have this as an issue template, as described here:

https://github.com/blog/2111-issue-and-pull-request-templates

Would probably be a good idea to do the same for PRs, e.g. to suggest that people sign the CLA first or that they run the tests and gofmt.

**Comment by maisem** [comment] 2016-03-21 18:22
cc @johndmulhausen

**Comment by mml** [comment] 2016-03-24 20:22
In addition, we could include text in the template to make it clear that ordinary support issues belong in stackoverflow.

**Comment by bgrant0607** [comment] 2016-04-06 05:52
cc @dchen1107 @david-mcmahon

**Comment by bgrant0607** [comment] 2016-04-06 05:53
Dupe of #21437

**Closed by bgrant0607** 2016-04-06 05:53 UTC
Labels: team/none

**Comment by david-mcmahon** [comment] 2016-04-06 18:21
ref #23743
