### ISSUE TITLE
tool to update a file in a configmap or generic secret

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#25832] opened 2016-05-18 21:10 UTC
I have some configmap and secrets that contain binary data. Downloading the configmap, and editing it by hand to update the data in them is perilous.

One current alternative is deleting and recreating the configmap but it's easy to forget you deleted it or screw up the replace and wander off for lunch while a deploy occurs which then breaks.

Another alternative is making a new configmap with a new path and then updating the deployments that need to use it. This seems a little too onerous and involves making the kubernetes user encode some version information into their configmap names which seems fragile.

It would be nice to get a `replace` like command but that was for updating a key in the config-map with a similar `--from-file` interface as `create config-map` so that the user doesn't screw up the encoding in the file.

(I've used "configmap" above, but all of the same issues occur for secrets, as well).

**Comment by sgrimee** [comment] 2016-05-19 20:41
I was given this trick on the slack channel:
```kubectl create configmap nginx-lb-config --from-file=nginx-lb.configmap --dry-run -o yaml | kubectl replace configmap nginx-lb-config -f -```

**Comment by jmhodges** [comment] 2016-07-24 07:52
Oh, while I'm back here to look this up again, I should note using that command doesn't prevent you from accidentally replacing a configmap that's been modified while you weren't looking.

Not sure how to make that happen from the command line without a bunch of `base64` and `kubectl patch` work.

**Comment by derekmahar** [comment] 2016-09-09 23:17
@jmhodges As an aside, can a container read a binary file from a volume to which is mapped a Kubernetes ConfigMap that contains that binary file?  Please see http://stackoverflow.com/questions/39420102/does-kubernetes-support-a-binary-file-in-a-configmap.

**Comment by liggitt** [comment] 2016-09-11 04:23
config maps are text-only, I believe. @pmorie can confirm/deny

**Comment by bgrant0607** [comment] 2016-10-25 00:29
Support for binary in configmaps was requested in #32432.

**Comment by bgrant0607** [comment] 2017-09-01 17:51
Closing this as a dupe of #30558 (updates of ConfigMap and Secret) and #32432 (support for binary data in ConfigMap).

**Closed by bgrant0607** 2017-09-01 17:51 UTC
Labels: area/configmap-api, area/kubectl, kind/feature, priority/awaiting-more-evidence, sig/cli, sig/node, team/ux (deprecated - do not use)
