### ISSUE TITLE
Kubelet gets throttled by AWS metadata service and becomes NotReady

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/kubernetes#49331] opened 2017-07-20 22:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We run Kubernetes in AWS. When cluster is scaled up to hundreds of minions, `kubelet` starts to get throttled by AWS when it tries to get node metadata and updates status.

```
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: E0720 17:30:38.975616   18998 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: EC2MetadataError: failed to make EC2Metadata request
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: caused by: <?xml version="1.0" encoding="iso-8859-1"?>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:  <head>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:   <title>429 - Too Many Requests</title>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:  </head>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:  <body>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:   <h1>429 - Too Many Requests</h1>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]:  </body>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: </html>
Jul 20 17:30:38 ip-10-72-34-220.us-west-2.compute.internal kubelet[18998]: E0720 17:30:38.975633   18998 kubelet_node_status.go:294] Unable to update node status: update node status exceeds retry count
```

Because of the failure the minion becomes `NotReady` and pods become `Unknown`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run a Kubernetes cluster in AWS with the flag `--cloud-provider=aws`. Launch enough minions and this error can be observed.

**Anything else we need to know?**:
In AWS, once a VM is launched its node IP is unlikely to change. I think we can add caching here, instead of requesting node IP from AWS metadata every time. However there might be other information we need to get from AWS on node status update, and caching might not work for those scenarios.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.5.7
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): "Container Linux by CoreOS 1353.7.0 (Ladybug)"
- Kernel (e.g. `uname -a`): `Linux ip-10-72-33-125.us-west-2.compute.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux`
- Install tools: Terraform
- Others:

**Comment by d-grigorenko** [comment] 2017-07-21 01:48
this is another flavor of https://github.com/kubernetes/kubernetes/issues/16593 The fix applied there https://github.com/kubernetes/kubernetes/pull/16633/files just moved the hotspot from AWS API to ec2metadata service. 

In broader sense this ticket https://github.com/kubernetes/kubernetes/issues/19124 points out that cloud provider API unavailability causes nodes become NotReady. This https://github.com/kubernetes/kubernetes/pull/25571 somehow mitigates that.

Possible solutions for the issue
* increase retries (currently 4, totally 5 tries) and delays between retries (now 20 milliseconds). As logs suggest, all 5 tries failed so the node was market NotReady. Ideally delays shall be randomized to avoid collisions.
* Cache and do not update persistent data such as local IP

The issue seems to be dupe of https://github.com/kubernetes/kubernetes/issues/41904

**Closed** 2018-03-13 03:38 UTC
Labels: kind/feature, lifecycle/rotten, sig/aws
