### ISSUE TITLE
kubeproxy started failed due to null point exceptions

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#51680] opened 2017-08-31 06:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When I start the kube proxy found the proxy can not started like below:
```
root@hchenk8s2:~# ./hyperkube proxy --kubeconfig=/var/lib/kubelet/kube-proxy-config --hostname-override=9.111.254.208 --proxy-mode=iptables --cluster-cidr=10.1.0.0/16
2017-08-31 14:14:39.555955 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-31 14:14:39.556128 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-31 14:14:39.556171 I | proto: duplicate proto type registered: google.protobuf.Timestamp
W0831 14:14:39.616916    5353 server.go:197] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0831 14:14:39.658407    5353 server.go:496] Using iptables Proxier.
I0831 14:14:39.671639    5353 server.go:531] Tearing down inactive rules.
E0831 14:14:39.736131    5353 proxier.go:691] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)
I0831 14:14:39.748434    5353 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0831 14:14:39.748476    5353 conntrack.go:52] Setting nf_conntrack_max to 131072
I0831 14:14:39.748510    5353 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0831 14:14:39.748532    5353 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0831 14:14:39.748606    5353 config.go:202] Starting service config controller
I0831 14:14:39.748634    5353 controller_utils.go:1010] Waiting for caches to sync for service config controller
I0831 14:14:39.748675    5353 config.go:102] Starting endpoints config controller
I0831 14:14:39.748684    5353 controller_utils.go:1010] Waiting for caches to sync for endpoints config controller
E0831 14:14:39.753209    5353 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:199
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:875
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:312
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:645
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:225
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:182
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:57
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x34b6754]

goroutine 137 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x41b4d80, 0x969b540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/proxy/iptables.newServiceInfo(0xc42023fb57, 0x7, 0xc42023fb60, 0xa, 0xc42023fb98, 0x5, 0xc4209ed310, 0xc420e73180, 0x38cb07564a860e17)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:199 +0x9d4
k8s.io/kubernetes/pkg/proxy/iptables.serviceToServiceMap(0xc420e73180, 0xc4207ed4a0)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:875 +0x1c8
k8s.io/kubernetes/pkg/proxy/iptables.(*serviceChangeMap).update(0xc420c4f200, 0xc421077df8, 0x0, 0xc420e73180, 0x99fb800)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:312 +0xb4
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).OnServiceAdd(0xc420c4f1e0, 0xc420e73180)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:645 +0x9a
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0xc4209f70b0, 0x495e5e0, 0xc420e73180)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:225 +0xe8
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).(k8s.io/kubernetes/pkg/proxy/config.handleAddService)-fm(0x495e5e0, 0xc420e73180)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:182 +0x3e
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc4201c71e0, 0xc4201c71f0, 0xc4201c7200, 0x495e5e0, 0xc420e73180)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc4209ddc20, 0x495e5e0, 0xc420e73180)
	<autogenerated>:57 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420acceb0)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4203042f8, 0xc4201c7df0)
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. checkout latest kubernetes sourcecode
2. make the kubernetes to get hyperkube
3. startup the kubeproxy

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yastij** [comment] 2017-08-31 09:43
cc @ncdc

**Comment by ncdc** [comment] 2017-08-31 11:04
This is a duplicate of #51499

**Closed by ncdc** 2017-08-31 11:04 UTC
Labels: kind/bug, needs-sig
