### ISSUE TITLE
The endpoint status does not update when the pod state changes rapidly.

### ISSUE THREAD

**Issue by QuantumEnergyE** [kubernetes/kubernetes#125638] opened 2024-06-22 11:13 UTC
### What happened?

![image](https://github.com/kubernetes/kubernetes/assets/19217340/7686ae10-e598-4d8f-8c8c-b28b16338912)

----
t2
1. Pod update event: ready to notReady
2. syncService
3. currentEndpoints state(from lister: Ready) do not equal to  target state(notReady)
4. clientSet.Endpoints.Update: update etcd to notReady

----
t3
1. Pod update event : notReady to ready(<xxMS)
2. syncService
3. **currentEndpoints state(from lister: Ready) equal to  target state(ready)，do not update Endpoints**

----
----
t4
1. Endpoint update event:  update endpoint lister cache to notReady
----

### What did you expect to happen?

The status of the endpoint should match the status of the pod.

### How can we reproduce it (as minimally and precisely as possible)?

Make the Pod status change rapidly. 
Lowering the etcd push interval should make it easier to reproduce.

### Kubernetes version

v1.25.3

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment] 2024-06-22 11:24
/sig network

@tnqn it seems this change is causing this problem https://github.com/kubernetes/kubernetes/commit/38966453ce106c2a5ac77816805fa8b086323b21

**Comment by tnqn** [comment] 2024-06-22 13:03
> @tnqn it seems this change is causing this problem [3896645](https://github.com/kubernetes/kubernetes/commit/38966453ce106c2a5ac77816805fa8b086323b21)

@aojea [3896645](https://github.com/kubernetes/kubernetes/commit/38966453ce106c2a5ac77816805fa8b086323b21) is indeed related but the root cause seems that `syncService` uses outdated informer cache. I think it can be fixed by having a "endpointsTracker" (like "endpointSliceTracker" in EndpointSliceController) to track Endpoints resource versions expected for each Service, to know if the Endpoints in informer cache is outdated, and to know if an Endpoints ADD/UPDATE event should trigger resyncing the Service. I could create a PR if the solution works for you.

**Comment by aojea** [comment] 2024-06-22 22:42
> > @tnqn it seems this change is causing this problem [3896645](https://github.com/kubernetes/kubernetes/commit/38966453ce106c2a5ac77816805fa8b086323b21)
> 
> @aojea [3896645](https://github.com/kubernetes/kubernetes/commit/38966453ce106c2a5ac77816805fa8b086323b21) is indeed related but the root cause seems that `syncService` uses outdated informer cache and doesn't subscribe to Endpoints ADD/UPDATE events. I think it can be fixed by having a "endpointsTracker" (like "endpointSliceTracker" in EndpointSliceController) to track Endpoints resource versions expected for each Service, to know if the Endpoints in informer cache is outdated, and to know if an Endpoints ADD/UPDATE event should trigger resyncing the Service. I could create a PR if the solution works for you.

How complex will it be? We don't want to invest much on this controller since we moved to endpointslice
I think your pr was right, but this consequences is something we didn't prevent... The bug seems legit though

**Closed** 2024-07-03 06:48 UTC
Labels: kind/bug, sig/network, area/controller-manager, needs-triage

**Comment by kedar700** [comment] 2024-08-07 14:13
We are still seeing this currently with 1.29.7 where endpoints are staying out of sync 
```
I0807 14:01:51.613700       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
I0807 14:01:51.624576       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
I0807 14:01:51.645704       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
I0807 14:01:51.686942       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
I0807 14:01:51.768648       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
I0807 14:01:51.808043       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test2-qa" err="endpoints informer cache is out of date, resource version 10168250766 already processed for endpoints test1/test2-qa"
I0807 14:01:51.930345       2 endpoints_controller.go:348] "Error syncing endpoints, retrying" service="test1/test-qa" err="endpoints informer cache is out of date, resource version 10168236546 already processed for endpoints test1/test-qa"
```

**Comment by aojea** [comment] 2024-08-13 18:51
@kedar700 the error is retried, is the status not being updated after the retry?
