### ISSUE TITLE
AWS: use EBS volume for minion instance

### ISSUE THREAD

**Issue by james-thimont-bcgdv** [kubernetes/kubernetes#12074] opened 2015-07-31 09:32 UTC
I'm using instance types without instance storage and the root disk fills up very quickly with docker images.  Could we add an option to attach EBS volumes to the minions for more disk space?

**Comment by justinsb** [comment] 2015-07-31 14:48
Which instance type are you using?  If you use an instance type that has instance storage, we will use that by default.  Instance storage should be a better match for Docker storage (ephemeral, higher-speed, more-reliable, cheaper).

The problem is that AWS seems to be moving away from instance storage in their latest families (c4 and m4).  AWS launched the m4/c4 family pretty late in the Kubernetes release cycle.  If the c5/m5 use instance storage, I agree we will probably have to add the option for EBS volumes on the minions.

Can you use c3/m3/r3 instances instead?  This may be a doc issue ("we should recommend c3/m3/r3") or it may be that really should support EBS volumes on the minions.  It may well be both!

**Comment by jtbcgdv** [comment] 2015-07-31 14:56
Hi Justin,
The m3.large is fine but the m3.medium only has 4Gb SSD.
Whilst building prototypes etc. I want to keep the cluster running costs down and use inexpensive instance types.

**Comment by fagiani** [comment] 2016-04-02 01:13
@justinsb, here is some feedback as I've been playing around with m3.medium setup and those are a couple of things I've tried in order to skip the 4Gb SSD drive and only use the EBS one (all changes were done in the `cluster/aws/util.sh` file):

1. Setting `BLOCK_DEVICE_MAPPINGS_BASE=""` will throw an error in the master host creation about JSON parsing:

        Starting Master
        No JSON object could be decoded
2. Setting `BLOCK_DEVICE_MAPPINGS_BASE="{}"` will go fine with master but halt on the minion configuration:

        Creating minion configuration
        Parameter validation failed:
        Missing required parameter in BlockDeviceMappings[1]: "DeviceName"

3. Keeping `BLOCK_DEVICE_MAPPINGS_BASE` intact and then removing it from the `NODE_BLOCK_DEVICE_MAPPINGS` will create both master and minions but will hang at the end with infinite messages like this:

        ... calling validate-cluster
        Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
        <...>
        Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
        Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
        Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
        Detected 0 ready nodes, found 0 nodes out of expected 2. Your cluster may not be fully functional.

I am now wondering if skipping SSD storage mount on the minions will break its core functionality or if the validate-cluster is trying to ensure some hard spec that requires the SSD mount. I may continue checking further on that later.

**Comment by justinsb** [comment] 2016-11-15 15:40
We're not going to be making further changes in kube-up, and kops solves this problem by using an EBS volume always (which then created a problem/opportunity to make better use of instance storage, but that's an aside...).  Closing.

**Closed by justinsb** 2016-11-15 15:40 UTC
Labels: area/cluster-lifecycle, area/platform/aws, priority/P2, team/sig-aws
