### ISSUE TITLE
On update Kubelet starts the new manifest-run pod before fully stopping the old one  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#42061] opened 2017-02-24 17:15 UTC
Version:
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.190+2bb97435eb5af0", GitCommit:"2bb9
7435eb5af02c6e75964c909069e438b19bae", GitTreeState:"clean", BuildDate:"2017-02-24T13:41:51Z", GoVersion:"go1.7.5",
 Compiler:"gc", Platform:"linux/amd64"} - HEAD, synced today.

I started K8S cluster with ./cluster/kube-up.sh with Cluster Autoscaler enabled. I modified the CA manifest file on the master. In logs the new autoscaler complained about port 8085 being used (by the old CA) and the old one stopped writing logs COUPLE seconds after this port unavailable entry was written. 

I guess the old POD should be stopped first and only then the new pod should started.

cc: @kubernetes/sig-node-bugs @dchen1107 @vishh @yujuhong  @fgrzadkowski @MaciekPytel

**Comment by mwielgus** [comment] 2017-02-24 17:16
cc: @yujuhong

**Comment by wojtek-t** [comment] 2017-02-24 19:19
This seems exactly like that problem @fgrzadkowski faced while his manual tests of etcd v3 upgrade - @mml FYI

**Comment by wojtek-t** [comment] 2017-02-24 19:34
BTW - that seems pretty serious to me.

**Comment by vishh** [comment] 2017-02-24 22:09
@yujuhong do you want me to take a stab at this or have you got this?

**Comment by yujuhong** [comment] 2017-02-24 23:29
I don't think this is a regression. Maybe just flaw in the existing behavior. AFAIK, any change in the manifest file would result in a different UID for the pod. To kubelet, this is a entirely new pod. There is no dependence between the creation of the new pod and the deletion of the old one.

**Comment by dchen1107** [comment] 2017-02-25 01:31
First: this is not a regression like what @yujuhong pointed out above. 

Second: Pod is immutable except the container image (which is also arguable). If you want to change pod, delete the old one, and create a new pod instance. For static pod, there is no easy way to guarantee the change is only to the container image, we agreed long time ago any modification to the manifest file should result in a new Pod. This is an intended behavior by design for the static pods.

Third: we strongly suggested not to use the static pods except two use cases: 1) masterless Kubelet (Standalone Kubelet) 2) first node in self-hosting. 

In your use case, why are you using static pod for Cluster Autoscaler? Why not using daemonset? If you must use the static pod, please introducing your own controller to guarantee the order between old and new pods. Same story for etcd server too. cc/ @mml who is working on etcd3 upgrade. 

I am inclined to close this issue as the design intended.

**Comment by wojtek-t** [comment] 2017-02-26 11:06
> In your use case, why are you using static pod for Cluster Autoscaler? Why not using daemonset? If you must use the static pod, please introducing your own controller to guarantee the order between old and new pods. Same story for etcd server too. cc/ @mml who is working on etcd3 upgrade.

As for "etcd" - how you can make it a DaemonSet? If etcd is not running, apiserver is not running, and thus any other components won't know what they should be scheduling/creating/running. This just won't work.
In a setup with a single master instance (or to be more clear: with a single etcd instance), this is just undoable.

As for cluster autoscaler, this would work as long as master node is registered in the cluster. Which is not the case in GKE, which means we can't really do it now.

> I am inclined to close this issue as the design intended.

I was really surprised that this is by-design, but reading your rationale it make sense to me. However I think should be very clearly documented, and I wasn't able to find it anywhere. So we should probably at least document it before closng this issue.

**Comment by mml** [comment] 2017-02-27 19:35
@wojtek-t the upshot of this design is that if pod authors need to guard against two versions of their pod running at the same time, they need to add that themselves.  Sometimes you might be able to do it in a little shell script wrapper, but maybe you would add it to your server directly.

I filed #42184 as a followup.

**Comment by dchen1107** [comment] 2017-03-10 19:33
I am closing this one as what we discussed above. Also @mml filed #42184 to track etcd related issue.

**Closed by dchen1107** 2017-03-10 19:33 UTC
Labels: area/kubelet, priority/important-soon, sig/node
