### ISSUE TITLE
[Failing Test] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode / default fs)] volume-stress multiple pods should access different volumes repeatedly [Slow] [Serial]

### ISSUE THREAD

**Issue by tico88612** [kubernetes/kubernetes#128324] opened 2024-10-25 01:58 UTC
### Which jobs are failing?

- sig-release-master-informing
  - gce-cos-master-serial

### Which tests are failing?

- `Kubernetes e2e suite.[It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] volume-stress multiple pods should access different volumes repeatedly [Slow] [Serial]`
- `Kubernetes e2e suite: [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] volume-stress multiple pods should access different volumes repeatedly [Slow] [Serial]`

### Since when has it been failing?

2024-10-23 12:40 PDT

[352056f09](https://github.com/search?q=repo:kubernetes/kubernetes+352056f09&type=commits)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

### Reason for failure (if possible)

```
{ failed [FAILED] Failed to wait for pod-6 [&Pod{ObjectMeta:{pod-9420b3ba-fa6f-4da2-bab3-b57bc29584fb  stress-379    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:PodSpec{Volumes:[]Volume{Volume{Name:volume1,VolumeSource:VolumeSource{HostPath:nil,EmptyDir:nil,GCEPersistentDisk:nil,AWSElasticBlockStore:nil,GitRepo:nil,Secret:nil,NFS:nil,ISCSI:nil,Glusterfs:nil,PersistentVolumeClaim:&PersistentVolumeClaimVolumeSource{ClaimName:csi-hostpathdc6bb,ReadOnly:false,},RBD:nil,FlexVolume:nil,Cinder:nil,CephFS:nil,Flocker:nil,DownwardAPI:nil,FC:nil,AzureFile:nil,ConfigMap:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Projected:nil,StorageOS:nil,CSI:nil,Ephemeral:nil,Image:nil,},},},Containers:[]Container{Container{Name:write-pod,Image:registry.k8s.io/e2e-test-images/busybox:1.36.1-1,Command:[/bin/sh -c trap exit TERM; while true; do sleep 1; done],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:volume1,ReadOnly:false,MountPath:/mnt/volume1,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,},},RestartPolicy:OnFailure,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c0,c1,},RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:*1000,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,SeccompProfile:nil,AppArmorProfile:nil,SupplementalGroupsPolicy:nil,},ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},SetHostnameAsFQDN:nil,OS:nil,HostUsers:nil,SchedulingGates:[]PodSchedulingGate{},ResourceClaims:[]PodResourceClaim{},},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},Resize:,ResourceClaimStatuses:[]PodResourceClaimStatus{},HostIPs:[]HostIP{},},}] turn into running status. Error: Timed out after 300.001s.
Expected Pod to be in <v1.PodPhase>: "Running"
Got instead:
    <*v1.Pod | 0xc002a26908>: 
        metadata:
          creationTimestamp: "2024-10-23T20:24:51Z"
          managedFields:
......(truncate)
```

### Relevant SIG(s)

/sig storage
@kubernetes/release-team-release-signal

**Comment by carlory** [comment] 2024-10-25 02:33
cc @torredil may be related to https://github.com/kubernetes/kubernetes/pull/127757

**Comment by carlory** [comment] 2024-10-25 02:59
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L85

cc @sanposhiho @torredil  This PR https://github.com/kubernetes/kubernetes/pull/127757 didn't register events for the volume attachment object changes, so we should add it. It's related to the existing Umbrella issue which was marked as complete. https://github.com/kubernetes/kubernetes/issues/118893 

It may be the root cause of the failing test.  

/assign @torredil 

Could you send a fix?

**Comment by sanposhiho** [comment] 2024-10-25 03:04
I suggest just adding a necessary event to EventsToRegister for a quick fix for this failure. QHint can be follow-up later.

**Closed** 2024-10-26 15:00 UTC
Labels: sig/storage, kind/failing-test, needs-triage
