### ISSUE TITLE
Deployment E2E tests failing in upgrade test jobs

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42449] opened 2017-03-02 23:40 UTC
@pwittrock you are listed as the test owner in test_owners.csv so directing this at you for now.

Most of the Deployment E2E tests are failing in the upgrade test jobs. See, for example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-latest-upgrade-cluster/479

Common error message:

Expected an error to have occurred.  Got:
    <nil>: nil

Note that the 1.6 release upgrade test jobs are not set up yet, but I'm trying to get ahead of issues by looking at the jobs running off master. Thanks!

**Comment by kargakis** [comment] 2017-03-03 11:49
@kubernetes/sig-apps-test-failures

**Comment by kargakis** [comment] 2017-03-03 11:50
Why are we expecting an error to occur on every test?:)

**Comment by kargakis** [comment] 2017-03-03 11:54
Is this test running 1.6 tests against a 1.4 cluster? This should explain the other deployment failure regarding the overlapping test.

**Comment by skriss** [comment] 2017-03-03 18:49
It should actually be the opposite, i.e. running 1.4 tests against a 1.6 cluster (that was upgraded from a 1.4 cluster)

**Comment by kargakis** [comment] 2017-03-03 21:38
The deployment overlap behavior has changed in 1.6 and is about to be dropped entirely, assuming https://github.com/kubernetes/kubernetes/pull/42175 gets merged. It was just bandage over a user error but that should not be possible in 1.6 with owner references. This means that the test is obsolete. I don't know what happens in this case. cc: @janetkuo

**Comment by kargakis** [comment] 2017-03-03 21:40
I am talking about https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-latest-upgrade-cluster/479#k8sio-deployment-overlapping-deployment-should-not-fight-with-each-other

**Comment by janetkuo** [comment] 2017-03-04 01:15
Looking at the test, it expects get deployment to fail to make sure it's deleted  https://github.com/kubernetes/kubernetes/blob/b440e9a9dbb30b/test/e2e/deployment.go#L206

**Comment by janetkuo** [comment] 2017-03-04 01:18
Something to do with garbage collector?

**Comment by skriss** [comment] 2017-03-09 21:48
@kargakis @janetkuo can you clarify the status? To be clear, for 1.5->1.6 upgrades, there are 2 failing Deployment tests in the jobs that perform an upgrade then run 1.5 tests to check for compatibility. Are these issues that need to be addressed for the 1.6 release? 

[k8s.io] Deployment deployment reaping should cascade to its replica sets and pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:62
Expected an error to have occurred.  Got:
    <nil>: nil
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:192

[k8s.io] Deployment overlapping deployment should not fight with each other
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:98
Failed to update the second deployment's overlapping annotation
Expected error:
    <*errors.errorString | 0xc420388ca0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:1223

Note that both of these pass in the jobs that upgrade 1.5->1.6 and then run the 1.6 tests.

**Comment by skriss** [comment] 2017-03-09 21:49
upgrade 1.5->1.6, run 1.5 tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster/21

upgrade 1.5->1.6, run 1.6 tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster-new/22

**Comment by kargakis** [comment] 2017-03-10 09:48
> upgrade 1.5->1.6, run 1.5 tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster/21

The overlapping test is obsolete for 1.6 as the functionality has been totally rewritten.
@krmayankk can you have a look in the cascading deletion test as you introduced server side deletion in Deployments?

> upgrade 1.5->1.6, run 1.6 tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster-new/22

This is something that @enisoc is currently looking into - seems like the problem is that the upgrade suite is compiled with a 1.6 when it runs the 1.5 part of the upgrade.

**Comment by skriss** [comment] 2017-03-13 20:38
@krmayankk please update by EOD today on whether the cascading deletion failure is a blocking issue for 1.6 or not; if it is, we need to get a PR in by tomorrow for the next beta/RC.

**Comment by kargakis** [comment] 2017-03-13 21:29
@caesarxuchao can you also have a look? It seems related to the kubectl reaper not deleting the deployment, likely because it goes through the GC in the end?

**Comment by caesarxuchao** [comment] 2017-03-13 22:03
The "[k8s.io] Deployment deployment reaping should cascade to its replica sets and pods" failure is because the deployment is not deleted yet because of the orphan finalizer when the 1.5 reaper.Stop() returns, see https://github.com/kubernetes/kubernetes/pull/35676#issuecomment-268126158. 1.6 kubectl won't have this problem because of https://github.com/kubernetes/kubernetes/pull/40576. 

I expect the upgrade test will fail all the deletion test for other controllers as well, after @enisoc's PRs that add controllerRef get merged.

I suggest that 
1. we communicate this behavior change of old kubectl via CHANGELOG.
2. Cherrypick https://github.com/kubernetes/kubernetes/pull/40576 to 1.5.

**Comment by janetkuo** [comment] 2017-03-14 01:22
Filed #43041 to fix this test failure by updating 1.5 reapers (#40576 has changes we don't want, so filed a separate PR). 

@skriss this doesn't block 1.6. The fix will be towards 1.5.

**Comment by kargakis** [comment] 2017-03-18 04:19
@skriss can you give an update on this issue?

**Comment by skriss** [comment] 2017-03-20 16:53
The deployment reaping issue appears to be fixed per https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-container_vm-1.5-container_vm-1.6-upgrade-cluster&width=20

Thanks!

**Closed** 2017-03-29 17:14 UTC
Labels: area/workload-api/deployment, kind/flake, kind/upgrade-test-failure, priority/failing-test, sig/apps
