### ISSUE TITLE
Deleting not scheduled POD cause scheduler errors

### ISSUE THREAD

**Issue by Hexta** [kubernetes/kubernetes#37609] opened 2016-11-29 07:33 UTC
Deleting not scheduled POD cause scheduler errors. 
kube-scheduler log contains messages like

> Error getting pod default/stress-1000200342-pi0f8 for retry: pod (stress-1000200342-pi0f8) failed to fit in any node

**Steps to reproduce**:
1. kubectl run stress --image progrium/stress --limits='cpu=300' --replicas=1 -- --cpu 1
2. kubectl delete deploy stress

**Kubernetes version**: 1.4.5

**Environment**:
- Bar-metal
- **OS**: Ubuntu 16.04.1

**Comment by timothysc** [comment] 2016-12-07 23:32
@jayunit100 please eval, por favor.

**Comment by resouer** [comment] 2016-12-27 14:22
Sorry, can't reproduce this case anyhow on fresh upstream master @Hexta ...

Could you provide more detail? Did you see this frequently? Can you repro it?

**Comment by Hexta** [comment] 2016-12-29 10:39
@resouer I also can't reproduce it on k8s 1.5.1.
May be this issue has been fixed indirectly.

**Comment by resouer** [comment] 2016-12-30 11:27
OK, then I will close this for now, feel free to re-open it when you encounter this again.

**Closed by resouer** 2016-12-30 11:27 UTC
Labels: kind/bug, sig/scheduling

**Comment by steinnes** [comment] 2017-02-01 14:57
I can't easily reproduce this but I have a cluster which I think is running into this very issue right now:
![image](http://static.steinn.org/kube-sched-weird.gif)


What I did was to add some deployments to the default namespace, then delete them after I made some mistake which I think caused two replica sets to step on each other's toes (label overlap) and caused a lot of pods being scheduled and killed.

This was ~2 months ago when I was first setting up kubernetes, and this is a dev cluster which has been fine, but not closely monitored, and is acting up now, and I started examining the logs.

I'm running on AWS with kubernetes 1.4.5, and used kube-up.sh to setup the cluster with the following parameters:
```
KUBE_AWS_ZONE=eu-central-1a
NUM_NODES=4
MASTER_SIZE=m3.medium
NODE_SIZE=t2.small
AWS_S3_REGION=eu-central-1
AWS_S3_BUCKET=takumi-kubernetes-artifacts
KUBE_AWS_INSTANCE_PREFIX=k8s
```

**Comment by steinnes** [comment] 2017-02-01 15:27
I started looking at the kube-scheduler logs because the cluster was slow to respond to requests and I noticed chunks of 404'd requests in the kube-apiserver logs:
![image](https://cloud.githubusercontent.com/assets/1097582/22512023/868b87ec-e88f-11e6-8f03-5696fc83d50d.png)

The source seems to be kube-scheduler, so I took a look there and saw what's in the gif above, and upon closer inspection it seems the errors or of two kinds:
```
E0201 15:02:38.613513       5 factory.go:544] Error getting pod default/takumi-server-dev-3422730534-fjx4c for retry: Operation cannot be fulfilled on pods/binding "takumi-server-dev-3422730534-fjx4c": pod takumi-server-dev-3422730534-fjx4c is being deleted, cannot be assigned to a host; retrying...
```

and the more frequent:
```
E0201 10:24:36.697155       5 factory.go:544] Error getting pod default/takumi-server-dev-3422730534-ihn4z for retry: pod (takumi-server-dev-3422730534-ihn4z) failed to fit in any node
fit failure on node (ip-172-20-0-26.eu-central-1.compute.internal): Insufficient cpu
fit failure on node (ip-172-20-0-79.eu-central-1.compute.internal): Insufficient cpu
fit failure on node (ip-172-20-0-28.eu-central-1.compute.internal): Insufficient cpu
fit failure on node (ip-172-20-0-27.eu-central-1.compute.internal): Insufficient cpu
```

Interestingly enough all my nodes seem to have room according to their allocated resources and they are only utilizing 10-15% of their CPU, and have a credit balance of 200+ CPU credits (t2 family on AWS).  But one of the nodes listed there (ip-172-20-0-28.eu-central-1.compute.internal) was a node that stopped responding a while back and isn't part of the cluster anymore.

### ip-172-20-0-26.eu-central-1.compute.internal
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  710m (71%)	400m (40%)	370Mi (18%)	470Mi (23%)
```

### ip-172-20-0-79.eu-central-1.compute.internal
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  400m (40%)	200m (20%)	800Mi (39%)	800Mi (39%)
```

### ip-172-20-0-27.eu-central-1.compute.internal
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  488m (48%)	288m (28%)	806416Ki (39%)	806416Ki (39%)
```

The pods which are listed in the log with the error in `failed to fit in any node` and the pods which are erroring due to `is being deleted, cannot be assigned to a host; retrying` are not the same.

I am a total beginner at kubernetes, but it seems to me the scheduler is stuck somewhere trying to
