### ISSUE TITLE
[Failing Test] Kubemark-5000

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#77602] opened 2019-05-08 15:31 UTC
**Which jobs are failing**:
ci-kubernetes-kubemark-gce-scale

**Which test(s) are failing**:
Density test

**Since when has it been failing**:
Run 1125829298771464196. 	2019-05-07 18:27:02 +0000 UTC

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-kubemark#kubemark-5000

**Reason for failure**:
Durring saturation phase only 3816 pods are scheduled.

**Anything else we need to know**:
It looks like the same issue happens to kubemark-100-high-density. The number of scheduled pods stops at 349.

**Comment by mm4tt** [comment] 2019-05-08 15:41
It looks like kubemark failed to initialize properly -
```
I0507 19:06:42.665] Found only 500 ready hollow-nodes while waiting for 5000.
```

Same thing in the kubemark-100-high-density. I'm 99% sure it's caused by https://github.com/kubernetes/kubernetes/issues/77551, which should get fixed once https://github.com/kubernetes/kubernetes/pull/77580 gets merged.

**Comment by mm4tt** [comment] 2019-05-09 07:46
https://github.com/kubernetes/kubernetes/pull/77580 got merged and it looks better now, from the on-going kubemark 5000:
```
W0509 07:45:06.859] I0509 07:45:06.859446   20316 scheduling_throughput.go:121] SchedulingThroughput: labelSelector(group = saturation): 39961 pods scheduled
```
and it's increasing.

**Comment by mm4tt** [comment] 2019-05-10 07:09
/close
Closing this one, as of today the density test has passed in both kubemark-5000 and kubemark-100-high-density.

**Closed by mm4tt** 2019-05-10 07:09 UTC
Labels: kind/failing-test, sig/scalability
