### ISSUE TITLE
Node leases not being GC'd

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#84981] opened 2019-11-08 10:40 UTC
I recently observed that node lease objects are staying around even after nodes got deleted. It seems like there is no reconcile logic for deleting orphaned node lease objects anywhere in the k8s control-plane. This is leading to stale objects piling up in etcd over time. Even worse if nodes are being created/deleted at a high rate.

Wojtek pointed me to kubelet code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodelease/controller.go#L220) where we come close to identifying this situation, but there also no lease cleanup is happening. Nevertheless, we need some controller to be doing this cleanup outside of kubelet (as kubelet can go poof anytime and node be deleted). Maybe node-lifecycle-controller?

@wojtek-t - can you share thoughts you were suggesting in our offline discussion?

@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment] 2019-11-08 11:41
I think that at the kubelet level, we should introduce an invariant that Lease object is created after the Node object is created - i.e. by changing
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodelease/controller.go#L92

That said, given that we may have leaked some Leases already, we need to extend nodelifecyclecontroller to:
- periodically list leases (from the local cache)
- find those that doesn't have owner-refs set
- for those if the corresponding Node exists, set the owner-refs, otherwise delete the Lease

**Comment by tedyu** [comment] 2019-11-08 12:58
How about the following as a starter ?
```
diff --git a/pkg/controller/nodelifecycle/node_lifecycle_controller.go b/pkg/controller/nodelifecycle/node_lifecycle_controller.go
index 151cd724b8..653885863c 100644
--- a/pkg/controller/nodelifecycle/node_lifecycle_controller.go
+++ b/pkg/controller/nodelifecycle/node_lifecycle_controller.go
@@ -62,6 +62,8 @@ import (
        taintutils "k8s.io/kubernetes/pkg/util/taints"
 )

+var controllerKind = v1.SchemeGroupVersion.WithKind("Node")
+
 func init() {
        // Register prometheus metrics
        Register()
@@ -1113,6 +1115,8 @@ func (nc *Controller) tryUpdateNodeHealth(node *v1.Node) (time.Duration, v1.Node
                if observedLease != nil && (savedLease == nil || savedLease.Spec.RenewTime.Before(observedLease.Spec.RenewTime)) {
                        nodeHealth.lease = observedLease
                        nodeHealth.probeTimestamp = nc.now()
+               } else if len(observedLease.OwnerReferences) == 0 {
+                       observedLease.OwnerReferences = []metav1.OwnerReference{*metav1.NewControllerRef(node, controllerKind)}
                }
        }
```

**Comment by wojtek-t** [comment] 2019-11-08 13:22
How does it going to help? NodeLifecycleController is currrently not updating leases (by design), so changing anything in its internal state won't change anything.

**Comment by wojtek-t** [comment] 2019-11-08 17:14
Actually, I looked deeper into the code, and generally, even if we create the Lease without OwnerReferences, in the next update we will try to update it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodelease/controller.go#L101

So the only situation when we will not try to update it is when going via the fallback path:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodelease/controller.go#L108

I'm not sure we really need to add the GC component, so the probability of it is really low
[we would have to always hit the "error path" for the whole lifetime of the kubelet]

I'm leaning towards adding a test that ensure that OwnerReferences are set and adding a condition that Lease will always be created with OwnerReferences.
I started working on that already in #84998

**Comment by wojtek-t** [comment] 2019-11-08 20:44
@shyamjvs #84998 is generally ready modulo unit test that I would like to add for it

**Comment by wojtek-t** [comment] 2019-11-14 07:26
#84998 was merged - I don't think the other part is release blocking.

**Closed** 2020-04-12 09:14 UTC
Labels: kind/bug, lifecycle/rotten, sig/scalability
