### ISSUE TITLE
ci-kubernetes-node-kubelet broken since 16:00pm PST yesterday  (03/01)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42431] opened 2017-03-02 19:13 UTC
https://k8s-testgrid.appspot.com/sq-blocking#node-kubelet
Only one green run out of the past 11 runs. 

Potential offenders:
https://github.com/kubernetes/kubernetes/compare/bce0718...5c168e2

/cc @kubernetes/sig-node-bugs 
@derekwaynecarr @smarterclayton @ncdc (saw you guys discussed this on sig-node slack)

**Comment by yujuhong** [comment] 2017-03-02 19:16
Related test failures: #42430, #42420, #42416

**Comment by vishh** [comment] 2017-03-02 19:17
@derekwaynecarr assigning this to you. @dashpole and I can help out if necessary.

**Comment by ncdc** [comment] 2017-03-02 19:19
Still not sure what's going on. In 1 downward api modification failure, I saw a pod created, container started, container killed 1 second later by the kubelet, when it's supposed to run for 120s. Very strange.

**Comment by ncdc** [comment] 2017-03-02 19:22
See e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/2316/build-log.txt:

```
I0302 06:59:04.319] [1mSTEP[0m: Creating the pod
I0302 06:59:04.319] Mar  2 14:33:03.701: INFO: Successfully updated pod "annotationupdate2359e741-ff55-11e6-bffb-42010a800018"
I0302 06:59:04.319] [AfterEach] [k8s.io] Downward API volume
I0302 06:59:04.319]   /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:126
I0302 06:59:04.319] [1mSTEP[0m: Collecting events from namespace "e2e-tests-downward-api-50f5g".
I0302 06:59:04.320] [1mSTEP[0m: Found 4 events.
I0302 06:59:04.320] Mar  2 14:35:03.704: INFO: At 2017-03-02 14:33:01 +0000 UTC - event for annotationupdate2359e741-ff55-11e6-bffb-42010a800018: {kubelet tmp-node-e2e-056c24a5-e2e-node-ubuntu-trusty-docker10-v2-image} Pulled: Container image "gcr.io/google_containers/mounttest:0.8" already present on machine
I0302 06:59:04.320] Mar  2 14:35:03.704: INFO: At 2017-03-02 14:33:01 +0000 UTC - event for annotationupdate2359e741-ff55-11e6-bffb-42010a800018: {kubelet tmp-node-e2e-056c24a5-e2e-node-ubuntu-trusty-docker10-v2-image} Created: Created container with id d028bc8c63e7395d845096bb79fa6f378e32020c0be2ed6a851ec50699404a21
I0302 06:59:04.320] Mar  2 14:35:03.704: INFO: At 2017-03-02 14:33:01 +0000 UTC - event for annotationupdate2359e741-ff55-11e6-bffb-42010a800018: {kubelet tmp-node-e2e-056c24a5-e2e-node-ubuntu-trusty-docker10-v2-image} Started: Started container with id d028bc8c63e7395d845096bb79fa6f378e32020c0be2ed6a851ec50699404a21
I0302 06:59:04.320] Mar  2 14:35:03.704: INFO: At 2017-03-02 14:33:02 +0000 UTC - event for annotationupdate2359e741-ff55-11e6-bffb-42010a800018: {kubelet tmp-node-e2e-056c24a5-e2e-node-ubuntu-trusty-docker10-v2-image} Killing: Killing container with id docker://d028bc8c63e7395d845096bb79fa6f378e32020c0be2ed6a851ec50699404a21:Need to kill Pod
```

**Comment by ncdc** [comment] 2017-03-02 19:57
So far I've only found the volume tests failing in the ubuntu trusty docker 1.10 vms. Not sure if that's 100% of them or just what I've looked at so far.

**Comment by dashpole** [comment] 2017-03-06 17:28
> Still not sure what's going on. In 1 downward api modification failure, I saw a pod created, container started, container killed 1 second later by the kubelet, when it's supposed to run for 120s. Very strange.

One idea is that cgroups are cleaned up before the pod is started, and that somehow causes the pod to fail.  See [only looking at running pods, instead of including all known pods.](https://github.com/kubernetes/kubernetes/commit/21a899cf850c4d4267cd502e69814243b7fce748#diff-10055ae93a8699af13ceba0482fc43c3L1525).  I'll try to verify my theory later...

**Comment by yujuhong** [comment] 2017-03-06 17:32
> So far I've only found the volume tests failing in the ubuntu trusty docker 1.10 vms. Not sure if that's 100% of them or just what I've looked at so far.

That's consistent with my observation. Ubuntu+docker 1.10 seems to be the only one failing. If anyone wants to try reproducing this locally, this would be the image to use.

**Comment by sjenning** [comment] 2017-03-06 17:32
@dashpole I noticed that too.  The "pod ran to completion" is "pod started and immediately exited".  I've tried to reproduce locally and can't find a commit around last Wednesday that obviously would have caused this.  I'll post any information I find here.

**Comment by ncdc** [comment] 2017-03-06 17:37
I tried to reproduce locally (not on GCE) with trusty & docker 1.10 but the tests are all passing so far. Either I didn't wait long enough or it's something specific to the GCE trusty image being used.

**Comment by derekwaynecarr** [comment] 2017-03-06 17:58
@dashpole -- i am not sure how that is possible.  the odd bit to me is we ran w/ pod cgroups on in node e2e since 1.5 if i am not mistaken.

**Comment by derekwaynecarr** [comment] 2017-03-06 18:01
@dashpole -- ignore my previous comment as previously we only deleted the cgroup when the pod was removed from the api server, and not just terminated.  so yeah, its possible something is happening here...

**Comment by derekwaynecarr** [comment] 2017-03-06 18:03
maybe we need to pass in both activePods and runningPods to get a more accurate listing?

**Comment by dashpole** [comment] 2017-03-06 18:04
@derekwaynecarr see [this kubelet log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/2318/artifacts/tmp-node-e2e-e058b1ae-gci-stable-56-9000-84-2/kubelet.log) from #42430.  Search for pod `b1261c24-ff6f-11e6-99a3-42010a80000d`, which has cgroups cleaned up within 2 seconds of starting.  May not be the culplit, but its worth looking into.

**Comment by derekwaynecarr** [comment] 2017-03-06 18:12
the runningPods cache appears like it could have a 2 second latency before updating its cache so it could be related and could be helped by passing in activePods as well...

**Comment by derekwaynecarr** [comment] 2017-03-06 18:13
see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime_cache.go#L64

**Comment by dashpole** [comment] 2017-03-06 18:16
That is possible. I am also not sure when a pod is considered running, and in what order pods are created.  Do we create cgroups before starting the container?  Would a pod be returned by GetPods (from above comment) if it had cgroups set up, but the container wasn't running yet?  

It could also simply be that we are cleaning up a pod's cgroups before it is ever running (if that is possible based on above questions).

**Comment by derekwaynecarr** [comment] 2017-03-06 18:25
@dashpole -- we create the cgroup before the container is started, so I think we need to pass activePods.

see: https://github.com/kubernetes/kubernetes/pull/42585

**Closed** 2017-03-07 06:20 UTC
Labels: kind/bug, kind/flake, priority/failing-test, priority/important-soon, sig/node
