### ISSUE TITLE
Custom column printer doesn't handle column spacing well 

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#58312] opened 2018-01-16 00:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli
/area kubectl

**What happened**:

I have a custom resource type (aggregated apiserver) that sets the openapi fields for custom columns like so:
```
NAME                    READY     REGISTERED   SHAPE            PRIVATE_IP
ad1-worker-pool-dj6p2   False     <none>       VM.Standard1.1   10.73.0.142
ad1-worker-pool-h8s89   False     <none>    VM.Standard1.1   10.73.0.141
ad1-worker-pool-ptjl8   False     <none>    VM.Standard1.1
```
As you can see, the spacig is off for REGISTERED. I figured it might be a max size issue but looking around i see some columns that are larger like the following and they're displayed nicely.

```
NAME       STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION   CONTAINER-RUNTIME
minikube   Ready     <none>    7h        v1.8.0    <none>        Buildroot 2017.02   4.9.13           docker://Unknown
``` 

**What you expected to happen**:

I expect the columns to be evenly spaced. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Create a custom resource that uses the openapi spec for displaying columns and make some columns larger in size. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nikhita** [comment] 2018-01-16 13:19
Dupe of https://github.com/kubernetes/kubernetes/pull/56629.

There is a PR open - https://github.com/kubernetes/kubernetes/issues/56282. :)

/close

**Closed by nikhita** 2018-01-16 13:19 UTC
Labels: area/kubectl, kind/bug, sig/cli
