### ISSUE TITLE
Nodeport assigned to two services on 3 Master HA Cluster

### ISSUE THREAD

**Issue by anhowe** [kubernetes/kubernetes#43233] opened 2017-03-16 17:39 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): K8S 1.5.3, and kubectl 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): xenial
- **Kernel** (e.g. `uname -a`): latest xenial
- **Install tools**:
- **Others**: ACS-Engine cluster, 3 masters

**What happened**:
Nodeport 30177 is assigned to dashboard and to the nginx service that was started within a minute of starting the dashboard.  The dashboard is being started as part of the addon manager.

**What you expected to happen**:
Each service should receive a separate node port.

**How to reproduce it** (as minimally and precisely as possible):
Run 3 master setup, with 3 API servers, 3 addon managers, 3 controllers (but one controller is elected leader).  Run dashboard as an add-on.  Create service shortly after dashboard is started an assigned nodeport.

We run a Jenkin's job, and this repros about 30-50% of the time. 

**Anything else we need to know**:
We instrumented the build and found the following:
1. Dashboard is initially created by the addon manager by issuing a POST to/api/v1/namespaces/kube-system/services.  This is where port 30177 is added, and snapshotted to etcd
2.  Immediately after the POST, another addon manager issues PATCH /api/v1/namespaces/kube-system/services/kubernetes-dashboard.  The post calls a release to 30177, and this is snapshotted to etcd.
3. Another API server receives the request for nginx and assigns 30177 to nginx service.
4. Afterwards all api servers start reporting message the node port 30177 for service nginx/namespace-15616 was assigned to multiple services.

**Workaround**: delete the nginx service, re-create the service.

@thockin have you seen this before?  This build has your latest changelist around repair.go #39206, but from best we can observe is unrelated to the changes.

**Comment by anhowe** [comment] 2017-03-16 18:25
The attached files are the API Server Logs of log server:

[26api0.txt](https://github.com/kubernetes/kubernetes/files/848646/26api0.txt)
[26api1.txt](https://github.com/kubernetes/kubernetes/files/848647/26api1.txt)
[26api2.txt](https://github.com/kubernetes/kubernetes/files/848648/26api2.txt)

Here is a timeline of events:

16:07:02.862 - 26api0.txt - Start POST /api/v1/namespaces/kube-system/services

16:07:02.863 - 26api0.txt - [Create(rest.go)

16:07:03.173 - 26api0.txt - 30177 allocated - in memory

16:07:03.255 - 26api0.txt - Create]

16:07:03.107 - 26api0.txt - bitmap.Snapshot (177),

16:07:03.256 - 26api0.txt - Finish POST /api/v1/namespaces/kube-system/services

16:07:08.474 - 26api2.txt - start patch k8s-dashboard

16:07:08.832 - 26api0.txt - 30177 released from allocator bitmap, and snapshotted to etcd

**Comment by thockin** [comment] 2017-03-16 19:19
On Thu, Mar 16, 2017 at 10:40 AM, anhowe <notifications@github.com> wrote:
>
> Is this a request for help? (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
>
> What keywords did you search in Kubernetes issues before filing this one? (If you have found any duplicates, you should instead reply there.):
>
> ________________________________
>
> Is this a BUG REPORT or FEATURE REQUEST? (choose one):
>
> Kubernetes version (use kubectl version): K8S 1.5.3, and kubectl 1.5.3
>
> Environment:
>
> Cloud provider or hardware configuration: azure
> OS (e.g. from /etc/os-release): xenial
> Kernel (e.g. uname -a): latest xenial
> Install tools:
> Others: ACS-Engine cluster, 3 masters
>
> What happened:
> Nodeport 30177 is assigned to dashboard and to the nginx service that was started within a minute of starting the dashboard. The dashboard is being started as part of the addon manager.
>
> What you expected to happen:
> Each service should receive a separate node port.
>
> How to reproduce it (as minimally and precisely as possible):
> Run 3 master setup, with 3 API servers, 3 addon managers, 3 controllers (but one controller is elected leader). Run dashboard as an add-on. Create service shortly after dashboard is started an assigned nodeport.
>
> We run a Jenkin's job, and this repros about 30-50% of the time.
>
> Anything else we need to know:
> We instrumented the build and found the following:
>
> Dashboard is initially created by the addon manager by issuing a POST to/api/v1/namespaces/kube-system/services. This is where port 30177 is added, and snapshotted to etcd

because type=NodePort ?

> Immediately after the POST, another addon manager issues PATCH /api/v1/namespaces/kube-system/services/kubernetes-dashboard. The post calls a release to 30177, and this is snapshotted to etcd.

Why is this releasing the port?  On purpose or bug?

> Another API server receives the request for nginx and assigns 30177 to nginx service.

Ports are allocated randomly from 2767 values, and you're reliably
reproducing this collision?

> Afterwards all api servers start reporting message the node port 30177 for service nginx/namespace-15616 was assigned to multiple services.

Why did they not get the update to the service that released it?

> Workaround: delete the nginx service, re-create the service.
>
> @thockin have you seen this before? This build has your latest changelist around repair.go #39206, but from best we can observe is unrelated to the changes.

Nope.  I'll try to repro.

**Comment by anhowe** [comment] 2017-03-16 20:05
1. because type=NodePort ?
Correct, the dashboard addon specifies `type=NodePort`

2. Why is this releasing the port?  On purpose or bug?
Discussed with @brendandburns and we figured it is because the addon manager does not see dynamically created `nodePort: 30177`, in the addon yaml (because it is dynamically assigned).  This points at a potential bug in the add-on manager that it should ignore the dynamically assigned values, ignoring the need for the patch.

3. Ports are allocated randomly from 2767 values, and you're reliably
reproducing this collision?
We are running Jenkins, and this repro's 30-50% of the time in the multi-master case.  The times it does not repro is when the same API server handles both the PUT of the dashboard and the nginx services, because AllocateNext() chooses the next random value for Nginx.

4. Why did they not get the update to the service that released it?
It is being released from the allocator bitmap in the registry, but not the service definition.  My guess is that it is successfully being removed from the allocator bitmap, but then when 30177 is attempted to be removed from the service it fails because the service is of type NodePort.  I need to instrument to confirm this.  If once confirmed, @brendandburns suggest I look to see if the removal from service can happen first, before removing from the allocator bitmap (nodeport should be gone from service definition, before being removed from allocator registry).  That way if removal from service fails, then allocator bitmap still keeps other services from locking it.

**Comment by brendandburns** [comment] 2017-03-16 20:39
for 3) it is the same across multiple machines, I assume it's because the random number generator has the same constant seed.

for 4) my guess is that on Service update we're doing the following:

   * M1: Update to service-1 comes in without NodePort (this is an update to an existing service)
   * M1: Allocator releases the port 30177, writes to etcd.
   * M1: Decides to re-allocate 30177 to the service-1, but _hasn't yet written to etcd_
   * M2: New service service-2 is created without NodePort
   * M2: Allocator also decides to allocate 30177 to service-2, writes it to etcd.
   * M1: Allocator fails to update etcd

At this point, both Service-1 and Service-2 have the same NodePort assigned to them.

**Comment by brendandburns** [comment] 2017-03-16 20:42
And a clarification on the Addon bits:

Addon manager has a service that looks like:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: foo
  name: foo
spec:
  ports:
  - port: 80
  selector:
    k8s-app: foo
  type: NodePort
```

But when there is a `GET` for it, it has `spec.nodePort` in the response, so add-on manager sees a difference, and posts back something missing the `nodePort` which clears and resets and starts this cycle.

**Comment by thockin** [comment] 2017-03-16 21:25
OK, I think I have found 1 bug in this path, but I can't convince myself it
would cause this failure mode, still working on it.

**Comment by thockin** [comment] 2017-03-16 21:43
On Thu, Mar 16, 2017 at 1:42 PM, Brendan Burns <notifications@github.com> wrote:
>
> And a clarification on the Addon bits:
>
> Addon manager has a service that looks like:
>
> apiVersion: v1
> kind: Service
> metadata:
>   labels:
>     k8s-app: foo
>   name: foo
> spec:
>   ports:
>   - port: 80
>   selector:
>     k8s-app: foo
>   type: NodePort
>
> But when there is a GET for it, it has spec.nodePort in the response, so add-on manager sees a difference, and posts back something missing the nodePort which clears and resets and starts this cycle.

The addon manager (the one we support, anyway - did you write your
own?) uses `kubectl apply`, so this should be fine.  The nodePort is
the same as clusterIP in this regard.

You can see it by repeatedly running `kubectl apply -f` on this and
seeing the nodePort not change.

**Comment by anhowe** [comment] 2017-03-16 21:56
The dashboard service object does not lose port 30177, it is only removed from etcd path /registry/ranges/servicenodeports.

Also, I see the same thing using `kubectl apply -f kubernetes-dashboard-service.yaml`, in that the release is happening, but when I view the dashboard service object, it still shows holding 30177.  Here's the instrumented logs:

21:50:20.7778 panics.go:76] BEGIN PATCH /api/v1/namespaces/kube-system/services/kubernetes-dashboard
21:50:20.8228 bitmap.go:128] [bitmap.Release(177),
21:50:20.8228 bitmap.go:134] bitmap.Release(177)]
21:50:20.8381 bitmap.go:205] [bitmap.Snapshot,
21:50:20.8381 bitmap.go:214] bitmap.Snapshot]
21:50:20.8389 panics.go:78] END PATCH /api/v1/namespaces/kube-system/services/kubernetes-dashboard

**Comment by thockin** [comment] 2017-03-16 22:22
Can you share this patch?

**Comment by thockin** [comment] 2017-03-16 22:31
ohh, maybe the same bug is triggering this!  God this code is twisty.

Are you game to try a patch?

in pkg/registry/core/service/rest.go, around line 435, look for

```
        for _, oldNodePort := range oldNodePorts {
               if !contains(newNodePorts, oldNodePort) {
                        continue
```

change the `!contains` to `contains` - just remove the `!`, then rebuild
and re-run?

Tim

**Comment by brendandburns** [comment] 2017-03-16 23:52
Yeah, its the standard addon manager.

We see it continuously doing a `PATCH` to the API Server.  (has `apply` moved to the server?)

**Comment by thockin** [comment] 2017-03-17 00:16
apply generates a PATCH

**Comment by thockin** [comment] 2017-03-17 00:22
On reflection all afternoon, I am pretty confident this is the bug.  I'll
send a PR, sans test probably, shortly

**Comment by thockin** [comment] 2017-03-17 00:23
https://github.com/kubernetes/kubernetes/pull/43259

**Comment by anhowe** [comment] 2017-03-17 02:15
Thanks @thockin.  I'm trying the patch and testing now.

**Comment by anhowe** [comment] 2017-03-17 03:55
Jenkins is now passing 100% on 3 master HA.  Also, logs no longer show the removal of the dashboard nodeport from registry.  I confirmed this for kubectl apply as well on the dashboard file.

Thanks for the fix!

**Comment by thockin** [comment] 2017-03-17 03:57
Thanks for the challenging bug.  It reminded me how much I hate this code :)

**Closed** 2017-03-17 05:39 UTC
