### ISSUE TITLE
Add readyReplicas to Deployments

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#28381] opened 2016-07-01 21:17 UTC
https://github.com/kubernetes/kubernetes/pull/29481 adds ReadyReplicas to Replica Sets.
https://github.com/kubernetes/kubernetes/pull/32771 adds AvailableReplicas/MinReadySeconds to ReplicaSets

We still need to add ReadyReplicas to Deployments.

**Comment by AdoHe** [comment] 2016-07-03 08:30
I like this feature :)

**Comment by bgrant0607** [comment] 2016-07-27 14:36
This is basically a dupe of #7483

**Comment by kargakis** [comment] 2016-07-31 12:53
@bgrant0607 thanks, I will be back at this in a couple of weeks.

**Comment by kargakis** [comment] 2016-08-19 14:23
@bgrant0607 updated the issue to track the api changes that still need to be done once #29481 is merged:
ReadyReplicas for Deployments
AvailableReplicas+MinReadySeconds for Replica Sets

**Comment by bgrant0607** [comment] 2016-08-19 16:34
Thanks, @kargakis

**Comment by kargakis** [comment] 2016-10-22 12:26
https://github.com/kubernetes/kubernetes/pull/32771 added AvailableReplicas+MinReadySeconds to replica sets so this basically now is ReadyReplicas for Deployments.

**Closed** 2017-01-02 12:46 UTC
Labels: area/workload-api/deployment, kind/api-change, kind/enhancement, priority/backlog, sig/apps, team/ux (deprecated - do not use)
