### ISSUE TITLE
kube-up.sh on GCE: 503 Backend Error

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#23933] opened 2016-04-06 19:25 UTC
When running kube-up.sh on GCE users have been running into the following error:

```
$ KUBERNETES_PROVIDER=gce KUBE_GCE_ZONE=us-central1-b kubernetes/cluster/kube-up.sh
Project: ***
Zone: us-central1-b
Creating gs://kubernetes-staging-a74ec99b17
Creating gs://kubernetes-staging-a74ec99b17/...
ServiceException: 503 Backend Error
```

I figured this maybe a permissions issue so I used a personal account to login to GCE from the VM I was running kube-up.sh

```
gcloud init
Welcome! This command will take you through the configuration of gcloud.

Your current configuration has been set to: [default]

Pick credentials to use:
 [1] XXXXXXXX-compute@developer.gserviceaccount.com
 [2] Log in with new credentials
Please enter your numeric choice:  2


You are running on a Google Compute Engine virtual machine.
It is recommended that you use service accounts for authentication.

You can run:

  $ gcloud config set account ``ACCOUNT''

to switch accounts if necessary.

Your credentials may be visible to others with access to this
virtual machine. Are you sure you want to authenticate with
your personal account?

Do you want to continue (Y/n)?  Y
```

Then I reran the kube-up.sh command and it seems to be working now. Maybe something up with permissions between service accounts and cloud storage?

```
$ KUBERNETES_PROVIDER=gce KUBE_GCE_ZONE=us-central1-b kubernetes/cluster/kube-up.sh
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs

All components are up to date.

All components are up to date.

All components are up to date.
... calling kube-up
Your active configuration is: [default]

Project: hightowerlabs
Zone: us-central1-b
+++ Staging server tars to Google Storage: gs://kubernetes-staging-b7de79765f/kubernetes-devel
+++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = e03c8ac3410a1638e09e54db88ec455ad90c64cc)
+++ kubernetes-salt.tar.gz uploaded (sha1 = f99e2e1615a061ce66cc2691e9d1691b7d95beee)
INSTANCE_GROUPS=
NODE_NAMES=
Looking for already existing resources
Starting master and configuring firewalls
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/zones/us-central1-b/disks/kubernetes-master-pd].
NAME                 ZONE          SIZE_GB TYPE   STATUS
kubernetes-master-pd us-central1-b 20      pd-ssd READY
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/regions/us-central1/addresses/kubernetes-master-ip].
Generating certs for alternate-names: IP:104.154.119.8,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-master
+++ Logging using Fluentd to gcp
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/global/firewalls/kubernetes-master-https].
NAME                    NETWORK SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
kubernetes-master-https default 0.0.0.0/0  tcp:443          kubernetes-master
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/zones/us-central1-b/instances/kubernetes-master].
NAME              ZONE          MACHINE_TYPE  PREEMPTIBLE INTERNAL_IP EXTERNAL_IP   STATUS
kubernetes-master us-central1-b n1-standard-1             10.240.0.7  104.154.119.8 RUNNING
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/global/firewalls/kubernetes-minion-all].
NAME                  NETWORK SRC_RANGES    RULES                    SRC_TAGS TARGET_TAGS
kubernetes-minion-all default 10.244.0.0/16 tcp,udp,icmp,esp,ah,sctp          kubernetes-minion
Creating minions.
Attempt 1 to create kubernetes-minion-template
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/global/instanceTemplates/kubernetes-minion-template].
NAME                       MACHINE_TYPE  PREEMPTIBLE CREATION_TIMESTAMP
kubernetes-minion-template n1-standard-2             2016-04-06T12:12:20.970-07:00
Created [https://www.googleapis.com/compute/v1/projects/hightowerlabs/zones/us-central1-b/instanceGroupManagers/kubernetes-minion-group].
NAME                    ZONE          BASE_INSTANCE_NAME SIZE TARGET_SIZE INSTANCE_TEMPLATE          AUTOSCALED
kubernetes-minion-group us-central1-b kubernetes-minion       3           kubernetes-minion-template
Waiting for group to become stable, current operations: creating: 3
Waiting for group to become stable, current operations: creating: 3
Waiting for group to become stable, current operations: creating: 3
Waiting for group to become stable, current operations: creating: 2
Group is stable
INSTANCE_GROUPS=kubernetes-minion-group
NODE_NAMES=kubernetes-minion-4p8j kubernetes-minion-dhom kubernetes-minion-z7fv
Using master: kubernetes-master (external IP: 104.154.119.8)
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

............Kubernetes cluster created.
cluster "hightowerlabs_kubernetes" set.
user "hightowerlabs_kubernetes" set.
context "hightowerlabs_kubernetes" set.
switched to context "hightowerlabs_kubernetes".
user "hightowerlabs_kubernetes-basic-auth" set.
Wrote config for hightowerlabs_kubernetes to /home/kelseyhightower/.kube/config

Kubernetes cluster is running.  The master is running at:

  https://104.154.119.8

The user name and password to use is located in /home/kelseyhightower/.kube/config.

... calling validate-cluster
Waiting for 4 ready nodes. 1 ready nodes, 1 registered. Retrying.
Waiting for 4 ready nodes. 1 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 1 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 1 ready nodes, 4 registered. Retrying.
Found 4 node(s).
NAME                     STATUS                     AGE
kubernetes-master        Ready,SchedulingDisabled   1m
kubernetes-minion-4p8j   Ready                      55s
kubernetes-minion-dhom   Ready                      47s
kubernetes-minion-z7fv   Ready                      56s
Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-1               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://104.154.119.8
GLBCDefaultBackend is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/default-http-backend
Heapster is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://104.154.119.8/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

**Comment by mbhinder** [comment] 2016-04-06 20:51
@kelseyhightower I ran into this as well and  filed #23926 describing a workaround:

Add the following to `$HOME/.boto`:
```
[GSUtil]
prefer_api = xml
```

**Comment by aviral26** [comment] 2016-04-06 23:14
That seems to work for me too.

(Original question : http://stackoverflow.com/questions/36415321/launching-kubernetes-multi-zone-cluster-service-unavailable-503-backend-error)

**Comment by vsimon** [comment] 2016-04-07 00:06
As one of the users hitting this issue, the workaround from @mbhinder got GCE kube-up working again.

**Comment by ixdy** [comment] 2016-04-07 21:33
@kubernetes/goog-testing this is why `kubernetes-e2e-gce-kubenet` is currently broken. I'm not sure we can easily update `$HOME/.boto` since Jenkins wipes the workspace on each run; we may just instead create the bucket as a one-off.

**Comment by JasonGiedymin** [comment] 2016-04-08 02:06
@ixdy pre run script (by hand) or have it run a script checked in aka `jenkins-e2e.sh` which creates the .boto file at $HOME for the user running jenkins?

**Comment by euank** [comment] 2016-04-08 03:20
@JasonGiedymin If you create the `.boto` file instead of using `-o "GSUtil:prefer_api=xml"` for just that command, the `upload-to-gcs.sh` script fails due to [this issue](https://github.com/GoogleCloudPlatform/gsutil/issues/351).

**Comment by quinton-hoole** [comment] 2016-04-11 21:29
Caused by gsutil bug https://github.com/GoogleCloudPlatform/gsutil/issues/348
Workaround available.  Dropping priority.

**Comment by andyzheng0831** [comment] 2016-04-13 18:00
@ixdy We added three GCE projects for our new Jenkins jobs recently, and each test hits this issue. What do we need to change to workaround it? I see PR #24012 has not been merged. cc/ @wonderfly FYI.

**Comment by freehan** [comment] 2016-04-13 21:37
@andyzheng0831 You can create the bucket manually. If the bucket exists, it won't hit the `gsutil` bug.

**Comment by andyzheng0831** [comment] 2016-04-13 22:28
@freehan Thanks, that works!

**Comment by mbhinder** [comment] 2016-06-03 05:05
https://github.com/GoogleCloudPlatform/gsutil/issues/348 has now been fixed, this can be closed.

**Closed** 2016-06-30 19:50 UTC
Labels: area/cluster-lifecycle, priority/P3, team/control-plane
