### ISSUE TITLE
Failed to collect filesystem stats, no such file or directory

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#16651] opened 2015-11-02 01:43 UTC
Running into this on my AWS cluster. Seems to happen every ~10 seconds.

```
Nov 02 01:42:57 ip-172-20-0-49 kubelet[13540]: I1102 01:42:57.265901   13540 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/b3f6e3297e2821bf03f6b22f4858d6c92f2187032eed873a3430ac36f2d5a5b5 with output du: cannot access ‘/var/lib/docker/aufs/diff/b3f6e3297e2821bf03f6b22f4858d6c92f2187032eed873a3430ac36f2d5a5b5’: No such file or directory
```

Perhaps it's trying to check something that was deleted? It should probably handle this and stop trying to check after it discovers the diff has been deleted.

**Comment by mikedanese** [comment] 2015-11-02 04:16
cc @vishh

**Comment by vishh** [comment] 2015-11-02 18:01
What version of kubernetes are you using?
Kubelet (cadvisor actually) detects dead containers and stops monitoring
them right away.
I wonder if docker storage driver is being detected incorrectly, or it
probably change underneath kubelet.

**Comment by paralin** [comment] 2015-11-02 18:44
@vishh I think it should detect both dead containers and containers that have been removed manually by the user.  Maybe it does this already?

On my server I did shut down all the daemons, resize the docker partition, and remake the simlink to it. Could this cause it?

**Comment by vishh** [comment] 2015-11-02 19:00
> @vishh <https://github.com/vishh> I think it should detect both dead
containers and containers that have been removed manually by the user.
Maybe it does this already?

cAdvisor relies on kernel APIs to identify container exit. So I doubt that
container exit could have caused this issue.

> On my server I did shut down all the daemons, resize the docker
partition, and remake the simlink to it. Could this cause it?

Possibly. Can you try re-starting the kubelet and see if this problem
dis-appears?

On Mon, Nov 2, 2015 at 10:45 AM, Christian Stewart <notifications@github.com

**Comment by paralin** [comment] 2015-11-04 22:13
@vishh This is now actually causing one of my nodes to not even work anymore.

```
Nov 04 22:12:33 ip-172-20-0-49 kubelet[18538]: I1104 22:12:33.479109   18538 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/7f16c83553068f99e1d0871eda1667bd158a09bd5fa59fd4be329374ca1057ac with output du: cannot access ‘/var/lib/docker/aufs/diff/7f16c83553068f99e1d0871eda1667bd158a09bd5fa59fd4be329374ca1057ac’: No such file or directory
Nov 04 22:12:33 ip-172-20-0-49 kubelet[18538]: - exit status 1
```

I've just updated to `HEAD` and this is even after a reboot.

**Comment by paralin** [comment] 2015-11-04 22:14
@vishh Okay, just rebuilt and updated again, after a reboot the issue seems to be gone. However, it's crashing the entire kubelet when the problem happens. Seems like a pretty critical issue to me.

**Comment by vishh** [comment] 2015-11-04 22:15
@paralin: I don't get how this error can cause your node to fail. This is an informational log message and does not affect stability.

**Comment by paralin** [comment] 2015-11-04 22:15
@vishh I don't really understand either, but it exits with status 1 right after printing the error.

It's fixed now but might be worth looking into I guess.

**Comment by vishh** [comment] 2015-11-04 22:16
It should not crash the kubelet. How did you conclude that this log is the
reason for kubelet crash?

**Comment by paralin** [comment] 2015-11-04 22:16
@vishh Approximately 4 times a second it would print these two lines to `journalctl -f`:

```
Nov 04 22:12:33 ip-172-20-0-49 kubelet[18538]: I1104 22:12:33.479109   18538 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/7f16c83553068f99e1d0871eda1667bd158a09bd5fa59fd4be329374ca1057ac with output du: cannot access ‘/var/lib/docker/aufs/diff/7f16c83553068f99e1d0871eda1667bd158a09bd5fa59fd4be329374ca1057ac’: No such file or directory
Nov 04 22:12:33 ip-172-20-0-49 kubelet[18538]: - exit status 1
```

**Comment by vishh** [comment] 2015-11-04 22:17
Check the kernel logs `dmesg`. I suspect some other issue in your case that
is causing the kubelet to exit.

**Comment by paralin** [comment] 2015-11-04 22:18
@vishh Unfortunately I don't have the kernel logs from the crash now that it's operating properly & several reboots... Whoops. 

We can close this, if I see the problem again I'll re-open. A bit concerning though.

**Comment by vishh** [comment] 2015-11-04 22:18
That is definitely undesirable. I will suppress those logs.

**Comment by paralin** [comment] 2015-11-04 22:19
@vishh Well one thing to do is investigate why it's actually attempting to `du` something that doesn't exist so many times. Suppressing the logs is a temporary fix I guess, but perhaps catch this situation and do something about it?

**Comment by vishh** [comment] 2015-11-04 22:19
Kubelet crash is indeed serious. So the next time this happens, collect
kernel logs as well, if possible. I'm fine with closing this issue for now.

**Comment by paralin** [comment] 2015-11-05 01:18
@vishh Happening again, on the latest HEAD.

**dmesg**

```
[183765.238486] aufs au_opts_verify:1612:docker[24243]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.245270] aufs au_opts_verify:1612:docker[24243]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.250771] aufs au_opts_verify:1612:docker[24243]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.252881] aufs au_opts_verify:1612:docker[24290]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.265120] aufs au_opts_verify:1612:docker[24228]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.280687] aufs au_opts_verify:1612:docker[24228]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.350412] aufs au_opts_verify:1612:docker[24312]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.356915] aufs au_opts_verify:1612:docker[24312]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.361700] aufs au_opts_verify:1612:docker[24312]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.363749] aufs au_opts_verify:1612:docker[24315]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.369042] aufs au_opts_verify:1612:docker[24315]: dirperm1 breaks the protection by the permission bits on the lower branch
[183765.393731] aufs au_opts_verify:1612:docker[24313]: dirperm1 breaks the protection by the permission bits on the lower branch
[183773.408098] cbr0: port 1(veth00e74b0) entered forwarding state
```

**Comment by paralin** [comment] 2015-11-05 01:21
I think this is unrelated, ugh. Nothing else in dmesg looks useful.

**Comment by paralin** [comment] 2015-11-05 01:21
@vishh 

More of this:

```
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: I1105 01:21:06.110818   22566 manager.go:2052] Back-off 5m0s restarting failed container=kube-controller-manager pod=kube-controller-manager-ip-172-20-0-9.us-west-2.compute.internal_kube-system
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: E1105 01:21:06.111208   22566 pod_workers.go:125] Error syncing pod 990e24f2bf627392e309a2a08f78bcc5, skipping: not all containers have started: 0 != map[0:{}]
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: I1105 01:21:06.301322   22566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/11d7af1f8a31989ab94fd05263a5f1f9dc6be8399a4490cb8bc8847b4cc8c620 with output du: cannot access ‘/var/lib/docker/aufs/diff/11d7af1f8a31989ab94fd05263a5f1f9dc6be8399a4490cb8bc8847b4cc8c620’: No such file or directory
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: - exit status 1
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: I1105 01:21:06.377843   22566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/fbcf696a8e1087771b4eefb65999cf36664b8c086e357a3d2db90d16259c0bc8 with output du: cannot access ‘/var/lib/docker/aufs/diff/fbcf696a8e1087771b4eefb65999cf36664b8c086e357a3d2db90d16259c0bc8’: No such file or directory
Nov 05 01:21:06 ip-172-20-0-9 kubelet[22566]: - exit status 1
Nov 05 01:21:11 ip-172-20-0-9 kernel: cbr0: port 1(veth730ae7d) entered forwarding state
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: I1105 01:21:17.122039   22566 manager.go:2052] Back-off 5m0s restarting failed container=kube-controller-manager pod=kube-controller-manager-ip-172-20-0-9.us-west-2.compute.internal_kube-system
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: E1105 01:21:17.122084   22566 pod_workers.go:125] Error syncing pod 990e24f2bf627392e309a2a08f78bcc5, skipping: not all containers have started: 0 != map[0:{}]
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: I1105 01:21:17.327907   22566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/2c538f3db3b56c62316a3338a59bb445e53db8dbae6bfe03a96288758140ec8b with output du: cannot access ‘/var/lib/docker/aufs/diff/2c538f3db3b56c62316a3338a59bb445e53db8dbae6bfe03a96288758140ec8b’: No such file or directory
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: - exit status 1
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: I1105 01:21:17.379895   22566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/1e4f4495d363591bf5e19eed15c84e4b6b9f524d6f7e6cf28f0aba62b46d5515 with output du: cannot access ‘/var/lib/docker/aufs/diff/1e4f4495d363591bf5e19eed15c84e4b6b9f524d6f7e6cf28f0aba62b46d5515’: No such file or directory
Nov 05 01:21:17 ip-172-20-0-9 kubelet[22566]: - exit status 1

```

**Comment by paralin** [comment] 2015-11-05 01:26
Fixed now by rebooting the system. Something weird happening though. I don't like the `kubelet[22566]: - exit status 1` message - is it kubelet dying? Or is it something kubelet started that's dying?

**Comment by vishh** [comment] 2015-11-05 18:16
cc @kubernetes/goog-node

**Comment by dchen1107** [comment] 2015-11-05 18:27
`kubelet[22566]: - exit status 1` message is bad, but should be a red herring. That exit code is from running command du and failed.

Also from https://github.com/kubernetes/kubernetes/issues/16651#issuecomment-153923597, kubelet doesn't crash. I don't know why kubelet crash in your cases though. Can you check journald logs about your kubelet service?

**Comment by frosenberg** [comment] 2015-11-10 08:44
I see the same messages in `syslog` but in a slightly different context: some of my containers fail due to some aufs issue:

```
Nov 10 08:40:50 ip-172-20-0-229 docker[7746]: time="2015-11-10T08:40:50.902082479Z" level=error msg="Couldn't run auplink before unmount: exit status 22"
Nov 10 08:40:50 ip-172-20-0-229 docker[7746]: time="2015-11-10T08:40:50.902176826Z" level=error msg="Handler for POST /containers/create returned error: error creating aufs mount to /mnt/ephemeral/docker/aufs/mnt/310474b558db33f0c4b2f71ae722ff9492ec9f4e29f7abc6fc1a3c692919df03-init: invalid argument"
Nov 10 08:40:50 ip-172-20-0-229 docker[7746]: time="2015-11-10T08:40:50.902248853Z" level=error msg="HTTP Error" err="error creating aufs mount to /mnt/ephemeral/docker/aufs/mnt/310474b558db33f0c4b2f71ae722ff9492ec9f4e29f7abc6fc1a3c692919df03-init: invalid argument" statusCode=500
```

At a later point I see the following (repeating):
```
Nov 10 08:41:24 ip-172-20-0-229 kubelet[7481]: I1110 08:41:24.221143    7481 fsHandler.go:87] failed to collect filesystem stats - du command failed on /mnt/ephemeral/docker/aufs/diff/4e447299440662d1e1baffb3654c3084b4b201654293eb72be40b3a553f0339d with output du: cannot access '/mnt/ephemeral/docker/aufs/diff/4e447299440662d1e1baffb3654c3084b4b201654293eb72be40b3a553f0339d': No such file or directory
```

This is a brand new install of 1.2.0-alpha.2 (also tried beta 1.1.1 and 1.0.7 it is the same).

**Comment by paralin** [comment] 2015-11-21 03:46
@vishh @kubernetes/goog-node  @mikedanese 

This is again getting spammed in the logs on my kubernetes cluster (running on HEAD).

```
failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/d200fe38c9d6620297037dc20ea8b033bca402abf25eb313865a2f1efccd2b74 with output du: cannot access `/var/lib/docker/aufs/diff/d200fe38c9d6620297037dc20ea8b033bca402abf25eb313865a2f1efccd2b74': No such file or directory
```

On every one of the nodes.

**Comment by HardySimpson** [comment] 2015-11-24 06:44
Also see this log

```
I1124 14:31:54.546529   23947 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/b1800f3df9d19230b84c0c6b5004b4e30e
cf18204c8bf771e44b86abafb0e637 with output du: cannot access '/var/lib/docker/aufs/diff/b1800f3df9d19230b84c0c6b5004b4e30ecf18204c8bf771e44b86abafb0e637': No such fi
le or directory
 - exit status 1
I1124 14:31:54.801438   23947 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/9ff3456a350aef4cc7a62b7804621072d9
0ba94db1d55f0d0fde13c8e250a554 with output du: cannot access '/var/lib/docker/aufs/diff/9ff3456a350aef4cc7a62b7804621072d90ba94db1d55f0d0fde13c8e250a554': No such fi
le or directory
 - exit status 1
I1124 14:31:54.801507   23947 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/2f4ff28ac1d5ab9111deb5db4b2bcc0dd3
71203ee938e0f60e999ef77347bcfe with output du: cannot access '/var/lib/docker/aufs/diff/2f4ff28ac1d5ab9111deb5db4b2bcc0dd371203ee938e0f60e999ef77347bcfe': No such fi
le or directory
 - exit status 1
```

kubelet version 1.1.1

I am doing a 100 pod / node test (e2e.test) and see this log.

And, the kubelet cost about 70% of CPU and cause container can not be created

```
root@node-118:/var/log# ps -ef | grep kubelet
root     12742  3171  0 14:44 pts/4    00:00:00 grep --color=auto kubelet
root     23947     1 40 10:27 ?        01:44:38 /usr/local/bin/kubelet --api-servers=https://33.1.3.72 --enable-debugging-handlers=true --hostname-override=33.1.1.196 --config=/etc/kubernetes/manifests --allow-privileged=True --v=2 --cluster-dns=10.247.3.10 --cluster-domain=cluster.local --cgroup-root=/ --system-container=/system --max-pods=200
```

**Comment by yujuhong** [comment] 2015-11-24 16:23
@HardySimpson 100 pods per node is not supported in v1.1.1. High cpu usage from kubelet is expected and I am not sure if the failed `du` commands are related to the usage. I am curious about why the container could not be created though.

On the other hand, I've also seen error messages like this in my test cluster. Re-labeled this issues as kind/bug.

**Comment by HardySimpson** [comment] 2015-11-25 08:03
This problem is caused by docker, as far as we know now. the docker didn't cleanup all things in /sys/fs/cgroup, and cadvisor seek them and goto /var/lib/....

anyway, why do you say 100 pods per node is not support at 1.1.1? as we know, the high useage of kubelet is mainly caused by cadvisor, it do more than 1.0.6.

**Comment by yujuhong** [comment] 2015-11-25 16:18
> This problem is caused by docker, as far as we know now. the docker didn't cleanup all things in /sys/fs/cgroup, and cadvisor seek them and goto /var/lib/....

That sounds plausible. Do you know what was left behind in /sys/fs/cgroup?

> anyway, why do you say 100 pods per node is not support at 1.1.1? as we know, the high useage of kubelet is mainly caused by cadvisor, it do more than 1.0.6.

By default, the max number of pods (--max-pods) is set to 40 in kubelet in v1.1.1. There are known  kubelet and docker cpu usage issues due to polling, and we're working on improving them for v1.2. cadvisor should not be causing high cpu usage though. Is there any indication (pprof) in your cluster that cadvisor is the culprit? Do you see high docker cpu usage as well?

**Comment by magicwang-cn** [comment] 2015-11-26 01:49
@yujuhong @HardySimpson 
i think there are two reasons about the high cpu usage(v1.1.1 version):
1. cadvisor itself, of course, when the node In idle state, the cadvisor works just fine, once the node in full load(there are many pods), the cadvisor will take up a lot of resources, you can see [the code](https://github.com/kubernetes/kubernetes/blob/release-1.1/Godeps/_workspace/src/github.com/google/cadvisor/container/libcontainer/helpers.go#L82)
as the pprof graph:
![cadvisor_cpu_1](https://cloud.githubusercontent.com/assets/7587313/11413288/64944d30-9422-11e5-917f-20d0e9bd0f15.png)
![cadvisor_cpu_2](https://cloud.githubusercontent.com/assets/7587313/11413290/678cd246-9422-11e5-910a-bfcb30ad556a.png)

2. docker or kubelet has not clear resources which related to pods thoroughly(cgroup resources, mount point and network .etcd), of course, in the normal state, it will not reach this problem(we just find this problem in the density test):
![cgroup](https://cloud.githubusercontent.com/assets/7587313/11413330/d96df070-9422-11e5-8187-e57087d6626f.png)

![network](https://cloud.githubusercontent.com/assets/7587313/11413335/dfdb87c4-9422-11e5-804d-d067085be314.png)

**Comment by yujuhong** [comment] 2015-12-02 18:15
@magicwang-cn, we are looking into increasing the housekeeping interval for cadvisor, which will reduce the cpu usage (#18044).

> docker or kubelet has not clear resources which related to pods thoroughly(cgroup resources, mount point and network .etcd), of course, in the normal state, it will not reach this problem(we just find this problem in the density test)

I think this might be the main cause. If kubelet/docker keeps leaking resources, it'd increase the workload of cadvisor. I've also seen `No such file or directory` errors in kubelet.log from different clusters. Do you have an example of the leakage? Thanks!

/cc @kubernetes/goog-node

**Comment by yujuhong** [comment] 2015-12-04 18:40
cadvisor leaks goroutines. For every container, cadvisor creates a file system handler to track disk usage. This handler launches a goroutine but the goroutine was never terminated even after the container dies.

After repeatedly creating and deleting pods, kubelet has over 1391 such fsHandler goroutines.

```
1391 @ 0x416b95 0x418e3c 0x4182d2 0x126733f 0x4402c1
#	0x126733f	github.com/google/cadvisor/container/docker.(*realFsHandler).trackUsage+0x3ff	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/google/cadvisor/container/docker/fsHandler.go:81
```

/cc @vishh @dchen1107

**Comment by dchen1107** [comment] 2015-12-04 18:50
@vishh I am assigning this one to you for triage. cc/ @jimmidyson 

I thought the initial issue of being failed to collect filesystem stats was fixed in cadvisor and included for 1.1 release already. Maybe we didn't clean the goroutine here?

**Comment by jimmidyson** [comment] 2015-12-04 19:01
Guessing this is https://github.com/google/cadvisor/issues/994

Cadvisor needs a whole lot of love tbh. I've tidied up a bit without some pretty major changes, but it may be time for a total review.

**Comment by vishh** [comment] 2015-12-04 19:01
I'm working on a fix.

**Comment by dchen1107** [comment] 2015-12-04 19:06
This is third time we found cAdvisor leaking goroutine, another one is  https://github.com/kubernetes/kubernetes/issues/15805. We should add a node test to avoid this.

**Comment by yujuhong** [comment] 2015-12-04 19:24
I ran 10 tests overnight with each test creating 40 pods and cleaning up afterwards. The increased in cpu usage is already visible.  I imagine the soak cluster has accumulated a huge number of deleted containers that would slow down kubelet tremendously, leading to failing tests (#17608). I just ssh'd in to one node in the soak cluster, and the most recent kubelet.log file contains 3546 unique `du` failures .

**Comment by jimmidyson** [comment] 2015-12-04 20:03
I voiced my concerns over the du check last time we discussed it. It's intensive both in terms of CPU & io even if you ignore this leak. I think we need the option to disable this check & default to disabled.

**Comment by vishh** [comment] 2015-12-04 20:10
If you look at #16889, `du` should be deprecated with a filesystem specific
tool like quota or dmtables, etc. As of now `du` is the only means to
understand how the primary storage device is being utilized across
containers.
How would a user handle a situation where one of the pods fills up the disk
due to excessive logging? Are we going to expect them to drain the entire
node, free up disk and then add the node back in?

**Closed** 2015-12-04 20:52 UTC
Labels: area/cadvisor, cherrypick-candidate, kind/bug, priority/P0, team/node
