### ISSUE TITLE
kubernetes/test/integration/garbagecollector/garbage_collector_test.go is flaky

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59585] opened 2018-02-08 19:16 UTC
This flaked 11/66 times in the last week.

/priority failing-test
/priority important-soon
/sig api-machinery
/kind flake

Please correct sig if assigned inaccurately.

**Comment by mithrav** [comment] 2018-02-08 20:19
@kubernetes/sig-api-machinery-test-failures

**Comment by yue9944882** [comment] 2018-02-11 15:22
note that it is `TestCascadingDeletion` is failing

**Comment by mithrav** [comment] 2018-02-16 23:55
Pinging for status

**Comment by cblecker** [comment] 2018-02-23 19:16
Closing as dupe of #59426

**Closed by cblecker** 2018-02-23 19:16 UTC
Labels: kind/flake, priority/failing-test, priority/important-soon, sig/api-machinery
