### ISSUE TITLE
[flaky] SchedulingThroughput - SchedulingThroughput error: scheduler throughput: actual throughput 81.200000 lower than threshold 90.000000]

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93217] opened 2020-07-19 04:22 UTC
**Which jobs are flaking**:

* ci-kubernetes-e2e-gci-gce-scalability
* ci-kubernetes-e2e-gci-gce-scalability-networkpolicies
* pull-kubernetes-e2e-gce-100-performance

**Which test(s) are flaking**:

```
testing/density/config.yaml

SchedulingThroughput error: scheduler throughput: actual throughput 81.800000 lower than threshold 90.000000]
```

**Testgrid link**:

* https://testgrid.k8s.io/google-gce#gce-cos-master-scalability-100&width=5
* https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-100-performance&width=5

**Anything else we need to know**:

Looking just at periodic jobs (not presubmit), the number of failures has been steadily rising since May:
* 3: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-05-30&text=scheduler%20throughput
* 6: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-06-06&text=scheduler%20throughput
* 11: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-06-13&text=scheduler%20throughput
* 16: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-06-20&text=scheduler%20throughput
* 19: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-06-27&text=scheduler%20throughput
* 26: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-07-04&text=scheduler%20throughput
* 34: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-07-11&text=scheduler%20throughput
* 65: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-07-18&text=scheduler%20throughput

/sig scalability
/sig scheduling

**Comment by liggitt** [comment] 2020-07-19 04:22
moving into the milestone for investigation

@kubernetes/sig-scalability-bugs @kubernetes/sig-scheduling-bugs

**Comment by justaugustus** [comment] 2020-07-19 05:16
FYI @kubernetes/ci-signal

**Comment by ahg-g** [comment] 2020-07-21 20:03
looking at few "failed" runs, the binding latency is the main culprit.

Example failed runs:
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1284880208997912581/artifacts/SchedulingMetrics_density_2020-07-19T16:18:04Z.json
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1285450313486045184/artifacts/SchedulingMetrics_density_2020-07-21T06:02:17Z.json
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1285501400658219009/artifacts/SchedulingMetrics_density_2020-07-21T09:26:22Z.json

 "e2eSchedulingLatency": {
    "Perc50": 145929078,
    "Perc90": 569616710,
    "Perc99": 991796135
  },
  "schedulingLatency": {
    "Perc50": 10867635,
    "Perc90": 28716736,
    "Perc99": 62374972
  }

Example successful runs:
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1285319199748526081/artifacts/SchedulingMetrics_density_2020-07-20T21:22:17Z.json 
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1285593005411012609/artifacts/SchedulingMetrics_density_2020-07-21T15:29:33Z.json

example:
 "e2eSchedulingLatency": {
    "Perc50": 66395939,
    "Perc90": 273240816,
    "Perc99": 508947405
  },
  "schedulingLatency": {
    "Perc50": 10146718,
    "Perc90": 27175497,
    "Perc99": 60826666
  }


e2eSchedulingLatency (schedulingLatency + binding) includes the binding overhead which is the time to update `pod.Spec.NodeName`, schedulingLatency is the time the scheduler spent evaluating the pod.

From the above, it seems that binding is the main factor causing this test to fail. Do we know if there are any performance regressions on the api server side related to updates?

**Comment by liggitt** [comment] 2020-07-21 20:58
> Do we know if there are any performance regressions on the api server side related to updates?

Not that I'm aware of. If I'm reading http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=APIServer&metricname=DensityResponsiveness_PrometheusSimple&Resource=pods&Scope=namespace&Subresource=binding&Verb=POST, the performance of posts to pods/binding looks pretty stable over time

**Comment by liggitt** [comment] 2020-07-21 21:15
/assign @wojtek-t @ahg-g 
for scalability / scheduling

@wojtek-t, can you verify my interpretation of https://github.com/kubernetes/kubernetes/issues/93217#issuecomment-662102921 ?

**Comment by wojtek-t** [comment] 2020-07-22 05:48
Agree - the post bindings didn't seem to change.

As scalability oncall:
/assign @tosi3k

**Comment by wojtek-t** [comment] 2020-07-22 06:52
Didn't yet look deeper into it, but binding latency shouldn't matter that much for throughput.
POST binding calls done by scheduler are asynchronous (i.e. they don't block scheduling the next pod), so that shouldn't influence this...

At this point, I also wouldn't exclude the fact that the SchedulingThroughput measurement is actually faulty (and it's a test issue not system issue)? We know that the current implemention has problems (e.g. https://github.com/kubernetes/perf-tests/issues/1027). Given the throughput is computed by the test, it's also possible that the cpu-starved test would result in lower numbers than they actually are.

Looking into perf-dash for throughput, it doesn't look very suspicious:
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=Scheduler&metricname=SchedulingThroughput

The first thing we should do is to actually exclude it's not a test issue (e.g. check in kube-apiserver logs that our logs really reflect API requests).

**Comment by liggitt** [comment] 2020-07-22 07:00
> Given the throughput is computed by the test, it's also possible that the cpu-starved test would result in lower numbers than they actually are.

Speaking of that, I just noticed today that the job doesn't request CPU for the test pod, so it can easily be starved. We noticed it was getting assigned the default request of 250m in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93307/pull-kubernetes-e2e-gce-100-performance/1285712793332355072/ (see podinfo.json in the artifacts). 

Shouldn't the perf test be requesting a specific amount of CPU for its test pod (and maybe even limiting to that amount to make results over time comparable)?

**Comment by wojtek-t** [comment] 2020-07-22 07:11
> Shouldn't the perf test be requesting a specific amount of CPU for its test pod (and maybe even limiting to that amount to make results over time comparable)?

Great catch - it absolutely should.
@tosi3k - can you please fix that for all 100-node jobs (5k jobs are setting requests at least though I agree that we should also be setting limits).

**Comment by tosi3k** [comment] 2020-07-22 09:23
I'm currently running some test jobs to investigate a sufficient CPU amount for our 100 nodes tests and will come back here with results when they finish.

**Comment by ahg-g** [comment] 2020-07-22 10:43
May be not the POST call itself that is taking longer, but that latency could be an indicator of some sort of throttling happening client-side.

**Comment by wojtek-t** [comment] 2020-07-22 10:49
I took a look into one random failure:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1282296675364245504

And while the test is lagging compare to kube-apiserver a bit (this may also be just watch latency too), this doesn't really change much.
We're computing scheduling throughput based on saturation pods.
First saturation pod was binded at:
```
I0712 13:04:37.142471      10 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/namespaces/test-1nynon-1/pods/saturation-deployment-0-7d4967d89d-76pdx/binding" lat     ency="23.142804ms" userAgent="kube-scheduler/v1.20.0 (linux/amd64) kubernetes/a2978e3/scheduler" srcIP="[::1]:43384" resp=201
```
Last saturation pod was binded at:
```
I0712 13:05:16.268957      10 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/namespaces/test-1nynon-1/pods/saturation-deployment-0-7d4967d89d-w22zq/binding" lat     ency="37.143049ms" userAgent="kube-scheduler/v1.20.0 (linux/amd64) kubernetes/a2978e3/scheduler" srcIP="[::1]:43384" resp=201
```

There were 3000 saturation pods, scheduled over ~39s, which gives avg scheduling throughput of:
3000pods/39s = ~77pods/s

To give more statistics, the time of n-th binding (based on kube-apiserver logs):
1:        13:04:37.142471
500:    13:04:42.714681
1000:  13:04:48.454814
1500:  13:04:54.183540
2000:  13:05:00.885061
2500:  13:05:08.461613
3000:  13:05:16.268957

And I just realized that we're failing the test on "highest throughput" (meaning we take the 5s when the most pods were scheduled). So best 5s had throughput of 87pods/s. Based on kube-apiserver logs, it seem to be roughly the same.

So the problem does NOT seem to be connected to cpu-starved test.

**Comment by wojtek-t** [comment] 2020-07-22 10:51
> May be not the POST call itself that is taking longer, but that latency could be an indicator of some sort of throttling happening client-side.

IIUC scheduler has qps limit set to 100. Are there any other calls that scheduler was doing at that time that could affect it?
Actually let me take a look at my run.

**Comment by wojtek-t** [comment] 2020-07-22 10:55
Just checked that run and I only see "leader election heartbeats" and post events. So nothing suspicious (BTW only 709 pod events at that time, which is a bit strange).

So I don't yet see anything that could be leading to throttling client-side.

BTW @ahg-g - can you confirm that binding is still happening asynchronously as it was happening in the past?

**Comment by ahg-g** [comment] 2020-07-22 10:59
Yes, it is still happening asynchronously.

**Comment by wojtek-t** [comment] 2020-07-22 11:04
Hmm - actually looking into numbers from that run:
```
  "e2eSchedulingLatency": {
    "Perc50": 90989898,
    "Perc90": 337779551,
    "Perc99": 793665641
  },
  "schedulingLatency": {
    "Perc50": 9677008,
    "Perc90": 26566183,
    "Perc99": 59293658
  }
```

It shows that 50th percentile of scheduling latency take 9.6ms. So with that number, we're actually really close to teoretical boundary of 100pods/s. Maybe I'm wrong, but I think low percentiles aren't much lower than 50th one, so I actually think that binding latency is actually a red herring (given it's also asynchronous).

**Comment by ahg-g** [comment] 2020-07-22 11:19
oh, we recently fixed a bug (https://github.com/kubernetes/kubernetes/pull/92840) in 1.19 that should increase Score latency (the bug exist in 1.18 as well but the patch isn't merged yet https://github.com/kubernetes/kubernetes/pull/93026).

Did this SchedulingThroughput test run before 1.18? the reason I am asking is because the overhead added by the fix is not new, it was there in versions 1.17 and below.

**Comment by wojtek-t** [comment] 2020-07-22 11:28
But that has merged 10 days ago, and it's still the same.

**Comment by wojtek-t** [comment] 2020-07-22 11:42
Ironically - we observe 100pods/s throughput even on low percentiles in 5k-node tests. So it's really smaller-scale related thing.

To check: isn't the master itself cpu-throttled at 100-node scale?

**Comment by ahg-g** [comment] 2020-07-22 11:46
Yes, it is certainly only at small scale, we (sig-scheduling) closely monitor the 5k benchmarks, for those the scheduling latency (without binding) at 50th percentile is just ~3ms, while for 100 nodes it is roughly 9ms as you noted (which is due to master size being smaller)

**Comment by wojtek-t** [comment] 2020-07-22 11:46
@ahg-g - looking into cpu usage graph:
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=DensityResources&PodName=kube-scheduler-e2e-big-master%2Fkube-scheduler&Resource=CPU

there seem to be clear increase in scheduler CPU usage around July 12th. Is it because of the fix you mentioned above?

**Comment by wojtek-t** [comment] 2020-07-22 11:52
FTR: this isn't a problem for 500-node kubemark too:
http://perf-dash.k8s.io/#/?jobname=kubemark-500Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput

We need to look into grafana dashboards for those run, but my suspicion is that we're cpu-starved occassionally (99th percentiles of CPU usage of components sum up to more than machine size, and I actually would expect them to be correlated to some extent).
@tosi3k - can you please pick a random failure and look into grafana dashboards to see how the CPU usage looks like there?

@jkaniuk - FYI

**Comment by wojtek-t** [comment] 2020-07-22 12:19
To given an update with my offline discussion with @ahg-g 

@ahg-g pointed me at this graph:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=kube-scheduler-gce-scale-cluster-master%2Fkube-scheduler&Resource=CPU

it is for 5k-node tests, but clearly around May 15th something happened that increased scheduler CPU usage.
There is no reason to believe this didn't affect 100-node test too.

@ahg-g is already looking over PRs from around that time, but so far we don't have clear victim. Couple PRs he mentioned are:
- https://github.com/kubernetes/kubernetes/pull/91084
- https://github.com/kubernetes/kubernetes/pull/91062
- [context: we introduced pod anti-affinity to kubedns couple days before: https://github.com/kubernetes/kubernetes/pull/90248]
- https://github.com/kubernetes/kubernetes/pull/90978 [though it shouldn only affect unschedulable pods]

**Comment by wojtek-t** [comment] 2020-07-22 12:21
and there is a second bump in that graph on July 12th which correlates with #92840 and @ahg-g mentioned above too

**Comment by ahg-g** [comment] 2020-07-22 12:51
The first bump is not expected, the second one is expected.

The issues #91084 and  #91062 are not expected to increase cpu overhead, so I will look at cpu profiles.

**Comment by ahg-g** [comment] 2020-07-22 13:16
> though it should only affect unschedulable pods - which we don't have

Looking at the scheduler logs, I can confirm that there are only 186 pods that failed to schedule (out of ~14839 pods). Those 186 pods were statefulset pods waiting for volume binding, so #90978 is unlikely to impact this test.

**Comment by ahg-g** [comment] 2020-07-22 15:13
Did the number of volumes or pods requesting volumes used in the test increase?

**Comment by ahg-g** [comment] 2020-07-22 16:55
†he profiles shows there is an increase in the overhead of `VolumeRestrictions` Filter (increased from 5% to 10%), but I am not really sure it explains the increase in cpu utilization. The code of that filter didn't change, hence my suspicion that this was a result of an increase in number pods with volumes in the test.

**Comment by jkaniuk** [comment] 2020-07-22 18:15
I do not see anything interesting happening to our test configs around 15th of May. Or 12th of June for that matter.

**Comment by wojtek-t** [comment] 2020-07-22 18:46
Can we temporarily bump master size to 8-core one maybe? And see how it will affect the results?

That would allow us to confirm/reject the hypothesis about lack of master resources being the root cause of the problem.  Once we're sure about the root cause, we can decide if/what should be optimized.

**Comment by wojtek-t** [comment] 2020-07-23 14:36
To give a short update:
- we're run experiments to run tests with 8-core masters (instead of 4-core) and they were waaay better; so I think we already know it's related to cpu-starvation on the master (short spikes)
- @tosi3k and @jkaniuk were trying to dig deeper into what is happening but apperently (except from #92840 which we know that increase resource usage and is expected and can be revert because it's bug fix) we don't have other victims

Given our tests are increasing qps limits to 100 (with default being 20) [to speed up tests] I wouldn't perceive it as a release blocker @kubernetes/ci-signal  ^^

We will continue to have the issue open until we figure out the best option to fix the flakiness. Options on the table:
- continue debugging to find other vicitims (we're not sure it was visibly better in the past though)
- reduce qps for 100-node tests
- stop failing tests on throughput in 100-node tests (just stick to 5k-node tests where we don't have those problems)
- increase master size fo 100-node tests
- ...

**Comment by liggitt** [comment] 2020-07-23 14:41
> * stop failing tests on throughput in 100-node tests (just stick to 5k-node tests where we don't have those problems)

if we have visibility to the metric in regular post-submits that we pay attention to, that seems reasonable

> * increase master size fo 100-node tests

I wouldn't recommend this for a presubmit that runs on every PR just to deflake this one metric

**Comment by wojtek-t** [comment] 2020-07-24 14:22
OK - so we spend some more time looking into this issue and:
- the biggest victim is #92840 (and conitrbuted most to the flakiness) - this is bug fix we can't really do much about
- there aren't any other obvious victims at any time - rather organic increase

Given:
- I'm 100% it's cpu-starvation of the master
- the fact that we explicitly bump qps limits comparing to defaults (so it's not official configuration) in this test
- we have coverage of scheduling throughput in 500-node kubemark and 5k-node clusters (where numbers are fine)
we decided to:
- get rid of throughput validation in 100-node tests (and rely on the 500-node kubemark and 5k-node clusters solely)

@tosi3k is working on that https://github.com/kubernetes/perf-tests/pull/1401 has just merged, it has to be cherrypicked to previous branches in perf-tests and we will enable that in tests. I'm reluctant for test config changes on Friday, so
ETA: Monday.

**Comment by ahg-g** [comment] 2020-07-24 16:45
Sounds good to me.

**Comment by wojtek-t** [comment] 2020-07-27 19:46
With https://github.com/kubernetes/test-infra/pull/18464 and https://github.com/kubernetes/test-infra/pull/18463 this should now be fixed.

**Closed by wojtek-t** 2020-07-27 19:46 UTC
Labels: kind/bug, kind/flake, sig/scalability, sig/scheduling
