### ISSUE TITLE
unit/integration flake: Timed out waiting for kubelet to answer

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#21640] opened 2016-02-21 06:46 UTC
http://pr-test.k8s.io/21180/kubernetes-pull-test-unit-integration/15343/
```
+++ [0220 07:11:26] Starting kubelet in masterful mode
W0220 07:11:26.807310    4163 server.go:431] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0220 07:11:26.807386    4163 server.go:392] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0220 07:11:26.807492    4163 plugins.go:71] No cloud provider specified.
I0220 07:11:26.807611    4163 manager.go:131] cAdvisor running in container: "/docker/c8b6eb82c8cbd476e5bd29d460b9a70ebd426a697e404e20e21903f913327c43"
I0220 07:11:26.945232    4163 fs.go:107] Filesystem partitions: map[/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c:{mountpoint:/workspace/artifacts major:8 minor:1 fsType: blockSize:0}]
I0220 07:11:27.697590    4163 manager.go:166] Machine: {NumCores:32 CpuFrequency:2499998 MemoryCapacity:127006019584 MachineID:7ae5ca5c485b47b88d89d96a71601d80 SystemUUID:46188494-77D1-5292-10E8-4D7CB332F9D9 BootID:459b5c46-2c98-44c1-b4a9-1835ccdab25f Filesystems:[{Device:/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c Capacity:528310788096}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:536870912000 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:02 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:127006019584 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[2 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[4 5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[6 7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[8 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[10 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[12 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[14 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:8 Threads:[16 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[18 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[20 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:11 Threads:[22 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:12 Threads:[24 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:13 Threads:[26 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:14 Threads:[28 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:15 Threads:[30 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown}
I0220 07:11:27.698820    4163 manager.go:172] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.10.1 CadvisorVersion: CadvisorRevision:}
W0220 07:11:27.699819    4163 server.go:335] failed to apply oom-score-adj to pid &{%!d(string=write) %!d(string=/proc/self/oom_score_adj) 13} (%!v(MISSING))
I0220 07:11:27.699951    4163 server.go:664] Watching apiserver
W0220 07:11:27.700387    4163 iptables.go:144] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
I0220 07:11:27.700510    4163 kubelet.go:363] Hairpin mode set to true
I0220 07:11:27.700573    4163 manager.go:196] Setting dockerRoot to 
!!! [0220 07:11:39] Timed out waiting for kubelet to answer at http://127.0.0.1:10248/healthz; tried 25 waiting 0.5 between each
!!! Error in ./hack/test-cmd.sh:48
  'return 1' exited with status 1
```

**Comment by lavalamp** [comment] 2016-02-22 18:16
Something holding the port already?

**Comment by sjenning** [comment] 2016-02-22 21:30
The previous masterless case just _barely_ passed with a 12.5 second timeout (25 tries at 0.5 second interval)

```
+++ [0220 07:11:26] On try 23, kubelet(masterless): ok
```

I think we just need to increase the timeout.

**Comment by yujuhong** [comment] 2016-02-23 00:57
I randomly sampled 5 green builds and they all have this test (starting kubelet in masterful/less mode) finished in 3s or less.

Judging for the successful masterless mode startup before the failure, kubelet spent the most time trying to register credential providers (a 10s gap in the log). 
The same roughly applies to the failed "masterful mode", based on where the log message stopped.

From https://github.com/kubernetes/kubernetes/blob/d6c43b0606dbebfeec7829291da8cc418b7ea56a/pkg/credentialprovider/gcp/metadata.go#L102, the registering process basically tries to access the metadata url `http://metadata.google.internal./computeMetadata/v1/` to see if the credential provider is enabled. I think this may just be the slow response from the metadata server.

```
+++ [0220 07:11:15] Starting kubelet in masterless mode
I0220 07:11:15.693244    4074 plugins.go:71] No cloud provider specified.
I0220 07:11:15.693405    4074 manager.go:131] cAdvisor running in container: "/docker/c8b6eb82c8cbd476e5bd29d460b9a70ebd426a697e404e20e21903f913327c43"
I0220 07:11:15.815329    4074 fs.go:107] Filesystem partitions: map[/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c:{mountpoint:/workspace/artifacts major:8 minor:1 fsType: blockSize:0}]
I0220 07:11:16.567904    4074 manager.go:166] Machine: {NumCores:32 CpuFrequency:2499998 MemoryCapacity:127006019584 MachineID:7ae5ca5c485b47b88d89d96a71601d80 SystemUUID:46188494-77D1-5292-10E8-4D7CB332F9D9 BootID:459b5c46-2c98-44c1-b4a9-1835ccdab25f Filesystems:[{Device:/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c Capacity:528310788096}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:536870912000 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:02 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:127006019584 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[2 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[4 5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[6 7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[8 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[10 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[12 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[14 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:8 Threads:[16 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[18 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[20 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:11 Threads:[22 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:12 Threads:[24 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:13 Threads:[26 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:14 Threads:[28 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:15 Threads:[30 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown}
I0220 07:11:16.569379    4074 manager.go:172] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.10.1 CadvisorVersion: CadvisorRevision:}
W0220 07:11:16.570058    4074 server.go:335] failed to apply oom-score-adj to pid &{%!d(string=write) %!d(string=/proc/self/oom_score_adj) 13} (%!v(MISSING))
W0220 07:11:16.570138    4074 server.go:592] No api server defined - no events will be sent to API server.
W0220 07:11:16.570289    4074 iptables.go:144] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
I0220 07:11:16.570407    4074 kubelet.go:363] Hairpin mode set to true
I0220 07:11:16.570471    4074 manager.go:196] Setting dockerRoot to 
I0220 07:11:16.570486    4074 plugins.go:56] Registering credential provider: .dockercfg
//  THE 10 SECOND GAP
I0220 07:11:26.574691    4074 plugins.go:56] Registering credential provider: google-dockercfg
I0220 07:11:26.575256    4074 plugins.go:56] Registering credential provider: google-dockercfg-url
I0220 07:11:26.575861    4074 plugins.go:56] Registering credential provider: google-container-registry
I0220 07:11:26.576744    4074 server.go:626] Started kubelet
E0220 07:11:26.576886    4074 kubelet.go:886] Image garbage collection failed: unable to find data for container /
I0220 07:11:26.576969    4074 server.go:108] Starting to listen on 127.0.0.1:10250
W0220 07:11:26.577091    4074 kubelet.go:942] No api server defined - no node status update will be sent.
E0220 07:11:26.579067    4074 kubelet.go:946] Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]
I0220 07:11:26.579100    4074 manager.go:122] Kubernetes client is nil, not starting status manager.
I0220 07:11:26.579122    4074 kubelet.go:2276] Starting kubelet main sync loop.
I0220 07:11:26.579245    4074 kubelet.go:2285] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory] container runtime is down]
+++ [0220 07:11:26] On try 23, kubelet(masterless): ok
+++ [0220 07:11:26] Starting kubelet in masterful mode
W0220 07:11:26.807310    4163 server.go:431] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0220 07:11:26.807386    4163 server.go:392] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0220 07:11:26.807492    4163 plugins.go:71] No cloud provider specified.
I0220 07:11:26.807611    4163 manager.go:131] cAdvisor running in container: "/docker/c8b6eb82c8cbd476e5bd29d460b9a70ebd426a697e404e20e21903f913327c43"
I0220 07:11:26.945232    4163 fs.go:107] Filesystem partitions: map[/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c:{mountpoint:/workspace/artifacts major:8 minor:1 fsType: blockSize:0}]
I0220 07:11:27.697590    4163 manager.go:166] Machine: {NumCores:32 CpuFrequency:2499998 MemoryCapacity:127006019584 MachineID:7ae5ca5c485b47b88d89d96a71601d80 SystemUUID:46188494-77D1-5292-10E8-4D7CB332F9D9 BootID:459b5c46-2c98-44c1-b4a9-1835ccdab25f Filesystems:[{Device:/dev/disk/by-uuid/67f84a7b-f850-4bb1-88e1-44b93711581c Capacity:528310788096}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:536870912000 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:02 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:127006019584 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[2 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[4 5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[6 7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[8 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[10 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[12 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[14 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:8 Threads:[16 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[18 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[20 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:11 Threads:[22 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:12 Threads:[24 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:13 Threads:[26 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:14 Threads:[28 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:15 Threads:[30 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown}
I0220 07:11:27.698820    4163 manager.go:172] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.10.1 CadvisorVersion: CadvisorRevision:}
W0220 07:11:27.699819    4163 server.go:335] failed to apply oom-score-adj to pid &{%!d(string=write) %!d(string=/proc/self/oom_score_adj) 13} (%!v(MISSING))
I0220 07:11:27.699951    4163 server.go:664] Watching apiserver
W0220 07:11:27.700387    4163 iptables.go:144] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
I0220 07:11:27.700510    4163 kubelet.go:363] Hairpin mode set to true
I0220 07:11:27.700573    4163 manager.go:196] Setting dockerRoot to 
!!! [0220 07:11:39] Timed out waiting for kubelet to answer at http://127.0.0.1:10248/healthz; tried 25 waiting 0.5 between each
```

**Comment by aveshagarwal** [comment] 2016-02-26 17:18
I am wondering even if this issue might be related to a slow response from the metadata server, why it does not show "Registering credential provider: .dockercfg" always in failed logs?

**Comment by aveshagarwal** [comment] 2016-02-26 19:43
If there is a possibility that ReadUrl in ./pkg/credentialprovider/config.go may take longer than expected, would it be preferred to use a Timeout (>0) with the http client to not get stuck longer than expected?

**Comment by yujuhong** [comment] 2016-02-29 19:57
> I am wondering even if this issue might be related to a slow response from the metadata server, why it does not show "Registering credential provider: .dockercfg" always in failed logs?

I am unsure why it didn't show that, but even in the passing round we see a 10 second gap, which almost maxed out the timeout.

> If there is a possibility that ReadUrl in ./pkg/credentialprovider/config.go may take longer than expected, would it be preferred to use a Timeout (>0) with the http client to not get stuck longer than expected?

I think adding a timeout is reasonable, but I am not sure what value is reasonable given that the previous request took 10s. @aveshagarwal, do you have any idea?

**Comment by aveshagarwal** [comment] 2016-02-29 20:10
Even I am not sure exactly what should be a reasonable value. My guess would be that if in normal cases, average response time is x seconds (perhaps a guestimate could be computed based on "normal" successful tests), then x could be a starting point, or otherwise another option is choosing something randomly (like 5s). And I think that if at some point, the server is responding in 10s, and even though the test passes, its not normal and something is going wrong.

**Comment by yujuhong** [comment] 2016-02-29 20:57
#22192 uses a 10 second timeout, but the request will be retried. Given that we don't retry this request, a short timeout is worrisome. Maybe we should add both retry and timeout in this case.

**Comment by aveshagarwal** [comment] 2016-02-29 22:15
@yujuhong SGTM.

**Comment by dchen1107** [comment] 2016-03-04 22:12
I reopen this one since pr #22318 was reverted.

**Comment by bprashanth** [comment] 2016-03-09 16:54
Noticed a similar hang in: https://github.com/kubernetes/kubernetes/issues/18980#issuecomment-193600649

The logs are a bit different from those observed in https://github.com/kubernetes/kubernetes/issues/21640#issuecomment-187457714: 
```
E0307 12:28:56.870523    9688 kubelet.go:956] Image garbage collection failed: unable to find data for container /
+++ [0307 12:28:56] On try 2, kubelet(masterless): ok
+++ [0307 12:28:56] Starting kubelet in masterful mode
Build timed out (after 60 minutes). Marking the build as aborted.
Build timed out (after 60 minutes). Marking the build as failed.
```

**Comment by yujuhong** [comment] 2016-03-09 22:17
> Noticed a similar hang in: #18980 (comment)

Uh...even if kubelet couldn't start up properly, the test itself should've timed out and logged "Timed out waiting for kubelet to answer at http://127.0.0.1:10248/healthz; tried 25 waiting 0.5 between each".
I am not sure if this failure is related.

**Comment by yujuhong** [comment] 2016-05-03 23:26
#24557 failure is not relevant to this issue.

The most recent report of such flake was over a week ago. I think the cause is the slow metadata url response in GCE, and that should've been fixed by the recent rollout. I am going to close this issue. Feel free to reopen if there is another occurrence.

**Closed by yujuhong** 2016-05-03 23:26 UTC
Labels: area/test, kind/flake, priority/P1, team/node
