### ISSUE TITLE
Deleting ReplicationController does not delete pods in API 

### ISSUE THREAD

**Issue by bmelville** [kubernetes/kubernetes#22881] opened 2016-03-11 23:11 UTC
Deleting a ReplicationController behaves differently between the command line and the API. From the command line, it will also delete the pods it has created, while in the API the pods are orphaned.

The difference in behavior between command line and API is jarring. Additionally, integrating directly with the API becomes extremely difficult when trying to manage replicationcontrollers directly. We are offering up a set of replicas as a powerful abstraction, but requiring that our customers break the abstraction and clean up after them.

It seems that, since the command line is the primary user interface, its behavior is the preferred one, so is there any plan to unify the two such that deleting a ReplicationController in the API also deletes the resources it has created and is managing?

Is it possible to at least give a choice, through some sort of flag or policy on the ReplicationController object?

**Comment by AdoHe** [comment] 2016-03-12 15:24
@bmelville could you provide your kubernetes version?

**Comment by bmelville** [comment] 2016-03-14 16:21
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}

I'll add that this is not only a function of ReplicationControllers, but also the new DaemonSets apparently. When I create and then delete a DaemonSet through the API, all its pods are left orphaned.

**Comment by pwittrock** [comment] 2016-03-15 00:52
@lavalamp Another use case for moving kubectl logic out of a thick client.

**Comment by lavalamp** [comment] 2016-03-15 00:56
Yeah, there's a very long tail of things like this.

**Comment by AdoHe** [comment] 2016-03-15 02:12
@lavalamp so anything we can do now?

**Comment by lavalamp** [comment] 2016-03-15 22:59
This requires a design. And before that, I want to make a list of everything in this category so we can make sure to move the most important things server-side first.

**Comment by lavalamp** [comment] 2016-03-15 23:00
#12143 is the parent issue.

**Comment by paralin** [comment] 2016-03-17 00:01
I... I actually didn't realize that the Kubernetes API wouldn't delete pods when the RC was deleted. Just discovered that one of my API driven projects isn't cleaning up pods properly. Whoops.

I would here prefer if the API did the deletion/cleanup on default, with an API parameter to prevent deletion of children.

**Comment by bgrant0607** [comment] 2016-04-06 06:29
Anyway, this is a dupe of lots of issues. We're working on it.

**Closed by bgrant0607** 2016-04-06 06:29 UTC
Labels: priority/P1, team/CSI-API Machinery SIG, team/ux

**Comment by vaikas-google** [comment] 2016-04-20 16:20
Can you point to a better bug to follow (since it's a dupe?)

**Comment by bmelville** [comment] 2016-04-26 20:50
@bgrant0607 , should we use #12143 or is there another issue we should use for following along we this? We work with many people for whom this is an issue and want to be able to keep them in the loop.

B.

**Comment by bgrant0607** [comment] 2016-04-26 21:56
Issue: #19054
Proposal: #23656
API changes: #23928
