### ISSUE TITLE
Scheduler making unsatisfiable decisions

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#10397] opened 2015-06-26 14:18 UTC
Now that heapster & influx have a high memory requirement (I think that is the change), I am seeing scheduler misallocations during cluster startup (on AWS, with 2 m3.medium minions).  I'm not entirely sure which Capacity is being exceeded - presumably memory, but elasticsearch-logging doesn't seem to have a memory requirement.

After startup `kubectl get pods` shows a lot of incorrect allocations of elasticsearch-logging:

```
elasticsearch-logging-v1-1klhh       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-40kxq       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-4dcqy       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-4jc9p       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-5bvvc       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-70ofx       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-7sus7       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-7xb66       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-8pfrr       0/1       CapacityExceeded   0          9m
elasticsearch-logging-v1-c1vgw       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-cflz1       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-clxyr       1/1       Running            0          6m
elasticsearch-logging-v1-esxcf       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-gr34g       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-h0u8m       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-ies3p       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-ig7wx       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-jct4c       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-jpd0f       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-kbtj8       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-lwdrc       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-mk2km       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-omq0c       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-p3446       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-pmjf7       1/1       Running            0          9m
elasticsearch-logging-v1-s6bmo       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-sqyrq       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-vs0l0       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-w2rhe       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-xdr2e       0/1       CapacityExceeded   0          6m
elasticsearch-logging-v1-z5qw2       0/1       CapacityExceeded   0          6m
fluentd-elasticsearch-i-557158ff     1/1       Running            0          4m
fluentd-elasticsearch-i-567158fc     1/1       Running            0          4m
kibana-logging-v1-dlzp0              1/1       Running            1          9m
kube-dns-v3-0qx0d                    3/3       Running            0          9m
monitoring-heapster-v4-6y7sd         1/1       Running            0          9m
monitoring-influx-grafana-v1-v2nmp   2/2       Running            0          9m
```

I have 2 nodes, each of which has these resources:

```
 "status": {
                "capacity": {
                    "cpu": "1",
                    "memory": "3853728Ki",
                    "pods": "100"
                },  
```

**Comment by bgrant0607** [comment] 2015-06-26 20:33
See also #10242

**Comment by bgrant0607** [comment] 2015-06-26 20:34
cc @dchen1107

**Comment by bgrant0607** [comment] 2015-06-26 20:35
Or maybe #10406

**Comment by dchen1107** [comment] 2015-06-26 20:44
I want to understand why so many elasticsearch-logging-XXX pods are scheduled to your cluster which only has 2 nodes, and one core each. There is LimitRange object created for default namespace which is still applying to addons service today. #10331 is pending to change this, that is a different issue.

**Comment by dchen1107** [comment] 2015-06-26 20:52
@bgrant0607 just indicates to me that those pods are not pending, instead of CapacityExceeded, which means they are rejected by kubelet at:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1553

cc/ @yujuhong related to mirror pods. On node, there is only one static pod -- fluentd, which by default has 100ms. Shouldn't scheduler take that into account when making decision?

**Comment by bprashanth** [comment] 2015-06-26 21:21
@justinsb can I see your elastic search rc? (kubectl get rc -o json) Can I also get a kubectl describe on both the running elasticsearch pod and one that's capacity exceeded.

**Comment by yujuhong** [comment] 2015-06-29 17:36
> cc/ @yujuhong related to mirror pods. On node, there is only one static pod -- fluentd, which by default has 100ms. Shouldn't scheduler take that into account when making decision?

Yes, all the static pods should have the resource limits set correctly, which will then be used to create mirror pods. To confirm this,  @justinsb, could you post the output the following to output so that we can see if there is any difference?
  1. The details of the fluentd (mirror) pods (`kubectl get pod <pod_name> -o json`)
  2. The manifest used to create the static pods on the node (`/etc/kubernetes/manifests/fluentd-es.yaml` on both nodes)

**Comment by yujuhong** [comment] 2015-07-08 17:25
There could be a race condition: fluentd is a static pod, which means that kubelet would start containers for it, and then create a mirror pod via apiserver. The scheduler would only see the resources consumed by fluentd when it sees the mirror pod. Before that, scheduler may try to assign pods that node without knowing that it'd be rejected (since kubelet knows what's actually running on the node)

As for why scheduler tried assigning all pods to the same node, I am guessing that one node became ready first, while the other lagged behind for a while. During this window, scheduler assigned all pods to the ready node.

I will try reproduce on my GCE cluster.

**Comment by yujuhong** [comment] 2015-07-08 22:10
All the default add-on + fluentd pods require exactly 1100m cpu shares, which is just over the node's capacity. 
If you have only one node, there is one pod deemed to be unable to run: 
```
./cluster/kubectl.sh get pods  --all-namespaces -o wide 
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE       NODE
kube-system   elasticsearch-logging-v1-lxr9r                      1/1       Running   0          7m        e2e-test-yjhong-minion-4onr
kube-system   elasticsearch-logging-v1-po93q                      1/1       Running   0          7m        e2e-test-yjhong-minion-4onr
kube-system   fluentd-elasticsearch-e2e-test-yjhong-minion-4onr   1/1       Running   0          2m        e2e-test-yjhong-minion-4onr
kube-system   kibana-logging-v1-r2q6e                             1/1       Running   1          7m        e2e-test-yjhong-minion-4onr
kube-system   kube-dns-v5-u4hlr                                   3/3       Running   0          7m        e2e-test-yjhong-minion-4onr
kube-system   kube-ui-v1-bpu3y                                    1/1       Running   0          7m        e2e-test-yjhong-minion-4onr
kube-system   monitoring-heapster-v5-swu2b                        0/1       Pending   0          7m        
kube-system   monitoring-influx-grafana-v1-fc7ox                  2/2       Running   0          19m       e2e-test-yjhong-minion-4onr
```
If kubelet cannot creates the mirror pod in time for fluentd, scheduler would schedule all others pods to the same node. Later on, when kubelet realizes that it got assigned pods that exceeded its capacity, it would reject one pod with `CapacityExceeded`. RC may create more pods to replace the failed ones, but eventually, scheduler would realize that the node doesn't have enough resource. The pod would then stay in "Pending".

```
./cluster/kubectl.sh get pods  --all-namespaces -o wide 
NAMESPACE     NAME                                                READY     STATUS             RESTARTS   AGE       NODE
kube-system   elasticsearch-logging-v1-lxr9r                      1/1       Running            0          10m       e2e-test-yjhong-minion-4onr
kube-system   elasticsearch-logging-v1-po93q                      1/1       Running            0          10m       e2e-test-yjhong-minion-4onr
kube-system   fluentd-elasticsearch-e2e-test-yjhong-minion-4onr   1/1       Running            1          1m        e2e-test-yjhong-minion-4onr
kube-system   kibana-logging-v1-jxgeb                             0/1       CapacityExceeded   0          1m        e2e-test-yjhong-minion-4onr
kube-system   kibana-logging-v1-r2q6e                             0/1       CapacityExceeded   0          10m       e2e-test-yjhong-minion-4onr
kube-system   kibana-logging-v1-xut3d                             0/1       Pending            0          1m        
kube-system   kube-dns-v5-u4hlr                                   3/3       Running            0          10m       e2e-test-yjhong-minion-4onr
kube-system   kube-ui-v1-bpu3y                                    1/1       Running            0          10m       e2e-test-yjhong-minion-4onr
kube-system   monitoring-heapster-v5-swu2b                        1/1       Running            0          10m       e2e-test-yjhong-minion-4onr
kube-system   monitoring-influx-grafana-v1-fc7ox                  2/2       Running            0          22m       e2e-test-yjhong-minion-4onr
```
I reproduced this problem by:
 1. Delete the fluentd manifest file
 2. Wait for the scheduler to schedule all other pods
 3. Restore the fluentd manifest. 
It's hard to reproduce otherwise because mirror pods usually get created in a short time frame.

Note that, this is when only one node is ready. If both nodes are ready, scheduler would be able to choose the node with lesser load (from its perspective).

To sum up, 
 - As expected, due to the race condition, there may be a window where scheduler is not aware of the resources consumed by static pods. The fact that all our add-on pods don't fit on one node surface this problem more often than expected.
 - The problem is transient and would be resolved automatically when the mirror pod is finally created. The node simply does not have enough resources to run all the pods.
 - Not having both nodes ready exacerbates the situation, as scheduler has no other nodes to assign to.

If all nodes are near their capacity and creation of mirror pods is slow, the pods may bounce for a while before they settle down. The worst case that I can imagine is when one node has many static pods running, but fail to create mirror pods consistently (for unknown reasons). Scheduler may always assign the pods to the same node due to its low load viewed from the apiserver. I am not sure if this is a plausible case.

**Comment by davidopp** [comment] 2015-07-08 22:20
Thanks for investigating and for the thorough explanation!

**Comment by bprashanth** [comment] 2015-07-08 22:26
It would be cool if we didn't create the cluster addon rcs till all nodes are ready (thought we already did this in kube-up). People will be confused if they see CapacityExceeded zombie pods, and nodes will rarely come up at the same time.

**Comment by yujuhong** [comment] 2015-07-09 00:32
> It would be cool if we didn't create the cluster addon rcs till all nodes are ready (thought we already did this in kube-up

Agreed. These addons are stored in `/etc/kubernetes/addons/` on the master instance and get checked periodically (similar to static pods). Since we create the master instance first, I don't think we wait for all the nodes to be up to create the addons.

**Comment by bprashanth** [comment] 2015-07-09 00:38
Hmm. Doesn't that mean there's a race where we could end up continuously bouncing a static pod in lieu of a cluster addon that could fit on any node (iirc the capacity checks are prioritied by creation time)? oh well.

**Comment by yujuhong** [comment] 2015-07-09 01:12
> Hmm. Doesn't that mean there's a race where we could end up continuously bouncing a static pod in lieu of a cluster addon that could fit on any node (iirc the capacity checks are prioritized by creation time)? oh well.

We prioritize static pods by accident because their creation timestamp, unlike regular pods, isn't set by the apiserver. It's always `0001-01-01 00:00:00 +0000 UTC` :-|

We can explicitly prioritize static pods after v1.0...

**Comment by timothysc** [comment] 2016-12-07 18:13
Closing in preference of: #20064

**Closed by timothysc** 2016-12-07 18:13 UTC
Labels: area/scheduling, priority/P2, team/control-plane, team/node
