### ISSUE TITLE
Pods sharing a PVC on a single node cluster fail to schedule

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#73216] opened 2019-01-23 13:43 UTC
/kind bug
/sig scheduling

**What happened**:
I run 50 Nginx containers on a single node cluster via Deployment with 50 replicas. Those containers have a volumemount via PVC backed by HostPath (`/data/kubernetes/tokens`). Sometimes `kube-scheduler` leaves some pods in `Pending` state, while some get to `Running` state. Error is that it PVC is not bound, yet describing said PVC, it is bound and used by said Pod (and 49 others).

Deleting pod in question helps (new copy gets scheduled), and so does restarting scheduler container, leading to conclusion that it is a bug in scheduler itself.

**What you expected to happen**:
All 50 containers always schedule successfully.

**How to reproduce it (as minimally and precisely as possible)**:
EDIT: Reproduced with minikube: https://github.com/kubernetes/kubernetes/issues/73216#issuecomment-457204530

Nginx deployment.yaml used: https://gist.github.com/tuminoid/56f939e5a06a16be72bbd155ecc75b2f

**Anything else we need to know?**:
Logs, describes etc: https://gist.github.com/tuminoid/5e6367070eb95d45c0d59550b888cd0e

Sometimes all pods come up, sometimes only some, and in this example, it got stuck after it had scheduled only one. Getting stuck after one is very special case, but maybe underlines the issue that it is somehow random/racy.

Maybe relevant issues/PRs?
#72045,  #71551

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
Reproduces on 1.13.1+, 1.12.4+ and 1.14.0-alpha1.

- Cloud provider or hardware configuration: Minikube / self-rolled VM
- OS (e.g. from /etc/os-release): Minikube / RHEL 7.6
- Kernel (e.g. `uname -a`): `Linux kubesingle 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Minikube (kubeadm) / manual
- Others:

**Comment by tuminoid** [comment] 2019-01-24 07:14
This is reproducible on `minikube` as well, with basically any container (since its about scheduling, not the pod itself):

```
NAME                  READY   STATUS    RESTARTS   AGE     IP            NODE       NOMINATED NODE
bb-5697d46cdd-4tqkb   1/1     Running   0          2m35s   172.17.0.21   minikube   <none>
bb-5697d46cdd-5cf4g   0/1     Pending   0          2m34s   <none>        <none>     <none>
bb-5697d46cdd-5tml5   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-6gzgj   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-6ktfz   1/1     Running   0          2m35s   172.17.0.20   minikube   <none>
bb-5697d46cdd-6wf7m   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-7ffj2   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-7r7vt   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-8zc6m   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-95kpw   1/1     Running   0          2m34s   172.17.0.9    minikube   <none>
bb-5697d46cdd-9xqd4   1/1     Running   0          2m35s   172.17.0.19   minikube   <none>
...
```

with YAML of:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb
spec:
  replicas: 50
  strategy: {}
  selector:
    matchLabels:
      service: bb
  template:
    metadata:
      labels:
        service: bb
    spec:
      containers:
        - image: busybox:latest
          command: ['/bin/sh', '-c', '/bin/tail -f /dev/null']
          name: bb
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
          volumeMounts:
            - mountPath: /tokens
              name: pv-vault-proxy
      volumes:
        - name: pv-vault-proxy
          persistentVolumeClaim:
            claimName: pvc-vault-ro
      restartPolicy: Always
      automountServiceAccountToken: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vault-ro
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: sc-vault-ro

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-ro
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-vault-ro
  hostPath:
    path: "/tmp"
```

Reason being `unbound immediate PersistentVolumeClaims`:
```
Name:               bb-5697d46cdd-cvpqc
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             pod-template-hash=5697d46cdd
                    service=bb
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/bb-5697d46cdd
Containers:
  bb:
    Image:      busybox:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
      /bin/tail -f /dev/null
    Limits:
      memory:  32Mi
    Requests:
      cpu:        10m
      memory:     16Mi
    Environment:  <none>
    Mounts:
      /tokens from pv-vault-proxy (rw)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  pv-vault-proxy:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   pvc-vault-ro
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  4m2s (x3 over 4m12s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
```

PV and PVC:
```
$ kubectl get pvc
NAME           STATUS   VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-vault-ro   Bound    pv-vault-ro   10Mi       ROX            sc-vault-ro    5m47s
$ kubectl get pvc,pv
NAME                                 STATUS   VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/pvc-vault-ro   Bound    pv-vault-ro   10Mi       ROX            sc-vault-ro    5m50s

NAME                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                  STORAGECLASS   REASON   AGE
persistentvolume/pv-vault-ro   10Mi       ROX            Retain           Bound    default/pvc-vault-ro   sc-vault-ro             5m50s

**Comment by tuminoid** [comment] 2019-01-24 13:55
Steps to reproduce:
```
$ minikube start # <whatever options you need>
$ kubectl create -f bb.yaml # see up for snippet of bb deployment
$ sleep 180; kubectl get pods | grep Pending   # very likely some pods are Pending and scheduler is stuck/ignoring pods
```

I can reproduce the bug on `1.12.4`, `1.12.5`, `1.13.1` and `1.13.2`, but not on `1.13.0`, `1.12.3` or earlier, or `1.11.6`, or earlier. Common scheduler related commit in all problematic releases is PR #71551. It is also cherry-picked to `1.11.6`, but I cannot reproduce there, so either it requires something in `1.12` tree to trigger, or it isn't about #71551.

Ping @bsalamat, @k82cn and @mlmhl.

**Comment by cofyc** [comment] 2019-01-25 01:32
Could you paste your storage class `sc-vault-ro` yaml too?

**Comment by cofyc** [comment] 2019-01-25 02:09
I guess this happens if PVC/PV cache in VolumeBInder is updated after `c.podQueue.MoveAllToActiveQueue()` is called in `factory.onPvcUpdate`. 

We have two different event handlers for PVC/PV events in scheduler:

- scheduler factory, call `c.podQueue.MoveAllToActiveQueue` to move unscheduable pods into active queue
- volume binder PV/PVC assume cache, to receive updates from API server

But there is no guarantee in which order different event handlers will be
called, see [docs](https://godoc.org/k8s.io/client-go/tools/cache#SharedInformer).

I've tried to fix this in an [old PR](https://github.com/kubernetes/kubernetes/pull/71213) to avoid inconsistent between ecache invalidations and PV/PVC cache.

Unscheduable pods may be moved to active queue before PV/PVC cache is updated is not a big problem before because we will move unscheduable pods to active queue on node heartbeat status update.

After https://github.com/kubernetes/kubernetes/pull/71551, we relies on PV/PVC events to move unscheduable pods to active queue. So when pod is rescheduabled, if PV/PVC in volume binder cache is not updated, pod will be unscheduable again and stuck in this situation.

**Comment by cofyc** [comment] 2019-01-25 02:38
@bsalamat @k82cn @misterikkit @msau42

I think we need find a way to move unscheduable pods to active queue after PV/PVC cache update in volume binder now.

The way I'm trying to do in https://github.com/kubernetes/kubernetes/pull/71213 is not good (leak volume binder cache details into scheduler). Does new scheduler framework support a better way?

**Comment by msau42** [comment] 2019-01-25 02:47
For a short term solution, I can see potentially two ways to fix this:
* Pass podqueue to volume scheduler cache, so it can move pods to active queue when it updates its cache
* Volume scheduler cache registers a handler that gets invoked in the scheduler factory's event handler, instead of registering as a separate informer handler.

The 2nd approach probably aligns better with the scheduler v2 framework

**Comment by tuminoid** [comment] 2019-01-25 04:38
@cofyc There is no separate `sc-vault-ro`, PV is statically created and SC is just used to map it to PVC.

Thanks for the initial analysis.

**Comment by cofyc** [comment] 2019-01-25 04:46
Thanks! I reproduced this issue locally, it has no relation with SC.

**Comment by cofyc** [comment] 2019-01-25 10:31
My mistake, the second issue is already addressed in https://github.com/kubernetes/kubernetes/pull/73078.

**Comment by bsalamat** [comment] 2019-01-25 18:32
FYI, we have also added #72558 to move pods to the active queue periodically. Is the issue reproducible in HEAD which has this change?

**Comment by tuminoid** [comment] 2019-01-30 06:03
I'll test 1.14.0-alpha2 if its reproducible.

**Comment by tuminoid** [comment] 2019-01-30 16:08
Does not reproduce for me with 1.14.0-alpha.2, which has #72558.

Disclaimer: minikube has issues with 1.14.0-alpha.2, as kube-apiserver doesn't recognize `Initializers` in `--enable-admission-controller`, so it has to be manually edited away to use minikube with alpha.2.

**Comment by tuminoid** [comment] 2019-02-07 11:03
Interestingly, it also doesn't reproduce on 1.12.5, which doesn't have #72558. It does have #72619 instead. 

1.13.3 has #72558, but it also has #72619. Same with 1.14.0-alpha.2, it has both.

So it might not actually be #72558 that fixes this, but #72619. Could someone verify why?

**Comment by bsalamat** [comment] 2019-02-21 20:39
@tuminoid Thanks for testing various versions. #72558 is already cherrypicked to 1.11+ branches.

**Comment by bsalamat** [comment] 2019-02-21 20:45
It is worth noting that #73309 is also a great improvement that should address this issue. With #73309 we should see the logic added by #72558 to get exercised in very rare (and unexpected) situations. Basically #72558 is our safety valve.
With the issue addressed, I think we can close this issue. Please feel free to reopen if needed.

**Closed by bsalamat** 2019-02-21 20:45 UTC
Labels: kind/bug, sig/scheduling
