### ISSUE TITLE
e2e flake: "Horizontal pod autoscaling (scale resource: CPU) [Skipped] [Autoscaling] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5" is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#17866] opened 2015-11-27 09:24 UTC
It failed twice within last 5 runs with the following error:

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:56 Nov 26 18:58:15.098: Number of replicas has changed: expected 3, got 4

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1851/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1849/

@jszczepkowski @mwielgus @piosz @gmarek

**Comment by jszczepkowski** [comment] 2015-11-30 09:15
The problem seems to be caused by flakiness of resource consumer:

```
 "items": [
   {
    "metrics": [
     {
      "timestamp": "2015-11-27T02:56:00Z",
      "value": 0
     }
    ],
    "latestTimestamp": "2015-11-27T02:56:00Z"
   },
   {
    "metrics": [
     {
      "timestamp": "2015-11-27T02:56:00Z",
      "value": 245
     }
    ],
    "latestTimestamp": "2015-11-27T02:56:00Z"
   },
   {
    "metrics": [
     {
      "timestamp": "2015-11-27T02:56:00Z",
      "value": 134
     },
     {
      "timestamp": "2015-11-27T02:55:00Z",
      "value": 260
     }
    ],
    "latestTimestamp": "2015-11-27T02:56:00Z"
   }
  ]
 }
```

**Comment by jszczepkowski** [comment] 2015-11-30 09:19
Marking as duplicate of #16425.

**Closed** 2015-11-30 09:20 UTC
Labels: area/autoscaling, kind/flake, priority/P0, team/control-plane
