### ISSUE TITLE
Accessing non-sensitive data of Secrets

### ISSUE THREAD

**Issue by rubenhak** [kubernetes/kubernetes#86268] opened 2019-12-14 05:02 UTC
/sig api-machinery

Secrets hold sensitive data. There is a need to allow certain programs to access Configuration part of secrets, yet restricting access to the sensitive data. Such capability would allow tools to validate correctness of configuration without worrying that the sensitive data can be leaked.

The plan is to query sanitized version of Secrets:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-name
  namespace: my-namespace
data:
  my-key-1: ***
  my-key-2: ***
  my-key-3: ***
```

One solution could be an introduction of additional API and RBAC verbs "get-sanitized" and "watch-sanitized".

**Comment by liggitt** [comment] 2019-12-14 16:59
Duplicate of https://github.com/kubernetes/kubernetes/issues/78056, see prior discussion there of the implications of this type of change. 

sig api-machinery and sig-auth are the likely sigs that would need to be involved in a proposal that works through the implications of a change like this

**Comment by liggitt** [comment] 2019-12-14 17:04
As noted in https://github.com/kubernetes/kubernetes/issues/78056#issuecomment-545561787 this is unlikely to make progress as an issue. A proposal that works through the design along with the implications of such a change can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps). I would suggest reaching out to the mentioned sigs to discuss the idea and see if there is interest in collaborating on a proposal. 

/close

**Closed by liggitt** 2019-12-14 17:04 UTC
Labels: kind/feature, priority/awaiting-more-evidence, sig/api-machinery, sig/apps, sig/auth
