### ISSUE TITLE
e2e flake: It should ensure a single API token exists

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#21995] opened 2016-02-25 17:56 UTC
It] should ensure a single API token exists
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service_accounts.go:152
STEP: waiting for a single token reference
Feb 25 08:46:55.622: INFO: default service account has a single secret reference
STEP: ensuring the single token reference persists
STEP: deleting the service account token
STEP: waiting for a new token reference
Feb 25 08:46:58.347: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:46:58.880: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:46:59.432: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:46:59.818: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:00.344: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:00.869: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:01.362: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:01.895: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:02.590: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:02.911: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:03.559: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:03.889: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:04.352: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:04.834: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:05.387: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:05.859: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:06.420: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:07.027: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:07.668: INFO: default service account still has the deleted secret reference
STEP: waiting for a new token reference
Feb 25 08:47:08.019: INFO: default service account still has the deleted secret reference
Feb 25 08:47:08.019: INFO: Unexpected error occurred: timed out waiting for the condition
[AfterEach] ServiceAccounts
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:84

**Comment by derekwaynecarr** [comment] 2016-02-25 17:56
@liggitt

**Comment by spxtr** [comment] 2016-02-28 19:11
This may have been caused by 6f8a951 (#20446). Both `kubernetes-e2e-gce` and `kubernetes-e2e-gke` failed this test for the first time on that commit and have been flaky ever since. Hard to say with flakes, though.

**Comment by bgrant0607** [comment] 2016-02-29 04:17
This failed at least 15 times in the last day or so. It needs to be fixed or moved back to the flaky suite.

**Comment by liggitt** [comment] 2016-02-29 05:02
It's a relatively new test (about a week old), but I'm having a hard time seeing what made it flaky in the last couple days, and I can't reproduce locally (of course). Testing a possible fix in https://github.com/kubernetes/kubernetes/issues/22160

**Comment by piosz** [comment] 2016-02-29 09:22
Yet another fail
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/12482/

cc @mwielgus @fgrzadkowski

**Comment by piosz** [comment] 2016-02-29 14:23
And same for GKE:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/1951/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/1952/

**Comment by quinton-hoole** [comment] 2016-02-29 18:37
@liggitt quite a few flakes against ubernetes-lite too.  Perhaps you should label these tests as flaky until they're stable, as they're blurring our regression signals.

In case it helps, we started to notice the errors at the following time, when the following PR's were merged:

Build #8739 (Feb 27, 2016 7:48:08 PM)
	Changes

* Modify ResourceQuota API to support requests/limits; scope filtering 
* Generated code for ResourceQuota API change
* ResourceQuota API validation for scopes and new resource types 
* Add quota evaluator framework 
* Make ResourceQuota admission and controller work generically
* Improve rendering of multiple quotas in namespace; show scopes 
* Add e2e tests for ResourceQuota
* Update resource quota scope documentation
* Improve overlapping quota behavior when there is a resource conflict

**Comment by quinton-hoole** [comment] 2016-02-29 18:40
@derekwaynecarr your ResourceQuota changes appear to be the smoking gun at this point.

**Comment by saad-ali** [comment] 2016-02-29 18:42
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/12508/

**Comment by liggitt** [comment] 2016-02-29 18:42
I don't see a direct connection between the quota bits and this test.

Unrelated note... the PR to fix this has had 7 clean test runs in a row, two of which were started by the merge bot, but it's not getting merged. Any idea why?

**Comment by spxtr** [comment] 2016-02-29 18:44
Mergebot doesn't want to merge anything when e2e tests are failing. Message oncall to merge a flake fix by hand.

**Comment by quinton-hoole** [comment] 2016-02-29 18:48
@liggitt Are you referring to #22160 ?  If so, it only got an LGTM 3 hours ago, and bas verified as good by merge-bot a few minutes ago.  merge-bot is a bit backed up at the moment.

If you're referring to some other PR, let me know which, and I can dig into it for you.

**Comment by liggitt** [comment] 2016-02-29 18:49
yes, #22160. the merge bot has attempted to merge it twice, got clean test runs both times, and not merged it.

**Comment by saad-ali** [comment] 2016-02-29 18:50
I'm on-call. I'll manually merge #22160

**Closed** 2016-02-29 18:51 UTC
Labels: kind/flake, priority/P0, team/control-plane

**Comment by derekwaynecarr** [comment] 2016-02-29 21:20
@liggitt @quinton-hoole - i guess anything is possible, but i am not sure the underlying reason... if anything i would have expected quota e2es fail..

**Comment by quinton-hoole** [comment] 2016-02-29 22:17
FYI, 10 clean runs so far on http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/ since #22160 merged.

**Comment by liggitt** [comment] 2016-02-29 22:23
great... that one did fix a legitimate issue
