### ISSUE TITLE
Kubernetes Pods not scheduled due to "Insufficient CPU" when CPU resources are available

### ISSUE THREAD

**Issue by armandocerna** [kubernetes/kubernetes#33777] opened 2016-09-29 18:44 UTC
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS, masters (Count: 3, Size: m3.medium), minions (Count 5, Size m4.xlarge)
- **OS** (e.g. from /etc/os-release): 14.04.5 LTS, Trusty Tahr
- **Kernel** (e.g. `uname -a`): Master:  3.13.0-95-generic Minion: 4.4.0-38-generic
- **Install tools**: Ansible using modified contrib playbooks: https://github.com/kubernetes/contrib/tree/master/ansible
- **Others**:

**What happened**:  When scheduling pods with a low resource request for CPU (15m) We recieve the message "Insufficient CPU" across all nodes attempting to schedule the pod.  We are using multi container pods and running a describe pods shows nodes with available resources to schedule the pods.  However k8s refuses to schedule across all nodes.  
[kubectl_output.txt](https://github.com/kubernetes/kubernetes/files/501431/kubectl_output.txt)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Below is a sample manifest that we can use to produce the output.  
[manifest.txt](https://github.com/kubernetes/kubernetes/files/501443/manifest.txt)

We end up scheduling pods up until about 10-14 pods and then we run into this problem. See graph below

<img width="1090" alt="screen shot 2016-09-29 at 11 30 56 am" src="https://cloud.githubusercontent.com/assets/5752233/18967327/9a73acde-8639-11e6-9b93-1e545fa3d94f.png">

**Comment by pizzarabe** [comment] 2017-04-24 10:00
We got the same problem. 
Unable to create more pods `Insufficient cpu` while all nodes are on ~5 - 10% cpu load

**Comment by fieryvova** [comment] 2017-05-12 13:05
Restart helped us as well. Is it something that's going to be fixed soon?

**Comment by rochdev** [comment] 2017-06-15 14:14
We are having the same problem and cannot restart the master since we are in GKE.

**Comment by chrissound** [comment] 2017-09-12 09:32
How do you restart the nodes? I'm using Google Cloud platform... Would I SSH into the compute instances and restart?

**Comment by flaviamissi** [comment] 2017-09-13 12:44
I had the same problem today (on GKE), restarted my nodes from the console interface, when they came back online I re-deployed everything and it works now.

**Comment by chrissound** [comment] 2017-09-13 14:04
@flaviamissi I've found the high cpu instances to work better.

**Comment by flaviamissi** [comment] 2017-09-15 09:49
Thanks @chrissound, I have another cluster with high cpu instances and indeed they haven't shown any issues.

Not sure if related, but I recently got an email from GCP pointing to these docs https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/. GKE will start doing this after `1.7.6` upgrade.

**Comment by dehypnosis** [comment] 2017-09-20 09:08
Kube-dashboard says that only 0.05 cpu unit is being occupied.
Why pod cannot be scheduled?

**Comment by discordianfish** [comment] 2017-10-21 13:41
Same issue on GKE, just added a fresh new instance (micro) but it won't schedule even the smallest pod on it. Eg:

 ```
    Requests:
      cpu:		1Mi
      memory:		64Mi
...
  26m		1s		95	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: Insufficient cpu (5).
```
Though on the fresh node there is enough cpu available:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  320m (34%)	100m (10%)	262Mi (44%)	414Mi (69%)
```

Other nodes are pretty packed at ~95% cpu allocated on each node, though even there it should schedule a 1m cpu pod.

**Comment by gempesaw** [comment] 2018-01-16 16:21
We had this same issue: we could schedule pods with CPU resources initially, over time the master(?) seemed to fall out of sync and wouldn't schedule any pods with CPU resources despite `describe nodes` reporting plenty of capacity - at which point, restarting the master temporarily restores functionality until it thinks the nodes are full again.

As part of coreOS updates, we bumped our etcd version to 3.2.9 and we are no longer seeing the problem: pods schedule happily when `describe nodes` indicates capacity is sufficient; when pods cannot schedule, `describe nodes` indicates that all the nodes do not have the capacity to handle the pod as requested. YMMV...

https://github.com/kubernetes/kubernetes/issues/45237#issuecomment-305654535 indicates that an analogous problem with memory resource was also solved by bumping etcd versions...

**Comment by RochesterinNYC** [comment] 2018-01-24 23:35
I might be seeing this as well (on GKE):

I have a deployment with:
```
[...]
        resources:
          requests:
            cpu: 1
            memory: 3G
[...]
        resources:
          requests:
            cpu: 9G
            memory: 52G
[...]
```

trying to deploy to a cluster that has 3 nodes with `15.89 CPU` allocatable and `57.65 GB` memory allocatable but getting `Insufficient cpu (3), Insufficient memory (6)` for scheduling.

Doing stuff like bumping the second container down to:

```    
   requests:
      cpu:        4G
      memory:     22G
```
results in the same scheduling issue.

**Comment by pgeorgiev333** [comment] 2018-01-30 08:45
Hi,

the issue has been submitted in 2016. Any idea when it will be fixed? I have Openshift Origin 3.7 and this is killing me.....

**Comment by aasmm7x** [comment] 2018-03-16 18:15
Nothing?

**Comment by appelsiini** [comment] 2018-04-11 15:52
Having a similar issue, there's almost 4 whole CPUs available within the cluster, a new Pod is requesting `500m` (half) & scheduler reports insufficient CPU in all nodes. 😱

**Comment by OlafSzmidt** [comment] 2018-05-09 14:28
Same issue here. GKE. 1.9.2-gke.1.

**Comment by pv93** [comment] 2018-05-10 22:00
Same issue, running 1.9.6-gke.1

**Comment by ambition-consulting** [comment] 2018-05-10 23:00
+1

**Comment by SJAnderson** [comment] 2018-05-12 08:37
This issue is coming up on two years now, we're seeing this and its holding us back from going to production.

**Comment by yangwenmai** [comment] 2018-05-18 03:43
Notice that `es-master.yaml` and `es-client.yaml`, you can change `replicas: 3` to `replicas: 1`.

**Comment by mbutan** [comment] 2018-05-22 06:13
Did anyone resolve this issue?

**Comment by k82cn** [comment] 2018-05-22 07:10
seems a really old issue, any new logs for this issue?

**Comment by chrissound** [comment] 2018-05-22 07:58
This isn't really an 'issue' and I think we should close this question. See here for a further explanation: https://stackoverflow.com/a/45585916/1663462

There main issue is probably that it's not very intuitive why one gets the error message - even though it is the intended and correct behavior.

**Comment by pv93** [comment] 2018-05-23 17:28
Why doesn't it trigger a scaleup then @chrissound?? Do I have to make sure that any pods I run on a given node request less than what the system pods have already taken up?

**Comment by tkyang99** [comment] 2018-06-05 22:18
Having the same issue here. I have many nodes with just 3% CPU utilization but for some reason new pods are not being allocated to them.

**Comment by k82cn** [comment] 2018-06-06 01:31
What's the version? any log ? The original issue is happened in 1.3.x, really old one.

I'd like to close this old issue, and please feel free to open a new one with more info, e.g. log, version :)

**Comment by nelsonfassis** [comment] 2018-06-06 22:45
@k82cn 
```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  31s (x637 over 3h)  default-scheduler  No nodes are available that match all of the predicates: Insufficient cpu (7), Insufficient memory (3), PodToleratesNodeTaints (5)
```
My resources on one of my nodes (they are all pretty much the same)
```
Capacity:
 cpu:     32
 memory:  65690484Ki
 pods:    110
Allocatable:
 cpu:     32
 memory:  65588084Ki
 pods:    110

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits    Memory Requests  Memory Limits
  ------------  ----------    ---------------  -------------
  26817m (83%)  30617m (95%)  12784Mi (19%)    32756Mi (51%)
```

It doesn't make sense to use the POD Limit, which should kill my pod in case of memory leak or some abnormal CPU usage, to limit POD scheduling. If I have 100 pods with each of them have one limit, is very unlikely that they will all be running at its peak limit at the same time. Kubernetes should know about the used resources on my node for that.

So, either I have to create pods that will have veeery little requests and will not be able to handle any burst of requests for example, or I will waste a huge amount of resources because of it.

**Comment by hrdymchl** [comment] 2018-06-15 14:44
Also seeing this issue. We're on GKE.

**Comment by mbutan** [comment] 2018-06-18 06:50
My problem was caused by CPU limits at IAM & admin -> Quotas -> Compute Engine API (CPU), had to requests for more resources available for my environment since upgraded limits my pods scale up easily.

**Comment by souravsekhar** [comment] 2018-06-20 15:03
I had similar issue, where pods failed scheduling due to insufficient CPU where all nodes are available. I found the issue with resource allocation. Resources were allocated in a manner that was exceeding the actual resources available. Reallocated, resources properly and things worked fine.

**Comment by nelsonfassis** [comment] 2018-06-27 17:13
@nsidhaye So, turns out my problem was:
We had 30 cores to use, every deployment had a default request/limit set to 1 core request, 2 cores limit.
Even tho the apps weren't consuming more than 50mi cpu, it was "locking" 1 whole core, meaning we hit the limit of 30 apps pretty quickly.

We had to redeploy most of our apps based on real resource consumption, using Prometheus/Grafana, we checked what is the average CPU consumption (and memory) for each pod, calculate how much it shoudl request and updated those values.

If you do a `kubectl describe nodes` you should see how much resources you already requested by node, and it should point you in the correct direction of fixing your issue.

**Comment by chenqiangzhishen** [comment] 2018-07-12 07:39
the same issue.

```
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedScheduling 38s (x8 over 1m) default-scheduler 0/25 nodes are available: 1 Insufficient pods, 1 PodToleratesNodeTaints, 23 Insufficient cpu.
```
we run pods with the same limit and request value of cpu(400m)/mem (1Gi), every node with 32core cpu, 128 mem, exclude the system resource part, we would run at least 60*24=1224 pod, but only runs the total of 906 pods.
when pick one node to  verify,  it really does not meets the full resoure. (only 43%)
```
Name: 10.129.22.23
Roles: <none>
Labels: beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
kubernetes.io/hostname=10.129.22.23
Annotations: node.alpha.kubernetes.io/ttl=0
volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp: Mon, 09 Jul 2018 17:17:28 +0800
Taints: <none>
Unschedulable: false
Conditions:
Type Status LastHeartbeatTime LastTransitionTime Reason Message
---- ------ ----------------- ------------------ ------ -------
OutOfDisk False Thu, 12 Jul 2018 09:02:41 +0800 Mon, 09 Jul 2018 17:17:28 +0800 KubeletHasSufficientDisk kubelet has sufficient disk space available
MemoryPressure False Thu, 12 Jul 2018 09:02:41 +0800 Mon, 09 Jul 2018 17:17:28 +0800 KubeletHasSufficientMemory kubelet has sufficient memory available
DiskPressure False Thu, 12 Jul 2018 09:02:41 +0800 Mon, 09 Jul 2018 17:17:28 +0800 KubeletHasNoDiskPressure kubelet has no disk pressure
Ready True Thu, 12 Jul 2018 09:02:41 +0800 Mon, 09 Jul 2018 17:17:59 +0800 KubeletReady kubelet is posting ready status
Addresses:
InternalIP: 10.129.22.23
Hostname: 10.129.22.23
Capacity:
cpu: 32
memory: 131911884Ki
pods: 110
Allocatable:
cpu: 32
memory: 131809484Ki
pods: 110
System Info:
Machine ID: 956ff818ca37414b8c43a31332f739bb
System UUID: 6b6cbe2a-5582-11e8-03ce-38adbed82897
Boot ID: ff7f7735-628a-4245-90cc-3fac5e82c436
Kernel Version: 4.17.4-1.el7.elrepo.x86_64
OS Image: CentOS Linux 7 (Core)
Operating System: linux
Architecture: amd64
Container Runtime Version: docker://18.3.0
Kubelet Version: v1.9.3
Kube-Proxy Version: v1.9.3
ExternalID: 10.129.22.23
Non-terminated Pods: (36 in total)
Namespace Name CPU Requests CPU Limits Memory Requests Memory Limits
--------- ---- ------------ ---------- --------------- -------------
default iperf-server-controller-n6zqf 0 (0%) 0 (0%) 0 (0%) 0 (0%)
default kube-proxy-10.129.22.23 0 (0%) 0 (0%) 0 (0%) 0 (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-170 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-191 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-213 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-226 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-252 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-280 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject0-8kjzl nginx-pod-292 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-1 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-103 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-112 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-28 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-47 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-55 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-71 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-81 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject1-p24vs nginx-pod-90 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-100 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-117 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-133 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-142 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-158 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-163 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-178 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-203 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-225 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-244 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-25 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-255 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-260 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-58 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-80 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
e2e-tests-clusterproject2-qdpm5 nginx-pod-9 400m (1%) 400m (1%) 1Gi (0%) 1Gi (0%)
kube-system calico-node-9rnh6 250m (0%) 0 (0%) 0 (0%) 0 (0%)
kube-system node-exporter-mdtfh 1 (3%) 1 (3%) 2Gi (1%) 2Gi (1%)
Allocated resources:
(Total limits may be over 100 percent, i.e., overcommitted.)
CPU Requests CPU Limits Memory Requests Memory Limits
------------ ---------- --------------- -------------
14050m (43%) 13800m (43%) 34Gi (27%) 34Gi (27%)
```

**Comment by chenqiangzhishen** [comment] 2018-07-13 01:54
workaround by restart kube-scheduler, then everything goes ok...

**Comment by chenqiangzhishen** [comment] 2018-07-13 01:58
workaround by restart kube-scheduler, then everything goes ok...

**Comment by Phineas** [comment] 2018-09-25 11:06
Still having this issue... on GKE.

**Comment by salvagglez** [comment] 2018-10-01 20:54
Same issue on GKE....

Even showing kube-system elements one of my nodes only uses 5% of the CPU resource:
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  100m (**5%**)     0 (0%)      0 (0%)           0 (0%)

**Comment by JCMais** [comment] 2018-10-03 01:56
I had this same issue, GKE has a default `LimitRange` with default limits for CPU request set to `100m`, this can be checked by running `kubectl get limitrange -o=yaml -n default|your-namespace`.


This limit is applied to every container. So for instance, if you have a 4 cores node, and assuming that for each POD 2 containers are going to be created, it will allow only for around ~20 pods to be created, at least that was what I understood about it.

The way around here is to change the default limit by changing the LimitRange, and removing old pods, so they are recreated with the new defaults, or specifically adding a different limit range to the new pods config.

Some reading material:
https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#specify-a-cpu-request-and-a-cpu-limit
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#create-a-limitrange-and-a-pod
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits

**Comment by JerzySpendel** [comment] 2018-10-04 10:55
JCMais, thanks! It worked for me (I removed LimitRange)

**Comment by vehsakul** [comment] 2018-11-24 15:43
On GKE it seems that the scheduler can run about 5 times fewer pods than it could according to the resource request. With the default of 100m it runs 2 pods (the node is almost idle, so it could run 9-10). With 40m 5 pods can run and with 20m -- 10 pods and so on. Setting cpu limit equal to request has no effect.

**Comment by stmaute** [comment] 2018-12-18 13:11
Any news on this issue? Encountered this on AWS EKS when a rolling update is performed.
Some pods stay in Pending state after rolling update.

**Comment by OlafSzmidt** [comment] 2018-12-18 13:31
@stmaute - you need to limit your pods to be allocated less CPU, depending on the machine it's running on.

**Comment by stmaute** [comment] 2018-12-18 13:36
hi @OlafSzmidt I have defined resource request and limit for my deployments. I have also set maxUnavailable=1 and maxSurge=0. 
I would expect that a rolling update will work because there are enough cpu resources available.

**Comment by KristianWindsor** [comment] 2019-01-01 07:36
I'm also having this issue. Is there no solution or steps to debug this yet?

**Comment by nelsonfassis** [comment] 2019-01-01 22:48
@KristianWindsor I will suggest you to describe the node you believe that should fit your request and check how it is. In my case, my mistake was to think that "requests == usage", so my nodes were using almost nothing of my resources but I made all the requests already. 
I believe that should be your case too.

**Comment by Chrisjw42** [comment] 2019-01-03 06:14
I am using GKE, and I've noticed that I receive this error when reaching the CPU limits as describes in @mbutan 's comment. Have a look at that limit (the default for us at this time is 8)

**Comment by sciffer** [comment] 2019-01-03 23:18
I'm seeing the exact same problem with Kubernetes 1.10.11, I wonder if I'm missing any of the settings the @mbutan mentioned(I could not find anything like that on AWS settings - maybe it's a GKE thing). My cluster runs on AWS(deployed using KOPS), pretty much a clean install.
Restarting the kube-schedulers works for me as well, but it is a temporary solution as quickly it gets back to it's "problematic" mode.
I checked the limitrange parameter as well and it is only set on the default namespace which I'm not using anyhow.

**Comment by myonlyzzy** [comment] 2019-02-18 08:30
I think the reason there is no  node  cpu Requests  can satisfied pod cpu request.  use this command check all node cpu request ,  `kubectl describe nodes {NodeName}` . if pod request cpu add current request cpu more than 100% , kube-scheduler will  get a event "Kubernetes Pods not scheduled due to "Insufficient CPU" "

**Comment by kivagant-ba** [comment] 2019-03-19 12:24
I know that it won't solve all the problems mentioned on the page but it my case it was a typo caused by copy-n-paste.

As you can see [in the documentation](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu):

> The expression `0.1` is equivalent to the expression `100m`, which can be read as `“one hundred millicpu”`.

But some people including me can accidentally copy values of **cpu** limits from **memory** limits and just use wrong syntax.

So the solution in this case is to replace **Mi** with "m".

**Comment by imriss** [comment] 2019-06-13 19:45
@myonlyzzy , thanks for your explanation. Is there any workaround that you suggest? In our case, it is a `helm` chart that deploys four `statefulset` that race against each other. However, the actual utilization does not go up enough to activate the `Auto Scaling group`, while many of the pods go in pending state with this error (`Insufficient cpu`).

**Comment by qqzeng** [comment] 2019-06-15 06:33
> We got the same problem.
> Unable to create more pods `Insufficient cpu` while all nodes are on ~~5 - 10% cpu load~ 60-70% cpu limit (`kubectl describe node`).
> Restarting the Master Node seems to successfully schedule the pods.

it works for me!

**Comment by sciffer** [comment] 2019-06-17 14:56
Can you share the yaml config?

Thanks,
Shalom

**Comment by suhavangupta** [comment] 2019-08-28 14:16
increasing the number of nodes helped me.

**Comment by zimmertr** [comment] 2019-08-28 23:38
Is this not happening because your specified CPU Limits exceed the possible number of CPU resources available among your hosts?

**Comment by aditanix** [comment] 2019-10-03 23:59
Is restarting the nodes the only solution to this problem? How can I circumvent this issue in a prod environment?

**Comment by zimmertr** [comment] 2019-10-04 04:07
Can you confirm that the resource limits you put in your manifests do not exceed the available resources in your cluster?

**Comment by tegk** [comment] 2019-12-09 11:45
Same here

**Comment by pisymbol** [comment] 2020-01-30 03:31
So this just happened to me. I have a four node RPi4 cluster (look out!):

```
Capacity:
  cpu:                4
  ephemeral-storage:  122820100Ki
  memory:             3999756Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  113191003973
  memory:             3897356Ki
  pods:               110
```

If Spark tries to schedule executors with cores=4, k8s scheduler barfs and says insufficient cpus?? If I make it 3 it works. No idea why since each worker node has 4 cores available.

**Comment by SaschaHeyer** [comment] 2020-03-05 19:53
Is there any official update to this topic?

**Comment by ahilsend** [comment] 2020-05-17 08:11
I have noticed the same in my cluster, running v1.18.2. Restarting the master node running the scheduler with the lock fixed it.

It would appear the scheduler caches some state, and doesn't properly invalidate it. Is there any way I can help troubleshoot this further?

**Comment by jmatt-cavli** [comment] 2020-06-11 18:16
I had the same issue, but spending some time debugging, I found the issue. It is not a bug in my case. Try checking kubectl describe nodes {node name}, and sum the total cpu requests by other pods. 

In my case, there were insufficient cpu resources left. Even though the overall cpu is not much utilised and free resources are available, the cpu requests from each pods are reserved and allocated dedicatedly in the nodes. Try reducing the cpu requests from other pod,  and the pending pods will get scheduled automatically..

**Comment by iqbalhusen** [comment] 2020-08-25 16:37
For me, creating all the deployments and services in a different namespace (other than `default`) fixed this issue.

**Comment by ksanchez15** [comment] 2020-08-25 18:29
I'm trying to install ElasticSearch on my AKS cluster using helm. I get an error telling me there isn't enough cpu. I have prometheus on my cluster but there are no spikes in cpu that would go close to 100%. 

Could someone help me understand the output of `kubectl describe node`? What is the relationship between requests and limits, what should the numbers look like?

**Comment by Romiko** [comment] 2020-11-15 01:33
I am having this issue with the Prometheus Alert Manager when I install a Virtual Node in GKE using the Azure Container instance provider.

**Comment by Romiko** [comment] 2020-11-15 01:36
The prometheus pod that got unscheduled has the following limits.

   Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi

Looking at the cluster, there is over 90% cpu available on all nodes. When I remove the aci  virtual node, pods return back to normal.

**Closed** 2021-04-14 02:59 UTC
Labels: area/nodecontroller, lifecycle/rotten, sig/scheduling

**Comment by chalcrow** [comment] 2021-04-23 05:18
In this scenario AWS/Azure/whatever can report incorrect CPU usage. Use `kubectl describe node xxxx` to check each node. You'll probably find that the CPU usage on the node is too high (see image below - this is showing a healthy state, but you may see that this is e.g. 80% in your own case). You may need to delete some resources from the node (e.g. any unused pods that aren't required) in order to successfully schedule new pods onto the node.

![image](https://user-images.githubusercontent.com/8063058/115821830-da2d4d00-a446-11eb-9f1a-c1ae24a60005.png)

**Comment by diepes** [comment] 2022-10-27 19:04
Still running into scheduling issues reporting not enough CPU, while describe nodes show CPU available under CPU request's.

v1.24

Could pod affinity cause this, wondering if the error is maybe just misleading.
