### ISSUE TITLE
AWS /mnt/ephemeral/kubernetes runs out of space

### ISSUE THREAD

**Issue by jtbcgdv** [kubernetes/kubernetes#13508] opened 2015-09-02 11:48 UTC
After a couple of days the mount point fills up and the node fails so I have to kill the EC2 instance.  This happens regularly and in different kubernetes clusters

Minion instance size m3.large
AWS region eu-west-1
Kubernetes version 1.0.3

```
Filesystem                            Size  Used Avail Use% Mounted on
udev                                  3.7G     0  3.7G   0% /dev
tmpfs                                 748M   75M  674M  10% /run
/dev/xvda1                            7.8G  2.0G  5.4G  27% /
tmpfs                                 3.7G  1.1M  3.7G   1% /dev/shm
tmpfs                                 5.0M     0  5.0M   0% /run/lock
tmpfs                                 3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/mapper/vg--ephemeral-docker       30G  3.2G   25G  12% /mnt/ephemeral/docker
/dev/mapper/vg--ephemeral-kubernetes  1.4G  1.4G     0 100% /mnt/ephemeral/kubernetes
tmpfs                                 748M     0  748M   0% /run/user/1000
```

```
/mnt/ephemeral/kubernetes$ sudo du
4	./kubelet/pods/c78ec9b6b03a20a64a85081486893ed5/containers/fluentd-elasticsearch
8	./kubelet/pods/c78ec9b6b03a20a64a85081486893ed5/containers
4	./kubelet/pods/c78ec9b6b03a20a64a85081486893ed5/plugins
4	./kubelet/pods/c78ec9b6b03a20a64a85081486893ed5/volumes
20	./kubelet/pods/c78ec9b6b03a20a64a85081486893ed5
36	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/containers/heapster
40	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/containers
4	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/plugins/kubernetes.io~secret/default-token-2mpaq
8	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/plugins/kubernetes.io~secret
12	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/plugins
8	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~secret/default-token-2mpaq
12	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~secret
16	./kubelet/pods/98fa50b7-507b-11e5-82e3-0681648242af/volumes
4	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/plugins/kubernetes.io~secret/default-token-5ze85
8	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/plugins/kubernetes.io~secret
12	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/plugins
8	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/volumes/kubernetes.io~secret/default-token-5ze85
12	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/volumes/kubernetes.io~secret
16	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af/volumes
40	./kubelet/pods/e8fac0e0-507d-11e5-82e3-0681648242af
4	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/containers/influxdb
4	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/containers/grafana
12	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/containers
4	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/plugins/kubernetes.io~secret/default-token-2mpaq
8	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/plugins/kubernetes.io~secret
12	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/plugins
8	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~secret/default-token-2mpaq
12	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~secret
12	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/raft/snapshot
28	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/raft
4	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/wal
3340	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/db/shard_db_v2/00001
1428620	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/db/shard_db_v2/00002
1431964	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/db/shard_db_v2
1431968	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage/db
1432004	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir/influxdb-persistent-storage
1432008	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes/kubernetes.io~empty-dir
1432024	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af/volumes
1432052	./kubelet/pods/992fb63a-507b-11e5-82e3-0681648242af
1432268	./kubelet/pods
4	./kubelet/plugins
1432280	./kubelet
16	./lost+found
1432300	.

```

**Comment by ArtfulCoder** [comment] 2015-09-02 22:00
@saad-ali

**Comment by saad-ali** [comment] 2015-09-02 22:08
Looks like InfluxDB slowly eats up all the disk space.
+@kubernetes/goog-node

**Comment by vishh** [comment] 2015-09-02 23:04
We are starting to work on Disk Space accounting and limiting. For now, I'd
suggest running InfluxDB with a volume and configuring it to store less
data.

**Comment by justinsb** [comment] 2015-09-06 15:12
The root cause here is that (on aufs) we assign a very small partition to "kubernetes" (my screw up), and this is the volume that backs host-volumes, as used by influx and elasticsearch.

I'm looking at ways to make this better.  Ideas (so far):
* repoint the influx & ES manifests to work with volumes;
* change the size of the partition
* making host-volumes draw from the bigger docker
* get rid of the docker/kubernetes volume split altogether

**Comment by ngbinh** [comment] 2015-09-10 10:54
we got hit by this issue. I think 
> repoint the influx & ES manifests to work with volumes;
is the right solution here. Is there a way to do so now?

**Comment by justinsb** [comment] 2015-09-10 14:07
I think that just having one big ephemeral volume is probably the easier short-term fix; I just propose a PR for that: #13803

If this looks good we can cherry-pick this also.

I think we should also consider putting influx & ES onto persistent volumes, though that isn't specific to AWS!

**Comment by jtbcgdv** [comment] 2015-09-10 14:13
@justinsb that's the approach we're looking at using.  mount a persistent volume on the kubernetes minions

**Comment by ngbinh** [comment] 2015-09-10 15:51
@justinsb thanks. I will try the fix tomorrow.

**Comment by justinsb** [comment] 2015-09-21 14:56
I think we should put influx & elasticsearch on a persistent volume (#14274), but I believe I fixed my mistake which was creating a very small volume which filled up very quickly.  Closing, but feel free to reopen/comment if not fixed.

**Closed by justinsb** 2015-09-21 14:56 UTC
Labels: area/availability, area/platform/aws, area/reliability, team/node

**Comment by smugcloud** [comment] 2016-05-05 00:02
Hi @justinsb I believe this issue still persists in 1.2. I opened a new issue to track this but wanted to get your thoughts on the underlying problem. 

https://github.com/kubernetes/kubernetes/issues/25174
