### ISSUE TITLE
ManagedFields not updated when old manager clears status

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#120201] opened 2023-08-28 06:34 UTC
### What happened?

`kubectl get appwrappers -n test-kfp    lang-id-mc2 --watch -o yaml --show-managed-fields` produced the following (edited for relevance).

```
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  annotations:
    edge.kcp.io/downsynced: "true"
    kcp.io/cluster: 2hiptwa4c04b197k
  creationTimestamp: "2023-08-24T16:05:50Z"
  generation: 35989
  labels:
    edge.kcp.io/projected: "yes"
  managedFields:
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:edge.kcp.io/downsynced: {}
          f:kcp.io/cluster: {}
        f:labels:
          .: {}
          f:edge.kcp.io/projected: {}
      f:spec:
        .: {}
        f:priority: {}
        f:resources:
          .: {}
          f:GenericItems: {}
          f:Items: {}
          f:metadata: {}
        f:schedulingSpec:
          .: {}
          f:clusterScheduling:
            .: {}
            f:clusters: {}
          f:dispatchDuration: {}
          f:requeuing:
            .: {}
            f:growthType: {}
            f:maxNumRequeuings: {}
            f:maxTimeInSeconds: {}
            f:numRequeuings: {}
            f:timeInSeconds: {}
        f:service:
          .: {}
          f:spec: {}
      f:status: {}
    manager: syncer
    operation: Update
    time: "2023-08-24T16:05:50Z"
  name: lang-id-mc2
  namespace: test-kfp
  resourceVersion: "13559919"
  uid: 2784e532-02d1-457e-8926-afbd15472fdf
...

---
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  annotations:
    edge.kcp.io/downsynced: "true"
    kcp.io/cluster: 2hiptwa4c04b197k
  creationTimestamp: "2023-08-24T16:05:50Z"
  generation: 35990
  labels:
    edge.kcp.io/projected: "yes"
  managedFields:
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:edge.kcp.io/downsynced: {}
          f:kcp.io/cluster: {}
        f:labels:
          .: {}
          f:edge.kcp.io/projected: {}
      f:spec:
        .: {}
        f:priority: {}
        f:resources:
          .: {}
          f:GenericItems: {}
          f:Items: {}
          f:metadata: {}
        f:schedulingSpec:
          .: {}
          f:clusterScheduling:
            .: {}
            f:clusters: {}
          f:dispatchDuration: {}
          f:requeuing:
            .: {}
            f:growthType: {}
            f:maxNumRequeuings: {}
            f:maxTimeInSeconds: {}
            f:numRequeuings: {}
            f:timeInSeconds: {}
        f:service:
          .: {}
          f:spec: {}
      f:status: {}
    manager: syncer
    operation: Update
    time: "2023-08-24T16:05:50Z"
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:controllerfirsttimestamp: {}
        f:filterignore: {}
        f:queuejobstate: {}
        f:sender: {}
        f:systempriority: {}
        f:targetClusterName: {}
    manager: Go-http-client
    operation: Update
    time: "2023-08-28T05:33:45Z"
  name: lang-id-mc2
  namespace: test-kfp
  resourceVersion: "13560151"
  uid: 2784e532-02d1-457e-8926-afbd15472fdf
...

---
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  annotations:
    edge.kcp.io/downsynced: "true"
    kcp.io/cluster: 2hiptwa4c04b197k
  creationTimestamp: "2023-08-24T16:05:50Z"
  generation: 35991
  labels:
    edge.kcp.io/projected: "yes"
  managedFields:
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:edge.kcp.io/downsynced: {}
          f:kcp.io/cluster: {}
        f:labels:
          .: {}
          f:edge.kcp.io/projected: {}
      f:spec:
        .: {}
        f:priority: {}
        f:resources:
          .: {}
          f:GenericItems: {}
          f:Items: {}
          f:metadata: {}
        f:schedulingSpec:
          .: {}
          f:clusterScheduling:
            .: {}
            f:clusters: {}
          f:dispatchDuration: {}
          f:requeuing:
            .: {}
            f:growthType: {}
            f:maxNumRequeuings: {}
            f:maxTimeInSeconds: {}
            f:numRequeuings: {}
            f:timeInSeconds: {}
        f:service:
          .: {}
          f:spec: {}
      f:status: {}
    manager: syncer
    operation: Update
    time: "2023-08-24T16:05:50Z"
  name: lang-id-mc2
  namespace: test-kfp
  resourceVersion: "13560194"
  uid: 2784e532-02d1-457e-8926-afbd15472fdf
...

---
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  annotations:
    edge.kcp.io/downsynced: "true"
    kcp.io/cluster: 2hiptwa4c04b197k
  creationTimestamp: "2023-08-24T16:05:50Z"
  generation: 35992
  labels:
    edge.kcp.io/projected: "yes"
  managedFields:
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:edge.kcp.io/downsynced: {}
          f:kcp.io/cluster: {}
        f:labels:
          .: {}
          f:edge.kcp.io/projected: {}
      f:spec:
        .: {}
        f:priority: {}
        f:resources:
          .: {}
          f:GenericItems: {}
          f:Items: {}
          f:metadata: {}
        f:schedulingSpec:
          .: {}
          f:clusterScheduling:
            .: {}
            f:clusters: {}
          f:dispatchDuration: {}
          f:requeuing:
            .: {}
            f:growthType: {}
            f:maxNumRequeuings: {}
            f:maxTimeInSeconds: {}
            f:numRequeuings: {}
            f:timeInSeconds: {}
        f:service:
          .: {}
          f:spec: {}
      f:status: {}
    manager: syncer
    operation: Update
    time: "2023-08-24T16:05:50Z"
  - apiVersion: mcad.ibm.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:controllerfirsttimestamp: {}
        f:filterignore: {}
        f:queuejobstate: {}
        f:sender: {}
        f:systempriority: {}
        f:targetClusterName: {}
    manager: Go-http-client
    operation: Update
    time: "2023-08-28T05:34:06Z"
  name: lang-id-mc2
  namespace: test-kfp
  resourceVersion: "13560303"
  uid: 2784e532-02d1-457e-8926-afbd15472fdf
...
```

It goes on like this, flapping between having one and two entries in the `metadata.managedFields` array.  But when there is only one entry, it does not hold the timestamp of the latest update, rather it stays fixed at the creation timestamp.

### What did you expect to happen?

Every update causes some entry in the ManagedFields array to have a later timestamp.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure.

### Anything else we need to know?

This is an OpenShift 4.13.5_1528 cluster.

### Kubernetes version

<details>

```console
mspreitz@mjs13 ~ % kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.13", GitCommit:"5244794d27b4cc68290bc496b00e248857ac8b47", GitTreeState:"clean", BuildDate:"2023-08-24T00:01:27Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+f245ced", GitCommit:"cbbd0bdba10e0b612e32cdeb6462daa6909df4be", GitTreeState:"clean", BuildDate:"2023-07-13T17:06:24Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
IBM
</details>

### OS version

<details>

Client is MacOS 13.5.1.
Server is OpenShift usual, a RedHat OS.

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MikeSpreitzer** [comment] 2023-08-28 06:35
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment] 2023-08-28 12:29
I wonder if #110058 was incomplete.

**Comment by apelisse** [comment] 2023-08-29 20:47
> It goes on like this, flapping between having one and two entries in the metadata.managedFields array. But when there is only one entry, it does not hold the timestamp of the latest update, rather it stays fixed at the creation timestamp.

What does the system do that would make the entries flap? I'm unsure how to reproduce.
Thanks for reporting!

**Comment by apelisse** [comment] 2023-09-11 20:24
So if the first controller (the one who creates) sets and owns a set of field `a`, it will have an entry in the list. Then a second controller starts setting a  set of field `b`, it'll have an entry in the list with these fields. if the first, creating controller overrides ALL of the values in `b` (i.e. if `a` was a superset of `b`), then the fieldmanager will be entirely removed since the second controller won't own any fields anymore.

In this case it's a CRD, and the fields of the second controllers are in status. How can it even own `f:status` is very weird to me.

**Comment by jpbetz** [comment] 2024-09-13 01:44
I believe this is fixed by https://github.com/kubernetes/kubernetes/pull/125263

If anyone is still able to reproduce on Kubernetes 1.31+, please reopen with reproduction.

/close

**Closed by jpbetz** 2024-09-13 01:44 UTC
Labels: kind/bug, sig/api-machinery, triage/accepted
