### ISSUE TITLE
Creating pod with empty argument crashes kubectl

### ISSUE THREAD

**Issue by kichik** [kubernetes/kubernetes#26927] opened 2016-06-07 01:35 UTC
`kubectl` crashes when creating a pod with one or more empty arguments. This also happens when creating a deployment with this as a pod spec.

I'm using v1.2.3.

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

I was able to get a similar crash with `kubectl` 1.2.4.

```bash
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

```bash
$ kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - echo
    - hello
    -
    - world

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x8386fb]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x0, 0x0, 0xc2081fc3a0, 0x1a, 0xc208587d88, 0x6, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:247 +0x198b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x11677e0, 0xc2082b7fc0, 0xc2081fc300, 0x17, 0xc208587dc0, 0x5, 0xc208462750, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:264 +0xa7b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843ced0, 0xc2081fc2a0, 0x13, 0xc20848d050, 0xc, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x118cbe0, 0xc20843ced0, 0xc2081fc200, 0x12, 0xc20848d050, 0xc, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:237 +0xe0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x11677e0, 0xc2081fc020, 0xc20843a590, 0xf, 0xc20848d070, 0x5, 0xc2084626c0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:264 +0xa7b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843cea0, 0xc20843a579, 0x5, 0xc208613320, 0xa, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x118cbe0, 0xc20843cea0, 0xc20842b8f4, 0x4, 0xc208613320, 0xa, 0xc208462630, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:237 +0xe0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843ce40, 0x0, 0x0, 0xc20843a498, 0x6, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateBytes(0xc20811c480, 0xc20806d130, 0xa6, 0xb0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:163 +0x89a
k8s.io/kubernetes/pkg/kubectl/cmd/util.getSchemaAndValidate(0x7fc7b327ee30, 0xc2081e86c0, 0xc20806d130, 0xa6, 0xb0, 0x1621220, 0x3, 0x1637ce0, 0x2, 0xc2081fda40, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:757 +0x407
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*clientSwaggerSchema).ValidateBytes(0xc2082033b0, 0xc20806d130, 0xa6, 0xb0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:819 +0xf41
k8s.io/kubernetes/pkg/kubectl/resource.ValidateSchema(0xc20806d130, 0xa6, 0xb0, 0x7fc7b327ea20, 0xc2082033b0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:213 +0x1f4
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc20810b3c0, 0xc2081a85c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:481 +0x2e0
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc2081a83e0, 0xc2081a85c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:441 +0x12e
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc208116fe0, 0x1, 0x1, 0xc2081a8560, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:198 +0x17e
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc2081a8420, 0xc2081a8560, 0x0, 0x0)
        <autogenerated>:100 +0xbd
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x7fc7b327eba0, 0xc2081a8420, 0xc20810aec0, 0xc2081a8520, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:361 +0x10b
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc2081a8480, 0xc2081a8520, 0x0, 0x0)
        <autogenerated>:117 +0xbd
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x7fc7b327ebc8, 0xc2081a8480, 0xc2081a84c0, 0x3, 0x4, 0xc2081a8500, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:269 +0x110
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc208203c50, 0xc2081a8500, 0x0, 0x0)
        <autogenerated>:138 +0xbc
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x7fc7b327ebf0, 0xc208203c50, 0xc208203c80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:296 +0x171
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc208117020, 0xc208203c80, 0x0, 0x0)
        <autogenerated>:133 +0xbb
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc208201f80, 0xc208203c80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:79 +0x73
k8s.io/kubernetes/pkg/kubectl/cmd.RunCreate(0xc208162960, 0xc208122000, 0x7fc7b3278030, 0xc208046008, 0xc20801ee80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:143 +0x743
k8s.io/kubernetes/pkg/kubectl/cmd.func·012(0xc208122000, 0xc2081a9200, 0x0, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:66 +0x107
github.com/spf13/cobra.(*Command).execute(0xc208122000, 0xc2081a90a0, 0x2, 0x2, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc20806b600, 0xc208122000, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc20806b600, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e6b160)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2081c73a0, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081c73a0, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081c7340, 0xc2081e2000, 0x1000, 0x1000, 0x0, 0x7fc7b3278378, 0xc208117038)
        /usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208046418, 0xc2081e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc7b327e1e0, 0xc208046418, 0xc20806ce18, 0xc2081e2000, 0x1000, 0x1000, 0x1309f20, 0x0, 0x0)
        /usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081c9800, 0xc2081e2000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20819fb60)
        /usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20819fb60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806cdc0)
        /usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [select]:
net/http.(*persistConn).writeLoop(0xc20806cdc0)
        /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by asalkeld** [comment] 2016-06-07 01:55
I can take this one.

**Comment by asalkeld** [comment] 2016-06-07 02:02
This looks like a duplicate of #20627

**Comment by dims** [comment] 2016-06-07 14:16
@asalkeld - Ah. so this can be closed.

**Comment by eparis** [comment] 2016-06-07 14:21
closing as a dup of #20627

**Closed by eparis** 2016-06-07 14:21 UTC
