### ISSUE TITLE
Requests to a service with no local endpoints are dropped rather than ICMP rejected

### ISSUE THREAD

**Issue by chenlin2001** [kubernetes/kubernetes#121371] opened 2023-10-19 19:24 UTC
### What happened?

When setting internalTrafficPolicy: Local and see what happens when there are no available pods on the specific node:I exec into a pod on a specific node and ran the curl command:
curl micronaut-k8-sample:8080/stickiness/5 and got:
curl: (28) Failed to connect to micronaut-k8-sample port 8080 after 129261 ms: Couldn’t connect to server
(This api succeeds when running on a node that there are available pods of for service micronaut-k8-sample)
It's timing out according to the client timeout, and not getting an immediate rejection 

### What did you expect to happen?

An ICMP rejection that service is not available

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a service with internalTrafficPolicy:  Local. 
2. Have 2 nodes, and deployment with node affinity so no pods are available on one of the nodes.
3.  Exec into a pod on the node that doesn't have the pod and curl to that service 

### Kubernetes version

1.2.6

### Cloud provider

EKS

**Comment by thockin** [comment] 2023-10-19 20:11
pkg/proxy/iptables/proxier.go:

```
1029         if !hasEndpoints {
1030             // The service has no endpoints at all; hasInternalEndpoints and
1031             // hasExternalEndpoints will also be false, and we will not
1032             // generate any chains in the "nat" table for the service; only
1033             // rules in the "filter" table rejecting incoming packets for
1034             // the service's IPs.
1035             internalTrafficFilterTarget = "REJECT"
1036             internalTrafficFilterComment = fmt.Sprintf(`"%s has no endpoints"`, svcPortNameString)
1037             externalTrafficFilterTarget = "REJECT"
1038             externalTrafficFilterComment = internalTrafficFilterComment
1039         } else {
1040             if !hasInternalEndpoints {
1041                 // The internalTrafficPolicy is "Local" but there are no local
1042                 // endpoints. Traffic to the clusterIP will be dropped, but
1043                 // external traffic may still be accepted.
1044                 internalTrafficFilterTarget = "DROP"
1045                 internalTrafficFilterComment = fmt.Sprintf(`"%s has no local endpoints"`, svcPortNameString)
1046                 serviceNoLocalEndpointsTotalInternal++
1047             }                                                                                                                                                                                        
1048             if !hasExternalEndpoints {
1049                 // The externalTrafficPolicy is "Local" but there are no
1050                 // local endpoints. Traffic to "external" IPs from outside
1051                 // the cluster will be dropped, but traffic from inside
1052                 // the cluster may still be accepted.
1053                 externalTrafficFilterTarget = "DROP"
1054                 externalTrafficFilterComment = fmt.Sprintf(`"%s has no local endpoints"`, svcPortNameString)
1055                 serviceNoLocalEndpointsTotalExternal++
1056             }
1057         }
```

If there are no endpoints at all, we do an ICMP reject, but if there are no policy-satisfying endpoints we drop. 

@danwinship do you recall why?

**Comment by danwinship** [comment] 2023-10-20 01:21
The decision to make it work that way predates me, but my understanding is:

There is necessarily a race condition between when kube-proxy stops accepting connections for the service, and when the Load Balancer re-queries the HealthCheckNodePort and _notices_ that kube-proxy has stopped accepting connections for the service. During that time, it's possible that a client will try to connect to the service, and the LB will route it to a node that is no longer accepting connections for it. If we REJECT the packet, and the LB passes that REJECT back to the client, then the client fails with "can't connect". Whereas if we just DROP the packet then the client's TCP stack (or userspace UDP code) will eventually retry, and hopefully the next time the LB will have updated its endpoint set, and send the connection to a valid node, and it just looks to the client like the service was slow to respond or there was a momentary glitch in the internet.

(Previous discussion [here](https://github.com/kubernetes/kubernetes/pull/106497#discussion_r835673633), in the context of syncing the iTP and eTP behavior. @aojea suggested that clients should just retry on error, but there's a difference between this case (where you'd want to retry immediately) and the cases where we currently actually do REJECT (where you'd want to retry *eventually*, because there is legitimately something wrong with the service right now and if you try again it's just going to fail again).)

But of course, this all predates ProxyTerminatingEndpoints, and at this point, as long as the LB re-checks HealthCheckNodePorts more frequently than your pod termination grace period, then there's actually no race condition...

**Comment by uablrek** [comment] 2023-10-20 07:02
/cc @aroradaman 

For proxy-mode=ipvs it might not be so simple to return an ICMP reject.

The use of "drop" is also documented at several places and how HealthCheck shall be used to direct traffic to nodes with local pods, e.g. [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport).

@chenlin2001 Is there a real use-case where this is a problem? Or is it just when doing tests?

IMO this is a documented and intended behavior, and not a bug. To alter it would be a feature request and should be well motivated.

**Comment by chenlin2001** [comment] 2023-10-20 07:09
Hi, yes, this is a real use case. I want to implement "local first" approach - try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node (will then go through external load balancer, to make sure it will pick an endpoint). This is possible if I get an immediate rejection, but if it's just dropped and I have to wait for client timeout this is much more problematic, and not sure I can do it.
In addition I would suggest adding to https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/ documentation about dropping also in addition to the existing documentation about NodePort. My use case is service with ClusterIp and internalTransferPolicy, as those are not the same use cases

**Comment by thockin** [comment] 2023-10-20 22:33
> I want to implement "local first" approach - try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node

@robscott one more vote for "PreferLocal"

@uablrek Is IPVS similar to the above (REJECT when no endpoints at all) or does it DROP there, too?

Even though I think this use-case is better handled with a PreferLocal, I do kind of lean towards REJECT as a better answer, when possible and safe.

**Comment by uablrek** [comment] 2023-10-21 06:24
> Is IPVS similar to the above (REJECT when no endpoints at all) or does it DROP there, too?

Um, it turns out that "PreferLocal" is already implemented in proxy-mode=ipvs.

To test I create a deployment with affinity for some nodes, and access them from a node where no server PODs are started:
```
vm-002 ~ # kubectl get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
tserver-86ccfcf6f5-cnktc   1/1     Running   0          5m59s   11.0.4.3   vm-004   <none>           <none>
tserver-86ccfcf6f5-fsw8r   1/1     Running   0          5m59s   11.0.3.2   vm-003   <none>           <none>
tserver-86ccfcf6f5-h2prg   1/1     Running   0          5m59s   11.0.4.2   vm-004   <none>           <none>
tserver-86ccfcf6f5-pc2dq   1/1     Running   0          5m59s   11.0.3.3   vm-003   <none>           <none>
```
With proxy-mode=iptables:
```
vm-002 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 40
Failed reads; 0
vm-003 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-pc2dq 27
tserver-86ccfcf6f5-fsw8r 13
```
With proxy-mode=ipvs:
```
vm-002 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-rvq8q 10
tserver-86ccfcf6f5-cztbt 10
tserver-86ccfcf6f5-qbsf8 10
tserver-86ccfcf6f5-szr52 10
vm-003 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-rvq8q 20
tserver-86ccfcf6f5-szr52 20
```
The example above is from the main netns on the nodes, but the result is the same when doing it from within a POD on the nodes.

**Comment by thockin** [comment] 2023-10-23 06:08
Well that's....not right. :)

Is that intentional somewhere?

**Comment by uablrek** [comment] 2023-10-23 06:18
> Well that's....not right. :)

Ok, but why drop? The src (pod-address) is preserved in any case and `externalTrafficPolicy: Local` works as "PreferLocal". I was not involved implementing internalTrafficPolicy for proxy-mode=ipvs, but my guess is that the same code as for `externalTrafficPolicy: Local` was re-used.

**Comment by uablrek** [comment] 2023-10-23 06:55
> try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node (will then go through external load balancer, to make sure it will pick an endpoint)

@chenlin2001 How will this work exactly? A try from a POD to the clusterIP doesn't work (drop or rejected), then what? Will it fall-back to a loadBalancerIP for the same service? If so, please use loadBalancerIP with `externalTrafficPolicy:Local` always. It will do exactly what you want automatically, and without performance penalty (no round-trip to an external LB)

**Comment by chenlin2001** [comment] 2023-10-23 07:07
My setup is built to work on both Kubernetes on prem and on eks. I have a Traefik load balancer with following rule:
```
{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "micronaut-k8-sample.fullname" . }}
  labels:
{{ include "micronaut-k8-sample.labels" . | indent 4 }}
{{- with .Values.ingressroute.annotations }}
annotations:
  {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingressroute.host }}`)
      kind: Rule
      services:
        - name: {{ include "micronaut-k8-sample.fullname" . }}
          port: {{ int .Values.ingressroute.port }}
          kind: Service
{{- end }}
```
And the service is configured:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "micronaut-k8-sample.fullname" . }}
  labels:
    {{- include "micronaut-k8-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.management.port }}
      targetPort: {{ .Values.management.port }}
      protocol: TCP
      name: management
  internalTrafficPolicy: Local
  selector:
    {{- include "micronaut-k8-sample.selectorLabels" . | nindent 4 }}
```
So my service itself is ClusterIp, and not LoadBalancer/NodePort so I can't use the externalTrafficPolicy:Local option

**Comment by thockin** [comment] 2023-10-23 15:56
@uablrek 

> Ok, but why drop? The src (pod-address) is preserved in any case and externalTrafficPolicy: Local works as "PreferLocal"

I'm not sure how eTP:Local can forward to a non-local pod and preserve the original IP, unless DSR, which doesn't work in all environments?

The main "why" is "that's how we specced it".  It's a policy decision.  For eTP:Local, it impacts latency, health-checking, resource usage (half as many conntracks), and source-IP retention.  Someone who configures eTP:Local made an explicit choice.  Likewise, for iTP:Local, it's potentially a correctness issue - I need to talk to the agent on my node, and forwarding me off-node is not valid.

We're looking at PreferLocal as a topology heuristic, rather than a policy

**Comment by thockin** [comment] 2023-10-23 16:00
> So overall, DROP wins.

I'm not following - do we think that it's better for TCP stacks to wait O(minutes) and auto-retry rather than telling clients that they should catch failures and retry more quickly?  I suspect clients will institute timeouts, so they will end up retrying themselves anyway.  Am I missing something?

**Comment by uablrek** [comment] 2023-10-23 16:09
> I'm not sure how eTP:Local can forward to a non-local pod and preserve the original IP, unless DSR, which doesn't work in all environments?

Sorry, I mean when a loadBalancerIP is accessed from a POD on the local cluster. Then it's not necessary to have local endpoints, the connect will be distributes in the same way as for eTP:Cluster. But since the src is "internal", i.e. a POD ip no snat is done

**Comment by thockin** [comment] 2023-10-26 16:39
Discussing on sig-net call today.  

It seems reasonable that internal no-endpoint connects would fast-fail - that seems agreeable, but should external still drop?

The code above already REJECTs external traffic, but only when there really are no endpoints.  If an etp:local LB picks a node with no endpoints, for whatever reason, is a reject appropriate?  On one hand, the LB made a "bad" choice.  On the other this could appear to be an info leak or semantic problem, so is less obvious.

**Comment by danwinship** [comment] 2024-02-01 21:44
> > So overall, DROP wins.
> 
> I'm not following - do we think that it's better for TCP stacks to wait O(minutes) and auto-retry 

They won't wait O(minutes); if they get no response to the initial SYN, they'll retry in 1 second, then 2 seconds, then 4 seconds (or however it goes).

> rather than telling clients that they should catch failures and retry more quickly?

Users should not _expect_ that healthy Kubernetes Services will sometimes reject their connections for no externally-apparent reason. If you connect to a Service and get "connection refused", that ought to be a reliable indication that something is actually wrong with the Service (or cluster, or Internet), and retrying right away won't help.

(At any rate, as I said above, with ProxyTerminatingEndpoints, the race condition goes away anyway, as long as your LBs are repolling endpoint health frequently enough. So now, nobody gets the 1/2/4/etc second delay, _and_ when the service actually fails, nobody has modified their clients to spam the LBs with doomed retries.)

**Comment by thockin** [comment] 2024-02-01 22:08
>> I'm not following - do we think that it's better for TCP stacks to wait O(minutes) and auto-retry
>
> They won't wait O(minutes); if they get no response to the initial SYN, they'll retry in 1 second, then 2 seconds, then 4 seconds (or however it goes).

OK, the TCP stack knows, but a client application doesn't - it will wait for O(minutes).

> with ProxyTerminatingEndpoints, the race condition goes away anyway, as long as...

That doesn't what should happen in the edge cases.

Looking back at this thread https://github.com/kubernetes/kubernetes/issues/121371#issuecomment-1771637582 still feels bad to me.  "If there are no endpoints at all, we do an ICMP reject, but if there are no policy-satisfying endpoints we drop."

I think that internal inconsistency is kind of gross.  If the abstraction is "you have reached the service, but there are no endpoints for you right now" then reject still seems right (at least for internal use).

External is more subtle.

**Comment by danwinship** [comment] 2024-02-02 13:57
> > > I'm not following - do we think that it's better for TCP stacks to wait O(minutes) and auto-retry
> > 
> > 
> > They won't wait O(minutes); if they get no response to the initial SYN, they'll retry in 1 second, then 2 seconds, then 4 seconds (or however it goes).
> 
> OK, the TCP stack knows, but a client application doesn't - it will wait for O(minutes).

No, the theory is that the TCP stack retries, and the LB treats each retry independently (since it doesn't create conntrack-records-or-equivalent until a connection actually succeeds) and so, eg, given 3 endpoints where only 1 of them is bad, each retry has a 2/3 chance of being routed to a live endpoint and succeeding, so (assuming I got the retry intervals right before) there's an 89% of chance of a successful connection within 3 seconds and a 97% chance of a successful connection within 7 seconds.

> reject still seems right (at least for internal use)

Yeah, there's really no particular motivation for the Internal behavior other than "let's be consistent with external". Well, and it was simpler to implement for the case of a service that is both iTP:Local and eTP:Local.

**Comment by thockin** [comment] 2024-02-02 17:01
For internal (client on node A tries to hit service with iTP:Local) whether it REJECTs or DROPs, the retries are unlikely to matter if there are no local endpoints.  If a client cares about a "fast" connection, they have to implement a timeout themselves, because even if an enpoint exists it might be slow.  If the client doesn't care (is willing to wait), then DROP is better because it *might* ride out a very temporary situation (e.g. mid-restart).

So the only argument for REJECT is if we want to make that part of the defined "API" to services - that ICMP reject means "no endpoints".

For external it's more tricky because we don't know if the ICMP will go to the LB or the oiginal client, and if the B how that will be interpretted.  Same argument applies wrt timeouts and the client, right?  So DROP is pretty clearly better for external, I think.

If I am tracking you, Dan, I am coming around.  It still feels wronng to REJECT sometimes and DROP others.  The question is - do we want to make REJECT part of the kube contract for internal, or make it part of the kube-proxy impl contract, change it all to DROP, or leave it because "back compat" (in which case we should comment the code as such).

We should also capture the argument completely for future readers (us, likely) when this comes up again.

**Comment by danwinship** [comment] 2024-02-05 17:46
> If the client doesn't care (is willing to wait), then DROP is better because it _might_ ride out a very temporary situation (e.g. mid-restart).

Right! OK, so there was another argument here, which is that:
1. A client that wants to connect to an iTP:Local service needs to be deployed to a node that has an endpoint for that service. You can't just deploy your client to a random node and expect it to work reliably.
2. So if a client tries to connect to an iTP:Local service, and there are no local endpoints, one of two things must be true:
   1. The client was deployed correctly, and there is _supposed to_ be a local endpoint, but it's currently unavailable (in which case, DROP is the better option since it will presumably come back soon).
   2. The client was deployed incorrectly, to a node that was never supposed to have an endpoint for this service (in which case REJECT is the better option since no endpoint is coming).
3. Since we can only pick one answer, we decide to assume that the client was being well-behaved and got unlucky, rather than assuming that the client was being stupid and doing something that shouldn't have worked anyway.
4. Therefore we should DROP rather than REJECT because the endpoint is probably just restarting and will be back soon.

This bug report is essentially an objection to point 1. I'm not convinced it's a _valid_ objection, since we don't claim that you ought to be able to implement "PreferLocal" on top of Local.

An alternative objection to this is to say that while the _client_ didn't do anything wrong in 2.i, the _service owner_ did; if they had wanted the service to keep working through the endpoint restart, they could have deployed a second endpoint to ensure its continued availability. Since they didn't do that, we should assume that they are OK with clients getting "connection refused" (ie, REJECT).

----

Anyway, if we want to make the change, it's easy, https://github.com/danwinship/kubernetes/commit/ef85e1223bdc6b1c637397935c76afde2d5d4db5

**Comment by thockin** [comment] 2024-02-06 04:16
...or should it always DROP and not REJECT?

**Comment by aroradaman** [comment] 2024-02-06 04:22
Maybe allow the user to configure this in the kube-proxy `v1alpha2` configuration?

**Comment by thockin** [comment] 2024-02-06 04:27
nooooooo! Every config we offer costs us complexity.  Less config, more
opinion.  PLEASE.

**Comment by aojea** [comment] 2024-02-06 21:05
> If an etp:local LB picks a node with no endpoints, for whatever reason, is a reject appropriate? On one hand, the LB made a "bad" choice. On the other this could appear to be an info leak or semantic problem, so is less obvious.

this is not a valid case etp:local LB should use the healtcheckNodePort before sending traffic, and as Dan said the possible race was fixed with terminating endpoints

IMHO `connection refused` or `reject` should be part of the contract of a connection to ClusterIP without endpoints (only for intra cluster traffic), because that IP is internal and it will inform the application that no endpoints are present at that point in time.
This also helps a lot to troubleshoot pod issues that depend on Services, because the message error is easy to reason about or for developers to build resilient applications, instead of relying on the TCP stack that you have too google each time how it works.
I don't like to DROP because it can be caused also by a firewall or network policy issues.
It also seems REJECT is also implemented by other projects like cilium https://github.com/cilium/cilium/pull/28157

For the external use case, I'm now more convinced by Dan arguments, as sending icmp errors through middleboxes can make more harm than benefit, and DROP is good.

My vote, is REJECT internal DROP external for Services without endpoints

**Closed** 2024-07-05 22:35 UTC
Labels: kind/bug, sig/network, lifecycle/rotten, needs-triage
