### ISSUE TITLE
rkt: systemctl restart doesn't tell rktnetes that a pod fails to start

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25242] opened 2016-05-06 01:51 UTC
I was testing the selinux support #24901 manually today by creating pods with good and bad selinux options.
And when I gave the pod bad selinux options, I expected the pod to fail.
However I saw the pod stuck in `ContainerCreating` state, even though the restart policy is no.

```
$ cat $ cat selinuxpod 
# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  nodeName: yifan-rkt-selinux-minion-164e
  securityContext:
    seLinuxOptions:
      user: system_u
      role: system_r
      type: kernel_t
      level: s1
  containers:
  - name: busybox
    image: busybox
    command:
      - cat
      - /tmp/hello
    volumeMounts:
    - name: hello
      mountPath: /tmp/hello
  restartPolicy: Never
  volumes:
  - name: hello
    hostPath:
      path: /tmp/hello

$ kubectl get pods --show-all
NAME      READY     STATUS              RESTARTS   AGE
busybox   0/1       ContainerCreating   0          8m

$ kubectl get events
7m          7m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id 487f0158
7m          7m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id 487f0158
6m          6m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id 60158324
6m          6m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id 60158324
5m          5m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id ae4f425d
5m          5m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id ae4f425d
3m          3m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id cd0aee69
3m          3m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id cd0aee69
2m          2m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id 40d55d04
2m          2m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id 40d55d04
1m          1m         1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id 7cde9747
1m          1m         1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id 7cde9747
20s         20s        1         busybox   Pod       spec.containers{busybox}   Normal    Created   {kubelet yifan-rkt-selinux-minion-164e}   Created with rkt id 77cfcf96
20s         20s        1         busybox   Pod       spec.containers{busybox}   Normal    Started   {kubelet yifan-rkt-selinux-minion-164e}   Started with rkt id 77cfcf96

```

On the node, I saw the pod is prepared, but not running, this means the systemd fails to start it:

```
$ sudo /opt/rkt/rkt list
UUID        APP         IMAGE NAME                      STATE       CREATED     STARTED     NETWORKS
40d55d04    busybox         registry-1.docker.io/library/busybox:latest     prepared    4 minutes ago   
60158324    busybox         registry-1.docker.io/library/busybox:latest     prepared    8 minutes ago           
77cfcf96    busybox         registry-1.docker.io/library/busybox:latest     prepared    2 minutes ago       
```

Also the journal log of the service:

```
$ sudo systemctl cat k8s_40d55d04-9963-43b9-85b5-566cb20f701c.service
# /run/systemd/system/k8s_40d55d04-9963-43b9-85b5-566cb20f701c.service
[Service]
ExecStart=/opt/rkt/rkt --insecure-options=image,ondisk --local-config=/etc/rkt --system-config=/usr/lib/rkt --dir=/var/lib/rkt run-prepared --net=kuben
ExecStopPost=/usr/bin/touch /var/lib/kubelet/pods/e9461039-132a-11e6-8403-42010af00002/finished-40d55d04-9963-43b9-85b5-566cb20f701c
KillMode=mixed
SELinuxContext=system_u:system_r:kernel_t:s1

$ sudo journalctl -u k8s_40d55d04-9963-43b9-85b5-566cb20f701c.service
-- Logs begin at Fri 2016-05-06 00:35:20 UTC, end at Fri 2016-05-06 01:47:07 UTC. --
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: Stopped k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service.
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: Started k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service.
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service: Main process exited, code=exited, status=229/SELINUX_CONTEXT
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service: Control process exited, code=exited status=229
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service: Unit entered failed state.
May 06 01:37:15 yifan-rkt-selinux-minion-164e systemd[1]: k8s_60158324-2b07-4c46-b1c1-5d5d0d2202f9.service: Failed with result 'exit-code'.
```

My question is, since the restart policy is "Never", why I keep seeing the pods being restarted?

Will dig into this further.

cc @euank @sjpotter

**Comment by yifan-gu** [comment] 2016-05-06 18:27
So turns out because the API service doesn't return the pod as it cannot find the UUID (https://github.com/coreos/rkt/issues/2502), so kubelet thinks it's not started, thus keeps restarting it.

**Comment by yujuhong** [comment] 2016-05-07 00:51
yes, kubelet needs to see the dead body to be convinced that the pod failed, due to the lack of other proof.

**Comment by yifan-gu** [comment] 2016-05-17 02:35
So this is fixed by rkt 1.6. But the pod is still restarting, as the container is in unknown state (because it's prepared, not running or exited), so [ShouldContainerBeRestarted()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/helpers.go#L64-L65) always returns true.

We might want to revisit this logic later cc @Random-Liu , but I am moving this off rktnetes 1.0 now.

**Comment by spzala** [comment] 2017-08-09 15:16
@yifan-gu hi, just wondering since it's over a year this issue was last discussed. Also, per your last comment I see the problem is partially solved and it was decided to revisit this after sometime.. so just a gentle touch base to see if you still think it's an issue or we can close it? Thanks!

**Comment by yujuhong** [comment] 2018-02-07 19:37
rktnetes has been deprecated. Closing

**Closed by yujuhong** 2018-02-07 19:37 UTC
Labels: lifecycle/rotten, sig/node
