### ISSUE TITLE
kubectl watch does not support server-print

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#66642] opened 2018-07-26 04:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
If creating a crd xxx with additionalPrinterColumns, running `kubectl get xxx --watch` only returns "Name Age". 

**What you expected to happen**:
same as `kubectl get` command, `kubectl get --watch` should also use server side printing by default. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a crd with additionalPrinterColumns, and run kubectl get --watch 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment] 2018-08-08 11:57
Dupe of https://github.com/kubernetes/kubernetes/issues/66538. Will continue the discussion there.

@qiujian16 Thanks for reporting this though! :+1: 

/close

**Closed by nikhita** 2018-08-08 11:57 UTC
Labels: kind/bug, sig/cli
