### ISSUE TITLE
Cannot create secrets from big (~6MiB) YAML file

### ISSUE THREAD

**Issue by jakubkulhan** [kubernetes/kubernetes#23125] opened 2016-03-17 15:34 UTC
I tried creating secrets [with Hunspell dictionaries for Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/hunspell.html). The dictionaries are quite big and serialized to Base64, they create about [6 MiB YAML file](https://github.com/kubernetes/kubernetes/files/178151/elasticsearch-config-hunspell.txt).

`kubectl` exists with this error in log:

```
I0317 16:20:06.268070    9870 decoder.go:144] decoding stream as YAML
F0317 16:20:06.268606    9870 helpers.go:107] bufio.Scanner: token too long
```

Tested with release 1.2.0.

**Comment by derekwaynecarr** [comment] 2016-03-17 20:14
There is a limit to the maximum size of a secret in bytes at 1 MiB.

**Comment by derekwaynecarr** [comment] 2016-03-17 20:15
What command did you use to create the secret?  Was it `kubectl create secret` subcommand?

**Comment by jakubkulhan** [comment] 2016-03-17 21:24
It was `kubectl create -f elasticsearch-config-hunspel.yml`, where `elasticsearch-config-hunspell.yml` is located [here](https://github.com/kubernetes/kubernetes/files/178151/elasticsearch-config-hunspell.txt) (Github does not allow `yml` file extension, so the uploaded file has been renamed to `txt`).

**Comment by AdoHe** [comment] 2016-03-20 15:16
@jakubkulhan I can see what's you problem, as for now we are using `bufio.Scanner` to split YAML documents in `pkg/util/yaml`, but bufio.Scanner cannot handle lines longer than 64KB (you'll get "bufio.Scanner: token too long"), in your case the line is more much longer than 64KB, I have fixed this on my local to use `reader.ReadLine()` instead of `bufio.Scanner`, I will open a PR tomorrow. Sorry about that, we should already fix this.

**Comment by AdoHe** [comment] 2016-03-21 03:43
@jakubkulhan I have open a PR #23265 ptal.

**Comment by smarterclayton** [comment] 2017-03-20 21:09
Dupe of https://github.com/kubernetes/kubernetes/issues/19603

**Closed by smarterclayton** 2017-03-20 21:09 UTC
Labels: sig/api-machinery
