### ISSUE TITLE
Federation build/deploy too dependent on google cloud

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#39870] opened 2017-01-13 15:45 UTC
**Kubernetes version** (use `kubectl version`):
master

**What happened**:
Attempting to build and deploy the federation images from the repo is heavily dependent upon google cloud.

**What you expected to happen**:
More flexibility in the build/deploy methods

**How to reproduce it** (as minimally and precisely as possible):
Follow http://kubernetes.io/docs/admin/federation/

**Comment by quinton-hoole** [comment] 2017-01-17 03:24
@rrati That process has been deprecated by the kubefed tool.  

https://kubernetes.io/docs/admin/federation/kubefed/

@madhusudancs Could you please make sure that the documentation is updated accordingly.

**Comment by marun** [comment] 2017-01-26 18:37
There has been some work done in the linked PRs.

**Comment by madhusudancs** [comment] 2017-01-26 19:58
@quinton-hoole yeah. Updating the existing documentation and marking the previous deployment mechanisms deprecated is planned for v1.6.

**Comment by rrati** [comment] 2017-01-26 20:27
@quinton-hoole This issue is relevant to current deploy/build mechanisms.

@madhusudancs This isn't a doc issue as problems still exist with new tools/methods.

**Comment by ethernetdan** [comment] 2017-03-13 22:50
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by madhusudancs** [comment] 2017-03-13 23:04
I would still like to keep this open. Feature work is done. We still need to update the documentation.

**Comment by ethernetdan** [comment] 2017-03-14 07:13
@madhusudancs okay, just be aware if it's in the milestone it will block the release

**Comment by madhusudancs** [comment] 2017-03-14 07:39
@ethernetdan last cycle we used `non-release-blocker` label to track issues like this and it worked pretty well. Can we use that this cycle too?

**Comment by nikhiljindal** [comment] 2017-03-14 18:01
Isnt this duplicate of https://github.com/kubernetes/kubernetes/issues/40536?

**Comment by madhusudancs** [comment] 2017-03-14 18:02
@nikhiljindal no it's not. See the comments above. Keeping it open for documentation.

**Comment by madhusudancs** [comment] 2017-03-14 18:05
Alright, I filed a documentation issue here https://github.com/kubernetes/kubernetes.github.io/issues/2809 and closing this one.

Too much book keeping.

**Closed** 2017-03-14 18:05 UTC
Labels: area/usability, non-release-blocker, sig/federation
