### ISSUE TITLE
e2e flake: Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17873] opened 2015-11-27 12:51 UTC
It failed in gce suite. I honestly have no idea under which team it falls: @bgrant0607 @thockin @ixdy @wojtek-t.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:46 Nov 27 02:50:59.145: Failed to find all 300 log lines
```

**Comment by gmarek** [comment] 2015-12-01 09:45
Another failure: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/837/

bumping to p0. @bgrant0607 - can you find an owner, or at least an appropriate team for this?

**Comment by bgrant0607** [comment] 2015-12-01 22:52
@kubernetes/goog-cluster owns logging (see team description).

**Comment by freehan** [comment] 2015-12-03 00:52
Cannot reproduce failure so far. Leaving it to run overnight...

**Comment by gmarek** [comment] 2015-12-03 08:00
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/847/

**Comment by freehan** [comment] 2015-12-05 01:30
Still cannot reproduce the exact failure... 
Increase verbosity... https://github.com/kubernetes/kubernetes/pull/18244

**Comment by wojtek-t** [comment] 2015-12-07 07:37
There were a lot of such failures over the weekend:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9772/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9771/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9770/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9766/

**Comment by gmarek** [comment] 2015-12-07 11:01
Moving this test to flaky (#18284), as it's only 66% stable and is blocking the build quite often: `Failed 10 times in the last 30 runs. Stability: 66 %`

@freehan please prioritize this.

**Comment by quinton-hoole** [comment] 2015-12-08 00:04
This test was passing 100% of the time until Build #9757 (Dec 5, 2015 4:13:38 PM).
After that, it failed 50% of the time (10 failures in 20 runs).  Clearly a PR that merged shortly before the above time introduced the flakyness.  That PR should be rolled back.

**Comment by wojtek-t** [comment] 2015-12-08 08:49
hmm - I looked into PRs that were merged around that time, and actually nothing looks suspicious to me

**Comment by freehan** [comment] 2015-12-08 23:15
This test is 100% successful in flaky test suite so far. I suspect some other e2e test is impacting this one. Adding more sanity checks...

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-flaky/8505/testReport/(root)/Kubernetes%20e2e%20suite/Cluster_level_logging_using_Elasticsearch_should_check_that_logs_from_pods_on_all_nodes_are_ingested_into_Elasticsearch/

**Comment by freehan** [comment] 2015-12-15 21:38
Let it in flaky suite overnight. If everything goes well, will unmark it.

**Comment by satnam6502** [comment] 2015-12-15 23:56
I can't follow any of the links but if I could get a bit more information about what is going wrong I could look into the Elasticsearch test if you think that is the issue rather than something else having a bad impact on it.

**Comment by freehan** [comment] 2015-12-16 01:12
@satnam6502 Thanks for offering to help. 

Here are the failure symptoms in Jenkins: 
1. ES cluster in red status. 
I bump into this once with my test cluster. It is cause by es split brain problem. Fix already merged. 
2. Missing all log lines from one node.
I cannot reproduce this. My guess is the fluentd pod on a node is not working properly. So I added validation for fluentd pods.

Can you think of anything else?

**Comment by satnam6502** [comment] 2015-12-16 01:48
Can you please point me to the fix for the split brain problem? Is that #18678 ? So that works by making sure there are always two master nodes? Is 2 really a good idea for quorum? As suggested here https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html a choice of 2 might not be desirable?
Missing log lines indeed mean a synthetic logging pod did not start for some reason -- without more log information it's hard to work out exactly why this occurred. If I get a moment I will try to do a repo.
Thanks.

**Comment by freehan** [comment] 2015-12-16 06:35
minimum_master_nodes set to 2 does not mean having 2 master nodes. It means the es cluster needs to have at least 2 nodes before electing a master. 
If network partition happened to a es non-master node, it will wait until it could reach out to at least one other node to start electing master. Hence it will prevent the split brain problem.

Based on the log in jenkins, all synthetic logging pod ran successfully.

**Comment by freehan** [comment] 2016-01-05 21:21
It gets flaky again... I am able to reproduce the problem by running DaemonRestart and Elasticsearch test together. It looks like the DaemonRestart test somehow disrupts the ES cluster. ES cluster gets into bad state, hence failing the es test. 

Confirmed with @yujuhong. This particular test restarts all the containers. 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/daemon_restart.go#L298

**Comment by yujuhong** [comment] 2016-01-05 22:14
> Confirmed with @yujuhong. This particular test restarts all the containers.

It's a recent regression. Found the cause and will upload a fix soon.

**Comment by gmarek** [comment] 2016-01-06 10:08
@yujuhong - please monitor this test and close this bug if there won't be any failures in some time.

**Comment by yujuhong** [comment] 2016-01-08 21:48
Test is green for the last 40 builds. Closing the issue.

**Comment by ihmccreery** [comment] 2016-01-30 00:57
This test is still marked as `[Flaky]` at `HEAD`.  @yujuhong please send a PR to promote it out of `[Flaky]`?

**Comment by yujuhong** [comment] 2016-01-30 01:35
Since @freehan is the owner of the issue. I'll let him decide whether the test is ready.

**Comment by freehan** [comment] 2016-01-30 02:36
The test has been successful lately. Want to add one more check to improve resilience. 

I had a pending PR to remove `Flaky` label. #18910 
Will try to merge it on Monday if everything goes well during the weekend.

**Comment by bprashanth** [comment] 2016-02-02 21:39
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26332/#

```
13:29:55 Feb  2 21:26:29.621: INFO: After 6m41.611116848s es still return duplicated log lines
13:29:55 Feb  2 21:26:54.627: INFO: pod 0: elasticsearch-logging-v1-cdmwo PodIP 10.245.2.3 phase Running condition [{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-02-02 21:17:53 +0000 UTC Reason: Message:}]
13:29:55 Feb  2 21:26:54.627: INFO: pod 1: elasticsearch-logging-v1-g0gaa PodIP 10.245.3.3 phase Running condition [{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-02-02 21:18:07 +0000 UTC Reason: Message:}]
13:29:55 Feb  2 21:26:54.685: INFO: After 7m6.675241628s expecting to find 600 log lines but saw 700
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20464/kubernetes-pull-build-test-e2e-gce/26332/

**Comment by freehan** [comment] 2016-02-02 22:11
I think that is because elasticsearch query return unexpect results. #20364 should solve it.

**Comment by bprashanth** [comment] 2016-02-02 23:31
Weirdly hit the same unrelated pr twice, but it looks like the fix just got merged
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26353/
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20464/kubernetes-pull-build-test-e2e-gce/26353/

**Comment by yujuhong** [comment] 2016-02-03 00:03
Still flaking:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10846/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10847/

**Comment by thockin** [comment] 2016-02-03 19:22
@freehan what's next on this?  Seems to not be resolved...

**Comment by bprashanth** [comment] 2016-02-03 19:33
Moved back into flaky in https://github.com/kubernetes/kubernetes/pull/20525, @freehan is trying for repro/solidifying the test IIUC

**Comment by freehan** [comment] 2016-02-03 19:33
@thockin 
Trying to reproduce the problem. It is running successful in flaky suite and my local cluster so far...
Will try to run it with other tests together.

**Comment by freehan** [comment] 2016-02-05 21:49
Two types of failure:

1. Elasticsearch cluster in bad state. 
This only happens when running with other disruptive tests. Never failed in `kubernetes-e2e-gce-parallel-flaky` suite where it is not running with disruptive tests. ES resilience can be improved by #19149

2. Missing log lines in Elasticsearch. 
I am able to reproduce this once. It is due to fluentd is hanged. Filed a issue to upstream. https://github.com/fluent/fluentd/issues/767


@ihmccreery Request to mark this test as [Feature] since it depends on two 3rd party components.

**Comment by bprashanth** [comment] 2016-02-05 22:32
The risk here is that ES is a default cluster addon. IMO it's fine not testing it for critical builds, but the risk is we'll ship something that straight crashloops. So if we move it to feature I'd ask that you add a smaller test that verifies basic functionality to a blocking suite (ping es, check that it accepts *some* logs). Or make it non-default.

**Comment by freehan** [comment] 2016-02-05 23:25
@bprashanth Good point. I will work on #19149 first. It has to be done anyway. It will also make future ES updates easier. 

BTW, ES addon is not default for GCE/GKE.

**Comment by bprashanth** [comment] 2016-02-05 23:32
>BTW, ES addon is not default for GCE/GKE.

Really? my e2e cluster always has it, why are we testing with it then?

**Comment by freehan** [comment] 2016-02-05 23:40
For GCE:
`config-default.sh: LOGGING_DESTINATION="${KUBE_LOGGING_DESTINATION:-gcp}"`
`config-test.sh: LOGGING_DESTINATION="${KUBE_LOGGING_DESTINATION:-elasticsearch}"`

**Comment by gmarek** [comment] 2016-02-08 08:30
Yeah - another place where test and 'production' configs differ, but I guess we need to test elasticsearch for 'fully opensource' version, thus it's justified...

**Comment by bprashanth** [comment] 2016-02-08 12:24
> Yeah - another place where test and 'production' configs differ, but I guess we need to test elasticsearch for 'fully opensource' version, thus it's justified...

That's [Feature] then, just like we test flannel. Not something to bring up as an addon on every e2e clusters.

**Comment by gmarek** [comment] 2016-02-08 12:55
We probably need some suite with all 'important' options (e.g. Features) turned on, on top of dedicated suite for every feature. Ugh... @ihmccreery

**Closed** 2016-02-19 13:46 UTC
Labels: area/logging, kind/flake, priority/P0, team/cluster
