### ISSUE TITLE
failed to bring up gce cluster for e2e test

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#25198] opened 2016-05-05 14:15 UTC
This just happened today. I was able to bring up a gce cluster just a couple days ago. It seems to be a gcloud cli change. 
```bash
# KUBERNETES_PROVIDER=gce KUBERNETES_CONFORMANCE_TEST=y go run hack/e2e.go -v -up
```
```console
INSTANCE_GROUPS=rootfs-e2e-minion-group
NODE_NAMES=rootfs-e2e-minion-mukv rootfs-e2e-minion-pixn rootfs-e2e-minion-ye4p
usage: gcloud compute instances describe  NAME [optional flags]
ERROR: (gcloud.compute.instances.describe) unrecognized arguments:
  --fields
  networkInterfaces[0].accessConfigs[0].natIP
2016/05/05 14:03:27 e2e.go:200: Error running up: exit status 2
2016/05/05 14:03:27 e2e.go:196: Step 'up' finished in 2m32.594482077s
2016/05/05 14:03:27 e2e.go:110: Error starting e2e cluster. Aborting.
exit status 1
```

@kubernetes/sig-testing

**Comment by jayunit100** [comment] 2016-05-05 14:30
does `cluster/kube-up.sh` work ?

**Comment by rootfs** [comment] 2016-05-05 14:39
@jayunit100 same error
```console
Group is stable
INSTANCE_GROUPS=rootfs-e2e-minion-group
NODE_NAMES=rootfs-e2e-minion-2zuq rootfs-e2e-minion-6cll rootfs-e2e-minion-gigu
usage: gcloud compute instances describe  NAME [optional flags]
ERROR: (gcloud.compute.instances.describe) unrecognized arguments:
  --fields
  networkInterfaces[0].accessConfigs[0].natIP
```

**Comment by rootfs** [comment] 2016-05-05 14:40
gcloud version
```console
#./google-cloud-sdk/bin/gcloud -v
Google Cloud SDK 108.0.0

alpha 2016.01.12
beta 2016.01.12
bq 2.0.24
bq-nix 2.0.24
core 2016.05.02
core-nix 2016.03.28
gcloud 
gsutil 4.19
gsutil-nix 4.18
```

**Comment by spxtr** [comment] 2016-05-05 15:32
dupe of #25153 should be fixed after rebase

**Closed by spxtr** 2016-05-05 15:32 UTC
