### ISSUE TITLE
kube-up scripts should not assume that all nodes have to be ready.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19786] opened 2016-01-18 09:49 UTC
Currently even if one Node is NotReady startup scripts fail. We should drop this requirement as we're allowing bigger clusters now. In big clusters few Nodes may fail to register in time (or at all), as e.g. virtual machine startup may fail (various cloud providers have different SLO's on machine startup success rates).

We should decide on percentage, smaller than 100, of machines that are requires for us to say that cluster startup were successful and update startup scripts. We also need to decide on what to do with fail machines - how do we tell user that some of them are not working and how can we help him/her with returning them to the provider.

Ref. #18969
cc @quinton-hoole @davidopp @dchen1107 @kubernetes/goog-control-plane @aronchick

**Comment by davidopp** [comment] 2016-01-19 07:16
@roberthbailey

**Comment by quinton-hoole** [comment] 2016-01-19 16:31
@gmarek It's going to be tricky to implement this policy reliably and have tests pass correctly in the face of failed nodes.  The problem is that most test jobs provision the correct number of nodes to accommodate the tests, and some tests probably implicitly assume that all provisioned nodes come up correctly.  I'm fully supportive of fixing those tests where required.  But be warned, whoever implements this proposal, should not merge the change before thoroughly testing it in the face of a failing node in every single test job, otherwise we will run into difficult to diagnose test flakes.

Another alternative starting point is to only activate this proposed change for large clusters, of which there are only a few test jobs, and a few tests that run in those large clusters.

**Comment by roberthbailey** [comment] 2016-01-19 21:21
@jlowdermilk

**Comment by gmarek** [comment] 2016-01-20 08:56
We need to decide if this is requirement for v1.2 and thus we need to assign someone to get this done, or can it wait to some patch release? @aronchick 

@quinton-hoole - I completely agree that this may require additional work with fixing the tests.

**Comment by quinton-hoole** [comment] 2016-01-20 18:50
@gmarek @aronchick I think that the 1.2 blocker for this is only the addition of basic documentation to the effect that if even a single node does not come online correctly (e.g. due to a faulty cloud VM) when bringing up a new cluster with kube-up (i.e. not necessarily in GKE), kube-up will report the cluster build as having failed (due to strict post-build checks), even though the cluster might be perfectly usable with say 999 out of 1000 nodes available.  This is only really relevant for very large clusters (~ hundreds to thousands of nodes).

Once we have fixed the e2e tests to be tolerable of not all nodes coming up correctly, we can relax the post-build checks.

I similar but independent argument holds for GKE, which does not use kube-up.  If we leave the GKE post cluster build checks strict, we risk ~50% of very large cluster builds (~1,000 nodes) reporting failure when they should not really (e.g. if 999 nodes came up successfully).  If we relax the post-build checks to not fail in that case, the e2e automated tests will likely become flaky, so we would lose valuable regression and v1.2 stability signals.

**Comment by quinton-hoole** [comment] 2016-01-20 18:51
@roberthbailey @alex-mohr FYI for GKE above.

**Comment by roberthbailey** [comment] 2016-01-20 19:13
A simpler "fix" for 1.2 would be to change the language printed out by kube-up to say something like "X/Y nodes are available, your cluster may not be fully functional". This would still "fail" kube-up (in the sense that we return an error code) but give the user a clear signal as to whether they care about the failure. For our automation, it wouldn't help, since the automation would always fail to create the large clusters.

**Comment by quinton-hoole** [comment] 2016-01-20 19:48
@roberthbailey Yes, agreed.  That would be a good implementation of the "additional basic documentation" that I mentioned, but perhaps did not express clearly enough.

**Comment by roberthbailey** [comment] 2016-01-20 19:57
Good to know we are on the same page. :)

**Comment by gmarek** [comment] 2016-01-21 14:57
We printed nearly exactly what @roberthbailey suggested. I changed it to be exactly that.

**Comment by wojtek-t** [comment] 2016-02-03 10:13
In the light of #20412 - can we close this one now?

**Comment by davidopp** [comment] 2016-02-06 18:37
Yes, #20407 and #20412

**Closed by davidopp** 2016-02-06 18:37 UTC
Labels: priority/P1, team/control-plane
