### ISSUE TITLE
Some tests are timing out and we are missing logs from them

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#37553] opened 2016-11-28 12:15 UTC
Runs like:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce/2835/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/1856/
unexpectedly timed out.
I wanted to look into logs, but we don't have logs for failed run, which makes them undebuggable.

There are 2 problems here:
1. why the suite timed out - it really seems to me that this is an infrastructure problems, because there is junit_xy.xml file for every from 25 workers, whereas in those runs, some are missing. @ixdy 
2. We are missing logs - gathering logs from master and nodes should be a P0 to enable debugging of huge number of runs that timed out.

@kubernetes/test-infra-maintainers

**Comment by deads2k** [comment] 2016-11-29 12:51
> I wanted to look into logs, but we don't have logs for failed run, which makes them undebuggable.

I'm having the same problem trying to look at the kops bring up failures: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/2319 . 

@kubernetes/rh-cluster-infra

**Comment by calebamiles** [comment] 2016-11-30 07:59
@wojtek-t, @fejta, do you believe this issue is a release blocker? Could you please update this issue by 1PM PST 30 November 2016. Thanks!

**cc: @saad-ali, @dims, @deads2k**

**Comment by wojtek-t** [comment] 2016-11-30 20:39
@fejta @kubernetes/test-infra-maintainers - can someone please take a look? This is blocking debugging a bunch of test failures.

**Comment by zmerlynn** [comment] 2016-11-30 21:19
@wojtek-t: I took a look at the two runs you posted. They're actually similar to e.g. [kops-aws-updown#106](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-updown/106/) in that the inner container running `hack/e2e.go` has overrun its time limit.

```
I1125 03:10:05.104] • [SLOW TEST:9.982 seconds]
I1125 03:10:05.104] [k8s.io] Services
I1125 03:10:05.104] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:826
I1125 03:10:05.104]   should create endpoints for unready pods
I1125 03:10:05.104]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1105
I1125 03:10:05.104] ------------------------------
W1125 03:41:57.290] ++ kill-leaked-container ci-kubernetes-e2e-gce-etcd3-1856
W1125 03:41:57.291] ++ local container=ci-kubernetes-e2e-gce-etcd3-1856
W1125 03:41:57.291] +++ docker inspect --format '{{.State.Pid}}' ci-kubernetes-e2e-gce-etcd3-1856
W1125 03:41:57.330] ++ local pid=5256
I1125 03:41:57.330] Processes running under container ci-kubernetes-e2e-gce-etcd3-1856:
```

Right now, we don't gather logs in that situation at all, on post-submit, it looks like. You can see https://github.com/kubernetes/test-infra/blob/master/jobs/pull-kubernetes-e2e-gce.sh#L74 (presubmit), vs https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce.sh#L79 (postsubmit). I'm sure part of this is because we cargo-culted all of those bash files from each other, and in particular the `pull-` jobs are all copied from one another and the `ci-` jobs from one another.

It looks relatively straightforward to fix.

**Comment by jingxu97** [comment] 2016-11-30 21:24
cc @Random-Liu

**Comment by zmerlynn** [comment] 2016-11-30 21:29
@fejta: How close are you on https://github.com/kubernetes/test-infra/issues/1226? Otherwise this is probably worth a quick fix even if it's going to get ripped out soon.

**Comment by fejta** [comment] 2016-11-30 21:43
@zmerlynn that orthogonal to this problem. We are already uploading captured artifacts. The problem is we do not capture additional artifacts when we timeout. 

The problem is that the issue is that we timeout and kill the container -- https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gci-gce.sh#L71

However the container is what knows how to captures additional artifacts when the job fails. The container needs to handle timeout logic and capture additional artifacts when that happens.

Aka for the e2e jobs we need timeout logic inside hack/e2e.go such this fires: https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go#L291

Jobs that do not use hack/e2e.go will need a similar solution.

@wojtek-t there is no one on my team who is free to work on this right now.

**Comment by zmerlynn** [comment] 2016-11-30 21:47
@fejta: I'm not sure I agree with that design. The test run could wedge for arbitrary reasons - it's really useful to time out the *container*. I'd almost rather have a separate entrypoint to `dockerized-e2e-runner` so it looks like:

```
timeout 20m dockerized-e2e-runner.sh
if [[ ${rc} -ne 0 ]]; then
  dockerized-e2e-runner.sh diagnose_cluster
fi
```

or something.

**Comment by zmerlynn** [comment] 2016-11-30 21:48
So I totally disagree that it's ortogonal.

**Comment by fejta** [comment] 2016-11-30 21:50
I disagree that we want to decouple diagnosing the cluster from the process that starts the cluster, runs the tests and shuts down the cluster.

Whether or not we are running inside a container should not impact whether we capture the right logs.

The core problem is that the container assumes it has infinity hours to complete its run.

**Comment by zmerlynn** [comment] 2016-11-30 21:52
Sure, especially in the obvious case of a test failure (but no lifecycle issue), you need to dump the logs while the cluster is up. But if the container wanders off, which, until we solve the Halting Problem, there's always going to be a chance of, you want another crack at diagnosis.

**Comment by fejta** [comment] 2016-11-30 21:54
That is very hypothetical and there are lots of side effects of designing things that way. Essentially you are asking to change 400 jobs to add this new diagnose_cluster logic. I'm suggesting we do it once inside the container where it belongs.

**Comment by zmerlynn** [comment] 2016-11-30 22:06
How? We can run timeout on the straight call to `go run hack/e2e.go`, but then you're not protecting anything outside of it (wedging gcloud update, random URLs taking forever, etc). You can layer it inside the container in the same manner I was just referencing, but do (inside the container):
```
timeout 20m e2e-runner.sh
# handle timeout
```
... but there are non-theoretical failures that will hit you eventually that the container is actually protecting right now.

**Comment by fejta** [comment] 2016-11-30 22:22
`timeout 20m go run hack/e2e.go` is an acceptable step in the right direction. Ideally it lives in e2e.go itself as this is the official interface/entry into our e2e testing (we will eventually migrate everything in e2e-runner.sh into e2e.go and delete e2e-runner.sh).

**Comment by fejta** [comment] 2016-11-30 22:24
btw, is this something you are interested in working on or are you just interested in the design?

I should be able to have someone work on this later this week, but would be very happy for you to start on it today.

**Comment by zmerlynn** [comment] 2016-11-30 22:31
I'm actually working on the quick fix now (matching how `pull-` does it with how `ci-` does it), but it would be interesting to look into the longer term question.

**Comment by zmerlynn** [comment] 2016-11-30 23:07
kubernetes/test-infra#1247 should be a good hacky fix, but not a great long-term solution, as @fejta points out.

**Comment by wojtek-t** [comment] 2016-12-01 08:35
I have a feeling that this fix didn't help. E.g. this failure still doesn't have logs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/2157/

Which mean it is still P0 in my opinion.

@fejta - I think there isn't anything more urgent that this. This is blocking tens of engineers in the team from effectively debug anything. Migrating something to a different framework or anything like that is far less important that this.

**Comment by krousey** [comment] 2016-12-01 18:06
Piling on to this, automated upgrade tests are now in a similar situation: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/481?log

(we fixed some things so now all the tests are actually running and timing out)

**Comment by fejta** [comment] 2016-12-01 19:26
Moving to kubernetes/test-infra#1250

**Comment by fejta** [comment] 2016-12-01 19:28
@krousey if you want better debugging on upgrade logs we need to go forward with https://github.com/kubernetes/test-infra/issues/1030

**Comment by ixdy** [comment] 2016-12-01 20:48
Looking at the Jenkins build log for kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/481:
```
+ ./_tmp/upload-to-gcs.sh
Run finished at Thu Dec  1 04:36:32 PST 2016
Uploading to gs://kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/481 (attempt 1)
Uploading build result: FAILURE
Uploading artifacts
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
CommandException: 12 files/objects could not be transferred.
Uploading to gs://kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/481 (attempt 2)
Uploading build result: FAILURE
Uploading artifacts
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/startupscript.log": .
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
CommandException: 12 files/objects could not be transferred.
Uploading to gs://kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/481 (attempt 3)
Uploading build result: FAILURE
Uploading artifacts
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-hl93/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-fyje/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/startupscript.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
Error opening file "file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts/gke-jenkins-e2e-default-pool-487a8b07-yrd9/kern.log": .
Error copying file:///var/lib/jenkins/workspace/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster/_artifacts: 'NoneType' object is not iterable
CommandException: 12 files/objects could not be transferred.
```

IMO a far less risky change (than converting all upgrade jobs to bootstrap) would be to add a single `sudo chmod o+r` before we call `upload-to-gcs.sh` for legacy jobs.

**Comment by ixdy** [comment] 2016-12-01 20:54
https://github.com/kubernetes/test-infra/pull/1264 for your consideration

**Comment by ixdy** [comment] 2016-12-01 22:22
Looks like the same issue affects bootstrap'd jobs, and kubernetes/test-infra#1264 didn't address them:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.5/90/
```
E1130 07:45:31.189] FAIL: ci-kubernetes-e2e-gce-serial-release-1.5
I1130 07:45:31.189] Upload result and artifacts...
I1130 07:45:31.189] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.5/90
I1130 07:45:31.190] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml _artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.5/90/artifacts
W1130 07:45:32.732] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-5t7r/startupscript.log": .
W1130 07:45:32.733] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.823] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-5t7r/kern.log": .
W1130 07:45:32.823] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.826] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-cxuf/startupscript.log": .
W1130 07:45:32.826] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.850] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-ie1t/startupscript.log": .
W1130 07:45:32.850] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.863] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-cxuf/kern.log": .
W1130 07:45:32.863] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.882] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-1x6t/startupscript.log": .
W1130 07:45:32.883] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.949] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-ie1t/kern.log": .
W1130 07:45:32.949] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:32.962] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-1x6t/kern.log": .
W1130 07:45:32.963] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:33.128] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-vqw3/startupscript.log": .
W1130 07:45:33.128] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:33.243] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-vqw3/kern.log": .
W1130 07:45:33.244] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:33.259] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-szuq/startupscript.log": .
W1130 07:45:33.260] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:33.358] Error opening file "file://_artifacts/bootstrap-e2e-minion-group-szuq/kern.log": .
W1130 07:45:33.358] Error copying file://_artifacts: 'NoneType' object is not iterable
W1130 07:45:37.305] CommandException: 24 files/objects could not be transferred.
I1130 07:45:37.408] process 19213 exited with code 1
W1130 07:45:37.409] Failed to upload artifacts
```

**Comment by ixdy** [comment] 2016-12-02 08:17
Oh, https://github.com/kubernetes/test-infra/pull/1247 doesn't work because we check out the kubernetes tarball inside the container, so `cluster/log-dump.sh` isn't going to exist after timeout. Looks like we really do need https://github.com/kubernetes/test-infra/pull/1270.

**Comment by fejta** [comment] 2016-12-02 19:29
Please leave this closed and send additional comments/feedback to https://github.com/kubernetes/test-infra/issues/1250

**Closed by fejta** 2016-12-02 19:29 UTC
Labels: kind/bug, non-release-blocker, priority/P0, team/test-infra
