### ISSUE TITLE
flaky test: TestCustomResourceDefaultingWithoutWatchCache

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#125760] opened 2024-06-27 12:06 UTC
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125758/pull-kubernetes-integration/1806280169099366400

### Which tests are flaking?

--- FAIL: TestCustomResourceDefaultingWithoutWatchCache (4.58s)

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

### Reason for failure (if possible)

```
{Failed;  === RUN   TestCustomResourceDefaultingWithoutWatchCache
    testserver.go:280: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing"
    testserver.go:164: runtime-config=map[api/all:true]
    testserver.go:165: Starting apiextensions-apiserver on port 33019...
I0627 11:11:35.766913  103190 serving.go:380] Generated self-signed cert (/tmp/apiextensions-apiserver4170115585/apiserver.crt, /tmp/apiextensions-apiserver4170115585/apiserver.key)
W0627 11:11:36.322777  103190 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0627 11:11:36.328509  103190 handler.go:286] Adding GroupVersion apiextensions.k8s.io v1 to ResourceManager
W0627 11:11:36.328547  103190 genericapiserver.go:761] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
W0627 11:11:36.328727  103190 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    testserver.go:191: Waiting for /healthz to be ok...
I0627 11:11:36.341029  103190 dynamic_serving_content.go:135] "Starting controller" name="serving-cert::/tmp/apiextensions-apiserver4170115585/apiserver.crt::/tmp/apiextensions-apiserver4170115585/apiserver.key"
I0627 11:11:36.341623  103190 secure_serving.go:213] Serving securely on 127.0.0.1:33019
I0627 11:11:36.341819  103190 customresource_discovery_controller.go:292] Starting DiscoveryController
I0627 11:11:36.341859  103190 tlsconfig.go:243] "Starting DynamicServingCertificateController"
I0627 11:11:36.341959  103190 naming_controller.go:294] Starting NamingConditionController
I0627 11:11:36.342008  103190 controller.go:142] Starting OpenAPI controller
I0627 11:11:36.342030  103190 controller.go:90] Starting OpenAPI V3 controller
I0627 11:11:36.342053  103190 crd_finalizer.go:269] Starting CRDFinalizer
I0627 11:11:36.342086  103190 establishing_controller.go:79] Starting EstablishingController
I0627 11:11:36.342104  103190 nonstructuralschema_controller.go:195] Starting NonStructuralSchemaConditionController
I0627 11:11:36.342117  103190 apiapproval_controller.go:189] Starting KubernetesAPIApprovalPolicyConformantConditionController
W0627 11:11:36.342225  103190 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.1.2.3:12345: connect: connection refused
E0627 11:11:36.342333  103190 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0\": dial tcp 127.1.2.3:12345: connect: connection refused" logger="UnhandledError"
I0627 11:11:36.546629  103190 handler.go:286] Adding GroupVersion tests.example.com v1beta1 to ResourceManager
W0627 11:11:37.822574  103190 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.1.2.3:12345: connect: connection refused
E0627 11:11:37.822650  103190 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0\": dial tcp 127.1.2.3:12345: connect: connection refused" logger="UnhandledError"
W0627 11:11:39.048433  103190 warnings.go:70] unknown field "alpha"
W0627 11:11:39.048463  103190 warnings.go:70] unknown field "beta"
W0627 11:11:39.048468  103190 warnings.go:70] unknown field "delta"
W0627 11:11:39.048472  103190 warnings.go:70] unknown field "epsilon"
W0627 11:11:39.048476  103190 warnings.go:70] unknown field "gamma"
    defaulting_test.go:288: Creating CR and expecting defaulted fields in spec, but status does not exist at all
    defaulting_test.go:301: CR created: map[string]interface {}{"apiVersion":"tests.example.com/v1beta1", "kind":"Foo", "metadata":map[string]interface {}{"creationTimestamp":"2024-06-27T11:11:39Z", "generation":1, "managedFields":[]interface {}{map[string]interface {}{"apiVersion":"tests.example.com/v1beta1", "fieldsType":"FieldsV1", "fieldsV1":map[string]interface {}{"f:spec":map[string]interface {}{".":map[string]interface {}{}, "f:a":map[string]interface {}{}, "f:b":map[string]interface {}{}, "f:replicas":map[string]interface {}{}, "f:v1beta1":map[string]interface {}{}}}, "manager":"integration.test", "operation":"Update", "time":"2024-06-27T11:11:39Z"}}, "name":"foo", "resourceVersion":"3714", "uid":"1fd9d30a-5657-4f26-bff8-e7b2f99cd18c"}, "spec":map[string]interface {}{"a":"a", "b":"B", "replicas":1, "v1beta1":"v1beta1", "v1beta2":"v1beta2"}}
    defaulting_test.go:308: Updating status and expecting 'a' and 'b' to show up.
    defaulting_test.go:315: Add 'c' default to the storage version and wait until GET sees it in both status and spec
    defaulting_test.go:318: wait until GET sees 'c' in both status and spec
    defaulting_test.go:325: will retry, did not find spec.c in the object
    defaulting_test.go:335: wait until GET sees 'c' in both status and spec of cached get
    defaulting_test.go:352: verify LIST sees 'c' in both status and spec
    defaulting_test.go:361: verify LIST from cache sees 'c' in both status and spec
    defaulting_test.go:374: verify WATCH sees 'c' in both status and spec
W0627 11:11:39.282080  103190 watcher.go:338] watch chan error: etcdserver: mvcc: required revision has been compacted
    defaulting_test.go:382: unexpected watch event: ERROR, &v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"The resourceVersion for the provided watch is too old.", Reason:"Expired", Details:(*v1.StatusDetails)(nil), Code:410}
I0627 11:11:39.282619  103190 customresource_discovery_controller.go:328] Shutting down DiscoveryController
I0627 11:11:39.282624  103190 object_count_tracker.go:151] "StorageObjectCountTracker pruner is exiting"
I0627 11:11:39.282651  103190 controller.go:170] Shutting down OpenAPI controller
I0627 11:11:39.282657  103190 naming_controller.go:305] Shutting down NamingConditionController
I0627 11:11:39.282675  103190 apiapproval_controller.go:201] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
I0627 11:11:39.282674  103190 dynamic_serving_content.go:149] "Shutting down controller" name="serving-cert::/tmp/apiextensions-apiserver4170115585/apiserver.crt::/tmp/apiextensions-apiserver4170115585/apiserver.key"
I0627 11:11:39.282681  103190 crd_finalizer.go:281] Shutting down CRDFinalizer
I0627 11:11:39.282721  103190 nonstructuralschema_controller.go:207] Shutting down NonStructuralSchemaConditionController
I0627 11:11:39.282742  103190 secure_serving.go:258] Stopped listening on 127.0.0.1:33019
I0627 11:11:39.282761  103190 establishing_controller.go:90] Shutting down EstablishingController
I0627 11:11:39.282778  103190 controller.go:120] Shutting down OpenAPI V3 controller
I0627 11:11:39.282762  103190 tlsconfig.go:258] "Shutting down DynamicServingCertificateController"
--- FAIL: TestCustomResourceDefaultingWithoutWatchCache (4.58s)
;}
```

### Relevant SIG(s)

/sig api-machinery

**Comment by Vyom-Yadav** [comment] 2024-06-29 16:24
Failure on master-blocking: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1806735419576946688

**Comment by liggitt** [comment] 2024-06-29 16:45
The error is that etcd is reporting the revision is compacted less than a second after the watch was initialized and retried:

```
W0627 11:11:39.048476  103190 warnings.go:70] unknown field "gamma"
    defaulting_test.go:288: Creating CR and expecting defaulted fields in spec, but status does not exist at all
    defaulting_test.go:301: CR created: map[string]interface {}{"apiVersion":"tests.example.com/v1beta1", "kind":"Foo", "metadata":map[string]interface {}{"creationTimestamp":"2024-06-27T11:11:39Z", "generation":1, "managedFields":[]interface {}{map[string]interface {}{"apiVersion":"tests.example.com/v1beta1", "fieldsType":"FieldsV1", "fieldsV1":map[string]interface {}{"f:spec":map[string]interface {}{".":map[string]interface {}{}, "f:a":map[string]interface {}{}, "f:b":map[string]interface {}{}, "f:replicas":map[string]interface {}{}, "f:v1beta1":map[string]interface {}{}}}, "manager":"integration.test", "operation":"Update", "time":"2024-06-27T11:11:39Z"}}, "name":"foo", "resourceVersion":"3714", "uid":"1fd9d30a-5657-4f26-bff8-e7b2f99cd18c"}, "spec":map[string]interface {}{"a":"a", "b":"B", "replicas":1, "v1beta1":"v1beta1", "v1beta2":"v1beta2"}}
    defaulting_test.go:308: Updating status and expecting 'a' and 'b' to show up.
    defaulting_test.go:315: Add 'c' default to the storage version and wait until GET sees it in both status and spec
    defaulting_test.go:318: wait until GET sees 'c' in both status and spec
    defaulting_test.go:325: will retry, did not find spec.c in the object
    defaulting_test.go:335: wait until GET sees 'c' in both status and spec of cached get
    defaulting_test.go:352: verify LIST sees 'c' in both status and spec
    defaulting_test.go:361: verify LIST from cache sees 'c' in both status and spec
    defaulting_test.go:374: verify WATCH sees 'c' in both status and spec
W0627 11:11:39.282080  103190 watcher.go:338] watch chan error: etcdserver: mvcc: required revision has been compacted
    defaulting_test.go:382: unexpected watch event: ERROR, &v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"The resourceVersion for the provided watch is too old.", Reason:"Expired", Details:(*v1.StatusDetails)(nil), Code:410}
```

That's really surprising to me. I can't keep track of what cache / etcd watch changes have gone in in the last couple weeks… @wojtek-t @p0lyn0mial @serathius is this flake explainable by newly changed behavior in the cache? Is it expected or a problem?

**Comment by serathius** [comment] 2024-07-01 07:32
Can't reproduce the failure by running test on it's own during test. Based on error it's related to compaction. Maybe the test assume that it fetch exact on compaction, but the revision is compacted in background. 

Is there any chance it was a caused by background compaction?
When the flakes started happening? I don't know how to read https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration as it doesn't mention test names.

**Comment by p0lyn0mial** [comment] 2024-07-01 07:45
I quickly looked at https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1806735419576946688

It looks like there is a single etcd instance shared for all tests. In this particular run the etcd was started at 17:18:47 and the RV used by the test was compacted at 17:22:00

Does anybody know what the default compaction used by etcd for integration tests is?

**Comment by serathius** [comment] 2024-07-01 07:59
5 minutes is kubernetes default. Could we disable the compaction in the integration tests?

**Comment by p0lyn0mial** [comment] 2024-07-01 08:14
The flake is not new:

- failed on [06/04/2024](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1798071077843243008)

- failed on [06/08/2024 ](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1799499759329742848)

- failed on [06/11/2024 ](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1800358679170519040)

- failed on [06/13/2024](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1801361858389610496)

- failed on [ 06/15/2024](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1801923779543175168)

- failed on [06/17/2024](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1802554441644118016) 


> Could we disable the compaction in the integration tests?

I think that the test should be fixed instead.

**Comment by p0lyn0mial** [comment] 2024-07-01 12:35
I have opened https://github.com/kubernetes/kubernetes/pull/125825 as a potential improvement for the test.

**Comment by neolit123** [comment] 2024-09-09 16:38
this is still flaking as seen here occasionally:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration
`k8s.io/apiextensions-apiserver/test/integration.integration`

someone from sig-apimachinery should TAL and get assigned to fix it.

**Comment by drewhagen** [comment] 2024-09-25 04:17
@p0lyn0mial I see that https://github.com/kubernetes/kubernetes/pull/125825 has merged, but has this fixed this specific issue?
It looks like there has been a few failures on this test in recent time:
[9/24 01:24 UTC−05:00](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1838463896583671808) and
[9/24 11:07 UTC−05:00](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1838610674188554240)

@kubernetes/sig-api-machinery-bugs The first release cut (1.32.0-alpha.1) is due in less than a week from today on Oct 1st 2024. Is this an issue that would or should block and delay release cuts? Please advise - thank you!

**Comment by p0lyn0mial** [comment] 2024-09-25 09:24
> @p0lyn0mial I see that https://github.com/kubernetes/kubernetes/pull/125825 has merged, but has this fixed this specific issue?
It looks like there has been a few failures on this test in recent time:
[9/24 01:24 UTC−05:00](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1838463896583671808) and
[9/24 11:07 UTC−05:00](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1838610674188554240)

Sorry, I couldn't find any indicators that prove the test failed in the runs you linked above.

**Comment by drewhagen** [comment] 2024-09-26 16:18
@p0lyn0mial can you please elaborate? This is what I'm seeing in the logs of [9/24 01:24 UTC−05:00](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1838463896583671808):
```
ok  	k8s.io/kubernetes/test/integration/apiserver/admissionwebhook	179.623s
I0924 06:47:07.993032  112482 etcd.go:73] etcd already running at http://127.0.0.1:2379/
ok  	k8s.io/kubernetes/test/integration/apiserver	287.885s
I0924 06:48:53.593765  112592 etcd.go:73] etcd already running at http://127.0.0.1:2379/
FAIL	k8s.io/apiextensions-apiserver/test/integration	393.328s
ok  	k8s.io/kubernetes/test/integration/apiserver/cel/authorizerselector/selectordisabled	6.375s
```
```
=== SKIP: test/integration/servicecidr TestServiceAllocPerformance (0.00s)
    perf_test.go:43: KEP-1880 performance comparison
=== Failed
=== FAIL: k8s.io/apiextensions-apiserver/test/integration TestNonStructuralSchemaConditionForCRDV1Beta1MigratedData (unknown)
    testserver.go:280: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing"
    testserver.go:164: runtime-config=map[api/all:true]
    testserver.go:165: Starting apiextensions-apiserver on port 42155...
```
```
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x4c
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 53783
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x73
=== FAIL: k8s.io/apiextensions-apiserver/test/integration TestNonStructuralSchemaConditionForCRDV1Beta1MigratedData/metadata_with_generateName_property (unknown)
    validation_test.go:1524: Creating CRD foos.tests-17.apiextension.k8s.io
I0924 06:48:51.503469  104156 handler.go:286] Adding GroupVersion tests-17.apiextension.k8s.io v1beta1 to ResourceManager
I0924 06:48:51.503538  104156 handler.go:286] Adding GroupVersion tests-17.apiextension.k8s.io v1 to ResourceManager
```

**Comment by wendy-ha18** [comment] 2024-09-29 09:30
Hi @p0lyn0mial , I just checked [Triage](https://storage.googleapis.com/k8s-triage/index.html?test=integration.integration), the latest fail of the test `k8s.io/apiextensions-apiserver/test/integration.integration` was [25/09/2024, 20:26:34](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-31/1838887507517771776) with the same errors ```TestCustomResourceDefaultingWithoutWatchCache```.

As the 1.32.0-alpha.1 release cut will happen in the next 02 days Oct 1st, do you think this issue will block the cut?

**Comment by wendy-ha18** [comment] 2024-09-30 11:40
Hi @neolit123 @p0lyn0mial @drewhagen, this test has been stable and hasn’t failed again since [25/09](https://storage.googleapis.com/k8s-triage/index.html?test=integration.integration). I don’t believe it will impact the release cut. Should we close this issue? I’ll reopen it if it fails again.

I’d appreciate your thoughts on this.

**Comment by p0lyn0mial** [comment] 2024-09-30 12:35
> Hi @p0lyn0mial , I just checked [Triage](https://storage.googleapis.com/k8s-triage/index.html?test=integration.integration), the latest fail of the test k8s.io/apiextensions-apiserver/test/integration.integration was [25/09/2024, 20:26:34](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-31/1838887507517771776) with the same error TestCustomResourceDefaultingWithoutWatchCache.

Could you please confirm that the job you linked is not for the previous release (1.31)? 
The job title suggests that it might be (`ci-kubernetes-integration-1-31`).

We did not backport the fix to the previous release.

**Comment by wendy-ha18** [comment] 2024-09-30 12:52
You're right, the test `k8s.io/apiextensions-apiserver/test/integration.integration` fails on `integration-1.31` job of `sig-release-1.31-blocking` board @p0lyn0mial . It's not fail on `master-blocking` :) . Should we close this issue?

![image](https://github.com/user-attachments/assets/6db64761-62d0-426c-831c-4cef3c4406cf)

**Comment by p0lyn0mial** [comment] 2024-09-30 13:06
> Should we close this issue?

I think so, the same job `k8s.io/apiextensions-apiserver/test/integration.integration` is green on the master branch. Please double check.

**Comment by wendy-ha18** [comment] 2024-09-30 13:10
yup, this test dose not fail in [`master-blocking` ](https://testgrid.k8s.io/sig-release-master-blocking#integration-master).

![image](https://github.com/user-attachments/assets/4db855dd-a2bf-49e2-9908-443c52c57e1a)

**Closed** 2024-09-30 13:16 UTC
Labels: kind/bug, sig/api-machinery, kind/flake, triage/accepted, sig/etcd
