### ISSUE TITLE
Unit test flake:  k8s.io/kubernetes/pkg/registry/controller/etcd

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#25513] opened 2016-05-11 22:39 UTC
Pr builder flake running a 1.2 branch cherrypick of unrelated test code.

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25508/kubernetes-pull-test-unit-integration/25420/

From build-log:
```
ok  	k8s.io/kubernetes/pkg/quota	1.173s
ok  	k8s.io/kubernetes/pkg/registry/componentstatus	1.184s
ok  	k8s.io/kubernetes/pkg/registry/configmap	1.248s
ok  	k8s.io/kubernetes/pkg/registry/configmap/etcd	40.136s
ok  	k8s.io/kubernetes/pkg/registry/controller	1.424s
FAIL	k8s.io/kubernetes/pkg/registry/controller/etcd	72.160s
ok  	k8s.io/kubernetes/pkg/registry/daemonset	1.122s
ok  	k8s.io/kubernetes/pkg/registry/daemonset/etcd	41.874s
ok  	k8s.io/kubernetes/pkg/registry/deployment	1.167s
ok  	k8s.io/kubernetes/pkg/registry/deployment/etcd	55.789s
ok  	k8s.io/kubernetes/pkg/registry/endpoint	1.517s
ok  	k8s.io/kubernetes/pkg/registry/endpoint/etcd	39.003s
ok  	k8s.io/kubernetes/pkg/registry/event	1.199s
...
```

**Comment by fejta** [comment] 2016-05-23 22:31
Assigning to @lavalamp per https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/OWNERS

**Comment by xiang90** [comment] 2016-06-03 00:06
I will try to reproduce this too.

**Comment by wojtek-t** [comment] 2016-06-08 14:06
To give more information about this - what exactly happened is:
```
=== RUN   TestWatch
--- FAIL: TestWatch (44.27s)
	resttest.go:945: unexpected error: client: etcd cluster is unavailable or misconfigured
	resttest.go:950: unexpected result from result channel
```

So it seems it's not test issue itself, but most probably something happened with etcd.

**Comment by wojtek-t** [comment] 2016-06-08 14:10
The issue is exactly the same as in #26403 btw.

**Comment by xiang90** [comment] 2016-06-08 14:16
@wojtek-t I still cannot reproduce it. I will try more this week.

**Comment by lavalamp** [comment] 2016-08-23 17:34
Closing as obsolete-- bot will open a new issue if it recurs.

**Closed by lavalamp** 2016-08-23 17:34 UTC
Labels: kind/flake, team/CSI-API Machinery SIG
