### ISSUE TITLE
Failure cluster [df7a596c...] `[sig-node] Pod InPlace Resize Container [Serial] `

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#128837] opened 2024-11-18 12:18 UTC
### Failure cluster [df7a596c0e6648ecbdd1](https://go.k8s.io/triage#df7a596c0e6648ecbdd1)

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/295aa03c-3d75-495c-876c-fc08b0e3c0c4">

##### Error text:
```
[FAILED] Timed out after 300.001s.
expected pod to be running and ready, got instead:
    <*v1.Pod | 0xc00180db08>: 
        metadata:
          annotations:
            owner.test: k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:964
          creationTimestamp: "2024-11-13T07:03:05Z"
          generateName: resize-test-
          labels:
            time: "831950759"
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:annotations:
                  .: {}
                  f:owner.test: {}
                f:generateName: {}
                f:labels:
                  .: {}
                  f:time: {}
              f:spec:
                f:containers:
                  k:{"name":"c1"}:
                    .: {}
                    f:args: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resizePolicy: {}
                    f:resources:
                      .: {}
                      f:limits:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                      f:requests:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                    f:securityContext:
                      .: {}
                      f:allowPrivilegeEscalation: {}
                
```
#### Recent failures:
[11/18/2024, 12:33:35 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858382589006450688)
[11/17/2024, 10:54:51 PM ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks/1858357674702278656)
[11/17/2024, 7:33:04 PM ci-cgroupv2-containerd-node-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2/1858307090125164544)
[11/17/2024, 4:33:02 PM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858261790991847424)
[11/17/2024, 1:33:09 PM ci-cgroupv2-containerd-node-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2/1858216492152131584)

/kind failing-test

/sig node

**Comment by esotsal** [comment] 2024-11-19 14:47
First quick feedback, checking the shared failed runs , i notice that beside InPlacePodVerticalScaling test, others tests not related with InPlacePodVerticalScaling fail, with timeout.

/triage accepted
/assign @esotsal

**Comment by esotsal** [comment] 2024-11-19 18:49
@dims checking the logs i notice failures from 13th November, i speculate is related with  [error](https://storage.googleapis.com/k8s-triage/index.html?sig=node&text=unable%20to%20destroy%20cgroup%20paths%20for%20cgroup) , which has been discussed also in the past https://github.com/kubernetes/kubernetes/issues/123766 . Could it be related with containerd ?

**Comment by hshiina** [comment] 2024-11-20 09:41
I guess the cause of this issue is that pod resize tests delete pods asynchronously. 

Pods in resize tests don't handle SIGTERM. So, it takes more than 30 seconds to delete pods:
https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/test/e2e/framework/pod/resize.go#L161

Resize tests don't wait for pods to be completely deleted. The tests don't use `DeleteSync`:
https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/test/e2e/common/node/pod_resize.go#L1009

Probably, Node Container Manager test fails to destroy the kubepods cgroup because of a remaining pod at resize tests:
https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/test/e2e_node/node_container_manager_test.go#L273-L277

This failure happens while kubelet is stopped and kubelet is not restarted if this failure is caused. Then all tests that run after this failure fail because kubelet is not running.

**Comment by esotsal** [comment] 2024-11-20 11:50
Thanks @hshiina , seems this was missed, DeleteSync is used [here](https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/test/e2e/common/node/pod_resize.go#L1163C14-L1163C23)

**Comment by aojea** [comment] 2024-11-20 13:32
It is good to go through one existing failure and paste the snippets that validate the theory, or we can end fix forwarding forever

**Comment by hshiina** [comment] 2024-11-20 20:12
In [this failure case](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858382589006450688):

In [build.log](https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858382589006450688/build-log.txt), a Node Container Manager test got failed:

```
------------------------------
[sig-node] Node Container Manager [Serial] Validate Node Allocatable [NodeFeature:NodeAllocatable] sets up the node and runs the test [sig-node, Serial, NodeFeature:NodeAllocatable]
k8s.io/kubernetes/test/e2e_node/node_container_manager_test.go:75
  STEP: Creating a kubernetes client @ 11/18/24 06:57:11.204
  STEP: Building a namespace api object, basename node-container-manager @ 11/18/24 06:57:11.204
  I1118 06:57:11.214971 1624 framework.go:275] Skipping waiting for service account
  STEP: Stopping the kubelet @ 11/18/24 06:57:11.267
  I1118 06:57:11.289449 1624 util.go:352] Get running kubelet with systemctl:   UNIT                            LOAD   ACTIVE SUB     DESCRIPTION
    kubelet-20241118T054620.service loaded active running /tmp/node-e2e-20241118T054620/kubelet --kubeconfig /tmp/node-e2e-20241118T054620/kubeconfig --root-dir /var/lib/kubelet --v 4 --feature-gates NodeSwap=true --config-dir /tmp/node-e2e-20241118T054620/kubelet.conf.d --hostname-override n1-standard-2-ubuntu-gke-2204-1-29-v20241115-888ebd35 --container-runtime-endpoint unix:///run/containerd/containerd.sock --config /tmp/node-e2e-20241118T054620/kubelet-config --kernel-memcg-notification=true --feature-gates=DisableKubeletCloudCredentialProviders=true --image-credential-provider-config=/tmp/node-e2e-20241118T054620/credential-provider.yaml --image-credential-provider-bin-dir=/tmp/node-e2e-20241118T054620 --cgroups-per-qos=true --cgroup-root=/ --fail-swap-on=false --runtime-cgroups=/system.slice/containerd.service

  LOAD   = Reflects whether the unit definition was properly loaded.
  ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
  SUB    = The low-level unit activation state, values depend on unit type.
  1 loaded units listed.
  , kubelet-20241118T054620
  W1118 06:57:11.411580    1624 util.go:478] Health check on "http://127.0.0.1:10248/healthz" failed, error=Head "http://127.0.0.1:10248/healthz": read tcp 127.0.0.1:58338->127.0.0.1:10248: read: connection reset by peer
  I1118 06:57:12.438298 1624 node_container_manager_test.go:76] Unexpected error: 
      <*errors.errorString | 0xc002560b10>: 
      unable to destroy cgroup paths for cgroup [kubepods] : rmdir /sys/fs/cgroup/kubepods/burstable/pod8ada592e-6fa2-40f6-88a4-9562e937b2f9/aa9e0f73ee7720b5dbd66647f4e7ae3c2c6c667cbb4ffacafb79ee8096414800: device or resource busy
      {
          s: "unable to destroy cgroup paths for cgroup [kubepods] : rmdir /sys/fs/cgroup/kubepods/burstable/pod8ada592e-6fa2-40f6-88a4-9562e937b2f9/aa9e0f73ee7720b5dbd66647f4e7ae3c2c6c667cbb4ffacafb79ee8096414800: device or resource busy",
      }
  [FAILED] in [It] - k8s.io/kubernetes/test/e2e_node/node_container_manager_test.go:76 @ 11/18/24 06:57:12.438
```

A pod whose ID is `8ada592e-6fa2-40f6-88a4-9562e937b2f9` caused this failure.
In [kubelog.log](https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858382589006450688/artifacts/n1-standard-2-ubuntu-gke-2204-1-29-v20241115-888ebd35/kubelet.log), we can confirm the namespace and the name of the pod:
```
I1118 06:56:56.134135   50597 pod_workers.go:768] "Pod is being synced for the first time" pod="pod-resize-tests-4207/resize-test-wggxt" podUID="8ada592e-6fa2-40f6-88a4-9562e937b2f9" updateType="create"
```

kubelet is stopped while killing containers in the pod:
```
I1118 06:57:00.589379   50597 kubelet.go:2066] "SyncTerminatingPod enter" pod="pod-resize-tests-4207/resize-test-wggxt" podUID="8ada592e-6fa2-40f6-88a4-9562e937b2f9"
I1118 06:57:00.589392   50597 kubelet_pods.go:1833] "Generating pod status" podIsTerminal=false pod="pod-resize-tests-4207/resize-test-wggxt"
I1118 06:57:00.589449   50597 kubelet_pods.go:1846] "Got phase for pod" pod="pod-resize-tests-4207/resize-test-wggxt" oldPhase="Running" phase="Running"
I1118 06:57:00.589571   50597 kubelet.go:2076] "Pod terminating with grace period" pod="pod-resize-tests-4207/resize-test-wggxt" podUID="8ada592e-6fa2-40f6-88a4-9562e937b2f9" gracePeriod=30
I1118 06:57:00.589631   50597 kuberuntime_container.go:788] "Killing container with a grace period override" pod="pod-resize-tests-4207/resize-test-wggxt" podUID="8ada592e-6fa2-40f6-88a4-9562e937b2f9" containerName="c1" containerID="containerd://abe2cd9397f09c5ba9f18b643cdfadd626b1876359f57ef0c4a6b96768e5e558" gracePeriod=30
I1118 06:57:00.589655   50597 kuberuntime_container.go:809] "Killing container with a grace period" pod="pod-resize-tests-4207/resize-test-wggxt" podUID="8ada592e-6fa2-40f6-88a4-9562e937b2f9" containerName="c1" containerID="containerd://abe2cd9397f09c5ba9f18b643cdfadd626b1876359f57ef0c4a6b96768e5e558" gracePeriod=30
<snip>
I1118 06:57:11.267886   50597 factory.go:279] Factory "containerd" was unable to handle container "/system-reserved"
I1118 06:57:11.267934   50597 factory.go:279] Factory "systemd" was unable to handle container "/system-reserved"
I1118 06:57:11.267948   50597 factory.go:272] Factory "raw" can handle container "/system-reserved", but ignoring.
I1118 06:57:11.267961   50597 manager.go:929] ignoring container "/system-reserved"
<end of the log>
```

The test that created this pod is located above the failed Node Container Manager test in `build.log`:
```
[sig-node] Pod InPlace Resize Container [Serial] Burstable QoS pod, one container with cpu & memory requests - decrease memory request [sig-node, Serial]
k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:937
<snip>
  I1118 06:57:00.510752 1624 exec_util.go:80] ExecWithOptions: execute(POST https://127.0.0.1:6443/api/v1/namespaces/pod-resize-tests-4207/pods/resize-test-wggxt/exec?command=%2Fbin%2Fsh&command=-c&command=head+-n+1+%2Fsys%2Ffs%2Fcgroup%2Fcpu.weight&container=c1&stderr=true&stdout=true)
  STEP: deleting pod @ 11/18/24 06:57:00.586
  I1118 06:57:00.590514 1624 helper.go:124] Waiting up to 7m0s for all (but 0) nodes to be ready
  STEP: Destroying namespace "pod-resize-tests-4207" for this suite. @ 11/18/24 06:57:00.6
• [4.576 seconds]
------------------------------
```

That's why I guessed remaining pods at resize tests had caused a failure at Node Container Manager test:
https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/test/e2e_node/node_container_manager_test.go#L273-L277

**Comment by dims** [comment] 2024-11-20 23:54
All the jobs have recovered after the revert:

https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial

**Comment by pacoxu** [comment] 2024-11-22 03:42
Most cases here should be fixed after the revert.

I still find some flakes in alpha CI: 
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features
  - Kubernetes e2e suite.[It] [sig-node] Pod InPlace Resize Container [Serial] [Feature:InPlacePodVerticalScaling] [NodeAlphaFeature:InPlacePodVerticalScaling] Burstable QoS pod, one container with cpu & memory requests - decrease memory request

**Comment by pacoxu** [comment] 2024-11-22 03:43
Can we close this issue?

**Closed** 2024-11-25 15:58 UTC
Labels: sig/node, kind/failing-test, triage/accepted
