### ISSUE TITLE
Bazel fail on pkg/controller/node:go_default_test 0.00s

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#40295] opened 2017-01-23 14:30 UTC
`pkg/controller/node:go_default_test 0.00s` from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40293/pull-kubernetes-bazel/1845/

`E0123 14:17:52.166468       6 controller_utils.go:245] couldn't parse version "" of node could not parse "" as version`

@mikedanese you're the bazel guy, right?

**Comment by mikedanese** [comment] 2017-01-23 15:51
This looks like a plain old unit test flake. @gmarek is test owner

**Comment by gmarek** [comment] 2017-01-26 13:30
Actually it's caused by:
```
--- FAIL: TestMonitorNodeStatusEvictPodsWithDisruption (0.32s)
	nodecontroller_test.go:1236: Zone is partially disrupted - eviction should take place.: expected pod eviction: true, got false
```
which seems scary. I'll need to take a look at that in first free cycles.

**Comment by spxtr** [comment] 2017-01-27 07:13
This is super flaky: https://k8s-testgrid.appspot.com/google-unit#bazel

**Comment by gmarek** [comment] 2017-01-27 08:43
Super flaky is rather overstatement for test that failed 5 times in the bazel test history:) I won't have time to look into it before week of Feb. 6th.

**Comment by jbeda** [comment] 2017-02-10 19:35
Hit this: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36101/pull-kubernetes-bazel/4564/

**Comment by spxtr** [comment] 2017-02-10 19:48
#39975 ?

**Comment by sttts** [comment] 2017-02-22 15:45
Duplicate of https://github.com/kubernetes/kubernetes/issues/39975

**Comment by wojtek-t** [comment] 2017-03-13 14:03
#39975 (which I agree that this is a dup of) is claimed to be fixed. Closing.

**Comment by kargakis** [comment] 2017-03-16 14:52
Still an issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/43217/pull-kubernetes-bazel/10247/

**Comment by liggitt** [comment] 2017-03-16 15:03
wrong issue, real issue is https://github.com/kubernetes/kubernetes/issues/39975

**Closed by liggitt** 2017-03-16 15:03 UTC
Labels: kind/flake
