### ISSUE TITLE
`kubectl diff` downloads" the OpenAPI at least once per object

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#97939] opened 2021-01-12 00:42 UTC

**Comment by julianvmodesto** [comment] 2021-01-12 01:20
/close

Duplicate of https://github.com/kubernetes/kubernetes/issues/97940

**Closed** 2021-01-12 01:20 UTC
Labels: needs-sig, needs-triage

**Comment by apelisse** [comment] 2021-01-12 02:13
No clue what happened here :-)
