### ISSUE TITLE
Unit tests take more than an hour to run

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25940] opened 2016-05-20 03:23 UTC
I think yesterday they were running in under 40 minutes.

I did https://github.com/kubernetes/contrib/pull/1022 because the submit queue is timing out before merging after running tests. I will try to push it live tonight. But we need to figure out what caused this.

**Comment by lavalamp** [comment] 2016-05-20 03:24
People who might want to be aware of this: @ixdy @krousey @smarterclayton @thockin @bgrant0607

**Comment by thockin** [comment] 2016-05-20 03:54
I am gathering times right now, hoping to get a suspect

**Comment by thockin-cc** [comment] 2016-05-20 04:36
Looking at go {builld,test} -x times, nothing stands out.  No one command
is dominating.  The vast majority of individual commands complete in < 1
sec.

$ cat make.times | awk -F: '{if (prev == 0) { prev=$1 } t=$1-prev; print t;
prev=$1}' | sort -n | uniq -c
  15292 0
    690 1
     23 2
      8 3
      2 4
      2 5
      1 6
      1 8
      2 10

**Comment by lavalamp** [comment] 2016-05-20 04:36
Did the number of times we run things change?
Maybe something is slower on Jenkins?

**Comment by bgrant0607** [comment] 2016-05-20 06:32
Did we increase the number of dimensions of the test matrix? (e.g., twice as many tests in order to test protobuf)

**Comment by krousey** [comment] 2016-05-20 16:35
If I go back to February 20 (furthest back I could find), it seems it took ~20 minutes: https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-test-go/8565/build-log.txt

And now it takes ~55 minutes, plus spending another 20-60 minutes in the queue waiting to be run.

**Comment by smarterclayton** [comment] 2016-05-20 16:40
We added the protobuf storage dimension @wojtek-t

**Comment by ixdy** [comment] 2016-05-20 17:44
Yeah, it has taken close to an hour for a while now. There is also a high amount of variance run-to-run depending what else is happening on the Jenkins VM, I think.

**Comment by ixdy** [comment] 2016-05-20 17:45
cc @kubernetes/sig-testing

**Comment by smarterclayton** [comment] 2016-05-20 18:02
Coverage is really bad - have we disabled that on the official runs?  That
forces a unique go test compilation per.

**Comment by ixdy** [comment] 2016-05-20 18:47
We haven't done coverage runs in a long while because it's so slow.

**Comment by wojtek-t** [comment] 2016-05-21 09:24
@smarterclayton - the protobuf storage test I added is only in test-update-storage-objects which is the fastest from all tests. So I really doubt it's because of that.

**Comment by wojtek-t** [comment] 2016-05-21 09:27
But when I'm looking into artifacts/ directory for test runs from Jenkins, e.g.:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25285/kubernetes-pull-test-unit-integration/26504/artifacts/

there are 12 different files (6 groups of tests: xml, stdout for each of them).

And I'm pretty sure we used to have less than 6 groups of tests even few weeks ago. Are we sure we didn't increase the number of dimensions recently?

**Comment by ixdy** [comment] 2016-05-26 22:14
We [run `hack/build-go.sh` in unit test runs](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/test-dockerized.sh#L55), which is probably gratuitous. It stops us from running the rest of the tests if things are horribly broken, but it also means we duplicate work with the e2e build.

We also run several dimensions for each of `KUBE_TEST_API_VERSIONS` and `KUBE_TEST_ETCD_PREFIXES` (https://github.com/kubernetes/kubernetes/blob/master/hack/test-go.sh#L61-L65). We should probably run just one of each in PR builds, but I don't know what to choose.

**Comment by smarterclayton** [comment] 2016-05-26 22:16
I'm trying to think of when they actually caught anything.  Randomize
and pick one of each?

**Comment by fejta** [comment] 2016-05-27 01:27
@smarterclayton good idea! I want tests to be consistent between runs so I'm just going to pick one for each at random.

@ixdy Nice info! Sent out two PRs for this (one to reduce the precommit set, a second to ensure the postcommit set does the full thing)

**Comment by fejta** [comment] 2016-05-27 03:28
@ixdy has opinions about the right way to make this happen

**Comment by ixdy** [comment] 2016-05-27 03:55
The issue is that we don't yet have the PR Jenkins in source control (https://github.com/kubernetes/test-infra/pull/18 is a WIP), so we have no particularly great place to override the defaults. We'll probably have to do it in Jenkins directly, but then we want to be sure we're picking the right values.

I'm not super comfortably picking a random set of API versions for `KUBE_TEST_API_VERSIONS`, and I would appreciate some guidance.

In `hack/test-go.sh`, we have
* v1,extensions/v1beta1,metrics/v1alpha1,federation/v1alpha1
* v1,autoscaling/v1,batch/v1,batch/v2alpha1,extensions/v1beta1,apps/v1alpha1,metrics/v1alpha1,federation/v1alpha1,policy/v1alpha1

Whereas in `hack/test-integration.go`, we have
* v1,extensions/v1beta1
* v1,autoscaling/v1,batch/v1,apps/v1alpha1,policy/v1alpha1,extensions/v1beta1

`KUBE_TEST_ETCD_PREFIXES` is only set in `hack/test-go.sh`, with the following values:
* registry
* kubernetes.io/registry

**Comment by ixdy** [comment] 2016-05-27 08:35
OK, I've figured out part of the issue: we currently run unit tests 2 times, and the integration test **4** times. And the integration test suite has some pretty slow tests:
* TestStressingCascadingDeletion takes around 4m30s
* TestOrphaning takes a bit over a minute
* TestUnschedulableNodes takes around a minute
* and a number of tests which take 10-30s, almost certainly due to polling intervals being too long

Why we run the integration test 4 times:
* In `hack/test-go.sh`, we break up the list of `KUBE_TEST_API_VERSIONS` and `KUBE_TEST_ETCD_PREFIXES` and try to run each once, but we don't run the full matrix. So if `KUBE_TEST_API_VERSIONS` is "1;2" and `KUBE_TEST_ETCD_PREFIXES` is "a;b" we'll test 1+a and 2+b.

In `hack/test-integration.sh`, we break up `KUBE_TEST_API_VERSIONS` there, and run `hack/test.go.sh test/integration` for each value of `KUBE_TEST_API_VERSIONS`. So if `hack/test-integration` has "3;4", we'll test 3+a and 3+b and 4+a and 4+b.

If I'm doing my git archaeology correctly, we've been running 2 runs of unit tests and 4 runs of integration tests ever since #20501 was merged.

My recommendation remains the same: we need to run fewer iterations of unit and integration tests in PR Jenkins.

**Comment by ixdy** [comment] 2016-05-27 08:44
At one point we did only run a few things in CI: #21352

Previous discussion of unit/integration getting slower: #21937 #24285

**Comment by wojtek-t** [comment] 2016-05-27 12:03
@lavalamp - what's the point in testing multiple "KUBE_TEST_ETCD_PREFIXES".
Since neither unit test nor integration tests don't test upgrades, I think it doesn't make any sense at all to test different values of those.
I will send a short PR for it.

**Comment by wojtek-t** [comment] 2016-05-27 13:28
I've sent our https://github.com/kubernetes/kubernetes/pull/26416 for review. This PR saves ~10-15 minutes on unit/integration tests. It's still not great, but at least better that it was.

**Comment by wojtek-t** [comment] 2016-05-27 13:52
BTW - I took a look into where we spend time in those runs and the biggest chunks are:
- 20m in hack/verify-all.sh (the biggest chunk seem to be verify_codecgen.sh ~7m)
- 2 x 5m - running unit tests
- 2 x 10m - running integration tests

We can try improving things, but generally, I don't think we will significantly reduce time neither unit or integration tests take. Which means that we are already at ~30m.

What we can do is to:
- either run unit tests and integration tests exactly once
- try to improve verify-* scripts

Or actually even run verify-* scripts in a separate suite. @lavalamp - any thoughts on this one?

**Comment by wojtek-t** [comment] 2016-05-27 14:10
@lavalamp 
Actually, I started wondering what's the point in running unit/integration tests with just a subset of api groups (my question especially applies to unit tests). 

I understand that we may want to switch some api groups to avoid running controllers to speed the up (or because they are in development can can interact badly with other controllers).
But for unit tests - it doesn't make sense. We should simply register everything we want to test, and just run those tests once.

**Comment by wojtek-t** [comment] 2016-05-27 14:24
And regarding verify-* scripts - we spend 1/3rd of those 20m on actually building necessary scripts one by one. Maybe building them all at once and then calling scripts from after-build/ directory would also help here...

**Comment by ixdy** [comment] 2016-05-27 17:00
I think we should still aim to run unit/integration tests exactly once in PR Jenkins. In post-submit Jenkins we can run both configurations.

If we do that, what's the proper `KUBE_TEST_API_VERSIONS` setting to use for PR Jenkins?

**Comment by ixdy** [comment] 2016-05-27 18:43
Feel free to assign back to me once we've decided what `KUBE_TEST_API_VERSIONS` to use.

**Comment by lavalamp** [comment] 2016-05-27 19:00
> what's the point in testing multiple "KUBE_TEST_ETCD_PREFIXES".
> Since neither unit test nor integration tests don't test upgrades, I think it doesn't make any sense at all to test different values of those.

The point is to keep it working. It doesn't have anything to do with upgrades. It is however fine to not run it as a *cross product* with the other choices, that is wrong and we used to not do that.

**Comment by wojtek-t** [comment] 2016-05-27 19:59
>
The point is to keep it working. It doesn't have anything to do with upgrades. It is however fine to not run it as a cross product with the other choices, that is wrong and we used to not do that.

OK, but do we need to run it in presubmit? Also, do we need to run it in unit tests? Noone ever was even close to breaking it...

To be honest, I think we have a dedicated unit/integration test to test this, instead of running the whole suite in that configuration...

**Comment by lavalamp** [comment] 2016-05-27 20:35
Yes, we could be more intelligent about this.

**Comment by mikedanese** [comment] 2016-05-27 21:03
By my calculations, testapi is used in 12% of packages:
```console
$ grep -r 'testapi' . | awk '{print $1}' | egrep '^\./pkg'|egrep '\.go:$' | sed 's/[a-z_]*\.go:$//' | sort | uniq | wc -l
63
$ find pkg -type d | wc -l
494
```

I'm going to start by only running those tests in the apigroup matrix

**Comment by lavalamp** [comment] 2016-05-27 21:46
Awesome!

**Comment by mikedanese** [comment] 2016-05-27 22:52
It takes 3 minutes on my workstation to compile all tests in pkg/ and it takes 30 seconds to execute them. I'm going to pivot and work on not recompiling per iteration. I hypothesis that will be more helpful than reducing the number of iterations (although I think we should do both).

**Comment by spxtr** [comment] 2016-05-27 23:04
This is somewhat related to #23648. All the `pkg/registry/*/etcd` tests waste a couple seconds per test spinning up and tearing down a server which adds up to several minutes per test-go run per api version.

**Comment by wojtek-t** [comment] 2016-05-28 20:00
@spxtr @ixdy @lavalamp - would it be possible to run: 1. unit & integration tests, 2. verify-all.sh script
in parallel?
Those two conceptually are independent, and this would basically divde the total time almost by 2.

**Comment by spxtr** [comment] 2016-05-28 20:23
Yes, I would like to split those apart.

**Comment by wojtek-t** [comment] 2016-05-29 09:39
@spxtr - actually, I did some quick experiment and it seems we can't simply run them in parallel, because they are affecting one another (hack/verify-codecgen.sh is generating some temporary files that are causing pain for unit tests).
However, in my opinion we should just split them into a separate suite, that would also be blocking merge.

In fact, I think that we need it anyway, because we will have more and more unit/integration tests and probably more and more verify scripts. So time they take will also increase. So splitting them into separate suite seems unavoidable.

**Comment by spxtr** [comment] 2016-05-30 07:59
Oh yes, sorry that's what I thought you meant. We should have them in two Jenkins jobs. Eventually we might want to pull the integration tests into their own job.

**Comment by goltermann** [comment] 2016-06-06 17:03
@mikedanese are you actively working on this one?  It's marked P0

**Comment by mikedanese** [comment] 2016-06-06 17:29
@goltermann I was out for the end of last week but I'm back on it today. The PR with the method I described above is #26585

**Comment by mikedanese** [comment] 2016-06-08 18:08
Is anyone working on splitting the jobs up yet? I'm going to experiment with breaking the integration tests into separate packages so they run in parallel.

**Comment by dims** [comment] 2016-06-09 11:03
Is this missing a milestone 1.3? (since it's a p0)

**Comment by wojtek-t** [comment] 2016-06-10 11:52
What we should also do is to split tests from cmd/integration into single pieces and migrate them to test/integration. I already started doing it in my free cycles.
This will reduce the amount of code we are compiling, and once @mikedanese PR is in, it will help even more.

**Comment by mikedanese** [comment] 2016-06-17 18:36
unit/integration is running at about 30 minutes.
verification is running at about 20 minutes.

Paralleling integration tests is the next thing that I think could knock some time off unit/integration suite but it involves starting an etcd per master and it's a non-trivial change.

**Closed** 2016-06-21 00:47 UTC
Labels: kind/bug, kind/flake, priority/P0, team/test-infra
