### ISSUE TITLE
Make metrics_grabber work with kubemark

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#44767] opened 2017-04-21 14:20 UTC
We're gathering a number of prometheus metrics during our performance test runs from the master machine. We should make it work for kubemark masters as well.

@kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment] 2017-05-05 21:26
Seems like this issue is a duplicate of https://github.com/kubernetes/kubernetes/issues/45038 (I guess I missed this one earlier).
@gmarek Can we close this now that it is fixed (unless there's something more to be done)?

**Closed** 2017-05-05 21:29 UTC
Labels: sig/scalability
