### ISSUE TITLE
CSI: kubelet removes NodeID annotation when a driver is restarted

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#71424] opened 2018-11-26 16:59 UTC
**What happened**:
When I restart pod with my driver and driver-registrar, node looses NodeID annotation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Kubernetes without any alpha features (local-up-cluster.sh in this case)

2. Start HostPath driver
    ```
    kubectl create serviceaccount csi-node-sa
    kubectl create serviceaccount csi-attacher
    kubectl apply -f test/e2e/testing-manifests/storage-csi/hostpath/hostpath/
    ```

3. Wait for everything to be Running

4. Check the node has annotation
    ```
    kubectl get node -o yaml

    annotations:
      csi.volume.kubernetes.io/nodeid: '{"csi-hostpath":"127.0.0.1"}'
    ```

4. Delete the node pod (deleting all pods here, we don't care about attacher/provisioner).
    ```
    kubectl delete pod --all
    ```
   
5. DaemonSet will start a new node pod with new registrar. Wait until the new pod gets Running.

6. Check the node **does not have the annotation**
    ```
    kubectl get node -o yaml

     <no annotations>
    ```

It's ~~100%~~ 80% reproducible in my local cluster. New driver-registrar deletes socket of the old registrar and creates new one. I can see in logs:

```
I1126 16:48:23.914792   31674 plugin_watcher.go:347] DeRegistering plugin {CSIPlugin csi-hostpath} at path /var/lib/kubelet/plugins_registry/csi-hostpath-reg.sock
I1126 16:48:23.914886   31674 csi_plugin.go:227] kubernetes.io/csi: registrationHandler.DeRegisterPlugin request for plugin csi-hostpath
I1126 16:48:23.919670   31674 csi_plugin.go:116] kubernetes.io/csi: Trying to validate a new CSI Driver with name: csi-hostpath endpoint: /var/lib/kubelet/plugins/csi-hostpath/csi.sock versions: 1.0.0, foundInDeprecatedDir: false
I1126 16:48:23.919756   31674 csi_plugin.go:137] kubernetes.io/csi: Register new plugin with name: csi-hostpath at endpoint: /var/lib/kubelet/plugins/csi-hostpath/csi.sock
```

So the old socket was deregistered very shortly before new one got registered. IMO these two operations collide with each other and the deregistration "wins" somehow.

**Environment**:
- Kubernetes version (use `kubectl version`): today's master

/kind bug
/sig storage

@saad-ali @bertinatto @msau42 @vladimirvivien @verult @davidz627

**Comment by jsafrane** [comment] 2018-11-26 17:13
Yeah, InstallCSIDriver runs in parallel with UninstallCSIDriver. UninstallCSIDriver updates the node while InstallCSIDriver is getting the current value. In most cases, InstallCSIDriver gets the old value (still with annotations) and does not update the node. Some locks are missing there.

But even with the locks it will be racy. We must make sure that UninstallCSIDriver grabs the lock before InstallCSIDriver, so the annotation is always added in the end.

**Comment by saad-ali** [comment] 2018-11-26 17:36
We should see if we can handle this at the `plugin_watcher` layer so that it works for everyone. 

We could use [goroutinemap](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/goroutinemap/goroutinemap.go) where key is the CSI driver name to ensure that two operations are not started in parallel for the same driver. But that's not the hard part, like you mentioned, the tricky part is ensuring the correct order of operations between create/delete events.

**Comment by vladimirvivien** [comment] 2018-11-26 19:54
I am investigating this today.  Will update with fix/finding on a PR.

**Comment by davidz627** [comment] 2018-11-26 20:07
A best practice for the driver should be to remove the registration sockets when the driver is uninstalled: this would generally remedy this problem for that particular driver in normal uninstall->install cases.
We do it for GCE PD here: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L26

I still think the underlying problem should be resolved though :+1:

**Comment by AishSundar** [comment] 2018-11-27 00:03
Is there an incoming PR for this?

**Comment by saad-ali** [comment] 2018-11-27 00:51
@vladimirvivien has been working on this today. He believes that he has the problem understood and is able to repro it. He is working on a fix/verification (which takes time since it requires multiple runs to repro/verify). He will add more information soon as he can.

**Comment by vladimirvivien** [comment] 2018-11-27 03:53
After spending a good amount of time chasing the cause for this issue, it came down to the plugin_watcher code that can handle fsnotify CREATE and fsnotify DELETE events concurrently here: https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L114
The `goroutine` at that line number causes both CREATE and DELETE events to be handled concurrently.  This can create race conditions in plugins by calling `Handler.RegisterPlugin` and `Handler.DeRegisterPlugin` concurrently.  This is fixed in this PR https://github.com/kubernetes/kubernetes/pull/71440 (see for detail of fix).

**Comment by vladimirvivien** [comment] 2018-11-27 14:59
@davidz627 that is a great suggestion, will make not of it for documentation.

**Closed** 2018-11-28 01:08 UTC
Labels: kind/bug, priority/critical-urgent, sig/storage

**Comment by jianglingxia** [comment] 2019-04-09 03:19
hi,I test in v1.13 and the problem existed!
my csi plugin running,but the node annotation can not labeled!
[root@paas-controller-111-111-111-118:/home/ubuntu]$ kubectl get po -n kube-system -o wide -w
NAME                                READY     STATUS    RESTARTS   AGE       IP                NODE
csi-attacher-cinderplugin-0         2/2       Running   0          4d        111.111.111.116   111.111.111.116
csi-nodeplugin-cinderplugin-cpq7m   2/2       Running   0          14s       111.111.111.118   111.111.111.118
csi-nodeplugin-cinderplugin-h48dh   2/2       Running   0          14s       111.111.111.116   111.111.111.116

Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
then cause my pod can not attached

I0409 01:50:59.173468       1 csi_handler.go:388] Saving attach error to "csi-46866cc91b27a53461216c2dab85709a01f1704004457f6e3b9f0f4beb26bf8e"
I0409 01:50:59.183080       1 controller.go:139] Ignoring VolumeAttachment "csi-46866cc91b27a53461216c2dab85709a01f1704004457f6e3b9f0f4beb26bf8e" change
I0409 01:50:59.215247       1 csi_handler.go:398] Saved attach error to "csi-46866cc91b27a53461216c2dab85709a01f1704004457f6e3b9f0f4beb26bf8e"
I0409 01:50:59.215281       1 csi_handler.go:103] Error processing "csi-46866cc91b27a53461216c2dab85709a01f1704004457f6e3b9f0f4beb26bf8e": failed to attach: node "111.111.111.116" has no NodeID annotation

**Comment by tiger0425** [comment] 2019-05-14 01:49
AttachVolume.Attach failed for volume "pvc-fbc1494b-758e-11e9-bfc0-005056b4b2af" : node "rancher196" has no NodeID annotation

**Comment by tiger0425** [comment] 2019-05-14 02:14
Docker版本 18.9.6
Kubelet版本 v1.12.0
操作系统 CentOS Linux 7
内核版本 3.10.0-957.10.1.el7.x86_64

ttachVolume.Attach failed for volume "pvc-341bbf51-75ed-11e9-bfc0-005056b4b2af" : node "crawler203" has no NodeID annotation


Dashboard/volume/pvc-341bbf51-75ed-11e9-bfc0-005056b4b2af
Volume Details
State:Detached
Health:
Frontend:Block Device
Attached Node & Endpoint :
Size:2 Gi
Actual Size:0 Bi
Base Image:
Engine Image:rancher/longhorn-engine:v0.4.1
Created:10 minutes ago
Latest Backup:

**Comment by timchenxiaoyu** [comment] 2019-07-21 02:22
I don't find code in kubelet  1.12.0 about this problem.    strange!
