### ISSUE TITLE
Flake: Horizontal pod autoscaling [Autoscaling Suite] should scale from 1 pod to 3 pods and from 3 to 5 (via deployment, with scale resource: CPU)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17584] opened 2015-11-20 20:08 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1766/

@davidopp please find an owner.

**Comment by piosz** [comment] 2015-11-20 21:04
cc @jszczepkowski @mwielgus

**Comment by piosz** [comment] 2015-11-30 09:42
duplicate of #16425

**Closed by piosz** 2015-11-30 09:42 UTC
Labels: kind/flake, priority/P1, team/control-plane
