### ISSUE TITLE
Update kubelet perf tests using the new metrics API 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#23961] opened 2016-04-07 00:05 UTC
Forked from https://github.com/kubernetes/kubernetes/issues/23956#issuecomment-206625651

kubelet perf tests are using old stats apis. They need to be ported over to use the summary API. We should fix this. 

cc/ @kubernetes/goog-node

**Comment by andyzheng0831** [comment] 2016-04-07 17:09
cc/ @roberthbailey @fabioy @wonderfly, the 3 failed GKE e2e test cases in our Jenkins are all due to this issue.

**Comment by andyzheng0831** [comment] 2016-04-07 19:10
@dchen1107 No assignee? And should we target this for milestone 1.2?

**Comment by yujuhong** [comment] 2016-04-07 19:42
I will work on it this week.

**Comment by dchen1107** [comment] 2016-04-07 20:00
No need to target for milestone 1.2. New Kubelet metrics API is still in alpha, and the old ones are not deprecated yet. Also this is a cleanup task, and it is not the root cause of your issue:  #23956

**Comment by dchen1107** [comment] 2016-04-07 20:02
UPDATE: The test itself is hard-coded with docker's cgroup path. We should fix that as soon as possible.

**Comment by andyzheng0831** [comment] 2016-04-07 20:11
The root cause is that cgroup "docker-daemon" is hard-coded in the kubelet_perf.go. But as https://github.com/kubernetes/kubernetes/issues/23956#issuecomment-206622011, this cgroup should not be created when systemd manages docker. Clean up this part should be enough for our testing.

**Comment by sjpotter** [comment] 2016-04-07 20:33
this also impacts rktnetes, working around it by forcing it to think its not on gce/gke so it only uses / cgroup as don't have any other other static cgroups it is looking for

**Comment by dchen1107** [comment] 2016-04-07 21:16
Ok, since we decided to have a patch release including #23996, we need to address this very test issue for 1.2 too. cc/ @roberthbailey

**Comment by yujuhong** [comment] 2016-04-08 23:08
> this also impacts rktnetes, working around it by forcing it to think its not on gce/gke so it only uses / cgroup as don't have any other other static cgroups it is looking for, but in reality doesn't help much, just going to mark them as bad tests right now for us

For `rkt` and *other container runtimes*, I'll upload a separate PR to *not* check the runtime stats at all. The PR base the decision on the container runtime type reported by the node status. Any objections? @sjpotter @derekwaynecarr

**Comment by yujuhong** [comment] 2016-05-10 00:11
#24003 was merged long ago. Closing the issue.

**Closed by yujuhong** 2016-05-10 00:11 UTC
Labels: area/test, priority/P1, team/node
