### ISSUE TITLE
kubectl oidc plugin: some providers (okta) don't return an id_token on refresh

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#51501] opened 2017-08-29 06:58 UTC
/kind bug
/sig auth

/assign @ericchiang 

Some OpenID Connect providers, namely Okta, don't return an id_token during a refresh[1]. The spec allows this[2] so their not non-compliant, but this means the error message when kubectl hits this case needs to improve[3]. Right now it's just:

```
Connection error: Get https://example.com:8443/api: token response did not contain an id_token
```

Maybe something long winded, like:

```
Connection error: Get https://example.com:8443/api: oidc refresh response from https://accounts.foo.com did not contain an id_token, either the scope "openid" wasn't requested upon login, or the provider doesn't support id_tokens as part of the refresh response.
```

Also might be worth documenting on kubernetes.io

[1] https://developer.okta.com/docs/api/resources/oidc.html#response-parameters-4
[2] https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
[3] https://github.com/kubernetes/client-go/blob/9675d048204baf818bb24f7c74d0e64f6254902e/plugin/pkg/client/auth/oidc/oidc.go#L254-L257

cc @grillz @thomastaylor312 @gtaylor since I know some of you are trying to use Okta as a provider.

**Comment by liggitt** [comment] 2017-09-24 03:39
actually, is this a dupe of https://github.com/kubernetes/kubernetes/issues/36847?

**Comment by gtaylor** [comment] 2017-09-24 16:48
Seems like it. Though, the issue description is much more detailed than #36847.

**Comment by liggitt** [comment] 2017-09-25 04:03
added extra details to #36847, will track there

**Closed by liggitt** 2017-09-25 04:03 UTC
Labels: kind/enhancement, sig/auth
