### ISSUE TITLE
Unable to access external IP from kubernetes cluster (Bare Metal)-1.14

### ISSUE THREAD

**Issue by prasann004** [kubernetes/kubernetes#75875] opened 2019-03-29 08:02 UTC
1) I am not able to connect my SQLSERVER database from the pods. I tried doing a telnet to 192.*.*.*  1433 and it connected.
logs: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections
2)My application uses some other API's which are hosted on my company's intranet and communicate on port 8199 but I couldn't get data from them either. I tried setting the IP of the API in /etc/resolv.conf , after that I was able to ping but pods couldn't establish a connection to the API.

@kubernetes/wg-k8s-infr
@spiffxp

**Comment by neolit123** [comment] 2019-03-29 23:42
/close 
duplicate of https://github.com/kubernetes/kubernetes/issues/75877

**Closed by neolit123** 2019-03-29 23:42 UTC
Labels: needs-sig, triage/support
