### ISSUE TITLE
 Unable to mount volumes for pod "glusterfs_default": exit status 1

### ISSUE THREAD

**Issue by moink635** [kubernetes/kubernetes#12575] opened 2015-08-12 08:07 UTC
Much appreciated if some helps 
Unble to mount volumes for pod 
Giving this error 
1)    failedMount     Unable to mount volumes for pod "glusterfs_default": exit status 1
2) failedSync      Error syncing pod, skipping: exit status 1

mounting with glusterfs code is below 

gluster_endpoints.json

```
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "glusterfs-cluster"
  },
  "subsets": [
    {
      "addresses": [
        {
          "IP": "192.168.1.63"
        }
      ],
      "ports": [
        {
          "port": 1
        }
      ]
    }
  ]
}
```

gluster_pod.json

```
{
    "apiVersion": "v1",
    "id": "glusterfs",
    "kind": "Pod",
    "metadata": {
        "name": "glusterfs"
    },
    "spec": {
        "containers": [
            {
                "name": "glusterfs",
                "image": "kubernetes/pause",
                "volumeMounts": [
                    {
                        "mountPath": "/mnt",
                        "name": "glusterfsvol"
                    }
                ]
            }
        ],
        "volumes": [
            {
                "name": "glusterfsvol",
                "glusterfs": {
                    "endpoints": "glusterfs-cluster",
                    "path": "gvol0",
                    "readOnly": true
                }
            }
        ]
    }
}
```

if any thing i need to update in code?
Thanks waiting for reply

**Comment by piosz** [comment] 2015-08-12 10:31
The problem is with https://github.com/GoogleCloudPlatform/kubernetes/tree/8813c955182e3c9daae68a8257365e02cd871c65/examples/glusterfs

@caesarxuchao  could you please take a look?

**Comment by moink635** [comment] 2015-08-12 10:44
Yes, i have already gone through  with that, but getting same issue?

**Comment by moink635** [comment] 2015-08-12 11:40
Mounting arguments: 192.168.1.63:192.168.1.63:/gvol0 /tmp/mesos/slaves/20150812-121915-1057073344-5050-2582-S0/frameworks/20150812-121915-1057073344-5050-2582-0000/executors/8afd73d6c887f893_k8sm-executor/runs/42646d7e-1c3d-4d2b-9df3-4e8b3186ffb5/pods/ae9912e4-40ce-11e5-a709-080027beea41/volumes/kubernetes.io~glusterfs/glusterfsvol glusterfs [ro]
Output: ERROR: failed to create logfile "/var/log/glusterfs/tmp-mesos-slaves-20150812-121915-1057073344-5050-2582-S0-frameworks-20150812-121915-1057073344-5050-2582-0000-executors-8afd73d6c887f893_k8sm-executor-runs-42646d7e-1c3d-4d2b-9df3-4e8b3186ffb5-pods-ae9912e4-40ce-11e5-a709-080027beea41-volumes-kubernetes.io~glusterfs-glusterfsvol.log" (File name too long)
ERROR: failed to open logfile /var/log/glusterfs/tmp-mesos-slaves-20150812-121915-1057073344-5050-2582-S0-frameworks-20150812-121915-1057073344-5050-2582-0000-executors-8afd73d6c887f893_k8sm-executor-runs-42646d7e-1c3d-4d2b-9df3-4e8b3186ffb5-pods-ae9912e4-40ce-11e5-a709-080027beea41-volumes-kubernetes.io~glusterfs-glusterfsvol.log
Mount failed. Please check the log file for more details.

**Comment by moink635** [comment] 2015-08-12 11:41
Output: ERROR: failed to create logfile "/var/log/glusterfs/tmp-mesos-slaves-20150812-121915-1057073344-5050-2582-S0-frameworks-20150812-121915-1057073344-5050-2582-0000-executors-8afd73d6c887f893_k8sm-executor-runs-42646d7e-1c3d-4d2b-9df3-4e8b3186ffb5-pods-ae9912e4-40ce-11e5-a709-080027beea41-volumes-kubernetes.io~glusterfs-glusterfsvol.log" (File name too long)

**Comment by caesarxuchao** [comment] 2015-08-13 06:46
Sorry, I'm busy with a PR. I will take a look this week.

**Comment by caesarxuchao** [comment] 2015-08-16 23:29
@moink635, I can't reproduce the problem. I think it's platform specific. Could you describe your cluster set-up?

The error message seems clear, I guess specifying the name of the log file in options [here](https://github.com/kubernetes/kubernetes/blob/7c9bbef96ed7f2a192a1318aa312919b861aee00/pkg/volume/glusterfs/glusterfs.go#L220) will solve the problem. @rootfs could you take a look?

**Comment by rootfs** [comment] 2015-08-17 14:56
@moink635 the long file name is suspcious, I don't find such message in k8s anywhere. Where did you get it?

**Comment by moink635** [comment] 2015-08-19 12:35
Thanks for your reply,

**Comment by rootfs** [comment] 2015-08-19 13:52
@moink635 `hostDir` is a workaround, it still gets problems if you don't have glusterfs mounted on some hosts. 
do you happen to have any clues about source of the long file name error?

**Comment by moink635** [comment] 2015-08-21 06:49
As i was using v1 api so, it's not hostDir --> hostPath  and work for me,
for long name i don't have any idea  thanks.

**Comment by bodgit** [comment] 2015-09-10 10:12
I'm running into the same problem:

```
E0910 09:54:38.580871   21639 mount_linux.go:103] Mount failed: exit status 1
Mounting arguments: 10.4.35.66:gv0 /tmp/mesos/slaves/20150804-092332-1680016394-5050-1110-S0/frameworks/20150715-130216-1713570826-5050-1229-0000/executors/e3df79b24ad1d75b_k8sm-executor/runs/cf292370-4ee6-4fa1-8e38-51a980db170e/pods/4c4faec6-57a1-11e5-8e05-005056b10d4c/volumes/kubernetes.io~glusterfs/glusterfsvol glusterfs [ro]
Output: ERROR: failed to create logfile "/var/log/glusterfs/tmp-mesos-slaves-20150804-092332-1680016394-5050-1110-S0-frameworks-20150715-130216-1713570826-5050-1229-0000-executors-e3df79b24ad1d75b_k8sm-executor-runs-cf292370-4ee6-4fa1-8e38-51a980db170e-pods-4c4faec6-57a1-11e5-8e05-005056b10d4c-volumes-kubernetes.io~glusterfs-glusterfsvol.log" (File name too long)
ERROR: failed to open logfile /var/log/glusterfs/tmp-mesos-slaves-20150804-092332-1680016394-5050-1110-S0-frameworks-20150715-130216-1713570826-5050-1229-0000-executors-e3df79b24ad1d75b_k8sm-executor-runs-cf292370-4ee6-4fa1-8e38-51a980db170e-pods-4c4faec6-57a1-11e5-8e05-005056b10d4c-volumes-kubernetes.io~glusterfs-glusterfsvol.log
Mount failed. Please check the log file for more details.

E0910 09:54:38.580936   21639 glusterfs.go:234] Glusterfs: mount failed: exit status 1
E0910 09:54:38.581068   21639 kubelet.go:1190] Unable to mount volumes for pod "glusterfs_default": exit status 1; skipping pod
E0910 09:54:38.636056   21639 pod_workers.go:111] Error syncing pod 4c4faec6-57a1-11e5-8e05-005056b10d4c, skipping: exit status 1
```

I think it's possibly triggered by trying to run Kubernetes on Mesos same as @moink635. I'm guessing by default, the log file for glusterfs is constructed from the mountpoint with any `/`'s mapped to `-`'s and this is under so many directories when running on mesos that the resulting filename exceeds the filesystem limitations on file length (XFS in my case). I can reproduce by simply trying to run:

```
$ touch tmp-mesos-slaves-20150804-092332-1680016394-5050-1110-S0-frameworks-20150715-130216-1713570826-5050-1229-0000-executors-e3df79b24ad1d75b_k8sm-executor-runs-cf292370-4ee6-4fa1-8e38-51a980db170e-pods-4c4faec6-57a1-11e5-8e05-005056b10d4c-volumes-kubernetes.io~glusterfs-glusterfsvol.log
touch: cannot touch ‘tmp-mesos-slaves-20150804-092332-1680016394-5050-1110-S0-frameworks-20150715-130216-1713570826-5050-1229-0000-executors-e3df79b24ad1d75b_k8sm-executor-runs-cf292370-4ee6-4fa1-8e38-51a980db170e-pods-4c4faec6-57a1-11e5-8e05-005056b10d4c-volumes-kubernetes.io~glusterfs-glusterfsvol.log’: File name too long
```

It turns out XFS has a maximum filename length of 255 characters and this particular filename is 284 characters long. Using a log file option to create something slightly more succinct in length would fix this.

**Comment by rootfs** [comment] 2015-09-10 12:30
cool, sounds a bug to me, will fix it. thanks for getting the details. @bodgit @moink635

**Comment by bodgit** [comment] 2015-09-10 12:38
I don't know how you're planning to fix it but I've been experimenting with trying to add a logFile option to the glusterfs volume. I'm just in the process of trying to spin up a test Kubernetes environment. If I manage to get it working I can send a PR.

**Comment by rootfs** [comment] 2015-09-10 12:48
right, that's the best way to fix it.

**Comment by bodgit** [comment] 2015-09-10 15:17
I've raised #13807 with my changes, could you take a look and advise if any more changes are required, particularly around my comment on the Persistent Volume bit in `getGlusterVolumeSource()`.

**Comment by caesarxuchao** [comment] 2015-10-02 23:33
@rootfs @bodgit  can we close this? I think #13807 fixed this.

**Comment by bodgit** [comment] 2015-10-05 11:59
Yes, I think this can be closed now.

**Comment by caesarxuchao** [comment] 2015-10-05 16:38
Thank you @bodgit

**Closed by caesarxuchao** 2015-10-05 16:38 UTC
Labels: priority/P2, team/cluster
