### ISSUE TITLE
Update services.md

### ISSUE THREAD

**Issue by jonbaierCTP** [kubernetes/kubernetes#16293] opened 2015-10-26 19:20 UTC
Cannot create service without selector as described here: http://kubernetes.io/v1.0/docs/user-guide/services.html#services-without-selectors

first created service with this YAML:

    apiVersion: v1
    kind: Service
    metadata:
      name: custom-service  
    spec:
      type: LoadBalancer
      ports:
      - name: http
        protocol: TCP
        port: 80

Second created this endpoint YAML (Where AUXILARY SERVICE IP was an IP for a second Service already running in the cluster):

    apiVersion: v1
    kind: Endpoints
    metadata:
      name: custom-service
    subsets:
    - addresses:
      - IP: <AUXILARY SERVICE IP>
      ports:
        - port: 80
          protocol: TCP

After if I run  kubectl describe service <service_name>` no endpoints are listed and the service IP (internal and external_) do not work

**Comment by jonbaierCTP** [comment] 2015-10-26 20:28
Solved, endpoint needs port name specified like so:

    apiVersion: v1
    kind: Service
    metadata:
      name: custom-service  
    spec:
      type: LoadBalancer
      ports:
      - name: http
        protocol: TCP
        port: 80

Example on documentation page just needs an update

**Comment by dalanlan** [comment] 2015-10-27 07:17
The doc is kinda out of date, indeed. Yet i cannot reproduce your issue.
Following manifest works fine for me. I cannot really see the necessity of `port name specification`. Am i missing anything? 
```
{
    "kind": "Endpoints",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service1"
    },
    "subsets": [
        {
            "addresses": [
                { "IP": "10.168.123.53" }
            ],
            "ports": [
                { "port": 9999 }
            ]
        }
    ]
}

```

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service1"
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": 9999
            }
        ]
    }
}
```

**Comment by jonbaierCTP** [comment] 2015-10-27 15:59
Is it possible that it's a version issue? I am using 1.0 and not 1.1. 

I also was using YAML for the most part. Although I did recreate the endpoint with JSON as a test once and still had the issue.

**Comment by bgrant0607** [comment] 2015-11-13 17:56
cc @kubernetes/goog-cluster

**Comment by bprashanth** [comment] 2016-02-16 21:39
I tried this and the only thing that bit me was IP is now lowercase, this appears to be fixed in HEAD: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#services-without-selectors. Please re-open if the issue persists.

**Closed by bprashanth** 2016-02-16 21:39 UTC
Labels: kind/documentation, priority/P2, team/cluster, team/ux
