### ISSUE TITLE
kubectl apply -f some-deployment.yaml leaks replica sets

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#38745] opened 2016-12-14 04:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.0

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS beta channel

**What happened**: Rolling out updates to our Deployment objects by calling `kubectl apply -f config.yaml` (where config.yaml contains a Deployment object) results in unbounded counts of empty replica sets in our cluster(s).

**What you expected to happen**: No leaked replica sets

**How to reproduce it** (as minimally and precisely as possible): See above.

**Anything else do we need to know**:

**Comment by hjacobs** [comment] 2016-12-15 21:43
We also see "leaked" replica sets (left behind when deleting deployments) when creating new deployments using Kubernetes 1.4.7.

**Comment by chrisleck** [comment] 2016-12-16 22:14
I think this is due to the default for `Deployment.RevisionHistoryLimit` being `nil`, meaning infinite.  Can we change the default on this to 5 or 10 without breaking the world?

**Comment by bgrant0607** [comment] 2017-03-21 17:18
Dupe of #23597.

Needs to be changed in a new API version.

**Closed by bgrant0607** 2017-03-21 17:18 UTC
