### ISSUE TITLE
Kubernetes create pod using OpenStack cinder on ubuntu is error

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#17706] opened 2015-11-24 02:54 UTC
I install kubernetes 1.1.1 in ubuntu and check out the official url http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html to create a cinder volume.

1.I config the following content in the path "/etc/kubernetes/cloud_config". [Global] auth-url=https://*****.v2.0 username=user password=pass region=regionOne tenant-id=0c331a1df18571594d49fe68asa4e
2.I add the following contend in "/etc/default/kubelet"
--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud_config

3.restart the kubernetes service.

4.create cinder
5.cluster/kubectl.sh create -f examples/mysql-cinder-pd/mysql.yaml 

Now I can connect with openstack cinder. But when I create a mysql pod. The pod status is running first, then it changes to be error status. 
I check out the kubelet.log. 
I find the error Unable to find pair interface, setting up all interfaces: exec: "nsenter": executable file not found in $PATH

**Comment by wangqunOne** [comment] 2015-11-24 03:00
@spothanis

**Comment by swagiaal** [comment] 2015-11-24 16:38
@wangqunOne I don't think this is a cinder issue. It looks like `nsenter` is required by `setUpContainer` to set up container networking. Make ure `nsenter` is installed on the node

**Comment by HackToday** [comment] 2015-11-25 04:37
@swagiaal  we have installed the nsenter.  Still we find that 

$ binaries/kubectl get pods
NAME      READY     STATUS             RESTARTS   AGE
mysql     0/1       CrashLoopBackOff   2          40s

#docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                      PORTS  
136977b9e6bb        mysql                                  "/entrypoint.sh mysql"   18 seconds ago      Exited (1) 15 seconds ago          ysql.a27fd072_mysql_default_637ee404-932d-11e5-99e5-fa163ea05ea6_2836649d
afee2beb2b6a        mysql                                  "/entrypoint.sh mysql"   27 seconds ago      Exited (1) 21 seconds ago          ysql.a27fd072_mysql_default_637ee404-932d-11e5-99e5-fa163ea05ea6_4b102e71
43f0c8bf3bfb        gcr.io/google_containers/pause:0.8.0   "/pause"                 34 seconds ago      Up 27 seconds                      OD.429f036b_mysql_default_637ee404-932d-11e5-99e5-fa163ea05ea6_9a097d2d

#docker logs 136977b9e6bb
Initializing database
2015-11-25T04:31:55.084190Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2015-11-25T04:31:55.087115Z 0 [ERROR] Aborting


So it seems container not worked for cinder.


ping @spothanis

**Comment by spothanis** [comment] 2015-11-25 05:22
@HackToday can you try bringing up mysql with out the volume?

**Comment by HackToday** [comment] 2015-11-25 08:42
@spothanis we can bring it successfullly without volume for mysql

seems mysql container have issue for 
/# mkdir /wokr
root@03e4cfe929f4:/# mkdir /wokr/lost+found
root@03e4cfe929f4:/# mysqld --initialize-insecure=on --datadir="/wokr/"        
2015-11-25T07:03:44.370147Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2015-11-25T07:03:44.370259Z 0 [ERROR] Aborting


As the new /dev/vdb include /lost+found, which makes mysql failed to initialization. So it most likely a mysql issue.

We tried nginx, it can mount ok and container running. So close it now.


But we surely think that the kubernetes docs is not correct for that example, at least should make that example work. It is another bug, I think we can track it use this thread.

**Comment by loshkovskyi** [comment] 2016-02-02 21:20
I've also encountered this issue and I would like to elaborate on it.

How to reproduce:

Follow the example here: http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html
Once you created the pod with `kubectl`, check its status (it will crash in a minute or so):
```
# kubectl get pods
NAME      READY     STATUS             RESTARTS   AGE
mysql     0/1       CrashLoopBackOff   2          1m

# kubectl logs mysql
Initializing database
2016-01-30T15:08:25.135487Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-01-30T15:08:25.135594Z 0 [ERROR] Aborting
```
Verify manually with the latest image using a created directory instead of a volume:
```
# mkdir -p /tmp/mysql/dir
# docker run --rm -it -e MYSQL_ROOT_PASSWORD=password-here -v /tmp/mysql:/var/lib/mysql mysql:5.7.10
Initializing database
2016-02-02T21:00:49.165832Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-02-02T21:00:49.165928Z 0 [ERROR] Aborting
```
From the [official MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html):

> 
When invoked with the --initialize or --initialize-insecure option, mysqld performs the following initialization sequence.
...
1. The server checks for the existence of the data directory as follows:
...
- If a data directory exists and is not empty (that is, it contains files or subdirectories), the server exits after producing an error message:
>
[ERROR] --initialize specified but the data directory exists. Aborting.
In this case, remove or rename the data directory and try again.
>
As of MySQL 5.7.11, an existing data directory is permitted to be nonempty if every entry either has a name that begins with a period (.) or is named using an --ignore-db-dir option.


A possible solution:

In [mysql.yaml](http://kubernetes.io/v1.1/examples/mysql-cinder-pd/mysql.yaml) replace `mountPath: /var/lib/mysql` with something other than `mysql`. For example: `mountPath: /var/lib/db`. Then the data directory `/var/lib/db/mysql` will be created and the initialization will carry on.

**Comment by swagiaal** [comment] 2016-02-04 19:47
hmm.. it sounds like the answer here is adding `--ignore-db-dir=lost+found`
This is not a kube issue per se since you would have this problem with MySQL if you set your datadir at the root of a drive.

**Comment by childsb** [comment] 2016-07-15 16:20
Closing per application fix mentioned.

**Closed by childsb** 2016-07-15 16:20 UTC
Labels: area/storage, area/system-requirement, area/volumes, kind/support, team/cluster
