### ISSUE TITLE
ThirdPartyResourceData objects still exist after deleting and recreating namespaces

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#34788] opened 2016-10-14 02:33 UTC
**BUG REPORT**

**Kubernetes version** (use `kubectl version`): v1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): default GCI image
- **Install tools**: kube-up

**What happened**:

- Create TPR "MyResource"
- Create namespace "soak-test"
- Create a "MyResource" "a" under "soak-test":
```
$ cat my-resource-a.yaml
apiVersion: "example.com/v1"
kind: "MyResource"
metadata:
  name: "a"
...
$ kubectl --namespace soak-test create -f my-resource-a.yaml
$ kubectl --namespace soak-test get MyResource
NAME           LABELS    DATA
a           ...
```
- Delete namespace "soak-test"
```
$ kubectl delete ns soak-test
```
- Verify it's deleted
- Recreate namespace "soak-test"

Here I'm expecting that the namespace should be fresh. But previous MyResource "a" still exists.
```
$ kubectl --namespace soak-test get MyResource
NAME           LABELS    DATA
a           ...
```

Is this expected or a bug?

**Comment by hongchaodeng** [comment] 2016-10-14 02:33
cc @brendandburns @philips @aaronlevy @xiang90

**Comment by deads2k** [comment] 2016-10-14 14:40
I'm adding this to the list of knowing issues around ThirdPartyResources here: https://github.com/kubernetes/features/issues/95

**Comment by derekwaynecarr** [comment] 2016-10-14 14:43
This is the same as https://github.com/kubernetes/kubernetes/issues/32306

**Comment by derekwaynecarr** [comment] 2016-10-14 14:44
In addition, you should not be able to delete a TPR schema def, if there are instances of that TPR in the system.

**Comment by deads2k** [comment] 2016-10-14 14:50
> In addition, you should not be able to delete a TPR schema def, if there are instances of that TPR in the system.

Probably requires a finalizer as noted in the feature issue along with proper respect for finalizing TPRs from the associated REST handler.

**Comment by pwittrock** [comment] 2016-10-18 21:19
Closing this as resolved

Resolution: Duplicate of  #32306

**Closed by pwittrock** 2016-10-18 21:19 UTC
Labels: component/kubectl, team/ux

**Comment by hongchaodeng** [comment] 2017-05-29 21:04
This happened again on k8s 1.6.2 .
Can we re-open it?
@pwittrock
