### ISSUE TITLE
[CRI] Decide what to do with traffic shaping in kubenet

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#37315] opened 2016-11-22 21:46 UTC
Traffic shaping is currently disabled in kubenet when running with CRI. We can enable it by passing pod sandbox annotation into network plugin.

The current traffic shaping happens per pod per node, lack of global coordination. Hence @dchen1107 suggest to remove it and pursue a better design. 

@kubernetes/sig-network @kubernetes/sig-node

**Comment by euank** [comment] 2016-11-22 21:58
cc @squeed 

IIUC the traffic shaping feature is alpha, so removing it isn't as big a deal from an API perspective.

**Comment by eparis** [comment] 2016-11-22 22:14
I heard dawns comment (3rd hand) to remove it. From an API perspective we wouldn't be breaking any rules. But I'm not sure 'global or nothing' is the only reasonable option.

I get that a datacenter is going to have bottlenecks and the only way to drive things well in light of those bottlenecks is from a global view. I wholeheartedly agree that a wholeistic datacenter view is required to implement broad scale QoS. But I'd like that we consider 2 things.

1. Not everyone is trying to get such a thing. They might just happy a crappy chatty app that they want to quiet down. Who knows the reason. But I know Red Hat has customers doing this.
2. But I don't buy into the fact that KUBERNETES needs to be that wholeistic controller. That controller may want to externally drive kubernetes limiting on a pod by pod (or container by container) basis given its wholeistic knowledge of the datacenters capabilities. To write an external controller kubernetes needs to provide the minimum primitive to limit bandwidth.

Its seem like the alpha annotation is about as minimal as we can hope for...

**Comment by thockin** [comment] 2016-11-22 22:39
The problem is that the annotation only works on some net drivers.  Maybe
we should just rename it to make that clear, then find a way to plumb it to
CNI, and implement it in plugins that care to.

**Comment by squeed** [comment] 2016-11-23 15:28
We're currently working on a convention within the CNI to facilitate post-interface-creation "tuning" plugins. One of the motivating examples is, of course, traffic shaping.

There are a few subtleties, including the fact that traffic shaping is a per-container consideration, rather than a per-network configuration.

The design I'm leaning towards is a separate call to libcni after the interface is created by the runtime / kubelet. This means that the traffic shaping parameters still need to be a distinct parameter set, rather than just the network config file. Consequently, the kubelet + runtime will still need to be able to pass them around.

**Comment by thockin** [comment] 2016-11-24 06:38
Maybe we need a CNI developers summit in early Q1?  There are a lot of
ideas on the table, we should be careful here...

**Comment by dchen1107** [comment] 2017-03-11 00:12
At the end we decided to enable kubenet traffic shaping with CRI to avoid those unnecessary backward compatibility issues. Close the issue. Thanks!

**Closed by dchen1107** 2017-03-11 00:12 UTC
Labels: sig/network, sig/node, team/cluster (deprecated - do not use)
