### ISSUE TITLE
Broken Grafana on k8s 1.4 on AWS

### ISSUE THREAD

**Issue by vladi-dev** [kubernetes/kubernetes#33775] opened 2016-09-29 17:57 UTC
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): Linux ip-172-20-0-9 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
- **Install tools**: ./cluster/kube-up.sh
- **Others**: 
KUBE_AWS_ZONE=us-west-2a
KUBERNETES_PROVIDER=aws
INSTANCE_PREFIX=first-k8s
MASTER_SIZE=t2.small
NUM_NODES=3

**What happened**: Grafana doesnt show grafs. There is an error `{"error":"error parsing query: found SELECT, expected ; at line 2, char 1"}`. This is because of the breaking changes in influxdb container image v0.7 where you no longer can have two queries without the semicolon between them.

**What you expected to happen**:
I expected grafana to show graphs :)

**How to reproduce it** (as minimally and precisely as possible):
Install k8s on AWS using `curl -sS https://get.k8s.io | bash`

**Anything else do we need to know**:
I solved this by downgrading influxdb container image from v0.7 to v0.6 and recreating monitoring pods.

<img width="1434" alt="screen shot 2016-09-29 at 10 52 03 am" src="https://cloud.githubusercontent.com/assets/10385147/18965794/7462ddf4-8633-11e6-9e11-634ff9ebda51.png">

**Comment by vladi-dev** [comment] 2016-09-29 18:01
This is the line where image is set: https://github.com/kubernetes/kubernetes/blame/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml#L23

**Comment by neotusca** [comment] 2016-10-05 02:25
thx.. vladi.
Samething me too in Baremetal.
Just modifty influxdb-grafana-controller.yaml and going on right.

I don't know why "grafana-influxdb queries without semi-colon".

**Comment by captify-akraievoy** [comment] 2016-10-07 17:10
Confirming this is not working in default 1.4 k8s AWS install.

See here for [actual cause](https://github.com/grafana/grafana/issues/4533#issuecomment-207813911): it seems that guys from influxdb team decided to walk away from some API perks which grafana 2.6 relied on, so I have to either downgrade influxdb version or force upgrade to grafana 3+

**Comment by jingxu97** [comment] 2016-10-08 05:36
@captify-akraievoy , could you please share more information about data lost issue? Any steps that might reproduce the issue? Thanks!

**Comment by captify-akraievoy** [comment] 2016-10-08 12:31
@jingxu97 well I've lost previous info which apparently was kept in influxdb container (which I downgraded) - grafana now shows CPU utilization and such only since the moment I force-restarted the pod. I think this is due to default AWS system pod YAMLs not referring to any persistent volumes (...claims or otherwise): so that this telemetery data is transient and lives only as long as pod lives.

**Comment by captify-akraievoy** [comment] 2016-10-08 12:35
@piosz this was actually [your commit](https://github.com/kubernetes/kubernetes/commit/94ca825a19a1adb12d92c052e6c2a43c5e59e9c9) which introduced this incompatibility - I would link to some issue or anything relevant but this is the only thing I could find

**Comment by piosz** [comment] 2016-10-10 09:59
@captify-akraievoy thanks for pointing me to it.

In #31519 I updated influxdb to the newer version to improve resource usage. It seems the old Grafana doesn't work with the new influxdb version. We need to update Grafana image - it's hosted in https://github.com/kubernetes/heapster/tree/master/grafana. Anyone willing to help?

cc @mwielgus

**Comment by piosz** [comment] 2016-10-20 13:11
@Crassirostris offered to help. Thanks!

**Comment by danielfm** [comment] 2016-10-24 12:56
I pushed [the latest change](https://github.com/kubernetes/heapster/commit/5b562437162e2794d275a508fa6d041d782379e4) to my private Docker registry and confirm that it fixes the problem.

**Comment by Crassirostris** [comment] 2016-10-24 12:58
@danielfm I was waiting for the pr to be merged. I hope to build and push the image and make a PR to the kubernetes repo in an hour.

**Comment by piosz** [comment] 2016-10-24 13:12
@danielfm thanks for confirming!

**Closed** 2016-10-24 20:38 UTC
Labels: component/kubelet, team/cluster

**Comment by piosz** [comment] 2016-10-25 07:43
This is now fixed in HEAD and should be included in 1.4 patch release soon. In the meantime you may want to use the new version in your cluster.

**Comment by nicolasbelanger** [comment] 2016-10-25 19:07
@piosz Works for me, thanks!
