### ISSUE TITLE
Windows HostProcessContainer jobs fail due to mismatching COMPUTERNAME

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#109821] opened 2022-05-05 13:08 UTC
### Which jobs are failing?

Windows GCE jobs:

https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master
https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-master

### Which tests are failing?

[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should run as a process on the host/node
[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should support various volume mount types

### Since when has it been failing?

Since the jobs were reintroduced.

### Testgrid link

https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master

### Reason for failure (if possible)

Windows COMPUTERNAMEs are typically limited to 15 characters [1], while the kubelet nodes spawned in the GCE test jobs are much longer (e.g.: ``e2e-e84a5b9f56-7f363-windows-node-group-0n9g``). The names might be truncated, resulting in the test failure.

[1] https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#netbios-computer-names

### Relevant SIG(s)

/sig windows
/sig testing

**Comment by marosset** [comment] 2022-05-05 16:37
dupe of https://github.com/kubernetes/kubernetes/issues/106640
/close

**Closed** 2022-05-05 16:38 UTC
Labels: sig/windows, sig/testing, kind/failing-test, needs-triage
