### ISSUE TITLE
Fix transport/cache static assertion that tlsCacheKey is comparable for go 1.20 semantics

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#116562] opened 2023-03-14 01:05 UTC
> > We need to tweak our code to keep the static check: [golang/go#56548 (comment)](https://github.com/golang/go/issues/56548#issuecomment-1317673963)
> 
> I assume that's something we can do now in master ahead of go1.20?

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/112680#issuecomment-1362953480_

**Comment by furkatgofurov7** [comment] 2023-06-30 06:59
@enj hi again!

Gentle reminder that the code freeze is starting [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496) (about 3 weeks from now), we want to ensure that each issue is dealt in timely manner and tracked.  

As the issue is tagged for 1.28, is it still planned for this release?

**Comment by furkatgofurov7** [comment] 2023-07-12 08:00
@enj hi! I don't seem to find any PR being worked on to close this issue?

Since it has not been updated for a long time, I'd like to check what's the status with you once again. 
FYI, as I informed about it already 2 weeks ago, we are in week 9 currently and the code freeze is starting next week (week 10) at [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496).

Please remove the milestone if this not currently tracked for v1.28 release or if it is still, please make sure that the fix is in  before the code freeze date above, thanks!

**Comment by moficodes** [comment] 2023-10-16 19:10
Hello @enj ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by moficodes** [comment] 2023-10-30 02:23
Hello @enj ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is this week. We want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by dims** [comment] 2023-11-13 14:21
/milestone v1.30

kicking the can, we are way past code freeze

**Comment by pacoxu** [comment] 2024-03-01 06:37
@enj does this still target v1.30?

**Comment by Vyom-Yadav** [comment] 2024-03-11 07:45
We are past the code freeze stage. Moving this to the next release.

/milestone v1.31

**Comment by Vyom-Yadav** [comment] 2024-06-14 04:23
Hello @enj! This issue has not been updated for a long time, so I'd like to check what's the status. The `code freeze is starting 02:00 UTC Wednesday 10th July 2024 (about 4 weeks from now)`, and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the issue is tagged for `1.31`, is it still planned for this release?

**Closed** 2024-08-20 01:14 UTC
Labels: sig/api-machinery, sig/auth, triage/accepted
