### ISSUE TITLE
PodDisruptionBudget is not respected when updating component spec

### ISSUE THREAD

**Issue by 180254** [kubernetes/kubernetes#95374] opened 2020-10-07 17:12 UTC
**What happened**:
I have:
-a Kubernetes cluster with two StatefulSets (let's call them foo and bar), managed using terraform.
-defined PodDisruptionBudget so only one replica of "foo", "bar" can be taken down at the same time.

I updated the definition of components (version of images has changed) and performed "terraform apply".
PodDisruptionBudget has been ignored. The "foo" and "bar" have been updated at the same time.

**What you expected to happen**:
PodDisruptionBudget is respected.
Only one replica of "foo", "bar" can be is updated at the same time.

**How to reproduce it (as minimally and precisely as possible)**:
Reproduction steps without terraform, just kubectl:
[foobar-statefulsets.zip](https://github.com/kubernetes/kubernetes/files/5342436/foobar-statefulsets.zip)
```
kubectl apply -f foobar-statefulsets.yaml
kubectl -n default patch statefulset foo --type='json' -p="[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"busybox:uclibc\" }]"
kubectl -n default patch statefulset bar --type='json' -p="[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"busybox:uclibc\" }]"
kubectl -n default get pod
```
```
bar-2                                          1/1     Terminating   0          49s
foo-2                                          1/1     Terminating   0          49s
```

**Anything else we need to know?**:
PodDisruptionBudget definition works, for example, when I do a "kubectl drain \<node\>"

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Azure`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
`Linux winnie-the-pooh 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-10-07 23:12
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/89820

PDBs do not guard workload update rollouts, but guard node drain operations

**Closed by liggitt** 2020-10-07 23:12 UTC
Labels: kind/bug, needs-triage, sig/cluster-lifecycle
