### ISSUE TITLE
Thousands TCP connections between master/compute stuck in "ESTABLISHED" status.

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#77114] opened 2019-04-26 08:44 UTC
**What happened**:
We've see thousands connections stuck in "ESTABLISHED" status between apiserver and kubelet. and running our of the 5-tuples for connections.

#netstat -t
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 ip-10-194-56-159.:38337 ip-10-194-57-180.:10250 ESTABLISHED
tcp        0      0 ip-10-194-56-159.:51666 ip-10-194-56-207.:10250 ESTABLISHED
tcp        0      0 ip-10-194-56-159.:36798 ip-10-194-57-59.a:10250 ESTABLISHED
tcp        0      0 ip-10-194-56-159.:40087 ip-10-194-57-67.a:10250 ESTABLISHED
tcp        0      0 ip-10-194-56-159.:41705 ip-10-194-57-197.:10250 ESTABLISHED
tcp        0      0 ip-10-194-56-159.:60977 ip-10-194-56-215.:10250 ESTABLISHED

#netstat -t |wc -l
36194

#curl one of the compute node on the master will fail:

curl -v 172.28.56.184:10250  (this is the compute node running the pod)
* About to connect() to 172.28.56.184 port 10250 (#0)
*   Trying 172.28.56.184...
* Failed to connect to 172.28.56.184: Cannot assign requested address
* couldn't connect to host at 172.28.56.184:10250
* Closing connection 0
curl: (7) Failed to connect to 172.28.56.184: Cannot assign requested address

**What you expected to happen**:
The stuck connections should be released
**How to reproduce it (as minimally and precisely as possible)**:
Not sure
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-11-09T15:12:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-11-09T15:12:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`):
 cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

- Kernel (e.g. `uname -a`):3.10.0-862.11.6.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2019-04-26 15:16
duplicate of https://github.com/kubernetes/kubernetes/issues/67382?

**Closed** 2019-04-26 15:30 UTC
Labels: kind/bug, sig/api-machinery, sig/node
