### ISSUE TITLE
Why after a Job finishes successfully, the Reason for the State the Pod becomes Error

### ISSUE THREAD

**Issue by zyxue** [kubernetes/kubernetes#22795] opened 2016-03-10 15:36 UTC
The original google groups thread is [here](https://groups.google.com/forum/#!topic/google-containers/eWRVGYvqSUw)

Here is an example showing the problem in the title with the relevant part highlighted in red. The job finishes successfully.

	....
		QoS Tier:
		  cpu:    Guaranteed
		Limits:
		  cpu:    7
		Requests:
		  cpu:        7
		State:        Terminated
		  Reason:        Error
		  Exit Code:    0
		  Started:        Fri, 04 Mar 2016 20:13:54 +0000
		  Finished:        Fri, 04 Mar 2016 21:24:25 +0000
		Ready:        False
		Restart Count:    0
		Environment Variables:
	Conditions:
	  Type        Status
	  Ready     False
	Volumes:
	  refresh-token:
		Type:    Secret (a secret that should populate this volume)
		SecretName:    refresh-token
	  default-token-eapfl:
		Type:    Secret (a secret that should populate this volume)
		SecretName:    default-token-eapfl
	Events:
	  FirstSeen    LastSeen    Count    From                        SubobjectPath                Reason    Message
	  ─────────    ────────    ─────    ────                        ─────────────                ──────    ───────
	  7m        7m        1    {kubelet gke-star-cluster-bb59c9ba-node-emis}    implicitly required container POD    Killing    Killing with docker id 679889627a8c

Here is another example.

	$ kubect get jobs abcd-10gb-g27255-sw-17
	JOB                      CONTAINER(S)   IMAGE(S)                                SELECTOR                                         SUCCESSFUL
	abcd-10gb-g27255-sw-17   abcd           us.gcr.io/xxx-xxx-xx-xxxx/abcd:latest   app in (abcd-10gb-g27255-sw-17),index in (649)   1
	$ kubect get pods abcd-10gb-g27255-sw-17-3wle4
	NAME                           READY     STATUS    RESTARTS   AGE
	abcd-10gb-g27255-sw-17-3wle4   0/1       Error     0          1d

If I ssh to the corresponding node and do `docker ps -a`

	CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                   PORTS               NAMES    
	ae858da78c0a        us.gcr.io/xxx-xxx-xx-xxxx/abcd:latest       "app.py --input-gs-ba"   23 hours ago        Exited (0) 4 hours ago                       k8s_abcd.a09f0478_abcd-10gb-g27255-sw-17-3wle4_default_90b60012-e496-11e5-bfe1-42010af00027_17c13bdd                

So everything seems normal, I don't understand why it's labeled Error...

**Comment by ncdc** [comment] 2016-03-10 21:46
cc @soltysh

**Comment by soltysh** [comment] 2016-03-10 23:05
@zyxue can you provide us with more details? From the above I see you got one failed pod, that doesn't prevent job from finishing successfully. It will always try to run to `.spec.completions` successful pods. If one pod fails new one will be spawn. Can you provide us with your configs and logs? Reproducible example would be the best, especially that I'm currently preparing for tomorrows KubeCon EU demo and I run quite a lot of jobs I didn't have any problems like the ones you're describing.

**Comment by zyxue** [comment] 2016-03-10 23:24
I don't have a log at the moment. I can attach a config. But that doesn't happen only for a single pod. I have finished thousands of jobs, and they all behave this way though the jobs all finished successfully. The finished pods don't get restarted even though its status labelled as Error, that's why I am confused.

**Comment by zyxue** [comment] 2016-03-10 23:43
Here I reproduced the problem using a hello-world example

$ gcloud container clusters create sample-cluster --num-nodes 1 --machine-type n1-standard-1

$ cloud container clusters get-credentials sample-cluster

$ kubectl create -f secret.yaml

$ cat jobs.yaml

	apiVersion: extensions/v1beta1
	kind: Job
	metadata: {name: abcd}
	spec:
	  parallelism: 2
	  selector:
		matchLabels: &id001 {app: abcd, index: '1'}
	  template:
		metadata:
		  labels: *id001
		  name: abcd
		spec:
		  containers:
		  - command: []
			image: hello-world:latest
			name: abcd
			resources:
			  limits: {cpu: 100m}
			volumeMounts:
			- {mountPath: /refresh-token, name: refresh-token, readOnly: true}
		  restartPolicy: OnFailure
		  volumes:
		  - name: refresh-token
			secret: {secretName: refresh-token}

$ kubectl get pods -a

	NAME         READY     STATUS    RESTARTS   AGE
	abcd-xnfv0   0/1       Error     0          23s

$ kubectl logs abcd-xnfv0

	Hello from Docker.
	This message shows that your installation appears to be working correctly.

	To generate this message, Docker took the following steps:
	1. The Docker client contacted the Docker daemon.
	2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
	3. The Docker daemon created a new container from that image which runs the
	executable that produces the output you are currently reading.
	4. The Docker daemon streamed that output to the Docker client, which sent it
	to your terminal.

	To try something more ambitious, you can run an Ubuntu container with:
	$ docker run -it ubuntu bash

	Share images, automate workflows, and more with a free Docker Hub account:
	https://hub.docker.com

	For more examples and ideas, visit:
	https://docs.docker.com/userguide/

$ kubectl describe pods

	Name:				abcd-xnfv0
	Namespace:			default
	Image(s):			hello-world:latest
	Node:				gke-sample-cluster-b7d1b5ed-node-yxo2/10.240.0.3
	Start Time:			Thu, 10 Mar 2016 23:34:23 +0000
	Labels:				app=abcd,index=1
	Status:				Succeeded
	Reason:				
	Message:			
	IP:				
	Replication Controllers:	<none>
	Containers:
	  abcd:
		Container ID:	docker://643a0a09b6777327a6ba340df4d71df3e96f8e0534c155bf91a62b203e801caa
		Image:		hello-world:latest
		Image ID:		docker://0a6ba66e537a53a5ea94f7c6a99c534c6adb12e3ed09326d4bf3b38f7c3ba4e7
		QoS Tier:
		  cpu:	Guaranteed
		Limits:
		  cpu:	100m
		Requests:
		  cpu:		100m
		State:		Terminated
		  Reason:		Error
		  Exit Code:	0
		  Started:		Thu, 10 Mar 2016 23:34:25 +0000
		  Finished:		Thu, 10 Mar 2016 23:34:25 +0000
		Ready:		False
		Restart Count:	0
		Environment Variables:
	Conditions:
	  Type		Status
	  Ready 	False 
	Volumes:
	  refresh-token:
		Type:	Secret (a secret that should populate this volume)
		SecretName:	refresh-token
	  default-token-5pwn2:
		Type:	Secret (a secret that should populate this volume)
		SecretName:	default-token-5pwn2
	Events:
	  FirstSeen	LastSeen	Count	From						SubobjectPath				Reason		Message
	  ─────────	────────	─────	────						─────────────				──────		───────
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	implicitly required container POD	Pulled		Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
	  3m		3m		1	{scheduler }										Scheduled	Successfully assigned abcd-xnfv0 to gke-sample-cluster-b7d1b5ed-node-yxo2
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	implicitly required container POD	Created		Created with docker id 4fff3f2f3423
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	spec.containers{abcd}			Pulling		Pulling image "hello-world:latest"
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	implicitly required container POD	Started		Started with docker id 4fff3f2f3423
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	spec.containers{abcd}			Pulled		Successfully pulled image "hello-world:latest"
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	spec.containers{abcd}			Created		Created with docker id 643a0a09b677
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	spec.containers{abcd}			Started		Started with docker id 643a0a09b677
	  3m		3m		1	{kubelet gke-sample-cluster-b7d1b5ed-node-yxo2}	implicitly required container POD	Killing		Killing with docker id 4fff3f2f3423

$ kubectl describe jobs

	Name:		abcd
	Namespace:	default
	Image(s):	hello-world:latest
	Selector:	app in (abcd),index in (1)
	Parallelism:	2
	Completions:	1
	Labels:		app=abcd,index=1
	Pods Statuses:	0 Running / 1 Succeeded / 0 Failed
	Volumes:
	  refresh-token:
		Type:	Secret (a secret that should populate this volume)
		SecretName:	refresh-token
	Events:
	  FirstSeen	LastSeen	Count	From	SubobjectPath	Reason			Message
	  ─────────	────────	─────	────	─────────────	──────			───────
	  3m		3m		1	{job }			SuccessfulCreate	Created pod: abcd-xnfv0

$ kubectl version

    Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}

**Comment by yujuhong** [comment] 2016-03-11 01:32
Apart from that, kubelet shouldn't have reported reason "Error" for a container with 0 exit code. This can be easily fixed in kubelet by [adding an extra check here](https://github.com/kubernetes/kubernetes/blame/release-1.1/pkg/kubelet/dockertools/manager.go#L392). 

BTW, this has already been fixed in HEAD (1.2):
```
NAMESPACE     NAME                                                READY     STATUS      RESTARTS   AGE       NODE
default       abcd-hdov3                                          0/1       Completed   0          8s        e2e-test-yjhong-minion-kigf
default       abcd-m4whe                                          0/1       Completed   0          8s        e2e-test-yjhong-minion-kigf
```

**Comment by janetkuo** [comment] 2016-03-11 01:54
@bgrant0607

**Comment by janetkuo** [comment] 2016-03-11 02:04
Looks like this is fixed in HEAD, and the `state.reason` should now be `Completed` (instead of `Error`). See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L371-L372

**Closed by janetkuo** 2016-03-11 02:04 UTC
Labels: priority/P1, team/ux

**Comment by bgrant0607** [comment] 2016-03-11 04:11
Thanks. @janetkuo @yujuhong 
cc @erictune @davidopp
