### ISSUE TITLE
TestGC is flaky

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14582] opened 2015-09-25 20:55 UTC
Passed on kubernetes-test-go 3-4 times, and then failed:
```
TestGC

gc_controller_test.go:122: [1]pod's deleted expected and actual did not match.
expected: [a]
actual: [b]
```

cc @brendandburns

**Comment by quinton-hoole** [comment] 2015-09-25 21:48
Duplicate of #14577

**Closed by quinton-hoole** 2015-09-25 21:48 UTC
Labels: area/test, kind/flake, priority/P0, team/control-plane
