### ISSUE TITLE
gce-serial tests are panicking due to NPE in autoscaling code

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#47127] opened 2017-06-07 14:50 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1173

```
I0607 01:09:38.349] [91m[1mâ€¢! Panic [32.767 seconds][0m
I0607 01:09:38.349] [k8s.io] Initializers
I0607 01:09:38.349] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:617[0m
I0607 01:09:38.349]   [91m[1mshould dynamically register and apply initializers to pods [Serial] [It][0m
I0607 01:09:38.349]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:206[0m
I0607 01:09:38.349] 
I0607 01:09:38.350]   [91m[1mTest Panicked[0m
I0607 01:09:38.350]   [91mruntime error: invalid memory address or nil pointer dereference[0m
I0607 01:09:38.350]   /usr/local/go/src/runtime/asm_amd64.s:514
I0607 01:09:38.350] 
I0607 01:09:38.350]   [91mFull Stack Trace[0m
I0607 01:09:38.350]   	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0607 01:09:38.350]   k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest.func1(0x2ef4ce0, 0xc421f65140, 0xc42114fd3f)
I0607 01:09:38.351]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:231 +0x5f
```

**Comment by smarterclayton** [comment] 2017-06-07 14:52
https://github.com/kubernetes/kubernetes/pull/46833 might be a culprit, but maybe not

**Comment by smarterclayton** [comment] 2017-06-07 14:53
This could be related to how the test initializes the framework or cleans it up, maybe.

**Comment by smarterclayton** [comment] 2017-06-07 14:54
Another failure in the same run, not just this one test:

```
I0606 21:26:15.687] [91m[1mâ€¢! Panic [756.712 seconds][0m
I0606 21:26:15.688] [k8s.io] Network Partition [Disruptive] [Slow]
I0606 21:26:15.688] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:617[0m
I0606 21:26:15.688]   [k8s.io] [ReplicationController]
I0606 21:26:15.688]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:617[0m
I0606 21:26:15.688]     [91m[1mshould eagerly create replacement pod during network partition when termination grace is non-zero [It][0m
I0606 21:26:15.688]     [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:331[0m
I0606 21:26:15.688] 
I0606 21:26:15.688]     [91m[1mTest Panicked[0m
I0606 21:26:15.688]     [91mruntime error: invalid memory address or nil pointer dereference[0m
I0606 21:26:15.688]     /usr/local/go/src/runtime/asm_amd64.s:514
I0606 21:26:15.689] 
I0606 21:26:15.689]     [91mFull Stack Trace[0m
I0606 21:26:15.689]     	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0606 21:26:15.689]     k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest.func1(0x2ef4ce0, 0xc420eae2a0, 0xc4217c5d3f)
I0606 21:26:15.689]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:231 +0x5f
I0606 21:26:15.689]     k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc420d2cb20, 0xc421b27200, 0xc420eae240, 0xc421abe780, 0x365130f)
I0606 21:26:15.689]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:275 +0x70
I0606 21:26:15.689]     k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc420d2cb20, 0xc421b27200, 0x0, 0x0)
I0606 21:26:15.689]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:191 +0x99
I0606 21:26:15.690]     k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc420d2cb20, 0xc421b27200, 0xc420d2cb20, 0xc421b27200)
I0606 21:26:15.690]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:216 +0x76
I0606 21:26:15.690]     k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x37e11d600, 0x1bf08eb000, 0xc421b27200, 0x5272fe0, 0xc420d6b980)
I0606 21:26:15.690]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:205 +0x4d
I0606 21:26:15.690]     k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest(0xc4215f0ab0, 0xfa)
I0606 21:26:15.690]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:244 +0x1d6
I0606 21:26:15.690]     k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).makeConsumeCPURequests(0xc4215f0ab0)
I0606 21:26:15.690]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:175 +0x328
I0606 21:26:15.690]     created by k8s.io/kubernetes/test/e2e/common.newResourceConsumer
I0606 21:26:15.690]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:137 +0x399
I0606 21:26:15.691]     
```

**Comment by wojtek-t** [comment] 2017-06-07 15:06
@wasylkowski @piosz @mwielgus @MaciekPytel

**Comment by smarterclayton** [comment] 2017-06-07 15:17
I'm not positive but the stack trace might be wrong due to inlining optimizations.  rc.framework == nil was my first guess, but that would fail earlier in that method.

**Comment by smarterclayton** [comment] 2017-06-07 15:26
Framework AfterEach runs namespace deletion, which may mean that .Namespace is nil (if inlining is indeed present).

**Comment by wasylkowski** [comment] 2017-06-08 02:47
I am looking into this right now.

**Comment by wasylkowski** [comment] 2017-06-08 03:23
It's unrelated. I reverted #46833 from the current master HEAD locally (via `git revert -m 1 07e4cca7b3`), then did `make` and finally `go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Initializers\sshould\sdynamically\sregister\sand\sapply\sinitializers\sto\spods\s\[Serial\]$'` and it did not help. The test still fails with the same message "Expected <*v1.Initializers | 0x0>: nil not to be nil" (location: /usr/local/google/home/wasylkowski/.gvm/pkgsets/go1.8.3/global/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:171)

**Comment by wasylkowski** [comment] 2017-06-08 03:41
Note that I have executed one of the initializers e2e test (not autoscaling), because it is one of the tests reported by https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1173 as panicked.

**Comment by wasylkowski** [comment] 2017-06-08 03:49
Looking a bit further I found out that commit https://github.com/kubernetes/kubernetes/commit/772ab8e1b4163c17d285a2789321762a8f2dc9f3 added the test above as already failing.

**Comment by wasylkowski** [comment] 2017-06-08 04:03
I have just realized that I have discovered yesterday a race condition in ResourceConsumer implementation, and #46833 might actually make it worse. Let me quickly make a PR out of a fix.

**Comment by wasylkowski** [comment] 2017-06-08 04:15
Let me try to recap what I have found out so far:
- The test that is being referred to at the top of this issue (e2e/extension/initializers.go) fails "out of the box" and probably deserves a separate issue to track it
- Other failing tests that look like they have a similar failure pattern (NPE) fail because of trying to send a "consume CPU" request to a non-existent pod (unrelated to initializers.go above, as far as I can tell)
- PR #46833 might cause the effect above (and probably does) because it actually deletes the pods that should have been deleted
- However, the root cause is that there is a race condition inside ResourceConsumer that makes "consume CPU" requests being sometimes sent already after "CleanUp" got called (fix prepared in PR #47157)

**Comment by smarterclayton** [comment] 2017-06-08 05:23
Initializer was fixed in a different PR, depending on what cluster you test
on.

**Comment by smarterclayton** [comment] 2017-06-08 05:27
Yeah, confirmed initializers test is now passing on GCE and disabled on GKE
(which doesn't enable initializers configuration group yet)

**Comment by wasylkowski** [comment] 2017-06-08 18:48
Clayton, can you assign this to me? I cannot do this myself.

**Closed** 2017-06-08 20:43 UTC
Labels: priority/failing-test, sig/autoscaling, sig/testing
