### ISSUE TITLE
bazel update fails on Mac

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#35356] opened 2016-10-22 05:59 UTC
```
$ hack/update-bazel.sh
extract err: no buildable Go source files in /Users/clayton/projects/origin/src/k8s.io/kubernetes/vendor/golang.org/x/exp/inotify
extract err: no buildable Go source files in /Users/clayton/projects/origin/src/k8s.io/kubernetes/vendor/golang.org/x/exp/inotify
extract err: no buildable Go source files in /Users/clayton/projects/origin/src/k8s.io/kubernetes/vendor/golang.org/x/exp/inotify
extract err: no buildable Go source files in /Users/clayton/projects/origin/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/selinux
extract err: no buildable Go source files in /Users/clayton/projects/origin/src/k8s.io/kubernetes/vendor/github.com/vishvananda/netlink/nl
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/cadvisor"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/cm"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/config"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/container"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/network/cni"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/network/exec"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/kubelet/network/kubenet"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/security/apparmor"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/bandwidth"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/mount"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/oom"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/procfs"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/resourcecontainer"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/rlimit"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/util/selinux"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/volume"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/volume/empty_dir"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/volume/host_path"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/volume/util"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/cmd/kubelet/app"
wrote BUILD for "/Users/clayton/projects/origin/src/k8s.io/kubernetes/test/e2e/generated"
F1022 01:58:08.289995   75625 gazel.go:35] err: "test/e2e_node/BUILD" cannot be a directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0x295800, 0xc400000000, 0x5c, 0xb0)
    /Users/clayton/projects/origin/src/github.com/golang/glog/glog.go:769 +0xa5
github.com/golang/glog.(*loggingT).output(0x27b480, 0xc400000003, 0xc420258300, 0x260686, 0x8, 0x23, 0x0)
    /Users/clayton/projects/origin/src/github.com/golang/glog/glog.go:720 +0x357
github.com/golang/glog.(*loggingT).printf(0x27b480, 0x3, 0x1a65b2, 0x7, 0xc42034bf18, 0x1, 0x1)
    /Users/clayton/projects/origin/src/github.com/golang/glog/glog.go:655 +0x14c
github.com/golang/glog.Fatalf(0x1a65b2, 0x7, 0xc42034bf18, 0x1, 0x1)
    /Users/clayton/projects/origin/src/github.com/golang/glog/glog.go:1148 +0x67
main.main()
    /Users/clayton/projects/origin/src/github.com/mikedanese/gazel/gazel.go:35 +0x166
```

Ends up removing a lot of stuff, looks like it's using GOOS=darwin and generating the wrong set of dependency trees.

**Comment by mikedanese** [comment] 2016-10-22 08:04
> Ends up removing a lot of stuff, looks like it's using GOOS=darwin and generating the wrong set of dependency trees.

Yup, just noticed that... It seems like I can't put off supporting darwin. I can add support in gazel. The panic is a different issue. The panic is caused by having both a `test/e2e_node/BUILD` file and a `test/e2e_node/build` directory in `test/e2e_node/`. I'm going to wrap the presubmit in a docker run on mac to stop the bleeding until I figure out a solution to this.

**Comment by mikedanese** [comment] 2016-10-22 08:32
I will look at this tomorrow. #35361 would disable the presubmit which is a temporary unblocker.

**Comment by mikedanese** [comment] 2016-10-22 20:26
This https://github.com/kubernetes/kubernetes/pull/35362 makes the presubmit stable on all os's but also disables the ability to actually build on macos. I can add support for mac soon.

**Comment by jayunit100** [comment] 2016-11-01 14:00
Yup , weird change sets are generated like this... 

```
--- a/pkg/client/clientset_generated/internalclientset/BUILD
+++ b/pkg/client/clientset_generated/internalclientset/BUILD
@@ -32,17 +32,6 @@ go_library(
         "//pkg/apis/policy/install:go_default_library",
         "//pkg/apis/rbac/install:go_default_library",
         "//pkg/apis/storage/install:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/apps/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/authentication/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/authorization/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/autoscaling/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/batch/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/certificates/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/core/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/policy/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/rbac/internalversion:go_default_library",
-        "//pkg/client/clientset_generated/internalclientset/typed/storage/internalversion:go_default_library", 
 ```

**Comment by jayunit100** [comment] 2016-11-01 14:01
part of #35356

**Comment by mikedanese** [comment] 2016-11-01 15:56
Are you building in and GOPATH? Are you synced with master? What does the code change look like? What go version are you using? I think I fixed claytons issue by pinning the architecture to amd64. I'm not certain your issue is Mac related.

**Comment by mikedanese** [comment] 2016-11-01 17:36
```console
$  kubernetes git:(master) go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mikedanese/go"
GORACE=""
GOROOT="/Users/mikedanese/.gimme/versions/go1.7.1.darwin.amd64"
GOTOOLDIR="/Users/mikedanese/.gimme/versions/go1.7.1.darwin.amd64/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_0/wx41t30519s75grkmtm_qddr009p0v/T/go-build253337678=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
$  kubernetes git:(master) go version
go version go1.7.1 darwin/amd64
$  kubernetes git:(master) pwd
/Users/mikedanese/go/src/k8s.io/kubernetes
$  kubernetes git:(master) ./hack/update-bazel.sh
$  kubernetes git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$  kubernetes git:(master) git rev-parse master
1fa836907496274f69bf17a383a555662c12ce49
$  kubernetes git:(master) ./hack/update-bazel.sh
$  kubernetes git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean➜  kubernetes git:(master) go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mikedanese/go"
GORACE=""
GOROOT="/Users/mikedanese/.gimme/versions/go1.7.1.darwin.amd64"
GOTOOLDIR="/Users/mikedanese/.gimme/versions/go1.7.1.darwin.amd64/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_0/wx41t30519s75grkmtm_qddr009p0v/T/go-build253337678=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
$  kubernetes git:(master) go version
go version go1.7.1 darwin/amd64
$  kubernetes git:(master) pwd
/Users/mikedanese/go/src/k8s.io/kubernetes
$  kubernetes git:(master) ./hack/update-bazel.sh
$  kubernetes git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$  kubernetes git:(master) git rev-parse master
1fa836907496274f69bf17a383a555662c12ce49
$  kubernetes git:(master) ./hack/update-bazel.sh
$  kubernetes git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**Comment by luomiao** [comment] 2016-11-03 01:47
@mikedanese 
Hi Mike, I got a problem with Bazel too on Mac. But maybe this is a different problem.
I am trying to submit this PR: https://github.com/kubernetes/kubernetes/pull/36108
which touches a big number of files.
And the verification step failed with verify-bazel step.
However on my local repo, even after I did ./hack/update-bazel.sh
The ./hack/verify-bazel.sh will still give error saying:
BUILD files are not up to date
Run ./hack/update-bazel.sh

I have totally no idea how to fix it now. Can you give some suggestions? Thanks!

**Comment by feiskyer** [comment] 2016-11-03 02:51
Another failed case:

```
F1103 10:49:29.320581   54592 gazel.go:42] err walking vendor: stat vendor/github.com/docker/docker/project/CONTRIBUTORS.md: no such file or directory
goroutine 1 [running]:
github.com/mikedanese/gazel/vendor/github.com/golang/glog.stacks(0x296800, 0xc400000000, 0x97, 0xeb)
	/Users/feisky/go/src/github.com/mikedanese/gazel/vendor/github.com/golang/glog/glog.go:766 +0xa5
github.com/mikedanese/gazel/vendor/github.com/golang/glog.(*loggingT).output(0x27c480, 0xc400000003, 0xc4200b0000, 0x261b1d, 0x8, 0x2a, 0x0)
	/Users/feisky/go/src/github.com/mikedanese/gazel/vendor/github.com/golang/glog/glog.go:717 +0x337
github.com/mikedanese/gazel/vendor/github.com/golang/glog.(*loggingT).printf(0x27c480, 0xc400000003, 0x1aa303, 0x16, 0xc4200d5f18, 0x1, 0x1)
	/Users/feisky/go/src/github.com/mikedanese/gazel/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/mikedanese/gazel/vendor/github.com/golang/glog.Fatalf(0x1aa303, 0x16, 0xc4200d5f18, 0x1, 0x1)
	/Users/feisky/go/src/github.com/mikedanese/gazel/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/Users/feisky/go/src/github.com/mikedanese/gazel/gazel.go:42 +0x31d
!!! Error in hack/update-bazel.sh:24
  '"${GOPATH}/bin/gazel" -root="$(kube::realpath ${KUBE_ROOT})"' exited with status 255
Call stack:
  1: hack/update-bazel.sh:24 main(...)
Exiting with status 1
```

**Comment by mikedanese** [comment] 2016-11-03 04:01
@luomiao thanks for the report. Your issue will be fixed when https://github.com/kubernetes/kubernetes/pull/36089 merges.

@feiskyer thats not a gazel or mac issue, that's a legitimate error. Master is broken https://github.com/kubernetes/kubernetes/issues/36111

**Comment by feiskyer** [comment] 2016-11-03 04:10
> @feiskyer thats not a gazel or mac issue, that's a legitimate error. Master is broken #36111

Yes, just noticed it failed on Linux either.

**Comment by mikedanese** [comment] 2016-11-03 17:47
Let's close this and open new issues. The original issue is fixed

**Closed by mikedanese** 2016-11-03 17:47 UTC
Labels: component/kubelet, priority/P1, team/cluster
