### ISSUE TITLE
Kubernetes create OpenStack cinder is failure

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#17618] opened 2015-11-21 10:51 UTC
I install kubernetes 1.1.1 in ubuntu and check out  the official url http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html to create a cinder volume.

1. I config the following content in the path "/etc/kubernetes/cloud_config".
[Global]
auth-url=https://*****.v2.0
username=user
password=pass
region=regionOne
tenant-id=0c331a1df18571594d49fe68asa4e
2. I add the following contend in "/etc/default/kubelet"
--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud_config

3. restart the kubernetes service.

4. create cinder 
5. cluster/kubectl.sh create -f examples/mysql-cinder-pd/mysql.yaml
The error information is following:
It looks as if you don't have a compiled kubectl binary
If you are running from a clone of the git repo, please run
'./build/run.sh hack/build-cross.sh'. Note that this requires having
Docker installed.
If you are running from a binary release tarball, something is wrong.
Look at http://kubernetes.io/ for information on how to contact the
development team for help.

**Comment by wangqunOne** [comment] 2015-11-21 10:51
@spothanis

**Comment by idvoretskyi** [comment] 2015-11-23 01:06
@wangqunOne how have you installed kubernetes in ubuntu?

It seems that you've simply cloned kubernetes git repository and tried to run the `kubectl.sh` script. Please, keep in mind that in this case `kubectl` binary hasn't been compiled.

I may recommend you to try one of the following options - compile `kubectl` binary using the described instructions or retrieve the latest kubernetes tarball, following the link - https://github.com/kubernetes/kubernetes/releases/latest

**Comment by HackToday** [comment] 2015-11-23 01:15
@idvoretskyi  She followed this guide,

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md


Also, the cinder volume example here 
http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html
said use following command:
   cluster/kubectl.sh create -f examples/mysql-cinder-pd/mysql.yaml

What do you think ?  Thanks

**Comment by idvoretskyi** [comment] 2015-11-23 01:44
@HackToday, @wangqunOne 

In the guide, http://kubernetes.io/v1.1/examples/mysql-cinder-pd/README.html is proposed to run command `cluster/kubectl.sh create -f examples/mysql-cinder-pd/mysql.yaml` - this guide describes an option when kubernetes is being installed as a ready-to-use binary. I told about that above - you'll have to retrieve the latest kubernetes tarball, following the link - https://github.com/kubernetes/kubernetes/releases/latest.

This guide, 
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md proposes to clone the git repository - in this case, you'll have to build the binary file manually.

**Comment by wangqunOne** [comment] 2015-11-23 02:17
root@kmaster:~# find . -name kubectl*
./kubernetes/test/e2e/kubectl.go
./kubernetes/test/integration/kubectl_test.go
./kubernetes/docs/user-guide/kubectl-overview.md
./kubernetes/docs/user-guide/kubectl
./kubernetes/docs/user-guide/kubectl/kubectl_describe.md
./kubernetes/docs/user-guide/kubectl/kubectl_cluster-info.md
./kubernetes/docs/user-guide/kubectl/kubectl_rolling-update.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_set-context.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_set.md
./kubernetes/docs/user-guide/kubectl/kubectl_version.md
./kubernetes/docs/user-guide/kubectl/kubectl_stop.md
./kubernetes/docs/user-guide/kubectl/kubectl_replace.md
./kubernetes/docs/user-guide/kubectl/kubectl_expose.md
./kubernetes/docs/user-guide/kubectl/kubectl_run.md
./kubernetes/docs/user-guide/kubectl/kubectl_edit.md
./kubernetes/docs/user-guide/kubectl/kubectl_annotate.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_view.md
./kubernetes/docs/user-guide/kubectl/kubectl_get.md
./kubernetes/docs/user-guide/kubectl/kubectl_config.md
./kubernetes/docs/user-guide/kubectl/kubectl_api-versions.md
./kubernetes/docs/user-guide/kubectl/kubectl_delete.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_unset.md
./kubernetes/docs/user-guide/kubectl/kubectl_exec.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_set-cluster.md
./kubernetes/docs/user-guide/kubectl/kubectl_patch.md
./kubernetes/docs/user-guide/kubectl/kubectl_label.md
./kubernetes/docs/user-guide/kubectl/kubectl_attach.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_set-credentials.md
./kubernetes/docs/user-guide/kubectl/kubectl_create.md
./kubernetes/docs/user-guide/kubectl/kubectl_autoscale.md
./kubernetes/docs/user-guide/kubectl/kubectl_port-forward.md
./kubernetes/docs/user-guide/kubectl/kubectl_apply.md
./kubernetes/docs/user-guide/kubectl/kubectl.md
./kubernetes/docs/user-guide/kubectl/kubectl_scale.md
./kubernetes/docs/user-guide/kubectl/kubectl_proxy.md
./kubernetes/docs/user-guide/kubectl/kubectl_namespace.md
./kubernetes/docs/user-guide/kubectl/kubectl_config_use-context.md
./kubernetes/docs/user-guide/kubectl/kubectl_logs.md
./kubernetes/docs/man/man1/kubectl-exec.1
./kubernetes/docs/man/man1/kubectl-config-set-cluster.1
./kubernetes/docs/man/man1/kubectl-api-versions.1
./kubernetes/docs/man/man1/kubectl-config-set.1
./kubernetes/docs/man/man1/kubectl-rolling-update.1
./kubernetes/docs/man/man1/kubectl-annotate.1
./kubernetes/docs/man/man1/kubectl-stop.1
./kubernetes/docs/man/man1/kubectl-describe.1
./kubernetes/docs/man/man1/kubectl-namespace.1
./kubernetes/docs/man/man1/kubectl-config-set-context.1
./kubernetes/docs/man/man1/kubectl-config-use-context.1
./kubernetes/docs/man/man1/kubectl-patch.1
./kubernetes/docs/man/man1/kubectl-proxy.1
./kubernetes/docs/man/man1/kubectl-apply.1
./kubernetes/docs/man/man1/kubectl-logs.1
./kubernetes/docs/man/man1/kubectl-config-view.1
./kubernetes/docs/man/man1/kubectl-create.1
./kubernetes/docs/man/man1/kubectl-expose.1
./kubernetes/docs/man/man1/kubectl-config-unset.1
./kubernetes/docs/man/man1/kubectl-replace.1
./kubernetes/docs/man/man1/kubectl-config-set-credentials.1
./kubernetes/docs/man/man1/kubectl-cluster-info.1
./kubernetes/docs/man/man1/kubectl-edit.1
./kubernetes/docs/man/man1/kubectl-port-forward.1
./kubernetes/docs/man/man1/kubectl-label.1
./kubernetes/docs/man/man1/kubectl-get.1
./kubernetes/docs/man/man1/kubectl-autoscale.1
./kubernetes/docs/man/man1/kubectl-scale.1
./kubernetes/docs/man/man1/kubectl-config.1
./kubernetes/docs/man/man1/kubectl-version.1
./kubernetes/docs/man/man1/kubectl-run.1
./kubernetes/docs/man/man1/kubectl-attach.1
./kubernetes/docs/man/man1/kubectl-delete.1
./kubernetes/docs/man/man1/kubectl.1
./kubernetes/docs/devel/kubectl-conventions.md
./kubernetes/pkg/kubectl
./kubernetes/pkg/kubectl/kubectl.go
./kubernetes/cluster/kubectl.sh
./kubernetes/cluster/ubuntu/binaries/kubectl
./kubernetes/examples/kubectl-container
./kubernetes/cmd/mungedocs/kubectl_dash_f.go
./kubernetes/cmd/mungedocs/kubectl_dash_f_test.go
./kubernetes/cmd/kubectl
./kubernetes/cmd/kubectl/kubectl.go
./kubernetes/contrib/completions/bash/kubectl

**Comment by idvoretskyi** [comment] 2015-11-23 02:19
You'll have to download and extract kubernetes.tar.gz from here - https://github.com/kubernetes/kubernetes/releases/latest. There is a ready-to-use script `cluster/kubectl.sh`, which you may use.

**Comment by wangqunOne** [comment] 2015-11-23 05:13
@idvoretskyi 
 Kubernetes can connect with openstack. But the pods is CrashLoopBackOff .  The kubelete.log's intend is following:
E1123 05:07:43.885833   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:07:45.410508   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:07:46.641702   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:07:48.998385   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:07:57.458113   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:08:05.126393   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:08:13.922266   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:08:17.730235   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:08:25.626238   19240 fs.go:211] Stat fs failed. Error: EOF
E1123 05:08:31.616209   19240 fs.go:211] Stat fs failed. Error: EOF

**Comment by wangqunOne** [comment] 2015-11-24 02:38
@idvoretskyi 
Now I can connect with openstack cinder. But when I create a mysql pod. The pod status is running first, then it changes to be error status. 
I check out the kubelet.log. 
 I find the error Unable to find pair interface, setting up all interfaces: exec: "nsenter": executable file not found in $PATH

**Comment by idvoretskyi** [comment] 2015-11-24 21:44
@wangqunOne: could you please provide us with the complete log?

Thank you.

**Comment by HackToday** [comment] 2015-11-25 05:05
@idvoretskyi  we try to install nsenter, but pod still failed for one strange issue:


we created new volumes
and tried still found the mysql containers always crash
and docker logs show that container
have following

Initializing database
2015-11-25T04:31:55.084190Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2015-11-25T04:31:55.087115Z 0 [ERROR] Abortin

**Comment by HackToday** [comment] 2015-11-25 08:43
close it, as it is duplicate of #17706

**Closed** 2015-11-25 08:50 UTC
Labels: area/platform/openstack, team/cluster
