### ISSUE TITLE
kubectl blocked on request to metrics-server

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#57103] opened 2017-12-12 17:09 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I've deployed a kubernetes multi master cluster with flannel as networking and the metrics-server in kube-system. After a rolling upgrade, every kubectl command I tried didn't respond anymore, yet requests to the API via curl worked fine. Raising the loglevel in the apiserver showed:

```
goroutine 23530 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42054f6c0, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42054f6c0, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc425912620, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:201 +0xb5
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc4280565c0, 0x7f0792f74668, 0xc429e77bd8, 0xc427b45400)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:246 +0x795
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.(*UpgradeAwareHandler).ServeHTTP(0xc42dc91920, 0x7f0792f74668, 0xc429e77bd8, 0xc427b45300)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:231 +0x838
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc4280e7500, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:150 +0x690
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42c29ab80, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x567
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc42221ff10, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x38d305c, 0xf, 0xc427ef6510, 0xc42221ff10, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc427f42120, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	<autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37a
net/http.HandlerFunc.ServeHTTP(0xc423eb0cd0, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:98 +0x5a0
net/http.HandlerFunc.ServeHTTP(0xc427d8b480, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x21b2
net/http.HandlerFunc.ServeHTTP(0xc423eb0d20, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc423eb0d70, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc427f42140, 0x7f0792f74668, 0xc429e77bd8, 0xc427b44e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc427f421c0, 0x8172b40, 0xc429e77bd8, 0xc427b44e00, 0xc42dc918c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x1ca

logging error output: "Error: 'context canceled'\nTrying to reach: 'https://10.99.129.104:443/apis/metrics.k8s.io/v1beta1'"
 [[kubectl/v1.8.4 (linux/amd64) kubernetes/9befc2b] 172.20.0.8:46378]
```

The IP is tries to connect to is the metrics-server's clusterIP. After deleting the metrics-server service, kubectl became responsive again.

During this time flannel didn't setup networking yet. (FWIW, I deploy it via a daemonset which has a init container to install the CNI plugins).

**What you expected to happen**:
It looks like something trying to reach the metrics-server blocked both kubectl as well as deployment of the flannel daemonset.
But even under this condition kubectl should still work. Fortunately I was able to remove the service via curl, though using kubectl would be much more convienient.

**How to reproduce it (as minimally and precisely as possible)**:
Haven't tried to reproduce it and might happen with single controller clusters but this is what I did:
1. Deploy cluster with 3 controller instances
2. Install flannel
3. Install metrics server
4. Replace all instances one by one

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4 installed by kubeadm, running 1.8.4+coreos.0 hyperkube kubelet
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): 1520.8.0

**Comment by liggitt** [comment] 2017-12-13 04:44
Dupe of https://github.com/kubernetes/kubernetes/issues/56430

**Closed by liggitt** 2017-12-13 04:44 UTC
Labels: kind/bug, sig/api-machinery
