### ISSUE TITLE
kube-proxy unable to connect to other instances

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#14842] opened 2015-09-30 18:49 UTC
I recently upgrade from CoreOS 801 -> 815, and from Kubernetes 1.0.5 -> 1.0.6. I'm using cloudformations that use the [cloud-configs in here](https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos). After the initial upgrade, there were no issues, but one of my EC2 instances died last night. The instance I brought up to replace it was unable to route any packets via kube-proxy, in or out; that is, service traffic from other instances to pods on this instance were rejected with connection refused messages, and traffic from these pods to services with pods on other instances were also rejected.

`journalctl -u flanneld.service` did not render any error messages. Most of the logs here indicate additions to the iptables (which all look sane, and show up in `iptables -L ...` lists), and then various announcements of peerings ("Calling NeighAdd" and NeighDel, for instance).

kube-proxy.service is another matter.

```
core@ip-10-50-24-20 ~ $ sudo journalctl -u kube-proxy.service -f
-- Logs begin at Wed 2015-09-30 18:08:14 UTC. --
Sep 30 18:46:31 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:31.822318    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.3:80: no route to host
Sep 30 18:46:31 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:31.822376    1043 proxysocket.go:133] Failed to connect to balancer: failed to connect to an endpoint.
Sep 30 18:46:32 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:32.822792    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.3:80: i/o timeout
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.088811    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.2:5672: connection refused
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.088924    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.2:5672: connection refused
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.089005    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.2:5672: connection refused
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.089111    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.2:5672: connection refused
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.089123    1043 proxysocket.go:133] Failed to connect to balancer: failed to connect to an endpoint.
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.823128    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.3:80: i/o timeout
Sep 30 18:46:34 ip-10-50-24-20.us-west-1.compute.internal kube-proxy[1043]: E0930 18:46:34.828304    1043 proxysocket.go:99] Dial failed: dial tcp 172.17.0.3:80: no route to host
```

Here's my ifconfig:

```
$ ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.17.42.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:e1ff:fe17:2a1d  prefixlen 64  scopeid 0x20<link>
        ether 02:42:e1:17:2a:1d  txqueuelen 0  (Ethernet)
        RX packets 25268  bytes 4023320 (3.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25322  bytes 30866064 (29.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.50.24.20  netmask 255.255.248.0  broadcast 10.50.31.255
        inet6 fe80::429:1ff:fe52:592f  prefixlen 64  scopeid 0x20<link>
        ether 06:29:01:52:59:2f  txqueuelen 1000  (Ethernet)
        RX packets 376521  bytes 516340029 (492.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 69416  bytes 10027688 (9.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 8951
        inet 10.244.29.0  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::b00f:5fff:fede:6cba  prefixlen 64  scopeid 0x20<link>
        ether b2:0f:5f:de:6c:ba  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 18 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 25393  bytes 7814156 (7.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25393  bytes 7814156 (7.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth1b78165: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::3401:32ff:fe73:82a8  prefixlen 64  scopeid 0x20<link>
        ether 36:01:32:73:82:a8  txqueuelen 0  (Ethernet)
        RX packets 9  bytes 738 (738.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 603  bytes 26526 (25.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth979a22a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::dc5b:87ff:fee8:1029  prefixlen 64  scopeid 0x20<link>
        ether de:5b:87:e8:10:29  txqueuelen 0  (Ethernet)
        RX packets 1279  bytes 772462 (754.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2082  bytes 140057 (136.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vetha78d2cf: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::5c87:edff:fe63:ab97  prefixlen 64  scopeid 0x20<link>
        ether 5e:87:ed:63:ab:97  txqueuelen 0  (Ethernet)
        RX packets 9  bytes 738 (738.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 538  bytes 23180 (22.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethaaec416: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::44e9:8aff:fe60:499f  prefixlen 64  scopeid 0x20<link>
        ether 46:e9:8a:60:49:9f  txqueuelen 0  (Ethernet)
        RX packets 13626  bytes 1985947 (1.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13451  bytes 27833005 (26.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethf4f82b8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::6418:2ff:fec9:c409  prefixlen 64  scopeid 0x20<link>
        ether 66:18:02:c9:c4:09  txqueuelen 0  (Ethernet)
        RX packets 10082  bytes 1622126 (1.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10938  bytes 2958649 (2.8 MiB)
        TX errors 0  dropped 3 overruns 0  carrier 0  collisions 0
```

And here's an example ReplicationController and Service that I'm having trouble getting through to:

```
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  selector:
    component: rabbitmq
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
```

**Comment by jcderr** [comment] 2015-09-30 19:23
after a whole tonne of troubleshooting, it looks like the issue is in fact with flannel; starting two docker containers all by themselves, they can't even ping one another.

**Comment by cjcullen** [comment] 2015-09-30 20:25
Can I go ahead and close this issue for now?

**Comment by jcderr** [comment] 2015-09-30 20:41
Yeah - I was just getting everything cleaned up after fixing this in my stack. It was ultimately tracked down to an issue in CoreOS alpha channel.

**Comment by cjcullen** [comment] 2015-09-30 20:53
Glad you found your root cause.

**Closed by cjcullen** 2015-09-30 20:53 UTC
