### ISSUE TITLE
PR merge failure: [Fail] Daemon set [It] should run and stop simple daemon 

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21767] opened 2016-02-23 17:33 UTC
PR builder failed when trying to merge

log:

>
Summarizing 1 Failure:
[Fail] Daemon set [It] should run and stop simple daemon 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:117
Ran 137 of 237 Specs in 426.097 seconds
FAIL! -- 136 Passed | 1 Failed | 0 Pending | 100 Skipped 

>
â€¢ Failure [335.605 seconds]
Daemon set
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:194
  should run and stop simple daemon [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:139
  error waiting for daemon pod to be reaped
  Expected error:
      <*errors.errorString | 0xc20802c8a0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:117

**Comment by mikedanese** [comment] 2016-02-24 03:42
These tests only fail when run in parallel with other tests. ref #16623

**Comment by mml** [comment] 2016-02-24 22:16
@pwittrock do you have a link to the whole run where this failed?

**Comment by pwittrock** [comment] 2016-02-25 00:54
Yes: [mergeflake.txt](https://github.com/kubernetes/kubernetes/files/145735/mergeflake.txt)

**Comment by pwittrock** [comment] 2016-02-25 00:56
Also:
https://doc-1c6us-10oao-s-googleusercontent.commondatastorage.googleapis.com/gs/fuc2vio4jd536so122rmrf52ehn3qlv5/nfbhte0cs20s3559geuq5p16ke5vkkn0/1456353000000/kubernetes-jenkins/01720166177040642613/ChJrdWJlcm5ldGVzLWplbmtpbnMSSXByLWxvZ3MvcHVsbC8yMDk0MC9rdWJlcm5ldGVzLXB1bGwtYnVpbGQtdGVzdC1lMmUtZ2NlLzI5OTYzL2J1aWxkLWxvZy50eHQ?a=AGjQbs4R7zWz8hx7U3HZF1jZNvDSIsI3zD3HhEVQRl8NndF39XtRB4-deKDlElRZY_5jkahsU7jJEzseG6gSz7D2_U7J-oT1XGCYmE1fItKHxIRJD0_uneGwyRTabkCXZO_ZC16H8ZosTo4tQS9Aiio04bq9yw_9n8cGFzwJnuG78ILMjo3tCCiaqN7I_URnPzMPpuASiqb_1Ry4yYCbh-TeEl0qivk3FqIvctPEDyPHT6HtS6RwKsL6q4yvaF_7S7CJmDXxw8wczBtAY_5l5NZY83wfxgjGBvo9lsJlNe8Z3EvSg799nTYz7mqf4stjL2Hvi5q9syxFmHimCofKTvSH0_ruVrSAYNerrUAuyfubTiGZH1OgO1l3YSIHiFyNZFo4g3bO9VbCeSs7MS8mlaITeWNK359wmSybGQ8B5HY2InPNdWGa-CbHCX1px-aX3ka3PzqHQCOd587-EJPKDMVUHUY8mjMVULZK7n49gG8jraLxxsHIc-kZ_7F_puhe_Rh4b2ElG42rUouzLpvvBnpG_8GkV1uJCQou_LC_Y7MtFm8TTCTpOFnsMvUaYQOmcf9uizimpE7C_5nTMm9Yf_3kqe_sYLqsfdjTI-3VmoK_1C3zmBWX5AHJ8XYsoEf0TodqVb7GLEyDSKzqDOejlwzm5rTHB7WBBYPidMZ4fT6ZnPFMllqPnzn2uEFYNffEoujMnsZ6-9Vg5kbOtyAzl5E9a0W9yVmE0-0iMbAaPwtX5rfkwLqvLhpxGXwWBEzm1VH-YEqHxY3hl5MrCcEWB2CZxan18VXTGQ

**Comment by gmarek** [comment] 2016-02-29 13:02
@mml @mikedanese - I looked at this flake and it actually looks like a real-ish problem somewhere (in system or in test logic). What this test does, to my understanding, is that it schedules one daemon on every Node, then lists daemons and expects that they will be one running daemon per Node. This implicitly assumes that daemon has a 'higher priority' than other pods running on Nodes, which turns out not to be true. From one of the logs that @pwittrock pasted:
```
Feb 23 06:55:54.190: INFO: event for daemon-set-cjy7y: {kubelet e2e-gce-builder-3-2-minion-poqh} Pulling: pulling image "gcr.io/google_containers/serve_hostname:1.1"
Feb 23 06:55:54.190: INFO: event for daemon-set-cjy7y: {kubelet e2e-gce-builder-3-2-minion-poqh} Pulled: Successfully pulled image "gcr.io/google_containers/serve_hostname:1.1"
Feb 23 06:55:54.190: INFO: event for daemon-set-cjy7y: {kubelet e2e-gce-builder-3-2-minion-poqh} Created: Created container with docker id 1be517b4a102
Feb 23 06:55:54.190: INFO: event for daemon-set-cjy7y: {kubelet e2e-gce-builder-3-2-minion-poqh} Started: Started container with docker id 1be517b4a102
Feb 23 06:55:54.190: INFO: event for daemon-set-cjy7y: {kubelet e2e-gce-builder-3-2-minion-poqh} Killing: Killing container with docker id 1be517b4a102: Need to kill pod.
```
which means that Kubelet decided to kill the daemon. I'm not quite sure why it did this, assuming that PR-builder cluster nodes has 2 CPUs, while it had only slightly more than 1CPU allocated:
```
Logging pods the kubelet thinks is on node e2e-gce-builder-3-2-minion-poqh
W0223 06:55:55.957557   22060 request.go:627] Throttling request took 188.344779ms, request: https://104.197.111.52/api/v1/proxy/nodes/e2e-gce-builder-3-2-minion-poqh:10250/runningpods
Feb 23 06:55:55.971: INFO: elasticsearch-logging-v1-rfpic started at <nil> (0 container statuses recorded)
Feb 23 06:55:55.971: INFO: fluentd-elasticsearch-e2e-gce-builder-3-2-minion-poqh started at <nil> (0 container statuses recorded)
Feb 23 06:55:55.971: INFO: kube-proxy-e2e-gce-builder-3-2-minion-poqh started at <nil> (0 container statuses recorded)
Feb 23 06:55:55.971: INFO: kibana-logging-v1-blofk started at <nil> (0 container statuses recorded)
Feb 23 06:55:55.971: INFO: kube-dns-v10-6m7kt started at <nil> (0 container statuses recorded)
Feb 23 06:55:55.971: INFO: monitoring-influxdb-grafana-v3-iucd6 started at <nil> (0 container statuses recorded)
```
All those pods account for 1010 CPUs if I didn't make any mistakes. It is possible that some other pods were present there during the test and died before this log line appeared.

cc @kubernetes/goog-node

**Comment by gmarek** [comment] 2016-02-29 13:39
I looked at the kubelet-logs and they confirm my theory - in the same time when daemon was scheduled on `poqh` node there were at least a couple of other tests running. Around that time I noticed Kubelet logs about `nginx`, `redis master`, `cleanup` (from kubelet cleanup test), `liveness-http` and I probably missed a couple. It's quite possible that all those pods were fully saturating the Node and after the Daemon got scheduled on this node things went astray.

It seems to me that either DeamonController doesn't look at available resources (which *sounds* OK by itself), or there's a race between DC and Scheduler (which isn't good), and Kubelet treats Daemons as normal Pods (which *sounds* OK by itself as well).

If DaemonController actually looks at resources then we have a race between Scheduler and DaemonController and we need to synchronize them somehow. If it doesn't we either should give daemons higher priority (i.e. make Kubelet kill them as last ones) or force the DaemonScheduler to take amount of free resources into account when creating daemons on Nodes AND synchronize itself with the Scheduler. I think the former is easier as the latter requires us to wait for etcdv3.

cc @lavalamp @davidopp @dchen1107 @bgrant0607

**Comment by mikedanese** [comment] 2016-02-29 17:59
@gmarek nice work. That would explain why it's not flaky in the non-parallel suites.

> DeamonController doesn't look at available resources

It should be.

> there's a race between DC and Scheduler

Daemonset pod's bypass the scheduler as DSC writes node name directly. It's possible it could race with scheduled pods but rather than solving with complicated locking, we should just account for that. We have the same problem with multiple schedulers and other controllers that create pods. Kubelet has final say in admission so worst case is some pods will fail to schedule.

> Kubelet treats Daemons as normal Pods

This is the case (sadly) and will probably be until we implement preemption.


Should we restrict this to the serial suites until we get it sorted out?

**Comment by lavalamp** [comment] 2016-02-29 18:32
There is a race between scheduler & dc by design. This should always be resolved in DC's favor (probably?) but we have no eviction mechanism right now. So I think this is a legit system problem and we can paper it over for the moment by moving this test to be serial :/

**Comment by wojtek-t** [comment] 2016-02-29 18:37
That should be pretty simple fix :)

**Comment by mml** [comment] 2016-02-29 20:34
Exccelent work, @gmarek.

We should move it to serial, and we should add a comment above the test explaining that its assumptions will not hold if anything else is going on, unless/until we get eviction.

I'll send a PR.

**Comment by davidopp** [comment] 2016-02-29 21:33
Yeah, very nice work @gmarek .

As others have said, once we have priority, the regular pod would get accepted by kubelet admission and the daemon would get rejected, but then the daemon controller would try again and that time it would succeed since it would explicit evict the regular pod.

**Closed** 2016-03-01 00:25 UTC
Labels: kind/flake, priority/P1, team/control-plane
