### ISSUE TITLE
Namespace controller should scale rcs to 0 before deleting pods

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#22825] opened 2016-03-10 22:03 UTC
http://pr-test.k8s.io/22807/kubernetes-pull-build-test-e2e-gce/32271/build-log.txt

```
STEP: Destroying namespace "e2e-tests-services-1ymgz" for this suite.
STEP: Destroying namespace "e2e-tests-services-kdrdp" for this suite.
Mar 10 11:15:17.444: INFO: Pod e2e-tests-services-kdrdp mutability-test-r7zn3 on node e2e-gce-builder-3-3-minion-gt43 remains, has deletion timestamp <nil>
Mar 10 11:15:17.444: FAIL: Couldn't delete ns "e2e-tests-services-kdrdp": pods remained within namespace e2e-tests-services-kdrdp after deletion: [mutability-test-r7zn3]


â€¢ Failure in Spec Teardown (AfterEach) [417.838 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:902
  should be able to change the type and ports of a service [AfterEach]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:716

  Mar 10 11:15:17.444: Couldn't delete ns "e2e-tests-services-kdrdp": pods remained within namespace e2e-tests-services-kdrdp after deletion: [mutability-test-r7zn3]

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:177
```

**Comment by lavalamp** [comment] 2016-03-11 00:36
@thockin to delegate

**Comment by bprashanth** [comment] 2016-03-11 18:56
This is a race in the namespace controller. We deleted the ns, but leaked a pod:
```
Mar 10 11:15:17.444: INFO: Pod e2e-tests-services-kdrdp mutability-test-r7zn3 on node e2e-gce-builder-3-3-minion-gt43 remains, has deletion timestamp <nil>
Mar 10 11:15:17.444: FAIL: Couldn't delete ns "e2e-tests-services-kdrdp": pods remained within namespace e2e-tests-services-kdrdp after deletion: [mutability-test-r7zn3]
```

From namespace_controller logs:
```
I0310 19:15:12.450848       6 namespace_controller_utils.go:256] namespace controller - deleteAllContentForGroupVersionResource - namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}
I0310 19:15:12.450863       6 namespace_controller_utils.go:264] namespace controller - deleteAllContentForGroupVersionResource - estimate - namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}, estimate: 0
I0310 19:15:12.450871       6 namespace_controller_utils.go:149] namespace controller - deleteCollection - namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}
I0310 19:15:12.450879       6 namespace_controller_utils.go:153] namespace controller - deleteCollection ignored since not supported - namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}
I0310 19:15:12.450887       6 namespace_controller_utils.go:227] namespace controller - deleteEachItem - namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}
I0310 19:15:12.450918       6 namespace_controller_utils.go:289] namespace controller - deleteAllContentForGroupVersionResource - checking for no more items in namespace: e2e-tests-services-kdrdp, gvr: {extensions v1beta1 replicationcontrollers}
I0310 19:15:12.486164       6 namespace_controller_utils.go:256] namespace controller - deleteAllContentForGroupVersionResource - namespace: e2e-tests-services-kdrdp, gvr: { v1 pods}
I0310 19:15:12.487768       6 namespace_controller_utils.go:264] namespace controller - deleteAllContentForGroupVersionResource - estimate - namespace: e2e-tests-services-kdrdp, gvr: { v1 pods}, estimate: 0
I0310 19:15:12.487788       6 namespace_controller_utils.go:149] namespace controller - deleteCollection - namespace: e2e-tests-services-kdrdp, gvr: { v1 pods}
I0310 19:15:12.495860       6 namespace_controller_utils.go:289] namespace controller - deleteAllContentForGroupVersionResource - checking for no more items in namespace: e2e-tests-services-kdrdp, gvr: { v1 pods}
I0310 19:15:12.500595       6 namespace_controller_utils.go:298] namespace controller - deleteAllContentForGroupVersionResource - items remaining - namespace: e2e-tests-services-kdrdp, gvr: { v1 pods}, items: 0
I0310 19:15:12.506324       6 namespace_controller_utils.go:256] namespace controller - deleteAllContentForGroupVersionResource - namespace: e2e-tests-services-kdrdp, gvr: { v1 replicationcontrollers}
I0310 19:15:12.506350       6 namespace_controller_utils.go:264] namespace controller - deleteAllContentForGroupVersionResource - estimate - namespace: e2e-tests-services-kdrdp, gvr: { v1 replicationcontrollers}, estimate: 0
I0310 19:15:12.506364       6 namespace_controller_utils.go:149] namespace controller - deleteCollection - namespace: e2e-tests-services-kdrdp, gvr: { v1 replicationcontrollers}
I0310 19:15:12.509349       6 namespace_controller_utils.go:289] namespace controller - deleteAllContentForGroupVersionResource - checking for no more items in namespace: e2e-tests-services-kdrdp, gvr: { v1 replicationcontrollers}
I0310 19:15:12.510371       6 namespace_controller_utils.go:298] namespace controller - deleteAllContentForGroupVersionResource - items remaining - namespace: e2e-tests-services-kdrdp, gvr: { v1 replicationcontrollers}, items: 0
```

The pod that was leaked was created by the rc when it detected a termination grace period on an existing pod. So why not scale the rc, wait for it to hit 0, delete it, then cleaning up any pods? 

@derekwaynecarr 

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/32271/
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22807/kubernetes-pull-build-test-e2e-gce/32271/

**Comment by bprashanth** [comment] 2016-03-11 18:58
Un-assigning Tim to let someone else with cycles take over, since this doesn't look like team/cluster

**Comment by derekwaynecarr** [comment] 2016-03-11 20:31
I was hoping to avoid having to infer a priority order or do any special behaviors per controller in deletion since admission should be blocking the controller from doing new creations here.

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/namespace/lifecycle/admission.go#L93

It's possible that local admission controller had a latent cache.

**Comment by derekwaynecarr** [comment] 2016-03-11 20:35
Closing as its a duplicate of https://github.com/kubernetes/kubernetes/issues/22045

**Closed by derekwaynecarr** 2016-03-11 20:35 UTC
Labels: kind/flake, team/control-plane
