### ISSUE TITLE
PVCs failing to be created still count towards the resource quota

### ISSUE THREAD

**Issue by ldruschk** [kubernetes/kubernetes#119593] opened 2023-07-26 15:21 UTC
### What happened?

When creating a PVC and the creation fails because a PVC with that name already exists, that will still count towards the namespaces resource quota.

### What did you expect to happen?

When a PVC cannot be created, it should not count towards the resource quota.

### How can we reproduce it (as minimally and precisely as possible)?

```
student@k8s-node-11:~$ cat storage-quota.yaml 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "800Mi"

student@k8s-node-11:~$ cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-one
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
```

```
student@k8s-node-11:~$ kubectl create ns reproduce
namespace/reproduce created
student@k8s-node-11:~$ kubectl -n reproduce create -f storage-quota.yaml 
resourcequota/storagequota created
student@k8s-node-11:~$ kubectl describe ns reproduce 
Name:         reproduce
Labels:       kubernetes.io/metadata.name=reproduce
Annotations:  <none>
Status:       Active

Resource Quotas
  Name:                   storagequota
  Resource                Used  Hard
  --------                ---   ---
  persistentvolumeclaims  0     10
  requests.storage        0     800Mi

No LimitRange resource.
student@k8s-node-11:~$ kubectl create -n reproduce -f pvc.yaml 
persistentvolumeclaim/pvc-one created
student@k8s-node-11:~$ kubectl describe ns reproduce 
Name:         reproduce
Labels:       kubernetes.io/metadata.name=reproduce
Annotations:  <none>
Status:       Active

Resource Quotas
  Name:                   storagequota
  Resource                Used   Hard
  --------                ---    ---
  persistentvolumeclaims  1      10
  requests.storage        200Mi  800Mi

No LimitRange resource.
student@k8s-node-11:~$ kubectl get -n reproduce pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-one   Pending                                                     13s
student@k8s-node-11:~$ kubectl create -n reproduce -f pvc.yaml 
Error from server (AlreadyExists): error when creating "pvc.yaml": persistentvolumeclaims "pvc-one" already exists
student@k8s-node-11:~$ kubectl describe ns reproduce
Name:         reproduce
Labels:       kubernetes.io/metadata.name=reproduce
Annotations:  <none>
Status:       Active

Resource Quotas
  Name:                   storagequota
  Resource                Used   Hard
  --------                ---    ---
  persistentvolumeclaims  2      10
  requests.storage        400Mi  800Mi

No LimitRange resource.
student@k8s-node-11:~$ kubectl get -n reproduce pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-one   Pending                                                     48s
```
When repeating this a few times, it will eventually lead to errors since we can't create any more PVCs:
```
student@k8s-node-11:~$ kubectl create -n reproduce -f pvc.yaml 
Error from server (AlreadyExists): error when creating "pvc.yaml": persistentvolumeclaims "pvc-one" already exists
student@k8s-node-11:~$ kubectl create -n reproduce -f pvc.yaml 
Error from server (AlreadyExists): error when creating "pvc.yaml": persistentvolumeclaims "pvc-one" already exists
student@k8s-node-11:~$ kubectl create -n reproduce -f pvc.yaml 
Error from server (Forbidden): error when creating "pvc.yaml": persistentvolumeclaims "pvc-one" is forbidden: exceeded quota: storagequota, requested: requests.storage=200Mi, used: requests.storage=800Mi, limited: requests.storage=800Mi
```

After waiting some minutes, the quotas are reset to be correct:
```
student@k8s-node-11:~$ kubectl describe ns reproduce
Name:         reproduce
Labels:       kubernetes.io/metadata.name=reproduce
Annotations:  <none>
Status:       Active

Resource Quotas
  Name:                   storagequota
  Resource                Used   Hard
  --------                ---    ---
  persistentvolumeclaims  1      10
  requests.storage        200Mi  800Mi

No LimitRange resource.
```

### Kubernetes version

<details>

```console
student@k8s-node-11:~$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Running on digital ocean VMs, cluster installed using kubeadm

```
student@k8s-node-11:~$ kubectl get node
NAME          STATUS   ROLES           AGE   VERSION
k8s-node-11   Ready    control-plane   27h   v1.27.4
k8s-node-12   Ready    <none>          27h   v1.27.4
```
</details>

### OS version

<details>

```console
student@k8s-node-11:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
student@k8s-node-11:~$ uname -a
Linux k8s-node-11 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Cluster installed manually using kubeadm with the packages from the official apt repository:
```
student@k8s-node-11:~$ cat /etc/apt/sources.list.d/kubernetes.list 
deb http://apt.kubernetes.io/ kubernetes-xenial main
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
student@k8s-node-11:~$ containerd --version
containerd containerd.io 1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Using calico version 3.25.0 from here: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
</details>

**Comment by carlory** [comment] 2023-07-27 09:23
After a deep code reading, I think it's not a sig-storage issue. But I'm not sure if it's real bug or not.

the quota admission in the kube-apiserver will update the usage value of a quota object if the request is admited though the request would be rejected by the kube-apiserver later. When a user create the same resource repeatedly in a very short time like this issue, the quota admission will update the usage value of the quota object to a wrong value eventually lead to reject other requests.

the quota controller in the kube-controller-manager is responsible for tracking quota usage status in the system and sync the quota object from the apiserver when quota is changed, and update the usage value of the quota to real.

/sig api-machinery

/cc @xing-yang for sig-storage side reivew.

/cc @deads2k

**Comment by jiahuif** [comment] 2023-07-27 16:38
/assign @xing-yang 
For sig-storage.
/triage accepted

**Comment by liggitt** [comment] 2023-08-04 05:27
Admission is enforced prior to persisting to etcd, so the resource quota reservation is committed before the write fails.

The quota controller periodically syncs consumed quota with actually persisted objects, but recovering quota reserved for a failed create happens asynchronously, not synchronously. 

This issue is a duplicate of https://github.com/kubernetes/kubernetes/issues/61530, https://github.com/kubernetes/kubernetes/issues/70563, https://github.com/kubernetes/kubernetes/issues/76787

**Closed by liggitt** 2023-08-04 05:27 UTC
Labels: kind/bug, sig/storage, sig/api-machinery, triage/accepted
