### ISSUE TITLE
Azure cluster creation fails and exits with an undefined resource exists

### ISSUE THREAD

**Issue by ShadySQL** [kubernetes/kubernetes#21067] opened 2016-02-11 12:02 UTC
Basically I try to deploy to azure but it fails epically all the time. It first complains about a storage account but the storage account doesnt exist.

Error: The storage account '6467741c7b0626' was not found.
  <<< async stack >>>
  at deleteAccount (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js:195:56)
  at storageAccount_deleteCommand__5 (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js:472:5)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

---After this I destroy the deployment and try again and then it says that a network with the name undefined already exist. Basically on the first run it creates the network but fails to deploy the storage account and when I delete the network it says that it still cant locate the storage account.

**Comment by bgrant0607** [comment] 2016-02-11 17:34
cc @colemickens

**Comment by yaron2** [comment] 2016-02-21 06:08
Please resolve this...

**Comment by colemickens** [comment] 2016-02-21 07:23
What version of `azure-xplat-cli` is being used?

**Comment by yaron2** [comment] 2016-02-21 10:24
0.9.15

**Comment by magmax** [comment] 2016-02-23 15:59
Try by setting the environment variable ``AZURE_STORAGE_ACCOUNT`` to an existing one in the selected subscrition.

You can select the subscription by setting the environment variable ``AZ_SUBSCRIPTION``.

**Comment by TomFreeman** [comment] 2016-03-05 16:07
I experienced this, setting the subscription explicitly seems to have worked around it.

**Comment by ShadySQL** [comment] 2016-03-05 16:17
What do you mean on setting the subscription explicitly? What did you do? Mind sharing please

**Comment by TomFreeman** [comment] 2016-03-05 16:27
setting the AZ_SUBSCRIPTION environment variable, but not setting the AZURE_STORAGE_ACCOUNT one, or indeed anything else.

get_subscriptions was returning undefined all the time, which seemed to be the cause for all the accounts being named 'undefined'

**Comment by ShadySQL** [comment] 2016-03-05 16:37
Thanks. So for my case I have BizSpark Plus and that's the name of my subscription so are you saying all I would need to do is run:

SET AZ_SUBSCRIPTION="BizSpark Plus"

??

**Comment by colemickens** [comment] 2016-03-05 19:14
@ShadySQL There would be a GUID value that you need to place there. If you have logged in the with `azure-xplat-cli` previously, then you can look in your `~/.azure/azureProfile.json` file to determine the subscription id. Alternatively it can be found the in Azure Portal under the "Subscriptions" resource.

**Comment by acesyde** [comment] 2016-03-17 20:42
If you use powershell set env by $env:AZ_SUBSCRIPTION = "GUID"

**Comment by loic-sharma** [comment] 2016-03-28 04:05
I ran into this problem too. It seems like [this](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/lib/azure_wrapper.js#L163) is the issue. If `get_subscription` can't find a `AZ_SUBSCRIPTION` environment variable, it returns nothing, which causes all of the azure to get an undefined value instead of a subscription id.

Now what's really weird is that node doesn't pick up my AZ_SUBSCRIPTION environment variable. I was able to get around this by explicitly declaring it:

```
AZ_SUBSCRIPTION=... ./create-kubernetes-cluster.js
```

**Comment by ffissore** [comment] 2016-04-04 13:49
I confirm bug (undefined all over) and workaround (setting AZ_SUBSCRIPTION env var)

**Comment by jdr0dn3y** [comment] 2016-04-06 18:22
AZ_SUBSCRIPTION doesn't get set properly for me when I login to Azure. You need to either explicitly set it on execute, or explicitly set it in your environment variables prior to running ./create.

**Comment by roberthbailey** [comment] 2017-04-25 06:08
@ShadySQL / @colemickens -- I'm going to close this issue since it hasn't been updated in over a year. Please re-open if this is still a problem with Kubernetes 1.6.

**Closed by roberthbailey** 2017-04-25 06:08 UTC
Labels: area/platform/azure, priority/backlog, sig/cluster-lifecycle, team/control-plane (deprecated - do not use)
