### ISSUE TITLE
Controller manager stuck in "the object has been modified; please apply your changes to the latest version and try again" even after restart

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#95958] opened 2020-10-28 19:18 UTC
**What happened**:
In controller manager we sometimes observed logs such as below. This happens to many resource type such as endpoints and replicasets. We thought it's staled informer cache, but after bouncing controller manager we still see the same logs. The only way to mitigate this is to bounce api-server.

```
Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"cig-prod-apps", Name:"<omitted>", UID:"4593f854-b824-4a9e-8e10-c16d558797b9", APIVersion:"autoscaling/v2beta2", ResourceVersion:"71905040", FieldPath:""}): type: 'Warning' reason: 'FailedUpdateStatus' Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "<omitted>": the object has been modified; please apply your changes to the latest version and try again
```

`kubectl get hpa` returns resources with proper resource versions, though.

**What you expected to happen**:
there seems to be some kind of caching in api-server? I think it should not return staled information

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): observed on 1.15, 1.17, 1.18
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by roycaihw** [comment] 2020-10-29 21:38
/sig autoscaling
/sig apps

@weinong Was the controller keep sending requests with the same resource version or different ones? I wonder if it can be some other clients in your cluster racing updating the objects. 

> but after bouncing controller manager we still see the same logs
> kubectl get hpa returns resources with proper resource versions, though.


IIRC the informer lists from watch cache after restart, while kubectl lists from etcd. cc @wojtek-t @jpbetz 

I think we need more evidence and a way to reproduce to better triage this issue. When you hit the issue again, before restarting the apiserver, could you try listing the objects with resourceVersion="0" and with resourceVersion unspecified, and see if you can capture a consistent difference between the two result for a period time?

**Comment by weinong** [comment] 2020-10-29 23:52
> Was the controller keep sending requests with the same resource version or different ones? I wonder if it can be some other clients in your cluster racing updating the objects.

From audit log, I really don't see any "list" from informer (is it expected?). but the watch always has the same resource version even after controller-manager is restarted.

**Comment by weinong** [comment] 2020-10-30 00:47
```
kubectl get --raw /apis/autoscaling/v1/namespaces/<omitted>/horizontalpodautoscalers/<omitted>?resourceVersion=0 | jq -r ".metadata.resourceVersion"
71905040
kubectl get --raw /apis/autoscaling/v1/namespaces/<omitted>/horizontalpodautoscalers/<omitted> | jq -r ".metadata.resourceVersion"
71902025
```
@roycaihw what does it mean?

**Comment by wojtek-t** [comment] 2020-10-30 09:45
THe fact that those two are different is expected:
- when listing from cache return RV that can be from objects of that type (so in this case it can be RV of the last even of any HPA object)
- whe listing from etcd we get the higher RV across the whole etcd

[The first one will change once https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption ]

This these logs doesn't contain anything particularly useful...

**Comment by wojtek-t** [comment] 2020-10-30 09:48
No wait...

71905040 > 71902025

So that seems super strange - it suggests that the watchcache is in front of kube-apiserver.
That generally can't happen, because we update watchcache only based on list/watch from etcd...

Did you do something strange to the etcd? Like restore its state or something?

**Comment by weinong** [comment] 2020-10-30 20:55
@wojtek-t does resource version imply the age of a resource like timestamp? etcd restore may be the culprit. but can api-server recover from such event?

**Comment by weinong** [comment] 2020-11-03 07:10
@wojtek-t I can repro this after triggering etcd restore without restarting api-server

**Comment by wojtek-t** [comment] 2020-11-03 12:35
OK - we have never promissed that you  can restore etcd without restarting api-server.
In fact, in order to correctly restore, you should restart all system component after that.

**Comment by roycaihw** [comment] 2020-11-03 23:29
Nice catch @wojtek-t! I think we can mention "you must restart system components after restoring etcd" in the [doc](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster) and close this issue. @weinong WDYT?

**Comment by weinong** [comment] 2020-11-04 00:04
SGTM! thanks!

**Comment by wojtek-t** [comment] 2020-11-04 15:27
@roycaihw - can you please take care of updating this documentation?

**Comment by roycaihw** [comment] 2020-11-05 18:39
Yes. Sorry I was going to send the PR but got distracted.

**Comment by roycaihw** [comment] 2020-11-05 19:26
sent https://github.com/kubernetes/website/pull/24911

**Closed** 2020-12-07 15:19 UTC
Labels: kind/bug, sig/api-machinery, sig/autoscaling, triage/accepted
