### ISSUE TITLE
If kube-controller-manager restarts, changes to ELBs are reverted

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#23744] opened 2016-04-01 17:26 UTC
I use LoadBalancer services in AWS to create ELBs. A typical service looks like this:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: internal-api
  name: internal-api
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    name: internal-api
  type: LoadBalancer
```

I have a script that will then slightly twiddle the ELB via the AWS API to change the listener from type `TCP` to type `HTTPS` and configure my SSL/TLS certificate.

If for any reason, the controller manager restarts, these changes are reverted. Preferably, the manager should only alter the ports in question and no other ELB parameters.

**Comment by willmore** [comment] 2016-04-09 20:25
We are facing the same issue on `1.1.4`. 
On our deployment, we manually create 443 listeners. These are removed upon controller restart.

**Comment by justinsb** [comment] 2016-06-03 23:24
This is actually by design; the ELB is considered "k8s-managed", and so will be "repaired".

We are adding more functionality by way of annotations on the service, so that you should have less and less need to configure your own ELB.

However, if you do need to, what I recommend is setting your service to Type=NodePort, and then setting up an ELB manually, and adding the node ASG to it.  That is more or less equivalent to what Type=LoadBalancer does, however k8s won't then try to manage the ELB.

Going to close this issue - feel free to reopen if needed.

**Closed by justinsb** 2016-06-03 23:25 UTC
Labels: area/networking, area/platform/aws, team/cluster

**Comment by jcderr** [comment] 2016-06-04 19:06
What I wound up doing is having an NGINX container that maps host names to services and attached _that_ to an ELB set up as you described.
