### ISSUE TITLE
Getting invalid Azure Active Directory token after upgrading kubectl to 1.17.2

### ISSUE THREAD

**Issue by iamcryptoki** [kubernetes/kubernetes#87643] opened 2020-01-29 10:19 UTC
**What happened**:

I have a Highly Available Kubernetes cluster (v1.17.0) living in a private Cloud, and API server is configured to authenticate users with Azure Active Directory.

Kubectl is installed on 3 computers with differents systems : macOS, Linux, and Windows.

1. After upgrading kubectl to 1.17.2 on my macOS computer, I am now getting `error: You must be logged in to the server (Unauthorized)` when trying to request the api server, e.g. `kubectl get pods`. I am still getting this error after having deleted and reconfigured my kubeconfig file with a new AAD token.

2. Then I tried to upgrade kubectl to 1.17.2 on my Linux computer. I am now getting the same error `error: You must be logged in to the server (Unauthorized)`. Also deleted and reconfigured my kubeconfig file with a new AAD token, but still getting the same error.

3. Then I tried to reconfigure the kubeconfig file on my mac using the same file that kubectl uses on my Windows computer, it works. Got authenticated, the API server accepts my requests.

3. Then I tried to delete and reconfigure my kubeconfig file on my Windows computer without upgrading kubectl. Kubectl version is 1.14.8. Got a new AAD token, kubectl works fine. Then I upgraded kubectl to 1.17.2 on that computer, I am now getting `error: You must be logged in to the server (Unauthorized)`.

It seems that the AAD token I get is invalid when using kubectl v1.17.2.

**What you expected to happen**:

Getting a valid AAD token using kubectl v1.17.2.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure API server to authenticate users with Azure Active Directory (OIDC).
2. Install kubectl v1.17.2 (or upgrade to).
3. Ask for authentification by running `kubectl get pods`.
>> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CL8HH8VMP to authenticate.
4. Authenticate to your account.

**Comment by liggitt** [comment] 2020-01-30 00:44
Thanks for the report. This is a duplicate of https://github.com/kubernetes/kubernetes/issues/87464 and will be resolved in 1.17.3 by https://github.com/kubernetes/kubernetes/issues/87540

**Closed by liggitt** 2020-01-30 00:44 UTC
Labels: kind/bug, needs-sig

**Comment by iamcryptoki** [comment] 2020-01-30 06:30
Thanks, @liggitt! Solved the issue by upgrading cluster from 1.17.0 to 1.17.2 and deleting `spn:` prefix in the OIDC configuration `--oidc-client-id=`.

**Comment by liggitt** [comment] 2020-01-30 06:38
To be clear, 1.17.3 will revert the breaking change, so you'll likely need to upgrade both server and kubectl at that point.

**Comment by iamcryptoki** [comment] 2020-01-30 07:25
Thanks, @liggitt!
