### ISSUE TITLE
kubeadm should not pull images for skipped addon phases (coredns, kube-proxy)

### ISSUE THREAD

**Issue by AndiDog** [kubernetes/kubernetes#114979] opened 2023-01-11 08:23 UTC
### What happened?

- Cluster created with custom CoreDNS installation, i.e. `skipPhases: [ addon/coredns ]` specified in kubeadm init configuration
- When joining a new node using `kubeadm join`, kubeadm still tries to pull all images
- If that image pull fails, kubeadm bails out despite the image not being required. See https://github.com/kubernetes/kubernetes/pull/114978 for how the CoreDNS image pull is special and could therefore fail.

### What did you expect to happen?

No image pull attempt for images belonging to skipped phases.

### How can we reproduce it (as minimally and precisely as possible)?

Not needed. The current functionality is very clear – see `GetControlPlaneImages` in code:

```
// GetControlPlaneImages returns a list of container images kubeadm expects to use on a control plane node
func GetControlPlaneImages(cfg *kubeadmapi.ClusterConfiguration) []string {
	images := make([]string, 0)

	// start with core kubernetes images
	images = append(images, GetKubernetesImage(constants.KubeAPIServer, cfg))
	images = append(images, GetKubernetesImage(constants.KubeControllerManager, cfg))
	images = append(images, GetKubernetesImage(constants.KubeScheduler, cfg))
	images = append(images, GetKubernetesImage(constants.KubeProxy, cfg))

	// pause is not available on the ci image repository so use the default image repository.
	images = append(images, GetPauseImage(cfg))

	// if etcd is not external then add the image as it will be required
	if cfg.Etcd.Local != nil {
		images = append(images, GetEtcdImage(cfg))
	}

	// Append the appropriate DNS images
	images = append(images, GetDNSImage(cfg))

	return images
}
```

### Anything else we need to know?

This also reduces unnecessary network throughput and is therefore in line with [KEP 3000](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3000-artifact-distribution) goals.

https://github.com/kubernetes/kubeadm/issues/1842 is quite similar.

### Kubernetes version

`master`

### Cloud provider

any

**Comment by neolit123** [comment] 2023-01-11 08:33
duplicate of
https://github.com/kubernetes/kubeadm/issues/2603

/close

**Closed by neolit123** 2023-01-11 08:33 UTC
Labels: kind/bug, needs-sig, needs-triage
