### ISSUE TITLE
integration flake: pods "cassandra" not found

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#22271] opened 2016-03-01 12:31 UTC
```
(B+++ [0301 03:21:16] Testing resource aliasing
pod "cassandra" created
service "cassandra" created
Successful get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}: cassandra:cassandra:
(Bservice "cassandra" deleted
Error from server: pods "cassandra" not found
E0301 03:21:16.915932   11778 nodecontroller.go:331] <nil>
!!! Error in ./hack/test-cmd.sh:1585
  'kubectl delete all -l app=cassandra "${kube_flags[@]}"' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:1585 runTests(...)
  2: ./hack/test-cmd.sh:1657 main(...)
Exiting with status 1
```
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22268/kubernetes-pull-test-unit-integration/16926/

may be related to #22128 #22134

cc @bgrant0607 @wojtek-t

**Comment by lavalamp** [comment] 2016-03-01 18:28
@caesarxuchao Looks like this is in test-cmd.sh, probably unrelated to the fix you made there but maybe you can still take a look.

@piosz copy-pasting an excerpt from the log makes it easier to route these things quickly.

**Comment by janetkuo** [comment] 2016-03-01 18:32
```
pod "cassandra" created
service "cassandra" created
Successful get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}: cassandra:cassandra:
(Bservice "cassandra" deleted
Error from server: pods "cassandra" not found
E0301 03:21:16.915932   11778 nodecontroller.go:331] <nil>
!!! Error in ./hack/test-cmd.sh:1585
  'kubectl delete all -l app=cassandra "${kube_flags[@]}"' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:1585 runTests(...)
  2: ./hack/test-cmd.sh:1657 main(...)
Exiting with status 1
```

**Comment by caesarxuchao** [comment] 2016-03-01 18:44
The pods are deleted by a `kubectl delete all ...`, which always sets the --ignore-not-found flag. It looks like the flag it not take effect. I'll dig into it later today.

**Comment by piosz** [comment] 2016-03-01 19:39
@lavalamp you are right. Sorry for that.

**Comment by caesarxuchao** [comment] 2016-03-02 06:58
I think this is https://github.com/kubernetes/kubernetes/issues/19403 all over again. The Cassandra pod hasn't been assigned a node when the deletion happens, so it will be deleted with `grace period=0`(https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/strategy.go#L115). 
After receiving the deletion request from kubectl, APIServer *may* get context-switched before it actually deletes the pod from etcd. At the same time, node controller sends another deletion request with 0 grace period and succeeded, When the first APIServer thread wakes and tries to continue the deletion, it fails because the pod is already deleted from etcd. The evidence supporting this hypothesis is the last line in the log:
```
E0301 03:21:16.915932   11778 nodecontroller.go:331] <nil>
```
and line 331 in nodecontroler.go is 
```
utilruntime.HandleError(nc.forcefullyDeletePod(pod))
```` 
The nil error suggests the nodecontroller has successfully deleted the pod with grace period 0.

**Comment by caesarxuchao** [comment] 2016-03-02 07:56
I think we can just ignore the error if api server replies the DELETE request with a "not found" error, i.e., ignore the "not found" error at this line: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete.go#L193

Because `kubectl delete` always issues a GET before issue DELETE, if user is deleting a resource that is never created, he'll still get the "not found" error.

**Comment by aveshagarwal** [comment] 2016-03-02 14:56
@caesarxuchao But as per cassandra test in hack/test-cmd.sh, cassandra pods are being created successfully, then why wouldn't they be assigned to a node? Also its not clear what is causing those pods to disappear that leads to this error. So it seems that the root cause is something else.

**Comment by aveshagarwal** [comment] 2016-03-02 15:08
Just wondering that is there a possibility that time between creation and deletion of a pod is so less that the pod has not yet been scheduled to a node before deletion causing this kind of race condition?

**Comment by caesarxuchao** [comment] 2016-03-02 18:01
Hi @aveshagarwal 
>  But as per cassandra test in hack/test-cmd.sh, cassandra pods are being created successfully, then why wouldn't they be assigned to a node? 

The log says its created successfully means the pods spec is written into the etcd, it doesn't indicate the pod has been assigned or is running.

> Also its not clear what is causing those pods to disappear that leads to this error. 

As I said, this log entry
```
E0301 03:21:16.915932   11778 nodecontroller.go:331] <nil>
```
indicates the node controller has successfully deletes the pod, and the root cause is the race between api server deleting a pod and other components deleting the pod.

**Comment by caesarxuchao** [comment] 2016-03-02 19:28
Sent https://github.com/kubernetes/kubernetes/pull/22376 to show what pod nodecontroller has deleted.

**Comment by caesarxuchao** [comment] 2016-03-02 19:28
I'm closing this issue in favor to #19403.

**Closed by caesarxuchao** 2016-03-02 19:28 UTC
Labels: area/test, kind/flake, priority/P1, team/ux
