### ISSUE TITLE
Investingate Kubemark regression caused by #39033

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#40291] opened 2017-01-23 09:52 UTC
We have a clear regression in kubemark-500.

Now pretty much 1/3rd tests are failing with error like this:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:253
scaling rc load-small-296 for the first time
Expected error:
    <*errors.errorString | 0xc426ef5bc0>: {
        s: "error while scaling RC load-small-296 to 5 replicas: timed out waiting for \"load-small-296\" to be synced",
    }
    error while scaling RC load-small-296 to 5 replicas: timed out waiting for "load-small-296" to be synced
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:484
```

This failed for the first time in this run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1806

We need to fix this ASAP as this is blocking submit-queue for long periods.

@k8s-oncall @shyamjvs @gmarek

**Comment by wojtek-t** [comment] 2017-01-23 09:55
Though, since this is flakiness, it might have happened a bit before this run...

**Comment by wojtek-t** [comment] 2017-01-23 10:41
I'm pretty sure that the errors here are coming from this point:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L242

That said, given the logs, it's clearly not timeout itself as it is "timeout after 10ms":
```
I0120 14:27:49.938] [1mSTEP[0m: Scaling { ReplicationController} load-small-296 in namespace e2e-tests-load-30-nodepods-2-nv03p to 5
I0120 14:27:49.949] Jan 20 14:27:49.948: INFO: Unexpected error occurred: error while scaling RC load-small-296 to 5 replicas: timed out waiting for "load-small-296" to be synced
```

So I guess we are hitting this path:
https://github.com/kubernetes/apimachinery/blob/master/pkg/watch/until.go#L64
which means that the watch is being closed.


However, what is interesting all the failures come from "scaling small RC to 5 replicas", which is pretty much a no-op (as they already have 5 replicas). So I don't know why we are even going into this path:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L226

**Comment by wojtek-t** [comment] 2017-01-23 10:46
BTW - the apiserver logs from this run:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1806/artifacts/kubemark-500-kubemark-master/

are ending in the middle of the test, so they are pretty much useless. We should also debug this later.

**Comment by wojtek-t** [comment] 2017-01-23 11:01
My hypothesis is that we are getting "ErrTimeout" as a result of "error too old" from apiserver. 
That said, it seems that nothing changed during last few days wrt to that, so I don't know why it is now failing...

**Comment by wojtek-t** [comment] 2017-01-23 15:13
BTW - we are also observing a huge regression around that time in kubemark-scale (and that one is really huge...)

**Comment by wojtek-t** [comment] 2017-01-23 15:13
This is the first run that completely blown up:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/224

**Comment by wojtek-t** [comment] 2017-01-23 15:19
@deads2k - to be honest, I looked into what was merged around that time, and my candidates for regression are either https://github.com/kubernetes/kubernetes/pull/40170 or https://github.com/kubernetes/kubernetes/pull/40146 (though I don't know yet what exactly is happening)

**Comment by deads2k** [comment] 2017-01-23 15:26
@wojtek-t those are moves without semantic changes.  I won't say its impossible, but it would really surprise me.

**Comment by wojtek-t** [comment] 2017-01-23 16:16
The other possibility is that this one broke something: https://github.com/kubernetes/kubernetes/pull/39033
[it seems that at least it increased the time the whole job takes by ~10m for kubemark-500].
@shyamjvs @gmarek - is that expected?

**Comment by shyamjvs** [comment] 2017-01-23 16:27
@wojtek-t I really doubt it. Besides I just noticed something interesting (which also kind of proves that there should be no issue with #39033), these rc scaling errors pop-up only during the first round of scaling (search for "Starting to scale ReplicationControllers first time..." and "Starting to scale ReplicationControllers second time...") and not in the second round. I checked this for 4 random runs and it seems to be case in all 4 of these (1806, 1848, 1858, 1863). This is quite spurious as it could possibly have something to do with the RC not being ready yet by the time we try scaling it.

**Comment by wojtek-t** [comment] 2017-01-23 16:29
What I just figured out is that "scaling" phase (being part of load test) started taking significantly more in this run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1803/?log#log
[~4m vs ~9m]

So I think the regression was exactly between 1802 and 1803 run. there are 4 PRs there:
https://github.com/kubernetes/kubernetes/pull/36693
https://github.com/kubernetes/kubernetes/pull/40154
https://github.com/kubernetes/kubernetes/pull/40170
https://github.com/kubernetes/kubernetes/pull/39033

The first one is trivial, the second one is only touching kubeadm.

So I think one of those is the problematic one:
https://github.com/kubernetes/kubernetes/pull/40170
https://github.com/kubernetes/kubernetes/pull/39033

Though the latter is only changing how we setup. So I'm really leaning towards #40170.
@deads2k - what could have changed as a result of that PR?

**Comment by shyamjvs** [comment] 2017-01-23 16:29
Also this error just happens for very few RCs (around 4-5) and this makes me feel strongly that it's a flaky performance issue rather than some code error.

**Comment by wojtek-t** [comment] 2017-01-23 16:30
@shyamjvs - it is performance issue, but now we are hitting it majority of runs, whereas previously we weren't hitting it at all. This is __clearly a regression__.

**Comment by smarterclayton** [comment] 2017-01-23 17:16
A couple of things I can think of:

1. The client-go code we updated contains a fix from earlier in the week - the update exposes it (so the problem was before that, but we weren't using it yet)
2. We changed error handling paths somehow, so errors that were being ignored suddenly started being handled, which resulted in controllers doing more work than before (i'm thinking about https://github.com/kubernetes/kubernetes/pull/39831 or https://github.com/kubernetes/kubernetes/pull/39886, both of which might have been masking an error).

**Comment by wojtek-t** [comment] 2017-01-23 19:00
@smarterclayton - what was the bug that was fixed? Do you have a link?

Regarding 2 - I don't think it's the case in our tests, as there aren't many errors in them. But hopefully I will have more time tomorrow to investigate it deeper.

**Comment by smarterclayton** [comment] 2017-01-23 19:21
1 was generic - i.e. the client-go bump triggered an earlier issue, and it's possible that is the real problem.

**Comment by smarterclayton** [comment] 2017-01-23 19:22
I *think* that without #39831 you wouldn't get timeout errors properly on anything that depended on Stream(), which is logs.  But if you're not depending on that we can eliminate it.

**Comment by smarterclayton** [comment] 2017-01-23 19:40
Do we have any other cluster data about any rates of object creation / updates?

**Comment by wojtek-t** [comment] 2017-01-24 07:42
> Do we have any other cluster data about any rates of object creation / updates?

I'm afraid I don't understand your question. 
In kubemark-500 in the test that we are facing problems we are starting 15.000 pods. The problematic scalings are happening when all those pods are already in the system.

**Comment by wojtek-t** [comment] 2017-01-24 09:42
I've run some tests locally. And few thins I discover was:
- when i'm trying to run kubemark on my own cluster, NPD simply doesn't work at all: https://github.com/kubernetes/kubernetes/issues/40350

- when I disable NPD, everything seems to work fine for me.

That means that https://github.com/kubernetes/kubernetes/pull/40170 doesn't seem to cause problems.

As a result, I'm going to try reverting #39033 and we will see if that helps (unfortunately even with this PR locally reverted NPD still doesn't work for me locally). But we will see.

**Comment by wojtek-t** [comment] 2017-01-24 12:48
I did one more experiment which was running the same test in a real cluster instead of kubemark. And it worked:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-enormous-cluster/1

So it seems to be kubemark-related.

We will see if reverting that PR will help pretty soon.

**Comment by wojtek-t** [comment] 2017-01-24 13:18
It seems that reverting this PR helped. However, I'm going to leave this bug open for some more time, to have more clear signal.

**Comment by shyamjvs** [comment] 2017-01-24 14:33
So I checked how much time various steps in the e2e suite take and it turns out that the main difference is in the RC scaling attempts in the load test:
- It takes around 1m45s after reverting
- It takes around 4m30s before reverting
There are 2 such scaling attempts and hence difference because of this is already 2 * (4m30s - 1m45s) = 5m30s.
Also, it takes around 1 min less for deleting namespaces at the end of the load test after reverting.

Overall, it takes around 8m less for the e2e suite to finish, after reverting. This seems surprising as the e2e test logic has been untouched by the PR.

**Comment by wojtek-t** [comment] 2017-01-25 09:36
After reverting the PR, we're back to being reliably green. So I'm closing this issue.

@shyamjvs will investigate the problems with his PR and will try to fix it and then resubmit for review.

**Comment by gmarek** [comment] 2017-01-25 09:49
I think we should keep this open with different title, so we'll have all investigation in one place.

**Comment by shyamjvs** [comment] 2017-02-16 10:01
Closing this issue as the regressions related to kubemark refactoring have been resolved after the revert.
Followed it up by 3 smaller refactor PRs and the tests have been green for quite some runs after the last one got merged.

**Comment by shyamjvs** [comment] 2017-02-16 10:02
Ref https://github.com/kubernetes/kubernetes/issues/38967

**Closed by shyamjvs** 2017-02-16 10:01 UTC
Labels: kind/flake, priority/important-longterm, sig/scalability
