### ISSUE TITLE
node describe shows incorrect kube-proxy version

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#54324] opened 2017-10-20 21:35 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli

**What happened**:

kube-proxy is on v1.8.1 but `describe node` shows the prior version of kube-proxy v1.7.1 instead of v1.8.1

```
System Info:
 Machine ID:                 e2fd926b05f24e6eb442f96cced03149
 System UUID:                0004FB00-0006-0000-A625-5CAF68F0A898
 Boot ID:                    58f00e28-abc9-4765-a565-5292816083e5
 Kernel Version:             4.1.12-103.3.8.el7uek.x86_64
 OS Image:                   Oracle Linux Server 7.4
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://1.12.6
 Kubelet Version:            v1.7.1
 Kube-Proxy Version:         v1.7.1
```

```
Containers:
  kube-proxy:
    Container ID:  docker://b6d6515b7eab5679a535b97a399bbd591a76173243315d17128ef9b180c0a329
    Image:         gcr.io/google_containers/kube-proxy-amd64:v1.8.1
    Image ID:      docker-pullable://gcr.io/google_containers/kube-proxy-amd64@sha256:58fd496116bf3d2790279f9c44040bdfa71791aba7a7a1b5ca35025b5a032b9f
```

**What you expected to happen**:

I expect the latest version of kube-proxy to be shown in `describe node`

**How to reproduce it (as minimally and precisely as possible)**:

Run a kubelet that's a prior version to kube-proxy (haven't tested if it breaks if the kubelet is newer than kube-proxy)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jhorwit2** [comment] 2017-10-20 21:38
The reason for this is that the kubelet assumes the version is the same. [code](https://github.com/kubernetes/kubernetes/blob/4b0511dc8cc6d4fb4775e00198757d50b35856a6/pkg/kubelet/kubelet_node_status.go#L663)

**Comment by liggitt** [comment] 2017-10-21 01:13
dupe of https://github.com/kubernetes/kubernetes/issues/48811

**Closed by liggitt** 2017-10-21 01:13 UTC
Labels: kind/bug, sig/cli

**Comment by liggitt** [comment] 2017-10-21 01:15
fwiw, sentiment seems to be that reporting kube-proxy version in kubelet status is not appropriate and should be deprecated... see https://github.com/kubernetes/kubernetes/pull/48988#issuecomment-320714445
