### ISSUE TITLE
e2e flake: "Kubernetes e2e suite.[k8s.io] Kubectl client [k8s.io] Simple pod should support exec"

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#23546] opened 2016-03-28 18:40 UTC
kubernetes-pull-build-test-e2e-gce/33760 for PR #23454 

This might a duplicate of #22671, but the failure wasn't entirely the same.

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:227
Expected error:
    <*errors.errorString | 0xc20851ad50>: {
        s: "Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.243 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config exec --namespace=e2e-tests-kubectl-4sutt -i nginx bash] []  0xc20846b088 hi\n  [] <nil> 0xc208925b20 exit status 2 <nil> true [0xc20846b088 0xc20846b0d0 0xc20846b0f0] [0xc20846b0d0 0xc20846b0f0] [0xc20846b0c8 0xc20846b0e8] [0x972bb0 0x972bb0] 0xc208920d20}:\nCommand stdout:\nhi\n\nstderr:\n\nerror:\nexit status 2\n",
    }
    Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.243 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config exec --namespace=e2e-tests-kubectl-4sutt -i nginx bash] []  0xc20846b088 hi
      [] <nil> 0xc208925b20 exit status 2 <nil> true [0xc20846b088 0xc20846b0d0 0xc20846b0f0] [0xc20846b0d0 0xc20846b0f0] [0xc20846b0c8 0xc20846b0e8] [0x972bb0 0x972bb0] 0xc208920d20}:
    Command stdout:
    hi
    
    stderr:
    
    error:
    exit status 2
    
not to have occurred
```

**Comment by ncdc** [comment] 2016-03-28 19:13
This is a dupe of #23321

**Closed by ncdc** 2016-03-28 19:13 UTC
