### ISSUE TITLE
Scheduler never discount the deleted pods on a node when calculating max-pods

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#22398] opened 2016-03-03 00:22 UTC
While debugging another issue, I found my pods pending forever:

```
$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                                  READY     STATUS    RESTARTS   AGE
default       hostnames-1963821055-ob408                            0/1       Pending   0          10m
default       nginx                                                 1/1       Running   0          22h
kube-system   elasticsearch-logging-v1-9k90q                        1/1       Running   1          1d
kube-system   elasticsearch-logging-v1-j08ky                        1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-fo98   1/1       Running   2          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-rg3g   1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-tikv   1/1       Running   0          1d
kube-system   heapster-v14-cfenb                                    2/2       Running   4          1d
kube-system   kibana-logging-v1-xz7hy                               1/1       Running   2          1d
kube-system   kube-dns-v10-qrv2j                                    4/4       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-fo98              1/1       Running   1          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-rg3g              1/1       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-tikv              1/1       Running   0          1d
kube-system   kubernetes-dashboard-v0.1.0-9rabh                     1/1       Running   0          1d
kube-system   l7-lb-controller-v0.5.2-1k4co                         2/2       Running   0          1d
kube-system   monitoring-influxdb-grafana-v3-op3cp                  2/2       Running   0          1d
```

Checking the reason on why pending, it looks like all hit max-pods limit here

```
$ cluster/kubectl.sh describe  pods hostnames-1963821055-ob408
Name:		hostnames-1963821055-ob408
Namespace:	default
Node:		/
Labels:		app=hostnames,pod-template-hash=1963821055
Status:		Pending
IP:		
Controllers:	ReplicaSet/hostnames-1963821055
Containers:
  hostnames:
    Image:	kubernetes/serve_hostname
    QoS Tier:
      memory:	BestEffort
      cpu:	Burstable
    Requests:
      cpu:	100m
    Environment Variables:
Volumes:
  default-token-b3uhy:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-b3uhy
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  4m		4m		1	{default-scheduler }			Warning		FailedScheduling	pod (hostnames-1963821055-ob408) failed to fit in any node
fit failure on node (e2e-test-dawnchen-minion-tikv): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-rg3g): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-fo98): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110

  4m	21s	14	{default-scheduler }		Warning	FailedScheduling	pod (hostnames-1963821055-ob408) failed to fit in any node
fit failure on node (e2e-test-dawnchen-minion-rg3g): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-fo98): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-tikv): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110

  3m	5s	5	{default-scheduler }		Warning	FailedScheduling	pod (hostnames-1963821055-ob408) failed to fit in any node
fit failure on node (e2e-test-dawnchen-minion-fo98): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-tikv): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
fit failure on node (e2e-test-dawnchen-minion-rg3g): Node didn't have enough resource: PodCount, requested: 1, used: 596, capacity: 110
```

But all my nodes are pretty empty except kube-system pods. I double checked the deleted pods, none of them are showed:

```
$ cluster/kubectl.sh get pods --all-namespaces --show-all
NAMESPACE     NAME                                                  READY     STATUS    RESTARTS   AGE
default       hostnames-1963821055-ob408                            0/1       Pending   0          15m
default       nginx                                                 1/1       Running   0          22h
kube-system   elasticsearch-logging-v1-9k90q                        1/1       Running   1          1d
kube-system   elasticsearch-logging-v1-j08ky                        1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-fo98   1/1       Running   2          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-rg3g   1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-tikv   1/1       Running   0          1d
kube-system   heapster-v14-cfenb                                    2/2       Running   4          1d
kube-system   kibana-logging-v1-xz7hy                               1/1       Running   2          1d
kube-system   kube-dns-v10-qrv2j                                    4/4       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-fo98              1/1       Running   1          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-rg3g              1/1       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-tikv              1/1       Running   0          1d
kube-system   kubernetes-dashboard-v0.1.0-9rabh                     1/1       Running   0          1d
kube-system   l7-lb-controller-v0.5.2-1k4co                         2/2       Running   0          1d
kube-system   monitoring-influxdb-grafana-v3-op3cp                  2/2       Running   0          1d
```

At this stage, I believe it must be scheduler issue which caches a wrong number. So I restarted my scheduler, and my pending pods are scheduled immediately:

```
$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                                  READY     STATUS    RESTARTS   AGE
default       hostnames-1963821055-ob408                            1/1       Running   0          23m
default       nginx                                                 1/1       Running   0          22h
kube-system   elasticsearch-logging-v1-9k90q                        1/1       Running   1          1d
kube-system   elasticsearch-logging-v1-j08ky                        1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-fo98   1/1       Running   2          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-rg3g   1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-tikv   1/1       Running   0          1d
kube-system   heapster-v14-cfenb                                    2/2       Running   4          1d
kube-system   kibana-logging-v1-xz7hy                               1/1       Running   2          1d
kube-system   kube-dns-v10-qrv2j                                    4/4       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-fo98              1/1       Running   1          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-rg3g              1/1       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-tikv              1/1       Running   0          1d
kube-system   kubernetes-dashboard-v0.1.0-9rabh                     1/1       Running   0          1d
kube-system   l7-lb-controller-v0.5.2-1k4co                         2/2       Running   0          1d
kube-system   monitoring-influxdb-grafana-v3-op3cp                  2/2       Running   0          1d
```

cc/ @kubernetes/goog-control-plane

**Comment by dchen1107** [comment] 2016-03-03 00:23
cc/ @yujuhong

**Comment by dchen1107** [comment] 2016-03-03 00:24
@davidopp @gmarek This issue might also cause some flakiness with SchedulerPrediction.

**Comment by yujuhong** [comment] 2016-03-03 00:36
When did you build your cluster? #20669 (which adds the scheduler cache) was just reverted this morning (ref: #22189).

**Comment by mikedanese** [comment] 2016-03-03 00:36
cc @hongchaodeng

**Comment by davidopp** [comment] 2016-03-03 00:38
Sorry Mike, didn't mean to unassign you - looks like a race condition in the UI.

**Comment by davidopp** [comment] 2016-03-03 00:39
(I mean, the reason I didn't see you had assigned this to yourself was due to a race condition. Not that this bug is due to a race condition. :) )

**Comment by yujuhong** [comment] 2016-03-03 00:42
> cc @hongchaodeng @wojtek-t since this looks like it might be an issue with the schedulercache

The PR was already reverted (#22189)

**Comment by dchen1107** [comment] 2016-03-03 00:44
@yujuhong I built my cluster yesterday afternoon. So it is possible the issue is resolved by reverting that bad pr. @mikedanese you can quickly verify it by reproduce that daemonset issue which you are working on. :-)

**Comment by mikedanese** [comment] 2016-03-03 00:55
I will verify, https://github.com/kubernetes/kubernetes/pull/20857 is not reverted

**Comment by hongchaodeng** [comment] 2016-03-03 01:13
Thanks @mikedanese for pointing it out.

We already found the root problem of e2e test failure caused in #20669 and are trying to fix it in another PR. In the meantime, I don't think #20857 is related since it's not actually changing the logic. And it's merged 3 weeks ago not causing failures.

**Comment by mikedanese** [comment] 2016-03-03 01:20
@hongchaodeng Do you thinkt the cause of the failure would explain this? Or does this look like something else?

**Comment by hongchaodeng** [comment] 2016-03-03 02:09
Yes. Once we fix it this will be likely fixed. They are the same symptom in my mind

**Comment by wojtek-t** [comment] 2016-03-03 06:59
#20857 shouldn't be a problem in my opinion

**Comment by mikedanese** [comment] 2016-03-03 22:43
I was not able to reproduce on head

**Closed by mikedanese** 2016-03-03 22:43 UTC
Labels: component/scheduler, kind/bug, priority/P0, team/control-plane
