### ISSUE TITLE
EBS volumes remains in 'attaching' state when attached with a previously used device name

### ISSUE THREAD

**Issue by koendc** [kubernetes/kubernetes#31891] opened 2016-09-01 16:07 UTC
**Kubernetes version**:

`Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+coreos.0", GitCommit:"f6f0055b8e503cbe5fb7b6f1a2ee37d0f160c1cd", GitTreeState:"clean", BuildDate:"2016-08-29T17:01:01Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS**: CoreOS
- **Kernel**: 4.6.3-coreos
- **Install tools**: kube-aws

**What happened**:

Some EBS volumes remain in the attachment state "attaching". These EBS volumes are attached on a device name that was used for a previous attachment.
Looking on the worker node, the volume is not visible in the device list (eg by running `lsblk`). After a reboot of the node the volume is attached successfully. The attachment state then is "attached".

**Expected behavior**:

The EBS volumes are attached correctly.

**How to reproduce it**:
1. Spin up a worker node
2. Create 20 EBS volumes
3. Create 19 pods with volumes attached on this node
4. Remove the first pod
5. Create a 20th pod with the 20th volume attached

Now the 20th volume remains in the attachment state 'attaching'.

20 is not necessary the lower bound but the issue did not appear with 3 volumes.

**Additional information**:

It seems related to the reuse of device names. Only when the device name /dev/xvdXX was already used for a previous attachment, the volume remains in the attachment state "attaching".
When using a lower number of volumes, it is still possible to detach-attach. Only when attaching a considerable amount of volumes (about 20), the issue appears.

According to [this AWS support article](https://aws.amazon.com/premiumsupport/knowledge-center/ebs-stuck-attaching/) it is possible that the device name was not released by the block device driver after detaching.

**Comment by thomaso-mirodin** [comment] 2016-10-23 21:23
Note, I'm still seeing this on 1.3.8 with both PVs and non-PV EBS volumes

**Comment by guoshimin** [comment] 2016-11-02 04:04
@thomaso-mirodin's co-worker here.

It seems sometimes the EBS volume isn't detached cleanly. When it happens, the following command, run from the node, shows errors:
```
$ sudo xenstore ls error/device/vbd
268449280 = ""
 error = "16 Device in use; refusing to close"
268448768 = ""
 error = "16 Device in use; refusing to close"
268449024 = ""
 error = "16 Device in use; refusing to close"
```
Normally this command should say
```
xenstore: xs_directory (error/device/vbd): No such file or directory
```

**Comment by offlinehacker** [comment] 2016-11-09 09:35
Do you think, is this issue then bound to a speciffic kernel version?

**Comment by sachincab** [comment] 2016-11-18 11:22
We seen this issue when delete pod and create again then it unable to attached volume sometimes as it tried to use same device name which has been used on node by other EBS volume attached.

In our case, we have two EBS volumes created through PVC and three EBS volumes created outside PVC.
We have two nodes where containers gets deployed where noticed this issue of same device name used on node to attach EBS volume.

Kubernetes version: 1.4.6
CoreOS: CoreOS 1185.3.0
Kernel: 4.7.3-coreos-r2

Please let me know if you need any more information on this.

**Comment by yash1425** [comment] 2016-11-29 10:27
Facing exactly the same issue.Not sure if it is an issue from AWS or kubernetes side. @sachincab  @jingxu97

**Comment by hanikesn** [comment] 2016-11-29 10:56
After uprading to 1.4.6 from 1.4.1 we also got more issues with volumes not attaching correctly.

**Comment by hanikesn** [comment] 2016-11-29 21:47
Apparently the new VolumeController easily gets confused when manually force detaching a stuck volume. As it will not retry attaching it any time soon. Additionally there's a long 2 min timeout on the kubelet side to try remounting the volume.

**Comment by jingxu97** [comment] 2016-11-29 22:58
@hanikesn Could you please share your master controller log so that I can help check the issue? Thanks

**Comment by leosunmo** [comment] 2016-12-14 03:51
I am facing the same issue using Ubuntu 16.04.1 with K8s version 1.4.6. 
I logged a support ticket with AWS and was informed that it's because we're not properly un-mounting the volume before issuing the detach call to AWS. Here's some snippets from the correspondence:
 

> I'm sorry you're continuing to have this issue. I see that your volume vol-0b450a070f528e848 is stuck attaching to /dev/xvdba. I checked the previous two volumes that were attached on /dev/xvdba, vol-044ef3d048ca995c3 and vol-05c1c4be3d2ffd357, and I can confirm that neither was force-deatched. However, it's not necessary to use force detach for this to occur. The issue occurs when a volume is detached while still mounted in the OS and stays in use for a period of time after the detach command is sent. It doesn't matter whether a normal detach or force-detach is used.
> 
> The last volume attached on /dev/xvdba was vol-05c1c4be3d2ffd357. This volume was detached at 2016-11-30T02:28:11 UTC and actually removed at 2016-11-30T02:30:21 UTC. The volume can't be fully removed until it's no longer in use by the OS, so that it was held for more than 2 minutes is pretty good evidence that it was still in use after being detached.

I asked if there was ANYTHING I could do in Ubuntu to fix the issue once it's in 'stuck' state, but got this response:

> Unfortunately, the issue is on the underlying host side and not an Ubuntu problem. Restarting your instance causes the relevant information on our side to reset, so that makes the device available for use again. You can also achieve the same result by stopping the instance and starting it again, which moves your instance to a new underlying host. Without a restart, you can work around the issue by choosing a different device, or avoid the problem by making sure the volume is fully unmounted and no longer in use before detaching, but that's about it I'm afraid. I am sorry for any inconvenience.

Also:

> We are working on a solution to prevent this from happening in the future, but I don't have specific information about when that fix will be available. In the meantime, you can continue to work around the problem by choosing a different mount device or restarting the instance.

But I'd rather not wait for AWS to make changes in Xen. How does K8s handle the un-mounting when the pod is deleted/rescheduled? Is there already a fix for this? I've searched around but I might have missed it.

I also ran the xenstore-ls command and got this (Thanks a ton to @guoshimin for that command, very helpful in troubleshooting!):
```
root@kube-node# xenstore-ls error/device/vbd
268448768 = ""
 error = "16 Device in use; refusing to close"
```


We're running in to this issue a lot, using both Deployments and Petsets (persistentVolumeClaims or hard-coded EBS volumes, doesn't matter).

**Comment by guoshimin** [comment] 2016-12-14 05:31
We had at least one case where this happened after someone in our organization force detached a volume from under Kubernetes. I'm beginning to suspect all the cases we had before were due to force detaches.

**Comment by chrislovecnm** [comment] 2016-12-14 17:56
@saad-ali / @justinsb can we get this assigned to someone in CoreOS and someone in @kubernetes/sig-aws ?

**Comment by chrislovecnm** [comment] 2016-12-14 17:56
Guys is this a duplicate https://github.com/kubernetes/kubernetes/issues/31891

**Comment by jingxu97** [comment] 2016-12-14 18:09
@leosumo, in k8s, when a pod is deleted, kubelet's volume controller will try to unmount first and then detach after unmount successfully. In case that  there are still some mount referencing the same device, unmount may not be able to issued. The volume controller at master will timeout after a period of time (set to 6 mins), and then issue detach. 

So it is possible in certain cases that the volume is detached while it is still mounted which we are try to avoid as much as possible. 

If you still have some logs around the time that issue occurred, could you please share with me? Thanks!

**Comment by gnufied** [comment] 2016-12-15 01:59
@leosunmo how are these kubernetes clusters configured btw? Are they running more than one controller-managers or etcd is clustered?

**Comment by leosunmo** [comment] 2016-12-15 03:50
Thanks for the prompt reply @jingxu97 . Unfortunately I don't have any logs around the time that a disk was unmounted, only when it tried unsuccessfully to mount my new disk. Here's logs from the first occurrence of this new ELB volume:

**Comment by leosunmo** [comment] 2016-12-15 04:02
Thanks for the prompt reply @jingxu97 . Unfortunately I don't have any logs around the time that a disk was unmounted, only when it tried unsuccessfully to mount my new disk. Here's logs from the first occurrence of this new ELB volume. Decided to upload a textfile as it got quite long.


[k8sdiskissue.txt](https://github.com/kubernetes/kubernetes/files/653743/k8sdiskissue.txt)

I removed a bunch of repeating flanneld messages as well as docker messages. Also had a bunch of successful messages pertaining to secret tokens and similar that I removed, did not seem relevant.

@gnufied 3 master nodes all running an api-server, controller-manager, scheduler, and clustered etcd.

**Comment by jsafrane** [comment] 2016-12-15 12:26
Reading https://aws.amazon.com/premiumsupport/knowledge-center/ebs-stuck-attaching/, the solution seems to be not to reuse device names. Currently, Kubernetes tries to find the lowest device name (in lexicographical order), which might have been just released. Instead, Kubernetes should find the next after the last attached device, say 'xvdbz' after 'xvdby'.

**Comment by jingxu97** [comment] 2016-12-15 19:28
@leosunmo, from the log I think it might hit aws path issue. the fix #36840 is in release 1.4.7. Could you please give it a try and let us know if you still have issue? Thanks!

**Comment by whereisaaron** [comment] 2016-12-15 23:41
If you have enough churn of pods (such as CI/CD) with EBS volumes you'll eventually see this. You can get this with just a small number of pods and volumes, e.g. I can get this with e.g. three pods on two worker nodes and two Pod-attached EBS volumes. You get it less (or possibly not at all) if you fully delete a deployment first. Using 'apply' to update running deployments is the best trigger in my experience. We got this with 1.3.x, and to date, I've seen reports up to at least 1.4.6.

As @leosunmo quoted AWS above, a force detach is definitely not required to trigger it, though it is a short-cut way to trigger it. Normally users end up force-detaching a volume after as @jingxu97 describes, k8s tells AWS to detach a still mounted device (or at least still in use as far as Xen is concerned). The next attach on that device name frequently or always gets stuck. You really can't to this on AWS and expect to reliably reuse that device name before the next reboot. AWS's advice, and our practice is always to reboot an instance after a bad or forced detach. Maybe they'll have a fix for the for Xen one day, but not so far, and it's been an issue for many years.

If it doesn't suit to reboot a node, the way we work around it is to deliberately let a Pod start-up get stuck on attaching a dummy EBS volume, then while it is stuck trying, deploy the Pod we wanted to, so that it gets attached on a different and untainted device name. This works, but it is painfully clumsy.

As @jsafrane suggests, it would significantly mitigate (but not eliminate) the problem if ks8 would round-robin the available dev names rather that always trying to reuse the same name. Once that lowest name has had a tainted unmount, the node is going to keep trying to use that device name and failing every time.

As better workaround for this AWS issue would be when, as @jingxu97 explained, a k8s unmount attempt expires after 6 minutes, and k8s tells AWS to detach the volume anyway. After that, the device path used for that mount should be recorded by k8s as tainted, and not reused by that node until that node is rebooted.

I don't completely understand how #36840 in release 1.4.7 would fix this issue? Was the mount -> volume name mapping problem causing the failed unmounts that lead to detaching mounted volumes? If so, I can see how this would mitigate the unmount problem. However that is not a fix for the 'unmount-expired, detach anyway' state, rather it would happen less often. If that situation is ever reached, that device name is tainted and probably will not work again until a reboot, k8s needs to recognize that.

**Comment by justinsb** [comment] 2016-12-16 00:41
I don't think we should close this until we've validated it.  Reopening.

**Comment by pajel** [comment] 2016-12-16 01:00
I am working on the same cluster as @leosunmo, upgraded to 1.4.7 and the issue is not fixed. Exactly the same symptoms - EBS stuck in attaching, trying to mount to /dev/xvdbb which probably hasn't been unmounted properly.
#38818 looks promising, we'll re-try once it's released.

**Comment by jingxu97** [comment] 2016-12-16 01:37
Hi @pajel, thanks for reporting this. I am wondering when you mentioned  "trying to mount to /dev/xvdbb which probably hasn't been unmounted properly." what do you mean by "hasn't been unmounted properly"? 
In the kube-controller-manager log, could you see whether DetachVolume (the volume that used /dev/xvdbb device path) is finished successfully? Just want to make sure the stuck in attaching state is not caused by other reasons.

**Comment by jingxu97** [comment] 2016-12-16 22:05
@whereisaaron thank you very much for your input. For k8s side, one of the most important policy is to avoid to detach a volume that is still mounted. In normal cases, device should be unmounted by kubelet first and then controller gets the signal that volume is safe to detach and issues detach operation. 

If the controller cannot get the signal in 6 minutes, it will go ahead to issue detach anyway. The reason we have this policy is to avoid volume is stuck in waiting for the safe to detach signal forever (e.g, kubelet is down). We are also discussing to increase the timeout to make (possibly) safer to detach. But there is still a chance of it.

Earlier we have fixed some bugs/issues related to kubelet fails to unmount as desired and controller decides to detach after timeout. I want to make sure that there is no other such issue or bugs for this. If in your cluster, you happen to see the issue occurs, could you please share us some logs so that we can double check?

**Comment by gnufied** [comment] 2016-12-17 01:01
FWIW I verified that @jsafrane 's fix indeed fixes the problem. Here is steps to reproduce this bug:

1. Wrote a script that creates pvc and pods that use those pvcs. Script is here - https://gist.github.com/gnufied/4b894d4b8702081076dfd834157d9fa9 it will basically keep creating pods until cluster capacity is exhausted (so don't do this in your prod. cluster). 
2. Usually last pod will be in pending state because of lack of CPU capacity.
3. At that point, I found volume-id of first pvc and force detached from Amazon Console. 
4. Delete a pod to free up capacity(I usually delete pod that was created just before pod that got stuck in hung state), but do not delete first pod that uses the PVC which I just force detached. Leave that pod alone.
5. At that point, the newest pod should start building and without this PATCH it will get hung in "ContainerCreating" state because pv gets assigned same device id as force detached volume. With PATCH - the newest pod gets up and running.

Admittedly it is bit synthetic reproduction but it does seem to work.

**Comment by justinsb** [comment] 2016-12-17 02:32
@gnufied just to confirm: you ran the test before the patch and it failed, and you ran it after the patch and it passed?

That's obviously good if so.  However force-detaching a volume is going to break things.  The original issue didn't involve force-detaching a volume AFAICT.

Also, I opened https://github.com/kubernetes/kubernetes/issues/38915 to capture the technique that @guoshimin had mentioned above.  I wasn't aware of the use of xenstore for diagnostics - we should probably capture those logs or use them in the node problem detector.

**Comment by gnufied** [comment] 2016-12-19 14:30
@justinsb yeah pretty much.

**Comment by guoshimin** [comment] 2016-12-22 21:13
I can now reproduce the problem deterministically with v1.3.8:
- create a deployment with replicas=1 with an EBS volume attached on node X
- Observe that node X reports the volume in VolumesInUse.
- go to node X and kill docker, and keep it down
- restart kubelet on node X
- Observe that node X stops reporting the volume in VolumesInUse, and also that it reports unready status.
- After some timeout the node controller mark all pods on node X for deletion
- a new pod is created but will stay in pending because the volume is still attached to the old node
- After the grace period, node controller force deletes all pods on node X
- Node controller determines that the volume is safe to detach from node X because node X doesn't claim it in VolumesInUse
- Node controller calls AWS to detach the volume. The volume will stay busy because it's still mounted
- Now bring back docker on node X. kubelet sees that the pod is deleted, so it unmounts the volume.
- The detach now completes.

Now if you run `sudo xenstore ls error` on node X, you will see an error. Any future attempt to attach a volume to node X at the same mountpoint will fail.

The key is that the kubelet falsely reports that no volume is in use when it first starts and the docker runtime is unavailable. This repro case doesn't work with v1.4.7 because kubelet dies very quickly if the docker runtime is unavailable, but I don't know if there are other cases where it will false reports empty VolumesInUse.

**Comment by koendc** [comment] 2017-02-03 10:27
@guoshimin I tried the command you provided on a node where it is no longer possible to attach volumes.
This is the output I get:

`xenstore-ls error`
`xenstore-ls: xs_open: No such file or directory`

Is this expected or is there anything else that needs to happen before the xenstore commands can be used?

**Comment by jsravn** [comment] 2017-03-06 10:30
To add another view, I've only seen this problem when people force detach volumes from the instance (kernel view of the device gets corrupted, and AWS is unable to attach volume with that device name again). Rebooting the node fixes it. As long as the device is unmounted beforehand, I've had 0 problems re-attaching (on ubuntu 16.04 and centos 7).

**Comment by whereisaaron** [comment] 2017-03-06 16:55
This appears entirely resolved by 1.5.1. In the same environment we don't see this at all any more.

The was a legitimate major issue with 1.3.x, it happened all the time with no one doing a (manual) force detach. Various device naming bugs would end up with k8s itself incorrectly doing a force detach and screwing things up. Also, the fast re-use of the same device name (rather than cycling through the available names) led to AWS/Xen screwing up the mounts.

I can't speak for 1.4.x but it sounds like various 1.4.x patches chipped away at the problem, so maybe the later 1.4.x versions are good too.

**Comment by jingxu97** [comment] 2017-03-06 18:47
I believe this issue is solved by PR #38818, which is also cherrypicked to 1.4. This PR avoid to immediately reuse the device names which are just released. So close this issue now. Please reopen it if anyone still experience it. Thanks!

**Closed by jingxu97** 2017-03-06 18:47 UTC
Labels: area/platform/aws, sig/storage, team/cluster (deprecated - do not use)

**Comment by geekofalltrades** [comment] 2017-09-13 17:53
Hi all,

We just hit this issue in Kubernetes 1.6.0.

We have three EC2 instances in a development Kubernetes cluster on which our developers are constantly setting up and tearing down container workloads that have PersistentVolumes associated. PostgreSQL databases with a pv; three-member etcd clusters with three pvs; etc. The instances have been up for about five months, and according to AWS support (who I also contacted about the issue) one of them has had about 750 volume attach-detach operations in that time.

It's gotten to the point where nothing with a PersistentVolume associated can be scheduled to these instances; volumes gets stuck, 100% of the time.

The workaround in #38818 is no longer sufficing for us.

Did anyone ever determine the root cause of this issue? Why is kubelet consistently taking >6min to unmount devices, causing the underlying Xen issue?

To unblock us, I've stood up three new nodes and cordoned the existing ones. I can keep the three existing ones around for a while to assist in troubleshooting, if needed, but I eventually want to shut them down.

**Comment by gnufied** [comment] 2017-09-13 18:16
Did you ever force detach a volume from those instances and did not reboot?

What does xenstore-ls report?

**Comment by geekofalltrades** [comment] 2017-09-13 22:22
The only volumes I've force-detached from these instances are the ones that got stuck in attaching.

Here's xenstore-ls on one of the three:

```
$ sudo xenstore-ls error/device
vbd = ""
 268449280 = ""
  error = "12 xenbus_dev_probe on device/vbd/268449280"
 268450048 = ""
  error = "12 xenbus_dev_probe on device/vbd/268450048"
 268458240 = ""
  error = "16 Device in use; refusing to close"
 268452864 = ""
  error = "12 xenbus_dev_probe on device/vbd/268452864"
 268453120 = ""
  error = "12 xenbus_dev_probe on device/vbd/268453120"
 268454144 = ""
  error = "12 xenbus_dev_probe on device/vbd/268454144"
 268454400 = ""
  error = "12 xenbus_dev_probe on device/vbd/268454400"
 268456704 = ""
  error = "12 xenbus_dev_probe on device/vbd/268456704"
 268457728 = ""
  error = "12 xenbus_dev_probe on device/vbd/268457728"
 268451840 = ""
  error = "12 xenbus_dev_probe on device/vbd/268451840"
 268453888 = ""
  error = "12 xenbus_dev_probe on device/vbd/268453888"
 268455168 = ""
  error = "12 xenbus_dev_probe on device/vbd/268455168"
 268457216 = ""
  error = "12 xenbus_dev_probe on device/vbd/268457216"
 268457984 = ""
  error = "12 xenbus_dev_probe on device/vbd/268457984"
 268460800 = ""
  error = "12 xenbus_dev_probe on device/vbd/268460800"
 268450560 = ""
  error = "12 xenbus_dev_probe on device/vbd/268450560"
 268451072 = ""
  error = "12 xenbus_dev_probe on device/vbd/268451072"
 51824 = ""
  error = "12 xenbus_dev_probe on device/vbd/51824"
 268451328 = ""
  error = "12 xenbus_dev_probe on device/vbd/268451328"
```

**Comment by gnufied** [comment] 2017-09-13 22:29
And did you reboot the instances after that?

**Comment by hanikesn** [comment] 2017-09-13 22:32
Never ever force detach an EBS volume. When stuff got stuck we always manually connected to the machine and umounted the volume so it could properly be detached. When you force detach a volume always reboot the node.

**Comment by geekofalltrades** [comment] 2017-09-13 23:28
@gnufied, @hanikesn 
These instances have never been rebooted. Doing so would disrupt certain "pet" pods that are running on them.

Again, the only volumes I ever force-detached were volumes that were stuck in attaching _recently_ - volumes that were already affected by this bug. AFAIK they were never attached in the first place in that case, so there would have been nothing to see from the OS side, and force-detaching them is the only way to get rid of them.

**Comment by whereisaaron** [comment] 2017-09-20 01:06
@geekofalltrades I dealt with this back in 1.3.x. Once you force-detach _any_ volume in AWS, that instance is in an inconsistent state. Any mounting after that will almost always not work. Xen/AWS will just keep having problems getting stuck with mounts/unmounts.

You can force detach a  volume to get access to mount it on another instance. But the instance you force-detached it from _must_ be rebooted to get it back to a consistent state.

**Comment by geekofalltrades** [comment] 2017-09-20 22:18
I may not be communicating this clearly.

* We have several AWS instances in a Kubernetes cluster.
* They have high volume churn. They've been up for 5 months and have each had 700+ volume-attach/-detach operations.
* Now, any time Kubernetes tries to attach an EBS volume to one of the instances, it gets stuck in attaching state.

**At no point during the normal lifecycle of these EC2 instances did we force-detach volumes from the instances. I only began force-detaching volumes after this bug had already struck.**

Me force-detaching volumes from these instances _did not trigger this issue_: it is part of _my response to_ the issue. This issue causes the volume to get stuck in attaching. At that point, the only way to get the volume unstuck is to force-detach it.

Since we did not force-detach volumes from these instances before they started hitting this issue, it seems to me that there is some legitimate Kubernetes issue here that caused these volumes to start getting stuck in attaching in the first place.

**Comment by gnufied** [comment] 2017-09-21 01:07
@geekofalltrades I feel your pain. I just wanted to make sure that problem wasn't caused by force detaching volumes. 

I know and agree that, in certain cases - a volume can be stuck in attaching state even though no volume was force detached from instance. I have seen it myself. But more often than not, when I have raised support request with Amazon, it turned out to be a "impaired volume" or something broke on their end. 


Having said that, may be we can do few things to lessen the pain but first we will have to know root cause of the problem (which we don't - I have some ideas but nothing conclusive).  I have few questions:

1. Did you try asking Amazon why is your volume stuck in 'attaching' state? Can you double check if volume is being attached to a device that is already taken (such as `/dev/xvdba`) on the node. 
2.  Can you get controller-manager logs grepped by volume-id for which volume was stuck.
3. Also if possible cloudtrail logs.

**Comment by geekofalltrades** [comment] 2017-09-27 18:57
I did open an AWS case to discuss the volumes. They verified from their side that it's because the device name was conflicting:

> Consistently, I could also see that volume attachment fails due to discrepancy in block device name mapping and returns errors similar to: 
	'attach-failed'- 'The device "xvdbf" is already defined'.
	'attach-failed'- 'The device "xvdbk" is already defined'. and so on.
There have been approximately 750 volume attach-detach done to this instance in past 5 months; This have resulted in situation that:
	A volume vol-005f7d64ad5cf4be4 was attached to instance as /dev/xvdbf. It was detached on 2017-09-05 18:16 UTC. Later, you tried to attach a volume vol-0d0d07808bd738bea with same device name /dev/xvdbf which conflicted depending upon the block device driver functionality.

Unfortunately, I don't seem to have any kube-controller-manager logs containing the volume ID of one of the two volumes that I know were stuck.

**Comment by gnufied** [comment] 2017-09-27 21:08
Also which version of k8s were you running? So just to be clear - k8s attempted attaching volume to `/dev/xvdbf` only after detaching the older volume right? 

I can confirm that, I have seen similar thing where a volume was "cleanly" detached and yet next attach to device (after significant time gap like 6-8 hours since last detach) still gets stuck in "attaching" state.  As far as k8s is concerned - it is doing right thing. It is only trying attach to a volume after detach has been successful. 

What Amazon is being hand wavy about is - the so called "device conflict". In my conversations with them - they have said following things (often sometimes conflicting):

1. Even after clean detach , sometimes a volume information can be cached by Operating System. They don't say where or why. 
2. They have also said,  sometimes the remote system - which is resonsible for attaching EBS volumes to nodes can also have cached device mapping and attempting to reuse a device can cause "attaching" bug.
3. In one conversation Amazon said - "detaching a mounted volume is same as force detaching". Now, obviously we know that detaching a mounted EBS volume doesn't work. The volume goes in "detaching" state and then "busy".  I am curious about this theory. I have tried to reproduce "attaching" bug by detaching a mounted volume, then attaching it (which fails) and then unmounting it. But so far it works and I could not reproduce it.

**Comment by geekofalltrades** [comment] 2017-09-28 00:09
This was Kubernetes 1.6.0.

I can only assume that k8s was trying to attach this volume after having detached the older one. Only k8s was managing the volumes attached to this instance; no human operator detached or attached any volumes to it.
