### ISSUE TITLE
Unable to resolve hostname using `kubectl logs`

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#22770] opened 2016-03-10 04:10 UTC
Using kubectl logs shows the following error:

```
Error from server: Get https://node-1:10250/containerLogs/kube-system/kibana-logging-v1-x1hr3/kibana-logging: dial tcp: lookup node-1: no such host
```

Kubernetes master uses nodeName to fetch logs from kubelet, which doesn't always resolve.  There are two workarounds as I can think of:
1. Manually add host entry in master's /etc/hosts, but this doesn't scale;
2. Use hostname override to use raw IP address. This is better, but raw IP is hard to manage and we see this error https://github.com/kubernetes/kubernetes/issues/22109

Since master already have the mapping from nodeName to IPAddress, we can get rid of the problem by just using internal IP?

**Comment by ernoaapa** [comment] 2016-03-22 05:57
:+1: Yes this is causing issues when i'm setting up from scrach. I want to use public ip as node name but cannot because apiserver uses it for communication. Would be great that I could give kubelet flags: `override-hostname=$public_ipv4` and `node-ip=$private_ipv4` and it would use the `InternalIP` for communication and display the public ip as hostname. I assumed this would work but it didn't :(

**Comment by ernoaapa** [comment] 2016-03-22 05:59
Some closely related discussion going on in here https://github.com/kubernetes/kubernetes/issues/22063

**Comment by Tha-Robert** [comment] 2016-09-09 10:52
Whats up with this ?

/T

**Comment by ernoaapa** [comment] 2016-09-10 04:42
I guess this have not been fixed. We're still using the internal ip as hostname and in node labels we have 'public-ip' label where we have the actual public ip. 
Really annoying if you want to for instance SSH to the server, first check nodes labels what the public ip is, then use that. Cannot use the node name because it's the internal ip 😞

**Comment by Aidamina** [comment] 2016-09-11 06:47
This isssue got worse because of #31311 although #32050 might eleviate some of the pain

**Comment by nelsonenzo** [comment] 2016-09-23 21:13
Is there any known workaround for this?  We just launched the new cluster in development and not being able to trail service logs is a big disappointment / near blocker for moving to production.

**Comment by ernoaapa** [comment] 2016-09-25 05:18
@nelsonenzo we're still using the workaround what I explained in previous comment.

**Comment by lukemarsden** [comment] 2016-09-26 15:09
This is about to become a much bigger problem as it affects everyone using the new `kubeadm` tool: https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/#limitations

**Comment by marun** [comment] 2016-09-27 18:21
I hit this problem a while ago and resorted to scripting periodic sync of node addresses and /etc/hosts on the master.

**Comment by errordeveloper** [comment] 2016-09-28 08:22
@kubernetes/sig-cluster-lifecycle could this be a low-hanging fruit for 1.5?

**Comment by mkulke** [comment] 2016-09-28 19:15
i ran into this issue with homebrewn clusters on AWS & OpenStack and had to resort to workarounds. eventually i wrote a patch which untangles `NodeName` from the node resolver in `logs/exec/port-forward`: #25532

**Comment by justinsb** [comment] 2016-09-29 04:54
We should be using the `nodeutil.GetNodeHostIP`, not the NodeName.  It is a long standing bug.  I'll try to put together a PR.

**Comment by justinsb** [comment] 2016-09-29 14:15
PR in #33718

**Comment by MarkThink** [comment] 2016-10-13 16:28
I also encountered a similar problem, weave network Kai not.

```
[root@master schema]# kubectl get po --namespace=kube-system -o wide
NAME                             READY     STATUS              RESTARTS   AGE       IP          NODE
etcd-master                      1/1       Running             3          10h       10.0.2.15   master
kube-apiserver-master            1/1       Running             3          10h       10.0.2.15   master
kube-controller-manager-master   1/1       Running             3          10h       10.0.2.15   master
kube-discovery-982812725-mtqfh   1/1       Running             0          18m       10.0.2.15   master
kube-dns-2247936740-3k2gn        0/3       ContainerCreating   0          5m        <none>      node1
kube-proxy-amd64-izxxe           1/1       Running             3          10h       10.0.2.15   master
kube-proxy-amd64-z8nj8           1/1       Running             1          10h       10.0.2.15   node1
kube-scheduler-master            1/1       Running             3          10h       10.0.2.15   master
weave-net-7m5jm                  2/2       Running             8          10h       10.0.2.15   master
weave-net-ed15l                  1/2       CrashLoopBackOff    1          20s       10.0.2.15   node1
```

```
[root@node1 schema]# kubectl logs -f weave-net-ed15l --namespace=kube-system -c weave
Error from server: Get https://node1:10250/containerLogs/kube-system/weave-net-ed15l/weave?follow=true: dial tcp: lookup node1 on 10.0.2.3:53: no such host
```

**Comment by buchireddy** [comment] 2016-11-09 18:58
It seems like the same issue could impact logging into an existing pod or running one off pods too.

This is the error message I'm seeing when I try to login to an existing pod.
```
root@ip-172-31-14-223:~# kubectl exec -it bash-2739707304-m14sw -- bash
Error from server: dial tcp 172.31.14.224:10250: i/o timeout
```

This is the error message when I tried `kubectl run`

```
root@ip-172-31-14-223:~# kubectl run -it bash --image=buchireddy/docker-bash -- bash
Waiting for pod default/bash-2739707304-m14sw to be running, status is Pending, pod ready: false
Waiting for pod default/bash-2739707304-m14sw to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
                                                      Error attaching, falling back to logs: dial tcp 172.31.14.224:10250: i/o timeout

Error from server: Get https://ip-172-31-14-224:10250/containerLogs/default/bash-2739707304-m14sw/bash: dial tcp 172.31.14.224:10250: i/o timeout
```

**Comment by hectorj2f** [comment] 2016-11-21 11:58
We also have a similar problem. We defined a specific hostname (not resolvable) to get a customized node name. We also specify the node-ip to a resolvable IP address in the kubelet parameters. So we expected the master api to use that `node-ip` instead of the hostname or node name. 

Surprisingly for us, kubernetes master uses the hostname to communicate with the kubelet instead of the node ip. So it cannot fetch the logs of our apps.

**Comment by derailed** [comment] 2016-11-26 19:05
Having the same issue here with timeouts using either kubectl logs/execs on pods. Cluster was hydrated via kubeadm. I understand I can alway ssh to instance and get logs/exec but this is a royal pain. Any update on this issue?

**Comment by mkulke** [comment] 2016-11-27 17:48
I haven't had the time to test an 1.5 cluster yet, but from looking at the code, i guess what works now is: 

- Set something master-resolvable via `--hostname-override` on the kubelet.
- Have the cloud-provider rename the node to something non-resolvable.

@hectorj2f By default the node uses the node's hostname, so when you use `--hostname-override` with some non-resolvable display name (e.g. "my-node-1"), the master will not be able to talk to the kubelet, because by default the hostname will be preferred as means to talk to the kubelet.

however in 1.5 there is also `--preferred-address-types` (https://github.com/kubernetes/kubernetes/blob/release-1.5/cmd/kube-apiserver/app/options/options.go#L112), which you can use to specify a priority list of comm options (Hostname, InternalIP, ExternalIP, LegacyHostIP).

The flag is not documented yet, but I think this should solve most issues around apiserver->kubelet comm.

**Comment by bonovoxly** [comment] 2016-12-01 15:47
@mkulke minor correction (because I just ran into it), use `--kubelet-preferred-address-types`.

**Comment by xmik** [comment] 2016-12-10 15:11
I confirm that `kubectl logs` and `kubectl exec` work when using Kubernetes 1.5.0-beta3 and having set `--kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP` for apiserver.

**Comment by vchan2002** [comment] 2017-02-07 23:24
>I haven't had the time to test an 1.5 cluster yet, but from looking at the code, i guess what works now is:

Set something master-resolvable via --hostname-override on the kubelet.
Have the cloud-provider rename the node to something non-resolvable.

**Comment by estechnical** [comment] 2017-09-15 14:56
This issue also affects me, I have just set up a kubernetes cluster with MAAS + Juju without using conjure-up, because conjure-up was failing to place the services correctly on our machines.

This issue https://github.com/conjure-up/conjure-up/issues/1150 details how I got where I am now...

When I try to use kubectl logs, it clearly shows that the dns request is going to google DNS:
```
https://jump:10250/containerLogs/default/kubernetes-bootcamp-2457653786-g7msl/kubernetes-bootcamp: dial tcp: lookup jump on 8.8.4.4:53: no such host
```
Is this the same issue or does this need a new one to be opened?

**Comment by estechnical** [comment] 2017-10-02 09:19
Sorry for the really long delay!
I can confirm that adding the names of the our nodes to /etc/hosts on the kubernetes master resolves this problem for us too :)

**Comment by luxas** [comment] 2017-10-19 18:45
I'm closing this as this feature has been around for quite some time now.

**Closed by luxas** 2017-10-19 18:45 UTC
Labels: priority/backlog, sig/api-machinery
