### ISSUE TITLE
Kube Proxy: Unable to open port when scheduling pods to kube master

### ISSUE THREAD

**Issue by brokoli18** [kubernetes/kubernetes#107297] opened 2022-01-03 21:24 UTC
### What happened?

I deployed a single node using kubeadm with the following components:
* docker CRI
* Flannel network
* Metallb ingress

After deploying the node I removed the master taint to enable scheduling pods on this node. Then I created an nginx deployment along with a loadbalancer service. After this the service should recieve an external IP on my local network (which it did), but this IP was not reachable. After checking the kubernetes services I noticed this in the logs:
```
E0103 15:18:11.648373       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30784: bind: address already in use" 
```
When checking this port on the node it is used by the kube proxy process:
```
tcp        0      0 0.0.0.0:30784           0.0.0.0:*               LISTEN      1000377/kube-proxy
```
If I delete this service the port is immidiately freed up, so there is no other service using it.

The `kube-proxy` version is `v1.23.1`. If I downgrade this to `v1.20.1` the loadbalancer starts working immidiately and there is no error in the logs, which leads me to believe that this is a bug.

### What did you expect to happen?

I expected the loadbalancer service to be reachable on the exposed port

### How can we reproduce it (as minimally and precisely as possible)?

* Deploy 1 kubernetes node with kubeadm
* Remove the master taint to enable scheduling of pods
* Set up flannel networking
* Create a loadbalancer/Nodeport type service
* Observe the logs of the kube proxy and the endpoint of the service to see this error
* Create a deployment and check that it is unreachable behind this service

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Bare Metal

### OS version

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### Install tools

kubeadm/kubernetes-xenial,now 1.23.1-00 amd64

### Container runtime (CRI) and and version (if applicable)

<details>

```
docker.io/focal-updates,focal-security,now 20.10.7-0ubuntu5~20.04.2 amd64 [installed]
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

```
k8s.gcr.io/kube-apiserver                        v1.23.1   b6d7abedde39   2 weeks ago     135MB
k8s.gcr.io/kube-proxy                            v1.23.1   b46c42588d51   2 weeks ago     112MB
k8s.gcr.io/kube-controller-manager               v1.23.1   f51846a4fd28   2 weeks ago     125MB
k8s.gcr.io/kube-scheduler                        v1.23.1   71d575efe628   2 weeks ago     53.5MB
quay.io/coreos/flannel                           v0.15.1   e6ea68648f0c   7 weeks ago     69.5MB
k8s.gcr.io/etcd                                  3.5.1-0   25f8c7f3da61   2 months ago    293MB
quay.io/metallb/speaker                          v0.11.0   896b796b12bb   2 months ago    50.2MB
quay.io/metallb/controller                       v0.11.0   85a7890eec45   2 months ago    46.5MB
rancher/mirrored-flannelcni-flannel-cni-plugin   v1.0.0    cd5235cd7dc2   2 months ago    9.03MB
k8s.gcr.io/coredns/coredns                       v1.8.6    a4ca41631cc7   2 months ago    46.8MB
k8s.gcr.io/pause                                 3.6       6270bb605e12   4 months ago    683kB
```

**Comment by aojea** [comment] 2022-01-03 21:34
/sig network
can you upload the kube-proxy logs?

**Comment by brokoli18** [comment] 2022-01-03 21:42
```
I0103 21:39:02.074293       1 node.go:163] Successfully retrieved node IP: 192.168.1.202
I0103 21:39:02.074422       1 server_others.go:138] "Detected node IP" address="192.168.1.202"
I0103 21:39:02.074481       1 server_others.go:561] "Unknown proxy mode, assuming iptables proxy" proxyMode=""
I0103 21:39:02.106295       1 server_others.go:206] "Using iptables Proxier"
I0103 21:39:02.106387       1 server_others.go:213] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I0103 21:39:02.106416       1 server_others.go:214] "Creating dualStackProxier for iptables"
I0103 21:39:02.106457       1 server_others.go:491] "Detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6"
I0103 21:39:02.107116       1 server.go:656] "Version info" version="v1.23.1"
I0103 21:39:02.111282       1 conntrack.go:52] "Setting nf_conntrack_max" nf_conntrack_max=131072
I0103 21:39:02.112132       1 config.go:317] "Starting service config controller"
I0103 21:39:02.112165       1 shared_informer.go:240] Waiting for caches to sync for service config
I0103 21:39:02.113563       1 config.go:226] "Starting endpoint slice config controller"
I0103 21:39:02.113584       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
I0103 21:39:02.212278       1 shared_informer.go:247] Caches are synced for service config
I0103 21:39:02.213755       1 shared_informer.go:247] Caches are synced for endpoint slice config
E0103 21:40:11.856203       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30756: bind: address already in use" port={Description:nodePort for default/nginx:80-80 IP: IPFamily:4 Port:30756 Protocol:TCP}
```
This is after updating the daemonset to use `v1.23.1` again and recreating the loadbalancer service

**Comment by aojea** [comment] 2022-01-04 14:26
can you dump the service that is causing the issue with ` kubectl get service <service> -o yaml` ?

**Comment by khenidak** [comment] 2022-01-04 19:26
How are you running kube-proxy? (it could be a case of running two of them)

**Comment by khenidak** [comment] 2022-01-04 20:45
/triage accepted

ah i think i see the bug. The following conditions needed.
1. No nodeaddresses
2. service without node port.

this will hit both proxiers https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1288
e.g. both will try to bind to `:<node-port>`

will PR a fix.

/assign

**Comment by khenidak** [comment] 2022-01-04 20:53
@brokoli18 as a temp work around you can set node addresses by setting `--nodeport-addresses` on your kube-proxy to a string slice e.g `--nodeport-addresses=<IPv4>,<IPv6>`

**Comment by aojea** [comment] 2022-01-04 21:17
interesting, the IP family discriminator in golang is not enough?
https://github.com/kubernetes/kubernetes/blob/9e209efd6567698894a86e30be025796d7e26aa4/pkg/proxy/iptables/proxier.go#L1300

**Comment by khenidak** [comment] 2022-01-05 18:47
I was wrong. It is wire all the way to port opener. 

@brokoli18  Can you please verify how many kube-proxy instances running on that node (when that error happens)? 

meanwhile i will check for other root causes.

**Comment by khenidak** [comment] 2022-01-05 19:08
also please share the service specification (after the error).

**Comment by brokoli18** [comment] 2022-01-06 14:29
Here is the definition of the service:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-06T13:59:36Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "360935"
  uid: d85ceb3f-9bfd-4390-8e5c-3a2778df4ff7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.127.22
  clusterIPs:
  - 10.111.127.22
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    nodePort: 31582
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.235
```

I had the thought myself that perhaps there are multiple kube proxies running on this node but as far as I can tell there is only 1, in a docker container. This is the default setup for kubeadm I believe:
```
$ ps aux | grep kube-proxy
root     2489724  0.0  0.4 748684 39800 ?        Ssl  13:57   0:00 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=sol
```

I had a look into using the `--nodeport-addresses=` option but wasnt sure where to put it. I ended up editing the kube-proxy daemonset and added it as a the commandline flag there but the result was the same.

**Comment by tdevinda** [comment] 2022-01-20 05:38
> I was wrong. It is wired all the way to port opener.
> 
> @brokoli18 Can you please verify how many kube-proxy instances running on that node (when that error happens)?
> 
> meanwhile i will check for other root causes.

I have the same issue. In my case there are two kube-proxy instances running when this happens. Both pods report the same port in use error

```
ubuntu@kube-master:/data/apps/hss-management-service$ k8 get pods --all-namespaces
NAMESPACE        NAME                                  READY   STATUS    RESTARTS   AGE
ccno-uservices   hss-management-8c6cf8477-s5jhn        1/1     Running   0          105m
kube-system      coredns-64897985d-pbbcd               1/1     Running   0          19h
kube-system      coredns-64897985d-qm9nz               1/1     Running   0          19h
kube-system      etcd-kube-master                      1/1     Running   4          19h
kube-system      kube-apiserver-kube-master            1/1     Running   2          19h
kube-system      kube-controller-manager-kube-master   1/1     Running   2          19h
kube-system      kube-proxy-6f77w                      1/1     Running   0          18h
kube-system      kube-proxy-mnb7k                      1/1     Running   0          19h
kube-system      kube-scheduler-kube-master            1/1     Running   2          19h
```

```
E0120 04:03:01.330412       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30205: bind: address already in use" port={Description:nodePort for ccno-uservices/hss-management-service:http IP: IPFamily:4 Port:30205 Protocol:TCP}
E0120 04:36:51.399804       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :31010: bind: address already in use" port={Description:nodePort for ccno-uservices/hss-management-service:http IP: IPFamily:4 Port:31010 Protocol:TCP}
```

**Comment by aojea** [comment] 2022-01-20 07:30
> I have the same issue. In my case there are two kube-proxy instances running when this happens

That is not supported, you can only have one kubeproxy

**Comment by tdevinda** [comment] 2022-01-20 07:52
I think that is supposed to be the way. I later found out that kube-proxy is a daemon set. I have two nodes. Master and a minion. So 2 proxies should be normal. 😢 I need to find a way around this. looks like for now a downgrade is the only option.

**Comment by aojea** [comment] 2022-01-20 10:45
> I think that is supposed to be the way. I later found out that kube-proxy is a daemon set. I have two nodes. Master and a minion. So 2 proxies should be normal. cry I need to find a way around this. looks like for now a downgrade is the only option.

sorry, let me clarify: I mean "two kube-proxy processes on the same node at the same time" :smile:

**Comment by drew-viles** [comment] 2022-01-22 16:44
Not sure if this will be much use in getting to the bottom of it but my fix was to switch the proxy-mode of kube-proxy from iptables to IPVS.

I'm not using KubeADM but have configured the services myself however it may still help those who have configured their cluster using KubeADM

Using proxy-mode iptables:
```
-- Logs begin at Fri 2021-12-17 12:30:32 UTC. --
Jan 22 16:33:43 server-0 kube-proxy[3105439]: I0122 16:33:43.899434 3105439 config.go:317] "Starting service config controller"
Jan 22 16:33:43 server-0 kube-proxy[3105439]: I0122 16:33:43.899513 3105439 shared_informer.go:240] Waiting for caches to sync for service config
Jan 22 16:33:43 server-0 kube-proxy[3105439]: I0122 16:33:43.899644 3105439 config.go:226] "Starting endpoint slice config controller"
Jan 22 16:33:43 server-0 kube-proxy[3105439]: I0122 16:33:43.899687 3105439 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
Jan 22 16:33:44 server-0 kube-proxy[3105439]: I0122 16:33:44.003333 3105439 shared_informer.go:247] Caches are synced for service config
Jan 22 16:33:44 server-0 kube-proxy[3105439]: I0122 16:33:44.009714 3105439 shared_informer.go:247] Caches are synced for endpoint slice config
Jan 22 16:33:44 server-0 kube-proxy[3105439]: E0122 16:33:44.336695 3105439 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :32032: bind: address already in use" port={Description:nodePort for public-ingress/ingress-nginx-controller:https IP: IPFamily:4 Port:32032 Protocol:TCP}
Jan 22 16:33:44 server-0 kube-proxy[3105439]: E0122 16:33:44.337180 3105439 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30798: bind: address already in use" port={Description:nodePort for public-ingress/ingress-nginx-controller:http IP: IPFamily:4 Port:30798 Protocol:TCP}
Jan 22 16:33:44 server-0 kube-proxy[3105439]: E0122 16:33:44.346943 3105439 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :31815: bind: address already in use" port={Description:nodePort for gitea/gitea-ssh:ssh IP: IPFamily:4 Port:31815 Protocol:TCP}
Jan 22 16:33:44 server-0 kube-proxy[3105439]: E0122 16:33:44.354410 3105439 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30315: bind: address already in use" port={Description:nodePort for database/postgresql:sql IP: IPFamily:4 Port:30315 Protocol:TCP}
```

Using IPVS:
```
-- Logs begin at Fri 2021-12-17 12:30:32 UTC. --
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.205218 3111214 ipset.go:113] "Ipset name truncated" ipSetName="KUBE-6-LOAD-BALANCER-SOURCE-CIDR" truncatedName="KUBE-6-LOAD-BALANCER-SOURCE-CID"
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.205282 3111214 ipset.go:113] "Ipset name truncated" ipSetName="KUBE-6-NODE-PORT-LOCAL-SCTP-HASH" truncatedName="KUBE-6-NODE-PORT-LOCAL-SCTP-HAS"
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.205850 3111214 server.go:656] "Version info" version="v1.23.0"
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.213968 3111214 conntrack.go:52] "Setting nf_conntrack_max" nf_conntrack_max=131072
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.218443 3111214 config.go:317] "Starting service config controller"
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.218503 3111214 shared_informer.go:240] Waiting for caches to sync for service config
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.218598 3111214 config.go:226] "Starting endpoint slice config controller"
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.218621 3111214 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.318963 3111214 shared_informer.go:247] Caches are synced for endpoint slice config
Jan 22 16:37:55 server-0 kube-proxy[3111214]: I0122 16:37:55.319166 3111214 shared_informer.go:247] Caches are synced for service config
```

**Comment by huangyingxian** [comment] 2022-01-25 12:53
I have the same error for it

**Comment by tdevinda** [comment] 2022-01-25 13:11
I don't know if I was supposed to do this in the first place, but I fixed it by installing flannel. 
Install it before you deploy any services. 
This issue was there for me in 1.23.0, 1.20.8

Before I went to 1.19's I tried flannel. 
Thanks to @sambestsolutions

**Comment by rtheis** [comment] 2022-02-03 13:47
We are also seeing this error on our managed service starting with Kubernetes version 1.23.  We are using Calico CNI and run iptables version of kube-proxy.  We can see kube-proxy listening on the node port.  We only have 1 version of kube-proxy running.  It seems that kube-proxy is doing this to itself.  The good news is that these errors appear to be noise in the logs since we haven't seen any problems as a result.

```
kube-prox  7166            root    7u  IPv4   107518      0t0  TCP *:30619 (LISTEN)
```

```
root@test-c7ol0um20idusck2tng0-iks123-default-00000185:/var/log# iptables -nvL -t nat | grep 30619
    0     0 KUBE-SVC-Z5B3TVBZULVR2BRU  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/public-crc7ol0um20idusck2tng0-alb1:http */ tcp dpt:30619
    0     0 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/public-crc7ol0um20idusck2tng0-alb1:http */ tcp dpt:30619
```

```
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.465779    7166 service.go:304] "Service updated ports" service="kube-system/public-crc7ol0um20idusck2tng0-alb1" portCount=2
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.465841    7166 service.go:419] "Adding new service port" portName="kube-system/public-crc7ol0um20idusck2tng0-alb1:http" servicePort="172.21.57.159:80/TCP"
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.465849    7166 service.go:419] "Adding new service port" portName="kube-system/public-crc7ol0um20idusck2tng0-alb1:https" servicePort="172.21.57.159:443/TCP"
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.465892    7166 proxier.go:827] "Syncing iptables rules"
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.513576    7166 proxier.go:1604] "Opened local port" port={Description:nodePort for kube-system/public-crc7ol0um20idusck2tng0-alb1:http IP: IPFamily:4 Port:30619 Protocol:TCP}
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: E0126 14:12:42.513671    7166 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30619: bind: address already in use" port={Description:nodePort for kube-system/public-crc7ol0um20idusck2tng0-alb1:http IP: IPFamily:4 Port:30619 Protocol:TCP}
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: I0126 14:12:42.513700    7166 proxier.go:1604] "Opened local port" port={Description:nodePort for kube-system/public-crc7ol0um20idusck2tng0-alb1:https IP: IPFamily:4 Port:31481 Protocol:TCP}
Jan 26 14:12:42 test-c7ol0um20idusck2tng0-iks123-default-00000185 kube-proxy.service[7166]: E0126 14:12:42.513720    7166 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :31481: bind: address already in use" port={Description:nodePort for kube-system/public-crc7ol0um20idusck2tng0-alb1:https IP: IPFamily:4 Port:31481 Protocol:TCP}
```

**Comment by aojea** [comment] 2022-02-03 14:48
This was fixed by https://github.com/kubernetes/kubernetes/pull/107413

It's a duplicate of https://github.com/kubernetes/kubernetes/issues/107170

/close

Please reopen if I'm mistaken

**Closed** 2022-02-03 14:48 UTC
Labels: kind/bug, sig/network, triage/accepted

**Comment by watery** [comment] 2023-06-17 17:46
@aojea  I think I've hit this, I'm on 1.23 and can't update (because I purposely chose this version to replicate a production env).

Adding `--nodeport-addresses` to kube-proxy command line (by editing the kube-proxy daemon set) didn't solve; I tried setting it to "0.0.0.0/8" or 127.0.0.1/8 but none worked.

Is there anything else I can do?

I'm going through these https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/ initial tutorials and I'm stuck because any service I create doesn't work due to the kube-proxy:

```
kubectl logs kube-proxy-7bxk7 -n kube-system
I0617 17:21:57.578051       1 node.go:163] Successfully retrieved node IP: 10.8.191.138
I0617 17:21:57.578219       1 server_others.go:138] "Detected node IP" address="10.8.191.138"
I0617 17:21:57.578609       1 server_others.go:561] "Unknown proxy mode, assuming iptables proxy" proxyMode=""
I0617 17:21:57.807762       1 server_others.go:206] "Using iptables Proxier"
I0617 17:21:57.808055       1 server_others.go:213] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I0617 17:21:57.808092       1 server_others.go:214] "Creating dualStackProxier for iptables"
I0617 17:21:57.808168       1 server_others.go:491] "Detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6"
I0617 17:21:57.809144       1 server.go:656] "Version info" version="v1.23.0"
I0617 17:21:57.814749       1 conntrack.go:52] "Setting nf_conntrack_max" nf_conntrack_max=131072
I0617 17:21:57.816000       1 config.go:317] "Starting service config controller"
I0617 17:21:57.816032       1 shared_informer.go:240] Waiting for caches to sync for service config
I0617 17:21:57.816055       1 config.go:226] "Starting endpoint slice config controller"
I0617 17:21:57.816069       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
I0617 17:21:57.916266       1 shared_informer.go:247] Caches are synced for endpoint slice config
I0617 17:21:57.916448       1 shared_informer.go:247] Caches are synced for service config
E0617 17:21:57.965716       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :30664: bind: address already in use" port={Description:nodePort for default/kubernetes-bootcamp IP: IPFamily:4 Port:30664 Protocol:TCP}

```

So far I have a control plane node and a worker node and the issue is present on both.

```
sudo netstat -ap | grep 30664
tcp        0      0 0.0.0.0:30664           0.0.0.0:*               LISTEN      10789/kube-proxy
```

One proxy is running on each node:

```
kubectl get pods -l k8s-app=kube-proxy -n kube-system -o wide
NAME               READY   STATUS    RESTARTS   AGE   IP             NODE            NOMINATED NODE   READINESS GATES
kube-proxy-7bxk7   1/1     Running   0          22m   10.8.191.138   vaio-sve151     <none>           <none>
kube-proxy-fpzhq   1/1     Running   0          22m   10.8.191.148   thinkpad-x260   <none>           <none>
```

The very first time I created a service, it worked; then I deleted it and now any further service I create isn't accessible.
Deleting the kube-proxy pods or restarting the whole cluster didn't help either.

**Comment by aojea** [comment] 2023-06-17 17:59
> version="v1.23.0"

1.23 is EOL,but anyway, if you still want to use 1.23 you should update to latest minor version, that has the fix
