### ISSUE TITLE
APIGroups are hard to deal with in the code

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#16173] opened 2015-10-23 18:43 UTC
APIGroups are a really useful features, but there are several areas of the code that need improvement to make their usage easier to understand.  These are few things I found while trying to reliably activate and configure the `extensions` group downstream
1. We need a `GroupVersion` object to make it very obvious in the code when a bit of code relies on that.  Right now, sometimes its two strings, sometimes its one string to split, sometimes objects hold both.
2. Validation is needed when starting a master to make sure that combination of `StorageDestinations`, `apiGroupVersionOverrides`, `storageVersions`, and the available `Groups` makes sense.  I suspect that there's a cleaner factorization.
3. DONE Functions like `InterfacesFor` need to decide if they take `GroupVersion` or just an API version.  I'm ok with either one, but right now you get things like an error message saying `unsupported storage version: v1beta1 (valid: v1beta1)` because part of the code thinks its a version and part of it thinks its a `GroupVersion`.
4. REST APIVersions are unrelated to storage APIVersions.  Right now, the REST preferred version is tied to the storage version.
5. Reporting throughout the stack should understand that `Kind` strings are no longer unambiguous.  Types like `StatusDetails` should accept an `APIGroup` as well.
6. Registrations of `GroupMeta` shouldn't be mutable.  I don't see why we'd ever want it mutable and its kind of crazy to change it part way through.
7. DONE (well, differently in https://github.com/kubernetes/kubernetes/pull/16062) Type registration and lookups seems to be split across three packages (`install`, `registered`, `latest`), all of which try to take APIGroups into account.  This needs reorganization.  Perhaps we could try a layered approach where `latest` is scoped to versions of a single APIGroup, `install` is responsible for handling registration with a `registered` package which is the source of truth for all metadata.  No other package should expose cross group metadata.
8. Having combined clients makes it harder to trace the effects of disabling an APIGroup and risks potential name collisions going forward.  Splitting Clients on APIGroups seems reasonable.

One of the things that may help with factorization is trying to describe the existing `v1` API as an GroupVersion("", "v1") throughout all of the code.  If its hard to read like that, then there's probably a factorization problem.

@caesarxuchao @smarterclayton @liggitt @kubernetes/kube-api

**Comment by mikedanese** [comment] 2015-10-23 19:10
@kubernetes/goog-csi

**Comment by lavalamp** [comment] 2015-10-28 04:22
I agree with everything but 4-- why not make the storage version the preferred version? We can be more efficient if clients speak that version (in theory).

**Comment by deads2k** [comment] 2015-10-28 11:51
> I agree with everything but 4-- why not make the storage version the preferred version? We can be more efficient if clients speak that version (in theory).

It makes an rolling update more painful.  If I want to roll an update that disables the old REST API, but keep addition API servers running that don't have the more recent codecs during the process, the current code forces me to expose a REST API version that I don't want to use.

I don't object to the current mode as a default, but I do object to it being the only valid combination.

**Comment by caesarxuchao** [comment] 2015-11-12 21:59
@deads2k thank you very much for submitting #17175. I'm working on the same issue since yesterday because the issue is assigned to me. In the future may we coordinate in the issue page to avoid duplicated efforts? Thank you for the understanding :)

**Comment by deads2k** [comment] 2015-11-12 22:55
> In the future may we coordinate in the issue page to avoid duplicated efforts? Thank you for the understanding :)

Sorry, I had a couple hours free, figured I'd help.  I'll open a detailed issue tomorrow with the known hot spots.  Then we can sort of check them out as we go along and work together.  There's enough touch points that a big bang is untenable.  Looks like each minor piece is going to take a few hours to do.

**Comment by caesarxuchao** [comment] 2015-11-12 23:05
Thank you @deads2k. I have the PR with many TODOs passing unit tests. I think it should cover most hot spots. I'll push it so we can take it as a reference.

**Comment by caesarxuchao** [comment] 2015-11-13 00:02
@deads2k here is my laundry list. https://github.com/kubernetes/kubernetes/pull/17185#issuecomment-156273462
You are welcome to edit it or open another issue.

**Comment by caesarxuchao** [comment] 2015-11-16 18:13
The laundry lists is in #17216.

**Comment by lavalamp** [comment] 2016-02-08 20:59
@deads2k Is there stuff in here that you still want to get in to 1.2? I'm thinking of kicking this out of the milestone.

**Comment by deads2k** [comment] 2016-02-09 12:48
> @deads2k Is there stuff in here that you still want to get in to 1.2? I'm thinking of kicking this out of the milestone.

I'm ok with that. We're still making progress.

**Closed** 2018-02-20 21:42 UTC
Labels: lifecycle/rotten, priority/important-soon, sig/api-machinery
