### ISSUE TITLE
Etcd v3 upgrade tests are failing

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#42247] opened 2017-02-28 14:37 UTC
I looked into logs from etcd v3 upgrade tests, and:

1.  in the latest branch: https://k8s-testgrid.appspot.com/etcd-upgrades
- etcd seems to upgrade fine,
- but apiserver is not starting with the following error:
```
I0228 14:08:06.816255       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
```

[seems to unrelated to etcd v3 in my opinion, but we should debug and fix it]

2. in the 1.5 branch: https://k8s-testgrid.appspot.com/etcd-upgrades#gce-1.5
- we are not even running upgrade tests
```
I0228 05:53:27.442] flag provided but not defined: -etcd-upgrade-storage
```

I think that it should be enough to cherrypick: https://github.com/kubernetes/kubernetes/pull/41852 to 1.5 branch.

**Comment by wojtek-t** [comment] 2017-02-28 15:48
@mikedanese @cjcullen - do any of you know why we are getting:
```
```
I0228 14:08:06.816255       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
```
```
?

**Comment by calebamiles** [comment] 2017-02-28 16:18
**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

**Comment by wojtek-t** [comment] 2017-02-28 16:52
https://github.com/kubernetes/kubernetes/pull/42260 should hopefully fix the problem with 1.5 branch

**Comment by wojtek-t** [comment] 2017-02-28 18:43
Talked with @mikedanese offline and this is some known issue - he is working on it in https://github.com/kubernetes/kubernetes/pull/42200

**Comment by nicksardo** [comment] 2017-02-28 23:38
Dupe of #42199

**Comment by wojtek-t** [comment] 2017-03-01 00:30
@nicksardo - only part of it is a dup. There is also some other issue.

**Comment by wojtek-t** [comment] 2017-03-01 15:02
Both of the problems above are now solved.

Though, the tests are still not passing. I've just merged: https://github.com/kubernetes/test-infra/pull/2084 that slightly modified configs of those jobs. And I hope this would solve the problem.

**Comment by mml** [comment] 2017-03-02 22:15
I think we can close this.  I am tracking one other failure in #38569 but I think I've got that one fixed, too.

**Closed by mml** 2017-03-02 22:15 UTC
Labels: priority/failing-test, sig/api-machinery
