### ISSUE TITLE
Allow `--all-namespaces=true` for `kubectl delete`

### ISSUE THREAD

**Issue by cilerler** [kubernetes/kubernetes#44718] opened 2017-04-20 13:07 UTC
**FEATURE REQUEST**

Not be able to use line below

```
kubectl delete services,deployments -l app=app1 --all-namespaces 
```

forces us to do this

```
kubectl delete services,deployments -l app=app1 --namespace=ns1
---
kubectl delete services,deployments -l app=app1 --namespace=ns2
---
kubectl delete services,deployments -l app=app1 --namespace=ns3
```

I would go to 20 but I believe you get the idea 😉 

**Kubernetes version**
Client v1.5.4
Server v1.6.1

**Comment by liggitt** [comment] 2017-04-20 15:02
@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment] 2017-04-20 15:03
deletion across all namespaces can be really destructive... since we can't prompt or warn, this makes it easy to fat-finger a cluster destroying action

**Comment by cilerler** [comment] 2017-04-20 15:34
I hear you, however since it will be an optional feature we should be fine.  😎

**Comment by liggitt** [comment] 2017-04-20 15:40
> since it will be an optional feature we should be fine. 😎

until tab-completion makes someone who meant to do --all delete everything in their cluster :-/

**Comment by smarterclayton** [comment] 2017-04-20 16:16
Yeah, I'm fairly sure this should require an additional confirmation.
Delete in general is too powerful by default.

**Comment by xiangpengzhao** [comment] 2017-04-20 17:55
Users might prefer `--namespace=ns1, ns2, ns3` to `--all-namespaces` for delete command. Take care of your `kube-system` :)

BTW, do we support such format `--namespace=ns1, ns2, ns3` now?

**Comment by cilerler** [comment] 2017-04-20 18:40
@xiangpengzhao nope

**Comment by bgrant0607** [comment] 2017-04-24 23:56
Dupe of #18282

**Closed by bgrant0607** 2017-04-24 23:56 UTC
Labels: kind/enhancement, sig/cli
