### ISSUE TITLE
kubectl apply doesn't work with thirdparty resource

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#23705] opened 2016-03-31 21:04 UTC
This is to keep track of known issues of thirdparty resource.

cc @brendandburns

**Comment by kargakis** [comment] 2016-03-31 23:03
@kubernetes/kubectl

**Comment by brendandburns** [comment] 2016-11-01 05:34
Dupe of https://github.com/kubernetes/kubernetes/issues/29542 (which has more detail)

Closing.

**Closed by brendandburns** 2016-11-01 05:34 UTC
Labels: area/app-config-deployment, component/kubectl, priority/P2, team/CSI-API Machinery SIG, team/ux
