### ISSUE TITLE
storage unit test flakes with "Unexpected error: too old resource version: 2 (3)"

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#18794] opened 2015-12-17 00:11 UTC
Looks like a unit test flake. A race between two concurrent instances of this test updating the same resource?
```
<testsuite tests="9" failures="1" time="1.451" name="k8s.io/kubernetes/pkg/storage">
<properties>
<property name="go.version" value="go1.4.3"/>
</properties>
<testcase classname="storage" name="TestEtcdParseWatchResourceVersion" time="0.000"/>
<testcase classname="storage" name="TestWatchCacheBasic" time="0.000"/>
<testcase classname="storage" name="TestEvents" time="0.000"/>
<testcase classname="storage" name="TestWaitUntilFreshAndList" time="0.000"/>
<testcase classname="storage" name="TestReflectorForWatchCache" time="0.000"/>
<testcase classname="storage" name="TestList" time="0.270"/>
<testcase classname="storage" name="TestWatch" time="0.370"/>
<testcase classname="storage" name="TestWatcherTimeout" time="0.160">
<failure message="Failed" type="">
cacher_test.go:235: Unexpected error: too old resource version: 2 (3)
</failure>
</testcase>
<testcase classname="storage" name="TestFiltering" time="0.380"/>
</testsuite>
```

cc @saad-ali

**Comment by quinton-hoole** [comment] 2015-12-17 00:12
Actually this is etcd stuff, not PD storage.  Relabelling accordingly.

**Comment by quinton-hoole** [comment] 2015-12-17 00:16
#17915 is where it happened.

**Comment by wojtek-t** [comment] 2015-12-17 10:27
I think this may be solved by https://github.com/kubernetes/kubernetes/pull/18635

**Comment by wojtek-t** [comment] 2015-12-22 15:20
Since this code change significantly since then, I'm closing this one. Please open another issue, if you observe it again.

**Comment by wojtek-t** [comment] 2015-12-23 06:34
I've just seen it again - reopening.

**Comment by wojtek-t** [comment] 2015-12-23 06:35
I'm on vacation now - may look into it once I'm back.

**Comment by wojtek-t** [comment] 2015-12-28 12:55
I didn't record that failure and now I'm unable to find it.
If someone observes this error - can you please paste a link to it here?

**Comment by wojtek-t** [comment] 2015-12-28 14:00
OK, I've got something:

    === RUN   TestWatch
    --- FAIL: TestWatch (0.08s)
	    cacher_test.go:184: Unexpected error: too old resource version: 1 (3)

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/9d912e843b40193c59cfa8d72b6b5780bda53b11/kubernetes-pull-test-unit-integration/7414/?debugUI=DEVELOPERS

**Comment by wojtek-t** [comment] 2015-12-28 14:30
OK - I managed to reproduce it locally (this is a race in test).
The fix is already sent out for review - #19140

**Comment by brendandburns** [comment] 2015-12-30 16:45
Re-opening this as it just flaked @ head:

.../job/kubernetes-test-go/5325/

**Comment by wojtek-t** [comment] 2015-12-30 17:13
cacher_test.go:302: Unexpected error: too old resource version: 4 (5)

This is a different issue than the original one (that I fixed), although the error is similar (I mean the original issue was in initialization, this one is in the middle/end of a test).

**Comment by wojtek-t** [comment] 2015-12-30 19:11
I have no idea what is happening here.
I've sent out PR extending logging for debugging purposes out for review - #19203

**Comment by wojtek-t** [comment] 2015-12-30 21:54
The log from failure;

    E1230 21:37:19.586059   18906 cacher_test.go:309] cached event: MODIFIED &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"5", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8205a0c70), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc82069aac0), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
    E1230 21:37:19.586726   18906 cacher_test.go:309] cached event: MODIFIED &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"6", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc82058de90), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc82058b780), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
    E1230 21:37:19.587501   18906 cacher_test.go:309] cached event: MODIFIED &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"7", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc82052a9c0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"fakeNode", SecurityContext:(*api.PodSecurityContext)(0xc82036cc80), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
    E1230 21:37:19.588029   18906 cacher_test.go:309] cached event: DELETED &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"8", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8205a17c0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"fakeNode", SecurityContext:(*api.PodSecurityContext)(0xc82069adc0), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}

It seems that because of some reason, the first event (addition) is missing...

**Comment by wojtek-t** [comment] 2015-12-31 06:51
OK - thanks to the logs, I managed to understood what was happening here. It's a test issue.
Will send a fix soon.

**Closed** 2015-12-31 08:35 UTC
Labels: kind/flake, priority/P2, team/CSI
