### ISSUE TITLE
Scheduler is getting really, really slow under bigger load.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20011] opened 2016-01-22 19:06 UTC
We're running kubemark tests with 500 nodes, which are recently failing:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-500-gce/1737

After 4.5k pods get scheduled and running scheduler is getting very, very slow. At the end we're getting to the state:
10:04:57 Jan 22 10:04:57.128: INFO: density15000-20a915d4-c130-11e5-9093-42010af01555 Pods: 15000 out of 15000 created, 4662 running, 109 pending, 10229 waiting, 0 inactive, 135 terminating, 0 unknown, 0 runningButNotReady 

Scheduler itself seems pretty relaxed, using 0.1-0.3 CPU on a master machine, but for some reason pods are not getting scheduled.

I think it may be caused by #18452, but I need to verify that.

cc @xiang90 @davidopp @lavalamp @timothysc

**Comment by xiang90** [comment] 2016-01-22 19:36
@hongchaodeng Can you take a look? Any regression found in our kube mark scheduling test?

**Comment by davidopp** [comment] 2016-01-22 19:52
@brendandburns A second set of eyes would be useful here. I reviewed this code and don't see how it could make anything slower but maybe I missed something?

If you think this code is blameless, and you have time, looking into the performance regression could be helpful.

**Comment by davidopp** [comment] 2016-01-22 20:04
But also @xiang90 @hongchaodeng if you can look into this - that would be great. Once we have performance regressions, the more time that passes the worse things get as it becomes harder and harder to track down the root cause.

**Comment by hongchaodeng** [comment] 2016-01-22 22:42
Confirmed that we have seen similar problems.
I will look into it. 
@gmarek Can you paste more log at the point when it's stuck? I don't have access to the link.

**Comment by lavalamp** [comment] 2016-01-22 22:45
That PR does change from index variables to copies. I would not expect that to result in a massive slowdown unless it was in a VERY tight loop and the copied structures were large.

...actually, there is a difference if you count the number of if statements that will be executed. I am skeptical that would make a huge difference, but I suppose it's possible.

**Comment by davidopp** [comment] 2016-01-22 22:51
@hongchaodeng can you or @xiang90 send a revert PR for now, and then do some experimentation before re-introducing it?

**Comment by hongchaodeng** [comment] 2016-01-22 23:03
I would verify that if the revert helps fixing the problem.

At the mean time, it reminds me that we should probably get benchmarking into jenkins test to prevent any regression in PR. That's a more effective way to look at commits and manual alerts.

**Comment by xiang90** [comment] 2016-01-22 23:10
@hongchaodeng I agree, I think we should run the scheduler performance test to prevent regression.

**Comment by hongchaodeng** [comment] 2016-01-22 23:54
I just did some experiments and found some facts:
 
- The 5k pods stuck point couldn't be reproduced in scheduler benchmark tool. This means that the scheduler could still schedule things. But what happened in Kubemark? There are many vectors that can have scalability problems.
- Although the Kubemark got stuck recently, I found that the regression happened quite some time ago. Only by resetting to a early Jan commit can I have the same scheduling rate as Dec.

So there are two problems: system gets stuck; regression happened before it.

**Comment by xiang90** [comment] 2016-01-22 23:59
@hongchaodeng Are you saying #18452 might not be the cause?

**Comment by hongchaodeng** [comment] 2016-01-23 00:57
I tried reverting it and then ran Kubemark density test. The system still gets stuck at 5k pods.

**Comment by davidopp** [comment] 2016-01-23 07:16
OK I'll close #18452; thanks for testing. It would be great if you guys can try to track down what caused the regression. Marek and Wojtekt are out all next week.

**Comment by davidopp** [comment] 2016-01-23 07:17
Oops, I forgot I had manually merged 18452. I'll un-revert later.

**Comment by hongchaodeng** [comment] 2016-01-23 07:33
Hi @davidopp ,
Sure. I will dig into Kubemark and figure out what stuck.

**Comment by hongchaodeng** [comment] 2016-01-25 04:49
I have done the following and found some evidence:

- First of all, it's not only the scheduler that "look" stuck. Scheduler stuck at scheduling, meanwhile scheduled pods also stuck in being run.
- When Kubemark got stuck, I checked api server metrics. Both rest request and scheduler metrics look normal.
- Finally, I checked in the scheduler log. I found the following:
```
type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods
```
- Then I print out how many nodes that the scheduler has. The number of nodes keeps decreasing until 0.

In Kubemark, we have developed and used [HollowKubelet](https://github.com/kubernetes/kubernetes/blob/059c2aa7991060890fbd68493be3acc0c4d6a181/pkg/kubemark/hollow_kubelet.go#L35-L35). I guess there might be inconsistent change in node. But I need help from node team and verify this.

/cc @jonboulle @yifan-gu @kubernetes/sig-scalability

**Comment by hongchaodeng** [comment] 2016-01-25 05:03
More info:
The scheduler gets node info from [here](https://github.com/kubernetes/kubernetes/blob/080cb60dab7dcdddf22bd658b8f443b2fd2af1b9/plugin/pkg/scheduler/factory/factory.go#L215).
It's basically a cache store that uses reflector to watch and update changes.

**Comment by hongchaodeng** [comment] 2016-01-25 19:26
@yifan-gu and I have fixed the problem.

The root cause happened in inconsistent change in fake docker client. In Kubemark, Docker client kept failing and showed following errors in logs:
```
docker: failed to parse docker server version "": Unable to parse version ""
```
It came from [DockerManager#Version()](https://github.com/kubernetes/kubernetes/blob/2ad642d37004b575654a0de7917fb205da8670c5/pkg/kubelet/dockertools/manager.go#L986-L986). The version couldn't be parsed because in HollowNode VersionInfo is overwritten. See [here](https://github.com/kubernetes/kubernetes/blob/90ac50852440d6fcde17a0f9f987137d1981d1a9/cmd/kubemark/hollow-node.go#L100).

I'm surprised that Kubelet can run so long before it realized that docker client failed.

The fix is simple, we shouldn't remove the Version -- either by overwriting ApiVersion or having Version added in.

**Comment by timothysc** [comment] 2016-01-25 19:32
xref: https://github.com/kubernetes/kubernetes/pull/20020

**Comment by lavalamp** [comment] 2016-01-25 20:31
Awesome, thanks!

**Comment by fgrzadkowski** [comment] 2016-01-28 16:35
@hongchaodeng Does it mean we can close this issuse?

**Comment by hongchaodeng** [comment] 2016-01-28 16:54
@fgrzadkowski 
Yes. I confirm it's fixed now.

**Comment by fgrzadkowski** [comment] 2016-01-28 18:02
Great! Thank you!

**Closed by fgrzadkowski** 2016-01-28 18:02 UTC
Labels: area/performance, priority/P0, team/control-plane

**Comment by davidopp** [comment] 2016-01-28 18:44
+1 -- thanks a lot!
