### ISSUE TITLE
Set TerminatedPodGCThreshold based on master size

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22680] opened 2016-03-08 01:35 UTC
12500 might be too large for, say, an n1-standard-4 master which has 3G of ram (i.e I don't think the estimate of: an object+metadata needed by etcd + duplication in apiserver cache = 256k is always going to be accurate). I think we came across a case where just 10,000 failed pods were enough to oom master components. Obviously 10,000 non-terminated pods can still oom it, but that's a DOS issue (https://github.com/kubernetes/kubernetes/issues/22679).

**Comment by davidopp** [comment] 2016-03-08 01:42
cc/ @mikedanese

**Comment by davidopp** [comment] 2016-03-08 01:42
ref/ #7660

**Comment by bprashanth** [comment] 2016-03-11 22:29
Apparently this bites us more often than we thought with the smallest master size @kubernetes/goog-gke 
I think we can simply bump it down to something like 5000?

**Comment by roberthbailey** [comment] 2016-03-11 23:13
Do we want to scale it based on master size or just set a lower threshold for all masters?

**Comment by bprashanth** [comment] 2016-03-12 00:02
Yeah bumping it down to something like 5000 might just make more sense. I suppose we want to make sure the gc isn't too aggressive and cleaning up failed pods in large ish clusters in 10h/overnight.

**Comment by gmarek** [comment] 2016-07-06 06:49
We also need to make sure that Jobs don't loose successes/failures if we GC their pods. Ref. #28486

cc @soltysh @erictune @wojtek-t

**Comment by wojtek-t** [comment] 2016-07-06 07:01
I have a counter proposal to scaling it based on master size.
Can't we just adjust it dynamically during runtime, based on the number of nodes in the cluster?

**Comment by gmarek** [comment] 2016-07-06 07:31
We can, but why should it be a function of number of Nodes? Reason for it being a function of master size is that it causes a memory problem on master if set too high.

**Comment by wojtek-t** [comment] 2016-07-06 07:39
Yeah - but master size should depend on the number of nodes. And you can't get master size from anywhere (instead of startup scripts). And you can get number of nodes during runtime, which will allow you to adjust the value of this flag during runtime.

**Comment by gmarek** [comment] 2016-07-06 08:10
I thought about doing it in the startup scripts, similarly to how we set heapster resources - we should have master size there. If we do it dynamically we probably need to expose the flag that will disable dynamic behavior, as I imagine some admins might want to have full control over this value.

**Comment by wojtek-t** [comment] 2016-07-06 08:30
Is there currently a flag to control it?

**Comment by gmarek** [comment] 2016-07-06 08:38
Yup - it's `TerminatedPodGCThreshold`.

**Comment by lavalamp** [comment] 2016-07-06 20:00
https://github.com/kubernetes/kubernetes/issues/25831

**Comment by bprashanth** [comment] 2016-09-16 01:24
@timstclair complained about abrnomal sluggishness in a 1.4 cluster loaded with failed pods

**Comment by gmarek** [comment] 2016-09-16 11:41
Yeah - it's pretty low hanging fruit, but it seems that no one had time to pick it up:/

**Comment by dims** [comment] 2016-11-16 14:20
This needs to be triaged as a release-blocker or not for 1.5 @gmarek

**Comment by gmarek** [comment] 2016-11-16 15:48
Ugh... I strongly believe we should do this, but it fell of everyone's radar. Again. Sad thing is that it actually causes problems, so I'm all for making it a release blocker with a hope that someone will find time to do this:/

**Comment by dims** [comment] 2016-11-16 15:50
@gmarek : which SIG should we ping?

**Comment by gmarek** [comment] 2016-11-16 15:57
@dims - that's a great question... It's a PodGC thing, so maybe @kubernetes/sig-api-machinery ?

**Comment by dims** [comment] 2016-11-16 16:02
@gmarek ack. let's wait to hear from them :)

**Comment by caesarxuchao** [comment] 2016-11-16 18:02
cc @foxish

**Comment by wojtek-t** [comment] 2016-11-16 18:06
Isn't it already done?

**Comment by wojtek-t** [comment] 2016-11-16 18:07
Ohh maybe not - I think we changed something different (I think it was size of deserialization cache).

**Comment by deads2k** [comment] 2016-11-16 18:29
> Ugh... I strongly believe we should do this, but it fell of everyone's radar. Again. Sad thing is that it actually causes problems, so I'm all for making it a release blocker with a hope that someone will find time to do this:/

Isn't this wired to `--terminated-pod-gc-threshold` for the controller manager, which could be used to keep it under control for the cluster?  It would be nice to have it auto-tune itself, but I if I'm looking at the right thing I don't think its a release blocker.

**Comment by wojtek-t** [comment] 2016-11-16 18:54
>
Isn't this wired to --terminated-pod-gc-threshold for the controller manager, which could be used to keep it under control for the cluster?

I'm afraid I don't understand this.

>
It would be nice to have it auto-tune itself, 

+1

>
but I if I'm looking at the right thing I don't think its a release blocker.

I think I agree - this is not a regression and we can live with it I guess.

**Comment by gmarek** [comment] 2016-11-16 20:01
I'm not sure - we saw clusters that were dying because of this problem, but if you don't think it's serious enough we can push it for 1.6.

We can probably have the --terminated-pod-gc-threshold automatically set taking into account amount of memory on the master machine. I'm not sure what's the best way to do it though (we can probably add some syscalls to the API server, and if we're running on linux-like system we might have `free` installed).

**Comment by lavalamp** [comment] 2016-11-16 22:38
I don't think this is a release blocker.

**Comment by gmarek** [comment] 2016-11-17 06:59
@dims OK. The impact of this problem is that master components will OOM if not configured correctly (user can specify the `--terminated-pod-gc-thershold` flag himselff). This is not a huge deal as log as user can live with an API server/CM reboot (read: HA is not a high priority for her).

**Comment by dims** [comment] 2016-11-17 10:58
Ack @gmarek thanks for the update

**Comment by foxish** [comment] 2016-11-17 16:46
This is something we should do for 1.6 I think. The currently specified default is unreasonably high.
It should also obviate the need for https://github.com/kubernetes/kubernetes/pull/32858.

**Comment by icambridge** [comment] 2017-02-19 19:15
So is this being worked on? If not I would like to help. It looks like a nice easy task to get into kubernetes development, but I am not actually sure what solution has been chosen. Is it going to be set it dynamically by the number of nodes or is it going to be done in the set up scripts?

**Comment by ethernetdan** [comment] 2017-03-13 22:55
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment] 2017-05-31 20:22
@kubernetes/sig-scalability-misc do we want this in for v1.7? is this the right sig to own this issue?

**Closed** 2019-09-04 03:50 UTC
Labels: help wanted, lifecycle/rotten, sig/scalability
