### ISSUE TITLE
`kubelet_pod_start_sli_duration_seconds_sum` getting negative values

### ISSUE THREAD

**Issue by MPV** [kubernetes/kubernetes#122675] opened 2024-01-10 08:54 UTC
### What happened?

We wanted to start using the SLI for kubelet pod start duration, as per:
- https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md
- https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md#steady-state-slisslos
- https://github.com/kubernetes/community/pull/2204
- https://github.com/kubernetes/kubernetes/pull/111930

...but it turns out that it seems to report unexpected/unusable **negative** values in the `sum` metric of the histogram, i.e:
`kubelet_pod_start_sli_duration_seconds_sum`

### What did you expect to happen?

As it's a duration, only positive values would be expected.

### How can we reproduce it (as minimally and precisely as possible)?

`count(kubelet_pod_start_sli_duration_seconds_sum < 0) / count(kubelet_pod_start_sli_duration_seconds_sum)` is `1` over time, i.e. all values are negative.

For example:
`rate(kubelet_pod_start_sli_duration_seconds_sum[10m])` gives negative durations:
><img width="1060" alt="Skärmavbild 2024-01-10 kl  09 35 23" src="https://github.com/kubernetes/kubernetes/assets/62675/1be54f59-a855-4379-9e6a-55d96dd1c6a7">

### Anything else we need to know?

Let me know if there's any more context I can provide so we can understand this better.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:12Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Cluster API OpenStack
</details>

**Comment by MPV** [comment] 2024-01-10 08:57
I've tried looking for existing same/similar issues. The closest I've found is this one reported by @aojea
- https://github.com/kubernetes/kubernetes/issues/114903

...which was fixed by @TommyStarK in:
- https://github.com/kubernetes/kubernetes/pull/114904

Would you be up for taking a peek @TommyStarK @aojea (as you worked on those issues/fixes)?

**Comment by TommyStarK** [comment] 2024-01-10 11:19
Sure I can give it a try
/assign

**Comment by MPV** [comment] 2024-01-11 14:25
I can confirm that by upgrading from k8s 1.26 to 1.27 I am no longer getting this issue, hence it seems it was fixed in the issue and PR found and linked above.

Should we close this one?

**Comment by TommyStarK** [comment] 2024-01-11 14:31
Yes if you are not able to reproduce the bug with 1.27
/unassign

**Comment by dashpole** [comment] 2024-01-11 17:34
Closing based on https://github.com/kubernetes/kubernetes/issues/122675#issuecomment-1887298106
/close

**Closed** 2024-01-11 17:34 UTC
Labels: kind/bug, sig/node, sig/instrumentation, needs-triage
