### ISSUE TITLE
When kubelet runs with --register-node=false and runs static pods, controller-manager tries to delete them regulary

### ISSUE THREAD

**Issue by codablock** [kubernetes/kubernetes#38187] opened 2016-12-06 11:44 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "static pod orphaned" and "static pod register-node"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.5.0-beta.2

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux master-1 4.8.11-1.el7.elrepo.x86_64 #1 SMP Sat Nov 26 11:13:42 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kargo (+custom changes)
- **Others**:

**What happened**:
The controller-manager logs repeatedly show that it deleted orphaned pods which belong to the static pods of kubelets which have "--register-node=false" set:

```
I1206 11:31:14.941598       1 gc_controller.go:184] Found orphaned Pod kube-controller-manager-master-1 assigned to the Node master-1. Deleting.
I1206 11:31:14.941605       1 gc_controller.go:71] PodGC is force deleting Pod: kube-system:kube-controller-manager-master-1
I1206 11:31:15.425141       1 gc_controller.go:188] Forced deletion of orphaned Pod kube-controller-manager-master-1 succeeded
```

The pods/containers are not really deleted. It looks like only the "mirror" PODs are deleted and later readded. But I'm not sure about this as I did not dig into mirror PODs that deep.

The POD status seems to be jumping from "Running" to "Pending" and back after every few seconds.

**What you expected to happen**:
I'd expect that the gc_controller would ignore static/mirror PODs in this case. I'm not sure how GC should work here in case the source kubelet dies as we don't have node status here.

**How to reproduce it** (as minimally and precisely as possible):
Run a kubelet with "--register-node=false" and add some static PODs/manifests. kargo for example does this at the moment. 

**Anything else do we need to know**:

**Comment by pigmej** [comment] 2016-12-06 13:34
@dims @saad-ali @kubernetes/sig-node  I think it should be release-blocker bug.

**Comment by dims** [comment] 2016-12-06 14:31
cc @saad-ali

**Comment by dims** [comment] 2016-12-06 14:33
@pigmej Is there anyone working on this issue?

**Comment by pigmej** [comment] 2016-12-06 14:42
@dims 
@ivan4th or @lukaszo could work on it. We will figure out ;-)

(cc @kubernetes/mirantis)

**Comment by dims** [comment] 2016-12-06 14:46
Assigned to both. Please make sure anyone working on this attend the Burndown meeting today

https://groups.google.com/d/msg/kubernetes-dev/mvIXrgEyHPY/EPyasKZaDAAJ

**Comment by mikedanese** [comment] 2016-12-06 21:29
What is the master kubelet's command line?

**Comment by euank** [comment] 2016-12-06 21:32
Since kargo was referenced, it looks like it's coming from https://github.com/kubernetes-incubator/kargo/blob/8870178a2d162b78ed6992e391f40ab0cba5867e/roles/kubernetes/node/templates/kubelet.j2#L15-L17

Should that not be `register-schedulable=false` instead of `register-node`? 

IIUC standalone kubelet is deprecated, and operating badly when `register-node=false` but the node object isn't created out-of-band basically sounds like expected behavior, unless I'm missing something.

**Comment by saad-ali** [comment] 2016-12-06 21:39
@yujuhong can you please help with the investigation and any fix please

**Comment by roberthbailey** [comment] 2016-12-06 21:39
@euank -- why do you think that standalone kubelet is deprecated? That's how we run it in GKE. 

GCE/GKE uses `register-schedulable=false` (see https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L509 and https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kubelet/default#L36) if you don't have the master configured to join the cluster. 

This looks like a kargo issue and not a release blocker.

**Comment by roberthbailey** [comment] 2016-12-06 21:42
Sorry, my last comment was incorrect. When running in the mode where the kubelet should be part of the cluster, we pass `register-schedulable=false` (so that nothing gets scheduled to the master node). When running in standalone mode we don't pass `--api-servers` at all, which prevents the kubelet from registering. 

What is the behavior that you are looking for?

**Comment by mikedanese** [comment] 2016-12-06 21:43
If you use `register-node=false`, you shouldn't be passing a kubeconfig to the kubelet or using --require-kubeconfig.

**Comment by mikedanese** [comment] 2016-12-06 21:45
We should mark `--register-node` as deprecated because it's essentially redundant to `len(apiservers) != 0` and kubelet expects those two conditions to be equal.

**Comment by lukaszo** [comment] 2016-12-06 21:47
The strange thing is that even the register-node == false kubelet still sends node status https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L285-L296

**Comment by mikedanese** [comment] 2016-12-06 21:49
I don't know why --register-node exists or if it's ever been tested... It's functionality looks very broken. If a node isn't meant to register, it just shouldn't create a client to the apiserver.

**Comment by euank** [comment] 2016-12-06 21:51
@mikedanese with some digging, I found that apparently it can be used to manually create the `node` object with a separate non-kubelet api client, and then have the kubelet operate as part of the cluster.

**Comment by mikedanese** [comment] 2016-12-06 21:54
Ahh, I remember when we used to do that back in 0.4.2... In which case this is a kargo bug that is fixed by not passing `--kubeconfig --require-kubeconfig` to the master kubelet if they don't want that kubelet to register. If they do want that kubelet to register, they need to either create the master node manually or pass `--register-node=true`. This seems to be working as intended?

**Comment by lukaszo** [comment] 2016-12-06 22:12
@mikedanese does it require any changes though?

**Comment by mikedanese** [comment] 2016-12-06 22:26
Not in kubernetes.

**Closed** 2016-12-06 22:47 UTC
Labels: component/kubelet, team/node

**Comment by pigmej** [comment] 2016-12-06 22:52
@mikedanese I think it require at least mention in docs. It may lead to unexpected behavior.

**Comment by mikedanese** [comment] 2016-12-06 22:53
http://kubernetes.io/docs/admin/node/#manual-node-administration seems like the right place and explores this topic thoroughly. Where else should we mention this?

**Comment by euank** [comment] 2016-12-06 22:53
@pigmej documented http://kubernetes.io/docs/admin/node/#manual-node-administration

Maybe there's other places it should be documented better.

Someone should definitely be opening an issue kargo side

**Comment by mattymo** [comment] 2016-12-07 07:28
@mikedanese thanks for clearing up how to create a kubelet that is not part of the cluster, does not register itself, and does not run static pods. In summary:
K8s master-only components kubelet config:
no --apiserver
no --kubeconfig
no --require-kubeconfig
no --register-node
no --register-unschedulable

Contrary to popular belief, the last 2 options above are not useful for creating an unschedulable master that should not run pods.

This is not a Kargo only issue. It was just discovered there. I'm sure others will run into this sooner or later.

**Comment by pigmej** [comment] 2016-12-07 09:06
Yeah, I agree with Matthew there. I've read the docs and found nothing that would mention unexpected behavior caused by mixing options‎, especially that it worked before 1.5 so many may be surprised with this behavior change (even if the previous one was incorrect).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Matthew MosesohnSent: środa, 7 grudnia 2016 08:28To: kubernetes/kubernetesReply To: kubernetes/kubernetesCc: Jędrzej Nowak; MentionSubject: Re: [kubernetes/kubernetes] When kubelet runs with --register-node=false and runs static pods, controller-manager tries to delete them regulary (#38187)@mikedanese thanks for clearing up how to create a kubelet that is not part of the cluster, does not register itself, and does not run static pods. In summary:
K8s master-only components kubelet config:
no --apiserver
no --kubeconfig
no --require-kubeconfig
no --register-node
no --register-unschedulable
Contrary to popular belief, the last 2 options above are not useful for creating an unschedulable master that should not run pods.
This is not a Kargo only issue. It was just discovered there. I'm sure others will run into this sooner or later.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes/kubernetes","title":"kubernetes/kubernetes","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes/kubernetes"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mattymo in #38187: @mikedanese thanks for clearing up how to create a kubelet that is not part of the cluster, does not register itself, and does not run static pods. In summary:\r\nK8s master-only components kubelet config:\r\nno --apiserver\r\nno --kubeconfig\r\nno --require-kubeconfig\r\nno --register-node\r\nno --register-unschedulable\r\n\r\nContrary to popular belief, the last 2 options above are not useful for creating an unschedulable master that should not run pods.\r\n\r\nThis is not a Kargo only issue. It was just discovered there. I'm sure others will run into this sooner or later."}],"action":{"name":"View Issue","url":"https://github.com/kubernetes/kubernetes/issues/38187#issuecomment-265376005"}}}‎

**Comment by mattymo** [comment] 2016-12-07 10:08
@mikedanese will kubeadm follow suit? Currently it uses taints to make master node unschedulable, but that will not work for daemonsets because of this reverted patch:
https://github.com/kubernetes/kubernetes/pull/31907#issuecomment-265382450

**Comment by mikedanese** [comment] 2016-12-07 15:29
What solution are you proposing? Better documentation? We can't change the behavior as it's working as it was intended to work and we can't break compatibility.

> create a kubelet that is not part of the cluster, does not register itself, and does not run static pods.

A standalone kubelet still runs static pods.

> Contrary to popular belief, the last 2 options above are not useful for creating an unschedulable master that should not run pods.

I don't understand this statement.

> it worked before 1.5 so many may be surprised with this behavior change (even if the previous one was incorrect).

Are you sure about this? This looks like it's the same behavior as always.

**Comment by ivan4th** [comment] 2016-12-07 15:59
I suspect that in 1.4 pod GC was working in a bit different manner (see https://github.com/kubernetes/kubernetes/blame/ce93c81029a6de1263715ea655d53756bc692e88/pkg/controller/podgc/gc_controller.go#L155), so the issue was less obvious because gc was either deleting mirror pods less often or was not deleting them at all. So kubelet behavior didn't change in this respect, it was always incorrect with this set of options, but the negative side-effects were probably less obvious.

**Comment by mikedanese** [comment] 2016-12-07 16:11
The node controller was responsible for this in v1.4. https://github.com/kubernetes/kubernetes/blob/v1.4.6/pkg/controller/node/controller_utils.go#L45, it's possible that the gc controller acts with lower latency.

**Comment by mattymo** [comment] 2016-12-07 16:15
@mikedanese What is the plan for kubeadm (or any other deployment tool) for 1.5? Register master node + taint or don't register master node?

**Comment by ivan4th** [comment] 2016-12-07 16:31
> it's possible that the gc controller acts with lower latency.

Yes, it's probably due to #37365
