### ISSUE TITLE
[Flaky test] [sig-auth] Metadata Concealment should run a check-metadata-concealment job to completion

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#98182] opened 2021-01-19 15:26 UTC
**Which jobs are flaking**:
`gce-master-scale-correctness`

**Which test(s) are flaking**:
`[sig-auth] Metadata Concealment should run a check-metadata-concealment job to completion`

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness

Failed job run URL: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1351499903934664704

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/metadata_concealment.go:34
Jan 19 12:34:04.906: failed to ensure job completion (metadata-concealment-4694:check-metadata-concealment)
Unexpected error:
    <*errors.errorString | 0xc00024e200>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/metadata_concealment.go:63
```

**Anything else we need to know**:
/kind flake
/sig scalability
/sig auth
/cc @kubernetes/sig-auth-bugs

**Comment by liggitt** [comment] 2021-01-19 16:09
There's a long trail of timeout failures on unrelated tests for this job ... is this an indication of a regression or load issue unrelated to this particular test?

**Comment by liggitt** [comment] 2021-01-19 16:09
cc @kubernetes/sig-scalability

**Comment by mm4tt** [comment] 2021-01-20 08:24
I haven't dug into this particular test failure, but in general a lot of timeouts in this job occur because the tests weren't designed to be run at this scale. E.g. there were tests trying to do something for every node which obviously is not going to work at 5k node scale. Other examples are things that just take longer for larger clusters, e.g. LB programming time depends on the number of nodes in cluster. 

We'd appreciate if someone from SIG auth would take a look and let us know whether this failure might be scale related (and the test could be rewritten to take that into account) or whether it might suggest a regression in the code. This correctness test suite runs over 800 tests and SIG scalability is simply not able to debug every test failure.

**Comment by pacoxu** [comment] 2021-01-20 09:12
Not sure whether it is related to #97789. There are many legacy endpoints that should be removed.

**Comment by liggitt** [comment] 2021-01-20 14:30
I don't see anything in that test that would be impacted by scale/number of instances. It is running a job with a single pod, which checks metadata endpoints which would not be different with a large number of instances.

**Comment by thejoycekung** [comment] 2021-01-25 15:54
Another failed job run here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1353577504081711104

**Comment by wojtek-t** [comment] 2021-01-25 18:38
Which shows it's clearly not-scalability related.

**Comment by liggitt** [comment] 2021-03-18 23:55
Looks like it's pretty solidly failing on other release branches as well - https://github.com/kubernetes/kubernetes/pull/100380#issuecomment-802382245

did something get fixed in master and not propagated to release branches?

**Comment by mikedanese** [comment] 2021-03-19 16:07
I think we need to cherry pick this:

https://github.com/kubernetes/kubernetes/commit/f85cbdb410d9c3ce26ad6527eb775f6a88554221

**Comment by mikedanese** [comment] 2021-03-19 17:05
I ran the cherry pick in https://github.com/kubernetes/kubernetes/pull/100407 manually and it seemed to do the trick.

**Closed** 2021-04-08 18:25 UTC
Labels: kind/bug, kind/flake, needs-triage, sig/auth, sig/scalability

**Comment by liggitt** [comment] 2021-04-26 17:43
history looks good: https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness&include-filter-by-regex=Metadata%20Concealment&width=5
