### ISSUE TITLE
"[sig-node] [Feature:StandaloneMode] when creating a static pod the pod should be running" test failing

### ISSUE THREAD

**Issue by haircommander** [kubernetes/kubernetes#127814] opened 2024-10-02 17:07 UTC
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-containerd-standalone-mode-all-alpha

### Which tests are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-e2e-containerd-standalone-mode-all-alpha/1840133214228713472

### Since when has it been failing?

9/28

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-e2e-containerd-standalone-mode-all-alpha/1840133214228713472

### Reason for failure (if possible)

looks like static pods aren't coming up right

### Relevant SIG(s)

/sig node

**Comment by AnishShah** [comment] 2024-10-04 18:14
Failure message:

```
{ failed [FAILED] Timed out after 300.001s.
Expected
    <*errors.errorString | 0xc000032b20>: 
    error checking if pod (static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0) is running ready: pod 'static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' on 'tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:45 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  }]
    {
        s: "error checking if pod (static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0) is running ready: pod 'static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' on 'tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:45 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  }]",
    }
to be nil
```

regression window: https://github.com/kubernetes/kubernetes/compare/80941e3e8...dad39bf43

I see a few changes related to error handling which might be related

**Comment by AnishShah** [comment] 2024-10-04 18:17
@mmorel-35 can you take a look at this test failure? It might be a regression due to your error handling changes?

**Comment by aojea** [comment] 2024-10-05 11:48
Interesting, this only fails in alpha https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-containerd-standalone-mode-all-alpha

does not fail in the other job https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-containerd-standalone-mode

Checking https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-e2e-containerd-standalone-mode-all-alpha/1840133214228713472

The tests times out because the pod is not able to get running in 300s

```
> Enter [It] the pod should be running - k8s.io/kubernetes/test/e2e_node/standalone_test.go:54 @ 09/28/24 21:09:40.841
[FAILED] Timed out after 300.001s.
Expected
    <*errors.errorString | 0xc000032b20>: 
    error checking if pod (static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0) is running ready: pod 'static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' on 'tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:45 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  }]
    {
        s: "error checking if pod (static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0) is running ready: pod 'static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' on 'tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:45 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC ContainersNotReady containers with unready status: [regular1]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-28 21:09:40 +0000 UTC  }]",
    }
to be nil
In [It] at: k8s.io/kubernetes/test/e2e_node/standalone_test.go:76 @ 09/28/24 21:14:40.859
```

I don't see changes on the kubelet or the e2e_node

The pod seems to be created, the problem seems to be on the container

> ContainersNotReady containers with unready status: [regular1]}

The kubelet logs https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-e2e-containerd-standalone-mode-all-alpha/1840133214228713472/artifacts/tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80/kubelet.log

> 0928 21:09:42.369544    1787 event.go:389] "Event occurred" object="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80" fieldPath="spec.containers{regular1}" kind="Pod" apiVersion="v1" type="Normal" reason="Pulled" message="Container image \"registry.k8s.io/e2e-test-images/busybox:1.36.1-1\" already present on machine"

> I0928 21:09:42.589778    1787 event.go:389] "Event occurred" object="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80" fieldPath="spec.containers{regular1}" kind="Pod" apiVersion="v1" type="Normal" reason="Started" message="Started container regular1"

It seems the exec probe succeeds

> I0928 21:09:45.423096    1787 kubelet.go:2530] "SyncLoop (probe)" probe="readiness" status="not ready" pod="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80"
I0928 21:09:45.422921    1787 prober.go:140] "Exec-Probe runProbe" pod="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80" containerName="regular1" execCommand=["/bin/sh","-c","cat /tmp/healthy"]

> I0928 21:09:45.486707    1787 prober.go:116] "Probe succeeded" probeType="Readiness" pod="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80" podUID="63a2eeabda8b093d2aa1853e5a20a4ea" containerName="regular1"

but then the container enters in a loop of not ready state 

> I0928 21:12:19.342173    1787 status_manager.go:691] "Ignoring same status for pod" pod="static-pod-8897/static-pod-64756837-f28a-43dc-a237-e692e6f66dc0-tmp-node-e2e-7f6c8fe9-cos-stable-113-18244-151-80" status={"phase":"Running","conditions":[{"type":"PodReadyToStartContainers","status":"True","lastProbeTime":null,"lastTransitionTime":"2024-09-28T21:09:45Z"},{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2024-09-28T21:09:40Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2024-09-28T21:09:40Z","reason":"ContainersNotReady","message":"containers with unready status: [regular1]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2024-09-28T21:09:40Z","reason":"ContainersNotReady","message":"containers with unready status: [regular1]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2024-09-28T21:09:40Z"}],"podIP":"10.100.0.2","podIPs":[{"ip":"10.100.0.2"}],"startTime":"2024-09-28T21:09:40Z","containerStatuses":[{"name":"regular1","state":{"waiting":{"reason":"ContainerCreating"}},"lastState":{"terminated":{"exitCode":137,"reason":"ContainerStatusUnknown","message":"The container could not be located when the pod was deleted.  The container used to be Running","startedAt":null,"finishedAt":null}},"ready":false,"restartCount":1,"image":"registry.k8s.io/e2e-test-images/busybox:1.36.1-1","imageID":"","started":false}],"qosClass":"Burstable"}


I'm not familiar with this test, it seems the exec probe is only executed once 🤔 

If the code changes in kubernetes are not the problem, we need to check if is possible some external dependency gots updated

**Comment by kannon92** [comment] 2024-10-14 15:00
I looked at the logs and I saw that EventedPleg was right before the pod was killed.

@pacoxu had a similar idea it seems. It looks like EvictedPleg was causing this failure.

**Comment by kannon92** [comment] 2024-10-14 15:00
@hshiina any ideas here?

**Comment by hshiina** [comment] 2024-10-14 18:52
> @hshiina any ideas here?

Does this job build containerd from the master? If so, this issue may be caused by containerd/containerd#10740 regarding EventedPLEG, which adds a timestamp for Generic PLEG ([KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3386-kubelet-evented-pleg/README.md#timestamp-of-the-pod-status)). kubelet converts this nanosecond-timestamp into seconds. This is being fixed by #127195. If generic PLEG sets this large wrong value to the cache, updates by Evented PLEG will be rejected because timestamps by Evented PLEG look older. So, a container status may get stuck and the static pod may not get in the expected status.

**Comment by pacoxu** [comment] 2024-10-15 08:12
I fixed the presubmit one by https://github.com/kubernetes/test-infra/pull/33642.

**Comment by kannon92** [comment] 2024-10-15 20:20
@hshiina I don't think we build containerd from master in these jobs. I think we pick a release of containerd.

**Closed** 2024-10-15 20:31 UTC
Labels: sig/node, kind/failing-test, needs-triage
