### ISSUE TITLE
[job failure] kubeadm-gce

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56091] opened 2017-11-20 20:38 UTC
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
@kubernetes/sig-cluster-lifecycle-test-failures 

This job has been failing since 2017-11-15.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/8585
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/8586
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/8795

**Comment by dims** [comment] 2017-11-20 21:24
@luxas @spiffxp here's the tentative plan - https://github.com/kubernetes/kubeadm/issues/256#issuecomment-345544237

**Comment by luxas** [comment] 2017-11-20 21:33
@spiffxp yes, the PR that fixed the root cause (https://github.com/kubernetes/kubernetes-anywhere/pull/483) just merged. Sorry for the long approving window there. Now we're about to bump the git sha pinning for the job: https://github.com/kubernetes/test-infra/blob/master/images/kubeadm/runner#L29 to make the test green

**Comment by luxas** [comment] 2017-11-21 22:32
Status update: https://github.com/kubernetes/test-infra/pull/5610 went in yesterday
The actual test-infra image bump got merged now https://github.com/kubernetes/test-infra/pull/5636, so the tests should start passing soon-ish

**Comment by xiangpengzhao** [comment] 2017-11-23 06:40
The https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce still fails after https://github.com/kubernetes/test-infra/pull/5636 merged.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/8906/artifacts/e2e-8906-node-vcw7/startupscript.log
shows:
```
Nov 23 05:13:24 ubuntu startupscript: kubeadm join --token "$KUBEADM_TOKEN" "$KUBEADM_MASTER_IP:443" --skip-preflight-checks --discovery-token-unsafe-skip-ca-verification true
Nov 23 05:13:24 ubuntu startupscript: + kubeadm join --token 043479.1a6ec0adafb593d0 10.128.0.2:443 --skip-preflight-checks --discovery-token-unsafe-skip-ca-verification true
Nov 23 05:13:25 ubuntu startupscript: Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-checks-errors=all
Nov 23 05:13:25 ubuntu startupscript: [kubeadm] WARNING: kubeadm is currently in beta
Nov 23 05:13:25 ubuntu startupscript: [preflight] Running pre-flight checks.
Nov 23 05:13:25 ubuntu startupscript: #011[WARNING FileExisting-crictl]: crictl not found in system path
Nov 23 05:13:25 ubuntu startupscript: [validation] WARNING: kubeadm doesn't fully support multiple API Servers yet
Nov 23 05:13:25 ubuntu startupscript: discovery: Invalid value: "true": address true: missing port in address
Nov 23 05:13:25 ubuntu startupscript: Finished running startup script /var/run/google.startup.script
```

Seems like param ` --discovery-token-unsafe-skip-ca-verification true` is incorrect. Just pass ` --discovery-token-unsafe-skip-ca-verification` would be OK. I will fix it.

I have a question here, for such bool type param, will only this format `with just the param name means true, without the param defaults to false or it's default value` be allowed?

**Comment by luxas** [comment] 2017-11-23 07:06
Yes, only the param will mean true by default. Thanks for fixing!

**Comment by xiangpengzhao** [comment] 2017-11-23 09:07
This needs two follow-up PRs like https://github.com/kubernetes/test-infra/pull/5610 and https://github.com/kubernetes/test-infra/pull/5636 after https://github.com/kubernetes/kubernetes-anywhere/pull/488 gets merged.

**Comment by xiangpengzhao** [comment] 2017-11-25 11:24
waiting @pipejakob for https://github.com/kubernetes/kubernetes-anywhere/pull/488 merging.

**Comment by spiffxp** [comment] 2017-11-27 14:07
Now waiting on https://github.com/kubernetes/kubernetes-anywhere/pull/491

**Comment by luxas** [comment] 2017-11-27 22:56
I merged the required PRs and updated test-infra together with @BenTheElder, hopefully we should start seeing green runs now :)

**Comment by xiangpengzhao** [comment] 2017-11-28 01:33
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce is green now. The [node log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/9124/artifacts/e2e-9124-node-zrqn/startupscript.log) shows that the flag is passed correctly. Thanks @shashidharatd ! Awesome!

**Comment by luxas** [comment] 2017-11-28 09:51
Closing this as the job is now green

**Closed by luxas** 2017-11-28 09:51 UTC
Labels: kind/bug, priority/critical-urgent, priority/failing-test, sig/cluster-lifecycle, status/approved-for-milestone, status/in-progress
