### ISSUE TITLE
kubectl exec works significantly slower on 1.2

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#23675] opened 2016-03-31 12:52 UTC
For small processes like /bin/bash or even irb I barely see a difference (if at all).
But when I try to open a Clojure REPL (JVM based) on a running code with
`kubectl exec -it my-pod-name lein repl`
It is definitely at least 4 times slower than kubernetes 1.1.3. The difference is from 8 seconds to about 30 seconds which is a lot.

Is it a known issue with kubernetes 1.2?

**Comment by a-robinson** [comment] 2016-03-31 22:39
What environment is your cluster deployed in?

**Comment by erez-rabih** [comment] 2016-04-01 11:02
@a-robinson on AWS

**Comment by a-robinson** [comment] 2016-04-01 15:19
@kubernetes/sig-aws @kubernetes/goog-control-plane

**Comment by ncdc** [comment] 2016-04-01 15:40
@erez-rabih can you gist the output of running `DEBUG=1 kubectl exec ...`?

**Comment by erez-rabih** [comment] 2016-04-01 17:14
@ncdc sure:
```
$ DEBUG=1 kubectl exec -it XXXXXXXXXXXXXX lein repl
2016/04/01 17:06:43 (0xc20825c420) (0xc20826a140) Create stream
2016/04/01 17:06:43 (0xc20825c420) (0xc20826a140) Stream added, broadcasting: 1
2016/04/01 17:06:43 (0xc20825c420) Reply frame received for 1
2016/04/01 17:06:43 (0xc20825c420) (0xc2081b2640) Create stream
2016/04/01 17:06:43 (0xc20825c420) (0xc2081b2640) Stream added, broadcasting: 3
2016/04/01 17:06:43 (0xc20825c420) Reply frame received for 3
2016/04/01 17:06:43 (0xc20825c420) (0xc20826a1e0) Create stream
2016/04/01 17:06:43 (0xc20825c420) (0xc20826a1e0) Stream added, broadcasting: 5
2016/04/01 17:06:43 (0xc20825c420) Reply frame received for 5
2016/04/01 17:06:43 (0xc20825c420) Data frame received for 5
2016/04/01 17:06:43 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:08:59 (0xc20825c420) Data frame received for 5
2016/04/01 17:08:59 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:08:59 (0xc20826a1e0) (5) Data frame sent
2016/04/01 17:08:59 (0xc20825c420) Data frame received for 5
2016/04/01 17:08:59 (0xc20826a1e0) (5) Data frame handling
nREPL server started on port 52894 on host 127.0.0.1 - nrepl://127.0.0.1:52894
2016/04/01 17:08:59 (0xc20826a1e0) (5) Data frame sent
2016/04/01 17:09:02 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame sent
2016/04/01 17:09:02 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame handling
REPL-y X.X.X, nREPL 0.X.XX2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame sent

2016/04/01 17:09:02 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame sent
Clojure X.X.0
2016/04/01 17:09:02 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:09:02 (0xc20826a1e0) (5) Data frame sent
OpenJDK 64-Bit Server VM X.X.0_rX-internal-b15
2016/04/01 17:09:04 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:04 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:09:04 (0xc20826a1e0) (5) Data frame sent
Docs: (doc function-name-here)2016/04/01 17:09:04 (0xc20825c420) Data frame received for 5
2016/04/01 17:09:04 (0xc20826a1e0) (5) Data frame handling
2016/04/01 17:09:04 (0xc20826a1e0) (5) Data frame sent
```

**Comment by ncdc** [comment] 2016-04-01 17:23
@erez-rabih it looks like it's taking 2m16s to show you that the REPL server started. How long does it take if you ssh to the node and `docker exec` the same command into the appropriate container?

**Comment by erez-rabih** [comment] 2016-04-01 17:29
@ncdc It actually takes the same amount of time with docker exec from within the node.
The thing is that it worked well with my old 1.1.3 cluster so I wonder what made the change...

**Comment by ravilr** [comment] 2016-04-02 19:26
I've observed this after upgrading to v1.2.0 for containers having low cpu limit set in their pod spec
1.2 enforces cpu cfs quota by default, this wasn't the case before:
https://github.com/kubernetes/kubernetes/pull/19900#issuecomment-173747795

**Comment by davidopp** [comment] 2016-04-03 00:41
@lavalamp

**Comment by davidopp** [comment] 2016-04-03 00:42
@vishh

**Comment by erez-rabih** [comment] 2016-04-03 05:43
@ravilr Thanks for pointing that out.

I can confirm that removing CPU limit from the pod spec solves the problem completely.
I had a CPU limit of 400m. Dropping it reduced the time from 2 minutes 20 seconds to 16 seconds.

**Comment by lavalamp** [comment] 2016-04-05 00:20
I think this is working as intended. @erez-rabih is there any documentation you looked at to try to figure this out? If so, we should consider updating it. Otherwise I think there's no action needed and we can close this?

**Comment by erez-rabih** [comment] 2016-04-05 04:45
@lavalamp Actually I moved to Kubernetes 1.2 thinking everything works as in 1.1 but then when I tried to exec into some of the pods I experienced the slow reaction.
If there was any documentation emphasizing this I probably missed it.

**Comment by davidopp** [comment] 2016-04-05 04:54
The [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v120) say "CPU hardcapping will be enabled by default for containers with CPU limit set, if supported by the kernel. You should either adjust your CPU limit, or set CPU request only, if you want to avoid hardcapping." It doesn't draw a direct connection to kubectl exec, though.

**Comment by erez-rabih** [comment] 2016-04-05 05:01
@davidopp You are right it is listed there. I guess I didn't think the effect would be so drastic.
Thanks for the help, I think we can close this.

**Closed** 2016-04-05 05:59 UTC
Labels: team/ux
