### ISSUE TITLE
Multiple critical builds have started failing (red) with "Not all pods in namespace 'kube-system' running and ready within 10m0s"

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#14968] opened 2015-10-02 06:57 UTC
for example, kubernetes-e2e-gce-slow, kubernetes-e2e-gce-reboot, kubernetes-e2e-gce, kubernetes-e2e-gce-parallel

@jszczepkowski @wojtek-t

**Comment by wojtek-t** [comment] 2015-10-02 06:59
Note that there is always the same pod that is not starting: - it's "kube-registry", e.g.:

    "The status of Pod kube-registry-v0-jls6c is Pending, waiting for it to be either Running or Failed"

**Comment by davidopp** [comment] 2015-10-02 07:10
Good point. It might have the same root cause as #14966.

**Comment by wojtek-t** [comment] 2015-10-02 11:42
It seems that it fixed itself without any intervention.
Did we understand why this happened?

**Comment by jszczepkowski** [comment] 2015-10-02 14:06
I think pod "kube-registry" is not the only offending one. Please examine:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8726/

It seems that in the above run cluster started correctly, but afterwards the problem spreaded across different tests where pods didn't start.

**Comment by jszczepkowski** [comment] 2015-10-02 14:08
Reducing priority to P1:
- the problem stopped to occur,
- most probably, it was not related to kubernetes, e.g.: docker images couldn't be effectively pulled from the registry.

**Comment by ihmccreery** [comment] 2015-12-03 01:01
What's the status of this?

Also, was "CB" (in the title) "critical build"?  I changed the title as such, but maybe misunderstood.

**Comment by erictune** [comment] 2016-02-25 17:11
Seen today.

**Comment by erictune** [comment] 2016-02-25 17:12
[Logs](https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21776/kubernetes-pull-build-test-e2e-gce/30456/?debugUI=DEVELOPERS)

**Comment by caesarxuchao** [comment] 2016-04-07 22:02
One more:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23985/kubernetes-pull-build-test-e2e-gce/34761/

**Comment by dims** [comment] 2016-06-04 03:20
We should mark this as a duplicate of https://github.com/kubernetes/kubernetes/issues/26135 (see last 10+ failures logged by the bot in that issue)

**Comment by wojtek-t** [comment] 2016-06-04 08:13
Yes - this is duplicate of #26135

**Closed by wojtek-t** 2016-06-04 08:13 UTC
Labels: priority/P0, team/test-infra
