### ISSUE TITLE
EBS in AWS clusters is all about issues and headaches

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#41339] opened 2017-02-13 16:55 UTC
Using EBS volumes is way too unstable on k8s aws deployments, we've been using kubernetes since version 1.2, now running a 1.5.2 cluster and the problems have always been there and never solved.
80% of the time I need to delete a pod under a replication controller or deployment that have a PVC linked it, it does not work, the problem varies, sometimes I saw this same message:

```
I0213 16:49:05.844132       6 aws.go:1366] Waiting for volume "vol-a60ecccc" state: actual=attaching, desired=attached
```

repeatedly for hours and some other times this another messages:

```
I0213 16:49:05.844132       6 aws.go:1366] Waiting for volume "vol-a60e9901" state: actual=detached, desired=attached
```

also for hours. The problem is only solved by deleting the pods several times, attaching and detaching the ebs manually through aws console several times, till it decides to work.

The problem is so recurrent that we've now started to use EFS through NFS when we need persistent storage.

I hope this gets fixed in future releases of kubernetes because it is disencouraging our team to run some applications that needs persistent volumes under k8s.

**Comment by gnufied** [comment] 2017-02-13 19:19
Does this happens when pod being managed by Deployment is moved from one node to another? We have identified some of those and fixed it - https://github.com/kubernetes/kubernetes/pull/39850 

It should be released as part of 1.5.3 when released. Can you try v1.5.3-beta.0 and let us know if you are still seeing the problem. cc @kubernetes/sig-storage-bugs 


Also if you still have some pod hanging in that state, can you paste output of `kubectl describe pod <pod-name>` ?

**Comment by felipejfc** [comment] 2017-02-13 21:49
it happens even if lets say, deployment has replication of 1 and then we kill this one pod and then a new pod get rescheduled in the same machine but it timeouts waiting for the volume to be mounted, I have no pod in this state right now because I solved it earlier by restarting the node that the pod was being scheduled >.<

**Comment by jsravn** [comment] 2017-03-06 10:45
@felipejfc I feel your pain. Maybe a list of known issues somewhere would be useful? I know of at least two, one is fixed in master but not yet released, other is not yet fixed:

* https://github.com/kubernetes/kubernetes/pull/40417 - volume gets stuck if pod deleted while attaching
* https://github.com/kubernetes/kubernetes/issues/34242 - volumes don't get detached properly if pods deleted during controller manager restart

I think on the whole it's a lot more stable now than it has been in the past. Things were really bad in 1.2 time. Make sure you're using the centralised volume manager to manage your EBS attach/detach as well, that helps a lot.

**Comment by jingxu97** [comment] 2017-03-20 21:25
@felipejfc Thanks for reporting the issue. As @gnufied and @jsravn there are a few issues that were fixed recently. Could you please give it a try on the newest release? Also could you provide some more details about the situation when you notice the problem so that we might reproduce the issue? Thanks!

**Comment by ketzacoatl** [comment] 2018-01-23 17:35
From what I've seen, this is still a problem.

**Comment by jsravn** [comment] 2018-01-24 10:43
We haven't had an EBS issue at all since 1.7ish. So I'm happy with closing this.

**Closed** 2018-02-23 11:42 UTC
Labels: kind/bug, lifecycle/rotten, sig/aws, sig/storage
