### ISSUE TITLE
`kubectl edit` cannot delete an element from a list of simple type

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#32398] opened 2016-09-09 17:49 UTC
To reproduce, create an object with multiple [finalizers](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L151), and `kubectl edit` cannot remove a single finalizer from the list. This is part of the problem reported in https://github.com/kubernetes/kubernetes/issues/32339. `kubectl update` can remove a finalizer.

I think the root cause is `kubectl edit` uses strategicmerge PATCH, but its syntax does not support deleting an element from a list of simple type, because we cannot specify a merge key.

We probably cannot fix it for 1.4, but we should at least document it somewhere.

cc @bgrant0607 @janetkuo

**Comment by janetkuo** [comment] 2016-09-09 23:24
Since `kubectl edit` isn't the only command that uses PATCH I believe `kubectl apply` and `kubectl patch` have the same issue.

**Comment by janetkuo** [comment] 2016-09-09 23:24
@kubernetes/kubectl

**Comment by thockin** [comment] 2016-09-10 04:58
This is not my area of expertise, so I approach it as an end user.  I was VERY surprised that this did not work, and I would say it's significantly broken.  I would not recommend PATCH to anyone, since the semantics are very surprising.  Since `kubectl edit` is such a visible feature, I would argue it should not use PATCH.

**Comment by ymqytw** [comment] 2016-09-29 18:50
> I think the root cause is kubectl edit uses strategicmerge PATCH, but its syntax does not support deleting an element from a list of simple type, because we cannot specify a merge key.

Chao's right. I have investigated.
Maybe we need to come up with a way to let strategicmerge PATCH handle this case correctly.

**Comment by smarterclayton** [comment] 2016-09-29 23:25
Edit has to use patch of some form, otherwise you can't edit anything being
rapidly changed underneath you (nodes, anything driven by controller).

We have to fix patch.  If patch doesn't work the whole edifice comes
tumbling down.

**Comment by AdoHe** [comment] 2016-09-29 23:45
```
We have to fix patch.
```
I think this is what we should do.

**Comment by thockin** [comment] 2016-09-30 06:43
Agree.  If patch doesn't work for 100% of the edits a person is allowed to
do, it isn't very useful.

**Comment by ymqytw** [comment] 2016-10-12 05:49
cc: @lavalamp

**Comment by zefciu** [comment] 2016-10-12 10:50
Taking a look

**Comment by lavalamp** [comment] 2016-10-12 20:42
The problem isn't with patches (they can represent the replacement of the
entire list) it's with the patches that kubectl edit makes.

At the very least kubectl edit can test the patch it makes on the old
object; if that doesn't result in something exactly like what the user
wrote, kubectl edit can stop there with an error. This would at least let
people be confident that their changes will work when we succeed.

Of course the second step is to make whatever routine generates the patches
do a replacement for lists of primitives rather than failing silently.

**Comment by zefciu** [comment] 2016-10-14 15:47
@lavalamp the patches created by kubectl have the deleted object correctly removed. So the problem is on the server side it seems to me.

**Comment by caesarxuchao** [comment] 2016-10-14 17:04
@zefciu last time I checked `kubectl edit` generated an empty patch if the edit was removing an item from a list of primitives (but not removing the entire list).

**Comment by zefciu** [comment] 2016-10-17 13:40
After some debugging I find that even on the side of apiserver the object's JSON is correctly patched in patchResource method. The problem must be on deeper level. Still looking.

**Comment by ymqytw** [comment] 2016-11-11 22:42
@caesarxuchao We can close this issue, since it should be fixed by #35647. I don't know why the bot don't close this from #35647.

**Comment by janetkuo** [comment] 2016-11-11 22:44
> I don't know why the bot don't close this from #35647.

To close both issues the keyword should be `fixes #xxxxx, fixes #xxxxx`. This also means the PR template needs to be updated

**Closed by janetkuo** 2016-11-11 22:44 UTC
Labels: component/kubectl, kind/bug, priority/P0, team/ux

**Comment by ymqytw** [comment] 2016-11-11 22:48
Thanks @janetkuo
