### ISSUE TITLE
Object delete sequence when deleting a whole namespace

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#55877] opened 2017-11-16 12:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I created a pvc  and a pod(mounting with pvc) in a namespace.
When I delete the whole namespace, according to the logs, I could see that k8s will first delete pvc, and then delete pod. While the pvc is actually a disk, we must first delete the pod, release the disk, and then delete pvc, otherwise delete the pvc first will always fail because there is a lock for the volume.
Is there any way or workaround to specify the delete sequence? thanks.

**What you expected to happen**:
delete pod first, and then delete pvc

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment] 2017-11-16 12:45
/sig scheduling
not sure it's related to scheduling...

**Comment by liggitt** [comment] 2017-11-17 00:35
There is work in progress to add finalizers to PVCs to prevent their deletion prior to dependent pods

**Comment by ncdc** [comment] 2017-11-17 14:49
Dupe of #45143?

**Comment by ncdc** [comment] 2018-01-12 14:48
#45143 was fixed by #55824 - can we close this issue now?

**Closed** 2018-01-12 14:58 UTC
Labels: kind/bug, sig/api-machinery, sig/storage
