### ISSUE TITLE
kubectl edit string format is wrong

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#17632] opened 2015-11-23 06:11 UTC
Edit a resource so that it fails validation:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# %!s(func(runtime.Object) (string, error)=0x4a4780) kubernetes was not valid:
# * required value
#
```

**Comment by aveshagarwal** [comment] 2016-02-25 17:00
I am not able to reproduce this and found that this is fixed in https://github.com/kubernetes/kubernetes/pull/20481

**Comment by thockin** [comment] 2016-02-25 21:13
I just reproduced it at head:

`# %!s(func(runtime.Object) (string, error)=0x4b0480) hostnames was not valid:`

It appears we are %s printing a func, rather than calling the func and printing the resulting string.

create a service `hostnames`.  `kubectl edit svc hostnames`.  Delete the `ClusterIP` line, save, exit.

**Comment by aveshagarwal** [comment] 2016-02-25 21:32
I am testing it at master head: and I get:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# services "kubernetes" was not valid:
# * spec.clusterIP: Invalid value: "": field is immutable
#
```

**Comment by thockin** [comment] 2016-02-25 21:35
Ahh, sorry, it's a server-side string and I didn't push a new server.
Being plural form is still weird, but you can close this.

**Closed** 2016-03-02 20:52 UTC
Labels: component/kubectl, help-wanted, kind/bug, priority/P2, team/ux
