### ISSUE TITLE
[Flaky Test] [sig-network]  Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service 

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98855] opened 2021-02-07 22:40 UTC
**Which jobs are flaking**: `ci-kubernetes-kind-ipv6-e2e-parallel `

**Which test(s) are flaking**: ` Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service `

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&include-filter-by-regex=Conntrack%20should%20be%20able%20to%20preserve%20UDP%20traffic%20when%20server%20pod%20cycles%20for%20a%20NodePort%20service

**Reason for failure**:

```
Jan 29 14:02:35.213: FAIL: Failed to connect to backend 1
Full Stack Trace
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc001201380)
	test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc001201380)
skipped 112 lines unfold_more
Latency metrics for node kind-worker2
Jan 29 14:02:35.897: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "conntrack-4554" for this suite.
• Failure [80.930 seconds]
[sig-network] Conntrack
test/e2e/network/framework.go:23
  should be able to preserve UDP traffic when server pod cycles for a NodePort service [It]
```

**Anything else we need to know**:

> NOTE: 2 clusters of 4 failures (1 in last day) out of 146571 builds from 1/23/2021, 7:00:10 PM to 2/7/2021, 4:36:56 PM.

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-kind-ipv6-e2e-parallel&test=Conntrack%20should%20be%20able%20to%20preserve%20UDP%20traffic%20when%20server%20pod%20cycles%20for%20a%20NodePort%20service

Spyglass: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1355147716480471040

/sig network

**Comment by aojea** [comment] 2021-02-07 23:13
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/91236 , it just changed the name recently

It will be fixed by https://github.com/kubernetes/kubernetes/pull/98305

**Comment by thejoycekung** [comment] 2021-02-08 15:18
going to close this for dupe

/close

**Closed** 2021-02-08 15:18 UTC
Labels: kind/flake, needs-triage, sig/network
