### ISSUE TITLE
Integ tests pass but still shows up as failure 

### ISSUE THREAD

**Issue by manugupt1** [kubernetes/kubernetes#106012] opened 2021-10-29 16:55 UTC
### Which jobs are flaking?

I have had 2 times when integ tests fails on my PR; but they succeed on the jenkins link. 

https://github.com/kubernetes/kubernetes/pull/105833#issuecomment-954451199

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105833/pull-kubernetes-integration/1453952457943027712

### Which tests are flaking?

integ-tests

### Since when has it been flaking?

28 Oct 2021

### Testgrid link

https://github.com/kubernetes/kubernetes/pull/105833#issuecomment-954451199
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105833/pull-kubernetes-integration/1453952457943027712

### Relevant SIG(s)

/sig testing

**Comment by BenTheElder** [comment] 2021-11-02 18:01
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/105833/pull-kubernetes-integration/1453952457943027712/build-log.txt

nope, the tests paniced and made a massive log file, which is why you can't see the log file directly in the prow.k8s.io frontend.

**Comment by BenTheElder** [comment] 2021-11-02 18:09
132M of logs (which exceeds our configured 100M limit for processing results in prow.k8s.io), downloaded it locally for easier viewing ... 

> panic: test timed out after 10m0s

looks like these are api priority and fairness tests
/sig api-machinery
/remove-sig testing

**Comment by MikeSpreitzer** [comment] 2021-11-05 06:09
I downloaded https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/105833/pull-kubernetes-integration/1453952457943027712/build-log.txt and looked into it.  I found `panic: test timed out after 10m0s` after a batch of messages (not in timestamp order!) with timestamps in the range 2021-10-29T05:42:19.405Z to 05:43:30.  But looking back in the log to find the start of the test, it appears to be only three or four minutes earlier.

```
=== FAIL: test/integration/apiserver/apply TestApplyResetFields (unknown)
W1029 05:39:20.086034  116588 feature_gate.go:237] Setting GA feature gate ServerSideApply=true. It will be removed in a future release.
I1029 05:39:20.086101  116588 feature_gate.go:245] feature gates: &{map[ServerSideApply:true]}
I1029 05:39:20.088572  116588 plugins.go:84] "Registered admission plugin" plugin="NamespaceLifecycle"
...
```

I am probably not clear on how exactly to interpret this log file.

Things start to look suspicious at the following part of the log:

```
W1029 05:39:28.184194  116588 lease.go:233] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
I1029 05:39:28.187613  116588 httplog.go:129] "HTTP" verb="POST" URI="/api/v1/namespaces/default/endpoints" latency="2.950184ms" userAgent="apply.test/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="7c51c59f-e1f3-4621-ad13-aa0eccc94df6" srcIP="127.0.0.1:34504" apf_pl="exempt" apf_fs="exempt" apf_fd="" resp=422
E1029 05:39:28.188092  116588 controller.go:228] unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8, ::1/128)
```

Things start to go really bad at the following part of the log:

```
I1029 05:39:32.803272  116588 naming_controller.go:341] Adding pandas.awesome.bears.com
I1029 05:39:32.830872  116588 trace.go:205] Trace[1103247379]: "Create" url:/apis/apiextensions.k8s.io/v1/customresourcedefinitions,user-agent:Go-http-client/2.0,audit-id:c951db44-52d3-4b4f-aec9-ed0cd245f5eb,client:127.0.0.1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (29-Oct-2021 05:39:30.134) (total time: 2475ms):
Trace[1103247379]: ---"About to convert to expected version" 8ms (05:39:30.142)
Trace[1103247379]: ---"Conversion done" 33ms (05:39:30.176)
Trace[1103247379]: ---"About to store object in database" 1ms (05:39:30.177)
Trace[1103247379]: ---"Object stored in database" 1304ms (05:39:31.481)
Trace[1103247379]: [2.47529367s] [2.47529367s] END
I1029 05:39:32.842492  116588 aggregator.go:237] Updating OpenAPI spec because k8s_internal_local_delegation_chain_0000000002 is updated
I1029 05:39:32.973754  116588 httplog.go:129] "HTTP" verb="POST" URI="/apis/apiextensions.k8s.io/v1/customresourcedefinitions" latency="2.750116973s" userAgent="Go-http-client/2.0" audit-ID="c951db44-52d3-4b4f-aec9-ed0cd245f5eb" srcIP="127.0.0.1:34504" apf_pl="exempt" apf_fs="exempt" apf_fd="" resp=201
E1029 05:42:07.555032  116588 reflector.go:138] k8s.io/kubernetes/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go:444: Failed to watch *v1.ConfigMap: Get "https://127.0.0.1:42753/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&resourceVersion=3384&timeout=9m54s&timeoutSeconds=594&watch=true": http2: client connection lost
```

**Comment by MikeSpreitzer** [comment] 2021-11-05 07:02
The following excerpt from the panic report tells me that there was a watch cache not initialized:

```
goroutine 7883 [sync.Cond.Wait, 9 minutes]:
sync.runtime_notifyListWait(0xc00bd78a90, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x4)
	/usr/local/go/src/sync/cond.go:56 +0x8c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*ready).wait(0xc00e187f80)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:1463 +0x38
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).Watch(0xc007e3da20, {0x51f0100, 0xc00bc37500}, {0xc00d312c70, 0xc}, {{0xc00c95b14d, 0x4}, {0x0, 0x0}, {{0x5238060, ...}, ...}, ...})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:464 +0xfe
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).WatchList(0xc00b748850, {0x51f0100, 0xc00bc37500}, {0xc00d312c70, 0xc00b7488b8}, {{0xc00c95b14d, 0x4}, {0x0, 0x0}, {{0x5238060, ...}, ...}, ...})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:546 +0x69
...
	/usr/local/go/src/net/http/server.go:2046 +0x2f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1({0x51dfbd8, 0xc014b48cc0}, 0xc0064dc500)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:248 +0xc1a
...
```

In fact, there are several goroutines with such a stack.

In the merge of commits c7c78e2b86a1326d1d31b9f7a35b723f9f940f79 (I do not know how to fetch a4bf2d74eba84940686e29675602aeaf443175d1) and bb24c265ce725c90f0e82b01e7c1ccbffb695d14 (of the `master` branch), cacher.go:464 says

```
	c.ready.wait()
```

Each such goroutine holds some seats in APF, with a stack like the following goroutine.

```
goroutine 11518 [chan receive, 9 minutes]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.(*initializationSignal).Wait(0xc0174ed680)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_context.go:92 +0x1f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.6()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:196 +0x21f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go:180 +0x1eb
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.immediateRequest.Finish(...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:785
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle(0xc007aaa000, {0x51f0090, 0xc020967e40}, {0xc00344f080, {0x51f0c98, 0xc00b636500}, {0x1, 0x0, 0x0}}, 0xc007b7cae0, ...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go:170 +0x8d3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.7()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:241 +0x125
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:209 +0x905
```

So the question here is why the watch cache is not initialized.  I suspect that is a consequence of the rot mentioned in my previous comment.

**Comment by MikeSpreitzer** [comment] 2021-11-05 07:11
There are several "panic: test timed out after 10m0s", at about the same time.  I do not understand why or what this means.

**Comment by MikeSpreitzer** [comment] 2021-11-05 07:21
@wojtek-t 
I wonder if APF should put a cap on how long to wait for a given watch cache to become initialized.

**Comment by wojtek-t** [comment] 2021-11-05 07:45
> I wonder if APF should put a cap on how long to wait for a given watch cache to become initialized.

I don't think it's APF per-se, but I agree that we shouldn't hang there indefinitely.
As an example, for lists we're waiting for cache to by synchronized for 3s:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L432
We probably need something similar here.

Though - we also need to be very careful here - because failing the watch could mean that components will fallback to list again, which will generate much higher load. So ideally we should fail the watch with an error that would result in retry of watch (429 is an example of such error - though not ideal to use in this case).

I guess the main quetion is why watchcache isn't initializing correctly - because at the level of this test it should be very fast - with almost no objects it doesn't have much work to do.

**Comment by MikeSpreitzer** [comment] 2021-11-05 13:57
What I meant to suggest is that APF limit how long it will hold off giving the initialization signal, that's all.  Not introduce any failure.

And, yes, I agree that APF is just a downstream casualty here.  As I said, I do not understand how to interpret what I see in that log file.  Some of it says the test ran for only three or four minutes, but other parts say it timed out after 10 minutes.

**Comment by aojea** [comment] 2021-11-05 14:07
integration job seems to be on the edge, once we add more load the jobs start to time out
https://github.com/kubernetes/kubernetes/issues/103512

my impression is that the tests are overwhelming etcd, and sometimes connections are closed and tests time out, but  I don't have any strong evidence, just that the etcd instance is shared between all tests and when we remove some load/tests from the job it recovers ...

**Comment by MikeSpreitzer** [comment] 2021-11-05 14:10
@aojea : The log discussed above starts by showing etcd slowness and connection loss, so that's consistent with what you say.  What is the right remedy?

**Comment by aojea** [comment] 2021-11-05 14:44
> @aojea : The log discussed above starts by showing etcd slowness and connection loss, so that's consistent with what you say. What is the right remedy?

Last time was fixed by setting one variable, but we only have hypothesis :shrug: 

https://github.com/kubernetes/kubernetes/pull/105506#issuecomment-937896765

I think that we are blind here, each test is compiled in a different binary and run in parallel with more tests, that makes difficult to get the test instrumented, however, the etcd instance is always the same, if we can have, in addition to the logs, etcd metrics we could correlate the failures with etcd problems , is a known issue that CI has disk contention, and that is a big issue for etcd ....

The job executes
https://github.com/kubernetes/kubernetes/blob/79a51090f9582c9b67576c180d77b95214d1cd3e/hack/jenkins/test-dockerized.sh#L51-L55

The bits that run etcd are
https://github.com/kubernetes/kubernetes/blob/79a51090f9582c9b67576c180d77b95214d1cd3e/hack/lib/etcd.sh#L85-L91

if we can just start some kind of prometheus client that dump the metrics to a file once the test finish, we could have better insights and working with more data to find out the root cause ... is something I want to do but I never find time

**Comment by BenTheElder** [comment] 2021-11-08 15:59
I think in CI these are now running on machines with local NVMe SSD, n1-highmem-8 as the only major workload (requesting ~all cores in the job), so worth noting if we're overloading here these tests are probably less reliable on plenty of reasonable local machines ...

**Closed** 2022-04-07 17:08 UTC
Labels: sig/api-machinery, kind/flake, lifecycle/rotten, triage/accepted
