### ISSUE TITLE
[flake] CGroup subsystem not mounted. integration tests.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#32675] opened 2016-09-14 14:50 UTC
Problem

Looks like CGroups / Kubelet not ready errors cause flakes in the integraiton  tests.

Example: 
```
  Ready 		False 	Wed, 14 Sep 2016 06:37:09 -0700 	Wed, 14 Sep 2016 06:34:09 -0700 	KubeletNotReady 		Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]
Addresses:		127.0.0.1,127.0.0.1
```

**Comment by dchen1107** [comment] 2016-09-14 16:03
@jayunit100 That is expected problem by design. If any required cgroups are not mounted, and memory cgroup is one of them. On another side, if memory cgroup is not mounted, docker won't work properly anyway. 

I am going close the issue. If you disagree, please reopen it.

**Closed by dchen1107** 2016-09-14 16:03 UTC
Labels: component/kubelet, team/node, team/ux

**Comment by jayunit100** [comment] 2016-09-15 12:01
ok, maybe it wasnt the cause of my test failures.
