### ISSUE TITLE
PD e2e tests are flaky

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#15467] opened 2015-10-12 10:35 UTC
PD tests are flaky, they fail with the following error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:179
Expected error:
    <*errors.errorString | 0xc2090e09f0>: {
        s: "gave up waiting for pod 'pd-test-fd51806e-70b0-11e5-b74c-42010af01555' to be 'running' after 5m0s",
    }
    gave up waiting for pod 'pd-test-fd51806e-70b0-11e5-b74c-42010af01555' to be 'running' after 5m0s
not to have occurred
```
Flaky cases:
**Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both.**
**Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession**

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8879/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8884/

**Comment by zmerlynn** [comment] 2015-10-12 17:29
This is a dupe of #15382, I think.

**Closed by zmerlynn** 2015-10-12 17:29 UTC
Labels: priority/P1
