### ISSUE TITLE
CEL has misleading error message for fields called "namespace"

### ISSUE THREAD

**Issue by mattcary** [kubernetes/kubernetes#122777] opened 2024-01-14 20:10 UTC
### What happened?

See the CRD at https://gist.github.com/mattcary/353b202240c250b5cb4371058f233476

in summary it is

```
spec:
  ref:
    name: myName
    namespace: myNamespace
```

One can create a x-kubernetes-validations rule that spec.ref.name != "", but one cannot create a rule that spec.ref.namespace != "". The former applies successfully, but applying the latter (the gist as written now):

```
The CustomResourceDefinition "validations.mattcary.info" is invalid: spec.validation.openAPIV3Schema.properties[spec].x-kubernetes-validations[0].rule: Invalid value: apiextensions.ValidationRule{Rule:"self.ref.namespace != \"\"", Message:"", MessageExpression:"", Reason:(*apiextensions.FieldValueErrorReason)(nil), FieldPath:"", OptionalOldSelf:(*bool)(nil)}: compilation failed: ERROR: <input>:1:9: undefined field 'namespace'
 | self.ref.namespace != ""
 | ........^
```

### What did you expect to happen?

The error message should say improper use of reserved word "namespace" rather than say that the field does not exist.

### How can we reproduce it (as minimally and precisely as possible)?

Save the gist https://gist.github.com/mattcary/353b202240c250b5cb4371058f233476 to a file, then `kubectl apply -f FILENAME`

### Kubernetes version

<details>

```console
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-gke.1492000
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux rodete"
VERSION_CODENAME=rodete
ID=debian
HOME_URL="https://go/glinux"
SUPPORT_URL="https://go/techstop"
BUG_REPORT_URL="https://go/techstop"
$ uname -a
Linux mattcary.c.googlers.com 6.5.13-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete1 (2023-12-06) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Ithrael** [comment] 2024-01-15 04:54
I can reproduce the issue, it may be because 'namespace' has been set as a keyword
https://github.com/kubernetes/kubernetes/blob/59f25b5c2dc4203ac45a80ac4fd8bb4b9c51077a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go#L198C1-L200C65
<img width="1016" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/36630192-3f70-4f10-8644-c695277f99f7">

**Comment by mattcary** [comment] 2024-01-16 16:35
Ah, thank you. That's what's going on, if I use `rule: self.ref.__namespace__ != ""` it validates as expected.

So I guess this is working as intended, although it's quite surprising "namespace" would be reserved.

At least the error message is very misleading, it should flag a syntax error rather than say that the field is not present.

**Comment by cici37** [comment] 2024-01-16 21:22
Thanks for raising the issue! We have a `escape` section writing in [CRD validation rule doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) specifically mentioned `namespace` as a reserved keyword. It could be referred in [CEL reserved keyword](https://github.com/google/cel-spec/blob/master/doc/langdef.md#syntax) as well. I agree that the returned error message might not be clear enough which could be improved.

/cc @jiahuif 
/triage accepted

**Comment by ballista01** [comment] 2024-01-16 22:09
Hello, I'd like to contribute to this issue. @cici37 I suppose it's about changing the error message or adding a separate rule to clarify the error. Could you give me a hint where the error message is generated?

**Comment by ballista01** [comment] 2024-01-28 07:22
/assign

I suppose it's about changing the error message or adding a separate rule to clarify the error. Seems to be here https://github.com/google/cel-go/blob/df072086206afaba0112df1facdd7cf7183af8a3/checker/checker.go#L655, working on it

**Comment by thockin** [comment] 2024-02-13 06:53
This is a pretty gnarly hazard - can we fix it at the root?  I am not a CEL expert - is the grammar actually ambiguous here?  It seems pretty bad to eat into field-names, ESPECIALLY when we know that "namespace" is an important word in k8s.

**Comment by ballista01** [comment] 2024-02-13 16:58
Sorry for missing the updates, I've been busy with the schoolwork recently. For this issue, I added a second check after CEL fails to find the `namespace` because it's already wrapped with `__` when provided to CEL. The second check looks for `__{word to look for}__` if the initial search is failed. If `__{word to look for}__` is found it generates a new error message, if it's still not found we can confirm the word is not there and it gives the same `undefined field` error. For now, it seems to work towards the right direction, I'll make sure it doesn't affect other parts later:
 
 Here's the test output:
 ```
 === RUN   TestValidationExpressions/embedded_object_with_properties
=== PAUSE TestValidationExpressions/embedded_object_with_properties
=== CONT  TestValidationExpressions/embedded_object_with_properties
    --- FAIL: TestValidationExpressions/embedded_object_with_properties (0.00s)
=== RUN   TestValidationExpressions/embedded_object_with_properties/has(self.embedded.metadata.namespace)
    validation_test.go:2063: expected error to contain 'OLD ERROR MESSAGE: undefined field 'namespace'', but got: root: Invalid value: "object": rule compile error: compilation failed: ERROR: <input>:1:4: improper use of reserved keyword 'namespace', use '__namespace__' instead
         | has(self.embedded.metadata.namespace)
         | ...^
        ERROR: <input>:1:4: undefined field 'namespace'
         | has(self.embedded.metadata.namespace)
         | ...^
        --- FAIL: TestValidationExpressions/embedded_object_with_properties/has(self.embedded.metadata.namespace) (0.00s)



FAIL
 ```
 
 The new error message will be `improper use of reserved keyword '{theMisusedKeyword}', use '__{theMisusedKeyword}__' instead`. The improvement involves changing some logic in CEL and modifying a couple of unit tests in K8s. @thockin @cici37 do you think it's a proper solution?

**Comment by thockin** [comment] 2024-02-13 18:02
I dont think it is OK to require users to say "__namespace__" when the field name is actually "namespace"

**Comment by ballista01** [comment] 2024-02-13 18:24
@thockin Yes, so the error message is prompting the user to use `__namespace__` when the user accidently used `namespace`.

**Comment by thockin** [comment] 2024-02-13 18:53
> The new error message will be `improper use of reserved keyword '{theMisusedKeyword}', use '__{theMisusedKeyword}__' instead`

I reject that this is an "improper use".  It seems pretty unambiguous that this is a field name, not a keyword usage.  I don't think this is an error - it should be made to work without surprises.

**Comment by cici37** [comment] 2024-08-29 16:09
/close 
Should be fixed by https://github.com/kubernetes/kubernetes/pull/126188
Note that the support was added for stored expression in 1.31 and will be supported in new incoming expression starting 1.32.

**Closed by cici37** 2024-08-29 16:10 UTC
Labels: kind/bug, sig/api-machinery, triage/accepted
