### ISSUE TITLE
About CNTT test，I want to know which test cases in k8s correspond to these use cases

### ISSUE THREAD

**Issue by beiying-6282** [kubernetes/kubernetes#97196] opened 2020-12-10 14:18 UTC
**Which jobs are failing**:   CNTT test

**Which test(s) are failing**:  Testsuite：cnf -cnf_conformance 

- functest_kubernetes.cnf_conformance.conformance - INFO - |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  
\|                             NAME                            \|     STATUS     \| |   |   |   |   |   |   |   |  
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  
\|                          privileged                         \|     passed     \| |   |   |   |   |   |   |   |  
\|                      increase_capacity                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                      decrease_capacity                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                         ip_addresses                        \|     passed     \| |   |   |   |   |   |   |   |  
\|     hardcoded_ip_addresses_in_k8s_runtime_configuration     \|     passed     \| |   |   |   |   |   |   |   |  
\|                     install_script_helm                     \|     passed     \| |   |   |   |   |   |   |   |  
\|                       helm_chart_valid                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                     helm_chart_published                    \|     failed     \| |   |   |   |   |   |   |   |  
\|                         helm_deploy                         \|     failed     \| |   |   |   |   |   |   |   |  
\|                   reasonable_startup_time                   \|     failed     \| |   |   |   |   |   |   |   |  
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  

**Since when has it been failing**:  now

**Testgrid link**:

**Reason for failure**:  Checking..，functest要求k8s是1.19版本，但目前用的是1.17测试

**Anything else we need to know**:
Community official test results：
https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-cnf-kali-cnf_conformance-run/19/console

**Comment by neolit123** [comment] 2020-12-14 18:39
/close
duplicate of https://github.com/kubernetes/kubernetes/issues/97195

**Closed** 2020-12-14 18:39 UTC
Labels: kind/failing-test, needs-sig, needs-triage
