### ISSUE TITLE
kubeadm init stuck midway

### ISSUE THREAD

**Issue by phungleson** [kubernetes/kubernetes#56275] opened 2017-11-23 05:52 UTC
Hi guys,

I have an issue, `kubeadm init` stucking at

```
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.8.4
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [kubernetes-master-eu-central-1.mydomain.com kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [private_ip public_ip]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
```

`docker ps` seems to shows some running containers
`systemctl status kubelet` returns active status

I am using CentOS 7.4 on AWS, have internet access.

I have no ideas what to do from here, maybe some timeouts would work? Some clues would be very welcome.

Thanks in advance.

**Comment by shun-miyoshi-com** [comment] 2017-11-24 07:30
Do you have at least 3 pods in `docker ps`?(kube-apiserver, kube-controller-manager, kube-scheduler)

If you yes,I think you should check `docker logs` of pods and kubelet log.

**Comment by phungleson** [comment] 2017-11-24 12:34
I literally just changed from Centos OS (ami-2ef4833) to Ubuntu (ami-a9a557c6) then it works.

What should I look into? It seems firewalld is off.

**Comment by phungleson** [comment] 2017-11-24 13:32
The docker ps looks like this

```
CONTAINER ID        IMAGE                                                                                                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
2750cbe66fc0        gcr.io/google_containers/kube-controller-manager-amd64@sha256:8adbcd2de1b1ef752ce92c0602f99aa4bd86798c7b546e56c398e18f9f60c26b   "kube-controller-mana"   3 minutes ago       Up 3 minutes                            k8s_kube-controller-manager_kube-controller-manager-ip-10-0-140-245.eu-central-1.compute.internal_kube-system_bf1763bbc55a0df9eef32c401d5fdb46_0
c5bfcd97269e        gcr.io/google_containers/kube-scheduler-amd64@sha256:72608b511275a1661b66f113cff09a0737b4d8e1405ad0ddb2e98c9cad0a8323            "kube-scheduler --add"   3 minutes ago       Up 3 minutes                            k8s_kube-scheduler_kube-scheduler-ip-10-0-140-245.eu-central-1.compute.internal_kube-system_e554495c6f8701f21accd04866090b05_0
6a57cba0daf7        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_kube-apiserver-ip-10-0-140-245.eu-central-1.compute.internal_kube-system_75667f10d2974a124465eadd43689788_0
54dbb7ceafaf        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_kube-controller-manager-ip-10-0-140-245.eu-central-1.compute.internal_kube-system_bf1763bbc55a0df9eef32c401d5fdb46_0
1275d1d44f93        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_etcd-ip-10-0-140-245.eu-central-1.compute.internal_kube-system_d76e26fba3bf2bfd215eb29011d55250_0
90eb3961c11f        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 3 minutes ago       Up 3 minutes
```

**Comment by phungleson** [comment] 2017-11-24 13:38
Logs in  controller looks like this

```
E1124 13:37:30.841259       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://10.0.140.245:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 10.0.140.245:6443: getsockopt: connection refused
E1124 13:37:33.816431       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
```

**Comment by shun-miyoshi-com** [comment] 2017-11-27 00:52
According to your `docker ps` log, kube-apiserver does not wake up, so contloller-manager could not access to apiserver(dial tcp 10.0.140.245:6443: getsockopt: connection refused)
It is not network problem.

Kubernetes repeats the following loop,
  create -> crash(because of error) -> wait 30s -> cleanup -> wait -> recreate -> ...

So, please try multiple `docker ps | grep kube-apiserver` in order to get apiserver process.
And please show me the log of apiserver.

**Comment by dims** [comment] 2017-11-27 15:05
cc @luxas 

@phungleson can you please move this to https://github.com/kubernetes/kubeadm/issues?

/sig cluster-lifecycle

**Comment by luxas** [comment] 2017-11-27 21:39
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue. Finally, please try to reproduce the bug with the latest Kubernetes version, it might as well already have been fixed :)

Thank you and have a good day!

**Closed by luxas** 2017-11-27 21:39 UTC
Labels: sig/cluster-lifecycle
