### ISSUE TITLE
kubectl apply success but add server-side flag apply failed

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#92332] opened 2020-06-20 03:50 UTC
**What happened**:
```
[root@master01 f]# kubectl apply -f nginx-deploy.yaml --prune --all --prune-whitelist=apps/v1/deployment --server-side --force-conflicts
Error from server: failed to create typed patch object: .spec.template.spec.containers[name="nginx"].ports: element 0: associative list with keys has an element that omits key field "protocol"
[root@master01 f]# kubectl apply -f nginx-deploy.yaml
deployment.apps/nginx-deployment unchanged
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@master01 f]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-06-20 13:13
cc @apelisse

**Comment by apelisse** [comment] 2020-06-20 20:36
This is a duplicate of https://github.com/kubernetes-sigs/structured-merge-diff/issues/130.

We're very aware of this bug, and we're working on getting this fixed. @jennybuckley.
In the mean time, I would suggest you add the `TCP` protocol for your nginx container to work-around the problem.

**Closed** 2020-06-20 20:36 UTC
Labels: kind/bug, sig/api-machinery, wg/api-expression

**Comment by moshebeeri** [comment] 2021-12-31 22:57
For a work around just do this:
    ports:
      - name: http
        protocol: TCP
        containerPort: 3000
