### ISSUE TITLE
Kubelet [Serial] [Slow] regular resource usage tracking for 0 pods per node over 20m0s

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19647] opened 2016-01-14 11:03 UTC
It fails all the time in `kubernetes-soak-continuous-e2e-gce`.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:184 Jan 13 13:22:56.720: CPU usage exceeding limits: node gce-soak-weekly-minion-fg9o: container "/docker-daemon": expected 95th% usage < 0.060; got 0.069 node gce-soak-weekly-minion-61lh: container "/docker-daemon": expected 95th% usage < 0.060; got 0.066
```

cc @kubernetes/goog-node

**Comment by yujuhong** [comment] 2016-01-21 18:35
I suspect the node was in a bad state. After deploying the new build, the test hasn't failed at all this week. Closing this and will re-open if it hits again.

**Comment by gmarek** [comment] 2016-02-01 10:18
It's failing again:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/345/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/357/

and so on.

**Comment by gmarek** [comment] 2016-02-01 10:18
cc @dchen1107 @davidopp

**Comment by yujuhong** [comment] 2016-02-01 18:40
The 0 pods per node test is more sensitive to noise caused by uneven distribution of cluster add-on pods. I adjusted the limits in #20423 to reflect the current kubelet status and also to account for the noise. Ideally we should disable the cluster add-ons in the cluster, but there is no easy way to do this in the current test framework. I think we should consider moving this test with hard limits to the node conformance test suite (where the addons are not enabled). We can keep this test here for monitoring purpose, but don't fail the build explicitly. We can integrate with other monitoring service and send alerts if necessary.

**Comment by gmarek** [comment] 2016-02-01 18:59
@yujuhong - actually it is easy to do during cluster startup. We can create a dedicated Node suite and run Node tests there (if it's not done already).

**Comment by yujuhong** [comment] 2016-02-01 20:33
> @yujuhong - actually it is easy to do during cluster startup. We can create a dedicated Node suite and run Node tests there (if it's not done already).

@gmarek, we actually just started node conformance tests in http://kubekins.dls.corp.google.com/view/Node/, which one of the v1.2 targets.
It seems like this test might be a good fit there. cc @pwittrock will know more about porting/migrating tests to the node conformance suites.

**Comment by dchen1107** [comment] 2016-02-01 21:13
Yes, one of the reasons we create a separate node test suite is moving this kind of test over. Let's try to move all node level resource tracking tests over to node test suite.

**Comment by davidopp** [comment] 2016-09-18 08:37
failing in
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-gci-1.4-upgrade-cluster

**Comment by yujuhong** [comment] 2016-09-22 17:16
@davidopp This issue is not intended for GCI nor upgrade suites. Filing a new issue might be better.

 GCI has had problems with the docker memory usage for a while, as you can see in https://k8s-testgrid.appspot.com/google-gci#gci-serial-release-1.4. I think they fixed it in the latest dev image, but I am not sure if that was used in the upgrade tests.

**Closed by yujuhong** 2016-09-22 17:16 UTC
Labels: kind/flake, priority/P1, team/node
