### ISSUE TITLE
kubelet support cadvisor interval  settings

### ISSUE THREAD

**Issue by yangyefei90** [kubernetes/kubernetes#127147] opened 2024-09-05 12:33 UTC
# What would you like to be added?
support cadvisor interval housekeeping settings in kubelet
such as --cadvisor-max-house-keeping-interval

# Why is this needed?
For online tasks, the monitoring factuality requirement is very high. Usually, a monitoring indicator needs to be collected every second. Currently, the maximum collection interval of kubelet is 15s and cannot be set. For important online businesses, it is unacceptable that problems cannot be accurately judged based on monitoring data. Therefore, it is expected that the maximum monitoring interval can be configured through kubelet to improve the real-time nature of monitoring data.

**Comment by kannon92** [comment] 2024-09-05 18:56
duplicate of https://github.com/kubernetes/kubernetes/issues/123340

/close

**Closed by kannon92** 2024-09-05 18:56 UTC
Labels: sig/node, kind/feature, needs-triage
