### ISSUE TITLE
e2e: time out fetching repo from github

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14074] opened 2015-09-16 21:24 UTC
In #13765 @lavalamp asked re: jenkins runs:
"@ixdy the last two runs timed out trying to fetch the repo from github. Is
there any way we can do a retry after like 30s instead of waiting 10m and
then failing?"

I also saw similar things in 2 other PRs, so promoting to issue.

**Comment by lavalamp** [comment] 2015-09-16 21:27
Yeah, I should have filed an issue, there may already be one. But @ixdy and @quinton-hoole are aware of this.

**Comment by quinton-hoole** [comment] 2015-09-16 21:47
@alex-mohr . @lavalamp the current theory is that this is not actually a github problem, but a problem on our Jenkins host (overload or something similar). I think it's more productive to direct effort to fixing that problem right now than to put in hacks to work around it.  @ixdy and Adam are both working on this as P0 as we speak.

If it turns out that the problem is on the github end, we can certainly look into working around it.

**Comment by quinton-hoole** [comment] 2015-09-16 21:49
Of course it goes without saying that TCP and the load balancers on the front of github do a reasonable job of retrying :-) so anything we tried to do would be over and above that, and would have to be better than those to be of much use.

**Comment by ixdy** [comment] 2015-09-16 22:30
cc @adamtanner

The PR Jenkins runs
`git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/heads/*:refs/remotes/origin/*`

for each change, which seems to check out all pull requests that have ever existed, even those that have merged. This is because it's using the refspec documented in the GitHub Pull Request Builder docs:
`+refs/pull/*:refs/remotes/origin/pr/*`

On my local machine, this only seems to take a few seconds, but for mysterious reasons it has started timing out after 10 minutes on Jenkins.

I recently (a few minutes ago) updated the refspec to only pull the change under test:
`+refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*`

Early evidence suggests this may be helping:
```
15:27:13 Fetching upstream changes from https://github.com/kubernetes/kubernetes
15:27:13  > git --version # timeout=10
15:27:13  > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/13765/*:refs/remotes/origin/pr/13765/* --prune
15:27:22  > git rev-parse refs/remotes/origin/pr/13765/merge^{commit} # timeout=10
15:27:22  > git rev-parse refs/remotes/origin/origin/pr/13765/merge^{commit} # timeout=10
15:27:22 Checking out Revision 6dc99be3fcdc3da5721f4b3a73c2d5139ba3e52f (refs/remotes/origin/pr/13765/merge)
15:27:22  > git config core.sparsecheckout # timeout=10
15:27:22  > git checkout -f 6dc99be3fcdc3da5721f4b3a73c2d5139ba3e52f
15:27:23 First time build. Skipping changelog.
```

**Comment by ixdy** [comment] 2015-09-16 23:56
OK, still having some issues; not a timeout, but still problematic:
From http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/8887/console

```
16:45:13 GitHub pull request #13978 of commit f260de4fc4b93ccd0a27f5bacce39649712ceb71, no merge conflicts.
16:45:14 Setting status of f260de4fc4b93ccd0a27f5bacce39649712ceb71 to PENDING with url http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/8887/ and message: 'Build started sha1 is merged.'
16:45:14 Using context: Jenkins GCE e2e
16:45:14 [EnvInject] - Loading node environment variables.
16:45:14 Building in workspace /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@2
16:45:14  > git rev-parse --is-inside-work-tree # timeout=10
16:45:14 Fetching changes from the remote Git repository
16:45:14  > git config remote.origin.url https://github.com/kubernetes/kubernetes # timeout=10
16:45:14 Pruning obsolete local branches
16:45:14 Fetching upstream changes from https://github.com/kubernetes/kubernetes
16:45:14  > git --version # timeout=10
16:45:14  > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/13978/*:refs/remotes/origin/pr/13978/* --prune
16:45:20 ERROR: Error fetching remote repo 'origin'
16:45:20 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
16:45:20 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
16:45:20 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
16:45:20 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
16:45:20 	at hudson.scm.SCM.checkout(SCM.java:485)
16:45:20 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
16:45:20 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
16:45:20 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
16:45:20 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
16:45:20 	at hudson.model.Run.execute(Run.java:1741)
16:45:20 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:45:20 	at hudson.model.ResourceController.execute(ResourceController.java:98)
16:45:20 	at hudson.model.Executor.run(Executor.java:408)
16:45:20 Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/13978/*:refs/remotes/origin/pr/13978/* --prune" returned status code 128:
16:45:20 stdout: 
16:45:20 stderr: error: RPC failed; result=18, HTTP code = 200
16:45:20 fatal: The remote end hung up unexpectedly
16:45:20 
16:45:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
16:45:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
16:45:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
16:45:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
16:45:20 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
16:45:20 	... 11 more
16:45:20 ERROR: null
```

I've found no useful information on what causes this, but this has also been happening with some regularity on PR Jenkins.

**Comment by ixdy** [comment] 2015-10-05 22:05
I've only seen one issue of this recurring on the PR Jenkins in the last week:
```
07:09:15 GitHub pull request #14827 of commit 3ae276cc0bebeca841a3003c9db3462d2b113693, no merge conflicts.
07:09:15 Setting status of 3ae276cc0bebeca841a3003c9db3462d2b113693 to PENDING with url http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/11084/ and message: 'Build started sha1 is merged.'
07:09:15 Using context: Jenkins GCE e2e
07:09:15 [EnvInject] - Loading node environment variables.
07:09:15 Building in workspace /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace
07:09:15  > git rev-parse --is-inside-work-tree # timeout=10
07:09:15 Fetching changes from the remote Git repository
07:09:15  > git config remote.origin.url https://github.com/kubernetes/kubernetes # timeout=10
07:09:15 Pruning obsolete local branches
07:09:15 Fetching upstream changes from https://github.com/kubernetes/kubernetes
07:09:15  > git --version # timeout=10
07:09:15  > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/14827/*:refs/remotes/origin/pr/14827/* --prune
07:09:30 ERROR: Error fetching remote repo 'origin'
07:09:30 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
07:09:30 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
07:09:30 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
07:09:30 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
07:09:30 	at hudson.scm.SCM.checkout(SCM.java:485)
07:09:30 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
07:09:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
07:09:30 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
07:09:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
07:09:30 	at hudson.model.Run.execute(Run.java:1741)
07:09:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
07:09:30 	at hudson.model.ResourceController.execute(ResourceController.java:98)
07:09:30 	at hudson.model.Executor.run(Executor.java:408)
07:09:30 Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/14827/*:refs/remotes/origin/pr/14827/* --prune" returned status code 128:
07:09:30 stdout: 
07:09:30 stderr: error: RPC failed; result=18, HTTP code = 200
07:09:30 fatal: The remote end hung up unexpectedly
07:09:30 
07:09:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
07:09:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
07:09:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
07:09:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
07:09:30 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
07:09:30 	... 11 more
07:09:30 ERROR: null
```

Lowering priority accordingly.

**Comment by ixdy** [comment] 2015-10-05 22:06
Also, this wasn't a timeout, but the mysterious "fatal: The remote end hung up unexpectedly" error which happens occasionally.

**Comment by ixdy** [comment] 2016-01-25 23:46
@spxtr do we think this has been fixed now?

**Comment by spxtr** [comment] 2016-01-25 23:52
#18960

Should be fixed now.

**Comment by ixdy** [comment] 2016-01-25 23:53
Great, going to close this then.

**Closed by ixdy** 2016-01-25 23:53 UTC
Labels: priority/P2, team/test-infra
