### ISSUE TITLE
Misintepretation of integer-like strings when deploying a ConfigMap

### ISSUE THREAD

**Issue by lukaszpierog** [kubernetes/kubernetes#112326] opened 2022-09-08 15:01 UTC
### What happened?

Example working config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  shortCommitHash: '0340914'
```

example of failing config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  shortCommitHash: 0340914
```
The difference is missing quotes around the value of shortCommitHash parameter.
The error is quite descriptive: "Invalid value: "map[data:map[shortCommitHash:340914]]": cannot convert int64 to string"
However this int-looking value according to [yaml specification](https://yaml.org/spec/1.2.2/#10213-integer) is not really an int, because it does not match a pattern (as it starts with 0). In fact its is a string. 
This happens to cause problems when using libraries like SnakeYaml for Java, which seem to correctly bypass quotes for a value like that, because according to the Yaml specification it should be implicitly considered a string and quotes are not necessary. Therefore when we use SnakeYaml library to prepare deployment Yaml files and then try to deploy those files to Kubernetes the process fails.

### What did you expect to happen?

ConfigMap should be considered valid even without quotes

### How can we reproduce it (as minimally and precisely as possible)?

As described above

### Kubernetes version

<details>

```console
$ kubectl version
Version info:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment] 2022-09-09 04:42
/sig api-machinery
There is some discussions related in https://github.com/kubernetes/kubernetes/issues/82296#issuecomment-529675294

**Comment by Jefftree** [comment] 2024-08-06 18:17
Duplicate of https://github.com/kubernetes/kubernetes/issues/82296 and https://github.com/kubernetes/kubernetes/issues/82296.

/close

**Closed by Jefftree** 2024-08-06 18:17 UTC
Labels: kind/bug, sig/api-machinery, needs-triage
