### ISSUE TITLE
Multiple mount points default-token-*

### ISSUE THREAD

**Issue by daniel-yavorovich** [kubernetes/kubernetes#25489] opened 2016-05-11 19:27 UTC
Dear Sirs/Madams,

I use Kubernetes v1.2.4, like Docker Multinode on Ubuntu 14.04 x86_64. After installation appears multiple mount points, which increase to infinity:

    # mount
    ...
    tmpfs on /var/lib/kubelet/pods/8f23c93a-17ab-11e6-92f3-002421ef2f79/volumes/kubernetes.io~secret/default-token-9bw9j type tmpfs (rw)
    tmpfs on /var/lib/kubelet/pods/74fbdeb9-17aa-11e6-92f3-002421ef2f79/volumes/kubernetes.io~secret/default-token-9i2dw type tmpfs (rw)

    # mount | grep -c default-token
    19934

The same situation is also manifested in the Kubernetes v1.3-alpha-1,2.

What could be the reason?

**Comment by jason-kane** [comment] 2016-05-13 22:25
same symptom here with kubernetes 1.2.1 -- mostly dupes:

~# df -h | grep tmpfs | wc -l
30438

~# df -h | grep tmpfs | sort | uniq | wc -l
65

**Comment by daniel-yavorovich** [comment] 2016-06-03 16:54
any updates?

**Comment by matchstick** [comment] 2016-07-07 07:57
@kubernetes/sig-storage Can you try this again with 1.3? We made some fixes in this area recently. Also please let us know more of your setup? Are you using any attached volumes? Or is this just getting the container runtimes to work?

**Comment by jingxu97** [comment] 2016-07-07 17:47
The fix in PR https://github.com/kubernetes/kubernetes/pull/27054 might fix your issue. Please let us know if you still experience the issue. Thanks!

**Comment by pmorie** [comment] 2016-07-25 14:11
@daniel-yavorovich is this still an issue?

**Comment by matchstick** [comment] 2016-08-12 00:47
Closing as we believe we have fixed this in 1.3.4.  Please reopen if you can reproduce it.

**Closed by matchstick** 2016-08-12 00:47 UTC
Labels: area/storage, team/cluster
