### ISSUE TITLE
[e2e failure] [k8s.io] [sig-apps] Network Partition [Disruptive] [Slow] [k8s.io] Pods should return to running and ready state after network partition is healed All pods on the unreachable node should be marked as NotReady upon the node turn NotReady AND all pods should be mark back to Ready when the node get back to Ready before pod eviction timeout

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56416] opened 2017-11-27 15:08 UTC
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
@kubernetes/sig-apps-test-failures 

This test has been failing since at least 2017-11-13 in the following jobs:
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-master
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-cluster

These jobs are on the [sig-release-master-upgrade dashboard](https://k8s-testgrid.appspot.com/sig-release-master-upgrade), and prevent us from cutting v1.9.0-beta.1 (kubernetes/sig-release#34). Is there work ongoing to bring this test back to green?

triage cluster [ae1720e299d92ebf1b8f](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bk8s%5C.io%5C%5D%5C%20%5C%5Bsig%5C-apps%5C%5D%5C%20Network%5C%20Partition%5C%20%5C%5BDisruptive%5C%5D%5C%20%5C%5BSlow%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Pods%5C%20should%5C%20return%5C%20to%5C%20running%5C%20and%5C%20ready%5C%20state%5C%20after%5C%20network%5C%20partition%5C%20is%5C%20healed%5C%20All%5C%20pods%5C%20on%5C%20the%5C%20unreachable%5C%20node%5C%20should%5C%20be%5C%20marked%5C%20as%5C%20NotReady%5C%20upon%5C%20the%5C%20node%5C%20turn%5C%20NotReady%5C%20AND%5C%20all%5C%20pods%5C%20should%5C%20be%5C%20mark%5C%20back%5C%20to%5C%20Ready%5C%20when%5C%20the%5C%20node%5C%20get%5C%20back%5C%20to%5C%20Ready%5C%20before%5C%20pod%5C%20eviction%5C%20timeout#ae1720e299d92ebf1b8f)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:219
Nov 20 09:53:30.042: Failed to observe node ready status change to false
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:61
```

- this showed up as a failure during the v1.8.0 release (https://github.com/kubernetes/kubernetes/issues/53018)
- the issue referenced therein was reopened and seems to have been failing ever since? (https://github.com/kubernetes/kubernetes/issues/47820)

**Comment by mattfarina** [comment] 2017-11-27 18:18
@kubernetes/sig-node-bugs This issue appears to be with Nodes and how they handle network partitions. I'm not sure this belongs with SIG Apps. Should this be with SIG Node?

**Comment by kow3ns** [comment] 2017-11-28 16:27
@mattfarina workloads added them some time ago. They should probably be disabled in upgrade tests for now. We have treated them as non-blocking. Network partition testing is inherently flakey.

@foxish PTAL

**Comment by foxish** [comment] 2017-11-28 17:13
+1 to what Ken said. It seems to me like the iptables rule injection to simulate a network partition is failing. I'll take a closer look today.

**Comment by foxish** [comment] 2017-11-29 21:22
@krzyzacy, it seems like this test fails in [gce-1.8-1.9-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-1.9-all#gce-1.8-1.9-upgrade-cluster&sort-by-failures=) but not in the gce or gke testing. I think the issue is that the cluster is brought up differently post upgrade. 

Is there a way we can disable the test in upgrade clusters only?

**Comment by krzyzacy** [comment] 2017-11-29 21:25
hummmm if we really want, we can tune ginkgo focus/skip filters for those suites

**Comment by foxish** [comment] 2017-11-29 21:31
The alternative there may be figuring out what's different between the 1.9 gce cluster setup post-upgrade, as opposed to a newly created 1.9 cluster. My suspicion is that it changes the API Server's IP address that the master and nodes use to communicate with each other.

**Comment by foxish** [comment] 2017-11-30 18:25
I've investigated further. There's no obvious issue I can see - given that this is causing noise, we'll disable these tests in all the upgrade suites and re-enable them after the fix is found.

**Comment by jberkus** [comment] 2017-11-30 21:34
If we're disabling this test, can we close the issue?  Or at least take it out of the milestone?

**Comment by spiffxp** [comment] 2017-12-01 18:00
@jberkus Not yet, I would like to wait until I see runs of the affected jobs with results for other tests, but missing results for these misbehaving tests.  As currently configured, testgrid is going to continue to show these as failing until we have 10 consecutive runs missing results for them.

**Comment by spiffxp** [comment] 2017-12-01 18:00
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by spiffxp** [comment] 2017-12-04 01:49
/reopen 
still failing, eg: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1165

**Comment by foxish** [comment] 2017-12-04 01:50
The previous fix didn't take. Will have a new fix shortly.

**Comment by spiffxp** [comment] 2017-12-06 02:36
@foxish this is still failing, eg: 
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1170
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/1650

Note these jobs are running release-1.8 tests against a cluster upgraded to master.  Does https://github.com/kubernetes/kubernetes/pull/56790 need to be cherry-picked back into release-1.8?

**Comment by jberkus** [comment] 2017-12-11 17:33
@foxish is there a new fix for this? Release is supposed to be this week.  Please update.

**Comment by foxish** [comment] 2017-12-11 18:53
This has already been disabled. https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-master&include-filter-by-regex=Network%20Partition

**Comment by enisoc** [comment] 2017-12-11 18:58
@jberkus Since this was classified as not a release-blocker, and we have disabled the tests in blocking jobs, I think we can remove it from the milestone.

**Comment by foxish** [comment] 2017-12-13 16:38
Closing in favor of https://github.com/kubernetes/kubernetes/issues/56787

**Closed by foxish** 2017-12-13 16:38 UTC
Labels: kind/bug, priority/failing-test, priority/important-soon, sig/apps, sig/node, status/approved-for-milestone, status/in-progress
