### ISSUE TITLE
When curling for stats summary containerd node, data on exited init containers is returned with empty cpu,mem,time

### ISSUE THREAD

**Issue by shahaf600** [kubernetes/kubernetes#73788] opened 2019-02-06 16:01 UTC
**What happened**:
When combining kubelet 1.11.3, with raw containerd v1.2.1 (running on CentOS with rpm[containerd-1.2.1-1.el7.x86_64]), there is a strange behavior, which is different from docker implementation.
when i curl 127.0.0.1:10255/stats/summary the data returned on an init container(exited container on node) i get back the following data:

```
{
      "name": "istio-init",
      "startTime": "2019-02-06T15:17:38Z",
      "cpu": {
       "time": null
      },
      "memory": {
       "time": null
      }
```
and when that happens, metrics-server(K8S component which scrapes all kuberneets nodes with this api and provide metrics to HPA so the cluster will be able to autoscale) with HPA have hard time to do scaling for all of the deployment which includes pods with those init containers.

and with docker that's works! why? because docker keeps the last metrics of init containers even after they finish their job. so when metrics-server tries to scrape for docker nodes everything is fine (I don't say it's okay because they include the calculation of dead containers into the autoscale math, but it covers on a bigger bug)

**What you expected to happen**:

I expected from the cadvisor or kubelet or containerd to not return information on dead containers because it mess up the whole process.

**How to reproduce it (as minimally and precisely as possible)**:

* install k8s 1.11.3 cluster with containerd 1.2.1 with centos with metric-server 0.3.1
* deploy a pod with init container
* curl that node 'curl 127.0.0.1:10255/stats/summary', and look for this init container

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: kubelet installed with centos service
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux kube-server-21 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubelet with init flags:
ExecStart=/usr/bin/kubelet --allow-privileged=true \
--cadvisor-port=4194 \
--cgroup-driver=cgroupfs \
--client-ca-file=/etc/pki/kubernetes_certs/ca.pem \
--cluster-dns=10.30.96.2 \
--cluster-domain=some-domain \
--cni-bin-dir=/opt/cni/bin \
--cni-conf-dir=/etc/cni/net.d \
--container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
--container-runtime=remote \
--cpu-manager-policy=none \
--kube-reserved-cgroup=podruntime.slice \
--kube-reserved=cpu=1,memory=3Gi \
--kubeconfig=/etc/kubernetes/kubelet_kubeconfig \
--kubelet-cgroups=/podruntime.slice \
--network-plugin=cni \
--node-labels=type=worker \
--pod-manifest-path=/etc/kubernetes/manifests \
--register-node=true \
--register-with-taints=taboola.com/new_node=true:NoSchedule \
--runtime-cgroups=/podruntime.slice \
--runtime-request-timeout=10m \
--system-reserved-cgroup=system.slice \
--system-reserved=cpu=1,memory=768Mi \
--tls-cert-file=/etc/pki/kubernetes_certs/*******************.com_cert.pem \
--tls-private-key-file=/etc/pki/kubernetes_certs/*****************.com_key.pem

/sig node
/sig scalability
/area kubelet
/area kubelet-api
/kind bug

**Comment by shahaf600** [comment] 2019-02-11 17:15
I would suggest here to kubernetes to not expose init containers that had done their job with the stats summary because it messes up the stats calculation.
Also it is good to mention that i downgraded metrics-server to v0.2.1 and configured it to scrape with the default period of time. Instead of 10 seconds as we did in v0.3.1.
And it seemed to solve the problem.

**Comment by littleroad** [comment] 2019-02-22 01:42
Duplicate of #74310

**Closed** 2019-09-09 14:57 UTC
Labels: area/kubelet, area/kubelet-api, kind/bug, lifecycle/rotten, sig/node
