### ISSUE TITLE
Failing Tests: [sig-instrumentation] Cluster level logging implemented by Stackdriver

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66778] opened 2018-07-30 13:44 UTC
# Failing Jobs
[sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-master)
# Failing Tests
[[sig-instrumentation] Cluster level logging implemented by Stackdriver should ingest events](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1351)
[[sig-instrumentation] Cluster level logging implemented by Stackdriver should ingest logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1351)
# Triage Results
[Cluster level logging implemented by Stackdriver should ingest events and Cluster level logging implemented by Stackdriver should ingest logs](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master)

/cc @tpepper @AishSundar 
/kind bug
/kind failing-test
/priority important-soon
/sig instrumentation
/milestone v1.12

**Comment by brancz** [comment] 2018-07-30 14:16
@coffeepac did we move this test to sig-gke?

In any case this is @piosz's territory :slightly_smiling_face: .

/assign @piosz 

(@loburm or @kawych if Piotr can't take care of this, could you assign this to appropriately to someone?)

**Comment by coffeepac** [comment] 2018-07-30 18:10
@brancz we didn't move this to sig-gke, I don't think that would be correct.  

however, starting with 1.12 this is behind a feature gate for e2e tests so it won't run most of the time.  We could cherry pick it back if that would clear the error.

**Comment by loburm** [comment] 2018-07-31 06:42
@serathius Could you take a look?

**Comment by serathius** [comment] 2018-07-31 08:24
Yup

**Comment by serathius** [comment] 2018-07-31 09:33
Problem was also visible on presubmits: https://k8s-testgrid.appspot.com/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gke
It was fixed already, can you rerun tests?

**Comment by coffeepac** [comment] 2018-08-06 20:26
is this still an issue?  we do have an option of feature-gating this so the test lives but doesn't block e2e.

**Comment by serathius** [comment] 2018-08-07 08:28
Problem was external, failing test suite is no longer caused by stackdriver.
@loburm can you close the issue?

**Comment by loburm** [comment] 2018-08-07 08:58
Unfortunately, I can't. Maybe someone else have enough permission to do it.

**Comment by brancz** [comment] 2018-08-07 09:10
I'm not sure I can, but I can try :slightly_smiling_face: 

/close

**Closed by brancz** 2018-08-07 09:10 UTC
Labels: kind/bug, kind/failing-test, milestone/needs-approval, priority/critical-urgent, sig/instrumentation
