### ISSUE TITLE
Apiserver is leaking go-routines

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#33472] opened 2016-09-26 09:54 UTC
We are observing that some clusters are leaking go-routines.

In particular, we observed clusters with 2 or 3 nodes that has 200.000+ go-routines.

However, this seem to be happening only on some clusters (not all of them).
I will try to provide more data when I have it.

@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment] 2016-09-26 09:54
@lavalamp

**Comment by lavalamp** [comment] 2016-09-26 17:21
My money would be on our timeout handling.

**Comment by smarterclayton** [comment] 2016-09-26 21:47
Is this on 1.4 or master branch?

**Comment by lavalamp** [comment] 2016-09-26 22:05
This would be in 1.3.x

**Comment by smarterclayton** [comment] 2016-09-26 22:20
Only in kubelet so far?  There was the one scheduler goroutine leak fixed.

**Comment by lavalamp** [comment] 2016-09-26 23:32
I thought this was in kube-apiserver, not kubelet.

**Comment by wojtek-t** [comment] 2016-09-27 05:14
@smarterclayton - it's apiserver

**Comment by krmayankk** [comment] 2016-09-27 09:03
@wojtek-t how does this issue manifest ? How did you measure the goroutines leak ?

**Comment by wojtek-t** [comment] 2016-09-27 09:30
@krmayankk - current number of go-routines is exported by one of the existing prometheus metrics.
Looking into graph of this metric over time (we have it internally) for some clusters, this is constantly growing.


However, note that this may be customer-load-specific, as this manifests only for some clusters, not for all of them.

**Comment by bogdando** [comment] 2016-09-28 09:09
Just a side comment, a bit of tl;dr. I was really impressed by the aforementioned go-routines' "birth control measures" https://github.com/kubernetes/kubernetes/issues/33472#issuecomment-249814281.  IMO, it could be *very* useful as well to automatically collect related code patterns from call stacks of long running/looking hanged/lost go-routines. And publish the most interesting findings in some Concurrency Anti-patterns blog for Go devs :) And I'm not joking. Would that be permanently blocked channels, working with IO of file descriptors, or deadlocks on a ```go foo.Lock()``` acquisition maybe? These type of issues end up being a nightmare for ops folks running leaky code in production. Just take a look how a neighbor project suffers https://github.com/docker/docker/issues?q=daemon+hangs+is%3Aopen

**Comment by smarterclayton** [comment] 2016-09-28 14:27
I haven't yet seen growth like this on our 1.3 clusters (I asked for additional monitoring on these clusters on this this morning) - however, we have a substantially different workload so that may help pin down the source.

**Comment by smarterclayton** [comment] 2016-09-28 14:28
Did you get a goroutine dump yet from any of those?

**Comment by wojtek-t** [comment] 2016-10-03 13:15
@smarterclayton - sorry for late response, I was on sick leave last week.

Yes - I already have something. I'm seeing 10s of thousand of go-routines of these 3 types:
```
goroutine 145519 [chan receive, 9511 minutes]:
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*Client).handleGlobalRequests(0xc823adb940, 0xc8232344e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/client.go:137 +0x4a
created by k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.NewClient
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/client.go:54 +0xe5
```

```
goroutine 38143 [chan receive, 9635 minutes]:
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readPacket(0xc8222de000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/handshake.go:124 +0x6d
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*mux).onePacket(0xc822772850, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/mux.go:224 +0x5e
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*mux).loop(0xc822772850)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/mux.go:199 +0x42
created by k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.newMux
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/mux.go:128 +0x20e
```

```
goroutine 11544 [IO wait, 9664 minutes]:
net.runtime_pollWait(0x7f7e2cbe0368, 0x72, 0xc8224da000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8221396b0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8221396b0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc822139650, 0xc8224da000, 0x1000, 0x1000, 0x0, 0x7f7e2cd4b050, 0xc820010130)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8211c54e0, 0xc8224da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8201a50e0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8201a50e0, 0xc820990220, 0x5, 0x5, 0x14, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f7e2cd65a78, 0xc8201a50e0, 0xc820990220, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f7e2cd65a78, 0xc8201a50e0, 0xc820990220, 0x5, 0x5, 0x134, 0x0, 0x0)
        /usr/local/go/src/io/io.go:315 +0x62
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*streamPacketCipher).readPacket(0xc820990200, 0xc800000009, 0x7f7e2cd65a78, 0xc8201a50e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/cipher.go:141 +0xc1
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc822955680, 0xc8201a50e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/transport.go:111 +0xce
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*transport).readPacket(0xc822955680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/transport.go:107 +0x55
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc822956960, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/handshake.go:153 +0xe7
k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc822956960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/handshake.go:133 +0x25
created by k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.newClientTransport
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/handshake.go:101 +0x31f
```

@smarterclayton @lavalamp - any thoughts on these?

**Comment by smarterclayton** [comment] 2016-10-03 17:22
This sounds like the TLS deadlock.

On Mon, Oct 3, 2016 at 9:15 AM, Wojciech Tyczynski <notifications@github.com

**Comment by smarterclayton** [comment] 2016-10-03 17:23
Is this related to
https://groups.google.com/forum/#!topic/golang-checkins/V_MARoQ1TVY?

**Comment by lavalamp** [comment] 2016-10-03 19:49
@cjcullen We have seen something similar in the past, haven't we? What was the resolution of that?

**Comment by wojtek-t** [comment] 2016-10-04 14:05
@bradfitz - can the stacktraces from above (https://github.com/kubernetes/kubernetes/issues/33472#issuecomment-251102678) be the reason of what @smarterclayton mentioned: https://groups.google.com/forum/#!topic/golang-checkins/V_MARoQ1TVY

**Comment by smarterclayton** [comment] 2016-10-04 17:27
It could also be a hang in crypto.ssh, but I ask because I believe we're
doing the SSH tunnel specifically to tunnel TLS underneath it.

**Comment by bradfitz** [comment] 2016-10-04 20:57
I see no TLS in the stack traces above, so this doesn't seem related to TLS at all.

**Comment by smarterclayton** [comment] 2016-10-04 21:32
@wojtek-t I would add a debug wrapper around the tls stream we proxy over ssh.  It's either a hang in the tunnel or a hang in the thing we send through the tunnel.  Go version?  

Any hung goroutines on the nodes?  And other similar goroutines?

**Comment by smarterclayton** [comment] 2016-10-04 21:33
*Any* other similar goroutines

**Comment by bradfitz** [comment] 2016-10-04 22:00
The problem is the net.Conn under the ssh connection went away and there are no TCP keep-alives and no deadlines on the read, so it's waiting forever for a reply that will never arrive.

Are you setting the ClientConfig.Timeout? https://godoc.org/golang.org/x/crypto/ssh#ClientConfig

Or find the thing that's making ssh connections and make sure that connection (TCP connection I assume?) has keep-alives enabled, and/or set the ReadDeadline during the dial/handshake, and then reset it back to be long, and then enable the ssh-level heartbeat mechanism.

Actualy, it looks like the ssh package doesn't have a knob for configuring ssh-level heartbeats. It should.

**Comment by cjcullen** [comment] 2016-10-05 22:16
@wojtek-t I'm assuming that these are all GKE clusters? And that these are likely caused by our passive attempts to keep tunnels open.

Previous ssh-related goroutine leaks have been from:
1. Not closing a response body: https://github.com/kubernetes/kubernetes/issues/24279
2. Hangs in ssh.Dial: https://github.com/kubernetes/kubernetes/issues/23835#issuecomment-205496791

This sounds like it might be the latter. When we "fixed" #23835, we decided that it would be more desirable to leak goroutines than to leave the apiserver without tunnels and unable to proxy. At the time, I think we determined that there wasn't a good way to timeout the ssh.NewClientConn call, but maybe @bradfitz has some insight.

Here is the potentially offending code (the timeout SSH dialer): https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L181

**Comment by wojtek-t** [comment] 2016-10-06 09:13
@bradfitz - do you have any thoughs about the above?

**Comment by bradfitz** [comment] 2016-10-06 17:40
I do. https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L181 can be simplified to be less twisty and more robust. I think the whole `timeoutDialer` vs `realDialer` distinction can go away. Just use `ssh.ClientConfig.Timeout`, or use `net.DialTimeout` and use `ssh.NewClient` with a `net.Conn` you supply, and then you can set TCP keep-alive on it.

**Comment by wojtek-t** [comment] 2016-10-06 19:34
@lavalamp - do you think you can find someone from CSI team to do it? [I'm happy to review], maybe @caesarxuchao ?

**Comment by dims** [comment] 2016-11-16 14:31
This needs to be triaged as a release-blocker or not for 1.5 @wojtek-t @cjcullen

**Comment by smarterclayton** [comment] 2016-11-16 16:52
Probably blocker.

**Comment by cjcullen** [comment] 2016-11-16 23:47
We should mark this as a release blocker. We believe we have a fix.

**Comment by dims** [comment] 2016-11-17 00:08
added release-blocker tag @cjcullen @smarterclayton

**Comment by wojtek-t** [comment] 2016-11-17 07:42
@cjcullen - great; is there already a PR for it? Can you point me to it?

**Comment by dims** [comment] 2016-11-18 13:52
@cjcullen - was it this? https://github.com/kubernetes/kubernetes/issues/35207 (fixed by https://github.com/kubernetes/kubernetes/pull/36451)?

**Comment by cjcullen** [comment] 2016-11-18 17:36
This one is fixed by #34302.

**Comment by dims** [comment] 2016-11-18 17:49
@cjcullen : let's talk on that PR.

**Comment by wojtek-t** [comment] 2016-11-21 12:29
@dims @cjcullen - since the PR fixing it was moved to 1.6, should we remove release-blocker from it?

**Comment by dims** [comment] 2016-11-21 12:40
yes thanks @wojtek-t doing it now

**Closed** 2016-12-30 02:07 UTC
Labels: priority/important-soon, sig/api-machinery, sig/scalability
