### ISSUE TITLE
Init container

### ISSUE THREAD

**Issue by tolomaus** [kubernetes/kubernetes#1589] opened 2014-10-05 18:42 UTC
Hi,
My current strategy for provisioning a new instance of my dockerized web app (rails+postgres) on a single docker host is to run a short-living docker container "app_db_init" that contains the initial state of the database files and that simply copies it to a convention-based location on the host.
The second step is to run a long-living container for the database "app_db" (using the previous location to mount a data volume) and then to run a long-living container for the app itself "app".

My challenge now is to port this whole setup to kubernetes. As both "app_db_init" and "app_db" obviously have to run on the same minion I have included them into one pod. THe problem now is that as "app_db_init" exits after copying the files it is continuously restarted by kubernetes.

I read about issue #159 and tried setting restartPolicy in the json structure but that didn't have any effect, probably I'm using the wrong format:

```
{
  "id": "app-db-test",
  "kind": "Pod",
  "apiVersion": "v1beta1",
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "app-db-test",
      "volumes":[{
        "name":"data", 
        "source":{"hostDir":{path: "/docker_data/app_db_test"}}
      }],      
      "containers": [{
        "name": "app-db-init-test",
        "image": "docker-registry/app_db_init:v1.0.0",
        "volumeMounts": [{
          "name": "data",
          "mountPath": "/data"
        }],
        "env": [{
          "name": "OVERWRITE_EXISTING_DATA",
          "value": "0"
        }]      
      },
      {
        "name": "app-db-test",
        "image": "docker-registry/app_db:v1.0.0",
        "ports": [{
          "name": "postgres",
          "containerPort": 5432,
          "hostPort": 5432
        }],
        "volumeMounts": [{
          "name": "data",
          "mountPath": "/var/lib/pgsql/data"
        }]
      }]
    }
  },
  "restartPolicy": "never", 
  "labels": {
    "name": "app-db-test"
  }
}
```
But even if it would work, I only want to have it applied to the first container, not the second, so the parameter should ideally be on the level of the container and not the pod.

Any suggestions on how to tackle this use case? Happy to re-architect my solution completely if it helps.

Thanks in advance,

Niek.

**Comment by bgrant0607** [comment] 2015-07-22 07:23
Closed #4282 as a dupe of this issue.
cc @cnaize @pythonpowerd @bkeroackdsc

**Comment by smarterclayton** [comment] 2015-11-11 06:09
As discussed at a recent community hangout it would be valuable to allow a pod to contain a single run once pod that functions as an "initializer" for the pod.  The initializer could do anything a regular container could do, including mutating filesystem or waiting for external services, or ensuring a remote system is ready to accept connections from this pod.  Many PreStop scenarios would instead be covered by this container (which can be a different image the primary containers).

We would have to define and implement a policy for how many init attempts could be made, and what happens on failure.

**Comment by bgrant0607** [comment] 2015-11-11 19:48
The init container should be in its own pid namespace.
cc @vishh

**Comment by smarterclayton** [comment] 2015-11-12 06:42
Draft concept:

1. Start the pod infra container
2. Setup networking
3. Initialize volumes
4. Start the "init" container and let it run to completion
5. Report init container status as normal from Kubelet
6. When init container succeeds, fails, or (maybe?) exceeds
InitDeadlineSeconds the container is terminated.  Any other result than
success should tear down the volumes and reset to step 3 (incrementing
restart counter on the init container)
7. Initialize the rest of the containers
8. The init container has condition initialized and condition ready?

It's tempting to use the name "init" as a special container name, which
means naive clients continue to see the pod as a set of containers (one of
which which happens first).  It does have backwards compatible expectations
if we were to change the init container name to be special.  We could
introduce a Boolean on a container to make it the init container and treat
>1 as a validation error.

On Nov 11, 2015, at 11:48 AM, Brian Grant <notifications@github.com> wrote:

The init container should be in its own pid namespace.
cc @vishh <https://github.com/vishh>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/1589#issuecomment-155891202>
.

**Comment by vishh** [comment] 2015-11-12 18:29
> 6. When init container succeeds, fails, or (maybe?) exceeds
InitDeadlineSeconds the container is terminated.  Any other result than
success should tear down the volumes and reset to step 3 (incrementing
restart counter on the init container)

I assume you are referring to volumes that are not `PV` here. 

> 8. The init container has condition initialized and condition ready?

If the init container is expected to run to completion, then why would readiness matter?

@thockin and @pmorie were discussing running the mounter for certain volumes as initializers. This approach will help account all resources consumed by such volumes to pods. The kubelet might have to run multiple initializers before starting user containers.

How will we handle volumes that need a daemon (ones that use FUSE for example)? The mount might have to show up before a consumer container starts running. In such cases, the side-car pattern will require users to implement some form of synchronization. Users might have to run a supervisor container that will restart the consumer container whenever the mounter container restarts. 
One option is to have first-class support for these kind of volumes in the kubelet. 
Another option is to allow long running initializer containers. A successful readiness probe for example, can be interpreted by the kubelet as success. A restart of such initializers should trigger restart of all the other containers.

**Comment by smarterclayton** [comment] 2015-11-12 21:34
Re: PV, yes, only tear down local volumes

Re: readiness, because clients need to interpret what the init container is
doing.

Re: multiple initializers, sounds pretty complex, but moving complex
mounters *out* of the Kubelet is one of the points of init.

Shouldn't fuse be a daemon set pod supporting a custom volume to the
Kubelet?

Cascading / long running initializers *sounds* like solving the wrong
problem.  Complex container start order also sounds like the wrong
problem.  But I don't know all the use cases, so we should describe them
here.


On Nov 12, 2015, at 1:30 PM, Vish Kannan <notifications@github.com> wrote:


   1. When init container succeeds, fails, or (maybe?) exceeds
   InitDeadlineSeconds the container is terminated. Any other result than
   success should tear down the volumes and reset to step 3 (incrementing
   restart counter on the init container)

I assume you are referring to volumes that are not PV here.


   1. The init container has condition initialized and condition ready?

If the init container is expected to run to completion, then why would
readiness matter?

@thockin <https://github.com/thockin> and @pmorie
<https://github.com/pmorie> were discussing running the mounter for certain
volumes as initializers. This approach will help account all resources
consumed by such volumes to pods. The kubelet might have to run multiple
initializers before starting user containers.

How will we handle volumes that need a daemon (ones that use FUSE for
example)? The mount might have to show up before a consumer container
starts running. In such cases, the side-car pattern will require users to
implement some form of synchronization. Users might have to run a
supervisor container that will restart the consumer container whenever the
mounter container restarts.
One option is to have first-class support for these kind of volumes in the
kubelet.
Another option is to allow long running initializer containers. A
successful readiness probe for example, can be interpreted by the kubelet
as success. A restart of such initializers should trigger restart of all
the other containers.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/1589#issuecomment-156193595>
.

**Comment by vishh** [comment] 2015-11-12 21:48
> Shouldn't fuse be a daemon set pod supporting a custom volume to the
Kubelet?

Yeah. With this approach though, the resource usage of FUSE daemon might
have to be accounted as infrastructure overhead.

**Comment by bgrant0607** [comment] 2015-11-19 23:36
We should ensure this composes well with the 2 flavors of volume discussed in #831.

**Comment by dchen1107** [comment] 2015-11-20 00:10
A couple of questions related to @smarterclayton's draft at: https://github.com/kubernetes/kubernetes/issues/1589#issuecomment-156015540

1) Does pod RestartPolicy apply to init container? Or treat init container as special case with Always by default? Or assume only Pod with Always can have init container? 
2) Do we allow more than one init container within a Pod?
3) Do we allow Pod with only init container? 
4) Should we introduce a new phase for Pod called Initialized? 
5) Can we assume when an init container run to completion with exit 0,  the environment for the user containers is truly initialized? No periodically check required?

**Comment by thockin** [comment] 2015-11-20 01:20
I don't like a special name because people have thus far been able to
assume that all containers[] have the same policies applied and could count
the number of entries and look for that in readiness.  I'd rather a new
field that is an optional api.Container.

regarding FUSE: I dont have a mental model of FUSE for various cluster
FS's.  Can one FUSE daemon handle multiple ceph/whatever clusters?  Are
there credentials involved?  Running FUSE daemons as the user in the user's
space means that we can account it.

I'm not sure that init is the right way to handle FUSE agents, but I have
not put deep thought into it yet.

**Comment by bgrant0607** [comment] 2015-11-20 03:02
My take on @dchen1107's questions:

1) No. init container executes once. If it fails, the pod fails.
2) No, one init container only, though I think we should also support volume containers (#831).
3) No, we don't allow pod with only an init container, until we allow empty pods and allow updates to add containers. The workaround is to have a pause container.
4) No new phases. Condition maybe, but there would need to be a reason why Ready wasn't sufficient.
5) Yes. We should forbid updates of the init container for now, for simplicity.

cc @kelseyhightower

**Comment by bgrant0607** [comment] 2015-11-20 03:05
Regarding a new field or magic name: A magic name is not very discoverable.

Should we report ContainerStatus for the init container?

**Comment by smarterclayton** [comment] 2015-11-20 22:13
Agree magic names are too magical.  Boolean init container makes naive
clients continue to see the init container, although the status behavior
will be different - init containers inside of a run-always pod can run to
completion, so an old client might assume that any exit code in the
container status of a run always pod means an error.  However... that's
probably a questionable check.  The other option is a new initContainer *
pointer, but old clients might assume that every container in container
status exists in pod.spec.containers and fail.  The last option is to
separate both spec and container status for init container, which means old
clients have no idea why their pod hasn't started.

I like the last one the most because it's the most declarative and forces
"at most one" init container thinking, but I hate that old clients wouldn't
see the status of the init pod.

**Comment by dchen1107** [comment] 2015-11-20 23:47
@smarterclayton I like the last option the most too. To resolve the old client issue, is it possible that we handle it specially at PodStatus conversion by translating initContainer failure to PodStatus.Reason?

**Comment by smarterclayton** [comment] 2015-11-24 01:38
Yeah, that's a good option.

On Nov 20, 2015, at 6:48 PM, Dawn Chen <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I like the last option
the most too. To resolve the old client issue, is it possible that we
handle it specially at PodStatus conversion by translating initContainer
failure to PodStatus.Reason?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/1589#issuecomment-158561146>
.

**Comment by erictune** [comment] 2015-11-24 22:10
Like new field approach of @thockin.  This is not a thing with the full generality of a `.spec.containers[]`.  It is a special purpose thing.  Probably quite a few fields of `api.Container` are forbidden for an init container.  Hence putting it in a different field.

**Comment by erictune** [comment] 2015-11-24 22:21
We've got two use cases here: the database setup described by the OP, and the FUSE use case described by @vishh.

In the OP's case, the init container is specified by the user.  In the FUSE case, the container to run would typically be provided by a cluster administrator and whitelisted, and may be automatically added by an admission controller.  

You might have a pod that needs both cases.  In order to compose those two cases, we need either separate fields for each, or a list.  Actually, since you could have several "volume setup Containers" that need to run, you probably need to have a list of these.

**Comment by smarterclayton** [comment] 2015-11-25 01:59
Which means more special purpose logic in pod security policy probably.

On Nov 24, 2015, at 5:10 PM, Eric Tune <notifications@github.com> wrote:

Like new field approach of @thockin <https://github.com/thockin>. This is
not a thing with the full generality of a .spec.containers[]. It is a
special purpose thing. Probably quite a few fields of api.Container are
forbidden for an init container. Hence putting it in a different field.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/1589#issuecomment-159421957>
.

**Comment by gurvindersingh** [comment] 2015-12-04 08:42
will this be part of 1.2 or even before ?

**Comment by erictune** [comment] 2015-12-09 19:02
Can there be multiple init containers?  If not, and if the user specifies an init container, then the "system" cannot add an init container.  Having the system add one could be very useful.  

Can init containers generate env vars that are put into the environment of the the main containers?  If so how?

**Comment by thockin** [comment] 2015-12-09 19:21
I think init containers and FUSE daemons are sort of different things, and
maybe need different solutions.

I see init containers as: a) always are "runOnce", b) bounded time, c) have
access to mounted volumes, d) are probably user-provided

I see FUSE daemons as: a) need a new restart policy "runUntilTermination"
(bad name, but the idea is to run until app containers are done), b) need
privs that the rest of the pod might not, c) don't need access to other
volumes, d) are generally not user-provided (e.g. ceph)

As for fetching container status, I had an idea.  Add a field to
status.containers[*] for restart policy.  We know that, by design, all
app-containers in a pod have the same restart policy, but init containers
have a different restart policy.  If we fan that out as part of status, we
could have all containers in a single status array.

**Comment by bprashanth** [comment] 2015-12-30 21:53
> 1. Start the pod infra container
2. Setup networking
3. Initialize volumes
4. Start the "init" container and let it run to completion

Inline with Eric's system vs user init container idea, can we drive 2 and 3 through init containers too? Eg: all pods could get a base init container that contains networking plugin binaries, runs with --privilege, host networking and has /proc mounted in. When invoked it will perform a CNI ADD. We'd need to run the same container on tear down though, so it won't be an "init" container.

**Comment by smarterclayton** [comment] 2015-12-30 22:09
If we do, those init containers have to be appropriately secured and
controlled.

**Comment by macropin** [comment] 2016-01-30 00:19
My 2c on this. We're coming over from fleet and we are used to chaining containers together for initialising applications. Without similar functionality in Kubernetes our deployments have become more difficult. 

I like the proposal in #1996. @bgrant0607 rejected the proposal on the grounds that it would make for complex restarts and updates. I don't believe this is an issue as the chained containers should be treated as a single entity. Only the last container in the chain needs to stay up. All the proceeding 'initialisation' containers perform **idempotent** tasks, and so in the case of failure it doesn't matter if they get restarted from the beginning of the chain.

**Comment by bgrant0607** [comment] 2016-01-30 00:37
Could you please explain more about your use case, @macropin ? Why do have multiple chained containers?

**Comment by macropin** [comment] 2016-01-30 12:22
@bgrant0607 For a database driven web app, we often make use of an intermediate container to ensure that the connected database has been initialised. As a concrete example, this allows us to provide a Wordpress container that is automatically configured with an attached MySQL instance (database and user automatically created). Previously we would have even injected updated environment variables into the final container (eg generate passwords, if not already defined), but since this is not possible with Kubernetes we've found workarounds.

**Comment by munnerz** [comment] 2016-03-26 20:50
I also have a need for an init pod, my use-case is a CI system: I need to run git within a container to clone a repository, before the actual build image is run using the cloned repo (so I'd require the init container to be able to access the pods volumes). I don't want to require a user have git installed in their build container. It seems the proposals discussed here cover my use-case well though.

**Comment by smarterclayton** [comment] 2016-03-29 02:18
Opened https://github.com/kubernetes/kubernetes/pull/23567 to see if we can reach a quick agreement on an API design - if so, this is relatively low hanging fruit for 1.3 and would help a number of scenarios for extending pod function.

I was motivated by the fact that I'm blocked in building out a secure build function that allows containers to split responsibilities safely, and by there being no way today to parameterize config without mutating an image.

**Comment by ncdc** [comment] 2016-06-03 18:29
@smarterclayton @kubernetes/sig-node ok to close this since #23567 has merged?

**Comment by smarterclayton** [comment] 2016-06-03 18:42
I need to land the proposal and docs.

**Comment by smarterclayton** [comment] 2016-06-16 20:12
Is there a reason this was removed from the milestone?  It's delivered, it just needs docs.

**Comment by smarterclayton** [comment] 2016-06-16 21:05
Docs PR opened, going to close this as complete (since the proposal won't land for 1.3)

**Closed by smarterclayton** 2016-06-16 21:05 UTC
Labels: area/stateful-apps, kind/feature, priority/P1, team/api, team/node, team/redhat
