### ISSUE TITLE
SkyDNS does not work when using it with Kubernetes Docker multinode setup

### ISSUE THREAD

**Issue by deromka** [kubernetes/kubernetes#23111] opened 2016-03-17 11:13 UTC
I'm running kubernetes docker containers on CentOS Linux release 7.2.1511, 3.10.0-327.10.1.el7.x86_64. 
I'm using the following script to run the kube-master [link](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh) 
and the following script to run the SkyDNS [link](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/skydns.yaml.in) I'm updating the the places with {{ pillar }} to the actual values as suggested by the tutorial: http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/

I'm using kubernetes 1.2.0-alpha.7

Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-beta.0", GitCommit:"50f7568d7f9b001c90ed75e79d41478afcd64a34", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.7", GitCommit:"c0fd002fbb25d6a6cd8427d28b8ec78379c354a0", GitTreeState:"clean"}

`
[local@kube-master-1458129646 ~]$ kubectl cluster-info
Kubernetes master is running at http://10.57.50.181:8080
KubeDNS is running at http://10.57.50.181:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
`
When accessing the following URL: [http://10.57.50.181:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns](http://10.57.50.181:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns) I get the following:

`
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
`

`[local@kube-master-1458129646 ~]$ kubectl describe svc
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			10.0.0.1
Port:			https	443/TCP
Endpoints:		10.57.50.181:6443
Session Affinity:	None
No events.
`

`
[local@kube-master-1458129646 ~]$ kubectl describe svc --namespace=kube-system
Name:			kube-dns
Namespace:		kube-system
Labels:			k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS
Selector:		k8s-app=kube-dns
Type:			ClusterIP
IP:			10.0.0.10
Port:			dns	53/UDP
Endpoints:		
Port:			dns-tcp	53/TCP
Endpoints:		
Session Affinity:	None
No events.
`

Here are the logs:

**kube2sky logs**

`I0317 10:58:02.475909       1 kube2sky.go:462] Etcd server found: http://127.0.0.1:4001
I0317 10:58:03.478586       1 kube2sky.go:529] Using https://10.0.0.1:443 for kubernetes master
I0317 10:58:03.478612       1 kube2sky.go:530] Using kubernetes API <nil>
I0317 10:58:03.479278       1 kube2sky.go:598] Waiting for service: default/kubernetes
I0317 10:58:04.480549       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.
I0317 10:58:06.484404       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.
I0317 10:58:08.488550       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.
`

**skydns logs**

`
2016/03/17 09:39:55 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [3]
2016/03/17 09:39:55 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/03/17 09:39:55 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
2016/03/17 09:40:17 skydns: failure to forward request "read udp 10.56.190.1:53: no route to host"
2016/03/17 09:40:20 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
2016/03/17 09:40:27 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
2016/03/17 09:40:31 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
2016/03/17 09:40:38 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
2016/03/17 09:40:42 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
2016/03/17 09:40:49 skydns: failure to forward request "read udp 10.56.190.1:53: i/o timeout"
`

**etcd logs**
`
2016-03-17 09:39:52.074261 I | etcdmain: etcd Version: 2.2.1
2016-03-17 09:39:52.074324 I | etcdmain: Git SHA: 75f8282
2016-03-17 09:39:52.074335 I | etcdmain: Go Version: go1.5.1
2016-03-17 09:39:52.074343 I | etcdmain: Go OS/Arch: linux/amd64
2016-03-17 09:39:52.074384 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2016-03-17 09:39:52.074974 I | etcdmain: listening for peers on http://localhost:2380
2016-03-17 09:39:52.075239 I | etcdmain: listening for peers on http://localhost:7001
2016-03-17 09:39:52.075304 I | etcdmain: listening for client requests on http://127.0.0.1:2379
2016-03-17 09:39:52.075406 I | etcdmain: listening for client requests on http://127.0.0.1:4001
2016-03-17 09:39:52.075813 I | etcdserver: name = default
2016-03-17 09:39:52.075829 I | etcdserver: data dir = /var/etcd/data
2016-03-17 09:39:52.075837 I | etcdserver: member dir = /var/etcd/data/member
2016-03-17 09:39:52.075844 I | etcdserver: heartbeat = 100ms
2016-03-17 09:39:52.075851 I | etcdserver: election = 1000ms
2016-03-17 09:39:52.075857 I | etcdserver: snapshot count = 10000
2016-03-17 09:39:52.075874 I | etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2016-03-17 09:39:52.075887 I | etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2016-03-17 09:39:52.075906 I | etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2016-03-17 09:39:52.077919 I | etcdserver: starting member 6a5871dbdd12c17c in cluster f68652439e3f8f2a
2016-03-17 09:39:52.077997 I | raft: 6a5871dbdd12c17c became follower at term 0
2016-03-17 09:39:52.078027 I | raft: newRaft 6a5871dbdd12c17c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-03-17 09:39:52.078036 I | raft: 6a5871dbdd12c17c became follower at term 1
2016-03-17 09:39:52.078279 I | etcdserver: starting server... [version: 2.2.1, cluster version: to_be_decided]
2016-03-17 09:39:52.079411 N | etcdserver: added local member 6a5871dbdd12c17c [http://localhost:2380 http://localhost:7001] to cluster f68652439e3f8f2a
2016-03-17 09:39:52.878477 I | raft: 6a5871dbdd12c17c is starting a new election at term 1
2016-03-17 09:39:52.878553 I | raft: 6a5871dbdd12c17c became candidate at term 2
2016-03-17 09:39:52.878574 I | raft: 6a5871dbdd12c17c received vote from 6a5871dbdd12c17c at term 2
2016-03-17 09:39:52.878600 I | raft: 6a5871dbdd12c17c became leader at term 2
2016-03-17 09:39:52.878666 I | raft: raft.node: 6a5871dbdd12c17c elected leader 6a5871dbdd12c17c at term 2
2016-03-17 09:39:52.879294 I | etcdserver: setting up the initial cluster version to 2.2
2016-03-17 09:39:52.879432 I | etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379 http://127.0.0.1:4001]} to cluster f68652439e3f8f2a
2016-03-17 09:39:52.880946 N | etcdserver: set the initial cluster version to 2.2
2016-03-17 11:03:10.579853 I | etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
2016-03-17 11:03:10.582194 I | etcdserver: saved snapshot at index 10001
2016-03-17 11:03:10.582470 I | etcdserver: compacted raft log at 5001
`

I have exactly followed the tutorial: [docker multinode setup](http://kubernetes.io/docs/getting-started-guides/docker-multinode/), but I cannot make the SkyDNS work

What am I missing? Or it is a bug in the scritps?

**Comment by agunnerson-explorys** [comment] 2016-03-17 16:02
I don't believe this is an issue with the docker multinode setup. I'm running into the same issue on a bare metal CentOS 7 mini-cluster (1 master, 4 nodes).

`skydns-rc.yaml`: https://gist.github.com/agunnerson-explorys/7e0b3fc9000addc56d46

kube2sky logs:
```
I0317 15:55:49.548831       1 kube2sky.go:462] Etcd server found: http://127.0.0.1:4001
I0317 15:55:50.550597       1 kube2sky.go:529] Using http://localhost:8080 for kubernetes master
I0317 15:55:50.550613       1 kube2sky.go:530] Using kubernetes API <nil>
I0317 15:55:50.550708       1 kube2sky.go:598] Waiting for service: default/kubernetes
I0317 15:55:50.551731       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:51.552440       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:52.553325       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:53.554167       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:54.555036       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:55.555980       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:56.556922       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:57.557748       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:58.558709       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:55:59.559389       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:00.560354       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:01.561403       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:02.562453       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:03.563269       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:04.564076       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:05.564919       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:06.565839       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
I0317 15:56:07.566840       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying.
```

I don't see anything unusual on the `kube-apiserver` side of things:

```
[andrew.gunnerson@pd-kube-master ~]$ sudo systemctl status -l kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-03-17 11:55:31 EDT; 39s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 3330 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─3330 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://pd-kube-master.explorys.net:2379 --insecure-bind-address=0.0.0.0 --allow-privileged=false --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota --service_account_key_file=/etc/kubernetes/service.key

Mar 17 11:55:28 pd-kube-master systemd[1]: Starting Kubernetes API Server...
Mar 17 11:55:28 pd-kube-master kube-apiserver[3330]: I0317 11:55:28.748404    3330 plugins.go:71] No cloud provider specified.
Mar 17 11:55:29 pd-kube-master kube-apiserver[3330]: I0317 11:55:29.031542    3330 master.go:379] Node port range unspecified. Defaulting to 30000-32767.
Mar 17 11:55:29 pd-kube-master kube-apiserver[3330]: I0317 11:55:29.033036    3330 master.go:401] Will report 10.0.26.67 as public IP address.
Mar 17 11:55:29 pd-kube-master kube-apiserver[3330]: [restful] 2016/03/17 11:55:29 log.go:30: [restful/swagger] listing is available at https://10.0.26.67:6443/swaggerapi/
Mar 17 11:55:29 pd-kube-master kube-apiserver[3330]: [restful] 2016/03/17 11:55:29 log.go:30: [restful/swagger] https://10.0.26.67:6443/swaggerui/ is mapped to folder /swagger-ui/
Mar 17 11:55:29 pd-kube-master kube-apiserver[3330]: I0317 11:55:29.129119    3330 server.go:622] Serving securely on 0.0.0.0:6443
Mar 17 11:55:31 pd-kube-master kube-apiserver[3330]: I0317 11:55:31.973389    3330 server.go:634] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
Mar 17 11:55:31 pd-kube-master kube-apiserver[3330]: I0317 11:55:31.973431    3330 server.go:664] Serving insecurely on 0.0.0.0:8080
Mar 17 11:55:31 pd-kube-master systemd[1]: Started Kubernetes API Server.
```

**Comment by fgrzadkowski** [comment] 2016-03-17 20:54
@kubernetes/sig-network @thockin @bprashanth

**Comment by bprashanth** [comment] 2016-03-17 21:17
@deromka can you run: https://github.com/kubernetes/kubernetes/blob/master/test/images/clusterapi-tester/pod.yaml and kubectl logs on that pod when it's running, it should show you the services in your cluster. If it doesn't, you have problems connecting to apiserver from a pod. 

@agunnerson-explorys what are your client/server versions? (kubectl version)

**Comment by agunnerson-explorys** [comment] 2016-03-18 14:47
@bprashanth Here are the versions:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"86327329213fed4af2661c5ae1e92f9956b24f55", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"86327329213fed4af2661c5ae1e92f9956b24f55", GitTreeState:"clean"}
```

They're the official packages from RHEL7/CentOS 7:

```
kubernetes-client-1.2.0-0.6.alpha1.git8632732.el7.x86_64
kubernetes-master-1.2.0-0.6.alpha1.git8632732.el7.x86_64
```

I actually rebuilt the cluster using the Ansible scripts from contrib and I'm not seeing this issue anymore. Those scripts were doing quite a few things that weren't in the documentation (like creating keys) which I suspect to have fixed whatever was causing the issue.

**Comment by bprashanth** [comment] 2016-03-18 15:37
go team ansible scripts!
I think @mikedanese is making cluster bootstrap scripts more robust in general

**Comment by huggsboson** [comment] 2016-03-20 02:32
I had issues with service account tokens ceasing to function after multiple runs of comtainerized kubelet due to state accumulating in /var/lib/kubelet.  kube2sky also showed "Using kubernetes API <nil>" for me.  I can give you a more direct way to test if it's service accounts when I get back to my computer, but if you want to try clearing out /var/lib/kubelet (umount all things under there first) and starting the cluster again.  That also tests it.

**Comment by zebulonj** [comment] 2016-03-23 19:33
I'm seeing something similar, running `kube2sky` on kubernetes v1.1.2 and CoreOS.

```
I0323 19:05:32.157816       1 kube2sky.go:462] Etcd server found: http://127.0.0.1:4001
I0323 19:05:33.159571       1 kube2sky.go:529] Using https://10.3.0.1:443 for kubernetes master
I0323 19:05:33.159592       1 kube2sky.go:530] Using kubernetes API <nil>
I0323 19:05:33.160011       1 kube2sky.go:598] Waiting for service: default/kubernetes
```

**Comment by bprashanth** [comment] 2016-03-23 19:57
@zebulonj can you try https://github.com/kubernetes/kubernetes/issues/23111#issuecomment-198085950?

**Comment by huggsboson** [comment] 2016-03-23 20:01
When I see "Using kubernetes API <nil>" as opposed to "Using kubernetes API v1" that usually indicates that the pod is unable to authenticate with the API.  Can you try running stopping the cluster and running:

mount | grep -o 'on /var/lib/kubelet.* type' | cut -c 4- | rev | cut -c 6- | rev | xargs --no-run-if-empty sudo umount
sudo rm -Rf /var/lib/kubelet

(If you are using docker-machine do docker-machine ssh <machine name, usually default> first)

**Comment by zebulonj** [comment] 2016-03-23 20:25
@bprashanth The tester output appears to confirm:
```
2016/03/23 20:21:53 Failed to list nodes: the server has asked for the client to provide credentials (get nodes)
```

@bprashanth @huggsboson Assuming that the pod is unable to authenticate with the API, what might cause that?

**Comment by bprashanth** [comment] 2016-03-23 20:42
Misconfigured clusters. do you have a service account in the same namespace ? did it create the token secret ? does your pod have a volume mount for the same secret? did the kubelet mount the tokens in the pod at the given mountpath? and is this token actually a valid token the apiserver recognizes, with the current certs it has.

**Comment by huggsboson** [comment] 2016-03-23 21:05
I've described the issue I had here:
https://github.com/kubernetes/kubernetes/issues/23197

Basically if you are stopping and starting the kubelet (in hyperkube) a bunch of times it looks like the state in /var/lib/kubelet eventually breaks service account tokens.

**Comment by zebulonj** [comment] 2016-03-24 16:54
@bprashanth Where can I learn more about how the pod authenticates to the API?

> Misconfigured clusters. do you have a service account in the same namespace ? did it create the token secret ? does your pod have a volume mount for the same secret? did the kubelet mount the tokens in the pod at the given mountpath? and is this token actually a valid token the apiserver recognizes, with the current certs it has.

I didn't explicitly do anything vis-a-vis authentication the first time I created the pod (replication controller), so if authentication depends on a mounted secret, token, etc., then it must be part of the internal machinery of kubernetes?

This is a cluster that had been working fine for 3-4 weeks, so I don't think it was simply misconfigured. Lends credibility to @huggsboson observation that after multiple restarts the state of service account tokens breaks. I'd love to have a better understanding of the authentication mechanism so I can continue to investigate.

**Comment by huggsboson** [comment] 2016-03-24 18:19
@zebulonj Can you try clearing out /var/lib/kubelet to test my theory?

**Comment by huggsboson** [comment] 2016-03-24 18:32
For a little more context on how service account tokens work.  Basically when a serviceAccount is created (there is always a default per namespace) the master (controller-manager) will will create a token and encrypt it using its private key, create a secret and associate it with the default serviceAccount.  This token is then automatically submitted by kube2sky to the API (using HTTP Authorization: Bearer token value).  The apiserver then verifies the token is valid by decrypting it using the master's public key. 

With hyperkube 

My working theory is there is a race between the setup-files containers, the manager and the apiserver.  Where the manager or apiserver uses the certs generated by the previous cluster run and then the other one gets the certs used by the latest run of setup files thereby leading to tokens that can not be verified by the apiserver.

**Comment by bprashanth** [comment] 2016-03-25 15:55
Possible, @mikedanese @liggitt for bearer token race

**Comment by liggitt** [comment] 2016-03-25 15:59
The same service account key should be used

**Comment by huggsboson** [comment] 2016-03-25 16:55
Just to be clear about things I know:
1. I know that the issue is related to service account tokens not functioning correclty
2. This is reproducible, turnup and turndown the cluster a few times and then try to use service account tokens.
3. I know that /var/lib/kubelet has some state in it that is causing this because if I blow it away between runs I don't have any issues.

Let me dive into my theory.

When people are using the moral equivalent of the turnup and turndown scripts, they create the containers and then destroy them (but don't clear /var/lib/kubelet where all [emptyDir](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/master.json) and secrets mounts live).  The [setup-files.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/setup-files.sh) script writes to an empty dir which are shared by apiserver (the thing that verifies  tokens) and controller-manager (the thing that mints and signs tokens).  When kubelet starts a pod from an on-disk file it gets the same pod-id every time, so any emptyDirs that were mounted will have the files in there from before (because we didn't kill /var/lib/kubelet).

My guess is:
1. apiserver starts up with certs from previous kube-up.  controller-manager waits for the api to become available to create the token in a secret.
2. setup-files.sh completes
3. controller-manager sees the api-server starts up and mints/signs the token and creates the secret with the token and cert (which is also broken) but with the now modified ca.crt and keyfile that setup-files.sh wrote.

An easy way to test this theory would be to have setup-files.sh exit early if the ca.crt and keys are already generated.  I won't have time over the next few days to work on this so if someone wants to try it out, I'd gladly help out in anyway I can.

BTW: I'm tracking what I believe is the underlying issue at #23197.

**Comment by liggitt** [comment] 2016-03-25 18:03
Service account tokens are stored in etcd. If the same etcd is used between multiple cluster starts, the same service account private/public key must be used, or the tokens stored in etcd will no longer validate.

**Comment by maxwell92** [comment] 2016-05-05 13:37
RUN: kubectl get secret --namespace=kube-system.
then delete the secret and all of kube-dns svc, rc.
finally ./deployAddons.sh

**Comment by luxas** [comment] 2016-05-15 12:41
I think this is fixed with #23550, and it's in the latest `v1.2.x` release.
Closing as probably fixed, @deromka reopen if it didn't work

**Closed by luxas** 2016-05-15 12:41 UTC
Labels: dependency/docker, team/node

**Comment by nvnobelen** [comment] 2016-05-18 18:59
It does not look like it is fixed:
Environment: coreos hyperkube 1.2.3

Test by re-creating the certificates and rebooting the environment:
kubectl get secret --namespace=kube-system 
will show an old secret and cause (at least) kube2sky to fail with any of the above indicated errors.
Manual action on removing the secret is still required to get it to work again

**Comment by axper** [comment] 2016-05-31 17:11
Please reopen, I am still having this issue with kubernetes 1.2.4.

**Comment by santanu-dey** [comment] 2016-07-09 12:24
Still experiencing a similar issues 1.3.0 and upto 1.4.0-alpha.0

In my case (docker based set up), either trusty or kubedns would get unauthorized from api server. 

and strangely I see that the secrets are not there inside the instances, under  the path /var/run/secrets/kubernetes.io/serviceaccount 

```
     [root@ ... ]#  kubectl exec -it kube-dns-v13-htfjo ls /bin/sh
     / #
     / # ls /var/run/secrets/kubernetes.io/serviceaccount
     / #
```

While it seems they are in the node and in the proxy instance 
```
tmpfs on /var/lib/kubelet/pods/3de53b0c-45bb-11e6-9f03-08002776167a/volumes/kubernetes.io~secret/default-token-8axd8 type
tmpfs on /var/lib/kubelet/pods/3de5591e-45bb-11e6-9f03-08002776167a/volumes/kubernetes.io~secret/default-token-8axd8 type
tmpfs on /var/lib/kubelet/pods/f29f35c7-45cc-11e6-9f03-08002776167a/volumes/kubernetes.io~secret/default-token-ql88q type
```

- Deleting the secret and deleting the pods then recreating them has no effect 
- Restarting cluster after unmounting & deleting the folders has no effect either

**Comment by thockin** [comment] 2016-07-10 05:35
@santanu-dey Rather than re-opening, can you file a new bug please?  Include:

Is this just kube-dns or do you get secrets mounted on ANY pods?

if you `ls /var/lib/kubelet/pods/*/volumes/kubernetes.io~secret/default-token-*` what do you see?

**Comment by santanu-dey** [comment] 2016-07-17 10:02
As of now it is a general no secrets getting mounted issue. 
My problem has been solved with a workaround suggested in an already existing bug  #26943 
So hopefully I do not need to open a new one.
