### ISSUE TITLE
Building with Go 1.4.3 fails scalability tests but Go 1.4.2 passes

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#17524] opened 2015-11-19 19:33 UTC
Earlier this week I moved the Jenkins jobs performing our builds of master, release-1.0, and release-1.1 (which run `hack/jenkins/build.sh`) from the Jenkins master to a Jenkins slave.

Immediately afterwards, the scalability tests started failing:
```
Density [Skipped] [Performance suite] should allow starting 30 pods per node
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:111
There should be no high-latency requests
Expected
    <int>: 1
not to be >
    <int>: 0

Load capacity [Skipped] [Performance suite] should be able to handle 30 pods per node
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:65
Expected
    <int>: 3
not to be >
    <int>: 0
```

When I moved the builds back to the Jenkins master, the scalability tests started passing again.

This doesn't match my understanding of our build jobs: since they run in Docker, they *should* be hermetic, producing the same outputs, but apparently something is different.

cc @kubernetes/goog-testing @zmerlynn @wojtek-t

**Comment by ixdy** [comment] 2015-11-19 19:33
We may also want to run the scalability tests with one of our official releases to see if there's something special going on with either the Jenkins master or slave.

**Comment by ixdy** [comment] 2015-11-19 19:56
https://goto.google.com/k8s-test/job/kubernetes-e2e-gce-scalability-1.1/146/ is a one-off run I just started which is using release/v1.1.2. We'll see how it goes.

**Comment by ixdy** [comment] 2015-11-19 22:49
The `release/v1.1.2` scalability test passed, which suggests there's something weird about the Jenkins slave.

**Comment by ihmccreery** [comment] 2015-12-03 00:54
@ixdy I'm bumping this down to P2.  If you're actively working on it, please assign it to yourself & up it back to P1.

**Comment by ixdy** [comment] 2016-01-15 22:18
cc @david-mcmahon this is the issue I mentioned last week.

**Comment by ixdy** [comment] 2016-01-19 20:52
Theory currently being tested: the Jenkins master had a stale version of the `golang:1.4.2` docker image, and the build was using this (since its Dockerfile only specifics `golang:1.4`). The Jenkins slave would've had a more recent golang image (probably 1.4.3).

**Comment by ixdy** [comment] 2016-01-20 00:33
After reverting the Jenkins master to `golang:1.4.2`, both the master and release-1.1 scalability suites passed again, so it's looking more and more like this is the root cause (though I don't understand why).

cc @gmarek

**Comment by ixdy** [comment] 2016-01-20 00:46
Assuming I'm reading the tea leaves correctly, the official release tarballs for both v1.1.2 and v1.1.3 were built with go1.4.2:
```
$ strings kubernetes/server/bin/kubelet | grep go1.4
go1.4.2
```

**Comment by ixdy** [comment] 2016-01-20 00:49
Whereas v1.1.4 used go1.4.3:
```
$ strings kubernetes/server/bin/kubelet | grep go1.4
go1.4.3
```

**Comment by ixdy** [comment] 2016-01-20 02:50
cc @kubernetes/sig-scalability

**Comment by timothysc** [comment] 2016-01-20 03:35
It is likely exposing subtle behavioral differences that manifest themselves as timing shifts or data-races.

**Comment by gmarek** [comment] 2016-01-20 09:19
It's the most visible effect, as it's a really big one.

**Comment by ixdy** [comment] 2016-01-25 21:28
Given that go 1.5.3 doesn't seem to have the same sort of regression, do we care to investigate what's broken in 1.4.3?

**Comment by timothysc** [comment] 2016-01-25 21:34
I would vote no, b/c there are other reasons why we want 1.5.3.

**Comment by gmarek** [comment] 2016-02-01 14:48
+1 to what @timothysc. We have enough more important things to do. I think we should close this issue.

**Comment by ixdy** [comment] 2016-02-01 20:20
Closing as "mystery still not solved".

**Closed** 2016-02-01 20:19 UTC
Labels: area/build-release, area/performance, area/test, priority/P1, team/test-infra

**Comment by rsc** [comment] 2016-02-19 00:08
Hi, Go team here. David Crawshaw pointed this issue out to me. We'd really like to understand both this and the problems you found with Go 1.5. The problem with Go 1.4.3 is interesting because _so little_ changed between Go 1.4.2 and Go 1.4.3. If there's a real regression there, perhaps it is the same one you hit trying Go 1.5, and there's a lot less to look through. Specifically:

$ git log --oneline go1.4.2..go1.4.3
50eb39b [release-branch.go1.4] go1.4.3
5d9c280 [release-branch.go1.4] doc: document go1.4.3
cb65428 [release-branch.go1.4] net/http: backport some potential request smuggling vectors from Go 1.5
8f33959 [release-branch.go1.4] net/http: harden Server against request smuggling
8f42967 [release-branch.go1.4] net/textproto: don't treat spaces as hyphens in header keys
e938de2 [release-branch.go1.4] runtime: don't return a slice with nil ptr but non-zero len from growslice
a527bdb cmd/dist: remove -Werror from CFLAGS
$

Honestly I can't see how any of those would have affected the performance of your test. All the more reason to try to reproduce it and track it down. And hopefully that experience will help when we move on to understanding why Go 1.5 doesn't work for you and then checking whether Go 1.6 does.

Please do feel free to file issues against golang/go for this kind of thing too, or at least to @-summon me. If I can't help, I'll find the right person to help for a particular issue.

Thanks very much.

**Comment by gmarek** [comment] 2016-02-19 05:50
cc @zmerlynn @lavalamp @davidopp @thockin @smarterclayton

**Comment by zmerlynn** [comment] 2016-02-19 15:05
@gmarek: You're probably some of the most versed in what was actually broken if you want to dive in and help. We never did exactly find a tight repro, but we do need to figure out a roll forward plan at some point.

I do know that 1.4.2 -> 1.4.3 pretty much broke our scalability tests across the board, but I can't speak to why.

**Comment by gmarek** [comment] 2016-02-19 15:23
Yeah - I was going to reply a bit more to this, but I got swamped with v1.2 stuff:/

IIRC (I may mix 1.4.3 with 1.5 issues as they happened close to each other) the repro was trivial - density30 tests on 100 nodes were reliably broken for branch v1.1 - issue was filed by @bprashanth: #19773, and we had an internal tracking bug as well.

I'll be more than happy to help you (@rsc) guys debug it. I guess cb65428 looks most suspicious, but I'm not sure it's that. I can try running those tests again with 1.4.3 to verify that I can reproduce the problem, and if you can provide some easy way to get a compiler with only one of those patches merged, I can play with those.

**Comment by lavalamp** [comment] 2016-02-19 18:02
Yeah, we should try a repro first. Clearly we can't stay on go1.4.2 forever, so we're very interested in tracking this down. ...we're also in the middle of getting a release out the door, though.

**Comment by gmarek** [comment] 2016-02-19 18:12
I'm afraid that I'll have time after we release 1.2, as there's too much stuff going on right now:/
