### ISSUE TITLE
Pods are not being assigned to ALL nodes.

### ISSUE THREAD

**Issue by soundofjw** [kubernetes/kubernetes#11909] opened 2015-07-27 23:26 UTC
I have a cluster (running on google container engine) with **4 nodes** and **8 pods**.

All 4 nodes are **Ready**.

However, when viewing Pods grouped by Node, all of my pods are distributed amongst 3 nodes (not 4).

![image](https://cloud.githubusercontent.com/assets/739668/8920262/e906aaa6-347b-11e5-9007-9f15819a95d3.png)

So - **why aren't all nodes being utilized?**

(The pods were launched well after all nodes became 'Ready' :D)

## Version

```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

**Comment by bprashanth** [comment] 2015-07-29 06:00
That's weird. Can you supply more information? (kubectl describe node <bad node>, kubectl get pods -o wide --all-namespaces,  kubectl get events <bad node>, /var/log/kube-scheduler.log from your master node). Some obvious reasons the scheduler might ignore a node are: host port conflict, node-labels, not enough resource, though the latter is less likely since you said you have no pods on the node.

**Comment by derekwaynecarr** [comment] 2015-07-29 18:50
Are the pods managed by a replication controller?
Are the pods load balanced by a service?

**Comment by soundofjw** [comment] 2015-07-29 22:13
Thanks for the followup!

## General setup

Pods are managed by replication controller.
One load balancer/service is made available to a handful of those pods.

## kubectl describe node
```
Name:			gke-es-reporting-v1-3f8429d3-node-n7g3
Labels:			kubernetes.io/hostname=gke-es-reporting-v1-3f8429d3-node-n7g3
CreationTimestamp:	Sat, 25 Jul 2015 03:40:22 -0700
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	True 	Wed, 29 Jul 2015 15:09:49 -0700 	Sat, 25 Jul 2015 03:40:53 -0700 	kubelet is posting ready status
Addresses:	10.240.181.207,104.197.51.125
Capacity:
 cpu:		4
 memory:	26813848Ki
 pods:		40
Version:
 Kernel Version:		3.16.0-0.bpo.4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://Unknown
 Kubelet Version:		v1.0.1
 Kube-Proxy Version:		v1.0.1
PodCIDR:			10.248.1.0/24
ExternalID:			9508614722499215901
Pods:				(3 in total)
  Namespace			Name
  kube-system			fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-n7g3
  kube-system			kube-dns-v8-hfbxp
  kube-system			kube-ui-v1-1yy5q
No events.
```

## kubectl get pods -o wide --all-namespaces

Well I didn't know about this command, but I'm sure herein lies my answer. There ARE pods there, they are just the kube-system pods. This is all fine, minus the part where I have a LOT of free resources not used by kubernetes master that could be utilized (sometimes my namespace PODs HAVE ended up on all nodes, in other setups...)

```
NAMESPACE     NAME                                                           READY     STATUS    RESTARTS   AGE       NODE
default       es-reporting-data-v3-r1-fs7kg                                  1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-uu2y
default       es-reporting-data-v3-r2-jqa5q                                  1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-hdho
default       es-reporting-data-v3-r3-93uhw                                  1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-iz9y
default       es-reporting-data-v3-r4-k0kbm                                  1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-hdho
default       es-reporting-master-v3-awvd1                                   1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-uu2y
default       es-reporting-master-v3-wnkz8                                   1/1       Running   0          1d        gke-es-reporting-v1-3f8429d3-node-iz9y
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-6kgz   1/1       Running   0          2d        gke-es-reporting-v1-3f8429d3-node-6kgz
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-hdho   1/1       Running   0          2d        gke-es-reporting-v1-3f8429d3-node-hdho
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-iz9y   1/1       Running   0          4d        gke-es-reporting-v1-3f8429d3-node-iz9y
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-n7g3   1/1       Running   0          4d        gke-es-reporting-v1-3f8429d3-node-n7g3
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-uu2y   1/1       Running   0          4d        gke-es-reporting-v1-3f8429d3-node-uu2y
kube-system   fluentd-cloud-logging-gke-es-reporting-v1-3f8429d3-node-yzfd   1/1       Running   0          4d        gke-es-reporting-v1-3f8429d3-node-yzfd
kube-system   kube-dns-v8-hfbxp                                              4/4       Running   0          2d        gke-es-reporting-v1-3f8429d3-node-n7g3
kube-system   kube-ui-v1-1yy5q                                               1/1       Running   0          4d        gke-es-reporting-v1-3f8429d3-node-n7g3
kube-system   monitoring-heapster-v5-am10p                                   1/1       Running   2          4d        gke-es-reporting-v1-3f8429d3-node-yzfd
```

## Misc.

`kubectl get events` is empty, probably due to a time range filter.


--

I think we may have our answer here, so for the sake of closing the issue, **are there any known ways** to encourage pods to occupy this master node?

**Comment by bprashanth** [comment] 2015-07-29 22:21
I think your node ran out of cpu. You can confirm by checking the cpu on the pods already on it (the cluster addons: dns, fluentd, ui; use something like -o json | grep cpu -A 4), the pods in the default namespace get a default cpu resource applied (kubectl get limits -o json).

**Comment by soundofjw** [comment] 2015-07-29 22:34
Thanks @bprashanth :

`kubectl get pods -o json | grep cpu -A 4`:
```json
                                "cpu": "100m"
                            }
                        },
                        "volumeMounts": [
                            {
--
                                "cpu": "100m"
                            }
                        },
                        "volumeMounts": [
                            {
--
                                "cpu": "100m"
                            }
                        },
                        "volumeMounts": [
                            {
--
                                "cpu": "100m"
                            }
                        },
                        "volumeMounts": [
                            {
--
                                "cpu": "100m"
                            }
                        },
                        "volumeMounts": [
                            {
--
                                "cpu": "100m"
                            }
                        },
```

The only limit is this one, as you mentioned:
```json
                    {
                        "type": "Container",
                        "default": {
                            "cpu": "100m"
                        }
                    }
```


I was under the impression there was still no way to assert pod resource limits -- #168

**Comment by mbforbes** [comment] 2015-08-16 22:27
> are there any known ways to encourage pods to occupy this master node?

When you say your cluster is size 4, do you mean 3 nodes + master, or 4 nodes + master?

GKE hosts the master (the "control plane") in a separate project, and there's absolutely no way to schedule pods to go on the master, by design. The nodes are the only places where you're allowed to run pods.

**Comment by soundofjw** [comment] 2015-08-17 15:12
@mbforbes Thanks for the question - we're `--num-nodes 4` - so 4 nodes + GKE hosted master

**Comment by mbforbes** [comment] 2015-08-17 18:22
Ah, so the simple answer doesn't work! :-)

+cc @roberthbailey

**Comment by roberthbailey** [comment] 2015-08-18 21:39
The kube-system pods don't run on a master node. They run on nodes within your cluster. Two of them happened to have landed onto the same node (using enough of its resources that none of your pods were scheduled there), but they could have just as easily been spread across three nodes or all packed into one node. 

What size nodes are you using? It may just be that one node happened to be full enough that the scheduler decided not to use it. You can forcibly assign pods to nodes if you want to, but it is usually better just to let them land where there is available room in the cluster and count on the scheduler to do the right thing.

**Comment by soundofjw** [comment] 2015-08-18 21:45
@roberthbailey 
I know the pods aren't being scheduled according to their resource limits (#168).

The nodes are `highmem-4`, and the pods are configured:
```yaml
     - name: es-d1
        cpu: 200
        memory: 18253611008 # 20gb
```

The reason a pod might end up failing is only because it's using the JVM to reserve heap memory, and failing when the shared memory isn't large enough.

**Comment by davidopp** [comment] 2015-08-19 08:29
If you're still having a problem, can you send the information @bprashanth mentioned here?
https://github.com/kubernetes/kubernetes/issues/11909#issuecomment-126113909

**Comment by goltermann** [comment] 2015-08-25 23:25
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Closed by goltermann** 2015-08-25 23:25 UTC
Labels: area/platform/gke, kind/support, priority/P2, team/control-plane, team/support
