### ISSUE TITLE
e2e flake: Kubernetes e2e suite.Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#25511] opened 2016-05-11 22:21 UTC
Failure:
http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//39212

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:732
Expected
    <int>: 0
to equal
    <int>: 1
```

**Comment by spxtr** [comment] 2016-05-18 01:03
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce/17052

**Comment by spxtr** [comment] 2016-05-18 01:03
Related to #25657

**Comment by lavalamp** [comment] 2016-05-20 00:15
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17235/

**Comment by lavalamp** [comment] 2016-05-20 00:16
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17234/

**Comment by lavalamp** [comment] 2016-05-20 00:16
@pwittrock any time to look at this?

**Comment by pwittrock** [comment] 2016-05-20 00:28
Yes.  Looking

**Comment by pwittrock** [comment] 2016-05-20 01:01
Looks like this is an image pull failure since the last event we are seeing in the namespace is an image pull event, but no events after that:

`
May 19 16:16:03.216: INFO: WaitFor completed with timeout 1m30s.  Pods found = 0 out of 1
STEP: Collecting events from namespace "e2e-tests-kubectl-kroxp".
May 19 16:16:03.220: INFO: At {2016-05-19 16:14:33 -0700 PDT} - event for redis-master: {replication-controller } SuccessfulCreate: Created pod: redis-master-3jcn1
May 19 16:16:03.220: INFO: At {2016-05-19 16:14:33 -0700 PDT} - event for redis-master-3jcn1: {default-scheduler } Scheduled: Successfully assigned redis-master-3jcn1 to jenkins-e2e-minion-w59u
May 19 16:16:03.220: INFO: At {2016-05-19 16:14:34 -0700 PDT} - event for redis-master-3jcn1: {kubelet jenkins-e2e-minion-w59u} Pulling: pulling image "gcr.io/google_containers/redis:e2e"
May 19 16:16:03.412: INFO: POD                                                           NODE                     PHASE    GRACE  CONDITIONS
May 19 16:16:03.412: INFO: test-webserver-94409b82-1e17-11e6-9e83-0242ac110013           jenkins-e2e-minion-91yy  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 16:15:37 -0700 PDT}  } {Ready False {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 16:15:37 -0700 PDT} `

**Comment by pwittrock** [comment] 2016-05-24 01:19
Duplicate of #25277

**Closed by pwittrock** 2016-05-24 01:19 UTC
Labels: kind/flake, priority/P0, team/ux
