### ISSUE TITLE
Kubernetes e2e suite.[sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance]

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#102100] opened 2021-05-18 16:28 UTC
#### Which jobs are flaking:

https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master

#### Which test(s) are flaking:

Kubernetes e2e suite.[sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance]

#### Testgrid link:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1394500067842330624

#### Reason for failure:
```
May 18 04:15:35.673: INFO: observed event type MODIFIED
May 18 04:16:27.543: FAIL: failed to see DELETED event
Unexpected error:
    <*errors.errorString | 0xc0002c4250>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/sig windows

**Comment by marosset** [comment] 2021-08-10 16:27
/triage accepted

It looks like there are timeouts that occasionally hit if this test pulls the agnhost image on windows tests.
Looking at the logs the containers start right as the tests hit the timeout.

One option may be to pre-pull images again.

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-20-windows-containerd/1421516215053979648
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-20-windows-containerd/1420066218756280320

**Comment by marosset** [comment] 2021-09-23 16:58
@jsturtevant @claudiubelu should we prepull anghost image?

**Comment by claudiubelu** [comment] 2021-11-22 17:47
> @jsturtevant @claudiubelu should we prepull anghost image?

We've merged the PR for optionally prepulling the images. From what I've tested on my env, it works as intended. We could enable image prepulling for a few jobs, and if things improve, I think we can apply it to other jobs as well.

Image prepull is enabled with the flag: ``--prepull-images="true"``

**Comment by claudiubelu** [comment] 2021-11-30 13:56
I've seen this other flakes  recently on the master branch runs [1][2].

[1] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1463022222498074624
[2] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1464115646240395264

I have sent a PR here, which already merged: https://github.com/kubernetes/test-infra/pull/24500

Here's a recent job run, which shows that the images have been prepulled: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1465662350655754240

```
Nov 30 12:55:45.503: INFO: Pre-pulling images so that they are cached for the tests.
Nov 30 12:55:45.658: INFO: Waiting for img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33
Nov 30 12:55:45.688: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:55:45.734: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:55:45.734: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:55:54.764: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:55:54.792: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:55:54.792: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:56:03.762: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:03.791: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:56:03.791: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:56:12.762: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:12.790: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:56:12.790: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:56:21.762: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:21.789: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:56:21.789: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:56:30.764: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:30.792: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 0
Nov 30 12:56:30.792: INFO: Node 2728k8s000 is running 0 daemon pod, expected 1
Nov 30 12:56:39.762: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:39.790: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33: 2
Nov 30 12:56:39.790: INFO: Number of running nodes: 2, number of available pods: 2 in daemonset img-pull-k8s.gcr.io-e2e-test-images-agnhost-2.33
Nov 30 12:56:39.790: INFO: Waiting for img-pull-k8s.gcr.io-e2e-test-images-busybox-1.29-2
Nov 30 12:56:39.806: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:39.825: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-busybox-1.29-2: 2
Nov 30 12:56:39.825: INFO: Number of running nodes: 2, number of available pods: 2 in daemonset img-pull-k8s.gcr.io-e2e-test-images-busybox-1.29-2
Nov 30 12:56:39.825: INFO: Waiting for img-pull-k8s.gcr.io-e2e-test-images-httpd-2.4.38-2
Nov 30 12:56:39.840: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:39.856: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-httpd-2.4.38-2: 2
Nov 30 12:56:39.857: INFO: Number of running nodes: 2, number of available pods: 2 in daemonset img-pull-k8s.gcr.io-e2e-test-images-httpd-2.4.38-2
Nov 30 12:56:39.857: INFO: Waiting for img-pull-k8s.gcr.io-e2e-test-images-nginx-1.14-2
Nov 30 12:56:39.872: INFO: DaemonSet pods can't tolerate node k8s-master-27280835-0 with taints [{Key:node-role.kubernetes.io/master Value: Effect:NoSchedule TimeAdded:<nil>}], skip checking this node
Nov 30 12:56:39.889: INFO: Number of nodes with available pods controlled by daemonset img-pull-k8s.gcr.io-e2e-test-images-nginx-1.14-2: 2
Nov 30 12:56:39.889: INFO: Number of running nodes: 2, number of available pods: 2 in daemonset img-pull-k8s.gcr.io-e2e-test-images-nginx-1.14-2
Nov 30 12:56:39.905: INFO: e2e test version: v1.24.0-alpha.0.11+c1153d3353bd4f
```

**Comment by claudiubelu** [comment] 2021-12-21 12:38
Sent a PR for other jobs: https://github.com/kubernetes/test-infra/pull/24718

**Comment by claudiubelu** [comment] 2022-01-10 18:03
I don't think we've seen those image pulling timeouts since we've merged the fixes above. We could close this for now, and reopen if it surfaces again, IMO.

**Comment by jsturtevant** [comment] 2022-01-10 18:06
sgtm, thanks for that update!
/close

**Closed** 2022-01-10 18:06 UTC
Labels: kind/flake, sig/windows, triage/accepted
