### ISSUE TITLE
Updating a deployment scales existing RS to 0 before new RS is ready

### ISSUE THREAD

**Issue by broady** [kubernetes/kubernetes#38072] opened 2016-12-04 22:22 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
https://github.com/kubernetes/kubernetes/issues?page=1&q=is%3Aissue+is%3Aopen+rolling+update++ready&utf8=%E2%9C%93

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):
1.4.4 client, 1.4.6 cluster

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:
Ran `kubectl apply -f ...`, updating the version for an image.
Observed the existing RS scale to zero before the new RS was ready (the container has a readinessProbe), resulting in downtime. 

**What you expected to happen**:
Traffic remains routed to the existing RS until the new RS is ready.

**How to reproduce it** (as minimally and precisely as possible):
https://gist.github.com/c82ae5cf2919684926b8bcc23d6ccddc

`kubectl apply -f deployment.yaml`

Wait for it to start serving.
Modify something like the "env" in deployment.yaml
Run `kubectl apply`.

Observe that the old RC is immediately scaled to zero.

**Anything else do we need to know**:
N/A

**Comment by kargakis** [comment] 2016-12-05 18:24
When you create a Deployment that does not specify the strategy, the deployment will be defaulted by the system to the Rolling strategy (so far so good) but it also defaults to rolling parameters that can make your app become totally unavailable (see https://github.com/kubernetes/kubernetes/issues/23304). I suggest switching MaxUnavailable to a non-100% percentage (currectly it should be 1 (absolute number) for you) if you want to make sure you will always run one pod.

**Comment by broady** [comment] 2016-12-05 18:41
@kargakis Ah, I see. Thanks Setting `MaxUnavailable=0` should have my desired effect, right?

**Comment by kargakis** [comment] 2016-12-05 18:42
Yes, you can also simply set it to 0.

**Comment by broady** [comment] 2016-12-05 18:42
This seems like a bad default. Was there a reason behind it?

**Comment by kargakis** [comment] 2016-12-05 18:45
I don't think there was a specific reason for it. There is already an open PR for changing that default (https://github.com/kubernetes/kubernetes/pull/34339) but we need to also move Deployments to a new api version (v1beta2 I guess) before merging it.

cc: @kubernetes/deployment

**Comment by broady** [comment] 2016-12-05 18:52
Yeah, it's a dangerous default to change. People may rely on the fact that only one pod of that kind is running at any time.

**Comment by broady** [comment] 2016-12-05 18:57
I tried `maxUnavailable: 0` and now see the old container only terminate after the new one is ready, but traffic is not routed via the LoadBalancer service for a couple minutes.

Separate bug?

**Comment by kargakis** [comment] 2016-12-05 18:58
Yes, that should be a separate bug specific to the LoadBalancer you use I guess.

**Comment by kargakis** [comment] 2016-12-05 19:26
Closing this as a dupe of https://github.com/kubernetes/kubernetes/issues/23304

**Closed by kargakis** 2016-12-05 19:26 UTC
