### ISSUE TITLE
flaky tests: E2eNode Suite.[It] [sig-node] MirrorPod when create a mirror pod without changes should successfully recreate when file is removed and recreated

### ISSUE THREAD

**Issue by kidddddddddddddddddddddd** [kubernetes/kubernetes#116889] opened 2023-03-23 12:34 UTC
### Which jobs are flaking?

- E2eNode Suite.[It] [sig-node] MirrorPod when create a mirror pod without changes should successfully recreate when file is removed and recreated [NodeConformance]
- pull-kubernetes-node-e2e-containerd.Pod

### Which tests are flaking?

`MirrorPod` at  `test/e2e_node/mirror_pod_test.go:183`

`pull-kubernetes-node-e2e-containerd.Pod` doesn't output any log, and fails really quick. 

### Since when has it been flaking?

seems like `pull-kubernetes-node-e2e-containerd.Pod` has been failing for some time.
`MirrorPod` has been flaking for one-day? testgrid shows it started to be flaky on 3-23.

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/49895476/227204760-92502d5d-573c-475b-b8d8-eb7750a7bc45.png">

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e

### Reason for failure (if possible)

{ failed [FAILED] Timed out after 126.026s.
Expected
    <wait.errInterrupted>: 
    timed out waiting for the condition
    {
        cause: <*errors.errorString | 0xc0001504f0>{
            s: "timed out waiting for the condition",
        },
    }
to be nil
In [It] at: test/e2e_node/mirror_pod_test.go:183 @ 03/23/23 08:00:47.506
}

### Relevant SIG(s)

/sig node

**Comment by bobbypage** [comment] 2023-03-24 19:43
Seems like this is a dup of https://github.com/kubernetes/kubernetes/issues/116714

**Comment by bobbypage** [comment] 2023-03-24 19:44
Duplicate of https://github.com/kubernetes/kubernetes/issues/116714

/close

**Closed by bobbypage** 2023-03-24 19:44 UTC
Labels: sig/node, kind/flake, needs-triage
