### ISSUE TITLE
change "kubectl get rc" to show some basic status info about the "state" of pods

### ISSUE THREAD

**Issue by jdk-google** [kubernetes/kubernetes#9057] opened 2015-06-01 12:22 UTC
kubectl get pods is really difficult to read. 
But - users need to have a way to check "has the stuff already started?".

So - maybe kubectl get rc could show some basic info about the status of pods? For example: the "replicas" column could say:

3 [2 running]

**Comment by bprashanth** [comment] 2015-06-01 17:12
> kubectl get pods is really difficult to read. 

We're fixing that :)
Fyi https://github.com/GoogleCloudPlatform/kubernetes/issues/7843.

> "replicas" column could say: 3 [2 running]

I don't see why not, @bgrant0607 thoughts? I would still leave out the `running` part because the rcs `status.Replicas` doesn't know what state the pods are in (they could be in pending).

**Comment by bgrant0607** [comment] 2015-06-01 17:24
Re. get pods, see #7843

**Comment by bgrant0607** [comment] 2015-06-01 17:28
Get RCs should not pull in pod status. Describe can do that:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/describe.go#L419

We could expand that output if that would be helpful.

Once #7843 is resolved, it should be easy to tally the number of running containers using get pods piped into awk or somesuch.

**Comment by jdk-google** [comment] 2015-06-08 10:32
HI Brian.

Describe gives info only about on RC at a time, right?

I would prefer to have one place where I can see list of all my "services"/ "jobs" (services not in the k8s sense) and their state on one screen.

For typical user they will fit (I expect that typical k8s user will have ~10 RCs not, ~100)

**Comment by hurf** [comment] 2015-06-11 02:42
Can we have `--all` option for `describe`, it can meet the requirment of @jdk-google to view all the 'services' without bring pod status into `get` @bgrant0607

**Comment by hurf** [comment] 2015-06-11 02:44
Since we think adding label support for `describe` is resonable in #9248, which would allow `describe` output multiple results.

**Comment by satnam6502** [comment] 2015-06-15 18:14
What do we want to do about this? Personally, I think a combination of `get rc` and `get pods` is fine -- but if you wanted to add `3 [2 Running]` under the replicas heading then I would be happy to take on this issue.

**Comment by bgrant0607** [comment] 2015-06-20 04:17
I think a combination of describe rc and get pods is fine for now, since we've improved get pods and added label support to describe.

**Comment by bgrant0607** [comment] 2016-01-25 06:40
Dupe of #7483

**Closed by bgrant0607** 2016-01-25 06:40 UTC
Labels: area/api, area/usability, component/kubectl, kind/enhancement, priority/P2, team/ux
