### ISSUE TITLE
'PATCH node-status' latency slo violations

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#62064] opened 2018-04-03 12:34 UTC
We've been observing some failures in our 5k-node density test caused due to high latency (>1s) of `patch node-status` calls. E.g:

```
WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:14.669ms Perc90:525.081ms Perc99:1.380235s Perc100:0s} Count:6873901}
```

Some affected runs:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/132
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/131
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/130
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/126
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/125
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/123
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/121
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/119
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/118

It increased from an earlier 700-800ms to 1-1.3s now.

cc @kubernetes/sig-scalability-bugs @wojtek-t

**Comment by shyamjvs** [comment] 2018-04-03 12:39
The difference doesn't really seem very visible in load test:

![load-patch-node-status](https://user-images.githubusercontent.com/4333971/38249630-9b6c0c06-374c-11e8-81bb-5e93ba93dd17.png)

and for density we see the difference, but we're missing some runs' entries in the graph due to some bug likely:

![density-node-status](https://user-images.githubusercontent.com/4333971/38249676-c746233e-374c-11e8-9478-e4c2053f445b.png)

**Comment by shyamjvs** [comment] 2018-04-03 12:43
On the good side, we're noticing the increase in kubemark-5000 also. Here's how the graph looks there for density, which is clearly indicating the regression:

![kubemark-density-patch-node](https://user-images.githubusercontent.com/4333971/38249832-4eef65e8-374d-11e8-8114-3f7001431081.png)

**Comment by shyamjvs** [comment] 2018-04-03 12:48
From kubemark-5000 load test, there seems to be even clearer indication (the increase likely is b/w 860 -> 862):

![load](https://user-images.githubusercontent.com/4333971/38250021-f1beb954-374d-11e8-8e4a-8e01d8a60fff.png)

**Comment by shyamjvs** [comment] 2018-04-03 12:52
I'm looking at the diff https://github.com/kubernetes/kubernetes/compare/50e28a5d50800c...a8060ab0a13168, and my suspicion is currently on https://github.com/kubernetes/kubernetes/pull/56717 which seems to add some extra processing on the way of creates/reads to subresource objects (so codepath is likely to be touched by node/status?)

cc @wojtek-t

**Comment by wojtek-t** [comment] 2018-04-03 12:58
#56717 is changing only client implementation. Latencies are measure server side, so this is unlikely that it's that PR (unless it's not adding additional requests).

**Comment by wojtek-t** [comment] 2018-04-05 07:29
The range 860-862 of kubemark-5000 is suspiciously close to that PR: https://github.com/kubernetes/kubernetes/pull/59953
[which was discovered to be reason for regression]

**Comment by wojtek-t** [comment] 2018-04-05 07:48
@shyamjvs - I looked into range that you mentioned above:
https://github.com/kubernetes/kubernetes/pull/59685 - unrelated
https://github.com/kubernetes/kubernetes/pull/59797 - unrelated
https://github.com/kubernetes/kubernetes/pull/57445 - unrelated
https://github.com/kubernetes/kubernetes/pull/59523 - unrelated (only removing some metrics gathering in CM)
https://github.com/kubernetes/kubernetes/pull/59090 - unrelated (only e2e tests changes)
https://github.com/kubernetes/kubernetes/pull/59697 - unrelated (docs)
https://github.com/kubernetes/kubernetes/pull/59489 - unrelated (only test changes)
https://github.com/kubernetes/kubernetes/pull/59716 - unrelated (only Azure changes)
https://github.com/kubernetes/kubernetes/pull/59761 - unrelated (only e2e test changes)
https://github.com/kubernetes/kubernetes/pull/59837 - unrelated (only juju changes)
https://github.com/kubernetes/kubernetes/pull/59103 - unlikely, but possible
https://github.com/kubernetes/kubernetes/pull/58433 - unrelated (only change to mount_linux file, can't regress kubemark)
https://github.com/kubernetes/kubernetes/pull/59749 - unrelated (only openstack changes)
https://github.com/kubernetes/kubernetes/pull/59832 - potentially
https://github.com/kubernetes/kubernetes/pull/59825 - unrelated (only removes unused code)
https://github.com/kubernetes/kubernetes/pull/59800 - unrelated (only benchmark-related changes)
https://github.com/kubernetes/kubernetes/pull/59817 - unrelated (potentially removes some retries)
https://github.com/kubernetes/kubernetes/pull/59711 - unlikely (changes how flags are used by hollow-node)
https://github.com/kubernetes/kubernetes/pull/59788 - unrelated (typos)
https://github.com/kubernetes/kubernetes/pull/59846 - unrelated (renames)
https://github.com/kubernetes/kubernetes/pull/59792 - unrelated (just juju)
https://github.com/kubernetes/kubernetes/pull/59666 - unlikely (changes to kubelet initialization, shouldn't affect kubemark)
https://github.com/kubernetes/kubernetes/pull/56717 - unlikely but possible
https://github.com/kubernetes/kubernetes/pull/59440 - unrelated (vsphere changes)
https://github.com/kubernetes/kubernetes/pull/59878 - unrelated (typos)
https://github.com/kubernetes/kubernetes/pull/59852 - unrelated (hack/lib/etcd, not used in tests)
https://github.com/kubernetes/kubernetes/pull/59335 - unrelated (only changes in scheduler algorithm)
https://github.com/kubernetes/kubernetes/pull/59872 - unrelated (only e2e test changes)
https://github.com/kubernetes/kubernetes/pull/59646 - unlikely (re-revert of https://github.com/kubernetes/kubernetes/pull/59523 also from this batch)


@shyamjvs So there are only 6 PRs here and all of them are quite unlikely to cause that problems in my opinion.
So maybe something happened slightly before (and we were lucky in one run) or slightly after?

**Comment by wojtek-t** [comment] 2018-04-05 07:53
Actually, take a look at this graph - this also proves where the regression was.
And it unfortunately gives the same range.

![screenshot from 2018-04-05 09-50-45](https://user-images.githubusercontent.com/10743879/38353543-053298ba-38b7-11e8-91f1-acaa4d30d18e.png)

So I think the suspicious PRs are (but neither of them looks like it could cause such things)
#59103 - unlikely, but possible
#59832 - potentially
#59711 - unlikely (changes how flags are used by hollow-node)
#59666 - unlikely (changes to kubelet initialization, shouldn't affect kubemark)
#56717 - unlikely but possible
#59646 - unlikely (re-revert of #59523 also from this batch)

**Comment by wojtek-t** [comment] 2018-04-05 08:00
BTW - this may be kubemark-specific regression, because we don't see similar effects in 5k-node clusters.
So it may be something different than the initially reported one.

**Comment by wojtek-t** [comment] 2018-04-05 08:34
As for the originally reported regression, I think the only thing we can say is that happened somewhere
between runs: 115 and 118:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/115
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/118

and unfortunately that's hell a lot of commits...

**Comment by wojtek-t** [comment] 2018-04-05 08:48
@shyamjvs had a hypothesis that the regression happened between runs of 884 and 995 of kubemark-5000 (which is within this time period).

I looked into corresponding diff:
https://github.com/kubernetes/kubernetes/compare/07240b7166d83b...46f05b0c2bc153

https://github.com/kubernetes/kubernetes/pull/59495 - unlikely, but possible
https://github.com/kubernetes/kubernetes/pull/60173 - unrelated (doc changes)
https://github.com/kubernetes/kubernetes/pull/60595 - unrelated (owners changes)
https://github.com/kubernetes/kubernetes/pull/60524 - unrelated (only changes leader election for scheduler)
https://github.com/kubernetes/kubernetes/pull/60385 - unrelated (only kubeadm changes)
https://github.com/kubernetes/kubernetes/pull/60615 - unrelated (only integration test changes)
https://github.com/kubernetes/kubernetes/pull/60580 - potentially possible
https://github.com/kubernetes/kubernetes/pull/60557 - unrelated (only e2e test changes)
https://github.com/kubernetes/kubernetes/pull/60362 - unrelated (only test changes)
https://github.com/kubernetes/kubernetes/pull/60629 - unrelated (only typos)
https://github.com/kubernetes/kubernetes/pull/60572 - unrelated (only docs)
https://github.com/kubernetes/kubernetes/pull/60623 - unrelated (only azure changes)
https://github.com/kubernetes/kubernetes/pull/60625 - unrelated (only azure changes)
https://github.com/kubernetes/kubernetes/pull/60520 - unlikely (retries in test framework)

@shyamjvs So here there are only 3 potential PRs that may have affected that - see above.

**Comment by wojtek-t** [comment] 2018-04-05 09:30
Since there isn't much there, i went one more run before (so commits from 883 to 884):

https://github.com/kubernetes/kubernetes/compare/b1ef631e5971f6...07240b7166d83b

https://github.com/kubernetes/kubernetes/pull/60376 - unrelated (changes docker calls for setup things)
https://github.com/kubernetes/kubernetes/pull/55584 - unrelated (simple fix)
https://github.com/kubernetes/kubernetes/pull/60358 - unrelated (docs changes)
https://github.com/kubernetes/kubernetes/pull/54631 - potentially (Quobyte library bump)
https://github.com/kubernetes/kubernetes/pull/60291 - unrelated (healthz changes in cloud-controller-manager)
https://github.com/kubernetes/kubernetes/pull/60470 - unrelated (scheduling api group)
https://github.com/kubernetes/kubernetes/pull/59149 - unrelated (examples and e2e tests)
https://github.com/kubernetes/kubernetes/pull/56075 - potentially
https://github.com/kubernetes/kubernetes/pull/60280 - unrelated (cleanup)
https://github.com/kubernetes/kubernetes/pull/60504 - retry EOFs (unlikely)
https://github.com/kubernetes/kubernetes/pull/60342 - unlikely
https://github.com/kubernetes/kubernetes/pull/60505 - unrelated (log changes)
https://github.com/kubernetes/kubernetes/pull/59218 - unrelated (e2e test changes)
https://github.com/kubernetes/kubernetes/pull/52900 - unrelated (cleanup)
https://github.com/kubernetes/kubernetes/pull/60486 - unrelated (?) bug fix in service controller
https://github.com/kubernetes/kubernetes/pull/60475 - unrelated (test changes)
https://github.com/kubernetes/kubernetes/pull/60514 - unrelated (integration tests)
https://github.com/kubernetes/kubernetes/pull/60506 - unrelated
https://github.com/kubernetes/kubernetes/pull/59903 - unrelated (e2e test changes)
https://github.com/kubernetes/kubernetes/pull/60319 - unrelated (e2e test changes)
https://github.com/kubernetes/kubernetes/pull/59345 - unrelated (e2e test changes)
https://github.com/kubernetes/kubernetes/pull/58171 - unrelated (e2e test changes)
https://github.com/kubernetes/kubernetes/pull/58036 - unlikely
https://github.com/kubernetes/kubernetes/pull/60540 - unlikely
https://github.com/kubernetes/kubernetes/pull/60555 - unrelated (test changes)

**Comment by shyamjvs** [comment] 2018-04-05 09:47
Thanks for looking into this @wojtek-t.
So like I mentioned in yesterday's offline discussion, there indeed seems to be different regression around run 884 of kubemark-5k (besides the other one b/w 860 and 862). Few reasons to believe it was around that time is:
- there's increase in 90%ile latency b/w 884-885 as you can see in the first graph in https://github.com/kubernetes/kubernetes/issues/62064#issuecomment-378236406
- there's increase in 99% latency b/w runs 116-118 of gce-5k (which was around the same time as 884-884). Here's the latency graph I generated for gce-5k (along with points that were missing on perf-dash):

![latency](https://user-images.githubusercontent.com/4333971/38358914-fdf9b1e0-38c6-11e8-8e71-228a07417c83.png)

**Comment by shyamjvs** [comment] 2018-04-05 10:06
And wrt your https://github.com/kubernetes/kubernetes/issues/62064#issuecomment-378857941 - I also agree with you that it's most likely because of my pr #59832. Some of those points about endpoints having single entries earlier and the apiserver mem-usage increasing after the change - I explained them earlier under https://github.com/kubernetes/kubernetes/issues/44701#issuecomment-366246563 and https://github.com/kubernetes/kubernetes/issues/59823.

Another thing (like we were discussing) is that only kubemark seeing this rise even more strongly suggests it's that change.
Since that's as expected, I'll now try to find the other one.

**Comment by wojtek-t** [comment] 2018-04-05 10:53
> And wrt your #62064 (comment) - I also agree with you that it's most likely because of my pr #59832. Some of those points about endpoints having single entries earlier and the apiserver mem-usage increasing after the change - I explained them earlier under #44701 (comment) and #59823.

That was different thing - they were empty because of validation problems.
Though that doesn't really matter now.

> Since that's as expected, I'll now try to find the other one.

Yeah - thanks for looking into that.
The only think that I'm not convinced is that the regression was between 116-118 (not 115-118).

As you see, above I analyzed changes from between 883-885 kubemark runs. There are only 9 pontential PRs that may have cause that.

**Comment by wojtek-t** [comment] 2018-04-05 12:08
@shyamjvs The more I look into it, the more doubts I have that the regression is not between 115 and 116. If you look into metrics for replicactioncontrollers, the increased between 115 and 116. And I think this might actually be the same thing that is causing increase of patch nodes.

**Comment by wojtek-t** [comment] 2018-04-05 12:10
Or maybe (looking into longer time horizon) these are only fluctuations...

**Comment by shyamjvs** [comment] 2018-04-06 18:57
I ran once against 116, and it looked like this:

```
    {
      "data": {
        "Perc50": 7.915,
        "Perc90": 171.342,
        "Perc99": 805.786
      },
      "unit": "ms",
      "labels": {
        "Count": "7134625",
        "Resource": "nodes",
        "Scope": "cluster",
        "Subresource": "status",
        "Verb": "PATCH"
      }
    },
```

Will run again later.

**Comment by wojtek-t** [comment] 2018-04-09 07:36
We need one or two more runs, but this seems like "before-regression" to me.

**Comment by shyamjvs** [comment] 2018-04-16 10:08
Ran once more against 116 and have the following values - 9.66ms (50%), 414.091ms (90%), 877.327ms (99%)
I believe we can now try to confirm that 118 is the right end.

**Comment by shyamjvs** [comment] 2018-04-16 17:55
I've ran against 118 and seems like it indeed is a bad one:

```
INFO: WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:10.244ms Perc90:627.37ms Perc99:1.004515s Perc100:0s} Count:4357372}
```

**Comment by wojtek-t** [comment] 2018-04-16 18:00
it's only 1.00s, so it would be good to have one more run.

**Comment by shyamjvs** [comment] 2018-04-17 15:36
I've run once more and it turned out bad again:

```
INFO: WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:11.16ms Perc90:645.185ms Perc99:1.020599s Perc100:0s} Count:4359913}
```

So continuing with assumption that 118 was bad, I ran the test against the mid-commit 249ecab74 and result was: 9.599 (50%), 573.99 (90%), 921.448 (99%)
I think this isn't super-clear, so I'm re-running against it.

**Comment by shyamjvs** [comment] 2018-04-18 12:46
For rerun against the same commit and it seems good:

```
"data": {
        "Perc50": 5.804,
        "Perc90": 173.217,
        "Perc99": 822.677
      },
```

And then I reran against the next commit f82b38cfaa and it seems unclear to me if it's bad:

1st try:

```
11.104ms, 572.727ms, 915.371ms
```

2nd try:

```
8.078ms, 552.669ms, 955.312ms
```

**Comment by shyamjvs** [comment] 2018-04-18 19:52
The 3rd try gave me:

```
"data": {
        "Perc50": 5.519,
        "Perc90": 212.198,
        "Perc99": 869.305
      },
```

So I'm going to proceed by assuming this was a good commit (and the earlier higher values were some variations).

**Comment by wojtek-t** [comment] 2018-04-19 06:15
I would say that there might be a second (smaller?) regression in the first half.
But +1 for assuming for now this was a good one and proceeding with that assumption.

**Comment by shyamjvs** [comment] 2018-04-19 12:31
So from the ones we were suspecting yesterday, the following remain in the diff:

- https://github.com/kubernetes/kubernetes/pull/56075 move rc-scaling to polling
- https://github.com/kubernetes/kubernetes/pull/60342 nested volume mounts
- https://github.com/kubernetes/kubernetes/pull/59495 exec-based client auth provider

**Comment by wojtek-t** [comment] 2018-04-19 12:31
There are only 4 potentially suspicious PRs in that range:
https://github.com/kubernetes/kubernetes/pull/56075
https://github.com/kubernetes/kubernetes/pull/60342 (highly unlikely, as it touches only kubelet and doesn't increase API calls IIUC)
https://github.com/kubernetes/kubernetes/pull/58171 (highly unlikely, as we're not using flex volumes in our tests)
https://github.com/kubernetes/kubernetes/pull/59495

**Comment by wojtek-t** [comment] 2018-04-19 16:27
@shyamjvs - so let's run on commit with one of them and without the other

**Comment by shyamjvs** [comment] 2018-04-20 11:17
Running it against 98eb5cbd04 gave me:

```
WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:11.679ms Perc90:643.619ms Perc99:1.022355s Perc100:0s} Count:4418914}
```

which leaves us only with my PR #56075 as the cause :)

**Comment by wojtek-t** [comment] 2018-04-23 07:55
Thank @shyamjvs 
That means we should prioritize: https://github.com/kubernetes/kubernetes/pull/50102 because that will unblock getting back to watch-based solution there.

**Comment by shyamjvs** [comment] 2018-04-23 14:27
Going back to the 'PATCH node-status' latency graph I posted earleir in https://github.com/kubernetes/kubernetes/issues/62064#issuecomment-378880484.. copying again:

![a](https://user-images.githubusercontent.com/4333971/39132445-21156b34-4712-11e8-9568-0916441e740a.png)

We now understand the cause for bump above threshold of 1s before run-119. This is caused by my PR #56075 that moved Scale() method for RCs from watch-based to poll-based.

The other part that remains is to figure why so much variance in the latency was introduced after run-119. Currently I'm trying to confirm that 119 is stable (so we can use it as left-end for bisection).

**Comment by shyamjvs** [comment] 2018-04-24 10:03
Running against 119 gave:

```
{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:9.408ms Perc90:697.499ms Perc99:1.062004s Perc100:0s} Count:5137540}
```

and against 120 gave:

```
{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:11.792ms Perc90:615.898ms Perc99:1.012838s Perc100:0s} Count:4692243}
```

I'm now planning to confirm if 121 sees the problem (even though the graph says it should) just to confirm right-end is correct.

**Comment by shyamjvs** [comment] 2018-04-25 12:40
Running against 121 confirmed that it's a bad one:

```
{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:10.811ms Perc90:546.962ms Perc99:1.240708s Perc100:0s} Count:4569021}
```

And bisecting at df3d8bcba6 in b/w 120 and 121 seems to be good:

```
{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:12.704ms Perc90:641.654ms Perc99:1.011261s Perc100:0s} Count:4838682}
```

This is the current diff - https://github.com/kubernetes/kubernetes/compare/df3d8bcba6ce98dec27c12e5e787bfc3b0bba60d...17d69c296eb75002a06b4ea0d8fe8c484eb90bff
I have suspicion on my etcd-revert to 3.1.11 (https://github.com/kubernetes/kubernetes/pull/60891), so I'm currently running against it.

**Comment by wojtek-t** [comment] 2018-04-25 12:56
> This is the current diff - df3d8bc...17d69c2

If you believe in that diff, there isn't anything else that may caused regression other than your PR...

**Comment by shyamjvs** [comment] 2018-04-25 13:01
That's true. But I want to ensure that I don't get a good run flakily (as that might mean I missed bad commits earlier in the commit history while bisecting by chance).

**Comment by shyamjvs** [comment] 2018-04-25 16:47
Confirmed it's my etcd change:

```
{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:10.822ms Perc90:428.997ms Perc99:1.214079s Perc100:0s} Count:7565564}
```

From an initial thought it seems to be like there's a variance in latencies that was introduced when we moved from 3.2.16 -> 3.1.11.
Based on all this I feel we should try to understand what exactly is happening with different etcd versions (i.e run density test (probably multiple times) against HEAD with each etcd version that's doubtful).

**Comment by wojtek-t** [comment] 2018-06-04 14:03
Given that we hopefully debugged and fixed the regressions (at least we are in much better shape now) and the fact that there are no concrete action items here, I'm closing this one.

**Closed by wojtek-t** 2018-06-04 14:03 UTC
Labels: kind/bug, priority/important-soon, sig/scalability

**Comment by shyamjvs** [comment] 2018-06-04 14:29
Yes, we seem to be in a good shape now. FTR I'm pasting below perf-dash showing latencies are back to normal values:

![patch](https://user-images.githubusercontent.com/4333971/40923026-06e42066-6814-11e8-87ff-0748f048bba2.png)

We can reopen this if we find some issue later.
/close
