### ISSUE TITLE
kubelet service/kubernetes appropriate selinux labels

### ISSUE THREAD

**Issue by a-wakeel** [kubernetes/kubernetes#41692] opened 2017-02-18 15:05 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
 **No**, not particularly related to troubleshooting

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
yeah i searched for **selinux:issues**, could not found any satisfactory results

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Neither of them, its just an extra thing may be in security point of view
<!--

If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.

**Kubernetes version** (use `kubectl version`):
latest (1.4.9)

**Environment**:
- **Cloud provider or hardware configuration**:
Intel Core i7 (local machine)
- **OS** (e.g. from /etc/os-release):
Centos 7
- **Kernel** (e.g. `uname -a`):
3.10.0-514.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:
-Can't find selinux module in **semodule -l** related to kubernetes
-Can't find proper/valid **selinux labels** for **kubelet** service

**What you expected to happen**:
- A selinux module of kubernetes in **semodule -l** list
- Proper/valid selinux labels for **kubelet** service and kubernetes

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
There should be a selinux module for kubernetes inorder to get proper labels on kublet service and kubernetes contexts(binaries and files etc) to make it work in selinux restricted environment.  I could not found any of this on my centos machine after installing and configuring kubernetes.

**Comment by a-wakeel** [comment] 2017-02-18 15:11
There should be a selinux module for kubernetes inorder to get proper labels on kublet service and kubernetes contexts(binaries and files etc) to make it work in selinux restricted environment.  I could not found any of this on my centos machine after installing and configuring kubernetes.

**Comment by smarterclayton** [comment] 2017-02-27 22:15
How did you install and configure kubernetes?

**Comment by a-wakeel** [comment] 2017-03-30 09:27
Sorry for late answer !
I followed this official guide for centos
https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by roberthbailey** [comment] 2017-06-20 17:31
I'm going to mark this as a duplicate of https://github.com/kubernetes/kubeadm/issues/279, as kubeadm issues have been moved to a different repository and we are tracking the current work on SELinux starting with that issue. Please follow-up with your requirements on https://github.com/kubernetes/kubeadm/issues/279. Thanks!

**Closed by roberthbailey** 2017-06-20 17:31 UTC
Labels: sig/cluster-lifecycle
