### ISSUE TITLE
skydns container exits repeatedly and new one gets created

### ISSUE THREAD

**Issue by biswars** [kubernetes/kubernetes#8042] opened 2015-05-10 17:19 UTC
Kubernetes version used: 0.16.2
skydns image: gcr.io/google_containers/skydns:2015-03-11-001
kube2sky image: gcr.io/google_containers/kube2sky:1.4

I am running this set up locally and able to run pods, services, replicationcontrollers. When I set up the dns by running the rc and service as available in the skydns-rc.yaml.yaml and skydns-svc.yaml, observed that skydns exits repeatedly and gets created again. Watching the logs  of this container gives the following lines before exiting.

sudo docker logs -f f7c77646eff5
2015/05/10 17:09:16 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [759]
2015/05/10 17:09:16 skydns: ready for queries on kubernetes.local. for tcp://0.0.0.0:53 [rcache 0]
2015/05/10 17:09:16 skydns: ready for queries on kubernetes.local. for udp://0.0.0.0:53 [rcache 0]
2015/05/10 17:09:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'
2015/05/10 17:09:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'
2015/05/10 17:09:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'

Can this be considered normal behavior ? (albeit, the dns functionality works well)

**Comment by thockin** [comment] 2015-05-11 03:23
Did you make your domain "foobar" ?  I think skydns expects it to have 2
tokens..

**Comment by biswars** [comment] 2015-05-11 06:29
The domain that I have specified is "kubernetes.local" and have removed the secret block (as it was complaining about missing tokens) in the skydns yaml file for rc. Would it cause the problem ?

**Comment by engine07** [comment] 2015-05-11 13:08
example on how to deploy dns token secret withouth any secret so that service doesn't hang: https://github.com/GoogleCloudPlatform/kubernetes/issues/7359

**Comment by thockin** [comment] 2015-05-11 15:22
The token might cause a problem for kube2sky, but not for skydns.  Does
'docker inspect' show anything for that container?

**Comment by biswars** [comment] 2015-05-12 10:55
Docker inspect for the exited containers is as follows. It shows the exit error code as "2".
Note: I don't get any issue in kube2sky container.

core@core-02 ~ $ sudo docker inspect d70f4ee6e480
[{
    "AppArmorProfile": "",
    "Args": [
        "-machines=http://localhost:4001",
        "-addr=0.0.0.0:53",
        "-domain=kubernetes.local"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "-machines=http://localhost:4001",
            "-addr=0.0.0.0:53",
            "-domain=kubernetes.local"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/skydns"
        ],
        "ExposedPorts": null,
        "Hostname": "kube-dns-szte1",
        "Image": "gcr.io/google_containers/skydns:2015-03-11-001",
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-05-12T10:50:02.803122804Z",
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/var/lib/kubelet/pods/a2a4eb5f-f894-11e4-a0ac-0800279924c6/containers/skydns/d70f4ee6e480398da77a5c49a915400e72784a319e56957b2374de0c2c6a5de7:/dev/termination-log"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "ContainerIDFile": "",
        "Devices": null,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "container:4a51ca5fb7097ddcf23d2ea468a460640fb1c2789685cc8c9aa561e623c9f526",
        "Links": null,
        "LxcConf": null,
        "NetworkMode": "container:4a51ca5fb7097ddcf23d2ea468a460640fb1c2789685cc8c9aa561e623c9f526",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "VolumesFrom": null
    },
    "HostnamePath": "",
    "HostsPath": "/var/lib/docker/containers/4a51ca5fb7097ddcf23d2ea468a460640fb1c2789685cc8c9aa561e623c9f526/hosts",
    "Id": "d70f4ee6e480398da77a5c49a915400e72784a319e56957b2374de0c2c6a5de7",
    "Image": "791ddf327076e0fd35a1125568a56c05ee1f1dfd7a165c74f4d489d8a5e65ac5",
    "MountLabel": "",
    "Name": "/k8s_skydns.2c2aa590_kube-dns-szte1_default_a2a4eb5f-f894-11e4-a0ac-0800279924c6_c1d9f90e",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/skydns",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/4a51ca5fb7097ddcf23d2ea468a460640fb1c2789685cc8c9aa561e623c9f526/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Error": "",
        "ExitCode": 2,
        "FinishedAt": "2015-05-12T10:50:40.245594568Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2015-05-12T10:50:03.54198059Z"
    },
    "Volumes": {
        "/dev/termination-log": "/var/lib/kubelet/pods/a2a4eb5f-f894-11e4-a0ac-0800279924c6/containers/skydns/d70f4ee6e480398da77a5c49a915400e72784a319e56957b2374de0c2c6a5de7"
    },
    "VolumesRW": {
        "/dev/termination-log": true
    }
}
]

**Comment by thockin** [comment] 2015-05-12 16:27
I'm afraid I have no clue why it would be exiting.  Maybe you can edit the
pod spec to add -verbose=true to the skydns container?

**Comment by biswars** [comment] 2015-05-13 06:37
I have started a fresh cluster manually and just created the dns rc with verbose=true in skydns. Note, I am running the cluster locally and not on GCE.

The followings are the logs:
core@core-02 ~ $ ./kubectl log -f kube-dns-lvdd5 skydns
2015-05-13T06:34:15.397362691Z 2015/05/13 06:34:15 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [6]
2015-05-13T06:34:15.397362691Z 2015/05/13 06:34:15 skydns: ready for queries on kubernetes.local. for tcp://0.0.0.0:53 [rcache 0]
2015-05-13T06:34:15.397362691Z 2015/05/13 06:34:15 skydns: ready for queries on kubernetes.local. for udp://0.0.0.0:53 [rcache 0]
[2015-05-13T06:34:54.118964308Z] 2015/05/13 06:34:54 skydns: received DNS Request for "foobar." from "127.0.0.1:59712" with type 1
[2015-05-13T06:34:54.119188618Z] 2015/05/13 06:34:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'
[2015-05-13T06:34:54.479883088Z] 2015/05/13 06:34:54 skydns: received DNS Request for "foobar." from "127.0.0.1:38381" with type 1
[2015-05-13T06:34:54.480267947Z] 2015/05/13 06:34:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'
[2015-05-13T06:34:54.646914970Z] 2015/05/13 06:34:54 skydns: received DNS Request for "foobar." from "127.0.0.1:41272" with type 1
[2015-05-13T06:34:54.647153001Z] 2015/05/13 06:34:54 skydns: can not forward, name too short (less than 2 labels): `foobar.'

Absolutely, have got no clue where the DNS request for foobar comes as I am using the skydns-rc.yaml almost as it is with no other pods running in my local cluster. The behavior is same, the skydns container exits repeatedly but the dns functionality works well.

**Comment by thockin** [comment] 2015-05-13 06:57
Aha.  foobar is the name that the healthcheck uses to see if DNS is alive.
If you deployed TODAY you might see it broken as you describe (I just filed
a bug on it).

But that doesn't explain why it was failing yesterday.  Can you look in
that node's kubelet log for any clues about healthcheck failing?

**Comment by looztra** [comment] 2015-05-16 11:31
I encounter the same pb as @biswars.

DNS resolution is fine, but the skydns containers is getting killed every 30s.

The problem seems to be related to the check/livenessProbe. By disabling it, the skydns container is not killed anymore.

```yaml
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.kube.local localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

still investigating, while discovering kubernetes internals :)

**Comment by gosharplite** [comment] 2015-06-02 09:03
I also encounter very similar issue. Skydns is getting killed every 30s unless livenessProbe is disable. Logs of skydns before getting killed are shown below.
```
2015/06/02 08:36:46 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [632]
2015/06/02 08:36:46 skydns: ready for queries on kubernetes.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/02 08:36:46 skydns: ready for queries on kubernetes.local. for udp://0.0.0.0:53 [rcache 0]
2015/06/02 08:37:16 skydns: received DNS Request for "kubernetes.default.kubernetes.local." from "127.0.0.1:45901" with type 1
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa." from "127.0.0.1:54704" with type 12
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa.openstacklocal." from "127.0.0.1:43411" with type 12
2015/06/02 08:37:16 skydns: received DNS Request for "kubernetes.default.kubernetes.local." from "127.0.0.1:53171" with type 1
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa." from "127.0.0.1:57561" with type 12
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa.openstacklocal." from "127.0.0.1:42054" with type 12
2015/06/02 08:37:16 skydns: received DNS Request for "kubernetes.default.kubernetes.local." from "127.0.0.1:35208" with type 1
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa." from "127.0.0.1:33474" with type 12
2015/06/02 08:37:16 skydns: received DNS Request for "2.0.10.10.in-addr.arpa.openstacklocal." from "127.0.0.1:52351" with type 12
```

**Comment by gosharplite** [comment] 2015-06-03 01:14
This might be a version issue. #8538

**Comment by thockin** [comment] 2015-06-03 03:53
I'm happy to debug if you can repro with 0.18 kubernetes and 1.7 kube2sky.

**Comment by gosharplite** [comment] 2015-06-03 09:50
@thockin My environment is created as shown.
1. [Pure openstack](http://docs.openstack.org/kilo/install-guide/install/apt/content/) on three physical servers.
2. CoreOS cluster based on @kelseyhightower [cloud-config file](https://github.com/kelseyhightower/osdc-2015/blob/master/demo/configs/kubernetes.yaml).
3. Kubernetes cluster based on  @kelseyhightower [demo](https://github.com/kelseyhightower/osdc-2015/tree/master/demo).
4. "token-system-dns" is enabled by following [authentication doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/authentication.md) and [manually replicating](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addons.sh) what salt is doing on GCE setup.

I have repro with 0.18 kubernetes and 1.8 kube2sky.

Kube2sky is working. It sets DNS record every 6 seconds.
```
$ kubectl get se
NAME            LABELS                                                                           SELECTOR            IP(S)          PORT(S)
frontend        name=frontend                                                                    name=frontend       10.10.32.4     80/TCP
kube-dns        k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns    10.10.0.10     53/UDP
                                                                                                                                    53/TCP
kubernetes      component=apiserver,provider=kubernetes                                          <none>              10.10.0.2      443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes                                          <none>              10.10.0.1      80/TCP
redis-master    name=redis-master                                                                name=redis-master   10.10.148.17   6379/TCP
redis-slave     name=redis-slave                                                                 name=redis-slave    10.10.1.237    6379/TCP
```
```
$ kubectl logs -f kube-dns-v2-htd8v kube2sky
I0603 09:24:21.683376       1 kube2sky.go:219] Setting DNS record: frontend.default.kubernetes.local. -> "{\"host\":\"10.10.32.4\",\"port\":80,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.687399       1 kube2sky.go:219] Setting DNS record: frontend.default.svc.kubernetes.local. -> "{\"host\":\"10.10.32.4\",\"port\":80,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.697698       1 kube2sky.go:219] Setting DNS record: kube-dns.default.kubernetes.local. -> "{\"host\":\"10.10.0.10\",\"port\":53,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.700019       1 kube2sky.go:219] Setting DNS record: kube-dns.default.kubernetes.local. -> "{\"host\":\"10.10.0.10\",\"port\":53,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.702035       1 kube2sky.go:219] Setting DNS record: kube-dns.default.svc.kubernetes.local. -> "{\"host\":\"10.10.0.10\",\"port\":53,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.717846       1 kube2sky.go:219] Setting DNS record: kube-dns.default.svc.kubernetes.local. -> "{\"host\":\"10.10.0.10\",\"port\":53,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.722932       1 kube2sky.go:219] Setting DNS record: kubernetes.default.kubernetes.local. -> "{\"host\":\"10.10.0.2\",\"port\":443,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.743179       1 kube2sky.go:219] Setting DNS record: kubernetes.default.svc.kubernetes.local. -> "{\"host\":\"10.10.0.2\",\"port\":443,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.764960       1 kube2sky.go:219] Setting DNS record: kubernetes-ro.default.kubernetes.local. -> "{\"host\":\"10.10.0.1\",\"port\":80,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.785767       1 kube2sky.go:219] Setting DNS record: kubernetes-ro.default.svc.kubernetes.local. -> "{\"host\":\"10.10.0.1\",\"port\":80,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.801481       1 kube2sky.go:219] Setting DNS record: redis-master.default.kubernetes.local. -> "{\"host\":\"10.10.148.17\",\"port\":6379,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.813042       1 kube2sky.go:219] Setting DNS record: redis-master.default.svc.kubernetes.local. -> "{\"host\":\"10.10.148.17\",\"port\":6379,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.840666       1 kube2sky.go:219] Setting DNS record: redis-slave.default.kubernetes.local. -> "{\"host\":\"10.10.1.237\",\"port\":6379,\"priority\":10,\"weight\":10,\"ttl\":30}"
I0603 09:24:21.845566       1 kube2sky.go:219] Setting DNS record: redis-slave.default.svc.kubernetes.local. -> "{\"host\":\"10.10.1.237\",\"port\":6379,\"priority\":10,\"weight\":10,\"ttl\":30}"
```
Skydns is also working. It is stable and receive DNS requests from livenessProbe every 10 seconds.
```
$ kubectl logs -f kube-dns-v2-htd8v skydns
2015/06/03 09:28:18 skydns: received DNS Request for "kubernetes.default.kubernetes.local." from "127.0.0.1:38995" with type 1
2015/06/03 09:28:18 skydns: received DNS Request for "2.0.10.10.in-addr.arpa." from "127.0.0.1:37543" with type 12
2015/06/03 09:28:18 skydns: received DNS Request for "2.0.10.10.in-addr.arpa.openstacklocal." from "127.0.0.1:54534" with type 12
2015/06/03 09:28:28 skydns: received DNS Request for "kubernetes.default.kubernetes.local." from "127.0.0.1:44221" with type 1
2015/06/03 09:28:28 skydns: received DNS Request for "2.0.10.10.in-addr.arpa." from "127.0.0.1:35247" with type 12
2015/06/03 09:28:28 skydns: received DNS Request for "2.0.10.10.in-addr.arpa.openstacklocal." from "127.0.0.1:48363" with type 12
``` 
The guestbook example is working too. Sending http command will trigger DNS requests in skydns.
```
$ curl "http://192.168.4.48/index.php?cmd=set&key=messages&value=tony_sais_hi"
{"message": "Updated"}
```
```
$ kubectl logs -f kube-dns-v2-htd8v skydns
2015/06/03 09:34:13 skydns: received DNS Request for "redis-master.default.kubernetes.local." from "10.1.5.1:43385" with type 28
2015/06/03 09:34:13 skydns: received DNS Request for "redis-master.kubernetes.local." from "10.1.5.1:35653" with type 28
2015/06/03 09:34:13 skydns: received DNS Request for "redis-master.openstacklocal." from "10.1.5.1:57538" with type 28
2015/06/03 09:34:13 skydns: received DNS Request for "redis-master." from "10.1.5.1:56078" with type 28
2015/06/03 09:34:13 skydns: can not forward, name too short (less than 2 labels): `redis-master.'
2015/06/03 09:34:13 skydns: received DNS Request for "redis-master.default.kubernetes.local." from "10.1.5.1:53258" with type 1
```
This issue does not exist in my environment now.
Many thanks for giving me direction to use latest version.

**Comment by erimatnor** [comment] 2015-06-09 09:30
I have the same issue with a similar setup. Not using token auth (disabled in DNS pod). Skydns pod restarted due to failed livenessProbe. Interestingly, executing the same command (nslookup) in the container via kubectl returns a 0-value exit code, so don't really understand why probe fails.

**Comment by looztra** [comment] 2015-06-10 05:51
@erimatnor which version of kubernetes are you using? I had the same trouble with versions < 0.18 and it seems to not happen anymore since 0.18

**Comment by goltermann** [comment] 2015-08-25 22:23
Closing as this doesn't appear to be reproducing currently.  Please reopen if you see it happening with Kubernetes 1.x

**Comment by kpatryk** [comment] 2016-01-26 15:12
Hi,

I'm facing the same issue with most recent version of Kubernetes v1.1.2:
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

while DNS seems to work inside Kubernetes cluster as expected SkyDns  container is killed every 30 seconds:
```
docker  ps -a -f name=k8s_skydns
CONTAINER ID        IMAGE                                                COMMAND                CREATED              STATUS                          PORTS               NAMES
3aebc59ddaa2        gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=h   29 seconds ago       Up 29 seconds                                       k8s_skydns.58571485_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_8024d18c   
bd359d2f85d7        gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=h   59 seconds ago       Exited (2) 29 seconds ago                           k8s_skydns.58571485_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_178b7325   
f87bfec07e77        gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=h   About a minute ago   Exited (2) 59 seconds ago                           k8s_skydns.58571485_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_01ec049c   
3d66b280cbdf        gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=h   About a minute ago   Exited (2) About a minute ago                       k8s_skydns.58571485_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_08b6559e   
3872aa532f97        gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=h   2 minutes ago        Exited (2) About a minute ago                       k8s_skydns.58571485_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_ebbace2c 
```

Kube2Sky version: 1.11
```
docker  ps -a -f name=k8s_kube2sky
CONTAINER ID        IMAGE                                    COMMAND                CREATED             STATUS              PORTS               NAMES
fcd59cd90641        gcr.io/google_containers/kube2sky:1.11   "/kube2sky -domain=c   2 hours ago         Up 2 hours                              k8s_kube2sky.8fa9debd_kube-dns-v9-lg9iv_kube-system_585d576f-c428-11e5-8f4f-066fb0fb812d_82b29f71   
```

Exited containers logs contain the same messages:
```
docker  logs b5c6e456aebe 
2016/01/26 15:08:04 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2016/01/26 15:08:04 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/01/26 15:08:04 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```

I have 3 minions deployed on AWS. Problem exists in all of them. Kube-proxy is flooding /var/log/syslog with the following messages:
```
Jan 26 14:55:47 ubuntu kube-proxy[17101]: E0126 14:55:47.857664   17101 proxysocket.go:93] Couldn't find an endpoint for kube-system/kube-dns:dns: missing service entry
Jan 26 14:55:47 ubuntu kube-proxy[17101]: E0126 14:55:47.857735   17101 proxysocket.go:93] Couldn't find an endpoint for kube-system/kube-dns:dns: missing service entry
Jan 26 14:55:48 ubuntu kube-proxy[17101]: E0126 14:55:48.044071   17101 proxysocket.go:93] Couldn't find an endpoint for kube-system/kube-dns:dns: missing service entry
Jan 26 14:55:48 ubuntu kube-proxy[17101]: E0126 14:55:48.044109   17101 proxysocket.go:93] Couldn't find an endpoint for kube-system/kube-dns:dns: missing service entry
Jan 26 14:55:48 ubuntu kube-proxy[17101]: E0126 14:55:48.566886   17101 proxysocket.go:165] I/O error: write tcp 10.244.0.5:43171: broken pipe
Jan 26 14:55:48 ubuntu kube-proxy[17101]: E0126 14:55:48.676225   17101 proxysocket.go:165] I/O error: write tcp 10.244.0.5:43173: broken pipe
```

and 
```
Jan 26 14:57:54 ubuntu kubelet[17029]: I0126 14:57:54.180346   17029 prober.go:169] Readiness probe for "kube-dns-v9-lg9iv_kube-system:skydns" failed (failure): Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
```

Any idea ?

**Comment by streamnsight** [comment] 2016-02-03 22:56
same problem here... I'm using v10 as per the RC and SVC described here: 
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns

however I see recent updates but not version bump in the YAML. 
What is the latest version to use?

**Comment by diseku** [comment] 2016-02-04 14:04
please reopen. same here with cluster/ubuntu

`  23s	23s	1	{kubelet <my_ip_here>}	spec.containers{skydns}	Unhealthy	Readiness probe failed: Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2016-02-04 14:02:42.393158391 +0000 UTC, error exit status 1

  23s	23s	1	{kubelet <my_ip_here>}	spec.containers{skydns}	Started		Started with docker id 04d52e33f1cc
  14m	23s	29	{kubelet <my_ip_here>}	spec.containers{skydns}	Pulled		Container image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c" already present on machine
  23s	23s	1	{kubelet <my_ip_here>}	spec.containers{skydns}	Killing		Killing with docker id db6b2e8b071c
  23s	23s	1	{kubelet <my_ip_here>}	spec.containers{skydns}	Created		Created with docker id 04d52e33f1cc
  13s	13s	1	{kubelet <my_ip_here>}	spec.containers{skydns}	Unhealthy	Readiness probe failed: Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
`

**Comment by streamnsight** [comment] 2016-02-04 18:46
@thockin @goltermann 

A little more info here: 
It seems to work 'sometimes'. I can't really understand when it works vs. when it does not, but what what I see with the pod 'describe' command, is that the health check fails either way: So when it 'works', it's when the health check didn't kill the container, while most times the container gets killed.

So, even though the health check fails the DNS works.

I would think you should be able to reproduce the `Readiness probe failed: Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'` part of the problem.

Now, as I said earlier I run the v10 version as describes in the repo here https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns but it is not up-to-date with the latest changes.

where do i find the latest skydns / kube2sky images to use? 
is there an easy way to browse these images somewhere? 
Thanks

**Comment by diseku** [comment] 2016-02-05 10:53
Ensure that you're not blocking udp with iptables for flannel and svc subnet and between the cluster nodes

**Comment by streamnsight** [comment] 2016-02-05 15:38
@diseku as i said Dns works when the pod runs, even thought the helth check failed. 
to me it must be a timing issue where the healthcheck is done too soon or something. 

i still didn't hear an answer about the latest image version to use and how to find out: thise images are on gcr.io but how to browse this registry for images??? i could not find the url for that.

thanks

**Comment by thecanadianbaker** [comment] 2016-02-12 13:58
@ArtfulCoder seems like this started for me after experiencing #15227 and resolving by restarting the pause container

**Comment by kpatryk** [comment] 2016-02-18 11:52
Hi,

In my case problem has been solved after upgrading Kubernetes cluster from version 1.1.2 to 1.1.7
Additionally I did some changes in cluster/aws/config-default.sh, one of the major one was to bump up MASTER_SIZE value to **t2.medium**. It provisions master node with 4 GB RAM, when previously it was only 2 GB and there was no swap configured in the standard AMI image (based on Ubuntu 15.04 Vivid). I noticed a lot of SSL/TLS timeouts in the master logs (communication with minions) and it was also happening when running kubectl. All this problem disappeared right now.

**Comment by ArtfulCoder** [comment] 2016-02-19 05:14
@streamnsight the version of containers to use can be found in
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in

**Comment by streamnsight** [comment] 2016-02-22 18:10
@ArtfulCoder this is what I am using, yet it is not the latest: the skydns docker image is 2015-10-13, while the repo has updates from this month. So my question is where do we find the most recent built images?

**Comment by r8k** [comment] 2016-03-08 05:42
@streamnsight not sure if this might help you, but here is a Dockerfile that I use to build SkyDNS myself. Dockerhub & GCR have old images, and hence I came up with this one. I have similar Dockerfiles for Kube2Sky et all (the ones from GCR are old, partly because GCR does not support trusted builds like Dockerhub yet, and hence my effort)

````
FROM debian:8.3

# set env variables
ENV GOLANG_VERSION 1.6
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz

# fetch base packages
RUN apt-get update && \
    apt-get install -y \
        --no-install-recommends \
        ca-certificates \
        g++ \
        gcc \
        tar \
        git \
        curl \
        xz-utils \
        libc6-dev \
    && rm -rf /var/lib/apt/lists/*

# install golang
RUN curl -SL \
  "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" | \
  tar -xzf - -C /usr/local

# set go path
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

# mkdir gopath
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

# build skydns
RUN go get github.com/skynetservices/skydns && \
    CGO_ENABLED=0 go build -a -installsuffix cgo \
    --ldflags '-w' github.com/skynetservices/skydns

# entrypoint
ENTRYPOINT ["/skydns"]
````

**Comment by zebulonj** [comment] 2016-03-23 18:48
Experiencing the same problem (DNS restarted every 30 seconds, appears to be killed by failed health check). Running kubernetes v1.1.2 on CoreOS, deployed following the [step-by-step guide](https://coreos.com/kubernetes/docs/latest/getting-started.html). Originally (for four weeks), everything worked fine save the very occasional DNS failure and restart. Then, restarted the DNS service/pod and have experiences what others have described above for ~24 hours (despite several attempts to fix).

Must recent fix attempt was to use the [ReplicationController definition](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in) provided above by @ArtfulCoder, but same result.

**Comment by liuyue2656** [comment] 2016-03-29 07:27
The same problem with me. Util I add `--kube_master_url=http://k8s-master:8080` in kube2sky_rc.yaml be fixed it.

**Comment by thockin** [comment] 2016-04-19 04:17
You should not need the master URL flag unless service accounts are not
configured.

https://github.com/GoogleCloudPlatform/kubernetes/issues/10265#issuecomment-117267504

**Closed by thockin** 2016-04-19 04:17 UTC
Labels: area/cluster-lifecycle, kind/support, team/cluster

**Comment by santanu-dey** [comment] 2016-07-17 10:04
Have a look at  #26943
There is a genuine bug that the service accounts being empty and that creates skydns to crash. 
The workaround suggested on that issue worked for me. FYI.

**Comment by crockpotveggies** [comment] 2017-02-21 21:21
Pretty much happening to us now, this issue describes a similar problem: https://github.com/kubernetes/kubernetes/issues/39489#issuecomment-281437557

**Comment by aloisio31** [comment] 2017-06-15 12:11
according to @looztra commented on 16 May 2015, that's exactly the reson.
In my case, I have such configuration in my dns-rc.yml:
`          livenessProbe:
            exec:
              command:
                - /bin/sh
                - "-c"
                - "nslookup kubernetes.default.svc.cluster.local localhost >/dev/null"
            initialDelaySeconds: 30
            timeoutSeconds: 5`
while I give kublet & skydns the cluster-domain "my.cluster". When I try the livenessProbe command in bash:
`kubectl --namespace=kube-system exec kube-dns-vkb6q nslookup kubernetes.default.svc.cluster.local localhost`, it return **fail** normally. So you can check your yml to give it a correct command.

By the way, only if you give your kubelet parameter "--cluster-dns x.x.x.x --cluster-domain xxx.xxx" and restart it, and make sure kube-probxy is running, you can access the domain name "kubernetes.default.svc._your.domain_" via its **clusterIP**.

Here is my result run in bash:
`# kubectl --namespace=kube-system exec kube-dns-vkb6q nslookup kubernetes.default.svc.my.cluster
Defaulting container name to etcd.
Use 'kubectl describe pod/kube-dns-vkb6q' to see all of the containers in this pod.
Server:         10.200.20.88
Address:        10.200.20.88#53

Name:   kubernetes.default.svc.my.cluster
Address: 10.200.20.1
