### ISSUE TITLE
Support Use Cases which involve Running Jobs to Completion on all nodes

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#40290] opened 2017-01-23 09:16 UTC
- Sometimes i want to run debugging commands across all nodes or a subset of nodes. This might be to collect some data quickly for analysis, collect the output of certain commands, or just make some temporary changes to nodes to validate an experiment.
- These commands are run to completion type Jobs, where i don't need them to be running always to ensure reconciliation
- These run to completion jobs may not be necessarily related to making changes to nodes. They could be verifying the presence of pods, or certain aspects of pods.
- DaemonSets requires pod to be running with restartAlways and Jobs dont have anything similar.
- We can have a discussion about other use-cases the community already sees here

**Comment by erictune** [comment] 2017-01-24 05:51
@kubernetes/sig-apps-feature-requests

**Comment by rothgar** [comment] 2017-01-24 15:56
Probably a duplicate of #36601

**Comment by kargakis** [comment] 2017-01-25 09:38
> Probably a duplicate of #36601

Agreed. @krmayankk please let me know if you think #36601 is not covering your use cases.

**Closed by kargakis** 2017-01-25 09:38 UTC
