### ISSUE TITLE
1000 node cluster is failing performance tests

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20400] opened 2016-02-01 09:35 UTC
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/50/build-log.txt

cc @kubernetes/sig-scalability @wojtek-t @alex-mohr @davidopp @fgrzadkowski @brendandburns

**Comment by hongchaodeng** [comment] 2016-02-01 16:07
@gmarek Can you share the logs?

I confirmed that it also failed on Kubemark. It's caused by high latency (>1s) api requests. In logs, it showed:
```
API calls latencies: {
  "apicalls": [
    {
      "resource": "nodes",
      "verb": "LIST",
      "latency": {
        "Perc50": 136212000,
        "Perc90": 547053000,
        "Perc99": 1008779000
      }
    },
  ...
  ]
}
```

**Comment by timothysc** [comment] 2016-02-01 16:39
Do we have a bi-sect?  

/cc @ncdc

**Comment by davidopp** [comment] 2016-02-01 20:57
Removing flake label since this is not a flake. Leaving P0 since this is definitely P0.

**Comment by gmarek** [comment] 2016-02-02 10:34
Last successful run: https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/41/build-log.txt
Failing one: https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/49/build-log.txt

It happened on a day when we changed to go 1.5.3, which makes it my prime suspect. There's also @smarterclayton PR #16067 that in some strange world can case it as well, but given our experiences with different version of go I don't think it's the main cause.

Digging deeper.

**Comment by gmarek** [comment] 2016-02-02 10:52
For kubemark regression happened between 10:15 and 11:16 am (MTV time) on Jan 21st.

**Comment by gmarek** [comment] 2016-02-02 15:08
I have some data from kubemark, which also shows that we regressed somewhere in last week and a half.
Latencies from the run on commit a9050679a5810eb9bfcf9eb9ca98991a7a0e8ef0:
```
Feb  2 16:03:02.196: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:138.793ms Perc90:232.645ms Perc99:485.957ms}}
Feb  2 16:03:02.196: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:94.532ms Perc90:127.44ms Perc99:325.172ms}}
Feb  2 16:03:02.196: INFO: Top latency metric: {Resource:pods Verb:POST Latency:{Perc50:7.417ms Perc90:17.684ms Perc99:221.175ms}}
Feb  2 16:03:02.196: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:14.28ms Perc90:16.642ms Perc99:42.436ms}}
Feb  2 16:03:02.196: INFO: Top latency metric: {Resource:pods Verb:PUT Latency:{Perc50:11.056ms Perc90:15.861ms Perc99:23.174ms}}
```

From the ~head:
```
Feb  2 14:31:39.621: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:121.186ms Perc90:378.483ms Perc99:652.822ms}}
Feb  2 14:31:39.621: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:80.953ms Perc90:155.79ms Perc99:548.367ms}}
Feb  2 14:31:39.621: INFO: Top latency metric: {Resource:componentstatuses Verb:LIST Latency:{Perc50:260.097ms Perc90:260.097ms Perc99:260.097ms}}
Feb  2 14:31:39.621: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:14.102ms Perc90:20.246ms Perc99:250.619ms}}
Feb  2 14:31:39.621: INFO: Top latency metric: {Resource:nodes Verb:GET Latency:{Perc50:793µs Perc90:3.118ms Perc99:173.743ms}}
```

Sadly it takes quite some time to run single experiment, so I can't tell that if it wasn't an anomaly.

**Comment by smarterclayton** [comment] 2016-02-02 16:40
There's some data suggesting that Go 1.5 GC has some issues in certain
corner cases (InfluxDB was reporting something similar).  Was this Go 1.4
-> 1.5.3, or 1.5.2 -> 1.5.3.  My retry case could certainly increase load
on server in certain cases.

**Comment by gmarek** [comment] 2016-02-02 17:11
I think it was Go 1.4 -> 1.5.3, but I'm not sure. @zmerlynn

**Comment by smarterclayton** [comment] 2016-02-02 17:43
https://github.com/golang/go/issues/14189

**Comment by zmerlynn** [comment] 2016-02-02 22:07
All recent `v1.2.0-alpha` builds are go 1.5.3, yes.

**Comment by zmerlynn** [comment] 2016-02-02 22:09
... but we can't do what InfluxDB did, because we have some pretty massive issues on 1.4.3. 1.4.2 was the last even vaguely happy point.

**Comment by gmarek** [comment] 2016-02-02 22:38
At this point it seems tat using 1.5.3 makes us violate our SLO for API call latencies on 1000 Node clusters. We can either loosen the SLO for big clusters or revert to 1.4.2. We can also hope to make enough improvements in the current code, but given how close we are to v1.2 I doubt we'll make it:/

cc @smarterclayton @timothysc @wojtek-t @davidopp @brendandburns @thockin

**Comment by timothysc** [comment] 2016-02-03 03:07
we (red hat) will not switch to 1.5.X for a while because it has to go through our channel update process.  That being said, I thought @wojtek-t was running 1.5.X for a while earlier and the number were passing.?.?

**Comment by gmarek** [comment] 2016-02-03 10:21
He was running mostly unit and integration tests. I know nothing about performance testing of 1.5.

**Comment by gmarek** [comment] 2016-02-03 13:19
It won't be a surprise for anyone, but I confirmed that it's go1.5. Results from 1000 node kubemark from commit 83a6b7fcaa2869744c7929b0c9b568168df60a10 (Merge pull request #19957):
```
Feb  3 14:17:26.402: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:131.779ms Perc90:235.184ms Perc99:490.191ms}}
Feb  3 14:17:26.402: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:91.885ms Perc90:106.852ms Perc99:294.336ms}}
Feb  3 14:17:26.402: INFO: Top latency metric: {Resource:pods Verb:POST Latency:{Perc50:7.71ms Perc90:16.019ms Perc99:165.464ms}}
Feb  3 14:17:26.402: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:14.519ms Perc90:16.62ms Perc99:146.373ms}}
Feb  3 14:17:26.402: INFO: Top latency metric: {Resource:pods Verb:PUT Latency:{Perc50:9.77ms Perc90:15.772ms Perc99:23.25ms}}
```

from commit d26f4e15839a23b3350ffaa0575995ee81ddda50 (Up to golang 1.5.3):
```
Feb  3 10:08:13.951: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:122.881ms Perc90:374.265ms Perc99:820.686ms}}
Feb  3 10:08:13.951: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:84.217ms Perc90:181.847ms Perc99:588.343ms}}
Feb  3 10:08:13.951: INFO: Top latency metric: {Resource:pods Verb:POST Latency:{Perc50:8.99ms Perc90:16.913ms Perc99:241.808ms}}
Feb  3 10:08:13.951: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:14.436ms Perc90:18.673ms Perc99:229.869ms}}
Feb  3 10:08:13.951: INFO: Top latency metric: {Resource:nodes Verb:GET Latency:{Perc50:786µs Perc90:2.103ms Perc99:163.343ms}}
```

Results are repeatable.

**Comment by wojtek-t** [comment] 2016-02-03 14:15
@timothysc - yes I was running Go 1.5, but only on 100-node clusters, where we don't see that significant difference.
It seems that on 1000-node clusters, the difference is much bigger (2x ?), and Go 1.5 makes things much worse...

**Comment by timothysc** [comment] 2016-02-03 15:14
@gmarek are you still running single master configuration at 1000.  I'm guessing this is a function of how often gc is getting kicked.   

If you spread the load what are the results?   Anything above 100 I would always recommend 3.

**Comment by wojtek-t** [comment] 2016-02-03 15:18
Yes - we are running single master. I think that 1000 nodes is few enough so that we should handle it with a single apiserver (and note that we can handle it with Go 1.4.2).
From performance perspective it seems that Go 1.5.3 doesn't provide any value, and makes the metrics worse...

[Note that I still think that we should upgrade to Go 1.5.3 at some point, but the question is whether we are ready for it now].

**Comment by smarterclayton** [comment] 2016-02-03 17:18
Have we tried the GC tuning recommended in the golang issue?

**Comment by zmerlynn** [comment] 2016-02-03 19:50
Is there a way we can try out new Go versions / Go settings without introducing them to the entire project? This method of injecting a new cross-build image into the whole project and pulling it all the way back out just to have the scalability folks say that it's regressed is probably not long term viable. I think we can probably muddle through a separate `kubernetes-build` job for, say, an `alpha` channel cross-build image, so we can test out build-image changes, if that's what it takes.

**Comment by zmerlynn** [comment] 2016-02-03 19:50
cc @ihmccreery @david-mcmahon

**Comment by thockin** [comment] 2016-02-04 04:47
We should try obvious and documented mitigations and then make sure the Go
folks are aware.  This is bad stuff.

**Comment by thockin** [comment] 2016-02-04 04:48
NM, I see the link to go :)

**Comment by wojtek-t** [comment] 2016-02-04 08:05
With revert to Go 1.4.2 we seem to be back to normal - thanks for reverting @zmerlynn 
So I'm closing this one.

**Closed by wojtek-t** 2016-02-04 08:05 UTC
Labels: area/performance, priority/P0, team/control-plane

**Comment by davidopp** [comment] 2016-02-04 08:09
Thanks for noticing this and debugging and fixing it!!

**Comment by smarterclayton** [comment] 2016-02-04 16:11
Can we open a tracking issue for Go 1.5 and link back to this so we can
coordinate release stuff around it?

**Comment by lavalamp** [comment] 2016-02-04 18:46
I came here to say what Clayton said. I will make an issue.
