### ISSUE TITLE
Validation for fields in wrong place, extra fields, etc

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#17165] opened 2015-11-12 17:27 UTC
Right now the validation seems to consist of validating well-formed doc & validating fields. It does not validate fields that are in the wrong place in a manifest or indeed extra, unknown fields. These are silently ignored. This is especially annoying when you're using YAML & e.g. you've messed up indentation of an optional field. Hard to troubleshoot.

Would be good to validate extraneous fields somehow.

**Comment by bgrant0607** [comment] 2015-11-13 23:52
--validate is on by default in kubectl now, and should catch this, though error messages could be better. 

Server-side validation is covered by #5889, but it's tricky due to version-skewed scenarios.

Closing as dupe of #5889.

**Closed by bgrant0607** 2015-11-13 23:52 UTC
