### ISSUE TITLE
[Failing test] ci-kubernetes-unit test failing 

### ISSUE THREAD

**Issue by gnoam** [kubernetes/kubernetes#110867] opened 2022-06-29 16:11 UTC
### Which jobs are failing?

[sig-release-master-blocking: ci-kubernetes-unit](https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit)

### Which tests are failing?

`k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestMain`

### Since when has it been failing?

28-06-2022 

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
 W0628 22:00:17.460786   67293 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    volume_binding_test.go:625: Feed testing data and wait for them to be synced
    volume_binding_test.go:639: Start informer factory after initialization
    volume_binding_test.go:642: Wait for all started informers' cache were synced
    volume_binding_test.go:645: Verify
    volume_binding_test.go:656: Verify: call PreFilter and check status
    volume_binding_test.go:659: filter prefilter status does not match: &{1 [error getting PVC "default/pvc-1": could not find v1.PersistentVolumeClaim "default/pvc-1"] 0xc000426b20 }, want: <nil>
    --- FAIL: TestVolumeBinding/local_volumes_with_close_capacity_are_preferred_(multiple_pvcs) (0.07s)
 ```

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by pohly** [comment] 2022-06-29 19:08
/close

This is a duplicate of https://github.com/kubernetes/kubernetes/issues/110854.

**Closed** 2022-06-29 19:08 UTC
Labels: sig/testing, kind/failing-test, needs-triage
