### ISSUE TITLE
can someone help solve this probelm: git commit err: Error in /hack/lib/etcd.sh:35

### ISSUE THREAD

**Issue by lixiaobing10051267** [kubernetes/kubernetes#31338] opened 2016-08-24 10:14 UTC
root@ubuntu:/home/zte/share/k8s-clone2/src/k8s.io/kubernetes# git commit
Checking that it builds... OK
...
Checking for swagger spec that need updating... !!! Error in /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:35
'version=$(etcd --version | head -n 1 | cut -d " " -f 3)' exited with status 141
Call stack:
1: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:35 kube::etcd::start(...)
2: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/update-swagger-spec.sh:59 main(...)
Exiting with status 1
!!! Error in hack/verify-swagger-spec.sh:38
'"${KUBE_ROOT}/hack/update-swagger-spec.sh"' exited with status 1
Call stack:
1: hack/verify-swagger-spec.sh:38 main(...)
Exiting with status 1
ERROR!
Swagger spec needs to be updated.
To regenerate the spec, run:
hack/update-swagger-spec.sh

Aborting commit

**Comment by dims** [comment] 2016-08-24 10:19
@lixiaobing10051267 isn't this a duplicate of https://github.com/kubernetes/kubernetes/issues/31232 ?

**Closed** 2016-11-16 06:44 UTC
Labels: component/apiserver, team/CSI-API Machinery SIG

**Comment by henrynash** [comment] 2016-12-05 14:22
I think I managed to work out what is wrong here: See: hack/etcd script can fail with pipe error 141 in some circumstances #38109
