### ISSUE TITLE
Allow port-forwarding to more interfaces than just localhost

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#42298] opened 2017-03-01 02:12 UTC
**FEATURE REQUEST?**

`kubectl` port forwarding appears to be limited to the `localhost` interface, as opposed to `0.0.0.0`. This makes it difficult for some network applications to access the local port.

For example, a Docker container running on a non-Linux host will likely be unable to resolve `localhost:80` to the port opened by `kubectl port-forward 80`. So debugging microservices in Kubernetes by port-forwarding and running some microservices locally in Docker becomes more difficult.

If `kubectl` can make the local port available on more local network interfaces, then applications could be configured for addresss like `$(ifconfig en0 inet):80` and such, enabling them to communicate with the remote Kubernetes port.

It is possible to work around this Kubernetes limitation by OS-specific port-forwarding, but this may be difficult for some users.

**Comment by chihangc** [comment] 2017-09-05 10:04
Agree. A lot of images like mongo expose the port. Forwarding 127.0.0.1 can't help

**Comment by manikantag** [comment] 2018-02-06 10:05
Duplicate of https://github.com/kubernetes/kubernetes/issues/43962

**Closed** 2018-04-07 11:35 UTC
Labels: lifecycle/rotten, sig/network
