### ISSUE TITLE
kubectl apply should be able to take a List

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19639] opened 2016-01-14 03:14 UTC
kubectl create, delete, etc. can already take a List object. kubectl apply can take the list object when it does creation, but it gives an (ugly) error when it's configuring the objects.

```
$ cat rcs.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx
  spec:
    replicas: 1
    selector:
      run: nginx
    template:
      metadata:
        labels:
          run: nginx
      spec:
        containers:
        - image: nginx
          name: nginx
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx-2
  spec:
    replicas: 1
    selector:
      run: nginx-2
    template:
      metadata:
        labels:
          run: nginx-2
      spec:
        containers:
        - image: nginx
          name: nginx-2
$ kubectl create -f rcs.yaml
replicationcontroller "nginx" created
replicationcontroller "nginx-2" created
$ kubectl delete -f rcs.yaml
replicationcontroller "nginx" deleted
replicationcontroller "nginx-2" deleted
$ kubectl apply -f rcs.yaml
replicationcontroller "nginx" created
replicationcontroller "nginx-2" created
```

Then... expected:

```
$ kubectl apply -f rcs.yaml
replicationcontroller "nginx" configured
replicationcontroller "nginx-2" configured
$
```

Actual:

```
$ kubectl apply -f rcs.yaml
expected a struct, but received a %!t(string=nil)
expected a struct, but received a %!t(string=nil)
$
```

**Comment by AdoHe** [comment] 2016-01-14 08:24
@ghodss what's you `kubelet version`?

**Comment by ghodss** [comment] 2016-01-15 06:05
1.2.0-alpha.5

**Comment by bgrant0607** [comment] 2016-01-23 06:41
Sounds like a bug. Are you interested in taking a look @AdoHe?

**Comment by AdoHe** [comment] 2016-01-23 13:00
@bgrant0607 sure I will take a look during this weekend.

**Comment by AdoHe** [comment] 2016-01-25 04:33
@bgrant0607 @ghodss I think the root cause is [here](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.5/pkg/util/strategicpatch/patch.go#L479-L482), the `dataStruct` actually is `info.VersionedObject`, in the origin `FileVisitor.StreamVisitor`, `VersionedObject` is not `nil`, but after the `FlattenListVisitor`, this object is nil. Would you like to double check this?

**Comment by jackgr** [comment] 2016-01-27 18:19
I'll take a look.

**Comment by AdoHe** [comment] 2016-01-28 09:50
@jackgr if you have make sure about this, please let me know. Thanks :)

**Comment by ghodss** [comment] 2016-02-09 07:32
@bgrant0607 Is there any ways we could get this into 1.2? It's actually making our config generation quite painful to have to make a separate file for every object. It looks like @AdoHe got pretty far? @AdoHe would you like to make a PR that we can review?

**Comment by bgrant0607** [comment] 2016-02-09 07:41
@ghodss I don't see how. It could have made 1.2 if a PR had been sent within a few days of the issue being filed.

**Comment by bgrant0607** [comment] 2016-02-09 07:43
@jackgr I unassigned all issues assigned to you. Please only assign issues that are actively being worked on, so that others can know which issues are available to be picked up.

**Comment by jackgr** [comment] 2016-02-09 20:52
@ghodss My apologies. If I'm not mistaken, this issue was filed after the code freeze for 1.2. I didn't realize that it was time critical or that it could make the release at that time.

@bgrant0607 Thank you. I still plan to address those issues for the next release, as discussed, but will assign each one to myself as I work on it.

**Comment by ghodss** [comment] 2016-02-10 01:22
@bgrant0607 I created #20948 which fixes this. I'm really hoping we can get this into 1.2 since it's a pretty small, isolated fix but a pretty big bug that is complicating our config generation system. Let me know what else I can do to help.

**Comment by bgrant0607** [comment] 2016-02-10 03:01
@ghodss Thanks for the PR. We're short on reviewer bandwidth at the moment. I assigned it to Clayton for review or delegation.

**Closed** 2016-02-14 08:56 UTC
Labels: area/app-config-deployment, component/kubectl, help-wanted, kind/bug, priority/P2, team/ux
