### ISSUE TITLE
PODs stale in Terminating stage

### ISSUE THREAD

**Issue by pkutishch** [kubernetes/kubernetes#49108] opened 2017-07-18 11:21 UTC
/kind bug

**What happened**:
Pod stays in terminating status forever

**What you expected to happen**:
POD removed.

**How to reproduce it (as minimally and precisely as possible)**:
Provision container with PVC (Dynamic provisioned) using GlusterFS wait untill running and then remove POD

**Anything else we need to know?**:
Events:
```
 1m		1m		1	kubelet, server37	spec.containers{wordpress-mariadb}	Normal		Killing			Killing container with id docker://fd110a30094acb46dfcc2f21bd4d5b6ba8f368925f9ec429c842bb27219e5d79:Need to kill Pod
  1m		1m		1	kubelet, server37						Warning		FailedSync		Error syncing pod, skipping: error killing pod: failed to "KillContainer" for "wordpress-mariadb" with KillContainerError: "rpc error: code = 4 desc = context deadline exceeded"
```
kubelet log
```
E0718 11:18:36.937419   18423 glusterfs.go:145] glusterfs: failed to get endpoints pvc-003c9ec9-6baa-11e7-9aab-002590e7245c[an empty namespace may not be set when a resource name is provided]
E0718 11:18:36.937451   18423 reconciler.go:438] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/0041c0ab-6baa-11e7-b113-00259097cf2c-pvc-003c9ec9-6baa-11e7-9aab-002590e7245c" (spec.Name: "pvc-003c9ec9-6baa-11e7-9aab-002590e7245c") pod "0041c0ab-6baa-11e7-b113-00259097cf2c" (UID: "0041c0ab-6baa-11e7-b113-00259097cf2c") with: an empty namespace may not be set when a resource name is provided
I0718 11:18:38.260423   18423 kubelet_node_status.go:391] Using node IP: "10.250.205.108"
server37 ~ # docker logs kubelet | grep W0718
W0718 11:13:03.390013   18423 conversion.go:110] Could not get instant cpu stats: different number of cpus
W0718 11:14:17.101741   18423 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "wordpress-mariadb-2583066575-9b4jt_default": Unexpected command output nsenter: cannot open : No such file or directory
W0718 11:14:17.109013   18423 pod_container_deletor.go:77] Container "edc0b05b0933bc34b7ab095ccf4e5164ee542021eb61e678d900f216ffa96c7f" not found in pod's containers
W0718 11:14:17.114122   18423 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "wordpress-mariadb-2583066575-9b4jt_default": Unexpected command output nsenter: cannot open : No such file or directory
W0718 11:14:17.826005   18423 kuberuntime_container.go:436] No ref for container {"docker" "fd110a30094acb46dfcc2f21bd4d5b6ba8f368925f9ec429c842bb27219e5d79"}
W0718 11:14:17.832128   18423 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "wordpress-mariadb-2583066575-9b4jt_default": Unexpected command output nsenter: cannot open : No such file or directory
W0718 11:14:18.120564   18423 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "wordpress-mariadb-2583066575-9b4jt_default": Unexpected command output nsenter: cannot open : No such file or directory
```

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- hardware
- cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1381.1.0
VERSION_ID=1381.1.0
BUILD_ID=2017-04-25-2232
PRETTY_NAME="Container Linux by CoreOS 1381.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Linux server37 4.10.12-coreos #1 SMP Tue Apr 25 22:08:35 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz GenuineIntel GNU/Linux
- Install tools: hyperkube

**Comment by wangycc** [comment] 2017-08-31 09:26
+1

**Comment by danielqsj** [comment] 2017-09-13 07:30
+1

**Comment by humblec** [comment] 2017-11-22 07:05
This should be fixed by https://github.com/kubernetes/kubernetes/pull/55796

**Comment by jingxu97** [comment] 2018-03-10 00:56
Actually  #55796 will avoid printing out the error message "Could not construct volume information ..", but I believe that is not the root cause of the issue here.

**Closed** 2018-05-09 01:29 UTC
Labels: kind/bug, lifecycle/rotten, sig/node

**Comment by miry** [comment] 2018-07-16 09:58
I had the same issue for v1.11. Pod has state Terminating. Container is alive on node in Docker 1.13. Describe shows `Killing container with id docker://containernaem:Need to kill Pod`
