### ISSUE TITLE
Flake: Density [Skipped] [Performance] should allow starting 30 pods per node

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#19711] opened 2016-01-15 18:53 UTC
Failed twice in the last two days.

	
Density [Skipped] [Performance] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:130 There should be no high-latency requests Expected : 1 not to be > : 0

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4024/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4006/

**Comment by Random-Liu** [comment] 2016-01-15 19:30
It seems that the second one is load capacity test. :)

**Comment by mikedanese** [comment] 2016-01-15 21:52
Ooops. Could they be related?

**Comment by Random-Liu** [comment] 2016-01-15 23:10
I've no idea, either. :(

**Comment by mikedanese** [comment] 2016-01-16 01:20
And again two more times:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4025/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4028/
cc @bprashanth @kubernetes/goog-control-plane

**Comment by mikedanese** [comment] 2016-01-16 01:20
#19743 to stop the bleeding

**Comment by gmarek** [comment] 2016-01-16 08:11
@mikedanese - if both of them are failing it's a strong signal for regression. They produce different pattern of loads.

**Comment by gmarek** [comment] 2016-01-22 10:19
It was regression caused by update of goversion to 1.4.3. Fixed by #19847

**Closed by gmarek** 2016-01-22 10:19 UTC
Labels: kind/flake, team/control-plane

**Comment by wojtek-t** [comment] 2016-01-22 12:58
Great debugging BTW.

**Comment by davidopp** [comment] 2016-01-22 20:18
+1 -- thanks for all of your consistent work on fixing test, Marek, even when we are not in a test fixit!
