### ISSUE TITLE
Kubeadm init --config config.yaml issue  ( high avalibulity cluster )

### ISSUE THREAD

**Issue by mannevijayakrishna** [kubernetes/kubernetes#82791] opened 2019-09-17 15:17 UTC

**Comment by mannevijayakrishna** [comment] 2019-09-17 15:18
Can some on help to reslove this below error/issue :: 


kubeadm init --config config.yaml
W0917 10:44:31.802396   10260 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta1", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"
[init] Using Kubernetes version: v1.15.3
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.21:2379/version: dial tcp 192.168.1.21:2379: connect: connection refused
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.22:2379/version: dial tcp 192.168.1.22:2379: connect: no route to host
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.23:2379/version: dial tcp 192.168.1.23:2379: connect: no route to host
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by neolit123** [comment] 2019-09-17 17:16
duplicate of https://github.com/kubernetes/kubernetes/issues/82792

/close

**Closed by neolit123** 2019-09-17 17:16 UTC
Labels: needs-sig, triage/support
