### ISSUE TITLE
should we support mismatched client server?

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#22338] opened 2016-03-02 07:23 UTC
FYI. I meet this problem when answering user question #22273, I am thinking whether we should support mismatched client server communication? Guess we should.

**Comment by tspecht** [comment] 2016-03-02 07:57
Just my (user) input: At least tell the user in a proper way and not throw JSON unmarshalling errors? ;)

**Comment by jlowdermilk** [comment] 2016-03-03 18:41
Client and server of different versions can communicate in any api groups they both support. However from what I understand the `extensions/v1beta1` api is only required to be compatible between releases. It may or may not have breaking changes at an arbitrary HEAD commit. If you're running code from HEAD, the client and server should be the same version.

**Comment by bgrant0607** [comment] 2016-03-03 18:52
Deployment was alpha in 1.1 and was disabled by default. We've made a number of breaking API changes. An old kubectl isn't going to work. We'll document this.

**Comment by bgrant0607** [comment] 2016-03-03 19:00
See also #20587, #5889, and search for other issues mentioning "validation". Don't disagree that it should be made more user-friendly.

**Comment by bgrant0607** [comment] 2016-03-04 00:53
Probably should be documented in the known-issues list: #21000

**Comment by bgrant0607** [comment] 2016-03-11 07:42
Dupe of #21116

**Closed by bgrant0607** 2016-03-11 07:42 UTC
Labels: area/app-config-deployment, kind/documentation, priority/P2, team/ux
