### ISSUE TITLE
kube-dns copies 127.0.0.35 from host's /etc/resolv.conf, doesn't work

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/kubernetes#45828] opened 2017-05-15 16:36 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kube-dns resolv.conf

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.6.3

**Environment**: ubuntu 17.04
- **Cloud provider or hardware configuration**: baremetal i7 pc, 16gb
- **OS** (e.g. from /etc/os-release): ubuntu 17.04

- **Kernel** (e.g. `uname -a`):4.10.0-21-generic
- **Install tools**: kubeadm
- **Others**:

**What happened**:

After installing on baremetal ubuntu 17.04 (my desktop), kube-dns not working

**What you expected to happen**:

dns should work

**How to reproduce it** (as minimally and precisely as possible):

Follow the kubeadm install steps on ubuntu 17.04

**Anything else we need to know**:

As far as I was able to track down (and temporarily solve), my ubuntu desktop has an `/etc/resolv.conf` file that is autogenerated to look like this:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53

```
When kube-dns starts, the dnsmasq container somehow ignores the `--dns` options given to the docker daemon, and instead copies my desktop's `/etc/resolv.conf` file.

Obviously, 127.0.0.35 doesn't work inside the pods.  It should never have been used in the first place.  There's a reason why docker daemon has `--dns` command line options.  These options should be used.  Docker does the right thing, don't override it.

**Comment by jmzwcn** [comment] 2017-05-18 02:14
Could I please take a try? any suggestion?

**Comment by antoineco** [comment] 2017-05-18 23:16
I think you're looking for the kubelet `--cluster-dns` flag. ([kubelet doc](https://kubernetes.io/docs/admin/kubelet/))
The `--dns` flag on the Docker deamon is ignored since #29378 was merged.

**Comment by thockin** [comment] 2017-05-19 05:16
You can pass `--resolv-conf=<path>` to kubelet to read a different resolv.conf file with values you want.

**Closed by thockin** 2017-05-19 05:16 UTC
Labels: area/dns, sig/network

**Comment by gjcarneiro** [comment] 2017-05-19 10:02
Maybe kubeadm needs to be smarter?...  It bothers me that the default install doesn't work.  This should be fixed *somewhere* IMHO...

**Comment by antoineco** [comment] 2017-05-19 12:26
The fact that you're using `systemd-resolved` is a particular case (this would also be true if you'd be using `dnsmasq`), most machines are configured to send DNS lookups to a host which is *not* localhost, so mounting the `resolv.conf` totally makes sense.

Even if `kubeadm` would detect that you're using a local resolver, how would it cope with that? How is it supposed to know which nameserver to use instead? Should it default to 8.8.8.8 and break the resolution of local names? I don't think so.

Note: even when using `kubeadm` you can edit the generated systemd drop-in for `kubelet.service` manually at `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`. See https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by gjcarneiro** [comment] 2017-05-19 13:01
> The fact that you're using systemd-resolved is a particular case

Well, my "particular case" is a standard Ubuntu desktop install.  Yes, I grant you that no person in their right mind would run Network Manager in a Ubuntu Server, but this is Desktop, it is normal.

If you think it's OK for kubeadm to not install correctly by default to a Ubuntu desktop, only server, I accept it, but it's a pity, Kubernetes should try harder be easy to install in a developer box.  And, no, minikube is not a good solution, due to numerous vboxsf filesystem bugs which make host files volume mounting frustrating, also due to the added memory consumption and cpu overhead of virtualbox.

BTW, the workaround I've used was to create a `kube-dns` `ConfigMap` with a `upstreamNameservers` entry.

**Comment by antoineco** [comment] 2017-05-19 13:46
It's not that uncommon I agree, any distribution using `systemd` can potentially default to using the `systemd-resolved` stub DNS resolver (btw this has nothing to do with `NetworkManager`).

Can you check the content of this file on your machine? `/run/systemd/resolve/resolv.conf`
Does it contain any entry?

**Comment by gjcarneiro** [comment] 2017-05-19 13:51
My `/run/systemd/resolve/resolv.conf` contains my actual DNS configurations, the ones I entered via the Network Manager UI (`/usr/bin/nm-connection-editor`):
```
# This file is managed by systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.122.65.250
nameserver 10.122.65.251
nameserver 10.122.65.240
search gambit int.gambit
```
The above configuration, if it were to be copied into kube-dns, should work.

**Comment by antoineco** [comment] 2017-05-19 14:07
So, as mentioned by @thockin, setting `--resolv-conf=/run/systemd/resolve/resolv.conf` should be a decent workaround for now.

How about raising a feature request in the kubeadm repo to default to that file in case `systemd-resolved` is running with `DNSStubListener` and `/etc/resolv.conf` is configured with the local resolver?

**Comment by gjcarneiro** [comment] 2017-05-19 14:44
That seems reasonable.  Created kubernetes/kubeadm#273.  Thanks.

**Comment by andrewrothman** [comment] 2017-12-03 04:08
I just ran into this same issue. As @thockin and @antoineco mentioned, I edited `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`.

I changed this line:
```
Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd
```

to this:

```
Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --resolv-conf=/run/systemd/resolve/resolv.conf
```

Which worked perfectly, and my pods can now access the internet as normal:

```
ping google.com # works now
```

Maybe adding a check to `kubeadm init` that reads the host's `/etc/resolv.conf` and adds this additional arg if the nameserver is set to `127.0.0.53` would solve the problem?

**Comment by mt-inside** [comment] 2018-01-09 13:44
I don't think either of the suggested solutions are correct. Unless I've missed something fundamental, the problem is that kube-dns is using the wrong servers as its upstream. Both kubelet arguments above (`--cluster-dns` and `--resolv-conf`) will affect the resolv.conf that kubelet bind mounts into **every** container. While this will get _external_ resolution working, it will disable in-cluster resolution - Pods won't be able to resolve Services.

It seems to me that the only correct fix is to keep the in-cluster DNS running and configured in Pods, and fix its upstream (manually if you're reading this because you have this issue, and also fix kubeadm to lay down the correct config for kube-dns at install time).

CoreDNS is configured with its upstream address in a Corefile from a configmap - kubeadm copies the host's nameserver here, and that won't work since it's loopback. "Old" SkyDNS-based kube-dns doesn't seem to have any config I can find in the default install; I guess it just looks at its pod's resolv.conf, which again is by default configured as per the host's.

Like I say, sticking 8.8.8.8 in the kubelet argument will make external resolution work, and I think it'll actually enable kube-dns to do external resolution, but none of the other pods will be using it so that's moot.

Note that the upstream should be your local servers (what systemd-resolved is calling); just using 8.8.8.8 will break site-local resolution. For the manual case, rather than looking in the depths of /run, systemd will tell you its stub's backends: `systemd-resolve --status`

**Comment by antoineco** [comment] 2018-01-09 14:01
@mt-inside that's why pointing `kubelet` to `/run/systemd/resolve/resolv.conf` makes sense because in an environment running `systend-resolved`

1. `/etc/resolv.conf` contains only one entry: localhost
2. `/run/systemd/resolve/resolv.conf` contains your actual DNS servers

`kube-dns` merely uses whatever nameservers `kubelet` provides as its forwarders, so if `kubeadm` configures `kubelet` to use *2)* instead of *1)* you're all set.

**Comment by andrewrothman** [comment] 2018-01-09 18:19
I'm sure there are other factors at play that I'm not aware of, but I'd just like to report that my pods are able to communicate out to the internet as well as to other pods in the cluster via DNS hostname (I haven't tried exposed services yet), and I haven't had networking issues since changing my config to the value I mentioned above.

Again, I'm sure there are complexities I'm not aware of. Just wanted to report my own experience and I'd be happy to answer any debugging questions.
