### ISSUE TITLE
Projected serviceAccountToken has mode of mounted file hardcoded to 0600

### ISSUE THREAD

**Issue by devkid** [kubernetes/kubernetes#82573] opened 2019-09-11 09:28 UTC
**What happened**:

Mounting `projected` `serviceAccountTokens` into a container always sets the mode of the mounted token files to `0600`. This is hardcoded in the source code:
https://github.com/kubernetes/kubernetes/blob/cf76868b3430be015cc1e8443a216bf863a9b9f7/pkg/volume/projected/projected.go#L357

**What you expected to happen**:

The file mode should equal the `defaultMode` given in the `projected` map.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with a `projected` `serviceAccountToken` with any `defaultMode` set. Observe that the file mode of the file is always `0600`.

**Environment**:
- Kubernetes version (use `kubectl version`): latest master

**Comment by devkid** [comment] 2019-09-11 10:28
@kubernetes/sig-node-bugs

**Comment by liggitt** [comment] 2019-09-11 12:53
duplicate of https://github.com/kubernetes/kubernetes/issues/74565

/cc @mikedanese 
/close

**Comment by liggitt** [comment] 2019-09-11 13:04
actually, leaving this open to track resolution

/remove-sig node
/sig auth
/assign @mikedanese 
/reopen

**Comment by mikedanese** [comment] 2019-09-18 17:53
This might be a docs issue, or the webhook could work around this by adding supplemental groups. I'm not sure if that's particularly desirable.

cc @micahhausler

**Comment by micahhausler** [comment] 2019-09-18 18:16
Yea, adding supplemental groups from the webhook is probably not the route we want to go, since it's hard to determine which GID is correct. We'll update our docs on that workaround, but having the mode be set by `defaultMode` is the desired behavior

**Comment by mikedanese** [comment] 2019-09-18 19:32
`deafultMode` defaults to world readable. The current behavior was intentional. I would really like if the world bit was never set on these tokens. This is something that I was hoping to fix with the second iteration of tokens. Coincidentally, the security audit pointed this issue out: https://github.com/kubernetes/kubernetes/issues/81116

**Comment by liggitt** [comment] 2019-09-18 19:45
Would you agree that requiring changes to pod specs in order to replace the secret-based token with the projected one by default doesn't seem tenable? If we can't require pod spec changes, and the pod spec doesn't contain enough info to confidently use gid / fsGroup / supplementalGroups, I don't see great options other than preserving the secret-based behavior.

What are the actual risks of injecting a token that is group or world-readable into a pod?

**Comment by mikedanese** [comment] 2019-09-18 19:56
I'd like to pursue the avenue of setting better file ownership of TokenVolumeProjections which would be preferable as it offers better security to users that are running as non-root transparently.

**Comment by willthames** [comment] 2019-10-24 04:36
One point to note here is that setting the `fsGroup` to the gid of the pod is a commonly documented workaround for this issue. However, this gid is typically 0 by default, which doesn't seem ideal - but if you then set the gid of the pod with `RunAsGroup`, this solution no longer works (`fsGroup` seems to be dropped if `RunAsGroup` is set to the same value (presumably as it's no longer a supplemental group) and the token is then only owner-readable again)

**Comment by mikedanese** [comment] 2020-03-11 07:10
Proposal to fix in https://github.com/kubernetes/enhancements/pull/1598

**Comment by mikedanese** [comment] 2020-09-16 18:59
Fixed by @zshihang in https://github.com/kubernetes/kubernetes/pull/89193

**Closed by mikedanese** 2020-09-16 18:59 UTC
Labels: kind/bug, lifecycle/frozen, priority/important-longterm, sig/auth
