### ISSUE TITLE
`kubectl get pods --show-all=false -o name` doesn't work

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#29115] opened 2016-07-18 14:39 UTC
The `--show-all=false` flag is documented as:

```
-a, --show-all=true: When printing, show all resources (false means hide terminated pods.)
```

However, when used together with `--output name`, all pods are listed, terminated pods are **not** omitted.

##### Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.661+d4ae9ca53dc88a-dirty", GitCommit:"d4ae9ca53dc88aa43c7b2fcc2a6aab1105746f0a", GitTreeState:"dirty", BuildDate:"2016-06-23T17:02:00Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.3.0-alpha.3-599-g2746284", GitCommit:"2fe486f", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.5.4", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps To Reproduce
1. Create namespace with terminated and running pods
2. Use `kubectl get pods` with/without `--show-all=false` and `-o name` and compare results.

##### Current Result

Now, the `--show-all` flag works with the default output, but doesn't when the output is set to `name`:

```
$ kubectl get pods --show-all=false
NAME                       READY     STATUS    RESTARTS   AGE
ruby-hello-world-1-sg623   1/1       Running   0          9d
$ kubectl get pods --show-all=false -o name
pod/ruby-hello-world-1-build
pod/ruby-hello-world-1-sg623
```

##### Expected Result

```
$ kubectl get pods --show-all=false
NAME                       READY     STATUS    RESTARTS   AGE
ruby-hello-world-1-sg623   1/1       Running   0          9d
$ kubectl get pods --show-all=false -o name
pod/ruby-hello-world-1-sg623
```

**Comment by rhcarvalho** [comment] 2016-07-18 14:43
@kubernetes/kubectl

**Comment by ncdc** [comment] 2016-07-18 14:44
cc @kubernetes/kubectl @kubernetes/rh-ux

**Comment by rhcarvalho** [comment] 2016-07-18 14:49
BTW, it's the same problem if `--output json`, and perhaps other values too (jsonpath, go-template, etc).

**Comment by AdoHe** [comment] 2016-07-18 15:23
I think I must made some mistake in the original implementation, I will fix this asap. pls assign this to me. @kubernetes/kubectl

**Comment by AdoHe** [comment] 2016-07-19 03:34
I take a look at this, the root cause is that `--show-all` flag is not respected when `--output` is specified. That's because skip not running pod(kind of filter logical) is a client side behavior currently, we are always retrieving the whole pod list. If we want to use `--show-all` with other output format, we need to re-consider this skip behavior, put this filter logical in client side make this hard to do.

**Comment by pwittrock** [comment] 2016-08-15 16:08
@AdoHe filtering in the client side seems reasonable to me

**Comment by deads2k** [comment] 2016-08-15 18:29
@juanvallejo @fabianofranz fyi

**Comment by pwittrock** [comment] 2016-10-17 22:11
@AdoHe Is this something you are working on or should I add it back to the list of items for new contributors?

**Comment by juanvallejo** [comment] 2016-10-18 13:38
Wouldn't this have been fixed by https://github.com/kubernetes/kubernetes/pull/31163?

**Comment by fabianofranz** [comment] 2016-10-18 15:33
Yes, this was fixed by https://github.com/kubernetes/kubernetes/pull/31163. This issue can be closed.

**Closed** 2016-10-18 15:59 UTC
Labels: component/kubectl, contributor-onboarding-assigned, good-for-contributor-onboarding, priority/P2, team/ux
