### ISSUE TITLE
E2e: Services should be able to up and down services

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#13478] opened 2015-09-01 23:34 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7142/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:278
Expected error:
    <*errors.errorString | 0xc20802bf70>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

**Comment by lavalamp** [comment] 2015-09-01 23:34
@quinton-hoole Do you know anything about this?

**Comment by quinton-hoole** [comment] 2015-09-01 23:57
@lavalamp No, sorry, I don't.

**Comment by quinton-hoole** [comment] 2015-09-02 00:01
That test flaked in #13315 also.
It seems to have failed 2 out of the last 30 runs in kubernetes-e2e-gce-parallel.

**Comment by quinton-hoole** [comment] 2015-09-02 00:06
@brendandburns you mentioned in email that this test was 50% flaky.  Where did that number come from?  It looks more like 6% as per above. Are you digging the 50% number out of Jenkins somewhere?

**Comment by lavalamp** [comment] 2015-09-02 01:01
@quinton-hoole Brendan was getting that number from the PR builder.

**Comment by nikhiljindal** [comment] 2015-09-02 02:49
As a data point:
In https://github.com/kubernetes/kubernetes/pull/13419 e2e tests have ran 8 times on the same code.
The tests passed 2 times and failed 6 times.
5 of those failures were due to this issue (service test timing out). 1 failure was due to failure to fetch git repo.

**Comment by quinton-hoole** [comment] 2015-09-02 03:18
In that case the failure rate in kubernetes-e2e-gce-parallel (6%) is very different than in the PR tester (60%+?). Both should run identical tests in identical environments. The only difference, off the top of my head, is the name of the GCE project that they run in.

We should double-check that they're identical setups, and check with GCE SRE whether there are any differences between the two projects. In the past we have seen project-specific funnies related to "migration". 

I can assist the oncall with this in the morning unless we're beaten to it by our European peeps.

**Comment by wojtek-t** [comment] 2015-09-02 06:27
This is partially duplicate of #13032

**Comment by alex-mohr** [comment] 2015-09-02 17:28
See also @brendandburns PR https://github.com/kubernetes/kubernetes/pull/13335 about incorrect assumptions the test appears to make?

**Comment by wojtek-t** [comment] 2015-09-02 17:31
That's a good point - I though it's already merged, but apparently it's not the case.

**Comment by quinton-hoole** [comment] 2015-09-02 21:26
@ixdy @ArtfulCoder FYI.  Looking into this now...

**Comment by quinton-hoole** [comment] 2015-09-02 22:12
@ArtfulCoder FYI.  The number of nodes being used in PR builder e2e (3) is different than the number in  kubernetes-e2e-gce-parallel (6), for no good reason.  I'm pretty sure that explains the difference in flake rates between the two.  I'll send in a PR shortly to fix that.

**Closed** 2015-09-03 19:14 UTC
Labels: priority/P0, team/testing
