### ISSUE TITLE
[Flaky Test] [sig-cli] Kubectl client Simple pod should support inline execution and attach

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#94248] opened 2020-08-26 08:13 UTC
**Which jobs are flaking**:
ci-kubernetes-e2e-ubuntu-gce-containerd

**Which test(s) are flaking**:
[sig-cli] Kubectl client Simple pod should support inline execution and attach 

**Testgrid link**:
https://testgrid.k8s.io/google-gce#gce-ubuntu-master-containerd
**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1297707120006795264

```

[sig-cli] Kubectl client Simple pod should support inline execution and attach expand_less | 1m44s

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:562 Aug 24 

01:40:27.672: Expected     <string>:  
      to contain substring     <string>: stdin closed 

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:586

```
the last echo before container exited is missed, by kubectl. 
 
**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20support%20inline%20execution%20and%20attach

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1297707120006795264
- links to specific failures in spyglass appreciated

**Comment by liggitt** [comment] 2020-08-26 12:15
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/73099, which has a proposed fix in https://github.com/kubernetes/kubernetes/pull/93961

**Comment by liggitt** [comment] 2020-08-26 13:56
closing as duplicate of https://github.com/kubernetes/kubernetes/issues/73099

**Closed by liggitt** 2020-08-26 13:56 UTC
Labels: kind/flake, sig/cli
