### ISSUE TITLE
Broken ci-kubernetes-node-kubelet e2e test

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#42580] opened 2017-03-06 16:23 UTC
It seems that after merging PR #41644 or PR #41753 node kubelet tests start to be broken: [link](https://k8s-testgrid.appspot.com/sq-blocking#node-kubelet&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Projected%5C%20should%5C%20update%5C%20labels%5C%20on%5C%20modification%5C%20%5C%5BConformance%5C%5D%5C%20%5C%5BVolume%5C%5D)
The test is failing in about 8 / 10 cases and is blocking our merge queue.

**Comment by jszczepkowski** [comment] 2017-03-06 16:24
CC @gmarek @yujuhong

**Comment by yujuhong** [comment] 2017-03-06 17:00
This is a duplicate of #42431

**Closed by yujuhong** 2017-03-06 17:00 UTC
Labels: priority/critical-urgent, priority/failing-test, priority/P0
