### ISSUE TITLE
The "kubernetes" endpoint is continuously updated when its subsets[0].addresses has been manually moved to subsets[0].notReadyAddresses

### ISSUE THREAD

**Issue by paveew** [kubernetes/kubernetes#121231] opened 2023-10-14 08:45 UTC
### What happened?

Update "kubernetes" endpoint by moving `subsets[0].addresses` to `subsets[0].notReadyAddresses` and the kube-apiserver keep logging
```
...
Resetting endpoints for master service "kubernetes" to [x.x.x.x]
...
"HTTP" verb="GET" URI="/api/v1/namespaces/default/endpoints/kubernetes"
"HTTP" verb="PUT" URI="/api/v1/namespaces/default/endpoints/kubernetes"
...
// The same log is continuously printed.
```

### What did you expect to happen?

The `ReconcileEndpoints` shows that following steps will be performed under the condition mentioned earlier:

1. Currently the "kubernetes" endpoint struct is (We manually updated it):
```
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```
2. Since currently "kube-apiserver" is healthy in fact (we just manually update the endpoint), the "kubernetes" endpoint struct will first be constructed as: 
```
  subsets:
  - addresses:
    - ip: x.x.x.x
```
3. And then `RepackSubsets` is called so the "kubernetes" endpoint struct will be updated to
```
  // the struct has no changes compared to the current "kubernetes" endpoint struct
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```
4. However, the update request will still be sent and nothing will be updated

In such condition, I think either the "kubernetes" endpoint should be updated by moving `subsets[0].notReadyAddresses` back to `subsets[0].addresses`, or not sending an update request

### How can we reproduce it (as minimally and precisely as possible)?

Update 'kubernetes' endpoint  by moving `subsets[0].Addresses` to `subsets[0].notReadyAddresses`
```
  // before
  subsets:
  - addresses:
    - ip: x.x.x.x
```
```
  // after
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Major:"1", Minor:"27+"
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
N/A
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by aojea** [comment] 2023-10-14 17:19
If you are modifying manually the endpoint you break the reconciler, why do need to do that?

Related to this topic, there is a proposal to make this configurable based on the apiserver healthz

https://github.com/kubernetes/kubernetes/pull/121105#discussion_r1357849080

**Comment by paveew** [comment] 2023-10-15 02:46
> If you are modifying manually the endpoint you break the reconciler, why do need to do that?

When apiserver is overloaded due to some unexpected requests, it may restart repeatedly due to OOM. In this case, the pods that send the unexpected requests cannot be deleted through apiserver. Manually removing the endpoint gives apisever a breather, and then the pods' deletion could be done.

**Comment by aojea** [comment] 2023-10-15 09:10
/assign

Manually modifying endpoints is not supported but I don't understand why the endpoints are not reconciled correctly ...

**Comment by aojea** [comment] 2023-10-18 19:45
@paveew the problem is that the reconcile logic does not detect a format error and then during the repackSubsets this is the expected result

https://github.com/kubernetes/kubernetes/blob/ea5e4bc2326c71250774f6a4f5545492c5621760/pkg/api/v1/endpoints/util_test.go#L206-L221

so, the Endpoint is never reconciled to the expected estate, once we fix that, as soon as you change the address the apiserver will reconcile it to the proper estate, if you want to change the Endpoints manually you have to use the option `none` on the following flag, so you can handle the Endpoints manually

```
--endpoint-reconciler-type string     Default: "lease"
Use an endpoint reconciler (master-count, lease, none) master-count is deprecated, and will be removed in a future version.
```
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by paveew** [comment] 2023-10-24 15:01
> --endpoint-reconciler-type string     Default: "lease"
Use an endpoint reconciler (master-count, lease, none) master-count is deprecated, and will be removed in a future version.

got it

**Comment by thockin** [comment] 2023-10-26 17:03
Discussed on sig-net:

Given that you can have 2 slices with different conditions for the same IP-port, we need to document what to do if a consumer sees this.

DECISION NEEDED: Should we be optimisitic (@robscott says kube-proxy does this) or pessimistic (@khenidak makes a case for this).  I personally agree with Kal - fail closed - but want to see if there's dissent?

Once we document that, is it really worth doing the work to try to validate this within a slice or within an Endpoints?  It's a breaking change, so not trivial and (IMO) low RoI

**Comment by danwinship** [comment] 2023-10-26 17:04
> if you want to change the Endpoints manually you have to use the option none on the following flag, so you can handle the Endpoints manually

Yeah, the code even documents the fact that it doesn't support other people modifying the `kubernetes` Endpoints: https://github.com/kubernetes/kubernetes/blob/v1.28.3/pkg/controlplane/reconcilers/reconcilers.go#L29C5-L30C40

(So I think the specific bug reported here is NOTABUG, though we still have to solve the simultaneously-ready-and-not-ready problem.)

**Comment by robscott** [comment] 2023-10-26 17:21
Some thoughts:

**EndpointSlice Controller**
The case where this can happen is if there is an EndpointSlice that has all endpoints within it being either updated or removed. In that case, those updates may be redistributed to other EndpointSlices with capacity, and that will translate into the following:

1. Update operation(s) to redistribute endpoints
2. Delete operation(s) to delete EndpointSlice(s) that are no longer required

The concern is the time between 1 and 2

**EndpointSlice Clients**
Of course regardless of that state, clients of EndpointSlice API need to handle duplicates because the API allows this, and Kubernetes does not have a reliable way to provide cross-resource validation.

**Endpoints**
Roughly the same thing is possible with the Endpoints API as documented by this bug.

**My recommendation**
We're stuck with this problem on EndpointSlices. We could add validation to prevent this within a single EndpointSlice, but that seems to have limited value since EndpointSlices are designed to be merged together for a Service. Although I'm open to a fix for the Endpoints API, it would technically be backwards incompatible.

It may be simplest just to provide some standard guidance on how to handle this case. I tend to lean towards optimism here because I think the most critical problem here could be when the only endpoint(s) left have conflicting readiness information. In that case, I'd rather route to an endpoint of unknown readiness than route to nowhere. I don't really think it's worth special casing this and would rather just apply an optimistic approach for Endpoints and EndpointSlice clients, but open to alternatives.

**Comment by thockin** [comment] 2023-10-26 17:32
> I'd rather route to an endpoint of unknown readiness than route to nowhere

I don't think that's the common case, though.  I think it's more likely that I have N ready and 1 (or small N) that is both ready and unready (dupplicates).  In that case, optimism means we include an endpoint in a set which doesn't need it, and risk errors.

We already will choose terminating endpoints when no other endpoints exist.  We chose at that time to NOT fall back on unready endpoints when no ready endpoints exist.  If we want to revisit that, we can, but I don't think it's specific to this case.

So if we made the change to pessimistic mode, what would break?

1) Services which *only* have duplicate-and-conflicting endpoints (e.g. single endpoint)
2) ... ?

**Comment by robscott** [comment] 2023-10-26 17:39
Good points @thockin, I think you and @khenidak have convinced me that pessimism for readiness is probably the right solution. In either case, we'll need to change kube-proxy's logic. It is currently optimistic but in a different way, it takes the first local endpoint it finds and runs with that:

https://github.com/kubernetes/kubernetes/blob/4d45fe55e6115ee7368ab57d2d8e67861c6bd08c/pkg/proxy/endpointslicecache.go#L302-L308

Some options:

1. Merge endpoint information to effectively get max(isLocal) and min(isReady)
2. Give precedence to local endpoints, followed by unready endpoints
3. Give precedence to unready endpoints, followed by local endpoints

I tend to think option 2 is the least confusing path, but open to alternatives.

**Closed** 2024-09-29 19:56 UTC
Labels: kind/bug, sig/network, lifecycle/rotten, needs-triage
