### ISSUE TITLE
cluster up failing ~50 jobs per hour

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44243] opened 2017-04-08 19:04 UTC
105935 - 70 builds/hr, 70 tests/hr - A bunch of GKE jobs fail to start clusters (summary). Started 4/1, spiked tuesday 4/4. Declined Wednesday and Thursday but still high.

/assign @lukemarsden @roberthbailey @jlowdermilk @mikedanese 

https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-reboot-1.6
https://storage.googleapis.com/k8s-gubernator/triage/index.html#ea6679417165f10786e6

```
W0408 10:16:56.440] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0408 10:16:56.440]  name: u'operation-1491670786127-f1ac6a61'
W0408 10:16:56.440]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0408 10:16:56.440]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/220967818552/zones/us-central1-a/operations/operation-1491670786127-f1ac6a61'
W0408 10:16:56.440]  status: StatusValueValuesEnum(DONE, 3)
W0408 10:16:56.440]  statusMessage: u'All cluster resources were brought up, but the cluster API is reporting 3 nodes out of 3 are unhealthy.'
W0408 10:16:56.441]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/220967818552/zones/us-central1-a/clusters/bootstrap-e2e'
W0408 10:16:56.441]  zone: u'us-central1-a'>] finished with error: All cluster resources were brought up, but the cluster API is reporting 3 nodes out of 3 are unhealthy.
```

**Comment by roberthbailey** [comment] 2017-04-10 07:30
@krousey found through manual testing that the GKE test environment broke for more than a day last week before anyone noticed (now that it isn't part of the submit queue and we don't have any automated alerting). I believe this was fixed before the end of last week, so I'm going to mark as such. Please reopen if you still see a high failure rate. 

(as an aside, if the failing tests are GKE-only, it doesn't do much good to assign the issue to @lukemarsden since there's nothing he can do to fix it).

**Comment by fejta** [comment] 2017-04-10 16:50
See original descriptio, especially the links. Kris likely caused the decline on Wednesday and/or Thursday. They remain high.

**Comment by mikedanese** [comment] 2017-04-10 18:25
This is fixed by the cherry picks linked in https://github.com/kubernetes/kubernetes/issues/44285

**Comment by fejta** [comment] 2017-04-12 21:01
This is triage cluster remains the source of 20 failures per hour (top source of problems):

Cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#d1ea23f2ffd4d4ffbf7d

Example jobs:
* `gke-gci-ci-master`: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-ci-master/4184
* `gci-gke-pre-release`: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-pre-release/1649

**Comment by fejta** [comment] 2017-04-14 20:44
Cluster is now https://storage.googleapis.com/k8s-gubernator/triage/index.html#10593569f958de2147a5

**Comment by mikedanese** [comment] 2017-04-19 20:32
Two should be fixed. The two prerelease test will continue to fail until 1.7.0-alpha.2.

**Comment by fejta** [comment] 2017-04-25 23:55
/unassign @mikedanese 
/assign @lukemarsden 

This is a top source of failure this week, failing 72 builds per hour
https://storage.googleapis.com/k8s-gubernator/triage/index.html#10593569f958de2147a5

**Comment by roberthbailey** [comment] 2017-04-27 05:08
The root cause of the failures is a GCP issue with our projects, so @lukemarsden isn't going to be able to do much to fix it. I've re-assigned to @fejta to track our fix since I won't have time to follow up on it for the next few days.

**Comment by fejta** [comment] 2017-04-27 23:51
Thanks for the investigation!

/unassign
/assign @mikedanese 

Chatted with Mike earlier today. He will follow up on the GCP problem so I can track down the rest of the top failures for this week.

**Closed** 2017-05-08 18:25 UTC
Labels: area/platform/gke, kind/flake, priority/failing-test, sig/cluster-lifecycle, team/gke
