### ISSUE TITLE
e2e failure: Restart [Disruptive] should restart all nodes and ensure all nodes and pods recover

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20507] opened 2016-02-02 18:49 UTC
The node restart test has been failing consistently past few runs: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/

From test logs it looks like kube-system pods are not being rescheduled within 2m after the nodes come back. #19889 is a possible culprit; test was passing before that got merged.

Sample failure (from [kubernetes-e2e-gce-serial/368](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/368/) [gcs](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/368)

```
09:20:13 Feb  2 09:20:13.210: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m44.693791979s elapsed)
09:20:15 Feb  2 09:20:15.215: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m46.69873923s elapsed)
09:20:17 Feb  2 09:20:17.220: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m48.703549212s elapsed)
09:20:19 Feb  2 09:20:19.225: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m50.708551772s elapsed)
09:20:21 Feb  2 09:20:21.230: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m52.713505396s elapsed)
09:20:23 Feb  2 09:20:23.235: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m54.718077785s elapsed)
09:20:25 Feb  2 09:20:25.239: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m56.722986874s elapsed)
09:20:27 Feb  2 09:20:27.244: INFO: Waiting for pod heapster-v13-estsb in namespace 'kube-system' status to be 'running and ready'(found phase: "Running", readiness: false) (1m58.727483325s elapsed)
09:20:29 Feb  2 09:20:29.270: INFO: Pod monitoring-influxdb-grafana-v3-3h8dv failed to be running and ready.
09:20:29 Feb  2 09:20:29.270: INFO: Wanted all 15 pods to be running and ready. Result: false. Pods: [l7-lb-controller-du0fu elasticsearch-logging-v1-dzxhq fluentd-elasticsearch-e2e-serial-minion-eyee kube-dns-v10-d30c0 kube-ui-v5-wiit2 kube-proxy-e2e-serial-minion-eyee kibana-logging-v1-oqa94 heapster-v13-estsb fluentd-elasticsearch-e2e-serial-minion-d49u kibana-logging-v1-l72a1 kube-proxy-e2e-serial-minion-wpbj kube-proxy-e2e-serial-minion-d49u elasticsearch-logging-v1-4lzcy fluentd-elasticsearch-e2e-serial-minion-wpbj monitoring-influxdb-grafana-v3-3h8dv]
09:20:29 [AfterEach] Restart [Disruptive]
09:20:29   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/restart.go:76
09:20:29 
09:20:29 • Failure [123.205 seconds]
```

**Comment by yujuhong** [comment] 2016-02-02 18:56
Heapster was crashing. It should have nothing to do with PR #19889 

/cc @dchen1107 @vishh @piosz @mwielgus 

Related: #20100 

Reassigning to @piosz  to triage.

**Comment by yujuhong** [comment] 2016-02-02 19:13
Perhaps unrelated, but this is what I observed in my cluster (built yesterday with 6f94afb68dd8312b28d0b868ab4ef81d8115a4a0):

influxdb was crashing and heapster crashed too (expected), but heapster panic due to a nil pointer dereference (unexpected)
```
E0202 18:20:30.002756       1 influxdb.go:117] Failed to create infuxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x50d441]

goroutine 27 [running]:
k8s.io/heapster/events/sinks/influxdb.(*influxdbSink).sendData(0xc82011b180, 0xc820235c00, 0x6, 0xa)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sinks/influxdb/influxdb.go:126 +0x221
k8s.io/heapster/events/sinks/influxdb.(*influxdbSink).ExportEvents(0xc82011b180, 0xc8203c2630)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sinks/influxdb/influxdb.go:111 +0x379
k8s.io/heapster/events/sinks.NewEventSinkManager.func1(0x7fea90a2d728, 0xc82011b180, 0xc8200fb860, 0xc8200fb8c0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sinks/manager.go:59 +0xe3
created by k8s.io/heapster/events/sinks.NewEventSinkManager
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sinks/manager.go:68 +0x238

goroutine 1 [chan receive]:
main.main()
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/eventer.go:88 +0xc44

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1843c80)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 8 [select]:
k8s.io/heapster/events/sources/kubernetes.(*KubernetesEventSource).watch(0xc820232660)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sources/kubernetes/kubernetes_source.go:101 +0x116e
created by k8s.io/heapster/events/sources/kubernetes.NewKubernetesSource
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/sources/kubernetes/kubernetes_source.go:160 +0x2cf

goroutine 22 [syscall]:
os/signal.loop()
	/usr/lib/google-golang/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/google-golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 33 [IO wait]:
net.runtime_pollWait(0x7fea90a2d500, 0x72, 0xc820014120)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820196220, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820196220, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201961c0, 0xc820251800, 0x800, 0x800, 0x0, 0x7fea90a6b050, 0xc820014120)
	/usr/lib/google-golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201000f0, 0xc820251800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820190c30, 0x7fea90a2d5c0, 0xc8201000f0, 0x5, 0x0, 0x0)
	/usr/lib/google-golang/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82017cdc0, 0x1446317, 0x0, 0x0)
	/usr/lib/google-golang/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82017cdc0, 0xc820348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fea90a79498, 0xc82017cdc0, 0xc82015c528, 0xc820348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82033e980, 0xc820348000, 0x1000, 0x1000, 0xc8203b3400, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82031aa20)
	/usr/lib/google-golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82031aa20, 0xc8203adf0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc82031aa20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc820233ad0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820233ad0, 0xc8203bc001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc82024ea40, 0xc8203bc001, 0x5ff, 0x5ff, 0xc800000000, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc82024ea40, 0xc8203bc001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc82024ea80, 0xc8203bc001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc820057a00, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820057a00, 0x1, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc820057a00, 0xe0ece0, 0xc820397e90, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820233b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820233b30)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:92 +0xf0
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:59 +0xbf

goroutine 15 [select]:
net/http.(*persistConn).readLoop(0xc82015c4d0)
	/usr/lib/google-golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:685 +0xc78

goroutine 16 [select]:
net/http.(*persistConn).writeLoop(0xc82015c4d0)
	/usr/lib/google-golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:686 +0xc9d

goroutine 28 [select]:
k8s.io/heapster/events/manager.(*realManager).Housekeep(0xc820190d20)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/manager/manager.go:64 +0x29f
created by k8s.io/heapster/events/manager.(*realManager).Start
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/events/manager/manager.go:49 +0x35
```

**Comment by dchen1107** [comment] 2016-02-02 19:50
Ok, heapster is running with new version v13 again from the log, and this is 4th times upgraded heapster run into crashloop.

**Comment by piosz** [comment] 2016-02-02 20:20
Reassigning to @mwielgus who implemented this particular part. We will investigate failures tomorrow.

We bumped the version of Heapster yesterday and we work hard on stabilizing it. Apologies for the problems.

**Comment by dchen1107** [comment] 2016-02-02 20:23
@piosz & @mwielgus FYI. the problem is very easy to trigger by reboot.

**Comment by piosz** [comment] 2016-02-12 08:56
After our recent changes and bumping Heapster to the new version #20650 the Heapster is no longer the problem. There are still some issues with influxdb. Closing in favor of #20247/

cc @fgrzadkowski

**Closed by piosz** 2016-02-12 08:56 UTC
Labels: priority/P0, team/cluster
