### ISSUE TITLE
Scheduler assigns pods to nodes with insufficient resources

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#10928] opened 2015-07-08 15:55 UTC
When the node clearly didn't have enough resources, scheduler still binds the pod to the node. The pod was eventually rejected by kubelet due to `CapacityExceeded`.
This might be working as intended, but is there any reason not to reject the pod upfront when scheduling?

```
I0708 00:50:09.864828      10 factory.go:214] About to try and schedule pod monitoring-heapster-v5-ss0e0
I0708 00:50:09.865049      10 priorities.go:38] Combined requested resources 1400 from existing pods exceeds capacity 1000 on node e2e-test-yjhong-minion-fsgq
I0708 00:50:09.865187      10 factory.go:312] Attempting to bind monitoring-heapster-v5-ss0e0 to e2e-test-yjhong-minion-fsgq
I0708 00:50:09.896511      10 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"monitoring-heapster-v5-ss0e0", UID:"48a602f3-250b-11e5-a4f0-42010af00ca3", APIVersion:"v1", ResourceVersion:"1122", FieldPath:""}): reason: 'scheduled' Successfully assigned monitoring-heapster-v5-ss0e0 to e2e-test-yjhong-minion-fsgq
```

/cc @davidopp

**Comment by davidopp** [comment] 2015-07-08 16:52
I wonder if this has the same root cause as #10899

**Comment by davidopp** [comment] 2015-07-08 17:03
@yujuhong Do you have any additional information on how to reproduce this?

**Comment by bprashanth** [comment] 2015-07-08 17:06
In theory it shouldn't even hit the priority functions if the pod can't fit on any node. If it does, it will get assigned to a random node. The function that the kubelet uses to reject pods is the same one the scheduler uses, so I suspect the pods given to it are different on either side (the scheduler side vs the kubelet side), which might be because of the mirror pod race in #10899.  

Can you verify that pods do get rejected under normal conditions with PodFitsResource?

**Comment by yujuhong** [comment] 2015-07-08 17:13
I suspected race condition due to the one mirror pod (fluentd) too. If that was true, the creation of mirror pod were severely deleted because RC created, and kubelet rejected 14 heapster pods in between.

```
e2e-tests-cluster-upgrade-htw3k   webserver-td92r                                     1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
e2e-tests-cluster-upgrade-htw3k   webserver-yibi1                                     1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       elasticsearch-logging-v1-v1snh                      1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       elasticsearch-logging-v1-z14fd                      1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       fluentd-elasticsearch-e2e-test-yjhong-minion-fsgq   1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       fluentd-elasticsearch-e2e-test-yjhong-minion-vnsm   1/1       Running            0          16h       e2e-test-yjhong-minion-vnsm
kube-system                       kibana-logging-v1-r3hc0                             1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       kube-dns-v5-2uwyu                                   3/3       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       kube-ui-v1-manll                                    1/1       Running            0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-1c78i                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-4qtty                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-csciq                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-fxijp                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-k7kl7                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-lypyb                        1/1       Running            2          16h       e2e-test-yjhong-minion-vnsm
kube-system                       monitoring-heapster-v5-ndjb5                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-nmvzn                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-omx9i                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-q7n8z                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-q9tpk                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-ss0e0                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-ua5qd                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-wmvvm                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-heapster-v5-xc9dw                        0/1       CapacityExceeded   0          16h       e2e-test-yjhong-minion-fsgq
kube-system                       monitoring-influx-grafana-v1-asptn                  2/2       Running            0          16h       e2e-test-yjhong-minion-fsgq
```
Among the pods, only `webserver-xxx` pods don't have resource limits specified as they are in a namespace that e2e upgrade test created (which didn't get cleaned up correctly...).
Note that the majority of the pods were assigned to the same node `e2e-test-yjhong-minion-fsgq`. I suspect that this was because one node (in the cluster upgrade test) became ready first.

I will try reproduce this scenario.

**Comment by bprashanth** [comment] 2015-07-08 17:16
also https://github.com/GoogleCloudPlatform/kubernetes/issues/10397

**Comment by yujuhong** [comment] 2015-07-08 22:16
I updated https://github.com/GoogleCloudPlatform/kubernetes/issues/10397#issuecomment-119746287.

In summary, I think this is a corner case where only one node was available AND mirror pod creation was slow. This should not happen often, but it seems that our cluster upgrade test is capable of triggering many bugs and corner cases.

This could just be a clarity issue because the scheduler log looked misleading even though scheduler functioned correctly.

**Comment by a-robinson** [comment] 2015-08-23 20:03
I reproduced this while playing around on #13048. All it took was creating a cluster at 1.0.3 on a single f1-micro. It also ran into #10397, hence the very long list of capacity exceeded pods from the heapster rc.

```
$ kubectl get pods --namespace=kube-system
NAME                                                 READY     STATUS             RESTARTS   AGE
fluentd-cloud-logging-gke-micro-6bfcaaa4-node-vckq   1/1       Running            0          16h
kube-dns-v8-rf09y                                    4/4       Running            0          16h
kube-ui-v1-r4bll                                     1/1       Running            0          16h
monitoring-heapster-v6-0181q                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-08le2                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-0nlye                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-19aie                         0/1       Pending            0          16h
monitoring-heapster-v6-1em5c                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-1fvcg                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-1rt7w                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-1xw9u                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-29mx2                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-2crvf                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-2kvf4                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-2x2ei                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-2xefq                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-2yzm8                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-3n9j9                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-3ovlj                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-4ct4u                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-5fsds                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-5upfz                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-6ak3h                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-6i7bk                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-6qmnd                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-7o83s                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-8do8o                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-8enyp                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-8guv6                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-951i9                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-9pm2a                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-9qgqe                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-a6dc7                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-asxfl                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-axd17                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-b51gg                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-bfg0f                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-bgq3y                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-bing2                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-bis4k                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-c3rko                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-c4bbp                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-c7x7d                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-ce55l                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-cmgg0                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-d08em                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-d0zdd                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-d5fb2                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-dfrrg                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-du83b                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-enkn5                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-f2ewg                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-f7n81                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-fjj3i                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-fohxf                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-g8ryn                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-gr7us                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-h92lf                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-hhp9w                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-hxkfu                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-irayt                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-ki0ue                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-kkacs                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-mgaes                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-mosat                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-mqu7u                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-n2uhq                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-ni286                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-pr8d8                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-pzvih                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-qupwl                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-r8l1c                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-s5ots                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-slztd                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-t3gsy                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-t7231                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-ucpau                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-ue9l0                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-vaiwt                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-w06y8                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-w7p5u                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-w9cqg                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-wba2c                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-wd486                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-wo5jq                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-woy5h                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-xkgbv                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-xvgby                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-z4vwn                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-znnq9                         0/1       CapacityExceeded   0          16h
monitoring-heapster-v6-zwzi5                         0/1       CapacityExceeded   0          16h
```

**Comment by timothysc** [comment] 2016-12-09 18:37
closing this issue, due to last report was > year ago.  If you think the issue still exists, please reopen.

**Closed by timothysc** 2016-12-09 18:37 UTC
Labels: priority/backlog, sig/scheduling, team/control-plane (deprecated - do not use)
