### ISSUE TITLE
e2e density test panicked

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#7464] opened 2015-04-28 22:55 UTC
I ran density test on a freshly built cluster and it panicked.

```
INFO: Pod States: 14 running, 6 pending, 0 waiting, 0 unknown 
INFO: Pod States: 0 running, 20 pending, 0 waiting, 0 unknown 
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 114 [running]:
github.com/onsi/ginkgo.Fail(0xc2081001e0, 0x1c6, 0xc2089535b0, 0x1, 0x1)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/ginkgo_dsl.go:229 +0xed
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc208ae4200, 0x7f349190c438, 0x1114220, 0x0, 0x0, 0x0, 0x0, 0x1114220)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x323
github.com/onsi/gomega/internal/assertion.(*Assertion).NotTo(0xc208ae4200, 0x7f349190c438, 0x1114220, 0x0, 0x0, 0x0, 0x7f349190c3f0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/onsi/gomega/internal/assertion/assertion.go:43 +0x95
github.com/GoogleCloudPlatform/kubernetes/test/e2e.expectNoError(0x7f34918e0b40, 0xc208953350, 0x0, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:223 +0x121
github.com/GoogleCloudPlatform/kubernetes/test/e2e.func·035()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:197 +0x19b
created by github.com/GoogleCloudPlatform/kubernetes/test/e2e.func·036
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:203 +0x1d3
<skip more stack trace>
```

If I read the log correctly, the test asserted in a goroutine, causing the panic.
Where this could have occurred: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/density.go#L201

**Comment by bprashanth** [comment] 2015-04-28 22:59
i suspect that test is running far more than we expect to work on too few nodes (can't tell without seeing how many rcs were created etc)

**Comment by yujuhong** [comment] 2015-04-28 23:02
I would be okay if the test simply failed, but I didn't expect to see it panic.

**Comment by bprashanth** [comment] 2015-04-28 23:04
yeah it stacktraces when an error is returned, which is confusing (by design i think, in the ExpectNoError function or whatever). We should log the error itself, if nothing else.

**Comment by yujuhong** [comment] 2015-04-28 23:09
The design is flawed then...There were >300 lines of stack trace without a message telling me what the failure was.

**Comment by bprashanth** [comment] 2015-04-28 23:10
Logging it should be as easy as Logf on err != nil, unsure why it wasn't done till now

**Comment by ixdy** [comment] 2016-02-04 00:10
Closing as obsolete.

**Closed by ixdy** 2016-02-04 00:10 UTC
Labels: area/test, priority/P2, team/test-infra
