### ISSUE TITLE
Kubelet blows away manual changes to mirror pods

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#12380] opened 2015-08-07 04:56 UTC
I found my fluentd pods (mirror pods) that were created by kubelet.  I made a manual change to one of them (changed the image).  I updated the pod successfully.  Kubelet immediately destroyed my changes.

As per conversation with @dchen1107, we should probably respect the changes made through the apiserver or else maybe block them?  Proposal was to save the hash of the file into an annotation.  Upon reading a mirror pod in apiserver that does not match the disk, check the hash - if it matches, assume the user changed it in the API.  If it doesn't match, blow it away and use the file.  Something like that...

**Comment by roberthbailey** [comment] 2015-08-07 06:15
My preference would be to just block changes to mirror pods. The kubelet isn't going to rewrite the manifest file on the node (or from the manifest URL) and it seems like that is the canonical source for the pod. If you want to have mutable pod definitions, you should create them through the apiserver in the first place. For the fluentd pods, we should move them out of the manifest and into a daemon controller (once the daemon controller supports updates).

**Comment by yujuhong** [comment] 2015-08-07 18:55
I agree with @roberthbailey. Allowing changes to mirror pods through the apiserver can certainly become a source of confusion. For example, if user made different changes to the manifest file and the pod through apiserver, kubelet would be left to resolve the conflicts, which should really be apiserver's job. It'd also be hard for user to debug which pod is running on the node given that apiserver always accepts the update to the pod. In addition, there may be potential "regression" of pods when kubelet restarts, in which case it will likely to start the pod based on the manifest file before getting updates from the apiserver. 

IMO, there should be one source of truth for a single pod. Given that we need to support standalone kubelets (when there is no apiserver or apiserver is temporarily unavailable), kubelet should respect the manifest files. Daemon controller seems more suitable for other use cases.
(FWIW, initially we wanted to make mirror pods read-only, or at least make it clear at the api level that it's a mirror pod, but the proposal was rejected).

**Comment by yujuhong** [comment] 2015-09-18 00:16
Lowering the priority since the future of static/mirror pod is unclear (may be deprecated) for use cases beyond non-master components.

**Comment by yujuhong** [comment] 2016-02-12 01:51
Let's close this one and discuss how to proceed in #16627

**Closed by yujuhong** 2016-02-12 01:51 UTC
Labels: kind/bug, priority/P2, team/node, team/ux
