### ISSUE TITLE
REST api - namespace entity contains namespace attribute as part of the metadata

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#5286] opened 2015-03-11 13:31 UTC
Namespace entity, as other entities, contains ObjectMeta (metadata), which contains in turn also a namespace property, which is :
a. duplication of information
b. can be updated to a completely different value than the namespace it's in.

so imho this is a bug and can cause inconsistency and confusion.

**Comment by abonas** [comment] 2015-03-11 13:32
cc @mfojtik

**Comment by derekwaynecarr** [comment] 2015-03-19 19:03
It should be prevented setting Namespace.Namespace here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L206

Were you able to set it on create or update?

**Comment by abonas** [comment] 2015-03-20 16:09
I just rechecked on latest master.
I was able to create it using the following input, got 201 CREATED back, but it looks as the namespace property was omitted.

{
    "kind": "Namespace",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "staging",
       "namespace":"some"
    },

}

**Comment by derekwaynecarr** [comment] 2015-03-20 16:26
did you do this via curl or kubectl?

----- Original Message -----

**Comment by abonas** [comment] 2015-03-20 16:32
> did you do this via curl or kubectl?

REST client (http)

**Comment by bgrant0607** [comment] 2016-07-12 21:41
Closing as dupe of #13579

**Closed by bgrant0607** 2016-07-12 21:41 UTC
Labels: area/swagger, priority/P2, team/CSI-API Machinery SIG
