### ISSUE TITLE
validation improperly rejects env variable names with dots

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#30120] opened 2016-08-05 03:58 UTC
pod spec validation rejects env variable keys that contain dots (eg "FOO.BAR"), but "FOO.BAR" is a valid env variable name for some (though not all) shell environments, so this validation rule is overly strict.

@smarterclayton

**Comment by smarterclayton** [comment] 2016-08-05 14:10
Posix allows dot env vars, but bash won't let you use them.  Since your container interface is much more towards the underlying POSIX I think it's reasonable to relax and allow dot for env var names.

**Comment by webwurst** [comment] 2017-03-15 13:04
There is now a Docker/Docker-Compose example for Elasticsearch using environment variables with dots: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

And you are sent to that example from the Docker Hub since the image there will be deprecated:
https://hub.docker.com/_/elasticsearch/

So maybe some more people will stumble upon this issue.

**Comment by saidimu** [comment] 2017-03-15 18:38
@webwurst Just stumbled on this very issue with Elasticsearch :(

**Comment by smarterclayton** [comment] 2017-03-17 04:27
We can consider this for 1.7

**Comment by smarterclayton** [comment] 2017-03-17 04:27
@kubernetes/sig-apps-features

**Comment by jarpy** [comment] 2017-05-02 05:26
Thank you for picking this up again. It would be hugely beneficial to the Elasticsearch, Kibana and Logstash images.

**Comment by timoreimann** [comment] 2017-07-16 23:15
Duplicate of the much older #2707.

**Closed** 2017-07-16 23:24 UTC
Labels: area/kubectl, sig/api-machinery, sig/apps
