### ISSUE TITLE
Kubespray not working with loadbalancer type and external IP on Ingress Conroller on IPVS

### ISSUE THREAD

**Issue by dev999k8** [kubernetes/kubernetes#100782] opened 2021-04-02 14:50 UTC
Cluster information:
Kubernetes version: 1.19
Cloud being used: Bare Metal
Installation method: Kubespray
Host OS: Centos7, Centos8, Ubuntu 20.04
CNI and version: Kube-router 1.2
CRI and version: docker 19.03

Machines: 2

I’ve checked out latest master of Kubespray (27/03/20201) and configured for 1 control pane only in hosts file. Thereafter, I modified k8s-cluster config to install “kube-router” and use “ipvs”.

After completion of kubespray provisioning - I run “kubectl get nodes” and the control pane and worker node are in ready state and working with no errors. Also checked “journalctl -xe” and there were no errors.

If I do curl “masterip:6443” on both the control pane and worker node I get

Client sent an HTTP request to an HTTPS server.

So far so good and beautfilly connected and working.

However, the BIG issue arises…

Now I deploy an ingress controller NGINX - tried via both helm and also kubectl method…but before I deploy it, I put a watch on worker node of the curl command and then deployed it.

curl “masterip:6443”

I get for a few seconds

Client sent an HTTP request to an HTTPS server.

As it deploys suddenly get the following on worker node:

curl: (7) Failed connect to masterip:6443; Connection refused

And now if I do kubectl get nodes I see worker node in “notready” state. So I do “journalctl -xe” and I see lines full of

10s": dial tcp masterip:6443: connect: connection refused

To be noted:

If I go back to the control pane and other machines in the same network run the curl I get:
curl “masterip:6443”

Client sent an HTTP request to an HTTPS server.

Which says it’s reachable on 6443, but inside worker node suddenly is no longer reachable.

Why was worker node able to reach, then suddenly it’s not reaching? What is doing this and how to fix?

Working on iptables mode (not ipvs) - works completely fine.
This same behaviour occurs on Centos7 and Centos8.
I’ve run kube-proxy cleanup and still occurs
I’ve run iptables -F for a test purpose - this I can’t curl inside worker node port 6443 of masterip, but I can access from any other machines.
If I run on worker node “ipvsadm -ln”
→ masterip:6443 Masq 1 0 2
I see in the InActConn column 2 - why?

I’ve tested using other CNI e.g. flannel also occurs.

Summary: Cluster provisioning works until as soon as ingress controller is deployed e.g. nginx, the worker node stops being able to access masterip:6443 - prior to deployment it can access.

Please let me know for further information and how to resolve.

**Comment by dev999k8** [comment] 2021-04-02 14:50
Want to add to above - I setup 2 fresh 20.04.2 LTS boxes (1 single control pane and 1 worker node) and did the same thing above and got same result - as soon as I deploy nginx ingress controller, the worker node stops being able to connect to port 6443 on master…really baffled.

To be noted - I’m using the master (control pane) external ip to host as ingress controller - could this be causing it? Are masters no longer able to host nginx ingress controller on port 80 / 443 as well as be master control pane? (I have working on 1.18 on centos8 - but from 1.19 no longer works if that is correct assumption of issue here).

**Comment by BenTheElder** [comment] 2021-04-02 18:52
Is there any reason to expect this is a kubernetes issue and not a kubespray issue? This repo has a lot of issues and contributors have significantly less bandwidth for responding to issues related every distro versus the code developed here.

This sounds like a configuration / usage issue with kubespray and your ingress, not a kubernetes bug.

https://github.com/kubernetes-sigs/kubespray

**Comment by dev999k8** [comment] 2021-04-02 18:57
@BenTheElder I'm getting this also non-kubespray method - on centos + ubuntu.

1.18 works perfectly, but not 1.19+ - so I need to urgent sooner or later.

Is there someone can try my reproducing my steps / setup on there end?

**Comment by BenTheElder** [comment] 2021-04-03 17:36
Someone else from SIG Network can hopefully comment re: IPVS doesn't work. I don't use centos or kubespray or IPVS. I recommend using the iptables backend which is better tested + supported IMHO.

**Comment by uablrek** [comment] 2021-04-04 06:23
> I modified k8s-cluster config to install “kube-router” and use “ipvs”.

How do you install `kube-router`? What functions of kube-router are enabled?

More ot the point, is `kube-router` replacing `kube-proxy`?

**Comment by dev999k8** [comment] 2021-04-04 12:18
Kube-router installation via kubespray. Also tried manually via there techdocs.

Using router, firewall and service proxy.

**Comment by uablrek** [comment] 2021-04-04 12:26
Kube-router as "service proxy" means that it takes over the job of kube-proxy. You must disable kube-proxy otherwise there will be conflicts. I think the problem is that both kube-router and kube-proxy in ipvs mode tries to configure ipvs. So;

Disable kube-proxy.

**Comment by dev999k8** [comment] 2021-04-04 12:38
@uablrek Kube-proxy is already removed, it is not running. As mentioned above the setup works fine on kube 1.18, just not 1.19+.

**Comment by uablrek** [comment] 2021-04-04 13:22
> Working on iptables mode (not ipvs) - works completely fine.

The above is misleading. Kube-router has no iptables mode.

Since `kube-router` is installed as service proxy and `kube-proxy` is disabled, this is a kube-router problem.

Please raise an issue on kube-router. I close this issue.

/close

**Closed** 2021-04-04 13:22 UTC
Labels: kind/bug, needs-triage, sig/network
