### ISSUE TITLE
Single watch endpoint for events and entities changes

### ISSUE THREAD

**Issue by simon3z** [kubernetes/kubernetes#5130] opened 2015-03-06 15:31 UTC
As discussed with @bgrant0607 my plan for analyzing the kubernetes cluster is to fetch all the entities (pods, services, enpoints, etc.) and then keep in sync watching the entities/events.

It would be great if instead of watching each entity separately:

```
https://apiserver:8443/api/v1beta3/watch/pods       // receive notices about pods
https://apiserver:8443/api/v1beta3/watch/services   // receive notices about services
...
```

I could watch just a single endpoint and receive all the updates, e.g.:

```
https://apiserver:8443/api/v1beta3/watch   // receive notices about entities/events
```

(I have the feeling that I have mentioned this idea to @thockin at the meetup)

In terms of performance it shouldn't be much different than what I would do anyway (watching each entity separately), and with the advantage of managing only one connection.

I already started some work in this direction but I'd like some early feedback on the idea. Thanks.

**Comment by derekwaynecarr** [comment] 2015-03-06 15:44
We had some discussion in the past about the ability to support watching multiple resource types in a single call.  See: https://github.com/GoogleCloudPlatform/kubernetes/issues/1685

I think we need to internally do a single watch on etcd in apiserver, and use that watch to handle all consumers in order to actually make this work in the long-run.

----- Original Message -----

**Comment by simon3z** [comment] 2015-03-06 16:25
> I think we need to internally do a single watch on etcd in apiserver, and use that watch to handle all consumers in order to actually make this work in the long-run.

Yes I think I saw a comment related to that in the code. The /pods, /services, etc... endpoints should be just filters applied on the single flow of updates (of all kinds).

**Comment by jmartin127** [comment] 2016-06-17 22:02
+1

**Comment by smarterclayton** [comment] 2017-06-01 17:10
Dupe of #1685

**Closed by smarterclayton** 2017-06-01 17:10 UTC
Labels: area/api, area/usability, priority/awaiting-more-evidence, sig/api-machinery
