### ISSUE TITLE
Automated upgrade tests failing when run manually

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#42382] opened 2017-03-02 02:00 UTC
Reproduction steps, following steps described in https://docs.google.com/document/d/1nj_cQ8RTuGPnpoHNOAROFNmgSaNytPdE1bgrNt8Hfjo/edit#
```
git checkout v1.6.0-beta.0
make quick-release
go run ./hack/e2e.go --check_version_skew=false --v=t --up --test --test_args="--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci"
```

The master fails to come back up after 2 hours.

/var/log/kube-apiserver.log:
```
...
I0302 01:33:21.121658       5 feature_gate.go:170] feature gates: map[ExperimentalCriticalPodAnnotation:true]
I0302 01:33:21.126161       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[e2e-test-stclair-minion] NodeInstancePrefix:e2e-test-stclair-minion Multizone:false}}
I0302 01:33:21.126183       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
Flag --address has been deprecated, see --insecure-bind-address instead.
I0302 01:38:30.136318       5 feature_gate.go:170] feature gates: map[ExperimentalCriticalPodAnnotation:true]
I0302 01:38:30.141176       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[e2e-test-stclair-minion] NodeInstancePrefix:e2e-test-stclair-minion Multizone:false}}
I0302 01:38:30.141231       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
Flag --address has been deprecated, see --insecure-bind-address instead.
I0302 01:43:31.108674       5 feature_gate.go:170] feature gates: map[ExperimentalCriticalPodAnnotation:true]
I0302 01:43:31.111403       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[e2e-test-stclair-minion] NodeInstancePrefix:e2e-test-stclair-minion Multizone:false}}
I0302 01:43:31.111437       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
Flag --address has been deprecated, see --insecure-bind-address instead.
I0302 01:48:42.170923       5 feature_gate.go:170] feature gates: map[ExperimentalCriticalPodAnnotation:true]
I0302 01:48:42.174802       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[e2e-test-stclair-minion] NodeInstancePrefix:e2e-test-stclair-minion Multizone:false}}
I0302 01:48:42.174837       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
Flag --address has been deprecated, see --insecure-bind-address instead.
I0302 01:53:44.095888       5 feature_gate.go:170] feature gates: map[ExperimentalCriticalPodAnnotation:true]
I0302 01:53:44.098858       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[e2e-test-stclair-minion] NodeInstancePrefix:e2e-test-stclair-minion Multizone:false}}
I0302 01:53:44.098887       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
unable to load server certificate: tls: failed to find any PEM data in certificate input
```

/cc @roberthbailey

**Comment by krousey** [comment] 2017-03-02 02:15
Duplicate of https://github.com/kubernetes/kubernetes/issues/42199.

Unfortunately the fix is not in the 1.6 beta.0.

**Closed by krousey** 2017-03-02 02:15 UTC
