### ISSUE TITLE
PodStatus is not refreshed by kubelet

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#17980] opened 2015-11-30 20:36 UTC
This is a regression found with HEAD:
```
$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.3.952+ae17a9400fda14-dirty", GitCommit:"ae17a9400fda14f54a89232797cd43399f228873", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.3.952+ae17a9400fda14-dirty", GitCommit:"ae17a9400fda14f54a89232797cd43399f228873", GitTreeState:"dirty"}
```

I built a cluster for soaking tests before holiday, and found some master components are not at running state this morning:
```
$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                           READY     STATUS             RESTARTS   AGE
default       nginx                                          0/1       CrashLoopBackOff   917        10d
kube-system   etcd-server-events-kubernetes-master           1/1       Running            0          10d
kube-system   etcd-server-kubernetes-master                  1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-master        1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-1fjv   1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-7avg   1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-nyon   1/1       Running            0          10d
kube-system   heapster-v10-i4a22                             1/1       Running            2          10d
kube-system   kube-apiserver-kubernetes-master               1/1       Running            2          6d
kube-system   kube-controller-manager-kubernetes-master      0/1       Error              1          6d
kube-system   kube-dns-v9-yu2ua                              4/4       Running            0          10d
kube-system   kube-proxy-kubernetes-minion-1fjv              1/1       Running            0          6d
kube-system   kube-proxy-kubernetes-minion-7avg              1/1       Running            0          6d
kube-system   kube-proxy-kubernetes-minion-nyon              1/1       Running            0          6d
kube-system   kube-scheduler-kubernetes-master               0/1       Error              1          6d
kube-system   kube-ui-v3-mjue5                               1/1       Running            0          10d
kube-system   l7-lb-controller-f7mxm                         2/2       Running            0          10d
kube-system   monitoring-influxdb-grafana-v2-fb6hq           2/2       Running            0          10d
```

Here is the output of kubectl describe for scheduler. Similar output for controller-manager. 
```
$ cluster/kubectl.sh describe pod kube-scheduler-kubernetes-master --namespace=kube-system
Name:				kube-scheduler-kubernetes-master
Namespace:			kube-system
Image(s):			gcr.io/google_containers/kube-scheduler:df4161ae0b1eef8ae0c530b39ce22904
Node:				kubernetes-master/10.240.0.2
Start Time:			Fri, 20 Nov 2015 10:21:04 -0800
Labels:				<none>
Status:				Running
Reason:				
Message:			
IP:				10.240.0.2
Replication Controllers:	<none>
Containers:
  kube-scheduler:
    Container ID:	docker://4027f9447fd9e0ac91a2733e6c79a9c27b7fda0aa2092a974664b08bec6035db
    Image:		gcr.io/google_containers/kube-scheduler:df4161ae0b1eef8ae0c530b39ce22904
    Image ID:		docker://c8e34c86ce4c3a6424dfd841b89459a23c613d8222a6ea3b2898500c17f95089
    Command:
      /bin/sh
      -c
      /usr/local/bin/kube-scheduler --master=127.0.0.1:8080  --v=2 1>>/var/log/kube-scheduler.log 2>&1
    QoS Tier:
      cpu:	Guaranteed
      memory:	BestEffort
    Limits:
      cpu:	100m
    Requests:
      cpu:			100m
    State:			Terminated
      Reason:			Error
      Exit Code:		255
      Started:			Mon, 23 Nov 2015 17:01:25 -0800
      Finished:			Mon, 23 Nov 2015 17:01:25 -0800
    Last Termination State:	Terminated
      Reason:			Error
      Exit Code:		255
      Started:			Mon, 23 Nov 2015 17:01:24 -0800
      Finished:			Mon, 23 Nov 2015 17:01:24 -0800
    Ready:			False
    Restart Count:		1
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  logfile:
    Type:	HostPath (bare host directory volume)
    Path:	/var/log/kube-scheduler.log
No events.
```

I ssh-ed into the master node, and found that the failed master component running happily:
```
# docker ps -a | grep kube-controller
214e69b17252        gcr.io/google_containers/kube-controller-manager:19dfed43c2d70d66041e08cc665feee7   "/bin/sh -c '/usr/loc"   6 days ago          Up 6 days                                      k8s_kube-controller-manager.4b5675b6_kube-controller-manager-kubernetes-master_kube-system_cfc3403b3d8ef08918339348296531d5_31bdcfca
d4125efecbca        gcr.io/google_containers/kube-controller-manager:19dfed43c2d70d66041e08cc665feee7   "/bin/sh -c '/usr/loc"   6 days ago          Exited (255) 6 days ago                        k8s_kube-controller-manager.4b5675b6_kube-controller-manager-kubernetes-master_kube-system_cfc3403b3d8ef08918339348296531d5_6d77fc14
8faaa15a4bb0        gcr.io/google_containers/kube-controller-manager:19dfed43c2d70d66041e08cc665feee7   "/bin/sh -c '/usr/loc"   6 days ago          Exited (255) 6 days ago                        k8s_kube-controller-manager.4b5675b6_kube-controller-manager-kubernetes-master_kube-system_cfc3403b3d8ef08918339348296531d5_5f4b930e
f5391d2c2986        gcr.io/google_containers/pause:2.0                                                  "/pause"                 6 days ago          Up 6 days                                      k8s_POD.6059dfa2_kube-controller-manager-kubernetes-master_kube-system_cfc3403b3d8ef08918339348296531d5_77d5fd06
860211600a56        gcr.io/google_containers/kube-controller-manager:08ee2d314b44e9fee310f0d672a93098   "/bin/sh -c '/usr/loc"   10 days ago         Exited (137) 6 days ago                        k8s_kube-controller-manager.f8037520_kube-controller-manager-kubernetes-master_kube-system_d41d72b8e470fd5161d949fc0200fcc5_00a39244
89aa10dc334a        gcr.io/google_containers/pause:2.0                                                  "/pause"                 10 days ago         Exited (0) 6 days ago                          k8s_POD.6059dfa2_kube-controller-manager-kubernetes-master_kube-system_d41d72b8e470fd5161d949fc0200fcc5_17a965d1
```

I restarted kubelet, and kubectl get pods show the proper states:
```
$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                           READY     STATUS             RESTARTS   AGE
default       nginx                                          0/1       CrashLoopBackOff   917        10d
kube-system   etcd-server-events-kubernetes-master           1/1       Running            0          10d
kube-system   etcd-server-kubernetes-master                  1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-master        1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-1fjv   1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-7avg   1/1       Running            0          10d
kube-system   fluentd-cloud-logging-kubernetes-minion-nyon   1/1       Running            0          10d
kube-system   heapster-v10-i4a22                             1/1       Running            2          10d
kube-system   kube-apiserver-kubernetes-master               1/1       Running            2          6d
kube-system   kube-controller-manager-kubernetes-master      1/1       Running            2          6d
kube-system   kube-dns-v9-yu2ua                              4/4       Running            0          10d
kube-system   kube-proxy-kubernetes-minion-1fjv              1/1       Running            0          6d
kube-system   kube-proxy-kubernetes-minion-7avg              1/1       Running            0          6d
kube-system   kube-proxy-kubernetes-minion-nyon              1/1       Running            0          6d
kube-system   kube-scheduler-kubernetes-master               1/1       Running            2          6d
kube-system   kube-ui-v3-mjue5                               1/1       Running            0          10d
kube-system   l7-lb-controller-f7mxm                         2/2       Running            0          10d
kube-system   monitoring-influxdb-grafana-v2-fb6hq           2/2       Running            0          10d
```

This is clearly a bug in kubelet itself.

**Comment by dchen1107** [comment] 2015-11-30 20:37
cc/ @yujuhong and @Random-Liu: I believe the regression is caused by the recent changes for performance.

**Comment by Random-Liu** [comment] 2015-11-30 20:40
OK. I'll look into it! :)

**Comment by Random-Liu** [comment] 2015-12-02 02:49
@dchen1107 @yujuhong I reproduced the issue with log enabled.

```
lantaol@kubernetes-master:~$ kubectl get pods --namespace=kube-system
NAME                                           READY     STATUS    RESTARTS   AGE
etcd-server-events-kubernetes-master           1/1       Running   0          1d
etcd-server-kubernetes-master                  1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-master        1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-19js   1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-j4uh   1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-wga1   1/1       Running   0          1d
heapster-v10-sbbss                             1/1       Running   0          1d
kube-apiserver-kubernetes-master               1/1       Running   1          33m
kube-controller-manager-kubernetes-master      0/1       Error     1          33m
kube-dns-v9-uk58o                              4/4       Running   0          1d
kube-proxy-kubernetes-minion-19js              1/1       Running   0          31m
kube-proxy-kubernetes-minion-j4uh              1/1       Running   0          30m
kube-proxy-kubernetes-minion-wga1              1/1       Running   0          31m
kube-scheduler-kubernetes-master               0/1       Error     1          33m
kube-ui-v3-m8ean                               1/1       Running   0          1d
l7-lb-controller-69drh                         2/2       Running   0          1d
monitoring-influxdb-grafana-v2-s6rs5           2/2       Running   0          1d
```

```
lantaol@kubernetes-master:~$ kubectl describe pod kube-scheduler-kubernetes-master --namespace=kube-system
Name:                           kube-scheduler-kubernetes-master
Namespace:                      kube-system
Image(s):                       gcr.io/google_containers/kube-scheduler:ccdf5c15ddaefc5a6e7f2d291c992e8c1449021650
Node:                           kubernetes-master/10.240.0.3
Start Time:                     Tue, 01 Dec 2015 02:37:58 +0000
Labels:                         <none>
Status:                         Running
Reason:
Message:
IP:                             10.240.0.3
Replication Controllers:        <none>
Containers:
  kube-scheduler:
    Container ID:       docker://e71c213473b8ae9452f86852fb2649d4b5c191a85561bf082ff02fe36161dfdf
    Image:              gcr.io/google_containers/kube-scheduler:ccdf5c15ddaefc5a6e7f2d291c992e8c1449021650
    Image ID:           docker://f8285f1f6f74eb45ca76696a4d3011f34fcf774cba1d392c81e40d68c3b48230
    Command:
      /bin/sh
      -c
      /usr/local/bin/kube-scheduler --master=127.0.0.1:8080  --v=2 1>>/var/log/kube-scheduler.log 2>&1
    QoS Tier:
      cpu:      Guaranteed
      memory:   BestEffort
    Limits:
      cpu:      100m
    Requests:
      cpu:                      100m
    State:                      Terminated
      Reason:                   Error
      Exit Code:                255
      Started:                  Wed, 02 Dec 2015 02:10:04 +0000
      Finished:                 Wed, 02 Dec 2015 02:10:04 +0000
    Last Termination State:     Terminated
      Reason:                   Error
      Exit Code:                255
      Started:                  Wed, 02 Dec 2015 02:10:03 +0000
      Finished:                 Wed, 02 Dec 2015 02:10:03 +0000
    Ready:                      False
    Restart Count:              1
    Environment Variables:
Conditions:
  Type          Status
  Ready         False 
Volumes:
  logfile:
    Type:       HostPath (bare host directory volume)
    Path:       /var/log/kube-scheduler.log
No events.
```

```
lantaol@kubernetes-master:~$ sudo docker ps -a | grep kube-scheduler
9d5516769571        gcr.io/google_containers/kube-scheduler:ccdf5c15ddaefc5a6e7f2d291c992e8c1449021650            "/bin/sh -c '/usr/loc"   37 minutes ago      Up 37 minutes                                     k8s_kube-scheduler.f11b204f_kube-sche
duler-kubernetes-master_kube-system_80f014c8b197613c7e69cee772007400_9e3dab20
e71c213473b8        gcr.io/google_containers/kube-scheduler:ccdf5c15ddaefc5a6e7f2d291c992e8c1449021650            "/bin/sh -c '/usr/loc"   38 minutes ago      Exited (255) 38 minutes ago                       k8s_kube-scheduler.f11b204f_kube-sche
duler-kubernetes-master_kube-system_80f014c8b197613c7e69cee772007400_42bd10d2
eff61969e3c9        gcr.io/google_containers/kube-scheduler:ccdf5c15ddaefc5a6e7f2d291c992e8c1449021650            "/bin/sh -c '/usr/loc"   38 minutes ago      Exited (255) 38 minutes ago                       k8s_kube-scheduler.f11b204f_kube-sche
duler-kubernetes-master_kube-system_80f014c8b197613c7e69cee772007400_228f648f
e4fcfa36534a        gcr.io/google_containers/pause:2.0                                                            "/pause"                 38 minutes ago      Up 38 minutes                                     k8s_POD.6059dfa2_kube-scheduler-kuber
netes-master_kube-system_80f014c8b197613c7e69cee772007400_63b60d13
87e17b6a7bb1        gcr.io/google_containers/kube-scheduler:00cec2f4dfca4c3bcc86994e9afa59921448936939            "/bin/sh -c '/usr/loc"   24 hours ago        Exited (137) 37 minutes ago                       k8s_kube-scheduler.4deb2005_kube-sche
duler-kubernetes-master_kube-system_7bf9388a0cc5688bb501580e551cb917_0a64aced
b62af169abd1        gcr.io/google_containers/kube-scheduler:00cec2f4dfca4c3bcc86994e9afa59921448936325            "/bin/sh -c '/usr/loc"   24 hours ago        Exited (137) 24 hours ago                         k8s_kube-scheduler.117f1ffa_kube-sche
duler-kubernetes-master_kube-system_7bf9388a0cc5688bb501580e551cb917_c5562cac
51e4fd1b9a34        gcr.io/google_containers/pause:2.0                                                            "/pause"                 24 hours ago        Exited (0) 37 minutes ago                         k8s_POD.6059dfa2_kube-scheduler-kuber
netes-master_kube-system_7bf9388a0cc5688bb501580e551cb917_1aa25b94
```

**Comment by Random-Liu** [comment] 2015-12-02 03:02
As the log, GetPodStatus have returned the ***right status***, but it was never updated to apiserver. It seems that the error occurs because apiserver is restarted after Kubelet started.

I'll dig into the log more. And the log is [here](https://gist.github.com/Random-Liu/d8f539cfec46b4715625).

**Comment by yujuhong** [comment] 2015-12-02 07:25
I couldn't reproduce this on my cluster at all. @Random-Liu, could you set the logging level of kubelet to 4 and include the kubelet.log? Thanks!

My guess is that this is caused by the order of updating the pod status and re-creating mirror pods during apiserver restarts. You could see a few failed attempts of status update when apiserver was restarting, and then completely silent (i.e., no status update) after apiserver started functioning. A more detailed would help confirm the theory and root cause the issue.

@timstclair, just FYI, as this might have something to do with status versioning, but I am not sure yet.

**Comment by Random-Liu** [comment] 2015-12-02 07:49
@yujuhong Yeah, good point! It looks like status manager doesn't work after apiserver is restarted. I modified the `build` file to let the image ID change every `make release`, then I run `kube-push.sh`. This ensures that the pods are restarted every `kube-push.sh`. By this way, the error may be triggered sometimes, but I'm not quite sure.

I'll change the log level, and try it again. :)

**Comment by Random-Liu** [comment] 2015-12-02 08:06
Because the pod status will come back to normal after kubelet restarted, I paste the log during kubelet restarting [here](https://gist.github.com/Random-Liu/985dc719d31ddb2f9c28). It may be useful.

The file is truncated, kubelet is restarted after line 80.

**Comment by Random-Liu** [comment] 2015-12-02 08:29
It's really flaky.

This time:
```
lantaol@kubernetes-master:~$ kubectl get pods --namespace=kube-system
NAME                                           READY     STATUS    RESTARTS   AGE
etcd-server-events-kubernetes-master           1/1       Running   0          1d
etcd-server-kubernetes-master                  1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-master        1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-19js   1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-j4uh   1/1       Running   0          1d
fluentd-cloud-logging-kubernetes-minion-wga1   1/1       Running   0          1d
heapster-v10-sbbss                             1/1       Running   0          1d
kube-apiserver-kubernetes-master               1/1       Running   1          2m
kube-controller-manager-kubernetes-master      0/1       Error     1          2m
kube-dns-v9-uk58o                              4/4       Running   0          1d
kube-proxy-kubernetes-minion-19js              1/1       Running   0          26s
kube-proxy-kubernetes-minion-j4uh              1/1       Running   0          47s
kube-proxy-kubernetes-minion-wga1              1/1       Running   0          46s
kube-scheduler-kubernetes-master               1/1       Running   1          2m
kube-ui-v3-m8ean                               1/1       Running   0          1d
l7-lb-controller-69drh                         2/2       Running   0          1d
monitoring-influxdb-grafana-v2-s6rs5           2/2       Running   0          1d
```
I changed log level to 4, and the log is [here](https://gist.github.com/Random-Liu/f5f0a4ee5d07b118b638). The log is also truncated, `kube-push.sh` started from line 360.

**Comment by yujuhong** [comment] 2015-12-03 02:20
I added some more logging and here is what I found:

```
I1203 01:04:35.387632   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 0, after: 1, status: {Phase: Conditions:[] Message: Reason: HostIP: PodIP: StartTime:2015-12-03 00:54:37 +0000 UTC ContainerStatuses:[]}
I1203 01:04:36.464037   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 1, after: 2, status: {Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-12-03 01:04:36.464017297 +0000 UTC Reason: Message:}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:2015-12-03 00:54:37 +0000 UTC ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:0xc2083dd120 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://5fc80677beea9580c49bc001020eac2706d92a19d2558e15eb5dcaa0d9613837}]}
I1203 01:04:37.633795   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 2, after: 3, status: {Phase:Running Conditions:[{Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-12-03 01:04:37.633774943 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kube-apiserver]}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:2015-12-03 00:54:37 +0000 UTC ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:<nil> Terminated:0xc20875fce0} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://5fc80677beea9580c49bc001020eac2706d92a19d2558e15eb5dcaa0d9613837}]}
I1203 01:04:40.427956   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 0, after: 1, status: {Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-12-03 01:04:40.427943671 +0000 UTC Reason: Message:}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:2015-12-03 01:04:40.427944272 +0000 UTC ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:0xc208301e80 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:0xc208af2620} Ready:true RestartCount:1 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://8d5ab9214d324460bc4259d9858f2bb441665fbafabb343a51f9c5075c6ff9cf}]}
I1203 01:04:42.385199   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 1, after: 2, status: {Phase:Running Conditions:[{Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-12-03 01:04:42.385175527 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kube-apiserver]}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:2015-12-03 01:04:40.427944272 +0000 UTC ContainerStatuses:[{Name:kube-apiserver State:{Waiting:0xc208b22200 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:0xc2085e1030} Ready:false RestartCount:1 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://8d5ab9214d324460bc4259d9858f2bb441665fbafabb343a51f9c5075c6ff9cf}]}
I1203 01:05:41.425311   28085 manager.go:259] [updateStatusInternal]: Incrementing status versionfor pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"), before: 2, after: 3, status: {Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-12-03 01:05:41.42529245 +0000 UTC Reason: Message:}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:2015-12-03 01:04:40.427944272 +0000 UTC ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:0xc208bb71e0 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:0xc208880fc0} Ready:true RestartCount:2 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://3cf73b2120300443be3e59b5cb9ecacfe5782ff90f6b843e5b4c8ddf994e09d7}]}
```

The version number of the pod status for kube-apiserver was reset once because the entry got deleted when status manager couldn't get a pod with the same name/namespace from the apiserver (the mirror pod was going through a series of creations/deletions) On the other hand, the apiStatusVersion was never cleared and the version number remains high.

```
I1203 01:04:41.537388   28085 manager.go:369] Status for pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"/"d481996e-9959-11e5-a632-42010af00002") updated successfully: {status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:<nil>}} LastTransitionTime:{Time:{sec:63584701480 nsec:427943671 loc:0x2969080}} Reason: Message:}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:0xc2084f5900 ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:0xc208301e80 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:0xc208af2620} Ready:true RestartCount:1 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://8d5ab9214d324460bc4259d9858f2bb441665fbafabb343a51f9c5075c6ff9cf}]} version:1 podName:kube-apiserver-kubernetes-master podNamespace:kube-system}
I1203 01:04:42.119329   28085 manager.go:369] Status for pod "kube-apiserver-kubernetes-master_kube-system" ("f9b36e13f1fca6b59dcbd9df360f7f2d"/"d481996e-9959-11e5-a632-42010af00002") updated successfully: {status:{Phase:Running Conditions:[{Type:Ready Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:<nil>}} LastTransitionTime:{Time:{sec:63584701477 nsec:633774943 loc:0x2969080}} Reason:ContainersNotReady Message:containers with unready status: [kube-apiserver]}] Message: Reason: HostIP:10.240.0.2 PodIP:10.240.0.2 StartTime:0xc2086481c0 ContainerStatuses:[{Name:kube-apiserver State:{Waiting:<nil> Running:<nil> Terminated:0xc20875fce0} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/kube-apiserver:758be10526abaf76183daa80a54d720e1449104338 ImageID:docker://fd8cad5745dcd6354b6b0be881b2a0bf58a4993092daab14aaace0de15b55fdf ContainerID:docker://5fc80677beea9580c49bc001020eac2706d92a19d2558e15eb5dcaa0d9613837}]} version:3 podName:kube-apiserver-kubernetes-master podNamespace:kube-system}
```

I sent a PR #18129 to remove the code which deletes the pod status entries.

**Comment by Random-Liu** [comment] 2015-12-11 09:31
@dchen1107 
#18129 has been merged, I've tested that PR should have fixed this issue.
And after reading status manager related code these days, I think what @yujuhong said is the root reason of the issue. :)

**Comment by yujuhong** [comment] 2015-12-11 19:39
Feel free to reopen if you see it again.

**Closed by yujuhong** 2015-12-11 19:39 UTC
Labels: kind/bug, priority/P0, team/node
