### ISSUE TITLE
Can't get --cloud-provider=aws to work (instance not found)

### ISSUE THREAD

**Issue by philk** [kubernetes/kubernetes#11543] opened 2015-07-19 02:33 UTC
I'm trying to set up AWS ELB attach volume access and keep getting an error on the kubelet. I have some bad feeling it might be related to #9801 as these nodes are CoreOS that were brought up by Terraform with custom service files but everything else is working fine (we're running cluster monitoring, dns, and a number of our own pods without issues). I've run awscli on that instance and the privileges definitely work. What am I doing wrong?

logs from kubelet service

```
I0719 02:22:59.549444    9662 factory.go:234] Registering Docker factory
I0719 02:22:59.549826    9662 factory.go:89] Registering Raw factory
I0719 02:22:59.638468    9662 manager.go:946] Started watching for new ooms in manager
I0719 02:22:59.639054    9662 oomparser.go:183] oomparser using systemd
I0719 02:22:59.640589    9662 manager.go:243] Starting recovery of all containers
E0719 02:22:59.679107    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
I0719 02:22:59.753816    9662 manager.go:248] Recovery completed
I0719 02:22:59.816369    9662 status_manager.go:76] Starting to sync pod status with apiserver
I0719 02:22:59.816426    9662 kubelet.go:1725] Starting kubelet main sync loop.
E0719 02:22:59.953337    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:01.047929    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:01.975409    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:03.645707    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:06.917503    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
I0719 02:23:07.790941    9662 server.go:635] POST /stats/container/: (46.254087ms) 0 [[Go 1.1 package http] 10.0.39.222:45497]
```

kube-kubelet.service

```
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
Environment="KUBERNETES_BINARY_VERSION=1.0.0"
EnvironmentFile=/etc/environment
ExecStartPre=/usr/bin/curl -L -o /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_BINARY_VERSION}/bin/linux/amd64
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
ExecStart=/opt/bin/kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --cloud-provider=aws \
  --hostname-override=${COREOS_PRIVATE_IPV4} \
  --api-servers=${KUBE_MASTER_IP}:8080 \
  --allow-privileged=false \
  --cluster_dns=10.2.0.2 \
  --cluster_domain=cluster.local \
  --cadvisor_port=4194 \
  --healthz_bind_address=0.0.0.0 \
  --healthz_port=10248 \
  --v=2 \
  --logtostderr=true
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

iam policy

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:Describe*"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
  ]
}
```

**Comment by philk** [comment] 2015-07-19 19:45
Well I found the cause at least:

Kubelet attempts to [get its ExternalID](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L748). To do this is uses the mis-named [aws.findInstanceByNodeName](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L662) which actually looks up the node by [private-dns-name](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L2274) not node name (which is potentially a good thing since in the case of autoscaling groups node names won't be unique, but still, confusing name). This would probably work under a normal situation but we're using a VPC DHCP option set to use an internal management domain, not the standard `<region>.compute.internal`. When the kubelet is configured for AWS it uses [the metadata service](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L278) to get it's [local-hostname](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L1240) which in our case doesn't match the private DNS name, it matches our management domain.

I'm not really sure what the right fix here is. My instinct is that `--hostname-override` should actually do something even when you're using `--cloud-provider=aws` (it currently seems to do nothing). I notice that `// TODO: ExternalID is deprecated, we'll have to drop this code` but I couldn't find out what that specifically means. Also interesting to me is that the `kubernetes.io/hostname` [label is inconsistent](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L736) in the case of using cloud provider unless the hostname exactly matches the "ExternalID". I'm not actually sure this entire section of code (kubelet.go 739-761) even does anything useful vs just using `kl.hostname` directly for the ExternalID. If ExternalID is really deprecated I'm inclined to submit a patch to rip that out.

**Comment by bkeroackdsc** [comment] 2015-07-22 19:37
@thockin @justinsb 

This also breaks the AWS cloud provider when using [private hosted DNS zones](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html).

Essentially, kubelet thinks the nodename is whatever the local hostname is ("ip-xx-xx-xx-xx-.my.custom.domain.com") and then tries to get the instance details by querying the EC2 API by ``private-dns-name``, which actually is something like "ip-xx-xx-xx-xx.us-west-2.compute.internal"). This fails of course.

This makes it impossible to use the AWS cloud provider and therefore automatic ELB provisioning, etc.

**Comment by thockin** [comment] 2015-07-23 06:01
I don't have the hands-on AWS experience Justin does, so I am going to
defer quite a bit to him, but I have been worried about this facet of the
system.  We do not have (or I do not know) a set of principled rules that
govern the myriad node-name options.  We need rules.

On Wed, Jul 22, 2015 at 12:37 PM, Benjamen Keroack <notifications@github.com

**Comment by bkeroackdsc** [comment] 2015-07-23 16:49
The error is thrown [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L748-L751) which calls into the [aws cloud provider](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L662-L672). The issue (to me) being that ExternalID(), instead of directly querying the local metadata store (initialNodeStatus() on kubelet should always be the *local* node, yes?) assumes that hostname will always equal private-dns-name (not true) and queries the EC2 API.

However the comments in that code indicate that ExternalID() is deprecated. So maybe this whole issue will go away soon?

**Comment by justinsb** [comment] 2015-07-27 12:31
A bit of context:

* NodeName is the k8s node name.  findInstanceByNodeName is to differentiate from findInstanceById, which uses an AWS ID (and confusingly I don't think this function is present in the current code).

* Currently NodeName must be an internally resolvable DNS name.  We have come very close to fixing this, but there are still a few last points. for e.g. kubectl exec/logs to work.  I would like to fix this: #11883

* If we can fix that problem, we can make the EC2 instance id the k8s node name.  That is more correct, I believe, and should then relax a lot of these requirements around DNS naming.  We also wouldn't constantly need to be translating between private dns name and instance id.

I think if I can fix #11883 then you can name your instances whatever you want (and/or turn off internal DNS altogether).  This is another instance where kube-up is very careful to do exactly the right thing, and it is very easy to do something different if not using kube-up.  I think the correct thing here is to relax the requirements, but in the meantime you probably can't use a custom DNS suffix.

**Comment by jtblin** [comment] 2015-09-03 20:10
Is there an ETA for this to be fixed? We deploy kubernetes on coreos in our own VPC in AWS and this is basically preventing us from using it as `kubelet` crashes with `cloud-provider=aws` as for OP because of this issue.

**Comment by justinsb** [comment] 2015-09-04 21:23
I recognize it's not ideal, but to help me understand better, is it an option to use the normal .compute.internal DNS suffix for the k8s VPC?  If not, why not?

I would like to fix it, but it is non-trivial.  Though it is a holiday weekend....

**Comment by bkeroackdsc** [comment] 2015-09-15 22:06
@justinsb if you use private DNS zones, ``.compute.internal`` isn't an option.

**Comment by jtblin** [comment] 2015-09-16 05:14
@justinsb moreover it should be possible to deploy k8s in an existing VPC vs having to create a VPC just for k8s. That's the use case that we have today (existing VPC with private DNS zones) which make using  k8s impossible.

**Comment by bkeroackdsc** [comment] 2015-09-16 16:38
In fairness you *can* deploy k8s in an existing VPC w/ private DNS zones, you just can't use AWS cloud provider integration.

**Comment by jtblin** [comment] 2015-09-16 21:22
Yes you're right, I shall have said make it impossible to use features like automatic ELB and EBS provisioning features. These are must-have features from our perspective hence the original shortcut.

**Comment by diranged** [comment] 2015-09-23 19:44
Just to add to this.. we've setup K8S 1.0.6 inside our VPC and just added `--cloud-provider=aws` (_and the accompanying IAM profiles to our nodes_). While things like `kubectl` work fine, we noticed that the `kubelet` processes are now registering themselves in the `kube-apiserver` with their EC2 name rather than the hostnames we use internally.

Now, we "allow" use of the `.internal` domain name from Amazon in the sense that we can resolve those names just fine. The only real issue here is that the `nodeName` in Kubernetes is now wrong and misleading for our engineers:

```
ip-10-16-80-224.us-west-1.compute.internal   kubernetes.io/hostname=tools-k8s-node-uswest1-17-i-905b2250   Ready
ip-10-16-82-31.us-west-1.compute.internal    kubernetes.io/hostname=tools-k8s-node-uswest1-15-i-67621ba7   Ready
ip-10-16-86-186.us-west-1.compute.internal   kubernetes.io/hostname=tools-k8s-node-uswest1-16-i-4eff2bfc   Ready
```

I also tried adding `--hostname-override=tools-k8s-node-uswest1-17-i-905b2250` to kubelet's startup parameters and it had no impact on the name actually registered in the api server.

**Comment by roboll** [comment] 2015-09-28 15:21
Forgive me if I'm missing something obvious here, and for repeating much of what @philk and @bkeroackdsc have said already, but I'm confused by the above conclusions. Using an `instance-id` as a node name (as suggested in #11883) is _not_ ideal, non-default hostnames are that way for a reason and it's going to be much clearer to users / administrators if they see the hostname rather than an instance id (_imho_). When securing a dynamic infrastructure it's often a necessity to work with a private domain in order to supply certificates - the ip addresses of nodes are unpredictable. Cloud providers need not be aware of this.

Kubernetes internally should not conflate the node name - the hostname of a node in the cluster, with the `instance-id`, the identifier it uses to communicate with the aws cloud provider.

The call to `ExternalID` eventually ends up calling `getInstanceByNodeName` (see below), with the implication that the node name is the `private-dns-name` - __can't this simply be changed to a more correct behavior of retrieving the instance id from the metadata service, and adjusting the query to use that?__ The change would entail fetching the `instance-id` from the metadata service, caching that, and changing the tag query to use `instance-id` instead of `private-dns-name`. This should always succeed as `instance-id` is unique to an instance. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2083

The only potential complication I foresee is if another member of the cluster needs to use the kubernetes node name in order to operate on the cloud provider, i.e. trying to attach an volume to an instance. As far as I can tell those operations are done locally, which is further implied by the iam permissions applied to `kubelet` nodes (`ec2:AttachVolume` and `ec2:DetachVolume`), but I haven't read the entire codebase. If this is a necessary use case, I'd suggest that a reverse dns lookup for the hostname, and then finding the instance with the cloud provider based on it's private ip, is more correct than assuming that the cloud provider has any knowledge of the instances hostname.

I'd be happy to put this change together but would like some feedback on the idea - @thockin @justinsb thoughts?

**Comment by jtblin** [comment] 2015-10-02 01:17
@diranged I just tried with 1.0.6 and I'm still getting the same problem i.e. logs are spammed with the errors below and the node doesn't register in the cluster

> Sep 30 18:25:24 ip-10-116-11-99.platform.dev.xxx kubelet[899]: E0930 18:25:24.488410     899 kubelet.go:1641] error getting node: node ip-10-116-11-99.platform.dev.xxx not found
Sep 30 18:25:25 ip-10-116-11-99.platform.dev.xxx kubelet[899]: E0930 18:25:25.047176     899 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found

**Comment by jfoy** [comment] 2015-10-14 23:42
:+1: to @roboll's proposal. We've just been bitten by this same issue.

**Comment by dhawal55** [comment] 2015-10-15 14:37
+1 to @roboll. I was wondering the same. Why not use instanceId for instance lookup. I will trying to find out why the PrivateDNSName for ec2 is not updated even when i have DHCP option sets for my VPC point to my custom DNS server. If that doesn't work, i'm going to change ```ExternalID``` method to use instanceID and submit a PR.

**Comment by dhawal55** [comment] 2015-10-16 22:05
I have changed the hostname on my ec2 instance to match the ```private-dns-name``` and restarted kubelet but somehow it keeps using the domain set in our VPC's DHCP option set. I have no idea where it is getting the domain. I checked /etc/host and /etc/resolv.conf and both have ```us-west-2.compute.internal``` as the domain. Can any one help explain how kubelet builds the nodeName and how i can make it use the aws domain?

**Comment by philk** [comment] 2015-10-17 03:30
It's been awhile since I looked at this but I'm pretty sure it's pulling
the hostname out of the AWS metadata service. I could confirm later when
I'm back at a real computer.

**Comment by dhawal55** [comment] 2015-10-17 08:02
Yes, that's what is looks like. Now I'm trying to figure how to change
hostname in metadata.

**Comment by roboll** [comment] 2015-10-27 01:48
@dhawal55 last I checked, even with custom dhcp options, amazon metadata service _does not_ change the `private-hostname` attribute. the default private hostname isn't used on the box, but is still resolvable via amazon dns. using custom dhcp options, amazon dns _does not_ resolve the custom hostname either, so it's up to you to use a private hosted route53 zone or your own dns.

aside from all that, kube needs to use the instance id for other apis used for mounting volumes, linking load balancers, etc. so it makes sense to use that as the canonical identifier for an instance.

**Comment by dhawal55** [comment] 2015-10-27 04:47
@roboll Yes, using instanceId is the ideal solution. I was looking for a workaround but it didn't work. It seems like a small change but i was running into issues cross-compiling for linux on a mac. Compilation succeeds but when i run the kubelet binary, i get error: "failed to create kubelet: cAdvisor is unsupported in this build"

**Comment by pat2man** [comment] 2015-11-02 21:33
I like the idea to switch to instanceId as the node-name, but I can see issues here. Ideally I would like to be able to set my node-names to be DNS resolvable like they currently are. What about having the findInstanceByNodeName method look for ```instanceId```, ```private-dns-name```  OR a tag called ```node-name```?

Currently I am looking at running OpenShift on Kubernetes and the only feature of ```--cloud-provider=aws``` that I really need is the EBS volume plugin. It seems a bit overkill to require all my node names to be ```instanceId``` just to get that plugin working.

**Comment by somejfn** [comment] 2015-11-10 17:58
Any traction on moving nodename to InstanceId ?   This bug is still a blocker to get ELB integration on v1.1.1 working for a k8s deployment with an existing vPC

**Comment by lordnynex** [comment] 2015-11-11 06:56
Hello. I'm experiencing the same issue with a completely different piece of software (ironically also AWS EMR) in AWS VPC's. I was googling around and this issue came up so I thought I'd share my thoughts. (Fair warning, I have no idea what kubernetes is nor have I ever used it).

The issue is sporadic and selective editing of AWS documentation. It used to be that setting domain-name in VPC DHCP option sets caused amazon's DHCP server to assign that as a prefix onto the nodes internal DNS name. But you couldn't do anything with it! 

Now, in a super fun turn of events, AWS supports private hosted zones but stops honoring domain-name in DHCP option sets. The node sets it's hostname according to the DHCP response and usually ends up with something like 'ip-10-1-30-179' as it's hostname. Since amazon takes the liberty of duplicating 'domain-name' configuration as 'search' configuration for the DHCP server host lookups automatically fail. 

Interestingly though, if you login to a machine in the VPC and modify /etc/resolv.conf's 'search' line to read

```
search YOURDOMAIN.com ec2.internal
```

and try to resolve that hostname it's works as expected. 

I have not tested the fix yet but DHCP obviously allows for multiple search domains and AWS did support it at one time. If it still does, it's as easy as adding 'search yourdomain.com ec2.internal' to a copy of your existing DHCP options set and associating it with the vpc. 

Hopefully one day there will be integration between Route53 and DHCP option sets.

Good luck everyone

**Comment by emaildanwilson** [comment] 2015-11-13 23:58
Does anyone know what it's using the generate the hostname when the kubelet first tries to register? i've changed the override to be a name that I confirmed works w/ "aws ec2 describe-instances --filter Name=private-dns-name,Values=myhostname" and I also set the hostname of the server to the same thing but kubelet still is complaining that it "failed to get external ID from cloud provider: instance not found". It seems like I had this working in 1.0.6 but now 1.1.1 is more picky. If everyone is ok with the fix that @roboll proposed is anyone working on that?

**Comment by emaildanwilson** [comment] 2015-11-14 00:26
eh... I found it after digging further. now it's overridden by the ec2 metadata (curl http://169.254.169.254/latest/meta-data/hostname) so I can't manipulate it anymore.... bummer. We really need this private-dns-name lookup to go away.

**Comment by jtblin** [comment] 2015-11-25 20:47
I tried using instance id instead of the private dns name but although it solves the immediate problem, it breaks the logs command as kubernetes tries to use the instance id to create the url to access the logs on the nodes via the kubelet e.g. ```$ kubectl --namespace=kube-system logs heapster-uo5x8 
Error from server: Get https://i-af486f71:10250/containerLogs/kube-system/heapster-uo5x8/heapster: dial tcp: lookup i-af486f71: no such host. ``` So instead I've submitted a PR using the private ip address which solves the issue described here and doesn't create new one.

**Comment by lordnynex** [comment] 2015-11-25 21:32
Hello, since my random comment a few weeks back I've looked into kubernetes and I must admit I'm now a huge fan. My issues were unrelated to kubernetes but stem from the same problem. In my original update I talked about adding multiple domains to your dhcp option set. I've since tested that idea and found it to be insufficient because not all operating systems deal with it in the same way. In particular zookeeper does not handle this well. 

I managed to fix my issue by creating forward DNS entries for the entire subnet. This will fix kubernetes issue as well. Here is a jsonnet file I've used to generate aws API batch dns requests. If you use this to generate DNS records that cover the entire subnet, private_dns resolution will work. 

You can substitute YOURDOMAIN.com with a custom TLD configured in your dhcp optionset. 

```forward_records.jsonnet```

```json
local record_ttl = 60;
local record_index = std.range(1, 255);

{
  "Comment": "Create forward records for kubernetes subnet",
  "Changes": [
    {
      "Action": "CREATE",
      "ResourceRecordSet": {
        "Name": "ip-10-1-40-%d.YOURDOMAIN.com" % i,
        "Type": "A",
        "TTL": record_ttl,
        "ResourceRecords": [
          {
            "Value": "10.1.1.%d" % i
          }
        ]
      }
    }
    for i in record_index
  ]
}
```

```bash
jsonnet forward_records.jsonnet > forward_record_batch.json
```

Substituting ```1234567890ABC``` with the zone-id for your private hosted zone. You can find the hosted zone ID by running

```bash
aws route53 list-hosted-zones
```

```bash
aws route53 change-resource-record-sets \
  --hosted-zone-id 1234567890ABC \
  --change-batch file:///forward_record_batch.json
```

**Comment by jtblin** [comment] 2015-11-25 21:39
How would that fix the problem? The issue is that when the `kubelet` calls `DescribeInstance` filtering on "private-dns-name" with "ip-x-x-x-x.YOURDOMAIN.com", the AWS API doesn't return any instance.

**Comment by lordnynex** [comment] 2015-11-25 21:47
@jtblin Sorry I may have misunderstood the issue. From the comments I was under the impression that there was a node to node connectivity issue because it was using private_dns as returned by the AWS api. If that is not the case, please disregard my comments. 

If, however, you're querying the API for nodes in a subnet their private_dns would come back as simply 'ip-x-x-x-x' without domain suffix (if your'e using a vpc). The issue then becomes that the node is unreachable because that name is not resolvable. But if you use private hosted zones and a properly configured dhcp optionset, that name would become resolvable. 

I'm aware I'm walking into this with very little context. I just found the issue frustrating and wanted to spare people the time I spent trying to figure it out.

**Comment by Calpicow** [comment] 2015-12-16 19:22
+1 any progress?

**Comment by kha0S** [comment] 2015-12-20 12:37
+1 this is really important in many setups

**Comment by moserke** [comment] 2015-12-30 01:27
https://github.com/Nordstrom/kubernetes/commit/a2a2e13ee15ff6d0346df0d9f2570f07bb495741 takes a different approach and uses instance-id, which is more expected with AWS.  Welcome conversation on this suggested fix.

**Comment by jtblin** [comment] 2015-12-30 01:44
As explained in #17643, using the instance-id does not work as the api server uses the node name for some commands like `logs` to access the container on the node, see conversation in the PR and #18525.

**Comment by moserke** [comment] 2015-12-30 02:22
This approach does not change the node name, only the externalID and providerID.  That way, things that still rely on the local-hostname as the nodeName still continue to function, like logs.  Seems like #17643 changed the node name to the instance-id as well, which caused problems.  This was more an attempt to make externalID/providerID be like a remote key to AWS, and used for that only.

**Comment by moserke** [comment] 2015-12-30 02:37
It keeps all of the changes encapsulated in the aws.go cloud provider so that other cloud providers can continue to work as the would normally with the node name.  Just does verifications in the provider to make sure the instance it is running on is the node name that was passed in.  Moves the abstraction away from relying on the nodeName to look up anything in aws.

**Comment by jtblin** [comment] 2015-12-30 04:07
Ok, I don't know the code well enough to comment tbh. Note that the changes I made are also encapsulated in the `aws.go` provider only, and touch less code overall. That said I don't have a strong opinion, as long as it works :)

**Comment by moserke** [comment] 2015-12-30 15:56
OK, yeah, looking through yours again, it is a bit more surgical to solve the specific need.  I do have some minor issues with switching the kubernetes node name to an IP address, but that is more a symptom of what I think is the bigger problem which is nodename is overloaded in this case and really externalID/providerID should be used everywhere in reference to finding the object in the cloud provider.  I don't understand why put in those keys if they don't really get used.  We should be able to name our nodes whatever we want and as long as the other key is set correctly the cloud provider should work.

In terms of getting things working though, I like that yours has less potential side effects.  Comes with some pain points, but those would be cleaned up if an overhaul of the cloud provider system was done.

I'll comment on your PR as well and see if we can get any motion on it.  This is really holding up a bunch of stuff for us.

**Comment by moserke** [comment] 2015-12-30 17:54
@jtblin do you use public IP addresses on your nodes?  I'm having an issue with ```func (aws *AWSCloud) NodeAddresses(name string) ([]api.NodeAddress, error) {``` because it tries to get a public IPV4 address which errors out.  That was part of the change I needed to make.

I had to modify it not to error if can't get the IP addresses, but to just throw an error if both addresses could not be found:

```
// NodeAddresses is an implementation of Instances.NodeAddresses.
func (aws *AWSCloud) NodeAddresses(name string) ([]api.NodeAddress, error) {
	self, err := aws.getSelfAWSInstance()
	if err != nil {
		return nil, err
	}

	addresses := []api.NodeAddress{}

	if self.nodeName == name || len(name) == 0 {
		internalIP, errInternal := aws.metadata.GetMetadata("local-ipv4")
		if errInternal != nil {
			glog.Errorf("local-ipv4 address could not be found: %s", errInternal)
		} else {
  		addresses = append(addresses, api.NodeAddress{Type: api.NodeInternalIP, Address: internalIP})
		}

		externalIP, errExternal := aws.metadata.GetMetadata("public-ipv4")
		if errExternal != nil {
			glog.Errorf("public-ipv4 address could not be found: %s", errExternal)
		} else {
  		addresses = append(addresses, api.NodeAddress{Type: api.NodeExternalIP, Address: externalIP})
		}

		if errInternal != nil && errExternal != nil {
			return nil, fmt.Errorf("local-ipv4: %s, public-ipv4: %s", errInternal, errExternal)
		}

		return addresses, nil
	}

	instance, err := aws.getInstanceByNodeName(name)
	if err != nil {
		return nil, err
	}

	if !isNilOrEmpty(instance.PrivateIpAddress) {
		ipAddress := *instance.PrivateIpAddress
		ip := net.ParseIP(ipAddress)
		if ip == nil {
			return nil, fmt.Errorf("EC2 instance had invalid private address: %s (%s)", orEmpty(instance.InstanceId), ipAddress)
		}
		addresses = append(addresses, api.NodeAddress{Type: api.NodeInternalIP, Address: ip.String()})

		// Legacy compatibility: the private ip was the legacy host ip
		addresses = append(addresses, api.NodeAddress{Type: api.NodeLegacyHostIP, Address: ip.String()})
	}

	// TODO: Other IP addresses (multiple ips)?
	if !isNilOrEmpty(instance.PublicIpAddress) {
		ipAddress := *instance.PublicIpAddress
		ip := net.ParseIP(ipAddress)
		if ip == nil {
			return nil, fmt.Errorf("EC2 instance had invalid public address: %s (%s)", orEmpty(instance.InstanceId), ipAddress)
		}
		addresses = append(addresses, api.NodeAddress{Type: api.NodeExternalIP, Address: ip.String()})
	}

	return addresses, nil
}
```

The change is in the first ```if```

**Comment by dpratt** [comment] 2016-01-20 19:57
I'm getting the same on my hand-built CoreOS AWS cluster inside a private subnet. I've patched my copy of the kubelet to handle this error. @moserke - are you planning on submitting a PR with this change? If not, I'm happy to.

**Comment by jtblin** [comment] 2016-01-26 13:32
@moserke no I don't use public ip addresses. Looking at the code, I see this function is called by the api-server and kubelet so I was surprised I was not getting the error but it looks this code is different in v1.1.3 not v1.1.4 which I am running and take care of the case where the public ip is missing, hence why I am not getting it.

```
// NodeAddresses is an implementation of Instances.NodeAddresses.
func (aws *AWSCloud) NodeAddresses(name string) ([]api.NodeAddress, error) {
	instance, err := aws.getInstanceByNodeName(name)
	if err != nil {
		return nil, err
	}

	addresses := []api.NodeAddress{}

	if !isNilOrEmpty(instance.PrivateIpAddress) {
		ipAddress := *instance.PrivateIpAddress
		ip := net.ParseIP(ipAddress)
		if ip == nil {
			return nil, fmt.Errorf("EC2 instance had invalid private address: %s (%s)", orEmpty(instance.InstanceId), ipAddress)
		}
		addresses = append(addresses, api.NodeAddress{Type: api.NodeInternalIP, Address: ip.String()})

		// Legacy compatibility: the private ip was the legacy host ip
		addresses = append(addresses, api.NodeAddress{Type: api.NodeLegacyHostIP, Address: ip.String()})
	}

	// TODO: Other IP addresses (multiple ips)?
	if !isNilOrEmpty(instance.PublicIpAddress) {
		ipAddress := *instance.PublicIpAddress
		ip := net.ParseIP(ipAddress)
		if ip == nil {
			return nil, fmt.Errorf("EC2 instance had invalid public address: %s (%s)", orEmpty(instance.InstanceId), ipAddress)
		}
		addresses = append(addresses, api.NodeAddress{Type: api.NodeExternalIP, Address: ip.String()})
	}

	return addresses, nil
}
```

BTW `local-ipv4` will always be present (it's the internal private ip address) so I don't think the change is really needed for that part. Worth opening an issue and submitting a PR to master.

**Closed** 2016-02-09 07:44 UTC
Labels: area/cluster-lifecycle, area/platform/aws, component/kubelet, priority/P1, team/node

**Comment by Seraf** [comment] 2016-06-18 12:23
Hello, I don't understand why this issue has been closed ?
I still have errors with components trying to reach ip-xxx-xxx-xxx-xxx.mycompany.internal instead of using  ip-xxx-xxx-xxx-xxx.eu-west-1.compute.internal because I'm using a private dns hostname on the DHCP.

Then I'm stuck, I don't know what to do as I need this private zone and kubernetes use dns not resolvable (not sur that create a /16 dns records is a good idea).

Any idea about it please ? Does someone have a solution ?

Thanks

**Comment by jtblin** [comment] 2016-06-18 12:27
The fix was released in 1.2. Which version do you use?

**Comment by Seraf** [comment] 2016-06-18 12:33
@jtblin I'm using the 1.2.4 release

**Comment by jtblin** [comment] 2016-06-18 12:37
Maybe a different problem then. We use private dns hostname without any issue now so I can confirm this issue has been fixed. What are the exact logs that you are getting?

**Comment by Seraf** [comment] 2016-06-18 12:50
Ok, thanks ! Good to know.

I should have another issue, I will dig a little bit more and if it seems to be related to this issue I will post an update.

Thanks for your reactivity !

**Comment by Seraf** [comment] 2016-06-21 16:57
Hello,
It seems to be working now, I'm not using cloud-provider on my controller/master, so it uses the hostname as nodename. But I was able to use anything else than ip-10-XX-XX-XX.compute.internal as nodename for my workers. Does someone had success with it ?

**Comment by tj13** [comment] 2017-01-03 07:33
@Seraf 
any update for cloud-provider enabled with the custom EC2 nodename?

**Comment by poonia0arun** [comment] 2017-10-04 22:38
@Seraf  is this issue closed ? I am using k8s 1.6 version and I am seeing the same behavior.. any recommendation ?

**Comment by Seraf** [comment] 2017-10-05 06:43
I wasn't able to use custom hostnames but didn't try again since this issue.

**Comment by poonia0arun** [comment] 2017-10-05 17:25
@Seraf  oh okay so what would you recommend .. I am unable to use AWS cloud provider as a persistent volume for my current openshift installation due to this error...

**Comment by Calpicow** [comment] 2017-10-05 17:30
I have gotten it to work by using kube-apiserver flag `--kubelet-preferred-address-types=InternalIP`.

**Comment by Calpicow** [comment] 2017-10-05 17:31
I have gotten it to work by using kube-apiserver flag `--kubelet-preferred-address-types=InternalIP`.

**Comment by poonia0arun** [comment] 2017-10-05 17:44
@Calpicow  how can I use this variable during openshift installation ?

**Comment by Calpicow** [comment] 2017-10-05 20:35
@poonia0arun Sorry, not familiar with OpenShift.

**Comment by pat2man** [comment] 2017-10-06 04:36
@poonia0arun you can add something like this to your node-config.yaml:

```yaml
kubeletArguments:
  kubelet-preferred-address-types:
  - "InternalIP"
```

**Comment by poonia0arun** [comment] 2017-10-06 05:17
@pat2man  I tried updating openshift-ansible/roles/openshift_node/templates/node.yaml.v1.j2 file with mentioned value which didn't take it during ansible installation so later I tried to update the file manually with the right values which you had mentioned.. I am still not able to restart the node service.. if I don't use any cloud provider it works fine ...

**Comment by srflaxu40** [comment] 2017-10-30 23:07
I think this is still an issue with kubeadm v1.8.2.  There needs to be way more doc for AWS as a cloud provider, or maybe something out-of-the-box with kubeadm.  At the moment, it seems super under doc'ed, especially when many people have this use-case right?

**Comment by DanyC97** [comment] 2018-03-18 07:31
@pat2man i got same output like @apooniajjn when i added in `/etc/origin/node/node-config.yaml`

```
kubeletArguments:
  node-labels: []
  kubeletPreferredAddressTypes:
  -  'InternalIP'
```

```
origin-node[126248]: Invalid NodeConfig /etc/origin/node/node-config.yaml
origin-node[126248]: flag: Invalid value: "kubeletPreferredAddressTypes": is not a valid flag
```


@liggitt looking [here](https://github.com/kubernetes/kubernetes/issues/22063#issuecomment-251997481) i see  you are familiar with this code.
Any thoughts why on 

```
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dev4-cluster:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```
the flag is not present ?

**Comment by DanyC97** [comment] 2018-03-18 07:45
however if i do this i won't get any error following service restart.
```
kubeletArguments:
  node-labels: []
kubeletPreferredAddressTypes:
  -  'InternalIP'
```
i'll need to see if this makes the difference or is ignored ...

**Comment by lcd2002** [comment] 2019-03-02 02:27
I'm not familiar with github but how this can be re-opened and having read through the entire thread, I don't understand why this was closed.  I'm using 1.13.1 and this is causing a problem, and it is actually a bigger problem than most people are commenting here.  

Going back to the original post, the problem is our AWS environment is confined to a VPC and our company's domain, so hostname has to be my_hostname.my_company.net.  We can't use ip-10-xx-xx-xx name, but setting --cloud-provider=aws with kubelet looks for hostname in ip-10-xx-xx-xx format.  The problem is in order to be able to create persistent volumes in AWS (ebs or efs types), I need to set --cloud-provider=aws but I cannot do that because of the node name has to be in ip-10-xx-xx-xx format, and on it goes around the circle.  I say this is a bigger problem because I cannot create any persistent volume in my cluster as long as the node names are in my_host.my_company.net format but being able to create a persistent volume is almost an absolute necessity.
