### ISSUE TITLE
docker 1.9.1: No available IPv4 addresses on this network's address pools: bridge

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#21523] opened 2016-02-19 02:35 UTC
I ran into this issue twice today by running pod creation/deletion tests (100 pods per node).

After reading @aboch's comments in the issues (e.g., https://github.com/docker/docker/issues/18535#issuecomment-164494430), all three issues below have the same root cause.

- No available IPv4 addresses: https://github.com/docker/docker/issues/18527
- Same IP address for different containers: https://github.com/docker/docker/issues/18535
- Docker 1.9.1 breaks for custom bridges: https://github.com/docker/docker/issues/18145

After screening the fixes in libnetwork during that time, it seems like https://github.com/docker/libnetwork/pull/771 might be the fix (though I could be totally wrong given my limited knowledge on networking).

Since we may go with docker 1.9.1 for v1.2, any thoughts on how to proceed with this problem? 

(BTW, I couldn't find any existing issue on this. Feel free to close this one if there is already one)

/cc @dchen1107

**Comment by bprashanth** [comment] 2016-02-19 03:22
I think the meta problem is docker made bridge networks persistent across restarts in 1.9 and fixed several bugs between then and 1.10. If we just want the old behavior, we *might* be able to get away with just nuking local-kv.db on each restart. Some questions:

* What does `docker network  inspect bridge` show, 255 ips actually used?
* How often does one hit it with 30 pods per node?
* How hard do we need to hammer things to fix it? (gc all containers, restart docker, delete /var/lib/docker/network). 
* Any chance we can pull one of the 10.rc s that don't have content-addressable storage? 

There are some intense solutions like writing our own IPAM plugin or cloning libnetwork IPAM from 1.10 as a "plugin" (assuming it has the fix), but it's too high risk IMO without pushing the release.

@kubernetes/goog-cluster

**Comment by thockin** [comment] 2016-02-19 06:42
I'm all for nuking the DB - there's no real value to us in having
consistent IPs across docker restarts, certainly not if it is as buggy as
it sounds.

Is it fixed in 1.10?

**Comment by bprashanth** [comment] 2016-02-19 16:30
> Is it fixed in 1.10?

According to bug reports most persisting-networks-cross-restart problems are fixed in 1.10, but 1.10 also has content-addressable storage. It sounds like quite a few fixes made it into "1.9.2", which was later just converted into a 1.10-rc.

> I'm all for nuking the DB - there's no real value to us in having
consistent IPs across docker restarts, certainly not if it is as buggy as
it sounds.

I believe the only real reason they persist the bridge network cross restart is so cross host networks work consistently. This is a feature we don't care about.

IMO nuking a file across O(100) nodes is too hard to do manually, but we can consider just documenting this if it's rare enough with a lower number of pods per node.

**Comment by yujuhong** [comment] 2016-02-19 18:21
> What does docker network inspect bridge show, 255 ips actually used?

No, only ~92 ips were used around that time.

> How often does one hit it with 30 pods per node?

I have no idea how often this hits with 30 pods per node. 

> How hard do we need to hammer things to fix it? (gc all containers, restart docker, delete /var/lib/docker/network).

I did all three: GC'd all containers, deleted /var/lib/docker/network, and restarted docker. It didn't work.
Someone said nuking everything in /var/lib/docker worked: https://github.com/docker/docker/issues/18527#issuecomment-172232647


According to https://github.com/docker/docker/issues/18535, two containers can have the same IP addresses. I didn't check if it happened in my cluster, but it'd have been harder to notice.

**Comment by bprashanth** [comment] 2016-02-19 18:27
We need to figure out a reliable repro, with whatever max-pods we're going to ship with, to understand the impact. @kubernetes/goog-node what's the chance of just going back to 1.8?

**Comment by a-robinson** [comment] 2016-02-19 18:33
cc @zmerlynn @alex-mohr @roberthbailey

**Comment by zmerlynn** [comment] 2016-02-19 19:18
What are the chances of validating 1.10? :)

**Comment by onorua** [comment] 2016-02-20 15:36
1.8 has the same issue, we use `1.8.3` and got nasty problems like this. You can reproduce it easily with the pod with "wrong" liveness probe. It will be rescheduled between nodes until IP pool got used completely. So it actually doesn't matter how many pods do you have, but rather how often do you restart docker daemon or node completely. 
Docker asked to upgrade to 1.9 in https://github.com/docker/docker/issues/14788, which apparently not fixed. Any way you don't want to go libnetwork way - why do you need broken ip allocator in this case?

**Comment by bprashanth** [comment] 2016-02-20 22:59
@onorua 1.8 had its problems (eg: https://github.com/kubernetes/kubernetes/issues/19477) but those are just bugs that we need to live with, most of them have workarounds, and only occur with high number of pods per node or some obscure case like HostPort. 1.9 made the leap to using libnetwork with persistent storage for bridge networks and that brough a host of other networking issues. 

Whether we use libnetwork or not in the long run, we need to ensure that this release (which will use the default docker bridge plugin) is stable. Can you please file a different bug with your exact repro so we can consider the impact?

**Comment by bprashanth** [comment] 2016-02-20 23:01
> What are the chances of validating 1.10? :)

Isn't 1.10 going to be a major leap for hosted offerings like GKE because of the overhead involved in migrating to content-addressable storage?

**Comment by thockin** [comment] 2016-02-21 02:23
So to catch up a bit: the bug exists in d 1.9, probably not in d 1.10, but
d 1.10 is probably too late to validate for k 1.2.  The suggested
workarounds don't actually work (can we re-confirm that?).  It's possible
for pods to get the same IP.

We can and should add logic to Kubelet to detect multiple pods with the
same IP, even if it is incomplete (wrt non-kube containers).

The rest is pretty scary, if I understand correctly.  Someone tell me I am
misunderstanding?

**Comment by bprashanth** [comment] 2016-02-21 05:50
> The rest is pretty scary, if I understand correctly.  Someone tell me I am
misunderstanding?

We haven't invested the effort in getting a reliable repro. From what I can tell 1.9 is just bad for networking. @dchen1107 mentioned that we might still go back to 1.8. 

> We can and should add logic to Kubelet to detect multiple pods with the
same IP, even if it is incomplete (wrt non-kube containers).

Sounds practical. On detecting an IP conflict we should probably delete all participant pods, or sort by creation timestamp and leave the first. Not sure I'd want to put this in each podworker, @kubernetes/goog-node will have better suggestions.

If we're going to code a workaround, we can also detect when docker run starts returning 500s in a goroutine: 
```
while true:
    if docker run != 0 
         if ++count > threshold {
           node.unschedulable = true
         }
    else 
        docker kill
        count = 0
```

**Comment by dchen1107** [comment] 2016-02-22 19:00
I could reproduce the issue only during docker reboot test so far. Adding a little bit logging, one can see the docker daemon received SIGTERM and start to persistent current state, and refuse to start other containers by throwing such error message. Meanwhile, kubelet could pick up such error during next syncLoop, which is misleading here: 

```
Mon Feb 22 18:35:56 UTC 2016===========================start shutdown 
time="2016-02-22T18:36:01.360863832Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:01.360915500Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:01.574372128Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:01.574404895Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:07.085757941Z" level=error msg="Handler for POST /containers/create returned error: sql: database is closed" 
time="2016-02-22T18:36:07.085813206Z" level=error msg="HTTP Error" err="sql: database is closed" statusCode=500 
time="2016-02-22T18:36:07.132089270Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/6f7b897221406a714859f7e68376095952756c04c358e363cc00d5ee510f4f3e/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/6f7b897221406a714859f7e68376095952756c04c358e363cc00d5ee510f4f3e/mqueue: no such file or directory" 
time="2016-02-22T18:36:07.148072161Z" level=error msg="Handler for POST /containers/6f7b897221406a714859f7e68376095952756c04c358e363cc00d5ee510f4f3e/start returned error: Cannot start container 6f7b897221406a714859f7e68376095952756c04c358e363cc00d5ee510f4f3e: no available IPv4 addresses on this network's address pools: bridge (3d1b6ce1539ccaf0b6359dba070bd8ba91695f33a100805fda4e2934df239f13)" 
time="2016-02-22T18:36:07.148122284Z" level=error msg="HTTP Error" err="Cannot start container 6f7b897221406a714859f7e68376095952756c04c358e363cc00d5ee510f4f3e: no available IPv4 addresses on this network's address pools: bridge (3d1b6ce1539ccaf0b6359dba070bd8ba91695f33a100805fda4e2934df239f13)" statusCode=500 
time="2016-02-22T18:36:08.087058337Z" level=error msg="Handler for POST /containers/create returned error: sql: database is closed" 
time="2016-02-22T18:36:08.087097389Z" level=error msg="HTTP Error" err="sql: database is closed" statusCode=500 
time="2016-02-22T18:36:08.112261109Z" level=error msg="Error during graph storage driver.Cleanup(): device or resource busy" 
Mon Feb 22 18:36:16 UTC 2016 =====================start startup 
time="2016-02-22T18:36:17.191851817Z" level=warning msg="Your kernel does not support swap memory limit." 
time="2016-02-22T18:36:17.191956195Z" level=warning msg="Your kernel does not support kernel memory limit." 
time="2016-02-22T18:36:17.192046995Z" level=warning msg="Your kernel does not support cgroup cfs period" 
time="2016-02-22T18:36:17.192067907Z" level=warning msg="Your kernel does not support cgroup cfs quotas" 
time="2016-02-22T18:36:18.218491756Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:18.218535622Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:18.548414290Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:18.548480597Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:18.786482291Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:18.786548580Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:19.025413435Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
time="2016-02-22T18:36:19.025475206Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-02-22T18:36:19.881451761Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 
```

Second experimental I had is after docker back to normal stage, check if docker daemon will cap the number of containers due to mistaken No available IPv4 addresses issue:

1) before experiemental, on the same node, there are 17 kube-docker containers running. 
```
# docker ps | wc -l
17
```
2) I quickly verify docker daemon by starting more than 100 containers manually
```
# docker ps | wc -l
160
# docker ps -a | wc -l
195
```

But I didn't see we never run into such issue when docker is not at restart stage, but it is rare. I didn't see such issue reported through e2e tests at all.

**Comment by dchen1107** [comment] 2016-02-22 19:03
Sent too quickly...

Since it is rare, and it only failed when a docker creation state, not affect all running containers, I inclined to not revert back docker 1.9.1 release. Instead, we should document this as known issue. 
The workaround I have is removing docker network checkpoint file.

**Comment by bprashanth** [comment] 2016-02-22 19:16
Overall I agree with 1.9+workaround+documentation. I'm just trying to figure out the workarounds.

> I didn't see such issue reported through e2e tests at all.

I'm not sure how conclusive this is since we don't pay much attentiont to soak and regular e2es are  running < 30 pods per node.

> The workaround I have is removing docker network checkpoint file.

That is also bound to help with: https://github.com/kubernetes/kubernetes/issues/20916#issuecomment-186937279, but I think ordering will be imporant:
- stop docker
- docker starts persisting state
- docker finished persisting state
- we delete checkpoint
- start docker

How do we detect step 2? 

> Second experimental I had is after docker back to normal stage

In the initial report, docker never came back to a normal stage. In fact it didn't even return after removing the checkpoint file. So do we need to totally avoid any docker request while it's persisting state, or risk that it gets wedged? If so, how do we transmit this to the kubelet?

**Comment by bprashanth** [comment] 2016-02-22 19:21
> How do we detect step 2/3?

I guess just stop, poll till docker pid is gone, rm -rf /var/lib/network/files/*, start; should work.

**Comment by vishh** [comment] 2016-02-22 19:28
As mentioned a couple of time earlier in this issue, can we instead switch to v1.8.3 and instead focus our energy on validating docker v1.10 and fixing possible issues with that release?

**Comment by dchen1107** [comment] 2016-02-22 19:35
>> I guess just stop, poll till docker pid is gone, rm -rf /var/lib/network/files/*, start; should work. 

The users could have configured their docker network checkpoint directory. Are we going to detect that to complicate our simple babysitter script? And why if it is rare issue?

**Comment by yujuhong** [comment] 2016-02-22 19:48
> As mentioned a couple of time earlier in this issue, can we instead switch to v1.8.3 and instead focus our energy on validating docker v1.10 and fixing possible issues with that release?

+1  docker itself gave up on  v1. and just moved on with v1.10. I think we've spent too much time investigating and working around the *known* issues of docker v1.9.

**Comment by bprashanth** [comment] 2016-02-22 19:52
> The users could have configured their docker network checkpoint directory. Are we going to detect that to complicate our simple babysitter script? And why if it is rare issue?

I'm not comfortable shipping 1.9 without a workaround if there is potential that the node is hosed (i.e docker is wedged and no amout of restarting brings it back). Running into this on O(10) nodes in a 100-1000 node cluster will be a bad experience.

**Comment by yujuhong** [comment] 2016-02-22 20:04
> I could reproduce the issue only during docker reboot test so far.

In my case, this is how I reproduced it:
 1. build fresh test cluster
 2. start 100 pause pods, wait until the pods are running and delete them.
 3. repeat (2) if everything works fine

The test usually fails the second time if it's going to fail. Note that I didn't explicitly kill docker, and supvervisord showed no sign of docker being killed unexpectedly.
However, I think @dchen1107 may be right about the docker restart being the cause. The thing is that kubelet restarts docker to configure cbr0 so it's possible that the network db has already in a bad state during that time.

**Comment by dchen1107** [comment] 2016-02-22 20:18
I am totally open to any opinion on this, but @vishh @bprashanth and @yujuhong how much confidence you guys have with docker 1.10 release here? 

We validated docker 1.9.X release since Oct, 2015 (https://github.com/kubernetes/kubernetes/issues/16110). We performed functional tests, integration tests and performance validation tests. 

Our entire jenkins project moves to docker 1.9.1 test more than 2 weeks for continuous and soaking tests. We used to find tons of issues caused by upgrade through salt and restart docker initially, especially corrupted docker network /  storage checkpoint files (#20995). After we baked docker binary into our image, we didn't run into that problem. 

On another side, we have docker issues with all previous release. For example, with kubelet 1.1 release, we have several documented docker issues against docker 1.8.3:

https://github.com/kubernetes/kubernetes/issues/15747#issuecomment-153201222
https://github.com/kubernetes/kubernetes/issues/10959

**Comment by thockin** [comment] 2016-02-22 20:39
I'll take known issues over unknown issues.  I lean towards declaring 1.9 DOA and telling people to use 1.8 or 1.10, and press on the 1.10 qual and docs (regarding the storage conversion).

**Comment by bprashanth** [comment] 2016-02-22 21:05
We're waiting for https://github.com/kubernetes/kubernetes/pull/21703. I believe the problems with 1.9 are surfacing as various node not ready/cluster timeout bugs (https://github.com/kubernetes/kubernetes/issues/20916#issuecomment-186937279). We're hoping restarting docker gracefully mitigates all of them. If that happens, this becomes just another (vaguely understood) docker bug.

**Comment by dchen1107** [comment] 2016-02-22 21:07
@thockin I want to clarify the issue reported here a little bit more:

* AFAIK, it is a rare case. Besides our own tests performed locally to stress the node, we didn't observe such issue through e2e tests. Talked to @yujuhong she couldn't reliably reproduce the issue even stretch our node very much.
* The problem doesn't hurt any running pods / docker containers. 
* When we hit the issue, the arriving pod / container will fail with proper container creation error message which propagate to the client. This is different from other issues like hairpin mode one, which doesn't have any visibility / introspection information to the end users. 

I am ok to back 1.8.3, not 1.10.X. We did fix forward compatibility issues in kubelet side to go along with docker 1.10.X. But most issues you observed here with 1.9.1, you will hit with 1.10.X, not even mention those new issues introduced in 1.10 release and image format ones.

**Comment by mml** [comment] 2016-02-22 21:49
@dchen1107 I think we are seeing this show up in e2e tests.  #20916

**Comment by bprashanth** [comment] 2016-02-23 01:53
We're hammering the network checkpoint: https://github.com/kubernetes/kubernetes/pull/21727. Hopefully that doesn't cause more crashing or burning.

**Comment by dchen1107** [comment] 2016-02-24 01:17
#21727 was merged yesterday, which removes the potential corrupted docker checkpoint file between stop and start the docker daemon. Along with two more other pr merged yesterday, we didn't observe any node bootup issue. 

But I have to confess that we might still run into docker/docker#18527, but it should be either transient which is what I recorded at https://github.com/kubernetes/kubernetes/issues/21523#issuecomment-187321130 or very rare during docker stable running state.

**Comment by yujuhong** [comment] 2016-02-24 19:04
Reopening since there is a recent occurrence in the scalability suite (#21878)

**Comment by wojtek-t** [comment] 2016-02-24 20:04
Pasting from a different #21878 

>
@dchen1107 decided to close it yesterday after having the workarounds merged, even though this could still happen rarely. See her comment: #21523 (comment)

@yujuhong - thanks for clairification; I think we need some more workaround, because what happened effectively in our scalability suite is that we lost the node completely. This shoudn't happen for customers paying for them (and it's also annoying for us, because it's blocking merge-bot).

**Comment by dchen1107** [comment] 2016-02-25 18:17
@wojtek-t I scan through the link you posted at #21878, the issue matches my initial thoughts here. From both docker and kubelet logs, one can see that right after kubelet configured cbr0, and restart docker, docker run into this issue. 

Related docker log:
```
time="2016-02-24T13:42:57.411957236Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-24T13:43:07.850507637Z" level=warning msg="Your kernel does not support swap memory limit." 
time="2016-02-24T13:43:07.850601070Z" level=warning msg="Your kernel does not support kernel memory limit." 
time="2016-02-24T13:43:07.850667170Z" level=warning msg="Your kernel does not support cgroup cfs period" 
time="2016-02-24T13:43:07.850686520Z" level=warning msg="Your kernel does not support cgroup cfs quotas" 
time="2016-02-24T13:43:07.868014734Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to allocate gateway (10.245.16.1): No available addresses on this pool" 
time="2016-02-24T13:43:12.805545984Z" level=error msg="Handler for GET /containers/docker-daemon/json returned error: no such id: docker-daemon" 
time="2016-02-24T13:43:12.805597663Z" level=error msg="HTTP Error" err="no such id: docker-daemon" statusCode=404 
time="2016-02-24T13:43:12.810437334Z" level=error msg="Handler for GET /containers/kubelet/json returned error: no such id: kubelet" 
time="2016-02-24T13:43:12.810464891Z" level=error msg="HTTP Error" err="no such id: kubelet" statusCode=404 
time="2016-02-24T13:43:12.813835616Z" level=error msg="Handler for GET /containers/system/json returned error: no such id: system" 
time="2016-02-24T13:43:12.813885310Z" level=error msg="HTTP Error" err="no such id: system" statusCode=404 
time="2016-02-24T13:43:17.633028616Z" level=error msg="Handler for GET /images/gcr.io/google_containers/pause:2.0/json returned error: No such image: gcr.io/google_containers/pause:2.0" 
time="2016-02-24T13:43:17.633090851Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/pause:2.0" statusCode=404 
time="2016-02-24T13:43:17.635438706Z" level=error msg="Handler for GET /images/gcr.io/google_containers/pause:2.0/json returned error: No such image: gcr.io/google_containers/pause:2.0" 
time="2016-02-24T13:43:17.635514508Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/pause:2.0" statusCode=404 
time="2016-02-24T13:43:18.228023605Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/dfc9fca7b90bf15ccf7967a53cac1b5ea277379fb4408e20ef6d2ce5247dde5c/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/dfc9fca7b90bf15ccf7967a53cac1b5ea277379fb4408e20ef6d2ce5247dde5c/mqueue: no such file or directory" 
time="2016-02-24T13:43:18.243183627Z" level=error msg="Handler for POST /containers/dfc9fca7b90bf15ccf7967a53cac1b5ea277379fb4408e20ef6d2ce5247dde5c/start returned error: Cannot start container dfc9fca7b90bf15ccf7967a53cac1b5ea277379fb4408e20ef6d2ce5247dde5c: no available IPv4 addresses on this network's address pools: bridge (c6fb853e0c423b4b3a447bbecf0745690d593ff85e712e59a86f2bef88b768a0)" 
```

I checked code at https://github.com/kubernetes/kubernetes/blob/699c80b75226e6adae67573569c386a62a578bae/pkg/kubelet/container_bridge.go#L49

Kubelet simply call service docker restart without removing potential corrupted docker checkpoint file here. I can send a fix shortly.

**Comment by wojtek-t** [comment] 2016-02-25 18:49
Thanks a lot for looking into it @dchen1107 . Looking forward to see the fix :)

**Comment by mml** [comment] 2016-02-26 00:59
FYI this is also blocking me trying to debug some failing/flaky tests.

**Comment by bprashanth** [comment] 2016-02-26 01:32
@mml a consistent repro would help a lot. Does removing /var/lib/docker/network and restarting docker fix it?

**Comment by wojtek-t** [comment] 2016-02-26 13:29
@bprashanth - from the comment above from @dchen1107 https://github.com/kubernetes/kubernetes/issues/21523#issuecomment-188916231 it seems she knows what is happening - she promised to send a fix for it

**Comment by bprashanth** [comment] 2016-02-26 19:00
@wojtek-t IIUC the fix is to apply the mitigatation steps we came up with earlier on (rm /var/lib/docker/network) when restarting docker at configureCBR0 time as well. There have been reports that this *doesn't* consistently fix the problem, but we don't have a reliable repro of such a case. Having that would help greatly.

**Comment by mml** [comment] 2016-02-26 19:07
I haven't tried to manually fix the nodes, but I will confirm whether or not that works on my cluster.

**Comment by mml** [comment] 2016-02-26 19:27
@bprashanth @dchen1107 this does not work.  First I SIGSTOP docker-checker.sh, stop docker, rm -rf /var/lib/docker/network, then start docker.  I then see the same error messages when trying to pull docker images:

```console
time="2016-02-26T19:25:27.881477063Z" level=error msg="Handler for GET /images/gcr.io/google_containers/fluentd-elasticsearch:1.14/json returned error: No such image: gcr.io/google_containers/fluentd-elasticsearch:1.14" 
time="2016-02-26T19:25:27.881524751Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/fluentd-elasticsearch:1.14" statusCode=404 
```

**Comment by bprashanth** [comment] 2016-02-26 19:45
do you still see "No available IPv4 addresses on this network's address pools"? are containers actually starting? I think image 404 for image pulls are different (docker could apparently contact the server and retrieve the 404)

**Comment by dchen1107** [comment] 2016-02-26 21:34
@mml failing pull image is different issue. Here is related to ip allocation from docker.

**Comment by mml** [comment] 2016-02-26 21:49
The 404 does seem to indicate that we contacted gcr.io and actually got a 404 from it.  OTOH, I get this consistently when trying to bring up an e2e cluster and if I try to pull the exact same image from my workstation it works fine.  I'm investigating further with the GCR folks.

**Comment by gmarek** [comment] 2016-03-01 13:30
I run into it on one of 3-cluster Nodes after running MaxPods test a couple of times (which seems consistent with repro scenario that @yujuhong suggested). I nuked the cluster, but I have all the logs if someone is interested.

```
 2m	2m	1	{kubelet e2e-test-gmarek-minion-7ss7}		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container d6333a08b316350dae00931729e33e59498915c751a5673a9588c08204b4a863: no available IPv4 addresses on this network's address pools: bridge (a2cece0bb5703fe5c62b73b8cc59c4d58a8e0560926916a54a6648ed71bdad35)\n"
```

**Comment by gmarek** [comment] 2016-03-01 14:34
What's worst in this, is that Kubelet keeps claiming that it's healthy when this happens, so more pods are scheduled on it.

**Comment by thockin** [comment] 2016-03-02 19:02
Dawn or Yu-Ju - anything I can do to help?  This is tough one...

**Comment by dchen1107** [comment] 2016-03-02 19:07
@gmarek Can you send the logs on my way? Thanks!

**Comment by bprashanth** [comment] 2016-03-02 21:17
We merged https://github.com/kubernetes/kubernetes/pull/22293 and expect this to be v. rare. If that's not the case (because honestly we haven't 100% understood the core problem and haven't invested time in a reliable repro) we need to discuss.

**Comment by dchen1107** [comment] 2016-03-02 23:52
#21703 and #22293 are merged to remove potential corrupted docker checkpoint files on every docker daemon restart. I can reproduce the issue very easily at node bootup time without those two prs. 

But like I mentioned above, we might still run into this issue with churn of massive docker container creation and deletion. It should be very rare, and when we run into that issue:

* All pre-existing containers are running happily without any issue
* When docker run into this issue, the number of max IPs on a node is capped at a fix number N. Any running container requesting a IP allocation (PodInfra container in our case) exit, a new container with IP allocation request will succeed. 
* When docker run into this issue, the error message of "no available IPv4 addresses on this network's address pools" is properly propagated to the client by kubelet. It is not a hidden issue. 
* To workaround the issue, one can shutdown the docker daemon and remove the corrupted checkpoint file. But this means all running containers on a node will be killed.

In this case, I am going to close this issue and document it as known docker issue for 1.2 release.

**Comment by dchen1107** [comment] 2016-03-02 23:52
cc/ @thockin @bgrant0607 @bprashanth

**Comment by thockin** [comment] 2016-03-03 00:01
I want to see a doc that covers Docker versions and known issues, so that
WHEN this blows up, we can point people to it.  Sadly, we're stuck with a
string of Docker releases, none of which are "good".  It sounds like 1.9 is
the "least bad".

**Comment by mml** [comment] 2016-03-03 00:06
> I want to see a doc that covers Docker versions and known issues, so that
> WHEN this blows up, we can point people to it.

+1 @thockin

**Comment by bgrant0607** [comment] 2016-03-03 04:11
ref #21000

**Comment by gmarek** [comment] 2016-03-30 22:58
This causes failures in SchedulerPredicates MaxPods test (#19681) - all recent failures are caused by 'No available IPv4 addresses on this network's address pools: bridge' error.

**Comment by gmarek** [comment] 2016-04-01 15:45
It's causing test flakyness, so adding flake label.

**Comment by bprashanth** [comment] 2016-04-01 15:55
@gmarek can you post logs? I looked through https://github.com/kubernetes/kubernetes/issues/19681#issuecomment-192073203 but nothing jumped out. The ipv4 error can happen on startup, and might show up in events, but it shouldn't persist. It shouldn't cause the node to flip to not ready, which is the failure mode I'd expect to cause the scheduler to fail to find a fit for 110 x 3 pods.

**Comment by gmarek** [comment] 2016-04-01 16:05
It's e.g. in http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/883/consoleText

```
Mar 29 14:40:06.387: INFO: At 2016-03-29 14:30:35 -0700 PDT - event for maxp-224: {kubelet gke-jenkins-e2e-3f0cce14-node-vjhz} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 7e4f8063bfb18520933868875fe510701457ae3860c0e42fc9d832cc7c6e7008: no available IPv4 addresses on this network's address pools: bridge (3841504ca2d560fe54163ebd4832ad2a00701b217c6264575a291989571010e6)\n"
```

**Comment by yujuhong** [comment] 2016-04-01 18:25
> @gmarek can you post logs? I looked through #19681 (comment) but nothing jumped out. The ipv4 error can happen on startup, and might show up in events, but it shouldn't persist. It shouldn't cause the node to flip to not ready, which is the failure mode I'd expect to cause the scheduler to fail to find a fit for 110 x 3 pods.

ipv4 error will persist once it happens from the past experiences. The node will stay ready but none of the pods can become running beyond that point.

**Comment by bprashanth** [comment] 2016-04-01 18:29
I think Dawn concluded that it was a startup time thing in > 90% of the cases, and we can solve this by nuking the checkpoint file when we restart docker for cbr0 in:

> #21703 and #22293 are merged to remove potential corrupted docker checkpoint files on every docker daemon restart. I can reproduce the issue very easily at node bootup time without those two prs.

If it's not a startup time thing I think we should be smarter about our docker health check and continue to restart+nuke checkpoint when we detect it, till we roll docker version forward.

**Comment by yujuhong** [comment] 2016-04-01 18:39
Yes, that was Dawn's conclusion. It could be that the docker checker script wasn't doing its job correctly, or that this is actually a startup problem.

> If it's not a startup time thing I think we should be smarter about our docker health check and continue to restart+nuke checkpoint when we detect it, till we roll docker version forward.

We should improve or docker health check in general. On the other hand, I think upgrading the docker version may even come before that.

**Comment by dchen1107** [comment] 2016-04-06 19:07
I am closing this issue for now. We are going to switch to docker 1.10, which should contain fix for this bug claimed by docker. Also the cluster team is working on to switch to cni solution for ip allocation, so that soon we will remove the dependency here. cc/ @freehan

**Closed by dchen1107** 2016-04-06 19:07 UTC
Labels: kind/flake, priority/P0, team/cluster, team/node
