### ISSUE TITLE
Panics in controller manager lookup cache

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#26376] opened 2016-05-26 19:50 UTC
I was just trying to delete a DaemonSet and got a ton of these, edited for brevity. They went away when I restarted the controller manager. The cluster had been updated to HEAD yesterday from two-month old binaries.

```
19:40:39 m0 k-c-m: E0526 19:40:39.692797   30456 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/asm_amd64.s:472
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/panic.go:426
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/panic.go:45
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/sigpanic_unix.go:24
19:40:39 m0 k-c-m: /usr/local/go/src/container/list/list.go:169
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/groupcache/lru/lru.go:79
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/lookup_cache.go:77
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:281
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:699
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:483
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:661
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:207
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:248
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:252
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:228
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/asm_amd64.s:1998
19:40:39 m0 k-c-m: E0526 19:40:39.693053   30456 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/asm_amd64.s:472
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/panic.go:426
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/panic.go:45
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/sigpanic_unix.go:24
19:40:39 m0 k-c-m: /usr/local/go/src/container/list/list.go:169
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/groupcache/lru/lru.go:79
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/lookup_cache.go:77
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:281
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:699
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:483
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:661
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:207
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:248
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:252
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go:228
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67
19:40:39 m0 k-c-m: kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47
19:40:39 m0 k-c-m: /usr/local/go/src/runtime/asm_amd64.s:1998
19:40:40 m0 k-c-m: I0526 19:40:40.697247   30456 controller.go:546] Failed deletion, decrementing expectations for set "kube-system"/"fluentd-logging"
19:40:40 m0 k-c-m: E0526 19:40:40.697274   30456 controller.go:548] unable to delete pods: pods "fluentd-logging-269i5" not found
```

**Comment by therc** [comment] 2016-05-26 19:54
Looking at the code at the lines in controller.go, it seems to be indeed deep in the bowels of syncDaemonSet() and the last line from the controller manager is:

`if obj, cached := dsc.lookupCache.GetMatchingObject(pod); cached {`

**Comment by therc** [comment] 2016-05-31 15:01
And it happened again. I was trying to kill and restart fluentd because it got stuck once more.

**Comment by mikedanese** [comment] 2016-05-31 17:41
cc @mqliang can you take a look?

**Comment by mikedanese** [comment] 2016-05-31 18:14
This is happening deep in the groupcache/stdlib list code. If this is not a bug in either of those and we are in fact misusing the groupcache api, we are likely missusing it in pkg/controller/lookup_cache.go.

cc @wojtek-t @lavalamp

**Comment by mikedanese** [comment] 2016-05-31 18:15
@therc what version of golang are the binaries compiled with?

**Comment by therc** [comment] 2016-05-31 18:30
$ go version
go version go1.6 linux/amd64

**Comment by lavalamp** [comment] 2016-06-03 00:03
I believe it's a threading bug. the lookup cache could call LRU's Get method concurrently, but it is calling this: https://golang.org/pkg/container/list/#List.MoveToFront which does not look threadsafe.

@mqliang do you have time to make a patch?

**Comment by therc** [comment] 2016-06-03 00:07
Since this is happening to my cluster all the time, I can give it a shot tomorrow morning, in exchange for a review or two of my.oldest pending PRs. :-)

**Comment by lavalamp** [comment] 2016-06-03 00:13
@therc haha--none of them are assigned to me but I can annoy someone in person for you ;)

**Comment by therc** [comment] 2016-06-03 00:16
Actually, two need rebasing, so that only leaves us another two.

**Comment by dims** [comment] 2016-06-03 02:24
@mqliang @249043822 - Is this issue caused by this change? https://github.com/kubernetes/kubernetes/commit/49f4f242a8fd1ff5b4d5e73dda3948005a529f63 

(since LRU cache modifies the linked list even for a get, we should use WLock for both read and writes?)

**Comment by dims** [comment] 2016-06-03 02:25
LOL looks like @mqliang beat me with a PR by 2 mins

**Comment by lavalamp** [comment] 2016-06-03 17:24
#26758 should fix this problem (and I LGTMd it) but I think we should also add a test.

**Comment by dims** [comment] 2016-06-04 02:29
@lavalamp Do we close this issue? or keep it open for test. Also do we need P0 priority for just the test?

**Comment by lavalamp** [comment] 2016-06-04 02:45
Let's keep it open and I'll reduce to p1 when at a real computer.

**Comment by mikedanese** [comment] 2016-06-06 15:48
@mqliang thanks for looking into this.

**Comment by kargakis** [comment] 2017-01-07 21:36
Should be fixed by https://github.com/kubernetes/kubernetes/pull/26758, closing.

**Closed by kargakis** 2017-01-07 21:36 UTC
Labels: kind/bug, priority/important-soon, team/control-plane (deprecated - do not use)
