### ISSUE TITLE
Restart test - nodes disappear

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#10822] opened 2015-07-07 12:29 UTC
```
Restart 
  should restart all nodes and ensure all nodes and pods recover
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/restart.go:127
[BeforeEach] Restart
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/restart.go:70
>>> testContext.KubeConfig: /usr/local/google/home/biskup/.kube/config
[It] should restart all nodes and ensure all nodes and pods recover
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/restart.go:127
STEP: ensuring all nodes are ready
INFO: Successfully found 2 nodes
INFO: Waiting up to 9.830392413s for node e2e-test-biskup-minion-1p95 readiness to be true
INFO: Waiting up to 9.830392413s for node e2e-test-biskup-minion-4073 readiness to be true
INFO: Node e2e-test-biskup-minion-1p95 condition 1/1: type: Ready, status: True
INFO: Successfully found node e2e-test-biskup-minion-1p95 readiness to be true
INFO: Node e2e-test-biskup-minion-4073 condition 1/1: type: Ready, status: True
INFO: Successfully found node e2e-test-biskup-minion-4073 readiness to be true
INFO: Got the following nodes before restart: [e2e-test-biskup-minion-1p95 e2e-test-biskup-minion-4073]
STEP: ensuring all pods are running and ready
INFO: Waiting up to 20s for the following 0 pods to be running and ready: []
INFO: Wanted all 0 pods to be running and ready. Result: true. Pods: []
STEP: restarting all of the nodes
STEP: getting the name of the template for the managed instance group
INFO: MIG group e2e-test-biskup-minion-group using template: e2e-test-biskup-minion-template
STEP: starting the MIG rolling update to e2e-test-biskup-minion-template
INFO: Started MIG rolling update; ID: 46aac7c6-15ca-4f54-9632-169f83bf0e01
STEP: polling the MIG rolling update (46aac7c6-15ca-4f54-9632-169f83bf0e01) until it completes
INFO: Waiting up to 10m0s for MIG rolling update to complete.
INFO: Waiting for MIG rolling update: 0/2 instances updated (21.02613445s elapsed)
INFO: Waiting for MIG rolling update: 0/2 instances updated (41.341414939s elapsed)
INFO: Waiting for MIG rolling update: 0/2 instances updated (1m0.980912232s elapsed)
INFO: Waiting for MIG rolling update: 0/2 instances updated (1m21.424383794s elapsed)
INFO: Waiting for MIG rolling update: 1/2 instances updated (1m41.386619632s elapsed)
INFO: Waiting for MIG rolling update: 1/2 instances updated (2m1.355138723s elapsed)
INFO: Waiting for MIG rolling update: 1/2 instances updated (2m20.964236407s elapsed)
INFO: Waiting for MIG rolling update: 1/2 instances updated (2m40.94024304s elapsed)
INFO: Waiting for MIG rolling update: 1/2 instances updated (3m0.947456466s elapsed)
INFO: Waiting for MIG rolling update: 2/2 instances updated (3m20.918004525s elapsed)
INFO: MIG rolling update complete after 3m20.918050979s
STEP: ensuring all nodes are ready after the restart
INFO: expected to find 2 nodes but found only 0 (10.04124215s elapsed)
INFO: expected to find 2 nodes but found only 0 (15.080708762s elapsed)
...
```

Nodes disappeared. I suppose the shutdown script unregistered them. Then they never registered.

From nodes:

```
biskup@e2e-test-biskup-minion-1p95:~$ sudo docker ps
FATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

docker logs:

```
time="2015-07-07T09:47:10Z" level=info msg="Received signal 'terminated', starting shutdown of docker..." 
time="2015-07-07T09:47:11Z" level=info msg="+job init_networkdriver()" 
time="2015-07-07T09:47:11Z" level=info msg="+job serveapi(unix:///var/run/docker.sock)" 
time="2015-07-07T09:47:11Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)" 
no such network interface
time="2015-07-07T09:47:11Z" level=info msg="-job init_networkdriver() = ERR (1)" 
time="2015-07-07T09:47:11Z" level=fatal msg="Shutting down daemon due to errors: no such network interface" 
```

kubelet:

```
E0707 09:47:14.414859    2847 reflector.go:136] Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
E0707 09:47:14.414966    2847 reflector.go:136] Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
```

Just before these tests I created another GKE cluster (this was on a e2e cluster). Maybe GKE interfered?

**Comment by marekbiskup** [comment] 2015-07-07 12:30
```
biskup@e2e-test-biskup-minion-1p95:~$ ls -l /var/run/docker.sock
ls: cannot access /var/run/docker.sock: No such file or directory
```

**Comment by marekbiskup** [comment] 2015-07-07 12:30
I have no idea what happened. I still have the cluster, if someone wants to get more logs.

**Comment by roberthbailey** [comment] 2015-07-07 15:00
/cc @dchen1107 

Is the docker process not running? monit should be configured to restart it when it's down (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/monit/docker) so if that isn't working then that's a cause for concern.

**Comment by marekbiskup** [comment] 2015-07-09 12:47
I forgot about the issue and destroyed the cluster.
I'll try to reproduce it.

**Comment by stevenbrichards** [comment] 2015-07-15 04:06
I'm able to reproduce this as well
```
Waiting for /var/run/docker.sock
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] +job init_networkdriver()
no such network interface
INFO[0000] -job init_networkdriver() = ERR (1)
Waiting for /var/run/docker.sock
FATA[0000]Shutting down daemon due to errors: no such network interface
```

**Comment by yujuhong** [comment] 2017-06-02 00:59
Closing the issue since it's ~2-year old, and a test issue.

**Closed by yujuhong** 2017-06-02 00:59 UTC
Labels: area/test, area/test-infra, priority/backlog, sig/cluster-lifecycle, sig/node
