### ISSUE TITLE
List API does not return `kind` and `apiVersion` for each result

### ISSUE THREAD

**Issue by asankov-cb** [kubernetes/kubernetes#98925] opened 2021-02-09 17:24 UTC
The response for a resource differs when called via `Get` or `List` API. The difference is that when fetched via `List` the `kind` and `apiVersion` fields are missing for the elements of the response.

This might not be a big deal, because you know what resource you are trying to get, but it causes us some problems when using `Watch` APIs via `client-go`. We use the `watch.Interface` in a generic way, where we have a sort of factory method that builds a `watch.Interface` client for each resource type and when we call that we are not sure what is the type we are working with (because `ResultChan()` returns `Event` which has the generic `runtime.Object`). if we call `GetObjectKind()` on that `runtime.Object` that is empty, because the API has not returned these values and `client-go` has not populated the fields. Thus we have to either do a type matching (`switch (object.type)`) or some other shenanigans to get the actual type.

Also, the [Kubernetes API guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources) state:
> All JSON objects returned by an API MUST have the following fields:
kind: a string that identifies the schema this object should have
apiVersion: a string that identifies the version of the schema the object should have

so this may or may not be viewed as a violation of this rule. 

Also, according to the [API spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#podlist-v1-core) the return type of List Pods (for example) is `PodList` which has `items` which is just a `[]Pod` (which should have `kind` and `apiVersion`)

I realise this can be so on purpose (for optimisation reasons, for example), if so, I would just like to know? If not, and you think this is a real issue I am willing to work on it and provide a fix.

An alternative would be to fix this in `client-go`, and add the fields manually (in a generic way) after the initial serialisation.

**What happened**:
List API operations do not return the `kind` and `apiVersion` for each element of `items`
**What you expected to happen**:
List API operations returns the `kind` and `apiVersion` for each element of `items`
**How to reproduce it (as minimally and precisely as possible)**:
```
$ curl http://127.0.0.1:8082/api/v1/namespaces/default/pods/myPod
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {...},
  "spec": {...},
  "status": {...}
}


$ curl http://127.0.0.1:8082/api/v1/namespaces/default/pods/
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "100948"
  },
  "items": [{
       "metadata": {...},
       "spec": {...},
       "status": {...}
}]
# `kind` and `apiVersion` are missing in the elements of `items`
```
**Anything else we need to know?**: Is this so on purpose? Some optimisation for less data send over the wire or something like this?

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: local kind cluster
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): 
```
Linux kind-control-plane 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kind

**Comment by neolit123** [comment] 2021-02-09 19:29
duplicate of https://github.com/kubernetes/kubernetes/issues/3030
and related to https://github.com/kubernetes/kubernetes/issues/80609

there is a WIP PR for this here:
https://github.com/kubernetes/kubernetes/pull/80618

please comment on the linked issues.
thanks

/close

**Closed** 2021-02-09 19:29 UTC
Labels: kind/bug, needs-triage, sig/api-machinery
