### ISSUE TITLE
Failure cluster [e365d8af...]: HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#128058] opened 2024-10-14 15:05 UTC
##### Error text:
```
[FAILED] wait for pod pod1 timeout, err:Told to stop trying after 2.030s.
The phase of Pod pod1 is Failed which is unexpected.
In [It] at: k8s.io/kubernetes/test/e2e/network/hostport.go:219 @ 10/06/24 08:23:08.362

```
#### Recent failures:
[10/12/2024, 1:48:08 AM ci-kubernetes-kind-conformance-parallel-ipv6](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1844887536313307136)
[10/11/2024, 3:44:11 PM ci-kubernetes-kind-network-nftables-ipv6](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-network-nftables-ipv6/1844735533264146432)
[10/6/2024, 9:54:37 AM ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-28-1-29](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-28-1-29/1842835512356769792)
[10/5/2024, 8:01:33 PM cloud-provider-azure-conformance-vmss-capz](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/cloud-provider-azure-conformance-vmss-capz/1842625879830695936)
[10/3/2024, 5:05:41 PM ci-kubernetes-kind-conformance-parallel](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-conformance-parallel/1841856945284190208)

/kind failing-test
/kind flake
/sig network

**Comment by aojea** [comment] 2024-10-21 11:32
It seems the test runs with other tests that run multiple pods and the node is at full capacity, checking https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1844887536313307136


> I1012 00:04:32.242364 70707 dump.go:53] At 2024-10-12 00:04:30 +0000 UTC - event for pod1: {kubelet kind-worker2} OutOfpods: Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110


There are a lot of pods prefixed as `simpletest-rc-to-be-deleted`
```
I1012 00:04:33.998671 70707 dump.go:128] gc-1657/simpletest-rc-to-be-deleted-9fnxn started at 2024-10-12 00:04:25 +0000 UTC (0+1 container statuses recorded)
I1012 00:04:33.998687 70707 dump.go:134] 	Container nginx ready: false, restart count 0
I1012 00:04:33.998706 70707 dump.go:128] gc-1657/simpletest-rc-to-be-deleted-zfqh9 started at 2024-10-12 00:04:28 +0000 UTC (0+1 container statuses recorded)
I1012 00:04:33.998718 70707 dump.go:134] 	Container nginx ready: false, restart count 0
I1012 00:04:33.998736 70707 dump.go:128] kube-system/kube-proxy-bcbmw started at 2024-10-12 00:01:41 +0000 UTC (0+1 container statuses recorded)
I1012 00:04:33.998749 70707 dump.go:134] 	Container kube-proxy ready: true, restart count 0
I1012 00:04:33.998768 70707 dump.go:128] gc-1657/simpletest-rc-to-be-deleted-nq4mv started at 2024-10-12 00:04:25 +0000 UTC (0+1 container statuses recorded)
I1012 00:04:33.998783 70707 dump.go:134] 	Container nginx ready: false, restart count 0
I1012 00:04:33.998799 70707 dump.go:128] services-7131/execpod-affinityg5dl4 started at 2024-10-12 00:04:26 +0000 UTC (0+1 container statuses recorded)
I1012 00:04:33.998813 70707 dump.go:134] 	Container agnhost-container ready: false, restart count 0
I1012 00:04:33.998831 70707 dump.go:128] gc-1657/simpletest-rc-to-be-deleted-wltzv started at 2024-1
```

That indicates this is the test impacting other tests https://github.com/kubernetes/kubernetes/blob/d99ee9293cd7f819b1ac81408b95e2b971d3f241/test/e2e/apimachinery/garbage_collector.go#L710-L719

that was already known by causing this kind of noisy problems

https://github.com/kubernetes/kubernetes/pull/107030

So, I think we should retitle this as `should not delete dependents that have both valid ` conformance test impact other tests running in parallel ... in this case it was HostPort but I will be surprised that does not happen with others ... maybe the hostPort has some specifics that make it more sensible to this problem ... lower timeouts maybe?

**Comment by thockin** [comment] 2024-11-21 17:29
ping to older untriaged issue

**Comment by thockin** [comment] 2024-12-05 17:01
ping again

**Comment by aroradaman** [comment] 2024-12-10 15:04
`HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol` creates three pods on the same node with different HostIPs and Protocols. 

All the tests mentioned in the issue description fails at https://github.com/kubernetes/kubernetes/blob/a499facee693a1a83daadb82d88f7b51d324ffc5/test/e2e/network/hostport.go#L218-L220

The captured events for test namespace contains
```
OutOfpods: Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
```

Also note that it is not always the first pod of the test which triggers the `OutOfPods`, for some of the cases it is the second pod, and some cases third.
This looks like a capacity, or too many tests in parallel issue.

**Comment by aojea** [comment] 2024-12-10 21:45
Thanks for the analysis , since it does not seem to happen on the "official" jobs https://storage.googleapis.com/k8s-triage/index.html#e365d8afd2e3f3d01d69 and the problem is environmental because a disruptive test, let's close this

/close

**Closed by aojea** 2024-12-10 21:45 UTC
Labels: sig/network, kind/flake, kind/failing-test, needs-triage
