### ISSUE TITLE
`io.k8s.api.admission` types missing from OpenAPI spec

### ISSUE THREAD

**Issue by coadler** [kubernetes/kubernetes#100595] opened 2021-03-26 20:16 UTC
#### What happened:

I'm attempting to use the Rust [API bindings](https://github.com/Arnavion/k8s-openapi) which are generated from the OpenAPI spec in this repo. I noticed that the `admission` section is completely missing. Looking further, it seems like the entire `admission` section is missing from the official OpenAPI spec all together. I'm not entirely sure if this is on purpose, but it would be nice to be able to use this section in 3rd party bindings.

The Go bindings can be seen here: https://github.com/kubernetes/api/tree/master/admission

#### What you expected to happen:

`io.k8s.api.admission` types are present in the OpenAPI spec, and can be used by 3rd party libraries to generate code.

#### How to reproduce it (as minimally and precisely as possible):

See https://raw.githubusercontent.com/kubernetes/kubernetes/9c9af69ea60519b610a70261fb1b8bb81a2a5d04/api/openapi-spec/swagger.json.

Grepping through the file produces no results for `io.k8s.api.admission.(v1|v1beta1)`.

**Comment by liggitt** [comment] 2021-03-27 16:06
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/84081

the generated openapi spec currently only contains types served by the API server

**Closed by liggitt** 2021-03-27 16:06 UTC
Labels: kind/bug, needs-triage, sig/api-machinery
