### ISSUE TITLE
e2e flake: Kubectl client [k8s.io] Simple pod [It] should support exec through an HTTP proxy 

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24620] opened 2016-04-21 20:33 UTC
```
â€¢ Failure [369.610 seconds]
[k8s.io] Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:426
  [k8s.io] Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:426
    should support exec through an HTTP proxy [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:478

    Apr 21 13:17:03.800: Unable to execute kubectl binary on the remote exec server due to error: Post https://104.197.168.138/api/v1/namespaces/e2e-tests-kubectl-3u4kj/pods/netexec/proxy/shell?shellCommand=https_proxy%3Dhttp%3A%2F%2F10.245.5.8%3A8080+.%2Fuploads%2Fupload904948526+--kubeconfig%3D%2Fuploads%2Fupload042959260+--server%3Dhttps%3A%2F%2F104.197.168.138%3A443+--namespace%3De2e-tests-kubectl-3u4kj+exec+nginx+echo+running+in+container: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:449
```
#24574 (comment)

**Comment by piosz** [comment] 2016-04-25 11:15
cc @lavalamp

**Comment by piosz** [comment] 2016-04-25 11:16
Yet another fail:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke/5067/

**Comment by spxtr** [comment] 2016-05-05 16:40
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/6143

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/6209

**Comment by dchen1107** [comment] 2016-05-05 20:43
Bump the priority to P0 since it has several failures already, and currently blocks our merge queue. The last one is:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16272/

**Comment by nikhiljindal** [comment] 2016-05-06 06:42
Failed again: https://github.com/kubernetes/kubernetes/pull/24943#issuecomment-216725855

**Comment by krousey** [comment] 2016-05-06 16:59
@nikhiljindal You got a direct logs link for that flake?

**Comment by krousey** [comment] 2016-05-06 17:08
I'm looking into this, but not making much headway. There are a couple of different errors:

```
May  4 13:22:00.355: INFO: Unable to upload kubeconfig to the remote exec server due to error: an error on the server has prevented the request from succeeding (post pods netexec)
```

```
13:13:09 May  5 13:12:48.484: INFO: Unable to execute kubectl binary on the remote exec server due to error: Post https://104.197.18.124/api/v1/namespaces/e2e-tests-kubectl-ifboj/pods/netexec/proxy/shell?shellCommand=HTTPS_PROXY%!D(MISSING)http%!A(MISSING)%!F(MISSING)%!F(MISSING)10.245.3.6%!A(MISSING)8080+.%!F(MISSING)uploads%!F(MISSING)upload076000197+--kubeconfig%!D(MISSING)%!F(MISSING)uploads%!F(MISSING)upload391541467+--server%!D(MISSING)https%!A(MISSING)%!F(MISSING)%!F(MISSING)104.197.18.124%!A(MISSING)443+--namespace%!D(MISSING)e2e-tests-kubectl-ifboj+exec+nginx+echo+running+in+container: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

but it seems to be communication errors with the netexec pod. I'm going to try to find that code and see if there's a problem there. Also, anyone have an idea what all the `MISSING` stuff in the error means? Is it a url encoding error?

**Comment by krousey** [comment] 2016-05-07 00:04
So this test has a lot of moving parts. I actually diagrammed to help me understand it for anyone who cares:

```
+-----+                               +---------+                   +---------+                    +-----------+       +-------+
| e2e |                               | netexec |                   | goProxy |                    | apiServer |       | nginx |
+-----+                               +---------+                   +---------+                    +-----------+       +-------+
   |                                       |                             |                               |                 |
   | create netexec                        |                             |                               |                 |
   |-------------------------------------->|                             |                               |                 |
   |                                       |                             |                               |                 |
   | upload kubeconfig                     |                             |                               |                 |
   |-------------------------------------->|                             |                               |                 |
   |                                       |                             |                               |                 |
   | upload kubectl                        |                             |                               |                 |
   |-------------------------------------->|                             |                               |                 |
   |                                       |                             |                               |                 |
   | create goProxy                        |                             |                               |                 |
   |-------------------------------------------------------------------->|                               |                 |
   |                                       |                             |                               |                 |
   |                                       |                    proxy IP |                               |                 |
   |<--------------------------------------------------------------------|                               |                 |
   |                                       |                             |                               |                 |
   | run kubectl exec through goProxy      |                             |                               |                 |
   |-------------------------------------->|                             |                               |                 |
   |                                       | -----------------------\    |                               |                 |
   |                                       |-| shell out to kubectl |    |                               |                 |
   |                                       | | with https_proxy set |    |                               |                 |
   |                                       | |----------------------|    |                               |                 |
   |                                       | proxied kubectl exec        |                               |                 |
   |                                       |---------------------------->|                               |                 |
   |                                       |                             |                               |                 |
   |                                       |                             | exec on nginx echo "Hi"       |                 |
   |                                       |                             |------------------------------>|                 |
   |                                       |                             |                               |                 |
   |                                       |                             |                               | echo "Hi"       |
   |                                       |                             |                               |---------------->|
   |                                       |                             |                               |                 |
   |                                       |                             |                               |     stdout "Hi" |
   |                                       |                             |                               |<----------------|
   |                                       |                             |                               |                 |
   |                                       |                             |                          "Hi" |                 |
   |                                       |                             |<------------------------------|                 |
   |                                       |                             |                               |                 |
   |                                       |                        "Hi" |                               |                 |
   |                                       |<----------------------------|                               |                 |
   |                                       |                             |                               |                 |
   |                                  "Hi" |                             |                               |                 |
   |<--------------------------------------|                             |                               |                 |
   |                                       |                             |                               |                 |
   | check logs to make sure it actually proxied a connection            |                               |                 |
   |-------------------------------------------------------------------->|                               |                 |
   | -----------------------------\        |                             |                               |                 |
   |-| restart goProxy and repeat |        |                             |                               |                 |
   | | using HTTPS_PROXY env var  |        |                             |                               |                 |
   | |----------------------------|        |                             |                               |                 |
```

**Comment by krousey** [comment] 2016-05-07 00:09
@ncdc Any ideas as to why this is starting to flake so much? Also, do we need to do it for both environment variables? If this sequence flakes 10% of the time, running it twice increase the overall flake to 19% of the time.

**Comment by jayunit100** [comment] 2016-05-07 00:13
Also, Is nginx even needed ? After all exec can be done in any simple pod. And the proxy is local right ?

**Comment by ncdc** [comment] 2016-05-07 00:25
@krousey not really. I don't have any foundation for this, but my gut feeling is there is something weird going on with the GCE networking between the apiserver and the kubelet (that's missing from your diagram above). It uses the rest generic proxy in the apiserver to proxy traffic between kubectl and the kubelet. That's where the timeouts seem to be occurring (at least that's where they were happening when I looked at this most recently).

**Comment by ncdc** [comment] 2016-05-07 00:40
@jayunit100 any image will work. The proxy is not local - you can't set HTTP_PROXY=127.0.0.1:3128 and have it work. The go code that sets up proxying ignores local loopback addresses. So we run a pod as the proxy. And we run another pod as the exec target (nginx currently).

**Comment by krousey** [comment] 2016-05-09 18:45
I've tried reproducing this several times with no luck. I'm adding some more logging so that the next time it fails we'll get more info.

**Comment by krousey** [comment] 2016-05-10 15:49
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25280/kubernetes-pull-build-test-e2e-gce/39167/

**Comment by gmarek** [comment] 2016-05-11 15:14
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16674/

**Comment by krousey** [comment] 2016-05-11 16:05
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16674/

(public long term results for @gmarek 's report.)

**Comment by ncdc** [comment] 2016-05-16 15:16
@krousey pantheon.corp.google.com isn't publicly available, FYI.

**Comment by ncdc** [comment] 2016-05-16 15:19
I'm guessing the best link would either be http://ci-test.k8s.io/kubernetes-e2e-gce/16674/ or https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16674

**Comment by gmarek** [comment] 2016-05-16 16:45
@krousey - this is a month-old P0, what's the status of it?

**Comment by krousey** [comment] 2016-05-16 22:44
@gmarek I added some logging hoping to get more info, but it seems this fails in a lot of different ways. I'm going to add some retries around setting up the netexec container, since we're not really interested in testing it's robustness.

**Comment by krousey** [comment] 2016-05-16 23:32
New type of failure I haven't seen before:

```
May 16 15:03:54.189: INFO: Unexpected kubectl exec output. Wanted "running in container\n", got  "Please enter Username: Please enter Password: Unable to connect to the server: x509: failed to load system roots and no roots provided\n"
```

Some how the prompting auth loader was invoked and the exec call? The config didn't fail to upload, but maybe it wasn't written correctly?

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25546/kubernetes-pull-build-test-e2e-gce/40306/

**Comment by krousey** [comment] 2016-05-16 23:39
@ncdc does this test need the netexec container? I'm thinking that a lot of the flakiness my be due to issues with netexec (failed writes, partial writes...) Could we do the following:

1. Create a PD from the e2e test and write kubectl + kubeconfig to it (is this possible?)
1. Stand up a busybox container with this PD mounted
1. Use the exec API to call kubectl exec on the busybox pod with the goproxy info
1. check the results as normal

Is that eliminating any important aspect of this test?

**Comment by ncdc** [comment] 2016-05-17 13:12
@krousey at a minimum, we need the following:

1. Use the copy of kubectl built from the current git commit
1. Run a proxy somewhere that is not localhost/127.0.0.1
1. Test the kubectl from step 1 with the env vars `http_proxy`, `https_proxy`, `HTTP_PROXY`, `HTTPS_PROXY`
1. Test attach, exec, and ideally port-forward (the 3 commands that currently use the SPDY roundtripper)

Beyond that, I think the rest is "test implementation details"

**Comment by krousey** [comment] 2016-05-17 16:09
@ncdc And the kubectl has to be run from inside the cluster? Also, why do we have to test all 4 env vars? Shouldn't 1 suffice?

**Comment by ncdc** [comment] 2016-05-17 16:15
@krousey I don't know that it matters where kubectl is run, as long as it's the kubectl that was just built. We have to test at least 2 - 1 variation of http_proxy and 1 variation of https_proxy. https_proxy is important because it lets us test that proxying works when the apiserver only talks https and that the secure flow is still functional.

**Comment by krousey** [comment] 2016-05-17 22:05
I have a change pending for this that removes a lot of the moving parts of this test. I cannot confirm that it's a fix (or actually any less flaky due to lack of sample size), but I'm going to close this issue if it goes in.

**Comment by krousey** [comment] 2016-05-23 16:10
Closing this as a lot of the complexity was removed. Reopen if it flakes again.

**Closed by krousey** 2016-05-23 16:10 UTC
Labels: component/kubectl, kind/flake, priority/P0, team/CSI-API Machinery SIG
