### ISSUE TITLE
pod status not updated after recovering from error

### ISSUE THREAD

**Issue by slintes** [kubernetes/kubernetes#14404] opened 2015-09-23 07:42 UTC
Hi,

I have a strange situation where a pod status is GenerelError, but the pod is running (after recovering from that error by starting another docker conatiner):
```
core@controller ~ $ kubectl get pods -o wide
NAME                                         READY     STATUS         RESTARTS   AGE       NODE
inaetics-producer-controller-xi881           0/1       GeneralError   0          27m       172.17.8.31

core@controller ~ $ kubectl describe pod inaetics-producer-controller-xi881
Name:				inaetics-producer-controller-xi881
Namespace:			default
Image(s):			inaetics/felix-agent
Node:				172.17.8.31/
Labels:				name=inaetics-producer-pod
Status:				Pending
Reason:				GeneralError
Message:			Query container info failed with error (No such container: 56595175b504f1c6347505f9b1fda3d36abda455f3a6f11354abafb28ce96283)
IP:
Replication Controllers:	inaetics-producer-controller (1/1 replicas created)
Containers:
  inaetics-producer-container:
    Image:	inaetics/felix-agent
    Limits:
      memory:		300Mi
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath					Reason			Message
  Wed, 23 Sep 2015 06:50:57 +0000	Wed, 23 Sep 2015 06:53:15 +0000	12	{scheduler }								failedScheduling	no nodes available to schedule pods
  Wed, 23 Sep 2015 06:53:31 +0000	Wed, 23 Sep 2015 06:53:31 +0000	1	{scheduler }								scheduled		Successfully assigned inaetics-producer-controller-xi881 to 172.17.8.31
  Wed, 23 Sep 2015 06:53:31 +0000	Wed, 23 Sep 2015 06:53:31 +0000	1	{kubelet 172.17.8.31}	implicitly required container POD		pulled			Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Wed, 23 Sep 2015 06:53:31 +0000	Wed, 23 Sep 2015 06:53:31 +0000	1	{kubelet 172.17.8.31}	implicitly required container POD		created			Created with docker id d5384c28cadf
  Wed, 23 Sep 2015 06:53:31 +0000	Wed, 23 Sep 2015 06:53:31 +0000	1	{kubelet 172.17.8.31}	spec.containers{inaetics-producer-container}	failed			Failed to create docker container with error: API error (500): open /var/lib/docker/overlay/56595175b504f1c6347505f9b1fda3d36abda455f3a6f11354abafb28ce96283-init/merged/etc/resolv.conf: cannot allocate memory

  Wed, 23 Sep 2015 06:53:31 +0000	Wed, 23 Sep 2015 06:53:31 +0000	1	{kubelet 172.17.8.31}	implicitly required container POD		started	Started with docker id d5384c28cadf
  Wed, 23 Sep 2015 06:53:41 +0000	Wed, 23 Sep 2015 06:53:41 +0000	1	{kubelet 172.17.8.31}	spec.containers{inaetics-producer-container}	created	Created with docker id 8060bda6ef0e
  Wed, 23 Sep 2015 06:53:41 +0000	Wed, 23 Sep 2015 06:53:41 +0000	1	{kubelet 172.17.8.31}	spec.containers{inaetics-producer-container}	started	Started with docker id 8060bda6ef0e
```

The corresponding containers are running fine and doing their work:
```
core@node-1 ~ $ docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
8060bda6ef0e        inaetics/felix-agent                   "/tmp/node-agent.sh f"   33 minutes ago      Up 33 minutes                           k8s_inaetics-producer-container.d7e49239_inaetics-producer-controller-xi881_default_713878d6-61bf-11e5-bea1-080027df9088_4be58e02
d5384c28cadf        gcr.io/google_containers/pause:0.8.0   "/pause"                 33 minutes ago      Up 33 minutes                           k8s_POD.e4cc795_inaetics-producer-controller-xi881_default_713878d6-61bf-11e5-bea1-080027df9088_89f0124b
```

I'm running k8s 1.0.6
```
core@controller ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

Greetings, Marc

**Comment by slintes** [comment] 2015-09-23 07:46
oh, if that is of interest: I'm running on CoreOS 808.0.0 with docker 1.8.2

**Comment by yujuhong** [comment] 2015-09-23 18:37
@slintes, do you by any chance still have the kubelet.log of the relevant time period?

**Comment by slintes** [comment] 2015-09-23 20:51
no, but I could reproduce it (I left out other running pods from the logs):

```
core@controller ~ $ kubectl get pods -o wide
NAME                                         READY     STATUS         RESTARTS   AGE       NODE
inaetics-processor-controller-y1vci          0/1       GeneralError   0          43m       172.17.8.32

core@controller ~ $ kubectl describe pod inaetics-processor-controller-y1vci
Name:				inaetics-processor-controller-y1vci
Namespace:			default
Image(s):			inaetics/felix-agent
Node:				172.17.8.32/
Labels:				name=inaetics-processor-pod
Status:				Pending
Reason:				GeneralError
Message:			Query container info failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
IP:
Replication Controllers:	inaetics-processor-controller (1/1 replicas created)
Containers:
  inaetics-processor-container:
    Image:	inaetics/felix-agent
    Limits:
      memory:		300Mi
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath					Reason		Message
  Wed, 23 Sep 2015 19:47:40 +0000	Wed, 23 Sep 2015 19:47:40 +0000	1	{scheduler }								scheduled	Successfully assigned inaetics-processor-controller-y1vci to 172.17.8.32
  Wed, 23 Sep 2015 19:47:40 +0000	Wed, 23 Sep 2015 19:47:40 +0000	1	{kubelet 172.17.8.32}	implicitly required container POD		pulled		Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Wed, 23 Sep 2015 19:47:40 +0000	Wed, 23 Sep 2015 19:47:40 +0000	1	{kubelet 172.17.8.32}	implicitly required container POD		created		Created with docker id e3b5ccd9c5eb
  Wed, 23 Sep 2015 19:47:40 +0000	Wed, 23 Sep 2015 19:47:40 +0000	1	{kubelet 172.17.8.32}	implicitly required container POD		started		Started with docker id e3b5ccd9c5eb
  Wed, 23 Sep 2015 19:47:40 +0000	Wed, 23 Sep 2015 19:47:40 +0000	1	{kubelet 172.17.8.32}	spec.containers{inaetics-processor-container}	failed		Failed to create docker container with error: API error (500): open /var/lib/docker/overlay/f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed-init/merged/etc/resolv.conf: cannot allocate memory

  Wed, 23 Sep 2015 19:47:50 +0000	Wed, 23 Sep 2015 19:47:50 +0000	1	{kubelet 172.17.8.32}	spec.containers{inaetics-processor-container}	created	Created with docker id b106782a3ddc
  Wed, 23 Sep 2015 19:47:50 +0000	Wed, 23 Sep 2015 19:47:50 +0000	1	{kubelet 172.17.8.32}	spec.containers{inaetics-processor-container}	started	Started with docker id b106782a3ddc

core@node-2 ~ $ docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
b106782a3ddc        inaetics/felix-agent                   "/tmp/node-agent.sh f"   About an hour ago   Up About an hour                        k8s_inaetics-processor-container.f39c92b4_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3b5bd33a
e3b5ccd9c5eb        gcr.io/google_containers/pause:0.8.0   "/pause"                 About an hour ago   Up About an hour                        k8s_POD.e4cc795_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3a1949f3

core@node-2 ~ $ journalctl -u kube-kubelet | grep inaetics-processor-controller-y1vci
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.045148    2789 kubelet.go:1227] Not generating pod status for new pod "inaetics-processor-controller-y1vci_default"
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.045161    2789 manager.go:1384] Need to restart pod infra container for "inaetics-processor-controller-y1vci_default" because it is not found
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.045490    2789 manager.go:1515] Got container changes for pod "inaetics-processor-controller-y1vci_default": {StartInfraContainer:true InfraContainerId: ContainersToStart:map[0:{}] ContainersToKeep:map[]}
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.078954    2789 status_manager.go:169] Status for pod "inaetics-processor-controller-y1vci_default" updated successfully
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.092078    2789 manager.go:601] Container default/inaetics-processor-controller-y1vci/POD: setting entrypoint "[]" and command "[]"
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.092149    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.136405    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"implicitly required container POD"}): reason: 'created' Created with docker id e3b5ccd9c5eb
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.301338    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"implicitly required container POD"}): reason: 'started' Started with docker id e3b5ccd9c5eb
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.312512    2789 manager.go:797] Added container: "/system.slice/docker-e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e.scope" (aliases: [k8s_POD.e4cc795_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3a1949f3 e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e], namespace: "docker")
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.323685    2789 manager.go:601] Container default/inaetics-processor-controller-y1vci/inaetics-processor-container: setting entrypoint "[]" and command "[/tmp/node-agent.sh felix_3]"
Sep 23 19:47:40 node-2 kubelet[2789]: E0923 19:47:40.442592    2789 manager.go:1579] Error running pod "inaetics-processor-controller-y1vci_default" container "inaetics-processor-container": API error (500): open /var/lib/docker/overlay/f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed-init/merged/etc/resolv.conf: cannot allocate memory
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.442613    2789 kubelet.go:2245] Generating status for "inaetics-processor-controller-y1vci_default"
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.442697    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"spec.containers{inaetics-processor-container}"}): reason: 'failed' Failed to create docker container with error: API error (500): open /var/lib/docker/overlay/f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed-init/merged/etc/resolv.conf: cannot allocate memory
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.465481    2789 kubelet.go:2262] Query container info for pod "inaetics-processor-controller-y1vci_default" failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
Sep 23 19:47:40 node-2 kubelet[2789]: I0923 19:47:40.492767    2789 status_manager.go:169] Status for pod "inaetics-processor-controller-y1vci_default" updated successfully
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.052543    2789 kubelet.go:2245] Generating status for "inaetics-processor-controller-y1vci_default"
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.067267    2789 kubelet.go:2262] Query container info for pod "inaetics-processor-controller-y1vci_default" failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.074970    2789 manager.go:1515] Got container changes for pod "inaetics-processor-controller-y1vci_default": {StartInfraContainer:false InfraContainerId:e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e ContainersToStart:map[0:{}] ContainersToKeep:map[e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e:-1]}
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.086513    2789 manager.go:601] Container default/inaetics-processor-controller-y1vci/inaetics-processor-container: setting entrypoint "[]" and command "[/tmp/node-agent.sh felix_3]"
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.166786    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"spec.containers{inaetics-processor-container}"}): reason: 'created' Created with docker id b106782a3ddc
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.216470    2789 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"inaetics-processor-controller-y1vci", UID:"f2bc04e2-622b-11e5-b06f-080027df9088", APIVersion:"v1", ResourceVersion:"1329", FieldPath:"spec.containers{inaetics-processor-container}"}): reason: 'started' Started with docker id b106782a3ddc
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.220400    2789 kubelet.go:2245] Generating status for "inaetics-processor-controller-y1vci_default"
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.221020    2789 manager.go:797] Added container: "/system.slice/docker-b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e.scope" (aliases: [k8s_inaetics-processor-container.f39c92b4_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3b5bd33a b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e], namespace: "docker")
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.224098    2789 manager.go:279] Container inspect result: {ID:b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e Created:2015-09-23 19:47:50.145805805 +0000 UTC Path:/tmp/node-agent.sh Args:[felix_3] Config:0xc208626300 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:4648 ExitCode:0 Error: StartedAt:2015-09-23 19:47:50.21533991 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:1c28d4c6aeb957d3bb62433f0d8974d9fc47b955ff46c657553051faf9b40944 Node:<nil> NetworkSettings:0xc20909f4f0 SysInitPath: ResolvConfPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/resolv.conf HostnamePath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hostname HostsPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hosts Name:/k8s_inaetics-processor-container.f39c92b4_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3b5bd33a Driver:overlay Volumes:map[] VolumesRW:map[] HostConfig:0xc208a50d20 ExecIDs:[] AppArmorProfile:}
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.224510    2789 kubelet.go:2262] Query container info for pod "inaetics-processor-controller-y1vci_default" failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
Sep 23 19:47:50 node-2 kubelet[2789]: I0923 19:47:50.224535    2789 status_manager.go:129] Ignoring same status for pod "inaetics-processor-controller-y1vci_default", status: {Phase:Pending Conditions:[] Message:Query container info failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed) Reason:GeneralError HostIP: PodIP: StartTime:2015-09-23 19:47:40.044974551 +0000 UTC ContainerStatuses:[]}
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.061925    2789 kubelet.go:2245] Generating status for "inaetics-processor-controller-y1vci_default"
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.073458    2789 manager.go:279] Container inspect result: {ID:b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e Created:2015-09-23 19:47:50.145805805 +0000 UTC Path:/tmp/node-agent.sh Args:[felix_3] Config:0xc20897f800 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:4648 ExitCode:0 Error: StartedAt:2015-09-23 19:47:50.21533991 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:1c28d4c6aeb957d3bb62433f0d8974d9fc47b955ff46c657553051faf9b40944 Node:<nil> NetworkSettings:0xc208560eb0 SysInitPath: ResolvConfPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/resolv.conf HostnamePath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hostname HostsPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hosts Name:/k8s_inaetics-processor-container.f39c92b4_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3b5bd33a Driver:overlay Volumes:map[] VolumesRW:map[] HostConfig:0xc208ddc5a0 ExecIDs:[] AppArmorProfile:}
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.076218    2789 kubelet.go:2262] Query container info for pod "inaetics-processor-controller-y1vci_default" failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.079146    2789 manager.go:1411] pod "inaetics-processor-controller-y1vci_default" container "inaetics-processor-container" exists as b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.079163    2789 prober.go:180] Readiness probe for "inaetics-processor-controller-y1vci_default:inaetics-processor-container" succeeded
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.242744    2789 prober.go:136] Liveness probe for "inaetics-processor-controller-y1vci_default:inaetics-processor-container" succeeded
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.242757    2789 manager.go:1515] Got container changes for pod "inaetics-processor-controller-y1vci_default": {StartInfraContainer:false InfraContainerId:e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e ContainersToStart:map[] ContainersToKeep:map[b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e:0 e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e:-1]}
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.242775    2789 kubelet.go:2245] Generating status for "inaetics-processor-controller-y1vci_default"
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.244412    2789 manager.go:279] Container inspect result: {ID:b106782a3ddc36fd3b37a66a8e013dd7a2f2408c3251fe54549ee19faf8cc24e Created:2015-09-23 19:47:50.145805805 +0000 UTC Path:/tmp/node-agent.sh Args:[felix_3] Config:0xc20831d800 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:4648 ExitCode:0 Error: StartedAt:2015-09-23 19:47:50.21533991 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:1c28d4c6aeb957d3bb62433f0d8974d9fc47b955ff46c657553051faf9b40944 Node:<nil> NetworkSettings:0xc2085cf090 SysInitPath: ResolvConfPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/resolv.conf HostnamePath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hostname HostsPath:/var/lib/docker/containers/e3b5ccd9c5ebb059e34ff8a7eb6c5cea79f04e5f7530788a506199a219e6565e/hosts Name:/k8s_inaetics-processor-container.f39c92b4_inaetics-processor-controller-y1vci_default_f2bc04e2-622b-11e5-b06f-080027df9088_3b5bd33a Driver:overlay Volumes:map[] VolumesRW:map[] HostConfig:0xc2085714a0 ExecIDs:[] AppArmorProfile:}
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.244927    2789 kubelet.go:2262] Query container info for pod "inaetics-processor-controller-y1vci_default" failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed)
Sep 23 19:48:00 node-2 kubelet[2789]: I0923 19:48:00.244960    2789 status_manager.go:129] Ignoring same status for pod "inaetics-processor-controller-y1vci_default", status: {Phase:Pending Conditions:[] Message:Query container info failed with error (No such container: f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed) Reason:GeneralError HostIP: PodIP: StartTime:2015-09-23 19:47:40.044974551 +0000 UTC ContainerStatuses:[]}
```

**Comment by yujuhong** [comment] 2015-09-23 21:03
Kubelet can't generate correct status because it encountered error inspecting one of the dead containers. We should improve that.

On the other hand, I am curious why the container creation/inspect continues to fail.
@slintes, does `f9c8bdc7c0b669364c68b83e9a` show up in `docker ps -a`, and could you inspect it?

/cc @kubernetes/goog-node to see if anyone's familiar with the creation error:
`API error (500): open /var/lib/docker/overlay/f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed-init/merged/etc/resolv.conf: cannot allocate memory`

**Comment by slintes** [comment] 2015-09-23 21:16
will try to reproduce again ;)
if relevant: the container has a memory resource limit set
you can find the complete setup on github, e.g.
- fleet-units that start the k8s binaries: https://github.com/INAETICS/kubernetes-demo-cluster/tree/elkAndMore/Controller/fleet-units
- the replication controller / pod: https://github.com/INAETICS/kubernetes-demo-cluster/blob/elkAndMore/Controller/inaetics-demo/k8s/inaetics-processor-controller.json

**Comment by slintes** [comment] 2015-09-23 21:54
can't reproduce it atm, sorry

**Comment by yujuhong** [comment] 2015-09-23 22:10
> can't reproduce it atm, sorry

No problem. Thanks for trying.

I don't see any problem with the resource limit. 

The creation error seems transient, as the second attempt eventually succeeded. Was docker using a lot of file descriptors?

It seems to me that after the creation failure, the container was lying around in `docker ps -a`, but kubelet couldn't inspect it. I wonder why it'd be in such a state.

**Comment by dchen1107** [comment] 2015-09-23 22:23
Error message 
```
API error (500): open /var/lib/docker/overlay/f9c8bdc7c0b669364c68b83e9a3c3830d2541ba8aef568380c5222f6e420c4ed-init/merged/etc/resolv.conf: cannot allocate memory
```
is from docker's graph driver. Docker daemon might hit max open file limit on your system. What's the output of /proc/$(pidof docker)/limits?

**Comment by dchen1107** [comment] 2015-09-23 22:28
But no matter what is the initial reason causing first creation failure, there is an issue in Kubelet on podStatus generation: the only user container is running, and pod status should be running, instead of, pending.

**Comment by GeneticGenesis** [comment] 2015-10-29 23:36
Hey guys,

Any more thoughts on this? We have a cluster exhibiting the same symptoms at the moment. Happy to grab logs etc. if needed.

Cheers,

**Comment by brandoncole** [comment] 2015-11-10 18:22
We also see this occasionally, it's hard to reproduce.  Here's our logs.  In this situation, Kubernetes will never self heal, we can delete the pod manually and it'll recover just fine though.   
```$ kubectl describe pod geometry-t17tr 
Name:				geometry-t17tr
Namespace:			default
Image(s):			192.168.20.10:5000/projectname/ms.geometry:latest,192.168.20.10:5000/projectname/adapter:latest
Node:				192.168.20.101/
Labels:				name=geometry,projectname=com.company.Geometry
Status:				Pending
Reason:				GeneralError
Message:			Query container info failed with error (No such container: e180ac631213f2a01c080b641f97581932d8d73839fae8b7e9e5e538f995e8b6)
IP:				
Replication Controllers:	geometry (1/1 replicas created)
Containers:
  geometry:
    Image:		192.168.20.10:5000/projectname/ms.geometry:latest
    State:		Waiting
    Ready:		False
    Restart Count:	0
  adapter:
    Image:		192.168.20.10:5000/projectname/adapter:latest
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From				SubobjectPath				Reason		Message
  Tue, 10 Nov 2015 16:15:55 +0000	Tue, 10 Nov 2015 16:15:55 +0000	1	{scheduler }								scheduled	Successfully assigned geometry-t17tr to 192.168.20.101
  Tue, 10 Nov 2015 16:16:02 +0000	Tue, 10 Nov 2015 16:16:02 +0000	1	{kubelet 192.168.20.101}	implicitly required container POD	pulled		Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Tue, 10 Nov 2015 16:16:02 +0000	Tue, 10 Nov 2015 16:16:02 +0000	1	{kubelet 192.168.20.101}	implicitly required container POD	created		Created with docker id 6d2fa01ea1d3
  Tue, 10 Nov 2015 16:16:04 +0000	Tue, 10 Nov 2015 16:16:04 +0000	1	{kubelet 192.168.20.101}	implicitly required container POD	started		Started with docker id 6d2fa01ea1d3
  ...
  Tue, 10 Nov 2015 18:02:30 +0000	Tue, 10 Nov 2015 18:02:30 +0000	1	{kubelet 192.168.20.101}	spec.containers{adapter}		failed		Failed to create docker container with error: API error (500): mkdir /var/lib/docker/overlay/54a379369508722e54fba9421e2dd10e83b63a2a815711457ae790c26f9166a9-init/merged/dev/shm: file exists

  Tue, 10 Nov 2015 18:02:40 +0000	Tue, 10 Nov 2015 18:02:40 +0000	1	{kubelet 192.168.20.101}	spec.containers{adapter}	failed	Failed to create docker container with error: API error (500): mkdir /var/lib/docker/overlay/e180ac631213f2a01c080b641f97581932d8d73839fae8b7e9e5e538f995e8b6-init/merged/dev/shm: file exists

  Tue, 10 Nov 2015 18:02:50 +0000	Tue, 10 Nov 2015 18:02:50 +0000	1	{kubelet 192.168.20.101}	spec.containers{adapter}	started	Started with docker id 75620954877b
  Tue, 10 Nov 2015 18:02:50 +0000	Tue, 10 Nov 2015 18:02:50 +0000	1	{kubelet 192.168.20.101}	spec.containers{adapter}	created	Created with docker id 75620954877b
  Tue, 10 Nov 2015 16:16:06 +0000	Tue, 10 Nov 2015 18:02:50 +0000	13	{kubelet 192.168.20.101}	spec.containers{adapter}	pulled	Successfully pulled image "192.168.20.10:5000/projectname/adapter:latest"```

**Comment by yujuhong** [comment] 2015-11-10 18:45
@brandoncole, does the container show up in `docker ps -a`? If so, what's the status and could you inspect it? I suspect that the first creation failure left the state inconsistent, so `docker ps` could still lists the container, but inspect fails. We should find out why the creation failed at the first place, and why the inspection didn't work afterwards.

**Comment by brandoncole** [comment] 2015-11-10 19:17
I already corrected the situation last time it happened, when it happens again I'll update the group.  I've seen a couple different failures, I've seen the `cannot allocate memory` and `file exists` error.  Give me a day and I should have an update.

**Comment by brandoncole** [comment] 2015-11-11 13:26
Okay, we got it again this morning.  Here's how the pod is described:

```
vagrant@dev:~$ kubectl describe pod geometry-bwhet
Name:				geometry-bwhet
Namespace:			default
Image(s):			192.168.20.10:5000/thunderstorm/ms.geometry:latest,192.168.20.10:5000/thunderstorm/adapter:latest
Node:				192.168.20.101/
Labels:				name=geometry,thunderstorm=com.autodesk.Geometry
Status:				Pending
Reason:				GeneralError
Message:			Query container info failed with error (No such container: abdf6642fa383f8281f8451e5ccd149a04ac1ad48350d7c96d662eb2c341511a)
IP:				
Replication Controllers:	geometry (1/1 replicas created)
Containers:
  geometry:
    Image:		192.168.20.10:5000/thunderstorm/ms.geometry:latest
    State:		Waiting
    Ready:		False
    Restart Count:	0
  adapter:
    Image:		192.168.20.10:5000/thunderstorm/adapter:latest
    State:		Waiting
    Ready:		False
    Restart Count:	0
```

And here are the docker processes on the minion:

```
core@m1 ~ $ docker ps | grep geometry
ce0337141e7e        192.168.20.10:5000/thunderstorm/ms.geometry:latest   "./geometryservice"      55 seconds ago       Up 54 seconds                           k8s_geometry.5c1e0919_geometry-bwhet_default_2f28e9cf-8877-11e5-86aa-080027d13a94_bfa21fc3
06645458dc2b        192.168.20.10:5000/thunderstorm/adapter:latest       "./adapter -listenAdd"   About a minute ago   Up About a minute                       k8s_adapter.b9b527c6_geometry-bwhet_default_2f28e9cf-8877-11e5-86aa-080027d13a94_26072a79
28e59c96ab16        gcr.io/google_containers/pause:0.8.0                 "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD.e4cc795_geometry-bwhet_default_2f28e9cf-8877-11e5-86aa-080027d13a94_34134204
```

It never recovers from this state unless we explicitly delete the pod `geometry-bwhet`  Based on the annotation of `docker ps` it looks like the `ce0337141e7e` is the expected container, but Kubernetes is looking for `abdf6642fa383`

**Comment by yujuhong** [comment] 2015-11-11 17:39
kubelet looks at the dead containers as well to report status such as "LastTerminationState". 

The status of the `abdf6642fa383` is what interests me.

@brandoncole, next time when it happens, could you check the status of the container that kubelet failed to query? Thanks!
 -  `docker ps -a | grep abdf6642fa383`
 -  `docker inspect abdf6642fa383`

**Comment by yujuhong** [comment] 2016-03-05 02:16
UPDATE: kubelet's behavior has changed and now it'll refuse to sync the pod whose container is in a corrupt state. We are patching kubelet to skip the bad container and sync the pod in #22576.

**Comment by dims** [comment] 2016-06-08 11:25
@yujuhong @slintes now that #22576 has merged should this be closed?

**Comment by yujuhong** [comment] 2016-06-08 16:58
Yes, thanks for reminding.

**Closed by yujuhong** 2016-06-08 16:58 UTC
Labels: kind/bug, priority/P1, team/node
