### ISSUE TITLE
unit flake: PersistentVolumeController could not update claim "default/claim5-2"

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26067] opened 2016-05-23 11:37 UTC
```
--- FAIL: TestControllerSync (0.21s)
	framework_test.go:711: Test "5-2 - complete bind": Claim check failed [A-expected, B-got result]: {"claim5-2":{"metadata":{"name":"claim5-2","namespace":"default","selfLink":"/api/v1/pvc/claim5-2","uid":"uid5-2","creationTimestamp":null,"annotations":{"pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes"}},"spec":{"accessModes":["ReadWriteOnce","ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"volumeName":"volume5-2"},"status":{"phase":"
		
		A: Bound"}}}
		
		B: Pending"}}}
```

cc @lavalamp

**Comment by brendandburns** [comment] 2016-05-23 23:02
My guess is that the failure here is in `waitTest` in `framework_test.go` it's waiting for idle across 10millis which seems like a pretty short period of time.

I think a better approach would be to assert an expected number of changes, and then wait for that.

**Comment by brendandburns** [comment] 2016-05-23 23:29
Closing as a dupe of https://github.com/kubernetes/kubernetes/issues/25967

**Closed by brendandburns** 2016-05-23 23:29 UTC
Labels: kind/flake, team/cluster
