### ISSUE TITLE
e2e addon-update fails from nil pointer

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20016] opened 2016-01-22 19:39 UTC
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/10479/console
```
10:14:37 STEP: copy invalid manifests to the destination dir (without kubernetes.io/cluster-service label)
10:14:37 Jan 22 10:14:37.914: INFO: Executing 'sudo cp addon-test-dir/e2e-tests-addon-update-test-1fqjg/invalid-addon-controller-v1.yaml /etc/kubernetes/addons/addon-test-dir/e2e-tests-addon-update-test-1fqjg/invalid-addon-controller-v1.yaml' on 104.197.222.15:22
10:14:37 Jan 22 10:14:37.929: INFO: Executing 'sudo rm -rf /etc/kubernetes/addons/addon-test-dir' on 104.197.222.15:22
10:14:37 panic: runtime error: invalid memory address or nil pointer dereference
10:14:38 [signal 0xb code=0x1 addr=0x0 pc=0x5736a7]
10:14:38 
10:14:38 goroutine 1752 [running]:
10:14:38 k8s.io/kubernetes/test/e2e.writeRemoteFile.func1(0xc821432000, 0x1a4, 0x142, 0x1d33550, 0x15, 0xc82155d760, 0x142)
10:14:38 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:405 +0x697
10:14:38 created by k8s.io/kubernetes/test/e2e.writeRemoteFile
10:14:38 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:409 +0x552
10:14:38 
10:14:38 goroutine 1 [chan receive, 17 minutes]:
10:14:38 testing.RunTests(0x200e6a0, 0x2a06ac0, 0x1, 0x1, 0x1)
10:14:38 	/usr/local/go/src/testing/testing.go:562 +0x8ad
10:14:38 testing.(*M).Run(0xc820057f08, 0x7)
10:14:38 	/usr/local/go/src/testing/testing.go:494 +0x70
10:14:38 main.main()
10:14:38 	k8s.io/kubernetes/test/e2e/_test/_testmain.go:54 +0x116
10:14:38 
10:14:38 goroutine 17 [syscall, 17 minutes, locked to thread]:
10:14:38 runtime.goexit()
10:14:38 	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
10:14:38 
10:14:38 goroutine 4 [chan receive, 2 minutes]:
10:14:38 github.com/golang/glog.(*loggingT).flushDaemon(0x2a2d660)
10:14:38 	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
10:14:38 created by github.com/golang/glog.init.1
10:14:38 	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
10:14:38 
10:14:38 goroutine 12 [syscall, 17 minutes]:
10:14:38 os/signal.loop()
10:14:38 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
10:14:38 created by os/signal.init.1
10:14:38 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
10:14:38 
10:14:38 goroutine 114 [chan receive]:
```
I think there's a race between the scp and stdin piping: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/addon_update.go#L405. Not sure who owns the test, @kubernetes/goog-control-plane ?

**Comment by zmerlynn** [comment] 2016-01-22 21:58
This is a dupe of #20006

**Closed by zmerlynn** 2016-01-22 21:58 UTC
Labels: kind/flake, priority/P1
