### ISSUE TITLE
Failure cluster [0dcc039d...] `[sig-node] Pod InPlace Resize Container [Serial] Burstable QoS pod, one container with cpu & memory requests + limits - remove CPU limits`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#128858] opened 2024-11-19 13:24 UTC
##### Error text:
```
[FAILED] Timed out after 300.001s.
expected pod to be running and ready, got instead:
    <*v1.Pod | 0xc000f25208>: 
        metadata:
          annotations:
            owner.test: k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1136
          creationTimestamp: "2024-11-13T06:53:05Z"
          labels:
            time: "615755521"
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:annotations:
                  .: {}
                  f:owner.test: {}
                f:labels:
                  .: {}
                  f:time: {}
              f:spec:
                f:containers:
                  k:{"name":"c1"}:
                    .: {}
                    f:args: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resizePolicy: {}
                    f:resources:
                      .: {}
                      f:limits:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                      f:requests:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                    f:securityContext:
                      .: {}
                      f:allowPrivilegeEscalation: {}
                      f:capabilities:
                        .: {}
                   
```
#### Recent failures:
[11/18/2024, 9:36:39 PM ci-cgroupv2-containerd-node-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2/1858700540658061312)
[11/18/2024, 9:11:46 PM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-serial-containerd/1858694423823519744)
[11/18/2024, 8:33:49 PM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1858684860508409856)
[11/18/2024, 7:33:12 PM ci-cgroupv2-containerd-node-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2/1858669509246717952)
[11/18/2024, 4:54:55 PM ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks/1858629495259402240)

/kind failing-test

/sig node

**Comment by esotsal** [comment] 2024-11-20 19:29
@kannon92  as discussed in sig-node meetingI think this is a duplicate of

https://github.com/kubernetes/kubernetes/issues/128837 and https://github.com/kubernetes/kubernetes/issues/128835

it should be fixed by 

https://github.com/kubernetes/kubernetes/issues/128837 and https://github.com/kubernetes/kubernetes/pull/128889

**Comment by dims** [comment] 2024-11-20 23:55
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-serial-containerd
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks

all the jobs have recovered

**Closed** 2024-11-20 23:59 UTC
Labels: sig/node, kind/failing-test, needs-triage
