### ISSUE TITLE
After upgrading nodes they are marked as "NetworkUnavailable"

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28362] opened 2016-07-01 16:34 UTC
```
E0701 15:46:30.814395       5 routecontroller.go:130] Could not create route 019d3522-3fa2-11e6-a04f-42010af00002 10.180.3.0/24 for node e2e-test-filipg-minion-r6b8 after 209.159431ms: googleapi: Error 409: The resource 'projects/ivory-honor-865/global/routes/e2e-test-filipg-019d3522-3fa2-11e6-a04f-42010af00002' already exists, alreadyExists
E0701 15:46:30.816208       5 routecontroller.go:130] Could not create route 5e7093cb-3fa1-11e6-a04f-42010af00002 10.180.1.0/24 for node e2e-test-filipg-minion-apmw after 201.001883ms: googleapi: Error 409: The resource 'projects/ivory-honor-865/global/routes/e2e-test-filipg-5e7093cb-3fa1-11e6-a04f-42010af00002' already exists, alreadyExists
E0701 15:46:30.949416       5 routecontroller.go:130] Could not create route b978bdb7-3fa1-11e6-a04f-42010af00002 10.180.2.0/24 for node e2e-test-filipg-minion-nu8c after 227.942663ms: googleapi: Error 409: The resource 'projects/ivory-h
```

**Comment by erictune** [comment] 2016-07-01 16:35
@dchen1107

**Comment by erictune** [comment] 2016-07-01 16:35
After upgrading 1.2.5 to 1.3.0-beta.3

**Comment by erictune** [comment] 2016-07-01 16:36
@Random-Liu

**Comment by erictune** [comment] 2016-07-01 16:38
@fgrzadkowski found this during upgrade testing.

**Comment by dchen1107** [comment] 2016-07-01 16:46
@fgrzadkowski From the logs you posted above, looks like the route is created ("already exists, alreadyExists"), routecontroller marked this as NetworkUnavailable wrongly. 

On upgrading a node, is the existing route removed? If no, routecontroller should tolerate the RouteExist error simply.

**Comment by dchen1107** [comment] 2016-07-01 16:48
I currently marked it as 1.3 milestone blocker. @Random-Liu could you please conform the issue and fix it if yes? Thanks!

**Comment by Random-Liu** [comment] 2016-07-01 16:51
@dchen1107 Sure, I'll look into it.

**Comment by Random-Liu** [comment] 2016-07-01 17:31
There seems to be some kind of race, the route is created again right after successfully created:
```
I0701 15:39:34.570643       5 routecontroller.go:124] Creating route for node e2e-test-filipg-minion-r6b8 10.180.3.0/24 with hint 019d3522-3fa2-11e6-a04f-42010af00002, throttled 472ns
I0701 15:39:59.456203       5 routecontroller.go:132] Created route for node e2e-test-filipg-minion-r6b8 10.180.3.0/24 with hint 019d3522-3fa2-11e6-a04f-42010af00002 after 24.88555886s
I0701 15:39:59.588080       5 routecontroller.go:124] Creating route for node e2e-test-filipg-minion-r6b8 10.180.3.0/24 with hint 019d3522-3fa2-11e6-a04f-42010af00002, throttled 581ns
E0701 15:39:59.808055       5 routecontroller.go:130] Could not create route 019d3522-3fa2-11e6-a04f-42010af00002 10.180.3.0/24 for node e2e-test-filipg-minion-r6b8 after 220.005512ms: googleapi: Error 409: The resource 'projects/ivory-honor-865/
global/routes/e2e-test-filipg-019d3522-3fa2-11e6-a04f-42010af00002' already exists, alreadyExists
...
```
And report error forever.

**Comment by dchen1107** [comment] 2016-07-01 18:44
One question: If there is such race issue, it should happen no matter upgraded or newly created clusters. Why we never see this before? I am questioning on @fgrzadkowski's test now.

**Comment by dchen1107** [comment] 2016-07-01 18:45
@Random-Liu is trying to reproduce the issue for a while, and will update the test result quickly.

**Comment by Random-Liu** [comment] 2016-07-01 19:01
Here is the node status during the test:

1) At 1.2.5
**kubernetes-master:**
```
  OutOfDisk 	False 	Fri, 01 Jul 2016 11:23:05 -0700 	Fri, 01 Jul 2016 11:20:21 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 	True 	Fri, 01 Jul 2016 11:23:05 -0700 	Fri, 01 Jul 2016 11:20:22 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
```
kubernetes-minion-5r0m:
```
  OutOfDisk 	False 	Fri, 01 Jul 2016 11:23:04 -0700 	Fri, 01 Jul 2016 11:20:36 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 	True 	Fri, 01 Jul 2016 11:23:04 -0700 	Fri, 01 Jul 2016 11:21:23 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
```
kubernetes-minion-a2xp:
```
  OutOfDisk 	False 	Fri, 01 Jul 2016 11:23:06 -0700 	Fri, 01 Jul 2016 11:20:39 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 	True 	Fri, 01 Jul 2016 11:23:06 -0700 	Fri, 01 Jul 2016 11:21:25 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
```
kubernetes-minion-q9ar:
```
  OutOfDisk 	False 	Fri, 01 Jul 2016 11:23:04 -0700 	Fri, 01 Jul 2016 11:20:35 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 	True 	Fri, 01 Jul 2016 11:23:04 -0700 	Fri, 01 Jul 2016 11:21:23 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
```

**2) Upgrade master to 1.3.0-beta.3**
kubernetes-master: (**happened once**)
```
  NetworkUnavailable 	True 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:30:03 -0700 	NoRouteCreated 			Node created without a route
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:30:26 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 01 Jul 2016 11:30:26 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Fri, 01 Jul 2016 11:30:26 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletReady 			kubelet is posting ready status
```
kubernetes-minion-5r0m:
```
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:30:27 -0700 	Fri, 01 Jul 2016 11:20:36 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 		True 	Fri, 01 Jul 2016 11:30:27 -0700 	Fri, 01 Jul 2016 11:21:23 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:29:59 -0700 	RouteCreated 			RouteController created a route
```
kubernetes-minion-a2xp:
```
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:30:33 -0700 	Fri, 01 Jul 2016 11:20:39 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 		True 	Fri, 01 Jul 2016 11:30:33 -0700 	Fri, 01 Jul 2016 11:21:25 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:29:59 -0700 	RouteCreated 			RouteController created a route
```
kubernetes-minion-q9ar:
```
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:30:27 -0700 	Fri, 01 Jul 2016 11:20:35 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  Ready 		True 	Fri, 01 Jul 2016 11:30:27 -0700 	Fri, 01 Jul 2016 11:21:23 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:29:59 -0700 	RouteCreated 			RouteController created a route
```
**3) Upgrade node to 1.3.0-beta.3**
kubernetes-master:
```
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:30:37 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:30:03 -0700 	KubeletReady 			kubelet is posting ready status
```
kubernetes-minion-5r0m:
```
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:34:48 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:34:23 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:34:23 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Fri, 01 Jul 2016 11:40:00 -0700 	Fri, 01 Jul 2016 11:34:59 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  KernelDeadlock 	False 	Fri, 01 Jul 2016 11:39:45 -0700 	Fri, 01 Jul 2016 11:35:06 -0700 	KernelHasNoDeadlock 		kernel has no deadlock
```
kubernetes-minion-a2xp:
```
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:37:21 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:39:57 -0700 	Fri, 01 Jul 2016 11:36:50 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 01 Jul 2016 11:39:57 -0700 	Fri, 01 Jul 2016 11:36:50 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Fri, 01 Jul 2016 11:39:57 -0700 	Fri, 01 Jul 2016 11:37:26 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  KernelDeadlock 	False 	Fri, 01 Jul 2016 11:39:39 -0700 	Fri, 01 Jul 2016 11:37:34 -0700 	KernelHasNoDeadlock 		kernel has no deadlock
```
kubernetes-minion-q9ar:
```
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Fri, 01 Jul 2016 11:39:28 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Fri, 01 Jul 2016 11:39:59 -0700 	Fri, 01 Jul 2016 11:39:02 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 01 Jul 2016 11:39:59 -0700 	Fri, 01 Jul 2016 11:39:02 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Fri, 01 Jul 2016 11:39:59 -0700 	Fri, 01 Jul 2016 11:39:39 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  KernelDeadlock 	False 	Fri, 01 Jul 2016 11:39:47 -0700 	Fri, 01 Jul 2016 11:39:46 -0700 	KernelHasNoDeadlock 		kernel has no deadlock
```

**Comment by dchen1107** [comment] 2016-07-01 19:14
Based on @Random-Liu's test, I think this is a red herring. I removed 1.3 milestone from it and dropped the priority to P1.

**Comment by Random-Liu** [comment] 2016-07-01 22:45
I've run the test for several times, and never reproduce the problem #28389. I've sent a walkaround for this, but I'm not sure whether we want to walk around it before we understand it.

**Comment by dchen1107** [comment] 2016-08-05 17:54
Close this as unproducible.

**Closed by dchen1107** 2016-08-05 17:54 UTC
Labels: priority/P1, team/control-plane
