### ISSUE TITLE
ScheduledJob of kubernetes never gets called

### ISSUE THREAD

**Issue by sachincab** [kubernetes/kubernetes#35508] opened 2016-10-25 10:58 UTC
**What happened**:
We created a scheduled jobs from example mentioned on documentation.
kubectl run hello --schedule="0/1 \* \* \* ?" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"

kubectl get scheduledjob hello
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
hello     0/1 \* \* \* ?   False     0         <none>

It never create a associated jobs.

**What you expected to happen**:
It should create jobs as per scheduled job specification.

**How to reproduce it** (as minimally and precisely as possible):
We noticed this problem with v1.4.3 however on stage cluster we run v1.4.4 and it does create associated jobs there.

**Output from stage cluster:**

```
kubectl get jobs
NAME                     DESIRED   SUCCESSFUL   AGE
hello-1859028810         1         1            11m
hello-1934853965         1         1            12m
hello-1934985037         1         1            9m
hello-1935116109         1         1            6m
hello-2010810192         1         1            10m
hello-2010941264         1         1            7m
hello-2011072336         1         1            4m
hello-2011203408         1         1            1m
hello-2086766419         1         1            8m
hello-2086897491         1         1            5m
hello-2087028563         1         1            2m
hello-2162853718         1         1            3m
hello-2162984790         1         1            33s

```

**Kubernetes version** (use `kubectl version`):
1.4.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1122.3.0
- **Kernel** (e.g. `uname -a`): Linux -1 4.7.0-coreos-r1
- **Others**: Enabled  --runtime-config=batch/v2alpha1 in apiserver flag.

Is this issue related to specific kubernetes version like v1.4.3 where it couldn't create associated jobs as per scheduled job specification?

Please let us know if you need any more information on this.
Thanks!

**Comment by kargakis** [comment] 2016-10-25 16:44
@soltysh

**Comment by janetkuo** [comment] 2016-10-25 17:05
I cannot reproduce this in 1.4.3. 

```console
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.3-dirty", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"dirty", BuildDate:"2016-10-25T17:01:10Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.3-dirty", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"dirty", BuildDate:"2016-10-25T17:01:10Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl run hello --schedule="0/1 * * * ?" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"
scheduledjob "hello" created

$ kubectl get scheduledjob 
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
hello     0/1 * * * ?   False     0         <none>

$ kubectl get jobs                                                                                                                                    
NAME               DESIRED   SUCCESSFUL   AGE
hello-3955992862   1         1            27s
```

It'd help if you can show us the controller manager log and then we can debug when it failed

**Comment by soltysh** [comment] 2016-10-25 19:53
Same here, using:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-25T19:45:57Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-25T19:45:57Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```
working as expected. 

To add more to what Janet already asked for it would be nice to show us the events for that SJ, as well.

**Comment by peay** [comment] 2016-11-06 13:19
Not sure if this is related (or if I should open a separate issue), but I have been running into similar symptoms with 1.4.0 where my `scheduledjob` ressources often stop to create jobs.

The controller manager has logs like

````
I1106 13:06:56.985296       1 event.go:217]
Event(api.ObjectReference{
Kind:"ScheduledJob",
Namespace:"default",
Name:"my-cron-job",
UID:"f953845e-9ec5-11e6-ab06-0025b500002f",
APIVersion:"batch",
ResourceVersion:"14861047",
FieldPath:""}):
type: 'Warning'
reason: 'FailedCreate' Error creating job: jobs.batch "my-cron-job-1476364091" already exists
````
and sure enough they'll be a job with this name dating from like the day before or something like that. I've seen this with jobs running every 5mins and every 30mins, haven't tested with anything else so far.

I've had a glance at things like https://github.com/kubernetes/kubernetes/blob/56bbfd259a6f45dfbcfb6f3c9f61643a787ed067/pkg/controller/scheduledjob/utils.go#L203 to try and figure out why there would be hashing collision but didn't see anything suspicious.

**Comment by soltysh** [comment] 2016-11-07 16:25
@peay your problem is covered in https://github.com/kubernetes/kubernetes/issues/34447, it's about creating duplicate job.

**Comment by peay** [comment] 2016-11-07 21:19
Ah, I hadn't found this issue, thanks a lot!

**Comment by DaanOlbrechts** [comment] 2016-11-16 14:07
@sachincab I had this very same issue, in the following scenario:
 - Fresh Kubernetes (v1.4.4 or v1.4.5) installed using kubeadm 
 - Set `--runtime-config=batch/v2alpha1` flag in the kube-apiserver manifest file (which promptly restarts it).
 - `kubectl get scheduledjobs` shows created scheduled jobs, but jobs are never created.

The issue was resolved in my setup by restarting the Docker service after enabling the flag in the manifest. This fix was mentioned in this [related issue](https://github.com/coreos/coreos-kubernetes/issues/742#issuecomment-258317601).

**Comment by soltysh** [comment] 2016-11-16 14:19
@sachincab with #34447 being fixed can you check if you're still experiencing problem, other option is @DaanOlbrechts pointer. I'm not sure what else might be wrong here. If you still having problems please provide details on your setup so that I could reproduce and fix the problem. Thanks.

**Comment by sachincab** [comment] 2016-11-18 11:35
@soltysh I could not able to reproduce this issue anymore however it might be docker restart pointed by @DaanOlbrechts help in my scenario as well.

@DaanOlbrechts , is it restart of docker on master or worker node solve the problem for you?

In my case if I remembered correctly, I did rollout our nodes in the cluster which solve the problem.

**Comment by DaanOlbrechts** [comment] 2016-11-18 12:40
@sachincab Just restarting Docker on the master node was enough.

**Comment by sachincab** [comment] 2016-11-18 15:52
@DaanOlbrechts that explain as I did rollout master instances as well and jobs were created properly.

**Comment by soltysh** [comment] 2016-11-21 09:19
@sachincab are you ok with closing this issue in that case?

**Comment by sachincab** [comment] 2016-11-21 11:37
@soltysh yeah sure, I am ok to close this issue.

**Closed** 2016-11-21 13:03 UTC
Labels: area/workload-api/cronjob, team/workloads

**Comment by MikaelCluseau** [comment] 2017-01-10 06:08
FWIW I had this same issue on my cluster (spoiler: restart you controller manager after enabling the API):
* upgraded to 1.5.1
* failed to schedule a CronJob due to api not enabled
* enabled the API on the `apiserver`  (flag `--runtime-config=batch/v2alpha1`)
* then scheduled a CronJob. No executions took place
* restarted kube-scheduler. No executions took place
* restart kube-controller-manager. Executions took place successfully

**Comment by kargakis** [comment] 2017-01-10 09:23
Isn't it documented somewhere? You should restart the controller manager to
enable the scheduledjob controller to run cc @soltysh

**Comment by MikaelCluseau** [comment] 2017-01-10 10:22
I don't know, but Google search pointed me here, so I documented the solution here.

**Comment by soltysh** [comment] 2017-01-12 12:10
Only controller-manager restart should be required, scheduler has nothing to do with that, iirc. I've created https://github.com/kubernetes/kubernetes.github.io/pull/2215 to addressed the issue.
