### ISSUE TITLE
kubectl get svc could show truncated hostname for Service.Type=Loadbalancer on AWS

### ISSUE THREAD

**Issue by xied75** [kubernetes/kubernetes#18019] opened 2015-12-01 14:42 UTC
Dear all,

I was following the Guestbook example on aws, when I do step seven
```
kubectl get services
```
The output column for External_IP is simply empty. Is this already reported to do with k8s or it's my setting up of aws wrong?

Best,

Dong

**Comment by fabioy** [comment] 2015-12-01 23:20
Maybe this could help: http://stackoverflow.com/questions/29223521/public-ip-on-service-for-aws-in-kubernetes-fails

**Comment by fabioy** [comment] 2015-12-01 23:21
And closing this issue for now (since it's not a product bug).

If the issue is still not addressed, please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by xied75** [comment] 2015-12-02 08:57
@fabioy It does not help at all, if you bother to read his answer there. I think his answer doesn't make any sense at all. What does 'you should use private IP' means? You can access your Guestbook on internet via 10.0.0.0?

In fact I got my Guestbook showing by looking at the NICs that was created after Guestbook service is created with LoadBalancer type.

My question was more to do with if I WANT to see the external IP in kubectl, is there code missing in k8s? If so I'm willing to make a PR. I certainly understand your stuff works in GCE, and this is to do with aws, so be it, just tell me IT IS missing so people can help.

This is GitHub, not SO, you don't need to be overzealous to close stuff people raise.

Would you mind to re-open this?

**Comment by fabioy** [comment] 2015-12-02 13:49
I see. Apologies for the quick close -- I was triaging a large backlog of issues accumulated over the US Thanksgiving holiday. Your comment clarifies why it's a k8s issue (and not just support).

Reopening the issue.

**Comment by xied75** [comment] 2015-12-08 15:34
Dear all, I have plan to look at the code regarding this issue, if no other people got time/interest. But before I do that I have a general question, given my limited knowledge on GCE.

In aws, when you use external Load Balancer, you get a long DNS name for the endpoint:
```
a9b5e0fbf9d9b11e5a5140aef4df3274-1191232749.eu-west-1.elb.amazonaws.com
```

Underneath there are two Public IPs created and owned by aws being round-robined by Route53.

The recommendation is to create CNAME for this long DNS name, and NOT use the Public IPs because it could be changed by aws.

If so, then we can't really display EXTERNAL_IP as the current kubectl designed, as we are NOT supposed to use the IP at all. The best we can do is display the DNS name for the service, I guess there will be some layout issues to make the columns look nice, if we managed to code the necessary bits.

But how is GCE handling this? Is the IP you got for the service from load balancer persistent and owned by you rather GCE?

Best,

Dong

**Comment by bigkraig** [comment] 2015-12-11 17:51
You can still get the hostname for the load balancer by doing a describe service:
```
$ kubectl describe services guestbook
Name:			guestbook
Namespace:		default
Labels:			app=guestbook
Selector:		app=guestbook
Type:			LoadBalancer
IP:			10.200.20.221
LoadBalancer Ingress:	a21dc42289f9d11e58e4b12b6367fabe-842960501.us-east-1.elb.amazonaws.com
Port:			<unnamed>	3000/TCP
NodePort:		<unnamed>	32269/TCP
Endpoints:		10.244.37.4:3000,10.244.39.3:3000,10.244.76.3:3000
Session Affinity:	None
No events.
```

**Comment by xied75** [comment] 2015-12-16 09:08
@bigkraig You are correct, so what do you think about the IP? Do we still somehow expect it or just make it clear in the documentation and close this issue?

**Comment by bigkraig** [comment] 2015-12-16 16:07
I think we make it clear in the documentation that you should use the hostname and forget about IPs when dealing with ELBs.

**Comment by justinsb** [comment] 2016-02-12 13:51
I agree that we should probably update the docs to make this clearer.

I would love to set up a CNAME but we don't manage external DNS at the moment in k8s.  I would love to have it appear in the `kubectl get` output but it's very long and when the output gets too wide the table display is effectively broken (annoying, but important).

So for 1.2 I think docs is the best we can do...

**Comment by justinsb** [comment] 2016-02-12 18:02
Proposed a doc change in #21145

**Comment by thockin** [comment] 2016-02-23 00:33
The doc is in.  We can close this?

As another idea, we could show the IP-or-hostname, but if len(hostname) > 16, show hostname[0:13] + "..." in normal output and show the whole thing in -o wide.

We don't have a lot of precedent for this, but it doesn't sound awful to me.  I'm going to move this out of the milestone but leave it open.  If anyone disagrees, let me know.

**Comment by xied75** [comment] 2016-02-23 11:09
Looks great. Thanks to all for the work. :+1:

**Comment by justinsb** [comment] 2016-02-23 17:06
I already had opened #21526 as a help-wanted for a future improvement to kubectl output, so I'm going to close this one.  The doc change is in for 1.2, hopefully we'll do something nicer in 1.3 via #21526

**Closed by justinsb** 2016-02-23 17:06 UTC
Labels: area/networking, area/platform/aws, component/kubectl, kind/feature, priority/P2, team/cluster

**Comment by dengemann** [comment] 2016-03-14 19:13
I'm having the same issue, working on master branch, but the proposed remedy does not apply for me: is it expected that `kubectl describe services <service name>` gives the same IP address as the usual get services listing. In the present case we're trying to access a [jupyter notebook](http://jupyter.org/) that is hosted on the master, I'm running the https://github.com/ogrisel/docker-distributed container on a 4 node cluster. cc @ogrisel. Any hint on how to access the master node from the outside would be highly appreciated.

Another question of clarification:

> As another idea, we could show the IP-or-hostname, but if len(hostname) > 16, show hostname[0:13] + "..." in normal output and show the whole thing in -o wide.

what do you mean by hostname in this case?

@justinsb @fabioy @bigkraig @xied75

**Comment by therc** [comment] 2016-06-02 23:16
See #26749 for a potential fix
