### ISSUE TITLE
`kubectl config view --minify` needs a top-level alias

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#10516] opened 2015-06-30 00:04 UTC
Here's the question I want to answer: when I use kubectl, what cluster am I talking to?

As a developer with several clusters, this is a really important question to me.

I was looking through `kubectl config --help` and I saw the options are:

```
  view            displays Merged kubeconfig settings or a specified kubeconfig file.
  set-cluster     Sets a cluster entry in kubeconfig
  set-credentials Sets a user entry in kubeconfig
  set-context     Sets a context entry in kubeconfig
  set             Sets an individual value in a kubeconfig file
  unset           Unsets an individual value in a kubeconfig file
  use-context     Sets the current-context in a kubeconfig file
```

Only asking @jlowdermilk did I learn that `kubectl config view --minify` was what I wanted. This seems kind of crazy! `--minify`? To see my current context?

@bgrant0607 how would you feel about one of the following options?
1. Top-level "GET" analogs for the "PUT" methods (get-cluster, get-credentials, get-context, ...)
2. Have `kubectl config view` output _only_ the current context by default, and have a flag like `--full` for the full config (rather than having to pass `--minify` for the current context).

(Leaving this for oncall and @bgrant0607 to determine priority.)

**Comment by jlowdermilk** [comment] 2015-06-30 00:06
cc @satnam6502, who asks me about `--minify` roughly every other week :)

**Comment by thockin** [comment] 2015-06-30 05:11
I think I filed a very similar bug at some point - the UX here is not at
all obvious.

Here's how I would naively expect it to work:

```
kubectl config get: get current config

kubectl config list: list configs (short)

kubectl config list -v: list configs (longer)

kubectl config use: select which config is current

some variants on new/set/unset
```

**Comment by bgrant0607** [comment] 2015-10-08 05:53
Dupe of #8593

**Comment by dims** [comment] 2016-06-09 18:25
@thockin @mbforbes - This seems to be a Dup of #8593 if so can we please close this?

**Comment by kargakis** [comment] 2017-06-03 00:06
@kubernetes/sig-cli-misc

**Closed** 2017-06-03 22:34 UTC
Labels: area/kubectl, priority/backlog, sig/cli
