### ISSUE TITLE
[Flaky Test] [NodeConformance]  when querying /stats/summary should report resource usage through the stats api [ubuntu]

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98649] opened 2021-02-01 04:10 UTC
**Which jobs are flaking**: `ci-kubernetes-node-kubelet` 

**Which test(s) are flaking**: `Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api` 

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master&include-filter-by-regex=%20should%20report%20resource%20usage%20through%20the%20stats%20api

**Reason for failure**:

```
I0131 20:32:38.016] • Failure [41.908 seconds]
I0131 20:32:38.017] [k8s.io] Summary API [NodeConformance]
I0131 20:32:38.017] /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
I0131 20:32:38.017]   when querying /stats/summary
I0131 20:32:38.017]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
I0131 20:32:38.017]     should report resource usage through the stats api [It]
I0131 20:32:38.017]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
I0131 20:32:38.018] 
I0131 20:32:38.018]     Failed after 15.161s.
      
I0131 20:32:38.018]     Expected
I0131 20:32:38.018]         <string>: Summary
I0131 20:32:38.018]     to match fields: {
I0131 20:32:38.018]     .Node.SystemContainers[pods].CPU:
I0131 20:32:38.019]     	Expected
I0131 20:32:38.019]     	    <string>: CPUStats
I0131 20:32:38.019]     	to match fields: {
I0131 20:32:38.019]     	.UsageNanoCores:
I0131 20:32:38.019]     		Expected
I0131 20:32:38.019]     		    <*uint64 | 0xc001528fe0>: 0
I0131 20:32:38.020]     		To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc000c8cab0 Expected
I0131 20:32:38.020]     		    <uint64>: 0
I0131 20:32:38.020]     		to be >=
I0131 20:32:38.020]     		    <int>: 10000})]
I0131 20:32:38.020]     	}
I0131 20:32:38.020]     	
I0131 20:32:38.021]     }
```

**Anything else we need to know**:
Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=when%20querying%20%2Fstats%2Fsummary%20should%20report%20resource%20usage%20through%20the%20stats%20api

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1355967179257810944

> _**NOTES:**_  45 failures out of 74048 builds from 1/17/2021, 7:00:22 PM to 1/29/2021, 10:40:01 PM

/sig node

**Comment by ehashman** [comment] 2021-03-10 18:27
/close

duplicate of https://github.com/kubernetes/kubernetes/issues/96068

**Closed** 2021-03-10 18:28 UTC
Labels: kind/flake, needs-triage, sig/node
