### ISSUE TITLE
kubectl wait should wait for resources to be available

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#87352] opened 2020-01-18 09:03 UTC
**What happened**:
I am installing a Kubernetes operator using Helm. The operator itself registers CRDs. Then I run
```
$ kubectl wait --for=condition=Established crds -l app=kubedb --timeout=5m
error: no matching resources found
```

**What you expected to happen**:

I expected `kubectl wait` to wait for the resources to be available until timeout.

When I am using --for != delete, as an user, I know the resource will become available and meet the for condition. I would expect `kubectl wait` to first wait long enough the label selector to return some result and then wait until those conditions are meet.

Either the kubectl wait command should wait for the full timeout duration or there should be a new --initial-timeout so that we tell `kubectl wait` to wait long enough for the resources to be available by the label selector.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/wait/wait.go#L249-L251

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/issues/65868

**Environment**:
$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.17.0

**Comment by liggitt** [comment] 2020-01-18 15:10
duplicate of https://github.com/kubernetes/kubernetes/issues/83094 and https://github.com/kubernetes/kubernetes/issues/83242

/close

**Closed by liggitt** 2020-01-18 15:10 UTC
Labels: kind/bug, sig/cli
