### ISSUE TITLE
subPath = file bug

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#45613] opened 2017-05-10 21:28 UTC
k8s 1.6.3 just landed and broke a lot of our systems. The issue shows as:
2017-05-10 20:07:19.245598 | NAME                       READY     STATUS                                                                                                                                      RESTARTS   AGE
2017-05-10 20:07:19.245760 | test-ceph-init-mon-hx3h1   0/1       mkdir /var/lib/kubelet/pods/c4fe3290-35bb-11e7-8ad3-fa163eceb3e9/volumes/kubernetes.io~configmap/resolv-conf/resolv.conf: not a directory   0          3m

The issue is, we have subPath set to a file in a configmap to map it into the right place in our container. But the new code assumes subPath is a directory and always does a mkdir over it. This causes things to fail.

The PR in question is:
https://github.com/kubernetes/kubernetes/commit/21871aa94525744dbc391fda841e42feee0671d1

**Comment by wongma7** [comment] 2017-05-10 21:30
cc @kubernetes/sig-storage-bugs
/assign wongma7

**Comment by kfox1111** [comment] 2017-05-10 21:40
Its also related to:
https://github.com/kubernetes/kubernetes/pull/43775

**Comment by zhouhaibing089** [comment] 2017-05-11 14:33
@wongma7 can you ensure your fix is picked to 1.6 branch, too?

**Comment by wongma7** [comment] 2017-05-11 14:36
yes, I will.

**Comment by sbezverk** [comment] 2017-05-11 22:17
any chance it gets finally committed? our testing gates are all red because of this issue..

**Comment by wongma7** [comment] 2017-05-11 22:20
I brought it up in the sig-storage meeting today so priority was raised to critical-urgent and sig node was pinged. I guess we could make some more noise, I'll try finding people on slack

**Comment by sbezverk** [comment] 2017-05-12 21:15
Would be great to get it out one way or another. I have heard other people also see this issue.

**Comment by wongma7** [comment] 2017-05-12 21:27
Status: it's merging to master right now & I just opened a cherry-pick for it into 1.6 https://github.com/kubernetes/kubernetes/pull/45749. 

I'm not sure what the procedure is for expediting a point release, but I suppose it would be enough if those other people +1 this issue, it may help the folks in charge judge the severity of the bug.

@ethernetdan and @enisoc what's the procedure here? The context is that a bug was introduced with 1.6.3 that makes it so that certain pods (that mount a volume's file using the subPath) fail to start. Thanks!

**Comment by wongma7** [comment] 2017-05-13 01:29
FYI, closed by mistake, sorry. We still need to track it 'til it's fixed in 1.6.x

**Comment by enisoc** [comment] 2017-05-13 01:29
@wongma7 I think an expedited release would be warranted if there are a large number of users who both (1) are affected by this issue, and (2) need something in 1.6.3 so rolling back to 1.6.2 is not good enough.

I don't know how common it is for users to rely on this feature, so any signal we can get on that would be helpful.

**Comment by sbezverk** [comment] 2017-05-13 12:36
@enisoc this feature is used a lot by kolla-kubernetes project.  Rolling back is problematic, our gating system works with centos and Ubuntu images, with centos we can go back to 1.6.2 but with Ubuntu, it looks like 1.6.2 binaries have been already removed. We use binaries which are provided by repo and not static files.

**Comment by zhouhaibing089** [comment] 2017-05-14 06:21
Perhaps we should add an e2e test case for subPath.

**Comment by v1k0d3n** [comment] 2017-05-15 11:57
yeah, i have to agree with @kfox1111 and @sbezverk on this one. our projects are very similar, and we're experiencing the same thing on our end w/v1.6.3.

**Comment by enisoc** [comment] 2017-05-15 17:59
After discussing with @saad-ali, I am planning to expedite v1.6.4 to fix this. However, I will wait for the e2e test, which I believe @wongma7 is working on.

**Comment by saad-ali** [comment] 2017-05-15 18:02
Keeping open until v1.6.4 ships with fix.

**Comment by wongma7** [comment] 2017-05-15 22:02
@enisoc @saad-ali the e2e test PR is here: https://github.com/kubernetes/kubernetes/pull/45852 . They cover both this issue and the original one I was trying to fix, #43775.

**Comment by rdsubhas** [comment] 2017-05-18 10:53
@saad-ali should kubernetes yank the binary packages for kubelet/kubeadm/etc that were released for 1.6.3 - until 1.6.4 gets released? Because many of us who are just installing kubeadm/kubelet/etc with 1.6.* have found that things suddenly start break.

`subPath` is not an alpha/beta feature, it's a core feature. Right now, its in the `KNOWN ISSUES` in the release note and stuff breaks until 1.6.4 is released. This 1.6.3 is a broken release and nobody should ever install it right?

**Comment by sbezverk** [comment] 2017-05-18 12:27
@rdsubhas as a workaround we compiled 1.6.3 kubelet with the one fix. If you are interested, please let me know I will share the link, I have it posted on GitHub.

**Comment by rdsubhas** [comment] 2017-05-18 12:32
@sbezverk thanks, but we have pinned kubernetes versions for now...

@saad-ali I can see that k8s 1.6.4-beta.1 is already being tagged. Great work from the team! Looks like k8s 1.6.4 will supersede 1.6.3 shortly. Thanks!

**Comment by enisoc** [comment] 2017-05-19 20:16
If you experienced this issue in v1.6.3, please try [v1.6.4](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v164) and report back on this bug. Thanks.

**Comment by kfox1111** [comment] 2017-05-19 23:45
@enisoc We've got a test all queued up. Just waiting for the rpms/debs to hit.

**Comment by saschagrunert** [comment] 2017-05-21 21:20
So I can confirm that the mentioned bug is fixed with 1.6.4. great, thanks. 👍🏻👌🏼

**Comment by saad-ali** [comment] 2017-05-22 18:21
Closing. Issue is fixed in https://github.com/kubernetes/kubernetes/releases/tag/v1.6.4 release

**Closed by saad-ali** 2017-05-22 18:21 UTC
Labels: kind/bug, priority/critical-urgent, sig/storage

**Comment by samiaben88** [comment] 2017-06-01 16:03
Hi
I'm facing this error, I'm using ansible to deploy kubernetes, so it brings the version: 1.5.2 , is their a way to resolve this issue ?
Thanks.

**Comment by wongma7** [comment] 2017-06-01 16:29
@samiaben88 this specific bug was introduced with 1.6.3 and fixed with 1.6.4. Please open a separate issue with more details about your issue

**Comment by samiaben88** [comment] 2017-06-02 08:15
ok thank u
