### ISSUE TITLE
Cannot print base64 CA data with jsonpath

### ISSUE THREAD

**Issue by sethvargo** [kubernetes/kubernetes#64983] opened 2018-06-11 15:20 UTC
/kind bug

**What happened**:

Tried to extract raw CA data (base64 encoded) using jsonpath. I got (what appears to be) the json representation of an `[]byte`.

```
$ kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'

[45 45 45 45 45 66 69 71 73 78 32 ...]
```

**What you expected to happen**:

I expected to get a base64 encoded string of the CA data, like:

```
LS0tLS1CRUdJTiBD...
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

1. `kubectl config view --raw` shows the value as b64 encoded correctly:

    ```yaml
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBD...
    ```

1. It works with `-json` and `jq` (at the expense of introducing jq):

    ```
    $ kubectl config view --raw -o json | jq '-r .clusters[0].cluster."certificate-authority-data"'
    LS0tLS1CRUdJTiBD...
    ```

**Environment**:

- Kubernetes version (use `kubectl version`): 

    ```
    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Darwin, but also reproduced on Debian 9
- Kernel (e.g. `uname -a`): Darwin Kernel Version 17.6.0

/sig kubectl
/sig cli

**Comment by ahmetb** [comment] 2018-06-11 19:08
duplicate of https://github.com/kubernetes/kubectl/issues/489
/close

**Closed by ahmetb** 2018-06-11 19:08 UTC
Labels: kind/bug, sig/cli
