### ISSUE TITLE
Possible e2e flake: Services [It] should be able to up and down services

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#23668] opened 2016-03-31 02:59 UTC
```
Failure [270.683 seconds]
[k8s.io] Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:420
  should be able to up and down services [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:276

  Expected error:
      <*errors.errorString | 0xc20904ddb0>: {
          s: "Only 2 pods started out of 3",
      }
      Only 2 pods started out of 3
  not to have occurred
```
[Full log](https://doc-0eiou-170d0-s-googleusercontent.commondatastorage.googleapis.com/gs/uicqmja7vc0lv3u64moqnrkd5drugvov/5sbjncl6th3ql2ejg7akj8mlulmrlpp8/1459386000000/kubernetes-jenkins/06802105212680952678/ChJrdWJlcm5ldGVzLWplbmtpbnMSSXByLWxvZ3MvcHVsbC8yMzY0Ni9rdWJlcm5ldGVzLXB1bGwtYnVpbGQtdGVzdC1lMmUtZ2NlLzM0MDA4L2J1aWxkLWxvZy50eHQ?a=AGjQbs7OAxYl0063Ko0sZhD9LvUs1SGvXG-IiLJ_u_ix8B12NmyWsfotiPnLZBEB1JDUL3bXifOEcjj6q0LxLeBMKOCN0ZFS-FFyHNSAHK5maqemcVAp8KE7FtFhooiqUpeDtCsjfEGViryxWXQehfppBm9xD_4vu6z4mda5zu7lBP__Tf6hrhMpB6Tm5P8YSI-0pP1WVoumVnUnmYhmJ54GOtZrx_ADvXT4RDPsc-rmNmOJIX-vXM37HidWsZxtq-ido8JT-41R9Lk3HtUScNtKRMXMui0n9HF0F4TYd3CA-t1BVgj_6CnQEGwocvzMMyfxBDjUH9QsuZVTRZjSmpCs0wr_A4AO7FqybMlogrtNBIieG5ErGxPQwvPQn15doHlbvcUqXgy7VbL8HN7I26bEGcY7azzkvcJpr17S1ZZ3WW7tQtNifX1t03CSC5S-t0Z5PvoqQOMVIUpk1PPP6Elv-esMO59XxqZEX3ZuvspQ2KwjtJp-P-MOai6onSbyPpUMD2wQBZmYwB4mpqsoFxtdglEaGr9Fg7qpNepArA4T2B5NqeLjj2DyPdjG7SVSfLKygfgCa-veUfkkir_d03_qHg6rlyxrKQ512KQOm9gcYBpEIpLpQgPvZ865UtQTz4kthcErwwYPPo1mcmi9d1eur6Reg4Yu2zEneHdPFcdcxNlTnAknY5lrSwt_Dk2amsHHpDfUrHwAltcP7EDyUHDtdDc1IYxFEzbLie7WYAR-oeGz6jVfWvpDrEzG69r9I5xHGYQKDBn_VX55XCDUYKs1hy1DnSvJ9w&nonce=e577e6sjm6po4&user=06802105212680952678&hash=nkiqr51rt9i7uj8iurt0ln4ulf50rnil)
Saw this on the PR builder for #23646. Might be the PR's fault. Filing this to remind myself to follow up.

**Comment by bprashanth** [comment] 2016-03-31 04:44
That looks like image pulling hang, the pod in question is service1-do4cj and it landed on node https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23646/kubernetes-pull-build-test-e2e-gce/34008/artifacts/e2e-gce-builder-3-0-minion-ki6z/?pli=1
```
I0331 01:39:19.438955    3456 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-services-7l7v3", Name:"service1-do4cj", UID:"628d1481-f6e1-11e5-9a1f-42010af00002", APIVersion:"v1", ResourceVersion:"1880", FieldPath:"spec.containers{service1}"}): type: 'Normal' reason: 'Pulling' pulling image 
...
I0331 01:43:39.364324    3456 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-services-7l7v3", Name:"service1-do4cj", UID:"628d1481-f6e1-11e5-9a1f-42010af00002", APIVersion:"v1", ResourceVersion:"1880", FieldPath:"spec.containers{service1}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "gcr.io/google_containers/serve_hostname:v1.4"
```

And of course I see the registry endpoint ping failures
```
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
I0331 01:38:44.179238    3456 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-kubectl-hf6bt", Name:"update-demo-nautilus-emehh", UID:"4acf79b7-f6e1-11e5-9a1f-42010af00002", APIVersion:"v1", ResourceVersion:"1026", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "update-demo" with ErrImagePull: "unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable"
```

So closing as dupe of https://github.com/kubernetes/kubernetes/issues/20550

**Closed by bprashanth** 2016-03-31 04:44 UTC
Labels: team/cluster
