### ISSUE TITLE
apiserver uses only one etcd node even when given several

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#6559] opened 2015-04-08 03:21 UTC
I ran kube-apiserver with five etcd nodes and kube-apiserver only sent reads and writes to one. If I took that node down, all reading and writing to etcd stopped with errors in the log about connection refused to that node's IP. There was no load balancing of reads or writes across the nodes of the cluster.

Using Kube version cb0850d7cf0847c969b2a2988a3c1d60eb49f4ae.

Here's the command line I'm using to start apiserver:

```
/usr/local/bin/kube-apiserver --address=127.0.0.1 --etcd_servers=http://10.240.142.196:4001,http://10.240.134.83:4001,http://10.240.4.53:4001,http://10.240.237.203:4001,http://10.240.82.164:4001 --cloud_provider=gce --admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,ResourceQuota --allow_privileged=False --portal_net=10.0.0.0/16 --cluster_name=thekubey --tls_cert_file=/srv/kubernetes/server.cert --tls_private_key_file=/srv/kubernetes/server.key --secure_port=6443 --token_auth_file=/srv/kubernetes/known_tokens.csv --v=2
```

I haven't yet reproduced this beyond my one instance of kube-apiserver, so if someone could confirm or deny that this is happening more broadly, that would be very helpful.

**Comment by bgrant0607** [comment] 2015-04-08 04:35
We just call etcd.NewClient with the list:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L187
https://github.com/coreos/go-etcd/blob/master/etcd/client.go#L86

It looks to me like this doesn't load-balance:
https://github.com/coreos/go-etcd/blob/6c0c031546a10bafb185c792b0b05cf7dccd2754/etcd/requests.go#L356

Assuming sequential consistency, that's the right thing for writes, maybe not for reads, depending on various implementation details. In my experience with similar systems, reads hitting non-leader replicas in the quorum may slow down writes to the master more than reading from the master due to an increase in variance in replicating transactions. To actually scale reads, one needs asynchronously updated (eventually consistent) read-only replicas.

**Comment by bgrant0607** [comment] 2015-04-08 04:35
cc @hchoudh

**Comment by dchen1107** [comment] 2015-04-08 17:23
subscribe to the issue.

**Comment by davidopp** [comment] 2015-04-08 21:54
Sort-of related: #5589

**Comment by quinton-hoole** [comment] 2015-04-08 21:58
cc: quinton-hoole@

**Comment by ghodss** [comment] 2015-04-09 10:57
To me, this is totally unacceptable. What's the purpose of using a database like etcd which operates in a cluster if you literally use only one server of the cluster, and go hard down when that server goes down? IMO it should be a 1.0 goal to both load balance across the cluster for reads, and not completely fail if the one etcd node you're using goes down. Keep in mind the current behavior doesn't even recover gracefully to use a different node if the other N nodes of your cluster are up and functioning properly.

I'm out until 4/20 starting tomorrow, but happy to discuss further on this when I return.

**Comment by derekwaynecarr** [comment] 2015-04-09 13:49
Cc @tstclair - I thought you were looking in this area so may want to weigh in.

**Comment by ArtfulCoder** [comment] 2015-04-09 14:10
#6422

**Comment by xiang90** [comment] 2015-04-09 14:18
@bgrant0607 
> Assuming sequential consistency, that's the right thing for writes, maybe not for reads,

If you read from one etcd member synchronously, etcd guarantees sequential consistency for both write and read. 

If you want to have sequential consistency guarantee across the cluster/clients (linearizable) , you need to use `quorum-read`. It is kind of expensive today both in `throughput` and `latency`. But we plan to improve in the future. Sacrificing `latency` should be enough.

Let me know if there is anything I can help with.

**Comment by bgrant0607** [comment] 2015-04-09 16:20
@ghodss HA is not on the 1.0 roadmap, though we'll want it shortly thereafter. We understand that some people may want it sooner. That would be great -- PRs welcome. 

@xiang90 What's the proper way to ensure failover to active/healthy replicas? How long should we expect a client to take to detect a replica failure and to redirect?

**Comment by davidopp** [comment] 2015-04-10 06:08
I think we can do this in two steps:

1) Start running etcd in a replicated configuration: Raft propagates writes to all replicas. All reads and writes go through the etcd leader. All reads and writes go through the k8s API server.

2) Have an API server always running in a "standby" mode on every etcd replica node, except on the etcd replica node that is the etcd leader; that API server is the "active" one. If a node fails, the API server on the node that becomes the new etcd leader becomes the active API server. All reads/write still go through the one active k8s API server. The advantage of (2) over (1) is that failover is very fast.

[Sharding the API server, so all replicas are active, would be a third step that I don't think is necessary any time soon.]

Load-balancing reads across etcd replicas could be introduced at any time but introduces consistency issues, as others have mentioned.

**Comment by timothysc** [comment] 2015-04-10 15:12
@xiang90 does this matter when you have a 3-node quorum?  If so, how?

**Comment by timothysc** [comment] 2015-04-10 15:16
So fwiw we see no real issue here, unless you wanted to rotate "initial" traffic across servers, b/c raft will still propagate anyway (thus connection).  

What/if any is the actual issue here? 

cc @rrati, @jayunit100

**Comment by davidopp** [comment] 2015-04-11 07:47
Yeah I think this is basically a feature request, not a bug report.

**Comment by xiang90** [comment] 2015-04-11 14:44
@bgrant0607 

Today's client is dump. It can only detect the `stop-failure`. It should try to connection other members in its list.

If a etcd member is partitioned from the majority, the client will not be aware of that. In this case, the etcd member itself should know it is partitioned and disconnect the client. There are more things we can do at client side too.

**Comment by bgrant0607** [comment] 2015-04-11 17:28
See also #5589

**Comment by timothysc** [comment] 2015-04-13 21:27
/cc @rrati @abhgupta, this is an indeed an issue in the apiserver as it caches the copy so if an etcd server goes down you receive: 

Error: Get http://<HOST>:2379/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp <IP>:2379: connection refused

**Comment by rrati** [comment] 2015-04-14 13:13
@xiang90 So, is this an etcd client issue?  It sounds like the etcd client isn't actually trying other members in the list if a failure is detected.

**Comment by xiang90** [comment] 2015-04-15 03:39
@timothysc @rrati I cannot follow. 

From @ArtfulCoder's comment, there is only one etcd instance in k8s cluster today. How do you expect the client to fail back to other etcd instances? Can you provide more information?

**Comment by timothysc** [comment] 2015-04-15 13:30
@xiang90 It's a very easy test.  Setup a cluster similar what @ghodss has decribed.  

1. Setup a etcd 3-node cluster 
2. Startup the apiserver with proper args for etcd
3. netstat to determine which server the apiserver appears to have chosen
4. kill that etcd server 
5. apiserver is now hosed, and it doesn't chose any of the other clients that have been provided to the etcd client. 
Toast!

**Comment by xiang90** [comment] 2015-04-15 16:25
@timothysc @rrati Replied in the etcd issue.

**Comment by ghodss** [comment] 2015-04-21 05:27
I'd like to clarify further why I think this is a critical issue, and why it is a bug and also doesn't conflict with the current 1.0 roadmap.

@ArtfulCoder

> The single instance of etcd runs on the mater today. If that node goes down, the entire cluster is hosed anyway. If, just etcd goes down, it is restarted.

To be clear, I am not proposing that any default or primary configuration of kubernetes change to support multiple nodes. However, the beauty of the apiserver/etcd design is that I can hook up apiserver to my multi-node etcd cluster and get redundancy for the cluster state even while kubernetes does not support HA apiserver.

It's completely different for the single master to crash and for me to lose the entire cluster state than for the stateless apiserver to crash and for me to have to simply manually spin up a new one and point it at my etcd cluster. Therefore, in our environment, we run a 5-node etcd cluster to ensure that we do not lose cluster state, but we run apiservers in an active/passive pair since they are not HA yet, which is totally fine. @briangrant I am not saying apiserver should be HA by 1.0, but I do believe that kubernetes should support an HA etcd configuration by 1.0, since it should be minimal work given the current design for tremendous robustness benefit.

For now, coreos/etcd#2677 seems to indicate that the etcd client SHOULD recover on a failure, so more investigation needs to occur to see exactly what's going on.

**Comment by timothysc** [comment] 2015-04-22 21:14
@ghodss I'm a solid +1 on this and will dig further into the issue. 

@xiang90 sorry for the lag, priority inversion.  I'll take a look either this evening or tomorrow a.m.

**Comment by timothysc** [comment] 2015-04-24 20:23
I've sandbox repro'd the problem here: https://github.com/timothysc/etcdk8s-stress

**Comment by tanmaybinaykiya** [comment] 2015-04-28 05:09
Same issues for me. 
https://github.com/GoogleCloudPlatform/kubernetes/issues/7423

**Comment by timothysc** [comment] 2015-08-24 16:26
preference is to close this issue in favor of: #11962

**Comment by davidopp** [comment] 2015-08-25 10:08
SGTM

**Closed by davidopp** 2015-08-25 10:08 UTC
Labels: area/availability, area/performance, dependency/etcd, priority/P2, team/control-plane, team/CSI
