### ISSUE TITLE
e2e flake: Downward API should provide pod IP as an env var

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20403] opened 2016-02-01 10:13 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10735/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/downward_api.go:81 "POD_IP=(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)" in container output Expected : POD_IP= KUBERNETES_PORT=tcp://10.0.0.1:443 KUBERNETES_SERVICE_PORT=443 HOSTNAME=downward-api-b0eb2988-c8ab-11e5-afda-42010af01555 SHLVL=1 HOME=/root KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443 KUBERNETES_SERVICE_PORT_HTTPS=443 PWD=/ KUBERNETES_SERVICE_HOST=10.0.0.1 to match regular expression : POD_IP=(?:\d+)\.(?:\d+)\.(?:\d+)\.(?:\d+)
```

I'm not sure who's responsible for Downward API. cc @lavalamp @davidopp @bgrant0607

**Comment by bgrant0607** [comment] 2016-02-01 19:29
Previous occurrence #13690

**Comment by pmorie** [comment] 2016-02-02 14:47
@gmarek is this in a normal e2e?  In a soak env?

**Comment by gmarek** [comment] 2016-02-02 14:52
It's normal e2e.

**Comment by pmorie** [comment] 2016-02-02 14:53
@gmarek I mean, the context in which the failure was discovered -- previously this happened only in a soak env.

I'm trying to reproduce now.

**Comment by gmarek** [comment] 2016-02-02 15:01
Yup, I understand. It happened in our main test suite.

**Comment by pmorie** [comment] 2016-02-02 20:20
Ran this about 500 times so far in a loop w/o a failure

**Comment by pmorie** [comment] 2016-02-03 04:37
Wasn't able to repro today, will continue tomorrow.

**Comment by thockin** [comment] 2016-02-03 19:18
Can we decorate logs (in a non-horrible way) to make a failure more visible?  That is a viable answer

**Comment by pmorie** [comment] 2016-02-03 19:23
@thockin I was doing just that and found that the information is present in the logs in a log message related to the hosts file mount.  Analyzing now, it looks like on the node where the flake happened, a little over of half the containers started with the podIP unknown.

```
I0201 06:19:08.157017    3382 kubelet.go:1157] Will create hosts mount for container:"dapi-container", podIP:: false
```

^^ example message

So, it looks like the underlying issue here is happening much more often than I personally thought.  Will try to debug.

**Comment by pmorie** [comment] 2016-02-03 19:43
Nevermind, it looks like most of the containers without pod IP are infracontainers.  I remember now that this is expected for the infra container.

**Comment by pmorie** [comment] 2016-02-03 21:47
Looks like it happened 4 times to actual containers on this node that flaked during e2e.

```
$ grep "hosts mount" ~/pod-flake.log  | grep "podIP::" | grep -v POD
I0201 06:17:53.642291    3382 kubelet.go:1157] Will create hosts mount for container:"kube-proxy", podIP:: false
I0201 06:19:08.157017    3382 kubelet.go:1157] Will create hosts mount for container:"dapi-container", podIP:: false
I0201 06:19:49.106935    3382 kubelet.go:1157] Will create hosts mount for container:"c", podIP:: false
I0201 06:20:49.107846    3382 kubelet.go:1157] Will create hosts mount for container:"hostexec", podIP:: false
```

**Comment by wojtek-t** [comment] 2016-02-04 09:37
This just happened again:

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/10931/?project=kubernetes-jenkins

**Comment by erictune** [comment] 2016-02-04 10:35
It happened again:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26572/testReport/junit/(root)/Kubernetes%20e2e%20suite/Downward_API_should_provide_pod_IP_as_an_env_var/

**Comment by spxtr** [comment] 2016-02-05 22:14
This is flaking 1 or 2 times per day on kubernetes-e2e-gce.

**Comment by lavalamp** [comment] 2016-02-05 22:17
new occurrence: https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/11020/

**Comment by thockin** [comment] 2016-02-08 19:06
bumping to p0

**Comment by thockin** [comment] 2016-02-22 17:41
@pmorie  status on this?

**Comment by ncdc** [comment] 2016-02-24 19:38
@thockin fix PR has lgtm; running through jenkins now.

**Comment by ncdc** [comment] 2016-02-24 19:58
@thockin correction, PR has a regression for kube-managed /etc/hosts :-( we'll need to update it

**Comment by ncdc** [comment] 2016-02-24 21:44
I think I've figured out why this is flaking. Here's what I'm seeing locally and also what I've noticed from 1 of the GCE flakes:

1. Kubelet sync loop processes a new pod
1. Infra container is created
1. Actual container is created (and it has the pod IP available correctly)
1. Actual container fails to start for some reason
1. Next sync loop iteration results in a new container
1. New container is passed a pod IP of ""

This looks something like this in the logs (with lots of snipping):

```
kubelet.go:1203] container: e2e-tests-downward-api-57jz3/downward-api-53637d5a-db3a-11e5-8cef-001c42de2c3c/dapi-container podIP: "172.17.0.3" creating hosts mount: true
[snip]
manager.go:1881] Error running pod "downward-api-53637d5a-db3a-11e5-8cef-001c42de2c3c_e2e-tests-downward-api-57jz3(5363a626-db3a-11e5-82e5-001c42de2c3c)" container "dapi-container": runContainer: API error (500): Cannot start container 90cffa61d617ab4f98a3dc72f7549c5a5cb85487957a167e180f1747571a8b43: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-90cffa61d617ab4f98a3dc72f7549c5a5cb85487957a167e180f1747571a8b43.scope/cpu.shares: no such file or directory
[snip]
kubelet.go:1203] container: e2e-tests-downward-api-57jz3/downward-api-53637d5a-db3a-11e5-8cef-001c42de2c3c/dapi-container podIP: "" creating hosts mount: false
```

**Comment by wojtek-t** [comment] 2016-02-29 12:06
@pmorie @ncdc - what's the status of this?

**Comment by pmorie** [comment] 2016-02-29 15:54
@wojtek-t I'm working on an e2e that captures the existing failure, hope to have a PR in the next day or so.

**Comment by ncdc** [comment] 2016-03-07 16:02
I was testing Paul's fix for this on Friday, but unfortunately the lack of https://github.com/kubernetes/kubernetes/pull/22607 in the tree resulted in a different error condition. Instead of failing because POD_IP was blank, it failed because the pod was marked as Failed and the container never ran.

**Comment by yujuhong** [comment] 2016-03-08 19:53
@ncdc I think the problem was originated by relying on passing the pod IP to downstream functions through modifying the `api.Pod` object https://github.com/kubernetes/kubernetes/blob/b1a6ee26efeda0c28825df12e2e4da0a550e08fd/pkg/kubelet/dockertools/manager.go#L1887

The `api.Pod` object should be treated as read-only in most kubelet functions, and you cannot assume the object wouldn't be updated if you write to it.

@pmorie's PR (#22666) builds on top of this hack, so the `getPodIP()` function won't always return the correct IP. Having a one-line hack is one thing, but wrapping it to be a seemingly proper function makes me uncomfortable. Since DockerManager.SyncPod has the most up-to-date information about the pod IP, I think we should just pass that down the call stack. (Alternatively, we can always query the container runtime for the correct IP address, but IMO, that's too expensive)

The call stack that needs to be modified:
```
  -> containerRuntime.SyncPod
    -> dm.runContainerInPod
      -> kubelet.GenerateRunContainerOptions
        -> kubelet.makeMounts
          -> kubelet.makeHostsMount
        -> kubelet.makeEnvironmentVariables
          -> kubelet.podFieldSelectorRuntimeValue
```
/cc @kubernetes/sig-node, FYI.

**Comment by ncdc** [comment] 2016-03-08 19:57
@yujuhong cool, thanks for the detailed explanation. Where in SyncPod does the pod IP exist other than the line you linked above, which only gets called when the infra container is created?

**Comment by yujuhong** [comment] 2016-03-08 20:02
If the infra container was **not** created in the same sync iteration, you should be able to get the pod IP from [`podStatus *kubecontainer.PodStatus`](https://github.com/kubernetes/kubernetes/blob/8b186991e2a85731943e099efcd3c676a6f1c774/pkg/kubelet/dockertools/manager.go#L1773), which was passed to the SyncPod()

**Comment by ncdc** [comment] 2016-03-08 20:03
Ok, so if we put if/else logic in for that check, then we can pass the pod IP around as needed, right?

**Comment by pmorie** [comment] 2016-05-05 15:44
Has anyone hit this recently?  Afaik, it can be closed.  I haven't seen it linked to anything recently.

**Closed** 2016-05-16 10:09 UTC
Labels: kind/flake, priority/P0, team/cluster
