### ISSUE TITLE
Some tests are timing out trying to connect to etcd, such as TestValidOpenAPISpec

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#39670] opened 2017-01-10 13:28 UTC
From e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39668/pull-kubernetes-unit/12379/:

```
=== RUN   TestValidOpenAPISpec
2017-01-10 05:14:11.602055 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.602360 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken EOF.
2017-01-10 05:14:11.602636 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.602785 I | integration: launching node7451630731281799814 (unix://localhost:node7451630731281799814.sock.bridge)
2017-01-10 05:14:11.602927 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.603200 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken EOF.
2017-01-10 05:14:11.603401 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken EOF.
2017-01-10 05:14:11.604404 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.604555 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.604888 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:11.609864 I | etcdserver: name = node7451630731281799814
2017-01-10 05:14:11.610007 I | etcdserver: data dir = /tmp/etcd210239747
2017-01-10 05:14:11.610088 I | etcdserver: member dir = /tmp/etcd210239747/member
2017-01-10 05:14:11.610159 I | etcdserver: heartbeat = 10ms
2017-01-10 05:14:11.610235 I | etcdserver: election = 100ms
2017-01-10 05:14:11.610306 I | etcdserver: snapshot count = 0
2017-01-10 05:14:11.610389 I | etcdserver: advertise client URLs = unix://127.0.0.1:21006.16606.sock
2017-01-10 05:14:11.610544 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21005.16606.sock
2017-01-10 05:14:11.610637 I | etcdserver: initial cluster = node7451630731281799814=unix://127.0.0.1:21005.16606.sock
2017-01-10 05:14:11.618264 I | etcdserver: starting member 946f8502809bacc3 in cluster 165d59333ecf0e8b
2017-01-10 05:14:11.618607 I | raft: 946f8502809bacc3 became follower at term 0
2017-01-10 05:14:11.618720 I | raft: newRaft 946f8502809bacc3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-01-10 05:14:11.618805 I | raft: 946f8502809bacc3 became follower at term 1
2017-01-10 05:14:11.636608 I | etcdserver: set snapshot count to default 10000
2017-01-10 05:14:11.636783 I | etcdserver: starting server... [version: 3.0.14, cluster version: to_be_decided]
2017-01-10 05:14:11.640111 I | membership: added member 946f8502809bacc3 [unix://127.0.0.1:21005.16606.sock] to cluster 165d59333ecf0e8b
2017-01-10 05:14:11.643142 I | integration: launched node7451630731281799814 (unix://localhost:node7451630731281799814.sock.bridge)
2017-01-10 05:14:11.699909 I | raft: 946f8502809bacc3 is starting a new election at term 1
2017-01-10 05:14:11.700102 I | raft: 946f8502809bacc3 became candidate at term 2
2017-01-10 05:14:11.700176 I | raft: 946f8502809bacc3 received vote from 946f8502809bacc3 at term 2
2017-01-10 05:14:11.700306 I | raft: 946f8502809bacc3 became leader at term 2
2017-01-10 05:14:11.700399 I | raft: raft.node: 946f8502809bacc3 elected leader 946f8502809bacc3 at term 2
2017-01-10 05:14:11.702012 I | etcdserver: setting up the initial cluster version to 3.0
2017-01-10 05:14:11.706684 I | etcdserver: published {Name:node7451630731281799814 ClientURLs:[unix://127.0.0.1:21006.16606.sock]} to cluster 165d59333ecf0e8b
2017-01-10 05:14:11.706888 N | membership: set the initial cluster version to 3.0
2017-01-10 05:14:12.500212 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:12.505006 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:12.505443 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:12.506267 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
2017-01-10 05:14:12.506481 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
...
...
2017-01-10 05:19:08.994220 I | v3rpc/grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node6250212877114317478.sock.bridge: connect: no such file or directory"; Reconnecting to {"localhost:node6250212877114317478.sock.bridge" <nil>}
panic: test timed out after 5m0s
```

cc @timothysc @hongchaodeng @wojtek-t @smarterclayton @sttts @xiang90

**Comment by timothysc** [comment] 2017-01-10 14:58
This error looks different then the connection gc problems we fixed a while back.  It looks more like a ulimit problem in this case.  Every time I chase these type of issues they are almost always related to "How" the testing infrastructure is running. 

/cc @spxtr @ixdy

**Comment by hongchaodeng** [comment] 2017-01-10 18:01
I don't know much about Swagger thing.
My question is where does the problem happen? In Swagger? In etcd?

**Comment by timothysc** [comment] 2017-01-10 18:03
example from this a.m. -   https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/1969

**Comment by ncdc** [comment] 2017-01-10 18:07
@timothysc that was from before #39649 was merged, I think

**Comment by mbohlool** [comment] 2017-01-10 18:18
I don't see any failure after ~8am where #39649 is merged.

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-test-go/

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit
(two failures after 8am are not related)

**Comment by hongchaodeng** [comment] 2017-01-10 18:23
Folks.
I understand it's very important to make tests passed and not blocking any PR.
But we should focus on why test failed, figuring out the root cause and fixing it, instead of talking about how disabling it makes failure gone.

**Comment by spxtr** [comment] 2017-01-10 18:36
Trying to repro locally with `bazel test //pkg/master:go_default_test -t- --runs_per_test=32`, haven't hit it yet.

**Comment by xiang90** [comment] 2017-01-10 18:39
@ncdc @spxtr @hongchaodeng 

It seems that there is a race between cluster startup, and connection establishment. It would be great if someone can reproduce it locally.

**Comment by kargakis** [comment] 2017-01-12 16:29
Dupe of https://github.com/kubernetes/kubernetes/issues/39604?

**Comment by wojtek-t** [comment] 2017-03-13 10:27
Yup - this was dup of #39604. Since that one was closed, I'm also closing this one.

**Closed by wojtek-t** 2017-03-13 10:27 UTC
Labels: kind/flake
