### ISSUE TITLE
Kubernetes logs split in kibana

### ISSUE THREAD

**Issue by snirbenyosef** [kubernetes/kubernetes#95096] opened 2020-09-27 09:50 UTC
**What happened**:
I have Kubernetes system in Azure and used the following instrustions to install fluent, elasticsearch and kibana: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch I am able to see my pods logs in kibana but when i send logs more then 16k chars its just split.

if i send 35k chars . its split into 3 logs.

how can i increase the limit of 1 log? I want to able to see the 36k chars in one log.
[https://i.stack.imgur.com/ewocJ.png](https://i.stack.imgur.com/ewocJ.png
)

**What you expected to happen**:
to see the log as one. not spilt to 3.

**How to reproduce it (as minimally and precisely as possible)**:
just send 36k chars.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kuberenetes 1.17.11
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ehashman** [comment] 2020-10-07 16:19
This sounds like an issue with either fluentd or the container runtime limiting log line size... perhaps https://github.com/moby/moby/issues/34620

/assign @dashpole

**Comment by dashpole** [comment] 2020-10-07 16:33
According to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md, the log line splits are determined by the container runtime.

What runtime are you using?

**Comment by snirbenyosef** [comment] 2020-10-07 16:55
how can i check that ?

**Comment by dashpole** [comment] 2020-10-07 16:57
`kubectl describe no  | grep Runtime`

**Comment by snirbenyosef** [comment] 2020-10-07 16:59
@dashpole what are you trying to describe ? the nodes ? the fluntd pods ?

**Comment by dashpole** [comment] 2020-10-07 17:00
`no` is short for `nodes`

**Comment by snirbenyosef** [comment] 2020-10-08 06:52
@dashpole 
 Container Runtime Version:  docker://19.3.12
 Container Runtime Version:  docker://19.3.12
 Container Runtime Version:  docker://19.3.12
 Container Runtime Version:  docker://19.3.12

**Comment by dashpole** [comment] 2020-10-08 16:27
Yeah, this is a duplicate of https://github.com/moby/moby/issues/34855.  Docker is splitting your logs at 16k, and it doesn't appear to be configurable.

**Comment by ehashman** [comment] 2020-11-02 16:29
/close

Please refer to the upstream issue to configure this. Thanks!

**Closed** 2020-11-02 16:29 UTC
Labels: kind/feature, kind/support, sig/instrumentation
