### ISSUE TITLE
Failure cluster [d4630f19...] Services should fail health check node port if there are only terminating endpoints

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#117838] opened 2023-05-06 09:02 UTC
##### Error text:
```
[FAILED] error running /workspace/github.com/containerd/containerd/kubernetes/platforms/linux/amd64/kubectl --server=https://35.230.64.81 --kubeconfig=/workspace/.kube/config --namespace=services-529 exec pause-pod-0 -- /bin/sh -x -c curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 http://10.138.0.3:30267/healthz:
Command stdout:
000
stderr:
+ curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 http://10.138.0.3:30267/healthz
command terminated with exit code 7

error:
exit status 7
In [It] at: test/e2e/network/service.go:2769 @ 05/04/23 23:24:08.784

```
#### Recent failures:
[2023/5/6 05:32:00 ci-kubernetes-e2e-gci-gce-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-containerd/1654599831877849088)
[2023/5/6 04:18:00 ci-cos-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-e2e-ubuntu-gce/1654581209281335296)
[2023/5/6 03:53:00 ci-cos-cgroupv1-containerd-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-e2e-gce/1654574917489790976)
[2023/5/6 01:56:22 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1654545568552194048)
[2023/5/6 01:50:22 ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1654544058632114176)

/kind failing-test

/sig network

**Comment by daman1807** [comment] 2023-05-06 09:09
@pacoxu looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/117824, a PR is already open for this https://github.com/kubernetes/kubernetes/pull/117830

**Closed** 2023-05-06 09:10 UTC
Labels: sig/network, kind/flake, needs-triage

**Comment by aojea** [comment] 2023-05-06 10:41
I need a lgtm for the fix https://github.com/kubernetes/kubernetes/pull/117830
