### ISSUE TITLE
Problems fetching PR commit from github

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#32356] opened 2016-09-09 06:45 UTC
stderr: error: object file .git/objects/5a/9848207a445a0bd97727b62e4a2dbf4ac35e61 is empty
fatal: loose object 5a9848207a445a0bd97727b62e4a2dbf4ac35e61 (stored in .git/objects/5a/9848207a445a0bd97727b62e4a2dbf4ac35e61) is corrupt
fatal: The remote end hung up unexpectedly

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32112/kubernetes-pull-build-test-e2e-gke/11052/

Found in https://github.com/kubernetes/kubernetes/pull/32112

**Comment by rmmh** [comment] 2016-09-09 09:30
Dupe of #26822. This hit a few different gke builds at the same time.

**Closed by rmmh** 2016-09-09 09:30 UTC
Labels: kind/flake, team/test-infra
