### ISSUE TITLE
Automatic pod rescheduling

### ISSUE THREAD

**Issue by rochdev** [kubernetes/kubernetes#47965] opened 2017-06-23 15:51 UTC
/kind feature

Right now if a node is terminated, its pods are rescheduled on any other available node. However, once a new node is created to replace the failed node, pods are not rescheduled on this node, so in case of a failure of the other node will result in a temporary outage.

For example:

Node N1 has pod P1
Node N2 has pod P2
Node N1 fails
Node N2 has pod P1 and P2
Node N3 is created to replace Node N1
Node N2 has pod P1 and P2
Node N3 has no pods

If N2 fails, there will be an outage until pods are rescheduled on N3. If one of the pods would have been rescheduled automatically when N3 became healthy, each node would have had a pod and a failure of any node would not result in an outage.

**Comment by davidopp** [comment] 2017-06-26 15:50
I agree with @krmayankk , this is a dupe of #12140. I'm going to close it, please reopen if you think the use case is not covered by that issue.

**Closed by davidopp** 2017-06-26 15:50 UTC
Labels: kind/feature, sig/api-machinery
