### ISSUE TITLE
kubelet fails starting CRI-O containers (Ubuntu 18.04 + systemd cgroups driver)

### ISSUE THREAD

**Issue by olberger** [kubernetes/kubernetes#77615] opened 2019-05-08 20:50 UTC
**What happened**:

kubelet doesn't seem to be able to manage containers started with CRI-O any more

I'm testing kubelet + CRI-O on an Ubuntu 18.04 server installation, inside a qemu/kvm VM managed by Vagrant (see https://github.com/olberger/vagrant-k8s-kubevirt-katacontainers/tree/539c9d06ffa611aa2d08da6cfa617d42fe218a40), in order to be able to test k8s + KubeVirt + KataContainers, which are all compatible with CRI-O  

kubelet will obsess on starting new containers, which looks like and endless process, and the cluster never gets ready.

For instance here are some syslogs :
```
May  8 13:32:44 ubuntu1804 systemd[1]: Started crio-conmon-93673e8dc9ee02e7855aa616de720d15d8c009013dc9577ad303ea38c00c67a6.scope.
May  8 13:32:44 ubuntu1804 systemd[1]: Created slice libcontainer_16535_systemd_test_default.slice.
May  8 13:32:44 ubuntu1804 systemd[1]: Removed slice libcontainer_16535_systemd_test_default.slice.
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.377844    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/libcontainer_16535_systemd_test_default.slice: no such file or directory
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.377890    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/libcontainer_16535_systemd_test_default.slice: no such file or directory
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.377913    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/libcontainer_16535_systemd_test_default.slice: no such file or directory
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.377993    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_16535_systemd_test_default.slice: no such file or directory
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.380535    9399 container.go:409] Failed to create summary reader for "/libcontainer_16535_systemd_test_default.slice": none of the resources are being tracked.
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.381180    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
May  8 13:32:44 ubuntu1804 kubelet[9399]: W0508 13:32:44.381358    9399 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_16535_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_16535_systemd_test_default.slice: no such file or directory
May  8 13:32:44 ubuntu1804 systemd[1]: Created slice libcontainer_16535_systemd_test_default.slice.
May  8 13:32:44 ubuntu1804 systemd[1]: Removed slice libcontainer_16535_systemd_test_default.slice.
May  8 13:32:44 ubuntu1804 systemd[1]: Started libcontainer container 93673e8dc9ee02e7855aa616de720d15d8c009013dc9577ad303ea38c00c67a6.
May  8 13:32:44 ubuntu1804 kubelet[9399]: E0508 13:32:44.391247    9399 kubelet.go:2244] node "kubernetes-vagrant-01" not found
May  8 13:32:44 ubuntu1804 kubelet[9399]: E0508 13:32:44.433374    9399 fsHandler.go:118] failed to collect filesystem stats - rootDiskErr: could not stat "/var/lib/containers/storage/overlay/93f8d93979e19d2d23dcccf4cf66d66ad7eced76f53871ef010de26816c821ac/diff" to get inode usage: stat /var/lib/containers/storage/overlay/93f8d93979e19d2d23dcccf4cf66d66ad7eced76f53871ef010de26816c821ac/diff: no such file or directory, extraDiskErr: <nil>
May  8 13:32:44 ubuntu1804 crio[8875]: open /dev/stderr: no such device or address
May  8 13:32:44 ubuntu1804 crio[8875]: NAME:
May  8 13:32:44 ubuntu1804 crio[8875]:    runc - Open Container Initiative runtime
May  8 13:32:44 ubuntu1804 crio[8875]: runc is a command line client for running applications packaged according to
May  8 13:32:44 ubuntu1804 crio[8875]: the Open Container Initiative (OCI) format and is a compliant implementation of the
May  8 13:32:44 ubuntu1804 crio[8875]: Open Container Initiative specification.
```

**What you expected to happen**:

It used to work (see asciinema recording at https://www-public.imtbs-tsp.eu/~berger_o/weblog/2019/04/26/testing-kubevirt-for-running-vms-inside-kubernetes-in-a-vagrant-qemu-vm/) a few days ago, but I fear some recent changes broke it.

**How to reproduce it (as minimally and precisely as possible)**:

Testing with vagrant up --provider=libvirt on Linux with a clone of that commit:
https://github.com/olberger/vagrant-k8s-kubevirt-katacontainers/tree/539c9d06ffa611aa2d08da6cfa617d42fe218a40

vagrant ssh into the VM and ps -edf f or tail -f /var/log/syslog would do...

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/kube-apiserver:v1.14.1
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.14.1
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/kube-scheduler:v1.14.1
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/kube-proxy:v1.14.1
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/pause:3.1
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/etcd:3.3.10
    kubernetes-vagrant-01: [config/images] Pulled k8s.gcr.io/coredns:1.3.1
```
- Cloud provider or hardware configuration: qemu/kvm VM + 
```
crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.13.1-dev
RuntimeApiVersion:  v1alpha1
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS 
- Kernel (e.g. `uname -a`): Linux kubernetes-vagrant-01 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm as in https://github.com/olberger/vagrant-k8s-kubevirt-katacontainers/blob/539c9d06ffa611aa2d08da6cfa617d42fe218a40/kubernetes.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Bruceforce** [comment] 2019-05-09 19:52
I can confirm this. If I start cri-o from a systemd service it fails with the above mentioned error message. Starting crio with `/usr/local/bin/crio` without systemd works just fine.

systemd file:
```
[Unit]
Description=OCI-based implementation of Kubernetes Container Runtime Interface
Documentation=https://github.com/cri-o/cri-o

[Service]
ExecStart=/usr/local/bin/crio
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by mattjmcnaughton** [comment] 2019-05-10 14:44
Thanks for your detailed report @olberger :)

Just want to do some quick version confirming - you've been using k8s 1.14.1 both when it did and did not work? Any other version changes?

**Comment by olberger** [comment] 2019-05-10 15:06
Not sure for before, when it used to work, but according to the asciinema recording mentioned above (https://asciinema.org/a/243325), it seems the same.
However, not sure for CRI-O, underlying OS stuff (systemd, kernel, etc.). Sorry.

**Comment by alitvak69** [comment] 2019-05-11 20:45
I was looking for some information for days.  I have exactly the same issue when I use podman + systemd on 18.04.2.  It is the same for both 14.15 and 14.18 kernels.  Podman without systemd runs fine.  Podman with systemd fails at runc with the same error    

podman[345937]: open /dev/stderr: no such device or address
podman[345937]: NAME: runc - Open Container Initiative runtime
podman[345937]: runc is a command line client for running applications packaged according to

...
podman[1156441]: time="2019-05-11T13:04:59-07:00" level=error msg="open /dev/stderr: no such device or address\n"
podman[1156441]: open /dev/stderr: no such device or address

**Comment by giuseppe** [comment] 2019-05-14 09:59
> I was looking for some information for days. I have exactly the same issue when I use podman + systemd on 18.04.2. It is the same for both 14.15 and 14.18 kernels. Podman without systemd runs fine. Podman with systemd fails at runc with the same error
> 
> podman[345937]: open /dev/stderr: no such device or address
> podman[345937]: NAME: runc - Open Container Initiative runtime
> podman[345937]: runc is a command line client for running applications packaged according to

I've tried to reproduce it on 18.04.2 using Podman from `ppa:projectatomic/ppa` but I am not able to reproduce it.  Do you have any reproducer?  How did you install Podman?

**Comment by alitvak69** [comment] 2019-05-14 13:37
I used ceph unit files to run ceph in podman rather than docker.  Systemd
unit successfully starts docker but fails with podman.  I can successfully
run the same podman container run command from the command line.  How were
you trying to replicate this?  Can you post your unit file?

**Comment by joost14** [comment] 2019-05-14 13:43
Hi, 

I'am having the same problem with Kubernetes with CRI-O. After joining a second worker node it fails to start flannel. 
`sudo systemctl status crio` gives the following error: 
```
mei 14 10:29:25 k8sworker02 crio[704]: time="2019-05-14T10:29:25+02:00" level=error msg="open /dev/stderr: no such
mei 14 10:29:25 k8sworker02 crio[704]: open /dev/stderr: no such device or address
```
What I've tried: 
- Installing previous version of Kubernetes (from `1.14.1` to `1.13.4`)
- Installing previous version of crio (from `1.13.1-dev` to `1.12.1-dev`)
- Building runc myself from their github page and selecting this in the crio.conf. 

Running it on Ubunut 18.04.2
Issue: https://github.com/cri-o/cri-o/issues/2368 (the one giuseppe linked)

**Comment by alitvak69** [comment] 2019-05-14 13:54
I wonder if the issue is with systemd and runc.  In both cases, crio and
podman, I see runc help output which tells me that something  is not being
passed to runc that it needs.

**Comment by giuseppe** [comment] 2019-05-14 14:08
> I used ceph unit files to run ceph in podman rather than docker. Systemd unit successfully starts docker but fails with podman. I can successfully run the same podman container run command from the command line. How were you trying to replicate this? Can you post your unit file?

I've only used `--cgroup-manager systemd` so it is different than your test and you confirmed it works from the CLI for you as well.  Could you share your service file so I test it?

**Comment by joost14** [comment] 2019-05-14 14:12
I've tried systemd and cgroupfs but no luck so far.

**Comment by giuseppe** [comment] 2019-05-14 14:43
so it seems that runc fails to re-open `/dev/stderr`.  That seems like a runc issue, as it doesn't really need to reopen it.
To fix the failure, you could use something like:
```
# echo "StandardError=null" >> /etc/systemd/system.conf
# systemctl daemon-reload
```

**Comment by alitvak69** [comment] 2019-05-14 14:59
Just an example.  I use ceph-ansible to install cluster so it may need to
install additional daemons like mon before running mgr but the error, in
this case, should be different,

[Unit]
Description=Ceph Manager


[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=-/usr/bin/podman stop ceph-mgr-storage2n1-la
ExecStartPre=-/usr/bin/podman rm ceph-mgr-storage2n1-la
ExecStart=/usr/bin/podman run --rm --net=host \
  --memory=16G \
  --cpus=4 \
  -v /var/lib/ceph:/var/lib/ceph:z \
  -v /etc/ceph:/etc/ceph:z \
  -v /var/run/ceph:/var/run/ceph:z \
  -v /etc/localtime:/etc/localtime:ro \
  -e CLUSTER=ceph \
  -e CEPH_DAEMON=MGR \
  -e CONTAINER_IMAGE= docker.io/ceph/daemon:latest-nautilus \
  {{ ceph_mgr_docker_extra_env }} \
  --name=ceph-mgr-storage2n1-la \
  docker.io/ceph/daemon:latest-nautilus
ExecStopPost=-/usr/bin/podman stop ceph-mgr-storage2n1-la
Restart=always
RestartSec=10s
TimeoutStartSec=120
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target

**Comment by alitvak69** [comment] 2019-05-14 15:00
BTW,

I  added projectatomic ppa and used apt-get -y podman to install.  My
podman version is 1.3.0

**Comment by alitvak69** [comment] 2019-05-14 15:02
Corrected file.

[Unit]
Description=Ceph Manager


[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=-/usr/bin/podman stop ceph-mgr-storage2n1-la
ExecStartPre=-/usr/bin/podman rm ceph-mgr-storage2n1-la
ExecStart=/usr/bin/podman run --rm --net=host \
  --memory=16G \
  --cpus=4 \
  -v /var/lib/ceph:/var/lib/ceph:z \
  -v /etc/ceph:/etc/ceph:z \
  -v /var/run/ceph:/var/run/ceph:z \
  -v /etc/localtime:/etc/localtime:ro \
  -e CLUSTER=ceph \
  -e CEPH_DAEMON=MGR \
  -e CONTAINER_IMAGE= docker.io/ceph/daemon:latest-nautilus \
  --name=ceph-mgr-storage2n1-la \
  docker.io/ceph/daemon:latest-nautilus
ExecStopPost=-/usr/bin/podman stop ceph-mgr-storage2n1-la
Restart=always
RestartSec=10s
TimeoutStartSec=120
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target

**Comment by alitvak69** [comment] 2019-05-14 15:04
Would it have an effect system wide?  Can I add it to a unit file or unit
override instead?

**Comment by giuseppe** [comment] 2019-05-14 15:09
@alitvak69 yes, I think it is better to add it only to the unit file

**Comment by alitvak69** [comment] 2019-05-14 15:13
Why would runc work outside of systemd?  And if it needs stderr,  giving it
Null in settings will redirect stderr to Null I presume?

**Comment by sfxworks** [comment] 2019-05-14 16:22
```
May 14 16:08:44 master-1 crio[30292]: time="2019-05-14T16:08:44Z" level=error msg="open /dev/stderr: no such device or address\n"
May 14 16:08:44 master-1 crio[30292]: open /dev/stderr: no such device or address
May 14 16:08:45 master-1 crio[30292]: open /dev/stderr: no such device or address
```
Running into same issues on Ubuntu 18.04.2 using cri-o-1.13 via PPA.

**Comment by giuseppe** [comment] 2019-05-14 19:58
PR here: opencontainers/runc#2057

**Comment by alitvak69** [comment] 2019-05-14 20:03
Until it is avaialble with project atomic and such, can I use a null
workaround?

**Comment by giuseppe** [comment] 2019-05-14 20:09
yes, but you will lose anything written to stderr.  You could probably also use a file, like `file:/path/to/the/file`

**Comment by alitvak69** [comment] 2019-05-14 20:28
What about actually mounting dev and using /dev/stderr ?

**Comment by giuseppe** [comment] 2019-05-15 07:23
> What about actually mounting dev and using /dev/stderr ?

`/dev/stderr` is a symlink to `/proc/fd/2`.  It is present, the issue here is that `/proc/fd/2` is a socket.  The fix for runc got merged, could you use an updated runc?

**Comment by joost14** [comment] 2019-05-15 07:39
I tried apt update/upgrade and restarting crio, but I'm still getting the issue. Could it be that crio's runc is not updated yet?

**Comment by olberger** [comment] 2019-05-15 09:32
I'm running this version from PPA repo for ubuntu and it fails:
```
cri-o-runc (1.0.0-rc6-1~dev~ubuntu18.04~ppa41) bionic; urgency=medium

  * autobuilt eb4aeed

 -- Lokesh Mandvekar (Bot) <lsm5+bot@fedoraproject.org>  Wed, 08 May 2019 16:49:59 +0000
```
@giuseppe could you point to version/commit or whatever helps identify the fixed version/snapshot ?

Thanks in advance.

**Comment by giuseppe** [comment] 2019-05-15 09:33
at the moment it is only fixed upstream.  You'd need to build runc manually

**Comment by alitvak69** [comment] 2019-05-15 12:19
Is there a version of the package on ppa we can downgrade to?

**Comment by giuseppe** [comment] 2019-05-15 14:12
@lsm5 could we update the runc version in the PPA repo?

**Closed** 2019-05-15 15:36 UTC
Labels: kind/bug, sig/node

**Comment by alitvak69** [comment] 2019-05-15 17:07
Thank you.  I seem them built but nut pushed to ppa yet.

**Comment by lsm5** [comment] 2019-05-15 18:03
should be available now.. let me know..

**Comment by lsm5** [comment] 2019-05-15 18:05
cri-o-runc (1.0.0-rc6-1~dev~ubuntu18.04~ppa42) bionic; urgency=medium

    * autobuilt b9b6cc6

    -- Lokesh Mandvekar (Bot) <lsm5+bot@fedoraproject.org>  Wed, 15 May 2019 16:54:40 +0000

**Comment by alitvak69** [comment] 2019-05-15 19:23
Thank you, everyone, for a quick turn around.  Quick testing showed that
fix is working, but more testing is needed.

**Comment by olberger** [comment] 2019-05-15 21:49
I confirm my initial tests with https://github.com/olberger/vagrant-k8s-kubevirt-katacontainers seem to confirm the regression is fixed. Many thanks

**Comment by alitvak69** [comment] 2019-05-15 23:35
I also confirm the fix working for podman.
