### ISSUE TITLE
"Services should serve multiport endpoints from pods" is failing repeatedly on kubernetes-e2e-gce-parallel

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#11675] opened 2015-07-21 18:52 UTC
This test has failed on 7 of the last 14 runs

**Comment by ihmccreery** [comment] 2015-09-02 21:34
This is flaking on roughly 25% of PR builds, so I'm marking it as P0.

**Comment by ihmccreery** [comment] 2015-09-02 21:36
@ixdy @quinton-hoole FYI

**Comment by ihmccreery** [comment] 2015-09-02 22:14
Hopefully this has the same root cause as the hypothesized cause of #13478, [not enough nodes](https://github.com/kubernetes/kubernetes/issues/13478#issuecomment-137260462).

**Comment by quinton-hoole** [comment] 2015-09-03 22:00
Fixed by #13534

**Closed by quinton-hoole** 2015-09-03 22:00 UTC
Labels: priority/P0, team/testing
