### ISSUE TITLE
Webhook REST clients cache invalid and possibly not expiring

### ISSUE THREAD

**Issue by raonitimo** [kubernetes/kubernetes#93409] opened 2020-07-24 06:41 UTC
**What happened**:
Deployed a webhook as a service to a Kubernetes cluster with 2 masters, listening initially on port 8000. 
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
kind: Service
apiVersion: v1
metadata:
  name: webhook
  namespace: webhook
spec:
  selector:
    app: webhook
  ports:
  - name: https
    protocol: TCP
    port: 8000
    targetPort: 443
```

Created a Validating Webhook pointing to port 8000:
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
- clientConfig:
    caBundle: ...
    service:
      name: webhook
      namespace: webhook
      path: /validate
      port: 8000
  failurePolicy: Fail
...
```

Changed the service to use port 443. As expected, pod creation started to fail with the message (not always though):
```bash
$ kubectl run nginx --image nginx
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.webhook.svc": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port 'ὀ' found for service "webhook"
```

The 'ὀ' character was a bug on printing the port number - 8000 in this case - that was [fixed](https://github.com/kubernetes/kubernetes/pull/85558). This is not the issue here.

After fixing the webhook configuration, I started seeing the message:
```bash
$ kubectl run nginx --image nginx
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.webhook.svc": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port 'ƻ' found for service "webhook"
```

Consistently when hitting one of the masters, while the Validating Webhook worked as expected when hitting the other master. Again the weird character 'ƻ' represents 443, the .webhooks[].clientConfig.service.port in ValidatingWebhookConfiguration.

The same issue persists after deleting the service, webhook, and recreating with the same names.

**What you expected to happen**:
I expected the Validating Webhook to work on both masters.

**How to reproduce it (as minimally and precisely as possible)**:
Tried reproducing this issue using a different service name, as well as deploying it in another cluster. But the same error didn't happen again, so I believe there was some sort of special condition that caused this problem.

**Anything else we need to know?**:
Digging a bit into this, I suspect it has something to do with the [caching](https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L117) . I couldn't find a reference to where this cache is cleaned up.

Shouldn't we move to a LRUExpireCache to avoid this?

I'm happy to make a pull request if you think this is the case.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15 (but this code hasn't changed since)
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-07-24 14:33
the cache key is the full configuration (including the port): https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L122, and the [cache is already a LRU cache](https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L61)

what specific version of 1.15 do you have?

does the cached version and live version of the service or endpoints in the problematic API server differ? you can see the difference with:

```
# live
kubectl get --raw /api/v1/namespaces/webhook/services/webhook
kubectl get --raw /api/v1/namespaces/webhook/endpoints/webhook

# cached
kubectl get --raw /api/v1/namespaces/webhook/services/webhook?resourceVersion=0
kubectl get --raw /api/v1/namespaces/webhook/endpoints/webhook?resourceVersion=0
```

**Comment by mb-m** [comment] 2020-07-27 22:05
So I found the problem originally, (and didn't realise what was going on) by managing to lock one of a pair of kubernetes masters to see one version of the service, and its peer to see a different one. As an AWS customer using the EKS service, I initially assumed that this was an EKS hardware issue, but further work with AWS support got us to the replicable example above.

Doing the testing @liggitt suggests reveals nothing untoward, the ?resourceVersion=0 version of the services and endpoints show exactly what you would expect, 404s when the service is gone, the current version when it's back, but reliably, we can see that the re-created service is still locked in on the same ports on the EKS masters for doing webhook operations, but not, as far as I can tell, for anything else (something that would fail tests, I imagine), as it was several days ago.

As far as I can tell, also, whichever version is cached is also visible on both a ValidatingWebhookConfig or a MutatingWebhookConfig (my original webhook system uses both, and both were set to Fail on error, but setting the mutating webhook to ignore on error shows the same behaviour on the validating webhook).

I'll admit that my knowledge of the kubernetes internals (especially around the caching of ListServices() or suchlike) isn't very good, and I've had a ton of other work that meant that this was a bit de-prioritised for me once I understood what to avoid, which has meant I can't point you to where this bug is likely coming from, but somewhere there appears to be some kind of cache (explicit and intentional or not) which isn't being cleared in the same way as the normal correct one.

Sorry that this is so handwavy, I normally like to be a bit more precise in my bug reporting.

**Comment by mb-m** [comment] 2020-07-27 22:11
I'm also not 100% sure, but I think to fully reproduce, you may have to actually do at least one request on each API server causing the webhook to look up the service to trigger the cache before changing the port number. I didn't get to try that particular experiment when I was trying to work out what to do with AWS support to replicate this problem.

**Comment by liggitt** [comment] 2020-07-27 22:13
what specific version of 1.15 are you running in the apiserver?

**Comment by mb-m** [comment] 2020-07-27 22:15
The EKS one (I'm afraid as a customer I don't know more than that, sorry - @raonitimo should be able to help here)

Also, I think the point where it's failing is within the call https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L172 to resolve the service.

**Comment by mb-m** [comment] 2020-07-27 22:28
I was a bit unsure about which implementation of ResolveEndpoints is being used, but if it's: https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/proxy/proxy.go#L43 (through one of the other implementations) then essentially, you end up https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/client-go/listers/core/v1/service.go#L55-L94 - which appears to be cacheing the list of the namespace with nothing obvious to clear it if you keep passing the same lister (is that what's happening in the webhook?)

**Comment by raonitimo** [comment] 2020-07-28 05:06
Hello @liggitt , thanks for investigating this. The specific cluster version is 1.15.11.

Please let me know if there's anything I can do to help.

**Comment by liggitt** [comment] 2020-07-28 14:33
> you end up https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/client-go/listers/core/v1/service.go#L55-L94 - which appears to be cacheing the list of the namespace with nothing obvious to clear it

The cache doesn't get cleared, it is updated by an informer watching add/update/delete events from the cluster (like most controllers).

**Comment by liggitt** [comment] 2020-07-28 14:41
> The same issue persists after deleting the service, webhook, and recreating with the same names.

That is very strange. When the servers are in this state, can you fetch the full content of the webhooks, service, endpoints, and backing pods (eliding any irrelevant confidential info) with `kubectl get -o yaml`?

> The specific cluster version is 1.15.11.

Ok, thanks. #83911 might have been relevant, but was fixed in 1.15.6. #86015 _might_ also be relevant, and was fixed in 1.18.0, but it's hard to imagine network disruption on a loopback connection inside the kube-apiserver process.

**Comment by mb-m** [comment] 2020-07-28 16:15
https://gist.github.com/mb-m/ab7678b404a755a0ac94ce02a0bae113 - some names and paths etc changed (in a consistent way) to protect internal names.

The initial service was created with `port: 8000` but got changed because of the error message (which I later found out was hardcoded to :443 in this version). One API server consistently looks for the service port (for this specific service name) on :8000 and the other on :443. I have to admit it didn't occur to me to expose both ports on the service (but this has been an evolving discovery, and given the cacheing I'm seeing, I suspect it won't help, but I can try that if need be). It also doesn't matter what name (or type as I mentioned above) the WebhookConfiguration object uses.

I was able to lock other service names with the webhook into the same behaviour (on the same API servers at least). Honestly, I'm a bit confused by this.

**Comment by liggitt** [comment] 2020-07-28 18:38
cc @caesarxuchao @roycaihw

**Comment by mb-m** [comment] 2020-08-05 09:32
@liggitt @caesarxuchao @roycaihw please let me know if there's anything more you need from me

**Comment by liggitt** [comment] 2020-08-05 14:22
the primary thing at this point would be to see if the issue could be reproduced on a supported version (1.16+) or on master, ideally in an isolated test case

**Closed** 2020-10-15 14:10 UTC
Labels: area/admission-control, kind/support, sig/api-machinery, triage/needs-information
