### ISSUE TITLE
Defaults and Conversions have deep entanglement

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6210] opened 2015-03-31 05:58 UTC
Given 

```
type Foo struct {
   Spec FooSpec
}
```

If you have a custom conversion for Foo and that func does not explicitly call Convert() on FooSpec,  then no conversion function will be called on Spec - not too surprising.  HOWEVER - it will also bypass the defaulting function of FooSpec.  This is a bit more surprising.

Worse - the tests for defaults run with no custom conversion functions loaded, it seems, so even though things pass the test, they don't actually work.

This needs some thought or AT LEAST some good docs.

**Comment by yujuhong** [comment] 2015-03-31 18:26
Yes, defaulting is tangled with conversions, and there are some caveats unfortunately. One example is that if you convert an object multiple times between different versions, you may end up having an object populated with default values from multiple versions. I am not sure that this is the intended behavior. We could use more clarity on this, and the example you mentioned.

As for the tests, as far as I know, *most* custom conversion functions convert versioned objects (e.g. pkg/api/v1beta1) to api objects (pkg/api), or vice versa, which is likely the case you were referring to. The defaults_tests.go in each version tests encoding a versioned object and decoding it into an object of the same version again. Nowhere in that path invokes `api <-> versioned` conversions. What I can do to improve the tests is to `Decode` the object into an api object, and then convert it back to the versioned object before verifying the default values. What do you think, @thockin?

**Comment by thockin** [comment] 2015-03-31 18:32
I'm not sure this is worth a lot of attention right now.  I wanted to file
it so we can think about it for a larger revamp of
conversion/validation/defaulting.

**Comment by yujuhong** [comment] 2015-03-31 19:00
Agreed that the entanglement should be addressed in a larger revamp, but the tests should still catch most of the unexpected errors until we have time for the revamp. I submitted a PR #6235.

**Comment by yujuhong** [comment] 2015-03-31 19:34
Default tests should be able to catch most problems now that the PR has been merged.

**Comment by dchen1107** [comment] 2015-03-31 20:11
+ me on latest update on this.

**Comment by lavalamp** [comment] 2015-03-31 21:15
Unfortunately, this is probably a post-1.0 item.

**Comment by pmorie** [comment] 2015-04-28 17:48
Related: https://github.com/GoogleCloudPlatform/kubernetes/issues/7337, might be able to be closed as a dupe.

**Comment by lavalamp** [comment] 2016-02-10 21:24
Kicking this can down the road.

**Comment by smarterclayton** [comment] 2017-06-01 17:26
Fixed!

**Closed by smarterclayton** 2017-06-01 17:26 UTC
Labels: area/apiserver, kind/technical-debt, priority/awaiting-more-evidence, sig/api-machinery
