### ISSUE TITLE
federation-controller/TestSecretController nil pointer

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33865] opened 2016-09-30 21:27 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33587/kubernetes-pull-test-unit-integration/47348/
```
panic: interface conversion: interface is nil, not *v1.Secret
/usr/local/go/src/runtime/panic.go:481 +0x3ff
/usr/local/go/src/testing/testing.go:467 +0x22a
/usr/local/go/src/runtime/panic.go:443 +0x521
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/secret/secret_controller_test.go:139 +0x70
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/secret/secret_controller_test.go:104 +0x194f
/usr/local/go/src/testing/testing.go:473 +0xdd
/usr/local/go/src/testing/testing.go:582 +0xae3
```
@kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment] 2016-10-01 19:47
@bprashanth #33880 is a duplicate of this issue, but I am closing this in favor of the bot filed one because the bot is probably going to reopen otherwise. But thanks though.

**Closed by madhusudancs** 2016-10-01 19:47 UTC
Labels: area/cluster-federation, kind/flake, priority/P2
