### ISSUE TITLE
Glusterfs volume type does not attempt to mount all availabe endpoints

### ISSUE THREAD

**Issue by gizmonicus** [kubernetes/kubernetes#13125] opened 2015-08-25 03:20 UTC
I have a demo cluster with 2 minions and one master. I have set up gluster-server on both minions with a replication factor of 2, meaning that any single node could fail and any pods that mount the gluster volume should be re-scheduled to the healthy node. However, this does not always work. Here is the error message generated by kubelet on my healthy minion:

Aug 24 22:49:43 kube1 kubelet[1279]: Mounting arguments: 192.168.100.10:gv0 /var/lib/kubelet/pods/425dd82d-4acf-11e5-840b-080027e80634/volumes/kubernetes.io~glusterfs/glusterfsvol glusterfs []
Aug 24 22:49:43 kube1 kubelet[1279]: Output: Mount failed. Please check the log file for more details.
Aug 24 22:49:43 kube1 kubelet[1279]: E0824 22:49:43.473575    1279 glusterfs.go:213] Glusterfs: mount failed: exit status 1
Aug 24 22:49:43 kube1 kubelet[1279]: E0824 22:49:43.473809    1279 kubelet.go:1190] Unable to mount volumes for pod "nginx-gluster-v1-fdwbu_default": exit status 1; skipping pod

What was odd is that it never tries to mount a volume from the other endpoint, even though it is healthy. It ALWAYS fails to mount and the images stay in a not ready state. If, on the other hand, I shut off the opposite node, the volumes mount successfully. 

I looked at the source to see what is happening and I believe the problem stems from the usage of rand.Int() in the setUpAtInternal function in pkg/volume/glusterfs/glusterfs.go. I wrote a test program and was surprised to find that rand.Int() always returns the same result if a seed is not supplied.

```go
package main

import (
    "math/rand"
    "fmt"
    "time"
)

func main () {
    // if you comment the rand.Seed line you
    // always get the same value for random
    rand.Seed(time.Now().Unix())
    random := rand.Int()
    fmt.Println(random)
}
```

So instead of choosing a random host, it always starts with the same one. What I *don't* understand is why it doesn't just move on to the next host in line after the mount command fails; the for loop should iterate over all available hosts until all are exhausted or the mount succeeds.

**Comment by saad-ali** [comment] 2015-09-09 03:48
@eparis or @jsafrane Could you take a look at this?

**Comment by gizmonicus** [comment] 2015-09-09 19:32
In case anyone finds this issue and wants a workaround; I used keepalived to create a floating IP address for my gluster endpoints and that solved the HA problem. It obviously wouldn't mitigate a mount storm, but I don't think 2 containers will be a problem.

**Comment by jsafrane** [comment] 2015-09-22 13:39
I cannot reproduce the bug. I tried with a two-machine gluster cluster and Kubernetes (current master) tries both endpoints if one of them fails to mount.

Still, the order in which they are tried is not random at all, pr #13807 seem to have broken the algorithm. If the endpoints are constant (and they are), iterating map[] gives its items always in the same (pseudo-random) sequence at https://github.com/bodgit/kubernetes/commit/8bbc86d83cb8009023fc58270040f14eefb95023#diff-e97253dd603331ffca81131a4b67264fR240

**Comment by jsafrane** [comment] 2015-09-22 13:40
@bodgit, @hchen, do I miss something ^ ?

**Comment by gizmonicus** [comment] 2015-09-22 14:38
It appears the current master does not have the issue with trying both
endpoints. I started to work on patching it myself but after building the
latest master, I also could not reproduce the error, even though it still
did not start with a random endpoint. The version that ships with CentOS 7
was, and as far as I am aware, still is affected. I'll take that up with
the RHEL/CentOS maintainers.

--

    Will Tomlinson

**Comment by bodgit** [comment] 2015-09-22 16:24
@jsafrane I based the change on http://blog.golang.org/go-maps-in-action#TOC_7 which states:

> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation.

@gizmonicus The trying of other endpoints is something else I fixed at the same time as I noticed the same behaviour when I was testing with one GlusterFS node down. I think it was something to do with the endpoints API changing. See the comments in #13807 near the end when I discovered it.

**Comment by jsafrane** [comment] 2015-09-24 13:35
@bogdit With golang 1.5 as available in Fedora 23 Beta and a map with two items, `for hostIP := range addr` returns the first one first in around 85% of cases. With 5 items in the map, the first one is returned first in ~50% of cases. It's doesn't look _that_ random to me.

Anyway, it will just make the first endpoint more busy, IMO there is no serious bug.

**Comment by gizmonicus** [comment] 2015-09-24 17:36
@jsafrane I agree that it isn't a serious bug since @bodgit fixed the "try other endpoints" logic; that was the biggest problem. I'm not terribly concerned with a mount storm because of the size of my cluster, but others might.

**Comment by wattsteve** [comment] 2016-08-11 23:51
@thockin close this

**Closed** 2016-08-12 06:51 UTC
Labels: area/storage, team/cluster
