### ISSUE TITLE
Flaky: DisruptionController evictions: enough pods, replicaSet, percentage => should allow an eviction

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45706] opened 2017-05-12 07:23 UTC
Failure clusters: https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=should%20allow%20an%20eviction

Most likely [cluster](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=should%20allow%20an%20eviction#63a36434077ff31ae29e) causing flakiness:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:363
Expected error:
    <*errors.errorString | 0xc420179330>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:247
```

/kind flake
/priority important-soon

@kubernetes/sig-scheduling-test-failures 
/assign @timothysc @davidopp 

Sig leads, please `/assign` someone to investigate and `/unassign` yourself. 
If this failure is more appropriate for another sig please `/sig better-sig` and `/sig-remove scheduling`

**Comment by fejta** [comment] 2017-05-12 07:25
Note that [DisruptionController should update PodDisruptionBudget status](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=should%20update%20PodDisruptionBudget%20status#63a36434077ff31ae29e) also started failing at the same time

**Comment by timothysc** [comment] 2017-05-12 20:12
@fejta So I'm digging backwards from the original gubernator link and some data doesn't make any sense to me,  when you have a moment could you poke me on irc.

**Comment by fejta** [comment] 2017-05-12 20:47
Note that failures from PRs will be noisy, since they also may contain people's possibly bad changes that aren't merged.

**Comment by timothysc** [comment] 2017-05-12 21:23
So in looking at the non-PR and just the CI I'm seeing a lot of : 

"May 11 02:13:53.334: All nodes should be ready after test, Not ready nodes: ", gke-bootstrap-e2e-default-pool-2e2dbc5c-dtrk"  

which to me seems like an infra flake, but if you are seeing something that I'm not, feel free to point it out to me.

**Comment by fejta** [comment] 2017-05-12 21:33
Do you have a gubernator link? Are you focusing on the AWS jobs (put aws into the job textbox)?

https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=aws&test=should%20allow%20an%20eviction

**Comment by timothysc** [comment] 2017-05-12 21:42
Ahh I was not, thx!

**Comment by davidopp** [comment] 2017-05-12 22:05
PDB is now owned by @kubernetes/sig-apps-misc 

cc/ @mml

**Comment by davidopp** [comment] 2017-05-12 22:05
(Which isn't to say that @timothysc shouldn't investigate -- I'm sure everyone will be very happy if he does :) )

**Comment by mml** [comment] 2017-05-18 17:32
Just saw this.  I will take a look.

**Comment by mml** [comment] 2017-05-18 17:47
Well this is weird.  I downloaded the controller manager log from a failed run.

```
% grep disruption.go ~/Downloads/kube-controller-manager.log
zsh: exit 1     grep disruption.go ~/Downloads/kube-controller-manager.log
% wc -l !$
wc -l ~/Downloads/kube-controller-manager.log
6931 /usr/local/google/home/mml/Downloads/kube-controller-manager.log
```

ah ha!

```
I0516 20:54:54.679359       5 controllermanager.go:437] Starting "disruption"                                                                                                                
W0516 20:54:54.679370       5 controllermanager.go:444] Skipping "disruption"
```

But... why?  Have we changed how `kube-controller-manager` is invoked on AWS?

**Comment by mml** [comment] 2017-05-18 17:58
It would be awesome to have a little pre-req on e2e tests that says "this test is meaningless unless controller X is running.  check if it is and fail immediately if not.".  To do that we need to have the running controllers exported as prometheus metrics, and a hook that lets us query prometheus metrics from kube-controller-manager.

**Comment by mml** [comment] 2017-05-18 18:04
DisruptionController refuses to start unless `poddisruptionbudgets` in `policy/v1beta1` (exactly) is available.  This is exactly the pattern we discourage [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L320), but the root cause here is probably that we aren't passing the right flags to `kube-apiserver` to turn on the policy group.

**Comment by kargakis** [comment] 2017-06-02 19:17
Dupe of https://github.com/kubernetes/kubernetes/issues/46871?

**Comment by justinsb** [comment] 2017-06-02 19:33
Not sure if a dup.  #46871 is a flake though - i.e. sometimes the controllers are skipped, sometimes they are not.  My knee-jerk reaction was some sort of race between API registration and controller startup.

I'm not clear whether this is a flake or not?  If it's a flake, I don't think it's about whether flags are enabled (unless we have deeper problems ;-) )

What is doubly weird is that when I look at the k-c-m logs for the most recent failures for that cluster of failures, the kops jobs have the "skipping" error, but the gce ones do not

e.g.

`W0602 03:57:59.767202       5 controllermanager.go:449] Skipping "disruption"`

Maybe there are 2 different things happening here.

**Comment by mml** [comment] 2017-06-05 18:39
#46871 is closely related, and I'm working in this area.  @justinsb, I
think it makes most sense for you to either take both of these issues, or
assign both to me.  Your call.  :-)

**Comment by foxish** [comment] 2017-06-16 22:51
This has not failed in the last 3 days. The issue appears to have been at least partly https://github.com/kubernetes/kubernetes/issues/47135 and https://github.com/kubernetes/kubernetes/issues/46871. I think this can be closed now.

**Comment by foxish** [comment] 2017-06-16 22:59
Closing, please reopen if these recur.

**Closed by foxish** 2017-06-16 22:59 UTC
Labels: kind/flake, priority/important-soon, sig/apps, sig/scheduling
