### ISSUE TITLE
Kubernetes does not support Azure Standard Load Balancers when provisioning services of type LoadBalancer 

### ISSUE THREAD

**Issue by xtophs** [kubernetes/kubernetes#61783] opened 2018-03-27 17:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

/kind feature
/sig azure

**What happened**:
Azure offers two different kinds of External Load Balancers, Basic and Standard. Differences are documented at: [https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-overview](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-overview)

**What you expected to happen**:
Kubernetes services offer a way to choose between Basic and Standard Load Balancers when provisioning a service of type LoadBalancer

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by karataliu** [comment] 2018-03-29 02:30
Duplicate of #60485

**Comment by feiskyer** [comment] 2018-03-30 01:42
Dup of #60485

**Closed by feiskyer** 2018-03-30 01:42 UTC
Labels: kind/feature, sig/azure
