### ISSUE TITLE
kube-push may have broke minion container images.

### ISSUE THREAD

**Issue by jetole** [kubernetes/kubernetes#18467] opened 2015-12-09 21:32 UTC
I was unable to verify this but it appears to me that when I did a push from 1.0.6 to 1.1.2, my new minion images were no longer able to register with the master server due to an "x509 unknown certificate authority". This made it so I was unable to scale the node sizes by adding more nodes.

**Comment by roberthbailey** [comment] 2015-12-09 21:39
To clarify, this is the new kubelet binary not being able to register with the master?

Where are you running your cluster?

**Comment by jetole** [comment] 2015-12-10 03:31
Yes. It's a new node / new kubelet binary. It's on GCE. I ran kube-down and kube-up creating a fresh 1.1.2 cluster and new nodes have successfully registered. I had added new nodes to 1.0.6 before running kube-push and new nodes had registered.

**Comment by roberthbailey** [comment] 2015-12-10 05:30
The kube-push flow isn't as thoroughly tested as the rolling-update-to-new-instance-template flow, so I'm not too surprised that it didn't work across minor versions. The kubelet gets a bunch of configuration from salt by way of env variables in the metadata server, and if the metadata values haven't been updated (and salt hasn't either) then it's quite possible for the kubelet to get into a state where it can't operate successfully.

**Comment by bgrant0607** [comment] 2016-02-01 19:56
Dupe of #17397

**Closed by bgrant0607** 2016-02-01 19:56 UTC
Labels: area/cluster-lifecycle, priority/P2, team/control-plane
