### ISSUE TITLE
No option to write hook on notification on top of kubernetes deployment completion or deployment stuck

### ISSUE THREAD

**Issue by jeyanthimuthuram** [kubernetes/kubernetes#59173] opened 2018-02-01 06:49 UTC
> /kind feature

**What happened**:

Can't able to write any hooks for notification or any other calls following the deployment is completed or stuck on top of kubernetes deployment apply

Because once `kubernetes apply -f deployment.yml` the process handler is transfered to the deamon which is good but we can't able to keep track of the deployment status of the current , it would be nice if there is a hook or something that would sophisticate this with the deployment success or failure.

**Comment by jhorwit2** [comment] 2018-02-03 19:58
@jeyanthimuthuram `kubectl rollout status deployment <name>` can be used to watch the status. It'll return a non-zero exit code if it fails. Does this satisfy what you want?

/kind feature

**Comment by jhorwit2** [comment] 2018-02-03 20:00
@jeyanthimuthuram I'm going to close this ticket since it's a duplicate of https://github.com/kubernetes/kubernetes/issues/14512. Please join the discussion there!

/close

**Closed by jhorwit2** 2018-02-03 20:00 UTC
Labels: kind/feature, sig/cluster-lifecycle
