### ISSUE TITLE
Update-bazel.sh broken on 1.10 release branch (?)

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#64972] opened 2018-06-11 12:36 UTC
```
$ hack/update-bazel.sh
../../internal/repos/remote.go:29:2: cannot find package "golang.org/x/tools/go/vcs" in any of:
	/var/folders/gg/zn9yfdld21j7xg5jnj5zz5d80000gn/T/tmp.dtMzxluX/go/src/github.com/bazelbuild/bazel-gazelle/vendor/golang.org/x/tools/go/vcs (vendor tree)
	/Users/sts/.bin/go-1.9/src/golang.org/x/tools/go/vcs (from $GOROOT)
	/var/folders/gg/zn9yfdld21j7xg5jnj5zz5d80000gn/T/tmp.dtMzxluX/go/src/golang.org/x/tools/go/vcs (from $GOPATH)
!!! [0611 14:34:36] Call tree:
!!! [0611 14:34:36]  1: hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:483
  Error in /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:483. '((i<3-1))' exited with status 1
Call stack:
  1: /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:483 kube::util::go_install_from_commit(...)
  2: hack/update-bazel.sh:34 main(...)
Exiting with status 1
!!! [0611 14:34:36] Call tree:
!!! [0611 14:34:36]  1: hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:473
  Error in /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:473. '((i<3-1))' exited with status 1
Call stack:
  1: /Users/sts/Quellen/kubernetes/src/k8s.io/kubernetes/hack/lib/util.sh:473 kube::util::go_install_from_commit(...)
  2: hack/update-bazel.sh:34 main(...)
Exiting with status 1
```

**Comment by nikhita** [comment] 2018-06-11 12:55
I get the same error too.

**Comment by nikhita** [comment] 2018-06-11 12:59
Looks related to https://github.com/bazelbuild/bazel-gazelle/pull/228

**Comment by nikhita** [comment] 2018-06-11 13:00
@sttts this looks like a dupe of https://github.com/kubernetes/kubernetes/issues/64925.

**Comment by nikhita** [comment] 2018-06-11 13:03
I'll close this in favour of #64925 
/close

**Closed by nikhita** 2018-06-11 13:03 UTC
Labels: kind/bug, priority/important-soon, sig/testing

**Comment by sttts** [comment] 2018-06-11 17:36
@ixdy works fine now. Thanks for the quick fix 👍
