### ISSUE TITLE
e2e flake: Error building GCE/GKE provider

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#22190] opened 2016-02-29 18:19 UTC
Test failure in start of `e2e.go`:
```
[20] Feb 28 19:26:14.607: INFO: Using service account "211744435552-compute@developer.gserviceaccount.com" as token source.
[20] I0228 19:26:14.607444    2017 gce.go:280] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:"211744435552-compute@developer.gserviceaccount.com"}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
[20] F0228 19:26:15.358650    2017 e2e.go:268] Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/networks?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
[21] Feb 28 19:26:14.627: INFO: Fetching cloud provider for "gce"
[21] 
```

[kubernetes-pull-build-test-e2e-gce/30906](https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/20415/kubernetes-pull-build-test-e2e-gce/30906)

It's possible this was just a connectivity loss with metadataserver on the pr-builder vm, not sure if the failure time lines up with restart/upgrades. cc @ixdy, @spxtr

**Comment by fejta** [comment] 2016-03-01 08:00
https://github.com/golang/oauth2/blob/master/google/google.go#L118 == can't get a token line

https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/compute/metadata/metadata.go#L167 == the reason OnGCE() is failing

**Comment by fejta** [comment] 2016-03-03 03:28
OnGCE() in metadata.go needs to get updated to retry on 500 errors, as by metadata server will be down by design during migrations and upgrades.

**Comment by fejta** [comment] 2016-04-06 23:00
@jlowdermilk didn't you fix this?

**Comment by jlowdermilk** [comment] 2016-04-06 23:19
No, I added retry in the gcloud cli, this is in the go generated client library. It does looks like there was a fix [upstream](https://github.com/GoogleCloudPlatform/gcloud-golang/commit/f95c875f2894b735501920cce2ab858f2110b23a) that we pulled in, so we can close this. Buildcop can reopen if new occurrences are found.

**Comment by lavalamp** [comment] 2016-06-12 20:23
This doesn't appear to be something bad that merged, but testing took a huge turn for the worse about 8PM last night. Maybe something in jenkins needs to be restarted?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L81
	
BeforeSuite

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:157 Jun 11 21:18:09.857: Failed to setup provider config: Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce/global/networks?alt=json: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/661044217466-compute@developer.gserviceaccount.com/token: dial tcp 169.254.169.254:80: i/o timeout

**Comment by fejta** [comment] 2016-06-12 22:34
I'll take a look...

**Comment by fejta** [comment] 2016-06-12 23:01
I suspect it has something to do with the metadata-cache not working well with the drift-token.

I'm going to experiment with replacing a few large instances with a metadata-cache in favor of a larger numbers of smaller instances with no metadata-cache.

**Comment by fejta** [comment] 2016-06-13 04:04
Things seem back to normal

**Closed by fejta** 2016-06-13 04:04 UTC
Labels: help-wanted, kind/flake, priority/P0, team/test-infra
