### ISSUE TITLE
ResourceQouta takes into account removed pods

### ISSUE THREAD

**Issue by aszecowka** [kubernetes/kubernetes#63981] opened 2018-05-17 16:15 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I create a namespace and define ResourceQouta for this namespace. Then I repeat: 
- create pod which requests less memory than defined in ResourceQouta for that namespace
- delete this pod

Finally, I was unable to create the pod, because the quota was exceeded.

**What you expected to happen**:
I am able to create the pod and ResourceQuota doesn't take into account removed pods.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create namespace test

cat res-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-demo
spec:
  hard:
    memory: 400Mi

kubectl create -f res-quota.yaml -n test

cat nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: 50Mi
      requests:
        memory: 50Mi

 kubectl create -f nginx.yaml -n test
 kubectl describe resourcequota -n test
Name:       mem-demo
Namespace:  test
Resource    Used  Hard
--------    ----  ----
memory      50Mi  400Mi

kubectl delete -f nginx.yaml -n test

kubectl describe resourcequota -n test
Name:       mem-demo
Namespace:  test
Resource    Used  Hard
--------    ----  ----
memory      50Mi  400Mi

```

Repeat creating and removing pod and finally I get:
```
kubectl create -f nginx.yaml -n test
Error from server (Forbidden): error when creating "nginx.yaml": pods "my-pod" is forbidden: exceeded quota: mem-demo, requested: memory=50Mi, used: memory=400Mi, limited: memory=400Mi
```
Even though no pods were in the namespace:
```
kc get pods -n test
No resources found.

kc describe resourcequota -n test
Name:       mem-demo
Namespace:  test
Resource    Used   Hard
--------    ----   ----
memory      400Mi  400Mi
```

It looks like ResourceQuota do not update used memory when pods are removed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```minikube version: v0.26.1```
- OS (e.g. from /etc/os-release): MacOs HighSierra 10.13.2
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aszecowka** [comment] 2018-05-17 16:19
@kubernetes/sig-api-machinery-bugs

**Comment by jennybuckley** [comment] 2018-05-17 20:13
@yliaog @derekwaynecarr

**Comment by hzxuzhonghu** [comment] 2018-05-18 02:46
Tried on master.  Could not reproduce.

**Comment by aszecowka** [comment] 2018-05-18 07:29
@hzxuzhonghu I can confirm that this problem does NOT exist on brand new minikube. My problem occurs on minikube where some additional components were installed. I will try to find which component influence behavior of ResourceQuota. Sorry for the confusion.

**Comment by hzxuzhonghu** [comment] 2018-05-18 08:52
So could close this issue?

**Closed** 2018-05-18 08:54 UTC
Labels: kind/bug, sig/api-machinery, sig/scheduling

**Comment by aszecowka** [comment] 2018-06-13 13:45
For people who also encounter this problem, probably it was caused by the bug in the resource quota controller, which caused deadlocks and in k8s 1.9.4 it was already fixed (https://github.com/kubernetes/kubernetes/commit/010a127314a935d8d038f8dd4559fc5b249813e4#diff-ea58bce3e7609824aaacbc6149b3ecd2)
