### ISSUE TITLE
Kubectl exec takes >5 minutes to bring up a bash shell

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#7551] opened 2015-04-30 06:01 UTC
`gcloud alpha container kubectl exec -p mysql-sqhv0 -c mysql -i -t bash`

Using a Mac in multiple locations, the above command takes about 5 minutes before it returns a prompt, but then it's fine (and speedy).

Doing docker exec on the node itself is instantaneous. Any idea what would cause this, or how I can debug?

**Comment by smarterclayton** [comment] 2015-04-30 18:10
I've seen something like this before.  @ncdc any ideas on what could be the cause?

**Comment by ncdc** [comment] 2015-04-30 18:13
When I tested against a GCE cluster, I was seeing really slow performance - slow enough that it timed out trying to create the underlying streams. I haven't investigated in detail.

You can add `DEBUG=1` to the client as well as to the kubelet, and it will print out spdystream debug info.

**Comment by aronchick** [comment] 2015-05-01 00:19
Sorry, can you help on where I put "DEBUG=1"?

**Comment by ncdc** [comment] 2015-05-01 01:01
When you run kubectl or the kubelet. I don't know if this would work, but you could try `DEBUG=1 gcloud alpha container kubectl exec -p mysql-sqhv0 -c mysql -i -t bash`. If that doesn't pass the env through to kubectl, it won't work, however. For the kubelet, you'd need to put it in I guess the init.d script that starts it up.

Doing `DEBUG` will really just show you when streams are created, when data is sent/received, and when streams & connections are closed. It won't help diagnose slowness. But if you can see the debug output, you could at least get a sense for if the streams are being created quickly by both client (kubectl) and server (kubelet). 

I did also stumble across this today which might be relevant: https://github.com/golang/go/issues/10544.

The future is to move to HTTP/2 once we have a usable library in Go. In the meantime, I can take a look at this, but I probably won't be able to get to it for a while.

**Comment by aronchick** [comment] 2015-05-01 01:19
No problem - i've been able to work around by just sshing into the node and
then docker exec-ing up to the container.

No joy on adding "DEBUG=1" to the front.

**Comment by aronchick** [comment] 2015-05-01 04:56
Here's the output of DEBUG:

```
# ~/Code/images/storage [21:40:38]
$ DEBUG=1 gcloud alpha container kubectl exec -p mysql-6nmud -c mysql -i -t -- bash -il
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d9e140) Create stream
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d9e140) Stream added, broadcasting: 1
2015/04/30 21:40:42 (0x208d9e0a0) Reply frame received for 1
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d9e1e0) Create stream
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d9e1e0) Stream added, broadcasting: 3
2015/04/30 21:40:42 (0x208d9e0a0) Reply frame received for 3
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d96000) Create stream
2015/04/30 21:40:42 (0x208d9e0a0) (0x208d96000) Stream added, broadcasting: 5
2015/04/30 21:40:42 (0x208d9e0a0) Data frame received for 3
2015/04/30 21:40:42 (0x208d9e1e0) (3) Data frame handling
2015/04/30 21:40:42 (0x208d9e0a0) Reply frame received for 5
2015/04/30 21:40:42 (0x208d9e0a0) Data frame received for 5
2015/04/30 21:40:42 (0x208d96000) (5) Data frame handling
2015/04/30 21:40:42 (0x208d96000) (5) Data frame sent
root@mysql-6nmud:/# 2015/04/30 21:45:42 EOF received
2015/04/30 21:45:42 Stream removed, broadcasting: 5
2015/04/30 21:45:42 Stream removed, broadcasting: 3
2015/04/30 21:45:42 Stream removed, broadcasting: 1
2015/04/30 21:45:42 Stream removed, broadcasting: 1
2015/04/30 21:45:42 Stream removed, broadcasting: 3
2015/04/30 21:45:42 Stream removed, broadcasting: 5
```

Interestingly, when I run `date` it happens in less than a second.

```
$ DEBUG=1 gcloud alpha container kubectl exec -p mysql-6nmud -c mysql -i -t -- date
2015/04/30 21:49:18 (0x208daa0a0) (0x208daa140) Create stream
2015/04/30 21:49:18 (0x208daa0a0) (0x208daa140) Stream added, broadcasting: 1
2015/04/30 21:49:19 (0x208daa0a0) Reply frame received for 1
2015/04/30 21:49:19 (0x208daa0a0) (0x208c7e0a0) Create stream
2015/04/30 21:49:19 (0x208daa0a0) (0x208c7e0a0) Stream added, broadcasting: 3
2015/04/30 21:49:19 (0x208daa0a0) Reply frame received for 3
2015/04/30 21:49:19 (0x208daa0a0) (0x208c7e1e0) Create stream
2015/04/30 21:49:19 (0x208daa0a0) (0x208c7e1e0) Stream added, broadcasting: 5
2015/04/30 21:49:19 (0x208daa0a0) Data frame received for 3
2015/04/30 21:49:19 (0x208c7e0a0) (3) Data frame handling
2015/04/30 21:49:19 (0x208daa0a0) Reply frame received for 5
2015/04/30 21:49:19 (0x208daa0a0) Data frame received for 5
2015/04/30 21:49:19 (0x208c7e1e0) (5) Data frame handling
2015/04/30 21:49:19 (0x208c7e1e0) (5) Data frame sent
2015/04/30 21:49:19 (0x208daa0a0) Data frame received for 5
2015/04/30 21:49:19 (0x208c7e1e0) (5) Data frame handling
Fri May  1 04:49:20 UTC 20152015/04/30 21:49:19 EOF received

2015/04/30 21:49:19 (0x208c7e1e0) (5) Data frame sent
2015/04/30 21:49:19 (0x208daa0a0) Data frame received for 5
2015/04/30 21:49:19 Stream removed, broadcasting: 5
2015/04/30 21:49:19 Stream removed, broadcasting: 3
2015/04/30 21:49:19 Stream removed, broadcasting: 1
2015/04/30 21:49:19 Stream removed, broadcasting: 1
2015/04/30 21:49:19 Stream removed, broadcasting: 3
2015/04/30 21:49:19 Data frame gone away for 5
2015/04/30 21:49:19 Stream removed, broadcasting: 5
2015/04/30 21:49:19 (0x208daa0a0) Go away received
```

If I was to hazard a guess, I think it's actually working fine, and the bash command is not attaching properly. Then, when the 5 minutes goes by, it times out, and only then it flushes out all the output. This appears to be verified below - I executed the command, typed `date` and then waited. You can see that the command was executed in less than 1 second, but only 5 minutes later did I actually receive it (when the shell auto-logged out).

```
$ DEBUG=1 gcloud alpha container kubectl exec -p mysql-6nmud -c mysql -i -t -- bash -il
2015/04/30 21:49:26 (0x208e78000) (0x208e780a0) Create stream
2015/04/30 21:49:26 (0x208e78000) (0x208e780a0) Stream added, broadcasting: 1
2015/04/30 21:49:26 (0x208e78000) Reply frame received for 1
2015/04/30 21:49:26 (0x208e78000) (0x208e78140) Create stream
2015/04/30 21:49:26 (0x208e78000) (0x208e78140) Stream added, broadcasting: 3
2015/04/30 21:49:26 (0x208e78000) Reply frame received for 3
2015/04/30 21:49:26 (0x208e78000) (0x208e78280) Create stream
2015/04/30 21:49:26 (0x208e78000) (0x208e78280) Stream added, broadcasting: 5
2015/04/30 21:49:26 (0x208e78140) (3) Writing data frame
2015/04/30 21:49:26 (0x208e78000) Data frame received for 3
2015/04/30 21:49:26 (0x208e78140) (3) Data frame handling
2015/04/30 21:49:26 (0x208e78000) Reply frame received for 5
2015/04/30 21:49:26 (0x208e78000) Data frame received for 5
2015/04/30 21:49:26 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:26 (0x208e78280) (5) Data frame sent
root@mysql-6nmud:/# 2015/04/30 21:49:26 (0x208e78000) Data frame received for 5
2015/04/30 21:49:26 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:26 (0x208e78280) (5) Data frame sent
d2015/04/30 21:49:26 (0x208e78140) (3) Writing data frame
2015/04/30 21:49:26 (0x208e78000) Data frame received for 5
2015/04/30 21:49:26 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:26 (0x208e78280) (5) Data frame sent
a2015/04/30 21:49:26 (0x208e78140) (3) Writing data frame
2015/04/30 21:49:26 (0x208e78000) Data frame received for 5
2015/04/30 21:49:26 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:26 (0x208e78280) (5) Data frame sent
t2015/04/30 21:49:26 (0x208e78140) (3) Writing data frame
2015/04/30 21:49:26 (0x208e78000) Data frame received for 5
2015/04/30 21:49:26 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:26 (0x208e78280) (5) Data frame sent
e2015/04/30 21:49:26 (0x208e78140) (3) Writing data frame
2015/04/30 21:49:27 (0x208e78000) Data frame received for 5
2015/04/30 21:49:27 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:27 (0x208e78280) (5) Data frame sent

2015/04/30 21:49:27 (0x208e78000) Data frame received for 5
2015/04/30 21:49:27 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:27 (0x208e78280) (5) Data frame sent
2015/04/30 21:49:27 (0x208e78000) Data frame received for 5
2015/04/30 21:49:27 (0x208e78280) (5) Data frame handling
Fri May  1 04:49:27 UTC 2015
2015/04/30 21:49:27 (0x208e78280) (5) Data frame sent
2015/04/30 21:49:27 (0x208e78000) Data frame received for 5
2015/04/30 21:49:27 (0x208e78280) (5) Data frame handling
2015/04/30 21:49:27 (0x208e78280) (5) Data frame sent
root@mysql-6nmud:/# 2015/04/30 21:54:26 EOF received
2015/04/30 21:54:26 Stream removed, broadcasting: 5
2015/04/30 21:54:26 Stream removed, broadcasting: 3
2015/04/30 21:54:26 Stream removed, broadcasting: 1
2015/04/30 21:54:26 Stream removed, broadcasting: 1
2015/04/30 21:54:26 Stream removed, broadcasting: 3
2015/04/30 21:54:26 Stream removed, broadcasting: 5
```

**Comment by smarterclayton** [comment] 2015-05-01 14:54
Seems like a flow control or flushing problem.  Hrm, I think I saw something like this when testing SSH over exec as well.

**Comment by aronchick** [comment] 2015-05-08 16:37
Yep, it's something with the gcloud wrapper - going straight against the kubernetes cluster with ```cluster/kubectl.sh exec -p node_name -ti bash``` is instantaneous

**Comment by jlowdermilk** [comment] 2015-05-08 18:54
There are a few issues like this where the wrapper causes problems. We're actually deprecating the gcloud wrapper and making standalone kubectl work automatically with GKE clusters. So the flow would be use gcloud to create cluster, then just use kubectl (the cloudsdk includes kubectl and makes it available on your PATH) directly. In the meantime, [`gcloud alpha container kubectl --help`](https://cloud.google.com/sdk/gcloud/reference/alpha/container/kubectl) has instructions for setting environment variable to use kubectl directly talk to a GKE cluster.

**Comment by ncdc** [comment] 2015-09-30 20:52
@aronchick @jlowdermilk since this works without the gcloud wrapper, and the wrapper is being deprecated for kubectl, should we close this issue?

**Comment by jlowdermilk** [comment] 2015-09-30 20:59
Yeah, this issue is obsolete. We no longer wrap kubectl calls in gcloud; kubectl is provided as a standalone gcloud component, and `gcloud container` creates/maintains kubeconfig entries for GKE clusters, so standalone kubectl works like it does for any other provider.

**Closed by jlowdermilk** 2015-09-30 20:59 UTC
Labels: priority/P2, team/CSI
