### ISSUE TITLE
Kube-scheduler dies when connection to API server is lost

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#41428] opened 2017-02-14 18:57 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kube-scheduler, scheduler, dies, lost, master

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`): **v1.5.2**

**Environment**:
- **Cloud provider or hardware configuration**: VirtualBox VM
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04

**What happened**:

The kube-scheduler process dies when it looses connection to the API server. The behavior is not deterministic. That is, I have not been able to reproduce this issue 100% of the time.

It is being caused due to: https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/app/server.go#L108

**What you expected to happen**:
The kube-scheduler process could enter a crash-loop until it's able to talk to the API server again.

**How to reproduce it** (as minimally and precisely as possible):
Stop the API server that is being consumed by the scheduler.

**Anything else we need to know**:

Logs:
```
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.119911   17481 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.PersistentVolumeClaim: Get https://192.168.42.2:6443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122210   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: Failed to list *extensions.ReplicaSet: Get https://192.168.42.2:6443/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122486   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get https://192.168.42.2:6443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122516   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:473: Failed to list *api.ReplicationController: Get https://192.168.42.2:6443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122539   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:466: Failed to list *api.PersistentVolume: Get https://192.168.42.2:6443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122570   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:460: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:10 node001 kube-scheduler[17481]: E0214 18:38:10.122594   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:470: Failed to list *api.Service: Get https://192.168.42.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.120409   17481 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.PersistentVolumeClaim: Get https://192.168.42.2:6443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.120458   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:457: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.122800   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: Failed to list *extensions.ReplicaSet: Get https://192.168.42.2:6443/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.122835   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get https://192.168.42.2:6443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.123933   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:460: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.124245   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:466: Failed to list *api.PersistentVolume: Get https://192.168.42.2:6443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.124275   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:473: Failed to list *api.ReplicationController: Get https://192.168.42.2:6443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.124300   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:470: Failed to list *api.Service: Get https://192.168.42.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:11 node001 kube-scheduler[17481]: E0214 18:38:11.698958   17481 leaderelection.go:228] error retrieving resource lock kube-system/kube-scheduler: Get https://192.168.42.2:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.123338   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:457: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.123374   17481 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.PersistentVolumeClaim: Get https://192.168.42.2:6443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.123403   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: Failed to list *extensions.ReplicaSet: Get https://192.168.42.2:6443/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.132099   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:473: Failed to list *api.ReplicationController: Get https://192.168.42.2:6443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.132131   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:466: Failed to list *api.PersistentVolume: Get https://192.168.42.2:6443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.132158   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:460: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.132179   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get https://192.168.42.2:6443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:12 node001 kube-scheduler[17481]: E0214 18:38:12.132198   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:470: Failed to list *api.Service: Get https://192.168.42.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.124901   17481 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.PersistentVolumeClaim: Get https://192.168.42.2:6443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.124950   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:457: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.124985   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: Failed to list *extensions.ReplicaSet: Get https://192.168.42.2:6443/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.135062   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get https://192.168.42.2:6443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.135109   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:460: Failed to list *api.Pod: Get https://192.168.42.2:6443/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.135145   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:466: Failed to list *api.PersistentVolume: Get https://192.168.42.2:6443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.135176   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:473: Failed to list *api.ReplicationController: Get https://192.168.42.2:6443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.135210   17481 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:470: Failed to list *api.Service: Get https://192.168.42.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.698619   17481 leaderelection.go:228] error retrieving resource lock kube-system/kube-scheduler: Get https://192.168.42.2:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.698735   17481 leaderelection.go:228] error retrieving resource lock kube-system/kube-scheduler: Get https://192.168.42.2:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp 192.168.42.2:6443: getsockopt: connection refused
Feb 14 18:38:13 node001 kube-scheduler[17481]: E0214 18:38:13.698758   17481 event.go:258] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'node001 stopped leading'
Feb 14 18:38:13 node001 kube-scheduler[17481]: I0214 18:38:13.701856   17481 leaderelection.go:207] failed to renew lease kube-system/kube-scheduler
Feb 14 18:38:13 node001 kube-scheduler[17481]: F0214 18:38:13.702835   17481 server.go:169] lost master
```

**Comment by alejandroEsc** [comment] 2017-02-15 22:05
@alexbrand could you give a bit more detail about the cluster where you see this happening. Is it an HA cluster? Is there more than one kube-scheduler? Also the logs show that, rightly so, the scheduler lost its leader role, was there any message indicating that it has stopped?

**Comment by alexbrand** [comment] 2017-02-15 22:17
@alejandroEsc This is a single node cluster. There is only one kube-scheduler running. 

The last log entry is a call to glog's fatal, which results in os.Exit(255). This is evidenced in the systemd logs:
```
Feb 15 22:15:25 node001 kube-scheduler[17481]: F0215 22:15:25.586659   17481 server.go:169] lost master
Feb 15 22:15:25 node001 systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=255/n/a
```

**Comment by alejandroEsc** [comment] 2017-02-24 19:29
@alexbrand should this issue be closed?

**Comment by alexbrand** [comment] 2017-02-24 19:32
Is it expected for the scheduler to exit if it looses connection to the master? I would expect it to enter a crash loop, waiting until it can connect again.

**Comment by smarterclayton** [comment] 2017-02-28 00:53
Today, any "leader elected" component (scheduler or controller manager) will exit if it loses the lease, which simplifies setup and creates a clear signal in the logs and the system for debugging.  So this is expected.

**Comment by alejandroEsc** [comment] 2017-02-28 16:57
@smarterclayton by this is expected you mean that the component shuts itself down? I would think it would continue to attempt a connection?

**Comment by tonylambiris** [comment] 2017-04-11 16:49
This issue seen with kubernetes 1.6.2-beta.0 as well:
```
Apr 11 16:43:16 csos-builder.csos.io kube-apiserver[65317]: I0411 16:43:16.765050   65317 wrap.go:75] GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (2.403347ms) 2
00 [[kube-scheduler/1.6.2 (linux/amd64) kubernetes/aaf9ea0/leader-election] 172.27.1.10:27986]
Apr 11 16:43:16 csos-builder.csos.io etcd[65157]: found common name csos-builder.csos.io
Apr 11 16:43:16 csos-builder.csos.io kube-apiserver[65317]: I0411 16:43:16.770697   65317 wrap.go:75] PUT /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (4.239189ms) 2
00 [[kube-scheduler/1.6.2 (linux/amd64) kubernetes/aaf9ea0/leader-election] 172.27.1.10:27986]
```
I sent a log message using logger(1):
```
Apr 11 16:43:17 csos-builder.csos.io csos[68571]: Restarting kube-apiserver
Apr 11 16:43:17 csos-builder.csos.io systemd[1]: Stopping Kubernetes API Server...
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.980983   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981182   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.980965   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981019   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981109   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981124   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981138   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981151   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: I0411 16:43:17.981170   65092 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: E0411 16:43:17.985509   65092 reflector.go:304] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:451: Failed to watch *v1.Pod: Get https://172.27.1.10:6443/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=168146&timeoutSeconds=306&watch=true: dial tcp 172.27.1.10:6443: getsockopt: connection refused
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: W0411 16:43:17.985605   65092 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:70: watch of *v1.PersistentVolume ended with: very short watch
Apr 11 16:43:17 csos-builder.csos.io kube-scheduler[65092]: W0411 16:43:17.985709   65092 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:70: watch of *v1.ReplicationController ended with: very short watch
```
Issuing a full restart on all kubernetes services solved the issue. All services running out of systemd using mostly the vanilla systemd files k8s ships with.

**Comment by kargakis** [comment] 2017-04-11 16:57
@kubernetes/sig-scheduling-bugs

**Comment by timothysc** [comment] 2017-04-11 17:04
Leader election code will do this on purpose b/c it is no longer the leader, this is not a bug.

**Comment by yekaifeng** [comment] 2017-07-14 03:18
If a scheduler leader is not able to renew() leader lock in etcd for a period longer than leader-elect-renew-deadline, which because of whatever reasons (api-server down, etcd leader switch, network unsable),  it should switch to follower mode and continue running instead of dying. When the running environment resume normal,  it can continue to acquire() for leader.

Consider such situation: 5 schedulers, accessing 1 api-server. Kill api-server, wait 15 sec, start api-server, wait 15 sec, kill again. All schedulers are gone after 5 iterates.

This behavior is not acceptable in production environment. And it is not a good practice for a production that designed for HA.

I would like to provide more test data about this and give a pull request for fixing it.

**Comment by bsalamat** [comment] 2017-07-14 05:00
@yekaifeng Please note that a new scheduler is created as soon as a scheduler exits. So, in the scenario that you described, you will have 5 new schedulers.

**Comment by yekaifeng** [comment] 2017-07-14 07:18
@bsalamat I guess, in your practice, you were using service guarding tool such as systemd or supervisord. So that it spawns a new one as long as the old one exited. 

For sure it works for most cases. While it will hide some deep system issues and make them difficult to exposed, such as network turbulence, etcd3 leader switch frequenly ... In addition, it brings extra dependency.

**Comment by bsalamat** [comment] 2017-07-14 17:43
@yekaifeng Kubelet creates a new scheduler. This is a very common practice to have watchdogs for critical system components that recreates them when they exit.

**Comment by timothysc** [comment] 2017-07-17 16:21
Thx for reporting, but as called out this is not actually a bug, closing.

**Closed by timothysc** 2017-07-17 16:21 UTC
Labels: kind/bug, sig/scheduling

**Comment by yekaifeng** [comment] 2017-07-26 04:58
#49260

**Comment by neerajrana-ivytech** [comment] 2023-04-06 10:46
Hi
i'm facing an issue may be related to this, actually when i restarted my application server (file server) , the running pods lost the connect with the application server in kubernates cluster. To resolve this thing i have to restart the pods again.

Can you guys help me here
