### ISSUE TITLE
high DELETE replicationcontrollers request latency in 2k node tests

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#67701] opened 2018-08-22 12:27 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/136 has failed with:

```
There should be no high-latency requests
I0818 17:43:08.589]   Expected
I0818 17:43:08.590]       <int>: 1
I0818 17:43:08.590]   not to be >
I0818 17:43:08.590]       <int>: 0
```

```
I0818 17:37:15.947] Aug 18 17:37:15.946: INFO: WARNING Top latency metric: {Resource:replicationcontrollers Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:3.13ms Perc90:11.866ms Perc99:1.197081s Perc100:0s} Count:2020}
```

Sample trace from kube-apiserver.log (I see ~10 requests like that, all of them roughly at the same time):

```
I0818 17:01:04.919640       1 trace.go:76] Trace[637673882]: "Delete /api/v1/namespaces/e2e-tests-density-30-20-hn4cw/replicationcontrollers/density-latency-pod-39" (started: 2018-08-18 17:01:03.906893012 +0000 UTC m=+14063.882323853) (total time: 1.012718889s):
Trace[637673882]: [1.012651328s] [1.012477405s] Object deleted from database
I0818 17:01:04.919702       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-20-hn4cw/replicationcontrollers/density-latency-pod-39: (1.013117116s) 200 [e2e.test/v1.13.0 (linux/amd64) kubernetes/b44a768 104.198.217.95:46014]
``` 

IIUC the trace correctly, we spend almost all time in 'Object deleted from database':

https://github.com/kubernetes/kubernetes/blob/6fe7f9f4b70fce08050e8211af6dee09517baef7/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L127-L138

/sig scalability
/sig api-machinery
/cc @wojtek-t @shyamjvs

**Comment by shyamjvs** [comment] 2018-08-22 12:38
Sounds like a duplicate of https://github.com/kubernetes/kubernetes/issues/66026?

**Closed** 2018-08-22 12:46 UTC
Labels: sig/api-machinery, sig/scalability
