### ISSUE TITLE
pod status is always in ContainerCreating because unable to mount nfs volume 

### ISSUE THREAD

**Issue by AlexMioMio** [kubernetes/kubernetes#36042] opened 2016-11-02 07:52 UTC
Today,i found a issue.when i deploy my pod using nfs volume,i noticed the pod's status is always ContainerCreating. So i try to find the reason of this status. when i describe this pod, i notice a message "timeout expired waiting for volumes to attach/mount for pod config-volume-test-pod. list of unattached/unmounted volumes=[nfs]". Is it a problem？ i think if pod can't mount a volume,it should fail to be created and the cluster should notify user this failure.thanks

**Comment by AlexMioMio** [comment] 2016-11-02 08:11
@smarterclayton

**Comment by AlexMioMio** [comment] 2016-11-02 08:23
I watch kubelet.log

**Comment by AlexMioMio** [comment] 2016-11-02 08:28
I read the kubelet.log.It seems kubelet try to mount nfs every two mintues. But i recommand it should limit the times of mounting nfs.

E1102 15:48:50.633130    8082 goroutinemap.go:155] Operation for "kubernetes.io/nfs/10.120.169.106//home/share_nfs" failed. No retries permitted until 2016-11-02 15:50:50.633126241 +0800 CST (durationBeforeRetry 2m0s). error: UnmountVolume.TearDown failed for volume "kubernetes.io/nfs/10.120.169.106//home/share_nfs" (volume.spec.Name: "testvolume2") pod "359cb93f-a004-11e6-8215-fa163edf54a8" (UID: "359cb93f-a004-11e6-8215-fa163edf54a8") with: stat /var/lib/kubelet/pods/359cb93f-a004-11e6-8215-fa163edf54a8/volumes/kubernetes.io~nfs/nfs: no such file or directory
I1102 15:49:09.716848    8082 pod_workers.go:177] got pod with processes, start sync pod
I1102 15:49:09.717047    8082 runtime.go:207] Generic process runtime start to sync pod: kind:"" apiVersion:""
W1102 15:49:30.454764    8082 container_manager_linux.go:573] CPUAccounting not enabled for pid: 7948
W1102 15:49:30.454793    8082 container_manager_linux.go:576] MemoryAccounting not enabled for pid: 7948
I1102 15:49:30.454802    8082 container_manager_linux.go:284] Discovered runtime cgroups name: /system.slice/docker.service
W1102 15:49:30.454836    8082 container_manager_linux.go:573] CPUAccounting not enabled for pid: 8082
W1102 15:49:30.454843    8082 container_manager_linux.go:576] MemoryAccounting not enabled for pid: 8082
I1102 15:49:36.716523    8082 pod_workers.go:192] got non-process pod, start sync pod
I1102 15:50:21.716732    8082 pod_workers.go:177] got pod with processes, start sync pod
I1102 15:50:21.716933    8082 runtime.go:207] Generic process runtime start to sync pod: kind:"" apiVersion:""
I1102 15:50:50.643830    8082 reconciler.go:138] UnmountVolume operation started for volume "kubernetes.io/nfs/10.120.169.106//home/share_nfs" (spec.Name: "testvolume2") from pod "359cb93f-a004-11e6-8215-fa163edf54a8" (UID: "359cb93f-a004-11e6-8215-fa163edf54a8").
E1102 15:50:50.643999    8082 nfs.go:240] Error checking IsLikelyNotMountPoint: stat /var/lib/kubelet/pods/359cb93f-a004-11e6-8215-fa163edf54a8/volumes/kubernetes.io~nfs/nfs: no such file or directory

**Comment by AlexMioMio** [comment] 2016-11-03 00:49
@brendandburns

**Comment by smarterclayton** [comment] 2016-11-03 00:54
Volumes can disappear for many reasons, so we don't fail deployment, we just wait (volumes can be provisioned in the background many minutes after a pod is created).  So that part is working as designed, but the messages and output to communicate to the user should be much clearer.

@kubernetes/sig-storage re: usability of volume mounting log messages and @kargakis since your RS propagating failure causes work will eventually need to report this up.

**Comment by AlexMioMio** [comment] 2016-11-03 06:11
Just image this situation:if thousand pods try to mount volume from a nfs server,but nfs server is shutdown,then the thousand pod will be in ContainerCreating status and will not be killed.If we don't fix up nfs server,the thousand pod willn't be ready to use.That's a problem.So i suggest we should limit the time of attempts.Thx

**Comment by rootfs** [comment] 2016-11-03 13:58
@AlexMioMio see #31272

**Comment by smarterclayton** [comment] 2016-11-03 14:33
That's not what I would describe as a problem, because NFS servers can be
down for lots of reasons.  If we delete a thousand pods because of a
network flake, that makes  the system behave unpredictably.

A pod that is RestartAlways is always restarted / waits, even if the things
it needs are gone forever.

On Nov 3, 2016 , at 2:11 AM, AlexMioMio <notifications@github.com> wrote:

Just image this situation:if thousand pods try to mount volume from a nfs
server,but nfs server is shutdown,then the thousand pod will be in
ContainerCreating status and will not be killed.If we don't fix up nfs
server,the thousand pod willn't be ready to use.That's a problem.So i
suggest we should limit the time of attempts.Thx

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36042#issuecomment-258070566>,
or mute the thread

**Comment by AlexMioMio** [comment] 2016-11-04 08:56
@smarterclayton that seems to make sense

**Comment by Stono** [comment] 2016-11-08 20:42
is it not this? https://github.com/kubernetes/kubernetes/issues/33447 same issue I'm having

**Closed** 2018-02-16 14:00 UTC
Labels: lifecycle/rotten, sig/storage, team/cluster (deprecated - do not use)
