### ISSUE TITLE
[Failing Test] Conformance- OpenStack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#91757] opened 2020-06-04 07:27 UTC
**Which jobs are failing**:
> Conformance- OpenStack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)

**Which test(s) are failing**:
> - Overall
> - Test
> - [sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Conformance]

**Since when has it been failing**:
> 06-03 07:08 PDT

**Testgrid link**:
>https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Reason for failure**:
> /home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
Jun  3 15:32:47.275: We need at least two pods to be created butall nodes are already heavily utilized, so preemption tests cannot be run
/home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:159

**Anything else we need to know**:
/sig scheduling
/cc @kubernetes/ci-signal
/milestone v1.19
/priority important-soon

**Comment by hasheddan** [comment] 2020-06-04 12:50
Duplicate of https://github.com/kubernetes/kubernetes/issues/91739

/close

**Closed** 2020-06-04 12:50 UTC
Labels: kind/failing-test, priority/important-soon, sig/scheduling
