### ISSUE TITLE
Kubectl: Replace usages of swagger with open API

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#44589] opened 2017-04-17 23:50 UTC
Deprecate the discovery API returning Swagger and replace all instances with open API

**Comment by mengqiy** [comment] 2017-04-19 19:40
@mbohlool We should come up with a TODO list of replacing usages of swagger with openAPI.

**Comment by mbohlool** [comment] 2017-04-19 23:15
@mengqiy sounds great. I am not familiar with kubectl code. Can you list all usage of old swagger in kubectl here? A link to packages would be enough but a link to actual usages (or samples of usages in those packages) would be much better. We can then create a list of tasks for it.

**Comment by earth2marsh** [comment] 2017-05-01 23:24
If you need guidance on how to use the name and/or logo of the OpenAPI Specification, there's a style guide here: https://github.com/OAI/OpenAPI-Style-Guide#the-specification-name-and-usage

**Comment by mengqiy** [comment] 2017-05-04 04:41
Sorry for the delay.

The usage of old swagger:
kubectl [retrieve swagger using discovery API](https://github.com/kubernetes/kubernetes/blob/3a259d38b21881e51c8561c33f8f68ce2a3e9a88/pkg/kubectl/cmd/util/cached_discovery.go#L236).
It is implemented [here](https://github.com/kubernetes/kubernetes/blob/3a259d38b21881e51c8561c33f8f68ce2a3e9a88/pkg/kubectl/cmd/util/factory_object_mapping.go#L432).
And swagger is being used for [validation(Validator)](https://github.com/kubernetes/kubernetes/blob/3a259d38b21881e51c8561c33f8f68ce2a3e9a88/pkg/kubectl/cmd/util/factory_object_mapping.go#L405)

And there are several commands call the Validator() function to do the validation. If you need them, I will list them.

**Comment by mbohlool** [comment] 2017-05-04 18:34
Thanks. From what I read, we have two options:
1. Read openapi spec instead of swagger and convert it inline to old swagger (so no change in validation code)
2. Fix validation code to use openapi instead of swagger (prefered). You can use OpenAPI loader @pwittrock wrote.
Doing first one seems to be faster, but keep in mind, you need to cache result because it taking some time to load. I really prefer second option.

**Comment by mengqiy** [comment] 2017-05-04 18:57
I'm leaning to the second option, too.
But as discussed in https://github.com/kubernetes/kubernetes/issues/39434 the client side validation will be moved to the server-side in 1 or 2 releases. So the client-side validation code won't live long.

**Comment by mbohlool** [comment] 2017-05-04 19:04
That means we should support old swagger for 2-3 releases. How much work do you think option 2 is?

**Comment by mengqiy** [comment] 2017-05-04 19:56
> That means we should support old swagger for 2-3 releases.

That's not good. We definitely should use OpenAPI.

> How much work do you think option 2 is?

Should not be too much.

**Comment by bgrant0607** [comment] 2017-09-07 20:45
dupe of #38637?

**Comment by mbohlool** [comment] 2017-09-07 22:03
I think this is more about kubectl, @pwittrock do you agree? if that is the case the title should reflect that.

**Closed** 2017-10-04 02:27 UTC
Labels: area/kubectl, sig/cli
