### ISSUE TITLE
Kubeadm : ClusterDNS value is not changing for different service CIDR

### ISSUE THREAD

**Issue by shettyh** [kubernetes/kubernetes#69487] opened 2018-10-06 07:11 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
While initializing the the Kubernetes cluster with `Kubeadm` , provided different `--service-cidr=172.168.0.0/22`. Still kubeadm injects `ClusterDNS` in kubelet config as `10.96.0.10`, this results in wrong dns address in all the pods.

**What you expected to happen**:
`kubeadm` should inject proper DNS server address in kubelet config.

**How to reproduce it (as minimally and precisely as possible)**:
Just initialize kubernetes cluster with `kubeadm` by providing the `--service-cidr=172.168.0.0/22`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
Baremetal
- OS (e.g. from /etc/os-release):
CentOS 7.5.x
- Kernel (e.g. `uname -a`):
```
Linux shetty-k8s.novalocal 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
`kubeadm`

- Others:
I can see the code to add the proper Cluster DNS address based on the service subnet here https://github.com/kubernetes/kubernetes/blob/8a3888dcfae0c8d4b66c8f9b2a64de93f08002c2/cmd/kubeadm/app/componentconfigs/defaults.go#L77 . Not sure why it is not working

**Comment by neolit123** [comment] 2018-10-26 22:20
duplicate of https://github.com/kubernetes/kubeadm/issues/1074
/close

**Closed by neolit123** 2018-10-26 22:20 UTC
Labels: kind/bug, sig/cluster-lifecycle

**Comment by neolit123** [comment] 2018-10-30 23:41
@steven-sheehy 
ok, better open the same issue in the k/kubeadm repo so that it can be tracked by the kubeadm team.
