### ISSUE TITLE
Docker images cached indefintely (by default?)

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#3028] opened 2014-12-18 14:43 UTC
User report:
"""I had a case where I pushed an update of an image to the docker hub (that is, the name stayed the same), and the change did not seem to be picked up after I took down, and then restarted, a group of pods that used that image.

After I took down the cluster itself and restarted, it picked up the change."""

Yes, they are cached indefinitely. This is currently relegated to imagePullPolicy.

It's fine to cache the bytes indefinitely if we're verifying the cached bytes are identical to the bytes we would pull from the server (e.g. re-validate), but at least as a default, name-based indefinite caching should block v1.

**Comment by etiennetremel** [comment] 2015-01-05 13:46
Thanks @dchen1107 adding the tag :latest works!

**Comment by fgrzadkowski** [comment] 2015-03-16 14:48
Is there consensus in this issue? Do we want to check hash of binary to see if we need to load new version? Does docker allow that?

**Comment by bgrant0607** [comment] 2015-03-17 04:25
@fgrzadkowski 

The problems are:
* We use the [standard Docker client](https://github.com/fsouza/go-dockerclient) to leverage Docker's built-in image management
* Docker encourages/forces late-binding of image names+tags to layer IDs (e.g., AFAIK, [Docker's remote API](https://docs.docker.com/reference/api/docker_remote_api_v1.15/) doesn't accept image IDs for container creation) -- as opposed to deployment-time resolution #1697
* Docker keeps a shared image/layer cache across all containers

So, containers affect one another. 

Even if we added a new pull policy, and/or we pulled image IDs from the Docker registry (using a [registry client](https://github.com/CenturyLinkLabs/docker-reg-client)) to determine whether a tag had been remapped to a new image, pulling the new image would affect other containers/pods the next time they restarted.

Probably that's the easiest thing to do, though. One approach would be to pull occasionally, such as a `PullDaily` and/or `PullHourly`. Another would be to pull at least once per pod creation, say, `PullOnCreation`, so that the scenario above, where a user killed and re-created their pods, would work as expected. We could change the default behavior in v1beta3. 

IIUC, Openshift works around this by running their own registry, creating their own tags for images, and maintaining their own image metadata outside the registry.

As for the hash, how would you do that without pulling the image? I believe the new registry proposals will use content-derived IDs, though that makes some other things harder.

**Comment by wojtek-t** [comment] 2015-04-10 12:55
@vmarmol 
IIRC you were working on GC of docker images. Is that already finished? Can we close this bug?

**Comment by vmarmol** [comment] 2015-04-10 15:39
@wojtek-t yes image GC is implemented and deployed, but I think this issue deals with a different problem. The problem here is that newly deployed pods can use old images (and old pods can unexpectedly use new images on a restart).

**Comment by vmarmol** [comment] 2015-04-10 15:50
An alternative we may consider is to re-tag images on the node and default to `PullOnCreation`. This will let us handle their lifecycle and when they update more easily.

For example
- Pod A pulls image `foo/bar:1.0`
- We re-tag `foo/bar:1.0` to `A-image`
- `foo/bar:1.0` is updated
- Pod B asks for image `foo/bar:1.0`
- We re-tag `foo/bar:1.0` to `B-image`

Pod B gets the new image it expected and when either pod restarts (assuming no `PullAllways`) they get the same image they started with. With re-tagging we may make `PullIfNotPresent` useless since in theory the image is never present, we always re-tag it. I don't believe this will affect performance too much however since we do have the actual layers if they have not changed. We'd need to examine how well Docker handles this.

**Comment by dchen1107** [comment] 2015-04-10 23:09
Wait, please no re-tag an existing image, and no new pull policy here. What I really want are:

1) Using tag as package version information. For a given image name and tag information, there is only one set of images. I know this is not what docker advertised, but I think their model is wrong. Thinking about the scenario given @vmarmol above, when both Pod A and Pod B land on the same node, containers in Pod A are restarted, which image Pod A should use? What if the binary in a image changes 
command or arguments?

2) tag :latest should be forbidden for any long living services. Only test job or batch job with RestartPolicy never could use this for testing purpose. 

Now we finally changed all our infrastructure images with specific tag, and removed all :latest from our manifest. Also we are building our master components image with specific tag representing official release or git commit hash for dev. 

I know I cannot force all docker users to follow this. In today's meetup, @smarterclayton mentioned a similar idea through ImageUID. 

cc/ @bgrant0607 @thockin

**Comment by thockin** [comment] 2015-04-10 23:34
I agree with Dawn's philosophy but don't believe we can impose that on the
world.

If I understand Victor's proposal, it's basically a refcount on a given
stack of layers, right?

**Comment by vmarmol** [comment] 2015-04-10 23:47
@thockin essentially yes. It ensures that an old pod doesn't use an image it didn't expect (after create) unless it asks for further pulls. New pods will pull new images if they're available without affecting old pods.

**Comment by dchen1107** [comment] 2015-04-11 00:18
@vmarmol The problem is that PullOnCreation only works pined pod on a single node, not on a cluster. Thinking about Pod A is rescheduled to another node, which image it should be used? I might misunderstand the proposal there though.

**Comment by thockin** [comment] 2015-04-11 00:22
You're right that it would get a different version if it moves across
hosts, but I think that's far less bad and less common.  Let's be honest -
we're designing around REALLY badly behaving people - retagging an upstream
image!

**Comment by bgrant0607** [comment] 2015-04-11 04:36
Let's not make this too complicated. AIUI, the support we need to resolve at pod template creation time is coming in the next version of the registry API.

For now, let's just give guidance re. what people can do to get reasonable behavior.

**Comment by bgrant0607** [comment] 2015-04-27 22:11
Docker 1.6 supports content-addressable images. See also #1697.

**Comment by bgrant0607** [comment] 2016-05-17 23:36
This shouldn't be solved by a new pull policy. It needs to be addressed at a higher level, as in Openshift or #1697.

**Closed by bgrant0607** 2016-05-17 23:36 UTC
Labels: area/usability, priority/P2, team/node
