### ISSUE TITLE
Flaky e2e: [Performance] should allow starting 30 pods per node

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#18608] opened 2015-12-11 23:48 UTC
Failed in the last 2 runs with
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:149 There should be no high-latency requests Expected : 1 not to be > : 0
```

Most recent run results: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3388/consoleFull

cc @gmarek, @fgrzadkowski

**Comment by jlowdermilk** [comment] 2015-12-12 01:09
Passing now, with no build change, so perhaps just flaky.

**Comment by wojtek-t** [comment] 2015-12-12 09:46
I guess the limit is a bit too strict now - I will relax it a bit.

**Comment by gmarek** [comment] 2015-12-12 11:40
I'm not certain it's the change shortening the threshold for listing pods. E.g. in http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3399 we failed on post pods, not listing them.

**Comment by gmarek** [comment] 2015-12-12 11:57
Only other nontrivial change I was able to find that got merged around the time test became flaky is #18383

**Comment by wojtek-t** [comment] 2015-12-14 07:29
I'm pretty sure this wasn't a regression - those were flakes (including those high times on posting pods).

Some better tracing has finally been merged on Thursday or Friday, so I'm planning to look into those this week.
Also - I would like to upgrade to 1.5.1 within days, as this may be the reason of those flakes too...

**Comment by fgrzadkowski** [comment] 2015-12-14 08:09
This happened again. Regression or not, this is happening really often! In the last 15 runs we had 6 yellow runs.

**Comment by wojtek-t** [comment] 2015-12-14 10:15
I took a closer look into it.

1. I increased the limit for Listing pods - it was too strict after my changes from Friday.

2. However, there were also a bunch of failures on too high latency of posting pods. I looked deeper into logs and there seem to be some bursts of longer requests with no good reason (e.g. there aren't more api calls at that time).
Looking at traces, I have 2 hypothesis:
  - either etcd is getting slow for some reason (but only for some relatively short period - like 0.5s)
  - or there is some "stop-the-world" - which may be caused by golang GC
[Note that this is pretty similar to https://github.com/kubernetes/kubernetes/issues/14552]

I think that what we should do now is:
- #18367 has already been merged
- we should __really prioritize__ upgrading to Go 1.5 asap (hopefully we will be able to do it this week)

However, if big flakiness-ration will persist, we should probably temporarily increase the limits in the test.

**Comment by wojtek-t** [comment] 2015-12-14 19:43
I guess we need to increase the limits to unblock merge-queue.
I'm increasing priority to P0 - will do it as a first thing tomorrow.

**Comment by saad-ali** [comment] 2015-12-14 19:52
Thank you for looking into this @wojtek-t and raising the priority to P0.

This issue is making the scalability E2E suite very unstable and blocking the merge queue.
Recent failures:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3440/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3439/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3433/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3428/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3437/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3426/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3424/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3422/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3419/

**Comment by wojtek-t** [comment] 2015-12-15 10:06
I temporary relaxed the limits in scalability tests. This should solve the flakiness issues.

**Comment by wojtek-t** [comment] 2015-12-16 16:59
Tests are stable now. Closing this issue.

**Closed by wojtek-t** 2015-12-16 16:59 UTC
Labels: area/performance, kind/flake, priority/P0, team/control-plane
