### ISSUE TITLE
Vagrant setup broken on master branch

### ISSUE THREAD

**Issue by apeeyush** [kubernetes/kubernetes#15692] opened 2015-10-15 06:13 UTC
I am trying to setup vagrant using the master branch but get the following error:

	==> minion-1: Installed:
	==> minion-1:   flannel.x86_64 0:0.5.0-3.fc21                                                 
	==> minion-1: Complete!
	==> minion-1: Created symlink from /etc/systemd/system/docker.service.requires/flanneld.service to /usr/lib/systemd/system/flanneld.service.
	==> minion-1: Job for flanneld.service failed. See "systemctl status flanneld.service" and "journalctl -xe" for details.
	The SSH command responded with a non-zero exit status. Vagrant
	assumes that this means the command failed. The output for this command
	should be in the log above. Please read the output to determine what
	went wrong.

However, the setup works completely fine when I use a stable version of Kubernetes. I want to make changes in the code and being able to make changes in the master branch and testing it directly will be really useful. Could someone help me figure out what the issue might be?

System Details are

     Ubuntu 14.04
     Vagrant 1.7.4
     VirtualBox 4.3.28r100309

**Comment by apeeyush** [comment] 2015-10-15 07:00
I suspect that it might be related to #15545

**Comment by apeeyush** [comment] 2015-10-15 22:18
On exploring further, it appears that the setup is working fine when networking is done using OVS instead of flannel.

Also, on the master branch, after the setup fails:
1. On ssh to the master node, `systemctl status etcd` shows that etcd terminates after some time of starting. However, flannel is still running.
2. On ssh to the minion-1 node, `systemctl status flannels` shows that it fails to start because of connection problems with etcd.

Could someone help me understand what might be going wrong and how to fix it?

**Comment by kargakis** [comment] 2015-10-19 11:59
I am hitting the same issue and I need to work on the latest master...

> On exploring further, it appears that the setup is working fine when networking is done using OVS instead of flannel.

@apeeyush can you guide me on how did you set this up? Thanks!

**Comment by apeeyush** [comment] 2015-10-20 05:12
@kargakis I made some changes today and even the flannel based vagrant setup seems to be working fine now!

Can you try rebuilding your kubernetes using

    ./build/release.sh

And then, setup the cluster using

    export KUBERNETES_PROVIDER=vagrant
    cluster/kube-up.sh

Please report your results here (whether it works or not). I am not sure if the error was because I had forgotten to rebuild the kubernetes..

**Comment by davidopp** [comment] 2015-10-28 23:31
@derekwaynecarr

**Comment by derekwaynecarr** [comment] 2015-10-28 23:51
This should all work fine from the master branch

$ make quick-release 
$ export KUBERNETES_PROVIDER=vagrant
$ cluster/kube-up.sh

I had run this from master yesterday without issue, but can verify again tomorrow.  Vagrant uses flannel and fedora, OVS got dropped awhile back.

I suspect your problems are related to your inability to build a release so please confirm the output of the above.

**Comment by apeeyush** [comment] 2015-10-29 07:13
I forgot to update the status here! I was able to setup the vagrant on master branch after doing a `make clean`.

However, it is not mentioned anywhere in the docs that it might be required. I guess we should document it or improve the Makefile to detect it.

Also, `make quick-release` works fine for me but `make release` seems to fail during the testing phase. I can try that again today and post the error if required.

**Comment by kargakis** [comment] 2015-11-08 14:27
@derekwaynecarr I remember I could run quick-release w/o a problem.

I updated both vagrant and virtualbox since to 1.7.4 and 5.0.8 respectively and can run on latest master w/o any problem.

**Comment by levackt** [comment] 2015-11-09 10:48
@kargakis confirmed, thanks

**Comment by derekwaynecarr** [comment] 2015-11-10 22:50
closing issue based on acks from others.

**Closed by derekwaynecarr** 2015-11-10 22:50 UTC
Labels: area/install, area/platform/vagrant, team/none
