### ISSUE TITLE
Add minor version skew warning to kubectl

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#20588] opened 2016-02-03 21:31 UTC
We should really find a way warn if you hit a newer server from a much older client.

c.f. #20587

cc @brendandburns

**Comment by bgrant0607** [comment] 2016-02-16 23:54
@zmerlynn Why isn't this a dupe of #20587?

**Comment by bgrant0607** [comment] 2016-02-16 23:54
This is a dupe of #18866

**Closed by bgrant0607** 2016-02-16 23:54 UTC
Labels: component/kubectl, help-wanted, priority/P2, team/ux
