### ISSUE TITLE
CRI: garbage collection may remove just-created sandbox

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#33984] opened 2016-10-04 01:10 UTC
Currently, kuberuntime removes a sandbox only when there are no containers belonging to it. But this introduces a potential problem of removing just-created sandbox, which means a sandbox may be removed if:

- It has been created and hasn't become ready yet (which means `RunPodSandbox` has been requested and has no response, but the sandbox is already shown in `ListPodSandbox`)
- garbage collection is run exactly at this time.

The quick fix is adding age policy to sandbox, e.g. only remove a sandbox if it is older than X. But it doesn't really guarantee this won't happen theoretically (e.g.`RunPodSandbox` takes much longer than gc age).

Maybe full gc policy should also be applied to sandboxes. @yujuhong @Random-Liu @yifan-gu  What do you think?

cc/ @kubernetes/sig-node

**Comment by Random-Liu** [comment] 2016-10-04 01:26
Remove older than X will cause 2 problems:
1) If RunPodSandbox is too slow, this could still happen.
2) If RunPodSandbox is too fast (crashloop), this may leave a lot of garbage.

**Comment by yifan-gu** [comment] 2016-10-04 02:01
Wonder if we can solve this by not killing the sandbox when it's just created.

Apparently, these two cases are different:
- 1, No containers have ever launched yet.
- 2, Containers have all exited.

Although there is a chance that exited containers are gc'd, so we can't tell (2) from (1), but the chances is very low, so we could ignore IMO.

I will try to take this into account in my refactoring work.

**Comment by yujuhong** [comment] 2016-10-04 15:38
> Although there is a chance that exited containers are gc'd, so we can't tell (2) from (1), but the chances is very low, so we could ignore IMO.

The current sandbox GC behavior is that we'll remove a sandbox if none of the containers are currently associated with it. I am afraid that if removing sandbox depends on the containers, the logic will grown even more complex.

One fundamental problem is that we can't tell if a sandbox is "created" or "exited". What If we add a new "created" state in the api, the garbage collector can avoid removing "created" sandboxes? Would this solve the problem? The runtime doesn't have to use the "created" state if that doesn't apply to the sandbox.

As for having multiple "created" sandbox per pod in some special cases (e.g., not being able to start the sandbox), we can always leave at maximum one "created" sandbox per pod until a pod is terminated or deleted.

Thoughts?

**Comment by yifan-gu** [comment] 2016-10-04 19:10
@yujuhong But even the sandbox has 0 containers, it will be in the state of `Ready` until it's been stopped, right?
What I was saying is we don't stop the sandbox until we really needs to, e.g. when the pod should be killed, but not when there is no containers running.

**Comment by yujuhong** [comment] 2016-10-04 19:15
> @yujuhong But even the sandbox has 0 containers, it will be in the state of Ready until it's been stopped, right?

Yes, but the sandbox will only be removed if it was stopped ("exited", not "created"). This will change the current "ready", "not ready" states that the sandbox has.

> What I was saying is we don't stop the sandbox until we really needs to, e.g. when the pod should be killed, but not when there is no containers running.

I remember we had a similar discussion last time and you rejected the idea of keeping the sandbox running since it'd be a waste of resource ;)

**Comment by yifan-gu** [comment] 2016-10-04 19:25
> I remember we had a similar discussion last time and you rejected the idea of keeping the sandbox running since it'd be a waste of resource ;)

@yujuhong It's different. As I said above, there are two cases a pod sandbox will have 0 containers:
- No containers have been started yet.
- All containers are exited.

Obviously, when no containers are started, the sandbox should not be stopped.
When all containers are exited, it depends whether those containers will restart or not.

Two states for sandbox are enough, and we need to fix the syncpod so that it doesn't kill the sandbox when it shouldn't.

**Comment by Random-Liu** [comment] 2016-10-04 20:23
> As for having multiple "created" sandbox per pod in some special cases (e.g., not being able to start the sandbox), we can always leave at maximum one "created" sandbox per pod until a pod is terminated or deleted.

If so, we don't we just extend the current logic?
If a sandbox 1) has containers in it or 2) is the latest sandbox for an existing pod, we keep it.

**Comment by yifan-gu** [comment] 2016-10-04 20:44
@Random-Liu It's a choice whether you put the logic in gc or in sync pod.
What I am proposing is GC does dumb job, just clean up what is marked as stopped.
And kubelet be more careful about stopping a sandbox.

**Comment by yujuhong** [comment] 2016-10-05 18:27
> And kubelet be more careful about stopping a sandbox.

The problem is not only about when to stop a sandbox though. For docker, the sandbox container goes through the state of created (not ready) -> running (ready). 

> Although there is a chance that exited containers are gc'd, so we can't tell (2) from (1), but the chances is very low, so we could ignore IMO.

The current GC logic cleans up all exited containers before attempting to remove sandboxes. It'd be hard to tell (1) from (2) if you don't change the dumb GC logic, and I actually like the dumbness of the logic :-|

**Closed** 2016-10-09 00:07 UTC
Labels: area/kubelet-api, component/kubelet, team/node
