### ISSUE TITLE
[Flaking Test]  [sig-network] Services should complete a service status lifecycle [Conformance]

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123853] opened 2024-03-11 03:45 UTC
### Which jobs are flaking?

- https://storage.googleapis.com/k8s-triage/index.html?test=Services%20should%20complete%20a%20service%20status%20lifecycle
![image](https://github.com/kubernetes/kubernetes/assets/2010320/06ec09a0-26aa-467f-83a1-698578075fa2)

### Which tests are flaking?

Kubernetes e2e suite [It] [sig-network] Services should complete a service status lifecycle [Conformance]

### Since when has it been flaking?

Since 3/6

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel
https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest

### Reason for failure (if possible)

```
[FAILED] failed to locate Service test-service-vmjll in namespace services-4066: timed out waiting for the condition
In [It] at: k8s.io/kubernetes/test/e2e/network/service.go:3497 @ 03/06/24 17:28:50.618
```

### Anything else we need to know?

added in v1.21 @Riaankl https://github.com/kubernetes/kubernetes/pull/100290

### Relevant SIG(s)

/sig network

**Comment by pacoxu** [comment] 2024-03-11 03:46
https://github.com/kubernetes/kubernetes/pull/122541 is the only PR that was merged in 2024-03-06. @aojea. 
- But I am not sure if it is related.

**Comment by Vyom-Yadav** [comment] 2024-03-11 08:39
Adding an urgent label to be on the safer side as we are cutting a beta release tomorrow:
/priority critical-urgent

**Comment by aojea** [comment] 2024-03-11 13:42
/assign @aojea 

let me check

**Comment by aojea** [comment] 2024-03-11 23:00
checking https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1766011295003316224

> STEP: watching for the Service to be updated - k8s.io/kubernetes/test/e2e/network/service.go:3470 @ 03/08/24 08:19:25.053
> I0308 08:19:25.056112 67239 service.go:3479] Observed Service test-service-rtm92 in namespace services-2313 with annotations: map[] & Conditions: {[]}
> I0308 08:19:25.056307 67239 service.go:3494] Observed event: &Service{ObjectMeta:{test-service-rtm92  services-2313  9c495a49-6a1f-4497-a4a6-22aac385c704 15246 0 2024-03-08 08:19:24 +0000 UTC <nil> <nil> map[test-service-static:true] map[patchedstatus:true] [] [] [{e2e.test Update v1 2024-03-08 08:19:24 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:test-service-static":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:loadBalancerClass":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:sessionAffinity":{},"f:type":{}}} } {e2e.test Update v1 2024-03-08 08:19:24 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:patchedstatus":{}}},"f:status":{"f:loadBalancer":{"f:ingress":{}}}} status}]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:http,Protocol:TCP,Port:80,TargetPort:{0 80 },NodePort:30127,AppProtocol:nil,},},Selector:map[string]string{},ClusterIP:fd00:10:96::e544,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[fd00:10:96::e544],IPFamilies:[IPv6],AllocateLoadBalancerNodePorts:*true,LoadBalancerClass:*example.com/internal-vip,InternalTrafficPolicy:*Cluster,TrafficDistribution:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{LoadBalancerIngress{IP:203.0.113.1,Hostname:,IPMode:*VIP,Ports:[]PortStatus{},},},},Conditions:[]Condition{},},}
> I0308 08:20:25.054122 67239 service.go:3497] Unexpected error: failed to locate Service test-service-rtm92 in namespace services-2313: 
>     <wait.errInterrupted>: 
>     timed out waiting for the condition
>     {
>         cause: <*errors.errorString | 0xc00056a6e0>{
>             s: "timed out waiting for the condition",
>         },
>     }
> [FAILED] failed to locate Service test-service-rtm92 in namespace services-2313: timed out waiting for the condition
> In [It] at: k8s.io/kubernetes/test/e2e/network/service.go:3497 @ 03/08/24 08:20:25.054


loop starts at 08:19:25.053 and waits for an event with the status of the Service updated with the condition set, times out one minute later at  08:20:25.054

but the test it says a new condition is added at

> I0308 08:19:25.053548 67239 service.go:3468] updatedStatus.Conditions: []v1.Condition{v1.Condition{Type:"StatusUpdate", Status:"True", ObservedGeneration:0, LastTransitionTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Reason:"E2E", Message:"Set from e2e test"}}

It starts a watch later 

> 2024-03-08T08:19:25.055483737Z stderr F I0308 08:19:25.055330       1 get.go:261] "Starting watch" path="/api/v1/namespaces/services-2313/services" resourceVersion="15212" labels="test-service-static=true" fields="" timeout="40m12.362813706s"


The event received does not have a Condition set

> ,Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{LoadBalancerIngress{IP:203.0.113.1,Hostname:,IPMode:*VIP,Ports:[]PortStatus{},},},},Conditions:[]Condition{},},}

I think the problem is we are not seeing the second event

https://github.com/kubernetes/kubernetes/blob/3ec6a387955b1240ad6d795663513f1ee12ceaec/test/e2e/network/service.go#L3473-L3496

the apiserver logs shows  a PATCH and PUT operation
```
2024-03-08T08:19:24.966489552Z stderr F I0308 08:19:24.966259       1 httplog.go:132] "HTTP" verb="GET" URI="/api/v1/namespaces/services-2313/services/test-service-rtm92/status" latency="17.163375ms" userAgent="e2e.test/v1.30.0 (linux/amd64) kubernetes/7ea3d02 -- [sig-network] Services should complete a service status lifecycle [Conformance]" audit-ID="e5db8866-d769-466a-8b20-9b18bc24b922" srcIP="[fc00:f853:ccd:e793::1]:57422" apf_pl="global-default" apf_fs="global-default" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="13.250677ms" resp=200
2024-03-08T08:19:25.00190924Z stderr F I0308 08:19:24.999907       1 httplog.go:132] "HTTP" verb="PATCH" URI="/api/v1/namespaces/services-2313/services/test-service-rtm92/status" latency="30.061868ms" userAgent="e2e.test/v1.30.0 (linux/amd64) kubernetes/7ea3d02 -- [sig-network] Services should complete a service status lifecycle [Conformance]" audit-ID="a185ba1b-f701-4e30-b2a0-acca54282e88" srcIP="[fc00:f853:ccd:e793::1]:57422" apf_pl="global-default" apf_fs="global-default" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="29.561367ms" resp=200
2024-03-08T08:19:25.052661235Z stderr F I0308 08:19:25.051383       1 httplog.go:132] "HTTP" verb="PUT" URI="/api/v1/namespaces/services-2313/services/test-service-rtm92/status" latency="32.112086ms" userAgent="e2e.test/v1.30.0 (linux/amd64) kubernetes/7ea3d02 -- [sig-network] Services should complete a service status lifecycle [Conformance]" audit-ID="5efa7e80-f20c-410b-8c34-883161c1c2c0" srcIP="[fc00:f853:ccd:e793::1]:57422" apf_pl="global-default" apf_fs="global-default" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="31.723138ms" resp=200
```

indeed it seems the test started to flake after https://github.com/kubernetes/kubernetes/pull/122541 

@liggitt @serathius @wojtek-t can be the field selector that causes the flake? other theory about the watches?

**Comment by pacoxu** [comment] 2024-03-12 02:21
@carlory tried to reproduce it locally and it will flake after continuing running it ~10 minutes.

If field selector can cause the flake, it may happen to other resources as well.

**Comment by carlory** [comment] 2024-03-12 05:54
> it may happen to other resources as well.

When I do same test on Secret resource, I cannot observe the similar flaking issue. The testing time is up to 1 hour.

**Comment by carlory** [comment] 2024-03-12 06:01
After I revert #122541, I cannot observe the flakes anymore within 20 minutes and then I cancel the runnning. 

But when I run with master branch, I can observe the flakes within 5 minutes. 

```
Summarizing 1 Failure:
  [FAIL] [sig-network] Services [It] should complete a service status lifecycle [Conformance] [sig-network, Conformance]
  /Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/network/service.go:3447

Ran 1 of 7458 Specs in 60.221 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 7457 Skipped
--- FAIL: TestE2E (60.32s)
FAIL
You're using deprecated Ginkgo functionality:
=============================================
  --ginkgo.slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.15.0


Tests failed on attempt #318


Ginkgo ran 1 suite in 4m39.453940917s

Test Suite Failed
```

It is so weird. I cannot understand why the flaking test does not appear with the Secret resource.

**Comment by carlory** [comment] 2024-03-12 06:03
How to reproduce the error, please follow the steps below:

On terminal 1:
```bash
sudo ./hack/local-up-cluster.sh
```

On terminal 2:
```bash
ginkgo  --focus "Services should complete a service status lifecycle" --until-it-fails -v test/e2e -- --num-nodes=0 --allowed-not-ready-nodes=-1
```

Wait for the error to occur. It should occur within 5 ~ 10 minutes.

**Comment by carlory** [comment] 2024-03-12 09:35
@aojea Sure, let me reproduce it again.

**Comment by aojea** [comment] 2024-03-12 10:00
get some verbosity on the apiserver , at least v4

**Comment by carlory** [comment] 2024-03-12 10:02
@aojea I have send it to you via slack, verbosity is 6

**Comment by Vyom-Yadav** [comment] 2024-03-12 10:06
@aojea @carlory This looks like a blocker for `v1.30.0-beta.0` release cut? wdyt?

**Comment by carlory** [comment] 2024-03-12 10:08
I think it is a blocker for v1.30.0 but not sure for v1.30.0-beta.0 cc @pacoxu 
I cannot reproduce it with v1.29.x

**Comment by aojea** [comment] 2024-03-12 17:33
It should be fixed by https://github.com/kubernetes/kubernetes/pull/123896 now

/close

**Closed by aojea** 2024-03-12 17:33 UTC
Labels: priority/critical-urgent, sig/network, kind/flake, needs-triage
