### ISSUE TITLE
missing  sentinel.py in redis image creation

### ISSUE THREAD

**Issue by rasekar2000** [kubernetes/kubernetes#19039] opened 2015-12-23 01:22 UTC
Hello Team,

https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/redis/image/Dockerfile#L8

COPY sentinel.py /sentinel.py file is missing in this latest version. 

Thanks and Regards,
Raj

**Comment by rasekar2000** [comment] 2015-12-23 18:29
import json
import sys

data = json.load(sys.stdin)

if data and "endpoints" in data and len(data["endpoints"]) > 0:
  host = data["endpoints"][0].split(":")[0]
else:
  host = "localhost"

print "sentinel monitor mymaster %s 6379 2" % host
print "sentinel down-after-milliseconds mymaster 60000"
print "sentinel failover-timeout mymaster 180000"
print "sentinel parallel-syncs mymaster 1"

--> Taken from after getting inside the docker running image

Regards,
Raj

**Comment by bgrant0607** [comment] 2016-01-29 00:23
cc @brendandburns

**Comment by bgrant0607** [comment] 2016-01-29 00:24
It doesn't look like sentinel.py was in the original PR.

**Comment by bgrant0607** [comment] 2016-02-05 21:30
Dupe of #17938, and also fixed.

**Closed by bgrant0607** 2016-02-05 21:30 UTC
Labels: help-wanted, kind/bug, kind/documentation, kind/example, priority/P2, team/ux
