### ISSUE TITLE
Incoming UDP packets not reach newly deployed services

### ISSUE THREAD

**Issue by dachulin** [kubernetes/kubernetes#31983] opened 2016-09-02 16:16 UTC
Hi,

We have a device (router in this case) that sends long living stream of udp packets to our kubernetes cluster. We then create a service and pods that expose a node port to receive the incoming udp packets. However, packets were not reach our containers.

Further digging and found that because UDP packets already stream into our host (therefore conntrack entry already created) BEFORE our service is created (iptable rules added), the iptable rule didn't take effect. Since our UDP stream is long living, the conntrack entry never get timeout neither.

To workaround the issue, we have to stop the UDP stream for sometime after the service is created so that the conntrack entry times out. If we use "conntrack -D" to clear all entries after service is deployed also workaround the issue. 

Though it is the behavior of the linux iptable that new rules doesn't affect already existing connection, we are trying to see if kubernetes proxy have any config that can clear the related conntrack entries when a new service is deployed?

**Comment by zreigz** [comment] 2016-09-12 08:35
I am interested in your problem. Can you give some more details how did you add iptables rules before service started. Did you use the PREROUTING chain to forward port to pod ?

**Comment by zreigz** [comment] 2016-09-12 09:46
OK I was able to reproduce the problem

**Comment by zreigz** [comment] 2016-09-12 11:19
I think the issue is more problematic and complex. It is explained here: https://github.com/docker/docker/issues/8795

**Comment by dachulin** [comment] 2016-09-12 17:29
Yes I think it is the same conntrack issue as in the one reported in docker issue. But I also think that the kubernetes might have a better control over it, since it knows the service up/down. I think k8s already deleting the conntrack entries when removing services. Just wondering if the same can apply to adding services?

**Comment by zreigz** [comment] 2016-09-13 05:11
Yes you are right. Kubernetes as a Docker manager should take care of this. Deleting the conntrack entries is done in very simple way: https://github.com/kubernetes/kubernetes/blob/65f3fa9caf79a5cae49ff893695c58ca63863ad1/pkg/proxy/iptables/proxier.go#L719
Just call the application `conntrack -D ...`

I will try to make Pull Request to solve the issue and then we will see if community like it.

**Comment by zreigz** [comment] 2016-09-13 06:23
But there is another problem because I removed conntrack entries `sudo conntrack -D ` and then I created service and still have problem. I have to restart my UDP sender. I use hyperkube for my k8s cluster.

**Comment by zreigz** [comment] 2016-09-13 08:36
In code it looks much better. I assume you used `nodePort` for your service to use some particular port.
The fix is in place when node port is binded. When I create PR I will let you know

**Comment by zreigz** [comment] 2016-09-13 09:07
The PR created: https://github.com/kubernetes/kubernetes/pull/32561

@dachulin If you want verify it you can easily do it using local cluster

```
$ git clone https://github.com/zreigz/kubernetes.git
$ cd kubernetes
$ git checkout fix-incoming-udp
$ make quick-release
$ cd cluster/images/hyperkube/
$ make build VERSION=v1.10.0
```
Then clone kube-deploy project to create local k8s cluster with image you already created with fixes

```
$ git clone https://github.com/kubernetes/kube-deploy.git
$ cd kube-deploy/docker-multinode
$ sudo env "PATH=$PATH" K8S_VERSION=v1.10.0 IP_ADDRESS=${HOST IP ADDRESS} ./master.sh
```

**Comment by dachulin** [comment] 2016-09-13 17:02
@zreigz 
Thanks for the fix. This is what we did manually to workaround so it should be good enough for us. It would be even better if you can clear the conntrack entry only for the affected entry, such as destination port, to minimizes the impact. Wondering if that possible?

**Comment by zreigz** [comment] 2016-09-14 05:19
I wanted do it like you mentioned but unfortunately conntract command doesn't give that possibilities. In parameters you can only pass the source and destination IP addresses.

**Comment by dachulin** [comment] 2016-10-28 15:55
Sorry didn't get back for a while.

I tried the conntrack tool and seems like you can use --dport option:

conntrack -D -s 172.27.209.165 -p udp --dport 53
udp      17 63 src=172.27.209.165 dst=171.70.168.183 sport=38061 dport=53 src=171.70.168.183 dst=172.27.209.165 sport=53 dport=38061 [ASSURED] mark=0 use=1
udp      17 33 src=172.27.209.165 dst=171.70.168.183 sport=45906 dport=53 src=171.70.168.183 dst=172.27.209.165 sport=53 dport=45906 [ASSURED] mark=0 use=1
conntrack v1.4.3 (conntrack-tools): 2 flow entries have been deleted.

**Comment by zreigz** [comment] 2016-11-03 07:45
Thanks for info I will try it

**Comment by zreigz** [comment] 2016-11-03 11:40
I've updated my PR for flag `--dport` It works well

**Comment by thockin** [comment] 2016-11-21 05:38
It's not clear to me why there would be a conntrack rule for your service port before we add any rules?

**Comment by dachulin** [comment] 2016-11-29 22:28
We have a router, which configured to export statistics using UDP to our host. That UDP stream is long live. If our host restarted, or we re-deploy our cluster (mainly during development), then udp packets received by host before K8S is provisioned.

**Comment by thockin** [comment] 2016-11-30 00:35
But why do you have conntrack rules - simply receiving packets will not
cause conntrack to create records..

**Closed** 2016-12-02 00:02 UTC
Labels: component/kube-proxy, team/cluster
