### ISSUE TITLE
invalid memory address or nil pointer dereference" in wait.JitterUntil

### ISSUE THREAD

**Issue by bizy01** [kubernetes/kubernetes#125680] opened 2024-06-24 21:57 UTC
### What happened?

![event-panic](https://github.com/kubernetes/kubernetes/assets/76192004/3ed97110-e8ad-4b8b-9a64-0ce1cd0ff4fa)

### What did you expect to happen?

no panic 

### How can we reproduce it (as minimally and precisely as possible)?

func (e *EventWatcher) OnAdd(obj interface{}) {
	defer recoverPanic("addEvent")

	event := obj.(*corev1.Event)
	e.watchEvent(event)
}

func (e *EventWatcher) OnUpdate(oldObj, newObj interface{}) {
	defer recoverPanic("updateEvent")
	event := newObj.(*corev1.Event)
	e.watchEvent(event)
}

func (e *EventWatcher) OnDelete(obj interface{}) {
	// nil
}

### Kubernetes version

<details>

```console
k8s version 1.19.5
k8s.io/client-go v0.22.6
```

</details>

**Comment by xyz-li** [comment] 2024-06-25 03:41
Could you provide more code?

**Comment by neolit123** [comment] 2024-06-25 10:29
yes, this could be just your code causing the panic.

/sig api-machinery

**Comment by mauri870** [comment] 2024-06-26 12:38
I guess the panic is happening here `event := newObj.(*corev1.Event)`? In that case seems to be a problem with your code, you need a full type assertion (`event, ok`).

Without a more complete reproducer it is hard to investigate this further.

Please post code snippets and stacktraces as text whenever possible, images cannot be copied or searched upon. Thanks!

**Comment by bizy01** [comment] 2024-06-27 02:58
![image](https://github.com/kubernetes/kubernetes/assets/76192004/a2a56eaf-e451-4977-b978-370bc49bec27)

That's what it looks like. I'll add an assertion

**Comment by BenTheElder** [comment] 2024-07-02 23:27
0.22.6 means kubernetes v1.22.6 which is long out of support: https://kubernetes.io/releases/ (1.27+ are currently supported, soon to be 1.28+ any day now)

+1 to the comment about please paste as text, it's hard to work with screenshots of text.

If this cannot be reproduced with a current release, we should close it.

**Comment by cici37** [comment] 2024-07-11 20:21
/close
Please feel free to reopen the issue if needed. Thanks :)

**Closed by cici37** 2024-07-11 20:21 UTC
Labels: kind/bug, sig/api-machinery, needs-triage

**Comment by yuan6711043** [comment] 2024-08-20 09:01
2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:71 +0x85
-- | --
  |   | 2024-08-17 20:57:06 | created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:73 +0x5a
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:771 +0x6b
  |   | 2024-08-17 20:57:06 | k8s.io/client-go/tools/cache.(*processorListener).run(0xc00058cb00?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.Until(...)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x20?, 0xc000612788?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000612738?, {0x1a9fc60, 0xc000324b40}, 0x1, 0xc00440e6c0)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x3e
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006126d8?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:778 +0xde
  |   | 2024-08-17 20:57:06 | k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  |   | 2024-08-17 20:57:06 | /usr/local/go/src/runtime/panic.go:838 +0x207
  |   | 2024-08-17 20:57:06 | panic({0x164d980, 0x2639880})
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:55 +0xd8
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000703860?})
  |   | 2024-08-17 20:57:06 | goroutine 69 [running]:
  |   | 2024-08-17 20:57:06 |  
  |   | 2024-08-17 20:57:06 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12f601e]
  |   | 2024-08-17 20:57:06 | panic: runtime error: invalid memory address or nil pointer dereference
  |   | 2024-08-17 20:57:06 | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:71 +0x85
  |   | 2024-08-17 20:57:06 | created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:73 +0x5a
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:771 +0x6b
  |   | 2024-08-17 20:57:06 | k8s.io/client-go/tools/cache.(*processorListener).run(0xc00058cb00?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.Until(...)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x20?, 0xc000612788?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000612738?, {0x1a9fc60, 0xc000324b40}, 0x1, 0xc00440e6c0)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x3e
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006126d8?)
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:778 +0xde
  |   | 2024-08-17 20:57:06 | k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  |   | 2024-08-17 20:57:06 | /usr/local/go/src/runtime/panic.go:838 +0x207
  |   | 2024-08-17 20:57:06 | panic({0x164d980, 0x2639880})
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:48 +0x75
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000703860?})
  |   | 2024-08-17 20:57:06 | /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:74 +0x99
  |   | 2024-08-17 20:57:06 | k8s.io/apimachinery/pkg/util/runtime.logPanic({0x164d980?, 0x2639880})
  |   | 2024-08-17 20:57:06 | goroutine 69 [running]:
  |   | 2024-08-17 20:57:06 | E0817 20:57:06.533920       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

**Comment by yuan6711043** [comment] 2024-08-20 09:14
2024-08-17T20:54:05.360385251+08:00 stderr F E0817 20:54:05.360227       1 shared_informer.go:781] unrecognized notification: <nil>
2024-08-17T20:57:06.542943565+08:00 stderr F E0817 20:57:06.533920       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2024-08-17T20:57:06.542975362+08:00 stderr F goroutine 69 [running]:
2024-08-17T20:57:06.54297969+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic({0x164d980?, 0x2639880})
2024-08-17T20:57:06.542982486+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:74 +0x99
2024-08-17T20:57:06.542984865+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000703860?})
2024-08-17T20:57:06.542987631+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:48 +0x75
2024-08-17T20:57:06.54299063+08:00 stderr F panic({0x164d980, 0x2639880})
2024-08-17T20:57:06.542993879+08:00 stderr F    /usr/local/go/src/runtime/panic.go:838 +0x207
2024-08-17T20:57:06.543005615+08:00 stderr F k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2024-08-17T20:57:06.543008424+08:00 stderr F    /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:778 +0xde
2024-08-17T20:57:06.543011057+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006126d8?)
2024-08-17T20:57:06.543013726+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x3e
2024-08-17T20:57:06.543017342+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000612738?, {0x1a9fc60, 0xc000324b40}, 0x1, 0xc00440e6c0)
2024-08-17T20:57:06.543020008+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
2024-08-17T20:57:06.543022848+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x20?, 0xc000612788?)
2024-08-17T20:57:06.543028202+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
2024-08-17T20:57:06.543030587+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.Until(...)
2024-08-17T20:57:06.543032706+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90
2024-08-17T20:57:06.543035316+08:00 stderr F k8s.io/client-go/tools/cache.(*processorListener).run(0xc00058cb00?)
2024-08-17T20:57:06.543037871+08:00 stderr F    /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:771 +0x6b
2024-08-17T20:57:06.543040241+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2024-08-17T20:57:06.543042877+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:73 +0x5a
2024-08-17T20:57:06.543045322+08:00 stderr F created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2024-08-17T20:57:06.543047478+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:71 +0x85
2024-08-17T20:57:06.550945456+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-08-17T20:57:06.550964626+08:00 stderr F    panic: runtime error: invalid memory address or nil pointer dereference
2024-08-17T20:57:06.550968077+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12f601e]
2024-08-17T20:57:06.55097015+08:00 stderr F
2024-08-17T20:57:06.55097301+08:00 stderr F goroutine 69 [running]:
2024-08-17T20:57:06.550975228+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000703860?})
2024-08-17T20:57:06.550980797+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:55 +0xd8
2024-08-17T20:57:06.550990388+08:00 stderr F panic({0x164d980, 0x2639880})
2024-08-17T20:57:06.550992911+08:00 stderr F    /usr/local/go/src/runtime/panic.go:838 +0x207
2024-08-17T20:57:06.550995443+08:00 stderr F k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2024-08-17T20:57:06.5509978+08:00 stderr F      /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:778 +0xde
2024-08-17T20:57:06.551000145+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006126d8?)
2024-08-17T20:57:06.551002972+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x3e
2024-08-17T20:57:06.551005785+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000612738?, {0x1a9fc60, 0xc000324b40}, 0x1, 0xc00440e6c0)
2024-08-17T20:57:06.551007866+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
2024-08-17T20:57:06.551009975+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x20?, 0xc000612788?)
2024-08-17T20:57:06.551012193+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
2024-08-17T20:57:06.551014496+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.Until(...)
2024-08-17T20:57:06.551033914+08:00 stderr F    /go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90
2024-08-17T20:57:06.5510365+08:00 stderr F k8s.io/client-go/tools/cache.(*processorListener).run(0xc00058cb00?)
2024-08-17T20:57:06.551054297+08:00 stderr F    /go/pkg/mod/k8s.io/client-go@v0.22.6/tools/cache/shared_informer.go:771 +0x6b
