### ISSUE TITLE
Add a new podLogsDirectory setting to Kubelet

### ISSUE THREAD

**Issue by mate201** [kubernetes/kubernetes#122021] opened 2023-11-23 10:19 UTC
### What would you like to be added?

Add a new podLogsDirectory setting to Kubelet, which will provide users with ability to set `podLogsRootDirectory`.

### Why is this needed?

The text below is copied from original [issue](https://github.com/kubernetes/kubernetes/issues/108384):

The root directory for pod logs is /var/log/pods as default, and doesn't support modification.
Sometimes we want container logs to be output to a specified place according to the disk usage plan.

Actually, docker outputs container logs to its workspace, and then creates symlink to /var/log/pods (dockershim does). That's ok.
After runtime switchs to others, like containerd, we should provide a way to set podLogsRootDirectory.

**Comment by kannon92** [comment] 2023-11-23 16:30
This is a duplicate of an existing issue. And someone has a PR up for it: https://github.com/kubernetes/kubernetes/pull/112957

**Comment by kannon92** [comment] 2023-11-23 16:31
Duplicate of https://github.com/kubernetes/kubernetes/issues/98473

/close

**Closed by kannon92** 2023-11-23 16:31 UTC
Labels: sig/node, kind/feature, sig/instrumentation, needs-triage, wg/structured-logging
