### ISSUE TITLE
nodePort is getting dropped

### ISSUE THREAD

**Issue by jdk-google** [kubernetes/kubernetes#9126] opened 2015-06-02 15:48 UTC
in my GKE cluster I'm creating a service using the file of the below contents, then I'm calling the below two commands

kubectl create -f frontend-service-test.json
kubectl get services/frontend-test -o json

and the "nodePort" field silently dissapears. Any ideas why?
 If there are some errors in the config I would expect to get an error

----- file contents ----
{
   "foobar": 3,
   "kind":"Service",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"frontend-test",
      "labels":{
         "name":"frontend-test"
      }
   },
   "spec":{
      "ports": [
        {
          "port":3001,
          "targetPort":3000,
          "nodePort":3002,
          "protocol":"TCP"
        }
      ],
      "selector":{
         "name":"frontend"
      },
      "createExternalLoadBalancer": true
   }
}

**Comment by thockin** [comment] 2015-06-02 16:10
@justinsb if he has time

**Comment by roberthbailey** [comment] 2015-06-02 17:32
NodePorts weren't added until 0.18.0 and GKE is not yet exposing this version of kubernetes (you can see the version of your cluster by running `gcloud alpha containers clusters list`). We expect to have 0.18.0 support in GKE by the end of this week.

**Comment by jdk-google** [comment] 2015-06-08 11:10
I see - so this is probably another example of a case where silently dropping uknown fields is not good.

Instead - I would raise an error for every JSON field not know to the server

**Comment by bgrant0607** [comment] 2015-08-17 23:28
Dupe of our other validation issues.

**Closed by bgrant0607** 2015-08-17 23:28 UTC
Labels: kind/friction, kind/support, priority/P3, team/cluster
