### ISSUE TITLE
Pods are not evicted if node is in NotReady state

### ISSUE THREAD

**Issue by Craftoncu** [kubernetes/kubernetes#101391] opened 2021-04-23 00:14 UTC
#### What happened:
If I stop the kubelet of one on my node server the pods on it arent evicted after 24 hours.

#### How to reproduce it (as minimally and precisely as possible):
Clean install Kubernetes v1.21.0 with kubespray

My pod keeps in Terminating state. But theres a warning on it "Node is not ready".

My pod configuration:

> kind: Pod
apiVersion: v1
metadata:
  name: prometheus-0
  generateName: prometheus-
  namespace: lens-metrics
  uid: aee8a22d-69ea-4815-85a8-b1d1ac8836b8
  resourceVersion: '12393'
  creationTimestamp: '2021-04-22T23:41:45Z'
  deletionTimestamp: '2021-04-22T23:49:27Z'
  deletionGracePeriodSeconds: 30
  labels:
    controller-revision-hash: prometheus-74f49f6589
    name: prometheus
    statefulset.kubernetes.io/pod-name: prometheus-0
  ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus
      uid: b94c9659-7e70-41ad-af5e-9997dd2c1d27
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-04-22T23:42:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:initContainerStatuses': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.233.96.1"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-04-22T23:43:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:controller-revision-hash': {}
            'f:name': {}
            'f:statefulset.kubernetes.io/pod-name': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"b94c9659-7e70-41ad-af5e-9997dd2c1d27"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:affinity':
            .: {}
            'f:nodeAffinity':
              .: {}
              'f:requiredDuringSchedulingIgnoredDuringExecution':
                .: {}
                'f:nodeSelectorTerms': {}
          'f:containers':
            'k:{"name":"prometheus"}':
              .: {}
              'f:args': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:livenessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":9090,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:readinessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:resources':
                .: {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/etc/prometheus"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/prometheus/rules"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/var/lib/prometheus"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:hostname': {}
          'f:initContainers':
            .: {}
            'k:{"name":"chown"}':
              .: {}
              'f:command': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/var/lib/prometheus"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:serviceAccount': {}
          'f:serviceAccountName': {}
          'f:subdomain': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"config"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
            'k:{"name":"data"}':
              .: {}
              'f:emptyDir': {}
              'f:name': {}
            'k:{"name":"rules"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
        'f:status':
          'f:conditions':
            'k:{"type":"Ready"}':
              'f:lastTransitionTime': {}
              'f:status': {}
  selfLink: /api/v1/namespaces/lens-metrics/pods/prometheus-0
spec:
  volumes:
    - name: config
      configMap:
        name: prometheus-config
        defaultMode: 420
    - name: rules
      configMap:
        name: prometheus-rules
        defaultMode: 420
    - name: data
      emptyDir: {}
    - name: kube-api-access-5d2dh
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  initContainers:
    - name: chown
      image: 'docker.io/alpine:3.9'
      command:
        - chown
        - '-R'
        - '65534:65534'
        - /var/lib/prometheus
      resources: {}
      volumeMounts:
        - name: data
          mountPath: /var/lib/prometheus
        - name: kube-api-access-5d2dh
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  containers:
    - name: prometheus
      image: 'quay.io/prometheus/prometheus:v2.19.3'
      args:
        - '--web.listen-address=0.0.0.0:9090'
        - '--config.file=/etc/prometheus/prometheus.yaml'
        - '--storage.tsdb.path=/var/lib/prometheus'
        - '--storage.tsdb.retention.time=2d'
        - '--storage.tsdb.retention.size=5GB'
        - '--storage.tsdb.min-block-duration=2h'
        - '--storage.tsdb.max-block-duration=2h'
      ports:
        - name: web
          containerPort: 9090
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
      volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: rules
          mountPath: /etc/prometheus/rules
        - name: data
          mountPath: /var/lib/prometheus
        - name: kube-api-access-5d2dh
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /-/healthy
          port: 9090
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /-/ready
          port: 9090
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: prometheus
  serviceAccount: prometheus
  nodeName: workernode3
  securityContext: {}
  hostname: prometheus-0
  subdomain: prometheus
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
          - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                  - linux
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-04-22T23:41:49Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-04-22T23:43:51Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-04-22T23:42:15Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-04-22T23:41:45Z'
  hostIP: 10.0.0.5
  podIP: 10.233.96.1
  podIPs:
    - ip: 10.233.96.1
  startTime: '2021-04-22T23:41:45Z'
  initContainerStatuses:
    - name: chown
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2021-04-22T23:41:49Z'
          finishedAt: '2021-04-22T23:41:49Z'
          containerID: >-
            docker://4b661eee9d99d82f6635a9e4a2b075fdffaa04b9100fecf6902f22182f9a9ca9
      lastState: {}
      ready: true
      restartCount: 0
      image: 'alpine:3.9'
      imageID: >-
        docker-pullable://alpine@sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011
      containerID: >-
        docker://4b661eee9d99d82f6635a9e4a2b075fdffaa04b9100fecf6902f22182f9a9ca9
  containerStatuses:
    - name: prometheus
      state:
        running:
          startedAt: '2021-04-22T23:41:59Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: 'quay.io/prometheus/prometheus:v2.19.3'
      imageID: >-
        docker-pullable://quay.io/prometheus/prometheus@sha256:8580e76d36a27da031f7164bb3284ad6415ab0a64ae566998d42cbc5a52fa1b0
      containerID: >-
        docker://7407e630f94f1c31b1c3549676a4cfd9d2880710917c97cb359169b92755e752
      started: true
  qosClass: Burstable

Here output from my nodes:
![grafik](https://user-images.githubusercontent.com/55136417/115800097-30b07200-a3da-11eb-82fe-db74f0913c72.png)

Following tolerations are set:
![grafik](https://user-images.githubusercontent.com/55136417/115800183-5e95b680-a3da-11eb-8614-5e72f5cc4694.png)

Output of my pods in used namespace:
![grafik](https://user-images.githubusercontent.com/55136417/115800375-c77d2e80-a3da-11eb-91f1-ce64cd336428.png)

**Comment by neolit123** [comment] 2021-04-25 18:47
duplicate of:
https://github.com/kubernetes/kubernetes/issues/55713

/close
/kind duplicate

**Closed** 2021-04-25 18:47 UTC
Labels: kind/bug, needs-sig, needs-triage
