### ISSUE TITLE
kubernetes cp command does not respond

### ISSUE THREAD

**Issue by Dhananjay-J-P** [kubernetes/kubernetes#61589] opened 2018-03-23 09:01 UTC
I want to copy one folder to pod, I am using below command 

``kubectl cp keys $POD:/home/oracle/ ``

Issue is when I hit enter, I do not see any response(it does not exit after copying folder,this behavior is sporadic), as if the command is taking long time, although when I check POD I can see folder is copied.

I need to close it with ctrl+c to execute next command.

**Comment by liggitt** [comment] 2018-03-23 15:37
likely a duplicate of https://github.com/kubernetes/kubernetes/issues/61557 (stdin consumption hangs, and `cp` uses stdin)

/close

**Closed by liggitt** 2018-03-23 15:37 UTC
Labels: needs-sig
