### ISSUE TITLE
Ubuntu manual install failed.

### ISSUE THREAD

**Issue by asifhj** [kubernetes/kubernetes#43221] opened 2017-03-16 15:42 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):  Ubuntu manual install failed.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`): 1.5.4

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 4.2.0-27-generic
- **Install tools**: NA
- **Others**: NA

**What happened**:
Installation failed.

**What you expected to happen**:
Should get install without an exception.

**How to reproduce it** (as minimally and precisely as possible):
git clone --depth 1 https://github.com/kubernetes/kubernetes.git
cd kubernetes
Edit config-default.sh
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

**Anything else we need to know**:

```
asif@KubeNode1:~/kubernetes/cluster$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /home/asif/.ssh/id_rsa (/home/asif/.ssh/id_rsa)
... calling verify-kube-binaries
!!! kubectl appears to be broken or missing
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
!!! Cannot find kubernetes-salt.tar.gz
Required binaries appear to be missing. Do you wish to download them? [Y/n]
y
Kubernetes release: v1.5.4
Server: linux/amd64  (to override, set KUBERNETES_SERVER_ARCH)
Client: linux/amd64  (autodetected)

Will download kubernetes-server-linux-amd64.tar.gz from https://storage.googleapis.com/kubernetes-release/release/v1.5.4
Will download and extract kubernetes-client-linux-amd64.tar.gz from https://storage.googleapis.com/kubernetes-release/release/v1.5.4
Is this ok? [Y]/n
y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  299M  100  299M    0     0  28.6M      0  0:00:10  0:00:10 --:--:-- 33.1M

md5sum(kubernetes-server-linux-amd64.tar.gz)=8f18205247f0247c850e98121a1d9404
sha1sum(kubernetes-server-linux-amd64.tar.gz)=6963895f3b966ac11c8055527c9f2b7dc200ef38

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.2M  100 22.2M    0     0  9699k      0  0:00:02  0:00:02 --:--:-- 9701k

md5sum(kubernetes-client-linux-amd64.tar.gz)=00bf70528fe7be3b824167502f550987
sha1sum(kubernetes-client-linux-amd64.tar.gz)=5605629e0d75387853a8497a102350dfa5461426

Extracting /home/asif/kubernetes/client/kubernetes-client-linux-amd64.tar.gz into /home/asif/kubernetes/platforms/linux/amd64
Add '/home/asif/kubernetes/client/bin' to your PATH to use newly-installed binaries.
... calling kube-up
~/kubernetes/cluster/ubuntu ~/kubernetes/cluster
Prepare flannel 0.5.5 release ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    508      0 --:--:--  0:00:01 --:--:--   508
100 3408k  100 3408k    0     0   479k      0  0:00:07  0:00:07 --:--:--  724k
Prepare etcd 2.3.1 release ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0    527      0 --:--:--  0:00:01 --:--:--   527
100 7946k  100 7946k    0     0   522k      0  0:00:15  0:00:15 --:--:-- 1541k
Prepare kubernetes 1.5.4 release ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.2M  100 22.2M    0     0  11.4M      0  0:00:01  0:00:01 --:--:-- 11.4M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  299M  100  299M    0     0  22.2M      0  0:00:13  0:00:13 --:--:-- 25.1M
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/kubernetes/cluster

Deploying master and node on machine 10.20.51.117
asif@10.20.51.117's password:
asif@10.20.51.117's password:
make-ca-cert.sh                                                                                                                                          100% 4333     4.2KB/s   00:00
easy-rsa.tar.gz                                                                                                                                          100%   42KB  42.4KB/s   00:00
config-default.sh                                                                                                                                        100% 6267     6.1KB/s   00:00
util.sh                                                                                                                                                  100%   29KB  29.0KB/s   00:00
kube-proxy.conf                                                                                                                                          100%  688     0.7KB/s   00:00
kubelet.conf                                                                                                                                             100%  645     0.6KB/s   00:00
kubelet                                                                                                                                                  100% 2158     2.1KB/s   00:00
kube-proxy                                                                                                                                               100% 2233     2.2KB/s   00:00
kube-scheduler.conf                                                                                                                                      100%  682     0.7KB/s   00:00
kube-controller-manager.conf                                                                                                                             100%  761     0.7KB/s   00:00
kube-apiserver.conf                                                                                                                                      100%  682     0.7KB/s   00:00
etcd.conf                                                                                                                                                100%  707     0.7KB/s   00:00
kube-apiserver                                                                                                                                           100% 2358     2.3KB/s   00:00
kube-scheduler                                                                                                                                           100% 2360     2.3KB/s   00:00
kube-controller-manager                                                                                                                                  100% 2672     2.6KB/s   00:00
etcd                                                                                                                                                     100% 2073     2.0KB/s   00:00
reconfDocker.sh                                                                                                                                          100% 2183     2.1KB/s   00:00
etcdctl                                                                                                                                                  100%   14MB  13.7MB/s   00:00
kube-apiserver                                                                                                                                           100%  119MB 119.0MB/s   00:00
kube-scheduler                                                                                                                                           100%   50MB  50.4MB/s   00:01
kube-controller-manager                                                                                                                                  100%   97MB  96.9MB/s   00:00
flanneld                                                                                                                                                 100%   16MB  15.8MB/s   00:00
etcd                                                                                                                                                     100%   16MB  15.9MB/s   00:00
kubelet                                                                                                                                                  100%  103MB 103.1MB/s   00:00
flanneld                                                                                                                                                 100%   16MB  15.8MB/s   00:00
kube-proxy                                                                                                                                               100%   44MB  43.6MB/s   00:01
asif@10.20.51.117's password:
flanneld.conf                                                                                                                                            100%  579     0.6KB/s   00:00
flanneld                                                                                                                                                 100% 2121     2.1KB/s   00:00
flanneld.conf                                                                                                                                            100%  570     0.6KB/s   00:00
flanneld                                                                                                                                                 100% 2131     2.1KB/s   00:00
asif@10.20.51.117's password:
/home/asif/kube/util.sh: line 22: /cluster/common.sh: No such file or directory
Connection to 10.20.51.117 closed.
Deploying master and node on machine 10.20.51.117 failed
```

**Comment by digglife** [comment] 2017-04-05 13:15
It's actually pretty frustrating if anyone like me start installing Kubernetes for the first time with these scripts for Ubuntu. I don't know what they ignore this serious issue, the original script just does NOT work as described in the official documents. 

Thank you @asifhj !

**Comment by ixdy** [comment] 2017-04-13 21:05
cc @resouer, @WIZARD-CXY

**Comment by ixdy** [comment] 2017-04-13 21:13
closing as dupe of #39224

**Closed** 2017-04-13 21:18 UTC
