### ISSUE TITLE
kubectl overwriting error message from server during `kubectl logs pod` (missing container within pod)

### ISSUE THREAD

**Issue by dlamotte** [kubernetes/kubernetes#39745] opened 2017-01-11 17:54 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
is:issue is:open label:area/kubectl error incorrect 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-22T13:59:22Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS Stable
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:
Running `kubectl logs pod` spews unhelpful error (older versions gave helpful error).

```
% kubectl logs mypod
Error from server (BadRequest): the server rejected our request for an unknown reason (get pods mypod)
```

**What you expected to happen**:
```
% kubectl logs mypod
Error from server (BadRequest): a container name must be specified for pod mypod, choose one of: [container1 container2]
```

**How to reproduce it** (as minimally and precisely as possible):
See above.  I believe you need at least 2+ containers in the pod to reproduce or it may default to the only container and "just work".

**Anything else do we need to know**:
Appears to be a regression.  Also, you can see the appropriate error by cranking up verbosity to `-v=8`.
```
% kubectl -v=8 logs mypod
...
I0111 11:45:01.868624   21381 request.go:904] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod mypod, choose one of: [container1 container2]","reason":"BadRequest","code":400}
...
```

Appears to be killing the correct and helpful error message.

**Comment by AdoHe** [comment] 2017-01-15 08:46
@kubernetes/sig-cli-misc

**Comment by kargakis** [comment] 2017-01-16 10:52
Dupe of https://github.com/kubernetes/kubernetes/issues/38774

**Closed by kargakis** 2017-01-16 10:52 UTC
