### ISSUE TITLE
Failing tests: multiple In-tree Volumes failures

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#68744] opened 2018-09-17 15:06 UTC
Failing Jobs
---
[sig-release-1.12-blocking#gce-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial)
[sig-release-1.12-blocking#gke-cos-1.12-default](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-default)
[sig-release-1.12-blocking#gke-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-serial)
[sig-release-master-blocking#gci-gce-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial)
[sig-release-master-blocking#gci-gke-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial)

Failing Tests
---
```
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]
[sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Dynamic PV (default fs)] volumes should be mountable
[sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly file specified in the volumeMount
[sig-storage] In-tree Volumes [Driver: azure] [Testpattern: Pre-provisioned PV (default fs)] volumes should be mountable
[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly file specified in the volumeMount
```

Error Example
---
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:120
Persistent Volume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 not deleted by dynamic provisioner
Expected error:
    <*errors.errorString | 0xc421bbec70>: {
        s: "PersistentVolume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 still exists within 5m0s",
    }
    PersistentVolume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 still exists within 5m0s
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:212
```

Triage
---
Tests failing across release-master-blocking, release-1.12-all and release-1.12-blocking.  More failures on GKE.  Many of the test results in testgrid are stale, most recently failing is https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial

/kind bug
/kind failing-test
/sig storage
/priority critical-urgent
/milestone v1.12

**Comment by tpepper** [comment] 2018-09-17 15:06
@kubernetes/sig-storage-test-failures

**Comment by tpepper** [comment] 2018-09-17 15:07
/assign @saad-ali 
/cc @childsb 

SIG leaders can you please triage this ASAP.  May be release blocking.

**Comment by saad-ali** [comment] 2018-09-17 16:06
Taking a look

**Comment by saad-ali** [comment] 2018-09-17 16:17
The only test that is currently failing is `[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]`

**Comment by saad-ali** [comment] 2018-09-17 16:41
This failure very roughly aligns with when https://github.com/kubernetes/kubernetes/pull/68590 was merged.

Assigning to David to debug further. 

/assign @davidz627

**Comment by tpepper** [comment] 2018-09-17 17:30
Since this looks like a recent regression, we will block 1.12 release on this until SIG Storage indicates otherwise.

**Comment by davidz627** [comment] 2018-09-17 23:19
Looks like the failure is happening in UnmountDevice during a check to see if the device is being used anywhere else on the system. The UnmountDevice call is "finding out" that the device is being used by `Open`ing the device path and getting a `EBUSY` error.

I have been unable to determine where the `EBUSY` error is coming from as there are no latent file descriptors open on that device as well as no remaining mounts. However, it does seem like if we just wait a while/retry the `EBUSY` error goes away showing that there is nothing else using the device. Current theory is that there is some kernel latency that causes the `Open` to fail for a while even after all others stop using the device (conjecture).

The fix being applied right now is that we will NOT fail UnmountDevice if the path is missing (already unmounted) and redo the `isDeviceOpened` check on the retry (it should show that the device is no longer opened after the time delay).

**Comment by msau42** [comment] 2018-09-17 23:34
The GetMountRefs failure if device path doesn't exist looks like it was introduced in 1.12 from https://github.com/kubernetes/kubernetes/pull/64416.  It consolidates the GetMountRefs methods to a new version of GetMountRef that errors in EvalSymlinks if the path doesn't exist (the old version still worked if path didn't exist).

 I'm still running the e2e against older releases to confirm.

**Comment by msau42** [comment] 2018-09-17 23:35
Also, the e2e started failing because we recently added more stringent validation to the test that caught this issue.

**Comment by saad-ali** [comment] 2018-09-17 23:47
Great work catching a potential regression with added testing!

**Comment by msau42** [comment] 2018-09-18 00:28
Ran the new e2e test changes against 1.10 and 1.11 clusters, and they passed.  So this is definitely a 1.12 regression

**Closed** 2018-09-18 19:32 UTC
Labels: kind/bug, kind/failing-test, priority/critical-urgent, sig/storage
