### ISSUE TITLE
MountVolume.SetUp succeeded for volume fills log files

### ISSUE THREAD

**Issue by bobveznat** [kubernetes/kubernetes#46364] opened 2017-05-24 17:25 UTC
**Kubernetes version**: 1.5.7

**Environment**:
- **Cloud provider or hardware configuration**: bare-metal installation on aws
- **OS** (e.g. from /etc/os-release): ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): 4.4.0-1016-aws
- **Install tools**: Custom installation
- **Others**:

**What happened**:
kubelet loves to tell me that "MountVolume.SetUp succeeded for volume". I have a reasonably small Kubernetes installation and this was logged on one host 116,244 times in 24 hours on a single host generating 39MB of log data in /var/log/syslog. The entire /var/log/syslog file is only 44MB. I have 4 "important" kubernetes clusters and across them 33 nodes running kubelet. At 39MB/host that's on the order of 1GB/day of MountVolume.SetUp succeeded log messages.

I use SumoLogic to collect my log files. This is worth approximately 3% of my quota to Sumo where each GB/day is expensive.

This verbose logging is probably exacerbated by our reasonably liberal use of secrets. Many of our deployments mount at least 3 and up to 5 secret volumes. We have approximately 2 dozen deployments running on each cluster.

**What you expected to happen**:
Don't log the same thing over and over again in a normal operational mode. These messages appear more "debug" than "info".

**How to reproduce it** (as minimally and precisely as possible):
To the best of my knowledge you simply need to deploy pods that mount secrets or volumes.

**Anything else we need to know**:
Logs are expensive.

**Comment by saad-ali** [comment] 2017-05-24 18:02
Duplicate of https://github.com/kubernetes/kubernetes/issues/29059. Closing in favor of that. But agreed this needs to be fixed (sad that it's slipped through so many releases).

**Closed by saad-ali** 2017-05-24 18:02 UTC
Labels: sig/storage
