### ISSUE TITLE
non-cri kubelet suite fails to launch nodes

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44683] opened 2017-04-19 20:08 UTC
Triage failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#d5276d7aa136b62f6d24

Testgrid history: https://k8s-testgrid.appspot.com/google-node#kubelet-non-cri-gce-e2e

Node owners:
/assign @derekwaynecarr @dchen1107

**Comment by dchen1107** [comment] 2017-04-19 22:13
It is a regression introduced yesterday. I am looking into it.

**Comment by dchen1107** [comment] 2017-04-19 22:20
From kubelet log:
```
KubeletNotReady could not locate kubenet required CNI plugins [bridge host-local loopback] at \"/opt/cni/bin\" or \"\"
```

The node is notready because the path of CNI plugin / kubenet is changed lately?

**Comment by dchen1107** [comment] 2017-04-19 22:34
@dnardo I believe your pr https://github.com/kubernetes/kubernetes/pull/44457 causing the regression for non-cri node-e2e here. 

cc/ @kubernetes/sig-network-bugs

**Comment by Random-Liu** [comment] 2017-04-19 22:53
I think the reason is that, for cri integration, we use `CNIBinDir` first for kubenet:
https://github.com/kubernetes/kubernetes/blob/b0a05b4597f7401a83f82348c5b353844fe13fd3/pkg/kubelet/kubelet.go#L533
But for non-cri integration, we are still using NetworkPluginDir 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L128

**Comment by dnardo** [comment] 2017-04-19 23:17
Yuck, sorry I'm looking at it.

**Comment by calebamiles** [comment] 2017-04-21 21:44
testgrid looks clean again. Closing this issue.

**cc: @dchen1107, @kubernetes/kubernetes-release-managers**

**Closed by calebamiles** 2017-04-21 21:44 UTC
Labels: area/node-e2e, area/node-lifecycle, kind/flake, sig/network, sig/node
