### ISSUE TITLE
hang on "kubectl delete" command

### ISSUE THREAD

**Issue by RushPu** [kubernetes/kubernetes#66110] opened 2018-07-12 08:22 UTC
/kind bug

**What happened**:
hang on "kubectl delete" command on my deployer machine, but can run other commands as usual
![image](https://user-images.githubusercontent.com/7221798/42620783-8b810d32-85ee-11e8-862b-af4ed0c8a856.png)
can run "kubectl delete" command on master node, deployer and master have the same ~/.kube directory.

**What you expected to happen**:
delete some resource

**How to reproduce it (as minimally and precisely as possible)**:
I don't know

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
![image](https://user-images.githubusercontent.com/7221798/42620984-14ed508a-85ef-11e8-9193-3957c382f7c5.png)
- Cloud provider or hardware configuration:
azure, I am not using cloud provider
- OS (e.g. from /etc/os-release):
centos 7.5
- Kernel (e.g. `uname -a`):
Linux cn2-k8s-deployer 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
installed by kubespray
- Others:

**Comment by liggitt** [comment] 2018-07-12 10:23
this is caused by a switch to kubectl to use "foreground deletion" in 1.11.0 that relies on server-side garbage collection being responsive to clean up the resource and its dependents, and blocks until it does.

the hang means that your controller manager isn't running, or the garbage collection controller isn't responsive at the moment you are deleting the object.

because of interactions like this, kubectl is returning to use background deletion in 1.11.1 (see https://github.com/kubernetes/kubernetes/pull/66024)

**Comment by liggitt** [comment] 2018-07-13 15:24
fixed in #66024, will be in 1.11.1
/close

**Closed by liggitt** 2018-07-13 15:24 UTC
Labels: kind/bug, sig/azure

**Comment by nilebox** [comment] 2018-08-17 05:28
The fix in #66024 makes me sad :(
We have just found out that foreground cascade deletion is not working in kubectl again.

> "foreground deletion" in 1.11.0 that relies on server-side garbage collection being responsive to clean up the resource and its dependents, and blocks until it does.

The workaround  for that would be not to wait, kubectl has a `--wait` flag for that:
```
 kubectl delete --wait=false ...
```

> the hang means that your controller manager isn't running, or the garbage collection controller isn't responsive at the moment you are deleting the object.

Personally I would prefer to get a hanging kubectl in that case.

@liggitt was keeping a backward compatibile behavior the main reason to switch back to `Background`? We should probably have a flag for explicit `--deletionMode=foreground` at least then... Otherwise there is no way to trigger a foreground deletion via kubectl :(

**Comment by nilebox** [comment] 2018-08-17 14:02
@liggitt the `Foreground` deletion mode is implemented in GC on the server side, and while understand the use case for client-side reapers, I disagree that it is only useful for some client-side blocking.

The real use case we have (as I previously described in #59850) is building a tree of objects where deleting a root will force deletion of all its children first and will block the deletion of itself in the meantime. This has nothing to do with a client-side logic, it's just annoying that `kubectl` won't ever use this mode, and our users obviously deleting objects via `kubectl`.

This is very similar to namespace behavior: deleted namespace gets blocked until all objects within it are gone.

I understand the concerns of having foreground deletion mode enabled by default though.
