### ISSUE TITLE
Migrate from godep to dep

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/kubernetes#52728] opened 2017-09-19 15:03 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

When it comes to dependency handling, migrate from godep to [dep](https://github.com/golang/dep). There are two reasons for this:

1. godep development is essentially done. See https://github.com/tools/godep/graphs/contributors. Edward Muller, the primary author of godep, worked in the group that came to the conclusion to start dep and he has contributed to that.
2. Kubernetes is a sufficiently complex project. If dep can work for Kubernetes it will be able to work for most things.

Note, I realize that for k8s to make the change it may mean changes to dep.

**Comment by mattfarina** [comment] 2017-10-24 18:15
@thockin before I dive headlong into this I would like to know whose blessing I'd need. Don't want to do the work if this isn't going to fly.

**Comment by fejta** [comment] 2018-01-28 06:50
/assign @sttts @mattfarina 
/assign

Stefan aren't you working on this?

**Comment by sttts** [comment] 2018-01-28 10:18
@fejta yes: https://github.com/kubernetes/kubernetes/pull/57795

**Comment by cblecker** [comment] 2018-02-05 05:23
Closing as a dupe of #44873
/close

**Closed by cblecker** 2018-02-05 05:23 UTC
Labels: area/build-release, sig/testing
