### ISSUE TITLE
e2e flake: RollingUpdateDeployment should delete old pods and create new ones [ Test Panicked]

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#21834] opened 2016-02-24 01:17 UTC
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/30094
https://cloud.google.com/console/storage/kubernetes-jenkins/pr-logs/pull/21790/kubernetes-pull-build-test-e2e-gce/30094/

```
•! Panic [66.156 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  RollingUpdateDeployment should delete old pods and create new ones [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:47

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/src/go/src/runtime/panic.go:387

  Full Stack Trace
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:194 (0xa13d3e)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:157 (0xa1364a)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:73 (0xa12159)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:58 (0xa11f90)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:2111 (0x56d42f)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:181 (0x8ca0e0)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:143 (0x8c9efb)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:137 (0x8c9e4c)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:2148 (0x531960)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:273 (0x47f04e)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:46 (0x58c47a)
  /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 (0x13af7d5)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:28 (0x541cb8)
  /usr/src/go/src/testing/testing.go:447 (0x46112f)
  /usr/src/go/src/runtime/asm_amd64.s:2232 (0x440541)
  ```

**Comment by bgrant0607** [comment] 2016-02-24 05:45
Dupe of #21765

**Closed by bgrant0607** 2016-02-24 05:45 UTC
Labels: area/test, kind/flake, team/ux
