### ISSUE TITLE
AWS, ELB: Allow LoadBalancer for service with sessionAffinity: ClientIP

### ISSUE THREAD

**Issue by mcbain** [kubernetes/kubernetes#13892] opened 2015-09-12 09:22 UTC
```
failed to create external load balancer for service pro/xyz: unsupported load balancer affinity: ClientIP
```

As in understood from http://kubernetes.io/v1.0/docs/user-guide/services.html the service setting 'sessionAffinity' is for the kube-proxy on each minion and not for the external load-balancer.
If both supporting the same sessionAffinity, one may also configure it on the external load-balancer, but it's just an optimization to already route the traffic to the target minion.

**Comment by justinsb** [comment] 2015-09-12 16:37
Hi - we use ELB on AWS for the load-balancer, in TCP mode.  My understanding is the ELB only supports sticky sessions when used in HTTP mode.  Even then it uses a cookie, not the clientIP.

What are you trying to do here?  It's not trivial, but there are options... we could add support for cookie-based ELB HTTP load balancers, we could change kube-proxy to do ClientIP based load-balancing.  There's also some work going on for Layer 7 HTTP load balancing, so it might be that it gets incorporated into that.  So any more details on what you'd like to achieve would be helpful!

**Comment by mcbain** [comment] 2015-09-12 17:55
Maybe I misunderstood the kube proxy load balancer. My idea of setting the sessionAfinity to clientIP was that all traffic to the service would be managed by kube proxy and routed to the correct target pod e.g. by client ip, even when the pod is on an other minion. The ELB would then just need to route the external traffic to one of the minions. Maybe this is completely wrong?!

**Comment by thockin** [comment] 2015-09-15 05:26
When coming through an ELB traffic frist has to arrive at a node (chosen by
ELB) and then get directed to a pod (chosen by kube-proxy).  Because
kube-proxies are not connected, and ELB doesn't do sticky, you might end up
at two different nodes, which make independent decisions about which
backend to give you.  :(

**Comment by justinsb** [comment] 2015-09-16 02:44
@thockin Do you think consistent hashing based on client IP would work though (not 100% sticky, but close)?  Although to capture the client IP we would _also_ need to turn on ELB's PROXY protocol, so it definitely would be a lot of work.

@mcbain is this primary for sticky HTTP sessions?  If so I think it would be much simpler to implement that with cookies in a Layer 7 load balancer (nginx/haproxy) running inside k8s, without requiring the (complicated) changes above.  Is HTTP the primary use case?

**Comment by thockin** [comment] 2015-09-16 03:43
@justinsb that sounds closer to correct than just ignoring the field, but
if it is a ton of work, it's probably not urgent.

**Comment by mcbain** [comment] 2015-09-16 06:33
@justinsb we want to serve our meteor apps with websockets support :)

**Comment by justinsb** [comment] 2015-09-16 11:09
Well that sounds familiar :-)

I think the best bet here is going to be to use an HTTP L7 load balancer (nginx or haproxy) running inside k8s, and use the sticky session support that it offers (probably cookie based).  k8s does have a layer 7 load balancer integration that I think/hope will be merged in 1.1; I don't know if it will support sticky sessions or websockets but we should try to make sure it does.

The big problem with something based on client-ip hashing is that ELB masks the client IP, so we'd have to enable the PROXY protocol, and then I don't think that would work with an iptables-backed kube-proxy (which is I believe where we're going).

**Comment by rroopreddy** [comment] 2015-10-09 00:44
Same issue with MQTT traffic through load balancer to message broker in the pods.  Similar to Websockets, TCP connections have to be sticky between load balancer <-> Services <-> Pods

**Comment by markoshust** [comment] 2016-03-01 21:50
Is my issue (http://stackoverflow.com/questions/35322432/running-meteor-app-with-nginx-ssl-proxy-on-kubernetes) caused because the ClientIP session affinity isn't being properly set in k8s? I thought I can use the network-layer load balancing vs doing it within nginx config.

**Comment by justinsb** [comment] 2016-03-04 16:39
Maybe ... but I think a 10 second delay sounds more like mongodb polling?   How about if we collaborate on putting an example into the examples/ dir:  If we can get that working, you'll know the problem isn't k8s!  Hopefully we'll find the same problems you're hitting. Would you mind opening a new issue and tagging me?

**Comment by markoshust** [comment] 2016-03-04 18:09
@justinsb thank you, it sounded like polling to me, however sometimes when it connects, there is no 10 sec lag -- it's instant. i'll put together a quick example using the images i'm using, will try to do so by next week. cheers!

**Comment by guoshimin** [comment] 2016-03-22 15:03
@justinsb What is the L7 load balancer you were talking about? Is it Ingress?

**Comment by paralin** [comment] 2016-04-08 02:35
+1 to enabling PROXY protocol on the ELBs.

**Comment by bjoernwenzel-tommapps** [comment] 2016-04-29 12:41
+1

**Comment by ApsOps** [comment] 2016-05-19 08:24
I'm trying to run a socket.io application in k8s and facing this issue as well. I set `sessionAffinity: ClientIP` but it seems it won't work since ELB doesn't send client IPs by default. I tried enabling proxy protocol in ELB but then it just stops serving the requests.

I think it would be nice to have support for proxy protocol since this would be the case in most (all?) the websocket applications.

**Comment by justinsb** [comment] 2016-06-04 02:30
Support for PROXY protocol just landed.  With that, you should be able to run an ingress controller (e.g. nginx) that can see client IPs and add them as X-Forwarded-For (or similar), and do sticky sessions based on IP or cookies.

I think technically we haven't delivered the request feature (clientIP with Type=LoadBalancer), but we have implemented an alternative way of doing it.  Assigning to a not-immediate-future milestone.

**Comment by devonbarrett** [comment] 2016-07-19 11:22
Similar use case with Meteor+websockets, would be super useful to have this.

>How about if we collaborate on putting an example into the examples/ dir
@justinsb can't see anything in the examples directory, did anything happen with that?

**Comment by njuicsgz** [comment] 2016-11-21 06:12
+1 to enabling PROXY protocol on the ELBs.

**Comment by MichaelJCole** [comment] 2016-11-22 03:12
@justinsb 

>Support for PROXY protocol just landed. With that, you should be able to run an ingress controller (e.g. nginx) that can see client IPs and add them as X-Forwarded-For (or similar), and do sticky sessions based on IP or cookies.

Do you have an example for that?  I got the [impression it wasn't implemented in Ingress](http://kubernetes.io/docs/user-guide/ingress/#loadbalancing)

**Comment by abourget** [comment] 2017-01-16 22:08
Also looking for an example use of this, is proxy protocol enabled by default now?

**Comment by MichaelJCole** [comment] 2017-01-17 23:43
FWIW, I used the nginx ingress on AWS and GCE.  I don't understand the platforms deeply, but this got me what I wanted: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

**Comment by andyp1per** [comment] 2017-05-25 12:35
The application load balancer seems like the way to go now?
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

**Comment by renewooller** [comment] 2017-06-14 01:22
To those using the ingress controller instead of AWS ELB - are you placing all your nodes in a public subnet, and then adding all those nodes to a cname or something? I'm having trouble seeing how we'd achieve this from a private subnet.

**Closed** 2018-02-25 16:34 UTC
Labels: area/platform/aws, lifecycle/rotten, sig/aws, team/cluster (deprecated - do not use)

**Comment by wrstlrlp13** [comment] 2018-04-16 15:22
/reopen

Is there anything indicating that support for sessionAffinity: clientIP is coming to load balancers for aws anytime soon?

Or is the nginx approach just what I should be going with?

**Comment by MichaelInfoworks** [comment] 2018-04-16 16:09
LOL, google has time to automate crappy bots, but not fix bugs.  You got played @wrstlrlp13.  Do it again robot!

/reopen 

Sucka!

**Comment by stonefury** [comment] 2018-05-10 18:01
So am I right that ELB with a service ClientIP sessionaffinity was never supported then? Is the only solution to put a ingress controller in between and use the proxy protocol?

Thanks

**Comment by rileytj** [comment] 2018-12-19 00:56
Why not support the X-FORWARDED-FOR HTTP Header? You could keep 

sessionAffinity: ClientIP
sessionAffinityConfig:
    clientIP:
        xForwardedFor: true  <propose>
        timeout: 10

**Comment by regnaio** [comment] 2022-04-23 09:06
> Why not support the X-FORWARDED-FOR HTTP Header? https://en.wikipedia.org/wiki/X-Forwarded-For
> 
> ```
> sessionAffinity: ClientIP
> sessionAffinityConfig:
>     clientIP:
>         xForwardedFor: true  <propose>
>         timeout: 10
> ```

Is this now supported?
