### ISSUE TITLE
kubernetes-e2e-gce-parallel is occasionally timing out after 2 hours

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13891] opened 2015-09-12 07:32 UTC
For example
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7733/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7726/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7722/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7721/

@quinton-hoole @ixdy

**Comment by ixdy** [comment] 2015-10-05 21:44
Dupe of #13485.

**Closed** 2015-10-05 21:44 UTC
Labels: priority/P1, team/test-infra
