### ISSUE TITLE
code coverage is failed at some cases

### ISSUE THREAD

**Issue by tingzhang** [kubernetes/kubernetes#24967] opened 2016-04-29 06:26 UTC
``` console
KUBE_COVER="y" KUBE_COVERPROCS=8 ./hack/test-go.sh -- -p=2
--- FAIL: TestSnippetWriter (0.00s)
        snippet_writer_test.go:85: Expected "snippet_writer_test.go:78" but didn't find it in "template: /home/stack/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/libs/go2idl/generator  /snippet_writer_test.go:77:1: unclosed action"
FAIL
coverage: 10.2% of statements
FAIL    k8s.io/kubernetes/cmd/libs/go2idl/generator     0.053s
```

**Comment by zhouhaibing089** [comment] 2016-04-29 06:48
@kubernetes/sig-testing and @lavalamp

**Comment by zhouhaibing089** [comment] 2016-04-29 07:56
It show passes when doing this patch:

```patch
--- a/cmd/libs/go2idl/generator/snippet_writer_test.go
+++ b/cmd/libs/go2idl/generator/snippet_writer_test.go
@@ -73,15 +73,13 @@ type Blah struct {
                t.Errorf("Expected %q, got %q", e, a)
        }

-       err = generator.NewSnippetWriter(b, c, "$", "$").
-               Do("$.|public", c.Order[0]).
-               Error()
+       err = generator.NewSnippetWriter(b, c, "$", "$").Do("$.|public", c.Order[0]).Error()
        if err == nil {
                t.Errorf("expected error on invalid template")
        } else {
                // Dear reader, I apologize for making the worst change
                // detection test in the history of ever.
-               if e, a := "snippet_writer_test.go:78", err.Error(); !strings.Contains(a, e) {
+               if e, a := "snippet_writer_test.go:76", err.Error(); !strings.Contains(a, e) {
                        t.Errorf("Expected %q but didn't find it in %q", e, a)
                }
        }
```

**Comment by tingzhang** [comment] 2016-04-29 08:01
thanks @zhouhaibing089 !
Another issue is:
pkg/master/master_test.go
```
--- FAIL: TestThirdPartyDiscovery (1.01s)
        Error Trace:    master_test.go:982
                        master_test.go:955
        Error:          Not equal: unversioned.GroupVersionForDiscovery{GroupVersion:"company.com/v1", Version:"v1"} (expected)
                                != unversioned.GroupVersionForDiscovery{GroupVersion:"", Version:""} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,4 +1,4 @@
                         (unversioned.GroupVersionForDiscovery) {
                        - GroupVersion: (string) (len=14) "company.com/v1",
                        - Version: (string) (len=2) "v1"
                        + GroupVersion: (string) "",
                        + Version: (string) ""
                         }

        Error Trace:    master_test.go:982
                        master_test.go:955
        Error:          Not equal: unversioned.GroupVersionForDiscovery{GroupVersion:"company.com/v3", Version:"v3"} (expected)
                                != unversioned.GroupVersionForDiscovery{GroupVersion:"", Version:""} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,4 +1,4 @@
                         (unversioned.GroupVersionForDiscovery) {
                        - GroupVersion: (string) (len=14) "company.com/v3",
                        - Version: (string) (len=2) "v3"
                        + GroupVersion: (string) "",
                        + Version: (string) ""
                         }

I0429 15:59:47.079006   31130 genericapiserver.go:82] Adding storage destination for group
I0429 15:59:47.079106   31130 genericapiserver.go:82] Adding storage destination for group autoscaling
I0429 15:59:47.079148   31130 genericapiserver.go:82] Adding storage destination for group batch
I0429 15:59:47.079190   31130 genericapiserver.go:82] Adding storage destination for group extensions
I0429 15:59:48.036682   31130 tunneler.go:208] Private key /tmp/private-1461916787 exists, but public key does not
FAIL
coverage: 68.1% of statements
FAIL    k8s.io/kubernetes/pkg/master    15.152s
```

**Comment by zhouhaibing089** [comment] 2016-04-29 14:50
I do not know the detail, but it looks like the test actually report error at line 77.

**Comment by lavalamp** [comment] 2016-05-02 18:52
What go version are you using?

**Comment by zhouhaibing089** [comment] 2016-05-03 02:48
If I remember correctly, it could be reproduced when running with go1.5.3 and go1.6.1. To be more specific, the go test passes, and this issue only happened when enabled with `export KUBE_COVER=y`.

**Comment by lavalamp** [comment] 2016-05-03 20:04
Interesting. I guess code coverage changes the behavior of line reporting?

I'm willing to take a PR to fix this!

**Comment by lavalamp** [comment] 2016-09-02 22:30
the coverage tool rewrites source code. Seems like a bug that it changes line numbers in the _test.go files. Skipping it wasn't the right fix IMO, we should file a bug with them.

**Comment by smarterclayton** [comment] 2017-06-01 18:30
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 18:30 UTC
Labels: area/test, sig/api-machinery
