### ISSUE TITLE
Federation per-user cluster authentication, authorization and audit logging

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#35254] opened 2016-10-21 01:25 UTC
Filing this issue to discuss the design for "per-user cluster authentication, authorization and audit logging" in federation. Ref https://github.com/kubernetes/features/issues/73

Problems that we want to solve:
- Audit: In federation audit logs, we know which user sent a particular request to federation control plane. But in kubernetes audit logs, we do not get to know that a particular kubernetes request was in response to what federation request and by which federation user.
- Authorization: When federation control plane receives a request, we authorize the request in federation control plane, but we do not validate that the user has authority in underlying clusters.
- Authentication: Similar to above. When federation control plane receives a request, we authenticate the request in federation control plane, but we do not know the corresponding authn credentials for that user in each of the underlying clusters. Federation controllers use common credentials for all operations in each underlying cluster.

cc @kubernetes/sig-federation-feature-requests  @kubernetes/sig-auth-feature-requests 
@quinton-hoole Let me know if I missed anything.

**Comment by quinton-hoole** [comment] 2016-10-21 01:41
Thanks @nikhiljindal .  I'd suggest focussing squarely on your third point (Authentication) for v1.5.  Authorization at the federation level is much less important (because if you get the Authentication part right, then the Authorization will be done at the cluster level).  Similarly for Auditing - if all of the actions are made against the underlying clusters using the correct (non-root) credentials, then the audit logging problem partly solves itself.

We can loop back to any remaining Authorization and Auditing concerns in a subsequent pass.

**Comment by deads2k** [comment] 2016-10-21 12:39
> Authentication: Similar to above. When federation control plane receives a request, we authenticate the request in federation control plane, but we do not know the corresponding authn credentials for that user in each of the underlying clusters. Federation controllers use common credentials for all operations in each underlying cluster.

I think you should consider using the impersonation mechanism we built.  That way the audit trail on the delegatee server will have the record of "done by federated server user as Y", so you'll get audit, authentication, and authorization all for free.

**Comment by karunchennuri** [comment] 2016-10-25 18:52
> Authentication: Similar to above. When federation control plane receives a request, we authenticate the request in federation control plane, but we do not know the corresponding authn credentials for that user in each of the underlying clusters. Federation controllers use common credentials for all operations in each underlying cluster.

Is it assumed that users of federation control plane are different from users of underlying clusters?

**Comment by quinton-hoole** [comment] 2016-10-26 15:42
Yes, given that the cloud providers might be different.

**Comment by karunchennuri** [comment] 2016-10-28 17:26
@nikhiljindal do we see any cases where a user may have access to only few underlying clusters? 
User A has write-access on cluster1 but only read-access on cluster 2. In this case User A from FCP can schedule pods to run only on cluster 1.
User B has write-access on all clusters. UserB can schedule pods on all underlying clusters.

**Comment by nikhiljindal** [comment] 2016-11-02 07:39
Seems like there are 2 different cases:

1. A common auth provider is used across all clusters.
2. Different auth providers are used for different clusters.

I am not sure how many people use option 1. It might be possible when all the clusters are on the same cloud provider (for ex in different availability zones)? or when all the clusters are on prem.
In option 1, if a user has access to write a resource in cluster 1, they have access to write that resource in all clusters. In this case, we can just use the same auth provider in federation control plane.

In option 2, we will need a user auth mapping in federation control plane. For ex: federation control plane needs to know that when it gets a request from user Bob, it needs to send that request to AWS cluster as BobAWS user and send the same request to GKE cluster as BobGKE.

**Comment by nikhiljindal** [comment] 2016-11-02 07:48
> > Authentication: Similar to above. When federation control plane receives a request, we authenticate the request in federation control plane, but we do not know the corresponding authn credentials for that user in each of the underlying clusters. Federation controllers use common credentials for all operations in each underlying cluster.
> 
> I think you should consider using the impersonation mechanism we built. That way the audit trail on the delegatee server will have the record of "done by federated server user as Y", so you'll get audit, authentication, and authorization all for free.

@deads2k That is great! But we will need a way to keep track of which user did what action in federation control plane in a way that is easily accessible to the controllers. Today if user A 
adds a label to a federation service and then user B adds another label, then federation service controller might observe it as one operation and directly add both the labels to all services in underlying clusters. In this new world, controller needs to know that these are 2 different operations done by 2 different users, so that it first sends a request to add Label A while impersonating as user A and then send another request to add Label B while impersonating as user B.

**Comment by quinton-hoole** [comment] 2016-11-02 22:14
@nikhiljindal My suggestion would be to lay out the various options in a requirements and design document, and use that as the basis for discussion/comment, rather than a long thread here.

**Comment by deads2k** [comment] 2016-11-03 11:49
> In this new world, controller needs to know that these are 2 different operations done by 2 different users, so that it first sends a request to add Label A while impersonating as user A and then send another request to add Label B while impersonating as user B.

This request has actually come up before, but maintaining an audit trail like that for deciding what a controller should do has been difficult to reason about in all the scenarios we've tried.  When you write up the doc, try to come up with a specific scenario and perhaps a suggestion about how we could track it.  This is finer granularity than we currently have in our API server.

**Comment by quinton-hoole** [comment] 2016-11-03 23:00
cc @alex-mohr FYI

**Comment by karunchennuri** [comment] 2016-12-13 22:56
@nikhiljindal is this part of the v1.5 now? Is there a requirement & design document that I can refer to?

**Comment by nikhiljindal** [comment] 2017-01-19 01:10
Sorry for the delay, I have documented the pros and cons and added some details regarding how can we propagate user identity to individual clusters in https://docs.google.com/document/d/1h3ULIc65gzv-9i-Pi6akBC_rt9QlNtHDqKCIc06gVV8. I have also compared it with our existing auth setup.

I think we can let our existing auth setup be the default, but also allow admins to setup user identity propagation (option 1 in that doc). Please feel free to add comments

**Comment by nikhiljindal** [comment] 2017-04-18 01:16
Sent https://docs.google.com/document/d/1ioBg6Nn7PwyAAY48S42VQ0Zr1LXY5IAnMbBsftmE8DI with a more concrete design of how we can support both SingleIdentity and UserIdentity.

**Comment by nikhiljindal** [comment] 2017-04-28 01:32
I presented https://docs.google.com/document/d/1ioBg6Nn7PwyAAY48S42VQ0Zr1LXY5IAnMbBsftmE8DI at the sig-auth meeting (https://www.youtube.com/watch?v=eT35tfepKGE) and here are some of the major issues raised:

* In UserIdentity mode, Cluster still needs to trust federation to have authenticated the user and trust it to have impersonated the right user.
* Giving federation impersonation powers can give it more power. For ex: if federation is to be used only for federating deployments, with SingleIdentity, federation can be given a service account that has authorization only to CRUD deployments. With UserIdentity, federation gets the ability to impersonate the user and hence gets authorization to do everything that the user can do. This can be fixed if we implement "scoped impersonation" (federation can be allowed to impersonate a user only to do specific things) or "intersecting impersonation" (federation can only do things that both it and the user being impersonated is allowed to do).
* UserIdentity fixes the current confused deputy bug, but introduces a new one where federation can impersonate the wrong user.
* Concerns regarding federation keeping track of all group memberships of a user (impersonation requires having to provide group memberships of the user being impersonated) and potentially exposing that information to other users. This can be fixed if federation has access to an external webhook to get group memberships of a user. It will then not need to keep track of memberships itself.
* Concerns regarding multiple updates to a resource from different users batched together and attributed to the user who last updated it. This can be fixed by implementing the FieldUserIdentity proposal. That also brought up issues in tracking user who last updated each field.

**Comment by quinton-hoole** [comment] 2017-07-18 22:40
Regarding the issues (in the order above), my suggestions:

- If federation only ever impersonates the user who (last) updated the federated object it will be very difficult to create a bug where it impersonates some other, valid user (modulo eventual consistency). 
- I think that this can be addressed by creating a user account in each cluster which only has authorization to do the things that we want the federation to be able to do on their behalf. Using the above example, CRUD deployments.  The federation user should use this account.
- See item 1 above.
- I would like to understand why impersonation requires provision of group memberships.  Is this by design? It would seem that group membership should be dictated in the cluster, not in the federation?  If so, can we fix impersonation to work like this in the cluster?
- See previous comments regarding individual field updates, which seem to mostly be an illusion.  Even with patches, the entire object is read from etcd, updated, and written back to etcd in it's entirety.  Is there really value in distinguishing individual field updates from whole object updates?

**Comment by liggitt** [comment] 2017-07-19 01:32
> I think that this can be addressed by creating a user account in each cluster which only has authorization to do the things that we want the federation to be able to do on their behalf. Using the above example, CRUD deployments. The federation user should use this account.

Do you mean the federation *server* should use this account? If so, I agree.

> It would seem that group membership should be dictated in the cluster, not in the federation?

Group membership is dictated by the authentication provider, which in many cases is external to the cluster, and in many cases can does not provide APIs to resolve a user name to a set of groups.

**Comment by quinton-hoole** [comment] 2017-07-19 16:26
@liggitt Yes, I actually meant that the federation user should use that account (when creating the federated object against the federation API), and that the federation server should use whatever account the federation user used, when interacting with the clusters on behalf of the federation user.  Make sense?  

Regarding group membership, how does the cluster verify that the user (or in this case federation controller, impersonating the user) providing their own alleged group membership is not lying?  I think I need to read up more on how group membership is tracked.  It's not clear to me how we reconcile 'group membership is dictated by the authentication provider' with 'group membership is supplied by the impersonating account'.  If, when a cluster (or federation) authenticates a user against the authentication provider, it receives, in the response, the users group membership, then the federation would not need to track group membership (because it would be tracked by the authentication provider), right?

**Comment by jianhuiz** [comment] 2017-07-27 16:36
1. The user and groups are not verified. RBAC matches what ever user and groups against the rules.
Which means it could be any username (exists or not) and groups (belonged to or not, exist or not). authorizer assumes that they are correct since already authenticated. In case of impersonation, arbitrary user and groups can be provided.
2. username and groups (user.Info) are results of  a successful authentication. There seems no way to query the user, group structure, which means federation control plane has to store the entire user.Info, instead of just a user id (or user name), for impersonation when accessing underlying clusters. In order to avoid leaking user information, we may need an additional registry and api for the controllers to query such information.

@quinton-hoole @nikhiljindal

**Comment by quinton-hoole** [comment] 2017-09-08 02:43
@jianhuiz took this over - reassigned.  
Required for federation GA.  Prioritized accordingly.

**Comment by liggitt** [comment] 2018-01-05 15:31
closing federation-specific issues, can reopen in https://github.com/kubernetes/federation/issues/ if desired

**Closed by liggitt** 2018-01-05 15:31 UTC
Labels: area/apiserver, area/federation, area/logging, kind/design, priority/important-soon, sig/auth, sig/multicluster
