### ISSUE TITLE
support insert node labels to pod env

### ISSUE THREAD

**Issue by yangyefei90** [kubernetes/kubernetes#127149] opened 2024-09-05 12:54 UTC
# What would you like to be added?
support insert node labels to pod env
eg: node1 has labels kubernetes.io/rack=7-401-H-17 means the cabinet location of the node1 is 7-401-H-17
Pod can inject node labels into environment variables by setting annotations
eg:  pod.alpha.kubernetes.io/node-labels-to-env=kubernetes.io/rack
You can see kubernetes.io/rack=7-401-H-17 in the pod environment variable

# Why is this needed?
When we manage production nodes, we usually label the nodes with various characteristics, including rack information, network information, etc.
For pods in production environments, some business scenarios need to decide their own status and attributes after startup. At this time, they perceive the status of their own topology to actively establish a connection with the server. Some labels on the node can let the business know the location of the pod itself.
Injecting the node label into the pod's environment variables allows the pod to perceive its position in the topology by reading the environment variables, so as to better establish a connection with the server.

**Comment by bouaouda-achraf** [comment] 2024-09-05 14:39
Is it a good option:
- to propagate node information at the pod level?
- or is it better to let a 'Policy Management' solution, like [Kyverno](https://kyverno.io/), handle that use case?

**Comment by xuzhenglun** [comment] 2024-09-05 16:58
seem duplicated with https://github.com/kubernetes/kubernetes/issues/40610

**Comment by BenTheElder** [comment] 2024-09-05 18:57
Yeah, this seems like a duplicate of https://github.com/kubernetes/kubernetes/issues/40610

The downward api allows injecting metadata into pod env.

**Comment by neolit123** [comment] 2024-09-06 05:18
/sig node
/close
duplicate, please comment in the existing issue

**Closed by neolit123** 2024-09-06 05:18 UTC
Labels: sig/node, needs-triage
