### ISSUE TITLE
caBundle field of MutatingWebhookConfiguration can reference CA Cert's value from Configmap or Secret

### ISSUE THREAD

**Issue by developer-guy** [kubernetes/kubernetes#90401] opened 2020-04-23 10:31 UTC
**What would you like to be added**:
It would be nice if want to reference my CA Cert's value from Secret or ConfigMap for the "caBundle" field of MutatingWebhookConfiguration.
**Why is this needed**:
At this point, we need to create our CA Cert first because we need to set it to caBundle field, so there is no chance to edit the creation process of the certificate with Helm. I would like to do create my certificates via Secrets or Configmap first via using Helm Chart hooks then reference it from the "caBunlde" field of MutatingWebhookConfiguration. For example:

>      caBundle:
>         valueFrom:
>            configMap:
>               name: ca-cert-configmap
>               key:  ca.crt
or 
>      caBundle:
>         valueFrom:
>            secret:
>               name: ca-cert-secret
>               key:  ca.crt

**Comment by liggitt** [comment] 2020-04-23 19:24
thanks for the feature request. this is a duplicate of https://github.com/kubernetes/kubernetes/issues/72944

/close

**Closed** 2020-04-23 19:24 UTC
Labels: kind/feature, sig/cluster-lifecycle, wg/component-standard
