### ISSUE TITLE
csr approved than denied ，can not be approved again

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#90510] opened 2020-04-27 06:20 UTC
**What happened**:
```
root@master01 12certificate]# kubectl certificate approve  my-svc.my-namespace --force
certificatesigningrequest.certificates.k8s.io/my-svc.my-namespace approved
[root@master01 12certificate]# kubectl get csr
NAME                  AGE   REQUESTOR   CONDITION
my-svc.my-namespace   19m   admin       Denied,Issued
[root@master01 12certificate]# ^C
[root@master01 12certificate]# ^C
[root@master01 12certificate]# kubectl get csr
NAME                  AGE   REQUESTOR   CONDITION
my-svc.my-namespace   27m   admin       Denied,Issued
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@master01 12certificate]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2020-04-27 12:51
Approving, then denying a CSR is not an intended behavior, and is proposed to be disallowed in 1.19. See https://github.com/kubernetes/enhancements/pull/1691

/sig auth
/assign

**Comment by kbruner** [comment] 2020-06-01 07:40
Hello from the bug triage team! This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting June 25th (about 4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the issue is tagged for 1.19, is it still planned for this release?

**Comment by liggitt** [comment] 2020-06-01 13:50
yes https://github.com/kubernetes/kubernetes/pull/90191 is open to resolve this issue

**Closed** 2020-06-02 06:34 UTC
Labels: kind/bug, sig/auth
