### ISSUE TITLE
TestEventf is failing intermittently

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#9453] opened 2015-06-09 01:04 UTC
```
E0608 17:41:07.461082    9747 event.go:91] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo.13e5d41aaf1b6b5e", GenerateName:"", Namespace:"baz", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"baz", Name:"foo", UID:"bar", APIVersion:"version", ResourceVersion:"", FieldPath:""}, Reason:"Reason", Message:"retry1", Source:api.EventSource{Component:"eventTest", Host:""}, FirstTimestamp:util.Time{Time:time.Time{sec:63569382067, nsec:0x1b622d5e, loc:(*time.Location)(0x1149c20)}}, LastTimestamp:util.Time{Time:time.Time{sec:63569382067, nsec:0x1b622d5e, loc:(*time.Location)(0x1149c20)}}, Count:1}' (retry limit exceeded!)
```
Maybe related to v1beta1/2 removal: https://github.com/GoogleCloudPlatform/kubernetes/issues/8087#issuecomment-110182028

cc @saad-ali @krousey

**Comment by saad-ali** [comment] 2015-06-09 03:49
The `retry limit exceeded` looks like it is an expected part of a negative test. Can you link to logs showing the intermittent failure. I'll take a look.

**Comment by bgrant0607** [comment] 2015-06-09 13:35
One example:
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/65966544

Don't know if it's related, but I also see:
```
go build github.com/ugorji/go/codec: signal: killed
```

**Comment by krousey** [comment] 2015-06-09 16:04
The build being killed is likely travis running out of resources.

**Comment by saad-ali** [comment] 2015-06-09 23:48
Looks like the problem is:
```
  event_test.go:339: diff: (*api.Event){TypeMeta:(api.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(api.ObjectMeta){Name:(string)foo GenerateName:(string) Namespace:(string)baz SelfLink:(string) UID:(types.UID) ResourceVersion:(string) CreationTimestamp:(util.Time){Time:(time.Time){sec:(int64)0 nsec:(uintptr)<nil> loc:(*time.Location)<nil>}} DeletionTimestamp:(*util.Time)<nil> Labels:(map[string]string)<nil> Annotations:(map[string]string)<nil>} InvolvedObject:(api.ObjectReference){Kind:(string)Pod Namespace:(string)baz Name:(string)foo UID:(types.UID)bar APIVersion:(string)version ResourceVersion:(string) FieldPath:(string)desiredState.manifest.containers[2]} Reason:(string)Started Message:(string)some verbose message: 1 Source:(api.EventSource){Component:(string)eventTest Host:(string)} FirstTimestamp:(util.Time){Time:(time.Time){sec:(int64)0 nsec:(uintptr)<nil> loc:(*time.Location)<nil>}} LastTimestamp:(util.Time){Time:(time.Time){sec:(int64)0 nsec:(uintptr)<nil> loc:(*time.Location)<nil>}} Count:(int)
    
    A: 3}
    
    B: 2}
```
Haven't been able to repro it locally. Trying to understand why this happens.

**Comment by saad-ali** [comment] 2015-06-10 18:36
Ran `github.com/GoogleCloudPlatform/kubernetes/pkg/client/record` tests repeatedly back to back overnight, still no repro.

**Comment by saad-ali** [comment] 2015-06-10 21:26
The error indicates that the number of times the event was seen in the past (event compression) is less (`2`) than expected (`3`).

Possibilities considered:
* At 3rd occurrence of event, the previous occurrence was not found in LRU cache:
  * Maybe the key generated for the event to do LRU lookup is different between the 3 occurrences of the event.
    * Logs indicate this is not the case, the event object is identical all three times, and code ensures it computes keys off only immutable fields.
  * Also this can't be because logs show that Count is 2, meaning an entry was found, it just had the wrong count.
* After 2nd occurrence of event, the event LRU cache was not updated:
  * Maybe `sink.Create` or `sink.Update` failed on 2nd occurrence so LRU didn't get updated
    * No error in log to indicate this happened
    * Also the test code always returns `nil` for error on `sink.Create` and `sink.Update` so this is essentially impossible.
  * Maybe the event was evicted from the LRU cache, causing the 2nd occurrence to create a new entry, and 3rd to show count 2.
    * The logs show that this is not the case: test passes for the 2nd occurrence indicating at that point the cache contained the correct entry. If the entry was evicted after that, then the failure of the 3rd event would complain about not finding any entry (count would be `1` not `2`).
* Maybe something is running in parallel and messing up the entries in the cache
  * Even if the same test was running in parallel, because read/write is protected with a `RWMutex` at worst the count would end up higher then what we expect, not lower.

So I'm not sure what is causing this to happen.

I did notice a problem, the `events_cache` is a singleton, meaning all sinks created by `StartRecordingToSink` in `event.go` end up using the same LRU cache. That doesn't explain this problem, but should also be fixed. Opened #9610 to track that.

**Comment by bgrant0607** [comment] 2015-07-01 00:20
Thanks for taking a look. Removing from 1.0. If it can't be reproduced, we can close. If it increases in frequency, we can reevaluate priority and milestone.

**Comment by saad-ali** [comment] 2015-11-12 21:28
Closing this as obsolete: This code/tests has since been significantly modified.

**Closed by saad-ali** 2015-11-12 21:28 UTC
Labels: area/test, kind/bug, priority/P2, team/CSI
