### ISSUE TITLE
How to expose PetSet/Pet externally

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#31663] opened 2016-08-30 01:33 UTC
PetSet use a headless service to manage its second domain records. But the headless service cannot be exposed externally.

So in order to expose the `PetSet`, the way I could think of is to create another **Service** (via NodePort/LoadBalancer/etc.). Not sure if it's the best way. Any comments are appreciated.

Another concern in my mind is: what if I only want to expose specific `Pet(s)`? Suppose index 0 is the master, how can I proceed to expose the `master pet` only?

**Comment by bprashanth** [comment] 2016-08-30 05:19
you can use a loadbalancer like haporxy, see https://github.com/kubernetes/kubernetes/issues/28660#issuecomment-241547634, closing as a dupe of that issue

**Closed by bprashanth** 2016-08-30 05:19 UTC
Labels: component/apiserver, team/cluster
