### ISSUE TITLE
unittest flake: "TestForwardPorts" is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#17660] opened 2015-11-23 14:28 UTC
I1123 15:24:46.038490   10450 portforward.go:213] Forwarding from localhost:12345 -> 12345
    I1123 15:24:46.038645   10450 portforward.go:213] Forwarding from 127.0.0.1:12345 -> 12345
    I1123 15:24:46.038702   10450 portforward.go:213] Forwarding from [::1]:12345 -> 12345
    E1123 15:24:46.038754   10450 portforward.go:202] Unable to create listener: Error listen tcp4 [::1]:12345: non-IPv4 address <nil>
    E1123 15:24:46.038794   10450 portforward.go:202] Unable to create listener: Error listen tcp6 127.0.0.1:12345: bind: invalid argument
    E1123 15:24:46.038812   10450 portforward.go:202] Unable to create listener: Error listen tcp6: too many colons in address ::1:12345
    I1123 15:24:46.039705   10450 portforward.go:213] Forwarding from 127.0.0.1:5000 -> 5000
    I1123 15:24:46.041335   10450 portforward.go:213] Forwarding from [::1]:5000 -> 5000
    I1123 15:24:46.042492   10450 portforward.go:213] Forwarding from 127.0.0.1:5001 -> 5001
    I1123 15:24:46.042528   10450 portforward.go:213] Forwarding from [::1]:5001 -> 5001
    I1123 15:24:46.042555   10450 portforward.go:213] Forwarding from 127.0.0.1:6000 -> 6000
    I1123 15:24:46.042582   10450 portforward.go:213] Forwarding from [::1]:6000 -> 6000
    I1123 15:24:46.042740   10450 portforward.go:247] Handling connection for 6000
    I1123 15:24:46.044774   10450 portforward.go:247] Handling connection for 5001
    --- FAIL: TestForwardPorts (0.02s)
            portforward_test.go:270: forward 2 ports with bidirectional data: server expected to receive "abcd", got "" for port 5001
    E1123 15:24:46.063246   10450 portforward.go:303] error copying from local connection to remote stream: write tcp 127.0.0.1:58015->127.0.0.1:33307: write: broken pipe
    I1123 15:24:46.063663   10450 portforward.go:213] Forwarding from 127.0.0.1:5555 -> 5555
    I1123 15:24:46.063704   10450 portforward.go:213] Forwarding from [::1]:5555 -> 5555
    E1123 15:24:46.064087   10450 portforward.go:202] Unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use
    E1123 15:24:46.064126   10450 portforward.go:202] Unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use
    W1123 15:24:46.064144   10450 portforward.go:154] Unable to listen on port 5555: All listeners failed to create with the following errors: listen tcp4 127.0.0.1:5555: bind: address already in use, listen tcp6 [::1]:5555: bind: address already in use
    FAIL
    FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	0.222s

**Comment by wojtek-t** [comment] 2015-11-23 16:17
@kubernetes/goog-testing

**Comment by mikedanese** [comment] 2015-11-23 19:27
@ncdc

**Comment by ncdc** [comment] 2015-11-23 19:30
Dupe of #16394

**Closed by ncdc** 2015-11-23 19:30 UTC
Labels: area/test, kind/flake, priority/P1, team/cluster
