### ISSUE TITLE
AWS Multiple-AZ Fails to Start Up and Register Nodes on Second AZ

### ISSUE THREAD

**Issue by druidsbane** [kubernetes/kubernetes#21877] opened 2016-02-24 14:25 UTC
Bringing up a cluster using the new Multiple-AZ Support fails on AWS.  The first part of the cluster comes up but we fail on bringing up the second set of nodes.  Below is the config to start up:

```
# this part succeeds
export KUBERNETES_PROVIDER=aws
KUBE_AWS_ZONE=us-west-2a kube-up.sh

# this command fails with: Could not detect Kubernetes master node IP.  Make sure you've launched a cluster with 'kube-up.sh'
KUBE_AWS_ZONE=us-west-2b KUBE_SUBNET_CIDR=172.20.1.0/24 KUBE_USE_EXISTING_MASTER=true kube-up.sh
```

And here is the log of the failure to bring up the second set of nodes:
```
Creating autoscaling group
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 2 minions started; ready
Sanity checking cluster...
Attempt 1 to check Docker on node @ <someIP> ...not working yet
Attempt 2 to check Docker on node @ <someIP> ...not working yet


Attempt 3 to check Docker on node @ <someIP> ...not working yet
Attempt 4 to check Docker on node @ <someIP> ...not working yet
Attempt 5 to check Docker on node @ <someIP> ...not working yet
Attempt 6 to check Docker on node @ <someIP> ...not working yet


Attempt 7 to check Docker on node @ <someIP> ...not working yet
Attempt 8 to check Docker on node @ <someIP> ...not working yet
Attempt 9 to check Docker on node @ <someIP> ...not working yet
Attempt 10 to check Docker on node @ <someIP> ...not working yet
Attempt 11 to check Docker on node @ <someIP> ...not working yet

Your cluster is unlikely to work correctly.
Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
```

**Comment by rata** [comment] 2016-03-15 03:48
Hi, just curious: is it expected that multi AZ kubernetes cluster on AWS will make it to v1.2?

**Comment by justinsb** [comment] 2016-03-15 14:41
@rata: yes.  WIP docs should now work with master (and possible beta.1)... https://github.com/kubernetes/kubernetes/pull/20044  I'm working on polishing these up to be less WIP!

**Comment by rata** [comment] 2016-03-16 00:08
@justinsb that's great, thanks!

**Comment by druidsbane** [comment] 2016-03-17 17:40
FYI, still seeing problem in final 1.2 release:
```
Could not detect Kubernetes master node IP.  Make sure you've launched a cluster with 'kube-up.sh'
```

**Comment by justinsb** [comment] 2016-03-17 18:22
@druidsbane can you open a new issue with details on what you saw and any hints on how to reproduce (e.g. any env variables you are setting prior to running kube-up)?  Thanks!

**Comment by druidsbane** [comment] 2016-03-18 13:44
Created issue: #23188

**Comment by quinton-hoole** [comment] 2016-03-28 17:08
Duplicate of #23188

**Closed by quinton-hoole** 2016-03-28 17:08 UTC
Labels: area/platform/aws, kind/documentation, priority/P1, team/sig-aws
