### ISSUE TITLE
After k8s upgrade, ETCD landed in different versions

### ISSUE THREAD

**Issue by mjrepo2** [kubernetes/kubernetes#93644] opened 2020-08-03 08:54 UTC
**What happened**:
kubernets etcd version are different from each other (1 out of 3) after upgrade from v1.17.6 to v1.18.3

**What you expected to happen**:
kubernetes to hold the versions in sync, that they continue to work together.

**How to reproduce it (as minimally and precisely as possible)**:
Unknown -- behavior is seen after upgrading k8s components from v1.17.6 to v1.18.3

**Anything else we need to know?**:
Stacked etcd cluster, 3 Master environment.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: baremetal

- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel (e.g. `uname -a`): Linux wmd-kub01 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): quay.io/coreos/flannel:v0.10.0-amd64

```
wmd@wmd-kub01:~$ kubectl get po -n kube-system -oyaml | grep etcd | grep image
      image: k8s.gcr.io/etcd:3.4.3-0
      image: k8s.gcr.io/etcd:3.4.3-0
      imageID: docker-pullable://k8s.gcr.io/etcd@sha256:4afb99b4690b418ffc2ceb67e1a17376457e441c1f09ab55447f0aaf992fa646
      image: k8s.gcr.io/etcd:3.3.10
      image: k8s.gcr.io/etcd:3.3.10
      imageID: docker-pullable://k8s.gcr.io/etcd@sha256:17da501f5d2a675be46040422a27b7cc21b8a43895ac998b171db1c346f361f7
      image: k8s.gcr.io/etcd:3.3.10
      image: k8s.gcr.io/etcd:3.3.10
      imageID: docker-pullable://k8s.gcr.io/etcd@sha256:17da501f5d2a675be46040422a27b7cc21b8a43895ac998b171db1c346f361f7

```

Cluster-info dump with appropriate error message:

```
2020-07-13 03:36:18.392782 W | etcdserver: member 3eace3fdc728b049 has a higher version 3.4.3
2020-07-13 03:36:22.394854 W | etcdserver: the local etcd version 3.3.10 is not up-to-date
2020-07-13 03:36:22.394892 W | etcdserver: member 3eace3fdc728b049 has a higher version 3.4.3
2020-07-13 03:36:26.396720 W | etcdserver: the local etcd version 3.3.10 is not up-to-date
2020-07-13 03:36:26.396757 W | etcdserver: member 3eace3fdc728b049 has a higher version 3.4.3

```

If I should provide any other required information please let me know.

Also, how would I go about triggering an update to k8s etcd, in cases like this?
We have never had to manually tinker with k8s etcd, since k8s controls it itself as far as I am aware.
Thanks!

**Comment by neolit123** [comment] 2020-08-03 10:23
> kubernetes to hold the versions in sync, that they continue to work together.

this seems like an administration issue.
each version of kubernetes usually comes with a different version of etcd.

> Install tools: kubeadm

are you using an external or stacked etcd cluster?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/

> Also, how would I go about triggering an update to k8s etcd, in cases like this?

for stacked, if you are using `kubeadm upgrade` you should call the command on all control-plane nodes.
for external, kubeadm does not manage the etcd upgrade for you, so you must go on each etcd node and upgrade the etcd server instance [manually](https://etcd.io/docs/v3.3.12/upgrades/upgrade_3_4/).

/remove-kind bug
/triage support
/sig cluster-lifecycle

**Comment by neolit123** [comment] 2020-08-03 10:24
> 2020-07-13 03:36:18.392782 W | etcdserver: member 3eace3fdc728b049 has a higher version 3.4.3

one of the etcd members has a newer version, so it seems like the etcd member upgrade was not completed.

**Comment by dk-do** [comment] 2020-08-03 10:26
Yes - looks same for me.
But how to fix this when the builtin K8S etcd is used?

**Comment by neolit123** [comment] 2020-08-03 10:27
> builtin K8S etcd is used

do you mean "stacked" etcd?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/

if you are using "stacked" etcd. you can use `kubeadm upgrade plan/apply`.

**Comment by neolit123** [comment] 2020-08-03 10:28
please read this carefully: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by dk-do** [comment] 2020-08-03 10:32
@neolit123 

Yes - we are using stacked etcd.

> please read this carefully: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

This is exactly what we did...
Can we just run the update on the remaining masters again?

**Comment by neolit123** [comment] 2020-08-03 10:35
> This is exactly what we did...

i doubt if `kubeadm upgrade` was run on all control-plane nodes that it did not upgrade etcd too.

> Can we just run the update on the remaining masters again?

you could try. using `kubeadm upgrade apply` would be better.
alternatively you can go on each /etc/kubernetes/manifests/etcd.yaml file and upgrade the etcd image version.

**Comment by neolit123** [comment] 2020-08-03 10:38
hope you get it fixed, i'm going to close this as it seems like a support ticket and not a bug / FR.

to get discussions with users that are already using kubeadm you can use #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Closed** 2020-08-03 10:38 UTC
Labels: sig/cluster-lifecycle, triage/support
