### ISSUE TITLE
kubectl run doesn't follow rules for `--`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13004] opened 2015-08-21 00:36 UTC
kubectl run --restart=Never --image=gcr.io/google_containers/busybox --command -- sleep 600

should either error (no name) or make up a name and set command to `["sleep", "600"]`.  It does neither, turning sleep into the pod name and making command 600.  `--` is supposed to define extra arguments.

**Comment by feihujiang** [comment] 2015-09-03 08:49
I checked this unexpected output, I found there is no separation between the name and extra arguments, just use the first argument as the name.  Maybe we could use --name to set name like docker run , or stick to use -- to define extra arguments (a little difficult to implement,  because -- is eated by cobra commander)?  @smarterclayton @bgrant0607 @brendandburns  What's your point?

**Comment by bgrant0607** [comment] 2015-09-03 16:33
Does exec behave differently?
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go#L56

**Comment by bgrant0607** [comment] 2015-09-03 16:35
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run.go#L57

Yes, exec doesn't have a --command flag, which is nicer (and works correctly):
```
$ kubectl exec 123456-7890 -c ruby-container -i -t -- bash -il
```

**Comment by feihujiang** [comment] 2015-09-03 22:49
I think the exec has the same problem too. $ kubectl exec  -c ruby-container -i -t -- bash  aaa, also use bash as the pod name. and aaa as the command

**Comment by smarterclayton** [comment] 2015-09-15 03:27
This is definitely a severe limitation in how arguments are handled - the
calling cobra command needs to be able to distinguish between the two
syntaxes.  Not sure what the best way is to fix this - @eparis may have
some strong opinions since he's been in a lot of this code.

On Thu, Sep 3, 2015 at 6:49 PM, feihujiang <notifications@github.com> wrote:

> I think the exec has the same problem too. $ kubectl exec -c
> ruby-container -i -t -- bash aaa, also use bash as the pod name. and aaa as
> the command
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13004#issuecomment-137594611>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by eparis** [comment] 2015-09-15 03:56
I'll try to give it some brain cycles tomorrow.  I have none right now.

**Comment by brendandburns** [comment] 2015-09-15 12:52
The problem is in cobra afaik.  When I looked into this, the `--` is gone after arg parsing.

**Comment by eparis** [comment] 2015-09-15 14:11
I don't see how we blame cobra or any parsing library...  Both python flag parsing and getopts(3) would do the same thing. We have multiple arguments which are unnamed. The `--` tells flag parsing its job is done and it should just dumps everything after the `--` in `args`. The ambiguity is 100% of our making.

I'm trying to understand what we believe the 'syntax' is. Things that work today
1. `kubectl run --image=busybox --command mycontainer echo "hello there"`
2. `kubectl run --image=busybox --command mycontainer -- echo "hello there"`
3. `kubectl run --image=busybox --command -- mycontainer echo "hello there"`

The patch in https://github.com/kubernetes/kubernetes/issues/13917 would cause numbers 1 and 3 to stop working, even though they work just fine today. Although @smarterclayton user error would get caught by the patch and we could give an intelligent error message...

The only 'good' fix from a correctness PoV that I can think of is to make the `mycontainer` an argument instead of it being unnamed...

(`SetInterspersed` is definitely not the right thing here, as the `mycontainer` can live anywhere in the arguments...)

**Comment by eparis** [comment] 2015-09-15 15:30
As I think more and more, I'm really starting to think we should just force `--name=` (or something similar)   We can leave the ambiguity as it is today.  There I can't think of anything in our docs, our parsers, or the years of using linux command lines that would make it normal that someone the left side of `--` is different than the right side. The best example I can think of is `git log`

```console
$ git grep log containerized README.md
fatal: ambiguous argument 'containerized': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
$ git grep log -- containerized README.md
```

Which is different than our situation in that the git `--` forces all unnamed args into our equivalent of `command` not that it ever requires an unnamed arg to the left. In this case the unnamed arg is optional. I'm trying to find something that allows required unnamed arguments and doesn't blow up if the user forgets them...

**Comment by bgrant0607** [comment] 2015-10-05 22:21
Have we decided what to do about this, if anything?

**Comment by feihujiang** [comment] 2015-10-06 10:46
@bgrant0607 Yes，we have decided. Once #14922 merged, I'll finish this as quickly as possible. and now I'm on a vacation, will be back to work the day after tomorrow.

**Comment by bgrant0607** [comment] 2015-10-08 05:22
Thanks. It would be great to also confirm whether or not #10838 is still an issue or can be closed.

**Closed** 2015-11-20 08:13 UTC
Labels: area/usability, component/kubectl, priority/P1, team/ux
