### ISSUE TITLE
Add gce-slow suite to the merge queue blockers

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17933] opened 2015-11-30 09:13 UTC
There are few important tests in this suite so I believe it would be useful to add it to blockers. We need to deflake it first though:
- #17518
- #17781

cc @ixdy @smarterclayton @brendandburns @wojtek-t @wonderfly

**Comment by wojtek-t** [comment] 2015-11-30 09:18
@eparis @lavalamp

**Comment by wojtek-t** [comment] 2015-11-30 09:18
@kubernetes/goog-testing

**Comment by wojtek-t** [comment] 2015-11-30 14:13
Although - this suite is pretty unstable now. So we should clear it up, before doing it.

**Comment by eparis** [comment] 2015-11-30 14:51
/me objects to adding more flaky tests. If not for the US holiday late last week we'd still be buried in PRs. I probably should put some thought into @lavalamp 's 'shame' report. https://github.com/kubernetes/contrib/pull/274

**Comment by wojtek-t** [comment] 2015-11-30 14:55
We definitely shouldn't add more flaky tests to it.

The rationale behind it is that we are running some __very important__ tests as part of gce-slow and anywhere else.
gce-slow shouldn't be a suite where we put tests that are flaky (those should be put into flake). gce-slow is a regular suite that is supposed to be green all-the-time, but it contains tests that can take significant time by their nature

**Comment by ihmccreery** [comment] 2015-11-30 17:15
@krousey was talking last week about problems with suites that were too slow to recover, simply because they took hours to run, even once fixed.  E.g. if a test in a suite that takes 4 hours to run, that's 4 hours before we can start merging again.  Perhaps an important consideration.

**Comment by gmarek** [comment] 2015-11-30 17:59
The question is if it's better to block the queue or miss a regression. Currently my feeling is that no one cares about tests that are not blocking the build.

**Comment by krousey** [comment] 2015-11-30 18:07
You mention that there are a few important tests in this suite. Perhaps we should pull only the important ones in instead of the entire slow suite. Also, we should look in how to speed them up.

The problem I had last week was a lot of low-rate one-off flakes combined with suites that took 2+ hours to run. So one or two flakes disabled merges for most of the working day.

Ideally we wouldn't have flakes and this wouldn't be that big of an issue.

**Comment by wojtek-t** [comment] 2015-11-30 18:17
I believe all of them are important - so we should just remove the flaky tests to gce-flaky and add slow to be blocker of merge-queue.

I agree with the objection that having long suites may block merge-bot for a long time. But exactly this should be motivation for fixing flaky ones. 

__And the real problem is not that we have long suites, but that almost noone cares about failing tests.__

**Comment by krousey** [comment] 2015-11-30 18:29
**There isn't only one real problem. There are several here.** People not caring about test failures is likely because they flake so often. Fixing that will help that issue.

Even with 0 flakes, long suites are a problem. When they fail, they delay detection time. So hours could pass before we know a commit is bad. Other commits could come in on top of this that make it non-trivial to roll back. Even if we do roll it back in 10 minutes, the suite has already restarted and will have to complete (fail) again, pick up the fix, then re-run to pass and unblock the submit queue.

In the end, I'm not saying don't add these. I'm just saying let's also try to reduce the MTTR. If there's a way to speed these up (rework the test logic, shard them, ...), we should do it.

**Comment by wojtek-t** [comment] 2015-11-30 18:34
>
Even with 0 flakes, long suites are a problem. When they fail, they delay detection time. So hours could pass before we know a commit is bad. Other commits could come in on top of this that make it non-trivial to roll back. Even if we do roll it back in 10 minutes, the suite has already restarted and will have to complete (fail) again, pick up the fix, then re-run to pass and unblock the submit queue.

That's not true. If you are reverting someting - we can simply restart the jenkins suite manually and avoid 2 hours of lost work.

Also, note that most of tests are not flaky at all - so it's possible to do it.
So once we are there, I don't think it's a problem of regressions. Regressions are rare - and I think that even if we have say 2 regressions per week, loosing say 10 hours per week of merging is not a disaster and we can definitely leave with that.

So I really think that the problem are flaky tests - not long suites.

**Comment by quinton-hoole** [comment] 2015-11-30 18:37
@krousey 
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L194
# The following tests are known to be slow running (> 2 min), and are
# thus run only in their own -slow- build variants.  Note that tests
# can be slow by explicit design (e.g. some soak tests), or slow
# through poor implementation.  Please indicate which applies in the
# comments below, and for poorly implemented tests, please quote the
# issue number tracking speed improvements.

**Comment by krousey** [comment] 2015-11-30 18:53
> So I really think that the problem are flaky tests - not long suites.

@wojtek-t What I've been trying to say is that this is **not** an either/or situation. It's both. And I agree the flakes are the worse part of it. I don't mean to hijack this entire issue with this discussion. I was just asking if something was being done with regards to test time instead of just turning a blind eye to it.

@quinton-hoole Thanks. This is what I wanted to see. Just curious, is there any consideration of overall suite times? Getting individual test times quick helps, but if you have 200+ tests that take 30 seconds each, you're still running that single suite for over an hour. Looking at the builds that can block the merge queue right now, 5 of the suites take ~1 hour or more. At least 2 of them took more than 2 hours.

**Comment by wojtek-t** [comment] 2015-11-30 19:37
@krousey - I agree that we should try to make those tests quicker. But I think the more important for now is to eliminate flakes. Once we're done with that, we can make tests better by making them faster. But I think we're not there yet.

@quinton-hoole @lavalamp ^^

**Comment by lavalamp** [comment] 2015-11-30 20:26
I'm going to use kubernetes/contrib#274 to spam googlers owning flaky tests every day. Adding the "kind/flake" label to an issue will cause this treatment. Hopefully, just filing a P1/P0 issue about a flaky test will get it fixed in O(days) now.

**Comment by gmarek** [comment] 2015-12-01 10:06
FYI: 'slow' suite is indeed slower than other ones but it's an order of 40% not few times:
- slow: 2h50m
- autoscaling: 2h9m
- scalability: 2h4m
- gke-ci: 1h49m

**Comment by wojtek-t** [comment] 2015-12-01 10:19
So it's better than it used to be - I remember both gce and gke exceeding 2 hours.

**Comment by quinton-hoole** [comment] 2015-12-01 16:07
A little bit of history about the slow tests, to provide some context, in case it's useful...

1. There are only 11 tests in "e2e-gce-slow", which currently take around 2h50m to run in serial (i.e. avg 15.5 minutes each)
2. There are 129 tests in "e2e-gce", which take 1h20m to run (i.e. avg 0.6 min each).

So as you can see, moving 11 of the 140 tests into the "slow" bucket, speeds up the run of the rest from 4h10m to 1h20m.

**Comment by eparis** [comment] 2015-12-01 16:14
Can we just parrallelize slow? Break it in half. Get each half down to like 1:30 ?

**Comment by wojtek-t** [comment] 2015-12-01 17:31
Some of them are parallelizable, some are not...

**Comment by eparis** [comment] 2015-12-01 17:34
I was thinking can we make a gce-slow-1 and a gce-slow-2

**Comment by quinton-hoole** [comment] 2015-12-01 17:43
Yeah, that makes sense to me.  It will definitely speed things up a bit, at the expense of some configuration and cognitive complexity.  "gce-slow-parallel" perhaps?

**Comment by ixdy** [comment] 2016-02-04 00:27
gce-slow and gke-slow are now blocking the SQ, so marking this fixed.

**Closed by ixdy** 2016-02-04 00:27 UTC
Labels: area/test, priority/P1, team/test-infra
