### ISSUE TITLE
kubectl 1.5.1 vs k8s 1.6 gives `error: no kind "Deployment" is registered for version "apps/v1beta1"`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#42392] opened 2017-03-02 06:17 UTC
```
>  ~/bin/kubectl-1.5.1 edit deployment -n kube-system dns-controller
error: no kind "Deployment" is registered for version "apps/v1beta1"
```

```
> ~/bin/kubectl-1.5.1 version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.661+01bfbb5fa04621", GitCommit:"01bfbb5fa0462189932b704be32401822a991627", GitTreeState:"clean", BuildDate:"2017-03-02T01:45:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment] 2017-03-02 07:12
prior to 1.6, kubectl cannot edit unknown kinds (fixed in https://github.com/kubernetes/kubernetes/pull/41304)

you should be able to edit the deployment in the extensions group like `~/bin/kubectl-1.5.1 edit deployment.extensions -n kube-system dns-controller`

**Comment by liggitt** [comment] 2017-03-02 07:13
@kubernetes/sig-cli-bugs

**Comment by justinsb** [comment] 2017-03-02 15:33
`~/bin/kubectl-1.5.1 edit deployment.extensions -n kube-system dns-controller` does work

I don't know if this portends some other areas of incompatibility (`get deployments` works though).  If not though, then if this is fixed in kubectl 1.6, then a release-note or similar to encourage people to upgrade kubectl seems like a reasonable fix (though we should then make sure that kubectl 1.6 works with older clusters!).  Thanks @liggitt !

**Comment by liggitt** [comment] 2017-03-02 15:36
`kubectl get` was converted to read objects from the server in unstructured form before `edit` and `apply` were. The linked PR has release notes in it.

**Comment by kargakis** [comment] 2017-03-03 18:39
@soltysh

**Comment by soltysh** [comment] 2017-03-03 20:43
Additionally k8s 1.6 will (hopefully) get the move where Deployments are additionally available under `apps/v1beta1`. Only newer `kubectl` like @liggitt mentioned will be able to handle this properly.

**Comment by pwittrock** [comment] 2017-03-05 21:21
@justinsb What is the bug to be fixed for 1.6?

**Comment by justinsb** [comment] 2017-03-05 21:28
@pwittrock not sure of the procedure in terms of tagging, but:

* `~/bin/kubectl-1.5.1 edit deployment -n kube-system dns-controller` does not work against 1.6 clusters, did work against 1.5 clusters.
* kubectl 1.5 CLI features are supposed to be compatible for at least 3 months and at least 1 release after their announced deprecation, per https://kubernetes.io/docs/deprecation-policy/ (?).
* And no deprecation has yet been announced (?)

**Comment by pwittrock** [comment] 2017-03-05 21:37
@janetkuo Is this due to the Deployment version changing?

**Comment by pwittrock** [comment] 2017-03-05 22:31
#41656 is similar

**Comment by liggitt** [comment] 2017-03-06 03:32
it's due to deployments additionally being available in the apps group. deployments in the extensions group still exist and are usable, but are no longer the preferred group.

most kubectl commands (get, update, replace, etc) handle either group equally well. the 1.5 versions of commands that were converted to use generic objects in 1.6 would not handle deployments in the apps group, and would require explicitly using the extensions group (e.g. `kubectl edit deployment.extensions dns-controller -n kube-system`)

**Comment by pwittrock** [comment] 2017-03-06 17:00
@janetkuo Is there something we can do to improve this experience?

**Comment by pwittrock** [comment] 2017-03-06 17:12
Also filed here: #42561  Looks like it impacts node as well.

**Comment by liggitt** [comment] 2017-03-06 17:18
that's a different issue, likely due to caching of bad discovery docs

**Comment by kargakis** [comment] 2017-03-06 23:15
@liggitt is this a dupe of https://github.com/kubernetes/kubernetes/issues/40813

**Comment by caesarxuchao** [comment] 2017-03-06 23:19
No, it's not a dupe of 40813. 40813 is for kubectl built from head and 1.5 server.

**Comment by soltysh** [comment] 2017-03-07 09:55
I've spoke with @liggitt yesterday more, and apparently there's nothing we can do for 1.5 to fix it. This was fixed properly in https://github.com/kubernetes/kubernetes/pull/41304 like Jordan mentioned. The only question is if we want to cherry-pick that fix (I'd say no - it's way too big to be safely backported). Thankfully there's a simple fix, by appending group to resource name. Although I might be missing something here, so I'm open to suggestions.

**Comment by pwittrock** [comment] 2017-03-07 16:57
@soltysh What can we do to mitigate the user experience fallout?  As I understand it, when users upgrade their master, `kubectl edit deployment` will just stop working with no further explanation to indicate that the user needs to append the group.  We definitely will need to update the release notes section "known issues and incompatibilities".

**Comment by kargakis** [comment] 2017-03-07 17:00
There is also the alternative of reverting https://github.com/kubernetes/kubernetes/pull/39683 and moving it to 1.7 (IIUC, kubectl 1.6 won't have this problem with 1.7 clusters).

**Comment by liggitt** [comment] 2017-03-07 17:06
> There is also the alternative of reverting #39683 and moving it to 1.7 (IIUC, kubectl 1.6 won't have this problem with 1.7 clusters).

Every user using deployments faces the problem of ever-increasing replicasets, which #39683 fixes. Some users face the problem of a 1.5.x kubectl being unable to edit.

**Comment by pwittrock** [comment] 2017-03-07 17:15
@liggitt @fabianofranz @AdoHe   Perhaps we need to revisit out commitment to supporting skewed / client server.  We consistently fail to meet this commitment, and I would rather tell users they need to match the client / server version than have things break when we tell them that client / server version skew is supported.  WDYT?

**Comment by kargakis** [comment] 2017-03-07 17:29
> Every user using deployments faces the problem of ever-increasing replicasets, which #39683 fixes. Some users face the problem of a 1.5.x kubectl being unable to edit.

The truth is that both cleanup and a sane maxUnavailable by default are huge ux wins. I guess there is a trade-off we need to make here. To be fair, nothing stops users that stumble across the issue of many replica sets to set the field in their deployments.

**Comment by liggitt** [comment] 2017-03-07 17:47
> To be fair, nothing stops users that stumble across the issue of many replica sets to set the field in their deployments.

Unless they do it using kubectl 1.5.x `apply` or `edit`, which drop unknown API fields :)

**Comment by kargakis** [comment] 2017-03-07 21:10
But there is no unknown field for 1.5 clients for Deployments.

**Comment by soltysh** [comment] 2017-03-08 13:40
> and I would rather tell users they need to match the client / server version than have things break when we tell them that client / server version skew is supported. WDYT?

I'd say it's strongly advised to do so and we do our best to keep to support skewed versions. Hopefully the big fix from @liggitt will allow us to actually make it more accurate starting from kubectl 1.6 :)

**Comment by fabianofranz** [comment] 2017-03-08 20:06
> @liggitt @fabianofranz @AdoHe Perhaps we need to revisit out commitment to supporting skewed / client server. We consistently fail to meet this commitment, and I would rather tell users they need to match the client / server version than have things break when we tell them that client / server version skew is supported. WDYT?

@pwittrock probably needs broader discussion but I'd be in favor. You'd still support skew of point releases (e.g. kubectl 1.6.1 --> server 1.6.0, etc)?

**Comment by pwittrock** [comment] 2017-03-09 17:05
@soltysh I think strongly advising that users match the kubectl / apiserver version makes a lot of sense.

**Comment by soltysh** [comment] 2017-03-09 20:36
Yeah, doing what @fabianofranz said is probably the best option, strongly advising major version and keeping full compatibility in minor, is doable.

**Comment by AdoHe** [comment] 2017-03-12 03:36
```
strongly advising major version and keeping full compatibility in minor
```
This is quite a big change, which means we may need to suggest user to upgrade binary more clearly, e.g print out `version skew, please upgrade` when use older version client against newer version server.

**Comment by liggitt** [comment] 2017-03-13 00:28
It definitely affects some commands more than others (and as we improve at making commands work generically, more and more work across broader skew)

**Comment by kargakis** [comment] 2017-03-13 00:56
We may be able to confidently say in the future that we support version
skew but it doesn't seem to be the case today.

**Comment by bgrant0607** [comment] 2017-03-14 16:20
The reality is that kubectl doesn't support version-skewed operation well today. This dates back to the beginning, from before we had Swagger support, the dynamic client, etc.: #3955.

However, we absolutely need to make version-skewed operation a goal.

**Comment by bgrant0607** [comment] 2017-03-14 16:22
Also, the stated level of compatibility is one minor release.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/versioning.md#supported-releases-and-component-skew

**Comment by justinsb** [comment] 2017-03-16 06:30
Having multiple kubernetes clusters versions that you are using is definitely a reality, and it is really annoying to have to keep around multiple kubectl versions and remember use the right one.  We don't want a "kubectl version manager"...

It does sound like we are getting better here, and will continue to do as we move more to the server.  I'd really rather we focused on getting better.  We do a great job of not breaking applications that use the API, so I think we can get there with kubectl.

**Comment by adohe** [comment] 2017-03-16 13:13
```
We don't want a "kubectl version manager"...
```
This is exactly what we should avoid. I believe.

**Comment by adohe** [comment] 2017-03-16 13:15
@pwittrock @fabianofranz also as what @bgrant0607 suggested in last SIG-CLI meeting, I would hope we can put more effort on version skew issues, and to make a better kubectl. wdyt?

**Comment by justinsb** [comment] 2017-03-16 13:50
(I also acknowledge that we have to be pragmatic.  If it's hard to fix and this one goes out as-is with a release-note, that's OK by me...)

**Comment by liggitt** [comment] 2017-03-16 14:16
> it is really annoying to have to keep around multiple kubectl versions and remember use the right one

agree, and pushing hard on backwards compatibility (new kubectl -> old server) would help with that.

**Comment by kensimon** [comment] 2017-03-22 17:00
Also noticing this even when the deployment is initially created by a 1.5.x client:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.4", GitCommit:"b202120be3a97e5f8a5e20da51d0b6f5a1eebd31", GitTreeState:"clean", BuildDate:"2017-03-17T17:42:22Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl run nginx --image=nginx
deployment "nginx" created
$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-2371676037-zrwfh   1/1       Running   0          15s
$ kubectl expose deployment nginx --port 80 --type=LoadBalancer
error: no kind "Deployment" is registered for version "apps/v1beta1"
```

And it's not just `kubectl edit` but other things that read the deployment in (in this case `kubectl expose`.)

**Closed** 2017-03-23 19:45 UTC
Labels: kind/bug, priority/critical-urgent, release-blocker, sig/api-machinery, sig/cli
