### ISSUE TITLE
vSphere API outage will bring a Kubernetes cluster down

### ISSUE THREAD

**Issue by robdaemon** [kubernetes/kubernetes#42338] opened 2017-03-01 16:48 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Kubernetes version** (use `kubectl version`):

1.5.2

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

vSphere 6.0
Ubuntu 14.04.3

**What happened**:

When vCenter is taken offline for maintenance, the entire Kubernetes cluster will go offline because it can no longer communicate with vCenter.

**What you expected to happen**:

The cluster should stay online, but not perform any changes.

**How to reproduce it** (as minimally and precisely as possible):

Take the vCenter API offline, observe cluster behavior.

**Anything else we need to know**:

The vCenter API is not considered to be HA, but Kubernetes seems to require that the cloud provider operate in an HA fashion.

**Comment by robdaemon** [comment] 2017-03-01 16:48
@kerneltime - I know this is not a small undertaking, but at a customer request, I'd like to talk about this.

**Comment by kerneltime** [comment] 2017-03-02 17:23
@robdaemon I don't think this is vSphere specific.. any backend api if down should bring down kubernetes.

**Comment by kerneltime** [comment] 2017-03-02 17:25
duplicate of https://github.com/kubernetes/kubernetes/issues/34364

**Comment by divyenpatel** [comment] 2017-03-24 22:50
Tried to see the behavior with bringing down VPXD.

```
# service-control --stop vmware-vpxd
Perform stop operation. vmon_profile=None, svc_names=['vmware-vpxd'], include_coreossvcs=False, include_leafossvcs=False
Successfully stopped service vpxd
```

Verified Cluster Health.

```
$ kubectl cluster-info
Kubernetes master is running at https://10.160.11.203
Heapster is running at https://10.160.11.203/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.160.11.203/api/v1/proxy/namespaces/kube-system/services/kube-dns
```

Observed pod is running.

```
$ kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
thinclaimpod   1/1       Running   0          4m
```

and able to get into container running within pod.

```
$ kubectl exec -it thinclaimpod /bin/sh
/ # date
Fri Mar 24 22:44:50 UTC 2017
/ # hostname
thinclaimpod
/ # exit
```

**Comment by kargakis** [comment] 2017-06-20 17:46
> duplicate of #34364

**Closed by kargakis** 2017-06-20 17:46 UTC
Labels: area/platform/vsphere, needs-sig
