### ISSUE TITLE
Cluster failed to initialize on GCE

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#22842] opened 2016-03-11 06:46 UTC
I tried to setup a trusty cluster on GCE, but it failed with `Cluster failed to initialize within 300 seconds`. 

Here is my environment setting:

```
export KUBERNETES_PROVIDER=gce
export KUBE_GCE_MASTER_PROJECT=ubuntu-os-cloud
export KUBE_GCE_MASTER_IMAGE=ubuntu-1404-trusty-v20160304
export KUBE_OS_DISTRIBUTION=trusty
./cluster/kube-up.sh
```

Am I missing something? CC @dchen1107 

By the way, this problem has also been confirmed by @Random-Liu .

**Comment by Random-Liu** [comment] 2016-03-11 07:26
In my test, kubelet keeps complaining that:
```
I0310 19:27:43.984869    3636 kubelet.go:1125] Attempting to register node kubernetes-minion-rg7p
I0310 19:27:43.991933    3636 kubelet.go:1128] Unable to register kubernetes-minion-rg7p with the apiserver: Post h
ttps://kubernetes-master/api/v1/nodes: dial tcp 10.240.0.2:443: connection refused
```

**Comment by dchen1107** [comment] 2016-03-11 15:54
@andyzheng0831 Can you take a look at this?

**Comment by andyzheng0831** [comment] 2016-03-11 17:48
I just try with the latest kubernetes head code. I think you missed something. Please note that you need to set both the master and nodes image/image-project. Here is my env variables:

export KUBE_OS_DISTRIBUTION=trusty
export KUBE_GCE_MASTER_PROJECT=ubuntu-os-cloud
export KUBE_GCE_MASTER_IMAGE=ubuntu-1404-trusty-v20160304
export KUBE_GCE_NODE_PROJECT=ubuntu-os-cloud
export KUBE_GCE_NODE_IMAGE=ubuntu-1404-trusty-v20160304

Then, kube-up.sh works. Commands "kubectl get nodes" and "kubectl get pods --all-namespaces" also show the right information. Please verify it.

**Comment by Random-Liu** [comment] 2016-03-11 18:19
@andyzheng0831 I don't quite understand.
In `gce/config-default.sh`, I saw this:
```
NODE_IMAGE=${KUBE_GCE_NODE_IMAGE:-"${MASTER_IMAGE}"}
NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-"${MASTER_IMAGE_PROJECT}"}
```
Doesn't that mean, nodes image/image-project is default to be the same with master?

**Comment by andyzheng0831** [comment] 2016-03-11 20:18
Yes, what you mentioned is correct. And I can reproduce the issue. I have been using the old way of setting both master and node image/project, so I have not noticed this issue. I am debugging it, and will update you

**Comment by Random-Liu** [comment] 2016-03-11 21:28
@andyzheng0831 Thanks a lot! :)

**Comment by andyzheng0831** [comment] 2016-03-11 23:07
I find the root cause. There are few racing cases which make the health check incorrectly thinks kubelet is unhealthy and kill it too fast. I just made a fix and tested it by running "kube-up.sh" and "kube-down.sh" back and forth for 10 times. I will send it out for review shortly.

**Comment by andyzheng0831** [comment] 2016-03-13 01:15
The fix is merged. Please feel free to close this issue. It seems like I don't have permission to close it.

**Comment by Random-Liu** [comment] 2016-03-13 01:33
@andyzheng0831 I also tested it with #22882. It works!
Close this issue since #22882 has been merged.

**Closed by Random-Liu** 2016-03-13 01:33 UTC
Labels: priority/P1, team/control-plane, team/node

**Comment by feiskyer** [comment] 2016-03-14 02:57
Have someone encountered this problem:

```
Created [https://www.googleapis.com/compute/v1/projects/soy-storm-108313/global/firewalls/kubernetes-master-https].
NAME                    NETWORK SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
kubernetes-master-https default 0.0.0.0/0  tcp:443          kubernetes-master
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - Value for field 'resource.metadata.items[1].value' is too large
```

I think `resource.metadata.items[1].value` should be `user-data=${KUBE_ROOT}/cluster/gce/trusty/master.yaml`, whose size is:

```
ll cluster/gce/trusty/master.yaml
-rw-r--r-- 1 root root 6727 3月  14 02:24 cluster/gce/trusty/master.yaml
```

BTW: I use a modified version of setup scripts from [here](https://github.com/feiskyer/kubernetes/blob/kubelet/hyper/cluster/gce/trusty/master.yaml) (mainly added some config for hyper container runtime).

**Comment by andyzheng0831** [comment] 2016-03-14 03:06
@feiskyer Thanks for reporting this. Recently I had expected this would happen someday, as GCE has a size limit for custom metadata. I made a PR #22818 to address it and sent out for review (actually earlier than the fix for this issue) Hopefully, we can get it be merged soon.

**Comment by feiskyer** [comment] 2016-03-14 03:44
@andyzheng0831 Thanks a lot.
