### ISSUE TITLE
kubectl command to convert pod IP to pod name

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#15763] opened 2015-10-16 05:51 UTC
Since we don't currently auto create POD DNS names, it would be nice to have a way to convert an IP address of a pod to pod name.  Perhaps even let you `exec` with an IP address in addition to a pod name.

Thanks!

**Comment by hurf** [comment] 2015-10-16 08:12
Is it dup with #15690?

**Comment by danielschonfeld** [comment] 2015-10-16 14:27
@hurf it appears it is! do you want to close this?

**Comment by thockin** [comment] 2015-10-16 16:30
15690 is specifically about SERVICES and not pods.

Can you explain what this issue is actually about?  What do you mean by pod
name?  a DNS name or just a name resolvable in our API?  Or something else?

**Comment by danielschonfeld** [comment] 2015-10-17 21:12
@thockin imagine you power up a storm cluster, or any cluster of any program.  the nodes need to announce themselves.  currently since we do not provide DNS entries for pod names in kube-dns then one must resort to announcing the POD's IP address broadcast to the network.

So now your logs are full of IPs that may or may not be meaningful to you.  

Suppose there was an error on of the nodes and all you can see is its IP and you want to go investigate you have to find on your own what pod this IP belongs to and from there figure out what host-node it resides on to go SSH into and do some digging around.

That's my use case

**Comment by bgrant0607** [comment] 2016-01-22 19:12
Sounds like a dupe of #3481

**Comment by thockin** [comment] 2016-04-27 04:44
We now have custom hostnames and DNS for them

**Closed by thockin** 2016-04-27 04:44 UTC
Labels: kind/feature, priority/P2, team/ux
