### ISSUE TITLE
Kubelet doesn't start master components

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28997] opened 2016-07-15 09:43 UTC
Recently we observe increased number of large-cluster startup failures. After very little digging it seems to be a problem in kubelet/cAdvisor/docker. We're seeing the following log repeat itself until the timeout:
```
I0715 09:23:50.678641    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/etcd-events.manifest"
I0715 09:23:50.679486    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/etcd.manifest"
I0715 09:23:50.679809    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/glbc.manifest"
I0715 09:23:50.680705    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/kube-addon-manager.yaml"
I0715 09:23:50.681108    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/kube-apiserver.manifest"
I0715 09:23:50.681663    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/kube-controller-manager.manifest"
I0715 09:23:50.682083    1419 file.go:135] Reading config file "/etc/kubernetes/manifests/kube-scheduler.manifest"
I0715 09:23:50.682400    1419 config.go:280] Setting pods for source file
I0715 09:23:50.729388    1419 kubelet.go:2257] skipping pod synchronization - [Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/memory/system.slice/kube-logrotate.service: no such file or directory]
I0715 09:23:51.123826    1419 server.go:960] GET /healthz: (30.885Âµs) 200 [[curl/7.47.1] 127.0.0.1:34718]
I0715 09:23:51.136068    1419 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
I0715 09:23:51.136100    1419 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
E0715 09:23:51.145694    1419 eviction_manager.go:126] eviction manager: unexpected err: failed GetNode: node 'e2e-scalability-master' not found
```

P0 as it happened at least 3 time in last 2 days.

cc @kubernetes/goog-node @kubernetes/sig-node @dchen1107 @Random-Liu @wojtek-t @fgrzadkowski

**Comment by wojtek-t** [comment] 2016-07-15 09:49
Those particular logs come from kubelet on master machine in this run:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gce-scalability/9505/console

**Comment by dims** [comment] 2016-07-15 13:36
@wojtek-t @gmarek - wild theory. is it possible that the kube-logrotate.service has to be running before kubernetes.target? Looking at:

- https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/node.yaml#L105
- https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/master.yaml#L105

If so, we could add a `Requires=kube-logrotate.service` in the `[unit]` for  kubernetes.target. Right?

**Comment by yujuhong** [comment] 2016-07-15 18:18
`Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/memory/system.slice/kube-logrotate.service: no such file or directory` caused kubelet not being able to sync pods.
Could it be possible that kubelet-logrotate get removed while cadvisor was traversing the directory recursively to add all of them? If so, we should ignore such errors since the file doesn't exist anymore.
/cc @timstclair @vishh

**Comment by Random-Liu** [comment] 2016-07-15 18:36
I've never seen `/sys/fs/cgroup/memory/system.slice/kube-logrotate.service` in my cluster.
Only `/etc/systemd/system/kube-logrotate.service`

**Comment by yujuhong** [comment] 2016-07-15 19:06
logrotation is triggered by `/etc/systemd/system/kube-logrotate.timer` and only runs hourly. I assume it was run while cadvisor was starting up, so cadvisor saw the short-lived cgroup.
All my comments above are just speculation :)

**Comment by Random-Liu** [comment] 2016-07-16 01:00
> logrotation is triggered by /etc/systemd/system/kube-logrotate.timer and only runs hourly. I assume it was run while cadvisor was starting up, so cadvisor saw the short-lived cgroup.
All my comments above are just speculation :)

Offline discussed with @vishh and @yujuhong, https://github.com/kubernetes/kubernetes/issues/28997#issuecomment-233043524 should be the root cause.

In this master, we can see:
```
I0715 09:19:30.780720    1419 factory.go:104] Error trying to work out if we can handle /system.slice/kube-logrotate.service: invalid container name
I0715 09:19:30.780728    1419 factory.go:115] Factory "docker" was unable to handle container "/system.slice/kube-logrotate.service"
I0715 09:19:30.780738    1419 factory.go:104] Error trying to work out if we can handle /system.slice/kube-logrotate.service: /system.slice/kube-logrotate.service not handled by systemd handler
I0715 09:19:30.780747    1419 factory.go:115] Factory "systemd" was unable to handle container "/system.slice/kube-logrotate.service"
I0715 09:19:30.780757    1419 factory.go:111] Using factory "raw" for container "/system.slice/kube-logrotate.service"
I0715 09:19:30.780924    1419 manager.go:865] Added container: "/system.slice/kube-logrotate.service" (aliases: [], namespace: "")
I0715 09:19:30.781092    1419 handler.go:325] Added event &{/system.slice/kube-logrotate.service 2016-07-15 09:19:30.750629175 +0000 UTC containerCreation {<nil>}}
```
It means that cadvisor did see `/sys/fs/cgroup/memory/system.slice/kube-logrotate.service` during [start up](https://github.com/google/cadvisor/blob/master/manager/manager.go#L281-L286).
 However, because `/sys/fs/cgroup/memory/system.slice/kube-logrotate.service` is only a short lived service, when cadvisor tried to [watch the cgroup](https://github.com/google/cadvisor/blob/master/manager/manager.go#L290), it has already been deleted. That's why we get the error:
```
inotify_add_watch /sys/fs/cgroup/memory/system.slice/kube-logrotate.service: no such file or directory
```

I've checked some normal clusters, cadvisor doesn't see `/sys/fs/cgroup/memory/system.slice/kube-logrotate.service` at all, because it is too short lived. This is only about timing. :)

Anyway, cadvisor shouldn't fail when the cgroup is missing during watching, which sometimes does happen. I'll send a fix soon.

**Comment by wojtek-t** [comment] 2016-07-16 09:54
Thanks a lot for this debugging! And waiting for the fix.

**Comment by Random-Liu** [comment] 2016-07-17 00:40
FYI, I've sent a PR to fix cadvisor side https://github.com/google/cadvisor/pull/1381. Once that PR is included in kubernetes, we can close this issue. :)

**Comment by wojtek-t** [comment] 2016-07-17 09:55
Awesome - thanks @Random-Liu

**Comment by dchen1107** [comment] 2016-07-25 22:01
Shouldn't we run into the same issue for 1.3 GKE release? If we do, we need to patch 1.3. cc/ @alex-mohr @roberthbailey

**Comment by roberthbailey** [comment] 2016-07-25 22:53
@jlowdermilk @a-robinson

**Closed** 2016-07-26 01:29 UTC
Labels: kind/flake, priority/P0, team/node
