### ISSUE TITLE
kubernetes-test-go takes ~43min occasionally hitting test timeout  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#23127] opened 2016-03-17 15:56 UTC

**Comment by liggitt** [comment] 2016-03-18 01:30
https://github.com/kubernetes/kubernetes/pull/22919 would help with unit tests. TLS enabled etcd for registry unit test packages is pretty slow

**Comment by maisem** [comment] 2016-03-21 23:25
Timed out again
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/9953/

**Comment by maisem** [comment] 2016-03-22 22:38
And again
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/9986/
This makes it twice in two days. Maybe we need to bump the priority.

**Comment by lavalamp** [comment] 2016-03-23 17:21
@spxtr to delegate

**Comment by spxtr** [comment] 2016-03-23 17:34
The suite used to take about 35 minutes, then for a few days it started taking 42 minutes, and now it's back to 35 minutes. Rather than bump up the timeout, we need to figure out which test has slowed down and why.

If it's something expected or out of our control then increasing the timeout is fine.

**Comment by liggitt** [comment] 2016-03-23 17:38
did the slowdowns coincide with https://github.com/kubernetes/kubernetes/pull/21535 merging? we saw that make all the registry package unit tests take 3x as long, and some hit the 1 minute package timeout

**Comment by spxtr** [comment] 2016-03-23 17:52
The original slowdown was caused by #21535, but it has improved somewhat since.

**Comment by spxtr** [comment] 2016-03-23 20:11
![testspeeds](https://cloud.githubusercontent.com/assets/7368979/13999264/a8cb9ab6-f0f8-11e5-84db-1160eb4c61bc.png)

I made a quick plot of kubernetes-test-go test times for the last thousand or so. The huge spike was #21535, and we recovered most of the way but not all the way.

**Comment by liggitt** [comment] 2016-03-23 20:51
Any interest in https://github.com/kubernetes/kubernetes/pull/22919, which runs the individual registry package units with non-tls etcd?

**Comment by spxtr** [comment] 2016-03-23 21:01
That looks like it might improve this significantly :)

**Comment by spxtr** [comment] 2016-03-23 23:02
Anyway, we're back down to ~35 minutes. Closing this issue.

**Closed by spxtr** 2016-03-23 23:02 UTC
Labels: kind/flake, team/test-infra
