### ISSUE TITLE
[Failing test] gce-ubuntu-master-containerd

### ISSUE THREAD

**Issue by bharitwal** [kubernetes/kubernetes#113552] opened 2022-11-02 16:47 UTC
### Which jobs are failing?

release-master-blocking:

- gce-ubuntu-master-containerd

### Which tests are failing?

- ci-kubernetes-e2e-ubuntu-gce-containerd.Overall
- kubetest.Test

### Since when has it been failing?

31st October 2022

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

### Reason for failure (if possible)

Kubernetes e2e suite: [It] [sig-node] Pods Extended Pod Container Status should never report success for a pending container  | 1m36s
-- | --
{Nov  2 15:37:18.311: 2 errors: pod pod-terminate-status-2-1 on node bootstrap-e2e-minion-group-rsb5 container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 15:35:51 +0000 UTC reason=StartError message=failed to start containerd task "8647c320912ba1b9d8d5ebf1bb1563cc856fe0a7c1f58fe217ea92091814dcc6": context canceled: unknown pod pod-terminate-status-1-5 on node bootstrap-e2e-minion-group-rsb5 container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 15:36:16 +0000 UTC reason=StartError message=failed to start containerd task "c5a4638e5bb7152c8727058e1103267e62a2e92ead46de5993c4dab38bd80001": context canceled: unknown failed test/e2e/node/pods.go:474 k8s.io/kubernetes/test/e2e/node.createAndTestPodRepeatedly(0x3, 0xf, {0x7f6e4b8?, 0xc004123800}, {0x7f8e7c0?, 0xc004123740}) 	test/e2e/node/pods.go:474 +0x81d k8s.io/kubernetes/test/e2e/node.glob..func10.3.2() 	test/e2e/node/pods.go:210 +0xae}

e2e.go:  | 18m53s
-- | --
{  error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Driver:.gcepd\]\|\[Slow\]\|\[Serial\]\|\[Disruptive\]\|\[Flaky\]\|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/14: exit status 1}

### Relevant SIG(s)

/sig cloud-provider
cc @kubernetes/ci-signal

**Comment by aojea** [comment] 2022-11-02 18:08
it should be fixed by now https://github.com/kubernetes/kubernetes/issues/113547

**Comment by aojea** [comment] 2022-11-02 18:09
yeah

/close

as duplicate of https://github.com/kubernetes/kubernetes/issues/113547

**Closed by aojea** 2022-11-02 18:09 UTC
Labels: kind/failing-test, sig/cloud-provider, needs-triage
