### ISSUE TITLE
Support for node-role.kubernetes.io and kubernetes.io/role in Kubelet config not working

### ISSUE THREAD

**Issue by rnsv** [kubernetes/kubernetes#85073] opened 2019-11-10 23:26 UTC
**What happened**:
Starting v1.16.x, the support to set node-role.kuberetes.io and kubernetes.io/role label using --node-labels option has stopped working because of this PR https://github.com/kubernetes/kubernetes/pull/79305.  This breaks the existing functionality as ```kubectl get nodes``` is not showing ROLES any more

**What you expected to happen**:
The system should allow setting node-role.kubernetes.io or kubernetes.io/role to manage node roles during Kubelet startup

**How to reproduce it (as minimally and precisely as possible)**:
Setting kubernetes.io/role or node-role.kubernetes.io/master as one of the --node-lables option will fail with the following message
```unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [kubernetes.io/role]```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.1
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): CentOS Linux
- Kernel (e.g. `uname -a`): Linux 3.10.0-1062.1.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment] 2019-11-10 23:32
It seems this was due to klog.Warningf being changed to Error (which should be conscientious decision).

**Comment by liggitt** [comment] 2019-11-10 23:40
This is a duplicate of #84912 

See https://github.com/kubernetes/kubernetes/issues/84912#issuecomment-551362981 and the referenced design for the reasons it is not desireable for kubelets to self-select their roles.

**Closed by liggitt** 2019-11-10 23:40 UTC
Labels: kind/bug, needs-sig
