### ISSUE TITLE
Many Kubectl e2e tests in master are broken against 1.0 cluster

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18581] opened 2015-12-11 18:07 UTC
Googlers can find results here:

http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.0-master-step2-kubectl-e2e-new/

P0 for triaging impact, then we can go from there.

**Comment by krousey** [comment] 2015-12-11 18:10
cc @kubernetes/goog-csi @bgrant0607

**Comment by krousey** [comment] 2015-12-11 18:11
I'm looking into this now to see what I can figure out.

**Comment by ihmccreery** [comment] 2015-12-11 18:12
There are some similar failures between 1.1 and 1.0, which we should be more concerned about:

http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.0-current-release-step2-kubectl-e2e-new/

Note that there aren't any failures between 1.1 and master:

http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step2-kubectl-e2e-new/

**Comment by krousey** [comment] 2015-12-11 18:32
cc @thockin for this particular failure.

For the guestbook app, we changed a field from mandatory to optional in #12831. So we removed it from the yaml files. In this case, it's the yaml specs that are not 1.0 compliant. So our specs are forward compatible, but not backwards compatible. That sucks for your testing, but I'm not sure how big of a customer impact this is. @bgrant0607 thoughts?

```console
error validating \"/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/kubernetes/examples/guestbook/frontend-service.yaml\": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
error validating \"/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/kubernetes/examples/guestbook/redis-master-service.yaml\": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
error validating \"/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/kubernetes/examples/guestbook/redis-slave-service.yaml\": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

I'm going to look into the others.

**Comment by brendandburns** [comment] 2015-12-11 18:39
I don't think that this is that big a customer impact, not worth fixing.  Probably worth a release note.

**Comment by ihmccreery** [comment] 2015-12-11 18:42
This is a specific instance of the larger issue #16040; @brendandburns did an audit of 1.1/1.0 here: #16041.

**Comment by krousey** [comment] 2015-12-11 19:08
Kubectl client Simple pod should support inline execution and attach
 
```console
    Expected error:
        <*errors.errorString | 0xc20838f250>: {
            s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.226.158 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/.kube/config --namespace=e2e-tests-kubectl-xv1yf run run-test --image=busybox --restart=Never --attach=true --stdin -- sh -c cat && echo 'stdin closed'] []  0xc2083a6ce0  Error from server: the server could not find the requested resource (post jobs)\n [] <nil> 0xc2083a7680 exit status 1 <nil> true [0xc208823408 0xc208823438 0xc208823450] [0xc208823408 0xc208823438 0xc208823450] [0xc208823410 0xc208823430 0xc208823448] [0x817d40 0x817e60 0x817e60] 0xc20867d500}:\nCommand stdout:\n\nstderr:\nError from server: the server could not find the requested resource (post jobs)\n\n",
        }
        Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.226.158 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.0-master-step1-deploy/workspace/.kube/config --namespace=e2e-tests-kubectl-xv1yf run run-test --image=busybox --restart=Never --attach=true --stdin -- sh -c cat && echo 'stdin closed'] []  0xc2083a6ce0  Error from server: the server could not find the requested resource (post jobs)
         [] <nil> 0xc2083a7680 exit status 1 <nil> true [0xc208823408 0xc208823438 0xc208823450] [0xc208823408 0xc208823438 0xc208823450] [0xc208823410 0xc208823430 0xc208823448] [0x817d40 0x817e60 0x817e60] 0xc20867d500}:
        Command stdout:
        
        stderr:
        Error from server: the server could not find the requested resource (post jobs)
        
        
    not to have occurred
```

Running kubectl run --restart=never starts a job. Jobs didn't exist in 1.0. And I'm pretty sure the entire run subcommand didn't exist in 1.0. Did we run this kind of test in 1.0? If so how?

**Comment by krousey** [comment] 2015-12-11 19:57
Kubectl client Simple pod should support exec through an HTTP proxy

Errors out during controller validation. The specific call that's failing is https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L1128

```go
c.Get().
Namespace(ns).
Resource("pods").
SubResource("proxy").
Name(podID).
Suffix("data.json").
Do().
Raw()
```

Was proxy as a sub-resource exposed in 1.0? @brendandburns 

```console
03:39:40 Dec 11 03:39:40.974: INFO: update-demo-nautilus-aroaq is running right image but validator function failed: an error on the server has prevented the request from succeeding (get pods update-demo-nautilus-aroaq)
```

**Comment by krousey** [comment] 2015-12-11 21:28
Kubectl client Simple pod should support exec through an HTTP proxy

I believe this is the same error as the controller validation logic. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L288 we see:

```go
			resp, err = c.Post().
				Namespace(ns).
				Name("netexec").
				Resource("pods").
				SubResource("proxy").
				Suffix("upload").
				SetHeader("Content-Type", postBodyWriter.FormDataContentType()).
				Body(pipeReader).
				Do().Raw()
```

which again is using the proxy sub-resource. @brendandburns ?

```console
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:359 Dec 11 03:38:24.051: Unable to upload kubeconfig to the remote exec server due to error: an error on the server has prevented the request from succeeding (post pods netexec)
```

**Comment by brendandburns** [comment] 2015-12-11 21:31
Pre 1.1 (afaik, @liggitt might know for sure) the only valid proxy path was `/api/proxy/...`

--brendan

**Comment by liggitt** [comment] 2015-12-11 21:39
pods/proxy was in 1.0: https://github.com/kubernetes/kubernetes/blob/v1.0.0/pkg/master/master.go#L474

**Comment by krousey** [comment] 2015-12-11 21:59
@liggitt Thanks for pointing that out. I will work on reproducing those errors then and try to get more information.

**Comment by krousey** [comment] 2015-12-14 18:46
@ihmccreery I could not reproduce the remaining failures on my own cluster. They all ran successfully multiple times for me. Maybe there is something wrong with the jenkins environment that is breaking proxying? Here's some versions that I tested with:

```go
ClientVersion: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.737+f6686ba3a49eaf", GitCommit:"f6686ba3a49eaf7f7cf76f65243d1e849c9d1e94", GitTreeState:"clean"}
ServerVersion: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.8-beta.65+8218bcbb79b5d4", GitCommit:"8218bcbb79b5d444082ce04137f2bf71056acc57", GitTreeState:"clean"}
```

```yaml
    nodeInfo:
      containerRuntimeVersion: docker://1.6.2
      kernelVersion: 3.16.0-0.bpo.4-amd64
      kubeProxyVersion: v1.0.8-beta.65+8218bcbb79b5d4
      kubeletVersion: v1.0.8-beta.65+8218bcbb79b5d4
      osImage: Debian GNU/Linux 7 (wheezy)
```

**Comment by ihmccreery** [comment] 2015-12-14 19:02
Talking with @cjcullen, chances are this is only affecting GKE, not GCE, because we run proxies differently.  I will try to reproduce, and decide what to do.

**Comment by liggitt** [comment] 2015-12-14 19:29
Subresource proxy via tunneling is known to be broken in 1.0. 
Fixed in https://github.com/kubernetes/kubernetes/pull/15224
Cherry-picked to 1.1 in https://github.com/kubernetes/kubernetes/pull/17127

**Comment by ihmccreery** [comment] 2016-01-21 00:16
This bug currently stands at:

Functionality introduced in #13780, not expected to work in 1.0:

- Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]

Introduced in #18507, never expected to work in 1.0 or 1.1:

- Kubectl client Kubectl run --rm job should create a job from an image, then delete the job [Conformance]

Changed from pod to job in #17195:

- Kubectl client Kubectl run job should create a job from an image when restart is Never [Conformance]
- Kubectl client Kubectl run job should create a job from an image when restart is OnFailure [Conformance]
- Kubectl client Simple pod should support inline execution and attach

Nodeports became optional in #12831, so this test is not backward-compatible:

- Kubectl client Guestbook application should create and stop a working application [Conformance]
- Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]

@lavalamp Can you shed some light on how you want to handle these changes from the CSI perspective? cc @kubernetes/goog-csi

**Comment by ihmccreery** [comment] 2016-01-21 00:22
EDIT: `--rm` was introduced in v1.2, but the test & functionality is actually backward compatible to 1.1, just not to 1.0, since jobs didn't exist in 1.0.

**Comment by ihmccreery** [comment] 2016-01-21 00:36
EDIT 2: *Kubectl client Simple pod should support inline execution and attach* is also failing when run on HEAD (tests/`kubectl` at HEAD) against a 1.1 cluster:

*no kind "DeleteOptions" is registered for version "extensions/v1beta1"*

which is confusing to me, because graceful deletion has been around for a while.  Maybe just not for jobs?  Or perhaps this is a bad error for some other problem here?

**Comment by ihmccreery** [comment] 2016-02-01 22:14
@lavalamp Ping; I want to get moving on this again as we're coming up against v1.2.  My proposal is:

> Functionality introduced in #13780, not expected to work in 1.0:

Disable for clusters <=v1.1.

> Introduced in #18507, never expected to work in 1.0 or 1.1:

Disable for clusters <=v1.2.

> Changed from pod to job in #17195:

Disable for clusters <=v1.2; another option would be to try to rewrite it in a way that would work against pre-v1.2 clusters, but that seems like a lot of work that's relatively low-priority.

> Nodeports became optional in #12831, so this test is not backward-compatible:

Similarly, disable for clusters <=v1.1; another option would be to try to rewrite it in a way that would work against pre-v1.1 clusters (add the NodePort field if we're against an old cluster), but that seems like a lot of work that's relatively low-priority.

**Comment by ihmccreery** [comment] 2016-02-01 22:50
Slight ammendments:

> Introduced in #18507, never expected to work in 1.0 or 1.1:

> Disable for clusters <=v1.2.

This actually does work for v1.1; I guess #18507 was backward-compatible as long as the cluster had jobs.

> Changed from pod to job in #17195:

> Disable for clusters <=v1.2; another option would be to try to rewrite it in a way that would work against pre-v1.2 clusters, but that seems like a lot of work that's relatively low-priority.

Similar.

So, I'd say let's just disable these for v1.0, which didn't have jobs.  We could hack together some backward compatible tests, maybe, for some of them, but again it seems low priority.

However!  For a v1.1 cluster running v1.2 tests, we see:

**Kubectl client Simple pod should support inline execution and attach**

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:459
Expected
    <*errors.StatusError | 0xc820732480>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "an error on the server has prevented the request from succeeding (delete jobs.extensions run-test)",
            Reason: "InternalError",
            Details: {
                Name: "run-test",
                Group: "extensions",
                Kind: "jobs",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "unknown",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
to be nil
```

Investigating.

**Comment by ihmccreery** [comment] 2016-02-01 22:54
#19608 implements that proposal; @lavalamp do you want to push back?

**Comment by lavalamp** [comment] 2016-02-01 23:19
No arguments.

**Closed** 2016-02-02 04:33 UTC
Labels: area/test, area/upgrade, priority/P1, team/CSI

**Comment by ihmccreery** [comment] 2016-03-10 20:38
cc @jlowdermilk
