### ISSUE TITLE
KUBE-PROXY: proxier.go:1306] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 16 failed

### ISSUE THREAD

**Issue by shahaf600** [kubernetes/kubernetes#71706] opened 2018-12-04 12:37 UTC
/sig network
/sig node
**What happened**:
we have a deployment of 800 pods, there was a redeployment yesterday of all the pods at once(don't know why it wasn't with rolling update, usually it is). we have a cluster of 113 nodes and this deployment is probably spreaded on all of the nodes, so all of the pods were recreated at once so in 23 of the servers we saw in kube-proxy logs that it could not reload the iptables.
and it caused unreachability for new pods in those nodes including this deployment i mentioned.
so 160 pods out of 800 were not reachable.

**What you expected to happen**:
that all of the pods will come back up smoothly 

**How to reproduce it (as minimally and precisely as possible)**:
probably to redeploy this massive deployment at once

**Anything else we need to know?**:
we have available resources for this cluster so a rolling update will perform well. 5 days ago we upgraded this deployment from 600 pods to 800 pods.
all of the 113 machines are 40 core 192 GB memory.
we are running vanilla kubernetes.

**Environment**:
- Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"**v1.11.3**", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- Cloud provider or hardware configuration:
bare metal dell 
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`):
3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
vanilla kubernetes
- Others:
if anything else is needed i'll provide it.
btw i tried to restart the firewalld and the kube-proxy, it didn't fix the problem, only a reboot did.

/kind bug

**Comment by nvnobelen** [comment] 2019-01-30 16:38
Same issue occurs on:
Ubuntu-1804-lts
Ubuntu-1810

Line number of when the error occurs varies

Issue does not occur on Ubuntu-1604-lts
(But due to docker 18.x PLEG issues with Ubuntu-1604-lts we really need the upgrade to a higher Ubuntu version, so this is iptables issue is pretty critical to get resolved)

**Comment by shahaf600** [comment] 2019-02-07 08:58
also as @nvnobelen said, it also cause the node to fail assigning ip addresses for new pods in the node, and it does not notify to kubelet that this worker is not ready, and than there will be scheduled new pods on it but with no access.

also what we did to avoid this issue for now, is to redeploy our large deployments slower (less pods down when redeploying), so the 800 pods deployment redeploy take like a hour.

**Comment by gtie** [comment] 2019-02-11 09:55
We have experienced what it seems to be like a similar issue. During a rollout, we updated kube-dns, which was sized at ~20 pods at a time. The update strategy for the kube-dns deployment is to spike up the size and recycle 10% at once.

~30min after the kube-dns rollout, we still had 1/3 of the cluster nodes using the old kube-dns addresses inside the iptables DNAT rules. Restarting the kube-proxy containers on the affected nodes resolved the problem immediately. We still have no good way of reproducing this issue, however.

**Comment by gtie** [comment] 2019-02-14 12:27
For the record, above behaviour was due to kube-proxy "freezing" - it stopped generating logs or doing iptables update. Restart of the frozen kube-proxy processes returned the cluster back to normal.

(Kubernetes 1.12.3 on CentOS 7)

**Comment by liurd** [comment] 2019-02-22 05:55
We also have the issue. 
One more thing is, if two process write iptables same time. in the race condition, there will be write iptable fails. No sure if it is related.

**Comment by thockin** [comment] 2019-04-04 23:36
I'm going to add some logging here.  If it is a spurious error it should retry eventually.  If it is actually generating bad payload, the logs will help.

https://github.com/kubernetes/kubernetes/pull/76171

**Comment by timstoop** [comment] 2019-04-23 09:05
I'm not sure if this is related or not, but it seems like this is one of the few issues dealing with this error. We have the same error on Kubernetes 1.11.6 (yes, we should upgrade, but I doubt that's related? Didn't see any fixes in newer versions that sound like they would solve this), running on Debian 9 in GCE. The underlying problem seems to be that "something" that kube-proxy is doing is causing the eth0 to flap:
```
[...]
[Tue Apr 23 08:26:12 2019] IPVS: Creating netns size=2104 id=82631                                             
[Tue Apr 23 08:26:13 2019] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready                                                  
[Tue Apr 23 08:26:13 2019] IPv6: ADDRCONF(NETDEV_UP): cali5ba039d7ec9: link is not ready                                       
[Tue Apr 23 08:26:13 2019] IPv6: ADDRCONF(NETDEV_CHANGE): cali5ba039d7ec9: link becomes ready                  
[Tue Apr 23 08:26:13 2019] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready                                             
[Tue Apr 23 08:26:35 2019] IPVS: Creating netns size=2104 id=82632                                             
[Tue Apr 23 08:26:36 2019] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready                                  
[Tue Apr 23 08:26:36 2019] IPv6: ADDRCONF(NETDEV_UP): cali02b8654a820: link is not ready                       
[Tue Apr 23 08:26:36 2019] IPv6: ADDRCONF(NETDEV_CHANGE): cali02b8654a820: link becomes ready                  
[Tue Apr 23 08:26:36 2019] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready                             
[Tue Apr 23 08:27:15 2019] IPVS: Creating netns size=2104 id=82633                                             
[Tue Apr 23 08:27:16 2019] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready                                  
[Tue Apr 23 08:27:16 2019] IPv6: ADDRCONF(NETDEV_UP): cali6b39d55793a: link is not ready                       
[Tue Apr 23 08:27:16 2019] IPv6: ADDRCONF(NETDEV_CHANGE): cali6b39d55793a: link becomes ready                  
[Tue Apr 23 08:27:16 2019] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready                             
[Tue Apr 23 08:27:19 2019] IPVS: Creating netns size=2104 id=82634
[...]
```

Restarting kube-proxy seems to solve the issue.

**Comment by thockin** [comment] 2019-04-23 15:33
That is bizarre.  Which proxy mode?

**Comment by timstoop** [comment] 2019-04-24 09:42
Sorry, I updated my comment but of course you cannot see that in your email. The stuff I pasted was a totally unrelated to the problem, so my comment sort of ended up being a "me too". Sorry for the noise.

**Comment by thockin** [comment] 2019-04-24 16:59
Logging has been added upstream.  I'll close this for now, but if/when it reappears please post new info! :)

**Closed by thockin** 2019-04-24 16:59 UTC
Labels: kind/bug, sig/network, sig/node

**Comment by remoe** [comment] 2020-06-18 10:38
I had a similarly error with 1.13.5. It was "fixed" after upgrading the memory of the controller node(s) from 2GB to 3GB :)

**Comment by cchxn258886** [comment] 2021-08-09 09:42
my cluster is 1.17 .i also get this problem。but the cluster has 10nodes 。only 2node have this probelm。when i look for this problem。the ipvs handle book tell me。nodePort can make ipvs rollback iptables 。so what can i do to resolve this problem？
