### ISSUE TITLE
How to use additional non-K8s secrets with an existing service account.

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#12012] opened 2015-07-30 06:30 UTC
According to the [user guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/service-accounts.md#adding-secrets-to-a-service-account), it's possible to consume a secret with an existing service account. Yet the doc marks it as TODO currently.
I tried to figure this out and could use some help here.

Note that i do have an existing serviceaccount `build-robot` with 2 secrets,
```
$ kubectl get serviceaccount/build-robot -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2015-07-29T08:55:14Z
  name: build-robot
  namespace: default
  resourceVersion: "2631"
  selfLink: /api/v1/namespaces/default/serviceaccounts/build-robot
  uid: 870ef2a5-35cf-11e5-8d06-005056b45392
secrets:
- name: test-secret
- name: build-robot-token-eupy8

```

Create a secret with following json

```json
{
    "apiVersion": "v1",
    "kind": "Secret",
    "metadata": {
        "name": "mysecretname",
        "annotations": {
            "kubernetes.io/service-account.name": "build-robot"
        }
    },
    "type": "kubernetes.io/service-account-token"
}

``` 

And i can get a new secret name `mysecretname`,

```shell
$ kubectl get secret/mysecretname -o yaml
```

```yaml
apiVersion: v1
data:
  ca.crt: ...
  token: ...
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: build-robot
    kubernetes.io/service-account.uid: 870ef2a5-35cf-11e5-8d06-005056b45392
  creationTimestamp: 2015-07-29T13:59:33Z
  name: mysecretname
  namespace: default
  resourceVersion: "6492"
  selfLink: /api/v1/namespaces/default/secrets/mysecretname
  uid: 0a066c70-35fa-11e5-8d06-005056b45392
type: kubernetes.io/service-account-token

```

I could consume the secret with a pod properly, yet the serviceaccount 'build-robot' seems to turn its back to that and completely free of this ( still 2 secrets) 

```shell
$ kubectl get serviceaccount/build-robot -o yaml
```

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2015-07-29T08:55:14Z
  name: build-robot
  namespace: default
  resourceVersion: "2631"
  selfLink: /api/v1/namespaces/default/serviceaccounts/build-robot
  uid: 870ef2a5-35cf-11e5-8d06-005056b45392
secrets:
- name: test-secret
- name: build-robot-token-eupy8

```

Is is supposed to be that way, or am i missing sth?

Btw, i would like to complete the doc if i sort this out.

**Comment by erictune** [comment] 2015-07-30 15:51
@liggitt

**Comment by liggitt** [comment] 2015-07-30 16:35
@dalanlan this is working as intended, though I can understand why it is confusing.

The service account `secrets` field is intended to enumerate/limit the secrets a pod running as that service account can mount. The first `service-account-token` secret in that list is automatically mounted by pods running as that service account.

The admission controller for pods is not yet enforcing this list, so pods are still able to volume mount secrets that are not referenced by their service account. @deads2k, @erictune and I are still thinking through the best way to allow enforcing this without making secrets a pain to use (see https://github.com/GoogleCloudPlatform/kubernetes/pull/11827).

Because `service-account-token` secrets hold API credentials for the service account, they can be useful from within pods, or from external systems (for example, to give to an external CI or monitoring system that needs to make API calls).
* The token controller ensures a `service-account-token` secret is created and added to the service account's list of secrets, in order to be auto-mounted into pods
* You can also create `service-account-token` secrets manually, for use with external systems. In that case, it is not necessary to mount them into a pod, so the secret does not need to be in the service account's list of mountable secrets. This is what you did when you manually created a `service-account-token` secret.

**Comment by dalanlan** [comment] 2015-07-31 03:11
Such a great help.
Any idea about `Service account controller`？ Saw it [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/service-accounts-admin.md#service-account-automation) without any details attached. More info would be much nicer there:)

**Comment by liggitt** [comment] 2015-07-31 03:45
It ensures a service account named "default" exists in every namespace

**Comment by erictune** [comment] 2015-08-05 06:31
@liggitt any plans to allow non-service-account-token secrets to be auto-mounted?  Automounting is pretty convenient.  But the question is where to mount them such that all pods of this service account are happy with the auto-mount location

**Comment by liggitt** [comment] 2015-08-05 15:10
I'd like to figure out auto-mounting, but I'm not sure where to hang the mount location configuration... pretty sure @pmorie has been wrestling with that for a while also

**Comment by deads2k** [comment] 2015-08-05 15:30
> I'd like to figure out auto-mounting, but I'm not sure where to hang the mount location configuration... pretty sure @pmorie has been wrestling with that for a while also

What if we took the easy way out and said the SA had to explicitly say where he wanted his automounted secret mounted?  That sounds a little weird to say out loud, but it would still allow a pod to avoid having to explicitly indicate that it wanted the secret mounted and any image would already have to know where wanted to look for the automounted secret, which implies some level of coordination.

**Comment by mbforbes** [comment] 2015-08-17 02:51
@liggitt thank you for the thorough explanation—@dalanlan it looks like your question has been answered? I'm going to close it assuming so, though please re-open if not. 

@erictune / @liggitt / @deads2k worth making a separate issue for auto-mounting if there isn't one?

**Closed by mbforbes** 2015-08-17 02:51 UTC
Labels: kind/support

**Comment by deads2k** [comment] 2015-08-17 12:02
> @erictune / @liggitt / @deads2k worth making a separate issue for auto-mounting if there isn't one?

There's discussion about various service account improvements/changes here: https://github.com/kubernetes/kubernetes/issues/11070
