### ISSUE TITLE
Docker daemon hang for unknown reason CPU high on docker process after restart master node

### ISSUE THREAD

**Issue by JuneZhao** [kubernetes/kubernetes#49857] opened 2017-07-31 05:35 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
We have k8s installed on Azure and recently we found that apiserver disconnected for unknown reason and when we try to pull the logs we found docker daemon hung and we have to restart the docker service and kubelet service to get it working.

We've collected logs regarding dockerd and kubelet 
**What you expected to happen**:
We would  to know any reason for this issue and mitigation for the issue.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
+Attachment

[journalctl_logs.zip](https://github.com/kubernetes/kubernetes/files/1186487/journalctl_logs.zip)
[vmstat.txt](https://github.com/kubernetes/kubernetes/files/1186488/vmstat.txt)

**Comment by JuneZhao** [comment] 2017-07-31 05:57
@kubernetes/sig-azure-bugs

/sig azure

**Comment by JuneZhao** [comment] 2017-07-31 07:24
system information:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

$ docker info
Containers: 24
 Running: 11
 Paused: 0
 Stopped: 13
Images: 6
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804 GiB
Name: k8s-master-109B067D-0
ID: STAA:QZTH:43N4:653J:KIOT:HGY7:CDZY:BSX5:E3TK:QSWW:ONDE:LMCG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

$ kubectl get pods --all-namespaces
NAMESPACE        NAME                                            READY     STATUS    RESTARTS   AGE
default          load-generator-1930141919-t6wnd                 1/1       Running   0          1d
gitlab           gitlab-runner-3041082169-rgq1l                  1/1       Running   0          1d
kube-system      default-http-backend-2657704409-tl785           1/1       Running   0          1d
kube-system      heapster-v1.2.0-1448994189-lt2k4                2/2       Running   0          1d
kube-system      kube-addon-manager-k8s-master-109b067d-0        1/1       Running   1          4d
kube-system      kube-apiserver-k8s-master-109b067d-0            1/1       Running   3          4d
kube-system      kube-controller-manager-k8s-master-109b067d-0   1/1       Running   87         4d
kube-system      kube-dns-v19-mqmcp                              3/3       Running   0          1d
kube-system      kube-dns-v19-w2gwg                              3/3       Running   0          1d
kube-system      kube-proxy-bk2mn                                1/1       Running   1          114d
kube-system      kube-proxy-c7zjr                                1/1       Running   1          114d
kube-system      kube-proxy-n1swl                                1/1       Running   1          114d
kube-system      kube-scheduler-k8s-master-109b067d-0            1/1       Running   416        4d
kube-system      kubernetes-dashboard-696481038-t8dqp            1/1       Running   0          1d
kube-system      nginx-ingress-controller-216873318-345mh        1/1       Running   0          1d
staging   api-215984225-49n3x                      1/1       Running   0          4h
staging   api-215984225-bsxx2                      1/1       Running   0          4h
staging   api-215984225-djcs5                      1/1       Running   0          4h
staging   api-215984225-tmtm3                      1/1       Running   0          4h
staging   api-215984225-xr4m2                      1/1       Running   0          4h

**Comment by feiskyer** [comment] 2017-10-31 05:43
@JuneZhao Didn't figure how to reproduce it. Do you still have such problems? or do you know how to reproduce it?

**Comment by JuneZhao** [comment] 2017-11-11 04:05
@feiskyer  Not really it was from a customer  and the issue actually not resovled back then.

**Comment by jdumars** [comment] 2017-12-26 17:37
I believe this still exists and needs to be looked at.

**Comment by khenidak** [comment] 2018-01-16 19:57
I looked at the logs. With the very limited details I have i noticed the following:
- docker's unix socket broke and dockerd couldn't recover after. The service hanged because **i think** docker was not designed for cases where the socket was forcibly closed outside the daemon. 

I noticed that you are running gitlab (on master?), are you mounting the docker socket inside this container?

**Comment by JuneZhao** [comment] 2018-01-30 02:35
@khenidak abandon by my customer so far, if this get caught will open again so far we can close the issue.

**Comment by khenidak** [comment] 2018-01-30 18:25
cool - Thanks
@jdumars  -- can we close this one?

**Closed** 2018-02-05 21:22 UTC
Labels: kind/bug, priority/important-soon, sig/azure, status/in-progress
