### ISSUE TITLE
Failure Finished Host tmp-node-e2e-b6d45b2a-coreos-alpha-1122-0-0-v20160727 Test Suite

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#31633] opened 2016-08-29 20:06 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30321/node-pull-build-e2e-test/21737/

```
I0829 10:30:09.777786   22504 remote.go:210] Copying test artifacts from tmp-node-e2e-b6d45b2a-coreos-alpha-1122-0-0-v20160727
I0829 10:30:09.792249   22504 run_remote.go:559] Deleting instance "tmp-node-e2e-b6d45b2a-coreos-alpha-1122-0-0-v20160727"
================================================================
Failure Finished Host tmp-node-e2e-b6d45b2a-coreos-alpha-1122-0-0-v20160727 Test Suite
Running Suite: E2eNode Suite
```

Super unclear what happened here...

**Comment by timstclair** [comment] 2016-08-29 20:29
cc @Random-Liu

**Comment by dchen1107** [comment] 2016-08-29 21:25
There is no test failed in this run. Is this blocking any pr merge?

**Comment by Random-Liu** [comment] 2016-08-29 21:34
```
SConnection to 146.148.103.180 closed by remote host.
, command [scp -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -r 146.148.103.180:/tmp/gcloud-e2e-622678784/results/ /var/lib/jenkins/workspace/node-pull-build-e2e-test/_artifacts/tmp-node-e2e-b6d45b2a-coreos-alpha-1122-0-0-v20160727] failed with error: exit status 1 and output:
ssh_exchange_identification: read: Connection reset by peer
]
```
This should be the reason. The ssh connect is reset by some reason.

**Comment by fejta** [comment] 2016-08-29 21:39
I think this is the main cause of https://github.com/kubernetes/kubernetes/issues/31439

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/8802/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/8768/

**Comment by Random-Liu** [comment] 2016-08-29 21:47
One observation is that all these test failures are on coreos `tmp-node-e2e-498cbc0e-coreos-alpha-1122-0-0-v20160727`.

**Comment by dchen1107** [comment] 2016-08-29 21:49
Looks like all failure are due to lost the connect to coreos host during the tests: 

Connection to 104.197.17.25 closed by remote host.
, command [scp -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -r 104.197.17.25:/tmp/gcloud-e2e-1986596147/results/ /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/_artifacts/tmp-node-e2e-beffb2ff-coreos-alpha-1122-0-0-v20160727] failed with error: exit status 1 and output:
ssh_exchange_identification: read: Connection reset by peer
]

cc/ @euank Can you help with this? Otherwise, we have to remove coreos image from node test metrics to stop the bleeding edge.

**Comment by euank** [comment] 2016-08-29 21:53
Possible theory: when I updated to the current way of launching coreos nodes, I just mask the update units, not explicitly stop them. That might not always be sufficient. I'll verify now whether that's where it is (my bad if so).

**Comment by euank** [comment] 2016-08-29 22:15
Theory confirmed (note the masked + active):

```
core@tmp-node-e2e-96819429-coreos-alpha-1122-0-0-v20160727 ~ $ sudo systemctl status update-engine
● update-engine.service
   Loaded: masked (/dev/null; bad)
   Active: active (running) since Mon 2016-08-29 22:12:24 UTC; 1min 33s ago
 Main PID: 1034 (update_engine)
   CGroup: /system.slice/update-engine.service
           └─1034 /usr/sbin/update_engine -foreground -logtostderr

Aug 29 22:12:23 localhost systemd[1]: Starting Update Engine...
Aug 29 22:12:24 localhost update_engine[1034]: [0829/221224:INFO:main.cc(155)] CoreOS Update Engine starting
Aug 29 22:12:24 localhost systemd[1]: Started Update Engine.
Aug 29 22:12:24 localhost update_engine[1034]: [0829/221224:INFO:update_check_scheduler.cc(82)] Next update check in 11m12s
Aug 29 22:13:09 tmp-node-e2e-96819429-coreos-alpha-1122-0-0-v20160727.c.coreos-g update_engine[1034]: [0829/221309:INFO:update_attempter.cc(485)] Updating boot flags...
core@tmp-node-e2e-96819429-coreos-alpha-1122-0-0-v20160727 ~ $ sudo systemctl status locksmithd
● locksmithd.service
   Loaded: masked (/dev/null; bad)
   Active: active (running) since Mon 2016-08-29 22:12:23 UTC; 1min 37s ago
 Main PID: 1016 (locksmithd)
   CGroup: /system.slice/locksmithd.service
           └─1016 /usr/lib/locksmith/locksmithd

Aug 29 22:12:23 localhost systemd[1]: Started Cluster reboot manager.
Aug 29 22:12:24 tmp-node-e2e-96819429-coreos-alpha-1122-0-0-v20160727.c.coreos-g locksmithd[1016]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="best-effort"
```
PR coming in a second... Mea culpa

**Comment by euank** [comment] 2016-08-29 23:20
PR #31653 if any of you fine flake-hunters want to give a review.

**Closed** 2016-08-30 07:08 UTC
Labels: kind/flake, priority/P0, team/node
