### ISSUE TITLE
Create/Update quota should calculate the current used resouce quota

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#22509] opened 2016-03-04 08:59 UTC
When create/update quota,if current used quota > the quota we will create/update, should failed.
we should calculate the current resource quota

```
1. Check current quota
[root@ip-172-18-14-46 bin]# kubectl describe quota/myquota-1
Name:           myquota-1
Namespace:      default
Resource        Used    Hard
--------        ----    ----
cpu         100m    100m
memory          128Mi   16Gi
persistentvolumeclaims  0   20
pods            1   20
replicationcontrollers  0   30
resourcequotas      1   1
secrets         1   15
services        1   10

2. Update the quota < current used resource quota
[root@ip-172-18-14-46 bin]# kubectl edit quota/myquota-1
resourcequota "myquota-1" edited
[root@ip-172-18-14-46 bin]# kubectl describe quota/myquota-1
Name:           myquota-1
Namespace:      default
Resource        Used    Hard
--------        ----    ----
cpu         100m    50m
memory          128Mi   50Mi
persistentvolumeclaims  0   20
pods            1   20
replicationcontrollers  0   30
resourcequotas      1   1
secrets         1   15
services        1   10

Expected results:
2. Should update quota failed.

Additional info:
Create quota also not calculate the current resource quota
```

**Comment by derekwaynecarr** [comment] 2016-03-04 14:43
I am not sure I agree...  an administrator may want to reduce the quota to prevent the creation of new resources while letting currently consumed resources run to completion.  Are there other negative side-effects?

**Comment by mikedanese** [comment] 2016-03-10 04:59
I agree with @derekwaynecarr . FWIW, this is not how cgroups work or other quota systems I have encountered.

**Comment by spiffxp** [comment] 2017-06-19 19:37
/sig api-machinery
because resourcequota

**Comment by derekwaynecarr** [comment] 2017-06-19 20:55
i am closing this as working as designed.

**Closed by derekwaynecarr** 2017-06-19 20:55 UTC
Labels: priority/backlog, sig/api-machinery, team/control-plane (deprecated - do not use)
