### ISSUE TITLE
[k8s.io] Kubectl client [k8s.io] Guestbook application should create and stop a working application [Conformance]

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33617] opened 2016-09-27 23:30 UTC
It hits the apiserver proxy on GKE, which fails with: 
```
'http://10.244.0.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:19.157: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.0.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:24.162: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.0.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:29.166: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.0.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:34.173: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.1.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:39.179: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.1.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 27 15:36:44.184: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-4b1917fb2f43ed3cbed7\"?'\nTrying to reach: 'http://10.244.1.6:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
```

We could just not hit the apiserver proxy but create a service of type=lb instead. That is actually more representative of real world app usage, but the proxy issue seems specific to gke and ssh-tunnels.

**Comment by bprashanth** [comment] 2016-09-28 01:11
@kubernetes/sig-testing fyi recent spike in failures on pr builders from this

**Comment by gmarek** [comment] 2016-09-28 09:53
@roberthbailey can you reassign?

**Comment by sttts** [comment] 2016-09-28 09:55
Saw this now on three different PRs independently with the gke smoke test, all this morning. Feels like a P0.

**Comment by gmarek** [comment] 2016-09-28 11:04
@sttts I thought I was the only one;) If it happens multiple times a day it's certainly a P0.

**Comment by roberthbailey** [comment] 2016-09-29 06:06
@cjcullen would be a good person to dig into this.

**Comment by gmarek** [comment] 2016-10-05 07:58
Ping @cjcullen

**Comment by cjcullen** [comment] 2016-10-05 22:24
I'm not sure how to debug this. I don't see any e2e failures of this test in testgrid in the last 2 weeks. Has it only happened in the PR builder?

**Comment by spxtr** [comment] 2016-10-05 22:32
Dupe of https://github.com/kubernetes/test-infra/issues/725

**Closed by spxtr** 2016-10-05 22:32 UTC
Labels: kind/flake, priority/P0, team/gke

**Comment by cjcullen** [comment] 2016-10-05 22:35
Thanks Joe!

**Comment by bprashanth** [comment] 2016-10-05 23:51
I usually look at one of the linked in prs, ctrl+f this bug number (33617) and go up to the last failure eg https://github.com/kubernetes/kubernetes/pull/31136#issuecomment-250711806
