### ISSUE TITLE
Kubectl get all does not include ingress resources

### ISSUE THREAD

**Issue by stokes776** [kubernetes/kubernetes#82701] opened 2019-09-13 13:49 UTC
**What would you like to be added**:
When running the command "kubectl get all -A" no ingress resources are shown.

**Why is this needed**: Particularly new users of kubernetes are confused why a valid resource type is not shown in a command that has a flag called -all. All should encompass all resource types.

**Comment by liggitt** [comment] 2019-09-13 14:36
Duplicate of https://github.com/kubernetes/kubernetes/issues/42885

/close

**Closed by liggitt** 2019-09-13 14:36 UTC
Labels: kind/feature, sig/cli

**Comment by liggitt** [comment] 2019-09-13 14:43
See also https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all
