### ISSUE TITLE
--runtime-config: very confusing

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16598] opened 2015-10-30 17:26 UTC
This is a grab-bag of issues.
1. api/all=true doesn't change defaults for individual resources; people will expect it to e.g. enable daemonset, but it doesn't.
2. The help text on the CLI is confusing. I suggest just making it explicitly list _all_ of the various strings accepted. I suggest further constructing the string representing the default explicitly, and showing it as the default in the CLI help.
3. Any invalid string should cause a failure to start with a clear message.
4. I think the docs will be more understandable if updated after the above changes.

**Comment by ashcrow** [comment] 2015-10-31 01:49
I started looking at the second and third items above in https://github.com/ashcrow/kubernetes/commit/10cd924465a71a5e0a6a3aa28c553d5008ddb6b3. I have a feeling I'm missing some valid inputs to ```--runtime-config``` though. Am I right in thinking it should be all of the non list items in https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/register.go#L35-L52?

**Comment by spzala** [comment] 2017-06-07 20:09
@lavalamp Hi Daniel, this issue was last discussed over a year ago. It seems like the issue is still there but I wanted to touch base with you and make sure that we want to keep it Open or Close it based on any discussion that might happened during this time. Thanks!

**Closed** 2018-02-24 15:09 UTC
Labels: lifecycle/rotten, priority/backlog, sig/api-machinery
