### ISSUE TITLE
HPA e2e tests failing on large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#52496] opened 2017-09-14 17:17 UTC
The following that have been failing on our 5k-node tests (https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness):

- [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 1 pod to 2 pods
- [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 2 pods to 1 pod

This is part of the correctness suite and large cluster tests are release-blocking.

cc @kubernetes/sig-autoscaling-bugs @kubernetes/sig-scalability-misc @mwielgus @DirectXMan12

**Comment by shyamjvs** [comment] 2017-09-14 17:17
@mwielgus Could you PTAL into this or redirect as apt? It's a release-blocker.

**Comment by shyamjvs** [comment] 2017-09-14 17:19
xRef https://github.com/kubernetes/kubernetes/issues/51718

**Comment by shyamjvs** [comment] 2017-09-14 17:24
The tests seem to be passing on the normal correctness job - https://k8s-testgrid.appspot.com/google-gce#gce (except the latest run)
but they're failing on large cluster and the reason seems to be timeout waiting for scaling to happen.

**Comment by mwielgus** [comment] 2017-09-14 17:46
If i have to guess it is heapster who is failing to provide metrics. HPA itself has no direct dependency on the number of nodes in the cluster. Assigning to @piosz .

**Comment by piosz** [comment] 2017-09-15 11:27
@loburm is going to take a look.

**Comment by aleksandra-malinowska** [comment] 2017-09-15 15:39
From the logs it seems like Heapster is unable to get metrics from nodes. It appears to be a separate issue from addon resizer restarts.

**Comment by loburm** [comment] 2017-09-18 08:31
Thanks for checking it. I have got the same logs for smaller cluster (10 nodes), so at least we know that the problem is not related to big number of nodes/pods.

**Comment by shyamjvs** [comment] 2017-09-18 12:44
@loburm - I'm seeing the test pass on our regular (small cluster) gce job - https://k8s-testgrid.appspot.com/google-gce#gce
And seems like it was passing before and then started failing on our 2k-node job - https://k8s-testgrid.appspot.com/google-gce-scale#gce-large-correctness

**Comment by loburm** [comment] 2017-09-18 13:30
thanks for pointing on it. The main difference between runs on small and big cluster - special node that we are creating for heapster container. And my local experiment have shown that without this node everything works, but with it - fails.

So I assume that it's more network related. I'll try to figure out what's going on.

**Comment by shyamjvs** [comment] 2017-09-19 10:52
Removing this as release-blocker and downing the priority as it's a setup issue specific to use of heapster node.
@loburm Would continue to work on it (thanks!).

**Closed** 2017-09-19 20:34 UTC
Labels: kind/bug, kind/e2e-test-failure, milestone-labels-complete, priority/failing-test, priority/important-soon, sig/autoscaling, sig/scalability
