### ISSUE TITLE
kubernetes local via docker dns/dashboard problems

### ISSUE THREAD

**Issue by ascheman** [kubernetes/kubernetes#29176] opened 2016-07-19 08:36 UTC
I tried to set up kubernetes locally via Docker according to http://kubernetes.io/docs/getting-started-guides/docker/

I ran into the following problems:

1. kubedns was not running (only 2 of the three containers in the DNS pod were coming up)
1. Dashboard was not running

## kubedns problem

The kubedns container in the kubedns pod wrote the following logs
```
...
I0719 08:24:17.689766       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: serializer for text/html; charset=utf-8 doesn't exist. Sleeping 1s before retrying.
E0719 08:24:17.690289       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: serializer for text/html; charset=utf-8 doesn't exist
E0719 08:24:18.370902       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: serializer for text/html; charset=utf-8 doesn't exist
I0719 08:24:18.692780       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: serializer for text/html; charset=utf-8 doesn't exist. Sleeping 1s before retrying.
E0719 08:24:18.693100       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: serializer for text/html; charset=utf-8 doesn't exist
I0719 08:24:19.369996       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0719 08:24:19.370082       1 dns.go:539] records:[], retval:[], path:[local cluster svc default kubernetes]
I0719 08:24:19.370647       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0719 08:24:19.370703       1 dns.go:539] records:[], retval:[], path:[local cluster svc default kubernetes]
E0719 08:24:19.469504       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: serializer for text/html; charset=utf-8 doesn't exist
E0719 08:24:19.876888       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: serializer for text/html; charset=utf-8 doesn't exist
I0719 08:24:19.876947       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: serializer for text/html; charset=utf-8 doesn't exist. Sleeping 1s before retrying.
E0719 08:24:20.569325       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: serializer for text/html; charset=utf-8 doesn't exist
E0719 08:24:21.170742       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: serializer for text/html; charset=utf-8 doesn't exist
I0719 08:24:21.171316       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: serializer for text/html; charset=utf-8 doesn't exist. Sleeping 1s before retrying.
F0719 08:24:21.473908       1 server.go:127] Received signal: terminated
```

and it was repeatedly restarted (health check also did not work!)

## Dashboard problem

The dashboard was restarted over and over again with the following log:
```
Starting HTTP server on port 9090
Creating API server client for http://localhost:8080
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://localhost:8080/version: dial tcp [::1]:8080: getsockopt: connection refused
```

## Work around

Just drop the two lines

```
--cluster-dns=10.0.0.10 \
--cluster-domain=cluster.local \
``` 

from the k8s Docker container start. Then everything starts up nicely!

## Working start up script

```
#!/bin/bash

set -eu

: ${ARCH:="amd64"}
: ${K8S_VERSION:="v1.3.2"}

exec docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:rw \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged \
    gcr.io/google_containers/hyperkube-${ARCH}:${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --allow-privileged --v=2
```

**Comment by apelisse** [comment] 2016-07-19 16:01
cc @erictune

**Comment by apelisse** [comment] 2016-07-19 17:17
cc @brendandburns Not sure who is supporting this now?

**Comment by brendandburns** [comment] 2016-07-19 17:27
I think these instructions are largely deprecated in favor of minikube:

https://github.com/kubernetes/minikube

**Comment by mnikolaenko** [comment] 2016-08-04 08:28
Try --volume=/var/lib/kubelet/:/var/lib/kubelet:rw,rslave instead of --volume=/var/lib/kubelet/:/var/lib/kubelet:rw. It worked for me.

**Comment by cheld** [comment] 2016-08-08 13:33
Duplicate of https://github.com/kubernetes/kubernetes/issues/26943

**Comment by thockin** [comment] 2016-09-01 16:42
if we're EOL'ing the local-docker instructions we should mark them as such.  I don't have a strong feeling either way, but DNS should work if it is a documented use case

**Comment by cheld** [comment] 2016-09-01 18:03
DNS is not working because service account not working any more when using --containerized. Works with shared or slave which is now default. Issue can be closed, I assume.

**Closed** 2016-09-01 18:18 UTC
Labels: component/dns, documentation/content-gap, kind/documentation, team/cluster
