### ISSUE TITLE
Update Bazel Script Broken

### ISSUE THREAD

**Issue by hprateek43** [kubernetes/kubernetes#85070] opened 2019-11-10 17:52 UTC
**What happened**:
I ran update-bazel.sh to update the bazel files. Instead it threw me this error

```
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/diff.go:25:2: cannot find package "github.com/bazelbuild/bazel-gazelle/config" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/config (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/config (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:30:2: cannot find package "github.com/bazelbuild/bazel-gazelle/flag" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/flag (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/flag (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/version.go:25:2: cannot find package "github.com/bazelbuild/bazel-gazelle/internal/version" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/internal/version (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/internal/version (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:31:2: cannot find package "github.com/bazelbuild/bazel-gazelle/label" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/label (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/label (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:32:2: cannot find package "github.com/bazelbuild/bazel-gazelle/language" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/language (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/language (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/langs.go:20:2: cannot find package "github.com/bazelbuild/bazel-gazelle/language/go" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/language/go (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/language/go (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/langs.go:21:2: cannot find package "github.com/bazelbuild/bazel-gazelle/language/proto" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/language/proto (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/language/proto (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:33:2: cannot find package "github.com/bazelbuild/bazel-gazelle/merger" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/merger (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/merger (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:34:2: cannot find package "github.com/bazelbuild/bazel-gazelle/repo" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/repo (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/repo (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:35:2: cannot find package "github.com/bazelbuild/bazel-gazelle/resolve" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/resolve (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/resolve (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/diff.go:26:2: cannot find package "github.com/bazelbuild/bazel-gazelle/rule" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/rule (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/rule (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go:37:2: cannot find package "github.com/bazelbuild/bazel-gazelle/walk" in any of:
        /usr/local/opt/go/libexec/src/github.com/bazelbuild/bazel-gazelle/walk (from $GOROOT)
        /Users/harshsingh/go/src/github.com/bazelbuild/bazel-gazelle/walk (from $GOPATH)
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/diff.go:27:2: cannot find package "github.com/pmezard/go-difflib/difflib" in any of:
        /usr/local/opt/go/libexec/src/github.com/pmezard/go-difflib/difflib (from $GOROOT)
        /Users/harshsingh/go/src/github.com/pmezard/go-difflib/difflib (from $GOPATH)
!!! Error in ./hack/update-bazel.sh:29
  Error in ./hack/update-bazel.sh:29. 'go install ./github.com/bazelbuild/bazel-gazelle/cmd/gazelle' exited with status 1
Call stack:
  1: ./hack/update-bazel.sh:29 main(...)
Exiting with status 1
```

**What you expected to happen**:
The bazel build  files should have been updated. Instead I got a package error.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a go 1.13 environment and run `hack/update-bazel.sh`

**Anything else we need to know?**:
NONE

**Environment**:
- Kubernetes version (use `kubectl version`):
Building Kubernetes master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
MacOS
- Kernel (e.g. `uname -a`):
Darwin Harshs-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

- Install tools:
NONE
- Network plugin and version (if this is a network-related bug):
NONE
- Others:
Building master branch of Kubernetes

**Comment by hprateek43** [comment] 2019-11-10 17:53
@liggitt Tagging for reference

**Comment by liggitt** [comment] 2019-11-10 18:52
what does `go env` output for you? Does a `make clean` help? Is your kubernetes checkout within your $GOPATH?

**Comment by hprateek43** [comment] 2019-11-11 05:22
go env

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/harshsingh/Library/Caches/go-build"
GOENV="/Users/harshsingh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/harshsingh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/harshsingh/Documents/Projects-CNCF/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v1/5kly19_554759ryghw1msxt80000gp/T/go-build962917621=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

`make clean` does not help. The error still persists. 

Isn't `GOPATH` deprecated in 1.13+, where `GOMOD` is enabled by default ?

**Comment by liggitt** [comment] 2019-11-11 05:35
Modules are enabled by default, but gopath may still be used, and the kubernetes build scripts have not yet been updated to work with gomodules. See https://github.com/kubernetes/kubernetes/issues/82531 for the work remaining to do that

**Comment by liggitt** [comment] 2019-11-11 05:38
Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/82531

/close

**Closed by liggitt** 2019-11-11 05:38 UTC
Labels: area/build-release, needs-sig, triage/not-reproducible, triage/support
