### ISSUE TITLE
kubectl proxy doesn't support websockets

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#33151] opened 2016-09-21 03:02 UTC
Repro:
```
$ kubectl proxy
```

```sh
$ kubectl -s http://localhost:8001 exec -it cli-2957612540-00uub bash
Error from server: Upgrade request required
```

https://github.com/koding/websocketproxy has a potential solution.

**Comment by brendandburns** [comment] 2016-09-21 03:03
@ncdc @liggitt @deads2k

**Comment by ncdc** [comment] 2016-09-21 13:00
This is a dupe of #32026

**Comment by ncdc** [comment] 2016-09-21 13:00
Also FYI `kubectl exec` uses SPDY, not websockets.

**Closed by ncdc** 2016-09-21 13:00 UTC
Labels: component/kubectl, team/ux
