### ISSUE TITLE
kubernetes-e2e-{gce,gke}-serial mostly red due to flakes

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#31448] opened 2016-08-25 18:32 UTC
preventing an alpha release

**Comment by dchen1107** [comment] 2016-08-29 19:03
cc/ @pwittrock

**Comment by dchen1107** [comment] 2016-09-01 21:39
There was a massive failure since last week, which was caused by a pr mistakenly enable GCI on some tests. The issue is fixed by https://github.com/kubernetes/test-infra/pull/462
Now kubernetes-e2e-gce-serial is back to normal now (https://k8s-testgrid.appspot.com/google-gce#gce-serial), and a separate investigation with gce-gci-serial is ongoing (https://k8s-testgrid.appspot.com/google-gce#gce-gci-serial)

But kubernetes-e2e-gke-serial is still flake with the following tests: 
1) Horizontal pod autoscaling (scale resource: CPU) [k8s.io] [Serial] [Slow] ReplicaSet Should scale from 1 pod to 3 pods and from 3 to 5 {Kubernetes e2e suite} #31592
2) [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5 {Kubernetes e2e suite} #31591
3) [k8s.io] Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable [replication controller] recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster  #27324 

But all above are under investigation separately. I am closing this one for now.

**Closed by dchen1107** 2016-09-01 21:39 UTC
Labels: area/test, kind/flake, priority/P0
