### ISSUE TITLE
test-cmd-util.sh: `kubectl delete deployment nginx` hangs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#40433] opened 2017-01-25 17:56 UTC
test-cmd-util.sh tests have been failing without blocking the merge queue for several weeks (https://github.com/kubernetes/kubernetes/issues/39168)

while re-enabling the tests in https://github.com/kubernetes/kubernetes/pull/40428, a failure was detected here:
```
   # Deletion of both deployments should not be blocked
   kubectl delete deployment nginx2 "${kube_flags[@]}"
   # Clean up
>  kubectl delete deployment nginx "${kube_flags[@]}"
```

the marked line loops getting this response from the server:
```
I0125 12:47:55.160339     891 round_trippers.go:395] GET http://127.0.0.1:8080/apis/extensions/v1beta1/namespaces/default/deployments/nginx
I0125 12:47:55.160374     891 round_trippers.go:402] Request Headers:
I0125 12:47:55.160383     891 round_trippers.go:405]     Accept: application/json, */*
I0125 12:47:55.160390     891 round_trippers.go:405]     User-Agent: kubectl/v0.0.0 (darwin/amd64) kubernetes/$Format
I0125 12:47:55.161911     891 round_trippers.go:420] Response Status: 200 OK in 1 milliseconds
I0125 12:47:55.161931     891 round_trippers.go:423] Response Headers:
I0125 12:47:55.161938     891 round_trippers.go:426]     Content-Type: application/json
I0125 12:47:55.161944     891 round_trippers.go:426]     Date: Wed, 25 Jan 2017 17:47:55 GMT
I0125 12:47:55.161949     891 round_trippers.go:426]     Content-Length: 1989
I0125 12:47:55.162014     891 request.go:991] Response Body: {"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"nginx","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/nginx","uid":"56470d21-e326-11e6-b4f5-acbc32c1ca87","resourceVersion":"1241","generation":10,"creationTimestamp":"2017-01-25T17:47:27Z","labels":{"name":"nginx-undo"},"annotations":{"deployment.kubernetes.io/revision":"5","kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"Deployment\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"nginx\",\"creationTimestamp\":null,\"labels\":{\"name\":\"nginx-undo\"}},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"name\":\"nginx-undo\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"name\":\"nginx-undo\"}},\"spec\":{\"containers\":[{\"name\":\"nginx\",\"image\":\"gcr.io/google-containers/nginx:1.7.9\",\"ports\":[{\"containerPort\":80}],\"resources\":{}}]}},\"strategy\":{}},\"status\":{}}\n"}},"spec":{"replicas":0,"selector":{"matchLabels":{"name":"nginx-undo"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"nginx-undo"}},"spec":{"containers":[{"name":"nginx","image":"gcr.io/google-containers/nginx:test-cmd","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulername":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}},"revisionHistoryLimit":0,"paused":true},"status":{"observedGeneration":9,"replicas":4,"updatedReplicas":2,"unavailableReplicas":4,"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2017-01-25T17:47:27Z","lastTransitionTime":"2017-01-25T17:47:27Z","reason":"MinimumReplicasUnavailable","message":"Deployment does not have minimum availability."}]}}
```

I've switched that to a non-cascading delete in order to re-enable the tests, but we need to figure out why the delete is now hanging, fix the hang, and re-enable the cascading delete

**Comment by kargakis** [comment] 2017-01-26 15:03
Highly likely because the observed generation of the overlapping deployment is not updated by the controller hence the reaper blocks forever.

**Comment by jessfraz** [comment] 2017-01-26 20:05
looking into this

**Comment by jessfraz** [comment] 2017-01-26 20:18
hmm i cannot reproduce locally after changing the lines was this a flake or hard fail everytime?

**Comment by liggitt** [comment] 2017-01-26 20:41
hard fail every time

**Comment by soltysh** [comment] 2017-01-30 12:16
This is dupe of #39666. Closing in favor of the other one.

**Closed by soltysh** 2017-01-30 12:16 UTC
Labels: area/test, area/workload-api/deployment, priority/failing-test, sig/cli
