### ISSUE TITLE
Pod containerPort does not match Service targetPort, but application still works properly

### ISSUE THREAD

**Issue by danielmapar** [kubernetes/kubernetes#73049] opened 2019-01-17 23:13 UTC
**What happened**: I created a `Pod` with `containerPort: 9999` and a `Service` with `targetPort: 3000`. On that note, my application inside my `Pod` should not work, but I can access it normally.

**What you expected to happen**: Not be able to access the application inside my `Pod`

**How to reproduce it (as minimally and precisely as possible)**:
`client-pod.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers: 
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 9999
```
`client-node-port.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    component: web
```

```bash
kubectl apply -f .\client-node-port.yaml
kubectl apply -f .\client-pod.yaml
minikube ip 
Access minikubeIp:31515
```

**Anything else we need to know?**:

By running `kubectl describe pods` you will be able to see:

```yaml
Containers:
  client:
    Container ID:   docker://b515215033f9a7c223a4cb4727f8e1acced6f455ad02acd2f604e13809301ea3
    Image:          stephengrider/multi-client
    Image ID:       docker-pullable://stephengrider/multi-client@sha256:855452509d6d9f13dbe1cd34fa3a21d7f6e7d1f0fafb38d1e715dda8e3d17f46
    Port:           9999/TCP
```
and by running `kubectl descrive services` you will see:
```yaml
Name:                     client-node-port
Namespace:                default
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"client-node-port","namespace":"default"},"spec":{"ports":[{"nodePort":31515,"p...
Selector:                 component=web
Type:                     NodePort
IP:                       10.108.209.125
Port:                     <unset>  3050/TCP
TargetPort:               3000/TCP
NodePort:                 <unset>  31515/TCP
Endpoints:                172.17.0.4:3000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```json
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Not a server
- OS (e.g. from /etc/os-release): Windows 10 64 bits + Hyper V (10.0.17763.1) + Minikube v0.32.0
- Kernel (e.g. `uname -a`):
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```
- Install tools: `choco install minikube` and `choco install kubernetes-cli`
- Others: Created minikube vm by running: `minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"`. More details can be found [here](https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c)

**Comment by amazingandyyy** [comment] 2019-01-18 01:13
I bumped into the same issue, it's weird. port 9999 still work even I didn't listen to port 9999.

**Comment by PatrickLang** [comment] 2019-01-25 19:08
/remove-sig windows

SIG-Windows owns the kubelet & kube-proxy for running Windows containers. This is an issue in minikube, which deploys a Linux VM. Can you check with the #minikube channel in the Slack on who to assign this to?

**Comment by danielmapar** [comment] 2019-02-08 08:25
@huangjiasingle  You are right, it is exposing 3000, but the Pod should not use that information in order to do the port forwarding. It should be using the information provided in the yml file as far as I am concerned.

**Comment by thockin** [comment] 2019-03-21 21:53
This is working as intended.  You asked it to forward to port 3000, and it did.

**Closed by thockin** 2019-03-21 21:53 UTC
Labels: kind/bug, sig/network, triage/unresolved

**Comment by derWeihnachtsmann** [comment] 2019-05-07 14:04
Is there a explanation why this is working? As a Kubernetes-Beginner, I like this to know..

**Comment by thockin** [comment] 2019-05-07 17:50
The service says to forward port 3050 on the service VIP(s) to port 3000 on the backends.  The pods are listen()ing on port 3000, so they respond.  The fact that the pod does not expose 3000 in YAML is not relevant -- that declaration is advisory.

If I had a time machine I might consider changing the semantics to be more locked-down wrt pod ports, but it's not an easy thing to change and stay compatible, so nobody has taken it on.

**Comment by ushell** [comment] 2021-03-29 07:24
mark it, container'port can receive traffic from service targetPort, even containerPort is wrong

**Comment by stickycode** [comment] 2023-07-25 23:26
I think its super LAME that this is not fixed... this should be feature flagged and allow people to enable enforcement, there are plenty of highly skilled teams that can fix up their configurations and apps. It doesn't need to break anything.

**Comment by stickycode** [comment] 2023-07-25 23:27
If the containerPort does nothing then remove it from the api

**Comment by thockin** [comment] 2023-07-25 23:31
Thank you for your feedback.
