### ISSUE TITLE
Cluster autoscaler scales up too much

### ISSUE THREAD

**Issue by kevincvlam** [kubernetes/kubernetes#54959] opened 2017-11-01 22:09 UTC
/kind bug
**What happened**:
I created a Alpha Google Container Engine cluster with two nodepools. One of the nodepools uses an instance-template that has a Tesla K80 GPU and installs nvidia drivers using a start-up script. 

The nodepool with the GPU, (GPU Nodepool) had auto-scaling enabled, with a minimum number of nodes of 1 and maximum of 3.

I had 1 node up from the GPU nodepool and scheduled 2 pods requesting 1 GPU each. The autoscaler brought up 2 addition nodes for the GPU nodepool, instead of just one. 

**What you expected to happen**:
The autoscaler brought up extra nodes for the GPU nodepool, this is bad because it costs money and any extra nodes are only brought down after 10+ minutes.

**How to reproduce it (as minimally and precisely as possible)**:
Create an Alpha Google Container Engine cluster with a GPU-enabled nodepool. The nodepool should use an instance group with a GPU and a start-up script that installs drivers and makes the GPU available as kubernetes resource, eg.

```
curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
apt-get update && apt-get install cuda -y
NVIDIA_GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g')
source /etc/default/kubelet
KUBELET_OPTS="$KUBELET_OPTS --node-labels='alpha.kubernetes.io/nvidia-gpu-name=$NVIDIA_GPU_NAME'"
echo "KUBELET_OPTS=$KUBELET_OPTS" > /etc/default/kubelet
systemctl restart kubelet.service
```

Enable auto-scaling on the nodepool and set the min=1 and max=4. Create only one instance of the instance group and schedule trigger scaling-up with a tensorflow deployment:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-gpu
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tensorflow-gpu
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-gpu-service
  labels:
    app: tensorflow-gpu
spec:
  selector:
    app: tensorflow-gpu
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
--- 
```

Should observe that the auto-scaler creates more nodes than needed. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Google Container Engine

- OS (e.g. from /etc/os-release):
ubuntu-gke-1604-lts

- Kernel (e.g. `uname -a`):
Linux gke-my-gpu-cluster-gpu-pool-7cb293cd-31tz 4.4.0-1027-gke #27-Ubuntu SMP Thu Aug 10 13:13:08 UTC 2017 x86_64 x

**Comment by kevincvlam** [comment] 2017-11-01 22:12
@kubernetes/sig-autoscaling-bugs

**Comment by mwielgus** [comment] 2017-11-02 11:04
Can you attach node definition (`kubectl get node -o yaml`)?

**Comment by kevincvlam** [comment] 2017-11-02 14:17
Yup see below. Thanks for your help!

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-11-02T14:05:15Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/fluentd-ds-ready: "true"
    beta.kubernetes.io/instance-type: n1-standard-2
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-accelerator: nvidia-tesla-k80
    cloud.google.com/gke-nodepool: default-pool
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-c
    kubernetes.io/hostname: gke-my-gpu-cluster-v17-default-pool-417a8543-gdzc
  name: gke-my-gpu-cluster-v17-default-pool-417a8543-gdzc
  resourceVersion: "1597"
  selfLink: /api/v1/nodes/gke-my-gpu-cluster-v17-default-pool-417a8543-gdzc
  uid: d9be7c1f-bfd6-11e7-9567-42010af0024c
spec:
  externalID: "9058288099155942356"
  podCIDR: 10.48.0.0/24
  providerID: gce://fathom-containers/us-east1-c/gke-my-gpu-cluster-v17-default-pool-417a8543-gdzc
status:
  addresses:
  - address: 10.142.0.4
    type: InternalIP
  - address: 35.196.237.134
    type: ExternalIP
  - address: gke-my-gpu-cluster-v17-default-pool-417a8543-gdzc
    type: Hostname
  allocatable:
    alpha.kubernetes.io/nvidia-gpu: "1"
    cpu: 1930m
    memory: 5779072Ki
    pods: "110"
    storage.kubernetes.io/scratch: "93619943269"
  capacity:
    alpha.kubernetes.io/nvidia-gpu: "1"
    cpu: "2"
    memory: 7659136Ki
    pods: "110"
    storage.kubernetes.io/scratch: 101584140Ki
  conditions:
  - lastHeartbeatTime: 2017-11-02T14:15:32Z
    lastTransitionTime: 2017-11-02T14:03:26Z
    message: kernel has no deadlock
    reason: KernelHasNoDeadlock
    status: "False"
    type: KernelDeadlock
  - lastHeartbeatTime: 2017-11-02T14:05:29Z
    lastTransitionTime: 2017-11-02T14:05:29Z
    message: RouteController created a route
    reason: RouteCreated
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: 2017-11-02T14:16:11Z
    lastTransitionTime: 2017-11-02T14:05:15Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2017-11-02T14:16:11Z
    lastTransitionTime: 2017-11-02T14:05:15Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2017-11-02T14:16:11Z
    lastTransitionTime: 2017-11-02T14:05:15Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2017-11-02T14:16:11Z
    lastTransitionTime: 2017-11-02T14:14:01Z
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - gcr.io/google-containers/fluentd-gcp@sha256:99cff747870a01cee36c2d1d482a137cf623bf956ca122909b9dc4d831c37e2a
    - gcr.io/google-containers/fluentd-gcp:2.0.8
    sizeBytes: 172232465
  - names:
    - gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:b537ce8988510607e95b8d40ac9824523b1f9029e6f9f90e9fccc663c355cf5d
    - gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
    sizeBytes: 134353887
  - names:
    - gcr.io/google_containers/kube-proxy:v1.7.6
    sizeBytes: 114691377
  - names:
    - gcr.io/google-containers/event-exporter@sha256:e25f66aca3e70af5859037cf7355c78ffe2e5fcb4b1d8a2954ee80b2dc3db3c7
    - gcr.io/google-containers/event-exporter:v0.1.5
    sizeBytes: 91087118
  - names:
    - gcr.io/google_containers/heapster-amd64@sha256:f58ded16b56884eeb73b1ba256bcc489714570bacdeca43d4ba3b91ef9897b20
    - gcr.io/google_containers/heapster-amd64:v1.4.2
    sizeBytes: 73404034
  - names:
    - gcr.io/google-containers/prometheus-to-sd@sha256:272e4ddfb3468c4c9ba245a716a74a7f2fb731cffeaf3583dbb4091565b1dfd6
    - gcr.io/google-containers/prometheus-to-sd:v0.2.1
    sizeBytes: 55231818
  - names:
    - gcr.io/google-containers/prometheus-to-sd@sha256:c6aaa681e77e55aa7f7017ca55265accde313f8e2e5484ee1d0a4d89ff741c48
    - gcr.io/google-containers/prometheus-to-sd:v0.1.3
    sizeBytes: 52037844
  - names:
    - gcr.io/google_containers/cluster-proportional-autoscaler-amd64@sha256:003f98d9f411ddfa6ff6d539196355e03ddd69fa4ed38c7ffb8fec6f729afe2d
    - gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.1.2-r2
    sizeBytes: 49648481
  - names:
    - gcr.io/google_containers/k8s-dns-kube-dns-amd64@sha256:1a3fc069de481ae690188f6f1ba4664b5cc7760af37120f70c86505c79eea61d
    - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
    sizeBytes: 49387411
  - names:
    - gcr.io/google_containers/k8s-dns-sidecar-amd64@sha256:9aab42bf6a2a068b797fe7d91a5d8d915b10dbbc3d6f2b10492848debfba6044
    - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
    sizeBytes: 41819177
  - names:
    - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64@sha256:46b933bb70270c8a02fa6b6f87d440f6f1fce1a5a2a719e164f83f7b109f7544
    - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
    sizeBytes: 41423617
  - names:
    - gcr.io/google_containers/addon-resizer@sha256:dcec9a5c2e20b8df19f3e9eeb87d9054a9e94e71479b935d5cfdbede9ce15895
    - gcr.io/google_containers/addon-resizer:1.7
    sizeBytes: 38983736
  - names:
    - gcr.io/google_containers/defaultbackend@sha256:fb91f9395ddf44df1ca3adf68b25dcbc269e5d08ba14a40de9abdedafacf93d4
    - gcr.io/google_containers/defaultbackend:1.3
    sizeBytes: 3618880
  - names:
    - busybox@sha256:9a5bcda321c23a905b818b0cec18347914cbf8ee3a4db6b570bc05aeb5f35a87
    - busybox:latest
    sizeBytes: 1129289
  - names:
    - gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516
    - gcr.io/google_containers/pause-amd64:3.0
    sizeBytes: 746888
  nodeInfo:
    architecture: amd64
    bootID: 3f1eecc2-a6ad-4773-90d8-03f277f38331
    containerRuntimeVersion: docker://1.12.6
    kernelVersion: 4.4.0-1027-gke
    kubeProxyVersion: v1.7.6
    kubeletVersion: v1.7.6
    machineID: e7d7631f15d8c31f5b2811218c17dd00
    operatingSystem: linux
    osImage: Ubuntu 16.04.3 LTS
    systemUUID: E7D7631F-15D8-C31F-5B28-11218C17DD00
```

**Comment by kevincvlam** [comment] 2017-11-02 14:23
Worth noting, not sure if I should add this in another issue, but it is related: also noticed that if the GPU nodepool was instead set to a minimum of 0, and 0 instances are up, then a scale-up wouldn't be triggered for a pod requesting a GPU. The pod shows an autoscaler event saying that the scale-up was not triggered because no nodes would cause the pod to be schedulable.

**Comment by MaciekPytel** [comment] 2017-11-02 14:27
The last part (scale-from-0) is expected - support for GPU in scale-from-0 was only recently added to CA (https://github.com/kubernetes/autoscaler/pull/401) and will be included for the first time in 1.0.2 (next release).

**Comment by MaciekPytel** [comment] 2017-11-02 14:37
@bskiba @mwielgus Also note that this is a 1.7 cluster, so it runs CA 0.6. Is there anything that we fixed for 1.0 that could account for this?

If anyone reproduces it the output of `kubectl get events --all-namespaces | grep cluster-autoscaler | grep Pod` may be useful - it should provide both scale-up plan and the list of pods CA is trying to help with the scale up.

**Comment by kevincvlam** [comment] 2017-11-02 15:14
Is this something that could be fixed by using a newer version? I was playing with v1.8.1-gke.0, but I couldn't expose the node GPU to pods after installing the drivers manually. Tried adding node-labels as both 'nvidia.com/gpu=Tesla-K80' and 'alpha.kubernetes.io/nvidia-gpu-name=Tesla-K80'.

eg.
```
KUBELET_OPTS="$KUBELET_OPTS --node-labels='nvidia.com/gpu=$NVIDIA_GPU_NAME'"
echo "KUBELET_OPTS=$KUBELET_OPTS" > /etc/default/kubelet
systemctl restart kubelet.service
```

**Comment by MaciekPytel** [comment] 2017-11-02 18:17
@kevincvlam Not sure at all if updating the version will help. We don't know what root cause was and without logs or events I don't think we'll be able to figure it out. Do you use stackdriver monitoring? If so you should be able to find events in there (look for ones called `TriggeredScaleUp`), otherwise if it happens again you can capture the events with the command I pasted above (they're only available for 1 hour though).

Alternatively we'll try to reproduce, but I doubt we'll be able to do it this week.

**Comment by kevincvlam** [comment] 2017-11-02 18:52
Reproduced the TriggeredScaleUp events. One thing I was speculating is that the GPU doesn't appear on the node until after the drivers have installed, which takes about 10-15 minutes. During that installation the newly created Node is created but does not show the GPU as a resource. Could that be contributing to causing the extra ScaleUp events? 

```
default   3m        3m        1         tensorflow-gpu-3302663013-d1d3n   Pod                                        Normal    TriggeredScaleUp             cluster-autoscaler                                      pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/fathom-containers/zones/us-east1-c/instanceGroups/gke-kevin-cluster-default-pool-8d259116-grp 1->2 (max: 3)}]
default   25s       25s       1         tensorflow-gpu-3302663013-d1d3n   Pod                                        Normal    TriggeredScaleUp             cluster-autoscaler                                      pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/fathom-containers/zones/us-east1-c/instanceGroups/gke-kevin-cluster-default-pool-8d259116-grp 2->3 (max: 3)}]
```

**Comment by bskiba** [comment] 2017-11-03 12:22
You're right, this is the issue. When the nodes start up, they have allocatable gpu = 0 so the pod is still unschedulable. Cluster Autoscaler then decides to add one more node to help.
We'll work with the GPU team to resolve this, as this is definitely not working as intended.

For now, it seems that the only autoscaling based on GPUs that will work correctly (starting from 1.8.3) is 0->1 scaling.

**Comment by kevincvlam** [comment] 2017-11-06 15:17
Thank you for looking into this! Looking forward to the fix :)

**Comment by MaciekPytel** [comment] 2017-11-06 15:19
@kevincvlam The fix should be included in k8s 1.8.3.

**Comment by MaciekPytel** [comment] 2017-11-08 09:20
@kevincvlam Sorry, the fix has proven more complex than I initially thought and I haven't managed to get it merged in time for 1.8.3. I'll merge it today or tomorrow and it will go out with 1.8.4.

**Comment by kevincvlam** [comment] 2017-11-08 14:56
Got it, thanks so much for the update and fix @MaciekPytel ! Will the PR show up here once it's submitted?

**Comment by MaciekPytel** [comment] 2017-11-13 14:43
@kevincvlam The PR has been merged to Cluster Autoscaler master (https://github.com/kubernetes/autoscaler/pull/461), I'll cherry-pick it for CA 1.0.3 (which will go out with k8s 1.8.4).

**Comment by kevincvlam** [comment] 2017-11-14 19:55
Amazing, thanks for the fix @MaciekPytel!

**Closed** 2017-12-07 06:49 UTC
Labels: kind/bug, sig/autoscaling
