### ISSUE TITLE
kube-controller-manager spamming errors in log

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#42438] opened 2017-03-02 21:53 UTC
kubernetes version: 1.5.3
platform: aws
deploy tool: kops

my master's **/var/log/kube-controller-manager.log**

is receiving this type of log:

```
I0302 21:51:11.715415       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:11.815662       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:11.915905       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.016217       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.116508       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.216725       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.316962       6 node_status_updater.go:74] Could not update node status ...
```

lots of times per second, this node "ip-172-20-114-85.ec2.internal" does not exist in the cluster anymore and is not shown if I ```kubectl get nodes```

shouldn't it be removed from status_updater?

**Comment by kargakis** [comment] 2017-03-03 13:00
@kubernetes/sig-node-bugs

**Comment by damienjoldersma** [comment] 2017-03-07 19:20
Any work around? Any way to purge those old nodes from the NodeInformer cache?

**Comment by yujuhong** [comment] 2017-03-07 19:34
AFAIK, sig-node doesn't maintain the node controller. 

Based on the [OWNERS](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.0/pkg/controller/node/OWNERS) files, the only approver is @gmarek

**Comment by gmarek** [comment] 2017-03-08 05:31
It has nothing to do with the NodeController:
```
find . -name node_status_updater.go
./pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
```

cc @saad-ali

**Comment by blakebarnett** [comment] 2017-03-23 23:34
This was happening in our clusters as well, only the leader was doing and and killing the container so it restarted made it stop happening.

**Comment by steinnes** [comment] 2017-04-05 14:09
@blakebarnett did you kill the `gcr.io/google_containers/kube-controller-manager` container, which then gets restarted by the scheduler, and that fixed it?

**Comment by blakebarnett** [comment] 2017-04-05 17:28
correct

**Comment by steinnes** [comment] 2017-04-07 14:30
Works for me™ @blakebarnett

**Comment by nabeelamjad** [comment] 2017-04-24 09:43
Same controller log here using k8s 1.5. I deleted one of the nodes which ran out of resources and became stuck, something I'm still trying to pinpoint the cause of but it appears to be related to volumes.

**Comment by xuwang** [comment] 2017-04-26 20:50
This happens on k8s 1.6.1 as well, that replaced old nodes won't get cleaned up, generating large error logs. On CoreOS installation, I did  systemctl restart kube-controller-manager. That fixed it.

**Comment by gmarek** [comment] 2017-04-27 08:04
Ping @saad-ali

**Comment by r4j4h** [comment] 2017-05-09 00:22
This is happening on k8s 1.4.12 as well, restarting kube-controller-manager does *not* seem to fix it for me. It is rotating through two nodes that no longer exist, so I am hoping the cache will purge itself at some point and they will stop?

**Comment by r4j4h** [comment] 2017-05-10 00:13
Just following up that the old nodes still not cleaned up

**Comment by saad-ali** [comment] 2017-05-10 23:47
@verult will work on a fix for this.

**Comment by saad-ali** [comment] 2017-05-10 23:49
@verult Let's make sure the fix also gets ported back to all affected branches (1.6, 1.5, and 1.4).

CC @kubernetes/sig-storage-bugs

**Comment by verult** [comment] 2017-05-11 00:09
I was able to reproduce the problem by force deleting a node containing a pod with some volume attached to it. Did anyone run into a different failure mode?

**Comment by steinnes** [comment] 2017-05-11 21:13
@verult I think that's how the bug surfaced for me.  When I force killed my node we had just started running a StatefulSet with an attached persistent volume, and I think there was one running on the very node I killed.

**Comment by verult** [comment] 2017-05-17 23:37
The NodeInformer cache is actually reporting the correct state. The problem is that inside the node status updater, there is another data structure keeping track of nodes that require a status update (see ActualStateOfWorld.GetVolumesToReportAttached(), called inside UpdateNodeStatuses() in node_status_updater.go). The entry for the deleted node is never removed from the data structure; rather, the updater is set to try to update the dead node again next time, which leads to the message being logged every 100ms.

The solution is to remove the corresponding node entry once the node is deleted. A fix is on its way.

**Closed** 2017-05-26 19:58 UTC
Labels: priority/P1, sig/storage

**Comment by verult** [comment] 2017-05-26 20:35
A fix for 1.5 is on the way (PR #46301 )

**Comment by r4j4h** [comment] 2017-06-05 22:05
Will 1.4 be included as well?

**Comment by verult** [comment] 2017-06-06 00:12
Here you go, my apologies.

**Comment by r4j4h** [comment] 2017-06-06 21:31
Thank you very much! :)

**Comment by saad-ali** [comment] 2017-06-29 18:41
To summarize, the fix for this is in
* 1.7 branch
  *  Releases 1.7.0 and greater
* 1.6 branch
  * Releases 1.6.5 and greater
* 1.5 branch
  * Releases 1.5.8 and greater (1.5.8 has not yet been cut, CC @mwielgus for ETA of that release).
* 1.4 branch
  * Releases 1.4.13 and greater (1.4.13 has not yet been cut, CC @jessfraz for ETA of that release).

**Comment by saad-ali** [comment] 2017-08-22 21:07
There is an edge case that the above fix did not handle: see https://github.com/kubernetes/kubernetes/issues/50721
PR https://github.com/kubernetes/kubernetes/pull/50806 is fixing that
