### ISSUE TITLE
Can kubectl/k8sapi support specified users in exec cmd/interface?

### ISSUE THREAD

**Issue by fisherxu** [kubernetes/kubernetes#55882] opened 2017-11-16 14:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

As the title, can kubectl/k8sapi cmd/interface support specified users of exec function like **docker exec -u** ? Or else can we implement it?

**Comment by sttts** [comment] 2017-11-17 12:46
Duplicate of https://github.com/kubernetes/kubernetes/issues/30656.

**Closed by sttts** 2017-11-17 12:46 UTC
Labels: sig/cli
