### ISSUE TITLE
please update for latest "rkt"

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#28740] opened 2016-07-10 12:48 UTC
Kubernetes v1.2.5 FTBFS with latest [rkt](https://github.com/coreos/rkt/releases) v1.10.0 as follows:

```
# k8s.io/kubernetes/pkg/kubelet/rkt 
src/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:245: multiple-value set.AsIsolator() in single-value context 
src/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:252: multiple-value set.AsIsolator() in single-value context 
```

Apparently _master_ is affected by the same problem.

Please update for latest _rkt_ release. Thanks.

**Comment by onlyjob** [comment] 2016-07-18 10:39
Ping, @yifan-gu, @dcbw.

**Comment by euank** [comment] 2016-07-18 18:29
That is a build error, correct?

Because Kubernetes vendors all dependencies, including appc, the build should be independent of the rkt version you have on your system or in your gopath.

It builds on master for me (and the build-bot should ensure this error doesn't happen on a release branch), so a bit more information on how you encountered that and how to reproduce would be helpful.

**Comment by onlyjob** [comment] 2016-07-18 22:23
@euank, on Debian we build from reusable external libraries, not vendored ones. Anyway eventually obsolete libraries need to be updated for one reason or another. Now would be a good time. :)

**Comment by euank** [comment] 2016-07-18 23:11
@onlyjob since the rkt runtime for kubernetes was only properly released/supported as of v1.3.0 I'm not sure if a cherry-pick of such a vendor update would/should end up in a v1.2.x branch (though I s'pose you can cherry pick it yourself).

Agreed that the vendored rkt/appc version on master should be updated. Is that enough for your packaging?

**Comment by onlyjob** [comment] 2016-07-19 00:58
Yes, updating master will do as then I would be able to either backport fix for 1.2 or upload 1.3. 

At the moment the problem is that supported rkt API is too old...

Thanks.

**Comment by euank** [comment] 2016-07-25 22:06
The etcd3 update will also update rkt to v1.12, so this should be fixed by #29399

**Comment by onlyjob** [comment] 2016-07-26 00:26
etcd3 is much more disruptive change than upgrading _rkt_...

**Comment by euank** [comment] 2016-07-26 01:41
I committed a godep bump of rkt to v1.11.0 https://github.com/euank/kubernetes/tree/update-vendored-rkt, but I need to double check that all the other changes really were transitive dependencies before we'd want to merge it.

I highly doubt that bump actually fixes the original issue here as well because I didn't have to make any code changes in `rkt.go`

**Comment by yujuhong** [comment] 2018-01-23 23:40
Closing since we are deprecating rktnetes (#53601)

**Closed by yujuhong** 2018-01-23 23:40 UTC
Labels: lifecycle/rotten, sig/rktnetes
