### ISSUE TITLE
service ipvs mode. long request time.

### ISSUE THREAD

**Issue by itshikanov** [kubernetes/kubernetes#89468] opened 2020-03-25 10:55 UTC
**What happened**:
I have cluster with 3 master nodes. Master nodes tainted and can run pods.
service.conf.yml:

```
apiVersion: v1
kind: Service
metadata:
  name: testproject-lb
spec:
  type: ClusterIP
  ports:
  - port: 9090 
    protocol: TCP
    targetPort: 9090 
  selector:
    app: testproject
```   
project_deployment.yml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testproject
spec:
  replicas: 3 
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: testproject
  template:
    metadata:
      labels:
        app: testproject
    spec:
      containers:
        - image: ANY_HTTP_APP_RETURN_IP
          env:
          - name: WORKERS
            value: "16"
          imagePullPolicy: Always
          name: testproject
          ports:
            - containerPort: 9090
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: 9090
```

```
kubectl get services
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes       ClusterIP   10.233.0.1     <none>        443/TCP    6d
testproject-lb   ClusterIP   10.233.34.81   <none>        9090/TCP   5d21h
```
```
ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.233.0.1:443 rr
  -> 80.93.187.100:6443           Masq    1      1          0         
  -> 95.213.184.39:6443           Masq    1      1          0         
  -> 212.92.101.221:6443          Masq    1      1          0         
TCP  10.233.0.3:53 rr
  -> 10.233.64.3:53               Masq    1      0          0         
  -> 10.233.65.2:53               Masq    1      0          0         
TCP  10.233.0.3:9153 rr
  -> 10.233.64.3:9153             Masq    1      0          0         
  -> 10.233.65.2:9153             Masq    1      0          0         
TCP  10.233.34.81:9090 rr
  -> 10.233.64.4:9090             Masq    1      0          0         
  -> 10.233.65.4:9090             Masq    1      0          0         
  -> 10.233.65.5:9090             Masq    1      0          0         
TCP  10.233.35.80:443 rr
  -> 10.233.65.3:8443             Masq    1      0          0         
UDP  10.233.0.3:53 rr
  -> 10.233.64.3:53               Masq    1      0          0         
  -> 10.233.65.2:53               Masq    1      0          0  
```

exec curl from console, on one server.  3 times to get all 3 pod.

```
time curl -s --output /dev/null  10.233.34.81:9090

real	0m3.067s
user	0m0.004s
sys	0m0.008s
time curl -s --output /dev/null  10.233.34.81:9090

real	0m0.060s
user	0m0.004s
sys	0m0.004s
time curl -s --output /dev/null  10.233.34.81:9090

real	0m3.065s
user	0m0.004s
sys	0m0.004s
```

3 seconds. When request go to another node. 

**What you expected to happen**:
I am try to create my own ipvs rules with  another port on some server.
Commands:
ipvsadm -A -t 10.233.62.199:9089 -s rr
ipvsadm -a -t 10.233.62.199:9089 -r  10.233.64.4:9090 -m
ipvsadm -a -t 10.233.62.199:9089 -r  10.233.65.5:9090 -m
ipvsadm -a -t 10.233.62.199:9089 -r  10.233.66.3:9090 -m

ipvsadm -ln

time curl -s --output /dev/null 10.233.62.199:9089
time curl -s --output /dev/null 10.233.62.199:9089
time curl -s --output /dev/null  10.233.62.199:9089

result

```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.233.0.1:443 rr
  -> 192.168.50.14:6443           Masq    1      0          0         
  -> 192.168.50.15:6443           Masq    1      1          0         
  -> 192.168.50.16:6443           Masq    1      1          0         
TCP  10.233.0.3:53 rr
  -> 10.233.64.3:53               Masq    1      0          0         
  -> 10.233.66.2:53               Masq    1      0          0         
TCP  10.233.0.3:9153 rr
  -> 10.233.64.3:9153             Masq    1      0          0         
  -> 10.233.66.2:9153             Masq    1      0          0         
TCP  10.233.10.115:443 rr
  -> 10.233.65.3:8443             Masq    1      0          0         
TCP  10.233.62.199:9089 rr
  -> 10.233.64.4:9090             Masq    1      0          1         
  -> 10.233.65.5:9090             Masq    1      0          1         
  -> 10.233.66.3:9090             Masq    1      0          1         
TCP  10.233.62.199:9090 rr
  -> 10.233.64.4:9090             Masq    1      0          0         
  -> 10.233.65.5:9090             Masq    1      0          0         
  -> 10.233.66.3:9090             Masq    1      0          0         
UDP  10.233.0.3:53 rr
  -> 10.233.64.3:53               Masq    1      0          0         
  -> 10.233.66.2:53               Masq    1      0          0         

real    0m0.055s
user    0m0.004s
sys     0m0.000s

real    0m0.056s
user    0m0.004s
sys     0m0.000s

real    0m0.056s
user    0m0.000s
sys     0m0.000s

0 second to all 3 pods! With my own ipvs rules.
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Virtual box 3 servers and same on 3 Hardware servers.
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux  4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig Network

**Comment by itshikanov** [comment] 2020-03-25 14:16
kube-proxy iptables mode the same problem. 3 second to pod on another node, if use service ip.

Try to install 1.16.3 - all Ok(iptables mode) - 0m0.004s to all pods if use service ip.

**Comment by uablrek** [comment] 2020-03-27 08:57
What CNI-plugin (version) are you using?

**Comment by uablrek** [comment] 2020-03-27 08:59
I have seen that "vxlan" can be a problem. If possible, test without vxlan (if you are using it)

**Comment by uablrek** [comment] 2020-03-27 09:46
See also https://github.com/kubernetes/kubernetes/issues/86507#issuecomment-595227060

**Comment by itshikanov** [comment] 2020-03-30 12:13
> What CNI-plugin (version) are you using?

quay.io/coreos/flannel:v0.11.0

**Comment by rikatz** [comment] 2020-04-03 19:48
@uablrek @itshikanov Let's move this to #88986 as this is a duplicate of the vxlan + offloading case

@itshikanov right now, you can test if the performance improves by disabling tx offload in all your flannel interfaces (all nodes). The problem happens in the source and not destination:

```
sudo ethtool --offload flannel.1 rx on tx off
```

**Comment by rikatz** [comment] 2020-04-03 19:48
I'll close and if this happens to be a different problem from the referenced issue above, please feel free to reopen.

@uablrek tks for the help in this issue :D

/close

**Closed** 2020-04-03 19:49 UTC
Labels: kind/bug, sig/network, triage/unresolved

**Comment by rikatz** [comment] 2020-04-03 19:58
Duplicate of #88986

**Comment by ehsan310** [comment] 2024-05-07 22:09
I am experiencing the exact same issue , but I don't have any vxlan setup i have Calico peered with DC router and use flat networking but experiencing the same delay! any idea what could be the cause ?

**Comment by uablrek** [comment] 2024-05-08 07:39
If it's related to this issue, you may experiment with `ethtool --offload (other interfaces) rx on tx off`. Otherwise it's some other problem with similar symptoms, and you may open a new issue
