### ISSUE TITLE
PR builder flake: [Fail] Deployment [It] deployment should delete old replica sets 

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21782] opened 2016-02-23 19:41 UTC
PR builder failed with this error message.  Unrelated to the actual changes:

>
Summarizing 1 Failure:

[Fail] Deployment [It] deployment should delete old replica sets 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:196

Ran 137 of 237 Specs in 532.033 seconds
FAIL! -- 136 Passed | 1 Failed | 0 Pending | 100 Skipped 

[prbuildflake.txt](https://github.com/kubernetes/kubernetes/files/143283/prbuildflake.txt)

**Comment by justinsb** [comment] 2016-02-23 19:49
Just hit this also.  A little more context:

```

• Failure [71.173 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should delete old replica sets [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:56

  Feb 23 09:45:31.112: Failed to remove deployment redis-deployment pods!
```

**Comment by nikhiljindal** [comment] 2016-02-23 19:54
Its a different test case, but the failure seems to be same as https://github.com/kubernetes/kubernetes/issues/21753.

The test timed out deleting pods.

**Comment by bgrant0607** [comment] 2016-02-23 23:24
Dupe of #21798

**Closed by bgrant0607** 2016-02-23 23:24 UTC
Labels: kind/flake, team/ux
