### ISSUE TITLE
CreatingLoadBalancerFailed with only "(events with common reason combined)"

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#45818] opened 2017-05-15 10:56 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No-ish.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "events with common reason combined"

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG/Request for improvement

**Kubernetes version** (use `kubectl version`):
~~~~
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
~~~~

**Environment**:
- **Cloud provider or hardware configuration**: AWS via kube-aws
- **OS** (e.g. from /etc/os-release): CoreOS 1235.12.0
- **Kernel** (e.g. `uname -a`): 4.7.3
- **Install tools**: kube-aws 0.9.4-ish

**What happened**:
I was deploying a service of type LoadBalancer, and that failed. I starting debugging this failure only a long time after the fact (other more relevant issues needed solving first - this is a development environment). At the time I got to it however kubernetes was not helpful anymore:

~~~~
$ kubectl --context production-admin -n signals-service-gateway describe svc nginx
Name:			nginx
Namespace:		signals-service-gateway
Labels:			<none>
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"name":"nginx","annotations":{"service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled...
			service.beta.kubernetes.io/aws-load-balancer-access-log-enabled=true
			service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name=collaborne-logs
			service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix=signals-service-gateway/nginx/
			service.beta.kubernetes.io/aws-load-balancer-backend-protocol=tcp
			service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled=true
			service.beta.kubernetes.io/aws-load-balancer-proxy-protocol=*
Selector:		infrastructure=nginx-ingress-controller
Type:			LoadBalancer
IP:			10.3.0.100
Port:			http	80/TCP
NodePort:		http	31964/TCP
Endpoints:		
Port:			https	443/TCP
NodePort:		https	32490/TCP
Endpoints:		
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  2d		4m		839	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  2d		4m		830	service-controller			Warning		CreatingLoadBalancerFailed	(events with common reason combined)
~~~~

"Events with common reason combined" is lovely ... but: what is the reason? :)

I couldn't find any proper message even when watching the events of that namespace, as even then it would just give that useless text. At this point the load balancer existed in the AWS console, but without instances. This further confused me.

Eventually I nuked the service, waiting for the deletion, and then added it again. It turns out that at least initially kubernetes does log the errors:
~~~~
  4m		4m		1	service-controller			Warning		CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service signals-service-gateway/nginx: Unable to update load balancer attributes during attribute sync: ValidationError: S3Bucket prefix cannot start or end with slash
~~~~

**What you expected to happen**:

Kubernetes provides me with the message, in such a way that I can debug and fix the problems.

For example give me ways to un-deduplicate messages (and sort them by "happened-when", not "happened-how-long-ago-last", please!), or somehow make sure to not kill the actual reason information.

**Comment by kensimon** [comment] 2017-05-16 21:11
I've been looking at some of the event usability/bugs lately, I'll start looking at this.

**Comment by kensimon** [comment] 2017-05-16 21:33
My guess is that the original message was GC'd but the subsequent message wasn't for some reason, since you say you didn't look at it until a long time later.  Events are API object like any other and they get GC'd.  This is my guess at least.

How long between when the issue and when you looked at the event list?

**Comment by timothysc** [comment] 2017-05-16 21:45
@ankon

**Comment by kensimon** [comment] 2017-05-17 16:35
Opened a new issue (#45971) to address the root cause here, because this same issue can happen for any event.  I'll put further thoughts on the design problems in that issue.  IMO you can leave this open and consider it closed only when #45971 is, or you can close it as a duplicate.

Thanks for your report!

**Comment by thockin** [comment] 2017-05-19 05:17
Thanks, @kensimon !  Events can use some love, for sure.

**Comment by ankon** [comment] 2017-05-19 07:00
For the record: I can't say for sure how long these events existed, could have well been a day or more.

**Comment by thockin** [comment] 2017-05-27 04:00
Closing in favor of #45971

**Closed by thockin** 2017-05-27 04:00 UTC
Labels: kind/bug, sig/network
