### ISSUE TITLE
kubernetes-cli 1.21.1 does not build on apple arm

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/kubernetes#102146] opened 2021-05-19 17:00 UTC
#### What happened:

kubernetes-cli 1.21.1 does not build on apple arm

#### What you expected to happen:

Build should be green like the previous release.

#### How to reproduce it (as minimally and precisely as possible):

See Homebrew/homebrew-core#77160

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MacOS 11-arm
- Kernel (e.g. `uname -a`):
- Install tools: brew
- Network plugin and version (if this is a network-related bug):
- Others:

---

<details>
<summary>build error log</summary>

```
==> make WHAT=cmd/kubectl
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
+++ [0512 21:40:32] Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
Generating prerelease lifecycle code for       27 targets
Generating defaulter code for       89 targets
Generating deepcopy code for      227 targets
Generating conversion code for      124 targets
Generating openapi code for AGGREGATOR
Generating openapi code for KUBE
Generating openapi code for APIEXTENSIONS
Generating openapi code for CODEGEN
Generating openapi code for SAMPLEAPISERVER
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10256d9d4]
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2572610187
relates to https://github.com/Homebrew/homebrew-core/pull/77160

**Comment by BenTheElder** [comment] 2021-05-19 18:51
this isn't specific to arm. you need gnu coreutils to run the build scripts, it's failing because it's trying to use gnu date options. a lot of the scripts use gnu options. in this case it's related to reproducible builds and setting SOURCE_DATE_EPOCH. IIRC homebrew could also set SOURCE_DATE_EPOCH to avoid this.

**Comment by BenTheElder** [comment] 2021-05-19 18:52
xref: https://github.com/kubernetes/kubernetes/pull/100044

**Comment by BenTheElder** [comment] 2021-06-23 09:15
https://github.com/Homebrew/homebrew-core/commit/fc81390368122d805938778c164f7a19b3641f59 fixed by having GNU utilities in path at build time.

**Closed by BenTheElder** 2021-06-23 09:15 UTC
Labels: kind/bug, kind/support, needs-triage, sig/cli
