### ISSUE TITLE
gci-gce-scalability tests fail due to "watch closed before Until timeout"

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56064] opened 2017-11-20 14:51 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/priority failing-test
Umbrella issue: #56062 
@kubernetes/sig-scalability-bugs 

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8136 failed with:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:191
scaling { ReplicationController} load-small-163
Expected error:
    <*errors.errorString | 0xc420ecfc30>: {
        s: "error while scaling RC load-small-163 to 2 replicas: watch closed before Until timeout",
    }
    error while scaling RC load-small-163 to 2 replicas: watch closed before Until timeout
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:592
```

@shyamjvs this error message sounds a little like a transient failure that should be retried, rather than cause the test to fail. Or am I misunderstanding it?

**Comment by shyamjvs** [comment] 2017-11-20 15:48
I suppose so. It seems like as part of our RC scale operation, we're first setting the replica count to the new value and then watching until the desired count matches the actual no. of replicas. Ref:

https://github.com/kubernetes/kubernetes/blob/98fb71e8ce2caa3062f3f0b0ed4ab470683f5578/pkg/kubectl/scale.go#L233-L246

Ideally, before returning with an error at the end, we should check if it's a `watch.ErrWatchClosed` error and then retry the watch (if we still have some timeout left).
Besides, there's a TODO in the watch Until() function saying,

https://github.com/kubernetes/kubernetes/blob/98fb71e8ce2caa3062f3f0b0ed4ab470683f5578/staging/src/k8s.io/apimachinery/pkg/watch/until.go#L72

I think the behaviour there should be so.

cc @kubernetes/sig-api-machinery-misc @wojtek-t

**Comment by ncdc** [comment] 2017-11-20 15:54
See: https://github.com/kubernetes/kubernetes/pull/50102

**Comment by shyamjvs** [comment] 2017-11-20 15:56
Also, seems like the kubectl Scale() function logic is different for RCs from others (i.e RS, jobs, deployments, etc). For others we're doing periodic polling to check the condition:

https://github.com/kubernetes/kubernetes/blob/98fb71e8ce2caa3062f3f0b0ed4ab470683f5578/pkg/kubectl/scale.go#L313

Should we move all of them also to watch or move RC to polling?

**Comment by shyamjvs** [comment] 2017-11-20 16:01
That's great @ncdc - just what I was wanting :)
And for https://github.com/kubernetes/kubernetes/issues/56064#issuecomment-345738834, I'll file another issue.

**Comment by wojtek-t** [comment] 2017-11-20 16:19
wait.Until is know to be broken:
https://github.com/kubernetes/kubernetes/issues/31345

So this is pretty much duplicate of that issue

**Comment by lavalamp** [comment] 2017-11-30 21:23
cc @jpbetz

**Comment by porridge** [comment] 2017-12-04 07:06
More failure(s):
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-release-1-7/474

**Closed** 2018-02-28 12:54 UTC
Labels: kind/bug, priority/failing-test, sig/api-machinery, sig/scalability
