### ISSUE TITLE
Configmap pretty display

### ISSUE THREAD

**Issue by tsn77130** [kubernetes/kubernetes#36222] opened 2016-11-04 11:10 UTC
**Kubernetes version** : 

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+coreos.0", GitCommit:"f6f0055b8e503cbe5fb7b6f1a2ee37d0f160c1cd", GitTreeState:"clean", BuildDate:"2016-08-29T17:01:01Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

```

**What happened**:

When I try to display configmap content with yaml output (kubectl get configmap webapp-inifile -o yaml), the output is sometimes pretty, and sometimes not -depending newlines are effectively displayed or not - just \n char-

I can't find what's the difference between some file and some others. (limit on numer of lines ?)

Configmap is created with --from-file option

Ex : 
```
apiVersion: v1
data:
  int.ini: "###\n# app configuration\n# http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/environment.html\n###\n\n[global]\nenv
    = INT\n\n[app:main]\nuse = egg:ihm\n\npyramid.reload_templates
    = true\npyramid.debug_authorization = false\npyramid.debug_notfound = false\n
...
```

**What you expected to happen**:

More human readable display, in order to be able to easily change parameter when kubectl edit congifmap
```
###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/environment.html
###

[global]
env = INT

[app:main]
use = egg:ihm

pyramid.reload_templates = true
pyramid.debug_authorization = false
```

**How to reproduce it** : 

```
kubectl create configmap webapp-inifile --from-file=/apps/webapp/int.ini
kubectl get configmap webapp-inifile -o yaml / kubectl edit configmap webapp-inifile
```

**Comment by brendandburns** [comment] 2016-11-21 06:26
Hrm, this seems to me like the right answer is to special case 'kubectl edit' for configmaps, rather than try to hack around with the YAML decoder.

I suppose we could use block quotes (e.g. `|`) if we see newlines but that seems error prone...

**Comment by brendandburns** [comment] 2017-02-24 06:40
Closing this, pretty print is there, kubectl configMap edit support is there.

**Closed by brendandburns** 2017-02-24 06:40 UTC
Labels: area/kubectl, priority/important-soon, team/ux (deprecated - do not use)

**Comment by jeremyeder** [comment] 2017-09-08 18:42
This still happens on kube 1.7 :-(

I'm not 100% sure how to reproduce, but what I did was:
- have an existing configmap
- ```kubectl edit configmap ...``` and edit a few lines
- exit the editor
- ```kubectl edit configmap``` ... now I see the ```\n``` characters instead of actual newlines.
- even ```kubectl get configmap ... -o yaml``` shows the ```\n``` characters

**Comment by thedch** [comment] 2017-09-26 21:15
I'm also seeing this issue in kube 1.7. During the past few days I have edited a configmap ~110 times, and seen the formatting get destroyed (spaces messed up, `\n` characters visible) twice. I can't determine anything specific that I did in those two edits that would have triggered the formatting messup.

**Comment by tsn77130** [comment] 2017-09-27 07:55
I'm still seeing this issue too.
Pushed a lot of identical configmaps, some ones are displaying good, and some other bad.

For example, I have a configmap with 3 files in ; they all are identical except one variable ; 2 of them display normally, and the last one displays with \n ...

**Comment by rileytg** [comment] 2017-10-18 22:39
also seeing this issue on 1.7

**Comment by rileytg** [comment] 2017-10-18 22:48
can we reopen this issue? or open a new one?

**Comment by transient1** [comment] 2017-11-29 03:39
I created a brand new configmap using 
`kubectl create configmap my-map --from-file file1 --from-file file2`

and when I viewed the yaml with `kubectl get configmap my-map -oyaml` it's full of \n characters and escape characters. This makes it very difficult to edit.

**Comment by Haybu** [comment] 2018-03-12 03:14
I am experiencing the same. \n character is messing up a configmap I'm creating with --from-file option. Anyone found a reason why this is happening ?

**Comment by lpzdvd** [comment] 2018-03-22 17:05
Also failing in 1.8.4

**Comment by jimmythedog** [comment] 2018-05-10 07:55
It seems strange to me that this is closed, when it is clearly still an issue
A configmap created from a yaml file that uses the [literal style](http://yaml.org/spec/1.2/spec.html#id2795688) i.e. the pipe symbol, is then almost unreadable with 'kubectl get -o yaml', and difficult to edit with kubectl

**Comment by tutaidalal** [comment] 2018-06-13 17:00
I am also facing the same issue of formatting .. I have a application configuration of 400-500 lines. Tryied many times. For fist 40-50 lines the format is good ans easily readable.. However, when i try to create config for entire configuration file its very difficult to edit the config map..

**Comment by huguesalary** [comment] 2018-09-11 20:33
Same issue here. No idea what makes one configmap show better than another.

**Comment by arafatmohammed** [comment] 2018-09-14 19:54
This issue corrupted my **aws-auth** configMap that authenticates my user to access the EKS cluster and now I am locked out of my EKS cluster.

**Comment by pastukhov** [comment] 2018-09-26 08:41
1.11
Still same

**Comment by corbeen** [comment] 2018-10-01 09:35
still same ( there is an example if install helm install stable/prometheus , you will find cm/prometheus-server )

**Comment by jimmythedog** [comment] 2018-10-03 10:29
I agree with @lleontop - I can recreate it every time
If you were to execute the following (ensuring *no* trailing spaces), the configmap remains "pretty"
```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
data:
  test.properties: |-
    abc=def
    xyz=123
kind: ConfigMap
metadata:
  name: test-for-formatting
EOF
```
However, repeat the above (or edit the existing one with `kubectl`), and put a trailing space after one of the key/value pairs, and that then messes up the configmap contents

**Comment by dotw** [comment] 2018-10-12 06:16
Can we reopen this issue? I need this feature to change the yaml in cm, and I have been struggling with the intent and \n for several days ...

**Comment by kashline** [comment] 2018-10-16 13:58
Please reopen this ticket, it's incredibly frustrating to have to deal with this even on small configmaps

**Comment by sylr** [comment] 2018-10-26 13:31
Got this also. I had to remove **tabs** from my config file to get the yaml multiline display.

**Comment by mrrandrade** [comment] 2018-11-05 22:18
Just created a messed up configmap on kuberntes 1.12.2.

**Comment by mwmix** [comment] 2018-11-20 12:40
Likewise.

**Comment by amimof** [comment] 2018-11-28 12:11
> I agree with @lleontop - I can recreate it every time
> If you were to execute the following (ensuring _no_ trailing spaces), the configmap remains "pretty"
> 
> ```
> cat <<-EOF | kubectl apply -f -
> apiVersion: v1
> data:
>   test.properties: |-
>     abc=def
>     xyz=123
> kind: ConfigMap
> metadata:
>   name: test-for-formatting
> EOF
> ```
> However, repeat the above (or edit the existing one with `kubectl`), and put a trailing space after one of the key/value pairs, and that then messes up the configmap contents

OMG thank you!

**Comment by sfitts** [comment] 2018-12-10 20:18
Just ran into this in EKS (1.10.3) -- highly annoying.  I have one config map that will come out OK if I use create directly, but if I pipe the output of `create --dry-run -o yaml` to apply then it gets munged.  Does seem like this is something that needs addressing.

**Comment by dozer47528** [comment] 2018-12-29 09:06
> Got this also. I had to remove **tabs** from my config file to get the yaml multiline display.

Have the same issue and fixed by removing tabs

**Comment by vsavinkov** [comment] 2019-02-08 10:16
Have the same issue, don't have any tabs in file. This issue totally should be reopened.

**Comment by v-i-o** [comment] 2019-02-08 16:47
This issue is valid and I am not sure why it was closed

**Comment by dfiduk** [comment] 2019-03-01 12:44
Not only spaces. Trail symbols too.

I uses vim for it
`:set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣`
`:set list`

**Comment by PabloPie** [comment] 2019-03-01 15:08
"\n   \n" in one of my files also messed up the pretty display.

**Comment by aguilarm** [comment] 2019-03-18 17:16
Created a new issue when I hit this again and was able to repro using the trailing whitespace

**Comment by vsavinkov** [comment] 2019-03-20 13:32
I've removed all the trailing whitespaces and tabs. The problem is gone.

**Comment by dfiduk** [comment] 2019-03-20 16:30
Check any possible special chars. It solve my problem some time ago

ср, 20 мар. 2019 г., 16:34 Viacheslav Savinkov <notifications@github.com>:

**Comment by preddys75** [comment] 2019-03-27 20:06
I have seen this issue in K8 1.7 -> 1.13

kubectl create configmap $CM_NAME -n $NAMESPACE --from-file=$PATCH_FILE --dry-run=true --output=yaml

where PATCH_FILE is attached file below. I renamed it from .json to .log so this webpage would let me include it.

[fb_vanilla_template.log](https://github.com/kubernetes/kubernetes/files/3015083/fb_vanilla_template.log)

**Comment by hardwaysun** [comment] 2019-05-03 23:51
Solve the issue by delete whitespace at each end of line.

**Comment by richstokes** [comment] 2019-05-08 22:52
The output of `get configmaps` is ugly. Wether using json or yaml, k8s injects a whole bunch of escape characters and messes up the formatting of the original config file. 

It would be very nice to have a switch that tells it to dump the config out "normally"!

**Comment by pauloeliasjr** [comment] 2019-05-29 22:32
I added a new line in a configMap using Tab for identation. After using Spaces instead of Tab, I was able to see the configmap as expected...

**Comment by qbaze** [comment] 2019-07-10 19:29
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

Same here, white space/s at the end of line ruin the output, all back to normal when white space/s removed.

**Comment by mrrandrade** [comment] 2019-11-02 06:08
Since I've still met this on 1.16, I'll point a bullet list of the regular culprits for the configmap messing:

- spaces before newline:

```
# cat -A will display a $ at the end of every line, so it'll be visually more pleasing than a regular grep.
cat -A < configmap.yaml | grep ' \$$'
``` 

- Tabs: 
```
# cat -T will show your tabs as ^I.
cat -T < configmap.yaml | fgrep '^I'
```

- Special characters like ãẽõ, áéó, öß will also mess your files. Look up for them in your comments, they might pass through!

**Comment by Nurza** [comment] 2019-11-14 16:27
An easy one liner to remove trailing whitespaces in a ConfigMap:

`kubectl get -o yaml cm [YOUR CONFIGMAP NAME] | sed -E 's/[[:space:]]\\n/\\n/g' | kubectl apply -f -`

**Comment by tomershukhman** [comment] 2020-01-20 08:41
Please reopen.
This issue still remains.
This format makes eks aws-auth configmap very hard to maintain.
Once the file is applied with trailing whitespaces the whole thing gets lots of \n and \.

As a temporary measurement is there a way to reformat the configmap in the "readable" way? after the \n are created?
@Nurza way didn't reformat the file for me.

**Comment by wdoekes** [comment] 2020-01-20 08:46
Nurza's method works. But you may have a space before EOF as well: `...last-line<SPACE>"`
Or you may have CR's in there `...\r\n...`, in which case you should remove the CRs.
Or you may have a TAB, which you should replace with one or more spaces.

**Comment by tomershukhman** [comment] 2020-01-20 09:20
@wdoekes  No CR/TAB/new lines.
I have a "clean" file that after I apply it all works great. (display as expected)
After I add one trailing white space to it, it gets those \n.
I tried to run Nurza's method but it didn't work.
Any other Ideas why Nurza's method is not working for me ?

This a part of the output I'm getting with` kubectl edit`

```
apiVersion: v1
data:
  mapRoles: "- rolearn: arn:aws:iam::000000000000:role/eksctl-tomer-test-cluster1-nodegr-NodeInstanceRole-OE604HKJ194S\n
    \ username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers
    \n    - system:nodes\n- rolearn: arn:aws:iam::000000000000:role/k8-admin\n  username:
    k8-admin\n  groups:\n    - system:masters\n"
kind: ConfigMap
```

**Comment by wdoekes** [comment] 2020-01-20 09:29
` - system:bootstrappers` has a space after it, although you don't see it.

```
ZGF0YToKICBtYXBSb2xlczogIi0gcm9sZWFybjogYXJuOmF3czppYW06OjAwMDAwMDAwMDAwMDpy
b2xlL2Vrc2N0bC10b21lci10ZXN0LWNsdXN0ZXIxLW5vZGVnci1Ob2RlSW5zdGFuY2VSb2xlLUFB
QUFBQUFBQUFBQVxuCiAgICBcIHVzZXJuYW1lOiBzeXN0ZW06bm9kZTp7e0VDMlByaXZhdGVETlNO
YW1lfX1cbiAgZ3JvdXBzOlxuICAgIC0gc3lzdGVtOmJvb3RzdHJhcHBlcnMKICAgIFxuICAgIC0g
c3lzdGVtOm5vZGVzXG4tIHJvbGVhcm46IGFybjphd3M6aWFtOjowMDAwMDAwMDAwMDA6cm9sZS9r
OC1hZG1pblxuICB1c2VybmFtZToKICAgIGs4LWFkbWluXG4gIGdyb3VwczpcbiAgICAtIHN5c3Rl
bTptYXN0ZXJzXG4iCg==
```
Because the LF is on the next line, there must be a space before it.

**Comment by tomershukhman** [comment] 2020-01-20 09:34
Correct but if I run Nurza's method the \n are still there.
Am I still missing anything?
This is what I run
`kubectl get -n kube-system -o yaml cm aws-auth | sed -E 's/[[:space:]]+\\n/\\n/g' | kubectl apply -f -`

**Comment by wdoekes** [comment] 2020-01-20 09:38
Nobody said that sed expression was perfect. Once you know this is your doing -- and you know how to fix it -- you're not bothered by this behaviour anymore.

**Comment by thapakazi** [comment] 2020-02-17 07:07
This is scary shit :hankey: 
 ... **what is the industry practice to edit the file like these: aws-auth...?**

I managed to type 20+lines by hand :disappointed:  and it worked on 3rd attempt :disappointed_relieved:

**Comment by mrrandrade** [comment] 2020-02-28 22:24
> ... **what is the industry practice to edit the file like these: aws-auth...?**

Cant' say about the 'like this', but aws-auth you can use eksctl to do the hard work for you:

```
eksctl get iamidentitymapping [arn]
eksctl create iamidentitymapping <arn> [--username USER] [--groups GROUP0,GROUP2]
eksctl delete iamidentitymapping <arn>
```

**Comment by mayurkumar09** [comment] 2020-07-09 14:12
If the formatting of cm goes wierd a simple hack to get it back to normal is :

- kubectl get cm configmap_name -o yaml > cm.yaml

- Now copy the contents of cm.yaml file and past it on yamllint.com. Yamllint.com is powerful tool to check the linting of yaml files.
This will provide you with the configmap as expected with correct formatting.

- Paste the output in another yaml file (for e.g -  cm_ready.yaml)

- kubectl apply -f cm_ready.yaml

**Comment by akunaatrium** [comment] 2020-07-24 10:44
Anyone knows why the issue is closed? It's not fixed as far as I can tell.

**Comment by 86label** [comment] 2020-07-30 06:58
If you just want the raw output as it was read in when created --from-file, you can use jq to get the raw string (without escaped newlines etc)
If you created a configmap from a file like this:
`kubectl create configmap myconfigmap --from-file mydata.txt`

Get the data:
`kubectl get cm myconfigmap -o json | jq '.data."mydata.txt""' -r`

@akunaatrium

**Comment by brylor** [comment] 2020-08-27 19:00
Edited a cm, came back in, and had \n all over. 

Something about white space in my previous edit? 

Not great overall :/

On

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alexjuchina** [comment] 2020-10-09 06:22
> If the formatting of cm goes wierd a simple hack to get it back to normal is :
> 
> * kubectl get cm configmap_name -o yaml > cm.yaml
> * Now copy the contents of cm.yaml file and past it on yamllint.com. Yamllint.com is powerful tool to check the linting of yaml files.
>   This will provide you with the configmap as expected with correct formatting.
> * Paste the output in another yaml file (for e.g -  cm_ready.yaml)
> * kubectl apply -f cm_ready.yaml

Awesome, very good website~

**Comment by sriharshakx** [comment] 2020-10-19 17:19
> I agree with @lleontop - I can recreate it every time
> If you were to execute the following (ensuring _no_ trailing spaces), the configmap remains "pretty"
> 
> ```
> cat <<-EOF | kubectl apply -f -
> apiVersion: v1
> data:
>   test.properties: |-
>     abc=def
>     xyz=123
> kind: ConfigMap
> metadata:
>   name: test-for-formatting
> EOF
> ```
> 
> However, repeat the above (or edit the existing one with `kubectl`), and put a trailing space after one of the key/value pairs, and that then messes up the configmap contents

Thank You very much

**Comment by stepanselyuk** [comment] 2020-11-17 21:55
I was able to fix this behavior by:

1) Don't use tabs, convert to spaces
2) To remove spaces before a newline character, use this:
```
 sed -i -E 's/[[:space:]]+$//g' File.ext
```
It seems also will convert CRLF to LF only.

**Comment by wcarss** [comment] 2021-02-09 23:05
Something small that exacerbates this issue is that in python's standard lib module `json`, up to some version (I think python 3.4, see https://bugs.python.org/issue16333), pretty printing adds a trailing space after every comma by default, unless you supply a list of separators yourself that omit the spaces (e.g. like `json.dumps(data, True, indent=4, separators=(",",":")`)

So if you have old-ish glue (e.g. python 2.7) that parses a k8s configmap into a file for archival purposes, and you made that file readable by pretty-printing it, using that file to regenerate a new configmap results in this gross escape behaviour.

**Comment by somaninga-pujari** [comment] 2022-03-07 08:10
Hello There,
One of our colleague has edited configmap with wrong data, now whole cluster inaccessible with any of role, need help on immediate basis and much appreciated.
Error:
through eksctl - Error: getting auth ConfigMap: Unauthorized
through  kubectl error: You must be logged in to the server (Unauthorized)

**Comment by saiskee** [comment] 2022-03-08 19:22
yaml marshallers will write a string to a multiline string e.g.
multiline_string: |
  some string!
  with new lines and \ no need to escape things
UNLESS
1. The string contains a \t character
2. The string terminates in a space character
2. The string contains a substring which matches the regex `\n[ ]+\n`

**Comment by CC11001100** [comment] 2022-06-21 03:44
Also reproduce in v1.22.3   :(

**Comment by Auggie321** [comment] 2022-06-23 02:57
I occasionally encountered this problem in v1.15.6 or v1.21.2, 
but eventually I was able to deal with it by using edit and then using vim's own set list to back-propagate 
the original static configmap code configuration under gitlab to see 
if there were extra spaces, and then modifying the local configmap file based on the online configmap's set list display under edit. 

The state of the online configmap under edit, to modify the local configmap file, is ultimately able to deal with this problem, 
but if there is a better official way to do it would be good.

**Comment by MartinKosicky** [comment] 2022-06-30 10:44
> ession was perfect. Once you know this is your doing -- and you know how to fix it -- you're not bothered by this behaviour anymore.

yes if you are working on linux

**Comment by samermassoud** [comment] 2022-07-25 17:32
i would like to share an observation that helped me sort out the line merging and \n.
it appears to be related to the last line of the file you are using (--from-file=file.conf) 
if the last line ends with empty space or tab. the config map is merged up in one line with \n as line feed
if  you remove the empty space from the last line, the ConfigMap will import file as is with |- or |+

**Comment by piyumisudusinghe** [comment] 2022-07-26 02:50
I got the same error after editing the ConfigMap file. I use an online tool to remove the trailing white space that we cannot see in the text. After copying the content which removed trailing whitespaces I was able to resolve this issue

**Comment by jainpratik163** [comment] 2023-08-08 07:48
in v1.24 also i can see same issue.
how we can edit cm with many lines.

**Comment by chao-luo** [comment] 2023-11-09 15:15
Finally, I found that the absence of a value defined in valus.yaml will cause the \n issue.

**Comment by GentleSong** [comment] 2024-03-19 11:55
delete space before \n or after \n
it works for me

**Comment by jainpratik163** [comment] 2024-03-31 06:45
did anyone find solution when we edit cm how we can see in proper format as for me really difficult to edit cm as we have many \n char and I can still see this issue in k8s version 1.28
