### ISSUE TITLE
kubectl logs should lookup by ip as well

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#32286] opened 2016-09-08 13:47 UTC
As shown in https://youtu.be/8cirvYVhRoI?t=18m6s, `kubectl logs` relies on the default DNS resolver to resolve the node name when getting logs. This shouldn't be the case, `kubectl logs` should query by node ip instead.

The relevant code is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/strategy.go#L302-L339

I consider this a bug fix. Can we get this into v1.4? I'll open a PR.

cc @pwittrock @liggitt @caesarxuchao @csrwng @smarterclayton @lavalamp @janetkuo @errordeveloper

**Comment by liggitt** [comment] 2016-09-08 13:52
no, discussion of resolution of the node is ongoing, and a change in master<->node communication will be very disruptive. this also affects exec and attach. a proposed fix is in https://github.com/kubernetes/kubernetes/pull/25532/, where the nodeName is no longer required to be DNS-resolveable, and the kubelet hostname/hostname-override/cloud-provider-resolved hostname is used instead

**Comment by liggitt** [comment] 2016-09-08 13:52
dupe of https://github.com/kubernetes/kubernetes/issues/22063

**Closed by liggitt** 2016-09-08 13:52 UTC

**Comment by luxas** [comment] 2016-09-08 14:06
Thanks for the fast response @liggitt! Now I don't have to reinvent the wheel :)
