### ISSUE TITLE
e2e flake: [k8s.io] PersistentVolumes NFS volume can be created, bound, retrieved, unbound, and used by a pod

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#25294] opened 2016-05-07 01:26 UTC
Immediately after this test was reenabled in #25128 we got huge numbers of parallel flakes in `kubernetes-e2e-gce`. This might be a coincidence. I'll make a PR to move it to flaky. If things haven't improved after it's moved then I'll revert, else I'll assign this issue to @jsafrane.

![ss](https://cloud.githubusercontent.com/assets/7368979/15089494/00f277ea-13b9-11e6-94db-c568d47adfbb.jpg)

**Comment by jsafrane** [comment] 2016-05-09 07:25
Do you have any logs? #25295 references #20550, but that has nothing to do with NFS nor PersistentVolumes.

**Comment by spxtr** [comment] 2016-05-09 17:22
[Here's one](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce/16352).

It's pretty clear this test caused the flakes we were seeing.

**Comment by jsafrane** [comment] 2016-05-31 07:20
@spxtr, do you have any logs?

**Comment by spxtr** [comment] 2016-05-31 22:16
It hasn't flaked since your fix went in, but we should keep the issue open until it's moved out of the flaky suite.

**Comment by matchstick** [comment] 2016-06-07 00:59
The fix Joe Finney developed was merged on 5/30. 

The signature for the problem in the log file referenced here is:

**```May`  6 18:56:07.895: Expected PersistentVolume to be bound, but got nil ClaimRef: kind:"" apiVersion:"" ```**

It looks like from this dashboard the last instance of this error log signature for the test **PersistentVolumes NFS test to the flaky suite.** was on 5/30 right around the time the code was merged. I found the [error test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-flaky/10266) off the dashboard at https://k8s-testgrid.appspot.com/k8s#gke-flaky

Since then the error has not occurred with that signature since I am tempted to close this bug, but keep the the test suite as marked "Flaky". The merge bot should start flagging the new bugs for this test going forward.

**Comment by spxtr** [comment] 2016-06-07 01:02
If it's no longer flaky we should move it out of the flaky suite. While it's in the flaky suite it won't block merges if it breaks and mergebot won't open bugs for it. 

I'm worried that if we just close this issue it'll sit in the flaky suite and break and noone will notice for a long time.

**Comment by jsafrane** [comment] 2016-08-04 15:54
This bug has not been reproduced for past 2 months, can we close it?

**Comment by spxtr** [comment] 2016-08-04 17:07
It looks like the test is still in the flaky suite, although with a different name. Once it's moved out of there then this can be closed.

**Comment by jsafrane** [comment] 2016-08-30 10:39
Not reproduced for three months, closing.

**Closed by jsafrane** 2016-08-30 10:39 UTC
Labels: kind/flake, team/cluster
