### ISSUE TITLE
Flaky build failure

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#27500] opened 2016-06-15 23:55 UTC
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27083/kubernetes-pull-build-test-e2e-gce/44892/

```
+++ [0615 16:38:35] Docker builds done
+++ [0615 16:39:34] Building tarball: server linux-arm
+++ [0615 16:39:35] Starting Docker build for image: kube-apiserver
+++ [0615 16:39:35] Starting Docker build for image: kube-controller-manager
+++ [0615 16:39:35] Starting Docker build for image: kube-scheduler
+++ [0615 16:39:35] Starting Docker build for image: kube-proxy
+++ [0615 16:39:35] Starting Docker build for image: federation-apiserver
+++ [0615 16:39:35] Starting Docker build for image: federation-controller-manager
name invalid: Requested repository does not match bearer token resource: google_containers/debian-iptables-arm
!!! Error in /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../build/../build/common.sh:858
  '"${DOCKER[@]}" build -q -t "${docker_image_tag}" ${docker_build_path} > /dev/null' exited with status 1
Call stack:
  1: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../build/../build/common.sh:858 kube::release::create_docker_images_for_server(...)
  2: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../build/../build/common.sh:777 kube::release::package_server_tarballs(...)
  3: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../build/../build/common.sh:705 kube::release::package_tarballs(...)
  4: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../build/release.sh:49 main(...)
Exiting with status 1
```

**Comment by spxtr** [comment] 2016-06-21 16:59
I think it's a dupe of #27451, already fixed.

**Closed by spxtr** 2016-06-21 16:59 UTC
Labels: kind/flake, team/test-infra
