### ISSUE TITLE
Setting up prometheus stack is failing in (some) presubmits

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#76490] opened 2019-04-12 07:53 UTC
e.g. this one:
```
W0412 05:03:54.874] F0412 05:03:54.874151   81303 clusterloader.go:205] Error while setting up prometheus stack: error while applying (/go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml): timed out waiting for the condition
```

Priority urgent, because it's blocking some merges.

**Comment by wojtek-t** [comment] 2019-04-12 08:00
This is another example:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/1116038326881619976/build-log.txt

**Comment by mm4tt** [comment] 2019-04-12 08:03
Will disable prometheus to unblock presubmits until we figure out what is going on

**Comment by mm4tt** [comment] 2019-04-12 09:16
For the later failure you linked, it seems that scheduler wasn't able to schedule the prometheus-k8s pod. Scheduler log:

```
I0410 18:24:08.442034       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-hlcl8 is bound successfully on node e2e-big-beta-minion-group-p8bg, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:24:25.143178       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:24:25.143251       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:24:25.155927       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-7f2jg is bound successfully on node e2e-big-beta-minion-group-3hvn, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:24:41.194393       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:24:41.194488       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:24:41.208597       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-lp2f4 is bound successfully on node e2e-big-beta-minion-group-xs71, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:24:50.491919       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:24:50.492028       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:24:50.508382       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-n858v is bound successfully on node e2e-big-beta-minion-group-ctn2, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:00.472412       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:00.472484       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:00.512913       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-d28cb is bound successfully on node e2e-big-beta-minion-group-6bw3, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:10.319925       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:10.320023       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:10.346688       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-kb2gk is bound successfully on node e2e-big-beta-minion-group-9jm0, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:19.364175       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:19.364250       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:19.375575       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-rctnh is bound successfully on node e2e-big-beta-minion-group-6wzv, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:31.805798       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:31.805867       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:31.842234       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-lfhvq is bound successfully on node e2e-big-beta-minion-group-5dg2, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:45.454685       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:45.454788       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:45.465215       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-tm7mb is bound successfully on node e2e-big-beta-minion-group-pzs8, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:25:54.227546       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:25:54.227615       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:25:54.243404       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-cgx8f is bound successfully on node e2e-big-beta-minion-group-vj8s, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:26:16.199037       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:26:16.199122       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:26:16.218291       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-z5wjh is bound successfully on node e2e-big-beta-minion-group-91d4, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:26:37.489914       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:26:37.490005       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:26:37.506851       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-f64ss is bound successfully on node e2e-big-beta-minion-group-r1vl, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:26:54.881017       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:26:54.881104       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
I0410 18:26:54.901365       1 scheduler.go:572] pod kube-system/fluentd-gcp-v3.2.0-zfzml is bound successfully on node e2e-big-beta-minion-group-460b, 101 nodes evaluated, 1 nodes were found feasible
E0410 18:27:09.776293       1 factory.go:660] Error scheduling monitoring/prometheus-k8s-0: pod has unbound immediate PersistentVolumeClaims (repeated 100 times); retrying
E0410 18:27:09.776379       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
```

**Comment by wojtek-t** [comment] 2019-04-12 09:21
The original thing is from this one:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/75474/pull-kubernetes-kubemark-e2e-gce-big/1116560766443458560/

**Comment by mm4tt** [comment] 2019-04-12 09:37
The presubmit failure is something else, it looks like it failed to created endpoints object.

```
W0412 05:03:41.849] I0412 05:03:41.849396   81303 framework.go:189] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
W0412 05:03:41.893] I0412 05:03:41.893235   81303 framework.go:189] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/prometheus-service.yaml
W0412 05:03:41.939] I0412 05:03:41.939112   81303 framework.go:189] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/prometheus-serviceAccount.yaml
W0412 05:03:41.979] I0412 05:03:41.978879   81303 framework.go:189] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/prometheus-serviceMonitor.yaml
W0412 05:03:42.021] I0412 05:03:42.021175   81303 prometheus.go:139] Exposing kube-apiserver metrics in kubemark cluster
W0412 05:03:42.222] I0412 05:03:42.222651   81303 framework.go:189] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml
W0412 05:03:54.874] F0412 05:03:54.874151   81303 clusterloader.go:205] Error while setting up prometheus stack: error while applying (/go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml): timed out waiting for the condition
```

In the kube-apiserver.log I see errors like
```
I0412 05:03:42.002655       1 wrap.go:47] PUT /apis/apps/v1/namespaces/monitoring/deployments/prometheus-operator/status: (2.456541ms) 200 [kube-controller-manager/v1.15.0 (linux/amd64) kubernetes/a75b7cd/system:serviceaccount:kube-system:deployment-controller [::1]:57512]
I0412 05:03:42.006572       1 wrap.go:47] PATCH /api/v1/namespaces/monitoring/pods/prometheus-operator-6ddc98bd97-6jg7c/status: (4.442369ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/a75b7cd 35.231.250.210:55654]
I0412 05:03:42.283457       1 wrap.go:47] GET /api/v1/namespaces/kubemark: (1.407868ms) 404 [kube-apiserver/v1.15.0 (linux/amd64) kubernetes/a75b7cd [::1]:56718]
I0412 05:03:42.284102       1 wrap.go:47] POST /api/v1/namespaces/kubemark/endpoints: (54.506111ms) 404 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.56.175:48810]
```

It looks like the `kubemark` namespace didn't exist... How is that possible in a kubemark test?

**Comment by mm4tt** [comment] 2019-04-12 09:52
The presubmit issue doesn't seem related to Prometheus. The test would fail even if there is no prometheus. The root cause was broken kubemark setup.
It looks like the kubemark failed during setting up hollow-nodes (to be more precise during building docker images):
```
I0412 04:59:35.775] Succeeded to gcloud compute disks.
I0412 04:59:35.876] time="2019-04-12T04:59:35Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: connection refused"
I0412 04:59:35.877] context canceled
I0412 04:59:35.880] Makefile:28: recipe for target 'build' failed
I0412 04:59:35.881] make: *** [build] Error 1
W0412 04:59:35.981] Attempt 1 failed to make gcloudpush . Retrying.
I0412 04:59:36.913] WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
I0412 04:59:40.939] docker build --pull -t gcr.io/k8s-presubmit-scale/kubemark:2eddb5 .
I0412 04:59:44.846] time="2019-04-12T04:59:44Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: connection refused"
I0412 04:59:44.847] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0412 04:59:44.851] Makefile:28: recipe for target 'build' failed
I0412 04:59:44.851] make: *** [build] Error 1
W0412 04:59:44.952] Attempt 2 failed to make gcloudpush . Retrying.
I0412 04:59:54.866] docker build --pull -t gcr.io/k8s-presubmit-scale/kubemark:2eddb5 .
I0412 04:59:58.060] time="2019-04-12T04:59:58Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: connection refused"
I0412 04:59:58.139] context canceled
I0412 04:59:58.144] Makefile:28: recipe for target 'build' failed
I0412 04:59:58.144] make: *** [build] Error 1
W0412 04:59:58.245] Attempt 3 failed to make gcloudpush . Retrying.
W0412 05:00:13.170] Failed to make gcloudpush .
I0412 05:00:14.779] Created [https://www.googleapis.com/compute/v1/projects/k8s-presubmit-scale/zones/us-east1-b/instances/e2e-75474-ac87c-kubemark-master].
I0412 05:00:14.950] WARNING: Some requests generated warnings:
I0412 05:00:14.954] - Disk size: '20 GB' is larger than image size: '10 GB'. You might need to resize the root repartition manually if the operating system does not support automatic resizing. See https://cloud.google.com/compute/docs/disks/persistent-disks#repartitionrootpd for details.
I0412 05:00:14.955] - The resource 'projects/cos-cloud/global/images/cos-beta-73-11647-64-0' is deprecated. A suggested replacement is 'projects/cos-cloud/global/images/cos-beta-73-11647-75-0'.
I0412 05:00:14.955]
I0412 05:00:15.063] NAME ZONE MACHINE_TYPE PREEMPTIBLE INTERNAL_IP EXTERNAL_IP STATUS
I0412 05:00:15.063] e2e-75474-ac87c-kubemark-master us-east1-b n1-standard-16 10.40.0.10 34.73.186.106 RUNNING

...


W0412 05:03:39.957] I0412 05:03:39.956807 81303 cluster.go:56] Listing cluster nodes:
W0412 05:03:39.985] I0412 05:03:39.985675 81303 prometheus.go:86] Setting up prometheus stack

```


To compare this is how a good kubemark run looks like
```
I0412 06:40:32.077] Succeeded to gcloud compute disks.
I0412 06:40:32.869] WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
I0412 06:40:34.318] Sending build context to Docker daemon 141.6MB
I0412 06:40:34.328] Step 1/2 : FROM debian:jessie
I0412 06:40:35.493] jessie: Pulling from library/debian
I0412 06:40:35.674] bf295113f40d: Pulling fs layer
I0412 06:40:36.683] bf295113f40d: Verifying Checksum
I0412 06:40:36.684] bf295113f40d: Download complete
I0412 06:40:41.841] bf295113f40d: Pull complete
I0412 06:40:41.862] Digest: sha256:201b887113d1190ed7811152af4c14f46a7ce8612dfdaee540fc353f5135d25a
I0412 06:40:41.872] Status: Downloaded newer image for debian:jessie
I0412 06:40:41.872] ---> 7cd9fb1ee74f
I0412 06:40:41.872] Step 2/2 : COPY kubemark /kubemark
I0412 06:40:49.890] ---> f9ffee87eb32
I0412 06:40:49.946] Successfully built f9ffee87eb32
I0412 06:40:49.957] Successfully tagged gcr.io/k8s-presubmit-scale/kubemark:yl4wsm
I0412 06:40:49.960] docker push gcr.io/k8s-presubmit-scale/kubemark:yl4wsm
I0412 06:40:50.555] The push refers to repository [gcr.io/k8s-presubmit-scale/kubemark]
I0412 06:40:50.573] d7370df7b66e: Preparing
I0412 06:40:50.574] 9abb3997a540: Preparing
I0412 06:40:50.755] 9abb3997a540: Layer already exists
I0412 06:41:02.115] d7370df7b66e: Pushed
I0412 06:41:04.064] yl4wsm: digest: sha256:b4b84a09b34f8b8728d233b697e2a529ce510b0a4a9438ff9c55b9ed60f39880 size: 741
I0412 06:41:04.096] Succeeded to make gcloudpush .
I0412 06:41:04.160] Created and uploaded the kubemark hollow-node image to docker registry.
I0412 06:41:04.824] namespace/kubemark created
I0412 06:41:05.170] configmap/node-configmap created
I0412 06:41:05.586] secret/kubeconfig created
I0412 06:41:05.607] Setting up kube-dns
I0412 06:41:06.143] replicationcontroller/heapster-v1.3.0 created
I0412 06:41:06.187] service/kube-dns created
I0412 06:41:06.227] serviceaccount/kube-dns created
I0412 06:41:06.268] configmap/kube-dns created
I0412 06:41:06.312] deployment.apps/kube-dns created
I0412 06:41:06.935] replicationcontroller/hollow-node created
I0412 06:41:06.946] Created secrets, configMaps, replication-controllers required for hollow-nodes.
I0412 06:41:10.350] Waiting for all hollow-nodes to become Running

...

W0412 06:44:02.410] I0412 06:44:02.410216 88913 cluster.go:56] Listing cluster nodes:
W0412 06:44:02.411] I0412 06:44:02.410667 88913 cluster.go:68] Name: hollow-node-24cwj, clusterIP: 10.64.1.6, externalIP: , isSchedulable: true
W0412 06:44:02.411] I0412 06:44:02.410677 88913 cluster.go:68] Name: hollow-node-24xvb, clusterIP: 10.64.2.42, externalIP: , isSchedulable: true
...
```

**Comment by mm4tt** [comment] 2019-04-12 09:54
To summarize, Prometheus is a red herring here. The kubemark cluster failed to start and this is the actual culprit here.
The start-kubemark.sh should fail if it's not able to set-up a fully operational kubemark cluster, it shouldn't ignore the setup errors.
We can also change CL2 to fail if there are no nodes detected in the cluster.

**Comment by mm4tt** [comment] 2019-04-12 12:45
I think we can close this bug and re-enable prometheus.
The presubmit issue is not related to prometheus at all.
The other failure seems to be a one-off PV/PVC issue, not sure if it's severe / frequent  enough to keep the prometheus disabled everywhere because of it.

**Comment by mm4tt** [comment] 2019-04-12 12:55
@misterikkit, could you take a look and explain how should we understand the error message we see in https://github.com/kubernetes/kubernetes/issues/76490#issuecomment-482502283, i.e.
```
E0410 18:25:10.320023       1 scheduler.go:481] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 100 times)
```

**Comment by mm4tt** [comment] 2019-04-18 12:32
@misterikkit, friendly ping :)

**Comment by mm4tt** [comment] 2019-05-09 13:13
@misterikkit, another one :) Could you take a look?

**Comment by sttts** [comment] 2019-05-09 17:18
Fighting with this as well: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/77207/pull-kubernetes-kubemark-e2e-gce-big/1125824885537378312

**Comment by mm4tt** [comment] 2019-07-16 12:15
The prometheus issue is fixed, regarding the scheduler issue we don't have logs for it anymore. Will reopen a dedicated scheduler issue if it occurs again.
/close

**Closed by mm4tt** 2019-07-16 12:15 UTC
Labels: kind/bug, priority/critical-urgent, sig/scalability
