### ISSUE TITLE
Investigate load balancer pod failure in gce / coreos / rkt environment

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#20529] opened 2016-02-03 00:50 UTC
cc/ @yifan-gu for more detail information.

**Comment by yifan-gu** [comment] 2016-02-03 07:28
cc @sjpotter This is solved when dns works correctly, right? Ref https://github.com/kubernetes/kubernetes/pull/20302

**Comment by sjpotter** [comment] 2016-02-03 07:35
yes, but I have had a terrible time testing anything in GCE today, I
figured out what the problem is, it seems when docker tries to start up
many times there's a problem with a bridge device and the docker unit just
keep restarting and the master never makes any progress.

**Comment by yifan-gu** [comment] 2016-02-24 17:59
I believe this is fixed after #20302 , so closing for now.

**Closed by yifan-gu** 2016-02-24 17:59 UTC
Labels: dependency/rkt, priority/P1, team/node
