### ISSUE TITLE
Pod can't access API - Unauthorized (10.2.0.1)

### ISSUE THREAD

**Issue by clanstyles** [kubernetes/kubernetes#26477] opened 2016-05-28 07:58 UTC
I'm not sure what the problem is. I'm trying to get an ingress controller to work. It seems that unversioned.NewInCluster() is failing. I then checked logs and see a lot of

```
time="2016-05-28T07:52:51Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://10.2.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://10.2.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\", retrying in 47.824953813s" 
```

I then kubectl exec -it ... /bin/bash 'ed into the pod to try and run the following command, found here http://stackoverflow.com/questions/30690186/how-do-i-access-the-kubernetes-api-from-within-a-pod-container 

```
KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1beta3/namespaces/default/pods/$HOSTNAME
```

This also confirms it's unauthorized.

How are tokens created? What would cause a pod to have proper access?

**Comment by zhouhaibing089** [comment] 2016-05-29 09:16
> How are tokens created?

The token was generated for each service account, which you could see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L267-L292)

> What would cause a pod to have proper access?

As mentioned above, each service account have at least one token, and it exists as a secret, whenever you start a pod, this secrets(contains a token) would mount as a volume at `/var/run/secrets/....`, you could check that, and the token is authenticated at [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/serviceaccount/jwt.go#L124-L220)

**Comment by cackharot** [comment] 2017-01-07 21:07
Faced the same issue recently. But finally figured out the cause and solution to the issue. 

Each namespace has one service token (named *default-token-xxxx*) and all pods in the same namespace get that token mount at `/var/run/secrets/kubernetes.io/serviceaccount/token` this is signed by the `/srv/kubernetes/server.key` file where kube-apiserver/kube-controller-manager runs aka cluster-master node.

When you recreate the master node `/srv/kubernetes/*` keys are regenerated, but the secrets store are not recreated using the new key, so all the mounted old tokens (which are signed by old server.key) are no longer valid.

You can also see lots of error from kube-apiserver.log:
```
handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
```

Solution: Manually delete all the *default-token-xxxx* in the config secrets and update the pods.

To Debug the token verification:
* Copy the `/var/run/secrets/kubernetes.io/serviceaccount/token` from your misbehaving pod
* Copy the `/srv/kubernetes/server.cert` from the cluster master node
* Use https://jwt.io/ to verify the signature or write a sample jwt verifier to test them.

**Comment by spzala** [comment] 2017-08-17 19:20
@clanstyles hi, seems like this is an user error. Can you please see if the solution provided by @cackharot works for you? If so, would you please close the issue?  https://stackoverflow.com/questions/ask/advice?tags=kubernetes is a good place to ask questions for a quick help. Thanks!

**Comment by liggitt** [comment] 2017-09-23 21:26
closing for lack of information

**Closed by liggitt** 2017-09-23 21:26 UTC
Labels: sig/auth, team/control-plane (deprecated - do not use)
