### ISSUE TITLE
Kubernetes v1.4.3 master deployed 135 nodes, after that the master node inaccessible. 

### ISSUE THREAD

**Issue by kvchampa** [kubernetes/kubernetes#35229] opened 2016-10-20 19:52 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Kubernetes deployed nodes limitation.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): v1.4.3 Server and v1.5.0-alpha Client.

**Environment**:
- **Cloud provider or hardware configuration**: Huawei Bare metal Server
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 3.16
- **Install tools**: python, htop, etcd 2.1
- **Others**: none

**What happened**: Master node deployed Worker/Node reach 135 Nodes. Now you can't access to master node anymore e.g. $kubectl get node 
errors message: Unable to connect to Server: dial tcp [::1]:8080: i/o timeout.

**What you expected to happen**: Should be able to execute $kubectl get node with no issue.

Unable to connect to Server: dial tcp [::1]:8080: i/o timeout.
**How to reproduce it** (as minimally and precisely as possible):Assume that  your config-default.sh with more than 150 nodes. then execute $KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

**Anything else do we need to know**: None

**Comment by ymqytw** [comment] 2016-11-09 00:18
@kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment] 2016-11-09 01:17
Can you log into the master machine and see if the apiserver is running? Or crashing?

**Comment by techtonik** [comment] 2017-05-26 05:17
Can this be reproduced?

**Comment by smarterclayton** [comment] 2017-06-01 18:49
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 18:49 UTC
Labels: area/apiserver, sig/api-machinery
