### ISSUE TITLE
federated deployments can't handle app label properly

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#45673] opened 2017-05-11 18:08 UTC
Creating two federated deployments with the same app label (nginx in my case) will cause the deployments to have wrong spreading of replicas. This doesn't happen in the regular k8s api server. 

How to reproduce:
1 - Create a deployment. I've used this template
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-fed
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
2 - Check on the 2 underlying clusters if the replicas are spread 50-50 
```
root@henrique-fed-1:~/run_app# k get deploy --context=fed
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed   6         6         0            6           28s
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes1
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed       3         3         3            3           26s
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes2
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed   3         3         3            3           1m
```
3 - Create an equal deployment just changing the name, keeping the same `app` label
4 - The second deployment replicas were not correctly spread, being all in the first cluster:
```
root@henrique-fed-1:~/run_app# k get deploy --context=fed
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed     6         6         0            6           1m
nginx-deployment-fed-2   6         6         0            6           22s
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes1
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed       3         3         3            3           1m
nginx-deployment-fed-2     6         6         6            6           19s
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes2
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed     3         3         3            3           2m
nginx-deployment-fed-2   0         0         0            0           1m
``` 

In the end, I've created another deploy, (nginx-deployment-fed-3) changing the name and the app label, and it was correctly spread:
```
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes1
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed       3         3         3            3           3m
nginx-deployment-fed-2     6         6         6            6           1m
nginx-deployment-fed-3     3         3         3            0           1s
root@henrique-fed-1:~/run_app# k get deploy --context=kubernetes2
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-fed     3         3         3            3           4m
nginx-deployment-fed-2   0         0         0            0           2m
nginx-deployment-fed-3   3         3         3            3           1m
```
Expected:
Replicas spread in all deployments, even with the same app label

*Kubernetes version** (use `kubectl version`): 1.6.2
Running on-prem federation in some VMs, 2 clusters in the federation
Also happened in GKE fed

**Comment by csbell** [comment] 2017-05-11 18:56
Can you provide replica counts and part of spec -- at least enough to explain what you were expecting and what happened? Thanks.

**Comment by nikhiljindal** [comment] 2017-05-11 20:32
Yes will be great to have exact steps to reproduce including the YAMLs that you used. How many clusters? Did you use preferences annotation?

**Comment by henriquetruta** [comment] 2017-05-12 16:24
@nikhiljindal @csbell just made a far more decent description

**Comment by perotinus** [comment] 2017-08-04 18:44
/unassign perotinus

I'm not working on deployments/replica sets at the moment.

**Comment by quinton-hoole** [comment] 2017-09-02 00:58
@henriquetruta Is this a dupe of #46119

**Comment by irfanurrehman** [comment] 2017-11-06 18:18
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#136.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close

**Closed by irfanurrehman** 2017-11-06 18:18 UTC
Labels: area/federation, kind/bug, priority/important-soon, sig/multicluster
