### ISSUE TITLE
Transition from Service without selector to Service without selector leaves stale/incorrect endpoints

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#97424] opened 2020-12-21 17:17 UTC
**What happened**:

Starting with namespace with no services (but one pod matching app=istiod), create a service:
```
$ ki get svc,endpoints,endpointslice
No resources found in istio-system namespace.
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: istiod
EOF
service/istiod created
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.182.10   <none>        8080/TCP   3s

NAME               ENDPOINTS         AGE
endpoints/istiod   10.244.0.5:8080   3s

NAME                                          ADDRESSTYPE   PORTS   ENDPOINTS    AGE
endpointslice.discovery.k8s.io/istiod-qbzdz   IPv4          8080    10.244.0.5   3s
```
We see endpoint and slice is created properly.

Next, we remove the selector from service
```
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 8080
EOF
service/istiod configured
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.182.10   <none>        8080/TCP   41s

NAME               ENDPOINTS         AGE
endpoints/istiod   10.244.0.5:8080   41s

NAME                                          ADDRESSTYPE   PORTS   ENDPOINTS    AGE
endpointslice.discovery.k8s.io/istiod-jnpqg   IPv4          8080    10.244.0.5   8s
endpointslice.discovery.k8s.io/istiod-qbzdz   IPv4          8080    10.244.0.5   41s
```
We expect the endpoint to be removed. However, it sticks around and for some reason we have a duplicate EndpointSlice.

Manually add an Endpoint into the service
```
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Endpoints
metadata:
  name: istiod
  namespace: istio-system
subsets:
- addresses:
  - ip: 1.2.3.4
  ports:
  - name: http
    port: 8080
EOF
Warning: resource endpoints/istiod is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
endpoints/istiod configured
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.182.10   <none>        8080/TCP   112s

NAME               ENDPOINTS      AGE
endpoints/istiod   1.2.3.4:8080   112s

NAME                                          ADDRESSTYPE   PORTS   ENDPOINTS    AGE
endpointslice.discovery.k8s.io/istiod-jnpqg   IPv4          8080    1.2.3.4      79s
endpointslice.discovery.k8s.io/istiod-qbzdz   IPv4          8080    10.244.0.5   112s
```

One of the slices is now correct, the other one is still unexpected.

Restart the scenario and do the apply in the other order:
```
$ kirm svc,endpoints,endpointslice --all
service "istiod" deleted
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 8080
EOF
service/istiod created
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.69.90   <none>        8080/TCP   2s
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: istiod
EOF
service/istiod configured
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.69.90   <none>        8080/TCP   9s

NAME               ENDPOINTS         AGE
endpoints/istiod   10.244.0.5:8080   1s

NAME                                          ADDRESSTYPE   PORTS   ENDPOINTS    AGE
endpointslice.discovery.k8s.io/istiod-l7xh2   IPv4          8080    10.244.0.5   1s
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 8080
EOF
service/istiod configured
$ ki get svc,endpoints,endpointslice
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/istiod   ClusterIP   10.96.69.90   <none>        8080/TCP   15s

NAME               ENDPOINTS         AGE
endpoints/istiod   10.244.0.5:8080   7s

NAME                                          ADDRESSTYPE   PORTS   ENDPOINTS    AGE
endpointslice.discovery.k8s.io/istiod-l7xh2   IPv4          8080    10.244.0.5   7s
endpointslice.discovery.k8s.io/istiod-pxqw7   IPv4          8080    10.244.0.5   1s
```

**What you expected to happen**:

* Service configuration should be fully declarative; applying `A->B->A` should be the same as applying just `A`. 
* EndpointSlice behavior should match Endpoints

**How to reproduce it (as minimally and precisely as possible)**:

I believe the above config can do it easily, let me know if not.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T22:31:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: kind

**Comment by howardjohn** [comment] 2020-12-21 17:18
/sig network

cc @robscott - mentioning you since this is something you work on I think, not because its blocking me at all.

**Comment by robscott** [comment] 2020-12-21 18:58
Hey @howardjohn, thanks for raising this issue! If I'm understanding this correctly, I think it may be a duplicate of https://github.com/kubernetes/kubernetes/issues/91072. I've added some more context in that issue about ways we could fix this - it's sadly more complicated than it seems on the surface. I'm going to close this but feel free to reopen if the other issue does not actually cover this.

/close

**Closed** 2020-12-21 18:59 UTC
Labels: kind/bug, needs-triage, sig/network

**Comment by aojea** [comment] 2020-12-21 22:28
The new slice is generated by the endpointslicemirroring controller , that is a bug https://github.com/kubernetes/kubernetes/issues/91072
