### ISSUE TITLE
Route53 entries for AWS ELBs

### ISSUE THREAD

**Issue by chbatey** [kubernetes/kubernetes#21397] opened 2016-02-17 16:53 UTC
We have a working version of this that is implemented for the AWS cloud provider.

If the `kubernetes.io/aws-lb-cname-zone` label is set we create a cname in Route53 with the format: `[service-name]-[namespace]-[hosted-zone].[zone]`

We'll be creating a PR for this soon and wanted to get people's opinions (@justinsb).

**Comment by therc** [comment] 2016-02-18 03:23
Shouldn't this be part of an Ingress? I'm working on implementing one, as suggested by @bprashanth.  My first target is SSL-serving load balancers, for services that are not of type LoadBalancer (otherwise either you end up with two ELBs for each service or the Ingress controller will fight with the controller manager to tweak the single ELB's listeners).  Next, Route53 support. Then, managing a pool of nginx instances to implement L7 path routing, like GCE's Ingress controller does.

**Comment by therc** [comment] 2016-02-18 03:32
What I also meant to say is that even if this is merged, since some users might not care about setting up an Ingress and the controller that it requires, we should make sure that there are no surprising behaviours in any of the four possible permutations (with/without label x with/without Ingress). Also, should this be a label or an annotation?

**Comment by bprashanth** [comment] 2016-02-18 05:08
DNS feels like it belongs in Ingress, because you need the hostname in the cert, and to use for things like SNI. Whether we're going to fold L4 into Ingress and deprecate Type=Loadbalancer or not is something we've tabled thus far, but will probably get around to discussing for the next release (there are valid reasons to keep Services as simple backends and express higher level lb/dos/gslb/ingress-y concepts in the Ingress -- services are ill suited to express fanout, which is typicall what one wants with DNS+url paths).

That said, i'd recommend doing whatevers easier at this point (maybe a shared lib that we can re-use in the AWS ingress controller?). IMO this should be an annotation.

**Comment by jmastr** [comment] 2016-06-10 07:17
@therc +1 Are there any updates about Route53 support? Thanks for the SSL ELB support btw.

**Comment by manojlds** [comment] 2016-10-07 10:48
What's the best approach to setup private/public elbs with Route53? Currently I have to handle them via Terraform, which means that I cannot have any random service in k8s served via elbs and dns, but have to be predefined externally.

**Comment by timbunce** [comment] 2016-10-12 12:00
Wishlist: Could the DNS name be templated? So rather than mandate one particular format, like `[service-name]-[namespace]-[hosted-zone].[zone]`, people could use a template that suits their needs. For example `{{.service}}-{{.namespace}}-{{.clustername}}`.

**Comment by danielwhatmuff** [comment] 2016-11-11 04:12
Has this been implemented? Are there any docs for the label mentioned above - kubernetes.io/aws-lb-cname-zone

**Comment by sachincab** [comment] 2016-12-05 16:15
Will this be part of 1.5 release?

**Comment by deitch** [comment] 2016-12-19 09:21
Been looking for this for a while. It is great that k8s automatically sets up the ELB, but you needs to take a manual step to retrieve the assigned AWS hostname and then create a CNAME.

Any update?

**Comment by nitro3v** [comment] 2016-12-23 14:19
+1

**Comment by jsravn** [comment] 2017-01-09 11:57
I'm one of the original authors of the PR for this. If you really want you can try cherry picking the last commit in https://github.com/kubernetes/kubernetes/pull/23576.

But we've long ago moved to using ingress. As originally discussed, that's the "right way" in kubernetes to handle external DNS. Our WIP is at https://github.com/sky-uk/feed - to use, create an ELB, then run the ingress controller and dns controller to manage a hosted zone. Then external DNS entries are managed via ingress resources. There is a similar effort going on in kops and k8s (https://github.com/kubernetes/ingress/tree/master/controllers/nginx).

I still see the utility in this for small clusters (as you hit the ELB limits very quickly otherwise), and it shouldn't be too much work for someone to pick up the work done so far.

**Comment by deitch** [comment] 2017-01-09 12:10
> But we've long ago moved to using ingress. As originally discussed, that's the "right way" in kubernetes to handle external DNS.

@jsravn so how do you have it configured? Assuming you start a `Service` that can have anywhere from 1-1000s (or more) of pods in its deployment, what actually routes the traffic in from the external world, and how are you configuring it? Is the ingress controller just managing ELB, or do you have actual proxies (e.g. nginx) set up, and if so, what is connecting to them? 

> create an ELB, then run the ingress controller and dns controller to manage a hosted zone. Then external DNS entries are managed via ingress resources

... which sounds like you create a single ELB separately (manually or CFN or tf), but what does it connect to and how is it configured?

**Comment by pawelprazak** [comment] 2017-01-13 10:31
Is there an ETA on this?

BTW, as a workaround I implemented a simple AWS Lambda with boto3 and CloudWatch Events triggering it on AddTag event.

**Comment by jsravn** [comment] 2017-01-13 12:11
@deitch controller manages an nginx instance which does virtual host routing. Can be scaled horizontally by attaching more to the single ELB.

**Comment by deitch** [comment] 2017-01-13 12:17
@jsravn 
> controller manages an nginx instance which does virtual host routing. Can be scaled horizontally by attaching more to the single ELB.

ingress controller creates and manages one or more nginx instances that act as app load balancers in front of the service? But those, in turn, need routable IPs. Are those fronted by ELB?

**Comment by jsravn** [comment] 2017-01-13 12:19
@deitch yep ELB is the front-end.

**Comment by deitch** [comment] 2017-01-13 12:24
> yep ELB is the front-end
So traffic flows Internet --> ELB --> nginx --> pods?

1. What do you gain by having nginx in here as opposed to ELB --> pods ? Is it just that k8s does a better job controlling nginx with an ingress controller, as opposed to trying to manage ELB directly?
2. How do you have ELB configured to talk to nginx?
3. Do you gain any benefits over NodePort if it is talking to nginx anyways?

Put it another way: when you spin up a new service, you need to spin up (or configure existing) nginx to handle the traffic, and how does ELB get configured then to route correctly to route traffic to nginx?

This thread started because `LoadBalancer` Service Type required a manual step to get the ELB dynamic URL and add it to DNS so client would know where to route. I think you eliminated some of that here, still (densely for me) am missing some of it?

**Comment by anguslees** [comment] 2017-02-20 07:29
Re @bprashanth's comment above: I was expecting to see at least one outraged comment above about how the Internet, Kubernetes, and DNS entries are *not* just for HTTP(S) and so DNS is *not* something that should be configured (only) in Ingress annotations, and something about the music choices of this younger generation.

Did I miss something?  Oh look, now there is such a comment :stuck_out_tongue:

**Comment by deitch** [comment] 2017-02-20 07:38
@jsravn my thinking actually has come around almost a complete 180. I no longer do automatic ELB (or anything else), unless I am doing non-http/https services.

I now have everything defined by Ingress, and use a Traefik or nginx ingress controller cluster-wide. I front it with a single ELB/ALB set to forward all subdomains of `*.somesub.mydomain.com` to the ingress controller's port(s). Since it is wildcard on the cloud load balancer, everything for config that matters ends up being handled by the ingress controller as configured by the Ingress.

The real reason I came around was portability. I wanted configs that could be dropped on minikube, uat, prod, AWS, GCE, etc. as easily as anywhere else. `type=LoadBalancer` made that difficult, adding route53 even more so.

With Ingress, I now have an almost-unified config for everywhere, making microservice development easy. I tell the dev, if your service is public-facing, add an Ingress, if not no; their ingress works wherever we send it.

**Comment by deitch** [comment] 2017-02-20 07:39
> something about the music choices of this younger generation.

LOL! I cannot complain, my kids all like classic rock in addition to more modern stuff. Warms my heart to hear my kid playing Eagles on the guitar or singing Beatles, Motown, etc.

If only I could get them to appreciate Mozart, Beethoven and Bach too....

**Comment by deitch** [comment] 2017-02-26 17:52
> With Ingress, I now have an almost-unified config for everywhere, making microservice development easy. 

I spoke too soon. I got nabbed by the lack-of-wildcard limitation. The latest ingress supports `*.mydomain.com` as the `Host:` part of the ingress, but not `subdomain.*`. That makes it closely tied to the actual final domain, and therefore the config is non-portable between environments. Drat.

**Comment by dlouzan** [comment] 2017-04-28 15:07
How do you handle this case for Internal ELBs? I have a service running in k8s that I would like to make accessible to other internal non-k8s services, so I can't use the service names (those are only available in the k8s network). So for this I am creating a k8s LoadBalancer service using the beta annotation for aws internal elbs. The issue is that afterwards I have to manually create an internal Route53 entry pointing to the internal ELB, so that I can give a meaningful and stable DNS address to the clients of this service.

Any ideas? can this be done automatically by Ingress?

**Comment by deitch** [comment] 2017-04-28 15:10
@dlouzan FWIW, I avoid ELB auto-management entirely. I have ELBs managed separately (mostly tf), and kube components only are responsible for kube. 

I have a terraform kubernetes module I wrote that takes as arguments what input ports it needs and sets up ELBs and security groups and NACLs to support it. Not ideal, but I don't like mixing kubernetes with AWS ELB

**Closed** 2018-02-22 17:25 UTC
Labels: area/platform/aws, lifecycle/rotten, sig/aws, sig/network
