### ISSUE TITLE
Properly partition e2e tests with labels to avoid murkiness around what's running where

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#10548] opened 2015-06-30 15:23 UTC
We need to make sure that at least one of our Jenkins configurations covers each e2e test. If it's never being run by automation, it is going to bit rot and we might as well not have it.

**Comment by zmerlynn** [comment] 2015-06-30 17:05
Amen. Tests that are skipped in every configuration need a bug - they're simply a waste of breath.

**Comment by quinton-hoole** [comment] 2015-06-30 17:49
Completely disagree, unfortunately. We have e2e tests that require an environment other than GCE, and we (Google) don't currently have e2e tests running outside of GCE from Jenkins C.I. yet.  So I think that this issue should be reformulated as a combination of "Run e2e in more environments"  and "enable 3rd parties to share Ci test results".  We have issues for both of those already.  I think that we can close this one?

**Comment by zmerlynn** [comment] 2015-06-30 18:20
@quinton-hoole: This is more referring to tests like Elasticsearch that somehow fell off our radar completely.

**Comment by zmerlynn** [comment] 2015-06-30 18:20
(Not accepting v1.0-post, sorry.)

**Comment by quinton-hoole** [comment] 2015-06-30 18:31
Sorry - I might have misunderstood what is being proposed here.  Is it just the audit being proposed here, or are you proposing deleting all of the e2e tests from the code base if they are not being run by Google's Jenkins C.I. The latter I'm rejecting, but the former is totally reasonable.

**Comment by quinton-hoole** [comment] 2015-06-30 18:34
PS:  Elasticsearch did not fall off our radar.  It's just that it is currently too flaky to provide a reliable signal of regressions, and is hence in the flaky group of tests, explicitly.  Just two days ago I discussed promoting it with @satnam6502 and we decided not to.  As soon as it's reliable (which it might well be by now) and the system is stable (it should be) we can promote it back to the stable set of tests.

**Comment by zmerlynn** [comment] 2015-06-30 18:37
How about the narrower statement: "We need to make sure that at least one of our Jenkins configurations covers each GCE/GKE-capable e2e test."

Is there a bug open for everything that's been demoted? I'm not sure of that.

**Comment by quinton-hoole** [comment] 2015-06-30 18:37
And to be clear, a test being labelled flaky is not necessarily any indication that there is anything wrong with the test.  It's more common for there to be something wrong with the system.  But as long as it's flaky, for either reason, it cannot provide a useful signal indicating regression, and is hence excluded from our set of reliable regression indicators.

**Comment by zmerlynn** [comment] 2015-06-30 18:37
@quinton-hoole: Totally agree with having a sickbay for flaky tests, but if something is perma-sickbayed, it's also bad.

**Comment by quinton-hoole** [comment] 2015-06-30 18:38
@zmerlynn Yes, every GCE-capable test is run in one of e2e-gce, e2e-gce-flaky, e2e-reboot, or e2e scalability.  If that's not the case, it's a bug which I can take responsibility for.  And yes, and audit to confirm this is a good idea, and I can do it.

**Comment by quinton-hoole** [comment] 2015-06-30 19:07
cc @ixdy who's doing a kind of an audit right now.

**Comment by ixdy** [comment] 2015-06-30 19:14
Based on the config in hack/jenkins/e2e.sh, we should hopefully be able to make sure that something demoted to flaky definitely runs in the flaky project; in particular, the e2e-gce project is configured with `--ginkgo.skip=${GCE_DEFAULT_SKIP_TEST_REGEX}|${GCE_FLAKY_TEST_REGEX}` and the gce-e2e-flaky project is configured with `--ginkgo.skip=${GCE_DEFAULT_SKIP_TEST_REGEX} --ginkgo.focus=${GCE_FLAKY_TEST_REGEX}` - so anything that's flaky is skipped in the former and focused in the latter.

The default skip test regex is `Skipped|Density|Reboot|Restart`. I don't immediately recall which tests have `Skipped` in the name, but the `Density` tests should be covered by the gce-e2e-scalability project and the `Reboot` tests by the gce-e2e-reboot project. The `Restart` tests have no project specified in the e2e.sh script, but they might be run in some other project? I'm not sure.

**Comment by ixdy** [comment] 2015-07-01 01:00
There are some inconsistencies in the parallel vs. non-parallel runs that still exist.

Compare the regular expressions:
```bash
# Specialized tests which should be skipped by default for projects.
GCE_DEFAULT_SKIP_TEST_REGEX="Skipped|Density|Reboot|Restart"
# The following tests are known to be flaky, and are thus run only in their own
# -flaky- build variants.
GCE_FLAKY_TEST_REGEX="Addon|Elasticsearch|Nodes.*network\spartition|Service\sendpoints\slatency|Shell.*services|readonly\sPD"
# Tests which are not able to be run in parallel.
GCE_PARALLEL_SKIP_TEST_REGEX="${GCE_DEFAULT_SKIP_TEST_REGEX}|Etcd|NetworkingNew|Nodes\sNetwork|Nodes\sResize"
GCE_PARALLEL_FLAKY_TEST_REGEX="Addon|Elasticsearch|Hostdir.*MOD|Networking.*intra|PD|ServiceAccounts|Service\sendpoints\slatency|Services.*change\sthe\stype|Services.*functioning\sexternal\sload\sbalancer|Services.*identically\snamed|Services.*release.*load\sbalancer|Shell|multiport\sendpoints"
```

`GCE_FLAKY_TEST_REGEX` should be a subset of `GCE_PARALLEL_FLAKY_TEST_REGEX`, but it's not. In particular, the "Service endpoints latency" test is (was) disabled on the sequential builds but not all of the parallel builds (pull had it disabled, post did not); additionally, the "readonly PD" test is disabled in sequential but not parallel, and it's not clear to me if "Nodes.*network\spartition" and "Nodes\sNetwork" are disabling the same things.

**Comment by zmerlynn** [comment] 2015-07-01 01:07
I feel like we should perhaps automatically run those lists through dryrun
and diff them and see what pops out, on a regular basis.

**Comment by wojtek-t** [comment] 2015-07-13 14:10
What we currently have is:

    "GCE_FLAKY_TEST_REGEX="MaxPods.*"

(which is a perfect subset of flaky parallel regexp).
IIUC, we have not all tests running in some set.

Can we close this issue now or is it something still missing here?

**Comment by davidopp** [comment] 2015-07-15 05:53
It seems to me that we definitely run all the e2e tests.

Looking at hack/jenkins/e2e.sh, it seems that everything except what's in ${GCE_DEFAULT_SKIP_TEST_REGEX} is run in either kubernetes-e2e-gce or kubernetes-e2e-gce-flaky:

```
  kubernetes-e2e-gce)
    : ${E2E_CLUSTER_NAME:="jenkins-gce-e2e"}
    : ${E2E_DOWN:="false"}
    : ${E2E_NETWORK:="e2e-gce"}
    : ${GINKGO_TEST_ARGS:="--ginkgo.skip=${GCE_DEFAULT_SKIP_TEST_REGEX}|${GCE_FLAKY_TEST_REGEX}"}
    : ${KUBE_GCE_INSTANCE_PREFIX="e2e-gce"}
    : ${PROJECT:="k8s-jkns-e2e-gce"}
    ;;

  # Runs the flaky tests on GCE, sequentially.
  kubernetes-e2e-gce-flaky)
    : ${E2E_CLUSTER_NAME:="jenkins-gce-e2e-flaky"}
    : ${E2E_DOWN:="false"}
    : ${E2E_NETWORK:="e2e-flaky"}
    : ${GINKGO_TEST_ARGS:="--ginkgo.skip=${GCE_DEFAULT_SKIP_TEST_REGEX} --ginkgo.focus=${GCE_FLAKY_TEST_REGEX}"}
    : ${KUBE_GCE_INSTANCE_PREFIX:="e2e-flaky"}
    : ${PROJECT:="k8s-jkns-e2e-gce-flaky"}
    ;;
```

As for what's in ${GCE_DEFAULT_SKIP_TEST_REGEX}:

```
GCE_DEFAULT_SKIP_TEST_REGEX="\
Skipped|\
Reboot|\
Restart|\
Example\
```

Reboot is tested in kubernetes-e2e-gce-reboot

So the only thing left really is Restart. But as far as I can tell, there are no such tests:

```
find test/e2e -name '*.go' | print | xargs grep Restart
```

So I think it's fine to leave this issue open so that we can automate this verification, but I'm going to move it out of 1.0 because it appears we are definitely running all the e2e tests.

**Comment by ixdy** [comment] 2015-07-17 20:06
Talking with @mbforbes today about GKE vs GCE tests run in Jenkins, we ran across some tests which we may want to confirm we should be skipping. All of the following are for GCE only.

For the density tests, only `Density [Skipped] [Performance suite] should allow starting 30 pods per node` is run regularly. The others are never run anywhere:
* `Density [Skipped] should allow starting 100 pods per node`
* `Density [Skipped] should allow starting 50 pods per node`
* `Density [Skipped] should allow starting 3 pods per node`

The examples test aren't run anywhere yet:
* `Examples e2e [Skipped][Example]Celery-RabbitMQ should create and stop celery+rabbitmq servers`
* `Examples e2e [Skipped][Example]Redis should create and stop redis servers`

The `Namespaces Delete ALL of 100 namespace in 150 seconds` test is disabled, apparently waiting on #7372.

The `Pods should get a host IP` is disabled everywhere, apparently due to #6558

The `Restart` test `Restart should restart all nodes and ensure all nodes and pods recover` isn't running anywhere.

The `Scale` tests don't appear to be running anywhere:
* `Scale [Skipped] should be able to launch 500 pods, 10 per minion, in 25 rcs/thread.`
* `Scale [Skipped] should be able to launch 500 pods, 10 per minion, in 5 rcs/thread.`

The volumes tests are all disabled, apparently needing privileged container support?
* `Volumes [Skipped] GlusterFS should be mountable`
* `Volumes [Skipped] NFS should be mountable`
* `[Skipped] persistentVolumes PersistentVolume`

cc some test authors to make sure this is all expected behavior: @wojtek-t @mwielgus @jayunit100 @quinton-hoole @mbforbes @rrati @jsafrane @markturansky

**Comment by rrati** [comment] 2015-07-17 20:18
We run density 100 pods per node in our test setup, but that's a physical cluster not in gke/gce.   I'm not sure where 3 and 50 are/would used, but I suspect 3 is intended as a quick test and 50 is a target not yet supported (just as is 100).

**Comment by pmorie** [comment] 2015-07-17 20:29
cc @timothysc

**Comment by timothysc** [comment] 2015-07-17 21:34
@ixdy I believe the defaults recently changed, so folks could probably enable all the volumes tests.

**Comment by wojtek-t** [comment] 2015-07-20 06:30
@ixdy our explicit goal for 1.0 is to support 30 pods per node. Thus it is "working as intended" that we are not running tests with more pods per node - the exist to allow people to look how far from supporting that many pods we are.

**Comment by jsafrane** [comment] 2015-07-20 06:54
> The volumes tests are all disabled, apparently needing privileged container support?
>
> Volumes [Skipped] GlusterFS should be mountable
> Volumes [Skipped] NFS should be mountable
> [Skipped] persistentVolumes PersistentVolume


Yes, these need privilege container support.

**Comment by mbforbes** [comment] 2015-07-20 18:57
Given oncalls only really monitor the "standard" GCE run (`kubernetes-e2e-gce`), and we're skipping both 3 pods/node and 30 pods/node tests, should we maybe turn those on for GCE?

For background, here's what we're skipping on the "standard" run:
-  Density [Skipped] [Performance suite] should allow starting 30 pods per node
-  Density [Skipped] should allow starting 3 pods per node
-  Density [Skipped] should allow starting 50 pods per node
-  Density [Skipped] should allow starting 100 pods per node
-  Load capacity [Skipped] [Performance suite] should be able to handle 3 pods per node
-  Load capacity [Skipped] [Performance suite] should be able to handle 30 pods per node

I'm going to turn them on for GKE and get some timing information that might help inform a decision.

**Comment by wojtek-t** [comment] 2015-07-20 19:00
@mbforbes - I don't think these tests make much sense in the GCE/GKE setup - those are purely performance tests so running them on 3-4 node cluster doesn't provide any useful information.
Also, I think that oncall is supposed to look also at gce-scalability suite, so it's not that we are not monitoring it.

**Comment by ixdy** [comment] 2015-07-20 19:00
@mbforbes the ["Critical Builds" tab](http://goto.google.com/k8s-test/view/Critical%20Builds/) includes the gce-scalability project, and I think oncalls are supposed to be using that.

**Comment by mbforbes** [comment] 2015-07-20 20:06
@wojtek-t ah so they're measuring apiserver performance and not node performance? It seems like 30 pods/node would be good to know from a node perspective, but if those tests are purely from a master perspective, then I can see it wouldn't provide data without a large enough cluster.

@ixdy ack—though perhaps we should do scalability on GKE as well?

**Comment by mbforbes** [comment] 2015-07-20 21:46
@wojtek-t @ixdy regarding the scale tests, do we want to enable those for the Jenkins scalability runs? I don't see an action item or issue for them above.

**Comment by ixdy** [comment] 2015-07-21 00:57
I'm not exactly familiar with what the scale tests do, but we should definitely be running them somewhere.

**Comment by mbforbes** [comment] 2015-07-21 06:46
Filed #11658 to run scale tests somewhere

**Comment by davidopp** [comment] 2015-07-21 06:51
I believe they are supposed to be running here
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-scalability/
but it appears it got misconfigured and isn't running anything.

**Comment by wojtek-t** [comment] 2015-07-21 07:03
@mbforbes - yes they are mostly testing apiserver performance (they are testing node performance only implicitly, because we are checking if pods are starting, but the main purpose is to test apiserver performance).

@davidopp - in gce-scalability we are running "Density 30 pods" and "Load capacity" and this is working as intended. I remember that I was looking into "scale" test at some point and decided not to include it into "gce-scalability", but I don't remember the exact reason for it.

**Comment by gmarek** [comment] 2015-07-22 12:18
I tried running those tests and they reliably fail, which is a good reason for not running them. OTOH we probably should debug errors we get, which is something similar to:
```
 Expected error:
      <*errors.errorString | 0x4c208361a10>: {
          s: "Only 9 pods started out of 20",
      }
      Only 9 pods started out of 20
  not to have occurred
```

**Comment by ixdy** [comment] 2015-07-23 18:42
The examples tests are now running in https://goto.google.com/k8s-test/job/kubernetes-e2e-gce-examples/.

**Comment by wojtek-t** [comment] 2015-12-14 19:46
What's the status of this?

@ihmccreery @ixdy - you did a bunch of changes around this recently.
Do you think we can close it? If not, can we state explicitly what needs to be done?

**Comment by roberthbailey** [comment] 2015-12-14 21:15
@jlowdermilk was also looking at jenkins configs recently. 

/cc @spxtr as well

**Comment by ihmccreery** [comment] 2015-12-14 21:32
I've changed the name of this issue to reflect a more sustainable solution than a one-off audit; this is my first work item for 2016.

**Comment by ihmccreery** [comment] 2015-12-22 20:24
As I'm working through this, I'm trying to drive down the number of different ways we partition tests so that it's clearer.  E.g. in #19021, I'm removing the notions of having flaky-in-parallel and flaky-in-gke.  Either a test is flaky or it's not.  While this might seem cumbersome, it will significantly reduce the cognitive load of having to deal with N different partitions of the tests.

**Comment by ihmccreery** [comment] 2016-01-26 23:12
I'm bumping this to P0 as part of the test reliability surge: we need to know where tests are running, and we need to speed up our signal, especially going from failing/flake to passing.

**Comment by ihmccreery** [comment] 2016-01-27 17:58
Remaining action items:

- [ ] get #19667 in to remove provider skip lists
- [ ] remove all `[Skipped]` labels from the suite, and remove docs/filters for it.
- [ ] audit `[Feature:...]` tests and make sure they're all running where they should be

**Comment by ihmccreery** [comment] 2016-02-19 19:35
With #20996 in, there are now instructions on, when branching a release series, how to do an audit of `[Feature:...]` tests (along with a tool to make it a bit easier), so I'm closing this as complete.

**Closed by ihmccreery** 2016-02-19 19:35 UTC
Labels: priority/P0, team/test-infra
