### ISSUE TITLE
Random build failure on fast nodes while saving docker containers into tarballs.

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#40632] opened 2017-01-27 21:57 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): build failures, docker save, rootfs

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): master branch

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I often build k8s locally, and regularly (but not every time) I get errors on the stage of saving built images into tarballs. Log can be seen below.
The more faster servers (more RAM, more CPU cores, faster RAIDs) are, the more often this error occurs. My suspicion that it's not something properly handled in Docker when multiple image operations happened at the same time with "docker build --pull" and "docker save" for the same base image.

```console

$ time make quick-release V=1

+++ [0127 00:48:12] Building tarball: server linux-amd64
+++ [0127 00:48:12] Building tarball: node linux-amd64
+++ [0127 00:48:13] Starting Docker build for image: kube-apiserver
+++ [0127 00:48:13] Starting Docker build for image: kube-controller-manager
+++ [0127 00:48:13] Starting Docker build for image: kube-scheduler
+++ [0127 00:48:13] Starting Docker build for image: kube-aggregator
+++ [0127 00:48:13] Starting Docker build for image: kube-proxy
+++ [0127 00:48:13] Starting build gcr.io/google_containers/kube-proxy:79fd668582fa6a9169eb3fdbfdee3072
+++ [0127 00:48:14] Starting build gcr.io/google_containers/kube-aggregator:9c9e2b8e746ccb22b7df62f77fcb3aba
+++ [0127 00:48:14] Starting build gcr.io/google_containers/kube-scheduler:f6c8ba5b4d591814e77eef4d59c08acc
+++ [0127 00:48:14] Starting build gcr.io/google_containers/kube-controller-manager:ea04ee1098acd54f0084823b5a8bd090
+++ [0127 00:48:14] Starting build gcr.io/google_containers/kube-apiserver:40cbdb82066d7c8cc3f8a51b42d97251
+++ [0127 00:48:32] Starting save gcr.io/google_containers/kube-scheduler:f6c8ba5b4d591814e77eef4d59c08acc
+++ [0127 00:48:32] Starting save gcr.io/google_containers/kube-aggregator:9c9e2b8e746ccb22b7df62f77fcb3aba
Error response from daemon: open /var/lib/docker/devicemapper/mnt/d84a3fbc6929be48b8e9f5cf15475e24cabbee4d2b77166f3e2664cf23943625/r
ootfs/bin/[: no such file or directory
!!! [0127 00:48:32] Call tree:
!!! [0127 00:48:32]  1: /home/kad/go/src/k8s.io/kubernetes/build/lib/release.sh:218 kube::release::create_docker_images_for_server(...)
!!! [0127 00:48:32]  2: /home/kad/go/src/k8s.io/kubernetes/build/lib/release.sh:94 kube::release::package_server_tarballs(.[10/1950]
!!! [0127 00:48:32]  3: build/release.sh:45 kube::release::package_tarballs(...)
+++ [0127 00:48:34] Starting save gcr.io/google_containers/kube-proxy:79fd668582fa6a9169eb3fdbfdee3072
+++ [0127 00:48:36] Save done for gcr.io/google_containers/kube-scheduler:f6c8ba5b4d591814e77eef4d59c08acc
+++ [0127 00:48:36] Deleting docker image gcr.io/google_containers/kube-scheduler:f6c8ba5b4d591814e77eef4d59c08acc
Untagged: gcr.io/google_containers/kube-scheduler:f6c8ba5b4d591814e77eef4d59c08acc
Deleted: sha256:d9a3da02d7b94b670db489f85dd23d8e58506f0614d5716479565869220d6d93
Deleted: sha256:461cef73103703d6787d16593beb50ab3d168a34ea33eeb29bebfcd1201f867b
+++ [0127 00:48:36] Starting save gcr.io/google_containers/kube-controller-manager:ea04ee1098acd54f0084823b5a8bd090
+++ [0127 00:48:37] Starting save gcr.io/google_containers/kube-apiserver:40cbdb82066d7c8cc3f8a51b42d97251
+++ [0127 00:48:39] Save done for gcr.io/google_containers/kube-controller-manager:ea04ee1098acd54f0084823b5a8bd090
+++ [0127 00:48:39] Deleting docker image gcr.io/google_containers/kube-controller-manager:ea04ee1098acd54f0084823b5a8bd090
Untagged: gcr.io/google_containers/kube-controller-manager:ea04ee1098acd54f0084823b5a8bd090
Deleted: sha256:faf42271c473f105895c87cc85530e830f975493b673e5b81e7c6f336f646623
Deleted: sha256:90b838115a6767ab3c16a269e426ffc332c0fad40639171d136613d1e5639b80
+++ [0127 00:48:40] Save done for gcr.io/google_containers/kube-apiserver:40cbdb82066d7c8cc3f8a51b42d97251
+++ [0127 00:48:40] Deleting docker image gcr.io/google_containers/kube-apiserver:40cbdb82066d7c8cc3f8a51b42d97251
Untagged: gcr.io/google_containers/kube-apiserver:40cbdb82066d7c8cc3f8a51b42d97251
Deleted: sha256:922bb48b3904ed60e710dd9206e05046198c668e8cfe8c9cc6f24f1d057540fc
Deleted: sha256:347c51e8e994f85b1b42088b97855033981a2a976d233f30bb6c356f167479d5
+++ [0127 00:48:43] Save done for gcr.io/google_containers/kube-proxy:79fd668582fa6a9169eb3fdbfdee3072
+++ [0127 00:48:43] Deleting docker image gcr.io/google_containers/kube-proxy:79fd668582fa6a9169eb3fdbfdee3072
Untagged: gcr.io/google_containers/kube-proxy:79fd668582fa6a9169eb3fdbfdee3072
Deleted: sha256:8be878e5106e136de094dc956ef7ad1d5a37696301d495b390680a25c4043b4d
Deleted: sha256:5ebc71fd462ad354bd4e44cddee3aaff790318a22e68f2a1f0fb1c7b5fbbc0d2
!!! [0127 00:48:43] previous Docker build failed
!!! [0127 00:48:43] Call tree:
!!! [0127 00:48:43]  1: /home/kad/go/src/k8s.io/kubernetes/build/lib/release.sh:218 kube::release::create_docker_images_for_server(...)
!!! [0127 00:48:43]  2: /home/kad/go/src/k8s.io/kubernetes/build/lib/release.sh:94 kube::release::package_server_tarballs(...)
!!! [0127 00:48:43]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [0127 00:48:43] previous tarball phase failed
Makefile:361: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1
```

**What you expected to happen**:
```console
+++ [0127 22:35:49] Starting build gcr.io/google_containers/kube-aggregator:729ffc22ea0a3b15148fac2e5ba8e959
+++ [0127 22:35:49] Starting build gcr.io/google_containers/kube-proxy:fa17d85fdb40bcf0835c12cb8a69ae5c
+++ [0127 22:35:49] Starting build gcr.io/google_containers/kube-scheduler:67200bb4e488fd377726d383d7a9d34f
+++ [0127 22:35:49] Starting build gcr.io/google_containers/kube-controller-manager:4d2ac5f60682e6a79d01586423e1a3f0
+++ [0127 22:35:49] Starting build gcr.io/google_containers/kube-apiserver:4e2291dd0e839d893db30f0e21c621e4
+++ [0127 22:35:52] Starting save gcr.io/google_containers/kube-apiserver:4e2291dd0e839d893db30f0e21c621e4
+++ [0127 22:35:58] Save done for gcr.io/google_containers/kube-apiserver:4e2291dd0e839d893db30f0e21c621e4
+++ [0127 22:35:58] Deleting docker image gcr.io/google_containers/kube-apiserver:4e2291dd0e839d893db30f0e21c621e4
Untagged: gcr.io/google_containers/kube-apiserver:4e2291dd0e839d893db30f0e21c621e4
Deleted: sha256:180fe1ba9bf432bbc4b4b012b1612cde252206c769713b7afb019d8be307537f
Deleted: sha256:46fe32b1f21e0e85bb02c07cc28c152558d5ab7288607a4c3d26362e0cd56acf
+++ [0127 22:36:02] Starting save gcr.io/google_containers/kube-aggregator:729ffc22ea0a3b15148fac2e5ba8e959
+++ [0127 22:36:05] Save done for gcr.io/google_containers/kube-aggregator:729ffc22ea0a3b15148fac2e5ba8e959
+++ [0127 22:36:05] Deleting docker image gcr.io/google_containers/kube-aggregator:729ffc22ea0a3b15148fac2e5ba8e959
Untagged: gcr.io/google_containers/kube-aggregator:729ffc22ea0a3b15148fac2e5ba8e959
Deleted: sha256:ff1d9666907dfb1308728d9781028cd6b8ede84195c9d24be8dacd355f651945
Deleted: sha256:f487b9de0e669f62403f024ee81d466227a3449a3594029fbebe31aff521a1b1
+++ [0127 22:36:06] Starting save gcr.io/google_containers/kube-scheduler:67200bb4e488fd377726d383d7a9d34f
+++ [0127 22:36:08] Save done for gcr.io/google_containers/kube-scheduler:67200bb4e488fd377726d383d7a9d34f
+++ [0127 22:36:08] Deleting docker image gcr.io/google_containers/kube-scheduler:67200bb4e488fd377726d383d7a9d34f
Untagged: gcr.io/google_containers/kube-scheduler:67200bb4e488fd377726d383d7a9d34f
Deleted: sha256:3c0af356b7541edcfc614a36714a10cc71f509f89a590b1dd4ff7b0cc25bcce8
Deleted: sha256:396e648287c6bfbc58bd5495e8f1246e033a13794d7201612dc8328af9882f10
+++ [0127 22:36:08] Starting save gcr.io/google_containers/kube-proxy:fa17d85fdb40bcf0835c12cb8a69ae5c
+++ [0127 22:36:09] Starting save gcr.io/google_containers/kube-controller-manager:4d2ac5f60682e6a79d01586423e1a3f0
+++ [0127 22:36:11] Save done for gcr.io/google_containers/kube-controller-manager:4d2ac5f60682e6a79d01586423e1a3f0
+++ [0127 22:36:11] Deleting docker image gcr.io/google_containers/kube-controller-manager:4d2ac5f60682e6a79d01586423e1a3f0
Untagged: gcr.io/google_containers/kube-controller-manager:4d2ac5f60682e6a79d01586423e1a3f0
Deleted: sha256:cb22f592f56eb033c3a691be23c13b301bcd2411020b81f7c92ba534aa65b89a
Deleted: sha256:dd1c16fea5bb34b3b81f787dd4a00cfc3d65c96b44e245af827dff895e7f6d01
+++ [0127 22:36:13] Save done for gcr.io/google_containers/kube-proxy:fa17d85fdb40bcf0835c12cb8a69ae5c
+++ [0127 22:36:13] Deleting docker image gcr.io/google_containers/kube-proxy:fa17d85fdb40bcf0835c12cb8a69ae5c
Untagged: gcr.io/google_containers/kube-proxy:fa17d85fdb40bcf0835c12cb8a69ae5c
Deleted: sha256:5288f7df74b0811827855fa19f04e05056b815f9ea1057d39f5b6629ce41f853
Deleted: sha256:2a370f0762733b5d8c2fa446c6edb2a41ced707a6118b6b319f3c605aa4a8d16
+++ [0127 22:36:13] Docker builds done
+++ [0127 22:37:22] Building tarball: final
+++ [0127 22:37:22] Building tarball: test
```

**How to reproduce it** (as minimally and precisely as possible):

Use fast server with fast storage (SSD) and enough cores/RAM to quickly build images.
The faster server and storage is, the bigger probability that "make release" or "make quick-release" will fail with something similar to "Error response from daemon: open /var/lib/docker/devicemapper/mnt/.../rootfs/bin/[: no such file or directory".

**Anything else do we need to know**:

If I disable parallel image build/save in build/lib/release.sh: in function kube::release::create_docker_images_for_server by removing "&", build error not possible to reproduce.

**Comment by calebamiles** [comment] 2017-01-31 00:31
Likely a problem with the container runtime but if someone from @kubernetes/sig-node-bugs could take a look that would be awesome. It would also be great to close this issue if there are no changes to make in tree. Thanks!

**Comment by ramkri123** [comment] 2017-04-28 05:41
Hi Kad,

Many thanks for sharing this issue. I am encountering the exact same isssue in my machine.

>>If I disable parallel image build/save in build/lib/release.sh: in function >>kube::release::create_docker_images_for_server by removing "&", build error not possible to reproduce.

I don't understand your fix. I don't find an "&" in the build/lib/release.sh file. If you can let me know your exact patch it would be much appreciated.

Thanks in advance,
Ramki
email: ramkri123@gmail.com

**Comment by kad** [comment] 2017-04-28 12:53
See my workaround here: https://github.com/kad/kubernetes/commit/550b4cd13d4d0231e00b3fb1381d457a25d57481

**Comment by ramkri123** [comment] 2017-04-28 14:58
Many thanks kad.

**Comment by shiywang** [comment] 2017-06-02 02:28
@calebamiles met the same problem, do we have some ideas how to fix that ? like merge this commit https://github.com/kad/kubernetes/commit/550b4cd13d4d0231e00b3fb1381d457a25d57481?

**Comment by gnufied** [comment] 2017-06-08 14:54
BTW - I hit on the same problem on my relatively fast desktop (4.5Ghz, 32GB RAM). I think the problem is related to loopback device for metadata and data:

```
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
```

Once I configured proper lvm devices as per instruction here - https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/ the error went away.

**Comment by kad** [comment] 2017-06-08 15:03
@gnufied changing storage driver in docker only hides issue, just because it changes timings on parallel operations. With some luck (load on your host or disk i/o load) you will hit it again.
Main problem is actually "docker build --pull" which is executed for same base image in parallel.
In my opinion, this should be fixed in docker code, that pull operation will not replace layer while it is still in use (lock&wait).

**Comment by gnufied** [comment] 2017-06-08 15:19
@kad We are not changing storage driver. It is still devicemapper. What we are changing is, rather than using a file as a blockdevice (mounted via loopback interface), we are giving it a proper block device. 

It is well known and well documented problem at this point - 
1. http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/
2. https://stackoverflow.com/questions/31620825/usage-of-loopback-devices-is-strongly-discouraged-for-production-use

**Comment by kad** [comment] 2017-06-08 16:45
well, to clarify my point: not changing by tuning storage driver. In my case, I'm also using devicemapper over real block devices (RAID) and due to different timings on RAID controllers on different hosts I still see same issues with different frequency.

**Comment by gnufied** [comment] 2017-06-08 18:13
Okay, then - we should open a bug with docker and track it down. I wouldn't claim correlation of my  use case necessary equals causation.

**Comment by kabakaev** [comment] 2018-02-08 16:07
Thanks for debuggin this, @kad.

Build scripts are a bit spahetti: for example, a function that builds tar files, also executes a function that builds docker containers. Therefore, it is not possible to only build tars, one have to build docker containers too.

As i wanted to build a clean release without a "durty" suffix, the workaround was to wrap docker execution under `flock`. This way, k8s git working copy remains clean, but all docker operations are executed sequentially.

```
mkdir -p ~/bin
cat << 'EOF' > ~/bin/docker
#!/bin/bash
# this script prevents parallel execution of docker command
# workaround for https://github.com/kubernetes/kubernetes/issues/40632
# set -x
(
    # wait 11111 seconds before failing to to obtain a lock
    flock -w 11111 9 || exit 1
    /usr/bin/docker "$@"
) 9 > ~/docker-command.lock
EOF
chmod +x ~/bin/docker
export PATH="~/bin:$PATH"
which docker
docker info
make quick-release
```

**Comment by kad** [comment] 2018-02-08 16:57
@kabakaev are you still hitting on that issue ? I haven't seen it for a while, and actually yesterday thinking about to close that issue.

**Closed** 2018-03-10 17:41 UTC
Labels: area/build-release, area/docker, kind/bug, lifecycle/rotten, sig/node, sig/onprem
