### ISSUE TITLE
Passing --device flag to docker run command (and its support in spec file)

### ISSUE THREAD

**Issue by jk-shah** [kubernetes/kubernetes#17066] opened 2015-11-10 18:07 UTC
We seem to have hit a requirement where we need to pass

--device=[]: Allows you to run devices inside the container without the --privileged flag.

Looking at  https://cloud.google.com/container-engine/docs/spec-schema  (which I have been using heavily as I could not see any other current doc) I have not figured how to pass that through the spec file.

Talking to @brendandburns on Mailing list his reply
"
Yes, afaik we don't support that flag currently.  We'd welcome a PR to add support.  Please file an issue on github or send code.

You can use hostDir to mount the device file into your container, but I don't know if the permissions will work correctly if you don't have --privileged set.
"

Filing this GitHub issue as a tracker for this small enhancement.

**Comment by dchen1107** [comment] 2015-11-10 18:27
@jk-shah Thanks for reporting the issue and feel free to send us the pr.

**Comment by urzds** [comment] 2016-06-17 10:24
Is this a duplicate of #5607?

**Comment by thockin** [comment] 2016-11-03 21:17
Dup of #5607 seems right.

**Closed by thockin** 2016-11-03 21:17 UTC
Labels: priority/P2, team/node
