### ISSUE TITLE
Should deleting manifests from /etc/kubernetes/addons delete the RCs/Pods?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23779] opened 2016-04-02 05:07 UTC
I thought this used to work, but I just deleted   `/etc/kubernetes/addons/cluster-monitoring` to get rid of influx and `/etc/kubernetes/addons/fluentd-elasticsearch` to turn off elasticsearch, and the pods/rcs remained.

I had to do this manually:

```
kubectl delete rc --namespace=kube-system elasticsearch-logging-v1
kubectl delete rc --namespace=kube-system kibana-logging-v1
ubectl delete rc --namespace=kube-system monitoring-influxdb-grafana-v3
kubectl delete service --namespace=kube-system elasticsearch-logging
kubectl delete service --namespace=kube-system kibana-logging
kubectl delete service --namespace=kube-system monitoring-grafana
kubectl delete service --namespace=kube-system monitoring-influxdb
```

Is this intended?  Is there a better way?

**Comment by justinsb** [comment] 2016-04-02 05:11
And even that doesn't get rid of fluentd-elasticsearch from the nodes ... so I guess I would have to manually remove it from every pod.

Note to self: For AWS, setting `ENABLE_CLUSTER_LOGGING=false` should prevent ES being installed in the first place.

**Comment by zhouhaibing089** [comment] 2016-04-02 05:55
The addons folder are checked by a service named `kube-addons`, so when you remove the files under `/etc/kubernetes/addons`, you could check the logs.

By the way, this file is mostly you could check: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addon-update.sh

**Comment by bgrant0607** [comment] 2016-04-05 16:49
cc @mikedanese @fgrzadkowski

**Comment by mikedanese** [comment] 2016-04-05 17:26
I am not able to reproduce. Deleting the svc or rc files deletes the addon for me. The sync loop runs every 10 minutes. Maybe you didn't wait long enough? You can kick the sync loop by running `sudo service kube-addons restart`.

https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addons.sh#L22

**Comment by roberthbailey** [comment] 2017-04-25 06:30
Marking as obsolete.

**Closed by roberthbailey** 2017-04-25 06:30 UTC
Labels: sig/cluster-lifecycle, team/control-plane (deprecated - do not use)
