### ISSUE TITLE
LoadBalancer issues on azure k8s v1.16.2 and v1.15.5

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/kubernetes#84052] opened 2019-10-17 14:40 UTC
**What happened**:
We noticed LoadBalancer issues on azure k8s `v1.16.2` and `v1.15.5`.
We use azure `basic` LoadBalancer and create two `LoadBalancer` type k8s services for azure clusters. Both services ultimately get a Public IP created in azure, however the azure LoadBalancer only contains one single Frontend IP Configuration for one of the k8s `LoadBalancer` type services. Thus the other k8s `LoadBalancer` service cannot be reached.

**What you expected to happen**:
All k8s `LoadBalancer` typed services to have a respective Frontend IP Configuration in the azure LoadBalancer.

**Anything else we need to know?**:
We noticed that a change regarding LoadBalancer handling in azure came into both affected k8s versions: https://github.com/kubernetes/kubernetes/pull/82890
Not sure however if this is related or the cause of the regression.

**Environment**:
k8s `v1.16.2` and k8s `v1.15.5`

cc @MSSedusch

**Comment by MSSedusch** [comment] 2019-10-17 14:42
cc @andyzhangx @feiskyer

**Comment by MSSedusch** [comment] 2019-10-17 16:08
From the logs I can see that two services are created almost at the same time. From the Azure Activity Log, the first services is added to the Azure Loadbalancer (frontend config, rules, probes) but is overwritten by an update of the Azure LB to add the second service. The result is that only the second K8s service has a corresponding frontend config, rule and probe. I think this behavior has not changed and could have potentially also happen in older releases before 1.16.2 and 1.15.5.

However, the change in #82890 added a check shouldUpdateLoadBalancer which checks if the service has a frontend config and does not reconcile it if it does not. So in this case, since the frontend config of the first service was overwritten, it will not be reconciled.

Somehow, the etag does not work as expected

**Comment by MSSedusch** [comment] 2019-10-17 16:34
I think I know the root cause. The two K8s services are the "first" services that are created for that cluster. That means there is no Azure Load Balancer and therefore no etag that is used. The two processes that create the K8s services in parallel cannot use an etag since there is no Azure Load Balancer

**Comment by feiskyer** [comment] 2019-10-20 12:08
/assign @chewong

@chewong could you help to take a look?

**Comment by chewong** [comment] 2019-10-21 23:02
I don't think #82890 causes a regression. We only perform `shouldUpdateLoadBalancer` check in `UpdateLoadBalancer` when the service controller detects a change in the number of nodes (i.e. when scaling clusters) and wants to reconcile all the services against the new set of nodes.

@MSSedusch @dguendisch do you have any relevant logs from kube-controller-manager / cloud-controller-manager, or steps I can follow to repro this issue? Thanks

**Comment by dguendisch** [comment] 2019-10-22 09:47
Currently we don't have additional logs (although I can recreate if absolutely needed)
But as an additional information: the issue happens on cluster creation, hence new nodes are getting created along the way.

**Comment by chewong** [comment] 2019-10-23 00:50
After looking at logs provided by @MSSedusch, I think the root cause of the bug is the concurrent-service-syncs flag in your cloud-controller-manager. According to your log, it was set to 10, which means if there were multiple service-related changes queued up for reconciliation, they were processed concurrently.

In your case, since there was no existing Azure Load Balancer when the cluster was created, the two services were making two separate CreateOrUpdateLB requests to the Azure LB client concurrently. They were trying to create a load balancer with the same name but each request only contained one FrontendIPConfiguration. In the end, the latter request would overwrite the load balancer’s existing FrontendIPConfiguration, causing it to only have one FrontendIPConfiguration instead of two.

**Comment by feiskyer** [comment] 2019-10-23 09:32
Thanks @chewong .

@dguendisch could you update concurrent-service-syncs to 1? we would limit the value to 1 in [cloud-provider-azure](https://github.com/kubernetes/cloud-provider-azure/issues/249).

**Comment by dguendisch** [comment] 2019-10-23 12:44
> @dguendisch could you update concurrent-service-syncs to 1? we would limit the value to 1 in [cloud-provider-azure](https://github.com/kubernetes/cloud-provider-azure/issues/249).

@dkistner just changed to `1` in https://github.com/gardener/gardener-extensions/pull/383

**Comment by feiskyer** [comment] 2019-10-29 01:50
Thanks @dguendisch @chewong. I think we can close it now

/close

**Closed by feiskyer** 2019-10-29 01:50 UTC
Labels: area/provider/azure, kind/bug, sig/cloud-provider
