### ISSUE TITLE
ResourceConsumer panic

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#46769] opened 2017-06-01 11:03 UTC
Coming from here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/163

```
I0531 18:28:51.143]   [91m[1mTest Panicked[0m
I0531 18:28:51.143]   [91mruntime error: invalid memory address or nil pointer dereference[0m
I0531 18:28:51.143]   /usr/local/go/src/runtime/asm_amd64.s:514
I0531 18:28:51.143] 
I0531 18:28:51.143]   [91mFull Stack Trace[0m
I0531 18:28:51.143]   	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0531 18:28:51.143]   k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest.func1(0x2e93740, 0xc42115c960, 0xc4211f9d3f)
I0531 18:28:51.143]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:231 +0x5f
I0531 18:28:51.144]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc420212780, 0xc4202f1bf0, 0xc42115c900, 0xc4212c1980, 0x35e87c1)
I0531 18:28:51.144]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:275 +0x70
I0531 18:28:51.144]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc420212780, 0xc4202f1bf0, 0x0, 0x0)
I0531 18:28:51.144]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:191 +0x99
I0531 18:28:51.144]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc420212780, 0xc4202f1bf0, 0xc420212780, 0xc4202f1bf0)
I0531 18:28:51.145]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:216 +0x76
I0531 18:28:51.145]   k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x37e11d600, 0x1bf08eb000, 0xc4202f1bf0, 0x51e3b00, 0xc421396960)
I0531 18:28:51.145]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:205 +0x4d
I0531 18:28:51.145]   k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest(0xc4200b7710, 0x32)
I0531 18:28:51.145]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:244 +0x1d6
I0531 18:28:51.146]   k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).makeConsumeCPURequests(0xc4200b7710)
I0531 18:28:51.146]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:175 +0x328
I0531 18:28:51.146]   created by k8s.io/kubernetes/test/e2e/common.newResourceConsumer
I0531 18:28:51.146]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:137 +0x399
```

@piosz @crassirostris @mwielgus @kubernetes/sig-autoscaling-bugs

**Comment by DirectXMan12** [comment] 2017-06-01 17:22
Have you seen this more than once?  The code along the stack trace isn't particularly illuminating, at a glance?

**Comment by wasylkowski** [comment] 2017-06-08 21:43
@wojtek-t This looks like a duplicate of #47127...

**Comment by wasylkowski** [comment] 2017-06-08 21:44
...and so should be fixed already

**Comment by piosz** [comment] 2017-07-13 09:29
Closing per https://github.com/kubernetes/kubernetes/issues/46769#issuecomment-307236102

**Closed** 2017-07-13 09:29 UTC
Labels: kind/flake, priority/failing-test, sig/autoscaling
