### ISSUE TITLE
Static IP Quota fails multiple upgrade jobs

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43316] opened 2017-03-17 19:01 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**What happened**:
MasterUpgrade test fails due to static IP quota limits across multiple upgrade jobs:
```
Mar 16 22:28:58.162: Failed to allocated static ip e2e-tests-ingress-upgrade-ojx6e-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-cluster/65#k8sio-upgrade-featureupgrade-k8sio-cluster-upgrade-should-maintain-a-functioning-cluster-featureclusterupgrade

**Comment by ixdy** [comment] 2017-03-17 19:17
We were probably leaking static IPs in this project at some point.

It looks like the janitor has already cleaned up the leaked IPs, so I don't think there's anything to do here unless it happens again.

(Are the tests using more than 7 static IPs?)

**Comment by krzyzacy** [comment] 2017-03-17 20:12
[The project looks pretty clean atm](https://pantheon.corp.google.com/compute/quotas?project=k8s-gke-upg-c1-4-c1-6-up-clu) - yeah I'd ask if more than 7 static IPs are used.

**Comment by ixdy** [comment] 2017-03-17 21:10
has this been failing in other jobs?

**Comment by ixdy** [comment] 2017-03-17 21:13
answer: [yes](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Failed%20to%20allocated%20static%20ip)

Given that the failures are very recently cluster, I'm going to guess this was caused by the AppArmor skip panic, and should be fixed by https://github.com/kubernetes/kubernetes/pull/43254.

**Closed by ixdy** 2017-03-17 21:13 UTC
Labels: area/release-infra, kind/upgrade-test-failure, priority/failing-test, team/test-infra
