### ISSUE TITLE
[e2e flake] [sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59527] opened 2018-02-08 03:43 UTC
Back story in https://github.com/kubernetes/kubernetes/issues/54904, but still the top 2nd flake on Velodrome: http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

**Comment by mithrav** [comment] 2018-02-08 03:43
kind/bug

**Comment by mithrav** [comment] 2018-02-08 03:44
/priority failing-test
/priority important-soon
/sig apps
/kind flake
@kubernetes/sig-apps-test-failures

**Comment by mithrav** [comment] 2018-02-26 23:40
Pinging for updates. This is still a top cause of flakiness.

**Comment by soltysh** [comment] 2018-03-09 10:35
So looking at the logs there are 2 problems here actually:

1. Is a bug filled in #59918, where the job controller does not notice a successful run after several retries.
2. The backoff is not getting cleared (#60202) when a successful run happened. 

All in all it looks like the backoff policy is causing both problems. Digging further to get to the actual root cause.

**Comment by soltysh** [comment] 2018-03-09 10:39
So it looks like no. 2 is caused by 1, actually, and since I'm able to reproduce this once in a while locally I'll try to get to the root cause.

**Comment by soltysh** [comment] 2018-03-16 16:07
https://github.com/kubernetes/kubernetes/pull/60985 merged, closing.
/close

**Closed by soltysh** 2018-03-16 16:07 UTC
Labels: kind/flake, priority/failing-test, priority/important-soon, sig/apps
