### ISSUE TITLE
PR builder failing with: Quota 'NETWORKS' exceeded. Limit: 75.0

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#26270] opened 2016-05-25 15:17 UTC
From http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/41958/:

```
+++ Staging server tars to Google Storage: gs://kubernetes-staging-b6e85ca3f3/e2e-gce-agent-pr-5-2-devel
+++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = a9d0980fd8e8964b93de951441da59eb23274b3f)
+++ kubernetes-salt.tar.gz uploaded (sha1 = c6ad0892e67923780b9ed9ac687799a14525082f)
+++ kubernetes-manifests.tar.gz uploaded (sha1 = 31078c562df80a6db7e20e97ec61f975a4c002db)
Creating new network: e2e-gce-agent-pr-5-2
WARNING: You are creating a legacy network. Using --mode=legacy will be required in future releases.
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Quota 'NETWORKS' exceeded. Limit: 75.0
```

**Comment by zmerlynn** [comment] 2016-05-25 15:24
Also here: http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/41956/console, from #26263

**Comment by dims** [comment] 2016-05-25 15:40
@zmerlynn - Are there public logs?

**Comment by zmerlynn** [comment] 2016-05-25 15:54
Here's [one set](https://00e9e64bac9b383fe79e81dc16fe6c4f028f7054d2142492c6-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F26207%2Fkubernetes-pull-build-test-e2e-gce%2F41958%2Fbuild-log.txt?qk=AD5uMEvOoqDhVRAYS_B8q_PnI9ZFDS1S8JYCPUIhmi4HBTNCxghwkB5CVuiLMYE7ESAWd6AzsnUMV30ek8cYvKwJBwlk1DpT7Ka8Xeh9ca5L7VnlnjvEG6utNI2ZHo7kCM3D24NiO1AADs9hA0UyxHWqtwV3eGO5if1Xs4WYu9IIznIcxEEj23dYKNKHjqSnl6Q2jSI_iUJ6xvSLLkUv9AW_M_PnDb2GOV6EPPEYEQok6SLXLlzADX7wonsSpPMSjdcjCQvMXEv4itCq24bErlZEHXAc-uj23xrmbrP4KNKLAVUAlfa4JAFGHnhofzh2VdzkelqukIZf-JOu10oBZtjPMnK0o7mKmLf9EygcVwy-2e0xgF4Z-dDE8BbP5tS2zQGncPaRhnoONmIlhNwIYolUuzgt-6O2IjW4cxMg-ApYQVNx_gH0C9xDCNNi5vpaZBHl44MNtEDdXs3asnv2MhPe_FX9qd9zlsSdRr2HxpFQIAFphC3K6sCvFxYVgJ0CtWQYgeyO_AtOttAmzzF1WRmBIw-Q2Pmvk-gsJSRR9Ropgk_U-TQSxleQ62axbGMxABtG3FWgA-ZhptJ-_TSaP8dkAlNceocevc5CWKmO8_HCw8aSgmFL3l1JyyTVKHiJuobNyO4laTt1KtON4RvFIh0n5M_lPYZfCbEweYz3JL-ohEpxjCZaIqUyJs7kk_sZXVlpIFIHI79Ep1hAYeEBsphd0u4qRq4YTJxMyImxgvM8GPFeZhzZhV2xbDblPV10L3jlBK0bknX_QqliN8lkuogLuQE6Rg_3Lmv0Ki3zKEfICKAmStYVtEhwKrHjFrmH_dI2aNKGOyRV9ljgfXtRG92zfcTTyHb_Khde3sjx6pvblE5kxgh7rTw).

**Comment by euank** [comment] 2016-05-25 17:32
Another set of logs: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25902/kubernetes-pull-build-test-e2e-gce/41986/ from #25902 

```
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Quota 'NETWORKS' exceeded. Limit: 75.0
```

**Comment by yujuhong** [comment] 2016-05-25 17:33
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26272/kubernetes-pull-build-test-e2e-gce/41981/

**Comment by nikhiljindal** [comment] 2016-05-25 18:44
cc @kubernetes/test-infra-maintainers

**Comment by lavalamp** [comment] 2016-05-25 18:49
@ixdy @fejta @spxtr Too many simultaneous runs in one project?

**Comment by alex-mohr** [comment] 2016-05-25 18:57
I chatted with @rmmh who offered to make sure someone on @kubernetes/test-infra-maintainers works on it.

**Comment by alex-mohr** [comment] 2016-05-25 18:59
I wonder if this is a symptom of #26199 fixed by #26208 ?  Presumably have to clean up too even if PR fixes future leaks.

**Comment by ixdy** [comment] 2016-05-25 19:38
The issue is that we create networks and routes based on the Jenkins agent name, but these never get cleaned up by the cluster scripts. @fejta recently renamed all of the Jenkins agents, which resulted in us creating a bunch of new networks and not deleting the old deprecated names.

I'll clean up the old ones now.

**Comment by ixdy** [comment] 2016-05-25 20:01
```
gcloud compute firewall-rules list --project=kubernetes-jenkins-pull --format='value(name)' | grep builder-'[12345]' | xargs gcloud compute firewall-rules delete --project=kubernetes-jenkins-pull
gcloud compute networks list --project=kubernetes-jenkins-pull --format='value(name)' | grep builder-'[12345]'  | xargs gcloud compute networks delete --project=kubernet
es-jenkins-pull
```

Back under quota limits.

**Closed** 2016-08-30 00:17 UTC
Labels: priority/P0, team/test-infra
