### ISSUE TITLE
Prevent regressions after structured logging migration

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#98975] opened 2021-02-10 22:28 UTC
For Structured Logging Migration: https://github.com/kubernetes/enhancements/issues/1602

[Beta graduation criteria:](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging#beta)
- Directories can be marked as migrated, preventing regression via verify script in hack.

#### What would you like to be added:

A tool that takes an input file (similar to the prior `./hack/.golint_failures` file) that takes an allow-list of directories that we expect to only use structured logs, and verify that only structured logging calls are used.

This tool should be written in a way that it can be added to the `./hack/verify.sh` script.

#### Why is this needed:

This tool will ensure, as part of presubmit verification, that any directories marked as "migrated" for structured logging to not regress back to unstructured logging.

ref: https://kubernetes.slack.com/archives/C20HH14P7/p1612466349019900

/sig instrumentation
/milestone v1.21
cc @adisky @navidshaikh

**Comment by ehashman** [comment] 2021-02-10 22:29
/triage accepted
(yes I know that's rude but I'm the chair of these here parts :smile:)

**Comment by adisky** [comment] 2021-02-11 11:12
@ehashman working on it with @navidshaikh
/assign

**Comment by erismaster** [comment] 2021-03-04 03:03
Hello! I am from the Bug Triage team! Code freeze is March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by adisky** [comment] 2021-03-04 03:29
@erismaster yes,  
it is still planned for the release :).

**Comment by serathius** [comment] 2021-03-06 11:44
Based on reviewing structured logging migrations PRs I think we should expand the scope of static analysis tool to check for common errors. For example misuse of `keysAndValues []interface{}` arguments, leaving formating strings `%s` in InfoS, typos in key arguments `podSandBoxID`.

With function prototype based on `[]interface{}` we cannot depend on compiler finding errors, leading to contributors making errors when using InfoS as they are unfamiliar with approach we took to pass arguments. I think this should be a blocker to start scaling migrating to more components thus it should be included in Beta scope.

Question to @ehashman, does this make sense to include it in Beta? should this work in this issue or create a separate one?

**Comment by adisky** [comment] 2021-03-08 06:09
> leaving formating strings %s in InfoS

+1 for this, we can add this.

> misuse of keysAndValues []interface{} arguments, typos in key arguments podSandBoxID.

I am not sure how to approach this, shouldn't we need valid key list for it?

Going to log an issue in klog/logcheck for string check.

**Comment by serathius** [comment] 2021-03-08 08:41
> I am not sure how to approach this, shouldn't we need valid key list for it?

As `klog.InfoS` function prototype is `func(msg string, keysAndValues []interface{})` we can pass anything we like in keysAndValues and compile will not catch this. This led to misuse like this:
``` 
klog.V(2).InfoS("Keeping PVC", "PVC", klog.KRef(pvcNamespace, pvcName), " because it is still being used")
```
We would like to ensure that
* Number of arguments is uneven (`msg +X * (key+value) = 1 + 2X` = always uneven number)
* Argument on uneven index is always string (we should never pass a var or const as key)

**Comment by adisky** [comment] 2021-03-08 08:49
@serathius Thanks, got the idea now !!

**Comment by ehashman** [comment] 2021-03-08 23:16
With #99090 merged I'd say this is done! Might have to do a little cleanup to go back and add migrated directories.

/close

**Closed** 2021-03-08 23:16 UTC
Labels: kind/feature, sig/instrumentation, triage/accepted
