### ISSUE TITLE
kubectl doesn't patch removing serviceAccountName from deployment

### ISSUE THREAD

**Issue by mkrutik** [kubernetes/kubernetes#108208] opened 2022-02-18 11:53 UTC
### What happened?

`kubectl apply -f` doesn't patch removed `serviceAccountName` from the `Deployment` manifest.

### What did you expect to happen?

Removed `serviceAccountName` from `Deployment` must be applied using `kubectl apply -f deployment.yaml` command. (or at least show some warning that it's not applied due to some reasons)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create `Deployment` manifest with any `serviceAccountName` within and apply it.
2. Remove `serviceAccountName` field from `Deployment` and apply it via `kubectl apply -f` command (use `-v=9` to see req/resp logs). 
3. Use `describe` or `get` command to get that `Deployment` and you should find that `serviceAccountName` still exists.

### Kubernetes version

<details>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
-
</details>

### OS version

<details>
Darwin macbook-pro.home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
</details>

### Install tools

<details>
`kubectl` installed via  `brew`
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
-
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
-
</details>

**Comment by knight42** [comment] 2022-02-21 15:57
@mkrutik  `kubectl apply` did remove the `serviceAccountName` field, but it didn't touch another similar but already deprecated field `serviceAccount`, so the `serviceAccountName` field seems to be unchanged.(You could verify this by running `kubectl edit`, only by removing the `serviceAccountName` and `serviceAccount` field at the same time could you unset the service account).

As a workaround, I think you could try `kubectl replace` which updates instead of patching the deployment.

**Comment by fedebongio** [comment] 2022-02-24 17:44
/assign @apelisse @jpbetz 
could either of you take a look / reassign please?
/triage accepted

**Closed** 2022-07-28 23:17 UTC
Labels: kind/bug, sig/api-machinery, sig/cli, lifecycle/rotten, wg/api-expression, triage/accepted

**Comment by zswanson** [comment] 2022-09-29 13:18
For anyone stumbling into this issue, its effectively a dupe of #72519 which was closed with a comment indicating this is somewhat intentional.

> serviceAccountName is defaulted from serviceAccount for backwards compatibility. If you want to remove the fields you must set both to empty explicitly. It is not possible to leave one field unset.
