### ISSUE TITLE
[Failing test] kubemark-500 failing due to no NetworkProgrammingLatency samples

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#90981] opened 2020-05-11 15:10 UTC
**Which jobs are failing**:
ci-kubernetes-kubemark-500-gce-stable3
**Which test(s) are failing**:
load test
**Since when has it been failing**:
2020-05-06
**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.15-500
**Reason for failure**:
`[measurement call NetworkProgrammingLatency - NetworkProgrammingLatency error: got unexpected number of samples: 0]`
**Anything else we need to know**:

/sig sig-scalability
/assign mm4tt

**Comment by mm4tt** [comment] 2020-05-12 10:03
/assign

@hasheddan, it shouldn't be in the v1.19 milestone. The tests that is failing is 1.15 test and the root-cause is in our perf-test infra
/remove-milestone v1.19

**Comment by mm4tt** [comment] 2020-05-12 10:08
It's a duplicate of https://github.com/kubernetes/perf-tests/issues/1068

**Comment by mm4tt** [comment] 2020-05-12 10:19
Actually, it looks like it fails consistently since May 6th - https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.15-500

The culprit is this PR which has enabled NPL on May 6th - https://github.com/kubernetes/perf-tests/pull/1218
I analyzed build logs from May 5th and 6th, in May 5th run NPL was disabled in May 6th is was enabled.
Given this is not a regression, NPL never worked on kubemark 1.15, we should simply disable it, will send a PR

**Closed** 2020-05-12 12:36 UTC
Labels: kind/failing-test, sig/scalability
