### ISSUE TITLE
Have "kubectl drain" use eviction subresource

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#34277] opened 2016-10-06 22:27 UTC
Documented here
http://kubernetes.io/docs/admin/disruptions/

Also we need to add some kind of "force" flag to say drain the machine even if it would violate pod disruption budget. If you use this flag, "kubectl drain" will use regular pod deletion rather than eviction subresource.

Another issue to consider (unrelated to eviction subresource/disruption budget) is whether to wait until all the pods have been deleted before returning (so e.g. if you call `kubectl drain` in a loop, you won't start draining the next machine until the pods have been deleted. this isn't as good as waiting for the pods to reschedule but it's better than just returning immediately, since graceful deletion could delay the actual deletion for an arbitrary amount of time. I don't think kubectl drain currently waits for the pods to be deleted before returning, but I can't remember. Note also that kubectl drain has a --grace-period flag that lets you override the per-pod grace period settings presumably with a lower value.)

cc/ @mml

**Comment by maisem** [comment] 2016-10-06 22:43
cc @bdbauer

**Comment by maisem** [comment] 2016-10-27 18:15
@ymqytw are you working on this? Looks like #35483 is a dupe of this.

**Comment by ymqytw** [comment] 2016-11-10 03:43
@maisem I think we can close this issue. Since this has been implemented in #35483.

**Comment by maisem** [comment] 2016-11-10 17:33
Cool! Thanks!

**Closed by maisem** 2016-11-10 17:33 UTC
Labels: priority/P1, team/control-plane
