### ISSUE TITLE
hack/verify-golint: skip `golint` installation if it already exists 

### ISSUE THREAD

**Issue by mayankshah1607** [kubernetes/kubernetes#94562] opened 2020-09-05 15:50 UTC
**What would you like to be added**:
While working on https://github.com/kubernetes/kubernetes/issues/68026, `hack/verify-golint.sh` had to be called multiple times when linting had to be fixed for particular packages. This process was slow because each time the script was called, `golint` was being installed all over again despite being installed already. We can improve the script by adding a logic to see if golint already exists on the machine before attempting to install it.

**Why is this needed**:

To optimize the flow of the entire linting process. Having to unnecessarily reinstall `golint` each time may feel somewhat redundant.

**Comment by neolit123** [comment] 2020-09-06 18:20
the used command is:
```
GO111MODULE=on go install golang.org/x/lint/golint
```

https://github.com/kubernetes/kubernetes/blob/master/hack/verify-golint.sh#L36-L40

calling it multiple times should reuse the already installed tool.

by adding `exit 0` here:
https://github.com/kubernetes/kubernetes/blob/master/hack/verify-golint.sh#L41

i confirm that this work as expected and golint is not downloaded / rebuild on each run of the script.

/remove-kind feature
/kind bug
/priority awaiting-more-evidence
/sig testing

**Comment by BenTheElder** [comment] 2020-09-09 06:12
We're not actually installing it to the host either:
https://github.com/kubernetes/kubernetes/blob/1c6057b59ca7a1eee66086b86c75315cf26db081/hack/verify-golint.sh#L33-L34

This is because we're making sure that we use the pinned version in `hack/tools/go.mod`.

If the binary already exists in the kubernetes binary output path, it should not be rebuilt. If you blow away the output dir it might be, but that's working as intended.

Tentatively closing as a mis-understanding.
/close

**Closed** 2020-09-09 06:12 UTC
Labels: kind/bug, priority/awaiting-more-evidence, sig/testing
