### ISSUE TITLE
Flake in e2e "should function for pod communication between nodes"

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25207] opened 2016-05-05 17:35 UTC
```
[k8s.io] Networking
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
  [k8s.io] Granular Checks
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
    should function for pod communication between nodes [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:258

    Expected error:
        <*errors.errorString | 0xc8206c77e0>: {
            s: "pod 'different-node-wget' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-05-04 23:36:14 -0700 PDT} FinishedAt:{Time:2016-05-04 23:36:17 -0700 PDT} ContainerID:docker://62371bb3bbc90830847affe7c89a34398253ce1de961e4519c67bf174ea4b454}",
        }
        pod 'different-node-wget' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-05-04 23:36:14 -0700 PDT} FinishedAt:{Time:2016-05-04 23:36:17 -0700 PDT} ContainerID:docker://62371bb3bbc90830847affe7c89a34398253ce1de961e4519c67bf174ea4b454}
    not to have occurred
```

```
[BeforeEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:108
STEP: Creating a kubernetes client
May  4 23:36:07.262: INFO: >>> TestContext.KubeConfig: /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config

STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:50
STEP: Executing a successful http request from the external internet
[It] should function for pod communication between nodes
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:258
STEP: Picking multiple nodes
STEP: Creating a webserver pod
W0504 23:36:07.470742   14025 request.go:347] Field selector: v1 - pods - metadata.name - different-node-webserver: need to check if this is versioned correctly.
May  4 23:36:14.006: INFO: Target pod IP:port is 10.245.5.9:8080
STEP: Checking that the webserver is accessible from a pod on a different node
May  4 23:36:14.009: INFO: Waiting up to 5m0s for pod different-node-wget status to be success or failure
May  4 23:36:14.012: INFO: No Status.Info for container 'different-node-wget-container' in pod 'different-node-wget' yet
May  4 23:36:14.012: INFO: Waiting for pod different-node-wget in namespace 'e2e-tests-nettest-cp8mh' status to be 'success or failure'(found phase: "Pending", readiness: false) (2.926326ms elapsed)
May  4 23:36:16.022: INFO: Nil State.Terminated for container 'different-node-wget-container' in pod 'different-node-wget' in namespace 'e2e-tests-nettest-cp8mh' so far
May  4 23:36:16.022: INFO: Waiting for pod different-node-wget in namespace 'e2e-tests-nettest-cp8mh' status to be 'success or failure'(found phase: "Running", readiness: true) (2.012352965s elapsed)
May  4 23:36:18.025: INFO: Nil State.Terminated for container 'different-node-wget-container' in pod 'different-node-wget' in namespace 'e2e-tests-nettest-cp8mh' so far
May  4 23:36:18.025: INFO: Waiting for pod different-node-wget in namespace 'e2e-tests-nettest-cp8mh' status to be 'success or failure'(found phase: "Running", readiness: true) (4.015936146s elapsed)
May  4 23:36:20.062: INFO: Unexpected error occurred: pod 'different-node-wget' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-05-04 23:36:14 -0700 PDT} FinishedAt:{Time:2016-05-04 23:36:17 -0700 PDT} ContainerID:docker://62371bb3bbc90830847affe7c89a34398253ce1de961e4519c67bf174ea4b454}
[AfterEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:109
```

**Comment by bprashanth** [comment] 2016-05-05 18:16
https://github.com/kubernetes/kubernetes/pull/23567#issuecomment-217087670

Hmm, @kubernetes/goog-node pod ip changed. 
There are 2 pods: different-node-webserver on e2e-gce-builder-3-3-minion-hc9h (10.245.5.9:8080) and different-node-wget e2e-gce-builder-3-3-minion-rqg4 (with entrypoint: wget --timeout=10 -s 10.245.5.9:8080). 

The wget failed.
From https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23567/kubernetes-pull-build-test-e2e-gce/38490/artifacts/e2e-gce-builder-3-3-minion-hc9h/

```
I0505 06:36:08.445332    3374 kubelet.go:1278] container: 
e2e-tests-nettest-cp8mh/different-node-webserver/different-node-webserver-container podIP: "10.245.5.9" 
creating hosts mount: true
...
I0505 06:36:10.906116    3374 manager.go:1894] Killing Infra Container for "different-node-
webserver_e2e-tests-nettest-cp8mh(a5e95211-128b-11e6-8f22-42010af00002)", will start new one

I0505 06:36:11.673181    3374 kubelet.go:1278] container: 
e2e-tests-nettest-cp8mh/different-node-webserver/different-node-webserver-container podIP: "10.245.5.7" creating hosts mount: true
```

**Comment by yujuhong** [comment] 2016-05-06 00:39
Relevant logs:
```
I0505 06:35:09.431829    3374 kubelet.go:2585] SyncLoop (UPDATE, "api"): "pod-init-7f2b04b4-128b-11e6-8b7e-42010af0000d_e2e-tests-pods-eygva(7f2d44fe-128b-11e6-8f22-42010af00002)"
E0505 06:35:09.431996    3374 runtime.go:58] Recovered from panic: "index out of range" (runtime error: index out of range)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:426
/usr/local/go/src/runtime/panic.go:15
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/status/manager.go:259
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2662
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2727
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2586
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2525
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1076
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:657
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47
/usr/local/go/src/runtime/asm_amd64.s:1998
I0505 06:35:09.433890    3374 container_manager_linux.go:246] Configure resource-only container /docker-daemon with memory limit: 5504894976
I0505 06:35:09.433966    3374 manager.go:123] Starting to sync pod status with apiserver
I0505 06:35:09.433992    3374 kubelet.go:2512] Starting kubelet main sync loop.
```

kubelet panic'd and wasn't handled properly until much later, this caused `kubelet.Start()` to be run again -- launching a second copy of status manager, pleg, and more. 
Evidence:
 - `Starting to sync pod status with apiserver` was logged by `statusManager.Start()`
 - `Starting kubelet main sync loop` was logged by `Kubelet.syncLoop()`
 - The two instances of pleg eventually caused a data race `fatal error: concurrent map writes` much later in the log.


As for why pod IP changed, that's because the two pleg instances messed up the pod status, causing the worker to create an infra container again, hence a new pod IP. It's amazing how all other tests passed.

@kubernetes/goog-node

**Comment by yujuhong** [comment] 2016-05-06 00:41
By the way, @smarterclayton could you double check to see if this was caused by your PR?

**Comment by smarterclayton** [comment] 2016-05-06 15:46
I have only seen this once, but it is possible.  Will look into the scenario.

**Comment by bprashanth** [comment] 2016-05-11 17:57
@smarterclayton can you close this if it was because of something in your pr?

**Comment by yujuhong** [comment] 2016-05-11 18:09
Need to fix the PR instead: https://github.com/kubernetes/kubernetes/pull/23567/files#r62897134

**Closed by yujuhong** 2016-05-11 18:09 UTC
Labels: kind/flake, team/node
