### ISSUE TITLE
integration flake: runServiceTest "FAILED: unexpected endpoints: timed out waiting for the condition"

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20500] opened 2016-02-02 18:22 UTC
Failed test logs:
[kubernetes-test-go-release-1.1/3464](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-test-go-release-1.1/3464)
[kubernetes-test-go-release-1.1/3467](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-test-go-release-1.1/3467)

Excerpt:
```
...
02:31:51 I0202 10:31:51.061294   11528 kubelet.go:2747] Generating status for "container-vm-guestbook-pod-spec-127.0.0.1_default"
02:31:51 I0202 10:31:51.061328   11528 manager.go:357] Container inspect result: {ID:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Created:0001-01-01 00:00:00 +0000 UTC Path: Args:[] Config:0xc208abf860 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:11528 ExitCode:0 Error: StartedAt:2016-02-02 10:27:01.068093205 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image: Node:<nil> NetworkSettings:0xc208924e00 SysInitPath: ResolvConfPath: HostnamePath: HostsPath: LogPath: Name:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Driver: Volumes:map[] VolumesRW:map[] HostConfig:0xc2092f5b00 ExecIDs:[] RestartCount:0 AppArmorProfile:}
02:31:51 I0202 10:31:51.061391   11528 manager.go:357] Container inspect result: {ID:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Created:0001-01-01 00:00:00 +0000 UTC Path: Args:[] Config:0xc208abf860 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:11528 ExitCode:0 Error: StartedAt:2016-02-02 10:27:01.068093205 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image: Node:<nil> NetworkSettings:0xc208924e00 SysInitPath: ResolvConfPath: HostnamePath: HostsPath: LogPath: Name:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Driver: Volumes:map[] VolumesRW:map[] HostConfig:0xc2092f5b00 ExecIDs:[] RestartCount:0 AppArmorProfile:}
02:31:51 I0202 10:31:51.061450   11528 manager.go:357] Container inspect result: {ID:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Created:0001-01-01 00:00:00 +0000 UTC Path: Args:[] Config:0xc208abf860 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:11528 ExitCode:0 Error: StartedAt:2016-02-02 10:27:01.068093205 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image: Node:<nil> NetworkSettings:0xc208924e00 SysInitPath: ResolvConfPath: HostnamePath: HostsPath: LogPath: Name:/k8s_nginx.72c3fedf_nginx-controller-2jgc8_test_79b0bc33-c997-11e5-8de7-0242ac110003_c4d89e98 Driver: Volumes:map[] VolumesRW:map[] HostConfig:0xc2092f5b00 ExecIDs:[] RestartCount:0 AppArmorProfile:}
02:31:51 I0202 10:31:51.061590   11528 manager.go:156] Ignoring same status for pod "container-vm-guestbook-pod-spec-127.0.0.1_default", status: {Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason: Message:}] Message: Reason: HostIP:127.0.0.1 PodIP:1.2.3.4 StartTime:2016-02-02 10:26:46.567773694 +0000 UTC ContainerStatuses:[{Name:guestbook State:{Waiting:<nil> Running:0xc2093bcb40 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:testimage ImageID:docker:// ContainerID:docker:///k8s_guestbook.66e0ba8_container-vm-guestbook-pod-spec-127.0.0.1_default_03bc68c962f47e499c14a1fc11750d71_1924aa66} {Name:redis State:{Waiting:<nil> Running:0xc2093bcac0 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:testimage ImageID:docker:// ContainerID:docker:///k8s_redis.5107f6a8_container-vm-guestbook-pod-spec-127.0.0.1_default_03bc68c962f47e499c14a1fc11750d71_139c0f0e}]}
02:31:51 I0202 10:31:51.081105   11528 config.go:254] Setting pods for source file
02:31:51 I0202 10:31:51.662718   11528 nodecontroller.go:611] Nodes ReadyCondition updated. Updating timestamp: {Capacity:map[memory:{Amount:0 Format:DecimalSI} pods:{Amount:32.000 Format:DecimalSI} cpu:{Amount:0 Format:DecimalSI}] Phase: Conditions:[{Type:OutOfDisk Status:False LastHeartbeatTime:2016-02-02 10:31:44 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletHasSufficientDisk Message:kubelet has sufficient disk space available} {Type:Ready Status:True LastHeartbeatTime:2016-02-02 10:31:44 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletReady Message:kubelet is posting ready status}] Addresses:[{Type:LegacyHostIP Address:127.0.0.1} {Type:InternalIP Address:127.0.0.1}] DaemonEndpoints:{KubeletEndpoint:{Port:10251}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion: OsImage: ContainerRuntimeVersion:docker:// KubeletVersion:v1.1.8-beta.0.12+7e94fe062bc7c4 KubeProxyVersion:v1.1.8-beta.0.12+7e94fe062bc7c4}}
02:31:51  vs {Capacity:map[memory:{Amount:0 Format:DecimalSI} pods:{Amount:32.000 Format:DecimalSI} cpu:{Amount:0 Format:DecimalSI}] Phase: Conditions:[{Type:OutOfDisk Status:False LastHeartbeatTime:2016-02-02 10:31:50 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletHasSufficientDisk Message:kubelet has sufficient disk space available} {Type:Ready Status:True LastHeartbeatTime:2016-02-02 10:31:50 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletReady Message:kubelet is posting ready status}] Addresses:[{Type:LegacyHostIP Address:127.0.0.1} {Type:InternalIP Address:127.0.0.1}] DaemonEndpoints:{KubeletEndpoint:{Port:10251}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion: OsImage: ContainerRuntimeVersion:docker:// KubeletVersion:v1.1.8-beta.0.12+7e94fe062bc7c4 KubeProxyVersion:v1.1.8-beta.0.12+7e94fe062bc7c4}}.
02:31:51 I0202 10:31:51.662873   11528 nodecontroller.go:611] Nodes ReadyCondition updated. Updating timestamp: {Capacity:map[pods:{Amount:32.000 Format:DecimalSI} cpu:{Amount:0 Format:DecimalSI} memory:{Amount:0 Format:DecimalSI}] Phase: Conditions:[{Type:OutOfDisk Status:False LastHeartbeatTime:2016-02-02 10:31:43 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletHasSufficientDisk Message:kubelet has sufficient disk space available} {Type:Ready Status:True LastHeartbeatTime:2016-02-02 10:31:43 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletReady Message:kubelet is posting ready status}] Addresses:[{Type:LegacyHostIP Address:172.17.0.3} {Type:InternalIP Address:172.17.0.3}] DaemonEndpoints:{KubeletEndpoint:{Port:10250}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion: OsImage: ContainerRuntimeVersion:docker:// KubeletVersion:v1.1.8-beta.0.12+7e94fe062bc7c4 KubeProxyVersion:v1.1.8-beta.0.12+7e94fe062bc7c4}}
02:31:51  vs {Capacity:map[pods:{Amount:32.000 Format:DecimalSI} cpu:{Amount:0 Format:DecimalSI} memory:{Amount:0 Format:DecimalSI}] Phase: Conditions:[{Type:OutOfDisk Status:False LastHeartbeatTime:2016-02-02 10:31:49 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletHasSufficientDisk Message:kubelet has sufficient disk space available} {Type:Ready Status:True LastHeartbeatTime:2016-02-02 10:31:49 +0000 UTC LastTransitionTime:2016-02-02 10:26:41 +0000 UTC Reason:KubeletReady Message:kubelet is posting ready status}] Addresses:[{Type:LegacyHostIP Address:172.17.0.3} {Type:InternalIP Address:172.17.0.3}] DaemonEndpoints:{KubeletEndpoint:{Port:10250}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion: OsImage: ContainerRuntimeVersion:docker:// KubeletVersion:v1.1.8-beta.0.12+7e94fe062bc7c4 KubeProxyVersion:v1.1.8-beta.0.12+7e94fe062bc7c4}}.
02:31:52 I0202 10:31:52.081478   11528 config.go:254] Setting pods for source file
02:31:52 I0202 10:31:52.785289   11528 util.go:508] Default route transits interface "eth0"
02:31:52 I0202 10:31:52.785440   11528 util.go:353] Interface eth0 is up
02:31:52 I0202 10:31:52.785507   11528 util.go:398] Interface "eth0" has 2 addresses :[172.17.0.3/16 fe80::42:acff:fe11:3/64].
02:31:52 I0202 10:31:52.785534   11528 util.go:365] Checking addr  172.17.0.3/16.
02:31:52 I0202 10:31:52.785545   11528 util.go:374] IP found 172.17.0.3
02:31:52 I0202 10:31:52.785555   11528 util.go:404] valid IPv4 address for interface "eth0" found as 172.17.0.3.
02:31:52 I0202 10:31:52.785565   11528 util.go:514] Choosing IP 172.17.0.3 
02:31:53 I0202 10:31:53.081807   11528 config.go:254] Setting pods for source file
02:31:54 I0202 10:31:54.082115   11528 config.go:254] Setting pods for source file
02:31:54 F0202 10:31:54.673137   11528 integration.go:846] FAILED: unexpected endpoints: timed out waiting for the condition
02:31:54 !!! Error in ./hack/test-integration.sh:57
```

**Comment by lavalamp** [comment] 2016-02-03 17:53
@davidopp I would have expected Endpoints controller to be in control-plane?

**Comment by thockin** [comment] 2016-02-03 19:17
cluster team is overloaded on flakes right now - help?

@davidopp @alex-mohr anyone available?

**Comment by alex-mohr** [comment] 2016-02-03 20:20
@cjcullen is maybe up for cluster team flakes!  :)

**Comment by davidopp** [comment] 2016-02-03 20:27
I'm never sure whether services should be considered control-plane or cluster.

Feel free to move it back to control-plane; as discussed at this morning's meeting nobody will be able to look at it until next week, but I think that may be true of all the teams...

**Comment by thockin** [comment] 2016-02-03 21:53
We're buried in new & existing flakes - if @cjcullen has time, we'd certainly appreciate it.

**Comment by cjcullen** [comment] 2016-02-03 22:29
Looking now.

**Comment by cjcullen** [comment] 2016-02-04 02:10
I've run this O(10) times and haven't been able to repro.

The failures from the jenkins runs are due to the endpoints controller "successfully" returning 0 endpoints for a service that we expect to have 1. The timeout is already 500 seconds, and I was able to get the test to pass consistently locally with a timeout of 30 seconds, so I doubt that it's just slow.

The logs appear to indicate that the Pod is scheduled and "running", so the failure is in the endpoints_controller noticing it.

**Comment by thockin** [comment] 2016-02-04 04:37
@justinsb @bprashanth maybe I am just seeing ghosts, but this could be a
missing event too?

**Comment by justinsb** [comment] 2016-02-04 13:25
My hypothesis is that the ghost we're seeing in #20599 and #20547 boils down to:

1. reflector.go loop loses connectivity or for some other reason does a full resync
1. change is made to the items at around the same time (before the watch resumes)
1. we list all items and resume the watch
1. etcd watcher issue means that we don't see change

Do we have logs for kube-controller-manager (or the equivalent)?  I do see some messages from endpoints_controller.go but I can't interpret them back to a resync, so I can't say whether this is the same problem.

I was thinking about adding some log messages to reflector.go, so that we would have a log message  whenever we reconnect & relist from etcd.

**Comment by bprashanth** [comment] 2016-02-04 20:45
I'm more inclined to believe that endpoints are awol because of either a watch cache bug or something to do with the recent label selector refactor (not sure if this is in yet), because the endpoints controller is fairly simple and hasn't been modified in a while. If this is happening, it would explain some of the services flake too.

**Comment by ihmccreery** [comment] 2016-02-04 21:03
This may be related to flakes/failures #20652.

**Comment by cjcullen** [comment] 2016-02-04 22:33
I'm sitting w/ @ihmccreery, and the logs from this integration test failure are different enough from the things he's finding that I'm hesitant to say that they have the same root cause. My endoints_controller is running the whole time, and I don't see anything about closed watches.

One thing I do see in the failure logs (that isn't in the logs from my successful runs) is a FailedSync on the Pod that should be the endpoint for the failing service:
```
I0202 10:26:52.377808   11528 manager.go:1707] Need to restart pod infra container for "foo_default" because it is not found
I0202 10:26:52.377919   11528 manager.go:1726] Container {Name:c1 Image:foo Command:[] Args:[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:1234 Protocol:TCP HostIP:}] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0202 10:26:52.378029   11528 manager.go:1817] Got container changes for pod "foo_default": {StartInfraContainer:true InfraContainerId: ContainersToStart:map[0:{}] ContainersToKeep:map[]}
I0202 10:26:52.378123   11528 manager.go:1823] Killing Infra Container for "foo_default", will start new one
I0202 10:26:52.378191   11528 manager.go:1856] Creating pod infra container for "foo_default"
I0202 10:26:52.378494   11528 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"foo", UID:"78eaf9e2-c997-11e5-8de7-0242ac110003", APIVersion:"v1", ResourceVersion:"322", FieldPath:"implicitly required container POD"}): reason: 'Pulled' Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
I0202 10:26:52.378713   11528 kubelet.go:929] Will create hosts mount for container:"POD", podIP:: false
I0202 10:26:52.379012   11528 manager.go:752] Container default/foo/POD: setting entrypoint "[]" and command "[]"
I0202 10:26:52.379108   11528 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"foo", UID:"78eaf9e2-c997-11e5-8de7-0242ac110003", APIVersion:"v1", ResourceVersion:"322", FieldPath:"implicitly required container POD"}): reason: 'Created' Created with docker id /k8s_POD.5c9
I0202 10:26:52.379151   11528 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"foo", UID:"78eaf9e2-c997-11e5-8de7-0242ac110003", APIVersion:"v1", ResourceVersion:"322", FieldPath:"implicitly required container POD"}): reason: 'Started' Started with docker id /k8s_POD.5c9
E0202 10:26:52.379441   11528 oom_linux.go:89] Error getting process list for cgroup /docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36: open /sys/fs/cgroup/devices/docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36/cgroup.procs: no such file or directory
E0202 10:26:52.379658   11528 oom_linux.go:89] Error getting process list for cgroup /docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36: open /sys/fs/cgroup/devices/docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36/cgroup.procs: no such file or directory
E0202 10:26:52.379861   11528 oom_linux.go:89] Error getting process list for cgroup /docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36: open /sys/fs/cgroup/devices/docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36/cgroup.procs: no such file or directory
E0202 10:26:52.380056   11528 oom_linux.go:89] Error getting process list for cgroup /docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36: open /sys/fs/cgroup/devices/docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36/cgroup.procs: no such file or directory
E0202 10:26:52.380281   11528 oom_linux.go:89] Error getting process list for cgroup /docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36: open /sys/fs/cgroup/devices/docker/dad4a706e39db929755e5e746ce70c03ff2e9b73118ef3512e176e8235fefa36/cgroup.procs: no such file or directory
E0202 10:26:52.380389   11528 manager.go:1864] Failed to create pod infra container: exceeded maxTries, some processes might not have desired OOM score; Skipping pod "foo_default"
I0202 10:26:52.380485   11528 kubelet.go:2747] Generating status for "foo_default"
I0202 10:26:52.380602   11528 manager.go:357] Container inspect result: {ID:/k8s_POD.5c9d0133_foo_default_78eaf9e2-c997-11e5-8de7-0242ac110003_919c0921 Created:0001-01-01 00:00:00 +0000 UTC Path: Args:[] Config:0xc2092e04e0 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:11528 ExitCode:0 Error: StartedAt:2016-02-02 10:26:52.379083059 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image: Node:<nil> NetworkSettings:0xc208a75c00 SysInitPath: ResolvConfPath: HostnamePath: HostsPath: LogPath: Name:/k8s_POD.5c9d0133_foo_default_78eaf9e2-c997-11e5-8de7-0242ac110003_919c0921 Driver: Volumes:map[] VolumesRW:map[] HostConfig:0xc208a4cfc0 ExecIDs:[] RestartCount:0 AppArmorProfile:}
E0202 10:26:52.380841   11528 pod_workers.go:112] Error syncing pod 78eaf9e2-c997-11e5-8de7-0242ac110003, skipping: exceeded maxTries, some processes might not have desired OOM score
I0202 10:26:52.380996   11528 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"foo", UID:"78eaf9e2-c997-11e5-8de7-0242ac110003", APIVersion:"v1", ResourceVersion:"322", FieldPath:""}): reason: 'FailedSync' Error syncing pod, skipping: exceeded maxTries, some processes might not have desired OOM score
```

**Comment by bprashanth** [comment] 2016-02-04 22:37
Maybe the pod isn't ready to begin with (which would make it ineligible for service membership)?

**Comment by cjcullen** [comment] 2016-02-04 22:40
That's my working hypothesis. The pod is never becoming ready, in which case it is the "correct" behavior that it never shows up in the endpoints list.

**Comment by cjcullen** [comment] 2016-02-04 22:44
Though that may just be a red herring, because I see [similar logs](http://kubekins.dls.corp.google.com/job/kubernetes-test-go-release-1.1/3586/consoleFull) in successful runs

**Comment by cjcullen** [comment] 2016-02-05 01:55
I've given up on trying to reason from the logs. I have a loop running integration tests at 7e94fe062bc7c4a5fdd53d699c3f43aabba3bac1 (one of the failures). I've gotten through 26 runs of the loop without a failure. I'll report back tomorrow.

**Comment by cjcullen** [comment] 2016-02-08 18:09
I got up to 1000 attempts without a failure. I'm going to close this issue and assume it was related to the watch-cache problems.

**Closed by cjcullen** 2016-02-08 18:09 UTC
Labels: kind/flake, team/cluster
