### ISSUE TITLE
kube-controller-manager is listing nodes every ~0.3 sec.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16871] opened 2015-11-05 20:18 UTC
@wojtek-t @lavalamp @davidopp 

we should definitely be using watch for this...  not sure which bit is doing it.

**Comment by hongchaodeng** [comment] 2015-11-05 22:54
@brendandburns 
I want to help with this issue. Can you provide any pointers?

**Comment by bprashanth** [comment] 2015-11-06 03:04
I'd suspect you can start by checking apiserver logs (/var/log/kube-apiserver.log) where you should see requests tagged with something like `[[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/65691d5] ` at the frequency mentioned, and then proceed to adding log lines in the various controllers coupled into the kube-controller-manager binary. The controllers are started here: https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/cmd/kube-controller-manager/app/controllermanager.go#L239, and you can find the source here: https://github.com/kubernetes/kubernetes/tree/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/pkg/controller. If something is hammering the apiserver, it will probably show in in /var/log/kube-controller-manager.log.

Note that a list is a GET and not all the controllers actually care about nodes. My first suspicion would be the node controller, and that it only goes crazy in some situations (maybe on node death).

**Comment by hongchaodeng** [comment] 2015-11-06 05:52
Thanks @bprashanth !
Let me read through the code. I should be able to get some GCE nodes to run cluster and see logs in a few days...

**Comment by wojtek-t** [comment] 2015-11-06 07:15
This is strange - I've never seen that. Maybe it's something new that is doing it?

**Comment by lavalamp** [comment] 2015-11-06 22:23
https://github.com/kubernetes/kubernetes/blob/f4b2d8358f53b79b1ef1e73218c23e62043829f0/pkg/controller/node/nodecontroller.go#L350

does a node list every 5 seconds, and there's already a node cache it could use instead.

**Comment by davidopp** [comment] 2015-11-07 11:20
> does a node list every 5 seconds, and there's already a node cache it could use instead.

Yeah we have a
 TODO: Change node status monitor to watch based.
in NodeController but never did it. 

@hongchaodeng if you'd like to implement that, and can do it quickly, please go ahead.

That said, it shouldn't be running every 0.3 seconds (!), as @lavalamp said it should be every 5 seconds (https://github.com/kubernetes/kubernetes/blob/c3a072768bb8983c3f43e4ab50e379b8bef4760a/cmd/kube-controller-manager/app/controllermanager.go#L213)

So there's something else going on here.

**Comment by hongchaodeng** [comment] 2015-11-07 22:05
It's definitely a good thing to react on node status update based on watch/notify mechanism.

I was having difficulty on the monolithic logic of [nodecontroller#monitorNodeStatus](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L349-L466). I guessed it was doing some diff and should changed to react to watch updates. The logic, however, wasn't clear to me. Can anyone help explain it? If anyone else want to write the code, I would like to follow and review code as well.

**Comment by davidopp** [comment] 2015-11-27 06:31
@hongchaodeng NodeController runs an infinite loop that calls monitorNodeStatus() periodically
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L201

The first line of monitorNodeStatus() is doing a List to fetch all nodes
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L350
Each time monitorNodeStatus() is called, it stores this in knownNodeSet, so that on each iteration it can see which nodes were added and deleted since the previous iteration. 

Instead we want to trigger on every time a Node object is added to etcd, deleted from etcd, or updated in etcd. 

Note that there are various flavors of timeout in NodeController, that do things like update NodeReady status to "Unknown" if NodeController hasn't heard from a node in a certain amount of time, and evicts nodes after a different amount of time. So you'll still need some function that runs periodically, to check for timeouts.

So you'd end up with four functions: three watches (node added, node deleted, node updated) and one that runs periodically to check timeouts.

It would be good to first verify whether the problem Brendan reported is still present at HEAD. (Note that the problem he reported is not just caused by not using watch in NodeController -- NodeController should only be doing a LIST every 5 seconds. So there's also something else going on, assuming the problem is still happening.)

**Comment by davidopp** [comment] 2015-12-15 07:29
@hongchaodeng Can you look into this? If you have more questions, let me know.

**Comment by hongchaodeng** [comment] 2015-12-15 18:05
Last time I wasn't able to reproduce the problem. Now I have been involved in something else and could not spend more time on this.

**Comment by roberthbailey** [comment] 2017-04-21 22:54
@davidopp - has this been fixed in the last year?

**Comment by roberthbailey** [comment] 2017-04-21 22:54
@erictune

**Comment by davidopp** [comment] 2017-04-21 23:12
I don't know -- maybe someone from @kubernetes/sig-apps-bugs can check

**Comment by foxish** [comment] 2017-04-21 23:19
@crimsonfaith91 do you want to take a look at this and verify that this is resolved?

**Comment by crimsonfaith91** [comment] 2017-04-21 23:38
sure! let me have a look at it. :)

**Comment by kargakis** [comment] 2017-04-23 15:50
Shouldn't be a problem anymore - all of the controllers are using shared
informers and the node informer should relist every 12h-24h

On Sat, Apr 22, 2017 at 1:12 AM, David Oppenheimer <notifications@github.com

**Comment by crimsonfaith91** [comment] 2017-04-25 01:45
With @foxish help, we are able to verify that the node listing happens every 20 seconds.
Feel free to check the log message copied below:

I0425 01:28:14.634759       5 wrap.go:75] GET /api/v1/nodes: (2.052114ms) 200 [[kube-controller-manager/v1.6.2 (linux/amd64) kubernetes/477efc3/system:serviceaccount:kube-sys
tem:pod-garbage-collector] [::1]:34544]

I0425 01:28:34.638494       5 wrap.go:75] GET /api/v1/nodes: (1.978765ms) 200 [[kube-controller-manager/v1.6.2 (linux/amd64) kubernetes/477efc3/system:serviceaccount:kube-sys
tem:pod-garbage-collector] [::1]:34544]

**Comment by roberthbailey** [comment] 2017-04-25 04:01
Thanks for confirming; I'm going to mark this as fixed.

**Closed by roberthbailey** 2017-04-25 04:01 UTC
Labels: priority/important-soon, sig/apps, team/control-plane (deprecated - do not use)

**Comment by crimsonfaith91** [comment] 2017-04-25 18:02
You are very welcome. :)

**Comment by wojtek-t** [comment] 2017-04-26 12:04
Yes - as @kargakis wrote we are using shared informers.
The only controller that is really listing nodes is node-controller and this is for the purpose of detecting nodes that are down and avoid stale data. @gmarek 

but I agree this is an obsolete issue.

**Comment by gmarek** [comment] 2017-04-26 12:39
It's not NodeController - NC lists from Informer as we're not too concerned about being late by few(hundred) milliseconds.

This report shows that pod-gc is making those calls and this is (sadly) expected. It's responsible for removing Pods from non-existing Nodes, and we want to avoid errors in this logic as much as possible. As this is just a cleanup job it's safe to do it even less often, if the current settings turn out to be to heavy for the API server.
