### ISSUE TITLE
Grafana addon no longer loads through apiserver proxy

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#14624] opened 2015-09-27 16:31 UTC
With the latest change to the grafana/heapster/influxdb addon, the grafana UI no longer appears to work properly through the apiserver proxy.  The UI loads, but attempting to login just spits out a 404.

Appears to be due to PR #14210 .

I suspect something changed in grafana to make it hostile to the URL paths that kubectl local proxy through the API server uses.

@vishh Could you please take a look?

**Comment by bgrant0607-nocc** [comment] 2015-09-27 18:39
cc @kubernetes/goog-csi

**Comment by vishh** [comment] 2015-09-28 16:27
@chrisleck: Now that external services work in almost all deployments, I'm thinking of not attempting to support Grafana via the apiserver proxy. WDYT?

**Comment by chrisleck** [comment] 2015-09-28 17:16
I see two problems with that...

1. It would make ```kubectl cluster-info``` report false information for this kube-system addon.  We need to change cluster-info to report the correct endpoint if the apiserver proxy won't work.
2. Given Kubernetes doesn't yet support "internal only" LoadBalancers, it would expose this endpoint to the world which is not appropriate.

I think until (2) is resolved, this needs to work via the apiserver proxy.

**Comment by vishh** [comment] 2015-09-28 17:22
Fair enough!

**Comment by dchen1107** [comment] 2015-09-28 17:28
I bumped the priority to P0 for 1.1 release, we can either figure out why after upgrading, the authentication failed via API server proxy, and fix the issue; or downgrade Grafana if we believe the issue is caused by incompatible of upgrading.

**Comment by lavalamp** [comment] 2015-10-02 18:04
This is fixed now.

**Closed by lavalamp** 2015-10-02 18:04 UTC
Labels: priority/P0, team/cluster, team/CSI
