### ISSUE TITLE
Image pulling failing with bearer token errors

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27451] opened 2016-06-15 18:01 UTC
Seeing tests fail because image pulling failed, because of:
```
17:24:09 pulling gcr.io/google_containers/pause-amd64:3.0
Error response from daemon: name invalid: Requested repository does not match bearer token resource: google_containers/pause-amd64
17:24:09 pulling gcr.io/google_containers/porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab
Error response from daemon: name invalid: Requested repository does not match bearer token resource: google_containers/porter
17:24:09 pulling gcr.io/google_containers/portforwardtester:1.0
```
https://github.com/kubernetes/kubernetes/issues/26134#issuecomment-226266013
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/44825/consoleFull

@kubernetes/goog-node did we recently change image pulling?

**Comment by yujuhong** [comment] 2016-06-15 18:10
Not that I know of.

**Comment by yifan-gu** [comment] 2016-06-15 18:15
Seeing this error as well in the e2e tests result https://github.com/kubernetes/kubernetes/pull/27220

**Comment by bprashanth** [comment] 2016-06-15 18:36
in https://github.com/kubernetes/kubernetes/pull/27415#issuecomment-226275162 this failed on node e2e-gce-agent-pr-28-0-minion-group-7mx6 but passed on some other nodes like e2e-gce-agent-pr-28-0-minion-group-a8gv.
@k8s-oncall fyi

**Comment by ihmccreery** [comment] 2016-06-15 18:38
I'm seeing this error also pulling images when trying to build: https://github.com/kubernetes/kubernetes/pull/27453#issuecomment-226276204

**Comment by ihmccreery** [comment] 2016-06-15 18:38
cc @roberthbailey

**Comment by bprashanth** [comment] 2016-06-15 18:44
Yeah this is foreboding but I don't have the time to dig, maybe we shoudl reach out to registry people to check? @kubernetes/goog-testing

**Comment by ihmccreery** [comment] 2016-06-15 18:47
I can have a look.

**Comment by mml** [comment] 2016-06-15 20:33
@quinton-hoole mentioned this as well.

**Comment by mml** [comment] 2016-06-15 20:33
And I saw this just now.  https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/27390/node-pull-build-e2e-test/10692/build-log.txt

**Comment by wojtek-t** [comment] 2016-06-16 08:54
And I saw this error 4 times in gke-large suite yesterday:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/49/consoleText

[4 different tests failed exactly because of that reason - see #27527 ]

**Comment by yujuhong** [comment] 2016-06-16 15:17
Based on the internal email thread, the GCR team was able to reproduce this failure with `docker pull` and `gcloud docker pull`.
They have also started rolling back their release to see if this would be fixed.

**Comment by ihmccreery** [comment] 2016-06-16 16:52
The GCR team rolled back around 4 p.m. yesterday, and it doesn't look like we've seen any issues since then.

**Comment by yujuhong** [comment] 2016-06-16 17:00
Thanks @ihmccreery. I am closing this issue since we haven't seen any failure since the rollback. Will reopen if there are any new failure.

**Closed by yujuhong** 2016-06-16 17:00 UTC
Labels: area/images-registry, area/platform/gce, kind/flake, priority/P1, team/node

**Comment by ihmccreery** [comment] 2016-06-16 17:28
Yes, the root cause on the GCR side sounds like it's understood, so we're good.

**Comment by wojtek-t** [comment] 2016-06-16 18:05
Yeah - the failures I linked were also from before 4pm
