### ISSUE TITLE
Pod won't be considered for preemption even its nominated node is considered as UnschedulableAndUnresolvable by filters

### ISSUE THREAD

**Issue by soulxu** [kubernetes/kubernetes#92600] opened 2020-06-29 10:09 UTC
**What happened**:
When a Pod's nominated node is considered as UnschedulableAndUnresolvable in the filter stage, the scheduler doesn't consider that pod for preemption even there are pods can be preempted on another node.

**What you expected to happen**:
When the pod's nominated node is considered as 'UnschedulableAndUnresolvable ' (For example, the taint being added by those conditions, https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition), the scheduler should try to preemption on other nodes.

**How to reproduce it (as minimally and precisely as possible)**:
- Create low priority pod, which schedule to nodeA
- Create mid priority pod, which schedule to nodeB
- Create high priority pod, which preempt the low priority pod on nodeA, and set high priority pod's nominated node as nodeA
- The nodeA's kubelet is down, the node life cycle controller taint the nodeA with 'node.kubernetes.io/unschedulable' (or taint with disk pressure..etc) before low priority pod finishes the termination.
- The high priority pod is keeping as pending status. The scheduler doesn't try to preempt the mid-priority pod on nodeB

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18.0
- Cloud provider or hardware configuration:
baremetal
- OS (e.g: `cat /etc/os-release`):
ubuntu1804
- Kernel (e.g. `uname -a`):
5.3.0-46-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment] 2020-06-30 02:34
This seems to be a duplicate of #85677.

**Comment by soulxu** [comment] 2020-06-30 09:11
@Huang-Wei actually, I found this case after review #85677. I file this issue since I feel it should be another case. The #85677 want to cleanup the nomnated node for cluster autoscaler. This is case need to allow the pod to preempt on other nodes again even it has a nomanted node. But I may understand incorrectly, please mark it duplicated if I'm wrong. Thanks for help anyway.  :)

**Comment by Huang-Wei** [comment] 2020-06-30 23:25
If the nominatedNodeName can be cleared properly in any case, this issue will no longer exist. From this point of view, I'd say this issue is a sub-case of #85677.

**Comment by Huang-Wei** [comment] 2020-07-01 00:02
BTW: in your description, if "The nodeA is down", how it comes out "a Pod's nominated node is considered as UnschedulableAndUnresolvable in the filter stage"? nodeA should NOT have existed in the result of Filter(), right?

(if the nodeA is just being shutdown, we still treat it as a normal node)

**Comment by soulxu** [comment] 2020-07-01 01:27
If the NodeA is down, the node life cycle controller will add taint 'node.kubernetes.io/unschedulable' to the node, then the TaintToleration filter will return 'UnschedulableAndUnresolvable '. It also means that it isn't only about nodeA is down, there are other conditions in this 'https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition to return 'UnschedulableAndUnresolvable'.

Beyond the TaintToleration filter, other filters may return 'UnschedulableAndUnresolvable' also, as my understanding, that means that node won't be available for that pod anymore, then we should try other nodes for preemption.

**Comment by Huang-Wei** [comment] 2020-07-01 01:35
@soulxu then we should better describe it as "being applied with a Taint", which more general. When you say "node is down", it usually refers to the node is deleted physically.

**Comment by soulxu** [comment] 2020-07-01 01:36
@Huang-Wei I got it, thanks again! let me correct it

**Comment by Huang-Wei** [comment] 2020-07-01 01:37
Also it's different from #85677. Let's not mention "node is down" in the description to avoid confusion.

**Comment by soulxu** [comment] 2020-07-01 01:46
thanks, done :)

**Closed** 2020-07-03 12:03 UTC
Labels: kind/bug, sig/scheduling
