### ISSUE TITLE
Allocator bugs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#9450] opened 2015-06-09 00:35 UTC
https://github.com/GoogleCloudPlatform/kubernetes/blob/51750a4680cbb161b068b7748c8d00cacb8a893a/pkg/registry/service/allocator/etcd/etcd.go#L149

Since resource version increments with every change and e.last will always be the old resource version, this if will trigger every time this runs. This is probably a performance problem. It also masks the fact that `fn()` should probably be run no matter what, not conditionally.

@smarterclayton 

Ref #9444

**Comment by smarterclayton** [comment] 2015-06-09 00:39
Was that in my original change?  I don't remember using that.

**Comment by lavalamp** [comment] 2015-06-09 00:47
Oh sorry, looks like I should be tagging @justinsb :)

**Comment by smarterclayton** [comment] 2015-06-09 00:48
He did such a thorough refactor I'm going to blame him first.  The original loop may have done the same thing of course.

**Comment by lavalamp** [comment] 2015-06-09 00:52
I'm also pretty skeptical of the try-locally-and-then-try-etcd strategy for allocates. Why not just try etcd?

**Comment by smarterclayton** [comment] 2015-06-09 00:54
Might be easier.  Do it inside a guaranteed update loop.  More expensive when you get denied (because you ask for an IP we know is allocated).

**Comment by lavalamp** [comment] 2015-06-09 01:00
But it's more correct-- we only *think* it's denied, it may have since been freed up!

**Comment by smarterclayton** [comment] 2015-06-09 01:19
True, but the user doesn't know that unless he's coordinating with the deleter.  Ultimately  I agree with you since we have to round trip to etcd to persist the in memory check every time.

**Comment by lavalamp** [comment] 2015-06-09 17:57
I think people will expect to be able to delete a service and then make another service with the same IP.

(@brendandburns: I don't think this is a 1.0 issue unless we're doing HA)

**Comment by justinsb** [comment] 2015-06-15 22:08
Can I confirm that I understand where we are:

* We saw "cannot allocate resources of type serviceipallocation at this time" bugs in e2e test runs
* We reverted #9390 (which contained a version bump of go-etcd, including a replacement JSON library)
* That fixed the test runs
* But the logic is still suspicious, as described in the first comment

Is that right?  (And in particular, we're not seeing the failure any more after we downgraded etcd?)

**Comment by lavalamp** [comment] 2015-06-15 22:13
@justinsb Yup!

**Comment by smarterclayton** [comment] 2015-06-15 22:14
All #9390 could have done was make an existing test race more likely.  The tests or our start order is at fault, not the codec (at least not without more evidence to the contrary).

If we change our start order and have Start return an error that's probably a better solution.  It ensures true failures cause masters to fail to start (etcd misconfiguration, etc), and transients should not recur on the second run through.  Alternatively, we can just move the order and wait for start to return.

**Comment by justinsb** [comment] 2015-06-15 23:13
@smarterclayton - sounds like you believe the problem is that it genuinely has not been initialized yet.  I was working under the assumption that it was simply an etcd/etcd binding/allocator bug.  @lavalamp: Do we have any indication of that?  Were the failures early in the run?

Did spot two slightly suspicious pieces of code:

1: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L380

ResourceVersion will be "" if UpdateObject fails, and this will happen silently.  This should probably be a glog.Warning at least, although I would also consider letting extractObj fail.

Looking at UpdateObject though, I don't see an obvious way for it to fail.

---

2: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/service/allocator/etcd/etcd.go#L143-L148

I don't see why we pass ignoreNotFound=true to GuaranteedUpdate, if we are then immediately going to fail if it is not found?

**Comment by smarterclayton** [comment] 2015-06-15 23:25
> On Jun 15, 2015, at 7:14 PM, Justin Santa Barbara <notifications@github.com> wrote:
> 
> @smarterclayton - sounds like you believe the problem is that it genuinely has not been initialized yet. I was working under the assumption that it was simply an etcd/etcd binding/allocator bug.
> 
I don't have any proof that's the problem in the tests but it's possible to race against the core controller loop starting, and if the first repair fails the cluster is not usable for services until it is.  If that's the case I expect there to be a glog error reported from 

glog.Errorf("Unable to perform initial service nodePort check: %v", err)
> @lavalamp: Do we have any indication of that? Were the failures early in the run?
> 

> Did spot two slightly suspicious pieces of code:
> 
> 1: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L380
> 
> ResourceVersion will be "" if UpdateObject fails, and this will happen silently. This should probably be a glog.Warning at least, although I would also consider letting extractObj fail.
> 
> Looking at UpdateObject though, I don't see an obvious way for it to fail.
> 
> 2: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/service/allocator/etcd/etcd.go#L143-L148
> 
> I don't see why we pass ignoreNotFound=true to GuaranteedUpdate, if we are then immediately going to fail if it is not found?
> 
So that we can control the error, but not truly required.  Originally the loop was going to be create or update but that's not the case anymore.

**Comment by lavalamp** [comment] 2015-06-15 23:25
I filed this issue specifically about the bit of code that I liked to in the first post. @justinsb if you're talking about #9444 specifically, my actual best guess is that the dependency change legitimately had a bug that changed the behavior of the go-etcd package, specifically what it returned as a resourceVersion in the case that it wasn't set (updating an non-existing object). (0 vs "" or something like that.) I filed this issue while digging through the code.

**Comment by justinsb** [comment] 2015-06-15 23:41
Right, so on the original issue here, I had a look and I think I understand the code.  (I am not the original author: https://github.com/GoogleCloudPlatform/kubernetes/blob/e200d5a317da3e3f6f25ff8f475aed785964443e/pkg/registry/service/ipallocator/etcd/etcd.go#L114-L136, but I could very well have introduced a problem)

I believe the code is correct, if perhaps a little over-optimized!  We keep track of the state in memory and we speculatively execute the allocation against that.  If the etcd state does not match our local state, we deserialize the etcd state and re-execute the allocation.  Then we serialize the state and try to CAS to etcd, and we repeat until we succeed or something goes wrong.

The 'unchanged' logic is an optimization to avoid a deserialization of the etcd state (I believe).  In our current code, we never set last on our local state other than on a write operation (which is probably correct, because only on a write are we consistent), and we only do it after the write in CreateOrUpdate.  Given that, I don't think we'll hit the fast-path more than once per CreateOrUpdate call (i.e. <=1 time per run?).

Given that it is a fairly minor optimization and we're having trouble in this general area, I agree we should de-optimize the code and just always `do { restore etcd state / apply fn / save etcd state } until (casSucceeds)`

@thockin was suggesting this bug is still happening in the e2e tests.  If it has totally gone away with the etcd client downgrade, then I think we have a pretty solid lead on tracking this down via #9444 which we can follow post v1 (unless anyone has time to track it down!).  If we're still seeing problems in e2e, I think we deoptimize now per this issue, and add a lot of logging in the hope that we gather more information, to try to figure out whether it is an etcd client problem or an initialization problem.  @lavalamp?

**Comment by lavalamp** [comment] 2015-06-16 01:04
> The 'unchanged' logic is an optimization to avoid a deserialization of the etcd state...

You mean this, right? ```if existing.ResourceVersion != e.last {```

Yeah, it looks like someone was trying to avoid unnecessary deserializations, but it's wrong-- the condition will always be true (because every write will increment resourceVersion but not change e.last), and if it were ever not true, it would erroneously not run ```fn()```.

**Comment by smarterclayton** [comment] 2015-06-16 01:19
Actually no, the last version is set here: https://github.com/GoogleCloudPlatform/kubernetes/blob/e200d5a317da3e3f6f25ff8f475aed785964443e/pkg/registry/service/ipallocator/etcd/etcd.go#L190 after a successful save.  So the version we check against here is our version and whether we are the last committer.

**Comment by justinsb** [comment] 2015-06-16 01:30
@lavalamp yes, that's the attempt to skip the deserialization.  I agree it won't get hit often, because...

@smarterclayton yes I agree that CreateOrUpdate sets the last field, but I don't think that is the common case (in particular, tryUpdate does not set the last field after a write).  I tracked it back and it looks like CreateOrUpdate is only called from the repair loop, so for the update after that is the only time tryUpdate could be fresh.

**Comment by lavalamp** [comment] 2015-06-16 01:47
...and it's a good thing it essentially never gets hit, because if it were, fn() would not get called and no progress would be made.

**Comment by smarterclayton** [comment] 2015-06-16 02:49
> On Jun 15, 2015, at 9:30 PM, Justin Santa Barbara <notifications@github.com> wrote:
> 
> @lavalamp yes, that's the attempt to skip the deserialization. I agree it won't get hit often, because...
> 
> @smarterclayton yes I agree that CreateOrUpdate sets the last field, but I don't think that is the common case (in particular, tryUpdate does not set the last field after a write). I tracked it back and it looks like CreateOrUpdate is only called from the repair loop, so for the update after that is the only time tryUpdate could be fresh.
> 
Try update not setting that field is very wrong - we get a response from etcd, we should be setting it.

**Comment by smarterclayton** [comment] 2015-06-16 02:53
Also, refresh should be setting last.

**Comment by fgrzadkowski** [comment] 2015-06-16 10:16
@lavalamp 
> my actual best guess is that the dependency change legitimately had a bug that changed the behavior of the go-etcd package, specifically what it returned as a resourceVersion in the case that it wasn't set (updating an non-existing object). (0 vs "" or something like that.)
To be honest I don't see how this could be a bug in etcd client library. Ugorji is used only to unmarshal etcd response. One of the fields in the response contains marshalled k8s api object, but it is not unmarshaled in go-etcd client library. In other words ugorji doesn't decode/encode our objects, it only decodes etcd.Response:
https://github.com/coreos/go-etcd/blob/master/etcd/response.go#L46

**Comment by lavalamp** [comment] 2015-06-16 18:06
@fgrzadkowski I'm saying the difference is in the etcd Node object, not in our own object. (Epistemic status: unchecked hypothesis)

**Comment by smarterclayton** [comment] 2017-06-01 17:50
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 17:50 UTC
Labels: priority/backlog, sig/api-machinery, sig/scalability
