### ISSUE TITLE
e2e flake: namespaces are still active after e2e test is finished

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#32368] opened 2016-09-09 09:57 UTC
We're seeing it in pretty much all our serial and soak suites and is probably most common failure reason for our tests - including a number of P0 issues. Marking it as a P0 release blocker because of this, @thockin please remove if you think it shouldn't be one.

cc @kubernetes/test-infra-maintainers @derekwaynecarr @rmmh

**Comment by wojtek-t** [comment] 2016-09-09 11:23
@gmarek - links to failures please (I will try to look into it).

Also - I'm not sure this is v1.4 issue - I would suspect this is purely test issue.

**Comment by gmarek** [comment] 2016-09-09 11:42
Possibly caused by errors like #32371

**Comment by wojtek-t** [comment] 2016-09-09 11:46
The underlying problem here are "500" errors coming from GKE - we should debug and fix them and these problems will also disappear.

**Comment by wojtek-t** [comment] 2016-09-09 11:48
This is basically duplicate of https://github.com/kubernetes/kubernetes/issues/31728

**Comment by goltermann** [comment] 2016-09-14 18:10
Moving to 1.5, this is a non-release-blocker.

**Comment by calebamiles** [comment] 2016-11-03 04:34
@wojtek-t, has this been resolved given that https://github.com/kubernetes/kubernetes/issues/31728 is closed. @saad-ali we should probably close this issue if confirmed that the issue has been resolved by migration

**Closed** 2016-11-03 06:38 UTC
Labels: kind/flake, non-release-blocker, priority/P0, team/control-plane, team/gke
