### ISSUE TITLE
hyperkube kubectl ... doesn't accept flags.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#25714] opened 2016-05-17 04:25 UTC
For example:

```
hyperkube kubectl --namespace=kube-system get pods
```

fails.

**Comment by bgrant0607** [comment] 2016-05-17 23:43
@brendandburns There are multiple PRs in flight to fix this, I think

**Comment by bgrant0607** [comment] 2016-05-17 23:44
See #25512

**Comment by bgrant0607** [comment] 2016-05-17 23:44
Dupe of #24088

**Closed by bgrant0607** 2016-05-17 23:44 UTC
Labels: component/kubectl, priority/P1
