### ISSUE TITLE
Update to require Docker >= 1.7

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#13742] opened 2015-09-09 15:50 UTC
We should update the code base to require at least Docker 1.7. There are new features added to 1.7 that make CPU overcommit possible, and there is at least 1 bug with exec in 1.6.2 (kubectl exec -i <pod> bash, then type exit -> hangs) that is fixed in 1.7+.

@smarterclayton @derekwaynecarr @dchen1107 @bgrant0607 @thockin @vishh @brendandburns @kubernetes/rh-cluster-infra @kubernetes/rh-platform-management

**Comment by thockin** [comment] 2015-09-09 15:57
I don't think we have it written down, but we have a de facto "three
dockers" rule.  We might recommend 1.7.1+ stringly, but we have to work
with 1.6 (and 1.5 until we have 1.8 qual'ed)

**Comment by liggitt** [comment] 2015-09-09 16:00
If we don't drop support for 1.6.2, we should at least document known issues (like `docker exec` hanging in 1.6.2) in case people hit it

**Comment by thockin** [comment] 2015-09-09 16:13
We should have a markdown file detailing what docker versions are known
compatible and what issues exist.  Got 20 minutes to start that?

The fun comes with release branches - do we support 1.8 on v1.0.x?  1.9?
 1.10?

@dchen1107

**Comment by dchen1107** [comment] 2015-09-09 17:48
I talked to @erictune on publishing a validation metrics: Kubernetes release version with recommended docker version(s) (Engine version + API version) + known issues a while back. For example, 1.0 release, we only validate it with 1.6.2. For 1.1, we validate it against 1.7.1 and 1.8+. The metrics should include confirming tests. 

@thockin At this moment, I am not sure about a de facto "three dockers" rule is right answer for now. There are too many cloud providers, and different OSs, especially since 1.8, Docker provides dynamic binaries for each OS. @yujuhong has more detail on this. Also for 1.0 release, we documented that 1.6.2 is recommended docker version, and right after the announcement of release, I saw the issue filed against 1.0 release + docker 1.7, then later docker 1.8. 

We did document the leakage caused by docker exec for 1.0: https://github.com/kubernetes/kubernetes/issues/10760#issuecomment-120506546
but it might be not very intuitive. We could improve our document on this.

**Comment by yujuhong** [comment] 2015-09-09 18:09
We used to have one deb file (which contains a static docker binary) for all non-RedHat distributions. This won't work anymore because docker switched to releasing dynamic binaries for each OS distro/version. I filed an #13749 for this. We could argue that for bare-metal and vagrant cases, users need to ensure that a supported docker version is installed. However, iiuc, we will still need to rely on salt to install Docker for AWS images.

**Comment by dchen1107** [comment] 2015-09-09 21:08
@liggitt forgot to mention above that the memory leakage issue caused by docker exec is still not completely fixed in docker 1.8 even: (https://github.com/docker/docker/issues/12899)

**Comment by ncdc** [comment] 2015-09-09 21:09
@dchen1107 FYI the exec issue I was referring to originally is that `docker exec -i <container> bash' followed by `exit<CR>` hangs. It affects `kubectl exec` as well. This is fixed in 1.7+.

**Comment by thockin** [comment] 2015-09-09 21:55
It's not clear to me - are we saying that docker 1.8 is OK for kube v1.0
builds?  Are we committing to validating new dockers?  Are we going to roll
containerVM with new dockers?

**Comment by dchen1107** [comment] 2015-09-09 23:11
@ncdc Will make sure that issue is documented.

@thockin Today we are saying something like this for kube v1.0: 

1) We validate / qualify docker 1.6.2 against Kubernetes 1.0 release: publish testing results and document the known issues. This is our recommend version for running this release. You can see all endorsed cloud providers (gce / gke / aws) are running 1.6.2 by default for 1.0 release.
2) Docker API version below 1.15 (mapping to docker engine 1.3 ?) is disallowed which is achieved through node healthchecking. For next release, we should bump this to 1.18 (mapping to docker engine 1.6.2)
3) Since it is open source, we cannot force all users to use qualified release(s). So the users running any docker releases other than 1.6.2 and with API above v1.15 are pretty on your own. 

We are indeed committing to validating new docker releases. As a record, Kubernetes 1.1 release is having docker 1.7.1 by default at least. If we finish validation of docker 1.8, we are going to have docker 1.8.X by default. 

We are going to cut ContainerVM release with new docker. For each formal release, salt-based docker upgrade is disallowed. We are doing salt-based docker upgrading is against HEAD, not release branch. You can think about we are bundling release (kernel, kubelet and docker) together. This is true at least for GCE / GKE. For AWS, we bundled kubelet and docker, not kernel, I think.

I think a de facto "three Kubelet" is a right answer for our cluster-lifecycle story. But introducing "tree docker" is totally a different story: 
1) I didn't see any reason to run old docker version against the new kubernetes release (If docker new release has issues, we don't upgrade our default version and ask them to fix first) on our endorsed cloud providers.
2) We don't have testing team to support such support metrics. 
3) For GCE/GKE/ AWS, bundle release works fine so far. 
4) ...

Any objections? I am open to any suggestion here. cc/ @roberthbailey @zmerlynn

**Comment by smarterclayton** [comment] 2015-09-09 23:25
Red Hat support for OpenShift and Kube on RHEL is slightly ahead - we
certify on the RH version of Docker 1.7.1 right now and will probably bump
to 1.8.x prior to RHEL 7.2 (which will be roughly congruous to Kube 1.1 and
OpenShift 3.1).  We will probably drop Docker 1.6.2 support at this point
because of the exec bug, and move our customers up.

I think we definitely need to grow the matrix for builds - as part of
@pmories work that will cover those areas.

On Sep 9, 2015, at 7:11 PM, Dawn Chen <notifications@github.com> wrote:

@ncdc <https://github.com/ncdc> Will make sure that issue is documented.

@thockin <https://github.com/thockin> Today we are saying something like
this for kube v1.0:

1) We validate / qualify docker 1.6.2 against Kubernetes 1.0 release:
publish testing results and document the known issues. This is our
recommend version for running this release. You can see all endorsed cloud
providers (gce / gke / aws) are running 1.6.2 by default for 1.0 release.
2) Docker API version below 1.15 (mapping to docker engine 1.3 ?) is
disallowed which is achieved through node healthchecking. For next release,
we should bump this to 1.18 (mapping to docker engine 1.6.2)
3) Since it is open source, we cannot force all users to use qualified
release(s). So the users running any docker releases other than 1.6.2 and
with API above v1.15 are pretty on your own.

We are indeed committing to validating new docker releases. As a record,
Kubernetes 1.1 release is having docker 1.7.1 by default at least. If we
finish validation of docker 1.8, we are going to have docker 1.8.X by
default.

We are going to cut ContainerVM release with new docker. For each formal
release, salt-based docker upgrade is disallowed. We are doing salt-based
docker upgrading is against HEAD, not release branch. You can think about
we are bundling release (kernel, kubelet and docker) together. This is true
at least for GCE / GKE. For AWS, we bundled kubelet and docker, not kernel,
I think.

I think a de facto "three Kubelet" is a right answer for our
cluster-lifecycle story. But introducing "tree docker" is totally a
different story:
1) I didn't see any reason to run old docker version against the new
kubernetes release (If docker new release has issues, we don't upgrade our
default version and ask them to fix first) on our endorsed cloud providers.
2) We don't have testing team to support such support metrics.
3) For GCE/GKE/ AWS, bundle release works fine so far.
4) ...

Any objections? I am open to any suggestion here. cc/ @roberthbailey
<https://github.com/roberthbailey> @zmerlynn <https://github.com/zmerlynn>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13742#issuecomment-139069011>
.

**Comment by dchen1107** [comment] 2015-09-09 23:41
@smarterclayton sounds like for each OpenShift release, there are at least two docker versions. Am I interpreting your statement above correctly? 

Yes, we need to grow the metrics, but at which level? horizontal (cluster level)? or vertical (node level)?

**Comment by eparis** [comment] 2015-09-10 00:15
Depends who you talk to in Red Hat if we have 1 or 2 "supported" versions. We are generally asking our customers to stay on a rather aggressive docker update schedule.

**Comment by liggitt** [comment] 2015-09-10 01:58
Did the secrets mounting issue on Docker 1.7 ever get resolved?

**Comment by thockin** [comment] 2015-09-10 04:32
On Wed, Sep 9, 2015 at 4:11 PM, Dawn Chen <notifications@github.com> wrote:
>

> 3) Since it is open source, we cannot force all users to use qualified release(s). So the users running any docker releases other than 1.6.2 and with API above v1.15 are pretty on your own.

So we do not intend to qualify Docker 1.7 or 1.8 against kubernetes
v1.0 - I appreciate that it is simple, I am worried that it will not
be good for real production users.

> We are indeed committing to validating new docker releases. As a record, Kubernetes 1.1 release is having docker 1.7.1 by default at least. If we finish validation of docker 1.8, we are going to have docker 1.8.X by default.

My question was whether we qual new docker against older kube, and if
so, how old?

> I think a de facto "three Kubelet" is a right answer for our cluster-lifecycle story. But introducing "tree docker" is totally a different story:
> 1) I didn't see any reason to run old docker version against the new kubernetes release (If docker new release has issues, we don't upgrade our default version and ask them to fix first) on our endorsed cloud providers.

The reason or SOME back-compat is that I don't buy that it's good for
user to demand they upgrade docker on our schedule.

> Any objections? I am open to any suggestion here. cc/ @roberthbailey @zmerlynn

I agree with the RedHat mode that 2 supported versions makes sense,
what I don't have confidence in is the long-term support for old kube
releases.

kubernetes v1.0.x will still be around and in use 12 months from now.
Docker will be on 1.15 or something by then.  Are we telling users
that the only way to get a supported kubernetes version is to run a
year-old Docker?  Is that OK with users?

The alternative is that we qual each new docker against each
kubernetes version - our qual tests are not that good yet.

**Comment by smarterclayton** [comment] 2015-09-10 14:42
@mrunalp

On Wed, Sep 9, 2015 at 9:58 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Did the secrets mounting issue on Docker 1.7 ever get resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13742#issuecomment-139093564>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by mrunalp** [comment] 2015-09-10 16:35
@smarterclayton The PR is under review https://github.com/opencontainers/runc/pull/208

**Comment by bgrant0607** [comment] 2015-09-11 22:23
I didn't read the whole thread, but did talk to @dchen1107 and @vishh. My opinion:

* 1.0.x is stuck with 1.6.x. Upgrade Kubernetes if you need a newer Docker. Hopefully we'll soon have a release cadence that's similar to Docker's.
* We should have a general policy about how many Docker versions we test and provide strong customer support for. 2 seems reasonable to me.
* IMO, we _could_ occasionally depart from the general policy in order to move off problematic Docker versions or to rely on a newer Docker feature. I wouldn't ever depend on a x.y.0 docker release, though. If the general policy is 2 releases rather than 3, we may never need to do this.
* Because people will try to get Kubernetes working on whatever random machines they have, I feel strongly that we shouldn't hard-fail on older Docker versions than the officially supported ones. We should document which ones we've tested and which new features we're depending on, in our release notes, and we should print a warning into the Kubelet logs if they're using an untested Docker version.

**Comment by pikeas** [comment] 2015-12-08 05:11
+1, really surprised that K8S is still on docker 1.7.1 (at least for AWS).

Are there any blockers or known issues with 1.8.x or 1.9.x? Is there an issue or doc to track validation status and test results for new docker versions?

**Comment by roberthbailey** [comment] 2015-12-08 05:43
For 1.1 on GCE we are using docker 1.8.3.

**Comment by smarterclayton** [comment] 2015-12-08 21:44
We certify on RHEL on 1.8.3 for Atomic and OpenShift.  I believe there was
an issue with 1.9.0, we are doing testing with 1.9.1 but there have been
stability issues identified where we were waiting for another rev.

**Comment by pmorie** [comment] 2015-12-09 18:08
Related: #12090

**Comment by dchen1107** [comment] 2015-12-10 23:46
For 1.1 release, we recommended docker 1.8.3 (https://github.com/kubernetes/kubernetes/issues/15563), but not enforced, which means you still can run some other docker releases. Also for 1.1 release, we dropped the support for any docker version below 1.6.2 (https://github.com/kubernetes/kubernetes/pull/15994), and this is enforced, which means if you are running docker pre 1.6.2, Kubelet will report NodeNotReady.

**Comment by dchen1107** [comment] 2015-12-10 23:49
We are currently validating docker 1.9.X. docker 1.9.1 has significant performance issue.

**Comment by luxas** [comment] 2016-02-15 05:58
Which docker versions will `v1.2` support? Ref: #20281
Is it possible to drop support for `v1.7.1`?

**Comment by thockin** [comment] 2016-02-15 06:06
I think we're saying 1.8 and 1.9, MAYBE 1.10

**Comment by luxas** [comment] 2016-02-17 13:13
OK, let's add a release note about that then and maybe a doc...
(I take it as `v1.7.1` is probably possible to use, but not officially supported)

**Comment by yujuhong** [comment] 2016-06-08 00:56
This issue is obsolete. Closing.

**Closed by yujuhong** 2016-06-08 00:56 UTC
Labels: priority/P2, team/node
