### ISSUE TITLE
Kubelet should retry refreshing its ECR token when throttled by AWS API 

### ISSUE THREAD

**Issue by somejfn** [kubernetes/kubernetes#41154] opened 2017-02-08 20:11 UTC
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  AWS
- **OS** (e.g. from /etc/os-release):  Container Linux by CoreOS stable (1235.5.0)
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2
- **Install tools**: Kargo 
- **Others**:

**What happened**:

We can pull images from AWS ECR most of the time but because of AWS API throttling, the Kubelet can't refresh the token at some point and POD creation later fails during docker pull phase:

Failed to pull image "123123123123.dkr.ecr.us-east-1.amazonaws.com/repo/imagename:latest": unauthorized: authentication required
Error syncing pod, skipping: failed to "StartContainer" for "imagename" with ErrImagePull: "unauthorized: authentication required

And in Kubelet logs minutes before the Deployment was created:

"Feb 08 19:13:30 ip-10-189-36-185.ec2.local kubelet[11674]: E0208 19:13:30.313769   11708 aws_credentials.go:201] while requesting ECR authorization token ThrottlingException: Rate exceeded

**What you expected to happen**:

Kubelet should aggressively retry to refresh ECR tokens on that type of event

**How to reproduce it** (as minimally and precisely as possible):

You'd need to force AWS to throttle the API call... I can hardly give a good recipe for that. 

**Anything else we need to know**:

**Comment by bigkraig** [comment] 2017-02-14 16:57
@deads2k @erictune @liggitt I can take a shot at adding an exponential backoff retry on this. Would it be something that should be done at the credentialprovider level or is an ECR specific implementation good?

This is biting us pretty often. Thanks!

**Comment by deads2k** [comment] 2017-02-14 17:17
I could see having a general kind of credential provider (peer to lazy maybe?) that knows to retry.  I don't remember if there's an obviously signal though.  Might require replumbing.

**Comment by bigkraig** [comment] 2017-02-25 02:31
looks like this is a dupe of #37962

**Closed** 2018-02-27 12:17 UTC
Labels: lifecycle/rotten, sig/aws, sig/node
