### ISSUE TITLE
Flake: Kubectl run rc [It] should create an rc from an image [Conformance] [pods not ready]

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22603] opened 2016-03-06 00:32 UTC
As seen here: https://github.com/kubernetes/kubernetes/pull/22064#issuecomment-192758541

Build log: http://pr-test.k8s.io/22064/kubernetes-pull-build-test-e2e-gce/31885

Excerpt from logs:
```
[It] should create an rc from an image [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:908
STEP: running the image gcr.io/google_containers/nginx:1.7.9
Mar  5 15:08:28.208: INFO: Running '/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl --server=https://146.148.96.85 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config run e2e-test-nginx-rc --image=gcr.io/google_containers/nginx:1.7.9 --generator=run/v1 --namespace=e2e-tests-kubectl-nnycp'
Mar  5 15:08:28.584: INFO: stderr: ""
Mar  5 15:08:28.584: INFO: stdout: "replicationcontroller \"e2e-test-nginx-rc\" created"
STEP: verifying the rc e2e-test-nginx-rc was created
STEP: verifying the pod controlled by rc e2e-test-nginx-rc was created
STEP: confirm that you can get logs from an rc
Mar  5 15:08:28.676: INFO: Running '/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl --server=https://146.148.96.85 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config logs rc/e2e-test-nginx-rc --namespace=e2e-tests-kubectl-nnycp'
Mar  5 15:08:29.048: FAIL: Failed getting logs by rc e2e-test-nginx-rc: Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.96.85 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config logs rc/e2e-test-nginx-rc --namespace=e2e-tests-kubectl-nnycp] []  <nil>  Error from server: the server could not find the requested resource ( pods/log e2e-test-nginx-rc-35or1)
 [] <nil> 0xc208580b60 exit status 1 <nil> true [0xc2083c6888 0xc2083c68b8 0xc2083c68f8] [0xc2083c6888 0xc2083c68b8 0xc2083c68f8] [0xc2083c68b0 0xc2083c68f0] [0x8a4940 0x8a4940] 0xc208a57680}:
Command stdout:

stderr:
Error from server: the server could not find the requested resource ( pods/log e2e-test-nginx-rc-35or1)
...

â€¢ Failure [19.214 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1082
  Kubectl run rc
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:910
    should create an rc from an image [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:908

    Mar  5 15:08:29.048: Failed getting logs by rc e2e-test-nginx-rc: Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.96.85 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config logs rc/e2e-test-nginx-rc --namespace=e2e-tests-kubectl-nnycp] []  <nil>  Error from server: the server could not find the requested resource ( pods/log e2e-test-nginx-rc-35or1)
     [] <nil> 0xc208580b60 exit status 1 <nil> true [0xc2083c6888 0xc2083c68b8 0xc2083c68f8] [0xc2083c6888 0xc2083c68b8 0xc2083c68f8] [0xc2083c68b0 0xc2083c68f0] [0x8a4940 0x8a4940] 0xc208a57680}:
    Command stdout:
    
    stderr:
    Error from server: the server could not find the requested resource ( pods/log e2e-test-nginx-rc-35or1)
    
    error:
    exit status 1
    ```

**Comment by fejta** [comment] 2016-03-06 07:13
So we call `kubectl run`  at 15:08:28.200 which completes at 28.600
Then we call `kubectl logs` at 15:08:28.700 which fails at 29.100

If we look at the `146.148.96.85:22-kube-apiserver.log` we see the following:

```
I0305 23:08:29.046236       6 handlers.go:152] GET /api/v1/namespaces/e2e-tests-kubectl-nnycp/pods/e2e-test-nginx-rc-35or1/log: (15.747688ms) 404 [[kubectl/v1.3.0 (linux/amd64) kubernetes/70b71ab] 104.197.251.240:39639]
I0305 23:08:29.276230       6 handlers.go:152] GET /api/v1/namespaces/e2e-tests-kubectl-nnycp/pods/e2e-test-nginx-rc-35or1: (4.361239ms) 200 [[kubelet/v1.3.0 (linux/amd64) kubernetes/70b71ab] 10.240.0.7:40817]
I0305 23:08:29.297219       6 handlers.go:152] PUT /api/v1/namespaces/e2e-tests-kubectl-nnycp/pods/e2e-test-nginx-rc-35or1/status: (19.267567ms) 200 [[kubelet/v1.3.0 (linux/amd64) kubernetes/70b71ab] 10.240.0.7:40817]
```

I suspect this means that the logs were read before the pod was fully running?

**Comment by bgrant0607** [comment] 2016-03-06 22:52
Maybe related to #21335. Indeed the flakes started some time after that was merged yesterday.

cc @deads2k @kargakis

**Comment by bprashanth** [comment] 2016-03-06 22:57
> I suspect this means that the logs were read before the pod was fully running?

It might just need a readiness probe. Looks like it's running nginx, so just this should be enough: https://github.com/kubernetes/kubernetes/pull/20865/files (in addition to polling till ready)

**Comment by deads2k** [comment] 2016-03-07 14:33
Opened https://github.com/kubernetes/kubernetes/pull/22641 to wait until the pods are ready.

**Comment by bgrant0607** [comment] 2016-03-11 08:14
```
â€¢ Failure [328.825 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1089
  Kubectl run rc
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:917
    should create an rc from an image [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:915

    Mar 10 23:54:32.348: Pods for rc e2e-test-nginx-rc were not ready

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:908
```
kubernetes-jenkins/pr-logs/pull/22844/kubernetes-pull-build-test-e2e-gce/32357

**Comment by deads2k** [comment] 2016-03-11 13:02
My kubelet skills are lacking, but this seems odd:
```
Mar 10 23:54:30.347: INFO: Waiting for pod e2e-test-nginx-rc-iog5c in namespace 'e2e-tests-kubectl-d0ynr' status to be 'running and ready'(found phase: "Pending", readiness: false) (4m58.349620485s elapsed)
......
Mar 10 23:54:35.013: INFO: e2e-test-nginx-rc-iog5c started at <nil> (0 container statuses recorded)
Mar 10 23:54:35.013: INFO: elasticsearch-logging-v1-jvkdy started at <nil> (0 container statuses recorded)
Mar 10 23:54:35.098: INFO: ERROR kubelet_docker_errors{operation_type="info"} => 1 @[0]
Mar 10 23:54:35.098: INFO: ERROR kubelet_docker_errors{operation_type="inspect_image"} => 20 @[0]
Mar 10 23:54:35.098: INFO: ERROR kubelet_docker_errors{operation_type="list_containers"} => 32 @[0]
Mar 10 23:54:35.098: INFO: ERROR kubelet_docker_errors{operation_type="list_images"} => 6 @[0]
Mar 10 23:54:35.099: INFO: ERROR kubelet_docker_errors{operation_type="stop_container"} => 8 @[0]
Mar 10 23:54:35.099: INFO: ERROR kubelet_docker_errors{operation_type="version"} => 12 @[0]
```

Are those docker errors normal?

**Comment by deads2k** [comment] 2016-03-11 13:04
Also, do we gather etcd dumps for failed tests?  I didn't see them `artifacts`, but I wasn't sure if they were somewhere else.  Being able to load an etcd with the dump, point an API server (no controllers) at it, and debug using the normal client tools is pretty useful downstream.

**Comment by bgrant0607** [comment] 2016-03-11 15:07
@deads2k No, good idea. Please file an issue.

**Comment by bgrant0607** [comment] 2016-03-11 15:08
@deads2k Yes, those docker errors look normal to me.

**Comment by janetkuo** [comment] 2016-03-11 20:12
This failure mode (pods not running) is similar to #22300. The rc successfully created pods, but they fail to start running in 5 minutes. 
cc @dchen1107 @yujuhong

**Comment by dchen1107** [comment] 2016-03-14 19:10
Checked logs of the latest failure reported by @bgrant0607 at https://github.com/kubernetes/kubernetes/issues/22603#issuecomment-195249155

The problem is related to image pulling like what I mentioned in our 1.2 issue burndown meeting:

From events related to e2e-test-nginx-rc-iog5c, one can find that there is only pulling event for such image without pulled.
```
Mar 10 23:54:34.586: INFO: At 2016-03-10 23:49:30 -0800 PST - event for e2e-test-nginx-rc: {replication-controller } SuccessfulCreate: Created pod: e2e-test-nginx-rc-iog5c
Mar 10 23:54:34.586: INFO: At 2016-03-10 23:49:31 -0800 PST - event for e2e-test-nginx-rc-iog5c: {default-scheduler } Scheduled: Successfully assigned e2e-test-nginx-rc-iog5c to e2e-gce-builder-3-1-minion-k1k9
Mar 10 23:54:34.586: INFO: At 2016-03-10 23:49:37 -0800 PST - event for e2e-test-nginx-rc-iog5c: {kubelet e2e-gce-builder-3-1-minion-k1k9} Pulling: pulling image "gcr.io/google_containers/nginx:1.7.9"
Mar 10 23:54:34.586: INFO: At 2016-03-10 23:54:33 -0800 PST - event for e2e-test-nginx-rc: {replication-controller } SuccessfulDelete: Deleted pod: e2e-test-nginx-rc-iog5c
```

Docker daemon is not hang at all, but docker pull is hang. This is a dup of https://github.com/kubernetes/kubernetes/issues/22819. This is also a known issue for docker concurrency pulling. In real production since 1.1 release, we made the serializing pull as the default due to the same reason, but test is still using paralleling pulling due to timeout issue. cc/ @vishh

**Comment by dchen1107** [comment] 2016-03-14 19:10
https://github.com/kubernetes/kubernetes/issues/21000

**Comment by dchen1107** [comment] 2016-03-14 19:11
Besides documenting this as known docker issue if paralleling pull is enabled, I don't think we can do much for 1.2 release here. cc/ @bgrant0607

**Comment by yujuhong** [comment] 2016-03-14 19:27
Just wanted to add that, there are a lot of failures where image pulling was slow (#21029), but did not hang. In those cases, you'd see a "Pulled" event in kubelet.log. The event never reached the apiserver because the pod was already deleted (due to test timeout), and the event was rejected at the time. E.g.,
```
E0211 00:06:28.339664    3902 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"e2e-test-nginx-rc-xjx8c.1431ba7a21c80c9e", GenerateName:"", Namespace:"e2e-tests-kubectl-k1od4", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-kubectl-k1od4", Name:"e2e-test-nginx-rc-xjx8c", UID:"3f1f2ea3-d053-11e5-85b9-42010af00002", APIVersion:"v1", ResourceVersion:"1854", FieldPath:"spec.containers{e2e-test-nginx-rc}"}, Reason:"Pulled", Message:"Successfully pulled image \"nginx\"", Source:api.EventSource{Component:"kubelet", Host:"e2e-gce-builder-2-3-minion-nksc"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63590745988, nsec:332915870, loc:(*time.Location)(0x2daf2a0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63590745988, nsec:332915870, loc:(*time.Location)(0x2daf2a0)}}, Count:1, Type:"Normal"}': 'namespaces "e2e-tests-kubectl-k1od4" not found' (will not retry!)
I0211 00:06:28.796169    3902 server.go:570] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-emptydir-2d6jr", Name:"pod-44ce3723-d053-11e5-8c2f-42010af00003", UID:"44cdbcb5-d053-11e5-85b9-42010af00002", APIVersion:"v1", ResourceVersion:"2677", FieldPath:"spec.containers{test-container}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "gcr.io/google_containers/mounttest-user:0.3"
```

I have checked quite a few failures and they all had this symptom. All image pulling on a single node was stalled for a period of time, and eventually went back to normal. I am not sure whether this is a gcr.io problem (in which case we should file a internal ticket), or other networking issues. On the other hand, there are still "unable to ping registry" (#20550) errors popping up from time to time. Given all the problems we've had, I'm less convinced that this is caused by docker concurrent pulling issues...

**Comment by vishh** [comment] 2016-03-14 22:17
Would looking at the image pull duration from kubelet metrics help here?

**Comment by yujuhong** [comment] 2016-03-15 00:16
> Would looking at the image pull duration from kubelet metrics help here?

Not necessarily. We already know sometimes image pull requests are slow on a node, but we don't know why. Adding the metrics won't help us figure out why...

**Comment by vishh** [comment] 2016-03-15 00:20
> Not necessarily. We already know sometimes image pull requests are slow on a node, but we don't know why. Adding the metrics won't help us figure out why...

It might help us deterministically identify registry issues.

**Comment by bgrant0607** [comment] 2016-03-15 01:35
Removed from 1.2 until we get more data about frequency and/or cause.

**Comment by dchen1107** [comment] 2016-03-28 23:23
We need to figure out a way to test docker pull reliably same / similar as what we are using at production, but not much latency introduced to test.

**Comment by justinsb** [comment] 2016-04-01 14:26
Could we have an alternate mechanism for getting images than docker pull?  Maybe a fetch from http (GCS/S3) and then a docker import?

**Comment by bprashanth** [comment] 2016-04-01 15:28
Yeah we can certainly just write our own docker puller that replaces the pull method in the current docker interface. I've entertained the idea, it would also allow us to timeout pulls. I think we're moving to the new docker api (the official one, we're currently using https://github.com/fsouza/go-dockerclient) which may help, it allows timeouts anyway.

The node team might have thoughts about the reliability of docker load/import. 
The fetch + docker load is what we already do for master components.

**Comment by yujuhong** [comment] 2016-04-01 18:35
> Yeah we can certainly just write our own docker puller that replaces the pull method in the current docker interface. I've entertained the idea, it would also allow us to timeout pulls. I think we're moving to the new docker api (the official one, we're currently using https://github.com/fsouza/go-dockerclient) which may help, it allows timeouts anyway.

@Random-Liu has pending PRs to switch to using the new docker client and we'll add timeout for each request after that. That said, setting timeout for pulling images is tricky because we'll only be able to set a long timeout unless we know the size beforehand. There is also no proof that retrying a pull request will help, which is what this issue is about. In fact, I've seen all the pull requests on one node to be slow for a 5 minute period, and everything was back to normal after that (while other nodes were not affected). In these cases, adding timeouts may help surface the error, but does not help avoid it.

> The node team might have thoughts about the reliability of docker load/import. 
> The fetch + docker load is what we already do for master components.

I know @dchen1107 has some opinions of using `docker load`. Another thing is that we'll have to do it for rkt as well.

**Comment by Random-Liu** [comment] 2016-04-01 18:53
Another option is that new docker engine-api keeps reporting image pulling progress (Like xx%). We could pass this to apiserver to help surface the error.

**Comment by bprashanth** [comment] 2016-04-01 18:59
> In fact, I've seen all the pull requests on one node to be slow for a 5 minute period, and everything was back to normal after that (while other nodes were not affected). In these cases, adding timeouts may help surface the error, but does not help avoid it

The assumption is that it's load on some centralized server (eg: GCE meatdata) and reducing number of concurrent requests/connections might help. Of course this is just a best practices approach, no telling if it will in one particular scenario. 

If we can detect it and timeout we should also try and avoid backoff. I don't want my pod to get exponentially jailed because it happen to get scheduled in a 5m gcr.io outage window.

**Comment by yujuhong** [comment] 2016-05-13 19:19
> If we can detect it and timeout we should also try and avoid backoff. I don't want my pod to get exponentially jailed because it happen to get scheduled in a 5m gcr.io outage window.

There are pros and cons. If gcr.io is slow due to high load, backing off is probably better.

Let's move the discussion to #25277 to consolidate all the issues.

**Closed by yujuhong** 2016-05-13 19:19 UTC
Labels: component/kubectl, kind/flake, priority/P1, team/ux
