### ISSUE TITLE
Broken link in k8s.io documentation

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#15337] opened 2015-10-08 23:05 UTC
The link to the "Pod API object" at the bottom of the [Pods page in the user guide](http://kubernetes.io/v1.0/docs/user-guide/pods.html) points to a page that can't be loaded:
https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/v1.0.1/docs/api-reference/definitions.html#_v1_pod

**Comment by RichieEscarez** [comment] 2015-10-09 00:26
Duplicate of #11772

**Comment by timstclair** [comment] 2015-10-20 21:18
Duplicate of https://github.com/kubernetes/kubernetes/issues/15916

**Closed by timstclair** 2015-10-20 21:18 UTC
Labels: kind/documentation, priority/P1, team/ux
