### ISSUE TITLE
Leaking reflector metrics in 1.8

### ISSUE THREAD

**Issue by brancz** [kubernetes/kubernetes#53485] opened 2017-10-05 08:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Ran Kubernetes 1.8 apiserver for 3 days and the memory usage kept going up.

![screenshot from 2017-10-05 10-12-19](https://user-images.githubusercontent.com/4546722/31216977-bb57bd00-a9b5-11e7-989f-0b4ee9b53133.png)

Looking at a heap profile showed, that the majority of this memory is coming from the [`cache.NewNamedReflector`](https://github.com/kubernetes/client-go/blob/82aa063804cf055e16e8911250f888bc216e8b61/tools/cache/reflector.go#L107) function, or more specifically, the [metrics being instantiated in it](https://github.com/kubernetes/client-go/blob/82aa063804cf055e16e8911250f888bc216e8b61/tools/cache/reflector.go#L112).

[pprof.hyperkube.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz](https://github.com/kubernetes/kubernetes/files/1358504/pprof.hyperkube.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz)

I validated that this is indeed coming from metrics by checking the amount of metrics exposed by the `/metrics` endpoint.

```
$ curl localhost:8001/metrics | wc -l
49966
```

In an equivalent workload cluster running Kubernetes `v1.7.5`, this number is round `3000`.

So I took a look and noticed, that the majority of these metrics are actually coming from reflectors of CRD resources. Around 15000 of those metrics are each related to one of the three CRDs installed in the cluster. The total number of metrics increases by ~50 every few minutes.

I feel this might be happening whenever the cache in the Prometheus Operator (the controller for the CRDs existing in this cluster) is hitting its resync interval for a particular resource, so this might be happening on either opening a watch and or listing the resources, but this is just a wild guess.

The metrics in the `NewNamedReflector` function should be injected instead of re-created and registered on the global metrics registry, but the fact that the apiserver keeps creating new reflectors for these resources is likely also a problem.

Another problem I've been noticing, starting approximately at the same time as this, is that the apiserver API latencies have increased significantly.

**What you expected to happen**:

Unique metrics for each type of reflector, not causing a memory leak.

**How to reproduce it (as minimally and precisely as possible)**:

The cluster was setup using bootkube, but recently upgraded to 1.8 (3 days ago), and the Prometheus Operator running on it with the [`kube-prometheus`](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) stack deployed.

**Anything else we need to know?**:

**Environment**: bootkube / bare metal
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): CoreOS Container Linux
- Kernel (e.g. `uname -a`): Linux sd-99796 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64
- Install tools: bootkube
- Others:

@sig-instrumentation-bugs @kubernetes/sig-api-machinery-bugs 

/cc @sttts @nikhita I know you recently worked on the CRD code, so you may know why there are new reflectors being created constantly.

**Comment by sttts** [comment] 2017-10-05 09:39
@frobware I suspect this is the leak of the storage caches that are dynamically created when a CRD is updated.

**Comment by sttts** [comment] 2017-10-05 09:39
Here is the storage creation: https://github.com/sttts/kubernetes/blob/fd09c3dbb67374e4f4b46b820b5cd3d9a3124cda/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L278-L277

**Comment by sttts** [comment] 2017-10-05 09:41
https://github.com/kubernetes/kubernetes/pull/50690 includes code to shutdown storages cleanly. We might need that for CR storages.

**Comment by smarterclayton** [comment] 2017-10-06 00:27
Dupe of https://github.com/kubernetes/kubernetes/issues/52121

**Comment by sttts** [comment] 2017-10-09 14:34
These metrics must be unregistered as well: https://github.com/kubernetes/client-go/blob/82aa063804cf055e16e8911250f888bc216e8b61/tools/cache/reflector.go#L112 when a storage is removed.

**Comment by mml** [comment] 2017-10-12 19:54
Closing as dup of #52121

**Comment by sttts** [comment] 2017-10-12 19:57
@mml it's not a pure dup. Would keep it open.

**Closed** 2017-10-13 12:09 UTC
Labels: kind/bug, priority/important-soon, sig/api-machinery

**Comment by sttts** [comment] 2017-10-19 10:39
Create a cherry-pick for 1.8: https://github.com/kubernetes/kubernetes/pull/54225

**Comment by brancz** [comment] 2017-10-25 12:58
I've been running 1.8.2 for an hour-ish and it seems that the metrics/memory are not growing anymore. Will report again in a couple of hours and or tomorrow. By then I'll be confident saying that it's fixed.

**Comment by sttts** [comment] 2017-10-25 13:07
That's very good news. Let's hope it stays like that.

**Comment by brancz** [comment] 2017-10-26 13:51
Unfortunately my apiserver started crashlooping after ~9 hours because the backing etcd cluster had an issue. Shortly before that the apiserver had a memory usage of around 290Mb after initial ramp up from 260Mb. The `go_memstats_heap_inuse_bytes` metric from the go runtime seems to be stable though, so this just sounds like garbage that hasn't been collected yet. So in short this seems to be fixed :slightly_smiling_face: .

**Comment by gmarek** [comment] 2017-10-31 11:36
@sttts please add regression test for leaking resources when CRDs are used. @kubernetes/sig-scalability-misc looks for leaks when using basic resources, but they can't own whole ever-expanding landscape.
