### ISSUE TITLE
Pods with failed volume mount show ImageNotReady

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#19589] opened 2016-01-13 06:32 UTC
An example pod:
```
Name:				cluster-ssh-server-ouan5
Namespace:			default
Image(s):			tutum/ubuntu:trusty
Node:				gke-cluster-1-b4c97d4d-node-lx67/10.240.0.2
Start Time:			Tue, 12 Jan 2016 18:53:57 +0100
Labels:				role=cluster-ssh-server
Status:				Pending
Reason:
Message:
IP:
Replication Controllers:	cluster-ssh-server (3/3 replicas created)
Containers:
  sshd:
    Container ID:
    Image:		tutum/ubuntu:trusty
    Image ID:
    QoS Tier:
      cpu:	Burstable
    Requests:
      cpu:		100m
    State:		Waiting
      Reason:		ImageNotReady
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False
Volumes:
  nfs:
    Type:	NFS (an NFS mount that lasts the lifetime of a pod)
    Server:	cluster-nfs.default.svc.cluster.local
    Path:	/
    ReadOnly:	false
  default-token-plqgq:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-plqgq
Events:
  FirstSeen	LastSeen	Count	From						SubobjectPath	Reason		Message
  ─────────	────────	─────	────						─────────────	──────		───────
  12h		9s		4543	{kubelet gke-cluster-1-b4c97d4d-node-lx67}			FailedMount	Unable to mount volumes for pod "cluster-ssh-server-ouan5_default": exit status 32
  12h		9s		4543	{kubelet gke-cluster-1-b4c97d4d-node-lx67}			FailedSync	Error syncing pod, skipping: exit status 32
```

**Comment by dchen1107** [comment] 2016-01-13 18:18
@sttts Can you post the related kubelet log somewhere so that we can take a look? Not sure about why volume mount failed here, but obviously the pending reason is misleading and we should fix. @saad-ali too.

**Comment by sttts** [comment] 2016-01-13 21:08
@dchen1107 here it is. The mount fails because the host does not use kube-dns, pretty surprising from a user point of view IMO.

```
I0113 21:04:16.302496    3336 kubelet.go:2012] SyncLoop (ADD): "cluster-ssh-server-66g0x_default"
E0113 21:04:16.578864    3336 mount_linux.go:103] Mount failed: exit status 32
Mounting arguments: cluster-nfs.default.svc.cluster.local:/ /var/lib/kubelet/pods/349796ac-ba39-11e5-be8d-42010af00124/volumes/kubernetes.io~nfs/nfs nfs []
Output: mount.nfs: Failed to resolve server cluster-nfs.default.svc.cluster.local: Name or service not known

E0113 21:04:16.578987    3336 kubelet.go:1383] Unable to mount volumes for pod "cluster-ssh-server-66g0x_default": exit status 32; skipping pod
E0113 21:04:16.581068    3336 pod_workers.go:112] Error syncing pod 349796ac-ba39-11e5-be8d-42010af00124, skipping: exit status 32
I0113 21:04:20.006894    3336 server.go:944] GET /stats/default/cluster-ssh-server-66g0x/349796ac-ba39-11e5-be8d-42010af00124/sshd: (93.69µs) 404 [[Go 1.1 package http] 10.156.1.10:57934]
I0113 21:04:20.016824    3336 server.go:944] POST /stats/container/: (2.187847ms) 0 [[Go 1.1 package http] 10.156.1.10:57939]
I0113 21:04:20.048513    3336 server.go:944] GET /stats/kube-system/fluentd-cloud-logging-gke-cluster-1-b4c97d4d-node-6hbr/f729fc81-ba38-11e5-be8d-42010af00124/fluentd-cloud-logging: (1.507272ms) 0 [[Go 1.1 package http] 10.156.1.10:58126]
I0113 21:04:22.440338    3336 server.go:944] GET /healthz: (1.105895ms) 0 [[curl/7.26.0] 127.0.0.1:51476]
```

The mount is tried a few times with the same log output.

**Comment by AdoHe** [comment] 2016-01-14 03:16
@sttts what's your `kubelet version`?

**Comment by sttts** [comment] 2016-01-18 07:55
@AdoHe it's a GKE cluster with 1.1.3.

**Comment by AdoHe** [comment] 2016-01-18 08:14
@sttts this is kind of tricky, I will try to find the root cause.

**Comment by childsb** [comment] 2016-07-13 15:29
This is a few months (and releases) old, @sttts is this still a problem?

@AdoHe are you still looking at this issue?

**Comment by suquant** [comment] 2016-07-14 11:39
This kind of problem repeat under "quay.io/coreos/hyperkube:v1.2.4_coreos.cni.1" image

```
# kubectl get ev

===
...
Output: mount.nfs: Failed to resolve server ...
===
```

When i use ip of service in "server" field everything working fine !

volume.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-store
  namespace: kube-system
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /media
    server: registry-glusterfs

```

**Comment by AdoHe** [comment] 2016-07-18 03:04
@childsb I am just a little bit busy with my company staff, so if you have bandwidth, please take it.

**Comment by saad-ali** [comment] 2016-08-02 20:07
This code path has changed significantly since this issue was opened. I will close it for now. If you encounter problems with v1.3.4+ please open another issue.

**Closed by saad-ali** 2016-08-02 20:07 UTC
Labels: area/storage, area/volumes, component/kubelet, team/node
