### ISSUE TITLE
Should pod IP be immutable?

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#108281] opened 2022-02-22 18:28 UTC
### What happened?

Today in k8s the IP assigned to a pod, which is a part of the pod status, is mutable. Changing the field through `kubectl edit` doesn't seem to take effect, but the object can be changed through a json patch directly (more under repro steps below). While the IP is again reset back to the original value as part of the next pod status update (done by kubelet periodically), the change itself goes through.

I've cut this issue to understand the reason (if there's one) for letting the pod IP be mutable even after the value is set initially as part of pod creation. For e.g is it allowed to change through the lifetime of a pod?

/sig network
/sig api-machinery

### What did you expect to happen?

Pod IP shouldn't have changed on attempting the patch. Maybe the API call itself should've been rejected?

### How can we reproduce it (as minimally and precisely as possible)?

- Create a pod:
```
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
EOF
```
- Wait for it to start running on a node, by then kubelet would've assigned the pod an IP:
```
$ kubectl get pod some-pod -o yaml
apiVersion: v1
kind: Pod
...
status:
  phase: Running
  podIP: 10.192.21.35
  podIPs:
  - ip: 10.192.21.35
...
```
- Then change the pod IP using json patch:
```
$ curl -k -XPATCH \
> -H "Content-Type: application/json-patch+json" \
> --data '[{"op": "add", "path": "/status/phase", "value": "Running"},{"op": "add", "path": "/status/podIP", "value": "0.0.0.0"}]' \
> http://localhost:8080/api/v1/namespaces/default/pods/some-pod/status
...
  "status": {
    "phase": "Running",
    "podIP": "0.0.0.0",
    "podIPs": [
      {
        "ip": "0.0.0.0"
      }
    ],
...
```

Typically within few seconds, the IP is again reset back to the original value as part of kubelet's periodic pod status update. But the changed value is present in the interim.

### Kubernetes version

Not version-specific AFAIU.

### Cloud provider

N/A

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment] 2022-02-22 21:25
The status is intentionally mutable. I'll defer to @kubernetes/sig-network-api-reviews on whether there are known/expected scenarios where the IP changes during a pod's lifetime.

Write access to pod status is only granted to system components like scheduler, kubelets, and node-controller by default. Cluster superusers can also write to status but are also able to do disruptive things to cluster objects.

**Comment by aojea** [comment] 2022-02-22 21:47
This conversations is related to this topic, specially interesting this comment from @smarterclayton 

https://github.com/kubernetes/kubernetes/pull/93898#issuecomment-920044741

**Comment by sftim** [comment] 2022-02-22 22:42
I recommend opening a documentation issue about making this behavior / risk clear to readers.

**Comment by sftim** [comment] 2022-02-22 22:42
Separately, does anyone want to suggest a feature gate that people can disable if they want to make Pod IP assignments immutable?

**Comment by aojea** [comment] 2022-02-23 06:26
> I recommend opening a documentation issue about making this behavior / risk clear to readers.

yeah, I was going through the code and I still don't have clear all the ramifications of this, there are also a lot of things that depend on the podIPs that are only created at start time , like environment variables and /etc/hosts file on the pods.

> the IP is again reset back to the original value as part of the next pod status update (done by kubelet periodically)

@thockin @khenidak this was discussed on the latest sig-network meeting, the doubt we had is what happens to the host network pods if the kubelet restarts

https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/pkg/kubelet/kubelet_pods.go#L1507-L1528

I think kubelet rebuilds the current status, and the host network pods reflect the right IPs ... that I think is the correct behavior, otherwise,

**Comment by khenidak** [comment] 2022-03-01 18:37
This is by design, for the following reason: Pod API object is tied to a sandbox (network namespace) on a node. The sandbox itself can restart/crash/deleted and come back with a different IPs. Node restart will cause recreation of sandboxes and hence new set of IPs. The pod object itself didn't change but its representation on the node (aka status) has changed.

What you are seeing is kubelet figuring api-server pod.status.IPs != curret-IPs so it must be patched. As for risks, I don't think there are any per-se because everything that operates on PodIPs is designed with mutability in mind. Specifically DNS, Endpoint, and EndpointSlice controllers.

The comment made by @aojea above is related to host-net pod and the impact of a node changing its IP (and thus pod IPs much change as well) today we don't do that and we want to.

**Comment by thockin** [comment] 2022-03-03 21:17
> Write access to pod status is only granted to system components_

100%

> does anyone want to suggest a feature gate that people can disable if they want to make Pod IP assignments immutable?

I don't think we should do that.  If you have untrusted actors setting that
value, you have already lost.

> there are also a lot of things that depend on the podIPs that are only created at start time_

I don't think we are really saying that the IP can change underneath a running
pod.  The Pod object in the API has a longer lifetime than a process or even a
cgroup.

> The sandbox itself can restart/crash/deleted and come back with a different IPs

Exactly.  Consider:
* pod is created
* kubelet starts pod lifecycle
* CNI assigns IP "X"
* kubelet published pod IP X in status                                                                                                                                               
* node crashes
* node reboots
* kubelet restarts
* pod still exists in API!
* kubelet start the pod again
* CNI assigns IP "Y"
* kubelet published pod IP Y in status

**Comment by thockin** [comment] 2022-03-03 21:20
Closing for now - working as intended

**Closed by thockin** 2022-03-03 21:20 UTC
Labels: sig/network, kind/support, needs-triage
