### ISSUE TITLE
After rebooting Master node, cannot connect server anymore

### ISSUE THREAD

**Issue by motek80** [kubernetes/kubernetes#66748] opened 2018-07-29 14:01 UTC
/kind bug

**What happened**:
On CentOS, after rebooting Master node, calling to kubectl produces the following error:

`The connection to the server xxx.xxx.xxx.xxx:6443 was refused - did you specify the right host or port?`

**What you expected to happen**:
Expected that system will continue to function normally after reboot

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow [this guide](https://kubernetes.io/docs/setup/independent/install-kubeadm/), installed kubelet, kubeadm and kubectl
2. Make sure system works (e.g. call "kubectl version")
3. call "reboot"
4. Make sure system doesn't works anymore (e.g. call "kubectl version")

**Anything else we need to know?**:
On Ubuntu 16.04 this not happens

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS / t2.Medium

- OS (e.g. from /etc/os-release):
CentOS 7.5

- Kernel (e.g. `uname -a`):
Linux ip-xxxxxxxxxx.compute.internal 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment] 2018-07-29 23:09
possible duplicate of https://github.com/kubernetes/kubeadm/issues/1026

1. please wait for the node for ~5 minutes, if it doesn't come up there is a problem.

2. please provide detailed logs from the kubelet
```
                        - 'systemctl status kubelet'
                        - 'journalctl -xeu kubelet'
```

/sig cluster-lifecycle
/cc @kubernetes/sig-node-bugs

**Comment by abdennour** [comment] 2018-08-23 12:55
The issue appears also with Ubuntu 16.04 in EC2 instance.

**Comment by neolit123** [comment] 2018-08-23 13:39
@abdennour 
in the above script i'm not seeing a step to install a pod network plugin. `kubeadm` init instructs about that when it finishes.
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

are you doing this step?

**Comment by abdennour** [comment] 2018-08-25 17:54
@neolit123  you have reason. Pod network plugin must be installed and `/etc/docker/daemon.json` must be removed.

**Comment by kheirp** [comment] 2018-09-17 07:04
@abdennour  Did installing the pod network solved your problem ?? as I have Calico already installed but still the same problem. Also, I can't run any kubectl commands as always the connection is refused to the api server. Any recommendations ??

**Comment by neolit123** [comment] 2018-10-26 22:38
please reopen an issue in kubernetes/kubeadm if you think there is a kubeadm bug at play here.

for questions please use our support channels like stackoverflow:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close

**Closed by neolit123** 2018-10-26 22:38 UTC
Labels: kind/bug, sig/cluster-lifecycle, sig/node

**Comment by e-gautier** [comment] 2019-03-03 19:28
For the Googlers, I know it can be silly but have you checked that any swap volume is accidentaly mounted at boot? (fstab etc..)

**Comment by raj12892** [comment] 2019-04-16 14:06
Disable the swap permanently by commenting swap entry in /etc/fstab and reboot you system.
systemctl status kubelet. #should be in running state.
systemctl start Kubelet.  #if not started 
finally if service is failing to start  use 'journalctl -xeu kubelet' to find out the root cause.
kubectl get services.     #finally to check the services are running or not.

**Comment by batman1911** [comment] 2019-04-16 14:33
Check if your SELinux is disabled or not. If its running, run the command setenforce 0, and restart the kubelet services. If it works, change selinux permissive permanently in its conf file and when you restart the machine it wont give you any issues.

**Comment by fabras78** [comment] 2019-07-06 14:49
In my case the problem was that swap memory was turned on.
I removed any matching reference found in /etc/fstab

**Comment by agbonjaru** [comment] 2024-07-12 14:37
Try commenting out swap from the /etc/fstab. Then perform a reboot of the server
