### ISSUE TITLE
Kubectl overview web page not rendered properly  

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#22621] opened 2016-03-07 03:22 UTC
http://kubernetes.io/v1.1/docs/user-guide/kubectl-overview.html#operations the table is almost not readable. 

@kubernetes/docs @caesarxuchao @nikhiljindal

**Comment by bgrant0607** [comment] 2016-03-07 17:53
Dupe of #21876

**Closed by bgrant0607** 2016-03-07 17:53 UTC
Labels: area/website, kind/bug, kind/documentation, team/ux
