### ISSUE TITLE
unit flake: "TestNewMultipleSourcesEndpointsMultipleHandlersAddRemoveSetAndNotified"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#20633] opened 2016-02-04 10:02 UTC
This has failed multiple times already:

config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"3.3.3.3", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"4.4.4.4", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"1.1.1.1", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"2.2.2.2", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil) config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"3.3.3.3", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"4.4.4.4", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"1.1.1.1", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"2.2.2.2", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil) config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"3.3.3.3", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"4.4.4.4", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"7.7.7.7", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil) config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"3.3.3.3", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"4.4.4.4", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"7.7.7.7", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil) config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"7.7.7.7", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil) config_test.go:119: Expected []api.Endpoints{api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"7.7.7.7", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}, api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foobar", GenerateName:"", Namespace:"testnamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset{api.EndpointSubset{Addresses:[]api.EndpointAddress{api.EndpointAddress{IP:"5.5.5.5", TargetRef:(*api.ObjectReference)(nil)}, api.EndpointAddress{IP:"6.6.6.6", TargetRef:(*api.ObjectReference)(nil)}}, NotReadyAddresses:[]api.EndpointAddress(nil), Ports:[]api.EndpointPort{api.EndpointPort{Name:"", Port:80, Protocol:""}}}}}}, Got []api.Endpoints(nil)

Example failures:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/7543/?project=kubernetes-jenkins
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/7540/?project=kubernetes-jenkins
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/7538/?project=kubernetes-jenkins

@kubernetes/goog-cluster

**Comment by saad-ali** [comment] 2016-02-04 18:46
This is a duplicate of #20613

**Comment by wojtek-t** [comment] 2016-02-04 19:02
@saad-ali - I don't think it's a duplicate - this is unit test, not integration test...

**Comment by bprashanth** [comment] 2016-02-04 19:04
closed via https://github.com/kubernetes/kubernetes/pull/20657

**Closed by bprashanth** 2016-02-04 19:04 UTC
Labels: area/test, kind/flake, priority/P0, team/cluster

**Comment by saad-ali** [comment] 2016-02-04 22:41
@saad-ali - I don't think it's a duplicate - this is unit test, not integration test...

#20613 was mislabeled integration. It's includes the same tests including `TestNewMultipleSourcesEndpointsMultipleHandlersAddRemoveSetAndNotified`. Hopefuly #20657 fixed it. It hasn't reoccurred in the last 4 hours since that was merged.

**Comment by wojtek-t** [comment] 2016-02-05 07:12
@saad-ali - ok thanks!
