### ISSUE TITLE
[Failing Test] gce-cos-master-scalability-100 (ci-kubernetes-e2e-gci-gce-scalability)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91540] opened 2020-05-28 16:11 UTC
**Which jobs are failing**:

`gce-cos-master-scalability-100 (ci-kubernetes-e2e-gci-gce-scalability)`

**Which test(s) are failing**:

`ClusterLoaderV2`
`diffResources`

**Since when has it been failing**:

`05-28-20 04:24 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

**Reason for failure**:

```
W0528 13:41:57.787] 2020/05/28 13:41:57 main.go:312: Something went wrong: encountered 2 errors: [error during /go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-1265992669033664512 --nodes=100 --prometheus-scrape-node-exporter --provider=gce --report-dir=/workspace/_artifacts --testconfig=testing/density/config.yaml --testconfig=testing/load/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/use_simple_latency_query.yaml --testoverrides=./testing/load/gce/throughput_override.yaml: exit status 1 Error: 2 leaked resources
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19
/sig scalability
/assign @sayanchowdhury

**Comment by hasheddan** [comment] 2020-05-28 18:56
@sayanchowdhury looks like this has recovered 👍 can you see if you can identify what the underlying issue was? I’ll continue to monitor and close this out if we stay green

**Comment by sayanchowdhury** [comment] 2020-05-28 18:57
Sure, I will look into it tomorrow.

**Comment by mm4tt** [comment] 2020-05-29 07:52
It was caused by quay.io outage - https://status.quay.io/
Fixed in https://github.com/kubernetes/perf-tests/pull/1289

For the future, you can assign such issues to scalability oncall - https://go.k8s.io/oncall

**Comment by hasheddan** [comment] 2020-05-29 10:37
Thanks @mm4tt!

/close

**Closed** 2020-05-29 10:37 UTC
Labels: kind/failing-test, priority/critical-urgent, sig/scalability
