### ISSUE TITLE
Kube-proxy socket descriptor leak

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#18354] opened 2015-12-08 15:12 UTC
While investigating a socket leak in our kubernetes-deployed application, I have found out that the kube-proxy also seems to have a serious leak of its own.

In two of my three nodes, out of the ~44K connections of the kube-proxy ....

```
ubuntu@ip-172-20-0-60:~$ sudo netstat -np | grep kube-proxy > netstat.txt
ubuntu@ip-172-20-0-60:~$ wc -l netstat.txt
44445 netstat.txt
```

... about 65% are legit established connections caused by the aforementioned leak ...
```
ubuntu@ip-172-20-0-60:~$ grep ESTABLISHED netstat.txt | wc -l
28922
```

... but ~14K are in FIN_WAIT2 state ...
```
ubuntu@ip-172-20-0-60:~$ grep FIN_WAIT2 netstat.txt | wc -l
14544
```

... and ~1K are in CLOSE_WAIT.
```
ubuntu@ip-172-20-0-60:~$ grep CLOSE_WAIT netstat.txt | wc -l
977
```

Here's some debug info:

* Gist with service descriptions, node descriptions and iptables rules from node `ip-172-20-0-60` (we are running kubernetes 1.1 in AWS): https://gist.github.com/2opremio/24adfa5a10b45b1b77da
* Goroutine dump of kube-proxy at node `ip-172-20-0-60`, obtained with `curl localhost:10249/debug/pprof/goroutine?debug=2`: [kube-proxy-go-routines.log.gz](https://www.dropbox.com/s/2bfz30z4q7pt5dl/kube-proxy-go-routines.log.gz?dl=1)
* `sudo netstat -np | grep kube-proxy` at node `ip-172-20-0-60`: [netstat.txt.gz](https://www.dropbox.com/s/1q4ncrf1xzxuj5b/netstat.txt.gz?dl=1)
* `/proc/sys/net/ipv4/tcp_fin_timeout` has a value of 60 in all my nodes.

After deploying the fix for application-level leak and waiting 10 minutes, according to `sudo netstat -np | grep kube-proxy` the number of ESTABLISHED connections is ~100 in all nodes as expected but, in the two affected nodes:

* The CLOSE_WAIT connections only halve from 1K to 500
* The FIN_WAIT2 ones also halve from 14K to 7K

I obtained new goroutine and netstat dumps, in case it helps:

* [kube-proxy-go-routines-after.log.gz](https://www.dropbox.com/s/xxcz0eb5p4l6xqt/kube-proxy-go-routines-after.log.gz?dl=1)
* [netstat-after.txt.gz](https://www.dropbox.com/s/o6igs1avb01apr1/netstat-after.txt.gz?dl=1)

Also, it may be valuable to know that the application-level leaks were caused by a websocket proxy (part of the `app-mapper` pods) which failed to clean up connections when the client-side closed the underlying TCP socket. Both the app-mapper and the destination are accessed through kubernetes services, which means that the kube-proxy is caught up in-between:

```
 frontend -> (kube-proxy local to frontend) -> app-mapper -> (kube proxy local to app-mapper) -> destination
```

The two kube-proxy instances affected live in the same nodes where the two app-mapper pods live: `ip-172-20-0-60` and `ip-172-20-0-62`

**Comment by 2opremio** [comment] 2015-12-08 15:19
Uhm, I have noticed that netstat somehow wasn't reporting all the sockets.

```
ubuntu@ip-172-20-0-60:~$ sudo netstat -np | grep kube-proxy | wc -l
7766
ubuntu@ip-172-20-0-60:~$ sudo ls -la /proc/$(pgrep kube-proxy)/fd | wc -l                                                         
14587
```

Whilst lsof does:

```
ubuntu@ip-172-20-0-60:~$ sudo lsof -n -p $(pgrep kube-proxy) | wc -l
14613
```

The extra entries seem to correspond to of the type:

`kube-prox 12985 root   36u  sock                0,8      0t0 49333002 can't identify protocol`

So, my analysis above still applies.

```
ubuntu@ip-172-20-0-60:~$ sudo lsof -n -p $(pgrep kube-proxy) | grep -v "can't identify" | wc -l
7783
ubuntu@ip-172-20-0-60:~$ sudo lsof -n -p $(pgrep kube-proxy) | grep  "can't identify" | wc -l
6839
```

Here's the lsof listing in case it helps: [lsof-after.txt.gz](https://www.dropbox.com/s/46x02vwa1icy8ji/lsof-after.txt.gz?dl=1)

**Comment by thockin** [comment] 2015-12-09 00:52
Can you post anything interesting from kube-proxy.log?  Does anything
appear to be spinning?  Maybe try bumping the kube-proxy --v flag to 4 and
reproducing

**Comment by thockin-cc** [comment] 2015-12-09 01:09
For record: The majority of hung goroutines (about 2/3 of them) are at `go
copyBytes("from backend", in, out, &wg)`.  The other third are at `go
copyBytes("to backend", out, in, &wg)`, both of which call down to
`io.Copy()`.

I note that we half-close (CloseWrite(), CloseRead()) connections in each
direction.  I'm not sure I recall why exactly.  I could try some tweaks
around here to get more info - are you willing to run a test binary for me?

**Comment by 2opremio** [comment] 2015-12-09 12:04
> Can you post anything interesting from kube-proxy.log?  Does anything
appear to be spinning?  Maybe try bumping the kube-proxy --v flag to 4 and
reproducing

The kube-proxy logs were empty (rotated by `journalctl` I guess) but I can try to reproduce in a separate cluster.

> I note that we half-close (CloseWrite(), CloseRead()) connections in each
direction.  I'm not sure I recall why exactly. 

It would be good to know, 7K are a lot plus they escape netstat (and I would bet that the same happens with most monitoring systems).

> I could try some tweaks
around here to get more info - are you willing to run a test binary for me?

Sure

**Comment by 2opremio** [comment] 2015-12-09 15:50
I have reproduced it with our unfixed, leaky app and kube-proxy running with `-v4` (in fact I can reproduce it systematically).

I can confirm that, for each descriptor pair our application leaks, kube-proxy gets one socket in CLOSE_WAIT and another one in FIN_WAIT2. Again, to give more context on our application:

```
 frontend -> (kube-proxy local to frontend) -> app-mapper -> (kube proxy local to app-mapper) -> destination
```

What's happening is that the frontend closes the client socket, but the app-mapper (which is proxying the frontend connection to the destination) doesn't close its connection pair. The CLOSE_WAIT socket in kube-proxy corresponds to the frontend ("from" side) socket and the FIN_WAIT2 to the app-mapper ("to" side).

My theory is that, when cleaning up a connection pair (due to the client closing its connection), kube-proxy expects the other end in the "to" connection to close it right away, but when it doesn't (due to the leak in this case) it stays in the FIN_WAIT2 state forever and leaving the "from" side in CLOSE_WAIT (why the app-mapper sends an ACK but not a FIN, I don't know). I think that, unlike what you stated in https://github.com/kubernetes/kubernetes/issues/17641#issuecomment-158915461, kube-proxy should probably timeout the connections on the "to" end after certain time. I don't see a point to wait for the "to" end if the "from" end was closed. I am not familiar with kube-proxy's internals so my reasoning may be an oversimplification or simply wrong.

Here is the netstat listing from one of the affected nodes:

```
ubuntu@ip-172-20-0-219:~$ sudo netstat -np | grep kube-proxy 
tcp        0      0 172.20.0.219:59268      10.244.2.23:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 172.20.0.219:59505      10.244.2.23:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 10.244.0.1:45619        10.244.0.13:80          ESTABLISHED 21210/kube-proxy
tcp        0      0 10.244.0.1:53013        10.244.0.15:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 10.244.0.1:53576        10.244.0.15:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 172.20.0.219:47075      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:46616      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:45959      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:45336      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:54488      10.244.1.6:80           ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:45588      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:44098      172.20.0.9:443          ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:47044      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:44097      172.20.0.9:443          ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:32809      10.244.2.23:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 10.244.0.1:58715        10.244.0.4:9200         ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:60776      10.244.2.23:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 172.20.0.219:46098      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:44791      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:44059      172.20.0.9:443          ESTABLISHED 21210/kube-proxy
tcp        0      0 10.244.0.1:52088        10.244.0.15:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 10.244.0.1:51837        10.244.0.15:80          ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:46512      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 10.244.0.1:52746        10.244.0.15:80          FIN_WAIT2   21210/kube-proxy
tcp        0      0 172.20.0.219:46245      10.244.2.11:4040        ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:44096      172.20.0.9:443          ESTABLISHED 21210/kube-proxy
tcp        0      0 172.20.0.219:59899      10.244.2.23:80          FIN_WAIT2   21210/kube-proxy
tcp6       0      0 10.244.0.1:32774        10.244.0.15:41286       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40007       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40984       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40525       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:57396       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40421       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:57258       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:58321       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:32774        10.244.0.15:41561       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:39497       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:57145       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40154       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:58529       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:58795       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:39868       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:40953       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:39245       ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:55905        10.244.0.2:35473        ESTABLISHED 21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:58054       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:58884       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:57021       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:60711        10.244.0.11:57652       CLOSE_WAIT  21210/kube-proxy
tcp6       0      0 10.244.0.1:57408        10.244.0.15:38700       ESTABLISHED 21210/kube-proxy
unix  3      [ ]         STREAM     CONNECTED     42964067 21210/kube-proxy    
unix  3      [ ]         STREAM     CONNECTED     42963318 21210/kube-proxy 
```

Here are the service descriptions:

```
$ kubectl describe svc
Name:			app-mapper
Namespace:		default
Labels:			name=app-mapper
Selector:		name=app-mapper
Type:			ClusterIP
IP:			10.0.127.213
Port:			<unnamed>	80/TCP
Endpoints:		10.244.0.15:80,10.244.2.23:80
Session Affinity:	None
No events.

Name:			frontend
Namespace:		default
Labels:			name=frontend
Selector:		name=frontend
Type:			LoadBalancer
IP:			10.0.136.83
LoadBalancer Ingress:	[ omitted for privacy reasons ]
Port:			<unnamed>	80/TCP
NodePort:		<unnamed>	32533/TCP
Endpoints:		10.244.0.11:80,10.244.2.13:80
Session Affinity:	None
No events.

Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			10.0.0.1
Port:			<unnamed>	443/TCP
Endpoints:		172.20.0.9:443
Session Affinity:	None
No events.

Name:			monitoring
Namespace:		default
Labels:			name=monitoring
Selector:		name=monitoring
Type:			ClusterIP
IP:			10.0.248.220
Port:			grafana	3000/TCP
Endpoints:		10.244.2.14:3000
Port:			prometheus	9090/TCP
Endpoints:		10.244.2.14:9090
Session Affinity:	None
No events.

Name:			scope-app-2
Namespace:		default
Labels:			name=scope-app-2
Selector:		name=scope-app-2
Type:			ClusterIP
IP:			10.0.140.125
Port:			<unnamed>	4040/TCP
Endpoints:		10.244.2.11:4040
Session Affinity:	None
No events.

Name:			ui-server
Namespace:		default
Labels:			name=ui-server
Selector:		name=ui-server
Type:			ClusterIP
IP:			10.0.25.182
Port:			<unnamed>	80/TCP
Endpoints:		10.244.0.12:80,10.244.2.15:80
Session Affinity:	None
No events.

Name:			users
Namespace:		default
Labels:			name=users
Selector:		name=users
Type:			ClusterIP
IP:			10.0.184.203
Port:			<unnamed>	80/TCP
Endpoints:		10.244.0.13:80,10.244.1.6:80
Session Affinity:	None
No events.
```

And here are the logs of the kube-proxy running in the same node: [kube-proxy.log.gz](https://www.dropbox.com/s/iqoovkejfvkw44h/kube-proxy.log.gz?dl=1)

**Comment by 2opremio** [comment] 2015-12-09 21:27
After having a look at the code, causing a couple of leaks and removing all pods to reduce the connections of the kube-proxy to a minimum, I have a pretty good idea of what's happening. 

The [`to backend` copier](https://github.com/kubernetes/kubernetes/blob/v1.1.1/pkg/proxy/userspace/proxysocket.go#L154) exits, but its [`from backend` counterpart](https://github.com/kubernetes/kubernetes/blob/v1.1.1/pkg/proxy/userspace/proxysocket.go#L153) doesn't.

I need to confirm this, but my guess is that the [`dest.CloseWrite()` and `src.CloseRead()`](https://github.com/kubernetes/kubernetes/blob/v1.1.1/pkg/proxy/userspace/proxysocket.go#L168-L169) in the `to backend` copier are not enough to guarantee that `io.Copy()` in the `from backend` routine returns if the remote end doesn't close the socket.


```
ubuntu@ip-172-20-0-219:~$ sudo netstat -npt | grep kube-proxy 
tcp        0      0 172.20.0.219:54900      10.244.2.6:80           FIN_WAIT2   9513/kube-proxy 
tcp        0      0 172.20.0.219:41914      172.20.0.9:443          ESTABLISHED 9513/kube-proxy 
tcp        0      0 172.20.0.219:41915      172.20.0.9:443          ESTABLISHED 9513/kube-proxy 
tcp        0      0 172.20.0.219:54362      10.244.2.6:80           FIN_WAIT2   9513/kube-proxy 
tcp6       0      0 10.244.0.1:55283        10.244.0.9:54173        CLOSE_WAIT  9513/kube-proxy 
tcp6       0      0 10.244.0.1:55283        10.244.0.9:53635        CLOSE_WAIT  9513/kube-proxy 
```

```
ubuntu@ip-172-20-0-219:~$ curl -s localhost:10249/debug/pprof/goroutine?debug=2 | grep proxysocket.go:154
ubuntu@ip-172-20-0-219:~$ curl -s localhost:10249/debug/pprof/goroutine?debug=2 | grep proxysocket.go:153
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/userspace/proxysocket.go:153 +0x330
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/userspace/proxysocket.go:153 +0x330
```

You may find the full go-routing stack here: https://gist.github.com/2opremio/d6ae289ce5db698f3989

**Comment by thockin** [comment] 2015-12-10 00:47
Good news - I have a clue what is happening (I think).  I am pretty sure it
is the half-close logic we have - it's technically possible to close just
one direction of a TCP session.  If the client closes the socket, the proxy
gets a signal that the client read-side closed and closes the backend's
write-side.  But it does not get a signal that the client's write side
closed (because POSIX, that's why).

If the backend responds by closing the socket (since it knows if it has
more data to send or not), the proxy gets a signal that the backend
read-side closed and closes the client's write side.

If the backend DOES NOT close the socket, the proxy waits forever.  It does
not get a signal that the client's write side closed.

So the easy fix is to not try the half-close stuff and just say that closed
means closed, lingering data be damned.  The more robust fix might be to
start a timeout on the backend once the client disconnects.

Here is a kube proxy binary which just closes the connection - try it out?

http://hockin.org/~thockin/kube/kube-proxy

**Comment by thockin** [comment] 2015-12-10 00:48
Specifically run with --v=4 and let me see logs :)

**Comment by 2opremio** [comment] 2015-12-10 01:48
>  If the client closes the socket, the proxy
gets a signal that the client read-side closed and closes the backend's
write-side.  But it does not get a signal that the client's write side
closed (because POSIX, that's why).

Yep, that matches my observations above.

> If the backend DOES NOT close the socket, the proxy waits forever.  It does
not get a signal that the client's write side closed.

I haven't run your binary but in parallel to your investigations I have come up with a simple repro which does exactly that.

```go
package main

import "net"

func main() {
        l, _ := net.Listen("tcp", "0.0.0.0:9999")
        defer l.Close()
        for {
                conn, _ := l.Accept()
                // defer conn.Close()
                conn.Write([]byte("Creating leak\n"))
        }
}
```

```
$ kubectl run leaker --image=2opremio/leaker # this image simply executes the code above
replicationcontroller "leaker" created
$ kubectl expose rc leaker --port=9999                                                                                                                                                                                       
service "leaker" exposed
```

For every leak created by the service I get a `CLOSE_WAIT`/`FIN_WAIT2` pair in the kube-proxy.
```
$ netcat $(kubectl get svc leaker -o template --template '{{.spec.clusterIP}}') 9999
Creating leak
^C
```

I can run your binary tomorrow if you still need me to, but I think this confirms your theory.

> So the easy fix is to not try the half-close stuff and just say that closed means closed, lingering data be damned.  The more robust fix might be to start a timeout on the backend once the client disconnects.

I believe that the opposite timer (on the client once the backend disconnects) would also be necessary

**Comment by 2opremio** [comment] 2015-12-10 02:46
I found some time and got the logs with a recent unmodified kube-proxy binary and the one you provided: https://gist.github.com/2opremio/ea12e7455630c59d3e4c

They confirm that the problem comes from the current use of `CloseWrite()` and `CloseRead()`.

I am curious to know how half-closing affects the TCP socket to get into the FIN_WAIT2 state. My initial assumption, just like @romanek-adam's at https://github.com/kubernetes/kubernetes/issues/17641#issuecomment-159894747 was that the server was sending an ACK but not a FIN, but I am not sure that's the case anymore.

**Comment by thockin** [comment] 2015-12-10 05:27
Thanks for the confirmation.  I can't say for sure whether these are the
exact same problem, but they are suspiciously similar.

I'll try to work up a real patch tomorrow.

**Comment by thockin** [comment] 2015-12-10 19:38
Patch is out for review.  Thanks for the help!

**Closed** 2015-12-17 09:33 UTC
Labels: team/cluster
