### ISSUE TITLE
federation: premature confirmation of the deletion of replica sets

### ISSUE THREAD

**Issue by lguminski** [kubernetes/kubernetes#38493] opened 2016-12-09 13:18 UTC
Steps to reproduce:
```
$ kubectl --context=federation delete rs k8shserver
replicaset "k8shserver" deleted
$ kubectl --context=federation create -f rs/k8shserver.yaml 
Error from server: error when creating "rs/k8shserver.yaml": object is being deleted: replicasets "k8shserver" already exists
```
Expected:
`kubectl delete rs` command should complete after all replica sets from all underlying clusters are deleted.

Observed:
command completed although there are still replica sets being deleted.

**Comment by calebamiles** [comment] 2016-12-12 19:38
Could someone from @kubernetes/sig-federation help triage this issue further?

**cc: @matchstick**

**Comment by nikhiljindal** [comment] 2016-12-16 20:37
Yes I can repro this bug. replicasets is still alpha.
The replicaset did go away after some time.

Adding kubectl tests for federation are going to help us catch such issues sooner https://github.com/kubernetes/kubernetes/issues/32826


Also note that we want to disable cascading deletion by default for federation resources: https://github.com/kubernetes/kubernetes/issues/38897

**Comment by nikhiljindal** [comment] 2016-12-16 20:38
cc @mwielgus who worked on replicasets

**Comment by mwielgus** [comment] 2017-01-18 22:35
Actually this is kind of expected behavior. Even in regular kubernetes api calls are non-blocking, they just mark something for deletion and the deletion is executed in the background, usually quite fast. In federation we follow the same pattern. However it is not that instantaneous as in regular kubernetes so you may get an impression that it works in a different way.

**Comment by lguminski** [comment] 2017-03-03 00:09
Probably the first message should be more explanatory. Instead of

replicaset "k8shserver" deleted

something like

replicaset "k8shserver" has been marked for deletion

**Comment by grodrigues3** [comment] 2017-03-10 22:09
@mwielgus since this is listed as "expected" behavior, i'm going to close this issue.  Reopen if needed

**Closed by grodrigues3** 2017-03-10 22:09 UTC
Labels: kind/bug, sig/federation

**Comment by csbell** [comment] 2017-03-10 22:16
I'll re-open -- the last suggestion from @lguminski is actually a good one (moved to 1.7 however).

**Comment by nikhiljindal** [comment] 2017-03-10 22:18
https://github.com/kubernetes/kubernetes/issues/42594 will fix this.
I think we can close this as a duplicate.
