### ISSUE TITLE
Idle cluster, CPU usage increasing

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#10659] opened 2015-07-02 01:21 UTC
Over the course of ~ 18 hours, my idle cluster's CPU usage went from ~5% -> ~20%. I repeated it with another cluster, which seems to have a single node with increasing CPU usage. 

Surprisingly, kubelet seems to be the hog. I used pprof to figure it out. It turns out to be the __exec based liveness probe__ that the kube-dns pod uses. Turning that off makes kubelet stop using so much CPU. The before & after pprof chart was very clear.

I don't have an answer for why the usage grows over time; maybe docker keeps some history such that every exec returns a bit more data than the previous one?

**Comment by lavalamp** [comment] 2015-07-02 01:21
@dchen1107 for node problem

@thockin can we replace the exec liveness probe with something?

**Comment by bprashanth** [comment] 2015-07-02 01:30
Nice. I made a mental note to myself that if anything was using exec on the node we might run into weirdness because of a potential timer leak: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L488

But I dismissed it at the time. Does your pprof have a bloated siftdown timer block by any chance?

**Comment by bprashanth** [comment] 2015-07-02 01:34
Hmm, I take that back, the timeout is too small really. But can you post the pprof?

**Comment by lavalamp** [comment] 2015-07-02 01:39
Sorry, I didn't actually save the pprof from the broken state. But it's easy to reproduce. It did have a small timer section, but the vast majority of the time went to json decoding docker output (and the associated garbage cleanup).

**Comment by bprashanth** [comment] 2015-07-02 01:42
then ignore my eagerness to correlate to other cpu issues I've seen

**Comment by derekwaynecarr** [comment] 2015-07-02 02:02
So is this an issue with any exec liveness probe or just this probe?

**Comment by lavalamp** [comment] 2015-07-02 05:01
@bprashanth You're not wrong, that's clearly a bug, just not this bug :)

@derekwaynecarr I think it's probably all exec probes, barring further evidence.

Further detail: after turning off the exec probe, my cluster's CPU stopped growing but did not go down.

**Comment by dchen1107** [comment] 2015-07-02 05:28
Will look into it tomorrow.

**Comment by thockin** [comment] 2015-07-02 05:51
Without that probe we have no real way to know when DNS is in trouble.

**Comment by lavalamp** [comment] 2015-07-04 03:36
Further followup: I rebooted the offending kubelet and the CPU dropped back to its initial level. Rebooting a different kubelet didn't have any effect. So it seems clear that exec leaks something.

**Comment by dchen1107** [comment] 2015-07-06 22:34
I did measurement over the long weekend through heapster, and couldn't reproduce the issue. I did observe slight cpu usage increase by running docker exec, but not as obvious as what reported here. Chatted with @lavalamp offline, he observed such increase from GCE pantheon ui, which is known NOT-ACCURATE since it includes all overheads for running VM itself.

**Comment by lavalamp** [comment] 2015-07-06 22:52
I can readily believe it's not accurate (it doesn't agree with ```top```, for example), but since restarting kubelet made the numbers go back down, I don't believe the VM overhead is a contributing factor.

**Comment by dchen1107** [comment] 2015-07-07 00:38
I sync-ed my client to HEAD, which includes ##10763, then I brought up a cluster after lunch, and monitored kubelet usage through heapster, and couldn't reproduce the issue. I will leave the cluster for one night, and recheck it.

**Comment by lavalamp** [comment] 2015-07-07 01:15
I started a cluster from head just now, too. We'll see if I repro. :)

**Comment by dchen1107** [comment] 2015-07-07 16:46
I leave my cluster run over-night. node af12 has kubernetes dns pod running and invoke docker exec every 10s. The below is kubelet cpu usage on node af12 over last 18 hours: 

![kubelet_cpuusage_af12](https://cloud.githubusercontent.com/assets/7740897/8551081/50302782-2489-11e5-9724-f91407d610cc.png)

There is slight cpu usage increase, but overall usage is ~2%. Based on this graph, it is not worthy doing anything for 1.0. 

We are going to continue monitoring this for more soaking time.

**Comment by lavalamp** [comment] 2015-07-07 16:59
I can no longer reproduce this, either. Will assume that #10763 fixed the vast majority of the problem. Thanks, Prashanth!

**Comment by alex-mohr** [comment] 2015-07-07 17:02
Triaged to P0 in war room -- continually increasing CPU usage breaks clusters, so until we're sure it's fixed (and not just likely fixed), leaving open as P0.

FWIW, the CPU reporting is in some sense the most accurate with that caveat that it includes all of the VM's usage -- user level, system level, kernel level, and yes, hypervisor overheads -- and is reflective of what the user sees as available for their own use.  Even if the cpu usage is coming from a different source than kubelet, kubernetes isn't usable if $unknown_source climbs to 50+% usage.

**Comment by alex-mohr** [comment] 2015-07-07 17:09
Also, @dchen1107 or @lavalamp -- seems like there's a test or release coverage gap here?  Presumably this isn't something that'd make it out to an official borg or omega release.  Do either of you have enough context to file an issue and/or propose something that would catch these next time?

**Comment by bprashanth** [comment] 2015-07-07 17:11
We can modify the soak test to catch leaks

**Comment by alex-mohr** [comment] 2015-07-07 17:17
Just remembered: discussed a couple weeks back, see also discussion at tail of #10471 @quinton-hoole

**Comment by quinton-hoole** [comment] 2015-07-07 19:34
@bprashanth Totally agree - soak tests are good place to do this sort of thing, and relatively straightforward.  In fact, irrespective of soak tests, an e2e test that checks resource usage and/or response latency of system component (see discussion at end of #10471), and fails if these are out of specification would be both simple to write a generally very useful.  It could/would:

1. run concurrently with other e2e tests during pre-merge checks to catch egergious performance regressions before merging, 
2. run repeatedly against soak test clusters and detect slow resource leaks like those detailed in this issue
3. run in our normal serial and parallel e2e tests to detect inconsistent performance/resource usage characteristics.

I'll open a post-v1.0 issue now to make sure that this gets done.

**Comment by dchen1107** [comment] 2015-07-07 20:23
@quinton-hoole Thanks for filing the issue. @yujuhong and @vmarmol has been doing resource benchmarking for both kubelet, kube-proxy and docker. They collected a lot of stats, but not published because the source base is keeping change. I just talked to @yujuhong earlier this morning to measure those usages against latest kubelet. We could carry this effort along with soak test and #10860. 

@alex-mohr and @roberthbailey For production support, especially for hosted master, the ideal situation is that by default configuring GCM for kubelet running on master node with some threshold as alert; if the usage is exceeding the threshold, file tickets to us. I talked to GCM guru, Jeremy, and @a-robinson to have API avaliable for alert earlier. We should file internal issue for this.

**Comment by bprashanth** [comment] 2015-07-07 20:26
Think there's still a cpu issue here. The docker inspect command continuously appends exec ids to the container info. Decoding container json for pods with exec probes gets more and more intense over time (we do at least one docker inspect per container every sync). More context: https://github.com/docker/docker/issues/14444.

We can work around this by reusing execs: https://github.com/GoogleCloudPlatform/kubernetes/pull/10862, or always using nsinit. Unsure if we want to at this point.

**Comment by dchen1107** [comment] 2015-07-07 21:24
@bprashanth docker exec has resource leakage (both cpu and memory) is known issue. If you take a look at the graph I posted above, there is slightly increasing too over time. Docker claimed that the fix is included in 1.7 release. 

At this moment, I am hesitated to take any dramatic change for 1.0 cut this Friday. Based on the data I collected so far, I prefer to leave as is.

**Comment by yujuhong** [comment] 2015-07-07 22:11
> At this moment, I am hesitated to take any dramatic change for 1.0 cut this Friday. Based on the data I collected so far, I prefer to leave as is.

For a long-running cluster, the cpu/memory increase could be pretty serious, especially since our dns add-on relies on exec for liveness probe.

At the very least, we should document this behavior. It'd be better if we can change our cluster add-ons to not use this feature.

**Comment by dchen1107** [comment] 2015-07-07 22:40
@brendandburns and @vishh How badly we switch back to use nsinit instead of docker exec?

**Comment by bprashanth** [comment] 2015-07-07 22:48
IMO the more serious problem here is the inclusion of the exec ids in the inspect output. Whatever leaks they have, they'll fix, and we'll roll out a new version of docker. Doesn't sound like they're even planning to fix the inspect, so anyone with an n1-standard-1 cluster will basically end up with unfathomable cpu starvation issues if they don't periodically restart the kubelet. 

At the very least I don't think our default out of box cluster should have a leak. One idea is to run a sidecar container for kube-dns, that shells out the nslookup and exposes it via an http probe.

**Comment by alex-mohr** [comment] 2015-07-07 22:49
If we're using 2% more cpu a day, that's a pretty bad experience after not-too-many days.  And I assume kubelet restarts won't fix, since it's a docker issue?

I don't understand why nsinit wasn't working for us.

And if the only exec usage at the moment is to health check our dns addon, kube2sky, that we 100% control (?), which cannot be health-checked except via exec, perhaps we could add a /healthz handler to it?  Or run a side-car container that answers /healthz by forking whatever command needs to be exec'd and returning the status?

CPU starvation is not something we should ship with, so I continue to claim P0 and v1 blocker.

**Comment by alex-mohr** [comment] 2015-07-07 22:50
And if restarting kubelet is a workaround, then min bar is a cronjob that whacks it once every N hours.

**Comment by bprashanth** [comment] 2015-07-07 22:51
I believe we'd need to restart the containers themselves to clear the exec ids

**Comment by dchen1107** [comment] 2015-07-07 23:04
Ok, to stop the bleeding, I am going to deprecate docker exec and remove livenessProber from dns pod for now. @bprashanth proposed to try to change docker exec to http prober for 1.0

**Comment by thockin** [comment] 2015-07-07 23:05
Discussion, summary:

1) dawn: disable liveness probe for DNS
2) prashanth: whip up an exec-to-healthz container, takes command and period, publishes status to healthz code.
3) if (2) is successful, rebuild kube-dns with it
4) dawn: document exec probes as broken in v1
5) tim: try to add fuel to Docker #14444
6) later: decide on exec probes, drop 'docker exec' if issue goes nowhere and rely on something else.

Worst case, we ship with no liveness probe for DNS.  Best case, we have a cool new sidecar container.

**Comment by brendandburns** [comment] 2015-07-07 23:11
we could also use a TCP socket health check on port 53 as a poor man's health check.

**Comment by thockin** [comment] 2015-07-07 23:19
This would be only marginally better than no liveness probe - I am not so
much worried about the server not listening as I am about it not producing
results.

**Comment by brendandburns** [comment] 2015-07-07 23:21
yeah, though is bouncing the container really going to help it produce results?

**Comment by thockin** [comment] 2015-07-07 23:24
maybe.  It helped in the past when skydns could not talk to etcd because it
raced at startup.  I really want multi-container or whole-pod bounces, but
that is a larger feature (already filed)

**Comment by dchen1107** [comment] 2015-07-07 23:38
@alex-mohr on why not switch back to nsinit:  Kubelet still has that support if docker exec is not available. We could fall back to nsinit. But containervm image removed nsinit recently after we switched to docker native exec. Also this introduces another dependency on our node too.

**Comment by goltermann** [comment] 2015-07-08 16:52
Moving from P0 to P1 and to v1.0-post milestone.  A workaround is in, and that's enough for v1.

**Comment by dchen1107** [comment] 2015-07-08 17:00
#10760 for release document

**Comment by philk** [comment] 2015-07-08 22:25
docker/docker#12899 is probably relevant to this issue. We ran into a number of weird issues (cpu, memory, stalls, failure to exec) when using docker exec for a periodic health check (not even using k8s).

**Comment by piosz** [comment] 2015-07-09 08:13
This may be also caused by Heapster itself https://github.com/GoogleCloudPlatform/heapster/pull/397

**Comment by dchen1107** [comment] 2015-07-09 20:42
@piosz that explains Heapster's memory leakage issue I observed when working on 
https://github.com/GoogleCloudPlatform/kubernetes/pull/10653#issue-92503401

**Comment by bprashanth** [comment] 2015-07-09 20:55
Heapster wasn't on my node and that doesn't correlate with the exec probe restart causing cpu to fall. Of course, heapster has issues of its own :)

**Comment by lavalamp** [comment] 2015-07-09 22:34
Heapster may have its own problems, but it wasn't the cause of my initial
report.

**Comment by yujuhong** [comment] 2016-08-11 23:54
The docker exec issue (https://github.com/docker/docker/issues/14444) was closed long agao and we already have resource usage test running repeatedly int he soak cluster. Closing this ancient issue.

**Closed by yujuhong** 2016-08-11 23:54 UTC
Labels: kind/bug, priority/P1, team/node
