### ISSUE TITLE
e2e: Quota 'ROUTES' exceeded.  Limit: 170.0

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#26271] opened 2016-05-25 16:37 UTC
http://pr-test.k8s.io/26243/kubernetes-pull-build-test-e2e-gce/41944/build-log.txt

The `e2e` and `Node e2e` tests are hitting the following errors:
```
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-agent-pr-3-0-minion-e2e-gce-agent-pr-3-0-http-alt' was not found
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-agent-pr-3-0-minion-e2e-gce-agent-pr-3-0-nodeports' was not found
Bringing down cluster using provider: gce
```

```
ERROR: gcloud crashed (OSError): [Errno 39] Directory not empty: '/usr/local/share/google/google-cloud-sdk.staging/lib/googlecloudsdk/third_party/apis'

If you would like to report this issue, please run the following command:
  gcloud feedback
Project: kubernetes-jenkins-pull
Zone: us-central1-f
INSTANCE_GROUPS=
NODE_NAMES=
Bringing down cluster
ERROR: gcloud failed to load: No module named argcomplete
```

```
WARNING: You are creating a legacy network. Using --mode=legacy will be required in future releases.
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Quota 'ROUTES' exceeded.  Limit: 170.0

2016/05/25 06:28:42 e2e.go:206: Error running up: exit status 1
2016/05/25 06:28:42 e2e.go:202: Step 'up' finished in 47.621947144s
2016/05/25 06:28:42 e2e.go:114: Error starting e2e cluster. Aborting.
```

**Comment by bprashanth** [comment] 2016-05-25 18:45
@k8s-oncall @kubernetes/goog-testing

**Comment by jingxu97** [comment] 2016-05-25 19:53
Two of my recent tests failed because of this issue. Is this a infrastructure issue?

**Comment by ixdy** [comment] 2016-05-25 20:03
dupe of #26270, now fixed.

**Closed by ixdy** 2016-05-25 20:03 UTC
Labels: kind/flake, team/test-infra
