### ISSUE TITLE
kubectl delete should use PropagationPolicy instead of OrphanDependents

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#61587] opened 2018-03-23 08:50 UTC
DeleteOptions.OrphanDependents has been deprecated, instead should use PropagationPolicy

/sig cli

**Comment by liggitt** [comment] 2018-03-23 16:11
duplicate of https://github.com/kubernetes/kubernetes/issues/59850?

**Closed** 2018-03-24 01:24 UTC
Labels: sig/cli
