### ISSUE TITLE
ReadConfigData test fails when tethered on t-mobile

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#12762] opened 2015-08-15 02:48 UTC
Apparently t-mobile redirects bad urls requests to their search homepage. This rather humorously causes the k8s unit tests to fail. TestReadConfigData expects an HTTP GET of `http://some.non.existent.foobar` to error, and it doesn't.

```
--- FAIL: TestReadConfigData (0.47s)
	helpers_test.go:262: unexpected non-error for http://some.non.existent.foobar
FAIL
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/util	0.486s
```

The following pre-existing TODO would solve both problems:

```
// TODO: test TLS here, requires making it possible to inject the HTTP client.
```

**Comment by cjellick** [comment] 2015-09-24 22:28
Dupe of #7104

**Closed** 2016-02-04 00:37 UTC
Labels: priority/P3, team/test-infra
