### ISSUE TITLE
e2e flake: kubelet should be able to delete 10 pods per node in 1m0s

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23591] opened 2016-03-29 17:22 UTC
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/13951/

I see 30 `cleanup30-0f814d6b-f5cc-11e5-9c1b-42010af01555-0cxyq: {kubelet jenkins-e2e-minion-vmgn} Killing: Killing container with docker id` lines and the RC was deleted, but 1 out of 3 nodes was really sluggish in deleting pods.

The sluggish node is jenkins-e2e-minion-he09 (https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/13951/artifacts/jenkins-e2e-minion-he09/) it has 2 pods at failure time: cleanup30-0f814d6b-f5cc-11e5-9c1b-42010af01555-xhc7o, cleanup30-0f814d6b-f5cc-11e5-9c1b-42010af01555-wjq3c. 

And indeed we do see:
```
I0329 16:35:37.082070    3388 manager.go:1400] Container 
"323684e40aa7d72e775a55b39ea14920141ed54930a8ab162f784e81898f8c03 cleanup30-0f814d6b-
f5cc-11e5-9c1b-42010af01555 e2e-tests-kubelet-quhn4/cleanup30-0f814d6b-f5cc-11e5-9c1b-
42010af01555-wjq3c" exited after 1.053961903s
...
I0329 16:35:56.928017    3388 config.go:269] Setting pods for source api
I0329 16:35:56.932285    3388 manager.go:400] Pod "cleanup30-0f814d6b-f5cc-11e5-9c1b-
42010af01555-wjq3c_e2e-tests-kubelet-quhn4(0fe4b997-f5cc-11e5-9d29-42010af00002)" fully 
terminated and removed from etcd
```

which is in time for the test, so maybe /runningpods is retruning stale data?

**Comment by yujuhong** [comment] 2016-03-29 18:39
> which is in time for the test, so maybe /runningpods is retruning stale data?

/runningpods can return slightly outdated data, but kubelet was cutting it close anyway. I think one issue is that pleg serially gets status for every pod, where at least one container has encountered a state transition. This becomes the bottleneck if a lot of containers changed in one relist period. We were aware of this problem and had come up with a few options before:
 1. Add a new GetPodStatus variant to bypass the `docker ps -a` call since pleg already have this information. The downside is that this is a very docker-specific optimization and doesn't make sense for other runtimes.  
 2. Parallelize the process.  
 3. Do nothing. Assume docker is busy and process slowly.

I think we can do (2) with a small number of goroutines (e.g., 2) to speed up the time.

**Comment by yujuhong** [comment] 2016-04-12 17:30
Mark this p2 since this doesn't happen often.

**Comment by yujuhong** [comment] 2016-05-10 00:33
The failure in #23752 is not related to the original issue, and was caused by kubelet hanging (potentially due to docker)
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23752/kubernetes-pull-build-test-e2e-gce/38775/

**Comment by dchen1107** [comment] 2016-05-27 01:28
I am closing this one since we haven't run into the same issue for a long time.

**Comment by piosz** [comment] 2016-05-31 08:58
The test failed in http://pr-test.k8s.io/26073/kubernetes-pull-build-test-e2e-gce/42616/build-log.txt

**Comment by yujuhong** [comment] 2016-05-31 17:19
https://console.cloud.google.com/storage/kubernetes-jenkins/pr-logs/pull/26073/kubernetes-pull-build-test-e2e-gce/42616/

Apiserver received the request to delete the pod at 08:16:53, but kubelet only saw this update at 08:18:31.
apiserver:
```
I0531 08:16:53.503224       8 handlers.go:165] DELETE /api/v1/namespaces/e2e-tests-kubelet-qx8wf/pods/: (78.115879ms) 200 [[kube-controller-manager/v1.3.0 (linux/amd64) kubernetes/3be3350/replication-controller] 127.0.0.1:33212]
```
kubelet:
```
I0531 08:18:31.117976    3521 kubelet.go:2611] SyncLoop (UPDATE, "api"): "cleanup60-f51575bd-2707-11e6-b934-42010af00003-nx3ho_e2e-tests-kubelet-qx8wf(f5aff5a9-2707-11e6-9d22-42010af00002)"
```

To know why kubelet didn't process the deletion requests until much later, I checked the kubelet log during that window. 
```
I0531 08:16:44.757725    3521 kubelet.go:2662] SyncLoop (housekeeping)
I0531 08:16:45.117498    3521 kubelet.go:2096] Orphaned volume "e94f76ed-2707-11e6-9d22-42010af00002/pvc-e5b2b27d-2707-11e6-9d22-42010af00002" found, tearing down volume
I0531 08:18:18.506583    3521 kubelet.go:2096] Orphaned volume "e94f76ed-2707-11e6-9d22-42010af00002/default-token-5paa3" found, tearing down volume
I0531 08:18:18.507900    3521 secret.go:236] Tearing down volume default-token-5paa3 for pod e94f76ed-2707-11e6-9d22-42010af00002 at /var/lib/kubelet/pods/e94f76ed-2707-11e6-9d22-42010af00002/volumes/kubernetes.io~secret/default-token-5paa3
I0531 08:18:18.526860    3521 kubelet.go:2020] Orphaned pod "e94f76ed-2707-11e6-9d22-42010af00002" found, removing
I0531 08:18:18.527295    3521 kubelet.go:2639] SyncLoop (SYNC): 19 pods; cleanup60-f51575bd-2707-11e6-b934-42010af00003-xc5uv_e2e-tests-kubelet-qx8wf(f535854e-2707-11e6-9d22-42010af00002), scale-down-htcg6_e2e-tests-job-wocdl(e97f2efe-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-j26dj_e2e-tests-kubelet-qx8wf(f533d83a-2707-11e6-9d
22-42010af00002), kube-proxy-e2e-gce-agent-pr-1-1-minion-group-acw6_kube-system(019882e7932859faf42e103cbc6bfa60), cleanup60-f51575bd-2707-11e6-b934-42010af00003-g746o_e2e-tests-kubelet-qx8wf(f532c04b-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-yv6u5_e2e-tests-kubelet-qx8wf(f5dc62cc-2707-11e6-9d22-42010af00002), cleanup60-f51575
bd-2707-11e6-b934-42010af00003-cwpfm_e2e-tests-kubelet-qx8wf(f5f36830-2707-11e6-9d22-42010af00002), pod-f7effd9d-2707-11e6-b9b6-42010af00003_e2e-tests-emptydir-95fmn(f7f8eb3b-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-5q7jr_e2e-tests-kubelet-qx8wf(f5326653-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af0
0003-apbn9_e2e-tests-kubelet-qx8wf(f53517b9-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-nx3ho_e2e-tests-kubelet-qx8wf(f5aff5a9-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-ja7fv_e2e-tests-kubelet-qx8wf(f5c7fd0c-2707-11e6-9d22-42010af00002), scale-up-ft8cq_e2e-tests-v1job-k1bpn(fb58c41b-2707-11e6-9
d22-42010af00002), scale-down-933qx_e2e-tests-job-wocdl(e97eee82-2707-11e6-9d22-42010af00002), proxy-service-6e4qk-splvx_e2e-tests-proxy-503q5(eb3f0df3-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-uo9ln_e2e-tests-kubelet-qx8wf(f52868d1-2707-11e6-9d22-42010af00002), cleanup60-f51575bd-2707-11e6-b934-42010af00003-5w2yw_e2e-tests-ku
belet-qx8wf(f5369db0-2707-11e6-9d22-42010af00002), nettest-qo9zk_e2e-tests-nettest-4z1y9(f6c1817a-2707-11e6-9d22-42010af00002), fluentd-elasticsearch-e2e-gce-agent-pr-1-1-minion-group-acw6_kube-system(781a0aa9da59c1d011e85a772ac0bf6b)
I0531 08:18:18.527451    3521 kubelet.go:2662] SyncLoop (housekeeping)
```
Kubelet appeared to be busy tearing down the volume `e94f76ed-2707-11e6-9d22-42010af00002/pvc-e5b2b27d-2707-11e6-9d22-42010af00002`, which took over 90s to complete.


In the meantime, there were errors trying to attach to the same PD.
```
I0531 08:16:44.010861    3521 attacher.go:131] Successfully found attached GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002".
I0531 08:16:44.464703    3521 gce_pd.go:222] PersistentDisk set up: /var/lib/kubelet/pods/e94f76ed-2707-11e6-9d22-42010af00002/volumes/kubernetes.io~gce-pd/pvc-e5b2b27d-2707-11e6-9d22-42010af00002 false stat /var/lib/kubelet/pods/e94f76ed-2707-11e6-9d22-42010af00002/volumes/kubernetes.io~gce-pd/pvc-e5b2b27d-2707-11e6-9d22-42010af00002: no such file or directory
I0531 08:16:45.117498    3521 kubelet.go:2096] Orphaned volume "e94f76ed-2707-11e6-9d22-42010af00002/pvc-e5b2b27d-2707-11e6-9d22-42010af00002" found, tearing down volume
E0531 08:16:47.767080    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:16:47.767137    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:16:52.767247    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=1).
E0531 08:16:56.502616    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:16:56.502690    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:01.502965    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=2).
E0531 08:17:05.392604    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:05.392712    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:10.392900    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=3).
E0531 08:17:14.141776    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:14.141880    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:19.142142    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=4).
E0531 08:17:22.825415    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:22.825536    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:27.825758    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=5).
E0531 08:17:31.686655    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:31.686744    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:36.686990    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=6).
E0531 08:17:40.505129    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:40.505211    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:45.505363    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=7).
E0531 08:17:49.291478    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:49.291560    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:17:54.291786    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=8).
E0531 08:17:58.104475    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:17:58.104580    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
W0531 08:18:03.104833    3521 attacher.go:86] Retrying attach for GCE PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002" (retry count=9).
E0531 08:18:06.858204    3521 gce.go:431] GCE operation failed: googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:18:06.858310    3521 attacher.go:90] Error attaching PD "e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'
E0531 08:18:11.858704    3521 kubelet.go:1886] Unable to mount volumes for pod "pvc-volume-tester-8y4z3_e2e-tests-volume-provisioning-1wmb9(f5673ca2-2707-11e6-9d22-42010af00002)": googleapi: Error 400: The disk resource 'e2e-gce-agent-pr-1-1-d-pvc-e5b2b27d-2707-11e6-9d22-42010af00002' is already being used by 'e2e-gce-agent-pr-1-1-minion-group-acw6'; skipping pod
```

/cc @kubernetes/sig-storage

**Comment by yujuhong** [comment] 2016-06-03 20:37
@saad-ali could you find someone to take a look? Thanks!

**Comment by saad-ali** [comment] 2016-06-03 20:47
The `Error attaching PD` should be fixed by https://github.com/kubernetes/kubernetes/pull/26351

There is work pending to change the kubelet volume clean up code to move it into it's own async loop so that id doesn't block the syncLoop when it hits a longer running operation.

**Comment by yujuhong** [comment] 2016-06-03 20:54
> There is work pending to change the kubelet volume clean up code to move it into it's own async loop so that id doesn't block the syncLoop when it hits a longer running operation.

Thanks! Is there an issue to track this work?

**Comment by saad-ali** [comment] 2016-06-03 21:04
Issue https://github.com/kubernetes/kubernetes/issues/21931

**Comment by matchstick** [comment] 2016-06-09 00:16
This test has been green since 5/25.

**Comment by saad-ali** [comment] 2016-06-15 21:58
https://github.com/kubernetes/kubernetes/pull/26801 is merged. It removes unmount logic from the syncPod loop. Closing issue.

**Closed by saad-ali** 2016-06-15 21:58 UTC
Labels: area/storage, kind/flake, priority/P2, team/cluster, team/node
