### ISSUE TITLE
Create dashboard of e2e test results for all cloud providers

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#4871] opened 2015-02-26 21:50 UTC
As was discussed in the cloud provider breakout yesterday, it would be very helpful to have a centralized dashboard which showed test results for the e2e tests on each of the supported cloud providers.

I'm not immediately sure of the best way to aggregate these data, since it will involve multiple separate CI instances, as nobody will run tests for all providers.

One possibility is to use a dummy Jenkins instance which others forward results to, though I'm not sure if this actually achieves what we want, and I'm unsure of the security implications. It's also possible that not everyone will be using Jenkins.

At the very least, we should probably update the cloud provider matrix in docs/getting-started-guides/README.md to link to publicly-available test results for each provider.

I'll work on GCE.
CC folks (copying from @satnam6502's list on a recent PR):
@derekwaynecarr for Vagrant
@doublerr for Rackspace
@justinsb for AWS
@jeffmendoza for Azure
@zmerlynn since he's looked into this as well

May want to include others too (who?). Also need to figure out how to deal with the cloud spec vs. node spec fan-out.

**Comment by roberthbailey** [comment] 2015-02-26 22:01
Dupe of #2234 (but I'll close that one since this issue has more recent context).

**Comment by ixdy** [comment] 2015-02-26 22:06
Oops. I tried searching for existing issues, but GitHub failed me.

Further requirements for each cloud provider test instance is that
a) it should run at least nightly, though more frequent is even better (depending on available resources)
b) it should run against Kubernetes tip - so for example, the GKE test instance probably isn't worth listing here

**Comment by jeffmendoza** [comment] 2015-02-27 16:57
cc @johngossman

**Comment by timothysc** [comment] 2015-08-11 01:15
cc @pmorie

**Closed** 2016-04-20 04:41 UTC
Labels: 0 - Backlog, area/reliability, area/test, priority/P2, team/test-infra

**Comment by ixdy** [comment] 2016-04-20 07:41
Aren't we still trying to do this?
