### ISSUE TITLE
In-Place Update of Pod Resources - resizing of pod may race with other pod updates

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#116826] opened 2023-03-22 00:55 UTC
### What happened?

This is a follow up from: https://github.com/kubernetes/kubernetes/pull/116702#discussion_r1142299413

Update of a Pod for in-place update of Pod Resources feature is constructing the updated pod and may get to the race with other update operations on this Pod. 

/sig node
KEP: https://github.com/kubernetes/enhancements/issues/1287

### What did you expect to happen?

See the linked comment. The issue is not trivial and may require a bigger refactoring of the logic.

### How can we reproduce it (as minimally and precisely as possible)?

no repro available at this moment. Likely resizing Pod around Pod Termination may result in "un-terminating" of the Pod.

### Kubernetes version

<details>
1.27
</details>

### Cloud provider

Any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment] 2023-06-16 03:25
When I tested this feature, I also found something extraordinary happened.

```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-5
spec:
  restartPolicy: Never
  containers:
  - name: qos-demo-ctr-5
    image: docker.m.daocloud.io/library/nginx:1.14.1
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: RestartContainer
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
```

1. In v1.27 with the VPA feature enabled, I set `resizePolicy` to CPU-not-required and memory-restartcontainer. create the pod using the yaml above,
2. Then I roll back the apiserver to v1.26
3. Do a simple update to pod annotation: add a new one
4. Upgrade back to v1.27 with VPA feature gate enabled
5. when I get the pod yaml again, the memory restart policy is set to `NotRequired`

Is this something expected?

**Comment by tallclair** [comment] 2024-10-14 22:57
@pacoxu I think the case you described is just related to dropping the disabled fields. When you update the annotation with the feature disabled, it overwrites the storage without the disabled resize policy field, and when you reenable it it just uses the default.

**Comment by tallclair** [comment] 2024-10-14 22:58
/triage accepted

I think this might be a duplicate of https://github.com/kubernetes/kubernetes/issues/116971, or at least resolved by the same fix, but needs further investigation.

**Comment by tallclair** [comment] 2024-11-04 18:38
Fixed by https://github.com/kubernetes/kubernetes/pull/128269
/close

**Closed by tallclair** 2024-11-04 18:39 UTC
Labels: kind/bug, sig/node, triage/accepted
