### ISSUE TITLE
e2e flake: deployment should delete old replica sets [pods not found]

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#22437] opened 2016-03-03 15:28 UTC
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/31484
https://cloud.google.com/console/storage/kubernetes-jenkins/pr-logs/pull/22233/kubernetes-pull-build-test-e2e-gce/31484/

```
• Failure [55.442 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should delete old replica sets [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:56

  Expected error:
      <*errors.errorString | 0xc20855f400>: {
          s: "error labeling replica sets and pods with pod-template-hash: error in adding template hash label 3943525156 to pods &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods ResourceVersion:1864} Items:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-cleanup-controller-k84p3 GenerateName:test-cleanup-controller- Namespace:e2e-tests-deployment-h7wz3 SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods/test-cleanup-controller-k84p3 UID:f3ac732c-e10f-11e5-86bc-42010af00002 ResourceVersion:1769 Generation:0 CreationTimestamp:2016-03-02 23:17:13 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[name:cleanup-pod pod:nginx] Annotations:map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"e2e-tests-deployment-h7wz3\",\"name\":\"test-cleanup-controller\",\"uid\":\"f304623a-e10f-11e5-86bc-42010af00002\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"645\"}}\n]} Spec:{Volumes:[{Name:default-token-lzpcz VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc20856c650 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil>}}] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-lzpcz ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc20856c680 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:e2e-gce-master-1-minion-ign6 SecurityContext:0xc2085c7940 ImagePullSecrets:[]} Status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-03-02 23:17:46 -0800 PST Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP:10.245.2.8 StartTime:2016-03-02 23:17:13 -0800 PST ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:0xc208572080 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/nginx ImageID:docker://9f4cd86c1aece2a4f468a3c39db6b13016457586f92abbc066dccccf42f63131 ContainerID:docker://29fca520c228db76de0443d26152c257bf96d743a3956277b657ca3b13665971}]}}]}: error in adding template hash label 3943525156 to pod {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-cleanup-controller-k84p3 GenerateName:test-cleanup-controller- Namespace:e2e-tests-deployment-h7wz3 SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods/test-cleanup-controller-k84p3 UID:f3ac732c-e10f-11e5-86bc-42010af00002 ResourceVersion:1769 Generation:0 CreationTimestamp:2016-03-02 23:17:13 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[name:cleanup-pod pod:nginx] Annotations:map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"e2e-tests-deployment-h7wz3\",\"name\":\"test-cleanup-controller\",\"uid\":\"f304623a-e10f-11e5-86bc-42010af00002\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"645\"}}\n]} Spec:{Volumes:[{Name:default-token-lzpcz VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc20856c650 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil>}}] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-lzpcz ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc20856c680 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:e2e-gce-master-1-minion-ign6 SecurityContext:0xc2085c7940 ImagePullSecrets:[]} Status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-03-02 23:17:46 -0800 PST Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP:10.245.2.8 StartTime:2016-03-02 23:17:13 -0800 PST ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:0xc208572080 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/nginx ImageID:docker://9f4cd86c1aece2a4f468a3c39db6b13016457586f92abbc066dccccf42f63131 ContainerID:docker://29fca520c228db76de0443d26152c257bf96d743a3956277b657ca3b13665971}]}}: pods \"test-cleanup-controller-k84p3\" not found",
      }
      error labeling replica sets and pods with pod-template-hash: error in adding template hash label 3943525156 to pods &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods ResourceVersion:1864} Items:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-cleanup-controller-k84p3 GenerateName:test-cleanup-controller- Namespace:e2e-tests-deployment-h7wz3 SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods/test-cleanup-controller-k84p3 UID:f3ac732c-e10f-11e5-86bc-42010af00002 ResourceVersion:1769 Generation:0 CreationTimestamp:2016-03-02 23:17:13 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[name:cleanup-pod pod:nginx] Annotations:map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"e2e-tests-deployment-h7wz3","name":"test-cleanup-controller","uid":"f304623a-e10f-11e5-86bc-42010af00002","apiVersion":"extensions","resourceVersion":"645"}}
      ]} Spec:{Volumes:[{Name:default-token-lzpcz VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc20856c650 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil>}}] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-lzpcz ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc20856c680 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:e2e-gce-master-1-minion-ign6 SecurityContext:0xc2085c7940 ImagePullSecrets:[]} Status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-03-02 23:17:46 -0800 PST Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP:10.245.2.8 StartTime:2016-03-02 23:17:13 -0800 PST ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:0xc208572080 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/nginx ImageID:docker://9f4cd86c1aece2a4f468a3c39db6b13016457586f92abbc066dccccf42f63131 ContainerID:docker://29fca520c228db76de0443d26152c257bf96d743a3956277b657ca3b13665971}]}}]}: error in adding template hash label 3943525156 to pod {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-cleanup-controller-k84p3 GenerateName:test-cleanup-controller- Namespace:e2e-tests-deployment-h7wz3 SelfLink:/api/v1/namespaces/e2e-tests-deployment-h7wz3/pods/test-cleanup-controller-k84p3 UID:f3ac732c-e10f-11e5-86bc-42010af00002 ResourceVersion:1769 Generation:0 CreationTimestamp:2016-03-02 23:17:13 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[name:cleanup-pod pod:nginx] Annotations:map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"e2e-tests-deployment-h7wz3","name":"test-cleanup-controller","uid":"f304623a-e10f-11e5-86bc-42010af00002","apiVersion":"extensions","resourceVersion":"645"}}
      ]} Spec:{Volumes:[{Name:default-token-lzpcz VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc20856c650 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil>}}] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-lzpcz ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc20856c680 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:e2e-gce-master-1-minion-ign6 SecurityContext:0xc2085c7940 ImagePullSecrets:[]} Status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-03-02 23:17:46 -0800 PST Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP:10.245.2.8 StartTime:2016-03-02 23:17:13 -0800 PST ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:0xc208572080 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/nginx ImageID:docker://9f4cd86c1aece2a4f468a3c39db6b13016457586f92abbc066dccccf42f63131 ContainerID:docker://29fca520c228db76de0443d26152c257bf96d743a3956277b657ca3b13665971}]}}: pods "test-cleanup-controller-k84p3" not found
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:435
```

**Comment by lavalamp** [comment] 2016-03-03 17:57
@janetkuo for triage. :)

**Comment by bprashanth** [comment] 2016-03-03 18:09
Apparently we're trying to label a "pods \"test-cleanup-controller-k84p3\" not found"," @nikhiljindal

**Comment by bprashanth** [comment] 2016-03-03 18:09
Ah, I see we have https://github.com/kubernetes/kubernetes/pull/22384

**Comment by bgrant0607** [comment] 2016-03-03 18:42
This is a dupe of #22300

**Comment by janetkuo** [comment] 2016-03-03 22:56
#22384 is merged. The not found failure mode should be gone.

**Comment by bgrant0607** [comment] 2016-03-04 06:07
Closing. We can reopen if not fixed.

**Closed by bgrant0607** 2016-03-04 06:07 UTC
Labels: area/app-config-deployment, kind/flake, priority/P0, team/ux
