### ISSUE TITLE
unit flake: plugin/pkg/scheduler/factory

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19229] opened 2016-01-02 17:58 UTC
```
Data race:

    WARNING: DATA RACE
    Write by goroutine 32:
      sync.raceWrite()
          /tmp/workdir/go/src/sync/race.go:41 +0x2e
      sync.(*WaitGroup).Wait()
          /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
      net/http/httptest.(*Server).Close()
          /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
      k8s.io/kubernetes/plugin/pkg/scheduler/factory.TestCreateFromEmptyConfig()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory_test.go:117 +0x63d
      testing.tRunner()
          /tmp/workdir/go/src/testing/testing.go:456 +0xdc

    Previous read by goroutine 50:
      sync.raceRead()
          /tmp/workdir/go/src/sync/race.go:37 +0x2e
      sync.(*WaitGroup).Add()
          /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
      net/http/httptest.(*waitGroupHandler).ServeHTTP()
          /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
      net/http.serverHandler.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
          /tmp/workdir/go/src/net/http/server.go:1361 +0x117c
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/5471/artifacts/?project=kubernetes-jenkins

**Comment by gmarek** [comment] 2016-01-04 12:11
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/b6614a4cc76fbfd94f6da52543d8afead6e2f2b7/kubernetes-pull-test-unit-integration/7864/build-log.txt

**Comment by gmarek** [comment] 2016-01-04 12:12
cc @davidopp @xiang90 @hongchaodeng

**Comment by fgrzadkowski** [comment] 2016-01-05 09:49
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/324890e267d9e2c58bb6e7663ced30bad5ff046a/kubernetes-pull-test-unit-integration/7878/?debugUI=DEVELOPERS

**Comment by fgrzadkowski** [comment] 2016-01-05 09:49
@davidopp Can you please reassign?

**Comment by piosz** [comment] 2016-01-07 14:20
Yet another fail http://kubekins.dls.corp.google.com/job/kubernetes-test-go/5744/

**Comment by krousey** [comment] 2016-01-07 22:03
This is a known bug in Go. https://github.com/golang/go/issues/12262 as noted in a similar failure we have #19254. Perhaps we should consolidate all occurrences of this into a single issue?

**Comment by davidopp** [comment] 2016-01-08 00:13
Yeah, I'll close this as a dupe of #19254. Thanks, Kris.

**Closed by davidopp** 2016-01-08 00:13 UTC
Labels: area/test, kind/flake, priority/P1, team/control-plane
