### ISSUE TITLE
Ability to expose headless service from kubectl CLI

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#15924] opened 2015-10-20 03:48 UTC
Currently, `kubectl expose` can expose a rc as a service - but it seems like the command line cannot create a headless service.  Proposing an additional flag, such as:

`kubectl expose rc somestuff --headless=true --port=8080`

**Comment by thockin** [comment] 2015-11-03 05:56
I'm fine with this sort of change.  Got spare cycles?

**Comment by saturnism** [comment] 2015-11-04 17:20
I can take a quick stab at it. looks like i'll need to update pkg/kubectl/cmd/expose.go

**Comment by saturnism** [comment] 2015-11-06 12:17
Actually, would it make sense to do.. `kubectl expose ... --type headless` instead?

**Comment by deads2k** [comment] 2015-11-06 13:11
@kubernetes/kubectl This feels more like an edge case than a primary use-case to me.  The command is already a mass of flags, is this common enough for us to add another one?

**Comment by saturnism** [comment] 2015-11-07 11:38
@deads2k i feel primary use-case is subjective to what people are trying to do. headless services are common when running certain class of services/apps that simply don't need a cluster IP.

**Comment by kargakis** [comment] 2015-11-17 11:07
This is a dupe of https://github.com/kubernetes/kubernetes/issues/10294. Let's do  --cluster-ip=None or --type=Headless instead of --headless @saturnism

**Comment by deads2k** [comment] 2015-11-17 12:49
> This is a dupe of #10294. Let's do --cluster-ip=None or --type=Headless instead of --headless @saturnism

In validation, headless isn't mutual exclusive to any type, so I think that `type` is in appropriate.  I could get behind `--cluster-ip=None`

**Comment by smarterclayton** [comment] 2015-11-17 14:29
Hrm - that may be legacy behavior.  Neither node port or load balanced will
work with a clusterIP=none iirc.

On Nov 17, 2015, at 7:50 AM, David Eads <notifications@github.com> wrote:

This is a dupe of #10294
<https://github.com/kubernetes/kubernetes/issues/10294>. Let's do
--cluster-ip=None or --type=Headless instead of --headless @saturnism
<https://github.com/saturnism>

In validation, headless isn't mutual exclusive to any type, so I think that
type is in appropriate. I could get behind --cluster-ip=None

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15924#issuecomment-157362876>
.

**Comment by bgrant0607** [comment] 2016-01-28 07:34
Closing as dupe of #10294

**Closed by bgrant0607** 2016-01-28 07:34 UTC
Labels: component/kubectl, priority/P2, team/ux
