### ISSUE TITLE
controller won't delete load balancer if service is deleted while controller is down

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#21960] opened 2016-02-25 06:13 UTC
To reproduce:

1. create a loadbalancer service
2. stop controller
3. delete the service
4. bring the controller back up

The loadbalancer is still there. Tested on AWS. Suppose it's the same for GCE.

**Comment by bprashanth** [comment] 2016-02-25 06:46
I'm totally willing to believe the scenario you described is happening. To avoid it we should reconcile existing services of type=loadbalancer with the cloud, and viceversa. I think we're lacking the viceversa bit. The tricky part is knowing what we created vs what another kubernetes cluster in the same project might've created.

**Comment by guoshimin** [comment] 2016-02-25 14:24
For AWS, would tagging the ELBs with KubernetesCluster={cluster_name} be
sufficient? Alternatively, can controller store the information about the
LBs it created in etcd?

**Comment by freehan** [comment] 2016-02-26 00:01
+1 for adding tags/description to loadbalancers. It is better to treat cloud provider as source of truth. 

Adding reconciliation would also help cleaning up dangling loadbalancer caused by improper cluster shutdown.

**Comment by bprashanth** [comment] 2016-02-26 14:43
Closing as a dupe of #15203

**Closed by bprashanth** 2016-02-26 14:43 UTC
Labels: priority/P2, team/cluster
