### ISSUE TITLE
Broken links for changelogs in Github Release emails.

### ISSUE THREAD

**Issue by bukowa** [kubernetes/kubernetes#88043] opened 2020-02-11 23:06 UTC
Here are example links for changelog i receive for github release emails

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#v173
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#v11510
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#downloads-for-v11510
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#downloads-for-v1167

**Comment by tanjunchen** [comment] 2020-02-12 02:36
refer to https://github.com/kubernetes/kubernetes/issues/87993

**Comment by justaugustus** [comment] 2020-02-12 03:42
Closing as duplicate of https://github.com/kubernetes/kubernetes/issues/87993.
Please follow the conversation over there.
/assign
/close
/area release-eng

**Closed by justaugustus** 2020-02-12 03:42 UTC
Labels: area/release-eng, kind/bug, sig/release
