### ISSUE TITLE
unit flake: pkg/client/unversioned/portforward is timing out

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19230] opened 2016-01-02 18:01 UTC
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	300.229s

Example failure:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/e41d66f0e207f8d32268b80e8d0d1c227663cc48/kubernetes-pull-test-unit-integration/7816/artifacts/?debugUI=DEVELOPERS

**Comment by ncdc** [comment] 2016-01-04 15:34
@wojtek-t do you know which test was timing out specifically?

**Comment by ncdc** [comment] 2016-01-04 16:51
Pasting the log from 17916:


```
=== RUN   TestGetListener
I0101 21:35:33.696843   12432 portforward.go:213] Forwarding from localhost:12345 -> 12345
I0101 21:35:33.697201   12432 portforward.go:213] Forwarding from 127.0.0.1:12345 -> 12345
I0101 21:35:33.697423   12432 portforward.go:213] Forwarding from [::1]:12345 -> 12345
E0101 21:35:33.697685   12432 portforward.go:202] Unable to create listener: Error listen tcp4 [::1]:12345: non-IPv4 address <nil>
E0101 21:35:33.697873   12432 portforward.go:202] Unable to create listener: Error listen tcp6 127.0.0.1:12345: bind: invalid argument
E0101 21:35:33.698001   12432 portforward.go:202] Unable to create listener: Error listen tcp6: too many colons in address ::1:12345
--- PASS: TestGetListener (0.00s)
    portforward_test.go:193: Asked a tcp4 forward for: localhost:12345, got listener 127.0.0.1:12345, expected: 12345
    portforward_test.go:193: Asked a tcp4 forward for: 127.0.0.1:12345, got listener 127.0.0.1:12345, expected: 12345
    portforward_test.go:193: Asked a tcp6 forward for: [::1]:12345, got listener ::1:12345, expected: 12345
=== RUN   TestForwardPorts
I0101 21:35:33.708779   12432 portforward.go:213] Forwarding from 127.0.0.1:5000 -> 5000
I0101 21:35:33.709130   12432 portforward.go:213] Forwarding from [::1]:5000 -> 5000
panic: test timed out after 5m0s

goroutine 12 [running]:
testing.startAlarm.func1()
    /tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
    /tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive]:
testing.RunTests(0x17f40e0, 0x1e32640, 0x4, 0x4, 0xc8201def01)
    /tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc8200d9ef0, 0x4861bf)
    /tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
    k8s.io/kubernetes/pkg/client/unversioned/portforward/_test/_testmain.go:60 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e537e0)
    /workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/golang/glog.init.1
    /workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ba

goroutine 7 [semacquire]:
sync.runtime_Semacquire(0xc8202050bc)
    /tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8202050b0)
    /tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
net/http/httptest.(*Server).Close(0xc820205080)
    /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x81
k8s.io/kubernetes/pkg/client/unversioned/portforward.TestForwardPorts(0xc8201e02d0)
    /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:360 +0x1230
testing.tRunner(0xc8201e02d0, 0x1e32670)
    /tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
    /tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 24 [chan send]:
k8s.io/kubernetes/pkg/util/httpstream/spdy.(*connection).SetIdleTimeout(0xc82031a180, 0x0)
    /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/connection.go:138 +0x9b
k8s.io/kubernetes/pkg/kubelet/server.ServePortForward(0x7f38e6bec0d0, 0xc8201b4580, 0xc8201aae00, 0x7f38e6bec108, 0xc8202012e0, 0x1598378, 0x3, 0x1599e40, 0x3, 0x0, ...)
    /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:796 +0x4b6
k8s.io/kubernetes/pkg/client/unversioned/portforward.fakePortForwardServer.func1(0x7f38e6bec0d0, 0xc8201b4580, 0xc8201aae00)
    /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:253 +0x265
net/http.HandlerFunc.ServeHTTP(0xc8201dfe00, 0x7f38e6bec0d0, 0xc8201b4580, 0xc8201aae00)
    /tmp/workdir/go/src/net/http/server.go:1422 +0x48
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc820201120, 0x7f38e6bec0d0, 0xc8201b4580, 0xc8201aae00)
    /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xff
net/http.serverHandler.ServeHTTP(0xc820011ec0, 0x7f38e6bec0d0, 0xc8201b4580, 0xc8201aae00)
    /tmp/workdir/go/src/net/http/server.go:1862 +0x207
net/http.(*conn).serve(0xc820316000)
    /tmp/workdir/go/src/net/http/server.go:1361 +0x117d
created by net/http.(*Server).Serve
    /tmp/workdir/go/src/net/http/server.go:1910 +0x465
FAIL    k8s.io/kubernetes/pkg/client/unversioned/portforward    300.274s
```

I believe what's happening here is the client is opening and closing the spdy connection so quickly at times that the spdy server is shutting down its goroutines just as quickly, before our code is able to call `SetIdleTimeout`. And when our code does call that, it hangs because there is nothing reading from the channel that `SetIdleTimeout` is sending to.

**Comment by ncdc** [comment] 2016-01-04 18:56
I believe the correct way to fix this is to fix spdystream. I have opened an issue here: https://github.com/docker/spdystream/issues/63. I have a local fix that appears to work (for a spdystream test, that is). I have yet to reproduce the timeout/panic with `TestForwardPorts` in my VM.

**Comment by gmarek** [comment] 2016-01-11 08:16
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5944

**Comment by ncdc** [comment] 2016-01-13 02:17
Proposed spdystream fix: https://github.com/docker/spdystream/pull/64

**Comment by brendandburns** [comment] 2016-01-22 04:42
I'll take on updating the dependency...

**Closed** 2016-01-26 00:55 UTC
Labels: area/test, kind/flake, priority/P0, team/cluster
