### ISSUE TITLE
The image inspector seems to returns an non-nil error

### ISSUE THREAD

**Issue by fd** [kubernetes/kubernetes#14234] opened 2015-09-19 20:26 UTC
I'm getting the following error on GKE:

    Failed to inspect image "my-image": <nil>

I traced it back to [this code][1]. The problem seems to be that `IsImagePresent` returns a nil-interface not a nil-pointer. nil-interfaces have a nil-value but a non-nil type. nil-pointers are just what you would expect (not an interface can be can alos be a nil-pointer).

  [1]: https://github.com/kubernetes/kubernetes/blob/6f01200188ab0aa6ceef29ab70741a7b6db82b35/pkg/kubelet/container/image_puller.go#L83-L88

**Comment by dchen1107** [comment] 2015-09-22 16:43
cc/ @yifan-gu

**Comment by yifan-gu** [comment] 2015-09-22 19:51
@fd Do you have any idea where does this nil-interface come from? Nothing seems wrong in [go-dockerclient](https://github.com/fsouza/go-dockerclient/blob/master/image.go#L184) I am confused.

**Comment by fd** [comment] 2015-09-28 18:49
@yifan-gu I tracked down the issue. Wercker builds invalid base images. which cause docker to fail.

**Comment by dchen1107** [comment] 2015-09-29 20:25
I closed this one for now.

**Closed by dchen1107** 2015-09-29 20:25 UTC
Labels: kind/support, priority/P1, team/node

**Comment by geoah** [comment] 2015-10-07 15:00
@fd would you be kind enough to provide some more info or a link on the "wercker builds invalide base images" -- currently facing the same issue and wondering if this is a known issue they are working on. Theanks!

**Comment by vially** [comment] 2015-10-30 22:37
I'm having the same issue (also with an image built by wercker) but I can pull and run the image manually using docker without any problems so I'm not sure the problem is in the image itself.

@fd Can you please provide more details about this issue. Thanks!

**Comment by yifan-gu** [comment] 2015-10-30 22:49
@vially Have you tried to inspect the image using the go docker client library? What does that return?

**Comment by fd** [comment] 2015-10-30 22:50
My guess is that wercker builds the image from a tar which might be missing some metadata used by go-dockerclient. 



—
Simon Menke

**Comment by vially** [comment] 2015-10-30 22:51
@yifan-gu I did not try that. In the meantime I've noticed that logging in through ssh into the nodes and manually removing the image `docker rmi image` fixed the issue for me. But obviously, this is only a workaround. I'll post here after I'll inspect the image using the go docker client library.

**Comment by vially** [comment] 2015-10-30 23:08
Update: inspecting the image using the [go docker client library](https://github.com/fsouza/go-dockerclient) works fine.

**Comment by yifan-gu** [comment] 2015-10-30 23:34
@vially Thanks, are you using the master branch? I saw the go docker has made some change to the function.

[the version we used](https://github.com/fsouza/go-dockerclient/blob/76fd6c68cf24c48ee6a2b25def997182a29f940e/image.go#L189)
[current master](https://github.com/fsouza/go-dockerclient/blob/master/image.go#L198)

Can you try the go-docker client commit 76fd6c68cf24c48ee6a2b25def997182a29f940e ? Not sure if the current master got the problem fixed.

**Comment by vially** [comment] 2015-10-30 23:46
I just tried with the go-docker client commit `76fd6c68cf24c48ee6a2b25def997182a29f940e` and it also works without issues.

I'm still investigating this and I'll post here if I find anything else.

**Comment by vially** [comment] 2015-10-31 04:03
I think I've found the problem. I've been experiencing this issue on Google Container Registry which currently runs kubernetes version `1.0.6` and docker version `1.6.2`.

When running `docker inspect` on the wercker image, the `DockerVersion` field is an integer with a value of `1` instead of being a string (missing the double quotes). However, this only seems to happen on version `1.6.2` of docker (which is what's currently running on the Google Container Registry). I've tested inspecting the same image on docker version `1.8.3` and a string value of `"1.5"` is returned.

This causes the go docker client library to [return an error](https://github.com/fsouza/go-dockerclient/blob/2f1ad24900b2777139b5becee93eb63a75b00617/image.go#L188-L191) while inspecting the image. However this error message gets lost because of [a bug](https://github.com/kubernetes/kubernetes/blob/388061f00f0d9e4d641f9ed4971c775e1654579d/pkg/kubelet/dockertools/manager.go#L1485-L1496) in version `1.0.6` of kubernetes (the `err` variable is reused inside the if block causing it to lose the initial value). That's why the printed error message is: `Failed to inspect image "my-image": <nil>`.

**Comment by yifan-gu** [comment] 2015-11-02 19:16
@vially Thank you! Forget to ask about the kubernetes' version :( So I guess this is fixed on the latest version of kubernetes and docker, right?

**Comment by vially** [comment] 2015-11-02 19:36
@yifan-gu I haven't had a chance to test the latest version of kubernetes (I'm only running it on Google Container Engine and they haven't upgraded yet). But since the latest docker of version (`1.8.3`) has no problem inspecting the wercker image then the go docker client library should not return an error either when inspecting it. Also the kubernetes bug seems to be fixed in master.

Therefore I think it's safe to say that this should be fixed in the latest versions of docker and kubernetes (although I still haven't got time to investigate whether the bug was actually a problem in the way wercker builds the base images or in the way docker `1.6.2` is inspecting the image).

**Comment by yifan-gu** [comment] 2015-11-02 19:40
@vially Cool. FYI, the buggy lines you pointed above in kubernetes have been refactored since then, now the image pulling logic is moved to container runtime to share the code, I think the error is not reused anymore:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/image_puller.go#L76-L88

**Comment by vially** [comment] 2015-11-02 20:49
@yifan-gu Yes, the refactored code looks good to me. Thanks for the info!
