### ISSUE TITLE
Allow dynamic change of scheduler's policy configuration

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#41600] opened 2017-02-16 21:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Kubernetes currently supports "multiple schedulers" (users can run their own custom scheduler(s))
(https://kubernetes.io/docs/admin/multiple-schedulers/), but running an entire separate scheduler is heavyweight, especially for common desires like using best-fit instead of the default spreading policy. There is a scheduler configuration file which allows users to selectively enable/disable predicate and priority functions, and to choose the weights of the enabled priority functions. But this file is read from local disk, so it is not flexible enough for run-time changes and may not be easily accessible in hosted solutions.
It would be great if scheduler configuration could be changed dynamically (probably by setting/changing a ConfigMap in an API call).

One possible use case for this feature is to allow automatic change of scheduling policies when certain characteristics of the cluster change. For example, we could automatically switch the scheduling policy from spreading to best-fit when the user enables cluster autoscaler (https://kubernetes.io/docs/admin/cluster-management/#cluster-autoscaling) on an existing cluster.

**Comment by bgrant0607** [comment] 2017-02-17 03:50
@bsalamat This is a dupe of #1627

**Comment by bsalamat** [comment] 2017-02-17 18:25
@bgrant0607 Yes. Thanks for pointing out. This is specifically targeting scheduler's config, but I guess we can mark it a dupe and continue the discussion in #1627.

**Comment by davidopp** [comment] 2017-02-18 21:40
I think it's worth keeping both issues open; this one is specific to scheduler, even if it uses an appoach decided in #1627.

**Comment by bsalamat** [comment] 2017-02-18 23:53
@kubernetes/sig-api-machinery-misc @kubernetes/sig-scheduling-feature-requests

**Comment by timothysc** [comment] 2017-02-20 14:51
In general, I've been wanting a SIGUP reconfig on * kube components.  Our initialization paths are really heavy weight atm, but imho we could probably start with rejigging for either signal-trap or fstat change = reconfig.  I'm old-school, so i'll always prefer an explicit SIGUP.

**Comment by jayunit100** [comment] 2017-02-22 18:41
one way to do this would be 
- to put the config (which iirc is already an API object) in etcd (i think its already maybe there anyway?)
- run a watch on it and dynamically reconfigure by default, so its transparent to the users.
- also it would be generalizable to other components.

**Comment by liggitt** [comment] 2017-02-22 18:44
most components don't have access to etcd

**Comment by jayunit100** [comment] 2017-02-23 14:14
(by etcd i meant apiserver, updated accordingly)

**Comment by bgrant0607** [comment] 2017-03-02 08:01
See also #12245

**Comment by bsalamat** [comment] 2017-03-02 19:41
@bgrant0607 Thanks for the link. This issue targets one of the schedulers command-line config items which is the scheduler's policy config (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/types.go#L111). I changed the title to clarify that this is only about scheduler's policy configuration.

**Comment by davidopp** [comment] 2017-03-14 07:35
ref/ #28842

**Comment by bsalamat** [comment] 2017-03-14 20:24
If you haven't seen this document already, please take a look and leave your comments:
https://docs.google.com/document/d/19AKH6V6ejOeIvyGtIPNvRMR4Yi_X8U3Q1zz2fgTNhvM

You must be a member of one of the two following groups to be able to see and comment:
`kubernetes-dev@googlegroups.com`
`kubernetes-sig-scheduling@googlegroups.com`

**Comment by bsalamat** [comment] 2017-03-15 21:51
@timothysc In the document I alluded to the fact that we can apply the config without restarting, but soft reconfig was not the focus of the document. When implementing the feature, I will evaluate it more to see what it takes to reconfig without restarting. We should defenitely think about reconfig as the next step.

**Comment by davidopp** [comment] 2017-03-20 09:07
I hate to keep expanding the scope of this issue, but one other thing that might be worth considering is to make some kind of decision of how we view the scheduler extender. What I mean is: it was implemented in the very early days of Kubernetes, before we had much processes in place, and the feeling at the time was that we would not encourage people to use it except as a last resort. This is why we never wrote documentation for it. Essentially it was an "alpha feature," even though we never called it that. IIRC the main concern was that it would interfere with scheduling optimizations, and in general would hurt scheduler latency and throughput (of course only when it is being used). But if it is something we now consider a "permanent" and full-fledged part of the default scheduler, then we should at least write documentation for it.

The reason I am mentioning it here is that the scheduler policy config is how you define the extender endpoint(s) and other attributes of the extender. If we decide that it really is "alpha" then we should make sure the config somehow makes that clear. 

Possibly this belongs in a separate issue, but for now maybe just mentioning it here is enough.

**Comment by bsalamat** [comment] 2017-03-23 20:28
As I have mentioned in the above doc, the final decision is to implement approach #2. The main reason for picking this approach is its advantages as explained in the doc.
There are scalability concerns for some components of the system with many instances, e.g., kubelet, if they decide to watch a number of API server objects. Such concerns do not exist for scheduler as we have usually one or at most several schedulers. Schedulers already have watches on many objects. So, adding one more object will not cause a noticeable impact. 

Please let me know if you have any objections.

**Comment by davidopp** [comment] 2017-03-29 22:28
@roberthbailey

**Comment by roberthbailey** [comment] 2017-05-23 21:52
@mikedanese

**Comment by bsalamat** [comment] 2017-09-07 18:12
kind/feature
priority/important-longterm

**Closed** 2018-06-04 19:59 UTC
Labels: lifecycle/rotten, milestone/removed, sig/scheduling

**Comment by Adirio** [comment] 2019-02-04 14:09
What is the state of this?

Was the doccument ever published for the public or just to the two mentioned GoogleGroups?

I'm intereseted in modifying the weights that each priority function has in a dynamic way.

**Comment by Adirio** [comment] 2019-02-05 13:55
> kind/feature
> priority/important-longterm

/kind feature
/priority important-longterm
