### ISSUE TITLE
e2e flake: scalability suite timed out

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#21313] opened 2016-02-16 16:17 UTC
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4642/consoleFull

It seems to be that there is some problem with gathering resource usage/log sizes or metrics.

**Comment by wojtek-t** [comment] 2016-02-16 16:18
@gmarek

**Comment by wojtek-t** [comment] 2016-02-17 08:25
There was another failure like that with additional logs:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4652/consoleFull

It seems that @gmarek knows what is happening.

**Comment by gmarek** [comment] 2016-02-17 10:24
Fix is merged. We need to monitor if it happens again.

**Comment by wojtek-t** [comment] 2016-02-21 09:24
Unfortunately, it seems that it didn't help:

    15:11:59 STEP: Collecting resource usage data
    15:11:59 Feb 20 15:11:59.953: INFO: Closed stop channel.
    16:27:36 Feb 20 16:27:36.934: INFO: Error while trying to SSH to 162.222.177.178:22, skipping probe. Error: error getting signer for provider gce: 'error reading SSH key /var/lib/jenkins/jobs/kubernetes-e2e-gce-scalability/workspace/.ssh/google_compute_engine: 'open /var/lib/jenkins/jobs/kubernetes-e2e-gce-scalability/workspace/.ssh/google_compute_engine: too many open files''

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4740/consoleFull

@gmarek - please take a look

**Comment by wojtek-t** [comment] 2016-02-23 07:15
This just happened again:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4789/consoleFull

I've increased priority of the PR to help with debugging to P0 as well as priority of this issue.

**Comment by wojtek-t** [comment] 2016-02-24 09:21
And one more failure:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4808/consoleFull

**Comment by gmarek** [comment] 2016-02-24 10:06
I hope that #21759 will solve this.

**Comment by gmarek** [comment] 2016-02-25 12:29
#21759 should have fixed this. I'll keep it open for some time to remember to verify if it did. Decreasing priority in the meantime.

**Comment by wojtek-t** [comment] 2016-02-26 07:25
@gmarek - this happened again at night with your extensive logging:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4848/consoleFull

Can you please take a look?

**Comment by gmarek** [comment] 2016-02-26 08:35
I found the problematic Node: e2e-scalability-minion-w5tf
There's a "Probing e2e-scalability-minion-w5tf" log, but the probe never finished.

**Comment by gmarek** [comment] 2016-02-26 09:01
I think we understand the problem now. One of the Nodes (w5tf one) was dead for some reason - it never started:
```
14:56:19 Feb 25 14:56:19.631: INFO: 206 / 208 pods in namespace 'kube-system' are running and ready (478 seconds elapsed)
14:56:19 Feb 25 14:56:19.631: INFO: expected 8 pod replicas in namespace 'kube-system', 8 are Running and Ready.
14:56:19 Feb 25 14:56:19.631: INFO: POD                                                NODE                         PHASE    GRACE  CONDITIONS
14:56:19 Feb 25 14:56:19.631: INFO: fluentd-elasticsearch-e2e-scalability-minion-w5tf  e2e-scalability-minion-w5tf  Pending  30s    [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-25 14:45:27 -0800 PST ContainersNotReady containers with unready status: [fluentd-elasticsearch]}]
14:56:19 Feb 25 14:56:19.631: INFO: kube-proxy-e2e-scalability-minion-w5tf             e2e-scalability-minion-w5tf  Pending  30s    [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-25 14:45:27 -0800 PST ContainersNotReady containers with unready status: [kube-proxy]}]
14:56:19 Feb 25 14:56:19.631: INFO: 
14:56:21 Feb 25 14:56:21.576: INFO: 206 / 206 pods in namespace 'kube-system' are running and ready (480 seconds elapsed)
14:56:21 Feb 25 14:56:21.576: INFO: expected 8 pod replicas in namespace 'kube-system', 8 are Running and Ready.
```
After 480 seconds NodeController decided that the Node is dead and marked is as NotReady, which allowed the test to proceed (working as intended, probably - @davidopp, @quinton-hoole). Sadly when we try to proxy to this dead node the call hangs because, as far as we can tell, proxy requests do not have any timeout. One workaround would be to modify the grabber in such a way that it waits only for number of Nodes that are ready at the end of the test, which is hacky, but should help. Other, better one, would be to add a timeout handling to the Proxy request (@lavalamp, @dchen1107).

The important finding is that, this problem is not a cause of test failures - those tests would fail anyway, because not all Nodes would be ready after it finishes.

**Comment by davidopp** [comment] 2016-02-26 10:06
Nice debugging!

> After 480 seconds NodeController decided that the Node is dead and marked is as NotReady, which allowed the test to proceed (working as intended, probably 

What blocks the test until the node is marked NotReady? I looked at load.go and saw this

```
		ns = framework.Namespace.Name
		nodes := ListSchedulableNodesOrDie(c)
		nodeCount = len(nodes.Items)
		Expect(nodeCount).NotTo(BeZero())
```

but it wasn't clear to me how that would result tin the behavior that the test blocks until node is marked as NotReady. Are you referring to some other code? Also you mentioned a proxy request, but I didn't see anything like that in load.go. I must be looking at the wrong thing?

**Comment by wojtek-t** [comment] 2016-02-26 11:08
Yes - we are basically talking about density.go here.

But the problem is basically not in the test but in the framework. Framework is waiting until all system pods are running and we have some per-node pods (influxdb). So once a node becomes unready, we are no longer waiting for the corresponding influxdb.

**Comment by gmarek** [comment] 2016-02-26 12:37
I tried to reproduce this problem but failed. I did the following:
- stopped Docker (changed supervisord config before that so it won't restart)
- stopped Kubelet (changed supervisord config before that so it won't restart)
- stopped VM

In all those cases probe exited successfully, so it seems that there's something fun happening between client API server and a kubelet, which causes proxy call to hang indefinitely. @dchen1107 @lavalamp

**Comment by wojtek-t** [comment] 2016-02-27 18:18
@gmarek - it seems that what you did helped to solve this problem.
However - there is one more from exactly the same category of failures:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4887/console

Can you please take a look?

**Closed** 2016-02-29 11:29 UTC
Labels: area/test, kind/flake, priority/P0, team/control-plane
