### ISSUE TITLE
integration flake: TestCascadingDeletion

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#25897] opened 2016-05-19 19:03 UTC
```
=== RUN   TestCascadingDeletion
--- FAIL: TestCascadingDeletion (130.15s)
	garbage_collector_test.go:211: timed out waiting for the condition
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25604/kubernetes-pull-test-unit-integration/26726/artifacts/

**Comment by janetkuo** [comment] 2016-05-19 19:38
cc @caesarxuchao

**Comment by ncdc** [comment] 2016-05-19 21:20
Dupe of #25890?

**Comment by ncdc** [comment] 2016-05-20 12:56
Closing as a dupe. Feel free to reopen if I'm incorrect.

**Closed by ncdc** 2016-05-20 12:56 UTC
Labels: kind/flake
