### ISSUE TITLE
kubectl create/replace should support templates

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#14039] opened 2015-09-16 13:24 UTC
When running `kubectl create`, I often find myself making a few trivial substitutions to the input manifest.  For an rc, I will normally add a label with the git sha, and change the docker image label.  Right now this is awkward; I typically do it through messy bash/sed.  I think it would be very helpful if `kubectl create` was able to perform this substitution.

(This is perhaps part feature-request, part "what is the right way to do this?"  I am not sure whether this belongs in kubectl.)

One way this could work would be to use our existing template syntax, with the input source being a set of variables that are specified on the command line.  I suggest it would be an error if the value was not provided (although it would also be nice to allow `{{gitsha | 'latest' }}`).

e.g.

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: myapp
    gitsha: {{gitsha}}
  name: sentry
spec:
  ...
        image: myregistry/mycoolapp:{{gitsha}}
```

then used with something like `kubectl create -vgitsha=12345 -f template.yaml`

One option might be to prototype this in contrib, as a totally separate command e.g.
 `kube-expand -vgitsha=12345 -f template.yaml | kubectl create -f -`

**Comment by DirectXMan12** [comment] 2015-09-16 17:23
Related to #10495

**Comment by bgrant0607** [comment] 2015-09-17 16:52
Dupe of #11492

**Comment by bgrant0607** [comment] 2016-02-08 22:07
Discussed extensively in SIG Config in December and January meetings:
https://groups.google.com/forum/#!forum/kubernetes-sig-config

And in #18215 

Closing as a dupe of #11492.

**Closed by bgrant0607** 2016-02-08 22:07 UTC
Labels: area/app-config-deployment, component/kubectl, priority/P1, team/ux
