### ISSUE TITLE
Federated ingress creates flapping backends and health checks

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes#36327] opened 2016-11-06 23:37 UTC
Similar to #34291 and possibly related to a problem described in #29341.

I have a federation with three clusters (us, asia, europe).  In it I have created a federated Ingress which refers to a federated Service:

Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buttonmasher-frontend
spec:
  backend:
    serviceName: buttonmasher-frontend
    servicePort: 80
```

Service:
```
kind: Service
apiVersion: v1
metadata:
  name: buttonmasher-frontend
  labels:
    app: buttonmasher-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30061
  selector:
    app: buttonmasher-frontend
  type: LoadBalancer
```

The Deployment has a livenessProbe on /:
```
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 1
```

Parts of the L7 LB are constantly being updated, created and removed.  

Over time, the number of instances shown as health in the LoadBalancer page in the Cloud console flaps - it should be 2/2 from all three regions, but there is generally one or two regions that say 0/2.

The project activity page is a hive of activity.
```
23:33
Create backend service
1082022110804@cloudservices.gserviceaccount.com created k8s-be-31488--32faf76db8066d21.
23:33
Update firewall rule
1082022110804@cloudservices.gserviceaccount.com updated k8s-fw-l7--32faf76db8066d21.
23:33
Create HTTP health check
1082022110804@cloudservices.gserviceaccount.com created k8s-be-31488--32faf76db8066d21.
23:33
Create backend service
1082022110804@cloudservices.gserviceaccount.com created k8s-be-31164--32faf76db8066d21.
23:33
Delete HTTP health check
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-30276--32faf76db8066d21.
23:33
Delete backend service
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-30276--32faf76db8066d21.
23:33
Create HTTP health check
1082022110804@cloudservices.gserviceaccount.com created k8s-be-31164--32faf76db8066d21.
23:33
Create backend service
1082022110804@cloudservices.gserviceaccount.com created k8s-be-30276--32faf76db8066d21.
23:33
Delete HTTP health check
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-31488--32faf76db8066d21.
23:33
Update firewall rule
1082022110804@cloudservices.gserviceaccount.com updated k8s-fw-l7--32faf76db8066d21.
23:33
Delete backend service
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-31488--32faf76db8066d21.
23:33
Create HTTP health check
1082022110804@cloudservices.gserviceaccount.com created k8s-be-30276--32faf76db8066d21.
23:32
Delete HTTP health check
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-30276--32faf76db8066d21.
23:32
Delete backend service
1082022110804@cloudservices.gserviceaccount.com deleted k8s-be-30276--32faf76db8066d21.
```

The backend service for the federated ingress seems to continue to exist, but one each for the consitutent regions come and go:
```
$ gcloud compute backend-services list
NAME                            BACKENDS                                                                                                                                                           PROTOCOL
k8s-be-30061--32faf76db8066d21  us-central1-c/instanceGroups/k8s-ig--32faf76db8066d21,europe-west1-c/instanceGroups/k8s-ig--32faf76db8066d21,asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21  HTTP
k8s-be-30276--32faf76db8066d21  asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                               HTTP
k8s-be-31164--32faf76db8066d21  europe-west1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                             HTTP
$ gcloud compute backend-services list
NAME                            BACKENDS                                                                                                                                                           PROTOCOL
k8s-be-30061--32faf76db8066d21  us-central1-c/instanceGroups/k8s-ig--32faf76db8066d21,europe-west1-c/instanceGroups/k8s-ig--32faf76db8066d21,asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21  HTTP
k8s-be-30276--32faf76db8066d21  asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                               HTTP
k8s-be-31164--32faf76db8066d21  europe-west1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                             HTTP
k8s-be-31488--32faf76db8066d21  us-central1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                              HTTP
$ gcloud compute backend-services list
NAME                            BACKENDS                                                                                                                                                           PROTOCOL
k8s-be-30061--32faf76db8066d21  us-central1-c/instanceGroups/k8s-ig--32faf76db8066d21,europe-west1-c/instanceGroups/k8s-ig--32faf76db8066d21,asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21  HTTP
k8s-be-30276--32faf76db8066d21  asia-east1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                               HTTP
k8s-be-31488--32faf76db8066d21  us-central1-c/instanceGroups/k8s-ig--32faf76db8066d21                                                                                                              HTTP
```

Similarly:
```
$ gcloud compute http-health-checks list
NAME                            HOST  PORT   REQUEST_PATH
k8s-be-30061--32faf76db8066d21        30061  /
k8s-be-30276--32faf76db8066d21        30276  /healthz
k8s-be-31164--32faf76db8066d21        31164  /healthz
k8s-be-31488--32faf76db8066d21        31488  /healthz
$ gcloud compute http-health-checks list
NAME                            HOST  PORT   REQUEST_PATH
k8s-be-30061--32faf76db8066d21        30061  /
k8s-be-30276--32faf76db8066d21        30276  /healthz
k8s-be-31488--32faf76db8066d21        31488  /healthz
```
The health check path is /healthz, which I think is the Kubernetes default, if nothing is specified?

**Comment by davidopp** [comment] 2016-11-07 04:57
@madhusudancs

**Comment by madhusudancs** [comment] 2016-11-07 08:09
@craigbox did you have other Ingress objects in the underlying clusters before creating federated Ingress?

Also, are these GKE clusters? Or GCE ones?

cc @bprashanth

**Comment by craigbox** [comment] 2016-11-07 10:05
They're GKE clusters, they're in the 'kube-pw' project and you're welcome to view them.

I didn't have any Ingress objects - in all testing I removed both the federated and all 3 cluster Ingresses, in which case I have no HTTP backend services/health checks.  I then recreate the federated Ingress and get this state.

I did first create the federated Ingress before I had a defined NodePort on the Service, but it was removed and readded since.

**Comment by quinton-hoole** [comment] 2016-11-07 20:27
Yes, we're aware of this problem.  Unfortunately I've not yet found the root cause.  Presumably the current GCLB Ingress controllers in the clusters are intermittently overwriting each other.  The design precludes this, but there seems to be a bug in the implementation, which I've not yet managed to find.

**Comment by craigbox** [comment] 2016-11-10 14:49
FTR, 30276, 31164 and 31488 are the respective nodePorts allocated to the l7-default-backend in each cluster.

**Comment by saturnism** [comment] 2016-11-11 23:44
i was able to reproduce on my cluster too.

**Comment by saturnism** [comment] 2016-11-12 01:02
i wonder if it has to do w/ `ingress.kubernetes.io/backends` annotation that also has cluster health. would a change in this trigger an update?

**Comment by saturnism** [comment] 2016-11-12 01:03
also, the federated ingress shows a different IP than the actual cluster ingress

**Comment by quinton-hoole** [comment] 2016-11-15 16:42
@craigbox You need to specify a nodeport in the federated service - that way it's consistent across all clusters.  If you don't, the health checks don't work, as they are only able to check a single port.

@saturnism The IP address on the federated ingress and all of the cluster ingresses should be identical.  You need to ensure that no non-federated ingresses exist in the clusters before they join the federation, otherwise they will already have independently created non-matching GCE L7 load balancers.  If that's not in the docs we should add it.

**Comment by quinton-hoole** [comment] 2016-11-15 17:07
@craigbox @saturnism My apologies.  The missing documentation is in https://github.com/kubernetes/kubernetes.github.io/pull/1424 .  I wrote it a while back, but had forgotten that it hasn't merged yet.  I'll fix that now.

**Comment by craigbox** [comment] 2016-11-15 19:13
@quinton-hoole I found that documentation in the end, thanks  The federated service is listed correctly works fine and the node ports are all the same.   The health checks still flap.  There were ingresses (federated or otherwise) created before I found the doc, but they were all deleted before I started.  

The only part where the nodeports aren't the same is the default L7 backend, but my example service shouldn't be touching (or using) that.  If we created a federated ingress on a cluster that had never had any ingresses at all, would you expect all the default backends to have a consistent port?

**Comment by quinton-hoole** [comment] 2016-11-15 21:47
@craigbox That's a good question, and the answer is no, as the default backends are not federated, so would have been created independently, and with different node ports.   One simple way to fix that would be to create a federated service for the default backend, with a specified node port.  The federated service would adopt the underlying cluster services, and ensure that all of their ports are consistent.

**Comment by quinton-hoole** [comment] 2016-11-15 21:52
For what it's worth, I managed to retrieve the logs from a GLBC displaying the problem of flapping health checks.  Still looking at it...


[glbc.log.txt](https://github.com/kubernetes/kubernetes/files/593198/glbc.log.txt)

**Comment by quinton-hoole** [comment] 2016-11-15 22:03
@bprashanth

**Comment by madhusudancs** [comment] 2016-11-15 22:13
@quinton-hoole thanks for the logs!

**Comment by quinton-hoole** [comment] 2016-11-16 00:01
Ignore the logs above.  Here is a better one:


[glbc.log.txt](https://github.com/kubernetes/kubernetes/files/593420/glbc.log.txt)

**Comment by quinton-hoole** [comment] 2016-11-16 00:06
Here are the associated ingress, service and replicaset logs:


[ingress.yaml.txt](https://github.com/kubernetes/kubernetes/files/593424/ingress.yaml.txt)
[nginx.yaml.txt](https://github.com/kubernetes/kubernetes/files/593427/nginx.yaml.txt)
[nginx-rs.yaml.txt](https://github.com/kubernetes/kubernetes/files/593428/nginx-rs.yaml.txt)

**Comment by quinton-hoole** [comment] 2016-11-16 00:10
In this case it looks like we ran out of quota for backend services. I've seen the same symptoms (flapping health checks) on another project that did have sufficient quota.  I will increase the quota on this project to confirm.

**Comment by quinton-hoole** [comment] 2016-11-16 00:13
This looks suspicious:

E1115 23:39:14.917897       5 utils.go:151] Requeuing default/nginx, err Error during sync <nil>, error during GC googleapi: Error 400: The http_health_check resource 'k8s-be-31407--de079c347c3256d9' is already being used by 'k8s-be-31407--de079c347c3256d9', resourceInUseByAnotherResource

**Comment by craigbox** [comment] 2016-11-16 14:10
My project (which you're again welcome to inspect logs for) has a quota of 10 backend services and in theory I should need 1, if not using the default backend, and a maximum of 4 if there's 3 clusters with 1 federated service & 1 default backend each?

**Comment by madhusudancs** [comment] 2016-11-22 20:21
We think we have identified the source of the problem. Filed issue #37306 to describe the problem, describe the workaround required until the problem is fixed and to discuss the proposed fix. 

I am going to document the workaround in the [Federated Ingress doc](http://kubernetes.io/docs/user-guide/federation/federated-ingress/), but also posting it here to make it easier for people who find this issue first:

The workaround is to manually install a firewall rule to expose the targets of all the underlying clusters in a federation for each Federated Ingress object so that the health checks can pass and GCE L7 load balancer is stable. This can be done using the `gcloud` command line tool as follows:

```shell
gcloud compute firewall-rules create <firewall-rule-name> \
  --source-ranges 130.211.0.0/22 --allow [<service-nodeports>]
  --target-tags [<target-tags>]
  --network <network-name>
```

where:
1. `firewall-rule-name` can be any name.
2. `[<service-nodeports>]` is the comma separated list of node ports corresponding to the services that backs the Federated Ingress.
3. [<target-tags>] is the comma separated list of the target tags assigned to the nodes in a kubernetes cluster.
4. <network-name> is the name of the network where the firewall rule must be installed.

Example:
```shell
gcloud compute firewall-rules create my-federated-ingress-firewall-rule \
  --source-ranges 130.211.0.0/22 --allow tcp:30301, tcp:30061, tcp:34564
  --target-tags my-cluster-1-minion, my-cluster-2-minion
  --network default
```

**Comment by craigbox** [comment] 2016-11-23 14:46
That fixed my problem, thanks!

(It's worth noting that you will, of course, also fail the health check if you don't have any pods running in the cluster. My demo deployment started with pods in only one of the three clusters, so I sat confused for a while as to why I still had 0/2 nodes healthy in the other two!)

**Comment by madhusudancs** [comment] 2016-11-23 18:30
Thanks for verifying it @craigbox.

> (It's worth noting that you will, of course, also fail the health check if you don't have any pods running in the cluster. My demo deployment started with pods in only one of the three clusters, so I sat confused for a while as to why I still had 0/2 nodes healthy in the other two!)

I hope it isn't too confusing after this fix and health checks shouldn't flap.

**Comment by vllry** [comment] 2017-04-25 23:39
I am also experiencing this issue, but the firewall workaround mentioned by @madhusudancs does not solve the problem. Health checks and backends are continuing to be swapped out every few seconds, and `kubectl describe ingress <name>` shows a stream of UpdateInCluster notifications.

**Comment by quinton-hoole** [comment] 2017-04-25 23:43
What version of K8s are you running @vllry ?  I believe that the underlying bug in the GLBC is fixed in Kubernetes v1.6.

**Comment by vllry** [comment] 2017-04-25 23:47
I'm using 1.6.1, via GKE.

**Comment by quinton-hoole** [comment] 2017-04-26 03:57
Oh dear.  Here are the relevant bug fixes:

https://github.com/kubernetes/kubernetes/issues/37306
https://github.com/kubernetes/kubernetes/pull/41942
https://github.com/kubernetes/ingress/pull/278

@csbell perhaps you can help @vllry to debug.  I'm OOTO for a few weeks.

**Comment by csbell** [comment] 2017-04-26 04:04
@vllry  Are you sure it's not an initial problem from https://github.com/kubernetes/ingress/pull/251 with a proposed fix in https://github.com/kubernetes/ingress/pull/652 ?
Please provide output from describe cluster if possible.

**Comment by vllry** [comment] 2017-04-26 18:16
I'm not sure if it's the same problem as kubernetes/ingress#251 - backends are being created and deleted like crazy which makes them hard to query. When I check whichever one is set in the load balancer, it's always in rate mode.

`$ kubectl describe cluster
Name:	asia-southeast1-a
Labels:	<none>
ServerAddressByClientCIDRs:
  ClientCIDR	ServerAddress
  ----		----
  0.0.0.0/0 	https://ip1

Conditions:
  Type		Status	LastUpdateTime				LastTransitionTime			Reason		Message
  ----		------	-----------------			------------------			------		-------
  Ready 	True 	Wed, 26 Apr 2017 10:55:19 -0700 	Tue, 25 Apr 2017 13:25:22 -0700 	ClusterReady 	/healthz responded with ok


Name:	europe-west1-b
Labels:	<none>
ServerAddressByClientCIDRs:
  ClientCIDR	ServerAddress
  ----		----
  0.0.0.0/0 	https://ip2

Conditions:
  Type		Status	LastUpdateTime				LastTransitionTime			Reason		Message
  ----		------	-----------------			------------------			------		-------
  Ready 	True 	Wed, 26 Apr 2017 10:55:22 -0700 	Tue, 25 Apr 2017 13:26:23 -0700 	ClusterReady 	/healthz responded with ok


Name:	us-east1-b
Labels:	<none>
ServerAddressByClientCIDRs:
  ClientCIDR	ServerAddress
  ----		----
  0.0.0.0/0 	https://ip3

Conditions:
  Type		Status	LastUpdateTime				LastTransitionTime			Reason		Message
  ----		------	-----------------			------------------			------		-------
  Ready 	True 	Wed, 26 Apr 2017 10:55:22 -0700 	Tue, 25 Apr 2017 13:30:24 -0700 	ClusterReady 	/healthz responded with ok


Name:	us-west1-a
Labels:	<none>
ServerAddressByClientCIDRs:
  ClientCIDR	ServerAddress
  ----		----
  0.0.0.0/0 	https://ip4

Conditions:
  Type		Status	LastUpdateTime				LastTransitionTime			Reason		Message
  ----		------	-----------------			------------------			------		-------
  Ready 	True 	Wed, 26 Apr 2017 10:55:23 -0700 	Tue, 25 Apr 2017 13:30:24 -0700 	ClusterReady 	/healthz responded with ok`

**Comment by vllry** [comment] 2017-04-26 18:33
It *looks* as though each cluster is fighting for control of the 1 ingress/LB, based on the constant rotation of backends and the constant cluster updates.

`Rules:
  Host	Path	Backends
  ----	----	--------
  *	* 	sitebuilder-production:80 (<none>)
Annotations:
  first-cluster:	asia-southeast1-a
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  21h		2m		173	federated-ingress-controller			Normal		FailedClusterUpdate	Ingress update in cluster europe-west1-b failed: Operation cannot be fulfilled on ingresses.extensions "sitebuilder-production-ingress": the object has been modified; please apply your changes to the latest version and try again
  21h		52s		204	federated-ingress-controller			Normal		FailedClusterUpdate	Ingress update in cluster asia-southeast1-a failed: Operation cannot be fulfilled on ingresses.extensions "sitebuilder-production-ingress": the object has been modified; please apply your changes to the latest version and try again
  21h		12s		161	federated-ingress-controller			Normal		FailedClusterUpdate	Ingress update in cluster us-west1-a failed: Operation cannot be fulfilled on ingresses.extensions "sitebuilder-production-ingress": the object has been modified; please apply your changes to the latest version and try again
  21h		12s		209	federated-ingress-controller			Normal		FailedClusterUpdate	Ingress update in cluster us-east1-b failed: Operation cannot be fulfilled on ingresses.extensions "sitebuilder-production-ingress": the object has been modified; please apply your changes to the latest version and try again
  21h		4s		6281	federated-ingress-controller			Normal		UpdateInCluster		Updating ingress in cluster us-east1-b
  21h		4s		6280	federated-ingress-controller			Normal		UpdateInCluster		Updating ingress in cluster asia-southeast1-a
  21h		4s		6287	federated-ingress-controller			Normal		UpdateInCluster		Updating ingress in cluster europe-west1-b
  21h		4s		6284	federated-ingress-controller			Normal		UpdateInCluster		Updating ingress in cluster us-west1-a
`

**Comment by csbell** [comment] 2017-04-26 23:27
Unfortunately, I doubt you'll be able to gather more information that you already have. Can you file a support ticket for your project with GKE?

**Comment by vllry** [comment] 2017-04-26 23:34
Sure, @csbell.

**Comment by vllry** [comment] 2017-04-28 18:52
@nicksardo: it's 1 federated ingress across four clusters.

**Comment by nicksardo** [comment] 2017-04-28 20:08
@vllry In your support ticket, can you ask them to cc @csbell and myself, please.

**Comment by vllry** [comment] 2017-04-28 20:13
Certainly @nicksardo

**Comment by irfanurrehman** [comment] 2017-10-30 18:07
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#79.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close

**Closed by irfanurrehman** 2017-10-30 18:07 UTC
Labels: area/federation, priority/important-soon, sig/multicluster, team/cluster (deprecated - do not use)
