### ISSUE TITLE
delete crd but not stop informer watch/list

### ISSUE THREAD

**Issue by calmkart** [kubernetes/kubernetes#84494] opened 2019-10-29 03:42 UTC
**What happened**:
when i create a crd and delete it, the kubernetes controller logs stderr 
`reflector.go:123] k8s.io/client-go/metadata/metadatainformer/informer.go:89: Failed to list *v1.PartialObjectMetadata: the server could not find the requested resource`
again and again.
If I delete more crd, the stderr will disturb me so I can't see other information.

**What you expected to happen**:
if i delete a crd, the informer watch/list will stop.
controller shouldn't print error.

**How to reproduce it (as minimally and precisely as possible)**:
`test.yaml`
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testits.calmkart.com
spec:
  group: calmkart.com
  version: v1
  names:
    kind: Testit
    plural: testits
  scope: Namespaced
```
`kubectl apply -f test.yaml`
`kubectl delete -f test.yaml`
then, tail the controller logs in namespace kube-system, the stderr print(about 1/s)

**Anything else we need to know?**:
[issue79610](https://github.com/kubernetes/kubernetes/issues/79610) is like this situation, but a little different.
how to solve it?
can i help with it?

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment] 2019-10-29 07:23
>issue79610 is like this situation, but a little different.

this is exactly a duplicate of https://github.com/kubernetes/kubernetes/issues/79610, am i missing anything?

**Comment by liggitt** [comment] 2019-10-29 17:02
yes, duplicate of https://github.com/kubernetes/kubernetes/issues/79610

/close

**Closed by liggitt** 2019-10-29 17:02 UTC
Labels: kind/bug, sig/api-machinery
