### ISSUE TITLE
Apply Jsonnet to simplify configuration

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#28943] opened 2016-07-14 06:59 UTC
Hi all,

Now configuration file should be _json-format_ or _yaml-format_. In my practice, I find that I often need to copy-and-paste some fragments of _JSON_ among some configurations. It's time-consuming and prone to mistake. I think _Jsonnet_ is a cool way to solve it.

Could anyone give me some suggestions? If this is valuable, I'm interested to code it up.
Thanks for insights you can offer.

**Comment by bgrant0607** [comment] 2016-07-20 05:01
Closing as a dupe of #13241

**Closed by bgrant0607** 2016-07-20 05:01 UTC
