### ISSUE TITLE
Collect logs even kube-up.sh failed 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#21722] opened 2016-02-23 00:29 UTC
We run into a lot of issues when kube-up.sh failed, and cluster is not ready. But there is no logs collected from node. For example, http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4784/gcsObjects/ simply exit without any log collections. 

xx/ @spxtr

**Comment by spxtr** [comment] 2016-02-23 00:31
[GCS logs for that run](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4784/)

**Comment by dchen1107** [comment] 2016-02-23 00:32
But the failure indicates several nodes notready, not log collected from those nodes at all.

**Comment by bprashanth** [comment] 2016-02-23 18:30
This is a p0 IMO because it makes several p0s really hard if not impossible to debug (eg: https://github.com/kubernetes/kubernetes/issues/20916)

**Comment by wojtek-t** [comment] 2016-02-25 13:27
+1 - I agree that this is P0 - it makes debugging some issues mostly impossible

**Comment by spxtr** [comment] 2016-02-25 18:16
It seems like we want to run `test/e2e/core.go:CoreDump` before tearing down the cluster, regardless of whether or not we ran tests.

**Comment by spxtr** [comment] 2016-02-26 01:07
This is a dupe of #10423. It's pretty tough to do this, since cluster up happens outside of the e2e framework we just don't get to use the regular logging stuff. Until we've got better support for that the best to do is just freeze the cluster and examine logs manually.

It might be worth considering putting cluster up and down into ginkgo before/aftersuite tests.

**Comment by bprashanth** [comment] 2016-02-26 01:19
> Until we've got better support for that the best to do is just freeze the cluster and examine logs manually.

Is that actually possible? that would be even better than getting logs but I'm not sure how we'll manage quota. 

> This is a dupe of #10423. It's pretty tough to do this, since cluster up happens outside of the e2e framework we just don't get to use the regular logging stuff.

@spxtr if we can't get it through the framework, can we just write a shell script? 

```shell
gcloud compute config-ssh
gcloud compute instances list | grep e2e | while read -ra node; do rsync beeps@$node.us-central1-b.kubernetesdev:/var/log/kubelet.log /tmp/kubelet$node.log; done
```
Or am I misunderstanding?

**Comment by spxtr** [comment] 2016-02-26 01:23
> Is that actually possible? that would be even better than getting logs but I'm not sure how we'll manage quota.
It's a long-term goal to switch test projects from pets to cattle, then if a cluster fails to up we can just remove it from the pool of available clusters and inspect it manually. Until then, you can inspect a failed cluster as long as the next run hasn't started tearing it down yet.

That script will help you with diagnosing current flakes, but we already have `test/e2e/core.go` that does what we want in Go.

**Comment by ixdy** [comment] 2016-02-26 01:25
See https://github.com/kubernetes/kubernetes/issues/10423#issuecomment-189070680 for a suggested plan.

**Comment by bprashanth** [comment] 2016-02-26 01:27
> Until then, you can inspect a failed cluster as long as the next run hasn't started tearing it down yet.

This won't help us. It fails overnight and the next run is too close.
You guys seem to have a plan that will converge in time for us to fix things for 1.2, so ignore my shell script :)

**Comment by wojtek-t** [comment] 2016-02-26 08:13
Similarly - we really need logs if build times out. Since we don't have them, debugging thins like:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/5970/console
is nearly impossible.

**Comment by spxtr** [comment] 2016-02-29 19:57
I'm going to close this as a dupe of #10423.

**Closed by spxtr** 2016-02-29 19:57 UTC
Labels: kind/flake, priority/P0, team/test-infra
