### ISSUE TITLE
client-go: PatchType is not supported for ApplyPatchType in fake

### ISSUE THREAD

**Issue by grishy** [kubernetes/kubernetes#104052] opened 2021-07-31 10:22 UTC
Hi,
When I write a tests:
```go
fakeReadyDeployment := fake.NewSimpleClientset(&appV1.Deployment{
TypeMeta: metav1.TypeMeta{
	Kind:       "Deployment",
	APIVersion: "apps/v1",
},
ObjectMeta: metav1.ObjectMeta{
	Name:            deploymentName,
	Namespace:       "default",
},
}).AppsV1().Deployments("default")
```

After try to apply:
```go
	_, err := fakeReadyDeployment.Apply(context.TODO(), deployment, metav1.ApplyOptions{
		FieldManager: appUID,
	})
```

I get: **PatchType is not supported**

Because we have 4 of const:
**k8s.io/apimachinery@v0.21.0/pkg/types/patch.go:25**
```go
const (
	JSONPatchType           PatchType = "application/json-patch+json"
	MergePatchType          PatchType = "application/merge-patch+json"
	StrategicMergePatchType PatchType = "application/strategic-merge-patch+json"
	ApplyPatchType          PatchType = "application/apply-patch+yaml"
)
```

But in switch only 3 case:
https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L150

Original issue: https://github.com/kubernetes/client-go/issues/970

**Comment by mritunjaysharma394** [comment] 2021-07-31 15:41
I tried to look in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apimachinery/pkg/util/ and found that while [strategicpatch](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch), exists and similarly exists `jsonmergepatch `and `mergepatch`, I guess, when we will try to fix this issue, we will have to add `applypatch` package as well and then use it in the switch-case statement https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L150 ?

**Comment by caesarxuchao** [comment] 2021-08-03 20:19
This seems to be duplicate of https://github.com/kubernetes/kubernetes/issues/103816 and https://github.com/kubernetes/kubernetes/issues/99953.

And there is PR (https://github.com/kubernetes/kubernetes/pull/103821) fixing those two.

/triage accepted

**Closed** 2022-03-19 04:39 UTC
Labels: kind/bug, sig/api-machinery, lifecycle/rotten, triage/accepted
