### ISSUE TITLE
Intermittent error when doing kubectl apply -f for a HorizontalPodAutoscaler: 'unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "scaleTargetRef"'

### ISSUE THREAD

**Issue by bes** [kubernetes/kubernetes#34413] opened 2016-10-09 12:42 UTC
**What keywords did you search in Kubernetes issues before filing this one?**
- unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "scaleTargetRef"
- HorizontalPodAutoscaler
- scaleTargetRef

Also searched google/stackoverflow

---

**Is this a BUG REPORT or FEATURE REQUEST?**
Bug report

**Kubernetes version** (use `kubectl version`):
v1.4.0

**Environment**:
- GKE with kubernetes v1.4.0

**What happened**:
Do `kubectl apply -f my-service.yaml`

Intermittently, since upgrading to 1.4.0 I have been getting

``` shell
error: error when applying patch:

to:
&{0xc8203546c0 0xc8202e3340 default my-service-horizpodautoscaler /my-service/build/k8s/my-service.yaml &HorizontalPodAutoscaler{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:my-service-horizpodautoscaler,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:HorizontalPodAutoscalerSpec{ScaleTargetRef:CrossVersionObjectReference{Kind:Deployment,Name:my-service-frontend,APIVersion:extensions/v1beta1,},MinReplicas:*1,MaxReplicas:3,TargetCPUUtilizationPercentage:nil,},Status:HorizontalPodAutoscalerStatus{ObservedGeneration:nil,LastScaleTime:<nil>,CurrentReplicas:0,DesiredReplicas:0,CurrentCPUUtilizationPercentage:nil,},} &TypeMeta{Kind:,APIVersion:,} 1537793 false}
for: "/my-service/build/k8s/my-service.yaml": error when creating patch with:
original:
{"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"my-service-horizpodautoscaler","creationTimestamp":null},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"my-service-frontend","apiVersion":"extensions/v1beta1"},"minReplicas":1,"maxReplicas":3},"status":{"currentReplicas":0,"desiredReplicas":0}}
modified:
{"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"my-service-horizpodautoscaler","creationTimestamp":null,"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"autoscaling/v1\",\"metadata\":{\"name\":\"my-service-horizpodautoscaler\",\"creationTimestamp\":null},\"spec\":{\"scaleTargetRef\":{\"kind\":\"Deployment\",\"name\":\"my-service-frontend\",\"apiVersion\":\"extensions/v1beta1\"},\"minReplicas\":1,\"maxReplicas\":3},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"my-service-frontend","apiVersion":"extensions/v1beta1"},"minReplicas":1,"maxReplicas":3},"status":{"currentReplicas":0,"desiredReplicas":0}}
current:
{"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"my-service-horizpodautoscaler","namespace":"default","selfLink":"/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/my-service-horizpodautoscaler","uid":"REDACTED-REDA-REDA-REDA-REDACTED","resourceVersion":"1537793","creationTimestamp":"2016-09-28T15:51:27Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"autoscaling/v1\",\"metadata\":{\"name\":\"my-service-horizpodautoscaler\",\"creationTimestamp\":null},\"spec\":{\"scaleTargetRef\":{\"kind\":\"Deployment\",\"name\":\"my-service-frontend\",\"apiVersion\":\"extensions/v1beta1\"},\"minReplicas\":1,\"maxReplicas\":3},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleRef":{"kind":"Deployment","name":"my-service-frontend","apiVersion":"extensions/v1beta1","subresource":"scale"},"minReplicas":1,"maxReplicas":3,"cpuUtilization":{"targetPercentage":80}},"status":{"lastScaleTime":"2016-10-08T23:19:12Z","currentReplicas":1,"desiredReplicas":1,"currentCPUUtilizationPercentage":0}}

for: "/my-service/build/k8s/my-service.yaml": unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "scaleTargetRef"
```

As you can see, it seems that the "current" metadata specifies "apiVersion" as extensions/v1beta1, that might be correct, but it seems suspicious to me...

I have the feeling it works every second time I do apply, but hard to say from my small sample size.

**What you expected to happen**:
The apply to work every time.

**How to reproduce it**

I used this yaml file (cleaned)

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
    tier: frontend
spec:
  type: NodePort
  ports:
  - name: http8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: my-service
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-service-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-service
        tier: frontend
    spec:
      containers:
      - name: my-service
        image: eu.gcr.io/my-project/my-service:v0.0.0
        env:
        - name: MY_ENVIRONMENT
          value: dev
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 800Mi

---
apiVersion: autoscaling/v1 #I've tried with extensions/v1beta1 and "scaleRef" below, but that doesn't work properly either (similar error message)
kind: HorizontalPodAutoscaler
metadata:
  name: my-service-horizpodautoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-service-frontend
    apiVersion: extensions/v1beta1 #I've tried with and without this, makes no difference
  minReplicas: 1
  maxReplicas: 3
```

**Anything else do we need to know**:

GET on clusters using https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters/get reveals:

``` json
[...]
 "addonsConfig": {
  "httpLoadBalancing": {
  },
  "horizontalPodAutoscaling": {
  }
 },
[...]
   "initialNodeCount": 1,
   "autoscaling": {
    "enabled": true,
    "minNodeCount": 1,
    "maxNodeCount": 3
   },
[...]

 "initialClusterVersion": "1.3.6",
 "currentMasterVersion": "1.4.0",
 "currentNodeVersion": "1.4.0",
```

To solve this I have temporarily moved the HPA section out of the file into a separate file, but I prefer having the complete configuration in one place.

Am I doing something wrong?

Thanks!

**Comment by bes** [comment] 2016-10-09 15:00
Tried deleting the hpa using `kubectl delete hpa my-service-horizpodautoscaler` and then reapplying. Worked first time (no errors) and the hpa was created. Waited a few minutes then applied again, and got the same error.

**Comment by pwittrock** [comment] 2016-10-13 22:11
Does this work consistently if the the hpa is in a different file?

**Comment by bes** [comment] 2016-10-14 06:12
@pwittrock No, it's the same thing. Every other time it seems to work.

**Comment by pwittrock** [comment] 2016-10-16 18:10
@ymqytw Would you look into this one as well?

**Comment by ymqytw** [comment] 2016-10-18 16:06
@pwittrock Yeah, I will look into this issue.

**Comment by ajohnstone** [comment] 2016-10-19 11:22
Getting this issue too on 1.4.3

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:20:04Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
11:03:39 INFO:k8s.kubernetes:kubectl --context=test-xxx-xxx.xx-xxx.photobox.com --namespace=development apply -f deploy/kubernetes;
11:03:39 error: error when applying patch:
11:03:39 
11:03:39 to:
11:03:39 &{0xc8200b4e40 0xc82034c460 development smash-website deploy/kubernetes/hpa.yaml &HorizontalPodAutoscaler{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:smash-website,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:HorizontalPodAutoscalerSpec{ScaleTargetRef:CrossVersionObjectReference{Kind:Deployment,Name:smash-website,APIVersion:extensions/v1beta1,},MinReplicas:*1,MaxReplicas:10,TargetCPUUtilizationPercentage:*45,},Status:HorizontalPodAutoscalerStatus{ObservedGeneration:nil,LastScaleTime:<nil>,CurrentReplicas:0,DesiredReplicas:0,CurrentCPUUtilizationPercentage:nil,},} &TypeMeta{Kind:,APIVersion:,} 629103 false}
11:03:39 for: "deploy/kubernetes/hpa.yaml": error when creating patch with:
11:03:39 original:
11:03:39 {"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"smash-website","creationTimestamp":null},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"smash-website","apiVersion":"extensions/v1beta1"},"minReplicas":1,"maxReplicas":10,"targetCPUUtilizationPercentage":45},"status":{"currentReplicas":0,"desiredReplicas":0}}
11:03:39 modified:
11:03:39 {"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"smash-website","creationTimestamp":null,"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"autoscaling/v1\",\"metadata\":{\"name\":\"smash-website\",\"creationTimestamp\":null},\"spec\":{\"scaleTargetRef\":{\"kind\":\"Deployment\",\"name\":\"smash-website\",\"apiVersion\":\"extensions/v1beta1\"},\"minReplicas\":1,\"maxReplicas\":10,\"targetCPUUtilizationPercentage\":45},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"smash-website","apiVersion":"extensions/v1beta1"},"minReplicas":1,"maxReplicas":10,"targetCPUUtilizationPercentage":45},"status":{"currentReplicas":0,"desiredReplicas":0}}
11:03:39 current:
11:03:39 {"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"smash-website","namespace":"development","selfLink":"/apis/autoscaling/v1/namespaces/development/horizontalpodautoscalers/smash-website","uid":"a9e65e5a-9539-11e6-bc5e-0645d95d0de3","resourceVersion":"629103","creationTimestamp":"2016-10-18T13:49:17Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"autoscaling/v1\",\"metadata\":{\"name\":\"smash-website\",\"creationTimestamp\":null},\"spec\":{\"scaleTargetRef\":{\"kind\":\"Deployment\",\"name\":\"smash-website\",\"apiVersion\":\"extensions/v1beta1\"},\"minReplicas\":1,\"maxReplicas\":10,\"targetCPUUtilizationPercentage\":45},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}","kubernetes.io/change-cause":"kubectl --context=test-xxx-xxx.xx-xxx.photobox.com --namespace=development --record=true apply -f deploy/kubernetes"}},"spec":{"scaleRef":{"kind":"Deployment","name":"smash-website","apiVersion":"extensions/v1beta1","subresource":"scale"},"minReplicas":1,"maxReplicas":10,"cpuUtilization":{"targetPercentage":45}},"status":{"currentReplicas":2,"desiredReplicas":0}}
11:03:39 
11:03:39 for: "deploy/kubernetes/hpa.yaml": unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "scaleTargetRef"
11:03:39 ERROR:k8s.kubernetes:stdout output:
11:03:39 deployment "smash-website" configured
11:03:39 service "smash-website-int" configured
11:03:39 service "smash-website" configured
```
yaml
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: smash-website
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: smash-website
  targetCPUUtilizationPercentage: 45
```

**Comment by ymqytw** [comment] 2016-10-19 18:36
I observed the APIVersion is wrong sometimes when using encoder to [encode](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L397) a internal object 
Sometimes it has `"apiVersion":"autoscaling/v1"` which is correct, but sometimes it has `"apiVersion":"extensions/v1beta1"` which is wrong.

I think there is something wrong with the [encoder](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L490) genertaed by codec.
@smarterclayton

**Comment by smarterclayton** [comment] 2016-10-19 21:19
It's possible that we are not forcing the stored version into a stable apiVersion/group, and so when the HPA controller runs it mutates the object via one name (extensions?) and when the user runs it updates via (autoscaling), and so the user action fails.  There is code in the storage codec (storage_factory.go) that should force objects from either type into a single version when stored in etcd.  That's probably the first place to look.  If that's not stable then multiple clients can cause this problem.

**Comment by bgrant0607** [comment] 2016-10-21 23:40
See also #23378, #22866

**Comment by devth** [comment] 2016-10-24 19:02
This busted our CD system for any repos that contain HPA manifests. Details:

- Started happening 10/17 on our GKE cluster.
- The cluster was upgraded to 1.4.0 on 10/4.
- Masters were upgraded to 1.4.3 on 10/16.

**Comment by ymqytw** [comment] 2016-10-24 20:35
I will prioritize this issue.
cc: @caesarxuchao

**Comment by ymqytw** [comment] 2016-10-25 04:50
The root cause is [bestMatch()](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/group_version.go#L291).
This function will return the first one in the slice when there is no best match.
In this case, this function's return value is not deterministic. It depends on the order of the input slice.
Ref: [#34010Comment](https://github.com/kubernetes/kubernetes/pull/34010#pullrequestreview-2764765)
@soltysh Can you give a fix?

**Comment by pwittrock** [comment] 2016-10-25 22:46
@caesarxuchao Is the codec library owned by the api-machinery sig?

**Comment by caesarxuchao** [comment] 2016-10-26 00:29
Yes. This is an api-machinery issue.

**Comment by soltysh** [comment] 2016-10-26 13:54
Lemme try to first reproduce this and I'll see what I can do.

**Comment by soltysh** [comment] 2016-10-27 06:37
It looks like the same problem as in #35149, goes all the way down the exact same method. Working on it now...

**Comment by pwittrock** [comment] 2016-10-27 20:20
Thx

**Comment by pwittrock** [comment] 2016-12-16 00:50
@soltysh any updates on this?

**Comment by matchstick** [comment] 2016-12-16 01:54
@pwittrock Giving this P1 priority and targeting to 1.5 for now. Should this be backported to 1.4?
Also I see #35688 has a possible fix. @soltysh Do you have an ETA? are you waiting on review?

**Comment by pwittrock** [comment] 2016-12-16 21:54
cc @caesarxuchao @lavalamp

**Comment by caesarxuchao** [comment] 2016-12-16 23:44
@liggitt is this issue fixed by your #38406?

**Comment by pwittrock** [comment] 2016-12-19 19:00
It is possible this is already fixed on master/head.  @ymqytw is trying to verify if this is the case now, and create a patch for 1.5 if this is the case.

**Comment by ymqytw** [comment] 2017-01-04 18:46
@munnerz I believe #38982 will be in 1.5.2.
@pwittrock Can you confirm?

**Comment by yunzhu-li** [comment] 2017-01-25 18:38
I'm still hitting this on an 1.5.2 cluster, although much fewer times. Both master and node version are 1.5.2.

**Comment by liggitt** [comment] 2017-01-25 18:40
do you have any pre-1.5.2 kubectl clients performing apply?

**Comment by yunzhu-li** [comment] 2017-01-26 01:07
@liggitt Thanks for reminding! We were running pre-1.5.2 `kubectl` clients and now updated. Will continue monitoring.

**Closed** 2017-01-27 13:41 UTC
Labels: area/kubectl, kind/bug, priority/P1, sig/api-machinery, sig/cli, team/ux (deprecated - do not use)

**Comment by nckturner** [comment] 2017-05-26 08:10
I have this issue with a 1.5.2 cluster with a 1.5.4 client, anyone else seeing it?

**Comment by adambkaplan** [comment] 2017-05-26 19:39
I'm seeing the same/similar issue thing with a 1.5.2 cluster and 1.5.4 client

**Comment by kishorekumark** [comment] 2017-10-11 04:57
seeing the same issue with v1.8.0 
macbook-pro-2:Federation kkokkiligadda$ kubectl --context=fed replace -f Adminconsole-Full.yaml --record --validate=false
service "adminconsole-app" replaced
deployment "adminconsole" replaced
error: unable to recognize "Adminconsole-Full.yaml": no matches for autoscaling/, Kind=HorizontalPodAutoscaler

How to overcome

**Comment by kishorekumark** [comment] 2017-10-11 04:58
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: adminconsole-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: adminconsole-app
    namespace: default
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
----
