### ISSUE TITLE
Doesn't detect failed replication controller

### ISSUE THREAD

**Issue by livelace** [kubernetes/kubernetes#25790] opened 2016-05-18 05:54 UTC
Configuration:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command: ["exit", "1"]
        ports:
        - containerPort: 80
```

[root@kube-controller1 ~]# kubectl get pods
NAME          READY     STATUS             RESTARTS   AGE
nginx-4xf35   0/1       CrashLoopBackOff   5

https://paste.fedoraproject.org/367808/63550656/

[root@kube-controller1 ~]# kubectl get rc
NAME      DESIRED   CURRENT   AGE
nginx     1         1         6m

https://paste.fedoraproject.org/367809/46355072/

https://github.com/openshift/jenkins-plugin/issues/33
https://github.com/openshift/origin/issues/8507

**Comment by kargakis** [comment] 2016-05-18 23:08
cc: @kubernetes/deployment 

There is no notion of a failed replication controller. Deployments in Kube / deploymentconfigs downstream should take care of this. See https://github.com/kubernetes/kubernetes/pull/19343

**Comment by kargakis** [comment] 2016-05-18 23:11
Actually this is a dupe of https://github.com/kubernetes/kubernetes/issues/14519. Can you post in that issue what do you want from a permanently failed deployment to do? I think your issue downstream was that you may end up with a replication controller that has no ready pods and wasn't identified by the deployment?

**Closed by kargakis** 2016-05-18 23:11 UTC
