### ISSUE TITLE
[CRI] Docker shim should persist runtime config options like podCIDR

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#35531] opened 2016-10-25 17:16 UTC
Does the shim need to persist runtime config options so the network plugin can notice changes?    
1. Some runtime options are only needed at startup and not changed thereafter. We handle this today.
2. Some may change at any point. Fails existence proof (?).
3. Some are only available after startup, but won't change

PodCIDR is an example of 3, and I think it might need to get persisted beause network plugins today assume a complete cni.conf. There are 2 ways to get that:     
1. Admin provisions complete CNI.conf in --cni-conf-dir, ignores podCIDR
2. runtime shim constructs valid CNI.conf at runtime

Kubenet for example keeps the cni.conf template in memory and replaces the CIDR using normal string substituation ("subnet: %s:"). When the kubelet retrieves a podCIDR from the node, it sends an event into kubenet. This works because kubenet is compiled in. If the shim is responsible for invoking the plugin, and the shim isn't compiled in, it needs a way to get the cidr. 

@kubernetes/sig-network

**Comment by feiskyer** [comment] 2016-10-26 02:45
cc/ @kubernetes/sig-node

**Comment by bprashanth** [comment] 2016-10-30 23:16
There's already an updateruntimeconfig rpc which I missed when initially filing this bug. The shim should do what it needs to persist that. See second commit in https://github.com/kubernetes/kubernetes/pull/35490

**Comment by yujuhong** [comment] 2016-10-31 18:18
> The shim should do what it needs to persist that.

Isn't this what the issue is about? I don't think dockershim persists the config today.

**Comment by bprashanth** [comment] 2016-10-31 18:28
Yeah it should be possible to feed config options like podcidr through a file down into a network plugin without needing a kube aware wrapper. Got confused.

**Comment by Random-Liu** [comment] 2016-10-31 18:39
There is an issue about checkpoint in dockershim https://github.com/kubernetes/kubernetes/issues/34672

**Comment by freehan** [comment] 2016-12-28 18:12
I thought twice about this. Now I am leaning towards NOT persisting podCIDR.

Kubelet pushes podCIDR config periodically. Dockershim currently only takes the first push and ignores updates. Since this piece of information is stored in memory, as long as dockershim is running, it will not update its podCIDR config. 

If kubelet did not push a new podCIDR, business as usual.

If kubelet did push a new podCIDR and dockershim keeps running, since we do not support podCIDR updates at run time, dockershim should ignore it. 

If kubelet push a new podCIDR and dockershim restarts, I think dockershim should take it. In this case, user may want to refresh the node. Otherwise, dockershim will stick with the first podCIDR it receives until someone comes in and clean it up.

Thoughts?

**Comment by thockin** [comment] 2016-12-28 18:23
This is clearly less than ideal, right?  In an ideal world, we would
recognize that the CIDR changed and react appropriately.  In practice, we
don't expect that to happen (for now), so we can take a shortcut.

Are there other such options that are more immediately important?  In the
medium term, podCIDR should be deprecated or become advisory at best.  What
else?

**Comment by freehan** [comment] 2017-02-10 01:11
merged: https://github.com/kubernetes/kubernetes/pull/39903

Reopen or open another issue if more information needed

**Closed by freehan** 2017-02-10 01:11 UTC
Labels: sig/network, sig/node, team/cluster (deprecated - do not use)
