### ISSUE TITLE
kube-apiserver endpoint cleanup when --apiserver-count>1

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#22609] opened 2016-03-06 05:11 UTC
Using `v1.2.0-beta.0` and running `--apiserver-count=2` in my cluster. I would expect the service endpoint to be cleaned up when one of them goes offline. This doesn't happen though, and causes ~50% of apiserver requests to fail.

**Comment by dchen1107** [comment] 2016-03-08 00:28
I haven't tried to reproduce the issue yet, but I suspect you might hit https://github.com/kubernetes/kubernetes/issues/22625 here. There is a pending pr https://github.com/kubernetes/kubernetes/pull/22626 to resolve #22625. Could you please try to patch your cluster to see if you still have the issue? Thanks!

**Comment by Calpicow** [comment] 2016-03-09 17:45
I don't believe that issue is related. When I down a master, I could see the node and pods being removed. What's not being removed is the second apiserver IP in the kubernetes endpoint.

**Comment by dchen1107** [comment] 2016-03-09 21:40
cc/ @mikedanese @lavalamp they might see the issue before.

**Comment by mikedanese** [comment] 2016-03-09 21:50
This isn't a bug. This is by design but it's likely the design could be better.

**Comment by lavalamp** [comment] 2016-03-10 19:21
Yes, we don't expect an apiserver to go down and stay down without a replacement.

**Comment by lavalamp** [comment] 2016-03-11 00:00
We could make this more robust by having apiservers count themselves, e.g. by each separately making an entry in etcd somewhere.

For now, if you change the number of apiservers that are running, you must change the --apiserver-count= flag by restarting all apiservers.

**Comment by hanikesn** [comment] 2016-04-15 10:03
What happens if one of them crashes/machines goes down? The `kubernetes` service endpoint would not be usable as 50% of the requests would fail.

**Comment by victorgp** [comment] 2016-04-21 12:23
This is actually an important issue that can break the high availability of the whole cluster.
The DNS service relies on the default kubernetes service to connect to the api. If an api server goes down, as hanikesn says, 50% of the requests will fail, hence, the DNS service will fail, therefore, the whole cluster might fail. Is there any plan to change the design of that apiserver-count?

**Comment by javefang** [comment] 2016-07-07 16:24
Agreed with @victorgp , we are creating a high availability cluster, and some services like DNS and Traefik do rely on the default kubernetes endpoint. I can workaround this by forcing them to use the load balancer's URL directly (basically don't use the default endpoint). But I feel like the service endpoint for kubernetes should be consistent with the rest?

**Comment by timothysc** [comment] 2016-07-28 19:28
Does this still exist @ncdc , post recent mod on endpoint update?

**Comment by hanikesn** [comment] 2016-10-15 12:42
This issue still exists with 1.4.1.

**Comment by ncdc** [comment] 2016-10-17 17:47
@timothysc yes, it still exists. We have an endpoint reconciler for the kubernetes service in OpenShift that uses etcd 2's key ttl mechanism to maintain a lease. If an apiserver goes down, one of the remaining members will remove the dead backend IP from the list of endpoints. If we can agree on a mechanism to do this in Kube (there were some concerns about etcd key ttl), I'd be happy to put together a PR.

**Comment by cristifalcas** [comment] 2016-10-18 09:58
:+1:

**Comment by fgrzadkowski** [comment] 2016-10-20 15:21
This problem came up when discussing HA master design. This made me think that maybe there's a better solution. As you say we should be using a TTL for each IP. What we can do is:

1. In the Endpoints object annotations we'd keep a TTL for each IP. Each annotation would keep a pair with an IP, that it corresponds to, and a TTL
2. Each apiserver when updating service kubernetes will do two things:
  1. Add it's own IP if it's not there and add/update TTL for it
  2. Remove all the IPs with too old TTL

This should be a very simple change and hopefully would solve this issue. WDYT?

**Comment by ncdc** [comment] 2016-10-20 15:27
@fgrzadkowski that's essentially what we're doing in OpenShift [here](https://github.com/openshift/origin/blob/b02e73f77d74f7b842a85bb819cb31391eb139d9/pkg/cmd/server/election/lease_endpoint_reconciler.go), although we use a separate path in etcd to store the data, instead of using the existing endpoints path.

**Comment by fgrzadkowski** [comment] 2016-10-20 15:41
Do you think that baking the logic I described above into apiserver [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L281) would make sense? 

@roberthbailey @jszczepkowski @lavalamp @krousey @nikhiljindal

**Comment by fgrzadkowski** [comment] 2016-10-24 14:13
Slight modification after discussion with @thockin and @jszczepkowski.

We believe that a reasonable approach would be to:

1. Add a ConfigMap that would keep the list of active apiservers, with their expiration times; those would be updated by each apiserver separately
2. Change EndpointsReconsiler in apiserver to update Endpoints list to match active apiservers from the ConfigMap.

That way we will have a dynamic configuration and at the same time we will not be updating Endpoints too often, as expiration times will be stored in a dedicated ConfigMap.

**Comment by ncdc** [comment] 2016-10-25 18:12
I assume you'd add retries in the event that 2 apiservers tried to update
the ConfigMap simultaneously?

**Comment by fgrzadkowski** [comment] 2016-10-26 13:04
You mean they would both try and one will fail to resourceversion conflict? Yes, we should retry in such case.

**Comment by bogdando** [comment] 2016-10-28 09:18
@fgrzadkowski :
> Each apiserver when updating service kubernetes will do two things:
> * Add it's own IP if it's not there and add/update TTL for it
> * Remove all the IPs with too old TTL

apiservers could do only the step 1, this would act as the heartbeat. If some is dead, the entry expires and autoremoves, so there is no need to do the step 2. This simplifies design and makes "collisions" impossible. Makes sens?

**Comment by timothysc** [comment] 2016-10-31 16:24
This is starting to overlap with discovery api. 

/cc @kubernetes/sig-cluster-lifecycle

**Comment by dgoodwin** [comment] 2016-10-31 19:16
Yes with regard to a config map containing active API servers, we have something very similar planned for discovery, see #30707.

**Comment by bogdando** [comment] 2016-10-31 19:58
Doesn't discovery cover only initial bootstrap, not dynamic membership changes? Like in etcd, you know.

**Comment by dgoodwin** [comment] 2016-11-01 11:55
We will need it to adjust itself for api server membership changes so it can continue to be used for bootstrapping new nodes as cluster evolves.

**Comment by pires** [comment] 2016-12-20 09:23
@dgoodwin is this going to be part of discovery as planned for 1.6?

**Comment by dgoodwin** [comment] 2016-12-20 13:15
@pires The config map containing active API servers will be coming for 1.6 via #36101, though it can only possibly contain one right now as I don't believe we're targetting HA for that timeframe. (and thus no cleanup)

**Comment by fgrzadkowski** [comment] 2016-12-20 16:02
Can't we have something sooner? This is completely blocking any proper HA setups.

I think @smarterclayton mentioned in https://github.com/kubernetes/kubernetes/pull/36057#issuecomment-259894702 that this will be prioritized to get into 1.6. Has something changed?

**Comment by dgoodwin** [comment] 2016-12-20 16:17
@fgrzadkowski to clarify I think we were talking about a separate related topic out of sig-cluster-lifecycle, this specific issue might be getting fixed in 1.6, I'm not sure.

**Comment by spiffxp** [comment] 2017-06-19 19:42
@kubernetes/sig-api-machinery-misc @kubernetes/sig-cluster-lifecycle-misc I can't figure out which of these two SIG's is more appropriate.  Lifecycle was mentioned above, and solid HA seems like it ought to be a reusable thing from apimachinery.  Please triage as you see fit

**Comment by yifan-gu** [comment] 2017-06-19 23:33
@spiffxp Is anyone actively working on this? If not we would like to take the work. But we may need a shepherd to review the design, doc and code.

My initial idea after reading the thread is that we should remove the `--apiserver-count` flag which won't work when we want to scale up/down the master control plane. Letting the apiserver to register with a key with TTL seems reasonable, but not sure if we have interface for doing such job.

**Comment by liggitt** [comment] 2017-06-19 23:46
I'd like to see an object representing each apiserver, both for status updates for liveness, backing data for populating the kubernetes service endpoints, and for detailed info about versions/features/config

**Comment by smarterclayton** [comment] 2017-06-20 00:45
What about aggregate API servers?  Should they have this object?

**Comment by luxas** [comment] 2017-06-20 09:42
I think this would be a great and necessary feature as Kube grows and starts utilizing HA for real (without an external LB like everybody does today).

@yifan-gu Is it possible that you could join the SIG Cluster Lifecycle meeting today 9am PT? I'd love to talk about this there.

cc @jbeda @timothysc ^

**Comment by aaronlevy** [comment] 2017-06-20 16:00
If @yifan-gu isn't able to make it - I'll be on the call and can discuss

**Comment by aaronlevy** [comment] 2017-06-20 17:27
Briefly discussed in the sig-cluster-lifecycle sync:

Exploring if we could come up with a proposal/implementation as part of a summer internship project. So goal would be to have something within the v1.8 release cycle.

Also @yifan-gu and @abhinavdahiya were planning to join the sig-api-machinery meeting this week to discuss possible direction / proposal. @liggitt does that seem like the right place to start this discussion?

**Comment by rphillips** [comment] 2017-08-03 23:41
There is a proposal from openshift [[1]](https://github.com/openshift/origin/blob/b02e73f77d74f7b842a85bb819cb31391eb139d9/pkg/cmd/server/election/lease_endpoint_reconciler.go) implementing a new registry for endpoints, but directly accesses etcd which we want to avoid. This proposal keeps the logic local to the module.

There was some concern about clock skew, but lots of things (like leader election) are impacted by large skews.

## Proposal

* Create an `EndpointEvictionTimeout` within the config, default: 5 minutes
* Add an annotation for each API server IP that is a lease on the IP:

| key|value|
| ------------- | ------------- |
|endpoints.k8s.io/api-controller/ip/[IP string] | Formatted Time Value | 

* Each iteration of ReconcileEndpoints would loop through Annotations:
  * Compare the timestamp if it is older than the eviction delay
    * IP exists in Addresses
      * Remove the IP from Addresses
      * Remove the Annotation
    * IP does not exist in Addresses
      * Remove the Annotation
* Update the Annotation for the current IP’s timestamp
* If the update fails due to a consistency constraint, read the Endpoint logic again, goto step 1, and attempt the write again, fail after 5 tries

## Example

API Controller IPs: 10.0.3.1, 10.0.3.2

|Key|Value|
|-- | --|
|k8.io/api-controller-ip/10-0-3-1 | 2009-11-10T23:00:00Z|
|k8.io/api-controller-ip/10-0-3-2 | 2009-11-10T23:00:00Z|

## Questions

- Are there technical concerns implementing a fix in this manner?

**Comment by smarterclayton** [comment] 2017-08-04 01:56
Updating endpoints is bad, in that it fans out to the entire cluster every write.  At 5k nodes that is a lot of traffic.  Updating another resource like configmap is less bad.  Least bad would be updating a resource that no one watches globally that is designed for this purpose.

**Comment by liggitt** [comment] 2017-08-04 01:59
5 minutes seems really long... I'd expect an unresponsive master to get its IP pulled out of the kubernetes service endpoints way sooner (more like a 15-30 second response time). The masters contending on a single resource to heartbeat also seems like it could be problematic.

**Comment by szuecs** [comment] 2017-08-08 09:51
We run 2 masters in AWS with an ASG. If we teardown one master it will take about 5-10 minutes to get a replacement, which is fine for all loadbalanced applications.

If you want to have a HA Kubernetes you have to set --apiserver-count=N, where N>1, but this will make sure that the "kubernetes" endpoints will not clean up the teardowned master from above. This is not like normal loadbalancers work and I think it is much worse, then an unavailable control plane!

**Comment by rphillips** [comment] 2017-08-16 16:16
Thank you for the feedback.

## Proposal

Add an `kube-apiserver-endpoints` ConfigMap in the `kube-system` namespace.

Populate the ConfigMap with the following:

```
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: kube-apiserver-endpoints
  namespace: kube-system
data: 
  192.168.0.3:
    update.timestamp=2016-02-18T19:14:38Z
  192.168.0.4:
    update.timestamp=2016-02-18T19:14:38Z
```

In the reconcile endpoints loop, expire the endpoint after a configured period of time (~1 minute?)

/cc @smarterclayton @liggitt

**Closed** 2017-09-23 16:14 UTC
Labels: area/HA, priority/backlog, sig/api-machinery, sig/cluster-lifecycle, team/control-plane (deprecated - do not use)
