### ISSUE TITLE
Unit flake in contrib/mesos/pkg/offers

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#23822] opened 2016-04-04 17:43 UTC
From http://pr-test.k8s.io/23649/kubernetes-pull-test-unit-integration/19981/

```
panic: test timed out after 5m0s

goroutine 3675 [running]:
panic(0x1299dc0, 0xc8201ec8e0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x184
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x18e4520, 0x1f4a000, 0x5, 0x5, 0xc8201ed001)
	/usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc82006df00, 0x0)
	/usr/local/go/src/testing/testing.go:515 +0x11e
main.main()
	k8s.io/kubernetes/contrib/mesos/pkg/offers/_test/_testmain.go:62 +0x211

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1f69c80)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/golang/glog.init.1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ba

goroutine 5 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc82024a040)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82024a030)
	/usr/local/go/src/sync/cond.go:63 +0xb3
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).pop.func1.1(0xc82001a180, 0xc82023e0a0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:349 +0x7a
created by k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).pop.func1
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:350 +0x13e

goroutine 26 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc8200cf7a0)
	/usr/local/go/src/testing/testing.go:441 +0x1e4
k8s.io/kubernetes/contrib/mesos/pkg/offers.TestExpiredOffer(0xc8200cf7a0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers_test.go:31 +0x51
testing.tRunner(0xc8200cf7a0, 0x1f4a000)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 27 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc820093aa0, 0xc8200cf7a0)
	/usr/local/go/src/testing/testing.go:586 +0x6c
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:587 +0xbc5

goroutine 28 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc8200cf830)
	/usr/local/go/src/testing/testing.go:441 +0x1e4
k8s.io/kubernetes/contrib/mesos/pkg/offers.TestTimedOffer(0xc8200cf830)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers_test.go:57 +0x51
testing.tRunner(0xc8200cf830, 0x1f4a018)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 29 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc820093aa0, 0xc8200cf830)
	/usr/local/go/src/testing/testing.go:586 +0x6c
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:587 +0xbc5

goroutine 56 [chan receive, 1 minutes]:
k8s.io/kubernetes/contrib/mesos/pkg/offers.TestListen(0xc82027c3f0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers_test.go:284 +0x56c
testing.tRunner(0xc82027c3f0, 0x1f4a048)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 39 [select, 1 minutes]:
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).pop.func1(0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:351 +0x259
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop(0xc82024a000, 0xc820061bb8, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:146 +0x75
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).pop(0xc82023e0a0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:376 +0xd7
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).Pop(0xc82023e0a0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:332 +0x49
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).nextListener(0xc8202382d0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:444 +0x6e
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).notifyListeners(0xc8202382d0, 0xc820061e90)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:457 +0x4f
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).Init.func2()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:508 +0x84
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until.func1(0xc82023e0c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:115 +0x59
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until(0xc82023e0c0, 0x0, 0xc820236180)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:116 +0x9a
created by k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).Init
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:508 +0x298

goroutine 31 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc8202820b0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8202820a0)
	/usr/local/go/src/sync/cond.go:63 +0xb3
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop.func1(0xc820282070, 0xc8200a01f8)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:161 +0x96
created by k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:163 +0x20d

goroutine 10 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc82024a0b0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82024a0a0)
	/usr/local/go/src/sync/cond.go:63 +0xb3
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop.func1(0xc82024a070, 0xc820050038)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:161 +0x96
created by k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:163 +0x20d

goroutine 57 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc8202820b0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8202820a0)
	/usr/local/go/src/sync/cond.go:63 +0xb3
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).Pop.func1(0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:133 +0xdf
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop(0xc820282070, 0xc820275df8, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:146 +0x75
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).Pop(0xc820282070, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:138 +0x86
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).ageOffers(0xc82027a320)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:429 +0x56
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).(k8s.io/kubernetes/contrib/mesos/pkg/offers.ageOffers)-fm()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:492 +0x2e
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until.func1(0xc82025e260)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:115 +0x59
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until(0xc82025e260, 0x0, 0xc8202604e0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:116 +0x9a
created by k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).Init
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:492 +0xbf

goroutine 58 [select]:
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop(0xc820282000, 0xc820273bb8, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:164 +0x3f0
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).pop(0xc8202622c0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:376 +0xd7
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayFIFO).Pop(0xc8202622c0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:332 +0x49
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).nextListener(0xc82027a320, 0x2)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:444 +0x6e
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).notifyListeners(0xc82027a320, 0xc820273e90)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:457 +0x4f
k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).Init.func2()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:508 +0x84
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until.func1(0xc8202622e0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:115 +0x59
k8s.io/kubernetes/contrib/mesos/pkg/runtime.Until(0xc8202622e0, 0x0, 0xc8202604e0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/runtime/util.go:116 +0x9a
created by k8s.io/kubernetes/contrib/mesos/pkg/offers.(*offerStorage).Init
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/offers/offers.go:508 +0x298

goroutine 3682 [semacquire]:
sync.runtime_Syncsemacquire(0xc820282040)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820282030)
	/usr/local/go/src/sync/cond.go:63 +0xb3
k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop.func1(0xc820282000, 0xc820240738)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:161 +0x96
created by k8s.io/kubernetes/contrib/mesos/pkg/queue.(*DelayQueue).pop
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/contrib/mesos/pkg/queue/delay.go:163 +0x20d
FAIL	k8s.io/kubernetes/contrib/mesos/pkg/offers	300.337s
```

**Comment by jdef** [comment] 2016-04-28 00:28
I think there's a potential race in which a goroutine is cond.Wait()'ing but never sees the cond.Broadcast because of how things get scheduled - and there's no retry if the cond.Broadcast is missed. i'm not able to reproduce this on my machine. i'm hacking on a fix. how reliably can this be reproduced on the k8s test infra?

**Comment by jlowdermilk** [comment] 2016-05-13 17:50
Another hit: [kubernetes-pull-test-unit-integration/25695/](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25537/kubernetes-pull-test-unit-integration/25695/).
No detailed logs, but it looks like this is hitting a 5min timeout:
```
ok  	k8s.io/kubernetes/contrib/mesos/pkg/election	3.303s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/executor	6.538s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/minion/tasks	1.174s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/node	1.354s
FAIL	k8s.io/kubernetes/contrib/mesos/pkg/offers	300.635s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/podutil	1.456s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/proc	2.908s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/queue	4.494s
ok  	k8s.io/kubernetes/contrib/mesos/pkg/redirfd	1.042s
```

**Comment by goltermann** [comment] 2016-06-06 18:19
@jdef do you have reason to think this is still happening?  if not, want to close it?

**Closed** 2016-06-17 10:06 UTC
Labels: area/platform/mesos, kind/flake, kind/mesos-flake, priority/P1, team/mesosphere
