### ISSUE TITLE
pull-kubernetes-unit: k8s.io/kubernetes/pkg/api TestRoundTripTypes is flaking

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes/kubernetes#51270] opened 2017-08-24 14:18 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind flake

**What happened**:
The [`TestRoundTripTypes` test in `pkg/api/serialization_test.go`](https://github.com/kubernetes/kubernetes/blob/73a6ee1dcc20ece22b1bbcdd00d3147984ba70bb/pkg/api/serialization_test.go#L204-L216) is flaking. It flaked before in https://github.com/kubernetes/kubernetes/issues/42651.

Output from a recent failure ([pull-kubernetes-unit for #48988](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51198/pull-kubernetes-unit/48988/)):
```
E0824 14:01:47.277941   12273 event.go:194] Unable to construct event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"", Message:"", Source:v1.EventSource{Component:"", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, LastTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Count:0, Type:""}': 'request construction error: '<nil>'' (will not retry!)
E0824 14:01:47.281233   12273 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"", Message:"", Source:v1.EventSource{Component:"", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, LastTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Count:0, Type:""}': '' (will not retry!)
E0824 14:01:47.281479   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281547   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281619   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281685   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281727   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281764   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281788   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281839   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281876   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281907   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281946   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.281996   12273 event.go:209] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E0824 14:01:47.282033   12273 event.go:144] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"", Message:"", Source:v1.EventSource{Component:"", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, LastTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Count:0, Type:""}' (retry limit exceeded!)
E0824 14:01:47.282328   12273 event.go:209] Unable to write event: 'A weird error' (may retry after sleeping)
E0824 14:01:47.282388   12273 event.go:209] Unable to write event: 'A weird error' (may retry after sleeping)
[...]
E0824 14:01:47.282750   12273 event.go:209] Unable to write event: 'A weird error' (may retry after sleeping)
E0824 14:01:47.282781   12273 event.go:144] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"", Message:"", Source:v1.EventSource{Component:"", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, LastTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, Count:0, Type:""}' (retry limit exceeded!)
E0824 14:01:47.283000   12273 event.go:209] Unable to write event: 'A weird error' (may retry after sleeping)
E0824 14:01:47.285503   12273 event.go:209] Unable to write event: 'fake error' (may retry after sleeping)
E0824 14:01:47.285629   12273 event.go:209] Unable to write event: 'fake error' (may retry after sleeping)

[...]
```

I can reproduce this locally on the latest `master` as well.

**What you expected to happen**:
Test should pass.

**How to reproduce it (as minimally and precisely as possible)**:
```
go test -v k8s.io/kubernetes/pkg/api -run TestRoundTripTypes$
```

**Comment by mattmoyer** [comment] 2017-08-24 14:19
cc @kubernetes/sig-auth-bugs

**Comment by nikhita** [comment] 2017-08-24 15:09
dupe of https://github.com/kubernetes/kubernetes/issues/51260.
fix is in progress here: https://github.com/kubernetes/kubernetes/pull/51258.

**Closed** 2017-08-24 15:12 UTC
Labels: kind/bug, kind/flake, sig/auth
