### ISSUE TITLE
Audit metadata level should include object owner references

### ISSUE THREAD

**Issue by pbarker** [kubernetes/kubernetes#65450] opened 2018-06-25 20:26 UTC
Currently, when audit logging is configured at the `metadata` level only a superset of the object data is being logged in the [objectReference](https://github.com/kubernetes/apiserver/blob/master/pkg/apis/audit/v1beta1/types.go#L263). In order to determine things like attribution (i.e. a deployment deletion caused pod deletion), the object's metadata needs to be examined to trace the cause/effect. That data can currently be found in the `RequestResponse` level in raw json form, but often that level needs to be restricted to not log sensitive data. This leaves an incomplete audit trail around a subset of the api objects. 

An object's metadata is intentionally separated from the object itself and contains relevant information for a complete audit story. Logging at the metadata level seems to already entail this data would be present. This issue proposes adding an `ownerReferences` field to the existing [objectReference](https://github.com/kubernetes/apiserver/blob/master/pkg/apis/audit/v1beta1/types.go#L263) struct.

 /kind feature

**Comment by pbarker** [comment] 2018-06-25 21:44
@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment] 2018-06-25 21:45
Metadata is not necessarily safe to log. For example `kubectl apply` stores full object content in annotations.

**Comment by pbarker** [comment] 2018-06-25 21:49
what about excluding the `annotations` or just scoping it to the `ownerReferences` and `labels`?

**Comment by tallclair** [comment] 2018-06-25 21:58
This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/56586

To [quote myself](https://github.com/kubernetes/kubernetes/issues/56586#issuecomment-358080379) from that issue:

> I'm going to argue against this feature for 2 reasons:
> 1. Annotations can contain arbitrary data, and thus be arbitrarily large. The matadata log-level should not (for performance & storage).
> 2. The metadata log-level does not include any information from the request object, so the object doesn't need to be decoded to log it. This is beneficial for performance, but also lets us log (at metadata) objects that the apiserver doesn't understand (e.g. in the aggregated apiserver case).
> 
> Given the above, I think it's better to add this to the usecases for log filters, and log at the request-level while filtering out the bulk of the request.

**Closed by tallclair** 2018-06-25 21:58 UTC
Labels: kind/feature, sig/auth

**Comment by tallclair** [comment] 2018-06-25 22:00
If you're interested in this topic though, I'm still open to the log filters idea. AFAIK no one has started designing that feature, so a KEP would certainly be welcome.
