### ISSUE TITLE
Provide a place for system components to publish system-wide events.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#35774] opened 2016-10-28 09:15 UTC
We would like to make system components statuses and actions more visible to the end user, especially on environments where master logs access is more complicated. An example of such component is Cluster Autoscaler. Where should we place events like that CA stopped because some of the instance group nodes did not registered properly and CA doesn't want to make the situation worse by adding or deleting new nodes. 

I proposed kube-system namespace as a temporary solution. See https://github.com/kubernetes/contrib/pull/1937.

cc: @erictune @davidopp @fgrzadkowski

**Comment by fgrzadkowski** [comment] 2016-11-02 12:25
@erictune @bgrant0607 Do you have some suggestions how we should use Events (or maybe some other mechanism) to expose cluster level events like cluster autoscaler decisions?

@thockin

**Comment by erictune** [comment] 2016-11-02 20:36
As a user who runs applications, I may not have permission to see the kube-system namespace object or node objects  (cannot do this in OpenShift, and I'd expect the same from other multi-tenant uses of Kubernetes).  

As a user, I typically can see my Pods.  I can see that my pods are Unschedulable.  So, I would expect to be able to see events on my pods telling me that something (e.g. cluster autoscaler) is reacting to that Unschedulable and trying to fix it, as well as if it tried but cannot fix it.

Also, even if I can see the kube-system namespace, or the nodes, I may not know to look there.

I will know to look at my Pods.  UIs show users their pods on the default screens.  

Also, we plan to change all the pod-creating-controllers so that they aggregate event information from the pods they control as new events and/or as status on that controller object.  This will be a very natural place for users to go for information.  (E.g. I list my ReplicaSet and it shows that I have Unschedulable pods and that is why it isn't scaled up yet).

Therefore, I would put the events on the pods.  I would not worry about the number of events that this generates.  The scheduler and kubelet already sends several events for every pod, and one more is not a problem.

I would send resend the event periodically.  The event collapsing mechanism will handle summarizing similar events.

Example of experience I would expect:

```
$ kubectl get pods
NAME                                READY     STATUS          RESTARTS   AGE
nginx-deployment-1006230814-6winp   1/1       Running         0          1h
nginx-deployment-1006230814-fmgu3   1/1       Unschedulable   0          10m
```

I get my pods and see that one is Unschedulable, so I decide to drill down on that pod using kubectl describe.

```
$ kubectl describe pods nginx-deployment-1006230814-fmgu3

$ kubectl describe pod nginx-deployment-1006230814-6winp
Name:		nginx-deployment-1006230814-6winp
Namespace:	default

...

Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----					-------------		--------	------		-------
  55m		22s		1	{default-scheduler }						          Normal	NotScheduled Unable to find suitable node                                                                                                
  45m		14m		1	{cluster-autoscaler}						          Normal    ScalingUp      adding node due to Unschedulable pods
  13m		45s		1	{cluster-autoscaler}						          Normal    ScaleUpFailed	      newly added node kubernetes-node-wul4 taking too long to join cluster.
```

**Comment by mwielgus** [comment] 2016-11-02 20:42
We already have events on the pod level. We will also soon have events for the deleted nodes. The problem is how to pass the information that is not specific to any particular K8S object. Like Cluster autoscaler is stopped because one node is missing (for example, has not registered yet). These events are not needed to be visible to all users but can be very useful to cluster administrator to tell why cluster autoscaler is not working as expected.

**Comment by erictune** [comment] 2016-11-02 20:47
The fact that it is stopped seems relevant to all users and so should be a
pod level event, I think?  The exact reason it is stopped: can that just go
into the logs?

**Comment by mwielgus** [comment] 2016-11-02 20:51
To which pods or nodes? All?
Also we are mainly talking about GKE where master components logs are not so easily available.

**Comment by erictune** [comment] 2016-11-02 20:52
All application logs are typically available from kubectl logs and via a
log aggregation service like ELK or GCL.  I don't see how cluster
autoscaler is different from say kubedns.

**Comment by mwielgus** [comment] 2016-11-02 20:58
Cluster autoscaler runs on a master. If if was running in "userspace" i would just attach all events to the CA pod. But there is no CA pod visible (neither scheduler, apiserver, etc) on GKE.

**Comment by erictune** [comment] 2016-11-02 23:13
Why can't cluster-autoscaler write debugging info to its logs the same as scheduler or apiserver?

**Comment by mwielgus** [comment] 2016-11-03 00:42
It does but can you actually see GKE api master logs as a regular user?

**Comment by davidopp** [comment] 2016-11-03 06:39
I'm with @mwielgus here, I think the logs are not an adequate way to surface information like this to the user (regardless of whether users can see the logs). IMO we shouldn't be asking users to poke through logs to understand why the cluster is behaving the way it is. I admit this is personal preference, not based on some kind of principle.

Part of the problem is that CA doesn't have a corresponding API object (like HPA does) where you could write this information as Status. If CA had an API object (I guess it would go in the kube-system namespace -- would users have permission to see its Status?), we wouldn't have this problem.

**Comment by fgrzadkowski** [comment] 2016-11-03 14:26
@erictune I think there are two use-cases:

1. As a user I'm debugging what's happening with my Pod as it's pending. I want to list all events and see that CA has created a new node and it waits for it register or something else.
2. As a user admin I want to understand why my cluster have 8 nodes instead of 4, or when exactly was the scale up triggered to better understand why my node reappeared.

For 1) we are already creating Events bound to a Pod. That's simple. We are now trying to solve second use-case. Currently we don't have any common pattern how to expose this kind of information for the user/admin.

@mwielgus suggested using `kube-system` namespace. It's not a problem that it would not be visible for "normal users" as we are targeting admins here. They would have access to this namespace.

I'm pretty sure that there are similar problems with some network related issues (@bprashanth , @thockin) that should be reported on cluster level.

**Comment by erictune** [comment] 2016-11-03 20:07
I agree we don't have a common pattern for #2.  Let's not design something the week before the freeze, and let's not do a temporary fix that is hard to undo.

Instead, there is room in the per-pod event "reason" to handle #2 as well.

**Comment by fgrzadkowski** [comment] 2016-11-04 08:35
It doesn't have to be for 1.5, but it's something we should figure out sooner than later. Can you explain how would administrator read all the events from per-pod events? I think UX would be very bad, but I might be missing something.

**Comment by davidopp** [comment] 2016-11-07 03:50
One cluster autoscaler user says "Would be great if I could get the status in something like 'kubectl get
hpa'"

Is there any reason why we shouldn't bite the bullet and do a CA object (which would also hold configuration information)? I know there was concern about complexity of making it work across multiple cloudproviders, but we already have a lot of things that have to work across multiple cloudproviders...

**Comment by fgrzadkowski** [comment] 2016-11-07 09:57
@davidopp I agree it could be a good solution. We were hesitant to start with desining it, but now we now much more. We have a working implementation across GCE, GKE and AWS and a WIP PR with OpenStack. Maybe it's a good time to revisit this? @mwielgus WDYT?

**Comment by fgrzadkowski** [comment] 2017-06-27 07:27
I think this is already possible. Currently we started using `ConfigMap` to report CA status and we plan to migrate to `ComponentStatus`. @mwielgus should we close this one?

**Closed** 2017-06-27 09:21 UTC
Labels: priority/backlog, sig/autoscaling, team/ux (deprecated - do not use)
