### ISSUE TITLE
var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#27973] opened 2016-06-23 21:09 UTC
I brought up on 5 bare metal nodes (Centos 7) 1.2.4 cluster. When I try to start the replication controller, POD fails. It seems /var/run/secrets/kubernetes.io/serviceaccount/token does not exist. I could not find any specific steps for configuring tokens. Default service account does not have much info:
kubectl --server 127.0.0.1:8080 describe  serviceaccounts default
Name:           default
Namespace:      default
Labels:         <none>
Image pull secrets:     <none>
Mountable secrets:      <none>
Tokens:                 <none>

I was wondering if I am missing some steps for the installation of the cluster? Greatly appreciate if somebody could help with this issue.
Thank you

**Comment by Random-Liu** [comment] 2016-06-23 23:45
@sbezverk You need to config admission-control flag on apiserver. Sometihng like `--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,ResourceQuota`.

The document: http://kubernetes.io/docs/admin/admission-controllers/
An related issue: https://github.com/kubernetes/node-problem-detector/issues/21#issuecomment-227930870

**Comment by sbezverk** [comment] 2016-06-24 00:07
Thank you for your replace, I checked command line used to start apiserver and I do see   ServiceAccount.
ExecStart=/usr/bin/hyperkube \
  apiserver \
  --insecure-bind-address=0.0.0.0 \
  --etcd-servers=http://127.0.0.1:2379 \
  --service-cluster-ip-range 10.57.0.0/16 \
  --allow-privileged=true \
  --admission-control=NamespaceLifecycle,NamespaceExists,ServiceAccount,LimitRanger,ResourceQuota

**Comment by sols1** [comment] 2016-06-24 21:13
I also added `--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota` and restarted kube-api but there are still no secrets:

```
kubectl get service account
NAME      SECRETS   AGE
default   0         7d

kubectl describe serviceaccounts default
Name:		default
Namespace:	default
Labels:		<none>

Image pull secrets:	<none>

Mountable secrets: 	<none>

Tokens:            	<none>
```

It does not look like this option enables ServiceAccount plugin

**Comment by erictune** [comment] 2016-06-24 22:18
@sbezverk
that admission controller flag may not have been required when the doc was written, but it is now 😃 
I'm happy to approve a PR that updates the docs.

You should look at the `/var/log/kube-controller-manager.log` and I suspect you will see errors from the token controller.  It may give a clue.
I suspect what is missing is that you don't have the `--service-account-private-key-file=/srv/kubernetes/server.key` flag on your `kube-controller-manager`.

**Comment by erictune** [comment] 2016-06-24 22:20
`kube-controller-manager` uses the same private key as the kube-apiserver's TLS key to sign the JWTs in the service account tokens.  Without this flag, it either doesn't run (in which case there might be no errors in the log, so disregard previous post) or it will rub but be confused.  I forgot which.

**Comment by Random-Liu** [comment] 2016-06-24 22:24
@erictune Thanks a lot!
This also explains the issue in node problem detector https://github.com/kubernetes/node-problem-detector/issues/21

**Comment by sols1** [comment] 2016-06-25 00:40
Actually more options are needed for api server http://kubernetes.io/docs/admin/authentication/

> Using an existing deployment script is implemented at cluster/saltbase/salt/generate-cert/make-ca-cert.sh.
> Execute this script with two parameters. The first is the IP address of apiserver. The second is a list of subject alternate names in the form IP:<ip-address> or DNS:<dns-name>.
> The script will generate three files: ca.crt, server.crt, and server.key.
> Finally, add the following parameters into apiserver start parameters:
> --client-ca-file=/srv/kubernetes/ca.crt
> --tls-cert-file=/srv/kubernetes/server.cert
> --tls-private-key-file=/srv/kubernetes/server.key

CERT_DIR=<path>/cert_dir CERT_GROUP=... ~/kubernetes-1.3/cluster/saltbase/salt/generate-cert/make-ca-cert.sh 192.168.78.16 IP:10.100.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:...

**Comment by tristanz** [comment] 2016-07-06 23:58
Did something change between 1.3.0-alpha4 and 1.3.0?  I don't seem to see to get anything in `/var/run/secrets/kubernetes.io/serviceaccount` either.  I'm running a development hyperkube setup with options:

apiserver: 
```
            "Entrypoint": [
                "/hyperkube",
                "apiserver",
                "--service-cluster-ip-range=10.0.0.1/24",
                "--insecure-bind-address=0.0.0.0",
                "--etcd-servers=http://127.0.0.1:4001",
                "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota",
                "--client-ca-file=/srv/kubernetes/ca.crt",
                "--basic-auth-file=/srv/kubernetes/basic_auth.csv",
                "--min-request-timeout=300",
                "--tls-cert-file=/srv/kubernetes/server.cert",
                "--tls-private-key-file=/srv/kubernetes/server.key",
                "--token-auth-file=/srv/kubernetes/known_tokens.csv",
                "--allow-privileged=true",
                "--v=2"
            ],
```
controller-manager:
```
            "Entrypoint": [
                "/hyperkube",
                "controller-manager",
                "--master=127.0.0.1:8080",
                "--service-account-private-key-file=/srv/kubernetes/server.key",
                "--root-ca-file=/srv/kubernetes/ca.crt",
                "--min-resync-period=3m",
                "--v=2"
            ],
```

**Comment by erictune** [comment] 2016-07-07 00:10
Tons changed.  Not sure what is causing the regression you see.

**Comment by tristanz** [comment] 2016-07-07 21:09
I believe this is a dupe of https://github.com/kubernetes/kubernetes/issues/26943.  The difference is the `rslave` option, although that doesn't seem to work by itself with stock `docker-machine`.

My current workaround is to launch with:
```
docker-machine ssh dev -- "sudo rm -R /var/lib/kubelet || true && sudo mkdir -p /var/lib/kubelet && sudo mount --bind /var/lib/kubelet /var/lib/kubelet && sudo mount --make-shared /var/lib/kubelet"
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw,rslave \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    --name=kubelet \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v${K8S_VERSION} \
        bash -c 'sed -i \
        "s/--insecure-bind-address=127.0.0.1/--insecure-bind-address=0.0.0.0/" \
        /etc/kubernetes/manifests/master.json; \
        /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --address=0.0.0.0 \
        --event-qps=100 \
        --api-servers="http://localhost:8080" \
        --config=/etc/kubernetes/manifests \
        --cluster-domain=cluster.local \
        --allow-privileged=true --v=2'
```

On cluster shutdown I also need to cleanup the mounts with:
```
docker-machine ssh dev -- "sudo umount \$(mount | grep /var/lib/kubelet | awk '{print \$3}')"
docker-machine ssh dev -- "sudo rm -rf /var/lib/kubelet"
````

**Comment by tristanz** [comment] 2016-07-08 20:56
The workaround above creates others problems, where `findmnt` fails and hundreds of mounts are created (https://github.com/kubernetes/kubernetes/issues/26943#issuecomment-224519722).  I can confirm everything worked in alpha4 but broke in alpha5 for containerized hyperkube.

**Comment by pires** [comment] 2016-11-15 16:29
This fixed it for me on `1.4.6`:
```
--service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
--root-ca-file=/etc/kubernetes/ssl/ca.pem
--cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem
--cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem
--insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
```

**Comment by radupantiru** [comment] 2016-11-15 22:45
Did not work for me until I've **deleted the etcd data folder** and using;

```
--service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
--root-ca-file=/etc/kubernetes/ssl/ca.pem
--cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem
--cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem
--insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
```

**Comment by gvenka008c** [comment] 2017-03-22 03:22
Anyway I can bypass the below error?

```
kubectl logs -f nginx-ingress-rc-nxvkb
I0322 03:21:02.513939       1 main.go:41] Starting NGINX Ingress controller Version 0.7.0
F0322 03:21:02.519600       1 main.go:55] Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

```

**Comment by kargakis** [comment] 2017-06-23 00:09
Please ask on StackOverflow, the kubernetes-users mailing list, or slack if this still a problem.

**Closed by kargakis** 2017-06-23 00:09 UTC
Labels: kind/support, needs-sig, team/control-plane (deprecated - do not use)

**Comment by utsav2307** [comment] 2017-11-13 08:03
I got this working by following:
1) Run kube-controller-manager "--root-ca-file=/etc/kubernetes/ssl/ca.pem" parameter. This will create tokens whenever you create a service account.
2) Next create a service account by name heapster in "kube-system" namespace.
3) I wanted heapster just for using HPA, so i specified the following in command section in heapster's yaml:
- /heapster
- --source=kubernetes:https://<master's ip>:443?inClusterConfig=false
- --sink=log

Make sure the master's ip is the same as what you get on running "kubectl cluster-info"

**Comment by pcj** [comment] 2019-02-10 22:39
Not exactly related to this issue but someone may encounter this via search so I'm posting it here.  

Another reason the serviceaccount/token is not available is if the deployment spec specifically excludes it via `automountServiceAccountToken: false`.  Some tools (like terraform `kubernetes_deployment`) can set this to false (hence overridding the default value `true`) without the user specifically requesting that!

Check your deployment for this value.

**Comment by ranimufid** [comment] 2019-02-14 16:19
@pcj , i'm currently encountering this with terraform. Is there any `kubernetes_deployment` parameter I can use to revert `automountServiceAccountToken` back to `true`? I can't seem to be able to find this in the docs

**Comment by pcj** [comment] 2019-02-15 04:32
@ranimufid I had trouble with that too.  You have to explicitly do the volume mount yourself, such as:

```hcl
resource "kubernetes_service_account" "foo" {
  metadata {
    name      = "foo"
    namespace = "default"
  }
}

resource "kubernetes_role" "foo" {
  metadata {
    name      = "foo"
    namespace = "default"
  }

  rule {
    api_groups = [""]
    resources  = ["pods"]
    verbs      = ["list", "create"]
  }
}

resource "kubernetes_role_binding" "foo" {
  metadata {
    name      = "foo"
    namespace = "default"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = "foo"
  }

  subject {
    // https://github.com/terraform-providers/terraform-provider-kubernetes/issues/204
    api_group = ""
    kind      = "ServiceAccount"
    name      = "foo"
  }
}

resource "kubernetes_deployment" "foo" {
  metadata {
    name = "foo"

    labels {
      app = "foo"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels {
        app = "foo"
      }
    }

    template {
      metadata {
        labels {
          app = "foo"
        }
      }

      spec {
        service_account_name = "foo"

        container {
          name  = "foo"
          image = "gcr.io/repo/foo:v20181207-201eb76"

          port {
            name           = "http"
            container_port = 8888
          }

          volume_mount {
            mount_path = "/var/run/secrets/kubernetes.io/serviceaccount"
            name       = "${kubernetes_service_account.foo.default_secret_name}"
            read_only  = true
          }
        }

        volume {
          name = "${kubernetes_service_account.foo.default_secret_name}"

          secret {
            secret_name = "${kubernetes_service_account.foo.default_secret_name}"
          }
        }
      }
    }
  }
}
```

There's a github issue on the terraform-provider-kubernetes repo that shows this/similar example but I don't have the reference handy.  Ignore the role/rolebinding if not interested, it's not required for the example.

**Comment by ranimufid** [comment] 2019-02-15 18:24
Thanks @pcj! That's very helpful. I think this might be the issue you're referring to: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/38

**Comment by shcallaway** [comment] 2019-05-16 21:49
Update for Terraform users:

There is now an `automount_service_account_token` parameter for the `kubernetes_service_account` resource: https://www.terraform.io/docs/providers/kubernetes/r/service_account.html#automount_service_account_token

**Comment by aneeshprodapt** [comment] 2022-03-21 05:46
In my case,  "automountServiceAccountToken: false"  entry was their in default ServiceAccount of the namespace. This was causing the issue.
