### ISSUE TITLE
k8s.io/kubernetes/pkg/controller UT flakes for invalid memory address

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#125181] opened 2024-05-29 06:35 UTC
### Which jobs are flaking?

- k8s.io/kubernetes/pkg/controller/garbagecollector.garbagecollector
- https://k8s.io/kubernetes/pkg/controller: tainteviction

### Which tests are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1795460000760467456
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1795613262369263616

### Since when has it been flaking?

NA

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

> stacktrace=<
> 	goroutine 561 [running]:
> 	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3a488b8, 0x4edba40}, {0x31ac240, 0x4e2c1d0})
> 		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xe5
> 	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x3a488b8, 0x4edba40}, {0x31ac240, 0x4e2c1d0}, {0x4edba40, 0x0, 0xc000c94da8?})
> 		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0xa2
> 	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x36477f0?})
> 		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x18f
> 	panic({0x31ac240?, 0x4e2c1d0?})
> 		/usr/local/go/src/runtime/panic.go:770 +0x132
> 	k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
> 		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/record/event.go:407 +0xbc
> 	created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher in goroutine 552
> 		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/record/event.go:400 +0x1b1
>  >
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x223479c]
>

**Comment by aojea** [comment] 2024-05-29 07:28
The panic is in the event watcher, @pohly @dgrisonnet you have landed several changes recently that are most probably related, can  you PTAL?

/sig instrumentation

**Comment by aojea** [comment] 2024-05-29 07:36
ok, so the problem is this

> E0528 14:33:05.634743   48023 event.go:398] "Unable start event watcher (will not retry!)" err="broadcaster already stopped" logger="TestGarbageCollectorConstruction leaked goroutine"
> E0528 14:33:05.635289   48023 event.go:398] "Unable start event watcher (will not retry!)" err="broadcaster already stopped" logger="TestGarbageCollectorConstruction leaked goroutine"


The watcher fails to be created

https://github.com/kubernetes/kubernetes/blob/7ba244f50e57257e9d435b42f3b0f17a92a0611a/staging/src/k8s.io/client-go/tools/record/event.go#L397-L399

but the goroutine keeps going and tries to get a channel from it

https://github.com/kubernetes/kubernetes/blob/7ba244f50e57257e9d435b42f3b0f17a92a0611a/staging/src/k8s.io/client-go/tools/record/event.go#L407

/assign @pohly

**Comment by pohly** [comment] 2024-05-29 11:58
That problem has already been there before the recent changes:

https://github.com/kubernetes/kubernetes/blob/f7dacb63cc0b0e79450b2f6d97b1c6e6c46070bd/staging/src/k8s.io/client-go/tools/record/event.go#L313-L331

When constructing the watch fails, that code needs to return instead of spawning the goroutine.

I think this is okay:
> E0528 14:33:05.634743 48023 event.go:398] "Unable start event watcher (will not retry!)" err="broadcaster already stopped" logger="TestGarbageCollectorConstruction leaked goroutine"

The `logger="TestGarbageCollectorConstruction leaked goroutine"` indicates that the `Unable start event watcher (will not retry!)` occurs after the test has completed. Before the recent changes, creating the watch would have succeeded and the test would have permanently leaked the goroutines. In that sense, the recent changes work as intended.

**Comment by aojea** [comment] 2024-05-29 12:00
ok, so this just uncovered an existing bug, those are the positive news 😄

**Comment by aojea** [comment] 2024-05-29 12:01
> When constructing the watch fails, that code needs to return instead of spawning the goroutine.

I don't know if we'll translate the problem to other layer, as `StartEventWatcher` will return a nil ,  it seems StartEventWatcher has to also return an error?

**Comment by pohly** [comment] 2024-05-29 12:09
I'm adding `return watch.NewEmptyWatch()` - https://github.com/kubernetes/kubernetes/blob/afebfdc5d411859468153e2b9921915f3e4f9ff4/staging/src/k8s.io/apimachinery/pkg/watch/watch.go#L74-L81

**Comment by pohly** [comment] 2024-05-29 12:20
Because of `defer utilruntime.HandleCrash()`, this shouldn't occur in production.

**Closed** 2024-05-29 13:20 UTC
Labels: kind/flake, sig/instrumentation, needs-triage
