### ISSUE TITLE
Cannot mount volume with different subPath

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#34453] opened 2016-10-10 15:19 UTC
**Kubernetes version** (use `kubectl version`): 1.4 (client and server)

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"201
6-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"201
6-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:
Doesn't show an error but only keeps **one** of the volumes mount when the same volume is mounted multiple times (with different `mountPath` and `subPath`).

**What you expected to happen**:
Should work (that's the main reason to have `subPath`) or at least fail with an error.

**How to reproduce it** (as minimally and precisely as possible):
YAML:

```
     volumeMounts:
        - name: che-vol
          mountPath: /home/user/che/workspaces
          subPath: workspaces
        - name: che-vol
          mountPath: /home/user/che/storage
          subPath: storage
```

**Anything else do we need to know**:
Trying here to mount a GKE disk, so cannot reference that volume twice.

**Comment by wernight** [comment] 2016-10-11 11:06
Example of where it'd be useful:

  - https://github.com/wernight/kubernetes-che
  - GitLab (to have config and data on the same disk and allow snapshoting them together)

**Comment by ymqytw** [comment] 2016-10-13 01:44
@kubernetes/sig-storage

**Comment by thockin** [comment] 2016-10-13 03:34
I just did a simple test, can confirm something is wonky...

**Comment by wernight** [comment] 2016-10-13 07:12
Forgot to specify that in my case I'm using a GKE disk.

**Comment by thockin** [comment] 2016-10-14 05:47
Disk tech doesn't matter. I can repro with an emptyDir

**Comment by thockin** [comment] 2016-10-14 06:03
Hmm, I just tried again and it worked.  What as broken for me was kubectl
edit (#34800)

**Comment by wernight** [comment] 2016-10-14 09:15
I don't do `kubectl edit` often. I mostly do `kubectl apply` to upgrade a `Deployment` and for that this bug appears.

**Comment by thockin** [comment] 2016-10-14 23:41
Apply also does patch - can you verify by reading-back that the YAML you
wanted got saved correctly?

**Comment by wernight** [comment] 2016-10-15 00:26
I not sure I understand your question. My YAML that I tried to apply is as above in this bug report (at least the relevant section).

**Comment by matchstick** [comment] 2016-10-15 07:47
@saad-ali I know you are busy but can you look at this for triage? If not let me know. @kubernetes/sig-storage

**Comment by thockin** [comment] 2016-10-16 04:02
My question was whether the YAML that the server has matches the YAML you
sent.  I found a bug in `kubectl apply` which caused my initial repro to
match your experience, but when I work around the bug (`kubectl replace`
instead of apply), the bug did not repro.

**Comment by wernight** [comment] 2016-10-16 23:01
It matches almost. The difference are the mounts: It only keeps one of the two mounts.

**Comment by thockin** [comment] 2016-10-16 23:21
Can you try with kubectl replace instead of apply?  It sounds like you hit
the same bug...

**Comment by wernight** [comment] 2016-10-17 00:55
Looks like it's working; but `replace` doesn't work for services, so it's really a workaround for now.

**Comment by thockin** [comment] 2016-10-17 01:45
It does work for services, you just need to RMW first.

**Comment by wernight** [comment] 2016-10-17 08:26
That mount error didn't appear on another test on another project, so possibly it was a temporary fluke.

I get: `Service "foo" is invalid: spec.clusterIP: Invalid value: "": field is immutable` like on issue #11237 . You say one can read-modify-write, just I don't see that on [kubectl replace](http://kubernetes.io/docs/user-guide/kubectl/kubectl_replace/). Do you mean to manually retrieve it the server YAML, modify it, and then `kubectl replace` with that? If so, it's not really "working" as a replacement for `apply`. At least it looks like the issue is in that "patch".

**Comment by thockin** [comment] 2016-10-18 03:44
yeah, `kubectl get -o yaml > file.yml; edit; kubectl replace -f file.yml`.

We know what the bug is, hopefully we can fix it in a 1.4.x

**Comment by saad-ali** [comment] 2016-10-18 04:10
Ref root cause: https://github.com/kubernetes/kubernetes/issues/34800

**Comment by jingxu97** [comment] 2017-12-18 22:21
@saad-ali Since the root cause #34800 is closed, can we close this one?

**Closed** 2018-02-16 23:09 UTC
Labels: lifecycle/rotten, sig/storage, team/cluster (deprecated - do not use)
