### ISSUE TITLE
Evaluate overlayfs with docker

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#15867] opened 2015-10-19 18:28 UTC
Docker now supports Overlayfs as a storage backend. Since Aufs doesn't work on all distributions and has caused kernel issues in the past (#10959), we should evaluate `Overlayfs` and see if it can become the default/recommended storage driver for kubernetes deployments.

Kubernetes is already being used with multiple storage backends, but our existing test infrastructure does not test against all the possible docker storage backends. Until we can enhance the existing kubernetes e2e infrastructure, we will continue to recommend users to use the default storage backend, which is `Aufs` as of now.

**Comment by justinsb** [comment] 2015-10-20 10:21
I would love to evaluate btrfs at the same time.  I personally have found it more reliable than aufs.  The biggest failing btrfs has is that when the disk gets close to full it behaves poorly (ENOSPC and no way to release space), although this is better in newer kernel versions and can typically be avoided by cleaning up docker images regularly (which we do) and perhaps by running a rebalance as a cron job on older kernels.

**Comment by rhatdan** [comment] 2015-10-20 12:06
I think this would be premature to make it default.  Multiple reasons to hold off on OverlayFS.
1.  Currently overlayfs with docker does not support SELInux labeling properly.  This means we have
to turn off SELinux separation between containers.  I believe SELinux is the best tool we currently have for
container separation.
2.  Overlayfs is not a posix compatible file system.  The first time we turned it on, we realized that it broke rpm/yum/dnf.  rpm libraries do a open of database files in /var/lib/rpm/ Read/Only, later on they open the same files as Read/Write which causes overlayfs to do a write up and rpm ends up having two file descriptors open to two different files, while it thinks it has the same file opened once.  We have fixed this by modifying yum to cause a write up right away.  But we don't know of any other programs that might expect similar behaviour. Locking files might cause problems.
3.  Overlayfs is a brand new file system,  I believe people should use a file system for a couple of years to understand the problems it could cause.  Using it for key infrastructure by default seems a little irresponsible.

**Comment by rhvgoyal** [comment] 2015-10-20 12:14
Agreed. OverlayFS is very new and not posix compliant. So applications might be in for a surprise. So while overlayfs should be an option but it is early for the default, I guess.

**Comment by rhvgoyal** [comment] 2015-10-20 12:24
It might be worth going through non standard behavior described here for overlayfs.

https://github.com/torvalds/linux/blob/master/Documentation/filesystems/overlayfs.txt#L178

**Comment by karlkfi** [comment] 2015-11-12 19:38
We use OverlayFS in our docker-in-docker testing for k8s on mesos (based on https://github.com/mesosphere/mesos-slave-dind). It works pretty well for that use case, but there have been some obnoxious recent kernel bugs that we have to test for and avoid. We fallback to AUFS on loop-device on AUFS if overlay isn't working or isn't available.

We're not using OverlayFS in production.

**Comment by smarterclayton** [comment] 2016-01-31 06:22
We (Red Hat) only recommend DeviceMapper in production (for Docker, Kube, and OpenShift on RHEL), and basically give the guidance above that Dan mentioned.  RHEL has a taint flag to warn applications when they are exposed to the non-POSIXness while running on Overlay, but we haven't had a sufficiently broad soak on a wide class of real apps yet to get feedback on the prevalence of issues.  I would expect to firm that position up over the next 3-6 months.

**Comment by dchen1107** [comment] 2016-05-04 22:09
cc/ @mrunalp

**Comment by dchen1107** [comment] 2016-05-04 22:12
cc/ @andyzheng0831 from our GCI team too.

**Comment by jeremyeder** [comment] 2016-05-06 16:49
Hmm, for me, the question is whether we really need to do this -- or should we be concentrating within the OCI framework to get away from CoW entirely.

If I could speak for only myself [1], I believe bind-mounted, read-only, non-root containers with payload on top is a superior design.

If you say that's too far off, then honestly not much has changed since https://github.com/kubernetes/kubernetes/issues/15867#issuecomment-149544988

That said, Overlay is fully supported in Red Hat's products, and we would be happy to help in qualifying it for use with Kubernetes.

[1] https://twitter.com/jeremyeder/status/721107670846029824

**Comment by rhatdan** [comment] 2016-05-06 16:57
I agree the long range we should be getting rid of COW file systems in production.  COW if for Developers and "Pet" containers.

**Comment by smarterclayton** [comment] 2016-05-06 16:58
Probably at least a year off for many people, and is fairly inflexible for
new users / new workloads.

**Comment by jeremyeder** [comment] 2016-05-06 17:03
So, is this gh issue really just asking for someone to write a test plan?

**Comment by vishh** [comment] 2016-05-06 18:41
@jeremyeder We ideally want k8s to support only a single CoW filesystem, as long as a CoW is required. This issue proposes considering `Overlayfs` as that default. We need to run adequate tests, in addition to fixing the issues that @rhatdan has pointed out [earlier](https://github.com/kubernetes/kubernetes/issues/15867#issuecomment-149544988), before we can consider using `Overlayfs` as the only supported CoW filesystem.

**Comment by dchen1107** [comment] 2016-05-06 18:42
We filed this issue for evaluating / validating overlayfs since many users asked for / questioned it. We also decided to include it as the filesystem to our GCI image. But we are far away to decide which filesystem is the default / recommended filesystem for now.

One of Kubelet's roadmap for the disk accounting in short and medium term is supporting the most common docker storage backends: devicemapper, aufs and overlayfs. Kubelet added overlayfs support since k8s 1.2 release. and devicemapper support is driven by Redhat team, and plan to have that support for 1.3 release. We didn't change that plan. 

On another side, I agreed with @jeremyeder on the statement of having bind-mounted, read-only, non-root containers with payload on top is a superior design. I raised this topic a couple months ago at one of sig-node meetings, but the consensus is it is too far away now. 

@jeremyeder We recently had a deep discussion on Container runtime interface with @mrunalp. Overlayfs is the topic raised when talking about the container's rootfs. @mrunalp mentioned that you guys did some evaluation & testing with overlayfs, and found some critical bugs besides the issues pointed out by @rhatdan. Could you please share with us the existing bug list?

**Comment by eparis** [comment] 2016-05-06 18:50
Given that overlayfs is non-posix conformant (and never will be) it seems it would be an extremely bad choice for it to be the `single` CoW filesystem. Bugs might be a problem right now which can be solved, but non-posix is a design flaw forever....

**Comment by smarterclayton** [comment] 2016-05-06 18:52
We should definitely look to *enable* read only non-CoW.  I'm just worried
that it's yet another bar for usability for Kube, so we'll continue to be
expected to work well with the other workload.

**Comment by jeremyeder** [comment] 2016-05-06 20:24
Hi @dchen1107 --

Do you have any indication what is driving "since many users asked for / questioned it" ?

---

Yes indeed @mrunalp is correct, we did to a lot of testing on Overlay before we marked it as fully supported in the latest release of RHEL (7.2).  

The output of that process was several things...documentation, configuration advice, performance testing, running a bunch of complex traditional ISV applications, and extra debug capabilities.

A few weeks ago I did even more research into Overlay and ended up pitching it to a group internally who has a workload that would be best served by Overlay.  But we have a lot of confidence in devicemapper, and folks want much more testing and soak time before consider moving away.

This is why I was asking if this issue is really about a test plan, because until we can agree on exactly the features that people want in overlay, as well as a test suite to exercise it there didn't seem to be any wiggle room (at least internally here).

BTW -- supporting a single CoW for Kube...sounds like the goal is to keep the test matrix under control, which I can sympathize with of course.  But I'm not sure we can (or should) arrive at one :-(

Anyway here's a roll-up as you requested, Dawn:

- [Red Hat Enterprise Linux 7.2 release notes, caveats for OverlayFS usage](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.2_Release_Notes/index.html#technology-preview-file_systems)

- David Howells added a knob to the kernel called check_copy_up [here](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/overlayfs/copy_up.c?id=fb5bb2c3b73df060d588b6521de5ab03589283f7) to help us debug issues related to some of the "non-standard behavior" of OverlayFS.

- The RHEL7 kernel has ```/sys/module/overlay/parameters/check_copy_up``` set to 1 by default.  This will at least tell us if the copy_up issue is present, and that way we can ask the customer what the app is doing.  We ran a lot of traditional apps in containers on overlay and we didn't hit this issue.  That said, if a customer app expects strict POSIX compliance then we would at least have a log message show up.

- [Non-standard Behavior of OverlayFS from upstream kernel docs]
(https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/overlayfs.txt#n179)

- You won't see the full list because some are security related and thus protected, but here are some of the things filed against overlay:
[list of red hat bugzilla issues related to overlayfs](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=POST&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&classification=Red%20Hat&component=docker&component=kernel&list_id=5076850&product=Red%20Hat%20Enterprise%20Linux%207&query_format=advanced&short_desc=overlay&short_desc_type=allwordssubstr)

**Comment by rhatdan** [comment] 2016-05-06 20:36
@rhvgoyal has been doing a lot of work with overlayfs kernel, trying to get SELinux to work properly and has found a few other issues, and submitted some fixes.

My biggest concern is about the lack of activity in the OverlayFS kernel work.  Until recently there have not been many people working on it, especially outside of Red Hat.

**Comment by rhvgoyal** [comment] 2016-05-09 13:19
Can't we enable support for overlayfs but not make it default and let users opt-in if they want to. That way some users will play with it, issues will be highlighted and possibly fixed or there will be known limitations and only those who can live with those limitations will choose overlayfs.

**Comment by andyzheng0831** [comment] 2016-05-09 16:52
cc @adityakali

**Comment by szmi** [comment] 2016-05-09 21:07
Hi, I'm the author and maintainer of overlayfs.

Contrary to popular belief overlayfs POSIX compliance **can** be fixed.  I haven't looked how aufs is going about it, whether it's duplicating the page cache or not.  But even a non-duplicating cache seems possible at filesystem level.  There are some technical challenges, but I don't see anything insurmountable. 

Even if not duplicating page cache is hard,  we could have an option to control whether one wants strict POSIX compliance at the cost of performance and memory use.

Two reasons why overlayfs went the non-posix way:

1) wanted first version to be small and simple for it to be easily merged

2) union-mounts have exactly the same posixness issues and it wasn't clear whether these were problematic in real-life or not

**Comment by rhvgoyal** [comment] 2016-05-10 12:59
Not duplicating page cache is single biggest advantage of overlayfs. Not sure if an option to move away from that will help.

**Comment by lihan** [comment] 2017-05-23 04:11
+1

**Comment by adityakali** [comment] 2017-05-23 05:07
Sorry for not updating this in a while.
[Container-Optimized OS](https://cloud.google.com/container-optimized-os/) has been running overlayfs (with ext4 as base filesystem) in production for about an year now. While I can't claim that it was without any issues, backporting latest overlayfs fixes from upstream has helped. Among other testing, we rely on xfstests (https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/tests/overlay) to provide us regression testing. Overall, we have been pretty happy with it so far.

**Comment by lihan** [comment] 2017-05-23 05:11
@adityakali 
I'm running on `GKE 1.6.2`, I tried to run `sudo lsmod | grep overlay` on the physical node which returns no entry, anything missing here?

**Comment by adityakali** [comment] 2017-05-23 05:50
Its not built as a separate module. Try this:

```
$ sudo modprobe configs
$ zcat /proc/config.gz | grep OVERLAY
CONFIG_OVERLAY_FS=y
```

**Closed** 2018-02-23 01:33 UTC
Labels: area/os/gci, lifecycle/rotten, priority/important-soon, sig/node
