### ISSUE TITLE
BUG: Memory-limited jobs with a resource quota that initially don't have enough resources stay in queue almost forever

### ISSUE THREAD

**Issue by murhum1** [kubernetes/kubernetes#45213] opened 2017-05-02 06:41 UTC
**What keywords did you search in Kubernetes issues before filing this one?**
Job, resourcequota, scheduler

- **Kubernetes version** (use `kubectl version`):

    Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"a55267932d501b9fbd6d73e5ded47d79b5763ce5", GitTreeState:"clean", BuildDate:"2017-04-14T13:36:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- **Environment**: CentOS bare metal (https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/)
- **Cloud provider or hardware configuration**: -
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux <server name> 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: -
- **Others**: -

**What happened**:
Having created a resourcequota (e.g. 400M) and creating enough memory-limited jobs to go over that quota (e.g. 4 x 200M limit jobs), at first, two jobs are created and executed as expected, and two jobs fail at first due to memory quota:

    Events:
      FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason		Message
      ---------	--------	-----	----		-------------	--------	------		-------
      4s		4s		1	job-controller			Warning		FailedCreate	Error creating: pods "memhog-y152c55u-" is forbidden: exceeded quota: memoryquota, requested: memory=200Mi, used: memory=400Mi, limited: memory=400Mi

After the first two jobs have been completed, instead of starting the remaining jobs as soon as possible, the remaining two jobs stay unstarted in this state for many, many hours until they finally start and complete.

First job: Start Time:	Fri, 28 Apr 2017 15:00:08 +0300
One of the remaining 2 jobs: Start Time:	Sat, 29 Apr 2017 07:13:34 +0300

**What you expected to happen**:

I'm expecting the two waiting jobs to start executing as soon as the resources they need are available, e.g. as soon as the first jobs are completed.

**How to reproduce it** (as minimally and precisely as possible):

Bring up a kubernetes cluster, then execute these commands:

    $ kubectl create quota memoryquota --hard=memory=400Mi
    $ echo kubectl run memhog-'$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)' --replicas=1 --restart=OnFailure --image-pull-policy=IfNotPresent --limits=memory='$1'Mi,cpu=100m --record --image=derekwaynecarr/memhog --command -- memhog -r100 '$2'm > run-memhog.sh
    $ chmod +x run-memhog.sh
    $ for i in {1..4}; do ./run-memhog.sh 200 100; done
    job "memhog-0ju2eiuy" created
    job "memhog-t8qyt5sj" created
    job "memhog-ljaqz4ek" created
    job "memhog-eb8q8kr3" created

Wait for around 30 seconds and the first jobs should be complete:
    
    $ kubectl get jobs
    NAME              DESIRED   SUCCESSFUL   AGE 
    memhog-0ju2eiuy   1         1            43s
    memhog-eb8q8kr3   1         0            42s
    memhog-ljaqz4ek   1         0            43s
    memhog-t8qyt5sj   1         1            43s
    $ kubectl describe jobs
    ....

However, the remaining jobs don't start at all as shown by:

    $ kubectl describe job memhog-ljaqz4ek
    Name:   memhog-ljaqz4ek
    Namespace:  test
    Selector: controller-uid=dd6fb770-2f00-11e7-8766-52c84ff43b2b
    Labels:   run=memhog-ljaqz4ek
    Annotations:  kubernetes.io/change-cause=kubectl run memhog-ljaqz4ek memhog -r100 100m --replicas=1 --restart=OnFailure --image-pull-policy=IfNotPresent --limits=memory=200Mi,cpu=100m --record=true --image=derekway...
    Parallelism:  1
    Completions:  1
    Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
    Pod Template:
      Labels: controller-uid=dd6fb770-2f00-11e7-8766-52c84ff43b2b
        job-name=memhog-ljaqz4ek
        run=memhog-ljaqz4ek
      Containers:
       memhog-ljaqz4ek:
        Image:  derekwaynecarr/memhog
        Port: 
        Command:
          memhog
          -r100
          100m
        Limits:
          cpu:    100m
          memory:   200Mi
        Environment:  <none>
        Mounts:   <none>
      Volumes:    <none>
    Events:
      FirstSeen LastSeen  Count From    SubObjectPath Type    Reason    Message
      --------- --------  ----- ----    ------------- --------  ------    -------
      3m    3m    1 job-controller      Warning   FailedCreate  Error creating: pods "memhog-ljaqz4ek-" is forbidden: exceeded quota: memoryquota, requested: memory=200Mi, used: memory=400Mi, limited: memory=400Mi    

Furthermore, pods related to the remaining jobs aren't even created and only the completed pods are shown:

    $ kubectl get pods -a
    NAME                    READY     STATUS      RESTARTS   AGE
    memhog-0ju2eiuy-bz0zm   0/1       Completed   0          7m
    memhog-t8qyt5sj-q9msw   0/1       Completed   0          7m    

**Anything else we need to know**:

I've also created a stackoverflow question about this (http://stackoverflow.com/questions/43654683/resourcequota-multiple-memory-limited-jobs-restarting-pending-jobs-takes-for), and asked about this in the kubernetes slack, where I was urged to create a bug report.

**Comment by erictune** [comment] 2017-05-04 21:56
@kubernetes/sig-scheduling-bugs

**Comment by davidopp** [comment] 2017-05-04 22:06
@derekwaynecarr

**Comment by derekwaynecarr** [comment] 2017-05-09 01:59
I will try to reproduce.

The creation of a pod will be blocked by quota.  In the absence of a pod, the scheduler has nothing to schedule, so it is not a scheduling bug.  It's possible the issue is related to back-off in the job controller not attempting to create pods again.  The event shows that it had been 3m since the job controller attempted to create pods again for the requisite job which implies some type of back-off.  None of the controllers are quota aware, so I would anticipate they should just keep trying at reasonable intervals at this point.

If you describe quota after the first 2 pods are completed, do you see quota usage being replenished as expected?

**Comment by tacy** [comment] 2017-05-09 02:10
@derekwaynecarr 

I would like to fix the bug, could you assigin it to me?

if pod create failed, jobcontroller.managejob(https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller.go#L539) need return error, https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller.go#L341 will requeue podcreate task.

**Comment by derekwaynecarr** [comment] 2017-05-09 02:13
@erictune -- maybe you have more insight, but it looks to me just reading the code that when a job controller is unable to create a pod due to lack of quota, its not actually an error that forces a re-queue of the job.  in addition, i cant actually see when a full resync of the job work queue happens outside of the informer sync interval which is probably really long.

see: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller.go#L457
see: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller.go#L609

**Comment by derekwaynecarr** [comment] 2017-05-09 02:14
@tacy - feel free to open a pr, please cc me on your solution.  i would like to understand from the job folks if there should be a periodic resync interval aside from the need to requeue the job when all pods cannot be spawned (which i assume your pr will handle via exponential backoff)

**Comment by derekwaynecarr** [comment] 2017-05-09 02:18
@ncdc @liggitt -- we will want to have a fix for this downstream as well.

**Comment by murhum1** [comment] 2017-05-09 04:42
@derekwaynecarr 
> If you describe quota after the first 2 pods are completed, do you see quota usage being replenished as expected?

Yes, after the first two jobs are complete, `kubectl describe quota memoryquota` shows that 0M out of 400M is in use. I'm also able to create new jobs, up to the memory limit so 2 at a time, that execute as expected. Any jobs over that at a time will stay in the same waiting state.

**Comment by tacy** [comment] 2017-05-09 05:44
@derekwaynecarr  - Yes, I want handle it via exponential backoff.
IMO, MaxOfRateLimiter had implemented  a periodic resync,  we don't need another one.

**Comment by soltysh** [comment] 2017-05-12 11:52
@derekwaynecarr I'll make sure to cherry-pick this to openshift (@sttts @ncdc fyi).

**Closed** 2017-05-16 04:08 UTC
Labels: area/batch, area/workload-api/job, kind/bug, sig/apps, sig/scheduling
