### ISSUE TITLE
Kubernetes master freezes when the etcd leader is unreachable

### ISSUE THREAD

**Issue by lhuard1A** [kubernetes/kubernetes#5589] opened 2015-03-18 10:24 UTC
While doing some perturbation tests, I noticed that the Kubernetes master breaks if we loose the machine hosting the etcd leader.

Here is the test (I’m using the libvirt-coreos cluster)

### Suspend any non-leader node

* Start a cluster with a multi-node etcd cluster and a multi-node kubernetes cluster
```
$ ./cluster/kube-up.sh
```

* Issue a `get minions` query:
```
$ ./cluster/kubectl.sh get minions
NAME                LABELS              STATUS
192.168.10.2        <none>              Ready
192.168.10.3        <none>              Ready
192.168.10.4        <none>              Ready
```

* Suspend a VM which is a kubernetes node and an etcd node:
```
$ virsh suspend kubernetes-minion-2
Domain kubernetes-minion-2 suspended
```

* Issue a `get minions` query:
```
$ ./cluster/kubectl.sh get minions
NAME                LABELS              STATUS
192.168.10.2        <none>              Ready
192.168.10.3        <none>              Ready
192.168.10.4        <none>              Ready

$ ./cluster/kubectl.sh get minions -o yaml | grep lastProbeTime
      lastProbeTime: 2015-03-18T09:48:08Z
      lastProbeTime: 2015-03-18T09:46:42Z
      lastProbeTime: 2015-03-18T09:48:08Z
```

**`get minions` answers and we see that the `lastProbeTime` of the frozen VM is not refreshed anymore. This is what is expected**

Now, the issue:

### Suspend the the VM hosting the etcd leader

* Start a cluster with a multi-node etcd cluster and a multi-node kubernetes cluster
```
$ ./cluster/kube-up.sh
```

* Issue a `get minions` query:
```
$ ./cluster/kubectl.sh get minions
NAME                LABELS              STATUS
192.168.10.2        <none>              Ready
192.168.10.3        <none>              Ready
192.168.10.4        <none>              Ready
```

* Suspend the VM which is the etcd leader:
```
$ for i in {1..4}; do ssh core@192.168.10.$i journalctl -u etcd; done | sort | egrep "state|leader"
…
Mar 18 09:51:14 kubernetes-minion-1 etcd[560]: [etcd] Mar 18 09:51:14.004 INFO      | kubernetes-minion-1: leader changed from '' to 'kubernetes-minion-1'.
Mar 18 09:51:14 kubernetes-minion-1 etcd[560]: [etcd] Mar 18 09:51:14.004 INFO      | kubernetes-minion-1: state changed from 'follower' to 'leader'.
…

$ virsh suspend kubernetes-minion-1
Domain kubernetes-minion-1 suspended
```

* Issue a `get minions` query:
```
$ ./cluster/kubectl.sh get minions
F0318 10:55:11.503734   17913 get.go:67] Error received from API: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

* Test that etcd is still responsive on the master:
```
$ ssh core@192.168.10.1 ps ax \| grep kube-api
/opt/kubernetes/bin/kube-apiserver […] --etcd_servers=http://127.0.0.1:4001 […]

$ ssh core@192.168.10.1 etcdctl ls
/registry
/coreos.com
```

* Check that etcd elect a new leader:
```
$ for i in {1..4}; do ssh -o ConnectTimeout=2s core@192.168.10.$i journalctl -u etcd; done | sort | egrep "state|leader"
[…]
Mar 18 09:54:32 kubernetes-master etcd[575]: [etcd] Mar 18 09:54:32.939 INFO      | kubernetes-master: leader changed from 'kubernetes-minion-1' to ''.
Mar 18 09:54:32 kubernetes-minion-2 etcd[568]: [etcd] Mar 18 09:54:32.874 INFO      | kubernetes-minion-2: leader changed from 'kubernetes-minion-1' to ''.
Mar 18 09:54:33 kubernetes-minion-3 etcd[565]: [etcd] Mar 18 09:54:33.135 INFO      | kubernetes-minion-3: leader changed from 'kubernetes-minion-1' to ''.
Mar 18 09:54:33 kubernetes-minion-3 etcd[565]: [etcd] Mar 18 09:54:33.135 INFO      | kubernetes-minion-3: state changed from 'follower' to 'candidate'.
Mar 18 09:54:33 kubernetes-minion-3 etcd[565]: [etcd] Mar 18 09:54:33.137 INFO      | kubernetes-minion-3: leader changed from '' to 'kubernetes-minion-3'.
Mar 18 09:54:33 kubernetes-minion-3 etcd[565]: [etcd] Mar 18 09:54:33.137 INFO      | kubernetes-minion-3: state changed from 'candidate' to 'leader'.
```

* But Kubernetes doesn’t recover:
```
$ cluster/kubectl.sh get minions
F0318 11:16:18.822576   19360 get.go:67] Error received from API: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

**The kubernetes master is streaming logs saying: `501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]` and all kubectl commands answer with the same reply.**

The etcd cluster could be secured on a set of dedicated VMs, but still: the loss of a single VM of a cluster can completely break Kubernetes if we are so unlucky that the lost VM was the etcd leader.

Would anybody be aware of a such a kind of issue and possible mitigation?

**Comment by brendandburns** [comment] 2015-03-18 20:48
I believe that the --etcd_servers flag should be a comma separated list of
all servers for an HA etcd deployment.

Can you try that?

If that's not the problem, then it's something in the etcd client library
and we'll need to dog in more.

Brendan

**Comment by lhuard1A** [comment] 2015-03-19 16:48
Good point about the `--etcd_servers`. Following your advice, I submitted #5656.

Unfortunately, it doesn’t solve the issue. Here is what I have now:
* `kube-apiserver` is connected to all the etcd nodes of the cluster:
```
$ ssh core@192.168.10.1 'ps aux | grep kube-apiserver'
[…]kube-apiserver […] --etcd_servers=http://192.168.10.1:4001,http://192.168.10.2:4001,http://192.168.10.3:4001,http://192.168.10.4:4001 […]
```

* Check which etcd node is the leader (it is `kubernetes-minion-1` `192.168.10.2`) :
```
$ for i in {1..4}; do ssh -o ConnectTimeout=2s core@192.168.10.$i journalctl -u etcd; done | sort | egrep "state|leader"
[…]
kubernetes-minion-1: leader changed from '' to 'kubernetes-minion-1'.
kubernetes-minion-1: state changed from 'follower' to 'leader'.
[…]
```

* Try to freeze a non-leader etcd node:
```
ssh core@192.168.10.1 'sudo kill -STOP $(pgrep etcd)'
```

* `kube-apiserver` is still responsive:
```
$ cluster/kubectl.sh get minions
NAME                LABELS              STATUS
192.168.10.2        <none>              Ready
192.168.10.3        <none>              Ready
192.168.10.4        <none>              Ready
```

* Unfreeze the frozen node and freeze the leader one instead (The leader is `kubernetes-minion-1` which is `192.168.10.2`):
```
$ ssh core@192.168.10.1 'sudo kill -CONT $(pgrep etcd)'
$ ssh core@192.168.10.2 'sudo kill -STOP $(pgrep etcd)'
```

* `kube-apiserver` is now unresponsive:
```
$ cluster/kubectl.sh get minions
… waits indefinitively …
```

* Check that etcd is still responsive:
```
$ etcdctl -C http://192.168.10.1:4001,http://192.168.10.2:4001,http://192.168.10.3:4001,http://192.168.10.4:4001 get /registry/minions/192.168.10.2
{"kind":"Minion","id":"192.168.10.2","uid":"3d13aa4a-ce53-11e4-970e-525400000003",[…]
$ etcdctl -C http://192.168.10.1:4001,http://192.168.10.2:4001,http://192.168.10.3:4001,http://192.168.10.4:4001 get /registry/minions/192.168.10.3
{"kind":"Minion","id":"192.168.10.3","uid":"3d273c9c-ce53-11e4-970e-525400000003",[…]
$ etcdctl -C http://192.168.10.1:4001,http://192.168.10.2:4001,http://192.168.10.3:4001,http://192.168.10.4:4001 get /registry/minions/192.168.10.4
{"kind":"Minion","id":"192.168.10.4","uid":"3d2cdc1f-ce53-11e4-970e-525400000003",[…]
```

* Check has a leader re-election has occured:
```
$ for i in {1..4}; do ssh -o ConnectTimeout=2s core@192.168.10.$i journalctl -u etcd; done | sort | egrep "state|leader"
Mar 19 16:35:22 kubernetes-minion-2 etcd[578]: [etcd] Mar 19 16:35:22.161 INFO      | kubernetes-minion-2: state changed from 'candidate' to 'leader'.
Mar 19 16:35:22 kubernetes-minion-2 etcd[578]: [etcd] Mar 19 16:35:22.162 INFO      | kubernetes-minion-2: leader changed from '' to 'kubernetes-minion-2'.
```

But `kube-apiserver` remains unresponsive as long as the etcd node (which is not the leader anymore) is frozen.

**Comment by alex-mohr** [comment] 2015-03-19 21:39
@davidopp think this falls under team/master?

**Comment by davidopp** [comment] 2015-03-24 20:48
This was marked P1 and 1.0 milestone but I don't think either of these are the case. Obviously we should fix this, but replicated etcd is part of HA master, which is one of our post-1.0 goals. (I sanity-checked with Tim and he agreed.) So , removing 1.0 tag and moving to P2.

**Comment by timothysc** [comment] 2015-04-06 21:18
@jayunit100 ^ per etcd tests.

**Comment by bgrant0607** [comment] 2015-04-08 22:11
cc @hchoudh

**Comment by jayunit100** [comment] 2015-04-10 22:30
we might be able to run an E2E which bashes etcd master in a separate thread to the point that its not capable of responding temporarily as a way to test this.

**Comment by bgrant0607** [comment] 2015-04-11 17:29
See also #6559

**Comment by timothysc** [comment] 2015-04-13 21:24
@lhuard1A FWIW suspend and resume is not the best test, b/c it won't force a failure on bounded sockets.  But it does highlight that https://github.com/GoogleCloudPlatform/kubernetes/issues/6559 is indeed an issue. 

@rrati ^ FYI

**Comment by EricMountain-1A** [comment] 2015-04-14 07:37
@timothysc software generally has more trouble dealing with half-dead situations - if you let the FIN sequence happen then it's easy for the software to understand something has died.  @lhuard1A is ensuring here that there is a network partition that is created without giving the FIN sequence a chance to happen.  It's a stronger test.

**Comment by timothysc** [comment] 2015-04-14 12:56
In either scenario death, or net split, #6559 appears to be the root.

**Comment by timothysc** [comment] 2015-04-29 14:58
@EricMountain-1A , @lhuard1A  just an update, that the root issue is in etcd.

For complete history see: https://github.com/coreos/etcd/issues/2677

**Comment by xiang90** [comment] 2015-04-29 15:01
@timothysc As I have told you, they are different issues. And we cannot reproduce this on in etcd itself. Please read through the history in this issue and the one in etcd again.

**Comment by kelseyhightower** [comment] 2015-04-29 15:10
@timothysc @xiang90 Maybe we jump on a hangout and try and debug together?

**Comment by timothysc** [comment] 2015-04-29 15:19
@kelseyhightower happy to.

**Comment by timothysc** [comment] 2015-08-24 16:26
preference is to close this issue in favor of: #11962

**Comment by bgrant0607** [comment] 2016-05-17 14:08
Obsolete

**Closed by bgrant0607** 2016-05-17 14:08 UTC
Labels: area/availability, area/reliability, dependency/etcd, kind/bug, priority/P2, team/control-plane, team/CSI-API Machinery SIG
