### ISSUE TITLE
CronJob Pods do not automatically remove themselves when successfulJobsHistoryLimit is configured

### ISSUE THREAD

**Issue by cpressland** [kubernetes/kubernetes#71796] opened 2018-12-06 14:45 UTC
**What happened**:
Jobs do not remove thier associated Pods when spawned from a CronJob with `successfulJobsHistoryLimit` set

**What you expected to happen**:
CronJob spawned Pods to delete themselves after a N number of succesful runs.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CronJob with a fairly frequent run schedule and set the `successfulJobsHistoryLimit` value to something low such as 1, 2 or 3.

Jobs are removed when the `successfulJobsHistoryLimit` is hit but the Pod is not removed.

**Anything else we need to know?**:
Environment was upgraded from Kubernetes 1.12.2 to 1.13.0

Example CronJob:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dracula
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: DEBUG
              value: "true"
            image: binkops.azurecr.io/dracula:latest
            imagePullPolicy: Always
            name: dracula
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: binkops.azurecr.io
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: '*/30 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```
Output of Jobs:

```
$ kubectl get job
NAME                              COMPLETIONS   DURATION   AGE
dracula-1544103000                1/1           16s        66m
dracula-1544104800                1/1           15s        36m
dracula-1544106600                1/1           15s        6m9s
```

Output of Pods:
```
$ kubectl get pods
NAME                                        READY   STATUS      RESTARTS   AGE
dracula-1544007600-hhlhf                    0/1     Completed   0          27h
dracula-1544009400-k44b8                    0/1     Completed   0          27h
dracula-1544011200-n2d6c                    0/1     Completed   0          26h
dracula-1544013000-mkcd9                    0/1     Completed   0          26h
dracula-1544014800-4mp4z                    0/1     Completed   0          25h
dracula-1544016600-glzxh                    0/1     Completed   0          25h
dracula-1544018400-w5xgj                    0/1     Completed   0          24h
dracula-1544020200-qtd5g                    0/1     Completed   0          24h
dracula-1544022000-xtqrz                    0/1     Completed   0          23h
dracula-1544023800-qk8zx                    0/1     Completed   0          23h
dracula-1544025600-2f292                    0/1     Completed   0          22h
dracula-1544027400-ptfxj                    0/1     Completed   0          22h
dracula-1544029200-sgj5m                    0/1     Completed   0          21h
dracula-1544031000-8q2wl                    0/1     Completed   0          21h
dracula-1544032800-tjtqw                    0/1     Completed   0          20h
dracula-1544034600-kjr8b                    0/1     Completed   0          20h
dracula-1544036400-kdsbd                    0/1     Completed   0          19h
dracula-1544038200-sh6lp                    0/1     Completed   0          19h
dracula-1544040000-xp94m                    0/1     Completed   0          18h
dracula-1544041800-xq84c                    0/1     Completed   0          18h
dracula-1544043600-4lwxr                    0/1     Completed   0          17h
dracula-1544045400-bbptg                    0/1     Completed   0          17h
dracula-1544047200-mrk6w                    0/1     Completed   0          16h
dracula-1544049000-gqbj2                    0/1     Completed   0          16h
dracula-1544050800-4wd99                    0/1     Completed   0          15h
dracula-1544052600-xqvk6                    0/1     Completed   0          15h
dracula-1544054400-tbzv4                    0/1     Completed   0          14h
dracula-1544056200-jmrch                    0/1     Completed   0          14h
dracula-1544058000-k4jsz                    0/1     Completed   0          13h
dracula-1544059800-sj49c                    0/1     Completed   0          13h
dracula-1544061600-x877x                    0/1     Completed   0          12h
dracula-1544063400-565bv                    0/1     Completed   0          12h
dracula-1544065200-vtvk2                    0/1     Completed   0          11h
dracula-1544067000-tbn7q                    0/1     Completed   0          11h
dracula-1544068800-4llxh                    0/1     Completed   0          10h
dracula-1544070600-mhm5k                    0/1     Completed   0          10h
dracula-1544072400-984h8                    0/1     Completed   0          9h
dracula-1544074200-ds8s7                    0/1     Completed   0          9h
dracula-1544076000-v2w29                    0/1     Completed   0          8h
dracula-1544077800-mmjkz                    0/1     Completed   0          8h
dracula-1544079600-8rf5x                    0/1     Completed   0          7h40m
dracula-1544081400-d8d6d                    0/1     Completed   0          7h9m
dracula-1544083200-dr7bg                    0/1     Completed   0          6h39m
dracula-1544085000-z27nq                    0/1     Completed   0          6h9m
dracula-1544086800-sfr29                    0/1     Completed   0          5h39m
dracula-1544088600-lgc6x                    0/1     Completed   0          5h9m
dracula-1544090400-m7r47                    0/1     Completed   0          4h39m
dracula-1544092200-f7zqh                    0/1     Completed   0          4h9m
dracula-1544094000-482wq                    0/1     Completed   0          3h39m
dracula-1544095800-mrfwg                    0/1     Completed   0          3h9m
dracula-1544097600-7hzrb                    0/1     Completed   0          159m
dracula-1544099400-87qzz                    0/1     Completed   0          130m
dracula-1544101200-gzg7g                    0/1     Completed   0          100m
dracula-1544103000-49p6z                    0/1     Completed   0          69m
dracula-1544104800-lw6p9                    0/1     Completed   0          39m
dracula-1544106600-46nr9                    0/1     Completed   0          9m56s
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Microsoft Azure, Cluster configured by hand, is not AKS.
- OS (e.g. from /etc/os-release):
```
cpressland@westeurope-controller-01 ~ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
```
- Kernel (e.g. `uname -a`):
`Linux westeurope-controller-01 4.15.0-1032-azure #33~16.04.1-Ubuntu SMP Fri Nov 9 22:36:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
Cluster was deployed via in-house Chef cookbook
- Others:
N/A

/kind bug

**Comment by liggitt** [comment] 2018-12-06 14:50
duplicate of https://github.com/kubernetes/kubernetes/issues/71772

/cc @soltysh 
/close

**Closed by liggitt** 2018-12-06 14:50 UTC
Labels: kind/bug, needs-sig
