### ISSUE TITLE
e2e build stuck at "Running build command..."

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39047] opened 2016-12-20 22:50 UTC
Steps to repro:
Run `go run hack/e2e.go -v -build`
Output:
```
2016/12/20 14:46:46 e2e.go:946: Running: make quick-release
+++ [1220 14:46:46] Verifying Prerequisites....
+++ [1220 14:46:46] Building Docker image kube-build:build-a3a7122c38-4-v1.7.4-1
+++ [1220 14:46:50] Syncing sources to container
+++ [1220 14:46:52] Running build command...
```

It just gets stuck there. Adding more logging I found that the command it is trying to run is: 
```
docker run --name=kube-build-a3a7122c38-4-v1.7.4-1 --user=112993:5000 --hostname=nikhiljindal --volumes-from kube-build-data-a3a7122c38-4-v1.7.4-1 --env KUBE_FASTBUILD=true --env KUBE_BUILDER_OS=linux-gnu --env KUBE_BUILD_PPC64LE=n --env KUBE_VERBOSE=1 --interactive --tty kube-build:build-a3a7122c38-4-v1.7.4-1 make cross
```
The command succeeds if I try in a separate tab, but running `go run hack/e2e.go -v -build` always gets stuck here. No idea why is that.

Filing this to see if others are also facing this or have any ideas why I am running into this.

**Comment by nikhiljindal** [comment] 2016-12-20 22:50
cc @ixdy Any idea?

**Comment by dchen1107** [comment] 2016-12-21 01:21
I ran into the same issue. My build is stuck for more than 2 hours. :-(

**Comment by ixdy** [comment] 2016-12-21 01:35
dupe of #39041

**Closed by ixdy** 2016-12-21 01:35 UTC
Labels: area/test, area/test-infra, kind/support
