### ISSUE TITLE
HPA: A single pod with unknown CPU blocks resizing

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#30471] opened 2016-08-11 19:59 UTC
HPA decided to rescale from 37 pods to 70.  For 11 minutes, it was blocked waiting for status on the new pods.  Of those 11 minutes, 8 mins were waiting for CPU usage of 2 pods and 7 mins were waiting for a single pod.

Impact: Presumably it could have had enough statistical significance on the 68 pods' resource usage to make scaling decisions more quickly.  More worrisome: if a single pod were blocked for much longer, HPA would from a user perspective not be working.  It should be more robust.

Aside, file as a different issue if you like, but it's not clear why HPA decided to go from 37 to 70 -- a jump of almost 2x, nor why it decided to scale down afterwards.  Is the workload really that unstable?

I0811 19:33:36.255284       7 horizontal.go:346] Successfull rescale of DEPLOYMENT, old size: 37, new size: 70, reason: CPU utilization above target
I0811 19:33:36.257925       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
I0811 19:33:36.839636       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
I0811 19:33:37.243940       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
I0811 19:33:48.585849       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
I0811 19:34:16.136815       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:34:16.137005       7 horizontal.go:92] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 37/66 of pods
I0811 19:35:03.507715       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:35:03.507754       7 horizontal.go:92] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 36/70 of pods
I0811 19:35:33.205954       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:35:33.205999       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 64/70 of pods
I0811 19:35:33.612257       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:35:33.612316       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 64/70 of pods
I0811 19:36:03.469516       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:36:03.469561       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 64/70 of pods
I0811 19:36:33.263556       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:36:33.263605       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 68/70 of pods
I0811 19:37:03.267194       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:37:03.267243       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 68/70 of pods
I0811 19:37:33.443780       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:37:33.443827       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:38:03.413053       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:38:03.413092       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:38:33.376381       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:38:33.376438       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:39:03.463229       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:39:03.463269       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:39:33.271963       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:39:33.272002       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:40:03.309366       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:40:03.309413       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:40:33.280528       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:40:33.280584       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:41:03.447094       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:41:03.447140       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:41:33.461717       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:41:33.461772       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:42:03.326426       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:42:03.326488       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:42:33.290515       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:42:33.290570       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/71 of pods
I0811 19:43:03.444128       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:43:03.444179       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:43:33.377820       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:43:33.377879       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:44:03.288268       7 horizontal.go:403] Successfully updated status for DEPLOYMENT
W0811 19:44:03.288314       7 horizontal.go:99] Failed to reconcile DEPLOYMENT: failed to compute desired number of replicas based on CPU utilization for DEPLOYMENT_PATH: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 69/70 of pods
I0811 19:44:33.294457       7 horizontal.go:346] Successfull rescale of DEPLOYMENT, old size: 70, new size: 56, reason: All metrics below target

**Comment by goltermann** [comment] 2016-09-06 20:21
@jszczepkowski is this needed for 1.4?

**Comment by jszczepkowski** [comment] 2016-09-12 09:41
I think we should do the following in case CPU for some pods is missing:

- treat missing CPU as 0% for scale-up,
- treat missing CPU as 100% for scale-down.

**Comment by jszczepkowski** [comment] 2016-09-12 09:51
CC @fgrzadkowski

**Comment by fgrzadkowski** [comment] 2016-09-27 14:21
We've seen a similar problem. HPA created many pods, but some of them were pending. Then we couldn't scale down the deployment as some of the metrics were available (for the pending pods).

I think what @jszczepkowski is too simple. What we need to do IMO is:
1. Ignore pods which are not running & ready. We should ignore those missing metrics and compute average based only on other pods.
2. For pods which are running & ready we should do what @jszczepkowski described - if we don't have metrics then:
  1. treat missing CPU as 0% for scale up
  2. treat missing CPU as 100% for scale down

There will be still a chance that something will break if we can't collect metrics for a long time for majority of the pods (e.g. 1 out of 2 pods), but I'd suggest to first implement what I propose above and only then try to fix this long-tail problem.

@DirectXMan12 Do you think you'll have time to work on this?

**Comment by atomantic** [comment] 2016-09-27 16:05
I just hit an issue with this where the HPA was reporting 136% CPU usage on nodes that were taking almost no traffic. It turned out there was a dead pod with an OutOfCPU error. 

The CPU usage dropped to 35% once I deleted this erroneous pod and instances normalized scaling operations. I only found this dead pod by digging into the hidden pods by running "kubectl get pods --all-namespaces -a". If the pod was truly dead beyond repair, it should either have been automatically dealt with or not hidden from default pod listing view.

**Comment by hongshibao** [comment] 2016-09-27 16:24
I think this is a bug in calculating average CPU request in HPA. The sum of CPU request (as the numerator) only count non-pending pods, but the number of pods (as the denominator) count all pods including pending ones. When there are always pending pods, the expected number of replicas will be increasing. You can see my PR for more details.

**Comment by fgrzadkowski** [comment] 2016-09-28 09:49
@atomantic What do you mean by dead? What was the state of this pod? Was it terminated?

@hongshibao Please link the PR this issue.

**Comment by hongshibao** [comment] 2016-09-28 11:36
@fgrzadkowski Pull Request is here: #33529

**Comment by atomantic** [comment] 2016-09-28 21:35
@fgrzadkowski The pod status was "OutOfCPU" and for some reason was blocking the hpa from calculating properly, even though the pod was removed from the default `kubectl get pods` list (had to add `-a` to see it there). Once I deleted the pod, the HPA resumed correct behavior and CPU calculation.

**Comment by hongshibao** [comment] 2016-09-29 03:19
@atomantic I observed a similar issue with yours in my testing environment. There were some pending pods caused by insufficient resources to allocate. What I observed was that HPA reported high CPU usage and thus decided to scale up. The CPU usage reported was increasing and finally the expected replicas to be scaled up reached the max value.

**Comment by jszczepkowski** [comment] 2016-09-29 08:28
There are two issues here:
1. HPA is not counting CPU utilization correctly when some of pods are not running: the fix is in progress (will include  #33529).
2. HPA is not working if some of running pods does not report resource utilization: fix described in https://github.com/kubernetes/kubernetes/issues/30471#issuecomment-249879455.

**Comment by jszczepkowski** [comment] 2016-09-29 09:25
> 1. HPA is not counting CPU utilization correctly when some of pods are not running: the fix is in progress (will include #33529).

Fixed by #33735.

**Comment by dims** [comment] 2016-11-16 14:42
This needs to be triaged as a release-blocker or not for 1.5 @jszczepkowski @alex-mohr @DirectXMan12 @fgrzadkowski

**Comment by DirectXMan12** [comment] 2016-11-16 16:36
This should have been fixed by #33593, so should be closable.

**Comment by fgrzadkowski** [comment] 2016-11-16 21:51
@DirectXMan12 do we have some e2e tests for this? If not, can you add?

**Comment by fgrzadkowski** [comment] 2016-11-17 08:48
Reassigning to Solly to work on e2e tests. Please close it once we cover this problem with proper tests.

**Comment by DirectXMan12** [comment] 2016-11-17 22:07
How are we going to reliably "pretend" to have non-existent metrics in an e2e context?  We can guess/hope/estimate the lag from Heapster, but e2e tests use real results from Heapster, so we can't fake anything there.  Similarly with pending pods.  I can test the readiness logic with a pod with a readiness check that never succeeds, but I uncertain as to the best course of action for the other two parts.

**Comment by fgrzadkowski** [comment] 2016-11-18 10:03
For pending pods you add some constraint where pods can run (e.g. only on a specific node) and how many on each node (e.g. only one). With it should be pretty simple to create pending pods.

For non-existent metrics, maybe we can have somehow break one of the kubelets such that heapster would not be able to read metrics from there?

**Comment by dims** [comment] 2016-11-18 13:27
per comments, this needs tests. so marking as non-release-blocker and leaving 1.5 milestone on. please holler if you disagree :)

**Comment by dims** [comment] 2016-12-09 15:48
@alex-mohr @DirectXMan12 Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by jszczepkowski** [comment] 2016-12-12 08:58
Fixed by  #33735 & #33593.

**Comment by fgrzadkowski** [comment] 2016-12-12 19:54
@jszczepkowski do we have any e2e tests to verify this? In https://github.com/kubernetes/kubernetes/issues/30471#issuecomment-261083725 I suggested adding some e2e tests and I think this requests still stands, unless I missed some PRs.

@DirectXMan12 Did you add e2e tests for those scenarios?

**Comment by jszczepkowski** [comment] 2016-12-13 08:41
We have thorough unittests, but AFAIK e2e tests are not yet implemented.

**Comment by fgrzadkowski** [comment] 2016-12-13 10:38
If you are fine with the current tests, than I'm also ok. But let's make sure this is the case before closing this issue.

**Comment by teddythetwig** [comment] 2017-05-19 13:55
Any updates on this issue?

**Comment by jszczepkowski** [comment] 2017-05-22 11:39
> Any updates on this issue?

Do you mean the feature or e2e tests? The feature (and unittests) are ready. AFAIK, e2e tests are still not implemented.

@DirectXMan12 Do you know if we have e2e tests for this?

**Comment by DirectXMan12** [comment] 2017-05-22 17:55
I don't think we have e2e tests for this yet.  It's on my list of things to get to eventually, but it requires a bit of fiddling to recreate the right circumstances.

**Closed** 2018-02-23 00:31 UTC
Labels: help wanted, lifecycle/rotten, priority/important-soon, sig/autoscaling, team/control-plane (deprecated - do not use)
