### ISSUE TITLE
Etcd watch window expires too often

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#8700] opened 2015-05-22 21:28 UTC
Even after extending/randomizing the server timeout I see too many watch window expirations. This leads to concurrent lists (it has dropped from > 50, to >30 < 50). There are periods when we get one expiration a second, and times when we have > 20 on the same second.

I can boil this down to cpu starvation of the go-etcd watcher:
https://github.com/coreos/go-etcd/blob/master/etcd/watch.go#L39

And reproduce it with:
```
go test -bench BenchmarkPodList -bench-pods 3000 -bench-tasks 100 -bench-quiet 3 -tags 'benchmark'
```
while concurrently setting up a cpu starved watch:
```
func TestEtcdWatch() {
	client := etcd.NewClient()
	var yield sync.Mutex
	go func() {
		for {
			yield.Lock()
			yield.Unlock()
		}
	}()
	go func() {
		if _, err := client.Watch(Key, waitIndex, true, incomingCh, stopCh); err != nil {
			errCh <- err
		}
	}()
	for {
		select {
		case res := <-incomingCh:
			glog.Infof("Got result %v", res)
		case err := <-errCh:
			glog.Fatalf("Got error %v", err)
		}
	}
}

```
I don't think this is s pathological test case. We hammer cpu on our n1-standard-4 master, and in reality we have 100's of open watches (and each of those 3000 pods will send at least 7 events). 

There are a few solutions:
1. Make the etcd watch window a command line parameter and bump it up to 5000. 
2. Etcd server supports stream watching. 
3. We Implement a cache with a custom watch window.

I've tested 1 and it seems to work (haven't investigated tradeoffs of larger window). 2, 3 are probably not going to happen for 1.0. 

@lavalamp @fgrzadkowski @wojtek-t

**Comment by lavalamp** [comment] 2015-05-22 21:34
We have discussed 1 before and it basically is not going to happen-- it increases etcd's memory usage too much IIRC.

2 sounds nice, but I don't know etcd code that well. @xiang90 how hard do you think it would be get etcd to keep watches open and stream results instead of sending one result per watch and then requiring a new connection?

3 is of course difficult.

**Comment by xiang90** [comment] 2015-05-22 21:41
@lavalamp 

Well... etcd now support 2 actually. But it is not tested or fully doced. 
We can explore if you think that is going to solve your problem.

But we do need to note that it is almost the same with solution 1 if the root cause is not network + etcd-client latency... Streaming it simply moves the event to a buffer if the receiver side is still slow.

**Comment by xiang90** [comment] 2015-05-22 21:44
@bprashanth Have you measure the current memory usage for 1.0 goal?

**Comment by bprashanth** [comment] 2015-05-22 21:50
@xiang90 I think streaming will solve it. The problem is scanning: https://github.com/coreos/etcd/blob/471aa1aa896567cf957db00d9d6fab87fdb08f2a/store/watcher_hub.go#L56

I don't mind slow watches, I just don't want to break, and have to relist everything. Of course it is bound to happen sometime, would be nice if we could engineer it so we don't have > 30 concurrent relists in common scenarios.

I recommended increasing the window because when we miss it, we do so by a hairline (eg: `[55553/55550]) [56552]` ). I can measure memory, do you have an idea of how much extra memory increasing the window by a 1000 needs, and are there trade-offs other than memory?

**Comment by bprashanth** [comment] 2015-05-22 21:53
I don't think it's n/w because of my repro test, and because I measured the times of the operations in the client watcher and nothing was *that* bad (sometimes sendRequest did take a second or so, but mostly it was OK)

**Comment by xiang90** [comment] 2015-05-22 21:59
@bprashanth If you always start from a recent index, scanning should not cost a lot... But it may... I have never benchmarked it. 

The server side streaming also needs some fixes... If you want to enable that, yea we can make it happen next week.

**Comment by xiang90** [comment] 2015-05-22 22:05
@bprashanth To be honest, the window of etcd was designed for filling the gaps between to continuous watch with ms level latency. 1000 events should be able to hold 200ms latency. Do you know why the duration between two watches is more than 200ms?

**Comment by bprashanth** [comment] 2015-05-22 22:07
It's not the cost of scanning, it's that many of our watchers *just* miss the StartIndex because the client is starved off cpu and they re-establish the connection for every watch. If we could avoid the scan alltogether by keeping the watch open, we could avoid the thundering herd relist. 

> Do you know why the duration between two watches is more than 200ms?

cpu starvation, our master runs on an n1-standard-4 which has 4 vcpus. See the example test case I have in my first comment.

**Comment by bprashanth** [comment] 2015-05-26 19:05
ref https://github.com/coreos/etcd/issues/2854#issuecomment-105329971

**Comment by smarterclayton** [comment] 2015-05-28 14:01
Why don't we just unify the etcd watch locally?  That means there is only one CPU talking to etcd.

**Comment by smarterclayton** [comment] 2015-05-28 14:02
The hard part there is dealing with slow readers on the API server but it's going to massively reduce TCP and memory overhead

**Comment by lavalamp** [comment] 2015-05-28 17:21
Unifying the watch basically means implementing caching/indexing (because you have to keep a change history). We're gonna have to do it for our next increment of scalability. But it's a lot of work and a big change, so we'd like to do it post 1.0 if we possibly can.

**Comment by bprashanth** [comment] 2015-05-28 17:23
fyi I decided to give streaming support a shot myself https://github.com/coreos/etcd/pull/2879

**Comment by xiang90** [comment] 2015-05-28 17:25
@lavalamp @smarterclayton

etcd has decided to improve the watching stuff fundamentally in v3. Providing O(1M) user driven compacted event history. I hope we do not do some crazy optimization in k8s. Or there might be duplicated work.

**Comment by smarterclayton** [comment] 2015-05-28 17:52
No disagreement - it seems like the real solution to the problem so I would to want to over solve it in another direction.

**Comment by smarterclayton** [comment] 2015-05-28 17:53
Yeah the use case of our apiservers is a lot like the etcd proxy - rather than stream the same changes across 100 watches, coalesce them across a single watch which requires a change window, flow control for slow consumers, bounded memory use, etc.

**Comment by bprashanth** [comment] 2015-05-28 18:18
@smarterclayton i think we should go from reopening the watch from a 100 watchers every event to streaming the events to a 100 watchers, to aggregating the watchers into a single stream. The last optimization is only going to happen post 1.0. @xiang90 if you have a watch api proposal along these lines please share.

**Comment by smarterclayton** [comment] 2015-05-28 18:20
The etcd 3 store changes will let us service the bulk of watches direct from the apiserver in our unified stream, but then fall back to etcd for anything outside our window.  Potentially the etcd stored window can be very large.

**Comment by bgrant0607** [comment] 2016-05-25 06:34
@xiang90 is this still an issue?

**Comment by wojtek-t** [comment] 2016-05-25 07:35
No - we can definitely close it now.

**Closed by wojtek-t** 2016-05-25 07:35 UTC
Labels: dependency/etcd, priority/P1, team/CSI-API Machinery SIG

**Comment by xiang90** [comment] 2016-05-25 16:20
@bgrant0607 @wojtek-t 

Expiring definitely does not happen too often with a few fixes we did. So, yes, this exact issue is resolved.

But for etcd2, the window size is still small. Expiring still can happen in theory. If we switch to etcd3, the root cause should be resolved. We implemented the streaming watch feature @bprashanth proposed. We will do more testing for etcd3 on this.

**Comment by wojtek-t** [comment] 2016-05-25 17:20
What I meant closing this issue is that this small window doesn't cause us problems now (even in large clusters).
