### ISSUE TITLE
unit test flake: TestReflectorResync

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#26087] opened 2016-05-23 17:28 UTC
```
=== RUN   TestReflectorResync
W0523 01:16:49.103080   19754 reflector.go:334] testing/testing.go:473: watch of *api.Pod ended with: expected resync reached
--- FAIL: TestReflectorResync (0.00s)
	reflector_test.go:384: expected exiting from err expected resync reached, got: <nil>
...
FAIL	k8s.io/kubernetes/pkg/client/cache	0.446s
```

**Comment by brendandburns** [comment] 2016-05-23 21:59
Dupe of https://github.com/kubernetes/kubernetes/issues/26058

Closing.

**Closed by brendandburns** 2016-05-23 21:59 UTC
Labels: kind/flake, priority/P1
