### ISSUE TITLE
e2e flakes: various suites fail with "failed to wait for pods running" error

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17931] opened 2015-11-30 08:32 UTC
From time to time we have a red run with errors like:
```
Deployment deployment should scale up and down in the right order

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:41 Expected error: <*errors.errorString | 0xc208517c90>: { s: "failed to wait for pods running: [gave up waiting for pod 'nginx-controller-681vo' to be 'running' after 5m0s]", } failed to wait for pods running: [gave up waiting for pod 'nginx-controller-681vo' to be 'running' after 5m0s] not to have occurred
```
In multiple tests. It is most apparent in soak cluster, but it happens in other suites as well, e.g. run 9668 in e2e-gce

cc @davidopp @dchen1107 @kubernetes/goog-node @wojtek-t

**Comment by lavalamp** [comment] 2015-12-02 18:17
@dchen1107 to delegate?

**Comment by timstclair** [comment] 2015-12-02 18:26
I can take a look at this.

**Comment by timstclair** [comment] 2015-12-03 01:22
In every example I found, the failure was a result of the container runtime going down:
```
Nov 29 10:45:48.995: INFO: Node e2e-gce-minion-3oxv condition 2/2: type: Ready, status: False, reason: "KubeletNotReady", message: "container runtime is down", last transition time: 2015-11-29 10:45:08 -0800 PST
...
Nov 29 10:51:28.927: INFO: Node Info: &{{ } {e2e-gce-minion-3oxv   /api/v1/nodes/e2e-gce-minion-3oxv 6d417210-96c0-11e5-a658-42010af00002 4925 0 2015-11-29 09:41:31 -0800 PST <nil> <nil> map[failure-domain.alpha.kubernetes.io/region:us-central1 failure-domain.alpha.kubernetes.io/zone:us-central1-f kubernetes.io/e2e-b74c5450-96c2-11e5-a76e-42010af01555:42 kubernetes.io/hostname:e2e-gce-minion-3oxv] map[]} {10.245.0.0/24 12760007499200551385 gce://k8s-jkns-e2e-gce/us-central1-f/e2e-gce-minion-3oxv false} {map[cpu:{2.000 DecimalSI} memory:{7863918592.000 BinarySI} pods:{100.000 DecimalSI}]  [{OutOfDisk False 2015-11-29 10:51:19 -0800 PST 2015-11-29 09:41:31 -0800 PST KubeletHasSufficientDisk kubelet has sufficient disk space available} {Ready False 2015-11-29 10:51:19 -0800 PST 2015-11-29 10:50:49 -0800 PST KubeletNotReady container runtime is down}] [{InternalIP 10.240.0.5} {ExternalIP 104.197.75.190}] {{10250}} { 208C13C9-E710-6F21-6A27-A9DF770B7D66 5203ce54-0156-45b6-aecd-9624d0390836 3.16.0-0.bpo.4-amd64 Debian GNU/Linux 7 (wheezy) docker://1.8.3 v1.2.0-alpha.4.152+c1af9dcb7fc11d v1.2.0-alpha.4.152+c1af9dcb7fc11d}}}
```

Unfortunately in all the examples I found, the kubelet logs were not successfully retrieved.

@kubernetes/goog-node I remember we had issues with the runtime going down in the past - were those ever fixed? Is there anything in particular I should look for here?

**Comment by dchen1107** [comment] 2015-12-04 01:47
We have babysitter (supervisord) on the node to notice docker down, and restart it.

Why kubelet logs are not retrieved? @ixdy

**Comment by ixdy** [comment] 2015-12-04 01:57
We should be collecting the kubelet logs. @timstclair can you point me to an instance where they weren't collected?

**Comment by timstclair** [comment] 2015-12-04 02:03
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9712/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9668/

Both have errors in the log like:

```
Nov 29 10:51:30.033: INFO: Unable to retrieve kubelet pods for node e2e-gce-minion-3oxv
```

**Comment by ixdy** [comment] 2015-12-04 02:07
Ah, there are no kubelet logs saved because the builds timed out, and the log collection only happens when we manage to finish running all tests. #10423 is probably the relevant issue.

**Comment by gmarek** [comment] 2015-12-04 09:46
One more reason to add post-run hooks to jenkins.

**Comment by ixdy** [comment] 2015-12-04 19:44
First we need to pull the log-collection code into a separate binary, rather than rolling it into e2e_test.

**Comment by gmarek** [comment] 2015-12-11 13:14
@timstclair Any update on this? It happened again:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12683/

**Comment by timstclair** [comment] 2015-12-11 18:59
There haven't been any updates since I was waiting for it to happen again and successfully collect logs. The sample you linked is what I was waiting for :) I'll do some digging later today.

**Comment by timstclair** [comment] 2015-12-14 22:26
Looked into the failures in 
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12683/. This is another case of the runtime going down (repeatedly). I don't see any hints in the [kubelet log](https://00e9e64bac39281a3d8c364bc8715af4b935927e3d862f1f06-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/logs%2Fkubernetes-e2e-gce-parallel%2F12683%2Fartifacts%2F104.197.244.24:22-kubelet.log?qk=AD5uMEskUiyhPC91_PXKvk5UNmzCm0ZCdVMHz7F2SAqH6uw_UoSuujyq2h6Ffpiw9ez6iY-Icx3KIXl7jhge7egq3RwbhVQGIdWCAktkmMYzw6z6Kjl9ttNhrzjByADVX2QYOFAXVpHdWrygyYHkixEIrq2TbruKh77WPko1kBc50hyzQ28qW-2kRtqhdNSylf_AbYT3y9vF2T7mxeInrf9VplyrK3VW3N8tcEfH-f7ddI4EceqpD4dEUp8AY7fdMMQFIMXFYh2vdBRt0Zb7xE2xf-eGrTqPjnxq4rHpa0QaFtippaPaMaVTO99PjADEbVVXVqCsYCCaz8aLVQXyZgponwa9WsO3_6fh5Vg6vj2RQugbXnU2Xv6-gGJC4AtnJUfiihxBUyf84xVQLy_-nl1C2X_prtMjk9zGO801viBdpP7-tTDulEMGkiE59QkLEUbB6lCtVM27DBwWxxyYAckq7GE564IOVEQlbSKy0oEP7BiLR2ww1WfSaR1eJeOFjkqL3-KCnUsGl7kC57AJZDEee0TGLc1rStpc1memLT20mMDq439jhJXvN_UIWR7TqGzDcRy1wu1M6N1l7DnEAjkZOxI0woNNmK6EqMCjhv3GyN_tuYmHBMbtWl8J58YmPuyYLoi9NsVwcfdNbEesQBmK1x8MBUreuTVGl7_PnALA7YQN0GH5TCgSEV0rTwlWtJqDka8sAlkvLRk0zw_VjL-4tLb5RNG9HpRsT95fca5Rj_bAnCDgSSZyK7gZRIpQzlzt_yB9Wa73qKPrIzV9Kz1jfsqkOuK7PWWMeB98fvz41ewAuMNhnTnsGg41iISQiwxYVa-sJE21FskLb1VPpxov6pee5NPc-3RQ_E193EaGH_Lltb5jIVOgq65NlGLyo0UBAFqCCExx-_IPVh3XTF-hL2MRJgtLznoZEyhxlx_kYAT2fjbt1Tg) as to what's causing it though.

@kubernetes/goog-node any ideas?

**Comment by timstclair** [comment] 2015-12-14 22:37
Also worth mentioning, the kubelet is failing the healthz check:
```
I1211 12:44:11.550732   15039 server.go:1063] GET /healthz: (73.002Âµs) 500
goroutine 238 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc208393420, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:209 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208393420, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
net/http.Error(0x7f52d091bfc8, 0xc208393420, 0xc20867e4e0, 0x58, 0x1f4)
	/usr/src/go/src/net/http/server.go:1274 +0x9a
k8s.io/kubernetes/pkg/healthz.funcÂ·002(0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x46e
net/http.HandlerFunc.ServeHTTP(0xc2083c6ad0, 0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/emicklei/go-restful.funcÂ·011(0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:278 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc2083caa80, 0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2083ada70, 0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc208062d80, 0xa, 0x10, 0xc2083ada70, 0x0, 0x2991ce8, 0x0, ...)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x4f
k8s.io/kubernetes/pkg/kubelet.(*filteringContainer).ServeHTTP(0xc2083caa00, 0x7f52d091bfc8, 0xc208393420, 0xc2083ecc30)
	<autogenerated>:72 +0x8a
k8s.io/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc2083ad9e0, 0x7f52d091bf90, 0xc208598140, 0xc2083ecc30)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server.go:1062 +0x13d
net/http.serverHandler.ServeHTTP(0xc208244240, 0x7f52d091bf90, 0xc208598140, 0xc2083ecc30)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20859 [[curl/7.26.0] 127.0.0.1:49860]
```

**Comment by gmarek** [comment] 2015-12-23 08:20
It happened again: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/a4202cbee9eb362da61cd2c4c74e217ca4fd0bdc/kubernetes-pull-build-test-e2e-gce/21745/build-log.txt

@timstclair - what's the status of this?

**Comment by gmarek** [comment] 2016-01-04 19:35
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10217/

@timothysc please prioritize this

**Comment by timstclair** [comment] 2016-01-05 01:02
It looks like that last failure (http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10217/) was a different issue, caused by a network hiccup:

```
I0104 18:50:19.148491    3368 server.go:806] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-e2e-kubelet-etc-hosts-lwlcu", Name:"test-pod", UID:"00127292-b314-11e5-a88b-42010af00002", APIVersion:"v1", ResourceVersion:"9933", FieldPath:"spec.containers{busybox-1}"}): type: 'Normal' reason: 'Pulling' pulling image "gcr.io/google_containers/netexec:1.0"
I0104 18:50:19.154507    3368 server.go:806] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-e2e-kubelet-etc-hosts-lwlcu", Name:"test-pod", UID:"00127292-b314-11e5-a88b-42010af00002", APIVersion:"v1", ResourceVersion:"9933", FieldPath:"spec.containers{busybox-1}"}): type: 'Warning' reason: 'Failed' Failed to pull image "gcr.io/google_containers/netexec:1.0": API error (500): unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
```

Further down in the logs the network appears to recover (later pulls succeed), but not before the test timed out. I don't know how to further diagnose this issue, but it sounds like maybe it was something out of our control. Maybe someone else from @kubernetes/goog-node can chime in?

It looks like multiple issues are getting lumped together into this one issue since they error message `gave up waiting for pod 'test-pod' to be 'running' after 5m0s` ends up being the same. Maybe the solution to this issue is to provide more informative error messages in this event, so we can more easily see what is a one-off flake vs. a legitamate bug?

**Comment by timstclair** [comment] 2016-01-05 01:11
the previous failure (https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/a4202cbee9eb362da61cd2c4c74e217ca4fd0bdc/kubernetes-pull-build-test-e2e-gce/21745/build-log.txt) looks like something different? The only failure I see there is:
```
â€¢ Failure [39.672 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:42
  deployment should scale up and down in the right order [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:41

  Expected
      <int>: 10
  to equal
      <int>: 2

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:284
```

**Comment by gmarek** [comment] 2016-01-05 07:56
Ah, sorry, I probably had too many tabs open at that point.

**Comment by timstclair** [comment] 2016-01-08 00:24
Another failure, another error, this one also different. I filed a separate issue for this one: https://github.com/kubernetes/kubernetes/issues/19387

**Comment by dchen1107** [comment] 2016-01-21 22:30
Deployment test failures are addressed separately by @janetkuo. And #19391 was merged. I am closing this issue for now.

**Closed by dchen1107** 2016-01-21 22:30 UTC
Labels: kind/flake, priority/P0, team/node
