### ISSUE TITLE
Save logfiles from components even if cluster hadn't started successfully.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18970] opened 2015-12-21 14:49 UTC
We observe failures of 1000-node startups when one or few nodes don't get registered. Because cluster startup fails we don't save any logs from any component, which makes this pretty much impossible to debug.

Setting this a P0, as this blocks debugging of #18969.

cc @ixdy @brendandburns @davidopp @wojtek-t @kubernetes/goog-node @kubernetes/goog-control-plane

**Comment by ixdy** [comment] 2016-01-22 22:07
dupe of #10423

**Closed by ixdy** 2016-01-22 22:07 UTC
Labels: area/performance, priority/P0, team/test-infra
