### ISSUE TITLE
godep restore/save/verify are super slow

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#61449] opened 2018-03-21 01:48 UTC
Filing this just in case someone has a clue. I was trying to update `golang.org/x/sys/unix` package in Kubernetes and I was using instructions @thockin recently updated in https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md but I found that all the steps are super slow. Like 40-50 minutes for restore, 40-50 minutes for save and then about same time for verify.

I am not on bad connection by any means. Wondering if this is because `./run-in-go-path.sh` sets up a new temporary GOPATH and everything has to be cloned. But that still does not explain why verify etc are super slow as well.

**Comment by liggitt** [comment] 2018-03-21 02:33
duplicate of https://github.com/kubernetes/kubernetes/issues/44873
/close

**Closed by liggitt** 2018-03-21 02:33 UTC
Labels: sig/contributor-experience
