### ISSUE TITLE
Unable to create pod in minikube 

### ISSUE THREAD

**Issue by mehmood8** [kubernetes/kubernetes#109327] opened 2022-04-06 05:48 UTC
below is my yml file 

```
kind: Pod
apiVersion: v1
metadata:
  name: testpod4
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80  
```
 kubectl apply -f pod1.yml

error:error validating "ppod.yml" error validation :kind not set; if you choose to ignore these error, turn validation off with --validate=false

**Comment by MadhavJivrajani** [comment] 2022-04-06 09:11
not able to reproduce the error
please provide more info such as version of K8s running etc
/kind support

**Comment by neolit123** [comment] 2022-04-06 17:09
> kubectl apply -f pod1.yml

> error:error validating "ppod.yml"

the error mentions a different file name `ppod.yml` and not `pod1.yml`.
the contents of `ppod.yml` might be missing:

```
kind: Pod
apiVersion: v1
```

looks like a support ticket; going to close this but please reopen if needed and if have more details that confirm an actual bug.

/close

**Closed** 2022-04-06 17:09 UTC
Labels: kind/support, needs-sig, needs-triage
