### ISSUE TITLE
kubectl inside a pod no longer respects the --context parameter

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#38744] opened 2016-12-14 04:12 UTC
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.0

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS Beta channel

**What happened**: We have automation running inside Jenkins in a Kubernetes pod.  With the rollout of 1.5.0, calling `kubectl --context=something get pods` now defaults to the InCluster configuration rather than the desired "something" context and we see the following error: `error: the namespace from the provided object "staging" does not match the namespace "jenkins". You must pass '--namespace=staging' to perform this operation`

**What you expected to happen**: The same as 1.4.6 behavior; kubectl respects the `--context` parameter.

**How to reproduce it** (as minimally and precisely as possible): See above.

**Comment by AdoHe** [comment] 2016-12-14 12:48
@kubernetes/kubectl

**Comment by chrisleck** [comment] 2016-12-14 23:50
I believe this is a breaking change regression and should be bumped up in priority.  This prevents me from driving changes to other clusters from my utility cluster.

**Comment by chrisleck** [comment] 2016-12-16 18:43
I had to roll back to 1.4.7 due to this issue.  Happy to help, but not sure what the desired semantic is here through the twisty maze of config code.

**Comment by pwittrock** [comment] 2016-12-16 22:18
@chrisleck Looks like this is a duplicate of #38834 and is being worked on.

**Comment by chrisleck** [comment] 2016-12-16 22:36
Cool - I'm happy to resolve this as a dup if the other is receiving attention.

**Comment by pwittrock** [comment] 2016-12-17 00:02
SGTM

**Closed by pwittrock** 2016-12-17 00:02 UTC
Labels: area/kubectl, priority/important-soon, sig/cli

**Comment by fabianofranz** [comment] 2016-12-22 03:54
@chrisleck since you mention you are using `--context`, I understand you have a kube config file inside the container. Can you confirm where it is located? `~/.kube/config`, some other location set by the `KUBECONFIG` env var, something else? Tks!

**Comment by chrisleck** [comment] 2016-12-22 04:20
I stuck it in the default location: ~/.kube/config


On Dec 21, 2016 7:54 PM, "Fabiano Franz" <notifications@github.com> wrote:

@chrisleck <https://github.com/chrisleck> since you mention you are using
--context, I understand you have a kube config file inside the container.
Can you confirm where it is located? ~/.kube/config, some other location
set by the KUBECONFIG env var, something else? Tks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/38744#issuecomment-268712555>,
or mute the thread
