### ISSUE TITLE
5k node tests time out waiting for nodes to come up

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56332] opened 2017-11-24 10:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-scalability-bugs 
/priority critical-urgent
umbrella issue: #55194 

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/35 failed with:
```
I1124 00:33:02.423] Nov 24 00:33:01.842: INFO: Unexpected error occurred: timed out waiting for the condition
I1124 00:33:02.423] 
I1124 00:33:02.423] 
I1124 00:33:02.423] Failure [5408.883 seconds]
I1124 00:33:02.424] [BeforeSuite] BeforeSuite 
I1124 00:33:02.424] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:138
I1124 00:33:02.424] 
I1124 00:33:02.425]   Expected error:
I1124 00:33:02.425]       <*errors.errorString | 0xc42037a1c0>: {
I1124 00:33:02.425]           s: "timed out waiting for the condition",
I1124 00:33:02.425]       }
I1124 00:33:02.425]       timed out waiting for the condition
I1124 00:33:02.425]   not to have occurred
I1124 00:33:02.426] 
I1124 00:33:02.426]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:176
```

The failure was waiting for enough nodes to be schedulable:
```
I1124 00:33:02.156] Nov 23 23:02:57.292: INFO: Waiting up to 1h30m0s for all (but 50) nodes to be schedulable
I1124 00:33:02.156] Nov 23 23:07:30.662: INFO: Unschedulable nodes:
[...]
I1124 00:33:02.406] Nov 24 00:32:30.331: INFO: Unschedulable nodes:
I1124 00:33:02.406] Nov 24 00:32:30.331: INFO: -> gce-scale-cluster-minion-group-700b Ready=true Network=false
I1124 00:33:02.407] Nov 24 00:32:30.331: INFO: -> gce-scale-cluster-minion-group-dx9c Ready=true Network=false
[... 70 more...]
```

@shyamjvs did you by any chance turn on the IP aliasing already? If so, then it clearly does not work well enough yet...

**Comment by wojtek-t** [comment] 2017-11-24 10:27
Hmm - this is strange. I downloaded controller manager logs and:
```
wojtekt@wojtekt3:~/Downloads$ cat kube-controller-manager.log-20171124-1511481600 | grep cloud_cidr_allocator | grep "Set node"  | wc -l
5001
```
So it seems it managed to successfully set network condition for all nodes.

So maybe the problem is that something else has overwritten this condition (because it is not using patch - whatever that is), and cidr_allocator will never set it to true again.

@shyamjvs - thouughts?

**Comment by wojtek-t** [comment] 2017-11-24 10:28
BTW - it was pretty fast this time - the difference between first and last setting cidr was ~8 minutes.

**Comment by porridge** [comment] 2017-11-24 10:30
@wojtek-t if you have the log, can you check if all the 5001 log lines refer to 5001 different nodes?

**Comment by shyamjvs** [comment] 2017-11-24 10:36
Just checked the logs.. All the nodes are unique and they were all (except one, but that's fine as we allow a slack) assigned a CIDR by 23:01:10.973363

**Comment by shyamjvs** [comment] 2017-11-24 10:38
And that was all part of the cluster validation which did proceed through:

```
I1123 22:57:00.193] Validating gce cluster, MULTIZONE=
W1123 22:57:00.293] ... calling validate-cluster
W1123 22:57:00.294] Project: kubernetes-scale
W1123 22:57:00.294] Network Project: kubernetes-scale
W1123 22:57:00.294] Zone: us-east1-a
I1123 22:58:05.760] [0;33mWaiting for 5001 ready nodes. 1367 ready nodes, 1563 registered. Retrying.[0m
I1123 22:58:23.457] [0;33mWaiting for 5001 ready nodes. 1545 ready nodes, 1781 registered. Retrying.[0m
I1123 22:58:43.751] [0;33mWaiting for 5001 ready nodes. 1758 ready nodes, 1947 registered. Retrying.[0m
I1123 22:59:03.817] [0;33mWaiting for 5001 ready nodes. 1948 ready nodes, 2266 registered. Retrying.[0m
I1123 22:59:23.905] [0;33mWaiting for 5001 ready nodes. 2266 ready nodes, 2780 registered. Retrying.[0m
I1123 22:59:43.802] [0;33mWaiting for 5001 ready nodes. 2778 ready nodes, 3461 registered. Retrying.[0m
I1123 23:00:37.915] [0;33mWaiting for 5001 ready nodes. 3554 ready nodes, 3985 registered. Retrying.[0m
I1123 23:01:00.429] [0;33mWaiting for 5001 ready nodes. 4874 ready nodes, 4991 registered. Retrying.[0m
I1123 23:01:22.664] [0;32mFound 4951 Nodes, allowing additional 2 iterations for other Nodes to join.[0m
I1123 23:01:22.664] [0;33mWaiting for 5001 ready nodes. 4993 ready nodes, 5001 registered. Retrying.[0m
I1123 23:01:44.279] Found 5001 node(s).
```

This was even before the testing framework started.

**Comment by porridge** [comment] 2017-11-24 10:39
Same with https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/68 but in that case 103 nodes remained without network after 1.5h.

**Comment by porridge** [comment] 2017-11-24 10:42
@shyamjvs what do you refer to as "that" in https://github.com/kubernetes/kubernetes/issues/56332#issuecomment-346797871?

**Comment by shyamjvs** [comment] 2017-11-24 10:43
CIDR assignment

**Comment by porridge** [comment] 2017-11-24 10:46
So you're saying that the validation before test framework starts performs
exactly the same node health check as the one within the framework?
In other words something broke it in between?

**Comment by wojtek-t** [comment] 2017-11-24 10:48
Re checking logs - I don't see any repeated nodes as @shyamjvs wrote. And all nodes are there:
```
wojtekt@wojtekt3:~/Downloads$ cat kube-controller-manager.log-20171124-1511481600 | grep cloud_cidr_allocator | grep "Set node"  | cut -d ' ' -f 13 | sort | uniq | wc -l
5001
```
[BTW - I checked that before sending this comment, I also thought that maybe something was repeated.]

But I think this code is correct (modulo the fact that it seems that something may overwrite the condition and it will never be set to true again).

**Comment by wojtek-t** [comment] 2017-11-24 10:49
I will send out a PR fixing this in few minutes.

**Comment by porridge** [comment] 2017-11-24 10:52
What do you intend to change? Make the cidr alocator re-apply the condition if it's lost? Won't that cause endless tug-of-war and node health flapping?

**Comment by shyamjvs** [comment] 2017-11-24 10:56
@porridge Wrt https://github.com/kubernetes/kubernetes/issues/56332#issuecomment-346799443:

All the nodes has been assigned CIDR by 23:01. And those nodes were then marked ready, which is why the cluster validation step proceeded through fine.
But later before the test suite, we're checking that the nodes are 'Schedulable' (*not* just Ready) which is where it fails.
And the reason is because the nodes' `Network=false` condition is set.
So the question is - Why is the node's network unready even though the CIDR has been allocated to it.

We should be able to find some clue from those nodes' kubelet logs.

@wojtek-t I'm not sure what you're sending out a PR for? (wrt https://github.com/kubernetes/kubernetes/issues/56332#issuecomment-346800221)

**Comment by wojtek-t** [comment] 2017-11-24 10:58
@shyamjvs - My guess is that something overwrote the condition due to not using patch. And if so, it will never be reapplied again.

**Comment by shyamjvs** [comment] 2017-11-24 11:06
I checked in the kubelet logs of http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/35/artifacts/gce-scale-cluster-minion-group-0jbn :

```
E1123 23:05:04.799666    1584 kubenet_linux.go:793] Failed to flush dedup chain: Failed to flush filter chain KUBE-DEDUP: exit status 255, output: Chain 'KUBE-DEDUP' doesn't exist.
I1123 23:05:36.819374    1584 kubelet.go:1285] Image garbage collection succeeded
E1123 23:48:16.097460    1584 kubelet_node_status.go:383] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"KernelDeadlock\"},{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2017-11-23T23:48:16Z\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2017-11-23T23:48:16Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2017-11-23T23:48:16Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2017-11-23T23:48:16Z\",\"type\":\"Ready\"}]}}" for node "gce-scale-cluster-minion-group-0jbn": Operation cannot be fulfilled on nodes "gce-scale-cluster-minion-group-0jbn": there is a meaningful conflict (firstResourceVersion: "1862496", currentResourceVersion: "1868546"):
 diff1={"metadata":{"resourceVersion":"1868546"},"status":{"$setElementOrder/conditions":[{"type":"KernelDeadlock"},{"type":"NetworkUnavailable"},{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2017-11-23T23:48:16Z","type":"KernelDeadlock"}]}}
, diff2={"status":{"$setElementOrder/conditions":[{"type":"KernelDeadlock"},{"type":"NetworkUnavailable"},{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2017-11-23T23:48:16Z","type":"OutOfDisk"},{"lastHeartbeatTime":"2017-11-23T23:48:16Z","type":"MemoryPressure"},{"lastHeartbeatTime":"2017-11-23T23:48:16Z","type":"DiskPressure"},{"lastHeartbeatTime":"2017-11-23T23:48:16Z","type":"Ready"}]}}
```

There seems to be a conflict while patching the node-status. Maybe the conflict is happening b/w kubelet and the cidr-allocator trying to set the node status field.
However what's surprising to me is why were we not seeing this earlier (when we were using range-allocator instead of cloud-allocator - was that doing sth different?)
I'll check.

Also there are no kubelet logs in b/w 23:05 and 23:48 which also is weird.

**Comment by wojtek-t** [comment] 2017-11-24 11:08
Because previously we were creating routes. And route controller is retrying setting the condition if this is set incorrectly in every loop.

**Comment by shyamjvs** [comment] 2017-11-24 11:11
Aah.. that makes sense. I was under the impression that the range-allocator (which was still the one assigning CIDRs to nodes) is also setting a similar node condition to cloud-allocator.
But seems like it's only the route-controller doing it.

**Comment by wojtek-t** [comment] 2017-11-24 11:16
https://github.com/kubernetes/kubernetes/pull/56336 is out for review

**Comment by porridge** [comment] 2017-11-27 08:53
FWIW, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/37 succeeded, guys can you take a look at how node setup went and close this bug if there are no red flags?

**Comment by shyamjvs** [comment] 2017-11-27 13:48
Yeah.. that looks normal. The cluster validation didn't take long:

```
I1125 23:19:30.502] Validating gce cluster, MULTIZONE=
W1125 23:19:30.602] ... calling validate-cluster
W1125 23:19:30.602] Project: kubernetes-scale
W1125 23:19:30.603] Network Project: kubernetes-scale
W1125 23:19:30.603] Zone: us-east1-a
I1125 23:20:37.576] [0;33mWaiting for 5001 ready nodes. 1517 ready nodes, 1645 registered. Retrying.[0m
I1125 23:20:55.523] [0;33mWaiting for 5001 ready nodes. 1628 ready nodes, 1831 registered. Retrying.[0m
I1125 23:21:14.407] [0;33mWaiting for 5001 ready nodes. 1788 ready nodes, 2438 registered. Retrying.[0m
I1125 23:21:33.222] [0;33mWaiting for 5001 ready nodes. 2383 ready nodes, 2751 registered. Retrying.[0m
I1125 23:21:52.610] [0;33mWaiting for 5001 ready nodes. 2751 ready nodes, 2861 registered. Retrying.[0m
I1125 23:23:08.324] [0;33mWaiting for 5001 ready nodes. 2842 ready nodes, 3726 registered. Retrying.[0m
I1125 23:23:29.643] Found 5001 node(s).
```

The time b/w the first node and the last node's CIDR assignment (and also networkUnavailable status update (which is now being retried)) is ~5.5m:

```
I1125 23:17:22.120371       7 cloud_cidr_allocator.go:231] Set node gce-scale-cluster-minion-group-1-32f6 PodCIDR to 10.64.53.0/24
...
I1125 23:23:00.574591       7 cloud_cidr_allocator.go:231] Set node gce-scale-cluster-minion-group-t65t PodCIDR to 10.82.3.0/24
```

Ginkgo did seem to wait for ~10m before starting the parallel nodes (which iirc is due to some BeforeSuite actions), but that seems ok.
Closing this... we can reopen it if we see some issues later.

/close

**Closed by shyamjvs** 2017-11-27 13:48 UTC
Labels: kind/bug, priority/critical-urgent, sig/scalability
