### ISSUE TITLE
Test failure: kubernetes-test-go's TestUDPProxyUpdatePort FAIL k8s.io/kubernetes/pkg/proxy/userspace 300.049s

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#26364] opened 2016-05-26 17:17 UTC
Test failure: kubernetes-test-go's TestUDPProxyUpdatePort FAIL k8s.io/kubernetes/pkg/proxy/userspace 300.049s

https://console.developers.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/12478

I don't see any more useful logs, though, so perhaps AI is to add sufficient logging to figure out what actually happened?  Or maybe log exists and I just don't see it.

**Comment by dims** [comment] 2016-06-06 19:52
Since we don't have much to go on and it has not occured since, do we close this for now?

**Comment by matchstick** [comment] 2016-06-07 02:06
I might try to run the this test in a loop and see how often or if it still occurs.

**Comment by girishkalele** [comment] 2016-06-07 21:15
Running the unit test in parallel 1200 iterations yielded one failure.

``` hack/test-go.sh -p 12 -i 100 pkg/proxy/userspace```
...
```
E0607 14:09:38.968177  116580 proxysocket.go:218] ReadFrom failed, exiting ProxyLoop: read udp [::]:43857: use of closed network connection
E0607 14:09:39.218909  116580 proxysocket.go:292] WriteTo failed: write udp [::]:35756->127.0.0.1:38629: use of closed network connection
E0607 14:09:39.219070  116580 proxysocket.go:238] SetDeadline failed: set udp 127.0.0.1:49782: use of closed network connection
E0607 14:09:39.486255  116580 proxysocket.go:218] ReadFrom failed, exiting ProxyLoop: read udp [::]:35503: use of closed network connection
panic: test timed out after 2m0s
```

See full failure output at https://gist.github.com/girishkalele/e3645d4bbe8eb95f0ee0db3d24649824

**Comment by girishkalele** [comment] 2016-06-07 21:42
@thockin @matchstick 

4 UDP sockets were found closed when not expected to be. Test harness seems to have hung till it panicked after 20 seconds waiting for progress.

**Comment by girishkalele** [comment] 2016-06-07 22:29
proxy/userspace test flakiness is easily reproducible using a shrunken ephemeral port pool. I restricted the pool to a 96 ports range.

'''echo '40000 40096' | sudo tee /proc/sys/net/ipv4/ip_local_port_range'''

**Comment by girishkalele** [comment] 2016-08-28 02:16
Closing because we are not seeing it now - I didn't make any fixes and cannot locate a commit that might have fixed this. Note userspace proxy cleanup (aka removal) is a TODO.

**Closed by girishkalele** 2016-08-28 02:16 UTC
Labels: area/test, flake-needs-czar-attention-release-1.4, kind/flake, priority/P1, team/cluster
