### ISSUE TITLE
kubectl get nodes fails when versions are incompatible 

### ISSUE THREAD

**Issue by SteveLasker** [kubernetes/kubernetes#40441] opened 2017-01-25 19:10 UTC
**Kubernetes version** 
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**: az acs kubernetes install-cli --install-location "C:\Program Files\Kubernetes\kubectl.exe"
- **Others**:

**What happened**:
```
kubectl get nodes
error: group map[federation:0xc082386930 :0xc082386e00 authentication.k8s.io:0xc082386ee0 authorization.k8s.io:0xc082387
030 certificates.k8s.io:0xc0823872d0 componentconfig:0xc082387340 policy:0xc08247e070 apps:0xc082386e70 autoscaling:0xc0
823870a0 batch:0xc082387260 extensions:0xc08247e000 rbac.authorization.k8s.io:0xc0820be070 storage.k8s.io:0xc0820be150]
is already registered
```

**What you expected to happen**:
PS> kubectl get nodes
```
NAME                    STATUS                     AGE
k8s-agent-58d1d89c-0    Ready                      18h
k8s-agent-58d1d89c-1    Ready                      18h
k8s-agent-58d1d89c-2    Ready                      18h
k8s-master-58d1d89c-0   Ready,SchedulingDisabled   18h
```

**How to reproduce it** (as minimally and precisely as possible):
Clean environment. Azure didn't have anything pre-provisioned
```az acs create -n kube1 -g stevelas-kube -d stevelaskube --generate-ssh-keys -l westus --orchestrator-type kubernetes```
```az acs kubernetes install-cli --install-location "C:\Program Files\Kubernetes\kubectl.exe"```

**Anything else do we need to know**:

**Comment by liggitt** [comment] 2017-01-25 21:15
kubectl 1.4 cannot deal with unexpected groups (like federation). this was fixed in kubectl 1.5

**Comment by liggitt** [comment] 2017-01-25 21:17
dupe of https://github.com/kubernetes/kubernetes/issues/39693, I think

**Closed** 2017-02-14 04:06 UTC

**Comment by liggitt** [comment] 2017-02-14 04:08
fixed in https://github.com/kubernetes/kubernetes/pull/36898
