### ISSUE TITLE
kubernetes unable to successfull mount volume in AWS

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [kubernetes/kubernetes#28999] opened 2016-07-15 10:52 UTC
Hello,

   after a node restart kubernetes is not able to be mount a volume successfully. Kubelet logs:

`
Jul 15 10:49:19 ip-172-20-0-107 kubelet[2203]: I0715 10:49:19.294687    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f" (UID: "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:49:19 ip-172-20-0-107 kubelet[2203]: I0715 10:49:19.297190    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f" (UID: "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:49:20 ip-172-20-0-107 kubelet[2203]: I0715 10:49:20.297055    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f" (UID: "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:49:20 ip-172-20-0-107 kubelet[2203]: I0715 10:49:20.299679    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f" (UID: "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:49:25 ip-172-20-0-107 kubelet[2203]: I0715 10:49:25.309368    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f" (UID: "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:49:25 ip-172-20-0-107 kubelet[2203]: I0715 10:49:25.311986    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f" (UID: "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:50:05 ip-172-20-0-107 kubelet[2203]: I0715 10:50:05.023812    2203 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 15 10:50:05 ip-172-20-0-107 kubelet[2203]: I0715 10:50:05.023844    2203 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 15 10:50:05 ip-172-20-0-107 kubelet[2203]: I0715 10:50:05.061022    2203 server.go:959] GET /stats/summary/: (46.28236ms) 200 [[Go-http-client/1.1] 10.244.2.4:50548]
Jul 15 10:50:15 ip-172-20-0-107 kubelet[2203]: I0715 10:50:15.345899    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "2320fbd7-4a77-11e6-9ba9-0e0cbeb16a0f" (UID: "2320fbd7-4a77-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:50:15 ip-172-20-0-107 kubelet[2203]: I0715 10:50:15.348424    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "2320fbd7-4a77-11e6-9ba9-0e0cbeb16a0f" (UID: "2320fbd7-4a77-11e6-9ba9-0e0cbeb16a0f").
ul 15 10:50:35 ip-172-20-0-107 kubelet[2203]: I0715 10:50:35.299234    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f" (UID: "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:50:35 ip-172-20-0-107 kubelet[2203]: I0715 10:50:35.301864    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f" (UID: "6c872046-4a75-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:50:42 ip-172-20-0-107 kubelet[2203]: I0715 10:50:42.323893    2203 container_manager_linux.go:284] Discovered runtime cgroups name: /system.slice/docker.service
Jul 15 10:50:43 ip-172-20-0-107 kubelet[2203]: I0715 10:50:43.324903    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f" (UID: "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:50:43 ip-172-20-0-107 kubelet[2203]: I0715 10:50:43.326891    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f" (UID: "aba6b129-4a6e-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:50:45 ip-172-20-0-107 kubelet[2203]: I0715 10:50:45.329335    2203 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") to pod "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f" (UID: "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f"). Volume is already mounted to pod, but remount was requested.
Jul 15 10:50:45 ip-172-20-0-107 kubelet[2203]: I0715 10:50:45.332028    2203 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-6jqrn" (spec.Name: "default-token-6jqrn") pod "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f" (UID: "037e9c66-4a76-11e6-9ba9-0e0cbeb16a0f").
Jul 15 10:51:05 ip-172-20-0-107 kubelet[2203]: I0715 10:51:05.034630    2203 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 15 10:51:05 ip-172-20-0-107 kubelet[2203]: I0715 10:51:05.034662    2203 conversion.go:128] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 15 10:51:05 ip-172-20-0-107 kubelet[2203]: I0715 10:51:05.055499    2203 server.go:959] GET /stats/summary/: (33.690703ms) 200 [[Go-http-client/1.1] 10.244.2.4:50548]
`

and continues so over and over. I think is the same issue reported here:
https://github.com/kubernetes/kubernetes/issues/27872

Kubernetes version 1.3.0

**Comment by matchstick** [comment] 2016-08-12 00:18
@coffeepac

**Comment by coffeepac** [comment] 2016-08-17 19:37
@matchstick @rootfs I took a look at this today and was unable to repro this behavior in either v1.3.0 or v1.3.5.  I created an AWS EBS volume, a PVC and a PV for it.  Created an app that uses the PVC, spun it up, cordoned off all other nodes and restarted the node with the pod running.  The pod has some internal state (a counter) which reset once the counter page was available after the reboot.

I do not think this is related to the linked issue, #27872.  That issue deals explicitly with an EBS volume and this deals with a secrets mount, which is kubernetes internal I think.  This also means my test probably wasn't real valid.  

I am a bit hesitant to call this 'Fixed' as i couldn't repro it with the listed version. 

@sp-joseluis-ledesma can you repro this in v1.3.5 or can you provide OS version and I can try to repro again.

**Comment by blurrcat** [comment] 2016-10-20 10:36
@sp-joseluis-ledesma how did you provision the cluster? I'm experiencing the same problem and I'm using kube_aws. Can that be the problem?

**Comment by coffeepac** [comment] 2016-10-20 12:28
@blurrcat hello!  I tried to chase this down and got nowhere. Do you mind doing a quick write-up of both how you provisioned the cluster (I'm not familiar with kube_aws so any specific flags or custom configs) and what version of kubernetes you are running?

**Comment by sp-joseluis-ledesma** [comment] 2016-10-20 13:05
Sorry, didn't have time to test it. I used kube-up.sh script with the following environment vars:
`
export KUBERNETES_PROVIDER=aws
export release=v1.3.0
export release_url=https://storage.googleapis.com/kubernetes-release/release/${release}/kubernetes.tar.gz

export KUBE_AWS_INSTANCE_PREFIX="lab-k8s"
export KUBE_OS_DISTRIBUTION=wily
export KUBE_AWS_ZONE=us-east-1a
export AWS_S3_REGION=us-east-1
export AWS_S3_BUCKET=kubernetes-bucket
export NODE_SIZE=r3.large
export MASTER_SIZE=m3.medium
`

regards,

**Comment by coffeepac** [comment] 2016-10-20 15:54
thanks @sp-joseluis-ledesma have you seen this issue show up in any later versions of kubernetes?  1.3 is up to 1.3.7 and 1.4 is GA

**Comment by blurrcat** [comment] 2016-10-21 03:04
Hi @coffeepac! Here's my setup:
* kubernetes 1.3.6(GitCommit:f6f005)
* setup with [kube-aws](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html) 0.8.2 on AWS.
* The OS is CoreOS stable (1122.2.0), running flannel, without Calico

kubelet is constantly re-mounting secret volumes:
```
MountVolume operation started for volume "kubernetes.io/secret/...Volume is already mounted to pod, but remount was requested.
MountVolume.SetUp succeeded for volume "kubernetes.io/secret/..
```
And occasionally:
```
Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/... device or resource busy
```
I think the problem may be that when I try to resize one of the worker nodes, I forgot to drain it before restarting it. Now all three nodes, including the master, are experiencing this problem.

**Comment by coffeepac** [comment] 2016-10-25 00:12
@blurrcat @sp-joseluis-ledesma I was unable to recreate this issue at Kubernetes 1.3.6 and stable CoreOS 1122.2.0 using kube-aws and doing a simple reboot.  I don't really have time to go any deeper into experimental repro steps.

Do you have the option of moving to 1.3.7 or 1.4.4?  Both versions will contain a number of storage related fixes, especially 1.4.4

**Comment by matchstick** [comment] 2016-10-25 00:19
@saad-ali @jingxu97 Agreement with @coffeepac  we did put a lot of fixes an dI know some of them may have impacted secretes, saad and jing should be able to weigh in here

**Comment by saad-ali** [comment] 2016-10-25 00:40
The `Volume is already mounted to pod, but remount was requested` message is not an error and is part of the normal operation of ephemeral volumes (like secrets)--it is the mechanism by which kubelet keeps the contents of the secret volume up to date. In a recent PR we've lowered the priority of the message so it is not printed in normal flow.

Can you describe more specifically what is not working as expected? Is there a pod failing to start?

There were known issues in the v1.3.0 that could prevent mounts of secrets to a pod if the secret got stuck unmounting from another pod. These issues were fixed in v1.3.4, with more storage fixes in v1.3.6. Since then, like Michael mentioned there have been a lot more fixes in storage, so if you can please try the newest version (1.4.4), that would be great!

**Comment by blurrcat** [comment] 2016-10-25 06:12
@saad-ali Thanks for your time! I have created a 1.4.3 cluster with kube-aws and the problem is gone!

**Comment by gleeb** [comment] 2016-11-25 21:31
Experiencing the same problem with kube_aws, kubernetes 1.4.3 but not with secret, with EBS PVC. it seems that something is stuck, and K8S is unable to release the volume from the EC2 instance and/or assign it to a pod again. I have not yet identified how to recreate the problem but i suspect it happens after the node works at 100% cpu for awhile, i "fixed" the problem once by actually terminating the node, which released the volume, and another by deleting the PV and recreating it (which is defiantly not a solution). as well force detaching the volume from AWS console didn't help.

**Comment by coffeepac** [comment] 2016-11-28 18:37
@gleeb your issue is unrelated to secret mounts.  can you please open up a fresh bug with repro steps?  its going to get lost here.

**Comment by coffeepac** [comment] 2016-11-28 18:39
@blurrcat you can increase the verbosity of a k8s daemon by passing in the flag '-v4'.  that method requires a restart.  I don't know of a way to reset the logging level dynamically.

additionally, your CPU issue seems to be unrelated to the original issue with secrets.  if you would like to open a perf/benchmark issue that would be awesome but this is not the ticket for it.

**Comment by coffeepac** [comment] 2016-11-28 18:40
@saad-ali @matchstick is there any reason to leave this open?  the original problem has been resolved.

I can't close this issue myself either, so I'll need a hand with that.

**Comment by saad-ali** [comment] 2016-12-03 06:34
@coffeepac Agreed, closing this issue. @blurrcat, 1.5.0 is coming out in the next week or 2. Give that a shot, and if you are still experiencing performance issues, please open a new bug with your data.

**Closed by saad-ali** 2016-12-03 06:34 UTC
Labels: area/platform/aws, area/storage, component/kubelet, priority/P1, team/node, team/sig-aws
