### ISSUE TITLE
kubernetes-soak-continuous-e2e-gce-1.1 broken on SchedulerPredicates tests

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16828] opened 2015-11-05 00:50 UTC
kubernetes-soak-continuous-e2e-gce-1.1 is broken on three tests:

```console
SchedulerPredicates validates MaxPods limit number of pods that are allowed to run

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:179
Expected error:
    <*errors.errorString | 0xc2092cda80>: {
        s: "Namespace e2e-tests-deployment-jwetj is active",
    }
    Namespace e2e-tests-deployment-jwetj is active
not to have occurred


SchedulerPredicates validates that NodeSelector is respected [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:179
Expected error:
    <*errors.errorString | 0xc208b0c110>: {
        s: "Namespace e2e-tests-deployment-jwetj is active",
    }
    Namespace e2e-tests-deployment-jwetj is active
not to have occurred


SchedulerPredicates validates resource limits of pods that are allowed to run [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:179
Expected error:
    <*errors.errorString | 0xc20953faa0>: {
        s: "Namespace e2e-tests-deployment-jwetj is active",
    }
    Namespace e2e-tests-deployment-jwetj is active
not to have occurred
```

This is P0 for an explanation we're comfortable with, then we can decide if we want to patch.

It looks like the namespace is refusing to delete because it's active.  Haven't been able to debug further.

**Comment by brendandburns** [comment] 2015-11-13 18:32
Is someone owning this?  We are leaking here...

**Comment by gmarek** [comment] 2015-11-16 14:53
Sorry, I was on vacation.

My best guess is that it's caused by the timeout of a jenkins suite. When suite times out no 'after-each' is called and namespace that was used for tests are left dangling. This is not a problem for ordinary tests, as we recreate clusters either way, but it's a problem for soak ones. I think that the simplest solution for it is to add a plugin to Jenkins which allows running some scripts post-runs to do this cleanup in case of a timeout. @ixdy @brendandburns @ihmccreery 

- currently builds are failing with 'Namespace e2e-tests-downward-api-7e90b is active' error (well, now there's something more, but were failing with this error recently)
- `e2e-tests-downward-api-7e90b` was created in run 317 which timed out:
```
Downward API volume 
  should provide labels and annotations files [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:94
[BeforeEach] Downward API volume
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
STEP: Creating a kubernetes client
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-soak-weekly-deploy-gce-1.1/workspace/.kube/config
STEP: Building a namespace api object
Nov 12 12:13:39.538: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-downward-api-7e90b
Nov 12 12:13:39.540: INFO: Get service account default in ns e2e-tests-downward-api-7e90b failed, ignoring for 2s: serviceaccounts "default" not found
Nov 12 12:13:41.543: INFO: Service account default in ns e2e-tests-downward-api-7e90b with secrets found. (2.005297933s)
STEP: Waiting for a default service account to be provisioned in namespace
Nov 12 12:13:41.543: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-downward-api-7e90b
Nov 12 12:13:41.545: INFO: Service account default in ns e2e-tests-downward-api-7e90b with secrets found. (2.195249ms)
[It] should provide labels and annotations files [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:94
STEP: Creating a pod to test downward API volume plugin
Nov 12 12:13:41.600: INFO: Waiting up to 5m0s for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 status to be success or failure
Nov 12 12:13:41.608: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:41.608: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (8.007453ms elapsed)
Nov 12 12:13:43.612: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:43.612: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (2.011723864s elapsed)
Nov 12 12:13:45.615: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:45.615: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (4.015227332s elapsed)
Nov 12 12:13:47.621: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:47.621: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (6.021268997s elapsed)
Nov 12 12:13:49.639: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:49.639: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (8.038617632s elapsed)
Nov 12 12:13:51.649: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:51.649: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (10.049197648s elapsed)
Nov 12 12:13:53.653: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:53.653: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (12.052881342s elapsed)
Nov 12 12:13:55.657: INFO: No Status.Info for container 'client-container' in pod 'metadata-volume-de2197b1-8979-11e5-ac87-42010af01555' yet
Nov 12 12:13:55.657: INFO: Waiting for pod metadata-volume-de2197b1-8979-11e5-ac87-42010af01555 in namespace 'e2e-tests-downward-api-7e90b' status to be 'success or failure'(found phase: "Pending", readiness: false) (14.056568548s elapsed)
Build timed out (after 240 minutes). Marking the build as aborted.
Build timed out (after 240 minutes). Marking the build as failed.
```

**Comment by ixdy** [comment] 2015-11-18 01:25
Would cherry-picking #17392 fix this?

**Comment by gmarek** [comment] 2015-11-18 08:32
Probably. The problem that may appear is that the time used for deleting this namespace will be accounted for the current test. As long as it's not a heavy test it's OK, but if something would need to clean up after density, or something similar, we're screwed.

**Comment by ixdy** [comment] 2015-11-30 21:05
#17670 has been merged. Rebuilding the 1.1 soak cluster now to see if it helps.

**Comment by ixdy** [comment] 2015-12-01 20:04
1.1 soak cluster has been healthy since I rebuilt it, with the exception of early this morning, when tests were broken because e2e tests tried to run while the cluster was being redeployed. Job blocking was not configured correctly, but I've since fixed that.

**Closed by ixdy** 2015-12-01 20:04 UTC
Labels: kind/flake, priority/P0, team/cluster
