### ISSUE TITLE
imagePullPolicy is required on Init Containers within a Pod template

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#38542] opened 2016-12-10 01:04 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* initContainers imagePullPolicy
* initContainers required value

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.3", GitCommit:"35fd1363821b8432ccde55632cf9ead4c79eddbb", GitTreeState:"clean", BuildDate:"2016-12-08T21:58:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.3", GitCommit:"35fd1363821b8432ccde55632cf9ead4c79eddbb", GitTreeState:"clean", BuildDate:"2016-12-08T21:54:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: cluster/kube-up.sh
- **Others**:

**What happened**:

When trying to create either a ReplicaSet or Replication Controller whose Pod template contains an Init Container, the validation fails saying `imagePullPolicy` is a required value.

```
The ReplicaSet "nginx" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```

```
The ReplicationController "nginx" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```

**What you expected to happen**:

The create should succeed and the Init Container should receive a default `imagePullPolicy`.

**How to reproduce it** (as minimally and precisely as possible):

Try to create either of the following:

**ReplicaSet**

```yaml
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "busybox",
                "command": ["wget", "-O", "/work-dir/index.html", "http://kubernetes.io/index.html"],
                "volumeMounts": [
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
```

**Replication Controller**

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "busybox",
                "command": ["wget", "-O", "/work-dir/index.html", "http://kubernetes.io/index.html"],
                "volumeMounts": [
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
```

**Anything else do we need to know**:

If I add `"imagePullPolicy": "IfNotPresent",` to the Init Container in the ReplicaSet or Replication Controller Pod template, the create succeeds.

When I create an Init Container without `imagePullPolicy` in a StatefulSet Pod template, it succeeds.

When I create an Init Container without `imagePullPolicy` in a bare Pod, it succeeds:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "install",
            "image": "busybox",
            "command": ["wget", "-O", "/work-dir/index.html", "http://kubernetes.io/index.html"],
            "volumeMounts": [
                {
                    "name": "workdir",
                    "mountPath": "/work-dir"
                }
            ]
        }
    ]'
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
```

**Comment by enisoc** [comment] 2016-12-10 01:15
@kubernetes/sig-api-machinery @caesarxuchao

**Comment by smarterclayton** [comment] 2016-12-10 02:48
Looks like defaulting not being applied on server?  That is probably due to removing defaulting from convert.  Surprised we didn't catch this earlier

**Comment by gajus** [comment] 2016-12-29 12:02
Any reason this isn't being merged?

**Comment by smarterclayton** [comment] 2017-01-05 02:19
Some values still not being defaulted

**Comment by k82cn** [comment] 2017-01-05 02:27
@smarterclayton , I'm going to create a PR if none works on it.

**Comment by k82cn** [comment] 2017-01-09 03:43
We decode from bytes, set defaults and then convert; but for init containers, we delay the decode from "decode phase" to "convert phase" at `Convert_v1_PodTemplateSpec_To_api_PodTemplateSpec`. 

The defaults has been handled for initContainer at https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/zz_generated.defaults.go#L194 . 

/cc @smarterclayton @hongchaodeng 

I'm working to find a solution for that; if any suggestion, please let me know.

**Comment by williamsandrew** [comment] 2017-01-10 22:44
Would this bug affect the deletion of jobs with an init-container? I ran into this bug and adjusted my manifest to add the pull policy to the init-container. However, I now cannot delete said job. Example:

```
$ kubectl delete jobs --all
error: Scaling the resource failed with: Job.batch "gem-repo-populate" is invalid: spec.template: Invalid value: {"metadata":{"name":"gem-repo-populate","creationTimestamp":null,"labels":{"controller-uid":"72bc92ae-d777-11e6-816d-525400bd971e","job-name":"gem-repo-populate"}},"spec":{"volumes":[{"name":"workdir","emptyDir":{}}],"containers":[{"name":"populate","image":"example.com:443/ruby_gcc:latest","command":["sh","-c","cd /workdir/mon-agent-repo \u0026\u0026 gem install httparty --no-ri --no-rdoc \u0026\u0026 bundle install \u0026\u0026 ./build_gems.sh \u0026\u0026 ./checktype_dep_resolve.rb"],"env":[{"name":"GEMINABOX_USERNAME","valueFrom":{"secretKeyRef":{"Name":"geminabox","key":"username"}}},{"name":"GEMINABOX_PASSWORD","valueFrom":{"secretKeyRef":{"Name":"geminabox","key":"password"}}},{"name":"GEM_HOST","value":"gem-repo"},{"name":"HTTP_PROTO","value":"http"},{"name":"WATCHER_API_URL","value":"http://nginx:81"},{"name":"WATCHER_REPO_URL","value":"http://gem-repo/ruby"},{"name":"AUTH_TOKEN","valueFrom":{"secretKeyRef":{"Name":"eb-check-repo-credentials","key":"token"}}}],"resources":{},"volumeMounts":[{"name":"workdir","mountPath":"/workdir"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Never","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"","securityContext":{},"imagePullSecrets":[{"Name":"registry"}]}}: field is immutable; Current resource version 2255
zsh: exit 1     kubectl delete jobs --all
```

**Comment by k82cn** [comment] 2017-01-10 23:40
@williamsandrew , not sure now. Let me check it,

**Comment by gregbkr** [comment] 2017-01-16 17:45
Same error here with version 1.5.1, 1.5.2

    The Job "grafana-import-dashboards" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value

With this setup: 

    kubectl apply -f monitoring

https://github.com/gregbkr/kubernetes-kargo-logging-monitoring/blob/master/monitoring/grafana-import-dashboards-job.yaml

Not working even if I specify a pullpolicy in the yaml. 
If I roll back to 1.4.7, it is working.

Thank you.
Greg.

**Comment by calebamiles** [comment] 2017-01-30 20:54
@k82cn, any updates on a PR to address this issue? Is anyone from @kubernetes/sig-api-machinery-misc able to pick this issue up otherwise?

**Comment by k82cn** [comment] 2017-01-31 00:45
@calebamiles , here's the latest status: there's is a PR to generate `DecodeNestedObjects` for each Object (https://github.com/kubernetes/gengo/pull/38), it works for Object (Pod, Job) now but List; I'm working to make it generating `DecodeNestedObjects` for List.

**Comment by smarterclayton** [comment] 2017-01-31 01:32
Why would you need List to work?  No client side logic should be decoding lists except as a generic submission.

**Comment by k82cn** [comment] 2017-01-31 01:49
The List tests are failed in `pkg/api/serialization_test.go`.

**Comment by calebamiles** [comment] 2017-01-31 15:42
Thanks for the update @k82cn!

**Comment by fluential** [comment] 2017-02-27 10:48
+1

**Comment by elicox** [comment] 2017-03-07 03:39
Any update on this? I still getting this issue with the last version of 1.5.3 on GKE?

**Comment by k82cn** [comment] 2017-03-07 03:45
> Any update on this? I still getting this issue with the last version of 1.5.3 on GKE?

ping @smarterclayton  for the comments? should we merge the PR for 1.5?

**Comment by k82cn** [comment] 2017-03-08 01:35
@elicox , there's a PR that handled that issue; but we're discussing not to merge it because initContainers had been moved to fields, and fields is the recommended way to use since 1.6. But  I'd like to get  @smarterclayton & @liggitt 's comments on 1.5.

**Comment by cortopy** [comment] 2017-03-09 11:35
This is still an issue in 1.5.3 when using annotations:

```
annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "imagePullPolicy": "Always",
            "securityContext": {
              "privileged": true
            }
          }
        ]'
```

Without `imagePullPolicy` the deployment would not be accepted

**Comment by k82cn** [comment] 2017-03-09 11:45
ping @smarterclayton & @liggitt  :).

**Comment by krmayankk** [comment] 2017-03-23 23:35
i dont think this is fixed in 1.5 I just encountered this bug on 1.5.3

**Comment by k82cn** [comment] 2017-03-24 01:14
@krmayankk , yes, the PR is NOT merged to any branch, so the issue is still here. I'll create a PR for 1.5.

**Comment by ramachittala** [comment] 2017-04-04 17:50
Hi Anyone help this issue.
#cat mongo-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mongo-svc-a
  name: mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - mountPath: "/data/db"
            name: mongopv
      volumes:
        - name: mongopv
          persistentVolumeClaim:
            claimName: mongopvc

When i want create mongo db container by using this file folowing error is occured.
# kubectl create -f mongo-pod.yml
The Pod "mongo-deployment" is invalid:spec.containers: Required value

**Comment by k82cn** [comment] 2017-04-05 01:38
@ramachittala , it seems there're two `spec` here, please remove the first one and have a try.

```
spec:
replicas: 1
template:
metadata:
labels:
name: mongo
spec:
containers:
- image: mongo
name: mongo
```

**Comment by ramachittala** [comment] 2017-04-05 19:03
@k82cn 
Hi my kubectl binary is configured at ubuntu 16.04 machine.
# kubectl get nodes
NAME            LABELS                                 STATUS
10.1.10.1   kubernetes.io/hostname=10.1.10.1  Ready,SchedulingDisabled
10.1.10.2   kubernetes.io/hostname= 10.1.10.2  Ready
10.1.10.3  kubernetes.io/hostname=10.1.10.3   Ready

- apiVersion: v1
  kind: Node
  metadata:
    creationTimestamp: 2017-03-03T14:41:52Z
    labels:
      kubernetes.io/hostname: 10.1.10.1
    name: 10.1.10.1
    resourceVersion: "858814"
    selfLink: /api/v1/nodes/10.1.10.1
    uid: 8a8e3c73-001f-11e7-8e83-0ebfb2cf4826
  spec:
    externalID: 10.1.10.1
  status:
    addresses:
    - address: 10.1.10.1
      type: LegacyHostIP
    - address: 10.1.10.1
      type: InternalIP
    capacity:
      cpu: "2"
      memory: 4041352Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: 2017-04-05T18:58:42Z
      lastTransitionTime: 2017-03-03T14:41:52Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
    - lastHeartbeatTime: 2017-04-05T18:58:42Z
      lastTransitionTime: 2017-04-05T15:27:52Z
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    nodeInfo:
      bootID: da52d21b-6124-4ac7-ab96-b196fefdca8c
      containerRuntimeVersion: docker://1.12.6
      kernelVersion: 4.9.16-coreos-r1
      kubeProxyVersion: v1.2.4+coreos.1
      kubeletVersion: v1.2.4+coreos.1
      machineID: 08cbb04332c9488fb5164c541b0136bd
      osImage: Container Linux by CoreOS 1298.7.0 (Ladybug)
      systemUUID: C3FD9852-2DFB-21F4-CE07-2597A746D99D

When i create pv for creation pod is shows pv is pending.
Please give any suggestions.....

**Closed** 2017-05-07 06:03 UTC
Labels: kind/bug, sig/api-machinery

**Comment by kallmekunal** [comment] 2020-11-11 09:45
Is there solution of this problem with version 2.7.
Still facing the same.
what exactly expectation of helm upgrade --install relname chartsdirectory
is is expected to work on first time installation in case with CI/CD Pipelines.
