### ISSUE TITLE
test-cmd flake: kubectl rollout pause deployments --recursive

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#25645] opened 2016-05-16 05:44 UTC
```
FAIL!
Get deployment {{range.items}}{{.spec.paused}}:{{end}}
  Expected: true:true:
  Got:      <no value>:true:
(B
1090 ./hack/test-cmd.sh
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25221/kubernetes-pull-test-unit-integration/25998/

**Comment by nikhiljindal** [comment] 2016-05-16 15:56
cc @janetkuo

**Comment by fejta** [comment] 2016-05-23 23:11
Assigning to @janetkuo per test-cmd.sh

**Comment by mikedanese** [comment] 2016-05-24 18:56
Flaked again https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26190/kubernetes-pull-test-unit-integration/27676/

**Comment by janetkuo** [comment] 2016-05-25 00:31
The flake actually happens when pausing the deployment. Changing issue title.

**Comment by janetkuo** [comment] 2016-05-25 00:43
When `kubectl rollout pause -f hack/testdata/recursive/deployment --recursive`, sometimes one of the deployments isn't paused. 

cc @metral @kargakis

**Comment by metral** [comment] 2016-05-25 01:37
I can't access the internal Google logs to examine the cause, nor can I reproduce this issue locally. Is there any additional information that you can provide to help troubleshoot the flake?

**Comment by metral** [comment] 2016-05-25 04:52
I've gone ahead and attempted a fix for this in https://github.com/kubernetes/kubernetes/pull/26243

**Comment by kargakis** [comment] 2016-05-25 08:05
We should fix this in https://github.com/kubernetes/kubernetes/issues/20437 eventually

**Comment by janetkuo** [comment] 2016-05-25 17:06
@metral the external links are here (`s/pantheon.corp/console.cloud`):
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25221/kubernetes-pull-test-unit-integration/25998/
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26190/kubernetes-pull-test-unit-integration/27676/

**Closed** 2016-05-26 02:49 UTC
Labels: kind/flake, priority/P1, team/ux
