### ISSUE TITLE
flake: pull-kubernetes-federation-e2e-gce federation-up.sh fails

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#46937] opened 2017-06-04 17:11 UTC
Occasionally we see that the pre-submit tests of federation `pull-kubernetes-federation-e2e-gce` fails in `./federation/cluster/federation-up.sh`. Here is the excerpts from one such failure
```
W0602 20:03:08.914] F0602 20:03:08.913648    3570 helpers.go:120] error: service account already exists in joining cluster
W0602 20:03:08.918] 2017/06/02 20:03:08 util.go:131: Step './federation/cluster/federation-up.sh' finished in 1m40.75685465s
W0602 20:03:08.918] 2017/06/02 20:03:08 e2e.go:410: Dumping Federation logs to: /workspace/_artifacts
W0602 20:03:08.918] 2017/06/02 20:03:08 util.go:129: Running: ./federation/cluster/log-dump.sh /workspace/_artifacts
W0602 20:03:08.970] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0602 20:03:08.970] Zone: us-central1-f
I0602 20:03:09.070] Dumping Federation and DNS pod logs to /workspace/_artifacts
W0602 20:03:14.350] 2017/06/02 20:03:14 util.go:131: Step './federation/cluster/log-dump.sh /workspace/_artifacts' finished in 5.431348858s
W0602 20:03:14.350] 2017/06/02 20:03:14 util.go:129: Running: ./federation/cluster/federation-down.sh
W0602 20:03:14.403] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0602 20:03:14.403] Zone: us-central1-f
I0602 20:03:14.707] Cleaning Federation control plane objects
I0602 20:03:15.024] pod "e2e-f8n-agent-pr-93-0-apiserver-348672285-938ws" deleted
I0602 20:03:15.059] pod "e2e-f8n-agent-pr-93-0-controller-manager-2186558600-c0bh8" deleted
I0602 20:03:15.300] service "e2e-f8n-agent-pr-93-0-apiserver" deleted
I0602 20:03:18.464] deployment "e2e-f8n-agent-pr-93-0-apiserver" deleted
I0602 20:03:21.575] deployment "e2e-f8n-agent-pr-93-0-controller-manager" deleted
I0602 20:03:21.880] persistentvolumeclaim "e2e-f8n-agent-pr-93-0-apiserver-etcd-claim" deleted
I0602 20:03:21.912] persistentvolume "pvc-17ecc7f9-4809-11e7-b884-42010a80000a" deleted
I0602 20:03:21.929] pod "e2e-f8n-agent-pr-93-0-apiserver-348672285-gb0rp" deleted
I0602 20:03:21.942] pod "e2e-f8n-agent-pr-93-0-controller-manager-2186558600-c0bh8" deleted
I0602 20:03:21.996] secret "default-token-fw7k4" deleted
I0602 20:03:22.057] secret "e2e-f8n-agent-pr-93-0-apiserver-credentials" deleted
I0602 20:03:22.087] secret "e2e-f8n-agent-pr-93-0-controller-manager-kubeconfig" deleted
I0602 20:03:22.114] secret "federation-controller-manager-token-mqn7v" deleted
I0602 20:03:22.393] namespace "f8n-system-agent-pr-93-0" deleted
I0602 20:03:33.190] +++ [0602 20:03:33] Waiting for 2 minutes to allow controllers to clean up federation components...
W0602 20:05:33.194] 2017/06/02 20:05:33 util.go:131: Step './federation/cluster/federation-down.sh' finished in 2m18.843064428s
W0602 20:05:33.194] 2017/06/02 20:05:33 none.go:41: Noop Down()
W0602 20:05:33.263] 2017/06/02 20:05:33 main.go:161: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0602 20:05:33.263] 2017/06/02 20:05:33 main.go:195: Something went wrong: error starting federation: error during ./federation/cluster/federation-up.sh: exit status 255
```

It looks like the service account representing the k8s cluster which is to be joined to federation already exist. maybe the uniqueness of service account names is not that unique in the cases where it is failing.

Some instances of failures where it happened. 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45251/pull-kubernetes-federation-e2e-gce/8528/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46672/pull-kubernetes-federation-e2e-gce/8518/

/assign @perotinus 
/cc @madhusudancs @kubernetes/sig-federation-bugs

**Comment by mbohlool** [comment] 2017-06-05 06:01
fails #46734

**Comment by shashidharatd** [comment] 2017-06-06 07:00
There could be multiple reasons why `./federation/cluster/federation-up.sh` could fail. One other reason could be that `gcr.io` service is temporarily down. Here is an example of such a failure. 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46979/pull-kubernetes-federation-e2e-gce/9117/?log#log
```
W0605 21:18:36.221] Error from server (BadRequest): container "apiserver" in pod "e2e-f8n-agent-pr-93-0-apiserver-2905553699-lg7b8" is waiting to start: trying and failing to pull image
```

**Comment by shashidharatd** [comment] 2017-06-06 09:21
Just analyzed that its not the gcr.io going down temporarily but the mismatch between the pushed hyperkube image version and the one which is used for federation-up.sh. Filing a separate issue for this.

**Comment by marun** [comment] 2017-06-12 20:52
@shashidharatd Should this issue be blocking 1.7?

**Comment by quinton-hoole** [comment] 2017-06-12 22:11
Replaced by #47032, where the root cause has been determined.  Closing this one.

**Closed by quinton-hoole** 2017-06-12 22:11 UTC
Labels: kind/bug, kind/flake, priority/critical-urgent, queue/blocks-others, sig/federation

**Comment by madhusudancs** [comment] 2017-06-12 22:57
@quinton-hoole just for posterity, this issue and #47032 are completely unrelated. But happy to close this one. I hope this isn't be a problem anymore with all the work @perotinus has done.

/cc @perotinus
