### ISSUE TITLE
Cannot assign service ip address manually

### ISSUE THREAD

**Issue by danrjohnson** [kubernetes/kubernetes#37829] opened 2016-12-01 16:29 UTC
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant
- **OS** (e.g. from /etc/os-release): ubuntu-14.04
- **Kernel** (e.g. `uname -a`): Linux dev-master01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Manual
- **Others**:

**What happened**:

I have `--service-cluster-ip-range=198.168.100.0/24`
When I attempt to create a service with a predefined clusterIP, I get the following:

```The Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "192.168.100.13": provided IP is not in the valid range```

If I remove the clusterIP from the service definition, it creates a service inside the valid range...

```NAME       CLUSTER-IP        EXTERNAL-IP   PORT(S)         AGE
kube-dns   198.168.100.186   <none>        53/UDP,53/TCP   6s
```

**What you expected to happen**:
It would consider an address from inside that range to be valid

**Comment by danrjohnson** [comment] 2016-12-01 18:16
It looks like this might be a problem with the network size.  A `/16` address works fine

**Comment by xiangpengzhao** [comment] 2017-06-17 17:25
are you still facing this? `192.168.100.13` is a valid IP in `198.168.100.0/24`. It's odd that the validation failed.I will try to reproduce this and dig into it.
/sig network

**Comment by xiangpengzhao** [comment] 2017-06-26 09:33
I can't reproduce this on v1.5.1. We are going to close this. Feel free to reopen if you still face this on the latest version.

/cc @thockin

**Closed** 2017-06-28 13:39 UTC
Labels: sig/network
