### ISSUE TITLE
Fail to get rootfs information unable to find data for container /

### ISSUE THREAD

**Issue by duffqiu** [kubernetes/kubernetes#58217] opened 2018-01-12 16:28 UTC
Hi all,

I use systemd to start kubelet,
but log show these error:

```
Jan 12 15:34:42 centos3 kubelet[6623]: E0112 15:34:42.401593    6623 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
```

but I still can create the pod successfully.
anyone can help?

the version is 1.9

/sig Apps

**Comment by shenshouer** [comment] 2018-01-15 04:39
error log from kubelet v1.9.1:

```
Jan 15 12:36:53 l23-27-101 kubelet[7335]: E0115 12:36:53.885011    7335 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Jan 15 12:36:54 l23-27-101 kubelet[7335]: E0115 12:36:54.885214    7335 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
```

**Comment by yue9944882** [comment] 2018-01-17 11:21
This error msg also occurred in #50111

**Comment by devenfan** [comment] 2018-01-28 02:23
the same error from kubelet 1.9.1:

<pre>
root@ubuntu-64:/opt/bin# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-01-28 10:01:55 CST; 17min ago
     Docs: https://github.com/kubernetes
 Main PID: 20940 (kubelet)
    Tasks: 21
   Memory: 71.0M
      CPU: 58.328s
   CGroup: /system.slice/kubelet.service
           └─20940 /opt/bin/kubelet --logtostderr=false --v=2 --log-dir=/var/log/kubernetes --address=0.0.0.0 --hostname-override=ubuntu-64 --allow-privileged=true --cgroup-driver=systemd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cl

Jan 28 10:01:55 ubuntu-64 systemd[1]: Started Kubernetes Kubelet Server.
Jan 28 10:02:00 ubuntu-64 kubelet[20940]: E0128 10:02:00.996798   20940 kubelet.go:1275] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
Jan 28 10:02:01 ubuntu-64 kubelet[20940]: E0128 10:02:01.060356   20940 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Jan 28 10:02:02 ubuntu-64 kubelet[20940]: E0128 10:02:02.060852   20940 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Jan 28 10:02:03 ubuntu-64 kubelet[20940]: E0128 10:02:03.061452   20940 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /

</pre>

**Comment by etabest** [comment] 2018-01-30 09:38
I also meet this error.
environment： 
os -- ubuntu server 16.04
kubelet -- v 1.9.2
error info:
 Jan 30 04:04:44 node-1 kubelet[9879]: E0130 04:04:44.861884    9879 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Jan 30 04:04:45 node-1 kubelet[9879]: E0130 04:04:45.864870    9879 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /

**Comment by voor** [comment] 2018-02-03 14:57
Same issue on Fedora 27:
```
Linux HOSTNAME_REMOVED 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"archive", BuildDate:"2018-01-15T15:56:33Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"archive", BuildDate:"2018-01-15T15:56:33Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@x2 ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2018-02-03 09:51:57 EST; 4s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 32508 (kubelet)
    Tasks: 14 (limit: 4915)
   Memory: 34.6M
      CPU: 993ms
   CGroup: /system.slice/kubelet.service
           └─32508 /usr/bin/kubelet --logtostderr=true --v=0 --address=127.0.0.1 --hostname-override=127.0.0.1 --allow-privileged=false --cgroup-driver=systemd --kubeconfig=/var/lib/kubelet/kubeconfig

Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.755379   32508 kubelet.go:1778] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.756393   32508 volume_manager.go:247] Starting Kubelet Volume Manager
Feb 03 09:51:57 x2 kubelet[32508]: E0203 09:51:57.757568   32508 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.856510   32508 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.859395   32508 kubelet_node_status.go:82] Attempting to register node 127.0.0.1
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.866008   32508 kubelet_node_status.go:127] Node 127.0.0.1 was previously registered
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.866030   32508 kubelet_node_status.go:85] Successfully registered node 127.0.0.1
Feb 03 09:51:57 x2 kubelet[32508]: I0203 09:51:57.869931   32508 kubelet_node_status.go:792] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2018-02-03 09:51:57.869916367 -0500 EST m=+0.529801371 LastTransitionTime:2018-02-03 09:51:57.869916367 -050
Feb 03 09:51:58 x2 kubelet[32508]: E0203 09:51:58.757957   32508 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Feb 03 09:51:59 x2 kubelet[32508]: E0203 09:51:59.758345   32508 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
```

**Comment by voor** [comment] 2018-02-03 15:03
Some additional information:
```
[root@x2 ~]# curl http://127.0.0.1:4194/validate/
cAdvisor version: 

OS version: Fedora 27 (Workstation Edition)

Kernel version: [Supported and recommended]
	Kernel version is 4.14.14-300.fc27.x86_64. Versions >= 2.6 are supported. 3.0+ are recommended.


Cgroup setup: [Supported and recommended]
	Available cgroups: map[blkio:1 memory:1 devices:1 freezer:1 net_cls:1 net_prio:1 hugetlb:1 cpuset:1 cpu:1 cpuacct:1 perf_event:1 pids:1]
	Following cgroups are required: [cpu cpuacct]
	Following other cgroups are recommended: [memory blkio cpuset devices freezer]
	Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.


Cgroup mount setup: [Supported and recommended]
	Cgroups are mounted at /sys/fs/cgroup.
	Cgroup mount directories: blkio cpu cpu,cpuacct cpuacct cpuset devices freezer hugetlb memory net_cls net_cls,net_prio net_prio perf_event pids systemd unified 
	Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
	Cgroup mounts:
	cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
	cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0


Docker version: [Supported and recommended]
	Docker version is 1.13.1. Versions >= 1.0 are supported. 1.2+ are recommended.


Docker driver setup: [Supported and recommended]
	Storage driver is overlay2.


Block device setup: [Supported and recommended]
	At least one device supports 'cfq' I/O scheduler. Some disk stats can be reported.
	 Disk "sda" Scheduler type "cfq".
	 Disk "dm-0" Scheduler type "none".
	 Disk "dm-1" Scheduler type "none".
	 Disk "dm-2" Scheduler type "none".
	 Disk "dm-3" Scheduler type "none".


Inotify watches: 
	

Managed containers: 
	/system.slice/akmods.service
	/system.slice/livesys.service
	/system.slice/systemd-logind.service
	/system.slice/netcf-transaction.service
	/system.slice/systemd-udevd.service
	/system.slice/polkit.service
	/kubepods.slice/kubepods-burstable.slice
	/system.slice/rtkit-daemon.service
	/system.slice/atd.service
	/system.slice/abrt-xorg.service
	/kube-proxy
	/
	/system.slice/kube-scheduler.service
	/system.slice/chronyd.service
	/system.slice/lvm2-lvmetad.service
	/system.slice/wpa_supplicant.service
	/system.slice/systemd-tmpfiles-setup.service
	/system.slice/systemd-random-seed.service
	/user.slice/user-0.slice/session-c13.scope
	/system.slice/rhel-push-plugin.service
	/system.slice/geoclue.service
	/system.slice/gdm.service
	/user.slice/user-1000.slice
	/kubepods.slice
	/system.slice/system-systemd\x2dcryptsetup.slice
	/system.slice/fedora-import-state.service
	/system.slice/docker.service
	/system.slice/sssd.service
	/system.slice/dracut-shutdown.service
	/system.slice/cups.service
	/user.slice/user-42.slice
	/system.slice/kube-proxy.service
	/system.slice/accounts-daemon.service
	/system.slice/mariadb.service
	/system.slice/kube-apiserver.service
	/system.slice/systemd-update-utmp.service
	/system.slice/rngd.service
	/system.slice/abrt-journal-core.service
	/system.slice/iscsi-shutdown.service
	/system.slice/system-lvm2\x2dpvscan.slice
	/system.slice/system-systemd\x2dfsck.slice
	/user.slice
	/system.slice/systemd-journal-flush.service
	/system.slice/iio-sensor-proxy.service
	/system.slice/udisks2.service
	/system.slice/gssproxy.service
	/system.slice/fedora-readonly.service
	/system.slice/systemd-user-sessions.service
	/system.slice/docker-containerd.service
	/system.slice/upower.service
	/system.slice/systemd-tmpfiles-setup-dev.service
	/system.slice/ModemManager.service
	/system.slice/etcd.service
	/system.slice/bluetooth.service
	/system.slice/avahi-daemon.service
	/system.slice/abrt-oops.service
	/system.slice
	/system.slice/systemd-modules-load.service
	/system.slice/NetworkManager.service
	/system.slice/systemd-udev-trigger.service
	/system.slice/system-getty.slice
	/system.slice/systemd-fsck-root.service
	/system.slice/libvirtd.service
	/system.slice/colord.service
	/system.slice/crond.service
	/system.slice/systemd-journald.service
	/system.slice/lvm2-monitor.service
	/system.slice/NetworkManager-wait-online.service
	/kubepods.slice/kubepods-besteffort.slice
	/system.slice/kmod-static-nodes.service
	/system.slice/alsa-state.service
	/init.scope
	/user.slice/user-0.slice
	/system.slice/rpc-statd-notify.service
	/system.slice/livesys-late.service
	/system.slice/system-systemd\x2dbacklight.slice
	/system.slice/mcelog.service
	/user.slice/user-0.slice/user@0.service
	/system.slice/systemd-sysctl.service
	/system.slice/kube-controller-manager.service
	/system.slice/dbus.service
	/system.slice/auditd.service
	/system.slice/abrtd.service
	/system.slice/firewalld.service
	/system.slice/kubelet.service
	/system.slice/systemd-udev-settle.service
	/system.slice/systemd-remount-fs.service

```

**Comment by zyxtech** [comment] 2018-02-05 07:22
meet the same error
os centos7.4(vagrant 2.0.1 ,virtualbox 5.2.2r119230  virtualization)
kubelet 1.9.2

`kubelet[11291]: E0205 05:57:29.768433   11291 container_manager_linux.go:583] [ContainerManager]: 
[ContainerManager]: Fail to get rootfs information unable to find data for container /`

**Comment by ingvagabund** [comment] 2018-02-09 11:49
Related to https://github.com/kubernetes/kubernetes/issues/55386

**Comment by ingvagabund** [comment] 2018-02-09 14:37
Ughhh: https://github.com/kubernetes/kubernetes/pull/40050

With `kubelet.kubeconfig`:
```
apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://127.0.0.1:8080/
    name: local
contexts:
  - context:
      cluster: local
    name: local
current-context: local
```

and setting `--fail-swap-on=false --kubeconfig=/var/lib/kubelet/kubelet.kubeconfig` I was able to create local cluster with `kubernetes-1.9.1`.

**Comment by ingvagabund** [comment] 2018-02-09 14:38
@voor can you verify?

**Comment by drpaneas** [comment] 2018-02-19 16:41
I have similar error from kubelet logs:

```bash
hyperkube[13020]: E0219 17:36:12.732825   13020 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 52 in cached partitions map
```

Applying the configuration posted by @ingvagabund 

```bash
d111:~ # cat /etc/kubernetes/kubelet 


###
# kubernetes kubelet (minion) config

# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=0.0.0.0"

# The port for the info server to serve on
KUBELET_PORT="--port=10250"

# You may leave this blank to use the actual hostname
KUBELET_HOSTNAME="--hostname-override=d111.qam.suse.de"

# Add your own!
KUBELET_ARGS="--fail-swap-on=false --kubeconfig=/var/lib/kubelet/kubelet.kubeconfig --pod-manifest-path=/etc/kubernetes/manifests"
```

it seems that my node (*d111* in this example) is now registered.

```bash
d295:~ # kubectl get nodes
NAME               STATUS    ROLES     AGE       VERSION
d111.qam.suse.de   Ready     <none>    20s       v1.9.3
```

However, this error is still there.

Distribution: openSUSE Tumbleweed

**Comment by chestack** [comment] 2018-03-05 11:28
+1 

kubernets:  v1.9.2
docker:  17.03.2-ce

du command hang there with this log in kubelet

**Comment by xandriaw** [comment] 2018-03-27 17:57
I'm also getting a similar error on VM trying to join an initiated Master as in t[he tutorial](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)
Kubernetes v1.9.6
Docker version 18.03.0-ce, build 0520e24

**Comment by qinghuawulang** [comment] 2018-04-12 08:40
i get same error in centos 
kubernetes:1.9.3

Fail to get rootfs information unable to find data for container

**Comment by mritd** [comment] 2018-04-17 03:27
Same issue on 1.10.1(ubuntu 16.04)

**Comment by bishnuroy** [comment] 2018-04-19 10:15
Service is running but getting the same error.

```
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: mount: /tmp/configdrive494564793: /dev/vdb already mounted on /media/configdrive.
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: W0419 09:51:40.037669    1463 server.go:387] invalid kubeconfig: stat /etc/kubernetes/ssl/kubeconfig.yaml: no such file or directory
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: W0419 09:51:40.209452    1463 server.go:236] No api server defined - no events will be sent to API server.
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.209513    1463 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.210495    1463 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.210547    1463 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgrou
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.210809    1463 container_manager_linux.go:266] Creating device plugin manager: false
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.211275    1463 kubelet.go:291] Adding manifest path: /etc/kubernetes/manifests
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: W0419 09:51:40.215980    1463 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.216048    1463 kubelet.go:577] Hairpin mode set to "hairpin-veth"
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.217927    1463 client.go:80] Connecting to docker on unix:///var/run/docker.sock
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.217989    1463 client.go:109] Start docker client with request timeout=2m0s
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: W0419 09:51:40.220368    1463 cni.go:171] Unable to update cni config: No networks found in /etc/kubernetes/cni/net.d
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.227899    1463 docker_service.go:232] Docker cri networking managed by kubernetes.io/no-op
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.242883    1463 docker_service.go:237] Docker Info: &{ID:3KBG:CFCH:Y5TD:VYDL:QWUI:KHYL:P6AP:GMLA:7V5U:UPFD:CTCE:7QXD Containers:0 ContainersRunning:0 Contai
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.243048    1463 docker_service.go:250] Setting cgroupDriver to cgroupfs
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.278377    1463 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.281744    1463 kuberuntime_manager.go:186] Container runtime docker initialized, version: 17.12.1-ce, apiVersion: 1.35.0
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.286313    1463 server.go:755] Started kubelet
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: W0419 09:51:40.286435    1463 kubelet.go:1365] No api server defined - no node status update will be sent.
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: E0419 09:51:40.286625    1463 kubelet.go:1281] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable t
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.286752    1463 server.go:129] Starting to listen on 0.0.0.0:10250
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.288237    1463 server.go:299] Adding debug handlers to kubelet server.
Apr 19 09:51:40 bflk8smin903 kubelet[1463]: I0419 09:51:40.288860    1463 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.032670    1463 kubelet_node_status.go:329] Adding node label from cloud provider: beta.kubernetes.io/instance-type=5
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.032724    1463 kubelet_node_status.go:340] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=nova
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.032736    1463 kubelet_node_status.go:344] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=RegionOne
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.483187    1463 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.483254    1463 status_manager.go:136] Kubernetes client is nil, not starting status manager.
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.483276    1463 kubelet.go:1772] Starting kubelet main sync loop.
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.483378    1463 kubelet.go:1789] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.8547
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.483384    1463 volume_manager.go:247] Starting Kubelet Volume Manager
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: E0419 09:51:41.483531    1463 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.583641    1463 kubelet.go:1789] skipping pod synchronization - [container runtime is down]
Apr 19 09:51:41 bflk8smin903 kubelet[1463]: I0419 09:51:41.783845    1463 kubelet.go:1789] skipping pod synchronization - [container runtime is down]
Apr 19 09:51:42 bflk8smin903 kubelet[1463]: I0419 09:51:42.184552    1463 kubelet.go:1789] skipping pod synchronization - [container runtime is down]
Apr 19 09:51:42 bflk8smin903 kubelet[1463]: E0419 09:51:42.483729    1463 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Apr 19 09:51:42 bflk8smin903 kubelet[1463]: I0419 09:51:42.984757    1463 kubelet.go:1789] skipping pod synchronization - [container runtime is down]
Apr 19 09:51:43 bflk8smin903 kubelet[1463]: E0419 09:51:43.484485    1463 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
Apr 19 09:51:43 bflk8smin903 kubelet[1463]: I0419 09:51:43.941598    1463 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
Apr 19 09:51:44 bflk8smin903 kubelet[1463]: I0419 09:51:44.593736    1463 kubelet_node_status.go:329] Adding node label from cloud provider: beta.kubernetes.io/instance-type=5
Apr 19 09:51:44 bflk8smin903 kubelet[1463]: I0419 09:51:44.593793    1463 kubelet_node_status.go:340] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=nova
Apr 19 09:51:44 bflk8smin903 kubelet[1463]: I0419 09:51:44.593806    1463 kubelet_node_status.go:344] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=RegionOne
```

**Comment by Vogtinator** [comment] 2018-05-03 09:33
Major 0 is used by the linux kernel for mountpoints which do not actually have a direct backing device. This applies to tmpfs, nsfs, overlayfs and also btrfs subvolumes for example.

**Comment by voor** [comment] 2018-05-03 10:16
I wonder if it's a selinux issue with the mounting of the volume, then?

**Comment by Vogtinator** [comment] 2018-05-03 12:03
These might actually be different errors: 

`Fail to get rootfs information failed to get device for dir /var/lib/kubelet` vs.
`Fail to get rootfs information unable to find data for container /`.

> I wonder if it's a selinux issue with the mounting of the volume, then?

I don't think so.

**Comment by vincentwu2011** [comment] 2018-05-11 07:14
+1 
k8s: 1.9.6
docker: 1.13.1

Sometimes the issue could be fixed by reboot the node.

**Comment by fjammes** [comment] 2018-05-12 08:41
+1
Having error:
`Fail to get rootfs information unable to find data for container /`
kubeadm, 1.9.1-0
kubectl, 1.9.1-0
kubelet, 1.9.1-0
kubernetes-cni, 0.6.0-0

docker: 18.03.1-ce
overlay2 on xfs

**Comment by chlyyy** [comment] 2018-05-18 05:28
+1

**Comment by wskinner** [comment] 2018-05-23 23:09
ME too. 
kubernetes 1.9.3
ubuntu 16.04
docker 17.03.2-ce, build f5ec1e2

**Comment by sgmiller** [comment] 2018-06-15 16:43
Same, Kubernetes 1.9.5, ubuntu 16.04, docker 18.03.1-ce

**Comment by JetMuffin** [comment] 2018-06-27 09:20
I got a similar error on **kubernetes 1.10.2** and **kubelete 1.10.2**, here are some logs:

```
Jun 27 17:16:10 zth kubelet[151929]: I0627 17:16:10.319443  151929 cpu_manager.go:155] [cpumanager] starting with none policy
Jun 27 17:16:10 zth kubelet[151929]: I0627 17:16:10.319455  151929 cpu_manager.go:156] [cpumanager] reconciling every 10s
Jun 27 17:16:10 zth kubelet[151929]: I0627 17:16:10.319467  151929 policy_none.go:42] [cpumanager] none policy: Start
Jun 27 17:16:10 zth kubelet[151929]: F0627 17:16:10.319490  151929 kubelet.go:1359] Failed to start ContainerManager failed to get rootfs info: unable to find data for container /
Jun 27 17:17:00 zth systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
```

**Comment by daicang** [comment] 2018-06-28 05:45
In my case, seems it's caused by force kill kubelet without cleaning Pod mountpoints. Delete `/var/lib/kubelet/pods/{pod-with-volume-mount}` helped fix this issue.

**Comment by JetMuffin** [comment] 2018-07-02 08:48
After debugging I found it's caused by cgroup in my case. Similar to #55386, `cpuacct.stat` has 6 fields which expected to be 4 on my server and cadvisor cannot collect container metrics.

Modify some codes at [vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go#L88](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go#L88) and **recompile kubelet** works for me.

```go
...
    fields := strings.Fields(string(data))
    if len(fields) != 4 && len(fields) != 6{
        return 0, 0, fmt.Errorf("failure - %s is expected to have 4 or 6 fields", filepath.Join(path, cgroupCpuacctStat))
    }
```

**Comment by timchenxiaoyu** [comment] 2018-08-16 13:26
k8s 1.6.4  docker 1.12.6 also this problem

E0816 16:21:12.121683  415225 kubelet.go:1165] Image garbage collection failed: unable to find data for container /
E0816 16:21:12.227843  415225 kubelet.go:1661] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E0816 16:21:12.227869  415225 kubelet.go:1669] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
E0816 16:21:12.234638  415225 kubelet.go:1661] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E0816 16:21:12.234660  415225 kubelet.go:1669] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /

**Comment by akutz** [comment] 2019-03-06 17:44
/reopen
/remove-lifecycle rotten

Hi all,

I'm running into this issue with `ci/latest` as of this morning.

- Kubernetes version (use `kubectl version`):
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.925+c4fd78e7c9f14c", GitCommit:"c4fd78e7c9f14c84b122caaa36a937a8868dff2f", GitTreeState:"clean", BuildDate:"2019-03-06T16:24:38Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.925+c4fd78e7c9f14c", GitCommit:"c4fd78e7c9f14c84b122caaa36a937a8868dff2f", GitTreeState:"clean", BuildDate:"2019-03-06T16:24:38Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
External vSphere Cloud Provider

- OS (e.g: `cat /etc/os-release`):
```shell
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
```shell
$ uname -a
Linux c01.2cb3631.sk8 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
[sk8](https://github.com/vmware/simple-k8s-test-env)

- Others:
The deployed cluster has two nodes:
1. `c01` - a control plane node able to schedule workloads
2. `w01` - a worker node


`kubectl describe nodes`
```shell
 Warning  InvalidDiskCapacity      17s    kubelet, c01.2cb3631.sk8     invalid capacity 0 on image filesystem
  Normal   Starting                 16s    kube-proxy, c01.2cb3631.sk8  Starting kube-proxy.
  Normal   Starting                 11s    kubelet, c01.2cb3631.sk8     Starting kubelet.
  Normal   Starting                 11s    kube-proxy, c01.2cb3631.sk8  Starting kube-proxy.
  Warning  InvalidDiskCapacity      11s    kubelet, c01.2cb3631.sk8     invalid capacity 0 on image filesystem
  Warning  InvalidDiskCapacity      6s     kubelet, c01.2cb3631.sk8     invalid capacity 0 on image filesystem
  Normal   Starting                 6s     kubelet, c01.2cb3631.sk8     Starting kubelet.
  Normal   Starting                 6s     kube-proxy, c01.2cb3631.sk8  Starting kube-proxy.
  Warning  InvalidDiskCapacity      1s     kubelet, c01.2cb3631.sk8     invalid capacity 0 on image filesystem
  Normal   Starting                 1s     kubelet, c01.2cb3631.sk8     Starting kubelet.
```

**c01**
`journalctl -xeu kubelet`
```
Mar 06 11:38:23 c01.2cb3631.sk8 kubelet[4758]: F0306 11:38:23.797404    4758 kubelet.go:1357] Failed to start ContainerManager failed to get rootfs info: cannot find filesystem info for
Mar 06 11:38:23 c01.2cb3631.sk8 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Mar 06 11:38:23 c01.2cb3631.sk8 systemd[1]: Unit kubelet.service entered failed state.
Mar 06 11:38:23 c01.2cb3631.sk8 systemd[1]: kubelet.service failed.
```

**w01**
`journalctl -xeu kubelet`
```
Mar 06 11:42:05 w01.2cb3631.sk8 kubelet[11076]: F0306 11:42:05.695473   11076 kubelet.go:1357] Failed to start ContainerManager failed to get rootfs info: cannot find filesystem info fo
Mar 06 11:42:05 w01.2cb3631.sk8 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Mar 06 11:42:05 w01.2cb3631.sk8 systemd[1]: Unit kubelet.service entered failed state.
Mar 06 11:42:05 w01.2cb3631.sk8 systemd[1]: kubelet.service failed.
```

**Comment by akutz** [comment] 2019-03-06 17:59
Hi All,

This is limited to `ci/latest` as `release/latest-1.15.txt` does not have this issue:

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0", GitCommit:"8d69dc630ba66d05ad95146583a7482ed1eb3f82", GitTreeState:"clean", BuildDate:"2019-02-19T14:04:01Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0", GitCommit:"8d69dc630ba66d05ad95146583a7482ed1eb3f82", GitTreeState:"clean", BuildDate:"2019-02-19T13:56:09Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Closed** 2019-08-03 20:23 UTC
Labels: lifecycle/rotten, sig/apps

**Comment by njuicsgz** [comment] 2019-11-11 11:29
it's gone after reboot the node~
