### ISSUE TITLE
Delete deployment does not respect --grace-period

### ISSUE THREAD

**Issue by msimon** [kubernetes/kubernetes#39089] opened 2016-12-21 16:47 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

delete deployment grace-period 
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** 
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4+3b417cc", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"not a git tree", BuildDate:"2016-10-21T22:33:18Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Google Container-VM Image
- **Kernel** (e.g. `uname -a`): Linux gke-cluster-gcp-west-web-default-pool-69bff2b4-glmi 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux

**What happened**:
Ran `kubectl delete --grace-period=600 deploy $Deployment`, preStop is executed but after 30 seconds the pods is force deleted. Thus, ignoring the grace-period

Running `kubectl delete --grace-period=600 pod $PodPartOfDeployment` does respect the grace-period 

**What you expected to happen**:
Pods part of the deployment should have --grace-period to gracefully shutdown

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment with a preStop hook that sleep for 100s.
Run `kubectl delete --grace-period=600 deploy $Deployment` will shut down the pod after 30 second
Run `kubectl delete --grace-period=600 pod $PodPartOfDeployment` will shut down the pod after 100s.

**Anything else do we need to know**:

**Comment by foxish** [comment] 2016-12-22 22:04
cc @smarterclayton @kubernetes/sig-apps-misc

**Comment by foxish** [comment] 2016-12-22 22:04
cc @janetkuo

**Comment by krmayankk** [comment] 2016-12-23 03:27
I would like to work on this. Is there someone who can give me some guidance on this

**Comment by kargakis** [comment] 2016-12-23 09:54
Dupe of https://github.com/kubernetes/kubernetes/issues/25055

**Closed** 2016-12-24 13:44 UTC
Labels: sig/apps
