### ISSUE TITLE
kube-apiserver panics on deployment of CRD

### ISSUE THREAD

**Issue by pingpilot** [kubernetes/kubernetes#59478] opened 2018-02-07 10:08 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When deploying a `rook.io/v1alpha1` CRD the kube-apiserver (run from gcr.io/google_containers/hyperkube:v1.9.2) panics with `fatal error: concurrent map writes`.

**What you expected to happen**:
When deploying a CRD to the cluster, the kube-apiserver does not panic and updates the map appropriately.

**How to reproduce it (as minimally and precisely as possible)**:
- Start the kupe-apiserver as a DaemonSet using https://pastebin.com/gvL5hUS0
- Deploy rook-operator with Helm using the commands  
 `helm repo add rook-alpha https://charts.rook.io/alpha`
 `helm install rook-alpha/rook --name rook --namespace rook`
- Install the attached pod, Cluster CRD, Pool CRD and StorageClass: https://pastebin.com/a1GJjmKB

**Anything else we need to know?**:
We deployed a different version of the Cluster CRD that did not cause a panic. Please find the diff attached: https://pastebin.com/6L9vTCCQ
Logs and Backtrace: [kube-apiserver.log](https://github.com/kubernetes/kubernetes/files/1702548/kube-apiserver.log)

**Environment**:
- Kubernetes version (use `kubectl version`): 
  `Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Packet
- OS (e.g. from /etc/os-release): 
  `NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"`
- Kernel (e.g. `uname -a`): 
  `Linux master1 4.14.16-coreos #1 SMP Thu Feb 1 20:38:35 UTC 2018 x86_64 Intel(R) Atom(TM) CPU C2550 @ 2.40GHz GenuineIntel GNU/Linux`
- Install tools: Matchbox / Bootkube
- Others:

**Comment by chaosaffe** [comment] 2018-02-07 10:18
@kubernetes/sig-api-machinery-bugs
/sig onprem
// cc @ash2k @sttts

**Comment by chaosaffe** [comment] 2018-02-07 10:39
Relevant section of the logs:
```
I0206 16:38:52.799136       1 handler.go:160] kube-aggregator: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.799179       1 pathrecorder.go:247] kube-aggregator: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/rook.io/v1alpha1/
I0206 16:38:52.799209       1 handler.go:160] kube-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.799229       1 pathrecorder.go:253] kube-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by NotFoundHandler
I0206 16:38:52.799249       1 handler.go:160] apiextensions-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.799271       1 pathrecorder.go:247] apiextensions-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/
I0206 16:38:52.799835       1 wrap.go:42] GET /apis/rook.io/v1alpha1/clusters?resourceVersion=0: (883.253µs) 200 [[Go-http-client/2.0] 10.99.17.7:57358]
I0206 16:38:52.800492       1 handler.go:160] kube-aggregator: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800505       1 handler.go:160] kube-aggregator: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800530       1 pathrecorder.go:247] kube-aggregator: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/rook.io/v1alpha1/
I0206 16:38:52.800547       1 pathrecorder.go:247] kube-aggregator: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/rook.io/v1alpha1/
I0206 16:38:52.800563       1 handler.go:160] kube-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800573       1 handler.go:160] kube-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800585       1 pathrecorder.go:253] kube-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by NotFoundHandler
I0206 16:38:52.800599       1 pathrecorder.go:253] kube-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by NotFoundHandler
I0206 16:38:52.800607       1 handler.go:160] apiextensions-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800619       1 handler.go:160] apiextensions-apiserver: GET "/apis/rook.io/v1alpha1/clusters" satisfied by nonGoRestful
I0206 16:38:52.800625       1 pathrecorder.go:247] apiextensions-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/
I0206 16:38:52.800637       1 pathrecorder.go:247] apiextensions-apiserver: "/apis/rook.io/v1alpha1/clusters" satisfied by prefix /apis/
fatal error: concurrent map writes

goroutine 47298 [running]:
runtime.throw(0x4998fe6, 0x15)
    /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc42eb2dd50 sp=0xc42eb2dd30 pc=0x42eb05
runtime.mapassign_faststr(0x4069820, 0xc436cc8420, 0x496a555, 0x8, 0xc427872408)
    /usr/local/go/src/runtime/hashmap_fast.go:685 +0x4da fp=0xc42eb2ddd0 sp=0xc42eb2dd50 pc=0x40feea
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.setNestedFieldNoCopy(0xc436cc83f0, 0x3dc4100, 0xc421f833e0, 0xc42eb2df18, 0x2, 0x2, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:198 +0x1ef fp=0xc42eb2de48 sp=0xc42eb2ddd0 pc=0xf4afbf
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.SetNestedField(0xc436cc83f0, 0x3dc4100, 0xc421f833e0, 0xc42eb2df18, 0x2, 0x2, 0x0)
```

**Comment by ash2k** [comment] 2018-02-07 11:58
`fatal error: concurrent map writes` means there is something else that is mutating the map that backs the unstructured. So I tried to find what it can be. The code tries to set the self link in the objects it got from the store:
https://github.com/kubernetes/kubernetes/blob/5fa2db2bd46ac79e5e00a4e6ed24191080aa463b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L255-L261

Is it safe in general to mutate object from the store? I know it is not with informers, but this is a different kind of store. I'm not familiar with this code and my own attempt to figure this out didn't bring any results. Too much indirection and I don't have time right now to figure this out. Can someone more knowledgeable have a look?

**Comment by sttts** [comment] 2018-02-08 09:30
> Is it safe in general to mutate object from the store?

Nope. Very bad things happen if you do that.

So this means that it concurrent write is inside the endpoints handler? No in unstructured?

**Comment by ash2k** [comment] 2018-02-08 10:10
> > Is it safe in general to mutate object from the store?
>
> Nope. Very bad things happen if you do that.

Double checking - this is not an informer store, this is some other store. This code was there for at least 2.5 years if I'm not mistaken. My guess is probably wrong.

> So this means that it concurrent write is inside the endpoints handler? No in unstructured?

It is an issue caused by concurrency, but there is no concurrent code in unstructured itself. Something is not doing locking properly or sharing an object by mistake.

**Comment by nikhita** [comment] 2018-03-03 10:40
> fatal error: concurrent map writes means there is something else that is mutating the map that backs the unstructured.

Need to dig into this but it reminds me of https://github.com/kubernetes/kubernetes/issues/56316 (https://github.com/kubernetes/kubernetes/pull/55650#discussion_r151848708).

**Comment by SEJeff** [comment] 2018-05-03 12:01
@pingpilot mind putting your examples in a gist or somewhere? $employer blocks pastebin (and we ran into what appears to be an identical or very similar bug deploying a few new rook objects to a 1.9.4 cluster.

**Comment by pingpilot** [comment] 2018-05-03 12:25
@SEJeff sure, here you are:
[kube-apiserver.yaml.txt](https://github.com/kubernetes/kubernetes/files/1970799/kube-apiserver.yaml.txt)
[tools.yaml.txt](https://github.com/kubernetes/kubernetes/files/1970800/tools.yaml.txt)
[CRD.diff.txt](https://github.com/kubernetes/kubernetes/files/1970803/CRD.diff.txt)

**Comment by c6h3un** [comment] 2018-06-01 03:06
We also have the same problem, the apiserver panics with `fatal error: concurrent map writes`. We follow the steps as below,
- Deploy apiserver with static pod  (run with k8s.gcr.io/kube-apiserver-amd64:v1.10.2 image)
- Setup kubelet and kube-controller-manager to use accessible and writeable volume plugin directory
- Deploy rook operator, rook cluster with block storage ([Quickstart](https://rook.io/docs/rook/master/quickstart.html), [GitHub repo example](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph))
- Deploy wordpress ( mysql.yaml and wordpress.yaml in [GitHub repo example](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes))

**Environment:**

- Kubernetes version (use kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:28:25Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:   
VMs on top of VMware server
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. uname -a):
```
Linux vm01 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by davidkarlsen** [comment] 2018-06-13 21:36
Same here, also a with rook install.
api-server log: https://www.pastefile.com/K7Yqp1

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

os-release
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

uname -a
Linux main.davidkarlsen.com 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sttts** [comment] 2018-06-14 10:37
Fixed in https://github.com/kubernetes/kubernetes/pull/65092

**Closed** 2018-06-15 18:39 UTC
Labels: area/apiserver, kind/bug, priority/important-soon, sig/api-machinery
