### ISSUE TITLE
`kubectl delete ns -n <namespace> --all` deletes ALL namespaces 

### ISSUE THREAD

**Issue by dilyar85** [kubernetes/kubernetes#75706] opened 2019-03-26 01:07 UTC
**What happened**:
`kubectl delete namespace --namespace=<namespace> --all` deletes all namespaces in the cluster. 

**What you expected to happen**:
The above command should throw an error since `--namespace` and `--all` are mutually exclusive commands.

**How to reproduce it (as minimally and precisely as possible)**:
**CAUTION**: This might delete all namespaces in your cluster!
Execute the command `kubectl delete namespace --namespace=<namespace> --all` by replacing `<namespace>` to any of your namespace.

**Anything else we need to know?**:
None.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
MacBook Pro 2.9 GHz Intel Core i9
```
- OS (e.g: `cat /etc/os-release`):
```
macOS Mojave Version 10.14.3
```
- Kernel (e.g. `uname -a`):
```
Darwin mbp 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:

**Comment by pswica** [comment] 2019-03-26 02:57
Usually, adding a `-n` flag specifies which namespace you are running the command from (e.g. it would be the metadata:namespace field, I believe). However, namespaces are cluster-level resources and specifying a namespace when deleting a namespace makes not much sense. Hence, it would only be natural that running the command deletes all namespace even though you specified the `-n` flag. 

Perhaps this makes more sense if you consider that you can run:
`kubectl get node`
`kubectl get node -n test`

and get the same result. The reason you get the same result is that nodes are also cluster-level resource so specifying the namespace has no impact on the output.

**Comment by liggitt** [comment] 2019-03-26 13:11
this is a duplicate of https://github.com/kubernetes/kubernetes/issues/61431

**Comment by liggitt** [comment] 2019-03-26 13:25
every kubectl invocation has a "current namespace", determined in this precedence order:
* an explicit `-n ...` value
* the namespace of the "current context" in the kubeconfig file
* `default`

The "current namespace" is used when making API requests for namespaced resources, and is ignored when making API requests for cluster-scoped resources.

If we wanted to start requiring an additional flag to delete all of a cluster-scoped resource, that would be a breaking change to `kubectl delete`, so we would need to start warning now (in 1.15), and could require an explicit flag in 1.19 (per https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior)

**Comment by YoubingLi** [comment] 2019-03-27 02:47
If we just wants to throw WARNING message after both -n and --all are specified toghter in the kubectl command line, I want to work on it.

/assign @YoubingLi

**Closed** 2019-04-06 18:07 UTC
Labels: kind/feature, sig/cli

**Comment by leonsp** [comment] 2019-11-28 18:29
Can this be properly fixed in a future release? The warning message is useful in a post-mortem, but even for those purposes it's unclear.

This would be a better warning: "You're about to delete all your namespaces. Are you sure? y/N"

Given the possibilities of shooting yourself in the foot, adding the equivalent of [the following](r) would improve the usability immeasurably:
- `rm --interactive *`, so that you have to confirm deletion for every single item being deleted
- `rm --preserve-root *`, so that you can't delete system resources without opting in

My team is currently recovering from this:
```
$ kubectl delete ns --namespace=foo --all
warning: deleting cluster-scoped resources, not scoped to the provided namespace
namespace "one" deleted
namespace "two" deleted
namespace "three" deleted
...
namespace "twentythree" deleted
```

**Comment by cben** [comment] 2019-12-02 13:00
I just heard from another user that accidentally destroyed a cluster by `kubectl delete nodes -n foo --all` instead of `kubectl delete pods -n foo --all` :fearful: 

Question: do we feel equally surprised when there is no `-n` flag, falling back to current namespace?
`kubectl delete pods --all` deletes all pods in current namespace; the similar `kubectl delete nodes --all` is at cluster scope and I'd say that's still pretty intuitive.

Question: is this specific to `delete`?  It's the most destructive one, but others can be used to similar effect e.g. `kubectl get nodes,pods --show-kind | xargs kubectl delete`, so it's important to keep namespace sematics consistent in all commands.

But for `--namespace=foo` while _technically_ the effect "set _current_ namespace to foo" is well-defined, I suspect many users have a different mental model of "constrain to namespace foo".  This mental model may be reinforced by assuming `--all-namespaces` is the anti-dote to `--namespace` that "lifts the constraint" :no_entry_sign: 

Maybe a "directory hierarchy" metaphore is a good way to discuss this.  It also matches how the REST api looks.  There are 3 modes for finding resources:

N. `ls /namespaces/foo/pods/*`  (current or --namespace)
A. `ls /namespaces/*/pods/*`  (with --all-namespaces)
G. `ls /nodes/*`

As mentioned on #61431, #39084, it's possible by design to mix (G) and (N) in same command e.g. `kubectl get nodes,pods`, with only namespaced resources constrained to current (or given) namespace.  There are effectively "two working directories" in play.
Compatibility aside, I can't say I care for this feature; the results won't mean "what I think they mean" and I'd prefer this disallowed.
I'm more OK with mixing (G) and (A) `kubectl get pods,nodes --all-namespaces`.

---

@leonsp's proposal is great because it's **backwards compatible** :sparkling_heart: 
At [some point](http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commitdiff;h=89ffaa19;hp=963d29f9) GNU `rm` broke compatibility and started defaulting to `--preserve-root`, but that only came about after _years_ of allowing users to opt-in to the safer behavior by `alias rm='rm --preserve-root --one-file-system'`, or whatever behavior one is comfortable with.
(There are downsides to building habits that won't hold on another person's shell.  But still, it's a viable path forward!)

So, various proposals for new options:

- [ ] `kubectl --all-in-namespace[=ns]` that is specifically a safer alternative to `--all`, refusing to match any cluster-global resources in same command.
  Using this doesn't cover the case of specific names given on command line — `kubectl delete nodes,pods f00-ba7` can match both a node and a pod that happen to be named `f00-ba7`.  But that's less likely to cause harm in practice...
- [ ] `kubectl --only-namespace=ns` that is specifically a stronger alternative to `--namespace=ns`, refusing to touch anything global and any other namespace.
  With a hope that in far future, `-n` could switch to mean this (if people request it, after long period of warnings).
- [ ] `kubectl --no-global` or `kubectl --namespaced` that refuses to match ANY cluster-global resource.
  Would require explicit `--global` to even list nodes.  (need to ensure latest wins, so one can override an alias expanding to `kubectl --no-global get nodes --global`)
  I don't think this could ever become default.
- [ ] `kubectl --either-namespaced-or-global` that refuses to mix (G) and (N) modes in same command.  Still allows `kubectl get nodes`, and possibly `kubectl get pods,nodes --all-namespaces`.
  With a hope that in far future, this could become default (if people request it, after long period of warnings).
- [ ] `kubectl delete --interactive` (and maybe other actions)

**Comment by liggitt** [comment] 2019-12-02 14:23
@leonsp @cben thanks for the feedback. It would probably be a good idea to raise these proposals in a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps) in coordination with the relevant sigs ([sig-cli](https://github.com/kubernetes/community/tree/master/sig-cli) for the command and [sig-architecture](https://github.com/kubernetes/community/tree/master/sig-architecture) for the compatibility aspects, most likely). Comments on a closed issue get lost in github notification noise.
