### ISSUE TITLE
[Failing Test] ci-cloud-provider-openstack-acceptance-test-e2e-conformance keeps timing out

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#95304] opened 2020-10-05 15:51 UTC
**Which jobs are failing**:
`ci-cloud-provider-openstack-acceptance-test-e2e-conformance` (Conformance - OpenStack in sig-release-master-informing TestGrid)

**Which test(s) are failing**:
- [sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance]  
- [sig-network] Services should have session affinity work for NodePort service [LinuxOnly] [Conformance]
- [sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] 
- ~~[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should be able to deny attaching pod [Conformance]~~

**Since when has it been failing**:
Looks like since September 21 at least from TestGrid, but unsure if it goes back further.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Reason for failure**:
Timeouts

**Anything else we need to know**:
Having trouble finding this job/these tests in triage - otherwise I'd put a link here as well :( 
Example prow job link for failures: https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1601820515

/sig network
/sig api-machinery
cc @kubernetes/ci-signal

**Comment by caesarxuchao** [comment] 2020-10-06 20:21
cc @cheftako 
/remove-sig api-machinery
/sig cloud-provider

**Comment by thejoycekung** [comment] 2020-10-16 15:07
Small update: `[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should be able to deny attaching pod [Conformance]` looks like it is no longer failing. 

The three sig network tests are still failing though. Example spyglass link: https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1602770887

/cc @kubernetes/sig-network-test-failures 
/remove-sig cloud-provider

**Comment by RobertKielty** [comment] 2020-10-20 14:01
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network&test=session%20affinity%20timeout#5f64bdae2f164c2694d1

**Comment by aojea** [comment] 2020-10-20 14:45
@RobertKielty you should contact the job owners, is not a sig-network job, 

anyway, happy to help them, but this depends on how they have the setup, 
are they using kube-proxy?
ipvs or iptables?

**Comment by cheftako** [comment] 2020-10-20 16:39
cc @lingxiankong

**Comment by lingxiankong** [comment] 2020-10-21 00:35
I will try to fix that

**Comment by aojea** [comment] 2020-10-21 05:49
@lingxiankong we can help if you provide the info on the CNI and the component that implement the service API, are you using kube-proxy?

**Comment by lingxiankong** [comment] 2020-10-21 08:14
> @lingxiankong we can help if you provide the info on the CNI and the component that implement the service API, are you using kube-proxy?

Thanks @aojea , the root cause is the access to the node port range is restricted for the k8s cluster nodes in cloud-provider-openstack CI. That's the limitation of the CI cloud provider. We have to skip the 3 test cases for now.

**Comment by aojea** [comment] 2020-10-21 08:31
wow, that was fast ... good was not a regression :+1:

**Comment by lingxiankong** [comment] 2020-10-22 19:43
According to https://logs.openlabtesting.org/logs/periodic-14/github.com/kubernetes/cloud-provider-openstack/master/cloud-provider-openstack-acceptance-test-e2e-conformance/7aa4451/job-output.txt.gz, the issue should be fixed now.

**Comment by thejoycekung** [comment] 2020-10-23 17:09
@lingxiankong Sorry about the late response - just wanted to give it another run. Yep, looks like these tests are no longer running! Thanks so much for your help. I think we can close this now.

/close

**Closed** 2020-10-23 17:09 UTC
Labels: kind/failing-test, needs-triage, sig/network
