### ISSUE TITLE
flaky test: unit/integration failed in “TestNamespaceController.go”

### ISSUE THREAD

**Issue by xialonglee** [kubernetes/kubernetes#39510] opened 2017-01-06 05:14 UTC
see: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38621/pull-kubernetes-unit/11304/#k8siokubernetesfederationpkgfederation-controllernamespace-testnamespacecontroller

I think that test fail is nothing to do with my pr #38621 

@mwielgus i tag you because the failed messages has connections with your pr #37659
and i have no idea why it fails, i tested it on my branch of my pr in my local machine, it passed.

the log is:
```
0xa4e85d	k8s.io/kubernetes/federation/pkg/federation-controller/util/test.RegisterFakeWatch.func1+0x14d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/test/test_helper.go:154
0x44355e	sync.runtime_notifyListWait+0x12e										/usr/local/go/src/runtime/sema.go:267
0x4da08d	sync.(*Cond).Wait+0x8d												/usr/local/go/src/sync/cond.go:57
0x9feb1d	k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop+0xed							/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:407
0x9fb020	k8s.io/kubernetes/pkg/client/cache.(*Controller).processLoop+0x70						/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:131
0xa09d91	k8s.io/kubernetes/pkg/client/cache.(*Controller).(k8s.io/kubernetes/pkg/client/cache.processLoop)-fm+0x41	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:102
0xbf15ff	k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1+0x6f								/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96
0xbf0d5d	k8s.io/kubernetes/pkg/util/wait.JitterUntil+0xbd								/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97
0xbf0c7a	k8s.io/kubernetes/pkg/util/wait.Until+0x5a									/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52
0x9fad0e	k8s.io/kubernetes/pkg/client/cache.(*Controller).Run+0x24e							/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:102
0xa052f9	k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler+0x1689	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:346
0xa02fab	k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch+0xe3b	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:317
0xa0a63a	k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1+0x4a	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:198
0xbf15ff	k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1+0x6f			/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96
0xbf0d5d	k8s.io/kubernetes/pkg/util/wait.JitterUntil+0xbd			/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97
0xbf0c7a	k8s.io/kubernetes/pkg/util/wait.Until+0x5a				/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52
0xa0aae3	k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1+0x3b3	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:266
0x579d3a	k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).run+0x63a	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:122
0x5801d7	k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler.func1+0x157	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:174
0x4972ad	testing.(*T).Run+0x56d		/usr/local/go/src/testing/testing.go:647
0x49bb99	testing.RunTests.func1+0xb9	/usr/local/go/src/testing/testing.go:793
0x496cc9	testing.tRunner+0xc9		/usr/local/go/src/testing/testing.go:610
0x49868a	testing.RunTests+0x4ba		/usr/local/go/src/testing/testing.go:799
0x49785f	testing.(*M).Run+0x12f		/usr/local/go/src/testing/testing.go:743
0x401428	main.main+0x1b8			k8s.io/kubernetes/federation/pkg/federation-controller/namespace/_test/_testmain.go:54
0x430fec	runtime.main+0x18c		/usr/local/go/src/runtime/proc.go:183
0x4aabdd	k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).Run.func1+0x4d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:263
0xa1bfa5	k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1+0xc5	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:228
0xa3aef2	k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop+0x92	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:201
0xa43d9d	k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon+0x9d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879
0x580066	k8s.io/kubernetes/federation/pkg/federation-controller/util.StartBackoffGC.func1+0x126	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/backoff.go:28
0x5515dd	runtime/pprof.writeRuntimeProfile+0xbd								/usr/local/go/src/runtime/pprof/pprof.go:614
0x551379	runtime/pprof.writeGoroutine+0xc9								/usr/local/go/src/runtime/pprof/pprof.go:576
0x54cbfd	runtime/pprof.(*Profile).WriteTo+0x47d								/usr/local/go/src/runtime/pprof/pprof.go:298
0xa4e376	k8s.io/kubernetes/federation/pkg/federation-controller/util/test.CheckObjectFromChan+0x2a6	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/test/test_helper.go:256
0x4a8001	k8s.io/kubernetes/federation/pkg/federation-controller/namespace.TestNamespaceController+0x1ae1	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:140
0x496cc9	testing.tRunner+0xc9										/usr/local/go/src/testing/testing.go:610
<autogenerated>:10: 
                        
	Error Trace:	namespace_controller_test.go:140
	
	Error:		Received unexpected error "Failed to get an object from channel"
	
<autogenerated>:10: 
                        
	Error Trace:	namespace_controller_test.go:147
	
	Error:		"map[]" does not contain "A"
	
```

**Comment by derekwaynecarr** [comment] 2017-03-10 22:26
i think someone from federation should debug this failure first.

**Comment by nikhiljindal** [comment] 2017-03-11 10:17
Closing as duplicate of https://github.com/kubernetes/kubernetes/issues/36351

**Closed by nikhiljindal** 2017-03-11 10:17 UTC
Labels: kind/flake, sig/federation
