### ISSUE TITLE
`kubectl --request-timeout=30s` using in-cluster config doesn't work

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#51952] opened 2017-09-05 13:26 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug
/area kubectl
@kubernetes/sig-cli-bugs

**What happened**:
```
/ # kubectl --namespace=kube-system --request-timeout 30s delete pod scheduler-healthcheck-kube-scheduler-2100019357-83rtb
error: yaml: mapping values are not allowed in this context
```

**What you expected to happen**:
For it to delete the pod

**How to reproduce it (as minimally and precisely as possible)**:
Use `kubectl --request-timeout=30s` from inside a pod

**Anything else we need to know?**:

Without `--request-timeout` the request succeeds:
```
/ # kubectl -v 10 --namespace=kube-system delete pod scheduler-healthcheck-kube-scheduler-2100019357-83rtb
I0905 13:24:35.380446     697 merged_client_builder.go:123] Using in-cluster configuration
...
```

With `--request-timeout` it instead talks to localhost, instead of using in-cluster config:
```
/ # kubectl -v 10 --namespace=kube-system --request-timeout=30s delete pod scheduler-healthcheck-kube-scheduler-2100019357-83rtb
I0905 13:24:55.490797     706 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.7.5 (linux/amd64) kubernetes/17d7182" http://localhost:8080/api
I0905 13:24:55.583140     706 round_trippers.go:405] GET http://localhost:8080/api 200 OK in 92 milliseconds
I0905 13:24:55.583175     706 round_trippers.go:411] Response Headers:
I0905 13:24:55.583180     706 round_trippers.go:414]     Date: Tue, 05 Sep 2017 13:24:55 GMT
I0905 13:24:55.583229     706 round_trippers.go:414]     Content-Length: 229
I0905 13:24:55.583241     706 round_trippers.go:414]     Content-Type: text/html; charset=utf-8
I0905 13:24:55.583331     706 request.go:991] Response Body: <b> Kubernetes healthz sidecar container </b><br/><br/><a href="/healthz">/healthz: healthz probe. Returns "ok" if the command given through -cmd exits with 0.</a><br/><a href="/quit">/quit: Cause this container to exit.</a><br/>
I0905 13:24:55.583641     706 cached_discovery.go:126] skipped caching discovery info due to yaml: mapping values are not allowed in this context
F0905 13:24:55.583726     706 helpers.go:120] error: yaml: mapping values are not allowed in this context
```

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by dixudx** [comment] 2017-09-05 14:53
> error: yaml: mapping values are not allowed in this context

@mikebryant What's your `./kubectl config view`? Why is it talking to localhost? Seems you've mis-configured config file for `kubectl`.

**Comment by mikebryant** [comment] 2017-09-05 15:43
```
/ # kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```
There is no kubeconfig file, as I'm trying to just use in-cluster config.

I think that error message was due to us running exechealthz on localhost:8080, so it was trying to parse the output.

We've now changed that, so it now looks like this:


```
/ # kubectl get pod weave-net-zrtsm
NAME              READY     STATUS    RESTARTS   AGE
weave-net-zrtsm   2/2       Running   0          23h
/ # kubectl --request-timeout=30s get pod weave-net-zrtsm
The connection to the server localhost:8080 was refused - did you specify the right host or port?
/ # 
```

Note it works without `--request-timeout`, but with it, it seems to be ignoring in-cluster config

**Comment by liggitt** [comment] 2017-09-05 17:47
duplicate of https://github.com/kubernetes/kubernetes/issues/49343

**Closed by liggitt** 2017-09-05 17:47 UTC
Labels: area/kubectl, kind/bug, sig/cli
