### ISSUE TITLE
azure disk may be mounted by pod before disk is actually attached

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#75619] opened 2019-03-22 23:42 UTC
**What happened**:
- restart pod using azure disk
- according to controller-manager, disk is successfully detached from /dev/sdc
- pod is rescheduled to the same node
- according to controller-manager, disk is reattached to the same node at /dev/sdd
- pod is started while /dev/disk/azure/scsi1/lun0 points to /dev/sdc
- disk is *actually* detached from /dev/sdc and reattached to /dev/sdd
- pod gets i/o errors

**What you expected to happen**: pod doesn't get i/o errors

**How to reproduce it (as minimally and precisely as possible)**:
- create a pod using an azure disk and fix its nodeName
- restart it every ~minute or 2 until it crashes

**Anything else we need to know?**: similar to https://github.com/kubernetes/kubernetes/issues/71453 except there is only one disk in this scenario.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.x
- Cloud provider or hardware configuration: azure

@andyzhangx our current theory is that the Attach and Detach calls are asynchronous https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_controller_standard.go#L84, so even though controller reports that detach->reattach succeeded azure doesn't actually detach->reattach until after kubelet has already mounted the volume, which it does because the volume has the same lun https://github.com/openshift/origin/blob/release-3.11/vendor/k8s.io/kubernetes/pkg/volume/azure_dd/attacher.go#L182. Is this scenario possible?

**Comment by andyzhangx** [comment] 2019-03-23 01:01
/assign
Does this issue only repro on VMSS? If so, I think it's related to the issue mentioned in attachment. That disk attach/detach issue on VMSS is caused by VMSS RP returned operation status directly before it completed. And VMSS team will fix this issue in April. VM availability Set won't have this issue.

**Comment by jim-minter** [comment] 2019-03-23 14:22
@andyzhangx yes, this is on VMSS.

@mjudeikis fyi

**Comment by andyzhangx** [comment] 2019-05-17 00:56
/close
close this issue since it's already fixed in VMSS RP on Azure.

**Closed by andyzhangx** 2019-05-17 00:56 UTC
Labels: kind/bug, sig/azure, sig/storage
