### ISSUE TITLE
Endpoints being deleted twice

### ISSUE THREAD

**Issue by cbandy** [kubernetes/kubernetes#99407] opened 2021-02-24 16:14 UTC
#### What happened:

A Service with a custom finalizer and a selector has its Endpoints deleted twice when it is deleted.

#### What you expected to happen:

I expected a Service's Endpoints to be deleted exactly once.

#### How to reproduce it (as minimally and precisely as possible):

Create the following Service and watch Endpoints as it is deleted. Notice that Endpoints are `DELETED` in steps 2 _and_ 4.

```yaml
#$ cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: select-some
  finalizers:
  - example.com/cbandy
spec:
  type: ClusterIP
  clusterIP: None
  selector: { cbandy: none }
  ports:
  - port: 9999
    protocol: TCP
```

```shell
kubectl get svc -o json -w --output-watch-events | jq --unbuffered '{ _ts: now, type, kind: .object.kind } + (.object.metadata | { name, creationTimestamp, deletionTimestamp, finalizers, ownerReferences })'
kubectl get ep  -o json -w --output-watch-events | jq --unbuffered '{ _ts: now, type, kind: .object.kind } + (.object.metadata | { name, creationTimestamp, deletionTimestamp, finalizers, ownerReferences })'
```

1. Setup
   `kubectl apply -f svc.yaml`

   ```json
   {
     "_ts": 1614180822.11588,
     "type": "ADDED",
     "kind": "Service",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": null,
     "finalizers": [
       "example.com/cbandy"
     ],
     "ownerReferences": null
   }
   {
     "_ts": 1614180822.134641,
     "type": "ADDED",
     "kind": "Endpoints",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": null,
     "finalizers": null,
     "ownerReferences": null
   }
   ```

2. Foreground Delete
   `kubectl delete -f svc.yaml --cascade=foreground`
   
   ```json
   {
     "_ts": 1614180857.693082,
     "type": "MODIFIED",
     "kind": "Service",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": "2021-02-24T15:34:17Z",
     "finalizers": [
       "example.com/cbandy",
       "foregroundDeletion"
     ],
     "ownerReferences": null
   }
   {
     "_ts": 1614180857.786051,
     "type": "DELETED",
     "kind": "Endpoints",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": null,
     "finalizers": null,
     "ownerReferences": null
   }
   ```
   
3. Garbage Collection (?)

   ```json
   {
     "_ts": 1614180858.384409,
     "type": "MODIFIED",
     "kind": "Service",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": "2021-02-24T15:34:17Z",
     "finalizers": [
       "example.com/cbandy"
     ],
     "ownerReferences": null
   }
   {
     "_ts": 1614180857.79415,
     "type": "ADDED",
     "kind": "Endpoints",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:34:17Z",
     "deletionTimestamp": null,
     "finalizers": null,
     "ownerReferences": null
   }
   ```

4. Remove Finalizer
   `KUBE_EDITOR="sed -i -e '/example.com\/cbandy/ d'" kubectl edit -f svc.yaml`
   
   ```json
   {
     "_ts": 1614181028.790913,
     "type": "DELETED",
     "kind": "Service",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:33:42Z",
     "deletionTimestamp": "2021-02-24T15:34:17Z",
     "finalizers": [
       "example.com/cbandy"
     ],
     "ownerReferences": null
   }
   {
     "_ts": 1614181028.799698,
     "type": "DELETED",
     "kind": "Endpoints",
     "name": "select-some",
     "creationTimestamp": "2021-02-24T15:34:17Z",
     "deletionTimestamp": null,
     "finalizers": null,
     "ownerReferences": null
   }
   ```

#### Anything else we need to know?:

I see a variety of issues around Service/Endpoint deletion. Finalizers are mentioned in #87603.

/sig network

#### Environment:

- Install tools: `kubeadm`
- Kubernetes version (use `kubectl version`):

  I see this behavior in v1.20 and v1.18.

  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

  ```
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by aojea** [comment] 2021-02-27 17:49
I think that this is indeed a duplicate of https://github.com/kubernetes/kubernetes/issues/87603
/cc @MrHohn @thockin

**Comment by thockin** [comment] 2021-03-04 21:25
Agree - closing as a dup, I pinged #87603

**Closed** 2021-03-04 21:25 UTC
Labels: kind/bug, needs-triage, sig/network
