### ISSUE TITLE
pkg/api doesn't compile with latest ugorji/go/codec

### ISSUE THREAD

**Issue by peterbourgon** [kubernetes/kubernetes#16361] opened 2015-10-27 13:14 UTC
```
$ # with an empty GOPATH
$ go get k8s.io/kubernetes/pkg/api
```

What I expected to happen: the package is fetched, compiled, and made available for use.

What actually happened:

```
# k8s.io/kubernetes/pkg/api
src/k8s.io/kubernetes/pkg/api/types.generated.go:439: r.EncodeEnd undefined (type codec.encDriver has no field or method EncodeEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:454: r.IsContainerType undefined (type codec.decDriver has no field or method IsContainerType)
src/k8s.io/kubernetes/pkg/api/types.generated.go:457: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:461: r.IsContainerType undefined (type codec.decDriver has no field or method IsContainerType)
src/k8s.io/kubernetes/pkg/api/types.generated.go:464: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:619: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:637: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:652: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:667: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:682: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
src/k8s.io/kubernetes/pkg/api/types.generated.go:682: too many errors
```

type.generated.go needs to be regenerated with the latest codec.

It is insufficient to say this is handled by Godeps, as third-party packages directly `import "k8s.io/kumernetes/pkg/api"`, and you don't rewrite your import paths.

**Comment by brandoncole** [comment] 2015-10-27 13:20
Our team is also affected by this.  We're implementing a workaround for the time being, of pinning github.com/ugorji/go/codec to 8a2a3a8c488c3ebd98f422a965260278267a0551.

**Comment by asim** [comment] 2015-10-27 14:35
Agree with Peter here. Facing same issue building kubernetes/contrib/service-loadbalancer and myodc/go-micro. I'm a believe in master always building especially when others can utilise this code.

**Comment by theo01** [comment] 2015-10-27 15:04
Faced the same issue here. 

Pinning github.com/ugorji/go/codec to 8a2a3a8c488c3ebd98f422a965260278267a0551 mentioned by @brandoncole work as a quick solution.

**Comment by mikedanese** [comment] 2015-10-27 18:00
cc @lavalamp

**Comment by mikedanese** [comment] 2015-10-27 18:09
Currently the client is not go gettable. We want to make it easy to use the go client in other projects (#5660 and more generally #8190) but we are not there yet. Until then, you need to checkout all required dependencies to the ref specified in Godeps/Godeps.json.

**Comment by lavalamp** [comment] 2015-10-27 22:08
Is updating the ugorji dependency sufficient to solve this problem? @wojtek-t, can you do this? Is there any reason not to?

(In the future we'd like to drastically reduce the import dependency tree)

**Comment by wojtek-t** [comment] 2015-10-28 08:32
Sure - I will try to update that dependency (if it will not break us).

**Comment by wojtek-t** [comment] 2015-10-28 08:38
OK - I see where the problem is :(
The issue is that we need to update this dependency in go-etcd and etcd itself first (because we need all of those to use the same version of ugorji).
The WIP PR updating our code is here:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:update_ugorji
but unfortunately it cannot be submitted now.

**Comment by jdoliner** [comment] 2015-10-28 19:53
What's blocking the PRs submission?
We're currently running in to this as well :(

**Comment by mikedanese** [comment] 2015-10-28 22:05
This is blocked because the change needs to be made upstream in https://github.com/coreos/go-etcd

There is a workaround which is to checkout the version gorji that we currently have pinned with godeps.

**Comment by lavalamp** [comment] 2015-10-29 23:36
Marking P1 due to all the complaints.

**Comment by brandoncole** [comment] 2015-10-29 23:40
Thank you @lavalamp

**Comment by wojtek-t** [comment] 2015-11-02 11:11
An update:
- go-etcd has already been update in https://github.com/coreos/go-etcd/pull/247
- I've send https://github.com/coreos/etcd/pull/3792 out for review to update etcd

Once this is merged, we should update ugorji, go-etcd and etcd in a single PR to fix that.

**Comment by wojtek-t** [comment] 2015-11-02 15:56
PR in etcd is already merged.

However, I'm having some trouble with updating etcd Godeps - I'm able to update ugorji, go-etcd, but when updating etcd itself I'm getting:

    wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ go get -u github.com/coreos/etcd/client
    wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ godep update github.com/coreos/etcd/client
    godep: no packages can be updated

@lavalamp @timothysc - any hints what I'm doing wrong?

**Comment by timothysc** [comment] 2015-11-02 19:33
@wojtek-t I came across a similar issue with etcd dep updating.  Here was my recipe... 

1. godep restore 
2. Blast your local ./Godeps directory 
3. Make certain your downloaded deps are the exact versions you are looking for.  (transitive mashing in a problem) 
4. godep save ./...

**Comment by wojtek-t** [comment] 2015-11-03 12:59
#16725 that should solve this issue is already out for review.

**Comment by glerchundi** [comment] 2015-11-05 08:18
@brandoncole thanks, that was a really quick fix :+1:

**Comment by asim** [comment] 2015-11-18 17:17
Unfortunately still not fixed.

**Comment by tmrts** [comment] 2015-11-21 22:36
I got the identical error mentioned by @peterbourgon as well.

**Closed** 2015-11-26 06:14 UTC
Labels: kind/support, priority/P1, team/CSI

**Comment by dhawal55** [comment] 2016-05-06 16:07
```go get k8s.io/kubernetes/pkg/api
package k8s.io/kubernetes/pkg/api: cannot find package "k8s.io/kubernetes/pkg/api" in any of:
	/usr/local/Cellar/go/1.6.1/libexec/src/k8s.io/kubernetes/pkg/api (from $GOROOT)
	/Users/xacj/go/src/k8s.io/kubernetes/pkg/api (from $GOPATH)```
