### ISSUE TITLE
kubectl -bash: _init_completion: command not found

### ISSUE THREAD

**Issue by moander** [kubernetes/kubernetes#12400] opened 2015-08-07 15:19 UTC
I'm having trouble with kubectl bash completion.

```
$ _output/local/bin/darwin/amd64/genbashcomp /usr/local/etc/bash_completion.d/
```

Error message when pressing tab:

```
$ kubectl -bash: _init_completion: command not found
```

I'm using bash_completion v1.3 from brew and kubectl v1.1.0-alpha.0.1417+c8177399965a6b

**Comment by brendandburns** [comment] 2015-08-14 05:34
@eparis

**Comment by eparis** [comment] 2015-08-14 13:41
I'm sorry, I don't have a mac to reproduce, so my 'help' might not be as helpful as it otherwise could be. But I can tell you how this works on Linux systems and hopefully that will get you an answer..

So _init_completion is supplied in bash_completions v1.3 as you pointed out.  On Linux its in the file `/usr/share/bash-completion/bash_completion`. That file has to be sourced by your bash shell before you load the kubectl completions.  Again on my linux system this works because ~/.bashrc sources /etc/bashrc.  /etc/bashrc in turn walks /etc/profile.d/* and sources those files. In my case there is a /etc/profile.d/bash_completion.sh which checks for the existence of `/usr/share/bash-completions/bash_completion` and sources it if it exists.

I have no idea how that chain is supposed to work on your mac. But find the bash_completion file provided by the bash_completions v1.3 and source it, then see if the completions work for you.

**Comment by moander** [comment] 2015-08-14 18:13
What's strange is that bash completion are working for my other commands (git/docker/gcloud and nany more).

Can someone with a mac please try to reproduce?

I have a access to multiple mac's, so I will do some more investigation over the weekend.

Morten




On Fri, Aug 14, 2015 at 6:42 AM -0700, "Eric Paris" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, I don't have a mac to reproduce, so my 'help' might not be as helpful as it otherwise could be. But I can tell you how this works on Linux systems and hopefully that will get you an answer..

So _init_completion is supplied in bash_completions v1.3 as you pointed out. On Linux its in the file /usr/share/bash-completion/bash_completion. That file has to be sourced by your bash shell before you load the kubectl completions. Again on my linux system this works because ~/.bashrc sources /etc/bashrc. /etc/bashrc in turn walks /etc/profile.d/* and sources those files. In my case there is a /etc/profile.d/bash_completion.sh which checks for the existence of /usr/share/bash-completions/bash_completion and sources it if it exists.

I have no idea how that chain is supposed to work on your mac. But find the bash_completion file provided by the bash_completions v1.3 and source it, then see if the completions work for you.

-

**Comment by goltermann** [comment] 2015-08-25 21:57
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by jtblin** [comment] 2015-09-03 19:55
On Mac, you have to install `bash-completion` with `brew` i.e. ` brew install bash-completion` then as per the install notes, add it to your `~/.bash_profile`:

```
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
```

That said even after doing that, it still doesn't work for me but I guess it isn't a `kubectl` issue.

**Comment by moander** [comment] 2015-09-03 20:00
Same for me. I have bash completion installed, and it works for any other program I have installed except for kubectl..


Morten

**Comment by eparis** [comment] 2015-09-03 20:01
what's the error?

**Comment by eparis** [comment] 2015-09-03 20:01
(and version of bash_completion)

**Comment by jtblin** [comment] 2015-09-03 20:03
Error is still `kubectl -bash: _init_completion: command not found`. I posted the question on [SO](http://stackoverflow.com/questions/32384452/kubectl-bash-init-completion-command-not-found) as well.

**Comment by jtblin** [comment] 2015-09-03 20:04
Version is `1.3`.

**Comment by eparis** [comment] 2015-09-03 20:37
any change one of you can try this patch https://gist.github.com/eparis/fd17b8fb4eb58efc2c12 ??

**Comment by eparis** [comment] 2015-09-03 20:39
you'll need to patch the kubectl completions file, source it again `. /path/to/it/kubectl` then try `kubectl [tab][tab]`

**Comment by eparis** [comment] 2015-09-03 20:43
I'm going to reopen, as this is a bug/issue  not a request for support

**Comment by jtblin** [comment] 2015-09-03 20:51
It works great with the patch, thanks @eparis!

**Comment by jtblin** [comment] 2015-09-03 20:53
Re: support vs bugs, I did find some issues have been closed lately that are real issues, not requests for support. It doesn't give the best image of the project (which is a shame as kubernetes is awesome) but I can understand as it can be hard to manage the number of issues and number of support type issues that are a better fit for SO. Thanks for your help with that, I'll answer the question on SO.

**Comment by eparis** [comment] 2015-09-03 20:54
give me 10 minutes or so and I'll have a PR you can link to that actually fixes it.

**Comment by jtblin** [comment] 2015-09-03 20:56
:+1:

**Comment by eparis** [comment] 2015-09-03 21:09
https://github.com/kubernetes/kubernetes/pull/13570

**Comment by moander** [comment] 2015-09-04 13:50
Thanks @eparis! It works :D

**Comment by kargakis** [comment] 2017-06-09 17:23
@kubernetes/sig-cli-misc

**Comment by eparis** [comment] 2017-06-10 04:49
This was fixed a long time ago. Closing.

**Closed by eparis** 2017-06-10 04:49 UTC
Labels: kind/bug, priority/awaiting-more-evidence, sig/cli, team/ux (deprecated - do not use)

**Comment by mykaul** [comment] 2017-08-17 12:34
Doesn't work for me: CentOS 7.3, bash-completion 2.1-6.el7, kubectl-1.7.3-1

**Comment by Ark-kun** [comment] 2018-08-20 22:29
Not working on Google Cloud Debian VM with bash-completion 2.1-4.3.

**Comment by unlikezy** [comment] 2019-08-02 07:26
After have done all things on https://kubernetes.io/docs/tasks/tools/install-kubectl/ on my iMac, I still got error: type _init_completion not found.
And finally I found that, although I have update my bash, and I  did got this message:
```
$which bash
/usr/local/bin/bash
$bash --version
GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
BUT, my terminal was still using old bash in fact:
```
$env
SHELL=/bin/bash
$/bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```
Need to change my default shell by typing command
```
chsh -l /usr/local/bin/bash
```
and it work.

**Comment by els-blasterspike** [comment] 2019-09-10 16:25
> Need to change my default shell by typing command
> 
> ```
> chsh -l /usr/local/bin/bash
> ```
> 
> and it work.

Did you mean `sudo chsh -s /usr/local/bin/bash` instead?
Thanks anyway for the hint!

**Comment by Rican7** [comment] 2024-02-21 01:40
@avoidik Thank you for this! I was using a new Bash version, but was still using the older (default) `bash-completion` from Homebrew. Installing the newer `bash-completion` version for my newer Bash version fixed it for me.

Simple as `brew unlink bash-completion && brew install bash-completion@2` for me!

Thanks again!
