### ISSUE TITLE
No storageclass info when using `cluster/kubectl.sh get pv` if create pvc with alpha annotation

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#41381] opened 2017-02-14 04:57 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.355+67859efaec9118-dirty", GitCommit:"67859efaec9118a04e8a42adf6de4a8850b869a0", GitTreeState:"dirty", BuildDate:"2017-02-04T06:10:14Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.355+67859efaec9118-dirty", GitCommit:"67859efaec9118a04e8a42adf6de4a8850b869a0", GitTreeState:"dirty", BuildDate:"2017-02-04T06:10:14Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
No storageclass info when using `cluster/kubectl.sh get pv` if create pvc with alpha annotation

**What you expected to happen**:
Storageclass info should displayed

**How to reproduce it** (as minimally and precisely as possible):
1.cluster/kubectl.sh create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/persistent-volumes/ebs/dynamic-provisioning/storageclass.yaml
storageclass "foo" created
2.Create pvc with alpha annotation
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "ebsc",
    "annotations": {
        "volume.alpha.kubernetes.io/storage-class": "foo"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "4Gi"
      }
    }
  }
}
3.Check pv and pvc storageclass info
[root@ip-172-18-9-70 kubernetes]# cluster/kubectl.sh get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
ebsc      Bound     pvc-6ced0725-f265-11e6-9f86-0ecb7d4ecce4   4Gi        RWO           foo            5s
[root@ip-172-18-9-70 kubernetes]# cluster/kubectl.sh get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM          STORAGECLASS   REASON    AGE
pvc-6ced0725-f265-11e6-9f86-0ecb7d4ecce4   4Gi        RWO           Delete          Bound     default/ebsc                            13s

**Anything else we need to know**:

**Comment by screeley44** [comment] 2017-02-14 05:11
I'll take a look at this

**Comment by screeley44** [comment] 2017-02-14 14:11
@chao007 - so the beta annotation works for OCP 3.4?  And only the alpha annotation doesn't show up?

**Comment by screeley44** [comment] 2017-02-15 00:48
@chao007 - the PV does not contain the alpha annotation when used for dynamic provisioning - not sure if this is a bug or by design.  The PV object does contain the beta annotation if used however.

alpha annotation PV:
```
# kubectl get pv pvc-b8170acf-f313-11e6-a5e4-0e35460a0dc4 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  creationTimestamp: 2017-02-15T00:14:31Z
  labels:
```

beta annotation PV:
```
# kubectl get pv pvc-d577675d-f313-11e6-a5e4-0e35460a0dc4 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.beta.kubernetes.io/storage-class: slow
```
@jsafrane - is there a reason we are not updating the annotation on a PV for alpha provisioning?  If not, let me know and I'll create a PR to handle

**Comment by jsafrane** [comment] 2017-02-16 12:22
Volumes created by alpha dynamic provisioning do not belong to any storage class, therefore they do not have any class annotation. Alpha annotation is just a trigger for provisioning and the value does not matter.

**Comment by screeley44** [comment] 2017-02-16 18:17
should we indicate that on the resource printer at least keying off of *pv.kubernetes.io/provisioned-by* ?  Something like

```
... ACCESSMODES   STORAGECLASS ...
... RWO           alpha-provisioned ...
```

@jsafrane @childsb @eparis ?

**Comment by msau42** [comment] 2017-08-05 00:24
Can this be closed? StorageClass is now GA and we deprecated/removed the alpha annotation.

**Comment by jsafrane** [comment] 2017-08-07 15:08
closing, alpha annotation is now deprecated.

**Closed by jsafrane** 2017-08-07 15:08 UTC
Labels: sig/storage
