### ISSUE TITLE
kubedns doesn't start because of label kubernetes.io/cluster-service: "true"

### ISSUE THREAD

**Issue by yolkov** [kubernetes/kubernetes#33894] opened 2016-10-02 16:55 UTC
BUG REPORT:

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: 3 baremetal nodes
- **OS** (e.g. from /etc/os-release): debian jessie
- **Kernel** (e.g. `uname -a`): Linux avi-app68 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
- **Install tools**:  kubelet as systemd service, others from manifests pods
- **Others**: calico network

**What happened**:
`cat kubedns-deployments.yaml`

``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    #kubernetes.io/cluster-service: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
      version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
        #kubernetes.io/cluster-service: "true"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      #nodeSelector:
      #  kube-role: master
      volumes:
        - name: ssl-certs-kubernetes
          hostPath:
            path: /etc/kubernetes/ssl
        - name: kubeconfig
          hostPath:
            path: /etc/kubernetes/kubeconfig.yaml
      containers:
        - name: kubedns
          image: gcr.io/google_containers/kubedns-amd64:1.8
          resources:
            # TODO: Set memory limits when we've profiled the container for large
            # clusters, then set request = limit to keep this container in
            # guaranteed class. Currently, this container falls into the
            # "burstable" category so the kubelet doesn't backoff from restarting it.
            limits:
              cpu: 100m
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          livenessProbe:
            httpGet:
              path: /healthz-kubedns
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
              scheme: HTTP
            # we poll on pod startup for the Kubernetes master service and
            # only setup the /readiness HTTP server once that's available.
            initialDelaySeconds: 30
            timeoutSeconds: 5
          args:
          # command = "/kube-dns"
          - --domain=dev.k8s
          - --dns-port=10053
          - --kubecfg-file=/etc/kubernetes/kubeconfig.yaml
          - --v=2
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/kubernetes/kubeconfig.yaml
            name: kubeconfig
            readOnly: true
          ports:
          - containerPort: 10053
            name: dns-local
            protocol: UDP
          - containerPort: 10053
            name: dns-tcp-local
            protocol: TCP
        - name: dnsmasq
          image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4
          livenessProbe:
            httpGet:
              path: /healthz-dnsmasq
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          args:
          - --cache-size=1000
          - --no-resolv
          - --server=127.0.0.1#10053
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
        - name: healthz
          image: gcr.io/google_containers/exechealthz-amd64:1.2
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          args:
          - --cmd=nslookup kubernetes.default.svc.dev.k8s 127.0.0.1 >/dev/null
          - --url=/healthz-dnsmasq
          - --cmd=nslookup kubernetes.default.svc.dev.k8s 127.0.0.1:10053 >/dev/null
          - --url=/healthz-kubedns
          - -port=8080
          #- -quiet
          ports:
          - containerPort: 8080
            protocol: TCP
      dnsPolicy: Default
```

if I create this deployments:
`kubectl create -f kubedns-deployments.yaml`
it's ok
If I uncomment `#kubernetes.io/cluster-service: "true"`, then pods started and immediately terminated.

**What you expected to happen**:
I want start kubedns as addon

**Comment by tyranron** [comment] 2016-10-03 13:11
Accordingly to [cluster add-ons description](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons) it seems that only Services and Replication Controllers can be add-ons. I think there is a conflict in naming conventions applied to cluster add-ons and Replication Controllers created by your Deployment.

**Comment by MrHohn** [comment] 2016-10-12 22:03
Your `kubedns` deployment was deleted by the addon manager.

I assume that your yaml file is not being put under /etc/kubernetes/addons on the master node. Addon manager will try to maintain the running addons to be the same as the configuration files under the addons folder. If your deployment have `kubernetes.io/cluster-service: "true"` label and under `kube-system` namespace, addon manager would consider it as a running addon. Since its configuration file is not in that folder, addon manager will then delete it.

@tyranron Current addon manager support `ReplicationController`, `Deployment`, `DaemonSet`, `PetSet`, `Service`, `PersistentVolume` and `PersistentVolumeClaim`. We are working on the upgrade and it will support almost all resource types in near future.

**Comment by yolkov** [comment] 2016-10-14 22:26
>I assume that your yaml file is not being put under /etc/kubernetes/addons on the master node. 
No, I put the yaml in /etc/kubernetes/addons.
If I uncomment a line kubernetes.io/cluster-service: "true", then pods created and immediately terminated.
If I comment out the line, then pods, deployment not created.

**Comment by MrHohn** [comment] 2016-10-14 22:50
Hmm, that is weird. In theory, if configuration file got put under the correct path, the Addon Manager should create it automatically.

Was there another kube-dns addon running? Are the other addons' configuration files put in the same place? Were they running properly?

And was there any suspicious error in Addon Manager's logs?

**Comment by yolkov** [comment] 2016-10-14 22:55
>Was there another kube-dns addon running?

no

```
INFO: Creating new Deployment from file /etc/kubernetes/addons/kubedns-deployments.yaml in namespace kube-system, name: kube-dns-v20
deployment "kube-dns-v20" created
INFO: == Kubernetes addon update completed successfully at 2016-10-14T22:51:50+0000 ==
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
INFO: Creating new Deployment from file /etc/kubernetes/addons/kubedns-deployments.yaml in namespace kube-system, name: kube-dns-v20
deployment "kube-dns-v20" created
INFO: == Kubernetes addon update completed successfully at 2016-10-14T22:52:50+0000 ==
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
error: name cannot be provided when a selector is specified
INFO: Creating new Deployment from file /etc/kubernetes/addons/kubedns-deployments.yaml in namespace kube-system, name: kube-dns-v20
deployment "kube-dns-v20" created
INFO: == Kubernetes addon update completed successfully at 2016-10-14T22:53:51+0000 ==
```

**Comment by MrHohn** [comment] 2016-10-14 23:40
Thanks for the log.

Seems like it is not Addon Manager who deleting it. I'm not aware of what other components are also using label `kubernetes.io/cluster-service: "true"` to manage resource (except `kubectl cluster-info`, but it is not deleting things). I will try to reproduce it.

BTW, your YAML file does not include the exec-healthz container but you are still specifying liveness probe for the other two containers, which will go wrone. But I guess you just didn't paste it completely.

**Comment by yolkov** [comment] 2016-10-14 23:50
I updated the config kubedns-deployment on top. I get it from https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.base.

logs from another addon-manager:
```
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:38:18+0000 ==
INFO: Deleting Service kube-system/kube-dns
INFO: Deleting Deployment kube-system/kube-dns-v20
service "kube-dns" deleted
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:39:18+0000 ==
INFO: Deleting Deployment kube-system/kube-dns-v20
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:40:18+0000 ==
INFO: Deleting Deployment kube-system/kube-dns-v20
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:41:18+0000 ==
INFO: Deleting Service kube-system/kube-dns
INFO: Deleting Deployment kube-system/kube-dns-v20
service "kube-dns" deleted
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:42:19+0000 ==
INFO: Deleting Deployment kube-system/kube-dns-v20
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:43:18+0000 ==
INFO: Deleting Deployment kube-system/kube-dns-v20
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:44:18+0000 ==
INFO: Deleting Service kube-system/kube-dns
INFO: Deleting Deployment kube-system/kube-dns-v20
service "kube-dns" deleted
deployment "kube-dns-v20" deleted
INFO: == Kubernetes addon update completed successfully at 2016-10-14T23:45:18+0000 ==
```

**Comment by MrHohn** [comment] 2016-10-15 00:14
Wait, what do you mean by another addon manager? There should be only one addon manager running, right?

Or you mean the logs in another case. Could you please tell me which log corresponding to which case?

**Comment by yolkov** [comment] 2016-10-15 01:19
thanks!!!

I ran 3 addon-manager on the master nodes. I killed the extra addon-manager. It worked.

**Comment by MrHohn** [comment] 2016-10-15 02:34
Surprise to know that! When you said `the master nodes`, do you mean you also have multiple master nodes? We expect only one master node in one cluster, and others should be non-master nodes. Just wanna make sure.

**Comment by yolkov** [comment] 2016-10-15 14:59
I've installed according to instructions https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md

**Comment by MrHohn** [comment] 2016-10-16 17:40
Sorry for the delay.

I see, the instructions are running the master components on three different `controller` nodes, interesting. I believe this is good.

For the errors in your logs. I think there was some conflicts between the resources this addon manager were trying to create and thoses resources created by the others addon manager before. I would say if you try again to spin up a new kubernetes cluster with proper steps (and start only one addon manager), everything should be fine?

**Comment by yolkov** [comment] 2016-10-16 19:41
Thanks for your reply.

I'll try later when I will setup another kubernetes cluster.

**Comment by thockin** [comment] 2016-11-21 18:52
Can we close this now?

**Closed** 2016-11-21 20:23 UTC
Labels: component/apiserver, team/cluster
