### ISSUE TITLE
Deployment doesn't create new replica set nor give any error

### ISSUE THREAD

**Issue by blixt** [kubernetes/kubernetes#36117] opened 2016-11-03 00:06 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

I'm hoping that this issue will resolve the problem I'm seeing.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`deployment`, `replica set`, `OldReplicaSets`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Google Container Engine

**What happened**:

I ran `kubectl apply -f` as usual to apply any changes to Deployment, Service, Ingress resources. The deployment did not create a new replica set with the updated container image. Going to the Kubernetes Dashboard I can confirm that the deployment was correctly updated with the new metadata.

The only difference when this issue started happening was a small code change.

I've tried multiple updates since and nothing changed. The nodes were on version 1.4.0 but I've tried updating them to 1.4.5 but still the same issue is happening.

The old pods are still operational and serving requests normally.

**What you expected to happen**:

The deployment should have created a new replica set with three pods, then rolled them out.

**How to reproduce it** (as minimally and precisely as possible):

I don't know.

**Anything else do we need to know**:

I've attached a file with the deployment's current configuration, as well as the deploy script I use to deploy: [files.zip](https://github.com/kubernetes/kubernetes/files/567982/files.zip)

Here's the output of `kubectl describe`:

```
$ kubectl describe deployment/fika-io
Name:			fika-io
Namespace:		default
CreationTimestamp:	Sun, 16 Oct 2016 10:58:42 -0400
Labels:			app=fika-io
Selector:		app=fika-io
Replicas:		3 updated | 3 total | 3 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
OldReplicaSets:		fika-io-749979362 (3/3 replicas created)
NewReplicaSet:		<none>
No events.
```

Note that there is no `NewReplicaSet`.

**Comment by blixt** [comment] 2016-11-03 00:33
Here's the rollout status of me trying to switch between different Docker image tags. The images after the last working one just leaves rollout status hanging on "Waiting for deployment spec update to be observed..." but if I change to the one before the working one I see "Waiting for rollout to finish".

So it seems that it's hanging with the new images, but nothing changed in the `Dockerfile` or the spec between the working version and the non-working ones (only relatively small code changes).

```
$ kubectl rollout status deployment/fika-io
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for rollout to finish: 1 out of 3 new replicas have been updated...
Waiting for rollout to finish: 1 out of 3 new replicas have been updated...
Waiting for rollout to finish: 2 out of 3 new replicas have been updated...
deployment fika-io successfully rolled out
deployment fika-io successfully rolled out
```

**Comment by smarterclayton** [comment] 2016-11-03 01:22
@kubernetes/deployment

**Comment by kargakis** [comment] 2016-11-03 09:37
Can you paste the logs from the controller manager?

**Comment by blixt** [comment] 2016-11-03 14:07
@kargakis Since the master node is managed outside my project by Google Container Engine, is there another way for me to access the controller manager logs than to look at `/var/log/kube-controller-manager.log` (e.g., via `kubectl`)?

**Comment by kargakis** [comment] 2016-11-03 14:46
@blixt I am not sure if there is a way, I don't think `kubectl` can do something like that. @bgrant0607 do we have a process for getting any logs from GCE for user reports?

**Comment by bgrant0607** [comment] 2016-11-03 15:57
cc @janetkuo

**Comment by amlinux** [comment] 2016-11-04 05:33
Same here. It's currently happening in my project. I can't reload anything. "kubectl apply -f" on any deployment doesn't work. "kubectl edit deployment" doesn't work either. The changes I make are saved in the deployment, but it doesn't have any effect on the replica sets.

**Comment by kargakis** [comment] 2016-11-04 09:58
Maybe related to https://github.com/kubernetes/kubernetes/issues/29735. Failed creation of the new rs is one of the few cases in the controller where we don't update observedGeneration for the deployment. We also don't emit any event which is bad. Event and deployment condition for the particular case is added in https://github.com/kubernetes/kubernetes/pull/35691

**Comment by amlinux** [comment] 2016-11-04 14:21
I noticed that old replica sets are not removed when a deployment rollout completes. My project has already accumulated more than 500 old RSes. When I cleaned up some of them, deployments got unstuck. Maybe there is some mechanism that prevents creation of new RSes if there are too many of them already?

**Comment by kargakis** [comment] 2016-11-04 14:31
@amlinux specify the number of old replica sets you want to retain in the deployment spec (revisionHistoryLimit).

**Comment by blixt** [comment] 2016-11-04 15:25
Okay I think there may be something to the replica sets number. Today I managed to deploy a copy of the image that was previously broken, and I think this is the significant sequence of events:

1. Set `revisionHistoryLimit: 5`
2. `kubectl set image deployment/fika-io fika-io=gcr.io/roger-api/fika-io:2016-11-02-001` (an image that had previously successfully rolled out)
3. Wait for Kubernetes to prune the old replica sets
4. Republish the image that won't deploy with a new tag
5. Apply a new deployment with the new image

I had previously tried publishing a new version while the deployment was in a broken state, after changing `revisionHistoryLimit` to 5, and that did not fix the problem. It seems the RCs were only pruned once I reverted to an image that had previously been working, and then when I deployed the exact same image (but with a new tag), it all worked.

**Comment by amlinux** [comment] 2016-11-05 07:13
+1 to what blixt said. Changing revisionHistoryLimit is not enough to unstick the deployment. Only when I cleaned up all replica sets with kubectl delete $(kubectl -o name get rs), on replica set was created, and then everything worked again.

It seems the actual problem is that deployments are somehow confused by too many old replica sets.

**Comment by ehacke** [comment] 2016-12-16 13:18
For anyone else running into this issue. If your deployment does not seem to work, do the following:

1. Ensure your deployment is reset back to the last successful deployment (not sure this is 100% required)
2. Use `kubectl get rs` to find all replica sets for that deployment
3. You should see a bunch of extra replica sets that have their `Desired` value at 0, delete all of those
4. Reattempt the deployment with a new version of the image, it should work now

Seems the issue might be that the old replica sets are not being cleaned up, and when their number exceeds the revisionHistoryLimit, the deployments stop working.

**Comment by yaoyaozong** [comment] 2016-12-16 19:54
I met the same problem on the container in Google Cloud. and following the @ehacke 's way, it resolved my problem. (no need for Step#1. I skipped it. :) )

**Comment by amlinux** [comment] 2016-12-16 20:08
Don't forget to set revisionHistoryLimit to 5 or other reasonable value on all your deployments to avoid reoccurence of this problem in future. Default value is "unlimited", and it doesn't work.

**Comment by yaoyaozong** [comment] 2016-12-16 22:13
Thanks @amlinux, already added. ^_^

**Comment by kargakis** [comment] 2016-12-17 11:54
Assuming Deployments were using a hashing algorithm that wasn't breaking that fast when brute-forced (https://github.com/kubernetes/kubernetes/issues/29735#issuecomment-254470553), the existence of hundreds of ReplicaSets shouldn't be a problem. We expect though that in production environments, quota will restrict the number of the existing ReplicaSets in a namespace (https://github.com/kubernetes/kubernetes/issues/33650 - https://github.com/kubernetes/kubernetes/pull/29986) and coupled with a sane default (https://github.com/kubernetes/kubernetes/issues/23597 - https://github.com/kubernetes/kubernetes/pull/34339) this issue shouldn't be a problem. That being said, I have a PR open for staging a migration for existing Deployments to use a more stable hashing algorithm (https://github.com/kubernetes/kubernetes/pull/38714).

Closing this as a dupe of https://github.com/kubernetes/kubernetes/issues/29735.

**Closed by kargakis** 2016-12-17 11:54 UTC
Labels: area/workload-api/deployment, sig/apps

**Comment by huangjiasingle** [comment] 2018-01-02 08:39
@kargakis l meet the some problem in my pro k8s cluster, it's not alway happen,  maybe first time happend,the deploy's rs has 378.  the next time doesn't happend, the deploy's rs has 380 or 379.  
in my problem , the old latest version rs's pod hangling Terminating, the new rs doen't create.
the rolling update Params :  maxSurge = 1 maxUnavaible =0 .

**Comment by kargakis** [comment] 2018-01-02 08:51
@huangjiasingle open a new issue with the version of your cluster and logs from the controller manager when you reproduce this and tag `@kubernetes/sig-apps-bugs`

**Comment by huangjiasingle** [comment] 2018-01-02 11:54
@kargakis ok, l viewed the code of deployment controller, the logic is:   syncDeployment() - > rolloutRolling() -> getAllReplicaSetsAndSyncRevision(), getAllReplicaSetsAndSyncRevision() the paramter  **createIfNotExisted** is true , so it should  alway create a newRS,  the controller's log doesn's has err log information,  l will  change the log level  tomorrow.   l also will review the code of deployment_controller.go detail.  thank you very much.  

l hope resovle this problem  with your help

**Comment by huangjiasingle** [comment] 2018-01-25 09:28
@kargakis l open a new issue https://github.com/kubernetes/kubernetes/issues/58801, l found the deploy-controller create the new rs too late ,so l think the new rs doesn't created before

**Comment by abdennour** [comment] 2018-02-19 12:39
I assume you are using `namespace` in some commands and you forgot to use it in other commands.
Make sure to use the same namespace `--namespace YOUR_SPACE`

**Comment by StarpTech** [comment] 2020-10-22 18:05
We faced with the exact same behavior as described in https://github.com/kubernetes/kubernetes/issues/36117#issuecomment-267592278 and the solution was to delete all old replicaSets. This looks like a serious issue in Kubernetes.

OS Image Debian GNU/Linux 9 (stretch)
Kubelet version v1.17.0
Kernel version 4.9.0-11-amd64

**Comment by keke8273** [comment] 2021-01-29 00:54
Same issue here. My deployment started to create new replicaSet after I set `revisionHistoryLimit` in the manifest file.

**Comment by billmetangmo** [comment] 2021-11-30 16:02
Same for me but i needed to restart kube master nodes

**Comment by bajoben** [comment] 2022-07-19 15:54
Same here with Kubernetes v1.21.2. Deleted all replicasets and restartet all master nodes. Cluster lit up like a christmas  tree but then it worked fine.
