### ISSUE TITLE
[Flaking Test] Kubernetes e2e suite.[It] [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [kubernetes/kubernetes#125281] opened 2024-06-02 14:22 UTC
### Which jobs are flaking?

```
 ci-kubernetes-e2e-gci-gce prowjob_config_url: https://git.k8s.io/test-infra/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml prowjob_description: Uses kubetest to run e2e tests (-Slow|Serial|Disruptive|Flaky|Feature) against a cluster created with cluster/kube-up.sh
```

### Which tests are flaking?

```
Kubernetes e2e suite.[It] [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
```

### Since when has it been flaking?

7:41 AM US EST on June 2nd, 2024

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default

### Reason for failure (if possible)

Based on the error, it looks like it's looking for some backwards compatibility for Kubernetes v1.17.

This is the first failure line from Triage
```
[FAILED] could not find group version resource for dynamic client and wardle/flunders
```

### Anything else we need to know?

Full error output via Triage.

```
[FAILED] could not find group version resource for dynamic client and wardle/flunders (discovery error: unable to retrieve the complete list of server APIs: wardle.example.com/v1alpha1: stale GroupVersion discovery: wardle.example.com/v1alpha1, discovery results: map[schema.GroupVersionResource]struct {}{schema.GroupVersionResource{Group:"", Version:"v1", Resource:"bindings"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"configmaps"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"endpoints"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"limitranges"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"persistentvolumeclaims"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"pods"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"podtemplates"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"replicationcontrollers"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"resourcequotas"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"secrets"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"serviceaccounts"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"services"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"controllerrevisions"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"daemonsets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"deployments"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"replicasets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"statefulsets"}:struct {}{}, schema.GroupVersionResource{Group:"authorization.k8s.io", Version:"v1", Resource:"localsubjectaccessreviews"}:struct {}{}, schema.GroupVersionResource{Group:"autoscaling", Version:"v2", Resource:"horizontalpodautoscalers"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"cronjobs"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"jobs"}:struct {}{}, schema.GroupVersionResource{Group:"coordination.k8s.io", Version:"v1", Resource:"leases"}:struct {}{}, schema.GroupVersionResource{Group:"crd.projectcalico.org", Version:"v1", Resource:"networkpolicies"}:struct {}{}, schema.GroupVersionResource{Group:"crd.projectcalico.org", Version:"v1", Resource:"networksets"}:struct {}{}, schema.GroupVersionResource{Group:"discovery.k8s.io", Version:"v1", Resource:"endpointslices"}:struct {}{}, schema.GroupVersionResource{Group:"events.k8s.io", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"metrics.k8s.io", Version:"v1beta1", Resource:"pods"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"ingresses"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"networkpolicies"}:struct {}{}, schema.GroupVersionResource{Group:"policy", Version:"v1", Resource:"poddisruptionbudgets"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"rolebindings"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"roles"}:struct {}{}, schema.GroupVersionResource{Group:"storage.k8s.io", Version:"v1", Resource:"csistoragecapacities"}:struct {}{}})
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:485 @ 05/24/24 04:05:35.467
```

### Relevant SIG(s)

/sig-cloud-provider

**Comment by userAdityaa** [comment] 2024-06-02 16:28
Hey, I'm new to contributing to open source. Can you help me with understanding of what the issue is about ?

**Comment by Vyom-Yadav** [comment] 2024-06-04 04:47
Duplicate of https://github.com/kubernetes/kubernetes/issues/119582
/close

**Closed by Vyom-Yadav** 2024-06-04 04:47 UTC
Labels: sig/api-machinery, kind/flake, needs-triage
