### ISSUE TITLE
Seeing OOMs on small nodes (g1-small) for node agents

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#52107] opened 2017-09-07 19:31 UTC
Seems to be a regression on the kubelet-side. Ref job - https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance

Run 27 was fine (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/27/artifacts/PodStartupLatency_density_2017-09-04T10:24:45Z.json) -

```
      "data": {
        "Perc100": 4482.739935,
        "Perc50": 1776.387197,
        "Perc90": 2446.611714,
        "Perc99": 3139.68287
      },
      "unit": "ms",
      "labels": {
        "Metric": "pod_startup"
      }
```

Run 28 regressed (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/28/artifacts/PodStartupLatency_density_2017-09-06T20:20:22Z.json) -

```
      "data": {
        "Perc100": 25293.880645,
        "Perc50": 1800.683666,
        "Perc90": 2571.957657,
        "Perc99": 16023.080663
      },
      "unit": "ms",
      "labels": {
        "Metric": "pod_startup"
      }
```

cc @kubernetes/sig-node-bugs @kubernetes/sig-scalability-misc @yujuhong @Random-Liu 

I'm looking at the [diff](https://github.com/kubernetes/kubernetes/compare/034c40be6f465d...150a560eed43a1) to find the fauilty PR. Any leads would be appreciated :)

**Comment by shyamjvs** [comment] 2017-09-07 19:48
From kubelet logs on one of the nodes (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/28/artifacts/gce-scale-cluster-minion-group-0pvz/kubelet.log), I'm seeing the following error:

```
E0906 07:30:49.326834    1555 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0906 07:30:49.329743    1555 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
```

**Comment by shyamjvs** [comment] 2017-09-07 19:51
Also seeing some failing inotify events (trying to understand what's happening):

```
W0906 17:00:24.781349    1555 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/kube-logrotate.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/kube-logrotate.service: no such file or directory
W0906 17:00:24.781619    1555 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/kube-logrotate.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/kube-logrotate.service: no such file or directory
W0906 17:00:24.781854    1555 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/kube-logrotate.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/kube-logrotate.service: no such file or directory
```

**Comment by shyamjvs** [comment] 2017-09-07 19:56
From the previous error, appears like it's failing to get docker config from metadata server. I'm suspicious about this PR which bumped the version of metadata-proxy - https://github.com/kubernetes/kubernetes/pull/50647
cc @ihmccreery

**Comment by yujuhong** [comment] 2017-09-07 20:21
Not sure if this is related, but event-exporter on one of the (not-ready) nodes caused system memory to be low.
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/28/artifacts/gce-scale-cluster-minion-group-2-zcs1/
```
Out of memory: Kill process 12714 (event-exporter) score 1674 or sacrifice child
Killed process 12714 (event-exporter) total-vm:2199988kB, anon-rss:1176056kB, file-rss:0kB
```
It was using more than 1GB of memory. 

On the same node, kube-proxy also got oom-killed(?).

I don't think we can reasonably measure the performance if the cluster is so unstable...

**Comment by yujuhong** [comment] 2017-09-07 21:45
Found a TODO to add resource limit to event-exporter: https://github.com/kubernetes/kubernetes/blob/v1.8.0-beta.0/cluster/addons/fluentd-gcp/event-exporter.yaml#L49
/cc @crassirostris

**Comment by shyamjvs** [comment] 2017-09-07 22:32
Digged up a bit to roughly find the 99th %ile for individual parts of pod-startup time:

- create->schedule latency : 2s (we have this value only upto second granularity)
- schedule->running latency : 2s (also second granularity)
- running->watch event delivered latency : 4.97s (the real problem)

In general, the tail latencies for watch event delivery seems quite high:

```
{density-latency-pod-1437-2n57s gce-scale-cluster-minion-group-2-000b 16.914496412s}
{density-latency-pod-1430-jqrt8 gce-scale-cluster-minion-group-3-8zf5 16.914896475s}
{density-latency-pod-1427-s78ft gce-scale-cluster-minion-group-4-6l2j 16.915326008s}
{density-latency-pod-1416-rkmch gce-scale-cluster-minion-group-1-tv6w 16.915970428s}
{density-latency-pod-1426-m5s4f gce-scale-cluster-minion-group-4-dn0g 16.917057933s}
{density-latency-pod-1424-gfvjh gce-scale-cluster-minion-group-7w6w 16.917376928s}
{density-latency-pod-1433-2h8fn gce-scale-cluster-minion-group-2-vdtc 16.91767879s}
{density-latency-pod-1420-7pbpv gce-scale-cluster-minion-group-w8dx 17.213268787s}
{density-latency-pod-1439-vcpfv gce-scale-cluster-minion-group-1-6lx9 17.251210845s}
{density-latency-pod-1358-qhfmx gce-scale-cluster-minion-group-2-zrt0 20.153229837s}
```

Normally the highest tail latency is < 3s. Seems like the apiserver is overloaded (but that looked to be the case for the previous run too, though it still had low latency).

cc @kubernetes/sig-api-machinery-bugs @wojtek-t - Are you aware of any recent changes that could've led to this?

**Comment by shyamjvs** [comment] 2017-09-07 22:36
Moving this from sig-node to api-machinery based on the above evidence.

**Comment by shyamjvs** [comment] 2017-09-07 23:26
Difference in resource-usage across the 2 runs during density test:

Before:

```
  "99": [
    {
      "Name": "etcd-events",
      "Cpu": 0.838961654,
      "Mem": 3,657,662,464
    },
    {
      "Name": "etcd",
      "Cpu": 1.117272041,
      "Mem": 13,611,061,248
    },
    {
      "Name": "apiserver",
      "Cpu": 10.125682466,
      "Mem": 34,463,993,856
    },
    {
      "Name": "controller-manager",
      "Cpu": 3.58193252,
      "Mem": 6,975,000,576
    },
    {
      "Name": "scheduler",
      "Cpu": 7.904524636,
      "Mem": 4,343,283,712
    },
```

Now:

```
  "99": [
    {
      "Name": "etcd-events",
      "Cpu": 0.71045827,
      "Mem": 4,530,171,904
    },
    {
      "Name": "etcd",
      "Cpu": 0.786903986,
      "Mem": 7,685,632,000
    },
    {
      "Name": "apiserver",
      "Cpu": 10.271745948,
      "Mem": 35,635,597,312
    },
    {
      "Name": "controller-manager",
      "Cpu": 4.210303752,
      "Mem": 9,394,192,384
    },
    {
      "Name": "scheduler",
      "Cpu": 8.540504537,
      "Mem": 4,339,539,968
    },
```

Etcd-events is using more memory (which we saw happen even earlier when something goes wrong and the system creates increasingly more and more events load) - though https://github.com/kubernetes/kubernetes/pull/47367 should've helped reduce events spam from client-side. cc @derekwaynecarr Maybe you have some insights here?

I'm more surprised about etcd using double the memory (given that it's supposedly not handling any event load).

**Comment by shyamjvs** [comment] 2017-09-07 23:28
I'll continue looking into it tomorrow.

cc @gmarek

**Comment by wojtek-t** [comment] 2017-09-08 19:09
As we discussed offline with @shyamjvs - the "watch latencies" is misleading there, because it can also mean, things like "slow kubelet, "throttled client in kubelet" and a couple other things.

I suggested to take a look into few particular pods that were responsible for this long latency and track what exactly was happening with them in apiserver, scheduler and kubelet logs.

**Comment by gmarek** [comment] 2017-09-11 08:44
Controller manager's resource usage seems suspiciously high as well, which suggests it's the component either emitting additional Events or is responding to them. Either way it's logs may tell us what's wrong.

**Comment by lavalamp** [comment] 2017-09-11 21:21
cc @mml 

We're not convinced this is API machinery?

**Comment by shyamjvs** [comment] 2017-09-11 21:36
Even I'm not yet sure about it. Will dig into it tomorrow.

@wojtek-t @gmarek Thanks for those useful leads.

**Comment by wojtek-t** [comment] 2017-09-12 06:19
@lavalamp - I'm not convinced. But didn't dig into that. @shyamjvs is looking into it, but based on what we told me offline, my hypothesis would be something different.

**Comment by shyamjvs** [comment] 2017-09-13 15:58
To experiment I increased the node size and the resource usage seems much better now:

With g1-small:

```
"99": [
    {
      "Name": "etcd-events",
      "Cpu": 0.735745202,
      "Mem": 3499872256
    },
    {
      "Name": "etcd",
      "Cpu": 1.066569241,
      "Mem": 13754146816
    },
    {
      "Name": "apiserver",
      "Cpu": 10.548744125,
      "Mem": 35721170944
    },
```

With n1-standard-1:

```
  "99": [
    {
      "Name": "etcd-events",
      "Cpu": 0.790590453,
      "Mem": 2220400640
    },
    {
      "Name": "etcd",
      "Cpu": 0.805094177,
      "Mem": 7026974720
    },
    {
      "Name": "apiserver",
      "Cpu": 8.249934247,
      "Mem": 31351058432
    },
```

Increasing the node memory reduced kubelet's oom-killings (we were earlier seeing them e.g for event-exporter and kube-proxy (https://github.com/kubernetes/kubernetes/issues/52107#issuecomment-327916932)). And oom-killings on nodes generate a tremendous amount of events and node-update qps on the api-server (https://github.com/kubernetes/kubernetes/issues/47899). The decrease in memory usage of etcd-events by one-third and etcd by half explains how much the effect of those calls are. Overall the latencies for api calls also improved with the change.

This is part of the problem (and we should try to understand why those node agents are ooming - cc @kubernetes/sig-node-bugs ).
There might be one more regression here as 'patch node-status' calls are still breaking the SLO in the density test:

```
I0913 04:25:00.344] Sep 13 04:25:00.342: INFO: WARNING Top latency metric: {Resource:nodes Subresource:status Verb:PATCH Latency:{Perc50:3.516ms Perc90:17.293ms Perc99:1.09619s Perc100:0s} Count:3794857}
```

**Comment by dchen1107** [comment] 2017-09-13 17:25
OOM events from node generated by NPD: https://github.com/kubernetes/kubernetes/issues/47899#issuecomment-310468114

**Comment by yujuhong** [comment] 2017-09-13 17:40
> event-exporter and kube-proxy

These pods do *not* have memory limits. They were causing system OOM issues and stressed the nodes -- the nodes are expected to be slow and unresponsive. If any of the pods under test are on those nodes, it'd not be surprising the status reporting latency is long.  Of course, the OOM events could cause second effects and increase the load on etcd.

As for why these pods were using so much memory and whether that's expected, I think @kubernetes/sig-network-bugs and @kubernetes/sig-instrumentation-bugs would have better ideas.

**Comment by shyamjvs** [comment] 2017-09-15 13:30
We're not seeing the issue with high pod-startup latencies anymore with n1-standard-1s. Continuing the discussion for increased api call latencies (which is a separate issue) in https://github.com/kubernetes/kubernetes/issues/51899. Removing the release-blocker label and 1.8 milestone.

cc @wojtek-t @dims

**Comment by dims** [comment] 2017-09-15 13:52
w00t! thanks @shyamjvs

**Comment by shyamjvs** [comment] 2017-09-15 14:09
/unassign
/assign @bowei @crassirostris 
for event-exporter and kube-proxy respectively. Feel free to redirect it as apt.

ref @yujuhong's comment - https://github.com/kubernetes/kubernetes/issues/52107#issuecomment-329242797

**Comment by bowei** [comment] 2017-09-15 19:29
I'm not sure if ascribing the usage to the kube-proxy necessarily makes sense. Is the cause due to increase memory usage in general or kube-proxy increasing its memory footprint? It may simply be the pod that ends up OOMing due to some other system daemon using more memory than before.

**Comment by crassirostris** [comment] 2017-09-15 19:34
Event-exporter problem should be fixed now: https://github.com/kubernetes/kubernetes/pull/52263

**Comment by shyamjvs** [comment] 2017-09-18 12:23
@bowei Sounds reasonable - should be verifiable. After the release I'll try switching to a smaller node again and see what's causing the mischief.

**Comment by porridge** [comment] 2017-10-25 16:44
@shyamjvs what's the status of this?

**Closed** 2018-03-24 18:11 UTC
Labels: kind/bug, lifecycle/rotten, sig/instrumentation, sig/network, sig/node, sig/scalability
