### ISSUE TITLE
Too many evicted pods in nodes with low resource

### ISSUE THREAD

**Issue by zhangdb-git** [kubernetes/kubernetes#88304] opened 2020-02-19 03:35 UTC
When one node is low on resource, some pods will be evicted to other nodes, but the pod with evicted status is still in this node and created more and more pods in this node. Before the resource pressure resolved, hundreds of pods with evicted status could be created.

```
NAME                                                    READY   STATUS             RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
influxdb-influxdb-75956dbd88-9rqsv                      0/1     Evicted            0          4d23h   <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-9wnlh                      1/1     Running            4          17h     10.233.91.105   k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-gfnzs                      0/1     Evicted            0          5d17h   <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-h4nw7                      0/1     Evicted            0          39h     <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-jkn42                      0/1     Evicted            0          39h     <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-jqdxm                      0/1     Evicted            0          5d17h   <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-mgvzb                      0/1     Evicted            0          33d     <none>          k8s1   <none>           <none>
influxdb-influxdb-75956dbd88-t6lj5                      0/1     Evicted            0          5d19h   <none>          k8s1   <none>           <none>
```

Why try so many times to create pods in nodes which are low on resource? Or we should clear evicted pods on time.

**Environment**:
- Kubernetes version: 1.14.6
- OS: CentOS 7.3

**Comment by henryon** [comment] 2020-02-19 05:50
might be the pod are allowed to deployed on this node with label selector?

**Comment by moonek** [comment] 2020-02-24 07:00
is this a duplicate of #55051, #54525

**Closed** 2020-07-23 09:00 UTC
Labels: kind/bug, lifecycle/rotten, sig/scheduling
