### ISSUE TITLE
e2e flake: "Services should be able to change the type and nodeport settings of a service"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18337] opened 2015-12-08 09:15 UTC
This test started constantly failing, mostly with the following error:

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:597 Expected error: <*errors.errorString | 0xc20846f1f0>: { s: "service mutability-service-test in namespace e2e-tests-services-naqmz doesn't have a LoadBalancer ingress point after 1200.00 seconds", } service mutability-service-test in namespace e2e-tests-services-naqmz doesn't have a LoadBalancer ingress point after 1200.00 seconds not to have occurred

Example failure (both GKE and GCE parallel):

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12540/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12541/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12542/

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9859/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9858/

@kubernetes/goog-cluster

**Comment by gmarek** [comment] 2015-12-08 09:44
@thockin please triage

**Comment by wojtek-t** [comment] 2015-12-08 09:46
It seems to also fail in 1.0 release:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.0/2490/console

So maybe it is related to GCE-networking?

**Comment by wojtek-t** [comment] 2015-12-08 11:06
And it also seems that this test is leaking some GCE resources:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9858/

**Comment by a-robinson** [comment] 2015-12-08 16:35
This was very likely caused by elevated GCE latency, which has a big impact on this test. I wouldn't spend too much time digging into these failures while everything else is also blowing up.

**Comment by wojtek-t** [comment] 2015-12-09 13:47
Yeah - that is reasonable. I'm closing this one - we should open another one if we observe this test failing again.

**Comment by spxtr** [comment] 2016-01-05 19:27
Another release-1.0 fail:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.0/2992/

**Comment by thockin** [comment] 2016-01-20 18:50
This is purely a matter of timeout.  How long of a timeout are we going to allow?  it's 20 minutes already.

We need a way to auto-bucket flakes like this and flag them as "probable backend issue" so they don't bother us.  Closing for now.

**Closed by thockin** 2016-01-20 18:50 UTC
Labels: area/test, kind/flake, priority/P0, team/cluster
