### ISSUE TITLE
Enable `kubectl top pod` support `--watch` option

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#61332] opened 2018-03-19 07:04 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

 /kind feature

**What happened**:
`kubectl top pod` do not support `--watch` now, it is better to support this so that cluster admin can monitor the resource usage change on time.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment] 2018-03-20 01:28
Duplicate of https://github.com/kubernetes/kubernetes/issues/52963

/close

**Closed by liggitt** 2018-03-20 01:28 UTC
Labels: kind/feature, sig/cli
