### ISSUE TITLE
Data race in TestOIDCAuthentication

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19002] opened 2015-12-22 10:30 UTC
The test is failing with the following race:

    WARNING: DATA RACE
    Write by goroutine 95:
      sync.raceWrite()
          /tmp/workdir/go/src/sync/race.go:41 +0x2e
      sync.(*WaitGroup).Wait()
          /tmp/workdir/go/src/sync/waitgroup.go:124 +0xf9
      net/http/httptest.(*Server).Close()
          /tmp/workdir/go/src/net/http/httptest/server.go:168 +0x80
      k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc.TestOIDCAuthentication()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc/oidc_test.go:395 +0x1fc1
      testing.tRunner()
          /tmp/workdir/go/src/testing/testing.go:456 +0xdc

    Previous read by goroutine 142:
      sync.raceRead()
          /tmp/workdir/go/src/sync/race.go:37 +0x2e
      sync.(*WaitGroup).Add()
          /tmp/workdir/go/src/sync/waitgroup.go:66 +0xfa
      net/http/httptest.(*waitGroupHandler).ServeHTTP()
          /tmp/workdir/go/src/net/http/httptest/server.go:198 +0x5c
      net/http.serverHandler.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1862 +0x206
      net/http.(*conn).serve()
          /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

@yifan-gu

**Comment by yifan-gu** [comment] 2015-12-22 19:22
@wojtek-t It looks like the server is stilling handling some request while it's stopped. 
Can you check if 
https://github.com/kubernetes/kubernetes/pull/18917/files fix this?

**Comment by wojtek-t** [comment] 2015-12-23 06:40
I'm OOO now, so I cant verify. @gmarek - maybe you can take a look? We may want to merge that PR.

**Comment by gmarek** [comment] 2015-12-23 08:35
So far I'm unable to reproduce the problem on the head, which suggests it's a rare flake.

**Comment by gmarek** [comment] 2015-12-23 08:37
It failed in the same minute I wrote previous message.

**Comment by yifan-gu** [comment] 2015-12-23 08:51
> It failed in the same minute I wrote previous message.

@gmarek Even if you pulled #18917 ?

**Comment by gmarek** [comment] 2015-12-23 08:52
Yup. It doesn't help.

**Comment by yifan-gu** [comment] 2015-12-24 00:51
Closing, as this should be fixed by #18917 
Feel free to reopen if the failure happens again :)

**Closed by yifan-gu** 2015-12-24 00:51 UTC
Labels: area/test, kind/flake, priority/P1
