### ISSUE TITLE
kubectl scale should use scale subresource

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22308] opened 2016-03-01 20:51 UTC
We reverted it to use Update (PUT) while scale was broken. We should revert back, for ReplicationController, ReplicaSet, and Deployment.

cc @janetkuo @madhusudancs @soltysh @kargakis

**Comment by kargakis** [comment] 2016-03-01 23:11
@bgrant0607 is everything ok now with the scale subresource?

**Comment by bgrant0607** [comment] 2016-03-02 02:57
@kargakis No, not done yet.

**Comment by kargakis** [comment] 2016-03-02 09:46
@bgrant0607 can you link any issues that need to be fixed before we proceed here?

**Comment by bgrant0607** [comment] 2016-04-27 06:48
@kargakis @soltysh I believe this can be fixed now.

**Comment by pwittrock** [comment] 2016-08-17 15:33
Duplicate of #29698

**Closed by pwittrock** 2016-08-17 15:33 UTC
Labels: component/kubectl, help-wanted, kind/cleanup, priority/P2, team/ux
