### ISSUE TITLE
Ubernetes Lite: Dynamic provisioned volumes are not labeled

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22592] opened 2016-03-05 20:45 UTC
It appears that dynamically provisioned volumes bypass the labelling admission controller, and so are not labeled with zone information.

**Comment by saad-ali** [comment] 2016-03-10 00:19
Fix pending: https://github.com/kubernetes/kubernetes/pull/22602

**Comment by saad-ali** [comment] 2016-03-10 00:25
This issue appears to be a duplicate of https://github.com/kubernetes/kubernetes/issues/22532
Do we need both?

**Comment by bgrant0607** [comment] 2016-03-10 02:57
Closing in favor of #22532. Reopen if that's wrong.

**Closed by bgrant0607** 2016-03-10 02:57 UTC
Labels: area/cluster-federation, area/storage, team/cluster

**Comment by justinsb** [comment] 2016-03-10 10:19
I don't know what I was doing opening a duplicate issue here... sorry.

**Comment by justinsb** [comment] 2016-03-10 14:30
Ah - I think this was supposed to be about tags in the EC2 API.  Opened #22792 instead (and PR-ed a fix)
