### ISSUE TITLE
kubernetes-e2e-gce-release failing often with "ReplicationController should serve a basic image on each replica with a private image."

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#14966] opened 2015-10-02 06:43 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1450/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1451/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1454/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1459/

@yujuhong @dchen1107

**Comment by yujuhong** [comment] 2015-10-02 17:39
kubelet failed to pull image:
```
W1001 19:14:53.081581    3608 manager.go:1801] Failed to pull image "gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1" from pod "my-hostname-private-b1541afe-6870-11e5-90ca-42010af01555-kzq2a_e2e-tests-replication-controller-lhxjk" and container "my-hostname-private-b1541afe-6870-11e5-90ca-42010af01555": API error (500): repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```

This was one of the issues we encountered when upgrading docker to 1.8 (#12506), and was fixed by #13747.

The release-1.0 branch should not be using the newer docker version. Unsure why the build would sometimes fail because of this (it doesn't always fail and it's green in the past few builds). @dchen1107 

Relevant bits from the kubelet.log:
```
I1001 19:03:17.370657    2495 manager.go:163] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 7 (wheezy) DockerVersion:1.6.2 CadvisorVersion:0.15.1}
I1001 19:03:57.393404    3373 manager.go:164] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 7 (wheezy) DockerVersion:Unknown CadvisorVersion:0.16.0}
I1001 19:04:01.910926    3608 manager.go:164] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 7 (wheezy) DockerVersion:Unknown CadvisorVersion:0.16.0}
```

**Comment by dchen1107** [comment] 2015-10-02 18:03
cc/ @mattmoor 

Yes, there is an API breakage from docker. Since 1.8 release both docker client & daemon tighten the image name validation to match the repository. #13747 fixed such issue for our 1.1 release.

From failing log I saw, the tests are still running against 1.0 release, and docker version is 1.6.2 which doesn't have such restriction. Looks like the failure from registry itself. Matt, did we recently upgrade our registry, which drops /v1 support and tighten the image name validation? 

The fix should be simple. Just backport #13747 to 1.0 release.

**Comment by yujuhong** [comment] 2015-10-02 18:45
I don't think the error is from the registry itself, since I was able to pull the image with docker 1.7.1. Still not sure why this test is flaky -- does it sometimes use a newer version of docker?

```console
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
$ docker pull gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1
Pulling repository gcr.io/_b_k8s_authenticated_test/serve_hostname
00619279d408: Download complete 
dfc79fbfddea: Download complete 
1624b13c090f: Download complete 
530f80fd689a: Download complete 
0f8672912df0: Download complete 
Status: Image is up to date for gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1
```

**Comment by mattmoor** [comment] 2015-10-02 19:02
Unless you are using Docker 1.8+, this should still work.

**Comment by yujuhong** [comment] 2015-10-02 19:12
@quinton-hoole @ixdy to see if this is related to the cluster/test setup.

**Comment by quinton-hoole** [comment] 2015-10-02 19:34
@yujuhong Nothing obvious that I can see.  There seem to be some other network-related errors in other nearby runs, e.g. 

job/kubernetes-e2e-gce-release/1469/
                       Type: "UnexpectedServerResponse",
                        Message: "Error: 'read tcp 10.240.0.3:10250: connection reset by peer'\nTrying to reach: 'https://10.240.0.3:10250/logs/'",

Perhaps an out of GCE static IP quota issue that someone resolved manually?
Or perhaps a bug in our networking stack.

Either way, as you say, it's running green again.  Lets wait for the next failure and dig deeper on a live cluster.

**Comment by dchen1107** [comment] 2015-10-02 20:07
Weird. I cannot pull the image with docker 1.7.1. But please note that the error is different from what @yujuhong posted at: https://github.com/kubernetes/kubernetes/issues/14966#issuecomment-145094787

```
$ docker pull gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1
Pulling repository gcr.io/_b_k8s_authenticated_test/serve_hostname
Error: image _b_k8s_authenticated_test/serve_hostname:1.1 not found
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by dchen1107** [comment] 2015-10-02 20:11
@quinton-hoole The reason I ruled out the network issue initially is that error log of API error (500) from kubelet? Do we have startup log on the node?

**Comment by quinton-hoole** [comment] 2015-10-02 20:20
@dchen1107 yes, the cluster logs for every failed test run are available via the "Google Cloud Storage Upload Report" link in Jenkins.

**Comment by dchen1107** [comment] 2015-10-02 20:38
@quinton-hoole I know that link. But unfortunately it doesn't include docker log and startup logs :-(

**Comment by yujuhong** [comment] 2015-10-02 20:44
> Weird. I cannot pull the image with docker 1.7.1. But please note that the error is different from what @yujuhong posted at: #14966 (comment)

@dchen1107, I think you ran this on your workstation, which didn't have the right credentials. Run the same command in an e2e cluster with older docker, you should be able to pull.


> @yujuhong above kubelet log of
> from one of test machines of kubernetes-e2e-gce-release?

Yes, I grabbed that from one of the kubelet.log files in a failed build.

**Comment by quinton-hoole** [comment] 2015-10-02 21:04
@dchen1107 then we should add docker logs and startup logs to those that are downloaded, if they're required for debugging.

What are their file names?

The code that needs to change is here:

https://github.com/kubernetes/kubernetes/blob/86fb79da056c8c4225723f17df54fd46ff89ea39/test/e2e/core.go#L53

Please open an issue to have the missing logs added.

**Comment by dchen1107** [comment] 2015-10-02 22:34
Ok, since Oct 2, 2015 8:46 AM, all builds are green. I checked some of machines, and docker version is the one for 1.0.X release. I am wondering if there is a configuration mess up yesterday? 

Anyway, I am closely monitoring this release build, and will update more.

**Comment by dchen1107** [comment] 2015-10-02 22:42
@quinton-hoole I guess downloading both docker and startup logs is a little bit overkill here. In most cases, we don't need that. I plan to dump those systemInfo to kubelet log whenever kubelet is restart.

**Comment by yujuhong** [comment] 2015-10-02 22:47
Hmm...we already do that, but sometimes it logs `DockerVersion:Unknown`
@dchen1107, shouldn't the "unknown" version problem be solved by #13318 (cherry-picked to release 1.0) already?

**Comment by dchen1107** [comment] 2015-10-02 23:02
Good finding! Yes, this is the first issue I asked @pwittrock to fix and I didn't realize it was cherrypicked to 1.0 already. In this case, I really think the test configuration was messed up since I haven't seen unknown docker version for a long time.

**Comment by davidopp** [comment] 2015-10-03 20:29
More failures:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1483/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release/1488/

**Comment by quinton-hoole** [comment] 2015-10-03 21:45
Same problem.  Error pulling image:

```
01:23:45 INFO: event for my-hostname-private-592e3dbe-69a7-11e5-ada5-42010af01555-4ldww: {kubelet e2e-gce-minion-lyff} Pulling: Pulling image "gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1"
01:23:45 INFO: event for my-hostname-private-592e3dbe-69a7-11e5-ada5-42010af01555-4ldww: {kubelet e2e-gce-minion-lyff} Failed: Failed to pull image "gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1": API error (500): repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
01:23:45 
```

**Comment by mattmoor** [comment] 2015-10-05 22:30
Can you just CP the `b.gcr.io` change?  You should only see this with Docker 1.8 (or above), if not please ping me on hangouts and I'm happy to debug.

**Comment by dchen1107** [comment] 2015-10-14 22:24
Now we split kubernetes-e2e-gce-release project into two: one for 1.0, and another one for 1.1. I checked builds last couple days for both projects, and none of them failed due to this particular issue. Like I mentioned in https://github.com/kubernetes/kubernetes/issues/14966#issuecomment-145177776, I believe the failure is caused by the test configuration back then, and such breakage is fixed after splitting. I am closing the issue now, please re-open it if failure happens again.

**Closed by dchen1107** 2015-10-14 22:24 UTC
Labels: area/test, kind/flake, priority/P1, team/node, team/test-infra
