### ISSUE TITLE
Deprecate/replace apt.kubernetes.io and yum.k8s.io (or) move them to community owned repository

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100348] opened 2021-03-17 20:06 UTC
- both `apt.kubernetes.io` and `yum.k8s.io` are redirects to google owned/operated package repository:
https://cs.k8s.io/?q=(yum%7Capt).kubernetes.io&i=nope&files=&excludeFiles=&repos=kubernetes/k8s.io
- deb/rpm packages are signed by folks in GOOG and uploaded to the repository (thanks @BenTheElder and others who take care of this!!!)

Choices are:
- Get a community owned key and setup our own repository
- Deprecate these repos in favor of something else

/sig release

**Comment by justaugustus** [comment] 2021-03-17 20:14
This is a duplicate of https://github.com/kubernetes/release/issues/281, which is part of the over-arching Artifact Management epic here: https://github.com/kubernetes/sig-release/issues/1372.

Further, there is a project board capturing some of these asks here: https://github.com/orgs/kubernetes/projects/48
Work will begin in v1.22.

/close

**Closed** 2021-03-17 20:14 UTC
Labels: kind/feature, needs-triage, sig/release

**Comment by dims** [comment] 2021-03-17 20:19
@justaugustus thanks! i wanted to be sure that we consider this and work through stuff way before we think of brand new use cases / scenarios.

**Comment by justaugustus** [comment] 2021-03-17 20:20
@dims -- Thanks. Please comment on the original issue! :)
