### ISSUE TITLE
pkg/kubelet/dockershim/network/cni/cni_test.go heavily flakes

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#82280] opened 2019-09-03 15:47 UTC
The upper test heavily flakes in master:

```
--- FAIL: TestCNIPlugin (0.12s)\n"}
    cni_test.go:279: Mismatch in expected output for setup hook. Expected 'ADD /proc/12345/ns/net podNamespace podName test_infra_container', got 'VERSION dummy   '\n"}
    cni_test.go:341: PASS:\tAddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)\n"}
    cni_test.go:341: PASS:\tDelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)\n"}
```

**Comment by squeed** [comment] 2019-09-03 15:51
Hey @mars1024 I think this might have something to do with your changes. Something is definitely a bit off. It probably is a faulty test...

```
$ go test --count=5 ./pkg/kubelet/dockershim/network/cni/...
--- FAIL: TestCNIPlugin (0.08s)
    cni_test.go:293: failed to parse reported cni input config /tmp/cni-test258298627/output/test_vendor59.in: (<nil> invalid character 'w' after top-level value)
    cni_test.go:300: mismatch in expected port mappings. expected [map[containerPort:80 hostIP:0.0.0.0 hostPort:8008 protocol:udp]] got []
    cni_test.go:307: mismatch in expected bandwidth. expected map[egressBurst:2.147483647e+09 egressRate:1e+06 ingressBurst:2.147483647e+09 ingressRate:1e+06] got map[]
    cni_test.go:317: mismatch in expected ipRange. expected [[map[subnet:10.0.2.0/24]]] got []
    cni_test.go:341: PASS:      AddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
    cni_test.go:341: PASS:      DelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
--- FAIL: TestCNIPlugin (0.08s)
    cni_test.go:279: Mismatch in expected output for setup hook. Expected 'ADD /proc/12345/ns/net podNamespace podName test_infra_container', got 'VERSION dummy   '
    cni_test.go:341: PASS:      AddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
    cni_test.go:341: PASS:      DelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
--- FAIL: TestCNIPlugin (0.08s)
    cni_test.go:300: mismatch in expected port mappings. expected [map[containerPort:80 hostIP:0.0.0.0 hostPort:8008 protocol:udp]] got []
    cni_test.go:307: mismatch in expected bandwidth. expected map[egressBurst:2.147483647e+09 egressRate:1e+06 ingressBurst:2.147483647e+09 ingressRate:1e+06] got map[]
    cni_test.go:317: mismatch in expected ipRange. expected [[map[subnet:10.0.2.0/24]]] got []
    cni_test.go:341: PASS:      AddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
    cni_test.go:341: PASS:      DelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
--- FAIL: TestCNIPlugin (0.08s)
    cni_test.go:279: Mismatch in expected output for setup hook. Expected 'ADD /proc/12345/ns/net podNamespace podName test_infra_container', got 'VERSION dummy   '
    cni_test.go:293: failed to parse reported cni input config /tmp/cni-test601262504/output/test_vendor300.in: (<nil> invalid character 'w' after top-level value)
    cni_test.go:300: mismatch in expected port mappings. expected [map[containerPort:80 hostIP:0.0.0.0 hostPort:8008 protocol:udp]] got []
    cni_test.go:307: mismatch in expected bandwidth. expected map[egressBurst:2.147483647e+09 egressRate:1e+06 ingressBurst:2.147483647e+09 ingressRate:1e+06] got map[]
    cni_test.go:317: mismatch in expected ipRange. expected [[map[subnet:10.0.2.0/24]]] got []
    cni_test.go:341: PASS:      AddNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
    cni_test.go:341: PASS:      DelNetworkList(*context.emptyCtx,*libcni.NetworkConfigList,mock.AnythingOfTypeArgument)
FAIL
FAIL    k8s.io/kubernetes/pkg/kubelet/dockershim/network/cni    0.417s
?       k8s.io/kubernetes/pkg/kubelet/dockershim/network/cni/testing    [no test files]
```

**Comment by liggitt** [comment] 2019-09-03 16:19
duplicate of https://github.com/kubernetes/kubernetes/issues/82150?

**Comment by mars1024** [comment] 2019-09-04 04:07
@squeed Looks like an occasional failure, and I don't think this is caused by my code change because I run tests for a few times, and sometime it is passed....
Still I can help to locate the root cause.

**Comment by mars1024** [comment] 2019-09-04 06:33
I revert my code change, test still fails from time to time...

**Comment by mars1024** [comment] 2019-09-04 13:43
I think i've found out the root cause, I'll pull a request soon, @sttts @squeed . cc @liggitt

**Closed** 2019-09-05 16:03 UTC
Labels: kind/failing-test, kind/flake, priority/important-soon, sig/network
