### ISSUE TITLE
the connection is unavailable

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#77255] opened 2019-04-30 09:34 UTC
/kind bug

/sig node
@Dawn Chen

**What happened**:
Pod creation failed in my k8s cluster with error message:grpc the connection is unavailable

**Anything else we need to know?**:
The location found that there was no connection to the docker, and my solution was to restart the docker,I didn't find a better way. Is there a better way to solve this problem?
command:
systemctl restart docker 

**Environment**:
- Kubernetes version (use `kubectl version`):1.10.4
- OS (e.g: `cat /etc/os-release`):ubuntu 16.04
- Kernel (e.g. `uname -a`):4.4.0
- Network plugin and version (if this is a network-related bug):calico

**Comment by shigy123456** [comment] 2019-04-30 09:35
docker version :17.03.2-ce

**Comment by mattjmcnaughton** [comment] 2019-04-30 14:13
Hi @shigy123456 - I'm seeing that you're using Kubernetes 1.10.4, which is not currently supported. Could you please upgrade to a currently supported k8s version (more info [here](https://kubernetes.io/docs/setup/version-skew-policy/)). tl:dr; 1.12.x, 1.13.x, and 1.14.x are the currently supported versions.

**Comment by shigy123456** [comment] 2019-05-01 00:55
hi@mattjmcnaughton,
Thank you for answering my question. My kubernetes version is not really up to date.
My question is whether the problem is caused by a low version of docker or a low version of kubernetes.
When I restart docker, I solve this problem, and judging from this solution, is it possible for me to upgrade docker to solve this problem, for example, I upgrade docker from 17.03 to 18.06?
If upgrading docker will solve the problem, can I use kubernetes1.10.4 and docker18.06?

**Comment by mattjmcnaughton** [comment] 2019-05-01 14:05
On Tue, Apr 30, 2019 at 05:56:13PM -0700, TimYin wrote:
> hi@mattjmcnaughton,
> Thank you for answering my question. My kubernetes version is not really up to date.
> My question is whether the problem is caused by a low version of docker or a low version of kubernetes.
> When I restart docker, I solve this problem, and judging from this solution, is it possible for me to upgrade docker to solve this problem, for example, I upgrade docker from 17.03 to 18.06?
> If upgrading docker will solve the problem, can I use kubernetes1.10.4 and docker18.06?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/77255#issuecomment-488165945

No problem :)

To be honest, I think your best chance for getting helpful information to answer
this question is to ask it on either [Stack
Overflow](https://stackoverflow.com/search?q=kubernetes) or the [k8s community
forum](https://discuss.kubernetes.io/). Would you mind closing this issue and
asking in one of those locations?

Thanks so much :)

**Closed** 2019-09-28 16:25 UTC
Labels: kind/bug, lifecycle/rotten, sig/node

**Comment by timyinshi** [comment] 2019-09-30 09:50
@mattjmcnaughton ok,thanks.
