### ISSUE TITLE
GCI doesn't work in europe-west1-c

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#26350] opened 2016-05-26 09:03 UTC
After upgrading image on master machine to GCI, I cannot start a cluster in europe-west1-c zone. Everything works fine in us-central, but in europe it doesn't.

Basically what I'm seeing it:
```
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

...........................................Cluster failed to initialize within 300 seconds.
```

I logged into a machine, and it actually didn't do anything useful (there are no running containers, not running k8s components, no services - nothing.

This is an extremely serious issue.

@andyzheng0831 @wonderfly @kubernetes/sig-node @kubernetes/goog-cluster

**Comment by andyzheng0831** [comment] 2016-05-26 09:06
Please try to assign it to someone else. I am OOO and will not be able to
take a look before next Tue.

**Comment by wonderfly** [comment] 2016-05-26 13:03
@adityakali Can you take a look? This might be related to the regional fallback thing that @zmerlynn and @andyzheng0831 added sometime back.

cc/ @kubernetes/goog-image

**Comment by wonderfly** [comment] 2016-05-26 15:22
I was able to reproduce and found some leads - downloading of kubernetes-manifests.tar.gz failed. Looking...

**Comment by wonderfly** [comment] 2016-05-26 16:06
I have a theory: https://github.com/kubernetes/kubernetes/pull/25425/files#diff-6a44976362555568e0243a480da2e86bR168 - all .yaml files are placed under `${dst_dir}/kubernetes`, so that `find` command will always fail, because of that `-maxdepth 1`. This code path was never triggered when we started clusters in US because of the `if [[ "${kube_addon_registry}" != "gcr.io/google_containers" ]];` check.

I made a quick fix and am testing it. Will update soon.

**Comment by wonderfly** [comment] 2016-05-26 17:15
Confirmed. See #26363

**Closed** 2016-05-27 16:58 UTC
Labels: area/cluster-lifecycle, area/os/gci, priority/P0, team/node
