### ISSUE TITLE
CSR ignores requested extension "Subject Alternative Name"

### ISSUE THREAD

**Issue by juniorz** [kubernetes/kubernetes#77092] opened 2019-04-25 18:08 UTC
**What happened**:

The certificate issued does not have `X509v3 Subject Alternative Name` extension.

**What you expected to happen**:

`X509v3 Subject Alternative Name` should be in issued cert, as in k8s v1.11.8.

**How to reproduce it (as minimally and precisely as possible)**:

```
cat <<EOF | tee server.csr
-----BEGIN CERTIFICATE REQUEST-----
MIIBfTCCASMCAQAwFTETMBEGA1UEAxMKbXktc2VydmljZTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABG/9DlfTJQbvcch/epkyGGo7VkhjmbXiXFxPBUfxF+GvcGgz
4cp1TYId4gUletyjpUEnA9xtOedOTdxdKRmkVjyggaswgagGCSqGSIb3DQEJDjGB
mjCBlzCBlAYDVR0RBIGMMIGJggpteS1zZXJ2aWNlghJteS1zZXJ2aWNlLmRlZmF1
bHSCFm15LXNlcnZpY2UuZGVmYXVsdC5zdmOCHm15LXNlcnZpY2UuZGVmYXVsdC5z
dmMuY2x1c3RlcoIkbXktc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
gglsb2NhbGhvc3QwCgYIKoZIzj0EAwIDSAAwRQIhAJNEMxPMSoJw4vBrL9XeGBE6
aVjQysG1Jtq49IUHiMW+AiA7hmpMRICQS3H9fmvluGMPTNO7PQj6iGwaR/noEQo1
+w==
-----END CERTIFICATE REQUEST-----
EOF

cat <<EOF | tee /dev/tty | kubectl apply -f -
---
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-service
  namespace: default
spec:
  groups:
  - system:authenticated
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

**Anything else we need to know?**:

The certificate signing request has the extension:

```
openssl req -text -noout -in server.csr

Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=my-service
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:6f:fd:0e:57:d3:25:06:ef:71:c8:7f:7a:99:32:
                    18:6a:3b:56:48:63:99:b5:e2:5c:5c:4f:05:47:f1:
                    17:e1:af:70:68:33:e1:ca:75:4d:82:1d:e2:05:25:
                    7a:dc:a3:a5:41:27:03:dc:6d:39:e7:4e:4d:dc:5d:
                    29:19:a4:56:3c
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:my-service, DNS:my-service.default, DNS:my-service.default.svc, DNS:my-service.default.svc.cluster, DNS:my-service.default.svc.cluster.local, DNS:localhost
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:93:44:33:13:cc:4a:82:70:e2:f0:6b:2f:d5:
         de:18:11:3a:69:58:d0:ca:c1:b5:26:da:b8:f4:85:07:88:c5:
         be:02:20:3b:86:6a:4c:44:80:90:4b:71:fd:7e:6b:e5:b8:63:
         0f:4c:d3:bb:3d:08:fa:88:6c:1a:47:f9:e8:11:0a:35:fb
```

and 

```

kubectl certificate approve my-service

kubectl get csr my-service -o jsonpath='{.status.certificate}' | base64 --decode | openssl x509 -text -noout -in /dev/stdin

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            e9:78:cd:bb:3b:80:fd:b1:7f:d9:0c:42:0c:38:38:9c:60:db:3c
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kubernetes
        Validity
            Not Before: Apr 25 17:22:00 2019 GMT
            Not After : Apr 24 17:22:00 2020 GMT
        Subject: CN=my-service
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:db:cb:a2:85:81:79:bf:43:d6:30:45:b5:07:3a:
                    77:e6:db:f1:db:77:f9:e4:0e:79:e3:5b:7e:6c:b9:
                    95:a1:ed:cd:19:c7:75:03:c2:10:56:7e:b5:57:1c:
                    85:b6:a5:f9:b3:2f:8c:87:4f:35:b3:a7:bd:23:cf:
                    e2:67:6b:d1:d0
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                F3:37:4E:34:15:5A:9E:11:95:E3:2F:49:8C:B6:65:3C:05:C7:8B:8D
    Signature Algorithm: sha256WithRSAEncryption
         a7:e5:5c:90:6a:03:d9:45:7b:6d:1d:ff:71:3b:fd:ee:7b:d0:
         5e:45:66:81:ff:64:23:87:8d:44:4f:78:dc:57:af:db:6b:28:
         fd:9f:d8:7c:a0:b4:30:a3:78:59:19:d1:e6:41:49:f1:20:29:
         08:06:c0:d2:4c:f6:05:da:9d:1c:04:d0:00:b9:c0:e4:65:31:
         17:62:2f:92:49:1c:76:3f:64:09:f4:dc:bc:6c:20:05:bb:ba:
         6e:96:16:ab:0f:89:3f:b9:56:91:71:38:f1:8b:05:52:d0:22:
         a4:a1:dd:c0:03:55:08:64:37:14:58:24:d2:b7:df:4e:e0:52:
         76:01:58:a3:ff:21:2a:e6:1c:a4:36:8e:3a:87:37:b9:69:76:
         a3:38:25:07:a4:47:61:3b:7d:98:31:c2:d8:3d:a8:00:88:da:
         97:ff:16:21:5b:61:a8:b0:c7:e9:28:c7:65:8b:61:ff:b4:77:
         04:a0:65:f0:c8:46:23:cf:84:dc:6a:52:45:7b:33:7d:a7:07:
         1c:02:6d:5c:ee:fc:74:ff:ee:20:d8:60:b5:5c:af:35:61:6c:
         35:3d:05:cc:84:e9:5c:9b:25:ae:f7:8d:02:ea:fe:a4:05:f5:
         5f:b2:e7:cb:8a:33:bf:ae:c8:ba:1e:58:fa:72:e6:24:f3:86:
         8c:0d:e0:ad
```

but the same Certificate Signing Request in k8s v1.11.8 has the expected `X509v3 Subject Alternative Name ` extension:

```
kubectl get csr my-service -o jsonpath='{.status.certificate}' | base64 --decode | openssl x509 -text -noout -in /dev/stdin

certificatesigningrequest.certificates.k8s.io/my-service approved
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            46:0c:37:a7:a3:1f:e3:16:eb:e0:fb:0e:a9:41:45:57:0c:d3:ce:42
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kubernetes
        Validity
            Not Before: Apr 25 17:52:00 2019 GMT
            Not After : Apr 24 17:52:00 2020 GMT
        Subject: CN=my-service
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:6f:fd:0e:57:d3:25:06:ef:71:c8:7f:7a:99:32:
                    18:6a:3b:56:48:63:99:b5:e2:5c:5c:4f:05:47:f1:
                    17:e1:af:70:68:33:e1:ca:75:4d:82:1d:e2:05:25:
                    7a:dc:a3:a5:41:27:03:dc:6d:39:e7:4e:4d:dc:5d:
                    29:19:a4:56:3c
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                E3:AE:4E:25:7D:F2:1E:D7:2E:D5:07:37:48:70:2F:9D:B1:36:5A:E7
            X509v3 Subject Alternative Name:
                DNS:my-service, DNS:my-service.default, DNS:my-service.default.svc, DNS:my-service.default.svc.cluster, DNS:my-service.default.svc.cluster.local, DNS:localhost
    Signature Algorithm: sha256WithRSAEncryption
         79:3a:6b:69:3b:11:37:e2:97:0c:2d:77:41:df:93:17:a5:07:
         ae:89:a0:5f:a8:8d:81:ac:fb:ca:80:fd:12:b7:93:e5:cc:ca:
         4c:ea:1b:86:be:28:0a:d1:67:5e:c9:ba:1f:86:7d:ee:d1:db:
         e3:fb:3d:dd:47:e9:b3:e0:ed:5c:7f:2f:85:05:68:e7:6f:63:
         a5:a0:68:c6:33:66:35:f8:0e:34:e5:ec:03:2a:0a:4d:d1:1e:
         b7:79:40:3d:40:77:93:aa:a6:2a:c7:1c:70:f0:45:8f:10:61:
         4c:83:ce:cd:1d:2f:5b:bd:7d:82:2e:2a:98:dc:f5:9d:f3:f5:
         ac:12:46:00:e5:34:c0:c0:8e:2e:f7:53:df:6d:3a:49:63:d0:
         37:2c:45:ce:74:32:3c:ac:1a:0a:da:e9:e5:ee:d2:9d:b1:19:
         3d:73:b0:d3:d2:a2:13:32:93:cb:34:df:8e:4e:f3:2c:cc:4f:
         78:fa:24:11:1f:12:7b:f3:76:56:74:7a:13:a3:2d:11:95:3f:
         c0:76:e9:f0:be:7a:cf:1e:cf:42:4b:b7:54:c5:80:7c:f2:d9:
         bf:59:2a:7f:7e:47:0a:2f:a3:84:2f:59:c0:63:ff:1a:6d:c0:
         8b:fa:61:c5:69:fe:24:40:03:36:45:df:ef:23:ed:09:ef:1f:
         00:70:47:eb
```

(full `kubectl version` for completeness: `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`)

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2019-04-26 06:01
I'm not able to reproduce this on master with `hack/local-up-cluster.sh`. Submitting your example, I see the signed certificate having the requested subject alt names.

It appears you're running in EKS.

@micahhausler, do you know if EKS runs a different CSR signer? If so, do you know if it's behavior changed to not honor SANs in the originating CSR?

**Comment by eviln1** [comment] 2019-04-26 15:52
Hello,
Able to reproduce in EKS  1.11 (eks.2) and EKS 1.12 (eks.1).

**Comment by micahhausler** [comment] 2019-04-26 18:43
Yea, I can confirm this is not an upstream issue and is EKS specific. You can follow along here: https://github.com/awslabs/amazon-eks-ami/issues/244.

**Comment by liggitt** [comment] 2019-04-26 19:17
thanks, closing here, can track in the eks issue

/close

**Closed by liggitt** 2019-04-26 19:17 UTC
Labels: area/platform/eks, kind/bug, sig/auth, triage/not-reproducible
