### ISSUE TITLE
Turn off client throttling in integration tests

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#22000] opened 2016-02-25 18:29 UTC
I see in logs things like this:

```
W0224 16:03:12.355951   19903 request.go:627] Throttling request took 1.19752203s, request: http://127.0.0.1:38001/api/v1/namespaces/default/services/atomicservice
```

There's no reason to throttle in integration tests. In fact it'd probably be a more effective test if it didn't throttle. And faster, too.

Thanks @wojtek-t for adding the log message that lets us notice this.

**Comment by wojtek-t** [comment] 2016-02-25 18:41
I think that we shouldn't switch of throttling.
What we should do is to increase the QPS limit - the default QPS limit in client is 5 (10 in burst). This is very low, since we are basically using just a single client in integration test IIUC.

What we should do is to increase it to 10 (20 burst) or even 20 (30 burst) [20/30 is what all k8s components have].
BTW - we should probably increase it also in e2e tests, because there are also a bunch of those logs there.

@lavalamp - WDYT?

**Comment by wojtek-t** [comment] 2016-02-25 18:41
Thanks to this change, we will be able to not throttle now, and in case of significant regression we will be able to see that in logs (that we are generating many more regressions).

**Comment by lavalamp** [comment] 2016-02-25 18:57
Sure, making the number a lot bigger works for me. I think it should be big enough that typically no throttling happens in the tests. If that means 50 or 100 qps, then so be it :)

**Comment by wojtek-t** [comment] 2016-02-25 18:59
I'm happy to change it tomorrow.

**Comment by derekwaynecarr** [comment] 2016-02-25 20:06
:+1:

**Comment by wojtek-t** [comment] 2016-02-26 10:01
I will wait for #21882 to be merged first and will send a PR out as soon as this is merged.

**Closed** 2016-03-06 05:27 UTC
Labels: priority/P1, team/test-infra
