### ISSUE TITLE
gci-gce-serial is failing in master

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47600] opened 2017-06-15 17:01 UTC
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:216
Jun 15 07:53:03.716: Error waiting for all pods to be running and ready: 4 / 26 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                    NODE                            PHASE   GRACE CONDITIONS
fluentd-gcp-v2.0-7s2bv bootstrap-e2e-minion-group-lc41 Running       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:47 -0700 PDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:47:50 -0700 PDT ContainersNotReady containers with unready status: [fluentd-gcp]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:56 -0700 PDT  }]
fluentd-gcp-v2.0-9gm87 bootstrap-e2e-minion-group-kb2k Running       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:12 -0700 PDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:47:16 -0700 PDT ContainersNotReady containers with unready status: [fluentd-gcp]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:22 -0700 PDT  }]
fluentd-gcp-v2.0-gwmv3 bootstrap-e2e-master            Running       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:10 -0700 PDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:47:36 -0700 PDT ContainersNotReady containers with unready status: [fluentd-gcp]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:32 -0700 PDT  }]
fluentd-gcp-v2.0-l4bn0 bootstrap-e2e-minion-group-nlwz Running       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:12 -0700 PDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:47:46 -0700 PDT ContainersNotReady containers with unready status: [fluentd-gcp]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-15 07:36:22 -0700 PDT  }]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:167
```

@kubernetes/kubernetes-release-managers @dchen1107

**Comment by yujuhong** [comment] 2017-06-15 17:13
```
I0615 08:48:40.580] ENDLOG for container kube-system:fluentd-gcp-v2.0-8skw9:prometheus-to-sd-exporter
I0615 08:48:40.787] Jun 15 08:48:40.787: INFO: Logs of kube-system/fluentd-gcp-v2.0-mqrs8:fluentd-gcp on node bootstrap-e2e-minion-group-vp5d
I0615 08:48:40.787] Jun 15 08:48:40.787: INFO:  : STARTLOG
I0615 08:48:40.788] /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsystemd.so.0': libcap.so.2: cannot open shared object file: No such file or directory. (LoadError)
I0615 08:48:40.788] Could not open library 'libsystemd.so': libcap.so.2: cannot open shared object file: No such file or directory.
I0615 08:48:40.788] Could not open library 'libsystemd-id128.so.0': libsystemd-id128.so.0: cannot open shared object file: No such file or directory.
I0615 08:48:40.788] Could not open library 'libsystemd-id128.so': libsystemd-id128.so: cannot open shared object file: No such file or directory
I0615 08:48:40.788] 	from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
I0615 08:48:40.788] 	from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
I0615 08:48:40.789] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:48:in `<module:Native>'
I0615 08:48:40.789] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:45:in `<module:Id128>'
I0615 08:48:40.789] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:6:in `<module:Systemd>'
I0615 08:48:40.789] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:3:in `<top (required)>'
I0615 08:48:40.789] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.789] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.789] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal/native.rb:1:in `<top (required)>'
I0615 08:48:40.790] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.790] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.790] 	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal.rb:2:in `<top (required)>'
I0615 08:48:40.790] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
I0615 08:48:40.790] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
I0615 08:48:40.790] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
I0615 08:48:40.790] 	from /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:1:in `<top (required)>'
I0615 08:48:40.791] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.791] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I0615 08:48:40.791] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
I0615 08:48:40.791] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/plugin.rb:170:in `each'
I0615 08:48:40.791] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/plugin.rb:170:in `try_load_plugin'
I0615 08:48:40.791] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/plugin.rb:130:in `new_impl'
I0615 08:48:40.791] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/plugin.rb:55:in `new_input'
I0615 08:48:40.792] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/root_agent.rb:154:in `add_source'
I0615 08:48:40.792] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/root_agent.rb:95:in `block in configure'
I0615 08:48:40.792] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/root_agent.rb:92:in `each'
I0615 08:48:40.792] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/root_agent.rb:92:in `configure'
I0615 08:48:40.792] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/engine.rb:129:in `configure'
I0615 08:48:40.793] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/engine.rb:103:in `run_configure'
I0615 08:48:40.793] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:489:in `run_configure'
I0615 08:48:40.793] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:174:in `block in start'
I0615 08:48:40.793] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:366:in `call'
I0615 08:48:40.793] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:366:in `main_process'
I0615 08:48:40.794] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:170:in `start'
I0615 08:48:40.794] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
I0615 08:48:40.794] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
I0615 08:48:40.794] 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
I0615 08:48:40.794] 	from /var/lib/gems/2.1.0/gems/fluentd-0.12.36/bin/fluentd:5:in `<top (required)>'
I0615 08:48:40.795] 	from /usr/local/bin/fluentd:23:in `load'
I0615 08:48:40.795] 	from /usr/local/bin/fluentd:23:in `<main>'
I0615 08:48:40.795] 
I0615 08:48:40.795] ENDLOG for container kube-system:fluentd-gcp-v2.0-mqrs8:fluentd-gcp
```
Most likely caused by the fluentd update #47545
/cc @ixdy

**Comment by mindprince** [comment] 2017-06-15 17:53
The gce-gpu tests are failing for the same reason.

**Comment by csbell** [comment] 2017-06-15 18:01
Ditto for pull-federation and federation-ci. pull-federation will need a cluster rebuild once the fix is incorporated upstream.
/cc csbell

**Comment by ixdy** [comment] 2017-06-15 18:45
well that's exciting. cc @crassirostris

**Comment by ixdy** [comment] 2017-06-15 18:48
#47610 to revert fluentd to 2.0.5.

**Comment by ixdy** [comment] 2017-06-15 18:58
I don't understand what's special about these clusters, though. The PR passed presubmit tests a number of times.

**Closed** 2017-06-15 20:22 UTC
Labels: approved-for-milestone, priority/critical-urgent, sig/auth, sig/instrumentation

**Comment by yujuhong** [comment] 2017-06-15 20:27
@ixdy none of the presubmit tests run COS images. I think that's the problem.

From the error message, it seems like copying libsystemd* is not enough, and more libraries need to be copied (e.g., libcap*). Will need to build a new fluentd image to fix this.

**Comment by ixdy** [comment] 2017-06-15 20:40
@yujuhong yeah, I think you're right. I started a cluster myself and the pod is failing on the master (COS) but not on the nodes (CVM). curious that this broke between fluentd 2.0.5 and 2.0.6, which has no code changes and only updates the base image... I guess something materially changed in the base image.
