### ISSUE TITLE
kubelet 1.18.4 cannot be installled on centos7

### ISSUE THREAD

**Issue by kubealex** [kubernetes/kubernetes#92240] opened 2020-06-17 22:25 UTC
**What happened**:

Tried to install k8s following documentation on Centos7
kubelet-1.18.4-0.x86_64 conflicts with containernetworking-plugins-0.8.6-1.el7.x86_64

**What you expected to happen**:
k8s installs

**How to reproduce it (as minimally and precisely as possible)**:
Add k8s repo
try to install packages
watch the conflict

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: bare metal/vm
- OS (e.g: `cat /etc/os-release`): CentOS7
- Kernel (e.g. `uname -a`): Linux k8s-master-0.k8s.lab 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: yum

**Comment by neolit123** [comment] 2020-06-18 00:47
/sig release
/triage support

unless i'm mistaken the latest PATCH version of 1.18.0 would include the CNI plugins inside the kubelet package and you don't have to install kubernetes-cni or containernetworking-plugins anymore.

for more questions try asking in #sig-release on k8s slack.

**Comment by kubealex** [comment] 2020-06-18 07:01
I'm not installing any other package than kubelet/kubeadm/kubectl, following the documentation.

I am just adding this repo:
https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearc

and running yum install kubelet kubeadm kubectl

**Comment by justaugustus** [comment] 2020-06-18 11:33
Closed as duplicate of https://github.com/kubernetes/kubernetes/issues/92242. Please follow that issue for updates.
/close

**Closed** 2020-06-18 11:33 UTC
Labels: kind/bug, needs-sig, triage/support
