### ISSUE TITLE
Coreos demo config doesn't work -- nodes polling /registry/nodes/localhost/boundpods

### ISSUE THREAD

**Issue by Symmetric** [kubernetes/kubernetes#3779] opened 2015-01-24 00:13 UTC
I'm trying to run the [CoreOS Multinode demo](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md), running against the latest master (4c413e7). I'm slightly off-piste, in that I'm running the cloud-configs on CoreOS VMs hosted on my ESX infrastructure, rather than cloud-hosted. However I think the problem I'm seeing is just an issue with the cloud-config files.

The master knows of the following nodes:

```
kubecfg list nodes
Minion identifier   Labels
----------          ----------
172.25.20.16        
172.25.20.129       
```

This is correct. I ran a container thusly:

```
kubecfg -p 8080:80 run busybox 1 myBusybox
```

The master seems to be in good shape now, with a replicationController in place, and the pod looks good:

```
92a7aaf8-a34d-11e4-acf0-005056980d4e   busybox             172.25.20.16/       name=myBusybox      Unknown
```
The node isn't picking up the controller though, since it's polling the wrong etcd directory:

```
Jan 23 22:36:20 localhost kubelet[672]: I0123 22:36:20.271540     672 logs.go:39] etcd DEBUG: get /registry/nodes/localhost/boundpods [http://172.25.20.17:4001]
Jan 23 22:36:20 localhost kubelet[672]: I0123 22:36:20.271567     672 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/localhost/boundpods?consistent=true&recursive=false&sorted=false
Jan 23 22:36:20 localhost kubelet[672]: I0123 22:36:20.271576     672 logs.go:39] etcd DEBUG: send.request.to http://172.25.20.17:4001/v2/keys/registry/nodes/localhost/boundpods?consistent=true&recursive=false&sorted=false | method GET
Jan 23 22:36:20 localhost kubelet[672]: I0123 22:36:20.271612     672 event.go:92] Event(api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"localhost", UID:"localhost", APIVersion:"", ResourceVersion:"", FieldPath:""}): status: '', reason: 'starting' Start
```

Note the GET for /registry/nodes/localhost. This doesn't match the value that the master has stored; it should be using the IP:

```
curl -L http://172.25.20.17:4001/v2/keys/registry/nodes/
{"action":"get","node":{"key":"/registry/nodes","dir":true,"nodes":[{"key":"/registry/nodes/172.25.20.129","dir":true,"modifiedIndex":46783,"createdIndex":46783},{"key":"/registry/nodes/172.25.20.16","dir":true,"modifiedIndex":48851,"createdIndex":48851}],"modifiedIndex":46783,"createdIndex":46783}}
```

Is the Kubelet misbehaving, by using the hostname? Or is a hostname mandatory to distinguish nodes, and kube-register isn't loading the nodes correctly on the master?

**Comment by Symmetric** [comment] 2015-01-24 00:24
I suspect this is down to the following config in kube-kubelet-service:

```
        ExecStart=/opt/bin/kubelet \                                                                                                                                                                                                                                   
        --address=0.0.0.0 \                                                                                                                                                                                                                                            
        --port=10250 \                                                                                                                                                                                                                                                 
        --hostname_override=$private_ipv4 \                                                                                                                                                                                                                            
        --etcd_servers=http://<master-private-ip>:4001 \                                                                                                                                                                                                               
        --logtostderr=true                                  
```

$private_ipv4 doesn't work under VMware...

**Comment by dchen1107** [comment] 2015-01-24 00:44
cc/ @kelseyhightower

**Comment by erictune** [comment] 2015-01-26 22:49
@Symmetric did you find a workaround for the $private_ipv4 issue?

**Comment by Symmetric** [comment] 2015-01-27 18:21
@erictune, I've successfully worked around this issue by manually specifying the IP in the kubelet-service, so that's definitely the source of the problem.

It looks like there's not a well documented way to populate the $private_ip on a bare-metal CoreOS deployment, though it can be done. It's therefore not obvious how to run Kubernetes on bare-metal or VMWare CoreOS. I believe this means the [Kubernetes CoreOS multinode cluster demo](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md) needs further documentation; from the CoreOS [docs](https://coreos.com/docs/running-coreos/platforms/vmware/) for their VMware image, "Note: The $private_ipv4 and $public_ipv4 substitution variables referenced in other documents are not supported on VMware."

I've found a couple options that look viable:

* [Run a two-step cloud-config](https://github.com/coreos/coreos-cloudinit/issues/205).
* Hack the /etc/environment using cloud-init as some of the [oem providers](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-rackspace/files/coreos-setup-environment) do. Instructions for creating a [custom CoreOS OEM] (https://coreos.com/docs/running-coreos/bare-metal/booting-with-pxe/) image look useful for the PXE case.

As I'm currently just experimenting with Kubernetes, I can live with static IP config for now.

**Comment by alex-mohr** [comment] 2015-01-29 00:08
@pires @kelseyhightower for https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md clarification?

**Comment by pires** [comment] 2015-01-29 00:24
```$private_ipv4``` works both in Vagrant and GCE. I know that it has worked in AWS from users feedback at ```#google-containers```. If no one is maintaining the VMware instructions, perhaps it's time to remove them?

Anyway, @Symmetric can you remove that flag and have a try? Post the results, please.

**Comment by Symmetric** [comment] 2015-02-18 21:26
@pires , just to confirm that manually fixing the `--hostname_override` flag in the coud_config resolved the problem (I didn't try removing it, don't know if that's an equivalent change).

**Comment by pires** [comment] 2015-02-18 22:10
@Symmetric can you ```cat /etc/environment``` on your CoreOS node(s) and check if ```COREOS_PUBLIC_IPV4``` and ```COREOS_PRIVATE_IPV4``` are correctly set?

**Comment by bgrant0607** [comment] 2015-03-12 00:00
Dupe of #4141 and probably others. Assigning to @erictune to close/dedupe.

**Comment by pires** [comment] 2015-03-12 00:19
@bgrant0607 this is not a dupe of #4141 in the sense that the issue here is with how CoreOS behaves in different environments (in this particular case VMware) when setting `${public,private}_ipv4` environment variable.

Since VMware instructions are not up-to-date, I would recommend removing them.

**Comment by bgrant0607** [comment] 2015-03-12 02:09
Ok, fair point. Kubelet shouldn't be contacting etcd, though.

@erictune is working out what to do with non-up-to-date instructions elsewhere (e.g., #5141).

**Comment by roberthbailey** [comment] 2015-08-27 02:15
Closing as obsolete. Please reopen if this is still an issue that needs to be addressed.

**Closed by roberthbailey** 2015-08-27 02:15 UTC
Labels: area/cluster-lifecycle, area/os/coreos, priority/P3
