### ISSUE TITLE
kube-ui does not show components form namespaces other than "default"

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#14389] opened 2015-09-22 23:33 UTC
It appears that kube-ui supports only 'default' namespace.
Any pod,rc,service created in namespaces other than 'default' are not shown/accessible via kube-ui.

**Comment by emmanuel** [comment] 2015-09-23 01:00
Duplicate of https://github.com/kubernetes/kube-ui/issues/5

**Comment by ichekrygin** [comment] 2015-09-23 16:58
missed the original, thx.

**Closed** 2015-09-23 16:58 UTC
