### ISSUE TITLE
Supply server capabilities along with version

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2953] opened 2014-12-16 00:13 UTC
Currently, the server says what build it is: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L272

It would be handy if the same api endpoint gave a list of "capabilities" of the cluster, such that tests could be run conditional on a capability instead of a (version, provider) pair.

(just writing up @zmerlynn's suggestion from our testing work item doc)

**Comment by smarterclayton** [comment] 2015-01-05 04:31
Capabilities should be well defined as well - every attribute that shows up in a capabilities list is extra overhead for advanced clients, and when capabilities change the behavior of the API increases the number of ways that client operations can fail when run across multiple servers.  Here's a recent discussion from the OpenShift side on how capabilities might be reflected: https://github.com/openshift/origin/pull/569.  We tried to focus on limiting the scope of what capabilities were to true feature flags, and identifying what other components (mostly admission control and authorization) would handle the remainder.

**Comment by bgrant0607** [comment] 2015-01-14 03:33
Why doesn't it work to build the tests with the system?

I agree with @smarterclayton. Note that we have added runtime configuration parameters to the apiserver. Currently, the only one that exists determines whether v1beta3 is exported, which is discoverable via the api version handler.

For features surfaced via API fields, server-side schema validation could be used to confirm support or lack thereof.

In general, I think an end-to-end argument applies: feature existence should be verified by probing its existence.

**Comment by zmerlynn** [comment] 2015-01-14 15:28
@bgrant0607: Read the beginning of the discussion at #3334. There is value in version skewed tests, and many organizations actually keep integration-level tests in a completely separate bucket that just knows how to speak all versions.

First, feature-existence isn't actually all this is meant to cover. There are cases where e.g. patch discovery is useful, like "did you fix this semantic interpretation issue so that I can issue calls in the way I'd prefer and you won't screw up? (otherwise I'm going to fall back on the way that doesn't corrupt things)?" (Without a specific example, this case is hard to describe, but it comes up: An example from previous jobs is cases where one call would do XYZ atomically, but is broken, so you have to fall back to a non-atomic N-step operation.) This is specifically relevant to the case of building a newer kubectl that might have to manipulate objects on an older cluster, which is relevant for things like upgrade. Which is also why you might do version skewed e2e client -> server testing, at the very least, hence discussion in #3334.

I also don't know if we have a generally fast server feature existence path for each feature "thing". Is it fast to determine that we can create a GCE PD? (I haven't checked.) Because `pd.sh` doesn't think so and uses the heavy-handed approach of checking the cloud provider, possibly because it's written in bash. If we surfaced a way to probe some of these things on the CLI, it would be a ton easier.

**Comment by bgrant0607** [comment] 2015-01-14 17:20
@zmerlynn Cross-version testing makes sense. Thanks for the pointer.

With respect to GCE PD, I actually strongly dislike the GCE-specific nature of this part of the API. That said, I'd be open to making it possible to query the cloud platform.

To the extent that we support different feature sets on different platforms or for otherwise different configurations, the reflective parts of the API (e.g., Swagger) should accurately reflect the supported feature set. To the extent that there are numerical limits (e.g., quotas on the number of pods that can be created) that affect client behavior, those should be accessible via reflection API, also.

With respect to workarounds for bugs, yes, I've encountered that in prior work on microprocessors and kernels. For that, I could get behind some kind of vector of issue numbers or PR numbers of fixes since the last major release.

**Comment by smarterclayton** [comment] 2015-01-14 18:23
In practice no non-first party client every does sophisticated detection well (no matter what the server exposes) - for something like Kubernetes, where we want to have APIs for many different languages (because it is an infrastructure component), we need to ensure as much as possible of our API can be discovered, automated, auto-documented, and auto-generated if we want to have the best outcome, and we have to be extra diligent around tests to ensure we never change API behavior except by adding a new property.

For sophisticated clients, the swagger endpoint offers an opportunity to detect whether attributes are available (so we have that covered), but extensible behaviors like volumes need their own discovery (ideally, again, automatically through swagger).  Issues fixed is one way, although I've never seen someone successfully convey that in a useful way to API clients - usually the lifetime of the issue is such that if it's very serious, you issue a high severity patch, otherwise, clients work around it through discovery or probing.

----- Original Message -----

**Comment by lavalamp** [comment] 2016-02-10 21:06
@zmerlynn It seems like this is not happening for 1.2. Holler if you disagree.

**Comment by zmerlynn** [comment] 2016-02-10 21:17
No. I'm pretty sure I'm not the right assignee for this right now, either.

**Comment by bgrant0607** [comment] 2017-03-09 04:20
Closing in favor of other issues, such as #4855.

**Closed by bgrant0607** 2017-03-09 04:20 UTC
Labels: area/api, area/reliability, area/test, area/test-infra, area/upgrade, priority/awaiting-more-evidence, sig/api-machinery, team/control-plane (deprecated - do not use)
