### ISSUE TITLE
Add csi snapshot test cases

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#96618] opened 2020-11-16 20:53 UTC
Consider to add one test case which have volumes taken from snapshot attached to the same node as the source volume. It also covers the case that snapshot is taken while volume is still attached to node.

1. create pvc as source volume, and a pod1 which writes data to the volume.
2. after data writing is finished, take a snapshot of the source volume 
3. create a new pvc which is from the snapshot taken above, 
4 create a new pod2 and assign it to the same node as p1
5. check the volume data

**Comment by jingxu97** [comment] 2020-11-16 20:54
cc @msau42 @xing-yang

**Comment by xing-yang** [comment] 2020-11-16 21:20
@jingxu97 I think this PR addressed this issue:  https://github.com/kubernetes/kubernetes/pull/92555.  Can you take a look?

**Comment by jingxu97** [comment] 2020-11-16 21:33
from what I tested, I think current snapshot tests will delete first pod first, and then create snapshot. The new test case is to keep the first one running while take snapshot, and also when creating the second pod and volume, the first pod and volume still exist.

The test case discovered an issue in windows related to disk offline/online issue mentioned here  https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/664

**Comment by kcmartin** [comment] 2021-03-05 06:23
Hello! I am from the Bug Triage team! This issue has not been updated for a long time, so I'd like to check on the status. The code freeze is starting March 9th, 2021 (less than 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.

As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by erismaster** [comment] 2021-03-12 21:51
Hi, Bug Triage here, I am going to move this to 1.22 milestone since we are past code freeze for 1.21.

/milestone v1.22

**Comment by dims** [comment] 2021-07-15 14:36
/milestone clear

this is just moving from milestone to milestone @msau42 @xing-yang :(

**Comment by xing-yang** [comment] 2021-07-15 15:10
Looks like the contributor who submitted a PR closed it a while ago:(.

**Closed** 2021-08-14 15:18 UTC
Labels: sig/storage, kind/feature, lifecycle/rotten, needs-triage
