### ISSUE TITLE
Kibana doesn't load any data

### ISSUE THREAD

**Issue by maulik887** [kubernetes/kubernetes#12644] opened 2015-08-13 11:40 UTC
Hello, I am trying to add [fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch) in my CoreOS cluster. But I end up having this  
![2015-08-13_1640](https://cloud.githubusercontent.com/assets/11058364/9248531/1ad70e7a-41da-11e5-9ad7-17556c8ec2c8.png)
Kibana doesn't show anything.

Some info about setup-

**Server Version**:
```version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}```

http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/#/settings/indices/?_g=() **I get console error like "Error: IndexPattern's configured pattern does not match any indices" like shown in above screenshot**

http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/elasticsearch/ **this gives me something like this**
```{
status: 200,
name: "Caiman",
cluster_name: "kubernetes-logging",
version: {
number: "1.5.2",
build_hash: "62ff9868b4c8a0c45860bebb259e21980778ab1c",
build_timestamp: "2015-04-27T09:21:06Z",
build_snapshot: false,
lucene_version: "4.10.4"
},
tagline: "You Know, for Search"
}```

**Cluster info**
Kubernetes master is running at http://192.168.20.100:8080
Elasticsearch is running at http://192.168.20.100:8080/api/v1beta3/proxy/namespaces/kube-system/services/elasticsearch-logging
Kibana is running at http://192.168.20.100:8080/api/v1beta3/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at http://192.168.20.100:8080/api/v1beta3/proxy/namespaces/kube-system/services/kube-dns

**elasticsearch:1.7 docker log**
```
I0813 09:44:50.709621       6 elasticsearch_logging_discovery.go:42] Kubernetes Elasticsearch logging discovery
I0813 09:44:50.749147       6 elasticsearch_logging_discovery.go:75] Found ["20.0.5.5" "20.0.96.4"]
I0813 09:45:00.753193       6 elasticsearch_logging_discovery.go:75] Found ["20.0.5.5" "20.0.96.4"]
I0813 09:45:00.753256       6 elasticsearch_logging_discovery.go:87] Endpoints = ["20.0.5.5" "20.0.96.4"]
[2015-08-13 09:45:01,822][INFO ][node                     ] [Caiman] version[1.5.2], pid[12], build[62ff986/2015-04-27T09:21:06Z]
[2015-08-13 09:45:01,823][INFO ][node                     ] [Caiman] initializing ...
[2015-08-13 09:45:01,828][INFO ][plugins                  ] [Caiman] loaded [], sites []
[2015-08-13 09:45:05,113][INFO ][node                     ] [Caiman] initialized
[2015-08-13 09:45:05,114][INFO ][node                     ] [Caiman] starting ...
[2015-08-13 09:45:05,306][INFO ][transport                ] [Caiman] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/20.0.5.5:9300]}
[2015-08-13 09:45:05,319][INFO ][discovery                ] [Caiman] kubernetes-logging/xw-Jftk_RLefH6P_gUVvSQ
[2015-08-13 09:45:08,402][INFO ][cluster.service          ] [Caiman] detected_master [Conquer Lord][Py2pJLfeR1aEuFlyj6pF_g][elasticsearch-logging-v1-wxmik][inet[/20.0.96.4:9300]]{master=true}, added {[Conquer Lord][Py2pJLfeR1aEuFlyj6pF_g][elasticsearch-logging-v1-wxmik][inet[/20.0.96.4:9300]]{master=true},}, reason: zen-disco-receive(from master [[Conquer Lord][Py2pJLfeR1aEuFlyj6pF_g][elasticsearch-logging-v1-wxmik][inet[/20.0.96.4:9300]]{master=true}])
[2015-08-13 09:45:08,442][INFO ][http                     ] [Caiman] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/20.0.5.5:9200]}
[2015-08-13 09:45:08,443][INFO ][node                     ] [Caiman] started
```

**kibana:1.3 docker log**
```ELASTICSEARCH_URL=http://elasticsearch-logging:9200
{"@timestamp":"2015-08-13T10:04:11.613Z","level":"info","message":"No existing kibana index found","node_env":"production"}
{"@timestamp":"2015-08-13T10:04:11.630Z","level":"info","message":"Listening on 0.0.0.0:5601","node_env":"production"}
```

Please do let me know if any other info you want me to share. (I'm tagging @satnam6502 here, as I saw you did lot of work around this addon) Please let me know what's wrong here.

**Comment by maulik887** [comment] 2015-08-13 11:45
Even I also tried ubuntu setup. Which is also giving me same error..

[Ubuntu Setup](https://github.com/kubernetes/kubernetes/tree/master/cluster/ubuntu)

**Comment by satnam6502** [comment] 2015-08-13 14:57
Sorry for the hassle -- I'll see if I can understand what is going on although I am not sure I know how to repo given the CoreOS setup.

**Comment by maulik887** [comment] 2015-08-13 17:08
Thank you for your help satnam, You can refer to above ubuntu setup or can use master & node.yaml mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md) to bring up CoreOS setup using vagrant & virtual box (what I have). You might end up having same issue. One thing to add here, in my coreos setup I manually create elastic search and kibana service & replication controller.

Plus, let me know if there is anything I can look at to debug this issue.

**Comment by maulik887** [comment] 2015-08-19 06:40
Sorry I'm stretching you guys.. but any update on this ?

**Comment by satnam6502** [comment] 2015-08-19 06:47
(Sorry -- I have been a bit distracted of late -- let me try to remember to look at this on Wednesday)

**Comment by satnam6502** [comment] 2015-08-19 21:07
So far I have managed to get Kibana up and working under a GCE setup... still seeing if I can repo what is reported here.

**Comment by satnam6502** [comment] 2015-08-19 21:12
I ran the counter demo:
```console
$ cd examples/blog-logging
$ kubectl create -f counter-pod.yaml 
```

and I see the synthetic counter/logger lines ingested. I will keep digging...

![working-kibana](https://cloud.githubusercontent.com/assets/6164339/9369136/329e8438-467c-11e5-8b8f-291d9e1e91ef.png)

**Comment by satnam6502** [comment] 2015-08-19 21:18
I see you are accessing the cluster via `kubectl proxy`. Please can you tell me what you see when you access `http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/_search?size=10` ?

I see something like:
```console
{"took":10,"timed_out":false,"_shards":{"total":6,"successful":6,"failed":0},"hits":{"total":22487,"max_score":1.0,"hits":[{"_index":".kibana","_type":"config","_id":"4.0.2","_score":1.0,"_source":{"buildNum":6004,"defaultIndex":"logstash-*"}},{"_index":".kibana","_type":"index-pattern","_id":"logstash-*","_score":1.0,"_source":{"title":"logstash-*","timeFieldName":"@timestamp","customFormats":"{}","fields":"[{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"stream\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_source\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"tag\",\"count\":79,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_index\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"log\",\"count\":84,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"message\",\"count\":83,\"scripted\":false},{\"type\":\"date\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"@timestamp\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"name\":\"_type\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_id\",\"count\":0,\"scripted\":false}]"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzZfdoTmhs8o5Xn","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:03.055086176Z\" level=info msg=\"GET /containers/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:03+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzZfdoTmhs8o5Xs","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:03.072281352Z\" level=info msg=\"GET /containers/json?all=1\" ","tag":"docker","@timestamp":"2015-08-19T21:01:03+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzZfdoTmhs8o5Xx","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:03.360340033Z\" level=info msg=\"GET /containers/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:03+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzZfdoTmhs8o5X2","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:03.868605914Z\" level=info msg=\"GET /containers/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:03+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzZfdoTmhs8o5X7","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:04.376508356Z\" level=info msg=\"GET /containers/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:04+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzafdoTmhs8o5YA","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:04.783193456Z\" level=info msg=\"GET /containers/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:04+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzafdoTmhs8o5YF","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:05.572175038Z\" level=info msg=\"GET /containers/json?all=1\" ","tag":"docker","@timestamp":"2015-08-19T21:01:05+00:00"}},{"_index":"logstash-2015.08.19","_type":"fluentd","_id":"AU9HxFzafdoTmhs8o5YK","_score":1.0,"_source":{"message":"time=\"2015-08-19T21:01:05.577306332Z\" level=info msg=\"GET /containers/f4f759f5cc8d964d4b3b26c4da0a8fdca5181ee2e6984cde147ce497cc67f777/json\" ","tag":"docker","@timestamp":"2015-08-19T21:01:05+00:00"}}]}}
```

**Comment by satnam6502** [comment] 2015-08-19 23:24
@maulik887 let me know if you would prefer an interactive chat / session if it helps -- I am not sure if I will ever get the time to repro a CoreOS setup.

**Comment by maulik887** [comment] 2015-08-20 10:18
I get this if I visit http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/_search?size=10

```
{"took":2,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
```
docker containers (ec & kibana) still gives me logs I mentioned above.

I'm more than happy to have interactive session to trace down this issue. I sent you details on your email (satnam@raintown.org).

**Comment by satnam6502** [comment] 2015-08-20 15:36
Well that is useful information: the root of the problem is not with Kibana, but with the underlying infrastructure that tries to get logs from the nodes to the Elasticsearch service. Let me think of a few more questions to ask you...

**Comment by SchwarzM** [comment] 2015-08-21 12:13
Hi,

we've got the same problem and as far as i understood it it's within the fluentd-elasticsearch bridge.
It mounts /var/log from the host which holds no logs because coreos uses journalctl.
It mounts /var/lib/docker/containers which displays no data because on coreos this is root:root 700.

Kind regards
Marian Schwarz

**Comment by maulik887** [comment] 2015-08-21 15:46
Sorry, What do you mean by this ? Didn't get your point. 
> edit: nvm got it running

**Comment by satnam6502** [comment] 2015-08-21 15:51
Hello @SchwarzM : are you saying that Docker puts its container logs under `jouranalctl` something on CoreOS? That, indeed, would be bad. Let me look into paramaterizied the name of the directory that contains the Docker container logs. That way you can use an ENV var in the pod spec to define the location of the Docker container logs.

**Comment by satnam6502** [comment] 2015-08-28 20:51
I am closing this issue since I have no heard anything back yet, and also because I am leaving Google and Kubernetes today.

**Closed by satnam6502** 2015-08-28 20:51 UTC
Labels: kind/support, priority/P1, team/cluster

**Comment by KeithTt** [comment] 2017-03-15 08:37
I met the same error.

OS: CentOS7
Kube Version: 1.5.3

```
{"type":"log","@timestamp":"2017-03-14T06:06:56Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":7,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-03-14T06:07:00Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":7,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
```

**Comment by rootsongjc** [comment] 2017-04-12 14:16
+1 
Same problem.
**My environment**
kubernetes 1.6.0
centos 7.2.1511
docker 1.12.5
There is no data in `/var/log/containers` .

**Comment by nelsonfassis** [comment] 2018-01-05 00:30
You can "fix" it by editing /etc/docker/daemon.json and tell docker to log on files:
{
"log-driver": "json-file",
"log-opts": {
"max-size": "1m",  # Max size of the log files.  
"max-file": "3"    # The maximum number of log files that can be present.
 }
This will make the *.log available for filebeat/fluentd to read from.
