### ISSUE TITLE
could not read an encoded object cannot unmarshal bool into Go value of type string

### ISSUE THREAD

**Issue by nhumrich** [kubernetes/kubernetes#14948] opened 2015-10-01 22:50 UTC
Getting an error while running
 
    kubectl create -f myrc.yaml

The yaml file has a boolean environment variable:

    spec:
      containers:
           ...
        env:
        - name: MY_ENV
          value: true

and I get the error:

    error: could not read an encoded object from myrc.yml: unable to load "myrc.yml": json: cannot unmarshal bool into Go value of type string

Changing the value to "true" makes it work, but I dont want it as a string, I want it set as a boolean.

**Comment by JanetKuo** [comment] 2015-10-02 00:57
Here's the model of env. The type of `value` should be `string`.  
```
v1.EnvVar {
  name (string): Name of the environment variable. Must be a C_IDENTIFIER. ,
  value (string, optional): Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "". ,
  valueFrom (v1.EnvVarSource, optional)
}
```

**Comment by pmorie** [comment] 2015-10-03 21:18
Can we close this?  It's working as intended.

**Closed** 2015-10-07 17:39 UTC
Labels: kind/support, priority/P2, team/ux
