### ISSUE TITLE
is kubernetes 1.9.2 don't support  --etcd-servers-overrides crd type

### ISSUE THREAD

**Issue by zky881220** [kubernetes/kubernetes#81508] opened 2019-08-16 10:40 UTC
[environment]
kubernetes 1.9.2
--etcd-servers-overrides=isolate.harmonycloud.cn/hleases#http://10.10.101.176:2379

crd.yaml
`apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hleases.isolate.harmonycloud.cn
spec:
  group: isolate.harmonycloud.cn
  version: v1alpha1
  names:
    kind: HLease
    plural: hleases
  scope: Namespaced`

[expected results]
hleases relate reaquest redirect 10.10.101.176:2379

[actual results]
hleases relate reaquest don't redirect 10.10.101.176:2379

**Comment by zegl** [comment] 2019-08-18 20:21
Kubernetes 1.9 is no longer supported, please check if you can reproduce this bug with newer versions of Kubernetes.

**Comment by Belyenochi** [comment] 2019-08-19 07:23
I have the same question
[env]
kubernetes 1.13.2

**Comment by liggitt** [comment] 2019-09-10 13:53
etcd server overrides are not currently supported for custom resource types

**Comment by raushan2016** [comment] 2019-10-19 00:50
+1 same scenarios, want to use crds with custom etcd.

**Comment by MikeSpreitzer** [comment] 2020-02-21 03:39
/remove-lifecycle rotten
This is still an interesting issue.

**Comment by jdumars** [comment] 2020-02-24 23:00
@liggitt this is something we're going to need to look at - any help getting this landed somewhere would be greatly appreciated!  cc: @lavalamp

**Comment by dims** [comment] 2020-02-24 23:05
@jdumars got someone who can clean up https://github.com/kubernetes/kubernetes/pull/84467 ?

**Comment by liggitt** [comment] 2020-02-24 23:09
See also https://github.com/kubernetes/kubernetes/pull/82580#issuecomment-535499216

Static cli options (--etcd-servers-overrids) that pair with dynamic api-specified options (dynamic custom resource API types) are pretty strange, so it's not clear this is the right way to accomplish parceling out custom resources to different etcd instances.

**Comment by lavalamp** [comment] 2020-02-24 23:09
@jpbetz should know the current state.

**Comment by lavalamp** [comment] 2020-02-24 23:10
Like I said on the mailing list, this would be a super dangerous flag to change. It's currently (afaik) only used for events, which are considered best effort.

**Comment by jpbetz** [comment] 2020-02-24 23:18
+1 to https://github.com/kubernetes/kubernetes/issues/81508#issuecomment-590595212

Details on what is motivating this might be helpful here. Is there an etcd limitation? If so, what etcd version is in use?

**Comment by MikeSpreitzer** [comment] 2020-02-25 00:45
I am motivated to consider this because of data volume considerations.  I am using Kubernetes API machinery to build an infrastructure cloud's control plane.  The total data volume for a datacenter is not something I can convince myself will fit in 8 GB; in fact, I am fairly confident it will not fit.

Etcd 3.2 and higher seem to be unreliable regarding startup --- there is flakiness in the TLS session establishment.

**Comment by MikeSpreitzer** [comment] 2020-02-25 00:46
I would be happy for a solution in which the custom resources are not really dynamic.

**Comment by alena1108** [comment] 2020-02-25 00:52
@jpbetz In general, it makes sense to provide etcd as an app-specific data store, especially as you have proliferation of CRDs. And proliferation is going to be inevitable k8s clusters grow in size (https://kubernetes.io/docs/setup/best-practices/cluster-large/) and more system/user workloads running as Kubernetes apps in these big clusters leveraging etcd as their data store.

Using structured etcd config over cli flag sounds like a great idea.

**Comment by jpbetz** [comment] 2020-02-25 01:02
> Etcd 3.2 and higher seem to be unreliable regarding startup --- there is flakiness in the TLS session establishment.

Do we have an issue open for this already?

**Comment by MikeSpreitzer** [comment] 2020-02-25 01:36
@matte21 : can you please report here what you found about etcd cluster startup flakiness?

**Comment by matte21** [comment] 2020-02-25 02:15
I used to deploy a 3-member etcd v3.3.11 cluster on a Kubernetes 1.16 IKS cluster. The etcd cluster was used to store CRs defined via API aggregation, and was managed via coreOS's [etcd operator](https://github.com/coreos/etcd-operator/tree/v0.9.4) v0.9.4.

I had successfully deployed the etcd cluster and accessed the API objects stored in it countless times on the very same IKS cluster, but one day, after deploying it, the weird behavior began. More precisely, the first member would always start up successfully, but the second member encountered an error and got stuck in failed state without being replaced. Its logs terminated with 

> 2020-02-10 22:23:40.466759 W | etcdserver: could not get cluster response from https://the-etcd-cluster-qdwdv2ctn7.the-etcd-cluster.example-com.svc:2380: Get https://the-etcd-cluster-qdwdv2ctn7.the-etcd-cluster.example-com.svc:2380/members: EOF
2020-02-10 22:23:40.467349 C | etcdmain: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given urls

where  `the-etcd-cluster-qdwdv2ctn7`  is the first member of the etcd cluster. The third member's pod was never created. This behavior happened around  80% of the times. In the remaining 20% the cluster got up and running and operated correctly; the 1st and second members of the cluster were up and running immediately, while the third member failed to start, got replaced (too quickly for me to intercept its logs) and then started correctly. Both the 2nd and 3rd member logs contained messages like:
> 2020-02-11 14:11:03.413970 I | embed: rejected connection from "172.30.171.153:47446" (error "tls: \"172.30.171.153\" does not match any of DNSNames [\"*.the-etcd-cluster.example-com.svc\" \"*.the-etcd-cluster.example-com.svc.cluster.local\"]", ServerName "the-etcd-cluster-nqkqzxqgzt.the-etcd-cluster.example-com^C I | embed: rejected connection from "172.30.171.153:47458" (error "tls: \"172.30.171.153\" does not match any of DNSNames [\"*.the-etcd-cluster.example-com.svc\" \"*.the-etcd-cluster.example-com.svc.cluster.local\"]", ServerName "the-etcd-cluster-nqkqzxqgzt.the-etcd-cluster.example-com.svc", IPAddresses [], DNSNames ["*.the-etcd-cluster.example-com.svc" "*.the-etcd-cluster.example-com.svc.cluster.local"])

I observed the issue only when TLS was enabled, I did many trials w/o TLS and the cluster started and operated perfectly fine.
I also tried many deployments with TLS on but different etcd versions. I observed the issue with
 `v3.2.0` and `v3.4.3`, never with `v3.1.15`, `v3.1.16` and `v3.1.20`.

After some experiments without solving the issue I deleted my IKS cluster and got a new one with Kubernetes 1.15. I've never seen the issue again since then.

For completeness:
manifest of the etcd cluster: https://github.com/MikeSpreitzer/kube-examples/blob/add-kos/staging/kos/deploy/etcd-cluster/48-etcd.yaml
manifest of the etcd operator: https://github.com/MikeSpreitzer/kube-examples/blob/add-kos/staging/kos/deploy/etcd-operator/47-eo-theop.yaml

**Comment by jpbetz** [comment] 2020-02-25 04:44
Thanks for the detailed report @matte21. I've cross posted it to https://github.com/coreos/etcd-operator/issues/2163. Let's discuss it further there.

**Comment by jdumars** [comment] 2020-02-25 17:17
thank you all for looking into this

**Comment by MikeSpreitzer** [comment] 2020-04-06 20:57
Not done here.

**Comment by saintwang007** [comment] 2021-11-19 06:09
> Not done here until there is a way for resources defined by CRDs to be stored in their own etcd clusters.

Has it been supported ？

**Comment by jpbetz** [comment] 2021-11-19 17:18
> > Not done here until there is a way for resources defined by CRDs to be stored in their own etcd clusters.
> 
> Has it been supported ？

No, AFAIK there has been no activity on this. But the question comes up every once and a while so I think it's appropriate to keep this open.

/reopen
/remove-lifecycle rotten

**Comment by jpbetz** [comment] 2021-11-19 17:25
Looks like the main roadblocks here are:
- Changing the flag is dangerous: https://github.com/kubernetes/kubernetes/issues/81508#issuecomment-590595569
- CLI flags are defined at api-server start up but custom resources are dynamic, so they don't pair well: https://github.com/kubernetes/kubernetes/issues/81508#issuecomment-590595212

**Comment by MikeSpreitzer** [comment] 2021-11-19 17:33
Yes, I agree.  I think the right approach to this would be through API objects rather than command line flags.

**Closed** 2022-04-22 22:46 UTC
Labels: priority/awaiting-more-evidence, sig/api-machinery, kind/feature, area/custom-resources, lifecycle/rotten, triage/accepted

**Comment by fourierr** [comment] 2023-09-28 06:11
Has it been supported ？
