### ISSUE TITLE
Say namespace does not exist when getting pods

### ISSUE THREAD

**Issue by martinmosegaard** [kubernetes/kubernetes#60974] opened 2018-03-09 13:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I created a namespace, then tried to get pods in it, but misspelled the namespace. The message was that there were no resources, which is not wrong. But it was clearer to me when I tried to describe the namespace and was told that the namespace did not exist:

```
~ $ kubectl create ns linuxcon
namespace "linuxcon" created
~ $ kubectl get ns
NAME          STATUS    AGE
default       Active    89d
kube-public   Active    89d
kube-system   Active    89d
linuxcon      Active    3s
~ $ kubectl get pods -n linuxctl <-- This is me misspelling
No resources found.
~ $ kubectl describe ns linuxctl
Error from server (NotFound): namespaces "linuxctl" not found <-- Oh. Right.
```

**What you expected to happen**:
Getting objects in an invalid namespace would tell me that the namespace is invalid:

```
~ $ kubectl get pods -n linuxctl
Error from server (NotFound): namespaces "linuxctl" not found
```

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.0
- Cloud provider or hardware configuration: Mac 
- OS (e.g. from /etc/os-release): macOS 10.13.3
- Kernel (e.g. `uname -a`): Darwin Kernel Version 17.4.0
- Install tools:
- Others:

**Comment by liggitt** [comment] 2018-03-10 03:09
Duplicate of https://github.com/kubernetes/kubernetes/issues/31753

**Comment by liggitt** [comment] 2018-03-10 03:09
At one point, a client-side check was added on notfound errors - https://github.com/kubernetes/kubernetes/pull/31594/files

**Closed** 2018-08-07 04:50 UTC
Labels: kind/feature, lifecycle/rotten, sig/cli
