### ISSUE TITLE
Got error "tls: oversized record received with length 20527" when using https_proxy for oc exec

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#15839] opened 2015-10-19 11:09 UTC
Version-Release number of selected component (if applicable):
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.1286+67cb65d906620f-dirty", GitCommit:"67cb65d906620f5abaa22a6dbc067dfa2b4d2482", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.1286+67cb65d906620f-dirty", GitCommit:"67cb65d906620f5abaa22a6dbc067dfa2b4d2482", GitTreeState:"dirty"}

How reproducible:
always

Steps to Reproduce:
1.openssl generate the ca.crt, server.key, server.crt
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authentication.md#creating-certificates 
2.start kube-api 
/root/kubernetes/_output/local/bin/linux/amd64/kube-apiserver --v=3 --cert-dir=/var/run/kubernetes --tls-cert-file=/root/ca/server.crt --tls-private-key-file=/root/ca/server.key --service-account-key-le=/tmp/kube-serviceaccount.key --service-account-lookup=false --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --etcd-servers=http://127.0.0.1:4001 --service-cluster-ip-range=10.0.0.0/24 --cors-allowed-origins="/127.0.0.1(:[0-9]+)?$,/localhost(:[0-9]+)?$" --bind-address=172.18.6.132 --secure-port=8443 --client-ca-file=/root/ca/ca.crt

3.run the exec without https_proxy exported
[root@ip-172-18-6-132 kubernetes]# cluster/kubectl.sh --insecure-skip-tls-verify=true --client-certificate=/root/ca/ca.crt --client-key=/root/ca/ca.key  --server=https://172.18.6.132:8443 exec nginx ls
bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var

4.set the https_proxy 
export https_proxy=https://172.18.6.132:3128/
5.
cluster/kubectl.sh --insecure-skip-tls-verify=true --client-certificate=/root/ca/ca.crt --client-key=/root/ca/ca.key  --server=https://172.18.6.132:8443 exec nginx ls
error: error sending request: Post https://172.18.6.132:8443/api/v1/namespaces/default/pods/nginx/exec?command=ls&container=nginx&container=nginx&stderr=true&stdout=true: tls: oversized record received with length 20527

log info in the  /var/log/squid/access.log is as below:

1445250946.180      0 172.18.6.132 NONE/400 4115 NONE error:invalid-request - HIER_NONE/- text/html
1445250946.181    160 172.18.6.132 TCP_MISS/200 3208 CONNECT 172.18.6.132:8443 - HIER_DIRECT/172.18.6.132 -

Actual results:
received error message "tls: oversized record received with length 20527"

Expected results:
should get the result as the step 1 

Additional info:
http_proxy works fine

**Comment by jlowdermilk** [comment] 2015-10-20 21:08
What platform are you running on?

**Comment by chao007** [comment] 2015-10-21 01:31
RHEL7

**Comment by ashcrow** [comment] 2015-10-21 01:57
Interesting. That log looks to state that the method and code are both NONE. I wonder if this is a squid TLS configuration issue. Can you provide more information on the squid servers configuration?

**Comment by ncdc** [comment] 2015-10-21 02:27
I believe the issue is that you're setting https_proxy to https://... when it most likely should be **http**://. In other words, `export export https_proxy=http://172.18.6.132:3128/`. Can you try that?

**Comment by ashcrow** [comment] 2015-10-21 02:33
@ncdc beat me to it. I was just verifying the same thing reading http://wiki.squid-cache.org/Features/HTTPS :smile:

**Comment by chao007** [comment] 2015-10-21 11:28
it is worked for oc exec when export https_proxy=http://172.18.6.132:3128
thanks

**Comment by ncdc** [comment] 2015-10-21 13:40
Glad to hear it worked. I'm going to close this.

**Closed by ncdc** 2015-10-21 13:40 UTC
Labels: team/CSI

**Comment by ssharifi02** [comment] 2016-07-19 11:46
so when i got the tls oversized issue i did try many things such as increasing the disk size, but at the end i did use the $docker-machine regenerate-certs default. and it worked this time

**Comment by wilderfield** [comment] 2018-08-08 22:09
You people are AMAZING!!!!!!!
I have been getting this same error message from git lfs when trying to push files to a git repo.

The problem was that I had HTTPS_PROXY=https://proxy:8080 when it should have been http://proxy:8080

Wow, I've been setting this variable incorrectly for 8 years now, and it finally bit me... causing me hours of wasted effort. Thank you all!

**Comment by Madhansudhan** [comment] 2019-04-26 08:01
Hi, am getting below error when i tried checking etcd cluster health status.  AM maintaining external etcd cluster(3 nodes) and checking health status with http , the cluster status was healthy.

Error:  client: etcd cluster is unavailable or misconfigured; error #0: tls: oversized record received with length 20527

**Comment by cgironda** [comment] 2019-05-23 09:48
Thanks to Andy Goldstein (ncdc), who propose a solution in 2015, I solve the same problem. Thank you.
