### ISSUE TITLE
ci-kubernetes-e2e-kops-aws is broken

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42461] opened 2017-03-03 01:56 UTC
It's been broken since noon: https://k8s-testgrid.appspot.com/sq-blocking#kops-aws
Failure examples:
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/4942
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/4941
potential offenders: https://github.com/kubernetes/kubernetes/compare/8cc7475...1d97472

The RC/RS PR seems to be the major one: #41984 /cc @enisoc

I only checked the one failure shown up in my PR https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42264/pull-kubernetes-e2e-kops-aws/15658/
While the cluster was still starting up (kubelet registering itself, creating mirror pods, etc), the replicaset created >70 kube-dns pods in less than 40s because all pods were rejected.
 1. The mirror pods on the master were not fully created yet, and the dns pods got assigned to the master node and rejected by kubelet due to insufficient resources on the node.
 2. After the mirror pods were created correctly, there was still one node that hadn't registered yet. All new dns pods failed at scheduling because the pod could not fit on any node.

For (2), After the node registered itself, it waited for ~50 to be assigned the pod CIDR. Seems a little bit high to me.
Also, on GCE, master nodes are unschedulable (taint?), but that doesn't seem like the case on AWS. Not sure if this is a feature or bug.

/cc @justinsb

**Comment by yujuhong** [comment] 2017-03-03 02:13
/cc @k8s-oncall 

This is blocking the submit queue.

**Comment by yujuhong** [comment] 2017-03-03 02:18
Also, the `kube-dns-autoscaler` pod entered crashloop backoff.

**Comment by yujuhong** [comment] 2017-03-03 02:25
> Also, the kube-dns-autoscaler pod entered crashloop backoff.

/c @MrHohn

**Comment by yujuhong** [comment] 2017-03-03 02:27
The failed dns pods should resolve by itself, but the `kube-dns-autoscaler` crashlooping seems to be the main problem(?)

**Comment by MrHohn** [comment] 2017-03-03 02:29
kubernetes/kops/pull/1997 added a new kube-dns template to kops but it forgot to remove this line https://github.com/kubernetes/kops/pull/1997/files#diff-6df1ffa89925b902fe586aca846f2bb0R44.

**Comment by smarterclayton** [comment] 2017-03-03 02:47
After we get a fix can we get a determination why it took 10 hours to respond to a broken job?

**Comment by smarterclayton** [comment] 2017-03-03 02:53
@kubernetes/sig-testing-misc re: above and discussion, maybe we should assign some jobs to sigs and have an email list for when the queue breaks.  Not all jobs are like that, but maybe we can get sig job on-calls from each sig during release weeks (and rotate among sigs)

**Comment by justinsb** [comment] 2017-03-03 03:03
Just merged the fix to dns-horizontal-autoscaler - thanks @MrHohn .  I was also looking at the kops build issue - we had an unrelated problem which I thought was the issue https://github.com/kubernetes/kubernetes/issues/42433 though I do think / hope that the cluster autoscaler fix will get it.

And yes, we should definitely have a slack room for any jobs that are submit-queue blockers.  Maybe even pager duty during "working hours".  I hadn't realized the queue was blocked until @smarterclayton pinged me - thank you.

Now I need to figure out how the bad build made it to the submit queue stage - we have some interlocks that should have prevented it (i.e. we can break kops without it breaking the submit queue, because we track the "last known good kops version").  But somehow one "lucky kops build" made it through testing - an anti-flake.

**Comment by apelisse** [comment] 2017-03-03 03:09
We have a pager duty for "working hours", it's https://github.com/k8s-oncall. And it's me, I've tried to investigate the issue but couldn't find the offender (was it really #41984?). I should have reverted or asked for help on slack (where?).
Sorry about that.

**Comment by justinsb** [comment] 2017-03-03 03:11
I'm also working on getting e2e jobs to add testing against the various k8s versions with kops: https://github.com/kubernetes/test-infra/pull/2106

**Comment by justinsb** [comment] 2017-03-03 03:16
@apelisse I don't think it was #41984 - I think it was much more likely to be https://github.com/kubernetes/kops/pull/1997 , but then I am a little perplexed as to how it passed the pre-test once and made it to the blocking job.  Maybe a race if we observe it before the autoscaler job fails - e.g. if we're slow to pull the image.

I definitely don't mind being pinged in slack on any AWS job.  And I don't think it's unreasonable to make pagerduty during "working hours" a requirement for having a submit-queue-blocking job, as long as we can figure out how not to exclude asia / europe.  I guess for now the k8s-oncall can just ping me on the AWS jobs on slack or I can share my phone #...

**Comment by apelisse** [comment] 2017-03-03 03:34
Are you telling me that there is an external implicit dependency that broke kubernetes/kubernetes and that there is no way to tell? *mild shock*. Seriously, that sounds like a bad idea. Shouldn't we have dependencies defined/committed in one place? And the submit-queue for k/k shouldn't break because another commit happens in another repo?

I'll definitely keep note that I can ask for your help if AWS breaks.

**Comment by smarterclayton** [comment] 2017-03-03 03:40
I was thinking maybe just trying to have a way for random folks to connect a problem in a job with a set of people to ask - I always feel guilty about asking the build cop, and I think it's probably a good thing to grease the skids for queue -> sigs -> triage as we get bigger.

**Comment by smarterclayton** [comment] 2017-03-03 03:41
Heck, if the job flake comment had an @ group for the flaking job (and a corresponding slack channel link on the test grid) that could potentially address the "who do I ask" question.

**Comment by smarterclayton** [comment] 2017-03-03 03:42
We got a green, so hopefully back to working.

**Comment by yujuhong** [comment] 2017-03-03 03:43
> We got a green, so hopefully back to working.

Yep. Pretty sure it's fixed.

Closing this issue and move the discussion to improve the flow somewhere else?

**Comment by yujuhong** [comment] 2017-03-03 03:44
> Yep. Pretty sure it's fixed.

Never mind....one green and then a red again.

**Comment by justinsb** [comment] 2017-03-03 03:49
So @zml can probably explain better, but the issue here is that we have safety mechanisms but that (for some reason) they failed.  We actually could consider these safety mechanisms for _all_ the blocking jobs.  If the safety mechanisms stop the queue from being blocked when it would otherwise be, so much the better :-) 

So what is this magical safety mechanism?  All credit to @zmerlynn for devising this, and all errors in the description here are my own:

* We have a simple job https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-kops-aws-updown.env which brings a cluster up and down with kops, and checks for basic operation.  Only if this job passes will the kops build be marked "good" and the version written to `latest-ci-updown-green.txt`
* The submit queue blocker then checks kubernetes head against that `latest-ci-updown-green.txt` version of kops.  Hopefully that will be the most recent version of kops, but if we break kops at head we don't break the submit queue.

So the kops build was broken - I hope by https://github.com/kubernetes/kops/pull/1997 but then somehow 8301 got through ( https://k8s-testgrid.appspot.com/google-aws#kops-aws-updown ).  So then the broken kops build was promoted and blocked the submit queue.

Of course, it is _also_ possible that #41984 or something else entirely has _also_ caused flakiness - some of the GCE / GKE jobs don't look 100% happy.  I think root root cause there is that we pushed a lot of PRs in to meet the feature freeze deadline and so we're seeing the resulting flakiness from all that new code.

**Comment by smarterclayton** [comment] 2017-03-03 03:50
GKE fix is in (merged that a few minutes ago).  How long does it take for a kops fix to propagate to queue?  Instant?

**Comment by smarterclayton** [comment] 2017-03-03 04:08
Got it, thanks.

**Comment by yujuhong** [comment] 2017-03-03 04:08
Both https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-updown/8301 and https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/4945 are interesting flakes though...

Just right before the 10 minute timeout, the test declared all kube-system pods (including `kube-dns-autoscaler`) were running and ready.

**Comment by justinsb** [comment] 2017-03-03 04:13
Just posted in sig-testing a request for someone to check if jenkins is really overloaded, as it looks like that is why 8310 missed ("If anyone has access to jenkins, I'm trying to understand why `ci-kops-build` took half an hour to trigger (AFAICT).  The build is https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kops-build/344 , the commit is https://github.com/kubernetes/kops/pull/2044 merged at 18:54 Pacific, but it looks like the job didn't start till  19:29 Pacific")

Looking at the flakes now.  I'm wondering if it is because the kube-dns-autoscaler would presumably be in a restart loop, and maybe we just got really "lucky"?

**Comment by justinsb** [comment] 2017-03-03 04:22
So `kube-dns-autoscaler` has no health check configured, and in our case would crash on startup.  Would it be momentarily ready while the pod had been created, but before it had crashed (because no health-check?).

**Comment by ethernetdan** [comment] 2017-03-03 04:30
> Heck, if the job flake comment had an @ group for the flaking job (and a corresponding slack channel link on the test grid) that could potentially address the "who do I ask" question.

+1

**Comment by justinsb** [comment] 2017-03-03 05:40
kops seems happy again :-)

**Comment by pwittrock** [comment] 2017-03-11 00:24
@justinsb Please close the issue if it is resolved.

**Closed** 2017-03-13 20:29 UTC
Labels: area/test, kind/bug, priority/critical-urgent, sig/aws
