### ISSUE TITLE
Integration flake: etcd cluster is unavailable in TestStoreDeleteCollectionNotFound

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#26403] opened 2016-05-27 07:56 UTC
Haven't found a flake really matching this, maybe https://github.com/kubernetes/kubernetes/issues/13117?

```
--- FAIL: TestStoreDeleteCollectionNotFound (4.60s)
	store_test.go:868: Unexpected error: client: etcd cluster is unavailable or misconfigured
=== RUN   TestStoreDeleteCollectionWithWatch
--- PASS: TestStoreDeleteCollectionWithWatch (0.85s)
=== RUN   TestStoreWatch
--- PASS: TestStoreWatch (2.05s)
FAIL
FAIL	k8s.io/kubernetes/pkg/registry/generic/registry	17.095s
```

Reference: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23801/kubernetes-pull-test-unit-integration/28159/

**Comment by dchen1107** [comment] 2016-05-27 16:06
@lavalamp Please triage.

**Comment by caesarxuchao** [comment] 2016-06-01 18:33
I'll take a look.

**Comment by caesarxuchao** [comment] 2016-06-01 21:32
@hongchaodeng @xiang90 could you take a look? Thanks.

**Comment by xiang90** [comment] 2016-06-01 22:15
@caesarxuchao Sure. I guess the etcd cluster was not fully started when the client made the first request. But we will try to reproduce and fix.

**Comment by xiang90** [comment] 2016-06-02 15:59
@caesarxuchao Can you reproduce this locally? I tried run the test for 1000s of times, but still could not reproduce it. Do you know the machine type that fails this test?

**Comment by caesarxuchao** [comment] 2016-06-02 18:04
@xiang90 no, I cannot reproduce it either. I don't know the machine type, I'm trying to find it out.

**Comment by xiang90** [comment] 2016-06-02 18:09
@caesarxuchao Sure. Thanks.

**Comment by caesarxuchao** [comment] 2016-06-02 18:15
> I guess the etcd cluster was not fully started when the client made the first request. But we will try to reproduce and fix.

I guess you've noticed there are two other calls to etcd to create objects before the line that returns the error, so the etcd cluter should have fully started.

**Comment by xiang90** [comment] 2016-06-02 18:30
@caesarxuchao Yes. I found that out... So I asked for a reproduce... Also this test starts a one node etcd cluster, so there should be no unavailability issue.

**Comment by ixdy** [comment] 2016-06-02 19:16
It's probably cause we're running too much at once on our Jenkins VMs. See #26420.

**Comment by xiang90** [comment] 2016-06-02 22:49
@ixdy That is possible. I will run a for loop with this test to see if CPU starvation can trigger it.

**Comment by lavalamp** [comment] 2016-06-06 20:43
@xiang90 any findings?

**Comment by caesarxuchao** [comment] 2016-06-09 22:40
I'm closing this one. It's a dupe of #25513. Please reopen it if I'm wrong.

**Closed by caesarxuchao** 2016-06-09 22:40 UTC
Labels: area/test, kind/flake, team/CSI-API Machinery SIG
