### ISSUE TITLE
BeforeSuite: Error waiting for all pods to be running and ready

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#31561] opened 2016-08-26 23:01 UTC
BeforeSuite fails for many different reasons. This issue is about making the following failure message more helpful (and/or fixing the problem if it's clear what's wrong). There are many examples in #30075. One is here: https://github.com/kubernetes/kubernetes/issues/30075#issuecomment-242580112

Aug 25 16:31:53.455: Error waiting for all pods to be running and ready: Not all pods in namespace 'kube-system' running and ready within 10m0s

**Comment by foxish** [comment] 2016-08-30 22:24
@apelisse Maybe we should refrain from posting a notification when there are no assignees?

**Comment by apelisse** [comment] 2016-08-31 00:45
Good point ...

**Comment by ymqytw** [comment] 2016-09-01 17:23
After digging into the logs, the problem seems to be that a few puller pods cannot complete in 10 minutes. And in most cases, they are caused by gcr is unreachable.

**Comment by ixdy** [comment] 2016-09-06 23:27
Do we know which pods or images are creating issues? 10 minutes seems like it should be plenty of time.

**Comment by ymqytw** [comment] 2016-09-07 16:46
e2e-image-puller-e2e-scalability-minion-group-**** happend 7 times
fluentd-elasticsearch-e2e-scalability-minion-group-****  happend twice
e2e-image-puller-jenkins-e2e-minion-group-**** happened once
heapster-v1.2.0-beta.2-664364718-***** happened once

**Comment by yujuhong** [comment] 2016-11-11 00:59
This issue focuses on the general (none-node specific) e2e framework. Removing the node team label.

**Comment by calebamiles** [comment] 2017-03-13 20:30
This issue has not been updated in 2017. Closing.

**cc: @ethernetdan, @kubernetes/release-team**

**Closed by calebamiles** 2017-03-13 20:30 UTC
Labels: kind/flake, priority/backlog
