### ISSUE TITLE
The following command does not recognize the --output=json flag

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#77683] opened 2019-05-09 17:42 UTC
I ran this command:

```bash
kubectl describe service --output=json
```

and it says 

```console
unknown flag: --output
```

I would expect this command to optionally output json.

@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment] 2019-05-09 23:01
duplicate of https://github.com/kubernetes/kubernetes/issues/25353#issuecomment-422525235

describe does multiple get requests. there is not a single API that encompasses all the information output by describe, and it is not intended to be written to as an API

you can run `kubectl get … -o json` to get the API responses for programmatic use. 

/close

**Closed by liggitt** 2019-05-09 23:01 UTC
Labels: kind/bug, needs-sig
