### ISSUE TITLE
Harden kubelet against TCP connection problems?

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19960] opened 2016-01-21 23:08 UTC
For a few hours yesterday, our test infrastructure was seeing TCP connection failures ~5% of the time.  That seems like a reasonable threshold and shouldn't make all of our tests fall over.  Part of the problem was Kubelet being unable to post node status to the API server (posting to external IP addresses via TCP, so this only affected GKE).

E.g.
- http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-prod/12343/
- http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-staging/4397/
- http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-test/11444/
- http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-test/11445/
- http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10407/

**Comment by dchen1107** [comment] 2016-01-21 23:36
@ihmccreery I poked all above links you posted above, and they have the same cause. I don't think there is a TCP connection issue between node and master. Looks like all master components are not running in all above incidents. Taking https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-test/11444/artifacts/ as an example, one can see that the logs of master components are empty:
```
  146.148.X.X:22-kube-apiserver.log	30 B	inode/x-empty	1 day ago		
 
  146.148.X.X:22-kube-controller-manager.log	30 B	inode/x-empty	1 day ago		
 
  146.148.X.X:22-kube-scheduler.log	30 B	inode/x-empty	1 day ago		
 
  146.148.X.X:22-kubelet.log	30 B	inode/x-empty	1 day ago		
 
  146.148.X.X:22-supervisord.log	30 B	inode/x-empty	1 day ago
```

Looks like this is a specific configuration issue in GKE itself.

**Comment by dchen1107** [comment] 2016-01-21 23:40
I also noticed that on above master node, the kubelet and supervisord are not running at all. Are we sure we are collecting the logs from the right master node?

**Comment by dchen1107** [comment] 2016-01-21 23:51
Ok, here are more information:
1) I re-examine the kubelet logs on slave nodes, and all point to the correct master. 
2) From build-log, I noticed that cluster validation passed, and kubectl cluster-info indicts that master components are running on the right node. 

Looks like we just have some issues on collecting master components' logs from gke master node here. 

Still dig into the issue on why.

**Comment by ihmccreery** [comment] 2016-01-21 23:52
Here's your answer:

```
08:53:57 SSH'ing to all nodes and running cat /var/log/kubelet.log
08:53:57 SSH'ing to all nodes and running cat /var/log/kube-proxy.log
08:53:57 SSH'ing to all nodes and running cat /var/log/supervisor/supervisord.log
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.197.57.138:22-kubelet.log.
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.154.61.18:22-kubelet.log.
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.197.57.138:22-kube-proxy.log.
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.154.61.18:22-kube-proxy.log.
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.197.57.138:22-supervisord.log.
08:53:57 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/104.154.61.18:22-supervisord.log.
08:56:05 Error running command: error getting SSH client to jenkins@104.197.57.138:22: 'dial tcp 104.197.57.138:22: connection timed out'
08:56:05 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/.kube/config
08:56:05 SSH'ing to all nodes and running cat /var/log/kubelet.log
08:56:05 SSH'ing to all nodes and running cat /var/log/kube-apiserver.log
08:56:05 SSH'ing to all nodes and running cat /var/log/kube-scheduler.log
08:56:05 SSH'ing to all nodes and running cat /var/log/kube-controller-manager.log
08:56:05 SSH'ing to all nodes and running cat /var/log/supervisor/supervisord.log
08:56:05 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/146.148.45.228:22-kubelet.log.
08:56:05 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/146.148.45.228:22-kube-apiserver.log.
08:56:05 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/146.148.45.228:22-kube-scheduler.log.
08:56:05 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/146.148.45.228:22-kube-controller-manager.log.
08:56:05 Writing to /var/lib/jenkins/jobs/kubernetes-e2e-gke-test/workspace/_artifacts/146.148.45.228:22-supervisord.log.
08:56:05 Error running command: error getting SSH client to jenkins@146.148.45.228:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain'
08:56:05 Error running command: error getting SSH client to jenkins@146.148.45.228:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'
08:56:05 Error running command: error getting SSH client to jenkins@146.148.45.228:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'
08:56:05 Error running command: error getting SSH client to jenkins@146.148.45.228:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'
08:56:06 Error running command: error getting SSH client to jenkins@146.148.45.228:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'
```

**Comment by alex-mohr** [comment] 2016-01-21 23:54
summary: The master components were running, but there were network issues in terms of connecting to them (e.g. the "dial tcp 104.197.57.138:22: connection timed out" errors).  Because they were ~5% of connections, it's speculated that kubelets could retry more when they can't initially connect to the master?

**Comment by ihmccreery** [comment] 2016-01-22 00:09
The master components were running, we just failed to collect logs from them due to networking issues.

Separately, (though due to the same networking issues,) kubelets were failing to post properly to the master.  @dchen1107 Is there more to do here?  I opened this as an investigative issue; I'll let you decide if it's something that needs pursuing.  If we drop 5% of tcp connections, is that a state Kubelets should be expected to run in?

**Comment by dchen1107** [comment] 2016-01-22 00:15
Sounds like test flakiness and failing collecting the logs have the same cause. @alex-mohr Kubelet already re-try to post status (both node and pod) to API server, not exhaustively, but definitely do it for every sync loop. 

From one of work nodes,  here are some kubelet logs:

```
E0120 15:42:47.288240    3303 kubelet.go:2291] Error updating node status, will retry: error getting node "gke-jkns-gke-e2e-test-4c57a694-node-yrpk": Get https://146.148.45.228/api/v1/nodes/gke-jkns-gke-e2e-test-4c57a694-node-yrpk: dial tcp 146.148.45.228:443: i/o timeout
...
E0120 15:43:27.331222    3303 kubelet.go:2291] Error updating node status, will retry: error getting node "gke-jkns-gke-e2e-test-4c57a694-node-yrpk": Get https://146.148.45.228/api/v1/nodes/gke-jkns-gke-e2e-test-4c57a694-node-yrpk: dial tcp 146.148.45.228:443: i/o timeout
...
E0120 15:45:17.699915    3303 kubelet.go:2291] Error updating node status, will retry: error getting node "gke-jkns-gke-e2e-test-4c57a694-node-yrpk": Get https://146.148.45.228/api/v1/nodes/gke-jkns-gke-e2e-test-4c57a694-node-yrpk: dial tcp 146.148.45.228:443: i/o timeout
...
E0120 15:45:47.700313    3303 kubelet.go:2291] Error updating node status, will retry: error getting node "gke-jkns-gke-e2e-test-4c57a694-node-yrpk": Get https://146.148.45.228/api/v1/nodes/gke-jkns-gke-e2e-test-4c57a694-node-yrpk: dial tcp 146.148.45.228:443: i/o timeout
...
```
From above logs, looks like the real tcp connection failure rate is much higher than 5% here.

**Comment by dchen1107** [comment] 2016-01-22 00:31
@ihmccreery My bad! I misunderstood the purpose of the issue. I thought it is as critical as other flakiness which blocks our merge-bot. 

We should test the cluster, especially Kubelet when dropping 5% of tcp connections. But test might be re-write or re-config with a long timeout value? Also @mfreehan has a pending pr https://github.com/kubernetes/kubernetes/pull/19731 which verifying Kubelet's behavior when network partition occurs.

**Comment by alex-mohr** [comment] 2016-01-22 20:07
I wonder if the issue is the client kubelet uses (which @krousey) is working on, and not kubelet itself?

**Comment by ihmccreery** [comment] 2016-01-22 22:38
> If we drop 5% of tcp connections, is that a state Kubelets should be expected to run in?

This seems to actually be wrong; we saw deterministic 100% loss of 5% of routes, so this is almost certainly a state we don't expect the Kubelet to run in.  Closing.

**Comment by ihmccreery** [comment] 2016-01-26 19:23
Reopening.  We hash based on port (among other things), which perhaps we should be rotating.  Assigning to @krousey for further investigation.

**Comment by krousey** [comment] 2016-01-26 21:10
@ihmccreery We do rotate source ports because the OS chooses a random one for us. Someone else asked this question just yesterday, and I even went so far as to do a 30-minute packet capture to prove it. Did I miss something today that makes us think this is the issue?

**Comment by krousey** [comment] 2016-01-27 22:41
Closing as I have verified that we do indeed cycle through source ports.

**Closed by krousey** 2016-01-27 22:41 UTC
Labels: area/test, team/CSI, team/gke, team/node
