### ISSUE TITLE
Kubelet: Kubelet built with go(<= 1.4) won't work with docker built with go(>=1.6)

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#23809] opened 2016-04-04 07:24 UTC
After #23506, Kubelet built with go(<= 1.4) won't work with docker built with go(>=1.6).

@andyzheng0831 reported that #23506 broke our Jenkins trusty built https://github.com/kubernetes/kubernetes/pull/23506#issuecomment-204757239. Thank @eparis for pointing me to https://github.com/docker/docker/issues/20865.

After some digging, I found out why this happened:

1. After https://github.com/golang/go/commit/6e11f45ebdbc7b0ee1367c80ea0a0c0ec52d6db5, the http server in Go 1.6 will validate the [HTTP Host header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) conforming to HTTP 1.1 (See https://github.com/golang/go/issues/13624)
2. On the http client side, Go writes the HTTP Host header with `request.Host` or `request.URL.Host`(if the former is empty) (See [here](https://github.com/golang/go/blob/a6557a05a03490af3b26f97f9a4ce99c7c773fe5/src/net/http/request.go#L404-L410))
3. When using the [default docker endpoint](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/client_unix.go#L6) (`unix:///var/run/docker.sock`), engine-api will set `request.Host=""`, `request.URL.Host="/var/run/docker.sock"` (See [set request.URL.Host](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/request.go#L85-L87) and [set request.Host](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/request.go#L131))
4. When the engine-api is built with Go >= 1.5, everything goes well, because Go will [clean up the Host](https://github.com/golang/go/blob/master/src/net/http/request.go#L523) making both `request.Host` and `request.URL.Host` to "", the HTTP Host header will be "". (See https://github.com/golang/go/issues/11206))
5. But when the engine-api is built with Go<=1.4, Go [won't clean up the Host](https://github.com/golang/go/blob/release-branch.go1.4/src/net/http/request.go#L368-L373), so the HTTP Host header will be `"/var/run/docker.sock"`. It will break Go 1.6 http server side validation in 1. because `'/'`is not a valid character, causing `400 Bad Request: malformed Host header`.

Go-dockerclient doesn't have this problem, because it is always using a "fake" url for unix endpoint. (See [here](https://github.com/fsouza/go-dockerclient/blob/c47e4f4e477828cb3e226acfff18b9e6c044ebdb/client.go#L400) and [here](https://github.com/fsouza/go-dockerclient/blob/c47e4f4e477828cb3e226acfff18b9e6c044ebdb/client.go#L717-L729).

I've filed an issue to docker engine-api https://github.com/docker/engine-api/issues/189. But **before they fix that, we could not use Kubelet built with go(<=1.4) together with Docker built with go(>=1.6)** unless we revert #23506.

Is this acceptable? @kubernetes/sig-node

**Comment by Random-Liu** [comment] 2016-04-04 07:30
Also ref #23563.

**Comment by errordeveloper** [comment] 2016-04-04 12:00
This is not an issue as of 1.11-rc2 https://github.com/docker/docker/pull/21489

**Comment by eparis** [comment] 2016-04-04 14:25
It doesn't seem like https://github.com/docker/docker/pull/21489 actually 'fixes' anything. This report is explicitly about 1.6 not working and all that does is not us 1.6. At best I would think we would call that a 'work around'.

**Comment by dchen1107** [comment] 2016-04-04 16:31
Let's fix docker/engine-api#189 or at least workaround it. IMO, before the issue is fixed, we should revert #23506.

**Comment by dchen1107** [comment] 2016-04-04 16:41
Chatted with @lavalamp offline, and he pointed me that https://github.com/kubernetes/kubernetes/pull/22149 might be in today. In that case, can we wait for a day or two? @andyzheng0831

**Comment by vishh** [comment] 2016-04-04 16:45
+1 for a revert!

**Comment by Random-Liu** [comment] 2016-04-04 16:49
@dchen1107 I'll send a PR to engine-api to fix this. Before that if go1.4+go1.6 is really important, we could do a revert.

**Comment by andyzheng0831** [comment] 2016-04-04 17:11
@dchen1107  @Random-Liu and all other guys, I really appreciate that you are working on a solution promptly. For @dchen1107 's question, yes we can wait for a couple days for you guys to fix it. As long as #23506 will not be in next release before fixing it, we are totally fine. The only noise is the Jenkins tests result, but we already narrowed the email notification to limited people in our team to avoid bothering a broad range of people very 0.5 hour. Thanks again!

**Comment by Random-Liu** [comment] 2016-04-04 20:30
I've sent a PR #190 to fix this. Hope it could get in.

**Comment by andyzheng0831** [comment] 2016-04-04 20:45
Thanks for making it! When your fix is merged, will it take effect immediately, or we need to wait for some cycles from docker side? If it will take effect immediately in k8s, our jenkins will verify it very quickly

**Comment by Random-Liu** [comment] 2016-04-04 20:50
@andyzheng0831 If that one is merged, on our side after bump uping the engine-api version it should work.

**Comment by andyzheng0831** [comment] 2016-04-06 00:07
@Random-Liu FYI, PR #22149 was just merged which upgrades k8s to golang 1.6. Accordingly, we are not blocked by the breakage due to incompatible docker daemon-client.

**Comment by Random-Liu** [comment] 2016-04-06 02:00
@andyzheng0831 That's great! :) I'll keep this issue open till docker/engine-api#190 get merged.

**Comment by Random-Liu** [comment] 2016-04-21 17:44
docker/engine-api#190 got merged, will close this issue after bumping up the engine-api version.

**Closed** 2016-05-06 10:16 UTC
Labels: component/kubelet, dependency/docker, team/node
