### ISSUE TITLE
fluentd stuck in ContainerCreating after upgrade

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#32844] opened 2016-09-16 04:20 UTC
from @Random-Liu description:

I've tried the update 3 times, and every time I got the pod `fluentd-cloud-logging-kubernetes-master` stuck in `ContainerCreating` state.

In the 1.3 cluster, fluentd-cloud-logging-kubernetes-master is Running.
```
$ curl https://get.k8s.io | bash
$ kubectl get pods --namespace=kube-system
NAME READY STATUS RESTARTS AGE
...
fluentd-cloud-logging-kubernetes-master 1/1 Running 0 1m
fluentd-cloud-logging-kubernetes-minion-group-3ov7 1/1 Running 0 55s
fluentd-cloud-logging-kubernetes-minion-group-pain 1/1 Running 0 51s
fluentd-cloud-logging-kubernetes-minion-group-qf3i 1/1 Running 0 51s
...
```

After updated to 1.4.
```
$ git checkout release-1.4
$ make quick-release
$ cluster/gce/upgrade.sh -M v1.4.0-beta.3
$ kubectl get pods --namespace=kube-system
NAME                                                 READY     STATUS              RESTARTS   AGE
...
fluentd-cloud-logging-kubernetes-master              0/1       ContainerCreating   0          1m
fluentd-cloud-logging-kubernetes-minion-group-3ov7   1/1       Running             0          6m
fluentd-cloud-logging-kubernetes-minion-group-pain   1/1       Running             0          6m
fluentd-cloud-logging-kubernetes-minion-group-qf3i   1/1       Running             0          6m
...
```

This happened everytime I try. In master kubelet.log, I found it full of:
```
Failed to setup network for pod "fluentd-cloud-logging-kubernetes-master_kube-system(d80fb8aa36d238ab5c6990d354d39176)" using n
etwork plugins "kubenet": Error adding container to network: no IP addresses available in network: kubenet; Skipping pod
```

**Comment by piosz** [comment] 2016-09-16 04:23
Looks like a problem with kubelet/networking?

cc @dchen1107 @kubernetes/sig-node @thockin @kubernetes/sig-network @davidopp @gmarek @wojtek-t

**Comment by thockin** [comment] 2016-09-16 04:45
@bprashanth @freehan @dcbw

**Comment by Random-Liu** [comment] 2016-09-16 04:56
It stuck in `ContainerCreating` after upgrade, and recovered after downgrade.

When it stuck, kubelet log is full of:
```
Failed to setup network for pod "fluentd-cloud-logging-kubernetes-master_kube-system(d80fb8aa36d238ab5c6990d354d39176)" using n
etwork plugins "kubenet": Error adding container to network: no IP addresses available in network: kubenet; Skipping pod
```

**Comment by bprashanth** [comment] 2016-09-16 06:02
Hmm, the master will have a pod-cidr of /30, which is just a single usable ip for fluent (0 is the network, .1 is gateway, .2 is usable ip, .3 is broadcast). It sounds like we're dropping that ip in cni. 

Maybe there's a bug in our logic to shave off the broadcast address, that drops the .2 as well?
Any implications of running fluent in hostnetwork like all other master components? 
Maybe we can simply expand the pod cidr allocated to the master to a /29 (as a workaround, of course)? 

If it's an off by one error it should be reproducible in a unittest, maybe it's something dumb. I don't think anything else used that ip (it would need to be a container started through the kubelet to get the ip from kubenet). The others are just backup suggestions.

**Comment by bprashanth** [comment] 2016-09-16 16:48
ok so i just allocated a /29 to the master kubelet and the container took off (just rewrote /etc/defaults/kubelet and service restart). Not sure I'll be able to get to this by midday, I suggest:     
* Someone tests out the dropping ip theory with a unittest to hostlocal ipam in cni (@freehan ?)
* Someone verify that using a /29 does't cause other issues (I don't know if we just chose a /30 because we're stingy or technical reason)

**Comment by bprashanth** [comment] 2016-09-16 16:52
@kubernetes/goog-gke because fluent is responsible for scraping master logs and we'd be blind without it AND ssh

**Comment by piosz** [comment] 2016-09-16 16:53
@bprashanth can I assign you as an owner of this issue?

**Comment by freehan** [comment] 2016-09-16 17:08
Let me check the ipam

**Comment by freehan** [comment] 2016-09-16 17:28
There is a bug in host-local ipam where `/30` subnet does not work properly. @dcbw 

Can we just switch to use `/29`?

**Comment by freehan** [comment] 2016-09-16 18:32
I do not think it matters on master, since there is no network route, no kube-proxy. Just need a cidr to run non-hostnetwork pods.

**Comment by roberthbailey** [comment] 2016-09-17 06:18
We used to [give the master a /24](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L60). When did it switch to a /30?

**Comment by bprashanth** [comment] 2016-09-19 16:57
I'm all for giving the master a /24 but giving it the one /24 we expect the nodecontroller to allocate feels weird, because the nodecontroller could randomize its allocations. Lets continue discussion on https://github.com/kubernetes/kubernetes/issues/32900, we have a stop gap fix so I'm closing this.

**Closed by bprashanth** 2016-09-19 16:57 UTC
Labels: area/logging, component/kubelet, priority/P1, team/cluster

**Comment by JeanMertz** [comment] 2016-10-06 19:47
We're having the same happen on a 1.3.7 cluster, but not for fluentd (or any kube-system pod), but for one of our production pods.

We've removed several other deployments+services, and killed the pod several times, but it just won't come up, while it keeps showing the error:

> Warning   FailedSync  Error syncing pod, skipping: failed to "SetupNetwork" for "xxx" with SetupNetworkError: "Failed to setup network for pod \"xxx(c3db35ac-8bf3-11e6-9697-42010af00027)\" using network plugins \"kubenet\": Error adding container to network: no IP addresses available in network: kubenet; Skipping pod"

This is on GKE (where we obviously don't have access to the master). What's the way forward here to get this pod up and running again (preferably without having to remove the entire deployment, as some of its replicas _are_ running, and it matters that some of them keep running)

**Comment by bprashanth** [comment] 2016-10-06 21:01
do you actually have ip addresses on the node? (available ips in the cbr0 cidr that are not assigned to running pods). Can you check kubelet logs on the node for anything suspicious? if the node has a /24 (kubectl get no -o yaml | grep -i podCIDR), it only has 255 ips. 

you can force the pod to reschedule on another node by marking the node it's on unschedulable (`kubect cordon`),  and kill the pod so it's recreated elsewhere. You probably want to do this anyway if that node is running pods you don't want to delete, and is complaining that there are no available ips for new pods.

**Comment by bprashanth** [comment] 2016-10-06 21:03
Wait, you must have available ips, we don't allow 255 pods on a node. hmm. What's in `/var/lib/cni/networks/kubenet/` on the node? can you correlate with running containers?

**Comment by bprashanth** [comment] 2016-10-06 21:04
And what version of kube/docker are your nodes running?

**Comment by JeanMertz** [comment] 2016-10-06 21:10
@bprashanth 

indeed `/24`

```
$ kubectl get no -o yaml | grep -i podCIDR
    podCIDR: 10.144.4.0/24
    podCIDR: 10.144.6.0/24
    podCIDR: 10.144.5.0/24
    podCIDR: 10.144.7.0/24
```

and indeed, it looks like the range has been depleted:

```
$ ls -lah /var/lib/cni/networks/kubenet/ | wc -l
256
```

Far less containers running:

```
$ docker ps | wc -l
109
```

but, counting stopped containers, it does go above 256:

```
docker ps -a | wc -l
266
```

versions:

```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bprashanth** [comment] 2016-10-06 21:16
Do you have a high deletionGrace timeout? 
We deliver docker stop (sigterm) and wait out termination/deletionGrace before delivering docker kill (sigkill). Containers in the Terminating state will hold onto their ips. can you dig into what those extra containers are doing? 

Each non-hostnetwork pod gets an ip from the cidr, if you have multiple containers per pod, it's still 1 ip. However that `ps -a` number is high enough that I think the stopped containers is probably the issue here.

**Comment by JeanMertz** [comment] 2016-10-06 21:24
All pods use the default `deletionGrace` timeout (on GKE). Still investigating the rest.

**Comment by JeanMertz** [comment] 2016-10-06 21:26
None of the `ps -a` containers are in `Terminating` state, all are `Exited` or running as expected.

**Comment by JeanMertz** [comment] 2016-10-06 21:30
A lot of those stopped containers are part of the pods currently in `ContainerCreating`, due to the fact that it can't get an IP.

**Comment by bprashanth** [comment] 2016-10-06 21:36
Terminating is a kubernetes thing. What does kubectl show as running on that node (kubectl get po -o wide | grep node-name)? 

Just tail -f the kubelet logs and see if it's saying anything suspicious. 
Can you remember what you did, and provide a repro?

**Comment by bprashanth** [comment] 2016-10-06 21:39
I meant `kubectl get po -o wide --show-all --all-namespaces | grep node name`

**Comment by JeanMertz** [comment] 2016-10-06 21:44
kubelet logs shows a continuous stream of:

```
I1006 21:40:38.721424    2938 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/157c45a6-78e2-11e6-9cc2-42010af00027-default-token-hdaai" (spec.Name: "default-token-hdaai") to pod "157c45a6-78e2-11e6-9cc2-42010af00027" (UID: "157c45a6-78e2-11e6-9cc2-42010af00027"). Volume is already mounted to pod, but remount was requested.
```

Which is weird, because `kubectl get pod --all-namespaces --show-all` shows no pods younger than 2 hours, or any pods with an unusual high restart count.

`kubectl get po -o wide --show-all --all-namespaces | grep <node>` shows nothing out of the ordinary.

**Comment by JeanMertz** [comment] 2016-10-06 21:49
I scaled back some replicas and things seem to become normal again:

```
$ docker ps -a | wc -l
147

$ docker ps | wc -l
96

$ ls -lah /var/lib/cni/networks/kubenet/ | wc -l
250
```

No more pods are currently in `ContainerCreating `. The `MountVolume ` log stream continues though. I'm also unsure what caused this in the first place.

**Comment by bprashanth** [comment] 2016-10-06 21:55
The log line you see might be a red herring, if you can upload your kubelet logs somewhere I can take a look.

250 is still really high, but it looks like deleting pods released ips, which is good. The mystery is that you have ~100 pods on the node, where are those remaining ips coming from? One way to tackle this is to grep kubelet logs, I'm not sure if we log the ips to match up to podnames at a V() level that shows up in GKE clusters, worth a shot.

**Comment by JeanMertz** [comment] 2016-10-06 22:02
pods on machine (only one has 2 containers, all others 1):

```
$ kubectl get po -o wide --show-all --all-namespaces | grep gke-blendle-default-v2-default-v135-1cdc1e30-4scf | wc -l
48
```

146 IPs are from late august:

```
ls -lahtr /var/lib/cni/networks/kubenet/ | grep "Aug 2*" | wc -l
146
```

However, the oldest pod on that machine is 30 days old...

**Comment by JeanMertz** [comment] 2016-10-06 22:08
`tail -f /var/log/kubelet.log | grep -v MountVolume` shows nothing out of the ordinary, only some GETs on `/stats/summary`, `/pods/` and `/healthz`, and:

> container_manager_linux.go:614] Found 149 PIDs in root, 149 of them are not to be moved

**Comment by bprashanth** [comment] 2016-10-06 22:14
We might be leaking ips on docker restart. Can you grep docker logs for something suspicious?  like restarting/stopping docker/containerd? your logs might be rotated though. I assume you're running on container vm (cat /etc/lsb-release exists => GCI).

**Comment by JeanMertz** [comment] 2016-10-06 22:23
`/etc/lsb-release` does not exist.

`zcat /var/log/docker.log*.gz` shows the following unique log types:


```
# ~1500 times
time="2016-10-01T06:20:38.470680750Z" level=warning msg="container d2bb8c36423eae2d8be1996120bc9a03fe62136420cbdc565e6dcb7aa775c643 restart canceled" 

# ~900 times
time="2016-10-01T03:26:09.850095620Z" level=warning msg="Your kernel does not support CPU cfs quota. Quota discarded." 
time="2016-10-01T03:26:09.850739382Z" level=warning msg="Your kernel does not support CPU cfs period. Period discarded." 

# ~300 times
time="2016-10-01T06:26:40.691070098Z" level=error msg="Handler for POST /containers/cb033ec9dfe2932e7c09b669531b9f39889d71724908882ae11bfd4993c67242/stop returned error: Container cb033ec9dfe2932e7c09b669531b9f39889d71724908882ae11bfd4993c67242 is already stopped" 

# ~150 times
time="2016-10-04T16:19:29.336413249Z" level=error msg="Handler for GET /containers/97002a17df6122279d1ca8e3efa69f032d9480dd7aec3710cb8901bb39a6e46c/json returned error: No such container: 97002a17df6122279d1ca8e3efa69f032d9480dd7aec3710cb8901bb39a6e46c" 

# ~20 times
2016/10/03 05:12:49 http: response.WriteHeader on hijacked connection
2016/10/03 05:12:49 http: response.Write on hijacked connection

# ~20 times
time="2016-10-03T08:47:30.208998615Z" level=error msg="Error running exec in container: rpc error: code = 2 desc = \"oci runtime error: exec failed: read parent: connection reset by peer\"\n" 
```

And some "no such image" errors of app deployments gone wrong

**Comment by JeanMertz** [comment] 2016-10-06 22:29
I'm trying to find something through GCE logging, but nothing shows up so far:

```
metadata.serviceName="compute.googleapis.com"
metadata.labels."compute.googleapis.com/resource_type"="instance"
metadata.labels."compute.googleapis.com/resource_id"="5393687681430556935"
log="docker"
"start"
NOT textPayload:"container"
```

Maybe you have a better query?

**Comment by bprashanth** [comment] 2016-10-06 22:30
There is a line docker emits when it restarts. Just once is probably enough, so no patterns. I'll look up the line in a bit.

**Comment by bprashanth** [comment] 2016-10-06 22:30
Off the top of my head it would probably be stopping containerd

**Comment by JeanMertz** [comment] 2016-10-06 22:32
0 results for:

```
metadata.serviceName="compute.googleapis.com"
metadata.labels."compute.googleapis.com/resource_type"="instance"
metadata.labels."compute.googleapis.com/resource_id"="5393687681430556935"
log="docker"
"containerd"
```

Scanned up to 2016-09-25 (00:00:00.000)

**Comment by bprashanth** [comment] 2016-10-06 22:47
I think i got a repro on a HEAD cluster https://github.com/kubernetes/kubernetes/issues/34278 (same docker version though), so that's prime suspect. I haven't looked at code yet, so maybe we're actually doing some delayed GC that just hasn't kicked in yet in my test cluster. Someone will comment on that bug if that's the case, and we will have to investigate an alternative theory.

**Comment by JeanMertz** [comment] 2016-10-06 22:51
Nice one!

Given the fact that the ~6 days of docker logs show no Docker restarts (and nothing can be found on GCE logs, although I'm unsure how far back those go), that GC timer would have to be very long for us to experience that issue.
