### ISSUE TITLE
Resource consumer is flaky

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#16425] opened 2015-10-28 12:10 UTC
Instead of consuming 250 milli-cores, recourse consumer consumes nearly 400 milli-cores. This causes flakiness of autoscaling e2e tests: 
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/1521/

**Horizontal pod autoscaling [Skipped][Autoscaling Suite] should scale from 1 pod to 3 pods and from 3 to 5 (scale resource: CPU)**
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:47
Oct 28 03:27:29.523: Number of replicas has changed: expected 3, got 4

Logs from controller-manager:
```
I1028 10:27:25.876466       6 metrics_client.go:135] Sum of cpu requested: {1.500 DecimalSI}
I1028 10:27:25.878913       6 metrics_client.go:172] Metrics available: {
  "items": [
   {
    "metrics": [
     {
      "timestamp": "2015-10-28T10:25:00Z",
      "value": 0
     },
     {
      "timestamp": "2015-10-28T10:24:00Z",
      "value": 180
     }
    ],
    "latestTimestamp": "2015-10-28T10:25:00Z"
   },
   {
    "metrics": [
     {
      "timestamp": "2015-10-28T10:25:00Z",
      "value": 227
     }
    ],
    "latestTimestamp": "2015-10-28T10:25:00Z"
   },
   {
    "metrics": [
     {
      "timestamp": "2015-10-28T10:25:00Z",
      "value": 122
     },
     {
      "timestamp": "2015-10-28T10:24:00Z",
      "value": 80
     }
    ],
    "latestTimestamp": "2015-10-28T10:25:00Z"
   }
  ]
 }
I1028 10:27:25.884889       6 horizontal.go:154] Successfull rescale of rc, old size: 3, new size: 4
```

**Comment by lavalamp** [comment] 2015-11-19 22:48
Happened again: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1759/

Please fix!

**Comment by piosz** [comment] 2015-11-20 20:50
The problem here might not be with Resource Consumer itself but rather with the way how metrics are collected. We are working on improving Heapster and I'm afraid we will not be able to fix the problem before the effort will be finished.

**Comment by piosz** [comment] 2015-11-20 20:55
Also if the problem will happen to often we can disable HPA tests for deployment which should decrease the number of flakes 2x.

**Comment by gmarek** [comment] 2015-11-30 09:23
Bumping a priority, as it's a dupe of a p0 issue.

**Comment by piosz** [comment] 2015-11-30 09:41
@gmarek thanks for dumping the priority, unfortunately as I wrote my feeling is that the problem is with monitoring pipeline rather that with resource consumer itself. I'm afraid we are not able to fix it before we improve Heapster.

**Comment by vishh** [comment] 2015-11-30 18:16
@piosz: What is the issue with the monitoring pipeline?

**Comment by piosz** [comment] 2015-11-30 19:49
IIRC there might be a few races due to big latency of data (~3 minutes). For example:
- we have RC with size 1 and total load 250m and autoscaler target 100m
- autoscaler resizes the RC to 3, so the load should drop down to ~80m
- unfortunately we have no fresh data so autoscaler resizes the RC once again

**Comment by vishh** [comment] 2015-11-30 20:03
Shouldn't the autoscaler's update frequency be greater than the minimum
resolution?

On Mon, Nov 30, 2015 at 11:50 AM, Piotr Szczesniak <notifications@github.com

**Comment by piosz** [comment] 2015-11-30 20:06
@jszczepkowski knows the logic better than me.

**Comment by piosz** [comment] 2015-12-01 12:51
closing as duplicate of #17992

**Closed by piosz** 2015-12-01 12:51 UTC
Labels: area/autoscaling, area/test, priority/P0, team/control-plane
