### ISSUE TITLE
API server recovery actions are destructive

### ISSUE THREAD

**Issue by joshk0** [kubernetes/kubernetes#24200] opened 2016-04-13 15:14 UTC
Hello! On GCE, we ran into [this incident](https://status.cloud.google.com/incident/compute/16007). The observed symptom was that our API servers were unreachable for a time. During that period, all pods kept running on nodes and we were able to serve production traffic no problem. As soon as the API servers returned, that event caused something to decide to kill every pod in our infrastructure. I think this is not an acceptable failure mode. Is this well understood / as designed right now or is there something that can be done?

For example, I would have been satisfied if it had done rolling restarts of every pod, and probably would not have even noticed the issue. But because it restarted every pod all at the same time, we lost some replication guarantees and lost a fair amount of data, the effects of which we're still recovering from right now.

**Comment by lavalamp** [comment] 2016-04-13 21:59
@joshk0 Was your cluster still on 1.1 or had it been upgraded to 1.2 already?

This is probably because the node controller doesn't understand the difference between apiserver being down and all the nodes being down. I think you're not the first to complain. @davidopp to triage. @roberthbailey may be interested also.

**Comment by davidopp** [comment] 2016-04-13 21:59
Hi Josh. Do you have logs from the API server, so we can investigate?

**Comment by davidopp** [comment] 2016-04-13 22:11
cc/ @gmarek

**Comment by lavalamp** [comment] 2016-04-13 22:18
I think this is severe enough when it happens to deserve a P0 rating.

**Comment by davidopp** [comment] 2016-04-13 22:20
Evictions are supposed to be rate limited. @joshk0 do you know over what period of time the pods were killed?

**Comment by roberthbailey** [comment] 2016-04-13 22:57
> This is probably because the node controller doesn't understand the difference between apiserver being down and all the nodes being down.

The node controller talks to the apiserver over a localhost connection, so it would have seen the apiserver being up and running during networking incident. If the apisever was down the node controller wouldn't be able to take any action.

The apiserver would have stopped receiving node status updates, so the node controller should have checked with the GCE API to see if the nodes still existed as they timed out after ~5m. The node controller should only evict pods and delete nodes if the GCE API says that the node no longer exists which should have returned false (assuming that the GCE API was reachable). 

How long does the replication controller wait to replace a pod that has no status with a new one?

**Comment by lavalamp** [comment] 2016-04-13 22:59
> The node controller talks to the apiserver over a localhost connection, so it would have seen the apiserver being up and running during networking incident.

Oh, that explains it, actually. So apiserver would not have gotten any status updates, and five minutes later the node controller would start deleting pods. 13 minutes after that (if the cluster is small enough), when connectivity is restored, the nodes reconnect and find a pending deletion/recreation of everything.

**Comment by lavalamp** [comment] 2016-04-13 23:01
So if we saw the logs of this apiserver, I guess we would see a bunch of deletions that happen *before* the nodes reconnect. The deletions would have been rate limited. Basically node controller doesn't account for the possibility of network segmentation where it and apiserver are together but separated from the rest of the cluster.

**Comment by lavalamp** [comment] 2016-04-13 23:03
The node controller only uses the "does this exist in the API" check to let it skip the rate limiting. It will still eventually delete the pods even if the node exists in the GCE API, just it will rate limit that.

**Comment by roberthbailey** [comment] 2016-04-13 23:04
@joshk0 -- can you send me your project name / zone / cluster (privately if you want) so that I can find the master logs and confirm @lavalamp's guess?

**Comment by davidopp** [comment] 2016-04-13 23:04
> Basically node controller doesn't account for the possibility of network segmentation where it and apiserver are together but separated from the rest of the cluster.

Why do you say that? The node controller rate limits pod evictions. We've been discussing making it work better across a range of cluster sizes (#20979) but it should be rate limiting right now.

**Comment by lavalamp** [comment] 2016-04-13 23:05
@roberthbailey If I understand the OP, @joshk0 is actually running a GCE cluster, not a GKE cluster, so that won't help you :)

**Comment by lavalamp** [comment] 2016-04-13 23:06
@davidopp Yes, the deletions were rate limited, but they were all *observed* at the same time, when the network segmentation ended. Is my hypothesis, anyway.

**Comment by lavalamp** [comment] 2016-04-13 23:06
That is, apiserver saw rate-limited deletions. But the kubelets saw a totally different system state when they rejoined 15 minutes later.

**Comment by davidopp** [comment] 2016-04-13 23:08
I definitely buy the theory that all of the evictions that happened during the disconnection would be observed at the same time; all I am saying is that the rate limiting would not allow to evict an entire cluster in 17 minutes. Regardless, #20979 should address this (and we should increase the priority of that).

**Comment by roberthbailey** [comment] 2016-04-13 23:09
@lavalamp If it was a GCE cluster, then internal connectivity between nodes and the master should have been fine. The outage was related to traffic to/from the external internet.

**Comment by lavalamp** [comment] 2016-04-13 23:13
@roberthbailey good point

@davidopp It looks like the current value is something like one pod every 10 seconds?

**Comment by davidopp** [comment] 2016-04-13 23:18
@lavalamp Ah, you're right, I thought it was longer.

**Comment by gmarek** [comment] 2016-04-14 01:30
@joshk0 - how large is the cluster? Current defaults are quite aggressive to say the least. We have a burst of 10 (so we can kill 10 Nodes straight away), and after that we kill one node every 10 seconds. If the partition time was 15 minutes NC was able to kill 70 Nodes.

**Comment by gmarek** [comment] 2016-04-14 01:32
To verify if rate limiting is working we'd need to get NodeController logs (or NodeController events).

**Comment by jgraettinger** [comment] 2016-04-14 04:24
Hi all, thanks for the quick response! Our project name is `pippio-production`. We operate _GKE_ clusters in both `us-central1-b` and `us-central1-c`, imaginatively called `production-b` and `production-c`. Both clusters had been updated to v1.2 prior to the incident.

Both clusters saw widespread pod deletion & re-creation during the incident window. Running pods appear to have started at exactly the resolution time of [incident 16007](https://status.cloud.google.com/incident/compute/16007) (in `production-b` all have status.startTime of 2016-04-12T02:27:26Z UTC, while `production-c` has 2016-04-12T02:27:40Z). It looks like DaemonSets survived unscathed, but all other pods did not.

**Comment by jgraettinger** [comment] 2016-04-18 14:37
@roberthbailey et al, did the master logs confirm the hypothesis? Thanks

**Comment by roberthbailey** [comment] 2016-04-19 14:30
@jgraettinger -- @gmarek is looking into them.

**Comment by gmarek** [comment] 2016-04-19 15:08
From controller-manager logs: 
- Incident started around 2016-04-12T02:10 when NodeController started noticing that it don't see updates on Node heartbeats. It correctly waited until 02:15 before doing anything
- at 02:15 it started evicting Pods from Nodes giving them grace period as promised
- shortly after ReplicationController started noticing that some RCs lacks a number of replicas and created replacement ones
- around 2:17 NC tried to reach cloud provider but failed; it kept evicting Pods
- after Pod GracePeriod passed NC started to delete Pods from API server
- at 2:27:30 NC was reconnected to Nodes, and all evictions were passed to Kubelets

This means that around 2:27:30 you should be seeing in your Kubelet logs a number of Pod deletion requests, followed by Pod creation requests shortly after.

This is, sadly, working as expected.

**Comment by gmarek** [comment] 2016-04-19 15:11
For DaemonSet I believe @mikedanese should be able to explain why they survived.

**Comment by mikedanese** [comment] 2016-04-19 15:14
Daemonsets are not evictable by the node controller. That's by design.

**Comment by lavalamp** [comment] 2016-04-21 21:08
#24597 is our planned method of ameliorating this in the short term.

**Comment by davidopp** [comment] 2016-05-27 19:59
#25571 fixed the most egregious situation but we need to more work on this in 1.4, so moved to 1.4 milestone

**Comment by dchen1107** [comment] 2016-08-19 17:20
Can someone summarize what we have done for 1.4 release here? #25571 was only mitigating the issue if all nodes not ready, but doesn't fix the partial segmentations. I remembered I saw the prs coming, but nothing is tracked down here. Thanks!

**Comment by davidopp** [comment] 2016-08-19 18:54
Yes, the partial segmentation issue is "fixed" now, by the series of PRs described in issue #28832.

**Comment by goltermann** [comment] 2016-09-06 20:24
Closing, this is now mitigated.

**Closed by goltermann** 2016-09-06 20:24 UTC
Labels: component/nodecontroller, priority/P1, team/control-plane
