### ISSUE TITLE
Endpoints objects fail to affect Service objects that previously had Selectors

### ISSUE THREAD

**Issue by aslanpour** [kubernetes/kubernetes#111929] opened 2022-08-19 10:57 UTC
### What happened?

Hi All,
I am trying to follow the instruction for using [Endpoints ](https://kubernetes.io/docs/concepts/services-networking/service/) objects to ask a Service object to distribute the load between Pods with specific IP addresses instead of any Pod with a matching label/selector. 
However, Endpoints objects seem not to work if the Service object had already defined the Selector parameter, and deleting Selector from the Service object seems to be not affected.
Endpoints objects seem only affect a Service object only if the Service object has never had a Selector. Hence, I have to delete the Service object of my deployment and then recreate a fresh one to be able to get the corresponding Endpoints object working.

### What did you expect to happen?

A Service object needs to know that if Selector is removed, it should get informed that it has to rely on the corresponding Endpoints object only.

### How can we reproduce it (as minimally and precisely as possible)?

**1- Apply a regular Deployment with 2 replicas and Service.**
`kubectl apply -f nginx.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: w6
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
    

**2- Verify the service**
`kubectl get svc`
```
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1       <none>        443/TCP   10d
my-service   ClusterIP   10.43.119.180   <none>        80/TCP    19s
```

**3- Send 2 requests to the service IP and port**
```
curl 10.43.119.180:80
curl 10.43.119.180:80
```

**4- Get pods info**
`kubectl get pods -o wide`
```
NAME                     READY   STATUS    RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES
nginx-7d96cc5bb5-7wm25   1/1     Running   0          61s   10.42.5.89   w6     <none>           <none>
nginx-7d96cc5bb5-hkzqz   1/1     Running   0          61s   10.42.5.90   w6     <none>           <none>
```

**5- Verify served requests by each Pod**
`kubectl logs pod/nginx-7d96cc5bb5-7wm25`
```
10.42.0.0 - - [19/Aug/2022:09:57:17 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
kubectl logs pod/nginx-7d96cc5bb5-hkzqz
10.42.0.0 - - [19/Aug/2022:09:57:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

**6-Both replicas are receiving requests.**
**7- Let's get current details of Service and Endpoint objects**
`kubectl describe svc/my-service`
```
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=nginx
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.119.180
IPs:               10.43.119.180
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.42.5.89:80,10.42.5.90:80
Session Affinity:  None
Events:            <none>

kubectl get endpoints
NAME         ENDPOINTS                     AGE
kubernetes   10.0.0.90:6443                10d
my-service   10.42.5.89:80,10.42.5.90:80   3m14s
```
**8- Get endpointslice**
`kubectl get endpointslice`
```NAME               ADDRESS TYPE   PORTS   ENDPOINTS                 AGE
kubernetes         IPv4          6443    10.0.0.90                 38d
my-service-hslp7   IPv4          80      10.42.5.89,10.42.5.90   2m16s
```

**9-Describe endpoints**
`k describe endpoints/my-service'
```
Name:         my-service
Namespace:    default
Labels:       <none>
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2022-09-17T04:40:48Z
Subsets:
  Addresses:          10.42.5.89,10.42.5.90
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  80    TCP

Events:  <none>
```

**10- Describe endpointslices**
`k describe endpointslice/my-service-hslp7`
```
Name:         my-service-hslp7
Namespace:    default
Labels:       endpointslice.kubernetes.io/managed-by=endpointslice-controller.k8s.io
              kubernetes.io/service-name=my-service
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2022-09-17T04:40:48Z
AddressType:  IPv4
Ports:
  Name     Port  Protocol
  ----     ----  --------
  <unset>  80    TCP
Endpoints:
  - Addresses:  10.42.5.89
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/nginx-7d96cc5bb5-9l8sw
    NodeName:   w6
    Zone:       <unset>
  - Addresses:  10.42.5.90
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/nginx-7d96cc5bb5-kwh96
    NodeName:   w6
    Zone:       <unset>
Events:         <none>
```

**11- Now, I am going to edit the Service object and delete the Selector part**

service.yaml file contains the following:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

`kubectl apply -f service.yaml `
`service/my-service configured`

**12- New look of the Service object.**
`kubectl describe svc/my-service`
```
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.119.180
IPs:               10.43.119.180
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.42.5.89:80,10.42.5.90:80
Session Affinity:  None
Events:            <none>
```

**13- And also the Endpoints object remains unchanged.**
`kubectl get endpoints`
```
NAME         ENDPOINTS                     AGE
kubernetes   10.0.0.90:6443                10d
my-service   10.42.5.89:80,10.42.5.90:80   4m6s

```

**14-But look at endpointslice**
`k get endpointslice`

```
NAME               ADDRESSTYPE   PORTS   ENDPOINTS                 AGE
kubernetes         IPv4          6443    10.0.0.90                 38d
my-service-hslp7   IPv4          80      10.42.5.89,10.42.5.90   5m7s
my-service-fvwcj   IPv4          80      10.42.5.89,10.42.5.90   51s
```

**15- And new endpointslice**
`k describe endpointslice/my-service-fvwcj`

```
Name:         my-service-fvwcj
Namespace:    default
Labels:       endpointslice.kubernetes.io/managed-by=endpointslicemirroring-controller.k8s.io
              kubernetes.io/service-name=my-service
Annotations:  <none>
AddressType:  IPv4
Ports:
  Name     Port  Protocol
  ----     ----  --------
  <unset>  80    TCP
Endpoints:
  - Addresses:  10.42.5.89
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/nginx-7d96cc5bb5-kwh96
    NodeName:   w6
    Zone:       <unset>
  - Addresses:  10.42.5.90
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/nginx-7d96cc5bb5-9l8sw
    NodeName:   w6
    Zone:       <unset>
Events:         <none>
```

**16- Again, I send 2 requests to the Service IP and Port to see the behaviour**
```
curl 10.43.119.180:80
curl 10.43.119.180:80
```

**17- I verify Pods logs.**
`kubectl logs pod/nginx-7d96cc5bb5-hkzqz`
```
10.42.0.0 - - [19/Aug/2022:09:57:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:01:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

`kubectl logs pod/nginx-7d96cc5bb5-7wm25`
```
10.42.0.0 - - [19/Aug/2022:09:57:17 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:01:11 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

**18- Pods received one request each which is fine. Because, I can see despite removing the Selector from the Service, it is still inheriting the previously registered Endpoints.**

**19- Now I apply my custom Endpoints objects which contains**
```
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
- addresses:
  - ip: 10.42.5.89
  ports:
  - port: 80
```
  
`k apply -f endpoints.yaml `
```
Warning: resource endpoints/my-service is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
endpoints/my-service configured
```

**20- The Endpoints object is designed to register only one of the Pods in the Endpoints list of the Service.**
`kubectl get endpoints`
```
NAME         ENDPOINTS        AGE
kubernetes   10.0.0.90:6443   10d
my-service   10.42.5.89:80    7m24s
```

**21- Let's verify if Service noticed this change.**
`kubectl describe svc/my-service`
```
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.119.180
IPs:               10.43.119.180
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.42.5.89:80
Session Affinity:  None
Events:            <none>
```

**22- Yes, it now has only the 10.42.5.89:80 in the Endpoints list.**

**23- Here is the issue. I am going to send 6 requests to the Service IP and am expecting that only one Pod: `10.43.119.180:80` receives the requests.**
```
curl 10.43.119.180:80
curl 10.43.119.180:80
curl 10.43.119.180:80
curl 10.43.119.180:80
curl 10.43.119.180:80
curl 10.43.119.180:80
```

**24- However, the Pods logs shows that requests are still delivered to both Pods, even the excluded Pod is receiving more of them. The registered Pod received 1 out of 6 (+ 2 previous ones) and the excluded Pod received 5 out of 6 (+ 2 previous ones). The uneven distribution is expected, but the point is that the excluded Pod is meant to not receive any request. Please correct me if I am wrong.**

`kubectl logs pod/nginx-7d96cc5bb5-7wm25`
```
10.42.0.0 - - [19/Aug/2022:09:57:17 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:01:11 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

Here is the excluded Pod:
`kubectl logs pod/nginx-7d96cc5bb5-hkzqz`
```
10.42.0.0 - - [19/Aug/2022:09:57:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:01:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:16 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:17 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:18 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:19 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
10.42.0.0 - - [19/Aug/2022:10:04:20 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
```

### Anything else we need to know?

If I completely delete the Service object and create a fresh one without Selector, then my Endpoints object will work as expected.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
**MASTER NODE:**
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a

**WORKER NODE**
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

</details>


### Install tools

<details>
curl -sfL https://get.k3s.io | sh -
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment] 2022-08-19 11:02
are you using kube-proxy?

since 1.22, kube-proxy uses endpointslices and not endpoints, you should do the same exercise you did, but checking the endpointslices generated in each case

**Comment by aslanpour** [comment] 2022-08-22 02:27
I am not using kube-proxy.
I checked the endpointslice objects. Once I create a deployment an EndpointSlice object is created for that. 
Once I delete the Selector parameter from my Service object, a new EndpointSlice is created, again referring to the Service. Hence, now I will have 2 EndpointSlice objects directing the load balancing for my Service. If I delete an IP address of a Pod from my Endpoint object, it is only getting deleted from the new EndpointSlice object and the old object is still keeping this IP address. I think when I make a Service object headless on the fly, its corresponding EndpointSlice requires updating itself, instead of being left unattended and creating a new EndpointSlice object. Does that make sense?

**Comment by aojea** [comment] 2022-08-22 07:11
I see, this is a duplicate of https://github.com/kubernetes/kubernetes/issues/103576

**Comment by neolit123** [comment] 2022-08-22 11:13
/sig network
close if needed pls

**Comment by aojea** [comment] 2022-09-01 17:15
> I see, this is a duplicate of #103576

@aslanpour do you mind paste those endpointslices objects? please paste the result of the `describe` command

is it possible that one endpointslice is the "orphaned" one from the endpointslice controller (the one generated for the service with selector) and the other one is the one generated by the endpointslicemirroring controller?

**Comment by bridgetkromhout** [comment] 2022-09-15 16:17
@aslanpour can you please provide the requested details? thanks!

**Comment by aslanpour** [comment] 2022-09-17 05:07
Sorry for the late action. I added the endpointslice descriptions in the above issue details.

**Comment by robscott** [comment] 2022-09-29 16:26
Hey @aslanpour, thanks for adding all the details here! I agree this is confusing, and unfortunately this appears to be a duplicate of https://github.com/kubernetes/kubernetes/issues/103576 as @aojea suggested. Based on your output above, I believe whatever you're using in place of kube-proxy is also using EndpointSlices. It looks like you're updating Endpoints, but not EndpointSlices after you remove the selector from the Service. That explains why requests would still be going to both Pods.

As mentioned in [this comment on the older bug](https://github.com/kubernetes/kubernetes/issues/103576#issuecomment-876890462), the Endpoints controller did not delete or empty Endpoints resources when the Service selector transitions to empty. To maintain backwards compatibility, EndpointSlice controller also doesn't clean up resources. At this point, although I agree this behavior is not ideal, it seems likely that there are people relying on this behavior and a change would be breaking.

**Comment by dcbw** [comment] 2022-10-13 15:47
@robscott given this is likely a dupe, should we close?

**Comment by thockin** [comment] 2022-10-13 16:01
ping?

**Comment by robscott** [comment] 2022-10-13 16:04
Yeah I don't think we can safely change anything here, closing this out.

/close

**Closed by robscott** 2022-10-13 16:04 UTC
Labels: kind/bug, sig/network, needs-triage
