### ISSUE TITLE
pull-kubernetes-bazel-test is flaky due to fail image pulling

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#59432] opened 2018-02-06 19:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59335/pull-kubernetes-bazel-test/29571/

```
NFO: Found 0 targets...
W0206 19:00:02.726] [0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
W0206 19:00:03.320] INFO: Elapsed time: 5.214s, Critical Path: 0.57s
W0206 19:00:03.322] INFO: Build completed successfully, 1 total action
W0206 19:00:03.329] Run: ('bazel', 'query', '--keep_going', '--noshow_progress', "kind(test, rdeps(//... -//build/... -//vendor/..., //...)) except attr('tags', 'manual', //...)")
W0206 19:00:03.341] INFO: $TEST_TMPDIR defined: output root default is '/root/.cache/bazel' and max_idle_secs default is '15'.
W0206 19:00:28.166] ERROR: /workspace/k8s.io/kubernetes/cluster/images/hyperkube/BUILD:3:1: no such package '@debian-hyperkube-base-amd64//image': Pull command failed: Traceback (most recent call last):
W0206 19:00:28.167]   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
W0206 19:00:28.167]     "__main__", fname, loader, pkg_name)
W0206 19:00:28.168]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
W0206 19:00:28.168]     exec code in run_globals
W0206 19:00:28.169]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/__main__.py", line 93, in <module>
W0206 19:00:28.170]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/__main__.py", line 82, in main
... skipping 4 lines ...
W0206 19:00:28.174]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/containerregistry/client/v2_2/save_.py", line 163, in <lambda>
W0206 19:00:28.174]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 266, in config_file
W0206 19:00:28.175]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 290, in blob
W0206 19:00:28.176]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 210, in _content
W0206 19:00:28.176]   File "/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 363, in Request
W0206 19:00:28.178] containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '403', 'content-length': '210', 'expires': 'Tue, 06 Feb 2018 19:00:15 GMT', 'server': 'UploadServer', 'cache-control': 'private, max-age=0', 'date': 'Tue, 06 Feb 2018 19:00:15 GMT', 'content-type': 'application/xml; charset=UTF-8', 'x-guploader-uploadid': 'AEnB2Uptju7SyGHKVNi6tY4s5R0bNzgqdH0sqmTV5YVC9MfhqXhK1-CwmL_irg0BsC2xFmz2A6Y9AFOiok2R0GtiyXaTnwawTQ'}
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment] 2018-02-06 19:27
duplicate of https://github.com/kubernetes/kubernetes/issues/59430

**Closed by liggitt** 2018-02-06 19:27 UTC
Labels: area/test-infra, kind/bug, sig/testing
