### ISSUE TITLE
Kubernetes services cause a huge delay

### ISSUE THREAD

**Issue by bengong2015** [kubernetes/kubernetes#10010] opened 2015-06-18 07:59 UTC
I set up a cluster by using kubernetes+docker+flannel+Haproxy, and test the network status by ApacheBench. (Kubernetes version v0.15.0, I set 'PublicIPs' in service in order to assigned ip:port for pods on each node)
The network design below:
Internet->Haproxy->kube-proxy(service)->flannel->docker bridge->containers
I tried the connection, it pass.
Then I run the test: (202.120.11.50 is master with Haproxy inside, the backends are 202.120.11.53:10000,202.120.11.54:10000,202.120.11.55:10000)
1) each minions has 2 pods, totally 6 pods
#ab -c 10 -n 100 202.120.11.50:10000/
...
Server Software:    WildFly/8
...
Concurrency Level:    10
Time taken for tests:  166.030 seconds
Complete requests:    100
Failed requests:          22
     (Connect: 0, Receive: 0, Length: 22, Exception: 0)   (the failed requests might caused by time out)
...
Time per request:       16603.049 [ms] (mean)
Time per request:       1660.305 [ms] (mean, across all concurrent requests)
Transfer rate:              1.20 [Kbytes/sec] received
...

2) each minions has 1 pod, totally 3 pods
#ab -c 10 -n 100 202.120.11.50:10000/
...
Server Software:    WildFly/8
...
Concurrency Level:    10
Time taken for tests:  100.050 seconds
Complete requests:    100
Failed requests:          0
...
Time per request:       10004.989 [ms] (mean)
Time per request:       1000.499 [ms] (mean, across all concurrent requests)
Transfer rate:              2.56 [Kbytes/sec] received
...

3) running pods by 'Host' network mode (assigned 'hostPort' for containers in creating ReplicationController), in this case, each minion can only has 1 pod.
Therefore, the network design has been changed:
Internet->Haproxy->docker bridge->container
#ab -c 10 -n 100 202.120.11.50:10000/
...
Server Software:    WildFly/8
...
Concurrency Level:    10
Time taken for tests:  0.077 seconds
Complete requests:    100
Failed requests:          0
...
Time per request:       7.650[ms] (mean)
Time per request:       0.765[ms] (mean, across all concurrent requests)
Transfer rate:              3348.31 [Kbytes/sec] received
...

Um...It shows the kubernetes service cause a really huge delay. I read the Services FAQ and already run docker daemon with '--iptables=false --ip-masq=false'. But, obviously it doesn't work.
Currently I used 'Host' mode, however, it restrict the num of replicas must less than the num of physical network cards. If I want to deploy more replicas for a container on a minion, the virtual subnet (like flannel or OpenVSwitch) is needed. 
Any idea?

**Comment by thockin** [comment] 2015-06-18 17:39
Do you have a reproducible test?  I have not run benchmarks lately, but
when I ran tests a few months ago the slowdown was almost entirely due to
the veth subsystem.  kube-proxy has a long-tail latency, but we have plans
for that for after 1.0

**Comment by bengong2015** [comment] 2015-07-15 02:23
@thockin Is the long-tail latency problem solved in the latest version 1.0.0? I didn't find any distribution in services.md or releases.md. Thanks.

**Comment by thockin** [comment] 2015-07-15 03:50
no, the long tail should be fixed by moving away from userspace proxying
entirely and that will land probably in 1.1

**Comment by MikaelCluseau** [comment] 2015-07-20 05:42
FWIW, one can `git cherry-pick 82ee237 753d2a0` to build an iptables-enabled proxy. Be aware that you need the `br_netfilter` module loaded if you run linux 3.18+. I did this on the release-1.0 branch, it works with ~150 services and ~200 pods giving less than 2ms response times.

**Closed** 2015-09-02 04:03 UTC
Labels: priority/P2, team/cluster
