### ISSUE TITLE
Potential bug of PodTopologySpread when nodeAffinity is specified

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#106971] opened 2021-12-10 22:24 UTC
We know that nodeAffinity/nodeSelector is honored during the calculating of PodTopolgySpread, however, when some existing pods match the incoming pod's topologySpreadConstratints, while also excluded by the nodeAfffinity, things get a bit tricky. Raising this issue to discuss if we should read it as a bug.

Here are the repro steps:

1. Suppose you have a 3-node cluster, worker1 and worker2 belong to zoneA, and worker3 belongs to zoneB:
    ```
    kind-worker          Ready    kubernetes.io/hostname=kind-worker,zone=zoneA
    kind-worker2         Ready    kubernetes.io/hostname=kind-worker2,zone=zoneA
    kind-worker3         Ready    kubernetes.io/hostname=kind-worker3,zone=zoneB
    ```
2. And make a deployment with 3 replicas. Suppose 2 land on worker2, and 1 land on worker.
    ```
    pause-58dffb5c6b-4kb5z   1/1     Running   kind-worker2
    pause-58dffb5c6b-d4nzr   1/1     Running   kind-worker2
    pause-58dffb5c6b-jpv9t   1/1     Running   kind-worker3
    ```
3. Create a new deployment with topologySpreadConstraints as well as nodeAffinity (not schedule to worker2):
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pause
      template:
        metadata:
          labels:
            app: pause
        spec:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: pause
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values: ["kind-worker2"]
          containers:
          - name: pause
            image: k8s.gcr.io/pause:3.6
    ```
4. The test pod will land on **worker3**.
    ```
    pause-58dffb5c6b-4kb5z   1/1     Running   kind-worker2
    pause-58dffb5c6b-d4nzr   1/1     Running   kind-worker2
    pause-58dffb5c6b-jpv9t   1/1     Running   kind-worker3
    test-7f87db4875-7gqxh    1/1     Running   kind-worker3
    ```

This behavior concerns me: it looks like the 2 pods on worker2 are taken into consideration, even though worker2 is excluded by nodeAffinity, so the pods on zoneA/zoneB distribute as **2:2**. However, shouldn't we disregard the matching pods that are excluded by nodeAffinity? In that case, the test pod should land on **worker1** to reach a pods distribution as **1:1**.

Please share your thoughts.

/sig scheduling
/kind bug

**Comment by Huang-Wei** [comment] 2021-12-10 22:25
cc/ @alculquicondor @ahg-g @kerthcet

**Comment by ahg-g** [comment] 2021-12-12 23:34
> This behavior concerns me: it looks like the 2 pods on worker2 are taken into consideration,

That is not issue, the problem is similar to what https://github.com/kubernetes/kubernetes/issues/105291 describes. What happened is that zoneA is now not "visible" at all, and so it is as if we have a single zone. The `minDomain` solution should apply to both cases.

**Comment by kerthcet** [comment] 2021-12-13 06:08
I think we should consider it as a bug.

|  node   | kind-worker  |   kind-worker2  |  kind-worker3  |   kind-worker4  |
|  ----  | ----  |  ----  |  ----  |  ----  |
| zone  | zone1 | zone1 | zone2 | zone2 |
| existingPods  | pod1 | pod2 | pod3, pod4 | pod5 |
| nodeStatus  | resourceExhausted | resourceExhausted | normal | normal |

Imagine in this situation, all of these pods are labeled with `app: pause`, then we want to apply a deployment.yaml like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pause
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values: ["kind-worker3"]
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.6
```
`kind-worker3` is excluded in scheduling. But when we try to calculate the skew, we will still calculate the pods in `kind-worker3`. Since `{zone: zone1}` : `{zone: zone2}` is `2:3`, then we will schedule the new pod to `kind-worker` or `kind-worker1`, but since they are resource exhausted, then it will be in pending state.

But if we filtered out the `kind-worker3`, the pod will be scheduled to `kind-worker4` successfully. I think it's the right algorithm.

**Comment by Huang-Wei** [comment] 2021-12-13 19:53
@ahg-g it's not the same as #105291, even if worker2 becomes invisible, there are still 2 zones:

```
kind-worker          Ready    kubernetes.io/hostname=kind-worker,zone=zoneA
kind-worker2         Ready    kubernetes.io/hostname=kind-worker2,zone=zoneA
kind-worker3         Ready    kubernetes.io/hostname=kind-worker3,zone=zoneB
```

**Comment by ahg-g** [comment] 2021-12-13 20:06
ah,  I didn't notice `kind-worker` existed.

What part of the code is causing this behavior? I would have assumed that the spreading would happen between `kind-worker` and `kind-worker`.

The following code shows that we should be skipping counting the pods on worker2
https://github.com/kubernetes/kubernetes/blob/e53f93c7bb9fe28e5de2799da8eb1c62bdd4f4f1/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L237

**Comment by Huang-Wei** [comment] 2021-12-13 20:10
@ahg-g it's the `allNodes` that is passed to processNode():

https://github.com/kubernetes/kubernetes/blob/e53f93c7bb9fe28e5de2799da8eb1c62bdd4f4f1/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L263

@kerthcet included the fix in #106623, and that bits should be extracted out to be a standalone PR, if we get to a consensus on this issue is a bug.

**Comment by ahg-g** [comment] 2021-12-13 20:18
I still don't get where the bug is. I think iterating over all node is the right way and the line I pointed to above should filter out the nodes that don't match the affinity.

Passing a filteredList (as in exclude nodes that were filtered by previous filters) is certainly not the right solution because we need to count pods on all nodes. Let alone the filteredlist is different based on how we order the filters, which should never be a factor in the semantics of the PodTopologySpread.

**Comment by Huang-Wei** [comment] 2021-12-13 20:43
The bug lies in the preFilterState's calculation. For the above case, it's expected to be `{zoneA: 0, zoneB: 1}`, but it ended up with `{zoneA: 2, zoneB: 1}`.

> Passing a filteredList

The code I posted above is in PodTopologySpread's PreFitler, not Filter.

**Comment by ahg-g** [comment] 2021-12-13 20:56
ok, this is indeed a bug, we need to check the node affinity constraints again inside the second loop.

**Comment by ahg-g** [comment] 2021-12-13 20:59
actually, doesn't seem efficient that we have two loops in the first place

**Comment by ahg-g** [comment] 2021-12-13 21:03
It seems we are doing it right in the score function, excluding those nodes: https://github.com/kubernetes/kubernetes/blob/2ae44bd74a64da2c4061f7675cb1e6cb20bbd5b3/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L153

**Comment by Huang-Wei** [comment] 2021-12-13 21:03
> actually, doesn't seem efficient that we have two loops in the first place

Feel the same. Let's fix the correctness issue first, and then improve the efficiency.

**Comment by alculquicondor** [comment] 2021-12-13 22:04
Do we know of a use case where this would be useful? It's kind of odd that there are matching pods in a node where we don't intend to schedule. Maybe during some sort of migration?

**Comment by Huang-Wei** [comment] 2021-12-13 23:57
It's about clarifying/correcting the semantics of constraints (nodeAffinity, and the to-be-added ones like Unschedulable taint) embedded in PodTopologySpread. So IMO we should fix the correctness issue, no matter there is a use case or not.

**Comment by alculquicondor** [comment] 2021-12-14 14:36
One thing to be aware of is whether a potential fix could render some pods unschedulable, thus be a breaking change. And that's where use cases weigh in.

**Closed** 2022-01-11 16:33 UTC
Labels: kind/bug, sig/scheduling, needs-triage
