### ISSUE TITLE
make test-cmd fails removing deployment

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#39666] opened 2017-01-10 11:39 UTC
`kubectl delete deployment nginx` times-out [here](https://github.com/kubernetes/kubernetes/blob/e827393fa2335cc7ed89043e7f26ef9b32fc71a9/hack/make-rules/test-cmd-util.sh#L2039) due to previous operations that happen to this deployment. This in turn causes further failures in the test-cmd code, due to previously existing pods from that test. 

I've initially tried forcing the removal, but it doesn't work b/c the pods are still left. I've spoke with @kargakis about it, he claims it might be due to recent changes to deployment reaping code. This is blocking #39614. 

@kubernetes/sig-apps-misc fyi

**Comment by kargakis** [comment] 2017-01-12 16:14
I will try to look into this tomorrow.

**Comment by kargakis** [comment] 2017-01-12 17:40
Latest test run from https://github.com/kubernetes/kubernetes/pull/39614 and this seems to be working as expected:
```
W0112 08:54:28.642] I0112 08:54:28.641695   14530 deployment_controller.go:499] Deployment has been deleted default/nginx2
W0112 08:54:28.924] I0112 08:54:28.923768   14530 event.go:217] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"nginx", UID:"c34b4345-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1445", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set nginx-503054122 to 0
W0112 08:54:28.929] I0112 08:54:28.928662   14530 event.go:217] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"nginx", UID:"c34b4345-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1445", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set nginx-617086214 to 0
W0112 08:54:28.941] I0112 08:54:28.940836   14530 event.go:217] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"nginx-503054122", UID:"c34c8a09-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1447", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: nginx-503054122-0pq78
W0112 08:54:28.950] I0112 08:54:28.950050   14530 event.go:217] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"nginx-503054122", UID:"c34c8a09-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1447", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: nginx-503054122-40l3h
W0112 08:54:28.952] I0112 08:54:28.952112   14530 event.go:217] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"nginx-617086214", UID:"c3d8cd22-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1448", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: nginx-617086214-rg7dx
W0112 08:54:28.953] I0112 08:54:28.952851   14530 event.go:217] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"nginx-617086214", UID:"c3d8cd22-d8e7-11e6-a69c-0242ac110002", APIVersion:"extensions", ResourceVersion:"1448", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: nginx-617086214-sk5hr
W0112 08:54:33.364] I0112 08:54:33.363560   23180 kubelet.go:1723] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]]
W0112 08:54:33.978] I0112 08:54:33.977902   14530 deployment_controller.go:499] Deployment has been deleted default/nginx
```
I am lowering the priority on this until it turns out I shouldn't.

**Comment by soltysh** [comment] 2017-01-20 13:04
I'm still seeing the problem, running master, back to P1 and I'm currently looking into it.

**Comment by kargakis** [comment] 2017-01-20 13:15
@soltysh can you paste a log of your controller manager when you hit this? Also grab any related events. And make sure there is at least a failed test run in Jenkins so we can have a look there too.

**Comment by soltysh** [comment] 2017-01-20 13:24
@kargakis will keep you informed

**Comment by soltysh** [comment] 2017-01-20 14:15
@kargakis this is the script that is failing for me every single time:
```
#!/bin/bash

set -x
set -e

id_field=".metadata.name"
deployment_image_field="(index .spec.template.spec.containers 0).image"

kubectl create -f /data/src/k8s.io/kubernetes/hack/testdata/deployment-revision1.yaml

# Rollback to revision 1 - should be no-op
kubectl rollout undo deployment nginx --to-revision=1
kubectl get deployment -o go-template="{{range.items}}{{$deployment_image_field}}:{{end}}"

# Update the deployment (revision 2)
kubectl apply -f /data/src/k8s.io/kubernetes/hack/testdata/deployment-revision2.yaml
kubectl get deployment -o go-template="{{range.items}}{{$deployment_image_field}}:{{end}}"

# Rollback to revision 1
kubectl rollout undo deployment nginx --to-revision=1
sleep 1
kubectl get deployment -o go-template="{{range.items}}{{$deployment_image_field}}:{{end}}"

# Rollback to last revision
kubectl rollout undo deployment nginx
sleep 1
kubectl get deployment -o go-template="{{range.items}}{{$deployment_image_field}}:{{end}}"

kubectl rollout undo deployment nginx
# Check that the new replica set has all old revisions stored in an annotation
newrs="$(kubectl describe deployment nginx | grep NewReplicaSet | awk '{print $2}')"
kubectl get rs "${newrs}" -o yaml | grep "deployment.kubernetes.io/revision-history: 1,3"

cat /data/src/k8s.io/kubernetes/hack/testdata/deployment-revision1.yaml | sed "s/name: nginx$/name: nginx2/" | kubectl create -f -
# Newest deployment should be marked as overlapping
kubectl get deployment nginx2 -o yaml | grep "deployment.kubernetes.io/error-selector-overlapping-with"
# Deletion of both deployments should not be blocked
kubectl delete deployment nginx2
# Clean up
kubectl delete deployment nginx --v=8
```
That last delete will hit timeout.

**Comment by kargakis** [comment] 2017-01-20 14:23
Last time I checked I couldn't reproduce it and I haven't seen it fail in Jenkins either. Building latest master and testing this shortly.

**Comment by kargakis** [comment] 2017-01-20 14:45
Can't repro with the script @soltysh provided
```
$ kc version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3604+4f8f6006cf17a3", GitCommit:"4f8f6006cf17a3189fbd51a83fe3864d247d6796", GitTreeState:"clean", BuildDate:"2017-01-20T14:21:25Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3604+4f8f6006cf17a3", GitCommit:"4f8f6006cf17a3189fbd51a83fe3864d247d6796", GitTreeState:"clean", BuildDate:"2017-01-20T14:21:25Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```
script log: http://pastebin.com/hWMkaqyK
server log: http://pastebin.com/ShTA21ng

**Comment by kargakis** [comment] 2017-01-30 11:30
@soltysh this doesn't seem like an issue in master - mind closing?

**Comment by soltysh** [comment] 2017-01-30 13:10
It is master, I'm hitting this every time I try, besides from the dupe it looks like @liggitt has exactly the same problem.

**Comment by kargakis** [comment] 2017-01-30 13:12
Can you guys sync about what you hit in the controller manager? Yours was a
storage error if I am not mistaken.

**Comment by kargakis** [comment] 2017-02-08 18:36
I saw the storage error today in some test, a lot was going on during that time and it got lost.

**Comment by kargakis** [comment] 2017-02-24 18:05
@soltysh if you are able to reproduce the storage error, mind sticking a panic that expects it and post the resulting stack trace here?

**Comment by kargakis** [comment] 2017-02-24 18:18
Make sure you update etcd
https://github.com/kubernetes/kubernetes/issues/41760#issuecomment-282362467

Closing since it's not an issue

**Closed by kargakis** 2017-02-24 18:18 UTC
Labels: area/test, kind/bug, priority/P1, sig/apps, sig/testing

**Comment by soltysh** [comment] 2017-02-27 14:53
Updating etcd fixed the problem in my case as well. Similarly to Derek I was running 3.0.4 before.
