### ISSUE TITLE
hack/local-up-cluster.sh broken on latest 1.5 branch

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#38847] opened 2016-12-16 00:15 UTC
local cluster failed to start in the latest 1.5 branch (commit 09cb1a9df8455c87c4e0f204e0f4e05284e7cf28):

```console
$ hack/local-up-cluster.sh                                                                                                                                  
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
make[1]: Entering directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
+++ [1215 15:40:40] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:40:40] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:40:44] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [1215 15:40:52] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:40:52] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:40:55] Building go targets for linux/amd64:
    cmd/libs/go2idl/defaulter-gen
+++ [1215 15:41:02] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:02] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:06] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
+++ [1215 15:41:14] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:14] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:17] Building go targets for linux/amd64:
    cmd/libs/go2idl/openapi-gen
make[1]: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
+++ [1215 15:41:26] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1215 15:41:26] Generating bindata:
    test/e2e/framework/gobindata_util.go
+++ [1215 15:41:29] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
make: Leaving directory `/usr/local/google/home//go/src/k8s.io/kubernetes'
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Detected host and ready to start services.  Doing some housekeeping first...
Using GO_OUT /usr/local/google/home//go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64
Starting services now!
Starting etcd
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.XV5AbQKB0n --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
+++ [1215 15:42:46] On try 2, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
Waiting for apiserver to come up
!!! [1215 15:42:56] Timed out waiting for apiserver:  to answer at https://localhost:6443/version; tried 10 waiting 1 between each
Cleaning up...
```

**Comment by janetkuo** [comment] 2016-12-16 00:33
It worked in v1.5.0 (58b7c16a52c03e4a849874602be42ee71afdcab1) but is broken in v1.5.1 (82450d03cb057bab0950214ef122b67c83fb11df)

**Comment by saad-ali** [comment] 2016-12-16 01:35
Thanks for noticing this @janetkuo 

@kubernetes/sig-cluster-lifecycle can you please help investigate and triage this issue or help find the correct owner?

We need to:

1. Verify that local-up-cluster is indeed broken in 1.5.1.
2. Identify what the severity of this is and how quickly we need to get a fix out.
3. Figure out why it's broken and fix it
  * There were only two commits between 1.5.0 and 1.5.1 that disabled anon auth. Does the local-up-cluster script expect anon auth? CC @erictune @deads2k @liggitt 
4. Figure out why this break of this script was not detected by any of our testing.

**Comment by janetkuo** [comment] 2016-12-16 01:36
Update: #38708 is the cause

**Comment by saad-ali** [comment] 2016-12-16 01:50
CC @bprashanth 

Local cluster up is a "hack" script we provide. It sucks that it broke in v1.5.1, but we do not need to rush a fix a v1.5.2 out the door to fix it. Instead we will wait for the normal v1.5.2 release schedule (post holiday).

Action items:
1. Update v1.5.1 release notes with a "Known Issues" section and add this issue to it, and, if possible, provide a workaround.
2. Fix this issue for the v1.5.2 release.

We need an owner for both these items. 

@janetkuo Could you own item 1?

@deads2k Could you own item 2?

**Comment by janetkuo** [comment] 2016-12-16 02:02
> @janetkuo Could you own item 1?

Yes

**Comment by deads2k** [comment] 2016-12-16 02:16
> @deads2k Could you own item 2?

Yeah.  I fixed it in a different pull once before

**Comment by janetkuo** [comment] 2016-12-16 02:18
> if possible, provide a workaround

Is the following workaround acceptable?

Pass `--anonymous-auth=true` to `sudo -E "${GO_OUT}/hyperkube" apiserver ...`

**Comment by saad-ali** [comment] 2016-12-16 02:21
Thank you both.

> janetkuo commented 3 minutes ago
> Is the following workaround acceptable?
> 
> Pass --anonymous-auth=true to sudo -E "${GO_OUT}/hyperkube" apiserver ...

@deads2k?

**Comment by deads2k** [comment] 2016-12-16 13:23
> Is the following workaround acceptable?
> 
> Pass --anonymous-auth=true to sudo -E "${GO_OUT}/hyperkube" apiserver ...

Yeah, that's actually better than what I did with the modification I made.  You want to do that instead?

**Comment by janetkuo** [comment] 2016-12-16 19:07
> Update v1.5.1 release notes with a "Known Issues" section and add this issue to it, and, if possible, provide a workaround.

Filed #38884

**Comment by lavalamp** [comment] 2017-01-26 00:57
I can confirm that without @janetkuo's suggested fix, local-up-cluster doesn't actually produce a functioning cluster. Controller manager is blocked from accessing anything.

**Comment by lavalamp** [comment] 2017-01-26 01:04
Well, let me back off on that claim. The controller manager seems to be able to talk to apiserver again, but pods don seem to be able to.

`E0126 00:59:10.717842       8 election.go:226] error retrieving resource lock default/etcd-operator: Get https://10.0.0.1:443/api/v1/namespaces/default/endpoints/etcd-operator: dial tcp 10.0.0.1:443: getsockopt: connection timed out`

e.g. etcd-operator prints a stream of the above.

**Comment by lavalamp** [comment] 2017-01-26 01:10
I think the issue is that the apiserver is failing to give the kubernetes service any endpoints.

**Comment by lavalamp** [comment] 2017-01-26 01:15
```
E0125 17:10:59.076148    4623 controller.go:162] unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)
```

**Comment by lavalamp** [comment] 2017-01-26 01:28
OK, I figured it out.

```
     if [[ "${API_HOST}" != "127.0.0.1" ]]; then
         advertise_address="--advertise_address=${API_HOST_IP}"
     fi
```

should be:

```
     if [[ "${API_HOST_IP}" != "127.0.0.1" ]]; then
         advertise_address="--advertise_address=${API_HOST_IP}"
     fi
```

because the API_HOST variable is "localhost", not 127.0.0.1.

**Comment by lavalamp** [comment] 2017-01-26 01:34
I sent #40501 with @janetkuo's fix and my fix.

**Comment by lavalamp** [comment] 2017-01-26 21:10
This ought to be fixed now.

**Closed by lavalamp** 2017-01-26 21:10 UTC
Labels: kind/bug, requires-release-czar-attention
