### ISSUE TITLE
Kube-apiserver failing to connect to multiple etcd servers using client cert authentication

### ISSUE THREAD

**Issue by rafatio** [kubernetes/kubernetes#79145] opened 2019-06-18 19:25 UTC
**What happened**:
After upgrading from 1.12.1 to 1.14.3, `kube-apiserver`'s only connecting to the first etcd server from the list passed in `--etcd-servers`.
The following errors appears during kube-apiserver startup:

```
I0618 18:45:34.225389       6 client.go:352] parsed scheme: ""
I0618 18:45:34.225416       6 client.go:352] scheme "" not registered, fallback to default scheme
I0618 18:45:34.226797       6 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{k8s-etcd-1:2379 0  <nil>}]
I0618 18:45:34.226895       6 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{k8s-etcd-1:2379 <nil>} {k8s-etcd-2:2379 <nil>} {k8s-etcd-3:2379 <nil>}]
W0618 18:45:34.245478       6 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {k8s-etcd-2:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for k8s-etcd-2, not k8s-etcd-1". Reconnecting...
W0618 18:45:34.247450       6 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {k8s-etcd-3:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for k8s-etcd-3, not k8s-etcd-1". Reconnecting...
```

And in etcd servers:

k8s-etcd-2
```
Jun 18 18:47:29 k8s-etcd-2 etcd[19521]: rejected connection from "10.x.x.x:14632" (error "remote error: tls: bad certificate", ServerName "k8s-etcd-1")
```

k8s-etcd-3
```
Jun 18 18:47:29 k8s-etcd-3 etcd[4520]: rejected connection from "10.x.x.x:37138" (error "remote error: tls: bad certificate", ServerName "k8s-etcd-1")
```

When we change etcd servers list order, the output is similar so doesn't look like to be a problem in the client certificate (e.g. if we pass k8s-etcd-2 first in the list, k8s-etcd-2 works, but k8s-etcd-1 and k8s-etcd-3 don't)

The error stops when we disable client cert authentication for etcd servers. Looks like it's always using the first etcd server in the list as ServerName, and then etcd server is rejecting the connection

**What you expected to happen**:
kube-apiserver be able to connect with a list of etcd servers using client cert authentication

**How to reproduce it (as minimally and precisely as possible)**:
Run kube-apiserver (1.14.3) passing two or more etcd servers (etcd Version: 3.3.10) and using client cert authentication

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`):
NAME="Oracle Linux Server"
VERSION="7.6"
ID="ol"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Oracle Linux Server 7.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.6

- Kernel (e.g. `uname -a`):
Linux k8s-master-1 4.1.12-124.26.12.el7uek.x86_64 #2 SMP Wed May 8 22:25:03 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
puppet

**Comment by wenjiaswe** [comment] 2019-06-20 20:21
I think this is a duplicate of #72102, thanks to gRPC team and @gyuho who are working on it.

**Comment by liggitt** [comment] 2019-06-22 05:18
correct, closing as duplicate of #72102

/close

**Closed by liggitt** 2019-06-22 05:18 UTC
Labels: kind/bug, sig/api-machinery
