### ISSUE TITLE
"Services" e2e test flaky on head

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#13032] opened 2015-08-21 15:08 UTC
"Services" e2e test seems to be broken (flaky) on head. See:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8170/console

Summarizing 3 Failures:

[Fail] Services [It] should be able to create a functioning external load balancer 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1238

[Fail] Services [It] should be able to change the type and nodeport settings of a service 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1238

[Fail] Services [It] should release the load balancer when Type goes from LoadBalancer -> NodePort 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1238

**Comment by jszczepkowski** [comment] 2015-08-21 15:09
I set-up e2e test cluster, and I was able to reproduce this problem manually. Test "Services.should be able to change the type and nodeport settings of a service" seems to fail in about 10% of runs.

• Failure [577.679 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:946
  should be able to change the type and nodeport settings of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:639

  Error waiting for the url http://23.251.142.250:80 to be reachable
  Expected error:
      <*errors.errorString | 0xc208029ea0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

**Comment by jszczepkowski** [comment] 2015-08-21 15:10
@wojtek-t @zmerlynn 
This problem may be caused #12975.

**Comment by wojtek-t** [comment] 2015-08-21 16:00
The more I'm looking into it, the more I doubt it's caused by my PR.

**Comment by quinton-hoole** [comment] 2015-08-21 16:08
Nice work @jszczepkowski.  It would be worthwhile improving those non-specific timeout error messages in the e2e test if anyone has time.  

I wouldn't be too surprised if GCE is perhaps taking a lot longer than usual.  We've seen that before.

**Comment by zmerlynn** [comment] 2015-08-21 18:57
`Services should be able to change the type and nodeport settings of a service` isn't just flaky on `gke-ci`, it's just outright broken. Does anyone on the GKE team have bandwidth for it? @a-robinson?

**Comment by wojtek-t** [comment] 2015-08-24 09:43
As I wrote above, it seems it wasn't caused by my PR (it was reverted on Friday and this test failed multiple times since then).

As discussed offline, @mwielgus (as our oncall) will take a look into it - my hypothesis is that it might be caused by #12986, but so far I have no confirmation for it.

**Comment by wojtek-t** [comment] 2015-08-24 09:44
cc @thockin @BenTheElder

Also note this comment: https://github.com/kubernetes/kubernetes/pull/12986#issuecomment-133273398

**Comment by wojtek-t** [comment] 2015-08-24 11:05
I locally reverted #12986 and it didn't fully fix the problem...

**Comment by BenTheElder** [comment] 2015-08-24 17:12
I killed my local e2e run after the restarted GCE bot finished first, when
thockin restarted the GCE tester everything passed.
Shouldn't be caused by the new proxy stuff as it is gated behind a cli flag.

Not sure what caused it though.

**Comment by a-robinson** [comment] 2015-08-24 17:21
I can't say I have much bandwidth for this. Do we have any additional logs saved from the failures?

My most likely guess is that GCE's LB is taking too long to initialize and start actually serving traffic. That would seem to be corroborated by the error message being "connection reset by peer", at least given my understanding of that message. It's unlikely that our webserver pod would recognize our request but choose to RST it.

If we are concerned about the webserver pod, though, it wouldn't hurt to add a readiness check to it.

**Comment by wojtek-t** [comment] 2015-08-24 18:13
These problems started on Friday - this has to be caused either by our change or by some GCE rollout.
As for logs - there are quite a lot failures on Jenkins for which we have logs.

**Comment by brendandburns** [comment] 2015-08-28 22:41
I think actually a lot of these problems are due to assumptions in the test that the ingress IP address stays constant across a port update, which it didn't.  I've updated the GCE code to make it stay true in: https://github.com/kubernetes/kubernetes/pull/13335

**Comment by quinton-hoole** [comment] 2015-09-10 20:43
One of these tests remain flaky. @brendandburns are you still working on this P0, or should it be re-assigned to someone who can work on it immediately?

 * Kubernetes e2e suite.Services should be able to change the type and nodeport settings of a service (**Failed 7 times** in the last 30 runs. Stability: 76 %)

**Comment by quinton-hoole** [comment] 2015-09-10 20:46
Never mind.  Fixing the above test is being tracked in #13818. The others are stable now.  Closing this issue.

**Closed by quinton-hoole** 2015-09-10 20:46 UTC
Labels: area/test, priority/P0, team/testing
