### ISSUE TITLE
cpuset.cpu_exclusive flag not set for Guaranteed Qos Pod Container

### ISSUE THREAD

**Issue by pperiyasamy** [kubernetes/kubernetes#87249] opened 2020-01-15 15:39 UTC
**What happened**:

I've deployed K8s cluster with kubelet's CPU Manager set to static policy.
While creating Guaranteed QoS POD with dedicated CPUs for the container, it assigns the dedicated CPUs, but without exclusive flag set in the container's cgroup file system (/sys/fs/cgroup/cpuset/cpuset.cpu_exclusive)

_worker_

```
# kubectl get pods
NAME       READY   STATUS    RESTARTS   AGE
pod-test   1/1     Running   0          7m16s
# cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0-1,6-17","entries":{"cdc2c5cc531dd48bceb064e5411259a46bd8b8e70974fce10a3620b5b5da2c05":"2-5"},"checksum":148873334}
```
_pod container_

```
# cat /proc/1/task/1/status | grep Cpus_allowed
Cpus_allowed:   0003c
Cpus_allowed_list:      2-5
# cat /sys/fs/cgroup/cpuset/cpuset.cpus
2-5
# cat /sys/fs/cgroup/cpuset/cpuset.cpu_exclusive
0
```

**What you expected to happen**:

The CPU cores 2-5 should get exclusively assigned to the pod container and cpuset.cpu_exclusive file is supposed to set with 1.

**How to reproduce it (as minimally and precisely as possible)**:

Create Guaranteed QoS Pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
`Linux my-centos 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ipuustin** [comment] 2020-01-16 08:35
The other containers in guaranteed pods with integer cpu requests will get other full cpus assigned to them while the default cpu pool shrinks, so there should be no overlap when the system . However, it's not guaranteed to be true outside of the kubernetes domain: there might be other "cousin" cpusets belonging to the system. I just tried setting the `cpuset.cpu_exclusive` flag on a container in a guaranteed pod and it failed for this reason.

Also, I don't think cpu manager guarantees even for kubernetes containers that the cpusets don't overlap at any point of time. The reconciliation loop only makes the guaranteed containers will eventually have separate cpusets.

Is there a particular reason why you would need `cpuset.cpu_exclusive` flag to be turned on?

**Comment by JanScheurich** [comment] 2020-01-16 11:07
@ipuustin This was a misunderstanding of the function of the cpuset.cpu_exclusive flag on our side. I thought it would automatically "disable" the CPUs in the current cpuset in other non-ancestor cpusets. But it seems it will only prevent that new overlapping cpusets can be created, and as your trial showed, you can't set the flag if there are already overlapping cpusets.

So the cpumanager approach to remove dedicated CPUs from the default cpuset of other containers during reconciliation is actually the only way to provide isolation from other pods running non-guaranteed containers. In that approach should do the trick.

What we are really after is how to *also* isolate the guaranteed containers running DPDK applications from interference by Kubernetes system processes, non-Kubernetes processes and as many kernel threads as possible, without having to revert to "isolcpus" on the kernel boot command line.

**Comment by ipuustin** [comment] 2020-01-16 14:25
Well, I guess the manual approach for this is to use kubelet's `--system-reserved` flag limiting the amount of cores available to cpu manager. Then see which cores cpu manager has taken to itself in the default cpuset. After this is done, create a new cpuset cgroup and add set the `cpuset.cpus` there to be exactly the reserved cpus and move all the system processes there. You might already have a '/system.slice` cgroup or similar where the system processes are.

For example, when I run kubelet with `--cpu-manager-policy=static --system-reserved=cpu=10` I see this in my log:

```
Jan 15 17:20:14 test kubelet[21341]: I0115 17:20:14.247128   21341 policy_static.go:110] [cpumanager] reserved 10 CPUs ("0-4,40-44") not available for exclusive assignment
```

This means that guaranteed pods are not scheduled on cpuset "0-4,40-44", thus it's safe to let system services execute on that cpuset.

Isolating the CPUs without `isolcpus` is a really interesting question. It might be that offlining and then onlining a CPU core while disabling interrupts there might provide you with a "clean" core. See this document: https://www.kernel.org/doc/Documentation/kernel-per-CPU-kthreads.txt

Also @klihub might have some good ideas here and maybe tell some of the previous NUMA and CPU pool approaches we have tried.

**Comment by klihub** [comment] 2020-01-16 18:20
> What we are really after is how to _also_ isolate the guaranteed containers running DPDK applications from interference by Kubernetes system processes, non-Kubernetes processes and as many kernel threads as possible, without having to revert to "isolcpus" on the kernel boot command line.

I think this is not possible with stock Kubernetes alone at the moment. That's why people are trying to use various kinds of workarounds, for instance for K8s-hosted NFV/DPDK applications: see [CPU-Pooler](https://github.com/nokia/CPU-Pooler), [CMK](https://github.com/intel/CPU-Manager-for-Kubernetes) or [CRI Resource Manager](https://github.com/intel/cri-resource-manager). All of these workarounds tend to come with their own gotchas and it's difficult to say which one might or would fit your needs the best/at all.

There were a few related presentation recently in KubeCon: see [1](https://sched.co/UaWZ), [2](https://sched.co/UaZx), and [3](https://sched.co/UabM).

Distilled from those presentations, AFAICT the current telco consensus about critical high-bandwidth/low-latency workloads is that for most of those workloads it is a good idea to use kernel-isolated CPUs. For some (for instance, 5G infra) it is a required but not sufficient pre-requisite... additionally you might need some/all of the following:
  - topology-aware workload placement (optimally aligned CPUs wrt. memory nodes/huge pages, and I/O/PCI cards)
  - your DPDK CPUs being masked from kernel interrupt handling
  - sched-fifo/RT scheduling
  - realtime pre-empt kernel

@kad Can probably tell a lot more about this subject.

**Comment by sbrs3** [comment] 2020-01-17 09:39
Trying to implement CPU isolation by moving system processes to `system-reserved` but kubelet fails to find the system cgroup I manually create and refer to with the `--system-reserved-cgroup` parameter.

I first create the /systemreserved cgroup like this: `cset set -c 0 -s /systemreserved`

In kubeadm-flags.env I have `--system-reserved=cpu=1 --system-reserved-cgroup=/systemreserved --enforce-node-allocatable=pods,system-reserved`.

When I restart kubelet I get: `kubelet.go:1380] Failed to start ContainerManager Failed to enforce System Reserved Cgroup Limits on "/systemreserved": ["systemreserved"] cgroup does not exist`.

Why is that? I can see the /systemreserved cgroup exists:

```
cset set -l -r -s /
cset: 
         Name       CPUs-X    MEMs-X Tasks Subs Path
 ------------ ---------- - ------- - ----- ---- ----------
         root        0-3 y       0 y   140    2 /
 systemreserved          0 n       0 n     0    0 /systemreserved
     kubepods        0-3 n       0 n     0    2 /kubepods
   besteffort        0-3 n       0 n     0    0 /kubepods/besteffort
    burstable        0-3 n       0 n     0    0 /kubepods/burstable
```

The cgroup driver is cgroupfs and the cluster was created with latest kubeadm.

**Comment by ipuustin** [comment] 2020-01-17 11:39
@sbrs3: Last time I created cgroups I did it something like this:

    $ sudo cgcreate -g blkio,cpu,cpuset,memory:systemreserved/
    # Initialize cpus and mems, otherwise can't exec in the cgroup
    $ sudo sh -c "cat /sys/fs/cgroup/cpuset/cpuset.cpus > /sys/fs/cgroup/cpuset/systemreserved/cpuset.cpus"
    $ sudo sh -c "cat /sys/fs/cgroup/cpuset/cpuset.mems > /sys/fs/cgroup/cpuset/systemreserved/cpuset.mems"

You should first try if you can manually run processes in the new cgroup. See also issue https://github.com/kubernetes/kubernetes/issues/85764.

**Comment by klihub** [comment] 2020-01-17 12:02
> Well, I guess the manual approach for this is to use kubelet's `--system-reserved` flag limiting the amount of cores available to cpu manager. Then see which cores cpu manager has taken to itself in the default cpuset. After this is done, create a new cpuset cgroup and add set the `cpuset.cpus` there to be exactly the reserved cpus and move all the system processes there.

@ipuustin Hmm... are you sure that would work as intended above ? Wouldn't that keep only the Guaranteed QoS Pods with full CPU requests off the reserved CPUs, with the best effort and burstable still running there ?

**Comment by ipuustin** [comment] 2020-01-17 13:12
@klihub Yes, it's only for guaranteed pods; I understood from the question that the idea was to get the guaranteed pods to run without inference. The burstable and besteffort pods are running on the "default" cpuset. The default cpuset only has the guaranteed pods deducted from it, but not the ` [system,kube]-reserved` cpus.  

It could actually be that if you will do the cgroup manually you might be better off with the new [--reserved-cpus](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#explicitly-reserved-cpu-list) option which actually takes a cpuset. It's mentioned in the documentation that it's designed for telco use cases.

**Comment by sbrs3** [comment] 2020-01-17 13:59
@ipuustin Same result when I create the cgroup with cgcreate as you suggested.
I can run processes in the newly created cgroup; I can even move most of the existing ones into there.

```
root@debian2:/var/lib/kubelet# cset set -l -r -s /
cset: 
         Name       CPUs-X    MEMs-X Tasks Subs Path
 ------------ ---------- - ------- - ----- ---- ----------
         root        0-3 y       0 y   135    2 /
 systemreserved          0 n       0 n     0    0 /systemreserved
     kubepods        0-3 n       0 n     0    2 /kubepods
   besteffort        0-3 n       0 n     0    0 /kubepods/besteffort
    burstable        0-3 n       0 n     0    0 /kubepods/burstable
root@debian2:/var/lib/kubelet# cset proc -m -k -f / -t /systemreserved --force
cset: moving all tasks from root to /systemreserved
cset: moving 55 userspace tasks to /systemreserved
cset: moving 80 kernel threads to: /systemreserved
[==================================================]%
cset: **> 67 tasks are not movable, impossible to move
cset: done
root@debian2:/var/lib/kubelet# cset set -l -r -s /
cset: 
         Name       CPUs-X    MEMs-X Tasks Subs Path
 ------------ ---------- - ------- - ----- ---- ----------
         root        0-3 y       0 y    67    2 /
 systemreserved          0 n       0 n    68    0 /systemreserved
     kubepods        0-3 n       0 n     0    2 /kubepods
   besteffort        0-3 n       0 n     0    0 /kubepods/besteffort
    burstable        0-3 n       0 n     0    0 /kubepods/burstable
```
But kubelet continues to insist that `/systemreserved` does not exist. Kernel is 4.9 (Debian Stretch).

**Comment by ipuustin** [comment] 2020-01-21 09:29
It appears that `Exists()` function in the cgroup manager logs the missing path on verbosity level 4 before it returns false, see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cgroup_manager_linux.go#L276.

Could you check what the log message says? Possibly you have some of the paths missing.

**Comment by sbrs3** [comment] 2020-01-22 14:47
Increased the log level of kubelet and it was missing following two paths: `[/sys/fs/cgroup/pids/systemreserved /sys/fs/cgroup/systemd/systemreserved]`. The first one (pids) I added by specifying pids controller with cgcreate. Not sure about the second one though (`/sys/fs/cgroup/systemd/...`). How would that get created? And why is kubelet looking for it even though I started it with `--cgroup-driver=cgroupfs`?
Could the kernel version play a role here? Which one are you using?

**Comment by ipuustin** [comment] 2020-01-23 09:33
The second path would be the systemd cgroup. Systemd uses that for process tracking. It's not optional in kubelet: see https://github.com/kubernetes/kubernetes/blame/50fa183d51d92b6abd9e7d146f0d38aca59ea4b1/pkg/kubelet/cm/cgroup_manager_linux.go#L256

I would have thought that systemd in your node would have mounted the cgroup. It also wonder if the systemd check might be removed based on the first message here: https://github.com/kubernetes/kubernetes/pull/28755

**Comment by saurabhanetskope** [comment] 2020-03-07 08:27
> The other containers in guaranteed pods with integer cpu requests will get other full cpus assigned to them while the default cpu pool shrinks, so there should be no overlap when the system . However, it's not guaranteed to be true outside of the kubernetes domain: there might be other "cousin" cpusets belonging to the system. I just tried setting the `cpuset.cpu_exclusive` flag on a container in a guaranteed pod and it failed for this reason.
> 
> Also, I don't think cpu manager guarantees even for kubernetes containers that the cpusets don't overlap at any point of time. The reconciliation loop only makes the guaranteed containers will eventually have separate cpusets.
> 
> Is there a particular reason why you would need `cpuset.cpu_exclusive` flag to be turned on?

@ipuustin going by this k8s feature release notes https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/, the cpu_sets or the core given to guaranteed containers should not change during the lifetime of the container. But the comment above suggests that it can happen. I am running into a similar issue mentioned here https://github.com/kubernetes/kubernetes/issues/88939
Is it expected to is it just a bug? We didn't see it k8s 1.13 but only in k8s 1.15.5

**Comment by ipuustin** [comment] 2020-03-09 14:56
I think that the cpuset for a Guaranteed container doesn't change after the first assignment. If you see it changing (other than the aforementioned "all cpus" -> "some limited number of cpus") you should check if your container has been restarted for any reason.

**Comment by saurabhanetskope** [comment] 2020-03-09 16:16
I checked and saw container has not restarted. cpu_sets for the guaranteed container-id changed after initial assignment. I have the kubelet logs to show that is indeed the case. I am attaching the log file. Please look for this container id in the logs 82b9c23702a30bcbe946379d0ae256954a42bccfec43cbe27dbf5e7a94aa334d

[kubelet_cpu_sets.log](https://github.com/kubernetes/kubernetes/files/4307718/kubelet_cpu_sets.log)

**Comment by klihub** [comment] 2020-03-10 08:56
> I checked and saw container has not restarted. cpu_sets for the guaranteed container-id changed after initial assignment. I have the kubelet logs to show that is indeed the case.

Does your Guaranteed QoS container takes a full integer number of CPUs ?

**Comment by saurabhanetskope** [comment] 2020-03-10 09:39
Yes, it has full integer number of CPUs. I also verified the result of docker inspect <c-id> and it does mention the cpuShares and cpusets correctly

**Comment by pkdas** [comment] 2020-03-19 22:24
I looked at the log - I do see container add/remove e.g. container ID 78ff8aadac734a58d91c483c6f7b92ff770534d5a8860e542df4b99639e04929
It might have been restarted.

**Comment by Maxpain177** [comment] 2020-07-31 23:15
Any news?

**Closed** 2020-08-31 00:02 UTC
Labels: kind/bug, lifecycle/rotten, sig/node

**Comment by Purushotham233** [comment] 2021-03-18 02:26
Facing a similar interference issue, cpu throttling reported for containers with integer in Guaranteed Pods. In our case the same node runs other Burstable and Guaranteed but fractional cpu containers.

Any inputs on the solve/workaround ?
@pperiyasamy @ipuustin

**Comment by willzhang** [comment] 2023-04-07 18:15
Any news?
