### ISSUE TITLE
Garbage Collector does not clean up service objects correctly with "Foreground" propagation policy

### ISSUE THREAD

**Issue by rsparulek** [kubernetes/kubernetes#90692] opened 2020-05-02 19:39 UTC
**What happened**:
```
Service Objects are not getting deleted/cleaned correctly when services are deleted and recreated quickly at scale. This issue is similar to earlier issue https://github.com/kubernetes/kubernetes/issues/77081

```

**What you expected to happen**:
```
Expected to cleanup service objects using "Foreground" propagation policy
```

**How to reproduce it (as minimally and precisely as possible)**:
```
This issue is hard to reproduce but it usually happens when services are deleted and recreated quickly at scale.
```

**Anything else we need to know?**:

**Environment**:
```
Multi Node K8S 1.18.2 cluster with single master node and 3 worker/slave nodes running
on Linux machines
```
- Kubernetes version (use `kubectl version`):
```
######## kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
Using kubernetes client version 10.0.0a1
```

```
Logs:

  File "/usr/lib/python3.4/site-packages/kubernetes/client/apis/core_v1_api.py", line 6934, in create_namespaced_service
    (data) = self.create_namespaced_service_with_http_info(namespace, body, **kwargs)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/apis/core_v1_api.py", line 7025, in create_namespaced_service_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/lib/python3.4/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)

kubernetes.client.rest.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Sat, 02 May 2020 18:16:39 GMT', 'Content-Length': '249'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"object is being deleted: services \"my-svc\" already exists","reason":"AlreadyExists","details":{"name":"my-svc","kind":"services"},"code":409}
```

**Comment by liggitt** [comment] 2020-05-02 22:06
Thanks for the report. This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/90512 and is likely specific to services due to its customized delete handler.

**Closed by liggitt** 2020-05-02 22:06 UTC
Labels: kind/bug, sig/cluster-lifecycle

**Comment by grosser** [comment] 2021-07-02 20:16
still seeing this with simple pods on 1.20 🤷

**Comment by liggitt** [comment] 2021-09-07 21:33
> still seeing this with simple pods on 1.20 🤷

do you have more details about the objects involved, the sequence of operations you're seeing, and the end state?

**Comment by grosser** [comment] 2021-09-07 21:35
no, this was a long time ago ... can add more docs when I see it again
... but chances are I won't see it again since we added a "delete if this is too old" check now :(

**Comment by liggitt** [comment] 2021-09-07 21:39
fwiw, the unit tests added in 1.20 let us do completely deterministic checking of async scenarios that are normally hard to reproduce ... I added one for deletion of a pod with a foreground finalizer at HEAD and wasn't able to reproduce the simplistic version of the scenario - https://github.com/liggitt/kubernetes/commits/gc-foreground
