### ISSUE TITLE
[Federation] kubefed join service account errors

### ISSUE THREAD

**Issue by font** [kubernetes/kubernetes#50888] opened 2017-08-18 05:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I was successfully able to `kubefed init` a federation control plane on a GKE k8s cluster, but upon attempting to join the cluster the following error occurs:

```
...
I0816 10:46:38.538848    5942 join.go:538] Creating service account in joining cluster
I0816 10:46:38.539061    5942 request.go:991] Request Body: {"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"gce-us-west1-gke_<project>_us-west1-b_gce-us-west1","namespace":"federation-system","creationTimestamp":null,"annotations":{"federation.alpha.kubernetes.io/cluster-name":"gce-us-west1","federation.alpha.kubernetes.io/federation-name":"federation"}}}
I0816 10:46:38.539134    5942 round_trippers.go:386] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubefed/v1.7.3 (linux/amd64) kubernetes/2c2fe6e" -H "Authorization: Basic ABCDEFGHIJKLMNOPQRSTUVWXYZabcd==" https://35.197.74.218/api/v1/namespaces/federation-system/serviceaccounts
I0816 10:46:38.576175    5942 round_trippers.go:405] POST https://35.197.74.218/api/v1/namespaces/federation-system/serviceaccounts 422 Unprocessable Entity in 37 milliseconds
I0816 10:46:38.576211    5942 round_trippers.go:411] Response Headers:
I0816 10:46:38.576225    5942 round_trippers.go:414]     Date: Wed, 16 Aug 2017 17:46:38 GMT
I0816 10:46:38.576236    5942 round_trippers.go:414]     Content-Type: application/json
I0816 10:46:38.576245    5942 round_trippers.go:414]     Content-Length: 1038
I0816 10:46:38.576515    5942 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ServiceAccount \"gce-us-west1-gke_<project>_us-west1-b_gce-us-west1\" is invalid: metadata.name: Invalid value: \"gce-us-west1-gke_<project>_us-west1-b_gce-us-west1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"gce-us-west1-gke_<project>_us-west1-b_gce-us-west1","kind":"ServiceAccount","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"gce-us-west1-gke_<project>_us-west1-b_gce-us-west1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}
I0816 10:46:38.576711    5942 join.go:541] Error creating service account in joining cluster: ServiceAccount "gce-us-west1-gke_<project>_us-west1-b_gce-us-west1" is invalid: metadata.name: Invalid value: "gce-us-west1-gke_<project>_us-west1-b_gce-us-west1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
I0816 10:46:38.576736    5942 join.go:234] Could not create cluster credentials secret: ServiceAccount "gce-us-west1-gke_<project>_us-west1-b_gce-us-west1" is invalid: metadata.name: Invalid value: "gce-us-west1-gke_<project>_us-west1-b_gce-us-west1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
This appears to be caused by the context name `gke_<project>_us-west1-b_gce-us-west1` which is using the default context name for a GKE cluster that is automatically imported to the kubeconfig file by `gcloud`.

If I update the kubeconfig context to get rid of the `_` to something like `gce-us-west1`, I can get past the above error but then subsequently hit the following error:

```
I0817 18:12:26.855195   14103 join.go:538] Creating service account in joining cluster
I0817 18:12:26.855329   14103 request.go:991] Request Body: {"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"gce-us-west1-gce-us-west1","namespace":"federation-system","creationTimestamp":null,"annotations":{"federation.alpha.kubernetes.io/cluster-name":"gce-us-west1","federation.alpha.kubernetes.io/federation-name":"federation"}}}
I0817 18:12:26.855376   14103 round_trippers.go:386] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubefed/v1.7.3 (linux/amd64) kubernetes/2c2fe6e" -H "Authorization: Basic ABCDEFGHIJKLMNOPQRSTUVWXYZabcd==" https://35.197.74.218/api/v1/namespaces/federation-system/serviceaccounts
I0817 18:12:26.885490   14103 round_trippers.go:405] POST https://35.197.74.218/api/v1/namespaces/federation-system/serviceaccounts 201 Created in 30 milliseconds
I0817 18:12:26.885536   14103 round_trippers.go:411] Response Headers:
I0817 18:12:26.885550   14103 round_trippers.go:414]     Content-Length: 470
I0817 18:12:26.885560   14103 round_trippers.go:414]     Date: Fri, 18 Aug 2017 01:12:26 GMT
I0817 18:12:26.885570   14103 round_trippers.go:414]     Content-Type: application/json
I0817 18:12:26.886617   14103 request.go:991] Response Body: {"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"gce-us-west1-gce-us-west1","namespace":"federation-system","selfLink":"/api/v1/namespaces/federation-system/serviceaccounts/gce-us-west1-gce-us-west1","uid":"4c7d5fb9-83b2-11e7-bda1-42010a8a01d8","resourceVersion":"220285","creationTimestamp":"2017-08-18T01:12:26Z","annotations":{"federation.alpha.kubernetes.io/cluster-name":"gce-us-west1","federation.alpha.kubernetes.io/federation-name":"federation"}}}
I0817 18:12:26.886800   14103 join.go:544] Created service account in joining cluster
I0817 18:12:26.886817   14103 join.go:546] Creating role binding for service account in joining cluster
I0817 18:12:26.887024   14103 request.go:991] Request Body: {"kind":"ClusterRole","apiVersion":"rbac.authorization.k8s.io/v1beta1","metadata":{"name":"federation-controller-manager:federation-gce-us-west1-gce-us-west1","namespace":"federation-system","creationTimestamp":null,"annotations":{"federation.alpha.kubernetes.io/cluster-name":"gce-us-west1","federation.alpha.kubernetes.io/federation-name":"federation"}},"rules":[{"verbs":["*"],"apiGroups":["*"],"resources":["*"]},{"verbs":["get"],"nonResourceURLs":["/healthz"]}]}
I0817 18:12:26.887093   14103 round_trippers.go:386] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubefed/v1.7.3 (linux/amd64) kubernetes/2c2fe6e" -H "Authorization: Basic ABCDEFGHIJKLMNOPQRSTUVWXYZabcd==" https://35.197.74.218/apis/rbac.authorization.k8s.io/v1beta1/clusterroles
I0817 18:12:26.917114   14103 round_trippers.go:405] POST https://35.197.74.218/apis/rbac.authorization.k8s.io/v1beta1/clusterroles 409 Conflict in 29 milliseconds
I0817 18:12:26.917149   14103 round_trippers.go:411] Response Headers:
I0817 18:12:26.917161   14103 round_trippers.go:414]     Content-Length: 388
I0817 18:12:26.917167   14103 round_trippers.go:414]     Date: Fri, 18 Aug 2017 01:12:26 GMT
I0817 18:12:26.917173   14103 round_trippers.go:414]     Content-Type: application/json
I0817 18:12:26.917214   14103 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:federation-gce-us-west1-gce-us-west1\" already exists","reason":"AlreadyExists","details":{"name":"federation-controller-manager:federation-gce-us-west1-gce-us-west1","group":"rbac.authorization.k8s.io","kind":"clusterroles"},"code":409}
I0817 18:12:26.917356   14103 join.go:630] Could not create role for service account in joining cluster: clusterroles.rbac.authorization.k8s.io "federation-controller-manager:federation-gce-us-west1-gce-us-west1" already exists
I0817 18:12:26.917375   14103 join.go:549] Error creating role binding for service account in joining cluster: clusterroles.rbac.authorization.k8s.io "federation-controller-manager:federation-gce-us-west1-gce-us-west1" already exists
I0817 18:12:26.917390   14103 join.go:234] Could not create cluster credentials secret: clusterroles.rbac.authorization.k8s.io "federation-controller-manager:federation-gce-us-west1-gce-us-west1" already exists
I0817 18:12:26.917446   14103 helpers.go:207] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:federation-gce-us-west1-gce-us-west1\" already exists",
  "reason": "AlreadyExists",
  "details": {
    "name": "federation-controller-manager:federation-gce-us-west1-gce-us-west1",
    "group": "rbac.authorization.k8s.io",
    "kind": "clusterroles"
  },
  "code": 409
}]
F0817 18:12:26.917481   14103 helpers.go:120] Error from server (AlreadyExists): clusterroles.rbac.authorization.k8s.io "federation-controller-manager:federation-gce-us-west1-gce-us-west1" already exists
```

**What you expected to happen**:
Properly be able to `kubefed join` the cluster into the federation.

**How to reproduce it (as minimally and precisely as possible)**:
```
1. gcloud container clusters create --cluster-version=1.7.3 <cluster_name> --zone=<zone> --scopes "cloud-platform,storage-ro,logging-write,monitoring-write,service-control,service-management,https://www.googleapis.com/auth/ndev.clouddns.readwrite"
2. kubefed init federation --host-cluster-context=<cluster_context> --dns-provider='google-clouddns' --dns-zone-name=<dns_zone_name> --controllermanager-arg-overrides="--v=10" --apiserver-arg-overrides="--v=10" --v=10
3. kubefed join <cluster_name> --host-cluster-context=<cluster_context> --cluster-context=<cluster_context> --v=10
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
→ kubefed version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GKE

cc: @kubernetes/sig-federation-bugs

**Comment by font** [comment] 2017-08-18 05:56
cc: @kubernetes/sig-federation-bugs

**Comment by ammaristotle** [comment] 2017-08-22 22:25
@font I was getting the same error earlier. I found a workaround, by renaming contexts.

```bash
$ kubectl config get-contexts
CURRENT   NAME                                         CLUSTER                                      AUTHINFO                                     NAMESPACE
          kfed                                          kfed                                          kfed                                         
          gke_MY_PROJECT_ID_us-east1-c_cluster_1_name   gke_MY_PROJECT_ID_us-east1-c_cluster_1_name   gke_MY_PROJECT_ID_us-east1-c_cluster_1_name   
*         gke_MY_PROJECT_ID_us-east4-a_cluster_2_name   gke_MY_PROJECT_ID_us-east4-a_cluster_2_name   gke_MY_PROJECT_ID_us-east4-a_cluster_2_name   
```

Where `MY_PROJECT_ID` is your project id and `cluster_1_name` and `cluster_2_name` are the names of your clusters if you run `gcloud container clusters list`

Assuming your host cluster is `cluster_1_name`, let's do a simple replace:
```bash
# Create a new context called, using the cluster and auth credentials from your cluster_1_name
$ k8s config set-context cluster_1_name \
  --cluster <CLUSTER> \
  --user <AUTHINFO>

# Delete the old cluster_1_name context
$ kubectl delete-context gke_MY_PROJECT_ID_us-east1-c_cluster_1_name
```

Now if you try `kubefed` it should work.

**Comment by font** [comment] 2017-08-22 23:24
Thanks @ammaristotle - that's the workaround I described in my original post where removing the violating underscores solves the issue.

But if you've already failed to `kubefed join` once, you subsequently hit another error as I described above. That should hopefully improve eventually via #41725. In the meantime, in order to get around that you need to cleanup the RBAC objects:

```
kubectl delete clusterrole \
    federation-controller-manager:federation-<cluster-name>-<cluster-name>
kubectl delete clusterrolebinding \
    federation-controller-manager:federation-<cluster-name>-<cluster-name>
```

**Comment by quinton-hoole** [comment] 2017-09-02 00:08
@font closing this as a dupe of #41725.  Your ref above should make sure that the context is not lost.  Thanks for your comprehensive report and suggestions.

**Closed by quinton-hoole** 2017-09-02 00:08 UTC
Labels: kind/bug, sig/federation

**Comment by font** [comment] 2017-09-02 01:10
@quinton-hoole The cleanup of the cluster role objects after hitting the first error is definitely a dupe of #41725, but there is still the original error where `kubefed join` fails to create the service account in the joining cluster.

That error was the original reason I opened this issue. Specifically, the `gcloud container clusters create` command creates your context names using underscores by default, and the `kubefed join` command attempts to use that context name as the service account name verbatim and fails because that name violates the DNS-1123 subdomain properties - since it contains a `_`.

Since underscores do not violate context names, it seems like the `kubefed join` operation could sanitize the service account name to remove underscores (and any other violating characters) prior to creating it in the joining cluster. It would still derive the service account name from the context name while replacing invalid characters. Otherwise the user will have to rename their context to remove any violating characters.

So I'm thinking we should keep this issue open. Thoughts?

**Comment by font** [comment] 2017-09-22 00:21
@quinton-hoole ^^

**Comment by irfanurrehman** [comment] 2017-09-22 05:26
@font @quinton-hoole I have updated https://github.com/kubernetes/kubernetes/issues/41725 to include a pointer (and a reference to this issue) to fix what is listed here.
@font please let me know if that is not ok, and you would still want this issue tracked here itself.

**Comment by font** [comment] 2017-09-22 22:16
It's good to include a pointer to this issue, but I don't think the items in #41725 are going to be solved in one PR as it's really a collection of feature enhancements and bug fixes. So I think it's good to have separate issues to track individual items just as is done in #41725 item 2 linking to an open sub-issue that's tracking it.

**Comment by quinton-hoole** [comment] 2017-09-22 23:16
@font I have no problem keeping this open if you think it's useful.  I was just trying to remove duplicates, but it sounds like this is not a legitimate dupe after all :-)

**Comment by font** [comment] 2017-09-25 15:47
@quinton-hoole Correct, not a duplicate. I'd prefer to keep it open so that we get it resolved.

**Comment by prasanna12510** [comment] 2018-03-18 23:33
check the secrets in the joining cluster
kubectl get secrets --namespace=federation-system 
kubectl delete secret <secret_name> --namespace=federation-system
