### ISSUE TITLE
e2e flake: should *not* be restarted with a /healthz http liveness probe [Conformance]

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18704] opened 2015-12-15 12:59 UTC
Example failure:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/20689/console

@kubernetes/goog-node

**Comment by ihmccreery** [comment] 2015-12-16 23:40
Similarly, I believe, (though the converse test) http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/20947/console

```
11:44:54 Pods
11:44:54 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:1176
11:44:54   should be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance] [It]
11:44:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:581
11:44:54 
11:44:54   Dec 16 11:44:50.239: pod e2e-tests-pods-z497e/liveness-exec - expected number of restarts: %!t(int=1), found restarts: %!t(int=0)
```

**Comment by spxtr** [comment] 2015-12-31 00:33
Ran into this on 1.0 branch.

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22149/console

**Comment by spxtr** [comment] 2016-01-07 00:55
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel/14017/

```
Pods should be restarted with a /healthz http liveness probe [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:636 Jan 6 16:11:53.763: pod e2e-tests-pods-70xtm/liveness-http - expected number of restarts: %!t(int=1), found restarts: %!t(int=0)
```

**Comment by piosz** [comment] 2016-01-12 17:02
Yet another failure
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10329/

**Comment by lavalamp** [comment] 2016-01-12 18:05
@timothysc Any news?

**Comment by timstclair** [comment] 2016-01-12 23:24
@spxtr - http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel/14017/ is a different issue (pod should be restarted vs. pod should **not** be restarted). That flake looks like it was caused by a known deadlock in docker.

**Comment by spxtr** [comment] 2016-01-12 23:30
Oops, you're right.

**Comment by timstclair** [comment] 2016-01-12 23:48
Cause of http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10329/ is the container that was not supposed to restart crashed:
```
I0112 15:08:37.590043    2544 helpers.go:96] Unable to get network stats from pid 3673: couldn't read network stats: failure opening /proc/3673/net/dev: open /proc/3673/net/dev: no such file or directory
I0112 15:08:37.599031    2544 manager.go:857] Destroyed container: "/3cb1c6d9ce8dffa6911fd501e01b79e3b6968ac2bdbc9b044bd084c951e64bc6" (aliases: [k8s_liveness.cd19d117_liveness-http_e2e-tests-pods-o4ggr_453223d9-b93e-11e5-805a-42010af00002_c9afaa6c 3cb1c6d9ce8dffa6911fd501e01b79e3b6968ac2bdbc9b044bd084c951e64bc6], namespace: "docker")
```
From what I can tell, it was just a transient container failure, but without more data I can't tell what caused it. I'll look into it again the next time this occurs.

**Comment by alex-mohr** [comment] 2016-01-21 18:09
merge-blocking failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/14750/

**Comment by dchen1107** [comment] 2016-01-21 22:20
@vishh Can you take a look at this since Tim is out this week? Thanks!

**Comment by vishh** [comment] 2016-01-22 00:38
@dchen1107: Starting to look at this now.

**Comment by vishh** [comment] 2016-01-22 01:38
This test only once in the last ~100 runs. In the last failure run, the pod was restarted and the event that was generated is as follows:

```Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Unhealthy: Liveness probe failed: Get http://10.253.6.11:8080/read: read tcp 10.253.6.11:8080: use of closed network connection```

More information:
```
[It] should *not* be restarted with a /healthz http liveness probe [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:699
Creating pod liveness-http in namespace e2e-tests-pods-jfebr
Jan 21 06:53:25.512: INFO: Waiting up to 5m0s for pod liveness-http status to be !pending
Jan 21 06:53:25.520: INFO: Waiting for pod liveness-http in namespace 'e2e-tests-pods-jfebr' status to be '!pending'(found phase: "Pending", readiness: false) (7.411874ms elapsed)
Jan 21 06:53:27.531: INFO: Saw pod 'liveness-http' in namespace 'e2e-tests-pods-jfebr' out of pending state (found '"Running"')
Started pod liveness-http in namespace e2e-tests-pods-jfebr
checking the pod's current state and verifying that restartCount is present
Initial restart count of pod liveness-http is 0
Restart count of pod e2e-tests-pods-jfebr/liveness-http is now 1 (50.485489519s elapsed)
deleting the pod
[AfterEach] Pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:70
Collecting events from namespace "e2e-tests-pods-jfebr".
Jan 21 06:55:28.262: INFO: event for liveness-http: {default-scheduler } Scheduled: Successfully assigned liveness-http to e2e-test-parallel-minion-muge
Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Pulled: Container image "gcr.io/google_containers/nettest:1.6" already present on machine
Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Created: Created container with docker id 8a968b9ab8f1
Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Started: Started container with docker id 8a968b9ab8f1
Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Unhealthy: Liveness probe failed: Get http://10.253.6.11:8080/read: read tcp 10.253.6.11:8080: use of closed network connection
Jan 21 06:55:28.262: INFO: event for liveness-http: {kubelet e2e-test-parallel-minion-muge} Killing: Killing container with docker id 8a968b9ab8f1: pod "liveness-http_e2e-tests-pods-jfebr(b964d6fa-c04e-11e5-bc06-42010af00002)" container "liveness" is unhealthy, it will be killed and re-created.
```

Still exploring.

**Comment by vishh** [comment] 2016-01-26 01:18
This test is failing ~1% of the time due to delays in the container startup. I opened #20134 to increase the wait before running the liveness checks. 
The misleading event reasons are due #19904. What happens in reality is that the liveness probe times out in 1 second (default value). 

If the test flakes again, we will have to look at the test image that is being used - `gcr.io/google_containers/nettest:1.6`

**Comment by roberthbailey** [comment] 2016-01-29 07:24
@vishh - now that #20134 has merged is there more to do here? Or are we waiting for a reoccurrence of a flake?

**Comment by dchen1107** [comment] 2016-01-29 17:11
I am closing this one for now since #20134 was merged. Please reopen it if the failure reoccurred.

**Comment by mikedanese** [comment] 2016-02-02 22:08
I think I ran into this here https://github.com/kubernetes/kubernetes/pull/20515#issuecomment-178849102

**Comment by yujuhong** [comment] 2016-02-02 23:49
> I think I ran into this here #20515 (comment)

From the log:
```
I0202 21:50:55.656922    3465 prober.go:110] Liveness probe for "liveness-http_e2e-tests-pods-6m5wj(f17b9a28-c9f6-11e5-8080-42010af00002):liveness" succeeded
I0202 21:51:05.657118    3465 prober.go:110] Liveness probe for "liveness-http_e2e-tests-pods-6m5wj(f17b9a28-c9f6-11e5-8080-42010af00002):liveness" succeeded
I0202 21:51:15.657788    3465 prober.go:110] Liveness probe for "liveness-http_e2e-tests-pods-6m5wj(f17b9a28-c9f6-11e5-8080-42010af00002):liveness" succeeded
I0202 21:51:25.658191    3465 prober.go:110] Liveness probe for "liveness-http_e2e-tests-pods-6m5wj(f17b9a28-c9f6-11e5-8080-42010af00002):liveness" succeeded
I0202 21:51:36.659166    3465 prober.go:103] Liveness probe for "liveness-http_e2e-tests-pods-6m5wj(f17b9a28-c9f6-11e5-8080-42010af00002):liveness" failed (failure): Get http://10.245.5.4:8080/read: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

This particular failure has nothing to do with the container startup.

**Comment by vishh** [comment] 2016-02-05 18:44
So 30s is not enough? I can bump it higher. I don't see any issues with the kubelet.

**Comment by dchen1107** [comment] 2016-02-08 18:25
@vishh I don't think it is related to initial delay. If you read what @yujuhong posted above, you can see that liveness probe succeeded a couple of times, then failed with timeout.

**Comment by vishh** [comment] 2016-02-08 18:44
@dchen1107: Yes. I updated my PR to bump up timeout instead.

**Closed** 2016-02-08 23:50 UTC
Labels: kind/flake, priority/P0, team/node

**Comment by caesarxuchao** [comment] 2016-03-11 22:08
This seems to occur again:
```
Pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:1222
  should *not* be restarted with a /healthz http liveness probe [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:783

  starting pod liveness-http in namespace e2e-tests-pods-mldzr
  Expected error:
      <*errors.errorString | 0xc208439850>: {
          s: "gave up waiting for pod 'liveness-http' to be '!pending' after 5m0s",
      }
      gave up waiting for pod 'liveness-http' to be '!pending' after 5m0s
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69
```
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22847/kubernetes-pull-build-test-e2e-gce/32427/?debugUI=CLOUD

**Comment by yujuhong** [comment] 2016-03-11 22:20
> This seems to occur again:

With a totally different cause:
```
Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:19 -0800 PST - event for liveness-http: {default-scheduler } Scheduled: Successfully assigned liveness-http to e2e-gce-master-1-minion-lj1a
Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:20 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} Pulling: pulling image "gcr.io/google_containers/nettest:1.7"
Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:20 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} Failed: Failed to pull image "gcr.io/google_containers/nettest:1.7": API error (500): unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable

Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:20 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "liveness" with ErrImagePull: "API error (500): unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable\n"

Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:21 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} BackOff: Back-off pulling image "gcr.io/google_containers/nettest:1.7"
Mar 11 13:26:21.424: INFO: At 2016-03-11 13:21:21 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "liveness" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/nettest:1.7\""

Mar 11 13:26:21.424: INFO: At 2016-03-11 13:22:02 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} Failed: Failed to pull image "gcr.io/google_containers/nettest:1.7": unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
Mar 11 13:26:21.424: INFO: At 2016-03-11 13:22:02 -0800 PST - event for liveness-http: {kubelet e2e-gce-master-1-minion-lj1a} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "liveness" with ErrImagePull: "unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable"
```

This looks like #20550, cc @ArtfulCoder
