### ISSUE TITLE
1.9.0 issue with kubectl secret generation that works up to 1.8.6

### ISSUE THREAD

**Issue by obriensystems** [kubernetes/kubernetes#57528] opened 2017-12-21 23:01 UTC
/kind bug
/sig auth

**What happened**:
Failure to pull docker images from a protected repository that used to work in 1.8.4 (still works in 1.8.6)
onap-aai      aai-resources-122881374-s5qd4           1/2       ImagePullBackOff   0          9h
using
create_registry_key() {
  cmd=`echo kubectl --namespace $1-$2 create secret docker-registry $3 --docker-server=$4 --docker-username=$5 --docker-password=$6 --docker-email=$7`
  eval ${cmd}
  check_return_code $cmd
}

before bringing up the pod

**What you expected to happen**:
docker pull from protected registry works

**How to reproduce it (as minimally and precisely as possible)**:
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes#ONAPonKubernetes-InstallKubectl 
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubectl
install kubernetes 1.9.0 to break the secret generation

install kubernetes 1.8.6 to fix it

**Anything else we need to know?**:
https://jira.onap.org/browse/OOM-522

**Environment**:
ubuntu@ip-172-31-82-112:~$ kubectl version

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.7-rancher1", GitCommit:"a1ea37c6f6d21f315a07631b17b9537881e1986a", GitTreeState:"clean", BuildDate:"2017-10-02T21:33:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Bare metal NUC 5777 ubuntu 16.04 or AWS EC2 VM (EBS) running Ubuntu 16.04
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
Rancher 1.6.10
Helm 2.3.0 client/server
Docker 1.12.6
- Others:

thank you guys, excellent project - and a shout out from the Linux Foundation's onap.org project which deploys 90+ containers in any 64G Ubuntu 16 system to run onap.
https://wiki.onap.org/display/DW/ONAP+Operations+Manager+Project
frank.obrien@amdocs.com

**Comment by liggitt** [comment] 2017-12-22 02:43
Duplicate of https://github.com/kubernetes/kubernetes/issues/57427, resolved in master, fix targeted for 1.9.1

**Closed by liggitt** 2017-12-22 02:43 UTC
Labels: kind/bug, sig/auth

**Comment by obriensystems** [comment] 2018-01-25 22:09
We are good under 1.9.2 - thank you
