### ISSUE TITLE
Split-Brain bug in leaderelection client.

### ISSUE THREAD

**Issue by cevian** [kubernetes/kubernetes#23731] opened 2016-04-01 14:42 UTC
I was using the election container (https://github.com/kubernetes/contrib/tree/master/election) and encountered a split-brain bug that I believe is the result of a bug in the client library (https://github.com/kubernetes/kubernetes/tree/master/pkg/client/leaderelection). First I'll post the Log from the container and then describe what I see as the problem in the code. The basic problem is that  postgres-system-1 used to be the leader but lost the lease. However, it still believes it is the leader since `OnStoppedLeading()` is never called.

> postgres-system-1 is the leader

```
E0331 22:29:34.261269 7 leaderelection.go:281] err: Endpoints "postgres-system" is forbidden: unable to UPDATE endpoints at this time because there are too many concurrent requests to increment quota
I0331 22:29:38.577846 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
I0331 22:29:43.902087 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
I0331 22:29:48.398030 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
E0331 22:29:57.136505 7 leaderelection.go:281] err: endpoints "postgres-system" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I0331 22:30:00.912678 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
I0331 22:30:05.480872 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
I0331 22:30:08.180503 7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
```

At this point postgres-system-1 still thinks its the leader.

I think the problem happens as follows (I'll walk through the code on master, where I believe the problem still exists but the actual code used by the election container is an older version, so the line numbers from the log and what i describe below don't line up). 

What happens is that the library encounters an error in https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go#L315

It then looses its leadership but remains in the the renew loop here https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go#L223

It is actually trying to acquire a lock in `tryAcquireOrRenew()` that it lost but it thinks it never lost it and is renewing. So `OnStoppedLeading()` is never called. This results in the container reporting the wrong leader because `OnStoppedLeading` never was called. This leads to a possibly dangerous split-brain scenario.

From looking at the code `OnNewLeader` does not have this problem. But the `OnStoppedLeading` callback is broken.

**Comment by cevian** [comment] 2016-04-01 14:50
@mikedanese Since you are listed as the owner of the leaderelection client.

**Comment by zhouhaibing089** [comment] 2016-04-01 15:18
I did try the leader election for kube-controller-manager and kube-scheduler weeks ago, it works really well for me..

**Comment by cevian** [comment] 2016-04-01 15:25
Just to clarify: It works well for me too most of the time. This is not a common error. Saw it just once --- but it is potentially dangerous due to split-brain.

**Comment by mikedanese** [comment] 2016-04-01 15:39
It will retry for the renew deadline in https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go#L223 which is by design. The client should retry potentially transient errors within the renew deadline. Which component's logs are those? postgres-system-1?

**Comment by cevian** [comment] 2016-04-01 16:31
Ahh I see how it works now. The logs are from the election container ((https://github.com/kubernetes/contrib/tree/master/election). Postgres-system-1 and 0 are simply the id names. I now think the bug is in a different spot. It's probably a race condition inside the container. Namely, between the callback here: https://github.com/kubernetes/contrib/blob/master/election/lib/election.go#L83:
and the start of the leaderelection client here:
https://github.com/kubernetes/contrib/blob/master/election/lib/election.go#L122

Pretty much postgres-system-1 was the leader when the original leader was queried here:

**Comment by quinton-hoole** [comment] 2016-04-11 21:35
Assign to @mikedanese to confirm my prioritization.

**Comment by mikedanese** [comment] 2016-04-11 21:38
Yup this may be a bug in the code in the leaderelection sidecar in contrib/. We should investigate and fix it (I have not yet had time to) but this doesn't affect master component leader election.

**Comment by timothysc** [comment] 2016-07-28 19:26
@cevian Is this still an issue for you?  This seems like it should be a bug in contrib... 

If so I'd move to close this one, and re-open there.

**Comment by cevian** [comment] 2016-07-28 21:26
Honestly haven't used the sidecar because of this bug. I agree it is more of a contrib issue. Fine by me if you close this. There is a contrib bug on this already #690. I'll update that with my latest thoughts.

**Closed** 2016-07-28 21:30 UTC
Labels: area/HA, priority/P3, team/control-plane

**Comment by ostrain** [comment] 2018-05-30 22:05
I think I just hit this same bug. I found this issue via google. For what it's worth the link above to the contrib bug is incorrect; the actual link is: https://github.com/kubernetes/contrib/issues/690
