### ISSUE TITLE
Kubernetes 1.28 builds fail on Fedora 38, 39, and 40 (rawhide)

### ISSUE THREAD

**Issue by buckaroogeek** [kubernetes/kubernetes#119955] opened 2023-08-15 22:37 UTC
### What happened?

K8S v1.28 rpm builds fail on Fedora 38, 39, and rawhide. These are builds using the establish rpm spec file to create the kubernetes rpms in Fedora. The spec file calls kube::golang::setup_env which is where the error occurs. The error occurs in the new ./hack/tools/ncpu tool.

It is important to note that the spec file sets ```export FORCE_HOST_GO=y```. Fedora 40/39 current provide golang 1.21.0; Fedora 38 provides golang 1.20.7. 

With Fedora 39 and rawhide the following is observed in the build output:

```
++ go env GOROOT
+ GOROOT=/usr/lib/golang
+ export GOROOT
+ unset GOBIN
+ export GO15VENDOREXPERIMENT=1
+ GO15VENDOREXPERIMENT=1
+ command -v ncpu
+ pushd /builddir/build/BUILD/kubernetes-855e7c48de7388eb330da0f8d9d2394ee818fb8d/src/k8s.io/kubernetes/hack/tools
+ GO111MODULE=on
+ go install ./ncpu
go: downloading go.uber.org/automaxprocs v1.5.2
ncpu/main.go:23:2: GOPROXY list is not the empty string, but contains no entries
++ kube::log::errexit
++ local err=1
++ set +o
++ grep -qe '-o errexit'
++ set +o xtrace
!!! [0815 13:36:21] Call tree:
!!! [0815 13:36:21]  1: /var/tmp/rpm-tmp.rP6APk:57 kube::golang::setup_env(...)
error: Bad exit status from /var/tmp/rpm-tmp.rP6APk (%build)
```

With Fedora 38 the following is observed:
```
++ go env GOROOT
+ GOROOT=/usr/lib/golang
+ export GOROOT
+ unset GOBIN
+ export GO15VENDOREXPERIMENT=1
+ GO15VENDOREXPERIMENT=1
+ command -v ncpu
+ pushd /builddir/build/BUILD/kubernetes-855e7c48de7388eb330da0f8d9d2394ee818fb8d/src/k8s.io/kubernetes/hack/tools
+ GO111MODULE=on
+ go install ./ncpu
go: downloading go.uber.org/automaxprocs v1.5.2
ncpu/main.go:23:2: unrecognized import path "go.uber.org/automaxprocs": https fetch: Get "https://go.uber.org/automaxprocs?go-get=1": dial tcp: lookup go.uber.org: Temporary failure in name resolution
++ kube::log::errexit
++ local err=1
++ set +o
++ grep -qe '-o errexit'
++ set +o xtrace
!!! [0815 14:58:17] Call tree:
!!! [0815 14:58:17]  1: /var/tmp/rpm-tmp.wkPWUg:54 kube::golang::setup_env(...)
error: Bad exit status from /var/tmp/rpm-tmp.wkPWUg (%build)
```

### What did you expect to happen?

Something similar to the successful build of K8S 1.27.4 at the same stage in the build process:

```
++ go env GOROOT
+ GOROOT=/usr/lib/golang
+ export GOROOT
+ unset GOBIN
+ export GO15VENDOREXPERIMENT=1
+ GO15VENDOREXPERIMENT=1
+ export KUBE_GIT_TREE_STATE=clean
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Fedora 38 (current release) 
2. sudo dnf install fedora-packager fedora-review
3.  Checkout the fedora rpm repo for kubernetes and update spec file for v1.28
4. Build.

### Kubernetes version

Problem building Kubernetes 1.28

### Cloud provider

N/A

### OS version

Fedora uses a chrooted build environment so these data may not be accurate for building F39 and 40.
<details>

```console
$ cat /etc/os-release

NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ uname -a
Linux pico 6.4.10-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 11 12:20:29 UTC 2023 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

Please let me know what I can do to help resolve!

Many thanks

**Comment by sftim** [comment] 2023-08-15 23:11
Official Kubernetes packages are available from pkgs.k8s.io

Do the .spec files from within https://github.com/kubernetes/release/tree/master/cmd/kubepkg/templates/latest/rpm work OK?

**Comment by buckaroogeek** [comment] 2023-08-15 23:29
It appears that the spec files from https://github.com/kubernetes/release/tree/master/cmd/kubepkg/templates/latest/rpm package up a prebuilt binary with associated configuration files. This is unlike the spec file used by Fedora which builds the target binaries with the version of golang each Fedora release includes.  It will take some time to try one of these spec files but I do not see anything unusual so do not expect issues.

It could well be that something in the Fedora golang configuration or use of Kubernetes build tools in the spec file is the root cause. 

These build error showed up in the ncpu routine that is new in 1.28.

**Comment by sftim** [comment] 2023-08-16 08:17
I recommend filing an issue against Fedora. So far as I know, the Kubernetes project does not maintain the Fedora package build code.

**Comment by liggitt** [comment] 2023-08-16 13:20
added in https://github.com/kubernetes/kubernetes/pull/117016

I agree we probably don't want to put things like this in the build path... in code generation or verify tools, that's more ok, but the build target should be hermetic

**Comment by liggitt** [comment] 2023-08-16 13:21
> Yeah, I assume the value of GOPROXY is not parsable in rawhide since they use go 1.21, we're still on 1.20.7:

that doesn't make sense to me... go1.21 should honor any GOPROXY setting go1.20.x did, right?

**Comment by saschagrunert** [comment] 2023-08-16 13:40
> > Yeah, I assume the value of GOPROXY is not parsable in rawhide since they use go 1.21, we're still on 1.20.7:
> 
> that doesn't make sense to me... go1.21 should honor any GOPROXY setting go1.20.x did, right?

@buckaroogeek can we get the value of `GOPROXY` within the rawhide build env?

**Comment by liggitt** [comment] 2023-08-16 13:43
I think the GOPROXY message is confusing, but might just be saying it was set in a way to disallow network fetches (non-empty, but doesn't contain entries). This is likely a duplicate of https://github.com/kubernetes/kubernetes/issues/119768, and would be resolved by https://github.com/kubernetes/kubernetes/pull/119977

**Comment by buckaroogeek** [comment] 2023-08-16 15:49
> It seems like an IPv6 DNS lookup is being attempted and refused (no ipv6 on this workstation)? I can `wget https://proxy.golang.org/go.uber.org/automaxprocs/@v/v1.5.2.zip` without any problem.
> 

Just speculation. Should the go.uber.org/automaxprocs code be included in the ./vendor subdirectory?

**Comment by liggitt** [comment] 2023-08-16 15:57
> Should the go.uber.org/automaxprocs code be included in the ./vendor subdirectory?

no, that's for code that actually gets built/linked into releases binaries

this module is only used to build an optional utility used to set up the environment when running some tests. https://github.com/kubernetes/kubernetes/pull/119977 and the 1.28 cherry-pick will resolve the issue

**Comment by liggitt** [comment] 2023-08-17 14:39
https://github.com/kubernetes/kubernetes/pull/119982 is merged so HEAD of release-1.28 will build without trying to install this tool

**Closed by liggitt** 2023-08-17 14:39 UTC
Labels: kind/bug, sig/release, needs-triage

**Comment by buckaroogeek** [comment] 2023-08-17 15:10
Thanks to all for the quick review and response.  Much appreciated.

best regards

**Comment by liggitt** [comment] 2023-08-17 15:44
> It is important to note that the spec file sets `export FORCE_HOST_GO=y`. Fedora 40/39 current provide golang 1.21.0; Fedora 38 provides golang 1.20.7.

I will note that building Kubernetes on go minor versions other than what is tested is not really something I would recommend. Kubernetes stays on supported go minor versions now, and will update the release-1.28 branch to go1.21 in the future once soak criteria are met.

**Comment by buckaroogeek** [comment] 2023-08-17 16:20
Thanks for the insights. The current spec file used to build the Kubernetes binaries in Fedora uses a ```BuildRequires``` setting to set the version of Go used in the build. For example:

```
BuildRequires: golang >= 1.20.7
```

The value set is always equal to the 'built with' note in the Kubernetes change log. If the Fedora release has a newer version of Go (e.g. Go 1.21) then the maintainer has to make sure that the minor release present in Fedora contains the changes present in the 'built with' minor release. (hope I am being clear).
