### ISSUE TITLE
CronJob can run immediately on schedule changes

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kubernetes#65457] opened 2018-06-26 00:55 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Updating a `CronJob` schedule to a date/time _after_ the last successful run will cause the job to trigger immediately.

**What you expected to happen**:
The `CronJob` would not trigger until the schedule is satisfied; behaving similar to the creation of a new CronJob.

I understand that `startingDeadlineSeconds` means k8s will try to make up for a missed run by default, but the two problems with that behavior is:
1. It's different than the behavior when creation a CronJob, which never runs immediately.
2. It's unclear what times are considered _missed_ as I was unable to reproduce this using a time "before" (based on the UTC time before midnight) the `lastScheduleTime`. If this is the behavior when the schedule is changed, it should be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a CronJob with a `* * * * *` schedule so that it triggers once (without a `startingDeadlineSeconds`)
* Change the schedule to something _before_ the CronJob's `lastScheduleTime`
* Wait for at least a couple minutes to pass
* Update the CronJob schedule to be a time between the `lastScheduleTime` and the current time.
* See that the CronJob runs, even if it is many hours before the current time

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3

**Comment by jaygorrell** [comment] 2018-06-26 00:59
@kubernetes/sig-apps-bugs

**Comment by ceshihao** [comment] 2018-06-28 10:08
The bug is because `cronjob-controller` would like to run crons for unmet schedule times.
https://github.com/kubernetes/kubernetes/blob/efeb20492227261261d1af2e61babdbbe17be951/pkg/controller/cronjob/utils.go#L96

And the function calculate unmet schedule times from `LastScheduleTime` in this update case.
https://github.com/kubernetes/kubernetes/blob/efeb20492227261261d1af2e61babdbbe17be951/pkg/controller/cronjob/utils.go#L103-L114

In your case, `LastScheduleTime` is `time1`, cron job's `UpdateTime` is `time3`, the new schedule meets the trigger condition on `time2` (unmet schedule times). 
`time1` < `time2` < `time3`

I wonder whether controller has to implement such a logic for unmet schedule times.
If yes, maybe it is more reasonable to calculate unmet schedule times from the later one of `UpdateTime` and `LastScheduleTime`.

**Comment by jaygorrell** [comment] 2018-06-28 13:00
Thanks for the explanation of what's going on.

I think something along those lines definitely makes sense. Essentially, I think it's safe to assume that when the job is updated, anything before the update time shouldn't be considered missed.

**Comment by soltysh** [comment] 2018-07-04 13:35
I'm going to close this as a duplicate of #63371.

**Closed by soltysh** 2018-07-04 13:35 UTC
Labels: area/workload-api/cronjob, kind/bug, sig/apps
