### ISSUE TITLE
kubectl Apply or validate is not using the json field in output

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25106] opened 2016-05-03 22:19 UTC
While testing #23567, I created an internal and external field `InitContainers` on pods, but the json field name of external InitContainers was `alphaInitContainers` (while the internal name is `initContainers`.  All but one e2e test passed - that test failed due to an invalid initContainers field.  However, that field is not present in any external serialization or swagger, which means that apply or validate is using the internal object to apply incorrectly.

```
â€¢ Failure [42.642 seconds]
[k8s.io] Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
  [k8s.io] Kubectl apply
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
    should apply a new configuration to an existing RC [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:576

    Expected error:
        <*errors.errorString | 0xc820270360>: {
            s: "Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.162.114 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config apply -f - --namespace=e2e-tests-kubectl-g3kyj] []  0xc820ad8510  error validating \"STDIN\": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false\n [] <nil> 0xc820849220 exit status 1 <nil> true [0xc8201a8710 0xc8201a8748 0xc8201a8760] [0xc8201a8710 0xc8201a8748 0xc8201a8760] [0xc8201a8728 0xc8201a8740 0xc8201a8758] [0x984050 0x9841b0 0x9841b0] 0xc820a2a540}:\nCommand stdout:\n\nstderr:\nerror validating \"STDIN\": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false\n\nerror:\nexit status 1\n",
        }
        Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.162.114 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@2/.kube/config apply -f - --namespace=e2e-tests-kubectl-g3kyj] []  0xc820ad8510  error validating "STDIN": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
         [] <nil> 0xc820849220 exit status 1 <nil> true [0xc8201a8710 0xc8201a8748 0xc8201a8760] [0xc8201a8710 0xc8201a8748 0xc8201a8760] [0xc8201a8728 0xc8201a8740 0xc8201a8758] [0x984050 0x9841b0 0x9841b0] 0xc820a2a540}:
        Command stdout:

        stderr:
        error validating "STDIN": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false

        error:
        exit status 1

    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1629
------------------------------
```

**Comment by smarterclayton** [comment] 2016-05-03 22:19
@liggitt

**Comment by smarterclayton** [comment] 2016-05-04 02:07
@kubernetes/kubectl re: apply being broken because it is using internal objects when it should not be

**Comment by janetkuo** [comment] 2016-05-12 18:19
#23378

**Comment by AdoHe** [comment] 2016-06-13 09:53
@smarterclayton I thought this a bit, error here is because client side schema validation failed: `error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false`, but in #26840, I just got sever side validation error: `pod updates may not change fields other than`. I played with init containers, and can't get this client validation error, how can I reproduce this?

**Comment by smarterclayton** [comment] 2016-06-13 14:28
If you want to report this, remove the JSON serializations from the internal types.  Then you'll also get failures.

**Comment by smarterclayton** [comment] 2016-06-13 14:28
You should only have to remove the JSON struct tag from one or two fields under (for instance) `APIContainers` and regenerate the codecs.

**Comment by ivan4th** [comment] 2016-06-27 17:24
Didn't manage to reproduce the issue on current master. Also tried to add `panic()` traps to `func (x *Container) CodecDecodeSelf()` and `func (x *Handler) CodecEncodeSelf()` to pkg/api/types.generated.go and they aren't being hit by kubectl client code. Did domething change there?

**Comment by smarterclayton** [comment] 2016-06-27 18:33
No one has fixed this to my knowledge, and I don't see evidence of a fix.

**Comment by ivan4th** [comment] 2016-06-27 20:10
Were you using unmodified redis-master-controller.json for the test above, or did you add init containers to it? I've tried removing JSON tags from Volumes and Containers fields of PodSpec in pkg/api/types.go and doing `hack/update-codegen.sh` + rebuilding k8s, but to no avail.

**Comment by ivan4th** [comment] 2016-06-28 16:26
Sorry, managed to reproduce it after all.

**Comment by ivan4th** [comment] 2016-06-28 17:30
I'm working on this issue.

**Comment by ivan4th** [comment] 2016-06-28 19:51
Apparently this one's red herring after all! [Here's](https://github.com/kubernetes/kubernetes/blob/700fbd0543e38c610c124ae55e49039b2b34cca9/test/e2e/kubectl.go#L1316) the place in e2e tests themselves where internal representation is being used. That's why I was unable to reproduce the problem when not running e2e tests. Not quite sure it even needs to be fixed. Sample output after adding Printfs to `modifyControllerConfiguration()`:

```
*********************** contents: {
   "kind":"ReplicationController",
   "apiVersion":"v1",
   "metadata":{
      "name":"redis-master",
      "labels":{
         "app":"redis",
         "role":"master"
      }
   },
   "spec":{
      "replicas":1,
      "selector":{
         "app":"redis",
         "role":"master"
      },
      "template":{
         "metadata":{
            "labels":{
               "app":"redis",
               "role":"master"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"redis-master",
                  "image": "gcr.io/google_containers/redis:e2e",
                  "ports":[
                     {
                        "name":"redis-server",
                        "containerPort":6379
                     }
                  ]
               }
            ]
         }
      }
   }
}

*********************** data: {"kind":"ReplicationController","apiVersion":"v1","metadata":{"name":"redis-master","creationTimestamp":null,"labels":{"app":"redis","kubectl.kubernetes.io/apply-test":"ADDED","role":"master"}},"spec":{"replicas":1,"selector":{"app":"redis","kubectl.kubernetes.io/apply-test":"ADDED","ro
le":"master"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"redis","kubectl.kubernetes.io/apply-test":"ADDED","role":"master"}},"spec":{"Volumes":null,"Containers":[{"Name":"redis-master","Image":"gcr.io/google_containers/redis:e2e","ports":[{"name":"redis-server","containerPort":6379}],"resource
s":{},"imagePullPolicy":""}],"serviceAccountName":""}}},"status":{"replicas":0}}
```

**Comment by ivan4th** [comment] 2016-06-28 19:58
On second thought, it confused the hell out of me, so maybe I should fix the test.

**Comment by ivan4th** [comment] 2016-07-04 21:36
@smarterclayton as the issue turned out to be indeed present in apiserver code, I've submitted the PR above to fix it. It doesn't address the problem of internal repr usage in e2e test though, but that's semi-cosmetic issue that probably deserves an issue of its own.

**Comment by ivan4th** [comment] 2016-07-06 22:42
@smarterclayton @liggitt Included a test in #28577 that proves there's no int/ext mixup in the PATCH handler. On the client side, there's no such mixup either, [see](https://github.com/kubernetes/kubernetes/blob/c0b67b62b26279b42f7527f3a79966675ce9b541/pkg/kubectl/cmd/apply.go#L129) (toInternal=false is passed to `f.Decoder` below this line). The only place where v1/api objects are confused is the e2e test itself.

**Comment by liggitt** [comment] 2016-07-06 23:46
I was more questioning some of the branches in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/apply.go (like on line 141 where it appears to be doing an Encode of what may be an internal object, and persisting that as an apply annotation for future invocations of apply to work with)

**Comment by ivan4th** [comment] 2016-07-07 11:21
Please take a look at this gist to see what actually happens there: https://gist.github.com/ivan4th/ac9c1480c70672eaa87a66daff7d97e7
As you see, `VersionedObject` is non-nil and `info.Object` is an empty object. Also, internal representation is nowhere to be seen. The problem can be probably triggered
by passing a file containing internal object to kubectl apply (?) but I'm not sure about that and not sure that's a realistic use case.

**Comment by ivan4th** [comment] 2016-07-07 13:27
[Here](https://github.com/kubernetes/kubernetes/blob/acda24ae256cd9888f84002c135bef37fcc770b7/pkg/kubectl/cmd/apply.go#L176) info.Object which is internal is passed to `patcher.patch()` where it gets passed to `patcher.patchSimple()` but [there](https://github.com/kubernetes/kubernetes/blob/acda24ae256cd9888f84002c135bef37fcc770b7/pkg/kubectl/cmd/apply.go#L230) it gets serialized back into v1 representation (see gist above for related debug output). So actually internal repr indeed isn't used and the [second branch](https://github.com/kubernetes/kubernetes/blob/acda24ae256cd9888f84002c135bef37fcc770b7/pkg/kubectl/apply.go#L124) in big `if` in `GetModifiedConfiguration()` you were probably speaking about isn't used during normal operation (again, maybe an internal object needs to be passed to `kubectl apply` to hit this branch, but not sure about it)

**Comment by liggitt** [comment] 2016-07-07 13:53
> the second branch in big if in GetModifiedConfiguration() you were probably speaking about isn't used during normal operation 

which makes me think we are not exercising or testing it well, and when we do hit it it may not be working correctly

**Comment by ivan4th** [comment] 2016-07-07 14:04
That's right, will try to add panic() there and run all the tests, but I just mean that #26840 is not actually related to this issue and my PR #28557 for it isn't blocked by it either.

**Comment by ivan4th** [comment] 2016-07-07 14:49
Hit it in `TestApplyMultipleObjectsAsList` in `apply_test.go`, but then again the internal object gets encoded into external repr there: https://gist.github.com/ivan4th/388dd4af13bccab41471a643f0105e75

**Comment by AdoHe** [comment] 2016-07-18 02:56
@ivan4th I am just a little bit confused, could you please explain what's the root cause here?

**Comment by ivan4th** [comment] 2016-07-19 20:46
@AdoHe The behaviour described in this issue is caused by [this line](https://github.com/kubernetes/kubernetes/blob/700fbd0543e38c610c124ae55e49039b2b34cca9/test/e2e/kubectl.go#L1316) in an e2e test. That's why I was unable to reproduce the problem at first (I tried to use `kubectl apply` on some yaml files). There's also another ["trojan" line](https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/apiserver/apiserver_test.go#L134) in one of the tests that can cause unexpected internal/external representation mixup in tests (fixed in #29034). I tried adding a lot of debug print to k8s code to catch the elusive "mixup" both on client and server side only to come to the conclusion that it only happens in tests. So in the end that's actually just a problem with tests.

**Comment by AdoHe** [comment] 2016-07-20 00:06
@ivan4th thanks for detailed explanation.

**Comment by liggitt** [comment] 2016-12-11 01:08
Possibly resolved in #38406

**Comment by grodrigues3** [comment] 2017-03-10 21:43
@liggitt can you verify if this was resolved

**Comment by liggitt** [comment] 2017-03-10 23:21
Yes. Fixed.

**Closed by liggitt** 2017-03-10 23:21 UTC
Labels: area/app-lifecycle, area/declarative-configuration, area/kubectl, kind/bug, priority/important-soon, team/ux (deprecated - do not use)

**Comment by devth** [comment] 2017-04-28 17:32
Not sure this if this is directly related but trying to apply a deployment with initContainers errors:

```
failed to create patch: unable to find api field in struct PodSpec for the json field "initContainers"
```
on 1.6.1.

**Comment by liggitt** [comment] 2017-04-28 17:37
@devth what does `kubectl version` show?

**Comment by devth** [comment] 2017-04-28 17:42
Ah, locally I have 1.6.1 but in CI it was using 1.5.3 (apparently `google/cloud-sdk` is stuck at 1.5.3). Will upgrade. Thanks!

**Comment by devth** [comment] 2017-04-28 18:49
@liggitt still errors after upgrading kubectl:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct PodSpec for the json field "initContainers"
```

This is via Helm 2.3.1.

**Comment by liggitt** [comment] 2017-04-28 18:55
it looks like helm 2.3.1 is locked to kubernetes 114f8911f9597be669a747ab72787e0bd74c9359 (which is v1.5.6)
