### ISSUE TITLE
Cannot get *client.Config to load properly - s/mergo.Merge/mergo.MergeWithOverwrite/ update needed

### ISSUE THREAD

**Issue by peter-edge** [kubernetes/kubernetes#12272] opened 2015-08-05 14:17 UTC
UPDATED IN NEXT COMMENT, needs a PR

I have tried a bunch of different things for an hour, and this is what I have found.

I have kubectl authenticated properly to a GCE cluster per the https://cloud.google.com/container-engine/docs/clusters/operations docs.

```
gcloud auth login
gcloud components update beta
gcloud components update kubectl
gcloud config set project PROJECT
gcloud config set compute/zone ZONE
gcloud beta container clusters create NAME --zone ZONE
gcloud config set container/cluster NAME
```

Where `PROJECT, NAME, and ZONE` are all set to a GCE project I control. `${HOME}/.kube/config` shows my GCE setup as the only cluster and user, and the context as the current context (ie I have not touched it otherwise).

I have tried the following code in a golang app:

```
    clientConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
        clientcmd.NewDefaultClientConfigLoadingRules(),
        &clientcmd.ConfigOverrides{},
    ).ClientConfig()
    if err != nil {
        return err
    }
    client, err := client.New(clientConfig)
    if err != nil {
        return err
    }
    versionInfo, err := client.ServerVersion()
    if err != nil {
        return err
    }
    fmt.Printf("%+v\n", versionInfo)
```

I have also tried this, just to see if I can replicate what kubectl is doing:

```
    factory := util.NewFactory(nil)
    client, err := factory.Client()
    if err != nil {
        return err
    }
    versionInfo, err := client.ServerVersion()
    if err != nil {
        return err
    }
    fmt.Printf("%+v\n", versionInfo)
```

In both cases, I get an error at `client.ServerVersion()`:

```
Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connection refused
```

I did some investigation/a lot of `debug.PrintStack()` and `fmt.Println(...)`, and I have found out that everything basically gets messed up here: https://github.com/GoogleCloudPlatform/kubernetes/blob/ded48a376107a66abb374e38ec6fc1d48e66678e/pkg/client/clientcmd/client_config.go#L296 which is due to `mergo.Merge` only merging unfilled values, and https://github.com/GoogleCloudPlatform/kubernetes/blob/ded48a376107a66abb374e38ec6fc1d48e66678e/pkg/client/clientcmd/client_config.go#L36 already having filled in the host. So this seems wrong to me, I can't figure out a better way.

Here's where things get really weird though:

I've gotten kubectl from the following sources (I'll reference the numbers below):
1. From gcloud and put on my path per the GCE docs, at `${HOME}/google-cloud-sdk/bin/kubectl`
2. From releases, at https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/darwin/amd64/kubectl
3. From checking out tag `v1.0.1` and doing `make all WHAT=cmd/kubectl GOFLAGS=-v`
4. From checking out tag `v1.0.1` and doing `go get -d -v -t ./cmd/kubectl/... && go install ./cmd/kubectl`
5. From `master` and doing `make all WHAT=cmd/kubectl GOFLAGS=-v`
6. From `master` and doing `go get -d -v -t ./cmd/kubectl/... && go install ./cmd/kubectl`

(1), (2), (3), and (5) all work:

```
# sample output from (5)
$ ./_output/local/bin/darwin/amd64/kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1279+ded48a376107a6", GitCommit:"ded48a376107a66abb374e38ec6fc1d48e66678e", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

(4) and (6) do not work:

```
# sample output from (6)
$ ~/go/bin/kubectl version
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused
```

So,
- What gives? I'm assuming it's something to do with a dependency, but that actually makes no sense unless it's mergo.
- The docs for how to use kubernetes from golang don't work/having to rely on the Godeps dependencies when this is a library gets wonky.

Any thoughts? Am I missing something huge and about to have egg on my face (probably)?

**Comment by peter-edge** [comment] 2015-08-05 14:31
I did some more investigation, and I found the issue:

https://github.com/imdario/mergo/compare/6633656539c1639d9d78127b7d47c622b5d7b6dc...master (the reference there is the one referenced in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/Godeps.json).

mergo added an "overwrite" concept, which means values are not being overridden. If I go to mergo and checkout that specific revision, and then do `go install ./cmd/kubectl`, that build works properly.

So we need to update godeps to mergo master, and update the kubernetes source code to use `mergo.MergeWithOverwrite` instead of `mergo.Merge` in the following places (this is just a grep for every usage):

```
$ agg mergo\\\.Merge
pkg/client/clientcmd/client_config.go:112:		mergo.Merge(clientConfig, userAuthPartialConfig)
pkg/client/clientcmd/client_config.go:118:		mergo.Merge(clientConfig, serverAuthPartialConfig)
pkg/client/clientcmd/client_config.go:138:	mergo.Merge(mergedConfig, configClientConfig)
pkg/client/clientcmd/client_config.go:176:		mergo.Merge(mergedConfig, promptedConfig)
pkg/client/clientcmd/client_config.go:177:		mergo.Merge(mergedConfig, previouslyMergedConfig)
pkg/client/clientcmd/client_config.go:271:		mergo.Merge(&mergedContext, configContext)
pkg/client/clientcmd/client_config.go:273:	mergo.Merge(&mergedContext, config.overrides.Context)
pkg/client/clientcmd/client_config.go:284:		mergo.Merge(&mergedAuthInfo, configAuthInfo)
pkg/client/clientcmd/client_config.go:286:	mergo.Merge(&mergedAuthInfo, config.overrides.AuthInfo)
pkg/client/clientcmd/client_config.go:296:	mergo.Merge(&mergedClusterInfo, DefaultCluster)
pkg/client/clientcmd/client_config.go:297:	mergo.Merge(&mergedClusterInfo, EnvVarCluster)
pkg/client/clientcmd/client_config.go:299:		mergo.Merge(&mergedClusterInfo, configClusterInfo)
pkg/client/clientcmd/client_config.go:301:	mergo.Merge(&mergedClusterInfo, config.overrides.ClusterInfo)
pkg/client/clientcmd/loader.go:137:	mergo.Merge(config, mapConfig)
pkg/client/clientcmd/loader.go:138:	mergo.Merge(config, nonMapConfig)
pkg/client/clientcmd/loader.go:210:	mergo.Merge(startingConfig, config)
```

I can do this if a maintainer is up for me doing it?

**Comment by dchen1107** [comment] 2015-08-05 21:11
@peter-edge thanks for looking into the issue, and a pr to fix the issue is very welcome.

**Comment by peter-edge** [comment] 2015-08-05 21:13
np, see the linked one :) it was pretty easy

**Comment by smarterclayton** [comment] 2017-06-01 17:58
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 17:58 UTC
Labels: kind/cleanup, priority/backlog, sig/api-machinery
