### ISSUE TITLE
Allow wildcards in resourceNames field of RBAC Roles

### ISSUE THREAD

**Issue by sbalinen** [kubernetes/kubernetes#93845] opened 2020-08-10 08:13 UTC
With helm3 secrets are being used as a default storage driver. I want to give the service account delete permissions only on the secrets being created by HELM but not others as mentioned below but this is not working. Any particular reason why wildcards are not allowed currently?

- apiGroups: [""]
   resources: ["secrets"]
   resourceNames: ["sh.helm.release.*"]
   verbs: ["delete"]

**Comment by liggitt** [comment] 2020-08-10 21:58
> Any particular reason why wildcards are not allowed currently?

Thanks for the feature request. You can see the previous discussion on adding partial matching on resourcenames and the primary reason it was declined at https://github.com/kubernetes/kubernetes/issues/56582

> Subdividing access on name prefix isn't a strong subdivision. Permissions that allowed access to a pods for a deployment named "my" would also allow access to pods for a deployment named "my-app"

Subdividing access within a namespace (e.g. "access to deployment foo and all `foo-` pods, but not access to deployment bar and all `bar-` pods in the same namespace") is not recommended. sig-auth's recommendation is either to grant access to a particular set of named resources, or all instances of that resource in a namespace

**Comment by liggitt** [comment] 2020-08-10 21:58
cc @kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment] 2020-08-10 21:59
/close

duplicate of #56582

**Closed** 2020-08-10 21:59 UTC
Labels: kind/feature, sig/auth
