### ISSUE TITLE
e2e flake: slow and unreliable image pulling

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#25277] opened 2016-05-06 19:13 UTC
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25054/kubernetes-pull-build-test-e2e-gce/38681/

```
I0506 03:07:01.272055    3411 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-horizontal-pod-autoscaling-8t5zw", Name:"rc-light-t62w5", UID:"99a46e33-1337-11e6-86e3-42010af00002", APIVersion:"v1", ResourceVersion:"1167", FieldPath:"spec.containers{rc-light}"}): type: 'Normal' reason: 'Pulling' pulling image "gcr.io/google_containers/resource_consumer:beta2"
I0506 03:12:12.616384    3411 server.go:611] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-horizontal-pod-autoscaling-8t5zw", Name:"rc-light-t62w5", UID:"99a46e33-1337-11e6-86e3-42010af00002", APIVersion:"v1", ResourceVersion:"1167", FieldPath:"spec.containers{rc-light}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "gcr.io/google_containers/resource_consumer:beta2"
```

**Comment by roberthbailey** [comment] 2016-05-08 07:03
@yujuhong is this fixed?

**Comment by yujuhong** [comment] 2016-05-09 17:01
No, not that I know of. There were some efforts (e.g., tag the image) dedicated to alleviate this problem, but it's hard to completely eliminate the flake without pre-pulling the images.
It might be worth figuring out what's closing the slow down (e.g., network bandwidth, slow registry, etc)

**Comment by bprashanth** [comment] 2016-05-13 18:21
This seems to be the core cause of multiple flakes in the flaky test list, and it's a pain to keep debugging the same thing (https://github.com/kubernetes/kubernetes/issues/25333, https://github.com/kubernetes/kubernetes/issues/25479, https://github.com/kubernetes/kubernetes/issues/24782)

@kubernetes/sig-node should we break and retry? are we at the point of using the new docker client that allows this. Maybe the reason for disabling parallel image pulls isn't a problem anymore, and enabling them will help? 

@kubernetes/sig-testing bit the bullet and do: https://github.com/kubernetes/kubernetes/issues/21449?

**Comment by yujuhong** [comment] 2016-05-13 19:04
> @kubernetes/sig-node should we break and retry? are we at the point of using the new docker client that allows this. Maybe the reason for disabling parallel image pulls isn't a problem anymore, and enabling them will help?

@Random-Liu recently added timeouts for docker operations and it's currently in use. The timeout is set to two minutes. For image pulling, this is set for the response time to the request, not for the subsequent layer pulling/downloading. We should probably ignore flakes older than a week, before the timeout went live. 

That said, we have already seen tests hitting this new timeout as well. I am not sure how many tests could tolerate the retry time (2min+backoff), so we may need to shorten the docker operation timeout/backoff, or bump the test timeouts.

As for serialized image pulling, it had its own timeout problems because tests were run in parallel, and they'd be blocked by pulling the images. It'd be even harder to estimate how long the timeout should be for tests in this case because it highly depends on what other tests are running at the same time.

**Comment by bprashanth** [comment] 2016-05-13 19:42
If we cache images it would also fix the gcr.io flake cases like https://github.com/kubernetes/kubernetes/issues/21990

**Comment by Random-Liu** [comment] 2016-05-13 23:30
Also ref #25408

**Comment by bprashanth** [comment] 2016-05-14 04:20
In this failure of gce-slow: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5568?pli=1

It looks like we pulled with the bad image to force backoff, then changed the image to a valid nginx to see that backoff was reset. Only, pulling timed out with the nginx as well. 

We should probably do something smarter here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pods.go#L1002, like check that it at least pulled once. That would prove that the backoff isn't reset.

**Comment by bprashanth** [comment] 2016-05-14 22:55
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16905

```
STEP: Waiting for a default service account to be provisioned in namespace
[It] Should scale from 1 pod to 2 pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:89
STEP: Running consuming RC rc-light via replicationController with 1 replicas
...
May 14 15:20:03.773: INFO: rc-light Pods: 1 out of 1 created, 0 running, 1 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
May 14 15:20:13.773: INFO: rc-light Pods: 1 out of 1 created, 0 running, 1 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
May 14 15:20:23.773: INFO: rc-light Pods: 1 out of 1 created, 0 running, 1 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
...
May 14 15:20:24.308: INFO: At {2016-05-14 15:18:14 -0700 PDT} - event for rc-light-hxmx0: {default-scheduler } Scheduled: Successfully assigned rc-light-hxmx0 to jenkins-e2e-minion-sk84
May 14 15:20:24.308: INFO: At {2016-05-14 15:18:18 -0700 PDT} - event for rc-light-hxmx0: {kubelet jenkins-e2e-minion-sk84} Pulling: pulling image "gcr.io/google_containers/resource_consumer:beta2"
May 14 15:20:24.308: INFO: At {2016-05-14 15:20:18 -0700 PDT} - event for rc-light-hxmx0: {kubelet jenkins-e2e-minion-sk84} Failed: Failed to pull image "gcr.io/google_containers/resource_consumer:beta2": net/http: request canceled
May 14 15:20:24.308: INFO: At {2016-05-14 15:20:18 -0700 PDT} - event for rc-light-hxmx0: {kubelet jenkins-e2e-minion-sk84} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "rc-light" with ErrImagePull: "net/http: request canceled"
```

**Comment by Random-Liu** [comment] 2016-05-15 02:04
I look into the log a bit. In the kubelet.log on jenkins-e2e-minion-sk84, we could see:
```
E0514 22:20:00.598207    3398 pod_workers.go:183] Error syncing pod b6fa2a88-1a21-11e6-bd76-42010af00002, skipping: failed to "StartContainer" for "redis-master" with ErrImagePull: "net/http: request canceled"
```
And in docker.log, at 2 minutes ago, we could see:
```
time="2016-05-14T22:18:00.569279628Z" level=info msg="GET /images/redis/json?size=1" 
time="2016-05-14T22:18:00.569543433Z" level=error msg="Handler for GET /images/redis/json returned error: No such image: redis" 
time="2016-05-14T22:18:00.569611596Z" level=error msg="HTTP Error" err="No such image: redis" statusCode=404
```

**Comment by bprashanth** [comment] 2016-05-15 02:11
The issue might be that one such gcr.io flake 404 puts the container into backoff, which hits the test timeout. But we *know* that image exists.

**Comment by Random-Liu** [comment] 2016-05-15 02:45
@bprashanth I found that the 404 error should be caused by an `ImageInspect` before pulling [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/image_puller.go#L83). Because the image is not present, docker daemon returns a 404, which is normal.

And after that, docker did start to pull the image
```
time="2016-05-14T22:18:00.628176753Z" level=info msg="POST /images/create?fromImage=redis&tag=latest"
```
So it seems that we need to investigate more, :(

**Comment by bprashanth** [comment] 2016-05-15 04:24
Eitherway in the normal case image pull takes < 1m. Almost all tests poll for the standard 5m till running+ready, if > 2m goes in pulling the image we *might* make the deadline. If it takes 2m, fails, goes into backoff and retries for 2m, we're probably not going to make it.

**Comment by bprashanth** [comment] 2016-05-15 20:15
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16967
```
STEP: Waiting for Redis master to start.
May 15 12:40:46.167: INFO: Selector matched 1 pods for map[app:redis]
May 15 12:40:46.167: INFO: Found 0 / 1
...
May 15 12:42:15.152: INFO: Selector matched 1 pods for map[app:redis]
May 15 12:42:15.152: INFO: Found 0 / 1
May 15 12:42:15.152: INFO: WaitFor completed with timeout 1m30s.  Pods found = 0 out of 1
May 15 12:42:15.154: INFO: Selector matched 1 pods for map[app:redis]
..
STEP: Collecting events from namespace "e2e-tests-kubectl-qoo5f".
May 15 12:42:15.159: INFO: At {2016-05-15 12:40:45 -0700 PDT} - event for redis-master: {replication-controller } SuccessfulCreate: Created pod: redis-master-x18jy
May 15 12:42:15.159: INFO: At {2016-05-15 12:40:45 -0700 PDT} - event for redis-master-x18jy: {default-scheduler } Scheduled: Successfully assigned redis-master-x18jy to jenkins-e2e-minion-rxhy
May 15 12:42:15.159: INFO: At {2016-05-15 12:40:46 -0700 PDT} - event for redis-master-x18jy: {kubelet jenkins-e2e-minion-rxhy} Pulling: pulling image "redis"
```

And in node logs, https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce/16967/artifacts/jenkins-e2e-minion-rxhy/kubelet.log: 
```
I0515 19:38:38.666821    3401 server.go:627] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-kubectl-w0kym", Name:"redis-master-mmpr7", UID:"9e8f488b-1ad4-11e6-b1d8-42010af00002", APIVersion:"v1", ResourceVersion:"3613", FieldPath:"spec.containers{redis-master}"}): type: 'Normal' reason: 'Pulling' pulling image "redis"
...
I0515 19:42:29.343224    3401 server.go:627] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-kubectl-qoo5f", Name:"redis-master-x18jy", UID:"ea865370-1ad4-11e6-b1d8-42010af00002", APIVersion:"v1", ResourceVersion:"5672", FieldPath:"spec.containers{redis-master}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "redis"
```

**Comment by fejta** [comment] 2016-05-23 23:04
Assigning to @bprashanth per https://github.com/kubernetes/kubernetes/pull/25784 (nice!)

**Comment by yujuhong** [comment] 2016-05-23 23:12
See also https://github.com/kubernetes/kubernetes/issues/26075#issuecomment-221122556

The 2min image pulling timeout that was added to kubelet has been causing the "net/http: request canceled" errors.
This also prevents any image to be pulled if it takes > 2 mins. I am sending a PR to disable it for now.

**Comment by yujuhong** [comment] 2016-06-10 17:39
> The 2min image pulling timeout that was added to kubelet has been causing the "net/http: request canceled" errors.
> This also prevents any image to be pulled if it takes > 2 mins. I am sending a PR to disable it for now.

This was fixed long ago. 

Have we seen any more image pulling issues for test pods (i.e., non-kube-system pods)? If not, I think we can close this one since there are multiple issues tracking potential, long-term solutions already.

**Comment by jszczepkowski** [comment] 2016-06-16 08:47
I'm still observing problems with pulling images in HPA e2e tests: #27196 and #27443.

**Comment by jszczepkowski** [comment] 2016-06-16 09:03
> I'm still observing problems with pulling images in HPA e2e tests: #27196 and #27443.

It turned out the resource consumer (used by HPA e2e tests) was not in the correct version in image puller, I'm fix it with #27531.

**Comment by bprashanth** [comment] 2016-06-26 00:04
We can keep this open for gke image pulling flake, till we either start running the image puller on gke or root cause the flake/run a local registry. Marking p2 though.

**Comment by bprashanth** [comment] 2016-08-29 21:39
Not seen much image pulling flake lately, closing

**Closed by bprashanth** 2016-08-29 21:39 UTC
Labels: area/test, kind/flake, priority/P2, team/none
