### ISSUE TITLE
Jobs aren't Marked as Complete with Sidecars

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kubernetes#73118] opened 2019-01-21 01:28 UTC
I'm not sure if this is a bug, design issue, or feature request, so starting with a bug report.

**What happened**:
Jobs aren't getting marked as Successful if they have sidecar containers, such as the Envoy Proxy injected by Istio.

**What you expected to happen**:
When the container that is declared as part of the job completes successfully, the job should be marked as successful. This works without Istio's sidecar proxy injected.

I've reported this as an Istio issue [#11045](https://github.com/istio/istio/issues/11045), but I don't think it's really an Istio issue, as much as it's Kubernetes that's not marking the Job successful.

I wonder if I'm observing the following: The Kubernetes controller that manages Job completion, is perhaps checking the status of _all containers_ within the pod, and until it finds _all_ are complete, it does not mark the Job successful. So sidecars, which is designed to run continuously, such as the Envoy Proxy, could be preventing Jobs from ever getting marked as successful.

Perhaps a feature request to address this would be to add a field to the Job's resource called something like: `completionContainers`, which would contain a list of container names which are the only ones to be checked to determine Job success (and/or failure). That way, we could specify which container names actually do the run-to-completion work, causing Kubernetes to ignore any that we don't want, such as those injected by Istio.

**How to reproduce it (as minimally and precisely as possible)**:
1. Retrieve [this example yaml](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/controllers/job.yaml) from the first example in these [kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/).
2. Execute `kubectl create -f job.yaml` in a Cluster and Namespace that includes Istio.
3. The core container as described in the above yaml completes in just seconds, but the notice that the Job doesn't ever get marked as successful.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- Install tools:
Kops
- OS (e.g. from /etc/os-release):
As provided by Kops.
- Kernel (e.g. `uname -a`):
As provided by Kops.

**Comment by pluttrell** [comment] 2019-01-21 04:03
@kubernetes/sig-apps-bug

**Comment by Joseph-Irving** [comment] 2019-01-21 10:03
Hey, this looks like a dupe of https://github.com/kubernetes/kubernetes/issues/25908. 

There is currently a proposal attempting to address this issue see https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md

**Comment by Shnatsel** [comment] 2019-01-21 11:45
If this is indeed a duplicate of #25908, please continue discussion there and close this issue.

Thanks for the detailed bug report!

**Closed** 2019-01-21 22:07 UTC
Labels: kind/bug, needs-sig
