### ISSUE TITLE
Master in scalability suite for 1.7 branch does not come up

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#49005] opened 2017-07-17 06:56 UTC
It happened 3 times in a row. Last failure:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1-7/93

@kubernetes/sig-scalability-bugs @wojtek-t @shyamjvs

**Comment by wojtek-t** [comment] 2017-07-17 07:18
However, gci-scalability is passing - this is probably some configuration issue.

**Comment by shyamjvs** [comment] 2017-07-17 09:30
Seems to be some problem with stopping the docker daemon (as iirc we change docker config and then restart it):

```
Starting Docker Application Container Engine...
...bla bla
Started Docker Application Container Engine.
<and the log ended>
```

(ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1-7/91/artifacts/e2e-scalability-1-7-master/docker.log)

While usually after this we have the following:

```
Stopping Docker Application Container Engine...
time="2017-07-14T06:49:51Z" level=info msg="stopping containerd after receiving terminated"
time="2017-07-14T06:49:51.833238240Z" level=info msg="Processing signal 'terminated'"
docker daemon exited
Stopped Docker Application Container Engine.
Starting Docker Application Container Engine...
```

(ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1-7/90/artifacts/e2e-scalability-1-7-master/docker.log)

cc @kubernetes/sig-node-bugs

**Comment by wojtek-t** [comment] 2017-07-17 09:33
Why we are not seeing it in any other tests then?

**Comment by shyamjvs** [comment] 2017-07-17 09:36
Trying to figure out

**Comment by shyamjvs** [comment] 2017-07-17 12:22
This seems to not happen for any other release 1.7 jobs I checked, even ones with debian as the node OS (though it doesn't really matter as the master is still gci).
For e.g - https://k8s-testgrid.appspot.com/release-1.7-all#gce-release-1-7

**Comment by shyamjvs** [comment] 2017-07-17 12:23
I triggered the job manually and checking what is the problem live.

**Comment by shyamjvs** [comment] 2017-07-17 12:27
It seems to magically work now and TBH I have no idea why. Seems to be some transient failure, though let's wait to check if it passes for some runs before closing the issue.

**Comment by shyamjvs** [comment] 2017-07-17 14:28
It failed again for the timer triggered run - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1-7/95
This is strange as it passed on manual trigger and I checked that the only args that are different for kubetest across both are:

```
'BUILD_CAUSE=TIMERTRIGGER'
'ROOT_BUILD_CAUSE_TIMERTRIGGER=true'
'BUILD_CAUSE_TIMERTRIGGER=true'

vs

'BUILD_CAUSE=MANUALTRIGGER'
'ROOT_BUILD_CAUSE_MANUALTRIGGER=true'
'BUILD_CAUSE_MANUALTRIGGER=true'
```

@kubernetes/test-infra-maintainers Seems like some pure jenkins issue. I'll try to reproduce this.

**Comment by krzyzacy** [comment] 2017-07-17 17:31
scalability 1.6 and 1.7 are sharing the same project and in Jenkins they are blocking each other, so manual trigger might cause conflict.

But from the log the only thing is `Cluster failed to initialize within 300 seconds.`, is there anything more descriptive we can find?

**Comment by shyamjvs** [comment] 2017-07-17 17:52
Yup. I manually triggered while the other test wasn't running. And iiuc if we trigger a job manually it should still block (or be blocked by) any blocked (or blocking) test. Is that true?

> But from the log the only thing is Cluster failed to initialize within 300 seconds., is there anything more descriptive we can find?

The previous failures (91, 92, 93, 95) seem to be due to docker not restarting, but I'm not super sure if that's the reason. Also run 98 (which was timer-triggered) succeeded and the current one (100) is going smoothly, but 99 failed (but this wasn't due to docker failure as the master components started (see [logs](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-release-1-7/99/artifacts/e2e-scalability-1-7-master/)) and it seems like the apiserver just didn't get enough time to start). Seems flaky on timer trigger.

**Comment by krzyzacy** [comment] 2017-07-17 17:58
cc @ixdy for Jenkins ¯\_(ツ)_/¯

**Comment by ixdy** [comment] 2017-07-17 22:23
I don't see anything that suggests this is related to Jenkins or test-infra in particular.

**Comment by shyamjvs** [comment] 2017-07-17 22:31
The job seems stable now https://k8s-testgrid.appspot.com/google-gce-scale#gce-1.7 and it might be some transient gce-side issues (though I'm not very sure about it).
Will wait for a few more runs and close the issue if it goes fine.

**Comment by shyamjvs** [comment] 2017-07-18 11:28
There a few failures again (108-111) but that's a different issue explained here - https://github.com/kubernetes/test-infra/pull/3561

**Comment by shyamjvs** [comment] 2017-07-18 21:34
This issue is now fixed and we have it all green - https://k8s-testgrid.appspot.com/google-gce-scale#gce-1.7

**Closed by shyamjvs** 2017-07-18 21:34 UTC
Labels: kind/bug, priority/failing-test, sig/node, sig/scalability
