### ISSUE TITLE
Supporting multiple API prefixes

### ISSUE THREAD

**Issue by uluyol** [kubernetes/kubernetes#10009] opened 2015-06-18 07:24 UTC
## Introduction

Continued from #7111 and #2306 (also relevant: #3806, #6363).

There is a strong desire for kubernetes to support multiple API prefixes. This would allow us to split to the API into a more logical structure and introduce support for an experimental API prefix. Additionally, we would like to separately version different parts of the API and provide sensible scoping rules for API objects.

OpenShift serves its own objects separately from kubernetes objects using the /osapi endpoint. However, it registers its objects under the kubernetes api.Scheme (instead of a separate runtime.Scheme) and is forced to follow the kubernetes version numbers. Moreover, OpenShift's "kinds" must be unique to avoid clashing with those in kubernetes. We would like a more general approach to avoid these limitations.

## Proposed Hierarchy

To achieve this, the api could have the following hierarchy: provider/apigroup/version/kind with the following properties:
* Any version/kind should be convertible to the corresponding version/kind within the same API group
* API groups within the same provider should be able to refer to objects within other groups. This is needed for things like namespaces and lists, as well as experimental API groups.

In the existing API server, a runtime.Scheme somewhat approximates a provider/apigroup, while an apiserver.APIGroupVersion corresponds to a version.

## Challenges
* Much of the code assumes that only one prefix, runtime.Scheme, and related structures exist. This is especially problematic for things like namespaces.
* Referring to types in other runtime.Schemes requires that they (along with conversion and defaulting functions) be registered with the current runtime.Scheme and version.
* The master does core API-specific work ([link](https://github.com/GoogleCloudPlatform/kubernetes/blob/15596ede41adf72ba5eac66404732be0c7f3c3b0/pkg/master/master.go#L458))
* Registering new prefixes/versions/objects requires dealing with too many things (see #2306 and #7111)

**Comment by uluyol** [comment] 2015-06-18 07:26
@lavalamp @bgrant0607 @smarterclayton @derekwaynecarr

**Comment by bgrant0607** [comment] 2015-06-19 01:34
The plugin issues are also somewhat relevant, so I'll ref them here: #991, #3201

**Comment by bgrant0607** [comment] 2015-06-19 01:41
Pointing out a minor detail: If we add more fields to the API schema, we'll want to populate them automatically so that the user doesn't have to, in the server (#3000) and/or client.

We probably could punt on provider for now, since there would only be different values for systems that didn't use Kubernetes conventions/tooling, such as Docker, cloud providers, etc.

**Comment by bgrant0607** [comment] 2015-06-19 01:49
Some hypothetical API groups, to test proposals against:
* end-user core objects: pod, pod template, secret, persistent volume claim, service
* higher-level end-user objects: replication controller, daemon (future), deployment (future), job (future)
* app admin objects: namespace, limit range, resource quota, service account
* system objects: event, endpoints, component status, resource stats (future)
* infrastructure / cluster admin objects: node, persistent volume
* experimental apis

**Comment by smarterclayton** [comment] 2015-06-19 02:19
Might want to split services off - if there are other control objects and policies around them they could potentially be big enough to be distinct (ie Openshift routes, external IPs or load balancers, affinity policies, etc).  That said, they're fairly self contained.

**Comment by bgrant0607** [comment] 2015-06-19 04:16
Re. services: Good point. 

Also sort-of relevant: #1451, #1744, #2306

Worth looking at:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/register.go

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/runtime/scheme.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/runtime/scheme_test.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/runtime/embedded_test.go

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/scheme.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/scheme_test.go

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd_test.go

https://github.com/openshift/origin/blob/master/pkg/image/api/v1/register.go

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L723
https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go#L583

What do we need per API group?

At least api.Scheme (which is a runtime.Scheme) and the corresponding conversion.Scheme.

m.storage (master.go).

**Comment by bgrant0607** [comment] 2015-06-19 05:04
This would benefit from #9971

**Comment by bgrant0607** [comment] 2015-06-19 05:09
From in-person discussion: All api groups will need to respect namespaces, for objects that should be namespaced.

**Comment by smarterclayton** [comment] 2015-06-19 14:44
Another desired feature: in the future, we should be able to easily run subsets of the apiserver independently.  That might cut across api groups, or only expose specific APIs (like the proxy and passthrough logging systems).

**Comment by bgrant0607** [comment] 2015-06-19 18:43
I agree, but don't know that we need to tackle subsets as part of this effort.

Another consideration: We need to continue to expose v1 as a single API group. We might need to decouple the effort to add new API groups from splitting the existing monolithic group. Or, maybe everything should go into the same Scheme, which would then have a sparse conversion matrix, so that the same entity could be exposed via multiple API groups. In the objects, we'd add apiGroup as a separate field (in TypeMeta), but in the version maps we'd prefix the version keys with their API groups. We have previously added objects (PodTemplate) that haven't exposed API paths in all API versions.

**Comment by bgrant0607** [comment] 2015-06-19 20:43
Candidates for experimental API prefix:
* Daemon #1518
* Deployment #1743
* RuntimeConfig #6477

**Comment by bgrant0607** [comment] 2015-06-19 20:44
Those could also be plugins, I suppose.

**Comment by bgrant0607** [comment] 2015-06-19 21:51
Probably need to fix #1490

**Comment by lavalamp** [comment] 2015-06-24 00:04
> However, it registers its objects under the kubernetes api.Scheme (instead of a separate runtime.Scheme) and is forced to follow the kubernetes version numbers. Moreover, OpenShift's "kinds" must be unique to avoid clashing with those in kubernetes. 

I don't understand this part. Scheme doesn't care if version matches across objects or not, and you can register a kind with whatever name you want, you don't have to use the name of the go object.

**Comment by lavalamp** [comment] 2015-06-24 00:09
If we make multiple schemes, we'd need a scheme registry (for people to find the scheme for their object), which seems like an awfully tall meta stack.

So instead consider making scheme provider aware. I'm not convinced that group needs special treatment, that just seems like window dressing apiserver tacks on.

Another reason to make scheme provider aware is so that you can mount the same object in multiple prefixes and have our encode/decode/convert code understand that it is the same object and doesn't need conversion.

**Comment by uluyol** [comment] 2015-06-24 00:59
>
> However, it registers its objects under the kubernetes api.Scheme (instead
> of a separate runtime.Scheme) and is forced to follow the kubernetes
> version numbers. Moreover, OpenShift's "kinds" must be unique to avoid
> clashing with those in kubernetes.
>
> I don't understand this part. Scheme doesn't care if version matches
> across objects or not, and you can register a kind with whatever name you
> want, you don't have to use the name of the go object.
>
OpenShift needs to refer to kubernetes objects (if nothing else, those in
api.{Type,Object}Meta, and as things stand, this requires being in the same
version as those objects. OpenShift could use a different version number,
but then the same objects would have to be re-registered under that version
along with conversion and copy functions.

**Comment by smarterclayton** [comment] 2015-06-24 03:16
That's definitely the biggest pain point today.    I'm provisionally ok with locking our top API to a Kube consistent scheme, but for objects that update more rapidly it'll be hard to reuse type meta and object meta (if we want to split out our various object sets into multiple components that move upstream or into their own projects, for example).

We can fork the simple types but the deep types (pod spec, part of deployment) are uglier.

**Comment by lavalamp** [comment] 2015-06-24 18:34
> OpenShift needs to refer to kubernetes objects (if nothing else, those in api.{Type,Object}Meta, and as things stand, this requires being in the same version as those objects

I don't get why. ObjectReference has a version field?

**Comment by smarterclayton** [comment] 2015-06-24 20:17
The biggest reason so far is kind names.  Minion vs Node is undecidable if you go through enough version and you're referencing that object from something in a different API scheme (like hypothetical build API at version v3 referencing what node it ran on with Kind "Node")

**Comment by uluyol** [comment] 2015-06-24 20:25
> I don't get why. ObjectReference has a version field?

I was referring to adding a type from the kubernetes api to another version. I was mixed up about the copy/conversion functions. Those are only needed when using a separate Scheme not when using a different version number.

I went ahead and created a new test version with the following two types:

```
type Hello struct {
	api.TypeMeta   `json:",inline"`
	api.ObjectMeta `json:"metadata,omitempty"`

	Text     string              `json:"text,omitempty"`
	Text2    string              `json:"test,omitempty"`
	Template *v1.PodTemplateSpec `json:"template,omitempty"`
}

type HelloList struct {
	api.TypeMeta   `json:",inline"`
	api.ObjectMeta `json:"metadata,omitempty"`

	Items []Hello `json:"items,omitempty"`
}
```
In order to make things work, this required the following call
```
api.Scheme.AddKnownTypes("exp",
	&Hello{},
	&HelloList{},

	&api.DeleteOptions{},
	&api.Namespace{},
	&api.ListOptions{},
	&api.Status{},
)
```

This appears to work (with all of the hooks in the master and storage) and I can create Hello Objects under the new version. I had thought more registration was required but I suppose not.

**Comment by lavalamp** [comment] 2015-06-24 21:21
> The biggest reason so far is kind names.  Minion vs Node is undecidable if you go through enough version and you're referencing that object from something in a different API scheme (like hypothetical build API at version v3 referencing what node it ran on with Kind "Node")

I guess I must be dense today, because I still don't see what the issue is. So you reference minion:v1beta1. What is wrong with that? Can you give a concrete example? This is hard to reason about in the abstract.

I *can* see adding a provider to the type, e.g. kubernetes/minion:v1beta1. That makes a lot of sense.

**Comment by uluyol** [comment] 2015-06-25 00:44
[This post follows a discussion with bgrant0607 and lavalamp]

### Summary

Logically, an API object should be uniquely identifiable by an API provider, group, version, and kind. Having API groups allows for independent versioning of different components, while providers are responsible for serving multiple API groups. Supporting multiple providers is not a high priority, and so the focus will be on supporting multiple groups.

It should be possible to achieve this by making runtime.Scheme aware of API groups. Doing so would eliminate any need to have multiple Schemes allowing api.Scheme to continue being the single global instance.

First Steps:

1. All of the maps in runtime.Scheme (and conversion.Scheme) need to be extended to support groups. TypeMeta will also be given a new field: APIGroup.
1. A new struct, KindSpec will be introduced that holds the group, version, and kind. This way we can avoid have method names like ObjectGroupVersionAndKind or ObjectGroupVersionKind and reduce the number of arguments and return values.
1. Methods that will need trivial changes: AddKnownTypes, AddKnownTypeWithName, KnownTypes, DataVersionAndKind (should be renamed DataKindSpec, this will require changes to pkg/conversion/meta.go), ObjectVersionAndKind (likewise), Recognized, New, AddFieldLabelConversionFunc, and ConvertFieldLabel.
1. ConvertToVersion and EncodeToVersion may need modifications, but they will not accept the group as an argument. In other words, kinds may only be converted within groups, not across groups.

**Comment by lavalamp** [comment] 2015-06-25 01:00
To that I'd add:

* Cross-provider introspection is explicitly out of scope; different providers will not be served by the same binary, and a provider defines the rest of the hierarchy. The api group, version, kind tree applies just to the kubernetes provider.
* Our TypeMeta will be moved to an "unversioned" library, so that we can use the same object in every version. We expect that it's stabilized enough that we can do this without much risk of breaking old api versions.
* Is KindSpec going to be any different than TypeMeta? If not, let's just use that.

**Comment by uluyol** [comment] 2015-06-25 01:06
I didn't think of that, but yes they would be the same. The one issue with using TypeMeta is that it would cause an import cycle (api -> runtime, runtime -> api) unless it's moved out of the api package.

**Comment by lavalamp** [comment] 2015-06-25 01:11
Yeah, it should move to pkg/api/unversioned or pkg/api/versionless. But still runtime should not be importing anything under pkg/api, so you have a very good point. Hm. I'll think about it.

**Comment by uluyol** [comment] 2015-06-25 01:28
I should point out that it would be nice if pkg/conversion could import it as well since runtime.Scheme is mostly a thin wrapper around conversion.Scheme.

**Comment by uluyol** [comment] 2015-06-26 00:13
There actually is a runtime.TypeMeta. If we're not going to break, why not just use that everywhere?

**Comment by lavalamp** [comment] 2015-06-26 01:29
Hm-- I think that might be OK. @smarterclayton can you think of any reason not to?

**Comment by smarterclayton** [comment] 2015-06-26 03:15
Will catch up on thread tomorrow, back in office.

**Comment by smarterclayton** [comment] 2015-06-26 20:01
We already have MetaInsertionFactory in conversion that depends on a TypeMeta equivalent, so we should probably just use that.  It's somewhat opinionated (which is why it was in runtime instead before).  It's possible DefaultMetaFactory should be specified from runtime.NewScheme() instead of implicit in conversion/scheme.go - in which case, having runtime.TypeMeta be the thing we use makes a lot of sense.

**Comment by smarterclayton** [comment] 2015-06-26 20:01
I'm not sure I find KindSpec any better than TypeMeta - I would really prefer just to leave it as TypeMeta.  If we add group to that, that's fine.

**Comment by smarterclayton** [comment] 2015-06-26 20:04
What group are "api.Status" and "api.DeleteOptions" in?

**Comment by bgrant0607** [comment] 2015-06-26 21:39
We need to detangle our API machinery and our API spec -- pkg/api currently contains both.

That said, TypeMeta is in an interesting grey area, since all of our API machinery depends on it in practice.

Some of the REST mapping types may have non-serializable structs we could use for the in-memory representation. HOWEVER, I've also proposed that we eliminate the separate in-memory representation (https://github.com/GoogleCloudPlatform/kubernetes/issues/8190#issuecomment-114139999).

So we should probably consider TypeMeta as part of the machinery.

Status also likely falls into that category. At minimum, it's really unversioned, since we return that type even when the user doesn't specify a valid API version.

**Comment by bgrant0607** [comment] 2015-06-26 21:40
Couldn't/shouldn't DeleteOptions be versioned?

**Comment by smarterclayton** [comment] 2015-06-26 21:59
It doesn't really exist in one group - it's exposed in all groups.  But you would need to be able to convert it to one internal interface/struct so that all our common client status code can still work (i.e. reading values off the known type).  Client shouldn't know about group1/v1/Status, group2/v2/Status, group3/v3/Status, but someone has to know that group3/v3/Status == group2/v2/Status == group1/v1/Status such that conversions can happen to give the client one bit of code.

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-06-26 22:00
When user doesn't specify a version, sure - but our clients absolutely depend on status being versioned (the recent ID -> Name rename is an example).  Status unversioned needs to be defined *somehow* - even if that's implicitly choosing a version to respond with (and it can self identify)

----- Original Message -----

**Comment by uluyol** [comment] 2015-06-26 22:22
> We already have MetaInsertionFactory in conversion that depends on a TypeMeta equivalent, so we should probably just use that. It's somewhat opinionated (which is why it was in runtime instead before). It's possible DefaultMetaFactory should be specified from runtime.NewScheme() instead of implicit in conversion/scheme.go - in which case, having runtime.TypeMeta be the thing we use makes a lot of sense.

Assuming that we use runtime.TypeMeta everywhere, pkg/conversion would not be able to use it. Would it make sense to move SimpleMetaFactory along with DefaultMetaFactory into pkg/runtime then?

**Comment by bgrant0607** [comment] 2015-07-01 17:50
Quick note: We need to think about the syntax printed and accepted by kubectl. Currently it uses resource/name.

**Comment by smarterclayton** [comment] 2015-07-02 23:33
I think users will stab us if we force them to type long
group/version/names.  We may be able to get away with guessing group based
on resource, but it does seem fraught.

On Jul 1, 2015, at 1:50 PM, Brian Grant <notifications@github.com> wrote:

Quick note: We need to think about the syntax printed and accepted by
kubectl. Currently it uses resource/name.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-117764944>
.

**Comment by bgrant0607** [comment] 2015-07-14 19:12
I'm all for guessing based on resource.

**Comment by uluyol** [comment] 2015-07-14 19:29
I have run into an issue with api.Status. Because it is a versioned object, it needs to be converted to a versioned api, but with multiple groups, this conversion fails because the API group is inferred from the type. So if I have group "exp" with version "v0" the server will try to convert the api.Status to have group "api" and version "v0".

Here are two potential fixes:
* Allow objects to exist in multiple (or every group), and plumb the TypeMeta everywhere. Currently, it's kept clear to allow us to use struct literals. Using constructors or having defaulting methods would help here
* Make api.Status an unversioned object

I can't say that I like either solution.

**Comment by uluyol** [comment] 2015-07-14 19:30
@thockin

**Comment by bgrant0607** [comment] 2015-07-14 21:51
Status is defined as follows in v1:
```
type Status struct {
	TypeMeta `json:",inline"`
	ListMeta `json:"metadata,omitempty" description:"standard list metadata; see http://releases.k8s.io/HEAD/docs/api-conventions.md#metadata"`
	Status string `json:"status,omitempty" description:"status of the operation; either Success, or Failure; see http://releases.k8s.io/HEAD/docs/api-conventions.md#spec-and-status"`
	Message string `json:"message,omitempty" description:"human-readable description of the status of this operation"`
	Reason StatusReason `json:"reason,omitempty" description:"machine-readable description of why this operation is in the 'Failure' status; if this value is empty there is no information available; a reason clarifies an HTTP status code but does not override it"`
	Details *StatusDetails `json:"details,omitempty" description:"extended data associated with the reason; each reason may define its own extended details; this field is optional and the data returned is not guaranteed to conform to any schema except that defined by the reason type"`
	Code int `json:"code,omitempty" description:"suggested HTTP return code for this status; 0 if not set"`
}
type StatusDetails struct {
	Name string `json:"name,omitempty" description:"the name attribute of the resource associated with the status StatusReason (when there is a single name which can be described)"`
	Kind string `json:"kind,omitempty" description:"the kind attribute of the resource associated with the status StatusReason; on some operations may differ from the requested resource Kind; see http://releases.k8s.io/HEAD/docs/api-conventions.md#types-kinds"`
	Causes []StatusCause `json:"causes,omitempty" description:"the Causes array includes more details associated with the StatusReason failure; not all StatusReasons may provide detailed causes"`
	RetryAfterSeconds int `json:"retryAfterSeconds,omitempty" description:"the number of seconds before the client should attempt to retry this operation"`
}
```
I think I'm still in favor of making this unversioned, though I know we've changed StatusDetails in the past, and should likely make more changes to it (e.g., Name and Kind should be expanded to a larger subset of ObjectReference). We need to have a default type returned for completely bogus paths not corresponding to any valid group or api version, anyway.

**Comment by smarterclayton** [comment] 2015-07-14 22:11
ListOptions / DeleteOptions are shared across multiple API groups (and they
have conversions).  The version they are used with may not be in the same
version of their code.  Requiring those to be explicitly registered by type
and name in each group isn't the end of the world (unless I missed
something making that impossible).

On Jul 14, 2015, at 5:51 PM, Brian Grant <notifications@github.com> wrote:

Status is defined as follows in v1:

type Status struct {
    TypeMeta `json:",inline"`
    ListMeta `json:"metadata,omitempty" description:"standard list
metadata; see http://releases.k8s.io/HEAD/docs/api-conventions.md#metadata"`
    Status string `json:"status,omitempty" description:"status of the
operation; either Success, or Failure; see
http://releases.k8s.io/HEAD/docs/api-conventions.md#spec-and-status"`
    Message string `json:"message,omitempty"
description:"human-readable description of the status of this
operation"`
    Reason StatusReason `json:"reason,omitempty"
description:"machine-readable description of why this operation is in
the 'Failure' status; if this value is empty there is no information
available; a reason clarifies an HTTP status code but does not
override it"`
    Details *StatusDetails `json:"details,omitempty"
description:"extended data associated with the reason; each reason may
define its own extended details; this field is optional and the data
returned is not guaranteed to conform to any schema except that
defined by the reason type"`
    Code int `json:"code,omitempty" description:"suggested HTTP return
code for this status; 0 if not set"`
}
type StatusDetails struct {
    Name string `json:"name,omitempty" description:"the name attribute
of the resource associated with the status StatusReason (when there is
a single name which can be described)"`
    Kind string `json:"kind,omitempty" description:"the kind attribute
of the resource associated with the status StatusReason; on some
operations may differ from the requested resource Kind; see
http://releases.k8s.io/HEAD/docs/api-conventions.md#types-kinds"`
    Causes []StatusCause `json:"causes,omitempty" description:"the
Causes array includes more details associated with the StatusReason
failure; not all StatusReasons may provide detailed causes"`
    RetryAfterSeconds int `json:"retryAfterSeconds,omitempty"
description:"the number of seconds before the client should attempt to
retry this operation"`
}

I think I'm still in favor of making this unversioned, though I know we've
changed StatusDetails in the past, and should likely make more changes to
it (e.g., Name and Kind should be expanded to a larger subset of
ObjectReference). We need to have a default type returned for completely
bogus paths not corresponding to any valid group or api version, anyway.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-121402653>
.

**Comment by uluyol** [comment] 2015-07-15 19:17
> ListOptions / DeleteOptions are shared across multiple API groups (and they
have conversions).  The version they are used with may not be in the same
version of their code.  Requiring those to be explicitly registered by type
and name in each group isn't the end of the world (unless I missed
something making that impossible).

**Comment by uluyol** [comment] 2015-07-15 19:18
Sorry for the accidental post + closing.

**Comment by uluyol** [comment] 2015-07-16 19:08
> ListOptions / DeleteOptions are shared across multiple API groups (and they have conversions).  The version they are used with may not be in the same version of their code.  Requiring those to be explicitly registered by type and name in each group isn't the end of the world (unless I missed something making that impossible).

runtime.Scheme.ObjectVersionAndKind returns the version and kind based on the Go type, not the values in the object's TypeMeta ([link to code that handles this in pkg/conversion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/scheme.go#L384)). Registering the same Go type in multiple groups breaks this behavior. I don't think we can have multi-group objects unless we plumb the (group, version, kind) everywhere, in which case we might as well just populate the TypeMeta.

**Comment by smarterclayton** [comment] 2015-07-16 23:16
On Jul 16, 2015, at 3:08 PM, Muhammed Uluyol <notifications@github.com>
wrote:

ListOptions / DeleteOptions are shared across multiple API groups (and they
have conversions). The version they are used with may not be in the same
version of their code. Requiring those to be explicitly registered by type
and name in each group isn't the end of the world (unless I missed
something making that impossible).

runtime.Scheme.ObjectVersionAndKind returns the version and kind based on
the Go type, not the values in the object's TypeMeta (link to code that
handles this in pkg/conversion
<https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/scheme.go#L384>).
Registering the same Go type in multiple groups breaks this behavior. I
don't think we can have multi-group objects unless we plumb the (group,
version, kind) everywhere, in which case we might as well just populate the
TypeMeta.



This is why we support explicit registration today, and why SelfLinking
against a go type is somewhat fraught.  I don't think we should be
depending on the static go type to define an object group - I can think of
a ton of reasons to expose objects in multiple groups (such as experimental
API groups and stable API groups).  I think it's a mistake to not have to
call into the Scheme (and to provide context from the code) to determine
the group of an object.  What matters is the encoding (the serialization)
not the transient in memory representation of the go type.

Maybe I missed the example of why having the go type determine the group is
valuable?


—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-122052660>
.

**Comment by uluyol** [comment] 2015-07-16 23:52
How would ObjectVersionAndKind function (or the group-extended version)? It doesn't make sense to extract version or kind information without the group. Within conversion.Scheme we have maps that go from (version, kind) to go type and go type to (version, kind). Both of these are necessary to support ObjectVersionAndKind's functionality to identify them from just the go type and create new objects using the Scheme. You can extend the first map to identify a (group, version, kind) but then the second one no longer makes sense when a single object is in multiple groups. You could add a parameter with the group name and resolve it that way, but I don't see how that is any better than plumbing the full TypeMeta.

**Comment by smarterclayton** [comment] 2015-07-17 00:22
Rereading the thread, I think I'm missing a key point that led to the
proposal to separate group.  Brian or Dan, can you describe more why group
*must* be separate and not part of version?

If group is part of apiVersion, ObjectVersionAndKind continues to function
by returning the canonical version for an object (which can be changed
during encode as part of a no-op conversion).  Then the different groups
are just aliases of one another and we don't need to track the group
internally.  I.e. ("service/v1", "ListOptions") and ("pods/v2",
"ListOptions") can be decoded to the same object (which might canonically
be "common/v1"), and during encode we merely perform a conversion to
("pods/v2", "ListOptions").

On Jul 16, 2015, at 7:52 PM, Muhammed Uluyol <notifications@github.com>
wrote:

How would ObjectVersionAndKind function (or the group-extended version)? It
doesn't make sense to extract version or kind information without the
group. Within conversion.Scheme we have maps that go from (version, kind)
to go type and go type to (version, kind). Both of these are necessary to
support ObjectVersionAndKind's functionality to identify them from just the
go type and create new objects using the Scheme. You can extend the first
map to identify a (group, version, kind) but then the second one no longer
makes sense when a single object is in multiple groups. You could add a
parameter with the group name and resolve it that way, but I don't see how
that is any better than plumbing the full TypeMeta.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-122132832>
.

**Comment by lavalamp** [comment] 2015-07-24 23:04
I can't think of a good argument for keeping version & group separate levels of the hierarchy.

I was going to say that our conversion functions would only work in a group, but I don't think that's really a difficult problem to solve.

Maybe completeness is an argument? We need a way to capture a set of objects that work with each other, and I thought version was that mechanism. We don't want people to declare that their api consists of `group/v1.2/foo` and `group/v1.3/bar`. But I guess we can enforce that via convention.

**Comment by nikhiljindal** [comment] 2015-07-27 23:06
I went through this thread and I have a few questions:

- I see a lot of discussion regarding making TypeMeta unversioned, but do we have a decision? Either way, how does making TypeMeta unversioned help with this issue?
I liked @bgrant0607's comment regarding separating api machinery and the spec. runtime.TypeMeta is part of the machinery. Do we want to reuse it in the spec, if we decide to make TypeMeta unversioned?

- We need to decide if we want group as a separate field similar to version, or we update version to be "group/version" as proposed in https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-122135884

**Comment by bgrant0607** [comment] 2015-07-28 22:30
Making TypeMeta unversioned simplifies plumbing through the codebase. Logically, it HAS to be unversioned, so that we can figure out the apiVersion and kind of a given resource across all possible groups, versions, and kinds. For instance, let's say a resource specified "type" and "ver" instead of "kind" and "version". That seems like it would introduce a lot of complexity and ambiguity (esp. since we have some resources with "type" fields).

As for whether we should lump group with version...

Some possible groups and versions (groupings are plausible but group names are just examples):
compute/v1: Pod, PodTemplate, Secret, PersistentVolumeClaim
compute/v2alpha1: ConfigData
lb/v1: Service, Endpoints
lb/v2alpha1: Route
deploy/v1: ReplicationController
deploy/v2alpha1: Deployment, Job, ScheduledJob
admin/v1: Namespace, LimitRange, ResourceQuota, ServiceAccount
info/v1: Event, ComponentStatus
info/v2alpha1: PodStats, NodeStats
cluster/v1alpha1: Daemon
infrastructure/v1: Node, PersistentVolume
extension/v1alpha1: ThirdPartyResource
experimental/v1alpha1: DiurnalScaler

Yes, I suppose that could work. We desperately need this, so I'm all for expedience, provided it doesn't create obvious problems, and I don't see any.

**Comment by bgrant0607** [comment] 2015-07-28 22:34
And of course all the corresponding List resources.

**Comment by dchen1107** [comment] 2015-07-29 17:53
cc/ @krousey This one is related to what we talked about yesterday on API group and api.Status versioning or unversioning, etc.

**Comment by nikhiljindal** [comment] 2015-07-29 17:54
ok thanks @bgrant0607. I will review https://github.com/GoogleCloudPlatform/kubernetes/pull/10582 assuming that we are unversioning TypeMeta and are updating version to be group/version.
Thanks!

**Comment by fgrzadkowski** [comment] 2015-08-26 09:15
To be honest I don't what's the value of some many api groups. Why not start with something simple (like introducing experimental) and introduce new groups only if we see a good use-case for it?

**Comment by lavalamp** [comment] 2015-08-26 23:13
Assigning Chao for review, since he's working on this at the moment.

**Comment by davidopp** [comment] 2015-08-27 06:54
I think the categories could be made more intuitive with a slight renaming and slight aggregation. How about compute, network, storage, collection, admin, experimental, extension? For example

**compute:** Pod, PodTemplate
**network:** Service, Endpoints, Route (does Route exist?)
**storage:** PersistentVolumeClaim, PersistentVolume
**collection:** ReplicationController, Deployment, Job, ScheduledJob, Daemon
**admin:** Namespace, LimitRange, ResourceQuota, ServiceAccount, Event, ComponentStatus, PodStats, NodeStats, Node, ConfigData, Secret
**experimental:** DiurnalScaler
**extension:** ThirdPartyResource

**Comment by pmorie** [comment] 2015-08-27 15:51
Has anyone thought about the changes necessary to existing components that might want to work with new versions of an existing API group?

**Comment by derekwaynecarr** [comment] 2015-08-27 17:14
I get why we want the API groups, but we do lose something today where each segment of our URL returns a result of some kind, so from /api/v1/namespaces/x/pods/foo, I can chop off a segment and get back a meaningful result that helps make the API sensible.  So in the new model here, where you would have /compute/v1/namespaces/x/pods/foo, does /compute/v1/namespaces/x still return a meaningful result, or do I need to go to /admin/v1/namespaces/x?

**Comment by caesarxuchao** [comment] 2015-08-27 17:27
@derekwaynecarr @pmorie, let's move the talk to #12951, where we have a RFC proposal for API groups.

**Comment by caesarxuchao** [comment] 2015-08-27 17:33
I think we should only expose namespaces at /admin. My concern is the version. Imagine we have compute/v1alpha3/namespaces/x/pods/foo, but v1alpha3 does not exist in the admin group, what should we return for compute/v1alpha3/namespaces/x?

**Comment by nikhiljindal** [comment] 2015-08-27 17:33
@derekwaynecarr Here is what I think we can do for that:
You need to go to ```/admin/v1/namespaces/x``` to get the namespace x.
```/user/v1/namespaces/x``` returns all valid resources kinds that can be appended to that path, like:
```
ResourceList:
{
"pods",
"replicationControllers",
.
.
.
}
```
We have talked about returning a ResourceList before for ```/api/v1```: https://github.com/kubernetes/kubernetes/pull/7883#issuecomment-99968066

**Comment by caesarxuchao** [comment] 2015-08-27 17:44
I'm closing this issue. Let's continue the discussion in #12951.

**Closed by caesarxuchao** 2015-08-27 17:44 UTC
Labels: area/api, area/extensibility, kind/enhancement, priority/P1, team/control-plane, team/CSI
