### ISSUE TITLE
Federation on AWS does not add route53 A and AAAA alias for federated service

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes/kubernetes#36757] opened 2016-11-14 16:59 UTC
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.5 

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS Alpha 1221
- **Kernel** (e.g. `uname -a`): 4.8.6
- **Install tools**:
- **Others**:

**What happened**:

When adding a federated service to a federation API with aws route53 as a DNS provider, alias records are not added to the hosted-zone. With AWS, Load balancer does not return IP addresses but FQDN :

```
kubectl --context=federation-cluster describe services                                                                                             
Name:                   nginx
Namespace:              default
Labels:                 app=nginx
Selector:               app=nginx
Type:                   LoadBalancer
IP:
LoadBalancer Ingress:   a97974d3daa8711e692d7024e51f5899-1324458526.eu-west-1.elb.amazonaws.com, a97a93575aa8711e68c950ea3591b9e0-1980277648.us-east-1.elb.amazonaws.com
Port:                   http    80/TCP
Endpoints:              <none>
Session Affinity:       None
No events.%                                                                                     
```

In AWS it is not possible to add A records with IP to a Load Balancer, an alias should be used.

**What you expected to happen**:

With google cloud, LB return IP address : 

```
$kubectl --context=federation-cluster describe services nginx

Name:                   nginx
Namespace:              default
Labels:                 run=nginx
Selector:               run=nginx
Type:                   LoadBalancer
IP:         
LoadBalancer Ingress:   104.197.246.190, 130.211.57.243, 104.196.14.231, 104.199.136.89, ...
Port:                   http    80/TCP
Endpoints:              <none>
Session Affinity:       None
No events.
```
if you look at the documentation, A records are created :

```
gcloud dns record-sets list --zone example-dot-com
NAME                                                                                                 TYPE      TTL     DATA
example.com.                                                                                       NS     21600  ns-cloud-e1.googledomains.com., ns-cloud-e2.googledomains.com.
example.com.                                                                                      SOA     21600 ns-cloud-e1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 1209600 300
nginx.mynamespace.myfederation.svc.example.com.                            A     180     104.197.246.190, 130.211.57.243, 104.196.14.231, 104.199.136.89,...
nginx.mynamespace.myfederation.svc.us-central1-a.example.com.     A     180     104.197.247.191
nginx.mynamespace.myfederation.svc.us-central1-b.example.com.     A     180     104.197.244.180
nginx.mynamespace.myfederation.svc.us-central1-c.example.com.     A     180     104.197.245.170
nginx.mynamespace.myfederation.svc.us-central1-f.example.com. CNAME 180     nginx.mynamespace.myfederation.svc.us-central1.example.com.
nginx.mynamespace.myfederation.svc.us-central1.example.com.         A    180     104.197.247.191, 104.197.244.180, 104.197.245.170
nginx.mynamespace.myfederation.svc.asia-east1-a.example.com.       A    180     130.211.57.243
nginx.mynamespace.myfederation.svc.asia-east1-b.example.com.  CNAME 180     nginx.mynamespace.myfederation.svc.asia-east1.example.com.
nginx.mynamespace.myfederation.svc.asia-east1-c.example.com.       A    180     130.211.56.221
nginx.mynamespace.myfederation.svc.asia-east1.example.com.           A    180     130.211.57.243, 130.211.56.221
nginx.mynamespace.myfederation.svc.europe-west1.example.com.  CNAME    180   nginx.mynamespace.myfederation.svc.example.com.
nginx.mynamespace.myfederation.svc.europe-west1-d.example.com.  CNAME   180     nginx.mynamespace.myfederation.svc.europe-west1.example.com.
... etc.
```

On AWS only CNAME are created and not the records to access the service from the outside :

```
aws route53 list-resource-record-sets --hosted-zone-id Z30RXJ6808BKLW --output text
RESOURCERECORDSETS      nginx.default.federation.svc.eu-west-1a.eu-west-1.archifleks.xyz.       180     CNAME
RESOURCERECORDS nginx.default.federation.svc.eu-west-1.archifleks.xyz.
RESOURCERECORDSETS      nginx.default.federation.svc.eu-west-1.archifleks.xyz.  180     CNAME
RESOURCERECORDS nginx.default.federation.svc.archifleks.xyz.
RESOURCERECORDSETS      nginx.default.federation.svc.us-east-1.archifleks.xyz.  180     CNAME
RESOURCERECORDS nginx.default.federation.svc.archifleks.xyz.
RESOURCERECORDSETS      nginx.default.federation.svc.us-east-1a.us-east-1.archifleks.xyz.       180     CNAME
RESOURCERECORDS nginx.default.federation.svc.us-east-1.archifleks.xyz.

```
On AWS, we should have a record like this :

```
nginx.default.federation.svc.us-east-1.archifleks.xyz IN A dualstack.FQDN of US LB
nginx.default.federation.svc.eu-west-1.archifleks.xyz IN A dualstack.FQDN of EU LB
nginx.default.federation.svc.archifleks.xyz IN A dualstack.FQDN of both US and EU LB

and the same thing for AAAA records
```
**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by nikhiljindal** [comment] 2017-01-17 03:05
cc @kubernetes/sig-federation-misc @quinton-hoole

**Comment by quinton-hoole** [comment] 2017-01-17 05:00
@ArchiFleKs can you confirm whether this bug still exists in v1.5?  I'm pretty sure that it was fixed, but haven't had the time to dig out the relevant PR yet.

**Comment by quinton-hoole** [comment] 2017-01-17 06:00
It looks like the code to do the right thing is there, but perhaps it doesn't work correctly on AWS.

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L211

@justinsb I seem to remember us fixing something here, but can't find the PR.  Any ideas?

**Comment by quinton-hoole** [comment] 2017-01-17 06:07
According to the working group meeting notes of 11/17/2016, we should have federation e2e CI tests running against AWS (see below).  @colhom or @madhusudancs should have the current status.

http://tinyurl.com/ubernetes-wg-notes

```
11/17/2016:
E2e Testing (Colin Hom, Madhu)
https://k8s-testgrid.appspot.com/google-federation
AWS: Scripts are merged. Next step: enable in test grid.
Need to merge a test infra PR for Jenkins to start running these tests. Next step will be to add a tab to test grid.
Merged in kube repo. Test-infra PR is ready to be merged. 
```

**Comment by ArchiFleKs** [comment] 2017-01-17 07:43
@quinton-hoole : I'll try again with 1.5. From what i understand here https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L211

LB Endpoint are resolved, but i'm not sure AWS ELB resolved IP address are stable as opposed to GCP. If the DNS provider is route53, we should an AWS alias and not an A record

**Comment by quinton-hoole** [comment] 2017-01-17 17:32
Yes, you're right, and I don't think that that part is done yet.  There is
an issue for it somewhere.

Q

**Comment by nikhiljindal** [comment] 2017-05-22 19:14
Yes the problem is that we get IP addresses on GCP and domain name on AWS. And we cant have both A records and CNAME for same DNS entry as explained in https://github.com/kubernetes/kubernetes/issues/35637#issuecomment-256961669.
So we need to choose either one for hybrid scenarios.

Closing this as dup of https://github.com/kubernetes/kubernetes/issues/35637

**Closed by nikhiljindal** 2017-05-22 19:14 UTC
Labels: area/platform/aws, sig/federation, team/cluster (deprecated - do not use)
