### ISSUE TITLE
[k8s.io] Upgrade [Feature:Upgrade] [k8s.io] master upgrade should maintain responsive services [Feature:MasterUpgrade]

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32715] opened 2016-09-14 19:41 UTC
[k8s.io] Upgrade [Feature:Upgrade] [k8s.io] master upgrade should maintain responsive services [Feature:MasterUpgrade]

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-master

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.3-1.4-upgrade-master/595

**Comment by bprashanth** [comment] 2016-09-14 20:03
This is also the same quota issue, deleted, put in increase limit, lets see if it hits again

**Comment by davidopp** [comment] 2016-09-18 08:57
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-cvm-1.4-upgrade-master
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-gci-1.4-upgrade-master

**Comment by bprashanth** [comment] 2016-09-18 21:14
Fishy

Artifacts https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-gci-1.3-gci-1.4-upgrade-master/23/artifacts/gke-jenkins-e2e-default-pool-be9fee4d-xtea/

Build https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-gci-1.3-gci-1.4-upgrade-master/23/build-log.txt

Node name `gke-jenkins-e2e-default-pool-be9fee4d-xtea`
Pod name `service-test-714ep`
PodCIDR 
```
I0917 16:09:55.165803   29376 kubelet.go:3907] Setting Pod CIDR:  -> 10.16.0.0/24
I0917 16:09:55.166261   29376 kubenet_linux.go:225] CNI network config set to {
"cniVersion": "0.1.0",
"name": "kubenet",
"type": "bridge",
"bridge": "cbr0",
"mtu": 1460,
"addIf": "eth0",
"isGateway": true,
"ipMasq": false,
"ipam": {
"type": "host-local",
"subnet": "10.16.0.0/24",
"gateway": "10.16.0.1",
"routes": [
{ "dst": "0.0.0.0/0" }
]
}
}
```

Looks like we failed to start one pod because it kept failing readiness probes in both cases:
```
Sep 17 04:01:42.990: INFO: At 2016-09-17 03:56:51 -0700 PDT - event for 
service-test-714ep: {kubelet gke-jenkins-e2e-default-pool-be9fee4d-xtea} Unhealthy: 
Readiness probe failed: Get http://10.16.0.4:80/hostName: net/http: request canceled 
while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
AFAICT this isn't related to the upgrade, because the logs say we upgraded to "1.4.0-beta.6.6+0e7430128aba0d" *after* the timeout to on readiness probe

Also the kubelet itself was experiencing networking problems
```
E0917 10:59:45.052570    1221 kubelet.go:2913] Error updating node status, will
 retry: error getting node "gke-jenkins-e2e-default-pool-be9fee4d-xtea": Get 
https://104.154.96.245/api/v1/nodes/gke-jenkins-e2e-default-pool-be9fee4d-xtea: 
dial tcp 104.154.96.245:443: i/o timeout
```

Kubelet reported node ready
```
I0917 10:54:24.065211    1221 kubelet.go:2924] Recording NodeReady event 
message for node gke-jenkins-e2e-default-pool-be9fee4d-xtea
```

I'll have to dig into what the test framework is doing more closely, at first glance it looks like it's running a single test on 1.3, upgrading, then running remaining tests on 1.4, and the above test is the one that ran on 1.3.

**Comment by bprashanth** [comment] 2016-09-18 22:37
The logs seem to indicate that this is always (often?) the first test to run, because of which its the only test that suffers an upgrade event in between the test (i.e runs on 1.3, upgrade, verify on 1.4). Filed: https://github.com/kubernetes/kubernetes/issues/33005. Of course it should still work in the given scenario.

**Comment by davidopp** [comment] 2016-09-18 22:55
> because of which its the only test that suffers an upgrade event in between the test (i.e runs on 1.3, upgrade, verify on 1.4)

I don't understand - I thought the way these tests worked was that they did an upgrade then ran the e2es? So it runs + verifies on the same version?

**Comment by bprashanth** [comment] 2016-09-18 23:13
it looked like that was happening *during* the first test, or at least, I see `Server Version 1.3.8` just before the test, then the test runs, I see "Waiting for pods blah" then upgrade, then verify, and all other tests. Eg:
```
Sep 17 23:14:10.931: INFO: Found all 1 pods
Sep 17 23:14:10.931: INFO: Waiting up to 2m0s for 1 pods to be running and ready: [service-test-39z84]
Sep 17 23:14:10.931: INFO: Waiting up to 2m0s for pod service-test-39z84 status to be running and ready
Sep 17 23:14:10.965: INFO: Waiting for pod service-test-39z84 in namespace 'e2e-tests-cluster-upgrade-f3fxv' status to be 'running and ready'(found phase: "Pending", readiness: false) (34.069806ms elapsed)
Sep 17 23:14:12.968: INFO: Waiting for pod service-test-39z84 in namespace 'e2e-tests-cluster-upgrade-f3fxv' status to be 'running and ready'(found phase: "Running", readiness: false) (2.037381379s elapsed)
Sep 17 23:14:14.972: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [service-test-39z84]
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:14.972: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:14.975: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: Starting disruption
Sep 17 23:14:14.975: INFO: Getting real version for "ci/latest-1.4"
Sep 17 23:14:14.975: INFO: Running /workspace/kubernetes_skew/hack/get-build.sh [-v ci/latest-1.4]
v1.4.0-beta.7
Sep 17 23:14:16.006: INFO: Version for "ci/latest-1.4" is "v1.4.0-beta.7\n"
Sep 17 23:14:16.006: INFO: Upgrading master to "1.4.0-beta.7"
Sep 17 23:14:16.006: INFO: Running gcloud [container clusters --project=gke-up-g1-3-c1-4-up-mas --zone=us-central1-c upgrade jenkins-e2e --master --cluster-version=1.4.0-beta.7 --quiet]

                                                                                
Upgrading jenkins-e2e...STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:16.980: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:18.984: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:20.988: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:22.993: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:24.997: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
Sep 17 23:14:27.001: INFO: Testing HTTP reachability of http://104.198.47.143:80/echo?msg=hello
STEP: hitting the pod through the service's LoadBalancer
```

**Comment by davidopp** [comment] 2016-09-19 03:57
Maybe you can take a look at
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-upgrade.yaml
and
jenkins/e2e-image/e2e-runner.sh
and see if this is the expected behavior. 

My understanding is that the upgrade is supposed to finish before any of the tests are run. Maybe we are not properly waiting for the upgrade to finish, which would be bad.

**Comment by bprashanth** [comment] 2016-09-19 19:19
Yeah, looks like it uses this test to verify the upgrade is working: https://github.com/kubernetes/kubernetes/issues/33005#issuecomment-248075391

I can surely make it do what you said (first upgrade, the run all tests), but eitherway this test should probably work, though it is weird that we're treating it specially.

**Comment by bprashanth** [comment] 2016-09-20 01:56
I'm not too worried about this, we know a service survives cluster upgrade from manual testing and we're not forcing any other test through upgrade. Also it is mostly green in the 2 links posted above and in https://k8s-testgrid.appspot.com/google-1.2-1.3-upgrade#gke-cvm-1.2-cvm-1.3-upgrade-master, demoting to p1, would be good to get some debug time on it if anyone has cycles though.

**Comment by bprashanth** [comment] 2016-11-16 00:25
going to let mergebot reopen if necessary, should be fixed

**Closed by bprashanth** 2016-11-16 00:25 UTC
Labels: area/test, component/apiserver, kind/upgrade-test-failure, priority/P1, team/control-plane
