### ISSUE TITLE
`kubectl logs -f` print a lot of log history

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#13899] opened 2015-09-13 02:18 UTC
As described, when running `kubectl logs -f`, it prints all history before following logs.  Would it be better to just print few lines?

**Comment by feiskyer** [comment] 2015-09-14 09:35
#13911 add `--tail` option for `kubectl logs`

**Comment by bgrant0607** [comment] 2015-09-17 17:48
Dupe of #12447
PR in flight: #13780

**Closed by bgrant0607** 2015-09-17 17:48 UTC
Labels: component/kubectl, team/ux
