### ISSUE TITLE
kube-push.sh is broken due to unbound variable KUBE_TAR_URL

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15794] opened 2015-10-16 20:39 UTC
I tried to upgrade my cluster through hack/dev-build-and-push.sh, and failed due to endless error messages:

hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1
hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1
hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1

...

**Comment by dchen1107** [comment] 2015-10-16 20:41
cc/ @ihmccreery @mikedanese I suspect #15519 the culprit here.

**Comment by ihmccreery** [comment] 2015-10-16 20:53
Closing this as a duplicate of #15738.

**Comment by ihmccreery** [comment] 2015-10-16 20:54
#15793 is out to fix.

**Closed by ihmccreery** 2015-10-16 20:53 UTC
Labels: area/cluster-lifecycle, area/upgrade, priority/P0, team/control-plane
