### ISSUE TITLE
unit flake: pkg/client/record

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19268] opened 2016-01-04 21:19 UTC
```
==================
WARNING: DATA RACE
Read by goroutine 40:
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:459 +0x12a9
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 42:
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:440 +0x308
  k8s.io/kubernetes/pkg/client/record.(*testEventSink).Create()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:49 +0x6d
  k8s.io/kubernetes/pkg/client/record.recordEvent()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:169 +0x206
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartRecordingToSink.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:125 +0x223
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:227 +0x14e

Goroutine 40 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/client/record/_test/_testmain.go:70 +0x20f

Goroutine 42 (running) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:229 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartRecordingToSink()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:141 +0x9bc
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:447 +0xb4d
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc
==================
--- FAIL: TestWriteEventError (0.01s)
	event_test.go:460: case retry1: wanted 12, got 8 attempts
=== RUN   TestLotsOfEvents
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/655cdd17314260140227b70821d6e8c6ad622c55/kubernetes-pull-test-unit-integration/7928/build-log.txt

**Comment by saad-ali** [comment] 2016-01-05 15:34
Looks like a dupe of https://github.com/kubernetes/kubernetes/issues/19202

**Comment by gmarek** [comment] 2016-01-05 21:16
I'm not sure. Failure message seems similar, but I can't see full logs for #19202 to check if race stack was there as well. I'll close the second one, as this one is on the list.

**Comment by quinton-hoole** [comment] 2016-01-07 20:25
A different error with the same unit test.  Perhaps fix in the same debugging effort?


```
--- PASS: TestEventCorrelator (0.02s)
	events_cache_test.go:96: create-a-single-event - expectedEvent.Count is 1
	events_cache_test.go:96: the-same-event-should-just-count - expectedEvent.Count is 2
	events_cache_test.go:96: the-same-event-should-just-count-even-if-more-than-aggregate - expectedEvent.Count is 11
	events_cache_test.go:96: create-many-unique-events - expectedEvent.Count is 1
	events_cache_test.go:96: similar-events-should-aggregate-event - expectedEvent.Count is 1
	events_cache_test.go:96: similar-events-many-times-should-count-the-aggregate - expectedEvent.Count is 2
	events_cache_test.go:96: similar-events-whose-interval-is-greater-than-aggregate-interval-do-not-aggregate - expectedEvent.Count is 1
FAIL
FAIL	k8s.io/kubernetes/pkg/client/record	1.575s
=== RUN   TestTLSConfigKey
```

**Comment by krousey** [comment] 2016-01-07 21:58
Dupe of #19151, which I have a PR out now that fixes it. #19368

**Closed by krousey** 2016-01-07 21:58 UTC
Labels: kind/flake, priority/P1
