### ISSUE TITLE
Make daemonset pod urls available as environment variables

### ISSUE THREAD

**Issue by ashic** [kubernetes/kubernetes#47969] opened 2017-06-23 16:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

It can be useful to be able to hit daemonset pods with http requests from application containers. For example, if we wish to push metrics to the daemonset pod to forward them to something like influxdb. Currently, we can achieve this by specifying a static host port for the daemonset, and then using http://nodename:static-port/ for access. However, this does require a static port on the host.

It would be great if "full urls" for daemonset ports were available as environment variables like they are for services.

**Comment by kargakis** [comment] 2017-09-10 23:38
Dupe of https://github.com/kubernetes/kubernetes/issues/28610

**Closed by kargakis** 2017-09-10 23:38 UTC
Labels: kind/feature, sig/apps
