### ISSUE TITLE
Master is not working after downgrade

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#32337] opened 2016-09-08 23:54 UTC
Encountered some issue when exercising upgrade and downgrade master node. The following lists the steps 
1. Bring up a 1.3.6 cluster in GCE
2.  Upgrade the master to 1.4.0-alpha (cluster/gce/upgrade.sh -M v1.4.0-beta.0), verify master is running fine and the version is 1.4.0
3. Downgrade the master back to 1.3.6. Now master is no longer running correctly. Still be able to login the master with gcloud, but all related logs (etcd.log, cloud-init.log) are empty. Kubelet is not running.

**Comment by jingxu97** [comment] 2016-09-08 23:54
@dchen1107 Could you please help take a look?

**Comment by jingxu97** [comment] 2016-09-09 00:01
From journalctl, I can see some related error message

Sep 08 18:02:13 kubernetes-master systemd[387]: [/usr/lib/systemd/system/bindmount@.service:6] Failed to add required mount for, ignoring: %I

Sep 08 18:02:50 kubernetes-master kubelet[1335]: E0908 18:02:50.767150    1335 server.go:309] Failed running kubelet: unsupported eviction signal nodefs.available
Sep 08 18:02:50 kubernetes-master kubelet[1335]: unsupported eviction signal nodefs.available

**Comment by dchen1107** [comment] 2016-09-09 00:04
Looked at @jingxu97's master node together, and found that after downgrade to old version, Kubelet doesn't come up: 

```
Sep 09 00:01:54 kubernetes-master kubelet[11856]: E0909 00:01:54.379021   11856 server.go:309] Failed running kubelet: unsupported eviction signal nodefs.available
Sep 09 00:01:54 kubernetes-master kubelet[11856]: unsupported eviction signal nodefs.available
Sep 09 00:01:54 kubernetes-master systemd[387]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Sep 09 00:01:54 kubernetes-master systemd[387]: kubelet.service: Unit entered failed state.
Sep 09 00:01:54 kubernetes-master systemd[387]: kubelet.service: Failed with result 'exit-code'.
```

**Comment by vishh** [comment] 2016-09-09 00:10
This is a bug. Kubelet needs to warn and move on with invalid eviction configuration to support backwards compatibility. We need to fix this in v1.3 and v1.4.
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment] 2016-09-09 00:14
I am confused?  What is the upgrade/downgrade requirement that makes this a
bug?

**Comment by dchen1107** [comment] 2016-09-09 00:15
@vishh I don't think that is the root cause here.

The configuration change for Kubelet was introduced by https://github.com/kubernetes/kubernetes/pull/31545 for 1.4, but for 1.3 of kubelet it should use the old. To me, looks like downgrade only downgrade the master component and configurations, not kubelet binary here.

**Comment by derekwaynecarr** [comment] 2016-09-09 00:15
Shouldn't a downgrade also imply reverting to the prior versions set
configured flags?

**Comment by dchen1107** [comment] 2016-09-09 00:16
@derekwaynecarr Yes, downgrade did revert to the prior versions set configured flags, but not kubelet binary itself. Kubelet on that master node is still running 1.4 Kubelet. :-)

**Comment by derekwaynecarr** [comment] 2016-09-09 00:17
I think Dawn and I are saying the same thing.

**Comment by dchen1107** [comment] 2016-09-09 00:19
Yes, we are saying the same. Not eviction manager issue, not kubelet issue. 

Ok, to fix the issue, when we downgrade from 1.4 to 1.3 , we have to switch GCI image to 53 milestone since it is bundled with Kubelet binary. cc/ @adityakali @Amey-D Can you help with this one?

**Comment by vishh** [comment] 2016-09-09 00:29
Why can't the kubelet ignore (with warning) unsupported configuration instead of failing? Lock stepping config is ideal, but are we requiring it?

**Comment by vishh** [comment] 2016-09-09 00:29
@dchen1107 How are you performing the downgrade?

**Comment by dchen1107** [comment] 2016-09-09 00:31
@jingxu97 was the one performing the downgrade. I am just standby for any issues. ;-)

**Comment by dchen1107** [comment] 2016-09-09 00:45
@vishh you might have the luxury to ignore this unsupport configurations. But if one flag has semantic change from one version to another version, what to do?

**Comment by vishh** [comment] 2016-09-09 00:47
We should disallow such breaking changes IMO. Our policy right now is to
support flag semantics for at-least two versions before updating or
removing it.

**Comment by Amey-D** [comment] 2016-09-09 01:27
I'm not familiar with the upgrade / downgrade workflow.  Does it involve tearing down the current instance and recreating it based on the OS version selection logic in the target version?  For example, when downgrading from 1.4.0 to 1.3.6, does it recreate the instance based on the OS version selection logic in 1.3.6?

**Comment by jingxu97** [comment] 2016-09-09 05:06
@vishh I used the following command to downgrade the master from 1.4.0 to 1.3.6. I think I used v1.3.6 version of upgrade script, but I am not completely sure since I changed my setup afterwards (In upgrade doc, it mentioned we should use v1.3 version of upgrade script when downgrading)
 
cluster/gce/upgrade.sh -M v1.3.6

**Comment by dchen1107** [comment] 2016-09-09 05:47
@Amey-D Like what I mentioned above at:https://github.com/kubernetes/kubernetes/issues/32337#issuecomment-245782813

When downgrading to 1.3.6 in this test, the current instance is torn down including the boot disk which the OS (GCI image) is installed. But the target OS version is still point to gci-dev-54 as the following:
```
Source image
gci-dev-54-8743-3-0
```
https://github.com/kubernetes/kubernetes/pull/31830 was introduced the right fix to pick a specific GCI version by default on GCE to 1.4 which specify the 1.4 release with gci-dev-54. 

But 1.3 release and prior would pick up the latest GCI release on that milestone (53) at: https://github.com/kubernetes/kubernetes/blob/release-1.3/cluster/gce/util.sh#L40
If the downgrade workflow does use the same logic, we shouldn't run into the current issue. The fix should be simple to point to the right OS version (or GCI milestone) here. 

I will check how the downgrade is performance tomorrow. This issue should only affect Kubernetes on GCE when downgrading to 1.3.6 from 1.4. It shouldn't affect any other clusters including GKE.

**Comment by dchen1107** [comment] 2016-09-09 20:32
@jingxu97 re-ran the upgrade test from 1.3.6 to 1.4, then downgrade the cluster from 1.4 to 1.3.6 with the proper scripts. Her new test proved my hypothesis above. I am close this issue. 

@jingxu97 You are hitting a real known issue for upgrade / downgrade tests now: #32253.
To workaround that issue and speed up your test, you can patch your upstream branch with https://github.com/kubernetes/kubernetes/pull/32404

**Closed by dchen1107** 2016-09-09 20:32 UTC
Labels: area/os/gci, area/upgrade, component/apiserver, priority/P0, team/node
