### ISSUE TITLE
Feature request: env_file support

### ISSUE THREAD

**Issue by jpswade** [kubernetes/kubernetes#40001] opened 2017-01-17 09:36 UTC
I have created .env files for environments for use with docker-compose. It would be useful to have the same support in kubernetes yaml files to avoid having to reformat them.

* See: https://docs.docker.com/compose/env-file/

**Comment by fraenkel** [comment] 2017-01-17 13:07
Do you mean something like https://github.com/kubernetes/kubernetes/pull/38882 or something else?

**Comment by bgrant0607** [comment] 2017-01-20 03:03
Dupe of #8800

**Closed by bgrant0607** 2017-01-20 03:03 UTC
