### ISSUE TITLE
[DaemonSet] Considering run-once DaemonSet (Job DaemonSet)

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#50689] opened 2017-08-15 14:07 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Currently, only restart=always is allowed for DaemonSet

**What you expected to happen**:
Run once DasemonSet is also vey useful, for example, install CNI or flexvolume binaries on every node.

Exit status can be used to determine its lifecycle. It's like a Job DaemonSet. But I am not sure if we should introduce a new API object or refactoring DaemonSet is enough.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by resouer** [comment] 2017-08-15 14:20
This is equivalent to adding dead loop to end of scritps:

```
# do my magic job

while true; do
	sleep 3600;
done
```

**Comment by guangxuli** [comment] 2017-08-15 16:07
Reasonable. +1.
Not sure why the DaemonSet Proposal describe that kubelet reject DaemonSet objects with pod templates that don't have restartPolicy set to Always. May be i miss something.

**Comment by wenlxie** [comment] 2017-08-16 09:26
If the DaemonSet can run pod in the node when:
1. Node just add to the cluster
2. Node restart.
That would be awesome

**Comment by resouer** [comment] 2017-08-19 02:13
Yes, it's true this use case tend to be associated with Node change. And I think this behavior can be covered by current DaemonSet controller.

**Comment by resouer** [comment] 2017-08-19 09:10
@mikedanese @kargakis，what do you think about his feature request? Is it reasonable or we prefer to leave it as is (https://github.com/kubernetes/kubernetes/issues/50689#issuecomment-322480599).

**Comment by wenlxie** [comment] 2017-08-19 10:39
@resouer  This scenario can be covered by current DaemonSet controller? I am a bit confused.
I know if the a node just added to the cluster, the controller will create one pod to it. But if the node restart, the DaemonSet controller still can do that?

**Comment by resouer** [comment] 2017-08-20 03:04
@wenlxie Controller has enough information about Node status change .

**Comment by wenlxie** [comment] 2017-08-20 03:08
@resouer  Thanks, will have a check and have a try.

**Comment by kargakis** [comment] 2017-08-20 11:00
Dupe of https://github.com/kubernetes/kubernetes/issues/36601

**Closed by kargakis** 2017-08-20 11:00 UTC
Labels: area/app-lifecycle, area/workload-api/daemonset, kind/feature, sig/scheduling

**Comment by minherz** [comment] 2020-04-16 11:18
why this is closed? the duplicated issue was not implemented, meaning the problem is still there.
it is still impossible to run daemonset with [pods that simulate jobs](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-template).
The duplicated issue should be #64623
