### ISSUE TITLE
[k8s.io] Services should work after restarting kube-proxy [Disruptive] failed all the time in ci-kubernetes-e2e-gce-serial

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#45988] opened 2017-05-17 19:58 UTC
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial is very flaky since 2017-05-12 00:47 PDT took 5h5m due to the test:
```
[k8s.io] Services should work after restarting kube-proxy [Disruptive]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:387
Expected error:
    <*errors.errorString | 0xc42030a400>: {
        s: "service verification failed for: 10.0.115.80\nexpected [service1-28w8q service1-bmp00 service1-d609r]\nreceived []",
    }
    service verification failed for: 10.0.115.80
    expected [service1-28w8q service1-bmp00 service1-d609r]
    received []
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:385
```
One example of failed builds is: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1063/

The flakiness currently blocks our 1.7 alpha-4 build.

cc/ @kubernetes/kubernetes-release-managers @kubernetes/sig-network-bugs @thockin

**Comment by dchen1107** [comment] 2017-05-17 20:32
@MrHohn is triaging this. Please let the release manager team know if this is a blocker.

**Comment by MrHohn** [comment] 2017-05-17 21:13
Found a potential root cause: https://github.com/kubernetes/kubernetes/commit/77624a12d38692e1cc06d8a375f67b6d48549ca9#diff-d51765b83fe795b469e8a86276b12dc9L590

Seems like this commit mistakenly flipped the skipping flag, so after restarted kube-proxy we failed to add the service rules back.

**Comment by MrHohn** [comment] 2017-05-17 21:14
cc @wojtek-t

**Comment by MrHohn** [comment] 2017-05-17 21:17
> Seems like this commit mistakenly flipped the skipping flag, so after restarted kube-proxy we failed to add the service rules back.

Sorry, I'm wrong. That only affects logging and it seems correct.

**Comment by MrHohn** [comment] 2017-05-17 22:00
Quick update, this seems to be a blocker.

The failure behavior is: In-cluster service stops working on node after kube-proxy is restarted. I'm trying to reproduce locally.

**Comment by MrHohn** [comment] 2017-05-17 22:20
Reproduced locally. After kube-proxy was restarted, the whole KUBE-SERVICES chain was missing. Though it recovered after the test service was deleted.

**Comment by MrHohn** [comment] 2017-05-17 22:55
The root cause should be https://github.com/kubernetes/kubernetes/commit/77624a12d38692e1cc06d8a375f67b6d48549ca9#diff-d51765b83fe795b469e8a86276b12dc9R907. Because `syncReason` is removed, we have not way to force kube-proxy to sync iptables rules.

During this disruptive test, we restart kube-proxy and flush some of the iptables chains. After restart, kube-proxy failed to restore the rules because there was neither endpoint change nor service change. Iptables rules didn't get restore until the real change came in (delete test service).

@wojtek-t @thockin

**Comment by thockin** [comment] 2017-05-17 23:01
ACK. We both missed that case.  I have to leave office soon, We could
revert that commit for a fast fix, though we do want most of the other
changes accumulated in there.

**Comment by wojtek-t** [comment] 2017-05-18 05:21
Yeah - I missed this case. Sorry. 

I will think about it try to re-revert with the fix.

**Comment by thockin** [comment] 2017-05-18 05:23
We can leave the reasons in place until the rest of the pre-filtering is done, and then remove the "did anything change" test entirely.  I owe you more time on that topic, will get to it probably tomorrow evening or Friday.

**Comment by wojtek-t** [comment] 2017-05-18 05:39
@thockin - yeah I think we can first try merging https://github.com/kubernetes/kubernetes/pull/45816 and then fix this PR. And that one is hanging on you :)

**Comment by wojtek-t** [comment] 2017-05-18 17:49
Marking as fixed - reverting my PR fixed the problems.

**Closed by wojtek-t** 2017-05-18 17:49 UTC
Labels: priority/critical-urgent, priority/failing-test, sig/network
