### ISSUE TITLE
kubelet --containerized should be marked deprecated

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#43708] opened 2017-03-27 15:15 UTC
It turns out that this flag actually breaks volume mounts, I've tried it by accident just now and spend too much time figuring out what was broken.

**Comment by ncdc** [comment] 2017-03-27 16:56
Wouldn't it make more sense to figure out what the issue is? I'd rather do that than remove functionality.

cc @smarterclayton @pmorie @eparis @yujuhong @dchen1107 @derekwaynecarr @sjenning @kubernetes/rh-cluster-infra @kubernetes/sig-node-bugs

**Comment by vishh** [comment] 2017-03-27 17:05
I'd be curious to know if the containerized mode is being tested by anyone... If there is no CI for it, then we should at-least mark it as `experimental`.

**Comment by eparis** [comment] 2017-03-27 17:11
I don't know about just kublet, but openshift node is successfully run containerized with volume mounts. Admittedly it is finiky to make sure you get the right things mounted into the node container and that they have the right mount propagation.

but --containerized is used in downstreams

**Comment by ncdc** [comment] 2017-03-27 17:19
Yes, we do use it successfully in OpenShift

**Comment by yujuhong** [comment] 2017-03-28 19:56
@errordeveloper could you provide more details about your setup, and the issues you encountered. This issue is not actionable without the information.

**Comment by fraenkel** [comment] 2017-03-29 03:45
https://github.com/kubernetes/kubernetes/issues/42889 documents many of the issues.

**Comment by eparis** [comment] 2017-06-16 14:12
Red Hat will work to fix problems with containerized kubelet, as we do use it. I'm going to close this issue. filing real bugs is the right path forward.

**Closed by eparis** 2017-06-16 14:12 UTC
Labels: sig/node
