### ISSUE TITLE
Token Review request has wrong behavior when token starts with a space

### ISSUE THREAD

**Issue by alejandrotineo** [kubernetes/kubernetes#114165] opened 2022-11-28 17:12 UTC
### What happened?

When issuing a token review request to the k8s api and provide a token with a leading space you get the following response:

```
{
	"kind": "TokenReview",
	"apiVersion": "authentication.k8s.io/v1",
	"metadata": {
		"creationTimestamp": null,
		"managedFields": [{
			"manager": "a-sample-manager",
			"operation": "Update",
			"apiVersion": "authentication.k8s.io/v1",
			"time": "2022-11-28T16:33:46Z",
			"fieldsType": "FieldsV1",
			"fieldsV1": {
				"f:spec": {
					"f:token": {}
				}
			}
		}]
	},
	"spec": {
		"token": " hello"
	},
	"status": {
		"authenticated": true,
		"user": {
			"username": "system:anonymous",
			"groups": [
				"system:unauthenticated"
			]
		},
		"audiences": [
			"https://kubernetes.default.svc.cluster.local"
		]
	}
}
``` 

### What did you expect to happen?

I would expect to have the token rejected. Similar to this output when no leading space is provided:

```
{
	"kind": "TokenReview",
	"apiVersion": "authentication.k8s.io/v1",
	"metadata": {
		"creationTimestamp": null,
		"managedFields": [{
			"manager": "a-sample-manager",
			"operation": "Update",
			"apiVersion": "authentication.k8s.io/v1",
			"time": "2022-11-28T16:37:31Z",
			"fieldsType": "FieldsV1",
			"fieldsV1": {
				"f:spec": {
					"f:token": {}
				}
			}
		}]
	},
	"spec": {
		"token": "hello"
	},
	"status": {
		"user": {},
		"error": "invalid bearer token"
	}
}
```

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce it, issue a token review request with a leading space in the token.

```
"spec": {
    "token": " hello"
},
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Happens locally in docker-desktop for Mac and also in AWS EKS
</details>

### OS version

<details>

```console

# MacOS:
$ os info
Monterey 12.6.1 (21G217)
$ uname -a
21.6.0 Darwin Kernel Version 21.6.0
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment] 2022-11-28 22:10
looks like this is a duplicate of https://github.com/kubernetes/kubernetes/issues/106142

TokenReview just delegates to the normal authentication chain with a request with an "Authorization: Bearer $token" header, so the behavior matches the actual Kubernetes API.

**Closed** 2022-11-28 22:10 UTC
Labels: kind/bug, needs-sig, needs-triage
