### ISSUE TITLE
Create a kubeadm installer container for CoreOS

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34134] opened 2016-10-05 19:29 UTC
And other platforms that may not have deb/rpm installation support

**Comment by luxas** [comment] 2016-10-05 19:30
cc @kubernetes/sig-cluster-lifecycle

**Comment by errordeveloper** [comment] 2016-10-05 20:24
Yes, we should. The code for one I've built earlier is [here](https://github.com/errordeveloper/t8s/tree/master/kubeadm-installer). Also, I think this issue should had been failed in the release repo.

**Comment by luxas** [comment] 2016-10-05 20:30
re an issue already in kubernetes/release; I can't see one

**Comment by errordeveloper** [comment] 2016-10-07 09:09
> re an issue already in kubernetes/release; I can't see one

No, I don't think there is one, I mean you should have opened this issue in that repo...

**Comment by errordeveloper** [comment] 2016-10-07 09:17
> ...you should have opened this issue in that repo...

But you don't have to, just trying to be a bit more organised :)

**Comment by qmx** [comment] 2016-10-19 03:13
I'd love to help to make this happen, can anyone mentor me on what needs to be done?

**Comment by bogdando** [comment] 2016-10-25 09:19
What kubernetes binaries are the 1st class citizens and allowed to go to hyperkube and what are the 2nd class and shall be shipped as a separate distros? Doesn't what defeat the very concept of the hyperkube distro? Shall we extract discovery and federation related binaries? Why do you thing LCM tool (kubeadm) differs to those so it has to be separated?

**Comment by luxas** [comment] 2016-11-14 05:42
OK, I got kubeadm working on CoreOS quite easily while travelling back from KubeCon :smile:
Here's how to do it:

```bash
K8S_VERSION=v1.4.4
CNI_RELEASE=07a8a28637e97b22eb8dfe710eeae1344f69d16e

mkdir -p /opt/cni /opt/bin
curl -sSL https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl > /opt/bin/kubectl
curl -sSL https://storage.googleapis.com/kubernetes-release-dev/ci-cross/v1.5.0-alpha.2.421+a6bea3d79b8bba/bin/linux/amd64/kubeadm > /opt/bin/kubeadm
chmod +x /opt/bin/kubectl /opt/bin/kubeadm
curl -sSL https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-${CNI_RELEASE}.tar.gz | tar xz -C /opt/cni/
cat > /etc/systemd/system/kubelet.service <<EOF
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
Environment=KUBELET_VERSION=${K8S_VERSION}_coreos.0
ExecStart=/usr/lib/coreos/kubelet-wrapper --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable docker kubelet
systemctl restart docker kubelet
```

Since CoreOS is missing `socat` on host, kubeadm preflight will stop the user from running init|join, so they must use `--skip-preflight-checks` like this `kubeadm init --skip-preflight-checks`.
We might consider making socat a soft dep for kubeadm, since kubelet will work, but not port-forwarding and such networking features. On CoreOS, we're running the kubelet in a rkt fly environment where socat exists, so it's ok.

I've already made an installer container for all oses here, we should consider making it "core": https://github.com/luxas/kubeadm-installer

How to install it on CoreOS for example:
```
docker run -it -v /etc/cni:/etc/cni -v /etc/systemd:/etc/systemd -v /opt:/opt -v /usr/bin:/usr/bin luxas/kubeadm-installer coreos
```

Feel free to test it out :smile: 
We should at least document these steps on CoreOS, as they differ from all other OSes.

cc @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment] 2016-11-14 05:51
cc @errordeveloper @pires @remoe @mettjus @qmx @ttcchl01 @v1k0d3n @JrCs @webwurst @HeavyHorst @raghu67 who've upvoted it :+1:

**Comment by pires** [comment] 2016-11-14 13:03
@luxas, one could figure out if the `kubelet` environment (if `containerized`) has `socat`. But I know there's WIP to remove the dependency on that.

**Comment by sandys** [comment] 2016-11-14 17:19
Can this be used to setup a cluster on a regular debian O's as well ?

**Comment by waynebrantley** [comment] 2016-11-14 22:11
Correct way to run...

 docker run -it -v /etc/cni:/rootfs/etc/cni -v /etc/systemd:/rootfs/etc/systemd -v /opt:/rootfs/opt -v /usr/bin:/rootfs/usr/bin luxas/kubeadm-installer coreos

**Comment by nick19860328** [comment] 2016-11-21 15:47
@waynebrantley wow, you guys are really cool.

**Comment by luxas** [comment] 2016-11-21 16:56
@sandys Yes, as long as you set the right cgroups manually

**Comment by dvohra** [comment] 2016-11-21 19:03
kubeadm init --skip-preflight-checks runs fine to create a single master node cluster. 

But the command to join the cluster on another node does not.

`  sudo kubeadm join --skip-preflight-checks --token=124af8.3210db576caf25c5 10.0.0.191`

The` kubectl get nodes` does not list the nodes added. 

kubeadm join generates the following output.
```

core@ip-10-0-0-219 ~ $ sudo kubeadm join --skip-preflight-checks --token=124af8.3210db576caf25c5 10.0.0.191
Skipping pre-flight checks
<util/tokens> validating provided token
<node/discovery> created cluster info discovery client, requesting info from "http://10.0.0.191:9898/cluster-info/v1/?token-id=124af8"
<node/discovery> cluster info object received, verifying signature using given token
<node/discovery> cluster info signature and contents are valid, will use API endpoints [https://10.0.0.191:6443]
<node/bootstrap> trying to connect to endpoint https://10.0.0.191:6443
<node/bootstrap> detected server version v1.4.4
<node/bootstrap> successfully established connection with endpoint https://10.0.0.191:6443
<node/csr> created API client to obtain unique certificate for this node, generating keys and certificate signing request
<node/csr> received signed certificate from the API server:
Issuer: CN=kubernetes | Subject: CN=system:node:ip-10-0-0-219.ec2.internal | CA: false
Not before: 2016-11-21 18:52:00 +0000 UTC Not After: 2017-11-21 18:52:00 +0000 UTC
<node/csr> generating kubelet configuration
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.



```

**Comment by dvohra** [comment] 2016-11-21 19:31
Also Pods are not getting scheduled even after 5 minutes.

```
core@ip-10-0-0-191 ~ $ kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP        NODE
nginx-3449338310-3dn1n   0/1       Pending   0          2m        <none>    
nginx-3449338310-ez256   0/1       Pending   0          2m        <none>    
nginx-3449338310-wvrfl   0/1       Pending   0          2m        <none>   
```

**Comment by luxas** [comment] 2016-11-21 19:34
Well, the output of the script says that you should do 
```
systemctl daemon-reload
systemctl enable docker kubelet 
```
and most importantly
```
systemctl start kubelet docker
```

I guess kubelet isn't just running. The container can't start it for you, and when you skipped the preflight checks, kubeadm wasn't able to inform you that the service wasn't running

**Comment by dvohra** [comment] 2016-11-21 19:40
Those were started before kubeadm init could be run.

```
core@ip-10-0-0-191 ~ $ sudo systemctl enable kubelet.service
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /etc/systemd/system/kubelet.service.
core@ip-10-0-0-191 ~ $ sudo systemctl enable docker.service
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
core@ip-10-0-0-191 ~ $ sudo systemctl start kubelet.service

```

Also added the master ip as A record on external DNS  nosqlsearch.com

**Comment by dvohra** [comment] 2016-11-21 19:52
The master being dedicated is not schedulable.

**Comment by dvohra** [comment] 2016-11-21 20:34
On new CoreOS nodes installed Master and additional nodes. All nodes get listed. The output of kubeadm join is:
```
core@ip-10-0-0-96 ~ $ sudo kubeadm join --skip-preflight-checks --token=d2ec95.ca68d7f1cb57fd6d 10.0.0.205
Skipping pre-flight checks
<util/tokens> validating provided token
<node/discovery> created cluster info discovery client, requesting info from "http://10.0.0.205:9898/cluster-info/v1/?token-id=d2ec95"
<node/discovery> cluster info object received, verifying signature using given token
<node/discovery> cluster info signature and contents are valid, will use API endpoints [https://10.0.0.205:6443]
<node/bootstrap> trying to connect to endpoint https://10.0.0.205:6443
<node/bootstrap> detected server version v1.4.4
<node/bootstrap> successfully established connection with endpoint https://10.0.0.205:6443
<node/csr> created API client to obtain unique certificate for this node, generating keys and certificate signing request
<node/csr> received signed certificate from the API server:
Issuer: CN=kubernetes | Subject: CN=system:node:ip-10-0-0-96.ec2.internal | CA: false
Not before: 2016-11-21 20:26:00 +0000 UTC Not After: 2017-11-21 20:26:00 +0000 UTC
<node/csr> generating kubelet configuration
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.


```

**Comment by dvohra** [comment] 2016-11-21 20:57
Cluster with a Master node gets created.
Additional nodes get joined.

But Pods do not get started.

```
core@ip-10-0-0-205 ~ $ kubectl get pods -o wide
NAME                     READY     STATUS              RESTARTS   AGE       IP        NODE
nginx-3449338310-bi0vo   0/1       ContainerCreating   0          5m        <none>    ip-10-0-0-96.ec2.internal
nginx-3449338310-khkqu   0/1       ContainerCreating   0          5m        <none>    ip-10-0-0-63.ec2.internal
nginx-3449338310-whwcd   0/1       ContainerCreating   0          5m        <none>    ip-10-0-0-63.ec2.internal
core@ip-10-0-0-205 ~ $ kubectl describe pod nginx-3449338310-bi0vo
Name:		nginx-3449338310-bi0vo
Namespace:	default
Node:		ip-10-0-0-96.ec2.internal/10.0.0.96
Start Time:	Mon, 21 Nov 2016 20:46:07 +0000
Labels:		pod-template-hash=3449338310
		run=nginx
Status:		Pending
IP:		
Controllers:	ReplicaSet/nginx-3449338310
Containers:
  nginx:
    Container ID:	
    Image:		nginx
    Image ID:		
    Port:		80/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pes8v (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-pes8v:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-pes8v
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----					-------------	--------	------		-------
  6m		6m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned nginx-3449338310-bi0vo to ip-10-0-0-96.ec2.internal
  6m		1s		370	{kubelet ip-10-0-0-96.ec2.internal}	Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "nginx-3449338310-bi0vo_default" with SetupNetworkError: "Failed to setup network for pod \"nginx-3449338310-bi0vo_default(86ed2967-b02b-11e6-bc4d-0a4b66a59436)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

core@ip-10-0-0-205 ~ $ 


```

**Comment by dvohra** [comment] 2016-11-21 21:02
The one difference during the retest is that the external DNS was not set with `--api-external-dns-names`.
`kubeadm init --skip-preflight-checks`

**Comment by luxas** [comment] 2016-11-22 06:39
You still need to install a pod network with `kubectl apply -f <addon-yaml>`, like always.
And just to be sure, have you started kubelet on the node also?

**Comment by dvohra** [comment] 2016-11-22 14:55
kubelet on the node is already started. 

Would it be the calico.yaml addon to apply?
http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/hosted/calico.yaml

Any modifications required to calico.yaml or apply as such with default settings?

**Comment by dvohra** [comment] 2016-11-22 17:39
Is a etcd cluster not created by default with kubeadm?

Applied a pod network as suggested. 

`kubectl apply -f calico.yaml`

calico.yaml is from http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/hosted/calico.yaml

Getting 
`etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused\n; Skipping pod"`

**Comment by dvohra** [comment] 2016-11-22 21:19
The issue is fixed with following settings:

-Replace the `data: etcd_endpoints` in `calico.yaml` from default setting of `127.0.0.1:2389` to the private ip of the master node. 

-Set `--listen-client-urls` and `--advertise-client-urls` in `etcd.json` to `0.0.0.0:2379`

**Comment by luxas** [comment] 2016-11-22 21:35
Oh no. Seems like calico broke the link in some way from the k8s website...

Well, @dvohra you should use this manifest http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/hosted/kubeadm/ instead of the other manifests that do require etcd.

With the manifest I linked, it will just be a `kubectl apply` with no extra config.

**Comment by dvohra** [comment] 2016-11-22 21:41
Thanks Luxas. 

But a etcd cluster is created by kubeadm. Why to create another etcd cluster which the kubeadm/calico.yaml does?

**Comment by luxas** [comment] 2016-11-22 21:46
The kubeadm etcd is _only_ for the apiserver and is right now deployed in a static pod, but that might change. Also when we go the HA route, we can't know where to find etcd, etc.

Basically, the etcd database that exists for the apiserver and is the heart of the cluster has nothing to do with a specific pod network's small config store between components, those two have to be separated, especially when looking at the security aspect.

**Comment by dvohra** [comment] 2016-11-22 21:48
Beside the issue, the `kubeadm/calico.yaml` has a bug in `calico-policy-controller ReplicaSet`, the labels don't match.
```

metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy-controller
```

Should be:

```

metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  template:
    metadata:
      name: calico-policy
      namespace: kube-system
      labels:
        k8s-app: calico-policy
```

**Comment by dvohra** [comment] 2016-11-22 23:48
The kubeadm/calico.yaml gets applied without any modification. But, the Pods do not get started with the following error.
	`FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "nginx-3449338310-1p37p_default" with SetupNetworkError: "Failed to setup network for pod \"nginx-3449338310-1p37p_default(7541546c-b10d-11e6-9621-0ae0495bf8fc)\" using network plugins \"cni\": No configured Calico pools; Skipping pod"

`

**Comment by luxas** [comment] 2016-11-23 16:42
@dvohra Please just tear down your cluster `kubeadm reset`, turn it up again (start kubelet and `kubeadm init|join`) and from the beginning apply the right manifest.

**Comment by dvohra** [comment] 2016-11-23 20:10
1. Started 3 new CoreOS EC2 instances. 
2. On one of the nodes reset with `kubeadm reset` if `kubeadm` available. Subsequently,  installed the `kubeadm-installer`
```
systemctl daemon-reload
systemctl enable docker kubelet 
systemctl start kubelet docker
```
3. Inited the cluster with `kubeadm init --skip-preflight-checks` 
4. Applied `kubeadm/calico.yaml`
5.Installed `kubeadm-installer` on the other 2 nodes
6. Joined the two nodes with master with `kubeadm join --skip-preflight-checks --token=<token>`
7. On master 3 nodes get listed with `kubectl get nodes`
8. Run a application on master
`kubectl -s http://localhost:8080 run nginx --image=nginx  --replicas=3 --port=80`
9. `kubectl get pods -o wide` lists the pods as `ContainerCreating` Status
10. Same error listed in pod description.
`FailedSync Error syncing pod, skipping: failed to "SetupNetwork" for "nginx-3449338310-1p37p_default" with SetupNetworkError: "Failed to setup network for pod \"nginx-3449338310-1p37p_default(7541546c-b10d-11e6-9621-0ae0495bf8fc)\" using network plugins \"cni\": No configured Calico pools; Skipping pod"`

**Comment by dvohra** [comment] 2016-11-26 14:33
Update:
With calico.yaml customization cluster does get created and Pods do get started but a service does not get created or exposed. The kubeadm/calico.yaml is the Pod network manifest to use but for the issue indicated previously.

**Comment by pswenson** [comment] 2016-12-16 21:55
in the meantime, what is the fastest way to get k8s going on coreoes for a dev env?

**Comment by stephanlindauer** [comment] 2016-12-17 11:11
if you are on aws you could try my setup: https://github.com/stephanlindauer/terra-aws-core-kube

**Comment by dvohra** [comment] 2017-01-02 17:41
Use the CloudFormation to initialize Kubernetes cluster on CoreOS. 
https://coreos.com/kubernetes/docs/latest/

**Comment by luxas** [comment] 2017-05-28 08:48
@mikedanese @pipejakob I think we should move this issue to kubernetes/kubeadm.

**Comment by roberthbailey** [comment] 2017-06-13 07:25
@luxas - please open an issue in the kubeadm repo for this feature request.

**Closed by roberthbailey** 2017-06-13 07:25 UTC
Labels: area/kubeadm, sig/cluster-lifecycle
