### ISSUE TITLE
kubectl debug --copy-to option copy or add labels

### ISSUE THREAD

**Issue by raffis** [kubernetes/kubernetes#115679] opened 2023-02-10 09:40 UTC
### What would you like to be added?

Add an option to kubectl debug --copy-to to either on the fly add labels to the clone or copy the existing labels from the origin.

### Why is this needed?

`kubectl debug --copy-to` currently does not copy labels. I reckon there is a good reason for it. (Probably if a pod from a replica-set gets cloned and would be removed again because of `pod-template-hash`).

However without labels the debug pod without labels is pretty much useless in a cluster which has networkpolicies based on labels if you actually want to debug network stuff.

Happy to contribute a pr if I am not the only one thinking there should be an option to label the pod (or copy labels).

**Comment by ardaguclu** [comment] 2023-02-10 12:07
Thanks for raising this issue @raffis 

This looks duplicate of https://github.com/kubernetes/kubectl/issues/1364, it would be better to continue discussions on there.

Would you mind if I close this one to better alignment?

**Closed** 2023-02-10 12:09 UTC
Labels: area/kubectl, kind/feature, sig/cli, needs-triage
