### ISSUE TITLE
strategic merge patch does not work with CRD types

### ISSUE THREAD

**Issue by aerokite** [kubernetes/kubernetes#52772] opened 2017-09-20 08:02 UTC
**strategic merge patch** on CRD object doesn't work.

`$ kubectl patch postgres p1 -p '{"spec":{"doNotPause":false}}'`

Getting following error:
```
Error from server: Object 'Kind' is missing in '{"object":{"apiVersion":"kubedb.com/v1alpha1","kind":"Postgres","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kubedb.com/v1alpha1\",\"kind\":\"Postgres\",\"metadata\":{\"annotations\":{},\"name\":\"p1\",\"namespace\":\"demo\"},\"spec\":{\"doNotPause\":false,\"init\":{\"scriptSource\":{\"gitRepo\":{\"repository\":\"https://github.com/k8sdb/postgres-init-scripts.git\"},\"scriptPath\":\"postgres-init-scripts/run.sh\"}},\"storage\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"50Mi\"}},\"storageClassName\":\"standard\"},\"version\":9.5}}\n"},"clusterName":"","creationTimestamp":"2017-09-20T07:19:17Z","deletionGracePeriodSeconds":null,"deletionTimestamp":null,"generation":0,"name":"p1","namespace":"demo","resourceVersion":"3637","selfLink":"","uid":"039baa9d-9dd4-11e7-8b3f-08002709c846"},"spec":{"doNotPause":false,"init":{"scriptSource":{"gitRepo":{"repository":"https://github.com/k8sdb/postgres-init-scripts.git"},"scriptPath":"postgres-init-scripts/run.sh"}},"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Mi"}},"storageClassName":"standard"},"version":9.5}},"spec":{"doNotPause":false}}'
```

But **merge patch** works on CRD types.
`$ kubectl patch postgres p1 -p '{"spec":{"doNotPause":false}}' --type="merge"`

I have used minikube
- Client Version: v1.7.4
- Server Version: v1.7.5

Registered CRD `postgreses.kubedb.com`
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2017-09-20T06:38:18Z
  labels:
    app: kubedb
  name: postgreses.kubedb.com
  resourceVersion: "193"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/postgreses.kubedb.com
  uid: 49ce4e1a-9dce-11e7-8b3f-08002709c846
spec:
  group: kubedb.com
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgreses
    shortNames:
    - pg
    singular: postgres
  scope: Namespaced
  version: v1alpha1
status:
  acceptedNames:
    kind: Postgres
    listKind: PostgresList
    plural: postgreses
    shortNames:
    - pg
    singular: postgres
  conditions:
  - lastTransitionTime: null
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: 2017-09-20T06:38:18Z
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
```

Postgres object `p1`
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubedb.com/v1alpha1","kind":"Postgres","metadata":{"annotations":{},"name":"p1","namespace":"demo"},"spec":{"doNotPause":false,"init":{"scriptSource":{"gitRepo":{"repository":"https://github.com/k8sdb/postgres-init-scripts.git"},"scriptPath":"postgres-init-scripts/run.sh"}},"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Mi"}},"storageClassName":"standard"},"version":9.5}}
  clusterName: ""
  creationTimestamp: 2017-09-20T07:19:17Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  generation: 0
  name: p1
  namespace: demo
  resourceVersion: "3637"
  selfLink: /apis/kubedb.com/v1alpha1/namespaces/demo/postgreses/p1
  uid: 039baa9d-9dd4-11e7-8b3f-08002709c846
spec:
  doNotPause: true
  init:
    scriptSource:
      gitRepo:
        repository: https://github.com/k8sdb/postgres-init-scripts.git
      scriptPath: postgres-init-scripts/run.sh
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
    storageClassName: standard
  version: 9.5
```

**Comment by deads2k** [comment] 2017-09-20 12:28
Without the merge definitions, you can't apply a strategic merge patch.  Looks like a dupe of https://github.com/kubernetes/kubernetes/issues/50037

**Comment by ncdc** [comment] 2017-09-20 13:40
Yes, this is a dupe.

**Closed by ncdc** 2017-09-20 13:40 UTC
Labels: area/third-party-resource, kind/bug, sig/api-machinery
