### ISSUE TITLE
Failed to generate pod sandbox config if missing /etc/resolv.conf

### ISSUE THREAD

**Issue by Haleygo** [kubernetes/kubernetes#103110] opened 2021-06-23 10:16 UTC
#### What happened:
I run kubeadm init on a node and it took a long time to wait for the kubelet(to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests"). And It timeout eventually, so I checked the journal of kubelet and found those error:

> Jun 23 18:33:35 10-6-150-51 kubelet[32141]: E0623 18:33:35.148371   32141 kuberuntime_sandbox.go:41] "Failed to generate sandbox config for pod" err="open /etc/resolv.conf: no such file or directory" pod="kube-system/kube-scheduler-10-6-150-51"
Jun 23 18:33:35 10-6-150-51 kubelet[32141]: E0623 18:33:35.148415   32141 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="open /etc/resolv.conf: no such file or directory" pod="kube-system/kube-scheduler-10-6-150-51"
Jun 23 18:33:35 10-6-150-51 kubelet[32141]: E0623 18:33:35.148499   32141 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-10-6-150-51_kube-system(39f9fcbd5659a4af7687f0af6d8320f0)\" with CreatePodSandboxError: \"Failed to generate sandbox config for pod \\\"kube-scheduler-10-6-150-51_kube-system(39f9fcbd5659a4af7687f0af6d8320f0)\\\": open /etc/resolv.conf: no such file or directory\"" pod="kube-system/kube-scheduler-10-6-150-51" podUID=39f9fcbd5659a4af7687f0af6d8320f0

Looks like the same problem as https://github.com/moby/moby/issues/4861

#### What you expected to happen:
Pod can create successfully because /etc/resolv.conf is not an essential file in filesystem. (see
http://man7.org/linux/man-pages/man5/resolv.conf.5.html)

> If this file does not exist, only the name server on the local machine
> will be queried

#### How to reproduce it (as minimally and precisely as possible):
1. mv /etc/resolv.conf somewhere else
2. run "kubeadm init" and watch kubelet journal

#### Environment:
- Kubernetes version (use `kubectl version`): Kubernetes v1.21.1
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9

**Comment by Haleygo** [comment] 2021-06-23 10:17
/assign
I will fix it the same way as https://github.com/moby/libnetwork/pull/1847

**Comment by Haleygo** [comment] 2021-06-23 12:03
It can also reproduce like this:
1. have a healthy cluster
2. choose one node, create a test pod yaml under kubelet manifest folder (to keep this pod on this node) and wait it ready
3. move /etc/resolv.conf somewhere else
4. delete test pod container and search kubelet journal for this test pod

**Comment by gjkim42** [comment] 2021-06-23 12:41
> I will try to create a new resolv file here if err is "file not exist"

Even if we consider this a bug,
IMHO, creating /etc/resolv.conf file to the host machine is a bad idea. I think making default resolver configuration is better approach.

**Comment by aojea** [comment] 2021-07-07 20:36
discussion was going on the PR https://github.com/kubernetes/kubernetes/pull/103183#issuecomment-875800132 , it should be triaged first though, is not clear this is a bug or a new feature kubernetes want to support ...

**Comment by pacoxu** [comment] 2021-08-10 02:42
> discussion was going on the PR [#103183 (comment)](https://github.com/kubernetes/kubernetes/pull/103183#issuecomment-875800132), it should be triaged first though, is not clear this is a bug or a new feature Kubernetes want to support ...

I only met similar issues in some private clouds or bare metal private machines. It would be a problem for them.
IMO, this may not be a bug, but something we can tolerate.

There are three ways:
1. like PR #103183, return an empty `resolv.conf` file. (I prefer this because in some cases the `/etc.resolv.conf` has no nameservers and the pod can start. File-not-exists is the same to me as no nameservers in the file.)
2. we can do some pre-check in installers or kubelet start-up.
3. this is expected behavior.

**Comment by aojea** [comment] 2021-08-10 08:01
> > discussion was going on the PR [#103183 (comment)](https://github.com/kubernetes/kubernetes/pull/103183#issuecomment-875800132), it should be triaged first though, is not clear this is a bug or a new feature Kubernetes want to support ...
> 
> I only met similar issues in some private clouds or bare metal private machines. It would be a problem for them.
> IMO, this may not be a bug, but something we can tolerate.
> 
> There are three ways:
> 
> 1. like PR [Kubelet use default DNS configuration if host's resolvConf file does not exist #103183](https://github.com/kubernetes/kubernetes/pull/103183), return an empty `resolv.conf` file. (I prefer this because in some cases the `/etc.resolv.conf` has no nameservers and the pod can start. File-not-exists is the same to me as no nameservers in the file.)

what if the resolv.conf is added later? this can race ...

> 2. we can do some pre-check in installers or kubelet start-up.

if the resolv.conf is needed/required for a cluster to work well, that I think it is, I think this is a good option

> 3. this is expected behavior.

at least is the one that we always had :smile: :smile:

**Comment by pacoxu** [comment] 2021-08-11 08:37
> what if the resolv.conf is added later? this can race ... or you have some pods with a dummy resolv.con and others with a good one

That would be a problem with this PR merged.
1. **No `resolv.conf` file**: Pod created with empty  `resolv.conf` file.
2. the correct `resolv.conf` is added.
3. New pod will use the correct  `resolv.conf`. But the old Pods is using the empty  `resolv.conf`.

Currently behavior
1. **No `resolv.conf` file**: Pod  cannot be created
2. the correct `resolv.conf` is added.
3. All running pods will use the correct  `resolv.conf`.

However, for scenario that the `resolv.conf` file is not correct at first and we change it to the correct one, it is also a problem.

**Comment by Haleygo** [comment] 2021-08-12 01:16
@aojea @pacoxu thanks for explanation.
Apparently, making up a default resolv.conf is a reckless move. 
Sounds like we should leave the pod creating process as it was, and it will be nice if there is a pre-check in installers or kubelet start-up.

**Comment by gjkim42** [comment] 2021-08-12 01:41
> what if the resolv.conf is added later? this can race ... or you have some pods with a dummy resolv.con and others with a good one

`resolv.conf` file that a pod uses can be changed somehow. Because it is loaded when creating the pod.
This issue is not relevant to the race itself. 

I think the main issue here is that whether we want kubelet to support the absence of `resolv.conf` or not.
**I am not claiming that it is necessary.**
However it seems that the case without `resolv.conf` is also a valid configuration.
> ```
> If this file does not exist, only the name server on the local
> machine will be queried, and the search list contains the local
> domain name determined from the hostname.
> ```

**Comment by aojea** [comment] 2021-08-12 08:52
> I think the main issue here is that whether we want kubelet to support the absence of resolv.conf or not.
> I am not claiming that it is necessary.
> However it seems that the case without resolv.conf is also a valid configuration.

Good point @gjkim42, that is really the discussion. 

I was checking the code and there is something important here we were not considering, and is that the resolv.conf path is a configuration option that defaults to `/etc/resolv.conf`

https://github.com/kubernetes/kubernetes/blob/27b02a3e37f6ae5c121e0e412520199b50fb8290/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L596-L604

https://github.com/kubernetes/kubernetes/blob/27b02a3e37f6ae5c121e0e412520199b50fb8290/cmd/kubelet/app/options/options.go#L506-L507

I personally, don't think that if I (as admin) configure the resolv.conf with a wrong path (non existing file) kubelet should work, that is a mistake I did in my configuration and as admin I should fixed. 

Kubernetes has some requirements, the absence of a resolv.conf is valid for Linux, that doesn't mean necessarily valid for Kubernetes, and in this case I think that is legit for Kubernetes to require that a `resolv.conf` file exist.

**Comment by gjkim42** [comment] 2021-08-12 09:42
> the resolv.conf path is a configuration option that defaults to `/etc/resolv.conf`

@aojea 
It seems like a fair point. I think that configuring the file path to the path that doesn't exist is weird.

And also agree that kubernetes has its own requirements.

---

@Haleygo 
Maybe there is an option for a user who doesn't want to inherit resolver configuration from anything.

https://github.com/kubernetes/kubernetes/blob/e7efe219f8a5fcdff9647d45639696048c1f6147/pkg/kubelet/network/dns/dns.go#L281-L301

Another alternative could be to let people who don't have any `resolv.conf` file set `resolvConf` argument to "" (empty string).

**Comment by aojea** [comment] 2021-08-12 10:56
> Another alternative could be to let people who don't have any `resolv.conf` file set `resolvConf` argument to "" (empty string).

:thinking:  what happens now if you do that? does it work?

**Comment by gjkim42** [comment] 2021-08-12 12:10
```sh
/home/gjkim/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/kubelet --v=3 --vmodule= --container-runtime=docker --hostname-override=127.0.0.1 --cloud-provider= --cloud-config= --bootstrap-kubeconfig=/var/run/kubernetes/kubelet.kubeconfig --kubeconfig=/var/run/kubernetes/kubelet-rotated.kubeconfig --resolv-conf= --config=/tmp/kubelet.yaml
```

I launched the kubelet with "--resolv-conf= ", and it seemed to work as expected.

```yaml
apiVersion: v1
kind: Pod 
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: ubuntu
    name: test
    resources: {}
  dnsPolicy: Default
  restartPolicy: Never
status: {}
```

```sh
$ kubectl exec -it test -- more /etc/resolv.conf
nameserver 127.0.0.1
search .
```

**Comment by gjkim42** [comment] 2021-08-12 12:52
https://github.com/kubernetes/kubernetes/blob/9c7426e14f977026ed74dce0c537ebb486f15cd7/pkg/kubelet/network/dns/dns.go#L401-L422

I think this code was executed, when we set `--resolv-conf= ` to the argument.

However, if we set [resolvConf in a config file](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) to "", resolv.conf path was set to "/etc/resolv.conf".
I think there exists inconsistency between setting with arguments and with a configuration file.

**Comment by aojea** [comment] 2021-08-12 13:14
> I think there exists inconsistency between setting with arguments and with a configuration file.

I think that this is because in golang the empty string is the default value, so you can't differentiate between empty or default, unless you use a pointer

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L184-L185

and is not a pointer
https://github.com/kubernetes/kubernetes/blob/27b02a3e37f6ae5c121e0e412520199b50fb8290/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L596-L604

**Comment by aojea** [comment] 2021-08-12 13:17
@liggitt we have one incongruence  between config and flags in kubelet, can you advise? 
https://github.com/kubernetes/kubernetes/issues/103110#issuecomment-897613618

I guess I remember you mentioned you went through this pain before

**Comment by liggitt** [comment] 2021-08-12 13:55
if you need to distinguish between unset and set-but-empty, the config file needs to use a pointer, and the defaulting needs to only default on nil, not ""

**Comment by aojea** [comment] 2021-08-12 14:00
> if you need to distinguish between unset and set-but-empty, the config file needs to use a pointer, and the defaulting needs to only default on nil, not ""

@gjkim42 I see that config is in v1beta1, maybe the change to a pointer still can be done, this different behavior between flags and config looks like a bug to me though

 ... and then users can set resolv.conf to "" if they don't want to use it, right?

**Comment by gjkim42** [comment] 2021-08-12 14:12
Yes, it looks ok to me, if there is no better suggestion.

**Comment by Haleygo** [comment] 2021-08-13 02:40
According to you guys discussions, the only thing left here is to remake the "--resolv-conf=" flag, from string to a pointer.
After that, users can set resolv.conf to "" if they don't want to use it; and if they don't set it or set it to a wrong (or not existed) path, kubelet should leave it be cause that is a mistake and should fixed.
Is that right? @gjkim42 
then I will close my first pr :)

**Comment by gjkim42** [comment] 2021-08-13 04:05
Yes, it is. You can make a new PR if you want to.

To clarify,
we have been able to set a resolv.conf file path to an empty string by kubelet arguments `--resolv-conf= --other-options` until now. The problem is that currently, we can't do the same workaround by the kubelet config file.

(One little concern is that kubelet command-line arguments already have been deprecated.)

**Comment by gjkim42** [comment] 2021-11-11 04:50
After https://github.com/kubernetes/kubernetes/pull/104624,
we can configure kubelet to not refer to any resolver configuration
- by running kubelet with `--resolv-conf= --OTHER_OPTS` or
- by setting `resolvConf` of kubelet config file to ""

Maybe we need some doc updates for this.

**Closed** 2022-01-10 05:37 UTC
Labels: kind/bug, priority/backlog, area/kubelet, sig/node, lifecycle/rotten, triage/accepted
