### ISSUE TITLE
hack/godep-save.sh pulls down docker/docker/project dir

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#48593] opened 2017-07-07 09:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I am trying to update the vendor directory by following the instructions here: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md.

When I run `./hack/godep-save.sh`, an extra directory is pulled:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/docker/docker/project/
````

This directory contains a `CONTRIBUTORS.md` which contains a symlink -  `../CONTRIBUTING.md`. 

Due to this, running `./hack/update-bazel.sh` panics:

```
F0707 12:15:44.993342    5803 gazel.go:54] err walking vendor: stat vendor/github.com/docker/docker/project/CONTRIBUTORS.md: no such file or directory
goroutine 1 [running]:
gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog.stacks(0xc420612b00, 0xc42062fb30, 0x97, 0xeb)
	/home/nikhita/code/kubernetes/src/gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog/glog.go:766 +0xa7
gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog.(*loggingT).output(0x6c05a0, 0xc400000003, 0xc420014f20, 0x6a262b, 0x8, 0x36, 0x0)
	/home/nikhita/code/kubernetes/src/gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog/glog.go:717 +0x348
gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog.(*loggingT).printf(0x6c05a0, 0xc400000003, 0x5dd1e2, 0x16, 0xc4200fbf38, 0x1, 0x1)
	/home/nikhita/code/kubernetes/src/gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog/glog.go:655 +0x14f
gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog.Fatalf(0x5dd1e2, 0x16, 0xc4200fbf38, 0x1, 0x1)
	/home/nikhita/code/kubernetes/src/gopkg.in/mikedanese/gazel.v17/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/home/nikhita/code/kubernetes/src/gopkg.in/mikedanese/gazel.v17/gazel/gazel.go:54 +0x2cd
!!! Error in ./hack/update-bazel.sh:40
  Error in ./hack/update-bazel.sh:40. '"${gazel}" -root="$(kube::realpath ${KUBE_ROOT})"' exited with status 255
Call stack:
  1: ./hack/update-bazel.sh:40 main(...)
Exiting with status 1
```

Related Links:

- https://github.com/kubernetes/kubernetes/pull/42967#issuecomment-288593136
- https://github.com/kubernetes/kubernetes/issues/35356#issuecomment-258054506
- https://github.com/tools/godep/pull/522
- https://github.com/moby/moby/pull/31847

**What you expected to happen**:
The extra directory should not be pulled down after running `./hack/godep-save.sh`.

**How to reproduce it (as minimally and precisely as possible)**:

By running `./hack/godep-save.sh`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.823+a57c33bd281732", GitCommit:"a57c33bd2817323806b97da5c2f848108f7403d8", GitTreeState:"clean", BuildDate:"2017-06-19T02:15:29Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 

```
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

godep version:

```
godep v79 (linux/amd64/go1.8.1)
```

**Comment by nikhita** [comment] 2017-07-07 09:40
cc @cblecker @sttts

**Comment by sttts** [comment] 2017-07-07 10:36
For the record (compare the links above): this was seen before, but seems to be not easily reproducible. I tried on Mac and didn't see this.

**Comment by nikhita** [comment] 2017-07-07 15:51
So `vendor/github.com/docker/docker/project/` should actually contain `CONTRIBUTING.md` (not `CONTRIBUTORS.md` due to the change at https://github.com/moby/moby/pull/31847 but surprisingly the change is not reflected?

I even ran `./hack/godep-restore.sh` before godep-save..

**Comment by sttts** [comment] 2017-07-07 16:18
> should actually contain CONTRIBUTING.md

Isn't our 1.11.2 version too old?

**Comment by nikhita** [comment] 2017-07-07 16:20
> Isn't our 1.11.2 version too old?

Thought so too. But it doesn't tell us why it's not reproduce-able every time then.

**Comment by cblecker** [comment] 2017-07-07 16:47
Yeah, so the issue here is that godep doesn't do a full copy of the repo into vendor.. it only copies *.go files, and any legal/licencing files. `CONTRIBUTORS` is considered a licence file, while "CONTRIBUTING" is not. So in this case, the symlink is copied, but the destination file is not.

This has been fixed at head (in the PR you point out), but we can't go back in time and change the 1.11.2 tag.

We have an ignore on the verify script (https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L128) so that we don't care if this file exists or has changed.

Short term fix: You can safely delete `vendor/github.com/docker/docker/project/` and proceed.
Mid term potential fix: We could add a safety check to `hack/godep-save.sh` to account for this one file and one use case, and if the file exists, delete it.
Long term fix: Get all these godep scripts dockerized (the first one being https://github.com/kubernetes/kubernetes/pull/46193) so that we can do things like `godep update` safely, and not have to take drastic measures like deleting the whole `vendor/` directory like the current docs say (ref: https://github.com/kubernetes/community/pull/520).

**Comment by cblecker** [comment] 2017-07-07 17:02
Wholeheartedly agree on last point, @sttts 👍 : https://github.com/kubernetes/kubernetes/issues/44873

**Comment by sttts** [comment] 2017-07-07 17:13
This might be fixed with https://github.com/kubernetes/kubernetes/pull/48615. @nikhita can you try again without the apimachinery dir in the GOPATH? I tried with godep-save and didn't see the project/ anymore. But I also had no change in gengo I think.

**Comment by nikhita** [comment] 2017-07-07 17:14
@nikhita On it now. :+1:

**Comment by nikhita** [comment] 2017-07-07 20:17
just for the record, #48615 does not prevent `vendor/github.com/docker/docker/project/` - but it does help in vendoring gengo. :)

**Closed** 2017-07-11 22:37 UTC
Labels: kind/bug, needs-sig
