### ISSUE TITLE
Daemonsets pods are being scheduled with duplicate IPs

### ISSUE THREAD

**Issue by maktouch** [kubernetes/kubernetes#72186] opened 2018-12-19 06:20 UTC
**What happened**:
Pods are being scheduled with duplicate IPs 

**What you expected to happen**:
Unique IP per pods

**How to reproduce it (as minimally and precisely as possible)**:
No clue, it seems to happen randomly. I only noticed it when my errors rate went up, and one of my Nginx Ingress (daemonset) wasn't reachable because of the IP conflict.

Most of the IP conflict remaining are bad but it seems like the cluster is still humming

```
kube-system     ip-masq-agent-wsqn5                                         1/1       Running     0          15h       172.20.1.10    gke-plr-web-prd-05-web-00-531bb1cd-2djt         <none>
kube-system     kube-proxy-gke-plr-web-prd-05-web-00-531bb1cd-2djt          1/1       Running     0          15h       172.20.1.10    gke-plr-web-prd-05-web-00-531bb1cd-2djt         <none>
monitoring      node-exporter-mz76k                                         1/1       Running     0          15h       172.20.1.10    gke-plr-web-prd-05-web-00-531bb1cd-2djt         <none>
```

**Anything else we need to know?**:
I created a GKE cluster with a custom pod address range and VPC-Native on. It looks like a race condition thing because it seems to only happen to DaemonSets and system pods, and the conflict is all on the same node, and the pod all have the same age

**Environment**:
- Kubernetes version (use `kubectl version`): 
```

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:

GKE

```
    Master version => 1.11.2-gke.18    
    Endpoint => <redacted>
    Client certificate	=> Enabled
    Binary authorization	=> Disabled
    Kubernetes alpha features	 => Disabled
    Current total size  => 33
    Master zone	=> us-west1-a
    Node zones	=> us-west1-a
    Network	 => <redacted>
    Subnet	=> <redacted>
    VPC-native (alias IP)	=> Enabled
    Pod address range	=> 172.30.0.0/17
    Default maximum pods per node	=> 110
    Service address range	=> 172.30.128.0/17
    Stackdriver Logging	 => Enabled
    Stackdriver Monitoring	=> Enabled
    Private cluster	=> Disabled
    Master authorized networks	=> Disabled
    Network policy	=> Disabled
    Legacy authorization	=> Disabled
    Maintenance window	=> 3:00 PM
    Cloud TPU	=> Disabled
    Node auto-provisioning	=> Disabled
```

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment] 2018-12-19 15:21
are those pods using host network?

**Comment by maktouch** [comment] 2018-12-20 07:18
@liggitt 

> are those pods using host network?

ip-masq-agent: yes
kube-proxy: yes
node-exporter: yes
ingress-nginx: no

**Comment by liggitt** [comment] 2018-12-20 14:30
it is expected that host network pods will have their IP set to the node's IP (which means multiple pods will have the same IP):

https://github.com/kubernetes/kubernetes/blob/0c7e207904edfd2f934cbcf3167229fc9d491dca/pkg/kubelet/kubelet_pods.go#L1361-L1363

Can you provide the output of the following:
```
kubectl get node -o yaml <problematic-node-name>
kubectl get pods -o yaml -l <selector for nginx pods> --field-selector=spec.nodeName=<problematic-node-name>
```

**Comment by liggitt** [comment] 2018-12-20 14:34
fyi, a couple issues around pod IPs and routing to pods were recently fixed in the 1.11.2 stream (not a duplicate IP issue, but related to pod IPs and the symptoms are similar to your unreachable pod issue):

https://cloud.google.com/kubernetes-engine/release-notes#december-17-2018
https://cloud.google.com/kubernetes-engine/release-notes#december-10-2018

`1.11.2-gke.26` contains fixes for both of those issues

**Comment by maktouch** [comment] 2018-12-20 14:41
```
ingress-nginx   ingress-ws-nginx-ingress-controller-tcf9x                   1/1       Running     0          4h        172.30.10.3    gke-plr-web-prd-05-websocket-00-5ff83431-w7qn   <none>
kube-system     fluentd-gcp-v3.1.0-n4nhg                                    2/2       Running     0          4h        172.30.10.3    gke-plr-web-prd-05-websocket-00-5ff83431-4m0n   <none>
```

This is the only thing remaining when I figured out it had a conflict. Unfortunately, this happened on a production cluster so I had to kill the node to repair it because the error rates were thru the roof. 

`ingress-ws-nginx-ingress-controller-tcf9x` is not using hostNetwork, and it's not on the same machine as the conflicting `fluentd-gcp-v3.1.0-n4nhg`

I'll make sure to run those 2 commands before repairing it next time it occurs. 

I'll also try to upgrade to `1.11.2-gke.26`

Cheers, thanks!

**Comment by liggitt** [comment] 2018-12-20 14:55
does the custom pod address range you specified overlap with node or service IP ranges?

**Comment by maktouch** [comment] 2018-12-21 01:46
Cluster range = 172.20.1.0/24
Pod address range	= 172.30.0.0/17
Service address range = 172.30.128.0/17

Not sure how to check for that

**Comment by jayunit100** [comment] 2018-12-22 16:56
In any case, not a bug, because “one IP per pod” , not “one pod for IP”, is the contract , right?.

**Comment by liggitt** [comment] 2018-12-22 17:02
I would not expect non-host-network pods to be assigned identical IP addresses. That seems like it would make network routing ambiguous, as seen in the "my Nginx Ingress (daemonset) wasn't reachable" comment.

**Comment by vikaschoudhary16** [comment] 2018-12-24 04:57
>Pod address range	= 172.30.0.0/17
>Service address range = 172.30.128.0/17

These subnets mean that:
Pod address range is 172.30.0.0 to 172.30.63.255
Service address range is 172.30.64.0 to 172.30.255.255

So ip ranges are not overlapping. Even if pods are using hostNetwork, if more than one such pods are on the same node, i dont see that as a problem because each application(pod), would listen on different port(otherwise there will be bind error and not ip conflict) and IP+port combination will be unique.

And if pods using hostnetwork are running on different nodes, then obviously there should not be ip conflict.

I am unable to see how hostnetworked pods can lead to IP conflict. Ip conflict can happen if only if one pod is hostnetworked and some another pod is using cni network plugin with IPAM configuration having overlapped ranges with the cluster nodes' subnet. In that case IP conflict is possible. No two pods, running with hostNetwork can create IP conflict, AFAIU.

**Comment by caseydavenport** [comment] 2019-01-03 01:07
> Agree but I guess my question — is it a responsibility of kube core to enforce a solution to this? Or is this an issue for the network plugin providers to address individually.

I feel this isn't something that kube core can enforce. While not the mainline, it's feasible that _someone_ might want a specialized network plugin that assigns the same address to multiple pods.

**Comment by freehan** [comment] 2019-04-04 21:20
@lzang

**Comment by lzang** [comment] 2019-04-10 21:42
@maktouch Are you able to reproduce the issue? If you can, you can ping me with your cluster info so that we can take a look.

**Comment by maktouch** [comment] 2019-04-11 06:20
I can't reproduce the issue :(

**Comment by freehan** [comment] 2019-05-02 20:44
reopen if needed

**Closed by freehan** 2019-05-02 20:44 UTC
Labels: kind/bug, sig/gcp, sig/network, sig/scheduling, triage/not-reproducible, triage/unresolved

**Comment by velzz** [comment] 2022-10-11 12:15
how to get duplicate pod ips and node ips in promql query

**Comment by jaroslawhartman** [comment] 2023-02-06 16:03
Just a quote from k8s [documentation](https://kubernetes.io/docs/concepts/services-networking/):
> Every [Pod](https://kubernetes.io/docs/concepts/workloads/pods/) in a cluster gets its own unique cluster-wide IP address.

So this could be source of the confusion - as we all learned here: it does not have be always true 😀
