### ISSUE TITLE
Fluentd not ready in scalability suite

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#26053] opened 2016-05-23 07:34 UTC
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-scalability/7705/
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/7705

**Comment by piosz** [comment] 2016-05-23 07:34
cc @gmarek

**Comment by gmarek** [comment] 2016-05-23 07:42
cc @lavalamp

**Comment by bprashanth** [comment] 2016-05-24 00:39
This is a dupe of image pulling flake, I only see one:
`event for fluentd-elasticsearch-e2e-scalability-minion-r1s0: {kubelet e2e-scalability-minion-r1s0} Pull`
and no corresponding "Pulled" event. It's really weird that we timed out on image pulling on a static pod.

@girishkalele can you check the docker logs of the node that pod landed on, and generally grep around kubelet logs for anything suspicious? if you don't find anything, dupe into https://github.com/kubernetes/kubernetes/issues/25277

**Comment by girishkalele** [comment] 2016-05-24 16:48
@bprashanth 

Thanks for the pointer - I will take a look

**Comment by girishkalele** [comment] 2016-05-24 22:18
Duplicate of image pulling flake - only 2 minions experienced fatal pull errors for the fluentd 1.15 image from the GCR repository.
Kubelet and docker logs show no other errors.
Running the docker daemon in -D debug mode might help shed more light on the exact image pull failure that we can provide to the GCE folks.

**Comment by girishkalele** [comment] 2016-05-24 22:19
Duplicate of #25277

**Closed by girishkalele** 2016-05-24 22:18 UTC
Labels: kind/flake, priority/P1, team/cluster
