### ISSUE TITLE
Kubernetes does not reschedule pods if node can't start new pods.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kubernetes#12195] opened 2015-08-04 09:57 UTC
I have a cluster with 3 minions. After rebooting 1 node all the pods were rescheduled to other 2. Unfortunately it was too many pods for the workers so they were not able start them. After 3rd node became online, pods were not rescheduled but stayed in pending state on other nodes instead.

I think that after few tries, pods should be destroyed and started somewhere else.

I am using kubernetes 0.19.3

**Comment by yujuhong** [comment] 2015-08-04 18:06
What's the reason for pods staying in the pending state? You can use `kubectl describe pod pod_name` to find out state/events associated with the pod, and/or paste the output here.

**Comment by lleszczu** [comment] 2015-08-05 08:47
```
W0805 08:27:01.799301    5960 request.go:302] field selector: v1 - events - involvedObject.name - stress-0al3w: need to check if this is versioned correctly.
W0805 08:27:01.799354    5960 request.go:302] field selector: v1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0805 08:27:01.799365    5960 request.go:302] field selector: v1 - events - involvedObject.uid - bff82894-3adb-11e5-a5ed-002590fd6260: need to check if this is versioned correctly.
Name:                           stress-0al3w
Image(s):                       10.4.5.1:5000/admin/stress
Node:                           10.4.5.8/
Labels:                         app=stress
Status:                         Pending
Replication Controllers:        stress (1500/1500 replicas created)
Containers:
No events.
```
It happens under heavy load, and kubelet is logging problems with communicating docker through socket /var/run/docker.sock. I think that after few tries it might be good to just kill that pod and give scheduler a chance to find a better host.

**Comment by erictune** [comment] 2015-08-05 17:03
If kubelet is completely stuck waiting for docker for a few minutes, then
it won't post to its node object, and so the node controller will kill all
the pods on the node.  Seems like this wasn't happening.
If the kubelet gets unstuck, then the pods should eventually start.  Seems
like this didn't happen either.

So, maybe one of the following was happening:
- pods were getting started, but new ones were arriving at the same rate,
so there were always some pods pending.  Did you see that specific pods
were pending for more than, say 5 minutes?
- some kubelet goroutines were blocked on docker, but not the one that
posts the kubelets state to its node object.  If this is happening, then we
may need to add some logic to kubelet to mark itself unhealthy and reject
its unstarted pods.

**Comment by yujuhong** [comment] 2015-08-05 17:42
> Replication Controllers:        stress (1500/1500 replicas created)

@lleszczu, you mentioned that you had 3 minions in the original post, and the second comment suggested that there were at least 1500 pods in your system, i.e., > 500 pods per node. Assuming this is true, the use case is far beyond what kubelet supports today (v1.0: 30~50 pods). It is likely that docker was overwhelmed by the requests, leading to kubelet unable to start the pods. You may run into other random problems as well in this unsupported scale.

- You are using 19.0.3. In v1.0, we limit the max number of pods allowed on a single node/kubelet. This is to prevent kubelet from being over-committed at the first place.
- We are working on reducing the pressure on the docker daemon by managing the pods more efficiently in kubelet.
- Given that scheduler doesn't support "re-scheduling" yet, what kubelet can probably do to recover from this situation is to detect the unusually long docker response time, and fail new pods. This ensures the current running pods are not affected. However, there is nothing to prevent the scheduler from assigning pods to the same node.

We're working on a few issues to help kubelet scale better. Any scale >100 pods per node is current beyond our scope, but we'd love to hear your experiences/issues.

**Comment by yujuhong** [comment] 2015-08-05 17:52
> - some kubelet goroutines were blocked on docker, but not the one that
> posts the kubelets state to its node object.  If this is happening, then we
> may need to add some logic to kubelet to mark itself unhealthy and reject
> its unstarted pods.

In fact, we do have logic in kubelet checking if docker is up, and post it in the node status:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2066

I think part of the problem is that the scale is way beyond what we currently support, and I'm not sure what issue was hit first.

@lleszczu, perhaps you can post kubelet.log, which may shed some light on the internal kubelet status?

**Comment by lleszczu** [comment] 2015-08-05 18:08
@erictune kubelet is working, but docker rejects attempts to start a new container
@yujuhong 
I understand that this is far beyond currently supported 30 pods. What I mean is that kubelet should fail the pod in situation when docker does not respond to requests ( let's say for 5 minutes, or maybe 10 attempts ), and give a chance to scheduler to choose better ( maybe less loaded ) node.
in logs something like this shows almost all the time:
```
pod_workers.go:108] Error syncing pod ef32e187-3b01-11e5-a5ed-002590fd6260, skipping: dial unix /var/run/docker.sock: resource temporarily unavailable
```
Btw. Im not running any workloads right now. I just want to find out in what ways I can break k8s :)

**Comment by yujuhong** [comment] 2015-08-05 18:35
> PS. Health checking logic is checking whether docker version returns any value, and it does in my case, but for example docker ps hangs forever.

That makes sense, and we should definitely improve health checking in kubelet :-)

There are a few issues though. Kubelet is only overwhelmed here because too many pods were assigned to it. Marking the node as not ready (because of the failed health check) would only relieve the problem temporarily, until it happens again. How to accurately convey the resource limit of the node back to the scheduler is important. /cc @dchen1107 and @vishh, who have more insight on the resource management area.


> Btw. Im not running any workloads right now. I just want to find out in what ways I can break k8s :)

Sounds good. I'd appreciate if you can share your results! For example, cluster size, pods per node, and the maximum sustainable workload, etc. It'd also be very helpful if you could let us know that the scale of your workload when filing an issue, so that we can respond accordingly.

**Comment by vishh** [comment] 2015-08-06 21:51
We are working on plumbing resource usage into the scheduler.
We have monit that attempts to reach out to docker periodically and restart
it if it fails to respond.

**Comment by goltermann** [comment] 2015-08-26 22:05
Looks like the questions here were answered.  Please reopen if not.

**Closed by goltermann** 2015-08-26 22:05 UTC
Labels: kind/friction, priority/P1, team/support
