### ISSUE TITLE
federation service controller doesn't always delete underlying services

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#28385] opened 2016-07-01 21:45 UTC
I actually see two problems here.  The state here is that the tests have run successfully to completion.

``` console
% krun -q kubectl --context=federation-cluster get svc --all-namespaces                                       
% krun -q kubectl --context=federation-e2e-gce-us-central1-c get svc --all-namespaces | grep federated-service
zsh: done       krun -q kubectl --context=federation-e2e-gce-us-central1-c get svc  | 
zsh: exit 1     grep federated-service
% ^1-c^1-b
krun -q kubectl --context=federation-e2e-gce-us-central1-b get svc --all-namespaces | grep federated-service
e2e-tests-federated-service-51tvg   federated-service       10.0.247.207   104.197.14.220   80/TCP              35m
e2e-tests-federated-service-qfx5a   federated-service       10.0.48.177    104.198.194.87   80/TCP              36m
% krun -q kubectl --context=federation-e2e-gce-us-central1-c get ns
NAME          STATUS    AGE
default       Active    2d
federation    Active    1d
kube-system   Active    2d
% ^1-c^1-b
krun -q kubectl --context=federation-e2e-gce-us-central1-b get ns
NAME                                STATUS    AGE
default                             Active    2d
e2e-tests-federated-service-51tvg   Active    36m
e2e-tests-federated-service-a4pmu   Active    37m
e2e-tests-federated-service-dvrzj   Active    38m
e2e-tests-federated-service-qfx5a   Active    37m
kube-system                         Active    2d
```
- [ ] We're not deleting the namespace from the second cluster.
- [x] It seems sometimes the services aren't deleted when the parent service goes away.  That's hidden in `1-c`.  We should add a test.

@kubernetes/sig-cluster-federation

**Comment by mml** [comment] 2016-07-01 21:45
@quinton-hoole guessing at priority.

**Comment by quinton-hoole** [comment] 2016-07-01 22:00
@mml By design we do not delete underlying services. It's a slightly complex problem.  If the services were already present in the cluster before creating the federated service, we adopt them.  And we don't want to delete such adopted services (as other clients are probably using them).  And it's not ingeneral possible to know which ones we created and which ones we adopted (without applying labels, or storing some persistent state, neither of which we really want to do). 

The namespace lingering is a test problem.  The test that creates the underlying namespaces is not cleaning them up properly.  That's easily and worth fixing.  Neither are really P1's though.

**Comment by dims** [comment] 2016-11-17 12:48
This needs to be triaged as a release-blocker or not for 1.5 @quinton-hoole @nikhiljindal

**Comment by madhusudancs** [comment] 2016-11-17 19:05
The behavior that this issue is asking for is the behavior right now and unfortunately we are not sure how this got in. We do not want automatic unintended deletion of underlying services, but instead do this with explicit cascading deletion that @nikhiljindal is working on. 

@nikhiljindal will correct the non-cascading deletion behavior as part of Issue #36799. And then implement cascading deletion separately. 

So closing this issue as a duplicate.

**Closed by madhusudancs** 2016-11-17 19:05 UTC
Labels: area/cluster-federation, area/test, priority/P2, team/control-plane
