### ISSUE TITLE
Cannot list custom objects defined by CRD with non-conventional pluralization

### ISSUE THREAD

**Issue by ayj** [kubernetes/kubernetes#51639] opened 2017-08-30 17:38 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`kubectl get route-rules.config.istio.io` fails and prints "the server doesn't have a resource type "route-rules" in group "config.istio.io" with the following CRD.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: route-rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: route-rules
    singular: routerule
  version: v1alpha2
```

**What you expected to happen**:

`kubectl get route-rules.config.istio.io` should return the list of custom objects defined by the `route-rules.config.istio.io` CRD or `No resources found` if no objects have been created yet.

**How to reproduce it (as minimally and precisely as possible)**:

### Non-working example
```
$ cat bad.yaml 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: route-rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: route-rules
    singular: routerule
  version: v1alpha2

$ kubectl apply -f bad.yaml 
customresourcedefinition "route-rules.config.istio.io" created

$ kubectl get route-rules.config.istio.io
the server doesn't have a resource type "route-rules" in group "config.istio.io"
```

**Anything else we need to know?**:

The following CRD _does_ work as expected.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: routerules
    singular: routerule
  version: v1alpha2

$ kubectl get routerules.config.istio.io
No resources found
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE 1.7.3 ALPHA
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ayj** [comment] 2017-08-30 17:39
/cc @lavalamp, @mandarjog, @kyessenov

ref https://github.com/istio/pilot/issues/1107

**Comment by lavalamp** [comment] 2017-08-30 20:53
@mbohlool @pwittrock

**Comment by alindeman** [comment] 2017-08-31 02:12
I poked at this a bit, and I think it may be more of a CLI UI/UX issue.

While the CLI reports `"customresourcedefinition "routerules.config.istio.io" created"`, `kubectl get` looks up based on _kind_ (not singular _or_ plural name).

Specifically, if we change `kind` to something completely arbitrary like `Noodle`:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: Noodle
    plural: routerules
    singular: routerule
  version: v1alpha2
```

And apply it:

```
$ kubectl apply -f noodle.yml
customresourcedefinition "routerules.config.istio.io" created
```

We get the expected `NotFound` when listing `noodle.config.istio.io` or `noodles.config.istio.io`:

```
$ kubectl get noodle.config.istio.io
Error from server (NotFound): Unable to list "noodles" ...
$ kubectl get noodles.config.istio.io
Error from server (NotFound): Unable to list "noodles" ...
```

```
$ kubectl get routerules.config.istio.io
the server doesn't have a resource type "routerules" in group "config.istio.io"
```

**Comment by sttts** [comment] 2017-09-01 08:21
If anybody wants to work on this, here are some pointers:

- The GET request to the server uses what is called a "resource name" (lower-case, plural, part of the HTTP path, compare https://blog.openshift.com/kubernetes-deep-dive-api-server-part-1/). The resource name for a CRD is the plural name, i.e. the path is `/apis/<group>/namespace/default/<plural>`.

- kubectl does certain transformations ("REST mappings") from the string given on the command line to the resource name. There are essentially two:
  - shortcut expansion (e.g. `kubectl get <CRD-plural>` or `kubectl get <CRD-short-name>`): it uses discovery information to build up the mapping, namely: https://github.com/kubernetes/kubernetes/blob/8895f314b478714a561dc1fc79d7411d31f91dc6/pkg/kubectl/cmd/util/shortcut_restmapper.go#L79 on the kubectl side and https://github.com/kubernetes/kubernetes/blob/33e50da9f403c6d23791a5936dd79c7281fdfd7f/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go#L112 on the CRD server side.
  - default mapping using a plural-heuristic (e.g. `kubeget get <lower-case-CRD-kind>s.<group>`): compare https://github.com/kubernetes/kubernetes/blob/b0b711119b48854e0b73805e42be2bcc4b2bd604/staging/src/k8s.io/apimachinery/pkg/api/meta/restmapper.go#L142 for the apimachinery code, called from kubectl at https://github.com/kubernetes/kubernetes/blob/f14618a56b69d0968528e714898d2d1df08b2312/staging/src/k8s.io/client-go/discovery/restmapper.go#L83.

The problem with the second expansion (of e.g. `noodles.config.istio.io`) seems to be that it maps `noodles.config.istio.io` as a GroupKind to the resource name `noodles`, but `/apis/<group>/namespace/default/noodles` does not exist.

Maybe @deads2k or @liggitt can confirm or correct my quick observations above.

**Comment by deads2k** [comment] 2017-09-01 11:27
> Maybe @deads2k or @liggitt can confirm or correct my quick observations above.

It sounds plausible.  I'd be happy to see the "let's guess at a plural" code gone.

**Comment by ash2k** [comment] 2017-09-13 00:14
Probably caused by #49948.

**Comment by mbohlool** [comment] 2017-09-18 20:20
This does not seem to be an api-machinery problem. I will remove sig-api-machinery label and add sig cli.

**Comment by liggitt** [comment] 2017-09-18 20:50
it was api-machinery, fixed in https://github.com/kubernetes/kubernetes/pull/50012

**Closed** 2017-09-18 20:51 UTC
Labels: area/third-party-resource, kind/bug, sig/api-machinery
