### ISSUE TITLE
`kubectl edit <list>` opens editor multiple times

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#20519] opened 2016-02-02 22:06 UTC
Invoking `edit` on a list should open the editor once with the entire List. It currently opens the editor multiple times, once per object.
1. Create several namespaces (a,b,c,d)
2. Do `kubectl edit namespaces`

**Comment by bgrant0607** [comment] 2016-02-02 22:48
cc @janetkuo

**Comment by kargakis** [comment] 2016-03-03 10:07
I think this is intentional

**Comment by liggitt** [comment] 2016-03-03 12:58
I hope not… it's almost unusable to do it that way, and it didn't used to do that. Editing a list of objects at once is much more understandable, imo

**Comment by janetkuo** [comment] 2016-03-17 07:42
This change was made in #15980 as a work-around to fix 2 bugs when editing a list:
1) panic when editing a list object
2) editing a list of objects failed to update (without an error)

**Comment by kargakis** [comment] 2016-11-01 16:02
@kubernetes/kubectl this has regressed 

Need to dig through the latest edit changes and find the offender.

**Comment by smarterclayton** [comment] 2016-11-01 16:06
Setting p1 since this is a regression.

**Comment by liggitt** [comment] 2016-11-01 16:24
With the fix, please add a test to make sure it doesn't regress in the future

**Comment by kargakis** [comment] 2016-11-01 16:46
It seems this was broken shortly after being fixed in https://github.com/kubernetes/kubernetes/pull/25085

**Comment by ymqytw** [comment] 2016-11-01 16:48
I will look into it.

**Comment by kargakis** [comment] 2016-11-01 17:00
@ymqytw I've tested it locally and all you need to do is to remove Visit since it visits Items of a List separately.

**Comment by ymqytw** [comment] 2016-11-01 18:15
@kargakis If I remove Visit it will break the test in `test-cmd.sh` that added from #25085.

**Comment by ymqytw** [comment] 2016-11-01 19:10
cc: @pwittrock

**Comment by kargakis** [comment] 2016-11-02 13:46
@ymqytw I was able to run --recursive and it works fine (opens all files under the directory you pass in a list if there is no error). What's the exact failure of the test? Maybe @metral can weigh in since he authored the original PR. I had missed the [part](https://github.com/kubernetes/kubernetes/pull/25085#issuecomment-219450790) where he said that the editor would open resources separately:)

**Comment by kargakis** [comment] 2016-11-03 10:55
The difference is that by opening the objects one by one, we get to skip invalid objects so --recursive is still able to edit other objects. By opening all the objects in a list, an invocation to a directory that contains files with errors will never open the editor and instead require those errors to be fixed ie. --recursive still continues to work but only on directories with valid objects.

**Comment by liggitt** [comment] 2016-11-03 14:44
if you ask to edit 50 objects and one is invalid, I'd rather see a useful error than 49 editors and an error

**Comment by kargakis** [comment] 2016-11-03 14:48
> if you ask to edit 50 objects and one is invalid, I'd rather see a useful error than 49 editors and an error

Agreed.

**Comment by kargakis** [comment] 2016-11-03 14:49
Opened https://github.com/kubernetes/kubernetes/pull/36148

**Comment by ymqytw** [comment] 2016-11-03 15:48
@kargakis Thanks.

**Comment by metral** [comment] 2016-11-03 16:21
> if you ask to edit 50 objects and one is invalid, I'd rather see a useful error than 49 editors and an error

![doh](http://www.talendia.com/wp-content/uploads/2015/11/Simpsons-Homer-DOH-1024x796-256x256.png)

Thanks for the fix @kargakis. Much appreciated.

**Closed** 2016-11-04 01:20 UTC
Labels: component/kubectl, priority/P1, team/ux
