### ISSUE TITLE
apiserver memory usage increased by 10-20% after addition of admission metrics

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56061] opened 2017-11-20 14:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Four medium-scale e2e performance test runs failed recently due to errors such as the following:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135
Expected error:
    <*errors.errorString | 0xc42fa524e0>: {
        s: "Container kube-apiserver-e2e-scalability-master/kube-apiserver is using 1506.86328125/1500 MB of memory",
    }
    Container kube-apiserver-e2e-scalability-master/kube-apiserver is using 1506.86328125/1500 MB of memory
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:365
```

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8046
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8059
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8086
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8136
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8177
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8182
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8191
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8196
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/1
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8215
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8232
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8248
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8256
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8275
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8276
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8297
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8300
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8302
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8333
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8337
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8361
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8367
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8371

@kubernetes/sig-scalability-bugs 
@kubernetes/sig-api-machinery-bugs 
/priority failing-test

**Comment by porridge** [comment] 2017-11-20 14:27
Three most recent failures are seen on this graph.

![apiserver](https://user-images.githubusercontent.com/489420/33023004-264118f8-ce07-11e7-852d-8f0d7cbb36cf.png)

This graph clearly shows a bi-modal distribution: ~900MiB vs ~1400MiB of memory usage across runs.
Does anyone from the @kubernetes/sig-api-machinery-bugs know why it could be so?

**Comment by porridge** [comment] 2017-11-20 14:33
Umbrella bug: https://github.com/kubernetes/kubernetes/issues/56062

**Comment by porridge** [comment] 2017-11-21 20:41
In a [recent run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8191) the usage is **much** higher:
>  "Container kube-apiserver-e2e-scalability-master/kube-apiserver is using 2712.40625/1500 MB of memory",

**Comment by porridge** [comment] 2017-11-22 07:28
Dear sig-api-machinery leads @deads2k @lavalamp do you have any thoughts about why apiserver's memory usage might vary by 3x between mostly-identical performance test runs? Or how to approach debugging this?

**Comment by porridge** [comment] 2017-11-23 12:03
/assign
My short-term plan is to look at the usage gathering mechanism to see if we can get a timeline of memory usage during a given test, and compare it against a test which uses little memory.
I'll also check if there is a correlation between usage and the order of load/density execution.

**Comment by porridge** [comment] 2017-11-23 17:46
My hunch was right: apiserver RAM usage during density test peaks at values:
- between 870 and 1030 MiB, when density test runs first, vs
- between 1200 and 1500 MiB (with [one exception](https://github.com/kubernetes/kubernetes/issues/56061#issuecomment-346154263)) when density runs after load test

This poses a few interesting questions:
1. Is this a memory leak? i.e. can memory use grow in an unbounded way?
1. It would be interesting to find out what "leaks" during the load test. I suspect it's some cache which does not have time to expire, and is not invalidated automatically when the load test's namespaces are deleted. Perhaps it should?
1. If the memory usage is bounded, then should the load test be trying to reach that bound? apparently it does not at the moment (since it grows further during density test). Should it try harder?
1. Do other components (e.g. etcd, controller manager) also exhibit this bi-modal resource usage pattern?
1. This behavior obviously hurts test repeatability. How do we mitigate it for the sake of scalability tests? should we bounce the apiserver (and other components) between the tests?

@wojtek-t @gmarek @shyamjvs what are your thoughts guys?

**Comment by porridge** [comment] 2017-11-23 17:49
This is the top flake of the 100-node scalability tests, I think we should at least bump the memory limit for the time being
/priority critical-urgent
@shyamjvs please add to v1.9

**Comment by wojtek-t** [comment] 2017-11-23 18:46
Re why some runs are significantly better - I didn't take a closer look, but my bet is that it depends on the fact whether load test is running first (before density) or second (after density test).

The fact that we are accumulating some information in caches is expected, and working as intended. To get expected difference we would need to compute the expected size (max cache size times average object size).

**Comment by shyamjvs** [comment] 2017-11-23 18:46
@porridge I think we should try to understand the reason for this. We might increase the limit, but imo we should do that only after understanding the cause.
As this is not a release-blocking job, we're relatively at ease in debugging this one.

Could we get the graph or at least the values of usage for a longer time period? Will help us know around what time this started happening.

**Comment by porridge** [comment] 2017-11-24 10:00
On Thu, Nov 23, 2017 at 7:47 PM, Shyam JVS <notifications@github.com> wrote:

> @porridge <https://github.com/porridge> I think we should try to
> understand the reason for this.
>

+1

> We might increase the limit, but imo we should do that only after
> understanding the cause.
>

I disagree with this one, though. I don't think we gain anything from the
frequent flakes, it's just a distraction, especially for me since currently
I'm trying to track every test failure by putting a link to the gubernator
page from a relevant bug.

> Could we get the graph or at least the values of usage for a longer time
> period? Will help us know around what time this started happening.
>
I'll come up with one.

**Comment by shyamjvs** [comment] 2017-11-24 10:07
SG. Though I don't remember a single case where thresholds were bumped down
(they're always bumped up). Also once those flakes go green, it
incentivizes one to care less about fixing it imo :)

I wouldn't push too hard on this one though.

**Comment by sttts** [comment] 2017-11-24 11:01
Any chance to get a pprof `top`output from the apiserver process, i.e. what is described in http://www.integralist.co.uk/posts/profiling-go/ as memory analysis? We enable `--profiling` by default. So this should be possible via `go tool pprof http://<apiserver>/debug/pprof/heap`.

**Comment by porridge** [comment] 2017-11-24 11:15
I'll take a stab at it. If not automatically on every test, then I'll at
least run it on a manual run.

**Comment by porridge** [comment] 2017-11-24 11:45
@shyamjvs This pattern was there ever since we keep records (which is not a lot - August 25th).
See graph:
![chart](https://user-images.githubusercontent.com/489420/33209195-0ddc7558-d115-11e7-9ab8-f3ba97d694f5.png)
There is a clear jump by 100/200MiB respectively, not so long ago, I'll get the commit range when it was introduced.

**Comment by wojtek-t** [comment] 2017-11-24 11:47
Regarding the pattern why some runs are visibly better than others - I already wrote why it can be like that:
https://github.com/kubernetes/kubernetes/issues/56061#issuecomment-346681868

**Comment by porridge** [comment] 2017-11-24 12:03
Yes Wojtek, that question was solved back in  https://github.com/kubernetes/kubernetes/issues/56061#issuecomment-346674103.
The partition to red vs blue line is exactly that.
We're now looking what caused that step in both lines near the right-hand side of the graph.

**Comment by shyamjvs** [comment] 2017-11-24 12:05
The fact that the order of those tests is affecting the usage seems to be there since a long time.
But we never had it exceed our bounds earlier - see that runs 7818 - 8045 (more than 200 runs) of https://k8s-testgrid.appspot.com/sig-scalability-gce#gce were continuously green (except for a couple of other flakes).

**Comment by shyamjvs** [comment] 2017-11-24 12:06
> I'll get the commit range when it was introduced.

Sounds great - thanks.

**Comment by porridge** [comment] 2017-11-24 12:11
Looks like it was between run 7965 and 7966. There was only one PR merged between these two runs:
https://github.com/kubernetes/kubernetes/pull/55183
@jpbetz do you think it's expected and intended that your changes increased apiserver memory usage by 100-200MiB on a 100-node cluster?

**Comment by shyamjvs** [comment] 2017-11-24 12:13
That sounds very likely to increase apiserver mem usage as it's adding a bunch of instrumentation to admission webhooks.

**Comment by porridge** [comment] 2017-11-24 12:23
Increase - yes. By 10-20%... not sure if that's intended. That's what I'd like to clarify.
Changing title to reflect the new finding.

**Comment by porridge** [comment] 2017-11-24 12:42
Let's focus this bug on the usage increase caused by #55183. I filed #56340 to track the less urgent bi-modal usage problem.

**Comment by shyamjvs** [comment] 2017-11-24 12:48
Thanks for creating the graph and filing the bugs.

**Comment by jpbetz** [comment] 2017-11-25 17:30
@porridge No, this amount of memory increase was not intended. We’ll need to adjust the instrumentation to get the utilization down to something more reasonable.

We added counter and histogram metrics at a per admission controller/webhook granularity. The counters are cheap. The histograms can be tuned to reduce memory footprint.  We’ll need to adjust them till we get into a more reasonable range, I’m thinking <20MB.

**Comment by jpbetz** [comment] 2017-11-25 17:46
We also can reduce the number of labels used.  I’ll send out a PR tonight.

**Comment by wojtek-t** [comment] 2017-11-26 11:38
@jpbetz - histograms are relatively cheap. So if these are causing that much overhead, we have really a lot of difference labels there.
But I've quickly skimmed your PR and you seem to be also using `SummaryVec` - from my experience this is pretty expensive. And my guess is that it may be causing majority of this memory increase.

**Comment by jpbetz** [comment] 2017-11-27 05:58
Thanks @wojtek-t. That's a useful insight. I'll remove the `SummaryVec` entirely from all but the top level metric.

**Comment by porridge** [comment] 2017-11-27 06:14
@wojtek-t can you please approve for milestone?

**Comment by wojtek-t** [comment] 2017-11-27 07:00
Approved - though, the PR fixing it is already queued in the submit queue, so should be merged pretty soon.

**Comment by porridge** [comment] 2017-11-27 07:13
ACK.  In progress
ETA: Today
Risks: none

**Closed** 2017-11-27 08:05 UTC
Labels: kind/bug, milestone/needs-attention, priority/critical-urgent, priority/failing-test, sig/api-machinery, sig/scalability, status/approved-for-milestone
