### ISSUE TITLE
Add a user parameter when do exec 

### ISSUE THREAD

**Issue by max88991** [kubernetes/kubernetes#80782] opened 2019-07-31 02:50 UTC
**What would you like to be added**:

Add parameter `User` in Kubernetes CRI `ExecRequest`

**Why is this needed**:
In Runtime-Spec, Process has the `User` [definition](https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L39) , 
considering that the `Exec` operation starts a process at the target location, and Kubernetes CRI is the standard that actually describes the operation, this parameter is actually needed.

**Comment by mattjmcnaughton** [comment] 2019-07-31 12:32
Could you share more about the ramifications of the k8s CRI not including the parameter in `ExecRequest`?

**Comment by liggitt** [comment] 2019-07-31 22:11
this is a duplicate of https://github.com/kubernetes/kubernetes/issues/30656

see discussion in that issue

/close

**Closed by liggitt** 2019-07-31 22:11 UTC
Labels: kind/feature, sig/node
