### ISSUE TITLE
e2e flake: Cluster level logging using GCL should check that logs from containers are ingested in GCL

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41668] opened 2017-02-17 23:19 UTC
The test has been [extremely flaky in the past few days](https://k8s-testgrid.appspot.com/sq-blocking#gci-gce&width=20&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Cluster%5C%20level%5C%20logging%5C%20using%5C%20GCL%5C%20should%5C%20check%5C%20that%5C%20logs%5C%20from%5C%20containers%5C%20are%5C%20ingested%5C%20in%5C%20GCL).

Some failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4333
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4329
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4326

/cc @Crassirostris @piosz

**Comment by Crassirostris** [comment] 2017-02-17 23:29
Thanks!

Closing as duplicate of https://github.com/kubernetes/kubernetes/issues/41647

**Closed by Crassirostris** 2017-02-17 23:29 UTC
Labels: area/logging, area/test, kind/flake, priority/failing-test
