### ISSUE TITLE
Init Container will be removed by kubeGC when we set --maximum-dead-containers-per-container=0 

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#77859] opened 2019-05-14 09:12 UTC
**What happened**:
1.set --maximum-dead-containers-per-container=0
2.  create a deploy with a init container
3. watch the pod status , you will see the change 
```
[root@hpa-vm:~]$ kubectl get pod -w
NAME          READY   STATUS    RESTARTS   AGE
nginx-f8jfv   1/1     Running   0          30s
NAME          READY   STATUS     RESTARTS   AGE
nginx-f8jfv   0/1     Init:0/1   0          95s
nginx-f8jfv   1/1     Running    0          100s
```

**What you expected to happen**:
init container wont't be removed. 
   _**we need separate the containerGC and initContainerGC**_

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Pingan2017** [comment] 2019-05-14 09:15
/sig node
@kubernetes/sig-node-bugs 
@kubernetes/sig-node-feature-requests

**Comment by Pingan2017** [comment] 2019-05-14 09:33
#62362

**Comment by mattjmcnaughton** [comment] 2019-05-14 13:41
Hi @Pingan2017 :)

Thanks for sharing this.

Do you mind providing a little more detail on the actual behavior and the expected behavior? I think I'm not totally following why its a problem to remove the init container if its already completed successfully. Is the issue that Kubelet thinks it hasn't completed successfully and keeps on trying to rerun it, leading to repeated execution of the init container?

**Comment by Pingan2017** [comment] 2019-05-15 02:29
> 
>  Is the issue that Kubelet thinks it hasn't completed successfully and keeps on trying to rerun it, leading to repeated execution of the init container?

Yes!  Kubelet will run the init container repeatedly.
pod flapping between Running/Init

```
[root@hpa-vm:~]$ kubectl get pod -w
NAME          READY   STATUS    RESTARTS   AGE
nginx-f8jfv   1/1     Running   0          17h
NAME          READY   STATUS     RESTARTS   AGE
nginx-f8jfv   0/1     Init:0/1   0          17h
nginx-f8jfv   1/1     Running    0          17h
nginx-f8jfv   0/1     Init:0/1   0          17h
nginx-f8jfv   1/1     Running    0          17h
```

**Comment by mattjmcnaughton** [comment] 2019-05-20 14:31
I was doing a little more research on this, and I realized that `--maximum-dead-containers-per-container` has been marked deprecated, with the recommendation to instead use `--eviction-hard` or `--eviction-soft`. 

@Pingan2017 do you know if this problem remains when using `--eviction-hard/--eviction-soft`? If no, thoughts on closing this issue in favor recommending anyone experiencing this issue utilize the non-deprecated behavior?

Here's some more info on `--eviction-hard` and `--eviction-soft` (https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy).

**Comment by Pingan2017** [comment] 2019-05-22 06:18
@mattjmcnaughton 
I'm afraid not.   Eviction also call the kubeGC to delete containers before evict pods

**Comment by Pingan2017** [comment] 2019-05-22 06:21
@kubernetes/sig-node-bugs  Could someone take a look?

**Comment by mattjmcnaughton** [comment] 2019-05-22 18:36
> @mattjmcnaughton
> I'm afraid not. Eviction also call the kubeGC to delete containers before evict pods

Hmm, but if the kubeGC evicts the pods, than wouldn't we expect it to delete the init container?

At a higher level, can you share the use case for setting `--maximum-dead-containers-per-container=0`, and confirm that we couldn't accomplish something similar by not setting `--maximum-dead-containers-per-container=0` and instead setting `--eviction-hard`.

Definitely not opposed to looking into this further, but since the functionality is deprecated, just want to confirm its a sensible investment. Thanks for your patience :)

**Closed** 2019-10-19 20:41 UTC
Labels: kind/bug, kind/feature, lifecycle/rotten, sig/node
