### ISSUE TITLE
Multiple Third Party Resources failing in 1.3.0-alphav

### ISSUE THREAD

**Issue by nowprovision** [kubernetes/kubernetes#26152] opened 2016-05-24 09:46 UTC
Using latest release of kube-apiserver and kubectl, with etcd 2.2.1 and a fresh data directory

`Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.4", GitCommit:"9990f843cd62caa90445cf76b07d63ba7b5c86fd", GitTreeState:"clean", BuildDate:"2016-05-17T21:58:54Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.4", GitCommit:"9990f843cd62caa90445cf76b07d63ba7b5c86fd", GitTreeState:"clean", BuildDate:"2016-05-17T21:51:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
`

I can create a ThirdPartyResource type okay with lets say a name of student.stable.acme.com via ./kubectl create -f student-type-setup.yaml, this returns a sucess message.  I then can get and list via curl at /apis/stable.acme.com/v1/students no problem.

However if I add another third party resource type say course.stable.acme.com, I can't list from this, server returns a 404, even though it was added successfully. 

More strangely, if at this point I restart the api server, 'courses' now lists okay, but voila 'student's no longer list.  Guessing as my etcd knowledge is very very limited - it's almost as if they are keyed to the same key. At this stage I'm guessing this is related to storage.

**Comment by brendandburns** [comment] 2016-06-23 23:36
Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/23831

**Closed by brendandburns** 2016-06-23 23:36 UTC
Labels: team/CSI-API Machinery SIG
