### ISSUE TITLE
Containers from init-containers section do not execute during node reboots

### ISSUE THREAD

**Issue by jakub-d** [kubernetes/kubernetes#36485] opened 2016-11-09 08:15 UTC
BUG REPORT
**Kubernetes version**
v1.4.3+coreos.0

**Environment**:
- **Cloud provider or hardware configuration**:
Bare metal CoreOS installation. 3 management nodes + 2 worker nodes.
- **OS** (e.g. from /etc/os-release):
`CoreOS stable (1185.3.0)`
- **Kernel** 
`4.7.3-coreos-r2`

**What happened**:
I added an `init-container` to the `kube-scheduler.yaml` file in `/etc/kubernetes/manifests` directory. It was executed once after the yaml file modification. When I rebooted the node running this POD, the POD was restarted but the `init-container` did not execute:

The kube-scheduler.yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
      {
        "image": "quay.io/coreos/hyperkube:v1.4.3_coreos.0",
        "name": "wait-for-master",
        "command": [ "/bin/bash", "-c", "while ! timeout 1 bash -c \"/kubectl --server=http://127.0.0.1:8080/ cluster-info\"; do sleep 1; done" ]
      }
    ]'
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: quay.io/coreos/hyperkube:v1.4.3_coreos.0
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
```

The POD description after the node reboot:
```
Name:           kube-scheduler-10.54.147.6
Namespace:      kube-system
Node:           10.54.147.6/10.54.147.6
Start Time:     Wed, 09 Nov 2016 07:51:35 +0100
Labels:         <none>
Status:         Running
IP:             10.54.147.6
Controllers:    <none>
Init Containers:
  wait-for-master:
    Container ID:       docker://ff5ef0e759eb332c50fcc117a5758c41080835addbd76e33eb60cdde10d9587b
    Image:              quay.io/coreos/hyperkube:v1.4.3_coreos.0
    Image ID:           docker://sha256:5d3bc50f81574bc41952e13862b04b98f310ab60601ff990e7267a4ba5227e8b
    Port:
    Command:
      /bin/bash
      -c
      while ! timeout 1 bash -c "/kubectl --server=http://127.0.0.1:8080/ cluster-info"; do sleep 1; done
    State:                      Terminated
      Reason:                   Completed
      Exit Code:                0
      Started:                  Tue, 08 Nov 2016 14:17:27 +0100
      Finished:                 Tue, 08 Nov 2016 14:17:35 +0100
    Ready:                      True
    Restart Count:              0
    Volume Mounts:              <none>
    Environment Variables:      <none>
Containers:
  kube-scheduler:
    Container ID:       docker://03e40bb84d477e6a284c4bfdf677d15135fe78785b17ae62d09cd04063f81aec
    Image:              quay.io/coreos/hyperkube:v1.4.3_coreos.0
    Image ID:           docker://sha256:5d3bc50f81574bc41952e13862b04b98f310ab60601ff990e7267a4ba5227e8b
    Port:
    Command:
      /hyperkube
      scheduler
      --master=http://127.0.0.1:8080
      --leader-elect=true
    State:                      Running
      Started:                  Wed, 09 Nov 2016 07:51:36 +0100
    Last State:                 Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Tue, 08 Nov 2016 20:50:42 +0100
      Finished:                 Wed, 09 Nov 2016 07:48:44 +0100
    Ready:                      True
    Restart Count:              4
    Liveness:                   http-get http://127.0.0.1:10251/healthz delay=15s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:              <none>
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         True 
  PodScheduled  True 
No volumes.
QoS Class:      BestEffort
Tolerations:    <none>
```

**How to reproduce it**
Create a pod with the `cloud-init` section and pin it to one node. Reboot the node several times and check if the `cloud-init` container was executed.

**Comment by pskrzyns** [comment] 2016-11-15 16:08
cc @smarterclayton @kubernetes/sig-node

**Comment by smarterclayton** [comment] 2016-11-15 16:55
@kubernetes/sig-apps

**Comment by bgrant0607** [comment] 2016-11-17 04:06
Init containers shouldn't re-execute so long as local storage isn't lost, and reboot won't necessarily (deliberately) cause the pod to be deleted.

**Comment by jakub-d** [comment] 2016-11-17 06:52
> Init containers shouldn't re-execute so long as local storage isn't lost, and reboot won't necessarily (deliberately) cause the pod to be deleted.

@bgrant0607 - thank you for looking into that. Does it mean that init-containers is limited only to storage initialization? I expected that we can use that in cases when applications have dependencies (for example they need a working database in order to start up).

Can we add an `executeBefore` parameter to init-containers? Available values for the parameter would be: `podCreation`, `podRestart`, `always`.

**Comment by smarterclayton** [comment] 2016-11-17 17:25
As we originally described the PR, init containers would run in all cases
that a pod restart was required.  I think it's a violation of the implied
(expected) semantics not to run init containers (which must be idempotent)
when 0 containers are running in the pod due to restart.

I think this may just be a bug that we never directly addressed in the pod
sync loop (because restart of the whole kubelet is handled slightly
differently).

On Wed, Nov 16, 2016 at 10:52 PM, Jakub Dlugolecki <notifications@github.com

**Comment by dchen1107** [comment] 2016-11-17 18:10
@smarterclayton Agreed with you on the semantics of the init containers by design. The problem is that the PodCondition: Initialized is checkpointed, and Kubelet doesn't distinguish the recovery phase from the normal operation phase.

**Comment by yujuhong** [comment] 2016-11-17 19:07
I don't think "pod restart" would cause init container to be rerun, if "infra container restart" is counted as pod restart. I just tried killing the infra container, and no init container was restarted. If this is not the intended behavior, then the current logic in the code is flawed.

As for reboots, I don't think there are any difference in the kubelet recovery phase in this case. Kubelet needs to restart the infra container anyway, and it could easily use that as an indicator to rerun init container if needed.

**Comment by euank** [comment] 2016-11-17 19:53
An init container causes the whole pod to be killed/restarted, right, so it would count as a pod restart.

I would also expect the init container to run after that sort of event because e.g. the ip might have changed.

**Comment by yujuhong** [comment] 2016-11-17 20:07
> An init container causes the whole pod to be killed/restarted, right, so it would count as a pod restart.

I think you meant "infra"

I was describing the existing implementation since both @smarterclayton and @dchen1107 seem to think that this works today when infra container is restarted, and that the bug only exists in kubelet restarts.

**Comment by smarterclayton** [comment] 2016-11-17 20:08
The original intent in the code (when I wrote it) was that infra container
restart should rerun initialization, specifically for pod IP changes.

**Comment by bgrant0607** [comment] 2016-11-17 23:21
cc @kow3ns

**Comment by Kuckkuck** [comment] 2017-04-03 08:09
I have the same issue, when a node reboots because of a CoreOS update, my elasticsearch init containers, which set vm.max_map_count=262144 via init container, are down, because the values wasn't set during reboot. When I kick the pods, the container comes up.

**Comment by smarterclayton** [comment] 2017-04-03 12:03
Any node restart should re-run init containers, so we should fix that if it no longer happens.  Same for infracontainer recreation.

**Comment by yujuhong** [comment] 2017-06-09 00:03
@smarterclayton, moving the discussion back to the main thread to not pollute the other issue.
https://github.com/kubernetes/kubernetes/issues/47186#issuecomment-307246119
> I think that was even in the original implementation, but that was when the
container sync startup code was nightmarish and hard to clearly communicate.

That's a fair point, although I am not sure it's less complex now and init containers contributed a lot to the complexity too... We also need better unit tests.

I looked at the code briefly, and I think the most straightforward solution is to prune all init containers whenever we need to (re)start the podsandbox. That could be a start.

**Comment by yujuhong** [comment] 2017-06-09 22:59
A solution that's more aligned with how SyncPod works today (i.e., making them more like regular containers):
 * Compute init containers to start/stop in [computePodContainerChanges](https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L427) and include the result in the `podContainerSpecChanges` struct.
 * Whenever kubelet needs to create a PodSandbox, purge (i.e., remove) all the init containers in the pod.

/cc @yifan-gu who tried refactoring the `SyncPod` logic in the previous releases.

**Comment by obeattie** [comment] 2017-06-25 10:55
This has bitten us pretty hard in production – we have several uses of init containers to perform initialisation of the network (eg. setting up tunnel interfaces). If the host restarts this state is obviously lost.

**Comment by kfox1111** [comment] 2017-06-25 23:58
I think this will eventually bite the openstack on k8s projects. Didn't realize this behavior. Having it be configurable per init-container would be great.

**Comment by munnerz** [comment] 2017-07-04 12:09
What are the chances of this being classed as a bug and backported to supported Kubernetes versions? This is quite a problematic behaviour that will require me to either:

a) build my health check to check for the existence of a particular file/some state, and trigger a pod recreation in the event it's not present (thus also preventing me allowing the pod to ever restart, and causing it to only ever be recreated), or 

b) promoting my init container to a sidecar that sleeps (and making my main process wait for these sidecars to finish their processing, potentially through a tmpfs/in memory emptyDir)

**Comment by yujuhong** [comment] 2017-07-10 18:04
> What are the chances of this being classed as a bug and backported to supported Kubernetes versions? This is quite a problematic behaviour that will require me to either:

I sent a fix #45799, but the change is quite large and porting it back could be difficult.

**Comment by simonswine** [comment] 2017-07-11 08:51
@yujuhong I think you linked to wrong PR: https://github.com/kubernetes/kubernetes/pull/47599. Thanks for fixing that, I can have a look at backporting it, but we need to make sure it will be considered as a bugfix and accpeted for backporting

**Comment by yujuhong** [comment] 2017-07-11 17:58
> @yujuhong I think you linked to wrong PR: #47599. Thanks for fixing that, I can have a look at backporting it, but we need to make sure it will be considered as a bugfix and accpeted for backporting

Oops.. I fixed that. Thanks. 

I am not sure about backporting such a huge change and risking the possibility of destabilizing the previous releases. For 1.7, this may still be viable, though not very desirable. For 1.6, there were two different implementations (cri and pre-cri) and quite a lot of change has happened since then.

Init containers have been there for many releases and I don't think this feature has ever worked as intended. Even though this is a bug, it's not technically a regression. I would definitely not recommend patching 1.6, and leaning towards not patching 1.7 too.

@smarterclayton @dchen1107 thoughts?

**Closed** 2017-08-17 02:50 UTC
Labels: area/kubelet, priority/important-soon, sig/node
