### ISSUE TITLE
k8s cgroup cpuset disappear causing container restart

### ISSUE THREAD

**Issue by neo-hu** [kubernetes/kubernetes#128397] opened 2024-10-29 03:14 UTC
### What happened?

```

[root@n1 kubepods-besteffort.slice]# cat /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice/*/cgroup.controllers
cpu io memory hugetlb pids rdma misc
cpu io memory hugetlb pids rdma misc

# wait 
[root@n1 kubepods-besteffort.slice]# cat /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice/*/cgroup.controllers
cpuset cpu io memory hugetlb pids rdma misc
cpuset cpu io memory hugetlb pids rdma misc
```

the disappearance of cpuset causes container restart

How should I handle it

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

Just install it

### Kubernetes version

- kubernetes-cni-1.2.0-150500.2.1.x86_64
- kubectl-1.28.15-150500.1.1.x86_64
- kubelet-1.28.15-150500.1.1.x86_64
- kubeadm-1.28.15-150500.1.1.x86_64
- containerd.io-1.7.22-3.1.el9.x86_64

<details>
```console
$ kubectl version
Client Version: v1.28.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

$ uname -a
Linux bx-10-182-20-103 5.14.0-284.25.1.el9_2.sinarelease.6.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 30 03:56:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ffromani** [comment] 2024-10-29 07:21
/triage accepted

likely dupe of https://github.com/kubernetes/kubernetes/issues/122955

**Comment by kannon92** [comment] 2024-10-29 15:42
/close

Duplicate.

**Closed by kannon92** 2024-10-29 15:42 UTC
Labels: kind/bug, sig/node, triage/accepted

**Comment by neo-hu** [comment] 2024-10-31 06:46
> /close
> 
> Duplicate.

How to solve it

**Comment by ffromani** [comment] 2024-10-31 07:16
> > /close
> > Duplicate.
> 
> How to solve it

Upgrade to a kubernetes version which includes https://github.com/kubernetes/kubernetes/pull/125923 - likely 1.32 and above. This fix is addressing a relatively rare corner case and it's unlikely to be backported.
