### ISSUE TITLE
kubernetes-e2e-gce-slow test suite leaking resources

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16192] opened 2015-10-23 21:37 UTC
```console
13:41:01 Bringing down cluster
13:41:49 ERROR: (gcloud.compute.instance-groups.managed.delete) Some requests did not succeed:
13:41:49  - Internal Error
13:41:49 
13:41:51 ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
13:41:51  - The instance_template resource 'e2e-slow-minion-template' is already being used by 'e2e-slow-minion-group'
13:41:51 
13:41:57 Updated [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/zones/us-central1-f/instances/e2e-slow-master].
13:42:44 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/zones/us-central1-f/instances/e2e-slow-master].
13:43:09 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/firewalls/e2e-slow-master-https].
13:43:26 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/firewalls/e2e-slow-minion-all].
13:43:27 Deleting routes e2e-slow-5f46aa47-79b1-11e5-bafa-42010af00002 e2e-slow-96a9332a-79b7-11e5-bafa-42010af00002 e2e-slow-a8196f66-79b0-11e5-bafa-42010af00002
13:43:49 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/routes/e2e-slow-5f46aa47-79b1-11e5-bafa-42010af00002].
13:43:49 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/routes/e2e-slow-96a9332a-79b7-11e5-bafa-42010af00002].
13:43:49 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/routes/e2e-slow-a8196f66-79b0-11e5-bafa-42010af00002].
13:43:57 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/e2e-slow-master-ip].
```

**Comment by saad-ali** [comment] 2015-10-23 23:34
Jenkins `kubernetes-e2e-gce-slow` test suite failed two times in a row with `Google Cloud Platform resources leaked while running tests` because `e2e-slow-minion-template` wasn't deleted.

```
16:24:00 + diff -sw -U0 '-F^\[.*\]$' /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-before.txt /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-after.txt
16:24:00 --- /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-before.txt	2015-10-23 13:45:02.506159125 -0700
16:24:00 +++ /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-after.txt	2015-10-23 16:24:00.742654398 -0700
16:24:00 @@ -10 +9,0 @@ [ instance-templates ]
16:24:00 -e2e-slow-minion-template n1-standard-2             2015-10-23T11:03:57.831-07:00
16:24:00 + [[ true == \t\r\u\e ]]
16:24:00 + echo '!!! FAIL: Google Cloud Platform resources leaked while running tests!'
16:24:00 
!!! FAIL: Google Cloud Platform resources leaked while running tests!
```

See:
* kubernetes-e2e-gce-slow/668
* kubernetes-e2e-gce-slow/669

**Comment by alex-mohr** [comment] 2015-11-03 00:05
Similar failure.  I noticed this one and the initial comment includes "Internal Error" response -- are the shell scripts aborting on that rather than retrying?

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/760/
15:02:15 Shutting down test cluster in background.
15:03:45 ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
15:03:45  - Internal Error
...
15:08:13 --- /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-before.txt	2015-11-02 12:22:00.167624968 -0800
15:08:13 +++ /var/lib/jenkins/jobs/kubernetes-e2e-gce-slow/workspace/_artifacts/gcp-resources-after.txt	2015-11-02 15:08:13.237538394 -0800
15:08:13 @@ -45,15 +44,0 @@ [ forwarding-rules ]
15:08:13 -a0169db53666f11e59d5842010af0684 us-central1 104.197.31.3    TCP         us-central1/targetPools/a0169db53666f11e59d5842010af0684
15:08:13 -a13cec8c1664811e5b0ba42010af0718 us-central1 104.154.81.5    TCP         us-central1/targetPools/a13cec8c1664811e5b0ba42010af0718
15:08:13 -a193d86fc66f111e584bc42010af0000 us-central1 104.197.188.125 TCP         us-central1/targetPools/a193d86fc66f111e584bc42010af0000
15:08:13 -a1ff141a7666211e59d9e42010af07bc us-central1 104.197.56.233  TCP         us-central1/targetPools/a1ff141a7666211e59d9e42010af07bc
15:08:13 -a2d8a285a66bd11e59e0942010af0617 us-central1 104.197.217.154 TCP         us-central1/targetPools/a2d8a285a66bd11e59e0942010af0617
15:08:13 -a3889614666b011e5a52242010af0c9c us-central1 23.251.153.49   TCP         us-central1/targetPools/a3889614666b011e5a52242010af0c9c
15:08:13 -a557ed8db665511e5bfd442010af011e us-central1 104.197.139.75  TCP         us-central1/targetPools/a557ed8db665511e5bfd442010af011e
15:08:13 -a66dc09b666e411e5aa0442010af0000 us-central1 104.154.93.40   TCP         us-central1/targetPools/a66dc09b666e411e5aa0442010af0000
15:08:13 -a6e2ba3e7669511e5bb7442010af02f6 us-central1 146.148.90.128  TCP         us-central1/targetPools/a6e2ba3e7669511e5bb7442010af02f6
15:08:13 -a6e6110cd66a311e5a35f42010af0180 us-central1 104.197.182.106 TCP         us-central1/targetPools/a6e6110cd66a311e5a35f42010af0180
15:08:13 -a72de3e6966d711e582d142010af0000 us-central1 104.197.54.143  TCP         us-central1/targetPools/a72de3e6966d711e582d142010af0000
15:08:13 -a7695876b663911e5963442010af0b62 us-central1 23.251.156.79   TCP         us-central1/targetPools/a7695876b663911e5963442010af0b62
15:08:13 -a98313d0f66ca11e5be2e42010af0000 us-central1 104.197.196.59  TCP         us-central1/targetPools/a98313d0f66ca11e5be2e42010af0000
15:08:13 -a9b59a328668811e59dd742010af0d99 us-central1 104.197.134.100 TCP         us-central1/targetPools/a9b59a328668811e59dd742010af0d99
15:08:13 -ad401eddf667b11e59dfa42010af03bb us-central1 104.197.202.114 TCP         us-central1/targetPools/ad401eddf667b11e59dfa42010af03bb


And submit queue is likely down for N hours again as a result.

**Comment by quinton-hoole** [comment] 2015-12-15 22:06
Yup, this seems like at least a P1, if not a P0 on the basis of it being the cause of highly flaky tests (and hence stalled merge bot).

**Comment by davidopp** [comment] 2015-12-15 22:45
@quinton-hoole points out we really need a master issue for fixing all the resource leaks.

**Comment by bprashanth** [comment] 2016-01-11 03:24
I just cleaned up a bunch of target pools and static ips because the cluster will fail to come up alltogether without static ips. Making it so a leaky test doesn't fail all runs thereafter is a meta issue, but the cause of the leak is probably not (unless it's a build aborting).

**Comment by quinton-hoole** [comment] 2016-01-25 18:37
Oops! This one was missing a kind/flake label. Fixed that now.

**Comment by davidopp** [comment] 2016-01-25 18:38
@quinton-hoole Thanks for adding the label. Can you recommend a course of action for fixing this?

**Comment by davidopp** [comment] 2016-01-25 18:39
(#13515 might help but I'm not sure)

**Comment by quinton-hoole** [comment] 2016-01-25 18:41
Yes, this is more than likely a duplicate of #13515.  I'll double check now that this particular test job is still leaking.  Pretty sure it is, probably for the same reason as #13515.

**Comment by davidopp** [comment] 2016-01-25 20:06
OK thanks much. Please report back your results as soon as you know.

**Comment by quinton-hoole** [comment] 2016-01-25 21:51
I don't see any leaked target pools in the past 4 months (there are a bunch of old ones created in September last year though).  Specifically, since @bprashanth deleted leaked target pools 2 weeks ago, I see no evidence of leaked target pools.

```
$ gcloud --project k8s-jkns-e2e-gce-slow compute firewall-rules list | tail -n +2 | awk '{print $1}' | xargs -n 1 gcloud --project k8s-jkns-e2e-gce-slow compute firewall-rules describe | grep creationTimestamp 
creationTimestamp: '2015-09-18T14:48:45.603-07:00'
creationTimestamp: '2015-09-18T14:48:45.565-07:00'
creationTimestamp: '2015-09-18T14:48:45.566-07:00'
creationTimestamp: '2015-09-18T14:48:45.565-07:00'
creationTimestamp: '2015-09-18T15:53:21.641-07:00'
creationTimestamp: '2015-09-18T15:53:22.371-07:00'
creationTimestamp: '2015-09-28T22:58:10.568-07:00'
creationTimestamp: '2015-09-28T18:19:34.841-07:00'
creationTimestamp: '2015-09-29T14:29:33.657-07:00'
creationTimestamp: '2015-09-28T21:25:55.676-07:00'
creationTimestamp: '2015-09-29T08:17:58.368-07:00'
creationTimestamp: '2015-09-29T06:45:00.366-07:00'
creationTimestamp: '2015-09-28T19:54:22.086-07:00'
creationTimestamp: '2015-09-29T12:58:32.245-07:00'
creationTimestamp: '2015-09-29T03:33:14.241-07:00'
creationTimestamp: '2015-09-29T05:13:21.304-07:00'
creationTimestamp: '2015-09-29T11:25:57.793-07:00'
creationTimestamp: '2015-09-28T17:42:14.057-07:00'
creationTimestamp: '2015-09-29T09:53:59.586-07:00'
creationTimestamp: '2015-09-29T02:01:23.264-07:00'
creationTimestamp: '2015-09-29T00:29:51.533-07:00'
```

**Comment by quinton-hoole** [comment] 2016-01-25 21:54
Similar result for routes.  Only those created in the current run today, and some from September last year:

```
$ gcloud --project k8s-jkns-e2e-gce-slow compute routes list | tail -n +2 | awk '{print $1}' | xargs -n 1 gcloud --project k8s-jkns-e2e-gce-slow compute routes describe | grep creationTimestamp 
creationTimestamp: '2015-09-18T14:48:36.115-07:00'
creationTimestamp: '2015-09-18T15:53:10.552-07:00'
creationTimestamp: '2015-09-18T14:48:36.096-07:00'
creationTimestamp: '2015-09-18T15:53:10.545-07:00'
creationTimestamp: '2016-01-25T13:51:42.045-08:00'
creationTimestamp: '2016-01-25T13:51:42.070-08:00'
creationTimestamp: '2016-01-25T13:51:42.060-08:00'
```

**Comment by quinton-hoole** [comment] 2016-01-25 21:56
Same for addresses:

```
$ gcloud --project k8s-jkns-e2e-gce-slow compute addresses list | tail -n +2 | awk '{print $1}' | xargs -n 1 gcloud --project k8s-jkns-e2e-gce-slow compute addresses describe | grep creationTimestamp 
creationTimestamp: '2016-01-25T13:48:47.473-08:00'
```

**Comment by quinton-hoole** [comment] 2016-01-25 21:58
Same for instance templates.  I think that we can close this issue as resolved.


```
$ gcloud --project k8s-jkns-e2e-gce-slow compute instance-templates list
NAME                     MACHINE_TYPE  PREEMPTIBLE CREATION_TIMESTAMP
e2e-slow-minion-template n1-standard-2             2016-01-25T13:49:55.520-08:00

```

**Comment by quinton-hoole** [comment] 2016-01-25 21:59
I'll delete all of the very old stuff that leaked last year.

**Closed by quinton-hoole** 2016-01-25 21:58 UTC
Labels: area/cluster-lifecycle, area/test, davidopp, kind/flake, priority/P1, team/control-plane

**Comment by quinton-hoole** [comment] 2016-01-25 22:24
It's worth noting that none of the Services e2e tests (which are the likely source of these leaks) are currently running in this slow test suite.  So it makes sense that there are no leaks.
