### ISSUE TITLE
Kubernetes 1.16.5 image wrongly package with 1.16.6-beta.0

### ISSUE THREAD

**Issue by floryut** [kubernetes/kubernetes#87424] opened 2020-01-21 13:38 UTC
**What happened**:
I've installed a cluster using Kubespray and chose to deploy Kubernetes 1.16.5.
But after the install with success I got a running 1.16.6-beta.0 cluster.

> NAME        STATUS   ROLES                                 AGE    VERSION
> fru000850   Ready    master                                110m   v1.16.6-beta.0
> fru000851   Ready    master                                109m   v1.16.6-beta.0
> fru000852   Ready    master                                109m   v1.16.6-beta.0
> fru000853   Ready    master                                109m   v1.16.6-beta.0
> fru000854   Ready    master                                109m   v1.16.6-beta.0
> fru000855   Ready    ingress-private,ingress-public,node   106m   v1.16.6-beta.0
> fru000856   Ready    ingress-private,ingress-public,node   106m   v1.16.6-beta.0
> fru000857   Ready    ingress-private,ingress-public,node   106m   v1.16.6-beta.0

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

> REPOSITORY                                                       TAG                 IMAGE ID            CREATED             SIZE
> gcr.io/google-containers/kube-proxy                              v1.16.5             0ee1b8a3ebe0        6 days ago          82.7MB
> gcr.io/google-containers/kube-apiserver                          v1.16.5             fc838b21afbb        6 days ago          159MB
> gcr.io/google-containers/kube-controller-manager                 v1.16.5             441835dd2301        6 days ago          151MB
> gcr.io/google-containers/kube-scheduler                          v1.16.5             b4d073a9efda        6 days ago          83.5MB
> ....

> 9698381a6601        b4d073a9efda                                    "kube-scheduler --au…"   3 hours ago         Up 3 hours                              k8s_kube-scheduler_kube-scheduler-fru000850_kube-system_31208d307dc2fa6eafa98a5cdf379dc7_0
> 7ca7c0486605        fc838b21afbb                                    "kube-apiserver --ad…"   3 hours ago         Up 3 hours                              k8s_kube-apiserver_kube-apiserver-fru000850_kube-system_7dd58f6f72459a35e3b0e065e4b5ec03_0
> ....

**What you expected to happen**:
Having a cluster up & running under version 1.16.5

**How to reproduce it (as minimally and precisely as possible)**:
Install a cluster using Kubespray 2.12 branch and Kubernetes 1.16.5 version.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.6-beta.0
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): Linux fru000850 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Kubespray 2.12 (branch)
- Network plugin and version (if this is a network-related bug): calico
- Others: none

**Comment by ialidzhikov** [comment] 2020-01-21 22:22
@floryut , see https://github.com/kubernetes/release/issues/1020 and https://groups.google.com/forum/#!topic/kubernetes-dev/Mhpx-loSBns.

@neolit123 , @justaugustus , could you please close this one as duplicate of https://github.com/kubernetes/release/issues/1020?

**Comment by justaugustus** [comment] 2020-01-21 22:28
Closed as duplicate of https://github.com/kubernetes/release/issues/1020.
/close

(You can also close with the `/close` bot command.)

**Closed by justaugustus** 2020-01-21 22:28 UTC
Labels: kind/bug, sig/release
