### ISSUE TITLE
[e2e failure] [sig-apps] Daemon set [Serial] Should adopt existing pods when creating a RollingUpdate DaemonSet regardless of templateGeneration

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#54575] opened 2017-10-25 15:31 UTC
/priority failing-test
/priority critical-urgent
/sig apps

This test case has been failing for a while and affects a number of jobs: [triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-apps%5C%5D%20Daemon%20set%20%5C%5BSerial%5C%5D%20Should%20adopt%20existing%20pods%20when%20creating%20a%20RollingUpdate%20DaemonSet%20regardless%20of%20templateGeneration)

This is affecting multiple jobs on the [release-master-blocking](https://k8s-testgrid.appspot.com/sig-release-master-blocking) testgrid dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22). Is there work ongoing to bring this job back to green?

[triage cluster a39a48487b56c56a97d6](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-apps%5C%5D%20Daemon%20set%20%5C%5BSerial%5C%5D%20Should%20adopt%20existing%20pods%20when%20creating%20a%20RollingUpdate%20DaemonSet%20regardless%20of%20templateGeneration#a39a48487b56c56a97d6)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:435
Expected error:
    <*url.Error | 0xc421c50fc0>: {
        Op: "Get",
        URL: "https://35.188.204.137/api/v1/namespaces/e2e-tests-daemonsets-wvmh7/pods?labelSelector=daemonset-name%3Ddaemon-set",
        Err: {
            Op: "dial",
            Net: "tcp",
            Source: nil,
            Addr: {
                IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 35, 188, 204, 137],
                Port: 443,
                Zone: "",
            },
            Err: {
                Syscall: "getsockopt",
                Err: 0x6f,
            },
        },
    }
    Get https://35.188.204.137/api/v1/namespaces/e2e-tests-daemonsets-wvmh7/pods?labelSelector=daemonset-name%3Ddaemon-set: dial tcp 35.188.204.137:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:553
```

@kubernetes/sig-apps-test-failures

**Comment by janetkuo** [comment] 2017-10-30 18:12
All test failures look similar: `getsockopt: connection refused`. It should be due to network issue instead of DaemonSet.  

@kubernetes/sig-network-bugs

**Comment by enisoc** [comment] 2017-10-30 21:12
@janetkuo @kow3ns This seems related to the new `apps/v1` DaemonSet.

The connection refused error is happening because kube-apiserver is crashing:

```
E1030 15:33:37.833277       5 runtime.go:66] Observed a panic: "unexpected group/version: apps/v1" (unexpected group/version: apps/v1)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/extensions/daemonset/strategy.go:142
<autogenerated>:1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/update.go:121
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:582
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:728
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:305
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:553
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:517
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:100
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:173
/usr/local/go/src/runtime/asm_amd64.s:2337
panic: unexpected group/version: apps/v1 [recovered]
	panic: unexpected group/version: apps/v1
```

**Comment by kow3ns** [comment] 2017-10-30 22:04
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/daemonset/strategy.go#L140 needs an update

**Comment by enisoc** [comment] 2017-10-30 22:07
Ah, well... I guess it's halfway working as intended. We put that there to make the tests fail if we forgot to update it when adding a new version. We had hoped it would fail during presubmit tests though. :(

**Comment by janetkuo** [comment] 2017-10-30 22:13
Sending a fix now

**Comment by crimsonfaith91** [comment] 2017-10-30 22:54
I wonder why the test is not failing on submit queue tests. Do i need to fix deployment and replicaset?

**Comment by kow3ns** [comment] 2017-10-30 23:43
The rest of the group is not merged, and the v1 PR takes the selector mutability into account.

**Comment by janetkuo** [comment] 2017-10-30 23:44
Since this bug crashes apiserver I'd expect it to affect many other e2e tests.

**Comment by crimsonfaith91** [comment] 2017-10-30 23:47
Noted, we need to fix deployment and replicaset when the v1 PR is merged.

**Comment by janetkuo** [comment] 2017-10-31 01:24
Not quite sure how this test isn't failing before but is now consistently failing. I'd expect the commit that triggers this to block the submit queue. 

The e2e test is still accessing DaemonSet through extensions/v1beta1 endpoints. From the above apiserver log it's hard to tell what updates DaemonSet via apps/v1 before the code panics. I tried to reproduce it locally, and found that garbage collector PUT apps/v1 DaemonSet:

```
I1030 18:04:36.153118   95862 wrap.go:42] GET /apis/apps/v1/namespaces/e2e-tests-daemonsets-ftxpw/daemonsets/adopt: (4.765283ms) 200 [[hyperkube/v1.9.0 (linux/amd64) kubernetes/bd28e6d/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:34040]
I1030 18:04:36.158887   95862 controller.go:538] quota admission added evaluator for: {apps daemonsets}
I1030 18:04:36.162207   95862 wrap.go:42] PUT /apis/apps/v1/namespaces/e2e-tests-daemonsets-ftxpw/daemonsets/adopt: (7.882408ms) 409 [[hyperkube/v1.9.0 (linux/amd64) kubernetes/bd28e6d/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:34040]
I1030 18:04:36.174673   95862 wrap.go:42] GET /apis/apps/v1/namespaces/e2e-tests-daemonsets-ftxpw/daemonsets/adopt: (1.16546ms) 200 [[hyperkube/v1.9.0 (linux/amd64) kubernetes/bd28e6d/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:34040]
```

**Comment by crimsonfaith91** [comment] 2017-10-31 01:46
When apps/v1 gets introduced, it may be ordered before apps/beta1 alphabetically. IIRC, there is a change on the apps/v1 PR that changes the order of API versions such that apps/v1 is ranked _before_ apps/v1beta2 and apps/v1beta2 _before_ apps/v1beta1. Perhaps this problem can be fixed when the PR merges.

**Comment by janetkuo** [comment] 2017-11-01 00:52
Since `panic` crashes apiserver and makes debugging harder which defeats the purpose of using it, we should return error on unsupported versions  instead.

**Closed** 2017-11-01 10:00 UTC
Labels: kind/bug, priority/critical-urgent, priority/failing-test, sig/apps

**Comment by enisoc** [comment] 2017-11-01 18:19
The first run with this change is still in progress, but this test already passed:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/2457

Thanks for the quick fix @janetkuo!
