### ISSUE TITLE
HPA scales up with no reason / blank reason

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/kubernetes#78712] opened 2019-06-04 23:55 UTC
**What happened**:
HPA scales up a deployment without a reason.

```
Events:
  Type     Reason             Age                   From                       Message
  ----     ------             ----                  ----                       -------
  Normal   SuccessfulRescale  57m (x3 over 3d9h)    horizontal-pod-autoscaler  New size: 250; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale  43m (x3 over 30h)     horizontal-pod-autoscaler  New size: 313; reason:
  Normal   SuccessfulRescale  42m                   horizontal-pod-autoscaler  New size: 391; reason:
  Normal   SuccessfulRescale  42m                   horizontal-pod-autoscaler  New size: 481; reason:
  Normal   SuccessfulRescale  41m                   horizontal-pod-autoscaler  New size: 518; reason:
  Normal   SuccessfulRescale  36m (x2 over 6d3h)    horizontal-pod-autoscaler  New size: 288; reason: All metrics below target
  Normal   SuccessfulRescale  32m                   horizontal-pod-autoscaler  New size: 284; reason: All metrics below target
  Normal   SuccessfulRescale  31m (x4 over 6d2h)    horizontal-pod-autoscaler  New size: 230; reason: All metrics below target
  Normal   SuccessfulRescale  25m                   horizontal-pod-autoscaler  New size: 230; reason:
  Normal   SuccessfulRescale  24m                   horizontal-pod-autoscaler  New size: 288; reason:
  Warning  FailedRescale      15m (x2 over 15m)     horizontal-pod-autoscaler  New size: 457; reason: ; error: Operation cannot be fulfilled on deployments.apps "prod": the object has been modified; please apply your changes to the latest version and try again
  Normal   SuccessfulRescale  51s (x123 over 6d5h)  horizontal-pod-autoscaler  (combined from similar events): New size: 218; reason: All metrics below target
```

**What you expected to happen**:
There should always be a reason for a scale up or scale down.

**How to reproduce it (as minimally and precisely as possible)**:
Not exactly sure. But we did notice this behavior during a rolling update.

Here's what the deployment strategy looks like:
```
...
strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 5%
    type: RollingUpdate
...
```

And the hpa:
```
...
spec:
  maxReplicas: 3000
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod
  targetCPUUtilizationPercentage: 20
...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Metrics server: 0.3.2 or 0.3.3
- Cloud provider or hardware configuration: AWS m4.10xlarge
- OS (e.g: `cat /etc/os-release`): CoreOS 2079.4.0
- Kernel (e.g. `uname -a`): 4.19.43

**Comment by mariusgrigoriu** [comment] 2019-06-05 00:31
@kubernetes/sig-autoscaling-bugs

**Comment by josephburnett** [comment] 2019-06-13 11:36
I've started looking into this.  (Also found in https://github.com/kubernetes/kubernetes/issues/78761).  This is what I think is going on:

When HPA computes a recommendation, it ignores any pods whose metrics are missing.  However it recomputes with fake missing metrics to see what they might have done.  When the initial recommendation is to scale down, it injects fake metrics of 100% usage (for dampening).  If the recommendation switches direction, it decides to punt on changing the scale.

However, the way it punts is by setting spec.replicas to the number of replicas it discovered.  In the case of a Deployment rollout, there may be more replicas than given in spec.replicas because burst capacity may specified.  So this will create a feedback loop to create additional pods.  (Theory, to be verified)

This bug is triggered when scale-up hits the ceiling of cluster capacity and many pods are unscheduled.  And when traffic is removed from the service (initial recommendation is scale-down).  The many unscheduled Pods become many fake 100% utilization metrics and ensure that the scale direction will always change, entering the defective code path.

I'll report back shortly with what I find out.  @mwielgus can you please assign this bug to me?

**Comment by josephburnett** [comment] 2019-06-13 11:39
The defective code path is:

**Comment by josephburnett** [comment] 2019-06-13 11:43
The defective code path is:

https://github.com/kubernetes/kubernetes/blob/4f29960cb2058c4f556bf1e5ba49c9a29a501e70/pkg/controller/podautoscaler/replica_calculator.go#L134

because `currentReplicas` is from status and could be larger than spec.replicas by design when rolling out a Deployment update:

https://github.com/kubernetes/kubernetes/blob/4f29960cb2058c4f556bf1e5ba49c9a29a501e70/pkg/controller/podautoscaler/horizontal.go#L238

Big thanks to @krzysztof-jastrzebski for triage and diagnosis.  :)

**Comment by tedyu** [comment] 2019-06-13 12:41
@josephburnett 
What do you think of my change in #78714 ?

**Comment by mariusgrigoriu** [comment] 2019-06-13 15:24
> However, the way it punts is by setting spec.replicas to the number of replicas it discovered. In the case of a Deployment rollout, there may be more replicas than given in spec.replicas because burst capacity may specified. So this will create a feedback loop to create additional pods. (Theory, to be verified)

Theory verified. We see the feedback loop on our clusters multiple times per day, escalating the number of pods up to a couple thousand more than needed. Using spec.replicas also has the behavior of locking in the deployment surge amount well after the deployment is done until the HPA decides to scale it back down. Another effect of this feedback loop is that users who run `kubectl rollout status` in their scripting will be stuck waiting for the duration of the feedback loop.

You can see details I posted here: https://github.com/kubernetes/kubernetes/issues/72775#issuecomment-499945980

The change in #78714 fixes the issue cosmetically. I hope we can go further and turn our attention to the feedback loop described in #72775

**Comment by josephburnett** [comment] 2019-06-14 09:36
Thanks @tedyu for the patch.  As @mariusgrigoriu said, that just give better information.  I'll focus first on fixing the feedback loop and then take a look at your PR.

**Comment by josephburnett** [comment] 2019-06-14 14:33
Pull request is out for review: https://github.com/kubernetes/kubernetes/pull/79035#issue-288355508

I found several other cases where we return `scale.Status.Replicas` which can cause a positive feedback loop.

**Comment by max-rocket-internet** [comment] 2019-06-19 14:02
@josephburnett is there any work around? We have this issue quite bad. Some of our deployments scale to `maxReplicas` very quickly.

Our deployment strategy looks like this:

```
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
```

**Comment by kaleocheng** [comment] 2019-06-20 05:22
based on the above discussion, theoretically, once we finished the rolling update and there is no unscheduled pod, the HPA should eventually decide to scale it back down right?  but I found it's still keeping on the max replicas.

```bash
$ kubectl get hpa 
NAME               REFERENCE                     TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
contact            Deployment/contact            4%/80%    1         3         3          2d18h

$ kubectl get deployment contact 
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
contact   3         3         3            3           26d
```

```bash
$ kubectl  describe deployment contact
Name:                   contact
Namespace:              xxxx
CreationTimestamp:      Fri, 24 May 2019 17:27:47 +0800
Labels:                 app=contact
                        env=xxxx
Annotations:            deployment.kubernetes.io/revision: 18
Selector:               app=contact,env=xxxx
Replicas:               3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=contact
           env=xxxx
           timestamp=1560997689
  Containers:
   contact:
    Image:      xxxx
    Port:       3000/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:      100m
      memory:   256Mi
    Readiness:  http-get http://:3000/health delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      contact-env-vars  ConfigMap  Optional: false
      contact-secrets   Secret     Optional: false
    Environment:        <none>
    Mounts:
      /app/uploads from nfs (rw)
      /secure from nfs-config (ro)
  Volumes:
   nfs:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    xxxx
    Path:      /contact/xxxx
    ReadOnly:  false
   nfs-config:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    xxxx
    Path:      /contact-config/xxxx
    ReadOnly:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   contact-7bc988fd4d (3/3 replicas created)
Events:          <none>
```


```bash
$ kubectl  describe hpa contact
Name:                                                  contact
Namespace:                                             xxx
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Mon, 17 Jun 2019 18:17:56 +0800
Reference:                                             Deployment/contact
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  4% (4m) / 80%
Min replicas:                                          1
Max replicas:                                          3
Deployment pods:                                       3 current / 3 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>
```

**Comment by max-rocket-internet** [comment] 2019-06-20 10:21
> but I found it's still keeping on the max replicas.

Yes, we have also many HPAs that never scale back down. See here: https://github.com/kubernetes/kubernetes/issues/78761

**Closed** 2019-07-02 16:31 UTC
Labels: kind/bug, sig/autoscaling

**Comment by deepanverma19** [comment] 2020-01-30 19:02
@max-rocket-internet Do you have any update for this?

**Comment by max-rocket-internet** [comment] 2020-01-31 10:27
Nope. There was some fixes merged but it takes so long for them to be in a GA release.

**Comment by rogerioefonseca** [comment] 2020-08-16 17:05
Hello, I'm experiencing this behavior as well and I would like to know if someone can answer me why it is closed if there is not a solution for this?

**Comment by rogerioefonseca** [comment] 2020-08-16 17:07
I mean is this being tracked or so?
@max-rocket-internet  do you have an idea of when this bugfix will be released?

**Comment by max-rocket-internet** [comment] 2020-08-17 08:11
> @max-rocket-internet do you have an idea of when this bugfix will be released?

I have no idea. Maybe @ josephburnett could give us a clue as to what was fixed, when it will be in a release and what wasn't fixed?

I find it really hard to understand what is being fixed in k8s PRs and also tracking a PR to a release 😕

**Comment by gerardgorrion** [comment] 2020-10-19 08:45
Hi @max-rocket-internet , we have same problem in kubernetes 1.15. We try to deploy some app and add the hpa to autoscale. Scaling up is working fine, but the extra pod is destroyed and created a new pod every 5 min:
![Captura](https://user-images.githubusercontent.com/35425181/96421362-f978c280-11f6-11eb-8848-2c4aa6a4d6f8.PNG)

When try to scale down (stopped the cpu consume), deployment events show request to scale down and a petition to scale up; the hpa show scale up with no reason; and the extra pods created by the autoscale was removed and created a new also every 5 min. Deployment never return to initial desiredpods (if we try to scale to 2, desiredpods show2, if we autoescale to 5, desiredpods show 5...).

We try to deploy hpa v1, v2beta1 and v2beta2 and only use CPU metric with %. Metric server seem work fine, every 30/40 sec the logs show correct node and pods status.

Thanks!
