### ISSUE TITLE
Kubernetes scheduler fails to schedule pods on nodes with enough resources.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#37232] opened 2016-11-21 19:25 UTC
A follow up of: https://github.com/kubernetes/kubernetes/issues/34772
 
I have a node with:
```
Name:			gke-test-cluster-1-default-pool-2fef8206-jk88
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=custom-4-8192
			beta.kubernetes.io/os=linux
			cloud.google.com/gke-nodepool=default-pool
			failure-domain.beta.kubernetes.io/region=us-central1
			failure-domain.beta.kubernetes.io/zone=us-central1-b
			kubernetes.io/hostname=gke-test-cluster-1-default-pool-2fef8206-jk88
Taints:			<none>
CreationTimestamp:	Mon, 21 Nov 2016 18:44:36 +0100
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  NetworkUnavailable 	False 	Mon, 21 Nov 2016 19:48:38 +0100 	Mon, 21 Nov 2016 19:48:38 +0100 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Mon, 21 Nov 2016 19:48:37 +0100 	Mon, 21 Nov 2016 18:44:36 +0100 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Mon, 21 Nov 2016 19:48:37 +0100 	Mon, 21 Nov 2016 18:44:36 +0100 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Mon, 21 Nov 2016 19:48:37 +0100 	Mon, 21 Nov 2016 18:44:36 +0100 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Mon, 21 Nov 2016 19:48:37 +0100 	Mon, 21 Nov 2016 18:45:06 +0100 	KubeletReady 			kubelet is posting ready status. AppArmor enabled
Addresses:		10.240.0.5,146.148.80.118
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					4
 memory:				8168548Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					4
 memory:				8168548Ki
 pods:					110
System Info:
 Machine ID:			0251ec6b2c2821ef342fe6d15833325b
 System UUID:			0B3867CF-4808-B8E4-C80C-37EF3ADF7373
 Boot ID:			f986c6b3-0c82-48ce-82a7-2856d61b0be9
 Kernel Version:		4.4.21+
 OS Image:			Google Container-VM Image
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.4.6
 Kube-Proxy Version:		v1.4.6
PodCIDR:			10.152.4.0/24
ExternalID:			3039357858658290851
Non-terminated Pods:		(7 in total)
  Namespace			Name										CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----										------------	----------	---------------	-------------
  default			my-app-2781155866-0fxn9								550m (13%)	0 (0%)		0 (0%)		0 (0%)
  default			my-app-2781155866-4p8lv								550m (13%)	0 (0%)		0 (0%)		0 (0%)
  default			my-app-2781155866-hph3k								550m (13%)	0 (0%)		0 (0%)		0 (0%)
  default			my-app-2781155866-ulbjk								550m (13%)	0 (0%)		0 (0%)		0 (0%)
  default			my-app-2781155866-vyp5w								550m (13%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			fluentd-cloud-logging-gke-test-cluster-1-default-pool-2fef8206-jk88		80m (2%)	0 (0%)		200Mi (2%)	200Mi (2%)
  kube-system			kube-proxy-gke-test-cluster-1-default-pool-2fef8206-jk88			100m (2%)	0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  2930m (73%)	0 (0%)		200Mi (2%)	200Mi (2%)
```

On the other hand
```
kubectl describe pod my-app-2781155866-8kr0g
Name:		my-app-2781155866-8kr0g
Namespace:	default
Node:		gke-test-cluster-1-default-pool-2fef8206-ae7w/
Start Time:	Mon, 21 Nov 2016 19:04:26 +0100
Labels:		name=my-app
		pod-template-hash=2781155866
Status:		Failed
Reason:		OutOfcpu
Message:	Pod 
IP:		
Controllers:	ReplicaSet/my-app-2781155866
Containers:
  my-app:
    Image:	ubuntu:16.04
    Port:	8000/TCP
    Command:
      /bin/bash
      -c
    Args:
      apt update; apt install stress; stress --cpu 1 --io 1 & sleep 999999
    Requests:
      cpu:	550m
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5ora1 (ro)
    Environment Variables:	<none>
Volumes:
  default-token-5ora1:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-5ora1
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1h		57m		7	{default-scheduler }			Warning		FailedScheduling	pod (my-app-2781155866-8kr0g) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-ae7w): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-jk88): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-6j58): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9mys): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9gxe): Insufficient cpu

  1h	48m	11	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-8kr0g) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-jk88): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-6j58): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9mys): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9gxe): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-ae7w): Insufficient cpu

  1h	47m	8	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-8kr0g) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9mys): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9gxe): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-ae7w): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-jk88): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-6j58): Insufficient cpu

  1h	47m	12	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-8kr0g) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9gxe): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-ae7w): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-jk88): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-6j58): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9mys): Insufficient cpu

  1h	47m	19	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-8kr0g) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-6j58): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9mys): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-9gxe): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-ae7w): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-2fef8206-jk88): Insufficient cpu

  46m	46m	1	{default-scheduler }						Normal	Scheduled	Successfully assigned my-app-2781155866-8kr0g to gke-test-cluster-1-default-pool-2fef8206-ae7w
  46m	46m	1	{kubelet gke-test-cluster-1-default-pool-2fef8206-ae7w}		Warning	OutOfcpu
```

The pod should be able to schedule on the node but it fails for unknown reason.

Reseting the scheduler helps, another pod is scheduled on the node and the resource usage jumps from 2930 to 3480. So it seems that the bug is somewhere around caching or retries. 

cc: @wojtek-t @gmarek @davidopp

**Comment by wojtek-t** [comment] 2016-11-21 19:30
@mwielgus - after thinking about it, I have one more idea to check - were there any pods that were finished (i.e. in a success or failure state)?

[I guess the problem is around caching, but not yet any idea what exactly.]

**Comment by mwielgus** [comment] 2016-11-21 19:39
No, all pods are either pending or running.

**Comment by gmarek** [comment] 2016-11-21 19:55
It looks like we are missing some additions, for some reason.

**Comment by paul-symphony** [comment] 2016-11-21 23:33
I am seeing a similar issue.  I have a cluster of 4 nodes, each with 4cpu.  There are no pods scheduled.  The first pod I attempt to schedule specifies 4 cpu.  However:
```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  3m		3m		2	{default-scheduler }			Warning		FailedScheduling	pod (jenkins-master-645022479-ov9ka) failed to fit in any node
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-spgr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-jitr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-3qqu): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-530e): Insufficient cpu

  3m	1m	3	{default-scheduler }		Warning	FailedScheduling	pod (jenkins-master-645022479-ov9ka) failed to fit in any node
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-3qqu): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-530e): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-spgr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-jitr): Insufficient cpu

  1m	1m	2	{default-scheduler }		Warning	FailedScheduling	pod (jenkins-master-645022479-ov9ka) failed to fit in any node
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-jitr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-3qqu): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-530e): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-spgr): Insufficient cpu

  3m	29s	8	{default-scheduler }		Warning	FailedScheduling	pod (jenkins-master-645022479-ov9ka) failed to fit in any node
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-530e): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-spgr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-jitr): Insufficient cpu
fit failure on node (gke-warpdrive-default-pool-eae1f3b0-3qqu): Insufficient cpu

  3m	2s	21	{cluster-autoscaler }		Normal	NotTriggerScaleUp	pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

**Comment by k82cn** [comment] 2016-11-22 05:34
@mwielgus / @paul-symphony , would you share scheduler's log?

**Comment by paul-symphony** [comment] 2016-11-22 05:37
how do i retrieve it?

**Comment by davidopp** [comment] 2016-11-22 05:48
> how do i retrieve it?

If you're running open-source Kubernetes, look in /var/log/kube-scheduler.log on the master
If you're running on GKE, unfortunately you can't see it.

**Comment by wojtek-t** [comment] 2016-11-22 09:40
@mwielgus - can you write exactly how did you reproduce it?

**Comment by mwielgus** [comment] 2016-11-22 09:52
@wojtek-t I followed this: https://github.com/kubernetes/kubernetes/issues/34772#issuecomment-260594667. @fgrzadkowski also reproduced the bug with these instructions but on the cluster autoscaler side (which reuses a big part of scheduler's logic).

**Comment by wojtek-t** [comment] 2016-11-22 13:27
@paul-symphony - your usecase is working as intended; we consume some part of resources for system pods (e.g. kube-proxy). So you pretty much can't schedule 4-cpu pod on a 4-cpu node.

**Comment by wojtek-t** [comment] 2016-11-22 13:52
@mwielgus - I think that your original description of the problem is incorrect. Basically what happened in your situation is that:
- you indeed have a node with some free space on it.
- but the pod that you pasted failed from w __known__ reason - scheduler scheduled it on a node, where there weren't any free resources, and kubelet rejected it

That said, there is clearly a bug in scheduler.

I managed to reproduce some problem with it, where there is a free space on a node, but scheduler is not scheduling any pod on it and claims there are no free resources on it.
I added some logs to the scheduler and it clearly seems like we are trying to schedule the same pod more than once. Some logs from my run:
```
I1122 13:23:45.511751       5 factory.go:488] About to try and schedule pod my-app-2781155866-99rnc
I1122 13:23:45.511781       5 scheduler.go:93] Attempting to schedule pod: default/my-app-2781155866-99rnc
E1122 13:23:45.512141       5 cache.go:113] assumePod: my-app-2781155866-99rnc e2e-test-wojtekt-minion-group-bgxy
I1122 13:23:45.512199       5 factory.go:648] Attempting to bind my-app-2781155866-99rnc to e2e-test-wojtekt-minion-group-bgxy
I1122 13:23:45.527339       5 factory.go:488] About to try and schedule pod my-app-2781155866-99rnc
I1122 13:23:45.527382       5 scheduler.go:93] Attempting to schedule pod: default/my-app-2781155866-99rnc
E1122 13:23:45.529108       5 cache.go:113] assumePod: my-app-2781155866-99rnc e2e-test-wojtekt-minion-group-sl4l
E1122 13:23:45.529129       5 scheduler.go:116] scheduler cache AssumePod failed: pod state wasn't initial but get assumed. Pod key: default/my-app-2781155866-99rnc
I1122 13:23:45.529176       5 factory.go:648] Attempting to bind my-app-2781155866-99rnc to e2e-test-wojtekt-minion-group-sl4l
E1122 13:23:45.539523       5 cache.go:163] AddPod: my-app-2781155866-99rnc e2e-test-wojtekt-minion-group-bgxy
I1122 13:23:45.544267       5 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-app-2781155866-99rnc", UID:"92aa3e09-b0b6-11e6-86ab-42010af00002", APIVersion:"v1", ResourceVersion:"2700", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned my-app-2781155866-99rnc to e2e-test-wojtekt-minion-group-bgxy
I1122 13:23:45.546205       5 scheduler.go:135] Failed to bind pod: default/my-app-2781155866-99rnc
E1122 13:23:45.546224       5 cache.go:137] ForgetPod: my-app-2781155866-99rnc e2e-test-wojtekt-minion-group-sl4l
E1122 13:23:45.546235       5 scheduler.go:137] scheduler cache ForgetPod failed: pod state wasn't assumed but get forgotten. Pod key: default/my-app-2781155866-99rnc
E1122 13:23:45.546244       5 factory.go:583] Error scheduling default my-app-2781155866-99rnc: Operation cannot be fulfilled on pods/binding "my-app-2781155866-99rnc": pod my-app-2781155866-99rnc is already assigned to node "e2e-test-wojtekt-minion-group-bgxy"; retrying
I1122 13:23:45.546286       5 factory.go:660] Updating pod condition for default/my-app-2781155866-99rnc to (PodScheduled==False)
W1122 13:23:45.546474       5 factory.go:597] Request for pod default/my-app-2781155866-99rnc already in flight, abandoning
I1122 13:23:45.546497       5 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-app-2781155866-99rnc", UID:"92aa3e09-b0b6-11e6-86ab-42010af00002", APIVersion:"v1", ResourceVersion:"2701", FieldPath:""}): type: 'Normal' reason: 'FailedScheduling' Binding rejected: Operation cannot be fulfilled on pods/binding "my-app-2781155866-99rnc": pod my-app-2781155866-99rnc is already assigned to node "e2e-test-wojtekt-minion-group-bgxy"
```

So the problem is basically with retrying in scheduling decisions.

**Comment by gmarek** [comment] 2016-11-22 15:06
We need to make sure that deduplicated FIFO queue that we use in the scheduler is really deduplicated.

**Comment by wojtek-t** [comment] 2016-11-23 13:10
I also managed to repro "roughly" the other way than yesterday, which is "again CA is right, but scheduler is consistently scheduling all pods to one node, those are later rejected by kubelet". The problem seems to be exactly the same with incorrect retries. I'm trying to understand this exactly right now.

Some logs:
```
I1123 12:46:43.248373       5 factory.go:488] About to try and schedule pod my-app-2781155866-08410
I1123 12:46:43.248417       5 scheduler.go:93] Attempting to schedule pod: default/my-app-2781155866-08410
E1123 12:46:43.248909       5 cache.go:113] assumePod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-z1xo
I1123 12:46:43.248958       5 factory.go:648] Attempting to bind my-app-2781155866-08410 to e2e-test-wojtekt-minion-group-z1xo
I1123 12:46:43.269811       5 factory.go:488] About to try and schedule pod my-app-2781155866-08410
I1123 12:46:43.269856       5 scheduler.go:93] Attempting to schedule pod: default/my-app-2781155866-08410
E1123 12:46:43.271569       5 cache.go:113] assumePod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-l730
E1123 12:46:43.271614       5 scheduler.go:116] scheduler cache AssumePod failed: pod state wasn't initial but get assumed. Pod key: default/my-app-2781155866-08410
I1123 12:46:43.271645       5 factory.go:648] Attempting to bind my-app-2781155866-08410 to e2e-test-wojtekt-minion-group-l730
E1123 12:46:43.293320       5 cache.go:163] AddPod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-l730
I1123 12:46:43.296456       5 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-app-2781155866-08410", UID:"8dff032b-b17a-11e6-bfe3-42010af00002", APIVersion:"v1", ResourceVersion:"4925", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned my-app-2781155866-08410 to e2e-test-wojtekt-minion-group-l730
I1123 12:46:43.304289       5 scheduler.go:135] Failed to bind pod: default/my-app-2781155866-08410
E1123 12:46:43.304340       5 cache.go:137] ForgetPod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-z1xo
E1123 12:46:43.304355       5 scheduler.go:137] scheduler cache ForgetPod failed: pod state wasn't assumed but get forgotten. Pod key: default/my-app-2781155866-08410
E1123 12:46:43.304364       5 factory.go:583] Error scheduling default my-app-2781155866-08410: Operation cannot be fulfilled on pods/binding "my-app-2781155866-08410": pod my-app-2781155866-08410 is already assigned to node "e2e-test-wojtekt-minion-group-l730"; retrying
I1123 12:46:43.304402       5 factory.go:660] Updating pod condition for default/my-app-2781155866-08410 to (PodScheduled==False)
W1123 12:46:43.304620       5 factory.go:597] Request for pod default/my-app-2781155866-08410 already in flight, abandoning
I1123 12:46:43.304655       5 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-app-2781155866-08410", UID:"8dff032b-b17a-11e6-bfe3-42010af00002", APIVersion:"v1", ResourceVersion:"4924", FieldPath:""}): type: 'Normal' reason: 'FailedScheduling' Binding rejected: Operation cannot be fulfilled on pods/binding "my-app-2781155866-08410": pod my-app-2781155866-08410 is already assigned to node "e2e-test-wojtekt-minion-group-l730"
E1123 12:46:43.321306       5 cache.go:191] UpdatePod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-l730
E1123 12:46:43.321353       5 factory.go:218] scheduler cache UpdatePod failed: no corresponding pod my-app-2781155866-08410 in pods of node e2e-test-wojtekt-minion-group-l730
E1123 12:46:57.182443       5 cache.go:191] UpdatePod: my-app-2781155866-08410 e2e-test-wojtekt-minion-group-l730
E1123 12:46:57.182481       5 factory.go:218] scheduler cache UpdatePod failed: no corresponding pod my-app-2781155866-08410 in pods of node e2e-test-wojtekt-minion-group-l730
```

**Comment by wojtek-t** [comment] 2016-11-23 13:21
OK - I understood exactly what happened in this case. What happened here is that:
- we tried to assign a pod to e2e-test-wojtekt-minion-group-z1xo
- in cache we assumed a pod is assigned to that node
- then we did another try to assign it to e2e-test-wojtekt-minion-group-l730
- assume to that node failed (because pod was already assumed)
- however, since binding is asynchronous, the second one succeeded
- then AddPod came and it moved the pod to "Add" state (from assumed), but it remained assigned to "e2e-test-wojtekt-minion-group-z1xo" whereas in fact it was scheduled on "e2e-test-wojtekt-minion-group-l730"
- that pretty much corruptedstate, because the pod remained assigned to a different node to which in fact it was assigned.

So that case I fully understand - @davidopp FYI
I will try to fully understand the previous case.

**Comment by wojtek-t** [comment] 2016-11-23 13:37
BTW - the above problem would be fixed by my PR (in a hack way, but still).

**Comment by wojtek-t** [comment] 2016-11-23 14:07
Actually, we discussed it with @gmarek and I think that the problem from yesterday was actually the same problem (and I was just looking into not exactly the logs I should have been looking). That said, I did 3 more tries, and all 4 runs failed exactly the same way.
What is more, the original bug reported by @mwielgus is also exactly the same one. 

So I think that the fix that is waiting for merge is a good enough fix (though it is a workaround, not a proper fix). 

I will send one more PR that will make the schedulercache be more resistant to such failure. And we should close this issue.
The more medium/long term AI from it is that we should rewrite that scheduler leaving only predicated, priorities and generic scheduler (which means rewriting scheduler.go and all the factories etc.).

**Comment by wojtek-t** [comment] 2016-11-24 18:19
Actually, we decided (@davidopp was involved) that the second PR #37379 will be merged and cherrypicked to 1.5 branch. So I'm marking as release-blocker.

**Comment by wojtek-t** [comment] 2016-11-29 14:20
For this, we are just waiting for:
https://github.com/kubernetes/kubernetes/pull/37379

to be merged and cherrypicked to 1.5 branch.

**Closed** 2016-11-29 16:15 UTC
Labels: area/scheduling, kind/bug, priority/P0, release-blocker, team/control-plane

**Comment by Bharathkumarraju** [comment] 2018-12-28 20:36
I am also having the same issue.

```
I1228 08:40:48.308734       1 feature_gate.go:190] feature gates: map[PersistentLocalVolumes:false VolumeScheduling:false MountPropagation:false Initializers:false]
W1228 08:40:48.308957       1 server.go:162] WARNING: all flags than --config are deprecated. Please begin using a config file ASAP.
I1228 08:40:48.381448       1 server.go:554] Version: v1.9.7
I1228 08:40:48.381639       1 factory.go:837] Creating scheduler from algorithm provider 'DefaultProvider'
I1228 08:40:48.381669       1 factory.go:898] Creating scheduler with fit predicates 'map[MaxGCEPDVolumeCount:{} MatchInterPodAffinity:{} CheckNodeMemoryPressure:{} PodToleratesNodeTaints:{} CheckVolumeBinding:{} CheckNodeDiskPressure:{} CheckNodeCondition:{} NoVolumeZoneConflict:{} MaxEBSVolumeCount:{} MaxAzureDiskVolumeCount:{} NoDiskConflict:{} GeneralPredicates:{}]' and priority functions 'map[BalancedResourceAllocation:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{} SelectorSpreadPriority:{} InterPodAffinityPriority:{} LeastRequestedPriority:{}]'
I1228 08:40:48.381936       1 server.go:573] starting healthz server on 0.0.0.0:10251
E1228 08:40:58.387799       1 reflector.go:205] k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:593: Failed to list *v1.Pod: Get https://127.0.0.1:6443/api/v1/pods?fieldSelector=spec.schedulerName%3Ddefault-scheduler%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.678840       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.ReplicationController: Get https://127.0.0.1:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.679002       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolume: Get https://127.0.0.1:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.880475       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Node: Get https://127.0.0.1:6443/api/v1/nodes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.880684       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolumeClaim: Get https://127.0.0.1:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.880949       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: Get https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.880966       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.StatefulSet: Get https://127.0.0.1:6443/apis/apps/v1beta1/statefulsets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.881279       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.PodDisruptionBudget: Get https://127.0.0.1:6443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:40:58.881607       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.ReplicaSet: Get https://127.0.0.1:6443/apis/extensions/v1beta1/replicasets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1228 08:41:02.691049       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list replicationcontrollers at the cluster scope
E1228 08:41:02.782896       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list nodes at the cluster scope
E1228 08:41:02.785919       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list poddisruptionbudgets.policy at the cluster scope
E1228 08:41:02.787109       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list persistentvolumes at the cluster scope
E1228 08:41:02.787738       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list services at the cluster scope
E1228 08:41:02.790571       1 reflector.go:205] k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:593: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list pods at the cluster scope
E1228 08:41:02.794360       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:kube-scheduler" cannot list persistentvolumeclaims at the cluster scope
E1228 08:41:02.795046       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.ReplicaSet: replicasets.extensions is forbidden: User "system:kube-scheduler" cannot list replicasets.extensions at the cluster scope
I1228 08:41:05.082972       1 controller_utils.go:1019] Waiting for caches to sync for scheduler controller
I1228 08:41:05.183279       1 controller_utils.go:1026] Caches are synced for scheduler controller
I1228 08:41:05.183439       1 leaderelection.go:174] attempting to acquire leader lease...
W1228 08:47:10.323939       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1.Service ended with: too old resource version: 48920913 (48923520)
W1228 08:47:10.324039       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1.PersistentVolumeClaim ended with: too old resource version: 48920913 (48923520)
W1228 08:47:10.324067       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1.ReplicationController ended with: too old resource version: 48920913 (48923520)
I1228 08:47:30.638223       1 leaderelection.go:184] successfully acquired lease kube-system/kube-scheduler
I1228 08:47:30.739515       1 scheduler.go:191] Failed to schedule pod: test/test-5696f749b9-cbh4x
I1228 08:47:30.741050       1 factory.go:1251] Updating pod condition for test/test-5696f749b9-cbh4x to (PodScheduled==False)
I1228 08:47:30.741368       1 scheduler.go:191] Failed to schedule pod: test/test-5696f749b9-qbg5n
I1228 08:47:30.741480       1 factory.go:1251] Updating pod condition for test/test-5696f749b9-qbg5n to (PodScheduled==False)
I1228 08:47:30.741869       1 scheduler.go:191] Failed to schedule pod: test/test-74467b6bc4-8b7gp
I1228 08:47:30.741939       1 factory.go:1251] Updating pod condition for test/test-74467b6bc4-8b7gp to (PodScheduled==False)
I1228 08:47:30.742123       1 scheduler.go:191] Failed to schedule pod: test/test-74467b6bc4-ngpq4
I1228 08:47:30.742212       1 factory.go:1251] Updating pod condition for test/test-74467b6bc4-ngpq4 to (PodScheduled==False)
I1228 08:47:30.742441       1 scheduler.go:191] Failed to schedule pod: test/test-74467b6bc4-pfj4
```

**Comment by arianitu** [comment] 2019-01-14 17:10
I just ran into this, how can I get this to work properly?

**Comment by jayunit100** [comment] 2019-02-07 18:50
I think we may be seeing a variant of this issue on kube 1.10, however, what we're seeing is that a pod keeps getting scheduled to the same node over and over again... and that node doesn't have enough memory to run said pod, so its bounced back.

Is it the `AssumePod` (or something like that) functionality's interaction w/ the cache  is possibly the culprit ?

**Comment by misterikkit** [comment] 2019-02-07 19:34
@arianitu what k8s version are you using? Probably it's best to file a separate issue so that the details don't get mixed up with this one.

@jayunit100 there have been some race conditions that leave stale data in the scheduler cache. Since you observed this in 1.10, it may have been fixed since then. I'd have to look through the history to see which fixes have gone in.

**Comment by arianitu** [comment] 2019-02-07 20:32
My issue was actually due to an auto-scale event that caused labels to be removed from existing nodes. 

I used nodeSelector with a label and after the label was removed I got this error. I re-added the labels and the pod was schedulable again. This is a GCE bug where labels are not added back during upgrades/scaling.

**Comment by misterikkit** [comment] 2019-02-20 20:42
@arianitu even more reason to track the bug in a separate issue (:

**Comment by satishkumar678122** [comment] 2020-11-14 10:12
> @mwielgus - after thinking about it, I have one more idea to check - were there any pods that were finished (i.e. in a success or failure state)?
> 
> [I guess the problem is around caching, but not yet any idea what exactly.]

  Warning  FailedScheduling  7s (x12 over 13m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.

**Comment by satishkumar678122** [comment] 2020-11-14 10:13
Warning  FailedScheduling  7s (x12 over 13m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
  

im irritating with this 

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    -
      image: nginx
      name: nginx
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"pod.yaml" 14L, 206C

**Comment by satishkumar678122** [comment] 2020-11-14 10:14
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    -
      image: nginx
      name: nginx
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
