### ISSUE TITLE
ResourceQuota does not allow limiting the number of ReplicaSet objects in a namespace

### ISSUE THREAD

**Issue by seh** [kubernetes/kubernetes#50686] opened 2017-08-15 13:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
It is not possible to express an object count constraint for _ReplicaSets_ in a _ResourceQuota_ object. At present, _ResourceQuota_ can [constrain the count of _ReplicationControllers_,](https://github.com/kubernetes/kubernetes/blob/788804142f1b3323523500c2932f511284b6eae9/pkg/quota/evaluator/core/replication_controllers.go#L28-L46) but [not _ReplicaSets_](https://github.com/kubernetes/kubernetes/tree/788804142f1b3323523500c2932f511284b6eae9/pkg/quota/evaluator/core).

**What you expected to happen**:
I expected to be able to include a hard limit on the number of _ReplicaSet_ objects by including a "replicasets" field in a _ResourceQuota_'s "spec.hard" object, but the API server rejects such an object.
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    # Accepted:
    replicationcontrollers: 1
    # Rejected:
    replicasets: 1
```

**How to reproduce it**:
Create the _ResourceQuota_ object shown above:
```shell
% kubectl create -f - <<END
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    replicationcontrollers: 1 
    replicasets: 1
END
```
Observe that the API server rejects the proposed object:
```
The ResourceQuota "core-object-counts" is invalid: 
* spec.hard[replicasets]: Invalid value: "replicasets": must be a standard resource type or fully qualified
* spec.hard[replicasets]: Invalid value: "replicasets": must be a standard resource for quota
```

Try again using the qualified resource name:
```shell
% kubectl create -f - <<END
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    replicationcontrollers: 1 
    extensions/v1beta1/replicasets: 1
END
```
Observe that the API server accepts the proposed object, but that the admission control plugin does not record the used count:
```shell
% kubectl get resourcequota core-object-counts-2 -o yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2017-08-15T12:55:31Z
  name: core-object-counts
  namespace: ELIDED
  resourceVersion: "69721114"
  selfLink: /api/v1/namespaces/ELIDED/resourcequotas/core-object-counts
  uid: 05482a90-81b9-11e7-ab5d-3ac4f80ae4b6
spec:
  hard:
    extensions/v1beta1/replicasets: "1"
    replicationcontrollers: "1"
status:
  hard:
    extensions/v1beta1/replicasets: "1"
    replicationcontrollers: "1"
  used:
    replicationcontrollers: "0"
```
Note, however, that there are two _ReplicaSet_ objects in this namespace:
```shell
% kubectl get replicasets -o name | wc -l
       2
```

**Anything else we need to know?**:

My primary interest is to preclude _Deployment_ objects from leaving behind too many _ReplicaSets_ for cases where someone does not configure "spec.revisionHistoryLimit." I understand that this field has since gained a sensible default value, but it's still possible that people can configure it to unreasonable values.

More broadly, though, it looks like [the ResourceQuota admission control plugin](https://kubernetes.io/docs/admin/admission-controllers/#resourcequota) got off to a strong start with core objects, but hasn't kept up with objects in other groups. Why is that so?

**Environment**:
- Kubernetes version:  
  > Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T15:13:53Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
  > 
  > Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.6-21+464b547b816b32", GitCommit:"464b547b816b32a76944088268b69232ef3571c7", GitTreeState:"clean", BuildDate:"2017-07-28T20:20:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  
  (None pertinent)

- OS (e.g. from /etc/os-release):  
  Client: macOS Sierra 10.12.6
  Server: Ubuntu 16.04.1 LTS

- Kernel (e.g. `uname -a`):  
  4.4.0-78-generic

**Comment by seh** [comment] 2017-08-15 13:19
@kubernetes/sig-apps-feature-requests
@kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment] 2017-08-30 15:19
@seh Thanks for reporting, I am refactoring this part and would like to take a deep look here. Will feedback soon.

**Comment by resouer** [comment] 2017-08-30 15:34
Kindly ping @deads2k , any idea on this issue? Is there any history reason we excluded ReplicaSet quota here?

**Comment by seh** [comment] 2017-08-30 15:37
That's great news, @resouer. I realize that _ReplicaSets_ are just one of many kinds not addressed by quotas today, but they are certainly one of the more popular kinds in use.

We have recently discovered that we'd also like the ability to constrain the number of "headed" versus "headless" _Service_ objects in a given namespace—to control the load imposed on _kube-proxy_ and _iptables_—but I suppose that's fodder for a separate issue.

**Comment by deads2k** [comment] 2017-08-30 15:38
> That's great news, @resouer. I realize that ReplicaSets are just one of many kinds not addressed by quotas today, but they are certainly one of the more popular kinds in use.

@derekwaynecarr has some ideas about generic object counts.  I'd rather see generic object counts pursued in preference to more one offs.  This would allow us to make quota more aggregatable.

**Comment by resouer** [comment] 2017-08-30 15:47
Agree, I can imagine the difficulty if we constrain all objects (which count is also growing ... ) one by one ...

**Comment by timothysc** [comment] 2017-09-06 21:32
This isn't really sig-scheduling's purview here.  Punting to /cc @kubernetes/sig-api-machinery-feature-requests

**Comment by kargakis** [comment] 2017-09-10 23:22
Dupe of https://github.com/kubernetes/kubernetes/issues/33650

**Closed by kargakis** 2017-09-10 23:22 UTC
Labels: kind/feature, sig/api-machinery, sig/apps
