### ISSUE TITLE
Add request usage rate to kubectl top 

### ISSUE THREAD

**Issue by ringtail** [kubernetes/kubernetes#73173] opened 2019-01-22 12:45 UTC
**What would you like to be added**:

Add a column of cpu and memory resource request usage rate 

**Why is this needed**:
```
NAME                                    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ap-southeast-1.i-t4n4g4xxyjqq4m1za2ge   876m         43%    4492Mi          58%
ap-southeast-1.i-t4naf4vt9ntpq52jigmy   690m         34%    4543Mi          58%
ap-southeast-1.i-t4nft9jkf356fnc1x60e   374m         18%    3250Mi          47%
ap-southeast-1.i-t4nhigpx87cif4a18x1k   796m         39%    4518Mi          58%
ap-southeast-1.i-t4ni9xnerwj6pqpz5y1p   791m         19%    953Mi           3%
ap-southeast-1.i-t4nj3b0kv2l06kzlpbo2   667m         33%    1975Mi          70%
ap-southeast-1.i-t4nj3b0kv2l06kzlpbo3   478m         23%    1524Mi          54%
```
Here is the current kubectl top node. But in kubernetes resource request means a lot in scheduling.  The value above can not tell any useful information for resource inventory and scheduling especially when you need to delete or scale down some nodes.

**Comment by lentzi90** [comment] 2019-06-01 16:31
I think this is a duplicate of #17512

**Closed** 2019-07-01 17:25 UTC
Labels: kind/feature, lifecycle/rotten, sig/autoscaling
