### ISSUE TITLE
Kubernetes uses Openstack cloud provider

### ISSUE THREAD

**Issue by drngsl** [kubernetes/kubernetes#20146] opened 2016-01-26 06:50 UTC
Hi!
I want to use openstack to provide storage for kubernetes pod, but when I run kubelet --cloud-provider=openstack --cloud-config=/etc/cloud.conf. It causes some errors.

kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

/etc/cloud.conf

```
[Global]
auth-url=https://162.3.132.50:443/identity/v2.0
username=username
password=password
region=RegionOne1
tenant-id=a1fa87b6b770496e929685fd5f1e0e18
```

And Errors like this:

```
I0126 06:32:54.408314   31559 server.go:273] Using root directory: /var/lib/kubelet
I0126 06:32:54.408556   31559 manager.go:127] cAdvisor running in container: "/user/0.user/7.session"
I0126 06:32:54.408994   31559 fs.go:93] Filesystem partitions: map[/dev/disk/by-label/cloudimg-rootfs:{mountpoint:/ major:253 minor:1}]
I0126 06:32:54.611071   31559 manager.go:158] Machine: {NumCores:1 CpuFrequency:2499998 MemoryCapacity:2099146752 MachineID:1fae653b5915a5674b404ebe55356ffe SystemUUID:08B94B58-03E6-4DC8-AF72-6676A4C73DAF BootID:19caa194-ce92-4e3c-b7df-947007ac685b Filesystems:[{Device:/dev/disk/by-label/cloudimg-rootfs Capacity:20062785536}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:21474836480 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:fa:16:3e:e7:f5:b3 Speed:0 Mtu:1400} {Name:flannel0 MacAddress: Speed:10 Mtu:1372}] Topology:[{Id:0 Memory:2099146752 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown}
I0126 06:32:54.612693   31559 manager.go:164] Version: {KernelVersion:3.13.0-49-generic ContainerOsVersion:Ubuntu 14.04.2 LTS DockerVersion:1.6.0 CadvisorVersion:0.16.0}
I0126 06:32:54.644869   31559 server.go:292] Successfully initialized cloud provider: "openstack" from the config file: "/etc/cloud.conf"
I0126 06:32:55.603302   31559 server.go:413] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
I0126 06:32:55.603472   31559 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
I0126 06:32:55.604560   31559 openstack.go:160] openstack.Instances() called
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x53c6e2]
.......
```

**Comment by AdoHe** [comment] 2016-01-26 10:06
@drngsl maybe you can check this #19264

**Comment by drngsl** [comment] 2016-01-26 12:43
@AdoHe , I checked that, but kubelet service on the minion nodes still can not restart.
kubelet conf on minion nodes
/etc/default/kubelet
# Kubelet Upstart and SysVinit configuration file

# Customize kubelet binary location
# KUBELET="/opt/bin/kubelet"

# Use KUBELET_OPTS to modify the start/restart options
KUBELET_OPTS="--address=0.0.0.0 \
  --port=10250 \
  --hostname_override=10.0.0.13 \
  --api_servers=10.0.0.15:8080 \
  --logtostderr=false \
  --log_dir=/var/log/kubernetes
  --cloud-provider=openstack\
  --cloud-config=/etc/cloud.conf\
  --v=5"

the Cloud-provider param is added by me.
After I restart kubelet service, result is like this:
root@serverceeb3051-1e23-4932-922b-b14a673ecf37:~# ps -ef | grep kube
root      1906     1  0 Jan21 ?        00:18:31 /opt/bin/kube-proxy --logtostderr=false --master=http://10.0.0.15:8080 --log_dir=/var/log/kubernetes
root      5449 14481  0 12:20 pts/6    00:00:00 grep --color=auto kube

And in log file only print the following log:
root@server1eb1b5ce-9649-4e60-9768-35bcc788fb2e:/var/lib/kubelet/plugins# vi /var/log/kubernetes/kubelet.INFO 

Log file created at: 2016/01/26 12:41:07
Running on machine: server1eb1b5ce-9649-4e60-9768-35bcc788fb2e
Binary: Built with gc go1.4.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0126 12:41:07.198835    4881 server.go:474] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0126 12:41:07.200069    4881 server.go:436] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0126 12:41:07.200113    4881 server.go:273] Using root directory: /var/lib/kubelet
I0126 12:41:07.200168    4881 manager.go:127] cAdvisor running in container: "/"
I0126 12:41:07.200548    4881 fs.go:93] Filesystem partitions: map[/dev/disk/by-label/cloudimg-rootfs:{mountpoint:/ major:253 minor:1}]
I0126 12:41:07.958450    4881 manager.go:158] Machine: {NumCores:1 CpuFrequency:2499998 MemoryCapacity:2099146752 MachineID:1fae653b5915a5674b404ebe55356ffe SystemUUID:5A47E84C-89EB-4774-812D-498E02B33144 BootID:f9e5a83f-6a9e-4daa-817d-b2fbba5215f2 Filesystems:[{Device:/dev/disk/by-label/cloudimg-rootfs Capacity:20062785536}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:21474836480 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:fa:16:3e:23:ff:49 Speed:0 Mtu:1400} {Name:flannel0 MacAddress: Speed:10 Mtu:1372}] Topology:[{Id:0 Memory:2099146752 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown}
I0126 12:41:07.959696    4881 manager.go:164] Version: {KernelVersion:3.13.0-49-generic ContainerOsVersion:Ubuntu 14.04.2 LTS DockerVersion:1.6.0 CadvisorVersion:0.16.0}
I0126 12:41:07.990864    4881 server.go:292] Successfully initialized cloud provider: "openstack" from the config file: "/etc/cloud.conf"
I0126 12:41:08.611983    4881 server.go:413] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
I0126 12:41:08.612018    4881 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
I0126 12:41:08.612068    4881 openstack.go:160] openstack.Instances() called
[new 3.txt](https://github.com/kubernetes/kubernetes/files/104884/new.3.txt)

**Comment by AdoHe** [comment] 2016-01-27 09:51
@drngsl are you using systemd? can you past `systemctl status kubelet` or `journalctl /usr/bin/kubelet` result here?

**Comment by drngsl** [comment] 2016-01-27 11:37
@AdoHe, No. My cluster host system is Ubuntu.
On ubuntu, which command can replace it?

**Comment by loshkovskyi** [comment] 2016-01-28 21:00
In Ubuntu 14.04 they use Upstart. Try these commands:
```
service kubelet status
grep kubelet /var/log/syslog
```
I was able to reproduce this runtime error and debugging it now.

**Comment by drngsl** [comment] 2016-01-29 00:39
@loshkovskyi, thanks.
But I can just get a little info. 
And I have updated this version to v1.1.4, but some about x509 error raises.https://github.com/kubernetes/kubernetes/issues/20266
Can you have a look for me?
Thank you!

**Comment by AdoHe** [comment] 2016-01-29 03:17
@drngsl From the log you pasted, kubelet is using self-signed certificates, but that's ok, these certificates are not used when you get cloud provider, so I think the problem is that your cloud conf file.

**Comment by drngsl** [comment] 2016-01-29 10:29
@AdoHe , I'm not sure that cloud-config the right for openstack or not. But when I use flocker to connect to openstack, it's ok.

**Comment by loshkovskyi** [comment] 2016-01-29 17:11
@drngsl, today I'm not able to reproduce the issue on my environment any more. We've switched to using API keys instead of passwords in Keystone. So using the same environment as before, I'm no longer able to catch the panic error. This leads me to a thought that the error had something to do with the password. I had some special symbols in the password (like a dollar sign), whereas the API keys use only letters and digits. I'll see if I come up with an idea of how to test this.

So now, I'm able to connect to Cinder without errors (I cut output a little bit for readability):
```
# cat /etc/issue
Ubuntu 14.04.3 LTS

# kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.3", GitCommit:"61c6ac5f350253a4dc002aee97b7db7ff01ee4ca", GitTreeState:"clean"}

# /opt/bin/kubelet --address=0.0.0.0 \
                   --port=10250 \
                   --hostname-override=kube-test1 \
                   --api-servers=http://kube-test1:8080 \
                   --logtostderr=true \
                   --cluster-dns=192.168.3.10 \
                   --cluster-domain=cluster.local \
                   --cloud-provider=openstack \
                   --cloud-config=/etc/cloud.conf \
                   --v=4

I0129 16:25:19.943279   16025 server.go:524] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
W0129 16:25:19.943447   16025 server.go:585] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0129 16:25:19.943481   16025 server.go:547] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0129 16:25:22.206404   16025 server.go:468] Successfully initialized cloud provider: "openstack" from the config file: "/etc/cloud.conf"
I0129 16:25:22.282398   16025 fs.go:108] Filesystem partitions: map[/dev/disk/by-uuid/f27e46f8-dd81-4edb-86b0-2ec0696d26dd:{mountpoint:/ major:253 minor:1 fsType: blockSize:0}]
I0129 16:25:22.307949   16025 server.go:485] Using root directory: /var/lib/kubelet
I0129 16:25:22.308210   16025 openstack.go:164] openstack.Instances() called
I0129 16:25:25.295486   16025 openstack.go:201] Found 25 compute flavors
I0129 16:25:25.295658   16025 openstack.go:202] Claiming to support Instances
I0129 16:25:25.295737   16025 server.go:718] cloud provider determined current node name to be kube-test1
I0129 16:25:25.295845   16025 server.go:728] Sending events to api server.
I0129 16:25:25.295991   16025 server.go:808] Watching apiserver
I0129 16:25:25.302668   16025 config.go:254] Setting pods for source api
...
```

And I've tested the OpenStack cloud provider works fine with the current latest version of Kubernetes:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
```

Although, there shouldn't be any problems with the version: the plugin was last time updated in October:
```
git log --stat kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
```

Could you verify the password you use?
Also, please pay attention to this option:
```
--hostname-override=kube-test1
```
This hostname should match the hostname of your machine and the name your machine has in Nova, which you can check with:
```
openstack server list
```
It's crucial for the hostnames to match because plugin compares them to determine to which host your Cinder volumes should be attached.

If they don't match, you may start getting such errors in your `kubelet` logs:
```
E0129 16:28:16.408227   16098 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: Failed to find object
```

**Comment by drngsl** [comment] 2016-01-30 06:20
@loshkovskyi .
Thanks for you detailed answer.
My environment now is v1.1.4.
When I replace password with api-key or replace name with user-id,
it prompts that :
I0130 06:15:01.704562   22436 server.go:524] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
could not init cloud provider "openstack": The base Identity V2 API does not accept authentication by APIKey
or
I0130 06:15:44.316297   22550 server.go:524] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
could not init cloud provider "openstack": The base Identity V2 API does not accept authentication by UserID

when the auth-url config is like auth-url=https://identity.hybrid.cloud.dt.com:443/identity/v2.0
it prompts:
I0130 06:17:23.156280   22821 server.go:524] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
could not init cloud provider "openstack": Post https://identity.hybrid.cloud.dt.com:443/identity/v2.0/tokens: x509: certificate is valid for *.*.*.domainname.com, not identity.hybrid.cloud.dt.com

**Comment by loshkovskyi** [comment] 2016-01-30 11:31
@drngsl, the errors like `The base Identity V2 API does not accept authentication by...` are coming from Keystone. So if your identity service does not accept user ids, then use usernames, etc. I don't think you can do much in this case but to consult with your cloud administrator or cloud provider to find out how to correctly authenticate in Keystone.
Same is for the certificates error. FYI: https://github.com/rackspace/gophercloud/issues/517 (the OpenStack provider in Kubernetes leverages the `gophercloud` package).
So, first of all, please make sure you are able to authenticate in Keystone either using the `curl` commands or a `keystone` client.

**Comment by drngsl** [comment] 2016-01-30 11:53
@loshkovskyi , In minion node, I am able to authenticate in Keystone using the `curl` command
```
curl https://identity.hybrid.cloud.dt.com:443/identity/v2.0/tokens --insecure --header "Content-Type:application/json" -X POST -d '{"auth": {"tenantId": "a1fa87b6b770496e929685fd5f1e0e18","passwordCredentials": {"userId": "ccb1020e9b9e47bd98c4df38cd426590","password": "password"}}}'
curl https://identity.hybrid.cloud.dt.com:443/identity/v2.0/tokens --insecure --header "Content-Type:application/json" -X POST -d '{"auth": {"tenantId": "a1fa87b6b770496e929685fd5f1e0e18","passwordCredentials": {"username": "admin","password": "password"}}}'
while not in kubernetes.
```

**Comment by drngsl** [comment] 2016-02-05 09:31
@loshkovskyi , thanks for you response.
when I need to post request to keystone with https protocol, of course, here it is not succeed. 
For kubelet, does it need to add other configurations, like `--tls-cert-file` `--tls-private-key-file`?

**Comment by AdoHe** [comment] 2016-02-05 15:28
@drngsl IIRC these two flags will not be used when you get cloud provider

**Comment by drngsl** [comment] 2016-02-05 15:54
@AdoHe, thanks!
If my keystone auth_url need to use url like https://*.*.*.mydomain.com, can i use the above cloud config kubelet directly?
Although, I can not use it to connect kubelet with openstack successful currently.

**Comment by drngsl** [comment] 2016-02-05 15:54
@AdoHe, thanks!
If my keystone auth_url need to use url like https://*.*.*.mydomain.com, can i use the above cloud config kubelet directly?
Although, I can not use it to connect kubelet with openstack successful currently.

**Comment by loshkovskyi** [comment] 2016-02-06 13:07
@drngsl, yes, you can use `https` in your `cloud.conf` for the `auth-url` variable.

**Comment by drngsl** [comment] 2016-02-13 14:00
@loshkovskyi 
There is a case, if my keystone endpoint-list uses domain name for client to visit, but my domain name isn't registered in CA, so I can't visit it directly with `http`, while cmd curl `--insecure ...` can make it. 

In k8s, method  `kubernetes/Godeps/_workspace/src/github.com/rackspace/gophercloud/provider_client.go:Request`
`func (client *ProviderClient) Request(method, url string, options RequestOpts) (*http.Response, error) {
	...
	// Construct the http.Request.
	req, err := http.NewRequest(method, url, body)
	if err != nil {
		return nil, err
	}

	// Populate the request headers. Apply options.MoreHeaders last, to give the caller the chance to
	// modify or omit any header.
	if contentType != nil {
		req.Header.Set("Content-Type", *contentType)
	}
	req.Header.Set("Accept", applicationJSON)

	for k, v := range client.AuthenticatedHeaders() {
		req.Header.Add(k, v)
	}

	// Set the User-Agent header
	req.Header.Set("User-Agent", client.UserAgent.Join())

	if options.MoreHeaders != nil {
		for k, v := range options.MoreHeaders {
			if v != "" {
				req.Header.Set(k, v)
			} else {
				req.Header.Del(k)
			}
		}
	}

	// Issue the request.
	resp, err := client.HTTPClient.Do(req)
	...

	return resp, nil
}`
if the parameter about HTTP can add config like `tr := &http.Transport{ 
TLSClientConfig:    &tls.Config{InsecureSkipVerify: true}, 
} `, my authentication may be valid.
Of cause, if this parameter can be setted in cloud config, that will be better?

**Comment by abourget** [comment] 2016-05-07 06:57
I'm hitting a similar issue, but in my case.. I'd like to do the verification of Keystone.  Where does the kubelet read the ca-certs on the system ? I thought it was `/etc/ssl/certs` (as per https://golang.org/src/crypto/x509/root_unix.go ) but it doesn't seem to work for some reasons.

**Comment by drngsl** [comment] 2016-05-08 08:40
@abourget 
for me, I don't how to config certifications for https, so I use --insecure option for https protocal.

**Comment by xsgordon** [comment] 2017-01-17 23:40
@idvoretskyi looks like this was only re-opened due to getting name dropped in https://github.com/kubernetes/kubernetes/issues/26527 - I think we can close this one as 26527 remains open for tracking.

**Comment by idvoretskyi** [comment] 2017-01-26 16:12
@xsgordon closed.

**Closed by idvoretskyi** 2017-01-26 16:12 UTC
Labels: area/kubectl, sig/node, sig/openstack
