### ISSUE TITLE
Update docs to indidcate that CPU limits are enforced using CPU hardcapping

### ISSUE THREAD

**Issue by stefanodoni** [kubernetes/kubernetes#27605] opened 2016-06-17 07:35 UTC
Hi,

as per current k8s doc, setting containers CPU limits translates to setting docker --cpu-shares option (http://kubernetes.io/docs/user-guide/compute-resources/):

_**The spec.container[].resources.limits.cpu is multiplied by 1024, converted to an integer, and used as the value of the --cpu-shares flag to the docker run command.**_

However, I have just verified that this is not (no longer?) the case.

I have created a CPU bound container which tries to burn 4 CPUs in k8s 1.2.4, with the following CPU requests and limits:

$ kubectl describe pod stress-c4 | egrep -A1 'Limits|Req'
Limits:
cpu: 2
Requests:
cpu: 1

This translates to a docker container with the following CPU settings:

sudo docker inspect 230cba933305 | grep -i cpu
"CpuShares": 1024,
"CpuPeriod": 100000,
"CpusetCpus": "",
"CpusetMems": "",
"CpuQuota": 200000,

Which means that:
- CPU shares = CPU requests * 1024
- CPU quota = CPU limits * 100000

So, what actually affects CPU shares is the CPU requests parameter, not the limits. Furthermore, when limits are set, it actually affects CPU quota, which implies that container is actually capped at 2 CPUs:

CONTAINER CPU % MEM USAGE / LIMIT MEM % NET I/O BLOCK I/O
230cba933305 200.59% 221.2 kB / 4.072 GB 0.01% 0 B / 0 B 0 B / 0 B

Questions:

1) Is this the intended behavior? I remember having read some design discussions about this and the consensus seemed to be that containers should not be capped CPU-wise, and the current doc seem to agree with that.
2) If this is the intended behavior, the doc should be updated to clearly state that setting CPU limits is not translating to CPU shares, but actually result in CPU capping.

Thank you!

**Comment by AdoHe** [comment] 2016-06-17 11:23
@kubernetes/sig-node

**Comment by lavalamp** [comment] 2016-06-18 00:43
I believe the behavior is correct.

**Comment by yujuhong** [comment] 2016-06-18 00:52
FYI, cpu capping in v1.2 release note: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#v120

**Comment by vishh** [comment] 2016-06-20 04:50
CPU `limits` are enforced using **hardcapping** and `requests` are enforced using **shares**. 
So its working as intended. 

The docs might have to be fixed. I updated the issue title to reflect that. 

Thanks for filing the issue @stefanodoni

**Comment by vishh** [comment] 2016-06-23 23:24
Fixed via https://github.com/kubernetes/kubernetes.github.io/pull/472

**Closed by vishh** 2016-06-23 23:24 UTC
Labels: documentation/confusing, team/control-plane
