### ISSUE TITLE
e2e flake: "paused deployment should be ignored" [timeout]

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#21491] opened 2016-02-18 19:19 UTC
```
â€¢ Failure [17.862 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:68
  paused deployment should be ignored by the controller [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:61

  Expected error:
      <*errors.errorString | 0xc20854f090>: {
          s: "deployment \"nginx\" shouldn't have a replica set but there is \"nginx-z2k7j\"",
      }
      deployment "nginx" shouldn't have a replica set but there is "nginx-z2k7j"
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:569
```

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21286/kubernetes-pull-build-test-e2e-gce/29183/

**Comment by bgrant0607** [comment] 2016-02-18 22:26
cc @janetkuo @kargakis @mqliang

**Comment by bprashanth** [comment] 2016-02-18 23:58
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21431/kubernetes-pull-build-test-e2e-gce/29257/artifacts/
http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//29257
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:61
Expected error:
    <*errors.errorString | 0xc20853a070>: {
        s: "deployment \"nginx\" shouldn't have a replica set but there is \"nginx-8kyi7\"",
    }
    deployment "nginx" shouldn't have a replica set but there is "nginx-8kyi7"
not to have occurred
```

**Comment by bgrant0607** [comment] 2016-02-19 20:27
This is not necessarily the cause of this problem, but we shouldn't have updates w/o retries:
```
	deployment.Spec.Paused = true
	deployment.ResourceVersion = ""
	deployment, err = c.Extensions().Deployments(ns).Update(deployment)
	Expect(err).NotTo(HaveOccurred())
```

**Comment by bgrant0607** [comment] 2016-02-19 20:29
There are 5 updates w/o retries in deployment.go.

**Comment by bgrant0607** [comment] 2016-02-19 20:41
Ref #21479

**Comment by bgrant0607** [comment] 2016-02-19 20:43
I wonder if this could also be related to #21576

**Comment by bgrant0607** [comment] 2016-02-19 20:56
This test is racy. It pauses, deletes the latest ReplicaSet, confirms that the Deployment is paused, then confirms that the latest ReplicaSet wasn't recreated.

Without generation/observedGeneration, there's no way to confirm that the controller has actually paused.

**Comment by bgrant0607** [comment] 2016-02-19 20:58
The test does confirm that a Deployment created as paused doesn't create a ReplicaSet.

**Comment by janetkuo** [comment] 2016-02-19 22:15
> There are 5 updates w/o retries in deployment.go.

Filed #21586 to fix this

**Comment by janetkuo** [comment] 2016-02-22 19:44
Another failure reported by @ihmccreery :
```
07:35:54   Expected error:
07:35:54       <*errors.errorString | 0xc209399800>: {
07:35:54           s: "deployment \"nginx\" shouldn't have a replica set but there is \"nginx-t9avk\"",
07:35:54       }
07:35:54       deployment "nginx" shouldn't have a replica set but there is "nginx-t9avk"
07:35:54   not to have occurred
```
See http://kubekins.dls.corp.google.com/job/kubernetes-upgrade-gke-1.0-master-step7-e2e-new/

**Comment by bgrant0607** [comment] 2016-02-23 02:08
@kargakis @nikhiljindal @janetkuo @mqliang 

This test is racy. It pauses the Deployment and then deletes the ReplicaSet without confirming the controller has observed the pause.

If we implemented generation/observedGeneration, we could use that to determine that pause had been observed.

Or, if we could scale paused deployments (#20273), we could pause, scale, and wait for the scale to take effect, since that must causally follow the pause. But that's not in yet, either.

We need the controller to provide SOME indication that it acted upon the change. It needs to at least report status, for example.

**Comment by nikhiljindal** [comment] 2016-02-23 07:55
Another hack to fix this will be to generate an event when controller sees the paused deployment, but depending on events is discouraged https://github.com/kubernetes/kubernetes/issues/21511

As far as I know, I dont think anyone is working on observedGeneration.

@kargakis By when do you think https://github.com/kubernetes/kubernetes/pull/20273 will be merged?

**Comment by kargakis** [comment] 2016-02-23 13:26
@nikhiljindal it's moving forward but I am not sure. We still need to sort things out like new rs creation during paused... I am going to submit a PR adding observedGeneration to deployments later today, that should be much more trivial to get in and use here as a fix.

**Comment by nikhiljindal** [comment] 2016-02-23 19:09
Great. I see that https://github.com/kubernetes/kubernetes/pull/21754 should fix this.

**Comment by bgrant0607** [comment] 2016-02-24 15:36
This test is now failing continuously.

**Comment by janetkuo** [comment] 2016-02-25 19:41
Taking a look at this now.

**Comment by nikhiljindal** [comment] 2016-02-25 19:46
I am pretty sure that the problem is https://github.com/kubernetes/kubernetes/issues/21753#issuecomment-188673390.

I am trying out a fix

**Comment by janetkuo** [comment] 2016-02-25 19:49
Thanks @nikhiljindal!

**Closed** 2016-02-26 00:10 UTC
Labels: area/app-config-deployment, kind/flake, priority/P0, team/ux
