### ISSUE TITLE
Use `nfs-client-provisioner` instead of `nfs-provisioner` for dynamic nfs storage e2e tests

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#73535] opened 2019-01-30 18:11 UTC
**What would you like to be added**: tests should start nfs-server+nfs-client-provisioner pods instead of starting an nfs-provisioner pod.

**Why is this needed**: It will be more consistent for all tests, dynamic/preprovisioned, to use nfs-server (containerized kernel nfs). And it will insulate us from nfs-provisioner bugs. nfs-provisioner is good enough as an all-in-one solution for testing the external provisioner interface but the scope of our e2e testing has expanded beyond that

/assign

**Comment by davidz627** [comment] 2019-03-06 22:08
@wongma7 will you be able to submit a fix for this in 1.14?

**Comment by wongma7** [comment] 2019-03-07 18:35
@davidz627 I've opened https://github.com/kubernetes/kubernetes/pull/75130

**Comment by davidz627** [comment] 2019-06-10 20:11
/remove-lifecycle stale
I believe the PR referenced has not yet merged and the issue is not resolved

**Comment by davidz627** [comment] 2019-09-09 22:19
/remove-lifecycle stale
I believe the PR referenced has not yet merged and the issue is not resolved

**Closed** 2020-02-07 00:42 UTC
Labels: kind/feature, lifecycle/rotten, needs-sig, sig/storage
