### ISSUE TITLE
kubelet utilization goes upto 400percent

### ISSUE THREAD

**Issue by ksarkaridirect** [kubernetes/kubernetes#68894] opened 2018-09-20 18:58 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Kubelet utilization on both master and worker node spikes upto 400 percent. I have seen a few bugs reported on it, but the resolve was not clear from reading the bugs. I am running 1.7.3 docker and my hardware has 64 cpus and is a sufficiently powerful dell fx2 blade with one master and one worker node.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.7.3
- Cloud provider or hardware configuration: 64 cpus intel/ dell fx2 server
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ksarkaridirect** [comment] 2018-09-20 19:12
/sig/kubelet

**Comment by dims** [comment] 2018-09-21 00:26
/close

duplicate of https://github.com/kubernetes/kubernetes/issues/68893 ?

**Closed by dims** 2018-09-21 00:26 UTC
Labels: needs-sig
