### ISSUE TITLE
Kubelet resource usage tracking tests flaking

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20231] opened 2016-01-27 19:55 UTC
E.g.

- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/1587
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/338
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/311

**Comment by yujuhong** [comment] 2016-01-27 20:59
https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/1587

The docker cpu usage is abnormally high for running only 10 addon pods on one node (`e2e-slow-minion-z57z`).

```
07:52:28 CPU usage of containers on node "e2e-slow-minion-z57z"
07:52:28 :container        5th%  20th% 50th% 70th% 90th% 95th% 99th%
07:52:28 "/"              1.982 1.993 1.999 2.000 2.000 2.000 2.000
07:52:28 "/docker-daemon" 0.502 0.516 0.529 0.540 0.561 0.564 0.569
07:52:28 "/kubelet"       0.000 0.000 0.000 0.000 0.000 0.000 0.000
07:52:28 "/system"        0.029 0.033 0.037 0.041 0.045 0.047 0.066
```
```
07:52:29 Jan 27 07:52:29.027: INFO: POD                                         NODE                  PHASE    GRACE  CONDITIONS
07:52:29 Jan 27 07:52:29.027: INFO: elasticsearch-logging-v1-hrdek              e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:00 -0800 PST  }]
07:52:29 Jan 27 07:52:29.028: INFO: elasticsearch-logging-v1-ok40a              e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:00 -0800 PST  }]
07:52:29 Jan 27 07:52:29.029: INFO: fluentd-elasticsearch-e2e-slow-minion-z57z  e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:35 -0800 PST  }]
07:52:29 Jan 27 07:52:29.030: INFO: heapster-v13-o33li                          e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:32:51 -0800 PST  }]
07:52:29 Jan 27 07:52:29.030: INFO: kibana-logging-v1-0em47                     e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:25 -0800 PST  }]
07:52:29 Jan 27 07:52:29.031: INFO: kube-dns-v10-ljmmy                          e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:18 -0800 PST  }]
07:52:29 Jan 27 07:52:29.031: INFO: kube-proxy-e2e-slow-minion-z57z             e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:23:54 -0800 PST  }]
07:52:29 Jan 27 07:52:29.031: INFO: kube-ui-v4-uwzlg                            e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:23:54 -0800 PST  }]
07:52:29 Jan 27 07:52:29.031: INFO: l7-lb-controller-drg14                      e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:24:59 -0800 PST  }]
07:52:29 Jan 27 07:52:29.031: INFO: monitoring-influxdb-grafana-v3-0pa2s        e2e-slow-minion-z57z  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-01-27 07:25:29 -0800 PST  }]
```

Nothing abnormal in `kubelet.log` during the two minutes of measurement. Note that another resource usage tracking (35 pods) also failed on this node later. This means either something was hammering docker or the numbers gathered are wrong.

I will look at other failures and see if there is any common pattern.

**Comment by yujuhong** [comment] 2016-01-27 21:11
It seems all the failures coincided with the heapster version bump and the gce-slow suite is back to normal after the revert #20215 landed. 

I'll start a cluster with the newer version of heapster to verify and also to check why the docker cpu usage is so high even with container restart backoff. 

Lowering the priority since the revert should've already fixed the builds.

**Comment by yujuhong** [comment] 2016-01-27 22:19
Hepaster's "eventer" container was dumping a ridiculous number of messages in the log ~7 min after starting. I can reliably reproduce this with the new heapseter (`gcr.io/google_containers/heapster:v0.20.0-alpha1`).

```
{"log":"I0127 21:31:01.202265       1 eventer.go:50] /eventer --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086\n","stream":"stderr","time":"2016-01-27T21:31:01.214337072Z"}
{"log":"I0127 21:31:01.202745       1 eventer.go:51] Eventer version 0.20.0-alpha1\n","stream":"stderr","time":"2016-01-27T21:31:01.215350855Z"}
{"log":"E0127 21:31:11.392170       1 influxdb.go:176] issues while creating an InfluxDB sink: failed to ping InfluxDB server at \"monitoring-influxdb:8086\" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.0.0.10:53: server misbehaving, will retry on use\n","stream":"stderr","time":"2016-01-27T21:31:11.411100497Z"}
{"log":"I0127 21:31:11.392213       1 influxdb.go:190] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s\n","stream":"stderr","time":"2016-01-27T21:31:11.411161514Z"}
{"log":"I0127 21:31:11.392227       1 eventer.go:73] Starting with InfluxDB Sink sink\n","stream":"stderr","time":"2016-01-27T21:31:11.411170663Z"}
{"log":"I0127 21:31:11.392243       1 eventer.go:87] Starting eventer\n","stream":"stderr","time":"2016-01-27T21:31:11.411176612Z"}
{"log":"I0127 21:31:30.000175       1 manager.go:78] Exporting 12 events\n","stream":"stderr","time":"2016-01-27T21:31:30.000372379Z"}
{"log":"I0127 21:31:30.027743       1 influxdb.go:168] Created database \"k8s\" on influxDB server at \"monitoring-influxdb:8086\"\n","stream":"stderr","time":"2016-01-27T21:31:30.028019834Z"}
{"log":"I0127 21:32:00.000116       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:32:00.000278256Z"}
{"log":"I0127 21:32:30.000117       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:32:30.000393141Z"}
{"log":"I0127 21:33:00.000208       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:33:00.000389592Z"}
{"log":"I0127 21:33:30.000199       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:33:30.000421969Z"}
{"log":"I0127 21:34:00.000173       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:34:00.000551243Z"}
{"log":"I0127 21:34:30.000150       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:34:30.000330527Z"}
{"log":"I0127 21:35:00.000490       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:35:00.000704676Z"}
{"log":"I0127 21:35:30.000165       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:35:30.000436932Z"}
{"log":"I0127 21:36:00.000146       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:36:00.000306467Z"}
{"log":"I0127 21:36:30.000132       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:36:30.000293675Z"}
{"log":"I0127 21:37:00.000144       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:37:00.000318992Z"}
{"log":"I0127 21:37:30.000229       1 manager.go:78] Exporting 0 events\n","stream":"stderr","time":"2016-01-27T21:37:30.000416054Z"}
{"log":"E0127 21:37:41.890510       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890599547Z"}
{"log":"E0127 21:37:41.890535       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890659931Z"}
{"log":"E0127 21:37:41.890539       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.89068599Z"}
{"log":"E0127 21:37:41.890547       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890691022Z"}
{"log":"E0127 21:37:41.890550       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890695172Z"}
{"log":"E0127 21:37:41.890553       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890699842Z"}
{"log":"E0127 21:37:41.890556       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890704012Z"}
{"log":"E0127 21:37:41.890558       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890727484Z"}
{"log":"E0127 21:37:41.890561       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890732187Z"}
{"log":"E0127 21:37:41.890564       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890735776Z"}
{"log":"E0127 21:37:41.890567       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890739533Z"}
{"log":"E0127 21:37:41.890569       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890743365Z"}
{"log":"E0127 21:37:41.890572       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890747158Z"}
{"log":"E0127 21:37:41.890575       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890750894Z"}
{"log":"E0127 21:37:41.890577       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890755682Z"}
{"log":"E0127 21:37:41.890580       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890761288Z"}
{"log":"E0127 21:37:41.890582       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890778086Z"}
{"log":"E0127 21:37:41.890585       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890785152Z"}
{"log":"E0127 21:37:41.890588       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890791365Z"}
{"log":"E0127 21:37:41.890590       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890859018Z"}
{"log":"E0127 21:37:41.890593       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890866286Z"}
{"log":"E0127 21:37:41.890596       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890870288Z"}
{"log":"E0127 21:37:41.890598       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890873712Z"}
{"log":"E0127 21:37:41.890601       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890877584Z"}
{"log":"E0127 21:37:41.890604       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890881343Z"}
{"log":"E0127 21:37:41.890607       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890885372Z"}
{"log":"E0127 21:37:41.890609       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890888966Z"}
{"log":"E0127 21:37:41.890612       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890892719Z"}
{"log":"E0127 21:37:41.890614       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890896384Z"}
{"log":"E0127 21:37:41.890617       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890900186Z"}
{"log":"E0127 21:37:41.890620       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890905554Z"}
{"log":"E0127 21:37:41.890622       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890910615Z"}
{"log":"E0127 21:37:41.890625       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890915758Z"}
{"log":"E0127 21:37:41.890627       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890920996Z"}
{"log":"E0127 21:37:41.890630       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890937439Z"}
{"log":"E0127 21:37:41.890633       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890944138Z"}
{"log":"E0127 21:37:41.890635       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890948935Z"}
{"log":"E0127 21:37:41.890638       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890952978Z"}
{"log":"E0127 21:37:41.890641       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890956444Z"}
{"log":"E0127 21:37:41.890643       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890960205Z"}
{"log":"E0127 21:37:41.890647       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.89096411Z"}
{"log":"E0127 21:37:41.890649       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890967605Z"}
{"log":"E0127 21:37:41.890652       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.89097153Z"}
{"log":"E0127 21:37:41.890655       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890975413Z"}
{"log":"E0127 21:37:41.890657       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890979265Z"}
{"log":"E0127 21:37:41.890660       1 kubernetes_source.go:103] Event watch channel closed\n","stream":"stderr","time":"2016-01-27T21:37:41.890983167Z"}
```

**Comment by yujuhong** [comment] 2016-01-27 22:42
@piosz  @mwielgus, just in case that you haven't got the chance to look at the heapster failure, the log from the new eventer container is posted above.

**Comment by yujuhong** [comment] 2016-01-27 22:46
It's sad that the overzealous logging from one container manifested as high docker cpu usage, but don't have any better solution as of today. I'm closing this issue since the root cause has been identified and the PR has been reverted.

**Closed by yujuhong** 2016-01-27 22:46 UTC
Labels: dependency/docker, priority/P1, team/node

**Comment by piosz** [comment] 2016-01-28 06:23
@yujuhong thanks for the investigation.
