### ISSUE TITLE
kubectl validation fails for types enabled via --runtime-config

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21042] opened 2016-02-11 04:54 UTC
I enabled DaemonSet and Deployment via `--runtime-config`.  Trying to use them with `kubectl create`, I get 

```
error validating "./daemon_sets/daemon.yaml": error validating data: couldn't find type: v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false
```

I took a leap of faith and ran with --validate=false and it worked.

**Comment by bgrant0607** [comment] 2016-02-11 18:35
I think this is a known issue, but don't know if we have a solution on the horizon. All the APIs will be enabled by default in 1.2, so this may be moot in the short term.

cc @caesarxuchao @lavalamp @nikhiljindal 

It might make sense to convert this particular error to a warning, however.

cc @janetkuo

**Comment by lavalamp** [comment] 2016-02-11 18:43
@thockin what exactly did you do to --runtime-config?

@nikhiljindal Theories about why the client doesn't understand v1beta1.DaemonSet? Is the defaulting mechanism for --runtime-config somehow leaking into the client setup?

**Comment by thockin** [comment] 2016-02-12 01:31
`--runtime-config=extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true`

**Comment by nikhiljindal** [comment] 2016-02-12 22:16
The issue is that if kubectl has old swagger schema cached (without the new daemon sets and deployment resources), then it would not know that new APIs have been enabled on the server and hence it should refetch the schema.
kubectl will try to validate using old schema and hence that error.

Manually clearing `~/.kube/schema/` is a way to fix the issue.

**Comment by lavalamp** [comment] 2016-02-16 18:21
How long does it cache that for?

**Comment by janetkuo** [comment] 2016-02-17 00:37
#21353

**Comment by nikhiljindal** [comment] 2016-02-24 04:57
The caching problem is being tracked in https://github.com/kubernetes/kubernetes/issues/21353.
Closing this one

**Comment by lavalamp** [comment] 2016-02-24 17:35
Actually closing :)

**Closed by lavalamp** 2016-02-24 17:35 UTC
Labels: component/kubectl, priority/P2, team/CSI-API Machinery SIG, team/ux
