### ISSUE TITLE
integration flake: TestUnschedulableNodes has a panic

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#27290] opened 2016-06-13 18:22 UTC
```
W0613 14:15:54.827171    9637 reflector.go:334] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:393: watch of *api.Node ended with: too old resource version: 724 (731)
--- FAIL: TestUnschedulableNodes (0.15s)
panic: interface conversion: interface {} is nil, not *api.Node [recovered]
	panic: interface conversion: interface {} is nil, not *api.Node

goroutine 12895 [running]:
panic(0x239e4c0, 0xc827e8c680)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8285e46c0)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x239e4c0, 0xc827e8c680)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
k8s.io/kubernetes/test/integration.waitForReflection.func1(0x1d66b20, 0x0, 0x0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:112 +0x222
k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc826e77dc0, 0xc828bd33b8, 0xc827faef00, 0x0, 0x0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:210 +0x77
k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc826e77dc0, 0xc828bd33b8, 0x0, 0x0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:170 +0x8a
k8s.io/kubernetes/pkg/util/wait.Poll(0x5f5e100, 0x6fc23ac00, 0xc828bd33b8, 0x0, 0x0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:164 +0x4f
k8s.io/kubernetes/test/integration.waitForReflection(0xc8285e46c0, 0x7f24991d6498, 0xc827043840, 0x297dee0, 0x19, 0x2d27730, 0x0, 0x0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:108 +0xd7
k8s.io/kubernetes/test/integration.DoTestUnschedulableNodes.func1(0xc8285e46c0, 0xc827225900, 0x7f24991d6498, 0xc827043840, 0xc8286f7740)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:178 +0x249
k8s.io/kubernetes/test/integration.DoTestUnschedulableNodes(0xc8285e46c0, 0xc8286f7740, 0x7f24991d6498, 0xc827043840)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:242 +0xaf9
k8s.io/kubernetes/test/integration.TestUnschedulableNodes(0xc8285e46c0)
	/home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:84 +0x73e
testing.tRunner(0xc8285e46c0, 0x3a6baa8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	k8s.io/kubernetes/test/integration	218.503s
```

seen on https://github.com/kubernetes/kubernetes/pull/26806

**Comment by lavalamp** [comment] 2016-06-13 20:08
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/12997

**Comment by lavalamp** [comment] 2016-06-13 20:30
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/12998

**Comment by derekwaynecarr** [comment] 2016-06-13 20:41
FYI - I could only reproduce this flake when I run that integration test in isolation.

**Comment by lavalamp** [comment] 2016-06-13 20:44
Seems to be happening every time right now?

**Comment by Random-Liu** [comment] 2016-06-14 00:28
http://pr-test.k8s.io/27309/kubernetes-pull-test-unit-integration/30487/

**Comment by wojtek-t** [comment] 2016-06-14 10:10
Closing as duplicate of #27344 - the fix is already in flight.

**Closed by wojtek-t** 2016-06-14 10:10 UTC
Labels: kind/flake, priority/P0
