### ISSUE TITLE
ABtest

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#44234] opened 2017-04-08 09:37 UTC
kubernetes rolling update support abtest

**Comment by kargakis** [comment] 2017-04-08 11:38
@kubernetes/sig-apps-feature-requests

**Comment by kargakis** [comment] 2017-04-08 11:38
Will be possible once we have auto-pause: https://github.com/kubernetes/kubernetes/issues/11505

**Comment by kargakis** [comment] 2017-05-20 18:11
Closing as a dupe of #11505

**Closed by kargakis** 2017-05-20 18:11 UTC
Labels: area/workload-api/deployment, kind/enhancement, sig/apps
