### ISSUE TITLE
GKE upgrade e2e tests leaking target pools, forwarding rules, and firewall rules

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#13515] opened 2015-09-02 16:47 UTC
Our `kubernetes-upgrade-gce` Jenkins job has been broken for quite a while now, and it looks like it's due to target pools and/or forwarding rules leaking and exceeding quota:

```
Sep  2 00:48:45.094: INFO: event for mutability-service-test: {service-controller } creating loadbalancer: creating loadbalancer
Sep  2 00:48:45.094: INFO: event for mutability-service-test: {service-controller } creating loadbalancer failed: error creating load balancer (will retry): failed to create external load balancer for service e2e-tests-services-mrlvq/mutability-service-test: googleapi: Error 403: Quota 'TARGET_POOLS' exceeded.  Limit: 50.0
```

I've cleared out the old rules, and I'll try to diagnose what's leaking them and why.

**Comment by ihmccreery** [comment] 2015-09-02 16:50
This seems like it could be related to #13333, but I'm not sure.

**Comment by ihmccreery** [comment] 2015-10-13 21:42
As another note, it looks like every GKE upgrade run has leaked the following two firewall rules:

```
name                                    | allowed protocol/port           | target tags

gke-gke-upgrade-05b8f3f0-node-http-alt  | tcp:80,tcp:8080                 | gke-gke-upgrade-05b8f3f0-node,k8s-gke-upgrade-node
gke-gke-upgrade-05b8f3f0-node-nodeports | tcp:30000-32767,udp:30000-32767 | gke-gke-upgrade-05b8f3f0-node,k8s-gke-upgrade-node
```

**Comment by lavalamp** [comment] 2015-12-02 18:19
@davidopp to delegate? Is this still an issue?

**Comment by roberthbailey** [comment] 2016-01-07 18:10
@ihmccreery - Are we still seeing the firewalls being leaked?

**Comment by quinton-hoole** [comment] 2016-01-07 19:28
@roberthbailey I checked this out yesterday, and yes, we still seem to have a leak.  I've not root caused or fixed it yet, mind you.

**Comment by quinton-hoole** [comment] 2016-01-07 19:30
@roberthbailey I don't think that the leak is specific to GKE tests, mind you.  I see leaked firewall rules in other, non-GKE tests too.  When I have a moment, I'll try to fix all of them, as I assume that there is a single root cause.

**Comment by davidopp** [comment] 2016-01-22 19:02
ping @quinton-hoole

**Comment by quinton-hoole** [comment] 2016-01-22 19:51
@brendandburns kindly offered to take this over.  Re-assigning to him.

**Comment by quinton-hoole** [comment] 2016-01-22 22:07
We've confirmed that we do still appear to be leaking resources.  Here's an example of one that's 2 weeks old:

```
"kind": "compute#firewall", "selfLink": "projects/k8s-jkns-gce-upgrade/global/firewalls/k8s-fw-a050cd289b6e711e5bdfc42010af0000", "id": "1892727626468726683", "creationTimestamp": "2016-01-09T07:38:28.404-08:00", "name": "k8s-fw-a050cd289b6e711e5bdfc42010af0000",
```

**Comment by thockin** [comment] 2016-01-28 18:35
When we kube-down a cluster, how careful are we to tear down managed objects like LBs?  Where is that happening?

**Comment by roberthbailey** [comment] 2016-01-28 18:46
kube-down doesn't tear down any of the managed objects. Each e2e test is supposed to clean up after itself. I imagine that if a test gets stopped abruptly (e.g. it goes past the jenkins timeout and jenkins pulls the rug out from underneath it), then we are likely to leak managed objects that were being used in the test that was running. 

@cjcullen

**Comment by davidopp** [comment] 2016-02-02 22:06
@brendandburns what are the suggested next steps for this issue?

**Comment by roberthbailey** [comment] 2016-02-03 05:59
http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke/301/ failed with leaked firewall rules, forwarding rules, and target pools after the `Services should be able to change the type and nodeport settings of a service` test failed (which is probably related).

**Comment by brendandburns** [comment] 2016-02-04 17:23
I'm afraid that test run didn't have sufficient logging information to debug it properly.  I've filed a bug on the logs not repro-ing.  I'll leave this open, but its not actionable any further for now.

**Comment by brendandburns** [comment] 2016-02-09 00:41
My bet is that this was caused by the bug fixed in https://github.com/kubernetes/kubernetes/pull/20700

I'm closing until it re-occurs...

**Closed by brendandburns** 2016-02-09 00:41 UTC
Labels: area/test, davidopp, kind/flake, priority/P1, team/control-plane
