### ISSUE TITLE
use cephfs，Output: mount: wrong fs type, bad option, bad superblock

### ISSUE THREAD

**Issue by keith4743** [kubernetes/kubernetes#39227] opened 2016-12-26 05:59 UTC
OS version：CentOS7
Kube version：1.2
ceph version：0.94.9

I am testing use cephfs as the background storage , i followed this guide：
https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/cephfs/

 it can work when i mount cephfs in command line directly, but when i use it with a yaml configuration, there are some problems.

# here is my yaml config：

apiVersion: v1
kind: Pod
metadata:
  name: cephfs
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 172.60.0.64:6789
      user: admin
      secretFile: "/etc/ceph/admin.secret"

# kubectl describe pod cephfs

Name:		cephfs
Namespace:	default
Node:		node01.stg-k8s.com/172.50.0.44
Start Time:	Mon, 26 Dec 2016 13:30:53 +0800
Labels:		<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  cephfs-rw:
    Container ID:	
    Image:		kubernetes/pause
    Image ID:		
    Port:		
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  cephfs:
  <unknown>
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  2m		2m		1	{default-scheduler }				Normal		Scheduled	Successfully assigned cephfs to node01.stg-k8s.com
  2m		9s		13	{kubelet node01.stg-k8s.com}			Warning		FailedMount	Unable to mount volumes for pod "cephfs_default(77cc3f4d-cb2c-11e6-bc8a-fa163e08d256)": CephFS: mount failed: Mount failed: exit status 32
Mounting arguments: 172.60.0.64:6789:/ /var/lib/kubelet/pods/77cc3f4d-cb2c-11e6-bc8a-fa163e08d256/volumes/kubernetes.io~cephfs/cephfs ceph [name=admin,secretfile=/etc/ceph/admin.secret]
**Output: mount: wrong fs type, bad option, bad superblock** on 172.60.0.64:6789:/,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

  2m	9s	13	{kubelet node01.stg-k8s.com}		Warning	FailedSync	Error syncing pod, skipping: CephFS: mount failed: Mount failed: exit status 32
Mounting arguments: 172.60.0.64:6789:/ /var/lib/kubelet/pods/77cc3f4d-cb2c-11e6-bc8a-fa163e08d256/volumes/kubernetes.io~cephfs/cephfs ceph [name=admin,secretfile=/etc/ceph/admin.secret]
Output: mount: wrong fs type, bad option, bad superblock on 172.60.0.64:6789:/,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

# dmesg | tail
[435691.977001] XFS (dm-1): Mounting V4 Filesystem
[435692.002547] XFS (dm-1): Ending clean mount
[1562106.073276] XFS (dm-1): Mounting V4 Filesystem
[1562106.102422] XFS (dm-1): Ending clean mount
[1562106.259007] XFS (dm-1): Mounting V4 Filesystem

# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-33796071-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 284.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 1.34 GB
 Metadata Space Used: 716.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.34 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)

**Comment by resouer** [comment] 2016-12-26 06:41
cc @rootfs please take a look if you have time.

**Comment by resouer** [comment] 2016-12-26 14:50
According to offline talk, this is caused by wrong secret encoding. Close it.

**Closed by resouer** 2016-12-26 14:50 UTC
Labels: sig/storage

**Comment by jiuchongxiao** [comment] 2018-07-18 01:30
@resouer how to set the encoding

**Comment by jiuchongxiao** [comment] 2018-07-18 01:41
@KeithTt do you had solved it? how to solve the issue?
