### ISSUE TITLE
"master upgrade should maintain a functioning cluster" failing

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#103697] opened 2021-07-14 18:48 UTC
#### Which jobs are failing:

ci-kubernetes-e2e-gce-stable1-beta-upgrade-master

#### Which test(s) are failing:

"master upgrade should maintain a functioning cluster"

#### Since when has it been failing:

Since https://github.com/kubernetes/kubernetes/pull/99857 merged

On 2021-07-09, the extract step also started failing.

#### Testgrid link:

* https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-master&width=5&include-filter-by-regex=Upgrade
* https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-cluster-new&width=5&include-filter-by-regex=Upgrade

testgrid titles are misleading, these are upgrading from 1.21 to 1.22

#### Reason for failure:

Refactor broke ginkgo usage.

/assign @wojtek-t 
/cc @zshihang

**Comment by liggitt** [comment] 2021-07-14 18:50
current blocking failure is `Failed to set release from https://storage.googleapis.com/k8s-release-dev/ci/k8s-beta.txt (Unexpected HTTP status code: 404)`

**Comment by liggitt** [comment] 2021-07-14 18:51
that looks related to https://github.com/kubernetes/release/commit/908c08157f33de077426857280e2df4fbf63f60a

cc @spiffxp

**Comment by liggitt** [comment] 2021-07-14 19:00
for reference, the auth upgrade jobs which upgrade from ci/latest-1.20 to ci/latest are currently green and are upgrading from v1.20.9-rc.0.20+66e6d5ee1fa946 to v1.22.0-beta.1.157+e375563732a6f5

https://testgrid.k8s.io/sig-auth-gce#upgrade-tests

**Comment by wojtek-t** [comment] 2021-07-14 19:22
This is super strange.  From example failure:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-master/1413528078591725568

```
Kubernetes e2e suite: [sig-cloud-provider-gcp] Upgrade [Feature:Upgrade] master upgrade should maintain a functioning cluster [Feature:MasterUpgrade] expand_less | 7m25s
-- | --
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cloud/gcp/cluster_upgrade.go:57 You may only call BeforeEach from within a Describe, Context or When /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
```

So clearly, the problem is connected from calling `NewDefaultFramework`.

Now - this is the upgrade auth upgrade job looks:
```
33 var _ = SIGDescribe("ServiceAccount admission controller migration [Feature:BoundServiceAccountTokenVolume]", func() {
34	f := framework.NewDefaultFramework("serviceaccount-admission-controller-migration")
35	testFrameworks := upgrades.CreateUpgradeFrameworks(upgradeTests)
36
37	ginkgo.Describe("master upgrade", func() {
38		ginkgo.It("should maintain a functioning cluster", func() {
39 			upgCtx, err := common.GetUpgradeContext(f.ClientSet.Discovery())
                        ...
```

vs the failing cluster upgrade:
```
51 var _ = SIGDescribe("Upgrade [Feature:Upgrade]", func() {
52 	f := framework.NewDefaultFramework("cluster-upgrade")
53 	testFrameworks := upgrades.CreateUpgradeFrameworks(upgradeTests)
54 
55 	// Create the frameworks here because we can only create them
56	// in a "Describe".
57	ginkgo.Describe("master upgrade", func() {
58		ginkgo.It("should maintain a functioning cluster [Feature:MasterUpgrade]", func() {
59			upgCtx, err := common.GetUpgradeContext(f.ClientSet.Discovery())
                        ..
```

The literally look the same for me with one failing and the other passing. I will keep looking...

**Comment by wojtek-t** [comment] 2021-07-14 19:38
Ironically - the tests seem to actually be running, e.g. from the run above from logs:
```
...
I0709 16:06:37.901] [0m[sig-cloud-provider-gcp] Upgrade [Feature:Upgrade][0m [90mmaster upgrade[0m 
I0709 16:06:37.901]   [1mshould maintain a functioning cluster [Feature:MasterUpgrade][0m
I0709 16:06:37.901]   [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cloud/gcp/cluster_upgrade.go:57[0m
I0709 16:06:37.901] [BeforeEach] [sig-cloud-provider-gcp] Upgrade [Feature:Upgrade]
I0709 16:06:37.902]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
I0709 16:06:37.902] [1mSTEP[0m: Creating a kubernetes client
I0709 16:06:37.902] Jul  9 16:06:37.892: INFO: >>> kubeConfig: /workspace/.kube/config
I0709 16:06:37.902] [1mSTEP[0m: Building a namespace api object, basename cluster-upgrade
I0709 16:06:38.042] Jul  9 16:06:38.042: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
I0709 16:06:38.042] W0709 16:06:38.042033   10421 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
...
I0709 16:14:00.610] Jul  9 16:14:00.610: INFO: Checking control plane version
I0709 16:14:00.719] Jul  9 16:14:00.718: INFO: Control plane is at version 1.21.3-rc.0.10+5f8f5ab3268b41
I0709 16:14:00.719] [1mSTEP[0m: Disruption complete; stopping async validations
I0709 16:14:00.719] [1mSTEP[0m: Waiting for async validations to complete
I0709 16:14:00.719] [AfterEach] [sig-cloud-provider-gcp] Upgrade [Feature:Upgrade]
I0709 16:14:00.719]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
```

So it seems that the tests are actually running (and passing).
It's just at the end we have this strange error reported...

**Comment by spiffxp** [comment] 2021-07-15 06:22
>Failed to set release from https://storage.googleapis.com/k8s-release-dev/ci/k8s-beta.txt (Unexpected HTTP status code: 404)

I can't find a job that sets k8s-beta, so I will copy it, but it will be pointing to a stale build anyway:
```
$ gsutil cat gs://kubernetes-release-dev/ci/k8s-beta.txt
v1.21.3-rc.0.10+5f8f5ab3268b41
$ gsutil cat gs://kubernetes-release-dev/ci/latest-1.21.txt
v1.21.3-rc.0.26+f872796713459c
$ gsutil cat gs://k8s-release-dev/ci/latest-1.21.txt; echo
v1.21.3-rc.0.26+f872796713459c
$ gsutil cp gs://kubernetes-release-dev/ci/k8s-beta.txt gs://k8s-release-dev/ci
Copying gs://kubernetes-release-dev/ci/k8s-beta.txt [Content-Type=text/plain]...
/ [1 files][   31.0 B/   31.0 B]
Operation completed over 1 objects/31.0 B.
```

This is our usual fun dance of `k8s-beta` not meaning anything until a release branch gets cut, ref: https://github.com/kubernetes/sig-release/issues/850

**Comment by spiffxp** [comment] 2021-07-15 06:29
```
$ for m in latest latest-1.22 k8s-master; do echo $m: $(gsutil cat gs://k8s-release-dev/ci/$m.txt); done
latest: v1.22.0-beta.2.3+f5bc129a9916a1
latest-1.22: v1.22.0-beta.2.3+f5bc129a9916a1
k8s-master: v1.22.0-beta.2.3+f5bc129a9916a1
```

I forget exactly how this all plays with job rotation once release-branch jobs are cut.  I would personally be fine with moving away from the `k8s-foo` markers towards hardcoded numbers, but I would rather defer to @kubernetes/release-engineering 

/assign @cpanato @puerco @justaugustus

**Comment by spiffxp** [comment] 2021-07-15 06:32
It looks like https://github.com/kubernetes/test-infra/pull/22790 is what stopped writing `gs://kubernetes-release-dev/ci/k8s-beta.txt`

**Comment by spiffxp** [comment] 2021-07-15 06:39
> that looks related to [kubernetes/release@908c081](https://github.com/kubernetes/release/commit/908c08157f33de077426857280e2df4fbf63f60a)
> 
> cc @spiffxp

That wasn't it, but thanks for tagging me in.  The extract step failing on 2021-07-09 means it's either https://github.com/kubernetes/test-infra/pull/22840 or one of its followup PRs mentioned in https://github.com/kubernetes/k8s.io/issues/2318#issuecomment-878609309

**Comment by spiffxp** [comment] 2021-07-15 07:42
https://github.com/kubernetes/kubernetes/pull/99857#discussion_r670214091 maybe this is the culprit for the first problem?

**Comment by wojtek-t** [comment] 2021-07-15 07:49
See https://github.com/kubernetes/kubernetes/issues/103697#issuecomment-880148377 above [that change was reverted in one of subsequent PRs]

**Comment by wojtek-t** [comment] 2021-07-15 07:50
Namely - this one: https://github.com/kubernetes/kubernetes/pull/101118

**Comment by wojtek-t** [comment] 2021-07-15 08:08
I guess I know what's happening - https://github.com/kubernetes/kubernetes/pull/101118 has to be cherrypicked back to 1.21.
Will open a cherrypick later today [need to run now.]

**Comment by wojtek-t** [comment] 2021-07-15 11:10
@liggitt - https://github.com/kubernetes/kubernetes/pull/103712 is out for review

**Comment by liggitt** [comment] 2021-07-15 14:51
> I can't find a job that sets k8s-beta, so I will copy it, but it will be pointing to a stale build anyway

Thanks, latest run passed the extract step and we're back to the ginkgo describe error. That should be fixed by #103712.

Once https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt updates to v1.21.3-rc.0.27+4aa451e8458a7c, can you push that to `k8s-beta.txt` as a stop gap while we figure out whether we should start pushing k8s-beta from CI again or update the job config?

**Comment by neolit123** [comment] 2021-07-15 15:10
Just wanted to note that for the kubeadm upgrade jobs we stopped testing
against stable and instead we test against the tips of release branches or
master. This allows us to also catch problems in backports before a patch
release is made.

To do that we have use the latest and latest-foo markers. The foo
calculations are currently in the tooling, since there are no latest-1
markers (ala stable1).

**Comment by liggitt** [comment] 2021-07-15 15:13
it looks like the `ci/k8s-stable1.txt` marker has the HEAD build for the most recent released minor version branch... isn't that what you want?

**Comment by neolit123** [comment] 2021-07-15 15:24
I guess it would. I may have been mislead by the 'stable' in the name. In practice the tooling can now do these calculations and its easy to say 'this upgrade job does latest-1 to latest upgrades', but one still needs to PR test infra. And IIRC the original intent of the *stable markers was mainly to not PR test infra on each release.

**Comment by liggitt** [comment] 2021-07-15 15:31
looks like CI build v1.21.3-rc.0.28+4aa451e8458a7c is available now

**Comment by spiffxp** [comment] 2021-07-15 15:31
> can you push that to k8s-beta.txt as a stop gap while we figure out whether we should start pushing k8s-beta from CI again or update the job config?

Done
```
$ gsutil cat gs://k8s-release-dev/ci/latest-1.21.txt; echo
v1.21.3-rc.0.28+4aa451e8458a7c
$ gsutil cp gs://k8s-release-dev/ci/latest-1.21.txt gs://k8s-release-dev/ci/k8s-beta.txt
Copying gs://k8s-release-dev/ci/latest-1.21.txt [Content-Type=text/plain]...
/ [1 files][   30.0 B/   30.0 B]
Operation completed over 1 objects/30.0 B.
```

**Comment by liggitt** [comment] 2021-07-15 15:31
awesome, thanks

**Comment by spiffxp** [comment] 2021-07-15 15:40
>And IIRC the original intent of the *stable markers was mainly to not PR test infra on each release.

If we're going to make a decision on what we think version markers should look like, that's what https://github.com/kubernetes/sig-release/issues/850 is for.  IMO the contributor clarity gained by hardcoding version numbers would far outweigh the toil of updating them every N months.

**Comment by neolit123** [comment] 2021-07-15 16:31
> IMO the contributor clarity gained by hardcoding version numbers would far outweigh the toil of updating them every N months.

I agree since some markers have been a bit cryptic. Tooling can help with the regular updates too.

**Comment by spiffxp** [comment] 2021-07-16 00:31
/assign
keeping an eye on the latest runs

**Comment by wojtek-t** [comment] 2021-07-16 05:48
OK - so cluster upgrade tests become green again after the change:
https://testgrid.k8s.io/google-gce-upgrade#gce-1.13-1.14-upgrade-cluster&width=25

But it seems that master upgrade is panicing (I don't know how it worked for me before). It's a type - going to send out fix soon.

**Comment by wojtek-t** [comment] 2021-07-16 05:54
fix in master branch: #103733
cherrypick to 1.21: #103734

**Comment by liggitt** [comment] 2021-07-16 13:58
https://github.com/kubernetes/kubernetes/pull/103734 is merged, should resolve the last failure

as long as the job points to ci/k8s-beta.txt, I guess we'll need one more bump once https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt updates to v1.21.4-rc.0.3+0e1bd6ab564...

**Comment by liggitt** [comment] 2021-07-16 14:26
also opened https://github.com/kubernetes/test-infra/pull/22915 to fix up the testgrid tab names and make these tests use ci/latest instead of ci/k8s-beta (happy to re-rework that if k8s-beta starts being automatically populated again)

**Comment by liggitt** [comment] 2021-07-16 15:20
> I guess we'll need one more bump of that file once https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt updates to v1.21.4-rc.0.3+0e1bd6ab564...

looks like it's ready now

**Comment by spiffxp** [comment] 2021-07-16 18:03
I got pulled away from keyboard, I'll sync shortly though the test-infra PR will probably obviate

**Comment by spiffxp** [comment] 2021-07-16 18:11
```
$ gsutil cp gs://kubernetes-release-dev/ci/k8s-beta.txt gs://k8s-release-dev/ci/
Copying gs://kubernetes-release-dev/ci/k8s-beta.txt [Content-Type=text/plain]...
/ [1 files][   31.0 B/   31.0 B]
Operation completed over 1 objects/31.0 B
```

**Comment by wojtek-t** [comment] 2021-07-21 12:29
OK - so the upgrade itself works now.

However, there are gazilions of storage tests that started failing after Jordan upgraded to use latest.

@liggitt - should we close this one and open a separate bug for the failing storage tests?

**Comment by liggitt** [comment] 2021-07-21 13:34
> @liggitt - should we close this one and open a separate bug for the failing storage tests?

probably so

**Comment by wojtek-t** [comment] 2021-07-21 13:37
Opened https://github.com/kubernetes/kubernetes/issues/103822

Closing this one as resolved.

**Closed by wojtek-t** 2021-07-21 13:37 UTC
Labels: kind/failing-test, priority/important-soon, sig/testing, triage/accepted
