### ISSUE TITLE
Add transient archive volume type that stores arbitrarily complex file structure

### ISSUE THREAD

**Issue by huhlig** [kubernetes/kubernetes#24044] opened 2016-04-08 14:58 UTC
Used for cases where pre-initialized data of arbitrary type can be provided to a pod. Similar use case to ([#13610](https://github.com/kubernetes/kubernetes/issues/13610)) however expanded to support arbitrarily complex structures.
1. Archive Format support for tar, zip or other archive format (preferably with compression/encryption).
2. Extracted to host or memdisk prior to container execution and and linked similar to emptyDir.
3. Contents while Mutable are lost upon pod termination.
4. Archive location could be from local file, http, or other compatible endpoint.

Use Cases:
1. Providing larger configuration/reference files of any format such as SQLite configuration databases.
2. Providing complex pre-configured file structures such as static websites with images.

This would likely require ([#13606](https://github.com/kubernetes/kubernetes/issues/13606))

**Comment by vishh** [comment] 2016-04-08 18:32
#831 is closely related. 
cc @bgrant0607 who has been talking about supporting volumes that are initialized by special volume containers which can then be consumed by pods.

**Comment by bgrant0607** [comment] 2016-04-09 04:19
Yes, this is a dupe of #831.

**Closed by bgrant0607** 2016-04-09 04:19 UTC
Labels: kind/feature, team/cluster
