### ISSUE TITLE
How to add node'role on kubelet v1.16.2 

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/kubernetes#85503] opened 2019-11-21 08:27 UTC
**What happened**:
Hello, I install the kubernetes with v1.16.2, but I found I cannot configure the node's role in the kubelet's parameter.  The follows is what I config on v1.14.3, but it got error on v1.16.2
```shell
--node-labels=node.kubernetes.io/master=true
```
The error log is as follows:
```shell
Nov 21 16:07:47 master2 kubelet[16849]: F1121 16:07:47.424623   16849 server.go:185] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/master]
Nov 21 16:07:47 master2 kubelet[16849]: --node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)
```

**What you expected to happen**:
I try run `kubectl label node`, and it can add role for node, but I wonder is there any method to add the role automatically? Why cancal this function?
**How to reproduce it (as minimally and precisely as possible)**:
add `--node-labels=node.kubernetes.io/master=true` to the `kubelet`'s start param, then restart `kubelet`.

**Comment by liggitt** [comment] 2019-11-22 07:29
This is a duplicate of #84912 

See https://github.com/kubernetes/kubernetes/issues/84912#issuecomment-551362981 and the referenced design for the reasons it is not desireable for kubelets to self-select their roles, and for alternatives for labeling nodes.

**Closed by liggitt** 2019-11-22 07:29 UTC
Labels: kind/bug, sig/api-machinery, sig/cli, sig/node, sig/release
