### ISSUE TITLE
Pod status not reported promptly in integration test (potentially due to watch delay)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#6651] opened 2015-04-09 20:12 UTC
Probably not the same as #6261?

```
E0409 20:06:54.436466   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:06:57.231617   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:00.441072   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:03.830751   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:06.631939   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:08.999560   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:12.642264   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:15.431503   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:18.831765   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:21.036332   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:24.233363   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:27.660547   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:30.518706   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:33.000798   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:36.464078   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:39.449110   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:42.014692   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:45.637593   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:48.437592   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:51.240095   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:54.632542   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:07:57.430374   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:00.632996   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:03.041408   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:06.656540   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:09.841615   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:12.260723   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:15.634119   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:18.637260   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:21.254251   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:24.433427   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:27.639387   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
E0409 20:08:30.647808   32568 kubelet.go:1341] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists
I0409 20:08:32.367981   32568 integration.go:391] pod found: default/container-vm-guestbook-manifest-127
I0409 20:08:32.368364   32568 integration.go:391] pod found: default/container-vm-guestbook-pod-spec-localhost
I0409 20:08:32.368544   32568 integration.go:391] pod found: default/foo
I0409 20:08:32.368665   32568 integration.go:391] pod found: default/static-pod-from-spec-localhost
F0409 20:08:32.368827   32568 integration.go:394] static-pod-from-spec FAILED: mirror pod has not been created or is not running: timed out waiting for the condition
```

To @yujuhong for triage

**Comment by dchen1107** [comment] 2015-04-09 20:15
Shouldn't this fixed by #6580?

**Comment by yujuhong** [comment] 2015-04-09 21:18
@dchen1107, this has nothing to do with #6580. kubelet is trying to create the mirror pod over and over again because it still hasn't observed the mirror pod from watch. It is probably the same as # #6261.

**Comment by lavalamp** [comment] 2015-04-09 21:22
I thought they might be different because this one has a bunch of "failed creating ... already exists" messages in it, but #6261 doesn't.

**Comment by yujuhong** [comment] 2015-04-09 21:30
It is essentially the same problem -- the watch was delayed so kubelet kept seeing the old snapshot of the pods where the mirror didn't exist.  That's why it's flaky and only happens on shippable (which I suspect has poorer performance) :(

This becomes worse every time a new test is added. I think we need to limit the number of concurrent tests in integration.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L981

**Comment by yujuhong** [comment] 2015-04-10 00:32
#6655 limits the number of concurrent tests on travis/shippable to 4. Let's see if this helps reduce the timeout flakes.

**Comment by lavalamp** [comment] 2015-04-10 18:47
Another example: https://app.shippable.com/builds/55275c45aa50c00b001ed2d9

**Comment by yujuhong** [comment] 2015-04-10 23:33
Here is yet another example: https://app.shippable.com/builds/5528571f892aba0c00bd674c

Retitled the issue since limiting the concurrent tests doesn't work. It could be that the server is heavily loaded and the test timed out, or there was a delay/drop in kubelet's pod watch stream.

**Comment by dchen1107** [comment] 2015-04-13 18:18
Now example: https://app.shippable.com/builds/552c02f56206490c0097314d

**Comment by yujuhong** [comment] 2015-04-14 19:17
If, for whatever reason, a watch update for pod creation is dropped, kubelet would need to wait until re-listing to notice that. This would certainly cause the test to time out. @lavalamp, would it be useful to shorten the re-listing interval for tests like this?

**Comment by lavalamp** [comment] 2015-04-14 20:44
I am not quite sure how this works--let's chat about it tomorrow?

**Comment by yujuhong** [comment] 2015-04-16 22:02
From [this failulre](https://app.shippable.com/builds/5530131d31d6ed0c0026fd2c), we can see that kubelet was lightly loaded as the update channel was mostly empty while waiting.
```
I0416 20:47:36.975546    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:37.976479    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:38.977073    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:39.978154    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:40.111029    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:40.978537    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:41.978930    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:42.724643    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:42.979593    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:43.980301    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:44.981798    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:45.982255    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
I0416 20:47:46.982765    2903 config.go:186] 0/50 updates in the channel; merge finished in 0.00 seconds.
F0416 20:47:47.207091    2903 integration.go:914] FAILED: pod never started running timed out waiting for the condition
``` 
 This corroborates the theory that watch might be at fault.

**Comment by quinton-hoole** [comment] 2015-04-16 22:10
cc: quinton-hoole

**Comment by yujuhong** [comment] 2015-04-16 23:14
The WIP reflector benchmark (#6697) may shed some light on this issue once it's integrated with the continuous e2e performance suite.

I will keep this issue open for now to gather more data (since this is not reproducible locally at all), and to see if there are other potential causes.

**Comment by yujuhong** [comment] 2015-05-11 23:19
The PR above disables the static pod test temporarily so that we can track down the root cause without spamming people with the failures. Note that other tests in the same file (integration.go) may still trigger the flaky failure, though less frequently.

**Comment by quinton-hoole** [comment] 2015-06-15 21:25
@yujuhong Can this be closed yet?

**Comment by yujuhong** [comment] 2015-06-18 21:54
> @yujuhong Can this be closed yet?

No, integration test is still flaky. See https://app.shippable.com/builds/5582458f3d07800f00077736 for example.

Many tests in cmd/intergration/intergration.go rely on checking the pod status with a preset timeout. I disabled one test which failed most often, but other tests still fail from time to time.

**Comment by yujuhong** [comment] 2016-02-09 01:33
The issue has been inactive for months, and there have not been any new reports. Closing.

**Closed by yujuhong** 2016-02-09 01:33 UTC
Labels: area/test, priority/P1, team/node
