### ISSUE TITLE
Improve test coverage on code generator

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#119289] opened 2023-07-13 13:47 UTC
The commands under https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator/cmd 
will benefit of a batter unit test coverage as seen in 

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/pull/119268#discussion_r1261752502_

**Comment by biswajit-9776** [comment] 2023-07-16 12:12
Hi @aojea, I would like to work on this issue. Could you tell me how many test files are needed per PR under this issue?

**Comment by DamianSawicki** [comment] 2023-07-17 08:54
Hi @biswajit-9776, the issue is already assigned to me. Would you consider contributing to other issues to avoid duplication?

**Comment by biswajit-9776** [comment] 2023-07-17 10:52
Hi @DamianSawicki, do you mind if I work on this issue along with you? I would only like to write tests on limited number of files, if that's okay with you...

**Comment by DamianSawicki** [comment] 2023-08-18 09:36
Hi @biswajit-9776, thanks for your engagement! If you also want to work on this particular issue, we should coordinate. Are you working on something other than `k8s.io/code-generator/cmd/lister-gen/generators/expansion.go`?

**Comment by biswajit-9776** [comment] 2023-08-20 06:57
Hey @DamianSawicki, currently I'm thinking of shifting to k8s.io/code-generator/cmd/informer-gen. Do let me know if you are already working on that particular directory. Also I could assist you in any of your work on this issue as I'm not preoccupied at the moment.

**Closed** 2023-09-29 16:10 UTC
Labels: sig/api-machinery, triage/accepted
