### ISSUE TITLE
kube-controller-manager Error unable to monitor quota for resource "networkpolicies"

### ISSUE THREAD

**Issue by jicki** [kubernetes/kubernetes#72091] opened 2018-12-17 01:40 UTC
version : 1.13.1

```
Dec 17 09:36:09 kubernetes-1 kube-controller-manager: E1217 09:36:09.170202   12921 resource_quota_controller.go:437] failed to sync resource monitors: couldn't start monitor for resource "extensions/v1beta1, Resource=networkpolicies": unable to monitor quota for resource "extensions/v1beta1, Resource=networkpolicies"
Dec 17 09:36:09 kubernetes-1 kube-controller-manager: W1217 09:36:09.176387   12921 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="kubernetes-1" does not exist
Dec 17 09:36:09 kubernetes-1 kube-controller-manager: W1217 09:36:09.176502   12921 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="kubernetes-2" does not exist
Dec 17 09:36:09 kubernetes-1 kube-controller-manager: W1217 09:36:09.176510   12921 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="kubernetes-3" does not exist


```

**Comment by Pingan2017** [comment] 2018-12-17 03:56
Duplicate of #69562

**Comment by Shnatsel** [comment] 2019-01-21 17:06
@jicki if this is indeed a duplicate, please close this issue and continue the discussion in #69562

**Closed** 2019-06-27 20:56 UTC
Labels: lifecycle/rotten, needs-sig
