### ISSUE TITLE
PR unit test run tries to grab wrong branch

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#30691] opened 2016-08-16 16:42 UTC
E.g.

```
GitHub pull request #25921 of commit 7469e31b6e2f884b0e78b6d612dfc45938e8d3cb, no merge conflicts.
[...]
Seen 55 remote branches
Checking out Revision 785feb748883b0ae2b939157f05f30c9ea2b92b3 (origin/pr/30686/merge)
[...]
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 785feb748883b0ae2b939157f05f30c9ea2b92b3" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 785feb748883b0ae2b939157f05f30c9ea2b92b3

```

**Comment by mml** [comment] 2016-08-16 17:17
@rmmh this happened again.

**Comment by rmmh** [comment] 2016-08-22 21:18
This flake is unfortunately a known issue with the Jenkins Github Pull Request Builder. We're moving off it ASAP.

**Comment by spxtr** [comment] 2016-08-22 21:26
closing as a dupe of #27462

I'm working on it but it won't be fixed right away, sorry.

**Closed by spxtr** 2016-08-22 21:26 UTC
Labels: priority/P1, team/test-infra
