### ISSUE TITLE
GCE: Dashboard add-on has no permissions by default

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#54810] opened 2017-10-30 19:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When you start up a v1.8.2 cluster on GCE with the default `kube-up.sh` script, the dashboard add-on is installed by default, but it uses the `kube-system:default` service account, which has no permissions.

This leads to errors like the following when you load the dashboard:

```
configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "default"
```

**What you expected to happen**:

Any of:

1. Dashboard should be given sufficient permissions as part of default cluster startup.
2. User should be given instructions to complete dashboard add-on setup by granting permissions after cluster startup.
3. Dashboard add-on should not be enabled by default with an incomplete configuration.

**How to reproduce it (as minimally and precisely as possible)**:

Download v1.8.2 archive.

```shell
cluster/get-kube-binaries.sh
cluster/kube-up.sh
kubectl proxy
```

Open http://localhost:8001/ui

**Anything else we need to know?**:

As explained on https://github.com/kubernetes/dashboard/issues/1800, fixing this is not in the scope of the dashboard project itself. The dashboard works fine once you complete the setup process by granting the necessary permissions. The problem is that the default `kube-up.sh` script leaves you with an incomplete setup.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: `cluster/kube-up.sh`
- Others:

**Comment by ahmetb** [comment] 2017-10-30 20:21
Possibly a duplicate of #39722.

**Comment by enisoc** [comment] 2017-10-30 21:01
@ahmetb Thanks. This issue was indeed mentioned at the end of that thread, although most of that thread is about a separate issue. Can we consolidate here for the new issue?

Something helpful linked from that thread is the example of how this was fixed for heapster:

https://github.com/kubernetes/kubernetes/pull/46750/files

**Comment by liggitt** [comment] 2017-10-31 03:52
the version of the dashboard currently deployed via kube-up exposes those permissions to anyone able to access the dashboard's IP, so default permissions are not really appropriate on a secured system.

https://github.com/kubernetes/kubernetes/pull/53046 is open to update the dashboard to a version that requires users to authenticate using their own credentials

**Comment by enisoc** [comment] 2017-10-31 23:30
@liggitt Do you know if they plan to cherrypick the dashboard version bump to 1.8.x?

If not, we should print some link at the end of kube-up.sh to a page that explains, "There's no secure way to run dashboard versions <1.7.x. If you want to enable it at your own risk, do this."

**Comment by liggitt** [comment] 2018-01-15 03:38
Fixed in https://github.com/kubernetes/kubernetes/pull/53046

/close

**Closed by liggitt** 2018-01-15 03:38 UTC
Labels: kind/bug, sig/gcp
