### ISSUE TITLE
Allow `kubectl port-forward` to use "services"

### ISSUE THREAD

**Issue by akram** [kubernetes/kubernetes#43570] opened 2017-03-23 13:55 UTC
`kubectl port-forward` should give the ability to forward trafic to a service not only a pod.

This is convenient for developer/debugging purposes and especially for non HTTP/SNI protocols that cannot use routes and that we don't want to expose through nodePort.

Implementation could be done using the /proxy url to send trafic to the service, and netcat/socat to handle it through a local port.

It may require to add an additional flag --service=service-name or use the svc/<svc_name> syntax

**Comment by liggitt** [comment] 2017-03-23 16:54
@kubernetes/sig-cli-feature-requests

**Comment by shahidhk** [comment] 2017-05-07 12:11
Duplicate of #15180

**Closed** 2017-05-07 18:35 UTC
Labels: kind/feature, sig/cli
