### ISSUE TITLE
Wrong release version

### ISSUE THREAD

**Issue by fanux** [kubernetes/kubernetes#87354] opened 2020-01-18 11:16 UTC
release pages kubelet version is wrong.

wget https://dl.k8s.io/v1.16.5/kubernetes-server-linux-amd64.tar.gz

```
 ./kubelet --version
Kubernetes v1.16.6-beta.0
```
kubelet version should be v1.16.5 not v1.16.6-beta.0

v1.15.8 also wrong

apiserver and other bin files too.

**Comment by liggitt** [comment] 2020-01-18 15:04
Thanks for the report. This is a duplicate of https://github.com/kubernetes/release/issues/1020 and new corrected releases are in progress. See https://groups.google.com/g/kubernetes-sig-release/c/7TFJWFucLUU/m/0AQsBNryCwAJ for details.

/close

**Closed by liggitt** 2020-01-18 15:04 UTC
Labels: kind/bug, sig/release
