### ISSUE TITLE
Failing job: ci-kubernetes-e2e-gci-gce-scalability / Failure cluster [7730c0d0...]

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103624] opened 2021-07-09 22:10 UTC
##### Error text:
```
error during /home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-1-21-1413377583168360448 --nodes=100 --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/use_simple_latency_query.yaml --testoverrides=./testing/overrides/load_throughput.yaml: exit status 1
```
#### Recent failures:
[7/9/2021, 4:15:21 AM ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413456354412072960)
[7/9/2021, 3:44:10 AM ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413448552457179136)
[7/9/2021, 3:13:16 AM ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413440750963658752)
[7/9/2021, 2:42:12 AM ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413432949348503552)
[7/9/2021, 2:11:18 AM ci-kubernetes-e2e-gci-gce-scalability](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413425150098935808)

/kind failing-test

/sig scalability

Appears to have started failing on 07/08.

**Comment by marseel** [comment] 2021-07-12 09:00
It's duplicate of #103606
All scalability tests were affected by this issue. 
/close

**Closed** 2021-07-12 09:00 UTC
Labels: kind/failing-test, needs-triage, sig/scalability
