### ISSUE TITLE
Various Bazel problems - Mac, assumptions about paths, etc

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#35359] opened 2016-10-22 06:03 UTC
On OSX El Capitan

```
$ bazel test  //pkg/...
ERROR: /Users/clayton/projects/origin/src/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/storage/unversioned/BUILD:13:1: every rule of type go_library implicitly depends upon the target '//:go_prefix', but this target could not be found because of: no such package '': BUILD file not found on package path.
ERROR: Analysis of target '//pkg/client/clientset_generated/internalclientset/typed/storage/unversioned:go_default_library' failed; build aborted.
INFO: Elapsed time: 0.115s
ERROR: Couldn't start the build. Unable to run tests.
```

Docs didn't seem to cover when this happens?

**Comment by smarterclayton** [comment] 2016-10-22 06:05
```
release: release 0.3.2-homebrew
```

**Comment by mikedanese** [comment] 2016-10-22 07:31
Hmm, will take a look. I have only tested on linux amd64 so far.

**Comment by mikedanese** [comment] 2016-10-22 08:01
This is caused by having both a build/ directory and a BUILD file in the root of the repository and make fs being case insensitive. cc @ixdy @spxtr

**Comment by spxtr** [comment] 2016-10-22 08:35
Ahh, case-insensitive filesystem bugs. Looks like we have two obvious options:

1. Don't support native builds on mac. Run it in docker.
1. Rename all `build/` folders to something else.

I'm happy with either solution, but remember @thockin's [words](https://github.com/kubernetes/kubernetes/issues/30600#issuecomment-241160172): "Please don't make Linux builds suck just because Mac builds have to suck."

**Comment by ixdy** [comment] 2016-10-22 19:38
Well, that is terrible.

Option 1 doesn't fix the issue - git is just going to fail to check out `build/` and `BUILD` on macOS.

Probably the only thing we can do is rename `build/` to something else, but that's going to break everyone who calls into `build/` directly instead of using `make`.

We need to do something soon, since this probably breaks all macOS development.

**Comment by mikedanese** [comment] 2016-10-22 19:49
https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node/ also has a BUILD and a build/

**Comment by smarterclayton** [comment] 2016-10-22 20:12
GitHub keeps time delaying / eating my emails, which drives me up the wall.

Was going to say you can make case sensitive FS on Mac fairly easily so that's not a real blocker (just annoying).  I'm willing to annoy Mac developers a slight bit because case sensitivity is so 1980.

**Comment by smarterclayton** [comment] 2016-10-22 20:12
We would definitely need to warn and error at the appropriate points.

**Comment by smarterclayton** [comment] 2016-10-22 20:32
Ok, so set up a case sensitive Mac FS partition and now my only failures are the GOOS problems.

Would recommend that we doc / warn users that they need Kubernetes to be on a case sensitive FS from now on, and steps for Mac are:

1. Create a new, case-sensitive Mac partition
  a. Free up space on your disk by using Disk Utility to shrink an existing partition (backup before hand)
  b. Create a new partition using the "OS X Extended (case-sensitive, journaled)" option
 2. Move your entire GOPATH or a parent dir over to that partition
 3. Symlink your old location to the new partition

NTFS I thought was case sensitive by default but doesn't apply for Bazel for now.  I know a few people who do Kubectl dev on Windows, but not often.  We may split kubectl anyway.

Honestly this is just one more argument that kube-proxy and kubelet don't belong in the core codebase, or kubectl doesn't, or the apiserver doesn't.  And even the linux bias of the Kubelet is just a detail today, because it can and will be multiplatform eventually.

**Comment by smarterclayton** [comment] 2016-10-22 20:32
```
bazel does not currently work properly from paths containing spaces (/Volumes/Case Sensitive HD/projects/origin/src/k8s.io/kubernetes).
```

Sigh.

**Comment by smarterclayton** [comment] 2016-10-22 20:36
Got a bit further:

```
bazel test  //pkg/...
........
INFO: Found 621 targets and 352 test targets...
ERROR: /Volumes/development/projects/origin/src/k8s.io/kubernetes/vendor/BUILD:727:1: null failed: bolt.a.GoCompileFile.params failed: error executing command bazel-out/local-fastbuild/bin/vendor/bazel-out/local-fastbuild/bin/vendor/github.com/boltdb/bolt.a.GoCompileFile.params: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
k8s.io/kubernetes/vendor/github.com/boltdb/bolt/bolt_linux.go:9: undefined: syscall.Fdatasync
INFO: Elapsed time: 38.586s, Critical Path: 2.34s
//pkg/admission:go_default_test                                       NO STATUS
```

which is just the GOOS problem.  How will Bazel handle build platform tags?

**Comment by smarterclayton** [comment] 2016-10-22 20:37
Seeing this

```
INFO: From Linking vendor/github.com/docker/docker/pkg/term_cgo.cgo.dir/gen/lib_cgo_lib.lo:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: bazel-out/local-fastbuild/bin/vendor/_objs/github.com/docker/docker/pkg/term_cgo.cgo.dir/gen/_cgo_lib/vendor/github.com/docker/docker/pkg/term_cgo.cgo.dir/gen/_cgo_export.pic.o has no symbols
```

which is a more complex thing - CGO vs not (we can't force kubectl to be compiled with CGO on all distros).

**Comment by smarterclayton** [comment] 2016-10-22 20:38
```
//pkg/kubectl/resource:go_default_test                                   FAILED in 0.1s
  /private/var/tmp/_bazel_clayton/5d0ba53608021b87fa9bd88a3bdcf100/execroot/kubernetes/bazel-out/local-fastbuild/testlogs/pkg/kubectl/resource/go_default_test/test.log

Executed 7 out of 7 tests: 6 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
○ cat /private/var/tmp/_bazel_clayton/5d0ba53608021b87fa9bd88a3bdcf100/execroot/kubernetes/bazel-out/local-fastbuild/testlogs/pkg/kubectl/resource/go_default_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
--- FAIL: TestHasNames (0.00s)
	builder_test.go:1231: expected HasName to error there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'resource.test get resource/<resource_name>' instead of 'resource.test get resource resource/<resource_name>', got there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'go_default_test get resource/<resource_name>' instead of 'go_default_test get resource resource/<resource_name>'
FAIL
```

The test fails because it depends on the binary name - go builds the binary with `<package>.test` but BAZEL builds differently (go_default_test).  That seems incorrect?

**Comment by mikedanese** [comment] 2016-10-22 21:03
p0 is to get mac workflow unbroken without using bazel. p1 is to get bazel workflow building on mac. I think documenting the filesystem requirements plus https://github.com/kubernetes/kubernetes/pull/35376 get us p0.

**Comment by mikedanese** [comment] 2016-10-22 21:07
Thanks for digging into this.

> The test fails because it depends on the binary name - go builds the binary with <package>.test but BAZEL builds differently (go_default_test). That seems incorrect?

Or is this just a bad assumption by the test?

> which is just the GOOS problem. How will Bazel handle build platform tags?

Bazel supports [selecting](https://www.bazel.io/versions/master/docs/be/functions.html#select) on target os and cpu arch. The edits could be made by hand now but it would probably be better to add this to gazel (build file automanager).

> which is a more complex thing - CGO vs not (we can't force kubectl to be compiled with CGO on all distros).

Yes, CGO and linkopts are something that needs to be sorted.

**Comment by smarterclayton** [comment] 2016-10-22 21:23
>> The test fails because it depends on the binary name - go builds the binary with .test but BAZEL builds differently (go_default_test). That seems incorrect?
> Or is this just a bad assumption by the test?

This test, probably.  In general, maybe not.  If I want to profile / benchmark a Go folder, I probably run `go test` outside of bazel (nothing we're doing here breaks normal Go, right?).  

This raises a point of whether bazel is taking over Go's responsibilities, or just augmenting them.  I think your point you raised about auto generation before is interesting, because I would expect the BUILD files to *stay* auto generated as much as possible, and have the non-autogenerated parts be special cases (api, generation, go-generate style things).  If we are just supplementing Go, that allows other downstream packages to continue to consume Kube libraries.  If we force every downstream consumer of Kubernetes to consume bazel, that's a bigger change.

Example - if we split kubectl, it'll still need to reuse a fair amount of core kube code (pkg/util, pkg/api, etc).  I assume it could also be bazel (not sure about the poor windows developers there, we can come back to them) for the most part.  But if other people want to spawn things off kubectl - do they also have to use bazel?

Second example - we're working heavily right now to make apiserver code reusable so that people can build extension ecosystem API projects that loosely couple to Kube.  Those are heavy consumers of generation code (@ncdc ex just asked this recently) so I think they'd want to reuse as much as possible of the infra, which means reusing bazel.

Third example - extension controllers.  They'll mostly reuse client-go as a Go library, so they probably don't want to depend on Bazel.

Fourth example - OpenShift and other Kube distributions (Apcera, Tectonic, etc).  Long term we really want OpenShift to be kube core + patches + admission controllers + extension servers (second example).  If we can solve the "can bazel be used in the ecosystem distro chain" question, then we're more likely to adopt bazel.  If we can't solve that question, we'll at least want the code generation bits and the consumption bits to work well when consumed from the outside, so I would still expect the go packages themselves to correctly compile.

So kind of speaks to the question of whether we can make gazel handle the "exactly map to Go rules auto generation" case, but still have a way to customize without then having to turn off auto generation.

**Comment by jbeda** [comment] 2016-10-22 22:28
I just hit this on my mac.  What fun!

While creating a case sensitive file system is doable on the mac, I think that it is a very very high bar to require a new filesystem to even *sync* the repo on to a mac successfully.  This is really just going to ask for trouble.

Is there any way to change the name that bazel uses?  `BUILD` is pretty generic and we aren't going to be the only ones hitting this.  If bazel is ever going to work on the mac on converted code bases they'll have to figure this out.

**Comment by jbeda** [comment] 2016-10-22 22:33
Can we revert the change to at least get things going until we figure this out?

**Comment by mikedanese** [comment] 2016-10-22 22:42
@jbeda how does this affect the old style build?

**Comment by jbeda** [comment] 2016-10-22 22:42
Looks like bazel doesn't support alternate file names but it might be actively worked on.  See https://github.com/bazelbuild/bazel/issues/552.  

I propose we roll this back until that lands.

**Comment by jbeda** [comment] 2016-10-22 22:44
@mikedanese -- you can't even clone the repo on to a mac right now.

<details>
```
$  git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$  git reset --hard upstream/master
HEAD is now at 081ee2d Merge pull request #34090 from mwielgus/designdoc-rs
$  git status
On branch master
Your branch is ahead of 'origin/master' by 581 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    BUILD
	deleted:    build/OWNERS
	deleted:    build/README.md
	deleted:    build/build-image/Dockerfile
	deleted:    build/build-image/VERSION
	deleted:    build/build-image/cross/Makefile
	deleted:    build/build-image/cross/golang-patches/CL28857-go1.7.1-luxas.patch
	deleted:    build/build-image/rsyncd.sh
	deleted:    build/cni/Makefile
	deleted:    build/copy-output.sh
	deleted:    build/debian-iptables/Dockerfile
	deleted:    build/debian-iptables/Makefile
	deleted:    build/debian-iptables/README.md
	deleted:    build/kube-dns/Changelog
	deleted:    build/kube-dns/Dockerfile
	deleted:    build/kube-dns/MAINTAINERS.md
	deleted:    build/kube-dns/Makefile
	deleted:    build/kube-dns/OWNERS
	deleted:    build/kube-dns/README.md
	deleted:    build/kube-dns/RELEASES.md
	deleted:    build/make-build-image.sh
	deleted:    build/make-clean.sh
	deleted:    build/pause/.gitignore
	deleted:    build/pause/Dockerfile
	deleted:    build/pause/pause.c
	deleted:    build/push-federation-images.sh
	deleted:    build/run.sh
	deleted:    build/shell.sh
	deleted:    build/util.sh
	deleted:    build/versionize-docs.sh
	deleted:    test/e2e_node/BUILD
	deleted:    test/e2e_node/build/build.go

no changes added to commit (use "git add" and/or "git commit -a")
```
</details>

**Comment by mikedanese** [comment] 2016-10-22 22:52
Seems like a race to decide which build wins:
<details>
```console
$ clone git@github.com:kubernetes/kubernetes.git
Cloning into 'kubernetes'...
remote: Counting objects: 360874, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 360874 (delta 8), reused 1 (delta 1), pack-reused 360848
Receiving objects: 100% (360874/360874), 333.50 MiB | 7.04 MiB/s, done.
Resolving deltas: 100% (236647/236647), done.
Checking out files: 100% (11471/11471), done.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    BUILD
	deleted:    test/e2e_node/BUILD

no changes added to commit (use "git add" and/or "git commit -a")
```
</details>

https://github.com/kubernetes/kubernetes/pull/35384 disables bazel. We need to decide wether to rename build/ or enforce case sensitve filesystems.

**Comment by mikedanese** [comment] 2016-10-22 22:55
> nothing we're doing here breaks normal Go, right?

Ya, we should absolutely always maintain compatibility with go build.

> This test, probably. In general, maybe not.

The test binary name change was made by gazel not bazel. Test binaries assume the name of the rules that generate them. e.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/BUILD#L66 .

> This raises a point of whether bazel is taking over Go's responsibilities, or just augmenting them

Bazel assumes the responsiblity of go build and instead relies on go tool compile. I believe that bazel is flexible enough that we can have a build that works with both. Go tool compile doesn't know about build tags or GOOS, GOARCH, CGO_ENABLED, GOPATH, GOROOT, the filepath of an input...


> So kind of speaks to the question of whether we can make gazel handle the "exactly map to Go rules auto generation" case, but still have a way to customize without then having to turn off auto generation.

That's the experiment. I will try to analyze and address your examples in depth next week.

**Comment by jbeda** [comment] 2016-10-22 23:20
Thanks @mikedanese! As for how to handle mac, IMO forcing the case sensitive file systems is a non-starter.

The other option is to wait until Bazel allows `BUILD.bazel` as the file name instead of just `BUILD`.  That looks like it is in progress and might land soon based on that bug.

**Comment by spxtr** [comment] 2016-10-24 17:56
I'd rather just rename our `build` directories. https://github.com/kubernetes/test-infra/issues/61 would have prevented this, but it's a huge pain to do this.

**Comment by smarterclayton** [comment] 2016-10-25 18:22
Can we rename bazel BUILD to .BUILD?

On Oct 22, 2016, at 4:35 AM, Joe Finney <notifications@github.com> wrote:

Ahh, case-insensitive filesystem bugs. Looks like we have two obvious
options:

   1. Don't support native builds on mac. Run it in docker.
   2. Rename all build/ folders to something else.

I'm happy with either solution, but remember @thockin
<https://github.com/thockin>'s words
<https://github.com/kubernetes/kubernetes/issues/30600#issuecomment-241160172>:
"Please don't make Linux builds suck just because Mac builds have to suck."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35359#issuecomment-255515240>,
or mute the thread

**Comment by smarterclayton** [comment] 2016-10-25 18:28
Is it possible on the mac to make the filesystem for bazel case sensitive?
It seems pretty likely we'll have packages and directories called "build"
in Kube ecosystem projects that want to reuse Kube build infra.

What "make fs" part is acting as insensitive?

On Oct 22, 2016, at 4:35 AM, Joe Finney <notifications@github.com> wrote:

Ahh, case-insensitive filesystem bugs. Looks like we have two obvious
options:

   1. Don't support native builds on mac. Run it in docker.
   2. Rename all build/ folders to something else.

I'm happy with either solution, but remember @thockin
<https://github.com/thockin>'s words
<https://github.com/kubernetes/kubernetes/issues/30600#issuecomment-241160172>:
"Please don't make Linux builds suck just because Mac builds have to suck."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35359#issuecomment-255515240>,
or mute the thread

**Comment by smarterclayton** [comment] 2016-10-25 18:35
We will eventually have other packages that are called "build".  OpenShift
has several.  I don't think assuming "build" is reserved is a long term
solution.

**Comment by smarterclayton** [comment] 2016-10-25 18:37
All the dealing with ugly real world stuff (Mac, distro build systems) I do
like the concept of bazel in terms of speeding up builds.

**Comment by smarterclayton** [comment] 2016-10-25 18:38
A nice addendum to:

Let not make developing on Kube suck

Which is probably more important to me.  Some Kube developers use Macs.
 95% of our code has zero to do with Linux.

On Oct 22, 2016, at 4:35 AM, Joe Finney <notifications@github.com> wrote:

Ahh, case-insensitive filesystem bugs. Looks like we have two obvious
options:

   1. Don't support native builds on mac. Run it in docker.
   2. Rename all build/ folders to something else.

I'm happy with either solution, but remember @thockin
<https://github.com/thockin>'s words
<https://github.com/kubernetes/kubernetes/issues/30600#issuecomment-241160172>:
"Please don't make Linux builds suck just because Mac builds have to suck."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35359#issuecomment-255515240>,
or mute the thread

**Comment by smarterclayton** [comment] 2016-10-25 18:46
We can set up a full case sensitive FS on mac via a partition if necessary.

On Oct 22, 2016, at 3:38 PM, Jeff Grafton <notifications@github.com> wrote:

Well, that is terrible.

Option 1 doesn't fix the issue - git is just going to fail to check out
build/ and BUILD on macOS.

Probably the only thing we can do is rename build/ to something else, but
that's going to break everyone who calls into build/ directly instead of
using make.

We need to do something soon, since this probably breaks all macOS
development.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35359#issuecomment-255549263>,
or mute the thread

**Comment by ncdc** [comment] 2016-10-25 18:49
> We can set up a full case sensitive FS on mac via a partition if necessary.

I don't see individual developers doing this (or were you joking?)

**Comment by spxtr** [comment] 2016-10-25 18:50
@smarterclayton I would agree with forcing developers to use a real file-system, but I don't think it's acceptable to be unable to clone the repo and make small docs changes on a mac. We have renamed the build folders, and we can add a presubmit that ensures this problem doesn't reoccur if necessary.

**Comment by ixdy** [comment] 2016-10-25 18:51
also hopefully https://github.com/bazelbuild/bazel/issues/552 will be fixed at some point in the next few months, which will solve the issue for us.

**Comment by smarterclayton** [comment] 2016-10-25 18:59
One more scenario - if I want to vendor Kube packages, what implications
are there to BUILD files in vendor/k8s.kubernetes/* directories?

**Comment by smarterclayton** [comment] 2016-10-26 16:28
The conflicts here are really annoying - I think in the last 3 days half of
my PRs have had merge conflicts, up significantly from when it was just API
changes.  Since *every* package in the system is now a candidate for merge
conflicts, we've made the merge problem a lot worse without fixing the "no
generated files" problem we originally set out to solve.

**Comment by spxtr** [comment] 2016-10-26 17:19
We can experiment with not checking in automanaged BUILD files.

**Comment by thockin** [comment] 2016-10-27 15:48
Can we just check in deltas?

**Comment by mikedanese** [comment] 2016-10-27 17:40
> Can we just check in deltas?

I will work on this.

**Comment by jayunit100** [comment] 2016-10-31 20:03
Thanks @mikedanese  ... :) ... Can we make a checklist for this guy to be closed? Probably several small PRs ; will be great for those of us in the community who are just learning and want to  watch the changes flow in.

**Comment by jayunit100** [comment] 2016-11-01 14:05
I think this is probably a checklist we can start with.  Any other stuff to add?
- [ fix mac update to not create extra files ]
- [ educate community on bazel in the docs ]
- [ make it so that verify-bazel gives more info on whats wrong ]

**Comment by spxtr** [comment] 2016-11-01 16:42
> maybe automate bazel update bot post-commit ? seems entirely possible.

We should add docs showing how to add a vim rule that updates bazel when you save.

**Comment by mbohlool** [comment] 2016-11-02 01:08
Adding a data point here. To sync, I forced to create a new case sensitive
image based partition on my mac. That was pretty painful because mac also
has a bug there in creating case sensitive partitions. I can sync/develop
now but at the cost of losing some performance.


Mehdy Bohlool |  Software Engineer |  mehdy@google.com |  mbohlool@github
<https://github.com/mbohlool>

**Comment by mikedanese** [comment] 2016-11-02 01:11
> I forced to create a new case sensitive
> image based partition on my mac

That should be fixed on HEAD and no longer necessary.

**Comment by ixdy** [comment] 2016-12-05 19:16
FYI we should be able to rename back to `build/` now. https://github.com/kubernetes/kubernetes/issues/38126

**Comment by techtonik** [comment] 2017-05-23 03:05
#38126 is resolved. What else is left to close the issue?

**Comment by smarterclayton** [comment] 2017-05-23 14:08
That Kubernetes builds on bazel.  Renaming build/ was only the p0.

**Comment by techtonik** [comment] 2017-05-23 19:14
@smarterclayton https://github.com/bazelbuild/bazel/issues/552 is fixed. What else is needed?

**Comment by smarterclayton** [comment] 2017-05-24 04:15
The issue now is that no cross-compile with bazel succeeds because bazel has no support for golang cross-compile and platform specific tags.  I.e. on a mac, `bazel build` is broken in Kubernetes.  The specific issue with regards to 552 is fixed, but not the broader issue.

**Comment by techtonik** [comment] 2017-05-24 11:58
@smarterclayton is there a ticket to track?

**Comment by mikedanese** [comment] 2017-05-24 17:22
This is the ticket. The test is to grab a mac and run make bazel-build

**Comment by mikedanese** [comment] 2017-05-24 17:23
Also https://github.com/mikedanese/gazel/issues/6

**Comment by ixdy** [comment] 2017-08-03 07:35
/assign

Once #47558 is fixed (in the next week or so) bazel build on mac should work, though cross-compilation to linux won't be supported until the next bazel release (probably later this month).

**Comment by techtonik** [comment] 2017-10-10 01:25
#47558 is fixed, so do Mac OS builds start to work?

**Comment by BenTheElder** [comment] 2018-04-09 18:45
on 1.10 something like `bazel build //cmd/kubeadm --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64` works great, though this only includes non-cgo binaries AFAIK

**Closed** 2018-09-06 20:51 UTC
Labels: area/build-release, lifecycle/rotten, priority/important-soon, sig/contributor-experience
