### ISSUE TITLE
Load configmap from file dynamically using configmap resource yml

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#41711] opened 2017-02-19 10:07 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubectl configmap from-file

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request (I think)

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

Make it possible (if it is not already and I haven't missed it) to load a configmap on the fly using a config yml?

Let's say I have a config file for some service, e.g. an nginx config `nginx.conf`. I want my custom nginx.conf to be available to my containers at runtime without extending the base image.

The k8s way is a configmap which then is mounted as a volume. To do that, I need to load the contents of that file as a configmap. I have two choices:

1. Run `kubectl create configmap some-name --from-file=path/to/my/nginx.conf`, which requires a separate `create` command rather than simple and idempotent `apply -f`.
2. Copy the entire nginx.conf into `nginx-confmap.yml` under `data:`, which is not very practical for editing and makes testing/debugging the config very difficult (not to mention DRY...).

Ideally, I should run `kubectl apply -f confdir/` (where all my yml are) and it does the right thing, including loading an individual file as configmap _at apply time_.

I would imagine something like:

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config
  namespace: default
dataFromFile: ./data/nginx.conf
```

1. Run `kubectl apply -f confdir/`
2. The file `nginx-confmap.yml` has a reference to the relative config file
3. kubectl sees the reference and loads it up

This allows me to stick with a standard set of files and operational flow `kubectl apply -f dir/` while maintaining my config files in their original format.

BTW, terraform works like this, as do other config management tools. When I use compose locally, I volume-mount the original file, making it clean.

**Comment by smarterclayton** [comment] 2017-02-27 22:15
Because each applied object is an API object, it's unlikely we'll be able to do this without someone introducing a tool on top to be invoked before apply.  Helm and other tools can offer some of this.

**Comment by deitch** [comment] 2017-02-27 23:00
> Because each applied object is an API object

How does `create configmap --from-file=some/file` do it? Wouldn't we want parity?

**Comment by skippy** [comment] 2017-03-14 19:47
@deitch THANKS for opening this up.  being able to do this in a declarative way via configs vs running a separate command is a nice +1.

**Comment by bgrant0607** [comment] 2017-03-23 02:53
Dupe of #30337

**Closed by bgrant0607** 2017-03-23 02:53 UTC

**Comment by deitch** [comment] 2017-03-24 13:39
@bgrant0607 this is _not_ a duplicate. #30337 refers to being able to upsert configmaps from files, so I can do `kubectl apply configmap mmap --from-file=/some/file`.

This issue refers to the ability to do it declaratively from a `yml` config file.

**Comment by Globegitter** [comment] 2017-06-22 12:15
Agreed @bgrant0607 this is not a duplicate, would be great to re-open.

**Comment by moizjv** [comment] 2017-06-30 00:06
Yes, I agree it would be great to reopen this.

**Comment by andyp1per** [comment] 2017-07-03 14:53
Yes agree reopen.

**Comment by zhangyihong** [comment] 2017-07-19 00:50
Yes, I agree it would be great to reopen this.

**Comment by 4220182** [comment] 2017-07-19 00:53
Yes , agree reopen.

**Comment by ecebuzz** [comment] 2017-07-20 15:28
Yes, it would be great to reopen this.

**Comment by vincbe** [comment] 2017-07-31 15:29
It seems coherent in the way we create K8s services and ressources from YAML files.

**Comment by sascha-coenen** [comment] 2017-08-13 11:05
please reopen this ticket

**Comment by SuperNami** [comment] 2017-08-15 04:06
Am also looking for this specifically, without this feature I need to remember to run the kubectl command before deploying my application. Same with secrets.

**Comment by sbourlon** [comment] 2017-08-28 18:42
Hi @bgrant0607, is this feature on the roadmap? It would be nice to have something similar to the docker-compose `env_file` (https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) as described by @deitch.

**Comment by ryanberckmans** [comment] 2017-08-29 18:32
This feature would be great.

**Comment by gabrielruiu** [comment] 2017-09-01 09:54
+1 for development of such a feature

**Comment by bgrant0607** [comment] 2017-09-01 18:01
I closed #30337 as a dupe of #24744.

See also my comment here:
https://github.com/kubernetes/kubernetes/issues/30558#issuecomment-326643503

How I see this fitting into the bigger picture is described in my uber doc: https://goo.gl/T66ZcD

I believe this is adequately covered by the other issues.

**Comment by bgrant0607** [comment] 2017-09-01 18:03
And, if anyone would like to help with either imperative or declarative forms of updates, please reach out to SIG CLI.

https://github.com/kubernetes/community/tree/master/sig-cli

**Comment by bgrant0607** [comment] 2017-09-01 18:06
@sbourlon 

kubectl create configmap --from-env-file:
https://kubernetes.io/docs/user-guide/kubectl/v1.7/#-em-configmap-em-

**Comment by pkennel** [comment] 2018-04-06 18:01
Agreed, there is a big distinction between having a resource declared in a yaml file, vs being required to use your brain, or annotate in a README.md that one should additionally create a config file with a separate cli command than `kubectl apply` or `kubectl create`

> @bgrant0607 this is not a duplicate. #30337 refers to being able to upsert configmaps from files, so I can do kubectl apply configmap mmap --from-file=/some/file.

> This issue refers to the ability to do it declaratively from a yml config file.

I would also love to see this feature implemented.  I would at least love to know what the logic is behind not supporting a kubernetes resource file reference a filesystem config file, as separate from running the `kubectl create configmap` command a separately.

**Comment by scniro** [comment] 2018-05-17 00:08
How is this seriously closed? This is a **deal breaker**. Welp, back to docker compose...

**Comment by bgrant0607** [comment] 2018-06-04 23:29
The ConfigMap API isn't the right place to express this.

This is covered by other issues, such as #24744. Apply does both creation and update, so they need to be handled the same.

PTAL 
https://github.com/kubernetes-sigs/kustomize
https://github.com/kubernetes/community/blob/master/keps/sig-cli/0008-kustomize.md
