### ISSUE TITLE
Provide a mechanism to support container migration in K8S

### ISSUE THREAD

**Issue by vutuong** [kubernetes/kubernetes#86341] opened 2019-12-17 08:10 UTC
**What would you like to be added**:
When we checkpoint then stop container by using docker engine, pod status will be marked as Error. But after that, when we restore Container, pod status should back to Running. 
**Why is this needed**:
One of the key challenges for edge computing is keeping quality of service guarantees better than traditional cloud services while offloading services to the end user’s nearest edge server. However, when the end user moves away from the nearby edge server, the quality of service will significantly
decreases. 
Therefore, efficient live migration is vital to enable the mobility of edge services in the edge computing environment.
Live migration of Docker containers is achievable by using checkpoint and restore tool ( CRIU).
This is reason why K8S should support checkpoint and restore tool.
/sig scalability

**Comment by vutuong** [comment] 2019-12-18 06:36
#investigating

**Comment by mikedanese** [comment] 2019-12-19 05:02
Duplicate of #3949

**Closed by mikedanese** 2019-12-19 05:02 UTC
Labels: kind/feature, sig/scalability
