### ISSUE TITLE
Retry loops should only read from the cache the first iteration

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#37725] opened 2016-11-30 23:31 UTC
Specifically, this code https://github.com/kubernetes/kubernetes/blob/5e1adf91dfbe6ec9f96950e9b4e28523b8d3ccd8/pkg/kubelet/kubelet_node_status.go#L325 reads from the cache every time, so it will keep failing as long as the cache is stale, which could be arbitrarily long.

@wojtek-t

**Comment by lavalamp** [comment] 2016-11-30 23:39
@saad-ali

**Comment by lavalamp** [comment] 2016-12-01 01:04
(release-blocker because we think this is a regression from 1.4 and it will be bad if someone hits it.)

**Comment by dchen1107** [comment] 2016-12-01 01:43
@wojtek-t I assigned this to you since it looks like a regression from https://github.com/kubernetes/kubernetes/pull/35294. Should we revert the pr?

**Comment by wojtek-t** [comment] 2016-12-01 07:41
This PR significantly improved performance. I will prepare a quick fix to do exactly what Daniel said.

**Comment by wojtek-t** [comment] 2016-12-01 08:13
https://github.com/kubernetes/kubernetes/pull/37788 is out for review (it's 6-line fix)

**Comment by dims** [comment] 2016-12-01 16:43
Looks like good news on this one thanks @lavalamp @wojtek-t

**Closed** 2016-12-01 23:06 UTC
Labels: kind/bug, priority/P0, release-blocker, team/node
