### ISSUE TITLE
e2e node flake: unable to create gce instance

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#28685] opened 2016-07-08 15:20 UTC
```

================================================================
I0708 08:07:48.151027   18781 run_e2e.go:342] Error deleting instance tmp-node-e2e-5de56a75-e2e-node-containervm-v20160321-image
================================================================
Failure Finished Host  Test Suite

unable to create gce instance with running docker daemon for image e2e-node-containervm-v20160321-image.  googleapi: Error 404: The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/tmp-node-e2e-5de56a75-e2e-node-containervm-v20160321-image' was not found, notFound
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28680/node-pull-build-e2e-test/13599/

**Comment by liggitt** [comment] 2016-07-08 16:55
dupe of https://github.com/kubernetes/kubernetes/issues/28683 (won by 2!)

**Closed by liggitt** 2016-07-08 16:55 UTC
Labels: kind/flake, team/test-infra
