### ISSUE TITLE
Flake in controller framework test

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#14138] opened 2015-09-17 21:26 UTC
```
E0917 14:23:44.991518   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:46.208306   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:47.208547   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:47.208700   84561 util.go:72] Recovered from panic: "sync: negative WaitGroup counter" (sync: negative WaitGroup counter)
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:66
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:54
/usr/local/go/src/runtime/asm_amd64.s:437
/usr/local/go/src/runtime/panic.go:423
/usr/local/go/src/sync/waitgroup.go:70
/usr/local/go/src/sync/waitgroup.go:95
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:333
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:182
<autogenerated>:23
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:252
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:126
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:115
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:116
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/local/go/src/runtime/asm_amd64.s:1696
--- FAIL: TestUpdate (2.00s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
        panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 50 [running]:
testing.tRunner.func1(0xc8203f8360)
        /usr/local/go/src/testing/testing.go:450 +0x171
sync.(*WaitGroup).Wait(0xc82040e420)
        /usr/local/go/src/sync/waitgroup.go:128 +0x114
k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate(0xc8203f8360)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:393 +0xb1c
testing.tRunner(0xc8203f8360, 0xfb67b0)
        /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xbcbe90, 0xfb6780, 0x3, 0x3, 0xc82017f601)
        /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200b9ee8, 0xc8200f0ea8)
        /usr/local/go/src/testing/testing.go:494 +0x70
main.main()
        k8s.io/kubernetes/pkg/controller/framework/_test/_testmain.go:64 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xfd0640)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 11 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820111480)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 13 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820111600)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 14 [semacquire]:
sync.runtime_Syncsemacquire(0xc82011c7a8)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82011c798)
        /usr/local/go/src/sync/cond.go:62 +0x9b
k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop(0xc82011c780, 0x0, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:290 +0xb2
k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop(0xc8201207e0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:125 +0x44
k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm()
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x20
k8s.io/kubernetes/pkg/util.Until.func1(0xc820047f88)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:115 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc820047f88, 0x3b9aca00, 0xc8201629c0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:116 +0x53
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc8201207e0, 0xc8201629c0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x1c2
created by k8s.io/kubernetes/pkg/controller/framework_test.TestHammerController
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:223 +0x3d4

goroutine 51 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820408400)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 52 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
k8s.io/kubernetes/pkg/util.Until(0xc820425f78, 0x3b9aca00, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:117 +0x61
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc82027ba40, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x1c2
created by k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:377 +0x874

goroutine 65 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
k8s.io/kubernetes/pkg/util.Until(0xc82040c8e0, 0x3b9aca00, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:117 +0x61
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:144 +0x9a
FAIL    k8s.io/kubernetes/pkg/controller/framework      2.287s
```

@lavalamp @mvdan

**Comment by mvdan** [comment] 2015-09-17 21:34
@mikedanese could you assign this to me? I can't assign to self.

**Comment by mvdan** [comment] 2015-09-19 05:26
@mikedanese I'm having a hard time reproducing this crash. What Go version is this? Did it run with or without `-race`? I assume this was on your machine - have you been able to reproduce it?

**Comment by mikedanese** [comment] 2015-09-23 20:19
I am running this with g1.5.1

**Comment by mvdan** [comment] 2015-09-26 18:35
So the issue is that sometimes, `Done()` gets called 13 times instead of 12. `DeleteFunc` is called an extra time, I haven't found out why yet.

**Comment by mvdan** [comment] 2015-09-26 18:57
See #14616.

**Comment by mvdan** [comment] 2015-09-26 19:03
I ran the tests a few hundred times to make sure it was gone - and it was - but that uncovered a less frequent flake. Opened #14617 for it.

**Closed** 2015-10-20 21:14 UTC
Labels: kind/flake, priority/P1, team/test-infra
