### ISSUE TITLE
e2e flake: NodeOutOfDisk test is flaky

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#17495] opened 2015-11-19 12:48 UTC
```
NodeOutOfDisk runs out of disk space

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:166
Expected
    <string>: gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1
to equal
    <string>: gke-jkns-gke-e2e-ci-92e7cbee-node-l228
```

**Comment by mwielgus** [comment] 2015-11-19 12:55
This started to break kubernetes-e2e-gke-ci 7h ago, just after it #16398 was merged.

**Comment by mwielgus** [comment] 2015-11-19 13:05
Some logs:

```
03:58:21 [BeforeEach] NodeOutOfDisk
03:58:21   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:84
03:58:21 STEP: Creating a kubernetes client
03:58:21 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gke-ci/workspace/.kube/config
03:58:21 STEP: Building a namespace api object
03:58:21 Nov 19 03:58:21.041: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-node-outofdisk-n4dxo
03:58:21 Nov 19 03:58:21.067: INFO: Service account default in ns e2e-tests-node-outofdisk-n4dxo with secrets found. (26.489706ms)
03:58:21 STEP: Waiting for a default service account to be provisioned in namespace
03:58:21 Nov 19 03:58:21.067: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-node-outofdisk-n4dxo
03:58:21 Nov 19 03:58:21.069: INFO: Service account default in ns e2e-tests-node-outofdisk-n4dxo with secrets found. (1.678076ms)
03:58:21 Nov 19 03:58:21.072: INFO: Querying stats for node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 using url api/v1/proxy/nodes/gke-jkns-gke-e2e-ci-92e7cbee-node-l228/stats/
03:58:21 Nov 19 03:58:21.131: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228: disk space available 98219220992 bytes
03:58:21 STEP: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228: creating a file of size 98055643136 bytes to fill the available disk space
03:58:21 Nov 19 03:58:21.131: INFO: Getting external IP address for gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:21 Nov 19 03:58:21.131: INFO: Calling fallocate -l 98055643136 test.img on gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:21 Nov 19 03:58:21.484: INFO: Waiting up to 1m0s for node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition OutOfDisk to be true
03:58:21 Nov 19 03:58:21.487: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:21 Nov 19 03:58:21.487: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:41 -0800 PST
03:58:23 Nov 19 03:58:23.491: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:23 Nov 19 03:58:23.491: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:41 -0800 PST
03:58:25 Nov 19 03:58:25.494: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:25 Nov 19 03:58:25.494: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:41 -0800 PST
03:58:27 Nov 19 03:58:27.498: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:27 Nov 19 03:58:27.498: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:41 -0800 PST
03:58:29 Nov 19 03:58:29.501: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:29 Nov 19 03:58:29.501: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: True, reason: "KubeletOutOfDisk", message: "out of disk space", last transition time: 2015-11-19 03:58:28 -0800 PST
03:58:29 Nov 19 03:58:29.501: INFO: Successfully found condition OutOfDisk of node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 to be true
03:58:29 Nov 19 03:58:29.501: INFO: Querying stats for node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 using url api/v1/proxy/nodes/gke-jkns-gke-e2e-ci-92e7cbee-node-l228/stats/
03:58:29 Nov 19 03:58:29.545: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228: disk space available 163631104 bytes
03:58:29 Nov 19 03:58:29.545: INFO: Querying stats for node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 using url api/v1/proxy/nodes/gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1/stats/
03:58:29 Nov 19 03:58:29.595: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1: disk space available 97349222400 bytes
03:58:29 STEP: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1: creating a file of size 97185644544 bytes to fill the available disk space
03:58:29 Nov 19 03:58:29.595: INFO: Getting external IP address for gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1
03:58:29 Nov 19 03:58:29.595: INFO: Calling fallocate -l 97185644544 test.img on gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1
03:58:29 Nov 19 03:58:29.907: INFO: Waiting up to 1m0s for node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition OutOfDisk to be true
03:58:29 Nov 19 03:58:29.910: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:29 Nov 19 03:58:29.910: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:40 -0800 PST
03:58:31 Nov 19 03:58:31.913: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:31 Nov 19 03:58:31.913: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:40 -0800 PST
03:58:33 Nov 19 03:58:33.919: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:33 Nov 19 03:58:33.919: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:40 -0800 PST
03:58:35 Nov 19 03:58:35.928: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:35 Nov 19 03:58:35.928: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:40 -0800 PST
03:58:37 Nov 19 03:58:37.931: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:37 Nov 19 03:58:37.931: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:08:40 -0800 PST
03:58:39 Nov 19 03:58:39.935: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:39 Nov 19 03:58:39.935: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 condition 2/2: type: OutOfDisk, status: True, reason: "KubeletOutOfDisk", message: "out of disk space", last transition time: 2015-11-19 03:58:38 -0800 PST
03:58:39 Nov 19 03:58:39.935: INFO: Successfully found condition OutOfDisk of node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 to be true
03:58:39 Nov 19 03:58:39.935: INFO: Querying stats for node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 using url api/v1/proxy/nodes/gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1/stats/
03:58:39 Nov 19 03:58:39.974: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1: disk space available 163590144 bytes
03:58:39 [It] runs out of disk space
03:58:39   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:166
03:58:39 STEP: Get CPU capacity on node gke-jkns-gke-e2e-ci-92e7cbee-node-l1an
03:58:39 STEP: Creating pods and waiting for all but one pods to be scheduled
03:58:39 Nov 19 03:58:39.981: INFO: Waiting up to 5m0s for pod pod-node-outofdisk-0 status to be running
03:58:39 Nov 19 03:58:39.984: INFO: Waiting for pod pod-node-outofdisk-0 in namespace 'e2e-tests-node-outofdisk-n4dxo' status to be 'running'(found phase: "Pending", readiness: false) (3.048183ms elapsed)
03:58:41 Nov 19 03:58:41.988: INFO: Found pod 'pod-node-outofdisk-0' on node 'gke-jkns-gke-e2e-ci-92e7cbee-node-l1an'
03:58:41 Nov 19 03:58:41.995: INFO: Waiting up to 5m0s for pod pod-node-outofdisk-1 status to be running
03:58:42 Nov 19 03:58:42.034: INFO: Waiting for pod pod-node-outofdisk-1 in namespace 'e2e-tests-node-outofdisk-n4dxo' status to be 'running'(found phase: "Pending", readiness: false) (38.623148ms elapsed)
03:58:44 Nov 19 03:58:44.038: INFO: Found pod 'pod-node-outofdisk-1' on node 'gke-jkns-gke-e2e-ci-92e7cbee-node-l1an'
03:58:44 STEP: Finding a failed scheduler event for pod pod-node-outofdisk-2
03:58:46 STEP: Recovering disk space on node gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:46 STEP: Recovering disk space on node gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:46 Nov 19 03:58:46.078: INFO: Getting external IP address for gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:46 Nov 19 03:58:46.078: INFO: Calling rm -f test.img on gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:46 Nov 19 03:58:46.265: INFO: Waiting up to 1m0s for node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition OutOfDisk to be false
03:58:46 Nov 19 03:58:46.268: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:46 Nov 19 03:58:46.268: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: True, reason: "KubeletOutOfDisk", message: "out of disk space", last transition time: 2015-11-19 03:58:28 -0800 PST
03:58:48 Nov 19 03:58:48.272: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:48 Nov 19 03:58:48.272: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: True, reason: "KubeletOutOfDisk", message: "out of disk space", last transition time: 2015-11-19 03:58:28 -0800 PST
03:58:50 Nov 19 03:58:50.275: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-11-19 03:09:16 -0800 PST
03:58:50 Nov 19 03:58:50.275: INFO: Node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 condition 2/2: type: OutOfDisk, status: False, reason: "KubeletHasSufficientDisk", message: "kubelet has sufficient disk space available", last transition time: 2015-11-19 03:58:48 -0800 PST
03:58:50 Nov 19 03:58:50.275: INFO: Successfully found condition OutOfDisk of node gke-jkns-gke-e2e-ci-92e7cbee-node-l228 to be false
03:58:50 STEP: Verifying that pod pod-node-outofdisk-2 schedules on node gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:50 Nov 19 03:58:50.275: INFO: Waiting up to 5m0s for pod pod-node-outofdisk-2 status to be running
03:58:50 Nov 19 03:58:50.278: INFO: Waiting for pod pod-node-outofdisk-2 in namespace 'e2e-tests-node-outofdisk-n4dxo' status to be 'running'(found phase: "Pending", readiness: false) (2.246924ms elapsed)
03:58:52 Nov 19 03:58:52.281: INFO: Found pod 'pod-node-outofdisk-2' on node 'gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1'
03:58:52 [AfterEach] NodeOutOfDisk
03:58:52   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:98
03:58:52 STEP: Recovering disk space on node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1
[....]
03:58:54 Nov 19 03:58:54.242: INFO: Successfully found condition Ready of node gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1 to be true
03:58:54 STEP: Destroying namespace "e2e-tests-node-outofdisk-n4dxo" for this suite.
03:58:54 
03:58:54 • Failure [33.804 seconds]
03:58:54 NodeOutOfDisk
03:58:54 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:167
03:58:54   runs out of disk space [It]
03:58:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:166
03:58:54 
03:58:54   Expected
03:58:54       <string>: gke-jkns-gke-e2e-ci-92e7cbee-node-vuw1
03:58:54   to equal
03:58:54       <string>: gke-jkns-gke-e2e-ci-92e7cbee-node-l228
03:58:54 
03:58:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:165
```

**Comment by wojtek-t** [comment] 2015-11-30 07:29
It happened again multiple times:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9675/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9652/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9753/

**Comment by wojtek-t** [comment] 2015-11-30 07:33
And there seem to be 2 different issues here:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9733/

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:84 Node gke-jkns-gke-e2e-ci-4aa15597-node-pnkr did not run out of disk within 1m0s Expected : false to be true

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9746/

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/nodeoutofdisk.go:168 Expected : gke-jkns-gke-e2e-ci-d25834e4-node-p7ko to equal : gke-jkns-gke-e2e-ci-d25834e4-node-16oz

@kubernetes/goog-node

**Comment by wojtek-t** [comment] 2015-11-30 09:17
I did some more debugging of it.

1. Is it possible that the timeout is too small here? We already had a lot of such problems in different places...

2. Here the problem is that:
- you're trying to schedule some pods on the given node (the one that is not out-of-disk)
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/nodeoutofdisk.go#L120
- however, because of some reason, some of those pods are scheduled on different nodes:

    08:27:04 Nov 29 08:27:04.451: INFO: Found pod 'pod-node-outofdisk-0' on node 'gke-jkns-gke-e2e-ci-d25834e4-node-16oz'
    08:27:06 Nov 29 08:27:06.464: INFO: Found pod 'pod-node-outofdisk-1' on node 'gke-jkns-gke-e2e-ci-d25834e4-node-p7ko'

I will try to look deeper into it.

**Comment by wojtek-t** [comment] 2015-11-30 09:42
hmm - to be honest, this
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9652/

is yet another type of failure

So we have at least 3 different type of failures in this test.


So I'm going to move it to gce-flaky suite temporarily.

**Comment by wojtek-t** [comment] 2015-11-30 10:11
@davidopp - is this may also be related to scheduler 
[to be honest, I think that scheduler code is correct (I quickly looked into it), but scheduling decisions are unexpected from the test pov].
Also note, that my feeling is that some of the problems here are system problems, not test problems.

@madhusudancs - it would be great if you could look into it asap

**Comment by madhusudancs** [comment] 2015-12-01 00:21
@wojtek-t I am looking into it.

**Comment by wojtek-t** [comment] 2015-12-03 13:14
@madhusudancs - did you manage to find something?

**Comment by madhusudancs** [comment] 2015-12-03 22:46
@wojtek-t No luck yet. For the timeout problem I will just increase the timeout duration and try. 

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9746/ and http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9652/ are different manifestations of the same problem. In both the cases the nodes where the pods are scheduled are not the expected nodes because they are supposed to be OutOfDisk=true. But in both the cases the pods are being scheduled on to that node. Trying to debug. The trouble is, I have no good way to reproducing this failure locally.

**Comment by goltermann** [comment] 2016-01-11 18:25
This one hasn't been touched in a long time.  Should #18691 fix it?  Can you take that across the finish line?

**Comment by madhusudancs** [comment] 2016-01-11 18:51
I tried #18691 thinking that, that approach would fix the flakiness, but it doesn't. I am still thinking about other possible approaches.

**Comment by davidopp** [comment] 2016-01-11 19:22
We decided to put this on the back burner. @madhusudancs already sunk an enormous amount of time into it and there is more critical stuff to work on. Bumping to P1.

**Comment by davidopp** [comment] 2016-01-22 17:47
I'm going to assign to myself for now and move this to the flaky test suite because nobody has been able to figure out how to write a non-flaky e2e test for this feature. We can revisit later.

**Comment by davidopp** [comment] 2016-01-22 19:32
Ah, it was already in flaky test suite. Closing issue, will file repalcement issue.

**Closed by davidopp** 2016-01-22 19:32 UTC
Labels: area/test, kind/flake, priority/P1, team/node
