### ISSUE TITLE
nftables do not scale for services

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/kubernetes#96018] opened 2020-10-29 19:50 UTC
**What happened**:
Can only scale up to ~500 services on a nftables based cluster (CentOS 8+, Debian 10+) with kube-proxy.
With 1000 services, around half fails to work.

**What you expected to happen**:
Tested with same cluster deployment, but on Ubuntu 18.04 (that uses legacy iptables) and managed to reach 2500 services.

**How to reproduce it (as minimally and precisely as possible)**: 
* create a 100 node cluster on OS with nftables enabled (CentOS 8, Debian 10)
* create simple http deployment (nginx) with 200 replicas
* create Load Balancer services (below example): I have used 100 VIPs and 10 Ports/svc
* wait for the cluster to "stabilize"
* try curl to every svcIP:Port

```
apiVersion: v1
kind: Service
metadata:
  name: scale-service-{{.Num}}
spec:
  ports:
{{range .Ports}}
  - port: {{.}}
    protocol: TCP
    targetPort: 8080
    name: sv{{.}}
{{- end}}
  selector:
    app: scale-service
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{.IP}}
```

**Anything else we need to know?**:
The iptables-save rules count on nftables reached ~400k lines when some services were unreachable.
For the non-nftables case I was able to see >1m rules.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- Cloud provider or hardware configuration: Deployed on VMs with 4vCPU, 16G mem,  50G disk,
- OS (e.g: `cat /etc/os-release`): CentOS 8.1
- Kernel (e.g. `uname -a`): 4.18
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Cilium 1.8 with kube-proxy present, using metalLB
- Others:

**Comment by bridgetkromhout** [comment] 2020-10-29 21:09
Discussion of newer OS version. (At least 1.8.4 of iptables)
/assign @dcbw

**Comment by mskrocki** [comment] 2020-11-04 00:33
I see same results (only ~500 services) on:
```
# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

# iptables --version
iptables v1.8.4 (nf_tables)
```

**Comment by dcbw** [comment] 2020-11-12 22:05
@mskrocki what specific RPM version of iptables? I would recommend iptables-1.8.4-10.el8_2.2

**Comment by dcbw** [comment] 2020-11-12 22:05
And if you have a relatively recent iptables, when you have 1000 services, could you grab iptables-save dump and attach?

**Comment by mskrocki** [comment] 2020-11-13 00:42
I have been using 1.8.4-10.el8_2.1, any guide on how I can get the 2.2 version?
I will try the test again and provide the dump later.

**Comment by mskrocki** [comment] 2020-11-13 17:12
Recently did some more testing, and manged to reproduce this issue with a small, 6 node cluster, meaning this is independent of cluster size. The node has to be big enough to handle the workload. Managed to find the cut-off value at around ~100k endpoints (e.g 200 replicas x 500 services). Going above that value starts to break some services.

**Comment by thockin** [comment] 2020-12-10 20:33
@mskrocki What is the followup here?  Do we think it is a kube bug, a kernel bug, or expected?

**Comment by dcbw** [comment] 2020-12-10 22:18
> I have been using 1.8.4-10.el8_2.1, any guide on how I can get the 2.2 version?
> I will try the test again and provide the dump later.

@mskrocki 1.8.4-10.el8_2.4 is latest in RHEL 8.3 which will likely show up in CentOS 8.3 at some point soon... happy to help you test those fixes out if you like.

**Comment by mskrocki** [comment] 2020-12-10 22:24
@thockin I think this is strictly iptables issue.

@dcbw any chance to get the rpm for testing somehow? Yeah, I will try to get the iptables dump.

**Comment by mskrocki** [comment] 2020-12-11 02:35
Tried this again Today, and got same results with 100 services (15 ports each) with 100 replica deployment (150000 endpoints) using:
```
# yum list installed |grep ipta
iptables.x86_64                      1.8.4-15.el8                            @BaseOS
```
that I got by just running yum update, I assume that version is newer from what you suggested?

To add, those are logs from kube-proxy:
```
I1211 02:22:16.176094       1 proxier.go:825] Sync failed; retrying in 30s
I1211 02:23:30.382895       1 trace.go:116] Trace[1952179761]: "iptables save" (started: 2020-12-11 02:23:26.853156607 +0000 UTC m=+1284.656421753) (total time: 3.529689976s):
Trace[1952179761]: [3.529689976s] [3.529689976s] END
I1211 02:23:37.647347       1 trace.go:116] Trace[2106935590]: "iptables save" (started: 2020-12-11 02:23:30.382932799 +0000 UTC m=+1288.186197946) (total time: 7.264374079s):
Trace[2106935590]: [7.264374079s] [7.264374079s] END
I1211 02:23:57.377823       1 trace.go:116] Trace[134025954]: "iptables restore" (started: 2020-12-11 02:23:41.146054014 +0000 UTC m=+1298.949319140) (total time: 16.231714959s):
Trace[134025954]: [16.231714959s] [16.231714959s] END
E1211 02:23:57.377884       1 proxier.go:1555] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 615306 failed
)
```
The iptables-save file has ~50MB, any suggestion on how to share that?

**Comment by thockin** [comment] 2021-01-08 00:25
You can upload it to drive or something and share it with sig-net ML ?

**Comment by dcbw** [comment] 2021-01-21 20:36
@mskrocki if you're using RHEL 8.3 (or CentOS equivalent) then you'll want at least iptables-1.8.4-15.el8_3.2 or later, unfortunately.

Upstream iptables release 1.8.6 (from late October) has all the fixes as well.

**Comment by thockin** [comment] 2021-02-04 21:48
Any updates on this @mskrocki ?

**Comment by mskrocki** [comment] 2021-02-04 21:51
No, no updates. I do have all the req packages, need to find time for this thou.

**Comment by mskrocki** [comment] 2021-02-08 18:54
Re-tested with:
```
[root@bm-node-06 ~]# yum list installed |grep ipta
iptables.x86_64                      1.8.4-15.el8_3.3                        @BaseOS          
iptables-ebtables.x86_64             1.8.4-15.el8_3.3                        @BaseOS          
iptables-libs.x86_64                 1.8.4-15.el8_3.3                        @BaseOS          
```
still same results, failing service around 150k endpoints.
This is the iptables-save dump during the failures: https://drive.google.com/file/d/1vQrpeWeXKFP3T7TRwWLqCplN3t8xSKdu/view?usp=sharing

**Comment by mskrocki** [comment] 2021-02-08 18:56
Just want to confirm, will kube-proxy's iptables version inside to image matter here?

**Comment by dcbw** [comment] 2021-02-18 20:50
> Just want to confirm, will kube-proxy's iptables version inside the image matter here?

yes, that would be the iptables version that matters (unless the image is mounting the host's directories and using the host versions)

**Comment by dcbw** [comment] 2021-02-19 05:08
So... this iptables save is 695992 lines. Which is extremely large. In the past, with just *iptables* (eg not iptables-nft), I've seen performance issues with iptables-restore with just 100,000 or 150,000 lines. We typically recommend setting min-sync-period to some large number of seconds (30? 60?) in cases like that.

Are you able to find out how much time iptables-restore (nft) takes to restore this 700,000 line dump?

**Comment by mskrocki** [comment] 2021-02-19 23:32
Run directly on the host:
```
# time iptables-restore iptables2.log 
iptables-restore: line 695918 failed

real    0m12.772s
user    0m10.062s
sys     0m2.450s
```

**Comment by dcbw** [comment] 2021-03-04 19:48
@mskrocki would you be able to provide that iptables-restore ruleset for further analysis?

**Comment by dcbw** [comment] 2021-03-18 19:37
@mskrocki ping? If we can get a ruleset from iptables-restore we can figure out where the hotspots are.

**Comment by mskrocki** [comment] 2021-03-18 19:41
I dont have that one exactly. What about the one I linked above, I dont think it will be any different.

**Comment by n0-1** [comment] 2021-03-24 17:06
Hi,

I can reproduce the failure with upstream iptables.
As for run-time, iptables-legacy restores the attached dump in 6.5min on my testing VM, iptables-nft fails after 16min. :(
Maybe the ruleset is simply too big, but of course if legacy iptables eats it iptables-nft shall do as well.
Still investigating, just a quick status update.

Cheers, Phil

**Comment by dcbw** [comment] 2021-04-06 01:48
Phil and Pablo have posted patches to improve iptables-nft performance to iptables-legacy levels based on the ruleset from this issue:
https://marc.info/?l=netfilter-devel&m=161730110620551&w=2
https://marc.info/?l=netfilter-devel&m=161730896024892&w=2

**Comment by n0-1** [comment] 2021-04-06 09:28
A fix to allow for large rulesets currently under review: https://marc.info/?l=netfilter-devel&m=161769909013299&w=2
Performance improvement applied meanwhile: https://marc.info/?l=netfilter-devel&m=161676942405027&w=2

**Comment by dcbw** [comment] 2021-04-15 21:13
While I think it was good to keep this bug open to debug/track the problem, I think we can close it now since the fixes are in nftables/iptables and are under review or already merged.
/close

**Closed** 2021-04-15 21:14 UTC
Labels: area/kube-proxy, kind/bug, needs-triage, sig/network

**Comment by n0-1** [comment] 2022-07-23 09:08
@liuyuan10  iptables v1.8.8 has all you need.
