### ISSUE TITLE
static pods can mount pvc *sometimes*

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#65004] opened 2018-06-12 06:41 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
Not very sure about this, but it's behavior is not so good to me.

> /kind feature

**What happened**:
Static pods can mount pvc when a normal pod with the same pvc is scheduled to the same node.

**What you expected to happen**:
The behavior should be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a pvc
2. create a normal pod and mount the pvc in step 1
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: example
      image: busybox
      command: ["sleep", "10000"]
      volumeMounts:
        - name: nfsvol
          mountPath: /nfs
          subPath: container-example/pod-example
```
3. Check where the normal pod is scheduled.
4. In the node where the previous pod is scheduled, we create a static pod, mount the nfsvol pvc again:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-test-pod
  namespace: default
spec:
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: myclaim
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - "36000"
  volumeMounts:
  - name: nfsvol
    mountPath: /nfs
  restartPolicy: Always
```
5. check the running containers with command `docker ps`, we can see the container runs successfully.

**Anything else we need to know?**:
The static pod and normal pod should be in the same namespace.

**Environment**:
community master

**Comment by liggitt** [comment] 2018-06-13 13:55
> Static pods can mount pvc when a normal pod with the same pvc is scheduled to the same node.

the authorization restrictions here are working as intended:
* the NodeRestriction admission plugin disallows creation of the mirror pod
* the Node authorizer prevents the node from accessing the PVC resource unless it has a pod scheduled to it

in protecting against a compromised kubelet, this is sufficient.

if we want to the kubelet to voluntarily reject static pods containing PVCs, that would make this behavior more consistent/predictable, but wouldn't actually improve security. reassigning to sig-storage for evaluation.

/sig storage

**Closed** 2018-12-03 16:55 UTC
Labels: kind/bug, lifecycle/rotten, sig/storage
