### ISSUE TITLE
Tag collected Docker container logs with pod name

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#4845] opened 2015-02-26 17:34 UTC
Currently we collect the JSON Docker container logs and ingest them without further processing into either Elasticsearch or Cloud Logging. It would be useful to add fields to identify the name of the pod that corresponds to a specific Docker container log file (line) and perhaps also the hostname too. Relating the Docker container ID to a pod name might be possible by speaking to the kubelet during log ingestion time and this would require us to write a suitable filter in Ruby as part of our Flueuntd setup. However, we also need access to historical information because we may need to tag a log file for a Docker container for which the pod is not currently running -- perhaps by looking at events? This then also impacts one of the decisions we are trying to make about where events should be stored -- esp. if we decided to also store them as log files ingested by the same flow.

This would then allow users to query "all logs for a pod" and enable the query "all logs for a service".

@a-robinson @dchen1107 @lavalamp @thockin

**Comment by a-robinson** [comment] 2015-02-26 18:21
Mostly a duplicate of #4255 in terms of implementation, but we can keep this one open instead if it has better discussion. I'd only change your description by saying that we definitely need to annotate using the pod's labels, much more than we'd need its hostname.

As for implementation, the container ID -> pod info mapping should be very cacheable, helping with logs from a recently finished container. As for even corner-ier cases where we don't have cached info and can't grab it from the kubelet, I think it's fine to just punt on the issue and only annotate with the container ID. Given where we are in the project, getting a reasonably simple solution that annotates correctly most of the time is better than getting a couple more tenths of a percent of annotation reliability at the cost of much more design and development time.

**Comment by satnam6502** [comment] 2015-02-26 18:43
Ah, right,  I forgot about the existing issue. Yes,  good points about labels.

**Comment by dims** [comment] 2016-05-20 20:51
Looks like this already got implemented
https://github.com/kubernetes/kubernetes/commit/7404b7019cbbe7cd6267f2c0027e4d879a825262

```
// Create a symbolic link to the Docker container log file using a name which captures the
// full pod name, the container name and the Docker container ID. Cluster level logging will
// capture these symbolic filenames which can be used for search terms in Elasticsearch or for
// labels for Cloud Logging.
```

So can we close this bug?

**Comment by a-robinson** [comment] 2016-05-20 21:01
Yes.

**Closed by a-robinson** 2016-05-20 21:01 UTC
Labels: area/logging, priority/P3, team/cluster
