### ISSUE TITLE
Under what circumstance will invoke "webhook" to implements authorization and authentication, and where can I find it in source code? Thanks

### ISSUE THREAD

**Issue by xiaochunyn** [kubernetes/kubernetes#26552] opened 2016-05-31 08:28 UTC
1. I want to know when will invoke "webhook" or "ABAC" in source code.
2. For mode "webhook", what resources(eg. pods) can users perform what operation(create, delete)?
3. I want to know it clearly in source code.

Thank you !

**Comment by dims** [comment] 2016-05-31 11:22
Duplicate of https://github.com/kubernetes/kubernetes/issues/26513 ?

**Comment by zhouhaibing089** [comment] 2016-05-31 15:03
I fell this should be post to stackoverflow, being more specific on your question would get answers more quickly.

> when will invoke "webhook" or "ABAC" in source code

they are plugins, and you may not run this plugins if it is not configured properly, but if you ask when does these plugins get called, you may take a look at https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/handlers.go#L482-L491

> For mode "webhook", what resources(eg. pods) can users perform what operation(create, delete)?

I think the comments at https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/webhook/webhook.go tells most of the detail.

**Comment by xiaochunyn** [comment] 2016-06-01 05:34
@zhouhaibing089 thank you very much for your answer, which helps me a lot !

**Closed** 2016-06-02 13:04 UTC
