### ISSUE TITLE
Services should be able to up and down services is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16883] opened 2015-11-05 23:11 UTC
Ref #13478

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:259
Expected error:
    <*errors.errorString | 0xc208880180>: {
        s: "Only 2 pods started out of 3",
    }
    Only 2 pods started out of 3
not to have occurred

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/10860/?project=kubernetes-jenkins&pli=1

**Comment by brendandburns** [comment] 2015-11-05 23:25
This looks like a super slow image pull:

https://00e9e64bac817349619375304bf8e3134fc98e0000ee987ebf-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/logs%2Fkubernetes-e2e-gce-parallel%2F10860%2Fartifacts%2F104.197.51.84:22-kubelet.log?qk=AD5uMEvK_InZqIot0Bvh5_woBN-8Sp-eAL_C2aow8Zobhhux7H5Rnl7w0VbSR28LuxKZfKks4jA2pjThkby4XuW8rAVzyJ_8WXq5mpOUhWx0Mdf1QqDBo6sikGLCXfSqlrrQAUAKg6D7qorGGl5mFJB20Hjo32SvloA7Kr59PyOY38kEgQsyQBsQGyUAze-ZSui395OZH7vXUW2ovtyJ4O1th3vStQjV49u4MgMT4335lEMDnL96vUWu4kDQLvBRmxEKsz3JJ8l7YUU62A-bmcbiIRKFlRhLZQAfrgRzGs3wv-KDV8RCyKsXIZstv2b2MmOGzU7FHAfSWkoXxykK0Oj_c9jjAsrTeMw49T5W0G4ntB9urM2oFYvMSrd6Jqk7y-AuVYT4454eDpRPyaEOlBzRcNyoEpWCv40K5q9sDFbGzxqC0gCLET54az62HqFrGUaBfR_UyVMnI-TnUdsK8rlCVTImIcGopG62jC8XNbWQfJuYe5i0lAeNa3e6c3iNlheeE_rwf9vl6fbfvGs76S252Oh0XXLht-DqLykd8YHS_CZALvDS82LqBGPnlOdkOqMQCS_v2BkNezNyzKxcGUUZ0BO7-r0qzn6xzUAhSQn-8-QQ8eJpy32uUOseqvgep29FIShovgy-mdqrBwiFOwjAgZUU32z_stM6jE_nlBdVkmsCbGGoXOL4hd_Tfc87uFO26OKucywtJ0uJoPbPS0nwpvC6jVmx2PpUimrvkq1z3S08xM-68dyDIDDZqv1ISkOzTTR37ZSKFTx5wTItj1ynt0IytpMC_vobXZAjvuaMYCkp_TNie4KT7m1e83UKz-ugovDY0jJ24M0j95bCNl34jl-wFpTqWamD3I8Fq_SK_jMK3SieGJZfvXDXy3xyLSD4AdgZodG_w_3fccJcWV9OunpSD6mSREv0G6A8wrwrY6w0guMGZzc

Search for service1-1mw1m

Pod is created @ 22:42

Image pull finishes at 22:45:12.915667 

At which point we've already timed out.

**Comment by brendandburns** [comment] 2015-11-05 23:34
To clarify:

It's not a slow pull, its slow waiting to _start_ the pull.

Pod is created @ 22:42
Image pull starts @ 22:45:12
Image pull finishes @ 22:45:17

**Comment by brendandburns** [comment] 2015-11-05 23:34
@vishh 

We need to extend the timeouts and also pre-pull most images to work around these kind of problems.

**Comment by dchen1107** [comment] 2015-11-05 23:37
@vishh Based on @brendandburns's comment above, it looks like the flakiness is caused by your PR which makes kubelet does serialized image pulling by default. Can you take a look to verify this? If yes, we should fix our tests:

1) Extended the timeout value which I dislike, but can accept it to get rid of flakiness as soon as possible
2) Change the test itself to use cached images on the node. We should have tests to validate docker pulling, but not necessarily to pull for tests. 

cc/ @kubernetes/goog-testing @kubernetes/goog-cluster

**Comment by vishh** [comment] 2015-11-05 23:40
Is this issue critical? The issue is currently marked as P2.

**Comment by brendandburns** [comment] 2015-11-06 00:54
No, I don't think its critical.  It's flaked once in the past 30 runs, and it works eventually, if the test didn't timeout. So its more of a test bug than anything else.

**Comment by wojtek-t** [comment] 2015-11-30 19:12
Another one:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/18363/#

According to our policy, increasing priority to P0.

Can someone please take a lok? If that's just a matter of timouts, it should be easy to fix.

**Comment by zmerlynn** [comment] 2015-12-05 03:33
Another one:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9744/

**Comment by thockin** [comment] 2015-12-23 06:39
This is P0

**Closed** 2016-01-08 20:41 UTC
Labels: kind/flake, priority/P0, team/node
