### ISSUE TITLE
[k8s.io] Pods should be submitted and removed [Conformance] 1m42s

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41902] opened 2017-02-22 16:41 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41894/pull-kubernetes-e2e-gce/19327/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:262
Failed to observe pod deletion
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:251
```

**Comment by yujuhong** [comment] 2017-02-22 17:04
@dashpole is looking into this.

**Comment by yujuhong** [comment] 2017-02-22 17:12
Seems like a lot of flakes are caused by the watch issue: #31345 
Maybe we should switch to polling in the test.

**Comment by smarterclayton** [comment] 2017-02-24 18:55
I'm taking this

**Comment by smarterclayton** [comment] 2017-02-24 19:14
Opened a fix that will at minimum give us more info, but also increases timeout

**Comment by smarterclayton** [comment] 2017-02-27 21:40
This is the last failure before my changed merged: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4717

Still waiting for a post.

**Comment by dchen1107** [comment] 2017-03-09 23:41
@smarterclayton Do you think https://github.com/kubernetes/kubernetes/pull/42779 is enough to address this issue? Or there are some other pending issues in watching code? Can we close this one?

**Comment by smarterclayton** [comment] 2017-03-10 00:50
We can close this, the issue is almost certainly the one fixed.

**Closed by smarterclayton** 2017-03-10 00:50 UTC
Labels: kind/flake, priority/important-longterm, sig/node
