### ISSUE TITLE
TestMonitorNodeStatusEvictPodsWithDisruption is flakey

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#39975] opened 2017-01-16 20:55 UTC
Running latest from master (currently commit 8ab0519160594e5da50212da7994fc5dfbbe05de), I'm seeing TestMonitorNodeStatusEvictPodsWithDisruption is flakey:

1. go test -c ./pkg/controller/node
1. while true; do if ! ./node.test; then break; fi; done
1. wait for failure

I've narrowed it down https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/controller/node/nodecontroller_test.go#L1220, which is supposed to process all the items (nodes) in the `zonePodEvictor[zone]` queue. This queue has a capacity of 1, and at least in the test code, a refill rate of 10000 QPS. If the call to `TryAccept` fails [here](https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/controller/node/rate_limited_queue.go#L209), it will stop processing wherever it happened to be in the queue. I've added some extra logging locally, and when it fails, I see it processing nodes 1 and 2 before TryAccept fails. The issue is that the pod it's trying to evict is on node0, and it doesn't process node0 before TryAccept returns false.

cc @smarterclayton @mikedanese @liggitt @sttts

**Comment by ncdc** [comment] 2017-01-16 21:03
I'm surprised we haven't hit this in jenkins yet

**Comment by liggitt** [comment] 2017-01-17 03:03
https://github.com/kubernetes/kubernetes/pull/13642 and https://github.com/kubernetes/kubernetes/commit/98b954c74cb2035388ddcb6356422e95f4ebc7a7#diff-bc52fc0dd98c0169dbbd19624927ac39R164 removed the "leak" option referred to in the godoc, but it seems like it kept the leak behavior, not the retry behavior when the rate limiter is hit

**Comment by cheftako** [comment] 2017-02-13 22:14
Still seeing this issue

**Comment by ravisantoshgudimetla** [comment] 2017-03-03 23:01
@calebamiles I didn't understand how this is related to sig/scheduling. Am I missing anything here?

**Comment by liggitt** [comment] 2017-03-07 02:17
guessing the flake is related to this line:
```
		// Give some time for rate-limiter to reload
		time.Sleep(50 * time.Millisecond)
```

anything on the order of milliseconds is going to be unreliable in testenvs that sometimes peg the CPU with parallel tests

**Comment by gmarek** [comment] 2017-03-07 09:42
I can extend this sleep to something bigger, but I don't have cycles to debug it properly:/

**Comment by liggitt** [comment] 2017-03-07 13:35
> or it's related to the single item burst and the "abort when TryAccept fails" behavior

any thoughts on that?

**Comment by gmarek** [comment] 2017-03-07 14:47
Generally we retry when TryAccept fails, but not in tests. So either we need to rewrite the test, or lengthen the sleep time. It's not perfect, but there's no way for "wait until rate limiter is reloaded".

**Comment by ravisantoshgudimetla** [comment] 2017-03-07 17:40
@gmarek @liggitt I was working on this issue and I tried the change that you suggested and I notice that it fails with this change too. #42634 and I think rewriting the test with retry option is option as I tried increasing 5000 ms and still it failed. I am new to the codebase, if there is piece of code where retry is available, I can check on that.

**Comment by gmarek** [comment] 2017-03-07 18:58
@ravisantoshgudimetla - what you wrote is concerning. I wish I had time to debug it:/ Frankly - those tests are old. Like really, really old. So they start to deserve a rewrite. 

On the flip side - we'll need to rewrite them when making taint-based evictions default, so we'll need to allocate time for that anyway. If lengthening sleep time reduce the flakyness I vote for doing that, and just wait for upcoming rewrite. @liggitt @ncdc

**Comment by ravisantoshgudimetla** [comment] 2017-03-09 13:52
@gmarek having a delay in the loop before https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/controller/node/nodecontroller_test.go#L1222 caused it to run for close 4 hours without terminating on 8GB,4 core machine. Is this something normal?

 I know, @ncdc is not happy with this change but since we are rewriting this test anyways, this could be a work around that removes the flakyness. Let me know your thoughts. If this does work, can we remove the flake label and keep this issues as this is not a release blocker for 1.6?

**Comment by gmarek** [comment] 2017-03-09 14:01
@ravisantoshgudimetla - I don't understand which delay in which loop you mean. You added a delay inside the "Try" call? What do you mean by 'run for close 4 hours without terminating'? That the test didn't fail? If so, then I'm all for such solution for stopping the bleeding.

**Comment by ravisantoshgudimetla** [comment] 2017-03-09 14:09
@gmarek , Yes I introduced a sleep like in loop for zone, like https://github.com/ravisantoshgudimetla/kubernetes/blob/nodecontroller_eviction_flake/pkg/controller/node/nodecontroller_test.go#L1262

Yes the test didn't fail but it didn't complete either even after, so I am wondering if this causes timeout in testing infra.

**Comment by gmarek** [comment] 2017-03-09 14:26
It's strange indeed... Do you have any logs for the test by any chance? Adding this delay shouldn't be noticeable, as it just inserts some delay here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/rate_limited_queue.go#L220
Sleeping under the lock is usually not the best idea, but 50 microseconds in test shouldn't make a lot of difference...

**Comment by ravisantoshgudimetla** [comment] 2017-03-09 14:35
Unfortunately no, I can try reproducing this today. Probably by afternoon EST, I can have something, The way I am doing as of now is the way suggested by @ncdc in the comments above. I can redirect that to a file and see. Let me know, if you are ok with approach.

**Comment by gmarek** [comment] 2017-03-09 14:37
I'm OK with anything that produces logs:) I generally do:
```bash
godep go test <bla> -v --alsologtostderr -race -args -v=10
```

**Comment by gmarek** [comment] 2017-03-09 14:40
@ncdc - out of curiosity. How often does this flake?

**Comment by ncdc** [comment] 2017-03-09 14:44
If I run my `while` loop, it takes about 8-10 seconds to flake.

**Comment by ravisantoshgudimetla** [comment] 2017-03-09 14:50
@gmarek @ncdc, I think I made a mistake. I did not take that while true loop out because of which it ran in infinite loop. I am sorry about that.  

It means that with that delay introduced that I mentioned earlier it never failed even after running for 4 hours, which means we got rid of atleast test flakyness. @ncdc, if you can confirm if it is working, I will raise a PR which introduces this delay.

**Comment by liggitt** [comment] 2017-03-09 14:56
giving the ratelimiter time to refill inside the loop is consistent with the theory that https://github.com/kubernetes/kubernetes/issues/39975#issuecomment-273010545 is causing problems.

If the rate limiter runs out of tokens in Try(), it returns with a `// Try again later` comment, but the unit test does not try again later. 

I'm having a hard time following the code to know if non-test invocations have the same problem or if this is just a unit test issue.

**Comment by ncdc** [comment] 2017-03-09 14:59
The sleep addition seems to have helped.

**Comment by gmarek** [comment] 2017-03-09 15:08
It's test only problem: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L520
Runs `Try` in `Until`, so it'll retry in the next round.

I guess the problem here was actually introduces later than what @liggitt suggests - I don't think that the removal of leaky behavior was problematic, but introducing a test that evicts more than one Node. This means that if processing queue is fast enough, then rate limiter fails to reload, so adding the sleep there is actually a correct solution (as long as we don't have good rate limiter mock/testable rate limiter).

**Comment by ravisantoshgudimetla** [comment] 2017-03-09 15:20
@gmarek @ncdc, Thanks for confirmation. I will raise a PR for that now. 

@liggitt As far as I understood, the issue is with unit test. If rate limiter fails to reload for a particular node, it cannot retry(unless the we separate out the logic which tells if the rate limiter has reloaded or not. - if we have that logic we can ask Try to run again by returning a false just like https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L539).

**Comment by liggitt** [comment] 2017-03-16 15:04
Still an issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/43217/pull-kubernetes-bazel/10247/

**Comment by liggitt** [comment] 2017-03-16 15:05
but not a blocker (the test is at fault)

**Comment by ravisantoshgudimetla** [comment] 2017-03-16 20:41
@liggitt Thanks, I will check this out after 1.6 release hopefully, with rewrites..

**Comment by timothysc** [comment] 2017-06-07 15:46
Has there been any recent incidents of this issue?  

It's marked for 1.7.

**Comment by timothysc** [comment] 2017-06-07 15:55
Closing - http://storage.googleapis.com/k8s-gubernator/triage/index.html?text=TestMonitorNodeStatusEvictPodsWithDisruption shows near nothing.

**Comment by ravisantoshgudimetla** [comment] 2017-06-07 16:12
@timothysc - this flakes out sporadically, I was able to reproduce this when debugging on my system, if I run it for long time.

**Comment by kargakis** [comment] 2017-07-15 19:02
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48030/pull-kubernetes-bazel/30316/

**Closed** 2017-07-17 09:31 UTC
Labels: area/nodecontroller, kind/flake, sig/scheduling
