### ISSUE TITLE
The API server omits the `kind` and `apiVersion` attributes for items in collections

### ISSUE THREAD

**Issue by wallrj** [kubernetes/kubernetes#63676] opened 2018-05-10 16:09 UTC
/kind bug

**What happened**:

I expected to be able to see `apiVersion` and `kind` attributes on each item in a collection of resources returned by the REST API server.

**What you expected to happen**:

The top level list had these attributes, but the items did not.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl proxy
```

```
curl --silent http://127.0.0.1:8001/api/v1/namespaces/kube-system/pods/kube-apiserver-kube-master | grep kind
  "kind": "Pod",
```

```
curl --silent http://127.0.0.1:8001/api/v1/namespaces/kube-system/pods | grep kind
  "kind": "PodList",
...
```

**Anything else we need to know?**:

What I really want to be able to do is call `obj.GroupVersionKind()` on an object returned by one of the client-go lister interfaces. Why, for example, can't we call `foo.GroupVersionKind()` here:
 * https://github.com/kubernetes/kubernetes/blob/release-1.10/staging/src/k8s.io/sample-controller/controller.go#L404
...rather than creating a new `schema.GroupVersionKind`

The docs suggest that the items should have these attributes:
 * https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#resources

**Environment**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

- On a https://github.com/Mirantis/kubeadm-dind-cluster

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
...
```

**Comment by liggitt** [comment] 2018-05-10 16:43
duplicate of https://github.com/kubernetes/kubernetes/issues/3030

/close

**Closed by liggitt** 2018-05-10 16:43 UTC
Labels: kind/bug, needs-sig
