### ISSUE TITLE
Admission controllers require insecure port to be open

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#23147] opened 2016-03-17 20:45 UTC
I activated admission controllers in my cluster and started getting this error when deploying kube2sky.

Inferred from the port 0 that it was the apiserver trying to go through an admission controller.

It's not clear if it's supported to disable the insecure port... For now I've simply re-enabled it.

**Comment by colemickens** [comment] 2016-03-17 20:45
```
+ /run/current-system/sw/bin/kubectl --cluster=kube-20160317-105346 --context=kube-20160317-105346 --client-certificate=/home/cole/code/azure/azkube_gopath/src/github.com/colemickens/azkube/_deployments/kube-20160317-105346/client.crt --client-key=/home/cole/code/azure/azku
be_gopath/src/github.com/colemickens/azkube/_deployments/kube-20160317-105346/client.key --certificate-authority=/home/cole/code/azure/azkube_gopath/src/github.com/colemickens/azkube/_deployments/kube-20160317-105346/ca.crt --server=https://kube-20160317-105346.westus.cloud
app.azure.com:6443 create -f skydns.yaml
Error from server: error when creating "skydns.yaml": Internal error occurred: Get http://0.0.0.0:0/api/v1/namespaces/kube-system: dial tcp 0.0.0.0:0: connection refused
Error from server: error when creating "skydns.yaml": Internal error occurred: Get http://0.0.0.0:0/api/v1/namespaces/kube-system: dial tcp 0.0.0.0:0: connection refused
```

**Comment by liggitt** [comment] 2016-03-18 01:27
Dupe of https://github.com/kubernetes/kubernetes/issues/13598

**Closed by liggitt** 2016-03-18 01:27 UTC
