### ISSUE TITLE
Make DNS required (update docs, add conformance test)

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#9107] opened 2015-06-02 08:37 UTC
This issue is a follow on from the discussion in PR #5284 by @piosz where folks like @pires and @eparis @nzwulfin  and maybe @derekwaynecarr complain about changing the key guestbook example to use DNS which makes it a nicer example for Kubernetes deployments that have a DNS add-on but breaks it for other clusters that don't. A very good point was made: the key example that most people try out should work on bare Kubernetes without the need to assume any add-ons services.

Although we can imagine some post 1.0 fixes (e.g. absorb DNS functionality into core Kubernetes @thockin ) I think it is very important to get our examples and documentation in very good shape for the 1.0 release so that everyone has a very good out of the box experience with the key guestbook example for any Kubernetes deployment that we explicitly support.

I propose the following approach for 1.0:
* Produce a variety of guestbook examples which make different assumptions about the type of the Kubernetes deployment.
* Have a `guestbook-bare` example that works without DNS.
* Have a `guestbook-dns` example that works with DNS.
* Have other `guestbook-XXX` examples that work with other Kubernetes deployments that can provide an alternative to our DNS add-on to achieve the same effect.
* Produce a clear matrix in our documentation that explains which example should be run depending on your deployment.
* Make clear at the beginning of the `README.md` for each of the examples the deployment that is expected.
* Perhaps modify the examples to make sure the pre-requisites are available before running e.g. in a Makefile as a pre-check?

@RichieEscarez @bgrant0607

**Comment by piosz** [comment] 2015-06-02 10:26
The problem is that we probably are not able to create `guestbook-base` example that really works without DNS in the current state of the system. We probably don't want to add a new features that would allow this for 1.0. See #4245, #5184.

We may add an example that doesn't require DNS but with comment that this works nondeterministically.

**Comment by nzwulfin** [comment] 2015-06-02 13:45
@piosz  While it may be non-deterministic to rely on ENV variables, and cause the issues you saw in https://github.com/GoogleCloudPlatform/kubernetes/issues/5184, I don't think `./cluster/kubectl.sh create -f examples/guestbook` is the typical way a learning example would be written.  There's a difference between running the complete example in a single run for testing purposes and a user following the steps in a guide to understand the system.  If you follow the steps in the guide manually, with verification as listed, then a non-deterministic version of the guide works.

Labelling as 'non-deterministic' or listing what 'features' are missing or what concerns there are with the approach in the guide are good things overall.  I'm not advocating for new features, but better docs :)

@satnam6502 I'd like to see release version in the matrix.  I don't know what the level of effort to keep all of the examples up to date given 5 releases since April 1 so including the release ver used will at  least provide a starting point to see where issues may arise.

I don't think there needs to be pre-flight checks for stated requirements.  These are learning docs, and if you don't follow them and have issues, start over, redo the examples.  I don't see that as unreasonable.

Maybe I'm getting ahead of the goal, the intent of the examples is to provide a user a good entry point and learning experience to become familiar with different uses of the product.  Is that a true statement?

**Comment by erictune** [comment] 2015-06-02 14:50
What is the problem with putting a blurb at the top that says "requires
DNS.  Most kubernetes distros offer this as an option. if yours doesn't see
[link to skydns docs]."

**Comment by pires** [comment] 2015-06-02 15:29
@erictune DNS and now the service-token thing have broken a lot of examples in the past.

As provider of a _distro_ (Vagrant + CoreOS) that it's meant for simplifying the lives of developers who just want to try Kubernetes and feel the official way is just daunting, I feel stuff like this makes it hard to keep up and has made it particularly painful to maintain the CoreOS documentation. Hell, it's even hard for me to get the `elasticsearch` or `hazelcast` example  (written by me!) to work properly now that you (as in team) decided to deprecate (futurely remove) API read-only support and go with service accounts.

This is just a personal feeling and it probably should just be ignored, but atm I just wish I had wait for 1.0. Or 2.0.

**Comment by eparis** [comment] 2015-06-02 15:43
@erictune So saying DNS is a requirement is ok. But that would need to be the first example and the canonical example. Then again, DNS isn't a good example, because it is both using the cluster and setting up the cluster. Whereas the best example would only be to use....

**Comment by fgrzadkowski** [comment] 2015-06-12 14:05
I think we need a tie-breaker here. I see there are arguments for both using DNS and using env vars. @brendanburns You were looking into many UX related things. WDYT?

**Comment by thockin** [comment] 2015-06-19 23:09
DNS is effectively required at this point.  We're working to make it so that you don't need a special DNS token (in fact due to a bug right now, you don't :).

If we just assume DNS, who is broken?

**Comment by eparis** [comment] 2015-06-19 23:46
@thockin standard answer 'everyone who doesn't use salt'

**Comment by thockin** [comment] 2015-06-20 04:47
Anyone can install DNS, and should - What significant k8s installation
procedures currently omit DNS and do we care to support that operating mode?

**Comment by nzwulfin** [comment] 2015-06-21 21:13
I think the conformance testing talked about in https://github.com/GoogleCloudPlatform/kubernetes/pull/9816 and https://github.com/GoogleCloudPlatform/kubernetes/issues/9717 are steps toward what I'm looking for.  Definitive answers as to what needs to be available at any particular release. 

But this is still test first, is there a plan to make the assumptions in the tests available in a doc?  I don't read Go and I shouldn't have to in order to figure out what a conforming cluster is.  This guide for writers is good (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/writing-a-getting-started-guide.md) but doesn't lay out a "working cluster".  Cluster admin guide doesn't either, and points to the other guides.  

@thockin as a newcomer, i  don't know what constitutes a "significant k8s installation procedure", but most of the guides (which seem to be the most authoritative after salt and the cluster scripts) don't set up DNS.

**Comment by amygdala** [comment] 2015-07-22 19:13
FYI- I've gotten ospo approval to put the images for this app on gcr.  I can create a version that uses envir vars instead of DNS, in the php script that is included in the image. 
One way to do this (w.r.t the overall example setup) could be to have the default image in the frontend.yaml be the DNS version, but add commented-out lines that say 'use this image instead if your cluster does not support the dns service). 
Not sure that's the best approach though.

**Comment by erictune** [comment] 2015-07-30 08:07
I think we should require all implementations to have DNS.  Its just too much work to support multiple types of examples, and it isn't hard to run DNS.   Several non-salt distros run it (for example cluster/libvirt-coreos, cluster/ubuntu).   I think we already decided this somewhere else.  At any rate let's consider it decided.  @thockin 

So, action items:
 - The current conformance test does not test DNS.  I will file an issue to make sure it is added to the v1.1 conformance test.
- The docs/getting-started-guides/scratch.md doesn't describe how to setup DNS.  I'll add instructions there.
- We should ask people to run the conformance test against their clusters as an extended validation if they have problems.  @lavalamp started doing this already.

**Comment by erictune** [comment] 2015-07-30 08:12
xref #12014

**Comment by bprashanth** [comment] 2016-02-16 21:52
So we have a DNS test, but it isn't part of [conformance]. Can we just add it to conformance, modify whatever docs and close this issue (asking for 1.2 triage)? any volunteers?

**Comment by thockin** [comment] 2016-02-17 06:08
There are at LEAST docs to update and getting-started guides to audit.

**Comment by bprashanth** [comment] 2016-02-19 01:42
Alright, we should do that for 1.2.0

**Comment by thockin** [comment] 2016-03-03 22:37
I'm tagging people who own docs that I think (with a very casual glance) don't include DNS as part of cluster turnup.  Please take a look at your docs and either convince me that they do bring up DNS properly and I just missed it, or craft a PR that includes DNS turnup.  I'd love to say DNS is required, but we don't want a bunch of docs that don't tell people how to do that.

@kolyshkin CentOS manual

@errordeveloper CoreOS+Azure

@jeffbean coreOS bare metal

@vallard @kelseyhightower coreOS multinode

@djosborne fedora+calico

@aveshagarwal fedora ansible

@eparis fedora manual

@whit @chuckbutler juju

@derekwaynecarr vagrant

**Comment by djosborne** [comment] 2016-03-03 22:59
@caseydavenport

**Comment by caseydavenport** [comment] 2016-03-03 23:13
@thockin @djosborne I think it is best we just remove the Fedora+Calico guide, at least temporarily.  It is quite outdated and needs a full re-write, but I don't think we have time to get it into a suitable condition for v1.2.

PR: https://github.com/kubernetes/kubernetes/pull/22475

**Comment by derekwaynecarr** [comment] 2016-03-04 00:25
@thockin

Vagrant runs DNS by default

https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/config-default.sh

# Optional: Install cluster DNS.
ENABLE_CLUSTER_DNS="${KUBE_ENABLE_CLUSTER_DNS:-true}"
DNS_SERVER_IP="10.247.0.10"
DNS_DOMAIN="cluster.local"
DNS_REPLICAS=1

**Comment by thockin** [comment] 2016-03-04 00:33
Thanks.

**Comment by chuckbutler** [comment] 2016-03-04 20:15
Hey @thockin  - we don't currently have DNS instructions under the `cluster/juju` instructions. We have however massively renovated the charms and will be landing layers + doc updates for that work within the next week or so. 

Is this soon enough to meet the deadline cutoff for this request?

**Comment by thockin** [comment] 2016-03-04 22:04
That's fine.  Note that docs will actually be moving to a new repo
eventually, but a patch should apply cleanly regardless.

**Comment by bgrant0607** [comment] 2016-03-10 03:05
@thockin Do we have a conformance test for this?

**Comment by thockin** [comment] 2016-03-11 17:17
No, there's a TODO in the e2e for DNS and Vagrant not working.  I am trying to find if that is stale or needs work.

**Comment by ArtfulCoder** [comment] 2016-03-11 18:55
the dns test has certain docker specific tests around pod hostname-via-annotation, which would not work for rkt. 
For conformance, we would need it to work for rkt as well ?

**Comment by thockin** [comment] 2016-03-11 22:11
Maybe we can split out the annotation parts into a separate case and mark the core case as conformance for now?  The annotation/hostname stuff is beta anyway

**Comment by thockin** [comment] 2016-03-14 16:08
@ArtfulCoder do you have time to take this one - I have another priority first part of this week...

**Comment by thockin** [comment] 2016-03-14 18:31
Abhi will look at this for conclusion TODAY

**Comment by bprashanth** [comment] 2016-04-25 21:21
Reopening since http://kubernetes.io/docs/admin/dns/ suggests it's still optional:
```
As of Kubernetes 0.8, DNS is offered as a cluster add-on. If enabled, a DNS Pod 
and Service will be scheduled on the cluster, and the kubelets will be configured to 
tell individual containers to use the DNS Service’s IP to resolve DNS names.
```

**Comment by thockin** [comment] 2016-06-09 17:54
@girishkalele FYI.  This was supposed to be done and then something got missed. :(

**Closed** 2016-08-30 21:04 UTC
Labels: component/dns, priority/P1, team/cluster
