### ISSUE TITLE
Replacing key in StringData secret result in extra key in live object

### ISSUE THREAD

**Issue by souleb** [kubernetes/kubernetes#108008] opened 2022-02-08 13:34 UTC
### What happened?

I have applied a secret

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
```

Then tried to update a key

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username1: admin
  password: t0p-Secret
```

As a result I have

```yaml
apiVersion: v1
data:
  password: dDBwLVNlY3JldA==
  username: YWRtaW4=
  username1: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2022-02-08T13:16:32Z"
  name: secret-basic-auth
  namespace: default
  resourceVersion: "263422"
  uid: d13de652-453b-484b-9c8c-a1d9c3c9d547
type: kubernetes.io/basic-auth
```

### What did you expect to happen?

I expected a key replacement like:

```yaml
```yaml
apiVersion: v1
data:
  password: dDBwLVNlY3JldA==
  username1: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2022-02-08T13:16:32Z"
  name: secret-basic-auth
  namespace: default
  resourceVersion: "263422"
  uid: d13de652-453b-484b-9c8c-a1d9c3c9d547
type: kubernetes.io/basic-auth
```

### How can we reproduce it (as minimally and precisely as possible)?

k apply --server-side=true -f stringdata-secret.yaml

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by apelisse** [comment] 2022-02-08 21:34
This is fundamentally a duplicate of #89938. To be frank, we're not going to solve #89938 and I'm going to go close it now. This feature is broken by design and can't be salvaged. I will suggest you pretend the `stringData` field doesn't exist.

**Comment by stefanprodan** [comment] 2022-02-09 09:12
>  I will suggest you pretend the stringData field doesn't exist.

How about removing `stringData` from the API or at least mark it as deprecated? @souleb and I got to this issue because Flux users do use `stringData` when encrypting secrets with SOPS in Git. What do you suggest we tell our users?

**Comment by stefanprodan** [comment] 2022-05-10 11:07
This can be closed. We've implemented the conversion from `stringData` to `data` in Flux before server-side apply takes over, to workaround this bug.

**Closed** 2022-06-09 11:23 UTC
Labels: kind/bug, sig/api-machinery, lifecycle/rotten, triage/accepted
