### ISSUE TITLE
unit flake: TestAddTwoFireEarly

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25135] opened 2016-05-04 14:30 UTC
--- FAIL: TestAddTwoFireEarly (10.15s)
	delaying_queue_test.go:92: unexpected err: timed out waiting for the condition

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/24164/kubernetes-pull-test-unit-integration/22236/build-log.txt

**Comment by roberthbailey** [comment] 2016-05-08 06:45
@wojtek-t is this fixed?

**Comment by wojtek-t** [comment] 2016-05-08 06:56
I didn't touch this. I've seen it once and I think noone looked into it yet.

**Comment by gmarek** [comment] 2016-05-24 07:24
It's not fixed.

**Comment by dims** [comment] 2016-06-06 19:05
Duplicate of https://github.com/kubernetes/kubernetes/issues/26689 ?

**Comment by deads2k** [comment] 2016-06-06 19:21
> Duplicate of #26689 ?

Yeah, they're the same.  haven't seen a reference since #26700 merged

**Comment by lavalamp** [comment] 2016-06-06 20:41
OK, if it happens again the bot will open a new issue.

**Closed by lavalamp** 2016-06-06 20:41 UTC
Labels: area/test, kind/flake, priority/P1, team/none
