### ISSUE TITLE
kubectl logs does not return logs from master node

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#27173] opened 2016-06-10 07:56 UTC
If are getting logs from a pod running in kube-system namespace on a node, kubectl works fine, e.g.:
```
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs node-problem-detector-v0.1-l95wx --namespace=kube-system
E0610 05:10:45.266116       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-e8rf": <nil>
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs fluentd-cloud-logging-kubernetes-minion-group-zn9x --namespace=kube-system
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs node-problem-detector-v0.1-2b6p3 --namespace=kube-system
E0610 00:38:54.672567       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-zn9x": <nil>
E0610 03:43:21.622643       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-zn9x": <nil>
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs node-problem-detector-v0.1-2b6p3 --namespace=kube-system
E0610 00:38:54.672567       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-zn9x": <nil>
E0610 03:43:21.622643       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-zn9x": <nil>
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs node-problem-detector-v0.1-p9xur --namespace=kube-system
E0610 04:52:21.769221       1 manager.go:130] failed to update node conditions: Operation cannot be fulfilled on nodes "kubernetes-minion-group-qr7u": <nil>
```
However, if we are getting logs from a pod running on master, operation fails, e.g.:
```
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ kubectl logs node-problem-detector-v0.1-zhf4a --namespace=kube-system
Error from server: the server could not find the requested resource ( pods/log node-problem-detector-v0.1-zhf4a)
```

**Comment by jszczepkowski** [comment] 2016-06-10 07:57
CC @fgrzadkowski @piosz @mwielgus

**Comment by dims** [comment] 2016-06-10 12:27
@jszczepkowski : dumb question, if you run "`kubectl describe ds`" "`kubectl describe po`", do you see the pod/daemonset in the correct namespace?

**Comment by yujuhong** [comment] 2016-06-10 16:36
See https://github.com/kubernetes/kubernetes/issues/6428#issuecomment-221042992 and https://github.com/kubernetes/kubernetes/issues/6428#issuecomment-221044285

**Comment by yifan-gu** [comment] 2016-06-10 21:38
subscribe.

**Comment by pwittrock** [comment] 2016-06-15 01:16
Can you confirm if the master has `--enable-debugging-handlers=false` set, or if this is another issue

**Comment by kargakis** [comment] 2016-06-15 08:04
@kubernetes/kubectl

**Comment by jszczepkowski** [comment] 2016-06-15 13:54
@pwittrock 

> Can you confirm if the master has --enable-debugging-handlers=false set, or if this is another issue

Yes, master had `--enable-debugging-handlers=false` set. When switched to `true`, kubectl logs start working for master's pods. So, I guess this is the expected behavior.

**Comment by smarterclayton** [comment] 2016-06-15 13:58
Yes, expected behavior.  `--enable-debugging-handlers` includes things that many people think of as core features (`logs`, `exec`, `attach`).  We probably need to split the flag so you can actually turn off the other ones, or just formalize defending the kubelet more effectively (by turning on the authz checks on the kubelet endpoints and requiring authenticated connections from everyone).

**Comment by pwittrock** [comment] 2016-06-15 17:22
Closing this since it is working as intended.  @smarterclayton is that worth filing an issue for?

**Closed by pwittrock** 2016-06-15 17:22 UTC
Labels: 4 - Done, component/kubectl, priority/P2, team/ux

**Comment by smarterclayton** [comment] 2016-06-15 17:29
I think it is worth opening - this is not the first time someone has turned
that off (thinking they were being secure) and then cutting off the things
they needed to actually run.
