### ISSUE TITLE
Failed to negotiate an api version v1

### ISSUE THREAD

**Issue by DjangoPeng** [kubernetes/kubernetes#35576] opened 2016-10-26 02:45 UTC
Everytime when I run `kubectl version`, I get the error:

```
error: failed to negotiate an api version; server supports: map[], client supports: 
map[authentication.k8s.io/v1beta1:{} componentconfig/v1alpha1:{} extensions/v1beta1:{} 
rbac.authorization.k8s.io/v1alpha1:{} autoscaling/v1:{} batch/v2alpha1:{} v1:{} policy/v1alpha1:{} 
federation/v1beta1:{} authorization.k8s.io/v1beta1:{} batch/v1:{} apps/v1alpha1:{}]
```

Version Info:
- Ubuntu 14.04 64bit
- latest version of k8s master branch
- docker v1.12.1

I login shell with user `dl`, and localhost is `9.91.9.130`.
rbac.yaml

```

---
kind: "ClusterRole"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: "admin"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: ["*"]

---
kind: "ClusterRoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: "admin"
subjects:
  - kind: "User"
    name: "pjt"
roleRef:
  kind: "ClusterRole"
  apiVersion: "rbac.authorization.k8s.io/v1alpha1"
  name: "admin"
```

.kube/config

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://9.91.9.130:8080
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: 2fO8rxXAHZs3OE1H
    username: admin
```

**Comment by zreigz** [comment] 2016-10-26 11:00
I was trying reproduce the issue. First I had to modify `rbac.yaml` file because of validation problems:
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: []
---
kind: "ClusterRoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: admin
subjects:
  - kind: "User"
    name: "pjt"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: admin
```
I was using the latest master branch and I didn't notice any problems

**Comment by ericchiang** [comment] 2016-10-26 18:42
Kinda a dup of https://github.com/kubernetes/kubernetes/issues/26909?

@DjangoPeng what version of Kubernetes are you using?

**Comment by deads2k** [comment] 2016-10-26 19:01
> I was using the latest master branch and I didn't notice any problems

Master automatically creates roles allowing discovery and negotiation and binds them to all users.

**Comment by DjangoPeng** [comment] 2016-10-27 00:58
@ericchiang k8s v1.2.0. I followed the [guide](http://kubernetes.io/docs/getting-started-guides/ubuntu/).

**Comment by ericchiang** [comment] 2016-10-27 01:02
@DjangoPeng RBAC was added in v1.3.0.

**Comment by DjangoPeng** [comment] 2016-10-27 02:45
@ericchiang  I tried v1.3.7 and it has been fixed. but I get a new error:
```
Prepare flannel 0.5.5 release ...
Prepare etcd 3.0.12 release ...
Prepare kubernetes 1.3.7 release ...
...
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
```
My master node is 9.91.9.130.
I get the error when calling `validate-cluster`:
```
The connection to the server 9.91.9.130:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 2 times)
The connection to the server 9.91.9.130:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 1 times)
The connection to the server 9.91.9.130:8080 was refused - did you specify the right host or port?
('kubectl get nodes' failed, giving up)

**Comment by DjangoPeng** [comment] 2016-10-27 05:55
@ericchiang Fixed `connection refused` error.
It caused by an `Unknown admission  plugin:DefaultStorageClass`, which can be found in `kube-apiserver.log`:
```
F1027 11:13:42.690161    7574 plugins.go:143] Unknown admission plugin: DefaultStorageClass
I1027 11:13:42.726486    7702 genericapiserver.go:606] Will report 9.91.9.130 as public IP address.
```
So I deleted `DefaultStorageClass` in [/ubuntu/config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/config-default.sh#L87).  Then, it goes well. 
```
... calling validate-cluster
Found 2 node(s).
NAME         STATUS    AGE
9.91.9.127   Ready     21s
9.91.9.130   Ready     30s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://9.91.9.130:8080
```
And it looks like a same [issue](https://github.com/kubernetes/kubernetes/issues/31726) of juju cluster, which hsa been fixed in that case. But I want to ensure if it's a bug in `ubuntu` case.

BTW, the info `{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}` is still exist, and I don't know how to handle it.

**Comment by liggitt** [comment] 2017-02-14 03:59
Closing this as the original issue has been fixed.

DefaultStorageClass is a valid admission plugin in HEAD

**Closed by liggitt** 2017-02-14 03:59 UTC
Labels: area/kubectl, sig/api-machinery
