### ISSUE TITLE
`kubectl rollout status` should adhere to the Deployment strategy parameters

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#40496] opened 2017-01-25 23:58 UTC
To reproduce it:

1. Have a deployment with deadline seconds specified, wait for it to be complete 
2. Update its pod template to use a bad image 
3. The deployment is still complete even after `progressDeadlineSeconds` has passed, with status.type=Progressing, status.status=True, status.reason=NewReplicaSetAvailable
4. `kubectl rollout status` shows the deployment is still progressing (not failed or complete)

@kargakis

**Comment by kargakis** [comment] 2017-01-26 09:16
Dupe of https://github.com/kubernetes/kubernetes/issues/40207, resolved by https://github.com/kubernetes/kubernetes/pull/40261

**Comment by janetkuo** [comment] 2017-01-27 01:38
@kargakis I can still reproduce this with the fix. Would you take a look? We should also add tests for this scenario

**Comment by kargakis** [comment] 2017-01-27 18:25
@janetkuo I am not able to reproduce anymore on master

**Comment by janetkuo** [comment] 2017-01-27 19:03
Here are the exact steps I ran:

```console 
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4066+0107e93cc61947-dirty", GitCommit:"0107e93cc61947f4ea1c2b867e9d0b495ad0687a", GitTreeState:"dirty", BuildDate:"2017-01-27T18:40:22Z", GoVersion:"devel +4cce27a3fa Sat Jan 21 03:20:55 2017 +0000", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4066+0107e93cc61947-dirty", GitCommit:"0107e93cc61947f4ea1c2b867e9d0b495ad0687a", GitTreeState:"dirty", BuildDate:"2017-01-27T18:40:22Z", GoVersion:"devel +4cce27a3fa Sat Jan 21 03:20:55 2017 +0000", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl run nginx --image nginx 
deployment "nginx" created

$ kubectl rollout status deployment nginx 
deployment "nginx" successfully rolled out

$ kubectl patch deployment nginx -p '{"spec":{"progressDeadlineSeconds":5}}'
"nginx" patched

$ kubectl set image deployment nginx nginx=nginx-bad
deployment "nginx" image updated

$ kubectl rollout status deployment nginx
Waiting for rollout to finish: 0 of 1 updated replicas are available...
(hangs)

$ kubectl describe deployment nginx
... 
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
  Progressing   True    NewReplicaSetAvailable
```

Did I do something wrong?

**Comment by kargakis** [comment] 2017-01-27 20:48
Well, by default you allow 1 maxUnavailable and you run with 1 replica so that means your deployment is complete as soon as the pod is created (no requirement for it to be available). Try tweaking maxUnavailable to 0 and retry what you have.

**Comment by janetkuo** [comment] 2017-01-30 17:48
I see. In this case, `kubectl rollout status` doesn't behave the same as deployment conditions. Should `kubectl rollout status` exit 0 as soon as min available is reached?

**Comment by kargakis** [comment] 2017-01-30 17:55
Yes, I think `kubectl rollout status` should exit based on the strategy parameters. If I don't require any pod as available, the command should exit as soon as my desired num of pods is up

@kubernetes/sig-apps-misc any thoughts? This seems like a bug in `rollout status`.

**Comment by kargakis** [comment] 2017-02-04 14:56
Repurposed the title - I won't be able to get to this anytime soon, @kubernetes/sig-cli-bugs anybody interested in taking a stab at this? Should be fairly easy to fix.

**Comment by AdoHe** [comment] 2017-02-05 08:06
@kargakis please assign this to me, I just go back from my holiday and will have more time to focus on CLI related things.

**Comment by kargakis** [comment] 2017-02-21 13:50
@AdoHe any news on this one? I would like to see it fixed in 1.6.

**Comment by kargakis** [comment] 2017-02-21 14:20
The fix should be pretty simple - make sure `rollout status` exits when d.status.availableReplicas >= d.spec.replicas-maxUnavailable(d).

**Comment by kargakis** [comment] 2017-02-21 14:43
Ok, will submit a fix shortly

**Closed** 2017-03-05 03:35 UTC
Labels: area/kubectl, area/workload-api/deployment, kind/bug, sig/apps, sig/cli

**Comment by kargakis** [comment] 2017-03-05 13:37
We may want to provide a flag for enabling the old behavior.
