### ISSUE TITLE
Errors in second density test runs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#23036] opened 2016-03-16 08:59 UTC
When running Density test second time on the same cluster I'm seeing errors like:

```
E0316 09:56:45.788713   12132 iowatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

cc @wojtek-t @kubernetes/sig-api-machinery

**Comment by fejta** [comment] 2016-03-23 06:13
I'm removing the test-infra label because I don't understand how this is related to the infrastructure at this point.

**Comment by lavalamp** [comment] 2016-03-23 21:06
This is not a very good bug report. Is this reproducible? What component is this even in?

**Comment by gmarek** [comment] 2016-03-23 22:13
It's a line that appears it test, sorry for not being more clear about it. So it's either the test that does something wrong, or API server.

And yes - it is (was a week ago) reproducable by running density test few times on the same cluster.

**Comment by lavalamp** [comment] 2016-03-28 22:22
Does this cause the test to fail?

**Comment by gmarek** [comment] 2016-03-29 07:53
Not reliably.

**Comment by smarterclayton** [comment] 2017-06-01 18:24
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 18:24 UTC
Labels: sig/api-machinery
