### ISSUE TITLE
kube-proxy call iptables-restore every seconds

### ISSUE THREAD

**Issue by fvigotti** [kubernetes/kubernetes#34006] opened 2016-10-04 10:37 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT
**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**: ansible ( custom )
- **Others**: used hyperkube image for kube-proxy 1.4.0 `gcr.io/google_containers/hyperkube:v1.4.0`
```
root     24213  2.4  0.1 719284 88724 ?        Ssl  10:23   0:17 /hyperkube proxy --v=4 --iptables-sync-period=120s --master=http://127.0.0.1:8080 --bind-address=xxx.xxx.xxx.xxx --cluster-cidr=10.200.0.0/16 --proxy-mode=iptables
```

**What happened**:
```

I1004 10:26:30.890678       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1004 10:26:30.907484       1 proxier.go:751] syncProxyRules took 61.631223ms
I1004 10:26:30.907522       1 proxier.go:523] OnEndpointsUpdate took 61.940597ms for 15 endpoints
I1004 10:26:31.913210       1 config.go:99] Calling handler.OnEndpointsUpdate()
I1004 10:26:31.913468       1 proxier.go:758] Syncing iptables rules
I1004 10:26:31.913488       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t filter]

----------------- list of rules  starting by "KUBE-" on *nat table
COMMIT

I1004 10:26:31.956539       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1004 10:26:31.974938       1 proxier.go:751] syncProxyRules took 61.467933ms
I1004 10:26:31.974977       1 proxier.go:523] OnEndpointsUpdate took 61.74503ms for 15 endpoints
I1004 10:26:32.860487       1 config.go:99] Calling handler.OnEndpointsUpdate()
I1004 10:26:32.860823       1 proxier.go:758] Syncing iptables rules
I1004 10:26:32.860848       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t filter]

----------------- list of rules  starting by "KUBE-" on *nat table
COMMIT
```

**What you expected to happen**:
http://kubernetes.io/docs/admin/kube-proxy/ 
says 
` --iptables-sync-period duration                How often iptables rules are refreshed (e.g. '5s', '1m', '2h22m').  Must be greater than 0. (default 30s)`
I've also tried to change to 120s or 2m, nothing changed...
also the documentation is missing the  `-v` param that show these operations.. and this makes debugging even more complicated.. ( one have always to look at the source code )

another things.. I see that [--noflush --counters] , but is this --counter necessary ? and If I want to keep that value increasing.. ?

**How to reproduce it** (as minimally and precisely as possible):
I think that happens normally in all setup.. I have no error logged about the current cluster setup so I suppose is the standard behaviour but I don't know if it's also the desidered 

**Anything else do we need to know**:

**Comment by fvigotti** [comment] 2016-10-05 09:26
HI,
I've also tested on a single brand new ubuntu 16.06 vps , 1 node only , using the commands that are here [http://kubernetes.io/docs/getting-started-guides/kubeadm/] and I see that kube-proxy have the same behaviour.. refresh iptables every seconds ..  It is normal?


```
kubectl --namespace=kube-system get pods 
kubectl --namespace=kube-system logs -f kube-proxy-amd64-gcrwv



I1005 09:24:17.214055       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1005 09:24:17.222216       1 proxier.go:751] syncProxyRules took 29.888233ms
I1005 09:24:17.223491       1 proxier.go:523] OnEndpointsUpdate took 32.391743ms for 4 endpoints
I1005 09:24:17.404944       1 config.go:99] Calling handler.OnEndpointsUpdate()
I1005 09:24:17.404988       1 proxier.go:758] Syncing iptables rules
I1005 09:24:17.404998       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t filter]
I1005 09:24:17.408879       1 healthcheck.go:86] LB service health check mutation request Service: default/kubernetes - 0 Endpoints []
I1005 09:24:17.410686       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t nat]
I1005 09:24:17.412555       1 iptables.go:362] running iptables -C [OUTPUT -t filter -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:17.414542       1 iptables.go:362] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:17.424579       1 iptables.go:362] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:17.438979       1 iptables.go:362] running iptables -N [KUBE-POSTROUTING -t nat]
I1005 09:24:17.441126       1 iptables.go:362] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I1005 09:24:17.443096       1 iptables.go:298] running iptables-save [-t filter]
I1005 09:24:17.445441       1 iptables.go:298] running iptables-save [-t nat]
I1005 09:24:17.448176       1 proxier.go:1244] Restoring iptables rules: *filter
:KUBE-SERVICES - [0:0]
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j REJECT
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j REJECT
COMMIT
*nat
:KUBE-SERVICES - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SEP-WAUCGDKZ7FS22SOS - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x00004000/0x00004000 -j MASQUERADE
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x00004000/0x00004000
-A KUBE-SERVICES -m comment --comment "default/kubernetes:https cluster IP" -m tcp -p tcp -d 100.64.0.1/32 --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --rcheck --seconds 180 --reap -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -s 51.254.xxx.xxx/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --set -m tcp -p tcp -j DNAT --to-destination 51.254.xxx.xxx:443
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
COMMIT
I1005 09:24:17.448421       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1005 09:24:17.456330       1 proxier.go:751] syncProxyRules took 51.339442ms
I1005 09:24:17.456477       1 proxier.go:523] OnEndpointsUpdate took 51.512551ms for 4 endpoints
I1005 09:24:19.201234       1 config.go:99] Calling handler.OnEndpointsUpdate()
I1005 09:24:19.203094       1 proxier.go:758] Syncing iptables rules
I1005 09:24:19.203259       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t filter]
I1005 09:24:19.206964       1 healthcheck.go:86] LB service health check mutation request Service: default/kubernetes - 0 Endpoints []
I1005 09:24:19.209355       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t nat]
I1005 09:24:19.211893       1 iptables.go:362] running iptables -C [OUTPUT -t filter -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.214594       1 iptables.go:362] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.217311       1 iptables.go:362] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.219748       1 iptables.go:362] running iptables -N [KUBE-POSTROUTING -t nat]
I1005 09:24:19.222025       1 iptables.go:362] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I1005 09:24:19.224436       1 iptables.go:298] running iptables-save [-t filter]
I1005 09:24:19.227656       1 iptables.go:298] running iptables-save [-t nat]
I1005 09:24:19.231146       1 proxier.go:1244] Restoring iptables rules: *filter
:KUBE-SERVICES - [0:0]
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j REJECT
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j REJECT
COMMIT
*nat
:KUBE-SERVICES - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SEP-WAUCGDKZ7FS22SOS - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x00004000/0x00004000 -j MASQUERADE
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x00004000/0x00004000
-A KUBE-SERVICES -m comment --comment "default/kubernetes:https cluster IP" -m tcp -p tcp -d 100.64.0.1/32 --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --rcheck --seconds 180 --reap -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -s 51.254.xxx.xxx/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --set -m tcp -p tcp -j DNAT --to-destination 51.254.xxx.xxx:443
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
COMMIT
I1005 09:24:19.231441       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1005 09:24:19.242574       1 proxier.go:751] syncProxyRules took 39.48146ms
I1005 09:24:19.243253       1 proxier.go:523] OnEndpointsUpdate took 41.763344ms for 4 endpoints
I1005 09:24:19.444201       1 config.go:99] Calling handler.OnEndpointsUpdate()
I1005 09:24:19.448492       1 proxier.go:758] Syncing iptables rules
I1005 09:24:19.448614       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t filter]
I1005 09:24:19.449545       1 healthcheck.go:86] LB service health check mutation request Service: default/kubernetes - 0 Endpoints []
I1005 09:24:19.451725       1 iptables.go:362] running iptables -N [KUBE-SERVICES -t nat]
I1005 09:24:19.453553       1 iptables.go:362] running iptables -C [OUTPUT -t filter -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.455406       1 iptables.go:362] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.457302       1 iptables.go:362] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1005 09:24:19.459158       1 iptables.go:362] running iptables -N [KUBE-POSTROUTING -t nat]
I1005 09:24:19.460907       1 iptables.go:362] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I1005 09:24:19.462782       1 iptables.go:298] running iptables-save [-t filter]
I1005 09:24:19.465205       1 iptables.go:298] running iptables-save [-t nat]
I1005 09:24:19.468144       1 proxier.go:1244] Restoring iptables rules: *filter
:KUBE-SERVICES - [0:0]
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j REJECT
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j REJECT
COMMIT
*nat
:KUBE-SERVICES - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SEP-WAUCGDKZ7FS22SOS - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x00004000/0x00004000 -j MASQUERADE
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x00004000/0x00004000
-A KUBE-SERVICES -m comment --comment "default/kubernetes:https cluster IP" -m tcp -p tcp -d 100.64.0.1/32 --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --rcheck --seconds 180 --reap -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment default/kubernetes:https -j KUBE-SEP-WAUCGDKZ7FS22SOS
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -s 51.254.xxx.xxx/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-WAUCGDKZ7FS22SOS -m comment --comment default/kubernetes:https -m recent --name KUBE-SEP-WAUCGDKZ7FS22SOS --set -m tcp -p tcp -j DNAT --to-destination 51.254.xxx.xxx:443
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp -p udp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp -p tcp -d 100.64.0.10/32 --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
COMMIT
I1005 09:24:19.468389       1 iptables.go:339] running iptables-restore [--noflush --counters]
I1005 09:24:19.477296       1 proxier.go:751] syncProxyRules took 28.80923ms
I1005 09:24:19.477425       1 proxier.go:523] OnEndpointsUpdate took 28.956093ms for 4 endpoints
```

**Comment by bprashanth** [comment] 2016-10-08 01:07
No it's not, this is a dupe of https://github.com/kubernetes/kubernetes/issues/26637

**Closed by bprashanth** 2016-10-08 01:07 UTC
Labels: component/kube-proxy, team/cluster
