### ISSUE TITLE
schedule different containers on the same gpu device

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kubernetes#46070] opened 2017-05-19 03:55 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
gpu
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG maybe

**Kubernetes version** (use `kubectl version`):
1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: bare-metal
- **OS** (e.g. from /etc/os-release): ubuntu 
- **Kernel** (e.g. `uname -a`): 4.4
- **Install tools**: kubeadm
- **Others**:

**What happened**:
I submit some gpu job and find out that some different container are using the same gpu
below is the ```nvidia-smi pmon``` output, we can see that device 7 is occupied by process 41470 and 45265, they belong to different container.
![2017-05-19 11 36 10](https://cloud.githubusercontent.com/assets/2142864/26232654/420bf5a8-3c8a-11e7-91b7-125e0682aa11.png)

**What you expected to happen**:
as the doc said https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
**Containers (and pods) do not share GPUs.**

**How to reproduce it** (as minimally and precisely as possible):
find a gpu-enabled cluster and run multiple job based on this yaml

```
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-mnist-example-nvidia1235fd6556
  labels:
    name: gpu-mnist-example-nvidia
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        name: gpu-mnist-example-nvidia
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia-gpu-type
                operator: In
                values:
                - "Tesla-K80"
              - key: nvidia-driver-version
                operator: In
                values:
                - "375.66"
      containers:
      - name: gpu-mnist-example
        image: alexwei/gpu-mnist:0.1.1
        args:
        - python3
        - mnist_deep.py
        - --data_dir=./MNIST_data
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: lib
          readOnly: true
      volumes:
      - name: lib
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/latest
      restartPolicy: Never
```
**Anything else we need to know**:

**Comment by vishh** [comment] 2017-05-19 15:42
that's because you are running your containers as privileged. @cmluciano

**Comment by cmluciano** [comment] 2017-05-19 17:54
I'm not sure if he is. I see 

```
securityContext:
          privileged: false
```

@WIZARD-CXY Are you saying that this job will potentially use the same device when you ran it twice?

**Comment by cmluciano** [comment] 2017-05-19 17:55
/assign

@kubernetes/sig-node-bugs

**Comment by seelam** [comment] 2017-05-19 19:57
cannot pull this image `index.qiniu.com/weiwei/gpu-mnist:0.1.1`.

**Comment by cmluciano** [comment] 2017-05-19 20:38
:smile: I tried that too. I think it might be a private registry.

**Comment by WIZARD-CXY** [comment] 2017-05-22 02:01
@cmluciano Actually there is another gpu trainning container running as command "python 45265", and this job this running as command python3. They are using the same gpu device.

**Comment by WIZARD-CXY** [comment] 2017-05-22 02:03
sorry, my mistake and I will push the image to a public registry.

**Comment by vishh** [comment] 2017-05-22 06:35
@cmluciano I wonder if #46087 might fix this. Can we add test cases for this issue once a repro is available?

**Comment by vishh** [comment] 2017-05-22 06:36
xref #44107

**Comment by WIZARD-CXY** [comment] 2017-05-22 10:15
yaml updated with public image

**Comment by WIZARD-CXY** [comment] 2017-05-22 11:03
I took more time investigating this issue and found that the container inspect result only show one gpu device (/dev/nvidia7) after launching the job.
```
 "Devices": [
                {
                    "PathOnHost": "/dev/nvidia7",
                    "PathInContainer": "/dev/nvidia7",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidiactl",
                    "PathInContainer": "/dev/nvidiactl",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm",
                    "PathInContainer": "/dev/nvidia-uvm",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm-tools",
                    "PathInContainer": "/dev/nvidia-uvm-tools",
                    "CgroupPermissions": "mrw"
                }
            ],

```
But when I exec into this container and use ls command, the output is
```
root@ofifffffoiiiu-mle-idia1235fd66-0lcvs:/dev# ls
core  mqueue            nvidia0  nvidia4  nvidiactl  shm     termination-log
fd    null              nvidia1  nvidia5  ptmx       stderr  tty
full  nvidia-uvm        nvidia2  nvidia6  pts        stdin   urandom
fuse  nvidia-uvm-tools  nvidia3  nvidia7  random     stdout  zero
```
It shows all the devices on the host. Is that normal?

**Comment by cmluciano** [comment] 2017-05-22 16:32
@vishh Yes, I can try to add a test to mimic this behavior, but I think this is caused by two processes running in the same container.

@WIZARD-CXY Can you run a ps inside of that container and grep on python? I think you have both a python and a python3 process running simultaneously in each of these pods. This can be subtle like a python3 init script starting a python process. 

If the above is true, then it would make sense that two processes are sharing the GPU; we segment at the container level.

**Comment by WIZARD-CXY** [comment] 2017-05-23 01:44
@cmluciano negative, they are in two different container,
```
root@training:/workspace# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 May17 ?        00:00:00 /usr/local/bin/dumb-init -- slee
root         8     1  0 May17 ?        00:00:00 /usr/sbin/sshd
root         9     1  0 May17 ?        00:00:00 sleep infinity
root      1273     0  0 May19 ?        00:00:00 bash
root      2411     0  0 May19 ?        00:00:00 bash
root     16075     0 99 May22 ?        5-20:49:03 python mxnet_train.py -f --pre
root     22489     0  0 09:43 ?        00:00:00 bash
root     22500 22489  0 09:43 ?        00:00:00 ps -ef
```

**Comment by cmluciano** [comment] 2017-05-23 17:42
@WIZARD-CXY All devices will be listed if the container is running in privileged mode. I noted 2 arguments that seem relevant in your manifest - python3 and the .py file. 

I am pulling your image locally to try it out.

**Comment by cmluciano** [comment] 2017-05-23 18:15
Unfortunately I could not get this working locally since it requires quite a lot of setup. Can you please detail what those two processes are? You mentioned that the python3 process is running in a different container, but the job only lists one container.

**Comment by WIZARD-CXY** [comment] 2017-05-25 07:18
@cmluciano  the container wasn't running in privileged mode as u said above.
```
securityContext:
          privileged: false
```
The other program is a proprietary ml training program using mxnet. I don't know much about mxnet.

**Comment by WIZARD-CXY** [comment] 2017-05-25 07:28
I will use some simple image and try to reproduce this if possible

**Comment by WIZARD-CXY** [comment] 2017-06-08 03:08
sorry for the late reply, I tried to use the above yaml to deploy gpu pod several times, but it doesn't reproduce the issue, I have to spend more time digging more deeper. I will keep posted

**Comment by dchen1107** [comment] 2017-06-19 16:16
What's the progress on this issue?

**Comment by cmluciano** [comment] 2017-06-19 16:18
Since we have been unable to reproduce this, I think this should be removed from the milestone and closed in 15 days.

**Closed** 2017-07-13 02:40 UTC
Labels: kind/bug, sig/node

**Comment by sharadsingh9** [comment] 2018-01-19 09:13
is it possible to have same nvidia driver installed on multiple docker container on same host ??

**Comment by addozhang** [comment] 2018-12-24 02:43
I think it should be issue with `privileged` setting. I am using a self defined scc which has `privileged` true.  Then multi pod share same gpu.

**Comment by fotstrt** [comment] 2022-03-10 00:11
Hello, 

When I use privileged mode, all Pods are scheduled on the same GPU (although the node has 8 GPUs).
Do you know if I can have both the privileged mode and all pods running on different GPUs?

Thank you!
