### ISSUE TITLE
Enable to remount attachable volumes after reboot the node

### ISSUE THREAD

**Issue by ailusazh** [kubernetes/kubernetes#52397] opened 2017-09-13 07:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

/sig storage

**What happened**:
For pods that with attachable volumes on a node, after reboot the node, and if the pods are not terminated, these volumes will be in the unmounted state because the fstab information doesn't update, and the kubelet will not try to remount these volumes. 

**What you expected to happen**:
After reboot the node, and if the pods are not terminated, the volumes should be remounted.

**How to reproduce it (as minimally and precisely as possible)**:
We should not mark the attachable volumes as mounted when starting kubelet  and reload these volumes, then the reconciler in volumemanager will remount them. And for the situation of just restart kubelet and didn't reboot the node , when reconciler try to remount, the method MountDevice in attacher and SetUp in mounter will check whether the dir is mounted, if already mounted, they will return nil and the mount volume operation will be succeed. So I think this change is feasible.

Just comment out a few lines of code, as follows：
```
func (rc *reconciler) updateStates(volumesNeedUpdate map[v1.UniqueVolumeName]*reconstructedVolume) error {
        ...
        ...

	// Get the list of volumes from desired state and update OuterVolumeSpecName if the information is avaiable
	volumesToMount := rc.desiredStateOfWorld.GetVolumesToMount()
	for _, volumeToMount := range volumesToMount {
		if volume, exists := volumesNeedUpdate[volumeToMount.VolumeName]; exists {
			volume.outerVolumeSpecName = volumeToMount.OuterVolumeSpecName
			volumesNeedUpdate[volumeToMount.VolumeName] = volume
			glog.V(4).Infof("Update OuterVolumeSpecName from desired state for volume (%q): %q",
				volumeToMount.VolumeName, volume.outerVolumeSpecName)
		}
	}

	for _, volume := range volumesNeedUpdate {
		err := rc.actualStateOfWorld.MarkVolumeAsAttached(
			volume.volumeName, volume.volumeSpec, "" /* nodeName */, volume.devicePath)
		if err != nil {
			glog.Errorf("Could not add volume information to actual state of world: %v", err)
			continue
		}

		err = rc.actualStateOfWorld.AddPodToVolume(
			volume.podName,
			types.UID(volume.podName),
			volume.volumeName,
			volume.mounter,
			volume.outerVolumeSpecName,
			volume.devicePath)
		if err != nil {
			glog.Errorf("Could not add pod to volume information to actual state of world: %v", err)
			continue
		}
		//if volume.pluginIsAttachable {
		//	err = rc.actualStateOfWorld.MarkDeviceAsMounted(volume.volumeName)
		//	if err != nil {
		//		glog.Errorf("Could not mark device is mounted to actual state of world: %v", err)
		//		continue
		//	}
		//}
		_, err = rc.desiredStateOfWorld.AddPodToVolume(volume.podName,
			volume.pod,
			volume.volumeSpec,
			volume.outerVolumeSpecName,
			volume.volumeGidValue)
		if err != nil {
			glog.Errorf("Could not add pod to volume information to desired state of world: %v", err)
		}
	}
	return nil
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ailusazh** [comment] 2017-09-13 07:47
@kubernetes/sig-storage-bugs

**Comment by dixudx** [comment] 2017-09-13 08:02
@ailusazh Duplicate of #51982?

**Closed** 2017-09-13 08:10 UTC
Labels: kind/bug, sig/storage
