### ISSUE TITLE
Mirror pods in a delete create loop in version skewed cluster (1.1 master, 1.0 node)

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#15960] opened 2015-10-20 18:15 UTC
Nodes can't recognize the static pods that they create possibly because the defaulting is different.

`IsMirrorPodOf` always returns false. https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/kubelet/pod_manager.go#L255

Here is a json diff of two pod specs before and after they are Semenatic.DeepEqual'd where before is created pod and after is what kubelet things the created pod should be.

![image](https://cloud.githubusercontent.com/assets/1787169/10617027/0c96b3b0-771d-11e5-9f78-e46917c67880.png)

Thus:

```
I1020 18:13:49.326315    3290 server.go:635] GET /healthz: (591.942µs) 0 [[curl/7.26.0] 127.0.0.1:50831]
W1020 18:13:50.396406    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:13:50.653880    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
E1020 18:13:52.325698    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:13:52.796781    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:13:53.456302    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:13:54.403250    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:13:54.650342    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:13:56.200110    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:13:57.062169    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:13:57.796263    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:13:58.305989    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
I1020 18:13:59.333278    3290 server.go:635] GET /healthz: (659.453µs) 0 [[curl/7.26.0] 127.0.0.1:50919]
W1020 18:13:59.796174    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:00.862961    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:01.798992    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:02.301664    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:03.596159    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:04.074172    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:05.396241    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:05.946993    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:07.196129    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:07.868130    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:08.796356    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
I1020 18:14:09.344579    3290 server.go:635] GET /healthz: (1.468086ms) 0 [[curl/7.26.0] 127.0.0.1:51022]
E1020 18:14:09.709632    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:10.797135    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:11.052371    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:12.799715    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:13.054409    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:14.596218    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:14.860010    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:16.395938    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:16.765795    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:18.196084    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:18.454031    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
I1020 18:14:19.365725    3290 server.go:635] GET /healthz: (1.062587ms) 0 [[curl/7.26.0] 127.0.0.1:51117]
W1020 18:14:19.996059    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:20.323381    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:21.796105    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:23.060629    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:23.996402    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:24.258658    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:25.796116    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:26.049641    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
W1020 18:14:27.595879    3290 status_manager.go:80] Failed to updated pod status: error updating status for pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system": pods "fluentd-cloud-logging-k-2-minion-j6nw" not found
E1020 18:14:28.004155    3290 kubelet.go:1252] Deleting mirror pod "fluentd-cloud-logging-k-2-minion-j6nw_kube-system" because it is outdated
```

p0 for triage

@dchen1107 @bgrant0607 @davidopp @ihmccreery @yujuhong

**Comment by mikedanese** [comment] 2015-10-20 20:07
I think the solution is to not apply defaults to mirror pods in the API Server.

**Comment by dchen1107** [comment] 2015-10-20 20:17
Yes,we have to add specific code to API Server to detect the mirror pod, then not apply defaults.

**Comment by yujuhong** [comment] 2015-10-20 20:17
The right fix should be #8683, which we didn't get to before v1.0. I will start on this and at least get it in for v1.1 to prevent future complications.

Since we cannot update the node/kubelet, options are:
 1. As @mikedanese suggests to disable applying defaults to mirror pods as a temporary fix. IIRC, @bgrant0607 was against treating mirror pod differently at the apiserver. Since this is only a workaround, perhaps we can relax the constraint?
 2. Provide a script to update the pod manifest files.

**Comment by bgrant0607** [comment] 2015-10-20 21:01
Disabling defaults has a number of problems:

1. Defaults are version-specific. Conversion may fail if defaults are not applied.
2. Validation may fail if defaults are not applied.
3. Code using defaulted fields assumes default values have been applied.
4. The defaulting pass is not the only place where values can be set, as mentioned in #8683. For instance, if the user were to change the kube-system LimitRange, that would cause the same problem.

This is another case where #1178 would have been useful.

Which gives me another idea. For mirror pods, we could capture the entire metadata+spec provided by the user as an annotation, as we do in the client for kubectl apply, and then we could return that in GET. PUT may not work.

We'd have to resolve the size concerns raised by #15878.

How serious of a problem is this delete-recreate loop?

**Comment by dchen1107** [comment] 2015-10-20 21:10
fluentd pods will never run on those 1.0 nodes once we upgrade master to 1.1 release.

**Comment by dchen1107** [comment] 2015-10-20 21:15
Ok, we are going with approach proposed in #8683. I am closing this issue as dup of #8683

**Comment by yujuhong** [comment] 2015-10-20 21:18
> Which gives me another idea. For mirror pods, we could capture the entire metadata+spec provided by the user as an annotation, as we do in the client for kubectl apply, and then we could return that in GET. PUT may not work.

"entire metadata+spec" in plain text? It'd be hard for kubelet to diff using this. It'd be better to let kubelet store hash of its own choosing so that it can easily compare when there is any change.

> How serious of a problem is this delete-recreate loop?
Every sync period (10s), for every staic pod that's affected, kubelet would delete and create the pod. The impact includes:
 - extra apiserver requests
 - unstable mirror pods (user cannot proper inspect their static pods through apiserver)

**Comment by yujuhong** [comment] 2015-10-20 21:18
> Ok, we are going with approach proposed in #8683. I am closing this issue as dup of #8683

Even with #8663, we can't fix v1.0 kubelet.

**Comment by mikedanese** [comment] 2015-10-20 21:25
Agree with @yujuhong

**Comment by dchen1107** [comment] 2015-10-20 21:27
Yes, I were confused. The comparison is in Kubelet, and we cannot patch 1.0 kubelet in this case.

**Comment by dchen1107** [comment] 2015-10-20 22:17
There are no serious issues with this bug: static pods are running properly, but corresponding mirror pods coming and gone. 

cc/ @roberthbailey Can we treat this as part of GKE cluster upgrade process? Can we upgrade GKE master nodes, then ask the users to upgrade their fluentd yaml file in their cluster? 

For OSS kubernetes users, most likely they won't run into this issue. But we should document this as known issue for 1.1.

**Comment by bgrant0607** [comment] 2015-10-20 22:18
Or can we update the fluentd yaml files when updating the master?

**Comment by dchen1107** [comment] 2015-10-20 23:15
cc/ @kubernetes/goog-gke

**Comment by zmerlynn** [comment] 2015-10-20 23:24
This is a cc @a-robinson issue, really.

But the fast answer is no, because "then ask the users to upgrade their fluentd yaml file in their cluster?" Historically our users are extremely slow to do maintenance.

**Comment by dchen1107** [comment] 2015-10-20 23:32
Our current plan for this issue is just document as a known issue for 1.1 release.

**Comment by mikedanese** [comment] 2015-10-21 17:22
In a 100 node cluster this is going to cause +100 writes +100 deletes per second. Is that extra load a concern?

**Comment by yujuhong** [comment] 2015-10-21 18:19
> In a 100 node cluster this is going to cause +100 writes +100 deletes per second. Is that extra load a concern?

This would be +100 writes +100 deletes every *10* seconds in a 100-node cluster.

We are still discussing options to let user update their manifest files.

**Comment by mikedanese** [comment] 2015-10-21 18:33
Ok, from the logs in the issue description, it looked more frequent but most of the deletes are failing with key not found

**Comment by yujuhong** [comment] 2015-10-21 20:20
> Ok, from the logs in the issue description, it looked more frequent but most of the deletes are failing with key not found

Uh....it's easy to trigger a sync for all pods in kubelet. Any change in any pod would trigger a sync. In this case, the DELETE/ADD of the mirror pod could also trigger another sync. So, yes, it could be worse than 10s...

We are looking at patching this in the apiserver, based on @lavalamp's suggestion.

**Comment by lavalamp** [comment] 2015-10-21 23:04
Yeah, my suggestion is fixing defaulting/conversion/validation as needed to make exceptions for mirror pods.

**Comment by lavalamp** [comment] 2015-10-21 23:07
I'm not 100% sure it's needed, but if necessary we can turn the defaulting fix on in apiserver, and leave it off in scheduler, so that it gets the defaults it expects.

**Comment by dchen1107** [comment] 2015-10-21 23:53
Yeah, it is way more frequent than 10s. I pointed this out to @yujuhong earlier.

We had a meeting with @alex-mohr, and looks like:
* Providing a scripts to convert fluentd yaml file and asking the user to run is not a solution. Our users are very slow on such maintenance work. 
* Piggyback such conversion work on master updating might not a solution for GKE clusters. We do have access to GKE nodes, and we don't do that. To obtain the permission to run script and sync a file requires more work from PM side.

This is a API backward compatibility issue anyway. Given today's version management policy, we should handle such compatibility issue. 

I checked our default code: 
* request diff was introduced by https://github.com/kubernetes/kubernetes/pull/12035. 
* TerminationGracePeriodSeconds was introduced along with graceful termination support. 
* There is no conversion for both fields
* There is no validation checking both fields today

I think it is safe to disable such defaulting for mirror pods shouldn't cause any issue for 1.1 release. Sending PR shortly.

**Comment by yujuhong** [comment] 2015-10-22 00:13
In order to not break the v1.1+ kubelet (which applies newer defaults), we should only skip defaulting for pods from pre-v1.1 kubelets.

An easy way to do this is to reuse #15983, which changes the mirror key annotation value from "mirror" to the hash of the pod manifest file. In short, if the key exists, it's a mirror pod. If the value is "mirror", it is sent by a pre-v1.1 kubelet. Otherwise, it's sent by a v1.1+ kubelet. 

Note that we will also need to maintain the special defaulting case for the future releases until we drop support for v1.0 nodes.

**Comment by bgrant0607** [comment] 2015-10-22 00:46
Just this morning, we discussed providing a script/tool to update static pod configs for people with large clusters. Why have we changed that plan?

Any hack in apiserver is going to be confusing and fragile. For instance, a LimitRange installed for kube-system would defeat the hack.

If we were to add a hack in apiserver, we'd need to remove it in 1.2.

**Comment by yujuhong** [comment] 2015-10-22 00:54
@bgrant0607, we talked to @alex-mohr and the conclusion was that node update may not be feasible as @dchen1107 [summarized above] (https://github.com/kubernetes/kubernetes/issues/15960#issuecomment-150056622).

I agree that any apiserver fix is hacky and fragile, but it seems the most viable option right now.

> If we were to add a hack in apiserver, we'd need to remove it in 1.2.

We would need to carry this fix in apiserver as long as GKE supports v1.N master + v1.0 node, unless we can make updating the configs part of the cluster upgrade process.

**Comment by bgrant0607** [comment] 2015-10-22 01:11
Ah. These fields are problems because they existed in 1.0, but weren't used nor populated. Entirely new fields are silently dropped during decoding.

We should cherrypick the solution into 1.0.7, since it appears there will be one.

**Comment by bgrant0607** [comment] 2015-10-22 01:16
That is, we should cherrypick  #15983 into the 1.0 branch.

**Comment by bgrant0607** [comment] 2015-10-22 01:34
Ref.  https://github.com/kubernetes/kubernetes/issues/4855#issuecomment-99565465

**Comment by bgrant0607** [comment] 2015-10-22 01:58
If the hack is going to remain indefinitely, I'm not comfortable circumventing defaulting, conversion, and validation.

**Comment by bgrant0607** [comment] 2015-10-22 01:59
Just not performing the defaulting for these specific fields on just mirror pods seems safer.

**Comment by bgrant0607** [comment] 2015-10-22 02:03
In particular, I could easily imagine a new version of the pod API in 1.2 or 1.3, which will require defaulting and conversion to be applied, in general.

**Comment by ihmccreery** [comment] 2015-10-22 11:47
> We would need to carry this fix in apiserver as long as GKE supports v1.N master + v1.0 node, unless ...

We'll be discussing this soon after 1.1 lands, I expect.  My proposal would be for v1.N masters to support v1.N-1 and v1.N-2 (and maybe v1.N-3) nodes.  That gives users 6-9 months to lag their nodes behind their masters.  But it warrants much further discussion.

> We should cherrypick the solution into 1.0.7, since it appears there will be one.

This isn't a viable solution either, because we can't depend on users updating their nodes to the latest 1.0 rev.  We expect arbitrary 1.0 nodes to work, including 1.0.6 all the way back to 1.0.1, per our current [upgrades policy](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades).

**Comment by lavalamp** [comment] 2015-10-22 17:50
@bgrant0607 As Ike noted, cherrypicking into 1.0 kubelets is not feasible for solving this, because the whole reason for the problem is that people aren't updating their nodes.

The conversion fix in #16080 is much preferable to the defaulting fix: it's less brittle, and components that need the defaulting (e.g. scheduler) will see the defaulting (because they run the conversion stack themselves), but on the wire the mirror pods from old kubelets will remain undefaulted.

**Comment by bgrant0607** [comment] 2015-10-22 19:32
I didn't say cherrypicking into 1.0 would solve the problem for everything. The behavior in 1.0 is pretty broken, even when not considering upgrade. We have a fix. We should cherrypick it into 1.0.

**Comment by bgrant0607** [comment] 2015-10-22 20:03
@lavalamp I don't see how different components would see different values for these fields, assuming they are all updated to the new code.

As discussed offline, the scheduler and node controller need to handle cases of empty requests and pod termination for 1.0 kubelets, anyway, so I think the conversion approach is fine. Please put the explanation in code comments, though, not just in issue/PR comments.

**Comment by lavalamp** [comment] 2015-10-22 20:58
@bgrant0607 Since the conversion stack does the defaulting at the end and runs in every component, and scheduler, node-controller, etc all consume *api.Pod objects (instead of *v1.Pod objects), they will have a view of the object with the fields defaulted. The conversion based fix essentially retains the defaulting in *api.Pod objects, but undoes it in any serialized representation of the object. Over the wire the defaulting will not be baked in to the object.

Older clients that have not been recompiled (including these kubelets) would see a version of the object without the fields being defaulted.

**Comment by bgrant0607** [comment] 2015-10-22 22:09
Defaulting is run first:
```
func (c *Converter) convert(sv, dv reflect.Value, scope *scope) error {
	dt, st := dv.Type(), sv.Type()
	// Apply default values.
	if fv, ok := c.defaultingFuncs[st]; ok {
		if c.Debug != nil {
			c.Debug.Logf("Applying defaults for '%v'", st)
		}
		args := []reflect.Value{sv.Addr()}
		fv.Call(args)
	}

	// Convert sv to dv.
	if fv, ok := c.conversionFuncs[typePair{st, dt}]; ok {
		if c.Debug != nil {
			c.Debug.Logf("Calling custom conversion of '%v' to '%v'", st, dt)
		}
		return c.callCustom(sv, dv, fv, scope)
	}
	if fv, ok := c.generatedConversionFuncs[typePair{st, dt}]; ok {
		if c.Debug != nil {
			c.Debug.Logf("Calling custom conversion of '%v' to '%v'", st, dt)
		}
		return c.callCustom(sv, dv, fv, scope)
	}

	return c.defaultConvert(sv, dv, scope)
}
```

**Comment by lavalamp** [comment] 2015-10-22 23:03
Oh, you're right, I somehow had that backwards in my head. Sorry, everyone. I think that tilts me back in favor of #16078.

This means that defaulting is part of the versioned structs and therefore changing the defaulting is an API breaking change, which we claimed we wouldn't do. Can we change our minds about the defaulting? How about moving this particular defaulting into conversion functions, which is the intended way of doing something like this?

**Comment by yujuhong** [comment] 2015-10-22 23:35
> Oh, you're right, I somehow had that backwards in my head. Sorry, everyone. I think that tilts me back in favor of #16078.

In #16080, we only reset the defaults when converting api.Pod to v1.Pod. Shouldn't all components still see the defaulting values?

> This means that defaulting is part of the versioned structs and therefore changing the defaulting is an API breaking change, which we claimed we wouldn't do. Can we change our minds about the defaulting? How about moving this particular defaulting into conversion functions, which is the intended way of doing something like this?

Agreed that this is an API breaking change.

Perhaps we should not change the defaults at all?

@bgrant0607 mentioned in https://github.com/kubernetes/kubernetes/issues/15960#issuecomment-150340063 that scheduler already deals with empty requests. It's true in [priorities.go](https://github.com/kubernetes/kubernetes/blob/53ae56f2052160e7b790f87b62206db1eb092d2f/plugin/pkg/scheduler/algorithm/priorities/priorities.go#L57), but seems untrue in [predicates.go](https://github.com/kubernetes/kubernetes/blob/7372e18e0210a3672f0ee275f0c8b63112dc7004/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L120). Maybe this should be fixed.

As for `TerminationGracePeriodSeconds`, we can also ask kubelet to apply a default value if we truly on to have the 30 second dfault.

**Comment by bgrant0607** [comment] 2015-10-23 00:15
resources.requests and terminationGracePeriodSeconds are effectively newly added fields, so setting defaults is not a breaking change for most clients. If Kubelet were comparing the pre-decoded pods returned by apisever, it would barf on every new field we've added. It's an accident of the implementation that it broke on exactly these fields.

**Comment by bgrant0607** [comment] 2015-10-23 00:22
Actually, neither priorities nor predicates takes values from limits any longer. That code is rely on the defaulting pass to copy limits to requests in the case that the requests field is absent. We would need to change that, yes, if we were to not set requests for the 1.0 mirror pods.

**Comment by bgrant0607** [comment] 2015-10-23 00:29
This Kubelet behavior was known to be broken back in May:
https://github.com/kubernetes/kubernetes/issues/8642#issuecomment-104670009

What we're trying to do now is figure out a workaround for this broken behavior.

My recommended solution is:
1. Do not set resources.requests and terminationGracePeriodSeconds to non-nil values for just 1.0 mirror pods. All other fields and all other pods, including 1.1 mirror pods, should have default values set normally. Doing this in the defaulting pass makes the most sense, assuming that it's straightforward to do given the structure of that pass.
2. Update the scheduler fit and priority functions to use limits for pods where requests are entirely absent.
3. Ensure that the new code in the node controller to handle termination of pods on 1.0 kubelets deals with unset terminationGracePeriodSeconds appropriately.
4. File a kind/workaround-removal issue to remove these hacks once we don't need to worry about 1.0 kubelets.

**Comment by lavalamp** [comment] 2015-10-23 00:34
Just for comparison, an alternative:

1. Remove this default setting from the defaulting function.
2. Add it to the conversion function instead.
3. For mirror pods from 1.0 kubelets (MPF1K), store the original value in an annotation.
4. For MPF1K, when converting *to* v1, restore the original value & remove the annotation.

No changes needed anywhere else in the system, maintenance cost is very low, we can carry this as long as needed.

**Comment by bgrant0607** [comment] 2015-10-23 00:37
@lavalamp I don't see how that keeps the default values off the wire.

**Comment by bgrant0607** [comment] 2015-10-23 00:41
Actually, I think I see. Yes, I think that could work.

**Comment by lavalamp** [comment] 2015-10-23 00:42
The defaults are added on the v1->internal transition, and removed on the internal->v1 transition.

**Comment by bgrant0607** [comment] 2015-10-23 00:42
(3) is converting v1 to IR, and (4) is converting IR to v1, either for storing to etcd or to communicate to another component, such as Kubelet.

**Comment by lavalamp** [comment] 2015-10-23 00:42
I'm saying stop using the default setting code for setting these "breaking" defaults.

**Comment by lavalamp** [comment] 2015-10-23 00:43
Right.

**Comment by bgrant0607** [comment] 2015-10-23 00:43
I don't think we want to do this for pods in general, though, just for MPF1K

**Comment by lavalamp** [comment] 2015-10-23 00:44
So I think we can actually just add a few more changes to @yujuhong's PR and it should work. (Just move the defaulting.)

**Comment by lavalamp** [comment] 2015-10-23 00:45
Yes, I agree. Just for MPF1K. We can easily broaden it if needed.

**Comment by bgrant0607** [comment] 2015-10-23 00:46
SGTM

**Comment by bgrant0607** [comment] 2015-10-23 00:46
We're going to want to do something similar for new fields added to alpha API versions that we don't want to expose in the stable, serialized version of the API.

**Comment by bgrant0607** [comment] 2015-10-23 00:47
So if this works, we should add it to api_changes.md.

**Comment by lavalamp** [comment] 2015-10-23 00:50
Yes. *Changing defaults* is a breaking change and therefore needs to happen in conversion. Adding new fields with new defaults is fine, just not changing the behavior of existing fields.

...of course I do think kubelet is being a very inflexible client here, but we can't fix the stuff that's already out there.

**Comment by yujuhong** [comment] 2015-10-23 00:58
> Yes. Changing defaults is a breaking change and therefore needs to happen in conversion. Adding new fields with new defaults is fine, just not changing the behavior of existing fields.
> 
> ...of course I do think kubelet is being a very inflexible client here, but we can't fix the stuff that's already out there.

+1 to both points. We should've patched kubelet sooner to avoid this, but it's out there and kubelet 1.0 remains a stubborn client. Sorry for that.

@lavalamp, @bgrant0607, thanks for coming up with the solution! Since both of you agreed on https://github.com/kubernetes/kubernetes/issues/15960#issuecomment-150395303, I will change my PR acoordingly.

**Comment by bgrant0607** [comment] 2015-10-23 14:06
So that there is no misunderstanding that leads to future such problems: Whether fields are new or pre-existing, it is an invalid assumption that unset fields may not be changed, whether by defaulting or by some other process, such as admission control.

**Comment by davidopp** [comment] 2015-10-27 22:47
This issue will be considered fixed for 1.1 once #16080 is submitted. (I didn't read this thread carefully enough yet to know whether additional work is necessary before considering this whole issue closed.)

**Comment by yujuhong** [comment] 2015-10-27 22:56
Update: #16080 has just been merged. Closing the issue.

**Comment by davidopp** [comment] 2015-10-27 23:01
Probably we should not close this issue until we do a cherrypick?

**Comment by piosz** [comment] 2015-10-28 08:52
The change was cherrypicked, so closing this issue

**Closed by piosz** 2015-10-28 08:52 UTC
Labels: area/api, area/upgrade, cherrypick-candidate, priority/P0, team/control-plane, team/node
