### ISSUE TITLE
Support init containers per deployment

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#36477] opened 2016-11-09 06:06 UTC
The current behavior of init containers is to run a set of init containers for every pod.

It would be nice if the behavior could be extended so that we can define a set of init containers for a deployment. This would be extremely useful if we have an app that talks to a database and would need to run database migrations or perform some action or task exclusively for the whole deployment during startup. We can then run these tasks in an init container, but only in 1 container per deployment.

**Comment by kargakis** [comment] 2016-11-09 11:27
@kubernetes/deployment @smarterclayton

**Comment by kargakis** [comment] 2016-11-09 11:27
Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/14512

**Closed by kargakis** 2016-11-09 11:27 UTC
Labels: component/kubelet, team/node
