### ISSUE TITLE
kubelet ended up running 2 POD containers for one manifest file

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15186] opened 2015-10-06 22:22 UTC
* SSH to master, edit a manifest file, observe changes
* kube-push
* SSH to master and see this:

```
thockin@kubernetes-master:~$ sudo docker ps | grep apiserv
73765927a94e        gcr.io/google_containers/pause:0.8.0                                                "/pause"                 12 minutes ago      Up 12 minutes                           k8s_POD.7be6d81d_kube-apiserver-kubernetes-master_kube-system_c90459f7ee07cfbc7e54e3a074c0895a_08dadf3f
dc9aac6eb2eb        gcr.io/google_containers/kube-apiserver:4b392aa99e91cfa7d7011e79a01f587a            "/bin/sh -c '/usr/loc"   20 minutes ago      Up 20 minutes                           k8s_kube-apiserver.2dfe3cf7_kube-apiserver-kubernetes-master_kube-system_59560f52e0c419aed6aa233f28fadde8_21b08c76
40cb44ebf32d        gcr.io/google_containers/pause:0.8.0                                                "/pause"                 6 hours ago         Up 6 hours                              k8s_POD.7be6d81d_kube-apiserver-kubernetes-master_kube-system_59560f52e0c419aed6aa233f28fadde8_8fcf2b79
```

Note that there are two POD containers running for kube-apiserver-kubernetes-master_kube-system

@yujuhong

**Comment by thockin** [comment] 2015-10-06 22:28
From kubelet log:

```
I1006 22:22:11.476905    7050 manager.go:1976] Back-off 5m0s restarting failed container=kube-scheduler pod=kube-scheduler-kubernetes-master_kube-system
I1006 22:22:11.490434    7050 manager.go:1976] Back-off 5m0s restarting failed container=kube-controller-manager pod=kube-controller-manager-kubernetes-master_kube-system
I1006 22:22:11.493936    7050 manager.go:1976] Back-off 2m40s restarting failed container=kube-apiserver pod=kube-apiserver-kubernetes-master_kube-system
```

**Comment by yujuhong** [comment] 2015-10-06 22:34
kubelet does not delete any pods running on the master because of #15122.

**Comment by yujuhong** [comment] 2015-10-06 23:52
Closing this issue since we've already confirmed the cause #15122

**Closed by yujuhong** 2015-10-06 23:52 UTC
Labels: component/kubelet, team/node
