### ISSUE TITLE
Timeout attaching/mounting volume

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#28962] opened 2016-07-14 15:49 UTC
Deployment/Service manifest:

```

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:0.19.2
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

logs from events:

```
2m         31m         14        prometheus-210570969-bqkbd                   Pod                                     Warning   FailedMount               {kubelet ip-10-66-10-42.eu-west-1.compute.internal}       Unable to mount volumes for pod "prometheus-210570969-bqkbd_default(b03d4cc7-49d5-11e6-8d0f-02468703b623)": timeout expired waiting for volumes to attach/mount for pod "prometheus-210570969-bqkbd"/"default". list of unattached/unmounted volumes=[data]
2m         31m         14        prometheus-210570969-bqkbd                   Pod                                     Warning   FailedSync                {kubelet ip-10-66-10-42.eu-west-1.compute.internal}       Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "prometheus-210570969-bqkbd"/"default". list of unattached/unmounted volumes=[data]
```

In aws, the volume is attached,

On the box:

```
core@ip-10-66-10-42 ~ $ ls -ltr /dev/xvdb*
brw-rw---- 1 root disk 202, 13312 Jul 14 15:15 /dev/xvdba
brw-rw---- 1 root disk 202, 13568 Jul 14 15:15 /dev/xvdbb
```

In `/proc/mounts` only one is mounted:

```
core@ip-10-66-10-42 ~ $ cat /proc/mounts | grep xvdb
/dev/xvdbb /var/lib/rkt/pods/run/58129cda-9746-4723-816c-e4fbfee90d3c/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-1a/vol-7c5014ff ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-1a/vol-7c5014ff ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/rkt/pods/run/58129cda-9746-4723-816c-e4fbfee90d3c/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/b038c2e6-49d5-11e6-8d0f-02468703b623/volumes/kubernetes.io~aws-ebs/pvc-562db436-49b4-11e6-8d0f-02468703b623 ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/kubelet/pods/b038c2e6-49d5-11e6-8d0f-02468703b623/volumes/kubernetes.io~aws-ebs/pvc-562db436-49b4-11e6-8d0f-02468703b623 ext4 rw,seclabel,relatime,data=ordered 0 0
```

Where can I debug this further?

**Comment by Quentin-M** [comment] 2016-07-19 13:46
+1

**Comment by saad-ali** [comment] 2016-07-19 18:22
@Zapadlo Take a look at the `/var/log/kube-controller-manager.log` on your master for events related to your volume `prometheus`. That will show you when the volume was attached/detached. It appears that your volume attached without issue so there should be nothing unusual here.

Then take a look at `/var/log/kubelet.go` on the node that the volume is supposed to be attached to. Looks for the UID of your pod (`b03d4cc7-49d5-11e6-8d0f-02468703b623`).  I suspect one of your mounts is failing. It looks like you are using hyperkube so it might be a mount namespace propagation issue.

**Comment by urzds** [comment] 2016-08-19 13:17
I *believe* this happens when the RC/Pod is being created shortly after the PV or PVC. The latter two appear to need several seconds to be fully available (even if the status is already set to "Bound").

I ran into the same issue with a NFS PV. When I delete and create PV+PVC+SVC+RC all in one go, the associated Pod will be in ContainerCreating state for several seconds (>10,<60), then log the warning event `timeout expired waiting for volumes to attach/mount for pod` and afterwards be created without any problems or further delays. When I first create PV+PVC, wait for several seconds (>30) and only then create SVC+RC, the pod will be created immediately and no warning event will be logged.

**Comment by saad-ali** [comment] 2016-08-19 18:10
Thanks for digging into it @urzds!

The capacity 0 issue (https://github.com/kubernetes/kubernetes/issues/29425) was fixed by PR https://github.com/kubernetes/kubernetes/issues/29982 and is in v1.3.5.

>I believe this happens when the RC/Pod is being created shortly after the PV or PVC. The latter two appear to need several seconds to be fully available (even if the status is already set to "Bound").
> 
>  I ran into the same issue with a NFS PV. When I delete and create PV+PVC+SVC+RC all in one go, the associated Pod will be in ContainerCreating state for several seconds (>10,<60), then log the warning event `timeout expired waiting for volumes to attach/mount for pod` and afterwards be created without any problems or further delays. When I first create PV+PVC, wait for several seconds (>30) and only then create SVC+RC, the pod will be created immediately and no warning event will be logged.

This is more or less expected behavior. The mount logic has exponential backoff so if it rapidly encounters PVC/PV does not exist, it'll back off the retries resulting in a longer mount time. We can consider optimizing this particular scenario. But I'll lower the priority on this for now and remove the milestone.

**Comment by urzds** [comment] 2016-08-19 18:18
Maybe the "Bound" status could be delayed, so the RC would be held back for a while and be scheduled only when the PVC is actually ready?

**Comment by saad-ali** [comment] 2016-08-19 18:24
I don't think the RC actually waits for PVC to be bound before scheduling.

**Comment by dove-young** [comment] 2016-12-20 03:08
I got the same problem in GlusterFS + Heketi environment. Kubernetes version is 1.4.5, baseOS is CenOS 7

```
uname -a
Linux tivsun01.cn.ibm.com 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

glusterd --version
glusterfs 3.7.17 built on Nov  3 2016 14:29:48
Repository revision: git://git.gluster.com/glusterfs.git
Copyright (c) 2006-2013 Red Hat, Inc. <http://www.redhat.com/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.

heketi -version
Heketi 2.0.6
```

```
kubectl describe po zookeeper-one-5awt4
Name:           zookeeper-one-5awt4
Namespace:      default
Node:           02.my.host/my-ip-address
Start Time:     Tue, 20 Dec 2016 10:51:41 +0800
Labels:         app=zookeeper
                daemon=zookeeper-one
Status:         Pending
IP:
Controllers:    ReplicationController/zookeeper-one
Containers:
  zookeeper-one:
    Container ID:
    Image:              nc9042036048.my.host/atlas/zookeeper:3.4.6
    Image ID:
    Ports:              2888/TCP, 3888/TCP, 2181/TCP
    Command:
      bash
      /tmp/zoo/start-zookeeper.sh
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /tmp/zoo from start-zookeeper (rw)
      /var/lib/zookeeper from zoo-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ie5gh (ro)
    Environment Variables:
      MYID:     1
      POD_IP:    (v1:status.podIP)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  zoo-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  zoo-data-zookeeper-1
    ReadOnly:   false
  start-zookeeper:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       start-zookeeper
  default-token-ie5gh:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-ie5gh
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  7m            7m              1       {default-scheduler }                            Normal          Scheduled       Successfully assigned zookeeper-one-5awt4 to 02.my.host
  5m            1m              3       {kubelet 02.my.host}                   Warning         FailedMount     Unable to mount volumes for pod "zookeeper-one-5awt4_default(3ef59024-c65f-11e6-8e8a-000c29a1790c)": timeout expired waiting for volumes to attach/mount for pod "zookeeper-one-5awt4"/"default". list of unattached/unmounted volumes=[zoo-data]
  5m            1m              3       {kubelet 02.my.host}                   Warning         FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "zookeeper-one-5awt4"/"default". list of unattached/unmounted volumes=[zoo-data]
  ```


```
kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
zoo-data-zookeeper-1   Bound     pvc-a4b8462d-c65e-11e6-8e8a-000c29a1790c   2Gi        RWO           14m
zoo-data-zookeeper-2   Bound     pvc-a4c05137-c65e-11e6-8e8a-000c29a1790c   2Gi        RWO           14m
zoo-data-zookeeper-3   Bound     pvc-a4c9acdf-c65e-11e6-8e8a-000c29a1790c   2Gi        RWO           14m
[root@01 init_scripts]#
[root@01 init_scripts]# kubectl describe pvc zoo-data-zookeeper-1
Name:           zoo-data-zookeeper-1
Namespace:      default
Status:         Bound
Volume:         pvc-a4b8462d-c65e-11e6-8e8a-000c29a1790c
Labels:         daemon=zookeeper-one
Capacity:       2Gi
Access Modes:   RWO
```

**Comment by valentin2105** [comment] 2017-01-09 22:03
I have also this problem using deployment with HELM,

I deploy all my pv,pvc,deploy,svc in one Charts, and my pod who requiere a volume from the PVC get scheduled and stay in ContainerCreating mode. I need to wait minutes or delete pods for they correctly get rescheduled using the volume. 

Here is the log when the pod get automaticly deleted (after minutes) : 
```
FailedMount    Unable to mount volumes for pod "php-apache-1230339418-mdw5t_f31f061b030bd9b86e8174b3a5031d92(60783e75-d6b2-11e6-bf73-aa0000e9626c)": timeout expired waiting for volumes to attach/mount for pod "php-apache-1230339418-mdw5t"/"f31f061b030bd9b86e8174b3a5031d92". list of unattached/unmounted volumes=[web-folder]
```

It would be awesome if the deployment or RC wait for the PVC to be bound before schedule !

**Comment by codablock** [comment] 2017-01-26 17:31
https://github.com/kubernetes/kubernetes/pull/40531 may slightly improve this situation as the maximum backoff time of 2 minutes will not fire anymore.

**Closed** 2017-07-12 03:00 UTC
Labels: area/platform/aws, priority/backlog, sig/aws, sig/storage, team/cluster (deprecated - do not use)

**Comment by Freyert** [comment] 2018-11-26 17:37
Reading from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/870#issuecomment-416883355 the new solution is:

> The issue with NVMe is a kops issue rather than a jupyter issue.
> 
> The workaround for it is to switch the kops os image to debian stretch where NVMe support has been added.
> 
> ```
> image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08
> ```
> - jacobtomlinson
