### ISSUE TITLE
Need to validate the value of resources in pod spec

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/kubernetes#64083] opened 2018-05-21 08:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
if the value of memory for  one pod is just set to 2, the pod will always stay in state of "containerCreating" as kubelet failed to  create sandbox and keeps creating sandbox.
**What you expected to happen**:
we need validate the value of memory and cpu once creating one new pod object for enhancement.
**How to reproduce it (as minimally and precisely as possible)**:
creating one pod with the value of memory set to 2

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
/kind feature
/kind enhancement

**Comment by liggitt** [comment] 2018-05-21 14:11
duplicate of #54567, #64011

/close

**Closed** 2018-05-21 14:12 UTC
Labels: area/apiserver, kind/enhancement, kind/feature, needs-sig
