### ISSUE TITLE
Support namespaced CRD

### ISSUE THREAD

**Issue by CindyXing** [kubernetes/kubernetes#83413] opened 2019-10-02 17:57 UTC
**What would you like to be added**:
Support namesapced CRD and CRD controller

**Why is this needed**:
Currently CRD and its related controllers are cluster wide. There are scenarios which need them be namespaced. 

- Different tenants on the cluster want to manage their own CRD types/objects and controllers
- Helm hit issues when charts share the same CRD dependency

**Comment by liggitt** [comment] 2019-10-03 02:45
duplicate of https://github.com/kubernetes/kubernetes/issues/65551

Thanks for the feature request, but this would involve a fundamental change to the kubernetes type system, API structure, and cluster-level controllers that operate on types across namespaces, and is unlikely to make progress as an issue. See more details at https://github.com/kubernetes/kubernetes/issues/65551#issuecomment-400909534

If you are interested in pursuing this, I would suggest adding it to the agenda for discussion at the [next SIG API-Machinery meeting](https://github.com/kubernetes/community/tree/master/sig-api-machinery#meetings), or if you would like to propose a concrete design for solving those issues, you may open a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/tree/master/keps/#kubernetes-enhancement-proposals-keps) to get feedback.

/sig api-machinery
/close

**Closed by liggitt** 2019-10-03 02:45 UTC
Labels: kind/feature, needs-sig, sig/api-machinery
