### ISSUE TITLE
Declarative update of a configmap from the contents of a file

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/kubernetes#30337] opened 2016-08-10 02:47 UTC
I'm trying to integrate configmaps into our continuous delivery flow. It's important for us that the deploys are idempotent.

Typically we'd create the configuration from files by doing
`kubectl create configmap myconfig --from-file=file1.yml --from-file=file2.yml`

However, if this is run more than once we get this since the command is a create
`Error from server: configmaps "myconfig" already exists`

There are `apply` and `replace` commands for file or stdin resources but no `apply configmap`. We could grab all the contents of each file and pipe that into a resource YML then pass that through to `apply` but it seems awkward.

What is the current accepted practice for updating a configmap that is file driven?

There is some overlap with this and https://github.com/kubernetes/kubernetes/issues/24744 plus https://github.com/kubernetes/kubernetes/issues/22368.

**Comment by pwittrock** [comment] 2016-08-10 21:12
cc @pwittrock

@erictune Can you comment on support for rolling updates for config maps

**Comment by pwittrock** [comment] 2016-08-10 21:14
@c-knowles As you noted, updates for config maps is still being worked on.  As a workaround you can create a new config map resource and change your pods to consume the new config map.  e.g. `kubectl create configmap myconfig_v1 --from-file=file1.yml --from-file=file2.yml`.

**Comment by c-knowles** [comment] 2016-08-11 05:30
Thanks for the info. My only input then would be it would be great if it could work the same way as other resources. i.e. `apply` works for upsert since ideally we don't really want to be concerned with whether it has been created yet or not.

I wrote a small script to collect the contents of the config files into a resource YML (then use `apply`) so will go with that for now. Your workaround would also work, we are already putting the git hash into the configuration name but we can also just put a hash that's randomised for each build to ensure re-running a delivery pipeline works if the configmap is already there.

**Comment by bgrant0607** [comment] 2016-08-30 21:00
see also #25832, #24049, #30558

**Comment by c-knowles** [comment] 2016-08-31 01:08
Happy to close this as duplicate so we have a single ticket.

**Comment by bgrant0607** [comment] 2017-09-01 17:54
Closing this as a dupe of #24744, which I expanded to cover configmaps.

How I see this fitting into the big picture is covered by my uber doc: https://goo.gl/T66ZcD

**Closed by bgrant0607** 2017-09-01 17:54 UTC
Labels: area/app-lifecycle, area/configmap-api, area/declarative-configuration, area/kubectl, kind/feature, priority/important-soon, sig/cli

**Comment by bgrant0607** [comment] 2017-09-01 18:01
See also #30558

**Comment by junneyang** [comment] 2019-01-17 14:30
why close?
