### ISSUE TITLE
[Flaky Test] : [sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#65286] opened 2018-06-20 21:17 UTC
## Flaky Jobs:
* [presubmits-kubernetes-blocking#pull-kubernetes-integration](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&show-stale-tests=)
* [ci-kubernetes-e2e-gci-gce](https://k8s-testgrid.appspot.com/sig-api-machinery#gce&width=5)

## Flakiest test :
* [[sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64957/pull-kubernetes-e2e-gce/40826)

## Triage link
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-06-15&sig=api-machinery&job=ci-kubernetes-e2e-gci-gce&test=Garbage%20collector%20should%20orphan%20RS%20created%20by%20deployment%20when%20deleteOptions.PropagationPolicy%20is%20Orphan

/priority failing-test
/priority important-soon
/kind flake
/sig-api-machinery
/assign @liggitt 
@kubernetes/sig-api-machinery-bugs 

@liggit @deads2k  @@fedebongio this failure is currently one of the top flake and repros in both Presubmits and CI jobs. This test is also part of the Conformance suite, which makes the flake far more critical. Can one of you please help triage this issue.

**Comment by liggitt** [comment] 2018-06-20 21:21
@jennybuckley did the additional logging added reveal anything helpful?

**Comment by liggitt** [comment] 2018-06-21 03:55
duplicate of https://github.com/kubernetes/kubernetes/issues/60463
/close

**Closed by liggitt** 2018-06-21 03:55 UTC
Labels: kind/bug, kind/flake, priority/failing-test, priority/important-soon, sig/api-machinery
