### ISSUE TITLE
Some Pods stop receiving traffic - connections left in FIN_WAIT2 state by kube-proxy

### ISSUE THREAD

**Issue by romanek-adam** [kubernetes/kubernetes#17641] opened 2015-11-23 10:14 UTC
I'd like to report a serious issue in Kubernetes v1.0.6.

The problem is that after the cluster is running for some time (a few days) some of our Pods stop receiving traffic. We narrowed it down to the fact that from time to time a connection in FIN_WAIT2 is left by kube-proxy and the connection is never "closed".

```
$ sudo netstat -tpn | grep FIN_WAIT2
tcp6       0      0 10.244.0.1:33132        10.244.0.35:48936       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:48340        10.244.0.35:56339       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:52619        10.244.0.35:57859       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:33132        10.244.0.50:36466       FIN_WAIT2   14125/kube-proxy
```

These connections are left in this state for hours. According to the [documentation of Linux kernel](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) (search for tcp_fin_timeout) such connections should be closed by the kernel after X seconds. On our nodes this setting is set to 60 seconds which is the default value:

```
$ cat /proc/sys/net/ipv4/tcp_fin_timeout
60
```

So it's either a problem with Linux kernel or kube-proxy is somehow preventing the kernel from closing these connection.

The worst thing is that such connections stack up over time and at some point some Pods stop receiving HTTP traffic directed at them.

As pointed out in a similar issue, #14641, restarting kube-proxy is a dirty workaround. On Ubuntu 15.04 the command to do this is

```
sudo systemctl restart kube-proxy
```

Unfortunately after some time connections in FIN_WAIT2 show up again.

Interestingly both `netstat` (as shown above) and `lsof` tell these connections are IPv6 connections, which is not true, although I'm not sure if it's related.

```
$ sudo lsof -i | grep FIN_WAIT2
kube-prox 14125   root   87u  IPv6 164237996      0t0  TCP ip-10-244-0-1.eu-west-1.compute.internal:52619->ip-10-244-0-35.eu-west-1.compute.internal:57859 (FIN_WAIT2)
kube-prox 14125   root  114u  IPv6 147720987      0t0  TCP ip-10-244-0-1.eu-west-1.compute.internal:33132->ip-10-244-0-35.eu-west-1.compute.internal:48936 (FIN_WAIT2)
kube-prox 14125   root  121u  IPv6 168665862      0t0  TCP ip-10-244-0-1.eu-west-1.compute.internal:33132->ip-10-244-0-50.eu-west-1.compute.internal:36466 (FIN_WAIT2)
kube-prox 14125   root  126u  IPv6 147854476      0t0  TCP ip-10-244-0-1.eu-west-1.compute.internal:48340->ip-10-244-0-35.eu-west-1.compute.internal:56339 (FIN_WAIT2)
```

For completeness - my cluster is located in AWS with EC2 running Ubuntu 15.04 and it was started using `kube-up.sh` (I can provide the config if needed).

```
$ uname -a
Linux ip-172-21-1-201 3.19.0-20-generic #20-Ubuntu SMP Fri May 29 10:10:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by romanek-adam** [comment] 2015-11-23 12:03
As pointed out in [an answer to my question](http://serverfault.com/a/738314/294009) on StackOverflow:

> the program that owns that socket is responsible for timing out the shutdown of the connection

So the question is: does kube-proxy correctly handle connection shutdown by timing out when not receiving shutdown ack from the other end?

**Comment by thockin** [comment] 2015-11-23 17:57
We do not timeout TCP - we're waiting for one end to close the connection,
at which point we clean up.  Can you explain more about how you're
triggering this?  I can't reproduce it.

You might also try the iptables proxier in kuberneet v1.1

**Comment by romanek-adam** [comment] 2015-11-26 11:57
The steps to reproduce this are unknown.

In general the FIN_WAIT2 state is quite unusual (see [this](https://kb.iu.edu/d/ajmi) and [this](http://serverfault.com/questions/738300/why-are-connections-in-fin-wait2-state-not-closed-by-the-linux-kernel/738314#comment922492_738300)) - it means the other end has already acknowledged our FIN but can still send us some data as it hasn't sent us its FIN packet (or it hasn't got the chance to do it). There are also some interesting old [Apache docs](http://httpd.apache.org/docs/2.0/misc/fin_wait_2.html) which refer to this topic.

Our application stack is based on Oracle Java 1.8 running on Alpine Linux as the base Docker image and hosts running Ubuntu 15.04.

FYI, just a few hours ago I had to restart `kube-proxy` to uncork our services. So this is not a one time issue.

**Comment by thockin** [comment] 2015-12-01 07:33
Let's leave this open for a while and hope we can get a repro...

**Comment by ahead4** [comment] 2015-12-02 16:47
+1 I'm also experiencing this. After a day or two (sometimes longer) some pods will stop receiving connections and the nginx reverse proxy we're using will begin logging 504 timeout errors when attempting to connect to service IPs.

A restart of the kube-proxy is required to bring it back into a working state.

Going to attempt to get a log of the issue so will post back in a few days.

**Comment by maclof** [comment] 2015-12-02 16:48
+1

**Comment by Sladewill** [comment] 2015-12-02 16:48
+1

**Comment by thockin** [comment] 2015-12-03 06:47
Thanks.  And to be clear, this is with the userspace proxy yes?

**Comment by ahead4** [comment] 2015-12-03 07:24
Yes that's correct.

**Comment by romanek-adam** [comment] 2015-12-03 22:04
Please note that this issue is quite hard to identify so there's potentially many more people affected, not really knowing what's happening.

**Comment by 2opremio** [comment] 2015-12-08 15:53
I think https://github.com/kubernetes/kubernetes/issues/18354 another instance of this. I have included all sorts of debugging information

**Comment by 2opremio** [comment] 2015-12-11 11:41
If this issue the same cause as #18354 (and it seems likely), this is triggered by kube-proxy origins/destinations not closing their sockets properly. As an alternative to patching kube-proxy, I would to check for leaks in the code of the pods whose IPs correspond the _Foreign Address_ of the `FIN_WAIT2 `  sockets of kube-proxy.

In @romanek-adam's example:

```
$ sudo netstat -tpn | grep FIN_WAIT2
tcp6       0      0 10.244.0.1:33132        10.244.0.35:48936       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:48340        10.244.0.35:56339       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:52619        10.244.0.35:57859       FIN_WAIT2   14125/kube-proxy
tcp6       0      0 10.244.0.1:33132        10.244.0.50:36466       FIN_WAIT2   14125/kube-proxy
```

I would check the pods with IP `10.244.0.35`  and `10.244.0.50` for leaks. If the pods are still alive (which may not be the case) you will find their IPs with `kubectl describe pods`.

**Comment by yenif** [comment] 2015-12-28 18:11
I started running into this issue on google container engine last week. I switched kube-proxy to iptables mode according to http://googlecloudplatform.blogspot.com/2015/11/enhancements-to-Container-Engine-and-Container-Registry.html ("A re-architected networking system”) and it’s working much better.

Is there a way to configure default annotations for new nodes being created and joining the cluster? Or is there another method I should use to make sure future nodes use iptables mode for kube-proxy?

**Comment by thockin** [comment] 2015-12-29 23:47
The iptables mode is technically still beta, but there's not (as far as I
know) a way to set labels on new nodes as they join the cluster, though
that seems reasonably parallel to admission control.

**Comment by thockin** [comment] 2015-12-29 23:47
@davidopp @mikedanese @roberthbailey to confirm - no way to set labels/annotations to be assigned to nodes as they join, right?

**Comment by roberthbailey** [comment] 2016-01-02 08:26
I don't know of anything built in to the system. You could write a pretty simple controller process that watches the apiserver's nodes and sets labels on them as new ones join and then run it in your cluster under a replication controller if you don't mind writing a small amount of code.

**Comment by thockin** [comment] 2016-01-03 05:30
This alone is not pleasant because you still need to kick kube-proxy to
pick up the annotation change :(

**Comment by yenif** [comment] 2016-01-04 00:12
Pretty hacky, but get's the job done. I just added

```
sed -i'' 's/--v=2 "/--v=2 --proxy-mode=iptables "/' /etc/default/kube-proxy
service kube-proxy restart
```

to the end of the gke startup template so nodes are configured when they are started by compute engine. I did the same thing for numerous sysctl settings.

**Comment by thockin** [comment] 2016-01-04 04:26
yeah, it would be neat if GKE had a way to add node labels/annotations
similar to startup scripts.

**Comment by jsravn** [comment] 2016-01-07 15:43
I can reproduce this pretty easily with persistent http connections where the client doesn't actively check for stale connections (such as Apache httpclient's connection pooling). If the server keepalive is less than client keepalive, the server will close the socket and the client won't close it properly. This leads to a FIN_WAIT2 socket to the client, and CLOSE_WAIT on the server.

**Comment by thockin** [comment] 2016-01-11 07:12
I think #18524 fixed this on master branch.  Cherry-pick to 1.1 release in #19463.  Please re-open if that doesn't get it.

**Closed by thockin** 2016-01-11 07:12 UTC
Labels: team/cluster
