### ISSUE TITLE
Kubelet should perform ACL check when pulling an image

### ISSUE THREAD

**Issue by jasinner** [kubernetes/kubernetes#73294] opened 2019-01-24 04:41 UTC
If an image already exists on a node it is possible to use that image in a different namespace even though a user might not have access to pull that image from a private repository.

This is mentioned in the [CIS Kubernetes Benchmark v1.3.0](https://www.cisecurity.org/benchmark/kubernetes/) in the item titled "1.1.11 Ensure that the admission control plugin AlwaysPullImages is set". There is offers a mitigation for this problem, but  that mitigation has a few issues:

1. it means any downtime of the registry causes corresponding application downtime across an entire cluster, which could bring down your entire application
2. it dramatically increases network traffic to the upstream registry

This issue can be reproduced by following these steps on v1.13.2:

1. Pull an image to the default namespace by following this guide. https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
2. Make sure you tag the image, and don't use the default, 'latest' tag because that will trigger the ImagePullPolicy to be 'Always'
3. Pull that same image into a pod in a different namespace without specifying the registry secret, eg:
$ cat stolen-pod.yaml 
```
apiVersion: v1
 kind: Pod
 metadata:
   name: private-reg
 spec:
   containers:
   - name: private-reg-container
     image: jazinner/image:1.0
 ```
4. You'll see that the image is pull successfully even though a secret was required to pull that image to the default namespace.

**Comment by cblecker** [comment] 2019-01-25 01:08
@dims I moved it.

**Comment by dims** [comment] 2019-01-25 01:38
Thanks @cblecker !

**Comment by zouyee** [comment] 2019-01-25 12:48
https://github.com/docker/compose-on-kubernetes/issues/27

**Comment by liggitt** [comment] 2019-01-25 14:34
duplicate of https://github.com/kubernetes/kubernetes/issues/18787

/close

**Closed by liggitt** 2019-01-25 14:34 UTC
Labels: sig/auth, sig/node

**Comment by liggitt** [comment] 2019-01-25 14:35
the `AlwaysPullImages` admission plugin will force all containers to ping the registry, which accomplishes the auth check, at the cost of putting your registry in the critical path for every container start
