### ISSUE TITLE
Core-dns pods crashing in large-cluster performance tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#68613] opened 2018-09-13 09:08 UTC
Sometime ago I observed in our 5k-node scalability tests that core-dns pods were crashing (we use n1-standard-1 nodes there). This was after we switched the default from kube-dns to core-dns in https://github.com/kubernetes/kubernetes/pull/67569. We need to investigate this before we cut the release.

/kind bug
/sig scalability
/sig network
/priority critical-urgent
/milestone v1.12

cc @wojtek-t @krzysied

**Comment by shyamjvs** [comment] 2018-09-13 09:09
cc @fturib @thockin

**Comment by shyamjvs** [comment] 2018-09-13 09:11
From our load test where we create ~8k services with a total of ~75k backends:

```
$ kubectl get pods -n kube-system -l k8s-app=kube-dns
NAME                       READY   STATUS    RESTARTS   AGE
coredns-779ffd89bd-25hk5   1/1     Running   20         23h
coredns-779ffd89bd-2b2kv   1/1     Running   26         23h
coredns-779ffd89bd-2f877   1/1     Running   21         23h
coredns-779ffd89bd-2k89h   1/1     Running   25         23h
coredns-779ffd89bd-2lctr   1/1     Running   22         23h
coredns-779ffd89bd-2ldqj   1/1     Running   30         23h
coredns-779ffd89bd-2mqhl   1/1     Running   27         23h
coredns-779ffd89bd-2rwk4   1/1     Running   22         23h
coredns-779ffd89bd-2x9gb   1/1     Running   26         23h
coredns-779ffd89bd-2xbtk   1/1     Running   19         23h
...
```

**Comment by shyamjvs** [comment] 2018-09-13 09:13
Looking at one such pod, it seems to have been OOMKilled:

```
Name:               coredns-779ffd89bd-wzhpr
Namespace:          kube-system
...
    State:          Running
      Started:      Wed, 12 Sep 2018 16:30:24 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```

**Comment by shyamjvs** [comment] 2018-09-13 09:16
From the yaml, it seems like core-dns has the same resources set as what kube-dns used to have earlier:

https://github.com/kubernetes/kubernetes/blob/989f6667d275c02e7dfebcc781f2360a07eedd15/cluster/addons/dns/coredns/coredns.yaml.base#L113-L118

**Comment by shyamjvs** [comment] 2018-09-13 09:20
@fturib Couple of questions:

- Do we have any evidence that core-dns has greater resource footprint than kube-dns?
- Also, I remember we were discussing about scale-testing core-dns a while ago for GA. Could you confirm what scale was it tested at?

**Comment by wojtek-t** [comment] 2018-09-13 09:30
@thockin @bowei @kubernetes/sig-network-bugs - @shyamjvs and @krzysied are working on confirming that this is the final reason of regression; but assuming that it's the case, given where we currently are in release phase, I think that we should revert switch to core-dns by default (if that is the reason - unless we know how to fix those fast).

**Comment by shyamjvs** [comment] 2018-09-13 09:38
IMHO we should revert this now and re-revert it back once we fix (and test) the OOM-kill issue.

**Comment by wojtek-t** [comment] 2018-09-13 09:40
We should first confirm with 100% certainty that it's that.

**Comment by wojtek-t** [comment] 2018-09-13 09:41
@AishSundar @guineveresaenger - ^^

**Comment by shyamjvs** [comment] 2018-09-13 09:49
> We should first confirm with 100% certainty that it's that.

We have evidence that load test passed in [this run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/203) right before the switch to core-dns was made. But I agree it's probably worth confirming once again (@krzysied is running the test currently).

**Comment by chrisohaver** [comment] 2018-09-13 13:39
> Do we have any evidence that core-dns has greater resource footprint than kube-dns?

Our early scale tests (5K nodes, 10K services, max QPS load) showed that they were essentially the same (coredns slightly lower).  Although this was done on coredns version 0.9.9. Coredns 1.2.2 is the version being tested.

CoreDNS is less memory efficient with cache than dnsmasq (what kube-dns uses).  But, IIRC, these e2e scale tests do not provide any QPS load, so that would not be a factor because without any queries, cache would not grow in size.  QPS load would have to be extremely high for cache to grow large enough to cause a problem during the test.  Furthermore, the latest version of coredns has a smaller default cache size, such that if it is full, it should fit in the deployment's default limit.

CoreDNS does deploy two instances by default.  Kube-DNS only deploys one.  So together, the coredns pods would of course take 2X the memory, but individually the expectation is they should be about the same (assuming no significant cache usage).

Do you have any statistics collected on the memory growth?

There are also these [scale service tests](https://k8s-testgrid.appspot.com/sig-network-gce#gce-coredns-performance) in sig-network added last release, which appear to be passing OK.  These run the maximum number of services allowed per cluster, and query a subset of the service names to verify function.  They are only run on a few nodes,  but coredns doesn't store node information, so a large number of nodes should not affect the memory footprint.

**Comment by chrisohaver** [comment] 2018-09-13 14:12
> From our load test where we create ~8k services with a total of ~75k backends:

@shyamjvs, what tests are "our load tests"?  And by "backend" do you mean a service endpoint? Can you provide more context?  Is this the e2e test, or a private test your group performs using the perf-test tool?  I see many coredns replicas, running for 24 hours, so presumably this is not the e2e tests.

**Comment by shyamjvs** [comment] 2018-09-13 14:18
This is a particular e2e test we have been running for a very long time
now, as part of release-blocking scalability CI tests. The e2e is at
test/e2e/scalability/load.go

**Comment by shyamjvs** [comment] 2018-09-13 14:20
And by "backend" above, I meant the no. of pods in total belonging to all
those services.

**Comment by chrisohaver** [comment] 2018-09-13 14:48
Ah, OK Thanks!  I didn't know those tests ran for extended periods of time.  I thought they just spun up a number of services, then spun them down.  How long do these tests run? I see 23 hours in the output you provided.  Or is the cluster not rebuilt each test, the same coredns instances processing 5K service down/up for multiple tests?  If thats the case, I could see a possibility of memory leak there maybe.  We have not tested repeated spin-up/teardown of a huge number of services.

I recall we did simulate a 10% "churn" per hour of services in our local scale/load tests, which we felt was realistic.  Services shouldn't churn very much in a real deployment so we chose to spin up/down about 10% of the services per hour (pods would churn a lot, but coredns/kube-dns do not monitor pods).

**Comment by shyamjvs** [comment] 2018-09-13 14:58
To clarify few things:

- The load test I mentioned above typically takes about 8-10 hrs when running on a 5000-node cluster
- It creates a bunch of services and then RCs which fall under those services. Then it scales those RCs up/down randomly and finally deletes the RCs and services
- In this case you see 23 hrs because we were running that load test manually and didn't delete the cluster for a few hours after the test finished. Anyway, the crashes start to happen as the test proceeds
- We're not doing any repeated spin-up or teardown here. It's just a one-off test.
- The test doesn't create any sustained churn of services (except the initial creation and the final deletion of those). It's more of a churn with the endpoints (as RCs are created, scaled, etc..)

**Comment by chrisohaver** [comment] 2018-09-13 15:13
Thanks, that clarifies things for me. CoreDNS does monitor endpoints, so there may be a leak there in CoreDNS.  Although if it is, I think it would be a leak in the k8s api go client/cache we use.  CoreDNS doesn't store dns records, it constructs them on demand from the api client cache when a query is received.  (Am i correct in saying there is no QPS load in this test?)

**Comment by shyamjvs** [comment] 2018-09-13 15:26
> CoreDNS does monitor endpoints

Few questions about this:

- Does that mean it keeps the endpoints objects in its memory (as that can be a sizable amount)?
- Was kube-dns also monitoring endpoints?
- Out of curiosity - why does DNS have to know about endpoints? (isn't just the service IP enough?)

> Am i correct in saying there is no QPS load in this test?

No QPS that we are creating in the test (there may still be some default control-plane lookups - I'm not sure though).

**Comment by chrisohaver** [comment] 2018-09-13 15:37
- Endpoints API objects are kept in memory, in an api cache (part of client-go lib).
- Kube-dns AFAIK more or less does the same.  I'll look in the kube-dns code again, its been a long time since I looked.
- DNS needs to know endpoints to be able to serve records for headless services (service without a cluster IP).  There is no way monitor only changes for headless services (that I know of) - so all endpoints are monitored, even ones for cluster IP services.

**Comment by wojtek-t** [comment] 2018-09-13 15:56
@chrisohaver - from what you wrote above, it seems that CoreDNS is processing (and keeping) k8s objects pretty much the same way that kube-dns is doing.

But because of some reason (assuming that @shyamjvs checked that correcly and both are requesting the same amount of resources), something must be significantly differently, because we weren't observing any extensive crashing of kube-dns (up until it was replaced to CoreDNS).

**Comment by wojtek-t** [comment] 2018-09-13 15:57
And the test is exactly the same as it was - we didn't change that around that time.

**Comment by shyamjvs** [comment] 2018-09-13 16:13
In general, it seems to me like [this e2e](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns_scale_records.go) you're running to scale-test dns is insufficient, as it's only creating empty services (without any endpoints). IMO that test should be changed to also create some sizeable endpoints objects for those services (either manually in that test, or if that's not possible, by actually creating many pods - which kind of ends up being like this load test) to reflect more realistic memory usage.

**Comment by chrisohaver** [comment] 2018-09-13 16:21
@wojtek-t, Well - Its possible that while kube-dns subscribes to events for endpoints, doesn't cache them if they are for cluster IP services.  Or, that it doesn't cache endpoint API objects in their entirety.  I'm looking at the code today.

@shyamjvs, Yes the other test only tests for service only.  This was known/discussed at the time.  The test is not a complete test - it was a first step.  Adding endpoints objects (with no pods because it's not a scale cluster) would be the logical next step.

**Comment by shyamjvs** [comment] 2018-09-13 16:30
> The test is not a complete test - it was a first step. Adding endpoints objects (with no pods because it's not a scale cluster) would be the logical next step.

IMO we should test for such a scenario (which is quite realistic), before switching it to production default :)

**Comment by wojtek-t** [comment] 2018-09-13 16:33
> IMO we should test for such a scenario (which is quite realistic), before switching it to production default :)

+100
That in my opinion is a very strong argument to reverting the default change, given that we're already in code freeze.
@thockin @bowei ^^

**Comment by bowei** [comment] 2018-09-13 16:38
Revert seems to be the safer option here (my opinion).

**Comment by chrisohaver** [comment] 2018-09-13 16:43
> +100

no! no! -100 !!! just kidding.

Well - After a quick glance at the kube-dns code, it seems it might not be caching endpoints for clusterIP services.  If this is true, it seems like it just sidesteps the test condition though.  i.e. If the tests contains a large number of headless services, kube-dns might consume more memory.

I could fix this in coredns, to not cache endpoint objects if the service is a cluster IP service, but the issue remains if all services are headless.

**Comment by bowei** [comment] 2018-09-13 16:47
dnsmasq has static memory allocation (the hash table nodes are all allocated up front).

**Comment by chrisohaver** [comment] 2018-09-13 16:48
> dnsmasq has static memory allocation (the hash table nodes are all allocated up front).

Per my understanding, this isn't about the dns cache, rather the API object stores.

**Comment by chrisohaver** [comment] 2018-09-13 16:58
I agree this needs to be fixed, and if we are not permitted to fix it during code freeze, then we have no other option than to revert CoreDNS as default.

If we are permitted a fix, an obvious "quick fix" would be to increase the memory limit. Although we'd have to find out what the required size actually is at max scale (in the test), and also decide if that number is reasonable.  e.g. if its 200, then thats probably fine, if it's 1000, perhaps not.

Would it be reasonable to update the memory limit to, say 500, and see what the max size is during the test, then if we don't get OOMs, drop the size to a reasonable buffer above it?

**Comment by shyamjvs** [comment] 2018-09-13 16:59
I've created the revert PR https://github.com/kubernetes/kubernetes/pull/68629 - PTAL.

**Comment by tpepper** [comment] 2018-09-13 17:09
I would vote for fixing, versus reverting.  Of course that's a bit dependent on seeing the size/scope of the fix.  But if it's just increasing resource limit somewhat, that doesn't seem bad.

**Comment by chrisohaver** [comment] 2018-09-13 17:31
If we are to seek the actual memory requirement at the max scale, would be be best to submit a PR that bumps it to a high number, say 1000, merge it, have the test run, then revert and make a decision?

Or would we need to duplicate the test environment locally.

**Comment by tpepper** [comment] 2018-09-13 17:33
Since we're only talking about 1 or 2 replicas here in the kube-dns and coredns cases...I think bumping the mem requirement here is reasonable to get into test asap.

**Comment by rajansandeep** [comment] 2018-09-13 17:47
I have PR https://github.com/kubernetes/kubernetes/pull/67392 which sets the mem limit to 1000

**Comment by chrisohaver** [comment] 2018-09-13 17:53
> I have PR #67392 which sets the mem limit to 1000

The idea here would be to merge this temporarily, and let the tests run, look at results, then revert.  Then, if we don't get OOM restarts, we can look at the actual memory usage and determine if it is a reasonable number.  If so, we can adjust the limit to reflect that.

**Comment by wojtek-t** [comment] 2018-09-13 17:53
> I have PR #67392 which sets the mem limit to 1000

I don't agree for that. This is breaking change. If users have packed cluster, this may lead to preempting their workloads.
That's definitely not a thing to do during code freeze.

**Comment by chrisohaver** [comment] 2018-09-13 17:55
>  If users have packed cluster,

The idea here would be to merge this _temporarily as a troubleshooting step_, and let the tests run, look at results, _then revert_. Then, if we don't get OOM restarts, we can look at the actual memory usage and determine if it is a reasonable number. If so, we can adjust the limit to reflect that.

**Comment by bowei** [comment] 2018-09-13 17:56
We have to be careful when we change resource limits up. Let's see what the experiment yields.

**Comment by wojtek-t** [comment] 2018-09-13 17:56
> The idea here would be to merge this temporarily as a troubleshooting step, and let the tests run, look at results, then revert. Then, if we don't get OOM restarts, we can look at the actual memory usage and determine if it is a reasonable number. If so, we can adjust the limit to reflect that.

I would be fine with doing that in early phase of release. Not when we are already during code freeze.
We are going to release 1.12 in less than two weeks - we shouldn't rush with fixes in that phase.
@bowei @thockin ^^

**Comment by tpepper** [comment] 2018-09-13 17:57
CoreDNS has claimed to support more transactions at lower memory overhead.  If that is not true at scale, there's a CoreDNS issue, imho.  But we need to help debug.  Running _a_ test to better triage seems worthwhile here.  Then we decide the path.  Revert?  Increase limit to (very? slightly?) higher number and release note it?  It's hard to understand the scope at this point.

Also I'm generally skeptical of users who have strong performance expectations on a cluster so hypothetically tightly packed as to not have some headroom on a node or two...production operation that close to the edge is inherently risky.

**Comment by tpepper** [comment] 2018-09-13 17:59
As 1.12 release lead I'm ok with this experiment today.  But at the same time will defer to SIG Scalability leadership.  If reverting is the primary path to insure all scalability tests are green in the next four or five days, then so be it.  I'd just rather be pragmatically open to helping forward progress if possible.

**Comment by bowei** [comment] 2018-09-13 17:59
IMHO we should bias towards stability. Note the user can chose CoreDNS as it is a supported GA option. This is not precluding the choice, just changing the default option...

**Comment by neolit123** [comment] 2018-09-13 18:02
it's too late in the cycle to move away from CoreDNS being the default. it's all over the documentation too.

**Comment by wojtek-t** [comment] 2018-09-13 18:05
> IMHO we should bias towards stability. Note the user can chose CoreDNS as it is a supported GA option. This is not precluding the choice, just changing the default option...

+100 - that also reflects my thoughts

> As 1.12 release lead I'm ok with this experiment today. But at the same time will defer to SIG Scalability leadership. If reverting is the primary path to insure all scalability tests are green in the next four or five days, then so be it. I'd just rather be pragmatically open to helping forward progress if possible, while not risking release blockage for 1.12.

I think it's getting too late. Even though we have some proofs that it's the last regression, I think we want a couple of green runs before we release the version.
And given how long scalability runs are, we don't have that many runs before that.
I think it's too late to rush with fixes - the project is in a state when we can't comprise on quality.

> it's too late in the cycle to move away from CoreDNS being the default. it's all over the documentation too.

I don't buy it - it should be a matter of reverting a PR changing that.
And as @bowei said it's only about changing the default.

**Comment by chrisohaver** [comment] 2018-09-13 18:06
@shyamjvs, Just curious, how long ago did you observe this?  This issue is only 9 hours old.  but you said you have observed it "some time ago" ...

**Comment by wojtek-t** [comment] 2018-09-13 18:07
@chrisohaver - the problem is that there were a couple other regressions that were more serious and were causing bigger issues and hiding this one.

**Comment by shyamjvs** [comment] 2018-09-13 18:07
Probably in the last or the one before that run. The reason for not having noticed it earlier was due to earlier regressions masking this problem.

**Comment by neolit123** [comment] 2018-09-13 18:10
@wojtek-t 
> I don't buy it - it should be a matter of reverting a PR changing that.

FYI coredns has been the default for kubeadm deployments since 1.11.

**Comment by wojtek-t** [comment] 2018-09-13 18:13
> FYI coredns has been the default for kubeadm deployments since 1.11.

That doesn't mean we should change defaults everywhere else.
It's deployment tools decision what they make default.

I'm saying that from scalability/performance perspective we are not ready to change the default for GCE.

**Comment by tpepper** [comment] 2018-09-13 18:15
Can we get an opinion from @kubernetes/sig-network-pr-reviews

**Comment by wojtek-t** [comment] 2018-09-13 18:16
So far we have opinion with @bowei who seems to agree with us. But yeah - we ask for more.

**Comment by tpepper** [comment] 2018-09-13 18:47
@wojtek-t do you want to timebox the decision point?

**Comment by neolit123** [comment] 2018-09-13 18:52
thanks @dims

**Comment by johnbelamaric** [comment] 2018-09-13 19:09
@tpepper if we can run the single test prior to the revert / bump resources decision that would be ideal. If it's too late for that then we will have no choice but to revert (and then revert the various docs PRs too).

**Comment by neolit123** [comment] 2018-09-13 19:10
@chrisohaver @johnbelamaric do you have infrastructure to test the memory bumps, as it seems that the test PR is not going to be merged?

**Comment by chrisohaver** [comment] 2018-09-13 19:18
@neolit123, No this is why I proposed we test via PR - it's the fastest option.  We could try to replicate the test environment.  We'd need details on specs, but I think this would take too much time to do.

**Comment by thockin** [comment] 2018-09-13 19:19
This is a decision that sig-scale and release owners need to make together.  I think it exemplifies the fact that this is IMPORTANT and that these roles are empowered to (and expected to) make hard decisions.  There's not a fixed rule as to which group is more important.  If you can't come to a decision, then it should escalate, but I sort of feel like the escalation is happening as a shortcut.

I don't think sig-network has standing in this - we obviously want progress but not at the cost of scalability or release.

**Comment by tpepper** [comment] 2018-09-13 19:37
From the release side, release team defers to SIG subject matter experts as a rule, so I do defer to scale for this issue.  But I will say I feel we do just have time relative to release schedule, which may be slipping a few days due to other issues also in need of merge + test data anyway, to run a scale experiment and that the data would be useful if SIG Scalability wants to run that now instead of 1.13 start.

**Comment by wojtek-t** [comment] 2018-09-13 20:16
> From the release side, release team defers to SIG subject matter experts as a rule, so I do defer to scale for this issue. But I will say I feel we do just have time relative to release schedule, which may be slipping a few days due to other issues also in need of merge + test data anyway, to run a scale experiment and that the data would be useful if SIG Scalability wants to run that now instead of 1.13 start.

@tpepper - I was thinking about that and how we can more help with that without risking too much on scalability side.
And I would like to propose some modification (though this clearly requires approval from release team).
My proposal is the following:
- we revert this PR today
- that will hopefully result in successful run from Friday`s test
- in the meantime, folks can thing what experiments may be useful for the to fix the situation (one thing to keep in mind is that we are not monitoring resource usage of dns instances, so if we need some data, we would need some mechanism to gather it) - so we need the PR for the experiment
- if the test run will be green, I'm fine with re-reverting the original PR (+ whatever is needed to further investigate it) [with a hope that since we're in freeze, we won't regress in the meantime]
- that will facilitate debugging
- if whatever fixes will be needed will be approved by release team and merged and will make CoreDNS pass the tests (say next Wed, or Thu - to be decided with release team), I'm fine with leaving that enabled by default - otherwise, we will revert it again

Do you think it is reasonable?

**Comment by tpepper** [comment] 2018-09-13 20:20
Yes this is veryreasonable.  It prioritizes what is also an experiment (tomorrow's scale run) to prove 1.12 release readiness in the safest path.  And then it also gives time to more deliberately plan an the best possible experiment for ~Monday-ish to see if there is an alternative path possible still for 1.12 or better set a footing to insure we get resolution on the CoreDNS issues and do so while we have people's attention, even if this "only" feeds debugging to inform merges that ultimately land in 1.13.

**Comment by johnbelamaric** [comment] 2018-09-13 21:46
Thanks @tpepper and @wojtek-t, that sounds like a good plan. @chrisohaver @fturib @rajansandeep we need to see what metrics we can start gathering during the test, and exactly how we want to run that experiment.

**Comment by thockin** [comment] 2018-09-13 21:53
Thanks, guys.  Good answer.

**Comment by chrisohaver** [comment] 2018-09-13 23:59
> we need to see what metrics we can start gathering during the test

Ah, Yes - ironically this isn't always so simple in kubernetes.
@wojtek-t, Is any resource metric monitoring exposed/available on these test systems?

**Comment by shyamjvs** [comment] 2018-09-14 10:19
So we have the revert merged and the CI tests are running against it currently.
Now for the remainder of the plan, we (sig-scalability) are happy to discuss / help with scale-testing any potential fixes to core-dns.

**Comment by chrisohaver** [comment] 2018-09-14 12:48
Thanks, a [comment](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/resource_usage_gatherer.go#L231) in `resource_usage_gatherer.go` says that all pods in `kube-system` are tracked if a podList is not provided.  Since dns pods reside in the `kube-system` namespace, does this mean they are tracked?  Or are the scale tests limiting tracking to a specific podList?

**Comment by chrisohaver** [comment] 2018-09-14 14:13
@shyamjvs, @wojtek-t As a sanity check, what does `/etc/resolv.conf` contain on the test nodes (assuming `kubelet` uses the default `/etc/resolv.conf`, and not an alternate file)?  A cause of OOM kills we have seen in the field is due to an upstream lookup loop (re: `systemd-resolved`).  Unlikely this is the case here, but if you can check it, I can exclude that possibility. Thanks!

**Comment by wojtek-t** [comment] 2018-09-14 14:19
>  Thanks, a comment in resource_usage_gatherer.go says that all pods in kube-system are tracked if a podList is not provided. Since dns pods reside in the kube-system namespace, does this mean they are tracked? Or are the scale tests limiting tracking to a specific podList?

I can't remember from the top of my head.
You can take a look how we initialize it (it should be somewhere in test/e2e/framework or sth like that).
Or maybe @shyamjvs remembers it?

**Comment by guineveresaenger** [comment] 2018-09-17 16:08
@wojtek-t @shyamjvs should this issue be closed then?

**Comment by shyamjvs** [comment] 2018-09-17 16:14
No, the issue with core-dns is still there. We just fixed the release by reverting it from being default. So I suggest removing the release-blocker labels and keeping this open for the remainder of the bug.

**Comment by guineveresaenger** [comment] 2018-09-17 16:16
@shyamjvs gotcha. I'll move it out of the milestone then.

/milestone clear
/milestone v1.13

/remove-priority critical-urgent
/priority important-soon

**Comment by neolit123** [comment] 2018-09-17 16:42
@chrisohaver @rajansandeep 
if core-dns doesn't end up being default in 1.12 could please make sure the docs are up to date?
(kubeadm is independent from this).

**Comment by miekg** [comment] 2018-09-18 19:39
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Core-dn..." ]
>@chrisohaver @rajansandeep
>if core-dns doesn't end up being default in 1.12 could please make sure the docs are up to date?
>(kubeadm is independent from this).

Is there an easy way to get debugging data of these tests regarding CoreDNS?

Or is the only way to try to replicate a similar setup and hoping we see the 
same issue?

**Comment by chrisohaver** [comment] 2018-09-18 19:55
@wojtek-t, @shyamjvs Is there a way in the framework to enable collection of profiling data (i.e. `pprof`)?  I initially thought no, but I noticed `e2e/framework/profile_gatherer.go`.

**Comment by chrisohaver** [comment] 2018-09-18 19:59
After a quick look at `profile_gatherer.go`, it looks like it only allows collection via SSH.

**Comment by wojtek-t** [comment] 2018-09-18 20:00
> After a quick look at profile_gatherer.go, it looks like it only allows collection via SSH.

yes - it's only via SSH. And I'm not sure it now supports more than master VM.

**Comment by chrisohaver** [comment] 2018-09-18 20:05
Looks like it would not be terribly complicated to add http support.

**Comment by fturib** [comment] 2018-09-19 03:04
About the OOM and memory limit for the Pod, we were able to make some measurement using presubmit scale tests on the PR #68683.

We could estimate some mem usage for 0, 500, 2k nodes. The point at 5k nodes need to be run on a ci test (which means needs to merge the code and wait the scale-perf test is triggered).


**CoreDNS**
* 0 nodes: 18mi (measured)
* 500 nodes: 38mi (measured)
* 2000 nodes: 93mi (measured)
* 5000 nodes: 201mi (expected by extrapolation) - need to be verified with a real test

**Kube-dns**
* 0 nodes: 38mi (measured)
* 500 nodes: 43mi (measured)
* 2000 nodes - ??  - extrapolation expect 82mi - test to be run.
* 5000 nodes - ?? - extrapolation expect 148mi - which is in line the current max limit at 170mi. (and we should verify it with a test, once the pod dns resource monitoring will be merged)

For CoreDNS, the computation shows that we should need to bump-up the memory limit of CoreDNS to 220mi (expect 201 + 20 of buffer).

**Comment by johnbelamaric** [comment] 2018-09-19 04:59
I’d really like to understand why the growth is worse than kube-dns. What
additional resources are we storing? It will be great if we can get that
profiling somehow.

**Comment by tpepper** [comment] 2018-09-19 15:39
We should make a release note for Known Issues, perhaps something like:

Feature #566 enabling CoreDNS as the default for kube-up deployments was dropped from the release due to a scalability resource consumption issue observed. The root cause in CoreDNS remains unclear (ie: it was expected to be faster and with lower resource consumption), but CoreDNS folks are investigating. If a cluster operator is considering using CoreDNS at scale, it may be necessary to give more consideration to CoreDNS pod resource limits and experimentally measure resource usage versus cluster resource availability.

**Comment by neolit123** [comment] 2018-09-20 13:41
+1 for adding reasons in the release notes.

**Comment by nikopen** [comment] 2018-10-11 12:14
Is this being worked on? Should be remediated for the next release, as there is time now to make it work / benchmark / alter the limits on yaml manifest.

/milestone v1.13

**Comment by chrisohaver** [comment] 2018-10-11 12:31
We will present progress today in the sig-scalability meeting.  We have a candidate fix: which reduces the amount of storage needed by the k8s/client-go package - enough to bring us below the kube-dns memory limit at 5000 nodes.

**Comment by AishSundar** [comment] 2018-10-29 00:32
@chrisohaver @fturib can this issue be closed now? or do you have pending PRs for 1.13 timeframe?

**Comment by rajansandeep** [comment] 2018-10-29 03:13
@AishSundar Yes, this issue can be closed as https://github.com/kubernetes/kubernetes/pull/69883 for CoreDNS default has been merged and there are no problems seen in the scale tests.

**Comment by wojtek-t** [comment] 2018-10-29 07:17
Yes - this can be closed.

**Closed by wojtek-t** 2018-10-29 07:17 UTC
Labels: kind/bug, priority/important-soon, sig/network, sig/scalability
