### ISSUE TITLE
Addon Manager returns "error retrieving RESTMappings to prune"

### ISSUE THREAD

**Issue by jsloyer** [kubernetes/kubernetes#43755] opened 2017-03-28 13:46 UTC
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.3-1+11d2fe73285bf7-dirty", GitCommit:"11d2fe73285bf763bbb3976c99510e1dddcf043f", GitTreeState:"dirty", BuildDate:"2017-03-16T14:56:53Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.3-1+11d2fe73285bf7-dirty", GitCommit:"11d2fe73285bf763bbb3976c99510e1dddcf043f", GitTreeState:"dirty", BuildDate:"2017-03-16T14:56:53Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
IBM
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`):
Linux kube-dal10-cr1ae13de8f8ae48349427ad8857dd5069-w2 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
I am running addon manager as a pod with [this yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml) and have placed the kube dashboard yaml from [here](https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml) into `/etc/kubernetes/addons`.  I have modifed the yaml to have the `addonmanager.kubernetes.io/mode: Reconcile` label.  See the full yaml [here](https://gist.github.com/jsloyer/e3aacec25186eaa32a3ac4796174035e).

Addon Manager runs and successfully creates the deployment and service but I have an error in the log about unable to prune RESTMappings.

```
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
deployment "kubernetes-dashboard" created
error: error retrieving RESTMappings to prune: invalid resource apps/v1beta1, Kind=Deployment, Namespaced=true: no matches for apps/, Kind=Deployment
INFO: == Kubernetes addon reconcile completed at 2017-03-28T13:36:10+0000 ==
```

**How to reproduce it** (as minimally and precisely as possible):
see above

**Comment by jayunit100** [comment] 2017-03-28 15:39
iirc isn't it `apis/apps/v1beta1/` not `/apps/v1beta1` ?

**Comment by MrHohn** [comment] 2017-03-28 17:15
Hi @jsloyer , you were using addon-manager v6.4-beta.1 (which is built with v1.6 kubectl binary) with v1.5+ apiserver. The specific error you hit is because there is not `apps/v1beta1,Deployment` resource in v1.5 k8s, instead there is only `extensions/v1beta1,Deployment`. The new group was introduced by #39683 for v1.6.

So it seems like `kubectl apply --prune` in v1.6 is not compatible with k8s v1.5.

On the addon-manager aspect, I'd recommend to use addon-manager v6.1 with k8s v1.5 ([CHANGELOG](https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/addons/addon-manager/CHANGELOG.md)).

**Comment by MrHohn** [comment] 2017-06-05 17:04
Since kubectl apply --prune is still in alpha, we may not guarantee its compatibility during version skew.

Closing this issue for now.

/sig cli

/close

**Comment by joshuawilson** [comment] 2017-08-04 14:13
@smarterclayton should this be closed?

**Comment by aslakknutsen** [comment] 2017-08-04 14:15
@joshuawilson @smarterclayton Note; this was tested with 3.6.0 RC.0, retesting with 3.6.0

**Comment by aslakknutsen** [comment] 2017-08-04 15:07
@joshuawilson @smarterclayton Confirmed same behavior in 3.6.0

**Comment by smarterclayton** [comment] 2017-08-04 21:48
`kubectl apply` should only fail under version skew when the client can't find a resource from the file in the discovery doc, and even if it does fail, it should return a better message.  This will only grow more common as we introduce and deprecate new APIs.

**Comment by smarterclayton** [comment] 2017-08-04 21:49
At minimum the CLI needs to indicate to the user that a particular resource in their client file is not recognized by the server, potentially print recognized versions, and instruct the user on what to do.

**Comment by adohe** [comment] 2017-08-06 04:18
```
At minimum the CLI needs to indicate to the user that a particular resource in their client file is not recognized by the server, potentially print recognized versions, and instruct the user on what to do.
```
SGTM.

**Comment by seh** [comment] 2017-10-10 21:13
I ran into this same problem running _kubectl apply --prune_ with the following versions in play:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-09-29T05:56:06Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```
None of the manifests in the files submitted to _kubectl apply --prune_ are of kind _Deployment_, nor are any of the objects in the cluster selected by the label selector I passed via the `--selector` flag.

**Comment by MrHohn** [comment] 2017-10-10 22:52
Unassigning as I'm not currently working on fixing this issue.

/unassign

**Closed** 2018-03-12 20:31 UTC
Labels: lifecycle/rotten, sig/cli
