### ISSUE TITLE
e2e flake: Kubectl expose should create services for rc [Conformance]

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25657] opened 2016-05-16 10:49 UTC
It is failing with the following error:

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:836 May 16 03:20:05.931: No pods matched the filter.

Example failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/17011/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16999/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16993/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16991/

@janetkuo

**Comment by spxtr** [comment] 2016-05-16 17:17
This currently has a 12% flake rate in merge-blocking suites.

**Comment by spxtr** [comment] 2016-05-16 20:16
@k8s-oncall this needs attention.

**Comment by bgrant0607** [comment] 2016-05-17 06:23
cc @kubernetes/kubectl

**Comment by jszczepkowski** [comment] 2016-05-17 09:04
The problem reoccurred today: 
```
[k8s.io] Kubectl client
01:19:42 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
01:19:42   [k8s.io] Kubectl patch
01:19:42   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
01:19:42     should add annotations for pods in rc [Conformance] [It]
01:19:42     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:972
01:19:42 
01:19:42     May 17 01:18:58.841: No pods matched the filter.
01:19:42 
01:19:42     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:672
```
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/17075/

**Comment by spxtr** [comment] 2016-05-17 21:51
@bgrant0607 can you find an owner for this? It's blocking about 20% of our merge time.

**Comment by bgrant0607** [comment] 2016-05-17 22:54
My guess is that it should not be using examples/guestbook-go as the input files. The "testing image pulling from Dockerhub" problem.

**Comment by bgrant0607** [comment] 2016-05-17 22:55
And `waitFor(1)` should be banned.

**Comment by pwittrock** [comment] 2016-05-17 23:43
I am looking at this

**Comment by pwittrock** [comment] 2016-05-18 16:36
PR is out for review.

**Comment by pwittrock** [comment] 2016-05-19 02:32
#25781 was merged and introduced a likely fix as well as debug info in the event the root cause was not addressed.  Re-open if we continue to see this.

**Closed by pwittrock** 2016-05-19 02:32 UTC
Labels: component/kubectl, kind/flake, priority/P0, team/ux
