### ISSUE TITLE
Deleting manifest files on a node does not delete pods

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15171] opened 2015-10-06 18:28 UTC
I logged into a node and deleted a manifest file.  I watched the API for the pod to die but it didn't.  After a few minutes I manually deleted the pod from the API - and it came back!  Then I logged into the node and just restarted kubelet - finally it went away in the API.

@yujuhong

**Comment by yujuhong** [comment] 2015-10-06 18:52
Something is definitely wrong here because kubelet was repeatedly trying to create the mirror pod, which already existed.
`Failed creating a mirror pod "kube-registry-proxy-kubernetes-minion-ta23_kube-system": pods "kube-registry-proxy-kubernetes-minion-ta23" already exists`

There seems to be no indication that kubelet observed the deletion of the manifest file. Will try to reproduce this afternoon.

**Comment by yujuhong** [comment] 2015-10-08 23:03
Fixed by #15185

**Closed by yujuhong** 2015-10-08 23:03 UTC
Labels: kind/bug, team/node
