### ISSUE TITLE
kubectl delete daemonset hang 

### ISSUE THREAD

**Issue by wangweihong** [kubernetes/kubernetes#33245] opened 2016-09-22 02:27 UTC
I have a daemonset resource like this:

```
NAME             DESIRED   CURRENT   NODE-SELECTOR   AGE
newrelic-agent   3         3         <none>          3d
```

 When I try to run `kubectl delete daemonset` to delete this daemonset resource , it hang a few minutes, and exited with result 1.

```
root@ubuntu192:~/k8s# kubectl get daemonset 
NAME             DESIRED   CURRENT   NODE-SELECTOR                                                               AGE
newrelic-agent   0         0         13e0252d-8069-11e6-9cdd-005056881537=13e02602-8069-11e6-9cdd-005056881537   3d
```

This daemonset still exists.I try to delete it again.This time it hang  8 minutes.

```
root@ubuntu192:~/k8s# kubectl delete ds newrelic-agent
error: timed out waiting for the condition
```

**Kubernetes version** (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.2.282+c8ea7af912f86e", GitCommit:"c8ea7af912f86e05e22f1e8d0d0b90c8b9fc90d7", GitTreeState:"clean", BuildDate:"2016-08-05T01:09:47Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.2.282+c8ea7af912f86e", GitCommit:"c8ea7af912f86e05e22f1e8d0d0b90c8b9fc90d7", GitTreeState:"clean", BuildDate:"2016-08-05T01:09:47Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Linux ubuntu192.168.14.100 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

This is part of  logs  I strace `kubectl delete daemonset`command. Is that some way k8s get stack strace like docker dameon?

> stat("/root/.kube/config", {st_mode=S_IFREG|0644, st_size=332, ...}) = 0
> openat(AT_FDCWD, "/root/.kube/config", O_RDONLY|O_CLOEXEC) = 5
> fstat(5, {st_mode=S_IFREG|0644, st_size=332, ...}) = 0
> read(5, "apiVersion: v1\nclusters:\n- clust"..., 844) = 332
> read(5, "", 512)                        = 0
> close(5)                                = 0
> stat("/var/run/secrets/kubernetes.io/serviceaccount/token", 0xc820466518) = -1 ENOENT (No such file or directory)
> stat("/var/run/secrets/kubernetes.io/serviceaccount/token", 0xc8204665e8) = -1 ENOENT (No such file or directory)
> futex(0xc8200e0908, FUTEX_WAKE, 1)      = 1
> socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
> setsockopt(5, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
> connect(5, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("192.168.14.100")}, 16) = -1 EINPROGRESS (Operation now in progress)
> epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1007984784, u64=140308999610512}}) = 0
> getsockopt(5, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
> getsockname(5, {sa_family=AF_INET, sin_port=htons(33804), sin_addr=inet_addr("192.168.14.100")}, [16]) = 0
> getpeername(5, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("192.168.14.100")}, [16]) = 0
> setsockopt(5, SOL_TCP, TCP_NODELAY, [1], 4) = 0
> setsockopt(5, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
> setsockopt(5, SOL_TCP, TCP_KEEPINTVL, [30], 4) = 0
> setsockopt(5, SOL_TCP, TCP_KEEPIDLE, [30], 4) = 0
> futex(0xc8200e0908, FUTEX_WAKE, 1)      = 1
> read(5, 0xc82029c000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
> write(5, "GET /api HTTP/1.1\r\nHost: 192.168"..., 163) = 163
> futex(0xc8200e0908, FUTEX_WAKE, 1)      = 1
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> epoll_wait(4, [], 128, 0)               = 0
> futex(0x2964fc0, FUTEX_WAKE, 1)         = 0
> futex(0x2964f10, FUTEX_WAKE, 1)         = 1
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
> futex(0x2964fe8, FUTEX_WAKE, 1)         = 0
> futex(0x2964f10, FUTEX_WAKE, 1)         = 1
> futex(0xc8200e0908, FUTEX_WAKE, 1)      = 1
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> sched_yield()                           = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2964fe8, FUTEX_WAKE, 1)         = 0
> futex(0x2964f10, FUTEX_WAKE, 1)         = 1
> futex(0x2964fc0, FUTEX_WAKE, 1)         = 1
> futex(0x2964f10, FUTEX_WAKE, 1)         = 1
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> sched_yield()                           = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> select(0, NULL, NULL, NULL, {0, 100})   = 0 (Timeout)
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> sched_yield()                           = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2964fe8, FUTEX_WAKE, 1)         = 1
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
> sched_yield()                           = 0
> sched_yield()                           = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULL)   = 0
> futex(0x2965d08, FUTEX_WAIT, 0, NULLerror: timed out waiting for the condition
>  <unfinished ...>
> +++ exited with 1 +++

**Comment by janetkuo** [comment] 2016-09-26 18:09
The node selector is updated to a random label (`13e0252d-8069-11e6-9cdd-005056881537=13e02602-8069-11e6-9cdd-005056881537`) by the daemon set reaper successfully. Looks like it timed out waiting for all its pods to be gone. If this is a bug, it should be related to daemon set controller. @mikedanese @deads2k 

What's the daemon set config? What is the label selector it's using? Are other controllers (e.g. deployments, replicasets, etc.) using the same / overlapping selectors? Are you able to find its pods (`kubectl get pods -l <labels>`) after the delete failed?

**Comment by wangweihong** [comment] 2016-09-27 06:08
@janetkuo  This is my daemon set yaml file.
> apiVersion: extensions/v1beta1
> kind: DaemonSet
> metadata:
>   name: newrelic-agent
>   labels:
>     tier: monitoring
>     app: newrelic-agent
>     version: v1
> spec:
>   template:
>     metadata:
>       labels:
>         name: newrelic
>     spec:
>       # Filter to specific nodes:
>       # nodeSelector:
>       #  app: newrelic
>       hostPID: true
>       hostIPC: true
>       hostNetwork: true
>       containers:
>       - image: 192.168.18.250:5002/admin/testservice:1
>         name: newrelic
>         ports:
>         - containerPort: 10000
> 
Sorry , I can't reproduce this problem now.

**Comment by hpejustin** [comment] 2016-09-29 11:01
@wangweihong I also got this problem when i delete RS. I agree with @janetkuo, the reason maybe timeout for waiting the conditation of pod. I do not think this has any thing to do with Daemonset. Because not only Daemonset met this problem without clear occasion. I think this is a service side problem, maybe the process of apiserver interact with etcd.

**Comment by janetkuo** [comment] 2016-09-29 17:09
Not sure if it's related to garbage collector, cc @caesarxuchao

**Comment by caesarxuchao** [comment] 2016-09-29 17:15
If the problem occurs again, could you use `kubectl get xxx -o yaml` to print the hang object?

The garbage collector doesn't work for the daemonset yet, so I guess it's not the culprit, but I need to see the output I requested above to be sure.

**Comment by lethe3000** [comment] 2016-10-24 09:06
I met this problem when deploy [torus](https://github.com/coreos/torus/blob/master/contrib/kubernetes/torus-k8s-oneshot.yaml)
`$ kubectl get ds torus -o yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2016-10-24T08:49:17Z
  generation: 5
  labels:
    app: torus
  name: torus
  namespace: default
  resourceVersion: "17947"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/torus
  uid: bf28a02b-99c6-11e6-bbbf-14dda98006c2
spec:
  selector:
    matchLabels:
      daemon: torus
  template:
    metadata:
      creationTimestamp: null
      labels:
        daemon: torus
      name: torus
    spec:
      containers:
      - env:
        - name: ETCD_HOST
          value: $(ETCD_TORUS_SERVICE_HOST)
        - name: STORAGE_SIZE
          value: 20GiB
        - name: LISTEN_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: AUTO_JOIN
          value: "1"
        - name: DEBUG_INIT
          value: "1"
        - name: DROP_MOUNT_BIN
          value: "0"
        image: quay.io/coreos/torus:latest
        imagePullPolicy: Always
        name: torus
        ports:
        - containerPort: 40000
          name: peer
          protocol: TCP
        - containerPort: 4321
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-torus
      nodeSelector:
        af2b82cf-99c7-11e6-a1fb-14dda98006c2: af2b832c-99c7-11e6-a1fb-14dda98006c2
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /srv/torus
        name: data
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 2
`

**Comment by pbecotte** [comment] 2016-11-08 18:46
Got the same issue.

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2016-11-08T18:37:33Z
  generation: 3
  labels:
    app: nginx
  name: log-daemonset
  namespace: default
  resourceVersion: "1448469"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/log-daemonset
  uid: 6986a16e-a5e2-11e6-9567-0e331f3b19c0
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        486a2eb0-a5e3-11e6-94f3-f45c89c7a1cf: 486a2eef-a5e3-11e6-94f3-f45c89c7a1cf
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 3

**Comment by pbecotte** [comment] 2016-11-08 18:48
This was actually created by an integration test for my kubernetes python client.  This is the yaml

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-daemonset
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9

Deleting the daemonset using the http api works fine, only see this issue using kubectl.

**Comment by nak3** [comment] 2016-11-17 13:47
I hit this issue. In my case, when I deleted daemonset and it hang, some of pods were `Terminating` status.
I'm not sure if all of reporters hit same reason with me, but here is a step to reproduce and workaround (in my case).

#### 1. Stop one of node service and makes it `NotReady`

~~~
# kubectl get node
NAME                     STATUS     AGE
knakayam-ose33-smaster   Ready      37d
knakayam-ose33-snode1    NotReady   2m
~~~

#### 2. Deploy daemonset and confirm one pod doesn't have `Running` status.

~~~
# kubectl create -f log-daemonset.yaml (I tested @pbecotte's log-daemonset in above his comment.)

# kubectl get pod
NAME                              READY     STATUS              RESTARTS   AGE
log-daemonset-4z8xo               0/1       ContainerCreating   0          3m
log-daemonset-l4nxo               1/1       Running             0          5m
~~~

#### 3. Delete daemonset and observe the issue

~~~
# kubectl delete ds log-daemonset
 ... (hang) ...
~~~

#### 4. Confirm the pod running on `NotReady` host still `Terminating`

~~~
# kubectl get pod -o wide
NAME                              READY     STATUS              RESTARTS   AGE       IP        NODE
log-daemonset-4z8xo               0/1       Terminating         0          4m        <none>    knakayam-ose33-snode1
~~~

### workaround

#### 1. delete pod with `--grace-period=0`

~~~
# kubectl delete pod log-daemonset-4z8xo --grace-period=0
pod "log-daemonset-4z8xo" deleted
~~~

#### 2. delete daemonset

~~~
# kubectl delete ds log-daemonset
daemonset "log-daemonset" deleted
~~~

**Comment by wu8685** [comment] 2017-03-14 13:23
Hi,
I also encounter this issue on v1.5.3, and the work around above doesn't work to me.
The step `delete pod` is stuck.

**Comment by caesarxuchao** [comment] 2017-03-14 18:56
In the `kubectl get` output, the daemonset's metadate field doesn't have finalizers, so it's not caused by the garbage collector.

I think it's because the pods are not deleted timely, so it's a node teams issue @kubernetes/sig-node-bugs

**Comment by caesarxuchao** [comment] 2017-03-14 18:57
cc @yujuhong

**Comment by falenn** [comment] 2017-03-14 19:02
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (172/150 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:41296 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cnrco-0005RH-Hx
	for dev@imwiz.com; Tue, 14 Mar 2017 12:56:56 -0600
Date: Tue, 14 Mar 2017 11:56:39 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1489517799;
	bh=q0Z1B07IPSXSZXQ662PUM9j5k9W4Vf1f81/6TWKM/tA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=A4biEWJmo6WW5z6kFWxY0/eLVMmzBXivlzS0cffLNss13/+RSuPt0FzSJ3+1jjzVk
	 Fx4aqiyOmAJZDsitgvwabJyV13mczXB/bEhJjaOl7IGMvtrZQNGqQlB3Fi22HCcp/S
	 JnBctQypdFE6TpjI2rg8Ctcmo6Di/8s6gtxfa2bU=

**Comment by violalu** [comment] 2017-03-16 06:08
@wu8685 u can delete them by delete them in etcd

**Comment by wu8685** [comment] 2017-03-16 10:28
@violalu it works. thx

**Comment by mikedanese** [comment] 2017-03-22 22:41
If you are going to force delete, don't use etcd. Use `kubectl delete --now`

**Comment by mattdietz** [comment] 2017-04-12 16:34
On v1.5.3/029c3a408176b55c30846f0faedf56aae5992e9b at least, kubectl delete cannot under any circumstances delete a daemonset in this state. Every combination of flag sent to the command fails with a timeout.

**Comment by kargakis** [comment] 2017-04-12 17:15
We have seen various issues with client-side deletion. We moved it in the server in 1.6.

**Comment by janetkuo** [comment] 2017-04-12 20:47
@mattdietz when the daemonset deletion failed with a timeout, are the DaemonSet pods `Terminating`, `Running`, or already deleted? `kubectl delete` waits for all DaemonSet pods to be terminated before deleting the DaemonSet, so the state of those pods tell us what caused the timeout.

**Comment by cjyar** [comment] 2017-04-19 23:12
Seeing this problem with 1.6.1.

I created the calico-node ds, it was misconfigured, so I deleted it. All the pods were terminated, but the ds won't go away. I've tried --now and --force, but kubectl won't delete the ds. The node selector has been updated to randomUUID=randomUUID.

**Comment by janetkuo** [comment] 2017-04-19 23:24
> All the pods were terminated, but the ds won't go away. 

@cjyar just to be clear, when you say the pods were terminated, you mean that you didn't see them from `kubectl get pods` anymore, correct?

**Comment by janetkuo** [comment] 2017-04-19 23:55
I'm unable to reproduce it, so just brainstorming some possible causes.

If DaemonSet deletion timeout and...
1. if DaemonSet's `.spec.template.spec.nodeSelector` isn't updated to randomUUID=randomUUID: it's something to do with `kubectl delete`
1. else if at least one of its pods is still `Running`: it's something to do with DaemonSet controller 
1. else if at least one of its pod is `Terminating`: it's something to do with `kubelet`
1. else if its pods are all gone, and DaemonSet's `.status.currentNumberScheduled + .status.numberMisscheduled` isn't `0`: it's something to do with DaemonSet controller
1. else if its pods are all gone, and DaemonSet's status is correct: it's something to do with garbage collector

**Comment by cjyar** [comment] 2017-04-20 14:48
@janetkuo Yes, the pods didn't appear in `kubectl get pods`.

Before I deleted the ds, its pods were all in various states of failing or restarting. Each pod has two containers.

After I deleted the ds, .status.numberMisscheduled was 3, which was the original size of the ds.

**Comment by janetkuo** [comment] 2017-05-08 23:55
Just found this in a GCE cluster, `kubectl delete ds` hangs, the DaemonSet node selector was updated (to kills all pods), all pods are deleted, but the DaemonSet won't go away because `kubectl delete` was waiting for DaemonSet's `.status.currentNumberScheduled + .status.numberMisscheduled == 0`. 

The DaemonSet status wasn't updated because kube-controller-manager static pod was evicted (it got evicted because the DaemonSet was marked as critical). Therefore, `kubectl delete` hangs.

**Comment by vishh** [comment] 2017-05-09 04:30
And kube-controller-manager isn't marked as "Critical" and being a static
pod it does get restarted by the kubelet.

**Comment by vnandha** [comment] 2017-05-17 05:53
I faced the same issue on 1.6.0

It usually happens if anyone of the node is not responding ( or it is unable to delete the daemon set pod on one node)

In my case,  I had a faulty node daemon set status shows `NodeLost`, I tried doing delete daemonset, it took a while and timedout 

`error: timed out waiting for the condition`

Later the daemonset pod status became `unknown`

`sysdig-falco-kt42p   1/1       NodeLost    10         48d       ip-x   node-x`

`sysdig-falco-kt42p   1/1       Unknown    10         48d       ip-x   node-x`

I was able to delete the daemon after deleting that daemonset pod forcefully

`kubectl delete pod sysdig-falco-kt42p  --grace-period=0 --force now`


Could the daemonset controller not wait for the unresponsive Nodes?

**Comment by janetkuo** [comment] 2017-05-25 01:05
@vnandha `kubectl delete` deletes resource cascadingly by default. DaemonSet cannot finish cascading deletion without all of its pods be gone. You can resolve this by either forcefully delete that pod and then delete the DaemonSet, or delete the DaemonSet with `--cascade=false`, and then delete its pods manually.

**Comment by vnandha** [comment] 2017-05-26 02:32
@janetkuo IMO, deleting daemon sets with cascade=true should not wait indefinitely if a pod is already in unknown state.

**Comment by zhan849** [comment] 2017-06-01 04:34
any updates on this? Got same problem on 1.4.3.

Scenario: we need to upgrade host package and kubernetes, so we:
1. Teared down all our kubernetes components, including daemonset
2. Terminated master
3. Created new master with exactly same configuration: userdata (except some package update information), network, storage, storage mapping, etc.

After new master is up, looks like daemonset controller is not even running: it keeps on waiting for pods controller to sync.
```
admin@ip-10-16-3-9:~$ grep -nr "daemoncontroller.go" /var/log/kube-controller-manager.log
2294:I0601 02:47:30.289591       7 daemoncontroller.go:235] Starting Daemon Sets controller manager
2352:I0601 02:47:30.402988       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2353:I0601 02:47:30.403022       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2428:I0601 02:47:30.505066       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2429:I0601 02:47:30.505107       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2483:I0601 02:47:30.609750       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2484:I0601 02:47:30.609774       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2554:I0601 02:47:30.709821       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2556:I0601 02:47:30.713718       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2585:I0601 02:47:30.823060       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2586:I0601 02:47:30.823116       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2607:I0601 02:47:30.925286       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2608:I0601 02:47:30.925325       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2629:I0601 02:47:31.026989       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2630:I0601 02:47:31.027035       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2636:I0601 02:47:31.153362       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2640:I0601 02:47:31.153375       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2669:I0601 02:47:31.276009       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2676:I0601 02:47:31.297028       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2708:I0601 02:47:31.445570       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2713:I0601 02:47:31.445685       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2739:I0601 02:47:31.548948       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2752:I0601 02:47:31.663737       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2763:I0601 02:47:31.680314       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2776:I0601 02:47:31.795928       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2787:I0601 02:47:31.805898       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2805:I0601 02:47:31.921769       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2821:I0601 02:47:31.931862       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2840:I0601 02:47:32.044025       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2853:I0601 02:47:32.048735       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2906:I0601 02:47:32.153786       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
2919:I0601 02:47:32.154174       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2963:I0601 02:47:32.334012       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
2967:I0601 02:47:32.334212       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
3012:I0601 02:47:32.434262       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
3015:I0601 02:47:32.434442       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
3066:I0601 02:47:32.534925       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
3071:I0601 02:47:32.534999       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
3132:I0601 02:47:32.654638       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/node-exporter
3136:I0601 02:47:32.654873       7 daemoncontroller.go:631] Waiting for pods controller to sync, requeuing ds kube-system/volume-mounts-fixer
admin@ip-10-16-3-9:~$ 
admin@ip-10-16-3-9:~$ uptime
 04:29:09 up  1:43,  1 user,  load average: 3.75, 2.86, 2.38
admin@ip-10-16-3-9:~$ 

```


actually, not only daemonset controller: all controllers look like to be waiting for pod controller to sync.



As for daemonset: node selector is messed up:
```
k get daemonset node-exporter -o yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
    scheduler.alpha.kubernetes.io/critical-pod: ""
    scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
  creationTimestamp: 2017-05-31T01:15:45Z
  generation: 2
  labels:
    app: node-exporter
    role: axcritical
    tier: platform
  name: node-exporter
  namespace: kube-system
  resourceVersion: "52977442"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/node-exporter
  uid: abf7a662-459e-11e7-89f8-0637a9c18476
spec:
  selector:
    matchLabels:
      app: node-exporter
      role: axcritical
      tier: platform
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: node-exporter
        role: axcritical
        tier: platform
    spec:
      containers:
      - command:
        - /run.sh
        env:
        - name: CPU_MULT
          value: "4.0"
        - name: MEM_MULT
          value: "4.0"
        - name: DISK_MULT
          value: "4.0"
        - name: AX_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AX_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: AX_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AX_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: get.applatix.io/axsys/node-exporter:2.1.1-6f8ad17
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /host/proc
          name: proc-fs
        - mountPath: /host/sys
          name: sys-fs
        - mountPath: /rootfs
          name: root-fs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
      - name: applatix-registry
      nodeSelector:
        c413efb8-4670-11e7-8842-0242ac110002: c413f0ea-4670-11e7-8842-0242ac110002
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
        name: proc-fs
      - hostPath:
          path: /sys
        name: sys-fs
      - hostPath:
          path: /
        name: root-fs
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
```

**Comment by janetkuo** [comment] 2017-06-01 21:34
@zhan849 the hang you observed is because somehow all controller pod cache stores failed to sync (i.e. unrelated to DaemonSet controller or kubectl delete). @caesarxuchao @deads2k any idea why this would happen?

**Comment by zhan849** [comment] 2017-06-02 05:51
@janetkuo Thanks for pointing out. I replied here because similar phenomenon is described by other people. Please let me know if I need to open new bug for it.

**Comment by janetkuo** [comment] 2017-06-02 21:45
@zhan849 yes, please open a new bug with reproduce steps, K8s version, mention that all controllers keep waiting for pod store to sync, and cc sig api-machinery.

**Comment by janetkuo** [comment] 2017-06-02 21:58
@vnandha when the node is unreachable, the decision to delete the pods cannot be communicated to the kubelet until it re-establishes communication with the apiserver. In the meantime, the pods which are scheduled for deletion may continue to run on the partitioned node. https://kubernetes.io/docs/concepts/architecture/nodes/#condition

If you want to delete a DaemonSet cascadingly, all its pods need to be gone, otherwise it's not a complete cascading deletion. You need to handle that Unknown pod before deleting the DaemonSet: https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#deleting-pods

**Comment by zhan849** [comment] 2017-06-02 23:22
@janetkuo filed #46890, cannot find the sig api-machinery group. could you pls add it?

**Closed** 2018-02-24 03:58 UTC
Labels: area/kubectl, area/workload-api/daemonset, lifecycle/rotten, sig/cli
