### ISSUE TITLE
Rapidly terminating pod can result in incorrect failure because of OOM adjuster

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#23607] opened 2016-03-29 22:23 UTC
On a pod that had `command: ["/bin/false"]` I get an error from the OOM adjuster... when in reality, the error was the pod exiting quickly.

```
I0329 19:14:54.912855    5836 docker.go:161] Pulling image nginx without credentials
I0329 19:14:55.578436    5836 kubelet.go:1235] container: default/nginx/init podIP: "172.17.0.2" creating hosts mount: true
E0329 19:14:56.532977    5836 pod_workers.go:138] Error syncing pod 84a2ddee-f5e2-11e5-b0cb-080027c5bfa9, skipping: failed to "StartContainer" for "init" with RunContainerError: "failed to apply oom-score-adj to container \"exceeded maxTries, some processes might not have desired OOM score\"- /k8s_init.b9b1de00_nginx_default_84a2ddee-f5e2-11e5-b0cb-080027c5bfa9_b076a7bb"
I0329 19:14:56.532985    5836 helpers.go:101] Unable to get network stats from pid 7047: couldn't read network stats: failure opening /proc/7047/net/dev: open /proc/7047/net/dev: no such file or directory
I0329 19:14:56.533111    5836 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"84a2ddee-f5e2-11e5-b0cb-080027c5bfa9", APIVersion:"v1", ResourceVersion:"66", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "init" with RunContainerError: "failed to apply oom-score-adj to container \"exceeded maxTries, some processes might not have desired OOM score\"- /k8s_init.b9b1de00_nginx_default_84a2ddee-f5e2-11e5-b0cb-080027c5bfa9_b076a7bb"
```

That error is incorrect - the pod exited with 1, but oomscore masked the container failure.

OOM score shouldn't be overriding the real error here.

**Comment by smarterclayton** [comment] 2016-03-29 22:26
This blocks being able to test some of these code paths easily (since I can't rely on the right error coming back).

**Comment by smarterclayton** [comment] 2016-04-01 17:41
This may be https://github.com/kubernetes/kubernetes/pull/21741

**Comment by dchen1107** [comment] 2016-04-01 18:13
#21741 should eliminate the issue caused by race with docker 1.10. But I thought https://github.com/kubernetes/kubernetes/pull/20169 should correct reporting of the status of an exit container. Assigned this to @vishh

**Comment by smarterclayton** [comment] 2016-04-01 18:16
I was on Docker 1.9.1-6 which I know is terribly ancient but is all fedora has.

**Comment by vishh** [comment] 2016-04-01 18:24
I thought I fixed it in #20169. Err... Will take a look at it later today. Do we want to fix this in v1.2?

**Comment by smarterclayton** [comment] 2016-04-01 18:37
This appears to break containers (at least, to an API consumer) that
execute very quickly - in my case it was something calling /bin/true, but
it's likely that very fast containers all exhibit some variant of this
behavior.

**Comment by vishh** [comment] 2016-04-01 20:57
So needs a fix in v1.2?

**Comment by smarterclayton** [comment] 2016-04-01 21:33
I'm not sure it affects more than docker 1.9.1-6 yet, or whether it's the
difference between 0.02 second startups and anything longer.  Was hoping
other people would have hit it.

**Comment by binarybana** [comment] 2016-04-15 18:20
We just saw this in 1.2.2 using Docker 1.10.3.

**Comment by smarterclayton** [comment] 2016-04-15 19:13
We've been running with the patch and the flake has gone away.  1.2.3 should contain this (as of current setup).

**Closed** 2016-05-23 19:46 UTC
Labels: area/usability, kind/bug, priority/P1, team/node

**Comment by hex108** [comment] 2016-12-01 10:23
We just saw this in kubernetes 1.4.1 with docker 1.9.1.

<pre>
...
I1130 10:02:51.966816    5569 oom_linux.go:110] pid 6075 needs to be set
I1130 10:02:51.966823    5569 oom_linux.go:69] attempting to set "/proc/6075/oom_score_adj" to "992"
I1130 10:02:51.966842    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.966859    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.966872    5569 oom_linux.go:85] failed to set "/proc/6075/oom_score_adj" to "992": write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.966879    5569 oom_linux.go:116] cannot adjust oom score for pid 6075 - write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.966991    5569 oom_linux.go:110] pid 6075 needs to be set
I1130 10:02:51.966997    5569 oom_linux.go:69] attempting to set "/proc/6075/oom_score_adj" to "992"
I1130 10:02:51.967010    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967020    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967025    5569 oom_linux.go:85] failed to set "/proc/6075/oom_score_adj" to "992": write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967031    5569 oom_linux.go:116] cannot adjust oom score for pid 6075 - write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967138    5569 oom_linux.go:110] pid 6075 needs to be set
I1130 10:02:51.967144    5569 oom_linux.go:69] attempting to set "/proc/6075/oom_score_adj" to "992"
I1130 10:02:51.967157    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967167    5569 oom_linux.go:79] write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967171    5569 oom_linux.go:85] failed to set "/proc/6075/oom_score_adj" to "992": write /proc/6075/oom_score_adj: invalid argument
I1130 10:02:51.967177    5569 oom_linux.go:116] cannot adjust oom score for pid 6075 - write /proc/6075/oom_score_adj: invalid argument
E1130 10:02:51.967208    5569 docker_manager.go:2254] container start failed: RunContainerError: Failed to apply oom-score-adj to container "/k8s_ff.5a8d8d57_ff-3757651080-fdxus_demo_5976b286-b623-11e6-a30a-525400ab7909_e7e58d2a"- exceeded maxTries, some processes might not have desired OOM score
E1130 10:02:51.967278    5569 pod_workers.go:184] Error syncing pod 5976b286-b623-11e6-a30a-525400ab7909, skipping: failed to "StartContainer" for "ff" with RunContainerError: "Failed to apply oom-score-adj to container \"/k8s_ff.5a8d8d57_ff-3757651080-fdxus_demo_5976b286-b623-11e6-a30a-525400ab7909_e7e58d2a\"- exceeded maxTries, some processes might not have desired OOM score"
</pre>

There is no time interval between each retry. If the container was finishing, we could not figure it out why it says "write ... : invalid argument". After we add some sleep between each retry to set oom score, the error message seems more clear, the error message becomes "/proc/6075/oom_score_adj does not exist" because the container finishes.

**Comment by vishh** [comment] 2016-12-01 10:45
Docker v1.10+ should not have this issue. Can you upgrade your docker version?

**Comment by hex108** [comment] 2016-12-01 11:33
Thanks, v.1.10+ looks fine. It will take some time to upgrade to v1.10+. It might be better if we could handle it well in kubelet, the small patch is at https://github.com/hex108/kubernetes/commit/3e856756687863cf033804dae5d30cd7536f63e0.

**Comment by vishh** [comment] 2016-12-01 11:39
Patch looks benign to me. Why don't you post it upstream?

**Comment by hex108** [comment] 2016-12-01 11:47
Add a PR https://github.com/kubernetes/kubernetes/pull/37808 for it.
