### ISSUE TITLE
configmaps "ingress-uid" not found failing 1.11 gke-ingress and gke- master-cluster upgrade and downgrade tests

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#65311] opened 2018-06-21 13:34 UTC
## Failing Jobs and Tests
* [gke-ingress-1.11](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-ingress-1.11)
* [gke-gci-1.10-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel)
* [gke-gci-master-gci-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel)

## Error
* [Upgrade test failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5368)
* [Ingress failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-ingress/3106)

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/cluster_upgrade.go:136
Expected error:
    <*errors.StatusError | 0xc420198bd0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "configmaps \"ingress-uid\" not found",
            Reason: "NotFound",
            Details: {Name: "ingress-uid", Group: "", Kind: "configmaps", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    configmaps "ingress-uid" not found
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/ingress.go:86

A bunch of gke-ingress and upgrade, downgrade tests started failing on the above  ingress errro after the merges / CPs yesterday as indicated by the [change log](https://github.com/kubernetes/kubernetes/compare/8745ea56e...5f5d6aa92). @liggitt I am assigning to you for initial investigation. Please re-triage as you see fit.

/kind bug
/priority critical-urgent
/assign @liggitt 
/cc @MrHohn @rramkumar1 @krousey @roberthbailey 
/cc @jberkus @tpepper @dims as FYI
/milestone v1.11

**Comment by MaciekPytel** [comment] 2018-06-21 13:40
This also happens on non-upgrade 1.10 jobs: https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gci-gke-ingress-1.10. It doesn't seem caused by change in the kubernetes/kubernetes, because there was a passing run on the same commit.

**Comment by liggitt** [comment] 2018-06-21 13:49
I don't have visibility to gke jobs... will need to be a googler.

/unassign
/assign @MaciekPytel 
for investigation or reassignment

**Comment by MaciekPytel** [comment] 2018-06-21 13:56
/assign @nicksardo 
cc: @bowei 

Can you take a look or reassign?

**Comment by jberkus** [comment] 2018-06-21 15:40
So, the fact that GCE-ingress is failing, and that the failure started at midnight pacific time, suggests that this is due to a change pushed by the GKE folks, and not due to changes in Kubernetes at all.

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ingress

Can someone from test-infra explain why gke-ingress is in blocking, and gce-ingress isn't?  Unless we have reason to believe that gce-ingress test is somehow deficient, I'm inclined to chalk this one up to "more internal GKE breakage".

**Comment by AishSundar** [comment] 2018-06-21 16:04
@jberkus gce-ingress is also in the release blocking dashboard and is not failing (as you indicated above). So it is a GKE only issue.

https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-ingress-1.11

**Comment by rramkumar1** [comment] 2018-06-21 16:28
The problem is purely on the GKE side, no cherry-pick into 1.11 is needed.

**Comment by guineveresaenger** [comment] 2018-06-21 20:31
Can someone update the labels for status tracking? It looks like we will _not_ include this for 1.11?

**Comment by AishSundar** [comment] 2018-06-22 03:02
@guineveresaenger the fix, purely GKE, has been pushed and as per @rramkumar1 it will take ~6hrs to propagate. I am still for tests to clean up, no luck thus far.That said its a GKE specific issue n doesnt need CP into 1.11

**Closed** 2018-12-29 02:50 UTC
Labels: kind/bug, lifecycle/rotten, milestone/incomplete-labels, priority/critical-urgent, priority/important-soon, sig/gcp
