### ISSUE TITLE
Schedule all pods at the same time (for stateless services)

### ISSUE THREAD

**Issue by oliverhausler** [kubernetes/kubernetes#98840] opened 2021-02-06 18:23 UTC
**What would you like to be added**:

When a service is updated, pods are switched one by one (pod started, traffic switched, previous pod stopped). I would like to have an option which first starts all pods, then switches traffic at the same time, then stops all previous pods.

**Why is this needed**:

Changing pods one by one is perfect for stateful services, but often not so good for stateless services. Example:

Websites can and will often fail while switching pods, because the HTML may come from a new server, but other resources may still be served (when round-robin is used) from a previous pod. This renders some resources unavailable, and if it happens with a CSS resource, it breaks the page until the update is complete.

A more specific example: Websites are often packaged with webpack. It is good practice to bundle all resources, including CSS, into a bundle created from a UUID, e.g. `1234567890.css` (where `1234567890` is the UUID), which is unwrapped on the client. This file is set to be cached indefinitely, as the next build uses a different UUID. If such website is served with k8s, it often breaks during the build, because round-robin is used for access to pods, and the HTML is served from a new version, while the bundle is tried to be served from an old version (where is doesn't exist yet).

It would be a lot smarter, if that's technically feasible, to switch all pods of a stateless service in the very same moment.

**Comment by neolit123** [comment] 2021-02-08 00:35
/sig network scheduling
^ adjust if needed.

**Comment by dougsland** [comment] 2021-02-18 20:53
Hi @oliverhausler 

I am wondering if what you are looking for is kind of Blue/Green (Rainbow) Deployments:
https://kubernetes.io/blog/2018/04/30/zero-downtime-deployment-kubernetes-jenkins/

Instead killing/replacing pods one at time, a new deployment is created and new separate stack of pods running v2 is launched (besides v1 deployment). Keep in mind that your cluster will need to be powerful to run twice number of replicas/pods for your application.

For example, you can switch the traffic to only pods labeled deployment: blue (and vice-versa)

```
apiVersion: v1
kind: Service
metadata:
name: demo
  ports:
   - port: 8080
     protocol: TCP
     targetPort: 8080
   selector:
     app: demo
     deployment: blue
   type: ClusterIP
```

**Comment by thockin** [comment] 2021-02-18 21:47
What @dougsland says is correct, I think.  You don't need Kubernetes to change to achieve this (more or less).

I say "more or less" because, fundamentally, there is no such thing as "all at once" in a system like Kubernetes.  Different nodes can be delayed in their reaction to changes.

For example, assume you deploy app v1, and select it in a service.  You might hit: 

* deploy app-v2
* switch the selector
* node 1 sees the endpoints change and updates to v2
* incoming traffic hits node 1
* a resource needs another GET
* 2nd get lands on node 2
* node 2 has not observed (or maybe not reacted to) the endpoints change
* hits app-v1

Whether this is possible depends on some variables like how you ingress traffic, which cloud and LB type, etc.

**Comment by thockin** [comment] 2021-02-18 21:48
Since this is not a bug or feature-request, I suggest we close it.  Happy to discuss further, if you like.

**Comment by oliverhausler** [comment] 2021-02-20 23:05
_Sorry for responding late, guys._

@dougsland Yes, it's sort of blue/green what I am looking for. blue/green may work for production, but for continuous integration during development, it is not a viable thing to do.
@thockin Correct, it will never be possible to switch at the very same moment, but for stateless services, having different versions co-exist at the same time is very bad. So the time should be as short as possible, which it is not, when pods are deployed sequentially.

But again, I believe the algorithm, when to switch pods, should be part of k8s. I believe there are two kinds of pods (stateful, stateless) and k8s should simply account for this by offering the different deployment patterns for the different needs.

_The same can be achieved at the ingress level, for example by targeting the same pod after the first request, instead doing round-robin, but it's not best practice I guess. And I can think of different packaging modes as well, but I'd really love to see this in k8s as it is the "silver bullet". It would really help._

**Comment by dougsland** [comment] 2021-02-21 20:19
> _Sorry for responding late, guys._
> 
> @dougsland Yes, it's sort of blue/green what I am looking for. blue/green may work for production, but for continuous 
> integration during development, it is not a viable thing to do.

I don't have the details from the development process you guys have but another way to do it is using A/B Testing. Which basically you deploy two versions of the software (master/devel) for testing new features and based on tests you can increase/decrease the percentage of traffic/users going to master or devel site without loosing any user connection.

**Comment by olivierlemasle** [comment] 2021-02-21 20:49
@dougsland I guess you mentioned the wrong Oliver ;-)

cc @oliverhausler

**Comment by dougsland** [comment] 2021-02-22 15:00
Closing this one, feel free to re-open if you have more questions.
/close

**Closed** 2021-02-22 15:00 UTC
Labels: kind/feature, needs-triage, sig/network, sig/scheduling
