### ISSUE TITLE
[ Failing test ] gce-cos-master-serial [sig-cluster-lifecycle] Nodes [Disruptive] Resize

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#80960] opened 2019-08-04 12:26 UTC
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to add nodes
[sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to delete nodes

**Since when has it been failing**:
30 July 2019 since today

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial&width=20

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:112
Unexpected error:
    <*errors.errorString | 0xc0039f06d0>: {
        s: "failed to wait for pods responding: timed out waiting for the condition",
    }
    failed to wait for pods responding: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:121
```
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:142
Unexpected error:
    <*errors.errorString | 0xc0046601d0>: {
        s: "failed to wait for pods responding: timed out waiting for the condition",
    }
    failed to wait for pods responding: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:152
```

/sig cluster-lifecycle

**Comment by alejandrox1** [comment] 2019-08-05 13:48
Thanks for opening this issue!
This one is a duplicate of https://github.com/kubernetes/kubernetes/issues/79662
You can see it in the ci signal project board https://github.com/orgs/kubernetes/projects/11
/close

**Closed by alejandrox1** 2019-08-05 13:48 UTC
Labels: kind/failing-test, sig/cluster-lifecycle
