### ISSUE TITLE
Canary CSI snapshot tests are failing

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#112126] opened 2022-08-30 15:08 UTC
### Which jobs are failing?

ci-kubernetes-csi-canary-test-on-kubernetes-master, [example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-canary-test-on-kubernetes-master/1564570330624692224)

### Which tests are failing?

[It] [sig-storage] CSI mock volume CSI Volume Snapshots [Feature:VolumeSnapshotDataSource] volumesnapshotcontent and pvc in Bound state with deletion timestamp set should not get deleted while snapshot finalizer exists
[It] [sig-storage] CSI mock volume CSI Volume Snapshots secrets [Feature:VolumeSnapshotDataSource] volume snapshot create/delete with secrets

### Since when has it been failing?

25-08-2022?

### Testgrid link

https://testgrid.k8s.io/sig-storage-csi-ci#canary-test-on-master

### Anything else we need to know?

Looking at "volume snapshot create/delete with secrets" test, it finishes OK, but the "Cleaning up resources" freezes for ~30 minutes:

```
    STEP: Deleting storageclass csi-mock-volumes-53205mbx6 08/30/22 12:35:21.996
    STEP: Cleaning up resources 08/30/22 12:35:22.006
    STEP: deleting the test namespace: csi-mock-volumes-5320 08/30/22 13:07:03.001
```

After these 30 minutes, the test timeouts and kills API server and etcd a and everything fails miserably.

Stack trace from "Cleaning up resources", it's stuck at shutting down gRPC server:

```
sync.(*WaitGroup).Wait(0xc0032997d0?)
        /home/jsafrane/.gimme/versions/go1.19.linux.amd64/src/sync/waitgroup.go:139 +0x52 fp=0xc003a0b850 sp=0xc003a0b828 pc=0x25837b2
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Stop.func1()
        vendor/google.golang.org/grpc/server.go:1709 +0x2e fp=0xc003a0b870 sp=0xc003a0b850 pc=0x3870f8e
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Stop(0xc0005bba40)
        vendor/google.golang.org/grpc/server.go:1742 +0x382 fp=0xc003a0ba00 sp=0xc003a0b870 pc=0x3870e62
k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/driver.stop(0x0?, 0x0?, 0x68c0da0?, 0x0?)
        test/e2e/storage/drivers/csi-test/driver/driver.go:174 +0xa5 fp=0xc003a0ba50 sp=0xc003a0ba00 pc=0x5e8b9e5
k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/driver.(*CSIDriver).Stop(...)
        test/e2e/storage/drivers/csi-test/driver/driver.go:133
k8s.io/kubernetes/test/e2e/storage/drivers.(*mockCSIDriver).PrepareTest.func2()
        test/e2e/storage/drivers/csi.go:605 +0x52 fp=0xc003a0ba98 sp=0xc003a0ba50 pc=0x5ef0cb2
k8s.io/kubernetes/test/e2e/storage/drivers.(*mockCSIDriver).PrepareTest.func4()
        test/e2e/storage/drivers/csi.go:692 +0x25 fp=0xc003a0bab0 sp=0xc003a0ba98 pc=0x5ef0925
```

### Relevant SIG(s)

/sig storage

**Comment by jsafrane** [comment] 2022-08-30 15:22
I reproduced this issue in somewhat hacked [prow.sh](https://github.com/kubernetes-csi/external-provisioner/blob/master/release-tools/prow.sh) from external-provisioner (or any other kubernetes-csi repo). The script compiles Kubernetes master from a fresh checkout, runs it in KIND, installs hostpath CSI driver with canary images and runs e2e tests for the CSI driver like this:

```
ginkgo   '-focus=(External.Storage|CSI.mock.volume)' '-skip=\[Serial\]|\[Disruptive\]' /home/jsafrane/project/go/src/k8s.io/kubernetes/_output/bin/e2e.test -- -report-dir /home/jsafrane/project/go/pkg/csiprow.ZgXun5lpJl/artifacts -storage.testdriver=/home/jsafrane/project/go/pkg/csiprow.ZgXun5lpJl/test-driver.yaml
```

"hostpath CSI driver with canary images" is the interesting part - when I run the test with the latest tagged images, it succeeds, when using canaries it freezes at the cleanup. I found out that using the latest tagged images for everything **except** `gcr.io/k8s-staging-sig-storage/csi-node-driver-registrar:canary` is enough to freeze the cleanup. And further I was able to check that node-driver-registrar at commit [c560a1e2982cf0396e0b245c507b3b9896145e94](https://github.com/kubernetes-csi/node-driver-registrar/commit/c560a1e2982cf0396e0b245c507b3b9896145e94) works, while master does not. There are just 2 commits in between: new release-tools and update to v1.25 libraries. I suspect it's the new libraries.

I still don't understand how node-driver-registrar and its libraries could affect gRPC between the hostpath CSI driver and e2e.test binary.

**Comment by jsafrane** [comment] 2022-08-30 15:24
@pohly does this ring a bell? I though node-driver-registrar does not do anything with proxied "mock" CSI calls between e2e.test and the CSI driver. In addition, why only these two tests fail reliably, while the rest works?

**Comment by jsafrane** [comment] 2022-08-30 15:26
For the record, this is diff in k/k that adds canary node-driver-registrar to e2e.test. This diff is enough to make the tests fail:

```diff
--- a/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
+++ b/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
@@ -35,7 +35,7 @@ spec:
             - mountPath: /csi
               name: socket-dir
         - name: driver-registrar
-          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.3.0
+          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:canary
           args:
             - --v=5
             - --csi-address=/csi/csi.sock
```

**Comment by pohly** [comment] 2022-08-30 16:09
This does not ring a bell at all. You are right that csi-node-driver-registrar should not be involved in the gRPC communication between e2e.test and the driver. Does it communicate with the driver after the initial registration?

If yes, then that will lead into connections that need to be proxied, which might prevent the shutdown. Just a wild guess.

But even then it's not clear how grpc.Server.Stop can get stuck. According to its documentation, "It immediately closes all open connections and listeners.". Hmm, could the proxy code get stuck when its listener is closed?

**Comment by jsafrane** [comment] 2022-08-30 16:10
There is `WaitGroup` in `grpc.Server.Stop` that gets stuck, I did not check what is in that group.

**Comment by pohly** [comment] 2022-09-05 13:23
> -          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.3.0
> +          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:canary

Well, of course it fails :sweat_smile:  There is no such canary image.

Hmm, but then why do other tests pass? They all use `registry.k8s.io/sig-storage/*:canary`.

**Comment by jsafrane** [comment] 2022-09-05 13:25
There is some magic in your script that replaces `registry` with `gcr.io`, the registrar runs and registers the driver in the end.

**Comment by pohly** [comment] 2022-09-05 13:32
Yep:
```
       # We cannot replace registry.k8s.io/sig-storage with gcr.io/k8s-staging-sig-storage because
        # e2e.test does not support it (see test/utils/image/manifest.go). Instead we
        # invoke the e2e.test binary with KUBE_TEST_REPO_LIST set to a file that
        # overrides that registry.
        find "$source/test/e2e/testing-manifests/storage-csi/mock" -name '*.yaml' -print0 | xargs -0 sed -i -e 's;registry.k8s.io/sig-storage/\(.*\):v.*;registry.k8s.io/sig-storage/\1:canary;'
        cat >"$target/e2e-repo-list" <<EOF
sigStorageRegistry: gcr.io/k8s-staging-sig-storage
EOF
        cat >&2 <<EOF
```

**Comment by pohly** [comment] 2022-09-05 13:49
One difference is that the driver-registrary canary no longer detects the loss of connection to the mock proxy. Previously it did:
```
csi-mockplugin-0/driver-registrar@127.0.0.1: E0905 13:10:27.883619       1 connection.go:132] Lost connection to unix:///csi/csi.sock.
```

It could be that the proxy code relies on the remote side to close their side of the connection before considering everything shut down. That is necessary because the remote side might still send some data that needs to be received. If the remote side keeps the connection open, everything freezes. One can argue that it shouldn't block forever, but the bigger question is why "Lost connection" is not detected anymore with the more recent gRPC.

**Comment by pohly** [comment] 2022-09-05 14:25
The "exit on connection loss" depends on our dialer being called again by gRPC:
https://github.com/kubernetes-csi/csi-lib-utils/blob/7ac934120a9dc2e36bc9fb93e70410e7181bc5b8/connection/connection.go#L128-L149

**Comment by pohly** [comment] 2022-09-05 16:13
/assign

No idea yet, but I'll keep looking...

**Comment by pohly** [comment] 2022-09-05 20:54
I can reproduce the same failure to shut down also in other tests. Must be a timing issue that it only occurred for the same two tests in the CI - not a very satisfying explanation, unfortunately.

I have something that works for me locally: closing connections when shutting down the listener -> see https://github.com/kubernetes/kubernetes/pull/112251

**Closed** 2022-09-12 15:07 UTC
Labels: sig/storage, kind/failing-test, needs-triage
