### ISSUE TITLE
Incorrect parsing of YAML strings

### ISSUE THREAD

**Issue by jieyu** [kubernetes/kubernetes#90905] opened 2020-05-08 19:38 UTC
**What happened**:

Trying to apply the following pod would result in a parse error:

```
Error from server (BadRequest): error when creating "bug.yaml": Pod in version "v1" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Args: []string: ReadString: expects " or n, but found 9, error found in #10 byte of ...|:["echo",999],"image|..., bigger context ...|"default"},"spec":{"containers":[{"args":["echo",999],"image":"debian:buster","imagePullPolicy":"Alw|...
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: bug
spec:
  containers:
  - image: debian:buster
    imagePullPolicy: Always
    name: bug
    stdin: true
    tty: true
    args:
    - echo
    - 0999
```

The problem is the `0999` part. Since it's not a valid octal number, it should be treated as string and not quote is needed. This can be validated by multiple ways:

1. Check this online [yaml->json conversion tool ](https://onlineyamltools.com/convert-yaml-to-json?input=apiVersion%3A%20v1%0Akind%3A%20Pod%0Ametadata%3A%0A%20%20name%3A%20bug%0Aspec%3A%0A%20%20containers%3A%0A%20%20-%20image%3A%20debian%3Abuster%0A%20%20%20%20imagePullPolicy%3A%20Always%0A%20%20%20%20name%3A%20bug%0A%20%20%20%20stdin%3A%20true%0A%20%20%20%20tty%3A%20true%0A%20%20%20%20args%3A%0A%20%20%20%20-%20echo%0A%20%20%20%20-%200999&indent-use-spaces=true&indent-spaces=2&indent-use-tabs=false)
2. Use python's default yaml package:
```
$ python
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.load('arg: 0999')
{'arg': '0999'}
```

**What you expected to happen**:

The above pod yaml should not result in parse error.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Konvoy on AWS
- OS (e.g: `cat /etc/os-release`):
CentOS 7
- Kernel (e.g. `uname -a`):
3.10
- Install tools:
Konvoy (kubeadm)
- Network plugin and version (if this is a network-related bug):
Calico CNI
- Others:

**Comment by liggitt** [comment] 2020-05-08 19:49
thanks for the report, this is a duplicate of https://github.com/kubernetes/kubernetes/issues/82296

/close

**Closed** 2020-05-08 19:49 UTC
Labels: kind/bug, sig/api-machinery
