### ISSUE TITLE
Validation error v1 yaml file

### ISSUE THREAD

**Issue by Yzord** [kubernetes/kubernetes#23273] opened 2016-03-21 10:53 UTC
I am trying to learn and understand Kubernetes so i created a cluster for it and wanted to deploy some services on them.

I follow the manual from Red Hat, because i use the RHELAH version from them. At some point (https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-containers/chapter-3-creating-a-kubernetes-cluster-to-run-docker-formatted-container-images chapter 3.7) i have to create some yaml files. One of them is creating one for the replicationcontroller. Red Hat gives me this example:

```
kind: ReplicationController
apiVersion: v1
metadata:
     name: db-controller
spec:
  replicas: 2
  selector:
    name: db
  template:
    spec:
      containers:
      - name: db
        image: dbforweb
        ports:
          - containerPort: 3306
    metadata:
      labels:
        name: "db"
      selectorname: "db"
  labels:
    name: "db"`
```

and finish it of with

> kubectl create -f db-rc.yaml

but no matter what i try, it always gives me this error:

>error validating "db-rc.yaml": error validating data: [found invalid field labels for v1.ReplicationControllerSpec, found invalid field selectorname for v1.ObjectMeta]; if you choose to ignore these errors, turn validation off with --validate=false

I have searched the web, but couldn't find anything specific about it. And because i use apiVersion v1 i guess the code is fairly new.

At this point i'm stuck and don't know what to do now. So hopefully someone wants to point me to the right direction.

OS: RHELAH latest version
Kubernetes: Gitversion 1.2.0
Docker version: 1.8.2-el7

ps, i dont know why the code is lined up to the left. Can't get it right :(

**Comment by zhouhaibing089** [comment] 2016-03-21 14:40
@Yzord You should use code block instead of the quote grammar.

```yaml
kind: ReplicationController
apiVersion: v1
metadata:
   name: db-controller
spec:
  replicas: 2
  selector:
    name: db
  template:
    spec:
      containers:
      - name: db
        image: dbforweb
        ports:
          - containerPort: 3306
    metadata:
      labels:
        name: "db"
      selectorname: "db"
  labels:
    name: "db"
```

I feel that the code you pasted is not well aligned, maybe fixed like this:

```yaml
kind: ReplicationController
apiVersion: v1
metadata:
   name: db-controller
spec:
  replicas: 2
  selector:
    name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: dbforweb
        ports:
        - containerPort: 3306
```

**Comment by AdoHe** [comment] 2016-03-21 17:46
Please always make sure yaml file is validate, especially the difference between map and array.

**Comment by Yzord** [comment] 2016-03-21 17:49
How can i check something like that?

**Comment by thockin** [comment] 2016-03-22 00:44
This was validated - the errors came from validation, and they were both indenting errors (yay YAML!)

```
kind: ReplicationController
apiVersion: v1
metadata:
     name: db-controller
spec:
  replicas: 2
  selector:
    name: db
  template:
    spec:
      containers:
      - name: db
        image: dbforweb
        ports:
          - containerPort: 3306
    metadata:
      labels:
        name: "db"
      # This next line is wrong - it needs to be indented under "labels"
      selectorname: "db"
  # This next line is wrong - it is currently under "spec", but it's not clear where it should go
  labels:
    name: "db"
```

**Comment by thockin** [comment] 2016-03-22 00:45
Closing this as a support issue.  Support issues are better handled on Slack or StackOverflow.

**Closed by thockin** 2016-03-22 00:45 UTC
Labels: team/CSI-API Machinery SIG

**Comment by jianzhangbjz** [comment] 2016-06-28 09:05
@thockin Thanks, I encounter the same indent error and have fixed it now. But, are there any docs about the indent  grammar?

**Comment by thockin** [comment] 2016-07-01 07:27
http://yaml.org/spec/ ?

**Comment by ye** [comment] 2016-07-13 22:18
Got the exact same error message as OP for the past weeks. Finally I was able to resolve it. The culprit was actually NOT because of yaml syntax error but rather an YAML spec error.

```bash
$ kubectl apply -f templates/letsencrypt_register.yml 
error validating "templates/letsencrypt_register.yml": error validating data: found invalid field label for v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false
```

Here is the content of`templates/letsencrypt_register.yml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
    label:
    name: letsencrypt
spec:
  selector:
    job-name: letsencrypt-register
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
```
And the offending bits was the the ".metadata.label", removing it solves the problem. 

Note that it passes the YAML online validator http://yaml-online-parser.appspot.com perfectly fine. 
**If `kubectl` were to able to pinpoint the root cause was actually a spec error or a syntax error, I would have saved tons of time figure this out already. So to me, this is still a documentation/error improvement issue**

Unfortunately, there isn't any good YAML command line tools available - I mean, there are plenty of one-liner solutions by using pyyaml / ruby / perl on the command line but none of them seem to be elegant and more often than not people forget them.

**Comment by heinrichbeukes** [comment] 2018-10-23 06:35
Had the same error, couldn't see why the code yaml was broken, so I added the --validate=false flag, and the script executed normally.

it's not a fix but it helps 2AM in the morning

**Comment by dims** [comment] 2018-10-23 12:58
long-term-issue (note to self)

**Comment by rishimallik1** [comment] 2020-01-23 03:53
> I am trying to learn and understand Kubernetes so i created a cluster for it and wanted to deploy some services on them.
> 
> I follow the manual from Red Hat, because i use the RHELAH version from them. At some point (https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-containers/chapter-3-creating-a-kubernetes-cluster-to-run-docker-formatted-container-images chapter 3.7) i have to create some yaml files. One of them is creating one for the replicationcontroller. Red Hat gives me this example:
> 
> ```
> kind: ReplicationController
> apiVersion: v1
> metadata:
>      name: db-controller
> spec:
>   replicas: 2
>   selector:
>     name: db
>   template:
>     spec:
>       containers:
>       - name: db
>         image: dbforweb
>         ports:
>           - containerPort: 3306
>     metadata:
>       labels:
>         name: "db"
>       selectorname: "db"
>   labels:
>     name: "db"`
> ```
> 
> and finish it of with
> 
> > kubectl create -f db-rc.yaml
> 
> but no matter what i try, it always gives me this error:
> 
> > error validating "db-rc.yaml": error validating data: [found invalid field labels for v1.ReplicationControllerSpec, found invalid field selectorname for v1.ObjectMeta]; if you choose to ignore these errors, turn validation off with --validate=false
> 
> I have searched the web, but couldn't find anything specific about it. And because i use apiVersion v1 i guess the code is fairly new.
> 
> At this point i'm stuck and don't know what to do now. So hopefully someone wants to point me to the right direction.
> 
> OS: RHELAH latest version
> Kubernetes: Gitversion 1.2.0
> Docker version: 1.8.2-el7
> 
> ps, i dont know why the code is lined up to the left. Can't get it right :(

same error for me too.Could anyone help me in sorting out this
