### ISSUE TITLE
test-cmd secret flake

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#40521] opened 2017-01-26 15:10 UTC
Looks like test-cmd secrets may have developed a flake while the tests were disabled.  Seeing

```
I0126 06:59:17.164] test-cmd-util.sh:1587: Successful get secret/secret-string-data --namespace=test-secrets  {{.data}}: map[k1:djE= k2:djI=]
I0126 06:59:17.251] (Btest-cmd-util.sh:1588: Successful get secret/secret-string-data --namespace=test-secrets  {{.data}}: map[k1:djE= k2:djI=]
I0126 06:59:17.838] (Btest-cmd-util.sh:1589: Successful get secret/secret-string-data --namespace=test-secrets  {{.stringData}}: <no value>
I0126 06:59:17.920] (Bsecret "secret-string-data" deleted
W0126 06:59:18.020] /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh: line 72: 11751 Terminated              kubectl proxy --port=0 --www=. --api-prefix="$1" > ${PROXY_PORT_FILE} 2>&1
W0126 06:59:18.021] E0126 06:59:15.097471   11543 namespace_controller.go:367] Failed to ensure delete object from underlying clusters finalizer in namespace my-namespace: failed to add finalizer orphan to namespace : Operation cannot be fulfilled on namespaces "my-namespace": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.021] E0126 06:59:15.100182   11543 namespace_controller.go:367] Failed to ensure delete object from underlying clusters finalizer in namespace my-namespace: failed to add finalizer orphan to namespace : Operation cannot be fulfilled on namespaces "my-namespace": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.021] E0126 06:59:15.433898   11543 namespace_controller.go:367] Failed to ensure delete object from underlying clusters finalizer in namespace test-secrets: failed to add finalizer orphan to namespace : Operation cannot be fulfilled on namespaces "test-secrets": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.021] No resources found.
W0126 06:59:18.021] E0126 06:59:15.691729   11543 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret test-secret: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "test-secret": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.021] No resources found.
W0126 06:59:18.022] E0126 06:59:16.202611   11543 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret test-secret: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "test-secret": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.022] No resources found.
W0126 06:59:18.022] E0126 06:59:16.721263   11543 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret test-secret: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "test-secret": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.022] E0126 06:59:16.725644   11543 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret test-secret: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "test-secret": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.022] E0126 06:59:17.078269   11543 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret secret-string-data: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "secret-string-data": the object has been modified; please apply your changes to the latest version and try again
W0126 06:59:18.023] I0126 06:59:17.832206    9173 trace.go:61] Trace "Get /api/v1/namespaces/test-secrets/secrets/secret-string-data" (started 2017-01-26 06:59:17.330701321 -0800 PST):
W0126 06:59:18.023] [501.438656ms] [501.438656ms] END
I0126 06:59:18.148] 
I0126 06:59:18.151] test-cmd-util.sh:1595: FAIL!
I0126 06:59:18.151] Get secrets --namespace=test-secrets {{range.items}}{{.metadata.name}}:{{end}}
I0126 06:59:18.151]   Expected: 
I0126 06:59:18.151]   Got:      secret-string-data:
I0126 06:59:18.151] (B
I0126 06:59:18.151] 1595 /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh
I0126 06:59:18.151] (B
I0126 06:59:18.169] +++ [0126 06:59:18] Clean up complete
I0126 06:59:18.171] Makefile:258: recipe for target 'test-cmd' failed
```
from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/2608 and the queue is blocked.

@nikhiljindal aftermath I think.

**Comment by jessfraz** [comment] 2017-01-26 17:43
I can look into this a bit today

**Comment by deads2k** [comment] 2017-01-26 18:08
blocking the queue again.

**Comment by nikhiljindal** [comment] 2017-01-26 18:32
Thanks @jessfraz 

Looking at the logs, I see the failure is with federation-apiserver and not kube-apiserver.

**Comment by nikhiljindal** [comment] 2017-01-26 19:41
I dont see anything obviously wrong with the test.
It is testing that `get secrets` should not the secret after deleting it.

I am trying to reproduce it locally but it has passed continuously for past 30 runs (I am still running it in a loop).

I couldnt find it on the testgrid to figure out the failure rate. I was expecting it to be in https://k8s-testgrid.appspot.com/google-unit or https://k8s-testgrid.appspot.com/sq-blocking.

**Comment by jessfraz** [comment] 2017-01-26 19:44
hmm maybe the problem is in the CI infrastructure? I am also running a loop lol

**Comment by nikhiljindal** [comment] 2017-01-26 19:56
That is why I wanted to see how many times has it failed in our CI infra.
cc @ixdy @fejta to help find it

**Comment by ixdy** [comment] 2017-01-26 20:06
test-cmd doesn't produce machine-parsable junit, so I don't know how feasible this is. @k8s-sig-testing-misc

**Comment by ixdy** [comment] 2017-01-26 20:07
`make test-cmd` is run in the ci-kubernetes-test-go job, but the lack of junit means it doesn't show up in testgrid.

**Comment by deads2k** [comment] 2017-01-26 22:57
Blocking the queue again.  This is probably due to not running the tests before, but the pain is significant.  Unfortunately, we probably can't sort out what to revert to fix it, but is there a way to only skip it for federation and you keep a p0 until you find it?

**Comment by nikhiljindal** [comment] 2017-01-26 23:46
Sure @deads2k 
Sent https://github.com/kubernetes/kubernetes/pull/40567

**Comment by jessfraz** [comment] 2017-01-27 18:59
I'm going to reopen this since we need to get to the heart of the problem

**Comment by nikhiljindal** [comment] 2017-01-30 23:01
https://github.com/kubernetes/kubernetes/issues/40568 discusses the problem and the fix.
Closing this in favor of that.

**Closed by nikhiljindal** 2017-01-30 23:01 UTC
Labels: sig/federation
