### ISSUE TITLE
Etcdctl get a lot of garbage info after upgrade aip-server to use etcdv3 api

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/kubernetes#64074] opened 2018-05-20 14:16 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:

I'm upgrading etcd to v3.0.17 for k8s to use etcdv3 api.

After etcd upgraded and apiserver started without 'storage-backend=etcd2' and 'storage-media-type=application/json' defined, I noticed that 'etcdctl get' can't display some info properly, like this:

```
/_egi_+_y/c-+fig+a-_/++be-_y_+e+/fi+ebea+-_-a_+-c-+f
{"+i+d":"C-+figMa-","a-iVe__i-+":"+1","+e+ada+a":{"+a+e":"fi+ebea+-_-a_+-    c-+f","+a+e_-ace":"++be-_y_+e+","+id":"9a09cef0-348c-11e7-ba37- 1418775d636e","c_ea+i-+Ti+e_+a+-":"2017-05-09T07:53:34Z"},"da+a":{"fi+ebea+.y++":"fi+ebea+:\+  -_-_-ec+-__:\+  -\+    i+-++_+y-e: +-g\+    d-c++e++_+y-e: _-a_+\+    fie+d_:\+      +a+e_-ace: ++be-_y_+e+\+    fie+d__++de___--+: +_+e\+    -a+h_:\+      - /+-g/*/*/_+de__\+  -\+    i+-++_+y-e: +-g\+    d-c++e++_+y-e: _-a_+\+    fie+d_:\+      +a+e_-ace: ++be-_y_+e+\+    fie+d__++de___--+: +_+e\+    -a+h_:\+      - /+-g/*/*/_+d-++\+\+-++-++:\+  +-g_+a_h:\+    h-_+_: [\"192.168.197.200:5044\",\"192.168.197.199:5044\"]\+    +-_+e_: 4\+    c-+-_e__i-+_+e+e+: 3\+    +-adba+a+ce: +_+e\+    i+de|: ++be-_y_+e+\+"}}
```

Also, I created a new pod, it was stored in the etcd like this:

```
# ETCDCTL_API=3 /opt/bin/etcdctl --endpoints http://10.3.7.27:2379 get /registry/pods/default/busybox-116p6
/registry/pods/default/busybox-116p6
k8s

v1Pod¯

ã
busybox-116pbusybox-default"-/api/v1/namespaces/default/pods/busybox-116p6*$1cc8a15c-5996-11e8-ac41-1418775d2f8528B
                                                                                                              ý¯ô×‹Ä‰îZ
a--b+_yb-|Z&
c-++_-++e_-_e+i_i-+-ha_h
1615036418Z
--d-+e+-+a+e-ge+e_a+i-+1bû
++be_+e+e_.i-/c_ea+ed-byÞ{"+i+d":"Se_ia+izedRefe_e+ce","a-iVe__i-+":"+1","_efe_e+ce":{"+i+d":"Dae+-+Se+","+a+e_-ace":"defa+++","+a+e":"b+_yb-|","+id":"fa90b377-44a0-11e8-83ca-1418775d636e","a-iVe__i-+":"e|+e+_i-+_","_e_-+_ceVe__i-+":"100605842"}}
b.
*_ched++e_.a+-ha.++be_+e+e_.i-/c_i+ica+---d+R
    Dae+-+Se+b+_yb-|"$fa90b377-44a0-11e8-83ca-1418775d636e*e|+e+_i-+_/+1be+a108zý
1
defa+++-+-+e+-+8g9+2
defa+++-+-+e+-+8g9+¤è
b+_yb-|-_egi_+_y.-_-d.+ca_i+c.c-+/+--+_/b+_yb-|:g+ibc/bi+/_h-c+hi+e +_+e; d- _+ee- 3600; d-+e*BJH
defa+++-+-+e+-+8g9+-/+a_/_++/_ec_e+_/++be_+e+e_.i-/_e_+iceacc-+++"+/de+/+e_+i+a+i-+-+-g_
                                                                                        IfN-+P_e_e++€ˆ¢Fi+eA++ay_ 2
                                                                                                                C++_+e_Fi__+Bdefa+++Jdefa+++Raz06.++_.+ab.+ca_i+c.c-+X`h_‚Ššdefa+++-_ched++e_²8
!+-de.a+-ha.++be_+e+e_.i-/+-+ReadyE|i_+_"       N-E|ec++e²;
$+-de.a+-ha.++be_+e+e_.i-/++_eachab+eE|i_+_"    N-E|ec++eÆ
R+++i+g#

I+i+ia+izedT_+ý¯ô×*2
ReadyT_+þ¯ô×*2$

P-dSched++edT_+þ¯ô×*2"* 10.3.7.342172.29.224.22ý¯ô×B›
b+_yb-|


þ¯ô× (2-_egi_+_y.-_-d.+ca_i+c.c-+/+--+_/b+_yb-|:g+ibc:d-c+e_--+++ab+e://_egi_+_y.-_-d.+ca_i+c.c-+/+--+_/b+_yb-|@_ha256:9f5597958a437eacae2634ff71b9f28f94720a3bf43378c1db282693c4fed9e5BId-c+e_://4c54e2b9224f0b2545311f272b08af110a557941efa7d77f9207f8ec617be37dJ
Be_+Eff-_+"
```

What's wrong with here? The data write through v3 api by apiserver is not readable?

My environment: Coreos 1298.5.0, kubernetes v1.8.12, etcd v3.0.17

**What you expected to happen**:
ETCD data is readable

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy kubernetes cluster with version v1.8.12, etcd3.0.17
2. stop apiserver, etcd
2. migrate etcd data from v2 to v3 with 'etcdctl migrate' command.
3. start etcd, apiserver
4. get data from etcd with 'etcdctl get / --prefix' command.

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v1.8.12
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release): coreos 1298.5.0
- Kernel (e.g. `uname -a`): 4.9.9-coreos-r1

**Comment by ncdc** [comment] 2018-05-20 19:03
This appears to be a duplicate of #44670

**Comment by liggitt** [comment] 2018-05-20 23:29
kubernetes writes binary protobuf content into etcd v3, which is not easily human readable like json

that appears to be your terminal's best effort to display string values interspersed with binary blobs

**Closed** 2018-05-20 23:29 UTC
Labels: needs-sig
