### ISSUE TITLE
HTTP2 imposes limits on number of connections from single client causing some tests to fail

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34081] opened 2016-10-05 08:15 UTC
It results with test failure with error `http2: no cached connection was available`, e.g. in https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/2278/build-log.txt

We saw this in our scalability tests (#33557) and fixed it there (#33733) with a hope, that only scalability tests have this problem. It turns out that not only, so we probably need some more general solution.

One idea would be to increase a number of cached connections (@timothysc @thockin), another to make a e2e framework to act as a proxy for all API-server calls and create additional clients as needed (@kubernetes/test-infra-maintainers @dchen1107). Finally we might just apply something similar to #33733 to each test that we see fail because of this (@kubernetes/sig-testing)

cc @wojtek-t

**Comment by timothysc** [comment] 2016-10-05 19:27
Is there a list of failing tests?  Also, from #33557 it looks like the issue is being fixed in golang 1.8 .

**Comment by wojtek-t** [comment] 2016-10-05 19:49
I think so far it was only:
"Namespaces [Serial] [It] should delete fast enough (90 percent of 100 namespaces in 150 seconds)"

**Comment by gmarek** [comment] 2016-10-05 20:44
That's the one we notices. I don't know if anyone actually gone through all the failures.

**Comment by timothysc** [comment] 2016-10-05 20:50
Ohh snap, we need to redux namespace deletes in lieu of etcd3.

**Comment by bprashanth** [comment] 2016-10-05 21:06
Can't we just extend the fix (https://github.com/kubernetes/kubernetes/pull/33733) more generally so tests use a random client from the created list instead of the same one everytime? 

IIUC this is not a limit imposed by the protocol, because MAX_STREAMS limits the number of in flight streams per endpoint. It sounds like the golang fix is just going to open a new connection when this limit is hit, should obviate the need for an elaborate workaround.

**Comment by gmarek** [comment] 2016-10-05 21:30
The problem is that tests currently get a client object from the framework and once it has it, it just uses it for communication with master. To fix this we can make from the framework a client proxy, so we can actually randomize transports we use in tests, make multiple transports per REST clients, or just wait for golang fix...

**Comment by dchen1107** [comment] 2017-03-13 20:21
The original issue should be fixed by #33733. Close it.

**Closed by dchen1107** 2017-03-13 20:21 UTC
Labels: area/test-infra, kind/flake, priority/backlog
