### ISSUE TITLE
unit flake: TestWriteEventError

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19202] opened 2015-12-30 17:14 UTC
event_test.go:460: case retry1: wanted 12, got 0 attempts

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5326/

**Comment by gmarek** [comment] 2016-01-05 21:16
dupe of #19268

**Closed by gmarek** 2016-01-05 21:16 UTC
Labels: area/test, kind/flake, priority/P1, team/CSI
