### ISSUE TITLE
Kube-proxy shouldn't delete the iptables immediately while terminating the pods.

### ISSUE THREAD

**Issue by fanliquan** [kubernetes/kubernetes#106144] opened 2021-11-04 08:49 UTC
### What would you like to be added?

Kube-proxy should keep the iptables before the preStop job done. 

### Why is this needed?

Since some of the preStop job need to notify the API server to do something, such as modifying the configMap, deleting the endpoint subnet from service. 
But now kubernetes did the preStop job and deleting the iptables at same time, if the iptables was removed faster. The preStop job will failed, since it lost the connection.

**Comment by aojea** [comment] 2021-11-04 08:54
You have to be more descriptive and explain in more detail what iptables are you referring, which pods has the prestop job (I assume it belongs to a service, right?) ... a "how to reproduce" will be great.
The iptables for a pod that belongs to a service is removed as soon as the pod is not ready, that is when it is removed from the ready endpoints ...

**Comment by fanliquan** [comment] 2021-11-04 09:15
Hi,
For example, we have a pod named pd-0, the ip address is 192.168.182.193.
# kubectl get pod -o wide
pd-0         1/1     Running   0          26h   192.168.182.193   node-10-63-142-89   <none>           <none>           

The preStop of its container is as below:
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - /var/lib/postgresql/scripts/preStop.sh


Then I login to the worker node, the virtual interface is as below:
~> sudo ip route show | grep 192.168.182.193
192.168.182.193 dev cali86c421f734b scope link

The according iptables is as below:
:~> sudo iptables -S | grep cali86c421f734b
-N cali-fw-cali86c421f734b
-N cali-tw-cali86c421f734b
-A cali-from-wl-dispatch-8 -i cali86c421f734b -m comment --comment "cali:Qxo93rJVQBzPJqPR" -g cali-fw-cali86c421f734b
-A cali-fw-cali86c421f734b -m comment --comment "cali:W8jgcvOvFmTC-Dwl" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A cali-fw-cali86c421f734b -m comment --comment "cali:9mht3qQCItHB7E4U" -j MARK --set-xmark 0x0/0x10000
-A cali-fw-cali86c421f734b -p udp -m comment --comment "cali:M7HdEQusVLmNnkOy" -m comment --comment "Drop VXLAN encapped packets originating in workloads" -m multiport --dports 4789 -j DROP
-A cali-fw-cali86c421f734b -p ipv4 -m comment --comment "cali:XrjBPNXYu96WHS8a" -m comment --comment "Drop IPinIP encapped packets originating in workloads" -j DROP
-A cali-fw-cali86c421f734b -m comment --comment "cali:686n59G5m2yRESrr" -j cali-pro-kns.efanliq
-A cali-fw-cali86c421f734b -m comment --comment "cali:vs7fj7WHA5q-ez5k" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-cali86c421f734b -m comment --comment "cali:-zXUMtzkSQDGRMr_" -j cali-pro-_Y4wJPXIA6XW_75M8PK
-A cali-fw-cali86c421f734b -m comment --comment "cali:2fFad_Ec3FuhgaO8" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-fw-cali86c421f734b -m comment --comment "cali:bcGRRwE5VSCdyJXl" -m comment --comment "Drop if no profiles matched" -j DROP
-A cali-to-wl-dispatch-8 -o cali86c421f734b -m comment --comment "cali:dtpDM0mWigr1jf86" -g cali-tw-cali86c421f734b
-A cali-tw-cali86c421f734b -m comment --comment "cali:kMmHujujGbbmVBfJ" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A cali-tw-cali86c421f734b -m comment --comment "cali:rX7KZyLLaQdOs9Sd" -j MARK --set-xmark 0x0/0x10000
-A cali-tw-cali86c421f734b -m comment --comment "cali:hTFEsa6_OYTHWMTC" -j cali-pri-kns.efanliq
-A cali-tw-cali86c421f734b -m comment --comment "cali:jmHeDWaYqYTcwMpo" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-tw-cali86c421f734b -m comment --comment "cali:0y9P-halOsFZcXGz" -j cali-pri-_Y4wJPXIA6XW_75M8PK
-A cali-tw-cali86c421f734b -m comment --comment "cali:gRVGdqb_qPtfZ6oX" -m comment --comment "Return if profile accepted" -m mark --mark 0x10000/0x10000 -j RETURN
-A cali-tw-cali86c421f734b -m comment --comment "cali:HwSHLgfmOd2CnF3R" -m comment --comment "Drop if no profiles matched" -j DROP


While I perform the kubectl delete pod/pd-0,  The action of deleting iptables and preStop job will be performed at same time.
Sometime the perStop job will failed since the iptables was removed before it. Thanks!

**Comment by aojea** [comment] 2021-11-04 09:29
those iptables are not created by  kube-proxy, I assume those are created by Calico so you should open the issue on that project

**Comment by fanliquan** [comment] 2021-11-04 09:45
OK, Thanks!

**Comment by aojea** [comment] 2021-11-04 09:52
I'm going to close it since is not related to k/k
thanks 
/close

**Closed** 2021-11-04 09:53 UTC
Labels: kind/feature, needs-sig, needs-triage
