### ISSUE TITLE
Utility to generate a secrets volume from an arbitrary directory structure

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#15514] opened 2015-10-13 00:29 UTC
As I'm writing more k8s config, I'm finding myself using secrets volumes for storing secrets and configuration. I've written shell scripts for generating configuration to pipe to kubectl, but what would really be useful is a utility to create/update/maintain secrets volumes from a directory structure.

This would allow for a fairly generic kubernetes config that could be combined with custom configuration in a secrets volume. I would expect it to work something like:

```
% ls haproxy
haproxy.cfg
% kubesec create haproxy-config-volume haproxy
secrets/haproxy-config-volume
% echo '# moar config' >> haproxy/haproxy.cfg
% kubesec diff haproxy-config-volume haproxy
# show a diff here...
% kubesec update haproxy-config-volume haproxy
secrets/haproxy-config-volume
```

Alternatively, the utility could just print config that could be piped to kubectl, or kubectl could support this functionality directly.

I searched around a little and didn't find anything like this. I'd be happy to implement it, but I don't know how something like this fits into the plans for secrets.

**Comment by liggitt** [comment] 2015-10-13 00:54
dupe of https://github.com/kubernetes/kubernetes/issues/4822

**Closed** 2015-10-13 00:55 UTC
