### ISSUE TITLE
kubectl logs -f stop after log rotation

### ISSUE THREAD

**Issue by arezvani** [kubernetes/kubernetes#126564] opened 2024-08-06 20:09 UTC
### What happened?

I have a problem that kubectl logs -f stop after log file rotation. 
https://github.com/kubernetes/kubernetes/pull/115702
In this link said this problem solved but when I update my kuber version to 1.29.0, I have this problem yet.

### What did you expect to happen?

`kubectl logs -f` continue showing logs after log rotation.

### How can we reproduce it (as minimally and precisely as possible)?

I have create this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 0.1; done'
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: count
```

Then I use this command to check logs:
```
k logs -f counter
```

After rotation `k logs -f counter` stop showing logs. When I check time of last log find this is as same as time of rotation of log file ( after 10M)

### Kubernetes version

1.29.0

### Cloud provider

<details>
on-premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

**Comment by xyz-li** [comment] 2024-08-07 03:41
@arezvani 
I have set `ContainerLogMaxSize` to 3Mi. 
I didn't reproduce this.

```
NAME   STATUS   ROLES           AGE   VERSION
node1     Ready    control-plane   60m   v1.29.0
```

**Comment by saschagrunert** [comment] 2024-08-07 08:37
I can't reproduce this either using 60c4c2b2521 and CRI-O https://github.com/cri-o/cri-o/commit/5fcc64c8d159e89c040928e4b0032f359a1c864e

**Comment by Aaina26** [comment] 2024-08-13 13:57
> I had set containerLogMaxSize to 1Mi and I am using CRI-O runtime. I could not reproduce it either. I used the current version of kubernetes. I see that the container runtime mentioned is containerd. Will try with that.

This issue did not reproduce with containerd as well.

**Comment by saschagrunert** [comment] 2024-08-14 07:06
Closing for now, please reopen if we can reproduce it.

**Closed by saschagrunert** 2024-08-14 07:06 UTC
Labels: kind/bug, sig/node, needs-triage
