### ISSUE TITLE
fluentd-elasticsearch logs mapping issue (kubernetes 1.1.1 + aws)

### ISSUE THREAD

**Issue by sebv** [kubernetes/kubernetes#17681] opened 2015-11-23 21:44 UTC
See log here: https://gist.github.com/sebv/914c9b73b48e4542bfeb , the symlink to /mnt/ephemeral/docker/containers is not valid within container.

This is a new issue on 1.1 (it's working on 1.0.7)

On the node:

```
ubuntu@ip-172-20-0-155:~$ sudo ls -l /var/log/containers
total 80
lrwxrwxrwx 1 root root 171 Nov 23 21:24 elasticsearch-logging-v1-4yjm2_kube-system_elasticsearch-logging-b475872a10ac01e5fd94934a0860996db9611bfeeff74970ef14e4537beda041.log -> /mnt/ephemeral/docker/containers/b475872a10ac01e5fd94934a0860996db9611bfeeff74970ef14e4537beda041/b475872a10ac01e5fd94934a0860996db9611bfeeff74970ef14e4537beda041-json.log
```

My version:

```
  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.8-beta.3+27719743e6b69e", GitCommit:"27719743e6b69e9526d5133b6d6b71cc6f1024c2", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.1", GitCommit:"92635e23dfafb2ddc828c8ac6c03c7a7205a84d8", GitTreeState:"clean"}
```

**Comment by sebv** [comment] 2015-11-24 09:00
Quick fix although probably bad idea to have an ephemeral mapping within a container:
```
diff --git a/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml b/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml
index c2105b2..1b364f8 100644
--- a/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml
+++ b/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml
@@ -15,15 +15,15 @@ spec:
     volumeMounts:
     - name: varlog
       mountPath: /var/log
-    - name: varlibdockercontainers
-      mountPath: /var/lib/docker/containers
+    - name: containers
+      mountPath: /mnt/ephemeral/docker/containers
       readOnly: true
   terminationGracePeriodSeconds: 30
   volumes:
   - name: varlog
     hostPath:
       path: /var/log
-  - name: varlibdockercontainers
+  - name: containers
     hostPath:
-      path: /var/lib/docker/containers
+      path: /mnt/ephemeral/docker/containers
```

**Comment by MartinSoto** [comment] 2016-05-24 22:19
This seems to be a duplicate of #13313. Unfortunately, no fix or workaround is suggested there either.

**Closed** 2018-02-13 17:54 UTC
Labels: lifecycle/rotten, sig/node
