### ISSUE TITLE
[Flaky Test] [sig-network] DNS should resolve DNS of partial qualified names for the cluster [LinuxOnly]

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98709] opened 2021-02-03 02:18 UTC
**Which jobs are flaking**: `ci-kubernetes-e2e-ubuntu-gce-containerd`

**Which test(s) are flaking**: `DNS should resolve DNS of partial qualified names for the cluster [LinuxOnly]`

**Testgrid link**:  https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd&include-filter-by-regex=DNS%20should%20resolve%20DNS%20of%20partial%20qualified%20names%20for%20the%20cluster%20

**Reason for failure**:

```
I0131 11:22:48.228] [sig-network] DNS
I0131 11:22:48.228] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:23
I0131 11:22:48.228]   should resolve DNS of partial qualified names for the cluster [LinuxOnly] [It]
I0131 11:22:48.228]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns.go:89
I0131 11:22:48.228] 
I0131 11:22:48.228]   Jan 31 11:22:45.314: Unexpected error:
      
I0131 11:22:48.229]       <*errors.errorString | 0xc0001881e0>: {
I0131 11:22:48.229]           s: "timed out waiting for the condition",
I0131 11:22:48.229]       }
I0131 11:22:48.229]       timed out waiting for the condition
I0131 11:22:48.229]   occurred
I0131 11:22:48.229] 
I0131 11:22:48.230]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:511
I0131 11:22:48.230] ------------------------------
I0131 11:22:48.230] {"msg":"FAILED [sig-network] DNS should resolve DNS of partial qualified names for the cluster [LinuxOnly]","total":-1,"completed":16,"skipped":75,"failed":1,"failures":["[sig-network] DNS should resolve DNS of partial qualified names for the cluster [LinuxOnly]"]}
skipped 14 lines unfold_more
I0131 11:22:48.233] 
I0131 11:22:48.233] [Fail] [sig-network] DNS [It] should resolve DNS of partial qualified names for the cluster [LinuxOnly] 
```

**Anything else we need to know**:

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1355830780370096128
Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=DNS%20should%20resolve%20DNS%20of%20partial%20qualified%20names%20for%20the%20cluster

/sig network

**Comment by pacoxu** [comment] 2021-02-03 02:42
```
Jan 31 11:22:45.408: INFO: At 2021-01-31 11:11:17 +0000 UTC - event for dns-test-ec2f130b-7b65-4e93-aba4-635026d0c0b2: {kubelet bootstrap-e2e-minion-group-nm9t} Pulling: Pulling image "k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4"
Jan 31 11:22:45.408: INFO: At 2021-01-31 11:11:27 +0000 UTC - event for dns-test-ec2f130b-7b65-4e93-aba4-635026d0c0b2: {kubelet bootstrap-e2e-minion-group-nm9t} Failed: Failed to pull image "k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4": failed to extract layer sha256:b4a0ec3e8cccd0439f54d29408d3d2f56227dcdd6aa441eba4c8ad07aa3a03c2: failed to get reader from content store: blob sha256:afee0e7e18571f0645de2bc381d1ccfc5656806dfbb39155f4369370839319a2 expected at /var/lib/containerd/io.containerd.content.v1.content/blobs/sha256/afee0e7e18571f0645de2bc381d1ccfc5656806dfbb39155f4369370839319a2: not found
Jan 31 11:22:45.408: INFO: At 2021-01-31 11:11:27 +0000 UTC - event for dns-test-ec2f130b-7b65-4e93-aba4-635026d0c0b2: {kubelet bootstrap-e2e-minion-group-nm9t} Failed: Error: ErrImagePull
Jan 31 11:22:45.408: INFO: At 2021-01-31 11:11:27 +0000 UTC - event for dns-test-ec2f130b-7b65-4e93-aba4-635026d0c0b2: {kubelet bootstrap-e2e-minion-group-nm9t} BackOff: Back-off pulling image "k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4"
Jan 31 11:22:45.408: INFO: At 2021-01-31 11:11:27 +0000 UTC - event for dns-test-ec2f130b-7b65-4e93-aba4-635026d0c0b2: {kubelet bootstrap-e2e-minion-group-nm9t} Failed: Error: ImagePullBackOff
```

k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4 is promoted in https://github.com/kubernetes/k8s.io/pull/1558 19 days ago.

```
[root@daocloud ~]# docker images  | grep jessie
k8s.gcr.io/e2e-test-images/jessie-dnsutils                                          1.4                                    5d26a8ba18fe   13 days ago     253MB
k8s.gcr.io/e2e-test-images/jessie-dnsutils                                          1.3                                    4db8afc88fa8   4 months ago    253MB
k8s.gcr.io/e2e-test-images/jessie-dnsutils                                          1.2                                    67b4d96f0abd   12 months ago   253MB
```

Not sure why the image pulling failed.

**Comment by pacoxu** [comment] 2021-02-03 05:30
Cannot reproduce it with 

- crictl  -D  pull k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4 
- docker pull k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4
- ctr image pull --platform linux/arm64 k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.4

```
[root@daocloud ~]#  curl -k https://k8s.gcr.io/v2/e2e-test-images/jessie-dnsutils/manifests/1.4 | grep arch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3477  100  3477    0     0   7228      0 --:--:-- --:--:-- --:--:--  7228
            "architecture": "amd64",
            "architecture": "arm",
            "architecture": "arm64",
            "architecture": "ppc64le",
            "architecture": "s390x",
            "architecture": "amd64",
```

Failed on ubuntu/amd64. Can someone try to reproduce it? Or this is temperory failure ?
```
    nodeInfo:
      architecture: amd64
      bootID: d5f4ca3c-6668-4c1d-99a5-d330a69ab29b
      containerRuntimeVersion: containerd://1.4.3
      kernelVersion: 5.4.0-1009-gcp
      kubeProxyVersion: v1.21.0-alpha.2.146+c241a237f9a635
      kubeletVersion: v1.21.0-alpha.2.146+c241a237f9a635
      machineID: 172402a8e1ec06221c9ecb34b2831731
      operatingSystem: linux
      osImage: Ubuntu 20.04 LTS
      systemUUID: 172402a8-e1ec-0622-1c9e-cb34b2831731
```

**Comment by aojea** [comment] 2021-02-03 21:28
I see only 1 failures in testgrid and  most failures are in kops jobs per this link
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=DNS%20should%20resolve%20DNS%20of%20partial%20qualified%20names%20for%20the%20cluster&xjob=kops

Is this a real flake or was a hiccup?

**Comment by aojea** [comment] 2021-02-04 22:00
@PriyankaH21 I'm going to close it, it seems that only happens in kops job.
If you find more than 2 failures in a week don't hesitate to reopen, but only 1 failure in the last 15 days is not enough to know if is a real flake or an environmental problem
/close

**Closed** 2021-02-04 22:00 UTC
Labels: kind/flake, needs-triage, sig/network
