### ISSUE TITLE
Add support for variables in configuration files

### ISSUE THREAD

**Issue by atrauzzi** [kubernetes/kubernetes#15703] opened 2015-10-15 12:36 UTC
I haven't seen anywhere in the kubernetes documentation that shows how to use variables (either specified command line, or by importing all declared environment variables) in my yaml configuration files.  As I'm getting started with google container engine, it's definitely something I'm already wishing for.
With things as they currently are, I either have to generate the files myself, or maintain multiple copies of similar configuration files (usually by environment).

Apologies in advance if this is a duplicate feature request.  I couldn't get a clear idea as to whether this is already underway.

**Comment by bgrant0607** [comment] 2015-10-15 16:08
Dupe of #11492.

Yes, agree that this is needed. We have a couple ideas in the works. 

It's also not too hard to run a preprocessing pass before passing the configs to kubectl, though we're considering adding support for that, as well. #13241

**Closed by bgrant0607** 2015-10-15 16:08 UTC
