### ISSUE TITLE
GKE e2e flake: Pod Disks should schedule a pod

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#23152] opened 2016-03-17 21:49 UTC
Flaked twice on kubernetes-e2e-gke-slow-release-1.2
[kubernetes-e2e-gke-slow-release-1.2/97](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/97)
[kubernetes-e2e-gke-slow-release-1.2/80](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/80)

```
Pod Disks should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession [Slow]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:216 Expected error: <*exec.ExitError | 0xc2082bc5f0>: { ProcessState: { pid: 15037, status: 256, rusage: { Utime: {Sec: 0, Usec: 424000}, Stime: {Sec: 0, Usec: 28000}, Maxrss: 23428, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 1473, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 0, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 2742, Nivcsw: 5, }, }, } exit status 1 not to have occurred


Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession [Slow]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:270 Expected error: <*exec.ExitError | 0xc2083d50f0>: { ProcessState: { pid: 18125, status: 256, rusage: { Utime: {Sec: 0, Usec: 436000}, Stime: {Sec: 0, Usec: 28000}, Maxrss: 23360, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 1440, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 0, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 2856, Nivcsw: 3, }, }, } exit status 1 not to have occurred


Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host [Slow]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:121 Expected error: <*exec.ExitError | 0xc2083f8420>: { ProcessState: { pid: 11297, status: 256, rusage: { Utime: {Sec: 0, Usec: 392000}, Stime: {Sec: 0, Usec: 32000}, Maxrss: 23300, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 1488, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 0, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 2524, Nivcsw: 8, }, }, } exit status 1 not to have occurred
```

**Comment by ihmccreery** [comment] 2016-03-17 22:01
This is a duplicate of #23149.

**Comment by ihmccreery** [comment] 2016-03-17 22:02
```
Mar 17 12:54:19.508: INFO: error running kubectl exec to write file: exit status 1
stdout=
stderr=Error from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-c5d9e45b81848219014b"?
)
```

**Closed by ihmccreery** 2016-03-17 22:02 UTC
Labels: kind/flake, priority/P1, team/cluster, team/gke
