### ISSUE TITLE
Auto-closing issues is harmful and causes friction

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#103151] opened 2021-06-24 10:31 UTC
Previously open issue : https://github.com/kubernetes/community/issues/5473
Twitter Discussion : https://twitter.com/BenTheElder/status/1407774856033181696

There's pros and cons to having a bot do this, let me try to enumerate current situation here:
- maintainers don't have to play bad cop
- keep set of open issues at a maintainable level
- bot commands are available to org members to `/reopen` reduces friction
- lifecycle labels help folks specify which issues not to touch
- we currently do not have dedicated team(s) that do issue triage well (except for some SIG like api-machinery that do this really well with twice a week triage session)
- initial issue labeling is still a problem, routing issues to the correct sig
- we have a new triage label which is not widely used yet across sigs

However there are numerous problems with the current situation:
- impression that project does not care about bugs
- folks open new issues for things that may be already present but closed
- too much traffic/noise from the bot activity
- issues where some follow up was requested/needed gets closed 

Options to do better?
- triage party 
- more hands on deck, train incoming folks to do issue triage and manage that as a subproject of some SIG
- stop the bot cold and let the SIGs adjust

What did i miss @BenTheElder ?

/sig contributor-experience

PS: It will be ironic if this issue gets auto-closed!

**Comment by sftim** [comment] 2021-06-24 11:34
It seems like a good idea to revisit the workflows here. What follows is very much my opinion and not representing any SIG. It also covers more than just autoclose.

Auto close _does_ avoid issues piling up.

- I'm OK with the idea of never closing issues that are triaged as accepted
- I'm also OK with the idea of auto closing issues that have been marked as needs more information or as support, and haven't had a response since they were so labelled.
- I'd be interested in splitting the “backlog” priority level into “stuff we'd clearly like to do as a SIG, and would if there were resources” vs. “it's a valid suggestion but it'll only happen if someone takes it forward”. For an example of the latter see issue 25061 in k/website: **Allow switching website between “light mode” and “dark mode”**.
- That split would help us let things fall off the second backlog, but perhaps let them stay on the first.
- Priorities above backlog should not autoclose, but I do want to see them rot and then be labelled _something_ if we don't get to them. Maybe become “overdue” or “unaddressed”?

For k/website, issues that haven't been triaged in _n_ days could go straight to _unaddressed_, skipping stale and rotten.

**Comment by sftim** [comment] 2021-06-24 11:42
Does https://github.com/features/issues provide any new way to track issues and help avoid closing ones that are worth keeping?

**Comment by BenTheElder** [comment] 2021-06-24 16:11
I want to point out that while the original somewhat hyperbolic tweet took off far beyond expectation there is an important follow-up: https://twitter.com/bentheelder/status/1407906836175491076

IMHO the biggest issue we have is staffing problems keeping after triage and so on.

> more hands on deck, train incoming folks to do issue triage and manage that as a subproject of some SIG

Perhaps a new role in SIGs recognizing the folks that do issue triage? I think we need some way to recognize and encourage doing this, in addition to some workflow guidance or tooling (such as triage-party instances).

Bot noise impacts me a lot, personally. To keep something like KIND running well @ Kubernetes HEAD + manage SIG testing etc. I am subscribed to a lot of issues and a *huge* amount of comments are just the lifecycle robot and users fending it off.
Frozen issues are cheaper, they see little noise when nobody is working on them and IMHO if these issues are breaking triage workflows then the workflows need to be improved.

But as mentioned above I think the important part is that this harms the reputation of the project immensely because for many people their first interaction is filing a bug or PR that slips through the cracks and then gets harassed by the auto close bot. We have other people exasperated and futilely commenting every time the bot comments to undo it. There is a sub thread about folks who outright said they do not participate anymore after this experience. Once we burn those folks they don't come back.

I think closing issues we never got to hides just how many of those exist except from those in the know about querying the right labels.

> I'd be interested in splitting the “backlog” priority level into “stuff we'd clearly like to do as a SIG, and would if there were resources” vs. “it's a valid suggestion but it'll only happen if someone takes it forward”. For an example of the latter see issue 25061 in k/website: Allow switching website between “light mode” and “dark mode”.

I think this would be useful signaling regardless.

> I'm also OK with the idea of auto closing issues that have been marked as needs more information or as support, and haven't had a response since they were so labelled.

I would add that we should consider poking for information (the bot could do this) at some point in the lifecycle.

+1, there's a big difference between we can't move forward with the issue because the author is not responding and we need information and the issue not getting a response from us. Auto-closing this sort of issue seems unlikely to produce the same response and keeping them open seems unlikely to net much for anyone.

In general +1 to @sftims comment above.

It's worth noting that most of our repos are not kubernetes/kubernetes scale and even a moderately busy repo is probably already more doable to triage without this than our busiest repos, I think we have two different scales of problems but we bluntly apply one workflow org wide.

We are trying disabling it on the KIND repo, which seems to clearly fall into the latter scale.

**Comment by evankanderson** [comment] 2021-06-24 16:32
One thing we're going to start experimenting with in Knative is building an issue-triage report to make this sort of thing more manageable:

The initial focus will be simply on quantifying the bot impact:

How many issues touched in the last 100 days:
* Were marked by the stale-bot?
* And had a human undo the stale-bot?
* First item and never had an org member comment?

If there's interest, it might also be possible to collect org member stats on issue replies (maybe treating first and last specially). This could help highlight people who are doing a great job of triage and issue-closing.

**Comment by coderanger** [comment] 2021-06-24 19:21
Being mostly on the user side I do feel a lot of frustration with these. I think auto-closing specifically in the case of a ticket/PR being in a "waiting for OP to respond" state is okay but when the issue is accepted as real and there's nothing more to say, then auto-closing them is pretty grumble-inducing. Auto-cloing untriaged tickets/PRs feels like a gray area, can see both sides, and probably should be a special case and a sign that our triage process needs improvement.

**Comment by fejta** [comment] 2021-06-24 21:26
This reminds me of the different types of strategies used by dictionaries. Some are descriptive -- describing how people use words -- whereas others are prescriptive -- informing people how they should use words. 

https://www.merriam-webster.com/words-at-play/descriptive-vs-prescriptive-defining-lexicography

What strategy should we use for the backlog of issues that no one has engaged with in half a decade?
* prescriptive  -- this issue is still probably broken and someone still ought to fix it
* descriptive -- no one has or will work on this issue, close it so it doesn't distract from the things we are fixing.

Neither is correct per se. Although I would note that most dictionaries these days tend to be descriptive.

Ideally we can figure out how to redirect the energy spent getting angry at automated descriptive processes and towards fixing more issues more consistently.

> impression that project does not care about bugs

The impression that the project does not care about bugs is an accurate conclusion implied by the large number of auto-closed issues. At the very least, the project's ability to generate bugs is higher than the community's current ability to fix them.

Pulling the battery out of a smoke detector is unlikely to put out a fire.

> [auto-closing bugs] harms the reputation of the project immensely because for many people their first interaction is filing a bug or PR that slips through the cracks and then gets harassed by the auto close bot. We have other people exasperated and futilely commenting every time the bot comments to undo it. 

In the same way smoke detectors rarely cause fires, I would not assign the cause of the reputational harm from ignoring bugs to automated processes that flag things as ignored.

Rather I would note the lack of the right processes in place that allow the maintainers on this project respond to incoming issues faster than they are supplied and also identify issues that have fallen through the cracks.

**Comment by BenTheElder** [comment] 2021-06-24 21:40
> What strategy should we use for the backlog of issues that no one has engaged with in half a decade?

We close bugs _far_ quicker than half a decade. IMO the amount of time a bug spends open is actually immaterial. If the bug is real and not fixed it deserves to be tracked, it is wasteful to file N bugs for the same problem, and it prevents users from tracking resolution when we spread it out in this way.

We've yet to have any solid arguments as to why open bugs are harmful. At best there is some complaint about issue triage, but that is accomplishable with e.g. just labeling the issue and filtering by label. Closing is orthogonal.

> Ideally we can figure out how to redirect the energy spent getting angry at automated descriptive processes and towards fixing more issues more consistently.

Many people filing bugs are ill equipped to fix them. A user of the project may not be in the right position / experience to resolve a bug. Their frustration is still relevant to the success of the project. There is also a lot of energy wasted in `/remove-lifecycle` comments.

> The impression that the project does not care about bugs is an accurate conclusion implied by the large number of auto-closed issues. At the very least, the project's ability to generate bugs is higher than the community's current ability to fix them.

Not even leaving the bug tracked and dismissively closing it is a bit different than not getting to it.

> In the same way smoke detectors rarely cause fires, I would not assign the cause of the reputational harm from ignoring bugs to automated processes that flag things as ignored.

There is explicitly evidence that there is reputational harm from this. Off hand: https://twitter.com/jordansissel/status/1407857648083472388
"K8s auto closing bot is why I don’t interact with k8s projects anymore. 😭👍🏻"

Further, I'd say this is not comparable to a smoke detector. Tracking the amount of inactive bugs is a smoke detector.
Closing them actually obscures this, I'd have a different impression encountering a project with ~9k bugs open than < 2k. How many people are aware of searching github for the closed issues with special label?

Closing issues is more like having a robot dump the flaming objects in your backyard so the smoke detector stops going off.

> Rather I would note the lack of the right processes in place that allow the maintainers on this project respond to incoming issues faster than they are supplied and also identify issues that have fallen through the cracks.

This is almost certainly the most important thing to address. That doesn't mean that other aspects of the current approach aren't problematic though.

**Comment by fejta** [comment] 2021-06-24 22:33
> Tracking the amount of inactive bugs is a smoke detector.

How would you separate active from inactive bugs?

> Their frustration is still relevant to the success of the project. There is also a lot of energy wasted in /remove-lifecycle comments.

Both of these are good signals that a SIG has underinvested in their triage or development process and/or have other problems (bad design/impl causing problems, important unhandled use cases, etc).

**Comment by BenTheElder** [comment] 2021-06-24 22:38
> How would you separate active from inactive bugs?

Auto-Labeling + search queries used by triagers or triage tooling still seems potentially relevant, but less heavy handed.

> Both of these are good signals that a SIG has underinvested in their triage or development process and/or have other problems (bad design/impl causing problems, important unhandled use cases, etc).

Yes -- we definitely have signal that triage processes are under-staffed / optimized / not going well, and it is definitely not uniform across SIGs (some are doing quite well).

As for how we might improve that, https://github.com/kubernetes/sig-testing/issues/7 is one issue tracking exploring that.

**Comment by ehashman** [comment] 2021-06-25 00:59
So people don't have to wade through Twitter, let me summarize my 2c...

Volume:

- We have nearly 7000 issues in k/k closed with the rotten label; realistically that's over 1000/yr: https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aclosed+label%3Alifecycle%2Frotten
- On average for the past year, we have 35 new issues opened every day: https://k8s.devstats.cncf.io/d/39/issues-opened-closed-by-sig?orgId=1&var-period=d&var-repo_name=kubernetes%2Fkubernetes&var-repo=kuberneteskubernetes&var-sig_name=All&var-kind_name=All
- From experience with SIG Instrumentation, I estimate that we typically triage about 5 issues per 30m session. I think it's therefore reasonable to estimate that one person could easily fill an entire half of their workday just triaging incoming issues to k/k, 7 days a week.

Contributor and issue filer expectations:

- Allowing a backlog of issues that anyone can file to grow forever fails to set healthy boundaries and realistic expectations around support in a FOSS project. Closed, stale issues illustrates the staffing gap and at least shifts some of the emotional labor on closing stale issues (which no one enjoys doing!! particularly if the reply that comes back is rude!) to a bot.
- I think there's a difference between closing issues that have been confirmed at some point but we're not staffed to handle vs. various user support requests, perhaps where the reporter is unresponsive.
- I frequently struggle with confirmed, legitimate issues that the project doesn't have resources to address, because there are only so many things we can prioritize working on. Even if an outside contributor does the work to fix the problem, reviewer/approver time is very limited.
- Addressing the limited approver time gap is not easy. It is extremely challenging to develop the experience to apply for approver on some of the high volume areas of the codebase (API Machinery, Node, etc.) You need to work on the project full-time, and that requires funding/employment. Many areas of the project have a lottery factor of 1.

At the moment, I think it's clear that SIGs are not resourced to manage the current volume of incoming issues in k/k. I think it's also fair to argue that the stale bot has discouraged issue filing, so I suspect that if we staffed the project for current issue load, we could easily see it increase in a short time and would find ourselves understaffed again.

Could the project hire someone to do full-time issue triage and management? And, if we did this, would we have sufficient staffing in SIGs to manage the workload of legitimate bugs and feature requests after moving the bottleneck?

**Comment by spiffxp** [comment] 2021-07-23 17:32
FWIW:
- the way the comments are done right now is via a commenter tool that comments on anything matching a certain github query
- it's super boilerplate-heavy and not able to be concisely configured in a way that would allow certain repos to opt-opt, or configure different thresholds, or different lifecycles, etc.
- if someone wanted to invest the effort in writing a purpose-built lifecycle management tool, this would probably way easier to accomplish

I feel like with the possible exception of kubernetes/kubernetes, it would be super cool to use a default that is selectively overridable by specific subprojects or SIGs.

As to effectives, I don't know anyone who's bothered to gather data on:
- whether perma-unstaling issues has been effective in getting them addressed (aka is this an alternate way of people spamming +1 or :thumbsup: on the issue to vote? does anyone pay attention?)
- whether auto-closed issues resurface later as larger-impact / higher-priority issues (aka we could have saved ourselves pain if we had addressed it earlier)

What would be a friendlier way to express that there isn't sufficient contributor capacity to even look at a given issue / PR? 

How would folks propose increasing contributor capacity to ensure that all issues / PRs can be looked at?

**Comment by BenTheElder** [comment] 2021-07-23 17:47
> it's super boilerplate-heavy and not able to be concisely configured in a way that would allow certain repos to opt-opt, or configure different thresholds, or different lifecycles, etc.

Overall I would agree that this is true but opt-out entirely is not really problematic, we're piloting this on the KIND repo.

You can see the three line diff necessary here: 
https://github.com/kubernetes/test-infra/pull/22675/files

> if someone wanted to invest the effort in writing a purpose-built lifecycle management tool, this would probably way easier to accomplish

I don't think anyone needs to alter the tool to support this or alternate per-repo comments, the tool is flexible and uses github search parameters for choosing where to comment. GitHub search is well documented and plenty powerful enough to exclude and include specific projects.

> What would be a friendlier way to express that there isn't sufficient contributor capacity to even look at a given issue / PR?

At the very least the phrasing can be a bit less blunt / more helpful, see also https://github.com/knative/community/issues/665#issuecomment-873873770, https://github.com/kubernetes/test-infra/issues/22911

Marking issues as needing triage and a perhaps a comment explaining the limited bandwidth etc. seems more useful than people `/remove-lifecycle`ing for years.

> How would folks propose increasing contributor capacity to ensure that all issues / PRs can be looked at?

I don't think you have to address that issue to resolve that the current approach to closing them out is noisy and frustrating.

Resolving capacity is not something people can solve with their own time and efforts, we need more staffed contributors, which at most we can raise to our employers.

I think we can reduce the issue count differently however:

We should also probably consider entirely removing / auto-closing the feature type in favor of asking people to file KEPs. And also the support type. Realistically most of the time we are manually re-pointing these issues to the the enhancements rep and the forums respectively, which could be automated, leaving only bugs, flaking/failing tests to deal with.

**Comment by BenTheElder** [comment] 2021-07-23 17:52
It is perhaps worth noting that this is factoring into the decision to donate kube-rs into the project https://github.com/kube-rs/kube-rs/issues/584, there should probably be a discussion somewhere (else?) about formally allowing subprojects to opt out of this. 

Previously we refused at least one project's request (helm, as I recall), though we've since (unofficially?) permitted merging this for one project (KIND, see above).

**Comment by sftim** [comment] 2021-07-25 19:56
> We close bugs far quicker than half a decade

I know that in k/website / SIG Docs we struggle to make improvements even when they've been _marked_ as important for some time. https://github.com/kubernetes/website/issues/4322 springs to mind. Folks are chipping away at the pile of frozen issues that have ended up at the end of the far end of the list.

Automatic closure has “helped” by making those frozen issues stand out. However, there's definitely a risk that some good idea never made it past triage and disappeared into the pile of closed suggestions.

**Comment by baurmatt** [comment] 2021-07-27 07:17
I wanted to add a good example which IMHO shouldn't be auto-closed:

https://github.com/kubernetes/kubernetes/issues/7890 is the [the top 5 of all upvoted issues](https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) but it is/was scheduled by the bot to be autoclosed.

**Comment by bacongobbler** [comment] 2021-08-02 17:25
> Previously we refused at least one project's request (helm, as I recall),

Can confirm it was the Helm project (@spiffxp and I chatted about this at the first Helm Summit).

**Comment by aojea** [comment] 2021-11-02 15:00
:upside_down_face:

**Comment by MadhavJivrajani** [comment] 2021-11-02 15:09
/remove-lifecycle stale
/lifecycle frozen
😬

**Comment by ghostsquad** [comment] 2022-03-04 21:40
this is like a 2min read: This provides some really useful insight into the problem:
https://blog.benwinding.com/github-stale-bots/

The way I see it, issues should never be closed, and it doesn't really matter if you have 100 open issues or 10,000. 

As a maintainer, personally, I'd want to concentrate on
1. confirmed bugs first (which would could be annotated as labels)
2. unlabeled issues that come in, sort by 👍 reactions, as it shows someone else encountered the same issue, and is reporting that they too are seeing the same problem, or desire the same feature
3. unlabeled issues that come in, sort by recent changes (new comments), this shows relevant activity in that thread that could mean high impact
4. investigate the use of something like this in order to find duplicate issues, label, and close them as duplicates:
https://github.com/probot/duplicate-issues
5. utilize github actions to export information to a system that can store and query the data. E.g. `on: issue_comment`, etc.

**Comment by dims** [comment] 2022-05-01 15:23
@liggitt @BenTheElder i forget where we talked about this? (chairs/leads meeting?) do we have a follow up PR or issue from the discussion there? (i think we said the last step in actually closing the issue should not happen, and there was discussion about if the issue is triaged then the bot should ignore it?). my brain is hazy ...

**Comment by BenTheElder** [comment] 2022-05-01 17:44
There's this recent discussion that cross referenced https://github.com/kubernetes/test-infra/issues/25967 (there's more related to that issue on the mailing lists etc).

I think that conversation is only scoped to not closing ~ triage/accepted + priority/critical-urgent issues.

I think at minimum untriaged issues also shouldn't be closing but I'm not sure if this was discussed.


----

In https://github.com/kubernetes-sigs/kind we've disabled the bot entirely for some time now and only close issues that are one of:
- duplicates (and label as such + link to the other issue)
- not enough info and unable to get a follow-up from the author with sufficient detail (which we eventually close ourselves when reviewing issues)
- resolved

And other than issues that lack info and don't receive more info after some time, all issues are considered accepted without the triage labeling.

I think it works well, and we should consider this for smaller repos. I understand concerns with Kubernetes/Kubernetes issue volume, though I also don't think the current approach is desirable.

**Comment by tallclair** [comment] 2022-10-14 17:10
If folks are reluctant to disable the bot entirely (Ben's suggestion), I have an alternate proposal:

1. Triaged issues are never marked stale or closed.
2. _(optional)_ After 1 year (or some long timeline) of no activity, require triaged issues to be re-triaged (this is sort of like marking them as stale)
3. Regular stale/rotten/closed rules are applied to untriaged issues

**Comment by sftim** [comment] 2022-10-16 20:34
AIUI, the bot was originally brought in for PRs and issues were adding later. For that reason I have +1'd https://github.com/kubernetes/kubernetes/issues/103151#issuecomment-1279262642.

**Comment by thockin** [comment] 2022-11-11 18:23
> not enough info and unable to get a follow-up from the author with sufficient detail (which we eventually close ourselves when reviewing issues)

This is a major use-case for me.  If we only auto-close issues which are "needs-triage" AND "needs-information", I'd be happy.  

>  After 1 year (or some long timeline) of no activity, require triaged issues to be re-triaged 

I like this too!  "needs triage" is a good signal, so far.

**Comment by enj** [comment] 2022-12-01 15:20
To throw out another suggestion specific to k/k, I run the weekly SIG Auth Issue triage meeting with @ritazh @aramase @nilekhc @ibihim @natalisucks and others.  We are slowly getting through our issues, slowly improving the automation around the triage process, etc.

I find this bot to be harmful, abrasive and an incredible waste of the community's time.

My proposal is very simple: if a k/k issue or PR has the `sig/auth` label and the total number of SIG labels is 3 or less, the bot should ignore it completely.  I and the other SIG members will take complete ownership of our issues and their triage.  I have no problem closing issues and PRs directly.  The passage of time does not solve bugs.

**Comment by tallclair** [comment] 2022-12-16 00:25
Who (which group) own's the bot? Who are the deciders on a change to it's behavior? It sounds like there's pretty broad agreement that it needs a change, do we just need someone to open a PR and make it so?

**Comment by BenTheElder** [comment] 2022-12-16 17:14
The code is implemented by SIG Testing but workflow changes need to go through contributor experience (https://github.com/kubernetes/test-infra/issues/28021), as reminded when recently shipping https://github.com/kubernetes/test-infra/issues/28021 to stop auto-closing "help-wanted" and "good-first-issue" labeled issues.

**Closed** 2023-02-07 23:17 UTC
Labels: kind/bug, sig/contributor-experience, lifecycle/frozen, needs-triage

**Comment by ShadowJonathan** [comment] 2024-01-30 09:08
I just saw the bot pop up again here; https://github.com/kubernetes/kubernetes/issues/484#issuecomment-1915738548

I thought it was decided that the bot was gone? Why was it added again?

**Comment by MadhavJivrajani** [comment] 2024-01-30 10:59
@ShadowJonathan the bot was never gone. However, the policy for auto-close was revised. Applying triage/accepted on the issue should give you a 1 year runway before the cycle begins again. 

See: https://github.com/kubernetes/test-infra/pull/28266
