### ISSUE TITLE
e2e flake: deployment should support rollover [minUnavailable/maxSurge violated]

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22719] opened 2016-03-08 23:07 UTC
kubernetes-jenkins/logs/kubernetes-e2e-gce/12967
```
• Failure [314.132 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should support rollover [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:59

  Expected error:
      <*errors.errorString | 0xc2084d9e90>: {
          s: "failed to wait for pods running: [gave up waiting for pod 'test-rollover-controller-0pi42' to be 'running' after 5m0s]",
      }
      failed to wait for pods running: [gave up waiting for pod 'test-rollover-controller-0pi42' to be 'running' after 5m0s]
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:461
```
cc @janetkuo

**Comment by bgrant0607** [comment] 2016-03-09 04:03
kubernetes-jenkins/logs/kubernetes-e2e-gce/13020
```
• Failure [188.857 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should support rollover [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:59

  Expected error:
      <*errors.errorString | 0xc20835e7e0>: {
          s: "error waiting for deployment test-rollover-deployment status to match expectation: total pods created: 6, more than the max allowed: 5",
      }
      error waiting for deployment test-rollover-deployment status to match expectation: total pods created: 6, more than the max allowed: 5
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:511
```

**Comment by bgrant0607** [comment] 2016-03-10 04:42
See also #21810

**Comment by janetkuo** [comment] 2016-03-11 01:12
The cause is that when we update the new RS's revision, the new RS is stale and we end up updating its Spec.Replicas to an earlier value. 
```
I0309 03:08:31.106162       7 event.go:211] Event(api.ObjectReference{Kind:"Deployment", Namespace:"e2e-tests-deployment-iz49z", Name:"test-rollover-deployment", UID:"33b1025f-e5a4-11e5-bd95-42010af00002", APIVersion:"extensions", ResourceVersion:"3889", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set test-rollover-deployment-2012901151 to 1
I0309 03:08:31.302921       7 event.go:211] Event(api.ObjectReference{Kind:"Deployment", Namespace:"e2e-tests-deployment-iz49z", Name:"test-rollover-deployment", UID:"33b1025f-e5a4-11e5-bd95-42010af00002", APIVersion:"extensions", ResourceVersion:"3900", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set test-rollover-controller to 3
I0309 03:08:31.374507       7 event.go:211] Event(api.ObjectReference{Kind:"Deployment", Namespace:"e2e-tests-deployment-iz49z", Name:"test-rollover-deployment", UID:"33b1025f-e5a4-11e5-bd95-42010af00002", APIVersion:"extensions", ResourceVersion:"3900", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set test-rollover-deployment-2012901151 to 2
I0309 03:08:32.973830       7 deployment_controller.go:772] updating replica set "test-rollover-deployment-3944704550"'s revision to 2 - &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:test-rollover-deployment-3944704550 GenerateName: Namespace:e2e-tests-deployment-iz49z SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[deployment.kubernetes.io/revision:2]} Spec:{Replicas:0 Selector:0xc208f6e2c0 Template:0xc208632f20} Status:{Replicas:0 ObservedGeneration:0}}
I0309 03:08:33.022979       7 replica_set.go:455] Too many "e2e-tests-deployment-iz49z"/"test-rollover-deployment-2012901151" replicas, need 0, deleting 2
I0309 03:08:33.024264       7 event.go:211] Event(api.ObjectReference{Kind:"Deployment", Namespace:"e2e-tests-deployment-iz49z", Name:"test-rollover-deployment", UID:"33b1025f-e5a4-11e5-bd95-42010af00002", APIVersion:"extensions", ResourceVersion:"3950", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set test-rollover-deployment-2012901151 to 0
```

**Comment by janetkuo** [comment] 2016-03-11 01:43
This is similar to #21810, the old RS is scaled up (when it should be scaled down) unexpectedly.

**Comment by bgrant0607** [comment] 2016-03-11 07:34
Removing from v1.2 unless/until this recurs

**Comment by janetkuo** [comment] 2016-03-11 20:09
Watching if #22828 fixes this failure mode.

**Comment by nikhiljindal** [comment] 2016-03-11 21:41
Failed again: https://github.com/kubernetes/kubernetes/pull/22872#issuecomment-195552901

```
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:79
  deployment should support rollover [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:66

  Expected error:
      <*errors.errorString | 0xc208551dd0>: {
          s: "error waiting for deployment test-rollover-deployment status to match expectation: total pods created: 7, more than the max allowed: 5",
      }
      error waiting for deployment test-rollover-deployment status to match expectation: total pods created: 7, more than the max allowed: 5
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:518
```

**Comment by janetkuo** [comment] 2016-03-11 22:10
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22872/kubernetes-pull-build-test-e2e-gce/32425/?debugUI=DEVELOPERS

**Comment by janetkuo** [comment] 2016-03-11 23:22
The scaling events look right, but one of the old replicas's status.replicas and spec.replicas doesn't look right. 

`test-rollover-controller` has been scaled down 4 -> 3 -> 1 -> 0, but its `spec.replicas` and `status.replicas` are both 3, and there's only 1 pod (available) it manages in the system when the test failed.

**Comment by janetkuo** [comment] 2016-03-11 23:50
RS replicas seem to be updated correctly. 

```
I0311 20:56:14.457855       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 3->3 (need 1), sequence No: 4->5
I0311 20:56:14.502351       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 3->1 (need 1), sequence No: 5->5
I0311 20:56:15.684891       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 1->0 (need 0), sequence No: 6->6
I0311 20:56:15.693625       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 0->0 (need 0), sequence No: 6->6
```

**Comment by janetkuo** [comment] 2016-03-12 00:21
In the e2e test log, `test-rollover-controller`'s Generation and ObservedGeneration are 4.

**Comment by janetkuo** [comment] 2016-03-12 00:46
```
1. I0311 20:55:46.742636       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 4->3 (need 3), sequence No: 4->4
2. I0311 20:55:48.416437       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-deployment-2012901151, 2->0 (need 0), sequence No: 3->3
3. I0311 20:56:14.457855       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-controller, 3->3 (need 1), sequence No: 4->5
4. I0311 20:56:14.500772       6 replica_set_utils.go:45] Updating replica count for ReplicaSet: test-rollover-deployment-2446224220, 2->2 (need 4), sequence No: 2->3
```
Looks like the RSes are correctly scaled up/down, and the replica count is updated right, but the e2e test `waitForDeploymentStatus` listed RSes without noticing the `test-rollover-controller` replica count update in step 3.

**Comment by janetkuo** [comment] 2016-03-12 00:50
I think it's because in `waitForDeploymentStatus` we didn't list old RSes and new RSes atomically.

**Comment by bgrant0607** [comment] 2016-03-12 04:05
Good catch!

FWIW, there is no such thing as "atomic", except for individual keys in etcd. 

The functions being called were mutating, not just polling.

**Comment by Random-Liu** [comment] 2016-04-02 00:56
Another two occurrences: 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23506/kubernetes-pull-build-test-e2e-gce/34204/artifacts/
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23763/kubernetes-pull-build-test-e2e-gce/34198/
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:69
Expected error:
    <*errors.errorString | 0xc2083cef60>: {
        s: "error waiting for deployment test-rollover-deployment status to match expectation: total pods available: 2, less than the min required: 3",
    }
    error waiting for deployment test-rollover-deployment status to match expectation: total pods available: 2, less than the min required: 3
not to have occurred
```

**Comment by janetkuo** [comment] 2016-05-28 00:25
cc @pwittrock

**Comment by janetkuo** [comment] 2016-05-31 18:34
Closing in favor of #26509

**Closed by janetkuo** 2016-05-31 18:34 UTC
Labels: area/app-config-deployment, kind/flake, priority/P1, team/ux
