### ISSUE TITLE
Move pkg/volume/testing.go to separate testing package

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#20243] opened 2016-01-27 22:38 UTC
That file contains a number of fake/mock objects used for testing, and it should really be moved to a separate package. Currently, all that code ends up in the production binaries.

As an aside, if doing this work, please change the "FindEmptyDirectoryUsageOnTmpfs" method to use the "MkTmpDir" call in "pkg/util/testing" package.

**Comment by mattjmcnaughton** [comment] 2016-01-31 04:36
I think the part about moving `pkg/volume/testing.go` might be a duplicate of https://github.com/kubernetes/kubernetes/issues/16106. I think its useful to keep this open though, to make the change re `MkTmpDir`.

**Closed** 2016-05-29 13:32 UTC
Labels: area/storage, area/test, kind/cleanup, team/test-infra
