### ISSUE TITLE
"Do not marhal internal struct" panic in apiserver

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#41316] opened 2017-02-13 11:43 UTC
When running some large cluster tests, apiserver panicked for me with this log:
```
I0213 11:31:35.972051       7 wrap.go:75] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dgke-gke-large-deploy-default-pool-4-6ad2147f-tgvw: (920.40887ms) 200 [[rescheduler/v0.0.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:38306]
E0213 11:31:35.974487       7 runtime.go:66] Observed a panic: "do not marshal internal struct" (do not marshal internal struct)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/encoding/json/encode.go:275
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/json.go:27
<autogenerated>:46
/usr/local/go/src/encoding/json/encode.go:431
/usr/local/go/src/encoding/json/encode.go:307
/usr/local/go/src/encoding/json/encode.go:280
/usr/local/go/src/encoding/json/encode.go:145
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field/errors.go:53
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors/errors.go:186
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/update.go:113
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:459
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:482
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:289
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:529
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:474
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:770
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1015
/usr/local/go/src/runtime/asm_amd64.s:2086
panic: do not marshal internal struct [recovered]
	panic: do not marshal internal struct [recovered]
	panic: do not marshal internal struct

goroutine 3930955 [running]:
panic(0x296e720, 0xc636405160)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc51eedbf28, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x296e720, 0xc636405160)
	/usr/local/go/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).marshal.func1(0xc51eedb3f8)
	/usr/local/go/src/encoding/json/encode.go:275 +0x19f
panic(0x296e720, 0xc636405150)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/pkg/api.Taint.MarshalJSON(0xc4708f1e80, 0x12, 0xc483dd7c20, 0x25, 0xc636404cd0, 0xa, 0x0, 0x0, 0x0, 0xc556d59800, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/json.go:27 +0x6d
k8s.io/kubernetes/pkg/api.(*Taint).MarshalJSON(0xc556d598b0, 0x2ddeea0, 0xc556d598b0, 0xc51eedb348, 0xc556d598b0, 0x5087220)
	<autogenerated>:46 +0x77
encoding/json.marshalerEncoder(0xc64672dc30, 0x2ddeea0, 0xc556d598b0, 0x99, 0xc556d50100)
	/usr/local/go/src/encoding/json/encode.go:431 +0xb1
encoding/json.(*encodeState).reflectValue(0xc64672dc30, 0x2ddeea0, 0xc556d598b0, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc64672dc30, 0x2ddeea0, 0xc556d598b0, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x2ddeea0, 0xc556d598b0, 0x303db3c, 0x13, 0x7fc37be47200, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:145 +0x8f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field.(*Error).ErrorBody(0xc66715fb00, 0x0, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field/errors.go:53 +0x94
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors.NewInvalid(0x0, 0x0, 0x270fbb4, 0x4, 0xc66715f6c0, 0x31, 0xc636405130, 0x2, 0x2, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors/errors.go:186 +0xab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest.BeforeUpdate(0x5080b60, 0xc4209a96c0, 0x7fc37b9db2d0, 0xc483dd6930, 0x504eca0, 0xc5eb554780, 0x504eca0, 0xc6a151bb80, 0x0, 0x8)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/update.go:113 +0x42c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update.func1(0x504eca0, 0xc6a151bb80, 0x0, 0x359421, 0x6, 0x0, 0x0, 0x359421, 0xc66715fa28)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:459 +0x303
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*store).updateState(0xc4202c2a80, 0xc66715fa40, 0xc52213f570, 0x504eca0, 0xc6a151bb80, 0x0, 0x0, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:482 +0x5b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*store).GuaranteedUpdate(0xc4202c2a80, 0x7fc37bdf3cc0, 0xc483dd6930, 0xc556d597c0, 0x43, 0x504eca0, 0xc6a151b900, 0x1, 0xc680c6dc60, 0xc52213f570, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:289 +0x492
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage.(*Cacher).GuaranteedUpdate(0xc42086d960, 0x7fc37bdf3cc0, 0xc483dd6930, 0xc66715f9c0, 0x3a, 0x504eca0, 0xc6a151b900, 0x1, 0xc680c6dc60, 0xc52213f570, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:529 +0x331
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update(0xc4209b1200, 0x7fc37b9db2d0, 0xc483dd6930, 0xc556d59552, 0x31, 0x50657e0, 0xc66715f980, 0x0, 0x0, 0xc5ed7ca600, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:474 +0x3be
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1.2(0xc500000018, 0x3b2e7f0, 0xc5ed7ca758, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:770 +0x11b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc5ae44a480, 0xc52213f500, 0xc5ae44a420, 0xc5ae44a300)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1015 +0x99
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1020 +0xd9
```

@kubernetes/sig-api-machinery-misc @smarterclayton @lavalamp

**Comment by wojtek-t** [comment] 2017-02-13 11:55
@gmarek @timothysc @davidopp 

it seems to be taint-related to me (looking into stacktrace from above, in particular those 2 lines):
```
k8s.io/kubernetes/pkg/api.Taint.MarshalJSON(0xc4708f1e80, 0x12, 0xc483dd7c20, 0x25, 0xc636404cd0, 0xa, 0x0, 0x0, 0x0, 0xc556d59800, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/json.go:27 +0x6d
k8s.io/kubernetes/pkg/api.(*Taint).MarshalJSON(0xc556d598b0, 0x2ddeea0, 0xc556d598b0, 0xc51eedb348, 0xc556d598b0, 0x5087220)
	<autogenerated>:46 +0x77
```

**Comment by liggitt** [comment] 2017-02-13 12:13
Dupe of https://github.com/kubernetes/kubernetes/issues/40491

**Comment by timothysc** [comment] 2017-02-13 16:43
closing this one.

**Closed by timothysc** 2017-02-13 16:43 UTC
Labels: kind/bug, priority/important-soon, sig/api-machinery
