### ISSUE TITLE
e2e flake: KubeProxy should test kube-proxy

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#20552] opened 2016-02-03 12:23 UTC
The test failed 2 times in slow suite:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/1793/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/1794/

No changes were merged this time.

Creating new issue as requested in https://github.com/kubernetes/kubernetes/issues/17781#issuecomment-173322936

**Comment by piosz** [comment] 2016-02-03 12:24
Yet another
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/1790/

**Comment by thockin** [comment] 2016-02-03 17:44
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-slow/1802/

**Comment by bprashanth** [comment] 2016-02-08 17:51
Fwiw logs from 5 days show what look like the watch bug, which was fixed on friday

**Comment by a-robinson** [comment] 2016-02-24 21:33
This failed in the e2e-gke-slow suite this morning:
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/1038/

```
KubeProxy should test kube-proxy [Slow]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:101 Expected : 1 to be == : 2
```

**Comment by a-robinson** [comment] 2016-02-24 22:26
And in e2e-gce-slow this afternoon:
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/2565/

**Comment by bprashanth** [comment] 2016-02-26 01:51
The gce slow failure looks like https://github.com/kubernetes/kubernetes/issues/21820#issuecomment-188523868, which seems like a kubectl exec bug, and the gke slow failure should be ameliorated with https://github.com/kubernetes/kubernetes/pull/22022 because it looks like a slow kube-proxy.

**Comment by ArtfulCoder** [comment] 2016-02-26 15:46
I will be making a small change to kubeproxy test to space out the retries within the test.
Lowering the priority of this bug since we have a good sense of what the root causes could be.

**Comment by fabioy** [comment] 2016-02-26 19:57
FYI, this test has flaked again, halting merge queue:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-slow/1112/

**Comment by bprashanth** [comment] 2016-02-26 22:15
For the record the last issue is *not* kube-proxy slowness. We had one of our endpoints go MIA toward the end of the test. 

There are 2 endpoints, netserver-1 and netserver-2. 
They landed on nodes: 130.211.138.98,  104.197.238.202
Something happened on the node ~18:50 such that one of them went offline. We know that things were ok before that because the previous sub-test (udp) hit both endpoints. 

In both logs you see a pattern like: 
```
I0226 18:47:47.580854    3375 kubelet.go:2330] SyncLoop (ADD, "api"): "netserver-1_e2e-tests-e2e-kubeproxy-tfjca(6de771f6-dcb9-11e5-9218-42010af00006)"


I0226 18:47:51.762606       5 proxier.go:484] Setting endpoints for "e2e-tests-e2e-kubeproxy-tfjca/node-port-service:udp" to [10.180.0.5:8081 10.180.1.5:8081 10.180.2.5:8081]
I0226 18:50:04.706593       5 proxier.go:484] Setting endpoints for "e2e-tests-e2e-kubeproxy-tfjca/node-port-service:http" to [10.180.0.5:8080 10.180.2.5:8080]

I0226 18:50:58.086113    3375 manager.go:1339] Container "42fd2b17c517db140180a0f1fc209b333721f09943a5f37d3ddd44b76e2b685d e2e-tests-e2e-kubeproxy-tfjca/netserver-1" exited after 312.586612ms
```
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/1112/artifacts/

Which indicates that the container was alive before and after, and kube-proxy updated the iptables on time. We also see docker restarts with:
```
time="2016-02-26T18:45:27.415677319Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually"
time="2016-02-26T18:45:31.471646705Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually"
time="2016-02-26T18:45:46.543710737Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually"
```

Though the timing doesn't match up, they could be related. Docker recovers because we rm /var/lib/docker/network. I'm reviewing https://github.com/kubernetes/kubernetes/pull/22080 which should clear some confusion around the docker restarts. 

@ArtfulCoder some clarity to the test would be nice, i.e which endpoints do we expect to hit, bouncing through which pod on which node (all this one can figure out by sifting through the logs), and which were actually returned. You can use a pattern like the services test (https://github.com/kubernetes/kubernetes/pull/22027) instead of the `sort| uniq| wc`, if you want to do this.

**Comment by bprashanth** [comment] 2016-02-29 01:00
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-slow/1186/
I updated https://github.com/kubernetes/kubernetes/pull/18672, and I'm also spacing out the hit endpoints calls which currently runs in a tight loop ~10 times. I would still recommend that instead of trying to wc -l we try hitting one endpoint for a while, the try hitting the next.

**Comment by wojtek-t** [comment] 2016-02-29 13:37
This happened again:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/2727/

**Comment by bprashanth** [comment] 2016-02-29 18:17
The last failure is different, looks like a manifestation of https://github.com/kubernetes/kubernetes/issues/20550. A netserver-2 pod failed to come online. From the logs, it was stuck in image pull backoff:
```
ResourceVersion:"3500", FieldPath:"spec.containers{webserver}"}): type: 'Normal' reason: 'BackOff' 
Back-off pulling image "gcr.io/google_containers/netexec:1.4"
I0229 12:03:44.967665    3373 server.go:600] Event(api.ObjectReference{Kind:"Pod", 
Namespace:"e2e-tests-e2e-kubeproxy-v1n8m", Name:"netserver-2", UID:"d5658d7e-dedb-11e5-bc5e-42010af00002", APIVersion:"v1", ResourceVersion:"3500", FieldPath:""}): type: 'Warning' reason: 
'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "webserver" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/netexec:1.4\""
```

And it went into backoff because of:
```
E0229 11:59:06.899203    3373 metadata.go:112] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
...
https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable
```

and docker logs are full of:
```
time="2016-02-29T12:03:44.966864184Z" level=error msg="Handler for GET /images/gcr.io/google_containers/netexec:1.4/json returned error: No such image: gcr.io/google_containers/netexec:1.4" 
time="2016-02-29T12:03:44.966926666Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/netexec:1.4" statusCode=404 
time="2016-02-29T12:03:58.967532603Z" level=error msg="Handler for GET /images/gcr.io/google_containers/netexec:1.4/json returned error: No such image: gcr.io/google_containers/netexec:1.4" 
time="2016-02-29T12:03:58.967595593Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/netexec:1.4" statusCode=404 
time="2016-02-29T12:04:10.965871866Z" level=error msg="Handler for GET /images/gcr.io/google_containers/netexec:1.4/json returned error: No such image: gcr.io/google_containers/netexec:1.4" 
time="2016-02-29T12:04:10.965923514Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/netexec:1.4" statusCode=404 
```
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-slow/2727/artifacts/104.154.31.134%3A22-docker.log.log

**Comment by thockin** [comment] 2016-02-29 18:20
if #20550 is fixed, why are we still seeing it here?  I've been away for a few days - what more do we need to do on this issue?

**Comment by bprashanth** [comment] 2016-02-29 18:22
I believe there have been a few threads/issues about a potential gcr.io issue (the 404s are really weird and out of our control). I haven't parsed the logs to know if we were too aggressive in backing off, but it looks like with the number of 404s backing off might've been the right thing.

**Comment by bprashanth** [comment] 2016-02-29 18:24
@mattmoor for the gcr.io weirdness

**Comment by bprashanth** [comment] 2016-03-17 21:20
I believe this issue can be closed, we re-opened https://github.com/kubernetes/kubernetes/issues/20550 for the gcr.io weirdness and it shouldn't be failing in other modes because of previous fixes

**Comment by gmarek** [comment] 2016-03-29 10:38
Yet again: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-slow/2159/

**Comment by thockin** [comment] 2016-04-18 17:16
@ArtfulCoder This is a P0 because of recurrence - any thoughts on next steps to root this out?

**Comment by bprashanth** [comment] 2016-04-18 17:20
Has it actually happened since the one time 20 days ago? (if no, I'd suggest looking through the logs of that one run and making sure it isn't something totally unrealted). 

The times I've seen it recently, it's been a manifestation of  https://github.com/kubernetes/kubernetes/issues/20552#issuecomment-190317859 which is closer to https://github.com/kubernetes/kubernetes/issues/20550

**Comment by pwittrock** [comment] 2016-05-26 20:30
Looks like it has been almost 2 months since the last time we recorded seeing this issue.  Any objection to closing it and letting the merge-bot open a new issue if we see it again.

**Closed** 2016-05-26 20:45 UTC
Labels: kind/flake, priority/P0, team/cluster
