### ISSUE TITLE
Fix data decode and retention mechanics

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#31924] opened 2016-09-01 21:54 UTC
This is obtuse to explain so I will try my best... 

In the storage layer we decode objects that come in off the wire from etcd.  That's all objects, irrespective of what we use higher up the stack.  These are kept as raw fully unpacked api-objects in memory.  

From there we construct a series of caches, typically from the key, which is actually a mundging of the meta-data of that object.  That representation is never reflected into the object for fast access, instead we always reconstruct keys in filter-functions using the meta-data.

From there, that data is then passed through the registry and re-encoded to transfer over the wire, even though we've never used 90 of it's decoded state.  

So ... thoughts on fixing?  

Almost seems like and MVC problem. 

/cc @kubernetes/sig-scalability @smarterclayton @jeremyeder

**Comment by wojtek-t** [comment] 2016-09-02 06:36
The key is a slightly separate issue and we can probably solve it much easier.

Regarding decoding - what we basically need to decode it to do the filtering. For that we need:
- labels (for which we obviously don't need to decode the whole object) - and IIUC @smarterclayton has some plan to do the "partial decode" for protobufs (since we will hopefully have protobufs in storage since 1.5)
- however, we also do filtering on some objects fields (e.g. NodeName of a pod), which turns to be way less obvious how to do...

**Comment by timothysc** [comment] 2016-09-02 16:51
I'm of the mind that the data we store in etcd does not need to be 1:1 representation of the api-objects themselves and could be envelope wrapped such that we only decode the envelope and cache the letter.  The envelope can contain the data we need to make our lives easier.

**Comment by smarterclayton** [comment] 2016-09-02 17:24
The problem is we don't know what data needs to be in the envelope.  Why
not denormalize on save if that's the case?

Partial protobuf is possible but is going to be somewhat ugly.  Still
trying to work out what it means.

On Fri, Sep 2, 2016 at 12:51 PM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment] 2016-09-02 17:45
> The problem is we don't know what data needs to be in the envelope.

Umm yes we do.

**Comment by smarterclayton** [comment] 2016-09-05 18:51
The data in the envelope will change over time, meaning that it must be versioned, meaning that we have a proliferation of types in the envelope and in storage.  We won't know what data has to be in the envelope for all versions, and different controllers need different data.  Our access patterns for caches are all over the place - labels and namespace are great starts, but enough caches require a larger subset of the object that I'd be surprised if the envelope didn't end up at 50% of the size of some structs.

I'd rather invest in generic fast extraction for JSON and Protobuf which can key off of Go structs or be parameterized.  I don't think the envelope would allow us to save more info than that.

**Comment by timothysc** [comment] 2016-09-06 20:31
re: versioning, yup.  

If the envelope/indexer ended up being 50% of the size of the letter then we have a classic data model access problem.  Meaning we should rethink our data model, or how we've sub-divided data in our registry, and whether it meets the needs of the access patterns.

**Comment by smarterclayton** [comment] 2017-06-01 18:41
Smart objects will happen at some point.  Just not breaking the bank today.  Moving to sig-scalability.

**Closed** 2018-02-24 16:10 UTC
Labels: lifecycle/rotten, priority/backlog, sig/api-machinery, sig/scalability
