### ISSUE TITLE
kube::release::package_hyperkube() fails to complete

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#39501] opened 2017-01-06 00:09 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`): Top of master
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1", GitCommit:"8ef690251641b7df6749f67abff86fa01c10b070", GitTreeState:"clean", BuildDate:"2017-01-05T23:16:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Build

**What happened**:
hyperkube fails

**What you expected to happen**:
hyperkube package to build

**How to reproduce it** (as minimally and precisely as possible):
kube::release::package_hyperkube() with $KUBE_DOCKER_IMAGE_TAG and ${KUBE_DOCKER_REGISTRY-} set.

**Anything else do we need to know**:
tail of log:
```
Step 12 : RUN ln -s /hyperkube /apiserver  && ln -s /hyperkube /controller-manager  && ln -s /hyperkube /federation-apiserver  && ln -s /hyperkube /federation-controller-manager  && ln -s /hyperkube /kubectl  && ln -s /hyperkube /kubelet  && ln -s /hyperkube /proxy  && ln -s /hyperkube /scheduler
 ---> Running in ca0800bdcfd6
 ---> 7b2ed6564e84
Removing intermediate container ca0800bdcfd6
Step 13 : COPY hyperkube /hyperkube
 ---> 2b5bbdacd697
Removing intermediate container 2b8dd5b1f34f
Successfully built 2b5bbdacd697
+++ [0105 15:44:07] Building hyperkube image for arch: s390x

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [build] Error 2
make: *** [release] Error 1
```

cc @kubernetes/test-infra-maintainers

**Comment by ixdy** [comment] 2017-01-06 00:26
cc @gajju26

**Comment by gajju26** [comment] 2017-01-06 08:50
@ixdy  Trying to reproduce and looking into this issue why it is failing for s390x.

**Comment by luxas** [comment] 2017-01-06 08:58
Thanks. To me it looks like s390x is missing from a list somewhere, might be in the kubernetes/release repo or in build/lib/release.sh...

Note that the image did build successfully, it's the tarball creation that somehow fails

**Comment by ixdy** [comment] 2017-01-06 17:15
@luxas ah, good call. looks like [this line](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/Makefile#L107) is the problem: https://storage.googleapis.com/kubernetes-release/network-plugins/cni-s390x-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz does not exist.

**Comment by ixdy** [comment] 2017-01-06 17:18
I think `cd build/cni && ARCH=s390x make push` is all we need to do. @freehan can you confirm?

**Comment by freehan** [comment] 2017-01-06 18:24
@ixdy Yes. That might be the problem. We never build CNI plugins for `s390x` ARCH.

**Comment by ixdy** [comment] 2017-01-06 18:49
Go 1.6 doesn't have support for s390x. I can build the s390x CNI plugin with Go 1.7.4 though.

**Comment by ixdy** [comment] 2017-01-06 18:53
OK, built and pushed https://storage.googleapis.com/kubernetes-release/network-plugins/cni-s390x-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz using go 1.7.4. (The other arches are presumably using go 1.6.something.)

@david-mcmahon can you confirm that this fixes the issue?

**Comment by luxas** [comment] 2017-01-06 21:05
Just FYI, I'm generally updating to go1.7 (including cni) in this PR: https://github.com/kubernetes/kubernetes/pull/38926

Thanks @ixdy for pushing that, I believe it will fix the issue.
(@ixdy Side note, have you now made sure every `Makefile` is pushed from from the PR @gajju26 made where he added s390x to the lists everywhere?)

**Comment by gajju26** [comment] 2017-01-09 07:07
@Ixdy @luxas 
I had been trying to reproduce this issue but I couldn't reproduce this issue because of build failure due to some other issue "_output/bin/deepcopy-gen: Permission denied" Tried to resolve this first but couldn't fix this. If I am not wrong the root cause is known for this failure and the required image is pushed also. Let me know if I have missed adding s390x support to some files. I will make a PR and add those required changes.

**Comment by luxas** [comment] 2017-01-09 21:56
@david-mcmahon ping. Can you confirm that pushing cni did fix the issue?

**Comment by david-mcmahon** [comment] 2017-01-10 00:52
So the build relies on pre-published items?  That seems less than optimal.  At the very least this should have prerequisite checks and error out appropriately rather than attempting to download something mid-build.

Checking the release pipeline now.

**Comment by david-mcmahon** [comment] 2017-01-10 01:25
This does indeed fix the build, so we are unblocked.

**Comment by luxas** [comment] 2017-01-19 19:35
Closing this as it's fixed.

**Closed by luxas** 2017-01-19 19:35 UTC
Labels: area/build-release, area/release-infra, area/test-infra, priority/important-soon
