### ISSUE TITLE
Test failure: SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47381] opened 2017-06-12 23:26 UTC
SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node 1m26s

[log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster-new/7#k8sio-schedulerpriorities-serial-pods-should-be-scheduled-to-low-resource-use-rate-node),  [test grid](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20SchedulerPriorities%5C%20%5C%5BSerial%5C%5D%5C%20Pods%5C%20should%5C%20be%5C%20scheduled%5C%20to%5C%20low%5C%20resource%5C%20use%5C%20rate%5C%20node)

Constant failure suggest test covers old behavior?

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:108
Expected
    <string>: gke-bootstrap-e2e-default-pool-41f3b929-jcc8
to equal
    <string>: gke-bootstrap-e2e-default-pool-41f3b929-l0gr
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:107from junit_01.xml
```

/sig scheduling
/assign @timothysc

**Comment by timothysc** [comment] 2017-06-14 18:35
I do not have time to dig into root cause right now. 
In general, the sig should be cc'd on issues. 

/cc @kubernetes/sig-scheduling-bugs

**Comment by caesarxuchao** [comment] 2017-06-16 19:28
In [gce-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7&width=5), it's most flaky test in the past 10 runs, failed 3 times

cc @kubernetes/kubernetes-release-managers

**Comment by davidopp** [comment] 2017-06-16 19:31
@bsalamat can you look into this?

**Comment by dchen1107** [comment] 2017-06-16 19:43
@bsalamat was trying to reproduce this for last 2 day, but failed. Assigned this to him for more detail information here.

**Comment by bsalamat** [comment] 2017-06-16 19:44
@dchen1107 brought this test to my attention a couple of days ago. I tried to reproduce, but I was not able to in my own cluster after 82 tries. I then tried running all `SchedulerPriorities [Serial]` tests and left them run since yesterday. I stopped it just half an hour ago. 
Given what I have seen so far, I don't think this failure is something of concern, but we should probably try to fix the flakiness if we can.

**Comment by k82cn** [comment] 2017-06-17 00:20
In https://github.com/kubernetes/kubernetes/issues/47382#issuecomment-308307455 , it found the pod to balance resource was not create; so I create a PR (#47488) to see what happened.

Another option is that can we create Pods (e.g. DNS) to management host, so we do not need to create additional Pods to balance resource.

**Comment by caesarxuchao** [comment] 2017-06-23 17:05
It passed for 35 times in https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7, but only passed 4/34 times in https://k8s-testgrid.appspot.com/release-1.7-blocking#gke-serial-release-1-7.

**Comment by monopole** [comment] 2017-06-23 19:22
I apologize for the overlap here with #47769.
That bug is a collection of SchedulerPriorities failures, which includes this.
We could break #47769 into finer parts if there are distinct bugs (like this one) then close #47769

**Comment by monopole** [comment] 2017-06-23 19:29
Very [flakey](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20SchedulerPriorities%5C%20%5C%5BSerial%5C%5D%5C%20Pods%5C%20should%5C%20be%5C%20scheduled%5C%20to%5C%20low%5C%20resource%5C%20use%5C%20rate%5C%20node).

This error doesn't look like a test infra tear down failure (given it happens in `priorities.go`).  But like any error could arise from a race condition.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:108
Expected
    <string>: gke-bootstrap-e2e-default-pool-18c37840-q13w
to equal
    <string>: gke-bootstrap-e2e-default-pool-18c37840-rzs8
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:107
````

**Comment by bsalamat** [comment] 2017-06-23 19:36
This test should be deleted. [My PR](47883) is already out and lgtm'ed. Someone with write permission should merge it. @k82cn @davidopp

**Comment by bsalamat** [comment] 2017-06-23 23:29
The test is deleted. This issue should be closed.

**Comment by ericchiang** [comment] 2017-06-26 20:04
Closing. Thanks @bsalamat

**Closed by ericchiang** 2017-06-26 20:04 UTC
Labels: kind/bug, sig/scheduling, status/in-progress
