### ISSUE TITLE
kubectl panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rthellend** [kubernetes/kubernetes#24606] opened 2016-04-21 16:56 UTC
This is on GKE. Everything at version 1.2.2.

```
$ kubectl rollout history deployment nginx
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb8 pc=0xe1affa]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/util/deployment.Revision(0x0, 0xc2083a2420, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:328 +0x4a
k8s.io/kubernetes/pkg/kubectl.(*DeploymentHistoryViewer).History(0xc20812ccb0, 0x1623b40, 0x7, 0x7ffdd08fdee9, 0x5, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/history.go:80 +0x7ea
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.RunHistory(0xc208134960, 0xc2081ada00, 0x7fd3570f4030, 0xc20804e008, 0xc2081af1c0, 0x2, 0x2, 0xc2081ae260, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_history.go:98 +0x8a8
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.func·002(0xc2081ada00, 0xc2081af1c0, 0x2, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_history.go:55 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc2081ada00, 0xc2081af040, 0x2, 0x2, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc20806d600, 0xc2081ada00, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc20806d600, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

@ivanpi-mtv @kenashcraft

**Comment by rthellend** [comment] 2016-04-21 17:22
Possibly related, it looks like the deployment controller is stuck or dead.

```
$ kubectl get deployment nginx -o yaml | grep -i generation
  generation: 22
  observedGeneration: 20
```

This is on GKE. Is there anything we can poke at ourselves to figure out what the problem is?

**Comment by rthellend** [comment] 2016-04-21 17:44
The same thing happened to another deployment (nginx-http-redirect) in the same cluster. I deleted and recreated both to get us going again.

**Comment by metral** [comment] 2016-05-02 02:04
I'm hitting this issue when my [PR](https://github.com/kubernetes/kubernetes/pull/23673) is getting checked against the `Jenkins unit/integration` test: https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/23673/kubernetes-pull-test-unit-integration/23639/build-log.txt

**Comment by AdoHe** [comment] 2016-05-02 07:59
@rthellend since `observedGeneration < generation`, it seems that the deployment controller has not observed the deployment. It's hard to say what happened to deployment controller without more info. Besides I tried to reproduce this on HEAD, but failed. could you reproduce this one?

**Comment by rthellend** [comment] 2016-05-02 15:54
I haven't tried to reproduce it, and I haven't seen it happen since I filed the issue.

**Comment by bgrant0607** [comment] 2016-05-06 23:28
cc @janetkuo @kargakis

**Comment by kargakis** [comment] 2016-05-07 11:29
When there is no new replicaset, nil takes its place and the panic is caused because of it.

**Comment by janetkuo** [comment] 2016-05-18 04:54
Closing since the fix is in

**Closed by janetkuo** 2016-05-18 04:54 UTC
Labels: area/app-config-deployment, component/kubectl, help-wanted, kind/bug, priority/P2, team/ux

**Comment by dasjestyr** [comment] 2018-04-13 21:27
I seem to have the same error but only if I run it from powershell like `iex "kubectl set env -n $n deploy/deployment-name DEPLOY_DATE=$(Get-Date)"`

If i run the exact same command outside of the script, it works fine. Any suggestions?
