### ISSUE TITLE
pull-kubernetes-e2e-gce fails with 'failed to acquire k8s binaries'

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#87828] opened 2020-02-04 20:25 UTC
**Which jobs are failing**:
pull-kubernetes-e2e-gce

**Which test(s) are failing**:

**Since when has it been failing**:

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87821/pull-kubernetes-e2e-gce/1224756243587928065/

**Reason for failure**:
```
W0204 19:45:07.551] 2020/02/04 19:45:07 main.go:316: Something went wrong: failed to acquire k8s binaries: error during /go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-gce --allow-dup (terminated): signal: killed
W0204 19:45:07.553] 2020/02/04 19:45:07 main.go:755: [Boskos] Update of gce-up-c1-4-glat-up-clu-n failed with no resource name gce-up-c1-4-glat-up-clu-n
W0204 19:45:07.569] Traceback (most recent call last):
W0204 19:45:07.569]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 779, in <module>
```

**Comment by neolit123** [comment] 2020-02-04 20:55
> W0204 19:45:07.553] 2020/02/04 19:45:07 main.go:755: [Boskos] Update of gce-up-c1-4-glat-up-clu-n failed with no resource name gce-up-c1-4-glat-up-clu-n

/sig testing

**Comment by liggitt** [comment] 2020-02-05 00:34
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/87441

**Closed by liggitt** 2020-02-05 00:34 UTC
Labels: kind/failing-test, sig/testing
