### ISSUE TITLE
The re-watch mechanism does not work as expectations

### ISSUE THREAD

**Issue by hormes** [kubernetes/kubernetes#76145] opened 2019-04-04 13:00 UTC
If we have two apiservers and restart one on an upgrade, all watchers will go to the other on and never shuffle to the new one.

```
var (
	// We try to spread the load on apiserver by setting timeouts for
	// watch requests - it is random in [minWatchTimeout, 2*minWatchTimeout].
	minWatchTimeout = 5 * time.Minute
)
```

We do the re-watch in reflector actually, but the underly client will be reused.

**Comment by wojtek-t** [comment] 2019-04-04 13:05
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/48610 which has much more discussion on it.

**Closed by wojtek-t** 2019-04-04 13:05 UTC
Labels: kind/bug, needs-sig
