### ISSUE TITLE
Kubernetes pods is still running even after local disk used by that pod is unmounted

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#88325] opened 2020-02-19 13:07 UTC
Kubernetes version - 1.16.3
helm version - 2.16.1
ubuntu - 16.04.5 (server version)
deploying using kubespray and helm.
Deployed pod using PV with local persistent claim (underlying disk is sdb1).

Performed some test cases.
one of the test cases is removing/un mounting the underlying disk used by pod and observed the behavior.

Even after umounting the disk , pods are running and when checked on nodes using (df -h), no disk is mounted .

Expected Behavior:- pod should go in crashloopbackoff.

question : If above observation is the expected behavior, how local persistent volume works internally?

/sig node
/sig storage

storage
--

storage
--

storage
--

**Comment by marquiz** [comment] 2020-02-19 16:02
Looks like the volume was not mounted by the pod. You should not be able to unmount when the device is "busy" i.e. there are users for it

**Comment by akshaysharama** [comment] 2020-02-19 16:08
Pod is mounting the volume ,I checked using exec to that pod and did df -h.It is there.
Even wrote some data and checked on mounted path in node ,i'm able to see the data.

But when I did sudo umount [mount-path] . It is un mounting but inside pod it is still there(checked using df -h)

**Comment by marquiz** [comment] 2020-02-20 13:06
Uh, sorry, I replied to hastily without thinking further :grimacing:

What you're experiencing is by design in Linux. The pv gets bind mounted inside the container (in a separate mount namespace, that's why you don't see it with `df -h` from the system). After creating the bind mount the kernel treats it just as another mount point to `/sdb1[/subdir]` and the two mount points (in host system and in container) are basically not linked in any way. You can freely unmount the host system mount point and the container mount still persists. Of course, creating new pods/containers with similar PVs is not possible anymore as the mount is gone from the host system.

Based on this I'd suggest closing this issue.

**Closed** 2020-07-19 14:32 UTC
Labels: lifecycle/rotten, sig/node, sig/storage, triage/support
