### ISSUE TITLE
"[k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster" failed on rktnetes

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#26987] opened 2016-06-07 18:45 UTC
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:43
Expected error:
    <*errors.errorString | 0xc82083bd90>: {
        s: "expected to find one replica for RC or deployment with label influxGrafana but got 0",
    }
    expected to find one replica for RC or deployment with label influxGrafana but got 0
not to have occurred
```

cc @kubernetes/sig-node @euank @tmrts

**Comment by dchen1107** [comment] 2016-06-08 17:41
Do we know the root cause of this?

**Comment by euank** [comment] 2016-06-08 20:04
On our CI environment we're running with MONITORING=standalone when it expects influxdb. I can't recall the issue with influxdb that resulted in this (at some point it didn't come up).

I've verified that, at least now, it appears to come up correctly. I'll update our CI environment and verify that test passes with no impact on other tests and, if so, we can close this.

**Comment by dchen1107** [comment] 2016-06-10 16:40
#27092 was merged, close the issue. Thanks!

**Closed by dchen1107** 2016-06-10 16:40 UTC
Labels: dependency/rkt, priority/P0, team/node
