### ISSUE TITLE
Node never gets back to cluster after reboot

### ISSUE THREAD

**Issue by bliss** [kubernetes/kubernetes#14408] opened 2015-09-23 08:47 UTC
Good day!
After a node reboot it never gets back and has NotReady status. Node kubelet status is OK. To bring a node back to cluster I have to restart node kubelet.
Could it be systemd services start order problem? I had similar problem with standalone cAdvisor: when it started not after docker it worked but sent no data.
```
head -n 5 /usr/lib/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service
```
```
kubelet --version
Kubernetes 1.0.3-0.1.git61c6ac5
```
```
uname -a
Linux node2.mydomain.com 3.10.0-229.11.1.el7.centos.x86_64 #1 SMP Wed Aug 12 17:56:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
minimal CentOS 7, KVM setup, bridge networking, master and nodes communicate via one bridge.
Thank you.

**Comment by vishh** [comment] 2015-09-23 17:17
Can you post the events from the kubelet soon after it comes up after a
node restart?

**Comment by bliss** [comment] 2015-09-23 17:51
Surely
```
Sep 23 23:42:24 node1.mydomain.com systemd[1]: Starting Kubernetes Kubelet Server...
Sep 23 23:42:24 node1.mydomain.com systemd[1]: Started Kubernetes Kubelet Server.
Sep 23 23:42:24 node1.mydomain.com kubelet[2050]: I0923 23:42:24.638899    2050 manager.go:127] cAdvisor running in container: "/"
Sep 23 23:42:24 node1.mydomain.com kubelet[2050]: I0923 23:42:24.639383    2050 fs.go:93] Filesystem partitions: map[/dev/vdb:{mountpoint:/var/lib/docker major:253 minor:16} /dev/vda1:{mountpoint:/ major:253 minor:1}]
Sep 23 23:42:24 node1.mydomain.com kubelet[2050]: I0923 23:42:24.641500    2050 manager.go:156] Machine: {NumCores:4 CpuFrequency:3392292 MemoryCapacity:1929428992 MachineID:d3321859f0f64653b2778c1f2ab80307 SystemUUID:D1B02D6D-18C5-49F7-AB09-731B7A84C621 BootID:f74445fe-b0a4-4b42-9972-84c63accfc65 Filesystems:[{Device:/dev/vdb Capacity:53660876800} {Device:/dev/vda1 Capacity:10433613824}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:10737418240 Scheduler:none} 253:16:{Name:vdb Major:253 Minor:16 Size:53687091200 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:52:54:00:51:ca:cb Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:2147074048 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:2 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:3 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}]}
Sep 23 23:42:24 node1.mydomain.com kubelet[2050]: I0923 23:42:24.642743    2050 manager.go:163] Version: {KernelVersion:3.10.0-229.11.1.el7.centos.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.6.2 CadvisorVersion:0.15.1}
Sep 23 23:42:24 node1.mydomain.com kubelet[2050]: I0923 23:42:24.642793    2050 plugins.go:69] No cloud provider specified.
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.000053    2050 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.001534    2050 server.go:661] Watching apiserver
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.071474    2050 plugins.go:56] Registering credential provider: .dockercfg
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.080915    2050 server.go:623] Started kubelet
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: E0923 23:42:26.081092    2050 kubelet.go:682] Image garbage collection failed: unable to find data for container /
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.082482    2050 server.go:63] Starting to listen on 0.0.0.0:10250
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.107207    2050 kubelet.go:702] Running in container "/kubelet"
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.223103    2050 factory.go:226] System is using systemd
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.223480    2050 factory.go:234] Registering Docker factory
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.223847    2050 factory.go:89] Registering Raw factory
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.300605    2050 manager.go:946] Started watching for new ooms in manager
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.300640    2050 oomparser.go:199] OOM parser using kernel log file: "/var/log/messages"
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.301834    2050 manager.go:243] Starting recovery of all containers
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.313954    2050 manager.go:248] Recovery completed
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.316594    2050 status_manager.go:76] Starting to sync pod status with apiserver
Sep 23 23:42:26 node1.mydomain.com kubelet[2050]: I0923 23:42:26.316613    2050 kubelet.go:1725] Starting kubelet main sync loop.
```

**Comment by vishh** [comment] 2015-09-23 18:05
I dont see any issues from the logs. Can you post the output of `kubectl
get events` ?

**Comment by bliss** [comment] 2015-09-23 18:11
Surely
```
FIRSTSEEN                         LASTSEEN                          COUNT     NAME                   KIND      SUBOBJECT   REASON         SOURCE                           MESSAGE
Wed, 23 Sep 2015 13:08:50 +0300   Wed, 23 Sep 2015 20:43:08 +0300   5         node1.mydomain.com   Node                  NodeNotReady   {controllermanager }             Node node1.mydomain.com status is now: NodeNotReady
Wed, 23 Sep 2015 23:42:26 +0300   Wed, 23 Sep 2015 23:42:26 +0300   1         node1.mydomain.com   Node                  starting       {kubelet node1.mydomain.com}   Starting kubelet.
Wed, 23 Sep 2015 23:42:26 +0300   Wed, 23 Sep 2015 23:42:26 +0300   1         node1.mydomain.com   Node                  rebooted       {kubelet node1.mydomain.com}   Node node1.mydomain.com has been rebooted, boot id: f74445fe-b0a4-4b42-9972-84c63accfc65
```

**Comment by vishh** [comment] 2015-09-23 21:47
Hmm. From the events it looks like node was marked as not ready and then the node restarted. After the restart, the node never registered successfully with the apiserver?

cc @kubernetes/goog-node

**Comment by dchen1107** [comment] 2015-09-23 21:58
Which version are you running? I haven't read your issue carefully, but If it is from HEAD, we do have an issue on posting node status from Kubelet caused by a recent refactory code. The buggy code was reverted two days ago.

**Comment by yujuhong** [comment] 2015-09-23 21:59
> Which version are you running? I haven't read your issue carefully, but If it is from HEAD, we do have an issue on posting node status from Kubelet caused by a recent refactory code. The buggy code was reverted two days ago.

From the previous comment, the version is Kubernetes 1.0.3-0.1.git61c6ac5, so the refactoring should not be relevant.

**Comment by yujuhong** [comment] 2015-09-23 22:02
@bliss, could you post the output of `kubectl describe node`? That would at least help us understand whether kubelet is posting node status messages at all.

> Hmm. From the events it looks like node was marked as not ready and then the node restarted. After the restart, the node never registered successfully with the apiserver?

From the LASTSEEN timestamp (` Wed, 23 Sep 2015 20:43:08 +0300`), kubelet transitioned to NodeNotReady after the reboot. I would like to know whether kubelet reported itself as NotReady after restarting, and if so, why did it do that.

Node would not register to apiserver again if the Node object is already in the apiserver.

**Comment by vishh** [comment] 2015-09-23 22:10
@yujuhong: The reboot happened at `Wed, 23 Sep 2015 23:42:26 +0300` whereas the node went to `NotReady` condition prior to that, at `Wed, 23 Sep 2015 20:43:08 +0300`.

**Comment by yujuhong** [comment] 2015-09-23 22:16
> @yujuhong: The reboot happened at Wed, 23 Sep 2015 23:42:26 +0300 whereas the node went to NotReady condition prior to that, at Wed, 23 Sep 2015 20:43:08 +0300.

You're right. I misread one number. It'd still be good to confirm whether kubelet was posting any node status. It could be posting itself as not ready :)
The "rebooted" event was sent when kubelet was composing the node status.

**Comment by bliss** [comment] 2015-09-23 22:25
Thank you for your feedback!
```
kubectl describe node node1.mydomain.com
Name:                   node1.mydomain.com
Labels:                 kuberdock-kube-type=type_0,kuberdock-node-hostname=node1.mydomain.com
CreationTimestamp:      Wed, 23 Sep 2015 23:54:58 +0300
Conditions:
  Type          Status          LastHeartbeatTime                       LastTransitionTime                      Reason                          
        Message
  Ready         Unknown         Thu, 24 Sep 2015 04:20:38 +0300         Thu, 24 Sep 2015 01:21:23 +0300         Kubelet stopped posting node status.    
Addresses:      ::1
Capacity:
 cpu:           4
 memory:        1884208Ki
 pods:          40
Version:
 Kernel Version:                        3.10.0-229.11.1.el7.centos.x86_64
 OS Image:                              CentOS Linux 7 (Core)
 Container Runtime Version:             docker://1.6.2
 Kubelet Version:                       1.0.3-0.1.git61c6ac5
 Kube-Proxy Version:                    1.0.3-0.1.git61c6ac5
ExternalID:                             node1.mydomain.com
Pods:                                   (2 in total)
  Namespace                             Name
  554217d9-09f8-4962-ab71-31330da48a74  2c88c3db-b7aa-4ceb-b783-971560c3de25-j2du9
  a6d16639-cb7f-44c8-9b02-2fa56e758aeb  5b3d56fa-6bc4-41e4-9ceb-bb8fa2c20294-ymbjy
Events:
  FirstSeen                             LastSeen                        Count   From                            SubobjectPath   Reason          Message
  Thu, 24 Sep 2015 01:14:49 +0300       Thu, 24 Sep 2015 01:14:49 +0300 1       {kubelet node1.mydomain.com}                  starting        Starting kubelet.
  Thu, 24 Sep 2015 01:14:49 +0300       Thu, 24 Sep 2015 01:14:49 +0300 14      {kubelet node1.mydomain.com}                  SystemOOM       System OOM encountered
  Thu, 24 Sep 2015 01:14:59 +0300       Thu, 24 Sep 2015 01:14:59 +0300 1       {kubelet node1.mydomain.com}                  starting        Starting kubelet.
  Thu, 24 Sep 2015 01:20:15 +0300       Thu, 24 Sep 2015 01:20:15 +0300 1       {kubelet node1.mydomain.com}                  NodeReady       Node node1.mydomain.com status is now: NodeReady
  Thu, 24 Sep 2015 01:16:11 +0300       Thu, 24 Sep 2015 01:21:23 +0300 3       {controllermanager }                            NodeNotReady    Node node1.mydomain.com status is now: NodeNotReady
  Thu, 24 Sep 2015 04:18:27 +0300       Thu, 24 Sep 2015 04:18:27 +0300 1       {kubelet node1.mydomain.com}                  starting        Starting kubelet.
  Thu, 24 Sep 2015 04:18:27 +0300       Thu, 24 Sep 2015 04:18:27 +0300 1       {kubelet node1.mydomain.com}                  rebooted        Node node1.mydomain.com has been rebooted, boot id: 25aad177-375d-4c63-8a13-5b2f3d7f05df
  Thu, 24 Sep 2015 04:18:27 +0300       Thu, 24 Sep 2015 04:18:27 +0300 1       {kubelet node1.mydomain.com}                  NodeReady       Node node1.mydomain.com status is now: NodeReady
  Thu, 24 Sep 2015 04:18:28 +0300       Thu, 24 Sep 2015 04:18:28 +0300 14      {kubelet node1.mydomain.com}                  SystemOOM       System OOM encountered
  Thu, 24 Sep 2015 04:20:38 +0300       Thu, 24 Sep 2015 04:20:38 +0300 1       {kubelet node1.mydomain.com}                  starting        Starting kubelet.
  Thu, 24 Sep 2015 04:20:38 +0300       Thu, 24 Sep 2015 04:20:38 +0300 1       {kubelet node1.mydomain.com}                  rebooted        Node node1.mydomain.com has been rebooted, boot id: 0f6fd064-901b-42a4-aa98-6a0602ce741f
  Thu, 24 Sep 2015 04:20:38 +0300       Thu, 24 Sep 2015 04:20:38 +0300 3       {kubelet node1.mydomain.com}                  SystemOOM       System OOM encountered
```

**Comment by vishh** [comment] 2015-09-23 22:35
Have you configured the kernel to panic on system OOM?

**Comment by bliss** [comment] 2015-09-23 22:37
System OOM (out of memory)?
```
[root@node1 bliss]# free -m
              total        used        free      shared  buff/cache   available
Mem:           1840         176        1231          46         431        1458
Swap:          2047           0        2047
```

**Comment by bliss** [comment] 2015-09-23 22:41
Now nodes basically do nothing, there are a couple of failed elasticsearch containers. Do not know where that OOM came from.

**Comment by vishh** [comment] 2015-09-23 22:45
Can you post the output of `cat /proc/sys/vm/panic_on_oom` ?

**Comment by bliss** [comment] 2015-09-23 22:50
```
[root@node1 bliss]# cat /proc/sys/vm/panic_on_oom
0
```

**Comment by vishh** [comment] 2015-09-23 22:52
Hmm. I wonder why the machine reboots in a loop. Can you post the kernel
logs `dmesg` ?

**Comment by bliss** [comment] 2015-09-23 22:57
@vishh:
not in a loop. All reboots are intentional. Basically when we install our kernel to a node and after installing kubernetes-node it goes rebooted because of necessity to apply the new kernel. after such reboot kubelet never recover on its own. Other reboots are just attemps to make kubelet to start posting correct status. Nodes aren't in production that's why reboots.

**Comment by vishh** [comment] 2015-09-23 23:28
I saw system OOMs and we have noticed in the past that system OOMs end up
slowing down the kubelet. If your node has reached a steady state, without
any OOMs, can you check whether the kubelet recovers now?

**Comment by dchen1107** [comment] 2015-09-24 00:02
I think system OOM in events might misleading here. I suspect there is an issue cadvisor parse kernel logs for OOM information based on the timestamp. 

@bliss Is there any kubelet flag changed? Can you manually restart kubelet service to see if node status changed?

**Comment by bliss** [comment] 2015-09-24 07:12
@dchen1107: Yes, manual kubelet restart make node to be shown as Ready

**Comment by bliss** [comment] 2015-09-26 14:43
@vishh As I suspected after I have asked systemd to start kubelet last with 'Type=idle' the problem disappeared. Thank you!

**Comment by vishh** [comment] 2015-09-26 19:49
Glad to hear the issue has been fixed. In general, kubelet attempts to
manipulate the network that docker daemon uses and in that process, it
restarts docker. I hope that kubelet attempting to restart docker doesn't
cause any confusion on systemd systems.

**Closed** 2015-11-03 05:16 UTC
Labels: team/control-plane, team/node
