### ISSUE TITLE
kube-controller-manager panic

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#83431] opened 2019-10-03 02:24 UTC
**What happened**: `kube-controller-manager` periodically panics, I don't do anything in particular to achieve that. At least I think so.

Here is logs several minutes before + actually the crash:

```
I1003 01:58:07.833371       1 shared_informer.go:204] Caches are synced for TTL 
I1003 01:58:07.862027       1 shared_informer.go:204] Caches are synced for cidrallocator 
I1003 01:58:07.902419       1 shared_informer.go:204] Caches are synced for disruption 
I1003 01:58:07.902443       1 disruption.go:341] Sending events to api server.
I1003 01:58:08.001100       1 shared_informer.go:204] Caches are synced for PVC protection 
I1003 01:58:08.001197       1 shared_informer.go:204] Caches are synced for stateful set 
I1003 01:58:08.003551       1 shared_informer.go:204] Caches are synced for persistent volume 
I1003 01:58:08.021973       1 shared_informer.go:204] Caches are synced for garbage collector 
I1003 01:58:08.022009       1 garbagecollector.go:139] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I1003 01:58:08.045525       1 shared_informer.go:204] Caches are synced for resource quota 
I1003 01:58:08.046627       1 shared_informer.go:204] Caches are synced for expand 
I1003 01:58:08.046636       1 shared_informer.go:204] Caches are synced for resource quota 
I1003 01:58:08.052866       1 shared_informer.go:204] Caches are synced for attach detach 
I1003 01:58:08.914978       1 shared_informer.go:197] Waiting for caches to sync for garbage collector
I1003 01:58:09.015202       1 shared_informer.go:204] Caches are synced for garbage collector 
E1003 02:01:01.000207       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x38d8420), concrete:(*runtime._type)(0x4171300), asserted:(*runtime._type)(0x371f240), missingMethod:""} (interface conversion: interface {} is *v1.Secret, not string)
goroutine 17432 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a23160, 0xc001d544b0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3a23160, 0xc001d544b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).processNextWorkItem(0xc000ee0c30, 0xc00067a100)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:152 +0x2c9
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).worker(0xc000ee0c30)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:140 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00064d9b0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00064d9b0, 0x2540be400, 0x0, 0x1, 0xc0002ad740)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00064d9b0, 0x2540be400, 0xc0002ad740)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:124 +0x1d0
panic: interface conversion: interface {} is *v1.Secret, not string [recovered]
	panic: interface conversion: interface {} is *v1.Secret, not string
goroutine 17432 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3a23160, 0xc001d544b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).processNextWorkItem(0xc000ee0c30, 0xc00067a100)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:152 +0x2c9
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).worker(0xc000ee0c30)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:140 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00064d9b0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00064d9b0, 0x2540be400, 0x0, 0x1, 0xc0002ad740)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00064d9b0, 0x2540be400, 0xc0002ad740)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:124 +0x1d0
```

**What you expected to happen**: I should never panic

**How to reproduce it (as minimally and precisely as possible)**: not sure I can provide anything useful here, it's just a cluster I just provisioned using `kubeadm`

**Anything else we need to know?**:

**Environment**: aws 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: aws t3a.small instances
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2019-10-03 02:39
thanks for the report. this is a duplicate of https://github.com/kubernetes/kubernetes/issues/82854

this is fixed in v1.16.1 by https://github.com/kubernetes/kubernetes/pull/82895

/close

**Closed by liggitt** 2019-10-03 02:39 UTC
Labels: kind/bug, sig/api-machinery
