### ISSUE TITLE
[Flaky test] EmptyDir volumes pod should support shared volumes between containers

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75127] opened 2019-03-07 18:02 UTC
**Which jobs are flaking**:
`ci-kubernetes-e2e-gce-cos-k8sbeta-default` (in `gce-cos-1.14-default`](https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default&width=20)

**Which test(s) are flaky**:
`[sig-storage] EmptyDir volumes pod should support shared volumes between containers`
This test flakes about 10% of the time, with a variety of errors; the job as a whole is among the flakiest (not only due to this test), with a flake rate of ~80%. As `gce-cos-1.14-default` is release-blocking, having steady tests within that job is important to give a strong signal on whether the release is good to ship.

**Reason for failure**:
From most to least common:

```
 error: unable to upgrade connection: container not found ("busybox-main-container")
```

```
error: Internal error occurred: error executing command in container: container not running (0053b22533db4c445b91a87ce2228319a513b143824d5371bbbd38594bd18043)
```

```
error: Internal error occurred: error executing command in container: Error response from daemon: No such exec instance '8e373c1c575c1e09071793ee512cf4703e3d366efed0f25cbf15d4172eb6915d' found in daemon
```

```
Expected error:
    <*errors.errorString | 0xc4206e55f0>: {
        s: "pod ran to completion",
    }
    pod ran to completion
not to have occurred
```
and others that occur less frequently (triage link below).

**Anything else we need to know**:
* [Triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-default%24&test=EmptyDir%20volumes%20pod%20should%20support%20shared%20volumes%20between%20containers)
* Part of https://github.com/kubernetes/kubernetes/issues/74960

/kind flake
/remove-kind failing-test
/sig storage
/milestone v1.14

cc @smourapina @alejandrox1 @kacole2 @mortent @spiffxp

**Comment by gnufied** [comment] 2019-03-07 18:28
duplicate of https://github.com/kubernetes/kubernetes/issues/75068 

/assign

**Comment by liggitt** [comment] 2019-03-07 18:31
/close

will track in the older issue

**Closed by liggitt** 2019-03-07 18:31 UTC
Labels: kind/flake, priority/critical-urgent, sig/storage
