### ISSUE TITLE
flake: Pods should invoke init containers on a RestartNever pod

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25919] opened 2016-05-19 22:20 UTC
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke/7330/

```
[It] should invoke init containers on a RestartNever pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:725
STEP: creating the pod
W0519 14:55:33.521095    4451 request.go:347] Field selector: v1 - pods - metadata.name - pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: need to check if this is versioned correctly.
E0519 15:00:33.521615    4451 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
[AfterEach] [k8s.io] Pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:109
STEP: Collecting events from namespace "e2e-tests-pods-eisug".
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:33 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {default-scheduler } Scheduled: Successfully assigned pod-init-6935827c-1e0c-11e6-95d8-0242ac110014 to gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Pulled: Container image "gcr.io/google_containers/busybox:1.24" already present on machine
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id 9d754e3d878d
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id 9d754e3d878d
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:37 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id cbf2532f0b70
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:37 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id cbf2532f0b70
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:39 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id df6944338ff1
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:39 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id df6944338ff1
May 19 15:00:33.566: INFO: POD                                                               NODE                                        PHASE    GRACE  CONDITIONS
May 19 15:00:33.566: INFO: foo-nnhfd                                                         gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:38 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-y536v                                                         gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:37 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  }]
May 19 15:00:33.566: INFO: pod-init-6935827c-1e0c-11e6-95d8-0242ac110014                     gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Pending  30s    [{Initialized False {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:41 -0700 PDT} ContainersNotInitialized containers with incomplete status: [init1]} {Ready False {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:33 -0700 PDT} ContainersNotReady containers with unready status: [run1]} {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:33 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-9tpg5                                                         gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:29 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-z8s4m                                                         gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:29 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:21 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:21 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-yust  gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:17 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  }]
May 19 15:00:33.566: INFO: heapster-v1.1.0.beta1-2658213798-otbd7                            gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:29 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:36 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:29 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-dns-v11-ykwl2                                                gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:53:03 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6             gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:34 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo             gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:14 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-yust             gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:11 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kubernetes-dashboard-v1.0.1-lpmgq                                 gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:25 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: l7-lb-controller-v0.6.0-hqjq8                                     gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:40 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: 
May 19 15:00:33.571: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.575: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.576: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.607: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.619: INFO: foo-9tpg5 started at 2016-05-19T14:56:27-07:00 (0+1 container statuses recorded)
May 19 15:00:33.619: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.619: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6 started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.619: INFO: foo-y536v started at 2016-05-19T14:54:35-07:00 (0+1 container statuses recorded)
May 19 15:00:33.619: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.619: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6 started at <nil> (0+0 container statuses recorded)
W0519 15:00:33.625505    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:33.690: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.690: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:1m15.178872s}
May 19 15:00:33.690: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:49.623859s}
May 19 15:00:33.690: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:41.109646s}
May 19 15:00:33.690: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.172187s}
May 19 15:00:33.690: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:19.312087s}
May 19 15:00:33.690: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:10.909938s}
May 19 15:00:33.690: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.694: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.694: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.783: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.816: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.816: INFO: foo-z8s4m started at 2016-05-19T14:56:27-07:00 (0+1 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.816: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.816: INFO: foo-nnhfd started at 2016-05-19T14:54:35-07:00 (0+1 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.816: INFO: heapster-v1.1.0.beta1-2658213798-otbd7 started at 2016-05-19T14:52:29-07:00 (0+2 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container heapster ready: true, restart count 0
May 19 15:00:33.816: INFO: 	Container heapster-nanny ready: true, restart count 0
W0519 15:00:33.827717    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:33.909: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.909: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:2m12.940414s}
May 19 15:00:33.909: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:40.007999s}
May 19 15:00:33.909: INFO: {Operation: Method:pod_worker_start_latency_microseconds Quantile:0.99 Latency:40.00792s}
May 19 15:00:33.909: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:37.240203s}
May 19 15:00:33.909: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.054067s}
May 19 15:00:33.909: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:19.222831s}
May 19 15:00:33.909: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:14.438603s}
May 19 15:00:33.909: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.913: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.914: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.920: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.933: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-yust started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.933: INFO: kube-dns-v11-ykwl2 started at 2016-05-19T14:51:53-07:00 (0+4 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container etcd ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container healthz ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container kube2sky ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container skydns ready: true, restart count 0
May 19 15:00:33.933: INFO: kubernetes-dashboard-v1.0.1-lpmgq started at 2016-05-19T14:51:53-07:00 (0+1 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container kubernetes-dashboard ready: true, restart count 0
May 19 15:00:33.933: INFO: l7-lb-controller-v0.6.0-hqjq8 started at 2016-05-19T14:51:53-07:00 (0+2 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container default-http-backend ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container l7-lb-controller ready: true, restart count 0
May 19 15:00:33.933: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-yust started at <nil> (0+0 container statuses recorded)
W0519 15:00:33.938564    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:34.052: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:34.052: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:1m27.970115s}
May 19 15:00:34.052: INFO: {Operation: Method:pod_worker_start_latency_microseconds Quantile:0.99 Latency:40.011826s}
May 19 15:00:34.052: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:37.427391s}
May 19 15:00:34.052: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:35.279983s}
May 19 15:00:34.052: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.050298s}
May 19 15:00:34.052: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:24.778446s}
May 19 15:00:34.052: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.99 Latency:20.007326s}
May 19 15:00:34.052: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.9 Latency:20.007326s}
May 19 15:00:34.052: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "e2e-tests-pods-eisug" for this suite.


â€¢ Failure [305.635 seconds]
[k8s.io] Pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  should invoke init containers on a RestartNever pod [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:725

  Expected
      <*errors.errorString | 0xc820095f10>: {
          s: "timed out waiting for the condition",
      }
  to be nil

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:710
```

**Comment by Random-Liu** [comment] 2016-05-23 07:18
A lot more failures:
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17445/
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17439/
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17426/

**Comment by Random-Liu** [comment] 2016-05-23 08:30
I looked into https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17426/, and found the reason.

Here is the timeline:
* All 3 containers (2 init containers and 1 application container) in the pod only run `/bin/bash`, so the pod finished soon after created.
```
I0522 16:38:14.114728    3384 kubelet.go:2585] SyncLoop (PLEG): "pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017_e2e-tests-pods-dlb35(92f743ec-203b-11e6-a08b-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"92f743ec-203b-11e6-a08b-42010af00002", Type:"ContainerDied", Data:"463471904cb02d1c4229bb04fc4bd318abec7ffd4f0179285b806b4ad773c50f"}
I0522 16:38:15.170187    3384 kubelet.go:2585] SyncLoop (PLEG): "pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017_e2e-tests-pods-dlb35(92f743ec-203b-11e6-a08b-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"92f743ec-203b-11e6-a08b-42010af00002", Type:"ContainerDied", Data:"30e2a7dbb8d8dc79607d0281d6bb5337fe378899659a5e0461769f1f808f4022"}
I0522 16:38:16.209435    3384 kubelet.go:2585] SyncLoop (PLEG): "pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017_e2e-tests-pods-dlb35(92f743ec-203b-11e6-a08b-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"92f743ec-203b-11e6-a08b-42010af00002", Type:"ContainerDied", Data:"14571009d33cbe038fc3f9e3b2ba9f1b9a8f96bde825ef2c95338dd21c237243"}
```
* The first init container `init1` was removed (twice).
```
I0522 16:38:16.759222    3384 manager.go:2122] Removing init container "init1" instance "463471904cb02d1c4229bb04fc4bd318abec7ffd4f0179285b806b4ad773c50f" 2
I0522 16:38:16.803807    3384 manager.go:2122] Removing init container "init1" instance "463471904cb02d1c4229bb04fc4bd318abec7ffd4f0179285b806b4ad773c50f" 2
```
* The first pod status is updated, because there is no historical containers for "init1", it is reported as "Waiting" and will be "Waiting" forever.
```
I0522 16:38:23.581556    3384 manager.go:422] Status for pod "pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017_e2e-tests-pods-dlb35(92f743ec-203b-11e6-a08b-42010af00002)" updated successfully: {status:{Phase:Pending Conditions:[{Type:Initialized Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:0x442f040}} LastTransitionTime:{Time:{sec:63599531897 nsec:0 loc:0x442f040}} Reason:ContainersNotInitialized Message:containers with incomplete status: [init1]} {Type:Ready Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:0x442f040}} LastTransitionTime:{Time:{sec:63599531892 nsec:0 loc:0x442f040}} Reason:ContainersNotReady Message:containers with unready status: [run1]} {Type:PodScheduled Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x442f040}} LastTransitionTime:{Time:{sec:63599531892 nsec:0 loc:0x442f040}} Reason: Message:}] Message: Reason: HostIP:10.240.0.4 PodIP: StartTime:0xc821494dc0 InitContainerStatuses:[{Name:init1 State:{Waiting:0xc820c35460 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/busybox:1.24 ImageID: ContainerID:} {Name:init2 State:{Waiting:<nil> Running:<nil> Terminated:0xc820ac1490} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/busybox:1.24 ImageID:docker://b175bcb790231169e232739bd2172bded9669c25104a9b723999c5f366ed7543 ContainerID:docker://30e2a7dbb8d8dc79607d0281d6bb5337fe378899659a5e0461769f1f808f4022}] ContainerStatuses:[{Name:run1 State:{Waiting:<nil> Running:<nil> Terminated:0xc820ac1500} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/busybox:1.24 ImageID:docker://b175bcb790231169e232739bd2172bded9669c25104a9b723999c5f366ed7543 ContainerID:docker://14571009d33cbe038fc3f9e3b2ba9f1b9a8f96bde825ef2c95338dd21c237243}]} version:5 podName:pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017 podNamespace:e2e-tests-pods-dlb35}
```

The root cause is that kubelet needs at least one instance of each container to generate pod status. But the function [`pruneInitContainersBeforeStart`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L2097-L2141) doesn't follow that. The function removes a container is if:
* It is not the latest init container instance (no matter what the init container name is)
* And it is not in `initContainersToKeep`.

The logic seems wired to me, because the variable [`name`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L2104) is only used to [print error log](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L2128), and the log seems wrong to me:
```
I0522 16:38:16.803807    3384 manager.go:2122] Removing init container "init1" instance "463471904cb02d1c4229bb04fc4bd318abec7ffd4f0179285b806b4ad773c50f" 2
E0522 16:38:16.805471    3384 manager.go:2128] failed to remove pod init container "init2": Error response from daemon: no such id: 463471904cb02d1c4229bb04fc4bd318abec7ffd4f0179285b806b4ad773c50f; Skipping pod "pod-init-92f32ebd-203b-11e6-8c7f-0242ac110017_e2e-tests-pods-dlb35(92f743ec-203b-11e6-a08b-42010af00002)"
```
Anyhow, the `initContainersToKeep` check should make sure that at least one instance of each init container will be kept.

However, when all containers finish, `initContainersToKeep` will be cleared [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1820-L1823). Then all container instances except the latest will be removed, and the pod is reported as "Waiting" because lack of historical containers.

@smarterclayton @yujuhong @dchen1107

**Comment by smarterclayton** [comment] 2016-05-23 14:05
Originally, the status was inferred from the most recent init container (so
the older ones being deleted was ok).  Now we need it to calculate the full
pod status.

Two options:

1. Keep exactly one of all init containers as long as the pod is alive for
status generation
2. Keep only the latest init container (furthest along) and keep whatever
status we have as long as we can (violates the "can be reconstructed by
observing state").

**Comment by smarterclayton** [comment] 2016-05-23 16:13
I think #1 is probably the approach we have to take today.  I'll make a
change to support that by ensuring init containers to keep preserves the
right containers.

**Comment by smarterclayton** [comment] 2016-05-23 16:47
Actually, we always keep *at least one* init container, AND additional ones
if initContainersToKeep calls them out.

**Comment by smarterclayton** [comment] 2016-05-23 16:48
pruneInitContainersBeforeStart assumes status is sorted in order of newest
to oldest.  I wonder if that's not the case.

**Comment by smarterclayton** [comment] 2016-05-23 16:50
I think I see the problem - we're supposed to be preserving ALL init
containers, but we are only preserving the *latest* init containers.  Going
to add a test case and send a fix.

**Comment by yujuhong** [comment] 2016-05-23 17:14
Yes, we want to get rid of the "preserving at least one container" per container name policy, but we're not there yet. It's easier for now to make init container behave like other containers, i.e., always leaving one dead container.

**Comment by smarterclayton** [comment] 2016-05-23 17:15
Fix up.

**Comment by gmarek** [comment] 2016-05-24 10:07
Dupe of #26131

**Comment by yujuhong** [comment] 2016-05-24 15:04
Let's close this one and use #26131 since I don't think the merge bot is smart enough to redirect its posts.

**Closed by yujuhong** 2016-05-24 15:04 UTC
Labels: kind/flake, priority/P1, team/node
