### ISSUE TITLE
e2e flake: "cannot create namespace"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#27610] opened 2016-06-17 11:15 UTC
In this run:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/51/console

131 tests failed.
However, most of them (all but two) failed with the following error:
```
01:40:47   Expected error:
01:40:47       <*errors.errorString | 0xc8200d80d0>: {
01:40:47           s: "timed out waiting for the condition",
01:40:47       }
01:40:47       timed out waiting for the condition
01:40:47   not to have occurred
01:40:47 
01:40:47   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:190
```

which means that we couldn't create a namespace.

However, I looked into logs of apiserver and there are not even such requests in apiserver.

**Comment by wojtek-t** [comment] 2016-06-17 11:15
Exactly the same happened in:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/1543/

[which suggests it's not related to the size of the cluster]

**Comment by wojtek-t** [comment] 2016-06-17 11:16
I'm going to add some log, because we don't even know why those requests to create a namespace are dropped.

**Comment by wojtek-t** [comment] 2016-06-17 11:19
@zmerlynn @gmarek @kubernetes/goog-gke [this may (or may not?) be related to GKE itself (I didn't see it in non-gke suites yet)

**Comment by fejta** [comment] 2016-06-17 21:16
Assigning to people to triage per labels/comments.

**Comment by bgrant0607** [comment] 2016-06-23 07:16
@wojtek-t Assigned to you until your log message yields more info, then we can reassign based on what we learn.

**Comment by wojtek-t** [comment] 2016-06-23 07:21
@bgrant0607 - sure; I added additional logging, but haven't seen this problem since then (6 days ago). I will report back when this happens again.

**Comment by wojtek-t** [comment] 2016-06-24 11:41
This has just happened in gke-serial:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/1599/

It seems that the issue is exactly the one from: https://github.com/kubernetes/kubernetes/issues/27612
So we can't create namespace, because of:
```
Jun 24 02:48:21.797: INFO: Unexpected error while creating namespace: Post https://104.198.222.231/api/v1/namespaces: x509: certificate signed by unknown authority
Jun 24 02:48:23.800: INFO: Unexpected error while creating namespace: Post https://104.198.222.231/api/v1/namespaces: x509: certificate signed by unknown authority
Jun 24 02:48:25.800: INFO: Unexpected error while creating namespace: Post https://104.198.222.231/api/v1/namespaces: x509: certificate signed by unknown authority
Jun 24 02:48:27.800: INFO: Unexpected error while creating namespace: Post https://104.198.222.231/api/v1/namespaces: x509: certificate signed by unknown authority
...
```

**Comment by wojtek-t** [comment] 2016-06-24 11:42
@erictune - can you please triage?

**Comment by wojtek-t** [comment] 2016-06-24 11:42
@cjcullen @kubernetes/goog-gke @roberthbailey 

Though it seems it appear only in GKE so far.

**Comment by wojtek-t** [comment] 2016-06-24 11:44
We may consider closing this as a duplicate of #27612

**Comment by cjcullen** [comment] 2016-06-24 20:34
Yeah this is a dupe of #27612

**Closed by cjcullen** 2016-06-24 20:34 UTC
Labels: kind/flake, priority/P1, team/cluster, team/CSI-API Machinery SIG
