### ISSUE TITLE
Node e2e pull image test fails saying it can't reach gcr.io

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#23669] opened 2016-03-31 05:41 UTC
Seeing a fair number of failures from the PR builder failing because they can't reach gcr.io

`Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable`

May need to disable the affected tests until the issue can be resolved.

18:11:42 I0331 01:07:35.717951    2083 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
18:11:42 I0331 01:07:35.718029    2083 docker.go:161] Pulling image gcr.io/google_containers/busybox:1.24 without credentials
18:11:42 I0331 01:07:36.102990    2083 docker.go:161] Pulling image gcr.io/google_containers/mounttest:0.2 without credentials
18:11:42 • Failure [0.544 seconds]
18:11:42 Container Conformance Test
18:11:42 /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/conformance_test.go:164
18:11:42   container conformance blackbox test
18:11:42   /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/conformance_test.go:163
18:11:42     when testing images that exist
18:11:42     /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/conformance_test.go:79
18:11:42       it should pull successfully [Conformance] [It]
18:11:42       /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/conformance_test.go:63
18:11:42 
18:11:42       Expected error:
18:11:42           <*errors.errorString | 0xc2083c1f00>: {
18:11:42               s: "image pull failed for gcr.io/google_containers/mounttest:0.2, this may be because there are no credentials on this request.  details: (unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable)",
18:11:42           }
18:11:42           image pull failed for gcr.io/google_containers/mounttest:0.2, this may be because there are no credentials on this request.  details: (unable to ping registry endpoint https://gcr.io/v0/
18:11:42           v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
18:11:42            v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable)
18:11:42       not to have occurred

**Comment by bprashanth** [comment] 2016-04-01 00:54
How does one get the link to the test artifacts when a node e2e fails? Usually when e2e fails we get a comment like: https://github.com/kubernetes/kubernetes/pull/23711#issuecomment-204165611. I'm guessing there's some way to map the pr/build-number to a run in jenkins, but a straight link would help.

**Comment by bprashanth** [comment] 2016-04-01 00:58
Also what's the incantation to rerun just the node e2es? 
k8s-bot test this github issue seems to rerun them all.

**Comment by pwittrock** [comment] 2016-04-01 16:07
@k8s-bot node e2e test this

**Comment by pwittrock** [comment] 2016-04-01 16:09
Node e2e doesn't comment on the PR because it was deemed too spammy.  The details link from the status checks section should be sufficient right now.

**Comment by bprashanth** [comment] 2016-04-01 16:11
> The details link from the status checks section should be sufficient right now.

How do I get kubelet logs?

**Comment by pwittrock** [comment] 2016-04-01 16:12
The kubelet logs should be output in the build logs.

**Comment by pwittrock** [comment] 2016-04-01 16:13
Related to #23544

**Comment by pwittrock** [comment] 2016-04-01 17:04
Hoping to mitigate this in #23736

**Comment by bprashanth** [comment] 2016-04-01 18:21
> The kubelet logs should be output in the build logs.

Ah I missed that. It looks like it's still V(2) (or maybe I just missed the right logs), can we bump it to V(4)?

**Comment by sttts** [comment] 2016-06-16 05:37
Happened again: https://github.com/kubernetes/kubernetes/issues/27369#event-693851671

**Comment by dchen1107** [comment] 2016-06-16 16:09
It is indeed a regression issue in the new release of the image registry, gcr.io. The team is rolling back their release. There is nothing more we can do here. Close the issue.

**Closed by dchen1107** 2016-06-16 16:09 UTC
Labels: kind/flake, team/node
