### ISSUE TITLE
EmptyDir can't be removed when pod become evicted

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#35406] opened 2016-10-24 07:04 UTC
**Description of problem**:
Mount a emptyDir in pod `/tmp` then create large file in emptyDir to trigger nodefs.available eviction, when pod become Evicted, the large file can't be removed, node always keep in DiskPressure 

**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.1.804+a7db9bccb56abf-dirty

**What happened**:
File in emptyDir can't be removed after pod become Evicted, and node always keep in DiskPressure=True

**What you expected to happen**:
File in emptyDir should be removed after pod become Evicted, and node become DiskPressure=false after a period.

**How to reproduce it** (as minimally and precisely as possible):

```
1. configure kubelet with eviction-soft
--eviction-soft="nodefs.available<3Gi"
--eviction-soft-grace-period="nodefs.available=20s"
--eviction-pressure-transition-period=30s

2. Create a pod with emptyDir
$ kubectl create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/hello-pod.yaml

3. Create a large file in pod /tmp dir
$ kubectl exec hello-pod -- dd if=/dev/zero of=/tmp/test1 bs=10M count=1024

4. Wait pod become Evicted then check node status and file in emptyDir
[root@ip-172-18-6-200 kubernetes]# kubectl get pod
NAME        READY     STATUS    RESTARTS   AGE
hello-pod   0/1       Evicted   0          23m
[root@ip-172-18-6-200 kubernetes]# kubectl describe node 127.0.0.1|grep DiskPressure
  DiskPressure      True    Mon, 24 Oct 2016 02:56:22 -0400     Mon, 24 Oct 2016 02:33:01 -0400     KubeletHasDiskPressure      kubelet has disk pressure
  29m       29m     2   {kubelet 127.0.0.1}         Normal      NodeHasNoDiskPressure   Node 127.0.0.1 status is now: NodeHasNoDiskPressure
  23m       23m     1   {kubelet 127.0.0.1}         Normal      NodeHasDiskPressure Node 127.0.0.1 status is now: NodeHasDiskPressure
[root@ip-172-18-6-200 kubernetes]# ls -lh /var/lib/kubelet/pods/8095536f-99b3-11e6-9bc0-0ebd788c9e1f/volumes/kubernetes.io~empty-dir/tmp/test1
-rw-r--r--. 1 root root 5.3G Oct 24 02:33 /var/lib/kubelet/pods/8095536f-99b3-11e6-9bc0-0ebd788c9e1f/volumes/kubernetes.io~empty-dir/tmp/test1

```

**Anything else do we need to know**:
When delete the pod the large file in emptyDir then removed.

**Comment by mdshuai** [comment] 2016-10-24 07:05
@derekwaynecarr

**Comment by derekwaynecarr** [comment] 2016-10-24 18:32
@sjenning - can you take this?

**Comment by sjenning** [comment] 2016-10-24 22:10
I am able to reproduce.

The logs show that the pod is evicted, but the pod resources remain.  Here is a debug session dump:
https://paste.fedoraproject.org/460401/34628714/

My theory is that the pod is still scheduled to the node because it is the only node.  This messes up the reconciler because the pod is scheduled to the node and its volumes are in the desired state, even though the pod is not running, so it doesn't think it need to clean anything up.  While the mount points for the pod are unmounted, the reconciler doesn't remove them, leaving the node in a state of unrecoverable disk pressure.

This theory is supported by the fact that if I remove the pod with `kubectl delete pod hello-pod`, effectively unscheduling the pod from the node, the reconciler immediately removes the pod resources, even though the pod is already not running on the node.

Need to look into the order of operations here.  What needs to happen is:

1) pod is evicted
2) pod's scheduled node information is cleared out
3) scheduler should not reassign the pod the node with disk pressure
4) reconciler on the node should clean up the pod resources

**Comment by derekwaynecarr** [comment] 2016-10-25 17:20
The issue is as follows:

1. handle pod clean-ups only cleans up pods that no longer exist on api server.

In response to disk pressure, we need to do the following:

1. cleanup terminal pod volumes
1. evict end-user pods

in handle `cleanupOrphanedPodDirs`

1. always clean-up volumes for pods failed with reason=evicted

The caveat here is memory backed volumes (secrets) as the current flow implies to me that they continue to have a charge to the kubelet memory cgroup even when the pod has reached a terminal state.  I think all tmpfs backed volumes need to be purged when the pod is purged.

/cc @dchen1107 @vishh @kubernetes/sig-node -- I want to discuss this in sig-node today.

**Comment by euank** [comment] 2016-10-25 20:16
We discussed this in the sig-node meeting today.

We all agree this is a problem and at the very least should get in a fix (even if partial) for 1.5. @derekwaynecarr said someone from Redhat should be able to help

The partial fix could just be evicting volumes when there's disk pressure, but it could also be removing any known-tmpfs volumes when the pod's cleaned up.

I think the next step is someone writing up a quick "Here's the fix I want to apply" (I'm not sure that has to be a formal proposal, especially since we want this to be fast)

**Comment by dashpole** [comment] 2016-10-25 21:23
cc @saad-ali

**Comment by derekwaynecarr** [comment] 2016-10-26 15:39
I think my comment above reflects the desired state I want to land at in
kube 1.5 which had no major objection in sig call.  Seth will be doing the
implementation this week.

**Comment by dims** [comment] 2016-11-16 14:39
This needs to be triaged as a release-blocker or not for 1.5 @derekwaynecarr @sjenning

**Comment by derekwaynecarr** [comment] 2016-11-16 15:20
Moved to 1.6, we will handle leaking memory backed volumes in 1.5.

**Closed** 2017-01-20 20:34 UTC
Labels: area/kubelet, sig/node
