### ISSUE TITLE
GCI Test Failing: (kubernetes-e2e-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working zookeeper cluster [Feature:PetSet])

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33317] opened 2016-09-22 20:32 UTC
GCI Test Failing: (kubernetes-e2e-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working zookeeper cluster [Feature:PetSet])

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.4

**Comment by foxish** [comment] 2016-09-23 00:29
Closing for now as the issue is identical to https://github.com/kubernetes/kubernetes/issues/33315

**Closed** 2016-09-23 00:41 UTC
Labels: area/os/gci, priority/P0, team/cluster
