### ISSUE TITLE
`v1.23.0-rc.0` breaks `crictl images` for Docker container-runtime (works fine on 1.23.0-beta.0)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubernetes#106807] opened 2021-12-03 19:57 UTC
### What happened?

On minikube HEAD we tried to bump the "newest" Kubernetes version from k8s `1.23.0-beta.0` to k8s `v1.23.0-rc.0`

however this breaks "crictl images" command

```
$ minikube ssh
docker@minikube:~$ sudo crictl images
FATA[0000] listing images: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService 
https://github.com/kubernetes/minikube/issues/13077
```
 
however if we start minikube with `1.23.0-beta.0` crictl works fine

```
$ make;mk delete --all;mk start --kubernetes-version=v1.23.0-beta.0
$ mk ssh
docker@minikube:~$ sudo crictl images
IMAGE                                     TAG                 IMAGE ID            SIZE
gcr.io/k8s-minikube/storage-provisioner   v5                  ba04bb24b9575       29MB
k8s.gcr.io/coredns/coredns                v1.8.4              6d3ffc2696ac2       44.4MB
k8s.gcr.io/coredns/coredns                v1.8.6              edaa71f2aee88       46.8MB
k8s.gcr.io/etcd                           3.5.0-0             2252d5eb703b0       364MB
k8s.gcr.io/etcd                           3.5.1-0             1040f7790951c       132MB
k8s.gcr.io/kube-apiserver                 v1.23.0-beta.0      70f3ee870024e       132MB
k8s.gcr.io/kube-controller-manager        v1.23.0-beta.0      ba6fcb43638a3       122MB
k8s.gcr.io/kube-proxy                     v1.23.0-beta.0      e223498b094cf       109MB
k8s.gcr.io/kube-scheduler                 v1.23.0-beta.0      916a7b78e5641       52.8MB
k8s.gcr.io/pause                          3.6                 7d46a07936af9       484kB
kubernetesui/dashboard                    v2.3.1              5bb89698273d8       217MB
kubernetesui/metrics-scraper              v1.0.7              5717d272af6d4       32.5MB
```

in changelog I see there are API changes https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#api-change
but I dont see any messages on how the end users would need to adopt to these changes. or the crictl users

I tried with `crictl version v1.21.0` and `crictl version v1.22.0` and for both I got the same error, 

(mind that this happens for Docker container runtime and it works fine if the container runtime is changes for containerd)

### What did you expect to happen?

I expected  "sudo crictl images" to reuturn list of images insted of error

### How can we reproduce it (as minimally and precisely as possible)?

on minikube head

try these two

$ make./out/minikube delete --all;./out/minikube start --kubernetes-version=v1.23.0-beta.0
$ ./ou/minikube ssh sudo crictl images

$ make./out/minikube delete --all;./out/minikube start --kubernetes-version=v1.23.0-rc.0

$ ./ou/minikube ssh sudo crictl images

### Kubernetes version

v1.23.0-rc.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

Related Issue https://github.com/kubernetes/minikube/issues/13077
Related PR https://github.com/kubernetes/minikube/pull/13073

**Comment by medyagh** [comment] 2021-12-03 20:05
@ehashman any insight on this issue ? I suspect it is related to this PR https://github.com/kubernetes/kubernetes/pull/106501

**Comment by liggitt** [comment] 2021-12-05 23:14
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/106798, fixed in https://github.com/kubernetes/kubernetes/pull/106803 and in 1.23.0-rc.1.

Can you verify this is resolved in rc.1 for you?

**Comment by medyagh** [comment] 2021-12-06 19:21
> I think this is a duplicate of #106798, fixed in #106803 and in 1.23.0-rc.1.
> 
> Can you verify this is resolved in rc.1 for you?

thanks it is a dupe of that issue, will reopen if the new patch hasnt fixed it.

It would be amazing if kubernetes releases get tested with minikube on kubernetes side. it has happend before that minikube integration tests found a failure in kubernetes after release

**Comment by liggitt** [comment] 2021-12-06 19:34
> > I think this is a duplicate of #106798, fixed in #106803 and in 1.23.0-rc.1.
> > Can you verify this is resolved in rc.1 for you?
> 
> thanks it is a dupe of that issue, will reopen if the new patch hasnt fixed it.

Sounds good, thanks.

/close

**Closed** 2021-12-06 19:35 UTC
Labels: kind/bug, sig/node, needs-triage
