### ISSUE TITLE
ClusterRole system:kube-scheduler cannot get extension-apiserver-authentication configmap

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kubernetes#72473] opened 2019-01-02 06:32 UTC
/kind bug
/sig auth
/sig api-machinery

**What happened**:

This is exactly analogous to https://github.com/kubernetes/kubernetes/issues/68986, but for kube-scheduler.

Kubernetes clusters with a self-hosted control plane (i.e. apiserver, controller-manager, scheduler run as pods) may run kube-scheduler with a service account with a ClusterRoleBinding to the default ClusterRole `system:kube-scheduler`, which is defined [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L416).

Starting in v1.12, both kube-scheduler (and kube-controller-manager) make a get request for the `extension-apiserver-authentication` configmap.

```
W0102 03:31:23.167185       1 authentication.go:262] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W0102 03:31:23.167220       1 authentication.go:199] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

For the controller-manager case (#68986), we fixed the `system:kube-controller-manager` ClusterRole to have this permission (#69062). I believe the same change is needed for system:kube-scheduler.

I've only now detected the kube-scheduler issue, since self-hosted clusters weren't previously using a limited service account.

**What you expected to happen**:

ClusterRole system:kube-scheduler should permit getting the extension-apiserver-authentication configmap.

**How to reproduce it (as minimally and precisely as possible)**:

Work on using a service account for the scheduler is in https://github.com/poseidon/typhoon/pull/370

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.1
- Cloud provider or hardware configuration: GCE, DigitalOcean, AWS
- OS (e.g. from /etc/os-release): Container Linux 1911.5.0
- Kernel (e.g. `uname -a`): 4.14.84-coreos
- Install tools: Typhoon

/kind bug

**Comment by dghubble** [comment] 2019-01-02 06:35
Oh, another detail. While in the kube-controller-manager missing permisison case, not being able to get the configmap was fatal, for the kube-scheduler, its merely an error. I still think we ought to have the default ClusterRole match the intended use, but figured I mention that.

**Comment by liggitt** [comment] 2019-01-02 16:57
duplicate of https://github.com/kubernetes/kubernetes/issues/71752

/close

**Closed by liggitt** 2019-01-02 16:57 UTC
Labels: kind/bug, sig/api-machinery, sig/auth
