### ISSUE TITLE
`Jenkins verification` fails with `GitException: Could not checkout`

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#27505] opened 2016-06-16 00:10 UTC
`Jenkins verification` PR test failed with:

From PR https://github.com/kubernetes/kubernetes/pull/27188: 
[log](https://00e9e64baccf2e670b2266325331ecae11a53e0c9824c2752b-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F27188%2Fkubernetes-pull-verify-all%2F192%2Fbuild-log.txt?qk=AD5uMEuvnaDSMV7sief248AtyK5l6uCirtJcaImkUhk6kIY31E9bYeWG7M6LQ67PFkqdynNkJCeh_dro-x1OLY2jjhr3DIz98QmrpIbvhUdEn85k8GL9lzi3SEHH8AWNbTyeWZ97AM3krsl4H5qf1kmS5xD-cCqg1lq7UYDelhU0bcGSv2zB13Ynv2YXOxOk4GCyFAX2k58pY08aPuBmcaTDkbaUFLNnxUxEERW7o26WNTStzddI57g-x7uFqVkfH_3tU38zSRYqpxzptZBmvsekhmk78P0mguSUU0XqlBr3QOFfXywZIKdFYtiNms0Ga-7QrK1TXDb_cnkfhgNWK7E-sTGssWXOtvBJBmgUS7cvTuamMpHNSg0ntl8YP8dr2aqFciPLIEtcrgDTzrUVsrguHCRH9kOx-A7srjHJQUUQaynT0oqrbJlaw7ls3i9Hq2zhkfjMqslePoX3jYnZl2j9CxKJqnCDik3IYP3fhuz2AT4JfSS9Los1uJ8zvJLn_g4ttuEFpd9dhuJW5DbyMR24zlMuD5BgBj4uHeijPrjKDLiRZuBU-zDucnqew-n3V6LgPIBMEx9PUlhzIJGSHy3HSDP7FfFVwzpgJTuojMynV1Bxn9RMxJwsPSjXlZ_Qp8s8HKsyrHEBrc6Nv1j598aCWVF4g5n6hCvbM3qrw5h0PqhYcUAqbmWMefq823CgqjDpoP64QKwrrgpLaGbYrWlMKyWkqJvAT6Rs-cr6kaI6sCdnaNZ6-qM78I-7JnsNChU_hiN4Zps8sxAl0F0ALcSBGtZII46Sre7GD5QAuRlhFGhXFJWd-C6ROegLX3xYYwaERYKOkq2oMSrRMQbugV6wLAf6ZS-tb6lRysT44CfdhC0hKgBcKROSDqnI0Q8235Hu4aI4YWPpuS2l-tFX6v5WdgM63Pi5cw)
```
Seen 47 remote branches
Checking out Revision c0c3f9ce267b27f200e07d4ac72aca07db128b49 (origin/pr/27488/merge)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f c0c3f9ce267b27f200e07d4ac72aca07db128b49 # timeout=20
FATAL: Could not checkout c0c3f9ce267b27f200e07d4ac72aca07db128b49
hudson.plugins.git.GitException: Could not checkout c0c3f9ce267b27f200e07d4ac72aca07db128b49
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1992)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to agent-pr-11(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy64.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1135)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f c0c3f9ce267b27f200e07d4ac72aca07db128b49" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: c0c3f9ce267b27f200e07d4ac72aca07db128b49

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1984)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fejta** [comment] 2016-06-16 03:21
Thanks for reporting! Assigning to @spxtr per @kubernetes/test-infra-maintainers

**Comment by fejta** [comment] 2016-06-16 03:27
Dupe of https://github.com/kubernetes/kubernetes/issues/27462

**Closed by fejta** 2016-06-16 03:27 UTC
Labels: kind/flake, team/test-infra
