### ISSUE TITLE
Proposal: change default behavior of deployment.spec.revisionHistoryLimit to a limit

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#23597] opened 2016-03-29 19:52 UTC
Currently, the default behavior of revisionHistoryLimit of deployments (in other words, if spec.revisionHistoryLimit is not specified) is to keep around all replica sets. This strikes me as unexpected and unreasonable behavior - in normal usage of the deployment object, you will quickly end up with dozens of replica sets with no obvious button or mechanism to clean them up. I think that using deployments in the typical recommended way should not result in unbounded creation of replica sets.

I personally vote for 1 as the default - it gives you basic rollback functionality but doesn't confuse the user by keeping around lots of replica sets and feels the most intuitive to me - but I think any number up to 5 is reasonable.

**Comment by ghodss** [comment] 2016-03-29 19:53
cc @bgrant0607 @kubernetes/sig-config @nikhiljindal @kargakis @janetkuo

**Comment by smarterclayton** [comment] 2016-03-29 20:13
We do three total in Openshift today, but judging by numbers most
people seem to be ok with 2 (haven't heard anyone complain about 3).

**Comment by bgrant0607** [comment] 2016-03-29 20:33
Agree that a bounded default is desirable in the next api version, and I'm looking for user feedback about what value would make sense for the most people. For now, we should document that users should set it, and we should set it in kubectl run.

**Comment by janetkuo** [comment] 2016-03-29 22:30
> For now, we should document that users should set it

This is documented in http://kubernetes.io/docs/user-guide/deployments/#revision-history-limit.

**Comment by JeanMertz** [comment] 2016-04-10 22:05
Personally, I'd be fine with 3:

* the current version, obviously
* one release old, to roll back in case of errors
* the oldest release of the three, as a safe-guard in case we did two breaking releases in a short time-span.

Of course, this is very arbitrary, but having three give me a safer feeling than only having the last two.

**Comment by kargakis** [comment] 2016-04-11 08:38
> Personally, I'd be fine with 3:

The current version is not counted in the limit, so in the case you described 3 should be 2.

**Comment by ApsOps** [comment] 2016-06-10 08:42
I think the default history limit should be set to `2`.

**Comment by pwittrock** [comment] 2016-08-05 17:26
Any number greater than 0 is better than the current infinite.  My big concern here is for automated systems that build and release a dev version on every commit (possibly dozens per-day).  The I doubt the overhead of 2-3 additional RS's is very high.  I would vote for the original + 2-3 in case the user tries to fix a broken release with doing 1-2 additional patches before giving up and rolling back (not as insane as it sounds).

**Comment by smarterclayton** [comment] 2016-08-05 19:54
At most 5, at minimum 2.  How about 3?

**Comment by luispabon** [comment] 2016-09-09 15:48
We're using 3 to good effect :+1:

**Comment by jordandev** [comment] 2016-12-08 23:29
We found that we ended up with hundreds of these when doing automated builds. Makes sense to be a default.

**Comment by ghodss** [comment] 2016-12-16 23:24
Can we make the default 3 in 1.6? @kubernetes/sig-apps-misc

**Comment by justinsb** [comment] 2017-01-04 00:32
So is anyone actually working on this?  I'm happy to do it, but whoever codes the PR chooses the number :-)

**Comment by janetkuo** [comment] 2017-01-04 00:35
We have #34339, but from https://github.com/kubernetes/kubernetes/pull/34339#issuecomment-252382562:

> This is a non-backward-compatible change. We try not to break behavior for beta APIs. The right way to do this is with a new API version, but it would be useful to include more in the new API version than just this change.

We'll accumulate more changes for a new API version for deployments

**Comment by krmayankk** [comment] 2017-01-04 03:20
Fine with default to be 2, which means current plus 2 revisions

**Comment by soltysh** [comment] 2017-01-10 16:33
Addressed in linked PR.

**Comment by jeremyong** [comment] 2017-01-13 23:14
We just discovered this issue as well because I noticed a small bump in memory usage every time we did a deploy. I think this is severe enough to be thought of as a memory leak to be honest and is definitely very unexpected behavior. +1

**Closed** 2017-03-01 16:29 UTC
Labels: area/app-lifecycle, area/workload-api/deployment, priority/important-soon, sig/apps

**Comment by steshaw** [comment] 2017-03-16 07:14
The inactive replicasets are confusing for new users. I wasn't expecting to have any after applying a modified deployment. From this perspective, setting a default limit to 2 or 3 for `.spec.revisionHistoryLimit` would not solve this problem (for new users).

It seems counterintuitive that the [history of deployments are stored in objects that they manage](http://kubernetes.io/docs/user-guide/deployments/#revision-history-limit).

**Comment by kargakis** [comment] 2017-03-16 12:55
@steshaw any suggestions on where might it be better to store it?

**Comment by steshaw** [comment] 2017-03-16 22:19
@kargakis no, not so much, I'm not familiar with the Kubernetes code base. Do you know the reasoning behind it (i.e. deployment histories being stored in replicasets)?
