### ISSUE TITLE
e2e PR builder: Quota 'STATIC_ADDRESSES' exceeded

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20646] opened 2016-02-04 14:56 UTC
Repeat of #17257

We are hitting our static IP quota on the e2e PR builder:

e.g. https://github.com/kubernetes/kubernetes/pull/20642#issuecomment-179868693(edited)

 ```
...
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
 
Attempt 1 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-master-0-master-https].
NAME                          NETWORK          SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
e2e-gce-master-0-master-https e2e-gce-master-0 0.0.0.0/0  tcp:443          e2e-gce-master-0-master
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
 
Attempt 2 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
...
```

**Comment by brendandburns** [comment] 2016-02-04 17:39
assigning to @spxtr to see if this is a leak, or we just are running too many tests.

**Comment by spxtr** [comment] 2016-02-04 19:31
cc @ixdy

**Comment by ixdy** [comment] 2016-02-04 19:52
We're at 191/200 firewall rules, 30/30 forwarding rules, 50/50 target pools... seems pretty leaky.

**Comment by ixdy** [comment] 2016-02-04 19:58
Since I have to restart Jenkins anyway, I'll purge all existing rules at the same time.

**Comment by ixdy** [comment] 2016-02-04 20:08
OK, deleted all forwarding rules, target pools, and leaked firewall and static IP addresses from the kubernetes-jenkins-pull project.

**Comment by ixdy** [comment] 2016-02-04 20:12
#20663 is the likely root cause of the leak. I'm closing this issue, since we should be good now (though a little more cleanup may be needed until #20663 is merged).

**Comment by andyzheng0831** [comment] 2016-02-05 04:56
This happens again: http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26903/console

20:34:37 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
20:34:37  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0

**Comment by nikhiljindal** [comment] 2016-02-05 05:32
This happened again: http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26909/console

```
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:26:43  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:26:43  
21:26:43 Attempt 1 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
21:26:52 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:26:52  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:26:52  
21:26:52 Attempt 2 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
21:26:53 Created [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-master-0-master-https].
21:26:53 NAME                          NETWORK          SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
21:26:53 e2e-gce-master-0-master-https e2e-gce-master-0 0.0.0.0/0  tcp:443          e2e-gce-master-0-master
21:27:06 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:27:06  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:27:06  
21:27:06 Attempt 3 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
21:27:25 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:27:25  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:27:25  
21:27:25 Attempt 4 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
21:27:49 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:27:49  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:27:49  
21:27:49 Attempt 5 failed to create static ip e2e-gce-master-0-master-ip. Retrying.
21:28:17 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
21:28:17  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
21:28:17  
21:28:17 Failed to create static ip e2e-gce-master-0-master-ip 
```
Am reopening the issue

**Comment by spxtr** [comment] 2016-02-05 17:52
#20663 went in shortly after this was reopened.

**Comment by ixdy** [comment] 2016-02-05 20:43
@thockin cleaned up the project again last night, so hopefully clear now. I'll double-check the project as well.

**Comment by thockin** [comment] 2016-02-05 23:34
I'm keeping an eye on it in the background, but it's unclear to me just how
aggressive I can be in manually  cleaning.  I killed at least one build
today.

**Comment by ixdy** [comment] 2016-02-06 00:13
I deleted a few additional firewall/forwarding/targetpools from overnight. Hopefully clear now.

**Comment by jingxu97** [comment] 2016-10-11 20:25
Hit this problem again in one of my tests run https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/34557/kubernetes-pull-build-test-e2e-gce/62668/build-log.txt
 
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 40.0

**Comment by spxtr** [comment] 2016-10-11 20:31
Yeah, looking at it now. Not just static IPs.

**Comment by spxtr** [comment] 2016-10-17 17:20
It's cleaned up and we've made steps to keep it from happening again. Please open a new issue if this reoccurs.

**Closed by spxtr** 2016-10-17 17:20 UTC
Labels: kind/flake
