### ISSUE TITLE
Secure access to private images on nodes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#21562] opened 2016-02-19 17:47 UTC
Discussion started on #21182.

If an image from a private registry has already been pulled onto a node, is there anything that prevents a pod without access to that registry from referencing and accessing the image?

cc @deads2k @dchen1107

**Comment by smarterclayton** [comment] 2016-04-06 15:03
This is a dupe of #18787

**Comment by liggitt** [comment] 2017-02-12 05:01
Closing as dupe

**Closed by liggitt** 2017-02-12 05:01 UTC
Labels: sig/auth, sig/node
