### ISSUE TITLE
kubectl edit brokenness editing volumeMounts (list of struct)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#34800] opened 2016-10-14 05:59 UTC
Start with:

```        
       volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-456                                                                                                                                 
          name: vol 
          subPath: d456
```

Edit to:

```
        volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-d2
          name: vol
          subPath: d2     
```

Read back what happened:

```
        volumeMounts:
        - mountPath: /vol-d2
          name: vol 
          subPath: d2
        - mountPath: /vol-456
          name: vol 
          subPath: d456
```

It synthesized a COMPLETELY WRONG result.  At this point, I can not, in good conscience, advocate using kubectl edit.

Can I please have `kubectl edit --replace` that doesn't go through patch brokenness.  Or better, make that default for 1.5 and make `kubectl edit --patch`   be the broken (but eventually fixed) path.

**Comment by wernight** [comment] 2016-10-14 09:17
Just wondering, why would on want to use `--patch` over `--replace`? Is that in case of concurrent edits?

**Comment by pwittrock** [comment] 2016-10-15 20:22
Can you get the desired result with a PATCH call?  I what are the merge keys used for VolumeMounts?

**Comment by ymqytw** [comment] 2016-10-15 21:25
I will take a close look next Monday.

**Comment by ymqytw** [comment] 2016-10-17 16:45
The root cause is that PATCH doesn't support multiple maps share the same key in one single list. In this case, 2 items share key `vol` in list `volumeMounts`.
When applying a patch to a list of maps on the API server, it needs a merge key to find which item to apply to. In this case, the patch is applied to the first item with key `vol` that turns out to be wrong.

**Comment by pwittrock** [comment] 2016-10-17 18:31
I agree with Tim.  PATCH is really broken and I am not certain there is any benefit in using patch with edit since the use case is very different than with apply.  I think we would actually want the optimistic locking failures to be surfaced to the user instead of ignore them since the user expects to write the complete state with edit.  Lets switch edit to use Replace and add this to the list of issues on PATCH

**Comment by pwittrock** [comment] 2016-10-17 20:15
@ymqytw Is the problem that the merge key is 'vol' and there are multiple items with the same merge key in the list?

**Comment by ymqytw** [comment] 2016-10-17 20:39
>Is the problem that the merge key is 'vol' and there are multiple items with the same merge key in the list?

@pwittrock Yes. Patch will apply to the first item that matches the merge key.

**Comment by pwittrock** [comment] 2016-10-17 20:49
@saad-ali @caesarxuchao This seems like an issue with defining the merge key for the VolumeMounts resource since the merge key must be unique within the list.  Is that correct?

**Comment by caesarxuchao** [comment] 2016-10-17 21:33
Right, the merge key needs to be unique. Maybe change to use `MountPath` as merge key? It looks to be unique. But it will be a breaking change, I guess the server regards the patch generated by old clients as invalid.

**Comment by pwittrock** [comment] 2016-10-17 21:46
@thockin Patch definitely has its share of issues.  It sounds like the one you encountered here is actually an issue with how VolumeMount is implemented.  I still think there is little value with using patch for edit generally beyond catching these sorts of issues.

**Comment by thockin** [comment] 2016-10-18 03:35
Change the key to mountPath is better.  I'm not sure it's guaranteed
unique, but at least duplicate values there are not useful.

I can send a PR for that.

I 100% agree that `edit` == `replace`.  We should just fix that.  It's
human-centric - patch is too clever.

In this particular case, I'd rather see the whole list replaced, rather
than an attempted patch, anyway.

**Comment by saad-ali** [comment] 2016-10-18 04:10
> Change the key to mountPath is better.  I'm not sure it's guaranteed
unique, but at least duplicate values there are not useful.
>
> I can send a PR for that.

Any backwards compatibility concerns?

> But it will be a breaking change, I guess the server regards the patch generated by old clients as invalid.

I think this should be fine. CC @kubernetes/sig-storage

**Comment by pwittrock** [comment] 2016-10-18 04:40
File #35016 for the `kubectl edit` to use "Replace" instead of "Patch".  Re-assigned to @thockin for the VolumeMounts changes.  If there are other ux specific items on this feel free to reassign back to myself and @ymqytw .

**Comment by kargakis** [comment] 2016-10-18 17:30
@kubernetes/kubectl

**Closed** 2016-10-19 07:21 UTC
Labels: area/storage, team/cluster

**Comment by ghodss** [comment] 2016-10-19 17:44
Just out of curiosity, why is name allowed to be non-unique in VolumeMounts? If it can't be used to refer uniquely to a mount, why does the field even exist?

**Comment by thockin** [comment] 2016-10-19 18:02
It is the name of the volume.  I can mount the same volume in more than one
place, especially true with subPath.
