### ISSUE TITLE
[flake] certificates controller unit test flake

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#46374] opened 2017-05-24 18:48 UTC
Seen in https://github.com/kubernetes/kubernetes/pull/45932

```
go test k8s.io/kubernetes/pkg/controller/certificates -o certificates.test
go get golang.org/x/tools/cmd/stress
stress ./certificates.test -test.run TestCertificateController$
```

@mikedanese happy to send a fix but didn't know if this might have been address with your current refactors.

Output:

```
103 runs so far, 0 failures

/tmp/go-stress671140097
--- FAIL: TestCertificateController (0.00s)
	certificate_controller_test.go:73: expected 3 actions
	certificate_controller_test.go:79: unexpected action: testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"certificates.k8s.io", Version:"v1beta1", Resource:"certificatesigningrequests"}, Subresource:"approval"}, Object:(*v1beta1.CertificateSigningRequest)(0xc4203d41c0)}
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 10 [running]:
testing.tRunner.func1(0xc4206152b0)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x194a260, 0x26ac670)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/certificates.TestCertificateController(0xc4206152b0)
	/home/eric/src/k8s.io/kubernetes/pkg/controller/certificates/certificate_controller_test.go:81 +0x675
testing.tRunner(0xc4206152b0, 0x1b91968)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca


ERROR: exit status 2


/tmp/go-stress734739564
--- FAIL: TestCertificateController (0.00s)
	certificate_controller_test.go:73: expected 3 actions
	certificate_controller_test.go:79: unexpected action: testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"certificates.k8s.io", Version:"v1beta1", Resource:"certificatesigningrequests"}, Subresource:"approval"}, Object:(*v1beta1.CertificateSigningRequest)(0xc4205681c0)}
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 11 [running]:
testing.tRunner.func1(0xc4204b8820)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x194a260, 0x26ac670)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/certificates.TestCertificateController(0xc4204b8820)
	/home/eric/src/k8s.io/kubernetes/pkg/controller/certificates/certificate_controller_test.go:81 +0x675
testing.tRunner(0xc4204b8820, 0x1b91968)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca


ERROR: exit status 2

204 runs so far, 2 failures
```

**Comment by mikedanese** [comment] 2017-05-24 19:58
This looks new. I'd happily review a fix. Thanks.

**Comment by ncdc** [comment] 2017-05-24 20:56
Dupe of #46365

**Comment by mikedanese** [comment] 2017-05-24 21:13
https://github.com/kubernetes/kubernetes/pull/46383

**Closed** 2017-05-24 21:13 UTC
Labels: kind/flake, sig/auth
