### ISSUE TITLE
Failure cluster [cefe0d5b...] `[sig-cli] Kubectl Port forwarding with a pod being removed should stop port-forwarding`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#128742] opened 2024-11-11 14:36 UTC
##### Error text:
```
[FAILED] Expected an error to have occurred.  Got:
    <nil>: nil
In [It] at: k8s.io/kubernetes/test/e2e/kubectl/portforward.go:613 @ 11/10/24 22:47:31.95

```
#### Recent failures:
[11/11/2024, 2:00:45 AM ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-containerd-e2e-ubuntu-gce/1855868045222744064)
[11/11/2024, 12:35:57 AM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1855846905636982784)
[11/10/2024, 6:00:50 PM ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-containerd-e2e-ubuntu-gce/1855747247937949696)
[11/10/2024, 5:25:57 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1855738691507458048)
[11/10/2024, 5:23:18 PM ci-cloud-provider-aws-e2e-kubetest2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cloud-provider-aws-e2e-kubetest2/1855737684882886656)

/kind failing-test

/sig cli

**Comment by liggitt** [comment] 2024-11-12 22:35
Is this a pre-existing test that went flaky when https://github.com/kubernetes/kubernetes/pull/128681 merged, or a new test added by https://github.com/kubernetes/kubernetes/pull/128681 that is flaky?

**Comment by liggitt** [comment] 2024-11-12 22:36
Adding to milestone to root-cause and either deflake or rollback https://github.com/kubernetes/kubernetes/pull/128681 before 1.32 release

**Comment by soltysh** [comment] 2024-11-14 15:48
> @soltysh there is some correlation between these test failing and this PR merged #128681

> Is this a pre-existing test that went flaky when #128681 merged, or a new test added by #128681 that is flaky?

Yes, it's a recent addition in that PR Antonio mentioned. I'm looking why it might be flaking... 

/assign

**Comment by soltysh** [comment] 2024-11-14 15:55
I see what the problem is, after we create port-forward, we're POST-ing to the forwarded endpoint. After the pod to which we're forwarding requests gets removed we're waiting either 3minutes (`DefaultPodDeletionTimeout`) or for an error from POST request. Based on the timing:
```
STEP: Wait for client being interrupted - k8s.io/kubernetes/test/e2e/kubectl/portforward.go:606 @ 11/11/24 07:10:40.136
STEP: Check the client error - k8s.io/kubernetes/test/e2e/kubectl/portforward.go:612 @ 11/11/24 07:13:40.136
```
it's clear we're never getting the error from POST, but we're hitting that timeout. The simplest fix will be to add a timeout to that POST request, since it apparently hangs w/o one. I'll open a PR in a bit.

**Closed** 2024-11-15 18:02 UTC
Labels: sig/cli, kind/failing-test, needs-triage
