### ISSUE TITLE
k8s periodics-kubernetes-bazel unit test failing

### ISSUE THREAD

**Issue by ranand20** [kubernetes/kubernetes#95228] opened 2020-10-01 10:31 UTC
**Which jobs are flaking**:
periodics-kubernetes-bazel-test

**Which test(s) are flaking**:
 TestDevicePluginReRegistrationProbeMode (2.02s)

**Testgrid link**:

**Reason for failure**:
Unit test is failing for pkg/kubelet/cm/devicemanager/TestDevicePluginReRegistrationProbeMode with below error.
~~~
"RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin514553038/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration".
~~~
**Anything else we need to know**:
Test is flaking, so I have generated the same scenario be running the below command. 
~~~
$go test -race -c ./pkg/kubelet/cm/devicemanager
$ stress ./devicemanager.test -test.run TestDevicePluginReRegistrationProbeMode
15 runs so far, 0 failures
32 runs so far, 0 failures
48 runs so far, 0 failures
69 runs so far, 0 failures
86 runs so far, 0 failures
102 runs so far, 0 failures
124 runs so far, 0 failures

/tmp/go-stress-20200930T093216-980141031
I0930 09:32:49.410528   12932 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
W0930 09:32:49.410795   12932 manager.go:596] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I0930 09:32:49.412924   12932 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0930 09:32:49.419288   12932 device_plugin_stub.go:153] GetInfo
E0930 09:32:49.420084   12932 goroutinemap.go:150] Operation for "/tmp/device_plugin514553038/server.sock" failed. No retries permitted until 2020-09-30 09:32:49.919924052 +0000 UTC m=+0.574491769 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin514553038/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0930 09:32:49.420914   12932 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin514553038/device-plugin.sock
I0930 09:32:49.423253   12932 device_plugin_stub.go:227] ListAndWatch
I0930 09:32:49.443396   12932 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin514553038/device-plugin.sock.new
E0930 09:32:50.416144   12932 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
I0930 09:32:50.418809   12932 device_plugin_stub.go:153] GetInfo
E0930 09:32:50.418975   12932 goroutinemap.go:150] Operation for "/tmp/device_plugin514553038/server.sock" failed. No retries permitted until 2020-09-30 09:32:51.418836407 +0000 UTC m=+2.073404099 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin514553038/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0930 09:32:50.421939   12932 device_plugin_stub.go:227] ListAndWatch
I0930 09:32:50.436384   12932 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin514553038/device-plu
…
141 runs so far, 1 failures
~~~

**Comment by liggitt** [comment] 2020-10-04 02:26
is this a duplicate of https://github.com/kubernetes/kubernetes/issues/94528 and https://github.com/kubernetes/kubernetes/issues/94547 ?

**Closed** 2020-10-07 08:30 UTC
Labels: kind/flake, needs-triage, sig/node, triage/duplicate
