### ISSUE TITLE
Pods are incorrectly rejected after kubelet restart due to NUMA and node label changes

### ISSUE THREAD

**Issue by davshen** [kubernetes/kubernetes#123859] opened 2024-03-11 10:08 UTC
### What happened?

1.NUMA causing rejection:
Node configuration: --cpu-manager-policy=static --memory-manager-policy=Static --topology-manager-policy=single-numa-node
InitContainer and main container's NUMA are calculated one by one.
CPU affinity is present, but in reality, the NUMA alignment of the InitContainer might not match the resource requirements of the main container.
Restarting kubelet leads to Pod rejection.
![WX20240311-175733@2x](https://github.com/kubernetes/kubernetes/assets/46776140/4ca5624f-3caa-4ba3-9518-6fb5148fe376)

2.Node Label change causing rejection:
Node has a label hpc=true, and the Pod has nodeAffinity based on this label.
Due to specific reasons, the label is removed.
Restarting kubelet results in Pod rejection with the error message: NodeAffinity failed

### What did you expect to happen?

Regardless of the situation, kubelet should not reject Pods that are running and were created before the kubelet restart.

### How can we reproduce it (as minimally and precisely as possible)?

I mentioned the steps in the 'what happened' section, and by following those steps, the issue can be reproduced consistently, 100% of the time.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux mjq-k8stestarsenalmaster-1 5.16.20-1.el7.x86_64 #3 SMP PREEMPT Thu Aug 18 13:53:10 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.16 31aa4358a36870b21a992d3ad2bef29e1d693bec
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ffromani** [comment] 2024-03-11 10:18
part 1 of this issue seems to be a dupe of https://github.com/kubernetes/kubernetes/issues/123816

**Comment by ffromani** [comment] 2024-03-11 10:20
Does this happen with a kubelet restart (just the kubelet) or with a full node reboot?

**Comment by AllenXu93** [comment] 2024-03-11 11:47
> Does this happen with a kubelet restart (just the kubelet) or with a full node reboot?

Yes, it cab be reproduce by:
1. Node has N NUMA, every NUMA has 40 Core CPU
2. Pod A created with 1 Core init-container, and 40 Core app container, and it can use all NUMA 0.
3. Pod B created with 2 Core, because of NUMA 0 CPU is fully used by Pod A, Pod B got CPU in NUMA 1.
4. Delete Pod A
5. ReCreate Pod A, so Pod A's created timestamp is greater than Pod B. Pod A still use NUMA 0.
6. Delete checkpoint
7. Restart Kubelet

After restart kubelet, kubelet will admit all Pods in node, sort by createdTime.
1. Pod B is allocate first, so it get 2 Core in  NUMA 0.
2. Then Pod A init-container, it get 1 Core in NUMA 0.
3. Pod A app-container will failed (NUMA 0 CPU not enough; NUMA 1 or other NUMA node is passed because of reuse CPU)

**Comment by AnishShah** [comment] 2024-03-13 17:30
part 1 is a duplicate of #123816. Please file a separate bug for part 2

**Closed** 2024-03-13 18:03 UTC
Labels: kind/bug, sig/node, needs-triage

**Comment by davshen** [comment] 2024-03-16 09:12
> moving to point 2 above, it would be nice to learn why the node label changes. I wouldn't expect to node labels to be dropped across kubelet restarts (or node reboots) without explicit action like explicit delete.

The reason why this label changed is because the operation and maintenance engineer organized the node label, such as hpc=true, and removed this label. When a pod is compatible with this label, restarting the node kubelet will cause the pod to be rebuilt. This actually shouldn’t be the case. It will affect the normal operation of the business.

**Comment by davshen** [comment] 2024-03-16 09:14
> part 1 is a duplicate of #123816. Please file a separate bug for part 2

In fact, the problem I want to solve when raising this PR is that no matter what the circumstances, pods that are running normally should not be rejected. Different problem than #123816 wants to solve.

**Comment by ffromani** [comment] 2024-03-16 10:49
> > moving to point 2 above, it would be nice to learn why the node label changes. I wouldn't expect to node labels to be dropped across kubelet restarts (or node reboots) without explicit action like explicit delete.
> 
> The reason why this label changed is because the operation and maintenance engineer organized the node label, such as hpc=true, and removed this label. When a pod is compatible with this label, restarting the node kubelet will cause the pod to be rebuilt. This actually shouldn’t be the case. It will affect the normal operation of the business.

The thing is, pod assignment is not sticky. Meaning. Once a scheduler decided which node should run a pod, this decision is not kept forever, and when a new scheduling attempt is done for whatever reason, the cluster state is re-evaluated.
A kubelet restart does the same: admission is re-attempted when kubelet restarts and it re-evaluates the pods which should be running on a node (as stored in the cluster state), and some conditions may cause admission failure.

That said, it's also true that despite this general condition, there's clearly an emerging consensus/sentiment about the fact that a kubelet restart should not affect the running workload. We "recently" discussed a [similar case](https://github.com/kubernetes/kubernetes/pull/118635).

So the case is here, but we need a separate issue and quite likely we will need also a larger scope conversation at SIG level and to move the topic to a different issue

**Comment by ffromani** [comment] 2024-03-16 10:51
> > part 1 is a duplicate of #123816. Please file a separate bug for part 2
> 
> In fact, the problem I want to solve when raising this PR is that no matter what the circumstances, pods that are running normally should not be rejected. Different problem than #123816 wants to solve.

OK, this is a fair point but we will need a refocusing of the issue. Filing a new issue about the general ask that restarting a kubelet should not cause any disruption to the running workload (which likely will mean skip admission of running pods, but let's not run ahead of ourselves) and backlink to this issue is probably the best way forward still.

Is much likely better to raise the most general issue ("restarting a kubelet should never affect the running workload") and then link specific examples than start with examples and then generalize.
