### ISSUE TITLE
Garbage collector should orphan RS created by deployment when deleteOptions.OrphanDependents is true

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#42639] opened 2017-03-07 12:40 UTC
Instead, there are no RSs present.

from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42593/pull-kubernetes-e2e-gce-etcd3/21127/ 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:471
Mar  6 13:31:39.687: remaining rs post mortem: &v1beta1.ReplicaSetList{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"/apis/extensions/v1beta1/namespaces/e2e-tests-gc-bkl67/replicasets", ResourceVersion:"10566"}, Items:[]v1beta1.ReplicaSet(nil)}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:451
```

@kubernetes/sig-api-machinery-misc

**Comment by caesarxuchao** [comment] 2017-03-10 00:41
According to the log of the first linked failure, and a local reproduction, the RS was not orphaned because the deployment controller-er adopted the RS that was just orphaned by the garbage collector.

To prevent the race, the deployment controller should get the latest deployment from API server, instead of checking its local cache, before [adopting](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_ref_manager.go#L310) the RS. This can completely prevent re-adoption. Because if the deployment tries to adopt the RS, it means the RS lacks the controllerRef, which means the garbage collector has orphaned the RS, which means the deletionTimestamp must have already been set, so the proposed check will prevent the re-adoption. (but there still could be race for new-adoption)

(We had considered such race when designing GC. We proposed to use ObservedGeneration to sync the deployment controller and the garbage collector. See the 6th point in https://github.com/kubernetes/kubernetes/issues/26120. This hasn't been implemented. This will prevent both re-adoption and new-adoption.)

**Comment by caesarxuchao** [comment] 2017-03-10 01:37
@janetkuo @enisoc could you help with the fix, since you are making controllerRef related changes? Also the fix should be applied to all controllers, not just the deployment controller.

**Comment by janetkuo** [comment] 2017-03-10 01:51
This sounds like a serious problem that needs to be fixed in 1.6.

**Comment by liggitt** [comment] 2017-03-10 13:52
Should we roll back the controller ref changes for 1.6? The observed generation feature seems like a significant change at this point in the release?

**Comment by deads2k** [comment] 2017-03-10 14:01
> Should we roll back the controller ref changes for 1.6? The observed generation feature seems like a significant change at this point in the release?

+1

We could establish the controller ref links for GC, but skip the selection changes.

**Comment by kargakis** [comment] 2017-03-10 14:16
> The observed generation feature seems like a significant change at this point in the release?

If it's not a big fix, I would take it. The GC not synchronizing with the rest of the controllers seems like a bigger issue...

**Comment by kargakis** [comment] 2017-03-10 14:28
By the way, wrt to Deployment owner references, the feature was added long before code freeze in https://github.com/kubernetes/kubernetes/pull/35676 so reverting https://github.com/kubernetes/kubernetes/pull/42175 won't probably fix this?

**Comment by enisoc** [comment] 2017-03-10 16:57
If it's true that this is caused by a cached version of the controller that doesn't see the DeletionTimestamp yet, then I agree with @kargakis that this problem predates #42175. I would also expect this to affect RC/RS as well, since they have been implementing this behavior since v1.5. Indeed, the equivalent test for RC seems to also be flaky and this may be a contributing cause: https://github.com/kubernetes/kubernetes/issues/42086

**Comment by enisoc** [comment] 2017-03-10 19:18
I discussed this with @caesarxuchao and @janetkuo. They confirmed that this is a longstanding flake, ever since ControllerRef support was added to Deployment in December (#35676), and also affects RC/RS which supported ControllerRef since v1.5.

The [long-term fix](https://github.com/kubernetes/kubernetes/issues/26120) is to coordinate between the GC and controllers via observed generation, but that is too involved to fix right now because controllers don't increment observed generation yet.

Instead, I plan to pursue the fix that @caesarxuchao [proposed above](https://github.com/kubernetes/kubernetes/issues/42639#issuecomment-285535368): After listing all the candidate objects (RSes in this case), but before deciding whether to adopt, re-fetch your own controller object (bypassing the cache) just to check for DeletionTimestamp.

**Comment by kargakis** [comment] 2017-03-10 20:54
> controllers may not all coordinate updates to ObservedGeneration with their sync() loop.

FWIW, all the workload controllers respect observedGeneration.

**Comment by ethernetdan** [comment] 2017-03-14 22:46
@enisoc @deads2k @kargakis is this release blocking for 1.6?

**Comment by caesarxuchao** [comment] 2017-03-14 23:14
Yes, it is.

**Comment by deads2k** [comment] 2017-03-15 18:44
This is a problem in the controllers and they need to ensure that when they set an ownerref, the owner actually exists.

**Closed** 2017-03-20 08:30 UTC
Labels: kind/flake, release-blocker, sig/apps
