### ISSUE TITLE
CPUs allocated for guaranteed QoS pod are not released when the Pods are deleted 

### ISSUE THREAD

**Issue by jitendra319** [kubernetes/kubernetes#109562] opened 2022-04-20 09:17 UTC
### What happened?

After deleting the qos-pod, qos-pod entries is not getting deleted from "file /var/lib/kubelet/cpu_manager_state" 
The same issue is also observed when doing scale-in and scale-down of qos-pod

in case of two or more worker node, there is possibility that, issue will be seen on one worker only

 sudo cat /var/lib/kubelet/cpu_manager_state | jq
{
  "policyName": "static",
  "defaultCpuSet": "0-2,4-7",
  "entries": {
    "499a37ae-89a8-4e73-a090-f86ea22a9f4c": {
      "cpu-qos2": "3"
    }
  },
  "checksum": 1515081781

### What did you expect to happen?

CPUs allocated for guaranteed QoS pod should be released when the Pods are deleted 

### How can we reproduce it (as minimally and precisely as possible)?

Create qos-pod with 1 Guranteed cpu,  
Check Banned CPU for pod using - sudo cat /var/lib/kubelet/cpu_manager_state | jq
Delete the Qos-pod
Check  Banned CPU , we can see the CPU is still reserved by the pod which got deleted 

### Anything else we need to know?

[log_on_pool1-ni2nhd1r.txt](https://github.com/kubernetes/kubernetes/files/8520085/log_on_pool1-ni2nhd1r.txt)

kubelet log during issue reproduction

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:38:28Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:27:59Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

openstack

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lxtywypc** [comment] 2022-04-21 08:44
This looks like https://github.com/kubernetes/kubernetes/issues/107074

**Comment by fromanirh** [comment] 2022-04-27 16:23
> This looks like #107074

that's a good catch. This can be related indeed.
In general, cpus are released after containers terminated periodically (please check the cpumanager reconcile period option), or when a new container is admitted.
IOW, it is expected (and not a bug) that the data in the state file is "stale" for some amount of time after the relevant containers terminate. I think in general inspecting the content of the cpu manager state file is plenty of pitfalls, so I don't recommend this as primary debug technique.
@jitendra319 did you observe other misbehaviours? For example, exclusive cpus not correctly assigned? Or this issue was filed only after checking the content of the state file?

**Comment by klueska** [comment] 2022-04-27 17:08
Seems the same as far as i can tell, I would close this as a duplicate.

**Comment by fromanirh** [comment] 2022-04-27 17:12
/close
treating as dupe of https://github.com/kubernetes/kubernetes/issues/107074

**Closed** 2022-04-27 17:12 UTC
Labels: kind/bug, sig/node, triage/accepted

**Comment by jitendra319** [comment] 2022-04-28 06:00
> > This looks like #107074
> 
> that's a good catch. This can be related indeed. In general, cpus are released after containers terminated periodically (please check the cpumanager reconcile period option), or when a new container is admitted. IOW, it is expected (and not a bug) that the data in the state file is "stale" for some amount of time after the relevant containers terminate. I think in general inspecting the content of the cpu manager state file is plenty of pitfalls, so I don't recommend this as primary debug technique. @jitendra319 did you observe other misbehaviours? For example, exclusive cpus not correctly assigned? Or this issue was filed only after checking the content of the state file?

This issue was filed after checking the content of the state file, because as a side effect it was affecting  IRQBALANCE_BANNED_CPUS in /etc/sysconfig/irqbalance

**Comment by klueska** [comment] 2022-04-28 06:31
Im not sure what IRQBALANCE_BANNED_CPUS is, but in principal, nothing should rely on the state file of the CPU manager. It has no API guarantees and is completely internal to the CPU manager implementation. It’s location on the filesystem and it’s format are subject to change at any time without warning.

**Comment by fromanirh** [comment] 2022-04-28 06:43
> Im not sure how IRQBALANCE_BANNED_CPUS is affected, but in principal, nothing should rely on the state file of the CPU manager. It has no API guarantees and is completely internal to the CPU manager implementation. It’s location on the filesystem and it’s format are subject to change at any time without warning.

I completely agree with Kevin. Peeking at the cpumanager state file is almost always a bad idea.
Some flows or applications external to the kubelet may want to know which exclusive CPUs a container got, for example to perform extra system tunings. All of this should probably better integrated in the platform somehow, but still these use cases exists today.

To learn about allocation of exclusive CPUs to container, a better approach would be the podresources API, which is node-local (no rounditrip to the APIserver needed). https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-list At very least, this is a supported API with well defined semantics and compatibility guarantees.
