### ISSUE TITLE
Test docker nightly build against GCI image and Kubernetes head

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25215] opened 2016-05-05 19:22 UTC
We have ~20 test jenkins builds are running against various GCI image, and Kubernetes builds already. @wonderfly kindly agreed to add another one to test docker nightly build for us. This is relatively easy comparing to today's debian-based containerVM image, and less error-prone. 

@liangchenye This is the first step to unblock the work of automating docker validation process which you have been working on. Beyond this, you need to:
- Introduce node e2e test suite for automating docker validation. You can  re-use the cloud_init config introduced by @wonderfly 
- Include your runtime conformance test suites to the newly introduced docker validation suite.
- Convert our current docker performance tests written by @Random-Liu to the new test suite.
- Add docker restart / recovery, resource tracking tests. 

After the first suite is done, we can expand the test suite to cover other os distro easily.

**Comment by dchen1107** [comment] 2016-05-05 21:55
cc/ @timstclair 

@wonderfly suggested an alternative approach, and will provide the detail information here.

**Comment by wonderfly** [comment] 2016-05-05 22:23
We definitely want to automate the docker validation tests that you guys wrote/will write, and run them on a continuous basis. We, GCI, internally have been doing continuous testing (at a much smaller scale) with docker HEAD, but it turned out that docker HEAD is rather flaky that made our test results more like noise. So instead, @dchen1107 suggested that we could do it with docker's prereleases (RC releases). I think that makes sense: we avoid the noise from docker's HEAD flakiness, yet still get a chance to find bugs and upstream fixes before its official release.

As of the implementation on GCI, docker is built in to our images. We don't do runtime download/installation as other distros do. But we have an experimental nightly builder that builds a GCI image with the latest docker release. I think we just need to update it to use docker prereleases, and supply the images it builds to the continuous docker validations tests. It is a little non-intuitive in the sense that to test a new docker version we'd have to build a new image, but it's essentially the same thing as requested in comment#1: a combination of GCI HEAD build, k8s HEAD build, and latest docker prerelease.

**Comment by Random-Liu** [comment] 2016-05-05 22:28
@wonderfly SGTM! :)

**Comment by wonderfly** [comment] 2016-05-28 03:00
Sorry this took a little longer. The GCI image side change was completed a week ago. I had to work on something else so didn't get a chance to sort out the k8s side change yet. I expect to send it out for review early next week.

**Comment by wonderfly** [comment] 2016-06-15 22:34
#26813 is out to fix this. It has been in the submit queue for a week and I have no idea when it'll get merged.

**Comment by wonderfly** [comment] 2016-06-17 17:37
The PR is marked as P3 so it's getting pushed back over and over again. Can anybody with the authority adjust its priority? Or if it's not super urgent then this issue should be a P3 too. :smile:

**Comment by wonderfly** [comment] 2016-06-28 16:51
It took a few iterations but we just had our first green docker validation build (checkout the internal Jenkins instance), and you can see the GCI image version, k8s commit number, and docker version (1.12.0-rc2), that it was run against.

So I think my share of the issue is done. I will continue helping you guys for questions, but this should be assigned to someone else now. @dchen1107 I don't have the permission to edit assignee. Can you?

**Comment by Random-Liu** [comment] 2016-06-28 17:20
@wonderfly Thanks a lot! I've assigned myself. And will leave unassign to @dchen1107. :)

**Comment by Random-Liu** [comment] 2016-09-06 21:05
@dchen1107 Can we close this one?

**Comment by wonderfly** [comment] 2016-11-03 17:15
Let's close this now?

**Closed** 2018-02-16 12:59 UTC
Labels: area/os/gci, area/test, lifecycle/rotten, priority/important-soon, sig/node
