### ISSUE TITLE
DaemonSet should allow for a RestartPolicy of OnFailure

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#17182] opened 2015-11-12 22:49 UTC
There are situations where we would like to run a container on each node, but the container is not meant to execute indefinitely, so that a `RestartPolicy` of `Always` is not desirable.  Consider a container that queries the AWS metadata service and applies appropriate labels to the node (e.g. region, zone, security groups, etc).  Currently this can be accomplished with static pods, but K8s recommends against end users making use of static pods.  To enable migration away from static pods for such use cases `DaemonSet` should allow for a `RestartPolicy` of `OnFailure`.

**Comment by kargakis** [comment] 2017-06-10 16:32
Closing as a dupe of https://github.com/kubernetes/kubernetes/issues/36601

**Closed by kargakis** 2017-06-10 16:32 UTC
Labels: needs-sig, priority/backlog, team/control-plane (deprecated - do not use)
