### ISSUE TITLE
[kubectl] abbrev "dpl" for deployments

### ISSUE THREAD

**Issue by Frostman** [kubernetes/kubernetes#24083] opened 2016-04-10 13:18 UTC
Most of the objects have the abbreviation (short form) in kubectl, for ex. rc == replicationcontroller. It'll be useful to have an abbrev for "deployments" as well and I'm proposing to use "dpl" for it.

**Comment by AdoHe** [comment] 2016-04-10 15:00
@kubernetes/kubectl

**Comment by bgrant0607** [comment] 2016-04-19 04:00
Dupe of lots of issues.

**Closed by bgrant0607** 2016-04-19 04:00 UTC
Labels: team/ux
