### ISSUE TITLE
Autoscaling cluster causes havoc on HPA by not starting heapster

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#34126] opened 2016-10-05 17:35 UTC
BUG REPORT:

Severity: Cluster becomes unusable unless an administrator intervenes and removes pods.

In an autoscaling scenario with the HPA and an instance autoscaler like GCE instance groups, scaling down the cluster causes trouble due to two issues:
1) Pending pods are not being terminated by the HPA due to (seemingly) incorrect usage calculations
2) Removing nodes from the cluster leads to a kill of Heapster, which then won't start again due to insufficient CPU resources, which then blocks removing pods by the HPA forever, effectively preventing any further scaling of the cluster.

**Environment information:**
Kubernetes version: 1.3.5
Environment: GCE
Servers 8 CPUs, 30GB Ram, 150GB disk

**Scaling settings:**
- Servers 8 CPUs
- Servers scale at 60% CPU (up or down), delay of 300s
- HPA scales at 51% (yes, it is a poor pod), scaling of 2 to a max of 64 pods.
- Pods are defined with a request and limit of 1500mc, so no flexibility there (not possible else the behaviour of the pods is not as it should be)

**Description of what happens:**
1) Server load increases from 25% to 60%, pods scale up fast to prevent backlog in the pods (pods are processing nginx logs with logstash in sync with the incoming data) (multi container pod: Nginx is doing virutally nothing in the container, logstash is running near 100%: On average the scaling point is 50%)
2) HPA explodes to 64 pods & nodes are scaled in to cope with the load: Nodes level out at 6 nodes for the given test.
3) Load per pod is decreased to <50% due to the scaling of nodes and pods
4) Pending pods are not being removed, a high number of them stays present
5) The load is decreased with as result that the nodes start to scale back
6) Pending pods are still pending, HPA is not scaling back pods.
7) Node with heapster is killed by the node scaler.
8) Due to now lack of CPU heapster does not start anymore, the HPA does not get information anymore and will not scale down pods.

**Proposed solution:**
A) Change Heapster request CPU to a low value so it will always start
B) Add new properties to the HPA:
- Max pending pods: This prevents a bunch of pods from being started while they can not be scheduled in the cluster anyway.
- Max time a pod is allowed to stay pending: Makes the autoscaler a bit more independent from heapster
- Let pods report to the HPA instead of to heapster what their load is, removing the heapster requirement completely and making the HPAs much more flexible. Heapster is then only for graphing purposes.

**Comment by DirectXMan12** [comment] 2016-12-15 16:30
cc @kubernetes/sig-autoscaling @kubernetes/sig-instrumentation

**Comment by davidopp** [comment] 2016-12-15 21:59
Is the "instance autoscaler" being referred to here the GCE cluster autoscaler (which shouldn't be used) or the GKE cluster autoscaler?

Also we fixed the "heapster can't schedule" problem in 1.4 with the "rescheduler"

**Comment by nvnobelen** [comment] 2016-12-30 18:46
The instance autoscaler itself is irrelevant for this issue:

1) Once the HPA pushes pods into pending, and no resources are available, the HPA will never terminate the pending pods anymore since it does not collect stats until all the pods are running

2) If you loose heapster due to any reason at all, and don't have resources in the cluster at that point in time to start it, the HPA is not working anymore, plus that noew the not working of the HPA will forever prevent the cluster from repairing.

By adding the proposed values, the HPA would become more "self-repairing", thus preventing a few of the scenarios leading to the cluster into the described state.

**Comment by DirectXMan12** [comment] 2017-01-03 16:59
> Once the HPA pushes pods into pending, and no resources are available, the HPA will never terminate the pending pods anymore since it does not collect stats until all the pods are running

This should be fixed in 1.5.  We now consider pending pods as having synthetic resource values (ditto when some of the metrics are missing).

> Once the HPA pushes pods into pending, and no resources are available, the HPA will never terminate the pending pods anymore since it does not collect stats until all the pods are running

IIRC, there's a mechanism to give cluster-critical components priority in the scheduler (perhaps the `scheduler.alpha.kubernetes.io/criticial-pod` annotation?).  At any rate, you probably want to dedicate certain nodes as "infrastructure nodes" for cluster components, and scale those separately.  It looks like the templates for Heapster in the cluster addons directory are configured for that.

> Max pending pods: This prevents a bunch of pods from being started while they can not be scheduled in the cluster anyway.

Not a bad idea, but the new logic around pending pods (assuming them to have 0 utilization on scale up) should have a similar effect here.

> Max time a pod is allowed to stay pending: Makes the autoscaler a bit more independent from heapster.

The HPA has no control over which pods are killed, by design.  That being said, IIRC, the existing controllers kill pending pods first, but the HPA has no control over this.

> Let pods report to the HPA instead of to heapster what their load is, removing the heapster requirement completely and making the HPAs much more flexible. Heapster is then only for graphing purposes.

We are in the process of revamping the metrics collection pipeline, but we will still have a component for collecting metrics from Kubelet.  Having the HPA do this itself ties the HPA too strongly to particular implementation details, and prevents the metrics from being used by other components.

**Comment by fgrzadkowski** [comment] 2017-06-02 16:07
@kubernetes/sig-autoscaling-bugs

**Closed** 2018-02-24 02:57 UTC
Labels: area/nodecontroller, lifecycle/rotten, sig/autoscaling, team/control-plane (deprecated - do not use)
