### ISSUE TITLE
Flake: [sig-network] Services should have session affinity work for LoadBalancer service with ESIPP

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71423] opened 2018-11-26 16:58 UTC
**Which jobs are failing**: gce-cos-master-slow

**Which test(s) are failing**:  [sig-network] Services should have session affinity work for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]

**Since when has it been failing**:  This test started to be flaky on 11/18

**Testgrid link**:  https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow

**Reason for failure**:

Looks to be a pretty straightfowards test not passing:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1648
Nov 26 10:03:00.209: Affinity should hold but didn't.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service_util.go:1452
```

If we look at triage, this test has *always* been flaky, but it got significantly more flaky (2X failures) on 10/27: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-29&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP

**Anything else we need to know**:

This job is non-blocking for 1.13, *except* if this represents an actual bug in Affinity the 1.13 team needs to know ASAP.

This failure may or may not be related to #52495.  It looks like this test was disabled for large clusters, but maybe the problem wasn't the cluster size.

/kind flake
/sig network
/priority important-soon
attn:
@thockin @caseydavenport @dcbw

**Comment by AishSundar** [comment] 2018-11-27 01:14
FWIW this seems to be a long standing issue, atleast as far bck as 1.12 timeframe

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-09-01&sig=network&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP%20on

**Comment by jberkus** [comment] 2018-11-27 16:00
Sure.  But the failures have become 3X as frequent, so I still want a sign-off by sig-network.

**Comment by MrHohn** [comment] 2018-11-27 18:57
cc @grayluck

**Comment by grayluck** [comment] 2018-11-27 19:13
Ack. Will work on this.

**Comment by AishSundar** [comment] 2018-11-28 05:55
@grayluck we plan to life code freeze for 1.13 tomorrow,11/28 5pm PST. If there is a new regression in 1.13 thats increased the flakes and needs addressing we need to get the fix in asap. Can you please let us know if this is a blocker for 1.13 by tomorrow, 11/28, morning 10am PST ?

**Comment by MrHohn** [comment] 2018-11-28 18:35
> If we look at triage, this test has always been flaky, but it got significantly more flaky (2X failures) on 10/27:

Great observation. I checked on the commits around that date but wasn't able to find any change that may cause regression. Hasn't been able to reproduce the same failure locally as well.

**Comment by MrHohn** [comment] 2018-11-29 01:58
Good catch on that, so the recent increase of flakiness likely is not caused by 1.13 changes so we shouldn't block release on this either.
cc @bowei

**Comment by MrHohn** [comment] 2018-11-29 02:00
But we will be looking deeper into the root cause.

**Comment by alejandrox1** [comment] 2019-02-28 02:09
More recent failures: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1288

**Logs**:
```
I0227 05:59:19.127] [AfterEach] [sig-network] Services
I0227 05:59:19.127] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:90
I0227 05:59:19.127]
I0227 05:59:19.127] • Failure [103.407 seconds]
I0227 05:59:19.127] [sig-network] Services
I0227 05:59:19.128] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:22
I0227 05:59:19.128] should have session affinity work for LoadBalancer service with ESIPP off [Slow] [DisabledForLargeClusters] [It]
I0227 05:59:19.128] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1670
I0227 05:59:19.128]
I0227 05:59:19.128] Feb 27 05:58:24.807: Affinity should hold but didn't.
I0227 05:59:19.128]
I0227 05:59:19.128] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service_util.go:1452
```

**Comment by mariantalla** [comment] 2019-03-06 16:34
Hello, could this issue be prioritized to help with stabilizing with the release blocking upgrade tests?

They're currently flaking 
* ~23% of the time in [gce-cos-master-slow](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow) ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-03-03&job=ci-kubernetes-e2e-gci-gce-slow&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP#3623204a284d7009ec97)) 
* ~30% of the time in [gce-master-new-downgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster) ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-03-03&job=ci-kubernetes-e2e-gce-master-new-downgrade-cluster&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP#3623204a284d7009ec97))

**Comment by grayluck** [comment] 2019-03-06 21:29
I am preparing a PR, basically allow Affinity some time to be configured, instead of failing out instantly.

**Comment by mariantalla** [comment] 2019-03-08 00:06
Thanks! Will keep an eye out for it.

**Comment by grayluck** [comment] 2019-03-10 06:02
The test is no longer flaky: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow&include-filter-by-regex=session%20affinity&width=20
Thanks everyone!

**Comment by mariantalla** [comment] 2019-03-12 16:27
Thanks!

Will keep an eye on it for a few days, on the following dashboards:
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster&width=20
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster&width=20
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster&width=20
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster-parallel&width=20

**Comment by mariantalla** [comment] 2019-03-13 10:40
It's stabler now, but still flaking once/twice a day, e.g. in [upgrade tests](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce.*master.*&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP%20on).

@grayluck - Is this the same issue as you looked at? Is there more to be done here?

/reopen

**Comment by MrHohn** [comment] 2019-03-13 18:08
@grayluck @mariantalla we should probably cherrypick https://github.com/kubernetes/kubernetes/pull/75073 into 1.13 in case of deflaking upgrade/downgrade job, because those jobs would run 1.13 tests against 1.14 (upgraded) cluster or 1.13 (downgraded) cluster.

FYI we've hit similar situation for DNS test (ref https://github.com/kubernetes/kubernetes/issues/74543#issuecomment-467973692).

**Comment by spiffxp** [comment] 2019-03-16 19:13
1.14: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=k8sbeta&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP
<img width="1110" alt="Screen Shot 2019-03-16 at 12 11 07 PM" src="https://user-images.githubusercontent.com/49258/54480353-a356c880-47e4-11e9-95be-ba1f52f9f40c.png">

1.13: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=k8sstable1&test=Services%20should%20have%20session%20affinity%20work%20for%20LoadBalancer%20service%20with%20ESIPP
<img width="1091" alt="Screen Shot 2019-03-16 at 12 11 22 PM" src="https://user-images.githubusercontent.com/49258/54480355-a81b7c80-47e4-11e9-88af-8e75726ede74.png">

Do we want to cherry-pick this back further?

**Comment by grayluck** [comment] 2019-03-17 04:26
Thanks for the nice graph. Look like the fix works. I'll create cherrypick PRs for 1.11 and 1.12 right away.

**Comment by MrHohn** [comment] 2019-04-04 18:34
AFAICT this has been significantly improved: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=session%20affinity
![Screenshot from 2019-04-04 11-33-13](https://user-images.githubusercontent.com/8681801/55579620-861f6680-56cd-11e9-9179-f18bb81d08c1.png)

Closing this and thanks to @grayluck!
/close

**Closed by MrHohn** 2019-04-04 18:34 UTC
Labels: kind/flake, priority/important-soon, sig/network, triage/unresolved
