### ISSUE TITLE
Kubernetes Baremetal / VM setup  - externalTrafficPolicy : false not working

### ISSUE THREAD

**Issue by jacobpm** [kubernetes/kubernetes#58139] opened 2018-01-11 07:07 UTC
/kind bug

We are running a CoreOS and Kubernetes environment on Bare-metal as well as VM.  nginx is running as a NodePort service.  There is no other load balancer involved (external or otherwise).  Kubernetes performs source NAT of incoming requests as described [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typenodeport).  

In our case, nginx and other apps running behind nginx need to know the actual IP of the requesting end-point.  I tried upgrading to Kubernetes 1.7 and setting flag externalTrafficPolicy to false.  The yaml I use to set up the nginx NodePort service looks something like below.  
**Even with this, I am not able to see the actual source IP.**

```
{
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "nginx-service",
		"labels": {
		  "appid": "XXX",
		  "app": "nginx"
		}  
      },
      "spec": {
        "ports": [{
          "name": "http",
		  "nodePort": 80,
		  "port": 80,
          "targetPort": 80
        },
		{
          "name": "https",
		  "nodePort": 443,
		  "port": 443,
          "targetPort": 443
        }],
        "selector": {
          "app": "nginx"
        },
		"clusterIP": "10.3.0.150",
        "type": "NodePort",
        "externalTrafficPolicy": "Local"
      }
}
```
Later I chanced upon some online documentation that mentioned externalTrafficPolicy is supported only in a Google Cloud Environment.  

- Is  externalTrafficPolicy supported on BareMetal / VM installations?

- On such Baremetal / VM installations, how can kube-proxy be configured to give the actual source IP of the requesting endpoint ?

**Kubectl version output**
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-29T00:18:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+coreos.0", GitCommit:"2aa47c8ec16177de41d4c8cad63c1ba0b7bd6d78", GitTreeState:"clean", BuildDate:"2017-09-29T22:25:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**OS details**
CoreOS (4.11.9-coreos)

**Comment by jacobpm** [comment] 2018-01-11 07:15
@kubernetes/sig-network-bugs
@kubernetes/sig-onprem-bugs

Adding a couple of mailers

**Comment by jacobpm** [comment] 2018-01-11 07:15
@kubernetes/sig-network-bugs
@kubernetes/sig-onprem-bugs

Adding a couple of mailers

**Comment by m1093782566** [comment] 2018-01-12 08:02
> Is externalTrafficPolicy supported on BareMetal / VM installations

Y

> On such Baremetal / VM installations, how can kube-proxy be configured to give the actual source IP of the requesting endpoint ?

If set `"externalTrafficPolicy": "Local"`, then access service via nodeport will only forward to the backend in the same node and there is no masq. In other words, source IP will be preserved.

**Comment by m1093782566** [comment] 2018-01-12 08:03
I can't catch any bugs?

**Comment by jacobpm** [comment] 2018-01-12 09:17
> If set "externalTrafficPolicy": "Local", then access service via nodeport will only forward to the backend in the same node and there is no masq. In other words, source IP will be preserved.


First of all, thank you for the response.  
My issue is I still don't see the source IP getting preserved even after setting "externalTrafficPolicy": "Local".

**Comment by jacobpm** [comment] 2018-01-16 06:07
@thockin @m1093782566 @kubernetes/sig-network-bugs
Could you please help shed some light on this issue.  It's turning out to be a blocker for us.  Hence the request.

**Comment by m1093782566** [comment] 2018-01-22 02:19
> My issue is I still don't see the source IP getting preserved even after setting "externalTrafficPolicy": "Local".

I double checked in my environment and can't reproduce it. Please check the iptables on your node to see if there are other masq rules created by processes other than kube-proxy.

I am going to close this issue since it's not really a bug.

/close

**Comment by m1093782566** [comment] 2018-01-22 02:20
But, we can continue to discuss in this thread.

**Closed by m1093782566** 2018-01-22 02:19 UTC
Labels: kind/bug, needs-sig, sig/network, sig/onprem

**Comment by raine** [comment] 2018-11-12 10:54
Have a `kubeadm` set up on a Ubuntu VPS with the following manifest

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30957
    port: 80
    targetPort: 80
    name: http
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.8
    ports:
    - containerPort: 80
```

```
% curl <public ip>:30957
<!DOCTYPE html>
<html>
...
```

Still, nginx is not logging the actual IP request originates from:

```
10.32.0.1 - - [12/Nov/2018:10:45:39 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.54.0" "-"
```

Quite new to kubernetes so there's probably something I'm missing but would've expected adding `externalTrafficPolicy: Local` to the service to start forwarding the real IP to nginx.

Any ideas if this should even work, and if not what to look into? Cheers.


```
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
