### ISSUE TITLE
MonitorResources test is failing in flaky suite

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17773] opened 2015-11-25 12:58 UTC
For some reason it's failing with error: 
```
04:36:49   Expected error:
04:36:49       <*errors.errorString | 0xc20827f470>: {
04:36:49           s: "missing info for container \"/kube-proxy\" on node \"e2e-flaky-minion-ajl8\"",
04:36:49       }
04:36:49       missing info for container "/kube-proxy" on node "e2e-flaky-minion-ajl8"
04:36:49   not to have occurred
```
cc @wojtek-t @ixdy

**Comment by wojtek-t** [comment] 2015-11-25 13:26
@mikedanese - you move kube-proxy to the "pod". Do you know what can be causing it?

**Comment by mikedanese** [comment] 2015-11-25 15:59
Yes that's the cause. @gmarek if you don't get to this, feel free to assign to me.

**Comment by gmarek** [comment] 2015-11-25 16:05
@mikedanese - thanks, as you know the context here it'd be faster if you fix it.

**Closed** 2015-11-25 18:01 UTC
Labels: area/test, priority/P0, team/test-infra

**Comment by gmarek** [comment] 2015-11-26 08:37
Thanks for taking care of this.
