### ISSUE TITLE
Delete old use-specific tokens

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10387] opened 2015-06-26 06:52 UTC
Now that service accounts work properly, we can delete things like the DNS token and the code needed to build it.

**Comment by thockin** [comment] 2016-05-12 21:40
@erictune I forget where this live(d) are we still generating the old-style tokens?  Or can we close this?

**Comment by mikedanese** [comment] 2016-05-17 14:49
This isn't done yet.

**Comment by liggitt** [comment] 2017-09-23 21:09
dupe of https://github.com/kubernetes/kubernetes/issues/13110

**Closed by liggitt** 2017-09-23 21:09 UTC
Labels: priority/backlog, sig/auth
