### ISSUE TITLE
GKE: Kubectl client Simple pod should support inline execution and attach

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32702] opened 2016-09-14 19:23 UTC
Kubectl client Simple pod should support inline execution and attach

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by AdoHe** [comment] 2016-09-15 16:13
when I tried to debug this on my local, just got this error:
```
[root@localhost kubernetes]# go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Kubectl\sclient\sSimple\spod\sshould\ssupport\sinline\sexecution\sand\sattach$'
2016/09/15 11:30:50 e2e.go:440: Running: get status
Local doesn't need special preparations for e2e tests
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.5-dirty", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"dirty", BuildDate:"2016-09-15T15:16:21Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
error: server version (&version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.0-dirty", GitCommit:"44368db9916cc345ebef8b6fbde3cdf0dc9d79dc", GitTreeState:"dirty", BuildDate:"2016-09-15T13:54:48Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}) differs from client version (version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.5-dirty", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"dirty", BuildDate:"2016-09-15T15:16:21Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"})!
2016/09/15 11:30:50 e2e.go:446: Error running get status: exit status 1
2016/09/15 11:30:50 e2e.go:442: Step 'get status' finished in 46.285881ms
2016/09/15 11:30:50 e2e.go:418: Testing requested, but e2e cluster not up!
exit status 1
```

I set up a one node cluster with kubernetes 1.4 on my local virtual machine, and then I tried to run the e2e tests with kubernetes 1.3.5, and just got this error. Quite unlucky. :(

**Comment by AdoHe** [comment] 2016-09-16 04:34
For this issue, I rechecked build [6166](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6166), since I cannot reproduce this on my local due to the error I commented above, so I took a deep look into log, and just got some clue. 
For this `should support inline execution and attach` suit test, the root error is:
```
[Fail] Kubectl client Simple pod [It] should support inline execution and attach 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:471
```
and the corresponding code snippet in 1.2 is:
```
Expect(c.Extensions().Jobs(ns).Delete("run-test", nil)).To(BeNil())
```
try to delete the job `run-test` but failed.

The question is whether we really created a job named `run-test`?
I searched the [build-log.txt](https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6166/build-log.txt), got some messages:
```
INFO: stdout: "Waiting for pod e2e-tests-kubectl-xv67b/run-test to be running, status is Pending, pod ready: false\nabcd1234stdin closed\nWaiting for pod e2e-tests-kubectl-xv67b/run-test to terminate, status is Running\n"

Sep 15 08:20:07.738: INFO: At 2016-09-15 08:20:05 -0700 PDT - event for run-test: {default-scheduler } Scheduled: Successfully assigned run-test to gke-jenkins-e2e-default-pool-c18c0b5d-8lld
Sep 15 08:20:07.738: INFO: At 2016-09-15 08:20:06 -0700 PDT - event for run-test: {kubelet gke-jenkins-e2e-default-pool-c18c0b5d-8lld} Started: Started container with docker id e3361a60ca72
Sep 15 08:20:07.738: INFO: At 2016-09-15 08:20:06 -0700 PDT - event for run-test: {kubelet gke-jenkins-e2e-default-pool-c18c0b5d-8lld} Pulled: Container image "busybox" already present on machine
Sep 15 08:20:07.738: INFO: At 2016-09-15 08:20:06 -0700 PDT - event for run-test: {kubelet gke-jenkins-e2e-default-pool-c18c0b5d-8lld} Created: Created container with docker id e3361a60ca72; Security:[seccomp=unconfined]
```
Also if you check `kubelet.log` of `gke-jenkins-e2e-default-pool-c18c0b5d-8lld`, you will see this pod is synced. There seems nothing wrong. IIUC, when we execute `kubectl run run-test`, no matter we use `job/v1` or `job/v1beta1` generate, the job name will be `run-test`, but the pod name belong to this job will not be `run-test`, it should be `run-test-***`. But from the logs,  the pod name is actually `run-test`, which means `kubectl run` creates a pod not a job, and of course the job deletion will fail.

**Comment by AdoHe** [comment] 2016-09-16 04:36
Above is what I got from logs, maybe not right, could provide some clue to debug this. ptal

**Comment by jingxu97** [comment] 2016-09-16 22:18
@AdoHe Your analysis is right, a job is not created. The old version of the test uses " --restart=Never". On new version of cluster, with this flag, only pod will be created, not a job. @jfrazelle has a fix #32898 for it. Thank you for help debug on this.

**Comment by AdoHe** [comment] 2016-09-17 01:58
that's great. Excellent job :)

**Comment by davidopp** [comment] 2016-09-18 01:46
https://k8s-testgrid.appspot.com/google-kubectl-skew#gke-1.2-1.3-gci-kubectl-skew
https://k8s-testgrid.appspot.com/google-kubectl-skew#gke-1.2-1.3-cvm-kubectl-skew

**Comment by AdoHe** [comment] 2016-12-05 12:55
@pwittrock this can be closed, please close it.

**Closed** 2016-12-05 16:44 UTC
Labels: 4 - Done, area/test, component/kubectl, kind/upgrade-test-failure, priority/P0, team/ux
