### ISSUE TITLE
iSCSI should be deleting scsi devices on PV unmount to prevent data corruption

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#59946] opened 2018-02-15 21:20 UTC
> /kind bug

**What happened**:

I am not an iSCSI expert, but it looks like there is data corruption  possible on iSCSI LUN reuse.

In the following sequence of events on a given node:

1. Provision iSCSI volume , map to host, LUN X will be assigned to it
2. let node discover that LUN (lets say mount another iSCSI PV, which would trigger iSCSI rescan)
3. delete iSCSI volume (LUN X will be unmapped from host)
4. Create new iSCSI volume, map to host, same LUN X will be assigned to it, following warning will be printed on a console:
```
Warning! Received an indication that the LUN assignments on this target have changed. 
The Linux SCSI layer does not automatically remap LUN assignments.
```
5. create PV for that iSCSI volume
6. run pod with that PV on this node

What is going to happen, is that even though `iscsi` volume plugin rescans scsi bus, rescan doesn't delete previously existing SCSI devices, so it can (will?) use OLD LUN X scsi device and then attempt to mount it with unknown consequences. On our systems we definitely saw how freshly formatted dynamically  provisioned volume couldn't be mounted due to ext4 errors , with  LUN warnings reported just before. I'll try to prepare reproducer for this case, but this "analytical proof" looks pretty scary already :-/

Steps 1, 3 can be done by dynamic provisioner such as netapp Trident, these volumes can be mounted on another node and never be mouted on a node in  question, what important is that they are created and node discovers them.

Extra information on LUN reuse, where solid advice on device deletion is given by kernel devs:

https://www.redhat.com/archives/dm-devel/2018-January/msg00493.html
https://www.redhat.com/archives/dm-devel/2016-October/msg00409.html

/sig storage
/cc @mtanino

**Comment by redbaron** [comment] 2018-02-27 18:47
Been hit by it again :(

@mtanino , @saad-ali , @childsb , iSCSI is not handling LUN reuse correctly. What do you think of following algorithm, I can submit PR if you agree with approach:

 On PV deletion do:
  - do all necessary unmounts
  - find scsi device for a LUN being deleted
  - find parent multipath
  - if multipath is present, find scsi devices multipath is made of
  - if multipath is present, run `multipath -f  <mpath>`
  - delete all discovered earlier scsi devices via sys/class/scsi_device/${host}:${channel}:${id}:${lun}/device/delete


Ideally, we shouldn't reinvent the wheel and just call `https://github.com/hreinecke/sg3_utils/blob/master/scripts/rescan-scsi-bus.sh` with `--lun=XX -m -d`, there are too many nuances in SCSI handling to not to use  tens of years of wisdom, but bundling sg3-utils into kubelet image is unlikely to happen with all current focus on the cloud and bare-metal setups being second class citizens.

**Comment by bswartz** [comment] 2018-03-07 15:12
I'd like to take this bug and fix it

**Comment by redbaron** [comment] 2018-04-11 10:16
It is made worse when multipath is enabled on host. Essentially multipath support is broken to the point it is plain dangerous to use.

 1. LUN X is mapped to host, discovered and sdX device is created
 2. multipathd picks up that device and created multipath device
 3. kubelet mounts multipath device
 4. pod is destroed, PV is destroyed, LUN unmapped
 5. sdX device remains on a node
 6. new LUN X is mapped to host, it is discovered and same sdX device is "reassigned to it"
 7. multipath sees it as path recovering from a failure
 8. same multipath device is mounted into new container.

If multipath doesn't have `disable_changed_wwids "yes"`  in its config, it doesn't detect that scsi device was completely replaced underneath. In theory there should be no outstanding IO after unmount and no data corruption should happen, but in practice when there are 4 paths to same LUN and PV constantly coming on and off across multiple nodes, something is not working quite right occasionally.

**Comment by bswartz** [comment] 2018-04-18 14:35
I plan to address this issue with 3 commits (they can be 1 PR or separate)

1. Add code to delete block devices after they're unmounted, to avoid leaving garbage on the nodes that could lead to I/O timeouts or corruption after the real devices are gone and/or reused.
2. Change the way scanning works to only scan the specific LUNs kubelet needs, instead of scanning the whole SCSI bug and picking up unrelated LUNs.
3. Change the wait loops to directly wait on the kernel to find devices, instead of waiting for udev to make symlinks to the devices, because udev frequently gets significantly behind on uevent processing in abnormal situations like when paths are down, which can lead to timeouts.

**Comment by rootfs** [comment] 2018-04-26 17:33
cc @bmarzins

**Comment by rootfs** [comment] 2018-06-21 17:58
As @bmarzins  and @redbaron  comment, the mpath flag must be set and maybe use wwid instead lun. @humblec  and @bswartz , can you verify it on your multipath setup and come up with a doc PR if that works?

**Comment by bswartz** [comment] 2018-06-25 14:45
I've verified that "disable_changed_wwids yes" does what it's supposed to do. On all of my test systems, the WWIDs are truly unique so there's no risk of a conflict there. I'm still not convinced that kubernetes is safe from problematic behavior related to multipath though.My fix for this bug addresses the lower level problem of not detaching disks that aren't in use, but the issue of kubernetes grabbing the wrong block device remains an issue. For example I can observe that sometimes that pod mounts /dev/sdc instead of /dev/dm-1, and I haven't found a way to reliably prevent that.

**Comment by redbaron** [comment] 2018-06-25 15:28
@bswartz , if you find why it is like that, please update https://github.com/kubernetes/kubernetes/issues/60894

**Comment by bswartz** [comment] 2018-06-25 16:17
@redbaron Sure, it's pretty easy to reproduce and pretty obvious what's going on. Fixing it isn't so easy. I'll update that bug.

**Closed** 2018-07-25 23:19 UTC
Labels: kind/bug, sig/storage
