### ISSUE TITLE
Kubelet didn't try to restart container upon NoSuchContainer error reported wrongly by docker

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22541] opened 2016-03-04 18:48 UTC
I was testing instance stop & start on AWS, which effectively shuts it down and brings it back up again.  The ephemeral storage is typically lost during this procedure.  Ephemeral storage contains /var/lib/docker, along with /var/kubernetes.

After I stopped & started the master, kubelet did not restart kube-apiserver.

Logs from kubelet & docker attached.

The root cause seems to be kubelet deciding this:

```
Mar 04 18:31:19 ip-172-20-0-9 kubelet[2835]: E0304 18:31:19.206437    2835 generic.go:229] PLEG: Ignoring events for pod kube-apiserver-ip-172-20-0-9.ec2.internal/kube-system: No such container: 1f2c34e963fa532b2e68288eb0c4014d702fcea74a8e582f166f1fd26b4c736b
```

[docker.log.txt](https://github.com/kubernetes/kubernetes/files/159210/docker.log.txt)
[kubelet.log.txt](https://github.com/kubernetes/kubernetes/files/159211/kubelet.log.txt)

**Comment by yujuhong** [comment] 2016-03-04 20:45
@justinsb, what's the version of your kubelet?

**Comment by dchen1107** [comment] 2016-03-05 00:26
I believe this is a real issue caused by docker bug and kubelet hasn't handled such error scenario. Docker sometimes report No-such-container wrongly.

**Comment by dchen1107** [comment] 2016-03-05 00:37
@yujuhong I mentioned to you offline, I think this is a regression introduced to 1.2 release. Before PLEG and podcache was introduced, Kubelet blindly ignore those bad dead containers, and start a new one: https://github.com/kubernetes/kubernetes/issues/14404

**Comment by yujuhong** [comment] 2016-03-05 01:04
> @yujuhong I mentioned to you offline, I think this is a regression introduced to 1.2 release. Before PLEG and podcache was introduced, Kubelet blindly ignore those bad dead containers, and start a new one: #14404

The conclusion is that we will ignore the "no such container" error and go on to sync the pod. 
(It's a regression of a hidden feature...)

**Comment by justinsb** [comment] 2016-03-05 01:42
This was head from around lunchtime today.  I believe it was a20258efaecfc5b46f24111f17bc18168713a124

Also of note: AWS so no docker babysitter then.  I had stopped & started the instance,which is a hard case, but other containers did start fine.  The manifest file for kube-apiserver was still there.

**Comment by yujuhong** [comment] 2016-03-05 02:14
> Also of note: AWS so no docker babysitter then. I had stopped & started the instance,which is a hard case, but other containers did start fine. The manifest file for kube-apiserver was still there.

We've seen a lot of issues resulted from docker not shutting down cleanly, but in this case, kubelet should recover. I uploaded a PR #22576 for this.

**Comment by dchen1107** [comment] 2016-03-07 23:01
I am closing the issue since #22576 was merged.

**Closed by dchen1107** 2016-03-07 23:01 UTC
Labels: dependency/docker, kind/bug, priority/P1, team/node
