### ISSUE TITLE
Be able to specify wildcard with `kubectl create -f`

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#24711] opened 2016-04-24 00:39 UTC
I'm currently adding Kubernetes support to JHipster. However, when JHipster generates the Kubernetes deployment YAML files, it also generates a `.yo-rc.json` under the same directory.

If I run `kubectl create -f .`, it'll create all the resources, and attempt to parse and create `.yo-rc.json` too!

Currently, if I run `kubectl create -f *.yml`:
```
kubectl create -f *.yml
error: Unexpected args: [gateway-mysql.yml gateway-service.yml jhipster-registry.yml micro1-deployment.yml micro1-mysql.yml micro1-service.yml monolith-deployment.yml monolith-mysql.yml monolith-service.yml]
```

This should just work. Or, have .kubernetesignore file ;)

**Comment by zhouhaibing089** [comment] 2016-04-24 01:51
I am thinking `kubectl create -f a.yml,b.yml,c.yml` would work because it supports a `StringSliceVarP` flag.

I agree to support `*.yml` since it is more straightforward. I will try to look and see whether it could be refined.

**Comment by AdoHe** [comment] 2016-04-25 08:41
why not you guys just put all the yaml files under a directory? we have already support this.

**Comment by saturnism** [comment] 2016-04-25 08:45
I already described the issue. Sometimes a tool has other metadata stored
in the same directory - like this .yo-rc.json that kubernetes will also try
to deploy. It'd be really inefficient to have yet another subdir to
encapsulate the kubernetes files.

**Comment by AdoHe** [comment] 2016-04-25 08:51
what if your `.yo-rc.json` is `.yo-rc.yml`, `*.yml` is not ok in such case.

**Comment by saturnism** [comment] 2016-04-25 11:20
That's a fair point and hence the other proposal is some sort of ignore
file. But, I can also easily use command lines to filter out things I don't
want, or, use pattern matching for things I do want. I feel respecting
globs is a good thing :)

**Comment by zhouhaibing089** [comment] 2016-04-25 15:20
@AdoHe I guess the point you have is to avoid introducing more complexity because we just can find a proper way to do this, but from the perspective of user experience, what's your idea of `kubectl create -f *.yml`?

**Comment by bgrant0607** [comment] 2016-04-25 16:26
See also #12123

**Comment by bgrant0607** [comment] 2016-04-25 16:26
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment] 2016-04-25 16:29
Closing this as dupe of #12123

**Closed by bgrant0607** 2016-04-25 16:29 UTC
Labels: component/kubectl, priority/P2, team/ux

**Comment by bgrant0607** [comment] 2016-04-25 16:33
See #24649 also

**Comment by saturnism** [comment] 2016-04-27 12:43
woohoo! thanks. it should also perhaps ignore .* files by default :)

**Comment by amitvashist7** [comment] 2018-07-10 20:13
I was using the below command with wildcard & it failing: 

**# kubectl create -f metrics-server/*.yaml**

Then I simply specify the directory which contains multiple yaml definitions; 

root@kube-master:~/kubernetes-project# **kubectl create -f metrics-server**
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.extensions/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
`root@kube-master:~/kubernetes-project#`

Thanks
