### ISSUE TITLE
Probe and lifecycle hook (postStart & preStop) logs should be inlined in the container logs

### ISSUE THREAD

**Issue by MaxDaten** [kubernetes/kubernetes#16412] opened 2015-10-28 07:13 UTC
Hi,

I'm currently testing kubernetes locally with coreos (https://github.com/pires/kubernetes-vagrant-coreos-cluster) and I want to utilize the `postStart` and `preStop` hooks to implement autodiscovery of a riak cluster. My written scripts (in the container) are running as expected via `kubectl exec`. But setting them in the hook the pods can't start (`STATUS ExitCode:2`). My script utilize the stderr for error during setup but tracing the stdout would be helpful too. How can I obtain the (stdout/stderr) output of the hook commands? I tried to set the verbosity of the kubelet to `--v=10` and peek in the kubelet journal (`journalctl -u kube-kubelet.service`). This is an excerpt with the only relevant log entries:

```
{
	"__CURSOR" : "s=649e2b834e244b0ab866e14d63fbe49c;i=13807;b=ced19be51fae42e9b54d864ee9be37c6;m=6dd37d68;t=52324be77e560;x=ef8ea62926a4c69b",
	"__REALTIME_TIMESTAMP" : "1446015604876640",
	"__MONOTONIC_TIMESTAMP" : "1842576744",
	"_BOOT_ID" : "ced19be51fae42e9b54d864ee9be37c6",
	"PRIORITY" : "6",
	"_UID" : "0",
	"_GID" : "0",
	"_SYSTEMD_SLICE" : "system.slice",
	"SYSLOG_FACILITY" : "3",
	"_TRANSPORT" : "stdout",
	"_CAP_EFFECTIVE" : "3fffffffff",
	"_SELINUX_CONTEXT" : "system_u:system_r:kernel_t:s0",
	"_MACHINE_ID" : "57aaa8f8e1274460b52b4715b528799d",
	"_HOSTNAME" : "node-01",
	"SYSLOG_IDENTIFIER" : "kubelet",
	"_PID" : "1589",
	"_COMM" : "kubelet",
	"_EXE" : "/opt/bin/kubelet",
	"_CMDLINE" : "/opt/bin/kubelet --address=0.0.0.0 --port=10250 --hostname_override=172.17.8.102 --api_servers=172.17.8.101:8080 --cloud_provider= --allow_privileged=true --cluster_dns=10.100.0.10 --cluster_domain=cluster.local --logtostderr=true --config=/opt/kubernetes/manifests/ --cadvisor_port=4194 --healthz_bind_address=0.0.0.0 --healthz_port=10248 --v=10",
	"_SYSTEMD_CGROUP" : "/system.slice/kube-kubelet.service",
	"_SYSTEMD_UNIT" : "kube-kubelet.service",
	"MESSAGE" : "I1028 07:00:04.866420    1589 manager.go:922] Using docker native exec to run cmd [/usr/sbin/k8s-riak-bootstrapper] inside container b36b79643e88aae213a2dc13981b62cb9128682121b79203ecc023c63801282e"
}
{
	"__CURSOR" : "s=649e2b834e244b0ab866e14d63fbe49c;i=13808;b=ced19be51fae42e9b54d864ee9be37c6;m=6dd37e01;t=52324be77e5f9;x=601ae3d575e01d9c",
	"__REALTIME_TIMESTAMP" : "1446015604876793",
	"__MONOTONIC_TIMESTAMP" : "1842576897",
	"_BOOT_ID" : "ced19be51fae42e9b54d864ee9be37c6",
	"PRIORITY" : "6",
	"_UID" : "0",
	"_GID" : "0",
	"_SYSTEMD_SLICE" : "system.slice",
	"SYSLOG_FACILITY" : "3",
	"_TRANSPORT" : "stdout",
	"_CAP_EFFECTIVE" : "3fffffffff",
	"_SELINUX_CONTEXT" : "system_u:system_r:kernel_t:s0",
	"_MACHINE_ID" : "57aaa8f8e1274460b52b4715b528799d",
	"_HOSTNAME" : "node-01",
	"SYSLOG_IDENTIFIER" : "kubelet",
	"_PID" : "1589",
	"_COMM" : "kubelet",
	"_EXE" : "/opt/bin/kubelet",
	"_CMDLINE" : "/opt/bin/kubelet --address=0.0.0.0 --port=10250 --hostname_override=172.17.8.102 --api_servers=172.17.8.101:8080 --cloud_provider= --allow_privileged=true --cluster_dns=10.100.0.10 --cluster_domain=cluster.local --logtostderr=true --config=/opt/kubernetes/manifests/ --cadvisor_port=4194 --healthz_bind_address=0.0.0.0 --healthz_port=10248 --v=10",
	"_SYSTEMD_CGROUP" : "/system.slice/kube-kubelet.service",
	"_SYSTEMD_UNIT" : "kube-kubelet.service",
	"MESSAGE" : "E1028 07:00:04.866536    1589 manager.go:1579] Error running pod \"riak-rc-s44yp_default\" container \"riak\": failed to call event handler: Error executing in Docker Container: 1"
}
```

[Gist to the complete journal](https://gist.github.com/MaxDaten/ba9ee70d825356b84f4f)

---

the `kubectl logs -p <pod-id>` or `kubectl get events` commands did not return any valuable informations too.

Any hints, how to debug the hooks?

**Comment by alexkappa** [comment] 2015-12-31 09:55
+1 I'm experiencing the same difficulty.

**Comment by luebken** [comment] 2016-02-22 13:08
+1

**Comment by MaxDaten** [comment] 2016-02-23 07:06
@luebken I didn't :( Currently I creating the riak ring with a discovery script in the container which I execute manually. I'm waiting for the persistance volumes to get manually reclaimable somehow. Before that, a autodiscovery via hooks isn't really possible afaik. So I didn't investigate the hooks further. Sorry

**Comment by innovia** [comment] 2016-03-20 16:19
+1

**Comment by kargakis** [comment] 2016-05-16 16:38
Getting the logs from a pod should inline logs from any hooks into the container log.

cc: @bgrant0607 @smarterclayton

**Comment by kargakis** [comment] 2016-05-16 16:39
cc: @kubernetes/sig-node

**Comment by vishh** [comment] 2016-05-16 17:54
Kubelet currently uses docker logs, which does not include output from `exec` commands. We are working on improving logging and we can expect probe logs to be inline in the future.
For now, if a probe had ran and returned a non-zero result, kubelet logs the probe output [here](https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/kubelet/prober/prober.go#L104), as part of kubelet's logs.

**Comment by yujuhong** [comment] 2016-05-16 18:08
> Kubelet currently uses docker logs, which does not include output from exec commands. We are working on improving logging and we can expect probe logs to be inline in the future.
> For now, if a probe had ran and returned a non-zero result, kubelet logs the probe output here, as part of kubelet's logs.

@vishh, the code you mentioned is for readiness/liveness probes. 

For lifecycle hooks, kubelet [doesn't print the output at all](https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/kubelet/lifecycle/handlers.go#L53). We should at least logs the output when there is an error.

**Comment by kargakis** [comment] 2016-05-16 18:10
Correction on my comment above: both probe and hook logs should be inlined in the pod log

**Comment by kargakis** [comment] 2016-05-16 19:25
@vishh @yujuhong until logs will be inlined events would be good to have for failed hooks

**Comment by bgrant0607** [comment] 2016-05-16 19:26
cc @bprashanth @smarterclayton re. the riak use case.

**Comment by yujuhong** [comment] 2016-06-08 18:06
#25681 already added logging for failed hooks. The issue is only about adding events.

**Comment by kargakis** [comment] 2016-06-08 18:12
> #25681 already added logging for failed hooks. The issue is only about adding events.

@yujuhong, @vishh also added events in that pull. Question: are those logs inlined into the pod logs? If not, then let's keep this issue open to track that change.

**Comment by yujuhong** [comment] 2016-06-08 18:19
@kargakis, thanks for reminding me! I am not sure having the logs inlined is the best way to surface the failures, but I'll retitle the issue to reflect this.

**Comment by yujuhong** [comment] 2016-06-08 18:22
Actually, I found a separate issue for that purpose #25766. Closing this one.

**Comment by kargakis** [comment] 2016-06-08 18:22
Great, I had forgot about that too:)

**Closed by yujuhong** 2016-06-08 18:22 UTC
Labels: area/logging, area/usability, priority/P2, team/node

**Comment by vishh** [comment] 2016-06-08 18:47
We need to place logs from hooks and probes in a per-container instance log
file. That requires some overhauling of log management in general.

**Comment by smarterclayton** [comment] 2016-06-08 19:44
Another note on logs for this stuff - there is no way today to get
termination logs from stdout / stderr into the pod status, because they
aren't actually files anywhere.  I'll spawn an issue.
