### ISSUE TITLE
e2e flake: "Service endpoints latency should not be very high"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#25556] opened 2016-05-13 00:08 UTC
The test E2E test `Service endpoints latency should not be very high` failed in `kubernetes-e2e-gce` with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service_latency.go:115 Not all RC/pod/service trials succeeded: got 1 errors 50, 90, 99 percentiles: 2.231559817s 2.332024188s 2.494024268s
```

Link to logs: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/16770/

**Comment by fejta** [comment] 2016-05-23 22:31
Assigning to @thockin per team/cluster label

**Comment by girishkalele** [comment] 2016-05-25 00:30
@thockin @saad-ali 

Job 16770 was pretty old and seems to have been cleaned up - I will look for a more recent occurrence of the same failure.

**Comment by girishkalele** [comment] 2016-05-25 17:53
@saad-ali 

I grabbed all available consoleText files (831 at this time) and did a grep for a few of these phrases, including "Service endpoints latency should not be very high" but haven't seen a reoccurrence.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/*/consoleText

Either this is a very rare flake or the underlying issue has been fixed by a recent commit.

**Comment by saad-ali** [comment] 2016-05-25 18:04
> Either this is a very rare flake or the underlying issue has been fixed by a recent commit.

That's possible. Feel free to close as no-repro. It can be re-opened if the test fails again (while making sure to preserve the logs somewhere permanent).

**Comment by girishkalele** [comment] 2016-05-25 20:20
Ah, your point about preserving the logs permanently got me looking at the GCS storage paths and I found the original build log for Jenkins job 16770 there, even though the job has been cleaned up on the Jenkins server.

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16770

**Comment by girishkalele** [comment] 2016-05-25 20:22
no-repro
Cannot reproduce - and problem has not reoccurred in the past 440 runs of the same suite.

**Closed by girishkalele** 2016-05-25 20:22 UTC
Labels: kind/flake, priority/P1, team/cluster
