### ISSUE TITLE
Kube-proxy --> not setting up route in ipvs mode (race condition/cannot easily replicate)

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/kubernetes#72197] opened 2018-12-19 11:08 UTC
**What happened**:
I used pod with a service to it. And I couldn't connect to this pod via ClusterIP, while Pod IP worked as expected. It's not for all ClusterIP services, just for a particular one. 

That is virtual IP, that is cluster IP didn't route properly.

**What you expected to happen**:

ClusterIP working and routing properly

**How to reproduce it (as minimally and precisely as possible)**:
No idea.

**Anything else we need to know?**:
After restarting all kube-proxy pods it started to work properly. 

Here are the most relevant logs I could find. It's mostly repeating the same message over and over again.

```
I1219 11:00:08.497286       1 graceful_termination.go:160] Trying to delete rs: 10.233.11.127:5432/TCP/10.233.96.4:5432
```

```
E1219 08:43:04.078410       1 graceful_termination.go:89] Try delete rs "10.233.11.127:5432/TCP/10.233.64.18:5432" err: Failed to delete rs "10.233.11.127:5432/TCP/10.233.64.18:5432", can't find the real server
```

```
I1219 08:43:04.078417       1 graceful_termination.go:93] lw: remote out of the list: 10.233.11.127:5432/TCP/10.233.64.18:5432
```

ClusterIP: 10.233.11.127
PodIP: 10.233.64.18; after redeploying 10.233.96.4. It didn't work with either pod that's why I redeployed it.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```Linux ip-10-88-4-189.eu-central-1.compute.internal 4.15.0-1029-aws #30-Ubuntu SMP Wed Nov 21 23:58:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
- Install tools:
kubespray
- Others:

/kind bug

**Comment by nmiculinic** [comment] 2018-12-19 11:09
/sig network

@kubernetes/sig-network

**Comment by Shnatsel** [comment] 2018-12-19 15:45
Does what you're observing look similar to the symptoms described in #66509 ?

It would probably help if you could run the diagnostics command suggested on that issue and post the output.

**Comment by lbernail** [comment] 2018-12-28 09:33
This is a duplicate of #71071
@nmiculinic : this issue is only present in kube-proxy 1.12.2+ (which you seem to be using given the logs, graceful termination is not enabled in 1.12.0 and 1.12.1)

**Comment by jcperezamin** [comment] 2019-02-11 14:23
As well on 1.13.0

E0211 14:16:59.924645       1 proxier.go:1530] Failed to list IPVS destinations, error: device or resource busy
E0211 14:16:59.924721       1 proxier.go:1150] Failed to sync endpoint for service: 10.233.112.0:31269/TCP, err: device or resource busy
E0211 14:16:59.924664       1 graceful_termination.go:89] Try delete rs "10.10.34.21:32571/TCP/10.233.64.77:443" err: Failed to delete rs "10.10.34.21:32571/TCP/10.233.64.77:443", can't find the real server
I0211 14:16:59.937752       1 graceful_termination.go:93] lw: remote out of the list: 10.10.34.21:32571/TCP/10.233.64.77:443
I0211 14:16:59.937829       1 graceful_termination.go:160] Trying to delete rs: 10.233.22.194:80/TCP/10.233.94.56:4040
I0211 14:16:59.938052       1 graceful_termination.go:160] Trying to delete rs: 10.10.34.21:32244/TCP/10.233.94.88:80
I0211 14:16:59.938175       1 graceful_termination.go:160] Trying to delete rs: 10.10.34.21:32244/TCP/10.233.64.78:80
E0211 14:16:59.940014       1 graceful_termination.go:183] Try flush graceful termination list err
I0211 14:17:59.940627       1 graceful_termination.go:160] Trying to delete rs: 10.10.34.21:32571/TCP/10.233.64.78:443

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by lbernail** [comment] 2019-02-11 14:46
@jcperezamin : yes, the fix was cherry-picked in `1.13.2`

**Comment by jcperezamin** [comment] 2019-02-12 11:18
It seems working fine after update to 1.13.3

I0212 10:56:55.746904       1 graceful_termination.go:174] Deleting rs: 172.17.0.1:32139/TCP/10.233.94.60:135
I0212 11:02:21.319291       1 graceful_termination.go:160] Trying to delete rs: 10.233.60.68:135/TCP/10.233.94.72:135
I0212 11:02:21.319841       1 graceful_termination.go:174] Deleting rs: 10.233.60.68:135/TCP/10.233.94.72:135
I0212 11:02:21.322581       1 graceful_termination.go:160] Trying to delete rs: 10.10.34.19:31156/TCP/10.233.94.72:135
I0212 11:02:21.323263       1 graceful_termination.go:174] Deleting rs: 10.10.34.19:31156/TCP/10.233.94.72:135
I0212 11:02:21.323972       1 graceful_termination.go:160] Trying to delete rs: 10.233.68.0:31156/TCP/10.233.94.72:135
I0212 11:02:21.324383       1 graceful_termination.go:174] Deleting rs: 10.233.68.0:31156/TCP/10.233.94.72:135
I0212 11:02:21.325304       1 graceful_termination.go:160] Trying to delete rs: 127.0.0.1:31156/TCP/10.233.94.72:135
I0212 11:02:21.325789       1 graceful_termination.go:174] Deleting rs: 127.0.0.1:31156/TCP/10.233.94.72:135
I0212 11:02:21.326450       1 graceful_termination.go:160] Trying to delete rs: 172.17.0.1:31156/TCP/10.233.94.72:135
I0212 11:02:21.327435       1 graceful_termination.go:174] Deleting rs: 172.17.0.1:31156/TCP/10.233.94.72:135
I0212 11:13:57.099981       1 graceful_termination.go:160] Trying to delete rs: 10.233.60.68:135/TCP/10.233.94.72:135
I0212 11:13:57.100087       1 graceful_termination.go:174] Deleting rs: 10.233.60.68:135/TCP/10.233.94.72:135
I0212 11:13:57.112270       1 graceful_termination.go:160] Trying to delete rs: 10.10.34.19:31156/TCP/10.233.94.72:135
I0212 11:13:57.112404       1 graceful_termination.go:174] Deleting rs: 10.10.34.19:31156/TCP/10.233.94.72:135
I0212 11:13:57.112610       1 graceful_termination.go:160] Trying to delete rs: 10.233.68.0:31156/TCP/10.233.94.72:135
I0212 11:13:57.112680       1 graceful_termination.go:174] Deleting rs: 10.233.68.0:31156/TCP/10.233.94.72:135
I0212 11:13:57.112887       1 graceful_termination.go:160] Trying to delete rs: 127.0.0.1:31156/TCP/10.233.94.72:135
I0212 11:13:57.112948       1 graceful_termination.go:174] Deleting rs: 127.0.0.1:31156/TCP/10.233.94.72:135
I0212 11:13:57.113116       1 graceful_termination.go:160] Trying to delete rs: 172.17.0.1:31156/TCP/10.233.94.72:135
I0212 11:13:57.113179       1 graceful_termination.go:174] Deleting rs: 172.17.0.1:31156/TCP/10.233.94.72:135

**Comment by lbernail** [comment] 2019-03-09 10:42
I think we close this issue (duplicate  #71071 and fixed)

**Closed** 2019-03-09 10:45 UTC
Labels: area/ipvs, kind/bug, sig/network, triage/unresolved
