### ISSUE TITLE
pvc is not deleted when the owner statefulset is deleted

### ISSUE THREAD

**Issue by dhcn** [kubernetes/kubernetes#78724] opened 2019-06-05 10:22 UTC
/sig Storage
**What happened**:
we create a crd, the cr has a statefulset, the cr has a pv template,and share it with the statefulset.
when we delete the cr, the pvc generated by pv template is still appear.
**What you expected to happen**:
when we delete the cr, the pvc generated by pv template is deleted too. because we may change the pvc template.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2019-06-06 13:14
what version of kubernetes are you using?

**Comment by liggitt** [comment] 2019-06-06 13:15
> the cr has a statefulset

does the StatefulSet have an ownerReference pointing at the cr instance? can you provide the API objects (full yaml) of the cr instance and the statefulset instance prior to deletion?

**Comment by liggitt** [comment] 2019-06-06 19:31
@kubernetes/sig-storage-misc @kubernetes/sig-apps-misc is there a reason the PVCs created by the statefulset controller don't set up a controller ownerRef pointing at the statefulset?

is it not desired that deletion of the statefulset also delete the associated PVCs?

https://github.com/kubernetes/kubernetes/blob/461f439b24ee43d95f328d225d1464f948f70893/pkg/controller/statefulset/stateful_set_utils.go#L141-L162

**Comment by msau42** [comment] 2019-06-06 21:08
It is intentional for scale down and then up scenarios.

There have been requests to add this as a new feature but it needs a new API option to preserve backwards compatibility.  Let me try to find the related issues/prs...

**Comment by msau42** [comment] 2019-06-06 21:53
Here's the main issue with discussion: https://github.com/kubernetes/kubernetes/issues/55045

I think the next steps are we need an owner for this feature to develop a KEP and own the implementation.

**Comment by liggitt** [comment] 2019-06-12 00:59
/close

duplicate of #55045

**Closed by liggitt** 2019-06-12 00:59 UTC
Labels: kind/feature, sig/apps, sig/storage
