### ISSUE TITLE
Daemons started on master node are not reachable

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28356] opened 2016-07-01 15:35 UTC
In v1.2.5 Daemon Pods are started on master machine, which is Unschedulable (this may be a problem, or not - I'm not certain what the decision was). For some reason Pod that is started on master machine is not reachable from other machines (it's reachable from master though). After upgrade to v1.3.0-beta.3 problem persists.

Repro:
- start a cluster (certainly from 1.2 branch, but I think it'll work the same on 1.3)
- create a daemon set:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: daemon
  name: daemon
spec:
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
      - image: gcr.io/google_containers/serve_hostname:v1.4
        name: servehostname
        ports: 
        - containerPort: 9376
```
- `kubectl get pod -o wide`
- find out which pod runs on the master machine
- `kubectl describe <that pod>`, find Pod IP
- ssh to any node and try `curl <pod IP>:9376` - it should hang.
- profit!

(to verify you can try curling any other daemon pod, which should work)

cc @fgrzadkowski @davidopp @erictune

**Comment by mikedanese** [comment] 2016-07-01 16:39
I wonder if this is a problem with pods in general.

**Comment by gmarek** [comment] 2016-07-01 16:45
I don't know who knows anything about master network. @thockin?

**Comment by mikedanese** [comment] 2016-07-01 16:52
Another question, do pods allocated on the master and not on the host network have connectivity connectivity before the restart?

**Comment by mikedanese** [comment] 2016-07-01 16:52
@freehan has been working on this.

**Comment by thockin** [comment] 2016-07-01 17:12
Why are pods running on the master?  That seems like a disastrously bad assumption.  The master may or may not have a link to the "real" pod network.

**Comment by mikedanese** [comment] 2016-07-01 17:20
@thockin that appears to be the case. At least on GCI, the kubelet flags on the master specify a --pod-cidr that doesn't match the route created by the route controller. I'm bringing up a v1.2.5 cluster now.

I don't know what you are referring to when you say "disastrously bad assumption". Knowing the caveats, this is a useful feature. Adding a taint to the master once NoScheduleNoPlace policy is implemented will make it more difficult for inexperienced users to do this accidentally. We need to make the change to ignore unsechdulable in the daemonset controller before bringing daemonset to beta because it did break compatibility.

**Comment by thockin** [comment] 2016-07-01 17:34
I think there's a difference between a "drained" node and the master.  We
don't make that distinction.  No user pod should "accidentally" run on the
master.  In situations like GKE it just WILL NOT work.

**Comment by mikedanese** [comment] 2016-07-01 17:59
GKE master kubelets are not registered so this could never happen in GKE. If a user chooses to register the master kubelet, they are opting into a mode where the master can run allocations like any other node. This obviously has some caveats, like if you want those pods to be able to talk to pods on other nodes you need to correctly configure the master bridge. What you get is kubectl logs, heapster monitoring, ability to ship master logs to a logging service using a fluentd daemonset...

We should allow this advanced feature to be opted into. It is only enabled by default in GCE, a deployment primary used for testing by k8s developers

**Comment by mikedanese** [comment] 2016-07-01 18:06
We traditionally enable alpha and expert features in GCE and not other platforms because if we don't, they don't get tested.

**Comment by freehan** [comment] 2016-07-01 18:26
The network route is not created for master. I thought that was intentional, no? You want to restrict access to master right? Plus there is no kube-proxy on master.

**Comment by thockin** [comment] 2016-07-01 19:21
Yeah, I think the idea that master can run user-pods is something that
should be explicitly chosen, not accidental.  At least, as long as we have
"master nodes".

**Comment by mikedanese** [comment] 2016-07-01 19:26
Ok. Closing since this is the intended behavior

**Closed by mikedanese** 2016-07-01 19:26 UTC
Labels: kind/bug, team/control-plane
