### ISSUE TITLE
ci-kubernetes-e2e-gci-gke-slow has been broken since 21:19pm EST yesterday

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#42484] opened 2017-03-03 15:15 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/3594

```
[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Alpha should create and delete alpha persistent volumes [Slow] [Volume] 5m13s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Dynamic\sprovisioning\s\[k8s\.io\]\sDynamicProvisioner\sAlpha\sshould\screate\sand\sdelete\salpha\spersistent\svolumes\s\[Slow\]\s\[Volume\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:242
Expected error:
    <*errors.errorString | 0xc420c03c50>: {
        s: "PersistentVolumeClaim pvc-mz6d4 not in phase Bound within 5m0s",
    }
    PersistentVolumeClaim pvc-mz6d4 not in phase Bound within 5m0s
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:46from junit_02.xml
Filter through log files | View test history on testgrid

[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Beta should create and delete persistent volumes [Slow] [Volume] 5m13s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Dynamic\sprovisioning\s\[k8s\.io\]\sDynamicProvisioner\sBeta\sshould\screate\sand\sdelete\spersistent\svolumes\s\[Slow\]\s\[Volume\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:163
Expected error:
    <*errors.errorString | 0xc42134da10>: {
        s: "PersistentVolumeClaim pvc-ddw16 not in phase Bound within 5m0s",
    }
    PersistentVolumeClaim pvc-ddw16 not in phase Bound within 5m0s
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:46from junit_06.xml
```

**Comment by smarterclayton** [comment] 2017-03-03 15:16
@ncdc found:

```
[9:58]  
ProvisioningFailed: Error creating provisioned PV object for claim e2e-tests-statefulset-bn9md/datadir-ss-0: persistentvolumes "pvc-0796659b-ffc0-11e6-a860-42010af00034" is forbidden: error querying GCE PD volume gke-bootstrap-e2e-ce84-pvc-0796659b-ffc0-11e6-a860-42010af00034: googleapi: Error 403: Insufficient Permission, insufficientPermissions. Deleting the volume
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5435/?log#log

**Comment by smarterclayton** [comment] 2017-03-03 15:16
@k8s-oncall @kubernetes/sig-testing-bugs did we change anything in test-infra or auth info on the backend yesterday?

**Comment by smarterclayton** [comment] 2017-03-03 15:32
@gnufied was looking at this.

**Comment by smarterclayton** [comment] 2017-03-03 15:35
Relaying from chat:

- no changes to kubernetes or test-infra in the time window
- suspect something in Google GCE infra changed, like a service account permission?

**Comment by gnufied** [comment] 2017-03-03 15:48
Yeah even dynamic provisioning tests failed with:

```
vent for pvc-mz6d4: {persistentvolume-controller } ProvisioningFailed: Error creating provisioned PV object for claim e2e-tests-volume-provisioning-rdqfz/pvc-mz6d4: persistentvolumes "pvc-adeddec0-001d-11e7-a07a-42010af00043" is forbidden: error querying GCE PD volume gke-bootstrap-e2e-2ef7-pvc-adeddec0-001d-11e7-a07a-42010af00043: googleapi: Error 403: Insufficient Permission, insufficientPermissions. Deleting the volume.
I0303 06:33:46.192] Mar  3 06:33:34.649: INFO: At 2017-03-03 06:29:30 -0800 PST - event for pvc-mz6d4: {persistentvolume-controller } ProvisioningCleanupFailed: Error cleaning provisioned volume for claim e2e-tests-volume-provisioning-rdqfz/pvc-mz6d4: persistentvolumes "pvc-adeddec0-001d-11e7-a07a-42010af00043" is forbidden: error querying GCE PD volume gke-bootstrap-e2e-2ef7-pvc-adeddec0-001d-11e7-a07a-42010af00043: googleapi: Error 403: Insufficient Permission, insufficientPermissions. Please delete manually.
```

**Comment by cjcullen** [comment] 2017-03-03 17:28
I'm digging into whether something changed in GKE

**Comment by gnufied** [comment] 2017-03-03 17:35
GKE was supposed to start using v1 version of SCs - https://github.com/kubernetes/kubernetes/pull/42477 

But I don't see how that can cause permission problems. cc @msau42

**Comment by msau42** [comment] 2017-03-03 18:57
I made two changes in GKE recently, but I do not believe they should cause issues with GCE PD permissions.

1. Enable v1 version of SC api.  I don't think this should cause issues because no code has been changed to use the v1 API yet.  All code should still be using v1beta.
2. Enable the PersistentVolumeLabel admission controller.  The admission controller operates on PVs after they've been created, but it looks like in this problem, the PV creation itself failed.

Regardless, I will continue to look into this issue more deeply.

**Comment by msau42** [comment] 2017-03-03 21:07
I believe the issue is enabling the PersistentVolumeLabel admission controller.  It is trying to query the labels for the PV, but is failing due to permission issues.  That causes the Admit() to return an error, causing the PV creation to fail.

**Comment by kow3ns** [comment] 2017-03-04 00:37
All the StatefulSet tests are broken on GKE with the following error:

I0303 15:41:59.672] Mar  3 15:41:33.663: INFO: At 2017-03-03 15:22:26 -0800 PST - event for datadir-ss-0: {persistentvolume-controller } ProvisioningFailed: Error creating provisioned PV object for claim e2e-tests-statefulset-cmdpk/datadir-ss-0: persistentvolumes "pvc-23412a8c-0068-11e7-9427-42010af0001a" is forbidden: error querying GCE PD volume gke-e2e-gke-agent-pr-7-pvc-23412a8c-0068-11e7-9427-42010af0001a: googleapi: Error 403: Insufficient Permission, insufficientPermissions. Deleting the volume.

[logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42367/pull-kubernetes-e2e-gke-gci/20881/?log#log)

**Comment by msau42** [comment] 2017-03-04 00:39
I just checked in a GKE change to disable the admission controller, so once that rolls out tonight, it should be fixed.

**Comment by msau42** [comment] 2017-03-06 23:44
The GKE issue has been fixed, so this can be closed now.

**Closed** 2017-03-07 01:21 UTC
Labels: kind/flake, priority/P0, sig/storage
