### ISSUE TITLE
Federated ReplicaSet e2e is timing out

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#32733] opened 2016-09-14 22:34 UTC
@mwielgus could you please take a look at this today?

Some hints. We are seeing this in the logs of  https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/4126

```
Replicas not match, federation replicas: 5/0, clusters replicas: 0/0
```

The last 0/0 doesn't look right.

cc @kubernetes/sig-cluster-federation @jianhuiz @kshafiee

**Comment by nikhiljindal** [comment] 2016-09-15 01:47
Making this P0.
Atleast need to to figure out if this is a code issue or just a test issue.

**Comment by pwittrock** [comment] 2016-09-16 21:39
@quinton-hoole Told me that this is not something we should consider a release blocker and they can work around if need be

**Comment by quinton-hoole** [comment] 2016-09-16 21:50
More precisely @jianhuiz is currently looking into it.  The test passes sometimes (~20%).   We can't release Federated ReplicaSets until we've root caused the problem, but it does not hold up the general release of Kubernetes v1.4.

**Comment by nikhiljindal** [comment] 2016-09-19 18:56
I will take a look as well

**Comment by nikhiljindal** [comment] 2016-09-20 18:16
This is passing locally for me. So this is definitely not a code issue, just a test setup issue.
The failure on Jenkins might be a low timeout issue.

**Comment by jianhuiz** [comment] 2016-09-20 19:20
it appears that kubelet is killing and restarting etcd which causes the instability of the underlying k8s clusters which makes the federation e2e test difficult to succeed.

following are the logs, note that I was running k8s in OpenStack


```
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.845746   11381 prober.go:108] Liveness probe for "etcd-server-k8s2-master_kube-system(fe173ea98e609960da703f987c32a01e):etcd-container" failed (failure): HTTP probe failed with statuscode: 503
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.845845   11381 kubelet.go:2319] SyncLoop (container unhealthy): "etcd-server-k8s2-master_kube-system(fe173ea98e609960da703f987c32a01e)"
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.940604   11381 openstack.go:431] Claiming to support Zones
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.940667   11381 openstack.go:436] Current zone is RegionOne
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.940718   11381 kubelet_node_status.go:251] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=RegionOne
Sep 20 18:10:20 k8s2-master kubelet[11381]: I0920 18:10:20.964085   11381 openstack_instances.go:79] Claiming to support Instances
Sep 20 18:10:21 k8s2-master kubelet[11381]: I0920 18:10:21.150815   11381 docker_manager.go:2000] pod "etcd-server-k8s2-master_kube-system(fe173ea98e609960da703f987c32a01e)" container "etcd-container" is unhealthy, it will be killed and re-created.
Sep 20 18:10:21 k8s2-master kubelet[11381]: I0920 18:10:21.150888   11381 docker_manager.go:1492] Killing container "ba2aab562b2bde246a1edc2bc80645348119c7f5ce9f2361169e4f2555925b21 etcd-container kube-system/etcd-server-k8s2-master" with 30 second grace period
Sep 20 18:10:21 k8s2-master docker-current[10809]: time="2016-09-20T18:10:21.151977893Z" level=info msg="{Action=stop, ID=ba2aab562b2bde246a1edc2bc80645348119c7f5ce9f2361169e4f2555925b21, LoginUID=4294967295, PID=11381}"

**Comment by nikhiljindal** [comment] 2016-09-20 20:40
@jianhuiz Is that specific to replica sets or are all federation e2e's failing on Openstack?
If the latter, then might be better to open a new issue specific to federation on openstack?

**Comment by nikhiljindal** [comment] 2016-09-20 20:43
Am able to reproduce the failure locally when I run all the tests.
Replicaset tests pass when I run only the replicaset tests, so looks like something else is interfering.

**Comment by nikhiljindal** [comment] 2016-09-20 20:45
Looking at the failure logs, I see that the controller manager is crashing with the following panic:

```
12:08:57 panic: assignment to entry in nil map
12:08:57 
12:08:57 goroutine 110 [running]:
12:08:57 panic(0x396b740, 0xc8202c6a20)
12:08:57 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12:08:57 k8s.io/kubernetes/federation/pkg/federation-controller/ingress.(*IngressController).updateClusterIngressUIDToMasters(0xc82011b180, 0xc820068b00, 0xc8208148c0, 0x10)
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/ingress/ingress_controller.go:564 +0xf25
12:08:57 k8s.io/kubernetes/federation/pkg/federation-controller/ingress.(*IngressController).reconcileConfigMap(0xc82011b180, 0xc820ad0dc0, 0xc820396d80)
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/ingress/ingress_controller.go:492 +0x10f3
12:08:57 k8s.io/kubernetes/federation/pkg/federation-controller/ingress.(*IngressController).reconcileConfigMapForCluster(0xc82011b180, 0xc820950780, 0x20)
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/ingress/ingress_controller.go:460 +0xd8e
12:08:57 k8s.io/kubernetes/federation/pkg/federation-controller/ingress.(*IngressController).Run.func4(0xc821121e80)
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/ingress/ingress_controller.go:312 +0xeb
12:08:57 k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler.func1(0xc820a8cca0, 0xc8200474b0)
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:176 +0xb3
12:08:57 created by k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler
12:08:57 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:181 +0x3f
12:08:57 
```


Not sure why does that panic happen only when the replicaset tests are running (maybe it has to do with the order in which tests are run).
Sending a fix for the panic.

**Comment by nikhiljindal** [comment] 2016-09-20 20:56
Sent https://github.com/kubernetes/kubernetes/pull/33120

I see now that the ingress e2e is also failing with the same panic.
So the fix is for both ingress e2e and replicaset e2e.

**Comment by nikhiljindal** [comment] 2016-09-20 23:03
ingress e2e is still failing after that fix.
Filed https://github.com/kubernetes/kubernetes/issues/33135 for that with more details

**Comment by nikhiljindal** [comment] 2016-09-20 23:12
replicaset e2e is also still failing with the following logs:
```
STEP: Updating federation replicaset "federation-replicaset" in namespace "e2e-tests-federation-replicaset-rndu0"
STEP: Successfully updated federation replicaset "federation-replicaset" in namespace "e2e-tests-federation-replicaset-rndu0"
STEP: Replicas not match, federation replicas: 15/5, clusters replicas: 15/15

STEP: Replicas not match, federation replicas: 15/15, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

Sep 20 14:44:47.610: INFO: Unexpected error occurred: timed out waiting for the condition
```

This seems like a bug in the code that divides the replicas in individual clusters. The divisions sum up to 14 instead of summing up to 15.

**Comment by jianhuiz** [comment] 2016-09-21 05:25
it was tested twice according to the log, one 15/14, yet the other succeed. There is however no replicaset controller logs, @nikhiljindal could you let the  e2e run controller manager with `--v=5` to enable more logs?

**Comment by jianhuiz** [comment] 2016-09-21 06:02
@mwielgus it's the planner issue which gave different outputs while providing different running replicas. 
e.g. it fails with the given case
```
        doCheckWithExisting(t, map[string]fed_api.ClusterReplicaSetPreferences{
                "*": {Weight: 1}},
                15, []string{"A", "B"},                         // replicas and clusters
                map[string]int64{"A": 5, "B": 8},         // running pods
                map[string]int64{"A": 7, "B": 8})         // expected result
```
```
--- FAIL: TestEqualWithExisting (0.00s)
        Error Trace:    planner_test.go:43
                        planner_test.go:110
        Error:          Not equal: map[string]int64{"A":7, "B":8} (expected)
                                != map[string]int64{"A":6, "B":8} (actual)

FAIL
```
It fails for `{"A": 5, "B": 8}`, too; but succeeds for other `{"A": x, "B": 8}` where x <= 7


@deepak-vij @kshafiee

**Comment by nikhiljindal** [comment] 2016-09-21 06:22
@jianhuiz Yes I was surprised that replicaset controller produces no logs at all unless I set --v.
I am not sure how to set it only for my PR.

Re: failing test case. Will be great if you can send a PR adding that case to planner_test.go. We can comment out the code for tests to pass on HEAD, but that will make it easy to reproduce that failure to test the fix.

**Comment by nikhiljindal** [comment] 2016-09-21 07:01
Sent https://github.com/kubernetes/kubernetes/pull/33159 to dump federation events which should help in debugging this

**Comment by nikhiljindal** [comment] 2016-09-21 18:01
Thanks @jianhuiz I am able to repro the failure with your test case.
Am debugging.

**Comment by jianhuiz** [comment] 2016-09-21 21:21
Sent #33213 fixing the planner issue

**Comment by nikhiljindal** [comment] 2016-09-22 17:29
This should now be fixed, but cant verify since e2e tests are failing on Jenkins, probably due to a quota issue.
Will close the issue when tests pass on Jenkins.

**Comment by nikhiljindal** [comment] 2016-11-09 23:19
Verified that this is now passing on Jenkins

**Closed by nikhiljindal** 2016-11-09 23:19 UTC
Labels: area/cluster-federation, component/apiserver, priority/P0, team/ux
