### ISSUE TITLE
e2e flake: "Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession"

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#21830] opened 2016-02-24 01:06 UTC
• Failure [1033.846 seconds]
Pod Disks
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:267
  should schedule a pod w/ a readonly PD on two hosts, then remove both. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:164

  Expected error:
      <*errors.errorString | 0xc209d73110>: {
          s: "gave up waiting for pod 'pd-test-a830c21c-da6b-11e5-8b3e-7831c1b8a4a8' to be 'running' after 15m0s",
      }
      gave up waiting for pod 'pd-test-a830c21c-da6b-11e5-8b3e-7831c1b8a4a8' to be 'running' after 15m0s
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:157

**Comment by quinton-hoole** [comment] 2016-02-24 01:07
Ref #21800

**Comment by quinton-hoole** [comment] 2016-02-24 03:13
Fixed! https://github.com/kubernetes/kubernetes/issues/21800#issuecomment-188037923

**Comment by a-robinson** [comment] 2016-02-24 19:41
Saw this flake again this morning:
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/1037/
```
Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession [Slow]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:266 Expected error: <*errors.errorString | 0xc2083326d0>: { s: "gave up waiting for pod 'pd-test-065def0f-db24-11e5-8bdd-42010af01555' to be 'running' after 15m0s", } gave up waiting for pod 'pd-test-065def0f-db24-11e5-8bdd-42010af01555' to be 'running' after 15m0s not to have occurred
```

**Comment by quinton-hoole** [comment] 2016-02-24 22:03
That looks like a general flake, not specific to multi-zone clusters. 
Updating title of this issue accordingly.

**Comment by davidopp** [comment] 2016-02-26 09:05
@saad-ali Do you think this is more likely PD-related more something-else-related? If you think it's PD-related, maybe you can take a look, otherwise we can take a look.

**Comment by quinton-hoole** [comment] 2016-02-26 16:34
Based on the error message it seems to be a bug in either the test or in PD mounting.  The title of the issue was actually wrong, as the test that @a-robinson reported was actually diferent from the original one that was failing here.  I've updated. Assigning to @saad-ali as the only reason it was originally assigned to team/control-plane was because it was originally an ubernetes0lite test failure, which has since been resolved.

**Comment by saad-ali** [comment] 2016-02-26 19:19
Verified that https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/1037/ ran into https://github.com/kubernetes/kubernetes/issues/19953

Smoking gun from the kubelet logs:
```
E0224 18:42:05.756508    3436 gce_util.go:179] Error attaching PD "jenkins-e2e-fe8fb1df-db23-11e5-8185-42010af01555": googleapi: Error 400: The disk resource 'projects/k8s-jkns-e2e-gke-slow/zones/us-central1-f/disks/jenkins-e2e-fe8fb1df-db23-11e5-8185-42010af01555' is already being used by 'projects/k8s-jkns-e2e-gke-slow/zones/us-central1-f/instances/gke-jenkins-e2e-f55c5f93-node-4k7m'
```

Closing this as a duplicate of issue https://github.com/kubernetes/kubernetes/issues/19953. Fix for that issue is WIP: https://github.com/kubernetes/kubernetes/issues/21931

**Closed** 2016-02-26 22:30 UTC
Labels: kind/flake, priority/P1, team/cluster
