### ISSUE TITLE
unit flake: empty_dir.TestMetrics (from k8s.io_kubernetes_pkg_volume_empty_dir)

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20028] opened 2016-01-22 22:48 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/6724/testReport/(root)/empty_dir/TestMetrics/

console output:
```
00:22:20 FAIL	k8s.io/kubernetes/pkg/volume/host_path	0.099s
```

test output:
```
Error Message

Failed
Stacktrace

empty_dir_test.go:320: Expected Available to be greater than 0
```

**Comment by lavalamp** [comment] 2016-01-25 17:40
@thockin to delegate

**Comment by alex-mohr** [comment] 2016-01-25 20:13
FWIW, I hear Tim is looking at this and the 2 other referenced issues himself, so no need to delegate.

**Comment by freehan** [comment] 2016-01-27 00:42
I am able to reproduce the failure by manually filling /tmp and run the test, of course on a test box... Not sure why it gets into this state in Jenkins. 

Basically these 3 unit tests assumes there is available space under /tmp. One also tries to create a helloworld file to check if the du metrics reflects it.

**Comment by goltermann** [comment] 2016-01-27 16:21
Does #20111 look like a fix for this?  @fabioy

**Comment by fabioy** [comment] 2016-01-27 21:14
It may help with this test, since it'd isolate each test's temp directory (and away from "/tmp").

**Comment by pmorie** [comment] 2016-01-28 20:48
@fabioy I'm not certain from looking at #20111 that it would help -- it's a NOP transformation as far as the code in question is concerned, unless I'm missing something.

I will try to reproduce this one independently.

**Comment by fabioy** [comment] 2016-01-28 21:26
#20111 may help reduce flakiness if it's a "/tmp" dir runs-out-of-space issue (since it gives each test a different tmp dir). But, it may not address the underlying problem, if something else is going on.

**Comment by pmorie** [comment] 2016-01-29 05:49
@fabioy Spent a little time on this before getting sucked into a meeting vortex but couldn't repro, will try again in the AM

**Comment by thockin** [comment] 2016-01-29 18:34
Status?  It sounds like this might be a legit "0 disk space case" - is the test ready to handle this?

**Comment by freehan** [comment] 2016-01-29 19:27
@thockin The test also tries to create a file and check if du metrics reflects it. Should we skip the file creation part if no space available?

**Comment by aveshagarwal** [comment] 2016-01-29 22:09
On my local VM, I filled /tmp completely: 
tmpfs                    3.9G  3.9G     0 100% /tmp

and ran stress tests:
../code/bin/stress ./volume.test -test.run=FlakyTest
3520 runs so far, 0 failures

**Comment by fabioy** [comment] 2016-01-29 22:21
@aveshagarwal If you ran the test after PR #20111, then the temp directory it looks for may not be under "/tmp". A lot of tests seemed to then "/tmp.k8s".

**Comment by freehan** [comment] 2016-02-01 19:03
Closing this issue... Reopen if it comes back.

**Comment by freehan** [comment] 2016-02-01 19:04
Closing this issue... Reopen if it comes back.

**Closed by freehan** 2016-02-01 19:04 UTC
Labels: kind/flake, priority/P1, team/cluster
