### ISSUE TITLE
kubectl get pods -l app=httpd-deploy,run=my-nginx   No resources found.

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#78398] opened 2019-05-27 14:16 UTC
i can't Filtering pods with two labels
```
[root@k8s-master ~]# kubectl get pods --show-labels
NAME                                      READY   STATUS    RESTARTS   AGE   LABELS
httpd-deploy-6876b4f86f-svdg8             1/1     Running   1          26h   app=httpd-deploy,pod-template-hash=6876b4f86f
my-nginx-cf4bf8df9-4v87n                  1/1     Running   4          22d   pod-template-hash=cf4bf8df9,run=my-nginx
nfs-client-provisioner-75bf876d88-44dmm   1/1     Running   12         81d   app=nfs-client-provisioner,pod-template-hash=75bf876d88
[root@k8s-master ~]# kubectl get pods -l app=httpd-deploy,run=my-nginx            
No resources found.
[root@k8s-master ~]# 
[root@k8s-master ~]# 
[root@k8s-master ~]# kubectl get pods -l 'app in (httpd-deploy),run in (my-nginx)'
No resources found.
```

**Comment by tedyu** [comment] 2019-05-27 15:40
From Builder#LabelSelector, it seems the label selector is single selector.

**Comment by avorima** [comment] 2019-05-29 18:11
I think the label selector is working as intended. The help output for selector lists `-l key1=value1,key2=value2` as example. From what I understand this means that it will search for a resource that has **both** labels.

To verify this you can label your pod `my-nginx-cf4bf8df9-4v87n` with `app=httpd-deploy` and then your query should work.

**Comment by php-coder** [comment] 2019-07-12 16:49
@willzhang see the comment from @avorima This doesn't look like a bug. Could we close the issue then?

**Closed** 2019-12-09 18:34 UTC
Labels: kind/bug, lifecycle/rotten, needs-sig
