### ISSUE TITLE
kube-up provisioning fails with Vagrant provider

### ISSUE THREAD

**Issue by rothgar** [kubernetes/kubernetes#26573] opened 2016-05-31 17:02 UTC
VMs are created but during the provisioning steps dnf-plugins-core fails to install which I believe causes a cascade of other failures. I haven't yet made any changes to the salt states requiring this package (I haven't found the one I need yet)
Opening this issue to track the issue and maybe get help finding where to make the change.
```
==> node-2:   Now waiting for the Salt provisioning process to complete on this machine.
==> node-2:   This can take some time based on your network, disk, and cpu speed.
==> node-2: [ERROR   ] Command ['dnf', '-y', 'install', 'dnf-plugins-core', 'python-dnf-plugins-core'] failed with return code: 1
==> node-2: [ERROR   ] output: Last metadata expiration check: 0:01:24 ago on Tue May 31 16:08:29 2016.
==> node-2: Package dnf-plugins-core-0.1.21-2.fc23.noarch is already installed, skipping.
==> node-2: Error: package python3-dnf-plugins-core-0.1.21-2.fc23.noarch conflicts with python-dnf-plugins-core < 0.1.21-2.fc23 provided by python-dnf-plugins-core-0.1.13-1.fc23.noarch
==> node-2: (try to add '--allowerasing' to command line to replace conflicting packages)
==> node-2: [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/state.py", line 1564, in call
==> node-2:     **cdata['kwargs'])
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 872, in installed
==> node-2:     **kwargs)
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 243, in _find_install_targets
==> node-2:     cur_pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 723, in list_pkgs
==> node-2:     for pkginfo in _repoquery_pkginfo(list_cmd):
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 134, in _repoquery_pkginfo
==> node-2:     for line in _repoquery(repoquery_args):
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 228, in _repoquery
==> node-2:     _check_repoquery()
==> node-2:   File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 190, in _check_repoquery
==> node-2:     raise CommandExecutionError('Unable to install dnf-plugins-core')
...
```

**Comment by mikedanese** [comment] 2016-06-01 06:57
cc @derekwaynecarr

**Comment by bacongobbler** [comment] 2016-06-01 16:18
dupe of https://github.com/kubernetes/kubernetes/issues/26104

**Closed** 2016-06-01 16:28 UTC
Labels: area/platform/vagrant, team/none
