### ISSUE TITLE
node "NotReady" after "issues", all pods removed, containers keep running

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#30972] opened 2016-08-19 06:49 UTC
_note: this issue will contain very little to work with, but I wanted it reported nonetheless, please close this if this is already reported in greater detail elsewhere, I couldn't find a relevant issue_

This morning we encountered one of our three GKE nodes in "NotReady" state. Unfortunately, I don't have a `describe node` log anymore, so I can't really tell you anything, _except_ that there was this event:

```
  2h        10s        273    {controllermanager }                                NormalDeletingAllPods        Node gke-blendle-default-v2-default-v134-d8d4ff70-sdzq event: Deleting all Pods from Node gke-blendle-default-v2-default-v134-d8d4ff70-sdzq.
```

And doing a `kubectl describe node` showed that _only_ daemonset pods where still running on the node, all other pods where removed.

However, when ssh'ing to the node, we noticed (some) applications where actually still running (in their containers), even though they where supposed to be deleted/rescheduled.

This caused some critical applications that shouldn't run with more than one replica for too long, to run with two replicas, unnoticed, because one was "flying under the radar", no longer being managed by Kubernetes.

Again, sorry that this issue is so sparse of actual useful debugging information, but I thought the issue warranted a ticket, if only to see if others have seen this as well, and if the Kubernetes maintainers believe this a big enough issue to warrant further investigation.

Our GKE cluster is running master/nodes versions v1.3.4.

cc: @jurriaan

**Comment by dchen1107** [comment] 2016-08-19 17:14
@JeanMertz Thanks for reporting GKE issues. 

I believe you ran into a known problem, and there are a couple of issues filed against it. But I only find this one: https://github.com/kubernetes/kubernetes/issues/24200 In summary, the problem is caused by the networking issue between master and the rest of nodes which cause massive pod eviction. Original design is that the master evicts all pods on a node if it doesn't hear from the node in about 5 mins. Normally this design works until we hit the master network issue. 

We took several actions on to make GKE / Kubernetes master more resilient to correlated node failure:

* In 1.3 release, we introduced a protection to mitigate the issue, in which case, NodeController wouldn't evict all pods if all nodes are not ready. But this doesn't help with partial segmentation which reported by you here.
* In incoming 1.4 release, we introduced a new eviction logic to Kubernetes's node controller. But I didn't find the document on it. cc/ @davidopp, @matchstick 
* Also we are working on master HA solution for GKE, which should eliminate such issue in a long run.

**Comment by dchen1107** [comment] 2016-08-19 17:15
@gmarek I think you are the one working on #24200, am I right?

**Comment by davidopp** [comment] 2016-08-19 18:54
I didn't read the initial message in this thread so I can't comment on the diagnosis, but the mass eviction fixes are described in #28832 and are all finished.

**Comment by dchen1107** [comment] 2016-08-19 19:58
@davidopp Thanks for updating the status. I am closing this as dup of  #28832 for now.

@JeanMertz  I am closing this as dup of  #28832 for now. If you think they are different ones, please re-open it.

**Closed by dchen1107** 2016-08-19 19:58 UTC
Labels: component/nodecontroller, team/control-plane

**Comment by davidopp** [comment] 2016-08-21 05:27
I finally read the initial message. This isn't a bug. For some reason Kubelet started reporting NotReady. (That might be due to a bug, but it's not what you were asking about.) When a node has reported NotReady for more than 5 minutes, the node controller deletes all the pods except daemonset pods from the node's "intended state." That's why `kubectl describe node` showed that only daemonset pods were still supposed to be running on the node. `kuebctl describe node` does not report what is actually running on the node. Whether that intended state can be implemented by Kubelet is a separate issue -- apparently it wasn't possible, which is why the containers were still running on the node. ReplicationController/ReplicaSet does not guarantee that only a single instance of a container will be running at a time. If you want that behavior you need to write your own controller or do application-level locking to ensure that the replacement doesn't start up if the original one hasn't released the lock.
