### ISSUE TITLE
Enable multiple oidc-client support in api-server to support kubectl migration

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#87542] opened 2020-01-25 01:03 UTC
**What would you like to be added**:
kubectl's azure auth module would obtain an AAD token whose `audience` claim has undesired `spn:` prefix. This claim is used in kube-apiserver for oidc client ID verification. To support migration of kubectl to get token without `spn:` prefix, kube-apiserver needs to support multiple `oidc-client-id`

**Why is this needed**:
The original issue about Azure AD token is explained very well in #86410. In sort, the current azure auth module will get a token whose audience claim has spn: prefix. This prefix is not documented in most Azure AD documentation which causes confusion and blocks some scenario.

There was an attempt to update existing azure auth module in #86412 which resulted in a breaking behavior to existing k8s clusters using Azure AD OIDC. The issue is documented well in #87464. Hence, the #86412 PR is reverted in #87507.

As discussed in [here](https://github.com/kubernetes/kubernetes/issues/87464#issuecomment-577894188), a proper migration path to achieve #86410 with zero impact to existing clusters should be:

1. (client side change) implement two auth modules in kubectl. #87541
2. (server side change) update api server to support multiple --oidc-client-id
3. customers can opt in to update `--oidc-client-id=spn:<guid>;<guid>` so that kubectl in old and new can still authenticate with api-server
4. migrate kubectl to use new auth module
5. update `--oidc-client-id=<guid>`

This issue is to implement the second task: **(server side change) update api server to support multiple --oidc-client-id**

**Comment by mikedanese** [comment] 2020-01-25 22:09
duplicate of https://github.com/kubernetes/kubernetes/issues/71162

**Closed** 2020-02-05 19:47 UTC
Labels: kind/feature, sig/auth
