### ISSUE TITLE
hairpin.go should not set hairpin mode on all interfaces

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#21284] opened 2016-02-15 22:29 UTC
I0215 16:27:02.388241   27779 hairpin.go:51] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 15628: exit status 1: nsenter: cannot open /proc/15628/ns/net: No such file or directory
I0215 16:27:02.389035   27779 hairpin.go:99] Enabling hairpin on interface lo
I0215 16:27:02.389175   27779 hairpin.go:99] Enabling hairpin on interface eno1
I0215 16:27:02.389211   27779 hairpin.go:99] Enabling hairpin on interface virbr2
I0215 16:27:02.389268   27779 hairpin.go:99] Enabling hairpin on interface virbr2-nic
I0215 16:27:02.389516   27779 hairpin.go:99] Enabling hairpin on interface virbr1
I0215 16:27:02.391329   27779 hairpin.go:99] Enabling hairpin on interface virbr1-nic
I0215 16:27:02.391387   27779 hairpin.go:99] Enabling hairpin on interface virbr0
I0215 16:27:02.391440   27779 hairpin.go:99] Enabling hairpin on interface virbr0-nic
I0215 16:27:02.391565   27779 hairpin.go:99] Enabling hairpin on interface virbr4
I0215 16:27:02.391651   27779 hairpin.go:99] Enabling hairpin on interface virbr4-nic
I0215 16:27:02.391759   27779 hairpin.go:99] Enabling hairpin on interface virbr3
I0215 16:27:02.392191   27779 hairpin.go:99] Enabling hairpin on interface virbr3-nic
I0215 16:27:02.392405   27779 hairpin.go:99] Enabling hairpin on interface docker0
I0215 16:27:02.392498   27779 hairpin.go:99] Enabling hairpin on interface cbr0
I0215 16:27:02.392552   27779 hairpin.go:99] Enabling hairpin on interface veth31932af

This seems pretty wrong...

**Comment by AdoHe** [comment] 2016-02-16 02:37
@dcbw We have already discussed this problem, you can refer this #19766 for more detail. Besides what do you think about hairpin mode setting? We temporarily add a flag to control this #20883

**Comment by AdoHe** [comment] 2016-02-16 15:40
@dcbw can you provide the type of network interfaces? such as `virbr2` `virbr2-nic`

**Comment by dcbw** [comment] 2016-02-16 15:44
@AdoHe the issue isn't about setting hairpin mode in general, that's fine to do.  The issue is that when the interface to set hairpin mode on isn't available, it sets hairpin mode on *all* interfaces, especially ones it shouldn't, like interfaces that aren't in any way related to kubernetes or docker.

There are any number of reasons why the interface couldn't be found, usually related to docker being slow or the container having exited/failed by the time the hairpin mode code runs if kubernetes is loaded.

**Comment by AdoHe** [comment] 2016-02-16 15:49
@dcbw I did understand what you mean, the problem is the fallback mechanism. We are trying to find a better solution. And of course do you have any good idea about this?

**Comment by thockin** [comment] 2016-03-03 00:36
I am open to better answers here.  I guess this will alleviate itself as we move more logic down towards plugins.

**Comment by bboreham** [comment] 2016-12-18 09:01
Fixed by #36990

**Closed** 2017-01-13 05:45 UTC
Labels: sig/network, sig/node
