### ISSUE TITLE
finished cronjob does not have logs from stderr

### ISSUE THREAD

**Issue by linehrr** [kubernetes/kubernetes#89432] opened 2020-03-24 15:40 UTC
**What happened**:
After scheduled cron job finished, we can only get logs from stdout but there is no stderr.

**What you expected to happen**:
by doing `kubectl logs` on the finished pod, you will only see stdout, no stderr. 

**How to reproduce it (as minimally and precisely as possible)**:
this is the cron template we've used. 
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron
  namespace: default
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
```
after job finished, trying to do `kubectl logs` will only see stdout logs but no stderr. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: on premise
- OS (e.g: `cat /etc/os-release`): `centos7`
- Kernel (e.g. `uname -a`): `Linux nj-k8sma1c1 4.4.212-1.el7.elrepo.x86_64 #1 SMP Wed Jan 29 08:34:02 EST 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Canal
- Others:

**Comment by soltysh** [comment] 2020-06-03 13:33
The presence of stdout or stderr logs is unrelated to cronjob or job controller, but rather is dependant on the application running in a particular image. I'd suggest trying to run your image directly as a pod, using `kubectl run`, for example, and verifying whether you're able to see both stdout and stderr from the app itself. If you don't there are two possibilities:
1. your application is not producing logs at stderr
2. `kubectl logs` is broken, in which case please report a bug against https://github.com/kubernetes/kubectl/ repository since this is an issue either on the CLI side, or
3. the kubelet is broken that it does not forward the logs from the container which in most cases might mean that the container runtime is at fault.

I'd start from the top. For now I'm going to close this as this is not a bug for sig-apps.
/close

**Closed** 2020-06-03 13:33 UTC
Labels: kind/bug, sig/apps
