### ISSUE TITLE
Ensure that go.mod uses vendored dependencies with release tags

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#78434] opened 2019-05-28 11:22 UTC
Currently there are a lot of dependencies that we use picked from random SHA(s). There's a script that computes newer dependencies based on newer released versions/tags at:
https://gist.github.com/dims/c0857b86441442b15852a4c2355db130#file-gomod_staleness-py

The script generates a github markdown table, we look through the table at the "From" columns with random SHA(s) and see which ones have a decent looking release in the "To" column and try to update those.

Essentially we should run this script periodically and look at what we can update from a random SHA to a specific release.

While doing so, we should be mindful of not adding too many `replace` statements. We do this by running `hack/lint-dependencies.sh` which prints out hack/pin-dependency.sh for various dependencies (and then run hack/update-vendor.sh). we iterate through the combination of these scripts until we are left with just the golang.org/x/* repos which do not have release/tags.

/area code-organization

**Comment by dims** [comment] 2019-05-28 11:22
cc @liggitt @cblecker

**Comment by andrewsykim** [comment] 2019-07-11 18:29
/close 

Dupe of https://github.com/kubernetes/kubernetes/issues/79234

**Closed by andrewsykim** 2019-07-11 18:29 UTC
Labels: area/code-organization, kind/cleanup, sig/architecture
