### ISSUE TITLE
upgrading from v1.13.6 to v1.14.7 causes container restart unexpectedly

### ISSUE THREAD

**Issue by sstoner** [kubernetes/kubernetes#84443] opened 2019-10-28 10:54 UTC
**What happened**:

I have a kubernetes cluster with version v1.13.6 and I want to upgrade to v1.14.7 step by step, without the use of cluster lifecycle management tools like kubeadm.

Firstly, I upgrade apiserver, scheduler and controller-manager to v1.14.7 and cluster works well. Then I upgrade kubelet one by one. 

when I upgrade kubelet from v1.13.6 to v1.14.7, all processes containers restarted except pause containers.   

**What you expected to happen**:

do not restart  container when upgrading, because the Container struct does't changed. see: https://github.com/kubernetes/kubernetes/blob/abdda3f9fefa29172298a2e42f5102e777a8ec25/staging/src/k8s.io/api/core/v1/types.go#L2040

**How to reproduce it (as minimally and precisely as possible)**:

kubelet upgrade from 1.13.6 to v.14.7. you will see the situation.  

**Anything else we need to know?**:

kubelet logs: 
` Oct 28 16:24:42 172.22.10.204 kubelet[8429]: I1028 16:24:42.657180    8429 kuberuntime_manager.go:600] Container "kube-proxy" ({"docker" "5b685f7601d2ec0714de56d0fdab32a77d559064d38f5ebfcb2bf6b93f09db60"}) of pod proxy-rb2tm_kube-system(5628eef3-f6ce-11e9-8991-28a6db84a612): Container kube-proxy definition changed, will be restarted
`

**Environment**:

- Kubernetes version v1.14.7:
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): 4.14.0
- Install tools: 
- Network plugin and version (if this is a network-related bug): cni-bridge
- Others:
`docker version`: v1.18.8 and v1.18.9

**Comment by liggitt** [comment] 2019-10-28 16:00
The computation leading to that message is performed here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L446-L449

Prior to https://github.com/kubernetes/kubernetes/pull/57741 (shipped in 1.16), the container hash looked at all fields in the container struct type . That meant that any change to any type used within the container API type definition would trigger a container restart on upgrade.

In practice, since [upgrades are expected to drain nodes](https://github.com/kubernetes/website/issues/12326#issuecomment-461081737), which restarts all containers anyway, that wasn't particularly impactful, but the issue is resolved in 1.16.

/close

**Closed by liggitt** 2019-10-28 16:00 UTC
Labels: kind/bug, sig/node, sig/usability

**Comment by bboreham** [comment] 2019-12-12 10:20
I just tripped over this; I have another interest because bugfix kubernetes/kubernetes#57135 was blocked on the basis that Kubernetes should not restart all pods on an upgrade. 

I might resurrect that PR based on what is said here and in  https://github.com/kubernetes/website/issues/12326.
