### ISSUE TITLE
VMDK refuses to attach/delete

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#75738] opened 2019-03-26 19:02 UTC
**What happened**:

VMDKs provisioned by the Kubernetes VSphere Volume plugin on a VMFS datastore backed by a HP 3 PAR Storage Array refuse to attach to nodes, attach fails with "Failed to add disk" error.

```
  Warning  FailedAttachVolume  59s (x108 over 3h27m)   attachdetach-controller                 AttachVolume.Attach failed for volume "pvc-86e8a3f7-4c76-11e9-97c4-8a58e0908f3b" : Failed to add disk 'scsi0:1'.
```

We worked around this by provisioning new PVCs. But the problem is that the existing "bad" VMDKs also refuse to delete (by k8s, via govc, or via vcenter UI) -- delete fails with "error caused by file".

/sig vmware
/sig storage

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by divyenpatel** [comment] 2019-05-09 23:45
@saad-ali Is this disk attached to some other powered on VM. If this is the case, we can not attach it to another powered on VM, and also we can not delete this disk, until disk is detached from the VM.

You have mentioned that "We worked around this by provisioning new PVCs.", means issue is not happening on all disks created on HP 3 PAR Storage Array.

**Comment by saad-ali** [comment] 2019-05-17 19:12
Hi @divyenpatel thanks for your reply.

Correct. This only effected VMDKs not the entire storage array. Something happened in the cluster which put pressure on the VMs, as Kubernetes moved pods to address the resource issue, the disks refused to move.

The biggest problem was that we couldn't "unstick" the VMDKs after this. The only way out was to provision new disks and deleting VMs and then deleting the effected VMDKs. Is there any advice on how to handle this more gracefully when it happens? And under what conditions this may happen?

**Comment by divyenpatel** [comment] 2019-05-21 01:14
@saad-ali 

This situation needs to be automatically resolved by Kubernetes. For some reason when node VM is not responding due to resource pressure, pod should be scheduled to another node, and disks should be detached from node VM, even when kubelet on the node is not responsive. 

Even if you attempt to shutdown the node VM, disk never gets detached and new Pod remains in the `container creating` state. 
There was a KEP opened for this to handle this situation - https://github.com/kubernetes/enhancements/pull/719

Here is the work around you can execute to handle this situation without deleting PVs.

1. Power-off the node VM which is under the pressure and not responding.
2. Manually detach all PV disks, which are attached on the VM. and then delete the node from API server using `kubectl delete node node-name`.
3. Now disks should allowed to be attached to another node.

cc: @SandeepPissay

**Comment by SandeepPissay** [comment] 2019-05-31 00:51
> Something happened in the cluster which put pressure on the VMs, as Kubernetes moved pods to address the resource issue, the disks refused to move.

@saad-ali The vsphere in tree driver will detach from old node and attach to new node if it gets the callback from attach-detach controller. If the disk is already attached to a powered on node VM and if there is a request to attach the same disk to another VM, this would result in the "Failed to add disk 'scsi0:1'". So, there is something wrong going on here. 

Can you clarify what you mean by "pressure on the VMs"? Was the kubelet unresponsive or the entire guest OS/VM was unresponsive. From @divyenpatel update, if the disk never gets detached, it sounds like a kubernetes bug and there is already a KEP for that - kubernetes/enhancements#719. If that is the case here too, then this does not sound like a vsphere specific problem. I think it is worth testing various failure cases where the kubelet/node VM/disk access fails and what happens to the stateful app. Something we can test and find out.

**Comment by saad-ali** [comment] 2019-06-06 02:02
Thanks for the replies @SandeepPissay and @divyenpatel.

> Can you clarify what you mean by "pressure on the VMs"? 

ESX hosts were under provisioned. They were running 5 node VMs which were running "too many pods" with "huge app, huge call, and data processing". This caused the cluster be "very full" and "each node had limited ram remaining". Which caused DRS to try and re-balance the VMs and so there was lots of live migration going on.

> From @divyenpatel update, if the disk never gets detached, it sounds like a kubernetes bug and there is already a KEP for that - kubernetes/enhancements#719.

We are looking in to that issue (we had a meeting about it this morning). But, in this case, as far as I can tell Kubernetes did issue a detach for the disk from the first node:

```
W0325 16:26:01.175985       1 reconciler.go:235] attacherDetacher.DetachVolume started for volume "pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b" (UniqueName: "kubernetes.io/vsphere-volume/[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk") on node "beta-cluster1-577b45bbf-5lbnl" This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching
E0325 16:26:01.176305       1 attacher.go:259] Error checking if volume ("[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk") is already attached to current node ("beta-cluster1-577b45bbf-5lbnl"). Will continue and try detach anyway. err=No VM found
I0325 16:26:01.176401       1 vsphere.go:869] Node "beta-cluster1-577b45bbf-5lbnl" does not exist, disk [BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk is already detached from node.
I0325 16:26:01.176504       1 operation_generator.go:419] DetachVolume.Detach succeeded for volume "pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b" (UniqueName: "kubernetes.io/vsphere-volume/[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk") on node "beta-cluster1-577b45bbf-5lbnl" 
I0325 16:26:01.276256       1 reconciler.go:291] attacherDetacher.AttachVolume started for volume "pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b" (UniqueName: "kubernetes.io/vsphere-volume/[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk") from node "beta-cluster1-577b45bbf-q5r7f" 
E0325 16:27:40.387588       1 vsphere.go:821] Failed to attach disk: [BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk for node: beta-cluster1-577b45bbf-q5r7f. err: +Failed to add disk 'scsi0:3'.
E0325 16:27:40.387711       1 attacher.go:80] Error attaching volume "[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk" to node "beta-cluster1-577b45bbf-q5r7f": Failed to add disk 'scsi0:3'.
```

Based on the error, the detach succeeds because the VMDK "is already detached from node", but then attach still fails with "Failed to add disk". I guess that indicates that the VMDK is attached to a different node then what Kubernetes thinks??

**Comment by misterikkit** [comment] 2019-07-18 23:10
@saad-ali Based on my read of the logs, it seems as though k8s assumes the VMDK is detached *because* the node is not found.
```
E0325 16:26:01.176305       1 attacher.go:259] Error checking if volume ("[BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk") is already attached to current node ("beta-cluster1-577b45bbf-5lbnl"). Will continue and try detach anyway. err=No VM found
I0325 16:26:01.176401       1 vsphere.go:869] Node "beta-cluster1-577b45bbf-5lbnl" does not exist, disk [BER_HP3Par_01_SSD_01] kubevols/kubernetes-dynamic-pvc-3d74be39-4c14-11e9-97c4-8a58e0908f3b.vmdk is already detached from node.
```

To me this suggests that the node or VM became unavailable before we attempted to detach the disk, and it remained attached. @divyenpatel I would expect little to no downtime for vMotion - is it possible that the Node object was deleted and recreated during the migration?

**Comment by SandeepPissay** [comment] 2019-10-11 20:48
@divyenpatel can you root cause the issue in the code?

**Comment by Quantas** [comment] 2020-01-11 16:38
SImilar to https://github.com/kubernetes/kubernetes/issues/80040 can we remove stale lifecycle from this issue? @yastij

**Closed** 2020-03-11 17:52 UTC
Labels: area/provider/vmware, kind/bug, lifecycle/rotten, sig/storage
