### ISSUE TITLE
kube-proxy process silently hangs on one of nodes

### ISSUE THREAD

**Issue by shakhat** [kubernetes/kubernetes#38372] opened 2016-12-08 09:41 UTC
**Kubernetes version** (use `kubectl version`):
Kubernetes v1.4.3+coreos.0

**Environment**:
- **Cloud provider or hardware configuration**:
  6 bare-metal nodes
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`):
Linux node1 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
Kargo
- **Others**:
Calico 0.21

**What happened**:
There is a pod (OpenStack Keystone) that runs on node1 and a service associated with it. Initially the service is reachable from all nodes, e.g. request to http://keystone.ccp:5000/ replies with valid HTTP response.

Keystone pod is restarted, as result the pod gets different IP address, DNS record is updated to point to new address. However the service is not reachable from node2. 

The reason is in iptables rules not being updated:

_good node_
```
-A KUBE-SEP-MMRSUY2HT6SO3JN6 -s 10.247.61.227/32 -m comment --comment "ccp/keystone:5000" -j KUBE-MARK-MASQ
-A KUBE-SEP-MMRSUY2HT6SO3JN6 -p tcp -m comment --comment "ccp/keystone:5000" -m tcp -j DNAT --to-destination 10.247.61.227:5000`
```
_bad node_
```
-A KUBE-SEP-2FVN6OV734ACY4G4 -s 10.247.61.245/32 -m comment --comment "ccp/keystone:5000" -j KUBE-MARK-MASQ
-A KUBE-SEP-2FVN6OV734ACY4G4 -p tcp -m comment --comment "ccp/keystone:5000" -m tcp -j DNAT --to-destination 10.247.61.245:5000
```
and the service:
```
vagrant@node1:~$ kubectl get endpoints 
NAME              ENDPOINTS                   AGE
keystone          10.247.61.227:5000          7d
```
kube-proxy pod is running on all nodes and in ready state:
```
root@node1:~# kubectl --namespace kube-system get pods
NAME                                    READY     STATUS    RESTARTS   AGE
kube-proxy-node1                        1/1       Running   0          12d
kube-proxy-node2                        1/1       Running   0          12d
kube-proxy-node3                        1/1       Running   0          12d
```

lsof output shows that kube-proxy process has established connections to http://127.0.0.1:8080 (master address) and a number of open listen sockets. 

however strace shows that the process and all of its threads are in futex, the typical picture is:
```
[pid 12405] futex(0x7594868, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 12405] futex(0x7594868, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 12405] futex(0x7594868, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 12370] <... select resumed> )      = 0 (Timeout)
[pid 12405] futex(0x7594868, FUTEX_WAIT, 0, {0, 100000} <unfinished ...>
[pid 12370] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid 12405] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 12405] futex(0x7594868, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
```

the last messages in log file are:
```
{"log":"E1206 09:41:58.866601       1 proxier.go:1247] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 4 failed\n","stream":"stderr","time":"2016-12-06T09:41:58.86667315Z"}
{"log":")\n","stream":"stderr","time":"2016-12-06T09:41:58.866690737Z"}
{"log":"E1206 09:42:49.047532       1 proxier.go:1247] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 4 failed\n","stream":"stderr","time":"2016-12-06T09:42:49.047652912Z"}
{"log":")\n","stream":"stderr","time":"2016-12-06T09:42:49.047670622Z"}
{"log":"E1206 10:51:11.788331       1 proxier.go:1247] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 4 failed\n","stream":"stderr","time":"2016-12-06T10:51:11.788482453Z"}
{"log":")\n","stream":"stderr","time":"2016-12-06T10:51:11.788506419Z"}
```
note that logs from other (live) kube-proxy also have same complains about iptables-restore, so it may be not the issue.

**What you expected to happen**:
Kubernetes should somehow detect that kube-proxy hangs and stopped processing events. I'd expect automatic issue detection and restart of kube-proxy pod 

**How to reproduce it** (as minimally and precisely as possible):
The issue happened under very low load, overall number of pods is about 100, and about 20 services.

**Comment by ayasakov** [comment] 2017-01-17 15:36
Reproduced on my env. 

**Kubernetes version** :
Kubernetes v1.4.6+coreos.0

**Environment:**

- **Cloud provider or hardware configuration:**
200 bare-metal nodes
- ** Install tools: **
Kargo

`# PROBLEM: backend IPs for service IP are not updated on k8s worker node

# iptables -t nat -L -n -v | grep :9696 | grep DNAT
  228 13680 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ccp/neutron-server:9696 */ tcp to:10.242.219.192:9696
  232 13920 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ccp/neutron-server:9696 */ tcp to:10.255.199.242:9696
  253 15180 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ccp/neutron-server:9696 */ tcp to:10.242.219.242:9696

# ROOT CAUSE: kube-proxy got stuck on Jan 05 2017 (current date is Jan 17 2017)

# docker ps <KUBE_PROXY>
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     47670  0.0  0.0  20224  3064 ?        Ss   15:13   0:00 bash
root     47676  0.0  0.0  17496  2100 ?        R+   15:13   0:00  \_ ps afuxww
root         1 56.0  0.0 1912820 109436 ?      Ssl   2016 18766:36 /hyperkube proxy --v=2 --master=https://localhost:443 --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --bind-address=172.20.9.116 --cluster-cidr=10.240.0.0/12 --proxy-mode=iptables --masquerade-all
root     47669  0.0  0.0  45948  3256 ?        S    Jan05   0:00 iptables-restore --noflush --counters

# docker logs <KUBE_PROXY>
I0105 00:22:32.630030       1 proxier.go:706] Deleting connection tracking state for service IP 10.224.0.3, endpoint IP 10.251.126.65
I0105 00:24:13.239386       1 proxier.go:706] Deleting connection tracking state for service IP 10.224.0.3, endpoint IP 10.251.126.65

# SOLUTION: restart kube-proxy container`

**Comment by pskrzyns** [comment] 2017-02-02 16:14
cc @kubernetes/sig-network-bugs

**Comment by listomin** [comment] 2017-02-04 09:38
@ivan4th has investigated the issue and opened this discussion in golang project https://github.com/golang/go/issues/18925

**Comment by pigmej** [comment] 2017-02-08 11:33
https://github.com/ivan4th/hoseproxy This is small project by @ivan4th to reproduce that bug.

**Comment by dcbw** [comment] 2017-03-20 23:18
If kube-proxy is running containerized, then it could be a candidate for health-checks.  Otherwise, I think handling this is probably outside the scope of kube-proxy itself, and instead a general issue for various kubernetes components, not the proxy specifically.

Could we close this issue in favor of the Golang one, since hang seems to be a Go thing and not actually kube-proxy?

**Comment by equinox0815** [comment] 2017-04-03 09:52
We have a very similar problem with kubelet. An underlaying bug in go would explain this. Anyone else experiencing that issue with kubelet as well or is it just us?

**Comment by thockin** [comment] 2017-05-19 04:19
This looks like not a big in kube?

**Closed by thockin** 2017-05-19 04:19 UTC
Labels: sig/network

**Comment by r7vme** [comment] 2017-06-13 09:51
We had same issue at least two times.

**Comment by r0bj** [comment] 2017-06-13 14:59
@equinox0815 I have experienced this bug also with kubelet.
