### ISSUE TITLE
Broken test: [k8s.io] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24262] opened 2016-04-14 17:48 UTC
This isn't a flake, the test is just broken. Starting from here:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/1064/

https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1064/

```
14:41:13 
14:41:13 • Failure [289.101 seconds]
14:41:13 [k8s.io] SchedulerPredicates [Serial]
14:41:13 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:420
14:41:13   validates MaxPods limit number of pods that are allowed to run [Slow] [It]
14:41:13   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:266
14:41:13 
14:41:13   Not scheduled Pods: []api.Pod(nil)
14:41:13   Expected
14:41:13       <int>: 0
14:41:13   to equal
14:41:13       <int>: 1
14:41:13 
14:41:13   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:107
```

I guess maybe something dies while it is scheduling everything?

**Comment by lavalamp** [comment] 2016-04-14 17:49
@davidopp to triage. This is breaking kubernetes-e2e-gce-serial right now.

**Comment by david-mcmahon** [comment] 2016-04-18 18:29
kubernetes-e2e-gce-serial hasn't passed in several days.  This is a gating job for this week's release.

**Comment by dchen1107** [comment] 2016-04-18 19:05
I took a quick look at failed builds of kubernetes-e2e-gce-serial this morning, and all are caused by this very test. I quickly checked why and noticed that most of them are failed due to fluentd.

23:12:53 Apr 17 23:12:53.746: INFO: fluentd-elasticsearch-jenkins-e2e-minion-8ukz started at <nil> (0 container statuses recorded)

**Comment by david-mcmahon** [comment] 2016-04-21 21:58
kubernetes-e2e-gce-serial still not passing.  Are we going to pass on the alpha release tomorrow?
My understanding is that kubernetes-e2e-gce-serial is a gating job for a release. 
@zmerlynn @roberthbailey

**Comment by david-mcmahon** [comment] 2016-04-21 23:33
cc @krousey, (build cop for a couple of days), though the issue has been around for a couple of weeks.

**Comment by krousey** [comment] 2016-04-21 23:46
ping @davidopp

**Comment by davidopp** [comment] 2016-04-21 23:49
@gmarek can you take a look at this?

**Comment by gmarek** [comment] 2016-04-22 14:37
Yup. It's a real bug:
```
$kubectl describe node e2e-test-gmarek-minion-n7fh
...
Non-terminated Pods:		(111 in total)
...
```

**Comment by gmarek** [comment] 2016-04-22 14:43
My best guess is that it's caused by parallel computation of bindings, as number of Pods assigned to a Node is read from NodeInfo, not from the 'AssumedPods' struct. @hongchaodeng

**Comment by gmarek** [comment] 2016-04-22 14:52
The fun thing is that tests started to fail in this way on Apr 12th between 12:44 and 16:26 UTC and as far as I can tell nothing was merged in scheduler codebase back then.

**Comment by gmarek** [comment] 2016-04-22 14:53
Run 1038 is the last 'good' one that I was able to find.

**Comment by hongchaodeng** [comment] 2016-04-22 15:02
How can we reproduce it?

> $kubectl describe node e2e-test-gmarek-minion-n7fh
...
Non-terminated Pods:        (111 in total)

> My best guess is that it's caused by parallel computation of bindings, as number of Pods assigned to a Node is read from NodeInfo

@gmarek Can you help clarify more detailed what's happening?

**Comment by gmarek** [comment] 2016-04-22 15:04
Easily - just run MaxPods test - it reliably fails:). If you want to dig a bit deeper you can add `--delete-namespace=false` flag when running tests. 

Scheduler assigned 111 pods to a given node. It certainly *looks* like the binding issue, but as I wrote - nothing was merged at the time it started to fail.

**Comment by wojtek-t** [comment] 2016-04-22 15:33
But parallel binding wasn't merged at that point... so there has to be at least another issue.

**Comment by gmarek** [comment] 2016-04-22 15:35
Yeah - my point exactly. It may be that we were always broken and some environment change caused this.

**Comment by wojtek-t** [comment] 2016-04-22 15:41
hmm - take a look here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L425

it seems we are not checking the maxPods predicate at all.
It's only part of  PodFitsResources, which we aren't calling by default, I think.

**Comment by gmarek** [comment] 2016-04-22 15:42
They moved it here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L457

**Comment by gmarek** [comment] 2016-04-22 15:44
https://github.com/kubernetes/kubernetes/pull/20204 was merged at the time.

**Comment by gmarek** [comment] 2016-04-22 15:49
(I was looking in the wrong place when checking what was merged back then) - I'll try to revert it.

**Comment by gmarek** [comment] 2016-04-22 16:22
Yeah - #20204 broke our scheduler. Test for `maxPods` is not included in `podFitsResourcesInternal` which is currently only predicate registered (instead of `PodFitsResources`).

cc @davidopp @HaiyangDING @lavalamp

**Comment by lavalamp** [comment] 2016-04-22 17:39
Sounds like this could have been caught by a unit or integration test.

**Comment by gmarek** [comment] 2016-04-22 17:49
Yup - if you convince someone that rewriting SchedulerPredicates tests into integration ones is a P0 more important than other things, I'm happy to do it:) Or I can help someone.

**Closed** 2016-04-23 06:00 UTC
Labels: kind/flake, priority/P0, team/control-plane
