### ISSUE TITLE
Jenkins e2e node builder is failing

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#23878] opened 2016-04-05 18:09 UTC
Example PR:
https://github.com/kubernetes/kubernetes/pull/23876

/cc @kubernetes/goog-node @smarterclayton

**Comment by vishh** [comment] 2016-04-05 18:11
PR builder has been failing for a while now. cc @pwittrock

**Comment by pwittrock** [comment] 2016-04-06 23:08
Duplicate of #23873.

tl;dr: jenkins wasn't correctly flushing configs to disk and things broke when it restarted.

Marking as fixed

**Closed by pwittrock** 2016-04-06 23:08 UTC
Labels: priority/P0, team/node
