### ISSUE TITLE
Failed to set statusUpdateNeeded to needed true because nodeName="node-v1-test"  does not exist

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#42158] opened 2017-02-27 13:17 UTC
Noticed that in [here](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/40927/pull-kubernetes-unit/20362/build-log.txt), this part:
```
W0227 04:39:11.830] E0227 04:39:11.830126   21448 actual_state_of_world.go:461] Failed to set statusUpdateNeeded to needed true because nodeName="node-v1-test"  does not exist
W0227 04:39:11.830] E0227 04:39:11.830158   21448 actual_state_of_world.go:475] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="node-v1-test"  does not exist
I0227 04:39:11.931] node "node-v1-test" created
W0227 04:39:12.232] Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on nodes "node-v1-test": the object has been modified; please apply your changes to the latest version and try again
W0227 04:39:12.239] !!! [0227 04:39:12] Call tree:
W0227 04:39:12.241] !!! [0227 04:39:12]  1: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:2917 run_pod_tests(...)
```

@kubernetes/sig-node-bugs || @kubernetes/sig-storage-bugs can you have a look at it?

**Comment by ncdc** [comment] 2017-02-27 21:24
Dupe of #41892

**Closed by ncdc** 2017-02-27 21:24 UTC
Labels: kind/flake, sig/node, sig/storage

**Comment by wangycc** [comment] 2017-03-14 11:07
I am also the same problem

**Comment by dmnord** [comment] 2017-03-31 04:54
And me too! How to resolve this issue? Where can I get right documentation/description? :-(

**Comment by 2knarf** [comment] 2017-10-13 11:30
Same here.

**Comment by resouer** [comment] 2017-10-13 13:58
@2knarf This should be fixed in https://github.com/kubernetes/kubernetes/pull/43152 which is included in 1.7

Are you using the latest Kubernetes release?

**Comment by wangycc** [comment] 2018-01-30 10:43
@resouer Appears again in the 1.9.1 version.
```shell
[root@ip-10-101-2-181 ~]# tail -500f /data/logs/kubernetes/kube-controller-manager.ERROR
Log file created at: 2018/01/30 18:38:59
Running on machine: ip-10-101-2-181
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0130 18:38:59.082300   10461 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="ip-10-101-2-91.cn-north-1.compute.internal"  does not exist
E0130 18:38:59.082841   10461 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="ip-10-101-2-168.cn-north-1.compute.internal"  does not exist
E0130 18:38:59.082887   10461 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="ip-10-101-2-204.cn-north-1.compute.internal"  does not exist
```

**Comment by devenfan** [comment] 2018-02-04 14:48
Kuberntes 1.9.1

root@ubuntu-105:/var/log/kubernetes# tail -f kube-controller-manager.ERROR
Log file created at: 2018/02/04 22:44:19
Running on machine: ubuntu-105
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0204 22:44:19.133862    2013 core.go:73] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
E0204 22:44:29.316850    2013 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="ubuntu-64"  does not exist

**Comment by mritd** [comment] 2018-04-16 09:47
Same here.(1.10.0 when reboot controller manager)

**Comment by ncdc** [comment] 2018-04-16 14:12
Sorry, just noticed the updates on this issue.

The history on this issue is a little confusing. It was opened because a test failed in CI. While it **looks** like the failure was this:
```
W0227 04:39:11.830] E0227 04:39:11.830158   21448 actual_state_of_world.go:475] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="node-v1-test"  does not exist
```
it was actually this:
```
W0227 04:39:12.232] Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on nodes "node-v1-test": the object has been modified; please apply your changes to the latest version and try again
```

The test that failed was a `kubectl replace` call to replace a `node`. It failed because there was a conflict, and the apiserver was using stale data from its watch cache (filed as https://github.com/kubernetes/kubernetes/issues/41892). The fix was to fetch the latest version of the conflicted object, and then retry the operation (https://github.com/kubernetes/kubernetes/pull/43152).


As far as the `Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="node-v1-test"  does not exist` error, I assume that is unrelated to the stale watch cache data issue that has since been fixed.

We can either reopen this and repurpose it as a storage issue, or we can create a new one. Either is fine with me.

**Comment by mritd** [comment] 2018-04-17 00:44
On my 1.10.0 cluster (the three master nodes), when I try to restart the controller-manager component of a node, the controller-manager of other nodes will try to re-election. The controller-manager component logs after successful election will There is this warning message.

``` sh
Apr 16 17:47:46 test37.node hyperkube[7518]: W0416 17:47:46.152050    7518 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.
```

**Comment by mritd** [comment] 2018-04-17 00:58
I'm not sure about the cause of this problem, but it looks similar to the #49549 issue, this issue is mentioned through the #49567 PR fix; currently #49567 PR nobody is concerned about being closed.

**Comment by gabrielfsousa** [comment] 2018-05-16 15:13
v.1.10.2 has the problem too

```
 W0516 12:21:51.186408       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="app197" does not exist
W0516 12:21:51.186438       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="app198" does not exist
W0516 12:21:51.187172       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="app199" does not exist 
```

**Comment by primeroz** [comment] 2018-08-29 10:37
@ncdc @jingxu97  I still see the same issue on v1.11.2 , exact same output 

```
W0829 09:30:43.715195       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="worker-medium01" does not exist
W0829 09:30:43.715403       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master01" does not exist
W0829 09:30:43.715781       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master02" does not exist
W0829 09:30:43.715864       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master03" does not exist
W0829 09:30:43.716009       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="worker-medium02" does not exist
W0829 09:30:43.716221       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="worker-medium03" does not exist
```

Everytime my controller-manager restart / failover

**Comment by sharkymcdongles** [comment] 2019-02-27 12:57
I also still see this in 1.13.3.

`W0227 12:56:10.652298       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-4" does not exist
W0227 12:56:10.652355       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-7" does not exist
W0227 12:56:10.652391       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-13" does not exist
W0227 12:56:10.652441       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-6" does not exist
W0227 12:56:10.652477       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master-2" does not exist
W0227 12:56:10.652501       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-9" does not exist
W0227 12:56:10.652532       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master-0" does not exist
W0227 12:56:10.652554       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-0" does not exist
W0227 12:56:10.652608       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-5" does not exist
W0227 12:56:10.652674       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="master-1" does not exist
W0227 12:56:10.652712       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-12" does not exist
W0227 12:56:10.653014       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-3" does not exist
W0227 12:56:10.653038       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-14" does not exist
W0227 12:56:10.653054       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-2" does not exist
W0227 12:56:10.653075       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-11" does not exist
W0227 12:56:10.653086       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-1" does not exist
W0227 12:56:10.653097       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-8" does not exist
W0227 12:56:10.653110       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minion-10" does not exist
`

**Comment by Aisuko** [comment] 2021-12-03 07:36
Hi guys, I hit the same issue on v1.9. Is there more information can help us? We deployed operator which the reconcile conflict with kubernetes controller-manager? or the watch-list cache mechnism has some issue in some point can trigger?

**Comment by yxdwind** [comment] 2023-01-14 23:10
I had the same issue,I used v1.21.
