### ISSUE TITLE
Unable to use client certificates with etcd after change to new client

### ISSUE THREAD

**Issue by kshelton** [kubernetes/kubernetes#22498] opened 2016-03-04 03:50 UTC
When the switch to the new client occurred, client certificate support wasn't included.

**Comment by liggitt** [comment] 2016-03-04 14:23
dupe of https://github.com/kubernetes/kubernetes/issues/18760

**Closed by liggitt** 2016-03-04 14:23 UTC

**Comment by kshelton** [comment] 2016-03-04 16:04
I've been looking for an open issue/pr for this since December - strange how github search couldn't find it.

**Comment by lavalamp** [comment] 2016-03-04 23:05
Yeah, sorry it can be hard to find things.
