### ISSUE TITLE
[sig-auth] Advanced Audit should audit API calls flake

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#60777] opened 2018-03-05 08:28 UTC
```
test/e2e/auth/audit.go:60
Event auth.auditEvent{level:"Metadata", stage:"ResponseComplete", requestURI:"/api/v1/namespaces/e2e-tests-audit-jnlrb/secrets/audit-secret", verb:"get", code:200, user:"kubecfg", resource:"secrets", namespace:"e2e-tests-audit-jnlrb", requestObject:false, responseObject:false} not found!
Expected
    <bool>: false
to be true
test/e2e/auth/audit.go:676
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60728/pull-kubernetes-e2e-gce/24504/

@kubernetes/sig-auth-test-failures

**Comment by liggitt** [comment] 2018-03-05 12:19
Duplicate of https://github.com/kubernetes/kubernetes/issues/60719
/close

**Closed by liggitt** 2018-03-05 12:19 UTC
Labels: kind/flake, sig/auth
