### ISSUE TITLE
kube-up / kube-down cycle not cleaning up well enough

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#16164] opened 2015-10-23 17:06 UTC
Something is leaving a PD around and causing `kube-up` on GCE to block partway up (which is disruptive when you're trying to just create a cluster while grabbing coffee):

```
Looking for already existing resources
Persistent disk kubernetes-kube-system-kube-registry found.
Would you like to shut down the old cluster (call kube-down)? [y/N] 
Starting master and configuring firewalls
```

I've had this happen pretty consistently on a clean project, clean build, `kube-down` / `kube-up`. Seems like an easy bug to fix.

**Comment by runningwild** [comment] 2015-10-26 17:02
Since bug is fairly general I figured that I'd throw in that kube-down on GCE is also leaking forwarding rules and target pools.  I built kubernetes today and this problem is still happening.

GCE charges for forwarding rules, I had a bunch of them lying around this month and got charged $35 for them :-P

**Comment by quinton-hoole** [comment] 2015-12-15 21:08
Seems like a duplicate of "GCE: kube-down doesn't clean up all resources" #18375  ?
Closing this one as such.

**Closed by quinton-hoole** 2015-12-15 21:08 UTC
Labels: area/cluster-lifecycle, davidopp, priority/P1, team/control-plane
