### ISSUE TITLE
kubectl edit: no such file

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#22371] opened 2016-03-02 18:19 UTC
This used to work...

```
$ kubectl edit svc hostnames-3512299341
error: open /tmp/usr/local/google/home/thockin/src/kubernetes/_output/local/bin/linux/amd64/kubectl-edit-fplln.yaml: no such file or directory
```

**Comment by janetkuo** [comment] 2016-03-02 18:21
@kubernetes/kubectl

**Comment by janetkuo** [comment] 2016-03-02 18:38
Filed #22373 to fix this

**Comment by bgrant0607** [comment] 2016-03-02 20:51
Dupe of #22296

**Comment by janetkuo** [comment] 2016-03-03 00:44
cc @bprashanth @AdoHe from the dupe PR

**Closed** 2016-03-03 00:57 UTC
Labels: component/kubectl, priority/P0, team/ux
