### ISSUE TITLE
Replicaset not maintain desired instances of same pod 

### ISSUE THREAD

**Issue by mukulk2020** [kubernetes/kubernetes#94851] opened 2020-09-17 10:10 UTC
>kubectl run nginx --image nginx
pod/nginx created

>kubectl get pods --show-labels
NAME    READY   STATUS    RESTARTS   AGE   LABELS
nginx   1/1     Running   0          10s   run=nginx

>kubectl apply -f rs.yaml
replicaset.apps/rs01 created

>kubectl get pods --show-labels
NAME         READY   STATUS              RESTARTS   AGE   LABELS
nginx        1/1     Running             0          60s   run=nginx
rs01-fk8w5   0/1     ContainerCreating   0          4s    run=nginx
rs01-gpbbb   0/1     ContainerCreating   0          4s    run=nginx

>kubectl get pods --show-labels
NAME         READY   STATUS    RESTARTS   AGE   LABELS
nginx        1/1     Running   0          72s   run=nginx
rs01-fk8w5   1/1     Running   0          16s   run=nginx
rs01-gpbbb   1/1     Running   0          16s   run=nginx

===============re.yaml===========
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs01
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      # Run the nginx image
      - name: redis
        image: redis

================================

**Instead of creating 3 pods , replica set only create 2 pods **:

**What you expected to happen**:
It should run 3 pods of redis 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Kind : kind v0.7.0 go1.13.6 windows/amd64

**Comment by mukulk2020** [comment] 2020-09-17 10:13
> @mukulk2020: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

Please use #sig-scalability

**Comment by yashvardhan-kukreja** [comment] 2020-09-18 08:59
Hi @mukulk2020 .. I reran the YAML u sent, multiple times and it worked perfectly. Can u please retry to do so. The issue you faced might be due to issue while setting up the manifest. If you somehow still have this messy replicaset running on your cluster, the please execute `kubectl get rs rs01 -o yaml` and paste the resulting output here, so that we can dig deeply into exactly what was the issue causing only 2 pods to be generated in the first place.

------------
Just so that we are on the same page, I ran this YAML which is exactly same as yours
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs01
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      # Run the nginx image
      - name: redis
        image: redis
```

**Output:**
```
master $ kubectl get pods --watch
NAME         READY   STATUS    RESTARTS   AGE
rs01-6nhnz   1/1     Running   0          47s
rs01-98nxt   1/1     Running   0          47s
rs01-zlbs6   1/1     Running   0          47s
```
```
master $ kubectl get rs
NAME   DESIRED   CURRENT   READY   AGE
rs01   3         3         3       5m5s
```

**Comment by mukulk2020** [comment] 2020-09-18 09:06
I agreed you are right ....but follow the same steps that i mention ..first create a niginx pod with same label ...

**Comment by yashvardhan-kukreja** [comment] 2020-09-18 09:49
Oh yes, my bad. 
So, @mukulk2020 , I did what you said and noticed one thing that on running that command to spin up an nginx pod resulted in the following:
```
master $ kubectl get pods --show-labels
NAME         READY   STATUS    RESTARTS   AGE    LABELS
nginx        1/1     Running   0          2m2s   run=nginx
```
Clearly, we can see that it got assigned the label `run=nginx`
And clearly in the replicaSet's manifest, you told it to have finally 3 replicas matching the labels `run: nginx`.

So, basically, replicaSet's job is to "maintain" 3 pods (replicas) at any point of time rather than "creating" 3 pods (replicas). So, in this situation when you started the replicaSet, it already saw one pod with the label `run=nginx`, so all that replicaset had to do was to spin up 2 new pods as per the spec, so that finally, the cluster would end up having a state where there are 3 pods with the label `run=nginx`

Now, you might argue that one of the pods (the first nginx one) is different from the one defined in the template of replicaSet's YAML but actually, if you look in the kubernetes docs, you'll notice that replicaSet only through the labelSelector and hence, the pod's labels.

Hence, in our situation, although the first nginx pod (with nginx image) and the two replicaSet pods (with redis image in each) are different internally, still the replicaSet found them same coz of their same labels i.e. "run=nginx"

**Comment by yashvardhan-kukreja** [comment] 2020-09-18 10:06
I believe the most unexpected thing here was the nginx pod automatically getting assigned the label "run=nginx" despitew that being NOT necessary, which led to all this confusion.

**Comment by krmayankk** [comment] 2020-09-21 08:02
working as designed . thanks @yashvardhan-kukreja for helping out on this issue
@mukulk2020 closing this since as per explanation. K8s is a declarative api based system and is working as designed. If you still dont feel satisfied, please put your comments and we will try to address it
/close

**Closed** 2020-09-21 08:02 UTC
Labels: kind/bug, sig/apps
