### ISSUE TITLE
Invalid ThirdPartyResource SelfLink value

### ISSUE THREAD

**Issue by nilebox** [kubernetes/kubernetes#42304] opened 2017-03-01 03:04 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): SelfLink, ThirdPartyResource, TPR

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Mac OS X 10.12.3
- **Kernel** (e.g. `uname -a`):
- **Install tools**: minikube
- **Others**:

**What happened**:
When I create a ThirdPartyResource following an example from https://kubernetes.io/docs/user-guide/thirdpartyresources/ (or create any other TPR), the SelfLink in Kubernetes object is invalid (one slash is missing).

**What you expected to happen**:
SelfLink is valid

**How to reproduce it** (as minimally and precisely as possible):
1. Create resource.yaml with the contents from https://kubernetes.io/docs/user-guide/thirdpartyresources/ :
```apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1
```
2. Create TPR
`kubectl create -f resource.yaml`
3. Fetch the created TPR object in YAML format
`kubectl get thirdpartyresource/cron-tab.stable.example.com -o yaml`
4. The result is the following:
```apiVersion: extensions/v1beta1
description: A specification of a Pod to run on a cron style schedule
kind: ThirdPartyResource
metadata:
  creationTimestamp: 2017-03-01T02:50:53Z
  name: cron-tab.stable.example.com
  resourceVersion: "4070"
  selfLink: /apis/extensions/v1beta1/thirdpartyresourcescron-tab.stable.example.com
  uid: e32a6db3-fe29-11e6-80b0-080027fddb63
versions:
- name: v1
```
5. The SelfLink value is invalid: it should be `/apis/extensions/v1beta1/thirdpartyresources/cron-tab.stable.example.com` (One slash is missing after `thirdpartyresources`)

**Anything else we need to know**:

**Comment by liggitt** [comment] 2017-03-01 04:52
dupe of https://github.com/kubernetes/kubernetes/issues/37622

**Closed by liggitt** 2017-03-01 04:52 UTC
