### ISSUE TITLE
Deployment Pod Count does not reflect the actual count nor matches the current ReplicaSet status

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#42295] opened 2017-03-01 01:55 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `kubernetes deployment unavailable`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS Stable 1235.5.0
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**: Deployment status does not reflect actual pod status nor does match the current ReplicaSet status.

```
kubectl get deploy/myservice
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
myservice   3         3         3            2           40d

kubectl describe deploy/myservice
Name:                   myservice
Namespace:              production
CreationTimestamp:      Thu, 19 Jan 2017 12:25:28 -0800
Labels:                 name=myservice
Selector:               service=myservice
Replicas:               3 updated | 3 total | 2 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        10
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
OldReplicaSets: <none>
NewReplicaSet:  myservice-1214004771 (3/3 replicas created)
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set myservice-1214004771 to 1
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set myservice-2591046384 to 2
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set myservice-1214004771 to 2
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set myservice-2591046384 to 1
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set myservice-1214004771 to 3
  8m            8m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set myservice-2591046384 to 0

kubectl describe rs/myservice-1214004771
Name:           myservice-1214004771
Namespace:      production
Image(s):       myservice:0.1.118.d196d30
Selector:       pod-template-hash=1214004771,service=myservice
Labels:         pod-template-hash=1214004771
                service=myservice
Replicas:       3 current / 3 desired
Pods Status:    3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  config-volume:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       myservice-0.1.118
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  9m            9m              1       {replicaset-controller }                        Normal          SuccessfulCreate        Created pod: myservice-1214004771-l1j6s
  9m            9m              1       {replicaset-controller }                        Normal          SuccessfulCreate        Created pod: myservice-1214004771-064rw
  9m            9m              1       {replicaset-controller }                        Normal          SuccessfulCreate        Created pod: myservice-1214004771-24z5m

kubectl get pod -l service=myservice
NAME                        READY     STATUS    RESTARTS   AGE
myservice-1214004771-064rw   1/1       Running   0          10m
myservice-1214004771-24z5m   1/1       Running   0          10m
myservice-1214004771-l1j6s   1/1       Running   0          10m
```

**What you expected to happen**: Deployment status show correct count of AVAILABLE pods

**How to reproduce it** (as minimally and precisely as possible): Deploy a deployment with multiple replicas

**Anything else we need to know**:
Impacts `kubectl rollout status` 
```
Waiting for rollout to finish: 2 of 3 updated replicas are available...
```

**Comment by kargakis** [comment] 2017-03-02 11:07
Can you post the status of the replica set when this occurs? This is probably a dupe of https://github.com/kubernetes/kubernetes/issues/41641

**Comment by ichekrygin** [comment] 2017-03-02 14:55
@kargakis I don't think that is it, although could be related, because, I observed this to happen on the *very first* deployment. Either way, I will post an update on the next repro.

**Comment by kargakis** [comment] 2017-03-02 15:03
This issue is not related with the sequence of deployments. It's rather a timing issue in the replica set controller where sometimes replica sets using minReadySeconds won't be correctly updated (their status.availableReplicas field).

**Comment by kargakis** [comment] 2017-03-07 11:04
Closing as a dupe of #41641.

**Closed by kargakis** 2017-03-07 11:04 UTC

**Comment by djablonski** [comment] 2017-03-09 15:03
We also encountered this issue, and at least here we had ReplicaSets where the status of the pods was available for all of them, while the deployment still showed one og them as unavailable...
Should I create a new issue for this?
