### ISSUE TITLE
Confusion around node name: providerID, externalID 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#60466] opened 2018-02-27 00:52 UTC
Currently both node_controller in cloudprovider and node_life_cycle controller checks whether node exists in cloudprovider or not. They are using different ways of checking the cloudprovider.
node_controlelr: InstanceExistsByProviderID by passing node's providerID. If there is an error, it will try to use ExternalID()
node_lifecycle_controller: Uses ExternalID() by passing nodeName.

However, according to this PR https://github.com/kubernetes/kubernetes/pull/7775, ExternalID is marked as deprecated three years ago. Should we continue to use this way?

cc @yujuhong @Random-Liu

**Comment by zetaab** [comment] 2018-02-27 05:03
If I have understood this cloud controller manager is the newest and is going to be use "only solution" in future? So I would say that we should not use deprecated feature anymore.

**Also I have one question:**
why cloud node controller is deleting nodes from cluster if we like reboot those. https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L148

Imo we should not delete nodes from if there is possibility that same node can return. The problem is that if we want to add some custom things like taints and labels to nodes, then reboot is removing these things. Currently we have own operator which will add these labels and taints after node is re-registered. node lifecycle controller is working in different way, it is not removing these in AWS (and I hope that openstack part of it is moving to that direction in https://github.com/kubernetes/kubernetes/pull/59931

**Comment by yujuhong** [comment] 2018-02-27 21:59
> However, according to this PR #7775, ExternalID is marked as deprecated three years ago. Should we continue to use this way?

Looks like https://github.com/kubernetes/kubernetes/pull/7775/files#r31184254 never happened.
@bgrant0607 @roberthbailey do we want to clean up the use of ExternalID in our codebase?

**Comment by adnavare** [comment] 2018-02-28 02:16
I can assign this issue to myself if no one is assigned? @jingxu97: is there any progress on this?

**Comment by adnavare** [comment] 2018-02-28 18:37
I see that ExternalID() calls <cloudProviderObject>.InstanceID() and InstanceExistsByProviderID() also calls <cloudProviderObject>.InstanceID(). In my opinion, it does't make sense to still have ExternalID() one, it is deprecated and other, it is just another layer of redirection. Please guide me if I am wrong

**Closed** 2018-04-09 18:58 UTC
Labels: area/node-lifecycle, area/nodecontroller, sig/node
