### ISSUE TITLE
 ssh_exchange_identification     One night later 

### ISSUE THREAD

**Issue by fanhongli** [kubernetes/kubernetes#50585] opened 2017-08-14 03:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: yes 

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:  ssh_exchange_identification

**What you expected to happen**: no  ssh_exchange_identification

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

**Environment**: centos7
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: 
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):

Linux dc232 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:  kubeadm 

- Others:

**Comment by zhangxiaoyu-zidif** [comment] 2017-08-14 10:02
you mean that you must use password to access from one node to anther by ssh.
And this situation occured after installing the cluster.
Some network env. or hostnames changed?

**Comment by fanhongli** [comment] 2017-08-15 01:13
nothing changed , i have to restart machine

**Comment by fanhongli** [comment] 2017-08-16 01:30
i think the dashboard have same thing wrong 

yesterday i did not start   dashboard  

nohup kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' >> dashboard.out &

my machine no need to restart again .

**Comment by cblecker** [comment] 2017-08-18 23:52
Duplicate of https://github.com/kubernetes/kube-ui/issues/59
/close

**Closed by cblecker** 2017-08-18 23:52 UTC
Labels: needs-sig
