### ISSUE TITLE
kubectl apply fails because "invalid: metadata.annotations: Too long: must have at most 262144 bytes"

### ISSUE THREAD

**Issue by nyarly** [kubernetes/kubernetes#100572] opened 2021-03-26 01:16 UTC
#### What happened:

I'm attempting to incorporate Strimzi into our cluster configuration. Our process is GitOps style: specifically, we build a declarative configuration in code, and then `kubectl apply` the whole thing. I got the error referenced here:
https://github.com/strimzi/strimzi-kafka-operator/issues/4589

The Strimzi project's solution is to use `kubectl create` for the one CRD, which would be reasonable if I was catering to a single cluster.

#### What you expected to happen:

`kubectl apply` to succeed.

#### How to reproduce it (as minimally and precisely as possible):

Pull down the Strimzi 0.22.1 Kafkas CRD, and attempt to `apply` it.

#### Anything else we need to know?:

This is a general limit on the size of any Kubernetes resource for `apply`. I understand in passing it has to do with the way in which `apply` annotates the resource with its own previous applied state interacting with etcd limits. It seems like this is a bug in Kubernetes, however, since it expects something from its datastore that isn't available. 

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-gke.1501", GitCommit:"de67bb0d58413ba2ba9b64810ab438a9734a2ab9", GitTreeState:"clean", BuildDate:"2021-02-26T23:41:52Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Ubuntu

**Comment by pacoxu** [comment] 2021-03-26 03:50
It should be similar to https://github.com/kubernetes/kubectl/issues/712.

**Comment by liggitt** [comment] 2021-03-26 04:57
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/82292

**Closed by liggitt** 2021-03-26 04:57 UTC
Labels: kind/bug, needs-triage, sig/api-machinery, sig/cli
