### ISSUE TITLE
After the installation of kubernetes 1.4.3 on CentOS7.2, failed to reboot the host

### ISSUE THREAD

**Issue by vincentwu2011** [kubernetes/kubernetes#40273] opened 2017-01-22 15:07 UTC
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:20:04Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
   kubernes are installed on a Virtual Machine.
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux  4.7.3-1.el7.elrepo.x86_64 #1 SMP Wed Sep 7 13:19:00 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
the kubernetes are deployed following guide https://github.com/kubernetes/kube-deploy/tree/master/docker-multinode.

- **Others**:
NFS persistent volumes are created on kubernetes cluster. And NFS persistent volume are consumed in some pods.

**What happened**:
after the kubenetes installation,  all the pods, service, PV, PVC, DNS, ... work fine. But it's failed to reboot the server. it seems reboot hangs on a specified step relevant with NFS. 
on the console of VMware Sphere, the log of VM as below:
...
[ OK ] Unmounted /run/docker/netns/0db421da098a.
[ OK ] Unmounted /opt/kubernetes/data/docker/contain...0df9c0be917bd506d42209fb4b6337c/shm
[ OK ] Unmounted /run/docker/netns/32a95753d81d.
[ OK ] Unmounted /opt/kubernetes/data/docker/contain...796965ac71e1f1fdf070a95389ec840/shm
[ OK ] Unmounted /run/docker/netns/52e14e816550.
[ OK ] Unmounted /opt/kubernetes/data/docker/contain...ce8ab0000ec45741c8f16ec421c0518/shm
[ OK ] Unmounted /run/docker/netns/65ad0a0051a9.
[ OK ] Unmounted /opt/kubernetes/data/docker/contain...4c4fa6f450c9b137ad6cd913deb491e/shm
[ OK ] Stopped Docker Application Container Engine.
          Stoppping Docker Application Container Engine...
[ OK ] Unmounted /opt/kubernetes/data/docker-boostrap/contain...e3e62ad57511fc39e11b03f93ccf1466/shm
[ OK ] Unmounted /opt/kubernetes/data/docker-boostrap/contain...8d6ca3ba3deb1241013b9295c53720/shm
[ OK ] Unmounted /opt/kubernetes/data/docker-boostrap/contain...da4d98300dcfb45a4a88cd2aee2bb78/shm
[ OK ] Unmounted /opt/kubernetes/data/docker-bootstrap/devicemapper.
[ OK ] Stopped Docker Application Container Engine.
[      *  ] (2 of 7) A stop job is running for /var/lib/k...bernetes.io~nfs/nfs-vol (2min37s /3min)

Notes: nfs-vol is the PV name created on this env.

**What you expected to happen**:
the server should be reboot successfully.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

the yaml file for PV and PVC as below:
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-vol
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/vols/nfs/core
    server: xx.xx.xx.xx

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-vol-claim
  namespace: core
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
        kubernetes.io/cluster-service: "true"

And here is yaml file example that how NFS volume is consumed:

...
        volumeMounts:
        - name: db-store
          mountPath: /var/pgdata
          subPath: platform-1.0/dm_db
      volumes:
      - name: db-store
        persistentVolumeClaim:
          claimName: nfs-vol-claim
...

**Comment by mnowrot** [comment] 2017-02-21 14:01
I'm facing the very same issue but on Kubernetes v1.5.2 running on CoreOS 1235.9.0. @vincentwu2011 did you perhaps manage to find a solution?

**Comment by mnowrot** [comment] 2017-02-22 08:22
@vincentwu2011 I've found a solution to this - in my case the root cause was NFS shutting down before Kubernetes. As I'm using hyperkube to deploy Kubernetes, I've set the services up so NFS waits for Docker shutdown before initiating its own shutdown and that solved the problem.

**Comment by spzala** [comment] 2017-09-28 01:04
@vincentwu2011 hi, can you please check if the solution provided by @mnowrot works for you since you ran into a similar problem as his with NFS? If so we can close this issue. @mnowrot thanks for your solution.

**Closed** 2018-03-12 04:15 UTC
Labels: lifecycle/rotten, sig/storage

**Comment by zhucan** [comment] 2019-12-10 07:21
> @vincentwu2011 I've found a solution to this - in my case the root cause was NFS server shutting down before Kubernetes. As I'm using hyperkube to deploy Kubernetes, I've set the services up so NFS server waits for Docker shutdown before initiating its own shutdown and that solved the problem.

If I use iscsi, whether I can set iscsi service after the docker service?

**Comment by zhucan** [comment] 2019-12-10 07:38
@mnowrot  Can you paste your solution?

**Comment by mnowrot** [comment] 2019-12-18 16:06
> 
> 
> @mnowrot Can you paste your solution?

Not really, as I don't have access to it any more. IIRC it boiled down to creating a drop-in file to systemd configuration of a docker service, making it dependent on nfsd. Something like:

```
[Unit]
Requires=nfsd.service
After=nfsd.service
```
