### ISSUE TITLE
podAntiAffinity namespace defaults to all, not current as documented

### ISSUE THREAD

**Issue by erikgrinaker** [kubernetes/kubernetes#45484] opened 2017-05-08 11:38 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): podAntiAffinity namespaces

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): cos 57 build 9202.64.0
- **Kernel** (e.g. `uname -a`): 4.4.35
- **Install tools**:
- **Others**:

**What happened**:

Created two deployments with same podAntiAffinity rules in different namespaces. Did not specify `namespaces` field for affinity rules. Pods in second namespace failed to schedule due to conflicts with pods in first namespace. Had to explicitly set `namespaces` field to allow scheduling.

**What you expected to happen**:

The `namespaces` field should default to the current namespace, as [documented](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature). Instead, it defaults to all namespaces.

**How to reproduce it** (as minimally and precisely as possible):

Consider the following deployment, which runs 2 Nginx pods that may not be scheduled onto the same node:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values: [nginx]
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

Create a cluster with 3 nodes, and apply the above manifest to two namespaces:

```sh
$ gcloud container clusters create --cluster-version 1.6.2 -m n1-standard-1 --num-nodes 3 test
$ kubectl apply -f nginx.yaml
$ kubectl create namespace other
$ kubectl -n other apply -f nginx.yaml
```

One of the pods in the second namespace will fail to be scheduled, even though the pod anti-affinity rules should only apply within the current namespace by default:

```sh
$ kubectl -n other get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-2407780625-15jkz   0/1       Pending   0          1m
nginx-2407780625-8m7h2   1/1       Running   0          1m

$ kubectl -n other describe pod nginx-2407780625-15jkz
[...]
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  8m		15s		34	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: MatchInterPodAffinity (3).
```

**Anything else we need to know**:

There is an open issue for this in the documentation repo:

https://github.com/kubernetes/kubernetes.github.io/issues/2676

However, I believe this is a bug with the implementation, as the code also states that it should default to current namespace:

https://github.com/kubernetes/kubernetes/blob/e443277d58e3ff1f0701ab97a1f4932389c27847/pkg/api/types.go#L1904-L1906

**Comment by suyogbarve** [comment] 2017-05-12 04:22
I can definitely recreate this issue in gke, however not able to reproduce it using test case

https://github.com/suyogbarve/k8stests/blob/master/bug_test.go

Any suggestions what is missing here? Above test case always Passes

**Comment by suyogbarve** [comment] 2017-05-13 05:05
This issue is already resolved after following commit 
https://github.com/kubernetes/kubernetes/commit/15c492bb2ea92d617db6681c09e095f4cad5456a#diff-fa4312d87a8e13262ade8a784ada4693
I have verified using latest kube-scheduler
/assign @wojtek-t

**Comment by erikgrinaker** [comment] 2017-05-13 13:13
Great, many thanks!

**Comment by wojtek-t** [comment] 2017-05-15 12:52
Yup - it should be solved at head.

@davidopp - should we backport it to 1.6. branch?

**Comment by davidopp** [comment] 2017-05-17 16:53
> should we backport it to 1.6. branch?

Yes, I think so. Can someone do it?

**Comment by wojtek-t** [comment] 2017-05-17 17:54
> Yes, I think so. Can someone do it?

@davidopp - will do tomorrow

**Comment by wojtek-t** [comment] 2017-05-18 18:01
@davidopp - actually, we already cherrypicked it in: https://github.com/kubernetes/kubernetes/pull/45352

**Comment by wojtek-t** [comment] 2017-05-26 08:50
I'm closing this one, since it is already fixed at head and cherrypicked to 1.6 branch.

**Closed by wojtek-t** 2017-05-26 08:50 UTC
Labels: sig/api-machinery, sig/scheduling

**Comment by gmflau** [comment] 2017-12-10 15:56
Is podAntiAffinity feature available in StatefulSets?

**Comment by davidopp** [comment] 2017-12-10 19:46
It should work with any pods regardless of how they are created.
