### ISSUE TITLE
Add a client/server implementation of the container runtime

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#13768] opened 2015-09-09 22:10 UTC
Currently, any container runtime has to be linked into the kubelet.  This makes experimentation difficult, and prevents users from landing an alternate container runtime without landing code in core kubernetes.

To facilitate experimentation and to enable user choice, we should add a client/server implementation of the container runtime interface. 

This implementation will simply encode the requests, send them to a server where they will be decoded and sent into an instance of the container runtime interface.

However, this enables container runtime implementations to be built and maintained outside of the core kubernetes tree.

@dchen1107 @smarterclayton 
@kubernetes/goog-node

**Comment by smarterclayton** [comment] 2015-09-09 22:12
@kubernetes/rh-cluster-infra

**Comment by brendandburns** [comment] 2015-09-09 22:14
@feiskyer

**Comment by bgrant0607** [comment] 2015-09-09 22:42
cc @thockin re. consistency and interaction with network and storage plugins

**Comment by vishh** [comment] 2015-09-09 23:03
We have two kinds of runtime abstractions in kubelet as of now - docker which operates at the container level, and rocket which operates at the pod level. Are we planning to expose both pod and container runtime plugins?

**Comment by yujuhong** [comment] 2015-09-09 23:13
> We need two kinds of runtime abstractions in kubelet as of now - one for docker which operates at the container level, and another for rocket which operates at the pod level. Are we planning to expose both pod and container runtime plugins?

I think we need to redefine the abstraction (container runtime interface) if we are going to expose it. We may need to ask `rkt` to expose a container-level api to work with kubelet, since most container runtimes operate at that level. That said, kubelet still relies on the container runtime (docker or rkt) to save pod level information (e.g., what pod a container belongs to), so a container runtime would still need to be aware of the existence of pod.

Also, I am working a pod event generator (#12802) for kubelet's performance improvement, so I'd appreciate to be kept in the loop for related changes :)

**Comment by feiskyer** [comment] 2015-09-10 01:04
> I think we need to redefine the abstraction (container runtime interface) if we are going to expose it. We may need to ask rkt to expose a container-level api to work with kubelet, since most container runtimes operate at that level. That said, kubelet still relies on the container runtime (docker or rkt) to save pod level information (e.g., what pod a container belongs to), so a container runtime would still need to be aware of the existence of pod.

I think we should provides both pod-level and container-level api to work with kubelet. As you say, container runtime must be aware of the existence of pod, so apis like creating and deleting pod should be pod-level. But other apis like exec/logs/attach should be container-level since they operates directly on container.

**Comment by yujuhong** [comment] 2015-09-10 01:54
The upside of keeping a container-level api is that we can keep the majority of the logic in kubelet, which would reduce code duplication and maintenance overhead.
I think we can maybe get away by passing pod UID & name as arguments when querying the runtime, if necessary. I need to think more about it.

/cc @yifan-gu for rkt.

**Comment by feiskyer** [comment] 2015-09-10 02:25
@yujuhong Rkt and hyper ( at #13079 ) are both operating at pod-level, their concept is consistent with kubernetes' pod. I think it's a good idea to reuse their pod apis in kubernetes, not split them into container-level.

**Comment by brendandburns** [comment] 2015-09-10 03:12
We currently have an exiting interface [`Runtime`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L53)

that both Docker and RKT implement.

I'm suggesting a network client/server version of that interface.

We can refactor/rewrite to our hearts content, but those refactors will just refactor the client/server interface also.

--brendan

**Comment by thockin** [comment] 2015-09-10 04:17
+1 to the idea

I don't see why we would keep any container-centric API.  The abstraction
is pods.  If a given runtime has to jump through hoops to implement pods
(I'm looking at you, docker) that their own problem.

**Comment by brendandburns** [comment] 2015-09-10 16:39
100% agree, the `Runtime` interface is Pod based, that's what we should have people implement.

**Comment by yifan-gu** [comment] 2015-09-10 18:33
+1 for the direction.

The core of the runtime interface is the `SyncPod()`, which the container runtime does the reconciliation in it. This is a bad abstraction as it hands to much work to container runtime and results in much code duplication.

Ideally container runtime should just implement `RunPod()`, `KillPod()`, and the kubelet should tell it which action to take during reconciliation. The trade-off is we will not be able to update a single container in a pod, that is if a pod has two containers and one of the container spec changes, then the other one will be killed as well.

**Comment by yifan-gu** [comment] 2015-09-10 18:53
Besides, i would suggest using grpc as
- No encoding/decoding codes needed to be written. 
- It is supposed to be faster than json ([though currently it's not](https://github.com/grpc/grpc-go/issues/89) :( ) 
- We can get client bindings for free.
- Server interfaces are generated as well. Each runtime only needs to implement them.

**Comment by yujuhong** [comment] 2015-09-10 19:02
> We currently have an exiting interface Runtime (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L53)

That's the interface I talked about, which was defined in a rush of time and needed to be polished (reiterated) more. I have filed issues before for that, and as @yifan-gu mentioned, even at pod-level abstraction there are many obvious imperfections.
I agree that client-server architecture is good in the long run. It's also important that we work towards a good API before committing and exposing the it for public consumption.

**Comment by yujuhong** [comment] 2015-09-10 19:05
> 100% agree, the Runtime interface is Pod based, that's what we should have people implement.

Not that I am against pod-level abstraction, but this alone is not the best argument IMO. We still have code (container garbage collection, image management, etc) bypassing the interface to talk to docker directly for direct container information. We should work out the requirements and fix the interface.

**Comment by pmorie** [comment] 2015-09-11 00:55
+1 to this direction

**Comment by feiskyer** [comment] 2015-09-11 06:49
I notice there are three places talking directly to dockerclient out of runtime: 

* `container garbage collection`
* `image management`
* `securitycontext`

I suggest move `securitycontext` to docker itself as it is only docker related.

For `container garbage collection` and `image management`, I suggest refactor them talking to `Runtime` interface instead.

**Comment by thockin** [comment] 2015-09-15 05:43
Yu-Ju,

There's certainly leaks in the abstraction, but if you consider something
like rkt or hyper, a container interface doesn't make much sense.
Everything that is more granular than a pod should be encapsulated behind
the pod interface.

The core of kubelet should only know about pods and abstract containers,
and nothing about the details of the runtime.  Garbage collection is the
runtime's problem.

I understand that this may not be the case right now :)

**Comment by yifan-gu** [comment] 2015-09-15 18:35
@yujuhong I think this is also something we need to consider when implementing the event generator in #13571

**Comment by yujuhong** [comment] 2015-09-15 23:06
> Yu-Ju,
> 
> There's certainly leaks in the abstraction, but if you consider something
> like rkt or hyper, a container interface doesn't make much sense.
> Everything that is more granular than a pod should be encapsulated behind
> the pod interface.

Hmm...I wasn't actually advocating the container-level abstraction. I brought it up because @dchen1107 mentioned it the other day, and I thought it was worth throwing into the discussion :)

> 
> The core of kubelet should only know about pods and abstract containers,
> and nothing about the details of the runtime.  Garbage collection is the
> runtime's problem.
> 
> I understand that this may not be the case right now :)

Agreed, but at the same time it seems like we want to have tighter control over disk space allocation and garbage collection, so the interface may not be as high-level as we want.
(@vishh would probably know more about the requirements)
These are probably some indications that we need to put into more thoughts or wait until we can have a more mature interface for the client-server architecture.

**Comment by yujuhong** [comment] 2015-09-15 23:13
> @yujuhong I think this is also something we need to consider when implementing the event generator in #13571

Agreed. For now, the generic event in generator #13571 uses the runtime interface to support container runtimes that don't support container/pod event streams. It shouldn't be too hard to adapt that to the new interface, or to implement the client-server architecture. For container runtimes which do support container event streams, they can implement one on their own.

**Comment by yifan-gu** [comment] 2015-09-15 23:50
@yujuhong By what I said I mean we might need to add pod level events. And in most of the time kubelet should only manage on pod level events. The container events should be handled by runtime according to the restartpolicy. However I tend to agree that container level events/interfaces are also necessary if we want to provide some fine grain introspection. (e.g. get per container's log, status etc). Though I am trying to think if we can just include these in the pod level events/interfaces..

**Comment by yujuhong** [comment] 2015-09-16 01:02
@yifan-gu, the current container events are packaged as pod-level events, even though they include some container information (ContainerStarted, etc). Having individual runtime handles all container-level events is a separate question though. If kubelet can fire and forget a pod without babysitting it, we may not even need pod-level events (other than maybe sending the pod status to the apiserver)  :)

**Comment by feiskyer** [comment] 2015-09-16 11:20
@brendandburns  Image manager refactored for client/server implementation of the container runtime.

**Comment by jdef** [comment] 2015-09-24 21:30
+1 for this. The mesos team is thinking of implementing a runtime for better integration with the mesos-native containerizer.

**Comment by smarterclayton** [comment] 2015-09-24 21:39
I see some significant downsides to client/server, including more hops into the container for exec/attach/portforward scenarios.  I do think that we should support a client/server containerizer, but for the foreseeable future I would want my containerizer compiled in if I was shipping a deployment.  

Conditionally compiled Kubelets provided with a particular host type (mesos, rocket, systemd+docker) has the same benefits without adding an extra hop.

**Comment by dchen1107** [comment] 2015-09-24 23:50
@smarterclayton inefficiency caused by client/server runtime is known. But please note that we didn't plan to make all container runtimes to use this model, and we do plan to continue supporting docker and rocket as Container Runtime as today, just with a better API. 

The only candidate we have today for this client / server model is hyper: 
https://github.com/kubernetes/kubernetes/pull/13079#issuecomment-139057198

**Comment by feiskyer** [comment] 2015-09-25 01:04
@dchen1107 @brendandburns I'm sorry, I thought client/server runtime is for all container runtimes.

**Comment by resouer** [comment] 2015-10-13 09:51
@brendandburns I'm interested in whether `runc` suitable for this model?

**Comment by vishh** [comment] 2015-10-13 17:24
`runc` is essentially a thin wrapper around the Linux APIs as of now. And
so, I don't think it will be a suitable candidate for being a container
runtime, at-least in its initial versions.

**Comment by resouer** [comment] 2015-10-16 06:34
@vishh agreed. Actually, I am keeping a close eye on docker 1.9, which has the same intention.

**Comment by feiskyer** [comment] 2015-11-11 13:39
@brendandburns @dchen1107 Filed design for client/server implementation of the container runtime at #17048

**Comment by feiskyer** [comment] 2016-03-23 07:21
@resouer have drafted a simple POC (in terms of `logs` api) to compare the performance penalty between client-server mode and compiled in mode. The POC is at [here](https://gist.github.com/resouer/112448583601f452a80f) and the evaluation results is [here](https://docs.google.com/spreadsheets/d/1w1OQ0eoRJvIt4QxsZyKV7-h-hXldpLgDU8_wKZgKm0g/edit?pref=2&pli=1#gid=0).

The results is: there are 17%-30% extra penalty with client-server mode. 

So complied in mode is more preferable for new container runtimes.

CC @brendandburns @dchen1107 @smarterclayton @kubernetes/sig-node

**Comment by yujuhong** [comment] 2017-06-02 01:08
We already implemented CRI and using it by default in 1.6. Closing.

**Closed by yujuhong** 2017-06-02 01:08 UTC
Labels: area/extensibility, priority/awaiting-more-evidence, sig/node
