### ISSUE TITLE
e2e parallel suite timed out

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18280] opened 2015-12-07 09:08 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12507/

cc @wojtek-t @dchen1107 @yujuhong

**Comment by yujuhong** [comment] 2015-12-07 16:15
It seems to me that the entire build timed out while no individual test failed or timed out.

**Comment by gmarek** [comment] 2015-12-07 16:49
Yup, but it looks like this:
```
22:57:00 • [SLOW TEST:9.061 seconds]
22:57:00 Docker Containers
22:57:00 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/docker_containers.go:72
22:57:00   should be able to override the image's default commmand (docker entrypoint) [Conformance]
22:57:00   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/docker_containers.go:61
22:57:00 ------------------------------
00:35:13 
Build timed out (after 120 minutes). Marking the build as aborted.
00:35:14 Build timed out (after 120 minutes). Marking the build as failed
```

For me it looks like the test hang for over a 100 minutes.

**Comment by wojtek-t** [comment] 2015-12-07 16:49
@yujuhong - that's not entirely true.
The whole build timed out, because completely nothing has happened during the last 1.5 hour (when Docker Containers were running).

**Comment by yujuhong** [comment] 2015-12-07 18:09
I see. Thanks for the clarification.

cc @pmorie who authored the test.

**Comment by wojtek-t** [comment] 2015-12-07 18:20
hmm - I'm not longer sure if that "Docker Containers" test.
This is another example of hanging tests:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/19419/console
and the last log is different.

I think that what happened here is that "Docker Containers" finished successfully, but no other tests passed after it. So I think that the problem is somewhere else.

@kubernetes/goog-testing

**Comment by ixdy** [comment] 2015-12-07 20:38
Yes, when this has happened in the past, there's been a test that panicks or does something to kill the parallel worker in a way it can't recover, and so we timeout waiting for that worker to report its completion.

The best way to track it down that I know of is to look at the Test Results Analyzer tab for the project and see which tests for a given run are N/A instead of pass/fail versus a regular run, since this means they didn't run or complete like normal. (I usually ignore the usually-skipped tests).

For kubernetes-e2e-gce-parallel/12507, the suspicious tests (those marked N/A) are:
* Daemon set should run and stop complex daemon
* EmptyDir volumes should support (root,0777,tmpfs) [Conformance]
* Kubectl client Proxy server should support --unix-socket=/path [Conformance]
* Networking should function for intra-pod communication [Conformance]
* Pods should support remote command execution over websockets
* Probing container with readiness probe should not be ready before initial delay and never restart [Conformance]

Will report on kubernetes-pull-build-test-e2e-gce/19419 next.

**Comment by ixdy** [comment] 2015-12-07 21:45
@wojtek-t kubernetes-pull-build-test-e2e-gce/19419 is not a timeout - did you mean to link something else?

**Comment by ixdy** [comment] 2015-12-07 21:49
19429 was a timeout. Its list of suspicious tests:
* Probing container with readiness probe should not be ready before initial delay and never restart [Conformance]	
* Networking should provide Internet connection for containers [Conformance]	
* Networking should function for intra-pod communication [Conformance]
* EmptyDir volumes should support (root,0666,tmpfs) [Conformance]

**Comment by ixdy** [comment] 2015-12-07 22:04
kubernetes-e2e-gce-parallel/12524 was another timeout. Suspicious tests there:
* EmptyDir volumes should support (root,0644,default) [Conformance]
* EmptyDir volumes volume on default medium should have the correct mode [Conformance]
* Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]
* Job should run a job to completion when tasks sometimes fail and are locally restarted
* Networking should function for intra-pod communication [Conformance]
* Services should be able to change the type and nodeport settings of a service

The only test that keeps appearing in these lists is `Networking should function for intra-pod communication [Conformance]`. @jayunit100 has anything there changed recently?

**Comment by ixdy** [comment] 2015-12-07 22:14
kubernetes-e2e-gce-parallel/12530 just timed out. Suspicious tests:
* Downward API should provide pod IP as an env var
* EmptyDir volumes volume on tmpfs should have the correct mode [Conformance]
* Job should keep restarting failed pods
* Job should run a job to completion when tasks sometimes fail and are not locally restarted
* Networking should function for intra-pod communication [Conformance]
* Pods should be submitted and removed [Conformance]
* Pods should support retrieving logs from the container over websockets
* Secrets should be consumable from pods [Conformance]
* Variable Expansion should allow substituting values in a container's args [Conformance]

Still points at the networking test.

**Comment by yujuhong** [comment] 2015-12-07 22:25
@ixdy, thanks for digging into the timeouts!

**Comment by wojtek-t** [comment] 2015-12-08 07:20
@ixdy - thanks! What you wrote seems very possible. I agree that probably the "Networking ..." test is the victim here.

**Comment by wojtek-t** [comment] 2015-12-08 10:31
OK - I'm closing this issue, because it's a duplicate of #13485

**Closed by wojtek-t** 2015-12-08 10:31 UTC
Labels: kind/flake, priority/P1, team/test-infra
