### ISSUE TITLE
Kubelet: More robust determination of hostname

### ISSUE THREAD

**Issue by ssergiienko** [kubernetes/kubernetes#5243] opened 2015-03-10 14:35 UTC
Kubelet service can't correctly determine hostname and fail to start.

Example (Clean CentOS 7)

Trace:
```
node2 kubelet[9462]: F0310 18:09:05.669072    9462 node.go:33] Couldn't determine hostname: exit status 1
```

But:
```bash
[root@node2 ~]# hostnamectl --static status
node2
[root@node2 ~]# cat /etc/hostname 
node2
```

If we additionally set hostname by hand in /etc/hosts with something like this:
```bash
[root@node2 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.56.102 node2
```
...then all works.

Expected that /etc/hostname (and/or hostnamectl) should be sufficient.

**Comment by eparis** [comment] 2015-03-10 14:41
I thought kubernetes used hostname -f.  What does that return?

**Comment by pythonpowerd** [comment] 2015-03-10 14:44
May be you are right )
```bash
[root@node2 ~]# hostname
node2
[root@node2 ~]# hostname -f
hostname: Name or service not known
```

**Comment by pythonpowerd** [comment] 2015-03-10 14:54
But hostname was set with default CentOS 7 graphical installer, isn't this enough for kubernetes?) If not, then maybe a little more sophisticated algorithm to determine hostname would be appropriate?

**Comment by pythonpowerd** [comment] 2015-03-10 15:41
Found that problem was in CentOS installer that writes /etc/nsswitch.conf with:
```
#hosts:     db files nisplus nis dns
hosts:      files dns
```
expected:
```
#hosts:     db files nisplus nis dns
hosts:      files dns myhostname
```

So, to avoid such problems kubernetes should consider to use more sophisticated algorithm to determine hostname? What do you think about this?

**Comment by dchen1107** [comment] 2015-03-10 18:44
we could extend our logic eventually on how to determine hostname, but for now, you can try to use --hostname_override to if you don't want to update /etc/nsswitch.

**Comment by pythonpowerd** [comment] 2015-03-10 18:55
Thanks anyway. We fixed our nsswitch, and now all works fine, but information about such kind of bugs caused by too simple algorithm of determining hostname may be helpful for future, and helps someone.
Close this issue if needed.

**Comment by vmarmol** [comment] 2015-03-10 19:07
Thanks @pythonpowerd! Will keep around for tracking purposes.

**Comment by onorua** [comment] 2016-02-15 15:04
This ticket should be closed, as the functionality is already here, don't know when exactly, but since 1.1 for sure.

**Closed** 2016-06-09 17:40 UTC
Labels: component/kubelet, priority/P3, team/node
