### ISSUE TITLE
Installing multiple third party resources on same resource path prefix has issues

### ISSUE THREAD

**Issue by uruddarraju** [kubernetes/kubernetes#23831] opened 2016-04-04 19:28 UTC
I am trying to install the following thirdparty resources:

```yaml
metadata:
  name: compute-node.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A compute node object is used by the mastercontroller to track computes in cloud"
versions:
 - name: v1
```

And 

```yaml
metadata:
  name: node-pool.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A node pool object to nodes is analogous to what a replicationcontroller is to pods"
versions:
 - name: v1
```

The first one gets successfully registered when I try to create it. But the second on never gets registered and kubectl does not throw an error out either. I digged a little deep into the kube-apiserver logs and I see the following error:

`Recovered from panic: "http: multiple registrations for /apis/tess.io/v1" (http: multiple registrations for /apis/tess.io/v1)`

When I digged deep into the thirdparty controller and master.go, here: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L611, I see that we have not covered the case where there can be 2 API objects defined on the same resource path prefix, like `/apis/tess.io/v1/nodepools` and `/apis/tess.io/v1/computenodes`

Is there something I am missing, or is this a genuine issue you think ?

**Comment by uruddarraju** [comment] 2016-04-04 20:56
cc @brendandburns

**Comment by uruddarraju** [comment] 2016-04-04 23:49
Also, from here https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L522

From what I understand, if I try to register a new Third Party resource whose group already exists, it considers that thirdpartyreource to already exist and would not take any action to register the new resource.

**Comment by uruddarraju** [comment] 2016-04-05 00:02
cc @brendandburns @wojtek-t

**Comment by wojtek-t** [comment] 2016-04-05 00:03
@lavalamp @kubernetes/sig-api-machinery

**Comment by uruddarraju** [comment] 2016-04-05 00:18
Also, once I create a thirdpartyresource and delete it, for some reason I have not been able to recreate any other thirdparty resources. I am running master on head using vagrant.

**Comment by lavalamp** [comment] 2016-04-05 00:24
Looks like bugs. Thanks for reporting.

**Comment by uruddarraju** [comment] 2016-04-06 23:50
The gist of the problem is that, there is no way we can modify a webservice with more routes and storages once it is installed. So we have to delete and reinstall the webservice with all the right things whenever a new thirdpartyresource is to be installed. But the removal of the webservice from the container is leaving some trails in the ServeMux.m map, which is a map of routes to handler functions.

go-restful does 2 things whenever you want to add a new webservice to the container.

1. add the webservice to the registeredwebservices list and 
2. register a handle function. . 

But, during a remove, it undos the 1 but not 2. 

From the go-restful perspective, if we add a webservice and remove it and if I try to add it back, it results in a panic.

**Comment by uruddarraju** [comment] 2016-04-06 23:51
I will try to reproduce it with a simple http application using go-restful and will file an issue if I am able to reproduce the issue.

**Comment by lavalamp** [comment] 2016-04-07 16:57
Thanks for all your effort, Uday!

**Comment by uruddarraju** [comment] 2016-04-07 18:49
Was able to reproduce the issue with just go-restful today, where I was able to successfully add a webservice to a container, remove it and when I add it back, I see the following issue:

```
panic: http: multiple registrations for /users
```

I tried the example here: https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go. And changed the lines https://github.com/emicklei/go-restful/blob/master/examples/restful-user-resource.go#L74 to do,

```
	container.Add(ws)
	container.Remove(ws)
	container.Add(ws)
```

This was what created the panic.

**Comment by uruddarraju** [comment] 2016-04-07 18:51
This explains why a thirdparty registration followed by unregistration, cannot be registered back (Which I think is critical for us.)

**Comment by uruddarraju** [comment] 2016-04-07 18:58
@lavalamp Created an issue with go-restful: https://github.com/emicklei/go-restful/issues/274

**Comment by uruddarraju** [comment] 2016-04-11 01:10
There was an other issue with the RemoveRoute call in go-restful for webservices having more than one route. Fixed it in https://github.com/emicklei/go-restful/pull/275

**Comment by uruddarraju** [comment] 2016-04-14 21:48
@lavalamp I still have to submit a fix to fix this. The PR only updates the godep :)

**Comment by duglin** [comment] 2016-07-09 14:21
FYI - I'm getting similar errors even when I use a different API group (domain name on the resources).

**Comment by duglin** [comment] 2016-07-09 14:46
Here's a gist with a simple test showing the issue:  https://gist.github.com/duglin/ffe983ba6f15ad8f1bad968ccbcdcba3

**Comment by nebril** [comment] 2016-08-02 07:30
I think this one should be reopened, the problem is still there on c7ec11b32ad396fd19a36c209991af401dbdfa2b

**Comment by brendandburns** [comment] 2016-08-07 04:55
I believe that https://github.com/kubernetes/kubernetes/pull/29724 should have the fix, can you test it out?

**Comment by caesarxuchao** [comment] 2016-08-09 23:35
Thanks @brendandburns. The added test-cmd.sh test in #29724 looks proper.

**Comment by brendandburns** [comment] 2016-08-14 03:26
Closing this since #29724 is merged.

**Closed by brendandburns** 2016-08-14 03:26 UTC
Labels: kind/bug, priority/P1, team/CSI-API Machinery SIG
