### ISSUE TITLE
flake: TestCrossNamespaceListWatch

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#46570] opened 2017-05-27 19:05 UTC
```
k8s.io/kubernetes/vendor/k8s.io/kube-apiextensions-server/test/integration TestCrossNamespaceListWatch 5.54s
basic_test.go:501: expected ADDED, got from junit_fd4bc6eaf817457a8dad8075fc1484aee6f3e66a_20170527-074212.xml
Filter through log files
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36721/pull-kubernetes-unit/33133/

**Comment by smarterclayton** [comment] 2017-05-27 19:06
@kubernetes/sig-api-machinery-pr-reviews

**Comment by nikhita** [comment] 2017-05-28 10:53
Dupe of https://github.com/kubernetes/kubernetes/issues/46446
Being addressed in https://github.com/kubernetes/kubernetes/pull/46536

**Closed** 2017-05-30 16:13 UTC
Labels: kind/flake, sig/api-machinery
