### ISSUE TITLE
whether kubelet should add a network-mode flag

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#26137] opened 2016-05-24 04:50 UTC
FYI. I am thinking about this recently when I am integrating kubernetes 1.2 with docker 1.10, and also some docker network plugins. I think after docker provides `docker network` command, `--net` option is not just `none, bridge, host, container, default`. Some docker network plugins may create other meaningful network name. I am not sure whether kubelet should support this case, but I can it's indeed necessary in some use cases. @dchen1107 @Random-Liu WDYT?

**Comment by thockin** [comment] 2016-05-24 05:59
There's not a concept of Network (as a noun) in Kubernetes yet, and when there is, it will not necessarily map to Docker's model.  We already barely use Docker for networking, by default.  That said, we already have a `hostNetwork` field.

**Comment by AdoHe** [comment] 2016-05-24 06:20
@thockin I did understand what you say. I am just wondering what should we do in cases where we have to specify the network name. In our current implementation, we have `hostNetwork` field, and if we use kubernetes network plugin, the network is `none`. What if the user is using docker's network plugin and have to set the network name when run containers?

**Comment by AdoHe** [comment] 2016-05-24 06:21
I did agree that we have to need to map to Docker's network model.

**Comment by thockin** [comment] 2016-05-24 07:43
Sorry.  I didn't mean to close it.  Those buttons are too close.  The problem is that we do not have a model for Networks yet and therefore we have no way to represent different networks.  I would be open to having a network mode for kubelet that was "native" or something that maybe looked at annotations or some external config and used that do program docker networks.

**Comment by AdoHe** [comment] 2016-05-24 07:54
@thockin This is just what I am considering. Actually in our internal version of kubernetes we have updated this since we are using docker network plugin to configure container network. And there are different docker networks in our container infrastructure, we need a way to set this when we are creating pod.

**Comment by AdoHe** [comment] 2016-05-24 08:26
```
having a network mode for kubelet that was native
```
I am afraid this is not that enough, having a network mode for kubelet means that all pods managed by this kubelet will have same network mode, which also means that all pods on a minion node will have same network mode, this may be not what users expect.

**Comment by AdoHe** [comment] 2016-05-25 10:46
@thockin I am not sure whether it's good for user to specify network in the pod definition, for a short term, maybe we can add a flag to kubelet, but we still need to think about how to program docker network.

**Comment by thockin** [comment] 2016-05-25 23:57
First, this exists:
https://github.com/kubernetes/contrib/tree/master/cni-plugins/to_docker

Second, I so think we should have a through-to-runtime network mode, but
that's only about connecting pods to a network, not creating networks (for
now)

If we had a "--net-driver=runtime" option, the docker runtime could look at
annotations on a Pod to decide which network to join it to.  I would be
generally supportive of that design.  I just don't have time to implement
it myself.

**Comment by AdoHe** [comment] 2016-05-26 13:00
@thockin that's just what I mean, we should have a through-to-runtime network mode which is just about connecting pods to a network, not about creating network. I think I will take some time to implement this as I really need this feature now.

**Closed** 2017-05-31 18:22 UTC
Labels: sig/network, team/cluster (deprecated - do not use)
