### ISSUE TITLE
Patching DaemonSet history to remove its controller ref always fails

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#47008] opened 2017-06-06 00:32 UTC
Patching controllerrevision while adopt/orphan failed, because the `.data` field is immutable:

```console
$ kubectl patch controllerrevision newrelic-agent-1-3791983440 -p '{"metadata":{"ownerReferences":[{"$patch":"delete","uid":"4ee3f9c3-4a4c-11e7-8509-6
4510658e388"}],"uid":"4ee48463-4a4c-11e7-8509-64510658e388"}}'
The ControllerRevision "newrelic-agent-1-3791983440" is invalid: data: Invalid value: runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x7b, 0x22, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x7b, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3a, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x22, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x6e, 0x65, 0x77, 0x72, 0x65, 0x6c, 0x69, 0x63, 0x22, 0x2c, 0x22, 0x74, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x74, 0x65, 0x73, 0x74, 0x31, 0x22, 0x7d, 0x7d, 0x2c, 0x22, 0x73, 0x70, 0x65, 0x63, 0x22, 0x3a, 0x7b, 0x22, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x22, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x22, 0x2c, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x41, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x22, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x61, 0x70, 0x70, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x3a, 0x7b, 0x7d, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3a, 0x22, 0x2f, 0x64, 0x65, 0x76, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6c, 0x6f, 0x67, 0x22, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x7d, 0x5d, 0x2c, 0x22, 0x64, 0x6e, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x41, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x22, 0x2c, 0x22, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x22, 0x2c, 0x22, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3a, 0x7b, 0x7d, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x3a, 0x33, 0x30, 0x7d, 0x7d}, ContentEncoding:"", ContentType:"application/json"}: field is immutable
```

**Comment by caesarxuchao** [comment] 2017-06-06 00:35
"field is immutable"

**Comment by caesarxuchao** [comment] 2017-06-06 00:45
Is there other party changing [Data](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1beta1/types.go#L431) frequently? Perhaps the Data is changed by other party before the patched Object is validated?

Or maybe it has something to do with `Data` being of type `runtime.RawExtension`, maybe patch doesn't work well with this type?

**Comment by janetkuo** [comment] 2017-06-06 00:46
> Is there other party changing Data frequently? Perhaps the Data is changed by other party before the patched Object is validated?

Not possible. controllrerevision `.data` cannot be changed, it's an immutable field

**Comment by caesarxuchao** [comment] 2017-06-06 00:50
cc @mengqiy since it might be a patch issue.

**Comment by mengqiy** [comment] 2017-06-06 00:52
@janetkuo Latest API server and latest kubectl?

**Comment by janetkuo** [comment] 2017-06-06 00:55
It's not kubectl specific. Found this in `KubeClient.AppsV1beta1().ControllerRevisions(namespace).Patch(name, types.StrategicMergePatchType, data)` when DaemonSet controller is trying to orphan its history. Also likely caused GC controller to fail orphan it too.

**Comment by janetkuo** [comment] 2017-06-06 01:20
To reproduce it:

```console 
$ kubectl create -f ds.yaml
$ kubectl get ds -o yaml | grep uid 
    uid: 6dfb9ac2-4a55-11e7-b281-64510658e388
$ kubectl get controllerrevision -o yaml | grep uid 
      uid: 6dfb9ac2-4a55-11e7-b281-64510658e388
    uid: 6dfc9100-4a55-11e7-b281-64510658e388
$ kubectl patch controllerrevision newrelic-agent-1-3791983440 -p '{"metadata":{"ownerReferences":[{"$patch":"delete","uid":"6dfb9ac2-4a55-11e7-b281-64510658e388"}],"uid":"6dfc9100-4a55-11e7-b281-64510658e388"}}'
```

It could be a controller revisions bug. cc @kow3ns

**Comment by janetkuo** [comment] 2017-06-06 01:24
Not sure why the error message showed controllerrevisions `.data` as type `runtime.Unknown`. Maybe DaemonSet controller is not creating the history right?

**Comment by janetkuo** [comment] 2017-06-06 01:34
It's probably something to do with DaemonSet.

/assign @janetkuo

**Comment by kargakis** [comment] 2017-06-06 10:24
@kubernetes/sig-apps-bugs

**Comment by kargakis** [comment] 2017-06-06 10:25
Is this a dupe of https://github.com/kubernetes/kubernetes/issues/46998 (or the other way around) ?

**Comment by caesarxuchao** [comment] 2017-06-06 16:52
No, 46998 exposes a problem in GC controller.

**Comment by mengqiy** [comment] 2017-06-06 18:04
@janetkuo Patching seems to be correct.
original:
map[data:map[metadata:map[creationTimestamp:<nil> labels:map[name:newrelic]] spec:map[volumes:[map[name:newrelic-config secret:map[secretName:newrelic-config defaultMode:420]] map[hostPath:map[path:/dev] name:dev] map[name:run hostPath:map[path:/var/run/docker.sock]] map[name:sys hostPath:map[path:/sys]] map[name:log hostPath:map[path:/var/log]]] containers:[map[terminationMessagePath:/dev/termination-log imagePullPolicy:Always name:newrelic command:[bash -c source /etc/kube-newrelic/config && /usr/sbin/nrsysmond -E -F] env:[map[name:NRSYSMOND_logfile value:/var/log/nrsysmond.log]] resources:map[requests:map[cpu:150m]] image:newrelic/nrsysmond volumeMounts:[map[name:newrelic-config readOnly:true mountPath:/etc/kube-newrelic] map[name:dev mountPath:/dev] map[name:run mountPath:/var/run/docker.sock] map[name:sys mountPath:/sys] map[mountPath:/var/log name:log]] terminationMessagePolicy:File securityContext:map[privileged:true]]] terminationGracePeriodSeconds:30 dnsPolicy:ClusterFirst hostNetwork:true restartPolicy:Always hostPID:true hostIPC:true securityContext:map[] schedulerName:default-scheduler]] revision:1 kind:ControllerRevision apiVersion:apps/v1beta1 metadata:map[creationTimestamp:2017-06-06T17:54:48Z labels:map[daemonset-controller-hash:3732475869 name:newrelic] ownerReferences:[map[apiVersion:extensions/v1beta1 kind:DaemonSet name:newrelic-agent uid:3b55a88f-4ae1-11e7-af61-42010a800002 controller:true blockOwnerDeletion:true]] name:newrelic-agent-3732475869 namespace:default uid:3b579612-4ae1-11e7-af61-42010a800002 resourceVersion:922]]

patch:
map[metadata:map[ownerReferences:[map[$patch:delete uid:3b55a88f-4ae1-11e7-af61-42010a800002]] uid:3b55a88f-4ae1-11e7-af61-42010a800002]]

merged:

map[kind:ControllerRevision apiVersion:apps/v1beta1 metadata:map[name:newrelic-agent-3732475869 namespace:default uid:3b55a88f-4ae1-11e7-af61-42010a800002 resourceVersion:922 creationTimestamp:2017-06-06T17:54:48Z labels:map[daemonset-controller-hash:3732475869 name:newrelic] ownerReferences:[]] data:map[metadata:map[creationTimestamp:<nil> labels:map[name:newrelic]] spec:map[restartPolicy:Always hostPID:true hostIPC:true securityContext:map[] schedulerName:default-scheduler volumes:[map[secret:map[secretName:newrelic-config defaultMode:420] name:newrelic-config] map[name:dev hostPath:map[path:/dev]] map[name:run hostPath:map[path:/var/run/docker.sock]] map[name:sys hostPath:map[path:/sys]] map[name:log hostPath:map[path:/var/log]]] containers:[map[image:newrelic/nrsysmond volumeMounts:[map[name:newrelic-config readOnly:true mountPath:/etc/kube-newrelic] map[name:dev mountPath:/dev] map[name:run mountPath:/var/run/docker.sock] map[mountPath:/sys name:sys] map[name:log mountPath:/var/log]] terminationMessagePolicy:File securityContext:map[privileged:true] name:newrelic command:[bash -c source /etc/kube-newrelic/config && /usr/sbin/nrsysmond -E -F] env:[map[name:NRSYSMOND_logfile value:/var/log/nrsysmond.log]] resources:map[requests:map[cpu:150m]] terminationMessagePath:/dev/termination-log imagePullPolicy:Always]] terminationGracePeriodSeconds:30 dnsPolicy:ClusterFirst hostNetwork:true]] revision:1]

**Comment by mengqiy** [comment] 2017-06-06 18:06
You don't have to send
```
'{"metadata":{"ownerReferences":[{"$patch":"delete","uid":"6dfb9ac2-4a55-11e7-b281-64510658e388"}],"uid":"6dfc9100-4a55-11e7-b281-64510658e388"}}'
```
Instead this should be enough
```
'{"metadata":{"ownerReferences":[{"$patch":"delete","uid":"6dfb9ac2-4a55-11e7-b281-64510658e388"}]}}'
```

**Comment by caesarxuchao** [comment] 2017-06-06 18:11
The second uid is to make sure the patch is applied to the correct object, not a different object with the same name.

**Comment by janetkuo** [comment] 2017-06-06 19:33
It's a DaemonSet controller bug, fix is coming

**Comment by janetkuo** [comment] 2017-06-06 19:56
Fixing this in #47075

**Closed** 2017-06-13 06:31 UTC
Labels: kind/bug, sig/apps
