### ISSUE TITLE
Timeout waiting for all HollowNodes to become Running in kubemark-gce test

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#21359] opened 2016-02-17 00:33 UTC
There isn't much detail in the logs... Perhaps the first step is to add more logging?
https://console.developers.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-gce/5748/

The relevant bit seems to be:
```
16:01:24 replicationcontroller "hollow-node" created
16:01:24 Waiting for all HollowNodes to become Running...
16:01:25 ........................................................................................................................................................................................................................................................................................................................................................................
16:16:25 Timeout waiting for all HollowNodes to become Running
16:16:25 Build step 'Execute shell' marked build as failure
```

**Comment by gmarek** [comment] 2016-02-18 10:46
Logs are there, but we started saving them to GCS buckets only recently. We're waiting for next failure to happen.

cc @wojtek-t

**Comment by gmarek** [comment] 2016-02-18 10:48
I'll change the message to distinguish between HollowNode startup and API server failure. My current theory is that it's caused by docker failure on master machine, which in turn prevents us from starting etcd, which causes the failure.

**Comment by wojtek-t** [comment] 2016-02-18 11:06
>
Logs are there, but we started saving them to GCS buckets only recently. We're waiting for next failure to happen.

I'm afraid we will not have logs from failed runs.

**Comment by dchen1107** [comment] 2016-02-24 00:09
One failed instance today:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/5921/console

**Comment by gmarek** [comment] 2016-02-24 10:34
```
15:15:28 Found only 96 ready Nodes while waiting for 100.
```

Which means that it's not a problem with master machine, but some HollowPods are not starting in the external cluster.

**Comment by gmarek** [comment] 2016-02-24 11:03
Sadly there are no logs in case of such failure.

**Comment by wojtek-t** [comment] 2016-02-25 14:47
https://github.com/kubernetes/kubernetes/pull/21871 was already been merged - thanks to it we should have necessary logs in case of next such failure.
Waiting for the next one to debug it.

**Comment by fabioy** [comment] 2016-02-25 19:43
We got a few failures, if you want to take a look:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/5970/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/5971/

**Comment by wojtek-t** [comment] 2016-02-25 20:07
@fabioy - actually both of the are different failures.

**Comment by fabioy** [comment] 2016-02-25 22:13
Ah, understood. Thanks for looking, though.

**Comment by wojtek-t** [comment] 2016-03-01 08:17
One more failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/6082/consoleFull

Ant this time we have logs:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-gce/6082/artifacts/?project=kubernetes-jenkins

I will look into it.

**Comment by wojtek-t** [comment] 2016-03-01 08:35
The above failure was problem with Kubelet - I filed #22259 for it.

**Closed** 2016-03-03 03:44 UTC
Labels: kind/flake, priority/P0, team/test-infra
