### ISSUE TITLE
e2e flake: node condition "TestCondition" not found

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#27273] opened 2016-06-13 13:11 UTC
[Fail] [k8s.io] NodeProblemDetector [k8s.io] KernelMonitor [It] should generate event when temporary error happens 

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26894/kubernetes-pull-build-test-e2e-gce/44457/

```
â€¢ Failure [42.980 seconds]
[k8s.io] NodeProblemDetector
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:660
  [k8s.io] KernelMonitor
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:660
    should generate event when temporary error happens [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node_problem_detector.go:221

    Expected success, but got an error:
        <*errors.errorString | 0xc820b9cb30>: {
            s: "node condition \"TestCondition\" not found",
        }
        node condition "TestCondition" not found

```

**Comment by wojtek-t** [comment] 2016-06-13 14:07
Duplicate of #27276

**Closed by wojtek-t** 2016-06-13 14:07 UTC
Labels: kind/flake
