### ISSUE TITLE
kubeadm centos documentation is incorrect

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kubernetes/kubernetes#43857] opened 2017-03-30 13:15 UTC
I'm following the steps listed in the documentation at https://kubernetes.io/docs/getting-started-guides/kubeadm/ for deployment on CentOS7 (single node installation).

kubeadm init gets stuck here at step 2 of 4:

```
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 43.322438 seconds
[apiclient] Waiting for at least one node to register and become ready
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
```
In /var/log/messages, I see the following:

```
Mar 30 15:07:58 win-s5mj4igebae kubelet: W0330 15:07:58.747233   14481 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 30 15:07:58 win-s5mj4igebae kubelet: E0330 15:07:58.747354   14481 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 30 15:08:03 win-s5mj4igebae kubelet: W0330 15:08:03.778100   14481 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 30 15:08:03 win-s5mj4igebae kubelet: E0330 15:08:03.778174   14481 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 30 15:08:08 win-s5mj4igebae kubelet: W0330 15:08:08.809108   14481 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 30 15:08:08 win-s5mj4igebae kubelet: E0330 15:08:08.809183   14481 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

```

However, according to the documentation, the network setup is only done in step 3 of 4.

**Comment by thelastworm** [comment] 2017-03-30 15:30
Same issue in ubuntu 16.04

**Comment by php-coder** [comment] 2017-03-30 17:13
For the documentation issues there is a dedicated project: https://github.com/kubernetes/kubernetes.github.io

**Comment by LaurentDumont** [comment] 2017-03-31 03:08
`Kubeadm` is currently broken. Wait for a fix to be released before using it ;)

https://github.com/kubernetes/kubernetes/issues/43815#issuecomment-290270198

**Comment by luxas** [comment] 2017-05-30 06:11
This has been fixed, duplicate of https://github.com/kubernetes/kubernetes/issues/43815

**Closed by luxas** 2017-05-30 06:11 UTC
