### ISSUE TITLE
E2E: [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD with validation schema [Conformance]

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#90517] opened 2020-04-27 10:42 UTC
[Recent failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1254380216860545027) in sig-scalability conformance test is related to CustomResourcePublishOpenAPI. Could you please check the reason for this failure?

/sig api-machinery
/assign @liggitt 
/cc @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment] 2020-04-27 12:45
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/90506

/close

**Closed** 2020-04-27 12:46 UTC
Labels: sig/api-machinery
