### ISSUE TITLE
Unit/integration tests timing out

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#23879] opened 2016-04-05 18:27 UTC
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22962/kubernetes-pull-test-unit-integration/20155/

```
Build timed out (after 60 minutes). Marking the build as aborted.
Build timed out (after 60 minutes). Marking the build as failed.
FATAL: Unable to delete script file /tmp/hudson1095119725192734885.sh
```

**Comment by spxtr** [comment] 2016-04-05 20:50
Might be a Jenkins bug.

https://issues.jenkins-ci.org/browse/JENKINS-12235

**Comment by fejta** [comment] 2016-04-07 01:19
@ixdy this looks like a repeat of https://github.com/kubernetes/kubernetes/issues/23200 

```sh
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /go/src/k8s.io/kubernetes
godep: [WARNING]:	$GOPATH: /go/src/k8s.io/kubernetes/_output/local/go:/go/src/k8s.io/kubernetes/Godeps/_workspace
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
```

The result is jenkins takes half an hour to start unit testing:

```sh
+ ./hack/build-go.sh
Go version: go version go1.6 linux/amd64
+++ [0404 14:25:09] Building go targets for linux/amd64:

+ ./hack/test-go.sh
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [0404 14:50:08] Running tests without code coverage
```

**Comment by ixdy** [comment] 2016-05-05 01:20
There haven't been any PRs linked here recently, so I wonder if this is still an issue.

**Comment by ixdy** [comment] 2016-05-09 23:13
The tests occasionally take ~1h instead of ~45m, but the timeout is set at 1h20, so there haven't been any recent failures.

**Comment by brendandburns** [comment] 2016-06-04 18:37
I just had one take > 80 minutes:

https://github.com/kubernetes/kubernetes/pull/25894

**Comment by ixdy** [comment] 2016-06-04 23:31
@brendandburns please link to the log when you report flakes. it is difficult to find the failing run otherwise.

**Comment by ixdy** [comment] 2016-06-04 23:35
In this case it was kubernetes-jenkins/pr-logs/pull/25894/kubernetes-pull-test-unit-integration/29066/, but it will save everyone time if you link the logs.

**Comment by wojtek-t** [comment] 2016-06-08 14:07
Can we close it as duplicate of #25940 ?

**Closed** 2016-06-08 17:17 UTC
Labels: kind/flake, team/test-infra
