### ISSUE TITLE
Flaky test: subresource_test integration test is failing with panic error

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#75183] opened 2019-03-08 14:20 UTC
It looks like subresources_test.go is flaking with:

```
I0308 11:59:32.875349 125866 clientconn.go:551] parsed scheme: "" I0308 11:59:32.875369 125866 
clientconn.go:557] scheme "" not registered, fallback to default scheme I0308 11:59:32.875409 
125866 resolver_conn_wrapper.go:116] ccResolverWrapper: sending new addresses to cc: 
[{127.0.0.1:2379 0 <nil>}] I0308 11:59:32.875514 125866 balancer_v1_wrapper.go:125] 
balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0308 11:59:32.875759 125866 
balancer_v1_wrapper.go:125] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0308 11:59:32.876221 125866 balancer_v1_wrapper.go:125] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] testserver.go:141: runtime-config=map[api/all:true] testserver.go:142:
 Starting apiextensions-apiserver on port 43045... testserver.go:160: Waiting for /healthz to be ok... subresources_test.go:537: unexpected error: WishIHadChosenNoxu.mygroup.example.com "foo" is 

invalid: apiVersion: Invalid value: "mygroup.example.com/v1beta1": must be mygroup.example.com/v1 panic: runtime error: invalid memory address or nil pointer dereference /usr/local/go/src/testing

/testing.go:792 +0x387 /usr/local/go/src/runtime/panic.go:513 +0x1b9 /go/src/k8s.io/kubernetes

/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration/subresources_test.go:541 +0xa1b /usr/local/go/src/testing/testing.go:827 +0xbf /usr/local/go/src

/testing/testing.go:878 +0x35c
````

/sig api-machinery

Link to failing test - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/75131/pull-kubernetes-integration/48253/

**Comment by gnufied** [comment] 2019-03-08 16:27
cc @liggitt , is this a new flake? worth marking for 1.14 milestone?

**Comment by liggitt** [comment] 2019-03-08 16:41
not new, dupe of https://github.com/kubernetes/kubernetes/issues/72493

/close

**Closed by liggitt** 2019-03-08 16:41 UTC
Labels: kind/failing-test, sig/api-machinery

**Comment by liggitt** [comment] 2019-03-08 16:43
(the panic is because the test doesn't fatal on line 537, but continues on, and `createdNoxuInstance` is nil)
