### ISSUE TITLE
Some services tests flaking after upgrading from v1.0 to v1.2

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#23060] opened 2016-03-16 17:11 UTC
```
21:19:10 Mar 15 21:19:10.705: INFO: Executing cmd "for i in $(seq 1 150); do wget -q -T 1 -O - http://10.39.241.250:80 2>&1 || true; echo; done" in pod e2e-tests-services-w0hwj/execpod
21:19:10 Mar 15 21:19:10.705: INFO: Running '/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.154.113.71 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.0-1.2-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-services-w0hwj execpod -- /bin/sh -c for i in $(seq 1 150); do wget -q -T 1 -O - http://10.39.241.250:80 2>&1 || true; echo; done'
21:19:11 Mar 15 21:19:11.181: INFO: error while kubectl execing "for i in $(seq 1 150); do wget -q -T 1 -O - http://10.39.241.250:80 2>&1 || true; echo; done" in pod e2e-tests-services-w0hwj/execpod: Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.0-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.113.71 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.0-1.2-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-services-w0hwj execpod -- /bin/sh -c for i in $(seq 1 150); do wget -q -T 1 -O - http://10.39.241.250:80 2>&1 || true; echo; done] []  <nil>  error: error executing remote command: Error executing command in container: Error executing in Docker Container: -1
21:19:11  [] <nil> 0xc208a9b8e0 exit status 1 <nil> true [0xc20a046670 0xc20a046698 0xc20a0466d0] [0xc20a046670 0xc20a046698 0xc20a0466d0] [0xc20a046690 0xc20a0466c8] [0x962af0 0x962af0] 0xc20a032ae0}:
21:19:11 Command stdout:
21:19:11 
21:19:11 stderr:
21:19:11 error: error executing remote command: Error executing command in container: Error executing in Docker Container: -1
21:19:11 
21:19:11 error:
21:19:11 exit status 1
21:19:11 
21:19:11 Output: 
21:19:11 Mar 15 21:19:11.181: INFO: Unable to reach the following endpoints of service 10.39.241.250: map[service2-fp8r0:{} service2-keode:{} service2-vgs64:{}]
```

View logs and artifacts at https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-upgrade-gke-1.0-1.2-step7-e2e-new/10

**Comment by ihmccreery** [comment] 2016-03-16 17:15
This is a v1.2 test running against a cluster that's been fully upgraded from v1.0 to v1.2.

**Comment by thockin** [comment] 2016-03-16 18:10
The strange thing is that it fails.  The command that is failing is:

```
for i in $(seq 1 150); do
    wget -q -T 1 -O - http://10.39.241.250:80 2>&1 || true;
    echo;
done
```

How on earth is that failing?  And yet, the error says "Docker" which means it really IS getting all the way to kubelet...

**Comment by thockin** [comment] 2016-03-16 18:14
cc @bprashanth @ArtfulCoder

**Comment by ihmccreery** [comment] 2016-03-16 18:21
Also flaking: `[Fail] Services [It] should serve multiport endpoints from pods [Conformance]`:

```
[It] should serve multiport endpoints from pods [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:224
STEP: creating service multi-endpoint-test in namespace e2e-tests-services-leh8d
STEP: waiting up to 1m0s for service multi-endpoint-test in namespace e2e-tests-services-leh8d to expose endpoints map[]
Mar 15 20:59:34.779: INFO: Get endpoints failed (7.387398ms elapsed, ignoring for 5s): endpoints "multi-endpoint-test" not found
Mar 15 20:59:35.783: INFO: successfully validated that service multi-endpoint-test in namespace e2e-tests-services-leh8d exposes endpoints map[] (1.011452288s elapsed)
STEP: creating pod pod1 in namespace e2e-tests-services-leh8d
STEP: waiting up to 1m0s for service multi-endpoint-test in namespace e2e-tests-services-leh8d to expose endpoints map[pod1:[100]]
Mar 15 20:59:36.823: INFO: successfully validated that service multi-endpoint-test in namespace e2e-tests-services-leh8d exposes endpoints map[pod1:[100]] (1.028416804s elapsed)
STEP: creating pod pod2 in namespace e2e-tests-services-leh8d
STEP: waiting up to 1m0s for service multi-endpoint-test in namespace e2e-tests-services-leh8d to expose endpoints map[pod1:[100] pod2:[101]]
Mar 15 20:59:40.887: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (4.056885745s elapsed, will retry)
Mar 15 20:59:45.931: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (9.100640989s elapsed, will retry)
Mar 15 20:59:50.979: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (14.148321824s elapsed, will retry)
Mar 15 20:59:56.022: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (19.191614215s elapsed, will retry)
Mar 15 21:00:01.069: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (24.238797688s elapsed, will retry)
Mar 15 21:00:06.121: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (29.291160685s elapsed, will retry)
Mar 15 21:00:11.192: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (34.361804506s elapsed, will retry)
Mar 15 21:00:16.237: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (39.406426618s elapsed, will retry)
Mar 15 21:00:21.331: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (44.500732016s elapsed, will retry)
Mar 15 21:00:26.376: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (49.54585563s elapsed, will retry)
Mar 15 21:00:31.420: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (54.590170271s elapsed, will retry)
Mar 15 21:00:36.468: INFO: Unexpected endpoints: found map[7f611601-eb2b-11e5-83ea-42010af00002:[100]], expected map[pod1:[100] pod2:[101]] (59.637940864s elapsed, will retry)
Mar 15 21:00:37.482: INFO: Pod e2e-tests-services-leh8d	pod1	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	<nil>
Mar 15 21:00:37.482: INFO: Pod e2e-tests-services-leh8d	pod2	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	fluentd-cloud-logging-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-41gc	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-41gc	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	fluentd-cloud-logging-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	fluentd-cloud-logging-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	heapster-v1.0.0-beta2-xckwv	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	kube-dns-v11-s21yl	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-41gc	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	kube-proxy-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-41gc	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-41gc	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	kube-proxy-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	kube-proxy-gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	kubernetes-dashboard-v1.0.0-l82vn	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw	<nil>
Mar 15 21:00:37.482: INFO: Pod kube-system	l7-lb-controller-v0.6.0-rmsz7	gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg	<nil>
Mar 15 21:00:37.482: FAIL: Timed out waiting for service multi-endpoint-test in namespace e2e-tests-services-leh8d to expose endpoints map[pod1:[100] pod2:[101]] (1m0s elapsed)
```

Same run as above.

**Comment by bprashanth** [comment] 2016-03-16 18:35
The lack of verbose logging from gke makes this nearly impossible to debug. 

The test starts a single pod, waits till it's running (we should add a probe and wait till Ready), then loops around trying to exec into it. Looks like the busybox container in the pod is continuously getting killed on the node. 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-upgrade-gke-1.0-1.2-step7-e2e-new/10/artifacts/gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-jkbw/?debugUI=CLOUD
```
I0316 03:58:32.144311    3407 kubelet.go:2388] SyncLoop (ADD, "api"): "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)"
I0316 03:58:32.155198    3407 manager.go:1688] Need to restart pod infra container for "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)" because it is not found
I0316 03:58:33.265030    3407 kubelet.go:2410] SyncLoop (PLEG): "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"596f45a2-eb2b-11e5-83ea-42010af00002", Type:"ContainerStarted", Data:"308e8438ab2ea11c37a2bcbcbad8897fbd5c19a61b67fd33bb5a595f1d5cd645"}
I0316 03:58:33.268169    3407 kubelet.go:2410] SyncLoop (PLEG): "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"596f45a2-eb2b-11e5-83ea-42010af00002", Type:"ContainerStarted", Data:"281fe0ee789a0b091c3cca67e8eb294325a16d1d55f68857a7f339e756264a3c"}
I0316 03:58:35.423437    3407 server.go:1096] POST /exec/e2e-tests-services-hcezf/execpod/exec?command=%2Fbin%2Fsh&command=-c&command=for+i+in+%24%28seq+1+150%29%3B+do+wget+-q+-T+1+-O+-+http%3A%2F%2F10.39.252.164%3A80+2%3E%261+%7C%7C+true%3B+echo%3B+done&error=1&output=1: (239.870947ms) hijacked [[kubectl/v1.3.0 (linux/amd64) kubernetes/a1fcccd] 10.240.0.2:51940]
I0316 03:58:35.447264    3407 kubelet.go:2391] SyncLoop (UPDATE, "api"): "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)"
I0316 03:58:35.447332    3407 kubelet.go:2394] SyncLoop (REMOVE, "api"): "execpod_e2e-tests-services-hcezf(596f45a2-eb2b-11e5-83ea-42010af00002)"
I0316 03:58:35.449388    3407 manager.go:1368] Killing container "281fe0ee789a0b091c3cca67e8eb294325a16d1d55f68857a7f339e756264a3c exec e2e-tests-services-hcezf/execpod" with 0 second grace period
I0316 03:58:35.451264    3407 kubelet.go:2229] Killing unwanted pod "execpod"
I0316 03:58:35.451331    3407 manager.go:1368] Killing container "281fe0ee789a0b091c3cca67e8eb294325a16d1d55f68857a7f339e756264a3c exec e2e-tests-services-hcezf/execpod" with 0 second grace period
I0316 03:58:35.469533    3407 kubelet.go:2388] SyncLoop (ADD, "api"): "execpod_e2e-tests-services-hcezf(5b6af665-eb2b-11e5-83ea-42010af00002)"
I0316 03:58:35.480954    3407 manager.go:1688] Need to restart pod infra container for "execpod_e2e-tests-services-hcezf(5b6af665-eb2b-11e5-83ea-42010af00002)" because it is not found
I0316 03:58:35.549351    3407 kubelet.go:1974] volume "596f45a2-eb2b-11e5-83ea-42010af00002/default-token-d0y4q", still has a container running "596f45a2-eb2b-11e5-83ea-42010af00002", skipping teardown
I0316 03:58:36.281651    3407 kubelet.go:2410] SyncLoop (PLEG): "execpod_e2e-tests-services-hcezf(5b6af66
```

And docker complains about not being able to exec:
```
error: read parent: connection reset by peer\n" 
time="2016-03-16T04:14:47.007408700Z" level=warning msg="signal: killed" 
time="2016-03-16T04:14:47.007492149Z" level=error msg="Error running command in existing container 11e7f1473b507a430b3918a55787f06a30a651d8c3e8eb61763ff19bdbd26f46: [8] System error: read parent: connection reset by peer" 
time="2016-03-16T04:14:47.007665173Z" level=error msg="Error running exec in container: execcantrun: Cannot run exec command 11a7ca1e0b9bba1746daa138a0a2b17f2116c3ad028cf37e7ed51d1718d8f945 in container 11e7f1473b507a430b3918a55787f06a30a651d8c3e8eb61763ff19bdbd26f46: [8] System error: read parent: connection reset by peer\n" 
time="2016-03-16T04:14:52.500154659Z" level=warning msg="signal: killed" 
time="2016-03-16T04:14:52.500245834Z" level=error msg="Error running command in existing
```
@kubernetes/goog-node

**Comment by yujuhong** [comment] 2016-03-16 20:13
```

Mar 15 21:00:37.573: INFO: At 2016-03-15 20:59:37 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "test" with RunContainerError: "runContainer: API error (500): Cannot start container 4ea3ece6894442514906b9668bd28f0fdef97e97af70b51c7fe8bb618e58396d: [8] System error: read parent: connection reset by peer\n"

Mar 15 21:00:37.573: INFO: At 2016-03-15 20:59:37 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "test" with RunContainerError: "runContainer: API error (500): Cannot start container c78902b0254065069844d67ab0e04043f548d52bc9bc663c9578c6415c2e7f5a: [8] System error: read parent: connection reset by peer\n"

Mar 15 21:00:37.573: INFO: At 2016-03-15 20:59:52 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} Created: Created container with docker id 458d2586c22a
Mar 15 21:00:37.573: INFO: At 2016-03-15 20:59:52 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} Failed: Failed to start container with docker id 458d2586c22a with error: API error (500): Cannot start container 458d2586c22ab22f69b9865e4239301fc015b462cf6bd80b40ecd26e29827818: [8] System error: read parent: connection reset by peer

Mar 15 21:00:37.573: INFO: At 2016-03-15 20:59:52 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "test" with RunContainerError: "runContainer: API error (500): Cannot start container 458d2586c22ab22f69b9865e4239301fc015b462cf6bd80b40ecd26e29827818: [8] System error: read parent: connection reset by peer\n"

Mar 15 21:00:37.573: INFO: At 2016-03-15 21:00:05 -0700 PDT - event for pod2: {kubelet gke-upgrade-gke-1-0-1-2-0ce3b8e1-node-vmyg} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "test" with CrashLoopBackOff: "Back-off 20s restarting failed container=test pod=pod2_e2e-tests-services-leh8d(7fff9417-eb2b-11e5-83ea-42010af00002)"
```
Could be caused by https://github.com/docker/docker/issues/14203#issuecomment-174331054

**Comment by ihmccreery** [comment] 2016-04-04 19:01
@yujuhong Can I pass this off to you to close out?

**Comment by yujuhong** [comment] 2016-04-04 20:54
Assume https://github.com/docker/docker/issues/14203 is the cause, that has been fixed in the docker v1.10. The workaround seems to be to add extra padding to the command. I am not sure why this happens only in the upgrade test and whether we want to patch the test for this. @dchen1107, any thoughts?

**Comment by ihmccreery** [comment] 2016-04-26 20:57
Ping @yujuhong.  What's the status of this?

**Comment by yujuhong** [comment] 2016-05-10 00:17
Service tests are mostly passing, and the failed tests don't show the "read parent: connection reset by peer" error anymore.

**Closed by yujuhong** 2016-05-10 00:17 UTC
Labels: area/test, area/upgrade, priority/P1, team/node
