### ISSUE TITLE
PodDisruptionBudget maxUnavailable request feature

### ISSUE THREAD

**Issue by deimosfr** [kubernetes/kubernetes#43327] opened 2017-03-17 21:14 UTC
Hi,

I've started to play with PodDisruptionBudget and it's nice for a lot of use case. However, for distributed databases like Cassandra, Elasticsearch etc... minAvailable is not an optimal option because it has to be changed depending on the size of the cluster.

Those distributed databases are configured with a desired replicas. The number of replicas is critical for the cluster health. To give an example, on a 30 nodes cluster with a replica of 3, you can loose 2 servers at max. It's not convenient to set minAvailable, as the cluster size can change over the time, so we have to adapt it as well. Percentages is unfortunately not better.

I propose to add a new option called maxUnavailable. In this case, with a replicat of 3, setting maxUnavailable to 2 is perfect with any kind of cluster size.

What do you think ?

**Comment by kargakis** [comment] 2017-03-18 03:12
Dupe of https://github.com/kubernetes/kubernetes/issues/34776

**Closed by kargakis** 2017-03-18 03:12 UTC
