### ISSUE TITLE
Kube-dns is not running

### ISSUE THREAD

**Issue by Mandy27** [kubernetes/kubernetes#33671] opened 2016-09-28 17:45 UTC
I am trying to install Kubernetes on Linux with kubeadm. At step 4, after installing Weave net, I see that kube-dns status just shows ContainerCreating.

**Comment by luxas** [comment] 2016-09-28 19:13
@kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment] 2016-09-28 19:13
@Mandy27 Please give more information about the environment

**Comment by Mandy27** [comment] 2016-09-28 19:30
I am setting up 3 virtual machines using Ubuntu 16.04-server-amd64 with 4GB RAM, Kubernetes 1.4.0, and weave-kube:1.7.0

**Comment by JustinAzoff** [comment] 2016-09-29 02:04
Hi!

I ran into the same thing yesterday.  I was able to fix it but I'm not sure which change specifically fixed things.

kube-dns was failing to start because cni errors because weave was not installed or running on the master node.

The first thing I noticed is that https://github.com/weaveworks/weave-kube/releases/download/latest_release/weave-daemonset.yaml has a block that specifies that weave should not run on the master node.  I removed this and re-applied it and also ran the

    kubectl taint nodes --all dedicated-

to get it to try to schedule weave-net on the master node.

The next issue that I ran into is that the VMs I created to test things had 1 cpu.  After all the base containers were started there was not enough cpu 'free' to schedule weave-net.  I tried tweaking some of the cpu settings in services but ended up just adding another cpu to the VM.

After weave-net finally started on the master node, kube-dns started right up and most things are functional.

The next issue that I ran into that I haven't fully fixed is that things mostly work, but none of my service addresses are reachable.  It works if I use the pod IP but not the service IP:

    $ kubectl run -i -t busybox --image=busybox --restart=Never
    / # nslookup kubernetes.default 10.46.0.2
    Server:    10.46.0.2
    Address 1: 10.46.0.2 kube-dns-2247936740-01bb9

    Name:      kubernetes.default
    Address 1: 100.64.0.1 kubernetes.default.svc.cluster.local

    / # nslookup kubernetes.default
    Server:    100.64.0.10
    Address 1: 100.64.0.10

    nslookup: can't resolve 'kubernetes.default'

    / # ping 10.46.0.2
    PING 10.46.0.2 (10.46.0.2): 56 data bytes
    64 bytes from 10.46.0.2: seq=0 ttl=64 time=1.042 ms
    ^C
    --- 10.46.0.2 ping statistics ---
    1 packets transmitted, 1 packets received, 0% packet loss
    round-trip min/avg/max = 1.042/1.042/1.042 ms
    / # ping 100.64.0.1
    PING 100.64.0.1 (100.64.0.1): 56 data bytes
    ^C
    --- 100.64.0.1 ping statistics ---
    4 packets transmitted, 0 packets received, 100% packet loss
    / # 
    
I don't think that's a problem with dns, seems something is broken in general with the iptables rules that redirect things.  The rules in KUBE-SERVICES exist but have no matching packets.

**Comment by paweloczadly** [comment] 2016-09-29 10:25
I have the same issue as @Mandy27 . My environment: AWS, 3 instances, Ubuntu 16.04, 4CPU 8GB RAM

**Comment by lukemarsden** [comment] 2016-09-29 11:20
cc @bboreham

**Comment by bboreham** [comment] 2016-09-29 11:44
I see several issues mentioned: 

> not enough cpu 'free' to schedule weave-net

Can you give some details on the exact figures? We tried to tweak the numbers to sneak under the line.

    nslookup: can't resolve 'kubernetes.default'

what does `/etc/resolv.conf` point to in that container?

> icmp probably isn't supposed to work 

right - kube-proxy only creates rules for the services it knows about, which are typically on tcp ports.

> testing with tcp fails the same way

Can you give more details?

What is supposed to happen is kube-proxy creates iptables rules in the host namespace which redirect to the pod IP(s).  So take a look at `iptables-save` on the host and see if you can see those rules.

**Comment by JustinAzoff** [comment] 2016-09-29 14:12
> Can you give some details on the exact figures? We tried to tweak the numbers to sneak under the line.

I'd have to blow the cluster away and start over to get the right logs again.  I just know it was complaining about 'OutOfcpu'.  I think adding the 2nd vCPU helped more than trying to tweak the cpu request params.  With everything running now after the changes I made I get:

```
Namespace         Name                            CPU Requests    CPU Limits  Memory Requests Memory Limits
---------         ----                            ------------    ----------  --------------- -------------
kube-system       etcd-kube1                      200m (10%)      0 (0%)      0 (0%)          0 (0%)
kube-system       kube-apiserver-kube1            250m (12%)      0 (0%)      0 (0%)          0 (0%)
kube-system       kube-controller-manager-kube1   200m (10%)      0 (0%)      0 (0%)          0 (0%)
kube-system       kube-discovery-1971138125-63ebx 0 (0%)          0 (0%)      0 (0%)          0 (0%)
kube-system       kube-dns-2247936740-01bb9       210m (10%)      210m (10%)  390Mi (21%)     390Mi (21%)
kube-system       kube-proxy-amd64-wwnw6          0 (0%)          0 (0%)      0 (0%)          0 (0%)
kube-system       kube-scheduler-kube1            100m (5%)       0 (0%)      0 (0%)          0 (0%)
kube-system       weave-net-bnpey                 400m (20%)      400m (20%)  0 (0%)          0 (0%)
Allocated resources:
(Total limits may be over 100 percent, i.e., overcommitted.
CPU Requests  CPU Limits  Memory Requests Memory Limits
------------  ----------  --------------- -------------
1360m (68%)   610m (30%)  390Mi (21%)     390Mi (21%)
```

> what does /etc/resolv.conf point to in that container?

It has `nameserver 100.64.0.10`

Which matches this:

```
[root@kube1 ~]# kubectl get svc -o wide --namespace=kube-system
NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE       SELECTOR
kube-dns               100.64.0.10      <none>        53/UDP,53/TCP   1d        name=kube-dns
...
```

The iptables rules are there, but I notice a few things.

They are constantly being re-added and the order changes:

```
[root@kube1 ~]# alias show='iptables -nv -t nat -L  KUBE-SERVICES|cut -c 1-35'
[root@kube1 ~]# show;sleep 2;show
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in
    0     0 KUBE-SVC-ERIFXISQEP7F7O
    0     0 KUBE-SVC-XGLOHA7QRQ3V22
    0     0 KUBE-SVC-C6CKJB4ETKECGE
    0     0 KUBE-SVC-H7VQWWG5YKBL3K
    0     0 KUBE-SVC-AZSKWM7CYTUZVH
    0     0 KUBE-SVC-NPX46M4PTMTKRN
    0     0 KUBE-SVC-TCOU7JCQXEZGVU
    4   294 KUBE-NODEPORTS  all  --
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in
    0     0 KUBE-SVC-C6CKJB4ETKECGE
    0     0 KUBE-SVC-H7VQWWG5YKBL3K
    0     0 KUBE-SVC-AZSKWM7CYTUZVH
    0     0 KUBE-SVC-NPX46M4PTMTKRN
    0     0 KUBE-SVC-TCOU7JCQXEZGVU
    0     0 KUBE-SVC-ERIFXISQEP7F7O
    0     0 KUBE-SVC-XGLOHA7QRQ3V22
    8   480 KUBE-NODEPORTS  all  --
```

There's an empty `KUBE-SERVICES` chain in the main iptables ruleset:

```
[root@kube1 ~]# iptables -L KUBE-SERVICES
Chain KUBE-SERVICES (1 references)
target     prot opt source               destination
```

Which may or may not be a problem.

If I follow: kubernetes.io/docs/user-guide/debugging-services/ I get this:

```
[root@kube1 ~]# kubectl get endpoints hostnames
NAME        ENDPOINTS                                      AGE
hostnames   10.32.0.3:9376,10.40.0.1:9376,10.46.0.2:9376   2m
[root@kube1 ~]# iptables-save | grep hostnames
-A KUBE-SEP-2NCOJPACPJ77HXT4 -s 10.32.0.3/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-2NCOJPACPJ77HXT4 -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.32.0.3:9376
-A KUBE-SEP-RJLKL7WVKNW77AEM -s 10.46.0.2/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-RJLKL7WVKNW77AEM -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.46.0.2:9376
-A KUBE-SEP-XQ4L6HFSGJWU2XON -s 10.40.0.1/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-XQ4L6HFSGJWU2XON -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.40.0.1:9376
-A KUBE-SERVICES -d 100.66.122.211/32 -p tcp -m comment --comment "default/hostnames: cluster IP" -m tcp --dport 80 -j KUBE-SVC-NWV5X2332I4OT4T3
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-2NCOJPACPJ77HXT4
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-XQ4L6HFSGJWU2XON
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -j KUBE-SEP-RJLKL7WVKNW77AEM
```

Now that I debug things further I realize that the service addresses work, but only on the nodes themselves:

```
[root@kube1 ~]# kubectl get svc hostnames
NAME        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
hostnames   100.66.122.211   <none>        80/TCP    9m

$ for x in 1 2 3;do ssh root@kube$x  curl -s 100.66.122.211:80;done
hostnames-3799501552-kbbie
hostnames-3799501552-0lcv2
hostnames-3799501552-kbbie
```

But if I start up a pod, it fails:
```
[root@kube1 ~]# kubectl run -i -t busybox --image=busybox --restart=Never
If you don't see a command prompt, try pressing enter.
/ # wget -O- 100.66.122.211:80
Connecting to 100.66.122.211:80 (100.66.122.211:80)
[hang]
```
The endpoints themselves work fine from a pod:

```
[root@kube1 ~]# kubectl get endpoints hostnames
NAME        ENDPOINTS                                      AGE
hostnames   10.32.0.3:9376,10.40.0.1:9376,10.46.0.2:9376   13m
[root@kube1 ~]# kubectl run -i -t busybox --image=busybox --restart=Never
/ # for e in 10.32.0.3:9376 10.40.0.1:9376 10.46.0.2:9376;do wget -O- $e 2>/dev/null;done
hostnames-3799501552-0lcv2
hostnames-3799501552-kbbie
hostnames-3799501552-ltxh0

**Comment by bboreham** [comment] 2016-09-29 14:21
Something's gone wrong here right away:

````
Namespace         Name                            CPU Requests    CPU Limits  Memory Requests Memory Limits
---------         ----                            ------------    ----------  --------------- -------------
kube-system       weave-net-bnpey                 400m (20%)      400m (20%)  0 (0%)          0 (0%)
````

we set:

````
            limits:
              cpu: 200m
            requests:
              cpu: 25m
````

So I wonder how your Requests got to 400m?  We run two containers so should be 50m total.

That said, taking it back to 50m would still leave your machine at 1010, i.e. overcommitted, so that's presumably why it wouldn't start.  Also of interest: your kube-dns is at 210m whereas mine is 110m.

**Comment by bboreham** [comment] 2016-09-29 14:28
Can you follow the service IP through iptables?

For instance I have a service at 10.0.181.14:

````
# iptables-save | grep 10.0.181.14
-A KUBE-SERVICES ! -s 10.180.0.0/14 -d 10.0.181.14/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.181.14/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
````

follow to the next chain:

````
# iptables-save | grep KUBE-SVC-XGLOHA7QRQ3V22RZ
:KUBE-SVC-XGLOHA7QRQ3V22RZ - [0:0]
-A KUBE-SERVICES -d 10.0.181.14/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-PB47X3FGDP2NFANH
````

and finally:

````
# iptables-save | grep KUBE-SEP-PB47X3FGDP2NFANH
:KUBE-SEP-PB47X3FGDP2NFANH - [0:0]
-A KUBE-SEP-PB47X3FGDP2NFANH -s 10.40.0.3/32 -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-MARK-MASQ
-A KUBE-SEP-PB47X3FGDP2NFANH -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp -j DNAT --to-destination 10.40.0.3:9090
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-PB47X3FGDP2NFANH
````

so that's how it translates to the pod address 10.40.0.3.  

If you follow your 100.66.122.211 address similarly, what do you get?

**Comment by JustinAzoff** [comment] 2016-09-29 14:29
Well, I did tweak some things to try to make it work.. I think I see what may have happened.  It looks like I tried removing the requests block alltogether so that it just has `limits:` but no `requests:`

```
[root@kube1 ~]# kubectl get --namespace=kube-system ds weave-net -o yaml

...
        resources:
          limits:
            cpu: 200m
...
```

But if I look at the created pods, I see:

```
[root@kube1 ~]# kubectl get pods --namespace=kube-system   weave-net-bnpey -o yaml|grep resources: -A 4
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 200m
--
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 200m
```

So, perhaps trying to remove requests: causes it to default to what the limit is?  I'm not sure if that is expected behavior or not, but I guess it definitely made things worse.

**Comment by JustinAzoff** [comment] 2016-09-29 14:50
Hmm, my iptables rules are the same except the first KUBE-MARK-MASQ rule is missing.  Is that related to hairpinning?


If I run tcpdump on the node and wget in the pod I see it trying to get to the right place, but it's not happy about something.
```
[root@kube1 ~]# tcpdump -ne -i vethwe-datapath
tcpdump: WARNING: vethwe-datapath: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vethwe-datapath, link-type EN10MB (Ethernet), capture size 65535 bytes
14:42:03.165974 06:f8:c8:be:76:27 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 74: 10.32.0.2.53628 > 10.46.0.2.9376: Flags [S], seq 1521133101, win 27400, options [mss 1370,sackOK,TS val 42975725 ecr 0,nop,wscale 7], length 0
14:42:03.166019 e6:db:0f:11:ba:94 > ea:0b:37:8b:02:f6, ethertype IPv4 (0x0800), length 74: 10.46.0.2.9376 > 10.32.0.2.53628: Flags [S.], seq 866443898, ack 1521133102, win 27160, options [mss 1370,sackOK,TS val 40457315 ecr 42975725,nop,wscale 7], length 0
14:42:03.166616 ea:0b:37:8b:02:f6 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 54: 10.32.0.2.53628 > 10.46.0.2.9376: Flags [R], seq 1521133102, win 0, length 0
14:42:04.167953 06:f8:c8:be:76:27 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 74: 10.32.0.2.53628 > 10.46.0.2.9376: Flags [S], seq 1521133101, win 27400, options [mss 1370,sackOK,TS val 42976728 ecr 0,nop,wscale 7], length 0
14:42:04.168039 e6:db:0f:11:ba:94 > ea:0b:37:8b:02:f6, ethertype IPv4 (0x0800), length 74: 10.46.0.2.9376 > 10.32.0.2.53628: Flags [S.], seq 882100285, ack 1521133102, win 27160, options [mss 1370,sackOK,TS val 40458317 ecr 42976728,nop,wscale 7], length 0
14:42:04.168608 ea:0b:37:8b:02:f6 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 54: 10.32.0.2.53628 > 10.46.0.2.9376: Flags [R], seq 1521133102, win 0, length 0
```

If I hit the backend ip directly from the pod it works, but I notice the l2 headers are different:

```
tcpdump: WARNING: vethwe-datapath: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vethwe-datapath, link-type EN10MB (Ethernet), capture size 65535 bytes

14:42:31.095619 ea:0b:37:8b:02:f6 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 74: 10.32.0.2.54994 > 10.46.0.2.9376: Flags [S], seq 720397919, win 27400, options [mss 1370,sackOK,TS val 43003654 ecr 0,nop,wscale 7], length 0
14:42:31.095675 e6:db:0f:11:ba:94 > ea:0b:37:8b:02:f6, ethertype IPv4 (0x0800), length 74: 10.46.0.2.9376 > 10.32.0.2.54994: Flags [S.], seq 2326288113, ack 720397920, win 27160, options [mss 1370,sackOK,TS val 40485245 ecr 43003654,nop,wscale 7], length 0
14:42:31.096237 ea:0b:37:8b:02:f6 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 66: 10.32.0.2.54994 > 10.46.0.2.9376: Flags [.], ack 1, win 215, options [nop,nop,TS val 43003656 ecr 40485245], length 0
14:42:31.096247 ea:0b:37:8b:02:f6 > e6:db:0f:11:ba:94, ethertype IPv4 (0x0800), length 143: 10.32.0.2.54994 > 10.46.0.2.9376: Flags [P.], seq 1:78, ack 1,
```

Not sure where 06:f8:c8:be:76:27 is coming from

**Comment by bboreham** [comment] 2016-09-29 15:48
`KUBE-MARK-MASQ` is used to mark packets needing SNAT.  Things will likely break if you don't have that, though I can't immediately match it to your specific symptoms.

One difference between the two tcpdumps you show is that the first one has 3 MACs and the second one has 2.  The SYN-ACK is coming back to a different MAC than the SYN was sent from, which may well be why it is immediately rejected.  It may be illuminating to track down what all those MACs belong to.

**Comment by bboreham** [comment] 2016-09-29 15:51
@JustinAzoff can I confirm you are using the released version Kubernetes 1.4.0?  There was an issue fixed shortly before release where the `KUBE-MARK-MASQ` chain was overwritten - #32413

**Comment by JustinAzoff** [comment] 2016-09-29 16:20
I installed via the yum repo 2 days ago, so I have:

```
[root@kube1 ~]# rpm -qa|egrep -e kube  -e docker
kubectl-1.4.0-0.x86_64
kubernetes-cni-0.3.0.1-0.07a8a2.x86_64
kubelet-1.4.0-0.x86_64
docker-selinux-1.10.3-46.el7.centos.14.x86_64
kubeadm-1.5.0-0.alpha.0.1534.gcf7301f.x86_64
docker-common-1.10.3-46.el7.centos.14.x86_64
docker-1.10.3-46.el7.centos.14.x86_64

[root@kube1 ~]# kubelet --version
Kubernetes v1.4.0

[root@kube1 ~]# docker ps|awk '{print $2}'|grep kube
gcr.io/google_containers/kube-dnsmasq-amd64:1.3
gcr.io/google_containers/kubedns-amd64:1.7
gcr.io/google_containers/kube-discovery-amd64:1.0
weaveworks/weave-kube:1.7.0
gcr.io/google_containers/kube-proxy-amd64:v1.4.0
gcr.io/google_containers/kube-controller-manager-amd64:v1.4.0
gcr.io/google_containers/kube-apiserver-amd64:v1.4.0
gcr.io/google_containers/kube-scheduler-amd64:v1.4.0

```

I tracked down 06:f8:c8:be:76:27, it's the address of the `weave` interface on my kube3 box where the busybox container is running.

Running tcpdump on that interface shows

```
16:11:46.331684 ea:0b:37:8b:02:f6 > 06:f8:c8:be:76:27, ethertype IPv4 (0x0800), length 74: 10.32.0.2.55794 > 100.66.122.211.http: Flags [S], seq 665822039, win 27400, options [mss 1370,sackOK,TS val 48358896 ecr 0,nop,wscale 7], length 0
16:11:46.331725 06:f8:c8:be:76:27 > f6:58:25:9d:7f:10, ethertype IPv4 (0x0800), length 74: 10.32.0.2.55794 > 10.40.0.1.9376: Flags [S], seq 665822039, win 27400, options [mss 1370,sackOK,TS val 48358896 ecr 0,nop,wscale 7], length 0
16:11:46.332448 f6:58:25:9d:7f:10 > ea:0b:37:8b:02:f6, ethertype IPv4 (0x0800), length 74: 10.40.0.1.9376 > 10.32.0.2.55794: Flags [S.], seq 660431814, ack 665822040, win 27160, options [mss 1370,sackOK,TS val 48356670 ecr 48358896,nop,wscale 7], length 0
16:11:46.332464 ea:0b:37:8b:02:f6 > f6:58:25:9d:7f:10, ethertype IPv4 (0x0800), length 54: 10.32.0.2.55794 > 10.40.0.1.9376: Flags [R], seq 665822040, win 0, length 0
```

Which seems like it shows the same thing but flipped.. I'm not sure if that is expected or not, I don't have a working setup to compare it to.

**Comment by bboreham** [comment] 2016-09-29 16:35
We can see the problem more clearly there - the SYN packet is sent off toward 100.66.122.211:80, but the SYN-ACK comes back from 10.40.0.1:9376.  Pretty sure this is some kind of NAT problem.

Does restarting kube-proxy help?  Or rebooting?

**Comment by JustinAzoff** [comment] 2016-09-29 16:49
Rebooted all 3 nodes again, same thing once everything came back up.  Pod IPs work but not service IPs.

**Comment by bboreham** [comment] 2016-09-29 16:58
And you still don't have that `KUBE-MARK-MASQ` rule?

**Comment by JustinAzoff** [comment] 2016-09-29 16:59
Correct:

```
[root@kube1 ~]# iptables-save | grep 100.66.122.211
-A KUBE-SERVICES -d 100.66.122.211/32 -p tcp -m comment --comment "default/hostnames: cluster IP" -m tcp --dport 80 -j KUBE-SVC-NWV5X2332I4OT4T3
```

**Comment by bboreham** [comment] 2016-09-29 17:01
CC @thockin - any idea what can cause the masquerade rule to be absent?

**Comment by yoks** [comment] 2016-09-29 17:14
Has same issue, Centos72. ClusterIP not working. Will provide details later.

**Comment by johscheuer** [comment] 2016-09-29 18:56
It looks like headless services are also broken, I got the following config:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  clusterIP: "None" # headless service => kube-dns will return pod IPs
  ports:
    - name rpc
      port: 7866
      protocol: TCP
    - name: rpc-udp
      port: 7866
      protocol: UDP
    - name: http
      port: 7876
      protocol: TCP
  selector:
    role: registry
```

And when I query the service with `nslookup` it doesn't return anything but there are endpoints:

```bash
kubectl get endpoints
NAME         ENDPOINTS                                      AGE
registry     10.44.0.2:7866,10.44.0.2:7866,10.44.0.2:7876   2h
```

Also the query takes a very long time to fail:

```bash
kubectl exec -ti debug -- sh 
/# nslookup registry
Server:    100.64.0.10
Address 1: 100.64.0.10

nslookup: can't resolve 'registry'
```

I run on CentOS 7.2 with weave (and used kubeadm).

**Comment by bboreham** [comment] 2016-09-29 19:30
@johscheuer it's going to get too difficult to maintain multiple threads of conversation in this one issue; please open your own issue.  Can you confirm there that kube-dns is not running; if so please do `kubectl describe node` for the node it should be running on.

**Comment by bboreham** [comment] 2016-09-29 19:32
So far none of the points raised have related to Kubeadm; can someone with permission change the label to "networking" or something like that?

**Comment by JustinAzoff** [comment] 2016-09-29 20:06
Hmm, that could be the same same issue.. If the pod ip isn't working dns lookups fail even though kube-dns is running.  So it's not that headless services are broken, you just can't query dns.

Does it work if you do this:

```
[root@kube1 ~]# kubectl get endpoints --namespace=kube-system kube-dns
NAME       ENDPOINTS                   AGE
kube-dns   10.46.0.4:53,10.46.0.4:53   1d
```

Find what the kube-dns pod ip is (10.46.0.4 in my case), then back in your debug container, try

```
# nslookup registry 10.46.0.4
```

In my case I get:

```
/ # nslookup hostnames
Server:    100.64.0.10
Address 1: 100.64.0.10

nslookup: can't resolve 'hostnames'
/ # nslookup hostnames 10.46.0.4
Server:    10.46.0.4
Address 1: 10.46.0.4 kube-dns-2247936740-01bb9

Name:      hostnames
Address 1: 100.66.122.211 hostnames.default.svc.cluster.local
```

And yeah, I don't know how much of this is related to kubeadm specifically, other than that if you follow http://kubernetes.io/docs/getting-started-guides/kubeadm/ you end up here.

**Comment by johscheuer** [comment] 2016-09-29 21:09
@bboreham This issue could be related with kubeadm. So at first: kube-dns is running in my setup and I'm able to acces my dashboard (but no other services).

Running nslookup without specifying the kube-dns pod ip fails:
```bash
nslookup registry
Server:    100.64.0.10
Address 1: 100.64.0.10

nslookup: can't resolve 'registry'
```

when I specify the kube-dns pod ip everything works fine:
````bash
nslookup registry 10.36.0.3
Server:    10.36.0.3
Address 1: 10.36.0.3 kube-dns-2247936740-s5lu1

Name:      registry
Address 1: 10.44.0.4 debug
```

It's very suspiciously that all pods use `100.64.0.10` as default for DNS lookups and the `service-cidr`option from kubeadm defaults to this IP range:

```bash
--service-cidr value              Use alterantive range of IP address for service VIPs, defaults to 100.64.0.0/12 (default 100.64.0.0/12)
```

On one of my Nodes:

```bash
ifconfig weave
weave: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
        inet 10.32.0.1  netmask 255.240.0.0  broadcast 0.0.0.0
        inet6 fe80::c88:2dff:fe1a:e66c  prefixlen 64  scopeid 0x20<link>
        ether 0e:88:2d:1a:e6:6c  txqueuelen 0  (Ethernet)
        RX packets 366  bytes 21068 (20.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 303  bytes 23660 (23.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ifconfig | grep 100.64
```

and the iptables output:

```bash
[root@panel4 ~]# iptables-save | grep 100.64
-A KUBE-SERVICES -d 100.64.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 100.64.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -d 100.64.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
[root@panel4 ~]# iptables-save | grep KUBE-SVC-TCOU7JCQXEZGVUNU
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
-A KUBE-SERVICES -d 100.64.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-6RTHVOJVKE2IJ2GA
[root@panel4 ~]# iptables-save | grep KUBE-SEP-6RTHVOJVKE2IJ2GA
:KUBE-SEP-6RTHVOJVKE2IJ2GA - [0:0]
-A KUBE-SEP-6RTHVOJVKE2IJ2GA -s 10.36.0.3/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-6RTHVOJVKE2IJ2GA -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.36.0.3:53
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-6RTHVOJVKE2IJ2GA
```

**Comment by bboreham** [comment] 2016-09-29 21:37
For people who are getting the original symptom, that the weave pod wouldn't start on the master node, we have reduced the CPU request in the YAML config so it should now start.

`kubectl apply -f https://git.io/weave-kube` ought to be enough to reconfigure it, but you may want to do `kubectl delete -f https://git.io/weave-kube` first, then `apply`.

**Comment by bboreham** [comment] 2016-09-30 20:27
I believe kube-proxy will not work properly with Weave Net on Centos unless the following setting is made:

    echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

If it is the solution, we will integrate into weave-kube.

**Comment by JustinAzoff** [comment] 2016-09-30 20:49
Yes, that improved things immediately.

**Comment by bboreham** [comment] 2016-10-05 17:31
We have released [Weave Net 1.7.1](https://github.com/weaveworks/weave/releases/tag/v1.7.1) which will apply the `bridge-nf-call-iptables` setting by itself.

This won't change anything related to `KUBE-MARK-MASQ`, but I think that trail went cold.  Suggest this issue can be closed.

**Comment by luxas** [comment] 2016-10-05 17:41
Okay, closing this.

@Mandy27 and others; please open a new issue referencing this if the issue does persist with Weave 1.7.1

**Closed by luxas** 2016-10-05 17:41 UTC
Labels: area/networking, component/kubeadm

**Comment by RahulG115** [comment] 2019-03-13 06:32
dont forget to fflush default iptable rules on centos  before running kubelet service
