### ISSUE TITLE
Unexpected handling of invalid ingress annotation

### ISSUE THREAD

**Issue by lukasgr90** [kubernetes/kubernetes#82536] opened 2019-09-10 15:02 UTC
**What happened**:

I used kubectl to apply an Ingress resource with an annotation, whose value was accidentally an integer (instead of a string). The Kubernetes API server accepted the resource, but silently removed all annotations (also valid ones).

**What you expected to happen**:

I expected, that the server either rejects the resource or removes only the invalid annotation.

**How to reproduce it (as minimally and precisely as possible)**:

Create minimal Ingress resource file with one wrong typed annotation, e.g. *ingress.yaml* with:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invalid-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: 240
spec: 
    rules:
      - host: invalid-domain.invalid
```

Now apply it:

```
lukas@lukas-ThinkPad-T460p:~/Downloads$ kubectl apply -f ingress.yaml 
ingress.extensions/invalid-ingress created
```

Afterwards get the resource definition from the server:

```
lukas@lukas-ThinkPad-T460p:~/Downloads$ kubectl get -o yaml ingress invalid-ingress
[...]
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: [...]
  creationTimestamp: "2019-09-10T14:51:29Z"
  [...]
```

_metadata.annotations_ only contains the key _kubectl.kubernetes.io/last-applied-configuration_, but not _kubernetes.io/ingress.class_ from the original definition.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux compute-0017.prod.figo.systems 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz GenuineIntel GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment] 2019-09-11 04:43
duplicate of https://github.com/kubernetes/kubernetes/issues/59113

fix in progress in https://github.com/kubernetes/kubernetes/pull/80371

/close

**Closed by liggitt** 2019-09-11 04:43 UTC
Labels: kind/bug, sig/cli
