### ISSUE TITLE
Kubelet fails to create kubernetes/pause image.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#14357] opened 2015-09-22 15:12 UTC
I noticed this while testing:
```
Name:				test-ss20y
Namespace:			default
Image(s):			kubernetes/pause
Node:				e2e-test-gmarek-minion-rdtw/10.240.113.178
Labels:				run=test
Status:				Running
Reason:				
Message:			
IP:				10.245.1.187
Replication Controllers:	test (10/10 replicas created)
Containers:
  test:
    Image:		kubernetes/pause
    State:		Running
      Started:		Tue, 22 Sep 2015 17:01:43 +0200
    Ready:		True
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	True 
Events:
  FirstSeen				LastSeen			Count	From					SubobjectPath				Reason		Message
  Tue, 22 Sep 2015 17:01:32 +0200	Tue, 22 Sep 2015 17:01:32 +0200	1	{scheduler }									Scheduled	Successfully assigned test-ss20y to e2e-test-gmarek-minion-rdtw
  Tue, 22 Sep 2015 17:01:32 +0200	Tue, 22 Sep 2015 17:01:32 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	implicitly required container POD	Pulled		Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Tue, 22 Sep 2015 17:01:33 +0200	Tue, 22 Sep 2015 17:01:33 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	implicitly required container POD	Started		Started with docker id 508d44ef5505
  Tue, 22 Sep 2015 17:01:33 +0200	Tue, 22 Sep 2015 17:01:33 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Pulling		Pulling image "kubernetes/pause"
  Tue, 22 Sep 2015 17:01:33 +0200	Tue, 22 Sep 2015 17:01:33 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Failed		Failed to create docker container with error: no such image
  Tue, 22 Sep 2015 17:01:33 +0200	Tue, 22 Sep 2015 17:01:33 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Pulled		Successfully pulled image "kubernetes/pause"
  Tue, 22 Sep 2015 17:01:33 +0200	Tue, 22 Sep 2015 17:01:33 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	implicitly required container POD	Created		Created with docker id 508d44ef5505
  Tue, 22 Sep 2015 17:01:43 +0200	Tue, 22 Sep 2015 17:01:43 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Pulled		Container image "kubernetes/pause" already present on machine
  Tue, 22 Sep 2015 17:01:43 +0200	Tue, 22 Sep 2015 17:01:43 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Created		Created with docker id cd04002797d8
  Tue, 22 Sep 2015 17:01:43 +0200	Tue, 22 Sep 2015 17:01:43 +0200	1	{kubelet e2e-test-gmarek-minion-rdtw}	spec.containers{test}			Started		Started with docker id cd04002797d8
```

cc @dchen1107 @yujuhong

**Comment by dchen1107** [comment] 2015-09-22 16:38
The issue reported here is not a real bug. Kubelet pulls the image, then start create container without checking if the image is present or not. Container creation is failed due to NoImage error, and return earlier. Next syncloop, Kubelet will reconcile the state again. Eventually, the image puller is done, container is created and run.

**Comment by dchen1107** [comment] 2016-01-29 06:23
Like what I mentioned above, there is no bug. We also change our image pulling to serialization for 1.1 release. After that, we didn't see NoImage error caused by corrupted image. Close the issue.

**Closed by dchen1107** 2016-01-29 06:23 UTC
Labels: component/kubelet, kind/cleanup, priority/P2, team/node
