### ISSUE TITLE
[Failing Test] gce-windows-1909-master (ci-kubernetes-e2e-windows-gce-1909)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87974] opened 2020-02-10 09:59 UTC
**Which jobs are failing**:
`gce-windows-1909-master (ci-kubernetes-e2e-windows-gce-1909)`

**Which test(s) are failing**:
```
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]
```

**Since when has it been failing**:
`2nd Feb 09:25 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master

**Reason for failure**:
```console
Feb  9 21:43:59.133: FAIL: Unexpected error:
    <*errors.errorString | 0xc005adcdf0>: {
        s: "service is not reachable within 2m0s timeout on endpoint 34.82.254.112:30053 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 34.82.254.112:30053 over TCP protocol
occurred
skipped 165 lines unfold_more
STEP: Destroying namespace "services-7529" for this suite.
[AfterEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:696
```

**Anything else we need to know**:
/sig windows
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18

**Comment by pjh** [comment] 2020-02-13 22:31
This is a duplicate of #87785.

/close

**Closed by pjh** 2020-02-13 22:31 UTC
Labels: kind/failing-test, priority/critical-urgent, sig/windows
