### ISSUE TITLE
e2e missing: verify heapster running and not flapping

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20100] opened 2016-01-25 19:12 UTC
We've had issues with crashlooping heapster (#19986) and indirect test failures of HPA due to broken heapster (?).  It appears we have insufficient coverage of heapster?  That is, a test that verifies heapster is running and not crashlooping would have made such issues much easier to debug and point directly to root cause?

**Comment by vishh** [comment] 2016-01-25 20:30
We have a monitoring-e2e test that has been verifying the availability of heapster. I guess that tests is not run on GKE clusters. 
It is possible to add a test that will validate heapster as a standalone entity. Heapster repo runs that test currently against HEAD and all PRs in the repo. We can repurpose that test to run on kube e2e as well. 
But, @piosz and @mwielgus are working on a new version of heapster with *new* APIs and so adding a test against the old APIs is not ideal. 

Perhaps a test that validates the stability of all kube-system namespace pods should be good enough?

**Comment by piosz** [comment] 2016-01-26 09:52
HPA e2e tests should catch crashlooping Heapster. Together with #19986 we had a regression in autoscaling suite #19896. I think we don't need any extra tests for crashlooping Heapster.

**Comment by piosz** [comment] 2016-01-26 09:59
I checked and HPA e2e tests don't run for GKE. How about enabling them (there are 2 tests, each of them last for 15-20 minutes, once the new version of Heapster is deployed should be less)?

cc @ihmccreery

**Comment by ihmccreery** [comment] 2016-01-26 17:30
Yes, this is why I filed #19542: to standardize what tests we're running where.  If you need more information to finish that, please let me know.

**Comment by piosz** [comment] 2016-01-26 20:06
@ihmccreery #19542 is about tests that are disabled as for now due to various reasons and are not related to this issue. [horizontal_pod_autoscaling](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/horizontal_pod_autoscaling.go#L51) e2e tagged as [Feature:Autoscaling] is running in autoscaling e2e suite and should be run also in some GKE suite. The question is which GKE suite is appropriate for it since there are 2 tests which last 30 minutes in total. AFAIR there was a gke-feature suite dedicated for such purposes but it was removed.

cc @zmerlynn

**Comment by ihmccreery** [comment] 2016-01-26 22:38
Ah, okay, so HPA falls into the "this is a feature that can't be tested in our core suites, so it needs to be a special snowflake".  What are the requirements for it, besides that it takes a long time?  Extra quota?  Let me know, and I can create a job for it in GKE.

**Comment by piosz** [comment] 2016-01-27 08:03
No special requirements besides running Heapster, which is default for GKE. It should work out of the box.

**Comment by ihmccreery** [comment] 2016-01-29 18:36
Closed via #20274

**Comment by dchen1107** [comment] 2016-01-29 19:07
@piosz I reopen this one. Obviously heapster crashloop due to node reboot causes a lot of test flakiness. Can we make sure it running not flapping after reboot? Thanks!

**Comment by vishh** [comment] 2016-01-29 19:19
Will an explicit test for heapster help here? Such a test will be carry less dependencies and be easier to debug in case of a failure.

**Comment by ihmccreery** [comment] 2016-01-29 19:39
^ @piosz

**Comment by piosz** [comment] 2016-01-31 07:25
From my investigation (local run) it seems that Heapster is not crashlooping after node reboot tests but it rather crashes a number of times during the reboot test which causes BackOff to be increased to 5min or so. Because of that Heapster is not able to recover within the given timeout but shortly after the reboot test is ended it comes back the normal state.

The issue here is the high number of restarts of Heapster (20 vs ~6 for other addons), which I'll investigate.

Some time ago @yujuhong suggested somewhere to decrease BackOff period in test configuration which should help in this case.

Instead of adding a new test test for it, we can add a check to reboot test for the number of restarts of Heapster. WDYT?

**Comment by thockin** [comment] 2016-02-01 19:05
Why is it crashing?

**Comment by yujuhong** [comment] 2016-02-01 19:47
There are two issue:.
 1. A functioning heapster sometimes takes a while (a few restarts) to become stable. That's what @piosz said in https://github.com/kubernetes/kubernetes/issues/20100#issuecomment-177421654. This could be due to missing dependency (e.g. influxdb) or other issues. One related issue to fix this is #20247. The bottom line, IMO, is that heapster should not crash so often. 
 2. A broken heapster (caused by upgrading to a bad version) either crash loops or causes other issues (e.g., https://github.com/kubernetes/kubernetes/issues/20231#issuecomment-175890410). This has happened a couple of times in the past two weeks. 

In either cases, it's annoying that heapster problem manifests indirectly in the reboot and other tests, which requires a lot of digging. A simple test running in per-PR jenkins to ensure heapster functions will at least blocks issues like (2).

As for (1), since it only manifests at node startup, reboot test might be the best place to verify that. I am okay with that as long as we make sure the error is surfaced clearly.

**Comment by thockin** [comment] 2016-02-03 19:20
update on this one?

**Comment by vishh** [comment] 2016-02-03 22:43
One more note: We had a simple test that validated heapster as part of jenkins PR builder. It has been marked flaky for a while. De-flaking that is also an option to move forward.

**Comment by piosz** [comment] 2016-02-04 14:14
@mwielgus @fgrzadkowski are working on fixing issues with failing Heapster. Not sure whether it makes sense to create a separate test for this purpose. HPA e2e seems to verify whether Heapster is running or not. Regarding reboot tests we will try to decrease the number of 'expected' crashes of Heapster.

@vishh which test? Monitoring e2e? I've just ported it to new version of Influxdb so it should work now.

**Comment by vishh** [comment] 2016-02-04 18:40
@piosz: Yes. Monitoring e2e. AFAIK it was [marked as flaky](
https://github.com/kubernetes/kubernetes/blob/f3429776c236da44b1b7d1c321f1e981f2ac791e/test/e2e/monitoring.go#L35
).
Should we not require InfluxDB and instead test heapster using its REST
API? InfluxDB has failed on node reboots in the past due to checkpointing
issues. Relevant issue: #20247

**Comment by zmerlynn** [comment] 2016-02-04 23:26
I would like a test that is runnable on GKE, so the InfluxDB requirement is somewhat of a non-starter. Given that I spent a good chunk of a weekend chasing basically a Heapster flap on the reboot tests, I think it would give us a better signal.

**Comment by thockin** [comment] 2016-02-08 19:07
update?

**Comment by piosz** [comment] 2016-02-08 19:43
@mwielgus @fgrzadkowski made significant progress on decreasing the number of fails of Heapster during the reboot test last week. @yujuhong could you please verify it helped on Jenkins?

@vishh Monitoring e2e should work now. I'll try to promote it from flaky suite. HPA e2e tests cover Heapster REST API.

@zmerlynn HPA e2e tests are running in kubernetes-e2e-gke-serial right now.

Since we have some coverage of Heapster both in GCE and GKE decreasing the priority. I'll add a dedicated test for just Heapster, but I don't treat it as P0. Any objections?

**Comment by yujuhong** [comment] 2016-02-08 21:24
> @mwielgus @fgrzadkowski made significant progress on decreasing the number of fails of Heapster during the reboot test last week. @yujuhong could you please verify it helped on Jenkins?

I haven't seen this recently, but I also wasn't actively checking.  The crashlooping should be pretty obvious in bulid.log if anyone wants to check.

**Comment by bprashanth** [comment] 2016-02-17 00:25
@piosz I assume your test is still on track for surfacing issues in the 1.2 timeframe (asking for cluster team triage)?

**Comment by piosz** [comment] 2016-02-19 14:01
We have a basic HPA test which test Heapster. It's nice to have for 1.2 but it's not a blocker.

**Comment by spiffxp** [comment] 2017-06-15 21:29
/sig instrumentation
sending your way due to heapster

**Closed** 2018-02-26 00:42 UTC
Labels: area/monitoring, lifecycle/rotten, priority/backlog, sig/instrumentation, team/cluster (deprecated - do not use)
