### ISSUE TITLE
I cant do clustering in kubernetes..... [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.

### ISSUE THREAD

**Issue by lokeshjava28** [kubernetes/kubernetes#94068] opened 2020-08-18 04:45 UTC
How to resolve below error .... Please suggest

**What happened**: I have create kubernertes master and kubernetes node in aws. While i am clustering then i am faceing above error.
Note: I have taken 1 cpu only. 

**What you expected to happen**:  I want to create cluster in kubernetes. So please suggest how to resolve above issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):  Kubernetes version: v1.18.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`): root

**Comment by liggitt** [comment] 2020-08-18 12:33
Duplicate of https://github.com/kubernetes/kubernetes/issues/94067

**Closed by liggitt** 2020-08-18 12:33 UTC
Labels: kind/bug, needs-sig
