### ISSUE TITLE
If image download fails, kubelet is never able to spawn the pod

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#12670] opened 2015-08-13 17:24 UTC
As the title suggest, if for some reason docker ran into trouble pulling the image (could happen on private registries where all nodes are trying to pull a big  image at once), resulting in `docker images` showing the size of the image as `0 bytes` causes kubelet to be stuck in an infinite loop of trying to start the pod and failing with the following **docker** generated error:

```
Aug 13 17:18:54 minion1 kubelet[26303]: E0813 17:18:54.728489   26303 manager.go:1579] Error running pod "frontend-ba0f5_default" container "frontend": no such image
```

And this repeats endlessly.

To FIX: The administrator of the cluster can go into that particular node and `docker rmi` that image that shows `0 bytes`.  Ideally kubelet would do the same and carry on with life.

Doing the above manually fixes the issue and brings the pod up.

**Comment by brendandburns** [comment] 2015-08-13 17:29
Assigning to @dchen1107 for triage in the node team.

I think we can detect if Docker says the image is present, but the image fails to run, we can declare the image "corrupt" and remove it.

**Comment by dalanlan** [comment] 2015-08-14 12:50
AFAIK, scratch is also of a size 0.  Removing the image roughly could hurt.

**Comment by erictune** [comment] 2015-08-14 17:12
If imagePullPolicy is Always, does kubelet do a pull each time, and does
docker notice on the second pull that the previous pull was incomplete?

**Comment by danielschonfeld** [comment] 2015-08-31 16:12
@dchen1107 is this still expected out for v1.1?

**Comment by yujuhong** [comment] 2015-10-13 21:14
Related issue: #10623

**Comment by dchen1107** [comment] 2015-10-13 21:18
I tried to reproduce this issue by concurrently pulling both mysql:5.6 and postgres:9.4 , couldnt reproduce it. I also tried pulling both mysql and nginx, couldn't reproduce it.

Also please note that docker has a fix for such issue: https://github.com/docker/docker/issues/9718

**Comment by antoineco** [comment] 2015-10-13 21:26
@dchen1107 it's not the correct way to reproduce it. Your images must have a large enough set of layers in common. The ones your mentioned don't. Cf #10623

Docker 1.9.0 fixes that indeed!

**Comment by willmore** [comment] 2016-01-08 13:32
Hi folks - seeing this issue on our AWS-hosted cluster.
Looking at this and other related threads, it seems upgrading to Docker-1.9 could be what we need. However, 1.9 has not yet been validated. 
Could anyone provide guidance on what to do in the meantime? Perhaps run a reaper that monitors the cluster for "stuck" pods and kills them?

**Comment by dchen1107** [comment] 2016-02-12 00:07
I am going to close this one since:

* We changed concurrent image pulling to serial one by default since 1.1 release.
* We validated docker 1.9.1 (https://github.com/kubernetes/kubernetes/issues/16110), and the last remain issue is (https://github.com/kubernetes/kubernetes/issues/20995).

**Closed by dchen1107** 2016-02-12 00:07 UTC
Labels: component/kubelet, dependency/docker, priority/P1, team/node
