### ISSUE TITLE
TestPreemptionStarvation is flaking

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#61512] opened 2018-03-22 02:17 UTC
/kind flake
/area test
/sig scheduling
/sig testing

Examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61480/pull-kubernetes-integration/2949/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61498/pull-kubernetes-integration/2934/

It's the most flaky test among all integration tests: https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration

/assign bsalamat

**Comment by liggitt** [comment] 2018-03-23 16:31
/priority failing-test

looks like it just started around midnight on 3/20: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestPreemptionStarvation

**Comment by liggitt** [comment] 2018-03-23 16:32
seems to correspond with merge of Merge pull request #60953 from anfernee/sched-cache-resync

**Comment by bsalamat** [comment] 2018-03-23 17:08
I started investigating this issue since yesterday. The preemption part of the test happens correctly, but for some reason scheduler believes that there are still not enough CPU to schedule the Pod. I will provide more updates when I find the root cause.

**Comment by bsalamat** [comment] 2018-03-24 00:18
I spent quite a bit of time chasing this issue down and I think I now know what is going on. This issue is caused by a subtle race condition in equivalence cache. Equivalence cache is disabled by default, but [it is enabled in scheduler integration tests](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/util.go#L83).

Here is what happens:
1. Scheduler tries to schedule Pod A, but A is not schedulabe and requires preemption.
2. Scheduler preempts several Pods to make room for Pod A.
3. Pod deletion events start arriving for the preempted pods.
4. Deletion events trigger scheduling queue and scheduler tries scheduling Pod A again.
**Here are the important events (the race is between step 6 and 7):**
5. Scheduler determines that Pod A is not yet schedulable, because deletion of the last preempted Pod is not reflected in the scheduler cache. Let's call the last preempted Pod X.
6. Deletion of Pod X is observed and invalidates equivalence cache.
7. Scheduler updates equivalence cache by the result of step 5.
8. Since scheduler observed deletion of Pod X while it was attempting to schedule A, scheduler puts A back in the active queue to try again.
9. Scheduler tries again, but it uses equivalence cache results this time. The results which was put in step 7. Scheduler determines that A is not schedulable based on equivalence cache and no other event invalidates the equivalence cache.
Test times out.

I believe what has caused this issue is #60753.
@resouer

**Comment by resouer** [comment] 2018-03-24 04:56
It seems like the race is: 
```
Next schedule of preemptor pod A 
      happens before 
Cache of scheduler is updated by pod A. 
```

i.e. step 5 VS 6 instead of 6 VS 7

We should fix it in that case later.

**Comment by bsalamat** [comment] 2018-03-24 19:12
> i.e. race between 5 & 6 instead of 6 & 7, as we have two independent pod informers in factory.go.

Actually, I think it is between 6 & 7 and this is not caused by the two independent informers. It is between updating the eCache with predicate results and invalidating cache triggered by the informers.

**Comment by resouer** [comment] 2018-03-24 20:34
@bsalamat Oh, thanks for enlighten, it's much clear now.

This should happen when multiple Pods (let's say 3) are preempted by Pod A. And caused by the race between:

6. Deletion of 3rd preempted Pod  ---> update cache + **invalidate eCache** + trigger 3rd re-try of Pod A
7. Pod A 2nd re-try fail due to ---> **update eCache**

If **update eCache of 7** happens after **invalidate eCache of 6**, the 3rd re-try of Pod A will fail.

This is very subtle, thank you again for spending time on this.

Can we do something maybe bypass eCache for preemptor retry?

**Comment by resouer** [comment] 2018-03-25 18:27
/assign

Should include in equivalence cache for beta task.

**Comment by bsalamat** [comment] 2018-03-27 00:51
> If update eCache of 7 happens later than invalidate eCache of 6, the 3rd re-try of Pod A will fail.

Yes. Exactly.

> Can we do something maybe bypass eCache for preemptor retry? It's not easy to coordinate invalidate and update as they are expected to be independent operations.

I don't think this scenario is not limited to preemption. If a few pods are deleted almost at the same time for any reason, the same race condition can cause problem. In fact, the scenario is not limited to pod deletions either. If any scheduling condition that invalidate eCache (for example volumes are added, etc.) changes, similar race condition could potentially exist. I don't have any good ideas to address this problem efficiently at the moment. I need to think more about it.

**Comment by resouer** [comment] 2018-03-29 06:34
5. Scheduler determines that Pod A is not yet schedulable, because deletion of the last preempted Pod is not reflected in the scheduler cache. Let's call the last preempted Pod X.
6. Deletion of Pod X is observed and invalidates equivalence cache.
7. Scheduler updates equivalence cache by the result of step 5.

@bsalamat I am reviewing the race and one thing does make sense to me is:

Step 5 should be:
https://github.com/kubernetes/kubernetes/blob/30a8f7d1bd21af67dd24ab6d473adbe977519cf6/pkg/scheduler/core/generic_scheduler.go#L517

Step 7 should be:
https://github.com/kubernetes/kubernetes/blob/30a8f7d1bd21af67dd24ab6d473adbe977519cf6/pkg/scheduler/core/generic_scheduler.go#L532-L534

Shouldn't step 5~7 already be protected by the lock here?
https://github.com/kubernetes/kubernetes/blob/30a8f7d1bd21af67dd24ab6d473adbe977519cf6/pkg/scheduler/core/generic_scheduler.go#L507-L508

**Comment by bsalamat** [comment] 2018-03-29 18:51
One thing that still remains unanswered in mind is that what is in #58555 that triggers this.

**Comment by bsalamat** [comment] 2018-03-30 05:53
> If the root cause is stale information in scheduler cache, maybe what #58555 is only blamed for cached a invalid information as it makes eCacheAvailable.

But eCache has been available even without #58555. #58555 just changed the equivalence hashing algorithm.

**Comment by resouer** [comment] 2018-03-30 17:31
@bsalamat I mean before #58555, every retrying of preemptor Pod A will not be considered as equivalent (no `controllerRef`), so it will never run into this as during the last time of retry, cache should already be populated. 

Actually, I agree as you mentioned, this will happen when frequent updating of cache+ecache in handlers, but AFAIK, at least in our tests, it's only the case for preemption scenario.

That's why I am thinking we should have some way to check scheduler cache to decide if ecache should be updated or not.

**Comment by bsalamat** [comment] 2018-03-30 17:46
> I mean before #58555, every retrying of preemptor Pod A will not be considered as equivalent (no controllerRef), so it will never run into this as during the last time of retry, cache should already be populated.

Ah, yes, that explains why the PR causes this issue.

> Actually, I agree as you mentioned, this will happen when frequent updating of cache+ecache in handlers, but AFAIK, at least in our tests, it's only the case for preemption scenario.

You are probably right that this happens only in our preemption tests, but such a scenario can happen in my other situations in real clusters. For example, autoscaler may kill a few pods at the same time to shrink the cluster. Descheduler may do the same when trying to move pods elsewhere. A few pods may be killed by their controller at the same time, etc.

> That's why I am thinking we should have some way to check scheduler cache to decide if ecache should be updated or not.

That's a hack in my opinion and may work for now, but will probably come back again in another form in the future. I think we should have proper synchronization. If I find the time, I will try a few ideas to see if we can address it in the next few days.

**Comment by resouer** [comment] 2018-03-30 18:49
@bsalamat Thanks! Yep, I would also prefer a fundamental fix like way to sync with cache or eliminate nodeInfo copy. Let's think it over.

**Comment by bsalamat** [comment] 2018-04-03 18:32
As we discussed above, the issue is caused by updating the eCache with stale information. The main problem is that scheduler takes a snapshot of the scheduler cache at the beginning of a scheduling cycle and works with that snapshot throughout that cycle. Now, if the eCache is invalidated after the snapshot taken, but before the eCache is updated during the scheduling cycle, chances are that the eCache is updated with stale information.
There are two immediate solutions that come to my mind:
1. Put a lock at the beginning of a scheduling cycle to lock eCache and release it only after the scheduling cycle is over. This could possibly cause slow down as the lock is held for a long period of time and event processing could possibly get accumulated behind the lock. We would also need to ensure that this would not cause further issues with scheduling queue.
1. Remove the snapshotting of nodeInfo at the beginning of a scheduling cycle and let scheduler work with the real-time information from the scheduler cache. The scheduler cache has mutex locks to control reads and writes. Using the real-time information has the potential of creating race condition. This idea should be investigated further to ensure that it would not create race conditions. If this works, it could possibly improve performance as we won't need to snapshot the cache at the beginning of a scheduling cycle.

**Comment by resouer** [comment] 2018-04-10 23:07
@bsalamat I reviewed direct usage of nodeInfo in scheduler. One tricky race will be: what happens if eventually we cannot schedule nominated pod on the node?  We need some way to remove the nominated pods previously added during schedule.

Another option is, maybe we can lock nodeInfo (scheduler cache) before cloning it and release after the schedule? It's similar to what we did in #61644. The performance impact here is minor.

**Comment by resouer** [comment] 2018-04-11 03:29
@bsalamat  Sorry, I should have claim it clearer. I am referring to option 2: if we remove `nodeInfo.Clone()` in scheduler, there may be chances that nodeInfo is updated by nominated Pods during scheduling, but somehow, this change is invalid (e.g. nominated Pods will not be scheduled on that node eventually). Then we will have a "dirty" nodeInfo. And it seems no existing logic can fix this inconsistency.

The reason I mentioned this race (and a potential lock solution) is: it seems nodeInfo snapshot  interfered with ecache update only happens in addNominatedPods() in scheduler. Is that correct?

**Comment by bsalamat** [comment] 2018-04-12 00:31
> I am referring to option 2: if we remove nodeInfo.Clone() in scheduler, there may be chances that nodeInfo is updated by nominated Pods during scheduling, but somehow, this change is invalid (e.g. nominated Pods will not be scheduled on that node eventually). Then we will have a "dirty" nodeInfo. And it seems no existing logic can fix this inconsistency.

I am not referring to the snapshotting that happens during preemption. I am referring to [the snapshotting that is done by `UpdateNodeInfoMap`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L123) at the beginning of a scheduling cycle.

> The reason I mentioned this race (and a potential lock solution) is: it seems nodeInfo snapshot interfered with ecache update only happens in addNominatedPods() in scheduler. Is that correct?

That's not correct. Scheduler always gets a snapshot of nodeInfos at the beginning of a scheduling cycle and uses the snapshot for making scheduling decisions. This snapshotting makes the following scenario possible:

1. Scheduler takes a snapshot of nodeInfos.
2. eCache is invalidated.
3. Scheduler runs predicates with the snapshot taken at step 1.
4. Scheduler updates eCache with stale information based on the snapshot of step 1.

**Comment by misterikkit** [comment] 2018-04-20 22:58
I discussed potential solutions with @bsalamat and he suggested this approach:

Instead of locking eCache at the start and end of a scheduling cycle, signal the start and end to eCache. During one cycle, any update that arrives after any invalidation will be silently dropped.

This should solve the problem because we will never write to eCache with stale information. This won't change the scheduling decision from step 5 of Bobby's [scenario](https://github.com/kubernetes/kubernetes/issues/61512#issuecomment-375830364), but we will re-run the predicates with fresh information.

If it turns out we are discarding too many equivalence cache updates, we could get a little more granular, applying the above behavior on a per-node basis.

I will implement this along with a test that follows the scenario in https://github.com/kubernetes/kubernetes/issues/61512#issuecomment-375830364

**Comment by bsalamat** [comment] 2018-04-24 00:47
Closing this PR and following up on this problem on #62921.

**Closed by bsalamat** 2018-04-24 00:47 UTC
Labels: area/test, kind/flake, priority/failing-test, sig/scheduling, sig/testing
