### ISSUE TITLE
rhel7 K8s v1.20 installation error

### ISSUE THREAD

**Issue by rikeshpatel14** [kubernetes/kubernetes#111676] opened 2022-08-04 00:37 UTC
**Team** - Trying to install K8s utilities (kubelet, kubeadm, kubectl) using yum on RHEL 7, but getting an error mentioned below. Can you please inform whether the base-url [https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64] is correct, checking as am getting signature verification error. Appreciate your help. Thank you

**yum command**
`yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes`

**error**
`https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes`

**/etc/yum.repos.d/kubernetes.repo contents**
```
$ cat /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
```

**Referring K8s documentation** - [https://v1-20.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm]

**Comment by rikeshpatel14** [comment] 2022-08-04 00:46
@jimangel , @reylejano , @mikedanese , @ritazh , @dims - Can you please help

**Comment by neolit123** [comment] 2022-08-04 08:22
duplicate of
https://github.com/kubernetes/website/issues/32207
see the solutions there.

versions < 1.22 are out support, docs pages too.

/close

**Closed** 2022-08-04 08:22 UTC
Labels: needs-sig, needs-triage
