### ISSUE TITLE
Pods getting lost during deployment creation

### ISSUE THREAD

**Issue by kdima** [kubernetes/kubernetes#34007] opened 2016-10-04 10:58 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.4.0 with https://github.com/kubernetes/kubernetes/pull/33967 patch applied.

**Environment**:
- **Cloud provider or hardware configuration**: GCE + custom kubernetes
- **OS** (e.g. from /etc/os-release): "CoreOS 1068.8.0 (MoreOS)"
- **Kernel** (e.g. `uname -a`): : 4.6.3-coreos
- **Install tools**:
- **Others**:

**What happened**:
But pods seem to get lost. I.e. 
```
kubectl get pods
NAME                            READY     STATUS    RESTARTS   AGE
...other-pods
abcd-3456205130-83b2q           1/1       Running   0          22s
```

So first time around it comes up ok. Now I try to delete and create this deployment.
```
kubectl delete -f abcdController.json
deployment "abcd" deleted
kubectl create -f abcdController.json
deployment "abcd" created
```

After that I can not see my pod anywhere:
```
kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
..other-pods-- but abcd is not here
```

I can see the deployment though
```
kubectl describe deployment abcd
Name:			abcd
Namespace:		default
CreationTimestamp:	Tue, 04 Oct 2016 11:25:54 +0100
Labels:			k8s-app=abcd
			kubernetes.io/cluster-service=true
			version=v1.1.0-beta2
Selector:		k8s-app=abcd,version=v1.1.0-beta2
Replicas:		0 updated | 1 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
OldReplicaSets:		<none>
NewReplicaSet:		<none>
```

But there is no corresponding replica set for it.

Here are the logs from scheduler:
```
 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
Oct 04 10:25:44 h-stg-core-2 docker[3806]: I1004 10:25:44.570168       1 scheduler.go:135] Failed to bind pod: default/abcd-3456205130-15x25
Oct 04 10:25:44 h-stg-core-2 docker[3806]: E1004 10:25:44.570184       1 scheduler.go:137] scheduler cache ForgetPod failed: pod state wasn't assumed but get forgotten. Pod key: default/abcd-3456205130-15x25
Oct 04 10:25:44 h-stg-core-2 docker[3806]: E1004 10:25:44.570191       1 factory.go:530] Error scheduling default abcd-3456205130-15x25: Operation cannot be fulfilled on pods/binding "abcd-3456205130-15x25": pod abcd-3456205130-15x25 is being deleted, cannot be assigned to a host; retrying
Oct 04 10:25:44 h-stg-core-2 docker[3806]: I1004 10:25:44.570212       1 factory.go:607] Updating pod condition for default/abcd-3456205130-15x25 to (PodScheduled==False)
Oct 04 10:25:44 h-stg-core-2 docker[3806]: W1004 10:25:44.570362       1 factory.go:544] Request for pod default/abcd-3456205130-15x25 already in flight, abandoning
Oct 04 10:25:44 h-stg-core-2 docker[3806]: I1004 10:25:44.570380       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"abcd-3456205130-15x25", UID:"e84beb50-8a1c-11e6-85c8-42010a140005", APIVersion:"v1", ResourceVersion:"6090", FieldPath:""}): type: 'Normal' reason: 'FailedScheduling' Binding rejected: Operation cannot be fulfilled on pods/binding "abcd-3456205130-15x25": pod abcd-3456205130-15x25 is being deleted, cannot be assigned to a host
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod name is abcd-3456205130-15x25
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod node is h-stg-wk2-1
Oct 04 10:25:46 h-stg-core-2 docker[3806]: E1004 10:25:46.645429       1 factory.go:176] scheduler cache UpdatePod failed: no corresponding pod abcd-3456205130-15x25 in pods of node h-stg-wk2-1
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod name is abcd-3456205130-15x25
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod node is h-stg-wk2-1
Oct 04 10:25:46 h-stg-core-2 docker[3806]: E1004 10:25:46.722604       1 factory.go:176] scheduler cache UpdatePod failed: no corresponding pod abcd-3456205130-15x25 in pods of node h-stg-wk2-1
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod name is abcd-3456205130-15x25
Oct 04 10:25:46 h-stg-core-2 docker[3806]: Pod node is h-stg-wk2-0
Oct 04 10:25:46 h-stg-core-2 docker[3806]: (*api.Pod)(0xc421648000)(&TypeMeta{Kind:,APIVersion:,})
```

Here are thr logs from the worker node to which the new pod was originally assigned:
```
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.357190    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.475171    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.475232    3706 kubelet.go:1802] Failed to delete pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", err: pod not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.484023    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.492239    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.492298    3706 kubelet.go:1802] Failed to delete pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", err: pod not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.503775    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.516296    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.516384    3706 kubelet.go:1802] Failed to delete pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", err: pod not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.542153    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.561550    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.561617    3706 kubelet.go:1802] Failed to delete pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", err: pod not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.567041    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.588436    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.588497    3706 kubelet.go:1802] Failed to delete pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", err: pod not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.599215    3706 kubelet.go:1617] SyncLoop (ADD, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.657951    3706 docker_manager.go:1906] Need to restart pod infra container for "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)" because it is not found
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: E1004 10:25:44.688467    3706 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: E1004 10:25:44.842306    3706 docker_manager.go:1701] Failed to create symbolic link to the log file of pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)" container "POD": symlink  /var/log/containers/abcd-3456205130-15x25_default_POD-01ee72d6577afa46241df7223f26cc39cd7283c73ee0da2f4b98bbef7a3d6d79.log: no such file or directory
Oct 04 10:25:44 h-stg-wk2-1 kubelet[3706]: I1004 10:25:44.990313    3706 docker_manager.go:2167] Determined pod ip after infra change: "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)": "10.120.2.11"
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: I1004 10:25:45.023612    3706 provider.go:119] Refreshing cache for provider: *gcp_credentials.dockerConfigKeyProvider
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: I1004 10:25:45.024235    3706 config.go:156] body of failing http response: &{0x67b3f0 0xc421ada940 0x67b210}
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: E1004 10:25:45.024263    3706 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: I1004 10:25:45.024290    3706 provider.go:119] Refreshing cache for provider: *gcp_credentials.dockerConfigUrlKeyProvider
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: I1004 10:25:45.025291    3706 config.go:156] body of failing http response: &{0x67b3f0 0xc421ebfc40 0x67b210}
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: E1004 10:25:45.025342    3706 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
Oct 04 10:25:45 h-stg-wk2-1 kubelet[3706]: I1004 10:25:45.688160    3706 kubelet.go:1652] SyncLoop (PLEG): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", event: &pleg.PodLifecycleEvent{ID:"e84beb50-8a1c-11e6-85c8-42010a140005", Type:"ContainerStarted", Data:"01ee72d6577afa46241df7223f26cc39cd7283c73ee0da2f4b98bbef7a3d6d79"}
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.575266    3706 kube_docker_client.go:309] Stop pulling image "eu.gcr.io/ourproject/abcd:20160915.125444.4f55766": "Status: Downloaded newer image for eu.gcr.io/ourproject/abcd:20160915.125444.4f55766"
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: E1004 10:25:46.592392    3706 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: E1004 10:25:46.665024    3706 docker_manager.go:1701] Failed to create symbolic link to the log file of pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)" container "abcd": symlink  /var/log/containers/abcd-3456205130-15x25_default_abcd-5e1101ed8ce36529cc2013333649342d1b4e77c1010b434103cef97225bfd712.log: no such file or directory
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.693803    3706 kubelet.go:1633] SyncLoop (DELETE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.701327    3706 kubelet.go:1652] SyncLoop (PLEG): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)", event: &pleg.PodLifecycleEvent{ID:"e84beb50-8a1c-11e6-85c8-42010a140005", Type:"ContainerStarted", Data:"5e1101ed8ce36529cc2013333649342d1b4e77c1010b434103cef97225bfd712"}
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.765815    3706 kubelet.go:1633] SyncLoop (DELETE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.829842    3706 kubelet.go:1627] SyncLoop (REMOVE, "api"): "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)"
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.834246    3706 kubelet_pods.go:684] Killing unwanted pod "abcd-3456205130-15x25"
Oct 04 10:25:46 h-stg-wk2-1 kubelet[3706]: I1004 10:25:46.834344    3706 docker_manager.go:1497] Killing container "5e1101ed8ce36529cc2013333649342d1b4e77c1010b434103cef97225bfd712 abcd default/abcd-3456205130-15x25" with 0 second grace period
Oct 04 10:25:47 h-stg-wk2-1 kubelet[3706]: I1004 10:25:47.125227    3706 kube_docker_client.go:309] Stop pulling image "eu.gcr.io/ourproject/abcd:20160915.125444.4f55766": "Status: Image is up to date for eu.gcr.io/ourproject/abcd:20160915.125444.4f55766"
Oct 04 10:25:47 h-stg-wk2-1 kubelet[3706]: E1004 10:25:47.145497    3706 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Oct 04 10:25:47 h-stg-wk2-1 kubelet[3706]: E1004 10:25:47.229814    3706 docker_manager.go:1701] Failed to create symbolic link to the log file of pod "abcd-3456205130-15x25_default(e84beb50-8a1c-11e6-85c8-42010a140005)" container "abcd": symlink  /var/log/containers/abcd-3456205130-15x25_default_abcd-890b1ce28b2e4d504143f8328671b1557afd9a2354c4935a18cc1c7fc8c7b20b.log: no such file or directory
Oct 04 10:25:49 h-stg-wk2-1 kubelet[3706]: I1004 10:25:48.873541    3706 docker_manager.go:1536] Container "5e1101ed8ce36529cc2013333649342d1b4e77c1010b434103cef97225bfd712 abcd default/abcd-3456205130-15x25" exited after 2.039169678s
Oct 04 10:25:49 h-stg-wk2-1 kubelet[3706]: I1004 10:25:49.047405    3706 docker_manager.go:1497] Killing container "01ee72d6577afa46241df7223f26cc39cd7283c73ee0da2f4b98bbef7a3d6d79 default/abcd-3456205130-15x25" with 0 second grace period
Oct 04 10:25:49 h-stg-wk2-1 kubelet[3706]: I1004 10:25:49.091565    3706 docker_manager.go:1536] Container "01ee72d6577afa46241df7223f26cc39cd7283c73ee0da2f4b98bbef7a3d6d79 default/abcd-3456205130-15x25" exited after 44.115046ms
Oct 04 10:25:49 h-stg-wk2-1 kubelet[3706]: I1004 10:25:49.704178    3706 kubelet_pods.go:684] Killing unwanted pod "abcd-3456205130-15x25"
Oct 04 10:25:49 h-stg-wk2-1 kubelet[3706]: I1004 10:25:49.706872    3706 docker_manager.go:1497] Killing container "890b1ce28b2e4d504143f8328671b1557afd9a2354c4935a18cc1c7fc8c7b20b /" with 30 second grace period

```

**What you expected to happen**:
Expected my pod to appear.

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment, delete a deployment, create it again. seems to happen pretty regularly.

**Anything else do we need to know**:
Some of the original discussion is on #33967

**Comment by xiang90** [comment] 2016-10-04 11:19
You run multiple schedulers, right?

**Comment by kdima** [comment] 2016-10-04 11:20
yeap three of them

**Comment by xiang90** [comment] 2016-10-04 11:21
Can you provide more detailed information of your setup? Then we can reproduce this more easily. Thanks!

**Comment by kdima** [comment] 2016-10-04 11:42
We have three master nodes that are running apiserver, controller-manager and scheduler each. All of those are running inside the docker container. Kubeletes are running as binaries i.e. not inside docker.
We have two static worker nodes and one that is scaled by GCE scaler group. 
Here are the parameters with which we start those components.
All of those services are scheduled via fleet.
```
kube-apiserver
docker run --env-file=/etc/imp_environment --rm \
      --name=apiserver \
      --net=host \
      -v /data/auth:/data/auth \
      -v /svr/apiserver/tls:/svr/apiserver/tls:ro \
      ${HYPERKUBE_IMG}:${K8S_VERSION} \
      /hyperkube \
      apiserver \
      --v=2 \
      --etcd-servers=http://${COREOS_PRIVATE_IPV4}:2379 \
      --insecure-bind-address=127.0.0.1 \
      --insecure-port=8080 \
      --bind-address=0.0.0.0 \
      --secure-port=6443 \
      --service-cluster-ip-range=${SERVICE_CIDR} \
      --cloud-provider=gce \
      --allow-privileged=true \
      --advertise-address=${COREOS_PRIVATE_IPV4} \
      --kubelet-https=true \
      --external-hostname=master.${CLUSTER_NAME}.internal.{OUR_DOMAIN} \
      --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,ResourceQuota \
      --runtime-config=extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true \
      --tls-cert-file="/svr/apiserver/tls/apiserver.pem" \
      --tls-private-key-file="/svr/apiserver/tls/apiserver.key" \
      --client-ca-file="/svr/apiserver/tls/ca.crt" \
      --kubelet-certificate-authority="/svr/apiserver/tls/ca.crt" \
      --kubelet-client-certificate="/svr/apiserver/tls/kubelet.pem" \
      --kubelet-client-key="/svr/apiserver/tls/kubelet.key" \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --token-auth-file=/data/auth/token

kube-controller
docker run --env-file=/etc/imp_environment  --rm \
      -v /svr/controller-manager/tls:/svr/controller-manager/tls:ro \
      --net=host \
      --name=controller-manager \
      ${HYPERKUBE_IMG}:${K8S_VERSION} \
      /hyperkube \
      controller-manager \
      --master=http://127.0.0.1:8080 \
      --leader-elect=true \
      --address=0.0.0.0 \
      --cloud-provider=gce \
      --cluster-cidr="${POD_CIDR}" \
      --service-cluster-ip-range="${SERVICE_CIDR}" \
      --allocate-node-cidrs=true \
      --configure-cloud-routes=true \
      --cluster_name=${CLUSTER_NAME} \
      --root-ca-file=/svr/controller-manager/tls/ca.crt \
      --service-account-private-key-file="/svr/controller-manager/tls/apiserver.key" \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --port=10252 \
      --logtostderr=true --v=2

kube-proxy
docker run --env-file=/etc/imp_environment --net=host --privileged --rm \
 -v /sys:/sys:rw \
 -v /var/run:/var/run:rw \
 -v /var/lib/kubelet:/var/lib/kubelet:ro \
 -v /svr/kube-proxy/tls:/svr/kubernetes/tls:ro \
 --name=proxy \
 ${HYPERKUBE_IMG}:${K8S_VERSION} \
 /hyperkube \
 proxy \
 --master=https://master.${CLUSTER_NAME}.internal.{OUR_DOMAIN}:6443 \
 --proxy-mode=iptables --v=2 \
 --bind-address=0.0.0.0 \
 --kubeconfig=/var/lib/kubelet/kubeconfig \
 --feature-gates=AllowExtTrafficLocalEndpoints=true \
 --cluster-cidr="${POD_CIDR}" \
 --logtostderr=true

kube-scheduler
docker run --env-file=/etc/imp_environment --rm \
      --net=host \
      --name=scheduler \
      ${HYPERKUBE_IMG}:${K8S_VERSION} \
      /hyperkube \
      scheduler \
      --address="0.0.0.0" \
      --master=http://127.0.0.1:8080 \
      --leader-elect=true \
      --port=10251 --v=2 \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --logtostderr=true

kubelet-master
kubelet \
      --allow-privileged=true \
      --cloud-provider=gce \
      --api-servers=https://master.${CLUSTER_NAME}.internal.{OUR_DOMAIN}:6443 \
      --v=2 --address=0.0.0.0 --enable-server \
      --container-runtime=docker \
      --config=/etc/kubernetes/manifests \
      --cluster-dns=10.220.254.254 \
      --cluster-domain=${CLUSTER_NAME}.k8s.{OUR_DOMAIN} \
      --port=10250 \
      --read-only-port=10255 \
      --hostname-override=%H \
      --logtostderr=true \
      --tls-cert-file="/svr/kubernetes/tls/kubelet.pem" \
      --tls-private-key-file="/svr/kubernetes/tls/kubelet.key" \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --reconcile-cidr=true \
      --network-plugin=kubenet \
      --register-schedulable=false

kubelete-worker
kubelet \
      --allow-privileged=true \
      --cloud-provider=gce \
      --api-servers=https://master.${CLUSTER_NAME}.internal.{OUR_DOMAIN}:6443 \
      --v=2 --address=0.0.0.0 --enable-server \
      --container-runtime=docker \
      --config=/etc/kubernetes/manifests \
      --cluster-dns=10.220.254.254 \
      --cluster-domain=${CLUSTER_NAME}.k8s.{OUR_DOMAIN} \
      --port=10250 \
      --read-only-port=10255 \
      --hostname-override=%H \
      --logtostderr=true \
      --register-schedulable=true \
      --tls-cert-file="/svr/kubernetes/tls/kubelet.pem" \
      --tls-private-key-file="/svr/kubernetes/tls/kubelet.key" \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --reconcile-cidr=true \
      --network-plugin=kubenet \
      --node-labels="INSTANCE_TYPE=${INSTANCE_TYPE},INSTANCE_ROLE=${ROLE}"
```

Here is the definition of service and controller on which I managed to reproduce this issue. 
Service:
```
{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": {
         "service.alpha.kubernetes.io/external-traffic": "OnlyLocal"
      },
      "labels": {
         "k8s-app": "abcd",
         "kubernetes.io/cluster-service": "true"
      },
      "name": "abcd",
      "namespace": "default"
   },
   "spec": {
      "loadBalancerIP": "1.2.3.4",
      "ports": [
         {
            "name": "http-tls",
            "port": 443,
            "targetPort": 443
         },
         {
            "name": "grpc-tls",
            "port": 444,
            "targetPort": 444
         }
      ],
      "selector": {
         "k8s-app": "abcd"
      },
      "type": "LoadBalancer"
   }
}
```

Controller:
```
{
   "apiVersion": "extensions/v1beta1",
   "kind": "Deployment",
   "metadata": {
      "labels": {
         "k8s-app": "abcd",
         "kubernetes.io/cluster-service": "true",
         "version": "v1.1.0-beta2"
      },
      "name": "abcd",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "template": {
         "metadata": {
            "annotations": {
               "prometheus.io/path": "/_metrics",
               "prometheus.io/port": "8080",
               "prometheus.io/scheme": "http",
               "prometheus.io/scrape": "true"
            },
            "labels": {
               "k8s-app": "abcd",
               "version": "v1.1.0-beta2"
            }
         },
         "spec": {
            "containers": [
               {
                  "image": "gcr_registry/abcd:ducks",
                  "imagePullPolicy": "Always",
                  "name": "abcd",
                  "ports": [
                     {
                        "containerPort": 8080,
                        "name": "http"
                     },
                     {
                        "containerPort": 8081,
                        "name": "grpc"
                     },
                     {
                        "containerPort": 443,
                        "name": "http-tls"
                     },
                     {
                        "containerPort": 444,
                        "name": "grpc-tls"
                     }
                  ],
                  "volumeMounts": [
                     {
                        "mountPath": "/keys1/",
                        "name": "keys1",
                        "readOnly": true
                     },
                     {
                        "mountPath": "/keys2/",
                        "name": "keys2",
                        "readOnly": true
                     }
                  ]
               }
            ],
            "volumes": [
               {
                  "name": "keys1",
                  "secret": {
                     "secretName": "keys1"
                  }
               },
               {
                  "name": "keys2",
                  "secret": {
                     "secretName": "keys2"
                  }
               }
            ]
         }
      }
   }
}
```
Is there anything else you guys need?

**Comment by davidopp** [comment] 2016-10-05 04:49
cc/ @wojtek-t

**Comment by wojtek-t** [comment] 2016-10-05 09:12
@kdima - sorry I don't understand the logs you pasted at the beginning.
In particular, the recreated deployment has this:
```
CreationTimestamp:  Tue, 04 Oct 2016 11:25:54 +0100
```

And the logs from kubelet scheduler and kubelet you pasted are from ~Oct 04 10:25:44

Looking into "seconds" part of timestamps, it seems that those logs from kubelet and scheduler simply come from before the new deployment was created. So I think we are missing some logs to actually debug it...

**Comment by mwitkow** [comment] 2016-10-05 09:34
Hi @wojtek-t. Is there a slack channel where we can discuss this and pair up on this (Slack maybe)? we have time this week to help troubleshoot the issue. It's kind of blocking us from rolling out k8s 1.4 on our clusters.

**Comment by wojtek-t** [comment] 2016-10-05 09:37
e.g. https://kubernetes.slack.com/messages/kubernetes-dev/

**Comment by kdima** [comment] 2016-10-05 09:48
@wojtek-t Sorry for the confusion. These are the correct logs but time on my local box has drifted significantly that's why the creation time does not match the  seconds in the logs.

**Comment by kdima** [comment] 2016-10-19 20:39
We have figured out what happened. We were running CoreOS stable release which does not include recommended version of docker. After upgrading to CoreOS Beta with Docker version 1.11.2 this issue went away. Given how much effort tracking this down was I don't know if it might make sense to alert the user that they are running on a not recommended version of software.
Feel free to close the bug.

**Comment by xiang90** [comment] 2016-10-20 23:08
@kdima Good to know. I thought it is caused by a race somewhere (and assume https://github.com/kubernetes/kubernetes/pull/33967 wont totally fix it) in the scheduler cache code. 

now we know it is caused by docker version. closing this issue.

**Closed by xiang90** 2016-10-20 23:08 UTC
Labels: area/deployment, component/kubelet, kind/bug, priority/P1, team/control-plane, team/node

**Comment by zouyee** [comment] 2017-04-07 03:12
@xiang90  I think I have meet the same problem in v1.5.3

**Comment by zouyee** [comment] 2017-04-07 03:14
```kubectl describe deployment dex -n kube-system
Name:			dex
Namespace:		kube-system
CreationTimestamp:	Fri, 07 Apr 2017 18:43:35 +0800
Labels:			app=dex
Selector:		app=dex
Replicas:		0 updated | 1 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
OldReplicaSets:		<none>
NewReplicaSet:		<none>
No events.
[root@ys-2 ~]# kubectl describe deployment dex -n kube-system
Name:			dex
Namespace:		kube-system
CreationTimestamp:	Fri, 07 Apr 2017 18:43:35 +0800
Labels:			app=dex
Selector:		app=dex
Replicas:		0 updated | 1 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
OldReplicaSets:		<none>
NewReplicaSet:		<none>
No events.
```
and I do not found any replica about dex

**Comment by sabbour** [comment] 2018-04-11 06:52
@zouyee did you eventually figure this out?
