### ISSUE TITLE
Remove overlap annotation from Deployment

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#47463] opened 2017-06-13 22:21 UTC
It's safe to remove `OverlapAnnotation` now.

- [ ] deployment controller: pkg/controller/deployment/deployment_controller.go
- [ ] deployment util: pkg/controller/deployment/util/deployment_util.go
- [ ] deployment reaper: pkg/kubectl/stop.go
- [ ] deployment describer: pkg/printers/internalversion/describe.go

@kubernetes/sig-apps-misc

**Comment by kargakis** [comment] 2017-06-13 22:24
Dupe of https://github.com/kubernetes/kubernetes/issues/43322

**Comment by janetkuo** [comment] 2017-06-13 22:25
Copied the list to #43322

**Closed** 2017-06-13 22:25 UTC
Labels: area/workload-api/deployment, help-wanted, kind/technical-debt, sig/apps
