### ISSUE TITLE
CLI-based discovery of resources

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#45829] opened 2017-05-15 17:01 UTC
I can discover what API Groups are present on my cluster using `kubectl api-versions`.
However, I cannot find out what Kinds are in each Group.

If I knew what kinds there were, then I could do `kubectl get $KIND` or `kubectl explain $KIND`.

Top-down exploration will become more important as there are more TPRs and AAs being installed into clusters.

The request here is to have a command that tells the kinds inside a specific api-version.

**Comment by erictune** [comment] 2017-05-15 17:02
@mbohlool we talked about this the other day.

**Comment by liggitt** [comment] 2017-05-15 19:08
duplicate of https://github.com/kubernetes/kubernetes/issues/42932, I think

**Comment by liggitt** [comment] 2017-05-15 19:09
yup, with implementation in progress in https://github.com/kubernetes/kubernetes/pull/42873

**Closed by liggitt** 2017-05-15 19:09 UTC
Labels: kind/feature, priority/important-longterm, sig/api-machinery, sig/cli
