### ISSUE TITLE
volumeClaimTemplates with a StatefulSet schedules volumes on different AWS AZs

### ISSUE THREAD

**Issue by justicel** [kubernetes/kubernetes#40631] opened 2017-01-27 21:55 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: KOPS

**What happened**:

If you specify an array of VolumeClaimTemplates and attach multiple claims to a single container, the claims will nearly always/always get scheduled in different zones than each other. The yaml for such a template is:

  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: zookeeper
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 60Gi
  - metadata:
      name: logdir
      annotations:
        volume.beta.kubernetes.io/storage-class: zookeeper
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

**What you expected to happen**:
Claims get scheduled and created in AWS both on the same AZ as the scheduled container.

**How to reproduce it** (as minimally and precisely as possible):

Use the above volumeClaimTemplates data and a volume set on a StatefulSet like:
        volumeMounts:
        - name: datadir
          mountPath: /snapshots
        - name: logdir
          mountPath: /transactions

**Anything else do we need to know**:

Attaching a screenshot of the scheduled volumes for one of the containers each on a separate AZ.
![screen shot 2017-01-27 at 11 57 14 am](https://cloud.githubusercontent.com/assets/1320452/22388970/269f6916-e498-11e6-8e6b-9021b9e22d5f.png)

**Comment by justicel** [comment] 2017-01-27 21:55
@justinsb Per your request

**Comment by calebamiles** [comment] 2017-01-31 00:42
@kubernetes/sig-storage-bugs you might want to help triage this issue. Thanks!

**Comment by jsafrane** [comment] 2017-02-01 11:21
Duplicate of #35695

**Closed by jsafrane** 2017-02-01 11:21 UTC
Labels: kind/bug, sig/aws, sig/storage
