### ISSUE TITLE
Failing while trying to install k8s in ubuntu

### ISSUE THREAD

**Issue by GabyCT** [kubernetes/kubernetes#92558] opened 2020-06-26 20:20 UTC
I am trying to install kubernetes with the following steps in Ubuntu 18.04 LTS
```
$ sudo bash -c "cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial-unstable main
EOF"
$ sudo -E sed -i 's/^[ \t]*//' /etc/apt/sources.list.d/kubernetes.list
$ curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
$ sudo -E apt update
$ sudo -E apt install --allow-downgrades -y kubelet="$kubernetes_version" kubeadm="$kubernetes_version" kubectl="$kubernetes_version"
```
These steps were taken from https://kubernetes.io/es/docs/tasks/tools/install-kubectl/

However, while trying to perform 
```
$ curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
```
We are getting the following error
```
gpg: no valid OpenPGP data found.
```
I am trying to install the following kubernetes version
```
version: "1.17.3-00"
```

**Comment by justaugustus** [comment] 2020-06-28 10:34
@kubernetes/release-engineering -- Can someone assist @GabyCT?
/sig release
/area release-eng

**Comment by schweikert** [comment] 2020-06-28 15:22
I believe this might be caused by packages.cloud.google.com returning a status code 500, which is something that seems to affect some clients (and that Google is analyzing/fixing).

You can check with this command: `curl -o /dev/null -s -w "%{http_code}\n" "https://packages.cloud.google.com/apt/doc/apt-key.gpg"`

**Comment by schweikert** [comment] 2020-06-28 15:58
Note that this issue should be resolved now.

**Comment by GabyCT** [comment] 2020-06-29 14:32
@schweikert thank you, today I was able to install k8s
```
$ curl -o /dev/null -s -w "%{http_code}\n" "https://packages.cloud.google.com/apt/doc/apt-key.gpg"curl -o /dev/null -s -w "%{http_code}\n" "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
404
200
```

**Comment by mrbobbytables** [comment] 2020-07-30 11:46
It looks like this is resolved. 👍 
I'm going to go ahead and close it out. If there are any further issues, please go ahead and reopen.
Thanks!

/close

**Closed** 2020-07-30 11:46 UTC
Labels: area/release-eng, kind/bug, sig/release

**Comment by stevo-f3** [comment] 2023-02-27 17:33
I'm getting 500 again whole day.

Any known issue or some service EOL/migrated?

**Comment by stevo-f3** [comment] 2023-02-27 17:39
Fresh one with a workaround/new url https://github.com/kubernetes/kubernetes/issues/116100
