### ISSUE TITLE
Race condition in PVC protection controller can lead to deletion of PVC used by Pod

### ISSUE THREAD

**Issue by matte21** [kubernetes/kubernetes#76703] opened 2019-04-17 10:56 UTC
**What's the problem**: 

The [PVC protection controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go) aims to prevent deletion of PVCs used by Pods, as described [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/postpone-pvc-deletion-if-used-in-a-pod.md). To that end, when it processes a PVC with `deletionTimestamp` set, it does a [cache-based list of the Pods](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L212), and removes its finalizer from the PVC only if no Pod is using that PVC. In the current implementation there's a race condition. Consider the following sequence of events:

1. A Pod _P_ using an existing PVC _X_ is created and scheduled on a node _N_. Assume _X_ has no `deletionTimestamp` set and no other Pod is using it. 
2. Kubelet on _N_ is notified of _P_, does a [live look up of _X_ against the API server](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L563), [sees that 
`deletionTimestamp` is not set](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L572-L587) and moves on to starting the containers and mounting the volumes for _P_, including the one backing _X_.
3. The API Server receives a deletion request for _X_ and sets its `deletionTimestamp`.
4. PVC protection controller is notified of the update of _X_, sees that its `deletionTimestamp` is set, and uses its Pods Informer's cache to retrieve the Pods which are using _X_.

If at step 4 the PVC protection controller's Pods Informer's cache does not contain _P_ yet (and this is possible), the PVC protection controller will remove its finalizer from _X_ even if _X_ is being used by _P_, and this will trigger deletion of _X_.

**Proposed solution**:

Replace the cache-based list of Pods in the PVC protection controller with a live look up against the API server, i.e. use a [client](https://godoc.org/k8s.io/client-go/kubernetes#Interface). This way it's impossible for the PVC protection controller to miss a Pod that is using a PVC. This change is tiny code-wise since the PVC protection controller already uses a client to remove its finalizer from PVCs (alternatively a different client could be used to avoid sharing the same rate limiter if that's a problem). The con is that it's more load on the API server and more network bandwidth (it's a list of ALL the Pods). But deletion of PVCs is a rare event so that's probably not too much of a problem.
If there is consensus I'm willing to code this solution (or any solution that reaches consensus) and open a PR.

**How to reproduce it (as minimally and precisely as possible)**:

I don't know, any suggestion is welcome.

**Comment by matte21** [comment] 2019-04-17 10:59
@kubernetes/sig-storage-bugs

**Comment by MikeSpreitzer** [comment] 2019-04-22 15:43
This is the same as https://github.com/kubernetes/kubernetes/issues/75980

**Comment by liggitt** [comment] 2019-06-12 01:52
/close
duplicate of #75980

**Closed by liggitt** 2019-06-12 01:52 UTC
Labels: kind/bug, sig/storage
