### ISSUE TITLE
`kubectl set` commands on ReplicaSet and DaemonSet occasionally return version registration errors

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#53040] opened 2017-09-26 06:21 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
create  a ReplicaSet then change its image by kubectl set image command. It returns an error ocassionally like 
error: replicasets/gakki-replicaset no kind "ReplicaSet" is registered for version "apps/v1beta1"

**What you expected to happen**:
image changes without error
**How to reproduce it (as minimally and precisely as possible)**:
yaml file as follows:
```
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
```
execute command:
kubectl create -f test.yaml
kubectl set image rs test-replicaset php-redis=nginx:1.7.9 

**Anything else we need to know?**:
the error happens ocassionally, you can make  several tries to observe this error.  
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.51+14cedb9f581d6a-dirty", GitCommit:"14cedb9f581d6a6de367e780e31a8ca1c7b12112", GitTreeState:"dirty", BuildDate:"2017-09-23T08:08:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.281+ba1ab3fd559dd7-dirty", GitCommit:"ba1ab3fd559dd775863477f00a3e8d3bf86583a0", GitTreeState:"dirty", BuildDate:"2017-09-25T11:31:36Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment] 2017-09-26 08:24
> the error happens ocassionally, you can make several tries to observe this error.

@WanLinghao Would you please run `kubectl get nodes` to verify the kubelet version.

**Comment by WanLinghao** [comment] 2017-09-26 08:29
@dixudx 
NAME      STATUS    ROLES     AGE       VERSION
node2     Ready     <none>    21d       v1.9.0-alpha.0.721+1a44e26670c9ce
node3     Ready     <none>    21d       v1.9.0-alpha.0.721+1a44e26670c9ce

**Comment by WanLinghao** [comment] 2017-09-26 11:13
@dixudx  did you get same error?

**Comment by lichuqiang** [comment] 2017-09-26 11:55
@WanLinghao the bug seems has nothing todo with version. It could be easily reproduced with current code from master branch.

**Comment by WanLinghao** [comment] 2017-09-26 12:01
@lichuqiang  I mean the ReplicaSet register process in api-server, not the K8s version.

**Comment by WanLinghao** [comment] 2017-09-26 12:05
@janetkuo  maybe it is related to your patch #49238  please take a look. thanks

**Comment by dixudx** [comment] 2017-09-26 14:34
@WanLinghao I did reproduce this error. Please help re-verify whether #53056 fixed it. Thanks.

**Comment by janetkuo** [comment] 2017-09-26 18:16
I saw the same `kubectl set image` error for apps.DaemonSet. These resources were both just bumped to apps from extensions in 1.8.

**Comment by janetkuo** [comment] 2017-09-26 18:55
kubectl set image error comes from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/set/helper.go#L131

**Comment by mengqiy** [comment] 2017-09-26 19:55
> kubectl set image error comes from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/set/helper.go#L131

Then you will need to update func UpdatePodSpecForObject in your PR. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L236

**Comment by janetkuo** [comment] 2017-09-26 20:37
> Then you will need to update func UpdatePodSpecForObject in your PR.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L236

That function checks internal version of resources.  Internal version DaemonSet and ReplicaSet are both in extensions (not apps).

**Comment by janetkuo** [comment] 2017-09-26 20:51
Also the error is not from `UpdatePodSpecForObject`.

**Comment by janetkuo** [comment] 2017-09-26 21:07
The error comes from runtime.Encode:

https://github.com/kubernetes/kubernetes/blob/30f015a6fc13979193a6105890ce91ace651eb5c/pkg/kubectl/cmd/set/set_image.go#L227-L229

**Comment by janetkuo** [comment] 2017-09-26 21:14
@kubernetes/sig-cli-bugs

**Comment by janetkuo** [comment] 2017-09-26 23:32
This needs to be fixed in 1.8, but should not block the release. Will add this to the known issues list in release note.

**Comment by mengqiy** [comment] 2017-09-27 00:53
Thanks Janet for debugging this.

> the error happens ocassionally, you can make several tries to observe this error.

From https://github.com/kubernetes/kubernetes/blob/30f015a6fc13979193a6105890ce91ace651eb5c/pkg/kubectl/cmd/set/set_image.go#L227-L229, it is not clear to me why it is intermittent. It should always fails, shouldn't it?

**Comment by janetkuo** [comment] 2017-09-27 18:44
Actually all `set` commands that uses the similar code (`UpdatePodSpecForObject` and then `Encode`) are affected. That includes `set image`, `set env`, `set resources`, and `set serviceaccounts`.

**Comment by liggitt** [comment] 2017-09-27 18:47
I'm debugging now

**Comment by liggitt** [comment] 2017-09-27 19:24
the issue is here:
https://github.com/kubernetes/kubernetes/blob/e33dd983ed75d15245534c87ddaf843aa617638a/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L483-L498

when it fails, it looks like this:
```
in: *extensions.ReplicaSet

targets:
schema.GroupVersion{Group:"storage.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"storage.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"apps", Version:"v1beta1"}
schema.GroupVersion{Group:"apps", Version:"v1beta2"}
schema.GroupVersion{Group:"authorization.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"authorization.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"batch", Version:"v1"}
schema.GroupVersion{Group:"batch", Version:"v1beta1"}
schema.GroupVersion{Group:"batch", Version:"v2alpha1"}
schema.GroupVersion{Group:"networking.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"policy", Version:"v1beta1"}
schema.GroupVersion{Group:"admissionregistration.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"certificates.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"extensions", Version:"v1beta1"}
schema.GroupVersion{Group:"scheduling.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"settings.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"componentconfig", Version:"v1alpha1"}
schema.GroupVersion{Group:"autoscaling", Version:"v1"}
schema.GroupVersion{Group:"autoscaling", Version:"v2beta1"}
schema.GroupVersion{Group:"", Version:"v1"}
schema.GroupVersion{Group:"authentication.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"authentication.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"federation", Version:"v1beta1"}

kinds:
schema.GroupVersionKind{Group:"apps", Version:"__internal", Kind:"ReplicaSet"}
schema.GroupVersionKind{Group:"extensions", Version:"__internal", Kind:"ReplicaSet"}

gvk: schema.GroupVersionKind{Group:"apps", Version:"v1beta1", Kind:"ReplicaSet"}
```

when it works, it is called like this:
```
in:
*extensions.ReplicaSet

targets:

schema.GroupVersion{Group:"componentconfig", Version:"v1alpha1"}
schema.GroupVersion{Group:"authentication.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"authentication.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"extensions", Version:"v1beta1"}
schema.GroupVersion{Group:"settings.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"federation", Version:"v1beta1"}
schema.GroupVersion{Group:"policy", Version:"v1beta1"}
schema.GroupVersion{Group:"networking.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"storage.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"storage.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"authorization.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"authorization.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"autoscaling", Version:"v1"}
schema.GroupVersion{Group:"autoscaling", Version:"v2beta1"}
schema.GroupVersion{Group:"batch", Version:"v1"}
schema.GroupVersion{Group:"batch", Version:"v1beta1"}
schema.GroupVersion{Group:"batch", Version:"v2alpha1"}
schema.GroupVersion{Group:"certificates.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1beta1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1"}
schema.GroupVersion{Group:"rbac.authorization.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"", Version:"v1"}
schema.GroupVersion{Group:"admissionregistration.k8s.io", Version:"v1alpha1"}
schema.GroupVersion{Group:"apps", Version:"v1beta1"}
schema.GroupVersion{Group:"apps", Version:"v1beta2"}
schema.GroupVersion{Group:"scheduling.k8s.io", Version:"v1alpha1"}

kinds:
[]schema.GroupVersionKind{schema.GroupVersionKind{Group:"apps", Version:"__internal", Kind:"ReplicaSet"}, schema.GroupVersionKind{Group:"extensions", Version:"__internal", Kind:"ReplicaSet"}}

gvk: schema.GroupVersionKind{Group:"extensions", Version:"v1beta1", Kind:"ReplicaSet"}
```

**Comment by liggitt** [comment] 2017-09-27 19:26
schema.GroupVersions#KindForGroupVersionKinds lacks information about which group/versions actually contain the kind in question

**Comment by janetkuo** [comment] 2017-09-27 20:09
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment] 2017-09-27 20:13
I think the right thing to do here is change `UpdatePodSpecForObject` to work on versioned objects and v1.PodSpec, pass in info.VersionedObject, and encode info.VersionedObject directly

**Comment by liggitt** [comment] 2017-09-27 20:13
testing out a PR now

**Comment by liggitt** [comment] 2017-09-28 00:46
Fix in https://github.com/kubernetes/kubernetes/issues/53158

**Closed** 2017-09-29 21:36 UTC
Labels: kind/bug, milestone-labels-complete, non-release-blocker, priority/important-soon, sig/api-machinery, sig/cli
