### ISSUE TITLE
heapster polling stats for long-dead pods

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16168] opened 2015-10-23 18:01 UTC
EDITED: the thing getting the stats is heapster, not fluentd (duh).

heapster is asking kubelet for stats for long-dead pods, and getting 404.

On my kubelet, 64% of all kubelet log lines are 404s of stats requests by heapster.

Example log lines:
```
I1022 00:17:30.008559    3663 server.go:1060] GET /stats/e2e-tests-job-46it6/rand-local-1snay/719df9be-7850-11e5-ad9f-42010af00002/c: (7.085453ms) 404 [[Go 1.1 package http] 10.244.2.3:46783]
... 17 hours passes ....
I1023 00:17:00.011542   28808 server.go:1060] GET /stats/e2e-tests-job-46it6/rand-local-1snay/719df9be-7850-11e5-ad9f-42010af00002/c: (34.632µs) 404 [[Go 1.1 package http] 10.244.2.3:47205]
```

10.244.2.3 is the heapster pod:
```console
$ kubectl get pods --namespace kube-system heapster-v10-ygqcu -o yaml | grep podIP
  podIP: 10.244.2.3
```

**Comment by erictune** [comment] 2015-10-23 18:02
P1 to examine whether this is happening on other clusters.  If not, then P2.  If so, then P1 to cut logging lines of kubelet in half, and reduce stats load.

**Comment by erictune** [comment] 2015-10-23 18:32
The pods are still present on the apiserver, but in state Completed.

**Comment by yujuhong** [comment] 2015-10-23 18:38
Heapster should stop polling the stats of terminated pods --  their stats won't change and the containers have probably already been GC'd.  @vishh, I think we talked about this before but I couldn't find the issue.

**Comment by dchen1107** [comment] 2015-10-23 18:44
@erictune and I just double checked it. It is not fluentd, it is heapster.

**Comment by vishh** [comment] 2015-10-23 18:48
This is a known issue. How do we want to deal with this? Fix it in heapster
right away or supress logs in kubelet for now?

**Comment by dchen1107** [comment] 2015-10-23 18:49
Now back to @yujuhong's above comment. There is always a race window given today's metrics API, heapster might query /stats on terminated pods. @timstclair's current work on metrics API should remove / mitigate such issue. 

Lower the priority to P2.

**Comment by dchen1107** [comment] 2015-10-23 19:02
Talked to @vishh: we are going to fix this in Heapster and cut a new release. But for 1.1 release, we are going to leave it as is.

**Comment by erictune** [comment] 2015-10-23 19:18
SGTM.

**Comment by vishh** [comment] 2015-10-23 19:24
@dchen1107: I thought we agreed that fixing this in heapster is racy and the new metrics APIs once implemented in kubelet will mitigate this issue. Let me know if you still want me to update heapster?

**Comment by erictune** [comment] 2015-10-23 23:09
IMO, you should still update heapster.

It is fine if it occasionally queries a pod after it has terminated, but it should eventually notice that a pod is gone, such as by periodically relisting.

In the example I gave, Heapster was still querying pods 17 hours after they had terminated.

**Comment by vishh** [comment] 2015-10-23 23:39
Fair point. If the pods are not garbage collected from the API server
automatically, this will be an issue. Heapster fix underway!

**Comment by jimmidyson** [comment] 2015-10-25 12:21
I think this has been discussed in other issues, but heapster shouldn't poll kubelets for individual pod metrics but rather request all pod metrics from kubelets & correlate back to pod resources as necessary. This would create much less load on the kubelet as well as providing consistent timings for pod metrics. This is how we do the metric collection when using Prometheus discovery btw.

**Comment by vishh** [comment] 2015-10-25 18:11
FYI: The new [kubelet metrics APIs](15862) should help address this issue.

**Comment by vishh** [comment] 2015-11-02 19:37
Heapster HEAD has been updated to ignore pods that have exited. The next release of Heapster v0.19.0 should contain the patch. I'm closing this issue for now, since we have a separate issue that is tracking implementation of the new metrics APIs

**Closed by vishh** 2015-11-02 19:37 UTC
Labels: area/monitoring, priority/P1, team/node

**Comment by ibalashov** [comment] 2016-03-17 15:27
JFYI, The issue is still there in google container-engine. There is a lot of 404 errors in kubelet log. 

Also, `kubelet` takes process takes high cpu, even with no app-level containers is running, I assume partly because of this.
