### ISSUE TITLE
Inconsistent API Server Behavior with CRDs 

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/kubernetes#58636] opened 2018-01-22 21:43 UTC
/kind bug

**What happened**:
While integration testing my CRD controller, I started to notice inconsistent behavior with the API server. Here is what happened (note: k8s v1.8.0):
```sh
$ minikube delete
$ minikube start --feature-gates CustomResourceValidation=true --kubernetes-version v1.8.0
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
$ cat > crd.yaml << EOF
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apiproxies.kanali.io
spec:
  group: kanali.io
  version: v2
  scope: Namespaced
  names:
    kind: ApiProxy
    listKind: ApiProxyList
    plural: apiproxies
    singular: apiproxy
    shortNames:
    - ap
EOF
$ kubectl apply -f crd.yaml
customresourcedefinition "apiproxies.kanali.io" created
$ cat > test.yaml << EOF
apiVersion: kanali.io/v2
kind: ApiProxy
metadata:
  name: example-basic-endpoint-backend
  namespace: default
spec:
  source:
    path: /example-basic-endpoint-backend
  target:
    path: /
    backend:
      endpoint: "https://httpbin.org"
EOF
$ kubectl apply -f test.yaml
apiproxy "example-basic-endpoint-backend" created
$ kubectl apply -f test.yaml
apiproxy "example-basic-endpoint-backend" configured
$ kubectl apply -f test.yaml
The ApiProxy "example-basic-endpoint-backend" is invalid: apiVersion: Invalid value: "ApiProxy": must be kanali.io/v2
```

**What you expected to happen**:
I expect `test.yaml` to be able to be applied successfully an infinite amount of time.

**How to reproduce it (as minimally and precisely as possible)**:
Use the above steps and note the Kubernetes and kubectl versions.

**Comment by frankgreco** [comment] 2018-01-22 21:44
@kubernetes/sig-api-machinery-bugs
@nikhita

**Comment by nikhita** [comment] 2018-01-22 21:47
This is a dupe of https://github.com/kubernetes/kubernetes/issues/53379 and was fixed in https://github.com/kubernetes/kubernetes/pull/54780.

**Comment by frankgreco** [comment] 2018-01-22 21:53
@nikhita thanks. Was this back-ported to `v1.8`?

**Comment by nikhita** [comment] 2018-01-22 22:10
> Was this back-ported to v1.8?

Yes, this is present in v1.8.4.

**Closed** 2018-01-22 22:10 UTC
Labels: kind/bug, sig/api-machinery
