### ISSUE TITLE
There should be a local storage persistent volume

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#7562] opened 2015-04-30 15:31 UTC
There should be a persistent volume plugin that:
1.  lets a user make a claim on a node's local storage
2.  ensures the scheduler places the pod on a node with the available storage
3.  provides host-stickiness so that the pod is restarted on the same node

The use-case for this is for applications that require local storage for performance reasons.
Initially we may need to expand this to include the ability to specify performance characteristics
of the storage such as iops, io bandwidth, etc.

This is a use-case that @jmccormick2001 needs for a product he's working on.  Did I capture your
requirements correctly, Jeff?

cc @markturansky @thockin

**Comment by markturansky** [comment] 2015-04-30 16:07
See the original discussion: https://github.com/GoogleCloudPlatform/kubernetes/pull/1515

Resource counting to enforce scheduling constraints (e.g, only 16 "GCE slots" per node) is a necessary requirement.  Nodes can have uniquely named resource slots (e.g, "HostPath-1622"), where the name matches the unique PV name.  

Durability is only as good as the underlying infrastructure or existing backup processes.  Restoration of a crashed node would be a manual task.

**Comment by jmccormick2001** [comment] 2015-04-30 17:11
Thanks Paul, yes, you have captured the use case with this issue.  The product we are working on requires local storage for I/O performance reasons for any pods that it spins up.  If the scheduler could handle the placement that would seem to make this easy to use.

**Comment by smarterclayton** [comment] 2015-04-30 21:10
There was a slightly weaker version of this proposed, which avoids the need to reschedule.  Would that work for your use case?

1. Add a new VolumeSource variant of emptydir called "uniqueemptydir". That source would have a unique key, called "unique".  A pod creator would create a sufficiently random secret that multiple pods could share (or one would be defaulted onto it).
2. When a pod is scheduled to a host, the volume directory would be created at `/volumedir/<unique>/`, and any pod on that host would be able to mount that directory.  
3. When a pod was deleted from a host, if there were no other pods referencing that volume, it would remain for a duration specified in the volume source with a default "persistAfterDeletion"

This would create a reusable, single-host directory that could be reused by multiple pods scheduled in quick succession.  It would not survive node failure or restarts.

**Comment by smarterclayton** [comment] 2015-04-30 22:08
Actually, now that I think about it, the scheduler can key on the unique token (and whether any pod is scheduled with it) to have a recent memory of scheduling.  So you could get "good enough" in some cases.

**Comment by markturansky** [comment] 2015-04-30 22:52
@smarterclayton how is that unique token different from a uniquely named resource slot?  Counting resources can survive pod death and node reboot.

Something like the flocker demo shown last Friday could provide the replication if the cluster admin doesn't already have meaningful backups in place.

**Comment by smarterclayton** [comment] 2015-04-30 23:17
Counting resources is distinct (and not very interesting, because it's size that's more important than count) - this is about identifying resources that are shared in a coherent way.  EmptyDir is a zero guarantee resource - this would add an identity to the resource.

Backup is nice, but there are many use cases where pods might be colocated and benefit from reuse of a per host cache, or the ability to reserve and consume resources with some stickiness.  I want to find the weakest guarantee that satisfies a broad swathe of cases around "I want to hold some local disk with some chance to reuse that if I die".  I don't want to implement durable storage.

**Comment by kostko** [comment] 2015-05-22 06:12
We also need such a feature for a very similar case, so to avoid the need and overhead of remote storage solutions when the database itself (running in a pod) can do replication.

> There was a slightly weaker version of this proposed a while back, which avoids the need to reschedule on the same node. Would the following work for your use case?

For us, this would not be ok. If the node containing the volume did not fail, the pod should be rescheduled on the same node. Otherwise, your approach could cause needless data transfer (if the pod used database replication to resync) when the pod is just killed and the data is actually still there. And in case there is only one replica, this would cause unnecessary data loss just because a pod was killed and rescheduled to a different node which doesn't have the volume.

**Comment by jmccormick2001** [comment] 2015-05-22 12:45
For my use case, Postgresql + replication, I think the minimum requirement would be one that lets me specify "use local storage" and when the pod/container dies, the scheduler would know to attempt to place the pod/container back on the original node.  If the node dies or the storage gets corrupted, it would be my application's or operations team's responsibility to deal with that failure/recovery and data backup.  I'm going to insure that my app works with network storage and the kube persistence APIs but I can already see customer's requiring the performance of local storage in enterprise settings.  Ideally, the persistence API's would be such that it would support this 'local' volume option and I wouldn't have to do something special outside of the API for this use case.

**Comment by smarterclayton** [comment] 2015-05-27 23:05
Related to #598

**Comment by bgrant0607** [comment] 2015-05-29 06:24
Yes, this is a dupe of #598.

The main use case for this is local flash, IMO.

**Comment by thockin** [comment] 2015-05-29 06:51
I feel like there's a bit of disconnect here.  Phrases like "when the
pod/container dies, the scheduler would know to attempt to place the
pod/container back on the original node" suggest that a pod might suddenly
die on one node and turn up somewhere else - this just isn't the way it
works.  There's already a very strong preference to restart on the same
node (not reschedule, mind you - restart).


> We also need such a feature for a very similar case, so to avoid the need
and overhead of remote storage solutions when the database itself (running
in a pod) can do replication.

Surely there's a crossover point here?  At an extreme, if your database can
do replication, then why does this affinity matter at all?  Just kill the
pod and move it somewhere else and let your app's replication handle it.
Obviously the reality is that there is a cost to that.  So how long should
we wait before deciding a node really is dead and that your pod has to b
restarted elsewhere?  5 minutes?  an hour?  a month?  At some point you
have been running at reduced N for long enough that the risk incurred by
that outweighs the cost of doing a data rebuild on a new node.  Even more,
what if this happens to 2 of your 3 replicas - how do we know thatit
suddenly became more urgent?

This feels a lot like the "forgiveness" idea from internal work.  You are
willing to forgive some extended outage across some number of replicas.
It's a complicated concept to model.

**Comment by bgrant0607** [comment] 2015-05-30 00:01
Forgiveness is #1574. It's not too bad if modeled in the right way (hence that proposal).

There are cases, however, where someone may need to replace a pod. Right now, we permit very few in-place updates, and rolling update is also not in place. That simplifies many parts of the system.

I really like the model where the only pets in the system are storage, whether network-attached or local.

**Comment by smarterclayton** [comment] 2015-05-31 21:28
> On May 29, 2015, at 8:01 PM, Brian Grant <notifications@github.com> wrote:
> 
> Forgiveness is #1574. It's not too bad if modeled in the right way (hence that proposal).
> 
> There are cases, however, where someone may need to replace a pod. Right now, we permit very few in-place updates, and rolling update is also not in place. That simplifies many parts of the system.
> 
> I really like the model where the only pets in the system are storage, whether network-attached or local.
> 
The interesting part of that mindset is that shared storage is the only thing that needs a lock - therefore the proper way to manage locks on the unique nature of pods is to tie the pod to unique storage and block pod start on the acquisition of the storage lock.  Since storage (to be unique) has to manage locking, you isolate those locks in a single place.  If you can take locks via FS operations on your store, your volume plugin can provide the guarantee.

The simplest possible unshared persistent storage is a remote zip file, backed by a lock manager and updated by the volume plugin, where forgiveness defines how long you wait for the lock before breaking it from a node.

**Comment by jmccormick2001** [comment] 2015-06-01 19:46
sorry about the disconnect, if the pod is guaranteed to always start on the same original node, then all I would need for my use case is  access to local storage on that node and an ability to specify the ownership/perms.

**Comment by thockin** [comment] 2015-06-01 20:23
It's not "guaranteed" - if the node is dead (no reply for some number of
minutes) all pods are moved elsewhere - that's why I called it a "strong
preference".  This is not a per-pod configurable.

To do this correctly is tricky because there's a new lifetime to manage.

**Comment by kuboid** [comment] 2015-06-03 21:43
@thockin 

We have done some work on this front and intend to submit a proposal soon. A very high level description.

1) Scheduler is aware of storage capacity of each node
2) Durable volumes are created with a specific size requirement (among others)
3) Scheduler places a durable volume to a node which meets the requirements
4) When a pod requests that a durable volume be mounted, it is only scheduled to the node that has this durable volume.
5) If the node is out of cpu/mem resources or dead or the volume doesn't exist, the pod remains in pending state.
6) If the node dies afterwards, node controller deletes/recreates the pod. The pod goes to pending state now because the node is dead.

Will discuss the idea more in person.

**Comment by erictune** [comment] 2015-06-03 22:07
Proposals welcome!  What you have outlined sounds similar to the "New
Resource Kind" option from #1515.
You may want to read through that issue while working on your proposal.
However, some time has passed
since then, so a fresh perspective is certainly welcome.

**Comment by bgrant0607** [comment] 2015-06-05 03:06
@kuboid: One detail: the node controller should not recreate the pod. It can either remain (i.e., not deleted) or be replaced by a pod controller, such as replication controller. If it remains, its unavailability could be reflected by a condition, such as Ready=False. See #7856, #6363, #1574, #8335.

**Comment by thockin** [comment] 2015-07-09 06:01
Anyone reading this should also read #598

**Comment by pmorie** [comment] 2015-12-16 17:05
@kubernetes/rh-storage

**Comment by davidopp** [comment] 2016-01-31 23:32
@kubernetes/huawei

**Comment by cescoferraro** [comment] 2016-02-21 13:51
I am doing this by using nodeSelector on the rc and hostPath on the pv for my clustered databases. And it works well.

**Comment by wattsteve** [comment] 2016-02-21 16:20
Yes, but if you follow that pattern, you need a singleton RC (replica=1) that pins the pod onto a host, *per node instance* in your clustered database (or whatever you're clustering). So, as an example, to deploy a 3 node MongoDB ReplicaSet this way, for each Mongo Instance you would need a singleton RC with a NodeSelector pointing to unique Kube Host (leaving you with 3 RCs). That approach uses Kubernetes Volumes (HostPath Pet Storage via Volume Plugin) and not Kubernetes *Persistent* Volumes (storage obtained via claim) . This PR is about enabling the latter. Anecdotally, we really need  clearer terms to differentiate our Pet vs. Cattle Storage options than "Volumes" and "Persistent Volumes".

**Comment by davidopp** [comment] 2016-02-21 20:07
What @wattsteve said. Besides being cumbersome to set up and manage, the approach you described is not self-healing, i.e. it eventually requires manual intervention to avoid falling below a quorum.

**Comment by davidopp** [comment] 2016-02-22 06:58
> What @wattsteve said. Besides being cumbersome to set up and manage, the approach you described is not self-healing, i.e. it eventually requires manual intervention to avoid falling below a quorum.

Sorry, that came off a little more negative than I had intended. :) What you're doing is indeed the best you can do with what we have right now, and I'm glad you find it usable.

**Comment by chengyli** [comment] 2016-02-29 14:04
@davidopp 
Current hostpath PersistentVolume doesn't support multiple nodes, is there any plan to enhance the kube-scheduler to make sure that pods which request same PersistentVolumeClaim shall not be scheduled on the same node? e.g. similar function as isVolumeConflict() in predicates.
Then cluster admin can label the nodes which shall provides the local storage, and create the PersistentVolume resource. Users only need create the PersistentVolumeClaim when launching a pod, 
but needn't care the host node storage path.

**Comment by thockin** [comment] 2016-03-04 00:53
hostpath PV is for devel and debug.  Not for production.

I think we all agree some form of PV backed by local-media is useful, but I
think that's as far as we have gotten

**Comment by davidopp** [comment] 2016-03-04 01:17
In the past @bgrant0607 has said this is very related to PetSet, and I agree. We should consider doing both at the same time (though they can be parallelized, I think). @thockin WDYT?

**Comment by thockin** [comment] 2016-03-04 03:00
I think it is orthogonal to petset.  For environments without networked
storage, local PV is a solution where there wasn't a good one before.  For
environments with "special" storage, local PV is an enabler.  For petset,
local PV is no better than network storage, if it is available.

**Comment by wattsteve** [comment] 2016-03-04 03:34
@thockin can you clarify why you feel that hostPath is for devel and debug? Why is a mount of a local disk perceived as less reliable than a mount of a network disk? For the node instances of on-premise scale out platforms like Cassandra, Mongo, GlusterFS, HDFS, etc., local disk is preferred to network disk for performance reasons.

**Comment by thockin** [comment] 2016-03-04 04:03
hostPath PV (as opposed to plain hostPath) was added for development.  The
scheduler is 100% unaware of it, and so can NOT make any guarantees about
"persistence" of that data.

**Comment by markturansky** [comment] 2016-03-04 13:18
Right.  There is no way currently for the scheduler to  know on which node to place a pod with a claim to a hostPath PV.

But if you wanted to add NodeName to HostPath ...

**Comment by smarterclayton** [comment] 2016-03-04 14:48
You still haven't responded to my "emptyDir should be added to PV for
the same reason" issue.  HostPaths suck to work with and encourage bad
app/image design (assume ability to run as root, chown, and selinux
relabel)

**Comment by smarterclayton** [comment] 2016-03-04 14:53
We have users in production today using hostPath PV to point to NFS,
Gluster and (I think) AFS/GFS shares that are mounted on all nodes.
So hostPath is a production story as well.

The devel story should be emptyDir PV because it doesn't require root
in the container to be useful or to have a bunch of perm hacks.

**Comment by thockin** [comment] 2016-03-04 22:13
hostpath PV to point to NFS is weird - why bother with PV?

I am not sure what "emptydir as PV" means.  Do you mean simply "PV backed
by local disk without the user knowing teh full path" ?  If so, that's what
I was agreeing we should have.

**Comment by smarterclayton** [comment] 2016-03-05 03:04
Security and centralization (PVs can be secured, hostPath direct on pod
can't).  Also, support for filesystem drivers that don't exist in Kube yet
(AFS, GFS, etc).

Emptydir as PV for testing and development that doesn't survive a single
pod lifetime is still useful for testing PV and developing applications.
I'd like the more complex (survives pod removal) solution, but hostPath is
not useful for dev/test when you don't want to run as root inside (and thus
root outside).  Adding emptydir to the PV struct would be better for
testing.

**Comment by Maverick-Crank-GRey** [comment] 2016-03-05 16:25
I'm surprised to see that

> hostPath is not useful for dev/test when you don't want to run as root inside

I thought that it's quite common case when an application is run **and** developed at the same. It seems to me, all applications that use dynamic languages (Python, Ruby, JavaScript) are developed being run - you can see your changes without "rebuild & redeploy". Even in Java world, a hot swap and [JRebel technologies](https://zeroturnaround.com/software/jrebel/features/) help developers reload code changes instantly.

I means that the code should be accessible to a host (developer) machine **and** a container. It's like a "[sidecar container pattern](http://blog.kubernetes.io/2015/06/the-distributed-system-toolkit-patterns.html)" but without a sidecar =)

**Comment by smarterclayton** [comment] 2016-03-06 21:54
A host path owned by your local user *and* the container is running as the
same local user is fine.  A container running as root and accessing that
host path will work, as long as you're fine with running root containers.
I would assume it's unlikely your container is running as the local user,
and if you want to build and ship containers that expect to be running as
root, then yes, hostPaths will be fine.  I would call this path "local app
dev".

The dev/test I was referring to was more, "does my app deploy to the
cluster correctly", and "does it work correctly with persistent volumes".
In that case, hostPath is problematic, because unless you're root in the
container (and can chown and relabel the PV at all, which NFS and non-block
storage are unlikely to allow) you won't be able to verify that your
application works with different types.

From a security perspective, if you have a large cluster (with more than
1-2 admins involved) and you're running containers as root on every box AND
using hostPaths, it's much easier for an attacker to compromise all the
machines (and by extension, compromise the cluster masters).  If you're
developing your apps with the goal of having the same configuration in dev
as in prod, and you don't want root in prod, you want to make it easy to
test with PVs in a consistent way in local dev without using root, for
which hostPaths aren't great at (but in very specific cases works fine).

**Comment by Maverick-Crank-GRey** [comment] 2016-03-08 07:26
Got it.
Thank you for the detailed picture.

**Comment by chrislovecnm** [comment] 2016-04-14 17:02
So folks this is quite important to use cases like big data. Cassandra, elastic, and others. I am not familiar with cockroach ... But maybe that as well.

Those big processes love some fast disk, and sometimes jbod attachments of multiple fast disks on bare metal.

How are we proceeding?

**Comment by bprashanth** [comment] 2016-07-05 23:56
Can we start by introducing this as `storage-class=sticky-local-disk`? 
Something like: 
* A new predicate function that gets pvs for a pod and rejects all but the one host specified in `kubernetes.io/stickyness` annotation. 
* Modify the volume manager on the kubelet to set the annotation to `pod.Spec.NodeName` before mounting a hostpath volume. 
* Write a provisioner that hooks up all PVCs with the given storage class, to a hostpath PV of `/var/lib/kubelet/writeable-location/unique-id`, where "unique-id" maps to one of the identity components in PetSet (i.e pods/UUID won't work)

The pod will initially land according to normal scheduling policy, the kubelet will set the annotation, after that the pod sticks. Implementing this is pretty simple.

There are a couple of details that need to be worked out (storage/qos on the node, cleaning up hostPath,  multiple pods claiming the same hostpath), but users can get sticky hostPath if they know exactly what they want even without the provisioner.

Clayton's secet+uid idea is nice too, but I think this is the easiest to start with, and it will allow people to play with petset on metal.

**Comment by mikefedyk** [comment] 2016-07-06 00:08
What happens when the node disappears temporarily or forever?  Leaving the pod stuck in an unschedulable state seems like a bad idea.  If it moves over to another node, then it would have high data affinity, and a startup script could logic that if the data dir is empty, restore from latest backup or replication slave.  The stickiness or affinity should not leave the pod in an unschedulable state if the node disappears.

**Comment by davidopp** [comment] 2016-07-06 00:37
@bprashanth : That sounds reasonable, my only concern is whether we will end up throwing it all out when we implement "full" local persistent volumes, which should work for any kind of controller and should allow you to launch a new pod (unrelated to any earlier pod that created or used the persistent local volume) and have it use an existing local volume (use cases for this are "clean up" tasks and using persistent local volume to store intermediate data in a pipeline of tasks that each read and write the local volume in sequence).  

On the specifics of your proposal: I am not very familiar with PetSet, but just to make sure I understand, in your design if the pod is deleted for whatever reason, the controller will create the replacement with the same annotation, so it will go back to the same node? (I assume PetSet will ensure it remounts the same path)

BTW rather than a new predicate function, we can just integrate it into the existing node affinity function.

**Comment by bprashanth** [comment] 2016-07-06 02:37
> @bprashanth : That sounds reasonable, my only concern is whether we will end up throwing it all out when we implement "full" local persistent volumes, which should work for any kind of controller and should allow you to launch a new pod (unrelated to any earlier pod that created or used the persistent local volume) and have it use an existing local volume (use cases for this are "clean up" tasks and using persistent local volume to store intermediate data in a pipeline of tasks that each read and write the local volume in sequence).

Does the existing local volume the new pod uses have the same data? (sorry if I missed a proposal, can you point me at it?). I'm specifically targetting the database + local storage case for latency and cost in prod, and easy of prototyping in dev.

There's a way to give people local storage today with something like Gluster, but it involves more moving parts/failure modes. 

> On the specifics of your proposal: I am not very familiar with PetSet, but just to make sure I understand, in your design if the pod is deleted for whatever reason, the controller will create the replacement with the same annotation, so it will go back to the same node? (I assume PetSet will ensure it remounts the same path)

The binding annotation is on the volume not the pod. Any pod referencing it must get scheduled to that host. 

> What happens when the node disappears temporarily or forever? Leaving the pod stuck in an unschedulable state seems like a bad idea. 

Admin will have to intervene and do something about the volume. At the very least, pull the drive, copy data off of it, delete the pv, etc. One can setup an out of band automation process that does exactly this but usually *some* action is necessary to decom a stateful node.

> If it moves over to another node, then it would have high data affinity, and a startup script could logic that if the data dir is empty, restore from latest backup or replication slave. 

@mikefedyk I think these are 2 different use cases. Affinity will work when you can afford to rsync over the network, or don't have strict consistency guarantees. This is not always the case. If your db is several 100 GBs your entire cluster will take a hit during the rsync, and in some cases (i.e the dead node is responsible for a segment of the keyspace) rsyncing from a peer migth result in data loss. 

I think there's a version of this that gives us affinity, but there's also a use case for hard pinning.

**Comment by davidopp** [comment] 2016-07-06 05:36
> Does the existing local volume the new pod uses have the same data? (sorry if I missed a proposal, can you point me at it?). I'm specifically targetting the database + local storage case for latency and cost in prod, and easy of prototyping in dev.

There is no spec or design written down anywhere, I am just saying that I think the requirements for the long-term solution include being able to have a controller create a replacement pod, or another controller create any kind of pod, and have it bind to the persistent data that is already on the machine (presumably created by some now-gone pod), to support the use cases I mentioned.

Ideally there would be a path to there from whatever you do short-term, but of course it's not strictly necessary.

> The binding annotation is on the volume not the pod. Any pod referencing it must get scheduled to that host.

Ah, got it. So the predicate you described makes sense (well, assuming all of the volumes for the pod that specify stickyness annotation specify the same host).

**Comment by mikefedyk** [comment] 2016-07-06 09:52
I think data gravity can be thought of in MTTR terms.  In the postgres case with one or more replication slaves, if the node a postgres master instance is running on dies, another instance on a different node can take over as master (see recent talks by jberkus) automatically, but you also want a new slave to come up to replace the failed master.  In that case, the MTTR is very quick, and the trade off of losing some recent transactions has been allowed if there is a hardware failure.

Another case is postgres, no data loss acceptable and downtime is the trade-off until the node is repaired.

Another one is the single postgres case with WaL shipping.  MTTR is 3 hours.  In that case another pod can be spun up, restore and WaL replay started, and if the original node comes back up, the building pod can be removed.

It may be that a boolean is enough: reschedule on volume missing=true

**Comment by bprashanth** [comment] 2016-07-06 17:16
> There is no spec or design written down anywhere, I am just saying that I think the requirements for the long-term solution include being able to have a controller create a replacement pod, or another controller create any kind of pod, and have it bind to the persistent data that is already on the machine (presumably created by some now-gone pod), to support the use cases I mentioned.

I think I'm talking about implementing exactly this, without a new type of volume (for now). 
If the pod/user knows what they're doing, they ask for a specific host-path like
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: v-0
  annotations:
    # this serves as a request to stick to the first host
    # the hostPath is allocated on.
    volume.alpha.kubernetes.io/sticky-host: ""
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default_foo-0
```
Which translates to: 
* Setting sticky-host is like setting spec.NodeName on all referencing pods.
* Any number of RCs can reference this pv, as long as sticky-host is set. 
* If stick-host is unset, it gets set to the host the first scheduled pod referencing it lands on. 
* Creating an RC referencing such a claim with stick-host unset is user/validation error (or we can have the scheduler write the stick-host field)
* PetSet should just work, because there's a 1:1 mapping of pod:volume

One issue with such design is that coming up with a unique, writeable hostPath might be hard in some environments. This is the `uniqueemptydir` support case. Ideally the system would pick some spot on the filesystem that matches the storage and read/write requirements specified in the PV/PVC. For "emptydir" today, the kubelet picks `/var/lib/kubelet/pods/UID` as an effective "hostPath". 

Obviously embedding UID in the path won't work for sticky pods, so either the kubelet needs to be aware of more than just pods (ie: /var/lib/kubelet/uid-of-RC/pods) or some higher level system like a volume controller needs to hand out these host paths. So I'm proposing that we have a PVC which looks like:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-0
  annotations:
    volume.alpha.kubernetes.io/storage-class: host-local
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Mi
```

that would provision PVs like the one above, BUT with a known writeable unique hostPath (probably still needs chowning by kubelet).

**Comment by pmorie** [comment] 2016-07-06 21:56
I would prefer not to base anything upon the `storage-class` annotation as it will probably go away once the storage classes proposal is adopted.

**Comment by bprashanth** [comment] 2016-07-06 22:13
yeah it's a means to an end. The point is that we can solve the "uniqueemptydir" issue by just writing a simple storage provisioner that populates hostPath with a known unique usable location, and solve the stickyness problem out of band for just hostPath volumes. 

There are a lot of ideas in this bug and I'd like to iterate on new types, formalize emptydir semantics, uid in secrets etc if possible (unless everyone already agrees on these). My main motivation being that it would be nice to have examples of databases using host local storage for 1.4.

**Comment by smarterclayton** [comment] 2016-07-07 00:55
I agree - I want the Dev/test flow, simple local storage, and the
longer term direction scoped out soon.  No one should have to depend
on a storage feature outside of Kube to develop, test, or roll out a
PetSet.  I'd probably be ok if we had "best-effort" (Dev/test only)
for 1.4

**Comment by davidopp** [comment] 2016-07-07 05:35
Thanks for the explanation. I like it. Only question is that these seem contradictory (so there's some detail I'm not understanding):

> If stick-host is unset, it gets set to the host the first scheduled pod referencing it lands on.
>
> Creating an RC referencing such a claim with stick-host unset is user/validation error (or we can have the scheduler write the stick-host field)

Isn't "Creating an RC referencing such a claim with stick-host unset" the way the first thing happens? ("If stick-host is unset...")

**Comment by bprashanth** [comment] 2016-07-07 16:47
> Isn't "Creating an RC referencing such a claim with stick-host unset" the way the first thing happens? ("If stick-host is unset...")

In the RC with N replicas case we can do this 1 of 2 ways:
1. Force the user to always pick the host and write it to the annotation. Just like today you can't create an RC with replicas > 1 and a read/write gce PD, you can't create an RC with replicas > 1 and an unset "stick-host" annotation because the 2 pods might get scheduled simultaneously (ignoring that we can't validate cross object right now). 
2. Write the stick-host annotation in the scheduler instead of in the kubelet. Then the second replica will follow the first one automatically.

2 is preferable but slightly harder to achieve because the scheduler today doesn't really write to anything directly, it just creates bindings.

**Comment by davidopp** [comment] 2016-07-07 21:28
Ah, thanks for the explanation.

Requiring the user to pick the host (option 1) seems bad.

Would a third option be to still have the kubelet write the stick-host annotation, but have kubelet admission control reject the second (and all subsequent) pods? That should cause the RC and scheduler to try again if the scenario you described for 1 happens.

**Comment by smarterclayton** [comment] 2016-07-07 22:58
Shouldn't the Kubelet *already* prevent concurrent pods from accessing a
RWO persistent volume by blocking the second pod from starting?

That sounds like a bug we already have to fix.

The scheduler already has to be aware of pvcs for label spreading... It
doesn't seem completely crazy that it can write back correlative info to
the PVC once scheduled.

On Jul 7, 2016, at 5:29 PM, David Oppenheimer <notifications@github.com>
wrote:

Ah, thanks for the explanation.

Requiring the user to pick the host (option 1) seems bad.

Would a third option be to still have the kubelet write the stick-host
annotation, but have kubelet admission control reject the second (and all
subsequent) pods? That should cause the RC and scheduler to try again if
the scenario you described for 1 happens.

**Comment by bprashanth** [comment] 2016-07-08 01:09
In the RC case we want read-write many I guess, each replica can create a unique subdir in the volume. 

I think I'm going to prototype a bit:    
1. Extend hostPath and emptyDir to pvs and use the sticky-host annotation as discussed
2. Write sticky-host from the scheduler ("how" remains TDB)
3. Reject any volume from the kubelet with sticky-host != self.nodeName
4. Figure out recycle policy for emptydir (kubelet needs to watch pvcs I guess?)

If 4 turns into a rathole, I'll probably punt on the sticky emptyDir PV for now and go with a dynamic provisioner that writes hostPaths to an "emptydir like" location.

**Comment by thockin** [comment] 2016-07-08 04:25
Prashanth and I spoke a bit, here's my recollection.

I think the *right* answer is to extend both emptyDir and hostPath to have
special meaning in PersistentVolumes context.

A PV emptyDir means "I want a local volume that has the same lifetime as
the PV".  The actual path to the volume doesn't matter, and is not knowable
a priori, though is maybe discoverable via PV.status.  I expect this is
what most people want. This would be cleaned up when the PV is deleted, and
would be subject to recycle policy.

A PV hostPath means "I want a SPECIFIC directory from the host".  There is
no automatic cleanup.  Data written this way is managed by the user.

**Comment by davidopp** [comment] 2016-07-08 04:40
> Write sticky-host from the scheduler ("how" remains TDB)

I still don't understand why this is necessary as opposed to having the Kubelet do it. We can make Kubelet admission control reject a second (and third, and fourth, ...) pod, which would address the "2 pods might get scheduled simultaneously" problem you mentioned in https://github.com/kubernetes/kubernetes/issues/7562#issuecomment-231137955.

It would be great to keep this writing of the annotation out of the scheduler if it's possible.

**Comment by bprashanth** [comment] 2016-07-08 04:48
I was trying to do both. Kubelet rejection has till now been a last resort type thing, because it incurs an additional round trip pod create/delete. By writing to the annotation in the scheduler we're effectively binding a volume to a node, and the scheduler has a global view (in theory) of the available disk on all nodes, so it didn't feel too wrong. I can start with the round trip solution.

**Comment by smarterclayton** [comment] 2016-07-08 13:58
Both of those sound good.  Although we have a lot of people using PV
with hostPath today in fairy sophisticated ways (on top of shared host
mounted dirs with unique uids, for example) so I want to make sure any
change to PV hostPath takes those into account.

**Comment by smarterclayton** [comment] 2016-07-08 22:31
If a node is drained or evacuated, do we need a separate mechanism to
flag the PVs as "unbound / impossible to retrieve"?

**Comment by bprashanth** [comment] 2016-07-08 22:45
Yeah if the node is deleted we should probably set the pv to that state. If the node is just unschedulable, the pod using that volume will remain in pending till the node becomes schedulable. The user needs to copy data off the volume into another node, and set the annotation on the pv to the new node name if they really want to move a pod referencing it.

**Comment by harobed** [comment] 2016-11-02 19:42
@chrislovecnm I see your comment https://github.com/kubernetes/kubernetes/issues/7562#issuecomment-210049829 … What's your hack to work around issue #7562 … until it's closed?

**Comment by chrislovecnm** [comment] 2016-11-06 00:07
@harobed I really do not have a hack to get around this.  If you need local storage, it will be ephemeral.  You can take the performance hit and use ESB or Google storage.  In AWS you are able to set IOPS, but I don't know if GCE allows for ssd attached storage yet.  In GCE all storage is remote anyways...

**Comment by a-robinson** [comment] 2016-11-06 01:38
@chrislovecnm, not that it really changes this issue much, but just to clarify:

* GCE does have SSD attached storage (SSD persistent disks, in their parlance)
* GCE does have a local SSD storage option (so not all storage is remote)

**Comment by chrislovecnm** [comment] 2016-11-06 21:40
@a-Robinson what has been communicated to me by Google is that even local ssd is not local ;) may have changed. Regardless, storage that can migrate between nodes would be extremely helpful.

**Comment by davidopp** [comment] 2016-11-06 22:15
https://cloud.google.com/compute/docs/disks/local-ssd

**Comment by F21** [comment] 2016-11-07 23:12
Local volumes recently landed in nomad. Maybe their implementation can be used as a reference:
https://www.nomadproject.io/docs/job-specification/ephemeral_disk.html
https://github.com/hashicorp/nomad/pull/1741

**Comment by chrislovecnm** [comment] 2016-11-13 03:58
@viglesiasce can you explain how https://cloud.google.com/compute/docs/disks/local-ssd actually work?  I am confused

**Comment by joshk0** [comment] 2016-11-20 14:42
[GKE Local SSD Doc](https://cloud.google.com/container-engine/docs/local-ssd) -- Short version, when you provision a local SSD on a GKE node, you magically get a /mnt/disks/ssd0 formatted ext4 volume. The Kubernetes Node gets the annotation `cloud.google.com/gke-local-ssd=true`. Whether it is actually present on the machine or not is not something I am privy to, but I assume it is and it is very fast. The Google team recommends the use of a `hostPath` to gain access to the SSD from Pods. This 

Historically, the SSD is not preformatted. What ended up working best for us was to hack the GKE OS template to mount the local SSD under /var/lib/kubelet. Then, I can just use an emptyDir volume to provision some SSD storage without having to specify this implementation specific hostPath in my pod spec.

In 1.3 and prior this caused no trouble. But in 1.4 it is now causing trouble with subsequent mounts that occur underneath /var/lib/kubelet. So now, I am thinking of undoing this hack and going for the hostPath volume on /mnt/disks/ssd0 instead. It's definitely less seamless than being able to use an emptyDir volume, because now I have to worry about name uniqueness on the local volume.

There are a lot of expensive looking features being proposed here. A lighter weight feature that would satisfy our use case is to have a construct to point emptyDir requests outside /var/lib/kubelet to a place like /mnt/disks/ssd0. Because of the pre-existing guarantees of emptyDirs (aka none), you don't really have to worry about node stickiness.

BTW, all our workloads that use local SSDs in this manner are able to move around and reconstruct themselves and don't particularly care that their local-SSD assets disappear once in a while if they get rescheduled.

Anyway, watching this ticket with interest. I think I will probably still go with the hostPath for now. It would be nice if the Kubernetes team could provide an official recommendation here, especially if it is not the same as the recommendation that the GKE team make in their docs.

**Comment by smarterclayton** [comment] 2016-11-20 18:35
I'm somewhat hesitant to name emptyDir more flexible (we have to deal
with security implications) but I do think your use case combines two
parts:

1. Gain access to faster storage - this is a "resource request" and
would need to be modeled this way (you request something special)
2. Have some persistence of data outside of pod lifetime.

The latter was proposed a while back - an emptyDir with a user
provided token that was GC'd by the kubelet but survived pod tear
down.  Anyone who knows the token can use it to get that storage on
the node.  If you use predictable tokens you can reuse disk.  If you
use high entropy tokens you get security (shared secret).

I don't know that I consider that approach much easier than the
current proposals though, because there are other important problems
we have to solve (storage attachment to machines) and the current
proposals take that into account.  But you could absolutely implement
that with a flex volume today.

**Comment by joshk0** [comment] 2016-11-20 20:14
One thing that is important that I forgot about in my previous post is that the hostPath workaround has an important caveat. If the Pod should be deleted, its storage is not automatically reclaimed by the Node. The responsibility would be on the Pod to clean up after itself (unlikely in bad scenarios) or having some externalized process on the Node or a kubelet pod which reaps old temp files.

In my current scenario, using an emptyDir volume manages all of this lifecycle competently already, and I would be losing that by moving to hostPath.

**Comment by F21** [comment] 2016-12-18 08:11
Will this happen in the near future (1.6, 1.7)? It would be really useful for running kube on baremetal or any standard VPS provider that does not offer HA pooled storage.

**Comment by kskalski** [comment] 2017-01-22 11:57
I'm wondering if there is a way to use nodeSelector in StatefulSet such that I can pin each replica to a specific node by a templatized label, similarly to how volumeClaimTemplates create a schema for accessing specific PVCs by name-index pattern.
Imagine
```
kind: StatefulSet
spec:
  template:
    spec:
      containers:
        - name: xyz
      nodeSelector:
        node: storage
```

which upon expansion would create pod xyz-0, xyz-1, ... with respective node selectors node: storage-0, node: storage-1, ...

**Comment by InAnimaTe** [comment] 2017-02-21 19:56
Agree with the above comments. People running on bare-metal clusters are a bit left out. This means any chart or other templates that almost always invoke a PVC completely fail to start.

I like the idea of utilizing a nodeSelector for defining the node's which I'm fine with storage existing on. This might be a single node or a few NFS/Gluster/etc.. enabled nodes in the cluster. This is similar to what I'm doing now (bind-mounts with nodeSelectors to pin to a single host)

**Comment by wattsteve** [comment] 2017-02-21 20:27
Folks, the SIGs are starting to rally around a new proposal for tackling
these problems. Please see proposal
https://github.com/kubernetes/community/pull/306 for issue
https://github.com/kubernetes/features/issues/121

**Comment by resouer** [comment] 2017-05-09 19:09
xref: https://github.com/kubernetes/kubernetes/issues/43640 by @msau42

**Comment by resouer** [comment] 2017-05-09 19:09
And kubernetes/community#306

**Closed** 2017-07-06 17:25 UTC
Labels: area/api, priority/backlog, sig/storage, team/huawei
