### ISSUE TITLE
e2e unit tests failing due to 60 minute timeout?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#19924] opened 2016-01-21 16:03 UTC
It appears that the unit tests in e2e are sometimes failing due to a 60 minute timeout, but it does not appear to be being correctly applied.

Logs here:
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/0586d866de1b0ca888ad3de53ad41cdb2077dd0e/kubernetes-pull-test-unit-integration/10243/

The weird thing is that the logs show that the unit tests themselves only took the normal amount of time - ten minutes or so (14:38 - 14:50 in the logs).  But I'm guessing there is an invisible delay before the first timestamp or after the last timestamp (or the 60 minute limit is not being correctly applied).

The wall clock time in between my request to retest and the failure result being posted was a little more than an hour (I think), so I think there is a silent delay somewhere.

**Comment by lavalamp** [comment] 2016-01-25 17:42
@ixdy?

**Comment by ihmccreery** [comment] 2016-01-25 17:50
Closing at duplicate of #18980, feel free to reopen if that's wrong.

**Closed by ihmccreery** 2016-01-25 17:50 UTC
Labels: kind/flake, priority/P0, team/test-infra
