### ISSUE TITLE
Investigate the soak test failures

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#27374] opened 2016-06-14 17:18 UTC
For last many runs, soak tests were red since the first build. We need to understand the soak test failures for 1.3 release. Yesterday, we just pushed a new soak-deploy package, and it looks better than previous many runs. Filed this issue for further tracking and investigation.

**Comment by Random-Liu** [comment] 2016-06-14 18:16
Quite a few soaking test were failing. One of the most significant reason is unready `monitoring-influxdb-grafana`:
```
monitoring-influxdb-grafana-v3-o4kwf  jenkins-e2e-minion-group-ajgi  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-06-07 03:19:01 -0700 PDT}  } {Ready False {0001-01-01 00:00:00 +0000 UTC} {2016-06-13 10:36:31 -0700 PDT} ContainersNotReady containers with unready status: [influxdb]} {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-06-07 03:19:01 -0700 PDT}  }]
```

**Comment by krousey** [comment] 2016-06-15 17:14
I looked into the reason why the GCE soak tests were timing out last week, and GCE masters are at 100% utilization on an n1-standard-1, even with no tests running. This could make the master slow enough to hit timeouts. I bumped up my GCE master to a n1-standard-2, and it idles at around 67%.

The GKE soak tests weren't timing out, but had individual failures. The GKE soak test master is at approximately 70% utilization.

Any idea what could be causing such a huge difference?

**Comment by dchen1107** [comment] 2016-06-15 18:44
@krousey thanks for the updates. That is what I observed from last week's failures. Also finally our master node which is running GCI image is having docker 1.11.2 this week, which helps with CPU utilization on the master nodes too.

**Comment by krousey** [comment] 2016-06-15 18:49
@dchen1107 The GCE masters are running 1.11.2 and are 100% utilized. The GKE masters are running 1.9 and are ~70% utilized. The new docker versions don't seem to be helping that much.

Is a master kubelet running in standalone mode doing a lot less than one that is registered with the API server? If this is expected utilization, perhaps we should bump the GCE masters to n1-standard-2 across all e2e suites (this utilization isn't unique to soak tests).

**Comment by dchen1107** [comment] 2016-06-17 18:02
@krousey I have a couple of questions: 

1) When you say master node's cpu utilization, I guess you are referring to the the entire node's cpu utilization, not measure individual containers and system daemons (docker and kubelet), right? 

2) When you say GKE master with 1.9, I guess you are referring to k8s 1.2 / 1.1 release. Right? If it is true, The extra cpu usage might be introduced by master components themselves. Someone should measure master components' resource usage. I filed an issue for that for 1.2 release.

**Comment by krousey** [comment] 2016-06-17 18:18
@dchen1107 

1) Yes, the overall node.

2) No. This is a GKE master with docker 1.9 and Kubernetes 1.3 build. The GKE and GCE masters were using different GCI base images. I created a GCE master with the same GCI image that the GKE master was using, and still noticed the over utilization. So the docker version probably doesn't matter.

**Comment by yujuhong** [comment] 2016-06-20 21:27
Not sure what the difference between gce and gke master is, but FYI, quite a significant chunk cpu usage comes from the addon-manager pod, which create multiple python processes periodically for version checkup (#26770).
``` 
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                                      
 2095 root      20   0 2368072 1.957g  14904 S  3.8 54.2 411:54.17 /usr/local/bin/kube-apiserver --v=2 --runtime-config=extensions/v1beta1 --delete-collection-workers=1 --cloud-config=/etc/gce.conf --address=127.0.0.1 --allow-privileged=t+ 
15979 root      20   0   55464  12600   5844 R  2.9  0.3   0:00.03 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
15984 root      20   0   55464  12552   5796 R  2.9  0.3   0:00.03 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
15986 root      20   0   55464  12440   5680 R  2.9  0.3   0:00.03 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
15988 root      20   0   55464  12384   5624 R  2.9  0.3   0:00.03 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
15991 root      20   0   53316  12220   5572 R  1.9  0.3   0:00.02 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
15994 root      20   0   53616  12372   5728 R  1.9  0.3   0:00.02 python -c  try:         import pipes,sys,yaml         y = yaml.load(sys.stdin)         labels = y["metadata"]["labels"]         if ("kubernetes.io/cluster-service", "true"+ 
```

**Comment by krousey** [comment] 2016-06-21 16:03
@yujuhong This also runs on the GKE master.

**Comment by quinton-hoole** [comment] 2016-06-23 17:09
I strongly suggest that we make resolving all soak test flakes a v1.4 release blocker.  We really do need to be able to hammer on a cluster for at least a week without it failing.  Tentatively marking this issue as such.  Let me know if anyone believes otherwise.

**Comment by krousey** [comment] 2016-06-24 23:13
@lavalamp Now that both GCE and GKE soak tests are green again, can you point me to how I can add them to the submit queue dashboard and get issues automatically filed for their failures?

**Comment by lavalamp** [comment] 2016-06-25 00:08
Make a PR to the contrib repo, mungegithub/mungers/submit-queue.go. Add to
the default arguments for the non blocking jobs flag.

**Comment by krousey** [comment] 2016-07-08 15:46
I'm going to close this tracking issue as I think we're in much better shape now.

- The suites no longer time out
- Many failures have been eliminated
- The remaining two major culprits have been identified and are being tracked in #27630 and #28124. And they're both 3rd party components.
- The submit queue now monitors and automatically files issues for these suites so regressions won't go unnoticed.

**Closed by krousey** 2016-07-08 15:46 UTC
Labels: area/test, kind/flake, priority/P0
