### ISSUE TITLE
kube-apiserver cannot reach heapster via ClusterIP

### ISSUE THREAD

**Issue by onitake** [kubernetes/kubernetes#56226] opened 2017-11-22 16:18 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
When trying to access one of the `top` resources, I get the following error:
```
$ kubectl top node worker-01
Error from server (InternalError): an error on the server ("Error: 'dial tcp 10.xx.xx.xx:8082: getsockopt: network is unreachable'\nTrying to reach: 'http://10.xx.xx.xx:8082/apis/metrics/v1alpha1/nodes/worker-01?labelSelector='") has prevented the request from succeeding (get services http:heapster:)
```
A similar error is returned when trying to access any service via `kubectl proxy`.

**What you expected to happen**:
A node's or pod's metrics are displayed.

**How to reproduce it (as minimally and precisely as possible)**:
- Run kube-apiserver on a control node without cluster networking
- Run weave on worker nodes: https://github.com/weaveworks/weave/releases/download/v2.1.1/weave-daemonset-k8s-1.7.yaml
- Run heapster: https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone/heapster-controller.yaml
- Execute `kubectl top node <any node>`

**Anything else we need to know?**:
The service cannot be reached because kube-apiserver is running on a node that isn't part of the cluster network.

This hasn't been an issue so far, as the apiserver usually does not need to connect to ClusterIPs. NodePorts and Ingresses have been sufficient so far. But this is no longer the case for top, metrics and autoscaling. For these features, the apiserver needs to talk to heapster, which is running in the cluster.

It seems most documentation related to heapster assumes that apiserver can talk to ClusterIPs, but this isn't necessarily the case.
I haven't found a good way to set this up in my kubernetes environment, except for running kubelet and container networking on the control nodes. This is not something I want to dismiss completely, but I'm looking for a simpler solution in the short term, if possible. Documentation also seems a bit scarce.

Please extend the heapster-based features in kubernetes so that they can access heapster via some other means than ClusterIP. NodePorts, for example, or an Ingress.

Otherwise, I'd be interested in documentation pointers on how to add cluster networking to a control node that is not running a container environment. Or, is it possible to run heapster directly on control nodes instead?

**Environment**:
- Kubernetes version (use `kubectl version`): Client 1.7.8 Server 1.8.3
- Cloud provider or hardware configuration: CloudStack/VMware
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-514.2.2.el7.x86_64
- Install tools: Ansible with custom playbooks
- Others: Setup based mostly on https://github.com/kelseyhightower/kubernetes-the-hard-way/ with some customisation.

**Comment by onitake** [comment] 2017-11-22 16:29
Would this work if the service is deployed as a cluster addon?

**Comment by onitake** [comment] 2017-11-22 23:53
@kubernetes/sig-network-feature-requests

**Comment by cmluciano** [comment] 2017-12-06 20:53
@kubernetes/sig-instrumentation-feature-requests

**Comment by DirectXMan12** [comment] 2017-12-09 17:01
For aggregated APIs, it's sufficient to have pod IP connectivity.  If you have neither pod nor service IP connectivity, you're going to have issues with any aggregated API.

Duplicate of #55238

**Comment by thockin** [comment] 2018-01-06 01:10
In general you can not assume the master has access to anything in the cluster, nor that it runs kube-proxy.

**Closed by thockin** 2018-01-06 01:10 UTC
Labels: kind/feature, sig/instrumentation, sig/network

**Comment by piosz** [comment] 2018-01-25 01:56
@thockin even through apiserver (kube?) aggregator?

**Comment by RickNEP** [comment] 2018-04-17 14:37
Any update on this? I'm having the same issue...
