### ISSUE TITLE
Failure cluster [1c7ddcfa...] 🐛 `[sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls [Conformance]`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#125711] opened 2024-06-25 23:52 UTC
### Failure cluster [1c7ddcfa885cdf9e931b](https://go.k8s.io/triage#1c7ddcfa885cdf9e931b)

<img width="1463" alt="image" src="https://github.com/kubernetes/kubernetes/assets/23304/56b030e0-b5b8-4c3d-80e6-0472d2541eaa">

##### Error text:
```
[FAILED] Expected
    <int>: 401
to be ==
    <int>: 400
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/chunking.go:109 @ 06/25/24 14:49:38.106

```
#### Recent failures:
[6/25/2024, 3:57:35 PM ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-30-on-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-30-on-latest/1805691555281899520)
[6/25/2024, 3:56:16 PM ci-kubernetes-kind-conformance-parallel-ipv6](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1805691305011974144)
[6/25/2024, 3:37:20 PM ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1805686522733662208)
[6/25/2024, 3:15:34 PM ci-kubernetes-e2e-kubeadm-kinder-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1805680986927665152)
[6/25/2024, 3:03:41 PM ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-28-on-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-28-on-latest/1805677966785515520)

/kind failing-test

/sig api-machinery

**Comment by liggitt** [comment] 2024-06-26 00:19
Duplicate of https://github.com/kubernetes/kubernetes/issues/125700, I think

**Closed** 2024-06-26 00:23 UTC
Labels: sig/api-machinery, kind/failing-test, needs-triage
