### ISSUE TITLE
Expose metrics from kube-proxy

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#18519] opened 2015-12-10 18:40 UTC
It would be great if we could throw off some sort of metrics from the proxy per-node.  Right now this is just an interface to drive iptables so we might be limited to what iptables exposes.

**Comment by thockin** [comment] 2015-12-11 05:10
I'll happily take patches here.  I'm buried and will not get to it any time
soon.

**Comment by errordeveloper** [comment] 2016-03-23 13:14
cc @squaremo @dpw

**Comment by smarterclayton** [comment] 2016-04-07 16:47
Dupe of #9125

**Closed by smarterclayton** 2016-04-07 16:47 UTC
Labels: component/kube-proxy, kind/feature, team/cluster
