### ISSUE TITLE
TODO: Convert validation code to be version-specific

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9998] opened 2015-06-18 00:53 UTC
After v1 is cut and v1beta3 dies.

**Comment by feihujiang** [comment] 2015-06-18 07:19
I would like to do some work on this

**Comment by thockin** [comment] 2015-06-18 19:41
This should be a relatively mechanical change

**Comment by smarterclayton** [comment] 2017-06-01 17:38
Dupe of #8550

**Closed by smarterclayton** 2017-06-01 17:38 UTC
Labels: priority/important-soon, sig/api-machinery
