### ISSUE TITLE
GCE e2e leaks PD

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16194] opened 2015-10-23 21:43 UTC
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel-flaky/7676/

```console
13:38:48 + [[ true == \t\r\u\e ]]
13:38:48 + ./cluster/gce/list-resources.sh
13:39:02 + [[ -f /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-before.txt ]]
13:39:02 + [[ -f /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-after.txt ]]
13:39:02 + diff -sw -U0 '-F^\[.*\]$' /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-before.txt /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-after.txt
13:39:02 --- /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-before.txt	2015-10-23 13:16:26.248820673 -0700
13:39:02 +++ /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-after.txt	2015-10-23 13:39:02.873874039 -0700
13:39:02 @@ -378,0 +379 @@ [ disks ]
13:39:02 +parallel-flaky-91e130dc-79c3-11e5-96b8-42010af01555 us-central1-f 10      pd-standard READY
13:39:02 + [[ true == \t\r\u\e ]]
13:39:02 + echo '!!! FAIL: Google Cloud Platform resources leaked while running tests!'
13:39:02 
```

**Comment by a-robinson** [comment] 2015-10-30 22:31
Closing as a dupe of #16308

**Closed by a-robinson** 2015-10-30 22:31 UTC
Labels: priority/P2, team/cluster
