### ISSUE TITLE
Add a severity concept in kubernetes events

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#15624] opened 2015-10-14 13:47 UTC
Hello,

As a new production operator of a GKE cluster, I feel a bit frustrated not to be able to distinguish "regular" / "normal" event from "not normal" events.

If we had a severity for events, it would be much easier for operators to know when the cluster is doing regular tasks or if something wrong is happening.

Maybe related to https://github.com/kubernetes/heapster/issues/477 ?

Any thought on that ?

**Comment by gmarek** [comment] 2015-10-14 14:43
@brendandburns @thockin @bgrant0607 @davidopp

**Comment by bgrant0607** [comment] 2015-10-14 14:49
cc @vishh @saad-ali @dchen1107

**Comment by vishh** [comment] 2015-10-14 17:20
+1 for this idea.

**Comment by derekwaynecarr** [comment] 2015-10-14 17:37
I agree.  Today, I have to ask "do you see any interesting output in kubectl get events" when I should be able to ask "do you have any output with severity X".  Big +1

**Comment by derekwaynecarr** [comment] 2015-10-14 17:38
@smarterclayton  @kubernetes/rh-cluster-infra @kubernetes/rh-dev-experience 

I think it would be a huge win if we got severity on events.

**Comment by ncdc** [comment] 2015-10-14 17:41
:+1:

**Comment by aveshagarwal** [comment] 2015-10-15 16:57
If nobody is working on it, I would be happy to work on it and here are some preliminary thoughts regarding changes required:

- [ ] Add  a new field Severity to type Event struct in  pkg/api/types.go,  pkg/api/v1/types.go:  

//Severity of this event (low, medium, high) (or may be Fatal too?)
Severity string `json:"severity,omitempty"`
- [ ] Modify event conversion API in ./pkg/api/v1/conversion_generated.go.
- [ ] Modify ./pkg/client/record APIs to include Severity.
- [ ] Modify calls to recorder APIs in the code.
- [ ] Modify kubectl describe and resource printer API related to events.
- [ ] Modify testing (e2e, unit etc) code around events.
- [ ] Change docs

**Comment by saad-ali** [comment] 2015-10-15 21:43
SGTM

**Comment by thockin** [comment] 2015-10-16 00:16
I'd go for more semantically meaningful severity - Info, Warning, Error,
for example.  3 should suffice, we can add more if we need them, but in my
experience it's hard enough to get people using just those 3 correctly.

**Comment by aveshagarwal** [comment] 2015-10-16 12:08
@thockin I am fine with Info, Warning, Error.

**Comment by aveshagarwal** [comment] 2015-10-21 01:02
I have submitted following PR https://github.com/kubernetes/kubernetes/issues/15999 to address this.

**Comment by erictune** [comment] 2015-10-21 16:11
Are the severities meant to relative to the cluster, or relative to the referenced object?

Here are 2 examples illustrate the differences:

(1) it is normal in a moderately large and busy cluster for the scheduler to sometimes bind a pod to a machine where it is subsequently rejected by a kubelet, due to changes in usage, or delayed information about the state of the machine.  

 - From the perspective of the cluster, everything is normal.  The kubelet is doing its job fine.  If the pod has an RC, then very likely that RC will make a new Pod and that new Pod will run okay.  So severity is Info.
 - From the perspective of that Pod, it is very severe, so severity is an Error

(2) Pods in a well functioning service occasionally fail a health check: they take longer than expected to start, or block on a very long query or on accessing a remote resource, or something else.

- From the perspective of the cluster, this is a normal event: the kubelet is doing its job just fine, and it will restart the container, and things will probably be just fine.
-  From the perspective of a Pod, this is a fatal event, so it is an Error.

---

Really, the definition of severity depends on what question the user is trying to answer, ("why did this particular Pod terminate" vs "is my cluster healthy".)

One normal way to consume events is in the context of a particular object in the output of `kubectl describe pods/foo`.  In that context, severity should be object-relative.

Another way people are talking about consuming events is by filtering all events based on severity.  In that context, the severities need to be global.  

In general, the code that generates events is in a good position to apply object-relative severities, but in a poor position to apply global severities.

**Comment by dchen1107** [comment] 2015-10-21 16:34
Well said, @erictune and +1 on object-relative severities.

**Comment by aveshagarwal** [comment] 2015-10-21 17:01
@erictune, I agree with you. And I think that to come up with global or cluster level severities, it would require:

1. Aggregating object level events.
2. Figuring out questions what makes cluster level or global severities.
3. Answering those questions based on 1.

That said, IMO, it is still helpful to add severity (somewhat similar to local log levels) to object level events as reading events reasons and messages could be tedious for cluster administrators to figure out if any action is desired or not. So I would say that it is also a step in the right direction. And it would also help to answer cluster level or global severities as decision making might be easier based on crisp information like severities (info, warn or error) than reasons or messages.

**Comment by bgrant0607** [comment] 2015-10-24 02:56
Enums can't be extended, so we need to carefully think about what severity levels we might want.

**Comment by bgrant0607** [comment] 2015-10-24 02:56
We should also fight event spam by getting rid of useless events.

**Comment by bgrant0607** [comment] 2015-10-24 03:00
People have also asked for distinguishing between user-initiated and system-initiated actions, and between normal and abnormal. I guess in this proposal "Info" would be considered normal. If so, we should ensure that the other severity levels aren't improperly applied to any normal occurrences.

**Comment by bgrant0607** [comment] 2015-10-24 03:15
I could see a case for a 4th: Critical.

**Comment by bgrant0607** [comment] 2015-10-24 03:23
Ah, we could add a User EventSource.

We should revisit #13925.

**Comment by bgrant0607** [comment] 2015-10-24 03:24
Related: #1462, #6532, #15464

**Comment by bgrant0607** [comment] 2015-10-24 03:32
Probably anything not actionable by the user should be Warn at best.

**Comment by bgrant0607** [comment] 2015-10-27 05:15
I agree with @erictune that severity would be perceived differently by the cluster administrator and the user.

**Comment by bgrant0607** [comment] 2015-10-27 06:27
We do need to do something to help users distinguish signal from noise.

These levels of severity are common in logging systems, such as glog. However, in my experience, severity levels defined at the origin of the signal produce an arms race and require constant vigilance in order to fight log/event spam and to maintain the desired signal to noise ratio. Frequently triggering events need to either be fixed or demoted in severity -- severity is a necessarily function of frequency. For an example, look at the proliferation of verbose logging severity levels in Kubernetes. Not only do we have Error, Warning, and Info, but we also have verbose logging levels from 1 to 8, which are all less important (or more frequent/expensive) than Info.

OTOH, in monitoring systems, alert triggers and escalation policies are decoupled from monitoring signal definition. That enables different interpretation of severity in different scenarios.

 In order to distill useful information from log severity levels, inevitably they have to be fed to an anomaly detector.

Sadly, I don't think we can reliably distinguish system-caused vs. user-caused problems, at least not currently. In the general case, even that requires anomaly detection. For instance, it's possible that failure to pull an image could occur because the user specified a non-existent image, but it could also be due to a bug in the image registry, a client-library bug, or a number of other root causes.

Certainly we should be able to distinguish expected (e.g., SuccessfulCreate, Scheduled) from unexpected (e.g., FreeDiskSpaceFailed, FailedScheduling).

I'm not sure more hardcoded levels than that are useful. As evidence of that, the majority of the events in #15999 were characterized as Error or Info. The handful of Warn-severity events were mostly normal but disruptive events, such as terminations and reboots, though some similar events were either categorized as Error or Info, which underscores the difficulty in assigning severities.

Proposal:
* call the categorization `type` rather than `severity`
* document that,  like `reason`, `type` is not an enum and that clients should be tolerant of new types
* start with types `Normal` and `Warn`. In the future, any `type`s other than `Normal` can be considered unexpected/abnormal. Possible future types include UserError, SystemError, etc., but we don't need to spec them right now.
* anything disruptive/undesirable/abnormal, such as anything that kills pods or prevents them from starting, should be categorized as `Warn`

**Comment by bgrant0607** [comment] 2015-10-27 06:31
I'll also point out the similarity to phase vs. conditions: #7856.

**Comment by aveshagarwal** [comment] 2015-10-27 13:39
@bgrant0607 Thanks, your proposal sounds good to me.

**Comment by bgrant0607** [comment] 2015-10-27 16:46
Update: I suggest `Warning` rather than `Warn` (noun vs. verb).

**Comment by thockin** [comment] 2015-12-30 01:11
Seems fixed now

**Closed by thockin** 2015-12-30 01:11 UTC
Labels: area/introspection, area/usability, kind/design, priority/P2, team/api
