### ISSUE TITLE
On kubernetes.io AWS link 404-s

### ISSUE THREAD

**Issue by cristicbz** [kubernetes/kubernetes#15698] opened 2015-10-15 09:40 UTC
Going to "Documentation > Turn-Key Cloud Solutions > AWS" takes you to http://kubernetes.io/v1.0/docs/getting-started-guides/AWS.html which 404s and then redirects back to homepage.

**Comment by jtblin** [comment] 2016-02-12 22:26
The issue doesn't exist for the current site / `v1.1` anymore. Going to "Documentation > Installing Kubernetes and Creating Clusters > Turn-Key Cloud Solutions > AWS" takes you to the correct page. I suggest to close the issue.

**Comment by justinsb** [comment] 2016-02-13 00:45
The problem is still visible here though: http://kubernetes.io/v1.0/gs-turnkey.html

**Comment by justinsb** [comment] 2016-02-13 00:45
I have no idea how that is built though.

**Comment by davidopp** [comment] 2016-02-19 07:40
Assigning to @bgrant0607 to find someone to fix it.

**Comment by bgrant0607** [comment] 2016-02-19 14:59
We're doing massive surgery to the website. Don't know if/when we'll get to this.

**Comment by bgrant0607** [comment] 2016-02-26 19:36
cc @johndmulhausen

**Comment by bgrant0607** [comment] 2016-04-29 00:19
Obsolete

**Closed by bgrant0607** 2016-04-29 00:19 UTC
Labels: area/platform/aws, area/website, kind/bug, kind/documentation, priority/P3, team/ux
