### ISSUE TITLE
ndots breaks DNS resolving

### ISSUE THREAD

**Issue by davidkarlsen** [kubernetes/kubernetes#64924] opened 2018-06-08 16:46 UTC
/kind bug

**What happened**:

cannot resolve cluster-external names
nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'google.com': Name does not resolve

**What you expected to happen**:

be able to resolve

**How to reproduce it (as minimally and precisely as possible)**:
create a pod with:
  dnsPolicy: ClusterFirst

**Anything else we need to know?**:
cat /etc/resolv.conf
nameserver 10.96.0.10
search weave.svc.cluster.local svc.cluster.local cluster.local lan.davidkarlsen.com davidkarlsen.com
options ndots:5 <-- this should not be there

if removing ndots:5 it will be able to resolve external adresses as expected according to policy

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
kubeadm / bare metal

- OS (e.g. from /etc/os-release):
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
uname -a
Linux main.davidkarlsen.com 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

kubeadm

- Others:
kubectl --namespace kube-system get cm/kube-dns -o yaml
apiVersion: v1
data:
  upstreamNameservers: |
    ["192.168.3.2"]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"stubDomains":"{\"lan.davidkarlsen.com\": [\"192.168.3.2\"]}\n","upstreamNameservers":"[\"192.168.3.2\", \"8.8.4.4\", \"8.8.8.8\"]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kube-dns","namespace":"kube-system"}}
  creationTimestamp: 2018-05-28T07:58:16Z
  name: kube-dns
  namespace: kube-system
  resourceVersion: "3162037"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-dns
  uid: e0dd4d17-624c-11e8-8edc-00902755ddee

cat /etc/resolv.conf 
nameserver 192.168.3.2
search lan.davidkarlsen.com davidkarlsen.com

(192.168.3.2 uses upstream dns-servers and is able to resolve.

**Comment by davidkarlsen** [comment] 2018-06-08 16:47
@kubernetes/sig-dns

**Comment by MrHohn** [comment] 2018-06-08 17:17
Can you try `dig +trace` to see what exactly is happening? The ndots option might affect when the initial absolute query be made, but shouldn't break the resolution.

**Comment by zq-david-wang** [comment] 2018-06-09 10:43
I bet your pod image is based on alpine.

**Comment by davidkarlsen** [comment] 2018-06-09 11:28
Also I upgraded to 1.10.4 yesterday after reporting, but still same problem:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zq-david-wang** [comment] 2018-06-09 11:48
Maybe your issue is similar to 
https://github.com/gliderlabs/docker-alpine/issues/255

**Comment by davidkarlsen** [comment] 2018-06-09 12:50
@zq-david-wang Interesting - it does in fact not fail with for instance ubuntu:latest or fedora:latest . -but alpine:latest fails.

**Comment by bboreham** [comment] 2018-06-11 11:33
The rationale for having ndots=5 is explained at length at https://github.com/kubernetes/kubernetes/issues/33554#issuecomment-266251056

I'm not entirely sure why you're seeing a failure - I have looked up lots of names like `google.com` via the alpine musl resolver, and not encountered this issue.  Can you trace the packets and see where the failure comes back?

Lastly, I would note that the name you want is actually `google.com.`, and by adding that last dot you will skip the search path.

**Comment by davidkarlsen** [comment] 2018-06-11 12:12
@bboreham It is only broken in the newer alpine images:

OK:
kubectl run -ti --rm test --image=alpine:3.3 --restart=Never -- nslookup google.com

Fails:
* kubectl run -ti --rm test --image=alpine:3.4 --restart=Never -- nslookup google.com
* kubectl run -ti --rm test --image=alpine:3.5 --restart=Never -- nslookup google.com
* kubectl run -ti --rm test --image=alpine:3.6 --restart=Never -- nslookup google.com
* kubectl run -ti --rm test --image=alpine:3.7 --restart=Never -- nslookup google.com
* kubectl run -ti --rm test --image=alpine:edge --restart=Never -- nslookup google.com

**Comment by bboreham** [comment] 2018-06-11 12:37
Works for me.

```
$ kubectl run -ti --rm test --image=alpine:edge --restart=Never -- nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.15.78 iad23s63-in-f14.1e100.net
Address 2: 2607:f8b0:4004:80c::200e iad23s42-in-x200e.1e100.net
```

If you could supply more detail, e.g. the packets, it may be possible to figure out what happened in your case.

**Comment by zq-david-wang** [comment] 2018-06-11 16:40
@davidkarlsen could you try this image `davidzqwang/alpine-dns:3.7` on your cluster, I made following changes to musl, build a new image based on alpine:3.7, and I test on my cluster, it seems work.

```
diff --git a/src/network/lookup_name.c b/src/network/lookup_name.c
index 209c20f..abb7da5 100644
--- a/src/network/lookup_name.c
+++ b/src/network/lookup_name.c
@@ -202,7 +202,7 @@ static int name_from_dns_search(struct address buf[static MAXADDRS], char canon[
                        memcpy(canon+l+1, p, z-p);
                        canon[z-p+1+l] = 0;
                        int cnt = name_from_dns(buf, canon, canon, family, &conf);
-                       if (cnt) return cnt;
+                       if (cnt > 0 || cnt == EAI_AGAIN) return cnt;
                }
        }

```

**Comment by davidkarlsen** [comment] 2018-06-12 21:15
@zq-david-wang that works!

**Comment by davidkarlsen** [comment] 2018-06-13 17:52
@bboreham 
```
17:51:31.207133 IP test.53401 > kube-dns.kube-system.svc.cluster.local.53: 58898+ A? google.com.default.svc.cluster.local. (54)
17:51:31.208245 IP kube-dns.kube-system.svc.cluster.local.53 > test.53401: 58898 NXDomain 0/1/0 (147)
17:51:31.208642 IP test.49420 > kube-dns.kube-system.svc.cluster.local.53: 26033+ A? google.com.svc.cluster.local. (46)
17:51:31.209409 IP kube-dns.kube-system.svc.cluster.local.53 > test.49420: 26033 NXDomain 0/1/0 (139)
17:51:31.209762 IP test.40807 > kube-dns.kube-system.svc.cluster.local.53: 29573+ A? google.com.cluster.local. (42)
17:51:31.210538 IP kube-dns.kube-system.svc.cluster.local.53 > test.40807: 29573 NXDomain 0/1/0 (135)
17:51:31.210888 IP test.36415 > kube-dns.kube-system.svc.cluster.local.53: 43691+ A? google.com.lan.davidkarlsen.com. (49)
17:51:31.211898 IP kube-dns.kube-system.svc.cluster.local.53 > test.36415: 43691 NXDomain* 0/1/0 (101)
17:51:31.212190 IP test.49947 > kube-dns.kube-system.svc.cluster.local.53: 28911+ A? google.com.davidkarlsen.com. (45)
17:51:31.262140 IP kube-dns.kube-system.svc.cluster.local.53 > test.49947: 28911 0/1/0 (103)
17:51:31.262635 IP test.52532 > kube-dns.kube-system.svc.cluster.local/etc # 
```

**Comment by bboreham** [comment] 2018-06-14 10:13
This looks interesting:

```
17:51:31.212190 IP test.49947 > kube-dns.kube-system.svc.cluster.local.53: 28911+ A? google.com.davidkarlsen.com. (45)
17:51:31.262140 IP kube-dns.kube-system.svc.cluster.local.53 > test.49947: 28911 0/1/0 (103)
```

is your DNS answering that request with something that is not NXDOMAIN?

**Comment by davidkarlsen** [comment] 2018-06-14 16:32
@bboreham 
```
dig google.com.davidkarlsen.com @192.168.3.2

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> google.com.davidkarlsen.com @192.168.3.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25390
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 0dd6c5fa7c9703269d6553405b2298863c4d153ebbbcdcd3 (good)
;; QUESTION SECTION:
;google.com.davidkarlsen.com.   IN      A

;; AUTHORITY SECTION:
davidkarlsen.com.       1763    IN      SOA     ken.ns.cloudflare.com. dns.cloudflare.com. 2028041242 10000 2400 604800 3600

;; Query time: 0 msec
;; SERVER: 192.168.3.2#53(192.168.3.2)
;; WHEN: Thu Jun 14 18:31:37 CEST 2018
;; MSG SIZE  rcvd: 142
```

**Comment by bboreham** [comment] 2018-06-14 17:12
I strongly suspect that is what your problem is - the response is `NOERROR` so the resolver accepts it, and empty so your client fails.  [RFC2308](https://tools.ietf.org/html/rfc2308#section-2.2) has some words of wisdom.

If your DNS returned `NXDOMAIN` the query would continue to the next possibility.

Or, just change the request to `google.com.` and it won't try the search list.

**Comment by davidkarlsen** [comment] 2018-06-14 19:39
Not entirely sure about that: https://serverfault.com/questions/545325/named-returns-empty-noerror-instead-of-nxdomain
NOERROR is returned if the domain exists but not the type, and the resolver library should try the next in the list - don't give up mid-way - also see fix by @zq-david-wang

**Comment by bboreham** [comment] 2018-06-15 08:23
That answer is describing correct DNS behaviour, yes. 
If your DNS server does have a record for `google.com.davidkarlsen.com.` that is not of type `A` then that is truly an unfortunate situation. 

At least it seems there are no further arguments that this is a bug in Kubernetes.

**Comment by davidkarlsen** [comment] 2018-06-15 08:38
I agree it is not a kubernetes bug - it is a musl resolver api bug. And I see the reasoning for having ndots:5 by default. It is a valid question to be able to configure this with parameters - but it is a workaround and not a fix - and a new issue - so closing. 

Thanks for all valuable input.

@zq-david-wang will your fix go in upstream anywhere?

**Comment by zq-david-wang** [comment] 2018-06-15 16:50
@davidkarlsen  musl seems to be a very quiet project now.... I tried to make contact, via mailing list or authors' mail,  no luck yet....
For now, you can build your own alpine abase image like I did:
Stage1: build git://git.musl-libc.org/musl with code changes I suggested in alpine container (apt --update add gcc make)
Stage2: copy the dynamic library to /lib/ld-musl-x86_64.so.1

**Comment by davidkarlsen** [comment] 2018-06-15 20:34
@zq-david-wang thanks a lot - unfortunately it is a weave/flux image which I do not control myself.

**Comment by davidkarlsen** [comment] 2018-06-19 20:48
@bboreham also when consulting cloudflare, their conclusion is:
```
Hi,

Per https://tools.ietf.org/html/rfc8020:

   [...] a response code of NXDOMAIN, it means that the domain
   name which is thus denied AND ALL THE NAMES UNDER IT do not exist.
```
hence I still think DNS is responding with the correct error-codes, but the musl resolver implementation is not acting correctly.

**Comment by bboreham** [comment] 2018-06-19 21:08
Problem is that your DNS did _not_ respond NXDOMAIN when asked about `google.com.davidkarlsen.com.`

**Comment by davidkarlsen** [comment] 2018-06-19 22:42
@bboreham I believe your interpretation of the spec is erroneous. The domain exist, the specific record does not exist, NOERROR with no-entries is a correct answer (and it additionally returns the NS records for the domain...)

**Comment by bboreham** [comment] 2018-06-19 23:02
Seriously, you have a domain `google.com.davidkarlsen.com.` ?

**Comment by zq-david-wang** [comment] 2018-06-26 10:08
@davidkarlsen got a response from alpine (https://bugs.alpinelinux.org/issues/9017),  the conclusion is that the issue is in dns server.  refer to http://www.openwall.com/lists/musl/2018/03/30/6

Start to think that this could be kubedns issue.

**Comment by davidkarlsen** [comment] 2018-06-26 10:45
Could be a cloudflare issue - they respond with NOERROR, while most other servers respond with NXDOMAIN - I have asked their support, but they don't see it as a violation of spec.
Nevertheless - I see it as being quite common - and resolver software should account for this.

```
dig nowhere.cloudflare.com @1.1.1.1

; <<>> DiG 9.10.6 <<>> nowhere.cloudflare.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8344
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;nowhere.cloudflare.com.                IN      A

;; AUTHORITY SECTION:
cloudflare.com.         300     IN      SOA     ns3.cloudflare.com. dns.cloudflare.com. 2028161217 10000 2400 604800 300

;; Query time: 52 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jun 26 12:43:43 CEST 2018
;; MSG SIZE  rcvd: 95
```

```
dig nowhere.google.com @1.1.1.1

; <<>> DiG 9.10.6 <<>> nowhere.google.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59189
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;nowhere.google.com.            IN      A

;; AUTHORITY SECTION:
google.com.             60      IN      SOA     ns1.google.com. dns-admin.google.com. 202092737 900 900 1800 60

;; Query time: 41 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jun 26 12:44:12 CEST 2018
;; MSG SIZE  rcvd: 97

Davids-Work-MacBook-Pro:prometheus et2448$ 
```

**Comment by stealthybox** [comment] 2018-07-08 08:39
@davidkarlsen, you can override the ndots option on the `ClusterFirst` policy by setting `spec.dnsConfig.options` to `{name: ndots, value: "1"}`

This feature was first introduced in 1.9

ref:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service#pod-s-dns-config

spec:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/pod-resolv-conf.md

**Comment by stealthybox** [comment] 2018-07-08 08:42
^ Regardless of the existing ability to override ndots, the peculiar DNS behavior described in this issue may need to be addressed.
Should we re-title this?

**Comment by tylfin** [comment] 2018-07-31 23:10
Running into the same issue, been doing the dnsConfig as an override for applications that experience this. Would love a longterm solution.

Running Kubes 1.11 with CoreDNS on bare-metal

**Comment by dklesev** [comment] 2018-11-09 16:42
for me it doesn't work even with `ndots:1`

**Comment by dklesev** [comment] 2018-11-12 14:32
@tesharp, well, even with blank I get the same issue. Strange thing is that it works for some time and suddenly breaks...

**Comment by Celestialdeath99** [comment] 2018-11-29 07:35
I am having the same issue. I am able to set this for most pods, and then it works, but there are some that are temporarily created when a pipeline for a CI job is executed on the cluster. I do not have control over that part of it so I cannot manually add the spec to the have the ndot value be 1. How can I override it globally and make the default be 1 for every new pod?

**Comment by adam-stanek** [comment] 2018-11-29 08:46
Yeah, that was exactly my situation. I have not found any way to do that so I have finally gave up on this issue and written custom pod initializer for it. It works but I really hate that I had to resort to something like that to make our setup work again... It is few lines of go code but I might share it if you are interested.

**Comment by Celestialdeath99** [comment] 2018-12-05 19:56
@adam-stanek If you are willing to share your solution it would be greatly appreciated! I have been trying everything I can think of to get this to work but nothing is working as of yet.

**Comment by jacobblock** [comment] 2018-12-06 05:13
Glad I found this thread; running into exact same issue. Private k8s cluster running behind rancher. Images that are pulling from github are failing along the lines of the above discussion. I think all the images seeing the issue are alpine based (version 3.8.1). @Celestialdeath99 would a custom resolv.conf work for your use case? See https://gist.github.com/superseb/f6894ddbf23af8e804ed3fe44dd48457 and https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ for reference.

**Comment by adam-stanek** [comment] 2018-12-06 13:07
@Celestialdeath99 Will this be helpful? https://gist.github.com/adam-stanek/8331d44bb38b864efdd693667ea170c1 I don't have time right now to create proper repo with step by step docs, but I might do it during some weekend if you think it would be useful for more people.

Please keep keep in mind that I am not a Go developer. I have put the code together after some research and it is working fine for me but surely it can be improved.

**Comment by Angelinsky7** [comment] 2019-01-14 16:17
i've got the same issue with some container today : 

Linux test-77fd4f49f7-m5b75 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 Linux

this is my resolve.conf file :
```
nameserver 10.43.0.10
search gitlab.svc.cluster.local svc.cluster.local cluster.local darkink.internal.
options ndots:5
```

if i remove (this is not very possible because some container are build from gitlab and others) this line : `options ndots:5` my dns is working correctly again. The issue is only on some host (not all) and if i add a `.` at the end of the host everything is resolving corretly

Can someone help ?

**Comment by NULLx76** [comment] 2019-01-23 20:23
I am also experiencing this same issue. Setting `spec.dnsConfig.options` to `{name: ndots, value: "1"}` does fix it. However, I don't want to do this for every container, is there any way that I can change the global default or do something else to resolve this.

Any help is appreciated

**Comment by cclloyd** [comment] 2019-02-11 02:03
I'm also having this issue.  Set up a 1 master 2 node cluster with kubespray.  Containers work if I set `ndots:1`, but anything more and it appends my domain name to any request.

**Comment by WeihanLi** [comment] 2019-04-06 10:12
I've also had this problem. In my case,  it only happened on `alpine` based image, it works on `Debian` based image

![image](https://user-images.githubusercontent.com/7604648/55668083-1f4da900-5897-11e9-8c0c-1f818d082ad4.png)

**Comment by fabiorauber** [comment] 2019-04-06 10:42
Solved this in Ubuntu 18.04 hosts by upgrading the kernel from 4.15 to 4.18. Now all my Alpine-based Pods have no trouble solving DNS names.

**Comment by WeihanLi** [comment] 2019-04-07 02:31
> Solved this in Ubuntu 18.04 hosts by upgrading the kernel from 4.15 to 4.18. Now all my Alpine-based Pods have no trouble solving DNS names.

After upgrade the kernel to latest(5.0.7-050007-generic), the problem still exists

**Comment by Constantin07** [comment] 2019-04-07 17:02
I'm also having issue with Alpine (3.6.0) pods on Kubenetes  (v1.14.0) with Ubuntu 18.04.2 LTS Kernel 4.15.0-47-generic. Only removing `options ndots` helped. Thanks @Angelinsky7 

Is there any option to get rid of  `options ndots` ?

**Comment by prameshj** [comment] 2019-05-02 22:01
You can customize pod dns similar to the example here - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config
You can set ndots to 1. 

From earlier comments, this seems like a musl implementation issue rather than kubernetes dns?
https://bugs.alpinelinux.org/issues/9017 says the dnsclient stops trying other searchpaths if a previous one returns unexpected error. Looks like this unexpected error is returned from whatever server is the upstream for the node. Maybe cloudFlare, something else. Setting ndots to a small value like 1, will ensure searchpath expansion does not kick in for hostnames with atleast 2 labels. 

Based on this, i am closing the issue, please reopen if needed.

/close

**Closed by prameshj** 2019-05-02 22:01 UTC
Labels: area/dns, kind/bug, sig/network, triage/unresolved

**Comment by pmhahn** [comment] 2020-09-25 15:17
> You can customize pod dns similar to the example here - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config

Correct my if I'm wrong, but this I would have to do manually for *each* pod.
I would like to configure this globally and make it the default: I'm experiencing random DNS failures with my GitLab-Runner, which starts multiple new temporary pods for running the individual jobs: They seem to inherit the default `ndots:5` and fail to resolve the external DNS entry. I'm still investigating the underlying problem, but it mostly happens when the DNS cache is cold, e.g. I'm starting jobs after a period if inactivity. If I restart those failing jobs manually, the 2nd time the succeed and are able to resolve the external DNS entry.
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4129

**Comment by Freundschaft** [comment] 2021-03-20 23:11
> > You can customize pod dns similar to the example here - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config
> 
> Correct me if I'm wrong, but this I would have to do manually for _each_ pod.
> I would like to configure this globally and make it the default: I'm experiencing random DNS failures with my GitLab-Runner, which starts multiple new temporary pods for running the individual jobs: They seem to inherit the default `ndots:5` and fail to resolve the external DNS entry. I'm still investigating the underlying problem, but it mostly happens when the DNS cache is cold, e.g. I'm starting jobs after a period if inactivity. If I restart those failing jobs manually, the 2nd time the succeed and are able to resolve the external DNS entry.
> https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4129

sorry to comment on a closed topic, but was a global ndots option ever introduced?

**Comment by Szpadel** [comment] 2022-08-27 14:29
For anyone that came here looking for solution for very similar issue where eg wget or other apps reported bad domain but nslookup worked fine
also ndots:1 resolves issue but the same container works on other cluster.
The issue was in extra `.` at the end of search in resolv.conf:
```search default.svc.cluster.local svc.cluster.local cluster.local .```
that dot came from `search .` on the host, and removing that line resolved dns issues

**Comment by dmeijboom** [comment] 2022-09-10 15:43
> For anyone that came here looking for solution for very similar issue where eg wget or other apps reported bad domain but nslookup worked fine also ndots:1 resolves issue but the same container works on other cluster. The issue was in extra `.` at the end of search in resolv.conf: `search default.svc.cluster.local svc.cluster.local cluster.local .` that dot came from `search .` on the host, and removing that line resolved dns issues

I'm not an export on DNS but for some reason this worked! I did the following things:
- Remove `/etc/resolv.conf` symlink and created a file with the same content (without `search .` obviously)
- Changed the `resolvConf` parameter in the `KubeletConfiguration` to `/etc/resolve.conf` (it was set to: `/run/systemd/resolve/resolv.conf` previously)
- Restarted all kubelets and voila

**Comment by dellnoantechnp** [comment] 2023-10-11 12:17
Gitlab-runner  helm default used  `gitlab-runner-helper:alpine-****` container image.
even `gitlab-runner-helper`  container `alpine-release` is  Alpine-3.18.

## Don't trust alpine base image.

config use like ubuntu tag:
```yaml
[runners.kubernetes]
     helper_image_flavor = "ubuntu"
```
