### ISSUE TITLE
Heapster monitoring e2e test is still very flaky

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#6541] opened 2015-04-07 23:05 UTC
It fails about 70% of the time at the moment (21 failures our of the past 30 runs in Jenkins)

Examples of success and failure cases are below.
In essence the failures are a result of the pod records not appearing in influxdb within the 5 minute timeout.  In success cases, they show up in <15 seconds.

I think that rjnagal@ has looked into this in the past.  I'll have another shot at it.

FAILURE EXAMPLE:
=================
INFO: failed to query list of pods from influxdb. Query: "select distinct(pod_id) from /cpu.*/", Err: expected only one series from Influxdb for query "select distinct(pod_id) from /cpu.*/". Got []

• Failure [300.668 seconds]
Monitoring
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/monitoring.go:50
  verify monitoring pods and all cluster nodes are available on influxdb using heapster. [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/monitoring.go:49

  monitoring using heapster and influxdb test failed

SUCCESS EXAMPLE:
===================

Monitoring 
  verify monitoring pods and all cluster nodes are available on influxdb using heapster.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/monitoring.go:49
[BeforeEach] Monitoring
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/monitoring.go:40
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/.kubeconfig
[It] verify monitoring pods and all cluster nodes are available on influxdb using heapster.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/monitoring.go:49
•

**Comment by quinton-hoole** [comment] 2015-04-07 23:06
Interestingly I have failed to reproduce the test failure on a local test cluster.  30 successful runs so far.  Might well be related to short-running vs long-running clusters (mine is long-running, Jenkins is short-running).  I'll try a bit harder.

**Comment by vishh** [comment] 2015-04-07 23:16
cc @rjnagal

**Comment by quinton-hoole** [comment] 2015-04-07 23:21
I've now managed to reproduce it locally, and it's failing consistently.  So far it seems that influxdb either comes up healthy in a cluster, and this test consistently succeeds, or it comes up unhealthy, and the test consistently fails.  Based on Jenkins runs (each of which runs on a newly build cluster), heapster fails to come up healthy about 70% of the time.

I'm going to suggest marking it as Pending (i.e. known flakey and skipped by Jenkins) until we've debugged it properly, as it's failures are masking other tests.

**Comment by quinton-hoole** [comment] 2015-04-09 00:07
Assigned to rjnagal@, who's busy looking into this.

**Comment by rjnagal** [comment] 2015-04-10 23:35
I think this was caused by changing the default to v1beta3. #6710 should fix it. I'll run e2e a few more times before enabling it back.

**Comment by rjnagal** [comment] 2015-04-14 18:44
field of greens !

**Comment by ihmccreery** [comment] 2016-01-30 00:59
All of the tests in `monitoring.go` are still labeled `[Flaky]` at `HEAD`.  Please send a PR to promote them out of `[Flaky]` to close this issue.

**Comment by ixdy** [comment] 2016-02-09 23:44
Tests are still marked flaky.

**Comment by piosz** [comment] 2016-02-11 20:16
This was fixed in #20156

**Closed** 2016-02-11 21:06 UTC
Labels: kind/flake, priority/P2, team/test-infra
