### ISSUE TITLE
E2E flake: Pods should have their auto-restart back-off timer reset on image update

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16248] opened 2015-10-25 15:29 UTC
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/14168/#

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:913
Oct 24 23:11:13.505: updating image did not reset the back-off value in pod=pod-back-off-image/back-off d3=29s d2=25s d1=50s
```

**Comment by erictune** [comment] 2015-10-26 18:23
xref #15800

**Comment by lavalamp** [comment] 2015-10-27 23:27
Happened again, blocking merges.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/10392

```
15:59:58 [BeforeEach] Pods
15:59:58   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
15:59:58 STEP: Creating a kubernetes client
15:59:58 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel/workspace/.kube/config
15:59:58 STEP: Building a namespace api object
15:59:58 Oct 27 15:55:19.706: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-pods-wqta4
15:59:58 Oct 27 15:55:19.707: INFO: Get service account default in ns e2e-tests-pods-wqta4 failed, ignoring for 2s: serviceaccounts "default" not found
15:59:58 Oct 27 15:55:21.713: INFO: Service account default in ns e2e-tests-pods-wqta4 with secrets found. (2.00764582s)
15:59:58 STEP: Waiting for a default service account to be provisioned in namespace
15:59:58 Oct 27 15:55:21.713: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-pods-wqta4
15:59:58 Oct 27 15:55:21.720: INFO: Service account default in ns e2e-tests-pods-wqta4 with secrets found. (7.072992ms)
15:59:58 [It] should have their auto-restart back-off timer reset on image update
15:59:58   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:913
15:59:58 STEP: submitting the pod to kubernetes
15:59:58 Oct 27 15:55:21.733: INFO: Waiting up to 5m0s for pod pod-back-off-image status to be running
15:59:58 Oct 27 15:55:21.858: INFO: Waiting for pod pod-back-off-image in namespace 'e2e-tests-pods-wqta4' status to be 'running'(found phase: "Pending", readiness: false) (124.804251ms elapsed)
15:59:58 Oct 27 15:55:23.951: INFO: Waiting for pod pod-back-off-image in namespace 'e2e-tests-pods-wqta4' status to be 'running'(found phase: "Pending", readiness: false) (2.218144073s elapsed)
15:59:58 Oct 27 15:55:25.965: INFO: Found pod 'pod-back-off-image' on node 'e2e-test-parallel-minion-edib'
15:59:58 STEP: verifying the pod is in kubernetes
15:59:58 STEP: getting restart delay-0
15:59:58 Oct 27 15:56:26.994: INFO: getRestartDelay: finishedAt=2015-10-27 15:56:01 -0700 PDT restartedAt=2015-10-27 15:56:26 -0700 PDT (25s)
15:59:58 STEP: getting restart delay-1
15:59:58 Oct 27 15:57:16.455: INFO: getRestartDelay: finishedAt=2015-10-27 15:56:31 -0700 PDT restartedAt=2015-10-27 15:57:16 -0700 PDT (45s)
15:59:58 STEP: getting restart delay-2
15:59:58 Oct 27 15:58:47.011: INFO: getRestartDelay: finishedAt=2015-10-27 15:57:21 -0700 PDT restartedAt=2015-10-27 15:58:46 -0700 PDT (1m25s)
15:59:58 STEP: updating the image
15:59:58 Oct 27 15:58:57.021: INFO: Waiting up to 5m0s for pod pod-back-off-image status to be running
15:59:58 Oct 27 15:58:57.026: INFO: Found pod 'pod-back-off-image' on node 'e2e-test-parallel-minion-edib'
15:59:58 STEP: get restart delay after image update
15:59:58 Oct 27 15:59:53.423: INFO: getRestartDelay: finishedAt=2015-10-27 15:58:51 -0700 PDT restartedAt=2015-10-27 15:59:53 -0700 PDT (1m2s)
15:59:58 STEP: deleting the pod
15:59:58 [AfterEach] Pods
15:59:58   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:52
15:59:58 STEP: Collecting events from namespace "e2e-tests-pods-wqta4".
15:59:58 Oct 27 15:59:53.443: INFO: event for pod-back-off-image: {scheduler } Scheduled: Successfully assigned pod-back-off-image to e2e-test-parallel-minion-edib
15:59:58 Oct 27 15:59:53.443: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulled: Container image "beta.gcr.io/google_containers/pause:2.0" already present on machine
15:59:58 Oct 27 15:59:53.443: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id f13a091b50ed
15:59:58 Oct 27 15:59:53.443: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id f13a091b50ed
15:59:58 Oct 27 15:59:53.443: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulling: pulling image "gcr.io/google_containers/busybox"
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulled: Successfully pulled image "gcr.io/google_containers/busybox"
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id e542e7b4555e
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id e542e7b4555e
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulled: Container image "gcr.io/google_containers/busybox" already present on machine
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 182847edad36
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 182847edad36
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Backoff: Back-off restarting failed docker container
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 10c3ce6ada1a
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 10c3ce6ada1a
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 4f4568c7edf4
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 4f4568c7edf4
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 024218479a6c
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 024218479a6c
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 3388eee03c62
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 3388eee03c62
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Killing: Killing with docker id 3388eee03c62
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulling: pulling image "nginx"
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Pulled: Successfully pulled image "nginx"
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Created: Created with docker id 1b87345c0d15
15:59:58 Oct 27 15:59:53.444: INFO: event for pod-back-off-image: {kubelet e2e-test-parallel-minion-edib} Started: Started with docker id 1b87345c0d15
15:59:58 Oct 27 15:59:53.466: INFO: POD                                                  NODE                           PHASE    GRACE  CONDITIONS
15:59:58 Oct 27 15:59:53.466: INFO: rand-non-local-nb6cm                                 e2e-test-parallel-minion-g0i5  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:59:51 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: rand-non-local-oexao                                 e2e-test-parallel-minion-fx5c  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:59:51 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: redis-master-04wb0                                   e2e-test-parallel-minion-fx5c  Pending         []
15:59:58 Oct 27 15:59:53.466: INFO: pd-test-55c89675-7cfe-11e5-8913-42010af01555         e2e-test-parallel-minion-2nkj  Pending         []
15:59:58 Oct 27 15:59:53.466: INFO: pd-test-55c897e8-7cfe-11e5-8913-42010af01555         e2e-test-parallel-minion-3ojs  Pending         []
15:59:58 Oct 27 15:59:53.466: INFO: pd-test-16f11f60-7cfe-11e5-abf7-42010af01555         e2e-test-parallel-minion-2nkj  Pending         []
15:59:58 Oct 27 15:59:53.466: INFO: pd-test-e4805f0e-7cfd-11e5-972b-42010af01555         e2e-test-parallel-minion-2nkj  Pending         []
15:59:58 Oct 27 15:59:53.466: INFO: pod-back-off-exponentially                           e2e-test-parallel-minion-fx5c  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:59:30 -0700 PDT ContainersNotReady containers with unready status: [back-off]}]
15:59:58 Oct 27 15:59:53.466: INFO: liveness-exec                                        e2e-test-parallel-minion-3ojs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:59:42 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: liveness-exec                                        e2e-test-parallel-minion-2nkj  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:58:01 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: elasticsearch-logging-v1-un7fm                       e2e-test-parallel-minion-wpqo  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:44 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: elasticsearch-logging-v1-vbwxu                       e2e-test-parallel-minion-g0i5  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:41 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-2nkj  e2e-test-parallel-minion-2nkj  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:32 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-3ojs  e2e-test-parallel-minion-3ojs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:29 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-edib  e2e-test-parallel-minion-edib  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:26 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-fx5c  e2e-test-parallel-minion-fx5c  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:54:04 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-g0i5  e2e-test-parallel-minion-g0i5  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:43 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: fluentd-elasticsearch-e2e-test-parallel-minion-wpqo  e2e-test-parallel-minion-wpqo  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:46 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: heapster-v10-smmdl                                   e2e-test-parallel-minion-g0i5  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:14 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: kibana-logging-v1-jwgq7                              e2e-test-parallel-minion-2nkj  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:36 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: kube-dns-v9-jbslv                                    e2e-test-parallel-minion-edib  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:26 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: kube-ui-v3-84uml                                     e2e-test-parallel-minion-2nkj  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:09 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.466: INFO: monitoring-influxdb-grafana-v2-fpyyv                 e2e-test-parallel-minion-3ojs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2015-10-27 15:52:40 -0700 PDT  }]
15:59:58 Oct 27 15:59:53.467: INFO: 
15:59:58 Oct 27 15:59:53.467: INFO: Waiting up to 1m0s for all nodes to be ready
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-2nkj condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:51:51 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-2nkj readiness to be true
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-3ojs condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:51:52 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-3ojs readiness to be true
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-edib condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:51:56 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-edib readiness to be true
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-fx5c condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:53:40 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-fx5c readiness to be true
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-g0i5 condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:52:00 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-g0i5 readiness to be true
15:59:58 Oct 27 15:59:53.472: INFO: Node e2e-test-parallel-minion-wpqo condition 1/2: type: Ready, status: True, reason: "KubeletReady", message: "kubelet is posting ready status", last transition time: 2015-10-27 15:52:04 -0700 PDT
15:59:58 Oct 27 15:59:53.472: INFO: Successfully found node e2e-test-parallel-minion-wpqo readiness to be true
15:59:58 STEP: Destroying namespace "e2e-tests-pods-wqta4" for this suite.
15:59:58 
15:59:58 
15:59:58 • Failure [278.793 seconds]
15:59:58 Pods
15:59:58 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:1188
15:59:58   should have their auto-restart back-off timer reset on image update [It]
15:59:58   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:913
15:59:58 
15:59:58   Oct 27 15:59:53.423: updating image did not reset the back-off value in pod=pod-back-off-image/back-off d3=1m2s d2=45s d1=1m25s
15:59:58 
15:59:58   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:911
15:59:58 ------------------------------
```

**Comment by lavalamp** [comment] 2015-11-19 19:20
Happened again:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9475/

@dchen1107 can you please find an owner?

**Comment by dchen1107** [comment] 2015-11-19 20:10
https://github.com/kubernetes/kubernetes/pull/16339 were supposed to fix the issue. Looks like a regression, @samsabed?

**Comment by dchen1107** [comment] 2015-11-20 19:58
This is a new regression, which should have the same cause as https://github.com/kubernetes/kubernetes/issues/17523

**Comment by dchen1107** [comment] 2015-11-20 21:43
I believe https://github.com/kubernetes/kubernetes/pull/17582 should fix the regression here. Close this one and please re-open it if the problem still occurred.

**Closed by dchen1107** 2015-11-20 21:43 UTC
Labels: kind/flake, priority/P0, team/node

**Comment by samsabed** [comment] 2015-11-22 06:20
nice troubleshooting and quick !
