### ISSUE TITLE
APIs to show recent revisions of configMap

### ISSUE THREAD

**Issue by defool** [kubernetes/kubernetes#90929] opened 2020-05-09 10:12 UTC
**What would you like to be added**:
APIs to show recent revisions of configMap.

**Why is this needed**:
Reversion history of configMap is useful for troubleshooting and rollback.

**Comment by liggitt** [comment] 2020-05-09 14:57
Thanks for the request. Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/22368 which includes revision management as a goal

**Closed by liggitt** 2020-05-09 14:57 UTC
Labels: kind/feature, sig/api-machinery
