### ISSUE TITLE
Loss of Kind and APIVersion in Errors from Request.Stream

### ISSUE THREAD

**Issue by magicsong** [kubernetes/kubernetes#129102] opened 2024-12-06 07:45 UTC
### What happened?

When invoking the func (r *Request) Stream(ctx context.Context) (io.ReadCloser, error) function in the Kubernetes client-go library, the error returned by the apiserver originally includes fields such as kind and apiVersion (e.g., "kind":"Status","apiVersion":"v1"). However, after passing through the rest-client’s processing logic, these fields (Kind and APIVersion) are stripped from the error object.

This leads to the following issues:

Users lose structured metadata (Kind, APIVersion) from the original server response, which is essential for identifying and categorizing the error type.
It becomes challenging to programmatically distinguish between different error types or versions without additional error handling logic.

### What did you expect to happen?

same as apiserver

### How can we reproduce it (as minimally and precisely as possible)?

Make a request using the Kubernetes client-go library that results in an error, e.g., an invalid resource request.
Observe the response from the apiserver (e.g., using a network debugging tool like kubectl or other HTTP debugging methods) to verify that the Kind and APIVersion fields are present in the error payload.
Check the error returned by the Request.Stream function to observe the absence of Kind and APIVersion.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment] 2024-12-14 04:45
This is a duplicate of the feature request at https://github.com/kubernetes/kubernetes/issues/80609

when using the typed client, the apiVersion/kind determines the go type the object is decoded to, and is then redundant and is discarded

**Closed by liggitt** 2024-12-14 04:45 UTC
Labels: kind/bug, sig/api-machinery, triage/accepted
