### ISSUE TITLE
Endpoint update its state very slow when shutdown a node

### ISSUE THREAD

**Issue by renyuntao** [kubernetes/kubernetes#97112] opened 2020-12-08 03:22 UTC
When I run `shutdown -h now` command to  shutdown a node in kubernetes cluster, endpoint update its state after about 40 seconds, but when I run command `kubectl delete pod POD-NAME`, endpoint update its state very quick. Can anyone explain why?

**Comment by pacoxu** [comment] 2020-12-08 07:46
Do you configure readiness check on your pod?

Or please check the param below, it may be caused by that the node is marked as NotReady after a grace period. This is configurable. After that, pod will be terminating and rescheduled
```
--node-monitor-grace-period duration     Default: 40s
--
  | Amount of time which we allow running Node to be unresponsive before marking it unhealthy. Must be N times more than kubelet's nodeStatusUpdateFrequency, where N means number of retries allowed for kubelet to post node status.

``` 
refer to https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by renyuntao** [comment] 2020-12-09 11:09
@pacoxu Thank you very much, it's  the problem of `--node-monitor-grace-period duration` option, when I change the value of `--node-monitor-grace-period` to `10s`, endpoint update its state more quick.

**Closed** 2020-12-09 11:09 UTC
Labels: kind/support, needs-sig, needs-triage

**Comment by renyuntao** [comment] 2020-12-09 11:11
Problem has been resolved.

**Comment by pacoxu** [comment] 2020-12-09 11:33
> @pacoxu Thank you very much, it's the problem of `--node-monitor-grace-period duration` option, when I change the value of `--node-monitor-grace-period` to `10s`, endpoint update its state more quick.

If you set it too small, there would be some **risks**. For instance, a temporary failure of network for a small period would result in pod scheduling frequently.

**Comment by renyuntao** [comment] 2020-12-09 14:25
> > @pacoxu Thank you very much, it's the problem of `--node-monitor-grace-period duration` option, when I change the value of `--node-monitor-grace-period` to `10s`, endpoint update its state more quick.
> 
> If you set it too small, there would be some **risks**. For instance, a temporary failure of network for a small period would result in pod scheduling frequently.

I change the value of `--node-monitor-grace-period` just for test, thanks.

**Comment by guanxingfeng** [comment] 2021-04-14 09:33
@pacoxu
I also encountered the problem of service access high availability when the node fails. The customer requires service failover within 3s after the node fails. I think it is not a good practice to adjust the parameters because it will bring more risks. Is there a better way? My current thoughts are:
1. Does kube-proxy have an active or passive health check for endpoints? It can check and remove unavailable endpoints within 3 seconds
2. Can it be solved with the help of a service mesh such as istio？

**Comment by guanxingfeng** [comment] 2021-04-14 09:33
@pacoxu
I also encountered the problem of service access high availability when the node fails. The customer requires service failover within 3s after the node fails. I think it is not a good practice to adjust the parameters because it will bring more risks. Is there a better way? My current thoughts are:
1. Does kube-proxy have an active or passive health check for endpoints? It can check and remove unavailable endpoints within 3 seconds
2. Can it be solved with the help of a service mesh such as istio？

**Comment by pacoxu** [comment] 2021-04-14 10:33
1. Do you mean readiness probe（you can set smaller interval/timeout）
2. not familiar with istio😓
