### ISSUE TITLE
KUBE_ENABLE_INSECURE_REGISTRY=true makes nothing if also using KUBE_USE_EXISTING_MASTER=true on KUBERNETES_PROVIDER=aws

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#24084] opened 2016-04-10 13:39 UTC
Trying to deploy a multi-az workers cluster I found that when I add the second zone using

KUBE_USE_EXISTING_MASTER=true MULTIZONE=1 KUBERNETES_PROVIDER=aws KUBE_AWS_ZONE=us-west-1b NODE_SIZE=t2.small KUBERNETES_SKIP_DOWNLOAD=true KUBE_SUBNET_CIDR=172.20.1.0/24 MASTER_INTERNAL_IP=172.20.0.9 NUM_NODES=1 KUBE_AWS_INSTANCE_PREFIX=kubernetes-stag KUBE_ENABLE_INSECURE_REGISTRY=true ./kubernetes/cluster/kube-up.sh

makes nothing,

admin@ip-172-20-1-138:~$ cat /etc/sysconfig/docker

DOCKER_OPTS=" -s aufs  --bridge=cbr0 --iptables=false --ip-masq=false --log-level=warn"
DOCKER_NOFILE=1000000

**Comment by lavalamp** [comment] 2016-04-13 22:53
@justinsb can you triage this?

**Comment by wsimmonds** [comment] 2016-06-14 10:53
@felipejfc: This issue is caused by the fact it's reading the environment variables from the master by SSH'ing in and downloading /etc/kubernetes/kube_env.yaml (get-master-env function in cluster/aws/util.sh):

ssh -oStrictHostKeyChecking=no -i "${AWS_SSH_KEY}" ${SSH_USER}@${KUBE_MASTER_IP} sudo cat /etc/kubernetes/kube_env.yaml

So if you didn't originally specify it (our case), it means setting KUBE_ENABLE_INSECURE_REGISTRY or EXTRA_DOCKER_OPTS when scaling out has no impact.

Same complaint: #23922

**Comment by roberthbailey** [comment] 2017-04-25 06:32
Closing as https://github.com/kubernetes/kubernetes/pull/42196 removed AWS support from kube-up.

**Closed by roberthbailey** 2017-04-25 06:32 UTC
Labels: area/platform/aws, sig/cluster-lifecycle, team/control-plane (deprecated - do not use)
