### ISSUE TITLE
multiple header shown when get service list 

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#69555] opened 2018-10-09 05:33 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I was using kubectl to get service list but find the it will printer duplicated header.

```
root@hchenxa-2:~/hchenwork/opentraceing# kubectl  get service --all-namespaces | grep -v nginx  | grep -v kube-system
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
default           date-server                                      ClusterIP   10.0.45.13     <none>        8080/TCP            2h
default           kubernetes                                       ClusterIP   10.0.0.1       <none>        443/TCP             31d
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
NAMESPACE         NAME                                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
default           zipkin                                           ClusterIP   10.0.223.224   <none>        9411/TCP            2h
docker-registry   docker-registry                                  ClusterIP   10.0.63.45     <none>        5000/TCP            1d
```

The reason may caused by I have 3000+ services.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

create 3000 service and use kubectl to get the service list

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by juanvallejo** [comment] 2018-10-15 14:48
Closing, as this is not a bug.

/close

**Closed by juanvallejo** 2018-10-15 14:48 UTC
Labels: kind/bug, sig/cli
