### ISSUE TITLE
MutatingWebhook not Load Balancing Across Replicas

### ISSUE THREAD

**Issue by michaelkipper** [kubernetes/kubernetes#75791] opened 2019-03-27 20:38 UTC
**What happened**:

We have an admission controller running as a `Deployment` with 3 replicas. Looking at the metrics for those replicas, we see admission spikes (during deploys, for example) causing a spike in latency for the controller, but only one of the replicas is actually receiving the traffic.

**What you expected to happen**:

Load balancing across the replicas, reducing the latency spikes.

**How to reproduce it (as minimally and precisely as possible)**:

The `cusco-sidecar-injector` service:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-03-13T20:40:23Z"
  labels:
    app: cusco-sidecar-injector
  name: cusco-sidecar-injector
  namespace: cusco-sidecar-injector
  resourceVersion: "287723231"
  selfLink: /api/v1/namespaces/cusco-sidecar-injector/services/cusco-sidecar-injector
  uid: 39ec346a-45d0-11e9-a7e0-42010a80014c
spec:
  clusterIP: <redacted>
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: cusco-sidecar-injector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

(Note: Not sure if the `status.loadBalancer` is related...)

The Deployment:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2019-03-13T20:40:23Z"
  generation: 11
  labels:
    app: cusco-sidecar-injector
  name: cusco-sidecar-injector
  namespace: cusco-sidecar-injector
  resourceVersion: "297194057"
  selfLink: /apis/extensions/v1beta1/namespaces/cusco-sidecar-injector/deployments/cusco-sidecar-injector
  uid: 39c3727b-45d0-11e9-a7e0-42010a80014c
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cusco-sidecar-injector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cusco-sidecar-injector
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cusco-sidecar-injector
            topologyKey: kubernetes.io/hostname
      containers:
        ...
```

Here's our webhook config:

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2019-03-13T20:39:29Z"
  generation: 1
  labels:
    app: cusco-sidecar-injector
  name: cusco-sidecar-injector
  resourceVersion: "287722795"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/cusco-sidecar-injector
  uid: 194637ed-45d0-11e9-a7e0-42010a80014c
webhooks:
- clientConfig:
    caBundle: <redacted>
    service:
      name: cusco-sidecar-injector
      namespace: cusco-sidecar-injector
      path: /inject
  failurePolicy: Ignore
  name: sidecar-injector.shopify.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    resources:
    - pods
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`GKE`

**Comment by michaelkipper** [comment] 2019-03-27 20:40
@kubernetes/sig-api-machinery-bugs

**Comment by yue9944882** [comment] 2019-03-28 05:06
seems like a dup of [https://github.com/kubernetes/kubernetes/issues/61296#issuecomment-374498664](https://github.com/kubernetes/kubernetes/issues/61296#issuecomment-374498664)

**Comment by caesarxuchao** [comment] 2019-03-28 20:30
I agree it's worth trying `--enable-aggregator-routing`.

However, when the flag is disabled, I expect kube-proxy to loadbalance the traffic among endpoints. What do I miss?

**Comment by lmunro-at-shopify** [comment] 2019-04-08 19:34
@caesarxuchao I think what's actually happening is due to the fact that kube-proxy does not truly loadbalance traffic.
It randomly assigns an endpoint to a connection (using iptables in this case).

I have noticed the api-server opening a fairly low number of long running connections to my own admission-controller. In one environment it was only 3 connections total, for a total of 3 pods running the admission-controller itself.

I don't see anything to prevent those few connections from randomly being assigned to the same pod.
I have seen cases where `netstat` inside the admission controller pods showed some with more than one connection, and others without any.

**Comment by liggitt** [comment] 2019-08-13 04:01
when using HTTP/1.1, even if kube-proxy randomly balanced (instead of round-robin, etc), enough concurrent requests would force new connections to open and even out over the long-run

when using HTTP/2, concurrent requests multiplex over a single connection, so fewer connections are opened, and it is more likely a lopsided traffic distribution will result

**Comment by liggitt** [comment] 2019-08-14 20:09
@michaelkipper as an experiment, can you run the kube-apiserver with the [`DISABLE_HTTP2=true` envvar](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L111-L118), and see if that balances out the

**Comment by liggitt** [comment] 2019-08-14 20:10
with sufficient numbers of connections, the random assignment by iptables should spread the load. I think the issue is with the http/2 client not opening multiple connections. One experiment would be to disable http/2 clients with an [`DISABLE_HTTP2=true` envvar](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L111-L118) when starting the apiserver and see if concurrent requests were spread better among backing pods

**Comment by michaelkipper** [comment] 2019-08-15 11:27
We use managed Kubernetes on Google Cloud, so I'm not sure this is possible/sustainable.

**Comment by lmunro-at-shopify** [comment] 2019-08-15 13:38
@liggitt I agree with your interpretation.

Not being able to change anything on `kube-apiserver` (because GKE), I ran an experiment a while ago where I forked [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and forced a downgrade from HTTP2 to HTTP1.1 with `SetKeepAlivesEnabled(false)` on the admission controller's `httpServer`.

Forcing a new connection on every request did indeed end up sending the same number of requests to each backend.
But that would require losing the benefits of HTTP2 and/or `Connection: Keep-Alive`, and is not currently supported by controller-runtime anyway.

**Comment by liggitt** [comment] 2019-08-15 13:42
> We use managed Kubernetes on Google Cloud, so I'm not sure this is possible/sustainable.

yeah, not suggesting it as a solution, just as a triage tool to narrow down the issue

**Comment by liggitt** [comment] 2019-08-15 13:43
HTTP/1.1 with keep-alive might be a reasonable balance. serial requests would go to a single backend as long as the connection was kept alive, but concurrent requests would distribute better. I'll look into what it would take to make the webhook clients use HTTP/1.1 as a short-term solution.

**Comment by lavalamp** [comment] 2019-08-15 16:53
For APIService (aggregated apiserver) we deliberately look at the endpoints and connect directly, if we're connecting to a service in the cluster, anyway.

Idea 1: We might want to add similar logic in apiserver to make the webhook connections.

Idea 2 (**actionable experiment**): There's (at least) two relevant ways to configure a Service in Kubernetes--ClusterIP, which ends up with a single IP, and [headless with selectors](https://kubernetes.io/docs/concepts/services-networking/service/#with-selectors). If you do the latter, the DNS resolution will return a list of endpoints rather than a single virtual IP. Now, I actually don't know what the go HTTP client does in this case; I would hope that it would round-robin between them, maintaining a connection to each. If it doesn't, we could write custom code that does this and/or seek to fix upstream.

Idea 3: since this HTTP2 behavior seems to come up in nearly every network call path--we could look at reducing the number of streams per connection or something like that. Overall it's probably better to be deliberate about doing things in a way that results in even load, but it's also more work.

**Comment by liggitt** [comment] 2019-08-15 17:10
> For APIService (aggregated apiserver) we deliberately look at the endpoints and connect directly, if we're connecting to a service in the cluster, anyway.

Webhooks resolve services the same way aggregated API servers do. API aggregation has the same http/2 balancing issue.

> Now, I actually don't know what the go HTTP client does in this case; I would hope that it would round-robin between them, maintaining a connection to each.

It resolves the [DNS name to a list of IPs](https://github.com/golang/go/blob/master/src/net/lookup.go#L235-L236), then attempts each IP in turn until it makes a successful connection, then reuses that connection (if keep-alive is enabled). It does not load balance.

**Closed** 2019-08-30 13:26 UTC
Labels: area/admission-control, kind/bug, priority/important-soon, sig/api-machinery

**Comment by caesarxuchao** [comment] 2020-11-12 21:46
Setting the [MaxConcurrentStreams](https://godoc.org/golang.org/x/net/http2#Server) in the webhook server might force the clients to create new connections when load is high.
