### ISSUE TITLE
unit flake: pkg/client/record

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#23610] opened 2016-03-29 23:06 UTC
pkg/client/record failed, but afaict  didn't give useful output

[http://pr-test.k8s.io/23285/kubernetes-pull-test-unit-integration/19655/](http://pr-test.k8s.io/23285/kubernetes-pull-test-unit-integration/19655/)

ok  	k8s.io/kubernetes/pkg/client/leaderelection	1.110s
FAIL	k8s.io/kubernetes/pkg/client/record	2.569s
ok  	k8s.io/kubernetes/pkg/client/restclient	1.282s

**Comment by Q-Lee** [comment] 2016-03-29 23:46
Ditto here: #23512 

http://pr-test.k8s.io/23512/kubernetes-pull-test-unit-integration/19644/

ok  	k8s.io/kubernetes/pkg/client/leaderelection	1.059s
FAIL	k8s.io/kubernetes/pkg/client/record	2.588s
ok  	k8s.io/kubernetes/pkg/client/restclient	1.251s

**Comment by a-robinson** [comment] 2016-03-30 23:38
And again today:
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-test-go/10329/

Why is there no output from the failed test? @spxtr @krousey, have any idea?

**Comment by spxtr** [comment] 2016-03-30 23:50
There is output, it's in artifacts/blablabla.stdout.

```
WARNING: DATA RACE
Write by goroutine 23:
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:353 +0x1e6
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:366 +0x82
  testing.(*common).Logf-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:351 +0x5f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:216 +0x2a7
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:237 +0x14e

Previous read by main goroutine:
  runtime.convT2E()
      /usr/local/go/src/runtime/iface.go:128 +0x0
  testing.(*T).report()
      /usr/local/go/src/testing/testing.go:538 +0xa18
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:591 +0xbdf
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/pkg/client/record/_test/_testmain.go:70 +0x210

Goroutine 23 (running) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:239 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:217 +0xa5
  k8s.io/kubernetes/pkg/client/record.TestEventf()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:351 +0x3034
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc
```

Looks like the same issue as #23372. @wojtek-t mind taking a look?

**Comment by a-robinson** [comment] 2016-03-31 00:08
Well that's certainly useful to know, thanks!

**Comment by wojtek-t** [comment] 2016-03-31 13:58
Duplicate of #23533 

@spxtr - I'm in US now, so I will not find time to look into it within a week.
Note - that there is comment why it is failing (which is different than #23372 )

**Closed by wojtek-t** 2016-03-31 13:58 UTC
Labels: kind/flake, priority/P1, team/CSI-API Machinery SIG
