### ISSUE TITLE
Kubernetes doesn't clear conntrack entry for TCP

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/kubernetes#104098] opened 2021-08-03 10:18 UTC
#### What happened:
When a Kubernetes node becomes NotReady, kube-proxy can delete conntrack entry for UDP, but can't delete conntrack entry for TCP.

#### What you expected to happen:
kube-proxy can delete conntrack entry for both UDP and TCP.
#### How to reproduce it (as minimally and precisely as possible):
1. Create a Service with TCP/UDP Endpoints.
2. Make one node that one Endpoint is on be NotReady.
3. After Node/Pod becomes NotReady, kube-proxy only delete conntrack entry for UDP, but doesn't delete conntrack entry for TCP.
#### Anything else we need to know?:
1. It is a performance enhancement introduced by  https://github.com/kubernetes/kubernetes/pull/83208, but it is not acceptable for application who use ClusterIP with TCP connection.
When a TCP backend is down(for example, node ungraceful shutdown), application may continue send TCP packets to the dead pod, and no response.
Could you please give suggestion what Kubernetes expect application to handle this kind of TCP connection raining day case?
2. Another option is:
Kubernetes can provide a configuration flag to let user select between performance and TCP stale connection cleanup ability.
#### Environment:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:11Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:53:19Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment] 2021-08-03 13:53
There are several issues duplicate of this

TCP connections need to allow graceful terminations, i.e if the pod is termination, kube-proxy can delete the TCP entries abruptly and should allow the app to terminate the connection, you can read more about this here:
https://github.com/kubernetes/kubernetes/issues/100698#issuecomment-812065536

However, there was a bug in the kernel where a TCP SYN stale entry was blackholing traffic
https://github.com/kubernetes/kubernetes/issues/101607#issuecomment-867774857

**Comment by tonyaw** [comment] 2021-08-04 07:17
Thanks for your info. It looks like a very complex issue. :-)
Followup questions:
1. I only care about the node NotReady case. For that case, can I say after EndpointSliceTerminatingCondition KEP is implemented, Kubernetes can add logic to delete TCP conntrack entries?
2. I didn't get the point of your second comment. Why we care about SYN entry since Kubernetes will delete all TCP related conntrack entries when a pod becomes NotReady?
Thanks in advance!

**Comment by aojea** [comment] 2021-08-04 08:43
> * I didn't get the point of your second comment. Why we care about SYN entry since Kubernetes will delete all TCP related conntrack entries when a pod becomes NotReady?

because those entries will become stale and can blackhole traffic, it is a corner case for TCP when it reuse the source port, the long explanation is the thread


> * I only care about the node NotReady case. For that case, can I say after EndpointSliceTerminatingCondition KEP is implemented, Kubernetes can add logic to delete TCP conntrack entries?

Maybe I didn't understand well your question, if the node is not ready? do you want to delete the conntrack entries on the node that is that notReady?
that node will not receive more traffic, why do you need to delete the conntrack entries there?

**Comment by tonyaw** [comment] 2021-08-04 14:13
My scenario:
client --> conntrack entry --> backend
The node that backend is on becomes NotReady, such as ungraceful shutdown.

I need to delete conntrack entry to let client receive RST so that client can establish a new connection to other backend via iptables.

**Comment by aojea** [comment] 2021-08-04 14:35
> I need to delete conntrack entry to let client receive RST so that client can establish a new connection to other backend via iptables.

???
"to let the client receive the RST" you need to keep the conntrack entry so the TCP connection is not closed, if you remove the conntrack entry any new packet will not be directed to the backend

**Comment by tonyaw** [comment] 2021-08-04 14:52
Let's say there are two backends(be01 and be02), and one clusterIP is in use.
client establishes TCP connection to be01 first by clusterIP. --> node that be01 is on is ungraceful shutdown. --> client doesn't know it, and continues send packets to be01 via clusterIP, and no response.
What I expect is:
Kubernetes can delete related conntrack entry on client kubernetes node --> client receives a RST when it sends packet to clusterIP again. --> client retries to establish connection again via clusterIP. --> The new connection is established to be02 via iptables.

**Comment by aojea** [comment] 2021-08-04 15:11
I see, so the problem is that there is no way today, that kube-proxy on the node with the client, can know be01 is terminating gracefully or it just has disappeared, if it blindly removes the conntrack entry it can break a graceful termination ...  
Maybe when the terminating endpoints feature is ready it can be done, but adding heuristic based on nodes events doesn't sound an option to me ...

Besides that, TCP connections are tricky, specially in environments like Kubernetes with so much NAT involved, so a best practice is to enable TCP keepalives and HTTP2 ping frames or other sort of keepalives on the client ... I've seen this scenario multiple times and not only caused by kube-proxy conntrack rules

**Comment by tonyaw** [comment] 2021-08-05 08:51
Thanks for your support!
Is there any schedule plan for KEP EndpointSliceTerminatingCondition so that you can plan the enhancement to delete TCP conntrack entry?

**Comment by thockin** [comment] 2021-08-05 21:44
Discussed at sig-net today.

We can't simply nuke the conntrack records when an endpoint becomes unready.  That would break traffic draining.

If I understand correctly, you need some sort of protocol-aware indication of a dead peer.  If you are not able to close the TCP session (e.g. node crash) then you need either something that watches TCP and resets connections from the middle after some inactivity or you need something above TCP to act as a heartbeat.

**Comment by thockin** [comment] 2021-08-05 21:45
and BTW, the fact that we do it for UDP is sketchy for the same traffic draining reason.  It's just less commonly needed on UDP.

**Comment by thockin** [comment] 2021-08-05 21:48
So, unless I misunderstand, I think this is a "won't fix" scenario.  @aojea suggested it might be a good doc or blog post, though.

If I don't hear otherwise, I will close this.

**Comment by tonyaw** [comment] 2021-08-06 02:18
@thockin and @aojea, 
So the current decision is:
Even if KEP EndpointSliceTerminatingCondition is implemented, Kubernetes doesn't have plan to delete TCP conntrack entry. Is it right?
KEP EndpointSliceTerminatingCondition plans to add a new Terminating condition.
Can kube-poxy use Terminating condition to know it is a "graceful shutdown" case?

**Comment by aojea** [comment] 2021-08-09 08:49
> If I understand correctly, you need some sort of protocol-aware indication of a dead peer. If you are not able to close the TCP session (e.g. node crash) then you need either something that watches TCP and resets connections from the middle after some inactivity or you need something above TCP to act as a heartbeat.

> Can kube-poxy use Terminating condition to know it is a "graceful shutdown" case?

When a node becomes not ready, , is not a graceful shutdown, bear in mind a TCP session can survive network hiccups, if the node becomes ready and pods available again, the TCP session will be working again.

I really think that for TCP, we should not workaround the application problems using the network, TCP already has all the mechanisms needed for handle these scenarios, and the risk of breaking something is too high.

is not possible enable TCP keepalives in your application?

**Comment by tonyaw** [comment] 2021-08-09 09:48
Yes. Application can handle it, but needs effort since our product is complex.
We expected Kubernetes(infrastructure layer) can handle it. :-)
I got your point from Kubernetes perspective. 
You can close this issue now.
Thanks for your great support! :+1:

**Comment by aojea** [comment] 2021-08-09 10:15
> Yes. Application can handle it, but needs effort since our product is complex.
> We expected Kubernetes(infrastructure layer) can handle it. :-)
> I got your point from Kubernetes perspective.
> You can close this issue now.
> Thanks for your great support!

Thanks for your comprehension 
/close

**Closed** 2021-08-09 10:15 UTC
Labels: kind/bug, sig/network, needs-triage

**Comment by michaeljmarshall** [comment] 2023-04-13 04:21
> > If I understand correctly, you need some sort of protocol-aware indication of a dead peer. If you are not able to close the TCP session (e.g. node crash) then you need either something that watches TCP and resets connections from the middle after some inactivity or you need something above TCP to act as a heartbeat.
> 
> > Can kube-poxy use Terminating condition to know it is a "graceful shutdown" case?
> 
> When a node becomes not ready, , is not a graceful shutdown, bear in mind a TCP session can survive network hiccups, if the node becomes ready and pods available again, the TCP session will be working again.
> 
> I really think that for TCP, we should not workaround the application problems using the network, TCP already has all the mechanisms needed for handle these scenarios, and the risk of breaking something is too high.
> 
> is not possible enable TCP keepalives in your application?

@aojea - this issue was very helpful. I have a follow up question. Are you saying that even when a node is gracefully shutdown, the kube-proxy will not clear the conntrack entries for TCP connections that are proxied via a `NodePort` with an `externalTrafficPolicy` of `cluster`? I am observing behavior that suggests this is the case, but I haven't yet had the chance to get the tcpdump to completely verify it.

I agree that the kube-proxy cannot handle every case, but I would have thought a graceful shutdown of a node could include letting peers know that the connection is going away. For example, other components in the networking stack initiate TCP RST packets to peers. An [AWS NLB will send a TCP RST](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html) packet to any clients that are connected to a target that is no longer passing the health checks:

> If a target becomes unhealthy, the load balancer sends a TCP RST for packets received on the client connections associated with the target, unless the unhealthy target triggers the load balancer to fail open.

In my case, the primary goal is to decrease the mean time to recovery when a node is removed. The application still needs to handle other types of TCP related issues, but an eager way to discover a connection is gone would be very valuable. Thanks!

**Comment by thockin** [comment] 2023-04-13 23:43
> Are you saying that even when a node is gracefully shutdown, the kube-proxy will not clear the conntrack entries for TCP connections that are proxied via a NodePort with an externalTrafficPolicy of cluster?

Can you clarify a bit?  What does it mean for a node to be gracefully shut down?  Do you mean someone ran the equivalent of `kubectl drain`?  Or do you mean someone pressed the ACPI power button telling the OS to reboot?

I think you're asking for the same thing I want, which is a clear signal that the node is going away "soon" so that actions like breaking a TCP session could be done (though I still don't know how to do that from the middle on linux).  https://github.com/kubernetes/kubernetes/issues/115139  https://github.com/kubernetes/autoscaler/issues/5201

**Comment by aojea** [comment] 2023-04-15 23:25
Tim I understand it as traffic sent to another node, and that node eventually goes away.

> An [AWS NLB will send a TCP RST](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html) packet to any clients that are connected to a target that is no longer passing the health checks:

We can't compare kube-proxy with a loadbalancer like that, is not exactly the same, though both have the same behavior, translating a virtual ip to a set the backends, but kube-proxy is much simpler and doesn't have health checks, per example.
In order to detect a node being removed, we need to add additional logic to kube-proxy to watch all nodes or to implement healthchecks. If we decide to implement watchs to all nodes (despite the scalability problem) then we should implement what Tim suggest in previous comment

**Comment by michaeljmarshall** [comment] 2023-04-17 19:54
> Can you clarify a bit? What does it mean for a node to be gracefully shut down? Do you mean someone ran the equivalent of `kubectl drain`? Or do you mean someone pressed the ACPI power button telling the OS to reboot?

The node is being shutdown by AKS/GKE as part of a Kubernetes node upgrade. My understanding is that the cloud provider drains the node and then restarts it. I can get more information, if necessary.

> I think you're asking for the same thing I want, which is a clear signal that the node is going away "soon" so that actions like breaking a TCP session could be done

Yes, this is exactly what I am looking for. If possible, I'd like for peers to be notified when a connection is going away in an effort to decrease the latency associated with shutting down (or restarting) a kubernetes node.

In my specific situation, I have a long lived TCP connection where the client acquires a lock on a server's resource. When the connection is hung in the middle, there is a chance the client will discover the broken connection first and will try to re-acquire the lock. In this case, the server needs to do additional work to determine if the resource is still owned by a live connection. The server will always need to have this logic because the network could break at any point, but it seems like having the k8s node close the connection would decrease the mean time to recovery in certain controlled cases like a kubernetes node upgrade, which would be valuable.

> (though I still don't know how to do that from the middle on linux). #115139 [kubernetes/autoscaler#5201](https://github.com/kubernetes/autoscaler/issues/5201)

I am not sure how to do this either, or if it is even a support part of the protocol. This comment https://github.com/kubernetes/kubernetes/issues/108523#issuecomment-1061940287 indicates that the TCP RST packet is a response, so it cannot be sent eagerly. However, given that we're on a middlebox, it seems like a TCP RST is the only available option.

I guess the primary question is what happens when other network proxies are terminated. Do they close connections or do they let peers independently discover the connection is gone?

> Tim I understand it as traffic sent to another node, and that node eventually goes away.

This is not what I meant. Based on the following diagram, I am asking if, when `K8s Node 1` is going away, the `Kube Proxy` on that same node could terminate the TCP connection so that the client and the server eagerly discover the connection is going away. It seems like this might be what happens when removing the conntrack record, but as far as I can tell, we don't remove that record eagerly.

```mermaid
flowchart LR
    A(Client) <--> B(Load Balancer)
    B <--> C(Node Port)
    C <--> D(Target)
    subgraph 1["K8s Node 1"]
        direction TB
        E(Kube Proxy) -.-> C
        C
    end
    subgraph 2["K8s Node 2"]
        direction TB
        D
    end
```

Interestingly, the problem of closing the TCP connection is trivially solved when using `externalTrafficPolicy: Local` because the `NodePort` and target are, by definition, on the same node. In this case, draining the node of pods also drains the proxied TCP connections.

```mermaid
flowchart LR
    A(Client) <--> B(Load Balancer)
    B <--> C(Node Port)
    C <--> D(Target)
    subgraph 1["K8s Node 1"]
        direction BT
        E(Kube Proxy) -.-> C
        C
        D
    end
```

Also, it's very interesting to me that the `externalTrafficPolicy: ProxyTerminatingEndpoints`, which looks to improve the `Local` policy will likely inherit the same problem of `externalTrafficPolicy: Cluster` for any new connections that get proxied to other endpoints.

> In order to detect a node being removed, we need to add additional logic to kube-proxy to watch all nodes or to implement healthchecks. If we decide to implement watchs to all nodes (despite the scalability problem) then we should implement what Tim suggest in previous comment

Given my above clarification, I don't think there is any need for nodes to watch other nodes. My thought was just that when a node is leaving the cluster, it should terminate the proxied TCP `NodePort` connections because they will no longer serve traffic.

As an alternative note, I also wonder if the termination of proxied connections is out of the scope of Kubernetes and would better belong in the OS's logic.

**Comment by aojea** [comment] 2023-04-17 21:28
Understood, what you are requesting is a behavior of the loadbalancer, not of kube-proxy, the thing is that there is a dance of different objects that has to be coordinated or the result will be unpredictable.
If a node is shutting down, it has to indicate that or start draining nodes allowing a grace period.
Once kube-proxy on that node detects the pods are terminating, it allows existing connections and new connections to work, BUT starts failing the healt check, SO the load balancer MUST not send any new traffic there.
IIUIC the Loadbalancer can use the healtcheck to know the state of the Service and send the RST to the client

**Comment by michaeljmarshall** [comment] 2023-04-17 22:29
> the thing is that there is a dance of different objects that has to be coordinated or the result will be unpredictable.

Makes sense. I have some questions though.

>  Once kube-proxy on that node detects the pods are terminating, it allows existing connections and new connections to work, BUT starts failing the healt check, SO the load balancer MUST not send any new traffic there.

It seems part of the challenge is that the NodePort never stops accepting new connections. If the kube-proxy knows the node is shutting down, could it remove the rules that configure the NodePort and then delete the conntrack records for existing connections? What is the reason the host never stops accepting those connections?

For life cycle events, is part of your concern that it is not predictable when the kube-proxy will receive the event handled by this code? 

https://github.com/kubernetes/kubernetes/blob/7696bcd10c2976ff3bf015a7e0be2ff8bb628d8c/pkg/proxy/iptables/proxier.go#L651-L665

> IIUIC the Loadbalancer can use the healtcheck to know the state of the Service and send the RST to the client

That still leaves the back end target with a hung connection.

I noticed that an [Azure Load Balancer](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset) will send a TCP RST packet to:

> inform your application endpoints that the connection has timed out and is no longer usable

This seems relevant because similar logic could apply here. The `NodePort` connection is no longer usable, and eagerly sending the RST lets peers know.

**Comment by thockin** [comment] 2023-04-21 23:26
>> Can you clarify a bit? What does it mean for a node to be gracefully shut down?
>
> The node is being shutdown by AKS/GKE as part of a Kubernetes node upgrade. My understanding is that the cloud provider drains the node and then restarts it.

This is true - but the node itself DOES NOT KNOW it is being drained.  Nothing in the API says it is being drained.  We know it is unschedulable (cordon'ed) and (over time) the pods are being removed, but there is not a single "hey guys, I am draining over here!" field.  :(

> However, given that we're on a middlebox, it seems like a TCP RST is the only available option.

If there's a good way to do it, I am open to figuring out when to use that.  My past experiments here did not turn up a good answer (but were somewhat a sloppily executed, I admit).

> Based on the following diagram, I am asking if, when K8s Node 1 is going away

This is what we are trying to enable sane drain semantics for (@alexanderConstantinescu) but don't have a good indicator yet.  @bobbypage @smarterclayton @x13n

> Given my above clarification, I don't think there is any need for nodes to watch other nodes. My thought was just that when a node is leaving the cluster, it should terminate the proxied TCP NodePort connections because they will no longer serve traffic.

That requires:
1) That the node knows when to do this
2) That the node has a mechanism to do this

Neither are true.

> It seems part of the challenge is that the NodePort never stops accepting new connections. If the kube-proxy knows the node is shutting down, could it remove the rules that configure the NodePort and then delete the conntrack records for existing connections? What is the reason the host never stops accepting those connections?

When do we do that?  When the node gets cordoned (unschedulable=true)?  It could be quite a long time after that before it actually goes away.  In fact it might NOT go away (see Cluster Autoscaler).  It turns out, so people use unschedulable as a coarse form of flow control, which  means we would wreak havoc with their services.  Even if we did use that signal - we want to do this gracefully - upstream LBs have not been updated yet, so if we immediately stop answering, we'll serve needless errors.  And that STILL doesn't solve the problem of running connections.  We want those to run as long as possible before we kill them, in case they finish.

So let me be clear - I agree with you.  I just don't know when to take action (node is draining) or what action to take (clearing conntrack didn't work when I tested it - the kernel was able to reassemble it enough to carry on!!) 

I am hoping the latter is just me being dumb and that the node/autoscaler teams can give us a clear answer on the first.  There have been several conversations, but it seems that what we want here is net-new.

**Comment by michaeljmarshall** [comment] 2023-04-22 05:52
Thank you for your detailed response @thockin! I completely agree that there are several timing problems with the question of "when" to kill connections. Also, I didn't realize node shutdown was such an open problem, that's very intriguing.

> 2. That the node has a mechanism to do this

I spent some time researching this point tonight, and I am now mostly convinced this is impossible given the current tools. I have been assuming that because cloud provider layer 4 load balancers can initiate TCP RST packets then the `NodePort`, which is just a layer 4 load balancer, can too. However, this assumption is likely incorrect.

I tried to trigger the `NodePort` host to send RST packets to client/server using `conntrack -D`. I monitored packets using `tcpdump`. I could see that the conntrack entry was removed, but I didn't see any eager RST packets sent. I just saw the connection eventually send reset packets in response to the client/server TCP keepalive packet. I then decided to switch tools. I tested with `tcpkill`, which led me to this blog https://hechao.li/2019/10/14/Tcpkill-for-IPv6/ that says:

> The way tcpkill works is essentially a [TCP reset attack](https://en.wikipedia.org/wiki/TCP_reset_attack).

> tcpkill uses libpcap to capture packets on an interface and then for each received TCP packet, send a TCP packet with RST flag back to the sender using libnet to reset the TCP connection. Because it can get the SEQ and ACK number in the received TCP headers, it does much better than a [blind reset attack](https://tools.ietf.org/html/rfc5961#section-3). As we know, the next SEQ sending to peer should be the last ACK received from the peer.

From these points, I realized that one of the essential differences between a k8s service and a cloud load balancer is likely that the cloud load balancer has some extra logic to track sequence numbers to ensure that it can send valid TCP RST packets. Based on my research, I don't see any indication that conntrack does this, which indicates to me that it is impossible to reset these proxied connections without first receiving a packet from a client and responding that the connection is gone. Given that this is the current state, I don't think there is any thing to improve. I am certainly not an expert in these networking systems, but this explanation seems to account for all of the observations, which seems compelling.

If we are able to confirm my thesis, I think it'd be really interesting and helpful to increase the visibility of this design detail/limitation. While applications are certainly _supposed_ to handle hung connections at the application level, it is quite interesting to see that there is a very expected condition that will create hung connections.

**Comment by thockin** [comment] 2023-04-23 18:49
I think there COULD BE a way to kill TCP from things like eBPF (I have not investigated) so I don't like saying it can't be solved - it just hasn't YET.

If we can spec out the end-of-life signal, so we know WHEN to take this action, then we can consider how aggressively to act.

**Comment by aojea** [comment] 2023-04-23 20:26
> I noticed that an [Azure Load Balancer](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset) will send a TCP RST packet to:

This RST is sent on idle timeout of a connection, the difference is you can set it in the loadbalancer, but you can also set it in your application too, the way I read the docs is not that it detects that the endpoint has left and reacts, it may be using tcp keepalives to detect the endpoint is alive ... is active polling

> I could see that the conntrack entry was removed, but I didn't see any eager RST packets sent. I just saw the connection eventually send reset packets in response to the client/server TCP keepalive packet.

you need to create a new packet to trigger the reset.

or I'm misreading or I think that we are conflating different topics:

- if the node is being deleted, the pod will be garbage collected and kube-proxy will not add any rules on that node, any new traffic there will be rejected
- if there are existing connections, we allow gracefully termination, resetting existing connections will break that

If the desire is, I have a long lived connection and I want to have a fast reaction to network issues, you have to use keepalives in your application, http2 and grpc allows to set them, tcp too (but this logic is more convoluted, long history here https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/)

in kubernetes all the client-go and apiserver http2 and grpc communications uses an idle timeout of 30 seconds, sending ping frames to detect broken connections and react fast to middleware boxes issues
