### ISSUE TITLE
IPv4/IPv6 dual-stack  kube-proxy   Failed to add destination: [fd00::1:c90a]:80, error: file exists

### ISSUE THREAD

**Issue by hanxiaolong891128** [kubernetes/kubernetes#101506] opened 2021-04-27 03:00 UTC
#### What happened:
kubernetes with IPv4/IPv6 have a problem with kube-proxy,

#### ERROR log
[root@k8s-master-1 ~]# service kube-proxy status -l
Redirecting to /bin/systemctl status  -l kube-proxy.service
● kube-proxy.service - Kubernetes Proxy
   Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-04-27 10:21:04 CST; 37min ago
 Main PID: 17653 (kube-proxy)
    Tasks: 12
   Memory: 27.4M
   CGroup: /system.slice/kube-proxy.service
           └─17653 /apps/k8s/bin/kube-proxy --logtostderr=false --v=2 --feature-gates=ServiceTopology=true,EndpointSlice=true,IPv6DualStack=true --masquerade-all=true --proxy-mode=ipvs --ipvs-min-sync-period=5s --ipvs-sync-period=5s --ipvs-scheduler=rr --cluster-cidr=10.80.0.0/12,fd00::/108 --log-dir=/apps/k8s/log --metrics-bind-address=127.0.0.1 --hostname-override=k8s-master-1 --kubeconfig=/apps/k8s/conf/kube-proxy.kubeconfig

Apr 27 10:58:42 k8s-master-1 kube-proxy[17653]: E0427 10:58:42.289330   17653 proxier.go:2014] Failed to delete destination: [fd00:8000::2]:53/TCP/253.0.0.0:53, error: no such file or directory
Apr 27 10:58:42 k8s-master-1 kube-proxy[17653]: E0427 10:58:42.289503   17653 proxier.go:1984] Failed to add destination: [fd00::1:c90a]:80, error: file exists
Apr 27 10:58:42 k8s-master-1 kube-proxy[17653]: E0427 10:58:42.289565   17653 graceful_termination.go:144] Delete rs "[fd00:8000::862d]:80/TCP/253.0.0.0:80" err: Delete destination "253.0.0.0:80" err: no such file or directory

#### Environment:
- Kubernetes version (use `kubectl version`): 1.17.12
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.5.1804 (Core) 
- Kernel (e.g. `uname -a`): 4.18.9-1.el7.elrepo.x86_64
- Install tools: kube-proxy
- Network plugin and version (if this is a network-related bug): Calico
- Others:

**Comment by uablrek** [comment] 2021-04-27 12:53
0xfd = 253 makes me supect a ipv6 address is interpreted as ipv4.

But the important here is that K8s v1.17 is not supported and `EndpointSlice=true` is still in alpha in v1.17. I think the problem may be EndpointSlice related. EndpointSlice is beta in v1.19 and is enabled by default and is tested e2e.

Please try to reproduce the problem on K8s v1.19 or later.

Waiting for that the issue remains un-triaged.

/area kube-proxy
/area ipvs

**Comment by uablrek** [comment] 2021-04-27 12:56
Preferably use K8s v1.21 where also IPv6DualStack is beta. Otherwise a fix is likely rejected since the issue is about an alpha feature.

**Comment by hanxiaolong891128** [comment] 2021-04-29 11:12
> 0xfd = 253 makes me supect a ipv6 address is interpreted as ipv4.
> 
> But the important here is that K8s v1.17 is not supported and `EndpointSlice=true` is still in alpha in v1.17. I think the problem may be EndpointSlice related. EndpointSlice is beta in v1.19 and is enabled by default and is tested e2e.
> 
> Please try to reproduce the problem on K8s v1.19 or later.
> 
> Waiting for that the issue remains un-triaged.
> 
> /area kube-proxy
> /area ipvs

Hi ~ Thanks for your reply! I have remove  `EndpointSlice=true`, and still the same error ……  I still don't understand Why a ipv6 address is interpreted as ipv4!   Can you give me the solve the direction?

**Comment by uablrek** [comment] 2021-04-29 16:05
There have been numerous bugs in that direction that has been weeded out. So this may be one of them.

But even if a bug is found in K8s <v1.21 it will not be fixed since it is a bug in an alpha feature (dual-stack).

So, please upgrade to K8s v1.21. If the problem still exists it it will be analyzed and fixed.

**Comment by uablrek** [comment] 2021-05-07 04:12
@hanxiaolong891128 Have you tested on K8s v1.21.0?

**Comment by hanxiaolong891128** [comment] 2021-05-10 06:12
> @hanxiaolong891128 Have you tested on K8s v1.21.0?

I just finished my vacation，and I'm going to test it this week

**Comment by hanxiaolong891128** [comment] 2021-05-10 09:36
> @hanxiaolong891128 Have you tested on K8s v1.21.0?

I've test id succeed, Thank you very much!  Best wishs for you~

**Comment by uablrek** [comment] 2021-05-10 09:37
Thanks! I close the issue.
/close

**Closed** 2021-05-10 09:37 UTC
Labels: area/ipvs, area/kube-proxy, kind/bug, needs-triage, sig/network

**Comment by pytimer** [comment] 2021-06-19 03:12
@uablrek I use v1.17.2 and run k8s on the only IPv6 environment, i have the same issue. I don't enable `EndpointSlice` feature, how can i fix it if use v1.17.2 ? Thanks.

**Comment by uablrek** [comment] 2021-06-19 05:41
> how can i fix it if use v1.17.2 ?

I don't think you can. Ipv6-only got to beta in v1.18 so in v1.17 ipv6 is still alpha and as such it may have bugs and fixes are not back ported. And besides v1.17 is not maintained. I think you must upgrade. And then I recommend to upgrade to v1.21. I am unsure about upgrade but I think the "version scew" allows you to upgrade 2 minor versions, e.g. v1.17 -> v1.19 -> v1.21. But you have to check that (I don't upgrade normally myself, just new install).
