### ISSUE TITLE
update-bazel ignores vendor/BUILD

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#51075] opened 2017-08-22 03:30 UTC
At this point I don't know if it is a valid file or not?

```
thockin@freakshow2 kubernetes json-iterator /$ rm vendor/BUILD 
thockin@freakshow2 kubernetes json-iterator /$ ./hack/update-bazel.sh 
wrote "BUILD.bazel"
thockin@freakshow2 kubernetes json-iterator /$ ls -l vendor/BUILD
ls: cannot access vendor/BUILD: No such file or directory
thockin@freakshow2 kubernetes json-iterator /$ git co -- vendor/BUILD
thockin@freakshow2 kubernetes json-iterator /$ ./hack/update-bazel.sh 
wrote "BUILD.bazel"
thockin@freakshow2 kubernetes json-iterator /$ ls -l vendor/BUILD
-rw-r----- 1 thockin eng 23888 Aug 21 20:28 vendor/BUILD
```

@ixdy @mikedanese @spxtr

**Comment by dixudx** [comment] 2017-08-22 09:12
@thockin I reproduce it on my env.

* After removing `vendor/BUILD`, `update-bazel.sh` will not create and update `vendor/BUILD`;
* Manually creating an empty file `vendor/BUILD`, `update-bazel.sh` will successfully rewrite and update `vendor/BUILD`;

/cc @ixdy Seems file `vendor/BUILD` will not be created automatically if missing.

**Comment by ixdy** [comment] 2017-08-22 17:53
This is working as intended, or at least as designed.

We only create new `BUILD` files if there are go sources in that directory, and `vendor/` doesn't have any go sources, so `vendor/BUILD` won't be auto-created.

We have a `vendor/BUILD` solely for the `package-srcs` and `all-srcs` rules, but those are only managed in existing `BUILD` files. Without `vendor/BUILD`, we'd have a lot of lines in `$KUBE_ROOT/BUILD.bazel`, which would be painful.

I learned last week that the [godeps instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md) say to remove all of `vendor/`, which mucks with this process a little bit. I added a step in the instructions there to recreate the `vendor/BUILD` file, but maybe `hack/update-bazel.sh` should just be doing that? I'm not super excited about adding special cases there, but `vendor/` is kinda weird, so maybe it's unavoidable.

**Comment by thockin** [comment] 2017-08-23 22:20
the more automatic the better

**Comment by spxtr** [comment] 2017-08-23 22:53
> Without `vendor/BUILD`, we'd have a lot of lines in `$KUBE_ROOT/BUILD.bazel`, which would be painful.

Specifically, this would cause many merge conflicts.

**Comment by ixdy** [comment] 2017-08-23 22:59
I'm a little confused, since this has been the way things have worked since #40777 merged in April, but 4+ people asking me about this in the last week have convinced me that this needs to be more automatic. Sent #51229.

**Closed** 2017-08-25 10:15 UTC
Labels: needs-sig
