### ISSUE TITLE
Panic during TestTaintNodeByCondition integration test

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#63427] opened 2018-05-04 09:23 UTC
[Panic](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61976/pull-kubernetes-integration/9691/) in the `TestTaintNodeByCondition` integration test in an seemingly unrelated PR https://github.com/kubernetes/kubernetes/pull/61976. 

```
panic: runtime error: invalid memory address or nil pointer dereference
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
/usr/local/go/src/runtime/panic.go:502 +0x229
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:133
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/equivalence_cache.go:89 +0xc4
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:512 +0x1de
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:353 +0x19a
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:47 +0x96
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:43 +0x10b
```

@kubernetes/sig-scheduling-bugs

**Comment by resouer** [comment] 2018-05-04 14:54
/assign

Let me take a look at this issue.

**Comment by resouer** [comment] 2018-05-04 15:46
It is known that `nodeInfo` may be nil during testing, and we've partially checked it like:

```go
func addNominatedPods(podPriority int32, meta algorithm.PredicateMetadata,
	nodeInfo *schedulercache.NodeInfo, queue SchedulingQueue) (bool, algorithm.PredicateMetadata,
	*schedulercache.NodeInfo) {
	if queue == nil || nodeInfo == nil || nodeInfo.Node() == nil {
		// This may happen only in tests.
		return false, meta, nodeInfo
	}

...
```

We just need to do the same check for `ecache.RunPredicate(...)`. 

Will send a patch later.

**Comment by ash2k** [comment] 2018-05-08 10:46
Another case in another unrelated PR https://github.com/kubernetes/kubernetes/pull/63522.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63522/pull-kubernetes-integration/10097/

**Comment by k82cn** [comment] 2018-05-08 11:44
@ash2k , thanks for your input, I'd like to see what will happen after #63472 merged :)

**Comment by liggitt** [comment] 2018-05-18 14:16
still seeing this:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1103224]

goroutine 47096 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x361b8e0, 0x71ac100)
	/usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).GetName(...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:133
k8s.io/kubernetes/pkg/scheduler/core.(*EquivalenceCache).RunPredicate(0xc42500cd40, 0x3f62748, 0x3e2aa3f, 0x11, 0xc42f9a2380, 0x523ab40, 0xc4345c8e10, 0x0, 0xc4235e5d50, 0x528e060, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/equivalence_cache.go:76 +0xc4
k8s.io/kubernetes/pkg/scheduler/core.podFitsOnNode(0xc42f9a2380, 0x523ab40, 0xc4345c8e10, 0x0, 0xc4339a3320, 0x528e060, 0xc42436fa40, 0xc42500cd40, 0x527b2c0, 0xc43b40ee70, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:512 +0x1de
k8s.io/kubernetes/pkg/scheduler/core.(*genericScheduler).findNodesThatFit.func1(0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:353 +0x19a
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.Parallelize.func1(0xc4235e5d90, 0xc42cdbad20, 0xc43bb83dc0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:47 +0x96
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.Parallelize
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:43 +0x10b

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64028/pull-kubernetes-integration/12124/

**Comment by liggitt** [comment] 2018-05-18 14:17
@kubernetes/sig-scheduling-test-failures is the failing code live in master or feature gated? is this a release blocker?

**Comment by ravisantoshgudimetla** [comment] 2018-05-18 15:34
- The failing code is live in master(https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/util.go#L157), where as the equivalence cache is still in alpha. 
- While the issue is something needs to be fixed in ecache code which @resouer is working on, this shouldn't be be blocking 1.11 release as we are still planning to graduate ecache to beta and that has not yet happened. 
- I will send a PR disable to test till the promotion happens. While promoting ecache we can re-enable it.

**Comment by misterikkit** [comment] 2018-05-18 20:14
> @kubernetes/sig-scheduling-test-failures is the failing code live in master or feature gated? is this a release blocker?

Equivalence cache implementation is behind a feature gate, and still alpha.

**Closed** 2018-05-19 13:49 UTC
Labels: kind/bug, priority/failing-test, sig/scheduling
