### ISSUE TITLE
Conformance test for DaemonSet RollingUpdate to rigid on timeout

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#71666] opened 2018-12-03 17:30 UTC
When running conformance testing on a cluster with 8 nodes schedulable for jobs, the conformance test for rolling updates on daemon sets fails due to timeout.

Test name: `Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]`

Test code is here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/daemon_set.go#L326-L369
It utilizes a hardcoded timeout limit of 5m.

**What happened**:
The logs seem to indicate nothing wrong other than the time it takes to complete the rolling restart. The rolling restart timeout is hardcoded at 5m which doesn't seem to be enough time for large enough clusters.

**What you expected to happen**:
I would expect the timeout to either be sliding or for the check to be kicking the can; ensuring that the update is proceeding by at least one node every minute or two.

**How to reproduce it (as minimally and precisely as possible)**:
Requires a cluster with at least 8 schedulable nodes; more would make the timeout more certain.

**Anything else we need to know?**:

I was trying to see what k8s was testing itself with and it seems (according to this log) that the test is run against a cluster with 4 schedulable nodes and takes ~3m which would line up with what I'm seeing (8 nodes for ~6m, 1 more than given by the hardcoded deadline)

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-serial/1555/build-log.txt

Seems like there are a few options:
 - use a "kick the can" strategy to ensure the timeout scales
 - use a timeout calculated from the number of schedulable nodes
 - (mitigation) increase the max number of down nodes so the update can occur faster

**Environment**:
- Kubernetes version (use `kubectl version`):
From test logs (cluster no longer available):
```
INFO: e2e test version: v1.12.1
INFO: kube-apiserver version: v1.12.2-1+619f4e6f7f010f
```

/sig testing
/kind bug

**Comment by johnSchnake** [comment] 2018-12-03 17:34
If there is agreement on the issue, I'm happy to implement the fix for this. I couldn't find anyone else really complaining about this timeout though so I wanted to be sure to get a sanity check first though.

**Comment by johnSchnake** [comment] 2018-12-03 20:17
@kubernetes/sig-testing Can I get someone to confirm/debunk my analysis above?

**Comment by johnSchnake** [comment] 2018-12-11 17:00
@kubernetes/sig-apps

**Comment by alexbrand** [comment] 2019-01-08 13:54
I am running into this as well. 

It seems like the image (`gcr.io/kubernetes-e2e-test-images/serve-hostname:1.1`) that is being used in the test takes around 30-40 seconds to be terminated. The test consistently hits the 5 minute timeout on a 10 node cluster, given that rolling all the pods takes longer than 300 seconds.

The `serve-hostname` binary [sleeps for 60 seconds][0] after getting the SIGTERM signal, which I believe would cause the kubelet to force-kill the process after the default 30 second grace period. Not sure why that sleep is there.

[0]: https://github.com/kubernetes/kubernetes/blob/master/test/images/serve-hostname/serve_hostname.go#L111

**Comment by mauilion** [comment] 2019-01-08 23:08
i can repro this in kubeadm-dind with `NUM_NODES=10`
It's a simple timeout issue. The behavior has changed between 1.11 and 1.12
in 1.11 this test takes less than 5 minutes for 10 nodes in 1.12 the test is now failing consistently

**Comment by timothysc** [comment] 2019-01-09 00:12
I don't know if I'm going to have enough bandwidth on this right now to dig into this.  It's likely the shift from controller<>scheduler on daemonsets.  I don't know if/when that landed. 

It seems kind of strange that the test takes that long TBH.

**Comment by alexbrand** [comment] 2019-01-09 00:43
I think the issue is in the `serve-hostname:1.1` test image that we are using, and not necessarily in the controller/scheduler. 

Seems like there was a sleep introduced to the serve-hostname process as part of this PR: https://github.com/kubernetes/kubernetes/pull/54327/files#diff-892c1503f99623821102be79d0505477R104

I am wondering if it was mistakenly left in there. 

If the sleep weren't there, the workload should exit immediately, allowing the rolling upgrade of the daemonset pods to complete within the allocated timeout.

**Comment by alexbrand** [comment] 2019-01-09 14:16
I am working on a PR that removes the sleep from `serve-hostname`. In the same PR, I am planning to bump the image version, and update all references I can find to the `gcr.io/kubernetes-e2e-test-images/serve-hostname` image.

**Comment by johnSchnake** [comment] 2019-01-09 15:08
Thanks for all the eyes looking at this, I appreciate it.  Removing the sleep will obviously speed things up and probably pass in these use cases. It still seems like something should be done so that the timeout scales though; if we have 1k node clusters we'd probably still have a problem, yes?

**Comment by timothysc** [comment] 2019-01-09 15:15
/assign @thockin @ixdy @spiffxp 

We're going to need an image push update for conformance regression.

WRT timeout scaling... yes, but let's base it on some data and experiments.

**Comment by thockin** [comment] 2019-01-10 01:48
The sleep in there was added over a year ago.  What changed RECENTLY?

Curiously there is a serve-hostname v1.4 tagged on k8s.gcr.io already, but I can;t say where it came from, since VERSION in k/k/test/images/serve-hostname says 1.2 ...

That sleep was added to test graceful termination, I think.  removing it may have side-effects.  Can we make the test runs set `terminationGracePeriodSeconds: 2` ?  Or maybe we make this termination-sleep a flag?

If we change it at all, we should bump the version to 1.5 and supercede all others.

**Comment by alexbrand** [comment] 2019-01-10 13:59
Thanks @thockin!

> The sleep in there was added over a year ago. What changed RECENTLY?

The most recent, related change I could happened 6 months ago: https://github.com/kubernetes/kubernetes/commit/a599697b873ebf4f11d0cba11da29ac4bc04ab32 (PR #66741). With this change, the conformance test started using the 1.1 version of the image, which includes the sleep.

> That sleep was added to test graceful termination, I think. removing it may have side-effects.

I think it'd be great to know if and how this sleep is being used in tests. @freehan also suggested (in #72738) using a flag to control the sleep behavior, so perhaps @freehan has more details about how the sleep is used.

With that said, it seems like we could address the immediate issue by setting the termination grace period to 1 or 2 seconds in the DaemonSet rolling upgrade test.

@timothysc, @ixdy, et al. - Would love your thoughts on whether this is an acceptable fix.

**Comment by bgrant0607** [comment] 2019-01-18 18:31
cc @BenTheElder @janetkuo

**Comment by bgrant0607** [comment] 2019-01-18 18:32
cc @kubernetes/cncf-conformance-wg

**Comment by BenTheElder** [comment] 2019-01-18 22:18
- Agree this needs fixing
- Will defer to DaemonSet owners on correct route to fix, but I like @thockin's suggestion. Perhaps we can just use a smaller sleep..
- I see in the linked PR that we're bumping to 1.3 despite the mystery 1.4 image, we should bump to 1.5 per @thockin's other point

**Comment by janetkuo** [comment] 2019-02-20 21:32
What images we use for this test shouldn't matter, as we only care about whether the images is updated. So if serve-hostname is causing us problem we can just use some other images instead. We could also increase the timeout based on the number of nodes for DaemonSet rolling update test.

**Comment by trevex** [comment] 2019-02-26 08:16
We have 45 nodes and we are unable to get this test to pass as well due to timeouts. Changing the image might help, but maybe adjusting the timeout based on node count is a solution as well.

**Comment by alexbrand** [comment] 2019-02-26 22:01
@trevex totally. @janetkuo suggested that as well and we have added it to the PR #72738

**Closed** 2019-02-27 04:55 UTC
Labels: area/conformance, kind/bug, sig/testing
