### ISSUE TITLE
Empty user and cluster in context created by "kubectl config set-context"

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#7804] opened 2015-05-05 22:04 UTC
I'm following the instructions in examples/kubernetes-namespaces. After I issued the command "cluster/kubectl.sh config set-context dev --namespace=development", I ended up with a context that had empty "cluster" and "user" field, so the following "kubectl get" commands fails as kubectl does not know where to send requests. 

Is this the expected behavior of "kubectl config set-context"? Or shall the newly created context inherit the "cluster" and "user" fields of the current context if these fields are not specified in the command?

**Comment by mbforbes** [comment] 2015-05-06 00:56
+cc @jlowdermilk might be able to give a bit more info (if this isn't resolved by #7820?)

**Comment by jlowdermilk** [comment] 2015-05-06 01:01
That is intended behavior of set-context. It only writes the fields that you explicitly tell it to, so that you can change just one field on an existing context without altering/erasing others.

**Comment by mbforbes** [comment] 2015-05-06 01:03
@jlowdermilk if you don't want to erase others, wouldn't that it doesn't inherit cluster/user be erasing them?

**Comment by caesarxuchao** [comment] 2015-05-06 01:04
@jlowdermilk, to clarify, if I run "cluster/kubectl.sh config set-context dev --namespace=development", then shall the "cluster" and "user" field be empty or inherit the current context?

**Comment by jlowdermilk** [comment] 2015-05-06 01:08
They should be empty. However, it would be reasonable to change the default behavior to "inherit cluster/user from current context" if we are creating a new context. @deads2k, thoughts?

**Comment by jlowdermilk** [comment] 2015-05-06 01:10
@mbforbes, the reason they are empty is because he created a new context. If he had issued the same command and the 'dev' context already had a cluster/user entry, it would only overwrite the namespace.

**Comment by deads2k** [comment] 2015-05-06 12:14
If we were to change this, I'm assuming we would we take similar behavior to all of the `kubectl config set*` commands?  I can certainly see benefits to having a flag that allows it to go either way, but I think I'd probably have the default of the `--inherit`(?) flag be `false` so that the verb `set` remains more accurate.  Inheriting values feels more like, `clone` with tweaks.

**Comment by zjj2wry** [comment] 2017-09-12 09:55
relative with #38053
user want use current-context config, and just update namespace. i think this flag should be added.

**Closed** 2018-03-11 11:59 UTC
Labels: area/kubectl, lifecycle/rotten, priority/backlog, sig/cli
