### ISSUE TITLE
e2e flaky: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42686] opened 2017-03-07 23:06 UTC
The test is very flaky lately and sample failure:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/753

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:70
Expected error:
    <*errors.errorString | 0xc420fda550>: {
        s: "Error while waiting for replication controller kubernetes-dashboard pods to be running: Timeout while waiting for pods with labels \"k8s-app=kubernetes-dashboard\" to be running",
    }
    Error while waiting for replication controller kubernetes-dashboard pods to be running: Timeout while waiting for pods with labels "k8s-app=kubernetes-dashboard" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:68
```

cc/ @kubernetes/sig-scheduling-bugs  @piosz, Could you help triage the flakiness?

**Comment by k82cn** [comment] 2017-03-08 01:41
@dchen1107 , I'm working on that at #32531 .

**Comment by k82cn** [comment] 2017-03-08 13:11
According to the log, the eviction was triggered by rescheduler and the pod wad deleted; but scheduler still can not find enough cpu resources for the dashboard pod. No clue for now :(.

**Comment by piosz** [comment] 2017-03-10 17:30
@k82cn this because another pod was scheduled into this spot. This is because rescheduler still uses old version of taints/tolerations. I'll fix this soon. Thanks for the investigation and sorry for the confusion.

**Comment by k82cn** [comment] 2017-03-12 01:58
@piosz , my pleasure :). Added comments on  kubernetes/contrib#2382 .

**Comment by marun** [comment] 2017-03-13 18:11
@piosz What's the status of the fix for this?

**Comment by aveshagarwal** [comment] 2017-03-13 18:13
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/32531 I think we should close one of these.

**Comment by marun** [comment] 2017-03-13 22:25
Closing in favor of #32531 since that one will will re-opened by the bot anyway.

/close

**Comment by ethernetdan** [comment] 2017-03-14 02:16
closing in favor of #32531

**Closed by ethernetdan** 2017-03-14 02:16 UTC
Labels: kind/flake, priority/critical-urgent, sig/scheduling
