### ISSUE TITLE
Kubeadm generates certificates for one year only.

### ISSUE THREAD

**Issue by Lionelpang** [kubernetes/kubernetes#68924] opened 2018-09-21 07:08 UTC
Hi，
The certificate generated by kubeadm is one year. Indeed, it has been written for one year from the source code. If the deadline is up to configmap and secr, all services need to be rebuilt. How do you solve this problem?

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shubheksha** [comment] 2018-09-21 10:38
/sig auth
/triage support
@Lionelpang, you might want to try asking in the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed.

**Comment by neolit123** [comment] 2018-10-26 14:34
in 1.13 kubeadm will support the command `kubeadm certs renew` (still a subject to change). the command is currently under `kubeadm alpha phase certs renew`. this command can be used for certificate rotation and that will update your certificates.

an kubeadm upgrade itself will also do that.

duplicate of:
https://github.com/kubernetes/kubeadm/issues/708

/close

**Closed by neolit123** 2018-10-26 14:34 UTC
Labels: area/kubeadm, sig/cluster-lifecycle, triage/support
