### ISSUE TITLE
kubeadm cleanup kubelet mounted paths on umount failure

### ISSUE THREAD

**Issue by mowangdk** [kubernetes/kubernetes#120376] opened 2023-09-02 10:02 UTC
### What happened?

kubeadm cleanup kubelet mounted paths on umount failure

logs:
```
[preflight] Running pre-flight checks
[reset] No etcd config found. Assuming external etcd
[reset] Please, manually reset etcd to prevent further issues
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[removeetcdmember.go:80] [reset] No kubeadm config, using etcd pod spec to get data directory
[unmount_linux.go:48] [reset] Failed to unmount mounted directory in /var/lib/kubelet/: /var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~csi/{pv-name}/mount
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]
```

When unmount fails, the cleanup program STILL cleans up the kubelet root directory.

### What did you expect to happen?

When unmount fails, the cleanup program SKIP cleans up the kubelet root directory.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a mounted directory, and keep writing data to the host's directory in one terminal.

```
dd if=/dev/urandom of=/var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~csi/{pv-name}/mount bs=1k count=10000000
```
2. Use ```kubeadm reset -f``` to remove node from k8s cluster in another terminal
3. The cleanup program cleans up the kubelet root directory. includes data in mountpoints(Persistent data)

### Kubernetes version

<details>

```console
$ kubectl version
# 1.26
```

</details>

### Cloud provider

<details>
Impact on all cloud providers
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment] 2023-09-02 15:43
duplicate of
https://github.com/kubernetes/kubeadm/issues/2923

please comment on that issue and add `fixes ...` in your PR.


/close

**Closed by neolit123** 2023-09-02 15:43 UTC
Labels: kind/bug, sig/cluster-lifecycle, needs-triage
