### ISSUE TITLE
tests: Delete Grace Period should be submitted and removed fails on Windows containerd

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#84610] opened 2019-10-31 17:12 UTC
**Which jobs are failing**:

containerd-l2bridge-windows-master
containerd-overlay-windows-master

**Which test(s) are failing**:

[k8s.io] [sig-node] Pods Extended [k8s.io] Delete Grace Period should be submitted and removed [Conformance]

**Since when has it been failing**:

Unknown

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#containerd-l2bridge-windows-master
https://testgrid.k8s.io/sig-windows#containerd-overlay-windows-master

**Reason for failure**:

The test fails with the following logs:

    STEP: verifying the kubelet observed the termination notice
    Oct 31 11:04:21.751: FAIL: kubelet never observed the termination notice
    Unexpected error:
        <*errors.errorString | 0xc0000b7080>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

**Anything else we need to know**:

/sig windows
/sig testing

**Comment by PatrickLang** [comment] 2019-10-31 22:19
Failing test code:
https://github.com/kubernetes/kubernetes/blob/5823cfce76780efe5897429ea59ca55f268a3123/test/e2e/node/pods.go#L141

**Comment by jterry75** [comment] 2019-10-31 23:02
@PatrickLang - Can you try to tell me what CRI calls this test amounts to? We can absolutely terminate a sandbox within 30 seconds :). So something must be different then how crictl issues a stop?

**Comment by adelina-t** [comment] 2019-11-01 12:11
@jterry75 To gracefully delete the pod, the test issues this API call: https://github.com/kubernetes/kubernetes/blob/5823cfce76780efe5897429ea59ca55f268a3123/test/e2e/node/pods.go#L123-L132

I'm looking further into exactly how this is eventually handled by kubelet.

**Comment by jterry75** [comment] 2019-11-01 18:13
@adelina-t - But do you know what CRI calls this is? IE: this is the REST call but I want to see understand what actually hits cri/containerd. Our test with crictl to the daemon specifically can stop these containers well within this limit. So I am trying to understand what is taking all the time.

**Comment by adelina-t** [comment] 2019-11-01 18:38
@jterry75 That's what I said, this is how the tests calls the delete, I'm now looking into what exactly it's doing until it reaches the CRI, because I strongly suspect it's not the normal delete path.

**Comment by adelina-t** [comment] 2019-11-01 21:43
@jterry75 : So the CRI call is StopContainer as it should be expected. 

But I believe I have a better understanding of what is going on. So deleteGracePeriod should be the time we should wait for the task to stop ( with SIGTERM ) before sending SIGKILL and killing it ( https://github.com/jterry75/cri/blob/windows_port/pkg/server/container_stop.go#L153 ). With that in mind, I've did the following:

Increased the gracePeriod in the test. Surprisingly, that didn't solve the problem and in the containerd logs I can see that it tried to stop it  with signal terminated and gracePeriod seconds later, it killed it.

Ok, so after, I reproduced manually with the same image the test uses ( e2eteam/nginx:1.14-alpine ) and, this time, unsurprisingly, we see the same behaviour.

I also ran with a vanilla image:

`kubectl run --generator=run-pod/v1 --image mcr.microsoft.com/windows/servercore:1809 test -- ping -t 127.0.0.1`

and the pod deletes withing 7 seconds without a problem.

So there is clearly a problem why killing the task for that specific nginx test image, Dockerfile here: https://github.com/kubernetes-sigs/windows-testing/blob/master/images/nginx/Dockerfile

( I also ran the same manual test with busybox, the image on which nginx is based on, it has no problem deleting )

**Comment by jterry75** [comment] 2019-11-01 22:01
Thanks @adelina-t! Can you help me with where this image is published so I can do a manual test against cri via crictl with some verbose logging? I should be able to figure out why its not coming down easily.

**Comment by adelina-t** [comment] 2019-11-01 22:03
@jterry75 The image is on dockerhub : e2eteam/nginx:1.14-alpine .

**Comment by jterry75** [comment] 2019-11-08 20:35
@adelina-t - This cant be right? `alpine`? What is the Windows process container image?

**Comment by PatrickLang** [comment] 2019-11-11 17:26
@jterry75 the tagging needs to follow the same naming as on Linux. It's not very intuitive. Windows images are substituted by changing the registry name, not the image name. This is documented here https://github.com/kubernetes-sigs/windows-testing/

So @adelina-t - can we proceed with moving off the nginx image? I think we should move this to an image that's better supported on all OS + architectures. If there's still ambiguity on whether or not terminateGracePeriod works as intended, we can add the needed handler to agnhost and add Windows cases that will let agnhost terminate after CTRL_SHUTDOWN plus some time so that we can test:

- clean termination after SIGTERM/CTRL_SHUTDOWN with no delay
- clean termination after SIGTERM/CTRL_SHUTDOWN with some delay less than terminationGracePeriod
- terminationGracePeriod reached with SIGKILL sent

**Comment by adelina-t** [comment] 2019-11-11 19:03
@PatrickLang yeah, I already have this PR for this: https://github.com/kubernetes/kubernetes/pull/84788

**Comment by alenkacz** [comment] 2019-11-25 09:37
@adelina-t will that PR get merged any time soon? I assume it's a test problem not a bug, correct?

**Comment by spiffxp** [comment] 2019-12-20 17:29
/close
This is no longer continuously failing in the linked testgrids.  Using https://github.com/kubernetes/kubernetes/issues/85762 to track the test's flakiness

**Closed by spiffxp** 2019-12-20 17:29 UTC
Labels: kind/failing-test, sig/testing, sig/windows
