### ISSUE TITLE
K8S openapi spec mark ContainerImage.name as required

### ISSUE THREAD

**Issue by pzheng1025** [kubernetes/kubernetes#100802] opened 2021-04-04 06:09 UTC
#### What happened:
`ContainerImage` is defined as
```
type ContainerImage struct {
	// Names by which this image is known.
	// e.g. ["k8s.gcr.io/hyperkube:v1.0.7", "dockerhub.io/google_containers/hyperkube:v1.0.7"]
	Names []string `json:"names" protobuf:"bytes,1,rep,name=names"`
	// The size of the image in bytes.
	// +optional
	SizeBytes int64 `json:"sizeBytes,omitempty" protobuf:"varint,2,opt,name=sizeBytes"`
}
```
For `Names []string`, both `[]` and `nil` are valid and they will be serialized to `[]` and `null` in Json respectively.  
However in openapi-spec/swagger.json, `ContainerImage.names` is marked as required so `null` is not allowed.
```
    "io.k8s.api.core.v1.ContainerImage": {
      "description": "Describe a container image",
      "properties": {
        "names": {
          "description": "Names by which this image is known. e.g. [\"k8s.gcr.io/hyperkube:v1.0.7\", \"dockerhub.io/google_containers/hyperkube:v1.0.7\"]",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "sizeBytes": {
          "description": "The size of the image in bytes.",
          "format": "int64",
          "type": "integer"
        }
      },
      "required": [
        "names"
      ],
      "type": "object"
    },
```
This cause a mismatch when doing deserialization based on openapi spec. 

#### What you expected to happen:
`names` should not be marked as required because `null` is a valid value. 
#### Environment:
- Kubernetes version (use `kubectl version`): v1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pzheng1025** [comment] 2021-04-18 02:03
Hello, is there any update for this issue?

**Comment by olix0r** [comment] 2021-05-18 21:23
Possibly related to https://github.com/kubernetes/kubernetes/pull/79018 and https://github.com/containerd/containerd/issues/4771

This bug can prevent a controller we're working on from enumerating nodes in a cluster, as we hit deserialization errors if any node in the cluster exposes an image with `names: null`. It seems like #79018 proposed to address this by using the image ID instead of its name.

I imagine that making this field optional would require a KEP, as it's an API change; but perhaps this could be fixed by ensuring that the `names` field is always initialized (i.e. to an empty list) to prevent deserialization errors? This would not require an API change and would make the implementation conform with the API spec.

**Comment by olix0r** [comment] 2021-05-18 23:02
Looking at the sources, it looks like the image list is constructed here: 

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/nodestatus/setters.go#L465-L479

It's not clear to me how it's even possible for `Names` to be uninitialized? I'll try to figure out how we got into this state...

**Comment by olix0r** [comment] 2021-05-19 02:42
I was just able to trigger this with `k3d` though I imagine this can be caused with other environments with a similar workflow:

```
:; kubectl get node -o json
...
                    {
                        "names": null,
                        "sizeBytes": 32579605
                    },
                    {
                        "names": [
                            "myapp:v0"
                        ],
                        "sizeBytes": 32579557
                    }
```

To get into this state, I first built my app with `docker build . -t myapp:v0` and then imported it into the local k3d cluster with `k3d image import myapp:v0`.

Then, I made some changes to my application and built it again with the same tag, and imported into the cluster with the same command. I believe that the `null` instance represents the first version of the application image and the named instance refers to the second build on the same tag.

```
:; kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.2+k3s1
```
```
:; k3d version
k3d version v4.1.1
k3s version v1.20.2-k3s1 (default)
```

**Comment by roycaihw** [comment] 2021-05-19 21:32
Sorry for the late reply.

https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-843622746 @olix0r That's interesting. I agree with you it seems impossible for `Names` to be nil. I wonder if there is a bug in [autoConvert_core_ContainerImage_To_v1_ContainerImage](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/zz_generated.conversion.go#L2938-L2942) that converts an internal-typed object with `Names: []string{}` into a v1-typed object with `Names: nil`. Looking

**Comment by roycaihw** [comment] 2021-05-19 22:09
I can reproduce it by changing [the code](https://github.com/kubernetes/kubernetes/blob/43c39ea7dabf1264c771e307b0769586465cabaa/pkg/kubelet/nodestatus/setters.go#L467-L468) to `names := []string{}`. Either I missed something basic or there is a bug in the conversion & serialization pipeline.

**Comment by roycaihw** [comment] 2021-05-19 23:20
I think I understand what happened:

If an image has neither `RepoDigests` nor `RepoTags`, kubelet sets `ContainerImage.Names` to `[]`. However, when the `v1.Node` object gets persisted to etcd in protobuf, the data is stored as `null`-- protobuff doesn't distinguish `null` and `[]`: https://github.com/kubernetes/kubernetes/pull/45294. Although we ask JSON API clients to tolerate `null` values for such fields, openapi-generated clients (e.g. the [Python client](https://github.com/kubernetes-client/python/issues/895)) treat `null` as an invalid value for a required field during deserialization. 

It's hard to tell what the right fix is: 
1. fundamentally it's a data lost in kube-apiserver serialization/deserialization IMO, but it may be hard to fix, since https://github.com/kubernetes/kubernetes/pull/45294 was the rollback of an attempt to fix
2. marking the `Names` field as optional is an option, but it needs to be approved by someone from SIG Node (and for other APIs that may have similar issue, it would depend on the implementation details of each API). On the plus side, there seems to be no server-side validation that requires `Names` to be not `null`. kubelet is the only writer of the field, and the fact is sometimes the field is written as `null`
3. making the JSON API client tolerate `null` value (as suggested by https://github.com/kubernetes/kubernetes/pull/45294) is an option, but it has to be done in a client-by-client basis. For https://github.com/kubernetes-client/python/issues/895, I think we can maintain a patch in the Python client to fix this. @pzheng1025 I'm not sure what client you're using though

**Comment by olix0r** [comment] 2021-05-19 23:45
I'm not familiar enough with the internals of etc protobuf serialization to know whether this feasible in this context, but in other applications I've used wrapper messages to avoid this ambiguity. For example:

```protobuf
   Names names = 1;
   message Names { repeated string names = 1; }
```

This lets the value-ness of the names field be encoded distinctly from the list itself.

**Comment by olix0r** [comment] 2021-05-19 23:53
Another instance of this issue discussed here https://github.com/kubernetes/kubernetes/issues/93606

**Comment by roycaihw** [comment] 2021-05-19 23:53
Kubernetes python client fix is tracked in https://github.com/kubernetes-client/python/issues/895#issuecomment-844567240. 

https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844561253 contains some API change suggestions for SIG node to consider, which could benefit JSON API clients:
> 1). marking the `Names` field as optional is an option
> 2). Please note that this could also be fixed if the node API takes a different approach when an image has neither RepoDigests nor RepoTags, e.g. ...

/unassign
/remove-sig api-machinery
/remove-triage accepted

let's see if someone from SIG node can pick this up

**Comment by roycaihw** [comment] 2021-05-20 00:01
https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844571579 thanks! But isn't that a breaking change if an old client talks to a new server? 

https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844574338 ah awesome! Probably we should just send a PR to SIG node to mark the field as optional

/help

**Comment by roycaihw** [comment] 2021-05-20 00:03
/assign

actually let me open one real quick

**Comment by olix0r** [comment] 2021-05-20 00:11
> [#100802 (comment)](https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844571579) thanks! But isn't that a breaking change if an old client talks to a new server?

As I said, I'm not really clear on where etcd protobuf clients are implemented or how public that API is. Generally, though, it could be done gracefully via a deprecation cycle.

* A new field is introduced and the prior field is considered deprecated;
* Writers write *both* the deprecated field and the new type field;
* The API server continues to read the deprecated field for one major version.
* Once a major version has passed, change the API server to read the new typed field and stop writing the deprecated version...

But this is all way more complicated than marking the field as optional. If it's acceptable to make it optional, that sounds fine to me!

Thanks for your help looking into this @roycaihw!

**Comment by roycaihw** [comment] 2021-05-20 00:20
that makes sense. Our proto definitions and clients are generated from the types.go files, so supporting the deprecation logic in the clients does sound like more work

**Closed** 2021-05-20 20:14 UTC
Labels: help wanted, kind/bug, needs-triage, sig/node

**Comment by pzheng1025** [comment] 2021-05-21 05:15
Thanks for the fix @roycaihw. I am using [Rust k8s-openapi](https://github.com/Arnavion/k8s-openapi).

**Comment by olix0r** [comment] 2021-05-21 05:18
@pzheng1025 it turns out that `k8s-openapi` already has a fix on master (https://github.com/Arnavion/k8s-openapi/commit/0a9d7e4 -- not yet on crates.io) and I've put up a PR to make it usable from kube-rs (https://github.com/clux/kube-rs/pull/531)
