### ISSUE TITLE
Flaky e2e test: Addon update should propagate add-on file changes (Failed 3 times in the last 30 runs. Stability: 90 %)

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#10136] opened 2015-06-19 22:44 UTC
Master tracking issue: #9312 

Error message as follows (pretty uninformative - need to fix that):

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/addon_update.go:321
Expected error:
    <*errors.errorString | 0xc208029760>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred

**Comment by quinton-hoole** [comment] 2015-06-19 22:54
New test introduced 3 days ago in #9493.

**Comment by quinton-hoole** [comment] 2015-06-19 22:55
@marekbiskup will you be able to look into this one?

**Comment by marekbiskup** [comment] 2015-06-22 06:15
I'm taking it now

**Comment by marekbiskup** [comment] 2015-06-22 06:59
@quinton-hoole , how can I find the failed runs of the test?

**Comment by marekbiskup** [comment] 2015-06-22 07:16
The error message is from the wait.Poll function. I'll create another wait.PollMsg that takes an error message to return something more meaningful that "error waiting for the condition".
e.g. "waiting for the condition: `pod is successfully scheduled`" .

**Comment by marekbiskup** [comment] 2015-06-22 10:38
#10171 improves the error messages from this test.

I have no idea where to find logs from the system from a failed execution. So it is not possible to investigate the error without reproducing it.

@quinton-hoole , are there any plans for gathering system logs (not test logs) from a failed execution of a ne2e test?

For now I'll just increase the timeout. Its in #10172.
In the meantime I'll try to reproduce the issue with a lower timeout.

**Comment by quinton-hoole** [comment] 2015-06-22 17:56
@marekbiskup The logs are already being uploaded to Google Cloud Storage.  See the "Google Cloud Storage Upload Report" link in the left menu when you're looking at a failed Jenkins run.

I'm not sure that increasing the timeout is a good idea.  Do you have any data to suggest that it is a good solution?

**Comment by quinton-hoole** [comment] 2015-06-22 23:17
For example, when this test passes, it always takes 32-35 seconds.  I don't think that increasing the timeout to 3 minutes will improve the success rate.  It will only make failures take a lot longer.

**Comment by marekbiskup** [comment] 2015-06-23 14:28
@quinton-hoole , you're right - I found a bug in production code.

It may happen that the addon-update script lists the add-on directory and finds a few files. Then it tries to create these add-ons. But they may disappear before they are used. The script is "robust", so it retries creating the file 100 times with 10 sec delay.

That's why we may have a 20-minute delay in creating an add-on in some cases.

What's worse, if the definition of one add-on is incorrect (and create will fail) - the add-on update script will be blocked for 20 minutes on each invocation.

I'm on a way to fixing it (as soon as I find a good way :)  )

**Comment by marekbiskup** [comment] 2015-06-23 14:41
Ok, my plan is to get rid of the retry loop - maybe retry 3 times with a 1s delay.
If something goes wrong and the objects are not created, they will be created in the next round - after 10 minutes.

I will also go back to 1min timeout in the test.

**Comment by quinton-hoole** [comment] 2015-07-02 00:54
This test is still failing, approximately as often as it always was.

**Comment by quinton-hoole** [comment] 2015-07-02 00:58
My apologies!  I was completely confused. It has not failed since the merge of #10237

**Comment by bprashanth** [comment] 2016-03-01 21:36
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22305/kubernetes-pull-build-test-e2e-gce/31209/?debugUI=CLOUD
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/31209/consoleFull
Looks like we just didn't create an addon service:

```• Failure [321.040 seconds]
Addon update
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:323
  should propagate add-on file changes [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:322

  Expected error:
      <*errors.errorString | 0xc208406ef0>: {
          s: "error waiting for service e2e-tests-addon-update-test-aefkd/addon-test-updated to appear: timed out waiting for the condition",
      }
      error waiting for service e2e-tests-addon-update-test-aefkd/addon-test-updated to appear: timed out waiting for the condition
  not to have occurred
```

**Comment by fejta** [comment] 2016-03-07 05:55
@bprashanth does that close this issue?

**Comment by bprashanth** [comment] 2016-03-07 18:05
I haven't investigated the last failure but it hasn't seemed to have occured since. I don't know who owns addon-update, but it's probably not team/cluster. I *think* this falls under control-plane, so I'll let them decide.

**Comment by fejta** [comment] 2016-03-08 07:22
Please add team/test-infra (or assign back to me) if there is more for our team to do.

**Comment by lavalamp** [comment] 2016-03-14 21:50
@davidopp to delegate

**Comment by davidopp** [comment] 2016-03-15 05:54
Hey @mikedanese how would you like to own addon updater? Currently implemented in https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addon-update.sh
but I assume your cluster deployment work will eventually sweep this up.

**Comment by mikedanese** [comment] 2016-05-16 17:30
This seems not flakey anymore

**Closed by mikedanese** 2016-05-16 17:30 UTC
Labels: kind/flake, priority/P1, team/control-plane
