### ISSUE TITLE
E2E gci-gce-serial kube-dns not coming up 

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#47186] opened 2017-06-08 14:37 UTC
gci-gce-serial has been failing since June 4th.

https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial&width=5

Seens a lot of different test failures that look like kube-system isn't coming up.

A bunch are looping on kube-dns not being ready.

```
I0607 21:11:47.198] Jun  7 21:11:47.198: INFO: The status of Pod kube-dns-2836479273-kr3f4 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0607 21:11:47.199] Jun  7 21:11:47.198: INFO: The status of Pod kube-dns-2836479273-mk7q5 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0607 21:11:47.199] Jun  7 21:11:47.198: INFO: The status of Pod kubernetes-dashboard-1971317102-1475c is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1210?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1208?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1209?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1207?log#log

Am diving into the kubelet logs to try to see what's going on and identify a SIG.

cc @kubernetes/kubernetes-release-managers

**Comment by dchen1107** [comment] 2017-06-08 16:22
cc/ @kubernetes/sig-network-misc @MrHohn @bowei 

Looks like kube-dns start failing again, which is the major cause for the current serial build failures.Thanks!

**Comment by MrHohn** [comment] 2017-06-08 17:54
Quick update: Took a look some of the recent failures. The kube-dns not ready failure are likely caused by the known issue discussed in https://github.com/kubernetes/kubernetes/issues/46651#issuecomment-305933636.

cc @freehan 

Though there are other issues combined, for instance: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1203
```
[k8s.io] DNS horizontal autoscaling [Serial] [Slow] kube-dns-autoscaler should scale kube-dns pods when cluster size changed 3m6s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:97
Expected
    <int>: 0
not to be zero-valued
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:58
```
Indicates nodes were broken by some other serial test ran before this test. I'm still looking into it.

**Comment by bowei** [comment] 2017-06-08 18:12
It looks like to fix #46641 there are a couple of options:
- Change the initialization order of kubelet
- Patch over the issue with ip-masq-agent
- Don't fix (known flaky issue from before)
- More investigation (... other solution?)

@dchen1107 @yujuhong Any preference on what the next steps are? Changing the initialization order seems the most correct to me, but am not certain size of impact.

**Comment by MrHohn** [comment] 2017-06-08 19:08
Seems like the second case I posted above was caused by ([link](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1203/artifacts/bootstrap-e2e-minion-group-lgh5/kubelet.log)):
```
error: failed to run Kubelet: invalid kubeconfig: invalid configuration: [unable to read client-cert /var/run/kubernetes/kubelet-client.crt for default-auth due to open /var/run/kubernetes/kubelet-client.crt: no such file or directory, unable to read client-key /var/run/kubernetes/kubelet-client.key for default-auth due to open /var/run/kubernetes/kubelet-client.key: no such file or directory]
kubelet.service: Main process exited, code=exited, status=1/FAILURE
```

And that was fixed by https://github.com/kubernetes/kubernetes/pull/47083.

**Comment by freehan** [comment] 2017-06-08 19:38
Okay. Here is what I found so far:

This time the cause of kube-dns being not ready is different than last time. This time is due to kube-proxy not able to run `iptables-restore`. Hence there is no default cluster ip 10.0.0.1 for api-server.

There are full of logs like this in kube-proxy.log:
```
proxier.go:1574] Failed to execute iptables-restore: failed to open iptables lock /run/xtables.lock: open /run/xtables.lock: is a directory
```

**Comment by freehan** [comment] 2017-06-08 19:39
I confirm that before rebooting. `/run/xtables.lock` is a file. After reboot, it becomes a directory.

Not sure why.

**Comment by freehan** [comment] 2017-06-08 19:59
Okay. If the file does not exist, mountPath will create a directory. But we do a init container for xtables.lock [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest#L60)

Is there a race between mountPath and init container?

cc @kubernetes/sig-storage-bugs @kubernetes/sig-node-bugs

**Comment by MrHohn** [comment] 2017-06-08 20:52
Seems to be introduced by #46259, which was merged at Jun 5th.

**Comment by MrHohn** [comment] 2017-06-08 20:52
cc @Q-Lee

**Comment by yujuhong** [comment] 2017-06-08 21:11
> Is there a race between mountPath and init container?

Init containers are (unintentionally) not rerun as node restarted: #36485

**Comment by Q-Lee** [comment] 2017-06-08 21:14
We're using a new version of iptables that attempts to lock on "/run/xtables.lock". Here's the summary.

1. iptables fails if the "/run" dir doesn't exist.
1. The "/run" dir doesn't exist on the base image.
1. The lock file is meaningless if it's not on a shared mount (flock).
1. Mounting the file creates a dir if the file doesn't already exist.
1. There exists an approved design to specify the type of a mount, but the implementation isn't in 1.7
Attempting to mount the file creates a dir when the file doesn't exist.
1. The "/run" dir is cleared on boot, because it contains only run state.
1. Sharing the "/run" dir is dangerous, because the same component in 2 containers could confuse their state.

Creating the file in the init container was meant to make mounting "/run" safe. My understanding was that the init container would finish before the mount is created. If this is a race, is it a bug in kubelet, or an error in my own understanding?

**Comment by Q-Lee** [comment] 2017-06-08 21:35
@yujuhong - interesting. I think I agree with others in the thread that the init container should be rerun. To quote bgrant:

>Init containers shouldn't re-execute so long as local storage isn't lost, and reboot won't necessarily (deliberately) cause the pod to be deleted.

In this case, the "/run" directory _is_ lost over the reboot.

--

But I doubt that changing the kubelet to rerun the init containers is an impractical fix at this point in this release. Can we just touch the file during node startup?

**Comment by yujuhong** [comment] 2017-06-08 21:52
> @yujuhong - interesting. I think I agree with others in the thread that the init container should be rerun. To quote bgrant:
> 
> Init containers shouldn't re-execute so long as local storage isn't lost, and reboot won't necessarily (deliberately) cause the pod to be deleted.
> In this case, the "/run" directory is lost over the reboot.

Uh...I don't disagree that init containers should be rerun when pods restarts. It sounds like a unintentional bug in the implementation and probably never worked since the feature was introduced. But I don't think kubelet can/should figure where you write your data in the init containers and whether the data will be lost after reboot... It either always rerun or not. 

> But I doubt that changing the kubelet to rerun the init containers is an impractical fix at this point in this release. 

Changing kubelet's logic would indeed be risky at this point. 

> Can we just touch the file during node startup?

For any node (os distro)?

**Comment by Q-Lee** [comment] 2017-06-08 22:05
My suggestion was gci-centric, that's fair. In retrospect, that was one of the major reasons to put it in an init container in the first place. It's an action that always needs to happen *before* we mount the file.

Alternatively, kube-proxy does very little. I don't think it will pollute /run. We could just mount the entire dir.
My understanding is that a feature is in the works that will let us declare the mount type to be a file, so hopefully this can be dealt with in 1.8.

@thockin @dchen1107

**Comment by dchen1107** [comment] 2017-06-08 22:24
Just read through the entire issue, and agreed with @Q-Lee above. The issue is a regression introduced by new version of gci image, and kubelet itself doesn't have any knowledge and dependency on this particular file: /run/xtables.lock. Any extra logic introducing to Kubelet is pollute the kubelet codebase here.

Suggested workaround for now is touch that file at GCI / COS node startup time, which can be done easily through cloud_init: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/node.yaml

On another hand, we should fix the init container for 1.8.

**Comment by smarterclayton** [comment] 2017-06-08 22:27
Re: init containers, the *intent* was that init containers would be re-run
when your "pod was restarted".   But we have no formal definition of that,
and in the absence of it, I'd probably lean in a future release to
rerunning init containers after reboot (init containers are supposed to run
if zero containers are found running).

**Comment by Q-Lee** [comment] 2017-06-08 22:29
>and kubelet itself doesn't have any knowledge and dependency on this particular file: /run/xtables.lock

@dchen1107 - that's doesn't sound entirely correct. The kubelet and kube-proxy both use iptables in the same netns. If the kubelet isn't locking, then it probably should.

>Suggested workaround for now is touch that file at GCI / COS node startup time, which can be done easily through cloud_init: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/node.yaml

This works fine for gci, but where else is kube-proxy used?

**Comment by yujuhong** [comment] 2017-06-08 22:31
> Re: init containers, the *intent* was that init containers would be re-run
> when your "pod was restarted".   But we have no formal definition of that,
> and in the absence of it, I'd probably lean in a future release to
> rerunning init containers after reboot (init containers are supposed to run
> if zero containers are found running).

Whenever the podsandbox (infra container) needs to be restarted, kubelet'd kill all the containers associated with it anyway, so I think we could just use that as an indication (i.e., need to create the podsandbox -> run all init containers). That way, we don't have to distinguish node reboots. @smarterclayton WDYT?

**Comment by Q-Lee** [comment] 2017-06-08 22:32
That makes sense to me, and I believe it was the suggested solution in the issue's thread.

**Comment by smarterclayton** [comment] 2017-06-08 22:36
I think that was even in the original implementation, but that was when the
container sync startup code was nightmarish and hard to clearly communicate.

**Comment by Q-Lee** [comment] 2017-06-08 23:19
@dchen1107 I think adding it there is better than putting it in the kubelet. But we'll need to be careful, because it needs to be added by anything that needs kube-proxy, and communicated to anyone whose startup isn't checked into the main repo.

**Comment by dchen1107** [comment] 2017-06-08 23:40
@Q-Lee you convinced me that Kubelet can temporarily carry that workaround. @MrHohn can you send us a pr in Kubelet with a TODO to remove it soon.

Re: https://github.com/kubernetes/kubernetes/issues/47186#issuecomment-307245350 @yujuhong what you proposed above SGTM. But like what @smarterclayton mentioned above, we didn't clearly define what is pod restart at the initial design time. At this moment, I felt it is not safe to take this for 1.7.

**Comment by MrHohn** [comment] 2017-06-09 01:24
Sent #47212.

**Closed** 2017-06-09 23:44 UTC
Labels: approved-for-milestone, kind/bug, priority/critical-urgent, sig/network, sig/node, sig/storage
