### ISSUE TITLE
kube-down does not cleanup GCE external load balancers

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#25503] opened 2016-05-11 21:40 UTC
1. I created a Kubernetes cluster in GCE using kube-up.sh
2. Created and exposed an external load balancer service using

kubectl expose rc netperf-w2 --namespace netperf --port=5201 --target-port=5201     --name=example-service1 --type=LoadBalancer

3. kube-down to wipe out my GCE cluster.

I find the load-balancers are still configured and running. I also find the firewall rules pointing to the load-balancers are also present and not cleaned up.

**Comment by thockin** [comment] 2016-05-12 04:17
As I understand, kube-down does not actually delete objects in the
apiserver, it just nukes the cluster, and as such is bound to miss stuff.
Someone tell me I am wrong, please?

**Comment by girishkalele** [comment] 2016-05-14 21:01
I was hoping it took care of freeing up all GCE resources before I left for the day - I searched for previous issues related to this and I found https://github.com/kubernetes/kubernetes/issues/4411 which references the same issue.

quote
(2) when cluster is shut down by kube-down.sh external load balancer are not removed.
To solve (2), I suggest just to delete all cluster's services in kube-down.sh, before shutting down master and minions. I'm not sure if services should be removed by a special tear-down code is master, because we may want to shut down master and restart it on a different server without changed state of cluster. Such operation should not affect resources.
unquote

**Comment by thockin** [comment] 2016-05-17 07:17
we should do a proper teardown of all namespaces and of all other top-level
objects, if we can.  That's a substantial project.

**Comment by a-robinson** [comment] 2016-05-25 15:24
@thockin - you are very right, kube-down doesn't even try to delete this stuff.

For what it's worth, this was brought up again by a customer today as a concern. It's not a small project, though, as you mention.

**Comment by bgrant0607** [comment] 2016-10-17 23:17
I'm closing this as a dupe of #4630.

**Closed by bgrant0607** 2016-10-17 23:17 UTC
Labels: team/cluster
