### ISSUE TITLE
Kubectl Get jobs with label selector returns blank

### ISSUE THREAD

**Issue by jmccarty3** [kubernetes/kubernetes#31009] opened 2016-08-19 16:52 UTC
**Kubernetes version** (use `kubectl version`):
1.3.4

**What happened**:
Performing a `kubectl get jobs -l <any label selector>` returns no jobs despite their existence.

**What you expected to happen**:
List of jobs matching the label selector

**How to reproduce it** (as minimally and precisely as possible):
Create a job with a label. Call `kubectl get jobs -l <selector>`

**Anything else do we need to know**:
I am not sure if this is similar to #22517 or not

**Comment by AdoHe** [comment] 2016-08-20 15:21
Seems like list jon doesn't respect label selector, will take a deep look.

**Comment by AdoHe** [comment] 2016-08-21 06:39
@jmccarty3 Thanks for reporting this, the root cause here is job label generation problem.

**Comment by AdoHe** [comment] 2016-08-21 06:43
@smarterclayton @lavalamp I dig into this issue, and just found no matter we set `manualSelector` or not, we will not set `job.ObjectMeta.Labels`, this is empty. but label query will just use this value and do the match. I think this is a bug of job label generation, we should fix it, wdyt?

**Comment by pwittrock** [comment] 2016-08-22 20:10
@erictune FYI

**Comment by janetkuo** [comment] 2016-08-26 21:58
I just hit this bug also. We should fix this.

**Comment by kargakis** [comment] 2016-08-28 15:25
cc: @soltysh

**Comment by dshulyak** [comment] 2016-08-30 09:09
On master filtering based on selector works as expected. Does it depend on apiVersion? I am using batch/v1

**Comment by AdoHe** [comment] 2016-08-30 09:50
@dshulyak I am afraid not, please see my old comment.

**Comment by soltysh** [comment] 2016-09-01 15:39
@AdoHe any progress on this one, if not I can start working on this one now that I'm back from PTO.

**Comment by AdoHe** [comment] 2016-09-01 23:37
I think this is already fixed on my local, will open a PR.

**Comment by soltysh** [comment] 2016-09-05 14:47
The issue here is that for some reason the pod labels are also copied over to job labels, not sure why yet, but only when presenting to user. The object stored in etcd does not have them and this is why selection does not return anything. If I create a job with labels I can select using them. So in the end the problem here is that something (not sure which part yet) is duplicating pod's labels on job when doing get.

**Comment by soltysh** [comment] 2016-09-05 15:02
The object returned by apiserver does not have the labels set, so apparently somewhere in `kubectl get` we're adding those labels unnecessarily.

**Comment by AdoHe** [comment] 2016-09-06 02:39
```
The object stored in etcd does not have them and this is why selection does not return anything
```
yes, we don't store in etcd now, so you mean we don't need to store job labels in etcd?

**Comment by soltysh** [comment] 2016-09-06 06:56
I'm saying if you don't set any labels none should be stored. Iow. [this job](https://github.com/kubernetes/kubernetes/blob/master/test/fixtures/doc-yaml/user-guide/job.yaml) does not have any labels set explicitly and that is perfectly valid, the only ones you're seeing are being added to pods running this job. But for some reason when you do get you're seeing the labels copied from pod template and this is what should be fixed.

**Comment by soltysh** [comment] 2016-09-06 08:23
As stated in the PR, I was wrong, apparently we're copying object's labels from pod template since almost forever (#6616) if they are not set. I'll prepare a followup for batch/v2alpha1.

**Closed** 2016-09-11 02:52 UTC
Labels: area/batch, kind/bug, priority/P1, team/ux
