### ISSUE TITLE
[upgrade test failure] Initializers should be invisible to controllers by default

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52584] opened 2017-09-15 23:45 UTC
cc @kubernetes/sig-api-machinery-test-failures 
cc @kubernetes/kubernetes-release-managers 

Observed on the upgrade cluster test suite

**Comment by liggitt** [comment] 2017-09-16 12:59
Dupe of https://github.com/kubernetes/kubernetes/issues/52585

**Closed by liggitt** 2017-09-16 12:59 UTC
Labels: sig/api-machinery
