### ISSUE TITLE
kubernetes-e2e-gke-multizone perma-broken on 6/18/2016

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#27692] opened 2016-06-19 17:06 UTC
The test job was passing consistently until midday on 6/18, e.g.

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-multizone/3736/

Then it started failing consistently, e.g:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-multizone/3737/

... with this error:

12:31:41 ... in gke:detect-node-instance-groups()
12:31:42 ERROR: (gcloud.compute.instance-groups.managed.list-instances) Some requests did not succeed:
12:31:42  - The resource 'projects/k8s-jkns-e2e-gke-multizone/zones/us-central1-f/instanceGroupManagers/gke-jenkins-e2e-default-pool-a48ce2c4-grp' was not found
12:31:42 

Assigning to @fejta and @roberthbailey to triage and assign someone to fix.

**Comment by quinton-hoole** [comment] 2016-06-19 17:07
cc: @a-robinson

**Comment by a-robinson** [comment] 2016-06-19 20:47
Almost certainly caused by #26917. I'm not going to bother rushing in a rollback today since it's not a critical build, but could you fix this up tomorrow @fabioy?

**Comment by fabioy** [comment] 2016-06-20 16:52
Yeah, that's me. The change to support multiple MIGs in a single zone doesn't quite work. Didn't know of this test variation.

Just to confirm, to run this test variation, the additional env vars I should set are (aside from the standard ones):

export KUBERNETES_PROVIDER=gke
export ADDITIONAL_ZONES=us-central1-a,us-central1-b

Any other?

**Comment by roberthbailey** [comment] 2016-06-20 16:55
@lavalamp -- yet another instance of a PR passing all presubmit tests and breaking other jenkins jobs after being merged.

**Comment by fabioy** [comment] 2016-06-20 18:01
@quinton-hoole Can you tell me a bit more how this test is setup? I tried to do a "kube-up.sh" with the additional zones and it worked for me. My settings:

export KUBERNETES_PROVIDER=gke
export ZONE=us-central1-f
export CLOUDSDK_BUCKET=gs://cloud-sdk-testing/ci/staging
export CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER=https://test-container.sandbox.googleapis.com/
export ADDITIONAL_ZONES=us-central1-a,us-central1-b

**Comment by quinton-hoole** [comment] 2016-06-20 18:23
@fabioy Have you read https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#federation-e2e-tests ?

**Comment by quinton-hoole** [comment] 2016-06-20 18:23
Oh, sorry, wrong link.

**Comment by quinton-hoole** [comment] 2016-06-20 21:13
@fabioy Take a look at https://github.com/kubernetes/kubernetes/pull/19578 and let me know if you need any more info.

**Comment by quinton-hoole** [comment] 2016-06-20 21:16
The above PR was the one for GCE.  
The following is the one @a-robinson did for GKE.  There are some relatively minor differences:

https://github.com/kubernetes/kubernetes/pull/24075

**Comment by fabioy** [comment] 2016-06-20 23:20
Hum, I'll have to dig a bit deeper. I tried the exact combination of env vars and my "kube-up" was successful (with the correct number of nodes across the zones). Curious...

**Comment by a-robinson** [comment] 2016-06-21 17:27
Any ETA, @fabioy? I'm getting tired of all the test failure emails :p

**Comment by fabioy** [comment] 2016-06-21 18:02
I think I found the problem. I have a workaround that'll make it work for now. I'm hoping sometime this afternoon.

**Closed** 2016-06-22 17:45 UTC
Labels: kind/flake, priority/P1, team/gke

**Comment by fabioy** [comment] 2016-06-22 20:45
@a-robinson @quinton-hoole The PR merged and gke-multizone Jenkins has gone green. Sorry for the trouble. There's still a larger issue of multi-zone handling in the test runner itself, but I think that's for another day.
