### ISSUE TITLE
Session Affinity ClientIP not working on Container Engine

### ISSUE THREAD

**Issue by bnadim** [kubernetes/kubernetes#20022] opened 2016-01-22 22:03 UTC
Hi,

ClientIP affinity seems to have some issue on Container Engine. Once you scale down a replicas set linked to a service with session affinity and GCE external load balancer, sticky session doesn't work anymore.
I tried to create a new cluster to be sure it wasn't any configuration related issue.

Steps to reproduce : 
 - Create a container cluster
 - Add a replica set (with a pod running http service that show a random id defined on launch) and a service with sessionAffinity set to "ClientIP"  and type "LoadBalancer"
 - scale replicaset to 0. Scale it back to 5.
 - Try to go on the url exposed on computer. Try the same thing on your phone on another network (for example your mobile data).
    The id on the phone change each time your reload the computer page.

Did i miss something ?

Thanks for your help.

**Comment by spiddy** [comment] 2016-03-02 17:56
This seems to be a duplicate of #13299

**Comment by thockin** [comment] 2016-03-02 18:24
Dup of #13299

**Closed by thockin** 2016-03-02 18:24 UTC
Labels: kind/support, team/cluster
