### ISSUE TITLE
kubernetes-e2e-gce-autoscaling: Autoscaling test failure #2469

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#19896] opened 2016-01-21 00:22 UTC
Test failure yesterday in autoscaling.  I don't know of any systematic issues from that time (other builds green), so offering it to autoscaling people to triage if there's anything interesting and close if not.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/2469/

Horizontal pod autoscaling (scale resource: CPU) [Skipped] ReplicationController [Feature:Autoscaling] Should scale from 5 pods to 3 pods and from 3 to 1

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:58 Jan 19 08:03:00.365: timeout waiting 10m0s for pods size to be 3

Autoscaling [Feature:Autoscaling] Should scale cluster size based on memory reservation

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_size_autoscaling.go:104 Expected error: <*errors.errorString | 0xc208516050>: { s: "timeout waiting 20m0s for cluster size to be 4", } timeout waiting 20m0s for cluster size to be 4 not to have occurred

Horizontal pod autoscaling (scale resource: CPU) [Skipped] ReplicationController [Feature:Autoscaling] Should scale from 1 pod to 3 pods and from 3 to 5

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:55 Jan 19 08:35:03.623: timeout waiting 10m0s for pods size to be 3

**Comment by alex-mohr** [comment] 2016-01-21 00:23
@kubernetes/goog-control-plane FYI, autoscaling failure yesterday.  Blocked merge queue for a couple of hours.

**Comment by alex-mohr** [comment] 2016-01-21 17:10
Here's another failed run, also blocking submit queue:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/2492

Given the failure is "Should scale cluster size based on memory utilization" and k8s doesn't actively support cluster auto-provisioning, is that test one we can skip?  And if/when we support auto-provisioning, re-enable?

**Comment by alex-mohr** [comment] 2016-01-21 21:41
And http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/2495

**Comment by zmerlynn** [comment] 2016-01-22 06:10
And
* http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/2496/
* http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/2497/
* http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/2498/
* http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/2499/

This test is no longer even vaguely failing but just outright broken as of 2495.

**Comment by piosz** [comment] 2016-01-22 06:13
This is a clear regression. Reassigning to @mwielgus who is oncall today.

**Comment by piosz** [comment] 2016-01-22 08:09
I'll take a look.

**Comment by piosz** [comment] 2016-01-22 12:29
#19984 fixed the permanently failing suite. I'll take a look into flakes 2469 and 2492. Decreasing priority.

**Comment by piosz** [comment] 2016-01-22 14:45
Suite 2469 is pretty weird for me. The Heapster was crash-looping for almost 1 hour after the creation and then came back to normal. Does anyone (@mwielgus @vishh @kubernetes/goog-node) has any idea what was the cause? Logs from kubelet are [here](https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-autoscaling/2469/artifacts/104.197.228.67%3A22-kubelet.log). 

Suite 2492 failed probably due to _flakiness_ of Google Cloud Autoscaler, which means when GCA is not sure whether to scale down it doesn't just in case. It's a very rare case (this is the second time when it happens during last 6 months).

**Comment by vishh** [comment] 2016-01-23 00:24
Heapster can crash if InfluxDB is unavailable.

**Comment by piosz** [comment] 2016-01-25 11:22
The suite started failing. I'm investigating the problem.

**Comment by piosz** [comment] 2016-01-26 08:48
#20109 fixed the issue - the suite hasn't been flaky for 15+ runs.

**Closed by piosz** 2016-01-26 08:48 UTC
Labels: kind/flake, priority/P1, team/control-plane

**Comment by davidopp** [comment] 2016-01-27 19:32
Awesome -- thanks!
