### ISSUE TITLE
Job should run a job to completion flake

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#15383] opened 2015-10-09 17:14 UTC
Failed 1 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8836/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Job_should_run_a_job_to_completion_when_tasks_sometimes_fail_and_are_locally_restarted/

**Comment by ncdc** [comment] 2015-10-10 15:19
@soltysh

**Comment by quinton-hoole** [comment] 2015-10-12 22:17
Duplicate of #15389

**Closed by quinton-hoole** 2015-10-12 22:17 UTC
Labels: kind/flake, priority/P1, team/control-plane
