### ISSUE TITLE
Possible regression in pod-startup-time

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#42000] opened 2017-02-23 20:18 UTC
In the last 10 runs of kubemark-500, 4-of them failed with "too high pod-startup-time".
We've never had problems with it before.

The failures are:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2777
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2782
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2784
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2785

Should be investigated.

@shyamjvs @gmarek

**Comment by wojtek-t** [comment] 2017-02-23 20:19
@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment] 2017-02-23 21:01
@k8s-oncall - FYI, I will look into it tomorrow (it's something different than the current failure, which hopefully should be fixed by #42003)

**Comment by shyamjvs** [comment] 2017-02-23 21:53
FYI, this happened to me too in the afternoon when I was running my own cluster within the `kubernetes-scale` project. Density test was just taking way too long (even though my cluster was just 3 nodes and 10 hollow-nodes). So I brought down the cluster and ran one in my personal project.

IMO the reason is that there were way too many many machines running in the project at that time (~5000 from gke-large-cluster test and 60 from the usual kubemark-2000 test). So we had 5 MIGs from gke-large (in us-east1-a) and 1 MIG from kubemark-2000 (in us-central1-f). We probably have a limit of 5 MIGs (either per zone or per project, I'm not sure). So maybe either this or we had some network bandwidth shortage?

**Comment by wojtek-t** [comment] 2017-02-24 07:13
kubemark-500 is running in completely different project - it's 100% unrelated.

Regarding kubernetes-scale - we have much higher quotas and it's fine to run both definitely. Additionally, there is isolation between networks. 

It really seems like a regression to me.

**Comment by wojtek-t** [comment] 2017-02-24 13:18
So we did a lot of investigation of it today together with @gmarek and the findings are:
- this is "flakiness" - i.e. some runs are as they were before.
- the first bad run is this one:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2763?log#log

The way how we detect if it is bad run, we are looking into those lines:
```
I0222 10:00:41.620] Feb 22 10:00:41.613: INFO: 10% worst run-after-schedule latencies: ...
I0222 10:00:41.621] Feb 22 10:00:41.613: INFO: perc50: 788.444452ms, perc90: 1.347778773s, perc99: 2.771830267s
```

The 99th percentile here higher than 2s is definitely a bad sign (it generally is below 1s).
There are a lot of such runs after this point.

The fact that this is high clearly suggests that this is regression in kubelet code.
@kubernetes/sig-node-bugs 

The only PR that was merged within previous 5 runs that may look related is this one:
https://github.com/kubernetes/kubernetes/pull/41349

@derekwaynecarr @justinsb @vishh @sjenning ^^

I tried 5 times running kubemark-500 locally with this PR reverted and all 5 runs were good (i.e. didn't face this 99perc higher than 1s).
So I think we should revert this PR.

**Comment by wojtek-t** [comment] 2017-02-24 14:11
Last 2 runs are also pretty bad:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2802/?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2803/?log#log
(though the one before them is pretty good).

**Comment by wojtek-t** [comment] 2017-02-24 14:33
So I have one more observation - it seems that whether the run is good or bad depends on whether we are first running load test or density test (we are running those 2 as part of each test run).

It doesn't change the fact that it's a regression, but maybe this will help with understanding?

**Comment by derekwaynecarr** [comment] 2017-02-24 14:37
I have a pr in flight to ensure a pod cgroup is deleted prior to a pod being deleted.  Right now it's in background which may be causing really broad hierarchies?

**Comment by derekwaynecarr** [comment] 2017-02-24 14:38
Which runs better if first?  Load or density?

**Comment by wojtek-t** [comment] 2017-02-24 14:42
If I'm running density in a loop, I don't see any problems (both with and without your PR).

It seems that something is staying from load test either in hollow-kubelet or holow-kubeproxy. These are not objects per-se, because we are deleting the whole namespaces (and  waiting until they are deleted), but maybe kube-proxy has some backlog work that it is doing? Or sth like that?

**Comment by wojtek-t** [comment] 2017-02-24 14:56
So yeah - running load test just before density makes it reproducible.

We talked with @derekwaynecarr and for now we are going to disable the flag for cgroups. That should solve the regression issue.

In the background, I will be working on making those tests more independent.

**Comment by derekwaynecarr** [comment] 2017-02-24 15:48
@wojtek-t - opened pr

**Comment by sjenning** [comment] 2017-02-24 18:05
@wojtek-t what is the `ginkgo.focus` passed to `test/kubemark/run-e2e-tests.sh` for "load" and "density" tests?

**Comment by timothysc** [comment] 2017-02-24 18:55
@sjenning , poke @mffiedler to blast out a cluster for you ;-) 

You'll likely never see it without a kubemark-500 equiv.

**Comment by ncdc** [comment] 2017-02-24 19:00
Thanks @timothysc :-) we've got one up and running.

**Comment by sjenning** [comment] 2017-02-24 19:25
@wojtek-t just ran kubemark on my own cluster.

`[Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets and 0 daemons` and got:

```
worst schedule latencies
perc50: 9.307743ms, perc90: 13.122051ms, perc99: 24.634236ms
worst run-after-schedule latencies
perc50: 200.033329ms, perc90: 601.934257ms, perc99: 731.414727ms
worst watch latencies
perc50: 1.025306815s, perc90: 1.695499114s, perc99: 2.046010868s
worst scheduled-to-end total latencies
perc50: 1.129049573s, perc90: 1.737352444s, perc99: 2.043592652s
worst e2e total latencies
perc50: 1.138982067s, perc90: 1.744747286s, perc99: 2.056566743s
```

Is 2 seconds e2e normal or high?

**Comment by wojtek-t** [comment] 2017-02-24 19:27
@sjenning - 2s is normal.

Though - see my comment above: https://github.com/kubernetes/kubernetes/issues/42000#issuecomment-282307818
It seems that it's not possible to repro it just by running density. It seems that it is reproducible by first running load.go, and running density after it.

**Comment by sjenning** [comment] 2017-02-24 19:28
@wojtek-t yes, that is what I'm doing next.  Just wondering what a baseline acceptable value was.

**Comment by wojtek-t** [comment] 2017-02-24 19:32
Betweem 2s and 2.5s is normal. The values above 3s suggest regression.

**Comment by wojtek-t** [comment] 2017-02-24 19:33
Ohh - to clarify. This "between 2s and 2.5s being normal" I'm talking about:
"worst e2e total latencies"

**Comment by sjenning** [comment] 2017-02-24 19:59
@wojtek-t so after a load, then another density, I could reproduce

```
worst schedule latencies
perc50: 9.392381ms, perc90: 12.978804ms, perc99: 31.069847ms
worst run-after-schedule latencies
perc50: 751.525304ms, perc90: 1.36334556s, perc99: 2.045595845s
worst watch latencies
perc50: 1.0551617s, perc90: 1.669326098s, perc99: 2.231286216s
worst scheduled-to-end total latencies
perc50: 1.732232327s, perc90: 2.496441259s, perc99: 3.413937383s
worst e2e total latencies
perc50: 1.741176838s, perc90: 2.504717641s, perc99: 3.422459192s
```

perc99 of 3.4s e2e with the very worst being 4.5s

Now to figure out how to get the metrics out of the hollow kubelet.

**Comment by gmarek** [comment] 2017-02-24 20:47
@sjenning - I'm not sure it was clear from what @wojtek-t wrote. Our theory is that it's caused by CPU starvation of hollow nodes.

**Comment by sjenning** [comment] 2017-02-24 21:00
@gmarek ooooooh... no that was not clear.  not to me at least. that changes what i'm looking for.  thanks for clarifying.

**Comment by gmarek** [comment] 2017-02-24 21:07
Load test somehow causes huge CPU usage increase on both hollow-kubelets and hollow-kubeproxies which stays very high (read: 100%) for quite some time.

**Comment by sjenning** [comment] 2017-02-24 21:27
@gmarek @wojtek-t @derekwaynecarr ok i'm finally catching up with everyone else.

Without PR https://github.com/kubernetes/kubernetes/pull/41753, the Burstable QoS level cgroup has `cpu.shares = 1024`.  This means that, under contention with guaranteed pods, *all* of the the burstable pods together (i.e. hollow-nodes) would get the proportionally the same cpu as one guaranteed pod with `cpu: 1024m`.  So CPU starvation could be happening where it wasn't happening before.

HOWEVER, @ncdc and I are looking into a situation where my main cluster nodes are chewing 100% CPU while both the main cluster and kubemark cluster are idle after the kubemark test is over.

```
top - 21:22:11 up  3:54,  2 users,  load average: 102.95, 104.47, 108.35
Tasks: 1151 total,   9 running, 1142 sleeping,   0 stopped,   0 zombie
%Cpu(s): 94.0 us,  5.6 sy,  0.3 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:  30839500 total, 15158632 used, 15680868 free,   555004 buffers
KiB Swap:        0 total,        0 used,        0 free.  3452916 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND         
 1720 root      20   0 2940092 196976  46016 S  33.8  0.6  92:32.99 kubelet         
17196 root      20   0  718424 144548  39892 S  22.6  0.5  14:09.96 kubemark        
20098 root      20   0  528972 182228  39916 S  22.6  0.6  14:02.18 kubemark        
19417 root      20   0  663044 171052  40652 S  22.3  0.6  14:13.43 kubemark        
19795 root      20   0  574196 156776  40700 S  22.0  0.5  14:09.56 kubemark        
19324 root      20   0  699200 157816  40216 S  19.7  0.5  14:05.28 kubemark        
14722 root      20   0  648736 172952  39796 S  19.4  0.6  14:11.93 kubemark        
15225 root      20   0  710852 163300  40196 R  19.4  0.5  14:07.59 kubemark        
21050 root      20   0  717580 159276  40192 S  19.0  0.5  13:58.52 kubemark        
18086 root      20   0  580224 156096  40852 S  18.4  0.5  14:00.11 kubemark        
18928 root      20   0  633344 151272  40264 S  18.4  0.5  14:00.83 kubemark        
10610 root      20   0  677400 192628  40376 S  18.0  0.6  13:59.43 kubemark        
13056 root      20   0  784836 158268  39332 R  18.0  0.5  13:57.14 kubemark        
20527 root      20   0  637180 159680  40076 R  17.7  0.5  14:04.54 kubemark        
17073 root      20   0  567936 156192  40476 S  17.1  0.5  14:00.54 kubemark        
15857 root      20   0  593792 157932  40016 S  16.7  0.5  13:57.08 kubemark        
17770 root      20   0  563196 153116  40440 R  16.7  0.5  14:05.02 kubemark        
19072 root      20   0  644368 156604  40276 S  16.7  0.5  14:13.21 kubemark        
19751 root      20   0  662204 162348  40508 S  16.7  0.5  14:10.16 kubemark        
21147 root      20   0  628756 152296  39828 R  16.7  0.5  14:10.16 kubemark        
16148 root      20   0  576932 166704  40236 R  16.4  0.5  14:03.58 kubemark        
14554 root      20   0  723444 170592  40204 S  16.1  0.6  14:09.89 kubemark        
22356 root      20   0  523912 170952  39884 S  15.7  0.6  14:03.93 kubemark        
15128 root      20   0  644248 157684  40788 S  15.1  0.5  14:09.08 kubemark        
20825 root      20   0  649720 157160  40428 S  15.1  0.5  14:12.02 kubemark        
21803 root      20   0  702768 152988  40392 S  15.1  0.5  14:05.38 kubemark        
18455 root      20   0  719432 162592  40720 S  14.8  0.5  14:00.64 kubemark        
19365 root      20   0  724780 159392  39660 S  14.8  0.5  14:10.65 kubemark        
 8554 root      20   0  589996 170820  40248 S  14.4  0.6  14:06.76 kubemark        
12798 root      20   0  563772 153904  40076 S  14.4  0.5  14:03.53 kubemark        
14603 root      20   0  646892 162208  39424 S  14.4  0.5  13:55.67 kubemark        
15075 root      20   0  782860 163996  39696 S  14.4  0.5  14:08.49 kubemark   
```

**Comment by gmarek** [comment] 2017-02-24 21:31
Yup - this is exactly what we observed. We don't know why it takes so long for components to become idle again though:(

**Comment by ncdc** [comment] 2017-02-24 21:58
It looks like the kubelet is spinning its wheels constantly trying to remount various pod volumes for some reason

**Comment by derekwaynecarr** [comment] 2017-02-24 22:11
so i am ok disabling pod cgroups for now until burstable cpu shares are set as expected, but we need kubemark to stop hot looping.

**Comment by ncdc** [comment] 2017-02-24 22:12
It's not just kubemark. It's the kubelet too

**Comment by ncdc** [comment] 2017-02-24 22:12
Here's a gist of 10 seconds of log data from the kubelet grepping for a single secret: https://gist.github.com/ncdc/8ddb83d5376b472e6bb84bf416a2b3e1

**Comment by ncdc** [comment] 2017-02-24 22:13
This secret is *not* mutating in etcd at all

**Comment by vishh** [comment] 2017-02-24 22:16
> It looks like the kubelet is spinning its wheels constantly trying to remount various pod volumes for some reason

This sounds bad.

**Comment by vishh** [comment] 2017-02-24 22:19
@ncdc https://github.com/kubernetes/kubernetes/pull/42081

**Comment by ncdc** [comment] 2017-02-24 22:20
Thanks @vishh. @sjenning you might try pulling that PR, doing a new build, and creating a new cluster to see if that helps (you'll have to tear down and recreate the cluster).

**Comment by derekwaynecarr** [comment] 2017-02-24 22:27
@vishh -- do we still want to disable pod cgroups until burstable shares for safety reasons?

**Comment by vishh** [comment] 2017-02-24 22:34
I feel it doesn't matter as long as the tests don't flake because of pod
cgroups. QoS cgroups update PR will also land soon and so let's avoid a
revert if we can.

**Comment by dchen1107** [comment] 2017-02-24 22:34
Just saw this issue. FYI: @yujuhong @Random-Liu and I were debugging the issue of the extra startup latency this morning, and we believe the root cause was identified after switching to CRI: #42081

But the fundamental issue is the artificial API QPS limit (default: 5) applying to all clients because unknown API Server's scalability limit / scope. Any changes at the node which generates more requests might cause the regression if we didn't fix the API Server scalability issue.

**Comment by liggitt** [comment] 2017-02-25 02:34
> But the fundamental issue is the artificial API QPS limit (default: 5) applying to all clients because unknown API Server's scalability limit / scope. Any changes at the node which generates more requests might cause the regression if we didn't fix the API Server scalability issue.

that limit is client-side, not server-side... do we know of a specific client that is being broadly shared and hitting the limit? (we should see "Throttling request took ..." messages in logs)

**Comment by Random-Liu** [comment] 2017-02-25 03:18
> that limit is client-side, not server-side... do we know of a specific client that is being broadly shared and hitting the limit? (we should see "Throttling request took ..." messages in logs)

Kubelet only uses one apiserver client. We did see a lot of “Throttling", some even up to 30 seconds.

**Comment by liggitt** [comment] 2017-02-25 05:49
Yeah, the kubelet is defaulting to 5 (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/defaults.go#L354-L357)

Other components have different defaults (scheduler defaults to 50, controller-manager to 20). We can certainly revisit the kubelet default if we need to.

**Comment by gmarek** [comment] 2017-02-25 07:29
We're aware that kubelet API limit is quite low now and that it's the main bottleneck for kubelet throughput right now. And yes, this means that any change in Kubelets requirements for contacting API server will be very visible and have a big impact on our performance tests - every change needs to be multiplied by 5000 which changes even 1 QPS change for kubelet, 5k QPS change for the API server (i.e. it's way easier/safer to double QPS limit for e.g. controller-manager than adding even 1 QPS for kubelet:() - which is exactly why we noticed a need for #42081.

That being said, this was unrelated with this issue. We were running those test in non-CRI mode (i.e. base cluster kubelets were running in non-CRI mode), and IIUC hollow-kubelets are still using Docker fake, not CRI-one (@shyamjvs @Random-Liu). Indeed we saw exactly the same error after #42081 was merged: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2822/build-log.txt

It's unclear to me whether this is a problem only with mocks, or with real things as well. We'd need to run a load test on a real big cluster to check that.

**Comment by Random-Liu** [comment] 2017-02-25 09:07
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2822 hasn't include #42081 yet I believe.

The kubernetes version is v1.7.0-alpha.0.201+46b20acba22d9a, which is merged before #42081 https://github.com/kubernetes/kubernetes/commit/46b20acba22d9ad577bce74cc3327f8bf4aa89d4

**Comment by wojtek-t** [comment] 2017-02-25 17:50
I have a fix for the underlying problem locally. I need to fix unit tests a will send out a PR out for review.

The problem is both in real kube-proxy and in our mock so the fix should visibily benefit real kube-proxy too (and the latency of propagating endpoints).

I will try to send it by Monday morning PST to have it merged in 1.6

**Comment by wojtek-t** [comment] 2017-02-25 20:16
The PR is out: https://github.com/kubernetes/kubernetes/pull/42108

It is saving 2/3 of cpu & memory allocations of the "non-iptables" related code in kube-proxy.

**Comment by gmarek** [comment] 2017-02-27 16:56
OK, it seems that it was caused by the same thing.

**Closed by gmarek** 2017-02-27 16:56 UTC
Labels: kind/flake, priority/failing-test, sig/scalability

**Comment by timothysc** [comment] 2017-02-27 17:07
@gmarek What is the concise summary here?  There are a number of issues posed, while @wojtek-t 's changes are on the proxy.  It's not clear to the outside observer what the root is.

**Comment by wojtek-t** [comment] 2017-02-27 17:21
The summary is that:
- when we run load test first (without my changes) kubeproxies are processing backlog during the next running density test
- with cgroups enabled, this is affecting kubelet ability to start pods, due to lack of cpu.

So cgroups just changed things, but the underlying problem was cpu starvation.

**Comment by timothysc** [comment] 2017-02-27 17:36
thx @wojtek-t
