### ISSUE TITLE
"Etcd failure [Disruptive] should recover from SIGKILL" e2e is completely broken, breaks other e2es

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#21129] opened 2016-02-12 09:22 UTC

**Comment by piosz** [comment] 2016-02-12 09:23
cc @k8s-oncall @kubernetes/goog-testing

**Comment by piosz** [comment] 2016-02-16 06:21
This is still hapening. Assigning Isaac for triage.

**Comment by ihmccreery** [comment] 2016-02-16 18:14
Three times in the last three days, BeforeSuite failed (filed #21322).  Otherwise, just

**Namespaces [Serial] should delete fast enough (90 percent of 100 namespaces in 150 seconds)**

is just totally borked (filed #21321).

@piosz; what prevented you from triaging this yourself?  It'd be good to know so I'm less in the critical path.

**Comment by ihmccreery** [comment] 2016-02-16 18:18
Sorry, I read this wrong.  I was looking at the gke-serial suite.  Triaging now.

**Comment by ihmccreery** [comment] 2016-02-16 18:23
It looks like massive failures are correlated extremely strongly with failure of

**Etcd failure [Disruptive] should recover from SIGKILL**

Every time that test passes, everything else (except #21321) passes; every time it fails, the whole suite goes south.

Reassigning to @kubernetes/goog-control-plane for triage.

**Comment by piosz** [comment] 2016-02-18 21:23
@ihmccreery sorry for delegating the work to you, but I completely didn't have time to do it and nobody else hasn't volunteered to do it for a while.

@mikedanese it seems you are the author of the test, so assigning you.

**Comment by ihmccreery** [comment] 2016-02-18 22:07
No problem @piosz!  Just wanted to make sure there wasn't some information missing.

**Comment by mikedanese** [comment] 2016-02-19 20:41
I'm looking at this today

**Comment by mikedanese** [comment] 2016-02-20 00:10
It looks like the token controller is not recovering from etcd failing. The test namespace is also stuck in a terminating phase. I'll continue to investigate

**Comment by mikedanese** [comment] 2016-02-20 00:22
Actually lot's of watch related things are broken. I can create/delete objects in the api but watch is broken. Trying to establish a watch in this state causes:
```
mikedanese@e2e-test-mikedanese-master:~$ curl localhost:8080/api/v1/namespaces/default/replicationcontrollers?watch
{"ErrStatus":{"metadata":{},"status":"Failure","message":"The  operation against  could not be completed at this time, please try again.","reason":"ServerTimeout","details":{},"code":500}}
```
Restarting the apiserver fixes the problem. I can start a watch again:
```
mikedanese@e2e-test-mikedanese-master:~$ curl localhost:8080/api/v1/namespaces/default/replicationcontrollers?watch
{"type":"ADDED","object":{"kind":"ReplicationController","apiVersion":"v1","metadata":{"name":"nginxx","namespace":"default","selfLink":"/api/v1/namespaces/default/replicationcontrollers/nginxx","uid":"476052ab-d767-11e5-8f71-42010af00002","resourceVersion":"6756","generation":1,"creationTimestamp":"2016-02-20T00:17:08Z","labels":{"run":"nginxx"}},"spec":{"replicas":2,"selector":{"run":"nginxx"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"nginxx"}},"spec":{"containers":[{"name":"nginxx","image":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}}},"status":{"replicas":2,"observedGeneration":1}}}
```

cc @kubernetes/goog-csi

**Comment by mikedanese** [comment] 2016-02-20 00:25
```
I0220 00:17:14.520476       6 handlers.go:130] GET /api/v1/namespaces/default/replicationcontrollers?watch: (1m0.000361856s) 504
goroutine 126357 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc209e662a0, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209e662a0, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).timeout(0xc20b6cb0a0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:243 +0xbf
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP(0xc208d15c60, 0x7f0396f550a0, 0xc209e662a0, 0xc20bfc9520)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:167 +0x355
k8s.io/kubernetes/pkg/apiserver.func·013(0x7f0396f55068, 0xc20c990aa0, 0xc20bfc9520)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:129 +0x1cb
net/http.HandlerFunc.ServeHTTP(0xc208c61790, 0x7f0396f55068, 0xc20c990aa0, 0xc20bfc9520)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208224c60, 0x7f0396f55068, 0xc20c990aa0, 0xc20bfc9520)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20c990a00)
        /usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/src/go/src/net/http/server.go:1751 +0x35e
 [[curl/7.26.0] 127.0.0.1:48495]
```

**Comment by davidopp** [comment] 2016-02-20 00:27
@lavalamp @wojtek-t

**Comment by lavalamp** [comment] 2016-02-20 00:56
startCaching is *trying* to lock here, but something is holding the lock. https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L214

I'm looking through a stack trace right now for the offender.

This is exactly where I'd expect a problem to be from the description of "bringing etcd down and up repeatedly".

**Comment by lavalamp** [comment] 2016-02-20 01:14
Ah @wojtek-t I think what happened is, when etcd stays down, a List never successfully finishes, and therefore it never calls the OnReplace function, and therefore the lock is never unlocked, and therefore startCaching can't exit.

**Comment by lavalamp** [comment] 2016-02-20 01:15
There's lots in apiserver log to support this:

```
E0220 00:31:54.276093       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.Endpoints: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276106       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.ReplicationController: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276114       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.ReplicationController: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276779       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.Pod: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276813       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.Service: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276817       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.ConfigMap: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276826       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.Secret: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276848       6 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *api.PersistentVolume: client: etcd cluster is unavailable or misconfigured
E0220 00:31:54.276864       6 cacher.go:212] 
```

Additionally I manually looked through the stack trace and confirmed that all of the stuck calls to Watch are stuck waiting to RLock and not some point afterwards.

**Comment by lavalamp** [comment] 2016-02-20 01:17
This is pretty bad, etcd going down for just a bit could freeze up apiserver until it is rebooted.

**Comment by lavalamp** [comment] 2016-02-20 01:20
I think I can make a fix.

**Comment by mikedanese** [comment] 2016-02-20 01:32
Thanks for looking into this.

**Comment by lavalamp** [comment] 2016-02-20 01:42
Yeah, I repro'd in a UT. Fix coming shortly.

**Comment by lavalamp** [comment] 2016-02-20 01:47
I assigned to @wojtek-t, but if anyone wants it merged sooner than monday, feel free to review.

**Comment by lavalamp** [comment] 2016-02-20 01:48
Many thanks to @mikedanese for handing me a broken server to look at, it made this super easy to find.

**Closed** 2016-02-22 10:03 UTC
Labels: area/test, kind/flake, priority/P0, team/CSI
