### ISSUE TITLE
Device Plugin Race

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#56026] opened 2017-11-20 00:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/area hw-accelerators
/sig node

**What happened**:
When re-writing the endpoint code I discovered that the [mutex logic](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L96) is wrong and can lead to a data race while calling the `Device` function.

The current logic is a bit convoluted and would make more sense if the map was created in the for loop.
However it seems like once the map is assigned to the structure, a device update while calling the `Device` function will lead to a data race,

**Anything else we need to know?**:
/assign @jiayingz

**Comment by lichuqiang** [comment] 2017-11-20 01:53
Not quite sure about the race scenario you described, which func do you mean by `Device` function ? The `manager.Devices()` ?

**Comment by vikaschoudhary16** [comment] 2017-11-20 18:23
> 
> When re-writing the endpoint code I discovered that the mutex logic is wrong and can lead to a data race while calling the Device function.

Did you mean [manager.Devices](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/manager.go#L138) by `Device function`?

> 
> The current logic is a bit convoluted and would make more sense if the map was created in the for loop.
> However it seems like once the map is assigned to the structure, a device update while calling the Device function will lead to a data race,

[`devices` map is being assigned to `endpoint` structure with locking protection only.
](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L156-#L158)

Did you want to say that a race will happen if `endpoint.devices` is being updated and at the same time `manager.Devices` gets invoked? If yes, i dont think so. At both the places, first endpoint.mutex lock is taken. So only one can run at a time and other will wait on mutex.

Please let me know if i mistaken something. 

> 
>

**Comment by RenaudWasTaken** [comment] 2017-11-21 00:26
> Did you mean manager.Devices by Device function?

Sorry I meant [`getDevices()`](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/manager.go#L138) essentially though the manager.Devices function calls the endpoint.getDevices().

> Did you want to say that a race will happen if endpoint.devices is being updated and at the same time manager.Devices gets invoked? If yes, i dont think so. At both the places, first endpoint.mutex lock is taken. So only one can run at a time and other will wait on mutex.

Yes thanks for clarifying this.

**Comment by vikaschoudhary16** [comment] 2017-12-15 16:13
I believe we all agree that there is no race in the scenario described in the description of this issue. Shall we close this issue?

**Comment by RenaudWasTaken** [comment] 2017-12-15 16:26
@vikaschoudhary16 there is a race I think I didn't fully read your answer at the time sorry.

Because the way maps works when [replacing](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L157) the map in the structure I am now making the Endpoint's map to the local copy of [`run`](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L96).

Which means that every time we lock in the [`getDevices()`](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L69) function we might [be](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L124) [changing](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L140) [that copy](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L152) underneath.

**Comment by vikaschoudhary16** [comment] 2017-12-18 10:53
@RenaudWasTaken thanks! I got confused b/w call-by-value and call-by-reference and forgot that in golang maps are call by reference.

**Comment by vikaschoudhary16** [comment] 2017-12-19 08:16
> Which means that every time we lock in the getDevices() function we might be changing that local map and thus the endpoint's map underneath.

@RenaudWasTaken  [even with proposed changes, ](https://github.com/kubernetes/kubernetes/pull/56398#issuecomment-352610130)this possibility still remains that some devices may disappear from the endpoint, while manager knows about those.

**Comment by tengqm** [comment] 2017-12-19 09:07
@vikaschoudhary16 Yes. That is the reason why in the latest commit in #56398 the manager is taking a snapshot of the devices known and based the device allocation on that. There are possibilities where devices come and go between the two points in time:

```
------S---------A1------A2-----A3---------C---------------------->
      ^         ^       ^      ^          ^   
    Snapshot   (Allocate calls ..)     Confirm              (manager)
      |                                   |
      | <--- devices appear/disappear --->|<--- devs cont. appear/disappear ...
```

See above diagram. At time `S` the manager starts processing the device allocation requests for a Pod.
It takes a snapshot of the all devices it knows. It doesn't care how many great devices appeared in history or how many devices may go dead in seconds. The manager cannot predict that, so "let it be" is its attitude towards device changes. At time `A1`, it tries allocate device ID `dev-A1`. So long `dev-A1` is good at the moment, it proceeds to allocate `dev-A2` and `dev-A3`. If and only when all requested devices can be allocated, the Pod can be successfully created. It could be the case that device A3 has gone offline after `S` and then come back to life soon before `A3`. That is acceptable. As a transaction, the Pod device allocation is okay.
We cannot pretend that we can get well prepared for all device failures. For example, after the manager has confirmed the device allocation, `dev-A2` may fail again. The Pod still cannot use it. But there is nothing we can do (it is life...).

**Comment by RenaudWasTaken** [comment] 2017-12-19 11:49
> @RenaudWasTaken even with proposed changes, this possibility still remains that some devices may disappear from the endpoint, while manager knows about those.

The race this issue is discussing is about a real race where mutex locks are not handled correctly.

The issue you are mentioning is a different one that @tengqm explains very well in the above comment.
It's a complex interaction but is currently correctly handled by the allocation and pod rejection process.

**Closed** 2017-12-25 07:37 UTC
Labels: area/hw-accelerators, kind/bug, sig/node
