### ISSUE TITLE
Kubernetes documentation is not working fine from last few days

### ISSUE THREAD

**Issue by msrinivascharan** [kubernetes/kubernetes#92322] opened 2020-06-19 21:02 UTC
i observed a major cosmetic change happened to Kubernetes documentation recently, before to that search option was pretty good. Now, it’s not working fine

If I type “security context” or “resource requests” in the search box, in the results, it is showing “fetching results….”, no result even after 15 minutes waiting also.

It works with single words like “security” and “resources” like that, but results

**Comment by BenTheElder** [comment] 2020-06-19 21:59
the documentation is in github.com/kubernetes/website
/sig docs

I believe this is a dupe of https://github.com/kubernetes/website/issues/21808
/triage duplicate
/close

**Closed** 2020-06-19 21:59 UTC
Labels: sig/docs, triage/duplicate, triage/support

**Comment by msrinivascharan** [comment] 2020-06-20 14:08
yes.. i just checked now, it's working fine.

if i type a search keyword like "redins prob"  intentionally wrong spelling, its showing suggestion with right spelling, like as earlier. seems everything ok.

**Comment by BenTheElder** [comment] 2020-06-20 15:44
If you see something like this in the future please file the bug against https://github.com/kubernetes/website/, the folks that manage the site will see the issue much more quickly if you file it against their repo.
