### ISSUE TITLE
`--cpu-manager-policy=static` leads sometimes to `/dev/null` permission denied

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubernetes#95296] opened 2020-10-05 09:30 UTC
**What happened**:

We discover in kubevirts CI k8s-cluster jobs sporadic permission errors on container startup where we can't access `/dev/null` [1] or /dev/kvm` (provided via device plugin) [2]. 

@Fefer-Ivan discovered the same problem in another project and could trace it down to the cpu manager flags [3].

[1] https://github.com/kubevirt/kubevirt/issues/2566
[2] https://github.com/kubevirt/kubevirt/issues/3872
[3] https://github.com/kubevirt/kubevirt/issues/2566#issuecomment-702008004

If this happens "often" or not is probably subjective. For us, it has impact on our prow merge-queue which is pretty bad for us.

I am happy to provide any more details needed.

**What you expected to happen**:

It looks a little bit like there is a race between the device setup from the kubelet/CRI and the container startup when the cpu manager is set to strict. It would be great if the containers only get started once the devices are ready.

It could for instance be related to the cgroup reconcile logic from the cpu manager. Maybe it creates moments where one can't access the devices.

**How to reproduce it (as minimally and precisely as possible)**:

Here one of our jobs which ran into this: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4155/pull-kubevirt-e2e-windows2016/1305640986470256640. Here the logs from the node which we captured (audit logs and kubectl logs created during the execution time https://gcsweb.apps.ovirt.org/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4155/pull-kubevirt-e2e-windows2016/1305640986470256640/artifacts/k8s-reporter/nodes/.

More of these can be found in the referenced kubevirt bug reports. 

**Anything else we need to know?**:

It happens on our CI across multiple versions (right now 1.16-1.18).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16-1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by EdSchouten** [comment] 2020-10-21 04:43
I've also observed this on a couple of occasions, and it seems this can even happen after a container has been running for >10 minutes. It even affects containers that don't use exclusive CPUs (i.e., pods that don't use Guaranteed QoS).

**Comment by EdSchouten** [comment] 2020-10-22 11:11
Ha! I think I've managed to find the root cause of this. This can happen if you're using a copy of runc that doesn't have this commit:

https://github.com/opencontainers/runc/commit/afe83489d4243800cb68b5c766831a4ceaff4578#diff-2bef70ef32203b9a65985f649e469ad4db0f361673aab84c1536afc9574ca29b

Just make sure you're running runc>=1.0.0-91 and you're fine!

**Comment by rmohr** [comment] 2020-10-22 11:28
@EdSchouten awesome, thanks for sharing. Will try it immediately.

**Comment by dims** [comment] 2021-01-13 23:34
looks like we can close this

/close

**Closed** 2021-01-13 23:34 UTC
Labels: kind/bug, needs-triage, sig/node
