### ISSUE TITLE
Run scalability tests for 1.7

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#47344] opened 2017-06-12 15:14 UTC
We know that kubemark-5000 currently fails in head. We need to make sure it's passing and run real 5000-Node tests before 1.7 release. 

cc @kubernetes/sig-scalability-bugs @dchen1107 @shyamjvs @wojtek-t

**Comment by dchen1107** [comment] 2017-06-12 18:47
both https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-scalability&show-stale-tests= and https://k8s-testgrid.appspot.com/release-master-blocking#gce-scalability&show-stale-tests= are green. 

https://k8s-testgrid.appspot.com/google-kubemark is also green. @gmarek I am assigning this to you to delegate.

**Comment by gmarek** [comment] 2017-06-14 07:59
Those are 100-Node tests. We need to look at https://k8s-testgrid.appspot.com/google-kubemark#gce-scale and run https://k8s-testgrid.appspot.com/google-gce#gce-enormous-cluster + https://k8s-testgrid.appspot.com/google-gke#gke-large-cluster.

We believe that we fixed the kubemark-scale, I'm working on making enormous and large clusters working.

**Comment by shyamjvs** [comment] 2017-06-14 16:49
FYI kubemark-scale is now fixed with run 469 green (ref: https://k8s-testgrid.appspot.com/google-kubemark#gce-scale)

**Comment by dchen1107** [comment] 2017-06-17 03:42
@gmarek Based on my record, scale test is the only one having automated for upgrade. Please make sure running the manual upgrade test for scale case.

cc/ @kubernetes/kubernetes-release-managers

**Comment by gmarek** [comment] 2017-06-19 12:47
Working on it with @shyamjvs.

**Comment by gmarek** [comment] 2017-06-21 09:40
Kubemark 5000 is passing. To run real 5000 Node experiment we need #47513 or equivalent to be merged.

**Comment by shyamjvs** [comment] 2017-06-21 19:35
Update: We could finally start an enormous cluster today on GCE, but with 4k nodes instead of 5k nodes (due to shortage of routes quota with gke-large-cluster also running). Currently load test is running. Density test failed due to oom'ing issue with a kubelet and also there was higher than threshold latency for 'list pods', but I think we understand this part. After the current run finishes, we'll try running 5k tomorrow (4k if that's not possible), likely with bigger nodes.

**Comment by marun** [comment] 2017-06-23 20:14
@gmarek What's the status on this?

**Comment by gmarek** [comment] 2017-06-23 20:31
@marun - it was the same issue as https://github.com/kubernetes/kubernetes/issues/47865#issuecomment-310694695.

Everything looks good for now. Two more tests are needed.

**Comment by gmarek** [comment] 2017-06-24 17:58
We run 4k Node test with services. Things look noticeably better after removal of ip-masq-agent, but we're still not passing. The reason for this is, again, storm of updates from NPD that overload API server. The reason for those updates is fluentd crashloop (OOM). @crassirostris

**Comment by shyamjvs** [comment] 2017-06-24 19:46
To clarify, the storm of updates due to fluentd oom'ing come from kubelet and this is the major component. Ones from npd are just a consequence. Explained in https://github.com/kubernetes/kubernetes/issues/47865#issuecomment-310861405

**Comment by gmarek** [comment] 2017-06-26 10:13
Discussed F2F - we're not sure why NPD tries to do anything in case of container OOM. @kubernetes/sig-node-bugs @dchen1107 @Random-Liu - do you know why NPD tries to patch NodeStatus in such scenario? Shouldn't Kubelet handle that? Currently it seems that if some Containers would be crashlooping we'll get into pretty bad failure loop, from which we can't recover given big enough scale. @derekwaynecarr Event Spam will help with that, but we should also minimize number of NodeStatus updates.

**Comment by marun** [comment] 2017-06-26 19:50
@gmarek Should this continue to be a release blocker?  If not, please remove 'approved-for-milestone'.

**Comment by Random-Liu** [comment] 2017-06-27 16:56
> do you know why NPD tries to patch NodeStatus in such scenario? Shouldn't Kubelet handle that? Currently it seems that if some Containers would be crashlooping we'll get into pretty bad failure loop, from which we can't recover given big enough scale.

Either node status update or event generation is shown as a `PATCH` in apiserver log, are we sure that NPD `PATCH` is patching NodeStatus? NPD only generates event for OOM instead of updating node condition. An event generation should be shown like this:
```
I0626 05:14:46.578731       6 wrap.go:42] PATCH /api/v1/namespaces/default/events/kubemark-5000-minion-group-s8hp.14cb63e2de1541f4: (625.489189ms) 200 [[node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format] 35.188.206.92:36716]
```

When there is no node condition need to update, NPD patches node status to update heartbeat timestamp every 1 minute, for 5000 node cluster, it should only generate 5000 (queries/min)=83.3 (queries/s).

**Comment by shyamjvs** [comment] 2017-06-27 18:29
NPD indeed is sending many PATCH node-status requests, so I guess this likely is a bug. Ref https://github.com/kubernetes/node-problem-detector/issues/124#issuecomment-311444471

**Comment by Random-Liu** [comment] 2017-06-27 18:36
@shyamjvs If so, this seems to be a apiserver client issue then. NPD won't patch node status so frequently, it seems to be the client itself retries frequently on patch error.

The client may need to be error code aware, it should not retry so frequently when the error code is 429, which only makes things worse.

**Comment by gmarek** [comment] 2017-06-27 18:39
I'd love to be able to fix fluentd, and I'm not alone @crassirostris. The thing is even though that's possible at least in theory, we need to be prepared for the same scenario for user Pods, which we won't be able to fix.

**Comment by Random-Liu** [comment] 2017-06-27 18:53
> I'd love to be able to fix fluentd, and I'm not alone @crassirostris. The thing is even though that's possible at least in theory, we need to be prepared for the same scenario for user Pods, which we won't be able to fix.

Offline discussed with @yujuhong, the client retry on 429 error seems to be an even more critical problem. Once someone triggers it, it will retry even more, and the whole cluster gradually go south.

**Comment by yujuhong** [comment] 2017-06-27 20:03
@gmarek @shyamjvs, my understanding is that there is no regression since the services test was not run with 1.6 (correct me if I am wrong). I think we can remove the release-blocker label and the 1.7 milestone, and leave this issue for follow-up discussions.

**Comment by shyamjvs** [comment] 2017-06-27 21:38
@yujuhong This is not a release-blocker anymore (ref: https://github.com/kubernetes/kubernetes/issues/47344#issuecomment-311163160)
We're yet to run scale tests on 5k nodes without services (did it only on 4k currently), which we recently got unblocked with pr https://github.com/kubernetes/kubernetes/pull/47513 getting merged.
We expect it to work, just waiting for correctness tests (currently running) on 5k node to first finish.

Removing release-blocker, but still keeping the 1.7 milestone. @gmarek SGTY?

**Comment by gmarek** [comment] 2017-06-28 07:58
+1. It's not a release blocker anymore. It seems that we're in the same state we were in 1.6.

**Comment by shyamjvs** [comment] 2017-06-30 19:04
Ran correctness e2e tests on 5k-node cluster and it went well except the following failures (mostly fixed):
- GCL logging (fixed after updating IAM for the project, thanks @crassirostris for guiding)
[k8s.io] Cluster level logging using GCL should check that logs from containers are ingested in GCL
[k8s.io] Cluster level logging using GCL should ingest events
- Misconfigured e2e test (fixed by https://github.com/kubernetes/kubernetes/pull/48271)
[k8s.io] Firewall rule should have correct firewall rules for e2e cluster 13s
- Heapster couldn't schedule on large cluster due to small nodes (fixed by https://github.com/kubernetes/kubernetes/pull/48214)
[k8s.io] Kubectl cluster-info should check if Kubernetes master services is included in cluster-info
[k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster
[k8s.io] [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light Should scale from 1 pod to 2 pods
[k8s.io] [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light Should scale from 2 pods to 1 pod
- Timeout while waiting for kubelet to update pod's volume on secret/configmap update (will file issue for this)
[k8s.io] ConfigMap optional updates should be reflected in volume [Conformance] [Volume]

**Comment by shyamjvs** [comment] 2017-07-01 01:14
Just finished upgrade testing from 1.6 to 1.7 on large cluster (500 nodes) successfully. With that we have all 3 things (correctness, scalability and upgradability) tested on large clusters.
We can close this issue now, having all the above individually filed issues. Thank you everyone who helped with this!

**Closed by shyamjvs** 2017-07-01 01:14 UTC
Labels: sig/node, sig/scalability, status/in-progress
