### ISSUE TITLE
Misleading EmptyDir default.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#66081] opened 2018-07-11 18:21 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
/kind bug

**What happened**:

If you mess up your `persistentVolumeClaim` definition, then you get an emptyDir for free :)

**What you expected to happen**:

You should just get complete scheduling failure, because the volume is undefined.

(even though its a semantic issue, for people that ship kubernetes YAMLs to customers, this can result in critical dataloss when they configure stuff...)

**How to reproduce it (as minimally and precisely as possible)**:

kubectl create -f https://gist.githubusercontent.com/jayunit100/622875501f127aa61cb81a8c5dfd7610/raw/1b5757eaeb55f5bff761ea5040f137e75c8a731d/cfssl.yml -n j1 ; sleep 5 ; kubectl get deployment cfssl -n j1 -o yaml | grep -A 5 emptyDir

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jayunit100** [comment] 2018-07-11 18:22
@k8s-mirror-storage-proposals @kubernetes/sig-storage-bugs

**Comment by msau42** [comment] 2018-07-11 18:46
Hm my kubectl correclty errored due to the bad yaml:
```
$ kubectl -f testpod.yaml 
error: error validating "testpod.yaml": error validating data: ValidationError(Pod.spec.volumes[0]): unknown field "wrongPersistentVolumeClaim" in io.k8s.api.core.v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false
```
```
apiVersion: v1
kind: Pod 
metadata:
  name: web-server
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/www/html
         name: mypvc
  volumes:
   - name: mypvc
     wrongPersistentVolumeClaim:
       claimName: test-pvc-2
```

**Comment by jayunit100** [comment] 2018-07-11 18:59
what version

**Comment by msau42** [comment] 2018-07-11 20:11
I am on head:
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.2029+7394f9300dc458-dirty", GitCommit:"7394f9300dc4580cf96878a9d84a450da17421a6", GitTreeState:"dirty", BuildDate:"2018-07-09T22:29:37Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.2029+7394f9300dc458-dirty", GitCommit:"7394f9300dc4580cf96878a9d84a450da17421a6", GitTreeState:"dirty", BuildDate:"2018-07-09T22:27:40Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by msau42** [comment] 2018-07-11 20:16
cc @k8s-mirror-api-machinery-bugs

**Comment by liggitt** [comment] 2018-07-11 21:03
probably a duplicate of https://github.com/kubernetes/kubernetes/issues/5889

**Comment by liggitt** [comment] 2018-07-11 21:05
I also get a client-side error:

```
kubectl create -f https://gist.githubusercontent.com/jayunit100/622875501f127aa61cb81a8c5dfd7610/raw/1b5757eaeb55f5bff761ea5040f137e75c8a731d/cfssl.yml
error: error validating "https://gist.githubusercontent.com/jayunit100/622875501f127aa61cb81a8c5dfd7610/raw/1b5757eaeb55f5bff761ea5040f137e75c8a731d/cfssl.yml": error validating data: ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "psadpiofj2pfjersistantVolumeClaiisdfdf" in io.k8s.api.core.v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by liggitt** [comment] 2018-07-11 21:06
closing since this can't be reproduced on master, and we have existing feature request issues for server-side opt-in of strict schema validation

/close

**Closed by liggitt** 2018-07-11 21:06 UTC
Labels: kind/bug, sig/storage

**Comment by liggitt** [comment] 2018-07-11 21:30
Submitting that to the server is equivalent to submitting a volume with no type defined, which defaults to emptyDir

**Comment by liggitt** [comment] 2018-07-11 21:35
See https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/defaults.go#L65

**Comment by msau42** [comment] 2018-07-11 21:35
Ah, I see the defaulting [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/defaults.go#L65).  That's an odd default policy, as it also overwrites any fields for the volume source.

**Comment by msau42** [comment] 2018-07-11 21:37
And it can cause applications to still come up successfully and write away thinking that their data will be persisted.

**Comment by liggitt** [comment] 2018-07-11 21:46
> That's an odd default policy, as it also overwrites any fields for the volume source.

 There are no other fields in the volume source if all the pointer fields are nil 

> it can cause applications to still come up successfully and write away thinking that their data will be persisted.

 I agree we wouldn't recommend setting the default that way now, but we're not going to change that and break currently valid pod specs
