### ISSUE TITLE
Support observedGeneration in kubectl wait

### ISSUE THREAD

**Issue by toumorokoshi** [kubernetes/kubernetes#101843] opened 2021-05-09 04:42 UTC
#### What would you like to be added:

Today, kubectl wait seems to just wait for a specific condition, and not much more. There is an effort with [kstatus](https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/README.md#conditions) to include fields aside from conditions to determine resource availability (e.g. observedGeneration).

It would be great if `kubectl wait` also supports observedGeneration's value as a flag, and wait until observedGeneration matches the generation of the object. 

#### Why is this needed:

kstatus seems to be satisfying a similar use case as kubectl wait (waiting for resources based on idiomatic fields in the object), it would be great to have the two follow the same semantics.

**Comment by CaoDonghui123** [comment] 2021-05-10 02:51
maybe duplicate of #95759

**Comment by neolit123** [comment] 2021-05-10 16:47
> maybe duplicate of #95759

/close
/sig cli

**Closed** 2021-05-10 16:47 UTC
Labels: kind/feature, needs-triage, sig/cli
