### ISSUE TITLE
[Flaking Test] k8s.io/apiserver/pkg/registry/generic/registry.registry

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [kubernetes/kubernetes#125425] opened 2024-06-10 21:42 UTC
### Which jobs are flaking?

k8s.io/apiserver/pkg/registry/generic/registry.registry

### Which tests are flaking?

k8s.io/apiserver/pkg/registry/generic/registry.registry

![2024-06-10_17-39-02](https://github.com/kubernetes/kubernetes/assets/28905827/109f6dc3-5556-4f49-9a10-49af0b4ea45a)

### Since when has it been flaking?

6/9/2024

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

It appears that there's a connection trying to be made locally over certain ports, but the connection cannot be established. Please see below.

```
=== FAIL: k8s.io/apiserver/pkg/registry/generic/registry TestStoreListResourceVersion (0.63s)
W0610 10:05:26.886087   69284 logging.go:59] [core] [Channel #245 SubChannel #247] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:42093", ServerName: "localhost:42093", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42093: connect: connection refused"
W0610 10:05:27.109417   69284 logging.go:59] [core] [Channel #125 SubChannel #127] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:35107", ServerName: "localhost:35107", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:35107: connect: connection refused"
W0610 10:05:27.212954   69284 logging.go:59] [core] [Channel #265 SubChannel #267] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:43981", ServerName: "localhost:43981", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:43981: connect: connection refused"
W0610 10:05:27.343989   69284 logging.go:59] [core] [Channel #225 SubChannel #228] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:40335", ServerName: "localhost:40335", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:40335: connect: connection refused"
```

### Relevant SIG(s)

/sig testing

**Comment by BenTheElder** [comment] 2024-06-11 16:52
Seeing this unit test flake elsewhere, this does seem like a dupe of https://github.com/kubernetes/kubernetes/issues/125406

pull-kubernetes-unit and ci-kubernetes-unit are the same tests, just pre-merge and periodically against merged code, it's the same flake.

**Comment by Vyom-Yadav** [comment] 2024-06-11 18:27
Duplicate of #125406 

/close

**Closed by Vyom-Yadav** 2024-06-11 18:27 UTC
Labels: kind/flake, sig/testing, needs-triage
