### ISSUE TITLE
CPU/MEM percentage in HPA should be based on limits! kedacore/keda#3506

### ISSUE THREAD

**Issue by Hello-Linux** [kubernetes/kubernetes#111717] opened 2022-08-05 09:12 UTC
### What happened?

https://github.com/kedacore/keda/issues/3506

### What did you expect to happen?

https://github.com/kedacore/keda/issues/3506

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kedacore/keda/issues/3506

### Anything else we need to know?

https://github.com/kedacore/keda/issues/3506

### Kubernetes version

https://github.com/kedacore/keda/issues/3506

### Cloud provider

https://github.com/kedacore/keda/issues/3506

### OS version

https://github.com/kedacore/keda/issues/3506

### Install tools

https://github.com/kedacore/keda/issues/3506

### Container runtime (CRI) and version (if applicable)

https://github.com/kedacore/keda/issues/3506

### Related plugins (CNI, CSI, ...) and versions (if applicable)

https://github.com/kedacore/keda/issues/3506

**Comment by neolit123** [comment] 2022-08-08 07:31
/sig autoscaling
for triage

**Comment by BenTheElder** [comment] 2022-08-08 22:47
This appears to be an indirect duplicate of https://github.com/kubernetes/kubernetes/issues/72811 with no new information. The link used for all issue template fields currently says:

> Proposal
> I think the cpu and mem should base on pod limit not request
> like this issue https://github.com/kubernetes/kubernetes/issues/72811
> 
> Use-Case
> No response
> 
> Anything else?
> No response

/triage duplicate
/close

**Closed** 2022-08-08 22:48 UTC
Labels: kind/bug, sig/autoscaling, triage/duplicate, needs-triage
