### ISSUE TITLE
flake: [k8s.io] Load capacity [Feature:Performance] should be able to handle 30 pods per node

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24269] opened 2016-04-14 18:48 UTC
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/6130/

https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/6130/

```
11:24:43 
11:24:43 • Failure [1554.510 seconds]
11:24:43 [k8s.io] Load capacity
11:24:43 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:424
11:24:43   [Feature:Performance] should be able to handle 30 pods per node [It]
11:24:43   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:152
11:24:43 
11:24:43   creating rc load-test-small-rc-197
11:24:43   Expected error:
11:24:43       <*errors.errorString | 0xc8236fe440>: {
11:24:43           s: "Number of reported pods for load-test-small-rc-197 changed: 4 vs 5",
11:24:43       }
11:24:43       Number of reported pods for load-test-small-rc-197 changed: 4 vs 5
11:24:43   not to have occurred
11:24:43 
11:24:43   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:218
```

**Comment by lavalamp** [comment] 2016-04-14 18:49
Previous closed issue: #22324

**Comment by saad-ali** [comment] 2016-05-13 05:15
Another failure: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/7386/

**Comment by fejta** [comment] 2016-05-23 22:32
Assigning to @davidopp per team/control-plane label

**Comment by wojtek-t** [comment] 2016-05-30 19:04
This is duplicate of #26511 - closing in favor of that one (which already has a PR fixing it in flight).

**Closed by wojtek-t** 2016-05-30 19:04 UTC
Labels: kind/flake, priority/P1, team/control-plane
