### ISSUE TITLE
E2E Failure: "Kubelet [Serial] [Slow] regular resource usage tracking for 100 pods per node over 20m0s"

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#22755] opened 2016-03-09 20:15 UTC
It's been broken every test since http://ci-test.k8s.io/kubernetes-e2e-gce-serial/791 . It's flaky, but not broken in `gke-serial`.

**Comment by dchen1107** [comment] 2016-03-09 21:28
@yujuhong This is the failure what I mentioned to you earlier.

**Comment by dchen1107** [comment] 2016-03-09 21:31
I think I know what is going on here. Now we registered 4 nodes including master node but master is unschedulable. The test itself doesn't detect such, and expect 400 pods. I will send pr shortly to fix this.

**Comment by yujuhong** [comment] 2016-03-09 21:33
@gmarek already had a PR up to fix this #22743

**Comment by bgrant0607** [comment] 2016-03-09 21:59
Fixed

**Comment by bgrant0607** [comment] 2016-03-10 02:41
Still failing

**Comment by bgrant0607** [comment] 2016-03-10 02:43
kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/749
```
• Failure [550.394 seconds]
Kubelet [Serial] [Slow]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:262
  regular resource usage tracking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:250
    for 100 pods per node over 20m0s [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:248

    Expected error:
        <*errors.errorString | 0xc20862a9a0>: {
            s: "Only 260 pods started out of 300",
        }
        Only 260 pods started out of 300
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:72
```

**Comment by yujuhong** [comment] 2016-03-10 02:53
One of the nodes ran into the "no available IPv4 addresses" docker issue #21523
```
event for resource300-a3db59a8-e64c-11e5-acac-42010af01555-prrsa: {kubelet gke-jenkins-e2e-eb728830-node-dexu} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container f1399475a1d83b2c5016eef383b592633fafdcfcd5e2672b77f047982e19ce63: no available IPv4 addresses on this network's address pools: bridge (f5d1e033158b216de87fb545a3e932b0c13875d357cd4d0260496d56e401defb)\n"
```

**Comment by yujuhong** [comment] 2016-03-10 03:00
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/749/

Also, not all logs were collected for this node (gke-jenkins-e2e-eb728830-node-dexu). E.g., kubelet.log was empty but docker.log was fine. /cc @spxtr 

Also, probably unrelated, but the build log is full of warning like this:
```
15:23:43   warnings.warn(_SCOPES_WARNING)
15:23:44 Dumping logs for gke-jenkins-e2e-eb728830-node-dexu
15:23:44 ... in gke:ssh-to-node()
15:23:44 ... in gke:detect-project()
15:23:44 /var/lib/jenkins/jobs/kubernetes-e2e-gke-serial/workspace/cloudsdk/google-cloud-sdk/lib/third_party/oauth2client/contrib/gce.py:72: UserWarning: You have requested explicit scopes to be used with a GCE service account.
15:23:44 Using this argument will have no effect on the actual scopes for tokens
15:23:44 requested. These scopes are set at VM instance creation time and
15:23:44 can't be overridden in the request.
```

**Comment by yujuhong** [comment] 2016-03-10 03:05
Dropping the priority since this is a documented, known issue.

**Comment by spxtr** [comment] 2016-03-10 03:20
I made this issue about the warnings: #22751

**Comment by yujuhong** [comment] 2016-03-10 03:30
> I made this issue about the warnings: #22751

I see. Thanks!

Closing this issues since the new failure was caused by #21523.

**Closed by yujuhong** 2016-03-10 03:30 UTC
Labels: area/test, priority/P1, team/control-plane
