### ISSUE TITLE
flake: k8s.io/kubernetes/pkg/controller/persistentvolume TestControllerSync 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#28121] opened 2016-06-27 16:17 UTC
Came up from: https://github.com/kubernetes/kubernetes/pull/28114

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28114/kubernetes-pull-test-unit-integration/32813/#k8siokubernetespkgcontrollerpersistentvolume-testcontrollersync

Ran several times locally, could not reproduce.

**Comment by jlowdermilk** [comment] 2016-06-27 16:52
This is the sole cause of flakes in the [test-go job](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/). Failures all look like
```
Error Message

Failed
Stacktrace

framework_test.go:810: Test "5-6 - update bound volume from 1.2": Claim check failed [A-expected, B-got result]: {"claim5-6":{"metadata":{"name":"claim5-6","namespace":"default","selfLink":"/api/v1/pvc/claim5-6","uid":"uid5-6","creationTimestamp":null
	
	A: ,"annotations":{"pv.kubernetes.io/bind-completed":"yes"}},"spec":{"accessModes":["ReadWriteOnce","ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"volumeName":"volume5-6"},"status":{"phase":"Bound"}}}
	
	B: },"spec":{"accessModes":["ReadWriteOnce","ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"volumeName":"volume5-6"},"status":{"phase":"Pending"}}}
```

**Comment by jlowdermilk** [comment] 2016-06-27 17:30
Dupe of #28076

**Closed by jlowdermilk** 2016-06-27 17:30 UTC
Labels: kind/flake, priority/P0, team/control-plane
