### ISSUE TITLE
node e2e test flake: Error deleting instance tmp-node-e2e-...

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#30719] opened 2016-08-16 22:57 UTC
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30701/node-pull-build-e2e-test/19211/ 

```
I0816 14:21:25.421677   17257 e2e_remote.go:208] Extracting tar on tmp-node-e2e-dba9cd69-e2e-node-containervm-v20160321-image
I0816 14:21:25.531914   17257 e2e_remote.go:208] Extracting tar on tmp-node-e2e-dba9cd69-e2e-node-ubuntu-trusty-docker10-v1-image
I0816 14:21:28.725255   17257 e2e_remote.go:221] Starting tests on tmp-node-e2e-dba9cd69-e2e-node-ubuntu-trusty-docker10-v1-image
I0816 14:21:28.997449   17257 e2e_remote.go:221] Starting tests on tmp-node-e2e-dba9cd69-e2e-node-containervm-v20160321-image
I0816 14:27:22.581857   17257 run_e2e.go:507] Error deleting instance tmp-node-e2e-dba9cd69-coreos-alpha-1122-0-0-v20160727
================================================================
Failure Finished Host  Test Suite

unable to create gce instance with running docker daemon for image coreos-alpha-1122-0-0-v20160727.  googleapi: Error 404: The resource 'projects/k8s-jkns-pr-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-dba9cd69-coreos-alpha-1122-0-0-v20160727' was not found, notFound
================================================================
I0816 14:27:22.587306   17257 run_e2e.go:507] Error deleting instance tmp-node-e2e-dba9cd69-gci-dev-54-8711-0-0
================================================================
Failure Finished Host  Test Suite

unable to create gce instance with running docker daemon for image gci-dev-54-8711-0-0.  googleapi: Error 404: The resource 'projects/k8s-jkns-pr-node-e2e/zones/us-central1-f/instances/tmp-node-e2e-dba9cd69-gci-dev-54-8711-0-0' was not found, notFound
================================================================
I0816 14:27:22.721755   17257 run_e2e.go:507] Error deleting instance tmp-node-e2e-dba9cd69-e2e-node-ubuntu-trusty-docker9-v1-image
================================================================
Failure Finished Host  Test Suite
```

**Comment by dchen1107** [comment] 2016-08-16 23:32
xref: https://github.com/kubernetes/kubernetes/issues/28716

**Comment by dchen1107** [comment] 2016-08-17 00:49
@yujuhong, @Random-Liu and I looked into the issue together, and we believe we found the root cause here: 

To speed up the test, node e2e test-infra tries to paralyzing the building with instance creation. Unfortunately the building might be failed, and through Fatal error, which bypass the deletionInstance call. This means every pr build with compiling error will leak 5 instances since today node e2e covers 5 different images (container-vm, coreos, gci, etc.)

@Random-Liu will send a fix shortly.

**Comment by yujuhong** [comment] 2016-08-17 01:55
I manually deleted the leaked VMs again since the number was increasing sooner than expected (i.e., many PRs don't compile at all). @Random-Liu's PR #30728 is waiting to be merged, and the fix should stop the bleeding.

**Comment by yujuhong** [comment] 2016-08-17 01:56
By the way, it's probably not a bad idea if we can stop the older builds of the same PR before starting a new one.

**Closed** 2016-08-17 04:04 UTC
Labels: kind/flake, priority/P0, team/node
