### ISSUE TITLE
cgroup/hugetbl/hugetlb.1GBlimit_in_bytes values set incorrectly

### ISSUE THREAD

**Issue by asmith-a10** [kubernetes/kubernetes#85938] opened 2019-12-05 09:24 UTC
**What happened**:
The value for cgroup/hugetbl/hugetlb.1GBlimit_in_bytes  is set incorrectly. 
Using the following settings:
        resources:
          requests:
            memory: 4Gi
            cpu: "4"
            hugepages-1Gi: 4Gi
          limits:
            memory: 4Gi
            cpu: "4"
            hugepages-1Gi: 4Gi

bash-4.2# cat hugetlb.1GB.limit_in_bytes 
9223372036854771712

**What you expected to happen**:
I would expect the value to be 4294967296

**How to reproduce it (as minimally and precisely as possible)**:
1. Allocate huge-pages
echo 12 >/sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
echo 12 >/sys/devices/system/node/node1/hugepages/hugepages-1048576kB/nr_hugepages
2. Create the cluster
3. Decleare Hugepages 
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
     ...
       resources:
          requests:
            memory: 4Gi
            cpu: "4"
            hugepages-1Gi: 4Gi
          limits:
            memory: 4Gi
            cpu: "4"
            hugepages-1Gi: 4Gi
        volumeMounts:
        - mountPath: /hugepages
          name: hugepage

**Anything else we need to know?**:
no
**Environment**:
Ubuntu 16.04.2 LTS
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux 5600t 4.15.0-72-generic #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node

**Comment by bart0sh** [comment] 2019-12-10 12:49
@AlxSmith11 

> bash-4.2# cat hugetlb.1GB.limit_in_bytes
9223372036854771712

Can you show full path to hugetlb.1GB.limit_in_bytes entry?

I'm guessing you're showing host level entry. You may want to look at the pod level one.
Here is what I see on my machine:
```
# cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
12
# cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
12
$ cat pod-85938.yaml 
kind: Pod
apiVersion: v1
metadata:
  name: test
spec:
  containers:
    - name: test
      image: alpine
      command: ["/bin/sh", "-c", "sleep 30000"]

      resources:
        requests:
          cpu: "4"
          hugepages-1Gi: 4Gi
        limits:
          hugepages-1Gi: 4Gi

      volumeMounts:
      - mountPath: /hugepages
        name: hugepage

  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages

# kubectl apply -f pod-85938.yaml 
pod/test created

# kubectl get pod -o jsonpath='{.metadata.uid}' test
29ed167e-d729-4932-a746-05ea3e886dc7

# cat /sys/fs/cgroup/hugetlb/kubepods/burstable/pod29ed167e-d729-4932-a746-05ea3e886dc7/hugetlb.1GB.limit_in_bytes 
4294967296
```

**Comment by AlxSmith11** [comment] 2019-12-10 22:34
@bart0sh 

Thanks for the reply. I do see the correct values being reported by the host.   The problem is the reporting inside the Pod/Container, as shown below.   Is the path /sys/fs/cgroup/hugetlb/ inside the container correct?

apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7
spec:
  selector:
    matchLabels:
      run: centos7
  replicas: 1
  template:
    metadata:
      labels:
        run: centos7
      annotations:
        k8s.v1.cni.cncf.io/networks: north-network,south-network
    spec:
      containers:
      - name: centos7
        image: toolbox-fc  
        imagePullPolicy: Never
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            memory: 16Gi
            cpu: "4"
            hugepages-1Gi: 4Gi
            intel.com/north_traffic: '1'
            intel.com/south_traffic: '1'
          limits:
            memory: 16Gi
            cpu: "4"
            hugepages-1Gi: 4Gi
            intel.com/north_traffic: '1'
            intel.com/south_traffic: '1'
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
              add: ["SYS_ADMIN", "NET_ADMIN","IPC_LOCK"]

$ kubectl create -f apps/centos/centos.yaml 
deployment.apps/centos7 created
$ kubectl get pods 
NAME                       READY   STATUS    RESTARTS   AGE
centos7-6548948cd6-zth6b   1/1     Running   0          10s
$ kubectl get pod -o jsonpath='{.metadata.uid}' centos7-6548948cd6-zth6b 
6dd9bb3b-088b-4724-83f1-267be53c9b4a
$ cat /sys/fs/cgroup/hugetlb/kubepods/pod6dd9bb3b-088b-4724-83f1-267be53c9b4a/hugetlb.2MB.limit_in_bytes 
0
$ cat /sys/fs/cgroup/hugetlb/kubepods/pod6dd9bb3b-088b-4724-83f1-267be53c9b4a/hugetlb.1GB.limit_in_bytes 
4294967296
$ kubectl exec -ti centos7-6548948cd6-zth6b bash 
[root@centos7-6548948cd6-zth6b /]# cat /sys/fs/cgroup/hugetlb/hugetlb.1GB.limit_in_bytes 
9223372035781033984
[root@centos7-6548948cd6-zth6b /]# cat /sys/fs/cgroup/hugetlb/hugetlb.2MB.limit_in_bytes 
9223372036852678656
[root@centos7-6548948cd6-zth6b /]# 

$kubectl describe node 5600t
Capacity:
 cpu:                      40
 ephemeral-storage:        360375948Ki
 hugepages-1Gi:            16Gi
 hugepages-2Mi:            0
 intel.com/north_traffic:  4
 intel.com/south_traffic:  4
 memory:                   131728872Ki
 pods:                     110
Allocatable:
 cpu:                      40
 ephemeral-storage:        332122473127
 hugepages-1Gi:            16Gi
 hugepages-2Mi:            0
 intel.com/north_traffic:  4
 intel.com/south_traffic:  4
 memory:                   114849256Ki
 pods:                     110
System Info:
 Machine ID:                 31cd703369634f3aaee1d48826368aa1
 System UUID:                4C4C4544-0057-4310-8052-CAC04F305432
 Boot ID:                    de127d24-4daf-46a0-b7ec-706ab2f83659
 Kernel Version:             4.15.0-72-generic
 OS Image:                   Ubuntu 16.04.2 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.6
 Kubelet Version:            v1.16.1
 Kube-Proxy Version:         v1.16.1
PodCIDR:                     10.244.0.0/24
PodCIDRs:                    10.244.0.0/24
Non-terminated Pods:         (11 in total)
  Namespace                  Name                                    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                    ------------  ----------  ---------------  -------------  ---
  default                    centos7-6548948cd6-zth6b                4 (10%)       4 (10%)     16Gi (14%)       16Gi (14%)     6m50s
  kube-system                coredns-5644d7b6d9-4shgn                100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     11m
  kube-system                coredns-5644d7b6d9-9knwt                100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     11m
  kube-system                etcd-5600t                              0 (0%)        0 (0%)      0 (0%)           0 (0%)         10m
  kube-system                kube-apiserver-5600t                    250m (0%)     0 (0%)      0 (0%)           0 (0%)         10m
  kube-system                kube-controller-manager-5600t           200m (0%)     0 (0%)      0 (0%)           0 (0%)         10m
  kube-system                kube-flannel-ds-amd64-q5jr8             100m (0%)     100m (0%)   50Mi (0%)        50Mi (0%)      11m
  kube-system                kube-multus-ds-amd64-zjk65              100m (0%)     100m (0%)   50Mi (0%)        50Mi (0%)      11m
  kube-system                kube-proxy-zvkrb                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         11m
  kube-system                kube-scheduler-5600t                    100m (0%)     0 (0%)      0 (0%)           0 (0%)         10m
  kube-system                kube-sriov-device-plugin-amd64-zbt9w    0 (0%)        0 (0%)      0 (0%)           0 (0%)         10m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                 Requests       Limits
  --------                 --------       ------
  cpu                      4950m (12%)    4200m (10%)
  memory                   16624Mi (14%)  16824Mi (15%)
  ephemeral-storage        0 (0%)         0 (0%)
  intel.com/north_traffic  1              1
  intel.com/south_traffic  1              1
Events:
  Type    Reason                   Age                From               Message
  ----    ------                   ----               ----               -------
  Normal  Starting                 12m                kubelet, 5600t     Starting kubelet.
  Normal  NodeHasSufficientMemory  12m (x8 over 12m)  kubelet, 5600t     Node 5600t status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    12m (x8 over 12m)  kubelet, 5600t     Node 5600t status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     12m (x7 over 12m)  kubelet, 5600t     Node 5600t status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced  12m                kubelet, 5600t     Updated Node Allocatable limit across pods
  Normal  Starting                 11m                kube-proxy, 5600t  Starting kube-proxy.

**Comment by bart0sh** [comment] 2019-12-11 08:39
>  Is the path /sys/fs/cgroup/hugetlb/ inside the container correct?

You should still use pod cgroup path(/sys/fs/cgroup/hugetlb/kubepods/pod6dd9bb3b-088b-4724-83f1-267be53c9b4a/hugetlb.1GB.limit_in_bytes in your example) inside the container I guess.

**Comment by bart0sh** [comment] 2020-02-26 11:36
@AlxSmith11 Is this issue solved? If so, please close it. Thanks.

**Comment by bart0sh** [comment] 2020-03-10 10:12
@AlxSmith11 gently ping for closing this issue.

**Comment by AlxSmith11** [comment] 2020-03-10 15:18
Hello Ed,

This has not been resolved.  Let me check the latest version k8s.

Thanks,

Alex

**Comment by odinuge** [comment] 2020-05-11 19:48
@bart0sh is correct, you have to check the cgroup on the host and not inside the container. You can look at the e2e test to see how it is verified there (by mounting the host cgroup as a volume): https://github.com/kubernetes/kubernetes/blob/43c56eb4038ee9f6b7275f5aefe3aba6fd5f181b/test/e2e_node/hugepages_test.go#L44-L89.

In case you are wondering if the cgroup enforcement work, you can try to mmap (and use) more huge page memory than allowed by the cgroup inside the pod and verify that the program crashes (but pre allocate more than that on the node). Here is a simple cli tool you can use. https://gist.github.com/odinuge/f018a974d169dd2a84e08316ffd3181f

There is some work on making it possible to inject the size via the downward API, but that is still in progress: https://github.com/kubernetes/kubernetes/pull/86102

/close

**Closed** 2020-05-11 19:49 UTC
Labels: kind/bug, sig/node
