### ISSUE TITLE
integration test TestPersistentVolumeClaimBinder is flaky

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#14145] opened 2015-09-17 23:39 UTC
This test has failed in about 4 out of 50 runs on our new Jenkins build (kubernetes-test-go):
````
persistent_volumes_test.go:108: Expected claim to be bound: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:claim02 GenerateName: Namespace:default SelfLink:/api/v1/namespaces/default/persistentvolumeclaims/claim02 UID:d2e48622-5d62-11e5-96cf-42010af01555 ResourceVersion:165 Generation:0 CreationTimestamp:2015-09-17 10:37:53 -0700 PDT DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[]} Spec:{AccessModes:[ReadOnlyMany ReadWriteOnce ReadWriteMany] Resources:{Limits:map[] Requests:map[storage:{Amount:5000000000.000 Format:DecimalSI}]} VolumeName:} Status:{Phase:Pending AccessModes:[] Capacity:map[]}}
```

Possibly unhelpfully-long full log here (from most recent failure): https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-test-go/52/build-log.txt

@kubernetes/goog-testing

**Comment by ixdy** [comment] 2015-09-17 23:40
Looks like a dupe of #14107, perhaps.

**Comment by ixdy** [comment] 2015-09-17 23:41
cc @markturansky based on git blame

**Comment by markturansky** [comment] 2015-09-18 00:19
Yes dupe of #14107.  I'm investigating.

**Closed by markturansky** 2015-09-18 00:19 UTC
Labels: priority/P2, team/testing

**Comment by saad-ali** [comment] 2015-09-21 22:00
I believe this is a dupe of #14284 not #14107
