### ISSUE TITLE
Support API CREATE with dry run

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#62197] opened 2018-04-06 15:15 UTC
Clients/Controllers need to know how a resource would look like without creating it. It can be changed by admission or defaulting. That's why we need dry run version of that API call to go through all that chain regular resource would have gone, just without storing it to etcd and with avoiding side effects from admission plugins.

Use cases:
 - [DaemonSet needs to know how the Pod's nodeSelector will look like after admission to know which nodes to even target (without creating a real pod as that is unthinkable in every sync pass)](https://github.com/kubernetes/kubernetes/issues/61886#issuecomment-379277543)
 - [kubectl apply and calculating patches](https://github.com/kubernetes/kubernetes/issues/34292)
 - [kubectl --dry-run needs to touch server](https://github.com/kubernetes/kubernetes/issues/11488)

/sig api-machinery
/priority important-longterm

@kubernetes/sig-api-machinery-feature-requests @janetkuo @deads2k @smarterclayton @liggitt @bgrant0607-cc

**Comment by liggitt** [comment] 2018-04-06 15:31
probably a duplicate of https://github.com/kubernetes/kubernetes/issues/11488

**Comment by tnozicka** [comment] 2018-04-09 15:37
@liggitt With the second half of this [comment](https://github.com/kubernetes/kubernetes/issues/11488#issuecomment-295273918)
```
We still need to make dry-run touch the server, or at least decide that we don't want to.
```
I've realized it might be better to have a separate issue making sure this is in the API, no matter what way kubectl goes.

**Comment by lavalamp** [comment] 2018-04-09 16:18
This is already explicitly on the list of items for moving kubectl apply serverside.

IMO 99% of the effort is implementing dry run in the API. We need it for both PUT and POST.

I personally find #11488 a very confusing issue as I don't see too much value in implementing a dry run in kubectl that doesn't tell you what the server is going to do. I still think this is probably a duplicate of something, but I'll leave it open until I run across it.

**Comment by tnozicka** [comment] 2018-07-09 05:08
/remove-lifecycle stale
(I believe this is moving forward as part of the new "apply" work - https://github.com/kubernetes/community/blob/master/keps/0006-apply.md)

**Comment by bgrant0607** [comment] 2018-09-16 18:03
cc @apelisse

**Comment by lavalamp** [comment] 2018-09-17 18:36
Dry run is alpha in the upcoming release.

**Comment by apelisse** [comment] 2018-09-17 18:37
> Dry run is alpha in the upcoming release.

Server-side dry-run should complement the existing client side dry-run, and close this issue as well as 11488.

**Comment by apelisse** [comment] 2019-01-03 23:13
Now beta, I suspect we can close this.

**Closed by apelisse** 2019-01-03 23:13 UTC
Labels: kind/feature, lifecycle/frozen, priority/important-longterm, sig/api-machinery
