### ISSUE TITLE
Connection resets with large payload 

### ISSUE THREAD

**Issue by jasvinder1107** [kubernetes/kubernetes#119887] opened 2023-08-10 15:12 UTC
### What happened?

Team, we are seeing possible regression of

https://github.com/kubernetes/kubernetes/issues/74839

https://github.com/kubernetes/kubernetes/pull/74840

What we are trying to do is transfer a large payload, and we get connection resets intermittently. 

### What did you expect to happen?

The upload should work without failure

### How can we reproduce it (as minimally and precisely as possible)?

In our scenario, long-running servers depict this behavior and **enable the net.netfilter.nf_conntrack_tcp_be_liberal = 1    on nodes fixed the issue for us.**

### Kubernetes version

<details>

```console

/usr/local/bin/kubectl version                         
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-14T18:10:45Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

```console

cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


uname -r
4.15.0-193-generic


```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

 

containerd.io                          1.5.11-1                                        amd64        An open and reliable container runtime

 runc version 1.0.3
commit: v1.0.3-0-gf46b6ba
spec: 1.0.2-dev
go: go1.16.15m1
libseccomp: 2.5.1

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

calico-node -v
v3.24.1

We are using kube-proxy with ipvs.

</details>

**Comment by uablrek** [comment] 2023-08-11 05:51
/sig network

> net.netfilter.nf_conntrack_tcp_be_liberal = 1 on nodes doesn't reproduce the issue anymore

But it has in the past? What has changed?

**Comment by uablrek** [comment] 2023-08-11 06:04
Related https://github.com/kubernetes/kubernetes/issues/117924? Probably not, since net.netfilter.nf_conntrack_tcp_be_liberal = 1 doesn't work, but if something has changed...?

**Comment by jasvinder1107** [comment] 2023-08-11 16:23
@uablrek So setting the net.netfilter.nf_conntrack_tcp_be_liberal = 1 fixed the issue for this case as in original defect.

**Comment by jasvinder1107** [comment] 2023-08-11 16:37
@aojea I apologize i should have put it in the description itself. I have updated it now.
We are using kube-proxy with ipvs. The problematic node has 64 interfaces (This includes calico and Oam interfaces). We jumped from k8 v1.21.11 to k8 1.24.7, so we haven't tested 1.23.

**Comment by jasvinder1107** [comment] 2023-08-11 17:27
I see it is definitely is related  [ https://github.com/kubernetes/kubernetes/issues/117924 ](url) @uablrek . I just confirmed the same issue is there in k8 1.21.11 as well.

**Comment by uablrek** [comment] 2023-08-12 07:28
@jasvinder1107 Can we set this issue as duplicate of https://github.com/kubernetes/kubernetes/issues/117924 then?

You can use net.netfilter.nf_conntrack_tcp_be_liberal=1 as a work-around until it's fixed. A problem as I see it, is that [I can't reproduce the problem](https://github.com/kubernetes/kubernetes/issues/117924#issuecomment-1545793708) which make it hard to verify a PR. On the other hand, the problem is analyzed in an excellent way so it should be possible to fix.

Perhaps you can help by testing a PR?

/cc @aroradaman

**Comment by jasvinder1107** [comment] 2023-08-14 01:26
@uablrek, sure, you can mark this as duplicate. The problem is this is only reproducible in our prod env with servers having high uptime. A simple reboot solves the problem for a few months. It is not easy to reproduce, but let me see if i can tweak conntrack buffers and try to reproduce it early. I will keep you posted on the progress of reproduction.

**Comment by uablrek** [comment] 2023-08-17 16:17
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/117924

**Comment by danwinship** [comment] 2023-08-22 13:30
> enable the net.netfilter.nf_conntrack_tcp_be_liberal = 1 on nodes fixed the issue for us.

If that works for you then that's our recommendation. There's discussion going on in the other issue @uablrek linked to about exactly what rules kubernetes should be creating to try to avoid this problem, but we know that we can't fix all connection reset problems for all kubernetes connections without also potentially breaking some non-kubernetes traffic for some users.

**Comment by danwinship** [comment] 2023-08-22 13:31
/close

dup of https://github.com/kubernetes/kubernetes/issues/117924

**Closed by danwinship** 2023-08-22 13:31 UTC
Labels: kind/bug, sig/network, needs-triage
