### ISSUE TITLE
VersionedParams & API Groups

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16376] opened 2015-10-27 16:52 UTC
Right now, we have the concept packing api query parameters into a struct, converting that to the versioned (serialized wire) format struct, then packing that into URL query parameters. This needs some slight adjustment for API groups.

Options:
1. Change nothing; every group needs its own e.g. ListOptions struct in the internal and external versions.
2. Move common options (e.g. ListOptions) to unversioned.

If we do 2, then we need to modify the code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L414

Options for modifying this code:
1. RESTClient takes a second "options" codec, which takes a struct, returns JSON, which can be converted to query parameters. (must be a second codec because the codec for the body of the request may be binary.)
2. RESTClient takes a second "options" codec, which takes a struct and returns URL query parameters directly.
3. Develop the concept of internal unversioned vs. external unversioned (UGH).

2.1 & 2.2 both have the advantage that RESTClient doesn't need to know about "convertor" at all any more.

2.1 can be done just by reusing our existing codec, which is nice, but 2.2 is probably clearer? 2.3 is confusing. Option 1 is verbose and error prone.

@smarterclayton @krousey @wojtek-t @caesarxuchao please all of you argue about this :)

**Comment by wojtek-t** [comment] 2015-10-27 17:03
From the main two options I definitely vote for "2" - if we have the same struct in 10 different places, adding a new field for example would be a pain.

From the second three options - I definitely don't like 3.

However, I'm not sure if I understand how 2.1/2.2 will work. We definitely want to support "ListOptions" in "extensions" client - I assume that we are leaving ListOptions in "v1" api.
So from this I understand that this "options" codec will be "internal <-> v1" converter.
So do we assume that we will not have any "extensions"-specific options for which we would need to use another codec (something like "DeploymentOptions" in "extensions" api)?

**Comment by caesarxuchao** [comment] 2015-10-27 17:26
> converting that to the versioned (serialized wire) format struct, then packing that into URL query parameters

From the code you pasted, I don't see where the query parameter is serialized, it's just converted to a versioned object and then to set to request's parameters? Did I miss something?

**Comment by krousey** [comment] 2015-10-27 17:40
I like being able to reuse the Options classes. I think maybe everything the RESTClient needs to know about an API group should just be one interface.

```go
type APIGroupCodec interface {
	EncodeObject(runtime.Object) ([]bytes, error)
	DecodeObject([]bytes) (runtime.Object, error)
	EncodeParamaters(unversioned.ListOptions) (url.Values, error)  // or whatever object
}
```

Similar to 2.2, but wrapped up into one interface.

**Comment by smarterclayton** [comment] 2015-10-27 17:41
It's likely that ListOptions and DeleteOptions are going to evolve over
time to have more fields.  At some point in the far future, we may want to
rename a field.  If we move them to unversioned we're giving up on that.
While having a versioned ListOptions per API group seems ugly, saying "we
give up, it's too hard to version this" also seems wrong.

**Comment by smarterclayton** [comment] 2015-10-27 17:44
There are three types of query objects today:

1. Structured objects which are specific to a REST endpoint that definitely
need API stability over time - PodLogOptions, PodExecOptions, etc
2. Structured objects which are tied to our generic API methods (List,
Delete) which probably need API stability over time - ListOptions,
DeleteOptions
3. Structured objects returned by the API for which we probably simply
can't afford to be backward incompatible - Status

I'd say the former should *clearly* be per API group.  The last one is ok
to be unversioned.  The middle one feels closer to the first one than the
last one.

**Comment by wojtek-t** [comment] 2015-10-27 18:08
Thanks for a detailed context Clayton.

 So what I'm trying to say is that we need possibly a different codec for 1. than for 2., which means that we need some mechanism to detect which one we should use.
 In other words, if we replace "PodLogOptions" which sth like "Deployment****Options", the we will need:
- "extensions <-> internal" codec for Deployment****Options
- "v1 <-> internal" codec for ListOptions
 Thus I think the original proposal (at least 2.1) doesn't solve the problem, right?

**Comment by caesarxuchao** [comment] 2015-10-27 18:37
If we make those options unversioned, why do we need a codec? We can just pass the option Object to `queryparams.Convert`.
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L419

I still don't see where we need to *serialize* the options.

**Comment by wojtek-t** [comment] 2015-10-28 08:23
We don't need to serialize them. But I think the problem is that we don't want to make them unversioned, so we need some conversion tools for them.

**Comment by lavalamp** [comment] 2015-10-28 17:06
@krousey I think the interface has to be this if we go that route-- it should work for all option type structs not just ListOptions. (and the server needs the decode, and we share code at the moment)

```go
type APIGroupCodec interface {
    EncodeObject(runtime.Object) ([]bytes, error)
    DecodeObject([]bytes) (runtime.Object, error)
    EncodeParameters(runtime.Object) (url.Values, error)
    DecodeParametersInto(url.Values, runtime.Object) error // "Into" because the particular server object can manufacture an appropriate options object.
}
```

I agree with Clayton's classification, and I think the above interface should handle the first two cases. The third is already handled.

@wojtek-t we currently make a codec per version, so we'd just register the unversioned list/delete options in every codec, and the specific options only in the appropriate codecs.

As far as versioning goes, if we have to make backwards incompatible changes in one of these, we'll have to make a ListOptionsV2 or some such. Also there's nothing keeping us from registering a special ListOptions in the group that needs it, while leaving other groups with the unversioned one.

**Comment by lavalamp** [comment] 2015-10-28 17:08
@caesarxuchao we can't hard code the type because it has to work for ListOptions, DeleteOptions, FooOptions, etc. @krousey and I are talking about compressing the conversion and serialization (to url.Values) into one interface for RESTClient simplicity, and because conversion could be a superfluous step here, so it makes sense to let the codec decide whether or not it's necessary.

**Comment by smarterclayton** [comment] 2015-10-28 18:08
@deads2k and @liggitt if you haven't already been following this

**Comment by wojtek-t** [comment] 2015-10-28 18:09
@lavalamp - so do we want to add "unversioned.ListOptions" and leave existing "v1.ListOptions" as is?

Regarding your interface - I think, creating that interface is just a matter of refactoring (we don't need to create almost any code). The EncodeParameters is already here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L99
and DecodeParametersInto is more-or-less here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L686

**Comment by lavalamp** [comment] 2015-10-28 21:59
@wojtek-t Yes to everything you said.

**Comment by smarterclayton** [comment] 2015-10-29 00:22
I'm still a little cautious about our headlong plunge to making lots of
things unversioned. I really don't want to give up the ability to solve
versioning options and status in the future.

In fact, I'd almost prefer we invent an API version name to represent *all*
unversioned objects and set it "v1".  Returning / using unversioned things
from a versioned API isn't any better than returning two different versions
(regarding @liggitt's point about API groups).  Anything we say has forever
backwards compatibility is still an API version.

On Oct 28, 2015, at 5:59 PM, Daniel Smith <notifications@github.com> wrote:

@wojtek-t <https://github.com/wojtek-t> Yes to everything you said.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16376#issuecomment-152009262>
.

**Comment by lavalamp** [comment] 2015-10-29 01:07
I think the ship has sailed for 1.1, but going forward I'm open to putting
these things in e.g. "common/v1" or something.

**Comment by wojtek-t** [comment] 2015-10-30 13:18
@lavalamp 

Let me ask two more questions, because I'm not sure I understand everything correctly.

1. When we add unversioned ListOptions (and Delete*), we want to register this type in all apis, right?
Does it mean that in v1 API we will have both "v1.ListOptions" and "unversioned.ListOptions"? Is it possible (and is it going to work to have two types with the same name)? I'm afraid methods like "Scheme::NewObject" will not work in that case (or am I missing something)?

2. Once we have "unversioned.ListOptions" - are we going to replace "api.ListOptions" with the "unversionedListOptions" everywhere? [I believe yes, but want to ensure].

**Comment by lavalamp** [comment] 2015-10-30 16:45
> Once we have "unversioned.ListOptions" - are we going to replace "api.ListOptions" with the "unversionedListOptions" everywhere? [I believe yes, but want to ensure].

This would be the plan, and we should be able to do it without breaking wire-format compatibility.

> When we add unversioned ListOptions (and Delete*), we want to register this type in all apis, right?

Maybe. I'd need to review that code again. It might be that we just need to register it once. We only need the double registrations if there's some conversion we want to happen, I think.

> Does it mean that in v1 API we will have both "v1.ListOptions" and "unversioned.ListOptions"?

Presumably only one ListOptions at a time in any given group/version?

> Is it possible (and is it going to work to have two types with the same name)? I'm afraid methods like "Scheme::NewObject" will not work in that case (or am I missing something)?

I think we'll have some plumbing to do to make it work. Kinds should not have to be globally unique, but I think some things will stop working at the moment if they aren't. This is one of the remaining api group cleanups.

**Comment by wojtek-t** [comment] 2015-11-02 15:38
>
    Does it mean that in v1 API we will have both "v1.ListOptions" and "unversioned.ListOptions"?
Presumably only one ListOptions at a time in any given group/version?

That is something that is very misleading in my opinion - this basically means that we have:
-v1.ListOptions in "v1" api group
-unversioned.ListOptions in all other api groups
Which means it's not really unversioned (because we have another version of it)...

<p>
 And one more question regarding AIP of Codecs. We already have a bunch of different Codec interfaces:
-ObjectCodec
-Decoder
-Encoder
-Codec
-ObjectEncoder
-ObjectDecoder
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/interfaces.go

To be honest - introducing one more (or few more) will complicate the situation even more (I spent some time trying to understand the rationale behind having them all, and still I don't fully follow it).
I think we should try to merge some of those, and extend the existing ones with the support for parameters. Personally I vote for extending only "Codec" - what do you think?

**Comment by deads2k** [comment] 2015-11-02 16:09
They serve purposes specific to particular parts of the stack (client, storage, REST, etc), though I think a few have been modified in unusual ways to make APIGroups happy.

 1. `ObjectEncoder` - Provides a way to serialize a `runtime.Object` into a given `GroupVersion`.  This logically allows serialization into any compatible format.  This would work well for client-side transforms.
 1. `Encoder` - Provides a mechanism for encoding to a default set of bytes.  This makes sense when you have an `ObjectEncoder` pinned to a specific `GroupVersion`.  For instance, inside of a `RESTStorage`.
 1. `Decoder` - Provides a way to deserialize bytes into a `runtime.Object`.  The pinned version methods seem to have grown organically. `DecodeIntoWithSpeicfiiedVersionKind` as a for instance.
 1. `ObjectCodec` - Provides a mechanism for serialization/deserializing general `runtime.Object` to and from given `GroupVersions`
 1. `Codec` - Provides general deserialization methods, but specific `Encoding` methods.  Useful for cases where you want to accept everything you can and guarantee specific returns.

**Comment by lavalamp** [comment] 2015-11-02 22:17
> That is something that is very misleading in my opinion - this basically means that we have:
> -v1.ListOptions in "v1" api group
> -unversioned.ListOptions in all other api groups

No-- I think I said earlier, I think we can remove it from v1 and replace it with unversioned.ListOptions without changing the wire format. I agree we ideally won't do the confusing thing you just described, but if it's necessary in a transitional phase, I don't mind it.

I think we should regularize our interfaces. `Codec` should be the combination of `Encoder` and `Decoder`. We should remove all notion of version from the Codec *interfaces*; that can be part of the implementation of the Codec if necessary.

**Comment by wojtek-t** [comment] 2015-11-03 11:39
>>
That is something that is very misleading in my opinion - this basically means that we have:
-v1.ListOptions in "v1" api group
-unversioned.ListOptions in all other api groups
>
No-- I think I said earlier, I think we can remove it from v1 and replace it with unversioned.ListOptions without changing the wire format. I agree we ideally won't do the confusing thing you just described, but if it's necessary in a transitional phase, I don't mind it.

Then I must have misunderstood you. The above explanation SGTM

**Comment by wojtek-t** [comment] 2015-11-03 13:31
@lavalamp 
Sorry for continuous questions here, but one more.

Once we add ListOptions to "unversioned" they should be compatible with "v1" - this means that field/label selectors will be strings there.
However, in "api.ListOptions" field/label selectors are "fields.Selector" and "labels.Selector" respectively which is pretty convenient. Does it mean that after this change we will have to parse those selectors every time we will want to use them or is there anything else that we can do here?

**Comment by lavalamp** [comment] 2015-11-03 20:53
@wojtek-t I think the idea is, if we're encoding directly to url.Values, we can keep the convenient selector types, and do the necessary plumbing in the en/decoding functions.

**Comment by lavalamp** [comment] 2015-11-03 20:54
@wojtek-t It's possible that adding a SetJSON-but-for-url.Values method on the selector might work, I haven't investigated.

**Comment by wojtek-t** [comment] 2015-11-05 14:57
@lavalamp - I agree we can do any encoding there. But I though, that we would like to have "unversioned.ListOptions" compatible with "v1.ListOptions", and thus we need to have the same types for the same fields - which is string for selectors. Or am I missing something?

**Comment by lavalamp** [comment] 2015-11-05 22:09
@wojtek-t I think as long as ListOptions is only ever encoded into url.Params and not to json, it should be OK to change that detail?

**Comment by ash2k** [comment] 2017-01-12 13:51
I'm sorry if this is not the right place to comment, but it seems relevant.
I tried to use `cache.NewListWatchFromClient()` to construct an Informer using `cache.NewSharedInformer()` but it does not work:
```
E0113 00:39:44.993647   60634 reflector.go:199] github.com/atlassian/smith/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *smith.Template: v1.ListOptions is not suitable for converting to "smith.atlassian.com/v1"
```
Debugging shows that global `api.ParameterCodec` is used to encode `v1.ListOptions` passed to the `VersionedParams()` method. This global `ParameterCodec` is constructed using global `api.Scheme` which does not know about my custom resource type and its group-version which was used to construct the client and is used by `VersionedParams` later. I registered the type in a freshly created `Scheme` because mutating global objects is not good and it causes a data race in my integration tests.
Why not make a value of type `runtime.ParameterCodec` part of the client just like other codecs? That way it could be used to encode the versioned parameter passed into the method.
I'm wondering what is the value of being able to pass `runtime.ParameterCodec` into each invocation of `VersionedParams()`?

**Comment by caesarxuchao** [comment] 2017-03-14 21:16
I think we can either update the signature of `cache.NewListWatchFromClient()` to allow passing in a custom parameter codec, or build the parameter codec into the RESTClient.

**Comment by seh** [comment] 2017-05-05 15:04
@caesarxuchao, have you thought more about which way you'll go here (change `cache.NewListWatchFromClient`, integrate the codec into `RESTClient`, or something else per @sttts's [suggestion](https://github.com/kubernetes/kubernetes/pull/43027/files#r106098606))?

**Comment by caesarxuchao** [comment] 2017-05-05 19:29
@ash2k @seh i've been dealing with the registration code ofthen these days, so a new thought: will add the following init func solve the problem?
```go
init() {
metav1.AddToGroupVersion(your_scheme or global_scheme, your_group_version)
}
```
(similar to this [line](metav1.AddToGroupVersion(scheme, SchemeGroupVersion))

**Comment by ash2k** [comment] 2017-05-06 00:06
@caesarxuchao I don't know what has changed, but I've been using `cache.NewListWatchFromClient()` without any issues for a while now.
See https://github.com/atlassian/smith/blob/6009186895464eada1f9adaf1bb5bd50bb7a5610/pkg/app/app.go#L173

However, lets imagine it does not work. I don't see how moving `metav1.AddToGroupVersion()` into an `init()` function will solve anything (see my comment above)? I already [call `metav1.AddToGroupVersion()`](https://github.com/atlassian/smith/blob/6009186895464eada1f9adaf1bb5bd50bb7a5610/types.go#L71) when I construct [full scheme](https://github.com/atlassian/smith/blob/6009186895464eada1f9adaf1bb5bd50bb7a5610/pkg/resources/client.go#L33) with all the groups and types I need so I don't see what it will change.

**Comment by seh** [comment] 2017-05-06 00:22
I'm just watching this discussion with interest, having been adapting the various TPR examples out there for my own uses.

I don't like having to also now juggle a `runtime.Scheme` and a `rest.Config` in order to build a `rest.RESTClient`; that need doesn't arise in the most authoritative example, because [it operates on the global `scheme.Scheme` value](https://github.com/kubernetes/client-go/blob/master/examples/third-party-resources/main.go#L156-L166). Hence I was hopeful that you had an approach here that would reduce the number of separate objects involved in getting a TPR client ready for use.

**Comment by caesarxuchao** [comment] 2017-05-08 21:09
@seh there is a PR updating the tpr example in client-go, and in it, it constructs its own `scheme`: https://github.com/kubernetes/kubernetes/pull/45463/files#diff-ddfc038ea1ea8715b20f2e4b811f334eR29

I think constructing a scheme is necessary, given our current apimachinery.

**Comment by caesarxuchao** [comment] 2017-05-08 21:21
Sorry @seh @ash2k let me check the parameter codec code again, i think the codec had evolved since i last checked. I'll type another comment later.

**Comment by caesarxuchao** [comment] 2017-05-08 22:24
@seh i don't know what changes fixes your code. I debugged the code a little, it looks like our apimachinery is very tolerant for "Unversioned Kind". The ListOptions is registered as "unversioned", thus there is no error. The related code is [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L483).

The ListWatcher generated by NewListWatherFromClient [always uses](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/listwatch.go#L64) the metav1.ParameterCodec. A user doesn't need to register the ListOptions, that parameterCodec will just work. So there is no bug that requires immediate fix.

In the long run, i think the parametercodec should be a field of the client, and user should be able to supply it via the config, like how a user would supply the codec. And if the config doesn't set the parametercodec, the client's construction function could use the [scheme.ParameterCodec](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/kubernetes/scheme/register.go#L46) by default.

**Comment by seh** [comment] 2017-05-15 15:33
Thank you for responding, @caesarxuchao. I was out on vacation for a week and am back catching up today.

I'm not sure whether my complaint about the need to manage a separate `runtime.Scheme` remains valid or not, given that you revised [your initial statement here](https://github.com/kubernetes/kubernetes/issues/16376#issuecomment-299991729).

In my application, I have a `rest.RESTClient` in use for things like watching namespaces. I also need to watch and read a few TPRs. Following the examples out there, they make it seem as though I need a _separate_ `rest.RESTClient` to deal with those TPRs, but I'm not sure if that's true. Would it be acceptable to use the same TPR-enabled `rest.RESTClient` instance for all of my Kubernetes resource access?

Also, what's your current thinking on whether we really need a special `NewListWatcherFromClient` function that accepts a `runtime.Scheme` parameter? It doesn't look good for the canonical example to involve that much duplicated code.

**Comment by sttts** [comment] 2017-05-15 15:57
@seh we merged a complete TPR example in client-go last week, might be helpful: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/third-party-resources.

**Comment by seh** [comment] 2017-05-15 17:08
Thanks. I'll study that one today, and rewrite my code again to better match the latest and greatest. This is quite a ride.

**Comment by caesarxuchao** [comment] 2017-05-15 17:13
@seh the latest trp example still constructs it's own [scheme](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/third-party-resources/client/client.go#L28-L29). But if you have an existing scheme, you can call `tprv1.AddToScheme` on the existing scheme. Note that you need to move the call to a init() function to avoid race. This way you'll have a scheme that knows all the resources, based on this scheme, i think you can build a RESTClient for tpr and k8s resources.

> Also, what's your current thinking on whether we really need a special NewListWatcherFromClient function that accepts a runtime.Scheme parameter? 

No changes required here. The original issue was fixed.

**Comment by seh** [comment] 2017-05-16 12:47
@caesarxuchao, speaking of `init` functions, do you know why [@nilebox's example registers the TPR types on the same scheme twice](https://github.com/kubernetes/kubernetes/commit/a6c97715ed7e24581dd9a02a256d57e56b70ac44#commitcomment-22146536)?

**Closed** 2018-02-22 12:20 UTC
Labels: lifecycle/rotten, priority/important-soon, sig/api-machinery
