### ISSUE TITLE
external etcd cluster restarting and make api server crashed

### ISSUE THREAD

**Issue by ajizkai** [kubernetes/kubernetes#91375] opened 2020-05-23 06:17 UTC
## Versions

**kubeadm version** (use `kubeadm version`): v 1.16.10-00

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.16.10-00
- **Cloud provider or hardware configuration**: openstack instance over juju and maas
- **OS** (e.g. from /etc/os-release): ubuntu xenial
- **Kernel** (e.g. `uname -a`): Linux devops-node 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
i have 3 kube master nodes and 3 etcd nodes, im using kubernetes version 1.16., sometimes my etcd cluster restart their static pods, and it make my kube-apiserver crashed, 

## this is my log
` {"log":"W0523 05:56:42.026354       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.5.5.216:2379 0  \u003cnil\u003e}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.5.5.216:2379: connect: connection refused\". Reconnecting...\n","stream":"stderr","time":"2020-05-23T05:56:42.026699045Z"}
{"log":"W0523 05:56:42.089891       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.5.5.216:2379 0  \u003cnil\u003e}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.5.5.216:2379: connect: connection refused\". Reconnecting...\n","stream":"stderr","time":"2020-05-23T05:56:42.090372823Z"}
{"log":"E0523 05:56:42.115445       1 status.go:71] apiserver received an error that is not an metav1.Status: \u0026errors.errorString{s:\"context canceled\"}\n","stream":"stderr","time":"2020-05-23T05:56:42.115983559Z"}
{"log":"E0523 05:56:42.115544       1 status.go:71] apiserver received an error that is not an metav1.Status: \u0026errors.errorString{s:\"context canceled\"}\n","stream":"stderr","time":"2020-05-23T05:56:42.116037201Z"}
{"log":"I0523 05:56:42.115797       1 trace.go:116] Trace[1597480739]: \"Get\" url:/api/v1/namespaces/kube-system/pods/kube-apiserver-node-3 (started: 2020-05-23 05:56:36.182165795 +0000 UTC m=+294.506473075) (total time: 5.93359523s):\n","stream":"stderr","time":"2020-05-23T05:56:42.116051223Z"}
{"log":"Trace[1597480739]: [5.93359523s] [5.933581982s] END\n","stream":"stderr","time":"2020-05-23T05:56:42.116063425Z"}
{"log":"I0523 05:56:42.117767       1 trace.go:116] Trace[1802591797]: \"Get\" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/node-3 (started: 2020-05-23 05:56:36.183986009 +0000 UTC m=+294.508293278) (total time: 5.933747404s):\n","stream":"stderr","time":"2020-05-23T05:56:42.118100501Z"}
{"log":"Trace[1802591797]: [5.933747404s] [5.933705316s] END\n","stream":"stderr","time":"2020-05-23T05:56:42.129726603Z" `

ndd my kube-apiserver pod ended, it make me cant access kubernetes for a while
## else 
- im using ha proxy as api server loadbalancer, which it only for api server
- etcd cluster accessed by direct ip from api server
- sorry for my bad english T_T
## thanks everyone

**Comment by neolit123** [comment] 2020-05-23 19:37
duplicate of:
https://github.com/kubernetes/kubernetes/issues/65062

/close

**Closed** 2020-05-23 19:37 UTC
Labels: kind/bug, sig/api-machinery
