### ISSUE TITLE
[Flaky test] ci-kubernetes-unit

### ISSUE THREAD

**Issue by Nivedita-coder** [kubernetes/kubernetes#110962] opened 2022-07-05 14:18 UTC
### Which jobs are flaking?

release-master-blocking

- ci-kubernetes-unit

### Which tests are flaking?

- ci-kubernetes-unit.Overall
- k8s.io/kubernetes/pkg/kubelet/nodeshutdown: TestLocalStorage
-  k8s.io/kubernetes/pkg/kubelet/nodeshutdown: TestFeatureEnabled
-  k8s.io/kubernetes/pkg/schedular/framework/plugins/volumebinding.TestBindPodVolumes
- k8s.io/kubernetes/pkg/schedular/framework/plugins/volumebinding.TestBindPodVolumes/binding-static-pv-succeeds-after-time

### Since when has it been flaking?

07-04 22:51 EEST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

`{Failed  === CONT  
    testing.go:1312: race detected during execution of test
FAIL
FAIL	k8s.io/kubernetes/pkg/kubelet/nodeshutdown	2.384s
}`

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by MadhavJivrajani** [comment] 2022-07-07 08:04
@pohly maybe you can help provide insights here (at least for the `nodeshutdown` tests since they are related to race conditions due to logging)!

Logs with details about the race: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1544926366053437440 

Seems like the race arises due to `t` being passed to and used for receiving logs here:
https://github.com/kubernetes/kubernetes/blob/2a017f94bcf8d04cbbbbdc6695bcf74273d630ed/vendor/k8s.io/klog/v2/ktesting/setup.go#L43

Read happens here:
https://github.com/golang/go/blob/3a7cec27738c51347f4e5a466410a0b2089391b7/src/testing/testing.go#L882

Write:
https://github.com/golang/go/blob/3a7cec27738c51347f4e5a466410a0b2089391b7/src/testing/testing.go#L1424-L1426

**Comment by pohly** [comment] 2022-07-07 10:35
This is a dupe of https://github.com/kubernetes/kubernetes/issues/110854. A revert [is pending](https://github.com/kubernetes/kubernetes/pull/110869) as a stop-gap solution, but I also expect an updated klog which is [more resilient against leaked goroutines](https://github.com/kubernetes/klog/pull/337) (the actual problem) soon.

**Comment by shuheiktgw** [comment] 2022-07-07 23:41
Hello @pohly 👋  I'm a 1.25 CI Signal Shadow and would you let us know if this issue should be a blocker for the 1.25.0-alpha.3 release? I believe this is not a blocker but just in case.

**Comment by pohly** [comment] 2022-07-08 06:23
The klog update went in, the race in the logging path should be gone now. The kubelet shutdown test still has other data races, but they don't seem to occur in the CI.

**Comment by Nivedita-coder** [comment] 2022-07-21 12:32
job is passing :)
/close

**Closed** 2022-07-21 12:32 UTC
Labels: kind/flake, sig/testing, triage/accepted
