### ISSUE TITLE
nodes can not auto recover from OutOfDisk. 

### ISSUE THREAD

**Issue by minjs** [kubernetes/kubernetes#29645] opened 2016-07-26 22:57 UTC
3 of my 5 nodes hit the OutOfDisk in 2 months ago. And then, those 3 nodes can not be used even the disk usage is dropped. I have to remove the node from cluster and restart the kubelet on that disk. 

"conditions":[{"type":"Ready","status":"True","lastHeartbeatTime":"2016-07-26T22:50:53Z","lastTransitionTime":"2016-06-14T21:25:15Z","reason":"KubeletReady","message":"kubelet is posting ready status"},{"type":"OutOfDisk","status":"Unknown","lastHeartbeatTime":"2016-05-16T20:52:46Z","lastTransitionTime":"2016-06-14T21:24:49Z","reason":"NodeStatusNeverUpdated","message":"Kubelet never posted node status."}]

**Comment by dchen1107** [comment] 2016-07-27 22:29
@minjs Can you run the following commands and copy & paste the output here:

* docker info
* kubelet --version
* kubectl describe nodes <node-id>

**Comment by bprashanth** [comment] 2016-07-27 22:39
I'm going to guess it's logs. If that's the case we should logrotate more furiously. I can double check the logrotate config. 

We should also partition disk better (i.e put docker logs on a different partition etc). 

I think if we hit the point where root disk fills up, for whatever reason, all bets are off. We should protect the node from this condition in the first place.

**Comment by dchen1107** [comment] 2016-07-27 23:34
@bprashanth It is very possible caused by the logs. But we don't know the user's running environment yet. We can partition disk better for GKE / GCE users by default, but we cannot have the full control for the users who build the cluster from the scratch.

Also in the initial report, the user mentioned that the disk usage is dropped, but node is not recovered. From snippet he attached, you can see that disk status is Unknown, not True or False. Looks like disk account is not work properly.

**Comment by bprashanth** [comment] 2016-07-27 23:38
My point is that all sorts of unnecessary things can happen if root disk is full for some period of time. We can't guarantee recovery. We ran into issues where DNS will break because we overwrite write /etc/resolv.conf, even if root disk frees up later, we wont fix the broken resolv.conf for at least 24h.

**Comment by minjs** [comment] 2016-07-28 00:11
kubectl describe nodes.... I have to say I already remove/add node and restarted kubelet. 

Name:			min-server004
Labels:			kubernetes.io/hostname=min-server004
CreationTimestamp:	Tue, 26 Jul 2016 15:50:46 -0700
Phase:			
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason		Message
  ----		------	-----------------			------------------			------		-------
  Ready 	True 	Wed, 27 Jul 2016 17:09:42 -0700 	Tue, 26 Jul 2016 15:50:46 -0700 	KubeletReady 	kubelet is posting ready status
Addresses:	172.16.10.34,172.16.10.34
Capacity:
 pods:		40
 cpu:		2
 memory:	3882704Ki
System Info:
 Machine ID:			f5178f4faf494cf69488c484b4920da6
 System UUID:			564DFFEF-85E3-BCD3-FD03-EC94E11BFB0B
 Boot ID:			0edb3503-2c4c-48c7-b6cc-270f941fbc64
 Kernel Version:		3.10.0-327.13.1.el7.x86_64
 OS Image:			CentOS Linux 7 (Core)
 Container Runtime Version:	docker://1.9.1
 Kubelet Version:		v1.2.0
 Kube-Proxy Version:		v1.2.0
ExternalID:			min-server004
Non-terminated Pods:		(0 in total)
  Namespace			Name		CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----		------------	----------	---------------	-------------
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  0 (0%)	0 (0%)		0 (0%)		0 (0%)
No events.

W0727 17:09:51.822669    7859 request.go:627] Throttling request took 148.604255ms, request: GET:http://localhost:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dmin-server005%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded
W0727 17:09:52.022666    7859 request.go:627] Throttling request took 197.118442ms, request: GET:http://localhost:8080/api/v1/events?fieldSelector=involvedObject.kind%3DNode%2CinvolvedObject.name%3Dmin-server005%2CinvolvedObject.namespace%3D%2CinvolvedObject.uid%3Dmin-server005

**Comment by minjs** [comment] 2016-07-28 00:12
[root@min-server004 ~]# kubelet --version=true
Kubernetes v1.2.0
[root@min-server004 ~]# docker info
Containers: 83
Images: 96
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-50657941-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.656 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.722 GB
 Metadata Space Used: 16.39 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: min-server004.pdlab.local
ID: 2543:TKP5:GYY4:BV4R:JRFM:5OJC:IRJK:V53S:I42J:WUGK:DBNU:JJ7N
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by bprashanth** [comment] 2016-07-28 01:11
fyi https://github.com/kubernetes/kubernetes/issues/29715 for logs

**Comment by minjs** [comment] 2016-07-28 23:42
I hit this again. All of my 5 nodes out of disk. I have 5 nodes, each has about 17GB disk size. 
I created 4 pods, each pod have 6 containers. I believe when I created the 5th pod, I hit the issue. 
Then I remove the first 4 pods.  But the 5th pod can not be created anyway. 

What is the minimum disk size required?  when I remove the first 4 pods, why the node conditions are not updated?





Name:			min-server002
Labels:			kubernetes.io/hostname=min-server002
CreationTimestamp:	Mon, 16 May 2016 13:41:12 -0700
Phase:			
Conditions:
  Type		Status		LastHeartbeatTime			LastTransitionTime			Reason			Message
  ----		------		-----------------			------------------			------			-------
  Ready 	True 		Thu, 28 Jul 2016 16:33:50 -0700 	Thu, 28 Jul 2016 14:26:23 -0700 	KubeletReady 		kubelet is posting ready status
  OutOfDisk 	Unknown 	Mon, 16 May 2016 13:41:12 -0700 	Thu, 28 Jul 2016 14:25:34 -0700 	NodeStatusNeverUpdated 	Kubelet never posted node status.
Addresses:	172.16.10.32,172.16.10.32
Capacity:
 cpu:		2
 memory:	1884388Ki
 pods:		40
System Info:
 Machine ID:			f5178f4faf494cf69488c484b4920da6
 System UUID:			564DA329-ED70-AF80-1726-FCC959CAFBC2
 Boot ID:			c6105c7b-bea8-4acf-b32f-2dd558945471
 Kernel Version:		3.10.0-327.13.1.el7.x86_64
 OS Image:			CentOS Linux 7 (Core)
 Container Runtime Version:	docker://1.9.1
 Kubelet Version:		v1.2.0
 Kube-Proxy Version:		v1.2.0
ExternalID:			min-server002
Non-terminated Pods:		(0 in total)
  Namespace			Name		CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----		------------	----------	---------------	-------------
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  0 (0%)	0 (0%)		0 (0%)		0 (0%)
No events.

**Comment by bprashanth** [comment] 2016-07-29 00:20
@minjs can you please figure out what's eating your disk? 
You can check if it's container logs by running du within /var/lib/docker/containers/*/*-json.log

**Comment by minjs** [comment] 2016-07-29 00:59
It might my application log. But I was expecting when I remove the other pods, the disk usage is low.  Should kubernetes recover from that condition?

**Comment by bprashanth** [comment] 2016-07-29 01:06
yeah it should, but the issue is that currently logs are on the root partition, and all sorts of bad things can happen if root fills up that are outside the scope of kubernetes. To prevent root from filling up we can logrotate more often (https://github.com/kubernetes/kubernetes/issues/29715) or partition better (https://github.com/kubernetes/kubernetes/issues/29762).

If you get into a state where say, your root is 90% full, and logrotate runs but doesn't have enough disk to complete the rotation, the disk will remain full, because kubernetes *will not* delete your container logs.

If the container logs eventually get rotated somehow, thereby freeing up disk, I'd be interested in seeing your /var/log/kern.log, /var/log/kubelet.log and the output of `df -kh` and `du -sh`.

**Comment by minjs** [comment] 2016-07-29 01:42
The reason I mentioned it might my application log is that soon I remove the pods, the disk usage goes low. My application logs are store in the pod empty dir.

**Comment by minjs** [comment] 2016-07-29 01:46
The pods life time is pretty shot and my don't write much info to the std, which is container log file on the host.

**Comment by bprashanth** [comment] 2016-07-29 01:55
Yeah emptydir should get purged when the pod is deleted, is the dir still lying around? you can find it in `/var/lib/kubelet/pods/*`. Please also upload your kubelet logs.

**Closed** 2018-02-14 17:17 UTC
Labels: kind/support, lifecycle/rotten, sig/node
