### ISSUE TITLE
[StructuredAuthenticationConfig] Wire CEL functions to authn config

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#119235] opened 2023-07-11 18:29 UTC
/sig auth
/assign
/triage accepted

**Comment by zelenushechka** [comment] 2023-10-15 14:36
Hello @aramase ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by zelenushechka** [comment] 2023-10-27 08:45
Hello @aramase. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and I want to ensure that each PR has a chance to be merged and issues can be addressed.
Is this issue still targeting the 1.29 release?

**Closed** 2023-10-31 23:33 UTC
Labels: sig/auth, triage/accepted
