### ISSUE TITLE
Write readNetworkingV1NamespacedIngressStatus test+promote - +1 endpoint coverage

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#93035] opened 2020-07-13 18:56 UTC
# Progress <code>[1/6]</code>

-   [X] Test in Ginkgo : [ingress.go](https://github.com/ii/kubernetes/blob/fix-ingress-status/test/e2e/network/ingress.go#L1145-L1151)
-   [X] test approval issue : [kubernetes/kubernetes#93035](https://github.com/kubernetes/kubernetes/issues/93035)
-   [X] test pr : [kuberenetes/kubernetes#93038](https://github.com/kubernetes/kubernetes/pull/93038)
-   [ ] two weeks soak start date : testgrid-link
-   [ ] two weeks soak end date :
-   [ ] test promotion pr : kubernetes/kubernetes#?

# Identifying an untested feature Using APISnoop.
It was picked up in APISnoop that an untested endpoint was promoted from Beta to GA.
PR [#91996](https://github.com/kubernetes/kubernetes/pull/91996) ingress: promote CRUD API tests for v1 to conformance covered the Ingress life cycle tests, but **readNetworkingV1NamespacedIngressStatus**  was missed.

According to this APIsnoop **readNetworkingV1NamespacedIngressStatus** endpoint is untested.

# The test updated in Ingress.go

## Test the functionality in Ginko

		ginkgo.By("get /status")
		ingResource := schema.GroupVersionResource{Group: "networking.k8s.io", Version: ingVersion, Resource: "ingresses"}
		gottenStatus, err := f.DynamicClient.Resource(ingResource).Namespace(ns).Get(context.TODO(), createdIngress.Name, metav1.GetOptions{}, "status")
		framework.ExpectNoError(err)
		statusUID, _, err := unstructured.NestedFieldCopy(gottenStatus.Object, "metadata", "uid")
		framework.ExpectNoError(err)
		framework.ExpectEqual(string(createdIngress.UID), statusUID, fmt.Sprintf("createdIngress.UID: %v expected to match statusUID: %v ", createdIngress.UID, statusUID))
'''
# Verifying increase in coverage

List endpoints hit by the test:
readNetworkingV1NamespacedIngressStatus endpoint

# Final notes

If this test get merged, ****test coverage will go up by 1 point****

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture
/area conformance

**Comment by cmluciano** [comment] 2020-07-13 20:13
Duplicate of #92199

**Comment by Riaankl** [comment] 2020-07-19 16:12
/reopen
#93038  Merged
/assign @heyste
Ready for creation of Promotion PR

**Comment by Riaankl** [comment] 2020-07-19 22:37
Code change was a bug fix in a Merged conformance test. 
The correction should not require Promotion.
/close

**Closed** 2020-07-19 22:37 UTC
Labels: area/conformance, sig/architecture, sig/testing
