### ISSUE TITLE
bazel not working

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#40876] opened 2017-02-02 18:29 UTC
`update-bazel.sh`  and `verify-bazel.sh` seems not working.
```
$ hack/update-bazel.sh 
# cd .; git clone https://gopkg.in/mikedanese/gazel.v13 /usr/local/google/home/mengqiy/work/golang/src/gopkg.in/mikedanese/gazel.v13
Cloning into '/usr/local/google/home/mengqiy/work/golang/src/gopkg.in/mikedanese/gazel.v13'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/mikedanese/gazel.v13/gazel: exit status 128
!!! Error in hack/update-bazel.sh:23
  Error in hack/update-bazel.sh:23. 'go get -u gopkg.in/mikedanese/gazel.v13/gazel' exited with status 1
Call stack:
  1: hack/update-bazel.sh:23 main(...)
```

@mikedanese @ixdy

**Comment by mikedanese** [comment] 2017-02-02 18:50
Duplicate of #39583, fixed by #40875.

Run `git config --global http.https://gopkg.in.followRedirects true` to workaround

**Closed by mikedanese** 2017-02-02 18:50 UTC
