### ISSUE TITLE
Behavior change between etcd v2 and v3 watch clients

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#36545] opened 2016-11-09 22:53 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): etcd watcher

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): HEAD / commit 8b5264e

**Environment**:
- **Cloud provider or hardware configuration**: local VM
- **OS** (e.g. from /etc/os-release): Fedora 24
- **Kernel** (e.g. `uname -a`): Linux localhost.localdomain 4.7.7-200.fc24.x86_64 #1 SMP Sat Oct 8 00:21:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

If you do a watch from resource version "0" using etcd_watcher.go (the etcd v2 client code), it initially performs a get of the key in question and returns Added or Modified events, based on a comparison of each node's createdIndex and modifiedIndex. This works all the time.

If you do a watch from resource version "0" using watcher.go (the etcd v3 client code), it attempts to get `kv.modifiedIndex - 1` for each kv returned, in an attempt to provide both the previous and current versions of each kv/object. This works as long as `kv.modifiedIndex - 1` has not been compacted. If compaction has occurred, the initial `sync()` will fail, and it's not possible to watch from "0"' for this particular key.

**What you expected to happen**:

Either:

1. The v3 watcher should not change the behavior from the v2 watcher; namely, it should not attempt to get the previous revision of each object and instead just return the current version as a `watch.Added` event
2. We agree that it's ok to change the behavior, and in the event that the database has been compacted and the previous revision of an object cannot be retrieved, that object is sent as a `watch.Added` event instead of `watch.Modified`.

**How to reproduce it** (as minimally and precisely as possible): I'm working on a unit test and fix.

**Anything else do we need to know**:

cc @wojtek-t @hongchaodeng @xiang90 @smarterclayton @liggitt @deads2k @derekwaynecarr @sttts

**Comment by xiang90** [comment] 2016-11-09 22:57
@ncdc I will take a look and get back to you tomorrow.

**Comment by xiang90** [comment] 2016-11-09 22:57
If you have a pr ready, just assign to me or hongchao.

**Comment by ncdc** [comment] 2016-11-09 22:57
I'll have one tonight hopefully

**Comment by ncdc** [comment] 2016-11-09 22:57
Although it depends on if we pick option 1 or 2

**Comment by xiang90** [comment] 2016-11-09 23:21
@ncdc 

The behavior of etcd2 is not technically correct. Watch from 0 and `Now` will give different results if watch from 0 always return "Added" even if 0 and `Now` should be the same. But we do not really have defined what does "0" mean in the interface.

Also for etcd3, we cannot guarantee that watch can always return the previous value. Option 1 seems to be easier to achieve. If we do option2, then we will have a "Modified" event without having previous value. I am not sure if that is acceptable or not.

**Comment by liggitt** [comment] 2016-11-09 23:29
I prefer option 1 as well, for kube API consistency.

**Comment by hongchaodeng** [comment] 2016-11-10 06:38
Just give an update here: I talked with @liggitt on this a bit. We agreed that the behavior should be the same as etcd2 watcher. 

Of course the API seems non-standard right now. We need to rewrite it in better API once this gets more stable.

**Comment by liggitt** [comment] 2016-11-10 06:39
Actually, it looks like the event type is a red herring. The etcd2 client has always set Added/Modified based on the equality/inequality of the node's createdindex/modifiedindex:
```
action := watch.Added
if res.Node.ModifiedIndex != res.Node.CreatedIndex {
	action = watch.Modified
}
```

the watch cache sets the event type to Added when watching from resourceVersion=0
```
result[i] = watchCacheEvent{
	Type:            watch.Added,
	Object:          elem.Object,
	Key:             elem.Key,
	ResourceVersion: w.resourceVersion,
}
```

the issue is that etcd3 is still doing a Get() of the previous revision of every KeyValue when watching from 0:
https://github.com/liggitt/kubernetes/blob/47012dc339e84529629b9595c183dd37f4c249be/pkg/storage/etcd3/watcher.go#L161:
```
for _, kv := range getResp.Kvs {
	prevResp, err := wc.watcher.client.Get(wc.ctx, string(kv.Key), clientv3.WithRev(kv.ModRevision-1), clientv3.WithSerializable())
	if err != nil {
		return err
	}
	var prevVal []byte
	if len(prevResp.Kvs) > 0 {
		prevVal = prevResp.Kvs[0].Value
	}
	wc.sendEvent(parseKV(kv, prevVal))
}
```

That can fail if ModRevision == ModCreation, or if the Get returns an ErrCompacted (it also seems like a potential performance problem to fan out N Get() calls during a single watch establishment

**Comment by liggitt** [comment] 2016-11-10 06:43
potential fix in https://github.com/kubernetes/kubernetes/pull/36561

**Comment by xiang90** [comment] 2016-11-10 06:59
@liggitt @hongchaodeng @ncdc 

I pretty dislike the fact that:

1. watch on 0 will first do a sync and then start to watch

2. we are forced to return prev value for all modification events

watch on 0 should just start watch from the latest revision. recovery the initial state (thus the sync or the initial get) should be a separate operation. But, yea, I guess we need to preserve this at least for now.

**Comment by wojtek-t** [comment] 2016-11-10 15:44
@xiang90 - yes, I think there is general agreement for it, though we can't change that in v1 API. There is more-than-1-year old issue for that:
https://github.com/kubernetes/kubernetes/issues/13969

**Comment by hongchaodeng** [comment] 2016-11-11 07:28
> That can fail if ModRevision == ModCreation

For this case, it won't fail. It returns empty result.

**Closed** 2016-11-12 06:33 UTC
Labels: component/apiserver, kind/bug, team/CSI-API Machinery SIG
