### ISSUE TITLE
Qual and deploy etcd 2.2 server code

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13884] opened 2015-09-11 23:54 UTC
It was officially released today; details here:
https://coreos.com/blog/etcd-2.2/

A few weeks ago we said "We should start testing it for potential inclusion in the 1.1 release":
https://groups.google.com/d/msg/google-containers/ans64vg7lhg/qfqCxQaZBQAJ

Are we still planning to do that? I couldn't find an issue or any work on it.

@bgrant0607 @brendandburns @dchen1107 @thockin @lavalamp

**Comment by lavalamp** [comment] 2015-09-12 00:08
@wojtek-t Do I recall you saying you wanted to investigate the new client from this?

**Comment by bgrant0607** [comment] 2015-09-12 04:30
cc @timothysc

**Comment by timothysc** [comment] 2015-09-12 13:57
#11962 is in flight atm, and uncovered some inconsistencies in the new api that they recently fixed.  I'll try to get the PR cleaned up by Monday.

**Comment by wojtek-t** [comment] 2015-09-14 07:06
As wrote above, @timothysc is currently working on it.

**Comment by timothysc** [comment] 2015-09-15 02:42
Two notes: 
1 - the amount of change is much greater then I would feel comfortable in making with such a short amount of bake time.  The thread safety issue has pretty much been passed off to the client to pass the context through to the library.  Meaning we need to change the storage layer to pass context through from the caller.  

2. This is pretty much a dupe of #11962 - recommend close and focus there, as it has the references to the history.

**Comment by davidopp** [comment] 2015-09-15 07:53
> This is pretty much a dupe of #11962 - recommend close and focus there, as it has the references to the history.

Maybe I'm misreading, but that issue seems to strictly be about the client, not the server. Should we be treating them separately? If so we could make this issue be just about the server.

**Comment by wojtek-t** [comment] 2015-09-15 07:58
IIUC, we should first change the client and only then switch to the new server. I agree with @davidopp that we should explicitly change this issue to be about the server (and make it dependent on the other issue).

**Comment by timothysc** [comment] 2015-09-15 12:47
+1 to rebrand on server.

**Comment by brendandburns** [comment] 2015-09-15 17:35
renamed to be explicitly about etcd 2.2. server

**Comment by bgrant0607** [comment] 2015-10-05 22:50
Have seen no PRs. Punting to 1.2.

**Comment by davidopp** [comment] 2015-12-15 07:54
Are we still interested in doing this?

**Comment by wojtek-t** [comment] 2015-12-15 08:02
We are currently in process of updating a client to the new official etcd client. Once this is done, we can probably get back to this one.

**Comment by davidopp** [comment] 2016-02-19 08:32
Should we close this and just say our next upgrade (whenever that happens) will be to v3?

**Comment by wojtek-t** [comment] 2016-02-19 08:40
Actually, we should close it, because we did it:
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/etcd/etcd.manifest#L13

**Closed by wojtek-t** 2016-02-19 08:40 UTC
Labels: priority/P1, team/control-plane
