### ISSUE TITLE
Malformed error messages

### ISSUE THREAD

**Issue by ashok-arora** [kubernetes/kubernetes#107012] opened 2021-12-14 07:32 UTC
### What happened?

kubectl returns the traceback for commands that don't exit:
```
$ kubectl list services -A
E1214 11:26:50.918812    3285 run.go:120] "command failed" err="unknown command \"list\" for \"kubectl\"\n\nDid you mean this?\n\tget\n\twait\n"
```

### What did you expect to happen?

Instead, it should return that the command does not exist, 
eg.
```
$ kubectl list services -A
Unknown command "list" for kubectl. Did you mean this?
    get
    wait 
```

### How can we reproduce it (as minimally and precisely as possible)?

```kubectl list services -A```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
minikube
</details>

### OS version

<details>

```console
macOS
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MadhavJivrajani** [comment] 2021-12-14 13:54
@ashok-arora 👋🏼 
I seem to be getting the expected output on
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
![Screenshot from 2021-12-14 19-17-32](https://user-images.githubusercontent.com/12381034/146010604-71f9336d-9b78-4d22-910a-30c0a54d9b76.png)

At the mentioned K8s version, I'm able to reproduce this as well 👍🏼

**Comment by MadhavJivrajani** [comment] 2021-12-14 14:06
I think this PR introduced this change: https://github.com/kubernetes/kubernetes/pull/105076
/cc @pohly

**Comment by pohly** [comment] 2021-12-14 16:17
/assign

@MadhavJivrajani is correct about the root cause.

The heuristic that I used to decide about the output format (plain text of error message) is incomplete and doesn't cover errors that occur before cobra hands over control to the actual command. I think I have an idea how this can be fixed.

**Comment by pohly** [comment] 2021-12-15 08:59
I see three possible solutions:
- an explicit parameter that says "always use fmt.Fprintf": this might be the safer solution for kubectl because it is unclear whether output via klog.ErrorS is ever desired
- tweak the heuristic:
  - check that a command was found (as done by @xyz-li in https://github.com/kubernetes/kubernetes/pull/107028): this works for this case, but I am worried that it is too specific for this particular issue here
  - check that Cobra ran our Pre methods (see my PR in https://github.com/kubernetes/kubernetes/pull/107044): IMHO a more generic solution, but still a heuristic

Please let me know what you like better.

**Comment by pohly** [comment] 2021-12-15 09:50
@xyz-li pointed out `kubectl kustomize` as one example where an error is returned after parsing is done and the command really ran. Other commands use `cmd/util.CheckError` and don't return, but `kustomize` (accidentally or intentionally, not sure) doesn't do that and returns, which is not handled correctly by `cli.Run` no matter what heuristics we use.

Therefore we need a way for `kubectl` to override the error handling. I think they improved heuristic in https://github.com/kubernetes/kubernetes/pull/107044 is useful, so I kept it and added another commit which adds `cli.RunNoErrOutput`.

@xyz-li: can you perhaps review that PR?

**Comment by pohly** [comment] 2021-12-17 08:19
@xyz-li reviewed https://github.com/kubernetes/kubernetes/pull/107044, but we still need someone with the necessary permissions to LGTM and approve it.

**Comment by eddiezane** [comment] 2022-03-02 17:56
This was closed by https://github.com/kubernetes/kubernetes/pull/107044

/close

**Closed** 2022-03-02 17:57 UTC
Labels: kind/bug, sig/cli, needs-triage
