### ISSUE TITLE
Apply changes to HorizontalPodAutoscaler configuration fails

### ISSUE THREAD

**Issue by adam-sandor** [kubernetes/kubernetes#32768] opened 2016-09-15 10:10 UTC
Updating my application with new HorizontalPodAutoscaler settings from a yaml file fails in the following ways. In both cases the application has been started using a yaml file and I'm trying to apply changes to it by changing the yaml file and calling `kubectl apply -f wholeWeaveDemo.yaml`. I'm using the [microservice-demo app](https://github.com/microservices-demo/microservices-demo/pull/305) app from Weaveworks. The link points to my PR which adds the HPA to the deployment.

After adding the HPA to the yaml file
*  When I don't make any changes to the yaml, just call `kubectl apply -f wholeWeaveDemo.yaml` I get this error: `for: "wholeWeaveDemo.yaml": unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "scaleRef"`
* If I try to increase the minimum number of replicas from 3 to 4 then apply I get this error:
`for: "wholeWeaveDemo.yaml": unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "cpuUtilization"`

In both cases there is more info:

```
&{0xc8202d7680 0xc820294230 default front-end wholeWeaveDemo.yaml TypeMeta:<kind:"HorizontalPodAutoscaler" apiVersion:"extensions/v1beta1" > metadata:<name:"front-end" generateName:"" namespace:"" selfLink:"" uid:"" resourceVersion:"" generation:0 creationTimestamp:<0001-01-01T00:00:00Z> annotations:<key:"kubectl.kubernetes.io/last-applied-configuration" value:"" > > spec:<scaleRef:<kind:"Deployment" name:"front-end" apiVersion:"" subresource:"scale" > minReplicas:4 maxReplicas:10 cpuUtilization:<targetPercentage:70 > > status:<currentReplicas:0 desiredReplicas:0 >  kind:"" apiVersion:""  215874 false}
for: "wholeWeaveDemo.yaml": error when creating patch with:
original:
{"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"front-end","creationTimestamp":null},"spec":{"scaleRef":{"kind":"Deployment","name":"front-end","subresource":"scale"},"minReplicas":3,"maxReplicas":10,"cpuUtilization":{"targetPercentage":70}},"status":{"currentReplicas":0,"desiredReplicas":0}}
modified:
{"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"front-end","creationTimestamp":null,"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"front-end\",\"creationTimestamp\":null},\"spec\":{\"scaleRef\":{\"kind\":\"Deployment\",\"name\":\"front-end\",\"subresource\":\"scale\"},\"minReplicas\":4,\"maxReplicas\":10,\"cpuUtilization\":{\"targetPercentage\":70}},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleRef":{"kind":"Deployment","name":"front-end","subresource":"scale"},"minReplicas":4,"maxReplicas":10,"cpuUtilization":{"targetPercentage":70}},"status":{"currentReplicas":0,"desiredReplicas":0}}
current:
{"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"front-end","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/front-end","uid":"6c36fbae-79c7-11e6-92ce-42010af00003","resourceVersion":"215874","creationTimestamp":"2016-09-13T15:33:30Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"front-end\",\"creationTimestamp\":null},\"spec\":{\"scaleRef\":{\"kind\":\"Deployment\",\"name\":\"front-end\",\"subresource\":\"scale\"},\"minReplicas\":3,\"maxReplicas\":10,\"cpuUtilization\":{\"targetPercentage\":70}},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"front-end"},"minReplicas":3,"maxReplicas":10,"targetCPUUtilizationPercentage":70},"status":{"lastScaleTime":"2016-09-13T15:33:30Z","currentReplicas":3,"desiredReplicas":3,"currentCPUUtilizationPercentage":0}}
```
```
&{0xc82030b500 0xc820247340 default front-end wholeWeaveDemo.yaml TypeMeta:<kind:"HorizontalPodAutoscaler" apiVersion:"extensions/v1beta1" > metadata:<name:"front-end" generateName:"" namespace:"" selfLink:"" uid:"" resourceVersion:"" generation:0 creationTimestamp:<0001-01-01T00:00:00Z> annotations:<key:"kubectl.kubernetes.io/last-applied-configuration" value:"" > > spec:<scaleRef:<kind:"Deployment" name:"front-end" apiVersion:"" subresource:"scale" > minReplicas:3 maxReplicas:10 cpuUtilization:<targetPercentage:70 > > status:<currentReplicas:0 desiredReplicas:0 >  kind:"" apiVersion:""  290619 false}
for: "wholeWeaveDemo.yaml": error when creating patch with:
original:
{"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"front-end","creationTimestamp":null},"spec":{"scaleRef":{"kind":"Deployment","name":"front-end","subresource":"scale"},"minReplicas":3,"maxReplicas":10,"cpuUtilization":{"targetPercentage":70}},"status":{"currentReplicas":0,"desiredReplicas":0}}
modified:
{"kind":"HorizontalPodAutoscaler","apiVersion":"extensions/v1beta1","metadata":{"name":"front-end","creationTimestamp":null,"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"front-end\",\"creationTimestamp\":null},\"spec\":{\"scaleRef\":{\"kind\":\"Deployment\",\"name\":\"front-end\",\"subresource\":\"scale\"},\"minReplicas\":3,\"maxReplicas\":10,\"cpuUtilization\":{\"targetPercentage\":70}},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleRef":{"kind":"Deployment","name":"front-end","subresource":"scale"},"minReplicas":3,"maxReplicas":10,"cpuUtilization":{"targetPercentage":70}},"status":{"currentReplicas":0,"desiredReplicas":0}}
current:
{"kind":"HorizontalPodAutoscaler","apiVersion":"autoscaling/v1","metadata":{"name":"front-end","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/front-end","uid":"6c36fbae-79c7-11e6-92ce-42010af00003","resourceVersion":"290619","creationTimestamp":"2016-09-13T15:33:30Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"HorizontalPodAutoscaler\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"front-end\",\"creationTimestamp\":null},\"spec\":{\"scaleRef\":{\"kind\":\"Deployment\",\"name\":\"front-end\",\"subresource\":\"scale\"},\"minReplicas\":3,\"maxReplicas\":10,\"cpuUtilization\":{\"targetPercentage\":70}},\"status\":{\"currentReplicas\":0,\"desiredReplicas\":0}}"}},"spec":{"scaleTargetRef":{"kind":"Deployment","name":"front-end"},"minReplicas":3,"maxReplicas":10,"targetCPUUtilizationPercentage":70},"status":{"lastScaleTime":"2016-09-15T09:24:31Z","currentReplicas":3,"desiredReplicas":3,"currentCPUUtilizationPercentage":0}}
```

In both cases I would expect the changes (or the no-changes) to be applied without an error. 

I can work around the problem by deleting the HPA and doing the apply afterwards.

I'm running Kubernetes on GCE. Installation was done using the deployment script in the Kubernetes distribution (kube-up.sh).
* `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
* `/etc/os-release`: PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
* `uname -a`: Linux kubernetes-minion-group-3imc 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by janetkuo** [comment] 2016-09-17 00:19
I'm able to reproduce this from HEAD

**Comment by janetkuo** [comment] 2016-09-17 00:26
This is because `kubectl` only recognizes HPA version as `autoscaling/v1` but not `extentions/v1beta1`. A better workaround it to change the HPA config to be `autoscaling/v1`, for example:

**extensions/v1beta1**
```yaml 
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
spec:
  scaleRef:
    kind: Deployment
    name: front-end
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 70
```

**autoscaling/v1** (I commented out the diff to make it more obvious): 
```yaml 
#apiVersion: extensions/v1beta1
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
spec:
  #scaleRef:
  scaleTargetRef:
    kind: Deployment
    name: front-end
    #subresource: scale
  minReplicas: 1
  maxReplicas: 10
  #cpuUtilization:
    #targetPercentage: 7
  targetCPUUtilizationPercentage: 70
```

cc @kubernetes/kubectl @AdoHe

**Comment by AdoHe** [comment] 2016-09-17 01:55
I will take a look.

**Comment by AdoHe** [comment] 2016-09-17 04:08
@adam-sandor please give a try with @janetkuo approach, I will check this after I finish local environment rebuild.

**Comment by adam-sandor** [comment] 2016-09-20 10:54
It worked nicely. Thanks @janetkuo !

Btw I found the wrong configuration on this page: http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

**Comment by pwittrock** [comment] 2016-09-29 18:23
@adam-sandor Closing the issue and opening #33776

**Closed by pwittrock** 2016-09-29 18:23 UTC
Labels: area/app-config-deployment, component/kubectl, kind/bug, team/ux

**Comment by adam-sandor** [comment] 2016-11-17 12:41
It seems that the solution mentioned above doesn't solve the problem. It seems that it is an intermittent error. We observed it with my colleague with him getting the error and me being able to apply the HPA changes. We both had the same client and same file. Somebody already reported the issue here https://github.com/kubernetes/kubernetes/issues/34413

**Comment by deepkumarchaudhary** [comment] 2019-08-28 10:15
thanks @janetkuo, it resolved my problem as well
