### ISSUE TITLE
e2e flake: Kubernetes e2e suite.Kubectl client Kubectl apply should apply a new configuration to an existing RC

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#23389] opened 2016-03-23 17:54 UTC
Recent failure on #23287 seems flaky. That PR didn't change anything but delete a few dead 
Jenkins jobs.

kubernetes-pull-build-test-e2e-gce/33368/

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:463
Expected error:
    <*errors.errorString | 0xc208266480>: {
        s: "Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.103.210 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ein3k] []  0xc2083c0510  Error from server: error when applying patch:\n{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"kind\\\":\\\"ReplicationController\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{\\\"name\\\":\\\"redis-master\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"}},\\\"spec\\\":{\\\"replicas\\\":1,\\\"selector\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"},\\\"template\\\":{\\\"metadata\\\":{\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"}},\\\"spec\\\":{\\\"containers\\\":[{\\\"name\\\":\\\"redis-master\\\",\\\"image\\\":\\\"redis\\\",\\\"ports\\\":[{\\\"name\\\":\\\"redis-server\\\",\\\"containerPort\\\":6379}],\\\"resources\\\":{}}]}}},\\\"status\\\":{\\\"replicas\\\":0}}\"},\"creationTimestamp\":null,\"labels\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"}},\"spec\":{\"selector\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"},\"template\":{\"metadata\":{\"labels\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"}}}}}\nto:\n&{0xc20802e410 0xc208089030 e2e-tests-kubectl-ein3k redis-master STDIN 0xc2084972c0 0xc2082ab1d0 566}\nfor: \"STDIN\": replicationControllers \"redis-master\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again\n [] <nil> 0xc20833f3a0 exit status 1 <nil> true [0xc208051338 0xc208051380 0xc2080513a8] [0xc208051338 0xc208051380 0xc2080513a8] [0xc208051348 0xc208051378 0xc2080513a0] [0x6da5a0 0x6da6c0 0x6da6c0] 0xc20833a5a0}:\nCommand stdout:\n\nstderr:\nError from server: error when applying patch:\n{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"kind\\\":\\\"ReplicationController\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{\\\"name\\\":\\\"redis-master\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"}},\\\"spec\\\":{\\\"replicas\\\":1,\\\"selector\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"},\\\"template\\\":{\\\"metadata\\\":{\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"app\\\":\\\"redis\\\",\\\"kubectl.kubernetes.io/apply-test\\\":\\\"ADDED\\\",\\\"role\\\":\\\"master\\\"}},\\\"spec\\\":{\\\"containers\\\":[{\\\"name\\\":\\\"redis-master\\\",\\\"image\\\":\\\"redis\\\",\\\"ports\\\":[{\\\"name\\\":\\\"redis-server\\\",\\\"containerPort\\\":6379}],\\\"resources\\\":{}}]}}},\\\"status\\\":{\\\"replicas\\\":0}}\"},\"creationTimestamp\":null,\"labels\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"}},\"spec\":{\"selector\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"},\"template\":{\"metadata\":{\"labels\":{\"kubectl.kubernetes.io/apply-test\":\"ADDED\"}}}}}\nto:\n&{0xc20802e410 0xc208089030 e2e-tests-kubectl-ein3k redis-master STDIN 0xc2084972c0 0xc2082ab1d0 566}\nfor: \"STDIN\": replicationControllers \"redis-master\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again\n\n",
    }
    Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.103.210 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ein3k] []  0xc2083c0510  Error from server: error when applying patch:
    {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"ReplicationController\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"redis-master\",\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"replicas\":1,\"selector\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"containers\":[{\"name\":\"redis-master\",\"image\":\"redis\",\"ports\":[{\"name\":\"redis-server\",\"containerPort\":6379}],\"resources\":{}}]}}},\"status\":{\"replicas\":0}}"},"creationTimestamp":null,"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}},"spec":{"selector":{"kubectl.kubernetes.io/apply-test":"ADDED"},"template":{"metadata":{"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}}}}}
    to:
    &{0xc20802e410 0xc208089030 e2e-tests-kubectl-ein3k redis-master STDIN 0xc2084972c0 0xc2082ab1d0 566}
    for: "STDIN": replicationControllers "redis-master" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
     [] <nil> 0xc20833f3a0 exit status 1 <nil> true [0xc208051338 0xc208051380 0xc2080513a8] [0xc208051338 0xc208051380 0xc2080513a8] [0xc208051348 0xc208051378 0xc2080513a0] [0x6da5a0 0x6da6c0 0x6da6c0] 0xc20833a5a0}:
    Command stdout:
    
    stderr:
    Error from server: error when applying patch:
    {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"ReplicationController\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"redis-master\",\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"replicas\":1,\"selector\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"containers\":[{\"name\":\"redis-master\",\"image\":\"redis\",\"ports\":[{\"name\":\"redis-server\",\"containerPort\":6379}],\"resources\":{}}]}}},\"status\":{\"replicas\":0}}"},"creationTimestamp":null,"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}},"spec":{"selector":{"kubectl.kubernetes.io/apply-test":"ADDED"},"template":{"metadata":{"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}}}}}
    to:
    &{0xc20802e410 0xc208089030 e2e-tests-kubectl-ein3k redis-master STDIN 0xc2084972c0 0xc2082ab1d0 566}
    for: "STDIN": replicationControllers "redis-master" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
    
    
not to have occurred
```

@spxtr to delegate.

**Comment by fejta** [comment] 2016-04-01 06:37
Looks like there are race conditions when `kubectl create` and `kubectl apply` are called near each other.

```sh
			By("creating Redis RC")
			runKubectlOrDie("create", "-f", controllerJson, nsFlag)
			By("applying a modified configuration")
			stdin := modifyReplicationControllerConfiguration(controllerJson)
			newKubectlCommand("apply", "-f", "-", nsFlag).
				withStdinReader(stdin).
				execOrDie()
```
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L547

**Comment by fejta** [comment] 2016-04-15 00:41
Made a best guess at assigning this flake with no owner for 2 weeks

**Comment by ihmccreery** [comment] 2016-04-15 17:41
Another example, I believe: http://pr-test.k8s.io/23097/kubernetes-pull-build-test-e2e-gce/32863/.

**Comment by erictune** [comment] 2016-04-28 00:12
Another example:  http://pr-test.k8s.io//24678/kubernetes-pull-build-test-e2e-gce/37164/

**Comment by cjcullen** [comment] 2016-05-03 04:58
Another one: https://github.com/kubernetes/kubernetes/pull/24304#issuecomment-216414081

**Comment by pwittrock** [comment] 2016-05-26 20:25
@davidopp Taking this since it looks like it is related to the test.  Let me know if you would prefer to keep it, or have some state on it already.

**Comment by pwittrock** [comment] 2016-05-27 17:20
Looks like this is caused by #15493

**Comment by pwittrock** [comment] 2016-05-27 17:21
Closing this as a duplicate

**Closed** 2016-05-27 22:54 UTC
Labels: kind/flake, priority/P1, team/ux
