### ISSUE TITLE
Etcd failure should recover from network partition with master flake

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#15384] opened 2015-10-09 17:15 UTC
Failed 1 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8824/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Etcd_failure_should_recover_from_network_partition_with_master/

/cc @lavalamp

**Comment by lavalamp** [comment] 2015-10-09 22:28
@wojtek-t, any chance you can look at this?

**Comment by wojtek-t** [comment] 2015-10-12 09:10
It seems to me that the problem is somewhere in Kubelet.
What exactly happened is that the test already managed to delete the pod:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/etcd_failure.go#L118
and it was waiting for the pod to be recreated by RC.

The pod was succefully recreated, scheduled and picked up by Kubelet. The interesting logs coming from Kubelet:

    I1008 23:21:48.351410    6377 config.go:382] Receiving a new pod "baz-3npl6_e2e-tests-etcd-failure-7z89v"
    I1008 23:21:48.351463    6377 kubelet.go:1944] SyncLoop (ADD): "baz-3npl6_e2e-tests-etcd-failure-7z89v"
    ...
    I1008 23:21:48.377069    6377 manager.go:1675] Need to restart pod infra container for "baz-3npl6_e2e-tests-etcd-failure-7z89v" because it is not found
    I1008 23:21:48.377281    6377 manager.go:1791] Killing Infra Container for "baz-3npl6_e2e-tests-etcd-failure-7z89v", will start new one
    I1008 23:21:48.377302    6377 manager.go:1824] Creating pod infra container for "baz-3npl6_e2e-tests-etcd-failure-7z89v"
    I1008 23:21:48.395862    6377 server.go:692] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-etcd-failure-7z89v", Name:"baz-3npl6", UID:"58c8e1e6-6e13-11e5-8111-42010af00002", APIVersion:"v1", ResourceVersion:"1755", FieldPath:"implicitly required container POD"}): reason: 'Pulled' Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
    I1008 23:21:48.408556    6377 manager.go:238] Status for pod "baz-3npl6_e2e-tests-etcd-failure-7z89v" updated successfully
    I1008 23:21:48.654567    6377 server.go:692] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-etcd-failure-7z89v", Name:"baz-3npl6", UID:"58c8e1e6-6e13-11e5-8111-42010af00002", APIVersion:"v1", ResourceVersion:"1755", FieldPath:"implicitly required container POD"}): reason: 'Created' Created with docker id 0c9a37a0e6fd
    I1008 23:21:49.362955    6377 server.go:692] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-etcd-failure-7z89v", Name:"baz-3npl6", UID:"58c8e1e6-6e13-11e5-8111-42010af00002", APIVersion:"v1", ResourceVersion:"1755", FieldPath:"implicitly required container POD"}): reason: 'Started' Started with docker id 0c9a37a0e6fd
    I1008 23:21:49.397378    6377 server.go:692] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-etcd-failure-7z89v", Name:"baz-3npl6", UID:"58c8e1e6-6e13-11e5-8111-42010af00002", APIVersion:"v1", ResourceVersion:"1755", FieldPath:"spec.containers{baz}"}): reason: 'Pulling' pulling image "gcr.io/google_containers/nginx"
    I1008 23:22:47.883663    6377 kubelet.go:1947] SyncLoop (UPDATE): "baz-3npl6_e2e-tests-etcd-failure-7z89v"
    I1008 23:22:47.918575    6377 kubelet.go:1950] SyncLoop (REMOVE): "baz-3npl6_e2e-tests-etcd-failure-7z89v"

So it clearly seems that Kubelet started pulling the image for the POD, but it didn't finish within a minute.

@dchen1107 @yujuhong - can someone from node team please take a look?

Reassigning to @dchen1107 for delegation
@dchen1107 @yujuhong - can one of you please take a look?

**Comment by lavalamp** [comment] 2015-10-12 20:03
Thanks for the investigation. Does this test really need the nginx
container? Can we switch to one that's either tiny or always present?

**Comment by dchen1107** [comment] 2015-10-12 20:14
Sounds like a timeout issue due to unpredictable docker pull action. I will update the test using pause image which is already presenting on the node.

**Comment by wojtek-t** [comment] 2015-10-13 06:35
Thanks @dchen1107 !
Since the fix is already merged - I'm closing this issue.

**Closed by wojtek-t** 2015-10-13 06:35 UTC
Labels: kind/flake, priority/P1, team/CSI
