### ISSUE TITLE
selfLink is missing slash

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubernetes#40578] opened 2017-01-27 04:05 UTC
**Kubernetes version** (use `kubectl version`):
```
bash-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3805+68f123dfa036be", GitCommit:"68f123dfa036bef57495f014a78144a9a1b517ca", GitTreeState:"clean", BuildDate:"2017-01-24T15:00:38Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3805+68f123dfa036be", GitCommit:"68f123dfa036bef57495f014a78144a9a1b517ca", GitTreeState:"clean", BuildDate:"2017-01-24T14:41:46Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
Centos
- **Kernel** (e.g. `uname -a`):
3.10.0-514.6.1.el7.x86_64
- **Install tools**:
Manual
- **Others**:

**What happened**:

```
bash-4.2# curl http://127.0.0.1:8080/api/v1/componentstatuses
...
    {
      "metadata": {
        "name": "etcd-0",
        "selfLink": "/api/v1/componentstatusesetcd-0",
        ...
...
bash-4.2# curl http://127.0.0.1:8080/api/v1/componentstatuses
...
"metadata": {
        "name": "ip-10-0-0-4.us-west-1.compute.internal",
        "selfLink": "/api/v1/nodesip-10-0-0-4.us-west-1.compute.internal",
        ...,
...
```
**What you expected to happen**:
The URLs should look something like
```
"/api/v1/componentstatuses/etcd-0"
"/api/v1/nodes/ip-10-0-0-4.us-west-1.compute.internal"
```
instead of
```
"/api/v1/componentstatusesetcd-0"
"/api/v1/nodesip-10-0-0-4.us-west-1.compute.internal"
```

**How to reproduce it** (as minimally and precisely as possible):
curl any resource that has a `selfLink`.

**Anything else do we need to know**:

**Comment by liggitt** [comment] 2017-01-27 04:12
Dupe of https://github.com/kubernetes/kubernetes/issues/37266

**Closed by liggitt** 2017-01-27 04:12 UTC
