### ISSUE TITLE
kubeadm is starting kubelet before complete config is writte to disk

### ISSUE THREAD

**Issue by kvaster** [kubernetes/kubernetes#86538] opened 2019-12-23 08:59 UTC
**What happened**:
kubeadm is timing out during cluster initialization on openrc systems. 
Kubelet is failing to start cause there is no complete configuration on the disk.

**What you expected to happen**:
It is expected to have complete config already written to disk before attempt to start kubelet.

**How to reproduce it (as minimally and precisely as possible)**:
Bug is reproducable with no configuration just by running ``kubeadm init``

**Anything else we need to know?**:
Bug is not reproducable on systemd cause kubelet is constantly restarting until it can read all configuration files. And on openrc by default kubelet is not restarted once it fails with config. My proposition is to change order of configuration and launching:

```
diff --git a/cmd/kubeadm/app/cmd/init.go b/cmd/kubeadm/app/cmd/init.go
index 57e87d6603e..942b2057909 100644
--- a/cmd/kubeadm/app/cmd/init.go
+++ b/cmd/kubeadm/app/cmd/init.go
@@ -172,9 +172,9 @@ func NewCmdInit(out io.Writer, initOptions *initOptions) *cobra.Command {

        // initialize the workflow runner with the list of phases
        initRunner.AppendPhase(phases.NewPreflightPhase())
-       initRunner.AppendPhase(phases.NewKubeletStartPhase())
        initRunner.AppendPhase(phases.NewCertsPhase())
        initRunner.AppendPhase(phases.NewKubeConfigPhase())
+       initRunner.AppendPhase(phases.NewKubeletStartPhase())
        initRunner.AppendPhase(phases.NewControlPlanePhase())
        initRunner.AppendPhase(phases.NewEtcdPhase())
        initRunner.AppendPhase(phases.NewWaitControlPlanePhase())
```

**Environment**:
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"archive", BuildDate:"2019-12-18T09:14:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by neolit123** [comment] 2019-12-23 22:46
>  My proposition is to change order of configuration and launching:

this is something that we discussed at some point, but the problem is that at this point it could be a breaking change to all the users that separated the init process into phases.

before applying this change we need an estimate of the implications.

> And on openrc by default kubelet is not restarted once it fails with config. My proposition is to change order of configuration and launching:

is there are way to tell an openrc service to loop-restart (crash loop) the same way as systemd is doing?

/kind design
/area ecosystem

**Comment by neolit123** [comment] 2019-12-23 22:46
i'm going to close this thicket and move it to k/kubeadm.

/close

**Closed by neolit123** 2019-12-23 22:46 UTC
Labels: area/ecosystem, kind/bug, kind/design, sig/cluster-lifecycle

**Comment by neolit123** [comment] 2019-12-23 22:48
opened here https://github.com/kubernetes/kubeadm/issues/1986
