### ISSUE TITLE
`kubectl delete node` make kube-scheduler enter failed state

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#31968] opened 2016-09-02 12:01 UTC
If there're some pod running in one node. `kubectl delete node $node` will make kube-scheduler enter failed state, 100% reproduced. 
Of course systemd will restart kube-scheduler if you configured it. But some time systemd restart it failed.
such as below:

> Sep 02 19:34:11 kube-node01 systemd[1]: Unit kube-scheduler.service entered failed state.
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service failed.
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service holdoff time over, scheduling restart.
> Sep 02 19:34:11 kube-node01 systemd[1]: Started Kubernetes Scheduler Plugin.
> Sep 02 19:34:11 kube-node01 systemd[1]: Starting Kubernetes Scheduler Plugin...
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic: runtime error: invalid memory address or nil pointer dereference
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: [signal 0xb code=0x1 addr=0x10 pc=0xc93be1]
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: goroutine 690 [running]:
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic(0x2261f80, 0xc82000e0a0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic(0x2261f80, 0xc82000e0a0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /usr/local/go/src/runtime/panic.go:443 +0x4e9
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).getMatchingAntiAffinityTerms(0xc8202a1740, 0xc8202559
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971 +0x13
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).satisfiesExistingPodsAntiAffinity(0xc8202a1740, 0xc82
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002 +0x9
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).InterPodAffinityMatches(0xc8202a1740, 0xc820255900, 0
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830 +0x11
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).InterPodAffinityMatches-fm(0xc820255900, 0x0, 0x0, 0x
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822 +0x7c
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler.podFitsOnNode(0xc820255900, 0x0, 0x0, 0xc8206a6120, 0xc8201d56e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215 +0x10e
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler.findNodesThatFit.func1(0x0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167 +0x169
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/pkg/util/workqueue.Parallelize.func1(0xc820430a80, 0xc8202c6680, 0xc8201c6000)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43 +0xbd
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: created by k8s.io/kubernetes/pkg/util/workqueue.Parallelize
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:45 +0x10f
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic: runtime error: invalid memory address or nil pointer dereference
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: [signal 0xb code=0x1 addr=0x10 pc=0xc93be1]
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: goroutine 693 [running]:
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic(0x2261f80, 0xc82000e0a0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: panic(0x2261f80, 0xc82000e0a0)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /usr/local/go/src/runtime/panic.go:443 +0x4e9
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).getMatchingAntiAffinityTerms(0xc8202a1740, 0xc8202559
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971 +0x13
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).satisfiesExistingPodsAntiAffinity(0xc8202a1740, 0xc82
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002 +0x9
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).InterPodAffinityMatches(0xc8202a1740, 0xc820255900, 0
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830 +0x11
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(_PodAffinityChecker).InterPodAffinityMatches-fm(0xc820255900, 0x0, 0x0, 0x
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822 +0x7c
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler.podFitsOnNode(0xc820255900, 0x0, 0x0, 0xc8206a74a0, 0xc8201d56e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215 +0x10e
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/plugin/pkg/scheduler.findNodesThatFit.func1(0x3)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167 +0x169
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: k8s.io/kubernetes/pkg/util/workqueue.Parallelize.func1(0xc820430a80, 0xc8202c6680, 0xc8201c6000)
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43 +0xbd
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: created by k8s.io/kubernetes/pkg/util/workqueue.Parallelize
> Sep 02 19:34:11 kube-node01 kube-scheduler[8957]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:45 +0x10f
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Sep 02 19:34:11 kube-node01 systemd[1]: Unit kube-scheduler.service entered failed state.
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service failed.
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service holdoff time over, scheduling restart.
> Sep 02 19:34:11 kube-node01 systemd[1]: start request repeated too quickly for kube-scheduler.service
> Sep 02 19:34:11 kube-node01 systemd[1]: Failed to start Kubernetes Scheduler Plugin.
> Sep 02 19:34:11 kube-node01 systemd[1]: Unit kube-scheduler.service entered failed state.
> Sep 02 19:34:11 kube-node01 systemd[1]: kube-scheduler.service failed.

Then`systemctl restart kube-scheduler` manually is ok.

**Comment by workhardcc** [comment] 2016-09-11 07:20
1.version: v1.4.0-alpha.3
2.just one master + five nodes 
Must some pods running in that node which you will delete.

**Comment by kdima** [comment] 2016-09-19 18:24
We seem to be having the same issue. I tried running v1.4.0-alpha.3 and 1.4.0-beta.8. Issue seems to persist on both. 
We have 3 masters and 3 worker nodes.
Our log output
```
Sep 19 18:18:33 h-stg-core-1 docker[18787]: I0919 18:18:33.160178       1 leaderelection.go:214] sucessfully acquired lease kube-system/kube-scheduler
Sep 19 18:18:33 h-stg-core-1 docker[18787]: E0919 18:18:33.160618       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /usr/local/go/src/runtime/asm_amd64.s:472
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /usr/local/go/src/runtime/panic.go:443
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /usr/local/go/src/runtime/panic.go:62
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /usr/local/go/src/runtime/sigpanic_unix.go:24
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43
Sep 19 18:18:33 h-stg-core-1 docker[18787]: /usr/local/go/src/runtime/asm_amd64.s:1998
Sep 19 18:18:33 h-stg-core-1 docker[18787]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         panic: runtime error: invalid memory address or nil pointer dereference
Sep 19 18:18:33 h-stg-core-1 docker[18787]: [signal 0xb code=0x1 addr=0x10 pc=0x1f360b1]
Sep 19 18:18:33 h-stg-core-1 docker[18787]: goroutine 148 [running]:
Sep 19 18:18:33 h-stg-core-1 docker[18787]: panic(0x4474760, 0xc820014080)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153
Sep 19 18:18:33 h-stg-core-1 docker[18787]: panic(0x4474760, 0xc820014080)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /usr/local/go/src/runtime/panic.go:443 +0x4e9
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).getMatchingAntiAffinityTerms(0xc82039ed80, 0xc82030e000, 0xc8207a1600, 0x23, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971 +0x131
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).satisfiesExistingPodsAntiAffinity(0xc82039ed80, 0xc82030e000, 0x0, 0x0, 0xc820766000, 0xc820771f80)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002 +0x986
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches(0xc82039ed80, 0xc82030e000, 0x0, 0x0, 0xc820c64900, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830 +0x117
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches-fm(0xc82030e000, 0x0, 0x0, 0xc820c64900, 0xc8200cb501, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822 +0x7c
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler.podFitsOnNode(0xc82030e000, 0x0, 0x0, 0xc820c64900, 0xc8204bd2f0, 0xc820c60800, 0x0, 0x0, 0x0, 0x0, ...)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215 +0x10e
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/plugin/pkg/scheduler.findNodesThatFit.func1(0x0)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167 +0x169
Sep 19 18:18:33 h-stg-core-1 docker[18787]: k8s.io/kubernetes/pkg/util/workqueue.Parallelize.func1(0xc8200cb560, 0xc8204ba980, 0xc8201e57a0)
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43 +0xbd
Sep 19 18:18:33 h-stg-core-1 docker[18787]: created by k8s.io/kubernetes/pkg/util/workqueue.Parallelize
Sep 19 18:18:33 h-stg-core-1 docker[18787]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:45 +0x10f

```

**Comment by mwitkow** [comment] 2016-09-26 07:41
@nhlfr what additional information would help you reproduce it? 

We seem to be getting this `kube-scheduler` NPE regularly (at least once a day) on our test cluster with `1.4.8-beta.8`. +@thockin FYI, as the `1.4` release is looming.

**Comment by davidopp** [comment] 2016-10-02 01:35
@wojtek-t @xiang90

**Comment by xiang90** [comment] 2016-10-20 23:06
this panic is fixed by https://github.com/kubernetes/kubernetes/pull/33086.

**Comment by brendandburns** [comment] 2016-11-06 23:51
Closing this since @xiang90 indicates it's fixed.

**Closed by brendandburns** 2016-11-06 23:51 UTC
Labels: component/scheduler, priority/P1, team/control-plane
