### ISSUE TITLE
kube-controller-manager: doesn't use root-ca-file for connection with master

### ISSUE THREAD

**Issue by player1-fleetsmithsupport** [kubernetes/kubernetes#32453] opened 2016-09-11 06:29 UTC
**Kubernetes version**:
```
:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud
- **OS** (e.g. from /etc/os-release):
```
:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
~# uname -a
Linux controller-1039 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
- **Others**:

**What happened**:
When I run `kube-apiserver`:
```
ExecStart=/usr/local/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
  --advertise-address=10.138.0.11 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --authorization-mode=ABAC \
  --authorization-policy-file=/var/lib/kubernetes/authorization-policy.jsonl \
  --bind-address=0.0.0.0 \
  --enable-swagger-ui=true \
  --etcd-cafile=/srv/encrypted/ca-pem \
  --insecure-bind-address=127.0.0.1 \
  --kubelet-certificate-authority=/srv/encrypted/ca-pem \
  --etcd-servers=https://etcd.service.consul:2379 \
  --service-account-key-file=/srv/encrypted/kubernetes-key.pem \
  --service-cluster-ip-range=10.32.0.0/24 \
  --service-node-port-range=30000-32767 \
  --tls-cert-file=/srv/encrypted/kubernetes.pem \
  --tls-private-key-file=/srv/encrypted/kubernetes-key.pem \
  --token-auth-file=/var/lib/kubernetes/token.csv \
  --v=2
```
and `kube-controller-manager`:
```
ExecStart=/usr/local/bin/kube-controller-manager \
  --allocate-node-cidrs=true \
  --cluster-cidr=10.200.0.0/16 \
  --cluster-name=kubernetes \
  --leader-elect=true \
  --master=https://10.138.0.11:6443 \
  --root-ca-file="/srv/encrypted/ca-pem" \
  --service-account-private-key-file="/srv/encrypted/kubernetes-key.pem" \
  --service-cluster-ip-range=10.32.0.0/24 \
  --v=2 \
  --debug=999
```
`kube-controller-manager` return error:
```
:~# /usr/local/bin/kube-controller-manager   --allocate-node-cidrs=true   --cluster-cidr=10.200.0.0/16   --cluster-name=kubernetes   --leader-elect=true   --master=https://10.138.0.11:6443   --root-ca-file="/srv/encrypted/ca-pem"   --service-account-private-key-file="/srv/encrypted/kubernetes-key.pem"   --service-cluster-ip-range=10.32.0.0/24   --v=999
I0911 05:41:28.091567    9603 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: kube-controller-manager/v1.3.6 (linux/amd64) kubernetes/ae4550c" https://10.138.0.11:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager
I0911 05:41:28.128820    9603 round_trippers.go:318] GET https://10.138.0.11:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager  in 37 milliseconds
I0911 05:41:28.129014    9603 round_trippers.go:324] Response Headers:
E0911 05:41:28.129169    9603 leaderelection.go:253] error retrieving endpoint: Get https://10.138.0.11:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: x509: certificate signed by unknown authority
I0911 05:41:28.129248    9603 leaderelection.go:210] failed to renew lease kube-system/kube-controller-manager
```

It looks like `kube-controller-manager` is not using custom CA to connect with master.

When I run:
```
~# openssl s_client -connect 10.138.0.11:6443 -CApath /srv/encrypted/ca-pem
CONNECTED(00000003)
depth=2 C = US, O = "Test, Inc.", OU = test.com, CN = Test Root CA 1
verify error:num=19:self signed certificate in certificate chain
---
Certificate chain
 0 s:/CN=controller-1039.controller.service.consul
   i:/CN=Test Infra Intermediate CA
 1 s:/CN=Test Infra Intermediate CA
   i:/C=US/O=Test, Inc./OU=test.com/CN=Test Root CA 1
 2 s:/C=US/O=Test, Inc./OU=test.com/CN=Test Root CA 1
   i:/C=US/O=Test, Inc./OU=test.com/CN=Test Root CA 1
---
Server certificate
[…]
```
everything looks fine.

**What you expected to happen**:
I would like to connect `kube-controller-manager` with `kube-apiserver` via HTTPS with custom self-signed CA.

**How to reproduce it** (as minimally and precisely as possible):
All commends to reproduce are above.

**Anything else do we need to know**:

**Comment by dims** [comment] 2016-09-12 12:55
@player1-fleetsmithsupport : I can see that the root ca file is picked up and used for calls in the controller manager - https://github.com/kubernetes/kubernetes/blob/17f82069bb1f4e07ee01856b357ebf451dc600b2/cmd/kube-controller-manager/app/controllermanager.go#L484 - Do you see anything in the log files?

**Comment by calvinmorrow** [comment] 2016-09-14 22:13
I'm seeing the same behavior with the controller-manager on 1.3.6.  All calls result in `x509: certificate signed by unknown authority`.

Strangely enough I tried changing the cli to use an invalid certificate and didn't see any change in the logs.  It does feel like the option isn't being passed through.

**Comment by calvinmorrow** [comment] 2016-09-14 22:42
Creating a kubeconfig with the same ca-certificate and specifying `--kubeconfig` in the controller-manager args allows https connections to work as intended.

**Comment by dims** [comment] 2016-09-21 09:52
@player1-fleetsmithsupport @calvinmorrow : so i lookeded deeper, the description of "root-ca-file" says
`"If set, this root certificate authority will be included in service account's token secret. This must be a valid PEM-encoded CA bundle."`

So this is *not* the command line option for setting the CA for normal operations like leader election. So that's why using the kubeconfig with the same ca-certificate (as reported by Calvin) works. 

Hope this helps

**Comment by ljagiello** [comment] 2016-09-21 15:55
@dims oh this is interesting I will definitely check that.

**Comment by liggitt** [comment] 2016-10-12 03:03
the correct place to set a trusted CA bundle for verifying connections to the api is in the kubeconfig file, as noted

**Closed by liggitt** 2016-10-12 03:03 UTC
Labels: component/apiserver, team/control-plane
