### ISSUE TITLE
Can't access cluster master endpoint after upgrade from 1.5.4 to 1.6.0

### ISSUE THREAD

**Issue by yolinas** [kubernetes/kubernetes#44275] opened 2017-04-10 13:14 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
system:anonymous
User "system:anonymous" cannot get  at the cluster scope
upgrade

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**: gcloud sdk 150.0.0
- **Others**:

**What happened**:
I upgraded our cluster from 1.5.4 to 1.6.0 and as a result I am no longer able to access the kubernetes dashboard that was available on the cluster master endpoint. The error I get is 403:
User "system:anonymous" cannot get  at the cluster scope.: "No policy matched.\nUnknown user \"system:anonymous\""

**What you expected to happen**:
I would expect to be able to get to the /ui endpoint to access the kubernetes dashboard on the cluster master endpoint after I am prompted for the username and password.

**How to reproduce it** (as minimally and precisely as possible):
- Start with a container cluster with a master version 1.6.0 and node version 1.5.4
- Run gcloud container clusters upgrade jlp-food-subscriptions-perf --cluster-version=1.6.0
- Hit the cluster master endpoint/ui url in the browser
- Get the error:
User "system:anonymous" cannot get  at the cluster scope.: "No policy matched.\nUnknown user \"system:anonymous\""

**Anything else we need to know**:

**Comment by Stono** [comment] 2017-04-10 14:05
I also have this issue, going from 1.5.6 -> 1.6.0

**Comment by motomux** [comment] 2017-04-11 21:37
I also have this issue by upgrading from v1.5.4 to v1.6.0.
I upgraded it on GCP console.

**Comment by MarcoGlauser** [comment] 2017-04-12 08:15
I have the same issue since upgrading from 1.5.4 to 1.6.0!
`kubectl proxy` still works though.

**Comment by ypadlyak** [comment] 2017-04-12 14:04
Me too :)

**Comment by liggitt** [comment] 2017-04-12 19:14
dupe of #39722

anonymous requests and browser basic-auth prompts cannot both be enabled. To access the dashboard via the API proxy endpoint from a browser with basic auth credentials, you can either use `kubectl proxy` and access the dashboard via localhost (recommended), or disable anonymous requests to the API (`--anonymous-auth=false`) and authenticate to the API directly from the browser with basic-auth credentials (no recommended)

**Closed by liggitt** 2017-04-12 19:14 UTC

**Comment by ensonic** [comment] 2017-05-05 11:41
Sorry I don't understand. My cluster on GKE migrated to 1.6. What do I need to run to still be able to access `https://<kubernetes-master>/ui`. This previously required user-name + passwd. I don't get why one needs to disable `anonymous requests to the API` to `enable basic-auth` - how is a basic auth'ed user anonymous?

**Comment by liggitt** [comment] 2017-05-05 12:03
The server won't send basic auth challenges to unauthenticated requests if anonymous auth is enabled. Without a challenge, the browser will never send its basic auth credentials. 

A better way to access the UI via the API is to run `kubectl proxy` and access `http://localhost:8001/ui`

**Comment by CelsoSantos** [comment] 2017-05-17 09:12
I too am facing this issue after upgrading to 1.6.2 on GKE

**Comment by alex88** [comment] 2017-05-20 22:53
Same here, using `kubectl proxy` and `http://localhost:8001/ui`

**Comment by naivegeek** [comment] 2017-05-25 18:14
I am also facing the same issue I have 1.6.4 version of kubernetes on Ubuntu 16.04 

Request
https://ip::6443/ui.html
Response
User "system:anonymous" cannot get  at the cluster scope.

**Comment by CelsoSantos** [comment] 2017-05-25 18:30
I'm not entirely sure of it, but I start to think that this was an intended change?

**Comment by simoami** [comment] 2017-06-16 05:53
A silent change indeed. I wonder what other hidden changes will 1.7 and beyond hold.

**Comment by ganda-pl** [comment] 2017-08-09 13:33
Funny thing is that on Chrome I get the error: **User "system:anonymous" cannot get  at the cluster scope.: "No policy matched.\nUnknown user \"system:anonymous\"".** 

Safari asks for login/password and dashboard can be accessed no problem...

**Comment by Dmitry1987** [comment] 2017-08-12 14:18
To me it seems like every next release of K8s will be more and more difficult to setup, maintain, and upgrade, for simple mortals who are not using hosted GKE or OpenShift versions. And it's totally ok, you know, people need to get paid for their work. Features are top priority, while 'ease of use' or "convenience" of those struggling with the open source version, are low priority. IMHO.

Same with most Hashicorp tools. Consul / vault / Nomad, are for masochists unless used in Hashicorp Atlas hosted solution... It's a pain to see architects and DevOps spend hundreds of work hours to learn, setup, and then troubleshoot all those systems on their own. Instead - the company could've hosted all their apps on google App Engine or something, without even hiring the fleet of "architects" and DevOps pros :+1: , and it will be (1) faster (2) cheaper, to launch all the same products and iterate development.

Disclaimer: I'm one of those masochist DevOps who works with all those '**great success** tools' manually, not using any hosted solution :) . But if it was my choice I'd migrate all our APIs and services to some out-of-the box professionally managed service, and sent home all cloud solution architects, cutting the operational costs by x5 lol.

**Comment by korenlev** [comment] 2017-11-08 14:38
same here, so default install of latest dashboard gives you no dashboard access from remote , only through local (127.0.0.1) proxy, this might need fixing

**Comment by korenlev** [comment] 2017-11-08 14:44
only workaround that helped me get access from remote is: https://kubernetes.io/docs/admin/kubelet-authentication-authorization/

**Comment by klud1** [comment] 2017-11-17 14:52
I'm learning K8s now (moving from Swarm),  I used `kube-up.sh` to spin up a cluster on GCE, it all seems to be setup properly
```sh
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://ip-address
GLBCDefaultBackend is running at https://ip-address/api/v1/namespaces/kube-system/services/default-http-backend/proxy
Heapster is running at https://ip-address/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://ip-address/api/v1/namespaces/kube-system/services/kube-dns/proxy
kubernetes-dashboard is running at https://ip-address/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
Metrics-server is running at https://ip-address/api/v1/namespaces/kube-system/services/metrics-server/proxy
Grafana is running at https://ip-address/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
InfluxDB is running at https://ip-address/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy
```
Trying to access the dashboard at `kubernetes-dashboard is running at https://ip-address/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy` it throws the following error
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 403
}
```

Furthermore, i'm not able to access at `https://ip-address/ui`
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/ui\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

**Comment by icewheel** [comment] 2018-01-29 08:46
Same issue here. Installed the latest version today.
```
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/ui\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```
http://localhost:8001/ list all the api endpoint and is working fine. But the dashboard needs authentication but there is no password and username.

**Comment by DerfOh** [comment] 2018-04-01 16:38
Having the same problem. Error needs to be more clear.

**Comment by levindoneto** [comment] 2019-01-24 13:10
I've got the same error:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:node:master-1\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}
````

Does somebody know how to solve it?

**Comment by binudba** [comment] 2020-01-05 20:00
This is how I solved it. Please take a look.
https://github.com/binudba/Troubeshooting-K8s-issues/blob/master/kube-apiserver-forbidden-messages.md

**Comment by levindoneto** [comment] 2020-01-05 20:45
> This is how I solved it. Please take a look.
> https://github.com/binudba/Troubeshooting-K8s-issues/blob/master/kube-apiserver-forbidden-messages.md

It works just fine now, thanks @binudba 😀

**Comment by levindoneto** [comment] 2020-01-05 20:46
> This is how I solved it. Please take a look.
> https://github.com/binudba/Troubeshooting-K8s-issues/blob/master/kube-apiserver-forbidden-messages.md

This works just fine for me, thanks @binudba 😀

**Comment by yomesky2000** [comment] 2020-04-08 07:38
@ levindoneto 

When you used this solution: https://github.com/binudba/Troubeshooting-K8s-issues/blob/master/kube-apiserver-forbidden-messages.md

Where you able to view the dashboard of your kubernete? i use the same solution byt still unable to get to the kubernete dashboard. If anyone has been ablem to solve this issue of accessing kubernete dashboard on VMware, pls help solve this issue asap.
