### ISSUE TITLE
flaky unit test in pkg/client/unversioned/portforward

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16394] opened 2015-10-27 22:53 UTC
```
--- FAIL: TestForwardPorts (0.01s)
	portforward_test.go:270: forward 2 ports with bidirectional data: server expected to receive "ghij", got "" for port 6000
E1027 15:46:48.833324    1555 portforward.go:303] error copying from local connection to remote stream: write tcp 127.0.0.1:45208->127.0.0.1:59640: write: broken pipe
I1027 15:46:48.833625    1555 portforward.go:213] Forwarding from 127.0.0.1:5555 -> 5555
I1027 15:46:48.833663    1555 portforward.go:213] Forwarding from [::1]:5555 -> 5555
E1027 15:46:48.834143    1555 portforward.go:202] Unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use
E1027 15:46:48.834190    1555 portforward.go:202] Unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use
W1027 15:46:48.834219    1555 portforward.go:154] Unable to listen on port 5555: All listeners failed to create with the following errors: listen tcp4 127.0.0.1:5555: bind: address already in use, listen tcp6 [::1]:5555: bind: address already in use
FAIL
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	0.188s
```

**Comment by ncdc** [comment] 2015-11-24 18:22
I have determined the root cause of this. In the test case, it:

1. starts a port forwarding session, listening on a local port
1. establishes a TCP connection to the local port
  1. a goroutine copies data from the local port to the remote
  1. a goroutine copies data from the remote to the local port
1. writes data to the TCP connection
1. reads data from the TCP connection
1. stops port forwarding, which results in the client streams being closed

The problem is that the data written in step 3 is only to the local TCP port. There's no guarantee that the goroutine in 2.i copies the data to the remote before step 5 happens.

In fact, if you reverse steps 3 (https://github.com/kubernetes/kubernetes/blob/ff9883d9ecd32f9db1077a4b6aeee3c112b0595d/pkg/client/unversioned/portforward/portforward_test.go#L335-L345) and 4 (https://github.com/kubernetes/kubernetes/blob/ff9883d9ecd32f9db1077a4b6aeee3c112b0595d/pkg/client/unversioned/portforward/portforward_test.go#L346-L357) so the write happens immediately before you close the stopChan, this test fails very quickly.

I am thinking about how to fix this...

**Comment by gmarek** [comment] 2015-12-29 10:37
Not done yet: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5253/

**Comment by quinton-hoole** [comment] 2016-01-02 00:14
Saw this again today:

https://github.com/kubernetes/kubernetes/pull/17916#issuecomment-168351936

**Comment by wojtek-t** [comment] 2016-01-02 18:01
@quinton-hoole - this was a different failure than this one. I've just opened https://github.com/kubernetes/kubernetes/issues/19230 for it and closing this one

**Closed by wojtek-t** 2016-01-02 18:01 UTC
Labels: kind/flake, priority/P0, team/CSI
