### ISSUE TITLE
Etcd size sometimes starts growing and grows until "mvcc: database space exceeded"

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#45037] opened 2017-04-27 16:31 UTC
To reproduce, bring up a GCE cluster, then modify the `--quota-backend-bytes` field in `/etc/kubernetes/manifest/etcd.manifest` and restart etcd.  I lowered it to 384 MiB to speed this up.

```console
% kubectl run sleep --image=busybox -- 'sleep 300'
% kubectl edit deployment sleep
# in the pod template, i put 3 annotations with 50,000 byte values
% while true; do
while> kc scale --replicas=1 deployments/sleep
while> sleep 1
while> kc scale --replicas=20 deployments/sleep
while> sleep 1 
while> done
```

After awhile, you'll start to get this from the loop: `error: Scaling the resource failed with: etcdserver: mvcc: database space exceeded; Current resource version 6060`

Cool, now it's broken.  Attached are some logfiles.  The data directory is huge, so I put the zipfile [on google drive](https://drive.google.com/a/google.com/file/d/0B7jY9P4LD3lZRUhMZkNvVUYyNjA/view?usp=sharing).  Join https://groups.google.com/forum/#!forum/kubernetes-dev if you don't have read access.

[etcd.log.txt](https://github.com/kubernetes/kubernetes/files/962218/etcd.log.txt)
[kube-apiserver.log.txt](https://github.com/kubernetes/kubernetes/files/962219/kube-apiserver.log.txt)

**Comment by hongchaodeng** [comment] 2017-04-27 16:43
> To reproduce, bring up a GCE cluster

Can you detail how did you bring up the cluster? k8s version, etcd version. Please give a script.

>  then modify the --quota-backend-bytes field in /etc/kubernetes/manifest/etcd.manifest and restart etcd.

Please give more detail. What is `/etc/kubernetes/manifest/etcd.manifest` file?

> After awhile

How long is a while? Can you give a measure?

**Comment by xiang90** [comment] 2017-04-27 19:08
@mml 

Each pod contains ~ 3 * 50,000bytes = 150 KB data or 50KB? Let's assume it is 150KB (50KB wont make a huge difference).

We are generating ~ 20/2 = 10 pods/seconds, which is 1500KB = 1.5MB/seconds data.

If we keep doing this for 300 seconds without cleaning up "dead" pods and do compaction timely, we will run out of storage quota you set (~300MB). It looks like a DOS to Kubernetes storage. No matter how hard we try, we will fill up the storage pretty soon. etcd seems to do the correct thing here to stop you from making etcd into an unrecoverable state.

This reproduce does not really make sense to me if my previous understanding is correct. 

But I will also look into the logs you provided to confirm my assumption. Maybe there is a bug somewhere causing etcd failed to compact the data.

@wojtek-t does this reproduce match what happened in reality? If yes, we need to limit the size of the pod, pod creation time, accelerate GC and compaction rate.

**Comment by mml** [comment] 2017-04-27 19:58
150K is correct.

But, the pods don't generally complete.  Most of them are deleted as we scale the controllers up and down.

Of those that do complete (by my math, I think it could be no faster than about 1 every 5 minutes), there is pod GC for dead pods.  I will try to find the parameters it is using to see if that is part of the problem.

**Comment by mml** [comment] 2017-04-27 20:09
> Of those that do complete (by my math, I think it could be no faster than about 1 every 5 minutes), there is pod GC for dead pods

This is set by the controller-manager flag `terminated-pod-gc-threshold`, which is `12,500` by default (see [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/options/options.go#L86) and [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/options/options.go#L164)).  But as I said, I don't think there will be many dead pods.

**Comment by mml** [comment] 2017-04-27 20:12
> Can you detail how did you bring up the cluster? k8s version, etcd version. Please give a script.

I did this at head, but observed the same behavior on 1.6.  I brought up an e2e test cluster, but `cluster/kube-up.sh` does basically the same thing.

> Please give more detail. What is /etc/kubernetes/manifest/etcd.manifest file?

On the master, this file is present and configures the static pod in which etcd runs.  One doesn't need to understand the whole file.  Just look for the `--quota-backend-bytes` flag and set the value to something low enough that you will hit it sooner.

> How long is a while? Can you give a measure?

I didn't record it.  Less than an hour.  Probably in the neighborhood of 10 minutes.

**Comment by xiang90** [comment] 2017-04-27 20:27
@mml  @wojtek-t 

Checked etcd log/data.

We have ~3700 keys in etcd, which consumes 385MB space. avg key size is ~100KB. Most of them are dead pods.

From etcd perspective, it SHOULD stop users from writing to it since the size exceeds the limit.

API server did GC pods

>  This is set by the controller-manager flag terminated-pod-gc-threshold, which is 12,500 by default 

If 12,500 is the threshold, then it is a problem. 12,500 * 150KB (1.85GB) >> 300MB. Right? So when you create ~3000 pods, etcd will exceed its size. That maps to ~300 seconds run of your script.

**Comment by xiang90** [comment] 2017-04-27 20:38
@mml 

Just to be clear. We should note that etcd3 keeps historical version of keys, which means both the PUT&DELETE will be kept until an etcd compaction is called. etcd compaction is every 5 minutes. As long as we create more than 3000 pods in 5 minutes, it triggers the no space alarm. 

12,500 setting is also a problem (when we set quota low) as I mentioned early.

**Comment by mml** [comment] 2017-04-27 20:40
@xiang90 OK, thanks.  Following from that if I try a modified version of this strategy where I try to keep the creation rate to say 2000 pods / 5 minutes, the system should stay healthy due to etcd compaction.  If that's right, I'll try this lower rate and see what happens.

**Comment by xiang90** [comment] 2017-04-27 21:00
> ~  2000 pods / 5minute

yes. and we need to make sure the 2000 pods are also removed either by the controller or pod GC (request etcd delete). or we will simply keep on adding stuff into etcd. compaction will take no effect.

**Comment by wojtek-t** [comment] 2017-04-28 07:05
I agree with @xiang90 that in this case it looks like "working as intended". Also note that we have the quota bytes set to 4GB, and it really makes a difference comparing to ~400MB, because we are doing compaction every 5 minutes in both cases.

> @wojtek-t does this reproduce match what happened in reality? If yes, we need to limit the size of the pod, pod creation time, accelerate GC and compaction rate.

To be honest, I'm not convinced it is what happened. My hypothesis is that we faced some other problem, but I wasn't the one what was doing the debugging here.

**Comment by wojtek-t** [comment] 2017-04-28 09:12
So I looked into logs of the cluster affected and:
- when I did manual: "compact + defrag"
I compacted only 1161 changes in etcd

What I mean, etcd was compacted to rev: 697302 and after my manual compaction to rev: 698463

So I'm pretty much convinced that the problem wasn't in too long history in etcd.

So I have a strong hypothesis, that what really helped in this case was actually "defrag".

@xiang90 - can you point us to some documentation what exactly defrag is doing? Should we also be doing periodic defrag in Kubernetes?

**Comment by wojtek-t** [comment] 2017-04-28 09:38
So now I'm 100% the problem wasn't about size of history in etcd - it was about fragmentation.

So what I did is that I took one of the snapshots from that cluster and restored it locally and it was huge. Then I just did defrag, and it was reduced by ~500x. See below:

```
wojtekt@wojtekt-work:~/Downloads$ ETCDCTL_API=3 etcdctl --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 8e9e05c52164694d | 3.0.17  | 5.1 GB  | true      |         2 |        150 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
wojtekt@wojtekt-work:~/Downloads$ ETCDCTL_API=3 etcdctl get /registry /zzz > out.txt
wojtekt@wojtekt-work:~/Downloads$ vim out.txt 
wojtekt@wojtekt-work:~/Downloads$ ETCDCTL_API=3 etcdctl get /registry /zzz | wc -l
6522
wojtekt@wojtekt-work:~/Downloads$ ETCDCTL_API=3 etcdctl defrag
Finished defragmenting etcd member[127.0.0.1:2379]
wojtekt@wojtekt-work:~/Downloads$ ETCDCTL_API=3 etcdctl --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 8e9e05c52164694d | 3.0.17  | 11 MB   | true      |         2 |        886 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
```

So I think this is all about the question that I asked above:

> @xiang90 - can you point us to some documentation what exactly defrag is doing? Should we also be doing periodic defrag in Kubernetes?

**Comment by wojtek-t** [comment] 2017-04-28 09:52
So in other words, my question here is:

"don't we need something like https://github.com/kubernetes/kubernetes/pull/45090 "

In my opinion this would solve the problem that we've seen.

**Comment by xiang90** [comment] 2017-04-28 17:11
@wojtek-t 

> can you point us to some documentation what exactly defrag is doing? 

defrag is there to reclaim disk space. It is a highwater mark that the database has ever grown to. For example, you put 10M keys into etcd and remove them all, you might want to call defrag. Other than that, we should be good. Normally, you will be able to use 50%+ the space.

16MB actual data but 5GB page allocation is really strange. Do you call snapshot from etcdctl frequently? 

We just found an issue in the underlying btree storage engine we use. It might cause the unbounded space usage. We are still investigating it.

**Comment by wojtek-t** [comment] 2017-04-28 17:31
> 16MB actual data but 5GB page allocation is really strange. Do you call snapshot from etcdctl frequently?

We've grown from ~60MB snapshot to ~4.5GB snapshot within 2 hours.

> vWe just found an issue in the underlying btree storage engine we use. It might cause the unbounded space usage. We are still investigating it.

I see - thanks for the info. Is there any issue for it?

**Comment by xiang90** [comment] 2017-04-28 17:33
@wojtek-t 

How often do you call snapshot from etcdctl? or how do you do snapshot?

**Comment by xiang90** [comment] 2017-04-28 17:36
> I see - thanks for the info. Is there any issue for it?

We are still looking into the problem right now.

**Comment by wojtek-t** [comment] 2017-04-28 17:37
Every hour or so. We're using etcdctl for snapshoting.

**Comment by xiang90** [comment] 2017-04-28 18:02
> Every hour or so. We're using etcdctl for snapshoting.

Hmm... if you do not do snapshot very frequently, you should not meet the exact issue I just described. It might be another thing. Do you have a good way to reproduce it?

**Comment by wojtek-t** [comment] 2017-04-28 20:04
>  Do you have a good way to reproduce it?

Not at all.

**Comment by xiang90** [comment] 2017-05-01 18:09
@wojtek-t I tried to reproduce this issue with Kubernetes with a higher load (higher throughput, less pod size) than @mml's, and keep on snapshotting it every 5 minutes. I cannot really reproduce the unbounded database size issue. 

The db size will grow to its max size before compaction and will not shrink without defrag, but that is normally OK.

> We've grown from ~60MB snapshot to ~4.5GB snapshot within 2 hours.

Is it possible that k8s does use > 2GB data at some point within the 2 hours range? We need a real reproduce to move forward I think.

I also write a simple etcd simulation the workload. It is more stressful than k8s, but still I cannot reproduce the problem.

Here is the script I wrote:

https://gist.github.com/xiang90/6fc371f7fad4b3cea1d72ef132855245

You can tune the paras: compaction duration, external snapshot duration, and max num of keys.

**Comment by wojtek-t** [comment] 2017-05-02 08:07
> The db size will grow to its max size before compaction and will not shrink without defrag, but that is normally OK.

Yes agree. This is fine.

> Is it possible that k8s does use > 2GB data at some point within the 2 hours range? We need a real reproduce to move forward I think.

I'm trying to look into logs, but so far didn't get anything useful I can share.
I think that it had to be some special kind of workload, because the cluster was pretty small (less than 10 nodes) and there wasn't that much happening there.

**Comment by wojtek-t** [comment] 2017-05-02 08:38
I looked also into etcd logs and I don't see anything suspicious there over those 2 hours. The logs look exactly the same as they look in all other clusters.

**Comment by wojtek-t** [comment] 2017-05-02 09:22
I also looked into apiserver logs, and didn't find anything super strange. In particular, there weren't many deletions in the meantime, so the size of DB shouldn't shrink during that time when we grown DB.

@xiang90 - is there any tool that I can potentially use to inspect what is using that space in the etcd snapshot file?

**Comment by xiang90** [comment] 2017-05-03 17:38
> is there any tool that I can potentially use to inspect what is using that space in the etcd snapshot file?

If you want to inspect etcd keys/values, restoring a new one member etcd server from that snapshot is the best option there: see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster

I would suggest you to inspect etcd keys from all snapshot first. Then we can see if one of the snapshots actually contains a huge number of real keys. 

etcd DB fils is a raw boltdb file. There is no good way to inspect the raw database pages without modifying the source code. But you can inspect the db files with boltdb command line tool here: https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go. Info and pages are useful. If you can provide these information to me (or you can investigate?), it can be helpful.

**Comment by xiang90** [comment] 2017-05-03 17:40
@mml @wojtek-t 

I know you guys run quite a few k8s clusters with etcd3 backend. How often does the issue appear? Does it appear on all of your etcd clusters? Or just one of them? Or a handful of them? What is the percentage?

**Comment by lavalamp** [comment] 2017-05-03 18:32
So far it is rare. We are not sure what the trigger is. I can say in 5gb backup, the last actual key appears 32mb into the file. The rest of it is 0 bytes and stuff that appears to be little-endian 8 byte ints counting up, although. starts at 10000000 00000000 (not at 0100...) and continues to 356f0300 00000000, although it skips some values at the beginning. Then a big chunk of 0 bytes. Then it repeats this, skipping different values at the beginning.

It is still possible that we are performing a sequence of writes that legitimately makes the file look like this, I guess, but I am leaning towards the belief that we're somehow triggering an etcd bug.

**Comment by xiang90** [comment] 2017-05-03 18:42
@lavalamp Can you try to run boltdb cmd pages/info against the snapshot file? Some rough info from these commands can be helpful.

**Comment by lavalamp** [comment] 2017-05-03 19:35
@xiang90 sent to you on slack.

**Comment by lavalamp** [comment] 2017-05-03 19:40
In the pages output, there's a page "freelist" with 65535 items. I think someone has an int underflow bug.

**Comment by lavalamp** [comment] 2017-05-03 20:11
Hm actually in the code 0xffff is a marker value meaning that many or more. https://github.com/boltdb/bolt/blob/2e25e3bb4285d41d223bb80b12658a2c9b9bf3e3/freelist.go#L167

**Comment by lavalamp** [comment] 2017-05-03 20:30
I used the bolt dump command to print out the free list block. Something is clearly wrong, the block starts

```
2879000 1521 0200 0000 0000 1621 0200 0000 0000
2879010 1721 0200 0000 0000 1821 0200 0000 0000
2879020 1921 0200 0000 0000 1a21 0200 0000 0000
2879030 1b21 0200 0000 0000 1c21 0200 0000 0000
2879040 1d21 0200 0000 0000 1e21 0200 0000 0000
2879050 1f21 0200 0000 0000 2021 0200 0000 0000
2879060 2121 0200 0000 0000 2221 0200 0000 0000
2879070 2321 0200 0000 0000 2421 0200 0000 0000
```

The first thing in the block should be the count, but it is clearly just part of whatever sequence is there.

**Comment by lavalamp** [comment] 2017-05-03 21:06
The page command agrees with me.

```
$ bolt page snapshot.db 10361
Page ID:    139541
Page Type:  leaf
Total Size: 4096 bytes
Item Count: 2

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4ed640, 0xc42000e1a0)
        /usr/local/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
main.(*PageCommand).PrintLeaf(0xc420053da8, 0x588300, 0xc420040010, 0xc420092000, 0x1000, 0x1000, 0x1, 0x17)
        /usr/local/pkgsets/go1.7.4/global/src/github.com/boltdb/bolt/cmd/bolt/main.go:542 +0x624
main.(*PageCommand).Run(0xc420053da8, 0xc42000a520, 0x2, 0x2, 0x0, 0x0)
        /usr/local/pkgsets/go1.7.4/global/src/github.com/boltdb/bolt/cmd/bolt/main.go:490 +0x716
main.(*Main).Run(0xc420053f08, 0xc42000a510, 0x3, 0x3, 0xc4200220b8, 0x0)
        /usr/local/pkgsets/go1.7.4/global/src/github.com/boltdb/bolt/cmd/bolt/main.go:112 +0x4df
main.main()
        /usr/local/pkgsets/go1.7.4/global/src/github.com/boltdb/bolt/cmd/bolt/main.go:64 +0xf0
```

**Comment by xiang90** [comment] 2017-05-03 21:08
@lavalamp 

This seems like a boltdb issue (at least, related). Do you mind creating an issue here: https://github.com/boltdb/bolt?

**Comment by xiang90** [comment] 2017-05-03 21:15
@lavalamp 

> Page Type:  leaf

The page type should be `freelist`, no? Is this the same pages you sent me over slack?

**Comment by lavalamp** [comment] 2017-05-03 21:52
I am possibly mixing up page ids and block numbers.

**Comment by lavalamp** [comment] 2017-05-03 21:59
Pages 0 and 1 give two different locations for the freelist, which both seem to give valid free lists.

```
Page ID:    0
Page Type:  meta
Total Size: 4096 bytes
Version:    2
Page Size:  4096 bytes
Flags:      00000000
Root:       <pgid=131>
Freelist:   <pgid=8354>
HWM:        <pgid=225078>
```

```
Page ID:    1
Page Type:  meta
Total Size: 4096 bytes
Version:    2
Page Size:  4096 bytes
Flags:      00000000
Root:       <pgid=131>
Freelist:   <pgid=7919>
HWM:        <pgid=225078>
```


```
Page ID:    7919
Page Type:  freelist
Total Size: 1781760 bytes
Item Count: 65535

222238
123
... (many lines omitted)
68373
```

```
Page ID:    8354
Page Type:  freelist
Total Size: 1781760 bytes
Item Count: 65535

222237
123
... (many lines omitted)
68373
```

**Comment by lavalamp** [comment] 2017-05-03 22:02
Yet the pages command clearly labels the first column as "page id" and says both 7919 and 8354 are free. Maybe this database is corrupt such that sequential page access doesn't work, but random page access does?

**Comment by lavalamp** [comment] 2017-05-03 22:19
hm, I was comparing pages command from the wrong snapshot. The correct snapshot indeed lists 8354 as the freelist (7919 is free).

**Comment by lavalamp** [comment] 2017-05-03 22:32
Obviously not the problem we're looking for but still worth tracking: https://github.com/boltdb/bolt/issues/681

**Comment by lavalamp** [comment] 2017-05-03 22:36
The actual last free block is 210031, not 68373.

**Comment by xiang90** [comment] 2017-05-03 22:38
@lavalamp 

But the check commands only say `1252482` and `1252483` is unreachabled. So the pages after `210031` should be still tracked by the freelist, no?

**Comment by xiang90** [comment] 2017-05-03 22:40
xref: https://github.com/coreos/etcd/issues/7870

etcd will track the snapshot pending duration, which might be the root cause of the unexpected growth of the db file. (We are still uncertain about the actual cause)

**Comment by lavalamp** [comment] 2017-05-03 22:57
Sorry, for that snapshot the last free block is 1252483 (1252482 is also in the free list). The total number of free blocks is 1255689.

**Comment by xiang90** [comment] 2017-05-03 23:34
@lavalamp Ah... OK. 1252483 is marked as "branch" (b+tree intermediate node). It should not be a free page listed in freelist, right? So the db file still seems to be corrupted somehow.

**Comment by lavalamp** [comment] 2017-05-04 00:36
Yeah.

```
$ bolt page snapshot.db 1252483
Page ID:    1249742
Page Type:  branch
Total Size: 4096 bytes
Item Count: 19

"": <pgid=1249745>
"": <pgid=1249747>
"": <pgid=1249749>
"": <pgid=1249751>
"": <pgid=1249753>
"": <pgid=1249755>
"": <pgid=1249757>
"": <pgid=1249759>
"": <pgid=1249761>
"": <pgid=1249763>
"": <pgid=1249765>
"": <pgid=1249767>
"": <pgid=1249769>
"": <pgid=1249771>
"": <pgid=1249773>
"": <pgid=1249775>
"": <pgid=1249777>
"": <pgid=1249779>
"": <pgid=1249781>
```

I am confused that the page ID reported is not the page ID I passed to the command, but maybe that's how branch pages work.

**Comment by wojtek-t** [comment] 2017-05-04 20:24
@lavalamp @xiang90 - what else can we do to debug the issue? Any ideas?

**Comment by xiang90** [comment] 2017-05-04 20:27
@wojtek-t 

At this point, I am 90% sure the issue is not from k8s code.

We are going to implement https://github.com/coreos/etcd/issues/7870, and probably back port it to both 3.0 and 3.1.

Then we need to run k8s against this patched etcd to see if this is a problem from etcd itself or from boltdb when the snapshot growth happens.

**Comment by xiang90** [comment] 2017-05-04 20:28
@wojtek-t 

It would be helpful if we can reproduce this issue. The etcd team will also develop a tool to strip out sensitive data, so that we can debug customer's data directory. But it might take us a while to finish.

**Comment by wojtek-t** [comment] 2017-05-05 07:27
@xiang90 - great, thanks a lot for all the help with it!

**Comment by wojtek-t** [comment] 2017-05-09 13:32
@xiang90 - do you have any findings about it?

**Comment by wojtek-t** [comment] 2017-05-15 07:00
@xiang90 - friendly ping. Were you guys able to find anything? It seems we are hitting this problem from time to time.

**Comment by xiang90** [comment] 2017-05-15 16:04
@wojtek-t Sorry for the late response. No, we did not find anything. @mml's reproduce in this issue does not make sense to me as I mentioned above.

I discussed with @lavalamp a few days ago. boltdb clearly has issues, but we are not sure if it is a symptom or the root cause. And we are not sure how we triggered it.

I am happy to look into this again if we can somehow reproduce it. Or we can get more debugging info (patch etcd with https://github.com/coreos/etcd/issues/7870) when it happens again.

**Comment by wojtek-t** [comment] 2017-05-15 16:54
> @wojtek-t Sorry for the late response. No, we did not find anything. @mml's reproduce in this issue does not make sense to me as I mentioned above.

@xiang90 - no worries. Yes I agree that @mml thing is something completely different and for me this is "working as intended"

> I discussed with @lavalamp a few days ago. boltdb clearly has issues, but we are not sure if it is a symptom or the root cause. And we are not sure how we triggered it.

Is etcd using boltdb internally? I initially had the impression that you were using it only to decode snapshot file, but I guess that's not the case, right? If it is using, can you point me to etcd code where it is using it (just out of curiosity)?

Reproduction is hard - I went through all all apiserver logs from one of our incidents that were "write" operations and 1. there weren't that many of those, 2. there wasn't anything unusual there. So be honest, for me it seems a little bit like some kind of race somewhere.

**Comment by xiang90** [comment] 2017-05-15 17:48
> Is etcd using boltdb internally?

Yes. We merge in mem diff back to boltdb to enable incremental snapshot for v3 (so no sudden IO/CPU usage for doing a full snapshot).

>  If it is using, can you point me to etcd code where it is using it (just out of curiosity)?

https://github.com/coreos/etcd/tree/master/mvcc/backend

> So be honest, for me it seems a little bit like some kind of race somewhere.

Agree. But I have no access to the actual data, and we do not have enough debugging logging. So I do not really know how I can help at this point. Even if I have the data + log, it is still hard to debug without any way to reproduce it.

We are thinking hard on how to help users to debug this kind of things at etcd side. But we do not have any plan yet.

**Comment by wojtek-t** [comment] 2017-05-31 12:56
I filed https://github.com/coreos/etcd/issues/8009 with some data for other cluster.

**Comment by spiffxp** [comment] 2017-05-31 20:18
@kubernetes/sig-scalability-misc do we want this in v1.7?  is this the right sig to own this issue?

**Comment by xiang90** [comment] 2017-06-09 05:26
i think we should close this issue. the description is not accurate. the root cause is found in etcd issue that @wojtek-t mentioned.

**Comment by mml** [comment] 2017-06-09 22:13
The issue title is wrong, but we will need to upgrade to a version of etcd with the fixed version of boltdb before we can mark this fixed.

**Comment by mml** [comment] 2017-06-09 22:14
Currently blocked on coreos/etcd#8009 which is in turn blocked on boltdb code reviews.

**Comment by ConradIrwin** [comment] 2017-08-08 01:09
I'm seeing this in production, for a related reason:

1. We set up a cron job to run every minute.
2. We didn't have quite enough cpu quota to run the jobs.
3. Result is a lot (~1000) of minutely cron jobs in the pending/restarting/Outofcpu states

I tried to delete the cron deployment to fix this, and got the same error message:

```
$ delete deployment cron
Connecting to staging kubernetes...
Error from server: etcdserver: mvcc: database space exceeded
```

Any ideas how I can rescue my cluster would be greatly appreciated

**Comment by wojtek-t** [comment] 2017-08-08 07:09
@ConradIrwin - please try to compact + defrag + disarm your etcd:
https://coreos.com/etcd/docs/latest/op-guide/maintenance.html
Space quota section.

**Comment by ConradIrwin** [comment] 2017-08-08 17:10
Thanks @wojtek-t Will forward your advice to the Google Container Engine engineers working on this.

**Comment by sokoow** [comment] 2017-12-21 15:36
Hey, I was under the impression that this will go into 3.3 release? Any update on this ?

**Comment by akabdog** [comment] 2017-12-21 18:44
I see v3.3.0-rc.0 is available, can someone confirm this is fixed there?

**Comment by xiang90** [comment] 2017-12-21 18:50
@akabdog it should significantly help.

**Closed** 2018-05-20 20:06 UTC
Labels: area/etcd, lifecycle/rotten, priority/important-soon, sig/scalability
