### ISSUE TITLE
kubectl create service does not create apiVersion and kind in the yaml file

### ISSUE THREAD

**Issue by chenpeihai1026** [kubernetes/kubernetes#64823] opened 2018-06-06 09:41 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**: kubectl create service yaml file

**What you expected to happen**: I can use kubectl create --edit -f $filename to edit the service yaml file

**How to reproduce it (as minimally and precisely as possible)**:kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run > /tmp/srv.yaml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):V1.10
- Cloud provider or hardware configuration:none
- OS (e.g. from /etc/os-release):ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):4.4.0
- Install tools:binary
- Others:
when i execute the cmd like this:
`kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run > /tmp/srv.yaml`
the srv.yaml file does not contains apiVersion and kind,see below:
`metadata:
  creationTimestamp: null
  labels:
    app: my-svc
  name: my-svc
spec:
  clusterIP: None
  selector:
    app: my-svc
  type: ClusterIP
status:
  loadBalancer: {}
`

**Comment by liggitt** [comment] 2018-06-06 18:51
duplicate of #61780, fixed in 1.10.1

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#changelog-since-v1100

/close

**Closed by liggitt** 2018-06-06 18:51 UTC
Labels: sig/cli
