### ISSUE TITLE
e2e failure: Kubectl client Simple pod should support port-forward

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#20268] opened 2016-01-28 13:19 UTC
Flaked two times in a row recently (builds #10565 and #10562 in e2e-gce)

@kubernetes/goog-ux

**Comment by spxtr** [comment] 2016-01-28 18:14
Similarly in e2e-gke-ci 10474 earlier today.

**Comment by bprashanth** [comment] 2016-01-28 19:15
Hmm, is this the whole ipv6 vs ipv4 thing again? @ncdc

**Comment by ncdc** [comment] 2016-01-28 19:18
I'm hoping "no". Here's more data:

```
• Failure [6.205 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:992
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:477
    should support port-forward [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:476

    Jan 27 21:41:32.370: Failed http.Get of forwarded port (http://localhost:53418): Get http://localhost:53418: EOF

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:471
```

**Comment by ncdc** [comment] 2016-01-28 19:25
Definitely not the same ipv6 vs ipv4 issue from a few months ago. This is in the kubelet log:

```
server.go:976] error forwarding port 80 to pod nginx_e2e-tests-kubectl-6vua1, uid : exit status 1
```

**Comment by ncdc** [comment] 2016-01-28 19:31
I'm leaning toward this not being a kubectl bug. Because the call to socat returned 1, I'm wondering if something went wrong with the command line invocation of socat. I don't have anything definitive yet, but that's my guess. Unfortunately there's no logging of the args, or of the stderr output from socat, so there's not much to go on. We could try adding those 2 things to help with debugging.

**Comment by lavalamp** [comment] 2016-01-28 19:43
@ncdc Do you have time to add that logging?

**Comment by bgrant0607** [comment] 2016-01-28 19:45
Test case:
```
		It("should support port-forward", func() {
			By("forwarding the container port to a local port")
			cmd, listenPort := runPortForward(ns, simplePodName, simplePodPort)
			defer tryKill(cmd)

			By("curling local port output")
			localAddr := fmt.Sprintf("http://localhost:%d", listenPort)
			body, err := curl(localAddr)
			Logf("got: %s", body)
			if err != nil {
				Failf("Failed http.Get of forwarded port (%s): %v", localAddr, err)
			}
			if !strings.Contains(body, nginxDefaultOutput) {
				Failf("Container port output missing expected value. Wanted:'%s', got: %s", nginxDefaultOutput, body)
			}
		})
```

So the call to curl() apparently returned an error.

**Comment by ncdc** [comment] 2016-01-28 19:47
@lavalamp @bgrant0607 yes I will add the logging now

**Comment by lavalamp** [comment] 2016-01-28 19:47
Thanks, Andy!

**Comment by bprashanth** [comment] 2016-01-28 19:51
yeah it appears to have returned an error because the socat we run in the container on the node to forward ports failed (or something in that pipeline between the kubelet and the container, as you also have noted with the exit 1 log line), thanks for volunteering for adding logs. Fyi V(4) should show up in test logs, though I'm not sure about gke logs which is where the latest failure seems to have come from.

**Comment by bprashanth** [comment] 2016-01-29 02:48
Maybe the nginx pod just needs a readiness probe? 

```
I0129 01:30:00.009793    2502 server.go:1048] POST /stats/container/: (4.946295ms) 200 [[Go-http-client/1.1] 10.244.0.4:50414]
I0129 01:30:00.025639    2502 server.go:1048] GET /stats/kube-system/fluentd-cloud-logging-gke-jkns-gke-e2e-ci-cb1d5628-node-lbmb/d9948f33-c61b-11e5-95a4-42010af00006/fluentd-cloud-logging: (1.838687ms) 200 [[Go-http-client/1.1] 10.244.0.4:50428]
I0129 01:30:00.115246    2502 docker.go:149] Pulling image nginx without credentials
E0129 01:30:01.829710    2502 server.go:976] error forwarding port 80 to pod nginx_e2e-tests-kubectl-sbmf8, uid : exit status 1: 2016/01/29 01:30:01 socat[7593] E connect(3, AF=2 127.0.0.1:80, 16): Connection refused
I0129 01:30:01.892650    2502 kubelet.go:2286] SyncLoop (UPDATE, "api"): "nginx_e2e-tests-kubectl-sbmf8(cfcacb45-c627-11e5-95a4-42010af00006)"
```

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ci/10480/consoleFull

https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gke-ci/10480/artifacts/107.178.217.129%3A22-kubelet.log

**Comment by lavalamp** [comment] 2016-02-02 18:49
@ncdc Have you had a chance to look at the logs from this occurrence?

**Comment by ncdc** [comment] 2016-02-02 18:56
I'm in and out the next few days, so I probably can't do much here this
week. Maybe look into the readiness probe suggestion?

**Comment by lavalamp** [comment] 2016-02-02 22:35
A readiness probe sounds like a reasonable thing to try.

**Comment by bprashanth** [comment] 2016-02-02 23:56
I'll try to do so today, but if anyone wants to step in, IIRC the test create -f examples/pod.json, you'll have to change this to read the json to a struct (maybe like https://github.com/kubernetes/kubernetes/blob/d3b869ae14db522e5fca91a295b8bc870713013f/test/e2e/serviceloadbalancers.go#L267), insert a probe and then create via client.

**Comment by lavalamp** [comment] 2016-02-09 04:49
#20444 has merged, but I'll leave this open for the readyness probe change, which seems like a good idea.

**Comment by wojtek-t** [comment] 2016-02-10 11:59
This has just failed again:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/20857/kubernetes-pull-build-test-e2e-gce/27831/build-log.txt

**Comment by ncdc** [comment] 2016-02-10 14:19
@wojtek-t the failure for 20857 was not the same root cause. I don't believe it is related to this issue.

```
â€¢ Failure [307.808 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1030
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:502
    should support port-forward [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:501

    Feb 10 11:15:20.797: Failed to parse kubectl port-forward output: F0210 11:15:20.797573   23052 portforward.go:115] Unable to execute command because pod is not running. Current status=Pending
```

**Comment by lavalamp** [comment] 2016-02-10 17:56
Looks like the readiness change is necessary after all, then.

**Comment by ncdc** [comment] 2016-02-10 17:57
@lavalamp I'm not sure adding a readiness probe would help the failure in 20857. The pod failed to start after 5 minutes. Right?

**Comment by lavalamp** [comment] 2016-02-10 17:58
@ncdc Oh, right. Maybe this is something completely unrelated then.

**Comment by maisem** [comment] 2016-02-11 20:56
Readiness probe change has been merged. Closing this.

**Closed by maisem** 2016-02-11 20:56 UTC
Labels: component/kubelet, kind/flake, priority/P0, team/CSI
