### ISSUE TITLE
Updating pod-template-hash race

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22451] opened 2016-03-03 19:11 UTC
I'm just documenting a half debug that i did because it's weird, but don't have time to go down a rabbit hole. 
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/31298/consoleFull
https://github.com/kubernetes/kubernetes/pull/22203#issuecomment-191162549
Failed because 2 pods weren't deleted. I think I see the following:   

1. update pod with pod-tempate-hash
2. update rc with pod-template-hash
3. rc manager sees 2 before 1 and create a pod with pod-template-hash (so now we have 2 pods)
4. Rc manager is prematurely deleted
5. Test fails because 2 pods are leaked

How does deployment wait on some signal about 1/2? Why did it think it was safe to delete the RS?

Generation number is updated when the rc manager *sees* the update. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller_utils.go#L40
https://github.com/kubernetes/kubernetes/blob/d0ce85a6d1dfd45cf30fda02980aba6a48409008/pkg/registry/controller/strategy.go#L64

Maybe this is what's confusing us? Does this need to change to "only update generation if rc manager has fulfilled spec"?

Then we can do:    

1. Update pod label
2. Update rc label
3. Wait till rc manager updates generation (this means it has fulfilled the rc label update, which means it must have seen the pod label update OR it created a new pod AND sees the pod label update -- so this could still backfire?).

Maybe I'm totally off about this? 

@janetkuo @nikhiljindal

**Comment by bgrant0607** [comment] 2016-03-04 23:15
Thanks @bprashanth. Yes, this bug sounds totally plausible.

We're going to need a robust solution to server-side cascading deletion generally (#1535). Our current approach can't be made robust and places an unreasonable burden on clients.

We'll likely have to fix this in 1.3.

**Comment by bgrant0607** [comment] 2016-03-06 17:28
In order to prevent this, we'd have to ensure that the RS controller saw the label changes on the pods before updating the selector on the RS.

**Comment by bgrant0607** [comment] 2016-03-06 17:29
We should document this as a known issue with adoption by Deployment in 1.2. #21000

**Comment by bgrant0607** [comment] 2016-03-07 18:25
Will see if we can fix this in 1.2, since it's still causing flakes.

**Comment by bgrant0607** [comment] 2016-03-10 19:29
One idea about how to address this: ReplicaSet could report how many pods' labels match the labels in the pod template in its status. Deployment could await that to report all replicas match (and observedGeneration >= generation) before updating the selector.

**Comment by lavalamp** [comment] 2016-03-11 01:03
Assign to @bgrant0607 to delegate

**Comment by bgrant0607** [comment] 2016-03-11 01:19
@caesarxuchao is working on this

**Comment by caesarxuchao** [comment] 2016-03-14 17:40
Should be fixed by #22847. Please reopen if the issue is not resolved.

**Closed by caesarxuchao** 2016-03-14 17:40 UTC
Labels: area/app-config-deployment, kind/flake, priority/P0, team/ux
