### ISSUE TITLE
HPA defaults are confusing

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#22431] opened 2016-03-03 12:54 UTC
I have the following situation:

1. HPA created via extensions/v1beta1 will have a default value for cpu target utilization set for 80% directly in object (and etcd)
2. HPA created via autoscaling/v1 will not have defaults applied, but HPA controller will use some default policy if nothing is set

When I create HPA via autoscaling/v1 I get the following responses from apiserver:
```
$ curl localhost:8080/apis/autoscaling/v1/horizontalpodautoscalers
{
  "kind": "HorizontalPodAutoscalerList",
  "apiVersion": "autoscaling/v1",
  "metadata": {
    "selfLink": "/apis/autoscaling/v1/horizontalpodautoscalers",
    "resourceVersion": "805"
  },
  "items": [
    {
      "metadata": {
        "name": "php-apache",
        "namespace": "default",
        "selfLink": "/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/php-apache",
        "uid": "5bb48123-e135-11e5-b260-42010af00002",
        "resourceVersion": "786",
        "creationTimestamp": "2016-03-03T11:44:59Z"
      },
      "spec": {
        "scaleTargetRef": {
          "kind": "ReplicationController",
          "name": "php-apache",
          "apiVersion": "v1"
        },
        "minReplicas": 1,
        "maxReplicas": 10
      },
      "status": {
        "currentReplicas": 4,
        "desiredReplicas": 4,
        "currentCPUUtilizationPercentage": 78
      }
    }
  ]
}

$ curl localhost:8080/apis/extensions/v1beta1/horizontalpodautoscalers
{
  "kind": "HorizontalPodAutoscalerList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/horizontalpodautoscalers",
    "resourceVersion": "883"
  },
  "items": [
    {
      "metadata": {
        "name": "php-apache",
        "namespace": "default",
        "selfLink": "/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/php-apache",
        "uid": "5bb48123-e135-11e5-b260-42010af00002",
        "resourceVersion": "859",
        "creationTimestamp": "2016-03-03T11:44:59Z"
      },
      "spec": {
        "scaleRef": {
          "kind": "ReplicationController",
          "name": "php-apache",
          "apiVersion": "v1",
          "subresource": "scale"
        },
        "minReplicas": 1,
        "maxReplicas": 10
      },
      "status": {
        "currentReplicas": 4,
        "desiredReplicas": 4,
        "currentCPUUtilizationPercentage": 79
      }
    }
  ]
}
```

This is correct as we don't want any defaults.

However when I run kubectl or read this object from HPA controller I get the following object (notice defaults applied to `cpuUtilization`):
```
$ cluster/kubectl.sh get hpa php-apache -o json
{
    "kind": "HorizontalPodAutoscaler",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "php-apache",
        "namespace": "default",
        "selfLink": "/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/php-apache",
        "uid": "5bb48123-e135-11e5-b260-42010af00002",
        "resourceVersion": "859",
        "creationTimestamp": "2016-03-03T11:44:59Z"
    },
    "spec": {
        "scaleRef": {
            "kind": "ReplicationController",
            "name": "php-apache",
            "apiVersion": "v1",
            "subresource": "scale"
        },
        "minReplicas": 1,
        "maxReplicas": 10,
        "cpuUtilization": {
            "targetPercentage": 80
        }
    },
    "status": {
        "currentReplicas": 4,
        "desiredReplicas": 4,
        "currentCPUUtilizationPercentage": 79
    }
}
```

AFAIU this is because kubectl will read object in version `extensions/v1beta1`, then translate it to an internal version and apply defaults, then translate it back to `extensions/v1beta1`. As a result I get a different object than talking directly to apiserver.

I think that the solutions is to not apply defaults in conversions in client library.

I believe that this is a blocker for the release. WDYT?

@bgrant0607 @lavalamp @piosz @wojtek-t

**Comment by bgrant0607** [comment] 2016-03-03 15:15
Long-standing issue: #3955

I doubt this is easy to change in the short term. Too high risk for 1.2, anyway.

As far as the API machinery, this is working as intended. 

This is a bug in the HPA implementation.

That field was always set in extensions/v1beta1, so leaving it unset would technically be a breaking change in behavior. Honestly, leaving it unset is not something we normally do in the API. It means that a user's active HPA could change behavior from one Kubernetes release to the next.

I'll think about alternatives. Typical tricks are to set the field in conversion instead and/or involve multiple fields or annotations.

**Comment by bgrant0607** [comment] 2016-03-03 15:21
Actually, this seems like the correct behavior to me.

**Comment by bgrant0607** [comment] 2016-03-03 15:23
Is that an older version of kubectl, or does kubectl GET the object using extensions/v1beta1 by default?

**Comment by bgrant0607** [comment] 2016-03-03 15:26
Ok, 2 weird issues here:
1. That GET via /apis/extensions/v1beta1 doesn't set the field to 80 by default
2. That kubectl is still using /apis/extensions/v1beta1 by default

**Comment by fgrzadkowski** [comment] 2016-03-03 15:34
Kubectl uses `extensions/v1beta1` by default. AFAIU it's impossible to configure it in kubectl, i.e. user cannot print object in either `autoscaling/v1` or `extensions/v1beta1`.

I think the problem is that `kubectl` and other clients see a different object version than what apiserver returns.

From HPA features perspective I think that the apiserver side is working ok.
1. If we create object in `v1beta1` it will have default forever (object in etcd has it). Upgrading to v1 will work and will not change anything.
2. If we create object in v1 and then read it in v1beta1 it will not have defaults, which is also expected and inline with the documentation. If we read this object via `extenstions/v1beta1` I think it should not have the default.

The problems is that HPA controller will never see policy unset as it will read objects through `extensions/v1beta1` and will always have the default set.

**Comment by bgrant0607** [comment] 2016-03-03 15:48
This field probably needs to be set in conversion rather than in defaulting.

**Comment by bgrant0607** [comment] 2016-03-03 15:50
I think you're also running into #13929

**Comment by fgrzadkowski** [comment] 2016-03-03 16:11
I think we agree that we've made a breaking change between `extensions/v1beta1` and `autoscaling/v1` by not setting defaults. This introduced the problem that clients reading through `v1beta1` will see cpu utilization set to 80% even if they haven't expected this (`autoscaling/v1` should not change the object). HPA controller will also see this default even for objects created via `autoscaling/v1`. Once we switch client library to use `autoscaling/v1` behavior for users may change (HPA controller will stop seeing default utilization set to 80% and will apply default policy hardcoded in HPA controller code), which is something we want to avoid.

I see two options:
1. Break `extensions/v1beta1` and stop setting the default at all
2. Move HPA controller and kubectl to using HPA objects in `autoscaling/v1` by default

If we choose 2) users we will have the expected behavior, but once we add ability to specify api version in kubectl users will see the same problem again if they specify `extensions/v1beta1` manually.

If we choose 1) we will break expectations for `extensions/v1beta1` (existing objects will work as they have, but new objects will not have defaults set), but at least everything will be clear and will work as expected - neither `extensions/v1beta1` nor `autoscaling/v1` will set default in object itself.

Personally I think that 1) is a better option. @bgrant0607 What's your opinion on that? Any other options I've missed?

**Comment by DirectXMan12** [comment] 2016-03-03 16:16
cc @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment] 2016-03-03 16:19
cc @deads2k

**Comment by deads2k** [comment] 2016-03-03 16:23
@kubernetes/rh-ux @kargakis I remember seeing activity on our side related to this particular setting on an HPA.

**Comment by bgrant0607** [comment] 2016-03-03 16:25
We were trying to not break 1.1 hpa controller, which we would if the field were ever unset in v1beta1.

I recommend setting the field in conversion and document the rest as known issues

**Comment by bgrant0607** [comment] 2016-03-03 16:27
Another option is a sentinel value for "up to controller", like 0 or -1

**Comment by DirectXMan12** [comment] 2016-03-03 16:36
Personally, I'd argue that changing the behavior of `extensions/v1beta1` could be very confusing for users, especially if they were counting on the "default to 80%" behavior, and then suddenly it wasn't there.

> Another option is a sentinel value for "up to controller", like 0 or -1

This also sounds reasonable.  I'd argue for either option 2 or the sentinel value.  The sentinel value seems to prevent most of the issues I have with options 1 and 2 (it doesn't break `extensions/v1beta1`, and it doesn't cause weird behavior between `autoscaling/v1` and `extensions/v1beta1`).  Even with the sentinel value, I'd still argue that the HPA controller and kubectl should probably be switched over to `autoscaling/v1`, though.

**Comment by bgrant0607** [comment] 2016-03-03 17:13
Ok, at the office now.

What's the storage version?

**Comment by bgrant0607** [comment] 2016-03-03 17:14
We should also document that users should use the v1 API until kubectl, the apiserver, and HPA controller all have been updated.

ref #4855

**Comment by bgrant0607** [comment] 2016-03-03 17:14
should not use

**Comment by bgrant0607** [comment] 2016-03-03 17:18
Does version negotiation across API groups work yet @lavalamp ?

If not, and we moved kubectl to v1 by default, then a newer kubectl wouldn't work with older apiservers.

**Comment by bgrant0607** [comment] 2016-03-03 17:20
Ref #14895

**Comment by fgrzadkowski** [comment] 2016-03-03 17:20
@bgrant0607 Storage version is currently `extensions/v1beta`.

@DirectXMan12 The behavior would be still the same (it so happens that the current default policy in HPA controller is using 80% utilization). The difference would be that the object would not have this field set after creation.

**Comment by bgrant0607** [comment] 2016-03-03 17:25
@fgrzadkowski Does any part of HPA not work at the moment, or you're just worried it would appear odd to the user?

**Comment by fgrzadkowski** [comment] 2016-03-03 17:35
The behavior of HPA controller is correct, because the default values set for objects in version `extensions/v1beta1` is the same as the default policy which is hardcoded in HPA controller (targeted for `autoscaling/v1` objects). 

From user perspective, the problem that I see is that kubectl prints something else that apiserver returns and something which I wouldn't expect from the documentation. However if we say that we don't recommend to use `autoscaling/v1` until controllers and kubectl use it (i.e. `v1.3`) than this is probably less of a problem.

Is it fair to say to the users the following?
```
For now it's not yet recommended to use autoscaling/v1 as you might get weird/unexpected results in kubectl output. Starting from 1.3, when we change defaults in kubectl, it should work as expected (as long as you don't force kubectl to use deprecated extension/v1beta1).
```
If we can say this, then I think we can just close this issue and make good release notes :)

**Comment by fgrzadkowski** [comment] 2016-03-03 17:45
From a slightly different side - my understanding is that if we introduce a breaking change in beta API then it means we not only include this change in v1, but also change beta API. Is my understanding correct? If that's the case, then I guess we should just change `extensions/v1beta1` and stop setting defaults for newly created objects.

**Comment by kargakis** [comment] 2016-03-03 17:59
> but new objects will not have defaults set

Does this really matter since the controller will use the same default value in case it is unspecified in the hpa?

**Comment by liggitt** [comment] 2016-03-03 18:06
> Does this really matter since the controller will use the same default value in case it is unspecified in the hpa?

internally it might behave the same, but a missing field can break clients that depend on the defaulting behavior of extensions/v1beta1, and don't handle a nil value

agree on setting in conversion to extensions/v1beta1, though it makes me question moving the default from API-level (where it can be known by all API consumers, and reasonably handled when converting to extensions/v1beta1) to controller-level in autoscaling/v1

**Comment by bgrant0607** [comment] 2016-03-03 18:07
I would just document this.

Users should not use the v1 API until kubectl, the apiserver, and HPA controller all have been updated, and when they do use it, the 1.2 kubectl will show the targetCPUUtilizationPercentage as 80 in the case that it is unset, which is how HPA interprets the value in 1.2.

**Comment by bgrant0607** [comment] 2016-03-03 18:12
@liggitt 

>> though it makes me question moving the default from API-level (where it can be known by all API consumers, and reasonably handled when converting to extensions/v1beta1) to controller-level in autoscaling/v1

Yes, that's the reason we made default logic explicit.

In this case, one could argue that user-specified target utilization is a constraint on the auto-scaling behavior, which is expected to become more sophisticated over time -- think of it similar to nodeSelector's affect on scheduling policy.

**Comment by fgrzadkowski** [comment] 2016-03-03 18:36
Ok, I'll close this issue and open a separate to document this properly.

**Comment by jwforres** [comment] 2016-03-03 19:22
From my understanding of what changed, this now means that a client will have no idea what parameters are being used to auto-scale (when the default is used).  This is a big usability problem... think about it from a common user workflow:

1) I'm not sure what scaling parameters I want, I'll pick the default to start with
2) Something's not right and I'm not autoscaling soon enough, I should probably adjust something
3) I have no clue how to tune this because I have no idea what the current target is... let me make a wild guess

**Comment by bgrant0607** [comment] 2016-03-03 21:17
@jwforres Good point. 

However, we do report the observed utilization in status. Presumably the user would need to set a target lower than the current utilization in your scenario.

Longer term, it's a question of the degree to which the user should have direct control over the policy via threshold knobs, or whether we should express higher-level intent via some other means.

**Comment by lavalamp** [comment] 2016-03-04 00:29
Added to my 1.3 list.

**Comment by danmcp** [comment] 2016-03-04 18:02
@bgrant0607 

>However, we do report the observed utilization in status. Presumably the user would need to set a target lower than the current utilization in your scenario.

Part of what makes this difficult is there could be a very large difference between limit and request (especially for CPU since overcommit is common).  And because HPA is based off of request, an 80% default might be a tiny fraction of limit.   Which could result in the auto scaling being super aggressive for some time period before the user has a chance to take observed utilization into account.  So it seems necessary to let the user understand what the default percentage will be set to for them to have a shot at understanding what's happening with their app.

**Comment by bgrant0607** [comment] 2016-03-04 23:52
@danmcp I understand the concern.

**Comment by bgrant0607** [comment] 2016-03-04 23:53
Oops. Reopened to figure out how to make this less confusing and more actionable in 1.3.

**Comment by fgrzadkowski** [comment] 2016-03-07 11:20
Currently using the default policy would not be a recommended setup for production use-cases, but I think it's a good starting point for a user. We'll obviously document what default means, but I don't think this should be exposed on the API level.

To give an extreme example, I don't know how kernel scheduler works, but I don't have to as long as it's working good enough. When I see problem I'd read documentation and apply `nice` to tweak the default strategy. 
I'd like to have a similar scenario for HPA user.

Does it make sense?

**Comment by piosz** [comment] 2016-03-18 17:03
Closing in favor of #23196

**Closed by piosz** 2016-03-18 17:03 UTC
Labels: area/autoscaling, priority/P2, team/control-plane
