### ISSUE TITLE
pkg/kubelet/network/cni/cni_test.go is flaky on shippable

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#15239] opened 2015-10-07 17:00 UTC

**Comment by yujuhong** [comment] 2015-10-08 23:02
cc author @dcbw from #14525

**Comment by dcbw** [comment] 2015-10-09 13:58
This has a couple dupes, and we're trying to track debugging in https://github.com/kubernetes/kubernetes/pull/14983.  I can't reproduce on Shippable or locally with multiple machines, so I need to get some more debugging into the test so that others can get some logs.

**Comment by dcbw** [comment] 2015-10-09 14:22
See also https://github.com/kubernetes/kubernetes/issues/14931

**Comment by yujuhong** [comment] 2015-10-09 16:20
Closing as dup of #14931

**Closed by yujuhong** 2015-10-09 16:20 UTC
Labels: area/test, kind/flake, team/cluster
