### ISSUE TITLE
integration flake: casandra failure

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22128] opened 2016-02-27 20:06 UTC
test-cmd.sh failed with the following:

    12:01:47 service "cassandra" created
    12:01:47 
    12:01:47 FAIL!
    12:01:47 Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
    12:01:47   Expected: cassandra:cassandra:cassandra:
    12:01:47   Got:      cassandra:cassandra:cassandra:cassandra:
    12:01:47 (B
    12:01:47 1535 ./hack/test-cmd.sh

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-test-go/8954/build-log.txt

**Comment by bgrant0607** [comment] 2016-02-27 21:28
Also:
kubernetes-jenkins/pr-logs/pull/22129/kubernetes-pull-test-unit-integration/16607

https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L1535

Looks like there should be 1 RC, 1 Pod, 1 Service -- 3 objects. But there are 4. Probably an extra pod.

We've been seeing a lot of suspect behavior from ReplicationController and ReplicaSet (which is basically identical code). Deployment is effectively a stress test for scaling ReplicaSets. 

Not sure if the expectation implementation is still just too broken or whether some of the new optimizations have destabilized the behavior.

cc @mqliang @janetkuo @kargakis @bprashanth

**Comment by goltermann** [comment] 2016-02-27 21:32
https://github.com/kubernetes/kubernetes/pull/21639 was merged yesterday.  Possibly related @jayunit100?

**Comment by goltermann** [comment] 2016-02-27 21:34
That was intended to fix the e2e casssandra example, but the yaml is reused here.

**Comment by bgrant0607** [comment] 2016-02-27 21:39
Good catch @goltermann. Previously the replicas count was 1 initially, whereas now it is being reduced from 2 to 1. That reduction races with the check in test-cmd.sh.

**Comment by jayunit100** [comment] 2016-02-27 21:58
This was broken before 
It's still broken now

The difference is that now it has a chance of passing when the containers are updated :).

**Comment by jayunit100** [comment] 2016-02-27 22:07
By the way, part of this tests changes were to completely decouple scaling behaviour (which is finicky) from the testing of the cassandra example   If integration.sh is relying on dynamic scaling behaviour to test cassandra, we might want to modify that as well, as that is a highly coupled test.

**Comment by bgrant0607** [comment] 2016-02-27 22:11
@jayunit100 The e2e test was broken. Now test-cmd.sh is also broken.

**Comment by bprashanth** [comment] 2016-02-27 22:17
That test is racy unless you pass a timeout. If you do, scale should poll on generation number. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/scale.go#L143
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L187
https://github.com/kubernetes/kubernetes/blob/e827c1cba35b70467751c92889a25c9f73b06980/pkg/client/unversioned/conditions.go#L89

Maybe scale should just figure out a timeout from the diff of desired and required replicas for better UX.

As an aside integration tests have historically been hard to debug because of some obvious problems with logging and the way we run them in parallel, so I'd recommend putting as much into unit/e2es as possible. 

Figuring out the right timeout for integration tests has also been an NP hard problem, because of the concurrency and the fact that we run them in containers and who knows how many instances on a single machine. 

> We've been seeing a lot of suspect behavior from ReplicationController and ReplicaSet (which is basically identical code). Deployment is effectively a stress test for scaling ReplicaSets.
Not sure if the expectation implementation is still just too broken or whether some of the new optimizations have destabilized the behavior.

Expectations maybe non-ideal for various other forms of concurrency, but they should work just like dumb counters. Are we seeing different behavior?

**Comment by bgrant0607** [comment] 2016-02-27 22:21
This particular test isn't the main scale test. I'll just create a pod instead of an RC.

**Comment by bgrant0607** [comment] 2016-02-27 22:21
Yes, all of test-cmd.sh is a flake waiting to happen.

**Comment by jayunit100** [comment] 2016-02-27 22:30
The service end points in the Cassandra containers jar was broken anyway, so I'm surprised this test passed to begin with at all, ((unless it skips pod validation entirely))

**Comment by bgrant0607** [comment] 2016-02-27 22:44
@bprashanth Yes, I'm seeing extremely delayed and/or duplicate deletions.

**Comment by bgrant0607** [comment] 2016-02-27 22:44
@bprashanth I suspect the store.

**Comment by bgrant0607** [comment] 2016-02-28 00:04
Yet another RC-related flake occurred in the PR I created to eliminate this flake.

kubernetes-jenkins/pr-logs/pull/22133/kubernetes-pull-build-test-e2e-gce/30818
```
STEP: Creating a RC of 60 pods and wait until all pods of this RC are running
STEP: creating replication controller cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 in namespace e2e-tests-kubelet-76zbt
Feb 27 15:13:57.524: INFO: Created replication controller with name: cleanup60-c7115171-dda7-11e5-bb6e-42010af00007, namespace: e2e-tests-kubelet-76zbt, replica count: 60
Feb 27 15:14:07.524: INFO: cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 Pods: 58 out of 60 created, 11 running, 24 pending, 23 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Feb 27 15:14:17.527: INFO: cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 Pods: 61 out of 60 created, 43 running, 16 pending, 2 waiting, 0 inactive, 1 terminating, 0 unknown, 0 runningButNotReady 
Feb 27 15:14:17.527: INFO: Number of reported pods for cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 changed: 61 vs 58, pods that changed since the last iteration:
...
Feb 27 15:14:17.528: INFO: Pod cleanup60-c7115171-dda7-11e5-bb6e-42010af00007-8ljn3 was deleted, had phase Pending and host 
...
kubelet
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet.go:159
  Clean up pods on node
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet.go:158
    kubelet should be able to delete 10 pods per node in 1m0s. [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet.go:156

    Expected error:
        <*errors.errorString | 0xc208400020>: {
            s: "Number of reported pods for cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 changed: 61 vs 58",
        }
        Number of reported pods for cleanup60-c7115171-dda7-11e5-bb6e-42010af00007 changed: 61 vs 58
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet.go:132
```

**Comment by bgrant0607** [comment] 2016-02-28 00:07
Filed #22134 for the new flake.

**Closed** 2016-02-28 01:48 UTC
Labels: area/test, kind/flake, priority/P0, team/control-plane, team/ux

**Comment by wojtek-t** [comment] 2016-02-28 09:17
@bgrant0607 - thanks a lot for debugging and fixing!
