### ISSUE TITLE
Kubernetes 1.5.1 does not start on AWS

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#39766] opened 2017-01-11 22:45 UTC
Trying to start Kubernetes 1.5.1 on AWS as:

```
NUM_NODES=2 NODE_SIZE=m3.medium KUBERNETES_PROVIDER=aws ./cluster/kube-up.sh
```
Kubernetes cluster just keeps waiting:

```
... Starting cluster in us-west-2a using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
Uploading to Amazon S3
+++ Staging server tars to S3 Storage: kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel
upload: ../../../../../../var/folders/81/ttv4n16x7p390cttrm_675y00000gn/T/kubernetes.XXXXXX.M3SE9klU/s3/kubernetes-salt.tar.gz to s3://kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/kubernetes-salt.tar.gz
upload: ../../../../../../var/folders/81/ttv4n16x7p390cttrm_675y00000gn/T/kubernetes.XXXXXX.M3SE9klU/s3/bootstrap-script to s3://kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/bootstrap-script
upload: ../../../../../../var/folders/81/ttv4n16x7p390cttrm_675y00000gn/T/kubernetes.XXXXXX.M3SE9klU/s3/kubernetes-server-linux-amd64.tar.gz to s3://kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/kubernetes-server-linux-amd64.tar.gz
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/kubernetes-staging-755bc8de1506d202e17ea5e8f90ab8e2/devel/bootstrap-script
Creating master IAM profile: kubernetes-master-kubernetes-kubernetes-vpc
Creating IAM role: kubernetes-master-kubernetes-kubernetes-vpc
Creating IAM role-policy: kubernetes-master-kubernetes-kubernetes-vpc
Creating IAM instance-policy: kubernetes-master-kubernetes-kubernetes-vpc
Adding IAM role to instance-policy: kubernetes-master-kubernetes-kubernetes-vpc
Creating minion IAM profile: kubernetes-minion-kubernetes-kubernetes-vpc
Creating IAM role: kubernetes-minion-kubernetes-kubernetes-vpc
Creating IAM role-policy: kubernetes-minion-kubernetes-kubernetes-vpc
Creating IAM instance-policy: kubernetes-minion-kubernetes-kubernetes-vpc
Adding IAM role to instance-policy: kubernetes-minion-kubernetes-kubernetes-vpc
Using SSH key with (AWS) fingerprint: SHA256:dX/5wpWuUxYar2NFuGwiZuRiydiZCyx4DGoZ5/jL/j8
Creating vpc.
Adding tag to vpc-c43a88a3: Name=kubernetes-vpc
Adding tag to vpc-c43a88a3: KubernetesCluster=kubernetes
Using VPC vpc-c43a88a3
Adding tag to dopt-6d696b09: Name=kubernetes-dhcp-option-set
Adding tag to dopt-6d696b09: KubernetesCluster=kubernetes
Using DHCP option set dopt-6d696b09
Creating subnet.
Adding tag to subnet-853bebe2: KubernetesCluster=kubernetes
Using subnet subnet-853bebe2
Creating Internet Gateway.
Using Internet Gateway igw-c73b78a3
Associating route table.
Creating route table
Adding tag to rtb-aceaa3cb: KubernetesCluster=kubernetes
Associating route table rtb-aceaa3cb to subnet subnet-853bebe2
Adding route to route table rtb-aceaa3cb
Using Route Table rtb-aceaa3cb
Creating master security group.
Creating security group kubernetes-master-kubernetes.
Adding tag to sg-6b568913: KubernetesCluster=kubernetes
Creating minion security group.
Creating security group kubernetes-minion-kubernetes.
Adding tag to sg-59568921: KubernetesCluster=kubernetes
Using master security group: kubernetes-master-kubernetes sg-6b568913
Using minion security group: kubernetes-minion-kubernetes sg-59568921
Creating master disk: size 20GB, type gp2
Adding tag to vol-01208426aa5552fb3: Name=kubernetes-master-pd
Adding tag to vol-01208426aa5552fb3: KubernetesCluster=kubernetes
Allocated Elastic IP for master: 35.167.202.88
Adding tag to vol-01208426aa5552fb3: kubernetes.io/master-ip=35.167.202.88
Generating certs for alternate-names: IP:35.167.202.88,IP:172.20.0.9,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-master
Starting Master
Adding tag to i-0d9196beec75a079d: Name=kubernetes-master
Adding tag to i-0d9196beec75a079d: Role=kubernetes-master
Adding tag to i-0d9196beec75a079d: KubernetesCluster=kubernetes
Waiting for master to be ready
Attempt 1 to check for master nodeWaiting for instance i-0d9196beec75a079d to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-0d9196beec75a079d to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-0d9196beec75a079d to be running (currently pending)
Sleeping for 3 seconds...
 [master running]
Attaching IP 35.167.202.88 to instance i-0d9196beec75a079d
Attaching persistent data volume (vol-01208426aa5552fb3) to master
2017-01-11T20:42:16.717Z	/dev/sdb	i-0d9196beec75a079d	attaching	vol-01208426aa5552fb3
Cluster "aws_kubernetes" set.
User "aws_kubernetes" set.
Context "aws_kubernetes" set.
Switched to context "aws_kubernetes".
User "aws_kubernetes-basic-auth" set.
Wrote config for aws_kubernetes to /Users/arungupta/.kube/config
Creating minion configuration
Creating autoscaling group
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 2 minions started; ready
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

Deleted the cluster and tried to create/start the cluster again, and same issue.

Is this expected to work?

**Comment by r4j4h** [comment] 2017-01-12 20:56
I can confirm 1.5.1 worked on Vagrant, but due to issues with Helm I reverted to 1.4.7, so I cannot verify if it works in AWS, but using `kops` 1.4.7 definitely works on AWS right now.

**Comment by arun-gupta** [comment] 2017-01-12 21:00
Tried to start again with 1.5.1 and got:

```
 0 minions started; waiting
 2 minions started; ready
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by arun-gupta** [comment] 2017-01-12 21:15
Seems to behave better with 1.5.2:

```
Wrote config for aws_kubernetes to /Users/arungupta/.kube/config
Creating minion configuration
Creating autoscaling group
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 2 minions started; ready
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

..............................................................................................................................................................................Kubernetes cluster created.
Sanity checking cluster...
Attempt 1 to check Docker on node @ 35.164.48.34 ...working
Attempt 1 to check Docker on node @ 35.166.132.171 ...not working yet
Attempt 2 to check Docker on node @ 35.166.132.171 ...working

Kubernetes cluster is running.  The master is running at:

  https://35.164.244.66

The user name and password to use is located in /Users/arungupta/.kube/config.

... calling validate-cluster
No resources found.
Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
No resources found.
Waiting for 2 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 2 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 2 ready nodes. 0 ready nodes, 2 registered. Retrying.
Waiting for 2 ready nodes. 1 ready nodes, 2 registered. Retrying.
Found 2 node(s).
NAME                                         STATUS    AGE
ip-172-20-0-195.us-west-2.compute.internal   Ready     46s
ip-172-20-0-224.us-west-2.compute.internal   Ready     54s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-1               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://35.164.244.66
Elasticsearch is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://35.164.244.66/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by gnufied** [comment] 2017-01-13 03:26
@arun-gupta can you paste generated bootstrap script. It will be there in master node. I think this may be related to - https://gist.github.com/gnufied/17c931f313668415597d21bcf69a8509 

And your master node might be hung in trying to `curl` metadata. I guess - `./kube-up.sh` is kinda broken right now for aws. My suggestion is to use kops for aws deployment.

**Comment by arun-gupta** [comment] 2017-01-13 14:53
`kube-up.sh` is getting deprecated anyway https://github.com/kubernetes/kubernetes/pull/38772. I removed the cluster already. Is it worth starting it again and sharing the logs? :)

**Comment by chrislovecnm** [comment] 2017-01-24 19:24
@arun-gupta I would say that we should close this issue :)  I do not talk for all of sig-aws ... but I do not think it will be fixed.

**Comment by zmerlynn** [comment] 2017-01-24 21:09
1.5.2 seems to have fixed this? Closing.

**Closed by zmerlynn** 2017-01-24 21:09 UTC
Labels: area/platform/aws, sig/aws
