### ISSUE TITLE
Begin supporting etcd3

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20504] opened 2016-02-02 18:37 UTC
There's probably already an issue about this, but none of my searches could find it.

I know @hongchaodeng (and @xiang90?) are interested in doing much of the work. @krousey may be able to help.

Off the top of my head, we'll need:
- Flag enable etcd 2 or etcd 3, support both for a significant period of time.
- Adjust storage.Interface as needed.
- Adjust deployment scripts, again we need both to work in parallel for one, possibly two, point releases.
- Provide update scripts/instructions to switch over a running cluster, ideally with no downtime.

**Comment by xiang90** [comment] 2016-02-02 18:43
@lavalamp yea. @hongchaodeng and me will start the work soon.

@smarterclayton anyone at Redhat is interested in this?

@HardySimpson anyone from Huawei?

**Comment by smarterclayton** [comment] 2016-02-02 18:45
We are indeed interested in it - I'm probably going to be very heavily involved, as is @derekwaynecarr and @ncdc, and @timothysc as well.

**Comment by krousey** [comment] 2016-02-02 18:47
@xiang90 Is there documentation for the v3 api? I've only been able to find the v2 api. Or is it the same?

**Comment by xiang90** [comment] 2016-02-02 18:49
@krousey 

https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

It is a gRPC defined service API. Check the proto directly. Thanks!

**Comment by krousey** [comment] 2016-02-02 19:03
@xiang90 I'm curious about the Range api. I see that I can pin it to a resource version, and define a half-open range of `[start, end)`. And the response has a boolean indicating that there is more. I assume you expect people to redo the same RangeRequest with the same resource version, but update the start to the key of the last element they saw? Like `[last_seen, end)`? Would that mean we'd see the same key/value pair twice?

(Also, this is probably not the best place to have this discussion. Where would be more appropriate?)

**Comment by timothysc** [comment] 2016-02-02 19:09
Given that I did the 2.2 client update, the touch points should all be isolated sans kube2sky.  I didn't think it was ready till march/april. @xiang90

**Comment by xiang90** [comment] 2016-02-02 19:59
@krousey 

>  Would that mean we'd see the same key/value pair twice?

You can do [lasts_seen+1, end)

> (Also, this is probably not the best place to have this discussion. Where would be more appropriate?)

You can always open an issue in etcd repo.

**Comment by smarterclayton** [comment] 2016-02-02 21:02
We should get a proposal going for the process of transforming, testing, and ensuring that it is not disruptive to the other 1.3 work.  We are probably going to push etcd3 hard for scale reasons, and now that the client is coming together there's no better time to get going than now.

**Comment by HardySimpson** [comment] 2016-02-03 01:20
@kevin-wangzefeng @magicwang-cn @alfred-huangjian

**Comment by magicwang-cn** [comment] 2016-02-03 01:23
great news!

**Comment by wojtek-t** [comment] 2016-02-03 14:19
I'm also interested in it and may be able to help with that a bit...

**Comment by timothysc** [comment] 2016-02-03 15:11
With the storage work done, you should be able to wholesale prototype a new back-end and not have to transform the existing.  The testing jig will need to be updated though.

**Comment by derekwaynecarr** [comment] 2016-02-03 20:52
+1

**Comment by wojtek-t** [comment] 2016-02-04 07:42
Definitely - it would be super helpful.

**Comment by magicwang-cn** [comment] 2016-02-15 02:20
@sunshine-zhd1229

**Comment by wojtek-t** [comment] 2016-02-15 07:26
I have met with @hongchaodeng last week and they are just starting doing the prototype roughly now. Once they have a prototype, the will start doing the real work. I will be coordinating with them and helping them from the k8s side.

**Comment by wojtek-t** [comment] 2016-02-15 07:26
So assigning to me, although probably most of the work will be done by CoreOS folks.

**Comment by timothysc** [comment] 2016-02-15 17:02
@wojtek-t please /cc me on reviews.

**Comment by wojtek-t** [comment] 2016-02-16 07:23
@timothysc sure
Although, it will probably take few weeks before the first one. But sure - I will cc you.

**Comment by timothysc** [comment] 2016-02-16 15:02
thx.

**Comment by hongchaodeng** [comment] 2016-03-03 21:27
I opened #22448 for a specific discussion of next step. Please feel free to discuss any thoughts there.

**Comment by wojtek-t** [comment] 2016-03-04 08:53
We should probably deduplicate issues. @lavalamp - are you fine with closing this one?

**Comment by lavalamp** [comment] 2016-03-04 23:21
I agree we should discuss it in one place, but #22448 is the dup ;)

The requirements in my first comment are not echoed in #22448, so I would prefer to close #22448.

**Comment by smarterclayton** [comment] 2016-07-08 03:52
@hongchaodeng Looking at what it would take to bump to etcd3 in this repo.  It looks like rkt depends on a GRPC from Feb 24, while the etcd3 APIs depend on the newer GRPC.  From a hacked together refresh:

```
go build ./cmd/hyperkube/
# github.com/coreos/rkt/api/v1alpha
../../github.com/coreos/rkt/api/v1alpha/api.pb.go:1110: cannot use _PublicAPI_GetInfo_Handler (type func(interface {}, "github.com/coreos/rkt/vendor/golang.org/x/net/context".Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
../../github.com/coreos/rkt/api/v1alpha/api.pb.go:1114: cannot use _PublicAPI_ListPods_Handler (type func(interface {}, "github.com/coreos/rkt/vendor/golang.org/x/net/context".Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
../../github.com/coreos/rkt/api/v1alpha/api.pb.go:1118: cannot use _PublicAPI_InspectPod_Handler (type func(interface {}, "github.com/coreos/rkt/vendor/golang.org/x/net/context".Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
../../github.com/coreos/rkt/api/v1alpha/api.pb.go:1122: cannot use _PublicAPI_ListImages_Handler (type func(interface {}, "github.com/coreos/rkt/vendor/golang.org/x/net/context".Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
../../github.com/coreos/rkt/api/v1alpha/api.pb.go:1126: cannot use _PublicAPI_InspectImage_Handler (type func(interface {}, "github.com/coreos/rkt/vendor/golang.org/x/net/context".Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
```

Do we need to bump rocket in order to move to etcd 3?

**Comment by hongchaodeng** [comment] 2016-07-08 03:57
@yifan-gu and I already had discussion on this and the answer is yes.
There is a couple of bug fixes in grpc that we would like to get in.

**Comment by smarterclayton** [comment] 2016-07-08 03:58
Ok.  I verified that bumping gogoproto and golang/proto won't break us, and did a quick round of tests to verify everything still worked afterwards.

**Comment by xiang90** [comment] 2016-07-08 03:59
@smarterclayton Can we hold that off for a few days? There is still a few issues in today's go-grpc. Most of them will be resolved by grpc GA release within this month.

**Comment by smarterclayton** [comment] 2016-07-08 04:40
Looking at the schedules, I'll definitely want a lot of soak time with etcd3 in Kube.  Having to wait until near the end of the month is somewhat concerning.  Do they have a date for their GA release?

**Comment by xiang90** [comment] 2016-07-08 04:51
@smarterclayton Actually we are waiting for one thing: https://github.com/grpc/grpc-go/pull/748. It will probably get merged next week. Then we will bump the dependency in etcd, then we bump etcd3 in k8s. Sounds good?

**Comment by jeremyeder** [comment] 2016-07-08 11:44
@xiang90 are there any etcd3 benchmarks available (comparisons to etcd2)?

**Comment by xiang90** [comment] 2016-07-08 12:57
@jeremyeder https://github.com/coreos/etcd/blob/master/Documentation/op-guide/performance.md#benchmarks

**Comment by jeremyeder** [comment] 2016-07-08 13:06
@xiang90 are there etcd2 numbers as well for comparison?

**Comment by xiang90** [comment] 2016-07-08 13:15
@jameskyle 

https://camo.githubusercontent.com/6f1a106a18eec2532d8b6af52ce9ab53b5542292/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f64627465737465722d726573756c74732f323031363034313630312f30312d7468726f7567687075742e737667

The graph is a little noise. It compres etcd2, etcd3, consul, zookeeper for putting 2M keys. etcd3 was the most thoughput stable one, and finished first. As number of keys grow, other systems were all stressed out, and leader election happened. ZooKeeper finished next. etcd2, Consul suffered from serval issues.

**Comment by xiang90** [comment] 2016-07-08 13:18
@jeremyeder I would suggest you to benchmark again in your own environment to get a more trustable result. On the other side, switching to etcd3 wont improve k8s performance significantly. (But it would help with openshift's monster etcd cluster with 700MB snapshot) The bottleneck is not at etcd side at the moment.

**Comment by jeremyeder** [comment] 2016-07-08 13:29
@xiang90 thanks.

**Comment by wojtek-t** [comment] 2016-08-10 09:27
@xiang90 @hongchaodeng - looking into etcd documentation it seems that migration tool (I believe that we all agree that we want to do offline migration - @smarterclayton @lavalamp - do you agree?) takes a user-provider transformer:
https://github.com/coreos/etcd/blob/master/etcdctl/README.md#migrate-options

Do we need any transformer in Kubernetes?

**Comment by timothysc** [comment] 2016-08-10 18:10
I used the one from a coreos doc a while back then removed TTL objects that was all.

**Comment by wojtek-t** [comment] 2016-08-11 09:26
So I did some manual experiments (to be specific, I did them in kubemark cluster, since it seemed easier) and it seems that migration seems to work (well, my experiments pretty simple, and all that I figured out is that there isn't anything terribly wrong).

Here is what I did:
```
From desktop:
> kubectl --kubeconfig=test/kubemark/resources/kubeconfig.kubemark run my-pod --image=gcr.io/google_containers/pause:2.0

From kubemark-master VM: 
> ps aux | grep apiserver
> sudo kill -9 <apiserver_pid>
> sudo docker ps
> sudo docker stop <container_ids_of_etcd_instances>
> sudo docker run --net=host -e "ETCDCTL_API=3" -v /var/etcd/data-events:/var/etcd/data -d gcr.io/google_containers/etcd:3.0.3 /usr/local/bin/etcdctl migrate --data-dir=/var/etcd/data
> sudo docker run --net=host -e "ETCDCTL_API=3" -v /var/etcd/data:/var/etcd/data -d gcr.io/google_containers/etcd:3.0.3 /usr/local/bin/etcdctl migrate --data-dir=/var/etcd/data

> sudo docker run --net=host -v /var/etcd/data-events:/var/etcd/data -d \
                gcr.io/google_containers/etcd:3.0.3 /usr/local/bin/etcd \
                --listen-peer-urls http://127.0.0.1:2381 \
                --advertise-client-urls=http://127.0.0.1:4002 \
                --listen-client-urls=http://0.0.0.0:4002 \
                --data-dir=/var/etcd/data
> sudo docker run --net=host -v /var/etcd/data:/var/etcd/data -d \
        gcr.io/google_containers/etcd:3.0.3 /usr/local/bin/etcd \
        --listen-peer-urls http://127.0.0.1:2380 \
        --advertise-client-urls=http://127.0.0.1:4001 \
        --listen-client-urls=http://0.0.0.0:4001 \
        --data-dir=/var/etcd/data

> // Remove old data
> sudo docker exec -i -t 0d6136796154 /bin/sh
> ETCDCTL_API=2 /usr/local/bin/etcdctl rm /registry --recursive
> sudo docker exec -i -t 1677af20bd4f /bin/sh
> ETCDCTL_API=2 /usr/local/bin/etcdctl --peers=http://127.0.0.1:4002 rm /registry --recursive

> sudo kubernetes/server/bin/kube-apiserver --address=0.0.0.0 --etcd-servers=http://127.0.0.1:4001 --etcd-servers-overrides=/events#http://127.0.0.1:4002 --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key --client-ca-file=/srv/kubernetes/ca.crt --token-auth-file=/srv/kubernetes/known_tokens.csv --secure-port=443 --basic-auth-file=/srv/kubernetes/basic_auth.csv --target-ram-mb=600 --runtime-config=extensions/v1beta1 --v=2 --delete-collection-workers=16 --service-cluster-ip-range=10.0.0.0/16 --storage-backend=etcd3 > apiserver.log &

From desktop:
> kubectl --kubeconfig=test/kubemark/resources/kubeconfig.kubemark get pods
```

It seems that it mostly works.

Unless I'm not missing anything, the remaining things are:
- figure out what we will do with events (TTLs are not translated)
- turn this into script
- do some more extensive testing of it

**Comment by xiang90** [comment] 2016-08-11 17:00
@wojtek-t 

> figure out what we will do with events (TTLs are not translated)

Here is my thought: Create a lease with 24 hour TTL (or the previous longest duration). Attached the keys with TTL to this lease. 

If we are happy about this approach, I guess @hongchaodeng can help to implement this in a day or two :)

**Comment by wojtek-t** [comment] 2016-08-17 07:43
@hongchaodeng - will you provide such transformer? [the length of the least should be configurable]

**Comment by hongchaodeng** [comment] 2016-08-17 17:57
Here's a plan to do events migration:
- During offline process, transformer will write a special key "_need_gc_events" => value "/events-dir-in-etcd"
- We need to check the special key. If existed, attach all events to a new lease. Delete the special key. There are two options here:
  - Automatically done on apiserver bootstrap. Or,
  - Have another tool run outside apiserver. It's fine to run it in any order with apiserver. Even if some events are attached to lease by apisrever, they will be reattached to new lease by the tool.

@wojtek-t WDYT?

**Comment by hongchaodeng** [comment] 2016-08-17 19:21
I have worked out something similar to above routine:
- First I run through the migration and make transformer print out all [TTL keys](https://github.com/hongchaodeng/etcdupgrade/blob/ad437b344da1dc376d563ff7a8783117504532b9/main.go#L21)
- Then I have [another program](https://github.com/hongchaodeng/etcdupgrade/blob/master/attachlease/main.go) that parse the files, and attach all keys to a routine.

Let me know if you are interested in this workflow and needs more help. Just copy my program if needed.

**Comment by wojtek-t** [comment] 2016-08-18 06:44
@hongchaodeng @xiang90 
Hmm - I really thought that it would be possible to do it with just a transformer and without yet another script that can be run only when etcd is up.

If that's not possible, I have a slightly different proposal:
1. once migration is finished and etcd is up do:
```
ETCDCTL_API=2 etcdctl ls /registry/events
```
[This will list us all the event keys form before migration (we can assume that after migration noone will write anything to v2 API storage]
2. create a lease using etcdctl
3. Attach all keys to that least (for this one we may actually need a Go program, since with etcdctl it may be too slow.

@lavalamp @hongchaodeng @xiang90 - thoughts?

**Comment by hongchaodeng** [comment] 2016-08-18 16:43
It's possible to make transformer attach lease with additional complexity. Instead, I think there is only loose requirements on events and we can handle that in a simpler way.

The solution @wojtek-t described above is excellent too. Once you have written and run the program, let us know the results and problems if any.

**Comment by wojtek-t** [comment] 2016-08-19 09:26
>
It's possible to make transformer attach lease with additional complexity. Instead, I think there is only loose requirements on events and we can handle that in a simpler way.

If this is possible to make a transformer doing it, we definitely should do it.
Even the procedure that I described above is non-trivial, and would make the upgrade process much more complicated (and thus waaaay less probably we will launch it soon).

@hongchaodeng - would be be able to provide such a transformer (I don't know how to do it and don't have time).

**Comment by hongchaodeng** [comment] 2016-08-19 23:10
@wojtek-t 

I do some experiments and can make it work by attaching lease directly in migration process. This is not very generic though and hard to make it generic. In order to move forward fast, I create a repo for such migrate tool: https://github.com/hongchaodeng/kube-etcd-migrate

**Comment by wojtek-t** [comment] 2016-08-23 07:32
@hongchaodeng - thanks!

Anyway - I had a discussion about migration with @lavalamp yesterday and we both agreed that we would like to use as few dedicated code as possible.

Thus we will use standard etcdctl migrate (with default transformer) and we are considering two approaches to do after that:
- start etcd on a different port for a moment (so that apiserver cannot connect to it) and attach events to a lease using etcdctl
- wait XX minutes and delete all events that were present before migration (ideally using etcdctl)

The former would be possible only if it would work pretty fast (say O(seconds)). I will try to do some experiments to see how long it takes on large clusters.

**Comment by wojtek-t** [comment] 2016-08-23 09:26
The first one is not going to work - it takes too long for large clusters.
I did some experiment with 2000-node kubemark.:
- etcdctl migrate took ~7s (for events), which is pretty good in my opinion
- however, to attach a lease to all events (using etcdctl) it took ~10 minutes to just process 10% of them, which is completely unacceptable

I also took a look into just removing those keys using etcdctl, and it would take ~30 minutes in my case, and it is also super long.

Which makes me think, that we will need a dedicated go code to do it in a reasonable time (but I still think this should be separate from the migration step).

So I think we may endup with original @hongchaodeng suggestion and reuse his program from here:
https://github.com/hongchaodeng/etcdupgrade/blob/master/attachlease/main.go

I will try to take a look deeper later today.

**Comment by hongchaodeng** [comment] 2016-08-23 18:02
Let me converge our conversation here.
- first of all, we don't need to list the ttl keys into a file. I have updated ["attachlease"](https://github.com/hongchaodeng/etcdupgrade/tree/master/attachlease) program to take in "ttl dir" instead of "ttl keys file".
- I have updated "migrate-if-needed.sh" from #31242
```
76c76,80
<       # Create a lease and attach all event keys to it.
---
>       # List all keys that require attaching a lease.
>       # Since we still didn't remove v2 data, we can simply use it.
>       ${ETCDCTL} --endpoints=127.0.0.1:${ETCD_PORT} ls --recursive \
>         "${TTL_KEYS_DIRECTORY:-/registry/events}" > ttl_keys.txt
>       # Create a lease and attach all keys to it.
78c82
<         --ttldir "${TTL_KEYS_DIRECTORY:-/registry/events}" \
---
>         --file ttl_keys.txt \
```

- Finally, I ran the program and see the time below:
```
$ time TARGET_STORAGE=etcd3 DATA_DIRECTORY=./bk/data-events ./migrate-if-needed.sh
Performing etcd2 -> etcd3 migration
using default transformer
finished transforming keys
Attaching leases to TTL entries
granted lease with TTL: 60 seconds
successfully attach 10201 keys to lease
TARGET_STORAGE=etcd3 DATA_DIRECTORY=./bk/data-events ./migrate-if-needed.sh  7.84s user 3.84s system 61% cpu 19.051 total

$ TARGET_STORAGE=etcd3 DATA_DIRECTORY=./bk/data ./migrate-if-needed.sh
Performing etcd2 -> etcd3 migration
using default transformer
finished transforming keys
Attaching leases to TTL entries
granted lease with TTL: 60 seconds
successfully attach 0 keys to lease
TARGET_STORAGE=etcd3 DATA_DIRECTORY=./bk/data ./migrate-if-needed.sh  22.99s user 1.72s system 104% cpu 23.688 total
```
This is "Standard persistent disk". It will be considerably faster switching to SSD.
For attaching the lease, we can also parallelize it.

**Comment by wojtek-t** [comment] 2016-08-24 10:26
OK - I think that the PR that is adding support for TTL migration: #31242 is ready for final review.

**Comment by goltermann** [comment] 2016-09-06 20:29
Leaving in 1.4 - this will probably rollout as a 1.4.x release at some point to simplify the changeover.

**Comment by pwittrock** [comment] 2016-09-08 01:01
@wojtek-t @lavalamp I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here, move it back and provide daily updates to this issue.

**Comment by lavalamp** [comment] 2016-09-08 23:04
@pwittrock we will want a patch release at some point (two, actually, given
#32253) but moving it out for the moment is fine.

**Comment by pwittrock** [comment] 2016-09-08 23:15
@lavalamp Thanks Daniel.

**Comment by wojtek-t** [comment] 2016-09-28 07:45
I have just pushed the new image:
```
gcr.io/google_containers/etcd-amd64:3.0.10-experimental.1
```

This contains 3.0.10 etcd release binaries, though I added "experimental.1" on purpose, since will probably want to expand the logic of the image on our side to handle migration. At the same time, we woudl like to enable some testing already.

@timothysc ^^

**Comment by wojtek-t** [comment] 2016-09-28 12:50
https://github.com/kubernetes/kubernetes/issues/33653 is definitely a blocker for launching etcd3 in my opinion

**Comment by timothysc** [comment] 2016-09-30 21:32
@wojtek-t when do we want to default the api-server to 3 vs 2?  I can put that PR in..

**Comment by wojtek-t** [comment] 2016-10-01 07:23
I'm not sure about changing the default, though we should probably change at least one of our blocking test suits to it. I will talk about it with @lavalamp on Monday.

**Comment by timothysc** [comment] 2016-10-03 17:01
Ideally I think we should have this planned out asap to avoid a 1.4 repeat.

**Comment by lavalamp** [comment] 2016-10-03 21:32
Status on etcd3 from my perspective:

1. We should get *something* testing etcd 3 on both a presubmit and postsubmit to prevent regressions. @ixdy or @spxtr, can one of you work with (or find someone to work with) @timothysc to make sure that happens ~soon?
2. We shouldn't *stop* testing etcd 2 until we have a migration path that we're confident in.
3. The current plan is to build the migration path into the etcd container--this will let anyone using the current setup scripts migrate safely. @wojtek-t left a more detailed comment in another place.
4. @mml will have some cycles for this, this quarter.
5. It's critical for us (GKE) to make this happen before 1.5
6. There hasn't been movement from us on this due to some vacations, but everyone necessary should be back on wednesday.

**Comment by wojtek-t** [comment] 2016-10-04 06:31
I will start working on the migration (described here: https://github.com/kubernetes/kubernetes/issues/22448#issuecomment-251057363 ) today/tomorrow

**Comment by wojtek-t** [comment] 2016-10-04 09:29
The new mechanism for building an image is already out for review.

The necessary changes to migrate-if-needed.sh script will come probably tomorrow.

**Comment by wojtek-t** [comment] 2016-10-04 12:10
>
We should get something testing etcd 3 on both a presubmit and postsubmit to prevent regressions. @ixdy or @spxtr, can one of you work with (or find someone to work with) @timothysc to make sure that happens ~soon?

As for post-submit, I think we should just promote the etcd3 suite that we already have to be blocking:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L308

So the missing thing here is to actually make some presubmit job testing etcd3.

**Comment by wojtek-t** [comment] 2016-10-04 12:20
In kubernetes/contrib#1831 I'm adding this job to submit-queue list of jobs. But we should probably also add it to blockers - do you agree @lavalamp ?

**Comment by wojtek-t** [comment] 2016-10-06 09:49
OK - so we already change the integration tests to actually run on 3.0.10 binary.

**Comment by timothysc** [comment] 2017-01-05 20:10
going to close this one now, we can open up issues as needed now.

**Closed by timothysc** 2017-01-05 20:10 UTC
Labels: area/etcd, priority/important-soon, sig/api-machinery, team/control-plane (deprecated - do not use)

**Comment by lavalamp** [comment] 2017-01-09 19:46
Great work everyone! Much appreciated!

**Comment by smarterclayton** [comment] 2017-01-09 19:48
Although my initial estimate of summer 2016 were way off :)

**Comment by timothysc** [comment] 2017-01-09 21:11
> Although my initial estimate of summer 2016 were way off :)

Yeah, my early 2016 was HIGHLY optimistic.  
"No one expects the Spanish inquisition" ~ M. Python
