### ISSUE TITLE
containers failing to resolve public dns

### ISSUE THREAD

**Issue by idanysela** [kubernetes/kubernetes#74533] opened 2019-02-25 19:19 UTC
running a kubernetes cluster on low priority vms using aks-engine, when attempting to scale up our container deployment (single container image) we are getting a lot of failed containers  failing to resolve public dns addresses 

kubectl get pods
NAME                                              READY     STATUS             RESTARTS   AGE
clients-user-experience-journey-7d74567f6-22ghg   1/1       Running            0          29m
clients-user-experience-journey-7d74567f6-24lvj   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-2568g   0/1       Completed          10         1h
clients-user-experience-journey-7d74567f6-26dj7   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-26x2c   1/1       Running            0          1h
clients-user-experience-journey-7d74567f6-276sd   1/1       Running            10         1h
clients-user-experience-journey-7d74567f6-27hjl   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-27mpr   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-29ffk   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-2cbst   1/1       Running            11         1h
clients-user-experience-journey-7d74567f6-2cl2s   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-2cnzm   1/1       Running            10         1h
clients-user-experience-journey-7d74567f6-2f4jv   0/1       CrashLoopBackOff   10         1h
clients-user-experience-journey-7d74567f6-2f78f   1/1       Running            11         1h
clients-user-experience-journey-7d74567f6-2fdds   1/1       Running            10         1h
clients-user-experience-journey-7d74567f6-2ff46   1/1       Running            10         1h

example container log:
/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details
see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
{"timestamp": "2019-02-24 17:54:34", "log_level": "INFO", "process_name": "clients_user_experience_journey", "message": "will read messages", "process_id": "6"}
{'process_name': 'clients_user_experience_journey', 'message': u'will read messages', 'process_id': '6'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/backend/clients/user_experience/journey.py", line 91, in <module>
    worker.perform_job()
  File "ng/backend_worker.py", line 285, in perform_job
    force_create_queue=self.force_queue_creation
  File "ng/aws/sqs.py", line 143, in read_message
   queue = self._get_queue(queue_name)
  File "ng/aws/sqs.py", line 76, in _get_queue
    return self.connection.get_queue(self.env_prefix + queue_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/connection.py", line 521, in get_queue
    return self.get_object('GetQueueUrl', params, Queue)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1192, in get_object
    response = self.make_request(action, params, path, verb)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.gaierror: [Errno -3] Temporary failure in name resolution
done running clients/user_experience/journey at Sun Feb 24 17:58:27 UTC 2019 with exitcode 1

**Comment by thockin** [comment] 2019-03-07 22:21
@saiyan86

**Comment by saiyan86** [comment] 2019-03-07 22:23
@idanysela Is this Windows or Linux?

**Comment by thockin** [comment] 2019-03-21 21:25
ping?  Should we close this?

**Comment by saiyan86** [comment] 2019-03-22 21:07
@thockin I think we can close this for now. I can't reproduce without enough troubleshooting information. If anything changes, we can reopen this.

**Closed** 2019-03-28 20:49 UTC
Labels: sig/network, triage/unresolved

**Comment by vaibhavnsingh** [comment] 2025-12-11 06:01
We are also intermittently getting this error. 

[Errno -2] Name or service not known
