### ISSUE TITLE
Apply command does not apply new configuration correctly in deployments

### ISSUE THREAD

**Issue by manypozo** [kubernetes/kubernetes#47238] opened 2017-06-09 11:15 UTC
@k8s-merge-robot

**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** kubectl, apply, configuration, deployment. Asked around in the slack channel as well.
I have visited other maybe close issues, but they are not exactly the same: 
* [#39798](https://github.com/kubernetes/kubernetes/issues/39798) 
* [#41641](https://github.com/kubernetes/kubernetes/issues/41641)

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**Kubernetes version**:
`kubectl version`
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-30T22:03:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}`

Also tried in:
`Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-23T22:28:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

**Minikube version**:
`minikube version`
`minikube version: v0.19.1`

**Environment for version 1.6.4**:
- **Cloud provider or hardware configuration**: Minikube
- **OS** (e.g. from /etc/os-release): MacOS Sierra 10.12.5
- **Kernel** (e.g. `uname -a`): Darwin mp.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
- **Install tools**: Minikube

**Environment for version 1.5.3**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu JuJu

**What happened**:
The deployment does not apply the new configuration by using the command `kubectl apply -f deployment.yaml`.

**What you expected to happen**:
The new replica-set created by the new apply configuration should deploy the pods, and gradually terminates the pods of the older replica-set.
Like this way; the new configuration is correctly applied.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a deployment.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
  labels:
    component: test
spec:
  replicas: 3

  selector:                               # POD selector
    matchLabels:
      component: test

  strategy:                               # how updating the deployment affect the Replicat Set and Pods
    type: RollingUpdate         #Recreate/RollingUpdate
    rollingUpdate:
      maxSurge: 1               # default, number of PODS created over desired number of replicas
      maxUnavailable: 0         # default (this can be in percentage as well)

  progressDeadlineSeconds: 600
  minReadySeconds: 0            # default, asap
  revisionHistoryLimit: 5        # how many revision to store 0/1/2/3/4/5...
  rollbackTo:
    revision: 0                 # 0=default, meaning the last revision available 

  template:
    metadata:
      labels:
        component: test

    spec:
      terminationGracePeriodSeconds: 15
      
      containers:
      - name: hello-node
        image: mjroxas/hello-node:v1
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8080
```

2. Deploy it using kubectl
`kubectl create -f deployment.yaml --save-config --record=true`
`deployment "hello-node" created`

`kubectl get deployment hello-node -o yaml | grep image:`
`      - image: mjroxas/hello-node:v1`

`kubectl describe deployment hello-node`
```yaml
Name:           hello-node
Namespace:      default
CreationTimestamp:  Fri, 09 Jun 2017 11:52:11 +0200
Labels:         component=test
Annotations:        deployment.kubernetes.io/revision=1
            kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"test"},"name":"hello-node","namespace":"defa...
            kubernetes.io/change-cause=kubectl create --filename=deployment.yaml --save-config=true --record=true
Selector:       component=test
Replicas:       3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:       RollingUpdate
MinReadySeconds:    0
RollingUpdateStrategy:  0 max unavailable, 1 max surge
Pod Template:
  Labels:   component=test
  Containers:
   hello-node:
    Image:      mjroxas/hello-node:v1
    Port:       8080/TCP
    Environment:    <none>
    Mounts:     <none>
  Volumes:      <none>
Conditions:
  Type      Status  Reason
  ----      ------  ------
  Available     True    MinimumReplicasAvailable
  Progressing   True    NewReplicaSetAvailable
OldReplicaSets: <none>
NewReplicaSet:  hello-node-1568347238 (3/3 replicas created)
Events:
  FirstSeen LastSeen    Count   From            SubObjectPath   Type        Reason                  Message
  --------- --------    -----   ----            -------------   --------    ------                  -------
  11s       11s     1   deployment-controller           Normal      ScalingReplicaSet           Scaled up replica set hello-node-1568347238 to 3
  11s       10s     3   deployment-controller           Warning     DeploymentRollbackRevisionNotFound  Unable to find last revision.
```

kubectl get rs
NAME                    DESIRED   CURRENT   READY     AGE
hello-node-1568347238   3         3         3         1m

kubectl get rs hello-node-1568347238 -o yaml | grep image:
      - image: mjroxas/hello-node:v1

3. Make a change on the deployment. To avoid writing the complete deployment.yaml file again I just show the changes (an update of the image):
`image: mjroxas/hello-node:v2`

4. Execute the apply
`kubectl apply -f deployment.yaml`
`deployment "hello-node" configured`

5. Verify the configuration and the new created replica-set
`kubectl describe deployment hello-node`
```yaml
Name:           hello-node
Namespace:      default
CreationTimestamp:  Fri, 09 Jun 2017 11:52:11 +0200
Labels:         component=test
Annotations:        deployment.kubernetes.io/revision=3
            kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"test"},"name":"hello-node","namespace":"defa...
            kubernetes.io/change-cause=kubectl create --filename=deployment.yaml --save-config=true --record=true
Selector:       component=test
Replicas:       3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:       RollingUpdate
MinReadySeconds:    0
RollingUpdateStrategy:  0 max unavailable, 1 max surge
Pod Template:
  Labels:   component=test
  Containers:
   hello-node:
    Image:      mjroxas/hello-node:v1
    Port:       8080/TCP
    Environment:    <none>
    Mounts:     <none>
  Volumes:      <none>
Conditions:
  Type      Status  Reason
  ----      ------  ------
  Available     True    MinimumReplicasAvailable
  Progressing   True    NewReplicaSetAvailable
OldReplicaSets: <none>
NewReplicaSet:  hello-node-1568347238 (3/3 replicas created)
Events:
  FirstSeen LastSeen    Count   From            SubObjectPath   Type        Reason                  Message
  --------- --------    -----   ----            -------------   --------    ------                  -------
  2m        2m      1   deployment-controller           Normal      ScalingReplicaSet           Scaled up replica set hello-node-1568347238 to 3
  2m        2m      3   deployment-controller           Warning     DeploymentRollbackRevisionNotFound  Unable to find last revision.
  1m        1m      1   deployment-controller           Normal      ScalingReplicaSet           Scaled up replica set hello-node-1666389095 to 1
  1m        1m      1   deployment-controller           Normal      DeploymentRollback          Rolled back deployment "hello-node" to revision 1
  1m        1m      1   deployment-controller           Normal      ScalingReplicaSet           Scaled down replica set hello-node-1666389095 to 0
```

**Events from describe suggest that the deployment automatically perform a rollback**

`kubectl get rs`
NAME                    DESIRED   CURRENT   READY     AGE
hello-node-1568347238   3         3         3         3m
hello-node-1666389095   0         0         0         6s

`kubectl get rs hello-node-1666389095 -o yaml | grep image:`
      - image: mjroxas/hello-node:v2

**Anything else we need to know**:
1. The example I have used in here just modifies the images of the deployment. (I know it is possible to do by using `kubectl set image`).  This situation happens with other changes like:
- adding a new volume and volumeMount to the deployment.yaml     (which is my final goal)

2. Other changes in the deployment.yaml seems to apply (always to an older replica-set):
- If I modify the number of replicas:  `kubectl apply -f deployment.yaml` changes the number of pods.

3. Surprisingly for me, if I do:
`kubectl edit deployment hello-node`
and manually edit all my changes (image and/or new volumes), it does accept and deploy my changes.

4. If instead of using apply I create a whole new deployment with the new configuration it works as well.

**Comment by mengqiy** [comment] 2017-06-10 00:47
After debug a bit, I found apply actually works. The issue is your deployment got rollback due to some reason.
You can find it in the log. And you can use `kubectl rollout history deployment hello-node` to view each revision, and you will find the revision with `image: mjroxas/hello-node:v2`.

**Comment by manypozo** [comment] 2017-06-10 11:21
Yes, this is what I said:
"Events from describe suggest that the deployment automatically perform a rollback"

But I do not understand why is that actually. It is a very simple example.

**Comment by mengqiy** [comment] 2017-06-10 19:47
@kubernetes/sig-apps-misc

**Comment by mengqiy** [comment] 2017-06-13 21:19
@janetkuo Can you help look into this deployment issue?

**Comment by janetkuo** [comment] 2017-06-13 21:37
@manypozo `rollbackTo = 0` shouldn't be specified in the yaml. That tells Deployment controller to roll back to the last revision.

**Comment by janetkuo** [comment] 2017-06-13 21:44
Closing. Please reopen if the issue persists after removing `rollbackTo` from yaml.

**Closed by janetkuo** 2017-06-13 21:44 UTC
Labels: sig/apps, sig/cli

**Comment by manypozo** [comment] 2017-06-14 09:37
@janetkuo removing the `rollbackTo: revision: 0` did work fine thank you.

However, I still do not get where is the difference. Regarding the documentation [Creating a deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment):
```
Revision
.spec.rollbackTo.revision is an optional field specifying the revision to rollback to. This defaults to 0, meaning rollback to the last revision in history.
```
Thought it was 0 by default in anyway (actually I commented this on my yaml as well).

**Comment by janetkuo** [comment] 2017-06-14 17:18
`This defaults to 0, meaning rollback to the last revision in history.` is not correct, the default value is nil (empty). It should be `If set to 0, roll back to the last revision`. I'll file a PR to fix the document. Thanks for the report!

**Comment by janetkuo** [comment] 2017-06-14 17:24
Actually, that part is not incorrect. 

```
.spec.rollbackTo is an optional field with the configuration the Deployment is rolling back to. Setting this field will trigger a rollback, and this field will be cleared every time a rollback is done.
```

`.spec.rollbackTo` defaults to nil.
`.spec.rollbackTo.revision` defaults to 0 (since it's an integer).

Setting `.spec.rollbackTo` to something other than nil will trigger a rollout, even if you specify a default value in `.spec.rollbackTo.revision`. 

I can see why this is confusing, I'll rephrase in the document to make it more clear.

**Comment by janetkuo** [comment] 2017-06-14 17:58
Filed https://github.com/kubernetes/kubernetes.github.io/pull/4085 to update doc
