### ISSUE TITLE
Deployment issue to Azure

### ISSUE THREAD

**Issue by ShadySQL** [kubernetes/kubernetes#20983] opened 2016-02-10 17:56 UTC
The deployment first fails but saying that a network named undefined exists but the deployer so to speak creates it. I delete the vnet from the management portal and now it complains about a storage account.
root@kubernetes:/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure# cat /root/.azure/azure.err
2016-02-10T17:51:16.609Z:
{ [Error: The storage account 'e045d415b12a01' was not found.]
  stack: [Getter/Setter],
  code: 'ResourceNotFound',
  statusCode: 404,
  requestId: 'cdb805b3c0177470a277e0f30775e1fa',
  __frame:
   { name: 'deleteAccount',
     line: 183,
     file: '/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js',
     prev:
      { name: 'storageAccount_deleteCommand__5',
        line: 465,
        file: '/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 7,
        col: 4 },
     calls: 0,
     active: false,
     offset: 12,
     col: 55 },
  rawStack: [Getter] }
Error: The storage account 'e045d415b12a01' was not found.
  <<< async stack >>>
  at deleteAccount (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js:195:56)
  at storageAccount_deleteCommand__5 (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/storage/storage.account._js:472:5)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/azureuser/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

**Comment by bgrant0607** [comment] 2016-02-11 18:42
Dupe of #21067

**Closed by bgrant0607** 2016-02-11 18:42 UTC
