### ISSUE TITLE
Error deleting conntrack entries for UDP peer: Invalid IP address

### ISSUE THREAD

**Issue by hulucc** [kubernetes/kubernetes#95486] opened 2020-10-12 10:40 UTC
![image](https://user-images.githubusercontent.com/4343900/95736735-2ee25500-0cb9-11eb-8574-22598ec49e90.png)
During the rolling update of udp deployment, casually, udp packets get losting continuesly by ~1mins, and kube-proxy showing failed to cleanup the conntrack table.

k8s: v1.16.6

**Comment by neolit123** [comment] 2020-10-12 14:29
> k8s: v1.16.6

hi, please try to reproduce the problem with 1.17+ (1.16 is no longer supported) or search it if this problem was already fixed.

/sig network

**Comment by aojea** [comment] 2020-10-13 18:44
From the top of my head, this sames related to https://github.com/kubernetes/kubernetes/pull/94107, 
@robscott do you think that is the same issue and will be resolved by your fix?

**Comment by robscott** [comment] 2020-10-13 18:51
Interesting, is this IP coming from `loadBalancerSourceRanges`?

**Comment by thockin** [comment] 2020-10-15 22:02
The error comes from pkg/util/conntrack/conntrack.go `ClearEntriesForNAT()` - it seems to be receiving a "" origin.

@hulucc can you include the Service YAML here?

**Comment by thockin** [comment] 2020-10-15 22:03
Also, which proxy mode are you using?  IPVS or iptables?

**Comment by aojea** [comment] 2020-10-29 22:30
kindly ping @hulucc , can you provide the information requested in 
https://github.com/kubernetes/kubernetes/issues/95486#issuecomment-709613975
and
https://github.com/kubernetes/kubernetes/issues/95486#issuecomment-709613590

**Closed** 2020-11-16 17:33 UTC
Labels: kind/bug, sig/network, triage/accepted

**Comment by hulucc** [comment] 2020-11-24 10:18
@thockin It's IPVS. and nothing special about service, just a udp loadbalaner.
