### ISSUE TITLE
statefulset，volume's name verification is invalid

### ISSUE THREAD

**Issue by yojay11717** [kubernetes/kubernetes#100766] opened 2021-04-02 01:57 UTC
#### What happened:

I mount a comfigmap with the name "jetty-start.ini", it can not work.

![image](https://user-images.githubusercontent.com/80832542/113371503-1d8d2200-9399-11eb-9461-c51cb08a9471.png)

![image](https://user-images.githubusercontent.com/80832542/113371284-9049cd80-9398-11eb-911e-3df949db7dab.png)

#### What you expected to happen:
Like deployment, it is not allowed to set such a name

#### Environment:
- Kubernetes version (use `kubectl version`):  1.18.3 && 1.20.0 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by NovaHe** [comment] 2021-04-02 03:14
comfigmap name muste be [Alphanumeric](https://whatis.techtarget.com/definition/alphanumeric-alphameric)
`jetty-start.ini` dot `.` is non alphanumeric，you can try to remove it

**Comment by liggitt** [comment] 2021-04-02 05:33
Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/97309

**Comment by liggitt** [comment] 2021-04-02 05:34
Thanks for the report. The missing validation is a known issue, but tricky to tighten compatibly

**Closed by liggitt** 2021-04-02 05:33 UTC
Labels: kind/bug, needs-sig, needs-triage
