### ISSUE TITLE
e2e test flake: kube-up failed

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#25673] opened 2016-05-16 15:34 UTC
```
...
Waiting for group to become stable, current operations: creating: 6
Waiting for group to become stable, current operations: creating: 6
Waiting for group to become stable, current operations: creating: 6
Waiting Terminated
++ chmod -R o+r /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/_artifacts
/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../cluster/../cluster/../cluster/gce/util.sh: line 1: 11165 Terminated              gcloud compute instance-groups managed wait-until-stable "${group_name}" --zone "${ZONE}" --project "${PROJECT}"
+ dump_cluster_logs_and_exit
+ local -r exit_status=143
+ [[ -x cluster/log-dump.sh ]]
+ ./cluster/log-dump.sh /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/_artifacts
Dumping master and node logs to /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/_artifacts
Master not detected. Is the cluster up?
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-9llb' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-f25n' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-t40h' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-3mf9' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-6yku' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-master-0-minion-9pj2' was not found
...
```

Couldn't find an exact match in the existing issue, so I opened this one. 

cc @ixdy @fejta

**Comment by nikhiljindal** [comment] 2016-05-16 16:16
Yes happened again: https://github.com/kubernetes/kubernetes/pull/23430#issuecomment-219391799

```
Waiting for group to become stable, current operations: creating: 3
Waiting for group to become stable, current operations: creating: 3
Waiting for group to b/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../cluster/../cluster/../cluster/gce/util.sh: line 1: 22347 Terminated              gcloud compute instance-groups managed wait-until-stable "${group_name}" --zone "${ZONE}" --project "${PROJECT}"
Terminated
++ chmod -R o+r /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/_artifacts
+ dump_cluster_logs_and_exit
+ local -r exit_status=143
+ [[ -x cluster/log-dump.sh ]]
+ ./cluster/log-dump.sh /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/_artifacts
Dumping master and node logs to /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/_artifacts
Warning: Permanently added '104.197.112.205' (ECDSA) to the list of known hosts.
Warning: Permanently added '104.197.14.10' (ECDSA) to the list of known hosts.
Warning: Permanently added '130.211.164.244' (ECDSA) to the list of known hosts.
Warning: Permanently added '104.197.231.208' (ECDSA) to the list of known hosts.
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-4-minion-9jql' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-4-minion-dq83' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-4-minion-asym' was not found
+ [[ true == \t\r\u\e ]]
+ go run ./hack/e2e.go -v --down
2016/05/16 03:03:11 e2e.go:194: Running: teardown
Project: kubernetes-jenkins-pull
Zone: us-central1-f
Shutting down test cluster in background.
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-4-minion-e2e-gce-builder-2-4-http-alt' was not found
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-4-minion-e2e-gce-builder-2-4-nodeports' was not found
Bringing down cluster using provider: gce

All components are up to date.

All components are up to date.

All components are up to date.
Project: kubernetes-jenkins-pull
Zone: us-central1-f
INSTANCE_GROUPS=e2e-gce-builder-2-4-minion-group
NODE_NAMES=e2e-gce-builder-2-4-minion-9gj6 e2e-gce-builder-2-4-minion-9jql e2e-gce-builder-2-4-minion-asym e2e-gce-builder-2-4-minion-dq83 e2e-gce-builder-2-4-minion-jxb7 e2e-gce-builder-2-4-minion-u4cb
Bringing down cluster
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/zones/us-central1-f/instanceGroupManagers/e2e-gce-builder-2-4-minion-group].
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/instanceTemplates/e2e-gce-builder-2-4-minion-template].
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-4-master].
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-4-master].
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-4-master-https].
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-4-minion-all].
Deleting routes e2e-gce-builder-2-4-1159d795-1b46-11e6-b49a-42010af00002
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/routes/e2e-gce-builder-2-4-1159d795-1b46-11e6-b49a-42010af00002].
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-2-4-master-ip].
property "clusters.kubernetes-jenkins-pull_e2e-gce-builder-2-4" unset.
property "users.kubernetes-jenkins-pull_e2e-gce-builder-2-4" unset.
property "users.kubernetes-jenkins-pull_e2e-gce-builder-2-4-basic-auth" unset.
property "contexts.kubernetes-jenkins-pull_e2e-gce-builder-2-4" unset.
Cleared config for kubernetes-jenkins-pull_e2e-gce-builder-2-4 from /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/.kube/config
Done
2016/05/16 03:06:38 e2e.go:196: Step 'teardown' finished in 3m26.593105674s
+ exit 143
+ chmod -R o+r /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/_artifacts
+ rc=124
+ [[ 124 -ne 0 ]]
+ [[ -x cluster/log-dump.sh ]]
+ [[ -d _artifacts ]]
+ echo 'Dumping logs for any remaining nodes'
Dumping logs for any remaining nodes
+ ./cluster/log-dump.sh _artifacts
Dumping master and node logs to _artifacts
Master not detected. Is the cluster up?
Nodes not detected. Is the cluster up?
+ [[ 124 -eq 124 ]]
+ echo 'Build timed out'
Build timed out
+ echo 'Exiting with code: 124'
Exiting with code: 124
+ exit 124
Build step 'Execute shell' marked build as failure
```

**Comment by caesarxuchao** [comment] 2016-05-16 17:34
I'm see this 3 times in a row

**Comment by caesarxuchao** [comment] 2016-05-16 17:34
@ixdy could this have the same cause as #24479?

**Comment by ixdy** [comment] 2016-05-16 17:40
Dupe of #25629. We're running out of IP addresses due to leaked VMs.

**Closed by ixdy** 2016-05-16 17:40 UTC
Labels: area/test, kind/flake, team/test-infra
