### ISSUE TITLE
REST selfLinks for CertificateSigningRequests missing slash

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes#42448] opened 2017-03-02 23:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** Bug report.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.754+102f267b6a8012", GitCommit:"102f267b6a8012752433737bc473730fc72c12f5", GitTreeState:"clean", BuildDate:"2017-03-02T21:58:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.754+102f267b6a8012", GitCommit:"102f267b6a8012752433737bc473730fc72c12f5", GitTreeState:"clean", BuildDate:"2017-03-02T21:55:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

(built from master very recently)

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): 
BUILD_ID=9000.84.2
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
- **Kernel** (e.g. `uname -a`): Linux gke-129068370477-20f7bf7264c390a3bb97 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**: GKE
- **Others**:

**What happened**:

Navigating the certificates.k8s.io API using curl, I noticed that CSR selfLinks are missing a slash:

    $ curl localhost:8080/apis/certificates.k8s.io/v1beta1/certificatesigningrequests
    {
      "kind": "CertificateSigningRequestList",
      "apiVersion": "certificates.k8s.io/v1beta1",
      "metadata": {
        "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests",
        "resourceVersion": "1881"
      },
      "items": [
        {
          "metadata": {
            "name": "csr-h0l06",
            "generateName": "csr-",
            "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequestscsr-h0l06",
            "uid": "fd2bd81a-ff9b-11e6-aee8-42010a800002",
            "resourceVersion": "667",
            "creationTimestamp": "2017-03-02T23:00:11Z"
          },
    <snip>

If I try to access the `selfLink` given (which is conspicuously missing a slash delimiter), I get a 404:

    $ curl localhost:8080/apis/certificates.k8s.io/v1beta1/certificatesigningrequestscsr-h0l06
    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "the server could not find the requested resource",
      "reason": "NotFound",
      "details": {},
      "code": 404
    }

If I add in the missing slash manually, I get the correct results (although it still reports the wrong `selfLink`):

    $ curl localhost:8080/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/csr-h0l06
    {
      "kind": "CertificateSigningRequest",
      "apiVersion": "certificates.k8s.io/v1beta1",
      "metadata": {
        "name": "csr-h0l06",
        "generateName": "csr-",
        "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequestscsr-h0l06",
        "uid": "fd2bd81a-ff9b-11e6-aee8-42010a800002",
        "resourceVersion": "667",
        "creationTimestamp": "2017-03-02T23:00:11Z"
      },
    <snip>

**What you expected to happen**:
The `selfLink`s reported should include the omitted slash, and successfully resolve without manual modification.

**Comment by liggitt** [comment] 2017-03-04 02:19
Dupe of https://github.com/kubernetes/kubernetes/issues/37266

**Closed by liggitt** 2017-03-04 02:19 UTC
