### ISSUE TITLE
Regression in performance of small clusters on GCE

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#14554] opened 2015-09-25 12:46 UTC
We managed to fix scalability on big clusters, but I'm still observing pretty bad behavior on small (default: 2-core master and 3 2-core nodes) clusters.
```
Sep 25 14:34:44.198: INFO: E2E startup time for 90 pods: 1m0.144616567s
```

```
Sep 25 14:35:10.796: INFO: 10% worst schedule latencies: [{density-latency-pod-d2b9d2ae-6381-11e5-ad30-7446a0bae05f-3 e2e-test-gmarek-minion-19so 0}]
Sep 25 14:35:10.796: INFO: perc50: 0, perc90: 0, perc99: 0
Sep 25 14:35:10.796: INFO: 10% worst run-after-schedule latencies: [{density-latency-pod-d2b9d2ae-6381-11e5-ad30-7446a0bae05f-3 e2e-test-gmarek-minion-19so 1s}]
Sep 25 14:35:10.796: INFO: perc50: 1s, perc90: 1s, perc99: 1s
Sep 25 14:35:10.796: INFO: 10% worst watch latencies: [{density-latency-pod-d2b9d2ae-6381-11e5-ad30-7446a0bae05f-3 e2e-test-gmarek-minion-19so 12.042980863s}]
Sep 25 14:35:10.796: INFO: perc50: 10.978594099s, perc90: 12.042980863s, perc99: 12.042980863s
Sep 25 14:35:10.796: INFO: 10% worst scheduled-to-end total latencies: [{density-latency-pod-d2b9d2ae-6381-11e5-ad30-7446a0bae05f-3 e2e-test-gmarek-minion-19so 13.042980863s}]
Sep 25 14:35:10.796: INFO: perc50: 11.978594099s, perc90: 13.042980863s, perc99: 13.042980863s
Sep 25 14:35:10.796: INFO: 10% worst e2e total latencies: [{density-latency-pod-d2b9d2ae-6381-11e5-ad30-7446a0bae05f-3 e2e-test-gmarek-minion-19so 13.042980863s}]
Sep 25 14:35:10.796: INFO: perc50: 11.978594099s, perc90: 13.042980863s, perc99: 13.042980863s
```

What's surprising is that for 100 node cluster I'm observing way lower e2e startup latency (around 3-4 seconds on 99th percentile). I've seen this on my clusters multiple times, I also checked different project with the same effect.

I was wandering if it's not disk IOPS throttling, but issue persisted after increasing disk size (and thus guaranteed IOPS). Another idea I had was contention on Pod Workers in Kubelet, so I instrumented the code, and I didn't found anything keeping lock for long, and there was a lot of time when lock was open.

I'm not sure if it's the case only for GCE, or other providers show the same behavior, can someone run density test on other provider/bare metal? @timothysc @spiffxp

Until we know if it's not K8s code that's causing this I don't think we should cut 1.1 release. @wojtek-t @quinton-hoole @brendandburns @lavalamp @thockin @fgrzadkowski 

I don't know if those are bad, or not, as we don't really have data for small clusters, but I'm including those for posterity.
```
Sep 25 14:35:53.903: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:399.828ms}
Sep 25 14:35:53.903: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:139.415ms}
Sep 25 14:35:53.903: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:83.7ms}
Sep 25 14:35:53.903: INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:63.72ms}
Sep 25 14:35:53.903: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.9 Latency:52.155ms}
```

**Comment by timothysc** [comment] 2015-09-25 13:51
@gmarek I'll post results later today.

**Comment by wojtek-t** [comment] 2015-09-25 14:00
BTW - we observed a single big result also in 100-node cluster:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/2535/consoleFull

01:45:26 Sep 25 01:45:26.466: INFO: perc50: 1.470002711s, perc90: 2.098192042s, perc99: 9.647201782s

**Comment by gmarek** [comment] 2015-09-25 14:37
I run tests on head from the beginning of September, and observed the same behavior. Checking 1.0 branch now.

**Comment by gmarek** [comment] 2015-09-25 14:45
Branch 1.0.X seems to be healthy:
```
INFO: 10% worst schedule latencies: [{density-latency-pod-e4046b3b-6393-11e5-a75c-7446a0bae05f-2 e2e-test-gmarek-minion-ytyj 0}]
INFO: perc50: 0, perc90: 0, perc99: 0
INFO: 10% worst run-after-schedule latencies: [{density-latency-pod-e4046b3b-6393-11e5-a75c-7446a0bae05f-2 e2e-test-gmarek-minion-ytyj 3s}]
INFO: perc50: 3s, perc90: 3s, perc99: 3s
INFO: 10% worst watch latencies: [{density-latency-pod-e4046b3b-6393-11e5-a75c-7446a0bae05f-2 e2e-test-gmarek-minion-ytyj 532.824338ms}]
INFO: perc50: 532.824338ms, perc90: 532.824338ms, perc99: 532.824338ms
INFO: 10% worst scheduled-to-end total latencies: [{density-latency-pod-e4046b3b-6393-11e5-a75c-7446a0bae05f-2 e2e-test-gmarek-minion-ytyj 3.532824338s}]
INFO: perc50: 3.532824338s, perc90: 3.532824338s, perc99: 3.532824338s
INFO: 10% worst e2e total latencies: [{density-latency-pod-e4046b3b-6393-11e5-a75c-7446a0bae05f-2 e2e-test-gmarek-minion-ytyj 3.532824338s}]
INFO: perc50: 3.532824338s, perc90: 3.532824338s, perc99: 3.532824338s
```

**Comment by gmarek** [comment] 2015-09-25 15:26
I wonder if it's not the same but that causes stairstepping in Samsung's setup. If it is so, it might actually be good, as this problem is reproducible very easily, and it's straightforward to automate PR bisection.

cc @spiffxp @quinton-hoole

**Comment by quinton-hoole** [comment] 2015-09-25 16:08
@gmarek I was about to suggest the same. Will let Bob White at Samsung know.

**Comment by bgrant0607** [comment] 2015-09-25 16:19
Where is the code for this test?

**Comment by gmarek** [comment] 2015-09-25 16:26
test/e2e/density.go

**Comment by bgrant0607** [comment] 2015-09-25 17:22
Neither RunRC nor createRunningPod appear to specify any resources nor terminationGracePeriodSeconds. Is a LimitRange created for the namespace used by the tests, or are all the pods really relying on default behavior?

**Comment by gmarek** [comment] 2015-09-25 17:27
They run in namespace created by the framework without LimitRanger and depend on default behavior.

**Comment by lavalamp** [comment] 2015-09-25 17:38
Ah, that might explain why so many of them get assigned to the same node? Which I observed here: https://github.com/kubernetes/kubernetes/issues/14273#issuecomment-142436818

**Comment by gmarek** [comment] 2015-09-25 17:42
I looked at the distribution, and it was reasonable. The first 30/node should be spreaded roughly equally, as they come from one replication controller. With last hundred anything can happen.

**Comment by gmarek** [comment] 2015-09-28 14:01
With @wojtek-t, thanks the magic of bisection, we found the (probable) offending PR: #13003. We didn't dig deeply to understand why it's the case, but the test results are as follows (one from multiple runs on each revision):

With this PR:
```
Sep 28 15:46:57.245: INFO: 10% worst e2e total latencies: [{density-latency-pod-58d541e4-65e7-11e5-8848-7446a0bae05f-2 e2e-test-gmarek-minion-mrnf 12.805475997s}]
Sep 28 15:46:57.245: INFO: perc50: 12.805475997s, perc90: 12.805475997s, perc99: 12.805475997s
```

One PR earlier:
```
Sep 28 16:00:47.108: INFO: 10% worst e2e total latencies: [{density-latency-pod-4db163a0-65e9-11e5-8a71-7446a0bae05f-2 e2e-test-gmarek-minion-krva 1.978019496s}]
Sep 28 16:00:47.108: INFO: perc50: 1.978019496s, perc90: 1.978019496s, perc99: 1.978019496s
```

Some observations that may help Node team (@dchen1107, @yujuhong, @vishh) with debugging this:
- we're seeing quite large metrics:
  - kubelet_pod_worker_start_latency_microseconds{quantile="0.5"} 1.977008e+06,
  - kubelet_pod_worker_start_latency_microseconds{quantile="0.9"} 4.476458e+06,
- Events containing information about pod start are emitted and recorded straight away, but we need to wait quite some time for this information to be included in the PodStatus,
- it's easy to reproduce by running `density` test with 30 pods/node on any version including aforementioned change on a small (2-3 Nodes) cluster,
- some simple UI for reading Kubelet's prometheus metrics would be quite helpful:)

IMO fixing this should be a P-1, as I don't think we can launch v1.1 in this state.
@thockin @quinton-hoole @bgrant0607 @davidopp @smarterclayton @spiffxp @brendandburns @fgrzadkowski

**Comment by wojtek-t** [comment] 2015-09-28 14:02
@yujuhong - since that was your PR - can you please take a look?

**Comment by quinton-hoole** [comment] 2015-09-28 15:39
Wow!  Impressive sleuthing @wojtek-t , @gmarek.  Awesome. If I'm reading that code correctly (after a full 30 second glance :-) so I might well not be) it throttles pod termination rate to 1 per second, and will block on the channel when the backlog reaches 50.  It's not totally clear to me that that explains the scheduling latency increase, mind you.

**Comment by gmarek** [comment] 2015-09-28 15:42
Scheduling latency has not increased. What's more - startup latency (as in: containers are running on the machine and Docker knows about it) also did not. What's lagging behind is reporting the state of the Pod (i.e. that it's already running, not pending).

**Comment by yujuhong** [comment] 2015-09-28 16:41
> @yujuhong - since that was your PR - can you please take a look?

The PR didn't change the pod status reporting path, so there is no potential cause off the top of my head. Still digging and running tests though...

**Comment by yujuhong** [comment] 2015-09-28 18:06
Update: I ran the tests using HEAD, and here is what I found.

- Confirmed that startup time of 30 pods per node for a default 3-node cluster is **~1 minute**.
- Bumped QPS of the apiserver client for kubelet from 5 to 20 (Burst: 30) consistently showed startup time of **15s**. In other words, the status report time seems to be completely dominated by the QPS.

The PR in question (#13003) actually should've reduced the startup time significantly by eliminating a lot of redundant syncs. Before submitting the PR, I measured it locally and saw the startup time reduce at the default QPS (5). I will dig into more to see why kubelet is maxing out the QPS, and also see if this PR actually increases the #updates (which is not obvious to me).

```
STEP: 2015-09-28 10:55:43.352228731 -0700 PDT Creating replication controller density90-231a87e2-660a-11e5-9c71-c4346b658736
Sep 28 10:55:43.395: INFO: 2015-09-28 10:55:43.395685688 -0700 PDT Created replication controller with name: density90-231a87e2-660a-11e5-9c71-c4346b658736, namespace: e2e-tests-density-uyhg6, replica count: 90
Sep 28 10:55:48.395: INFO: 2015-09-28 10:55:48.395992773 -0700 PDT density90-231a87e2-660a-11e5-9c71-c4346b658736 Pods: 90 out of 90 created, 13 running, 52 pending, 25 waiting, 0 inactive, 0 terminating, 0 unknown 
Sep 28 10:55:48.396: INFO: Ignoring prom push, push gateway unavailable
Sep 28 10:55:53.396: INFO: 2015-09-28 10:55:53.3964525 -0700 PDT density90-231a87e2-660a-11e5-9c71-c4346b658736 Pods: 90 out of 90 created, 41 running, 49 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Sep 28 10:55:53.396: INFO: Ignoring prom push, push gateway unavailable
Sep 28 10:55:58.396: INFO: 2015-09-28 10:55:58.396891744 -0700 PDT density90-231a87e2-660a-11e5-9c71-c4346b658736 Pods: 90 out of 90 created, 90 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown 
Sep 28 10:55:58.397: INFO: Ignoring prom push, push gateway unavailable
Sep 28 10:55:58.397: INFO: E2E startup time for 90 pods: 15.044926715s
STEP: Waiting for all events to be recorded
Sep 28 10:56:08.397: INFO: Found 693 events
Sep 28 10:56:08.397: INFO: - reason: Scheduled, source: scheduler -> 90
Sep 28 10:56:08.398: INFO: - reason: Pulled, source: kubelet -> 180
Sep 28 10:56:08.398: INFO: - reason: Created, source: kubelet -> 180
Sep 28 10:56:08.398: INFO: - reason: Started, source: kubelet -> 180
Sep 28 10:56:08.398: INFO: - reason: SuccessfulCreate, source: replication-controller -> 90
```

**Comment by gmarek** [comment] 2015-09-28 20:00
@dchen1107 - I don't know what kind/flake label actually means, but it's ~100% reproducible (at least I'm yet to see a 'fast' run).

**Comment by gmarek** [comment] 2015-09-28 20:18
@yujuhong pointed out that I was't clear on what's regressing. The problem I'm referring to is the one that starts here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L245 and the results are printed here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L375.

**Comment by yujuhong** [comment] 2015-09-28 23:08
> @yujuhong pointed out that I was't clear on what's regressing. The problem I'm referring to is the one that starts here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L245 and the results are printed here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L375.

@gmarek clarified that the regression was the latency for starting up extra pods *after* 90 pods are already running.


I think I've identified the root cause.

 - Density test checks whether 90 pods have become running; if the condition is true, it proceeds to start the additional pods.
 - The test assumes that the pods status will not be updated after this point, which is not true. The pod ready condition may be flipped. See an example below.
```
I0928 22:16:16.522613   21175 status_manager.go:202] Status for pod "density90-878deb89-662e-11e5-8d36-c4346b658736-u0l7u_e2e-tests-density-88d0k" updated successfully: {Phase:Pending Conditions:[] Message: Reason: HostIP: PodIP: StartTime:2015-09-28 22:16:15 +0000 UTC ContainerStatuses:[]}
I0928 22:16:27.527780   21175 status_manager.go:200] Status for pod "density90-878deb89-662e-11e5-8d36-c4346b658736-u0l7u_e2e-tests-density-88d0k" updated successfully: {Phase:Running Conditions:[{Type:Ready Status:False}] Message: Reason: HostIP:10.240.0.5 PodIP:10.245.1.43 StartTime:2015-09-28 22:16:15 +0000 UTC ContainerStatuses:[{Name:density90-878deb89-662e-11e5-8d36-c4346b658736 State:{Waiting:<nil> Running:0xc2090bea80 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/pause:go ImageID:docker://6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 ContainerID:docker://036dab04292c9c9136612014be58f58bdd78f40db4226c7d33d3a75f455f6891}]}; Running: &{StartedAt:2015-09-28 22:16:17 +0000 UTC}
I0928 22:16:39.923654   21175 status_manager.go:200] Status for pod "density90-878deb89-662e-11e5-8d36-c4346b658736-u0l7u_e2e-tests-density-88d0k" updated successfully: {Phase:Running Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP:10.240.0.5 PodIP:10.245.1.43 StartTime:2015-09-28 22:16:15 +0000 UTC ContainerStatuses:[{Name:density90-878deb89-662e-11e5-8d36-c4346b658736 State:{Waiting:<nil> Running:0xc209d22d40 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/pause:go ImageID:docker://6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 ContainerID:docker://036dab04292c9c9136612014be58f58bdd78f40db4226c7d33d3a75f455f6891}]}; Running: &{StartedAt:2015-09-28 22:16:17 +0000 UTC}
```

PR #13003 reduced the batch startup time of 90 pods by at least 20s (~1m25s to ~1m20s) via reducing the redundant syncs. The side-effect of this is that there are still many queued-up "pod ready" statuses waiting to be sent out, due to the QPS limitation, when all pods are running. Therefore, it *appears* that the extra pod startup latency is long, but the status was actually queued up in the pod status manager.  

When I change the e2e test to wait for all pods are ready. The latencies are back to normal. (The batch startup time would increase due to the extra condition).
```
Sep 28 15:42:21.896: INFO: E2E startup time for 90 pods: 1m30.048268746s
...
Sep 28 15:42:37.418: INFO: Waiting for all Pods begin observed by the watch...
Sep 28 15:42:37.581: INFO: 10% worst schedule latencies: [{density-latency-pod-347258a8-6632-11e5-b768-c4346b658736-3 e2e-test-yjhong-minion-4g4m 0}]
Sep 28 15:42:37.581: INFO: perc50: 0, perc90: 0, perc99: 0
Sep 28 15:42:37.581: INFO: 10% worst run-after-schedule latencies: [{density-latency-pod-347258a8-6632-11e5-b768-c4346b658736-3 e2e-test-yjhong-minion-4g4m 1s}]
Sep 28 15:42:37.581: INFO: perc50: 1s, perc90: 1s, perc99: 1s
Sep 28 15:42:37.581: INFO: 10% worst watch latencies: [{density-latency-pod-347258a8-6632-11e5-b768-c4346b658736-3 e2e-test-yjhong-minion-4g4m 1.921176627s}]
Sep 28 15:42:37.581: INFO: perc50: 1.519722296s, perc90: 1.921176627s, perc99: 1.921176627s
Sep 28 15:42:37.581: INFO: 10% worst scheduled-to-end total latencies: [{density-latency-pod-347258a8-6632-11e5-b768-c4346b658736-3 e2e-test-yjhong-minion-4g4m 2.921176627s}]
Sep 28 15:42:37.581: INFO: perc50: 2.519722296s, perc90: 2.921176627s, perc99: 2.921176627s
Sep 28 15:42:37.581: INFO: 10% worst e2e total latencies: [{density-latency-pod-347258a8-6632-11e5-b768-c4346b658736-3 e2e-test-yjhong-minion-4g4m 2.921176627s}]
Sep 28 15:42:37.581: INFO: perc50: 2.519722296s, perc90: 2.921176627s, perc99: 2.921176627s
Sep 28 15:42:37.581: INFO: Approx throughput: 61.61900596365411 pods/min
```

I'll upload a PR to change the expectation of the tests so that it wait until the pods are ready, if there is no objection. @wojtek-t, @gmarek 
However, I think the QPS is still too low that it'd greatly affect the "perceived" end-to-end performance (or kubelet's performance) if there is any fluctuation. We can either use a separate apiserver client for the events (by setting the EventRecordQPS) or consider bumping up the overall client QPS for kubelet.

p.s. The ready condition would only be set when kubelet has the container probing results, i.e., the next sync period. Overall, probing is undergoing some rewriting/refactoring to support more features (#12866), and this may reduce the additional ready=true status update for pods without probes defined, but it would not affect the rest of the pods.

**Comment by yujuhong** [comment] 2015-09-28 23:09
Lowering the priority there is no actual performance regression -- what regressed is the "perceived" performance of the density test.

**Comment by quinton-hoole** [comment] 2015-09-28 23:48
Nice debugging YuJu!  What is the current client QPS rate limit for kubelet?  Where is it set?  On what basis is it set to the current value (whatever that may be)?

**Comment by yujuhong** [comment] 2015-09-29 01:01
> What is the current client QPS rate limit for kubelet? Where is it set? On what basis is it set to the current value (whatever that may be)?

The default QPS for any client is 5.0, which is what kubelet uses. I have no idea how this value was picked, but I assumed it was set based on the cluster/apiserver scalability. @wojtek-t may know more...

**Comment by pmorie** [comment] 2015-09-29 05:29
@gmarek The ambiguity around what the exact regression was that you commented on earlier is one reason that I think the latency test should have assertions around each class of latency (since we look at 4 different latency measurements).

**Comment by gmarek** [comment] 2015-09-29 05:36
This time the ambiguity was on a higher level - we probably should have two separate tests, one for measuring throughput for 'burst' workload, and one for single pods. IIRC that was an original design, but someone decided to put both those tests into the `density.go`, which was causing misunderstanding.

But to the point: originally we didn't have any assertions around latencies, as they were not stable enough. IIRC watch latencies can differ by few hundred percent between runs, so putting any assertions will either be close to meaningless (way to high), or cause flakyness. cc @wojtek-t who added assertions.

**Comment by pmorie** [comment] 2015-09-29 05:44
To be clear, the latency test (which is currently part of the density test, though to debug another similar regression related to #13052, I have extracted it so that it can also be run independently of the density test, see #13932 ) checks 5 different latency measurements:

1.  Scheduling (difference between creation and scheduled timestamps)
2.  Startup (difference between scheduled and running timestamps)
3.  'Watch' (difference between running timestamp and when a watch client _observes_ the pod reporting a `Running` phase)
4.  'Schedule to watch' (difference between scheduled timestamp and when a client _observes_ the pod reporting a `Running` phase)
5.  'Create to watch' (difference between scheduled timestamp and when a client _observes_ the pod reporting a `Running` phase) (this is called 'E2E lag' in the test)

I believe the metric in question that's regressing in this case is (5).  Can you confirm, @gmarek ?

I'll be honest, I am not quite sure what value measurements (3, 4, 5) give us.  As an example, I don't know that the difference between when a pod was scheduled and when a particular client _observed that it entered a running state_ has a lot of meaning for me as a performance metric.  Also, this implicitly assumes that the nodes in the test and the node where the client is running have synchronized clocks.  Any clock skew between the e2e process and the nodes in the cluster will surface to this test as differences in latencies.

As @yujuhong points out, measurements (3, 4, 5) are also highly dependent on what else may be happening on a node due to the relatively low QPS and strict (IMO) threshold set on measurement (5).  I am not arguing that we shouldn't have strict thresholds that we monitor, only that we make the right measurements to be strict about.

Perhaps I just don't get something about this test.  Anyone feel free to set me straight :-D

**Comment by pmorie** [comment] 2015-09-29 05:53
@gmarek I think your reply came while I was writing my last comment.  Race condition :)

**Comment by wojtek-t** [comment] 2015-09-29 06:14
>
But to the point: originally we didn't have any assertions around latencies, as they were not stable enough. IIRC watch latencies can differ by few hundred percent between runs, so putting any assertions will either be close to meaningless (way to high), or cause flakyness. cc @wojtek-t who added assertions.

It wasn't really my goal. Basically, I wanted to have assertions around what is important for us. As the end user, I don't care whether e.g. some internal watch implementation is efficient or not - what I care about is how fast I can start a pod.
So this is something that we really measure - the other numbers are just for debugging (to see where we spend most of the time and to eliminate bottlenecks).

**Comment by dchen1107** [comment] 2015-09-29 06:33
Default QPS 5.0 was introduced to all Kubernetes clients, including Kubelet when last time Kubelet sent too many node status updates, which flooded API server. IMP, that limit was randomly chose without much rationale behind. But what is the max QPS API server can support? Do we have that number?

**Comment by wojtek-t** [comment] 2015-09-29 06:52
I'm pretty sure we can do more, but I don't have exact number.

**Comment by gmarek** [comment] 2015-09-29 07:21
@pmorie - we discussed your point a lot at the time latency test was introduced. It was quite some time ago, so I may be missing something, but I believe most of the discussions is here: https://github.com/kubernetes/kubernetes/issues/3952#issuecomment-110642892.

You will probably notice, that I was making similar point to yours about using watch in our measurements, but on the difference between the time the pod was started, and the time a Watch observed the status update.

Clock skew was discussed on #9186, and we decided that we don't care about it, as on GCE clocks are synchronized, so we can trust the results we're getting.

**Comment by smarterclayton** [comment] 2015-09-29 07:48
It's worth mentioning that we have the ability to do backpressure from the
apiserver that is not being leveraged today (because of low client
limits).  I don't have a ton of trust in that, but we *should* be able to
trust the apiserver to tell clients to back off, and use that to manage
some of these concerns.

We need to improve the server rate limiter to leverage the APIRequestInfo
and more heuristics (like global pod lists) and more appropriately send
back off retry times that vary per type.  The clients should honor that 429
and retry time for most operations.

On Sep 29, 2015, at 8:34 AM, Dawn Chen <notifications@github.com> wrote:

Default QPS 5.0 was introduced to all Kubernetes clients, including Kubelet
when last time Kubelet sent too many node status updates, which flooded API
server. IMP, that limit was randomly chose without much rationale behind.
But what is the max QPS API server can support? Do we have that number?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14554#issuecomment-143958624>
.

**Comment by yujuhong** [comment] 2015-10-02 00:16
+1 for back pressure from the apiserver since client QPS limit is not adjusted based on the cluster size today. It'd also be nice if we can expose that to tell where the bottleneck is. Filed #14955 for this.

I am closing this issues since the test has been fixed, and @wojtek-t is working on getting events out of the main etcd instance https://github.com/kubernetes/kubernetes/issues/14702#issuecomment-144086763.

**Closed by yujuhong** 2015-10-02 00:16 UTC
Labels: area/performance, priority/P1, team/node
