### ISSUE TITLE
Support EIP Allocations with AWS NLB

### ISSUE THREAD

**Issue by pho-enix** [kubernetes/kubernetes#63959] opened 2018-05-17 06:49 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig aws

**Anything else we need to know?**:

AWS NLBs support static IP addresses by associating an EIP per AZ. An already allocated EIP can be supplied with the [subnetMapping](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SubnetMapping.html).

A user can then supply EIP allocation IDs in the service definition of kubernetes. By that the service will be available via those static IPs.

**Comment by gregkeys** [comment] 2018-06-21 02:02
eip's for white listing are really important in the enterprise, we need this feature now, as a result we have to manually create nlb's, would really like to see this added

**Comment by chrissnell** [comment] 2018-06-21 21:40
This is also important for hosting providers, who might have huge numbers of apex domain DNS `A` records pointed at EIPs.  Associating an already-allocated EIP with a new Kubernetes-generated NLB would be huge!

**Comment by 2rs2ts** [comment] 2018-08-15 21:25
This feature would save us weeks of work reimplementing the cloud controller just so we can preserve a special ELB that has static IP addresses... I really wish it was available

**Comment by brooksgarrett** [comment] 2018-09-29 00:34
I'd like to contribute time to working on this. Is anyone else actively working on adding support?

**Comment by pho-enix** [comment] 2018-10-01 06:07
@brooksgarrett That's awesome news. Thanks for working on this.

Do you need assistance in testing this in an AWS environment? I might help out with that ...

**Comment by brooksgarrett** [comment] 2018-10-01 13:10
Sure, the PR has been approved for testing so the binaries are available. I'm moving the code into our soak environment to get it some more exposure this week.

**Comment by pho-enix** [comment] 2018-10-01 13:53
I've been trying with:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-060029855176d9d52,eipalloc-0167919bfcb1170c2,eipalloc-094a0864e3e10becb"
```
But I only go a NLB without the EIPs deployed. Didn't find any errors in the logs.

Do I have to enable a feature flag for it or kind of?

**Comment by brooksgarrett** [comment] 2018-10-01 14:54
The reviewer found a typo where I may not be collecting the correct annotation. I'm waiting for the new build to complete and then rolling to our soak test. I'm passing through any AWS error and also error if the number of EIP and Subnets don't match. 

Let me get it online with the changes from code review and I'll dig in deeper.

**Comment by pho-enix** [comment] 2018-10-02 09:09
I checked with the fixes you provided yesterday. Works :)

Created a service which spawns over 3AZs and supplied 3 EIP allocations.

NLBs gets created correctly.

**Comment by brooksgarrett** [comment] 2018-10-02 12:53
Can you also comment on the PR? I'm sure having multiple successful tests would be helpful to the reviewer.

**Comment by LuluGO** [comment] 2019-01-24 22:54
Hey, thanks for doing this, I was just looking for a way to associate one eip to a nlb, one question though why do you need one eip for each AZ? now the nlb creates a 1 public IP that balance to 3 AZ using traefik in my case when I deploy the service, thanks

**Comment by pho-enix** [comment] 2019-01-25 14:32
Due to the fact that EIPs are represented by network hardware in AWS's datacenter you'd like to have redundant instances. If you run with only one EIP and the AZ of this EIP goes down, you won't be able to reach the (still up and running) traefik deployment in the other two AZs.

**Comment by raulcd** [comment] 2019-03-27 11:51
Hi, I've seen the PR (https://github.com/kubernetes/kubernetes/pull/69263) has been waiting for an update for three months. @brooksgarrett do you need a hand? do you want me to pick it up? I am really interested on this to be merged :smile:

**Comment by brooksgarrett** [comment] 2019-03-27 19:43
Can you help write the tests? I'm completely lost there to be honest.

**Comment by raulcd** [comment] 2019-03-28 12:53
Hi @brooksgarrett I've found out that test-coverage on the aws provider is low and there is no tests on the `ELBv2` so I can't find tests on NLB. I am going to open a new issue and work on improving coverage for that and hopefully I'll find out how to add tests for the new annotation. As you can see below current coverage for `aws.go` and `aws_loadbalancer.go` is low and can't find tests for NLB:
```
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go (29.2%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go (59.3%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_instancegroups.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_loadbalancer.go (12.9%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_metrics.go (50.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_routes.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_utils.go (41.7%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator.go (72.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/instances.go (89.5%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/log_handler.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/regions.go (100.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/retry_handler.go (46.3%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/sets_ippermissions.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/tags.go (58.6%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/volumes.go (12.1%)
```

**Comment by brooksgarrett** [comment] 2019-03-28 13:33
Thanks for the help. I thought I was just missing being able to locate them.

**Comment by newtondev** [comment] 2019-04-13 20:26
+1 need this ASAP

We are hosted on EKS so only official version supported. Any idea when this will be merged?

**Comment by aranair** [comment] 2019-04-17 18:16
.... As a workaround, I'm just manually creating a second NLB (with EIPs) and changing the listeners to forward the traffic to the automatically created target groups (from the 1st NLB).

**Comment by vorozhko** [comment] 2019-05-09 13:00
Waiting for this as well on EKS.

Thanks!

**Comment by aleicher** [comment] 2019-05-17 06:34
👍 would be great to have that in place. thanks!
I can confirm that the manual workaround by @aranair works fine, but it is hard to automate that flow.

**Comment by catalinvr** [comment] 2019-05-21 14:12
+1 Waiting for this as well on EKS.

**Comment by QwertyJack** [comment] 2019-05-26 09:56
+1 can wait

**Comment by QwertyJack** [comment] 2019-05-26 10:17
+1

**Comment by newtondev** [comment] 2019-05-26 15:48
I have created a node project that runs as a cronjob and monitors a SOURCE target group and clones the targets to a DESTINATION target group.

So when you create a LoadBalancer of type 'nlb' in kubernetes, all you need to do is manually create a new 'nlb' in AWS Console, assign your EIP to your NLB for a specific 'subnet'(availability zone), then create a target group with no targets; use the ARN from this target group as the destination and use the ARN of the kubernetes target group as the SOURCE.

More information here:
[https://github.com/newtondev/k8s-aws-nlb-target-cloner](https://github.com/newtondev/k8s-aws-nlb-target-cloner)

Public docker image:
https://hub.docker.com/r/newtondev/k8s-aws-nlb-target-cloner

**Closed** 2019-06-23 07:15 UTC
Labels: kind/feature, sig/aws

**Comment by dayyehm** [comment] 2019-08-14 09:50
I have hard time getting this working with NLB using ingress controller :
https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb

================================
kind: Service
apiVersion: v1
metadata:
name: ingress-nginx
namespace: ingress-nginx
labels:
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/part-of: ingress-nginx
annotations:
# Enable PROXY protocol
#service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
service.beta.kubernetes.io/aws-load-balancer-type: nlb
#service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-07e3afcd4b7b5d644,eipalloc-0d9cb0154be5ab55d,eipalloc-0e4e5ec3df81aa3ea"
service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-061f4a497621a7179,subnet-001c2e5df9cc93960"
# Ensure the ELB idle timeout is less than nginx keep-alive timeout. By default,
# NGINX keep-alive is set to 75s. If using WebSockets, the value will need to be
# increased to '3600' to avoid any potential issues.
#service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
type: LoadBalancer
selector:
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/part-of: ingress-nginx
ports:
- name: http
port: 80
targetPort: http
- name: https
port: 443
targetPort: https

**Comment by dayyehm** [comment] 2019-08-14 09:52
I have hard time getting this working with NLB using ingress controller :
https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb

Even subnets are not taking effect here , its not passing my configurations in the API that creates the NLB 

================================
kind: Service
apiVersion: v1
metadata:
name: ingress-nginx
namespace: ingress-nginx
labels:
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/part-of: ingress-nginx
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: nlb
service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-07e3afcd4b7b5d644,eipalloc-0d9cb0154be5ab55d,eipalloc-0e4e5ec3df81aa3ea"
service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-061f4a497621a7179,subnet-001c2e5df9cc93960"
spec:
type: LoadBalancer
selector:
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/part-of: ingress-nginx
ports:
- name: http
port: 80
targetPort: http
- name: https
port: 443
targetPort: https
=======================================================``

**Comment by amitoo7** [comment] 2019-12-11 08:10
> I have hard time getting this working with NLB using ingress controller :
> https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb
> 
> Even subnets are not taking effect here , its not passing my configurations in the API that creates the NLB
> 
> ================================
> kind: Service
> apiVersion: v1
> metadata:
> name: ingress-nginx
> namespace: ingress-nginx
> labels:
> app.kubernetes.io/name: ingress-nginx
> app.kubernetes.io/part-of: ingress-nginx
> annotations:
> service.beta.kubernetes.io/aws-load-balancer-type: nlb
> service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-07e3afcd4b7b5d644,eipalloc-0d9cb0154be5ab55d,eipalloc-0e4e5ec3df81aa3ea"
> service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-061f4a497621a7179,subnet-001c2e5df9cc93960"
> spec:
> type: LoadBalancer
> selector:
> app.kubernetes.io/name: ingress-nginx
> app.kubernetes.io/part-of: ingress-nginx
> ports:
> 
> * name: http
>   port: 80
>   targetPort: http
> * name: https
>   port: 443
>   targetPort: https
>   =======================================================``

I am also getting the same error can anyone help me with this ??

**Comment by dayyehm** [comment] 2019-12-11 08:20
@amitoo7  what version of k8s you are using ? this is not supported before 1.15 as far as I know so my issue was that I tried to implement on EKS

**Comment by amitoo7** [comment] 2019-12-11 10:43
Hi @dayyehm i am using the latest  version of k8 1.15 .5

**Comment by amitoo7** [comment] 2019-12-11 10:52
@dayyehm I am not using EKS with my solution but the problem is the same as you mentioned

**Comment by sskmail14** [comment] 2020-04-22 21:29
> I have created a node project that runs as a cronjob and monitors a SOURCE target group and clones the targets to a DESTINATION target group.
> 
> So when you create a LoadBalancer of type 'nlb' in kubernetes, all you need to do is manually create a new 'nlb' in AWS Console, assign your EIP to your NLB for a specific 'subnet'(availability zone), then create a target group with no targets; use the ARN from this target group as the destination and use the ARN of the kubernetes target group as the SOURCE.
> 
> More information here:
> https://github.com/newtondev/k8s-aws-nlb-target-cloner
> 
> Public docker image:
> https://hub.docker.com/r/newtondev/k8s-aws-nlb-target-cloner

@newtondev 
New to EKS.

Could you elaborate how the connectivity from NLB that we have created manually (as you mentioned ) to the ingress-nginx pod?

**Comment by sskmail14** [comment] 2020-04-23 06:49
> @amitoo7 what version of k8s you are using ? this is not supported before 1.15 as far as I know so my issue was that I tried to implement on EKS
@dayyehm
 
Has it worked for you in k8s 1.15 EKS?

**Comment by melissajenner22** [comment] 2020-10-09 19:59
How to get Allocation IDs?

**Comment by JoelTrain** [comment] 2022-02-26 00:08
my elastic eip ids cannot be found at service creation, so it just sits in pending forever.

if I resort to listing the subnets on their own annotation, (not using subnet discovery) same thing.

no matter what I do it seems to not find me elastic ip addresses.

Are you sure nlb type is supported to work with Elastic IPs?

From the AWS docs it seem they are pretty heavily trying to discourage use of the nlb type (Cloud Provider Load Balancer) in favor of pushing the new AWS Load balancer.

**Comment by pre** [comment] 2022-02-26 06:01
> my elastic eip ids cannot be found at service creation, so it just sits in pending forever.
> 


 Note: you will need to use the NEWER aws-lb-controller and install it on your own for elastic ip support. The kubernetes in-tree load balancer controller does not support aws elastic ips. 
 
See available `service` annotations: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/


If you have done that: 
what do your aws-lb-controller logs tell you?

I guess there’s an access problem with your iam role. Is your aws-lb-controller iam autorized to list and modify eip’s? Are the eip annotations exactly correct, can they be found by the controller? The controller’s log stream should have some kind of an error there. 

I have successfully assigned eips using service annotations to provision an aws nlb, but pay attention, you need to install the aws-lb-controller yourself. The kubernetes built-in aws library does not support eips.

**Comment by pippin-staked** [comment] 2022-08-23 21:35
Here is the annotation needed for assigning a static Elastic IP to your NLB.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#eip-allocations

**Comment by george-c29** [comment] 2024-10-27 11:39
I'm using nginx ingress controller with svc (type LoadBalancer). If I have an existing Loadbalancer svc which automatically created an NLB, will annotating said svc (in order to allocate EIPs) cause the loadbalancer to be recreated (thus requiring me to update the DNS in Route53)?
