### ISSUE TITLE
Test rollback in automated upgrade tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#43452] opened 2017-03-21 12:45 UTC
Currently, we re not testing rollback at all in any of our existing automated-upgrade testing. Since we are going into direction when there will be only automated upgrade tests (hopefully this will happen in 1.7), this would mean that noone will be testing rollback at that point.

We should extend our existing upgrade test to also test "rollback".

@thockin @davidopp @mml @skriss

**Comment by krousey** [comment] 2017-03-21 20:01
https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-1.5-downgrade-cluster
https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-gci-1.6-gci-1.5-downgrade-cluster

**Comment by mml** [comment] 2017-03-21 20:10
I pinged @krousey because we had been talking via IM about these failing rollback tests.  I believe he's planning to send me a PR to fix them, but if not a bug specifically about those is on the way.

At any rate, we actually are testing rollback.

**Comment by krousey** [comment] 2017-03-21 20:14
https://github.com/kubernetes/kubernetes/issues/43470 for the issue about broken downgrade testing.

**Comment by spiffxp** [comment] 2017-05-31 18:29
/sig testing

I don't have privileges to move this out of the milestone, but I question whether we're getting this in for 1.7.  Possible overlap with @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment] 2017-05-31 18:36
@spiffxp I can move it out of the milestone if you want

**Comment by mml** [comment] 2017-05-31 23:52
@krousey @wojtek-t I think we can close this, right?  We do have downgrade testing.

**Closed** 2017-06-01 06:33 UTC
Labels: area/test-infra, priority/important-soon, sig/cluster-lifecycle, sig/testing
