### ISSUE TITLE
kubectl create needs a create-or-replace option

### ISSUE THREAD

**Issue by al45tair** [kubernetes/kubernetes#90141] opened 2020-04-14 17:03 UTC
**What would you like to be added**:
Right now, we have `kubectl create`, which will create _but not replace_ a resource, and `kubectl replace`, which will replace _but not create_ a resource.

One or other (maybe both?) of them really should have an option to _create or replace_ as needed.

There are two obvious objections to this:

1. You could do `kubectl delete` then `kubectl create`. _Except you can't_ because *the delete can overtake the create*. Really.

2. You could use `kubectl apply`. _Sometimes_ this is true, but `kubectl apply` tries to patch the resource with the differences, which won't work if some of the fields can't be changed.

**Why is this needed**:
My use-case for this is creating-or-replacing a CRD during a test run. We need to create it if it isn't already present, or replace it if it is present. The other options don't work for this case for the reasons given above.

**Comment by nikhita** [comment] 2020-07-02 14:43
This is probably a duplicate of https://github.com/kubernetes/kubernetes/issues/14040

**Closed** 2020-11-29 16:26 UTC
Labels: kind/feature, lifecycle/rotten, sig/cli
