### ISSUE TITLE
kubectl get <resource> -n <wrong-namespace> returns zero resources instead of wrong namespace

### ISSUE THREAD

**Issue by sureshpalemoni** [kubernetes/kubernetes#91244] opened 2020-05-19 12:56 UTC
**What would you like to be added**:
when we send the command kubectl get <resource> -n <wrong-namespace>, it returns no resources or zero resources in the namespace. Some people might get this wrong, and may think there deployments have been erased or not at all deployed. 

**Why is this needed**:
It is ideal to return no such namespace in the cluster, to reflect the real error. This will not confuse people who might be looking into the wrong namespace.

**Comment by liggitt** [comment] 2020-05-19 13:44
Looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/75537

**Comment by zhouya0** [comment] 2020-05-20 03:19
Seems not a sig-cli problem, you can have such test:
```
[root@master ~]# kubectl get --raw /api/v1/namespaces/non-exist/pods
{"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/non-exist/pods","resourceVersion":"12568447"},"items":[]}
```
It returned with code 200.

**Comment by nikhita** [comment] 2020-06-22 10:54
As mentioned in https://github.com/kubernetes/kubernetes/issues/75537#issuecomment-475466491, this is to prevent unauthorized users sniffing the existence of namespaces.

Closing this issue since it is a duplicate of https://github.com/kubernetes/kubernetes/issues/75537. Please reopen if needed!

**Closed by nikhita** 2020-06-22 10:54 UTC
Labels: kind/feature, sig/cli

**Comment by akessner-github** [comment] 2024-05-30 10:39
I came across this issue today.
If you run `kubectl get namespace no-exist` you'll get an error and exit code 1
So namespace sniffing is still possible.
