### ISSUE TITLE
kubernetes-soak-continuous-e2e-gce went yellow

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14125] opened 2015-09-17 17:36 UTC
Last night kubernetes-soak-continuous-e2e-gce went yellow, first failing with node not ready:
Sep 16 21:06:18.783: All nodes should be ready after test, Not ready nodes: [{{ } {gce-soak-weekly-minion-xsmf  
More recent builds have failed with eg:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:162
Expected error:
    <*errors.errorString | 0xc20823b390>: {
        s: "Namespace e2e-tests-addon-update-test-wp1zy is active",
    }
    Namespace e2e-tests-addon-update-test-wp1zy is active
not to have occurred

I haven't had time to dig, perhaps @kubernetes/goog-testing cabal has cycles?

**Comment by quinton-hoole** [comment] 2015-09-17 17:51
Dupe of #13828

**Closed by quinton-hoole** 2015-09-17 17:51 UTC
Labels: priority/P1, team/testing
