### ISSUE TITLE
kubectl proxy to node is broken

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#9029] opened 2015-05-29 23:13 UTC
I tried to run go tool pprof through kubectl proxy, and found it is broken on HEAD

```
$ kubectl proxy
Starting to serve on localhost:8001
```
In web browser go to http://localhost:8001/api/v1beta3/proxy/nodes/kubernetes-minion-kfrp:10248/debug/pprof/heap, I got error message:
```
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://kubernetes-minion-kfrp:10250/debug/pprof/heap'
```

I tried to hit /logs on the same node, it failed with the same error. The regression is caused by recent security changes 

cc/ @roberthbailey @lavalamp @vmarmol

**Comment by lavalamp** [comment] 2015-05-29 23:27
This must have been broken recently, but I haven't been able to find the change that did it. It seems like something that would have been done for #3168...

**Comment by lavalamp** [comment] 2015-05-29 23:28
This should also break kubectl log and all the fancy port forwarding stuff. We really need e2e tests for this stuff. I think this is probably P0, it's a big regression.

**Comment by dchen1107** [comment] 2015-05-29 23:33
kubectl logs works fine actually:

```
$ cluster/kubectl.sh logs kube-dns-v1-rive3 etcd
2015/05/29 21:08:49 etcd: no data-dir provided, using default data-dir ./default.etcd
2015/05/29 21:08:49 etcd: listening for peers on http://localhost:2380
2015/05/29 21:08:49 etcd: listening for peers on http://localhost:7001
2015/05/29 21:08:49 etcd: listening for client requests on http://127.0.0.1:2379
2015/05/29 21:08:49 etcd: listening for client requests on http://127.0.0.1:4001
2015/05/29 21:08:49 etcdserver: datadir is valid for the 2.0.1 format
2015/05/29 21:08:49 etcdserver: name = default
2015/05/29 21:08:49 etcdserver: data dir = default.etcd
2015/05/29 21:08:49 etcdserver: member dir = default.etcd/member
2015/05/29 21:08:49 etcdserver: heartbeat = 100ms
2015/05/29 21:08:49 etcdserver: election = 1000ms
2015/05/29 21:08:49 etcdserver: snapshot count = 10000
2015/05/29 21:08:49 etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2015/05/29 21:08:49 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/05/29 21:08:49 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/05/29 21:08:49 etcdserver: start member 6a5871dbdd12c17c in cluster f68652439e3f8f2a
2015/05/29 21:08:49 raft: 6a5871dbdd12c17c became follower at term 0
2015/05/29 21:08:49 raft: newRaft 6a5871dbdd12c17c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/05/29 21:08:49 raft: 6a5871dbdd12c17c became follower at term 1
2015/05/29 21:08:49 etcdserver: added local member 6a5871dbdd12c17c [http://localhost:2380 http://localhost:7001] to cluster f68652439e3f8f2a
2015/05/29 21:08:51 raft: 6a5871dbdd12c17c is starting a new election at term 1
2015/05/29 21:08:51 raft: 6a5871dbdd12c17c became candidate at term 2
2015/05/29 21:08:51 raft: 6a5871dbdd12c17c received vote from 6a5871dbdd12c17c at term 2
2015/05/29 21:08:51 raft: 6a5871dbdd12c17c became leader at term 2
2015/05/29 21:08:51 raft.node: 6a5871dbdd12c17c elected leader 6a5871dbdd12c17c at term 2
2015/05/29 21:08:51 etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379 http://127.0.0.1:4001]} to cluster f68652439e3f8f2a
2015/05/29 21:50:30 etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
2015/05/29 21:50:30 etcdserver: compacted log at index 10001
2015/05/29 21:50:30 etcdserver: saved snapshot at index 10001
2015/05/29 22:32:12 etcdserver: start to snapshot (applied: 20002, lastsnap: 10001)
2015/05/29 22:32:12 etcdserver: compacted log at index 20002
2015/05/29 22:32:12 etcdserver: saved snapshot at index 20002
2015/05/29 23:13:50 etcdserver: start to snapshot (applied: 30003, lastsnap: 20002)
2015/05/29 23:13:50 etcdserver: compacted log at index 30003
2015/05/29 23:13:50 etcdserver: saved snapshot at index 30003
```

But I still think we should fix this.

**Comment by roberthbailey** [comment] 2015-05-30 06:10
The malformed http response is what you get when you try to make a plain http connection to an https endpoint (and presumably what you get when you try to make an https connection to an http server). In this case, I believe that the proxy is trying to make an https connection to the http server running on port 10248 on the kubelet. I didn't realize that you could specify a port number in the proxy URL -- I'm sure that the code makes a blanket https connection to nodes because it assumes it is hitting the secured endpoint.

**Comment by roberthbailey** [comment] 2015-05-30 06:11
If you can specify arbitrary ports on a node, how can we tell the proxy which ports should expect an SSL connection and which shouldn't? If we can't, then I think we should default to having them all be secure.

**Comment by bprashanth** [comment] 2015-06-03 01:25
1. Kubectl proxy only serves /api endpoints. I'm still able to create an ssh tunnel (by hand) from the master to localhost and do something like `curl http://localhost:8001/api/v1beta3/pods`. Fixing the proxy to serve /logs and /debug should be easy.

2. kubectl logs pod and /logs are different, the former hits the kubelet for the logs of a container in a pod while the latter exposes /var/log on the master. This is why kubectl log worked.

3. The default kubectl proxy timeout kicks us out off the /debug endpoint before go has a chance to collect enough samples. Honestly I've had a much better time profiling using https://github.com/GoogleCloudPlatform/kubernetes/issues/9065, but the timeout is also fixable.

**Comment by bprashanth** [comment] 2015-06-04 17:08
Note that even with the pr above there's still a timeout in the proxy server that disallows useful profiling as described in my previous comment. Other endpoints (like container logs and metrics) will work.

**Comment by davidopp** [comment] 2015-06-08 17:09
@lavalamp / @bprashanth: do you think the issue @bprashanth mentioned in the last update needs to be fixed for 1.0, or will #9262 be sufficient for 1.0?

(BTW https://github.com/GoogleCloudPlatform/kubernetes/pull/9262#issuecomment-109468760
says "We can revisit & test more after @brendandburns' ssh tunnel stuff goes in?" -- has that gone in yet?)

**Comment by bprashanth** [comment] 2015-06-08 17:14
I don't think the /debug endpoints timing out is a 1.0 blocker (we can still fix it).

**Comment by lavalamp** [comment] 2015-06-08 17:21
@davidopp I was hoping that would summon @brendandburns so he could tell us himself :)

@bprashanth what's the timeout currently at (and which proxy server are you talking about)? If it's > 30 seconds, I think it's fine. If it's less than that, we can fix after 1.0.

**Comment by bprashanth** [comment] 2015-06-08 17:24
I will need to dig up which server exactly (the kubectl proxy, the apiserver, the apiserver proxy and the kubelet server), but pprof -kubelet debug endpoint- will timeout before 30s

**Comment by davidopp** [comment] 2015-06-09 21:33
At the master team meeting we decided it's OK that /debug handler doesn't work, but we do need
an e2e test for master proxy.

**Comment by lavalamp** [comment] 2015-06-15 22:02
#9698 added an e2e proxy test.

**Comment by lavalamp** [comment] 2015-08-27 18:49
I believe this was fixed by the addition of --api-prefix to kubectl proxy, but never closed.

**Closed by lavalamp** 2015-08-27 18:49 UTC
Labels: area/introspection, kind/bug, priority/P1, team/CSI
