### ISSUE TITLE
apf: kubemark-500 scale test fails with mutating request estimator enabled

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#105804] opened 2021-10-21 02:51 UTC
### What happened?

kubemark-500 scale test fails with apf mutating request estimator enabled.

https://github.com/kubernetes/kubernetes/pull/103539
First red: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1448021022367289344

### What did you expect to happen?

Expected kubemark-500 scale test to pass 

### How can we reproduce it (as minimally and precisely as possible)?

- use the test PR: https://github.com/kubernetes/kubernetes/pull/105768
- run `/test pull-kubernetes-kubemark-e2e-gce-big`

**Comment by tkashem** [comment] 2021-10-21 02:52
# Work Estimate for Mutating Request

concurrency limit for `workload-high` is at `98`
![](https://i.imgur.com/uoBxAkR.png)

queue wait time is high around the window 12:35 - 12:45. This is a time window of interest since majority of the slow requests coincide on this window.
![](https://i.imgur.com/ipaWglR.png)

number of requests pending in queue is also higher around that time window
![](https://i.imgur.com/jaY5tQH.png)

why is queue wait time higher around this window? I think it's because
the rate of mutating request was consistently higher around that phase of 
the kubemark test. So more mutating requests were processed by apf during
that window.
![](https://i.imgur.com/2Ds8Y84.png)


number of currently executing requests were hovering below 3, that's quite low. on the other hand, concurrency in use was hovering around 50
![](https://i.imgur.com/XJq2msZ.png)

computed final seats for mutating requests are too high and apf failed to accommodate these requests due to lack of available seats. This led to high queue wait time. number of active watches is quite high for kubemark test.
![](https://i.imgur.com/h0Q0DUh.png)

after caping final seats to 10, the `pull-kubernetes-kubemark-e2e-gce-big` test has passed two times in a row.

**Comment by MikeSpreitzer** [comment] 2021-10-21 04:41
@tkashem : what is the PromQL for the graphs of "p&f - currently executing requests" and "p&f - concurrency in use" ?

**Comment by MikeSpreitzer** [comment] 2021-10-21 04:50
What if that cap on finalSeats is raised from 10 to 30, or 100?

**Comment by MikeSpreitzer** [comment] 2021-10-23 01:13
That graph of average execution duration --- which covers the first phase but not the second --- has a surprisingly squashed Y axis.  If you had cut off the spike at the end then we could read the data from around 14:00 with more precision.

As it is, it looks like the average first phase was roughly 1 to 4 ms depending on which FlowSchema was involved.  With a second phase of 5 ms, this means the first phase was roughly 1/6 to 4/9 of the total set-seconds taken per request, meaning the first-phase dead space was roughly 1/6 to 4/9 of the total and the second phase was, respectively, 5/6 to 5/9 of the total.

**Comment by MikeSpreitzer** [comment] 2021-10-23 01:16
@tkashem : if I understand your suggestion correctly, and drop the common term `S*G` from both sides of your equation, you are suggesting that in the real world we reshape from `finalSeats * A` to `initialSeats * A'`.  We could certainly make the real-world scheduler do that math, but I fear it would defeat the purpose here.  The problem is that the actual work of sending notifications is done in a big parallel burst, and our goal is server self-protection from that big parallel burst.

**Comment by wojtek-t** [comment] 2021-11-05 07:34
With the recent changes, we seem to be fine on 500-node tests.
But 5k-node tests are still blowing up.

I was playing a bit with it in https://github.com/kubernetes/kubernetes/pull/106085
And it seems it's failing even if I set additional latency to 1us (so nothing compared to request latency).
It basically seems that the width of the requests is pretty much preventing the test from making reasonable progress.

Now - I decreased the max width to 5 to see what will happen. 

But we need to understand this better. So the quick intro to it:
- workload-high is the PL we're having problem with
- it's where both scheduler and controll-manager calls are going
- it seems to have  40 shares out of 240 - so 1/6th 
- IIUC, we're setting 600 seats, so that gives 100 seats for this PL

Let's for a moment assume that wide calls are just the one from endpoint-slices.
Looking into last post-submit of kubemark-500:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1455928132908355584/artifacts/APIResponsivenessPrometheus_simple_load_2021-11-04T02:47:25Z.json
the p50 (let's assume that average is close to p50) for patch endpoint slices is 25ms.
This means that a single endpointslice update is blockig 10 seats (1/10th of PL for 25ms then)

We don't have very high churn there - 20pods/s, so even assuming that every pod transition to ready is generating endpointslice, that means 40qps on endpointslices (1 for adding endpoint as not-ready and 2nd for transitioning to ready). So that means that they will be blocking 10 seats for 25ms 40 times, so 10 seats blocked for 1s.
This doesn't seem to be concerning with 100 seats in that PL.

So there has to be something different - which I don't yet understand.

I think we need a list of calls with width>1 assigned to PL workload-high...

**Comment by MikeSpreitzer** [comment] 2021-11-08 18:11
I think #105873 would help

**Comment by MikeSpreitzer** [comment] 2021-11-14 05:02
I am struggling with the lack of information we are getting from the pull-kubernetes-kubemark-e2e-gce-scale job in both #106085 and #105768 .  The artifacts directory is missing all sorts of stuff, like apiserver logs and Prometheus metrics.

I am not familiar with the testing infrastructure here.  What is imposing the timeout that happens, and why are the logs not collected?

So I started digging into https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106085/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848 .  The info at the top says:
> Started | 2021-11-10 09:30:15 +0000 UTC
> Elapsed | 20h0m26s

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/106085/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848/prowjob.json includes this in the spec:

```
		"decoration_config": {
			"timeout": "20h20m0s",
			"grace_period": "15m0s",
```

I am a little confused, now I have three durations to think about, not just one.  How are they related?

The status of that prow job says:

```
		"startTime": "2021-11-10T09:28:25Z",
		"pendingTime": "2021-11-10T09:28:26Z",
		"completionTime": "2021-11-11T05:30:43Z",
```

That's a duration of about 20 hours plus 2 minutes.

That prow jobs seems to somehow come from https://github.com/kubernetes/test-infra/blob/c643adb8fd830bf65bc5f06ec0c140823df15799/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L358-L429 , which also specifies `decoration_config.time: 1220m` but is silent about `grace_period`.

That prow job defines four layers of launcher.  The container image is `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211111-d096cb0c5f-master`.  The container "command" is `runner.sh /workspace/scenarios/kubernetes_e2e.py` and the "args" include `--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh`.

**Comment by MikeSpreitzer** [comment] 2021-11-14 05:26
I am assuming that container image was built from https://github.com/kubernetes/test-infra/blob/master/images/kubekins-e2e/Dockerfile .  I am not familiar with bazel, so the details of what's going on in there are not immediately clear.  But I can pull that image and look around.  `/usr/bin/env python` gets me python 2.7.16!

I assume that the `runner.sh` here is https://github.com/kubernetes/test-infra/blob/master/images/bootstrap/runner.sh .  I looked at the build.log (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/106085/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848/build-log.txt) and its contents look consistent with that runner.sh.

As an aside, I note that https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/106085/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848/prowjob.json includes the following it its environment listing

```
							"name": "GOOGLE_APPLICATION_CREDENTIALS_DEPRECATED",
							"value": "Migrate to workload identity, contact sig-testing"
```

but build-log.txt shows that

```
  gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}" || true
```

was done anyway.

There's not much more interesting in runner.sh.  It gets around to `set -o xtrace` and invoking the following command line, which appears on line 10 of build-log.txt.

```
 /workspace/scenarios/kubernetes_e2e.py --build=quick --cluster= --extract=local --flush-mem-after-build=true --gcp-node-size=e2-standard-8 --gcp-nodes=84 --gcp-project=k8s-presubmit-scale --gcp-zone=us-east1-b --kubemark --kubemark-nodes=5000 --provider=gce --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-scale --env=CL2_ENABLE_HUGE_SERVICES=true --test=false --test_args=--ginkgo.focus=xxxx '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh' --test-cmd-args=cluster-loader2 --test-cmd-args=--nodes=5000 --test-cmd-args=--provider=kubemark --test-cmd-args=--report-dir=/logs/artifacts --test-cmd-args=--testconfig=testing/load/config.yaml --test-cmd-args=--testconfig=testing/access-tokens/config.yaml --test-cmd-name=ClusterLoaderV2 --timeout=1200m --use-logexporter --logexporter-gcs-path=gs://sig-scalability-logs/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848
```

I assume the next layer is https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py .  That uses the Python package `argparse` to build a parser that handles some of the arguments and passes the rest to the next layer.  That next layer is not even visible on the command line; it is an invocation of `kubetest` which is echoed into build-log.txt and then run with `subprocess.check_call`.  Here is what was echoed:

```
Run: ('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=quick', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-scale', '--up', '--down', '--provider=gce', '--cluster=e2e-dbda2b26eb-93f0a', '--gcp-network=e2e-dbda2b26eb-93f0a', '--extract=local', '--flush-mem-after-build=true', '--gcp-node-size=e2-standard-8', '--gcp-nodes=84', '--gcp-project=k8s-presubmit-scale', '--gcp-zone=us-east1-b', '--kubemark', '--kubemark-nodes=5000', '--test_args=--ginkgo.focus=xxxx', '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh', '--test-cmd-args=cluster-loader2', '--test-cmd-args=--nodes=5000', '--test-cmd-args=--provider=kubemark', '--test-cmd-args=--report-dir=/logs/artifacts', '--test-cmd-args=--testconfig=testing/load/config.yaml', '--test-cmd-args=--testconfig=testing/access-tokens/config.yaml', '--test-cmd-name=ClusterLoaderV2', '--timeout=1200m', '--logexporter-gcs-path=gs://sig-scalability-logs/pull-kubernetes-kubemark-e2e-gce-scale/1458365923697102848')
```

**Comment by MikeSpreitzer** [comment] 2021-11-14 05:41
I am assuming the next layer down is https://github.com/kubernetes/test-infra/tree/master/kubetest .  There is a panic near the end of build-log.txt with a stack trace that looks consistent-ish with the latest version, https://github.com/kubernetes/test-infra/blob/c643adb8fd830bf65bc5f06ec0c140823df15799/kubetest/e2e.go .  The statements in that version at lines 249 and 767 look consistent with build-log.txt, and the same is true for https://github.com/kubernetes/test-infra/blob/c643adb8fd830bf65bc5f06ec0c140823df15799/kubetest/process/process.go#L103 .  That leaves us with https://github.com/kubernetes/test-infra/blob/c643adb8fd830bf65bc5f06ec0c140823df15799/kubetest/e2e.go#L771 --- and I do not see how that can panic!

**Comment by MikeSpreitzer** [comment] 2021-11-14 22:41
As another aside, the REAMDE for kubetest says that it is deprecated in favor of https://github.com/kubernetes-sigs/kubetest2 .

**Comment by MikeSpreitzer** [comment] 2021-11-14 22:43
I also tried the pull-kubernetes-kubemark-e2e-gce-scale job on an easier PR (#106325), one that should not have failures, but it failed anyway.  See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106325/pull-kubernetes-kubemark-e2e-gce-scale/1459459749048225792 .

**Comment by MikeSpreitzer** [comment] 2021-11-14 22:49
pull-kubernetes-kubemark-e2e-gce-scale also ran recently on #105768 , and again timed out and failed to gather much stuff, erring out of `log-dump.sh` as well as `run-e2e.sh`.

**Comment by MikeSpreitzer** [comment] 2021-11-14 22:57
Interestingly, #106085 also had pull-kubernetes-kubemark-e2e-gce-scale complete recently, and this one did NOT timeout after 20 hours!  It got some other error after 12h51m .  The `log-dump.sh` got more stuff than for those other PRs, mostly a bunch of pprof files.  Still no apiserver logs.  And it still erred out somehow.

**Comment by MikeSpreitzer** [comment] 2021-11-15 04:22
@wojtek-t, regarding https://github.com/kubernetes/kubernetes/issues/105804#issuecomment-961682024 : you said you set the width cap to 5 seats, but then talked about a request occpying 10 seats; I am confused.  Github is still willing to show me https://github.com/wojtek-t/kubernetes/commit/43709a962e3980c68c638c4b9f5083c6c2f18e16 ; I see no change to the width cap there.

**Comment by MikeSpreitzer** [comment] 2021-11-15 04:52
I did some looking into the 500 node prometheus metrics from #106085, starting at https://github.com/kubernetes/kubernetes/pull/106085#issuecomment-968483422 .

**Comment by MikeSpreitzer** [comment] 2021-11-15 05:58
I also opened https://github.com/kubernetes/test-infra/issues/24349 about the continuing failure to collect information.

**Comment by wojtek-t** [comment] 2021-11-15 08:52
> @wojtek-t, regarding #105804 (comment) : you said you set the width cap to 5 seats, but then talked about a request occpying 10 seats; I am confused. Github is still willing to show me wojtek-t@43709a9 ; I see no change to the width cap there.

Yeah - should be 5 everywhere (or 10 everywhere). I was first playing with 10, then with 5 and it's a bit messed up in the description.
But the bottom line is that I can't explain it even with cap 10...

**Comment by wojtek-t** [comment] 2022-01-10 13:22
Closing - #106085 has been merged couple days ago and everything seems to work fine at 5k node scale now.

**Closed by wojtek-t** 2022-01-10 13:22 UTC
Labels: kind/bug, sig/api-machinery, triage/accepted
