### ISSUE TITLE
Node Controller deletes the node before it deletes the pods on that node

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#12545] opened 2015-08-11 19:32 UTC
This is bad b/c it leads to a race condition where a node may have disappeared, but it's pods won't, and the pods will be stuck in pending forever.

We should delete pods first, and _then_ delete nodes.

**Comment by bgrant0607** [comment] 2015-08-11 20:31
cc @smarterclayton @gmarek @nikhiljindal

**Comment by abrutus** [comment] 2015-08-11 20:42
This prevented my pod to go from Starting to Running, since it was scheduled on a node that was deleted. Which led the DNS service to not be able to come back

**Comment by nikhiljindal** [comment] 2015-08-11 20:42
Right.

There is also the case when user directly deletes the node, in which case, we will need a GC controller to clear the pods: https://github.com/GoogleCloudPlatform/kubernetes/issues/7660#issuecomment-128636044

**Comment by bgrant0607** [comment] 2015-08-11 20:46
@abrutus Fixing this won't solve that problem.

**Comment by davidopp** [comment] 2015-08-11 20:53
Oh, so the problem is the following race condition?

1) NodeController deletes node
2) Before scheduler sees the deletion, it assigns the Pod to a Node
3) NodeController doesn't know the Pod was assigned to a node, so when it deletes the Pods on the node it doesn't delete that Pod

As @roberthbailey pointed out in the PR, this PR just seems to trade one race for another, namely

1) NodeController deletes Pods on the Node
2) Scheduler schedules a Pod onto the node
3) NodeController deletes the node

The proper solution for all of this (and I'm sure this isn't the first or last race condition like this we'll have) is to use etcd transactions once they're available so that we can have cross-object dependencies. I thought there was an issue about it already but I can't find one, so I'll file one.

In the mean time, I think the best we can do is have a background controller that sweeps up the garbage (there's definitely an issue or PR for that, but I can't find it at the moment).

**Comment by gmarek** [comment] 2015-08-11 20:55
Currently there's a cache of 'known' Nodes, and NodeController periodically deletes Pods from Nodes it doesn't know about (#12277). It does not solve this problem fully, as if the NodeController dies the cache is cleared, and it doesn't know which Nodes do not exist. @davidopp suggested two alternatives https://github.com/GoogleCloudPlatform/kubernetes/issues/11631#issuecomment-128518659, while @smarterclayton is adding other mechanism for handling that in #9165

**Comment by brendandburns** [comment] 2015-08-11 21:10
No, I'm pretty sure that the problem that @abrutus saw was due to Node controller.  In the process of debugging that cluster we scaled down to zero and then back up, the cluster was pretty grumpy due to something like 100k failed pods.

So while there are other races out there, I'm pretty sure that this is the root cause of the one that he saw.

**Comment by brendandburns** [comment] 2015-08-11 21:12
fwiw, the problem is way simpler than the race that @davidopp mentioned, it goes like this:

1) node controller deletes node
2) node controller is killed for some reason (e.g. reboot)
3) pods that should have been deleted, aren't, because the node controller is out of the loop, since the node no longer exists.

Note that this also can happen as follows:

1) Node is deleted
2) Requests to delete pods error out

Nothing ever goes back in and makes sure the pods are deleted after the first try.

**Comment by gmarek** [comment] 2015-08-11 21:20
Yup, but #12546 doesn't solve this problem AFAICT.

**Comment by davidopp** [comment] 2015-08-11 21:34
@brendanburns Ah, I was confused because your description of the issue says "the pods will be stuck in pending forever" but actually this does not have anything to do with Pods in Pending state. You're just talking about Pods that were oprhaned when their node was deleted.

I don't have a problem with your PR (and I see it is already merged :) ) but since there are still race conditions all over the place, I think the better general solution is the GC controller (#7660). We might eventually be able to get rid of that once we have multi-object transactions in etcd, but I don't claim to be familiar with all of the use cases #7660 is intended for.

**Comment by smarterclayton** [comment] 2015-08-11 21:35
Quick question.  Why do we delete nodes from the node controller?

Why not mark them dead and gc them after a few hours?  Does deletion help
us provide a better experience?

On Aug 11, 2015, at 5:12 PM, Brendan Burns <notifications@github.com> wrote:

fwiw, the problem is way simpler than the race that @davidopp
<https://github.com/davidopp> mentioned, it goes like this:

1) node controller deletes node
2) node controller is killed for some reason (e.g. reboot)
3) pods that should have been deleted, aren't, because the node controller
is out of the loop, since the node no longer exists.

Note that this also can happen as follows:

1) Node is deleted
2) Requests to delete pods error out

Nothing ever goes back in and makes sure the pods are deleted after the
first try.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12545#issuecomment-130079206>
.

**Comment by davidopp** [comment] 2015-08-11 21:42
Synchronous is a simpler model but if we're going to do background GC of stuff it might be better to be consistent and clean up everything in the background. There can still be race conditions even with a GC controller, but at least if it keeps sweeping you would expect it will eventually get rid of all the garbage or at least keep it at a low level.

**Comment by smarterclayton** [comment] 2015-08-11 21:44
And a node that is already not ready and not being scheduled can be
evacuated without a problem.  Deletion is a nice signal to other
components, but we could signal using conditions or a status update.

On Aug 11, 2015, at 5:42 PM, David Oppenheimer <notifications@github.com>
wrote:

Synchronous is a simpler model but if we're going to do background GC of
stuff it might be better to be consistent and clean up everything in the
background. There can still be race conditions even with a GC controller,
but at least if it keeps sweeping you would expect it will eventually get
rid of all the garbage or at least keep it at a low level.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12545#issuecomment-130086268>
.

**Comment by brendandburns** [comment] 2015-08-11 23:03
Right now, if we don't at least delete the Pods, then a replication controller will never get a signal that it should recreate the pod.  We could move the pods into "Host Failed" state or something like that and make the replication controller respect that.

The problem with background GC in this case is that you can't differentiate between a Pod that a user explicitly asked to be placed on a machine (in which case we prob. shouldn't delete it) from a Pod that got orphaned just because the node got deleted and an error occurred.

I think it might also be worth adding a replication-controller only GC loop for these pods, since you can introspect the Replication Controller's template and verify that it didn't request the Host, and thus know that it is safe to delete those pods.

I started down that path originally, but found #12546 to be a cleaner, simpler solution for now.  Definitely room for future improvement.

**Comment by smarterclayton** [comment] 2015-08-11 23:15
Why wouldn't we delete a pod a user explicitly placed on the node?  If
scheduler input is different from user input we shouldn't be using
spec.nodeName, but we chose to use that because targeted pods aren't any
more special than any other (you can create an RC for a targeted pod as
well).

On Aug 11, 2015, at 7:04 PM, Brendan Burns <notifications@github.com> wrote:

Right now, if we don't at least delete the Pods, then a replication
controller will never get a signal that it should recreate the pod. We
could move the pods into "Host Failed" state or something like that and
make the replication controller respect that.

The problem with background GC in this case is that you can't differentiate
between a Pod that a user explicitly asked to be placed on a machine (in
which case we prob. shouldn't delete it) from a Pod that got orphaned just
because the node got deleted and an error occurred.

I think it might also be worth adding a replication-controller only GC loop
for these pods, since you can introspect the Replication Controller's
template and verify that it didn't request the Host, and thus know that it
is safe to delete those pods.

I started down that path originally, but found #12546
<https://github.com/GoogleCloudPlatform/kubernetes/pull/12546> to be a
cleaner, simpler solution for now. Definitely room for future improvement.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12545#issuecomment-130105520>
.

**Comment by bgrant0607** [comment] 2015-08-12 05:07
We absolutely should delete pods that users placed. They should just have a scheduler that selected nodes prior to pod creation. Once we add a mechanism to disable the default scheduler, they'll even be able to invoke /binding.

If there are situations where we want to avoid deleting pods, that's forgiveness #1574. The only case I think we could get away without an explicit notion of forgiveness for now is Daemon.

**Comment by davidopp** [comment] 2015-08-12 05:39
@brendandburns If we find a Pod whose spec.nodeName field references a node that does not exist, that is always an error and the Pod should be immediately deleted. (So I think I am agreeing with Brian.) Thus I don't think the following is actually a problem: "The problem with background GC in this case is that you can't differentiate between a Pod that a user explicitly asked to be placed on a machine (in which case we prob. shouldn't delete it) from a Pod that got orphaned just because the node got deleted and an error occurred."

**Comment by davidopp** [comment] 2015-08-12 05:44
(But as a separate issue, I think that if we ever get fine-grained ACLs, we don't want to let users set nodeName directly. They should use node label selectors to constrain where something gets scheduled, and we should publish the node name as a label on every node.)

**Comment by gmarek** [comment] 2015-08-12 09:46
There's a corner case when user have a RC with a template that has a NodeName set. If the Node goes down and we delete Pods that were running on it (in one way or another - it doesn't really matter), RC will recreate those pods which will stay pending forever (and probably take some percentage of schedulers time).

This case is rather silly pet-like behavior, so I don't know if we care about it.

**Comment by smarterclayton** [comment] 2015-08-12 14:15
Maybe the rescheduler (proposed as looking at pods that are in pending)
should apply back pressure somehow.  Or maybe the idler (proposed as part
of general resource usage and horizontal autoscaling) should look at any
replication controller that is pending for a long time and simply set them
back to 0.

On Wed, Aug 12, 2015 at 5:47 AM, Marek Grabowski <notifications@github.com>
wrote:

> There's a corner case when user have a RC with a template that has a
> NodeName set. If the Node goes down and we delete Pods that were running on
> it (in one way or another - it doesn't really matter), RC will recreate
> those pods which will stay pending forever (and probably take some
> percentage of schedulers time).
>
> This case is rather silly pet-like behavior, so I don't know if we care
> about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12545#issuecomment-130241017>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by gmarek** [comment] 2015-08-12 14:34
With every post I like the GC idea more. We'd have one place which is responsible for removing garbage from the cluster, as otherwise the logic (and definition of 'garbage') will be spread out throughout the system and (probably) very hard to comprehend.

**Comment by gmarek** [comment] 2015-08-12 17:02
I thought a bit more about it, and indeed Node:Pod relationship is special, as it is the only explicit one I know of, but sadly not the only one when deletions has to cascade down to other objects (another example: Namespaces). IIUC for namespaces we currently have the same problems we have for Pods/Nodes now, i.e. if NamespaceController would die before deleting everything that lives in the deleted Namespace, thing will hang there forever. I don't know what else has/will have this property: Daemons? Jobs? Nominal Services?

All in all we need some general GC design that can be applied to all those scenarios. I don't know if it should be a pattern that we inject into every controller, or a separate GarbageController, or something else. I think it's possible to write a general GC, that will take a configuration storing information about which deletes has to cascade and act on it.

@bgrant0607 @davidopp

**Comment by smarterclayton** [comment] 2015-08-12 22:58
On Aug 12, 2015, at 1:02 PM, Marek Grabowski <notifications@github.com>
wrote:

I thought a bit more about it, and indeed Node:Pod relationship is special,
as it is the only explicit one I know of, but sadly not the only one when
deletions has to cascade down to other objects (another example:
Namespaces). IIUC for namespaces we currently have the same problems we
have for Pods/Nodes now, i.e. if NamespaceController would die before
deleting everything that lives in the deleted Namespace, thing will hang
there forever. I don't know what else has/will have this property: Daemons?
Jobs? Nominal Services?


Namespaces won't hang, they will continually try to make progress like
other controllers (RC or endpoints) and periodically re sync everything.


All in all we need some general GC design that can be applied to all those
scenarios. I don't know if it should be a pattern that we inject into every
controller, or a separate GarbageController, or something else. I think
it's possible to write a general GC, that will take a configuration storing
information about which deletes has to cascade and act on it.

@bgrant0607 <https://github.com/bgrant0607> @davidopp
<https://github.com/davidopp>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/12545#issuecomment-130370605>
.

**Comment by bgrant0607** [comment] 2015-08-13 00:48
This is getting way off topic, and the discussion will be hard to find once this issue is closed.

Quick comments:

I disagree that we should disallow setting of nodeName. That's intentionally permitted.

Replication controller will need to get smarter about dealing with failures, in general.

I am strongly in favor of a GC component.

Explicit "parent dependencies" proposal: https://github.com/kubernetes/kubernetes/issues/1535#issuecomment-91413501

**Comment by davidopp** [comment] 2015-08-13 01:13
@bgrant0607 Can you describe a scenario where setting of nodeName by an end-user (as opposed to a scheduler) would be useful?

@gmarek The corner case you mentioned here
https://github.com/kubernetes/kubernetes/issues/12545#issuecomment-130241017
is essentially the same as the second one mentioned here
https://github.com/kubernetes/kubernetes/issues/12545#issuecomment-130069562

The way we solved these kinds of implicit inter-object dependencies in Omega was to use transactions. If you set a Pod's hostname = node X, then in the same transaction you also have to do a no-op write to the object representing node X. This ensures that you have the latest information about both the object you are modifying and the object(s) that your decision is implicitly dependent on. This can trivially be used to ensure that you don't assign a Pod to a machine that has been deleted. 

The thing I haven't figured out yet is whether the mechanism I described above, plus using transactions to ensure we delete objects and their children/dependencies atomically (e.g. node and its Pods), solves all the race conditions and means we wouldn't actually need a GC controller.

(I realize etcd transactions don't exist yet...)

**Comment by bgrant0607** [comment] 2015-08-13 02:09
Example for setting nodeName:

User puts data on the host filesystem and then wants to launch a pod to mount it in a volume

Since to the system it would be indistinguishable from the above: user writes something like their own Daemon controller or rack-level controller/scheduler

**Comment by davidopp** [comment] 2015-08-13 02:24
I think the common case is that cluster admins will not want the end-user to be able to override all of the admission controllers and the scheduler, which is what writing nodeName lets you do. Anyway, let me re-phrase my argument to: we need ACLs that allow an admin to deny users the right to write that field *if* that's how they want to configure the cluster. We don't need to hard-code making it impossible.

**Comment by bgrant0607** [comment] 2015-08-13 03:03
I have no problem with making it possible to control writability of nodeName, though I think it's doesn't buy much. Constraints will still be possible and generally override any scheduling heuristics, there's not much difference between pending and failed, we could run feasibility at pod creation as well as for /binding, and Kubelet is the final decider.

I don't see how setting nodeName bypasses the admission-control plugins.

**Comment by davidopp** [comment] 2015-08-13 05:30
> Constraints will still be possible and generally override any scheduling heuristics

I agree that for our current default scheduler and Kubelet checks, being able to set nodeName isn't any more powerful than other things you can already do. However, I was envisioning a world where users have custom schedulers that may enforce additional predicates. For example, maybe the scheduler takes a config file specifying groups of dedicated machines and associated users who are allowed to use them; the scheduler ensures that users who don't belong on a machine don't get scheduled there. This is not possible to enforce if users can set nodeName directly. (In theory you could implement dedicated machines using an admission controller that attaches some kind of "not <label>" selector to every pod that doesn't  belong on a dedicated machine (one selector per dedicated machine group) but I'm just trying to make a more general point that letting the user pick the machine directly may not be desirable in all cases.) And I would argue that this kind of thing Kubelet does not need to check; dedicated machine group ownership seems like exactly the kind of thing you wouldn't want to have to store in both the master and kubelet. 

I didn't understand your comment about running feasibility for /binding; (1) that seems to imply you'd want feasibility logic in the API server which seems to have a lot of drawbacks, and (2) if the user can still overwrite nodeName I'm not sure it buys you any security.

My comment about admission control was wrong; I forgot it runs before the object is even persisted.

**Comment by smarterclayton** [comment] 2015-08-13 15:17
Per field policy is hard, @erictune and @liggitt and @deads2k and I have
spent a lot of time thinking about it.  I think we want it, but it's not a
trivial path between here and there.  Until then, admission control or
careful API design is our option.  Today, nodeName can be rejected due to
node selectors, and in OpenShift we implemented a node selector defaulting
mechanism that is the mechanism for admins to control this.  The ac checks
the node selector, if it doesn't match a value stored with the namespace it
checks it against the default, and the default/namespace value is
intersected with the selector (so you can't escape the selector an admin
sets).  If it would conflict you get rejected.  It's worked out ok.

On Thu, Aug 13, 2015 at 1:31 AM, David Oppenheimer <notifications@github.com
> wrote:

> Constraints will still be possible and generally override any scheduling
> heuristics
>
> I agree that for our current default scheduler and Kubelet checks, being
> able to set nodeName isn't any more powerful than other things you can
> already do. However, I was envisioning a world where users have custom
> schedulers that may enforce additional predicates. For example, maybe the
> scheduler takes a config file specifying groups of dedicated machines and
> associated users who are allowed to use them; the scheduler ensures that
> users who don't belong on a machine don't get scheduled there. This is not
> possible to enforce if users can set nodeName directly. (In theory you
> could implement dedicated machines using an admission controller that
> attaches some kind of "not " selector to every pod that doesn't belong on a
> dedicated machine (one selector per dedicated machine group) but I'm just
> trying to make a more general point that letting the user pick the machine
> directly may not be desirable in all cases.) And I would argue that this
> kind of thing Kubelet does not need to check ; dedicated machine group
> ownership seems like exactly the kind of thing you wouldn't want to have to
> store in both the master and kubelet.
>
> I didn't understand your comment about running feasibility for /binding;
> (1) that seems to imply you'd want feasibility logic in the API server
> which seems to have a lot of drawbacks, and (2) if the user can still
> overwrite nodeName I'm not sure it buys you any security.
>
> My comment about admission control was wrong; I forgot it runs before the
> object is even persisted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12545#issuecomment-130540641>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment] 2015-08-13 15:21
nodeName can only be rejected by nodeSelectors if you let admission do a
lookup (labels != name). currently, if you specify a nodeName that doesn't
match the nodeSelector, the node will actually get the pod definition and
fail on the selector mismatch

**Comment by gmarek** [comment] 2015-08-13 15:53
By Node at one point you probably mean Kubelet, but other than that you're right.

**Comment by davidopp** [comment] 2015-08-16 19:46
Let me see if I understand the mechanism you're describing. You use admission controller to add a node selector to every Pod, which constrains the Pod to only run on the set of machines that the policy allows? (Possibly you optimize this by not adding a node selector if it already has one that constrains the Pod to a set of nodes that meets the policy.) So if the user sets nodeName, the Pod may go to the node but it will fail the predicate check. Is that right?

**Comment by liggitt** [comment] 2015-08-16 23:27
Correct. We actually always add the selector to avoid needing to do node lookups during admission (and in case node labels change later). Pods with existing incompatible node selectors fail admission.

**Comment by bgrant0607** [comment] 2015-08-25 02:31
The scheduler shouldn't be where we enforce who's allowed to use what machine. That needs to be pushed down to kubelet.

**Comment by bgrant0607** [comment] 2015-08-25 02:34
Or potentially admission control -- I'd be fine with that.

Defaulting the node selector is effectively how we implement "dedicated machines" in Borg.

**Comment by davidopp** [comment] 2015-08-25 05:39
I don't think the knowledge of who's allowed to use what machine should be in the Kubelet. It certainly has to be somewhere else as well (either in the admission controller or the scheduler), and this seems like the kind of thing our system design should not require to be in two places.

Given that, my point is that you can't allow end-users to set nodeName, because that would allow them to violate the policy about dedicated machines.

I think it's completely reasonable for us to say that the admin should be able to configure the system so that all scheduling has to go through a scheduler, and can't be done manually via nodeName. This requires being able to ACL which clients can write nodeName.

You mentioned combined controller+schedulers like Daemon Controller. They would be in the ACL. Basically, any component that the admin trusts to obey the scheduling policies gets ACLed to write nodeName.

In general we do need to put scheduling predicates in the Kubelet, but it seems to me that's not practical for predicates that require large configurations (like dedicated machines). Additionally, if "write your own scheduler" is to be one of the extensibility strategies for scheduling policies, a user-written scheduler may have additional predicates that aren't compiled into the Kubelet. It can't secure enforce such policies if nodeName is writable by end-users.

**Comment by smarterclayton** [comment] 2015-08-25 14:40
To mention, pull #12962 changes the behavior of ordering of deletion (a node will not be deleted as long as we observe pods scheduled to that node, minus the possible race of a nodeName being targeted between the window when delete completes and the node is created).

**Comment by smarterclayton** [comment] 2015-08-31 15:22
This is fixed by #12962

**Closed by smarterclayton** 2015-08-31 15:22 UTC
Labels: priority/P1, team/control-plane
