### ISSUE TITLE
unit flake: TestDQ_sanity_check is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25349] opened 2016-05-09 12:30 UTC
Failure:

    --- FAIL: TestDQ_sanity_check (2.01s)
	delay_test.go:137: delay too short: 1.881104721s, expected: 2s
    --- PASS: TestDFIFO_sanity_check (2.06s)
    --- PASS: TestDQ_ordered_add_pop (3.13s)
    FAIL
    FAIL	k8s.io/kubernetes/contrib/mesos/pkg/queue	3.453s

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/25344/kubernetes-pull-test-unit-integration/24932/build-log.txt

**Comment by liggitt** [comment] 2016-05-10 17:59
```
--- FAIL: TestDFIFO_Offer (1.02s)
	delay_test.go:404: delay too short: 811.573966ms, expected: 1s
```

**Comment by fejta** [comment] 2016-05-23 22:30
Assigning to @jdef per https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/OWNERS

**Comment by goltermann** [comment] 2016-06-06 18:26
@jdef  do you have reason to think this is still happening?  if not, want to close it?

**Comment by k82cn** [comment] 2016-09-23 02:24
Test passed with the latest code, suggest to close it firstly; if happened again, please assign it to me directly :).

Head: `88bcf4a5b48daddafb4ab644984f0d711992f998`
OS: `Darwin klauss-mbp.cn.ibm.com 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64`
Test command: `make test WHAT=contrib/mesos/pkg/queue`
Test output:

```
...
Running tests for APIVersion: v1,apps/v1alpha1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1alpha1,extensions/v1beta1,federation/v1beta1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1,imagepolicy.k8s.io/v1alpha1,storage.k8s.io/v1beta1
+++ [0923 10:10:44] Running tests without code coverage
ok  	k8s.io/kubernetes/contrib/mesos/pkg/queue	3.168s
```

**Comment by wojtek-t** [comment] 2016-09-23 07:42
@k82cn - this is flake, not permanent failure (as almost all issues with "kind/flake"; running a test once most probably will not fail and that's expected

**Comment by k82cn** [comment] 2016-09-23 08:39
@wojtek-t, thanks for your input.
The log is gone, let me check the code to see if any clue :).

**Comment by k82cn** [comment] 2016-09-23 10:05
Here maybe the root case after reviewing the code: the `TestDQ_sanity_check` do the following steps:

1. add `testJob` into `DelayedQueue`
2. get current time (`before := time.Now()`)
3. pop item from `DelayedQueue`
4. get current time (`now := time.Now()`)
5. check the wait period (`now.Sub(before)`)

The problem is that: the timer start at "Step 1" in `q.Add()`  in `DelayedQueue`, if there's any delay between "Step 1" & "Step 2", the wait period will be shorter than expected. The proposed PR is to record time before adding item.

If any comments, please let me know.

Thanks
klaus

**Closed** 2016-09-24 21:21 UTC
Labels: flake-needs-czar-attention-release-1.4, kind/flake, priority/P1, team/mesosphere
