### ISSUE TITLE
Make `InitializerConfiguration` per namespace level

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#53859] opened 2017-10-13 02:29 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
This is a issue from istio https://github.com/istio/istio.github.io/issues/660

The current `InitializerConfiguration` is cluster level and all of the affected resources (deployment etc) will be adding the `pending initializers`, but if the initializers are down or the initializer does not clear the `pending initializers`, the resources will always hang.

It is better make the `InitializerConfiguration` namespace level.

/cc @caesarxuchao 

/sig api-machinery

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment] 2017-10-13 02:58
@gyliu513 Well, I don't think making the `InitializerConfiguration` namespaced is a good idea. If so, we need to start multiple initializers per namespace, right? It is such a burden.

Also why not directly making your own initializer watching certain namespace, such as the namespace where the `InitializerConfiguration` is. This will be much simpler instead of changing Kubernetes.

Just as @ayj mentioned, istio/pilot#1437 and `excludeNamespace` could possibly be enhanced to support your use case.

**Comment by gyliu513** [comment] 2017-10-13 03:06
@dixudx I think it is the API server who added the `pending initalizers` to the kubernetes resources, so I was hoping that we can probably add a flag in `InitializerConfiguration`, such as 

```
namespace: xxx
```

If namespace is configured, then `InitializerConfiguration` will be namespace level; if not configured, will still be global level. This can make the configuration more flexible.

**Comment by gyliu513** [comment] 2017-10-13 03:06
@dixudx I think it is the API server who added the `pending initalizers` to the kubernetes resources, so I was hoping that we can probably add a flag in `InitializerConfiguration`, such as 

```
namespace: xxx
```

If namespace is configured, then `InitializerConfiguration` will be namespace level; if not configured, will still be global level. This can make the configuration more flexible.

**Comment by gyliu513** [comment] 2017-10-13 03:07
Of course I can update the initializer to handle such logic first, but I do hope that the initializer should be enhanced to support this as well.

**Comment by dixudx** [comment] 2017-10-13 03:23
Since `InitializerConfiguration` does not contain any sensitive information and also we may not want anyone to alter it after applying, e.g.  we want to enforce image pulling by adding related initializer controller. It will be redundant to make them namespaced.

> If namespace is configured, then InitializerConfiguration will be namespace level; if not configured, will still be global level. This can make the configuration more flexible.

@gyliu513 Right. This will be better. 

@ahmetb @caesarxuchao I am thinking whether we could add a new field like `Namespaces: []string` to indicate this.

https://github.com/kubernetes/kubernetes/blob/17a6115103e5ed98e5de78e145ff244560051698/staging/src/k8s.io/api/admissionregistration/v1alpha1/types.go#L77-L106

If this field is set, then only specific namespaces will apply the `InitializerConfiguration`. Otherwise, applying for all namespaces by default, just like what we are using right now.

WDYT?

**Comment by ahmetb** [comment] 2017-10-13 04:51
This is a duplicate of #51290.

- I see that in Istio case we're looking at opt-in Namespaces for initialization. **I'm curious if opt-out should also be possible** (i.e. I don't want any initialization in kube-system or kube-addons namespaces). What do you think?

- I'm not sure if `[]string` of Namespace names is a pattern currently discouraged by the API. A pattern in use for selecting namespaces is in the NetworkPolicy API. It has a [`NamespaceSelector` field](https://kubernetes.io/docs/api-reference/v1.8/#networkpolicypeer-v1beta1-extensions) of type `LabelSelector` to do label-based selection. Arguably both options have merits, but I'm curious if the list of names has any disadvantage (why didn't NetworkPolicy API go with this)?

**Comment by dixudx** [comment] 2017-10-13 08:38
> **I'm curious if opt-out should also be possible** (i.e. I don't want any initialization in kube-system or kube-addons namespaces. There's definitely use case for this, and in this case I probably shouldn't start namespaces field to all my initializerconfigurations).

Well, to some extent, this could help solve the problem. But only these selected `kube*` namespaces. What if we expand the scope and do not want to apply initializers to other selected namespaces, not just `kube*` namespaces. When running a multi-tenant cluster, it'd be useful to apply some policies in just certain namespaces.

I think we'd better to provider a more general way to incorporate this. WDYT?

> I'm not sure if `[]string` of Namespace names is a pattern currently discouraged by the API.

Yes, this may not be that efficiency and elegant.

> A pattern in use for selecting namespaces is in the NetworkPolicy API. It has a NamespaceSelector field of type LabelSelector to do label-based selection. Arguably both options have merits, but I'm curious if the list of names has any disadvantage (why didn't NetworkPolicy API go with this)?

+1. This looks nicer and provides more powerful selecting rules, which may be the a great bonus for choosing this. Also this keeps consistent with NetworkPolicy.

Filed a PR #53879. @gyliu513 @ahmetb PTAL.

**Comment by ahmetb** [comment] 2017-10-13 16:10
@dixudx I was just curious whether []string is a worse idea than NamespaceSelector or not, from an API design perspective.

I think almost no one labels their namespaces currently (or at least I've not seen in anywhere). That's why I don't find NetworkPolicy's design in this case particularly useful (i.e. I have to label existing namespaces like `default` to apply cross-NS policies with it.)

What do folks think about allowing both, but only one can be allowed at a time:

```yaml
namespaces:
  namespaceSelector: (...LabelSelector)
  names: (...[]string)
```

**Comment by dixudx** [comment] 2017-10-14 15:03
> I was just curious whether []string is a worse idea than NamespaceSelector or not, from an API design perspective.

If using `[]string`, we may need to list the namespaces exhaustively, which is error-prone. For new added namespace, a manual update to the initializer is required, which is not quite convenient and flexible.

> I think almost no one labels their namespaces currently (or at least I've not seen in anywhere).

@ahmetb You're right. So I [did not use labels when matching](https://github.com/dixudx/kubernetes/blob/7cb9ee46f9460f163cd23e2b1490a4f54ab60be8/staging/src/k8s.io/apiserver/pkg/admission/plugin/initialization/initialization.go#L309-L311). 

```
!selector.Matches(labels.Set(map[string]string{"namespace": namespace}))
```

> That's why I don't find NetworkPolicy's design in this case particularly useful (i.e. I have to label existing namespaces like default to apply cross-NS policies with it.)

With above implementation, we don't need to explicitly add new label `namespace=xxx`, which may be misconfigured to other value.

**Comment by cmluciano** [comment] 2017-10-17 15:39
@ahmetb FWIW NetworkPolicy v1 discussion is [here](https://github.com/kubernetes/kubernetes/pull/39164#discussion_r116577498) . IIRC the original thoughts were a special field on the actual Namespace object, but this was in clear violation of proper layering.

**Comment by cmluciano** [comment] 2017-10-17 15:43
Also I agree that this is a duplicate of https://github.com/kubernetes/kubernetes/issues/51290 .

@dixudx @gyliu513 Can we condense thoughts of this issue in another comment on https://github.com/kubernetes/kubernetes/issues/51290 to eliminate issue sprawl?

**Comment by ahmetb** [comment] 2017-10-17 16:58
Yeah I'm still curious if we can have a namespace selector with labels XOR well as name list (opt-out version of this) for the initializers. I think labels have merit, but in practice people are not labeling things.

@dixudx I didn't fully understand your explanation above. Can you give some concrete examples?

**Comment by gyliu513** [comment] 2017-10-18 03:44
+1 to close this and move all the discussion there.

@dixudx can you please help post a summary of the discussion to that issue and close this one?

/assign @dixudx

**Comment by dixudx** [comment] 2017-10-18 06:54
> I think labels have merit, but in practice people are not labeling things.

@ahmetb Yes, you're right. So I did not read the namespace label from `metadata.Labels` when admitting `initializerConfigurations`. Instead I make such a selector `labels.Set(map[string]string{"namespace": namespace})` when finding appropriate initializers.

And `namespaceSelector` in `InitializerConfiguration` can be set like this,

```
....
     namespaceSelector: namespace!=kube-system
...
```

**Comment by ahmetb** [comment] 2017-10-18 07:04
@dixudx so is the NamespaceSelector field going to be of type `LabelSelector`? Are labels going to work as selectors in addition to your example?

**Comment by dixudx** [comment] 2017-10-18 07:09
> so is the NamespaceSelector field going to be of type LabelSelector?

Yes.

> Are labels going to work as selectors in addition to your example?

`metadata.Labels` are not used/referenced in `namespaceSelector`.

**Comment by ahmetb** [comment] 2017-10-18 07:19
@dixudx (still not sure if the answer to my question is yes or no 😄 ) My understanding is that LabelSelector helps you specify a namespace like:

```
apiVersion: v1
metadata:
  name: foo
  labels:
    purpose: test
```

using 

```yaml
namespaceSelector:
  purpose: test
```

If this is not working then the behavior of the `namespaceSelector` field is not compatible with NetworkPolicy API. I think it should be, if we're using the same field name, it should behave the same.

**Comment by dixudx** [comment] 2017-10-18 07:28
@ahmetb The behavior of my `namespaceSelector` is not like this, since we only care about namespaces here, right? The `namespace` value is retrieved from `attributeRecord` when admitting checks for `create` requests to add initializers.

> not compatible with NetworkPolicy API. I think it should be, if we're using the same field name, it should behave the same.

Well, we could make them compatible later if there is a consensus. But if so, does it mean we have to add a new label `namespace: xxx` in `metadata.Labels`? As you said, almost no one labels their namespaces currently.

**Comment by dixudx** [comment] 2017-10-18 07:31
/close

move discussions to #51290.

**Closed by dixudx** 2017-10-18 07:31 UTC
Labels: kind/feature, sig/api-machinery
