### ISSUE TITLE
Work around KubeProxy panic that makes Node's network not working

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#25543] opened 2016-05-12 19:06 UTC
Currently a Docker bug may cause KubeProxy to crashloop thus making the Node unable to use cluster network, which in turn makes Pods scheduled on this Node unreachable.

To mitigate this issue we need to surface the information about problems with KubeProxy, that will allow scheduler to ignore given node when scheduling new Pods. ProblemAPI is going to address this kind of problems in the future, but we need a fix for the 1.3.

Either Kubelet or KubeProxy needs to update a NodeStatus with the information that Node networking is down. I suggests that we reuse NodeReady Condition for this, as this would make the rest of ControlPlane work out of the box. We will replace this fix with the ProblemAPI use in the future. @thockin @dchen1107 

Another option, which requires more work, is creating a completely new NodeCondition type to handle this case. This would require making Scheduler aware of this new Condition. @davidopp @bgrant0607 

@alex-mohr @wojtek-t @fgrzadkowski @zmerlynn

**Comment by bgrant0607** [comment] 2016-05-13 00:13
Does kubelet monitor kube-proxy health?

**Comment by dchen1107** [comment] 2016-05-13 00:22
Kube-proxy today runs as a static pod (daemonset), kubelet treats it the same as other static pods. Yes, Kubelet reports kube-proxy podstatus back to master, that is all. The detail information on kube-proxy is in crashloop at https://github.com/kubernetes/kubernetes/issues/24295#issuecomment-218597689

**Comment by dchen1107** [comment] 2016-05-13 00:32
cc/ @philips Brandon, this issue explains my long position against running kubelet, kube-proxy, etc. critical daemons as docker container. I am ok to packaging them into docker image, and running as linux containers, but they shouldn't depend on docker daemon.

**Comment by yifan-gu** [comment] 2016-05-13 00:37
@dchen1107 I think we don't want to run them as docker containers as well, we want to run them as rkt containers.

**Comment by dchen1107** [comment] 2016-05-13 00:49
@yifan-gu The initial proposal I reviewed was docker container, and I did raise my concerns to @vishh, @mikedanese and coreos developers then. Running it as rkt container should be ok since rkt is daemon-less today, and shouldn't have this chicken egg issue at the first place. But we still have the problem on the nodes without rkt as runtime. 

@gmarek At the meeting, I suggested that kube-proxy update NodeStatus with a newly introduced NodeCondition, like what we plan to do with kernel issue at: https://github.com/kubernetes/kubernetes/issues/23028#issuecomment-215578728 The reason of not using NodeReady is that kubelet might override that. 

Another very hacky way is before crashing, Kube-proxy logs the read-only filesystem problem somewhere, like /var/lib/kube-proxy/... Kubelet will pick up the information, then update NodeReady Condition with detail error message prefixing with "kube-proxy:" kube-proxy's responsibility to make the information up-to-date.

**Comment by mikedanese** [comment] 2016-05-13 01:24
Can I have more description of the bug? Is there a related docker issue? Is there a repro? Does this only affect kube-proxy or will it affect other pods on the node?

We need to support running critical applications (including system daemons) in pods in order to allow easy deployment and integration with vendors (e.g. storage and network vendors). cc @aronchick @thockin since we were just talking about integrating through addons. What features are we missing that we can't support this right now? Is it just that our default container runtime is buggy and flaky and unreliable? Do we need the NodeProblem API? Do we need taints/tolerations?

**Comment by gmarek** [comment] 2016-05-13 05:22
@mikedanese - I don't know about any way to repro it other than running huge clusters. Pretty much every run of a 1000 Node cluster has this problem on at least one Node.

**Comment by dchen1107** [comment] 2016-05-14 00:01
@mikedanese If you want to know the detail, see https://github.com/kubernetes/kubernetes/issues/24295#issuecomment-218597689. It is a docker issue, and pretty rare.

**Comment by thockin** [comment] 2016-05-17 07:02
Can we regroup on this issue this week?  Like tomorrow?

**Comment by thockin** [comment] 2016-05-17 07:12
I will happily make kube-proxy write to or offer up pretty much any API we
deem necessary to detect this issue.

To me it still feels like a docker health-check suite is needed, and one of
the tests is that sysfs gets mounted rw.  BUt in the mean time, how about
this:

make `/var/run/kubernetes/problems/` be the API.  Any component which feels
that it has a node problem can write a JSON file into that directory.

```go
type Problem struct {
  Description string `json:"description"`
  Suspect string `json:"suspect"`
  Reference string `json:"reference"`
  Timestamp: string `json:"timestamp"`
}
type ProblemList []Problem
```

For this case, kube-proxy would write a file:

```json
{
    [
        {
            "description": "sysfs is read-only",
            "suspect": "docker",
            "reference": "
http://github.com/kubernetes/kubernetes/issues/25543",
            "timestamp": "2016-05-17 12:10PDT"
        }
    ]
}
```

Kubelet can turn that into Node status reports.

**Comment by gmarek** [comment] 2016-05-17 08:48
cc @dchen1107 @alex-mohr @davidopp @wojtek-t @zmerlynn

**Comment by dchen1107** [comment] 2016-05-23 17:15
PR of introducing NodeProblemDetector was merged last week, and the pr to enable it by default for Kubernetes cluster was merged over the weekend. So far everything works fine. 

Even it is an alpha feature, GKE folks agreed to enable it for GKE. To workaround this particular issue before we have proper docker fix, we can easily extend today's KernelMonitor module of NodeProblemDetector to monitor kube-proxy log, and report a new NodeCondition called SysfsReadonly to the issue visible. 

But we don't have remedy system yet, and pr of converting node problem (events, conditions etc.) to taints is still under the debate / review: 
1) Should NodeController respect this new Condition, and simply mark node NotReady?
2) Should repair system pickup this issue, and restart docker?

**Comment by dchen1107** [comment] 2016-06-03 18:03
Do we still observe the problem with docker 1.11.X? If no, I want to close this; otherwise, we are going to reconfigure NodeProblemDetector to make the issue visible.

**Comment by dchen1107** [comment] 2016-06-03 19:10
cc/ @davidopp

**Comment by thockin** [comment] 2016-06-03 20:17
Agree, I'd love to *not* "fix" this..

**Comment by wojtek-t** [comment] 2016-06-03 20:29
I think we've seen it the day before yesterday during our tests - @gmarek can you please confirm?

**Comment by gmarek** [comment] 2016-06-04 07:19
I can't recall - we certainly did saw some failed nodes during the test, but I'm not sure we made sure it was a kube-proxy issue.

**Comment by wojtek-t** [comment] 2016-06-04 07:37
But what I can tell for sure that it's definitely less frequent - we started 2000-node cluster 10+ times during this week and we've seen it at most once (which makes it at least 99.995% reliable).

**Comment by zmerlynn** [comment] 2016-06-04 14:31
Not enough data. GKE is still deploying the old ContainerVM and isn't running Docker 1.11.1 yet, unless I'm mistaken.

**Comment by wojtek-t** [comment] 2016-06-06 06:26
aah ok - I didn't know that...

**Comment by zmerlynn** [comment] 2016-06-06 22:41
I'm going to tentatively close this until we show that it's a problem on Docker 1.11.2, now that Docker 1.11.2 is in `master` on both GCE and GKE.

**Comment by zmerlynn** [comment] 2016-06-06 22:41
(Obviously feel free to reopen if I'm wrong.)

**Comment by Random-Liu** [comment] 2016-06-10 23:55
Another occurrence: https://github.com/kubernetes/kubernetes/issues/26135#issuecomment-225315536

**Comment by bprashanth** [comment] 2016-06-15 19:48
So it's still happening, can we teach NDP to detect and surface this as node unschedulable?

**Comment by Random-Liu** [comment] 2016-06-16 18:09
@bprashanth Yes, we can. But I found that the error only occurred once with docker 1.11 till now.

At least, this should be a known issue, right? https://github.com/kubernetes/kubernetes/issues/27076

**Comment by bprashanth** [comment] 2016-06-16 18:17
> @bprashanth Yes, we can. But I found that the error only occurred once with docker 1.11 till now.

Doesn't this render the node unusable (i.e no services will work because kube-proxy is broken)? if so, we should surface regardless of frequency IMO. Whether we fix or paper over it is a different issue.

**Comment by wojtek-t** [comment] 2016-06-17 06:29
>
Doesn't this render the node unusable (i.e no services will work because kube-proxy is broken)? if so, we should surface regardless of frequency IMO. Whether we fix or paper over it is a different issue.

+1

**Comment by Random-Liu** [comment] 2016-06-17 06:50
@bprashanth Because it's code freeze, I can add a temporary short hack in node problem detector to detect this issue. @dchen1107 Should we de that? :)

**Comment by dchen1107** [comment] 2016-06-17 18:10
Removed the priority and added it back to 1.3 milestone, so that we can discuss at burndown meeting.

**Comment by bprashanth** [comment] 2016-06-17 18:22
Yeah i think codefreeze just means no features

**Comment by dchen1107** [comment] 2016-06-17 22:36
It is very rare after we upgrade to docker 1.11.X. To extend KernelMontor in NodeProblemDetector to detect the issue is totally overkill, since we have to allocate more compute resource to NodeProblemDetector to process tons of kube-proxy logs. Here is what I suggested for this issue for 1.3 and 1.4+:

- Document this as known issue for docker releases: docker 1.10.X (#19720), docker 1.11.X (#23397). Also document it as Kubernetes 1.3 release known issue at https://github.com/kubernetes/kubernetes/issues/27076. @Random-Liu is also updated admin guide for NodeProblemDetector, and the suggestion on how to handle this issue will be included there. 
- For 1.4, I think we should change kube-proxy. Instead of logging the error then crashing, kube-proxy should report its problem to NodeProblemDector, which aggregates the node issues and propagate them to upstream layers, so that the admin / remedy system & control-plane can take proper action upon the issues. 

I am removing this from 1.3 milestone, and unassigning myself. cc/ @matchstick to find the right owner from cluster team for next release here.

**Comment by zmerlynn** [comment] 2016-06-22 21:02
On a 2k node cluster, I just saw 4 nodes come up this way on Docker 1.11.2. I'm not saying it's going to stop the release, but it does stop bringup on large clusters pretty frequently. For some reason we went through a "nice" patch where it was rare, but today it was just bad.

**Comment by Random-Liu** [comment] 2016-06-22 21:27
@zmerlynn We can have a quick fix in node problem detector by parsing the kube-proxy log.
But the problem is that, kube-proxy generates logs very fast. If we let node problem detector do that, it has to waste cpu even on the good nodes.
A better solution is let node problem detector expose an endpoint and let other system components report problems. However, we are not there yet for 1.3.
If we'd still want to solve this for 1.3, we could let kube-proxy have some kind of error log, and only print error in it. Then we can change node problem detector to parse the error log and report problems. By this, we can at least make these errors visible to users.

/cc @dchen1107 @bprashanth

**Comment by dchen1107** [comment] 2016-06-23 21:22
Comment at https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-226897582 is still valid. We cannot do much for 1.3 release here, and extending NodeProblemDetector to parse the application logs is wrong move. Also NodeProblemDetector is not running on GKE nodes  yet.

**Comment by eparis** [comment] 2016-06-24 13:26
I'm seeing people say they reproduced on 1.11.2, is there a 1.11 docker issue? I know that https://github.com/docker/docker/issues/7101 was closed. If I'm going to get my docker guys to dig, I need a docker bug report...

**Comment by alex-mohr** [comment] 2016-06-24 19:19
@matchstick Can you please ramp up on this and come up with a way to bring node and kube proxy teams together to resolve?  Even if we don't land in 1.3.0, I propose this is at least a P1 for 1.3.1.

**Comment by wojtek-t** [comment] 2016-06-24 19:27
FYI @alex-mohr and others

In #28015 I added a hacky way of resolving those issues to our test framework. In the last run of gke-large-cluster run it seemed to work (there was 1 broken kube-proxy, this triggered restarting docker, which in turn fixed the problem).

This is obviously not the solution, but:
- it seems to prove that 'docker restart' solves the problem
- it should stop the bleeding in our tests

**Comment by dchen1107** [comment] 2016-06-24 23:12
@eparis & @alex-mohr  I copied & paste what I wrote in another internal thread to give you some background:

No, it is not a blocker for 1.3 release: 
  - It is not a regression from 1.2 release.
  - It is way less frequently after we upgrade to docker 1.11.2 from docker 1.9.1
  - NodeProblemDetector is not designed for processing arbitrary logs. It is an overkill solution given such low frequency and relative high resource overhead. 
  - By default NodeProblemDetector is not running on gke node due to the extra overhead per node introduced to our customer. 


Meanwhile @alex-mohr Since GKE already has repair system built, it should be very easy to extend GKE repair system to check if kube-proxy is in crashloop. If yes, then kubectl logs to retrieve the last terminated container log to see if the issue is caused by readonly root filesystem. If yes, the repair system can issue a docker restart.

**Comment by eparis** [comment] 2016-06-24 23:18
agreed not a blocker. This is likely only fixable in docker. We should keep it up the priority so we dig into and fix docker.  @ncdc can try next week to get our docker people talking to whoever on your side you want to get this fixed (in 1.11.3 or later probably)

**Comment by Random-Liu** [comment] 2016-06-24 23:47
Can we add a node readiness or liveness probe to solve this?

One of the default behaviours of the probe is to make sure the key components are running normally, and the behaviour could be extended overtime.

* Probably adding a node probe controller or node health controller to perform the probing.
* Or just use the health probe of GCE MIG.

Just random thoughts, may not work. :)

**Comment by dchen1107** [comment] 2016-06-25 00:05
@Random-Liu All are good ideas. But let's move that discussion to a separate issue, and use this one to focus providing the workaround for KubeProxy panic within 1.3 timeframe. Thanks!

**Comment by dchen1107** [comment] 2016-06-25 00:06
Also what you suggested probe controller can be easily achieved by GKE repair system.

**Comment by Random-Liu** [comment] 2016-06-25 00:07
@dchen1107 Agree. https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-228490986 needs quite a lot of work, definitely not for 1.3 :)

**Comment by goltermann** [comment] 2016-06-27 18:11
Keeping in v1.3 until we decide on Docker 1.11 for sure.

**Comment by zmerlynn** [comment] 2016-06-27 18:14
The `kube-proxy` issue seems to be present on old and new docker alike, sadly.

**Comment by Random-Liu** [comment] 2016-06-27 18:59
I opened a docker issue here https://github.com/docker/docker/issues/24000. Feel free to supply information on that issue.

**Comment by thockin** [comment] 2016-07-03 16:22
So what's the right kube-proxy fix?

**Comment by wojtek-t** [comment] 2016-07-04 06:28
@thockin - didn't we decided that we just want to discover this problem in NodeProblemDetector and then mark this node as not-healthy (whatever that means - adding a new condition or extending NodeReady or ...)? In my opinion if it would be clear to user why this node is not healthy, this should be good enough.

FYI in https://github.com/kubernetes/kubernetes/pull/28015 I worked around this in our tests :)

**Comment by thockin** [comment] 2016-07-04 06:51
It wasn't clear to me if kube-proxy should do something different or not.

**Comment by bprashanth** [comment] 2016-07-06 17:37
yeah this is a docker bug (https://github.com/docker/docker/issues/7101), unsure if there's a pod level workaround, couldn't make out if it was specific to hostNetwork. the work around is restarting docker. 

It happened more frequently in 1.9, but still happens on 1.11 (node team empirical data). To surface it to the NPD we need to either send some http event to a NPD server (vaporware) or write to a special hostPath termination log type file (parsing kube-proxy logs form NPD is too expensive).

**Comment by matchstick** [comment] 2016-07-07 05:43
This feels like a hot potato but I am not sure if it still needs to be addressed or not. If it does, let's do so. I apologize for not being able to understand what the current status is.
It looks like we have a [docker/docker#7101](https://github.com/docker/docker/issues/7101).

Reading @dchen1107's comment from 12 days ago she states:
While folks may want the node problem detector extended to parse logs to detect it, that is not a good fit for that system and it doesn't run on all nodes anyway. Also GKE can be extended to possibly repair this problem.

@Random-Liu @thockin @bprashanth @alex-mohr @gmarek @zmerlynn @eparis 
Questions: 
Is this an issue that we need to still address for production? 
Or can we wait for docker fix?
If we haven't fixed the kube-proxy panic (which we should) how do ensure we still provide a signal that this is happening?

**Comment by matchstick** [comment] 2016-07-07 05:44
I am leaving this on 1.3 until we know the best thing to do.

**Comment by thockin** [comment] 2016-07-07 05:48
If we can DIRECTLY tell the node problem system about a problem, I have no
qualms about doing that.  drop a file in a dir, for example.

**Comment by Random-Liu** [comment] 2016-07-07 05:59
@thockin @matchstick Node problem detector is not running on GKE cluster now. :)
https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-228493292 and https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-228490986 should be a better fix for this.

If we still want a fix in the node problem detector, letting kubeproxy drop a file could be enough for now.

**Comment by thockin** [comment] 2016-07-07 06:04
If you can give me a spec of what dir to mount and what sort of file to
write, I'll do it.

**Comment by Random-Liu** [comment] 2016-07-07 06:42
@thockin For temporary fix, something like `2>kube-proxy.log.stderr` should be enough.
The kernel monitor of node problem detector could be ported to parse arbitrary log, the only reason we can't do that for kube-proxy.log is because the log is too spammy.
`2>kube-proxy.log.stderr` should be enough for now. I checked the node in `kubernetes-e2e-gke-large-cluster` and `kubernetes-e2e-gce` cluster, normally only few lines are at Error level. :)

**Comment by thockin** [comment] 2016-07-07 06:52
I thought that Dawn said we DO NOT want to parse logs.  Parsing logs is, in
general, a total hack and very very brittle.  we should have a real push
API.

**Comment by matchstick** [comment] 2016-07-07 07:34
@Random-Liu I agree with @thockin I also understood @dchen1107 thought we should not parse logs. Is that common practise for the node problem detector? It feels fragile to me and to be avoided.

**Comment by Random-Liu** [comment] 2016-07-07 08:29
@thockin @matchstick Yeah, I agree parsing log is fragile, that's why I call it a temporary or a quick fix. :)
The only good thing is that it doesn't need significant change on both sides, although I don't think it's a good solution, either. :(

For a better fix, it will need some more design and work. Let me think about it a little more~

Moreover, I still think https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-228485749 and https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-228490986 is the best solution for this issue.

As a key component of Kubernetes, it's wired that we don't have a component to monitor whether it is healthy or not.

**Comment by bprashanth** [comment] 2016-07-07 21:36
Re making kube-proxy "not panic", it currently fails in resizing the hash table for conntrack entries, for which it needs to write to /sys. I'm not sure if there are more locations (we moved /sys/module/br_netfilter loading into kubelet IIUC), or if conntrack itself needs write access to /sys. 

I think Dawn/Liu are more worried about the NPD not parsing kube-proxy logs, because its memory usage would balloon. If kube-proxy can detect the situtation internally, either by parsing its own logs (which is brittle) or poking someting in /sys for example (like the hash table resizing it's currently failing on), it can drop a token into a hostPath (hoping the docker bug doesn't manifest as ro hostPath). 

Kube-proxy will still remain dysfunctional, though we might be able to:    
1. Surface the issue/mark node unusable
2. Setup a feedback loop that restarts docker 

We just need to be careful to cleanup the hostPath so it doesn't end up in a restart loop.

**Comment by alex-mohr** [comment] 2016-07-07 23:31
My understanding of 1.3's state based on a brief chat with @Random-Liu : something like ~1 in 1000 nodes will be affected by this issue and if nodes are affected, pods scheduled on those nodes have {broken,little,no} networking.

We hope Docker will eventually fix it.  But because that's not the case for 1.3, and we don't want to make excessive changes to 1.3, perhaps that means that we should fix it expediently.

Summarizing my understanding of previous discussion: expedient thing would be some mechanism to detect (@bprashanth's proposal like kube-proxy detecting and writing to /tmp/kube-proxy-claims-docker-issue-present.txt) and $something (kubelet, node problem detector, a bash script in a loop) that checks for existence of that file followed by some form of remediation {kill docker, sudo reboot, .....} to bash the node into working again.

Maybe an ugly hack is okay for now and we hope that docker fixes it for the next release so in 1.4 we can rm the code?  Or for 1.4 we can do something that is More Elegant And Less Offensive To Engineering Sensibilities?

**Comment by thockin** [comment] 2016-07-08 05:15
Bounded-lifetime hacks are fine, but they need to come with giant
disclaimers and named-assignees to cleanup the mess after a specific event.

**Comment by alex-mohr** [comment] 2016-07-08 13:08
Agree, re: bounded-lifetime hacks needing care and we shouldn't do them indiscriminately.

We and our users have a problem today -- and we've had a problem for the past N months without traction.  I'd like the problem solved for 1.3 because I'd like us to have a great product and I don't think the state of broken nodes is there.

Aside; we've spent N hours discussing the issue and could likely have worked around the issue in less aggregate people time than we spent discussing?  Apologies for the leaked frustration: this issue seems to be stuck in either some form of analysis paralysis or cracks between teams or perfect-is-the-enemy-of-the-good state.

@Random-Liu Again, I don't care about implementation details.  We also need more than just tech or a piece of code.  Exit criteria is that users don't get broken nodes shipped to them.

**Comment by bprashanth** [comment] 2016-07-08 15:45
>Exit criteria is that users don't get broken nodes shipped to them.

We're not going to solve this problem for as long as we depend on a lagging docker release cycle, and they don't backport or do intermediate releases to help us. This is just a one off docker bug that's left us in a bad state. Such issues come up every release, get documented in the release notes and we ship anyway. 

The easiest fix (disclaimers and all) is to redirect kube-proxy stderr and parse it out from NPD. Even then, the node will remain broken unless we restart docker. the NDP will only surface the error.

**Comment by Random-Liu** [comment] 2016-07-08 16:54
@alex-mohr I'm working on a PR yesterday night, will send it out soon.

**Comment by Random-Liu** [comment] 2016-07-08 18:17
FYI, a fix is here #28697.
In #28697, I let kube-proxy update a node condition `RuntimeUnhealthy` with specific reason, message and hit to the administrator about the remediation.
The specific reason why we want to do this is discussed in the PR description https://github.com/kubernetes/kubernetes/pull/28697#issue-164584119.

**Comment by davidopp** [comment] 2016-07-08 19:19
FWIW I agree 100% with @alex-mohr. 

@Random-Liu using node condition SGTM, but your PR should probably also modify the scheduler here
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L434
to prevent the system from sending new pods to a node that has RuntimeUnhealthy condition. I realize there will still be a time window when we might send some pods to that node (before the problem is detected) but at least the time window will be bounded this way.

**Comment by Random-Liu** [comment] 2016-07-08 20:44
> using node condition SGTM, but your PR should probably also modify the scheduler here
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L434
to prevent the system from sending new pods to a node that has RuntimeUnhealthy condition.

@davidopp Yeah, we can do that. But before that, we should make sure that the node is really unusable without setting conntrack.
In fact, we only setting conntrack to increase the max connection limit on the node (default 64k->256k) https://github.com/kubernetes/kubernetes/pull/19182.
Without this, is the node really considered to be unusable? @thockin 
* If so, we should prevent scheduling pods to the node.
* If not, maybe we should just surface the problem to the administrator and let the node keep working.

> I realize there will still be a time window when we might send some pods to that node (before the problem is detected) but at least the time window will be bounded this way.

Yeah, that's why I think we should not restart docker ourselves to try to remedy the problem. There may still be workloads running the node. We'd better leave this to the user to decide. :)

**Closed** 2016-07-11 06:42 UTC
Labels: area/platform/gke, priority/P1, team/cluster, team/node

**Comment by Random-Liu** [comment] 2016-07-11 07:23
https://github.com/kubernetes/kubernetes/pull/28697 is merged, and hopefully, it could solve this issue.
I've also sent a PR to revert the walkaround in the test framework https://github.com/kubernetes/kubernetes/pull/28015 to verify whether the issue is really fully solved.

**Comment by bprashanth** [comment] 2016-07-13 20:57
@Random-Liu thanks for the help!

**Comment by alexbrand** [comment] 2017-02-25 18:37
@Random-Liu I just ran into this, and I am able to repro consistently. It might be due to the craziness of my experiment, but I still wanted to contribute the data point.

I am experimenting with docker inside docker. All I am about to describe is itself running inside a privileged CentOS 7 container that has systemd and Docker installed. The CentOS 7 container is running on my dev machine (Docker for Mac). 

I have a kubelet running fine, and all control plane components running as static pods. When I attempt to run kube-proxy as a static pod (privileged) it crashes with the following logs:
```
I0225 18:13:46.886161       1 iptables.go:176] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
I0225 18:13:46.886259       1 server.go:168] setting OOM scores is unsupported in this build
I0225 18:13:46.888648       1 server.go:215] Using iptables Proxier.
I0225 18:13:46.941545       1 server.go:227] Tearing down userspace rules.
I0225 18:13:46.941707       1 healthcheck.go:119] Initializing kube-proxy health checker
I0225 18:13:46.956490       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0225 18:13:46.957841       1 conntrack.go:66] Setting conntrack hashsize to 32768
write /sys/module/nf_conntrack/parameters/hashsize: operation not supported
```
sysfs is mounted as rw:
```
# mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```
sysfs is mounted as rw on containers:
```
docker run -ti --privileged --net=host busybox mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```
Using busybox to further inspect:
```
# docker run -ti --privileged --net=host busybox sh
/ # echo 16384 > /sys/module/nf_conntrack/parameters/hashsize
sh: write error: Operation not supported
/ # mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
/ # id
uid=0(root) gid=0(root) groups=10(wheel)
/ # ls -l /sys/module/nf_conntrack/parameters/
total 0
-rw-r--r--    1 root     root          4096 Feb 25 17:54 acct
-r--------    1 root     root          4096 Feb 25 17:54 expect_hashsize
-rw-------    1 root     root          4096 Feb 25 18:20 hashsize
-rw-r--r--    1 root     root          4096 Feb 25 17:54 nf_conntrack_helper
-rw-r--r--    1 root     root          4096 Feb 25 18:09 tstamp
```

**Comment by pmichali** [comment] 2017-09-28 18:15
@Random-Liu, @alexbrand I'm seeing the same issue when running kubeadm-dind-cluster, where kube-proxy is failing to come up, because it is trying to write to /sys/module/nf_conntrack/parameters/hashsize. This is on the filesystem sysfs, which "mount" shows is rw (so it passes the R/W check in kube-proxy code), but the filesystem is not writeable.

Within kube-proxy:
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)

/sys/module/nf_conntrack/parameters
# touch x
touch: cannot touch 'x': Permission denied

I'm also running docker containers inside of docker containers. FYI, others have not seen this issue, when just running docker on bare-metal.

@ivan4th @danehans
