### ISSUE TITLE
e2e integration test flake: scheduler test nil pointer

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27285] opened 2016-06-13 17:18 UTC
If the node doesn't exist in the cache we can't deference it

```
W0612 13:30:58.798999   17771 reflector.go:334] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:393: watch of *api.Node ended with: too old resource version: 2009 (2014)
panic: interface conversion: interface {} is nil, not *api.Node [recovered]
	panic: interface conversion: interface {} is nil, not *api.Node

goroutine 158712 [running]:
panic(0x243e060, 0xc84b625700)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc83c6a4f30)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x243e060, 0xc84b625700)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
k8s.io/kubernetes/test/integration.waitForReflection.func1(0x1dec540, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:112 +0x222
k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc84c2506e0, 0xc84ab17740, 0xc84c0c0c60, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:210 +0x77
k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc84c2506e0, 0xc84ab17740, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:170 +0x8a
k8s.io/kubernetes/pkg/util/wait.Poll(0x5f5e100, 0x6fc23ac00, 0xc84ab17740, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:164 +0x4f
k8s.io/kubernetes/test/integration.waitForReflection(0xc83c6a4f30, 0x7ff9e4625d80, 0xc84ab51860, 0x2a3a440, 0x19, 0x2dfbf88, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:108 +0x172
k8s.io/kubernetes/test/integration.DoTestUnschedulableNodes.func1(0xc83c6a4f30, 0xc8464a8f00, 0x7ff9e4625d80, 0xc84ab51860, 0xc84aa5eb00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:178 +0x249
k8s.io/kubernetes/test/integration.DoTestUnschedulableNodes(0xc83c6a4f30, 0xc84aa5eb00, 0x7ff9e4625d80, 0xc84ab51860)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:242 +0xaf9
k8s.io/kubernetes/test/integration.TestUnschedulableNodes(0xc83c6a4f30)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:84 +0x73e
testing.tRunner(0xc83c6a4f30, 0x3b68ea0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	k8s.io/kubernetes/test/integration	250.517s
```

**Comment by wojtek-t** [comment] 2016-06-14 10:10
duplicate of #27344

**Closed by wojtek-t** 2016-06-14 10:10 UTC
Labels: component/scheduler, kind/flake, team/control-plane
