### ISSUE TITLE
Nodes sometimes fail to become ready in E2E cluster 

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#29703] opened 2016-07-27 20:53 UTC
This cluster failed validation because only one of four nodes became ready:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/27199/kubernetes-pull-build-test-e2e-gce/50752/build-log.txt

**Comment by dchen1107** [comment] 2016-07-27 22:22
I quickly checked failed logs, and found only master node is at ready state. Kubelet logs are full of the following error message:

I0727 21:08:35.638175    3475 kubelet.go:2079] skipping pod synchronization - [failed to start eviction manager unable to find data for container /]
I0727 21:08:40.638356    3475 kubelet.go:2079] skipping pod synchronization - [failed to start eviction manager unable to find data for container /]
I0727 21:08:45.638551    3475 kubelet.go:2079] skipping pod synchronization - [failed to start eviction manager unable to find data for container /]
...

@pmorie looks like it is caused by pr #27199 which adding disk eviction logic to kubelet. @derekwaynecarr

**Comment by dchen1107** [comment] 2016-07-27 22:23
I am closing this one for now. Please re-open it if I were wrong. I will take a deep look then.

**Closed by dchen1107** 2016-07-27 22:23 UTC
Labels: area/test, priority/P1, team/node

**Comment by derekwaynecarr** [comment] 2016-07-27 22:25
I'll have to debug this.  I was unable to reproduce locally today.  Will investigate tomorrow.
