### ISSUE TITLE
[Failing test] GCE-5000: density tests are failing

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#77080] opened 2019-04-25 14:56 UTC
It seems there is yet another regression in scalability tests (another one is debuged in https://github.com/kubernetes/kubernetes/issues/76579), this time in density tests. It looks unrelated to this another regression as it started to failing later (at 53b7bc30b). 

/sig scalability

**Comment by wojtek-t** [comment] 2019-04-26 08:27
My personal guess would be: https://github.com/kubernetes/kubernetes/pull/74690
Can we try confirming/rejecting this hypothesis?

**Comment by wojtek-t** [comment] 2019-04-26 08:28
@wenjiaswe - FYI (it's not confirmed, but if you could comment on that too)

**Comment by krzysied** [comment] 2019-04-26 11:47
I've opened the [bug for increased cpu usage of apisever](https://github.com/kubernetes/kubernetes/issues/77127). The plot for  [apiserver cpu usage](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=kube-apiserver-gce-scale-cluster-master%2Fkube-apiserver&Resource=CPU) looks exactly like plot for [get pod latency](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=pods&Scope=namespace&Subresource=&Verb=GET).
I guess those two issues are the results of one regression.

**Comment by wojtek-t** [comment] 2019-04-29 13:03
Hmm - this is an interesting graph:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput

@krzysied - how we can have throughput higher than 100? What does the measurement do?

**Comment by krzysied** [comment] 2019-05-06 14:05
> how we can have throughput higher than 100? What does the measurement do?

IIRC The throughput is calculated based of pods becoming observable (returned by watch). My guess is that apiserver or etcd is overloaded during latency pod creation phase. This resulst in watch returning objects in bursts. Therefore the temporary (observed not real) throughput can increase, while the average throughput remains unchanged.

**Comment by krzysied** [comment] 2019-05-06 14:18
About the density test regression:
![pod_cluster_list](https://user-images.githubusercontent.com/25119199/57230906-b97d4a00-7019-11e9-8f83-d7e1cc56d5a0.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=pods&Scope=cluster&Subresource=&Verb=LIST

![pod_cluster_list_count](https://user-images.githubusercontent.com/25119199/57230909-bb470d80-7019-11e9-9e00-7e043e084c42.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityRequestCount&Resource=pods&Scope=cluster&Subresource=&Verb=LIST

It looks like the regression is correlated with pods listing on cluster level. This "additional" pods linting is done by node-controller:

![node_controller](https://user-images.githubusercontent.com/25119199/57231259-7a9bc400-701a-11e9-875d-ef759eed451e.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityRequestCountByClient&client=kube-controller-manager%2Fv1.15.0%20(linux%2Famd64)%20kubernetes%2Fsystem:serviceaccount:kube-system:node-controller&code=200&component=apiserver&group=&resource=pods&scope=cluster&subresource=&verb=LIST&version=v1

**Comment by krzysied** [comment] 2019-05-06 14:36
I looks like the regression is caused by increased time of node controller listing all pods for each nodes.
- Before regression this action took about 17m to be performed. (Time measure between first and last pods list call)
- The first regression (that happened between runs 1117699728771911683 and 1118062113902825476) increased the time to 28m
- The second regression (runs 1119148959034511365 and 1120236390706057221) increased time to 52m.
- The changes between (1121685830616748032 and 1122772971874684928) reduced the time to 30m.

**Comment by krzysied** [comment] 2019-05-06 14:43
It is possible that first regression could have been caused by [mTLS PR](https://github.com/kubernetes/kubernetes/pull/74690). It was introduced  between runs 1117699728771911683 and 1118062113902825476 and reverted between 1121685830616748032 and 1122772971874684928.

**Comment by wenjiaswe** [comment] 2019-05-06 19:00
@krzysied, thanks you very much for your analysis. I will look into [mTLS PR](https://github.com/kubernetes/kubernetes/pull/74690) and submit it again after I resolve the performance issue. Thanks!

**Comment by wojtek-t** [comment] 2019-07-04 16:45
This is now fixed.

**Closed by wojtek-t** 2019-07-04 16:45 UTC
Labels: kind/failing-test, sig/scalability
