### ISSUE TITLE
Two DaemonRestart tests are failing repeatedly in kubernetes-e2e-gke-ci

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#15052] opened 2015-10-03 20:26 UTC
DaemonRestart Scheduler should continue assigning pods to nodes across restart
is failing with some kind of ssh error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:256
Expected error:
    <*errors.errorString | 0xc208525a90>: {
        s: "error getting SSH client to jenkins@104.197.97.173:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain'",
    }
    error getting SSH client to jenkins@104.197.97.173:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain'
not to have occurred
```

DaemonRestart Kubelet should not restart containers across restart
is failing like this:
```
09:25:08 DaemonRestart 
09:25:08   Kubelet should not restart containers across restart
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:275
09:25:08 [BeforeEach] DaemonRestart
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:205
09:25:08 STEP: Skipping test, which is not implemented for gke
09:25:08 [It] Kubelet should not restart containers across restart
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:275
09:25:08 [AfterEach] DaemonRestart
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:211
09:25:08 
09:25:08 •! Panic [0.001 seconds]
09:25:08 DaemonRestart
09:25:08 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:276
09:25:08   Kubelet should not restart containers across restart [It]
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:275
09:25:08 
09:25:08   Test Panicked
09:25:08   runtime error: invalid memory address or nil pointer dereference
09:25:08   /usr/src/go/src/runtime/panic.go:387
09:25:08 
09:25:08   Full Stack Trace
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/nodes.go:67 (0x69fba3)
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1253 (0x4ca09a)
09:25:08   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:259 (0x51fe56)
09:25:08   /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 (0xbab825)
09:25:08   /usr/src/go/src/testing/testing.go:447 (0x460b0f)
09:25:08   /usr/src/go/src/runtime/asm_amd64.s:2232 (0x440671)
```

Sample failures:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8655/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8656/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8657/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8658/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8659/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8660/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8661/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8662/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8663/

@mikedanese @brendandburns @zmerlynn @roberthbailey 
we're not seeing these failures in the GCE runs of this test AFAICT

**Comment by roberthbailey** [comment] 2015-10-04 06:09
These tests should be skipped on GKE (see https://github.com/kubernetes/kubernetes/issues/11834). It seems like returning from the BeforeEach function doesn't actually cause the test to be skipped though, it just prevents the test from running the initialization code. 

It's not surprising that the tests are passing on GCE, since that's the only platform where they should be running.

**Comment by jszczepkowski** [comment] 2015-10-27 10:25
The same problem occurred on GCE. Suit kubernetes-e2e-gce failed due to it:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9143/

**Comment by jlowdermilk** [comment] 2015-12-18 19:27
These tests are now correctly skipped for GKE.

**Comment by davidopp** [comment] 2015-12-19 07:02
Reopening because @jszczepkowski mentioned that it is also sometimes failing in GCE, where it should work.

**Comment by mikedanese** [comment] 2015-12-19 08:12
is this a dup of #17829 at this point?

**Comment by ihmccreery** [comment] 2015-12-22 19:43
I'm closing this as a duplicate of #17829.

**Closed by ihmccreery** 2015-12-22 19:43 UTC
Labels: davidopp, kind/flake, priority/P0, team/control-plane
