### ISSUE TITLE
hack/update-api-reference-docs.sh broken

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27685] opened 2016-06-19 06:03 UTC
It seems to have broken a couple hours ago. `git bisect`ing shows that it's not something that merged that broke it, it's some dependency. I'm disabling it so the merge queue can make progress, and opening this issue so we fix ASAP. Our api docs will be out of date if any changes to the api merges, that seems like an OK tradeoff.

**Comment by sttts** [comment] 2016-06-20 07:07
It's because the `hack/gen-swagger-docs` container accesses master's `pkg/api/v1/register.go` and uses the `GetObjectKind` lines to list the top level api objects (compare https://github.com/kubernetes/kubernetes/blob/master/hack/gen-swagger-doc/gen-swagger-docs.sh#L43). 

In https://github.com/kubernetes/kubernetes/pull/27168/commits/e3af3451c8445639c33644bbcbdc94da16968b87#diff-f0456cede4d61f48e51015136685ba1dL117 these lines for factored out into a generic `TypeMeta` method (https://github.com/kubernetes/kubernetes/pull/27168/commits/e3af3451c8445639c33644bbcbdc94da16968b87#diff-626f1ac5e2de78da4d7aaa83b03b0afcR50).

**Comment by sttts** [comment] 2016-06-20 07:28
The actual root cause of the trouble is that we run scripts from HEAD accessing files from master. If we change the later, the former might get incompatible. Why is that necessary?

Compare https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh#L63.

**Comment by lavalamp** [comment] 2016-06-20 17:49
@sttts thanks for looking into this!

**Comment by lavalamp** [comment] 2016-06-20 17:51
@caesarxuchao looks like you might have had something to do with this, can you put a fix together?

**Comment by fejta** [comment] 2016-06-20 17:57
FYI this is also causing https://k8s-testgrid.appspot.com/google-unit#test-go-release-1.2 to fail

**Comment by caesarxuchao** [comment] 2016-06-20 18:01
@sttts has sent #27706 to fix it. I'm reviewing it.

**Comment by smarterclayton** [comment] 2016-06-20 18:10
Introduced by #27168

**Comment by caesarxuchao** [comment] 2016-06-20 18:19
Thanks @stts. The fix LGTM.

**Comment by goltermann** [comment] 2016-06-21 05:07
Closing, #27706 is merged

**Closed by goltermann** 2016-06-21 05:07 UTC
Labels: priority/P0, team/CSI-API Machinery SIG
