### ISSUE TITLE
panic 'concurrent map writes' in kube-controller-manager in the DeploymentController

### ISSUE THREAD

**Issue by yannchristensen** [kubernetes/kubernetes#29638] opened 2016-07-26 21:58 UTC
kube-controller-manager is hitting a panic 'concurrent map writes'. We have hit this several times, our cluster has 3 worker nodes and around 10 pods so it is small. 

version info:
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+coreos.0", GitCommit:"1c7c17f64b669d94307f6e8bb09e4ca69f63d6b9", GitTreeState:"clean"}

I extracted the log below with this cmd:
    
> kubectl logs kube-controller-manager-ip-10-16-7-10.us-west-2.compute.internal  --namespace kube-system 

....snip....
I0726 21:39:35.154205       1 controllermanager.go:375] Starting apps/v1alpha1 apis
I0726 21:39:35.154214       1 controllermanager.go:377] Starting PetSet controller
I0726 21:39:35.154714       1 controller.go:237] Starting Daemon Sets controller manager
I0726 21:39:35.156005       1 pet_set.go:144] Starting petset controller
E0726 21:39:35.165470       1 util.go:45] Metric for serviceaccount_controller already registered
I0726 21:39:35.172633       1 attach_detach_controller.go:191] Starting Attach Detach Controller
W0726 21:39:35.174264       1 request.go:347] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
W0726 21:39:35.224631       1 request.go:347] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
I0726 21:39:35.239116       1 endpoints_controller.go:322] Waiting for pods controller to sync, requeuing service default/kubernetes
I0726 21:39:35.239149       1 replication_controller.go:554] Waiting for pods controller to sync, requeuing rc kube-system/kube-dns-v11
I0726 21:39:35.239229       1 endpoints_controller.go:322] Waiting for pods controller to sync, requeuing service kube-system/heapster
I0726 21:39:35.243163       1 endpoints_controller.go:322] Waiting for pods controller to sync, requeuing service prod-alpha1-003/signalsapi-service
I0726 21:39:35.243786       1 endpoints_controller.go:322] Waiting for pods controller to sync, requeuing service kube-system/kube-dns
I0726 21:39:35.269144       1 controller.go:641] Waiting for pods controller to sync, requeuing ds ops/signals-fluentd
I0726 21:39:35.286571       1 event.go:216] Event(api.ObjectReference{Kind:"Deployment", Namespace:"prod-alpha-003", Name:"fing", UID:"762f13c2-5378-11e6-9a77-062e72edb83d", APIVersion:"extensions", ResourceVersion:"240127", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set fing-2433196982 to 1
fatal error: concurrent map writes

goroutine 343 [running]:
runtime.throw(0x3bb6aa0, 0x15)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc821bc7dc0 sp=0xc821bc7da8
runtime.mapassign1(0x290c6a0, 0xc8212cafc0, 0xc821bc7ee8, 0xc821bc7ed8)
	/usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc821bc7e68 sp=0xc821bc7dc0
k8s.io/kubernetes/pkg/util/deployment.equalIgnoreHash(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:159 +0x2c1 fp=0xc821bc8270 sp=0xc821bc7e68
k8s.io/kubernetes/pkg/util/deployment.FindOldReplicaSets(0xc820a7ec00, 0xc821433000, 0xe, 0x11, 0xc820058120, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:196 +0x418 fp=0xc821bc9998 sp=0xc821bc8270
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).getAllReplicaSetsAndSyncRevision(0xc82103c900, 0xc820a7ec00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:635 +0x20c fp=0xc821bc9b00 sp=0xc821bc9998
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncRollingUpdateDeployment(0xc82103c900, 0xc820a7ec00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:577 +0x54 fp=0xc821bc9bc8 sp=0xc821bc9b00
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncDeployment(0xc82103c900, 0xc82176b260, 0x16, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:459 +0xa6a fp=0xc821bc9d40 sp=0xc821bc9bc8
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.syncDeployment)-fm(0xc82176b260, 0x16, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:166 +0x42 fp=0xc821bc9d70 sp=0xc821bc9d40
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).worker.func1(0xc82103c900)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:398 +0x113 fp=0xc821bc9e18 sp=0xc821bc9d70
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).worker(0xc82103c900)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:402 +0x21 fp=0xc821bc9e28 sp=0xc821bc9e18
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:179 +0x20 fp=0xc821bc9e38 sp=0xc821bc9e28
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8202959b0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:86 +0x4b fp=0xc821bc9e68 sp=0xc821bc9e38
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8202959b0, 0x3b9aca00, 0x0, 0x1, 0xc820058900)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87 +0xb4 fp=0xc821bc9f38 sp=0xc821bc9e68
k8s.io/kubernetes/pkg/util/wait.Until(0xc8202959b0, 0x3b9aca00, 0xc820058900)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x43 fp=0xc821bc9f68 sp=0xc821bc9f38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821bc9f70 sp=0xc821bc9f68
created by k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:179 +0x158

**Comment by AdoHe** [comment] 2016-07-27 00:49
@kubernetes/deployment

**Comment by yannchristensen** [comment] 2016-07-27 18:31
forgot to include version information (also added inline):
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+coreos.0", GitCommit:"1c7c17f64b669d94307f6e8bb09e4ca69f63d6b9", GitTreeState:"clean"}

**Comment by kargakis** [comment] 2016-08-03 10:25
Dupe of https://github.com/kubernetes/kubernetes/issues/29960

**Closed by kargakis** 2016-08-03 10:25 UTC

**Comment by lavalamp** [comment] 2016-08-03 22:06
BTW, if you're hitting this, it means you have deployments with overlapping label selectors, which is going to cause you problems elsewhere.
