### ISSUE TITLE
InitContainer are not recreated when Pod sandbox changed

### ISSUE THREAD

**Issue by ryarnyah** [kubernetes/kubernetes#49505] opened 2017-07-24 16:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
/kind bug

**What happened**: When "Pod sandbox changed" containers are recreated but initContainer are not.

**What you expected to happen**: If the Pod is restarted, all Init Containers must execute again.

**How to reproduce it (as minimally and precisely as possible)**: Create some pod with a initContainer, reboot node and wait.

**Anything else we need to know?**: Sandbox changed because flannel start after pod. (/run/flannel/subnet.env: no such file or directory)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.4
- Cloud provider or hardware configuration**: CentOS 7.3
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`): Linux controller1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by yujuhong** [comment] 2017-07-24 16:39
Duplicate of #36485

**Closed by yujuhong** 2017-07-24 16:39 UTC
Labels: kind/bug, sig/node
