### ISSUE TITLE
Flaky unit test: Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce 

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#107414] opened 2022-01-07 18:49 UTC
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce 

### Since when has it been flaking?

Jan 7th, 2022

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&include-filter-by-regex=Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce

### Reason for failure (if possible)

reconciler_test.go:1273: Check volume <fake-plugin/volume-name> is reported as attached to node <fail-detach-node>, got false, expected true

### Relevant SIG(s)

/sig storage

**Comment by pacoxu** [comment] 2022-01-10 03:26
https://storage.googleapis.com/k8s-triage/index.html?test=Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce

/cc @jingxu97 @gnufied

**Comment by liggitt** [comment] 2022-04-02 17:20
this is the top unit test flake according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by dims** [comment] 2022-04-02 21:16
cc @xing-yang

**Comment by jingxu97** [comment] 2022-07-01 23:50
I think this test is no longer flaky by checking the test grid, close it now.

**Comment by brianpursley** [comment] 2022-07-27 17:51
Unfortunately this does still seem to be flaky:
https://storage.googleapis.com/k8s-triage/index.html?text=Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce

```
{Failed  === RUN   Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce
W0727 17:07:22.173879   55592 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0727 17:07:22.174421   55592 reconciler.go:343] "attacherDetacher.AttachVolume started" volume={VolumeToAttach:{MultiAttachErrorReported:false VolumeName:fake-plugin/volume-name VolumeSpec:0xc0001a8588 NodeName:fail-detach-node ScheduledPods:[&Pod{ObjectMeta:{pod-uid1  pod-uid1  pod-uid1  0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:PodSpec{Volumes:[]Volume{},Containers:[]Container{},RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},SetHostnameAsFQDN:nil,OS:nil,},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},},}]}}
I0727 17:07:22.174609   55592 operation_generator.go:398] AttachVolume.Attach succeeded for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "fail-detach-node" 
E0727 17:07:23.175440   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0727 17:07:23.185778   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0727 17:07:23.196123   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0727 17:07:23.206659   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0727 17:07:23.217079   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0727 17:07:23.279115   55592 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
I0727 17:07:23.279378   55592 reconciler.go:271] "attacherDetacher.DetachVolume started: this volume is not safe to detach, but maxWaitForUnmountDuration expired, force detaching" duration="50ms" volume={AttachedVolume:{VolumeName:fake-plugin/volume-name VolumeSpec:0xc0001a8588 NodeName:fail-detach-node PluginIsAttachable:true DevicePath:/dev/vdb-test DeviceMountPath: PluginName:} MountedByNode:true DetachRequestedTime:2022-07-27 17:07:23.175371375 +0000 UTC m=+3.487241656}
    reconciler_test.go:1545: Check volume <fake-plugin/volume-name> is reported as attached to node <fail-detach-node>, got false, expected true
--- FAIL: Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce (1.11s)
```

/reopen

**Comment by BenTheElder** [comment] 2022-07-29 21:10
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111552/pull-kubernetes-unit/1553117127928451072
```
W0729 20:49:40.631626   55768 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0729 20:49:40.632129   55768 operation_generator.go:398] AttachVolume.Attach succeeded for volume "volume-name" (UniqueName: "fake-plugin/volume-name") from node "fail-detach-node" 
I0729 20:49:40.632349   55768 reconciler.go:343] "attacherDetacher.AttachVolume started" volume={VolumeToAttach:{MultiAttachErrorReported:false VolumeName:fake-plugin/volume-name VolumeSpec:0xc0000131d0 NodeName:fail-detach-node ScheduledPods:[&Pod{ObjectMeta:{pod-uid1  pod-uid1  pod-uid1  0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:PodSpec{Volumes:[]Volume{},Containers:[]Container{},RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},SetHostnameAsFQDN:nil,OS:nil,},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},},}]}}
E0729 20:49:41.687894   55768 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0729 20:49:41.699051   55768 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0729 20:49:41.709573   55768 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0729 20:49:41.719973   55768 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
E0729 20:49:41.730378   55768 reconciler.go:219] failed to get health of node fail-detach-node: node "fail-detach-node" not found
    reconciler_test.go:1545: Check volume <fake-plugin/volume-name> is reported as attached to node <fail-detach-node>, got false, expected true
--- FAIL: Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce (1.10s)
```
    
/remove-lifecycle stale

**Comment by BenTheElder** [comment] 2022-07-29 21:11
> this is the top unit test flake according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

still the case

**Comment by brianpursley** [comment] 2022-07-30 14:39
How about adding some logging to help troubleshoot this?

I looked at it a little, but it is hard to tell which part of the test is failing.

PR https://github.com/kubernetes/kubernetes/pull/111577

**Comment by alculquicondor** [comment] 2022-09-09 13:35
This is still happening

**Comment by sunnylovestiramisu** [comment] 2022-11-16 17:19
From the logs, in the OneVolumeDetachFailNodeWithReadWriteOnce test, ```verifyVolumeAttachedToNode``` succeeded, but the next verification ```verifyVolumeReportedAsAttachedToNode``` failed.

In verifyVolumeAttachedToNode, the attachState is from calling ```asw.GetAttachState(volumeName, nodeName)``` and within asw, it calls ```asw.attachedVolumes[volumeName]```. 

In verifyVolumeReportedAsAttachedToNode, the volumes are obtained from calling ```asw.GetVolumesToReportAttached()```, it seems that the node is not in asw.nodesToUpdateStatusFor at this step.

**Comment by sunnylovestiramisu** [comment] 2022-11-19 02:46
Tried to run stress test as well but still cannot reproduce.

**Command**:
```
stress ./reconciler.test -test.run=Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce -test.cpu=5
```

**Result**:
```
5s: 16 runs so far, 0 failures
...
20m20s: 6651 runs so far, 0 failures
20m25s: 6675 runs so far, 0 failures
```

Also tried running n process in parallel.
**Command**:

```
stress -p 4 ./reconciler.test -test.run=Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce -test.cpu=5
```

**Result**:
```
...
26m55s: 2216 runs so far, 0 failures
27m0s: 2221 runs so far, 0 failures
```

**Comment by kerthcet** [comment] 2022-12-15 02:39
It seems like it happens more frequently. But I may have no time to dig into the cause. Let's see.

**Comment by kerthcet** [comment] 2022-12-15 02:44
cc @jingxu97 as the test author.

**Comment by aojea** [comment] 2023-03-09 11:06
The problem is that this test has a lot of dependency on the sleeps that are hardcoded with a very narrow scope, but our CI seems to be able to stress it much more. As soon as you change one of the sleep duration a minimum it starts to flake

https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L641

https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L650-L658

https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L662-L666

https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L670-L673

https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L683-L684


The test can not make an assumption that timing is perfect, even more in the sub second range

@msau42 can someone in sig-storage review this test and make it less dependant on those tight sleeps?

**Comment by pacoxu** [comment] 2023-03-14 03:54
According to most failures, it failed at Line 660.
https://github.com/kubernetes/kubernetes/blob/69b9f9b1f0293fd56917d310b79b2e4be3672d9c/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go#L650-L660

I wondered if the ` time.Sleep(100 * time.Millisecond) ` is too small when stress is huge. A simple fix would be just adding some extra time here.

**Comment by msau42** [comment] 2023-03-14 04:26
I agree this test case is too brittle due to its specific timing dependencies. To fix this, I suggest reworking the test case to:

1) Add retry with timeout to wait for final conditions
2) Remove the intermediate timing-based state transition checks. Instead, we can keep track of state transitions in the Fakes and validate those stats.

@jingxu97 @gnufied wdyt?

**Comment by lauralorenz** [comment] 2023-03-28 18:10
Friendly ping from 1.27 CI Signal that this test is still a noisy flake on the master-blocking dashboard as CI Signal has flagged it in https://github.com/kubernetes/kubernetes/issues/116774 and https://github.com/kubernetes/kubernetes/issues/116955.

**Closed** 2023-04-12 01:19 UTC
Labels: priority/important-soon, sig/storage, kind/flake, triage/accepted
