### ISSUE TITLE
windows error message reports kubelet as uid -1

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#96171] opened 2020-11-03 17:36 UTC
**What happened**:
We Recently saw this on a broken windows cluster in a bug report in sig-windows slack: 

```
Log file created at: 2020/11/03 15:57:57
Running on machine: WIN-JG3L4V103D0
Binary: Built with gc go1.15 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1103 15:57:57.351178     724 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://172.25.21.247:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": Forbidden
E1103 15:57:57.605838     724 server.go:748] kubelet needs to run as uid `0`. It is being run as -1
E1103 15:57:57.614808     724 file_unsupported.go:28] Watching source file is unsupported in this build
E1103 15:57:57.614808     724 file.go:98] Unable to read config path "C:\\var\\lib\\kubelet\\etc\\kubernetes\\manifests": path does not exist, ignoring
E1103 15:57:57.620810     724 reflector.go:127] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://172.25.21.247:6443/api/v1/services?limit=500&resourceVersion=0": 
```
**What you expected to happen**:

The kubelet log would clearly say "kubelet is not running"

**How to reproduce it (as minimally and precisely as possible)**:

Try to start the kubelet server without the kubelet process properly running on windows

**Anything else we need to know?**:

**Environment**: windows
- Kubernetes version (use `kubectl version`): master

**Comment by jsturtevant** [comment] 2021-01-22 00:29
I believe this is a essentially a duplicate of #96512 which has an active PR that resolves the issue

/close

**Closed** 2021-01-22 00:29 UTC
Labels: kind/bug, needs-triage, sig/node, sig/windows
