### ISSUE TITLE
ReplicaSet is missing an owner ref of the Deployment that created it

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#33845] opened 2016-09-30 16:53 UTC
In 1.4.x

Create a deployment and wait for an RS to be created.  Check the yaml/json output of the RS

Expected: there should be _something_ on the RS that says what Deployment created it.  The proposal is related to https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/garbage-collection.md

Actual: nothing points back to the deployment.

This is a big problem for clients that want to make associations back to the Deployment that created an RS.  Currently we have to get the entire list of deployments and compare the label selectors.  Generally you need to know what deployment created an RS so that you can point the user to editing the Deployment and not the RS directly.

**Comment by jwforres** [comment] 2016-09-30 16:53
cc @mfojtik @pmorie

**Comment by jwforres** [comment] 2016-09-30 16:53
cc @spadgett

**Comment by pmorie** [comment] 2016-09-30 16:53
@kubernetes/sig-apps

**Comment by pmorie** [comment] 2016-09-30 16:58
This seems like a bug to me -- I would love for this to be fixed in a 1.4 minor version.

**Comment by krmayankk** [comment] 2016-10-01 01:01
I can work on this,  can someone assign it to me

**Comment by kargakis** [comment] 2016-10-02 21:18
@kubernetes/deployment

**Comment by kargakis** [comment] 2016-10-06 14:41
@krmayankk just saw your comment, let me know when you have a PR ready for review.

**Comment by pwittrock** [comment] 2016-10-13 21:52
cc @caesarxuchao

**Comment by caesarxuchao** [comment] 2016-10-13 22:32
We currently only automatically creates the ownerRef for pods pointing to the RC or RS that creates it, as stated in the [doc](http://kubernetes.io/docs/user-guide/garbage-collection/). I want to support deployment as well, but did not have time to. 

@krmayankk thanks for taking this, I can help with the review. You could take a look at my previous [PR](https://github.com/kubernetes/kubernetes/pull/27600/files) for RC as a reference.

**Comment by caesarxuchao** [comment] 2016-10-13 22:35
To be compatible with old clients, we also need to set the default garbage collection policy for deployments, something like this: https://github.com/kubernetes/kubernetes/pull/30838/files#diff-4098c5ce0a712fe113b57ca60b0fbb5aR48.

**Comment by krmayankk** [comment] 2016-10-17 06:49
@kargakis started working on this. Still new to this community. I had raised this earlier, but how does one get an issue assigned, since before its assigned its unclear who is working on it. @caesarxuchao  thanks for the pointers. I  have started looking into your PR for RC as reference. One question , what is the controller-ref-manager and do you think adding a controller ref for ReplicaSets/Replication Controllers, requires any changes in the c ontroller ref manager ?

**Comment by krmayankk** [comment] 2016-10-17 07:00
@caesarxuchao it seems we would also need a ReplicaSetControllerRefManager, is this design explained somewhere in the proposals. Was there a possibility of a more generic design which would do this based on controllerRef and not need specific refManagers ?

**Comment by kargakis** [comment] 2016-10-17 09:43
@krmayankk the issue is already assigned to you. @caesarxuchao, me, and anyone from @kubernetes/deployment can help with reviews.

**Comment by krmayankk** [comment] 2016-10-24 19:44
@kargakis The PR for the initial part would be ready by tomorrow. I am still new to this area, and have reached out to @janetkuo on slack for help. I wanted to basically confirm, where would the equivalent of Classify() from @caesarxuchao PR should be called from , in the deployment controller code to collect all the replica sets and fix their references. I am basically creating a  ReplicaSetControllerRefManager, similar to PodControllerRefManager to do that in controller_ref_manager. Any pointers on where Classify should be called, will help a lot. After i have figured that , other parts of the discussion i would need help is basically figuring out how to test it all.

**Comment by caesarxuchao** [comment] 2016-10-24 21:44
We discussed on slack, ReplicaSetControllerRefManager should be called at Deployment and RS informers' ResourceEventHandlerFuncs. Also, if there is a periodic resync func, ReplicaSetControllerRefManager should be called there, too.

**Comment by kargakis** [comment] 2016-10-25 09:34
@krmayankk it seems that the PodControllerRefManager does the whole Classify/Adopt dance [while the replica set is synced, just after listing all of its pods](https://github.com/kubernetes/kubernetes/blob/cfbb0eb2ff680173eeaa0ce91ab42f3c4f9bbc33/pkg/controller/replicaset/replica_set.go#L579). The respective place to do this in the deployment controller is not clear enough atm because we list all over the place. I am going to open a PR that consolidates all lists into a single starting place and there you can build the ReplicaSetControllerRefManager (ideally the updates on the replica sets should be atomically applied as we sync them and apply the pod-template-hash label but since we are going to patch I think having it as a separate step after listing is fine.)

> we just checked the code, it seems the deployment manager doesn't do periodic resync

It does, and it's currently set to [30s](https://github.com/kubernetes/kubernetes/blob/cfbb0eb2ff680173eeaa0ce91ab42f3c4f9bbc33/pkg/controller/informers/extensions.go#L104).

**Comment by kargakis** [comment] 2016-10-25 13:46
Ok, I think the change needed to consolidate all lists into one place will be non-trivial and I don't want to block this issue. For now I think we will be fine with a separate list [before](https://github.com/kubernetes/kubernetes/blob/2729f282f38b5cac580c42b95aace87fc0fcb355/pkg/controller/deployment/deployment_controller.go#L357) any processing of the deployment happens where you should: 1) list all replica sets in the namespace and 2) classify them as owned and finally adopt (or release) them, [similar to how the rs controller marks pods](https://github.com/kubernetes/kubernetes/blob/2729f282f38b5cac580c42b95aace87fc0fcb355/pkg/controller/replicaset/replica_set.go#L571-L607).

**Comment by caesarxuchao** [comment] 2016-10-25 18:16
> It does, and it's currently set to 30s.

Thanks. I thought the informer would use the `FullDeploymentResyncPeriod` defined in the deployment controller package, so I concluded it's not resyncing because `FullDeploymentResyncPeriod` was not used anywhere.

**Comment by sputnick** [comment] 2016-11-02 19:32
I agree with the original poster that this change is necessary. This is causing myself problems to identify the real controller for pods. A side effect of this is that pod.metadata.ownerReferences doesn't actually reference the Deployment either and says the ReplicaSet is the "top controller" with the field "controller=true". When this is fixed will there be a need at all to reference the ReplicaSet in the Pod?

Anyway if you are dealing with this issue today you can use black magic i.e. looking for combinations of "ownerReferences", "pod-template-hash", "generateName" and the annotation [kubernetes.io/created-by] from Pods to guesstimate the top controller. You will be right ~99.99% of the time in my experience - the one use case where my search algorithm failed it actually lead me to realise that the original Deployment had been deleted and then the actual top controller had become the ReplicaSet (which now could scale the pods). For now the only thing I can do is to mark the "App" as "missing a controller". Looking forward to this fix!

**Comment by kargakis** [comment] 2016-11-02 20:06
> When this is fixed will there be a need at all to reference the ReplicaSet in the Pod?

I think pods will always reference replica sets and replica sets will reference deployments.

**Comment by sputnick** [comment] 2016-11-02 20:11
Ok @kargakis but what will ownerReferences look like?

**Comment by kargakis** [comment] 2016-11-03 09:21
@sputnick here is the design doc that explains what "controller=true" means for an owner reference:
https://github.com/kubernetes/kubernetes/blob/f4c2a05eeaad78e5c6c8698a1e15a0c1032ccb25/docs/proposals/controller-ref.md#api-and-semantic-changes

**Comment by sputnick** [comment] 2016-11-03 18:56
@kargakis thanks I've seen that. It just doesn't help at all with ReplicaSets because you also have to jump over the ReplicaSet to get to the real controller. I'm just saying I feel that we should have the real controller in there. Real as in it can scale the pods without it rolling back like it does when you scale with a ReplicaSet that was created by a Deployment.

**Comment by kargakis** [comment] 2016-11-03 20:49
Not sure what you mean when you say "real controller". Replica sets manage pods and deployments manage replica sets. I think the abstraction is clear enough for the owner references to make sense as we set them already (for pods) and will set in the near future (for replica sets).

**Comment by sputnick** [comment] 2016-11-03 21:06
I'm referring to that you cannot scale the pod replicas with the owner controller=true if that controller is a ReplicaSet made by a Deployment. That is inconsistent with every other controller like RC, Job etc. I don't mind the ReplicaSet being in there but as a tool maker working with K8s api to make a tool/platform for applications I'm not a fan of making special cases just for ReplicaSets.

In other words kubectl and all clients will have to introduce a special case to scale pods that are only marked with their ReplicaSet as owner if that Pod was indirectly created by a Deployment. i.e.
kubectl scale --replicas=5 rs theReplicaSet 
Returns true! Everything worked...and then the Deployment rolls the pods back to it's definition of the number of pods.

If the owner controller can also scale the pods even though it is and indirect controller (created by something similar to or by a Deployment) then I would case less because I don't have to make special cases and traverse a controller tree with perhaps unknown types (only true for Deployment+RS today...)

**Comment by kargakis** [comment] 2016-11-03 21:38
kubectl doesn't special-case replica sets owned by deployments, it treats all of them equally. The behavior of a deployment rolling back the pods scaled by a replica set it owns is correct. The pod is still owned by the replica set, the deployment owns the replica set. Scaling a replica set owned by a deployment is a user error. Users shouldn't touch replica sets or setup autoscalers for replica sets owned by deployments, that's why we have deployments in the first place.

Now I see why you would want a deployment reference in the pod but I am not sure we have thought that out yet. Why are you trying to identify owning controllers for pods instead of looking at the controller in your system first and them move down to pods?

**Comment by smarterclayton** [comment] 2016-11-03 21:44
At large scale propagating controller references down a chain becomes very
expensive - we probably can't do it for that reason alone.

On Nov 3, 2016, at 5:38 PM, Michail Kargakis <notifications@github.com>
wrote:

kubectl doesn't special-case replica sets owned by deployments, it treats
all of them equally. The behavior of a deployment rolling back the pods
scaled by a replica set it owns is correct. The pod is still owned by the
replica set, the deployment owns the replica set. Scaling a replica set
owned by a deployment is a user error. Users shouldn't touch replica sets
or setup autoscalers for replica sets owned by deployments, that's why we
have deployments in the first place.

Now I see why you would want a deployment reference in the pod but I am not
sure we have thought that out yet. Why are you trying to identify owning
controllers for pods instead of looking at the controller in your system
first and them move down to pods?

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/33845#issuecomment-258281968>,
or mute the thread

**Comment by sputnick** [comment] 2016-11-03 21:49
@kargakis that's a good question, I'm glad you asked :)

The short answer is to group k8s resources as Applications. The shortest answer is that going bottom up (pods to controllers) is marginally better than going from controller to Pods with the current situation (related to this issue but there are also other things to consider).

The slightly longer analysis:

Application discovery challenges and decisions:
------------------------------------------------
We chose "bottom up" discovery and will solve the cons/edge cases specifically. Our application discovery only relies on core k8s objects
information and doesn't handle any third party methods of app discovery yet. That could be added later as a plugin. This method works
well for Helm as well as most recommended application packaging methods on the web.

**Bottom up discovery - From Pod to Controllers :**

Pros:
- Using information about the Pod we can deduce which is the top controller that can scale the Pod and how that selects the Pod.
- From the Pod we can also figure out a common App label.
- When using this method we can find problems with a Pod like a missing controller (cascading deletes may have failed).
- We don't have to know every type of Controller beforehand for this to work.

Cons:
- Controllers with Zero pods won't show up in our list. They likely don't consume any resources but you would still like to see them.
- The way K8s now identifies top controllers in not simple and involves our code making assumptions based on research and experience.
There are issues related to this being worked on.

**Top down discovery - From Controllers to Pods:**

Pros:
- If we declare all types of Controllers and iterate through them we can find all pods related to them.
- From the controller we can figure out a common app label

Cons:
- We will get many false positives mainly when we have indirectly created Pods from Deployments through ReplicaSets. We have to analyze the Pod details to figure out which controller to keep.
- We won't find orphan pods and therefor we can't know if those pods have issues
- We have to hard code every controller type in our code (this is the biggest negative...)

In addition to this we also find Services which can only be found by examining Endpoints, targetRef and that again points to Pods. So to be sure we find all services we still need at least the UID of the pods involved...

**Comment by sputnick** [comment] 2016-11-03 21:51
@smarterclayton exactly that's why I'm caching API stuff using MongoDB and watching the APIs. This also allows me not to care about the types of controllers around...except because of this issue I have to care specifically about Deployments and ReplicaSets...

**Comment by kargakis** [comment] 2016-11-03 22:37
Ok, so your real problem is that the Deployment->RS->Pod relationship is unlike any other relationship in Kube. You are going to have the same problem with CronJobs. Also you definitely cannot make this assumption once you start handling third party resources. You will need to traverse all objects up to the top controller. Propagating owner references is indeed going to be very expensive for us to handle.

**Comment by sputnick** [comment] 2016-11-03 22:46
Yeah @kargakis that's also why I'm saying going from pod and up is better (for now) because then you don't have to know all controller types - the connection from RS to Top Controller is the missing piece. With a middleware layer like Mongodb it becomes much less expensive figure this out but having the "real top controller" also as a controller in ownerReferences would solve this for all types or alternatively mention the creator of the ReplicaSet in the ownerReference for the ReplicaSet on the Pod - that is likely not any more expensive than just adding the ReplicaSet as the owner today?

**Comment by sputnick** [comment] 2016-11-03 22:51
Just to add to the confusion for people reading this thread here are some of the other "standard" ways k8s exposes these types of relations (that I have found):

Annotation: "kubernetes.io/created-by" - on 99% of pods with the exception of pods that are created directly.
Label: "controller-uid" e.g. on Jobs which incidentally also has a "job-name" label

Without the actual creation "tree" and ownerreferences you can resort to using "generateName" and "pod-template-hash" to guesstimate relationships...

**Closed** 2016-12-23 02:50 UTC
Labels: area/workload-api/deployment, priority/important-soon, team/ux (deprecated - do not use)
