### ISSUE TITLE
Strange slow controller-manager startup

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18343] opened 2015-12-08 10:52 UTC
Last cluster I was spinning up took way to long:
- Kubelets/Master machine was created around 9:44 GMT
- Kubelet on Master machine noticed all manifests and started to create Pod for controller-manager (still 9:44)
- Docker claims that the controller-manager was started around 9:48 GMT for the first time.
Nothing happened in those 4 minutes, as controller-manager wasn't up, so no Kubelet was receiving its CIDR and everything just waited for something to happen.

Does someone have any idea why this may be the case? 

cc @wojtek-t  @fgrzadkowski @kubernetes/goog-node

**Comment by dchen1107** [comment] 2015-12-08 18:33
@gmarek Please run the following commands and copy & paste the output here:

* docker ps -a
* kubectl describe pods <controller-manager-pod>  or kubectl get pods -o yaml <controller-manager-pod>
* kubectl logs <controller-manager-pod>

Also why do you think it is node team's issue here since controller-manager container is running already?

**Comment by dchen1107** [comment] 2015-12-08 18:33
cc/ @davidopp @mikedanese

**Comment by gmarek** [comment] 2015-12-08 18:43
@dchen1107  - because it's not running. It was 4 minutes after the start of the Kubelet and the time when Kubelet noticed manifest for controller manager and the time when it was started, according to the docker inspect (which is consistent with the timestamp of the first log line in controller manager logs).

I don't have this cluster running - I have only Kubelet logs, if you're interested. @fgrzadkowski was looking at this with me, so he may correct me if I remember something wrongly.

I think it's the nodes team issue, because the problem is between noticing manifest file and starting a container. No other component takes part in this.

**Comment by dchen1107** [comment] 2015-12-08 19:17
>Docker claims that the controller-manager was started around 9:48 GMT for the first time. Nothing happened in those 4 minutes, as controller-manager wasn't up, so no Kubelet was receiving its CIDR and everything just waited for something to happen.

Can you run:

* docker ps -a and find controller-manager container id
* docker inspect <controller-manager container id>
* docker logs <controller-manager container id>

**Comment by dchen1107** [comment] 2015-12-08 19:19
@gmarek can you send me kubelet cmdline flag on your master node too?

**Comment by gmarek** [comment] 2015-12-08 19:21
Sorry - I can't run anything on this cluster, as it's long down. It was an ordinary e2e cluster with register master node flipped to 'true'.

**Comment by dchen1107** [comment] 2015-12-08 19:23
Ok, I guess I know what is going on, but need to verify it.

**Comment by davidopp** [comment] 2015-12-15 06:13
@dchen1107 So, what *is* going on? :)

**Comment by dchen1107** [comment] 2016-01-29 06:21
Close the issue since I didn't verify my theory, and the issue is obsolete.

**Closed by dchen1107** 2016-01-29 06:21 UTC
Labels: priority/P1, team/control-plane, team/node
