### ISSUE TITLE
e2e flaky: kubernetes-e2e-gke-release-1.2 failed to create cluster sometimes

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#23544] opened 2016-03-28 18:07 UTC
kubernetes-e2e-gke-release-1.2/596 is red due to 

```
10:50:05 ... in gke:detect-nodes()
10:50:05 ... in gke:detect-node-names()
10:50:05 ... in gke:detect-project()
10:50:05 ... in gke:detect-node-instance-group()
10:50:06 NODE_NAMES=gke-jenkins-e2e-5a07ca2f-node-k223 gke-jenkins-e2e-5a07ca2f-node-kgeo gke-jenkins-e2e-5a07ca2f-node-s6o0
10:50:43 Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gke-1-2/global/firewalls/jenkins-e2e-http-alt].
10:50:44 NAME                 NETWORK     SRC_RANGES RULES           SRC_TAGS TARGET_TAGS
10:50:44 jenkins-e2e-http-alt jenkins-e2e 0.0.0.0/0  tcp:80,tcp:8080          gke-jenkins-e2e-5a07ca2f-node,k8s-jenkins-e2e-node
10:50:44 ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
10:50:44  - The resource 'projects/k8s-jkns-e2e-gke-1-2/global/firewalls/jenkins-e2e-nodeports' already exists
10:50:44 2016/03/28 10:50:44 e2e.go:200: Error running up: exit status 1
10:50:44 2016/03/28 10:50:44 e2e.go:196: Step 'up' finished in 3m55.345493409s
10:50:44 
2016/03/28 10:50:44 e2e.go:110: Error starting e2e cluster. Aborting.
```

I only observed such failure with gke, not gce cluster.

**Comment by dchen1107** [comment] 2016-03-28 18:08
cc/ @kubernetes/goog-gke

**Comment by roberthbailey** [comment] 2016-03-28 18:17
This is part of the e2e test setup (not GKE itself) in util.sh: https://github.com/kubernetes/kubernetes/blob/master/cluster/gke/util.sh#L187-L192

Since it says that the firewall already exists, it looks like a previous test run didn't clean up correctly.

**Comment by roberthbailey** [comment] 2016-03-28 18:22
In the previous run (which was a green dot):

```
10:33:45 2016/03/28 10:33:45 e2e.go:194: Running: teardown
10:33:45 ... in gke:prepare-e2e()
10:33:45 ... in gke:test-teardown()
10:33:45 ... in gke:detect-project()
10:34:12 Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gke-1-2/global/firewalls/jenkins-e2e-http-alt].
10:34:12 ERROR: gcloud crashed (CannotConnectToMetadataServerException): <urlopen error [Errno 111] Connection refused>
10:34:12 
10:34:12 If you would like to report this issue, please run the following command:
10:34:12   gcloud feedback
10:34:12 Bringing down cluster using provider: gke
```

So it looks like gcloud crashed while tearing down that firewall in the previous run, which is preventing new runs from starting up.

**Comment by roberthbailey** [comment] 2016-03-28 18:24
@dchen1107 did you manually clean up the firewall rule? It looks like the current run didn't hit this issue.

**Comment by bprashanth** [comment] 2016-03-28 18:40
That gcloud crash has occurred 4 times in the last 12 hours in the Ingress suite, if we just updated gcloud on our builders, we should probably open an internal bug. I think it's flake in contacting the metadata server that previous didn't cause the crash but is now.

**Comment by dchen1107** [comment] 2016-03-28 18:53
@roberthbailey I didn't do any manual steps here. I believe the next run was trying to do tear down first and succeed.

**Comment by roberthbailey** [comment] 2016-03-28 20:10
@bprashanth — @jlowdermilk is already looking into it. 

@dchen1107 — that's good, it'd be nicer if it did it correctly on the next run, but doing it 2 runs later isn't terrible. 

On the one hand, we could pretty easily fix this with some retries in firewall creation, but that would mask regressions in gcloud like we found here.

**Comment by dchen1107** [comment] 2016-03-28 20:22
@roberthbailey Agreed. I filed the issue to make sure there is no regression in our stack, especially with 1.2 gke.

**Comment by jlowdermilk** [comment] 2016-03-29 18:32
I rolled back the gcloud version on pr builders and disabled the gcloud update job. We'll see if that improves situation. In the meantime I'm trying to repro the failure.

**Comment by jlowdermilk** [comment] 2016-03-30 16:18
This turns out to be caused by metadataserver flaking on the jenkins master. We have so many processes hitting metadataserver that it occassionally errors, and gcloud doesn't retry requests. I added retry upstream.

**Comment by bgrant0607** [comment] 2016-03-30 20:06
cc @ncdc

**Comment by jlowdermilk** [comment] 2016-03-30 21:08
@k8s-oncall, how much pain is this causing? I can update gcloud on jenkins-master to a ci build to pick up retry, but that carries some risk.

**Comment by a-robinson** [comment] 2016-03-30 21:27
It's been pretty bad today... I'd recommend trying out the CI build. That'll also get us much faster feedback on whether the changes you made help or if we need to do something else.

**Comment by a-robinson** [comment] 2016-03-30 21:46
The metadata server's flakiness is also causing problems for the kubelet pulling images...

From https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/749/
```
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
13:19:06            v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable)
13:19:06       not to have occurred
```

**Comment by a-robinson** [comment] 2016-03-30 22:30
It's still causing pain all over the place - I'm now very in favor of trying out the CI build

**Comment by jlowdermilk** [comment] 2016-03-30 22:31
Working on it. I want to make sure the script doesn't break the world before I run it on jenkins master/slave vms.

**Comment by jlowdermilk** [comment] 2016-03-31 00:11
Jenkins master is now running a ci gcloud build. I looked at a couple jobs and it seems to be running correctly. Let me know if you see issues and/or if flake rate from gsutil/gcloud errors changes.

**Comment by a-robinson** [comment] 2016-03-31 05:57
I think this may have caused some problems:

* The timing lines up reasonably well with #23670, although I'm not sure why a new gcloud would cause that.

* There's a gsutil crash in kubernetes-e2e-gce-reboot, although that's only happened in [the most recent run](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-reboot/2002/):

```
22:38:22 ++ gsutil cat gs://kubernetes-release/ci/latest.txt
22:38:22 Traceback (most recent call last):
22:38:22   File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 12, in <module>
22:38:22     import bootstrapping
22:38:22 ImportError: No module named bootstrapping
```

* [e2e-gce-release hit a gcloud crash during the teardown step](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-release-1.2/936/):

```
All components are up to date.
Project: k8s-jkns-e2e-gce-1-2
Zone: us-central1-f
ERROR: gcloud crashed (error): [Errno 111] Connection refused

If you would like to report this issue, please run the following command:
  gcloud feedback
INSTANCE_GROUPS=
NODE_NAMES=
Bringing down cluster
ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
 - The instance_template resource 'jenkins-e2e-minion-template' is already being used by 'jenkins-e2e-minion-group'
```

**Comment by a-robinson** [comment] 2016-03-31 06:10
I've switched the jenkins master back to the released version of gcloud, hopefully in a way that won't break things even further.

**Comment by jlowdermilk** [comment] 2016-04-08 20:26
Closing this as dupe of #23545.

**Closed by jlowdermilk** 2016-04-08 20:26 UTC
Labels: kind/flake, priority/P1, team/gke
