### ISSUE TITLE
Liveness command probe does not honor timeoutSeconds

### ISSUE THREAD

**Issue by h0tbird** [kubernetes/kubernetes#43811] opened 2017-03-29 14:49 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

GKE

**What happened**:

Liveness command probe does not honor `timeoutSeconds`.

**What you expected to happen**:

I expect the liveness command probe to enter failure state after `timeoutSeconds` seconds.

**How to reproduce it**:

*liveness.yaml*
```
apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - name: liveness
    command: ["/bin/sh", "-c", "while true; do date; sleep 1; done"]
    image: alpine
    livenessProbe:
      exec:
        command: ["sleep", "20"]
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
```
```
kubectl create -f liveness.yaml
```

**Anything else we need to know**:

The pod above lives forever but should be terminated.

**Comment by iam404** [comment] 2017-05-22 04:41
Has similar issue. Liveness probe health check fail but still pod was not restarted.

**Comment by andreychernih** [comment] 2017-06-14 18:10
Same here, I have a liveness probe with `timeoutSeconds: 1` and it looks like this timeout is not respected - I see a healthcheck process started several minutes ago and kubernetes does not restart the pod.

**Comment by xiangpengzhao** [comment] 2017-06-16 02:29
A similar issue https://github.com/kubernetes/kubernetes/issues/26895 which is about `readinessProbe`

/sig node

**Comment by rhcarvalho** [comment] 2018-01-15 13:50
This is a duplicate of #26895.

**Closed** 2018-03-16 14:59 UTC
Labels: area/platform/gke, lifecycle/rotten, sig/node, team/gke
