### ISSUE TITLE
e2e test failing on ResourceUsage should not exceed expected amount.

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#12429] opened 2015-08-08 04:44 UTC
Since 4:25PM the e2e test `ResourceUsage should not exceed expected amount` has been failing.
Looking at the last batch of merged PRs I can't tell if any of them are responsible, either individually or in combination. Please can the PR authors @eparis @BenTheElder @nikhiljindal @gmarek @feihujiang @yifan-gu have a think about whether their change could have caused:
```
ResourceUsage should not exceed expected amount.

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:131
Expected
    <map[string]e2e.resourceUsagePerContainer | len:3>: {
        "e2e-gce-minion-jt3o": {
            "/": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.32753680271174745,
                MemoryUsageInBytes: 5536577126,
                MemoryWorkingSetInBytes: 1995254169,
                CPUInterval: 0,
            },
            "/docker-daemon": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.05330590708577182,
                MemoryUsageInBytes: 3765198848,
                MemoryWorkingSetInBytes: 674401484,
                CPUInterval: 0,
            },
            "/kubelet": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.04093180701209144,
                MemoryUsageInBytes: 94748672,
                MemoryWorkingSetInBytes: 94444748,
                CPUInterval: 0,
            },
            "/kube-proxy": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.015246457387254289,
                MemoryUsageInBytes: 5681152,
                MemoryWorkingSetInBytes: 5656576,
                CPUInterval: 0,
            },
            "/system": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.004761631665055137,
                MemoryUsageInBytes: 42254336,
                MemoryWorkingSetInBytes: 25874432,
                CPUInterval: 0,
            },
        },
        "e2e-gce-minion-yb6a": {
            "/system": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.00338632073811133,
                MemoryUsageInBytes: 43447910,
                MemoryWorkingSetInBytes: 26343014,
                CPUInterval: 0,
            },
            "/": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.3377336907593952,
                MemoryUsageInBytes: 2699154227,
                MemoryWorkingSetInBytes: 936918220,
                CPUInterval: 0,
            },
            "/docker-daemon": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.06698396036521867,
                MemoryUsageInBytes: 1778617548,
                MemoryWorkingSetInBytes: 339885260,
                CPUInterval: 0,
            },
            "/kubelet": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.0644396340620269,
                MemoryUsageInBytes: 99394355,
                MemoryWorkingSetInBytes: 98837299,
                CPUInterval: 0,
            },
            "/kube-proxy": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.010085711242831061,
                MemoryUsageInBytes: 4357324,
                MemoryWorkingSetInBytes: 4330291,
                CPUInterval: 0,
            },
        },
        "e2e-gce-minion-itlb": {
            "/": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.45461458647632885,
                MemoryUsageInBytes: 4603497676,
                MemoryWorkingSetInBytes: 1894986547,
                CPUInterval: 0,
            },
            "/docker-daemon": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.059021967282394824,
                MemoryUsageInBytes: 2742996172,
                MemoryWorkingSetInBytes: 488832204,
                CPUInterval: 0,
            },
            "/kubelet": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.06799305314744905,
                MemoryUsageInBytes: 104071168,
                MemoryWorkingSetInBytes: 103599308,
                CPUInterval: 0,
            },
            "/kube-proxy": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.012785393033208461,
                MemoryUsageInBytes: 5046272,
                MemoryWorkingSetInBytes: 5021696,
                CPUInterval: 0,
            },
            "/system": {
                Name: "",
                Timestamp: {sec: 0, nsec: 0, loc: nil},
                CPUUsageInCores: 0.004112326988701547,
                MemoryUsageInBytes: 67950182,
                MemoryWorkingSetInBytes: 51807846,
                CPUInterval: 0,
            },
        },
    }
to be empty
```
@ixdy @quinton-hoole @dchen1107

**Comment by BenTheElder** [comment] 2015-08-08 04:56
Looking. I don't _think_ anything I did would have.

**Comment by satnam6502** [comment] 2015-08-08 05:39
So I suspect it might be #11374 
@gmarek please can you take a look?
I will have a think about reverting... not sure if that is the best thing to do.

**Comment by satnam6502** [comment] 2015-08-08 05:43
I reverted... let's see what happens.

**Comment by gmarek** [comment] 2015-08-08 09:20
I'm 99% sure it's just tuning. I put there numbers that were good (+ some padding) on my e2e cluster. We just need to change constants.

The idea behind this test, after it's tuned to our testing environment, is to run in on our soak cluster, to make sure we don't bleed resources.

**Comment by gmarek** [comment] 2015-08-08 09:41
`/` probably should be removed all together - it makes no sense:/

FWICT we need to increase CPU:
* `/docker-daemon` to 0.07
* `/kubelet` seems OK
* `/kube-proxy` seems OK
* `/system` seems OK

MemoryUsageInBytes:
* `/docker-daemon` to 4500000000
* `/kubelet` to 150000000
* `/kube-proxy` seems OK
* `/system` to 100000000

MemoryWorkingSetInBytes:
* `/docker-daemon` seems OK 
* `/kubelet` seems OK
* `/kube-proxy` seems OK
* `/system` seems 75000000

It'd be also interesting to add fluentD container to the test, but it can wait.
I'll write a PR with corrected constraints.

**Comment by gmarek** [comment] 2015-08-08 09:48
I'll do this on Monday:/

**Comment by satnam6502** [comment] 2015-08-08 13:47
Indeed e2e turned green after reverting #11374

**Comment by satnam6502** [comment] 2015-08-08 13:48
@gmarek : thank you. Sorry if I should not have merged this -- maybe you still needed some time to work out some constants? I'll leave this issue open until the test can be merged with e2e green afterwards.

**Comment by satnam6502** [comment] 2015-08-08 13:52
@gmarek going forward might this be a worrying source of future instability in our e2e tests as our system evolves?

**Comment by gmarek** [comment] 2015-08-08 14:30
It's good that you merged it, as otherwise I wouldn't know what constants to put there.

This is supposed to be regression test. Yes, it'll probably cause test failures, but only when we make our system less efficient. Node that this test is supposed to be run on an empty cluster (non-parallel etc.).

**Comment by timothysc** [comment] 2015-08-10 17:01
cc @rrati jayunit100

**Comment by quinton-hoole** [comment] 2015-09-10 22:01
This test is still flaky.  Re-opening.

ResourceUsage should not exceed expected amount. (Failed 8 times in the last 30 runs. Stability: 73 %)

e.g. job/kubernetes-e2e-gce-flaky/4897/testReport/

**Comment by gmarek** [comment] 2015-09-11 14:36
It looks like a regression to me. Kubelet started using more CPU than before. I can readjust constraints, but maybe we should try to understand why that's the case.

cc @dchen1107 @yujuhong

**Comment by yujuhong** [comment] 2015-09-11 16:54
I will take a look, when jenkins is reachable..

**Comment by gmarek** [comment] 2015-09-11 16:58
I'm not sure if it'll show anything of interest. Kubelet was using 11% of CPU, which is noticeably higher value that when I was setting up limits. Do you know of any changes to Kubelet that might have caused this?

**Comment by lavalamp** [comment] 2015-12-08 01:33
@gmarek status?

**Comment by gmarek** [comment] 2015-12-08 10:57
It kind of hangs on #17774. I can deflake it easily by increasing limits/disabling memory checking if we're convinced it's not a regression.

**Comment by gmarek** [comment] 2015-12-08 11:16
I updated what I believe was within reason, but in the same time I found that docker-daemon started using way more CPU than before (previous limit was 0.08) and in the run
http://kubekins.dls.corp.google.com/view/Flaky/job/kubernetes-e2e-gce-flaky/8476/
we see:
```
 { "e2e-flaky-minion-huv7": { "/docker-daemon": { Name: "", Timestamp: {sec: 0, nsec: 0, loc: nil}, CPUUsageInCores: 0.5213071566184293, MemoryUsageInBytes: 1205100544, MemoryWorkingSetInBytes: 193668710, CPUInterval: 0, }
```

**Comment by gmarek** [comment] 2015-12-10 13:45
#18345 is merged. I'll wait a couple of days to check if it's stable.

**Comment by gmarek** [comment] 2015-12-11 08:23
Previous problems with Kubelet disappeared, we have a new one with Docker daemon, which started to use over 10% of CPU on average in five 15 sec. probes. 

Is this expected, or should we worry about it? @dchen1107 @yujuhong

**Comment by yujuhong** [comment] 2015-12-11 23:25
@gmarek, I think in general the test is more subject to fluctuations due to the shorter monitoring time. Since I am adding cpu usage limits in #18382, should we just consolidate the tests? My test doesn't set memory limit yet, but I think we can do that after we improve the memory usage metrics. Overall, consolidating the tests should save both us some time. What do you think?

**Comment by dchen1107** [comment] 2015-12-12 01:04
Agreed with @yujuhong above. Can we consolidate this one with resource_monitor tests?

**Comment by gmarek** [comment] 2016-01-08 08:45
If only I had time for this... For now I increased thresholds, but I do think those were genuine failures. I.e. I don't believe that 'occasional spikes' can happen in every single run.

**Comment by gmarek** [comment] 2016-01-22 12:41
I'm removing the test in question. @yujuhong can you please add a memory monitoring to yours? While sitting with an internal team using k8s I heard more complains about kubelet/docker daemon memory usage than CPU usage. I think we should monitor this as well. @dchen1107 @davidopp

**Comment by yujuhong** [comment] 2016-01-22 17:52
> I'm removing the test in question. @yujuhong can you please add a memory monitoring to yours? While sitting with an internal team using k8s I heard more complains about kubelet/docker daemon memory usage than CPU usage. I think we should monitor this as well. @dchen1107 @davidopp

We should definitely add monitoring of memory usage, but I think we should first get a usable number from cadvisor (perhaps RSS instead of the working set).

What cloud/OS is the internal team using and what version of kubernetes? If they observe abnormal memory usage, it could be caused by memory leakage in cadvisor (e.g., #19633). It has happened more than once in cadvisor.

**Closed** 2016-01-22 19:10 UTC
Labels: kind/flake, priority/P0, team/control-plane

**Comment by davidopp** [comment] 2016-01-22 19:12
@zmerlynn I'm OK with closing this but I'm going to file a replacement issue and assign to @yujuhong . This is an important thing to have coverage of.

**Comment by davidopp** [comment] 2016-01-22 19:13
(Oh sorry, it was marked as closed by @zmerlynn simply because he did the merge of @gmarek's PR. Anyway, filing issue now.)
