### ISSUE TITLE
Hash collision in GetPodTemplateSpecHash Function 

### ISSUE THREAD

**Issue by lth2015** [kubernetes/kubernetes#43449] opened 2017-03-21 11:48 UTC
Test Code:
```golang
package main

import (
        "encoding/json"
        // "k8s.io/kubernetes/pkg/api"
        "fmt"
        "k8s.io/kubernetes/pkg/apis/extensions"
        podutil "k8s.io/kubernetes/pkg/util/pod"
)

const (
        DeploymentNewStr = `{
    "kind": "Deployment",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "yce-test",
        "namespace": "yce",
        "selfLink": "/apis/extensions/v1beta1/namespaces/yce/deployments/yce-test",
        "uid": "757f39f0-c38d-11e6-977e-44a84240716a",
        "resourceVersion": "78916094",
        "generation": 81,
        "creationTimestamp": "2016-12-16T12:45:01Z",
        "labels": {
            "author": "admin",
            "name": "yce-test",
            "version": "alpha-test-2016-10-26"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "32",
            "image": "img.reg.3g:15000/yce-alpha:201703211640",
            "kubernetes.io/change-cause": "update to 201703211640",
            "userId": "1"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "author": "admin",
                "name": "yce-test",
                "version": "alpha-test-2016-10-26"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "author": "admin",
                    "name": "yce-test",
                    "version": "alpha-test-2016-10-26"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "yce-test",
                        "image": "img.reg.3g:15000/yce-alpha:201703211640",
                        "ports": [
                            {
                                "containerPort": 8080,
                                "protocol": "TCP"
                            }
                        ],
                        "env": [
                            {
                                "name": "DB_HOST",
                                "value": "mysql-test.yce:3306"
                            },
                            {
                                "name": "DB_USER",
                                "value": "root"
                            },
                            {
                                "name": "DB_PASS",
                                "value": "root"
                            },
                            {
                                "name": "DB_NAME",
                                "value": "yce"
                            },
                            {
                                "name": "REDIS_HOST",
                                "value": "redis-master.yce:6379"
                            },
                            {
                                "name": "QA",
                                "value": "QA"
                            },
                            {
                                "name": "SIAGENTHOST",
                                "value": "172.21.1.11"
                            },
                            {
                                "name": "SIAGENTPORT",
                                "value": "31080"
                            }
                        ],
                        "resources": {
                            "limits": {
                                "cpu": "2",
                                "memory": "4Gi"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "imagePullPolicy": "IfNotPresent"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {}
            }
        },
        "strategy": {
            "type": "RollingUpdate",
            "rollingUpdate": {
                "maxUnavailable": 2,
                "maxSurge": 2
            }
        }
    },
    "status": {
        "observedGeneration": 80,
        "replicas": 1,
        "updatedReplicas": 1,
        "availableReplicas": 1
    }
}`

        DeploymentOldStr = `{
  "status": {
    "availableReplicas": 1,
    "updatedReplicas": 1,
    "replicas": 1,
    "observedGeneration": 80
  },
  "spec": {
    "strategy": {
      "rollingUpdate": {
        "maxSurge": 2,
        "maxUnavailable": 2
      },
      "type": "RollingUpdate"
    },
    "template": {
      "spec": {
        "securityContext": {},
        "dnsPolicy": "ClusterFirst",
        "terminationGracePeriodSeconds": 30,
        "restartPolicy": "Always",
        "containers": [
          {
            "imagePullPolicy": "IfNotPresent",
            "terminationMessagePath": "/dev/termination-log",
            "resources": {
              "limits": {
                "memory": "4Gi",
                "cpu": "2"
              }
            },
            "env": [
              {
                "value": "mysql-test.yce:3306",
                "name": "DB_HOST"
              },
              {
                "value": "root",
                "name": "DB_USER"
              },
              {
                "value": "root",
                "name": "DB_PASS"
              },
              {
                "value": "yce",
                "name": "DB_NAME"
              },
              {
                "value": "redis-master.yce:6379",
                "name": "REDIS_HOST"
              },
              {
                "value": "QA",
                "name": "QA"
              },
              {
                "value": "172.21.1.11",
                "name": "SIAGENTHOST"
              },
              {
                "value": "31080",
                "name": "SIAGENTPORT"
              }
            ],
            "ports": [
              {
                "protocol": "TCP",
                "containerPort": 8080
              }
            ],
            "image": "img.reg.3g:15000/yce-alpha:201703151133",
            "name": "yce-test"
          }
        ]
      },
      "metadata": {
        "labels": {
          "version": "alpha-test-2016-10-26",
          "name": "yce-test",
          "author": "admin"
        },
        "creationTimestamp": null
      }
    },
    "selector": {
      "matchLabels": {
        "version": "alpha-test-2016-10-26",
        "name": "yce-test",
        "author": "admin"
      }
    },
    "replicas": 1
  },
  "metadata": {
    "annotations": {
      "userId": "1",
      "kubernetes.io/change-cause": "update to 201703211640",
      "image": "img.reg.3g:15000/yce-alpha:201703211640",
      "deployment.kubernetes.io/revision": "32"
    },
    "labels": {
      "version": "alpha-test-2016-10-26",
      "name": "yce-test",
      "author": "admin"
    },
    "creationTimestamp": "2016-12-16T12:45:01Z",
    "generation": 81,
    "uid": "757f39f0-c38d-11e6-977e-44a84240716a",
    "selfLink": "/apis/extensions/v1beta1/namespaces/yce/deployments/yce-test",
    "namespace": "yce",
    "name": "yce-test"
  },
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment"
}`
)

func main() {

        newDp:= new(extensions.Deployment)
        json.Unmarshal([]byte(DeploymentNewStr), &newDp)

        oldDp:= new(extensions.Deployment)
        json.Unmarshal([]byte(DeploymentOldStr), &oldDp)

        podTemplateSpecHash := podutil.GetPodTemplateSpecHash(newDp.Spec.Template)
        podTemplateSpecHashOld := podutil.GetPodTemplateSpecHash(oldDp.Spec.Template)

        fmt.Printf("%d, %s\n", podTemplateSpecHash, newDp.Spec.Template.Spec.Containers[0].Image)
        fmt.Printf("%d, %s\n", podTemplateSpecHashOld, oldDp.Spec.Template.Spec.Containers[0].Image)
}
```

Result:
```bash
./hasher 
985343960, img.reg.3g:15000/yce-alpha:201703211640
985343960, img.reg.3g:15000/yce-alpha:201703151133
```

In kube-controller-manage.log:
```bash
E0321 18:53:41.645479    1664 deployment_controller.go:395] Error syncing deployment yce/yce-test: error creating replica set yce-test: replicasets "yce-test-2281102275" already exists
```

The rolling upgrade progress got stuck(actually failed)  when we try to upgrade our deployment yce, and we know we got the new Deployment with it's image updated, but it didn't get the newRs as suppose to, it seems like the Deployment had created the newRs with the same PodTemplateSpecHash in its name because of the hash collision in GetPodTemplateSpecHash() function.

BTW, we use kubernetes 1.2 version.

Thank you~

**Comment by kargakis** [comment] 2017-03-21 13:05
Dupe of https://github.com/kubernetes/kubernetes/issues/29735

**Closed by kargakis** 2017-03-21 13:05 UTC
