### ISSUE TITLE
Merge bot cannot merge more than 3 PRs per hour

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13441] opened 2015-09-01 12:41 UTC
Currently running e2e tests on PR builder takes ~22 minutes. However, during those 22 minutes we have:
- 9 minutes of building & starting cluster
- 8 minutes of running tests
- 5 minutes of turning down cluster

We should either try to speed-up cluster up/down operations or use push instead of turning up and down the whole cluster every time.

cc @kubernetes/goog-testing @quinton-hoole

**Comment by wojtek-t** [comment] 2015-09-01 14:48
Note that 2.5 PRs per second is an extremely optimistic assumption - it assumes that:
- build is constantly green
- there are no PR-builder flakes (which are happening relatively frequently)

**Comment by wojtek-t** [comment] 2015-09-01 14:49
cc @brendandburns

**Comment by quinton-hoole** [comment] 2015-09-01 15:21
@wojtek-t Note that the PR builder runs multiple e2e test clusters at once.  Currently it has 8 concurrent worker threads, so it can currently test around 20 PR's per hour, and that can be increased arbitrarily.

Having said that, I guess that by it's current design the merge bot needs to run e2e tests strictly in serial?  Even if we make the optimizations that you suggest, it will only increase the rate from 2.5/hour to about 6/hr (assuming 2 minutes to build and push updates to the cluster, plus 8 minutes to run the tests).  The number of e2e tests is highly likely to increase, bringing that back down again.  I don't think that this is good enough.

I think we need to come up with a better solution here (perhaps in addition to the optimization that you propose).

Two options come to mind:

1. Optimistically run the merge bot e2e test runs in parallel, assuming that most of them will pass (seeing as they've already passed once before).  For example, say PR's 1, 2 and 3 have all passed their individual e2e test runs when merged against current HEAD (as per current per-PR e2e).  Now we want to test them in serial on top of each other, so we kick off three concurrent e2es (the first including PR 1, the second including PR's 1 and 2, and the third including PR's 1, 2, 3).  The liklihood of any of them failing is very low (assuming that our e2e tests are properly deflaked, which they are not at the moment, but should be soon).  

2. Dramatically cut down the number of e2e tests that the merge bot runs.  It's conceivable that e.g. we could run only the tests that take <2 minutes, and if we run them all in parallel we could conceivably get them all to complete in ~2 minutes.  That would push the merge rate up to about 25 per hour, using the same assumptions as above.

Thoughts?  @brendandburns ?

**Comment by quinton-hoole** [comment] 2015-09-01 15:31
cc @ixdy who might have some better ideas?

**Comment by wojtek-t** [comment] 2015-09-01 15:41
I think that 6 PRs/hours would be strictly better - it's more than 100 per day, which I think should be enough for quite some time. I think we don't need to as much right now.

I think the first suggestion makes a lot of sense.

As for your second point, this really assumes that build+up+down is quite fast. Since it's currently not, we're back to the initial point that I mentioned.

**Comment by quinton-hoole** [comment] 2015-09-01 15:50
Oh, I forgot to mention, doing a push rather than a down/up has the downside that there could well be "state bleed" between test runs.  Storage attached to the VM's, iptables rules in the kernel, connection tracking tables (also int he kernel), that sort of thing.  But we can certainly give it a try.  Should be fairly simple to implement.  @ixdy?

**Comment by wojtek-t** [comment] 2015-09-01 16:08
Sure - I agree that's not the best solution - I was just brainstorming. And I'm not sure how much we can gain from it.

**Comment by quinton-hoole** [comment] 2015-09-01 18:38
@lavalamp purely FYI.  He was trying to unclog the merge queue this morning, and expressed interest in this topic.

**Comment by lavalamp** [comment] 2015-09-01 18:43
I think 3 per hour would be OK if everything were constantly green without flakes, which it isn't.

**Comment by nikhiljindal** [comment] 2015-09-01 20:06
There are 34 LGTM'd open PRs right now: https://github.com/kubernetes/kubernetes/labels/lgtm
Can we have them manually merged by oncall until the merge-bot catches up?

**Comment by quinton-hoole** [comment] 2015-09-01 20:11
As far as I know, the merge bot waits for "ok-to-merge".
There are 8 of those:

https://github.com/kubernetes/kubernetes/labels/ok-to-merge

Q

**Comment by lavalamp** [comment] 2015-09-01 20:19
@nikhiljindal I did manually just merge a batch, waiting for all the test runs to be clean before I do more.

@quinton-hoole It only needs ok-to-merge for non-whitelisted contributors; @brendandburns just added a change so it will start asking for the label if it needs it.

**Comment by nikhiljindal** [comment] 2015-09-01 20:24
Great thanks @lavalamp!

**Comment by wojtek-t** [comment] 2015-09-02 13:38
>
I think 3 per hour would be OK if everything were constantly green without flakes, which it isn't.

Maybe that's true, but are quite far from being there. Currently merge-bot is able to merge just few PRs per day due to different flakes.

**Comment by brendandburns** [comment] 2015-09-09 23:59
Yeah, I would rather get to steady state green without flakes as a first step.  merge bot is serial by design.  We should use this as a forcing function to make our test infrastructure better.

**Comment by wojtek-t** [comment] 2015-09-10 06:26
>
Yeah, I would rather get to steady state green without flakes as a first step. merge bot is serial by design. We should use this as a forcing function to make our test infrastructure better.

+1 - if we have non-flaky tests, being able to merge ~60 PRs per day (+ those that not require e2e tests, like docs) seems to be enough for now

**Comment by brendandburns** [comment] 2015-11-10 19:21
Closing this since we seem to be ok w/ the status quo...

**Closed by brendandburns** 2015-11-10 19:21 UTC
Labels: area/test, priority/P2, team/test-infra
