### ISSUE TITLE
ABAC authorizer should provide access to unversioned endpoints

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#17462] opened 2015-11-18 22:41 UTC
Right now the [abac authorizer](https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/abac.go) doesn't provide a way to authorize access to unversioned api endpoints, e.g. /version, /api. This means that you cannot use`kubectl` to interact with resources on an apiserver using `--authorization-mode=ABAC`, since `kubectl` hits /api to get the list of supported api versions.

At least [one user](http://stackoverflow.com/questions/33790438/using-kubectl-with-kubernetes-authorization-mode-abac) has hit this problem. cc @liggitt, @deads2k, @lavalamp

**Comment by liggitt** [comment] 2015-11-18 22:45
Fix in progress in https://github.com/kubernetes/kubernetes/pull/16148 
Trying to get back to finish that up

**Comment by lavalamp** [comment] 2015-11-18 23:45
Good catch.

**Comment by liggitt** [comment] 2015-11-18 23:48
Dupe of https://github.com/kubernetes/kubernetes/issues/13097

**Closed by liggitt** 2015-11-18 23:48 UTC
Labels: priority/P1, team/control-plane, team/CSI
