### ISSUE TITLE
hack/verify-bazel.sh failing with HTTP error 301

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#39583] opened 2017-01-08 20:52 UTC
When I run it locally:
```
$ hack/verify-bazel.sh
# cd .; git clone https://gopkg.in/mikedanese/gazel.v13 /usr/local/google/home/mtaufen/go-tools/src/gopkg.in/mikedanese/gazel.v13
Cloning into '/usr/local/google/home/mtaufen/go-tools/src/gopkg.in/mikedanese/gazel.v13'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/mikedanese/gazel.v13/gazel: exit status 128
!!! Error in hack/verify-bazel.sh:23
  'go get -u gopkg.in/mikedanese/gazel.v13/gazel' exited with status 1
Call stack:
  1: hack/verify-bazel.sh:23 main(...)
Exiting with status 1
```

Small test case to induce failure:
```
$ git clone https://gopkg.in/mikedanese/gazel.v13
Cloning into 'gazel.v13'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
```

I am using git version 2.11.0, if it makes any difference.

**Comment by mtaufen** [comment] 2017-01-08 20:54
Also applies to `hack/update-bazel.sh`

**Comment by mikedanese** [comment] 2017-01-09 19:03
This is caused by the most recent git upgrade and affects all of our gopkg.in deps but gazel is the one we pull the most. @ixdy @spxtr how do we mitigate this?

**Comment by spxtr** [comment] 2017-01-09 19:11
We could possibly set `http.followRedirects` in verify/update-gazel, but that feels a bit iffy because it has to be global. Possibly print out the command to fix it in case the go get fails?

**Comment by mikedanese** [comment] 2017-01-09 19:16
Source code for gopkg.in is here https://github.com/niemeyer/gopkg . There doesn't seem to be an open issue for this.

**Comment by mikedanese** [comment] 2017-01-09 19:17
I filed. https://github.com/niemeyer/gopkg/issues/50

**Comment by spxtr** [comment] 2017-01-09 19:20
@ixdy says `git config --global http.https://gopkg.in.followRedirects true`

**Comment by niemeyer** [comment] 2017-01-10 01:51
Sorry for the trouble. We'll change gopkg.in a bit to ensure the manual configuration is not necessary.

**Comment by nikhiljindal** [comment] 2017-01-20 00:39
@niemeyer Was this fixed in gopkg.in?

**Closed** 2017-02-03 02:53 UTC
Labels: area/build-release

**Comment by niemeyer** [comment] 2017-02-21 17:06
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by mikedanese** [comment] 2017-02-21 17:09
@niemeyer thanks for fixing this!
