### ISSUE TITLE
kubernetes v1.11.8: watch of *v1.Service ended with: too old resource version

### ISSUE THREAD

**Issue by andy-wolf168** [kubernetes/kubernetes#89802] opened 2020-04-03 04:28 UTC
**What happened**:
```
[root@node1 ~]# kubectl get node
NAME      STATUS     ROLES     AGE       VERSION
node1      Ready      master    44d       v1.11.8
node2      Ready      master    44d       v1.11.8
node3      Ready      master    44d       v1.11.8
```

1. The node1 reboot while creating service (selector={app=app-dc1}), and create successed with resourceVersion=3597644:

` Service(apiVersion=v1, kind=Service, ...}, clusterName=null, creationTimestamp=2019-09-11T05:18:16Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=dc}, name=dc, namespace=dc, ownerReferences=[], resourceVersion=3597644,...selector={app=app-dc1},...)`

2. controller-manager not received the event of service change, and did not create endpoints

(1) 
```
[root@node1 ~]#kubectl get svc dc -n dc -owide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE    SELECTOR
  dc  ClusterIP   10.96.222.160    <none>    480/TCP   44m   app=app-dc1
[root@node1 ~]#kubectl get ep dc -n dc 
No resource found
```

(2) logs in controller-manager with --v=6: 
   I did not see this log : "Finished syncing service %q endpoints. (%v)" in  EndpointController#syncService

controller-manager logs:

```
I0911 05:18:17.658700       1 reflector.go:428] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: Watch close - *v1.Service total 0 items received
I0911 05:18:17.661983       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=3591583&timeoutSeconds=367&watch=true 200 OK in 2 milliseconds
W0911 05:18:17.662267       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.Service ended with: too old resource version: 3591583 (3597647)
..
I0911 05:18:18.662495       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130
I0911 05:18:18.664628       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?limit=500&resourceVersion=0 200 OK in 1 milliseconds
I0911 05:18:18.667097       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=**3597647**&timeoutSeconds=317&watch=true 200 OK in 1 milliseconds
```

I found that created service's resourceVersion is **3597644**, it is older then watchcatche's **3597647**, can this event be lost?

Because I see these descriptions saying that reconnection is only taken from the cache, not all data in etcd. 

```
Reflector) ListAndWatch(){
// Explicitly set "0" as resource version - it's fine for the List()
// to be served from cache and potentially be delayed relative to
// etcd contents. Reflector framework will catch up via Watch() eventually.
lastRv=listerWatcher.List(ResourceVersion: "0"})
listerWatcher.Watch(lastRv)  
```

**What you expected to happen**:
"kubectl get ep dc -n dc" can  show ep  resource

**How to reproduce it (as minimally and precisely as possible)**:
reboot 

**Anything else we need to know?**:
Probabilistic appearance

**Environment**:
- Kubernetes version (use `kubectl version`):  1.11.8
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
@tedyu @liggitt

**Comment by liggitt** [comment] 2020-04-06 14:48
cc @wojtek-t

**Comment by wojtek-t** [comment] 2020-04-06 15:03
Copying from the above:

```
I0911 05:18:18.662495       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130
I0911 05:18:18.664628       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?limit=500&resourceVersion=0 200 OK in 1 milliseconds
I0911 05:18:18.667097       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=**3597647**&timeoutSeconds=317&watch=true 200 OK in 1 milliseconds
```

Reflector is watching starting with RV of the LIST request from before it:
https://github.com/kubernetes/kubernetes/blob/release-1.11/staging/src/k8s.io/client-go/tools/cache/reflector.go#L307

Based on that, we know that the LIST operation itself returned `RV=3597647`.

So there are two options:
(a) the LIST didn't contain the date
(b) Informer framework handled the diff incorrectly (and didn't fire the request)


@andy-wolf168 - do you have watch-cache enabled in your cluster? It may help us detecting whether you faced (a) or (b) issue...

**Comment by andy-wolf168** [comment] 2020-04-06 15:23
> Copying from the above:
> 
> ```
> I0911 05:18:18.662495       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130
> I0911 05:18:18.664628       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?limit=500&resourceVersion=0 200 OK in 1 milliseconds
> I0911 05:18:18.667097       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=**3597647**&timeoutSeconds=317&watch=true 200 OK in 1 milliseconds
> ```
> 
> Reflector is watching starting with RV of the LIST request from before it:
> https://github.com/kubernetes/kubernetes/blob/release-1.11/staging/src/k8s.io/client-go/tools/cache/reflector.go#L307
> 
> Based on that, we know that the LIST operation itself returned `RV=3597647`.
> 
> So there are two options:
> (a) the LIST didn't contain the date
> (b) Informer framework handled the diff incorrectly (and didn't fire the request)
> 
> @andy-wolf168 - do you have watch-cache enabled in your cluster? It may help us detecting whether you faced (a) or (b) issue...

**Comment by andy-wolf168** [comment] 2020-04-06 15:26
Thanks for taking the time to respond,@wojtek-t,@liggitt
Yes, watch-cache is enable. 
--default-watch-cache-size="100"
--watch-cache="true"
 --watch-cache-sizes="[]"

**Comment by wojtek-t** [comment] 2020-04-06 16:20
@andy-wolf168 - I guess you didn't want to close the issue?

**Comment by wojtek-t** [comment] 2020-04-06 16:27
Actually, looking deeper into this log:
```
I0911 05:18:18.667097       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=**3597647**&timeoutSeconds=317&watch=true 200 OK in 1 milliseconds
```

I think that there is something happening here too. The fact that it finished within 1ms suggests that some error might have been sent here (200 from watch doesn't reflect that it really finished successfully). Maybe that's a red-herring, but it would be useful to see what happened later.

Also - if you are able to reproduce it, it would be useful if you could send the results of what LIST result (both with RV="0" and with RV="").

**Comment by andy-wolf168** [comment] 2020-04-07 08:28
I think it is a common behavior for the client to re-listwatch. At this time, whether the data in the server cache may be discarded because the cache is full, and then not processed by the client?
Or, is it possible that the data in the server cache is consumed by a client such as a kubelet, and the client controller-manager connected later will not be able to accept the event?

**Comment by wojtek-t** [comment] 2020-04-07 11:22
> I think it is a common behavior for the client to re-listwatch.

true

> At this time, whether the data in the server cache may be discarded because the cache is full, and then not processed by the client?

The cache in server has two parts:
- the state (which doesn't have any limits - it is the whole state from a given point in time - propagated by watch from etcd)
- the transaction log - which is used for sending events to watchers (that has a capacity)

In your case, there was a list operation from cache (resourceVersion=0 is what determines it) and as I mentioned above, what was returned was a state from the time when RV=3597647
```
I0911 05:18:18.667097       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?resourceVersion=**3597647**&timeoutSeconds=317&watch=true 200 OK in 1 milliseconds
```
[we uses RV from list to pass it to watch]

Given it's later than RV of service creation, that LIST (assuming no bugs) would contain that service, and as a result it would be delievered by informer framework as a handler call.

So as I mentioned above:
- either there is a bug in watch cache (in it's easiest part that is just keeping up the state) and it didn't contain that service even though RV was past its creation
- or the list contained it, but there is a bug in informer framework and the diff wasn't correctly processed

> Or, is it possible that the data in the server cache is consumed by a client such as a kubelet, and the client controller-manager connected later will not be able to accept the event?

No - events can be consumed independently by different watchers.


I tried reproducing it over night (left a script running) and failed. so I think we need more information from you to debug it.

**Comment by andy-wolf168** [comment] 2020-04-07 12:03
> The cache in server has two parts:
> 
> - the state (which doesn't have any limits - it is the whole state from a given point in time - propagated by watch from etcd)
> - the transaction log - which is used for sending events to watchers (that has a capacity)
`I0911 05:18:18.664628       1 round_trippers.go:405] GET https://10.0.206.180:6443/api/v1/services?limit=500&resourceVersion=0 200 OK in 1 milliseconds`
Whether the data obtained by the list operation of resourceVersion=0 comes from the transaction log(that has a capacity), not from the state (which doesn't have any limits, and have full data)

> what was returned was a state from the time when RV=3597647
create service return message:
`Service(apiVersion=v1, kind=Service, ...}, clusterName=null, creationTimestamp=2019-09-11T05:18:16Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={app=dc}, name=dc, namespace=dc, ownerReferences=[], resourceVersion=3597644,...selector={app=app-dc1},...)`
as I mentioned above, that created service's resourceVersion is 3597644, it is older then watchcatche's 3597647, Can it be inferred that the creation event of service is not within the scope of re-listwatch?

**Comment by wojtek-t** [comment] 2020-04-07 12:05
@andy-wolf168 - I already wrote the above.

>> either there is a bug in watch cache (in it's easiest part that is just keeping up the state) and it didn't contain that service even though RV was past its creation

By design it works. I don't see any suspcious in the code. And I'm not able to reproduce.
We need to reproduction steps from you or more logs than you gave.

**Closed** 2020-09-04 13:49 UTC
Labels: kind/bug, lifecycle/rotten, sig/api-machinery
