### ISSUE TITLE
Kubelet use RunC instead of docker daemon

### ISSUE THREAD

**Issue by sparkthu** [kubernetes/kubernetes#29731] opened 2016-07-28 10:11 UTC
Mesos 1.0.0 has already support use docker images without docker daemon. I think it is an attractive feature for kubelet.

**Comment by luxas** [comment] 2016-07-28 22:28
cc @kubernetes/sig-node

**Comment by euank** [comment] 2016-07-29 00:23
I believe this is a duplicate of https://github.com/kubernetes/kubernetes/pull/26788

This is also related to the features https://github.com/kubernetes/features/issues/54 (which will make it possible to swap in such a runtime) and https://github.com/kubernetes/features/issues/58 (a feature to run Kubernetes with rkt rather than Docker), as well as other bits of related discussion.

**Comment by yujuhong** [comment] 2016-07-29 00:29
Yes, integrating with other container runtimes (runc being one example) is WIP already. Let's close this issue.

**Closed by yujuhong** 2016-07-29 00:29 UTC

**Comment by shenshouer** [comment] 2018-07-12 09:22
How to ?

**Comment by dims** [comment] 2018-07-12 10:34
@shenshouer see https://github.com/kubernetes-incubator/cri-o
