### ISSUE TITLE
apf: test flake without detailed logs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#97511] opened 2020-12-25 04:14 UTC
**What happened**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97447/pull-kubernetes-e2e-kind/1342023270328700928

```
Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can be classified by testing flow-schemas/priority-levels expand_less | 2s
-- | --
test/e2e/apimachinery/flowcontrol.go:48 Dec 24 08:41:58.409: matching user doesnt received UID for the testing priority-level and flow-schema vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

**What you expected to happen**:

This test should not flake and the logs should show me what did happen.

https://github.com/kubernetes/kubernetes/blob/88a05df5ff1b311e8e92f64b4f3a2c7d4329d14e/test/e2e/apimachinery/flowcontrol.go#L63

**How to reproduce it (as minimally and precisely as possible)**:

Send a PR to Kubernetes. Run tests repeatedly. Enjoy flakes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment] 2020-12-25 11:47
This looks a duplicate of 
https://github.com/kubernetes/kubernetes/issues/96803

**Comment by BenTheElder** [comment] 2021-01-07 22:11
https://github.com/kubernetes/kubernetes/issues/96803 had some different failures I think, commented there as well

**Comment by lavalamp** [comment] 2021-01-08 00:17
My guess is we somehow have a race with the apiserver loading the new PL / FS.

**Comment by BenTheElder** [comment] 2021-02-25 00:55
spotted again 1.20 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/2089/pull-kind-e2e-kubernetes-1-20/1364730432314150912

seems to be sporadic in HEAD and 1.20 at least:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=matching%20user%20doesnt%20received

**Comment by BenTheElder** [comment] 2021-06-04 19:40
/remove-lifecycle stale

These are still occurring. We have multiple instances today like:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/flowcontrol.go:48
May 21 13:27:41.970: matching user doesnt received UID for the testing priority-level and flow-schema
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=matching%20user%20doesnt%20received

**Comment by lavalamp** [comment] 2021-06-04 23:40
The failures appear to be only from 1.20. The code for the test is definitely very different now. Probably https://github.com/kubernetes/kubernetes/pull/96984 fixed the problem. I can't think of a reason not to backport it.

**Comment by BenTheElder** [comment] 2021-06-08 21:49
Good catch re: 1.20

filed https://github.com/kubernetes/kubernetes/pull/102709, there were conflicts and I'm not certain yet that it's correct.

**Closed** 2021-11-05 23:09 UTC
Labels: sig/api-machinery, kind/flake, lifecycle/rotten, triage/accepted
