### ISSUE TITLE
Support show pod/service/events/rc by namespace in UI

### ISSUE THREAD

**Issue by njuicsgz** [kubernetes/kubernetes#9311] opened 2015-06-05 09:24 UTC
It seems we just support namespace 'default' for all items of 'view' in dashboard. I can not find any place to get Pods/Services of other namespace.

**Comment by njuicsgz** [comment] 2015-06-05 09:24
```
root@paas-185:~# kubectl version
Client Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.1", GitCommit:"befd1385e5af5f7516f75a27a2628272bb9e9f36", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.1", GitCommit:"befd1385e5af5f7516f75a27a2628272bb9e9f36", GitTreeState:"clean"}
```

**Comment by derekwaynecarr** [comment] 2015-06-05 12:56
kubectl get pods --namespace=foo

Or am I missing something in the question?

**Comment by njuicsgz** [comment] 2015-06-09 00:52
Sorry for the confused issue title. I mean the dashboard of k8s in www, not CLI. I cannot find any config or filter by namespace in the GUI.

**Comment by njuicsgz** [comment] 2015-06-17 00:54
@derekwaynecarr can you change the label 'CLI'? since it is a UI issue.
Thanks

**Comment by bgrant0607** [comment] 2015-10-08 05:42
Dupe of #13276

**Closed by bgrant0607** 2015-10-08 05:42 UTC
Labels: component/ui, team/ux
