### ISSUE TITLE
Can't replace a pvc

### ISSUE THREAD

**Issue by nballotta** [kubernetes/kubernetes#18761] opened 2015-12-16 16:15 UTC
Hi, I'm trying to change the size of a pv and a pvc. The pv went well, but I can't change the pvc size. 

This is what I've done.

```
$ kubectl get pvc --all-namespaces

NAMESPACE     NAME                LABELS                               STATUS    VOLUME                         CAPACITY   ACCESSMODES   AGE
kube-system   kube-registry-pvc   kubernetes.io/cluster-service=true   Bound     kube-system-kube-registry-pv   50Gi       RWO           2d

$ kubectl get pvc kube-registry-pvc --namespace="kube-system" -o yaml > storage-claim.yaml

$ vim storage-claim.yaml # I changed requests: storage and capacity: storage to 10Gi

$ kubectl replace -f storage-claim.yaml
persistentvolumeclaim "kube-registry-pvc" replaced

$ kubectl get pvc --all-namespaces
NAMESPACE     NAME                LABELS                               STATUS    VOLUME                         CAPACITY   ACCESSMODES   AGE
kube-system   kube-registry-pvc   kubernetes.io/cluster-service=true   Bound     kube-system-kube-registry-pv   50Gi       RWO           2d

$ kubectl get pvc kube-registry-pvc --namespace="kube-system" -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2015-12-14T10:42:38Z
  labels:
    kubernetes.io/cluster-service: "true"
  name: kube-registry-pvc
  namespace: kube-system
  resourceVersion: "103704"
  selfLink: /api/v1/namespaces/kube-system/persistentvolumeclaims/kube-registry-pvc
  uid: 64e6d18d-a24f-11e5-b366-0800275bd0a6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kube-system-kube-registry-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound 
```

This is the yaml I try to replace the pvc with:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2015-12-14T10:42:38Z
  labels:
    kubernetes.io/cluster-service: "true"
  name: kube-registry-pvc
  namespace: kube-system
  resourceVersion: "103704"
  selfLink: /api/v1/namespaces/kube-system/persistentvolumeclaims/kube-registry-pvc
  uid: 64e6d18d-a24f-11e5-b366-0800275bd0a6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kube-system-kube-registry-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

It's a bug or I'm missing something?

**Comment by jingxu97** [comment] 2016-08-31 06:13
@saad-ali @thockin could you please help answer what is the expected behavior?

**Comment by thockin** [comment] 2016-08-31 18:46
a) You can't edit `status` the same way you edit `spec`.  Even if you could, status is reflected from reality, so your changes would get nuked.

b) Updating a PVC will not unbind it and restart the pod.  Unfortunately we allowed this update.  It should probably have been blocked.  To get a new PVC->PV binding you really need a new PVC.

https://github.com/kubernetes/kubernetes/issues/24111

That said I'm going to close this as "not a bug"

**Closed** 2016-08-31 18:46 UTC
Labels: area/storage, team/cluster

**Comment by jingxu97** [comment] 2016-08-31 18:53
Could we add this behavior to doc so that user can understand what to do in this case.

**Comment by thockin** [comment] 2016-08-31 19:35
that would be great!
