### ISSUE TITLE
kubeadm should bind API to port 6443 to avoid obvious collisions

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#34311] opened 2016-10-07 09:07 UTC

**Comment by errordeveloper** [comment] 2016-10-11 11:00
As many folks asked for this, I'm going to fix it.

**Comment by guybrush** [comment] 2016-10-11 15:48
i changed the 3 occurences of `443` to `6443` and it worked for me (but i am totally unfamiliar with the code)

```
k8s.io/kubernetes/cmd/kubeadm $ git grep 443
app/master/discovery.go:                endpointList = append(endpointList, fmt.Sprintf("https://%s:443", addr))
app/master/kubeconfig.go:               fmt.Sprintf("https://%s:443", advertiseAddresses[0]),
app/master/manifests.go:                        "--secure-port=443",
```

**Comment by sandys** [comment] 2016-10-12 18:18
can you guys look at bug #34307 simultaneously ? we would like to have control over this (for policy reasons), but it doesnt seem to work by changing json or whatever. 

it would be awesome if you could give a kubeadm commandline flag to make it happen in a nicer way (and take care of restarting api server, etc)

**Comment by errordeveloper** [comment] 2016-10-12 18:39
@sandys #33638 will allow you to set any ports you prefer, It's like that we might change the defaults and provide flags in one go.

**Comment by errordeveloper** [comment] 2016-10-12 18:40
@guybrush yes, that should be enough. We are planning to make this change and add a flag also, and release it along with other bug fixes as a snapshot build.

**Comment by sandys** [comment] 2016-10-12 19:16
@errordeveloper thank you! but in context of this bug, i meant that changing the json is not working for several people (including me). we are hitting issue #34307 . Will this bug (34311) and 34307 be fixed together ?

**Comment by luxas** [comment] 2016-10-15 07:52
Closing this as a duplicate of #33638

**Closed by luxas** 2016-10-15 07:52 UTC
Labels: component/kubeadm
