### ISSUE TITLE
upgrade to 1.18.0，ipvs do not sync endpoint error: parseIP Error

### ISSUE THREAD

**Issue by k8sre** [kubernetes/kubernetes#89561] opened 2020-03-27 03:26 UTC
**What happened**:

k8s
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
os
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
kernel
```
Linux master-01 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

<img width="436" alt="1" src="https://user-images.githubusercontent.com/35365219/77718362-b5855c80-701d-11ea-9eef-c61bd0386ff3.png">

<img width="533" alt="2" src="https://user-images.githubusercontent.com/35365219/77718372-b918e380-701d-11ea-9212-18a2df0009ca.png">

<img width="317" alt="3" src="https://user-images.githubusercontent.com/35365219/77718376-bd450100-701d-11ea-9dfc-612481c4e280.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/35365219/77718395-cafa8680-701d-11ea-8e3f-14cab240386b.png">

**Comment by liggitt** [comment] 2020-03-27 03:59
This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/89520

**Closed by liggitt** 2020-03-27 03:59 UTC
Labels: kind/bug, needs-sig

**Comment by aojea** [comment] 2020-03-27 09:02
@k8sre can you provide more details?
has this happened after an upgrade?
have you dual-stack enable or only ipv4?

**Comment by k8sre** [comment] 2020-04-08 09:50
only ipv4
