### ISSUE TITLE
Pod stuck on pending status due to hung docker daemon

### ISSUE THREAD

**Issue by sspeiche** [kubernetes/kubernetes#13305] opened 2015-08-28 12:27 UTC
Kubernetes should detect that case when a node has a hung docker daemon and scheduler is infinitely waiting for pod to be launched.  It would be good to terminate the execution after some period of time and log an event/message. It would be better if it attempted to launch the pod on a different healthy node.

I hit this issue recently with an instance that had been running for about a month. Things were working fine for a couple weeks.

/version reveals:
"gitVersion": "v0.17.1-804-g496be63",
"gitCommit": "496be63",

Original down stream issue in https://github.com/openshift/origin/issues/4398

**Comment by yujuhong** [comment] 2015-08-28 19:23
kubelet checks if docker is up periodically, and should post a "NotReady" node status to the apiserver if docker is unresponsive. Did this not happen in your cluster?

**Comment by bprashanth** [comment] 2015-08-28 20:08
Might also depend on what you mean by hung, if docker version is working but everything else is not it probably won't trigger the NotReady

**Comment by sspeiche** [comment] 2015-08-28 20:11
@csrwng @wshearn Can you assist in providing the details of what you've seen on your end that is causing it to be stuck in pending?

**Comment by csrwng** [comment] 2015-08-28 20:15
In this case some commands like ```docker images``` were responding, but ```docker ps``` and ```docker run [blah]``` were just hanging

**Comment by meonkeys** [comment] 2016-01-29 20:00
I've got a repro in my cluster, but it generally takes _6 days_ to surface. Master and worker nodes run CoreOS alpha 928.0.0. See https://github.com/coreos/bugs/issues/254#issuecomment-176509100

**Comment by yujuhong** [comment] 2016-01-29 20:18
> docker version was working (probably just the client-side version

@meonkeys, `docker version` also checks the server version in newer docker (v1.7+?). See https://github.com/kubernetes/kubernetes/issues/17525#issuecomment-158246388
However, the hanging issue seems to only hit `docker ps` and not `docker version`. We've seen it a couple of times in our soak cluster too (#20096).
@dchen1107 did some digging and it seems to be a kernel issue. The best kubernetes can do at this point is to clearly declare that the node is in a bad state, and let the control plane drain the pods on the node.

FYI, there are more discussions in #17525 about checking the health check in supervisord (or other babysitters) to use `docker ps`

**Comment by meonkeys** [comment] 2016-01-29 22:31
> `docker version` also checks the server version in newer docker

Right, I meant that maybe it actually said something like this, but I wasn't paying close enough attention:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by dchen1107** [comment] 2016-01-29 23:57
@meonkeys after you run docker version, could you please check the return code? supervisord should capture the issue if code is not 0, and try to restart docker daemon.

But if you hit kernel issue like #20096, docker version returns 0, but hang forever. In this case, the only way to do is rebooting the node.

**Comment by meonkeys** [comment] 2016-01-30 18:13
@dchen1107 ah, thanks for the clarification. Yes, next time I get a repro I'll note the return code of `docker version`.

**Comment by andrewmichaelsmith** [comment] 2016-02-19 10:51
We are seeing this quite regularly. Some as yet undiagnosed issues we have with the docker daemon (I suspect https://github.com/docker/docker/issues/13885) leave the `docker ps` in a state where it hangs indefinitely.

We find our pods will stay in "Terminating" and "Pending" (we've seen upwards of 1 day) and the node remains Ready.

Our setup (I don't have a node in this state at the moment, but will update when I do):

```Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64```

**Comment by andrewmichaelsmith** [comment] 2016-02-19 15:04
We've just hit this issue again. `docker ps` is hanging. I can confirm that `docker version` *does not* hang:

```$ sudo docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64```

`docker ps` and `docker info` do not respond (hang indefinitely).

The node is still reporting as Ready and has been for the last 30 minutes.

**Comment by andrewmichaelsmith** [comment] 2016-02-26 14:19
Would you be interested in a pull request that uses "docker info" for the health check instead of "docker version"?

**Comment by pieterlange** [comment] 2016-05-24 15:14
Ping: are there still plans to change the docker health check to use docker ps instead of docker version?

Had this exact problem on 2 coreos 1032.1.0 nodes today; the docker daemon is completely unresponsive (except for version), but this didn't get picked up by kubernetes. Node remains healthy.

**Comment by yujuhong** [comment] 2016-05-24 16:13
@pieterlange, we already switched our [docker checking script](https://github.com/kubernetes/kubernetes/blob/e6af5ee2965ec47d02d6609f67a9526819872fcb/cluster/saltbase/salt/supervisor/docker-checker.sh#L46) to use `docker ps` as the health check. The babysitter will restart docker if it hangs.

In addition to that, we also added timeout to docker calls in kubelet, so that even if docker hangs, kubelet will not get stuck with it. kubelet will then update docker's health condition if the request did not succeed.

I am closing this issue since most things have already been taken care of. Feel free to reopen it if that's not the case.

**Closed by yujuhong** 2016-05-24 16:13 UTC
Labels: area/reliability, priority/P2, team/node

**Comment by dchen1107** [comment] 2016-05-24 16:25
@pieterlange We are using docker ps to do healthcheck in 1.2 release. Also incoming 1.3 release, we switch to docker native client library so that we can apply timeout to all docker API calls except pulling images. Thanks for reporting the issue.

**Comment by dadux** [comment] 2016-08-17 00:46
Still happening in 1.3.4. 
Docker ps was hanging due to https://github.com/docker/docker/issues/5618 , but the node was still marked as healthy.

**Comment by bprashanth** [comment] 2016-08-17 00:50
@dadux that shouldn't be happening if the container bridge is in promiscuous mode (which is the default deployment), maybe there's something else going on, which os/cloud etc are you on? in the case you mentioned not just docker ps but the daemon itself is a hung task and one needs to reboot the node. I belive the node problem detector (https://github.com/kubernetes/node-problem-detector, if you're running it) should surface such issues.

**Comment by dadux** [comment] 2016-08-17 01:51
@bprashanth CoreOS 1068.8.0 on AWS. I think the problem is I'm using flannel, so the kubelet doesn't manage the bridge - I don't have a cbr0 interface, and I see hairpin mode being enabled for all my veth. Not sure how to work around this.

Thanks, I'll definitely deploy the node-problem-detector, that should at least make my node not healthy !

**Comment by alph486** [comment] 2016-09-02 03:48
@yujuhong I can also confirm this is still happening in 1.3.4. Same environment as @dadux.

**Comment by philk** [comment] 2016-09-20 18:53
Important note for someone else who comes across this thread, node-problem-detector doesn't find this issue on CoreOS (lack of journald support) until kubernetes/node-problem-detector#33 is merged

**Comment by andyxning** [comment] 2017-02-03 07:32
@philk @sspeiche [kubernetes/node-problem-detector#33](https://github.com/kubernetes/node-problem-detector/pull/33) has been merged. :)
