### ISSUE TITLE
41 flakes: k8s.io/kubernetes/pkg/printers/internalversion TestDescribeServiceAccount

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#54834] opened 2017-10-31 02:43 UTC
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestDescribeServiceAccount
```
--- FAIL: TestDescribeServiceAccount (0.00s)
	describe_test.go:1694: expected : "Name:                bar\nNamespace:           foo\nLabels:              <none>\nAnnotations:         <none>\nImage pull secrets:  test-local-ref (not found)\nMountable secrets:   test-objectref (not found)\nTokens:              <none>\nEvents:              <none>\n"
		 but got output:
		 "Name:                bar\nNamespace:           foo\nLabels:              <none>\nAnnotations:         <none>\nMountable secrets:   test-objectref (not found)\nTokens:              <none>\nImage pull secrets:  test-local-ref (not found)\nEvents:              <none>\n"
```

Looks like we may have to sort the order in which things are printed.

**Comment by liggitt** [comment] 2017-10-31 03:18
dupe of https://github.com/kubernetes/kubernetes/issues/54619, fixed in https://github.com/kubernetes/kubernetes/pull/54628

**Closed by liggitt** 2017-10-31 03:18 UTC
Labels: sig/api-machinery
