### ISSUE TITLE
Docker getting starting guide breaks my computer - no new terminals can be created

### ISSUE THREAD

**Issue by tomdee** [kubernetes/kubernetes#18230] opened 2015-12-04 21:29 UTC
If I follow the docker getting started guide from here https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md

It instructs me to start the kubelet with the following command
```
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube:v1.1.2 \
    /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests
```

When I do this I'm no longer able to create any terminals. I'm running Ubuntu 15.04.
The error I get when starting terminal is: 
```
There was an error creating the child process for this terminal
getpt failed: Permission denied
```

I can collect additional diags if someone can guide me on what to collect...

**Comment by tomdee** [comment] 2015-12-04 21:31
I should add that the only way I've found to fix this is to reboot.

**Comment by tomdee** [comment] 2015-12-10 23:57
Any update on this @zmerlynn

**Comment by zmerlynn** [comment] 2015-12-11 00:04
cc @brendandburns @dchen1107

**Comment by tomdee** [comment] 2015-12-11 00:34
I've just been trying it out some more and the `-v /dev:/dev` line seems unnecessary. I suggest we just remove it.

**Comment by luxas** [comment] 2015-12-18 21:49
Related to #15577

**Comment by dmag** [comment] 2015-12-31 22:39
This also affected me on Fedora 23.

I paused for a long time before running that docker container because I'm not sure why kubernetes needs all those permissions, and which ones are optional. (This should be at least documented.) 

I'd be much happier with "safe" docker instructions, even if it limits some features.

**Comment by itorres** [comment] 2016-01-03 02:26
The problem is that `/dev/pts/ptmx` permissions are changed to 000. 
>  [ptmx(4)](http://linux.die.net/man/4/ptmx):
> The file /dev/ptmx is a character file with major number 5 and minor number 2, usually of mode 0666 and owner.group of root.root. It is used to create a pseudoterminal master and slave pair. 

So a quick workaround is running `chmod 666 /dev/pts/ptmx`

**Comment by luxas** [comment] 2016-01-03 07:47
@itorres Thanks for the workaround! 
Was stuck with ssh for some days now, not even reboots did solve it :/
However, your trick did it :+1:

**Comment by slackfarmer** [comment] 2016-02-01 21:31
I had the exact same issue. It is the docker command causing this issue and by changing the permissions via `chmod 666 /dev/pts/ptmx` resolved my issue without a reboot.

**Comment by olafure** [comment] 2016-02-04 17:58
Please consider bumping up the priority of this one.  Rendering dev's workstation virtually unusable is quite an rough welcome to Kubernetes.

**Comment by luxas** [comment] 2016-02-04 18:09
@fgrzadkowski Thoughts? Should it be a `v1.2` issue?
I agree it's very annoying.

**Comment by fgrzadkowski** [comment] 2016-02-05 08:57
AFAIU we are mounting `/dev` so that we are able to use external devices as volumes. However in a local docker cluster this doesn't sound like a very useful thing... I guess as a workaround we can temporary comment out this line with an appropriate comment. WDYT?

@luxas Do you want to send a fix for this?

**Comment by luxas** [comment] 2016-02-07 20:04
Sure @fgrzadkowski, I'll send a fix

**Comment by saad-ali** [comment] 2016-02-10 02:12
@15577 duplicate

**Comment by raeesiqbal** [comment] 2016-02-11 23:51
+1

**Closed** 2016-02-15 11:52 UTC
Labels: priority/P1, team/node
