### ISSUE TITLE
"kubectl <verb> all" should support more resources. 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#23215] opened 2016-03-18 21:22 UTC
`kubectl <verb> all` currently only supports "rc, "svc", "pods", and "pvc". Now that we have replica sets and deployments, we should add them to the list. 

Also, is the use of `all` documented anywhere?

@kargakis @smarterclayton @derekwaynecarr @kubernetes/kubectl

**Comment by bgrant0607** [comment] 2016-03-18 23:08
Should use the discovery API. @lavalamp @caesarxuchao 

Not sure about documentation.

**Comment by liggitt** [comment] 2016-03-18 23:15
@deads2k has done work to hook up `all` to discovery for openshift. There's ongoing debate about whether it should actually include every last resource or not (@smarterclayton)

**Comment by caesarxuchao** [comment] 2016-03-18 23:31
Dup of https://github.com/kubernetes/kubernetes/issues/22337.

**Comment by soltysh** [comment] 2016-03-22 12:30
There are some discussion around the general topic of aliases in https://github.com/kubernetes/kubernetes/issues/18023 and https://github.com/kubernetes/kubernetes/issues/20293.

**Comment by bgrant0607** [comment] 2016-04-27 06:39
Closing as dupe of #22337

**Closed by bgrant0607** 2016-04-27 06:39 UTC
Labels: component/kubectl, help-wanted, priority/P2, team/ux
