### ISSUE TITLE
Consider adopting dep

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#59332] opened 2018-02-05 03:38 UTC
With the latest version of dep and a few tweaks, it now appears to be possible to get dep working with kubernetes.

Here are some learnings from getting dep to not crash for kops (cf https://github.com/kubernetes/kops/pull/4382 ):

* We created a script https://github.com/kubernetes/kops/pull/4382/commits/9fbbbcb76a141658c156b3fd4ffe01ca622fa44c which compares the versions in Godeps.json to the versions resolved by dep
* dep version resolution can be complicated, so we ended up effectively locking every dependency.  This is probably no bad thing, as otherwise it seems that introduction of new code in either the repo or a dependency could change the versions resolved (i.e. the builds might not be repeatable).  (cf https://github.com/kubernetes/kops/pull/4382/commits/8c18d033fa35aa0d6d02c29e30a3c26cfad8b79a )
* `requires` blocks let us declare dependencies that are used by our build script, for example for apimachinery code generation (cf https://github.com/kubernetes/kops/pull/4382/commits/69ff65d91163f37d6cf3002e0f42aa26e6b46016 )
* `github.com/chai2010/gettext-go` has a weird dependency in the version declared in Godeps.json (at least in the 1.9 branch), so we had to deviate from that version and use `bf70f2a70fb1b1f36d90d671a72795984eab0fcb`  (hat-tip to @eparis  for the fix)
* For use with bazel, we use some horrific trickery: we `dep ensure`, then we delete all the bazel files from vendor, then we run bazel with `bazel run //:gazelle -- -proto disable`.  For projects which use proto in bazel, we then need to _revert_ the BUILD.bazel changes outside the vendor directory (as we only want `--proto disable` in the vendor directory).  (cf https://github.com/kubernetes/kops/pull/4382/commits/61b23a6eadd449bab43f40018ae7c5023fcad66c)

It's not ideal, we're basically use dep as a glorified wrapper around git pull, but at least it finally can be made to work.

One intriguing option: this could solve our problem of coordinating versions for a release in a multi-repo world: we could publish a list of the dep `overrides` for each release.  In theory dep won't use those overrides unless the source code actually uses them (in theory).

**Comment by justinsb** [comment] 2018-02-05 03:38
cc @kubernetes/sig-release-feature-requests

**Comment by jhorwit2** [comment] 2018-02-05 03:42
@justinsb This is a duplicate of https://github.com/kubernetes/kubernetes/issues/52728 which has a WIP PR https://github.com/kubernetes/kubernetes/pull/57795.

**Comment by justinsb** [comment] 2018-02-05 03:52
Hooray - yes, it seems dep is finally able to not-segfault and we're all finally having our WIP efforts succeed :-)

I'm wondering if I should change this into a document for the benefit of our universe of kubernetes projects, once we all get this working.  And some of the stuff about around _not_ relying on dep version resolution, and possibly publishing a per-minor release set of overrides feels like something we should decide on.  Is sig-release the correct venue?

**Comment by cblecker** [comment] 2018-02-05 05:32
Hey @justinsb,
We actually have a couple issues for this, so I'm going to close this one out as a dupe. There's a bunch of discussion on #44873 as far as how to improve dependency management for k/k.

I also know there has been a bunch of work in k/test-infra on making dep play nice with bazel. We're hoping to combine these different efforts together into a working solution to the complexity that is k/k :)

Thanks for the info!

/close

**Closed by cblecker** 2018-02-05 05:32 UTC
Labels: kind/feature, sig/release
