### ISSUE TITLE
Integration test flake: Data race in k8s.io/kubernetes/pkg/controller/volume/persistentvolume

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#30947] opened 2016-08-19 00:41 UTC
I got the following failure in the unit test of k8s.io/kubernetes/pkg/controller/volume/persistentvolume.
```
==================
WARNING: DATA RACE
Read by goroutine 156:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).Stop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_base.go:471 +0xc0
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.TestControllerSync()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_test.go:204 +0x39b2
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Previous write by goroutine 173:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_base.go:461 +0x2d4

Goroutine 156 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/pkg/controller/volume/persistentvolume/_test/_testmain.go:90 +0x210

Goroutine 173 (finished) created at:
  k8s.io/kubernetes/pkg/controller/volume/persistentvolume.TestControllerSync()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/controller_test.go:178 +0x32ad
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30913/kubernetes-pull-test-unit-integration/40492/

**Comment by liggitt** [comment] 2016-08-21 18:36
dupe of #30775

**Closed by liggitt** 2016-08-21 18:36 UTC
Labels: area/test, kind/flake
