### ISSUE TITLE
no kind \"CSINode\" is registered for version \"storage.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30

### ISSUE THREAD

**Issue by ysaakpr** [kubernetes/kubernetes#94741] opened 2020-09-12 09:06 UTC
**What happened**:
I had a migration to 1.17 and got to rollback to 1.15, after that, many times I am hitting an error like this on API server. Few of the applications are started failing with. error
```
no kind \"CSINode\" is registered for version \"storage.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30
```
How would I fix this error? I have installed the cluster using kops, there is no documentation on fixing this error anywhere. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: aws
- Install tools: kops

**Comment by ysaakpr** [comment] 2020-09-12 09:07
Is there way to convert the resources to older version, and are there any command to see what all are resources which is not compatible with the existing k8s cluster version?

**Comment by ysaakpr** [comment] 2020-09-12 09:20
```
$ kubectl api-resources -o wide | grep storage
csidrivers                                                               storage.k8s.io                       false        CSIDriver                        [create delete deletecollection get list patch update watch]
csinodes                                                                 storage.k8s.io                       false        CSINode                          [create delete deletecollection get list patch update watch]
storageclasses                    sc                                     storage.k8s.io                       false        StorageClass                     [create delete deletecollection get list patch update watch]
volumeattachments                                                        storage.k8s.io                       false        VolumeAttachment                 [create delete deletecollection get list patch update watch]
```

```
$ kubectl get csinodes
Error from server: no kind "CSINode" is registered for version "storage.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

So basically, all the apps which are failing is doing listing all k8s resources, and while listing CSINode it getting this error. Apart from this there are no issue. Are there a way to delete this resource kind from API resources?

**Comment by liggitt** [comment] 2020-09-12 13:50
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/94675, some potential remedies are described in  https://github.com/kubernetes/kubernetes/issues/94675#issuecomment-690315502

Deleting must be done on an API server version capable of reading the v1 objects (e.g. 1.17+) or directly against etcd (using etcdctl, for example)

**Closed by liggitt** 2020-09-12 13:50 UTC
Labels: needs-sig, triage/support
