### ISSUE TITLE
HPA V2 cannot get custom metrics info

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#45581] opened 2017-05-10 09:10 UTC
Description of problem: HPA V2 cannot get custom metrics info.
```
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  31m		6s		63	horizontal-pod-autoscaler			Warning		FailedGetObjectMetric		unable to get metric http_requests_total: Service on default sample-metrics-app/unable to fetch metrics from API: unable to map kind Service to resource: no matches for /, Kind=Service
  31m		6s		63	horizontal-pod-autoscaler			Warning		FailedComputeMetricsReplicas	failed to get object metric value: unable to get metric http_requests_total: Service on default sample-metrics-app/unable to fetch metrics from API: unable to map kind Service to resource: no matches for /, Kind=Service
```

kubernetes version: v1.7.0-alpha.3.129+20fa30e4b5a256

How reproducible:
Always

Steps to Reproduce:
1. Enable kube DNS, start controller_manager with --horizontal-pod-autoscaler-use-rest-clients="true" and start apiserver with --runtime-config="api/all=true"
```
$ kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2alpha1
```

2. Deploy the Prometheus Operator for monitoring Services in the cluster
```
kubectl apply -f https://raw.githubusercontent.com/luxas/kubeadm-workshop/master/demos/monitoring/prometheus-operator.yaml
kubectl apply -f https://raw.githubusercontent.com/luxas/kubeadm-workshop/master/demos/monitoring/sample-prometheus-instance.yaml
```

3. Deploy a custom metrics API Server and a sample app
```
kubectl apply -f https://raw.githubusercontent.com/luxas/kubeadm-workshop/master/demos/monitoring/custom-metrics.yaml
kubectl apply -f https://raw.githubusercontent.com/luxas/kubeadm-workshop/master/demos/monitoring/sample-metrics-app.yaml
```

4. Check hpa status.
```
# kubectl describe hpa sample-metrics-app-hpa
```

Actual results: hpa cannot get custom metrics, current value is "unknown"
4. Check hpa status.
```
# kubectl describe hpa sample-metrics-app-hpa
Name:							sample-metrics-app-hpa
Namespace:						default
Labels:							<none>
Annotations:						kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v2alpha1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"sample-metrics-app-hpa","namespace":"default...
CreationTimestamp:					Wed, 10 May 2017 04:29:50 -0400
Reference:						Deployment/sample-metrics-app
Metrics:						( current / target )
  "http_requests_total" on Service/sample-metrics-app:	<unknown> / 100
Min replicas:						2
Max replicas:						10
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  31m		6s		63	horizontal-pod-autoscaler			Warning		FailedGetObjectMetric		unable to get metric http_requests_total: Service on default sample-metrics-app/unable to fetch metrics from API: unable to map kind Service to resource: no matches for /, Kind=Service
  31m		6s		63	horizontal-pod-autoscaler			Warning		FailedComputeMetricsReplicas	failed to get object metric value: unable to get metric http_requests_total: Service on default sample-metrics-app/unable to fetch metrics from API: unable to map kind Service to resource: no matches for /, Kind=Service
```

Expected results: 
HPA V2 can get custom metrics info correctly.

Addition info: 
```
# kubectl get all
NAME                                      READY     STATUS    RESTARTS   AGE
po/prometheus-operator-1303517395-dsnkk   1/1       Running   0          9m
po/prometheus-sample-metrics-prom-0       2/2       Running   0          9m
po/sample-metrics-app-2206349241-76xc4    1/1       Running   0          8m
po/sample-metrics-app-2206349241-gvvv7    1/1       Running   0          8m

NAME                      CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
svc/kubernetes            10.0.0.1     <none>        443/TCP          11m
svc/prometheus-operated   None         <none>        9090/TCP         9m
svc/sample-metrics-app    10.0.0.177   <none>        80/TCP           8m
svc/sample-metrics-prom   10.0.0.184   <nodes>       9090:30999/TCP   9m

NAME                                          DESIRED   CURRENT   AGE
statefulsets/prometheus-sample-metrics-prom   1         1         9m

NAME                         REFERENCE                       TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
hpa/sample-metrics-app-hpa   Deployment/sample-metrics-app   <unknown> / 100   2         10        2          8m

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/prometheus-operator   1         1         1            1           9m
deploy/sample-metrics-app    2         2         2            2           8m

NAME                                DESIRED   CURRENT   READY     AGE
rs/prometheus-operator-1303517395   1         1         1         9m
rs/sample-metrics-app-2206349241    2         2         2         8m
```

```
# kubectl get hpa.v2alpha1.autoscaling sample-metrics-app-hpa -o yaml
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2alpha1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"sample-metrics-app-hpa","namespace":"default"},"spec":{"maxReplicas":10,"metrics":[{"object":{"metricName":"http_requests_total","target":{"kind":"Service","name":"sample-metrics-app"},"targetValue":100},"type":"Object"}],"minReplicas":2,"scaleTargetRef":{"kind":"Deployment","name":"sample-metrics-app"}}}
  creationTimestamp: 2017-05-10T08:29:50Z
  name: sample-metrics-app-hpa
  namespace: default
  resourceVersion: "25672"
  selfLink: /apis/autoscaling/v2alpha1/namespaces/default/horizontalpodautoscalers/sample-metrics-app-hpa
  uid: d59e067f-355a-11e7-9933-0ef2c87c59d8
spec:
  maxReplicas: 10
  metrics:
  - object:
      metricName: http_requests_total
      target:
        kind: Service
        name: sample-metrics-app
      targetValue: "100"
    type: Object
  minReplicas: 2
  scaleTargetRef:
    kind: Deployment
    name: sample-metrics-app
status:
  currentMetrics: []
  currentReplicas: 2
  desiredReplicas: 0
```

**Comment by mdshuai** [comment] 2017-05-10 09:24
@DirectXMan12 @luxas

**Comment by DirectXMan12** [comment] 2017-05-10 15:15
Due to some refactors, things inadvertently broke the way the custom metrics client converts between Kinds and Resources.  https://github.com/kubernetes/kubernetes/pull/45384 should fix the issue (although there's a bit of cleanup to be done afterwards to use a discovery mapper instead of the "guess" mapping)

**Comment by luxas** [comment] 2017-05-10 19:42
@DirectXMan12 When did the regression occur? In which PR?

**Comment by DirectXMan12** [comment] 2017-05-10 20:06
@luxas I don't remember the exact PR.  It was part of the removal of the auto-install code, IIRC, somewhat recently.  I can try to dig it up if you want.

**Comment by luxas** [comment] 2017-05-10 20:11
@DirectXMan12 I just was curious since I recall I used a pretty recent version (alpha.2 maybe?) and had it working...

However, I'm more interested if we have any tests that cover the HPA v2.
If we don't, we probably should have ;)

**Comment by DirectXMan12** [comment] 2017-05-11 19:13
Yeah, we need e2e tests for that, I just need to figure out the best way do it (e.g. should we stand up the sample implementation from the custom-metrics-boilerplate repo?  Should we stand up the "test" HTTP server that is hardcoded to respond in a certain way, which might easily break if the client changes?)

**Comment by 23doors** [comment] 2017-05-23 18:07
Any news on that? Changes in custom metrics handling in 1.6 was one of the more anticipated ones for me and some poeple in my circle. But docs are still vague on this matter, at one point linking to what seems to be abandoned repo. And in general lacking an example of how metrics can be exposed now. Plus it seems that it is broken according to this issue?

**Comment by luxas** [comment] 2017-05-29 15:43
@23doors Please see https://github.com/luxas/kubeadm-workshop for a demo.
@DirectXMan12 et al. are working on making it even better and easily usable in v1.7

@DirectXMan12 we can close this issue right as https://github.com/kubernetes/kubernetes/pull/45384 was merged?

**Comment by 23doors** [comment] 2017-05-29 16:23
@luxas thanks. I guess I'll have to hold on until 1.7 then. Especially considering current API is not really stable and whole process is kind of cumbersome right now. 

My ideal scenario would be to make it so that:
* on each node, there is a process that based on pod spec - periodically gathers custom metrics from sources we defined. E.g. from file or http response (jsonpath). 
* HPA gathers all of that and based on current state of those metrics makes a decision about scaling.

Why not make it as simple as that? Prometheus, metrics apiservers, changing controller args and such seem just unnecessary. Full disclosure - I haven't looked up plans for metrics for 1.7, so maybe a flow that is just as simple is planned.

**Comment by luxas** [comment] 2017-05-29 16:33
It actually is very simple. The only thing you must do is to create an API endpoint that serves these requests: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/custom-metrics-api.md

Be it whatever. One YAML object for telling k8s where your service is, nothing more (in v1.7)

**Comment by 23doors** [comment] 2017-05-29 16:46
That sounds exactly what I am looking for. Thanks! I'll just make a workaround until 1.7 is released.

**Comment by luxas** [comment] 2017-05-29 16:58
Yes, the Prometheus thing is just a reference implementation. The YAML file to tell kube about your service requires [API Aggregation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/aggregated-api-servers.md) which is available in v1.7.0-alpha.3+ or so.

The YAML file can look like this: https://github.com/luxas/kubeadm-workshop/blob/master/demos/monitoring/custom-metrics.yaml#L110

**Comment by ngtuna** [comment] 2017-08-10 07:50
@luxas Hi I deployed `custom-metrics.yaml` file and it got error at that point and I have no clue to debug. Any idea is highly appreciated.

https://gist.github.com/ngtuna/9235afed0d6d14cdd0c7c6e00bb46e05

**Comment by DirectXMan12** [comment] 2017-08-15 18:41
this is not the place to ask for support.  Please try on StackOverflow, or, if you think there's a bug, in a new bug.

(since I'm already replying, I'll point you in the right direction: please read [the aggregated API server concepts documenation](https://github.com/kubernetes-incubator/apiserver-builder/tree/master/docs/concepts)).

**Comment by luxas** [comment] 2017-08-23 21:45
@DirectXMan12 is this still an issue?

**Comment by DirectXMan12** [comment] 2017-08-24 20:05
I think this is resolved.

**Closed** 2017-08-24 20:16 UTC
Labels: sig/autoscaling, sig/instrumentation
