### ISSUE TITLE
NFS PV is getting mounted then immediately unmounted, causing Kubernetes to fail to bring up pods

### ISSUE THREAD

**Issue by AmandaCameron** [kubernetes/kubernetes#20734] opened 2016-02-05 19:07 UTC
Kubelet seems to be having trouble mounting a NFS PV. The mount will briefly appear in the mount output, then immediatly (within 2s) disappear. This is causing some major headaches for me.

The only clue I can find is this:
I0205 19:00:24.904536   27673 nfs.go:157] NFS mount set up: /var/lib/kubelet/pods/8c73c65c-cc39-11e5-810b-5600001de9f9/volumes/kubernetes.io~nfs/maine-coon-keys false stat /var/lib/kubelet/pods/8c73c65c-cc39-11e5-810b-5600001de9f9/volumes/kubernetes.io~nfs/maine-coon-keys: no such file or directory

if I spam stat <path given> it'll stat, then disappear again, presumably when it gets unmounted.

I was told in the slack to cc @saad-ali so here it is.

**Comment by AmandaCameron** [comment] 2016-02-05 19:11
Upon scanning through with a different grep, it appears it's mounted, then immediatly called an orphan and unmounted.

**Comment by thockin** [comment] 2016-02-05 23:11
@rootfs also

**Comment by metral** [comment] 2016-02-10 05:24
I too am hitting this hiccup on v1.1.7.

I filed a similar issue on v1.1.3 a few months back https://github.com/kubernetes/kubernetes/issues/18749

**Comment by rootfs** [comment] 2016-02-10 13:38
@AmandaCameron what are your pod and pv/pvc like? i want to run it locally to reproduce this issue.

**Comment by rootfs** [comment] 2016-02-10 13:48
This looks similar to #18749

**Comment by metral** [comment] 2016-02-10 18:35
Agreed, like https://github.com/kubernetes/kubernetes/issues/18749, its orphaning + unmounting the disk on its own.

my PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mystore
    server: <IP_ADDR>
```

my PVC:

```
apiVersion: v1
metadata:
  name: my-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

My NFS server is nfsv4 running on an Ubuntu 14.04 distro with /etc/exports looking like such, where 192.168.1.100 is a K8s Node:

```
/mystore 192.168.1.100(rw,sync,no_root_squash,no_all_squash,no_subtree_check)
```

Mounting the NFS volume manually from other machines works fine and has no issues, but when NFS is used with PV+PVC I hit this orphaning issue all the time.

The pod hits this issue while instantiating per `kubectl describe`:
```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────   ──────          ───────
  5m            5m              1       {scheduler }                            Scheduled       Successfully assigned my-rc to 192.168.1.100
  5m            4s              33      {kubelet 192.168.1.100}                 FailedMount     Unable to mount volumes for pod "my-rc": exit status 32
  5m            4s              33      {kubelet 192.168.1.100}                 FailedSync      Error syncing pod, skipping: exit status 32
```

**Comment by rootfs** [comment] 2016-02-10 18:37
@kubernetes/goog-node

**Comment by rootfs** [comment] 2016-02-10 19:10
@metral I tested v1.1.7 code locally using your pv/pvc and my own pod, found no problem so far.

is it possible to post your pod?

**Comment by AmandaCameron** [comment] 2016-02-10 21:28
my PVC/PV are the same as above, the Pod is just the normal

```yaml
...
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
```

**Comment by rootfs** [comment] 2016-02-11 02:24
@yujuhong any idea about why orphanning doesn't skip live container?

**Comment by yujuhong** [comment] 2016-02-11 18:28
> @yujuhong any idea about why orphanning doesn't skip live container?

I think whether a container is live/running or not is irrelevant since the container in question hadn't been started yet.
From the code, the [cleanup function](https://github.com/kubernetes/kubernetes/blob/v1.1.7/pkg/kubelet/kubelet.go#L1577) gets a list of desired volumes and a list of actual volumes from the disk, then remove the undesired ones. The persistent volume must not have been in the desired list.

Oh I just found this #19600. Looks like this have been fixed in HEAD.

**Comment by yujuhong** [comment] 2016-02-11 18:29
Assigning to @saad-ali to see if the fix will be ported back to v1.1

**Comment by saad-ali** [comment] 2016-02-24 04:31
Created a cherry pick for #19600 (PR https://github.com/kubernetes/kubernetes/pull/21855). If there is another 1.1 release (v1.1.9), this fix will be in that release. Otherwise, it'll be in the v1.2 release.

**Comment by saad-ali** [comment] 2016-02-26 00:55
Cherry pick for 1.1 will be a pain (see PR #21855). Since the 1.2 branch is being cut soon, we'll hold off on the cherry pick.

**Closed** 2016-05-27 23:54 UTC
Labels: area/storage, team/cluster
