### ISSUE TITLE
ImageGCFailed, unable to delete images and reclaim disk.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#45558] opened 2017-05-09 18:52 UTC
**Kubernetes version**: 1.6.2 master and nodes
**Environment**: GKE
**What happened**: The following has been happening for the last week or two.

I noticed loads of pods being evicted with the following message from `kubectl describe`:
```
Node:		gke-prow-build-pool-a89df2af-4bc8/
Status:		Failed
Reason:		Evicted
Message:	The node was low on resource: nodefs.
```
The node shows ready but also that it has disk pressure from `kubectl get no`:
```yaml
status:
  conditions:
  - lastHeartbeatTime: 2017-05-09T17:38:33Z
    lastTransitionTime: 2017-05-09T15:43:02Z
    message: kubelet has disk pressure
    reason: KubeletHasDiskPressure
    status: "True"
    type: DiskPressure
  - lastHeartbeatTime: 2017-05-09T17:38:33Z
    lastTransitionTime: 2017-05-09T01:07:06Z
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
```
`kubectl describe no` shows lots of `ImageGCFailed`.
```
  FirstSeen	LastSeen	Count	From						SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----						-------------	--------	------			-------
  4h		19s		564	kubelet, gke-prow-build-pool-a89df2af-4bc8			Warning		EvictionThresholdMet	Attempting to reclaim nodefs
  4h		18s		54	kubelet, gke-prow-build-pool-a89df2af-4bc8			Warning		ImageGCFailed		(events with common reason combined)

```
Kubelet logs show that it's failing to delete the images and free up disk space. For each image it shows this every 10 seconds:
```
A  I0509 17:59:31.183907    1453 image_gc_manager.go:335] [imageGCManager]: Removing image "sha256:fa60023475d842a7a62d38fa27a0d3f6fd672be5ea1f09e6d07f8459d2c0c60a" to free 1105710474 bytes 
A  E0509 17:59:31.186643    1453 remote_image.go:124] RemoveImage "sha256:fa60023475d842a7a62d38fa27a0d3f6fd672be5ea1f09e6d07f8459d2c0c60a" from image service failed: rpc error: code = 2 desc = Error response from daemon: conflict: unable to delete fa60023475d8 (must be forced) - image is being used by stopped container 8641d5395d30 
A  E0509 17:59:31.186705    1453 kuberuntime_image.go:126] Remove image "sha256:fa60023475d842a7a62d38fa27a0d3f6fd672be5ea1f09e6d07f8459d2c0c60a" failed: rpc error: code = 2 desc = Error response from daemon: conflict: unable to delete fa60023475d8 (must be forced) - image is being used by stopped container 8641d5395d30 
```

**What you expected to happen**:

I would be happy if the node were marked unschedulable when it's out of disk. I would also be happy if the images successfully clean up. As it is, the node just evicts any pod that attempts to run on it.

**How to reproduce it**:

I don't know how to reproduce from scratch, but I've cordoned this node and can give access to someone for debugging.

Please let me know if you need more information, and apologies if this is a dupe.

cc @kubernetes/sig-node-bugs

**Comment by vishh** [comment] 2017-05-09 20:25
IIRC, there is a known bug around kubelet GC'ing unnecessarily. @dashpole did you post a fix for it and was it backported?

**Comment by dashpole** [comment] 2017-05-09 20:31
That was #44986, which dealt with evicting even if image garbage collection was partially successful.  It was backported to 1.6, but I am not sure if a release with it has been cut.

**Comment by dashpole** [comment] 2017-05-09 20:44
@vishh shouldn't we not be scheduling new pods to nodes with disk pressure?

**Comment by dashpole** [comment] 2017-05-09 20:51
It doesn't worry me that we fail to clean up images.  This happens whenever we try to clean up an image belonging to a terminated container, but could also be indicative of issues with docker, which is why we report it.  I am confused by two things:
1. Why are we scheduling new pods to the node that has disk pressure?
2. If we are evicting lots of pods, why are we unable to reduce disk pressure?

**Comment by dashpole** [comment] 2017-05-09 20:59
@spxtr do you see any "Failed to admit pod" messages in the kubelet logs?

**Comment by spxtr** [comment] 2017-05-09 21:03
Yes.
```
W0509 15:32:20.075156 1453 eviction_manager.go:128] Failed to admit pod ci-kubernetes-bazel-build-218730_test-pods(54dad7c2-34cc-11e7-bd29-42010a8000d0) - node has conditions: %v%!(EXTRA []v1.NodeConditionType=[DiskPressure])
```

**Comment by dashpole** [comment] 2017-05-10 00:51
#44986 was cherrypicked after 1.6.2 was cut, so it will be in 1.6.3.  But that still doesn't fully explain this behavior.

@spxtr  Do you see a bunch of `Ignoring node gke-prow-build-pool-a89df2af-4bc8 with DiskPressure condition status True` in the most recent portion of the kube-scheduler logs? 
Or do you instead see a bunch of `Scheduled` events to that node?  How often do you see each of these?

How many pods are currently scheduled to that node?

If there is something eating through all of the disk space on the node, what I expect to see is that the kubelet does image GC (possibly producing an event), and then evicts pods until it has successfully reduced disk pressure, while preventing pods from scheduling to it.  The most confusing piece is that `lastTransitionTime: 2017-05-09T15:43:02Z` was nearly 2 hours ago, at the time of your posting, meaning that despite all of the evictions, the kubelet is still unable to reduce disk pressure.

**Comment by dashpole** [comment] 2017-05-10 00:58
@vishh could this behavior be caused by critical pod admission ignoring disk pressure?  If a node daemon uses up all disk space a critical pod would still schedule to the node, but then be immediately evicted.

**Comment by spxtr** [comment] 2017-05-10 19:06
I recreated the nodes in order to start kubernetes tests running again. Once I see the issue show up again I'll cordon off one node and let you investigate manually.

At that point I'll probably downgrade to 1.4.9, since I never had this problem with that version.

**Comment by dashpole** [comment] 2017-05-10 19:51
ok, I just realized this was a test-infra issue.  I have access to the cluster now, so I'll be able to debug if it happens again

**Comment by dchen1107** [comment] 2017-05-10 20:07
@spxtr thanks for taking a quick action upon this test infrastructure issue. The failure blocks some of our critical validations. Thanks. @yguo0905

**Comment by yguo0905** [comment] 2017-05-11 16:37
@spxtr and @dashpole, looks like the problem happened again. https://k8s-testgrid.appspot.com/canonical-kubernetes#gce-ubuntu.

**Comment by spxtr** [comment] 2017-05-11 17:16
Yes, I'm going to cordon one of the nodes and then downgrade the rest to 1.4.9.

**Comment by dashpole** [comment] 2017-05-11 17:25
I am looking at one right now

**Comment by dashpole** [comment] 2017-05-11 17:30
let me know which one you cordon off

**Comment by spxtr** [comment] 2017-05-11 17:31
```bash
kubectl get no -ojson | jq -r '.items[] | select(.status.conditions[] | select(.status == "True") | select(.type == "DiskPressure")) | .metadata.name'
```
Lists nodes with disk pressure. There's probably a better way.

**Comment by dashpole** [comment] 2017-05-11 17:32
I am looking at one of them, and all of the disk usage is coming from var/docker/overlay.  I see ~150 containers, a couple using as much as 7G of space each

**Comment by spxtr** [comment] 2017-05-11 18:19
I'm not totally sure how it's supposed to work, but it looks like the kubelet isn't deleting any of the stopped containers.
```
$ docker ps -a | wc -l
86
```
Half of those 86 are pause containers, almost all of the rest are exited. For example:
```
19e52f1b3b37        7067922fad0e                               "/bin/bash /runner --"   21 hours ago        Exited (0) 21 hours ago                         k8s_ci-kubernetes-e2e-ubuntu-gke-1-6-200-0_ci-kubernetes-e2e-ubuntu-gke-1-6-200_test-pods_1a73a7d4-35c0-11e7-bd29-42010a8000d0_0
23ad954090fc        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 21 hours ago        Exited (137) 21 hours ago                       k8s_POD_ci-kubernetes-e2e-ubuntu-gke-1-6-200_test-pods_1a73a7d4-35c0-11e7-bd29-42010a8000d0_0
193d170f5683        fa60023475d8                               "/bin/bash /runner --"   21 hours ago        Exited (1) 21 hours ago                         k8s_pull-kubernetes-bazel-18800-0_pull-kubernetes-bazel-18800_test-pods_9a940f6e-35a7-11e7-bd29-42010a8000d0_0
07757c331a29        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 21 hours ago        Exited (0) 21 hours ago                         k8s_POD_pull-kubernetes-bazel-18800_test-pods_9a940f6e35a7-11e7-bd29-42010a8000d0_1
```
Then the log messages are clear. The eviction manager is trying to delete docker images to free up space, but that's failing because the images are still in use by these exited containers. I presume something else is supposed to be cleaning up dead containers?

I didn't have this problem with 1.4 nodes, and I'm testing out 1.5 right now.

**Comment by dashpole** [comment] 2017-05-11 18:22
Yeah, we are looking into possible issues with container garbage collection

**Comment by dashpole** [comment] 2017-05-12 01:33
Running the command: 
`kubectl get po --all-namespaces -a -ojson | jq -r '.items[] | select(.spec.nodeName == "NODE_NAME") | .metadata.name, .status.phase'`
shows all of the pods that are assigned to the node, and their phase.  On the nodes I looked at, about half of the pods run were failed.

The kubelet keeps the terminated containers around until the pod API object is deleted.  Currently, we dont automatically delete pods because logs are tied to the container.  We will (hopefully soon) be separating container logs from the actual container.  

I am not sure exactly why you havent experienced this problem before, as none of this behavior has changed recently.  Is it possible that your jobs are failing more often than before?  If pods continually fail and are recreated, this could leave behind a lot of dead containers, which would eat through disk space, until nothing else can be scheduled.

Curiously enough, none of the dead containers on the node belonged to evicted pods.  This is because we explicitly delete containers from evicted pods during the eviction process.

Running `docker ps -a` on the node revealed that a number of containers had exit status 137, which means that the containers were being OOM killed.  Might be worth looking into.

All considered, this is working as intended--although the intended functioning has some clear drawbacks that we plan to address.

One way to work around this for the time being would be to set up a separate job/script to delete pods periodically, if you do not care about inspecting the ones that fail.  That would at least keep you from running out of disk space.

**Comment by krzyzacy** [comment] 2017-05-12 02:03
+1

**Comment by vishh** [comment] 2017-05-12 02:28
> One way to work around this for the time being would be to set up a separate job/script to delete pods periodically, if you do not care about inspecting the ones that fail.

Dead containers should not be of any concern to users as long as kubelet can reliably garbage collect dead containers under disk pressure. Why is kubelet not performing GC in this scenario?
It's not clear why users have to run additional controllers to GC pods in-order for kubelet to keep the node up and running.

**Comment by spxtr** [comment] 2017-05-12 02:48
I delete pods older than a day already, and I opened a PR changing that to an hour. I agree with @vishh that I shouldn't have to GC so aggressively just to keep my cluster running.

Of all the non-pause containers left on the node, roughly 2/3 exited with (0) and 1/3 exited with a non-zero exit code. I'm not sure why the exit code is relevant. I'm also not sure why we haven't run into this before either, but I upgraded my nodes to 1.6 and saw it start happening that night. It *could* be a coincidence, since we are migrating new pod types to this cluster, but it feels unlikely.

**Comment by dashpole** [comment] 2017-05-12 05:26
> Why is kubelet not performing GC in this scenario?

What exactly do you mean?  The eviction manager does not garbage collect containers when under disk pressure, only images atm.  And the kubelet's general behavior is to garbage collect them only after a period of time, or if we hit one of the dead container limits (total dead containers, dead containers per container, etc...).  However, this doesnt prevent the scenario here, where we have lots of dead containers within the time period.

We could add garbage collection of all dead containers as a response to disk pressure as a possible solution.

**Comment by vishh** [comment] 2017-05-12 05:29
> We could add garbage collection of all dead containers as a response to disk pressure as a possible solution.

This is the bug. According to our current flag documentation, container GC is expected to be handled by eviction manager too (cc @derekwaynecarr )

**Comment by vishh** [comment] 2017-05-12 05:30
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L991

**Comment by dashpole** [comment] 2017-05-12 05:32
> I'm not sure why the exit code is relevant.

I was hypothesizing that you could be creating new pods at a faster rate if they were failing and had an onFailure restart policy.  Since pods disappear after a day, the amount of disk space used is equivalent to the space used by all pods scheduled to that node over the day.

**Comment by yujuhong** [comment] 2017-05-12 16:03
> Dead containers should not be of any concern to users as long as kubelet can reliably garbage collect dead containers under disk pressure. Why is kubelet not performing GC in this scenario?
> It's not clear why users have to run additional controllers to GC pods in-order for kubelet to keep the node up and running.

There is no reason why terminated pods should not be evicted under disk pressure. In fact, kubelet should prefer choosing them as victims so that it's less disruptive to the system. This is something that the eviction manager should handle, but I don't think it does today.

As to "why", I think @dashpole already said that this is a workaround.

> Of all the non-pause containers left on the node, roughly 2/3 exited with (0) and 1/3 exited with a non-zero exit code. I'm not sure why the exit code is relevant. I'm also not sure why we haven't run into this before either, but I upgraded my nodes to 1.6 and saw it start happening that night. It could be a coincidence, since we are migrating new pod types to this cluster, but it feels unlikely.

Off the top of my head, kubelet has always behaved like this. I am not sure why you didn't have problems with the older clusters, but it'd be hard to confirm this without running the same amount of workload in the clusters. As for the non-zero exit codes, they may not be relevant to this issue in question, but it could indicate other problems. If the containers were OOM killed, it probably implies that we should set better resource requirements for the pod so that we don't overcommit the nodes.

**Comment by spxtr** [comment] 2017-05-12 17:08
Okay, the fix in https://github.com/kubernetes/test-infra/pull/2736 fixed my cluster in just a couple minutes. Thanks @dashpole for troubleshooting. I can confirm that 1.5 nodes still have the problem, and so it seems it was just coincidence that it started to break the day after I upgraded to 1.6.

**Comment by dashpole** [comment] 2017-05-12 20:26
>https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L991
EDIT: We should be running container GC here.

@vishh do you mean we should delete all dead containers here?  Wouldn't that break our guarantees around preserving dead containers?

**Comment by vishh** [comment] 2017-05-12 20:50
> @vishh do you mean we should delete all dead containers here? Wouldn't that break our guarantees around preserving dead containers?

There are really no guarantees. Kubelet keeps dead containers on a best effort basis. Given that the old features that allowed managing dead containers explicitly can now be safely removed, I'd say we should update eviction manager to GC dead containers before even removing images.

**Comment by dashpole** [comment] 2017-05-12 21:46
> Given that the old features that allowed managing dead containers explicitly can now be safely removed

I didnt realize this was an "old" feature.  Are logs already stored separately from containers?  If so, then we should change the default settings to not keep old containers by default.  The eviction manager could be changed to trigger gc, but im not sure thats really necessary, given that container gc runs every 10 seconds.

**Comment by vishh** [comment] 2017-05-12 21:53
> Are logs already stored separately from containers? 

Not yet. But that doesn't matter. 

> given that container gc runs every 10 seconds

This logic should be removed once eviction manager takes over GC of containers.

**Comment by dashpole** [comment] 2017-05-12 22:11
Ok, that makes sense.  I'll try and implement this in the near future.

**Comment by yujuhong** [comment] 2017-05-12 22:19
> There are really no guarantees. Kubelet keeps dead containers on a best effort basis. Given that the old features that allowed managing dead containers explicitly can now be safely removed, I'd say we should update eviction manager to GC dead containers before even removing images.

Just making sure my understanding is correct --these containers will only be removed under disk pressure, right? We don't want to delete containers immediately after it terminates (yet).

**Comment by dashpole** [comment] 2017-05-12 22:22
Thats what I plan to implement.  Then after we have that working, we would remove the container gc logic all together.

**Comment by vishh** [comment] 2017-05-12 22:22
> Just making sure my understanding is correct --these containers will only be removed under disk pressure, right? 

Yes. That's what I'm hoping too.

**Comment by dashpole** [comment] 2017-06-01 01:16
PR, which I believe will make it in 1.7: https://github.com/kubernetes/kubernetes/pull/45896

**Comment by dashpole** [comment] 2017-06-06 16:29
#45896 has been merged, which should solve this issue.
/close

**Closed by dashpole** 2017-06-06 16:29 UTC
Labels: priority/failing-test, sig/node, sig/testing

**Comment by spxtr** [comment] 2017-06-06 16:48
Thanks again!
