### ISSUE TITLE
[Flake] [sig-cli] Kubectl client Kubectl server-side dry-run should check if kubectl can dry-run update Pods [Conformance]

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#95929] opened 2020-10-27 20:32 UTC
Started to fail continuosly on 10/22

![image](https://user-images.githubusercontent.com/6450081/97358734-f8513080-189b-11eb-9847-ec801f0baf36.png)

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cli%5C%5D%5C%20Kubectl%5C%20client%5C%20Kubectl%5C%20server%5C-side%5C%20dry%5C-run%5C%20should%5C%20check%5C%20if%5C%20kubectl%5C%20can%5C%20dry%5C-run%5C%20update%5C%20Pods%5C%20%5C%5BConformance%5C%5D

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 21 22:35:56.713: Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running /workspace/github.com/containerd/cri/kubernetes/platforms/linux/amd64/kubectl --server=https://34.82.182.130 --kubeconfig=/workspace/.kube/config --namespace=kubectl-6885 replace -f - --dry-run=server:\nCommand stdout:\n\nstderr:\nError from server (Conflict): error when replacing \"STDIN\": Operation cannot be fulfilled on pods \"e2e-test-httpd-pod\": the object has been modified; please apply your changes to the latest version and try again\n\nerror:\nexit status 1",
        },
        Code: 1,
    }
    error running /workspace/github.com/containerd/cri/kubernetes/platforms/linux/amd64/kubectl --server=https://34.82.182.130 --kubeconfig=/workspace/.kube/config --namespace=kubectl-6885 replace -f - --dry-run=server:
    Command stdout:
    
    stderr:
    Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on pods "e2e-test-httpd-pod": the object has been modified; please apply your changes to the latest version and try again
    
    error:
    exit status 1
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:592
```
#### Recent failures:
[10/23/2020, 9:34:41 PM ci-kubernetes-e2e-gci-gce-containerd](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-containerd/1319723868742488064)
[10/23/2020, 9:22:41 PM ci-cri-containerd-e2e-gci-gce](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce/1319720850726850560)
[10/23/2020, 9:20:41 PM ci-kubernetes-e2e-ubuntu-gce-containerd](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1319720345518739456)
[10/23/2020, 9:16:41 PM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1319719339800137728)
[10/23/2020, 8:40:44 PM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1319710280803946496)

/kind failing-test
/kind flake

/sig cli

**Comment by thejoycekung** [comment] 2020-10-28 02:07
dupe of #95832

/close

**Closed** 2020-10-28 02:07 UTC
Labels: kind/failing-test, kind/flake, needs-triage, sig/cli

**Comment by aojea** [comment] 2020-10-28 06:51
Ups, sorry, didn't notice there was one already open
Thanks
