### ISSUE TITLE
Alpha e2e failing due to monitoring bringup failures

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56854] opened 2017-12-05 16:07 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-instrumentation-bugs 

**What happened**:
Since at least the weekend, the alpha e2e suites have been intermittently failing because a few monitoring services failed to come up running.

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features

**Comment by x13n** [comment] 2017-12-06 10:42
This just happened again: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/17830

I managed to ssh into master machine before it was deleted and found this in event-exporter logs:
{"log":"F1206 10:30:32.309274       1 main.go:75] Failed to initialize sink: failed to build config: not running on GCE, which is not supported for Stackdriver sink\n","stream":"stderr","time":"2017-12-06T10:30:32.309578819Z"}

The machine didn't realize it is running on GCE which caused event-exporter to crashloop. I didn't have time to inspect anything else because the machine was deleted by e2e test.

**Comment by x13n** [comment] 2017-12-06 10:44
event-exporter is using complicated logic to detect this: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/event-exporter/vendor/cloud.google.com/go/compute/metadata/metadata.go#L191

**Comment by x13n** [comment] 2017-12-06 10:48
But event-exporter failure is probably a side effect of metadata-proxy failing as well.

**Comment by x13n** [comment] 2017-12-06 10:51
@ihmccreery Can you take a look?

**Comment by ihmccreery** [comment] 2017-12-13 19:50
@x13n What makes you think that the metadata proxy failed?

**Comment by x13n** [comment] 2017-12-14 08:46
I found it pending in some of the failed tests (e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/17970), together with others (e.g. event-exporter, as I wrote above). Now I checked other failures e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/17975 and the only failures there are for fluentd-gcp and kubernetes-dashboard, so the cause is probably elsewhere.

**Comment by serathius** [comment] 2018-01-19 12:10
I was able to reproduce problem. In my case monitoring services (fluentd and metrics-server) were not running, because CPU requests were over capacity. 
Looks like other monitoring services (heapster, event-exporter) where scheduled on master, inspite `SchedulingDisabled` node status. 
It was fixed after I deleted pods for those services, resulting in rescheduling them on other nodes.

**Comment by x13n** [comment] 2018-01-19 12:48
/unassign
/assign @serathius 

Reassigning, since @serathius is now working on this.

I guess the question now is why those pods ended up running on the master.

**Comment by x13n** [comment] 2018-01-19 12:51
Or not :) You need to join k8s org first...

**Comment by piosz** [comment] 2018-01-23 17:07
cc @bsalamat @davidopp

**Comment by serathius** [comment] 2018-01-24 17:05
Scheduler was ignoring Unschedulable nodes, so at cluster startup with no other node available, addons where scheduled on master. 
Fixed here https://github.com/kubernetes/kubernetes/issues/58648

**Comment by piosz** [comment] 2018-01-24 22:21
Thanks @serathius

**Closed by piosz** 2018-01-24 22:21 UTC
Labels: kind/bug, sig/instrumentation
