### ISSUE TITLE
Kubeadm inside docker container fails

### ISSUE THREAD

**Issue by andersla** [kubernetes/kubernetes#35712] opened 2016-10-27 18:08 UTC
## When trying to install Kubeadm inside Ubuntu 16.04 docker container it fails. 

BUG REPORT

**Kubernetes version** (use `kubectl version`):
latest

**Environment**:
Ubuntu 16.04 Docker container

**What happened**:
When trying to install Kubeadm inside Ubuntu 16.04 docker container it fails.
My Idea was to use one docker container as master "node" and a second container as a worker "node" (kubernetes in docker)
Is this a systemd issue? (something I came across when "googling" for answers)

Inside Ubuntu 16.04 docker image I install with : apt-get install -y kubeadm

setup log:

```
...
...
...
all: Setting up socat (1.7.3.1-1) ...
    all: Setting up kubelet (1.4.3-00) ...
    all: /var/lib/dpkg/info/kubelet.postinst: 38: /var/lib/dpkg/info/kubelet.postinst: [[: not found
    all: Setting up kubectl (1.4.3-00) ...
    all: Setting up kubeadm (1.5.0-alpha.0-1534-gcf7301f-00) ...
    all: Failed to connect to bus: No such file or directory
    **all: dpkg: error processing package kubeadm (--configure):**
    all: subprocess installed post-installation script returned error exit status 1
    all: Setting up netcat-traditional (1.10-41) ...
    all: update-alternatives: using /bin/nc.traditional to provide /bin/nc (nc) in auto mode
    all: Setting up netcat (1.10-41) ...
    all: Setting up patch (2.7.5-1) ...
    all: Setting up rename (0.20-4) ...
    all: update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
    all: Setting up tcpd (7.6.q-25) ...
    all: Setting up ubuntu-fan (0.9.1) ...
    all: invoke-rc.d: could not determine current runlevel
    all: invoke-rc.d: policy-rc.d denied execution of start.
    all: Setting up xz-utils (5.1.1alpha+20120614-2ubuntu2) ...
    all: update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
    all: Setting up python3 (3.5.1-3) ...
    all: running python rtupdate hooks for python3.5...
    all: running python post-rtupdate hooks for python3.5...
    all: Setting up apparmor (2.10.95-0ubuntu2.2) ...
    all: update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
    all: Setting up dh-python (2.20151103ubuntu1.1) ...
    all: Processing triggers for libc-bin (2.23-0ubuntu4) ...
    all: Processing triggers for systemd (229-4ubuntu11) ...
    all: Processing triggers for initramfs-tools (0.122ubuntu8.5) ...
    all: Processing triggers for dbus (1.10.6-1ubuntu3) ...
    all: Errors were encountered while processing:
    all: kubeadm
    all: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> all: Killing the container: 93babb5045461c343a803109ba683a2acf68f1f453447a336b09171a1b190f38
Build 'all' errored: Script exited with non-zero exit status: 100

==> Some builds didn't complete successfully and had errors:
--> all: Script exited with non-zero exit status: 100
```

**Comment by luxas** [comment] 2016-10-27 18:14
cc @errordeveloper and @marun since they have been running systemd inside a container

@andersla Be beware that running systemd this way inside a container is not supported ootb, but feel free to try it our/hack on it as it would be great for testing kubeadm that way

**Comment by zreigz** [comment] 2016-10-28 07:36
If you don't mind I would like take a look closer and try to fix it.

**Comment by andersla** [comment] 2016-10-28 08:48
@zreigz Please do!
This is how I try to install it:

`docker run -it --privileged ubuntu /bin/bash`

And then:

```
echo "Updating Ubuntu..."
apt-get update -y
apt-get upgrade -y

echo "Install os requirements"
apt-get install -y \
  curl \
  apt-transport-https \
  dialog \
  python \
  daemon

echo "Add Kubernetes repo..."
sh -c 'curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'
sh -c 'echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list'
apt-get update -y

echo "Installing Kubernetes requirements..."
apt-get install -y \
  docker.io \
  kubelet \
  kubernetes-cni \
  kubectl \
  kubeadm
```

**Comment by zreigz** [comment] 2016-10-28 09:10
I reproduced it and I have been working on this

**Comment by zreigz** [comment] 2016-10-31 07:24
There are two problems. 

The first one: `ll: /var/lib/dpkg/info/kubelet.postinst: 38: /var/lib/dpkg/info/kubelet.postinst: [[: not found` 
On Ubuntu systems, /bin/sh is dash, not bash, and dash does not support the double bracket keyword. Good thing is the issue is fixed on master branch and should be available soon: https://github.com/kubernetes/release/blob/master/debian/xenial/kubelet/debian/postinst#L40

The second one is not so trivial. Running systemctl in container fails with `Failed to get D-Bus connection`. It seems like systemd doesn't work properly in container. Now I am working on this

**Comment by andersla** [comment] 2016-10-31 07:42
Great!
I just don't see why installation of kubeadm need systemd/systemctl at all?

**Comment by zreigz** [comment] 2016-10-31 07:47
Because of those two lines: https://github.com/kubernetes/release/blob/master/debian/xenial/kubeadm/debian/postinst#L25

```
systemctl daemon-reload
systemctl restart kubelet
```

It fails on first line

**Comment by zreigz** [comment] 2016-10-31 07:48
this is the explanation:
```
# because kubeadm package adds kubelet drop-ins, we must daemon-reload
# and restart kubelet now. restarting kubelet is ok because kubelet
# postinst configure step auto-starts it.
```

**Comment by zreigz** [comment] 2016-10-31 07:52
There are some configuration steps to make it work but I have to try it first. If I find something I'll let you know.

**Comment by zreigz** [comment] 2016-11-02 07:19
Good news. I've managed solve all issues. It needs last tests and I will post solution how to run kubeadm in Docker container

**Comment by andersla** [comment] 2016-11-02 07:23
Super! I will help testing as soon as it is ready! - although I am on holidays the rest of his week:)

**Comment by zreigz** [comment] 2016-11-02 10:13
There are two main issues regarding installation kubeadm in Docker container. First is systemd running in container. Second is installation docker inside container. Successfully the problems were fixed. Here is the Dockerfile which must be used to prepare Ubuntu image

```
FROM ubuntu
ENV container docker
RUN apt-get -y update

RUN apt-get update -qq && apt-get install -qqy \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    vim \
    iptables
    
RUN curl -sSL https://get.docker.com/ | sh

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME /sys/fs/cgroup
VOLUME /var/run/docker.sock
CMD /sbin/init
```
I use this command to build the image in the directory containing the Dockerfile
```
docker build -t kubeadm_docker .
```

Now you can run prepared image and finish kubeadm installation.
Use the following command to run `kubeadm_docker` image:
```
docker run -it -e "container=docker" --privileged=true -d --security-opt seccomp:unconfined --cap-add=SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/run/docker.sock:/var/run/docker.sock  kubeadm_docker /sbin/init
```

Find running image ID

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
7dd73057620d        kubeadm_docker      "/sbin/init"        About an hour ago   Up About an hour                        furious_fermi

```

Now you can open container console:
```
docker exec -it 7dd73057620d /bin/bash
```
This is you script (with small modifications) to install kubeadm
```
echo "Updating Ubuntu..."
apt-get update -y
apt-get upgrade -y

systemctl start docker

echo "Install os requirements"
apt-get install -y \
  curl \
  apt-transport-https \
  dialog \
  python \
  daemon

echo "Add Kubernetes repo..."
sh -c 'curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'
sh -c 'echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list'
apt-get update -y

echo "Installing Kubernetes requirements..."
apt-get install -y \
  kubelet

# This is temporary fix until new version will be released
sed -i 38,40d /var/lib/dpkg/info/kubelet.postinst

apt-get install -y \
  kubernetes-cni \
  kubectl \
  kubeadm
```
And finally you can execute
```
# kubeadm init
```
Everything works the same like on local machine.
Good luck :)

**Comment by SuperStevenZ** [comment] 2016-11-17 06:45
@zreigz That solved the same problem of mine perfectly, thanks!

**Comment by SuperStevenZ** [comment] 2016-11-17 07:21
@zreigz That solved the same problem of mine, thanks!

**Comment by zreigz** [comment] 2016-11-17 07:30
No problem :)

**Comment by mikedanese** [comment] 2016-11-22 17:47
This issue was moved to kubernetes/kubeadm#17

**Closed by mikedanese** 2016-11-22 17:47 UTC
Labels: component/kubeadm

**Comment by keatz55** [comment] 2016-12-24 06:30
@zreigz Thanks!
