### ISSUE TITLE
e2e flake: Reboot [Disruptive] each node by ordering clean reboot and ensure they function upon restart

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#19190] opened 2015-12-30 08:29 UTC
This failed 4 times in the last 12 hours. Last failure:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-reboot/9748/

@kubernetes/goog-node

**Comment by gmarek** [comment] 2016-01-04 11:30
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-reboot/9990/

**Comment by dchen1107** [comment] 2016-01-12 01:12
This one has the same root cause of #19189:

14:52:38 Jan 11 14:52:38.142: INFO: monitoring-influxdb-grafana-v2-wpf4q          e2e-reboot-minion-31hq  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-01-11 14:51:51 -0800 PST ContainersNotReady containers with unready status: [influxdb]}]

Close it as dup of #19189.

**Closed** 2016-01-12 01:12 UTC
Labels: kind/flake, priority/P0, team/node
