### ISSUE TITLE
unit/integrations tests on per-PR builder are timing out

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18980] opened 2015-12-21 18:34 UTC
I'm not sure what happened, but our unit/integration tests started timing out recently (I mean build is timing out).

    I1221 17:31:43.944771    4488 genericapiserver.go:303] Node port range unspecified. Defaulting to 30000-32767.
    Build timed out (after 45 minutes). Marking the build as aborted.
    Build timed out (after 45 minutes). Marking the build as failed.
    FATAL: Unable to delete script file /tmp/hudson8166020313250965666.sh

An example failure:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/173718059d925d29c746b832c739058f10bbd1d6/kubernetes-pull-test-unit-integration/6967/?debugUI=DEVELOPERS

@kubernetes/goog-testing @ixdy @spxtr

**Comment by wojtek-t** [comment] 2015-12-21 18:34
Note that those tests are still working (i.e. these are not hanging forever tests - something is still working on them).

**Comment by ixdy** [comment] 2015-12-21 20:11
The unit tests have started taking much, much longer. From the run you linked, note the timestamps:
```
+++ [1221 17:03:39] Running tests without code coverage
...
+++ [1221 17:27:02] Saved JUnit XML test report to /workspace/artifacts/junit_v1,extensions-v1beta1_20151221-170339.xml
```

We haven't changed really changed anything on Jenkins - we still only run at most 3 unit/integration builds on a single VM. Maybe moving to Go 1.5 made things more heavyweight? Or maybe something changed about the VMs themselves?

**Comment by ixdy** [comment] 2015-12-21 20:19
post-submit Jenkins doesn't really have any CPU contention and is also running much slower:
```
+++ [1221 19:51:49] Running tests without code coverage
+++ [1221 20:09:53] Saved JUnit XML test report to /workspace/artifacts/junit_v1,extensions-v1beta1_20151221-195149.xml
```

Seems like something is wrong with our tests.

**Comment by wojtek-t** [comment] 2015-12-21 20:21
hmmm - also build is much much longer:

    +++ [1221 16:46:57] Building go targets for linux/amd64:
    ...
    +++ [1221 16:52:50] Placing binaries

It's strange - it's much faster than 6 minutes when I'm doing it locally...

**Comment by ixdy** [comment] 2015-12-21 20:23
I'll bump up the timeout on kubernetes-pull-test-unit-integration (again) - this time from 45m to 60m. We definitely need to track down this slowdown though.

**Comment by wojtek-t** [comment] 2015-12-22 14:40
hmm - I took a quick look into few random test outputs and it seems that the extremely long things are:
- building - up to 6-7 minutes
- hack/test-go - up to 25 minutes

However, I did some experiments and run:

1. what Jenkins is running:

        wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ make clean
        wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ hack/test-go.sh -- -p=2
It takes ~10 minutes on my machine

2. tests without parallel mode:

        wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ make clean
        wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ hack/test-go.sh
This takes ~3.5 minutes on my machine.

This means the latters is ~3x faster - to be honest this is extremely strange... - if we somehow fix it, it would be much better.
@ixdy - can you please take a look?

**Comment by ixdy** [comment] 2015-12-22 20:09
`-p=2` is limiting Go to using only 2 CPU cores, rather than the number available on the machine, so it makes sense that it's slower with that flag.

I think the limit comes from Travis and Shippable, where CPU is more constrained. We can probably try removing it or setting it to something higher and see if that helps.

**Comment by wojtek-t** [comment] 2015-12-22 21:54
ohh - I though that -p=2 is just causing to run up to 2 tests in parallel - not limiting the cpu usage.

**Comment by wojtek-t** [comment] 2015-12-28 10:31
This helped a lot!
I'm lowering the priority of it - @ixdy feel free to close if you think it doesn't make sense to investigate more...

**Comment by ixdy** [comment] 2015-12-28 18:10
I'll watch next week after the holidays when the PR flow picks up again...

**Comment by ihmccreery** [comment] 2016-01-21 23:29
@ixdy Can you please follow up on this, and close if it's no longer an issue?

**Comment by ixdy** [comment] 2016-01-21 23:30
The timeouts of unit/integration test runs seem to have gone away.

**Comment by ixdy** [comment] 2016-01-21 23:35
Actually, that's a lie. Two builds (kubernetes-pull-test-unit-integration/10243 and kubernetes-pull-test-unit-integration/10174) both failed in the last day. In both cases, they seemed to stop making any progress either in the middle of the kubectl or integration tests, printing nothing for 30-45m until they timed out.

I really have no idea what happened.

**Comment by ixdy** [comment] 2016-01-21 23:36
From kubernetes-pull-test-unit-integration/10243:
```
06:50:39 +++ [0121 14:50:39] Starting kubelet in masterless mode
06:50:40 I0121 14:50:40.106113   26091 plugins.go:71] No cloud provider specified.
06:50:40 I0121 14:50:40.107248   26091 manager.go:128] cAdvisor running in container: "/docker/f272d084744471521a91bb99b99ffe2a39622b65f817a3331da6e0745e510b23"
06:50:40 I0121 14:50:40.275194   26091 fs.go:105] Filesystem partitions: map[/dev/disk/by-uuid/e8292f07-3714-41a2-ae8e-4a059f383139:{mountpoint:/bin/docker major:8 minor:1 fsType: blockSize:0} /dev/sdb:{mountpoint:/workspace/artifacts major:8 minor:16 fsType: blockSize:0} /dev/sdc:{mountpoint:/etc/resolv.conf major:8 minor:32 fsType: blockSize:0}]
06:50:40 I0121 14:50:40.304586   26091 manager.go:163] Machine: {NumCores:32 CpuFrequency:2499998 MemoryCapacity:127006019584 MachineID:b0c468423c30475c9068e24f5d7ea7e9 SystemUUID:A4349E3A-E4AE-7AEE-C997-31D4CBCACDD4 BootID:d2c63cd8-e508-4fbc-a350-af64588311bc Filesystems:[{Device:/dev/sdb Capacity:1056759873536} {Device:/dev/sdc Capacity:211244736512} {Device:/dev/disk/by-uuid/e8292f07-3714-41a2-ae8e-4a059f383139 Capacity:10432602112}] DiskMap:map[8:16:{Name:sdb Major:8 Minor:16 Size:1073741824000 Scheduler:cfq} 8:32:{Name:sdc Major:8 Minor:32 Size:214748364800 Scheduler:cfq} 8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:cfq}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:02 Speed:10000 Mtu:1460}] Topology:[{Id:0 Memory:127006019584 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[2 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[4 5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[6 7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[8 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[10 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[12 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[14 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:8 Threads:[16 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[18 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[20 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:11 Threads:[22 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:12 Threads:[24 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:13 Threads:[26 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:14 Threads:[28 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:15 Threads:[30 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-32}
06:50:40 I0121 14:50:40.335255   26091 manager.go:169] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
06:50:40 W0121 14:50:40.337004   26091 server.go:317] failed to set oom_score_adj to -999: write /proc/self/oom_score_adj: permission denied
06:50:40 W0121 14:50:40.337070   26091 server.go:574] No api server defined - no events will be sent to API server.
06:50:40 W0121 14:50:40.337250   26091 iptables.go:142] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
06:50:40 I0121 14:50:40.338337   26091 plugins.go:56] Registering credential provider: .dockercfg
06:50:40 I0121 14:50:40.341051   26091 plugins.go:56] Registering credential provider: google-dockercfg
06:50:40 I0121 14:50:40.341547   26091 plugins.go:56] Registering credential provider: google-dockercfg-url
06:50:40 I0121 14:50:40.342127   26091 plugins.go:56] Registering credential provider: google-container-registry
06:50:40 I0121 14:50:40.342527   26091 server.go:608] Started kubelet
06:50:40 W0121 14:50:40.342720   26091 kubelet.go:930] No api server defined - no node status update will be sent.
06:50:40 I0121 14:50:40.343205   26091 server.go:103] Starting to listen on 127.0.0.1:10250
06:50:40 E0121 14:50:40.343314   26091 kubelet.go:867] Image garbage collection failed: unable to find data for container /
06:50:40 +++ [0121 14:50:40] On try 2, kubelet(masterless): ok
06:50:40 +++ [0121 14:50:40] Starting kubelet in masterful mode
07:38:13 Build timed out (after 60 minutes). Marking the build as aborted.
07:38:13 Build timed out (after 60 minutes). Marking the build as failed.
```

From kubernetes-pull-test-unit-integration/10174:
```
00:20:04.570 I0121 04:35:28.445123   32629 kubelet.go:2297] SyncLoop (RECONCILE, "api"): "phantom.baz_default(650d2d6d-bff8-11e5-b7ba-0242ac110002)"
00:20:04.571 I0121 04:35:28.445467   32629 replication_controller.go:200] No controllers found for pod phantom.baz, replication manager will avoid syncing
00:20:04.600 I0121 04:35:28.477140   32629 kubelet.go:2341] SyncLoop (housekeeping)
00:20:04.600 I0121 04:35:28.477629   32629 volumes.go:215] Making a volume.Cleaner for volume kubernetes.io~empty-dir/redis-data of pod 25d047f0dbbc4c0057d0b739dcf7e80b
00:20:04.601 I0121 04:35:28.477739   32629 volumes.go:251] Used volume plugin "kubernetes.io/empty-dir" for 25d047f0dbbc4c0057d0b739dcf7e80b/kubernetes.io~empty-dir
00:20:04.601 I0121 04:35:28.478932   32629 kubelet.go:2341] SyncLoop (housekeeping)
00:20:04.602 I0121 04:35:28.479190   32629 kubelet.go:2131] Killing unwanted pod "phantom.bar"
00:20:04.602 I0121 04:35:28.479289   32629 manager.go:1348] Killing container "/k8s_c1.cd1b02d5_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_5c9f48b2 /" with 30 second grace period
00:20:04.603 I0121 04:35:28.479328   32629 manager.go:1380] Container "/k8s_c1.cd1b02d5_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_5c9f48b2 /" exited after 18.415µs
00:20:04.603 W0121 04:35:28.479349   32629 manager.go:1386] No ref for pod '"/k8s_c1.cd1b02d5_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_5c9f48b2 /"'
00:20:04.603 I0121 04:35:28.479358   32629 volumes.go:215] Making a volume.Cleaner for volume kubernetes.io~empty-dir/redis-data of pod 25d047f0dbbc4c0057d0b739dcf7e80b
00:20:04.603 I0121 04:35:28.479384   32629 manager.go:1348] Killing container "/k8s_POD.6d140183_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_c9e202ff /" with 30 second grace period
00:20:04.604 I0121 04:35:28.479479   32629 manager.go:1380] Container "/k8s_POD.6d140183_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_c9e202ff /" exited after 10.656µs
00:20:04.604 W0121 04:35:28.479498   32629 manager.go:1386] No ref for pod '"/k8s_POD.6d140183_phantom.bar_default_641b41bd-bff8-11e5-b7ba-0242ac110002_c9e202ff /"'
00:20:04.605 I0121 04:35:28.479408   32629 volumes.go:251] Used volume plugin "kubernetes.io/empty-dir" for 25d047f0dbbc4c0057d0b739dcf7e80b/kubernetes.io~empty-dir
00:20:04.605 I0121 04:35:28.479683   32629 kubelet.go:1802] Orphaned pod "641b41bd-bff8-11e5-b7ba-0242ac110002" found, removing
00:20:04.606 I0121 04:35:28.484169   32629 config.go:265] Setting pods for source file
00:20:04.648 I0121 04:35:28.525728   32629 integration.go:943] Scheduler doesn't make phantom pods: test passed.
00:20:04.649 I0121 04:35:28.525873   32629 integration.go:1051] 
00:20:04.649 
00:20:04.649 Logging high latency metrics from the 10250 kubelet
00:20:04.667 I0121 04:35:28.544550   32629 server.go:1050] GET /metrics: (17.629031ms) 200 [[Go-http-client/1.1] 127.0.0.1:39600]
00:20:04.681 Jan 21 04:35:28.558: INFO: 
00:20:04.681 Latency metrics for node localhost:10250
00:20:04.681 Jan 21 04:35:28.558: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:4.179703s}
00:20:04.681 Jan 21 04:35:28.558: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:4.179703s}
00:20:04.681 Jan 21 04:35:28.558: INFO: {Operation:update Method:pod_worker_latency_microseconds Quantile:0.99 Latency:4.175833s}
00:20:04.681 Jan 21 04:35:28.558: INFO: {Operation:update Method:pod_worker_latency_microseconds Quantile:0.9 Latency:4.175833s}
00:20:04.682 I0121 04:35:28.558580   32629 integration.go:1053] 
00:20:04.682 
00:20:04.682 Logging high latency metrics from the 10251 kubelet
00:20:04.695 I0121 04:35:28.572190   32629 server.go:1050] GET /metrics: (12.737965ms) 200 [[Go-http-client/1.1] 127.0.0.1:35908]
00:20:04.707 Jan 21 04:35:28.584: INFO: 
00:20:04.707 Latency metrics for node localhost:10251
00:20:04.707 Jan 21 04:35:28.584: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:4.179703s}
00:20:04.707 Jan 21 04:35:28.584: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:4.179703s}
00:20:04.707 Jan 21 04:35:28.584: INFO: {Operation:update Method:pod_worker_latency_microseconds Quantile:0.9 Latency:4.175833s}
00:20:04.707 Jan 21 04:35:28.584: INFO: {Operation:update Method:pod_worker_latency_microseconds Quantile:0.99 Latency:4.175833s}
01:00:17.660 Build timed out (after 60 minutes). Marking the build as aborted.
```

**Comment by ihmccreery** [comment] 2016-01-22 18:52
@zmerlynn Can you have a look at this as part of our push to de-flake?

**Comment by zmerlynn** [comment] 2016-01-22 18:55
Sure.

**Comment by bprashanth** [comment] 2016-01-22 22:46
if you need another data point for the "unable to delete script file failure": http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/24795/consoleFull

**Comment by lavalamp** [comment] 2016-01-25 18:57
Mysterious timestamp gap in this:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/24774/consoleFull

```
11:54:25     cmd/genconversion
11:54:25     cmd/gendeepcopy
11:54:25     cmd/genswaggertypedocs
11:54:25     examples/k8petstore/web-server/src
11:54:25     github.com/onsi/ginkgo/ginkgo
11:54:25     test/e2e/e2e.test
12:22:17 +++ [0122 19:54:25] linux/amd64: go build started
12:22:17 +++ [0122 20:20:07] linux/amd64: go build finished
12:22:17 +++ [0122 19:54:25] linux/386: go build started
12:22:17 +++ [0122 20:22:17] linux/386: go build finished

...


12:44:27 ++ go run ./hack/e2e.go -v --down
12:44:28 2016/01/22 20:44:28 e2e.go:303: Running: teardown
12:44:28 Project: kubernetes-jenkins-pull
12:44:28 Zone: us-central1-f
12:44:28 Shutting down test cluster in background.
12:44:51 Build timed out (after 60 minutes). Marking the build as aborted.
12:44:51 Build timed out (after 60 minutes). Marking the build as failed.
12:44:51 FATAL: Unable to delete script file /tmp/hudson468857099179788081.sh
12:44:51 java.lang.InterruptedException
12:44:51 	at java.lang.Object.wait(Native Method)
12:44:51 	at hudson.remoting.Request.call(Request.java:147)
12:44:51 	at hudson.remoting.Channel.call(Channel.java:780)
12:44:51 	at hudson.FilePath.act(FilePath.java:979)
12:44:51 	at hudson.FilePath.act(FilePath.java:968)
12:44:51 	at hudson.FilePath.delete(FilePath.java:1422)
12:44:51 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:104)
12:44:51 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
12:44:51 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:44:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
12:44:51 	at hudson.model.Build$BuildExecution.build(Build.java:205)
12:44:51 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
12:44:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
12:44:51 	at hudson.model.Run.execute(Run.java:1738)
12:44:51 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:44:51 	at hudson.model.ResourceController.execute(ResourceController.java:98)
12:44:51 	at hudson.model.Executor.run(Executor.java:410)
12:44:51 Build was aborted
12:44:51 Recording test results
```

**Comment by ixdy** [comment] 2016-01-25 21:18
@lavalamp that one is for an e2e test run, so #13485. This issue is for timeouts on the unit/integration runs. :(

**Comment by ixdy** [comment] 2016-01-25 21:19
... though actually, that's entirely separate from either of these issues. The switch to go 1.5 has made builds weird and slow.

**Comment by ixdy** [comment] 2016-01-25 21:27
I think because builds are slower in 1.5 (and expected to be), we probably need to increase the # of Jenkins slaves and run fewer builds per slave.

**Comment by ihmccreery** [comment] 2016-01-25 22:09
> I think because builds are slower in 1.5 (and expected to be), we probably need to increase the # of Jenkins slaves and run fewer builds per slave.

@ixdy Can you own that and/or file a bug with `kind/flake` so we can track that as an action item?

**Comment by ixdy** [comment] 2016-01-26 01:20
Created https://github.com/kubernetes/kubernetes/issues/20133 regarding build slowness.

Until we can figure out how to deal with it, e2e and unit/integration tests are regularly going to time out, I'm afraid.

**Comment by ihmccreery** [comment] 2016-01-27 18:24
@ixdy Can we close this now that we have more Jenkins resources?

**Comment by bprashanth** [comment] 2016-03-08 04:31
I think this happened once again http://pr-test.k8s.io/22664/kubernetes-pull-test-unit-integration/17789/

I didn't dig too deep though, so there might've been a hanging daemon or something. Didn't look that way from build logs.

**Comment by ixdy** [comment] 2016-03-08 19:18
Looks like it got stuck after
```
+++ [0307 12:28:56] Starting kubelet in masterful mode
```

**Comment by bprashanth** [comment] 2016-03-08 19:21
That's a suspicious place to hang at, especially since the next run passed, but it's possible that there's a deadlock or something I guess. If the timings are accurate it just hung there for 30m.

**Comment by wojtek-t** [comment] 2016-03-09 14:43
If that's after:

    +++ [0307 12:28:56] Starting kubelet in masterful mode

Is it a dup of #21640 ?

**Comment by bprashanth** [comment] 2016-03-09 16:54
Likely so, closing for now as a dupe of #21640

**Closed by bprashanth** 2016-03-09 16:54 UTC
Labels: kind/flake, priority/P0, team/test-infra

**Comment by Random-Liu** [comment] 2016-04-05 02:02
Not sure whether this is the same issue: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23844/kubernetes-pull-test-unit-integration/20189/
