### ISSUE TITLE
maxSurge not accounting for terminating pods in rolling update 

### ISSUE THREAD

**Issue by chruss2** [kubernetes/kubernetes#95498] opened 2020-10-12 20:26 UTC
**What happened**:
When patching a deployment with 15 replicas and a rolling update strategy, it immediately put 3 pods in terminating status, and scheduled 7 new pods.  This is using the default settings for maxSurge and maxUnavailable of 25%.

**What you expected to happen**:
It should immediately put 3 pods in terminating status, and schedule 4 new pods (not 7).
* maxSurge = 25% rounds up to 4,
* maxUnavailable = 25% rounds down to 3.

Because the 3 terminating pods are still running and using resources, they should count towards the total number running, and the combined total size of the old and new replicasets should not exceed 15 + maxSurge = 19 pods.

**How to reproduce it (as minimally and precisely as possible)**:
I don't have a minimal test case on-hand, but it should be fairly easy to design a script that is slow to terminate (ours takes about 60 seconds between receiving the SIGTERM signal and actually exiting).

**Anything else we need to know?**:
We are using an HPA, so the 15 replicas is not hard-coded in the deployment.  But our cluster stabilized on 15 nodes before I ran the rolling update.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Google Cloud
- OS (e.g: `cat /etc/os-release`): MacOS Catalina 10.15.7
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.6.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by janetkuo** [comment] 2020-10-20 00:09
When the Deployment controller performs a rolling update on a Deployment, it scales up/down based on the `.spec.replicas` of the ReplicaSets it controls. When a ReplicaSet is scaled down, the ReplicaSet's `.spec.replicas` will be reduced and some of its Pods will be terminating, but the Deployment controller simply ignores terminating Pods when calculating maxSurge / maxUnavailable. 

Similarly, ReplicaSet controller ignores terminating Pods while doing operations, such as calculating its `.status.availableReplicas`:
https://github.com/kubernetes/kubernetes/blob/6f1288f58c2a810a33ac0cf990483aa601ddc61d/pkg/controller/replicaset/replica_set.go#L680-L681

**Comment by janetkuo** [comment] 2020-10-20 00:09
Closing, as this works as designed. Please feel free to reopen if there are still issues to be resolved.

**Closed by janetkuo** 2020-10-20 00:09 UTC
Labels: kind/bug, sig/apps, triage/accepted

**Comment by jalaziz** [comment] 2021-03-13 01:13
Would it make sense to add this behavior ot the docs? Variations of this issue have been brought up before in #97227 and #41596.

We also ran into this and it was a bit unexpected.

**Comment by timolehto** [comment] 2021-04-06 11:35
Yeah @janetkuo definitely this should be clarified as @jalaziz suggests...

If it even makes sense to have features like max surge/unavailable with this behaviour. I mean what's the point? If basically immediately when you make a deploy all old pods change their state to terminating then when exactly would the max surge settings and max unavailable settings be useful? I'm failing to see any point in them. I might be ignorant here, so please set me straight if I am. And if there is some point to them, then perhaps elaborate that too on the docs as well, because at least to me the obvious (and only?) use case one would have for these is precisely to control how fast to launch new pods in case your old pods take long to terminate.

**Comment by hiberabyss** [comment] 2021-08-17 13:51
> Yeah @janetkuo definitely this should be clarified as @jalaziz suggests...
> 
> If it even makes sense to have features like max surge/unavailable with this behaviour. I mean what's the point? If basically almost immediately when you make a deploy all old pods change their state to terminating then when exactly would the max surge settings and max unavailable settings be useful? I'm failing to see any point in them. I might be ignorant here, so please set me straight if I am. And if there is some point to them, then perhaps elaborate that too on the docs as well, because at least to me the obvious (and only?) use case one would have for these is precisely to control how fast to launch new pods in case your old pods take long to terminate.
> 
> P.S. Some background... in our particular we have 400 pods crunching away slow background jobs which could in the worst case take hours. We have set the termination grace period to 12h to give ample time for the pods to gracefully finish up their work. Typically after a deploy in a matter of 2-3 min the pod count skyrockets to 650+ drawing insane amount of resources from our cluster and then the pod count normalises gradually and in about 30 min 99% previous generation pods have terminated.

In my case, I only create one pod and would like the pod been terminated before new pod created, here the MaxSurge should also consider terminating pods.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-08-23 10:19
Yeah this behaviour is really confusing, needed to search google to find this issue

**Comment by haorenfsa** [comment] 2023-12-13 11:07
At least, maybe we should add a field like maxTerminating?
