### ISSUE TITLE
updatedAnnotations during rollback don't get applied

### ISSUE THREAD

**Issue by eruleman** [kubernetes/kubernetes#36851] opened 2016-11-15 23:45 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `updatedAnnotations`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5+5a0a696", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"not a git tree", BuildDate:"2016-10-29T08:29:14Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): `Linux node-0 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 Linux`
- **Install tools**: Custom
- **Others**: We have a deployment called `ladder`.

**What happened**:
```
eruleman@Erics-MacBook-Pro: ~/ladder/ladder (autorollback *)$ kubectl get deployment ladder -o yaml | grep test-annotation
    test-annotation: a
eruleman@Erics-MacBook-Pro: ~/ladder/ladder (autorollback *)$ curl -X POST https://kube-master/apis/extensions/v1beta1/namespaces/default/deployments/ladder/rollback -d '{"name":"ladder","updatedAnnotations":{"test-annotation":"6"},"rollbackTo":{"revision":6}}' -H "Content-Type: application/json"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "expected pointer, but got invalid kind",
  "code": 500
}
eruleman@Erics-MacBook-Pro: ~/ladder/ladder (autorollback *)$ kubectl get deployment ladder -o yaml | grep test-annotation
    test-annotation: "5"
eruleman@Erics-MacBook-Pro: ~/ladder/ladder (autorollback *)$ curl -X POST https://kube-master/apis/extensions/v1beta1/namespaces/default/deployments/ladder/rollback -d '{"name":"ladder","updatedAnnotations":{"test-annotation":"7"},"rollbackTo":{"revision":7}}' -H "Content-Type: application/json"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "expected pointer, but got invalid kind",
  "code": 500
}
eruleman@Erics-MacBook-Pro: ~/ladder/ladder (autorollback *)$ kubectl get deployment ladder -o yaml | grep test-annotation
    test-annotation: "6"
```

**What you expected to happen**:
We expect the updatedAnnotations to be applied to the new deployment. Instead, the updatedAnnotations are applied to the previous replica set.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else do we need to know**:

**Comment by bgrant0607** [comment] 2016-11-17 01:34
cc @kubernetes/deployment

**Comment by kargakis** [comment] 2016-11-18 11:22
Can't reproduce in master (works as expected). I suspect this was fixed in https://github.com/kubernetes/kubernetes/pull/35522.

**Closed** 2016-12-02 16:02 UTC
Labels: area/workload-api/deployment, kind/bug, team/workloads
