### ISSUE TITLE
e2e flake: [k8s.io] NoExecuteTaintManager [Serial] evicts pods from tainted nodes

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42682] opened 2017-03-07 23:00 UTC
The test is really flaky lately, for example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/757
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/758

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:189
Mar  7 04:34:07.792: Failed to evict Pod
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:185
```

cc/ @kubernetes/sig-scheduling-bugs @gmarek, can you help with triage?

**Comment by gmarek** [comment] 2017-03-08 08:59
Dupe of #42685

**Closed by gmarek** 2017-03-08 08:59 UTC
Labels: kind/flake, priority/critical-urgent, sig/scheduling
