### ISSUE TITLE
AWS: kube-down script didn't remove DHCP option set when delete VPC

### ISSUE THREAD

**Issue by c4po** [kubernetes/kubernetes#23869] opened 2016-04-05 13:42 UTC
kube-down script delete VPC, subnet and igw, but not delete the DHCP option set created in kube-up

**Comment by ajohnstone** [comment] 2016-04-09 23:24
duplicate of #24028 PR #24081

**Comment by justinsb** [comment] 2016-11-17 17:14
Closing as dup

**Closed by justinsb** 2016-11-17 17:14 UTC
Labels: area/platform/aws, team/sig-aws
