### ISSUE TITLE
Logs from components in timed-out runs are not gathered

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#35201] opened 2016-10-20 13:30 UTC
When some test suite is timing out, we don't have any logs. Examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-etcd3/4000/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-etcd3/4016/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-etcd3/4036/

If you look into artifacts/ directory in GCE for those, they don't have any logs.

This is making debugging issues like #35107 basically impossible.

@kubernetes/test-infra-maintainers @gmarek

**Comment by spxtr** [comment] 2016-10-20 16:50
It's a dupe of https://github.com/kubernetes/test-infra/issues/79. I was hoping that we can add a timeout to `bootstrap.py`, or else we should add a timeout to individual steps in `hack/e2e.go`.

**Closed** 2017-01-30 07:59 UTC
Labels: area/test-infra, priority/critical-urgent
