### ISSUE TITLE
[Failing Test]  Uses kubeadm/kinder to run kubeadm-e2e and e2e tests 

### ISSUE THREAD

**Issue by soggiest** [kubernetes/kubernetes#79668] opened 2019-07-02 16:39 UTC
**Which jobs are failing**:
ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master

**Which test(s) are failing**:
task-01-add-kubernetes-versions
task-11-reset
task-12-delete

**Since when has it been failing**:
07/02/2019 

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master

**Reason for failure**:
```
ime="15:40:04" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
Error: unknown cluster "kinder-upgrade"
 completed!
 # task-11-reset
kinder do kubeadm-reset --name=kinder-upgrade
 Error: a cluster with the name "kinder-upgrade" does not exists
 exit status 1
 # task-12-delete
kinder delete cluster --name=kinder-upgrade
 Error: unknown cluster "kinder-upgrade"
 exit status 1
 Ran 5 of 13 tasks in 0.000 seconds
FAIL! -- 2 tasks Passed | 3 Failed | 8 Skipped
 see junit-runner.xml and task logs files for more details
```

**Anything else we need to know**:
https://github.com/kubernetes/kubernetes/compare/6d8dd2111...a807cb625

/cc @kubernetes/sig-cluster-lifecycle
/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by neolit123** [comment] 2019-07-02 16:47
caused by missing files in GCS buckets:
https://kubernetes.slack.com/archives/C09QZ4DQB/p1562077303458500

/sig testing
/assign

**Comment by neolit123** [comment] 2019-07-03 19:19
after this merged the CI should stabilize:
https://github.com/kubernetes/release/pull/814
please check again tomorrow.

**Comment by justaugustus** [comment] 2019-07-05 15:19
This was caused by changes to the build/release tooling, which have since been reverted (https://github.com/kubernetes/release/pull/814).

Here is the first green run of the tests since the k/release revert:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1146506659837775872

Closing this out, but continued discussion on tooling/process improvement is happening here: https://github.com/kubernetes/release/issues/816
/close
/assign
/sig release

**Closed by justaugustus** 2019-07-05 15:19 UTC
Labels: kind/failing-test, priority/critical-urgent, sig/cluster-lifecycle, sig/release, sig/testing
