### ISSUE TITLE
Containerized cluster cannot mount default secrets

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#18239] opened 2015-12-04 23:18 UTC
When running a containerized kubernetes cluster I cannot spawn pods due to `file does not exist` errors when trying to mount their secret volumes:

```
$ kubectl create -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
EOF
pod "busybox-sleep" created
```

```
$ kubectl get pods
NAME                   READY     STATUS              RESTARTS   AGE
busybox-sleep          0/1       ContainerCreating   0          15s
k8s-master-127.0.0.1   3/3       Running             0          8m
```
```
$ kubectl describe pod busybox-sleep
Name:				busybox-sleep
Namespace:			default
Image(s):			busybox
Node:				127.0.0.1/127.0.0.1
Start Time:			Fri, 04 Dec 2015 22:48:56 +0000
Labels:				<none>
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  busybox:
    Container ID:	
    Image:		busybox
    Image ID:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-6dwl1:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-6dwl1
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Reason		Message
  ─────────	────────	─────	────			─────────────	──────		───────
  32s		32s		1	{scheduler }				Scheduled	Successfully assigned busybox-sleep to 127.0.0.1
  32s		10s		3	{kubelet 127.0.0.1}			FailedMount	Unable to mount volumes for pod "busybox-sleep_default": IsLikelyNotMountPoint("/var/lib/kubelet/pods/333c85c3-9ad9-11e5-aeed-f6b7b4d3b3d7/volumes/kubernetes.io~secret/default-token-6dwl1"): file does not exist
  32s		10s		3	{kubelet 127.0.0.1}			FailedSync	Error syncing pod, skipping: IsLikelyNotMountPoint("/var/lib/kubelet/pods/333c85c3-9ad9-11e5-aeed-f6b7b4d3b3d7/volumes/kubernetes.io~secret/default-token-6dwl1"): file does not exist
```

The secrets are there as expected:

```
$ kubectl get secrets
NAME                  TYPE                                  DATA      AGE
default-token-6dwl1   kubernetes.io/service-account-token   2         8m
```

Here are the full kubelet logs: https://gist.github.com/2opremio/6fcbae55d83f20bc3c82

The single-node containerized cluster is created using [this script](https://gist.github.com/2opremio/12eafc0c2485d8d13f2a), which is based on https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md and spawns a cluster based on a recent version of master (https://github.com/kubernetes/kubernetes/tree/81b6ac47557359429e519d889d9ad48b5c8a2411).

This is the docker version I am running:

```
$ docker info
Containers: 7
Images: 62
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: 77RC:MDFB:UNPM:62Z6:FYLF:TZTG:43NZ:77DD:IL22:QI6S:LDSV:UN6W
Debug mode (server): true
File Descriptors: 54
Goroutines: 90
System Time: 2015-12-04T23:01:25.308787463Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

The client runs in an OSX laptop and the daemon runs inside a VM provisioned with `docker-machine create --driver virtualbox --engine-storage-driver overlay default`

Surprisingly, everything works when using a vagrant VM provisioned with https://github.com/weaveworks/weave/blob/vagrant-pin-docker/Vagrantfile, so the problem must somehow be environmental but I haven't managed to triage the difference causing the problem.

**Comment by zmerlynn** [comment] 2015-12-05 03:59
cc @brendandburns

**Comment by 2opremio** [comment] 2015-12-05 12:17
I don't know if this is part of the cause, but the volume mountpoint basedirs in the host exist but are empty. For instance:

```
$ sudo find '/var/lib/kubelet/pods/cae566d6-9b48-11e5-bc44-f6b7b4d3b3d7/volumes/'
/var/lib/kubelet/pods/cae566d6-9b48-11e5-bc44-f6b7b4d3b3d7/volumes/
/var/lib/kubelet/pods/cae566d6-9b48-11e5-bc44-f6b7b4d3b3d7/volumes/kubernetes.io~secret
/var/lib/kubelet/pods/cae566d6-9b48-11e5-bc44-f6b7b4d3b3d7/volumes/kubernetes.io~secret/default-token-ixiqp
```

Whereas in the working VM:

```
$ sudo find '/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/'
/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/
/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/kubernetes.io~secret
/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/kubernetes.io~secret/default-token-uitlt
/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/kubernetes.io~secret/default-token-uitlt/token
/var/lib/kubelet/pods/32f06f64-9b49-11e5-9db4-0800279b9f1d/volumes/kubernetes.io~secret/default-token-uitlt/ca.crt
```

**Comment by dchen1107** [comment] 2015-12-08 00:12
cc/ @fgrzadkowski Is this the known issue for docker? Do we have a workaround for this?

**Comment by dchen1107** [comment] 2015-12-08 00:13
@fgrzadkowski I am going to assign this to you for the triage. Thanks!

**Comment by 2opremio** [comment] 2015-12-08 00:37
@dchen1107 https://github.com/kubernetes/kubernetes/issues/16055#issuecomment-150167990 indicates that the docker issue is worked-around in HEAD, which is from where this hyperkube container is built.

Furthermore, it only seems to fail in certain environments.

**Comment by 2opremio** [comment] 2015-12-14 14:55
@fgrzadkowski ping . Sorry to insist but this is blocking our local development and automatic tests.

**Comment by runseb** [comment] 2015-12-22 11:39
@2opremio did you manage to find a solution for this ?

**Comment by 2opremio** [comment] 2015-12-22 11:45
@runseb Unfortunately not

**Comment by runseb** [comment] 2015-12-22 11:48
@2opremio is there a version of the hyperkube image and docker for which it works ?

**Comment by 2opremio** [comment] 2015-12-22 11:57
As explained in the report above it does work in certain Vagrant VMs like https://github.com/weaveworks/weave/blob/vagrant-pin-docker/Vagrantfile using 2opremio/hyperkube:81b6ac4 , which is just hyperkube built from commit 816ac4 (you would probably get the same result building from master). See the [simplified version of the boot script I am using](https://gist.github.com/2opremio/12eafc0c2485d8d13f2a) for further details.

**Comment by runseb** [comment] 2015-12-22 12:20
I am running on a single node docker deployment, I tried with docker 1.8.3 and official hyperkube image 1.1.2 (trying now with 1.1.3 which was pushed yesterday). I am still at a loss to understand the issue.

**Comment by runseb** [comment] 2015-12-22 14:09
@2opremio so you got this to work on docker 1.8.3 with your image 2opremio/hyperkube:81b6ac4 ?

**Comment by runseb** [comment] 2015-12-22 14:23
related #16969 #13791 which have been merged

https://github.com/kubernetes/kubernetes/pull/16969
https://github.com/kubernetes/kubernetes/pull/13791

**Comment by 2opremio** [comment] 2015-12-22 17:55
yes

**Comment by huggsboson** [comment] 2015-12-30 21:27
@fgrzadkowski @runseb @2opremio I confirmed that kubernetes/kubernetes#19069 fixed my secret mounting issues in docker-machine.  I was using docker 1.9.1.

**Comment by fgrzadkowski** [comment] 2016-01-04 09:23
@huggsboson Lovely! I have a PR in-flight to release hyper-kube with every alpha release every 2 weeks (#19061)

**Comment by 2opremio** [comment] 2016-01-08 14:25
kubernetes#19069 does fix this for me too

**Comment by mikedanese** [comment] 2016-01-28 00:01
dup of #16055

**Closed by mikedanese** 2016-01-28 00:01 UTC
Labels: priority/P1, team/control-plane, team/node

**Comment by gopinatht** [comment] 2016-02-06 01:16
I already asked this in #19069 but wanted to ask here anyway as this is the exact problem I am facing:

Isn't this supposed to be fixed with docker version 1.10? I have docker version 1.10 and hyperkube version 1.2.0-alpha.7. Do I still need ncenter?

With these versions, what modificiations do I need for the single node containerized docker to get it to work (without ncenter): https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md

Any info appreciated.

**Comment by mikedanese** [comment] 2016-02-06 01:19
@gopinatht we have not updated to docker 1.2, it also requires changes on our side as well to use the new mount propagation apis. nsenter is still required until this work is done, but nsenter is a working substitue for now.

**Comment by gopinatht** [comment] 2016-02-07 18:34
@mikedanese Thanks for the explanation. Does this mean hyperkube itself needs to change? I thought the changes necessary were only the command line --volume parameters of docker run command to use the "shared/slave" option?

**Comment by mikedanese** [comment] 2016-02-07 18:48
@gopinatht ya you are correct for hyperkube running in a container, the example just needs to be updated to use the new -v flag. I was thinking about the case where kubelet runs in a static pod. For that we need to update the api to include some specification of mount propagation.

**Comment by gopinatht** [comment] 2016-02-08 18:18
Guys,

I would appreciate a bit of hand holding here. I tried changing the single node docker command (https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) like so:

`docker run \
    --restart=always \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:**shared** \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:**shared** \
    --volume=/var/run:/var/run:**shared** \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged=true --v=10`


Please not the **shared** mount propagation setting. When I do this, i get the error:

`docker: Error response from daemon: Cannot start container f7a5ae3d3e88b02ba42544ec768050717c942bc62889175171e6ebb3f89a1a6c: Path /var/run is mounted on /run but it is not a shared mount..`

I am trying to do this on a Unbutu trusty on a vagrant box. I am using docker version 1.10.0 and hyperkuber version v1.2.0-alpha.7.

What am I missing here? If I roll back the `shared` setting with the original `rw`, I get the error mentioned in this issue: `Unable to mount volumes for pod` with the `IsLikelyNotMountPoint` error.

If this is not the right forum for these questions, I would appreciate if someone could point me to the right forum.

**Comment by gopinatht** [comment] 2016-02-08 18:19
Please ignore the `**` in the command above. I was trying to emphasize it.

**Comment by gopinatht** [comment] 2016-02-12 02:26
Hey Guys, 

Thanks to @gravis in (https://github.com/openshift/origin/issues/3072), I think I figured it out (at least for the single node containerized kubernetes environment: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md). 

The steps I followed was:

```
mkdir -p /var/lib/kubelet
mount -o bind /var/lib/kubelet /var/lib/kubelet
mount --make-shared /var/lib/kubelet
```

and the the actual command

```
docker run \
    --restart=always \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:shared \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v${K8S_VERSION} \
    /hyperkube kubelet \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged=true --v=10
```

I am using kubernetes version **v1.2.0.alpha.7**. Also please note that in the main command, I added the **shared** mount and removed the "**containerized**" parameter. Also, I am using the latest version of Docker (1.10).

Hope this is useful to someone. I can submit a pull request for changing the documentation for the single node setup if others can validate that these steps work and are the right approach.

**Comment by bertrand-quenin** [comment] 2016-02-12 16:52
Thanks for sharing, I'm having the same issue. Going to test it ASAP

**Comment by 2opremio** [comment] 2016-02-12 17:47
@errordeveloper This will interest you.

**Comment by gopinatht** [comment] 2016-02-12 19:18
Guys,

I have now hit another issue, now that secrets/certificates are available from within a pod, the certificate itself has become a problem. It looks like the certificate is generated for the k8s API service like so: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/setup-files.sh#L35

`CERT_DIR=/data CERT_GROUP=kube-cert-test /make-ca-cert.sh $(hostname -i)`

However, the hostname -i is resolving to 127.0.1.1 for the API server (docker container). However, when we try to access the k8s API, say using kubectl with a command like this from within a pod:

`kubectl proxy -p 8080`, I get the following error message:

`Unable to connect to the server: x509: certificate is valid for 127.0.1.1, not 10.0.0.1`

It looks like generating the certificate for the API service is wrong (hostname -i). How can we work around this?

**Comment by luxas** [comment] 2016-02-12 19:21
This is a known issue... I can maybe send a patch in some days
More arguments are needed to `/make-ca-cert.sh`

**Comment by gopinatht** [comment] 2016-02-12 20:01
@luxas Thanks for the quick turnaround. Is there a bug logged around this (I could not find it)?

I wonder what the patch is you are thinking about. Would it be something like this?

`CERT_DIR=/data /make-ca-cert.sh $(hostname -I | awk '{print $1}')`

If so, I am not sure this will work in our scenario because the IP this will resolve to would be the IP of the container in which the API service is running (something like 10.0.2.15) and that is not the same as the master (10.0.0.1). Would there be a better way to generate the certificate to bind to the master?

**Comment by luxas** [comment] 2016-02-12 20:14
@gopinatht #18227

**Comment by huggsboson** [comment] 2016-03-11 20:26
With the :rw fix I'm seeing no errors on pod creation but the /var/run/secrets/kubernetes.io/serviceaccount/ is empty.  
I'm going to try the :ro fix with the mount commands @gopinatht mentioned above.

/ # ls -lah /var/run/secrets/kubernetes.io/serviceaccount/
total 4
drwxrwxrwx    2 root     root          40 Mar 11 18:55 .
drwxr-xr-x    3 root     root        4.0K Mar 11 18:55 ..

**Comment by huggsboson** [comment] 2016-03-11 20:35
When I do what @gopinatht suggested, /var/lib/kubelet:shared instead of /var/lib/kubelet:rw it actually mounts the secrets.

I still get this error when my pods start up even though the file exists, I assume it is another permissions issue:
1m		1m		1	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/mnt/sda1/var/lib/docker/containers/14e52ab6940db770a196020a45331073e1c77e0af58bdc7d94eb936a8634373a/resolv.conf\" does not exist"

**Comment by luxas** [comment] 2016-03-11 21:00
@huggsboson Try this: https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-194149162

**Comment by huggsboson** [comment] 2016-03-11 21:32
rshared starts up okay, and secrets get mounted, but I still get the message (before it even pulls images, cf6cb... is the docker container id for the /pause for busybox):
```
 9m		9m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned busybox to 127.0.0.1
  9m		9m		1	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/mnt/sda1/var/lib/docker/containers/cf6cb0949abaa72701cef450154b3807e7cbc72d1342372ecded61ad4f6f9b3a/resolv.conf\" does not exist"

  9m	9m	1	{kubelet 127.0.0.1}	spec.containers{busybox}	Normal	Pulling	pulling image "busybox"
```

**Comment by huggsboson** [comment] 2016-03-11 21:53
I've been using master.json to launch services inside kubelet.  I'm curious if I should be using master-multi.

**Comment by tdeheurles** [comment] 2016-03-11 22:09
the only difference between the two are from where you can access the cluster

**Comment by tdeheurles** [comment] 2016-03-11 22:12
Look [master](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/master.json) and [master-multi](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/master-multi.json)

The only difference is the `--insecure-bind-address`. In one you can only access in localhost, in the other from anywhere.

**Comment by huggsboson** [comment] 2016-03-11 22:14
it looks like master-multi (manifests-multi) also doesn't spin up an etcd for you:
[Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/Dockerfile)
