### ISSUE TITLE
e2e flake: trouble creating gke e2e clusters from head

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#23634] opened 2016-03-30 16:58 UTC
Both kubernetes-e2e-gke and kubernetes-e2e-gke-slow have had a couple failures to bring up a cluster this morning, seeing errors like:
Timed out waiting for cluster initialization. Cluster API may not be available.
All cluster resources were brought up, but the cluster API is reporting that component "scheduler" is unhealthy.

@jlowdermilk, does this overlap at all with the investigations you've been doing lately?

**Comment by a-robinson** [comment] 2016-03-30 17:00
@kubernetes/goog-gke

**Comment by jlowdermilk** [comment] 2016-03-30 20:31
It looks like both failures are symptoms of the same issue with docker -d that is currently being investigated. cc @dchen1107

**Comment by saad-ali** [comment] 2016-05-13 00:23
Happened again recently on gke and gke-slow around the same time:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/6796/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-slow/4097/

**Comment by roberthbailey** [comment] 2016-05-13 03:33
@maisem @andyzheng0831

**Comment by roberthbailey** [comment] 2016-05-13 03:39
In both of those failed builds the master VM never came up.

**Comment by andyzheng0831** [comment] 2016-05-13 03:48
Is there a way to ssh into the master instance?

**Comment by roberthbailey** [comment] 2016-05-13 03:55
The e2e framework tears it down right away, so it's long gone.

**Comment by andyzheng0831** [comment] 2016-05-13 04:02
I am not sure if it is related with docker. We received an issue report from a GCI customer recently saying that docker daemon fails to start upon instance bootup. The root cause is https://github.com/docker/docker/issues/18113. We had already cherry-picked the fix into GCI docker, but the image used in GKE does not have it. If docker daemon fails to start, I think master will not work.

**Comment by roberthbailey** [comment] 2016-05-13 04:06
Yeah, if docker isn't running then nothing much is going to happen.

**Comment by andyzheng0831** [comment] 2016-05-13 04:09
OK, I will raise the priority of internal issue for the log files. Solving that issue will make debug in future easier. Moreover, I will check-pick the docker patch into GCI-beta, which is the branch we reserve for GKE.

**Comment by andyzheng0831** [comment] 2016-05-18 19:35
I think the root cause is related with cAdvisor. The following events are shown repeatedly about skipping pod synchronization. Although /etc/kubernetes/manifests dir has all kube-system manifest, kubelet does not create any one.

kubelet.go:2499] skipping pod synchronization - [Failed to start cAdvisor open /sys/fs/cgroup/cpu,cpuacct/system.slice/systemd-hostnamed.service: no such file or directory]

@vishh , could you take a look what is wrong with cAdvisor. This issue happens with very low frequency. I guess it may be by some racing conditions.

**Comment by vishh** [comment] 2016-05-18 23:03
@andyzheng0831: cAdvisor has had several issues with systemd recently. We might have to ignore `systemd-hostnamed.service` file like `.mount` files are ignored [here](https://github.com/google/cadvisor/blob/master/container/systemd/factory.go#L42).

**Comment by andyzheng0831** [comment] 2016-05-18 23:07
I think so. Even for the normal kubelet on GCI, I still see logs about moving systemd-hostnamed containers, which looks not right (although it does not hurt functionality). Is there a systematical way to let cAdvisor ignore a certain set of system services?

**Comment by vishh** [comment] 2016-05-18 23:13
@andyzheng0831 We need first class support for systemd in cAdvisor. The way systemd uses cgroupfs is also a bit weird.

**Comment by johnbazan** [comment] 2016-09-23 12:18
Hello guys, how are you?

I'm experiencing the issue mentioned in this thread

Sometimes (I agree with the racing conditions theory) I see the following messages in the systemd service status

inotify_add_watch /sys/fs/cgroup/memory/system.slice/systemd-hostnamed.service: no such file or directory]
Sep 22 20:17:04 querymgr-queryws-0 kubelet[1069]: I0922 20:17:04.664344    1069 kubelet.go:2365] skipping pod synchronization - [Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/memory/system.slice/systemd-hostnamed.service: no such file or directory]
Sep 22 20:17:09 querymgr-queryws-0 kubelet[1069]: I0922 20:17:09.669617    1069 kubelet.go:2365] skipping pod synchronization - [Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/memory/system.slice/systemd-hostnamed.service: no such file or directory]
Sep 22 20:17:14 querymgr-queryws-0 kubelet[1069]: I0922 20:17:14.669816    1069 kubelet.go:2365] skipping pod synchronization - [Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/memory/system.slice/systemd-hostnamed.service: no such file or directory



Is there any workaround that I could use without changing the kubelet version?

Thanks a lot!

**Comment by roberthbailey** [comment] 2017-06-01 05:09
closing as obsolete.

**Closed by roberthbailey** 2017-06-01 05:09 UTC
Labels: needs-sig, priority/important-soon, team/gke
