### ISSUE TITLE
Amount of skydns pods does not scale with cluster needs

### ISSUE THREAD

**Issue by crunchie84** [kubernetes/kubernetes#28497] opened 2016-07-05 12:52 UTC
We are running kubernetes 1.2.4 on GKE. We observed that when we increased load on our system by 20% our outbound connections from our pods started to fail 80% of the time. After much diagnosing we found that our cluster was running with just one `kube-dns` pod. This pod was being hammered and resulted in failures to resolve DNS requests.

Our cluster started smaller (3x VM 8 core if i remember correctly) and is currently almost doubled in size/cores (10x VM 4 core).

Creating a new cluster in GKE of the same size gave us three `kube-dns` pods. My expectations would be that the amound of `kube-dns` pods would scale by load (using a HPA?) or that the pods would scale by cluster size (using deamonsets?). Not that the amound of `kube-dns` pods would be based on the initial cluster size when creating it in GKE.

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

NOTE: I do not know if this issue is superseded by the DNS changes discussed in #22823

**Comment by crunchie84** [comment] 2016-07-05 12:56
Note; our cluster started smaller (3x VM 8 core if i remember correctly) and is currently almost doubled in size/cores (10x VM 4 core)

**Comment by davidopp** [comment] 2016-07-19 08:41
cc/ @matchstick @thockin

**Comment by matchstick** [comment] 2016-07-19 15:58
So my current belief is that we are going to address this in 1.4 I believe this may be a duplicate of #28648.

**Comment by girishkalele** [comment] 2016-07-19 17:17
@crunchie84 

The current short term proposal is to simply scale the number of DNS pods by size of the cluster (disregarding whether they are 1 vCPU or 32 vCPU instances) but it is a start.

I have done some dns benchmarking to measure max QPS supported by a dns pod, so long term, we plan a load sensitive feedback loop to scale more precisely than the proposal above.

**Comment by kichik** [comment] 2016-08-03 19:14
We had the same issue. Below are the commands we used to resolve it, in case someone else gets this issue.
```!bash
$ kubectl --namespace kube-system scale get rc
NAME           DESIRED   CURRENT   AGE
kube-dns-v11   1         1         50d
$ kubectl --namespace kube-system scale --replicas 8 rc kube-dns-v11
replicationcontroller "kube-dns-v11" scaled
```

**Comment by girishkalele** [comment] 2016-08-03 19:52
See https://github.com/kubernetes/contrib/pull/1427 which will add auto scaling based on number of cores in the cluster.

**Comment by zilman** [comment] 2016-08-29 09:52
@girishkalele This doesn't appear to solve it fully. 
Besides the scalability issue seems there's an intermittent reliability bug.

[kube-dns-v19](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.sed) svc and rc taken from official repo.

```KUBE_PROXY_ARGS="--proxy-mode=iptables --masquerade-all=true"```

nslookup kubernetes.default from a brand new busybox pod outright hangs, sometimes completes slowly, and occasionally returns immediately. It also seemed completely reliable on a cluster with just one node. could it be the iptable rules aren't written on all the nodes correctly / simultaneously? 

```E0829 09:43:08.793042       1 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 10.40.0.2:53468->10.16.0.1:443: read: connection timed out```

```I0829 09:44:11.302477       1 logs.go:41] skydns: failure to forward request "read udp 10.40.0.2:55176->172.20.0.2:53: i/o timeout"```

Sadly makes no difference if I scale kubedns to 8 pods or 1.

**Comment by zilman** [comment] 2016-08-29 09:59
Just to clarify: ```nslookup servicename <podip>```
This is like a lottery. Some of them work some of the time, some hang, and it changes all the time.

**Comment by girishkalele** [comment] 2016-08-29 17:34
@zilman 

Questions on your logs:

If I am reading the logs correctly (what is streamwatcher.go ?) pod 10.40.0.2 attempted an https connection to 10.16.0.1 and the connection timed out ? Is 10.16.0.1 the API master ?

The failure to forward UDP to upstream 172.20.0.2:53 should not be for a lookup of kubernetes.default - local K8s services will not need to be forwarded to upstream DNS ?

If single node works reliably and multiple nodes do not, I would diagnose this as your cluster/overlay network having network connectivity issues perhaps ?

**Comment by zilman** [comment] 2016-08-29 17:55
@girishkalele 

I'm guessing: https://github.com/kubernetes/kubernetes/blob/master/pkg/watch/streamwatcher.go, not fluent in the k8s codebase yet. 

controller-manager, apiserver: ```--service-cluster-ip-range=10.16.0.0/12```
kubelet: ```--cluster-dns=10.16.0.10```
skydns-svc.yaml: ```clusterIP: 10.16.0.10```

10.40.0.2 <-- a kube_dns pod
10.16.0.1 <-- kubernetes.default
So this seems to make sense, right?  ```10.40.0.2:53468->10.16.0.1:443```

172.20.0.2 <-- wait a minute... that's the AWS VPC DNS server, interesting!

I added a dhcp option set, my domain name in this vpc is ```domain-name = us-west-2.compute.internal k8s``` -- could that be throwing it for a loop somehow?

**Comment by girishkalele** [comment] 2016-08-29 18:32
The DHCP domain-name option would probably make its way into the node's underlying resolv.conf that would be used for upstream resolution. Can you check the /etc/resolv.conf in the VMs ?

Also, the log line `10.40.0.2:53468->10.16.0.1:443` would mean that DNS lookup for kubernetes.local finished correctly, and the IP 10.16.0.1 was resolved but the TCP connection timed out.

**Comment by zilman** [comment] 2016-08-30 00:08
@girishkalele, quite right.

> search default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal k8s
nameserver 10.16.0.10
options ndots:5
<sub>/etc/resolv.conf on regular pod, I don't think the 'k8s' on the end impacts it, right?</sub>

I take back what I said about the single minion cluster, I just haven't tried it enough, it is reproducible no matter how many minions. If I repeat ```nslookup kubernetes.default.svc.cluster.local``` after responding instantly a few times it hangs, eventually returns, and start working normally again intermittently. 

>search us-west-2.compute.internal k8s
nameserver 172.20.0.2
options ndots:5
<sub>/etc/resolv.conf on kube_dns pod</sub>

Additionally: 

```
kubectl logs $pod --namespace=kube-system --container kubedns
I0829 20:19:21.696107       1 server.go:94] Using https://10.16.0.1:443 for kubernetes master, kubernetes API: <nil>
I0829 20:19:21.699491       1 server.go:99] v1.4.0-alpha.2.1652+c69e3d32a29cfa-dirty
I0829 20:19:21.699518       1 server.go:101] FLAG: --alsologtostderr="false"
I0829 20:19:21.699536       1 server.go:101] FLAG: --dns-port="10053"
I0829 20:19:21.699548       1 server.go:101] FLAG: --domain="cluster.local."
I0829 20:19:21.699554       1 server.go:101] FLAG: --federations=""
I0829 20:19:21.699560       1 server.go:101] FLAG: --healthz-port="8081"
I0829 20:19:21.699565       1 server.go:101] FLAG: --kube-master-url=""
I0829 20:19:21.699571       1 server.go:101] FLAG: --kubecfg-file=""
I0829 20:19:21.699577       1 server.go:101] FLAG: --log-backtrace-at=":0"
I0829 20:19:21.699584       1 server.go:101] FLAG: --log-dir=""
I0829 20:19:21.699600       1 server.go:101] FLAG: --log-flush-frequency="5s"
I0829 20:19:21.699607       1 server.go:101] FLAG: --logtostderr="true"
I0829 20:19:21.699613       1 server.go:101] FLAG: --stderrthreshold="2"
I0829 20:19:21.699618       1 server.go:101] FLAG: --v="0"
I0829 20:19:21.699622       1 server.go:101] FLAG: --version="false"
I0829 20:19:21.699629       1 server.go:101] FLAG: --vmodule=""
I0829 20:19:21.699681       1 server.go:138] Starting SkyDNS server. Listening on port:10053
I0829 20:19:21.699729       1 server.go:145] skydns: metrics enabled on : /metrics:
I0829 20:19:21.699751       1 dns.go:167] Waiting for service: default/kubernetes
I0829 20:19:21.700458       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0829 20:19:21.700474       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0829 20:19:26.691900       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:49468->172.20.0.2:53: i/o timeout"
I0829 20:19:38.691647       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:48080->172.20.0.2:53: i/o timeout"
I0829 20:19:43.697072       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:43631->172.20.0.2:53: i/o timeout"
I0829 20:19:48.702265       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:50563->172.20.0.2:53: i/o timeout"
I0829 20:19:51.700859       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://10.16.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.16.0.1:443: i/o timeout. Sleeping 1s before retrying.
E0829 20:19:51.701798       1 reflector.go:214] pkg/dns/dns.go:156: Failed to list *api.Service: Get https://10.16.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.16.0.1:443: i/o timeout
E0829 20:19:51.701860       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get https://10.16.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.16.0.1:443: i/o timeout
I0829 20:19:53.707635       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:42223->172.20.0.2:53: i/o timeout"
I0829 20:19:55.099736       1 server.go:107] Setting up Healthz Handler(/readiness, /cache) on port :8081
I0829 20:21:14.832910       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:44598->172.20.0.2:53: i/o timeout"```
```

I'm frankly at a loss..

**Comment by zilman** [comment] 2016-08-30 00:22
Aha! I figured it out! This is what the kubelet spews at exactly the same time I nslookup:

```


Aug 30 00:19:17 ip-172-20-0-12 kubelet[3008]: I0830 00:19:17.733349    3008 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/3e74b308-6e43-11e6-b92a-0a81cdea99a1-default-token-qbfsf" (spec.Name: "default-token-qbfsf") to pod "3e74b308-6e43-11e6-b92a-0a81cdea99a1" (UID: "3e74b308-6e43-11e6-b92a-0a81cdea99a1"). Volume is already mounted to pod, but remount was requested.
Aug 30 00:19:17 ip-172-20-0-12 kubelet[3008]: I0830 00:19:17.735260    3008 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/3e74b308-6e43-11e6-b92a-0a81cdea99a1-default-token-qbfsf" (spec.Name: "default-token-qbfsf") pod "3e74b308-6e43-11e6-b92a-0a81cdea99a1" (UID: "3e74b308-6e43-11e6-b92a-0a81cdea99a1").
Aug 30 00:19:26 ip-172-20-0-12 kubelet[3008]: I0830 00:19:26.755206    3008 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/b37ed838-6e46-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") to pod "b37ed838-6e46-11e6-b92a-0a81cdea99a1" (UID: "b37ed838-6e46-11e6-b92a-0a81cdea99a1"). Volume is already mounted to pod, but remount was requested.
Aug 30 00:19:26 ip-172-20-0-12 kubelet[3008]: I0830 00:19:26.757435    3008 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b37ed838-6e46-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") pod "b37ed838-6e46-11e6-b92a-0a81cdea99a1" (UID: "b37ed838-6e46-11e6-b92a-0a81cdea99a1").
Aug 30 00:19:27 ip-172-20-0-12 kubelet[3008]: I0830 00:19:27.578557    3008 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-202:1-17262586-pool
Aug 30 00:19:27 ip-172-20-0-12 kubelet[3008]: I0830 00:19:27.764875    3008 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/b37ee95e-6e46-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") to pod "b37ee95e-6e46-11e6-b92a-0a81cdea99a1" (UID: "b37ee95e-6e46-11e6-b92a-0a81cdea99a1"). Volume is already mounted to pod, but remount was requested.
Aug 30 00:19:27 ip-172-20-0-12 kubelet[3008]: I0830 00:19:27.766684    3008 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b37ee95e-6e46-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") pod "b37ee95e-6e46-11e6-b92a-0a81cdea99a1" (UID: "b37ee95e-6e46-11e6-b92a-0a81cdea99a1").
Aug 30 00:19:42 ip-172-20-0-12 kubelet[3008]: I0830 00:19:42.681845    3008 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-202:1-17262586-pool
Aug 30 00:19:45 ip-172-20-0-12 kubelet[3008]: I0830 00:19:45.819293    3008 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/3b379e01-6e45-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") to pod "3b379e01-6e45-11e6-b92a-0a81cdea99a1" (UID: "3b379e01-6e45-11e6-b92a-0a81cdea99a1"). Volume is already mounted to pod, but remount was requested.
Aug 30 00:19:45 ip-172-20-0-12 kubelet[3008]: I0830 00:19:45.821897    3008 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/3b379e01-6e45-11e6-b92a-0a81cdea99a1-default-token-qzct7" (spec.Name: "default-token-qzct7") pod "3b379e01-6e45-11e6-b92a-0a81cdea99a1" (UID: "3b379e01-6e45-11e6-b92a-0a81cdea99a1").
Aug 30 00:19:57 ip-172-20-0-12 kubelet[3008]: I0830 00:19:57.772950    3008 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-202:1-17262586-pool
```

It seems these are all the kube_dns pods having their secrets (needlessly, I might add) refreshed, which appears to be a blocking operation somehow that's a surprisingly long time. As soon as it finishes the dns query returns!

#29059

**Comment by thockin** [comment] 2016-08-30 00:34
What version kubelet?

**Comment by zilman** [comment] 2016-08-30 00:45
Here, I even recorded [a video of it](https://youtu.be/-sj0xJ6nE5Q). 
The performance varies but its really clear this is in sync.

```
kubelet --version
Kubernetes v1.3.5
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by girishkalele** [comment] 2016-08-30 02:54
@zilman That is quite strange - you mean that during the mountVolume, the kube-dns binary doesn't respond to DNS queries ? I assume this is a docker api call,  I wonder if it sends a SIGSTOP to all container processes while performing mount/unmount operations. Can you watch the process flags in ps to see what state the kube-dns binary is in ?

**Comment by thockin** [comment] 2016-08-30 06:27
I can't fathom how volumes would cause this, but @pmorie can speak to
whether the volume code is doing something unplanned here...

**Comment by pwittrock** [comment] 2016-09-08 01:13
@MrHohn @thockin @crunchie84 @girishkalele 

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by joeblackwaslike** [comment] 2016-09-08 05:38
I also had a similar problem with dns but eventually realized it only happened with udp packets.  I did some packet captures and it was an ip-masquerading issue.  

I was using flannel (older version from when i first installed kubernetes) and decided to look through some of the issues on the github and noticed alot of people with the exact same packet captures and also compared iptables rules with those listed in the issues and it was a match.  

The two things that helped the most were upgrading to the newer version of flannel and configuring flannel with docker correctly.  I believe this is something that the newer documentation addresses well but if you use flanneld for your networking you want to set it to do the ip-masquerading only, and disable ip-masq and iptables in your docker daemon.  I had configured it the exact opposite.  

There was one strange lingering issue remaining though, for any pod running with hostNetwork: true on the same host as the kube-dns pod, dns would break.  I tried increasing the replicas up to 3 in a 3 node cluster and with the kube-dns pods spread evenly dns was effectively broken on all of the nodes about 33% of the time (only when running hostNetwork: true).

I decided to try out calico and it works great, none of the problems I had with flanneld. :)

**Comment by zilman** [comment] 2016-09-08 16:00
@pwittrock @MrHohn @thockin @girishkalele

I've resolved the issue on my end. I think the mountVolume thing was reversed causality on my part, sorry for that. 

It ended up being the overlay (weave in my case), slightly misconfigured, wrongly interacting with the masquerade stuff in subtle ways. Joeblackwaslike provides a good overview and many others ran into similar problems and wrote elsewhere. Not a fun thing to debug.

I think more than anything its a documentation issue at this point and you possibly can close this.

**Comment by thockin** [comment] 2016-09-08 16:21
Thanks!!

**Closed by thockin** 2016-09-08 16:21 UTC
Labels: area/networking, priority/P1, team/cluster
