### ISSUE TITLE
kubelet.rpm 1.9.1 is not signed

### ISSUE THREAD

**Issue by den-is** [kubernetes/kubernetes#57873] opened 2018-01-05 06:13 UTC
/kind bug

**What happened**:
```
yum install kubelet
...
Package efde37cfcd34c8232daafb0337b8ba5fda70100ab6988fca71ba30ce929311dd-kubelet-1.9.1-0.x86_64.rpm is not signed
```
**What you expected to happen**:
Complete installation without errors

**How to reproduce it (as minimally and precisely as possible)**:
- get fresh centos 7.4 1708
- setup kubernetes repo
- try to install kubelet standalone or as dependency of kubeadm

**Environment**:
- Kubernetes version (use `kubectl version`): supposed to be 1.9.1
- Cloud provider or hardware configuration: VirtualBox
- OS (e.g. from /etc/os-release):  CentOS 7.4 1708 minimal setup with all updates at the moment of writing this
- Kernel (e.g. `uname -a`): Linux kubm1.dev 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Eddman** [comment] 2018-01-05 09:12
I can confirm that kublet-1.9.1 can't be installed. The only option is to use:
```
yum install --nogpgcheck kubelet
```

**Comment by SedjiG** [comment] 2018-01-05 14:51
Same issue: Package efde37cfcd34c8232daafb0337b8ba5fda70100ab6988fca71ba30ce929311dd-kubelet-1.9.1-0.x86_64.rpm is not signed

Eddman comment seems to work.
Thanks

**Comment by rushabh268** [comment] 2018-01-05 15:52
Seeing the same issue with 1.9.0 as well on a fresh install

**Comment by BernhardBerbuir** [comment] 2018-01-05 17:00
There is a extrem difference in size between 1.9.0 and 1.9.1:
```
yum info kubelet
Installed Packages
Name        : kubelet
Arch        : x86_64
Version     : 1.9.0
Release     : 0
Size        : **96 M**
Repo        : installed
From repo   : Kubernetes
Summary     : Container cluster management
URL         : https://kubernetes.io
License     : ASL 2.0
Description : The node agent of Kubernetes, the container cluster manager.

Available Packages
Name        : kubelet
Arch        : x86_64
Version     : 1.9.1
Release     : 0
Size        : **17 M**
Repo        : Kubernetes
Summary     : Container cluster management
URL         : https://kubernetes.io
License     : ASL 2.0
Description : The node agent of Kubernetes, the container cluster manager.
```
=> installing 1.9.1 might not be a good idea ...

**Comment by liggitt** [comment] 2018-01-05 17:14
Duplicate of https://github.com/kubernetes/kubernetes/issues/57855

**Comment by funky81** [comment] 2018-01-05 17:14
I have different size than yours...

yum info kubelet
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.angkasa.id
 * extras: centos.mirror.angkasa.id
 * updates: centos.mirror.angkasa.id
Installed Packages
Name        : kubelet
Arch        : x86_64
Version     : 1.9.1
Release     : 0
Size        : **96 M**
Repo        : installed
From repo   : kubernetes
Summary     : Container cluster management
URL         : https://kubernetes.io
License     : ASL 2.0
Description : The node agent of Kubernetes, the container cluster
            : manager.

**Closed by liggitt** 2018-01-05 17:14 UTC
Labels: kind/bug, needs-sig
