### ISSUE TITLE
eviction-hard setting doesnt prevent pods from being re-scheduled onto same node

### ISSUE THREAD

**Issue by dshulyak** [kubernetes/kubernetes#31778] opened 2016-08-31 12:11 UTC
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.2.1807+f80530c7f77e2f", GitCommit:"f80530c7f77e2fd272e6718b7d1754df0869d478", GitTreeState:"clean", BuildDate:"2016-08-29T12:08:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.2.1807+f80530c7f77e2f", GitCommit:"f80530c7f77e2fd272e6718b7d1754df0869d478", GitTreeState:"clean", BuildDate:"2016-08-29T12:03:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
2 kubelet nodes + 1 master, deployed by local vagrant provider

**What happened**:
While working on https://github.com/kubernetes/kubernetes/issues/31098 I added `--eviction-hard=memory.available<90%` to evict pets from node-1. It did its job and they were evicted, but after that pod was constantly re-scheduled onto same node.

**What you expected to happen**:
Expected that eviction-hard will prevent pod from being scheduled onto the same node, as long as evict condition is preserved.

**How to reproduce it** (as minimally and precisely as possible):
1. Create petset (i was using cockroachdb example)
2. Add `--eviction-hard=memory.available<90%` (or another condition which will evict pods from node)

I didn't try it with regular pods, so you may need to use my patch https://github.com/kubernetes/kubernetes/pull/31777

**Comment by dshulyak** [comment] 2016-09-01 11:52
@derekwaynecarr @vishh @dchen1107

**Comment by dshulyak** [comment] 2016-09-01 12:05
I have the following understanding of this problem:

- If node is under resource pressure - kubelet should not admit the pod, pod status Phase should be Failed and the Reason should be different from Evicted
- If so scheduler needs to be aware of this somehow and not re-schedule a pod onto the same node

I would appreciate if someone will confirm if this is the case? If so, i can work on a solution according to problem statement

**Comment by derekwaynecarr** [comment] 2016-09-01 12:38
For MemoryPressure, the Kubelet only rejects pods with BestEffort quality of service (ie pod that makes no memory or CPU request).  The same for scheduler.

For DiskPressure, Kubelet and scheduler will place no more pods on the node independent of QoS.

Can you provide the YAML output for the pod that was scheduled on the node so we can see its resource requirements?

**Comment by dshulyak** [comment] 2016-09-01 12:43
@derekwaynecarr sure, i was using this example https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-petset.yaml

**Comment by vishh** [comment] 2016-09-01 18:32
What @derekwaynecarr said! Rejection of new pods is based on the QoS class and guarantees of the resource.

**Comment by dshulyak** [comment] 2016-09-01 18:45
@vishh can you please point me to documentation on this topic or original discussion? I would say it is not a best behavior to re-schedule evicted pod onto same node

**Comment by dshulyak** [comment] 2016-09-01 18:51
also according to what @derekwaynecarr said pod that makes no memory request should be rejected by kubelet under MemoryPressure. This is exactly the case in mentioned example

**Comment by vishh** [comment] 2016-09-01 19:03
@dshulyak 

Pods with no requests or limits are classified as `BestEffort`. They will be rejected by kubelet when it is under `MemoryPressure`. Disk is already a best effort resource, since there existing no isolation for it yet. So kubelet rejects all pods irrespective of the QoS class when under disk pressure. 

How is an evicted pod different from any other new pod scheduled to the node? An evicted pod will get replaced by a new pod and there is no means for the system currently to track previous incarnations of a pod.
#12140 attempts to fix this.
Currently it is assumed that the eviction thresholds map to reserved resources. For example, if the memory eviction threshold is 100Mi, then the scheduler will not use those 100Mi for scheduling. Take a look at this [doc](http://kubernetes.io/docs/admin/out-of-resource/)
So in theory, a Burstable pod when rescheduled on to the same node that is under memory pressure will not be evicted again unless it happens to be using more memory than it originally requested consistently. 

If you suffer from overcommit issues consistently, consider setting up soft thresholds too in addition to hard thresholds. The assumption has been that the average utilization of resources on nodes is about 50 - 70%.

**Comment by vishh** [comment] 2016-09-01 19:05
@dshulyak are you expecting the system to reject burstable pods too?

**Comment by derekwaynecarr** [comment] 2016-09-03 02:13
Closing issue as this is working as designed.  Pod was burstable qos.

**Comment by dshulyak** [comment] 2016-09-03 05:38
I actually thought that it should be best effort qos. Is it burstable because of pvc storage request?

**Comment by dshulyak** [comment] 2016-09-06 13:40
@derekwaynecarr @vishh Are you sure that this should be closed? I can easily reproduce stated behavior with pod created with `kubectl run --image nginx my-pod`. The result of it is: 

```
[root@kubernetes-master ~]# kubectl get pods
NAME                      READY     STATUS              RESTARTS   AGE
my-pod-2887686308-3yal1   0/1       ContainerCreating   0          0s
  info: 25 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.
```

25 pods were evicted and then recreated

**Comment by derekwaynecarr** [comment] 2016-09-06 14:48
@dshulyak

**Comment by derekwaynecarr** [comment] 2016-09-06 14:50
@dshulyak -- can you do a `kubectl get pod -o yaml` for the pod that is rejected/created so we can see what the pod is after creation?  A LimitRange could be specifying default resource requirements.

**Comment by derekwaynecarr** [comment] 2016-09-06 21:47
Is this a duplicate of https://github.com/kubernetes/kubernetes/issues/31098?

**Comment by dshulyak** [comment] 2016-09-07 12:20
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"my-pod-2887686308","uid":"2169cfab-74f5-11e6-be44-0800277ad4a8","apiVersion":"extensions","resourceVersion":"188007"}}
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      my-pod'
  creationTimestamp: 2016-09-07T12:18:32Z
  generateName: my-pod-2887686308-
  labels:
    pod-template-hash: "2887686308"
    run: my-pod
  name: my-pod-2887686308-3x99a
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: my-pod-2887686308
    uid: 2169cfab-74f5-11e6-be44-0800277ad4a8
  resourceVersion: "188038"
  selfLink: /api/v1/namespaces/default/pods/my-pod-2887686308-3x99a
  uid: 31277ddf-74f5-11e6-be44-0800277ad4a8
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: my-pod
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-akryk
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: kubernetes-node-1
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-akryk
    secret:
      defaultMode: 420
      secretName: default-token-akryk
status:
  message: The node was low on memory.
  phase: Failed
  reason: Evicted
  startTime: 2016-09-07T12:18:32Z
```

**Comment by dshulyak** [comment] 2016-09-07 12:59
I see that cpu: 100m was added, which makes this pod burstable. But maybe it is possible to introduce qos per each resource type? E.g this pod will be cpu burstable, but memory besteffort? and we can block scheduling of this pod until MemoryPressure will be come False

**Comment by derekwaynecarr** [comment] 2016-09-07 14:11
@dshulyak - the original design for QOS was per resource per container.  We changed it in 1.3 to per pod for a few reasons a) easier to understand as a user, b) aligns with unified cgroup hierarchy direction in cgroups API, c) aligns with pod level cgroup proposal.

**Comment by derekwaynecarr** [comment] 2016-09-07 14:11
closing the issue as the resource had Burstable QOS, eviction worked as designed.

**Closed by derekwaynecarr** 2016-09-07 14:11 UTC
Labels: component/kubelet, team/control-plane
