### ISSUE TITLE
Return HTTP 410 for recently deleted resources

### ISSUE THREAD

**Issue by sym3tri** [kubernetes/kubernetes#7670] opened 2015-05-02 00:46 UTC
Is it reasonable to return `410 Gone` HTTP errors for recently deleted resources? Given the amount of Pod churn in the cluster with replication controllers etc could be quite high, it would be nice to know (at least for a reasonable amount of time afterwards) that a resource did once exist but is now gone.

**Comment by smarterclayton** [comment] 2017-06-01 17:25
Dupe of #1468

**Closed by smarterclayton** 2017-06-01 17:25 UTC
Labels: area/usability, priority/awaiting-more-evidence, sig/api-machinery
