### ISSUE TITLE
unversioned client unit test TestBackoffLifecycle failed

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#21739] opened 2016-02-23 09:25 UTC
I met this in #21349.
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/15730/testReport/junit/

This test should have nothing to do with kubelet, so it seems to be a flake.

**Comment by lavalamp** [comment] 2016-02-23 18:54
@Random-Liu Please link to the externally available logs when filing these: https://cloud.google.com/console/storage/kubernetes-jenkins/pr-logs/pull/21349/kubernetes-pull-test-unit-integration/15730/

(under the "Google Cloud Storage Upload Report")

**Comment by lavalamp** [comment] 2016-02-23 18:56
Also, it's helpful to include the logs of the failed test:

```
--- FAIL: TestBackoffLifecycle (6.55s)
	request_test.go:753: Attempt 1
	request_test.go:778: 0 finished in 1.634567ms
	request_test.go:753: Attempt 2
	request_test.go:778: 1 finished in 4.614486009s
	request_test.go:753: Attempt 3
	request_test.go:778: 2 finished in 1.93424377s
	request_test.go:780: 1.93424377s not in range 2
```

**Comment by lavalamp** [comment] 2016-02-23 19:00
This code/test should probably be changed to use a Clock: https://github.com/kubernetes/kubernetes/blob/e62cf38fa932c1357fe0848de60559aaf3f73a95/pkg/util/clock.go#L26

**Comment by lavalamp** [comment] 2016-02-23 19:06
Yeah, the problem is attempt 1 took much longer than expected, so attempt 2 did not need to wait so long (I guess). I think this can be fixed by the test just setting and using a fake clock in the backoff object.

**Comment by lavalamp** [comment] 2016-02-23 19:07
@jayunit100 this is your baby, right? Can you fix this?

**Comment by jayunit100** [comment] 2016-02-23 19:20
sure, just saw this

**Comment by Random-Liu** [comment] 2016-02-23 19:22
@lavalamp Thanks a lot! I will do better next time, :)

**Comment by jayunit100** [comment] 2016-02-24 18:21
@Random-Liu  ok ive put a patch up that should solve the flakiness without making the `request.go` unnecessarily complicated.   thanks for reporting.

**Comment by Random-Liu** [comment] 2016-02-24 19:12
@jayunit100 Thanks for the patch! Feel free to close this after the patch is merged. :)

**Closed** 2016-02-25 00:26 UTC
Labels: component/clientlib, kind/flake, team/CSI-API Machinery SIG
