### ISSUE TITLE
[Failing Test]  CSI Mock volume storage capacity storage capacity unlimited

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [kubernetes/kubernetes#125547] opened 2024-06-17 13:37 UTC
### Which jobs are failing?

master-informing
gce-master-scale-correctness

```
CSI Mock volume storage capacity storage capacity unlimited
```

### Which tests are failing?

```
Kubernetes e2e suite: [It] [sig-storage] CSI Mock volume storage capacity storage capacity unlimited expand_less | 40s
-- | --
{ failed [FAILED] while waiting for all CSI calls: error waiting for expected CSI calls: Unexpected CSI call 0: expected CreateVolume (0), got DeleteVolume (0) In [It] at: k8s.io/kubernetes/test/e2e/storage/csimock/csi_storage_capacity.go:196 @ 06/16/24 17:45:57.515 }
```

Looks like there's an extra Worker Node running when it's not supposed to, or at least not scheduled to.

```
Detected 5000 ready nodes, found 5001 nodes out of expected 5001. Your cluster may not be fully functional.
```

### Since when has it been failing?

It looks like failures started on 4/18/2024, but they may have been deemed flakes until now as it's now happening every day.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Anything else we need to know?

On k8s-triage, I'm also seeing this error tied to a storage issue. It may be because there's an extra Worker Node running when there's not supposed to be, so there isn't enough storage availab.e

```
[TIMEDOUT] A node timeout occurred
In [It] at: k8s.io/kubernetes/test/e2e/storage/csimock/csi_storage_capacity.go:323 @ 05/31/24 19:00:20.242

This is the Progress Report generated when the node timeout occurred:
  [sig-storage] CSI Mock volume storage capacity CSIStorageCapacity CSIStorageCapacity used, no capacity (Spec Runtime: 5m0.092s)
    k8s.io/kubernetes/test/e2e/storage/csimock/csi_storage_capacity.go:323
    In [It] (Node Runtime: 5m0.001s)
      k8s.io/kubernetes/test/e2e/storage/csimock/csi_storage_capacity.go:323
      At [By Step] deploying csi mock driver (Step Runtime: 4m59.937s)
        k8s.io/kubernetes/test/e2e/storage/drivers/csi.go:558
```

### Relevant SIG(s)

/sig scalability

**Comment by Vyom-Yadav** [comment] 2024-06-17 14:21
Duplicate of https://github.com/kubernetes/kubernetes/issues/125539

/close

**Closed by Vyom-Yadav** 2024-06-17 14:21 UTC
Labels: sig/scalability, kind/failing-test, needs-triage
