### ISSUE TITLE
debug kubectl with goland got an panic

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#90431] opened 2020-04-24 03:49 UTC
**What happened**:
```
runtime: unexpected return pc for k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.BasicPod.Generate called from 0xc0005fefa8
stack: frame={sp:0xc0005fe988, fp:0xc0005fef30} stack=[0xc0005f8000,0xc000600000)
000000c0005fe888:  000000000043c022 <runtime.panicmem+98>  000000c0005fe938 
000000c0005fe898:  9165f0c0fb379244  4c4d7a122e2697a5 
000000c0005fe8a8:  1bd405cc31b5b4cd  7be3cac7e3b63f4c 
000000c0005fe8b8:  0000000000411753 <runtime.mapiterinit+179>  00000000c009e502 
000000c0005fe8c8:  000000000044047a <runtime.main+442>  000000c00004c000 
000000c0005fe8d8:  0000000000000000  000000c000040060 
000000c0005fe8e8:  0000000000000000  0000000000000000 
000000c0005fe8f8:  0000000002117780  000000000370b2d0 
000000c0005fe908:  0000000000000000  0000000000000000 
000000c0005fe918:  0000000000000000  0000000000000000 
000000c0005fe928:  000000c0005fe948  000000000043c022 <runtime.panicmem+98> 
000000c0005fe938:  0000000002117780  000000000370b2d0 
000000c0005fe948:  000000c0005fe978  0000000000453d0e <runtime.sigpanic+126> 
000000c0005fe958:  000000c00004c000  000000c00006bc01 
000000c0005fe968:  000000c000106120  000000c00004c000 
000000c0005fe978:  000000c0005fef28  0000000001b9426f <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.BasicPod.Generate+1455> 
000000c0005fe988: <0000000000000001  000000c0005f6000 
000000c0005fe998:  000000000231ec85  0000000000000005 
000000c0005fe9a8:  000000c0005f6000  0000000000000000 
000000c0005fe9b8:  0000000000000000  0000000000000000 
000000c0005fe9c8:  000000c00039a0c0  000000c0003d2020 
000000c0005fe9d8:  0000000000000000  00000000020a0380 
000000c0005fe9e8:  000000c0003d2020  0000000000000000 
000000c0005fe9f8:  000000000014c901  000000c0005f6000 
000000c0005fea08:  000000c0005f6030  000000000040e661 <runtime.mallocgc+849> 
000000c0005fea18:  0000000000000000  0000000000000000 
000000c0005fea28:  000000c000000000  000000c0005f6030 
000000c0005fea38:  0000000000000001  0000000000000018 
000000c0005fea48:  0000000000000000  0000000000000040 
000000c0005fea58:  000000c000770000  000000c0000340e0 
000000c0005fea68:  0000000000000005  0000000002403f80 
000000c0005fea78:  000000c000580000  0000000000140108 
000000c0005fea88:  0000000000000000  0000000000000000 
000000c0005fea98:  0000000000000000  000000c0005e0b30 
000000c0005feaa8:  0000000000418f77 <runtime.heapBitsForAddr+71>  000000c0000340e0 
000000c0005feab8:  0000000000000005  0000000000000000 
000000c0005feac8:  0000000000000000  000000000375ad20 
000000c0005fead8:  0000000000000000  0000000000000000 
000000c0005feae8:  000000000375ad20  0000000000000000 
000000c0005feaf8:  0000000000000000  0000000000000001 
000000c0005feb08:  0000000000000040  000000c000770000 
000000c0005feb18:  000000000375ad20  0000000000000000 
000000c0005feb28:  0000000000000000  000000000375ad20 
000000c0005feb38:  0000000000000000  0000000000000000 
000000c0005feb48:  00000000020a0380  000000c0005e0b98 
000000c0005feb58:  00000000020a0380  000000c0003d2020 
000000c0005feb68:  0000000000000098  0203000000000000 
000000c0005feb78:  00000000001bffff  000000c0005e0bc8 
000000c0005feb88:  0000000000000098  00000000004bfc36 <reflect.ValueOf+118> 
000000c0005feb98:  00000000020a0380  000000c0003d2020 
000000c0005feba8:  000000000040429d <runtime.ifaceeq+77>  00000000022e0380 
000000c0005febb8:  0000000000000001  000000000467ffff 
000000c0005febc8:  000000c0005e0c58  0000000000418f77 <runtime.heapBitsForAddr+71> 
000000c0005febd8:  00000000020a0380  000000c0003d2020 
000000c0005febe8:  0000000002404200  000000c0005e0df8 
000000c0005febf8:  00000000004a5613 <reflect.DeepEqual+803>  00000000020a0380 
000000c0005fec08:  000000c00039a0c0  0000000000000098 
000000c0005fec18:  00000000020a0380  000000c0003d2020 
000000c0005fec28:  0000000000000098  000000c0005e0cb0 
000000c0005fec38:  0000000000000000  0000000000000000 
000000c0005fec48:  000000000467ffff  000000c0005e0cb0 
000000c0005fec58:  000000c0005e0cb0  00000000026e6ac0 
000000c0005fec68:  00000000020a0380  00000000026e6ac0 
000000c0005fec78:  00000000020a0380  00000000020a0380 
000000c0005fec88:  000000c0003d2020  0000000000000098 
000000c0005fec98:  00000000020a0380  000000c00039a0c0 
000000c0005feca8:  0000000000000098  0000000000000000 
000000c0005fecb8:  9ef5712800000000  000000c0005e0ce0 
000000c0005fecc8:  0000000000000000  000000000043ed39 <runtime.asyncPreempt2+105> 
000000c0005fecd8:  0000000002404178  000000c00004c000 
000000c0005fece8:  000000c0005e0e70  000000000047157b <runtime.asyncPreempt+219> 
000000c0005fecf8:  0000000000000006  0000000000000011 
000000c0005fed08:  000000c000529900  0000000000000012 
000000c0005fed18:  0000000000000010  000000c0005e0900 
000000c0005fed28:  00000000001be901  0000000000000044 
000000c0005fed38:  000000000467b902  0000000000000000 
000000c0005fed48:  0000000002030001  0000000000000000 
000000c0005fed58:  0000000000000018  000000c000580058 
000000c0005fed68:  0000000000000000  0000000000000000 
000000c0005fed78:  0000000000000000  0000000000000000 
000000c0005fed88:  0000000000000000  0000000000000000 
000000c0005fed98:  0000000000000000  0000000000000000 
000000c0005feda8:  0000000000000000  0000000000000000 
000000c0005fedb8:  0000000000000000  0000000000000000 
000000c0005fedc8:  000000c00015e420  000000c00015e450 
000000c0005fedd8:  000000c00015e4e0  000000c00015e4b0 
000000c0005fede8:  000000c000004320  000000c0000042c0 
000000c0005fedf8:  000000c000106030  000000000043ed39 <runtime.asyncPreempt2+105> 
000000c0005fee08:  0000000002404178  000000c00004c000 
000000c0005fee18:  000000c0005e0fa0  000000000047157b <runtime.asyncPreempt+219> 
000000c0005fee28:  0000000001ba7ec0 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.(*BasicPod).Generate+0>  000000c0006c1890 
000000c0005fee38:  0000000002133600  00000000009cb22b <k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/errors.NewAggregate+683> 
000000c0005fee48:  0000000000000000  0000000000000000 
000000c0005fee58:  00000000001be901  0000000000000044 
000000c0005fee68:  000000000467b902  0000000000000000 
000000c0005fee78:  0000000002030001  0000000000000000 
000000c0005fee88:  0000000000000018  000000c000580058 
000000c0005fee98:  0000000000000000  0000000000000000 
000000c0005feea8:  0000000000000000  0000000000000000 
000000c0005feeb8:  0000000000000000  0000000000000000 
000000c0005feec8:  0000000000000000  0000000000000000 
000000c0005feed8:  0000000000000000  0000000000000000 
000000c0005feee8:  0000000000000000  0000000000000000 
000000c0005feef8:  000000c00015e420  000000c00015e450 
000000c0005fef08:  000000c00015e4e0  000000c00015e4b0 
000000c0005fef18:  000000c000004320  000000c0000042c0 
000000c0005fef28: !000000c0005fefa8 >0000000001ba7f46 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.(*BasicPod).Generate+134> 
000000c0005fef38:  000000c0006c1890  0000000000000000 
000000c0005fef48:  0000000000000000  0000000000000000 
000000c0005fef58:  0000000000000000  000000c00006bdd0 
000000c0005fef68:  0000000000000000  0000000000000000 
000000c0005fef78:  0000000000000000  0000000000000000 
000000c0005fef88:  000000c000106120  000000c0001060c0 
000000c0005fef98:  0000000000000246  000000c0005e1258 
000000c0005fefa8:  000000c0005ff258  0000000001cb7a74 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/run.(*RunOptions).createGeneratedObject+292> 
000000c0005fefb8:  000000000375ad20  000000c0006c1890 
000000c0005fefc8:  0000000000000000  0000000000000000 
000000c0005fefd8:  0000000000000000  0000000000000000 
000000c0005fefe8:  000000000000000b  000000c0005e1028 
000000c0005feff8:  0000000000418203 <runtime.typedmemmove+67>  0000000000000000 
000000c0005ff008:  0000000000000000  0000000000000000 
000000c0005ff018:  0000000000000000  00000000020a0380 
000000c0005ff028:  000000000375bf40 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x232fd43, 0x11)
	C:/Go/src/runtime/panic.go:1114 +0x79
runtime.gentraceback(0x43c022, 0xc0005fe938, 0x0, 0xc00004c000, 0x0, 0x0, 0x7fffffff, 0x343efef8, 0x0, 0x0, ...)
	C:/Go/src/runtime/traceback.go:273 +0x1a4e
runtime.addOneOpenDeferFrame.func1()
	C:/Go/src/runtime/panic.go:719 +0x98
runtime.systemstack(0x0)
	C:/Go/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	C:/Go/src/runtime/proc.go:1041

goroutine 1 [running]:
runtime.systemstack_switch()
	C:/Go/src/runtime/asm_amd64.s:330 fp=0xc0005fe840 sp=0xc0005fe838 pc=0x46da60
runtime.addOneOpenDeferFrame(0xc00004c000, 0x43c022, 0xc0005fe938)
	C:/Go/src/runtime/panic.go:718 +0x82 fp=0xc0005fe880 sp=0xc0005fe840 pc=0x43cf52
panic(0x2117780, 0x370b2d0)
	C:/Go/src/runtime/panic.go:927 +0x11d fp=0xc0005fe938 sp=0xc0005fe880 pc=0x43d63d
runtime.panicmem()
	C:/Go/src/runtime/panic.go:212 +0x62 fp=0xc0005fe958 sp=0xc0005fe938 pc=0x43c022
runtime.sigpanic()
	C:/Go/src/runtime/signal_windows.go:246 +0x7e fp=0xc0005fe988 sp=0xc0005fe958 pc=0x453d0e
runtime: unexpected return pc for k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.BasicPod.Generate called from 0xc0005fefa8
stack: frame={sp:0xc0005fe988, fp:0xc0005fef30} stack=[0xc0005f8000,0xc000600000)
000000c0005fe888:  000000000043c022 <runtime.panicmem+98>  000000c0005fe938 
000000c0005fe898:  9165f0c0fb379244  4c4d7a122e2697a5 
000000c0005fe8a8:  1bd405cc31b5b4cd  7be3cac7e3b63f4c 
000000c0005fe8b8:  0000000000411753 <runtime.mapiterinit+179>  00000000c009e502 
000000c0005fe8c8:  000000000044047a <runtime.main+442>  000000c00004c000 
000000c0005fe8d8:  0000000000000000  000000c000040060 
000000c0005fe8e8:  0000000000000000  0000000000000000 
000000c0005fe8f8:  0000000002117780  000000000370b2d0 
000000c0005fe908:  0000000000000000  0000000000000000 
000000c0005fe918:  0000000000000000  0000000000000000 
000000c0005fe928:  000000c0005fe948  000000000043c022 <runtime.panicmem+98> 
000000c0005fe938:  0000000002117780  000000000370b2d0 
000000c0005fe948:  000000c0005fe978  0000000000453d0e <runtime.sigpanic+126> 
000000c0005fe958:  000000c00004c000  000000c00006bc01 
000000c0005fe968:  000000c000106120  000000c00004c000 
000000c0005fe978:  000000c0005fef28  0000000001b9426f <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.BasicPod.Generate+1455> 
000000c0005fe988: <0000000000000001  000000c0005f6000 
000000c0005fe998:  000000000231ec85  0000000000000005 
000000c0005fe9a8:  000000c0005f6000  0000000000000000 
000000c0005fe9b8:  0000000000000000  0000000000000000 
000000c0005fe9c8:  000000c00039a0c0  000000c0003d2020 
000000c0005fe9d8:  0000000000000000  00000000020a0380 
000000c0005fe9e8:  000000c0003d2020  0000000000000000 
000000c0005fe9f8:  000000000014c901  000000c0005f6000 
000000c0005fea08:  000000c0005f6030  000000000040e661 <runtime.mallocgc+849> 
000000c0005fea18:  0000000000000000  0000000000000000 
000000c0005fea28:  000000c000000000  000000c0005f6030 
000000c0005fea38:  0000000000000001  0000000000000018 
000000c0005fea48:  0000000000000000  0000000000000040 
000000c0005fea58:  000000c000770000  000000c0000340e0 
000000c0005fea68:  0000000000000005  0000000002403f80 
000000c0005fea78:  000000c000580000  0000000000140108 
000000c0005fea88:  0000000000000000  0000000000000000 
000000c0005fea98:  0000000000000000  000000c0005e0b30 
000000c0005feaa8:  0000000000418f77 <runtime.heapBitsForAddr+71>  000000c0000340e0 
000000c0005feab8:  0000000000000005  0000000000000000 
000000c0005feac8:  0000000000000000  000000000375ad20 
000000c0005fead8:  0000000000000000  0000000000000000 
000000c0005feae8:  000000000375ad20  0000000000000000 
000000c0005feaf8:  0000000000000000  0000000000000001 
000000c0005feb08:  0000000000000040  000000c000770000 
000000c0005feb18:  000000000375ad20  0000000000000000 
000000c0005feb28:  0000000000000000  000000000375ad20 
000000c0005feb38:  0000000000000000  0000000000000000 
000000c0005feb48:  00000000020a0380  000000c0005e0b98 
000000c0005feb58:  00000000020a0380  000000c0003d2020 
000000c0005feb68:  0000000000000098  0203000000000000 
000000c0005feb78:  00000000001bffff  000000c0005e0bc8 
000000c0005feb88:  0000000000000098  00000000004bfc36 <reflect.ValueOf+118> 
000000c0005feb98:  00000000020a0380  000000c0003d2020 
000000c0005feba8:  000000000040429d <runtime.ifaceeq+77>  00000000022e0380 
000000c0005febb8:  0000000000000001  000000000467ffff 
000000c0005febc8:  000000c0005e0c58  0000000000418f77 <runtime.heapBitsForAddr+71> 
000000c0005febd8:  00000000020a0380  000000c0003d2020 
000000c0005febe8:  0000000002404200  000000c0005e0df8 
000000c0005febf8:  00000000004a5613 <reflect.DeepEqual+803>  00000000020a0380 
000000c0005fec08:  000000c00039a0c0  0000000000000098 
000000c0005fec18:  00000000020a0380  000000c0003d2020 
000000c0005fec28:  0000000000000098  000000c0005e0cb0 
000000c0005fec38:  0000000000000000  0000000000000000 
000000c0005fec48:  000000000467ffff  000000c0005e0cb0 
000000c0005fec58:  000000c0005e0cb0  00000000026e6ac0 
000000c0005fec68:  00000000020a0380  00000000026e6ac0 
000000c0005fec78:  00000000020a0380  00000000020a0380 
000000c0005fec88:  000000c0003d2020  0000000000000098 
000000c0005fec98:  00000000020a0380  000000c00039a0c0 
000000c0005feca8:  0000000000000098  0000000000000000 
000000c0005fecb8:  9ef5712800000000  000000c0005e0ce0 
000000c0005fecc8:  0000000000000000  000000000043ed39 <runtime.asyncPreempt2+105> 
000000c0005fecd8:  0000000002404178  000000c00004c000 
000000c0005fece8:  000000c0005e0e70  000000000047157b <runtime.asyncPreempt+219> 
000000c0005fecf8:  0000000000000006  0000000000000011 
000000c0005fed08:  000000c000529900  0000000000000012 
000000c0005fed18:  0000000000000010  000000c0005e0900 
000000c0005fed28:  00000000001be901  0000000000000044 
000000c0005fed38:  000000000467b902  0000000000000000 
000000c0005fed48:  0000000002030001  0000000000000000 
000000c0005fed58:  0000000000000018  000000c000580058 
000000c0005fed68:  0000000000000000  0000000000000000 
000000c0005fed78:  0000000000000000  0000000000000000 
000000c0005fed88:  0000000000000000  0000000000000000 
000000c0005fed98:  0000000000000000  0000000000000000 
000000c0005feda8:  0000000000000000  0000000000000000 
000000c0005fedb8:  0000000000000000  0000000000000000 
000000c0005fedc8:  000000c00015e420  000000c00015e450 
000000c0005fedd8:  000000c00015e4e0  000000c00015e4b0 
000000c0005fede8:  000000c000004320  000000c0000042c0 
000000c0005fedf8:  000000c000106030  000000000043ed39 <runtime.asyncPreempt2+105> 
000000c0005fee08:  0000000002404178  000000c00004c000 
000000c0005fee18:  000000c0005e0fa0  000000000047157b <runtime.asyncPreempt+219> 
000000c0005fee28:  0000000001ba7ec0 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.(*BasicPod).Generate+0>  000000c0006c1890 
000000c0005fee38:  0000000002133600  00000000009cb22b <k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/errors.NewAggregate+683> 
000000c0005fee48:  0000000000000000  0000000000000000 
000000c0005fee58:  00000000001be901  0000000000000044 
000000c0005fee68:  000000000467b902  0000000000000000 
000000c0005fee78:  0000000002030001  0000000000000000 
000000c0005fee88:  0000000000000018  000000c000580058 
000000c0005fee98:  0000000000000000  0000000000000000 
000000c0005feea8:  0000000000000000  0000000000000000 
000000c0005feeb8:  0000000000000000  0000000000000000 
000000c0005feec8:  0000000000000000  0000000000000000 
000000c0005feed8:  0000000000000000  0000000000000000 
000000c0005feee8:  0000000000000000  0000000000000000 
000000c0005feef8:  000000c00015e420  000000c00015e450 
000000c0005fef08:  000000c00015e4e0  000000c00015e4b0 
000000c0005fef18:  000000c000004320  000000c0000042c0 
000000c0005fef28: !000000c0005fefa8 >0000000001ba7f46 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.(*BasicPod).Generate+134> 
000000c0005fef38:  000000c0006c1890  0000000000000000 
000000c0005fef48:  0000000000000000  0000000000000000 
000000c0005fef58:  0000000000000000  000000c00006bdd0 
000000c0005fef68:  0000000000000000  0000000000000000 
000000c0005fef78:  0000000000000000  0000000000000000 
000000c0005fef88:  000000c000106120  000000c0001060c0 
000000c0005fef98:  0000000000000246  000000c0005e1258 
000000c0005fefa8:  000000c0005ff258  0000000001cb7a74 <k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/run.(*RunOptions).createGeneratedObject+292> 
000000c0005fefb8:  000000000375ad20  000000c0006c1890 
000000c0005fefc8:  0000000000000000  0000000000000000 
000000c0005fefd8:  0000000000000000  0000000000000000 
000000c0005fefe8:  000000000000000b  000000c0005e1028 
000000c0005feff8:  0000000000418203 <runtime.typedmemmove+67>  0000000000000000 
000000c0005ff008:  0000000000000000  0000000000000000 
000000c0005ff018:  0000000000000000  00000000020a0380 
000000c0005ff028:  000000000375bf40 
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned.BasicPod.Generate(0x1ba7f46, 0xc0006c1890, 0x0, 0x0, 0x0)
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/generate/versioned/run.go:265 +0x5af fp=0xc0005fef30 sp=0xc0005fe988 pc=0x1b9426f

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x372b560)
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1010 +0x7a
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:411 +0xf1

goroutine 21 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2403638, 0x12a05f200, 0x0, 0x1, 0xc000040120)
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:164 +0x1c5
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x2403638, 0x12a05f200, 0xc000040120)
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x54
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	D:/gopath/kubernetes_go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x97

Debugger finished with exit code 0

```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.14.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
windows 10
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment] 2020-04-24 08:02
Did you use go 1.12 ?

Not sure if this was related to the use of Goland.

**Comment by liggitt** [comment] 2020-04-24 21:46
closing as duplicate of https://github.com/kubernetes/kubernetes/issues/90432

/close

**Closed** 2020-04-24 21:46 UTC
Labels: kind/bug, needs-sig
