### ISSUE TITLE
Public image "jessie-dnsutils" have no update for years

### ISSUE THREAD

**Issue by guessi** [kubernetes/kubernetes#126936] opened 2024-08-27 10:36 UTC
### What would you like to be added?

Public image `registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3` have no update for years, and it's packed with legacy CoreDNS 1.5.0 inside the docker image.

ref:
- https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
- https://github.com/kubernetes/kubernetes/blob/master/test/images/jessie-dnsutils/Dockerfile
- https://github.com/kubernetes/kubernetes/commits/master/test/images/jessie-dnsutils (last update was years ago)

### Why is this needed?

`jessie-dnsutils` commonly used for DNS troubleshooting, and it's based on EOL jessie image.
- https://www.debian.org/releases/jessie/
- https://wiki.debian.org/LTS

**Comment by kannon92** [comment] 2024-08-27 12:21
/sig testing
/sig network

cc @aojea

**Comment by thockin** [comment] 2024-08-29 16:51
This is not really a supported image for use beyond testing.  We need to find a better answer for general use.  We do have a k/k/test/images/... dire for it, but obviously Jessies is old.

**Comment by BenTheElder** [comment] 2024-08-29 18:45
Wherever possible in the tests we've been moving to the single agnhost utility image, `registry.k8s.io/e2e-test-images/agnhost`, source at https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/README.md

It is actively maintained and supports multi-arch + windows.

While developed for testing, it has already been used in a few of the docs now as a util image for debugging.

For the specific case of:
- https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

I confirmed this works just as well with `registry.k8s.io/e2e-test-images/agnhost:2.39` as a drop in replacement for the image in that pod.

As a meta point, we should consider if the docs can centrally pick a version so we can easily bump docs references to the latest available tag, since registry.k8s.io doesn't support mutable tags, but we avoid breaking changes in this image.

That is more of a question for https://github.com/kubernetes/website though

**Comment by BenTheElder** [comment] 2024-08-29 18:47
I would suggest that we replace references to this image with agnhost, at least as a stopgap.

We should consider if we want to maintain and host an image specifically designed for debugging and what that would look like, but I suspect it winds up being essentially duplicate effort with agnhost anyhow (... though perhaps with a clearer, less "clever" name :-))

**Comment by thockin** [comment] 2024-08-31 04:05
https://github.com/kubernetes/website/pull/47735

@aojea The reason we still have jessie for this is https://github.com/kubernetes/kubernetes/issues/10161 - do you think it's safe now to remove that? :)

**Comment by aojea** [comment] 2024-08-31 08:31
> @aojea The reason we still have jessie for this is #10161 - do you think it's safe now to remove that? :)

OMG, please remove this :) 

/assign @thockin

**Comment by guessi** [comment] 2024-08-31 13:06
@thockin thanks for update, it's my first time to hear agnhost.

Checked the PR and source code of agnhost, I think the sample commands should update as well?
I can see `nslookup` is used for the guidance.

Besides, I can see the base image for agnhost is also EOL, should be addressed in another PR as well,
* https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/BASEIMAGE

**Closed** 2024-09-11 00:17 UTC
Labels: sig/network, kind/feature, sig/testing, needs-triage
