### ISSUE TITLE
Enable api-server to return only selfLinks on list APIs

### ISSUE THREAD

**Issue by tvishwanath-arkin** [kubernetes/kubernetes#72195] opened 2018-12-19 10:05 UTC
**What would you like to be added**:
It would be good to have only selfLinks returned by the api-server on List based resource apis.
Ex: /api/v1/namespaces/default/pods?linksOnly=true

**Why is this needed**:
As the work load increases, the list apis tend to become slow due to retrieval of entire pod object.
Returning links can have following benefits
1) Quick response for users who just want to know how many items are present and cache them for lazy loading.
2) Now the response would be quick and selfLinks contains resource names. This helps user to search resources by name in any fashion.

While the feature to add conditional fieldSelectors OR a contains operator might be a time consuming one, this can be a low hanging fruit that opens up a lot of possibilities at the client side like lazy loading, pagination, search and indexing

/kind feature
/sig api-machinery

**Comment by liggitt** [comment] 2018-12-19 15:07
You can request just the metadata for objects with an `Accept` header of `application/json;as=PartialObjectMetadataList;v=v1beta1;g=meta.k8s.io`

**Comment by liggitt** [comment] 2018-12-19 15:11
duplicate of https://github.com/kubernetes/kubernetes/issues/1459, currently addressed by the ability to request only metadata

/close

**Closed by liggitt** 2018-12-19 15:11 UTC
Labels: kind/feature, sig/api-machinery

**Comment by tvishwanath-arkin** [comment] 2019-01-03 04:15
@liggitt I tried **/api/v1/pods** with the above Accept header but to no avail. I get the below error from api server. I tried on a K8S 1.9.6 cluster
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "only the following media types are accepted: application/json, application/yaml, application/vnd.kubernetes.protobuf",
    "reason": "NotAcceptable",
    "code": 406
}

**Comment by liggitt** [comment] 2019-01-03 05:04
It was promoted to v1beta1 in https://github.com/kubernetes/kubernetes/pull/59059/commits/d07a608607e1f4d252003c17cd615652574a0823 in 1.10
