### ISSUE TITLE
Jobs: specifying both parallelism and backoffLimit can lead to unexpected results

### ISSUE THREAD

**Issue by bodom0015** [kubernetes/kubernetes#60735] opened 2018-03-02 21:55 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I have noticed recently that the `parallelism` field seems to mess with the perceived `backoffLimit`.

Running a job with `backoffLimit: 3` and `parallelism: 2`, I get 2 pod replicas at a time, which both fail and spawn 2 more. A total of 7 pod replicas are created in this case before the job fails due to the`backoffLimit`:
```
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      53s   job-controller  Created pod: backoff-fail-brxks
  Normal   SuccessfulCreate      53s   job-controller  Created pod: backoff-fail-6ss6x
  Normal   SuccessfulCreate      50s   job-controller  Created pod: backoff-fail-dsj77
  Normal   SuccessfulCreate      40s   job-controller  Created pod: backoff-fail-nxww7
  Normal   SuccessfulCreate      40s   job-controller  Created pod: backoff-fail-5qfrp
  Normal   SuccessfulCreate      30s   job-controller  Created pod: backoff-fail-wjdg8
  Normal   SuccessfulCreate      30s   job-controller  Created pod: backoff-fail-mtnht
  Warning  BackoffLimitExceeded  10s   job-controller  Job has reach the specified backoff limit
```

**What you expected to happen**:
I would expect ~3 failed pods before the job is stopped due to hitting the `backoffLimit`.

**How to reproduce it (as minimally and precisely as possible)**:
I am running the test job below, varying only the value for `parallelism`:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: backoff-fail
spec:
  backoffLimit: 3
  parallelism: 2
  template:
    metadata:
      name: backoff-fail
    spec:
      containers:
      - name: failing-container
        image: ubuntu:xenial
        command: [ "/bin/bash" ]
        args: [ "exit", "1" ]
      restartPolicy: Never
```

Simply `kubectl create -f backoff-fail.job.yaml` and watch for failing pods.

Running `kubectl describe job backoff-fail` can quickly confirm whether or not the `backoffLimit` has been reached

**Anything else we need to know?**:
From the above example, it appears that the actual number of replicas we should expect is approximately `parallelism * backoffLimit`?

Is this the expected behavior? Perhaps `parallelism > 1` leads to undefined behavior when specifying a `backoffLimit`? It is also entirely possible that this is just me misunderstanding precisely what the `parallelism` field means at a very low level.

With `backoffLimit: 3` and `parallelism: 1`, I get a single pod replica at a time, which fails before creating another replicas. A total of 3 pod replicas are created in this case before the `backoffLimit` is "reach":
```
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      35s   job-controller  Created pod: backoff-fail-j5st2
  Normal   SuccessfulCreate      34s   job-controller  Created pod: backoff-fail-n848n
  Normal   SuccessfulCreate      24s   job-controller  Created pod: backoff-fail-gm8g5
  Warning  BackoffLimitExceeded  4s    job-controller  Job has reach the specified backoff limit
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.4.111-k8s
- Install tools: Cloud9 AWS + kops
- Others: ??

**Comment by soltysh** [comment] 2018-03-12 13:59
Yeah backoff is problematic with the parallelism > 1 as described in #56853, which was fixed in https://github.com/kubernetes/kubernetes/pull/60202. Lemme see if it solves the issues.

**Comment by soltysh** [comment] 2018-03-12 14:43
Hmmm... actually looking further at both this case and the code it doesn't say that `backoffLimit` will only try creating that many pods. It rather states 'number of retries before marking this job failed' and retries are controlled at the controller level, which in this particular case retried exactly three times. The fact that each time it created `parallelism` pods is due to how the job controller works and how the spec is defined. I'm worried that changing this behavior to `backoffLimit` being the number of retried containers would unnecessarily complicate the controller code. @kow3ns @bodom0015 do you agree that this is working as designed and we can close this issue?

**Comment by bodom0015** [comment] 2018-03-22 18:00
@soltysh I can definitely how see the `backoffLimit` in this case could be perceived as job restarts instead of pod restarts. In my opinion, this issue can be closed.

Thank you very much for clarifying this behavior! :)

**Closed** 2018-03-27 07:58 UTC
Labels: kind/bug, sig/apps
