### ISSUE TITLE
hyperkube arguments don't pass through correctly (w/ kubectl)

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#25623] opened 2016-05-15 02:24 UTC
hyperkube + kubectl isn't working as I'd expect:

`./hyperkube kubectl run -i --tty nginx --image=nginx --restart=Never`

results in:

```
Error: unknown shorthand flag: 'i' in -i

Kubernetes command line client

Usage:
  Kubernetes command line client [flags]

Available Flags:
      --alsologtostderr[=false]: log to standard error as well as files
      --application-metrics-count-limit=100: Max number of application metrics to store (per container)
      --boot-id-file="/proc/sys/kernel/random/boot_id": Comma-separated list of files to check for boot-id. Use the first one that exists.
      --container-hints="/etc/cadvisor/container_hints.json": location of the container hints file
      --docker="unix:///var/run/docker.sock": docker endpoint
      --docker-env-metadata-whitelist="": a comma-separated list of environment variable keys that needs to be collected for docker containers
      --docker-only[=false]: Only report docker containers in addition to root stats
      --docker-root="/var/lib/docker": Absolute path to the Docker state root directory (default: /var/lib/docker)
      --docker-run="/var/run/docker": Absolute path to the Docker run directory (default: /var/run/docker)
      --enable-load-reader[=false]: Whether to enable cpu load reader
      --event-storage-age-limit="default=24h": Max length of time for which to store events (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is a duration. Default is applied to all non-specified event types
      --event-storage-event-limit="default=100000": Max number of events to store (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is an integer. Default is applied to all non-specified event types
      --global-housekeeping-interval=1m0s: Interval between global housekeepings
      --google-json-key="": The Google Cloud Platform Service Account JSON Key to use for authentication.
  -h, --help[=false]: help for hyperkube
      --housekeeping-interval=10s: Interval between container housekeepings
      --ir-data-source="influxdb": Data source used by InitialResources. Supported options: influxdb, gcm.
      --ir-dbname="k8s": InfluxDB database name which contains metrics requred by InitialResources
      --ir-hawkular="": Hawkular configuration URL
      --ir-influxdb-host="localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb:api": Address of InfluxDB which contains metrics requred by InitialResources
      --ir-namespace-only[=false]: Whether the estimation should be made only based on data from the same namespace.
      --ir-password="root": Password used for connecting to InfluxDB
      --ir-percentile=90: Which percentile of samples should InitialResources use when estimating resources. For experiment purposes.
      --ir-user="root": User used for connecting to InfluxDB
      --log-backtrace-at=:0: when logging hits line file:N, emit a stack trace
      --log-cadvisor-usage[=false]: Whether to log the usage of the cAdvisor container
      --log-dir="": If non-empty, write log files in this directory
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --logtostderr[=true]: log to standard error instead of files
      --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id": Comma-separated list of files to check for machine-id. Use the first one that exists.
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --storage-driver-buffer-duration=1m0s: Writes in the storage driver will be buffered for this duration, and committed to the non memory backends as a single transaction
      --storage-driver-db="cadvisor": database name
      --storage-driver-host="localhost:8086": database host:port
      --storage-driver-password="root": database password
      --storage-driver-secure[=false]: use secure connection with database
      --storage-driver-table="stats": table name
      --storage-driver-user="root": database username
      --v=0: log level for V logs
      --version[=false]: Print version information and quit
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
unknown shorthand flag: 'i' in -i
```

**Comment by whitmo** [comment] 2016-05-16 15:08
Also seeing this behavior:
`~$ /usr/local/bin/hyperkube kubectl create -f /etc/simple/kube-ui.yaml 
Error: unknown shorthand flag: 'f' in -f`

hyperkube from `gcr.io/google_containers/hyperkube:v1.2.2`

**Comment by whitmo** [comment] 2016-05-16 15:29
Confirmed this is still an issue on 1.2.4 .

**Comment by bgrant0607** [comment] 2016-05-17 23:45
Dupe of #24088

See PR #25512

**Closed by bgrant0607** 2016-05-17 23:45 UTC
