### ISSUE TITLE
Problem in Vagrant kubernetes deployment in a proxy environment...

### ISSUE THREAD

**Issue by fahadpolash** [kubernetes/kubernetes#9733] opened 2015-06-12 20:28 UTC
Hello,
I have vagrant kubernets up and running in my laptop. There is no proxy settings in my laptop.
The outputs are from my laptop:

from my laptop Operating system:

fahad@fahad-Inspiron-5537:~/kubernetes$ env | grep -i proxy
fahad@fahad-Inspiron-5537:~/kubernetes$ 

Now I get into the vagrant master:

[vagrant@kubernetes-master ~]$ env | grep -i proxy
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$ netstat -nl | grep tcp
tcp        0      0 10.245.1.2:7080         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN     
tcp        0      0 10.245.1.2:6443         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:58263           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4505            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4506            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 10.245.1.2:8000         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN     
tcp6       0      0 :::10250                :::*                    LISTEN     
tcp6       0      0 :::10255                :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::45360                :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::4194                 :::*                    LISTEN     
[vagrant@kubernetes-master ~]$ 

Notice that, In my vagrant master port 6443 is running, and there is no proxy in my vagrant master as well.

Now have a look at my other machine where I am going to deploy vagrant kubernets [the same release I used for my laptop]. But I have proxy setting in that machine and I need it . But the vagrant kubernets is giving me following error:

==> minion-1:  *  INFO: Salt installed!
Wrote config for vagrant to /home/nio/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
......
Waiting for each minion to be registered with cloud provider
Unable to connect to the server: net/http: TLS handshake timeout

For your information the proxy settings of my machine is : 
nio@Linux10:~/kubernetes$ env | grep -i proxy
http_proxy=http://blabla.com:port
ftp_proxy=http://blabla.com:port
socks_proxy=http://blabla.com:port
https_proxy=http://blabla.com:port
no_proxy=some ip ranges
{note, I have omitted actual ip and proxies are ommited from my machine }

Proxy settings that I passed to vagrant master through vagrant file is as below:

[vagrant@kubernetes-master ~]$ env | grep -i proxy
http_proxy=http://blabla.com:port
ftp_proxy=http://blabla.com:port
socks_proxy=http://blabla.com:port
https_proxy=http://blabla.com:port
no_proxy=some ip ranges

The services that are running in my machine's vagrant master:
[vagrant@kubernetes-master ~]$ netstat -nl | grep tcp
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4505            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4506            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:53242           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 10.245.1.2:8000         0.0.0.0:*               LISTEN     
tcp6       0      0 :::10250                :::*                    LISTEN     
tcp6       0      0 :::10255                :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::53117                :::*                    LISTEN     
tcp6       0      0 :::4194 

You can notice that there is no service running on port 6443??

So, I want to know is there any impact on the proxy settings?
It seems so to me because I used the same releases but it is not working in the proxy environment. And I got the above given errorin my proxied machine. 

Did anybody had the similar issues or any suggestions please?

Thank you.

**Comment by roberthbailey** [comment] 2015-07-06 18:56
@derekwaynecarr have you been able to reproduce?

**Comment by derekwaynecarr** [comment] 2015-08-26 19:14
Can you test if you are still having an issue from the master branch?

**Comment by roberthbailey** [comment] 2015-09-23 04:21
@fahadpolash - I'm going to close this as obsolete since it's been idle for a few months. Please re-open if you are still having this issue so that we can help get to the bottom of it. Thanks!

**Closed by roberthbailey** 2015-09-23 04:21 UTC
Labels: area/cluster-lifecycle, area/platform/vagrant, team/control-plane
