### ISSUE TITLE
kubernetes on vsphere wrong docker systemd config

### ISSUE THREAD

**Issue by veryhumble** [kubernetes/kubernetes#20980] opened 2016-02-10 17:18 UTC
Hi,

I just tried to deploy kubernetes on vsphere using the latest alpha7 build and following the getting started guide.

Everything works fine to the point where the docker service won't start with an error:
```
flag provided but not defined: -d
```
this seems to be an issue in the docker.service systemd file. Changing it to 
```
ExecStart=/usr/bin/docker daemon -H fd:// "$DOCKER_OPTS"
```
fixes the issue

Wonder if anyone else had this issue?

**Comment by a-robinson** [comment] 2016-02-16 23:45
Hi @veryhumble, thanks for bringing this up! To be honest, I don't know whether the vsphere configuration gets much usage (or love), so if you think you have a fix, we'd love if you could send a pull request!

cc @imkin, who last touched the vsphere getting started stuff.

**Comment by imkin** [comment] 2016-02-18 15:29
@veryhumble @a-robinson I agree that this is causing the issue. But this is not specific to vsphere. how systemd starts the docker daemon is deriving from the general kubernetes deploy configuration used for other providers, vagrant and ubuntu.

Please see this issue here https://github.com/kubernetes/kubernetes/pull/20281

I think this is a dupe of https://github.com/kubernetes/kubernetes/pull/20281:-)

**Comment by a-robinson** [comment] 2016-02-18 17:24
Yup, thanks for finding that!

**Comment by imkin** [comment] 2016-06-28 21:08
@a-robinson can this issue be closed?

**Comment by a-robinson** [comment] 2016-06-28 21:21
Looks like it, thanks!

**Closed by a-robinson** 2016-06-28 21:21 UTC
Labels: area/platform/vsphere, team/none
