### ISSUE TITLE
e2e flake: Density is failing with "too high pod startup latency" if more pods are scheduled to the same node

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#22072] opened 2016-02-26 19:55 UTC
Had this test flake twice today:

Density [Feature:Performance] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:487 Expected error: <*errors.errorString | 0xc20ddeb820>: { s: "too high pod startup latency 99th percentil: 5.420308856s", } too high pod startup latency 99th percentil: 5.420308856s not to have occurred

See: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4865/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4858/

**Comment by fabioy** [comment] 2016-02-26 21:57
And one more, but this time in kubernetes-kubemark-gce:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-gce/6001/

**Comment by wojtek-t** [comment] 2016-02-29 07:28
Looking into it now.

**Comment by wojtek-t** [comment] 2016-02-29 08:17
@fabioy - those 3 are completely different issue:
- the second one was fixed by #22051 
- the third one (kubemark) was cause by a PR in kubelet that was reverted


The only real issue is the first one. And what is happening there is:
- we are starting N pods in N-node cluster to check the pods startup time
- however, if few of them with close numbers (we are creating one pod per 200ms) are scheduled to the same node, their startup time is significantly higher then

This is exactly what happened here - the following pods were scheduled to:
node: e2e-scalability-minion-upt5 
4.77s density-latency-pod-7b028b68-dcb5-11e5-b775-42010af01555-66
5.42s density-latency-pod-7b028b68-dcb5-11e5-b775-42010af01555-59
5.77s density-latency-pod-7b028b68-dcb5-11e5-b775-42010af01555-63

**Comment by wojtek-t** [comment] 2016-02-29 08:23
So in the following case - we basically scheduled 3 pods to the same node within 1.4s. According to what @yujuhong wrote in some other PR, it's more than supported by Kubelet now ( @yujuhong - can you confirm?)

So what we should do is to debug, why scheduler is scheduling those pods to a single kubelet in that phase. @gmarek

**Comment by wojtek-t** [comment] 2016-02-29 10:43
@gmarek is adding some more logging in #22168 that would allow us to say something more about scheduler`s decision.

**Comment by yujuhong** [comment] 2016-02-29 18:19
> So in the following case - we basically scheduled 3 pods to the same node within 1.4s. According to what @yujuhong wrote in some other PR, it's more than supported by Kubelet now ( @yujuhong - can you confirm?)

The pod startup latency is affected by the number of concurrent requests. If we don't test the behavior (startup latency of N pods on a node, where N > 1), we probably don't support it :)

**Comment by wojtek-t** [comment] 2016-02-29 18:36
@yujuhong - yeah, this was basically my question. It's probably fine that we don't support it now - I just wanted to ensure that I'm not missing anything.

I (at least partially) know what is happening there, and should send out a fix to it tomorrow or so.

**Comment by wojtek-t** [comment] 2016-03-01 12:55
I have an explanation of it right now. The problem is in scheduler. The issue is generally in LeastRequestedPriority function:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/priorities.go#L81
In our tests, we are scheduling pods without setting request. So scheduler for priorities is assuming some default values:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/util/non_zero.go#L29
 However, as soon as we exceed node capacity, it no longer has any effect (and this is exactly the case, because we have 1 core CPUs, and are scheduling ~30 pods on each node).

 But it's not the only problem. The second issue is about rounding. The calculateScore function returns int from 0 to 10, which means that if on 1-cpu node we have 470millis requested, it's exaclty the same from priority function perspective that e.g. 420millis.

 What we would do:
- I've just introduced requests to pods, that would fix the first issue of exceeding capacity in priority function
- This will reduce differences between different pods, but it will not fix the second problem.

Once the above is merged and we will have some numbers - we should introduce requests to "latency" pods, so that we will be scheduling exactly one additional pod per node.

Will send the other PR out soon. This will fix the problem completely.

**Comment by wojtek-t** [comment] 2016-03-01 13:41
Actually - after discussing it offline with @gmarek we decided to:
- decrease request for regular pods a bit (so that at the cluster scale we are significantly below cluster capacity)
- do not set any requests on "latency" pods (to trigger "full scheduling")

Then adding a new latency pod (with 0.1cpu request) will trigger increasing its underlying score, so they should all be spread evenly between nodes.

**Comment by saad-ali** [comment] 2016-03-02 00:18
More occurrences of this failure:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4949/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4955/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4967/

**Comment by saad-ali** [comment] 2016-03-02 02:06
More failures:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4969/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4967/

**Comment by saad-ali** [comment] 2016-03-02 02:26
More:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4970/

**Comment by wojtek-t** [comment] 2016-03-02 07:28
All of the failures from @saad-ali are a different issue. One of them is because of failing kubelet, and for the others I just opened #22340 for it

**Comment by wojtek-t** [comment] 2016-03-03 10:03
Fixed by #22284

**Closed by wojtek-t** 2016-03-03 10:03 UTC
Labels: area/performance, kind/flake, priority/P1, team/control-plane
