### ISSUE TITLE
staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go is out of date

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#42031] opened 2017-02-24 02:37 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master & 1.6

**What happened**:
`staging/src/k8s.io/apiserver/pkg/apis/example/v1/generated.proto` & `staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go` are out of date; and can not be updated by `./hack/update-staging-client-go.sh`

/cc @sttts

**Comment by k82cn** [comment] 2017-02-24 02:37
@sttts , I can help to create PR with your guidance :).

**Comment by sttts** [comment] 2017-02-24 10:12
Those files are just a copy from pkg/api for testing purposes. There is no technical need to keep them up-to-date. If you want to fix them for cosmetics purposes, just change what you want in the types.go files and generated protobuf with `hack/update-generated-protobuf.sh.`

**Comment by k82cn** [comment] 2017-02-24 10:37
@sttts , thanks ; I'll create a PR for it after #41770 merged.

**Comment by sttts** [comment] 2017-07-04 07:23
As this is not a bug, closing.

**Closed by sttts** 2017-07-04 07:23 UTC
Labels: sig/api-machinery
