### ISSUE TITLE
Controller never healed from data loss, exceeded AWS API rate limit 

### ISSUE THREAD

**Issue by sethp-jive** [kubernetes/kubernetes#14197] opened 2015-09-18 20:24 UTC
Admittedly this one is an edge case, but we had an issue that nearly locked us out of our AWS account following data loss on the kubernetes master. Specifically:
1. We turned up a k8s cluster integrated with AWS
2. An issue in our infrastructure caused us to lose the master's etcd storage (since resolved)
3. The new master came up, we recreated some of the lost state (i.e. kubectl create -f service.yml) and the master tried to resync that partial state with AWS, failing on duplicate resources
4. Until those resources were manually removed, the controller retried each operation often enough that our account become API rate limited, degrading access to our infrastructure

The obvious solution is to not lose the master's data, and we have fixed our mistake there. That said, as the flow above nearly locked us out of our AWS account, it would be nice if the controller had responded a little better to the partial data scenario. Two changes that would have helped us:
1. Increasing backoffs (random, exponential, fibonacci, etc.) around AWS API retries especially when the previous call failed due to a "RequestLimitExceeded" – though this does have the downside of pushing out time to convergence when the underlying issue is fixed
2. A way for the AWS integration to self-heal: when it fails to create e.g. a route because that route already exists in the table, a nicer error handling strategy might simply say "Creation successful!" – the situation is more difficult with security groups that have some state that potentially requires diffing, but in our case the issue occurred in the degenerate case where the controller was trying to recreate the exact resource that already existed

For context, the log messages we saw from the controller (there was some variation depending on which exact request was throttled):

```
E0916 23:21:30.178529       1 servicecontroller.go:171] Failed to process service delta. Retrying: failed to create external load balancer for service default/hello-world: error listing AWS subnets: RequestLimitExceeded: Request limit exceeded.
    status code: 503, request id: []
```

```
E0916 22:53:56.348372       1 routecontroller.go:91] Could not create route ROUTE_ID 10.244.0.0/24: error creating AWS route (10.244.0.0/24): RequestLimitExceeded: Request limit exceeded.
```

The underlying issues seemed to stem from:

```
E0916 23:35:37.607891       1 servicecontroller.go:171] Failed to process service delta. Retrying: failed to create external load balancer for service default/hello-world: InvalidGroup.Duplicate: The security group 'SECURITY_GROUP_ID' already exists for VPC 'VPC_ID'
```

```
E0916 22:52:56.239869       1 routecontroller.go:91] Could not create route ROUTE_ID 10.244.3.0/24: error creating AWS route (10.244.3.0/24): RouteAlreadyExists: The route identified by 10.244.3.0/24 already exists.
```

Deleting both of those resources did appear to resolve the problem. Thanks for reading my book!

**Comment by aronchick** [comment] 2015-10-05 19:07
+1 I've seen this as well.

**Comment by quinton-hoole** [comment] 2015-10-05 20:30
cc @justinsb

**Comment by davidopp** [comment] 2015-12-15 07:49
ping @justinsb

**Comment by therc** [comment] 2015-12-29 22:32
I have observed this at least twice, too.

**Comment by therc** [comment] 2016-01-03 20:48
After some more investigation, I am not sure that ignoring RouteAlreadyExists will always work, because if e.g. all routes don't get cleanly deleted when bringing down a cluster and then you bring it up again, the leftover routes will be in "blackhole" state:
```
$ aws ec2 describe-route-tables --filters Name=route.state,Values=blackhole | jq '.RouteTables[].Routes[] | select(.State == "blackhole")'
{
  "Origin": "CreateRoute",
  "State": "blackhole",
  "NetworkInterfaceId": "eni-6bb31848",
  "DestinationCidrBlock": "10.128.0.0/24"
}
{
  "Origin": "CreateRoute",
  "State": "blackhole",
  "NetworkInterfaceId": "eni-7fb71c5c",
  "DestinationCidrBlock": "10.128.2.0/24"
}
{
  "Origin": "CreateRoute",
  "State": "blackhole",
  "NetworkInterfaceId": "eni-e0b11ac3",
  "DestinationCidrBlock": "10.128.1.0/24"
}
```

In that case, there's no way around removing the stale routes.

**Comment by justinsb** [comment] 2016-01-03 23:18
Ah - I have a PR for the blackhole route problem #17078.  I'll tidy it up and try to get it merged!

**Comment by justinsb** [comment] 2016-01-04 00:00
So I agree with the issue as described by @sethp-jive here: we need a generic solution and specific solutions for any repeatable problems (like the route blackhole issue).

For the generic solution, we need some form of backoff so we don't hit AWS rate limits - the big problem here is that these limits are account-wide, so a k8s cluster could disable access to other infrastructure running in the same account.  It is not trivial to know _how_ to do this though; I tried before with generic rate-limiting but I couldn't figure out how to actually decide what a sensible limit would be.  We could observe the "RequestLimitExceeded" error and then introduce a back-off, which would protect the AWS account, but the problem is that this is "backwards-looking" - by the time we hit this error we have already hit the limit and are causing other requests to fail.  That said, I think if we log whenever we see RequestLimitExceeded, and we also then insert a throttle into all (?) AWS calls after hitting RequestLimitExceeded, we can protect the AWS account and also collect logs for specific fixes.

For the specific issues, I think we have to fix them one by one, both fixing the underlying issue as in #17078 (which would be AWS specific) or by inserting backoffs into retries (which should apply to all providers).

**Closed** 2018-02-24 21:15 UTC
Labels: area/platform/aws, lifecycle/rotten, priority/important-soon, sig/aws
