### ISSUE TITLE
Update to golang 1.11.0

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69312] opened 2018-10-01 21:45 UTC
Sometimes we switch the golang versions towards the end of the release which is problematic.

For 1.13, can we please switch over to golang 1.11.0 early in the cycle?

cc @ixdy @cblecker @BenTheElder

**Comment by cblecker** [comment] 2018-10-01 21:47
dupe of #67872

/close

**Closed by cblecker** 2018-10-01 21:47 UTC
Labels: sig/release
