### ISSUE TITLE
hack/update-codecgen.sh is creating codecs that fail verification

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#24473] opened 2016-04-19 15:02 UTC
As an example, see the change in the following PR:

https://github.com/kubernetes/kubernetes/pull/24347#issuecomment-211959855

/cc @kubernetes/rh-cluster-infra @kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment] 2016-04-20 08:06
This is super strange - it's changing codecs for types that didn't change in that PR.

**Comment by wojtek-t** [comment] 2016-04-20 12:29
@derekwaynecarr - I'm not able to reproduce this issue.

When I ran hack/update-codecgen.sh at the changes from first commit of #24347 the only changes that were generated for me are those in pkg/api/v1/types.generated.go
Then running hack/verify-codecgen.sh works fine.

I have no idea how your changes from:
cmd/libs/go2idl/client-gen/testdata/apis/testgroup.k8s.io/types.generated.go
were generated.

**Comment by smarterclayton** [comment] 2016-04-20 13:20
Same version of go?

**Comment by wojtek-t** [comment] 2016-04-20 13:21
I'm using 1.6

**Comment by derekwaynecarr** [comment] 2016-04-20 20:32
I am using 1.6.

**Comment by derekwaynecarr** [comment] 2016-04-20 21:43
If I do the following:

```shell
$ go version
go version go1.6.1 linux/amd64
$ git fetch upstream
$ git checkout master
$ git rebase upstream/master
$ make clean
$ make all
$ hack/verify-codecgen.sh --> no error
$ hack/update-codecgen.sh
$ git status
[decarr@localhost kubernetes (master)]$ git status
On branch master
Your branch is ahead of 'origin/master' by 1382 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup.k8s.io/types.generated.go
```

**Comment by derekwaynecarr** [comment] 2016-04-20 21:44
So even with no code change, the tool is trying to changing something.

**Comment by derekwaynecarr** [comment] 2016-04-20 21:54
Hmm, let me go back to go 1.6.0 and try that out... maybe there is a diff between go 1.6.0 and go 1.6.1

**Comment by derekwaynecarr** [comment] 2016-04-21 01:14
I switched to run go 1.6 and have the same problem.

```
$ go version
go version go1.6 linux/amd64
```

This is now blocking multiple PRs I need to get merged so if anyone else can assist its much appreciated.

**Comment by wojtek-t** [comment] 2016-04-21 06:15
That's super strange - I'm not able to reproduce this problem.

**Comment by wojtek-t** [comment] 2016-04-21 09:17
@derekwaynecarr - are you running this on mac? We used to have some problems in the past that it was working on linux, but wasn't working correctly on mac. However, I don't have mac, so I'm not able to debug it if that's the case.

**Comment by derekwaynecarr** [comment] 2016-04-21 12:39
No Mac, Linux Fedora 23

**Comment by wojtek-t** [comment] 2016-04-21 12:42
Super strange.. the I don't know why I can't reproduce it.

**Comment by therc** [comment] 2016-04-27 14:28
Does it make a difference if you set GO15VENDOREXPERIMENT to 0? Yesterday I wasted a couple of hours on something like this and I tried so many things. I think #23749 has what fixed it for me.

**Comment by pmorie** [comment] 2016-04-28 00:30
For the record i have had this problem many times before. It eventually goes away, but it always comes back :ghost:

**Comment by wojtek-t** [comment] 2016-06-16 13:06
I think it was finally fixed by @thockin in https://github.com/kubernetes/kubernetes/pull/25240

**Closed by wojtek-t** 2016-06-16 13:06 UTC
Labels: priority/P1, team/CSI-API Machinery SIG
