### ISSUE TITLE
kubdeadm v1.5:  Can not access service by curl <ClusterIP>:<Port>, curl hang or "Connection refused"

### ISSUE THREAD

**Issue by Zjianglin** [kubernetes/kubernetes#37199] opened 2016-11-21 09:13 UTC
###

This is a request for help.
searched keywords: can not access service, clusterIP
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Environment**:
- **Cloud provider or hardware configuration**:non-cloud; Architecture: x86_64,CPUs: 2,Mem: 2 GiB
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`):Linux kube-master 4.4.0-47-generic #68-Ubuntu x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
I used kubeadm and the procedure in [Installing Kubernetes on Linux with kubeadm](http://kubernetes.io/docs/getting-started-guides/kubeadm "Title") and for the most part the installation went well.I enable the master to also be a minion node.So it's a single-machine Kubernetes cluster.

Following along the [walkthrough of the Persistent Storage example](http://kubernetes.io/docs/user-guide/persistent-volumes/walkthrough/ "Title"), I can not access service by curl ClusterIP:Port:
It will hang or output something below:
~~~~
root@kube-master:~# curl 10.106.156.167:3000
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Connection refused"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
~~~~
Then I update the service to Type: NodePort, and set nodePort to 30000.Then I can access the service by NodeIP:nodePort:
```
 root@kube-master:~# curl localhost:30000
 I love Kubernetes storage!
```

I tried to debug service by following along the [debugging services document](http://kubernetes.io/docs/user-guide/debugging-services/ "Title"):

```
root@kube-master:~# kc get pv,pvc,svc,pods --all-namespaces
NAMESPACE   NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM     REASON    AGE
NAMESPACE   NAME            STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
default     pvc/myclaim-1   Bound     pv0001    10Gi       RWO           23m
NAMESPACE     NAME                  CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default       svc/frontendservice   10.96.234.18   <nodes>       3000/TCP        21m
default       svc/kubernetes        10.96.0.1      <none>        443/TCP         3h
kube-system   svc/kube-dns          10.96.0.10     <none>        53/UDP,53/TCP   3h
NAMESPACE     NAME                                     READY     STATUS    RESTARTS   AGE
default       po/busybox                               1/1       Running   1          29m
default       po/mypod                                 1/1       Running   0          23m
kube-system   po/dummy-2088944543-h06m8                1/1       Running   0          1h
kube-system   po/etcd-kube-master                      1/1       Running   1          55m
kube-system   po/kube-apiserver-kube-master            1/1       Running   1          55m
kube-system   po/kube-controller-manager-kube-master   1/1       Running   1          55m
kube-system   po/kube-discovery-1150918428-1x956       1/1       Running   0          1h
kube-system   po/kube-dns-654381707-gijot              3/3       Running   0          1h
kube-system   po/kube-proxy-qekzr                      1/1       Running   1          3h
kube-system   po/kube-scheduler-kube-master            1/1       Running   1          55m
kube-system   po/weave-net-tve7d                       2/2       Running   2          3h
persistentVolume is not namespaced

```

* What about the DNS service?
```
root@kube-master:~# kc describe svc frontendservice
Name:			frontendservice
Namespace:		default
Labels:			<none>
Selector:		name=frontendhttp
Type:			NodePort
IP:			10.96.234.18
Port:			<unset>	3000/TCP
NodePort:		<unset>	30000/TCP
Endpoints:		10.32.0.5:80
Session Affinity:	None
No events
```

* I enter a busybox container, there I could nslookup the service and access the service by 
<ClusterIp>:<Port>  as well as  <endpointIp>:<port>  :
```
/ # nslookup frontendservice
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      frontendservice
Address 1: 10.96.234.18 frontendservice.default.svc.cluster.local
/ # wget -qO- 10.32.0.5:80
I love Kubernetes storage!
/ # wget -qO- 10.96.234.18:3000
I love Kubernetes storage!
```

**What you expected to happen**:
I expected to print out "I love kubernetes storage!" when  run curl clusterIP:Port  
(`curl 10.106.156.167:3000`). 
output such as:
```
root@kube-master:~# curl 10.96.234.18:3000
I love Kubernetes storage!
```

**How to reproduce it** (as minimally and precisely as possible):
1. setup a single cluster by admin. [Installing Kubernetes on Linux with kubeadm](http://kubernetes.io/docs/getting-started-guides/kubeadm "Title")
2. install network addon: ``` kubectl apply -f https://git.io/weave-kube ```
3.  Following along the [walkthrough of the Persistent Storage example](http://kubernetes.io/docs/user-guide/persistent-volumes/walkthrough/ "Title"), 
  ```
  $ mkdir /tmp/data01
  $ echo 'I love Kubernetes storage!' > /tmp/data01/index.html
  $  kubectl create -f docs/user-guide/persistent-volumes/volumes/local-01.yaml
  $ kubectl create -f docs/user-guide/persistent-volumes/claims/claim-01.yaml
  $  kubectl create -f docs/user-guide/persistent-volumes/simpletest/pod.yaml
  $  kubectl create -f docs/user-guide/persistent-volumes/simpletest/service.json
  ```
**Anything else do we need to know**:

**Comment by resouer** [comment] 2016-11-21 10:28
Thanks for report. Why are you trying to curl `10.106.156.167` while I can see your clusterIP is actually `10.96.234.18`?

I believe your kube-proxy is working. Since you can already visit Service by `NodePort ` mode.

**Comment by Zjianglin** [comment] 2016-11-22 01:32
@resouer  Firstly I start the service at 10.106.156.167, and then I tried to curl 10.106.156.167.How ever, my computer is dead for some reasons and i restarted it. Then the pod running before restarting was dead. So I recreate the pv,pvc,pod,service , the new service's clusterIP is 10.96.234.18.Also, I tried to ```curl 10.96.234.18 ```, but it hanged for a long time and out put below in the end:

```
root@kube-master:~# curl 10.96.234.18:3000
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: ""
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
```

**Comment by resouer** [comment] 2016-11-22 08:36
@Zjianglin According to your post (which is actually error report from nginx), k8s Service has already redirected your traffic to the backend Pod (it's `mypod` I guess). 

Could you please figure out why your `mypod` is out of service (and it's status is RUNNING, it's wired).

I can see the last part of the guide suggest you to do this:
> You should be able to query your service endpoint and see what content nginx is serving. A “forbidden” error might mean you need to disable SELinux (setenforce 0).

Have you disabled SELinux? (otherwise nginx will refuse to response to your request)

**Comment by Zjianglin** [comment] 2016-11-23 03:28
Hi~ @resouer , the SELinux was disabled as default. 
```root@kube-master:~# sestatus
   SELinux status:                 disabled
```
However, I'm sorry that I didn't understand your other words . The `curl 10.96.234.18:3000` hanged for a long time, how can know whether the traffic has redirected to the backend Pod(`mypod`) by the service(`frontendservice`)? 

Following along side [debugging-service](http://kubernetes.io/docs/user-guide/debugging-services/#a-pod-cannot-reach-itself-via-service-ip), 
  1. I can confirm that the service(`frontendservice`) is running, has `endpoints`, the Pod(`mypod`) is actually serving(I can access the service by `NodeIP:nodePort` in `NodePort` mode and get expected output.),  
  2. I >have DNS working,` iptables` rules installed, and `kube-proxy` does not seem to be misbehaving.
```
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/frontendservice:" -m tcp --dport 30000 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/frontendservice:" -m tcp --dport 30000 -j KUBE-SVC-AGCYLPLBGVDRXMMI
-A KUBE-SEP-YJI5MBS55ULMFDFK -s 10.32.0.5/32 -m comment --comment "default/frontendservice:" -j KUBE-MARK-MASQ
-A KUBE-SEP-YJI5MBS55ULMFDFK -p tcp -m comment --comment "default/frontendservice:" -m tcp -j DNAT --to-destination 10.32.0.5:80
-A KUBE-SERVICES -d 10.96.234.18/32 -p tcp -m comment --comment "default/frontendservice: cluster IP" -m tcp --dport 3000 -j KUBE-SVC-AGCYLPLBGVDRXMMI
-A KUBE-SVC-AGCYLPLBGVDRXMMI -m comment --comment "default/frontendservice:" -j KUBE-SEP-YJI5MBS55ULMFDFK
```

I am really confused why the service can't be accessed by curl `CluterIP:Port`.

**Comment by resouer** [comment] 2016-11-23 08:43
@Zjianglin The response you got from  `curl 10.96.234.18:3000` is a error output from Nginx, that's why I said your service has redirected your request to `mypod`, which is a Nginx running. 

And this is done by:
```
-A KUBE-SERVICES -d 10.96.234.18/32 -p tcp -m comment --comment "default/frontendservice: cluster IP" -m tcp --dport 3000 -j KUBE-SVC-AGCYLPLBGVDRXMMI
```
I think you have noticed what happened next is:`KUBE-SVC-AGCYLPLBGVDRXMMI -> KUBE-SEP-YJI5MBS55ULMFDFK -> 10.32.0.5:80`.

So can you make sure `curl 10.32.0.5:80` from that node always works? And could you please also post your service yaml?

**Comment by resouer** [comment] 2016-11-23 12:14
And please make sure you are not doing that behind some `http_proxy` btw.

**Comment by Zjianglin** [comment] 2016-11-24 05:11
Hi, @resouer , from another pod(`busybox`),I can always get expected output `I love kubernetes storage!` by `wget -qO- 10.32.0.5:80` , is that your ` make sure wget or curl 10.32.0.5:80 from that node always works?` meaning?
The service yaml:
```
root@kube-master:~# kc get svc frontendservice -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"frontendservice","creationTimestamp":null},"spec":{"ports":[{"protocol":"TCP","port":3000,"targetPort":"http-server"}],"selector":{"name":"frontendhttp"}},"status":{"loadBalancer":{}}}'
  creationTimestamp: 2016-11-21T08:33:37Z
  name: frontendservice
  namespace: default
  resourceVersion: "11828"
  selfLink: /api/v1/namespaces/default/services/frontendservice
  uid: 32ecc543-afc5-11e6-bb6c-0019bb5451a0
spec:
  clusterIP: 10.96.234.18
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: http-server
  selector:
    name: frontendhttp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

```

Then, thanks for your reminding of the `http_proxy`. After `unset http_proxy` , i can access the service by `curl 10.96.234.18:3000`. However, at another node in the cluster, I can only random access the service, often get "timeout" or " No route to host". I have tried several times   Does it matters?
```
cloud@CNT-13:~$ unset {http,ftp,socks,https}_proxy
cloud@CNT-13:~$ env | grep -i proxy
cloud@CNT-13:~$ curl 10.239.47.100:30000
I love Kubernetes storage!
cloud@CNT-13:~$ curl 10.96.234.18:3000
curl: (7) Failed to connect to 10.96.234.18 port 3000: Connection timed out
cloud@CNT-13:~$ curl 10.96.234.18:3000
curl: (7) Failed to connect to 10.96.234.18 port 3000: No route to host
cloud@CNT-13:~$ logout
```
> logout and login again
```
cloud@CNT-13:~$ unset {http,ftp,socks,https}_proxy
cloud@CNT-13:~$ env | grep -i proxy
cloud@CNT-13:~$ curl 10.96.234.18:3000
curl: (7) Failed to connect to 10.96.234.18 port 3000: No route to host
cloud@CNT-13:~$ curl 10.96.234.18:3000
I love Kubernetes storage!
cloud@CNT-13:~$ curl 10.96.234.18:3000
I love Kubernetes storage!
cloud@CNT-13:~$ curl 10.96.234.18:3000
curl: (7) Failed to connect to 10.96.234.18 port 3000: No route to host
```

**Comment by resouer** [comment] 2016-11-24 14:12
It's good to know `http_proxy` is the problem (you are behind GFW I guess). 

As for your last question, k8s is working well according to your logs & posts. Could you please try to `curl` your pod directly from  `cloud@CNT-13` to see if there's any `No route to host`? Your underlying network seems unstable (Looks like Weave + IaaS network?)

Anyway, I will close this issue now since it's not a bug. If you think there's something wrong with your network, please re-open this or create a new one.

**Closed by resouer** 2016-11-24 14:12 UTC
Labels: component/kube-proxy

**Comment by Zjianglin** [comment] 2016-11-25 03:12
@resouer  okay, Thanks for your help!

**Comment by Starefossen** [comment] 2016-12-21 11:30
@Zjianglin did you ever figure out what was not working in this case? Think I might experience a similar problem with my cluster.

**Comment by Zjianglin** [comment] 2016-12-22 06:19
@Starefossen actually my service and pods are working normally,just the traffic was redirected to proxy server. After `unset http_proxy`, the problem was solved. 
 Maybe you should debug your cluster status following with [official debugging-service](http://kubernetes.io/docs/user-guide/debugging-services/#a-pod-cannot-reach-itself-via-service-ip)
