### ISSUE TITLE
kubernetes don't clean up docker container?

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#12713] opened 2015-08-14 08:06 UTC
Verison: kubernetes 1.02
I create rc or pod success on node1 . After delete rc or pod, docker container and docker images still could be seen in "docker ps -a" and "docker images" which still occupy disk space. 
Expected results: Once pod is deleted, docker container and images should be deleted automatically to release disk space.
if  create and delete pod repeatedly on node1, I suppose less and less disk space to free. So I need to run "docker rmi and docker rm" command to clean up docker container and images on node1 by myself?

thanks!

**Comment by yujuhong** [comment] 2015-08-14 16:03
kubernetes has a separate container and image garbage collectors that routinely check the containers/images. They are controlled by a few flags. For example, container GC only kicks in after the maximum #containers exceeds  [`maximum-dead-containers`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L223).

There is definitely room for improvement. E.g., like you suggested, we should try removing containers associated with deleted pods as soon as possible (#8347). We should also document the GC behavior better (#8416).

**Comment by brendandburns** [comment] 2015-08-14 19:01
Closing this as dupe of #8347 and #8416

**Closed by brendandburns** 2015-08-14 19:01 UTC
Labels: kind/support, team/node
