### ISSUE TITLE
TestUnschedulableNodes: Failed to observe reflected update for setting unschedulable=true

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25845] opened 2016-05-19 00:09 UTC
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-test-go/12266/

```
--- FAIL: TestUnschedulableNodes (20.07s)
    scheduler_test.go:166: Failed to observe reflected update for setting unschedulable=true: timed out waiting for the condition
```

**Comment by fejta** [comment] 2016-05-23 23:04
Assigning to @davidopp per team/control-plane label

**Comment by mml** [comment] 2016-06-03 23:46
Not sure if this is still happening.  Will take a look on Monday.

**Comment by mml** [comment] 2016-06-06 22:18
This error message comes from a place where we retry for an arbitrary period of time (20s) before giving up.  If the failures are rare, this looks like the standard problem of trying to pick a timeout that fails quickly enough but doesn't flake all the time.

I have tried cranking the timeout down to 50ms instead to see if I can reproduce (no luck yet), but any transient failure around this timeout is basically by design.  The "problem" could be that other threads or just etcd haven't gotten enough resources to finish in 20 wall seconds.

It might be interesting if we could get a thread dump when this fails.  And maybe turn on etcd debug logging.

**Comment by mml** [comment] 2016-06-06 22:48
For sure, running etcd with --debug and sending stdout to a file we keep would be super useful.  It logs every request with timestamps.

**Comment by wojtek-t** [comment] 2016-06-08 12:15
It sometime happens - I've seen it yesterday in completely unrelated PR.

**Comment by wojtek-t** [comment] 2016-06-08 12:27
I think I wrote this test at some point btw. Let me take a look.

**Comment by wojtek-t** [comment] 2016-06-08 13:04
I took a look and to be honest I have no idea what is happening there. I sent out a PR to slightly extend logging which may help with debugging - see #27401

**Comment by mml** [comment] 2016-06-09 19:56
I couldn't find an example of this happening at all in June.  Downgrading to P2 and we'll wait until it happens again.

**Comment by wojtek-t** [comment] 2016-06-09 20:02
This happened to me on Tuesday in #26880

**Comment by calebamiles** [comment] 2016-11-04 19:43
@mml @lavalamp @fejta @wojtek-t any updates on this issue; should it be closed?

**Comment by dims** [comment] 2016-11-17 22:07
Marking this as fixed. please reopen if necessary.

**Closed by dims** 2016-11-17 22:07 UTC
Labels: kind/flake, priority/P1, team/control-plane
