### ISSUE TITLE
e2e flake: dns and kibana are failing in cluster

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#21973] opened 2016-02-25 10:55 UTC
I observed a situation where dns and kibana didn't started correctly in cluster:

    11:36:04 Feb 24 11:36:04.003: INFO: POD                      NODE                     PHASE    GRACE  CONDITIONS
    11:36:04 Feb 24 11:36:04.003: INFO: kibana-logging-v1-si37t  jenkins-e2e-minion-2stw  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 11:33:35 -0800 PST ContainersNotReady containers with unready status: [kibana-logging]}]
    11:36:04 Feb 24 11:36:04.003: INFO: kube-dns-v10-ynxa8       jenkins-e2e-minion-knjr  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 10:41:13 -0800 PST ContainersNotReady containers with unready status: [skydns]}]

I did some more debugging and:
- dns didn't started because skydns container wasn't answering on probes:

    I0224 18:41:33.641001    3372 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-v10-ynxa8", UID:"08a66aa4-db26-11e5-9f36-42010af00002", API     Version:"v1", ResourceVersion:"207", FieldPath:"spec.containers{skydns}"}): type: 'Warning' reason: 'Unhealthy' Readiness probe failed: HTTP probe failed with statuscode: 503

- kibana was simply crashlooping [my hypothesis is that it was because of lack of dns]

The failure is from:
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-kubemark-gce/5947/build-log.txt

It seems very similar to https://github.com/kubernetes/kubernetes/issues/15227 

@ArtfulCoder - since you fixed #15227 - maybe you can think about something?

**Comment by gmarek** [comment] 2016-02-25 13:43
Few more datapoints:
logs from a healthy proxy:
```
Flag --resource-container has been deprecated, This feature will be removed in a later release.
I0225 08:35:45.613380       5 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
I0225 08:35:45.613455       5 server.go:148] setting OOM scores is unsupported in this build
I0225 08:35:45.654124       5 server.go:194] Using iptables Proxier.
I0225 08:35:45.654237       5 server.go:207] Tearing down userspace rules.
I0225 08:35:45.654255       5 iptables.go:380] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I0225 08:35:45.655246       5 iptables.go:380] running iptables -C [PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I0225 08:35:45.656134       5 iptables.go:380] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I0225 08:35:45.657127       5 iptables.go:380] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I0225 08:35:45.658243       5 iptables.go:380] running iptables -C [INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I0225 08:35:45.659242       5 iptables.go:380] running iptables -F [KUBE-NODEPORT-NON-LOCAL -t filter]
I0225 08:35:45.660204       5 iptables.go:380] running iptables -F [KUBE-PORTALS-CONTAINER -t nat]
I0225 08:35:45.661035       5 iptables.go:380] running iptables -F [KUBE-PORTALS-HOST -t nat]
I0225 08:35:45.661840       5 iptables.go:380] running iptables -F [KUBE-NODEPORT-HOST -t nat]
I0225 08:35:45.662595       5 iptables.go:380] running iptables -F [KUBE-NODEPORT-CONTAINER -t nat]
I0225 08:35:45.663604       5 conntrack.go:36] Setting nf_conntrack_max to 262144
I0225 08:35:45.663652       5 conntrack.go:41] Setting conntrack hashsize to 65536
I0225 08:35:45.663962       5 conntrack.go:46] Setting nf_conntrack_tcp_timeout_established to 86400
...
```
logs from a crashlooping one:
```
Flag --resource-container has been deprecated, This feature will be removed in a later release.
I0225 08:35:47.932544       6 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
I0225 08:35:47.932613       6 server.go:148] setting OOM scores is unsupported in this build
I0225 08:35:47.958715       6 server.go:194] Using iptables Proxier.
W0225 08:35:47.958819       6 proxier.go:198] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
I0225 08:35:47.958842       6 server.go:207] Tearing down userspace rules.
I0225 08:35:47.958857       6 iptables.go:380] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I0225 08:35:47.959849       6 iptables.go:380] running iptables -C [PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I0225 08:35:47.960963       6 iptables.go:380] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I0225 08:35:47.961995       6 iptables.go:380] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I0225 08:35:47.962995       6 iptables.go:380] running iptables -C [INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I0225 08:35:47.963899       6 iptables.go:380] running iptables -F [KUBE-NODEPORT-NON-LOCAL -t filter]
I0225 08:35:47.964752       6 iptables.go:380] running iptables -F [KUBE-PORTALS-CONTAINER -t nat]
I0225 08:35:47.965718       6 iptables.go:380] running iptables -F [KUBE-PORTALS-HOST -t nat]
I0225 08:35:47.966493       6 iptables.go:380] running iptables -F [KUBE-NODEPORT-HOST -t nat]
I0225 08:35:47.967300       6 iptables.go:380] running iptables -F [KUBE-NODEPORT-CONTAINER -t nat]
I0225 08:35:47.968229       6 conntrack.go:36] Setting nf_conntrack_max to 262144
I0225 08:35:47.968272       6 conntrack.go:41] Setting conntrack hashsize to 65536
open /sys/module/nf_conntrack/parameters/hashsize: read-only file system
```

Kube-proxy fails when trying to write a hashsize in the last line, but the first difference is in
```
W0225 08:35:47.958819       6 proxier.go:198] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
```

**Comment by gmarek** [comment] 2016-02-25 14:53
I look around the web and I found that it's often caused by `br_netfilter` kernel module not being loaded. It's unlikely a race, as it's a crashloop, not a single failure. cc @kubernetes/goog-cluster @thockin

**Comment by lavalamp** [comment] 2016-02-25 18:18
Is this a dup of #21940?

**Comment by lavalamp** [comment] 2016-02-25 18:21
Assign to @spxtr to figure out if it's dup or not.

**Comment by spxtr** [comment] 2016-02-25 19:16
It's definitely a dup. Looks like this issue has more information, though.

I'm almost certainly not the right person to fix this.

**Comment by bprashanth** [comment] 2016-02-25 21:37
Duping into https://github.com/kubernetes/kubernetes/issues/21940

**Closed by bprashanth** 2016-02-25 21:37 UTC
Labels: area/test, kind/flake, priority/P1, team/cluster
