### ISSUE TITLE
Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#59002] opened 2018-01-30 01:15 UTC
The rescheduler test `[sig-scheduling] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available` has failed for a long time.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/rescheduler.go:55
Expected error:
    <*errors.errorString | 0xc420eccb70>: {
        s: "error while scaling RC kubernetes-dashboard to 2 replicas: Scaling the resource failed with: unable to get client for deployments.extensions: unable to get full preferred group-version-resource for deployments.extensions: the cache has not been filled yet",
    }
    error while scaling RC kubernetes-dashboard to 2 replicas: Scaling the resource failed with: unable to get client for deployments.extensions: unable to get full preferred group-version-resource for deployments.extensions: the cache has not been filled yet
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/rescheduler.go:73
```

Let's either fix this test or skip it.

@kubernetes/sig-scheduling-misc 
/cc @piosz

**Comment by bsalamat** [comment] 2018-01-30 01:23
We plan to retire rescheduler in 1.10. It is being replaced by priority and preemption. So, if the test has been failing for a long time, I would skip the test for now.

**Comment by Random-Liu** [comment] 2018-01-30 01:28
> We plan to retire rescheduler in 1.10. It is being replaced by priority and preemption. So, if the test has been failing for a long time, I would skip the test for now.

@bsalamat Agree. Thanks for the clarification.

**Comment by porridge** [comment] 2018-01-30 14:22
The http://k8s-testgrid.appspot.com/sig-scalability-gce#gce load capacity test is failing every single time since yesterday with a message very similar to this one.

**Comment by porridge** [comment] 2018-01-30 14:47
It sounds like this could be caused by #59043

**Comment by timothysc** [comment] 2018-01-30 15:39
Closing, given the other merge.

**Closed by timothysc** 2018-01-30 15:39 UTC
Labels: priority/failing-test, sig/scheduling
