### ISSUE TITLE
The CNI binary used by salt will leak iptable rules

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#27082] opened 2016-06-08 21:21 UTC
I am testing rktnetes on gce using the kubenet with the CNI binary downloaded from https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/cni/init.sls

And I am seeing iptable rule leaks issue. I am pretty sure the CNI binaries we used [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/cni/init.sls#L22) doesn't contain the fix.

Ref:
https://github.com/coreos/rkt/pull/2618
https://github.com/coreos/rkt/issues/2565

cc @freehan @dcbw @kubernetes/sig-network @euank

**Comment by freehan** [comment] 2016-06-08 21:52
Do you mean the rules did not get clean up? Did TearDownPod finish properly?
I plan to bump cni version once some fixes get in. 
ref: https://github.com/containernetworking/cni/issues/215

**Comment by yifan-gu** [comment] 2016-06-08 22:39
@freehan Pretty sure the plugin.TearDownPod finished succefully. I verified that the allocated IP is cleaned.

**Comment by freehan** [comment] 2016-06-08 23:18
Can you reproduce it by running cni ADD/DEL manually using the cni binary with the same config?

**Comment by yifan-gu** [comment] 2016-06-09 01:26
Let me try. @freehan

**Comment by yifan-gu** [comment] 2016-06-09 01:51
Before running the plugin.

```
sudo iptables-save | wc -l
95
```

Run ADD/DEL with the latest binary, using the scripts from cni repo.
```
$ cd cni/scripts
$ sudo CNI_PATH=../bin ./priv-net-run.sh echo
$ sudo iptables-save | wc -l
95
```

Run ADD/DEL with the binary from salt.
```
$ wget https://storage.googleapis.com/kubernetes-release/network-plugins/cni-c864f0e1ea73719b8f4582402b0847064f9883b0.tar.gz
$ tar xvf cni-c864f0e1ea73719b8f4582402b0847064f9883b0.tar.gz
$ sudo CNI_PATH=./bin ./priv-net-run.sh echo
$ sudo iptables-save | wc -l
99
```

I am using the example cni config from the cni's readme.
```
$ cat /etc/cni/net.d/10-mynet.conf 
{
    "name": "mynet",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.22.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

**Comment by dcbw** [comment] 2016-06-10 22:25
We probably want to update the salt binaries to the recent CNI 0.3 release anyway.  Then we can drop some workarounds in the kubenet plugin.

I'm not familiar with the procedure for getting the right binary bits uploaded, and where the binaries should come from.  Could anyone enlighten me on that?

**Comment by dcbw** [comment] 2016-06-10 22:27
The CNI fix is probably https://github.com/containernetworking/cni/pull/195 I think.

But that is no longer relevant now that https://github.com/kubernetes/kubernetes/pull/27132 has landed.  So I think we can close this issue and upload newer CNI binaries after 1.3 lands?

**Comment by freehan** [comment] 2016-06-10 22:31
@yifan-gu #27132 should have covered this.

@dcbw I am thinking pulling cni to vendor dir and build from there. Somehow similar to kube-proxy. I do not want to build/upload for every new release.

**Comment by freehan** [comment] 2016-06-10 22:40
Closing this since it has been fixed.

Continue discussion on better CNI build process at #27211

**Closed by freehan** 2016-06-10 22:40 UTC
Labels: area/networking, kind/bug, priority/P0

**Comment by yifan-gu** [comment] 2016-06-10 23:02
@freehan Thanks! I will test the fix with rktnetes.
