### ISSUE TITLE
node status is flapping between ready and not ready state because of long interval at which node lease renew

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#80172] opened 2019-07-15 13:44 UTC
**What happened**:
The node lease feature becomes beta and enables by default in v1.14. After upgrading our cluster to v1.14, we found some nodes become not ready occasionally and later become ready again after a few seconds. 
In order to have a quick failure detection and recovery, our kubelet has a flag setting `--node-status-update-frequency=5s` and controller-manager has another flag setting `--node-monitor-grace-period=10s`. 

If we use node lease feature, the kubelet doesn't report it's status as frequently as specified by flag `--node-status-update-frequency`, and use node lease mechanism to report that node is alive.
the default interval at which node lease renew is hardcoded 10s,  but it can't be exactly 10s and may be a little bit more than 10s because of some network latency.  when controller-manager doesn't receive messages from kubelet in every 10s in our case, it will mark this node as unreachable and not ready state, but in the next reconcile cycle, it receives the lease update message and mark this node as reachable again,  so the node status is flapping between ready and not ready state.

This seems a breaking change that setting kubelet's lease renewing interval to a hardcoded 10s,  even though our node status update frequency has a little bit small value, node lease should align kubelet's previous behavior and renew as frequently as  `--node-status-update-frequency` to reporting alive message, otherwise controller-manager will mark this node as unreachable.

**What you expected to happen**:
So we should not merely set node lease renewing interval to 10s, maybe depending on the `--node-status-update-frequency` has a more heuristic value.

**How to reproduce it (as minimally and precisely as possible)**:
1. setup a v1.14 kubernetes cluster
2. then set flag `--node-status-update-frequency=5s` to kubelet and `--node-monitor-grace-period=10s` to controller-manager. 
3. then wait a few minute, 
4. you'll find some log regarding `node unreachable` in controller-manager's log.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
/kind bug
/assign

**Comment by dims** [comment] 2019-07-15 14:19
@liggitt smells like a regression WDYT?

**Comment by liggitt** [comment] 2019-07-15 14:26
cc @wojtek-t

**Comment by wojtek-t** [comment] 2019-07-15 19:33
@dims - not a regression - I think the only issue is that we may be missing some documentation, but other than that I think everything looks fine.

So how it works now is:
- There are two fields in Kubelet Config:
 (a) NodeStatusUpdateFrequency: https://github.com/kubernetes/kubernetes/blob/bbef01a20292d40ef4dff8e4c20f3423df679dfb/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L304
 (b) NodeStatusReportFrequency
https://github.com/kubernetes/kubernetes/blob/bbef01a20292d40ef4dff8e4c20f3423df679dfb/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L317

The comments there are pretty detailed and you should read them, but in short the first one roughly translates to how frequenty the lease object is send and the second how frequenty node status is updated (assuming nothing changed in the meantime).


IIRC, there was a decision to not expose it via a flag, because flags in kubelet are deprecated and we're moving to config.

So you can actually mitigate the problem by setting the second field in the config I mentioned above to some smaller value (like 5s) and then you will get Node Status updates every 5s as you want.

So it's possible to achieve what you want without any code changes.


That said, enabling for changing the default lease duration to something larger than 10s, sounds reasonable.

**Comment by tedyu** [comment] 2019-07-15 19:40
How about making the default lease duration 12s (or 14s) ?

I can send out a PR once a new default is agreed upon.

**Comment by gaorong** [comment] 2019-07-16 03:28
@wojtek-t 
thanks for comments.

> So you can actually mitigate the problem by setting the second field in the config I mentioned above to some smaller value (like 5s) and then you will get Node Status updates every 5s as you want.

I don't thank this can help me. as  comment before `NodeStatusReportFrequency` said: "nodeStatusUpdateFrequency is the frequency that kubelet computes node status. **If node lease feature is not enabled**, it is also the frequency that kubelet posts node status to master."  

But what if we both want node lease feature enables (as this is an indeed helpful feature) and heartbeat with apiserver with some smaller value (like 5s)?

**Comment by gaorong** [comment] 2019-07-16 04:04
IMHO, we should add filed in Kubelet Config to let user tune the node lease renewing interval, WDYT?

**Comment by wojtek-t** [comment] 2019-07-16 07:26
> IMHO, we should add a filed in Kubelet Config to let user tune the node lease renewing interval, WDYT?

That sounds like the cleanest option to me (rather than some playing with existing params).

@wangzhen127 - who is the owner of the feature on Node side.

**Closed** 2019-07-18 14:08 UTC
Labels: kind/bug, sig/node
