### ISSUE TITLE
Unpopular opinion: Is the BLM banner size necessary?

### ISSUE THREAD

**Issue by clarkmcc** [kubernetes/kubernetes#94952] opened 2020-09-22 00:14 UTC
I hope this doesn't come off the wrong way, but as I've been using the docs, Kubebuilder, and any other site that is Kubernetes specific, I've noticed a good 200ish px of the top of my page is dedicated to the BLM banner, on virtually every page. I agree as much as the next person that racism is not acceptable, but I didn't come to Kubernetes.io to be preached to about politics, and current world/country issues; I came to learn about orchestrating containerized workloads. I've got no problem with CNN, NBC, or any other major news outlet putting the banner all over their pages, but I'm curious why political and world issues are on the Kubernetes pages?

Again I don't want this to come off as me being in support of anything related to racism, I would have the same stance about a recipe website advocating for AWS services, or gmail putting up messages about how to capture birds: things just are out of place; when I go to specific websites, I go for specific reasons.

A couple of proposed ideas:
1. Remove the banner entirely since kubernetes.io is not a news/social-justice site.
2. Shrink the banner, or make it a floating message in one of the bottom corners.

Anyways, mine may be the unpopular opinion, it just seems a little strange. And quite frankly from a UX standpoint, I would be irritated by any banner that took up that much space on every page of a website I use as often as kubernetes.io.

On that note, thanks to all those who contribute and make this product and community great!

**Comment by hwdef** [comment] 2020-09-22 02:09
I think the second idea is better.

**Comment by dims** [comment] 2020-09-22 02:33
Duplicate of https://github.com/kubernetes/website/issues/23824

/close

**Closed** 2020-09-22 02:33 UTC
Labels: committee/steering
