### ISSUE TITLE
Misleading error when using patch with name and generateName both set

### ISSUE THREAD

**Issue by ceridwen** [kubernetes/kubernetes#65725] opened 2018-07-02 21:00 UTC
/kind bug

**What happened**:

When passing JSON that contains both the name and generateName fields to the API server, if the object with that name already exists, the API server returns the following error every time:

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"The POST operation against Secret could not be completed at this time, please try again.","reason":"ServerTimeout","details":{"name":"POST","kind":"Secret"},"code":500}
```

**What you expected to happen**:

A 409 error with the reason set to AlreadyExists, because a resource with that name already exists.

**How to reproduce it (as minimally and precisely as possible)**:

Create a resource with generateName.  Send a patch with the name of the existing resource and generateName set.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration: Clusters on VMs or bare metal.
- OS (e.g. from /etc/os-release): 
```NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux fab10-compute-1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubespray
- Others: I'm using the Kubernetes Python client 6.0.0 to make the create and patch requests.

**Comment by liggitt** [comment] 2018-07-02 23:16
Thanks for the report. This is a duplicate of https://github.com/kubernetes/kubernetes/issues/32220

/close

**Closed by liggitt** 2018-07-02 23:16 UTC
Labels: kind/bug, needs-sig
