### ISSUE TITLE
Suddenly getting TLS Handshake timeout on most requests to the api server

### ISSUE THREAD

**Issue by joshm1** [kubernetes/kubernetes#13382] opened 2015-08-31 12:43 UTC
I'm unable to use `kubectl` because of TLS handshake timeout.

```
kubectl get pods
error: couldn't read version from server: Get https://master-ip/api: net/http: TLS handshake timeout
```

edit: After several tries I got one to go through, so it's not happening 100% of the time.  But the error has been recorded over 4k times in the logs.

I've also noticed the error is showing up often in `/var/log/kube-apisever.log` from requests from minions.

```
I0831 12:35:19.950945       8 logs.go:41] http: TLS handshake error from 172.20.0.65:58143: EOF
I0831 12:35:20.599641       8 logs.go:41] http: TLS handshake error from 172.20.0.148:53774: EOF
I0831 12:35:20.601809       8 logs.go:41] http: TLS handshake error from 172.20.0.240:41027: EOF
I0831 12:35:22.272985       8 logs.go:41] http: TLS handshake error from 172.20.0.25:42939: EOF
I0831 12:35:23.210921       8 logs.go:41] http: TLS handshake error from 172.20.0.240:41034: EOF
I0831 12:35:24.520112       8 logs.go:41] http: TLS handshake error from 172.20.0.65:58172: EOF
```

I also noticed a lot of `dial tcp 127.0.0.1:8080: connection refused` errors in the logs on various endpoints.

```
E0831 12:36:54.588879       5 reflector.go:136] Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1/resourcequotas: dial tcp 127.0.0.1:8080: connection refused
E0831 12:36:54.589161       5 reflector.go:136] Failed to list *api.Secret: Get http://127.0.0.1:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 127.0.0.1:8080: connection refused
E0831 12:36:54.628359       5 reflector.go:136] Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1/serviceaccounts: dial tcp 127.0.0.1:8080: connection refused
E0831 12:36:54.628471       5 reflector.go:136] Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1/limitranges: dial tcp 127.0.0.1:8080: connection refused
E0831 12:36:54.628608       5 reflector.go:136] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1/namespaces: dial tcp 127.0.0.1:8080: connection refused
E0831 12:36:54.628669       5 reflector.go:136] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1/namespaces: dial tcp 127.0.0.1:8080: connection refused
```

If it's relevant, the ephemeral filesystem on /mnt/ephemeral/kubernetes is 99% on one of my minions.  Most of my kube-system pods (kube-ui, kube-dns, elasticsearch, etc) are running that minion. It's full because of elasticsearch and heapster empity-dir volumes, and the mount is only 3.75GB. This filesystem being full caused other problems this weekend, including containers from the kube-dns pod shutting down which in turn brought down all of my other production pods over the weekend.

**Comment by lavalamp** [comment] 2015-08-31 20:11
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by JeanMertz** [comment] 2015-09-26 16:06
@lavalamp we're running into the same problem, unfortunately, it doesn't seem [any SO post has been created](http://stackoverflow.com/search?q=%5Bkubernetes%5D+TLS+handshake+timeout) for this issue.

We're running on GKE without any manual modifications, should it still be considered a "question" on SO, or is this an issue related to Kubernetes?

In our case, we had a script use a service-account on Kubernetes to access the API using `kubectl`, but suddenly we started seeing failures, related to the command not being able to access the API server:

```
$ kubectl get pod
error: couldn't read version from server: Get https://10.135.240.1:443/api: net/http: TLS handshake timeout
```

**Comment by JeanMertz** [comment] 2015-09-26 16:33
In fact, I am now quite positive this is a bug or something is going wrong on GKE:

```
$ kubectl log -f kube-dns-v8-53r8k kube2sky --namespace=kube-system
E0926 16:31:55.054495       1 reflector.go:136] Failed to list *api.Service: Get https://10.135.240.1:443/api/v1/services: net/http: TLS handshake timeout
E0926 16:31:57.045077       1 reflector.go:136] Failed to list *api.Endpoints: Get https://10.135.240.1:443/api/v1/endpoints: net/http: TLS handshake timeout
```

the entire DNS resolution system on our cluster is non-functional because of this issue.

**Comment by roberthbailey** [comment] 2015-09-26 22:43
What version of kubernetes are you running on GKE (`gcloud container clusters list`)?

**Comment by JeanMertz** [comment] 2015-09-27 04:21
@roberthbailey 1.0.6

Having said that, this *might* be related to one of our services on Kubernetes not closing http connections properly on one of the health endpoints, causing tens of thousands of `CLOSE_WAIT` connections to stay open on the nodes.

We've since patched this up, so we'll see how things behave now.

**Comment by roberthbailey** [comment] 2015-09-28 18:59
@JeanMertz - please let us know if you still see this.

**Comment by JeanMertz** [comment] 2015-09-28 20:59
@roberthbailey I havent. It seems to be related to https://github.com/kubernetes/kubernetes/issues/14641

**Comment by roberthbailey** [comment] 2015-09-28 22:44
Thanks for the update.

**Comment by paralin** [comment] 2015-10-21 06:32
Just started seeing this again @roberthbailey 

```
Oct 21 06:31:43 ip-172-20-0-115 kubelet[25950]: E1021 06:31:43.245829   25950 kubelet.go:2259] Error updating node status, will retry: Put https://172.20.0.9/api/v1/nodes/ip-172-20-0-115.us-west-2.compute.internal/status: net/http: TLS handshake timeout
Oct 21 06:31:46 ip-172-20-0-115 kubelet[25950]: E1021 06:31:46.303538   25950 reflector.go:206] pkg/kubelet/kubelet.go:211: Failed to watch *api.Service: Get https://172.20.0.9/api/v1/watch/services?resourceVersion=1904: net/http: TLS handshake timeout
```

Any ideas?

**Comment by roberthbailey** [comment] 2015-10-28 04:34
@paralin -- sorry, I was out of the office last week. Are you still having this issue? If so, I can dig into it tomorrow.

**Comment by paralin** [comment] 2015-10-28 14:47
@roberthbailey I haven't been looking for it but I haven't seen it either. I've also upgraded the cluster to HEAD multiple times.

I think the issue is caused by the master running out of memory and no longer responding to requests. That has been fixed in my cluster.

**Comment by rroopreddy** [comment] 2015-11-08 23:50
Seeing same issue once in couple of days; running Kubernetes 1.0.7 on AWS

$ ./cluster/kubectl.sh get pods -o wide
error: couldn't read version from server: Get https://<kuber_master_ip_address>/api: net/http: TLS handshake timeout

After this error, I can not even SSH into kube_master as if all the processes are killed. Have to restart the cluster from scratch

**Comment by paralin** [comment] 2015-11-09 00:42
@rroopreddy Your master ran out of memory. Force reboot it via your cluster.

On the master, after it comes back up:

```
sudo apt-get update
sudo apt-get install swapspace
```

This will automatically scale swap so that you never run out of memory and deadlock yourself out.

**Comment by rroopreddy** [comment] 2015-11-09 01:01
@paralin, I could not ssh into master and hence had to reboot through AWS console. Processes seem to have not started after AWS console restart. Are separate scripts for cube master and minions to inject these commands so that it is done automatically with "cube_up.sh" command, thanks

**Comment by paralin** [comment] 2015-11-09 04:04
@rroopreddy I would just manually install it for now as it's kind of a temporary fix before a new release with the OOM fixes are cut. Just SSH in when the server is working and install the package.

If you want to customize the boot process on AWS edit

```
cluster/aws/templates/
```

The shell scripts in there are combined to form the boot script.

**Comment by rajeswarr** [comment] 2015-11-18 12:44
Hi,

I used vagrant in mac and getting below error. can someone help me.

Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: net/http: TLS handshake timeout

**Comment by akrmhrjn** [comment] 2015-11-30 09:10
Hey, 
I am using kubernetes on aws and getting the error continuously.

It was working fine for two days and after that when I try **kubectl** command, it gave me the error 
```
error: couldn't read version from server: Get https://54.76.223.85/api: dial tcp 54.76.223.85:443: connection refused
```
After trying couple of times, it gave me another error
```
error: couldn't read version from server: Get https://54.76.223.85/api: net/http: TLS handshake timeout
```
Then suddendly after some time the kubernetes worked fine. It started giving me the results.
But , it again gave me same error after couple of minutes. This error is occuring continuously. Why is this happening?? It seems to be working fine, but I am getting errors most of the time I execute the command.

**Comment by roberthbailey** [comment] 2015-11-30 18:34
@akrmhrjn - it sounds like your apiserver process is crashing every few minutes. What version of Kubernetes are you running?

**Comment by akrmhrjn** [comment] 2015-12-01 05:37
@roberthbailey Must be the v1.1.2.
I downloded using following command.
```
wget -q -O - https://get.k8s.io | bash
```
Thanks.

**Comment by roberthbailey** [comment] 2015-12-02 02:59
Running on GCE (the default)?

**Comment by roberthbailey** [comment] 2015-12-02 04:57
I haven't been able to reproduce the apiserver crashing (although maybe I need to wait longer). In the mean time, can you look at `/var/log/kube-apiserver.log` on your master VM and see if it has a stack trace?

**Comment by akrmhrjn** [comment] 2015-12-02 05:42
@roberthbailey Nope, I have used 
```
export KUBERNETES_PROVIDER=aws
```
I have been trying kubernetes on gcloud so I shut down the cluster on aws as it was giving me errors. 
I will again start today and will let you know soon. 
Also, I installed kubernetes client on Digital Ocean server and started kubernetes. Can this be the issue? So, today I will be installing client on aws instance and check again.  
Thanks.

**Comment by akrmhrjn** [comment] 2015-12-07 05:28
@roberthbailey So, in gcloud it is working fine from 5 days. And last friday I started on aws as well a, this time client on aws instance. Still the same error. 
```
error: couldn't read version from server: Get https://52.19.115.139/api: dial tcp 52.19.115.139:443: connection refused
```

Can you please tell me now how can I ssh to master node on aws so that I can attach you with kube-apiserver.log?

**Comment by roberthbailey** [comment] 2015-12-07 07:16
I haven't ever set up a cluster on AWS, but I would imagine that it is the same as ssh'ing to any AWS instance. @brendandburns or @justinsb might also be able to help.

**Comment by akrmhrjn** [comment] 2015-12-14 04:57
@brendandburns @justinsb Guys, can you help me with above issue?

**Comment by jeffpeiyt** [comment] 2016-01-22 00:58
We got the same issue. It make the nodes into not ready state quite often

**Comment by prashantchitta** [comment] 2016-01-27 01:05
Once we setup cluster, Minion goes to NotReady state after 2 or 3 days with the following error.
Error updating node status, error getting node "{node-name}": Get https://{ip}:6443/api/v1/nodes/{node-name}: dial tcp {ip}:6443: network is unreachable

To see if its a network connectivity issue, i ssh'ed  into the minon and did a curl of the exact url above and it works. So network connectivity is ruled out.

Any pointers why the node goes to NotReady state and unable to post the status to api server?

**Comment by roberthbailey** [comment] 2016-01-27 06:16
@prashantchitta - If you restart the kubelet process (but not the VM) does it start working again or do you keep seeing the network unreachable errors?

**Comment by prashantchitta** [comment] 2016-01-27 06:24
@roberthbailey If I restart the kubelet, it works perfectly fine. But, after 2 or 3 days of continuously running, again it goes back to NotReady state.

I am guessing its something related to connection pool issue somewhere. Any thoughts?

**Comment by roberthbailey** [comment] 2016-01-27 20:14
That makes it sound like a kubelet networking issue. 

/cc @dchen1107 @thockin @krousey

**Comment by suzukihi724** [comment] 2016-02-10 04:09
I got the same issue kubernetes v1.1 on AWS  when I used t2-micro cluster for master-node.
But, this issue doesn't happen when using t2-large cluster (that has more memory than t2-micro) .

**Comment by HackToday** [comment] 2016-02-29 05:06
@suzukihi724  do you mean you would not hit this issue with more memory case ?

How many memory do you use ?

**Comment by nikhiljindal** [comment] 2016-03-14 19:32
Reopening the issue since clearly users are still hitting it.
We seem to have hit the same issue in our e2e: https://github.com/kubernetes/kubernetes/issues/18558#issuecomment-194665285


As per the last update from @roberthbailey (https://github.com/kubernetes/kubernetes/issues/13382#issuecomment-175832658), it sounds like a kublet networking issue.
cc @dchen1107

**Comment by yujuhong** [comment] 2016-03-14 23:30
> @roberthbailey If I restart the kubelet, it works perfectly fine. But, after 2 or 3 days of continuously running, again it goes back to NotReady state.
> 
> I am guessing its something related to connection pool issue somewhere. Any thoughts?
> 
> I saw this issue #17641 and tried to check CLOSE_WAIT on the kubelet node and it returned empty.

@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment] 2016-03-14 23:50
It's not obvious to me what's going on, but it sounds like it could be
caused by some component running out of available FDs? Do our AWS turn-up
scripts not give apiserver an extended number of FDs?

**Comment by nikhiljindal** [comment] 2016-03-14 23:56
I wouldnt say that its happening only on AWS. We encountered the error in our e2e tests as well.
Also, we are seeing this in requests from kubelet and kubectl so maybe the issue is with the underlying client library that both are using to contact the server.

cc @krousey

**Comment by dchen1107** [comment] 2016-03-15 00:00
@nikhiljindal are the logs for those e2e tests are saved somewhere? Looks like the logs of the most recent failure are deleted already. Without those information, I don't know what we can do here.

**Comment by dchen1107** [comment] 2016-03-15 00:04
From commented https://github.com/kubernetes/kubernetes/issues/13382#issuecomment-175321858, I don't think there is a kubelet network related issue. The issue is occurred when Kubelet tries to update NodeStatus to kube-apiserver and is rejected by server.

**Comment by jeffpeiyt** [comment] 2016-03-15 00:31
@dchen1107 we are in an OpenStack based private cloud and faces the same issue

**Comment by nikhiljindal** [comment] 2016-03-15 00:33
We had increased the number of file descriptors for apiserver before: https://github.com/kubernetes/kubernetes/pull/6353, but the error at that time was specifically: `too many open files`.
Also, in the e2e failure: subsequent requests worked fine. There was just one command that failed.

e2e logs are at http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/32142/

**Comment by sporkmonger** [comment] 2016-04-17 05:54
I started hitting this after I accidentally set up two services / two deployments that mistakenly had the same label selector. The scheduler dutifully saw that there were too many containers for that selector and kept terminating and relaunching both. Forever. This would lead to TLS handshake errors after about 10-15 minutes. If you want a quick way to repro, that may be it.

**Comment by ye** [comment] 2016-07-27 22:25
I am seeing the exact same errors today on our internal gitlab k8s cluster. All `kubectl` commands were working just half an hour ago. No any significant events happened in the past half an hour to the best of my knowledge.

```bash
$ kubectl --context gke_internal-gitlab_us-central1-a_gitlab-k8s get svc
Unable to connect to the server: net/http: TLS handshake timeout
$ kubectl --context gke_internal-gitlab_us-central1-a_gitlab-k8s get svc
Unable to connect to the server: net/http: TLS handshake timeout
$ kubectl --context gke_internal-gitlab_us-central1-a_gitlab-k8s get ep
Unable to connect to the server: net/http: TLS handshake timeout
$ kubectl --context gke_internal-gitlab_us-central1-a_gitlab-k8s get pod
The connection to the server 104.197.xxx.xxx was refused - did you specify the right host or port?
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.5", GitCommit:"25eb53b54e08877d3789455964b3e97bdd3f3bce", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.5", GitCommit:"25eb53b54e08877d3789455964b3e97bdd3f3bce", GitTreeState:"clean"}
$ gcloud version
Google Cloud SDK 118.0.0

bq 2.0.24
bq-nix 2.0.24
core 2016.07.18
core-nix 2016.03.28
gcloud 
gsutil 4.19
gsutil-nix 4.18
kubectl 
kubectl-darwin-x86_64 1.2.5

``` 
Running k8s on GCP. `kubectl` is installed via `gcloud components install kubectl`

**Comment by elouanKeryell-Even** [comment] 2016-08-30 15:34
My team is using kubernetes 1.2.0 on another cloud provider, and we are encoutering the same issue.

Issuing `kubectl get pods` takes a long time (~45s), and generates the following logs on the apiserver side:

```
I0830 15:17:53.901890       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53958: EOF
I0830 15:17:53.906282       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53968: EOF
I0830 15:17:53.906329       6 logs.go:41] http: TLS handshake error from 212.144.54.208:40457: EOF
I0830 15:17:53.906355       6 logs.go:41] http: TLS handshake error from 212.144.54.208:40633: EOF
I0830 15:17:53.906376       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47271: EOF
I0830 15:17:53.906400       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47272: EOF
I0830 15:17:53.906420       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53971: EOF
I0830 15:17:53.906442       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60731: EOF
I0830 15:17:53.906462       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47276: EOF
I0830 15:17:53.906483       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47279: EOF
I0830 15:17:53.906503       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47336: EOF
I0830 15:17:53.906522       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47343: EOF
I0830 15:17:53.906543       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47344: EOF
I0830 15:17:53.906562       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60732: EOF
I0830 15:17:53.906583       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47886: EOF
I0830 15:17:53.906602       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53980: EOF
I0830 15:17:53.906623       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47887: EOF
I0830 15:17:53.906643       6 logs.go:41] http: TLS handshake error from 212.144.54.208:40179: EOF
I0830 15:17:53.906665       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53983: EOF
I0830 15:17:53.906684       6 logs.go:41] http: TLS handshake error from 212.144.54.209:53988: EOF
I0830 15:17:53.906734       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47428: EOF
I0830 15:17:53.906757       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47451: EOF
I0830 15:17:53.906778       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47494: EOF
I0830 15:17:53.906797       6 logs.go:41] http: TLS handshake error from 212.144.54.209:54001: EOF
I0830 15:17:53.906817       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47538: EOF
I0830 15:17:53.906837       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60735: EOF
I0830 15:17:53.906874       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47181: EOF
I0830 15:17:53.906894       6 logs.go:41] http: TLS handshake error from 212.144.54.209:54039: EOF
I0830 15:17:53.906913       6 logs.go:41] http: TLS handshake error from 212.144.54.209:54040: EOF
I0830 15:17:53.906932       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60740: EOF
I0830 15:17:53.906961       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60741: EOF
I0830 15:17:53.906983       6 logs.go:41] http: TLS handshake error from 212.144.54.208:44219: EOF
I0830 15:17:53.907002       6 logs.go:41] http: TLS handshake error from 212.144.54.208:44220: EOF
I0830 15:17:53.907023       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60744: EOF
I0830 15:17:53.907040       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47894: EOF
I0830 15:17:53.907087       6 logs.go:41] http: TLS handshake error from 212.144.54.209:54043: EOF
I0830 15:17:53.907111       6 logs.go:41] http: TLS handshake error from 212.144.54.209:54052: EOF
I0830 15:17:53.907128       6 logs.go:41] http: TLS handshake error from 212.144.54.211:60747: EOF
I0830 15:17:53.907145       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47958: EOF
I0830 15:17:53.907160       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47622: EOF
I0830 15:17:53.907177       6 logs.go:41] http: TLS handshake error from 212.144.54.208:47187: EOF
I0830 15:17:54.343985       6 trace.go:57] Trace "Get /api/v1/nodes/kubernetes-1.my.domain.net" (started 2016-08-30 15:17:53.901777962 +0000 UTC):
[437.140983ms] [437.140983ms] END
```

`212.144.*` are my slaves IPs (three slaves).

Sometimes it doesn't even respond:

```
# kubectl get pods
Error from server: the server cannot complete the requested operation at this time, try again later
```

I've monitored resource usage on the cluster, it doesn't seem to be too busy. network & CPU are quite low, memory is currently used up to 85% on some slave nodes but I think we have been witnessing the problem with a way lower memory usage than this.

Anyway, the problem seems to appear a few days after the cluster has been deployed (works fine at the beginning).

**Comment by Pensu** [comment] 2016-09-09 05:45
Has anyone been able to solve it? We are also hitting the same issue.

**Comment by nalink** [comment] 2016-11-30 01:08
seeing same issue on AWS:
kubernetes git:(master)> kubectl cluster-info
Unable to connect to the server: net/http: TLS handshake timeout

**Comment by jeffpeiyt** [comment] 2016-11-30 02:03
@freehan  this is a P1 for a year. I mentioned it in my [post](https://medium.com/@jeffpeiyt/a-reusable-part-in-many-cloud-projects-2151f42572e9#.nm10z2vpw) too.  Any plans :-) ?

**Comment by ununseptium** [comment] 2017-01-02 08:29
Btw. this is by no means a Kubernetes exclusive issue. I'm getting the TLS Handshake Error also when i try to add a VM Host to my Rancher setup which is based on `cattle` instead of kubernetes. So i guess we should open the issue somewhere at docker/docker?

**Comment by jeffpeiyt** [comment] 2017-01-02 17:07
@ununseptium Thanks for the information provided.  Do you have an exact location where the handshake error occurred in cattle?  Our team checked this the error in Kubernetes, which is specific to when the kubelet agent heartbeats to the API server (master) . Does cattle has a similar HTTPS server as in K8s API Server?   I feel it is the k8s API server's scalability or some transient issue when handling (maybe too many) requests?

**Comment by ununseptium** [comment] 2017-01-03 08:37
@jeffpeiyt Unfortunately i've a hard time actually getting useful informations from rancher logs (they actually seem do not really log those things) but if you're interested i opened a issue at rancher they may can provide additional informations: rancher/rancher#7246

To your other question: I'm not really an Kubernetes Expert but every Rancher core service, API, WebUI etc. is served in one container which doesn't have to be using HTTPS at all. So my API is currently called over basic HTTP. 

My handshake failure appears when `some mechanism` (the mystery) inside this rancher container tries to communicate with the external service. (Which is in this case VMCenter) This doesn't seem to be cattle (or kubernetes) related at all because the error appears before i can add the host where the actual orchestration will be setup on.

Funny note: I tried confirming the handshake error manually with a curl call to the VMCenter API inside the error producing container but everything seems fine if i connecting to the API this way...  (more detailed here: rancher/rancher#7246)

**Comment by mqliang** [comment] 2017-01-09 14:25
We got the same issue. We write a custom controller using client-go, and deployment it in k8s cluster. Our custom controller can not List&Watch from APi server due to the `TLS handshake timeout` error. 

We use the following code snippet to create a clientset.

```
        // creates the in-cluster config
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}
	// creates the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

```

**Comment by wojtek-t** [comment] 2017-01-16 09:47
Are you sure it's not problem connected to some settings of your cluster? E.g. lack of file descriptors in apiserver or sth like that? We are not seeing such problems in our environments.

**Comment by homotopycolimit** [comment] 2017-01-28 17:27
I am experiencing the same issue:
kubectl giving TLS timout errors on brand new kubernetes cluster on azure (deployed with kubernetes-anywhere).

`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by bitmage** [comment] 2017-03-30 19:38
I get this on GCE on a weekly basis.  Node version 1.4.7, master version 1.4.9.

I'd be really interested in workarounds - how can I restore my connection?  And of course in a fix.

I saw some comments regarding restarting the master kubelet.  I've got a cluster of 5 VMs running.  How do I know which one is master?  Been searching and can't seem to find the answer to that question.  Maybe I'm misunderstanding something about the cluster topology.

I know something that's happening with my cluster now is we have an Elixir process that's not terminating database connections correctly.  I've set the pods up to restart nightly, but perhaps there's still lingering issues at the node level.  It sounds similar to some of the other stories that I'm hearing in this thread.

I'm happy to participate in further debugging, but I'm not sure where to start.

**Comment by akram** [comment] 2017-05-24 18:06
Hi,
I don't know if this would help, but....
we were having this issue because of a wildfly image running the KUBE_PING component, and the JVM hosting this configuration was not preventing TLSv1.0

to do so, we added: -Dhttps.protocols="TLSv1.1,TLSv1.2"

**Comment by justinsb** [comment] 2017-05-24 20:19
We did fix a long-standing bug with NodePort services, where they would leak sockets if there were no endpoint behind the service.  Easy to see if you are affected, because you'll have lots of sockets in `sudo netstat -anp | grep CLOSE_WAIT` - hundreds if not thousands.

More details e.g. https://github.com/kubernetes/kubernetes/issues/43212#issuecomment-287511016

The typical way this was manifesting itself was as a service with type = LoadBalancer which had no pods, on AWS that uses NodePort and the ELB does a health check every 5 / 10 seconds, each of which would result in a leaked connection.

But if you're using NodePort, this will manifest itself on GCE as well.  And you would suddenly see e.g. the master stop responding.

**Comment by jaytaylor** [comment] 2017-10-27 23:03
Tip: Ensure your proxy settings aren't messed up.

Verify the path to the master, e.g.:

```bash
$ kubectl cluster-info
Kubernetes master is running at https://10.196.10.229:6443
...

$ curl -v https://10.196.10.229:6443/
```

The output may be informative as to what the source of the issue is.

**Closed** 2017-12-13 05:57 UTC
Labels: priority/important-soon, sig/api-machinery, sig/node

**Comment by sourcesoft** [comment] 2018-03-23 16:04
Not sure if this helps you guys, it this happens to me only when I'm trying to access the cluster using university, library or coffeeshop wifi.

Seems fine with office and home ISPs. It appears to be a firewall some one them are running (specially libraries that monitor data)

**Comment by rajendrarawat17** [comment] 2018-12-13 10:46
I was also facing same issue. 
I disabled firewall and it worked for me.

commands:
systemctl stop firewalld
systemctl disable firewalld

**Comment by ljs617966244** [comment] 2019-04-03 11:19
set https_proxy cause this issue for me

**Comment by MarvinMiao** [comment] 2019-04-19 05:27
> set https_proxy cause this issue for me

same to me

**Comment by kidlj** [comment] 2019-07-29 07:49
> set https_proxy cause this issue for me

me the same.

**Comment by omerlin** [comment] 2019-08-29 06:26
set no_proxy cause this issue for me

**Comment by aakashrshah** [comment] 2020-01-04 11:16
I removed the `conf/extra/httpd-ssl.conf` temporarily from my cluster and it worked.

**Comment by OktaySavdi** [comment] 2020-04-09 12:53
the problem seems to be a **proxy** error

```
export username="MyUser"
export password="MyPassword"
export "http_proxy=http://$username:$password@ProxyServerIP:ProxyServerPort"
export "https_proxy=https://$username:$password@ProxyServerIP:ProxyServerPort"
export "no_proxy=localhost,default.local,`echo 10.10.10<your ıp subner>.{1..255} | sed 's/ /,/g'`,`echo 10.10.10<your ıp subner>.{1..255} | sed 's/ /,/g'`"

export "HTTP_PROXY=$http_proxy"
export "HTTPS_PROXY=$https_proxy"
export "NO_PROXY=$no_proxy"
```

**Comment by w0x12ef** [comment] 2020-08-13 14:39
set no_proxy cause this issue for me

**Comment by nagulvali** [comment] 2020-10-19 17:10
I have brand new cluster installed and no pods scheduled on it. after few hours, I tried to communicate to the server using kubectl getting below error. faced this issue before few times which deleting and re-installing entire cluster fixed the issue. but still not sure what causing this.
![image](https://user-images.githubusercontent.com/42230689/96488600-16ab9200-11f3-11eb-8181-df4df8e475ae.png)

**Comment by nagulvali** [comment] 2020-10-19 17:12
still facing this issue - any idea what causing this issue and is there any workaround solutions, suggestions etc.

**Comment by judeki** [comment] 2020-10-23 21:29
> In fact, I am now quite positive this is a bug or something is going wrong on GKE:
> 
> ```
> $ kubectl log -f kube-dns-v8-53r8k kube2sky --namespace=kube-system
> E0926 16:31:55.054495       1 reflector.go:136] Failed to list *api.Service: Get https://10.135.240.1:443/api/v1/services: net/http: TLS handshake timeout
> E0926 16:31:57.045077       1 reflector.go:136] Failed to list *api.Endpoints: Get https://10.135.240.1:443/api/v1/endpoints: net/http: TLS handshake timeout
> ```
> 
> the entire DNS resolution system on our cluster is non-functional because of this issue.

if Anyone still Getting this Bloody error as l have spend a lot of time before l find the solution that work for me
Though this is in Minikube env 
First thing 
$Minikube Stop
$virtualbox 
increase the CPU memory of your VirtualBox
$ Minikube start  

Job done

**Comment by fanchenxu-ship** [comment] 2021-01-17 12:49
> Hi,
> 
> I used vagrant in mac and getting below error. can someone help me.
> 
> Waiting for each minion to be registered with cloud provider
> error: couldn't read version from server: Get https://10.245.1.2/api: net/http: TLS handshake timeout

i have get some error. and i don't know how to resolve it

**Comment by lavalamp** [comment] 2021-01-19 16:46
"TLS handshake timeout" is an extremely generic error message that indicates something is wrong in the networking path between your client and server.
* wrong proxy settings
* apiserver is not running
* apiserver is not healthy and load balancer is therefore not sending it traffic
* load balancer did something confusing with your traffic

This issue is 5 years old and is probably not a good place to get help.

**Comment by magh** [comment] 2021-02-04 18:08
It helped me. Below instructions didn't list 192.168.49.0/24 in the NO_PROXY example which cause the issue.
https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/

**Comment by vhristev** [comment] 2023-07-29 15:00
I had that issue caused by the Ubuntu 22.04 iptables. 

Solve the issue. But that is because I'm using `cilium` as CNI and its use eBPF
```
iptables --flush
```
