### ISSUE TITLE
Failed to pull image x509: certificate signed by unknown authority while create deloyment using kubectl apply -f

### ISSUE THREAD

**Issue by Lavie526** [kubernetes/kubernetes#93556] opened 2020-07-30 06:16 UTC
**What happened**:
After I use kubectl apply -f test.yml, the deployment get created successfully, however the pod status is always :
NAME                                READY   STATUS             RESTARTS   AGE
dv-deployment-57bf77c9b4-f549q      0/1     ImagePullBackOff   0          19m
dv-deployment-57bf77c9b4-r5kkn      0/1     ImagePullBackOff   0          19m

while using kubectl describ pod, here is the details:
Name:         dv-deployment-7ffff8b557-c22qd
Namespace:    default
Priority:     0
Node:         minikube/172.17.0.3
Start Time:   Wed, 29 Jul 2020 23:06:36 -0700
Labels:       app=dvDeployment
              pod-template-hash=7ffff8b557
Annotations:  <none>
Status:       Pending
IP:           172.18.0.4
IPs:
  IP:           172.18.0.4
Controlled By:  ReplicaSet/dv-deployment-7ffff8b557
Containers:
  dv:
    Container ID:
    Image:          bi.docker.aaa.com/dv/runtime:latest
    Image ID:
    Ports:          9701/TCP, 9703/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:  600m
    Requests:
      cpu:        300m
    Liveness:     tcp-socket :9703 delay=200s timeout=1s period=10s #success=1 #failure=3
    Readiness:    tcp-socket :9703 delay=180s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xfmbg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-xfmbg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xfmbg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  62s                default-scheduler  Successfully assigned default/dv-deployment-7ffff8b557-c22qd to minikube
  Normal   Pulling    24s (x3 over 61s)  kubelet, minikube  Pulling image "bi.docker.aaa.com/dv/runtime:latest"
  Warning  Failed     24s (x3 over 61s)  kubelet, minikube  Failed to pull image "bi.docker.aaa.com/dv/runtime:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://bi.docker.aaa.com/v2/: x509: certificate signed by unknown authority
  Warning  Failed     24s (x3 over 61s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    9s (x3 over 60s)   kubelet, minikube  Back-off pulling image "bi.docker.aaa.com/dv/runtime:latest"
  Warning  Failed     9s (x3 over 60s)   kubelet, minikube  Error: ImagePullBackOff

However, i am able to pull the image using:
docker pull bi.docker.aaa.com/dv/runtime:latest. 
After i manully pulled image and it is in local repostory which could be shown while use docker images.
It is still failed to create pod after i change the pull image policy to IfNotPresent.

**What you expected to happen**:
Why it is not able to pull image while create deployment? I have add the repository url Insecure Registries for docker configuation:
 Insecure Registries:
  bi.docker.aaa.com
  127.0.0.0/8

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f test.yml
kubectl get pods
kubectl describe pod

Below is the test.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-deployment
spec:
  #progressDeadlineSeconds: 600 #The maximum time in seconds for a deployment to make progress before it is considered to be failed.Default value is 600s
  replicas: 2
  revisionHistoryLimit: 1 #By default Kubernetes stores the last 10 ReplicaSets and lets you roll back to any of them.
  selector: #defines how the Deployment finds which Pods to manage
    matchLabels: # select a label with app name
      app: dvDeployment
  template:
    metadata:
      labels:
        app: dvDeployment # The Pods are labeled with app: biDeployments
    spec:
      terminationGracePeriodSeconds: 30 #Duration in seconds the pod needs to terminate gracefully. Defaults to 30 seconds. 0 stands for delete immediately.
      containers: # Indicates containers on pods
      - name: dv
        image: bi.docker.aaa.com/dv/runtime:latest
        readinessProbe:
                tcpSocket:
                        port: 9703
                initialDelaySeconds: 180
                periodSeconds: 10
                #timeoutSeconds: 1
                #failureThreshold: 3
        livenessProbe:
                tcpSocket:
                        port: 9703
                initialDelaySeconds: 200
                periodSeconds: 10
                #timeoutSeconds: 1
                #failureThreshold: 3
        ports:
        - containerPort: 9701
          #name: management api
        - containerPort: 9703
          #name: odbc port
        resources:
          requests:
            cpu: "300m"
            #memory: "500M"
          limits:
            cpu: "600m"
            #memory: "1000M"

**Anything else we need to know?**:
I am start minikube using "docker" vm driver
docker version
Client: Docker Engine - Community
 Version:           19.03.1-ol
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        ead9442
 Built:             Wed Sep 11 06:40:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       ead9442
  Built:            Wed Sep 11 06:38:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.2.0-rc.0-108-gc444666
  GitCommit:        c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
Linux slc09yau 5.4.17-2011.0.7.el7uek.x86_64 #2 SMP Mon Mar 16 20:48:30 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Lavie526** [comment] 2020-07-30 06:23
Any suggestion?

I have tried, if i use below yml, it is able to create pods succesfully.

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

**Comment by udit249** [comment] 2020-07-30 06:36
I am looking into this issue

**Comment by udit249** [comment] 2020-07-30 06:46
Before you're pulling the image manually are you using docker login command to login to the private registry?
Can you share the image path as when I am trying to  pull through the mentioned registry I am getting nosuch host.

**Comment by udit249** [comment] 2020-07-30 06:48
Also when you're trying with nginx image , it is pulling from docker hub direclty that is why it is able to pull the image successfully and started the pod

**Comment by Lavie526** [comment] 2020-07-30 06:48
no, i don't use log in.

Actually the image: bi.docker.oraclecorp.com/dv/runtime:latest

**Comment by udit249** [comment] 2020-07-30 07:01
If you are able to manually pull the image , create an image pull secret using below command :
kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<username> --docker-password=<pwd> --docker-email=<your-email>

After creating secret , please add the secret in deployment inside the pod template spec.
for ref:
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred

**Comment by Lavie526** [comment] 2020-07-30 07:35
what's the username/pwd/server should I input when call kubectl create secret?

**Comment by udit249** [comment] 2020-07-30 07:49
for login to a private registry there are credentials used, so that you need to put there and the server would be your registry name.

Finally, you may have to define the certificate to docker by creating a new directory in /etc/docker/certs.d containing the certificates as explained : https://docs.docker.com/engine/security/certificates/

**Comment by Lavie526** [comment] 2020-07-30 08:06
However, i am in my local repository. Why it is not able to get the local image?

**Comment by udit249** [comment] 2020-07-30 08:29
Change imagePullPolicy to IfNotPresent and try.
If that doesn't work change the image tag from latest to other version tag as when we define the image tag as latest, the imagePullPolicy is set to be Always implicitly.

**Comment by Lavie526** [comment] 2020-07-30 08:51
It is strange, still not works. I have changed to IfNotPresent, and also not use the latest tag, but still same error.:

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  67s                default-scheduler  Successfully assigned default/dv-deployment-5f7d6ff56d-rv46h to minikube
  Normal   Pulling    30s (x3 over 66s)  kubelet, minikube  Pulling image "bi.docker.oraclecorp.com/dv/runtime:1.0.0-20200730004206"
  Warning  Failed     30s (x3 over 66s)  kubelet, minikube  Failed to pull image "bi.docker.oraclecorp.com/dv/runtime:1.0.0-20200730004206": rpc error: code = Unknown desc = Error response from daemon: Get https://bi.docker.oraclecorp.com/v2/: x509: certificate signed by unknown authority
  Warning  Failed     30s (x3 over 66s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    3s (x5 over 65s)   kubelet, minikube  Back-off pulling image "bi.docker.oraclecorp.com/dv/runtime:1.0.0-20200730004206"
  Warning  Failed     3s (x5 over 65s)   kubelet, minikube  Error: ImagePullBackOff

**Comment by udit249** [comment] 2020-07-30 10:00
This is quiet strange.
If you want to use image present in local, you can create a local repository on your localhost using:
docker run -d -p 5000:5000 --restart=always --name registry registry:2

After that tag the image with your local registry and push the image in it.
docker tag bi.docker.oraclecorp.com/dv/runtime:1.0.0-20200730004206 localhost:5000/runtime:1.0.0-20200730004206

docker push localhost:5000/runtime:1.0.0-20200730004206


Then you can use that image name in deployment and imagePullPolicy to IfNotPresent

**Comment by Lavie526** [comment] 2020-07-31 01:41
@udit249 I tried to create the local repository, and use it, however still not works.

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  34s                default-scheduler  Successfully assigned default/dv-deployment-656d4dfb86-9kwk2 to minikube
  Normal   Pulling    18s (x2 over 33s)  kubelet, minikube  Pulling image "localhost:5000/dv-runtime:1.0.0-20200730004206"
  Warning  Failed     18s (x2 over 33s)  kubelet, minikube  Failed to pull image "localhost:5000/dv-runtime:1.0.0-20200730004206": rpc error: code = Unknown desc = Error response from daemon: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused
  Warning  Failed     18s (x2 over 33s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    6s (x3 over 32s)   kubelet, minikube  Back-off pulling image "localhost:5000/dv-runtime:1.0.0-20200730004206"
  Warning  Failed     6s (x3 over 32s)   kubelet, minikube  Error: ImagePullBackOff

It is already show up in the docker images.
-bash-4.2$ docker images
REPOSITORY                                                     TAG                    IMAGE ID            CREATED             SIZE
localhost:5000/dv-runtime                                      1.0.0-20200730004206   1df53b17736e        18 hours ago        2.9GB

**Comment by rikatz** [comment] 2020-08-03 13:43
**https://bi.docker.oraclecorp.com/v2/: x509: certificate signed by unknown authority** means that the docker daemon from the worker node pulling the image does not recognize the certificate being used in the registry.

PTAL https://docs.docker.com/engine/security/certificates/

**Comment by litao20102546** [comment] 2020-08-20 03:27
I have the same problem. Is it a code bug?

**Comment by rikatz** [comment] 2020-08-20 14:26
Hello, as stated before this is not a code bug. This is due to your docker registry certificate not being trusted by your container runtime.

PTAL at https://docs.docker.com/engine/security/certificates/ to see how to import the certificate of your docker registry into your container runtime, if you're using some private or non trusted registry.

I'm closing this issue, please feel free to reach by if you believe the problem is other

/assign
/close

**Closed** 2020-08-20 14:26 UTC
Labels: needs-sig, triage/support
