### ISSUE TITLE
kubernetes-e2e-gce-federation is failing consistently with 'projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt' was not found

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#26436] opened 2016-05-27 16:37 UTC
Just to make sure that this is getting attention.  Pretty sure that @colhom is busy fixing this, but I could not find the tracking issue.  Feel free to assign this back to me if necessary.

```
kubernetes-e2e-gce-federation - Build # 27 - Still Failing
http://goto.google.com/k8s-test/job/kubernetes-e2e-gce-federation/27/
Started by timer

Changes:
No changes

Failed tests:
No tests ran.

Build log:
https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/27/build-log.txt
[...truncated 864 lines...]
jenkins-us-central1-f-minion-group-a60c   Ready                      29s
jenkins-us-central1-f-minion-group-ha2q   Ready                      25s
jenkins-us-central1-f-minion-group-zvjf   Ready                      29s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-1               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://130.211.123.112
GLBCDefaultBackend is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/default-http-backend
Elasticsearch is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://130.211.123.112/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

allowed:
- IPProtocol: tcp
  ports:
  - '80'
- IPProtocol: tcp
  ports:
  - '8080'
creationTimestamp: '2016-05-27T09:00:44.435-07:00'
description: ''
id: '7095430114407993795'
kind: compute#firewall
name: jenkins-e2e-minion-jenkins-e2e-http-alt
network: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/networks/jenkins-e2e
selfLink: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt
sourceRanges:
- 0.0.0.0/0
targetTags:
- jenkins-e2e-minion
allowed:
- IPProtocol: tcp
  ports:
  - 30000-32767
- IPProtocol: udp
  ports:
  - 30000-32767
creationTimestamp: '2016-05-27T09:01:22.072-07:00'
description: ''
id: '7611402338315915709'
kind: compute#firewall
name: jenkins-e2e-minion-jenkins-e2e-nodeports
network: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/networks/jenkins-e2e
selfLink: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-nodeports
sourceRanges:
- 0.0.0.0/0
targetTags:
- jenkins-e2e-minion
cat: /workspace/kubernetes/cluster/../_output/release-stage/server/linux-amd64/kubernetes/server/bin/federation-apiserver.docker_tag: No such file or directory
namespace "federation-e2e" created
No resources found
service "federation-apiserver" created
attempting to get federation-apiserver loadbalancer hostname (1 / 30)
attempting to get federation-apiserver loadbalancer hostname (2 / 30)
attempting to get federation-apiserver loadbalancer hostname (3 / 30)
attempting to get federation-apiserver loadbalancer hostname (4 / 30)
attempting to get federation-apiserver loadbalancer hostname (5 / 30)
attempting to get federation-apiserver loadbalancer hostname (6 / 30)
attempting to get federation-apiserver loadbalancer hostname (7 / 30)
attempting to get federation-apiserver loadbalancer hostname (8 / 30)
attempting to get federation-apiserver loadbalancer hostname (9 / 30)
attempting to get federation-apiserver loadbalancer hostname (10 / 30)
attempting to get federation-apiserver loadbalancer hostname (11 / 30)
Found federation-apiserver host at 104.197.149.66
yaml: line 17: mapping values are not allowed in this context
2016/05/27 09:11:00 e2e.go:218: Error running up: exit status 1
2016/05/27 09:11:00 e2e.go:214: Step 'up' finished in 14m43.86767367s
2016/05/27 09:11:00 e2e.go:114: Error starting e2e cluster. Aborting.
exit status 1
+ dump_cluster_logs_and_exit
+ local -r exit_status=1
+ [[ -x cluster/log-dump.sh ]]
+ ./cluster/log-dump.sh /workspace/_artifacts
Dumping master and node logs to /workspace/_artifacts
Master not detected. Is the cluster up?
Nodes not detected. Is the cluster up?
+ [[ true == \t\r\u\e ]]
+ go run ./hack/e2e.go -v --down
2016/05/27 09:11:02 e2e.go:212: Running: teardown
Project: k8s-jkns-e2e-gce-federation
Zone: us-central1-f
Setting zone vars to: federation-e2e-gce-us-central1-a
service "federation-apiserver" deleted
Shutting down test cluster in background.
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-nodeports].
Bringing down cluster using provider: gce

All components are up to date.

All components are up to date.

All components are up to date.
Project: k8s-jkns-e2e-gce-federation
Zone: us-central1-a
INSTANCE_GROUPS=jenkins-us-central1-a-minion-group
NODE_NAMES=jenkins-us-central1-a-minion-group-sk2z jenkins-us-central1-a-minion-group-x2r6 jenkins-us-central1-a-minion-group-yajf
Bringing down cluster
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-a/instanceGroupManagers/jenkins-us-central1-a-minion-group].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/instanceTemplates/jenkins-us-central1-a-minion-template].
Updated [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-a/instances/jenkins-us-central1-a-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-a/instances/jenkins-us-central1-a-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-a-master-https].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-a-minion-all].
Deleting routes jenkins-us-central1-a-04a3641a-2424-11e6-862d-42010af00002 jenkins-us-central1-a-0786a412-2424-11e6-862d-42010af00002
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/routes/jenkins-us-central1-a-0786a412-2424-11e6-862d-42010af00002].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/routes/jenkins-us-central1-a-04a3641a-2424-11e6-862d-42010af00002].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/regions/us-central1/addresses/jenkins-us-central1-a-master-ip].
property "clusters.k8s-jkns-e2e-gce-federation_jenkins-us-central1-a" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-a" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-a-basic-auth" unset.
property "contexts.k8s-jkns-e2e-gce-federation_jenkins-us-central1-a" unset.
Cleared config for k8s-jkns-e2e-gce-federation_jenkins-us-central1-a from /workspace/.kube/config
Done
Setting zone vars to: federation-e2e-gce-us-central1-b
No resources found
Shutting down test cluster in background.
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt' was not found

ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-nodeports' was not found

Bringing down cluster using provider: gce

All components are up to date.

All components are up to date.

All components are up to date.
Project: k8s-jkns-e2e-gce-federation
Zone: us-central1-b
INSTANCE_GROUPS=jenkins-us-central1-b-minion-group
NODE_NAMES=jenkins-us-central1-b-minion-group-2xsy jenkins-us-central1-b-minion-group-m5p2 jenkins-us-central1-b-minion-group-qqy0
Bringing down cluster
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-b/instanceGroupManagers/jenkins-us-central1-b-minion-group].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/instanceTemplates/jenkins-us-central1-b-minion-template].
Updated [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-b/instances/jenkins-us-central1-b-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-b/instances/jenkins-us-central1-b-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-b-master-https].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-b-minion-all].
Deleting routes jenkins-us-central1-b-b20b137d-2424-11e6-af1c-42010af00006
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/routes/jenkins-us-central1-b-b20b137d-2424-11e6-af1c-42010af00006].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/regions/us-central1/addresses/jenkins-us-central1-b-master-ip].
property "clusters.k8s-jkns-e2e-gce-federation_jenkins-us-central1-b" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-b" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-b-basic-auth" unset.
property "contexts.k8s-jkns-e2e-gce-federation_jenkins-us-central1-b" unset.
Cleared config for k8s-jkns-e2e-gce-federation_jenkins-us-central1-b from /workspace/.kube/config
Done
Setting zone vars to: federation-e2e-gce-us-central1-f
No resources found
Shutting down test cluster in background.
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-http-alt' was not found

ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-e2e-minion-jenkins-e2e-nodeports' was not found

Bringing down cluster using provider: gce

All components are up to date.

All components are up to date.

All components are up to date.
Project: k8s-jkns-e2e-gce-federation
Zone: us-central1-f
INSTANCE_GROUPS=jenkins-us-central1-f-minion-group
NODE_NAMES=jenkins-us-central1-f-minion-group-a60c jenkins-us-central1-f-minion-group-ha2q jenkins-us-central1-f-minion-group-zvjf
Bringing down cluster
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-f/instanceGroupManagers/jenkins-us-central1-f-minion-group].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/instanceTemplates/jenkins-us-central1-f-minion-template].
Updated [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-f/instances/jenkins-us-central1-f-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/zones/us-central1-f/instances/jenkins-us-central1-f-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-f-master-https].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/firewalls/jenkins-us-central1-f-minion-all].
Deleting routes jenkins-us-central1-f-5a642d85-2425-11e6-8322-42010af0000a
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/global/routes/jenkins-us-central1-f-5a642d85-2425-11e6-8322-42010af0000a].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-federation/regions/us-central1/addresses/jenkins-us-central1-f-master-ip].
property "clusters.k8s-jkns-e2e-gce-federation_jenkins-us-central1-f" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-f" unset.
property "users.k8s-jkns-e2e-gce-federation_jenkins-us-central1-f-basic-auth" unset.
property "contexts.k8s-jkns-e2e-gce-federation_jenkins-us-central1-f" unset.
Cleared config for k8s-jkns-e2e-gce-federation_jenkins-us-central1-f from /workspace/.kube/config
Done
2016/05/27 09:24:16 e2e.go:214: Step 'teardown' finished in 13m13.226815662s
+ exit 1
+ chmod -R o+r /workspace/_artifacts
+ rc=1
+ [[ 1 -ne 0 ]]
+ [[ -x kubernetes/cluster/log-dump.sh ]]
+ [[ 1 -eq 124 ]]
+ [[ 1 -eq 137 ]]
+ [[ 1 -ne 0 ]]
+ echo 'Build failed'
Build failed
+ echo 'Exiting with code: 1'
Exiting with code: 1
+ exit 1
Build step 'Execute shell' marked build as failure
```
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[PostBuildScript] - Execution post build scripts.
[kubernetes-e2e-gce-federation] $ /bin/bash -xe /tmp/hudson2665859571424393189.sh
+ mkdir -p _tmp
+ curl -fsS --retry 3 https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/jenkins/upload-to-gcs.sh
+ chmod +x ./_tmp/upload-to-gcs.sh
[Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
Run condition [Current build status] preventing perform for step [Execute shell]
[Current build status] check if current [FAILURE] is worse or equals then [UNSTABLE] and better or equals then [UNSTABLE]
Run condition [Current build status] preventing perform for step [Execute shell]
[Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [FAILURE]
Run condition [Current build status] enabling perform for step [Execute shell]
[kubernetes-e2e-gce-federation] $ /bin/bash -xe /tmp/hudson7673132838991460213.sh
+ JENKINS_BUILD_FINISHED=FAILURE
+ ./_tmp/upload-to-gcs.sh
Run finished at Fri May 27 09:24:19 PDT 2016
Uploading to gs://kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/27 (attempt 1)
Uploading build result: FAILURE
Uploading artifacts
Marking build 27 as the latest completed build

*** View logs and artifacts at https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/27 ***

[Current build status] check if current [FAILURE] is worse or equals then [ABORTED] and better or equals then [ABORTED]
Run condition [Current build status] preventing perform for step [Execute shell]
[Google Cloud Storage Uploader] Uploading: build-log.txt
[BFA] Scanning build for known causes...
..........[BFA] Found failure cause(s):
[BFA] Error starting e2e cluster from category setup
[BFA] Done. 10s
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
```

**Comment by colhom** [comment] 2016-05-27 17:01
@quinton-hoole @nikhiljindal I have a PR up for this already. It's caused by the docker version on the upstream Jenkins workers being older than ours.

#26396

**Comment by colhom** [comment] 2016-05-27 17:04
Oh nevermind, this is a different error. it Seems that the issue #26396 is addressing with kubernetes-federation-build must have been resolved via other means sometime last night.

**Comment by colhom** [comment] 2016-05-27 17:16
The root cause is this line:
```
yaml: line 17: mapping values are not allowed in this context
```

This is caused by the image repo and tag not being in the expected text file, which is caused by `kubernetes-federation-build` job failing. The root cause of that is still #26396. We should try to get that merged ASAP, and once the build starts succeeding this issue could be fixed.

Alternatively we could upgrade the Jenkins slave docker version.

**Comment by colhom** [comment] 2016-05-27 21:50
As to the "firewall-rules.delete not found" bit on tear-down- this is a soft-error that is present in the kubernetes-e2e-gce build logs as well. The [gcloud delete](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1360) commands are set up explictly to allow that failure.

It's also not problematic that all federation zones share these rules, as far as I can tell.

@quinton-hoole this should be marked fixed?

**Comment by nikhiljindal** [comment] 2016-05-31 18:32
Thanks for fixing this @colhom

**Closed by nikhiljindal** 2016-05-31 18:32 UTC
Labels: area/cluster-federation, priority/P1, team/control-plane
