### ISSUE TITLE
`TestErrConnKilled` met race detected during execution 

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#108545] opened 2022-03-06 05:17 UTC
### What happened?

Unit test `TestErrConnKilled`  failed for several times due to race detected. Details see: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108541/pull-kubernetes-unit/1500141824923144192

Report this in case of potential bug.

/sig testing

### What did you expect to happen?

Unit test passed as normal.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
NOne
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment] 2022-03-06 05:18
I'd like to take a research first.

**Comment by MadhavJivrajani** [comment] 2022-03-07 06:05
Duplicate of https://github.com/kubernetes/kubernetes/issues/108043
/close

**Closed** 2022-03-07 06:05 UTC
Labels: kind/bug, sig/testing, needs-triage
