### ISSUE TITLE
Secrets created with kubectl apply -f are available as clear text in "Annotations"

### ISSUE THREAD

**Issue by bes** [kubernetes/kubernetes#29923] opened 2016-08-02 16:56 UTC
Maybe I'm misunderstanding, or doing something wrong, but I don't think Secrets should be available in clear text by means of `kubectl describe secrets` even if they are created using `kubectl apply -f`

# Example

my-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  tls.crt: BASE64...
  tls.key: BASE64...
```

Commands:
```
kubectl apply -f my-secret.yaml
kubectl describe secrets my-secret
```

`kubectl describe` will have an "Annotations:" field which contains the entire yaml file (as JSON), including my base64 encoded secrets:

```
Name:		tls
Namespace:	default
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"kind":"Secret","apiVersion":"v1","metadata":{"name":"tls","creationTimestamp":null},"data":{"tls.crt":"BASE64...","tls.key":"BASE64..."},"type":"Opaque"}

Type:	Opaque

Data
====
tls.key:	1565 bytes
tls.crt:	1234 bytes
```

I appreciate that it's hard to `apply` something without storing last-applied-configuration, but maybe Secrets should be treated as a special case?

**Comment by zhouhaibing089** [comment] 2016-08-03 10:49
People would argue that you can edit it, why can't you read it, given that there is some kind of namespace isolation via RBAC or something else.

Actually I am confused as well, what's the exact use case for secrets and why the base64 encoding is required?

**Comment by pwittrock** [comment] 2016-08-10 21:39
@zhouhaibing089 The use case for secrets is to inject binary data (files) into your application without checking them into your source repo or building them into your images.  This is useful for things like private encryption keys.

**Comment by pwittrock** [comment] 2016-08-10 21:41
@bes Do you know if it is possible to give read access to just the annotation without giving read access to the actual secret?  If not, this seems less critical.  I can appreciate that you may not want the base64 printed to your console when you want to describe the secret.

**Comment by pwittrock** [comment] 2016-08-10 21:41
cc @pwittrock

**Comment by zhouhaibing089** [comment] 2016-08-11 07:32
@pwittrock that makes sense for me, however when I compared the configmap and secrets, I am confused, secrets is something that is truly secret, it looks like just one more base64 encoding while configmap is in clear text, but somewhat secrets could still be read anyway.

**Comment by bgrant0607** [comment] 2016-08-15 17:04
Dupe of #23564

**Closed by bgrant0607** 2016-08-15 17:04 UTC
Labels: component/kubectl, priority/P2, team/ux

**Comment by liggitt** [comment] 2019-08-03 23:45
This was a duplicate of https://github.com/kubernetes/kubernetes/issues/23564

That issue was closed as working as designed. Metadata is not treated as less confidential than main object content by encryption at rest or authorization.
