### ISSUE TITLE
/etc/hosts is overwritten despite code stating it should not be overwritten

### ISSUE THREAD

**Issue by jstangroome** [kubernetes/kubernetes#44473] opened 2017-04-13 22:51 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): etc/hosts exists overwritten

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Minikube on Virtualbox 5.1.18 on Windows 10 64-bit
- **OS** (e.g. from /etc/os-release): Minikube's boot2docker OS
- **Kernel** (e.g. `uname -a`): Linux minikube 4.7.2 #1 SMP Fri Apr 7 10:38:40 PDT 2017 x86_64 GNU/Linux
- **Install tools**: Minikube 0.18.0
- **Others**:

**What happened**:
The `/etc/hosts` file in a container is modified every time a container is (re-)created in a Pod. This includes between a Pod's Init-Container completing and the Pod run-time containers starting.

**What you expected to happen**:
The `/etc/hosts` file should be written once at Pod initialization as per the source code at https://github.com/kubernetes/kubernetes/blob/v1.6.0/pkg/kubelet/kubelet_pods.go#L188-L192

**How to reproduce it** (as minimally and precisely as possible):
Create a Pod with an Init-Container that appends a comment to the end of its `/etc/hosts` file then run `cat /etc/hosts` in a run-time container of the Pod and see the appended comment is lost.

Can also be done with a multi-container Pod where one container fails to stay running and gets recreated.

**Anything else we need to know**:
The method for checking that the `/etc/hosts` file exists has a bug:
`if _, err := os.Stat(fileName); os.IsExist(err) {`
https://github.com/kubernetes/kubernetes/blob/v1.6.0/pkg/kubelet/kubelet_pods.go#L189

`os.Stat` on an existing file returns `err` of `nil` and then `os.IsExist(nil)` returns false so the if block is not executed and the file gets overwritten.

Repro of this Stat and IsExist behaviour: https://play.golang.org/p/mWKjRDYUbF

**Comment by jstangroome** [comment] 2017-04-13 23:00
It may be as trivial to just change the if line to:
`if _, err := os.Stat(fileName); err = nil {`

But it may be more idiomatic to change the overall implementation of the function and use the following to avoid a race-condition in between `stat`-ing the file and writing it:
`if file, err := os.OpenFile(fileName, O_CREATE, 0644), os.IsExist(err) {`

**Comment by ivan-section-io** [comment] 2017-04-13 23:11
With a high chance of several containers starting at the same time, I feel may be worth the extra few lines to avoid such `os.stat`/`osutil.WriteFile` race state, and do a single `os.OpenFile`, write & close. (I haven't personally tested `os.OpenFile( ..., os.O_WRONLY|os.O_CREATE, ..)` returns `err` on existing files - but I believe it should)

**Comment by supereagle** [comment] 2017-04-14 02:12
@jstangroome   Yes, this code really has error. Thanks for your report. I will fix this in a PR.

**Comment by kargakis** [comment] 2017-04-14 17:05
@kubernetes/sig-node-bugs

**Comment by dchen1107** [comment] 2017-04-14 20:48
I believe the issue was exist from day one since Kubelet generates its own /etc/hosts to workaround a issue from docker, and this is not a regression from 1.6. Marked it for 1.7 milestone. Please feel free to send us a pr to address the issue.

**Comment by yujuhong** [comment] 2017-04-14 21:09
There is an open PR for this: #44481

**Comment by yujuhong** [comment] 2017-05-02 21:58
#43632 provides a HostAlias field in the pod spec for users to specify host entries. Given the addition of that feature, I think users should not try to modify the host in the init or application containers, and kubelet should remain the authority of this file unless users explicitly mount this path.
@jstangroome, is the new HostAlias sufficient for your use case?

**Comment by supereagle** [comment] 2017-05-03 02:57
New HostAlias is a great work. What about the PR #44481? The origin code really has logical error, and the etc-hosts file is overwritten every time. In order to keep the ip, host name and domain name in etc-hosts file up to date, maybe this code can be removed.

**Comment by jstangroome** [comment] 2017-05-03 04:25
@yujuhong Yes, from reading the commits in #45148 it appears that HostAlias in the pod spec will remove the need for me to modify the `/etc/hosts` file directly from within an init or app container for my current use case.

**Comment by yujuhong** [comment] 2017-05-03 21:29
@jstangroome that's great. I think we can close this issue.

@supereagle we can verify the content of the file to see if it's up-to-date, but I think for now, removing the check is fine. Thanks!

**Closed** 2017-05-03 21:33 UTC
Labels: area/kubelet, kind/bug, sig/node

**Comment by supereagle** [comment] 2017-05-04 06:13
@yujuhong  Have submitted the PR #45329 to remove it. PTAL.
