### ISSUE TITLE
Prioritize static pods 

### ISSUE THREAD

**Issue by joshk0** [kubernetes/kubernetes#35477] opened 2016-10-25 01:08 UTC
I'm running Kubernetes 1.4 in GKE and I had a runaway pod eat up all my disk. The new disk based eviction tossed out all the pods in response. (I then hit #35406 , but that's unrelated to this issue.) 

In the aftermath, I found that absolutely no pods were running on the machine, including kube-proxy. When I cleaned up the node, I found that service IPs didn't resolve, and I assumed that this was because of the absence of the kube-proxy. After rebooting the node, the kube-proxy came back and everything went back to normal. Unfortunately, I did not keep kubelet logs before rebooting.

As kube-proxy is a special kubelet pod, it's not easy to issue API commands to restore it. It seems reasonable for there to be a basic health check on kube-proxy at the kubelet level, which will trigger its recreation if it for any reason goes away, or at the very least, mark the node unhealthy.

**Comment by yujuhong** [comment] 2016-10-27 18:27
Related issue: #35521

**Comment by bprashanth** [comment] 2016-10-27 18:49
Yeah there are 2 parts to this, I think:     

1. Don't treat a static pod rejection as final, because the manifest is already on the  node so it *cannot* possibly run anywhere else
2. Assume static pods are the most important because they manage shared node resources for all the other pods on the node (iptables, logs etc)

What about resources on the master? I still want a way to sacrifice fluent before apiserver.

**Comment by bprashanth** [comment] 2016-10-27 18:52
retitiled because this isn't specific to kube-proxy, how will this work for daemons?

**Comment by yujuhong** [comment] 2016-10-27 18:53
Related issue on preemption: #22212

**Comment by bprashanth** [comment] 2016-10-27 18:56
So I guess 1 is fixed with the mentioned pr? 
If so we can probably close as a dupe of 22212

**Comment by yujuhong** [comment] 2016-10-27 19:06
> It seems reasonable for there to be a basic health check on kube-proxy at the kubelet level, which will trigger its recreation if it for any reason goes away, or at the very least, mark the node unhealthy.

Neither of the two addresses this, but I don't think kubelet should treat any pod specially.

**Comment by dchen1107** [comment] 2016-10-31 22:05
I am closing this one in favor of https://github.com/kubernetes/kubernetes/issues/22212: cc/ @davidopp 

* Kube-proxy shouldn't be special pod to Kubelet
* Instead, we should have a generic way describing preemption priority / eviction cost described in #22212.

**Closed by dchen1107** 2016-10-31 22:05 UTC
Labels: component/kube-proxy, team/node
