### ISSUE TITLE
CRD: Top level x-kubernetes-preserve-unknown-fields breaks kubectl explain

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/kubernetes#104419] opened 2021-08-17 17:05 UTC
#### What happened:

`kubectl explain` breaks when used on a CRD with a top level `x-kubernetes-preserve-unknown-fields: true`.

#### What you expected to happen:

A coworker encountered this and I'm not sure what the expected behavior is. I think I'd expect either a validation error if this is is invalid or `kubectl explain` to still output descriptions and fields.

#### How to reproduce it (as minimally and precisely as possible):

<details>
<summary>Without top level `x-kubernetes-preserve-unknown-fields`:</summary>

```
cat <<EOF > crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          # x-kubernetes-preserve-unknown-fields: true
          type: object
          description: I am the top level description
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
    - ex
EOF

kubectl apply -f crd.yaml

kubectl explain example
```

```
KIND:     Example
VERSION:  kuberneddies.dev/v1

DESCRIPTION:
     I am the top level description

FIELDS:
   apiVersion   <string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
...
```
</details>

<details>
<summary>With top level `x-kubernetes-preserve-unknown-fields`:</summary>

```
cat <<EOF > crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          description: I am the top level description
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
    - ex
EOF

kubectl apply -f crd.yaml

kubectl explain example
```

```
KIND:     Example
VERSION:  kuberneddies.dev/v1

DESCRIPTION:
     <empty>
```
</details>

#### Anything else we need to know?:

I'm not too familiar with this extension and this could indeed be the expected behavior.

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

/sig cli
/sig api-machinery
/area custom-resources
/area kubectl

cc @Shreya027

**Comment by fedebongio** [comment] 2021-08-17 20:18
After triage, these seems to be a kubectl problem. The field is valid on a crd from an api-machinery perspective
/remove-sig api-machinery

**Comment by eddiezane** [comment] 2021-08-18 16:07
@apelisse any thoughts on this? I'll check what the OpenAPI is actually returning later.

**Comment by apelisse** [comment] 2021-08-18 16:13
Yeah, that's mostly an api-machinery problem actually.
/sig api-machinery
/triage accepted

Not that we can do anything about it though. preserve-unknown-field have their schema replaced by "accept-all" because of how kubectl handles schema. There are two ways we can fix that:
1. Have better schemas, we're working on that @Jefftree 
2. Remove kubectl validation which is forcing us to have terrible schemas @kevindelgado 

We're definitely working on improvements in that area that will fix this bug eventually, but nothing trivial.

**Comment by Shreya027** [comment] 2021-08-20 06:44
Hi,

Just following up on the issue. I tried running the command  `kubectl explain mesh` with CRD version v1beta with `CRD_OPTIONS ?= "crd:trivialVersions=true,crdVersions=v1beta1,preserveUnknownFields=false"`. The explain functionality works for me as shown below, but some of the unknown fields get dropped as expected. 



```
aws-app-mesh-controller-for-k8s % kubectl explain mesh
KIND:     Mesh
VERSION:  appmesh.k8s.aws/v1beta2

DESCRIPTION:
     Mesh is the Schema for the meshes API

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec	<Object>
     MeshSpec defines the desired state of Mesh refers to
     https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_MeshSpec.html

   status	<Object>
     MeshStatus defines the observed state of Mesh
```

If I set `preserveUnknownFields=true`  in CRD_OPTIONS for v1beta, I am not able to render all the fields on kubectl explain, similar to the issue faced in CRD version v1.

```
aws-app-mesh-controller-for-k8s % kubectl explain mesh
KIND:     Mesh
VERSION:  appmesh.k8s.aws/v1beta2

DESCRIPTION:
     <empty>
```

Is there any way I can make `kubectl explain` work with either CRD version v1 or v1beta1 without dropping the unknown fields?

**Comment by apelisse** [comment] 2021-08-20 16:08
I would strongly suggest we don't invest too much time on this right now, since @Jefftree is working on some related improvements that will help build better versions of explain.

**Comment by liggitt** [comment] 2021-08-22 01:08
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/95702#issuecomment-713548542 and is intentional / necessary for compatibility with kubectl. 

Unfortunately, publishing any schema details causes kubectl to start enforcing client-side validation, which effectively breaks kubectl create/apply when sending a resource containing fields not represented in the schema.

In other words, if the schema indicates it expects unknown fields, we cannot publish a schema or you won't be able to create/apply those unknown fields with kubectl.

**Comment by liggitt** [comment] 2021-08-29 01:28
This is working as intended, though it should probably be better documented as a consequence of using preserveUnknownFields

**Comment by sttts** [comment] 2021-08-31 16:22
+1 for better documentation. I am very hestitant encouraging use of `x-kubernetes-preserve-unknown-fields: true` by enabling advanced features. This was meant as a last chance to move into structured schema world after sins of bad API design in the past.

**Comment by apelisse** [comment] 2021-08-31 16:34
I think we can solve this with OpenAPI v3, no?

**Comment by liggitt** [comment] 2021-09-01 20:33
> I am very hesitant encouraging use of x-kubernetes-preserve-unknown-fields: true by enabling advanced features. 

I agree. Any CRD using `x-kubernetes-preserve-unknown-fields` is opting into persisting potentially problematic data (problematic in size or in schema/type/structure) and is *usually* questionable.

> I think we can solve this with OpenAPI v3, no?

we should include all schema information available when we start publishing openapi v3, but for openapi v2 purposes, this is working as intended

**Closed** 2022-01-29 21:18 UTC
Labels: kind/documentation, area/kubectl, sig/api-machinery, sig/cli, area/custom-resources, lifecycle/rotten, triage/accepted
