### ISSUE TITLE
Unit test failures for volume/fc & iscsi.  Detach not called

### ISSUE THREAD

**Issue by kpgriffith** [kubernetes/kubernetes#40099] opened 2017-01-18 19:56 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:  Dev
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  MacOS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When running `make test` the following errors occur

```
--- FAIL: TestPluginVolume (0.01s)
	fc_test.go:197: Detach was not called
--- FAIL: TestPluginPersistentVolume (0.00s)
	fc_test.go:197: Detach was not called
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/fc	0.109s

--- FAIL: TestPluginVolume (0.00s)
	iscsi_test.go:197: Detach was not called
--- FAIL: TestPluginPersistentVolume (0.00s)
	iscsi_test.go:197: Detach was not called
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/iscsi	0.106s

FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/names [build failed]
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
A few other people tried it and reproduced the failures.

**Comment by calebamiles** [comment] 2017-01-19 00:44
could someone from @kubernetes/sig-storage-misc please take a look? thanks!

**Comment by rootfs** [comment] 2017-01-19 01:11
I don't think kubelet (and many related pkg) can run on mac.

**Comment by rootfs** [comment] 2017-01-19 01:23
`DetachDisk` calls `mont.GetMountRefs`, which in turn calls out OS specific `List`. `List` is a no-op on Mac.

**Comment by kpgriffith** [comment] 2017-01-24 02:38
@rootfs do we need to change something so it skips the tests on a mac or do we just leave it alone and understand it fails when on a mac?  Not sure what to do from here.  Thanks.

**Comment by rootfs** [comment] 2017-02-08 16:03
@kpgriffith there doesn't seem to be a switch in unit test yet, but it is not hard to make one

**Comment by ianchakeres** [comment] 2017-05-07 19:30
**I was unable to reproduce this issue on my Mac. I am running commit 79a2e35 from master on 2017-05-05.**

**Environment**: Dev

* **Cloud provider or hardware configuration**:
* **OS**: MacOS 10.12.14
* **Kernel**: Darwin Kernel Version 16.5.0
* **Install tools**: Go1.8.1
* **Others**:
**What happened**:

**I was unable to reproduce this issue on my Mac. I am running 79a2e35.**

```
$ make test WHAT=./pkg/volume/fc KUBE_GOFLAGS="-v"

Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0507 12:17:40] Running tests without code coverage
=== RUN   TestCanSupport
--- PASS: TestCanSupport (0.00s)
=== RUN   TestGetAccessModes
--- PASS: TestGetAccessModes (0.00s)
=== RUN   TestPluginVolume
--- PASS: TestPluginVolume (0.00s)
=== RUN   TestPluginPersistentVolume
--- PASS: TestPluginPersistentVolume (0.00s)
=== RUN   TestPersistentClaimReadOnlyFlag
--- PASS: TestPersistentClaimReadOnlyFlag (0.00s)
=== RUN   TestIoHandler
--- PASS: TestIoHandler (0.00s)
PASS
ok  k8s.io/kubernetes/pkg/volume/fc0.126s

$ make test WHAT=./pkg/volume/iscsi KUBE_GOFLAGS="-v”

Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0507 12:19:56] Running tests without code coverage
=== RUN   TestCanSupport
--- PASS: TestCanSupport (0.00s)
=== RUN   TestGetAccessModes
--- PASS: TestGetAccessModes (0.00s)
=== RUN   TestPluginVolume
--- PASS: TestPluginVolume (0.00s)
=== RUN   TestPluginPersistentVolume
--- PASS: TestPluginPersistentVolume (0.00s)
=== RUN   TestPersistentClaimReadOnlyFlag
--- PASS: TestPersistentClaimReadOnlyFlag (0.00s)
=== RUN   TestPortalMounter
--- PASS: TestPortalMounter (0.00s)
=== RUN   TestGetDevicePrefixRefCount
--- PASS: TestGetDevicePrefixRefCount (0.00s)
=== RUN   TestExtractDeviceAndPrefix
--- PASS: TestExtractDeviceAndPrefix (0.00s)
=== RUN   TestExtractIface
--- PASS: TestExtractIface (0.00s)
=== RUN   TestExtractPortalAndIqn
--- PASS: TestExtractPortalAndIqn (0.00s)
=== RUN   TestExtractTransportname
--- PASS: TestExtractTransportname (0.00s)
=== RUN   TestWaitForPathToExist
--- PASS: TestWaitForPathToExist (0.00s)
PASS
ok  k8s.io/kubernetes/pkg/volume/iscsi0.128s
```

**Comment by techtonik** [comment] 2017-05-23 02:52
@kpgriffith can you confirm that the problem is resolved with the recent Go and k8s?

**Comment by kpgriffith** [comment] 2017-05-23 14:50
@techtonik Yeah, let me double check, will let you know.

**Comment by kpgriffith** [comment] 2017-05-23 18:21
@techtonik I get the same results as @ianchakeres 

I can't reproduce the issue now either.  Thanks.

**Comment by techtonik** [comment] 2017-05-23 19:08
@kpgriffith nice. You can close the issue then, :wink:

**Closed** 2017-05-23 21:58 UTC
Labels: area/test, kind/bug, sig/storage
