### ISSUE TITLE
e2e flake: minion-group never becomes stable

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#25760] opened 2016-05-17 17:41 UTC
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25672/kubernetes-pull-build-test-e2e-gce/40216/

```
[...]
Waiting for group to become stable, current operations: creating: 6
Waiting for group to become stable, current operations: creating: 4,recreating: 2
Waiting for group to become stable, current operations: creating: 6
[...]
Waiting for group to become stable, current operations: creating: 6
Waiting for group to become stable, current operations: creatingTerminated
[...]
```

Assigning to team/control-plane because I know at least @mikedanese has worked on cluster deployment.

**Comment by fejta** [comment] 2016-05-23 22:36
Assigning to @mikedanese per @ihmccreery comment

**Comment by mikedanese** [comment] 2016-05-23 23:32
I'm going to push back onto the test-infra team. There is nothing in the logs that indicated what failed. No logs were collected from any instance. Without more information, I can't know what actually happened. This is not possible for me to investigate.

**Comment by mikedanese** [comment] 2016-05-23 23:33
Transient GCE issues can cause this behavior. What would we do to fix this if that turned out to be the cause? Regardless, seems like we need more debug info.

cc @ixdy

**Comment by ixdy** [comment] 2016-05-23 23:51
At little earlier in the log, you can see that the issue is quota:
```
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 150.0
```
This probably happened during the fire we had last week when the node e2e tests were leaking VMs everywhere.

Who owns the `cluster/gce` scripts? Better error handling/logging of cluster turn-up probably belongs to them.

**Comment by mikedanese** [comment] 2016-05-23 23:59
ugh. :) I will reclaim. Thanks for the tip @ixdy

**Comment by dims** [comment] 2016-06-06 19:11
based in "This probably happened during the fire we had last week when the node e2e tests were leaking VMs everywhere." comment, can we close this?

**Comment by davidopp** [comment] 2016-06-08 07:53
I think "Better error handling/logging of cluster turn-up" sounds worth doing, to reduce how long it takes us to debug flakes in the future, but this isn't directly a flake, so I'm going to remove the flake label and upgrade to P1.

**Closed** 2018-02-27 18:23 UTC
Labels: lifecycle/rotten, priority/important-soon, sig/testing, team/control-plane (deprecated - do not use)
