### ISSUE TITLE
integration flake: kubectl delete pods

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19403] opened 2016-01-08 09:47 UTC
```
pod "redis-proxy" deleted
Error from server: pods "valid-pod" not found
E0108 09:35:06.910405   19228 nodecontroller.go:349] pods "redis-proxy" not found
!!! Error in ./hack/test-cmd.sh:383
  'kubectl delete pods valid-pod redis-proxy "${kube_flags[@]}" --grace-period=0' exited with status 1
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/f5a41823c2b988f158d12322bf89cd6113190f0c/kubernetes-pull-test-unit-integration/8470/build-log.txt

cc @janetkuo @kubernetes/goog-ux @ixdy @lavalamp

**Comment by gmarek** [comment] 2016-01-11 10:24
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/d3d4bdf34319c8ad2903c415a93e776b177776c2/kubernetes-pull-test-unit-integration/8354/

**Comment by bgrant0607** [comment] 2016-01-21 23:25
@caesarxuchao PTAL

**Comment by caesarxuchao** [comment] 2016-01-26 21:12
The root cause is that the node controller and kubelet delete the pods using their names (they should use UID instead):
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L349
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/manager.go#L384
(this is not an exhaustive list)

In test-cmd.sh, we create and delete the same pod multiple times, so it's possible that  the node controller or the kubelet sends a deletion request api server, with the intention to delete the N*th* occurrence of a pod, while it's actually deleting the N+1*th* occurrence of the pod.

To reproduce the flake, I introduced a random delay between 500~1500 ms in the node controller's execution path (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L309), then using a script to create/delete a pod repeatedly, and the flake will occur after several rounds.

@dchen1107 @kubernetes/goog-control-plane

**Comment by mikedanese** [comment] 2016-01-26 21:16
Why is it not okay to delete by name?

**Comment by caesarxuchao** [comment] 2016-01-26 21:20
namespace+name pair is not an unique identifier across time.

**Comment by caesarxuchao** [comment] 2016-01-26 21:22
@lavalamp, the client library and the API server don't support deletion by UID, I think we should support.

**Comment by lavalamp** [comment] 2016-01-26 21:28
Thanks!! My thoughts:

1. Why does node controller care about these pods? I'm pretty sure the original author wasn't expecting that.
2. As a temporary fix, is it hard to just use new names for every incarnation of these pods?

**Comment by lavalamp** [comment] 2016-01-26 21:30
Deleting by UID is probably a bigger can of worms than we want to open right now, although it will eventually be important.

Thinking out loud here, but maybe it'd be possible to add a resource version to the delete command. I.e., "delete only if it hasn't changed since rv=xxxxx".

But I still think it's probably ideal to turn off the node controller for this test.

**Comment by caesarxuchao** [comment] 2016-01-26 21:36
> 1. Why does node controller care about these pods? I'm pretty sure the original author wasn't expecting that.

I'm also thinking if we can centralize all the pod deletion logic into kubelet, but it seems some of the logic need to stay in the node controller, e.g, [this one](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L325), because only the node controller knows if the node exists.

[This](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L309) deletion probably can be done by the kubelet.

**Comment by mikedanese** [comment] 2016-01-26 21:39
> Why does node controller care about these pods? I'm pretty sure the original author wasn't expecting that.

Looks like node controller is getting an update of the pod where DeleteionTimestamp is set, which seems like a bug if --grace-period is set to 0. My understanding is that if grace period is zero, the pod should get immediately deleted.

> This deletion probably can be done by the kubelet.

That deletion will never make it to the kubelet because it hasn't been scheduled yet. I'm pretty sure none of those deletions can be handled in the kubelet.

**Comment by caesarxuchao** [comment] 2016-01-26 21:47
Btw, when running hack/test-cmd.sh ([sample log](https://00e9e64baca2815b82403596dc2ecd7bfd2467925931af290a-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fd3d4bdf34319c8ad2903c415a93e776b177776c2%2Fkubernetes-pull-test-unit-integration%2F8354%2Fbuild-log.txt?qk=AD5uMEvY566tJnz5QAuEvy11JnnwNNQyE6lyq4Onn-6mqnFXl1hvhvm5sgeyeNpe3sCNUbi2rXbKWxjJHEe6eo88-pcCfkMOJ8QeWJFQQXez_0xGG6ddLDL2F-61wVMShx2C-I3rm2_n_LnvZPcBRuQIdqucJSGGYZy9jdDAGoYf-OT9OWYRw9H7o4-Q56MoSZBG5lavOmdf-DUEzxBAnSp8Ktk3jwsjitV1uzSOnIf5YUJboQ0ZNt1kIK0YEdQBkVs-jFsm229krEWXlxl_qtr5Hxk6Zcm12petZCAjUEneyQ6FiwoyMx3BaXJX1g7RJonu1fvGcs1Tkmostlw7bdRXafNI-2a_FYQZwZ8PUHuj4qUrdPshCz7xIWmPUZW7mn3EGnOCVwrJLbxJHErIUj3_owm3Z8fKythsQ19NTskEVOM9zKCy1XdBtKGCFw7M3AvdyUU1FUDvjgI5V5jtpwVfwdme4a8_At0iipbOuH1q6RmMzggpq5yivRbUSX7p4E8oywuRoRML_tTAReCl7F-8V2JolLqbhDNbM_o5Xg_5jppQjX_vnNoMwyvB1Q-imn-R_IUUKpO_n9H833KnHeyNUyqn3IXF_2KeX_HAKyB34-b3Vyxc4m_9F7wdv3RcBAS2rStHbLVGbJ5cwiAD04kfLj5_qJryEB-AJ7kXrvpMyQgFbVE9v4ecch7H5nsb29YGh3p1v0l2VwEm0teiidqdvstqt9xruIZTnk-Aq9xlOEt4L35xSyqdKDpeNcb_joDthTY1ChYA3evemESE7rWFwZcvnqeLp4ELakaSB9o4NKNwQVbUZcTrTx67W4SzYc7l0qG-CDZ7JJ3SQbgwhmnm_CPffPyYTvGJ6NaxbKT-fVaX9NM0RR1ZgUMLl0ByBWfX3Pyj39DEXO9FyG9qutKHtJWctQP53sXo6xC82zPVCFxPSXdXvfd-j3ystO_rq1nljVvDP6C04o1i5fbIc5ouXgv-biNsaA)), the node controller generates many messages about the failed deletions: `100: Key not found (/registry/pods/default/valid-pod)` or `...nodecontroller.go:349] pods "valid-pod" not found`, those are because kubelet wins the race and has deleted the pods.

**Comment by caesarxuchao** [comment] 2016-01-26 21:49
> Looks like node controller is getting an update of the pod where DeleteionTimestamp is set, which seems like a bug if --grace-period is set to 0. My understanding is that if grace period is zero, the pod should get immediately deleted.

I think kubelet will delete such pods immediately, so it's not a bug. The node controller will try to delete such pods again but will fail.

**Comment by lavalamp** [comment] 2016-01-26 23:03
That's my expectation, too (that grace period being zero should bypass all graceful deletion code and just immediately delete the pod).

**Comment by caesarxuchao** [comment] 2016-01-26 23:14
When the grace period is zero, api server update the storage(https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L384), and then delete the pod from the storage (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L419). The check of if grace period is 0 is after the update(https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L403).

It seems it should not do the update if grace periods is zero.

**Comment by lavalamp** [comment] 2016-01-26 23:35
@smarterclayton Do you agree that the above is a bug?

**Comment by lavalamp** [comment] 2016-01-26 23:37
Hm, is the problem a missing or incorrect BeforeDelete handler?

**Comment by caesarxuchao** [comment] 2016-01-26 23:51
I think we are dealing with two problems here:
1. if grace-period=0, the registry shouldn't do an update.
2. the client library should provide a Delete() method that takes an unique identifier, the "name+namespace" pair is ambiguous across time.

**Comment by lavalamp** [comment] 2016-01-27 00:09
Thinking about this more, I wonder if the update is intentional. If so, we need some coordination so that both apiserver and kublet don't try to delete.

**Comment by smarterclayton** [comment] 2016-01-27 00:54
Grace period 0 is intentional, but may not be required for correct
behavior.  If the user signals delete immediately, we record that
intent so it shows up in watch and can be a signal kubelet to
terminate immediately (although we don't actually do that today, so we
could walk back the behavior).  We definitely need a precondition
delete on uid.

**Comment by smarterclayton** [comment] 2016-01-27 00:56
There will never be a single owner of pod lifecycle because pods are bound to nodes, and so all components have to deal with races to delete.

**Comment by smarterclayton** [comment] 2016-01-27 00:59
I chose to err on the side of being explicit about user intent with the update to zero out termination.  But technically explicit deletion can be the same signal.

**Comment by caesarxuchao** [comment] 2016-01-27 00:59
> If the user signals delete immediately, we record that
intent so it shows up in watch and can be a signal kubelet to
terminate immediately

A delete operation will also trigger a watch event, so kubelet will be signaled even if we skip the update right?

**Comment by lavalamp** [comment] 2016-01-27 01:48
> A delete operation will also trigger a watch event, so kubelet will be signaled even if we skip the update right?

It should be, yes.

In the interest of fixing this test in the short term, I think the easiest thing to do might be to turn off the node controller for this section of the test. (Is it needed by anything in the test?)

But we should file at least two issues: 
* "kubectl delete can race with graceful deletion"-- Things have to handle races, but there shouldn't be a race where you delete something and your delete fails because your own delete caused another component to issue a delete for the same thing... As far as I can see from the code, this could happen if apiserver context-switched at the wrong times (even if the more common thing of an old delete getting a new object is the issue at hand).
* controllers should delete via UID (or namespace/name + RV) -- I wouldn't be surprised if there's already an issue for this.

**Comment by bgrant0607** [comment] 2016-01-27 04:20
+1 to resourceVersion and uid preconditions on delete.

Yes, maybe we shouldn't update the grace period before deletion in the case that the grace period is 0.

Why can't we use unique pod names in the test? Turning off node controller seems like a bad idea.

Index by uid is #4817.

**Comment by caesarxuchao** [comment] 2016-01-27 06:45
I don't see any flag option to turn of node controller.

> Why can't we use unique pod names in the test?

Pod's name is specified in the config file, is there any clean way to change the pod's name each time `kubectl create -f` is called?

Anyway, I'll try to make a PR to skip update if grace period is 0. That should alleviate this flake.

**Comment by dchen1107** [comment] 2016-01-28 23:15
cc/ @erictune in case you are running into this issue.

**Comment by bgrant0607** [comment] 2016-02-01 19:25
@caesarxuchao As for how to change the name: we could use sed to replace the name. Or we could change the namespace.

**Comment by caesarxuchao** [comment] 2016-02-03 19:33
This should be fixed by #20202.

I filed #20572 for deletion via UID or namespace/name+resourceVersion.

**Comment by piosz** [comment] 2016-03-02 10:42
This happened again:
```
pod "redis-proxy" deleted
Error from server: error when stopping "docs/user-guide/multi-pod.yaml": pods "redis-master" not found
E0302 01:11:15.856525    7784 nodecontroller.go:331] pods "redis-proxy" not found
!!! Error in ./hack/test-cmd.sh:624
  'kubectl delete -f docs/user-guide/multi-pod.yaml "${kube_flags[@]}"' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:624 runTests(...)
  2: ./hack/test-cmd.sh:1657 main(...)
Exiting with status 1
```
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/22171/kubernetes-pull-test-unit-integration/17070/

**Comment by aveshagarwal** [comment] 2016-03-02 14:42
This error  "nodecontroller.go:331] pods "redis-proxy" not found" here seems related to the error in https://github.com/kubernetes/kubernetes/issues/22271 .

**Comment by caesarxuchao** [comment] 2016-03-02 18:12
I think the issue in #22271 is the same.
The last few lines of logs:
```
(BE0302 01:11:15.841086    7784 nodecontroller.go:331] <nil>
pod "redis-proxy" deleted
Error from server: error when stopping "docs/user-guide/multi-pod.yaml": pods "redis-master" not found
E0302 01:11:15.856525    7784 nodecontroller.go:331] pods "redis-proxy" not found
```
The symptom seems to align with my hypothesis in https://github.com/kubernetes/kubernetes/issues/22271#issuecomment-191097981. `nodecontroller.go:331] <nil>` suggests the nodecontroller has successfully deleted a pod (probably "redis-master"), so kubectl fails with `pods "redis-master" not found`. I'll add more logs in nodecontroller to make sure this is the problem.

In fact, we knew this race condition when investigating #19403, but we discovered other race condition that are more likely to happen so we didn't solve this one.

**Comment by caesarxuchao** [comment] 2016-03-02 19:29
Sent #22376 to show what pod nodecontroller has deleted.

**Comment by bgrant0607** [comment] 2016-03-03 01:28
Anywhere where we delete lists of pods (and other resources), including those filtered by label selector, we should ignore not-found errors. There are such loops in the controller reapers for cascading deletion.

cc @janetkuo @kargakis @soltysh

**Comment by caesarxuchao** [comment] 2016-03-03 02:12
#22048 makes `kubectl delete` safely ignore the NotFound error. #22408 forces `kubectl delete` to issue a "GET" before submitting "DELETE". The "GET" will effectively check if the user is trying to delete a resource that is never created, so if later the API server sends a NotFound error in response to the "DELETE" request, kubectl can safely ignore it.

**Closed** 2016-03-04 05:10 UTC
Labels: kind/flake, priority/P0, team/ux
