### ISSUE TITLE
cronjobs do not honor defined schedules

### ISSUE THREAD

**Issue by robbinscp** [kubernetes/kubernetes#86647] opened 2019-12-26 19:34 UTC
**What happened**:

Cronjobs do not run on the specified schedule defined in the spec.  Some jobs seem to be "missed" by the scheduler.  Usually this recovers on its own, but it would be nice to have some sort of validation that this is either expected behavior or that there is something wrong with the cronjob system.  

For example, I have a cronjob that runs every 5 minutes called `dns-checker`.  If I review the events for the cronjob, I can see a 10 minute gap between the last scheduled job and the next one. 

```  
  Normal  SawCompletedJob   19m    cronjob-controller  Saw completed job: dns-checker-1577386500
  Normal  SuccessfulCreate  9m27s  cronjob-controller  Created job dns-checker-1577387100
  Normal  SawCompletedJob   9m7s   cronjob-controller  Saw completed job: dns-checker-1577387100
```
If I run `kubectl get cronjob` I can see similar output - jobs should run every 5 minutes but the last schedule time is over 5 minutes.

```
$ kubectl get cronjob -n mis
NAME          SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
dns-checker   */5 * * * *   False     0        6m29s           140d
drupal-cron   */1 * * * *   False     1        89s             328d
```

**What you expected to happen**:

A cronjob runs per the schedule defined.  

**How to reproduce it (as minimally and precisely as possible)**:

Apply the following spec noted below (non-pertinent env variables/identifiers removed)

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2019-08-07T22:37:15Z"
  name: dns-checker
  namespace: mis
  resourceVersion: "328215361"
  selfLink: /apis/batch/v1beta1/namespaces/mis/cronjobs/dns-checker
  uid: e819a817-b963-11e9-a7ed-0e147f95f294
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - --preserve-status
            - "30"
            - /usr/local/bin/dns-checker
            command:
            - /usr/bin/timeout
            image: ops:latest
            imagePullPolicy: Always
            name: dns-checker
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  startingDeadlineSeconds: 6
  successfulJobsHistoryLimit: 3
  suspend: false

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS EKS, version 1.14
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): 
```
$ uname -a
Linux ip-10-0-31-250.ec2.internal 4.14.146-119.123.amzn2.x86_64 #1 SMP Mon Sep 23 16:58:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: Deployed using AWS CloudFormation
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by thehackercat** [comment] 2020-01-03 04:30
+1

**Comment by johnbatty** [comment] 2020-02-26 15:07
I have a similar issue - a daily cronjob that fails to get scheduled around 1 in 5 days. 
Server version is 1.17.1

```
Name:                          qs-dependabot
Namespace:                     <redacted>
Labels:                        <none>
Annotations:                   <none>
Schedule:                      1 0 * * *
Concurrency Policy:            Replace
Suspend:                       False
Successful Job History Limit:  10
Failed Job History Limit:      5
Starting Deadline Seconds:     10s
Selector:                      <unset>
Parallelism:                   1
Completions:                   1
Pod Template:
  Labels:  <none>
  Containers:
   qs-dependabot:
    Image:      <redacted>
    Port:       <none>
    Host Port:  <none>
    Environment Variables from:
      qs-dependabot-env  Secret  Optional: false
    Environment:         <none>
    Mounts:              <none>
  Volumes:               <none>
Last Schedule Time:      Tue, 25 Feb 2020 00:01:00 +0000
Active Jobs:             <none>
Events:                  <none>
```
Here you can see that it failed to get scheduled last night and 4 days ago:
```
NAME                                  READY   STATUS      RESTARTS   AGE
qs-dependabot-1581724860-fmzh8        0/1     Completed   0          11d
qs-dependabot-1581811260-6chgd        0/1     Completed   0          10d
qs-dependabot-1581897660-qr4cb        0/1     Completed   0          9d
qs-dependabot-1581984060-nlfnf        0/1     Completed   0          8d
qs-dependabot-1582070460-4pcrd        0/1     Completed   0          7d15h
qs-dependabot-1582156860-pbxsl        0/1     Completed   0          6d15h
qs-dependabot-1582243260-67gg9        0/1     Completed   0          5d15h
qs-dependabot-1582416060-h5hnx        0/1     Completed   0          3d15h
qs-dependabot-1582502460-lcxn7        0/1     Completed   0          2d15h
qs-dependabot-1582588860-2gkd9        0/1     Completed   0          39h
```

**Comment by johnbatty** [comment] 2020-02-26 15:13
After a bit of digging, I think that the problem might be the value of "Starting Deadline Seconds".  In my case this is 10 secs, in the original problem report it is 6 secs.

It turns out that the k8s cronjob controller runs every 10s...
https://github.com/kubernetes/kubernetes/blob/392bf0adef478175b9cf0226b02820eb1820f797/pkg/controller/cronjob/cronjob_controller.go#L95-L96

If the scheduler is too late, then it just skips the schedule:
k8s controller scheduling code...
https://github.com/kubernetes/kubernetes/blob/392bf0adef478175b9cf0226b02820eb1820f797/pkg/controller/cronjob/cronjob_controller.go#L268-L284

So looks like the solution here is to either remove the "Starting Deadline Seconds" field, or set it to a value significantly bigger than 10 secs.

Ideally `k8s` would document and enforce a minimum value here.

I ended up with 10s in my template because I copied the Terraform cronjob example:
https://www.terraform.io/docs/providers/kubernetes/r/cron_job.html

**Comment by johnbatty** [comment] 2020-02-26 15:18
I have changed my value of "Starting Deadline Seconds", but will take a week to confirm whether this fixes the issue.

Note that if the schedule is skipped, then the cronjob controller does trigger a warning event. However it turns out that events time out and disappear after only an hour(!) by default which could explain why I haven't seen these.
https://github.com/kubernetes/kubernetes/issues/52521

**Comment by thehackercat** [comment] 2020-07-23 02:15
cf https://github.com/kubernetes/kubernetes/pull/93370

**Comment by soltysh** [comment] 2020-09-21 19:19
This seems like it's a potential duplicate of https://github.com/kubernetes/kubernetes/issues/90801 I'm going to close this one and please move the discussion there.
/close

**Closed** 2020-09-21 19:19 UTC
Labels: area/workload-api/cronjob, kind/bug, sig/apps
