### ISSUE TITLE
Load Balancer retry error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31007] opened 2016-08-19 16:12 UTC
k8s 1.3.4

A user reported this error:

```
E0817 18:07:37.390133       1 servicecontroller.go:201] Failed to process service delta. Retrying in 5s: Failed to create load balancer for service redacted/redacted: error configuring load-balancer health-check: Throttling: Rate exceeded
    status code: 400, request id: 7acaa199-64a5-11e6-841e-d35a3e64a7ff
```

followed by:

```
W0817 18:07:47.495294       1 reflector.go:334] pkg/controller/service/servicecontroller.go:150: watch of *api.Service ended with: couldn't queue object: couldn't create key for object &{lastState:0xc820d72340 appliedState:<nil> mu:{state:0 sema:0} lastRetryDelay:10000000000}: object has no meta: struct service.cachedService lacks embedded TypeMeta type
```

We probably should check that we aren't doing something silly in AWS that causes us to hit the rate limit, but in any case it looks like we have a bug (type conversion error?) in the service controller requeue logic.

**Comment by justinsb** [comment] 2016-08-19 16:14
cc @alph486

**Comment by petetnt** [comment] 2016-08-22 05:47
FWIW I am also seeing similar kinds of errors in a AWS hosted cluster

```
W0822 05:41:08.147462       1 reflector.go:334] pkg/controller/service/servicecontroller.go:150: watch of *api.Service ended with: couldn't queue object: couldn't create key for object &{lastState:0xc820e524e0 appliedState:0xc820e524e0 mu:{state:0 sema:0} lastRetryDelay:0}: object has no meta: struct service.cachedService lacks embedded TypeMeta type
```

**Comment by justinsb** [comment] 2016-08-22 15:27
@mfanjie @bprashanth do you understand this error? I poked around the code but can't see where it is coming from?  Will it be resolved by #25189 in 1.4?  And is there something we can backport, and is it important?

So many questions :-)

**Comment by bprashanth** [comment] 2016-08-22 17:24
The `cachedService` object it's complaining about is a an internal construct that doesn't have a metadata field. The normal key lookup functions rely on api objects having an embedded `ObjectMeta` that they can grab the ns/name key from. It looks like we were/are(?) trying to store/retrieve a cachedService into a store that has a keyfunc that constructs the key from the objectMeta as described (eg: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/store.go#L51), which won't work.

A more specific repro would help zero in on where we're doing this.

**Comment by alph486** [comment] 2016-08-22 17:30
@bprashanth There is another issue (unclear how related it is): https://github.com/kubernetes/kubernetes/issues/30917 . The reproduction steps there should get this error. Its not the best set of steps.. Its just what I did in my stack before I started seeing the error. But its a start.

**Comment by bprashanth** [comment] 2016-09-07 22:42
I inspected the service controller and I don't think we're trying to enqueue a non-string right now, or apply the keyFunc to a non api object. This might've been an artifact of the old service controller. Can you please check if it repros on 1.4 something? (post: https://github.com/kubernetes/kubernetes/pull/25189 basically).  

I don't think we want to backport the entire rewrite into 1.3 at this point, so I'm closing, please reopen if you'd like someone to debug the old pre-rewrite code (i.e it's actually causing issues and needs a backport ASAP).

**Closed by bprashanth** 2016-09-07 22:42 UTC
Labels: component/controller-manager, priority/P1, team/cluster
