### ISSUE TITLE
make release fails w/ rsync error

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#34309] opened 2016-10-07 08:20 UTC
When I try to `make relese`, i get the following error:

```
jsz@jsz-desk2:~/go/src/k8s.io/kubernetes$ make release
+++ [1007 10:03:27] Verifying Prerequisites....
+++ [1007 10:03:28] Building Docker image kube-build:build-e64b058fff-3-v1.6.3-9
+++ [1007 10:04:24] Creating data container kube-build-data-e64b058fff-3-v1.6.3-9
+++ [1007 10:04:26] Syncing sources to container
!!! [1007 10:05:43] Could not connect to rsync container. See build/README.md for setting up remote Docker engine.
make: *** [release] Error 1
```

**Kubernetes version** (use `kubectl version`):
```
commit 144d88b0a14a0e04de3d119ba3785dfb434c2cda
```

**Environment**:
- **Cloud provider or hardware configuration**: `GCE`

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
Linux *** 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wojtek-t** [comment] 2016-10-07 08:23
I see the same.

**Comment by gmarek** [comment] 2016-10-07 08:24
Me too. All of us are using go version go1.6.3 linux/amd64.

**Comment by colemickens** [comment] 2016-10-07 08:51
Reported here: https://github.com/kubernetes/kubernetes/issues/34300 My issue references other fixes. The other fixes may resolve this problem for some people.

**Comment by colemickens** [comment] 2016-10-07 08:51
cc: @jbeda

**Comment by MrHohn** [comment] 2016-10-07 16:31
Have the exact same issue. With the latest commit f765f5e5d007937864b4bfd49caa9701dc07da7a and go version go1.6.3 linux/amd64.

**Comment by ixdy** [comment] 2016-10-07 17:52
I think https://github.com/kubernetes/kubernetes/pull/34288 will fix this for Googlers. not sure about @colemickens' problem.

**Comment by jbeda** [comment] 2016-10-07 19:19
This is probably a dupe of #34300 but worth trying to collect more data and isolate.  Instructions from there:

First, run bash -x KUBE_VERBOSE=6 build/run.sh echo hello. This will create a lot of spew, probably. You can put that in a gist and link from here.

Second, you can comment out kube::build::stop_rsyncd_container at the end of build/common.sh and then run build/copy-output.sh. This will leave the rsync container running. We can then figure out if that one failed to launch or if can't communicate it.

Thanks!

**Comment by jbeda** [comment] 2016-10-07 19:29
Can you folks also check that you have rsync (and which version)?

**Comment by MrHohn** [comment] 2016-10-07 19:40
Checked.
```
$ rsync --version
rsync  version 3.1.0  protocol version 31
```

**Comment by MrHohn** [comment] 2016-10-07 20:43
`make quick-release` is working now. I think #34288 does fixed it.

**Comment by jbeda** [comment] 2016-10-07 20:53
@MrHohn Great!

@jszczepkowski -- can you confirm if things are working for you?  If not, some of the debug spew will be helpful.

**Comment by jszczepkowski** [comment] 2016-10-10 07:35
> can you confirm if things are working for you? If not, some of the debug spew will be helpful.

`make release` works again, thanks for the fix! I guess we can now close this issue.

**Closed** 2016-10-10 10:15 UTC
Labels: area/build-release, component/kubectl, priority/P0, team/none
