### ISSUE TITLE
flag to toggle/configure kubectl retry

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#23993] opened 2016-04-07 19:37 UTC
In #23461 I described how difficult it is to write automation around kubectl.  You want to check for errors at each stage, but you don't want the script to be so brittle that it only works if the apiserver is up and reachable 100% of the time.  Asking users (including ourselves) to add the retry logic in the shell does not seem correct, so I'd like to see us add retry logic (off by default if we want) to kubectl.

@kubernetes/kubectl

**Comment by janetkuo** [comment] 2016-04-08 06:06
How about adding flags for max retry times and retry intervals to kubectl?

**Comment by smarterclayton** [comment] 2016-04-08 15:07
What do we retry on?  Idempotent requests?  HTTP calls?

**Comment by mml** [comment] 2016-04-11 21:16
@smarterclayton asks a question which actually has two parts.  (1) Which *cases* do we retry on (500? 4xx? TCP errors?) and (2) then which requests.

For (1) I suggest for now that we only retry when we get some kind of transport error like connection refused, connect reset by peer, etc., but not on any HTTP codes.

For (2) I think we should retry every single request.  After all, what else would we expect authors of other clients to do?  In some cases we might get back 422 or 409 with the reason being that our previous attempt succeeded but we never got the response.  For a first version, it seems OK if we just produce an error in this case but one can imagine a future version where we have a flag that makes `kubectl create` behave like `mkdir -p`.

**Comment by bgrant0607** [comment] 2016-04-19 04:47
Some of these retries may be in the client library.

**Comment by smarterclayton** [comment] 2016-04-19 05:34
I would be ok with transport request level retries (we do special handling
of certain classes already, and the client library in Go is better at
distinguishing those now).

**Comment by kargakis** [comment] 2017-04-04 18:36
Dupe of https://github.com/kubernetes/kubernetes/issues/5762?

**Comment by kargakis** [comment] 2017-04-04 18:37
Btw I would love to have this. It would make bash controller loops more robust.

**Comment by kargakis** [comment] 2017-04-04 18:37
@kubernetes/sig-api-machinery-misc @kubernetes/sig-cli-misc

**Comment by adohe** [comment] 2017-04-09 06:18
@kargakis yep, kind of duplicated, so what's your opinion about this? I would like to pick this in 1.7

**Closed** 2018-02-21 03:48 UTC
Labels: area/admin, area/kubectl, lifecycle/rotten, priority/backlog, sig/api-machinery, sig/cli
