### ISSUE TITLE
Get pods for many pods is very heavy

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#6514] opened 2015-04-07 12:37 UTC
I have a 50 node cluster with 1 rc with 1500 replicas. Each pod list takes few second and saturates 4 core master for that time. This slows down the whole system including scheduler, node/pod status updates, controllers etc.

@wojtek-t

**Comment by wojtek-t** [comment] 2015-04-07 12:48
Note that listing all pods will happen in a healthy system relatively often due to #6513

**Comment by davidopp** [comment] 2015-04-07 21:54
@lavalamp suggested add a benchmark (using go benchmarking facility) using integration test mechanism in test/integration so we can track this over time.

cc/ @davidopp

**Comment by davidopp** [comment] 2015-04-07 21:54
(e.g. to distinguish etcd overloaded vs. API server slow)

**Comment by timothysc** [comment] 2015-04-08 01:54
+1 for an e2e test. Ideally I would like to collect metrics on the apiserver similar to the scheduling latency and capture that as part of an e2e.

**Comment by erictune** [comment] 2015-04-14 15:36
Something doesn't make sense.  Pods contain around 1kB of data.  1 core
should be able to process hundreds of megabytes per second or more.  Even
if it were reprocessing all the pods for some reason, (1000MB of data),
there is no way a read should saturate 4 cores for a second.

**Comment by bprashanth** [comment] 2015-04-14 16:36
It's unclear what exactly is saturating those cores, it could be etcd doing something unrelated. I'm writing  benchmarks that isolate list performance.

**Comment by wojtek-t** [comment] 2015-04-15 06:25
>
It's unclear what exactly is saturating those cores, it could be etcd doing something unrelated. I'm writing benchmarks that isolate list performance.

It's definitely not etcd - it is apiserver (this we already know). And basically the work it is doing is converting data read from etcd (mostly via watches and lists). Note e.g. that a Kubelet is watching pods assigned to it, but the label filtering in the apiserver (i.e. apiserver is getting changes to all pods, unmarshals/converts them and only then is applying labels filtering, resulting in most of the changes not effective).

**Comment by bgrant0607** [comment] 2015-04-15 06:42
Yes, we need to optimize label/field selectors: #4817 / #5548

**Comment by fgrzadkowski** [comment] 2015-04-15 07:04
@erictune @bprashanth As @wojtek-t said we pretty sure that it's not etcd that is a bottleneck. Regarding throughput let's take an example:

* 100 node cluster with 30 pods per node gives 3000 pods
* There are ~ default services
* Every 10 seconds endpoints controller lists all pods (with label selector) for each service. This gives 3000 pods * 10 / 10 s = 3000 pods / s

So just to handle endpoints controller apiserver decodes/encodes (in a very suboptimal way) 3000 pods every seconds so 160 ns per pods. This sounds quite reasonable. 

On top of that we have:
* regular list operations in many other places (e.g. replications controller, scheduler)
* lists that comes for broken watch
* all write operations (e.g. node statuses)

Once you add all of that I think it's not that surprising that 4 core master can be saturated.

**Comment by erictune** [comment] 2015-04-23 14:20
@fgrzadkowski where does 160ns come from?
3000 pods per second is 333us per pod.  That doesn't sound reasonable at all.

**Comment by timothysc** [comment] 2015-04-23 15:00
@fgrzadkowski do you still see this, post the Informer changes?

**Comment by fgrzadkowski** [comment] 2015-04-27 09:29
Several improvements have been made including #7107 and #7288 (still in review). I still observe latency above 1s, but CPU usage is much lower (probably it's worth to investigate what is our next bottleneck). Let me look into this more carefully and update the current state.

**Comment by timothysc** [comment] 2015-04-28 14:18
@fgrzadkowski how do we track the perf changes in apiserver to detect any regressions?

**Comment by fgrzadkowski** [comment] 2015-04-28 14:44
We are working on this :) Currently we only look at e2e performance test latency. I'm working on a PR to verify operation latency in apiserver. In general our goal is to increase performance to the level where we meet 1.0 goals and add e2e test that verify this.

**Comment by bgrant0607** [comment] 2015-06-30 03:32
Is this still an issue?

**Comment by wojtek-t** [comment] 2015-06-30 05:57
@bgrant0607 - listing pods is still the most expensive api call. Currently, in our scalability tests, high percentiles of listing pods are the only operations with latency exceeding 1s.
So I think this is still an issue, but it's not of very high priority in my opinion (there will be changes post 1.0 that should improve it - e.g. #10475), so I'd prefer to leave this issue open (it's not under 1.0 milestone, so I hope it's not a big problem).

**Comment by timothysc** [comment] 2015-07-07 19:30
+1

**Comment by lavalamp** [comment] 2015-12-03 22:59
Reassigning since this is the logical next step of the caching that @wojtek-t has been doing.

**Comment by wojtek-t** [comment] 2015-12-04 08:05
This is basically duplicate of https://github.com/kubernetes/kubernetes/issues/15945 - so closing this one.

**Comment by wojtek-t** [comment] 2015-12-14 10:09
Listing pods is much much faster now, with serving them from memory - #15945.

**Closed by wojtek-t** 2015-12-14 10:09 UTC
Labels: area/performance, priority/P1, team/CSI
