### ISSUE TITLE
Kubectl rollout status never finishes for StatefulSets [on kubectl "v1.13.0"]

### ISSUE THREAD

**Issue by puneetsar** [kubernetes/kubernetes#72212] opened 2018-12-19 20:23 UTC
**What happened**:
kubectl rollout status does not work for stateful sets. gets stuck with this message:
> kubectl rollout status statefulset/web -n puneet-test
Waiting for partitioned roll out to finish: 0 out of 3 new pods have been updated...

**What you expected to happen**:
After all pods have come up fine, rollout status should have succeeded.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a statefulset, and watch for its status.
kubectl apply -f https://raw.githubusercontent.com/puneetsar/yard/master/statefulsets.yaml
kubectl rollout status statefulset/web

**Anything else we need to know?**:

**Environment**:
> kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

> kubectl rollout status statefulset/web -n puneet-test
Waiting for partitioned roll out to finish: 0 out of 3 new pods have been updated...

/kind bug

**Comment by danielqsj** [comment] 2019-01-14 09:14
@puneetsar  I cannot reproduce it in master branch. 
```
# kubectl rollout status statefulset/web
partitioned roll out complete: 2 new pods have been updated...
```

**Comment by diafour** [comment] 2019-03-01 06:17
Do some research on this issue while working on https://github.com/flant/kubedog/issues/42

The main problem in `Status` method https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rollout_status.go#L121. The code that detects paritition rollout doesn't handle correctly `partition: 0` case.

The bug is reproduced when manifest doesn't contain `updateStrategy`. In this case k8s adds default updateStrategy to sts.Spec:
```
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
```
*sts.Spec.UpdateStrategy.RollingUpdate.Partition is 0. The fix for this case is in PR https://github.com/kubernetes/kubernetes/pull/71987


When manifest contains `updateStrategy` like this:
```
  updateStrategy:
    type: RollingUpdate
```
Then sts.Spec.UpdateStrategy.RollingUpdate.Partition == nil and `rollout status` is working as expected.

**Closed** 2019-07-29 08:14 UTC
Labels: kind/bug, lifecycle/rotten, sig/apps, sig/cli
