### ISSUE TITLE
deleting a deployment doesn't delete the replicaset

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#35447] opened 2016-10-24 16:44 UTC
In kubeadm we [create a dummy deployment and destroy it right away (after it reports as ready)](https://github.com/kubernetes/kubernetes/blob/33ebe1f18b9cf5909931376f656e19e80ac9ac1c/cmd/kubeadm/app/master/apiclient.go#L239-L275). It turns out that deleting the deployment doesn't destroy the RS.

**Comment by kargakis** [comment] 2016-10-24 16:53
Closing as dupe of https://github.com/kubernetes/kubernetes/issues/33845

**Closed by kargakis** 2016-10-24 16:53 UTC
Labels: component/nodecontroller, team/ux
