### ISSUE TITLE
kubelet-wrapper crashes when upgrading from 1.12.3 to 1.13.x

### ISSUE THREAD

**Issue by joberget** [kubernetes/kubernetes#78970] opened 2019-06-13 08:35 UTC
**What happened**:

We first drained the master and ran kubectl delete node master, reinstalled it and upgraded to 1.13.3. Then the problem started, kubelet-wrapper crashes, logs in the bottom. I also tried to upgrade it to 1.13.7 and it fails as well. Downgrading to 1.12.3 works fine. Is this because of 1.13 talking to 1.12 apiserver? We upgrade kubelet and api at the same time on the node.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Remove a master and readd as upgraded to 1.13.3.

**Anything else we need to know?**:
It is a multicluster with 4 master nodes.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Local vmware installation

- OS (e.g: `cat /etc/os-release`):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.5.1
VERSION_ID=2079.5.1
BUILD_ID=2019-06-05-2258
PRETTY_NAME="Container Linux by CoreOS 2079.5.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux server 4.19.43-coreos #1 SMP Wed Jun 5 22:24:22 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz GenuineIntel GNU/Linux

- Install tools:
Bash scripts

- Network plugin and version (if this is a network-related bug):
kubenet

- Others:

```
Jun 12 17:45:29 server kubelet-wrapper[12293]: I0612 15:45:29.944951   12293 reconciler.go:154] Reconciler: start to sync state
Jun 12 17:45:30 server kubelet-wrapper[12293]: E0612 15:45:30.152248   12293 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
Jun 12 17:45:30 server kubelet-wrapper[12293]: /usr/local/go/src/runtime/asm_amd64.s:522
Jun 12 17:45:30 server kubelet-wrapper[12293]: /usr/local/go/src/runtime/panic.go:513
Jun 12 17:45:30 server kubelet-wrapper[12293]: /usr/local/go/src/runtime/panic.go:82
Jun 12 17:45:30 server kubelet-wrapper[12293]: /usr/local/go/src/runtime/signal_unix.go:390
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:546
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:449
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:192
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:115
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:741
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1689
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:824
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:174
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:183
Jun 12 17:45:30 server kubelet-wrapper[12293]: /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:221
Jun 12 17:45:30 server kubelet-wrapper[12293]: /usr/local/go/src/runtime/asm_amd64.s:1333
```

**Comment by liggitt** [comment] 2019-06-13 13:21
This sounds like a duplicate of https://github.com/kubernetes/kubernetes/issues/71749

Make sure your API server is at least 1.13.x. If it is not, a 1.13.x kubelet will not run against a < 1.13.x API server. The npe was changed to a nicer message in 1.14 in https://github.com/kubernetes/kubernetes/pull/74529

**Comment by liggitt** [comment] 2019-06-13 13:22
> Is this because of 1.13 talking to 1.12 apiserver?

Yes. See https://kubernetes.io/docs/setup/release/version-skew-policy/ (specifically the upgrade order section)

/close

**Closed by liggitt** 2019-06-13 13:22 UTC
Labels: kind/bug, needs-sig
