### ISSUE TITLE
gitVersion results in inconsistent string values

### ISSUE THREAD

**Issue by ImJasonH** [kubernetes/kubernetes#99376] opened 2021-02-23 20:49 UTC
Ref. https://github.com/google/ko/issues/315#issuecomment-783718564

[pkg/version/base.go](https://github.com/kubernetes/client-go/blob/12449b5492ee1108d29d9ee17b428c84a6a3f55b/pkg/version/base.go#L58) includes:

	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
	// companion .gitattributes file containing 'export-subst' in this same
	// directory.  See also https://git-scm.com/docs/gitattributes
	gitVersion   string = "v0.0.0-master+$Format:%h$"

This `$Format:%h$` directive, activated by `git archive` and the [`.gitattributes`](https://github.com/kubernetes/client-go/blob/https://github.com/kubernetes/client-go/blob/12449b5492ee1108d29d9ee17b428c84a6a3f55b/pkg/version/.gitattributes/pkg/version/.gitattributes) containing the line `base.go export-subst`, results in file contents served by GitHub Archives that can change in unexpected ways. For example, the length of the commit SHA can expand over time as there are collisions.

This non-determinism can lead to surprises, such as https://github.com/google/ko/issues/315, where a client-go dependency resulted in unexpectedly different tar hashes, which was detected when a new version of the ko binary was being added to Homebrew.

tl;dr: though the client-go dependency itself didn't change for ko, later runs of `git archive` (via GitHub Archives) resulted in different contents for the `gitVersion` string to avoid a new collision for the previous prefix length, which cascaded into different content SHAs and shady-looking binary SHAs.

I'm not sure, but after reading docs I believe you could naively solve this by replacing `$Format:%h$` with `$Format:%H$` so the `gitVersion` string includes the full commit hash instead of the abbreviated one.

I have no idea if anything depends on `gitVersion` being a shorter string, but presumably things are fine with it having been a variable-length string so 🤷‍♂️ . Given enough time/collisions, I suppose theoretically `%h` will slow grow to be equal to `%H`, but I don't think that will happen during any of our lifetimes 👴 

cc @Bo98

**Comment by liggitt** [comment] 2021-02-23 21:14
Thanks for the report. Moving to kubernetes/kubernetes where this source comes from.

There's not a lot we can do for past releases, but I'd be in favor of switching to %H going forward. Reproducibility of source archives is important.

**Closed** 2021-02-26 17:30 UTC
Labels: kind/bug, needs-triage, sig/release

**Comment by ImJasonH** [comment] 2021-02-26 17:31
Thanks for taking this on @liggitt !! 🎉

**Comment by jonyhy96** [comment] 2022-01-11 11:42
@liggitt @neolit123 since we don't actually use `git archive` to full-fill the commit info as version, should we just delete that `.gitattributes` file?  
containerd faced a issue about checksum mismatch https://github.com/containerd/containerd/issues/6387 due to this.

**Comment by afbjorklund** [comment] 2022-01-11 12:28
> containerd faced a issue about checksum mismatch [containerd/containerd#6387](https://github.com/containerd/containerd/issues/6387) due to this.

and before that it was https://github.com/cri-o/cri-o/issues/4820 and before that https://github.com/containers/podman/issues/9355, so everywhere

**Comment by nikhita** [comment] 2022-01-17 14:05
> should we just delete that .gitattributes file?

@jonyhy96 @afbjorklund I have created https://github.com/kubernetes/publishing-bot/pull/285 to stop including the `.gitattributes` files in k8s libraries. For anyone vendoring these libraries in the future, you should no longer be affected by this issue.
