### ISSUE TITLE
Deleting a namespace sometimes leaves orphaned deployment and pods which can't be deleted

### ISSUE THREAD

**Issue by wallrj** [kubernetes/kubernetes#36891] opened 2016-11-16 13:57 UTC
I've got my kubernetes cluster into a state where there are pods and a deployment that belong to a deleted namespace.

I deleted the namespace (by calling the REST API directly).

And I can't delete the orphaned resources.

```
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# kubectl get --show-all --all-namespaces pods
NAMESPACE                                                         NAME                                                               READY     STATUS    RESTARTS   AGE
kube-system                                                       dummy-2088944543-v5fg8                                             1/1       Running   1          1d
kube-system                                                       etcd-acceptance-test-richardw-l2ljj4wewubtc-0                      1/1       Running   1          1d
kube-system                                                       kube-apiserver-acceptance-test-richardw-l2ljj4wewubtc-0            1/1       Running   1          1d
kube-system                                                       kube-controller-manager-acceptance-test-richardw-l2ljj4wewubtc-0   1/1       Running   3          1d
kube-system                                                       kube-discovery-1150918428-f4k00                                    1/1       Running   1          1d
kube-system                                                       kube-dns-654381707-ywhvt                                           3/3       Running   0          1d
kube-system                                                       kube-proxy-5yycz                                                   1/1       Running   0          1d
kube-system                                                       kube-proxy-pbft1                                                   1/1       Running   0          1d
kube-system                                                       kube-scheduler-acceptance-test-richardw-l2ljj4wewubtc-0            1/1       Running   3          1d
kube-system                                                       weave-net-czyj0                                                    2/2       Running   0          1d
kube-system                                                       weave-net-obiaa                                                    2/2       Running   0          1d
t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385   nginx-deployment-4087004473-7hh33                                  1/1       Running   0          2h
t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385   nginx-deployment-4087004473-dfg1d                                  1/1       Running   0          2h
t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385   nginx-deployment-4087004473-fxmfr                                  1/1       Running   0          2h
```
```
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# kubectl get --show-all namespaces                                                                                       
NAME          STATUS    AGE
default       Active    2h
kube-system   Active    2h
```
```
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# kubectl delete --namespace t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385 pod nginx-deployment-4087004473-fxmfr
Error from server: namespaces "t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385" not found
```
```
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

```
uname -a
Linux acceptance-test-richardw-l2ljj4wewubtc-0 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Cloud: Google Cloud Platform 
Installed according to `kubeadm` documentation http://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by liggitt** [comment] 2016-11-16 17:53
cc @derekwaynecarr 

do you know what admission plugins you have enabled, and if you have the NamespaceLifecycle plugin enabled?

**Comment by rothgar** [comment] 2016-11-17 05:09
I've seen this too in my test cluster. I'll have to verify what's enabled on my api server.

**Comment by liggitt** [comment] 2016-11-17 14:50
can you grab the yaml of the stuck objects? do they have finalizers or ownerRefs set in their metadata?

**Comment by liggitt** [comment] 2016-11-17 14:50
@caesarxuchao any idea if garbage collection could make the namespace controller think it had cleaned everything up, but still leave objects existing?

**Comment by dims** [comment] 2016-11-17 15:16
@liggitt : if this is a non-release-blocker, please add that label :)

**Comment by liggitt** [comment] 2016-11-17 15:21
if it's recreatable, it's a release blocker

**Comment by rothgar** [comment] 2016-11-17 16:19
My apiserver (1.4.4) has the following plugins
`--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota`

I don't have a reproducible but know I have seen it before

**Comment by wallrj** [comment] 2016-11-17 17:10
Mine's been configured by `kubeadm`. Here's a snippet of the docker inspect` output:

```
# docker inspect k8s_kube-apiserver.67fed3c3_kube-apiserver-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_21cc3e1299bfcfd3c8fd311efa792984_b3c9db7f
...
            "Image": "gcr.io/google_containers/kube-apiserver-amd64:v1.4.4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "kube-apiserver",
                "--v=2",
                "--insecure-bind-address=127.0.0.1",
                "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota",
                "--service-cluster-ip-range=10.96.0.0/12",
                "--service-account-key-file=/etc/kubernetes/pki/apiserver-key.pem",
                "--client-ca-file=/etc/kubernetes/pki/ca.pem",
                "--tls-cert-file=/etc/kubernetes/pki/apiserver.pem",
                "--tls-private-key-file=/etc/kubernetes/pki/apiserver-key.pem",
                "--token-auth-file=/etc/kubernetes/pki/tokens.csv",
                "--secure-port=6443",
                "--allow-privileged",
                "--advertise-address=10.240.0.4",
                "--etcd-servers=http://127.0.0.1:2379"
            ],
```

**Comment by wallrj** [comment] 2016-11-17 17:43
I've attempted to export my pods, deployments and namespaces using the following command `kubectl get --show-all --all-namespaces --output yaml --export ...`
[kubernetes_resources.zip](https://github.com/kubernetes/kubernetes/files/598073/kubernetes_resources.zip)

**Comment by caesarxuchao** [comment] 2016-11-17 17:54
@wallrj in the title you said deployments were left behind, but the pasted output only showed pods. Could you confirm if the deployment objects were left behind?

**Comment by wallrj** [comment] 2016-11-17 17:55
:arrow_up: See zip file attached above.

**Comment by caesarxuchao** [comment] 2016-11-17 18:13
Thanks. The deployment that got left behind:
```
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2016-11-16T11:42:48Z
    generation: 2
    labels:
      app: nginx
    name: nginx-deployment
    namespace: t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385
    resourceVersion: "106662"
    selfLink: /apis/extensions/v1beta1/namespaces/t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385/deployments/nginx-deployment
    uid: cc6d50b8-abf1-11e6-b9f6-42010af00004
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
      spec:
        containers:
        - image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    observedGeneration: 2
    replicas: 3
    updatedReplicas: 3
kind: List
metadata: {}
```
Looks like it's not caused by the garbage collector. @liggitt are there other suspects?

**Comment by caesarxuchao** [comment] 2016-11-17 18:22
The left-behind pod doesn't have a deletion timestamp:
```
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385","name":"nginx-deployment-4087004473","uid":"cc6dd651-abf1-11e6-b9f6-42010af00004","apiVersion":"extensions","resourceVersion":"106622"}}
    creationTimestamp: 2016-11-16T11:42:48Z
    generateName: nginx-deployment-4087004473-
    labels:
      app: nginx
      pod-template-hash: "4087004473"
    name: nginx-deployment-4087004473-dfg1d
    namespace: t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385
    ownerReferences:
    - apiVersion: extensions/v1beta1
      controller: true
      kind: ReplicaSet
      name: nginx-deployment-4087004473
      uid: cc6dd651-abf1-11e6-b9f6-42010af00004
    resourceVersion: "106661"
    selfLink: /api/v1/namespaces/t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385/pods/nginx-deployment-4087004473-dfg1d
    uid: cc704cfe-abf1-11e6-b9f6-42010af00004
```

Could this be a race? Can user create an object when the namespace is in the terminating state?

**Comment by wallrj** [comment] 2016-11-17 18:32
> Could this be a race? Can user create an object when the namespace is in the terminating state?

Sounds plausible. My tests originally created a namespace on `setUp`, create a `Deployment`, then immediately delete the namespace in `tearDown` ...perhaps before the deployment pods had been created / launched.

**Comment by liggitt** [comment] 2016-11-17 19:05
just to double check, single etcd server, single apiserver?

**Comment by wallrj** [comment] 2016-11-17 19:21
I think so...how can I be check?

```
# docker ps
CONTAINER ID        IMAGE                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
11c6935eda92        gcr.io/google_containers/kube-controller-manager-amd64:v1.4.4   "kube-controller-mana"   31 hours ago        Up 31 hours                             k8s_kube-controller-manager.edfea2a0_kube-controller-manager-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_aa642bd88d7c4f8636a7f3d6df731565_9c49f5fb
60ff677342db        gcr.io/google_containers/kube-scheduler-amd64:v1.4.4            "kube-scheduler --v=2"   31 hours ago        Up 31 hours                             k8s_kube-scheduler.c164d8b1_kube-scheduler-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_87687297b5040798a1737ed4061b3dab_91c0ef4f
9bb059aeca61        nginx:1.7.9                                                     "nginx -g 'daemon off"   31 hours ago        Up 31 hours                             k8s_nginx.f5cb328e_nginx-deployment-4087004473-fxmfr_t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385_cc6fbcdb-abf1-11e6-b9f6-42010af00004_9b9d7a3c
3abda6bfaa3a        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 31 hours ago        Up 31 hours                             k8s_POD.d8dbe16c_nginx-deployment-4087004473-fxmfr_t-kubernetesplugin-kubernetesplugintests-test-create-pod-355385_cc6fbcdb-abf1-11e6-b9f6-42010af00004_c20d3bf1
0f89fd214e4a        gcr.io/google_containers/exechealthz-amd64:1.1                  "/exechealthz '-cmd=n"   2 days ago          Up 2 days                               k8s_healthz.13f3684f_kube-dns-654381707-ywhvt_kube-system_40be01fa-ab24-11e6-aab9-42010af00004_02c21998
c8b56bd5ccb6        gcr.io/google_containers/kube-dnsmasq-amd64:1.3                 "/usr/sbin/dnsmasq --"   2 days ago          Up 2 days                               k8s_dnsmasq.45cf67a6_kube-dns-654381707-ywhvt_kube-system_40be01fa-ab24-11e6-aab9-42010af00004_fa7b9b01
362cd29e0cba        gcr.io/google_containers/kubedns-amd64:1.7                      "/kube-dns --domain=c"   2 days ago          Up 2 days                               k8s_kube-dns.c35f8fb3_kube-dns-654381707-ywhvt_kube-system_40be01fa-ab24-11e6-aab9-42010af00004_66140880
02bd066f7068        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-dns-654381707-ywhvt_kube-system_40be01fa-ab24-11e6-aab9-42010af00004_551e2fb7
1ed78a9fee7c        weaveworks/weave-npc:latest                                     "/usr/bin/weave-npc"     2 days ago          Up 2 days                               k8s_weave-npc.a795942e_weave-net-obiaa_kube-system_41458481-ab24-11e6-aab9-42010af00004_097e3e7d
f54c67c389ad        weaveworks/weave-kube:latest                                    "/home/weave/launch.s"   2 days ago          Up 2 days                               k8s_weave.25a9abdf_weave-net-obiaa_kube-system_41458481-ab24-11e6-aab9-42010af00004_877f2b84
4a97839cc812        gcr.io/google_containers/kube-proxy-amd64:v1.4.4                "kube-proxy --v=2 --k"   2 days ago          Up 2 days                               k8s_kube-proxy.2e54b651_kube-proxy-5yycz_kube-system_40b9c82d-ab24-11e6-aab9-42010af00004_745c55bd
ab948e85588e        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-scheduler-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_87687297b5040798a1737ed4061b3dab_c9dd4912
382ed9c6acf0        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_weave-net-obiaa_kube-system_41458481-ab24-11e6-aab9-42010af00004_d74c291e
387c2f64b674        gcr.io/google_containers/kube-apiserver-amd64:v1.4.4            "kube-apiserver --v=2"   2 days ago          Up 2 days                               k8s_kube-apiserver.67fed3c3_kube-apiserver-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_21cc3e1299bfcfd3c8fd311efa792984_b3c9db7f
c306725b1864        gcr.io/google_containers/kube-discovery-amd64:1.0               "/usr/local/bin/kube-"   2 days ago          Up 2 days                               k8s_kube-discovery.61afcdf5_kube-discovery-1150918428-f4k00_kube-system_3bf46152-ab24-11e6-aab9-42010af00004_802bc1d6
e49bd2eb1682        gcr.io/google_containers/etcd-amd64:2.2.5                       "etcd --listen-client"   2 days ago          Up 2 days                               k8s_etcd.5a0e984b_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_60cab3d5
1a751075bd3b        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_dummy.80f41be0_dummy-2088944543-v5fg8_kube-system_3b5670e8-ab24-11e6-aab9-42010af00004_89b7b29a
2b939a931f5c        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-apiserver-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_21cc3e1299bfcfd3c8fd311efa792984_cf6e310a
cb12111fffaa        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-controller-manager-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_aa642bd88d7c4f8636a7f3d6df731565_9c573843
faea5f30a83e        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-discovery-1150918428-f4k00_kube-system_3bf46152-ab24-11e6-aab9-42010af00004_d638c5d1
6b54a0d40bc2        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_67e6b71b
bc79f52ed9fe        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_dummy-2088944543-v5fg8_kube-system_3b5670e8-ab24-11e6-aab9-42010af00004_6aba46fc
9ea3ab6a6803        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_kube-proxy-5yycz_kube-system_40b9c82d-ab24-11e6-aab9-42010af00004_15889443
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# docker ps | grep etcd
e49bd2eb1682        gcr.io/google_containers/etcd-amd64:2.2.5                       "etcd --listen-client"   2 days ago          Up 2 days                               k8s_etcd.5a0e984b_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_60cab3d5
6b54a0d40bc2        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_67e6b71b
root@acceptance-test-richardw-l2ljj4wewubtc-0:~# docker ps | grep etcd
e49bd2eb1682        gcr.io/google_containers/etcd-amd64:2.2.5                       "etcd --listen-client"   2 days ago          Up 2 days                               k8s_etcd.5a0e984b_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_60cab3d5
6b54a0d40bc2        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 2 days ago          Up 2 days                               k8s_POD.d8dbe16c_etcd-acceptance-test-richardw-l2ljj4wewubtc-0_kube-system_a81a848a0bf7f0d38bc5f9b6b3a7140a_67e6b71b

```

**Comment by liggitt** [comment] 2016-11-17 19:23
looks like an etcd cluster of 3, and a single apiserver

**Comment by rothgar** [comment] 2016-11-17 23:09
My environment is 3 etcd and 3 apiservers

**Comment by grodrigues3** [comment] 2016-11-17 23:52
@liggitt if it is indeed reproducible, please add the release-blocker label

**Comment by derekwaynecarr** [comment] 2016-11-22 18:44
If you are running an HA API server, it is possible for a resource to be admitted in admission control after the namespace is deleted due to a race in delivering the watch notification to all API servers to observe the namespace is terminating.  @liggitt and I discussed potentially having the namespace controller to check the kubernetes endpoint to see if it's HA and if so, add a delay to namespace deletion to allow for each admission controller in each API server to get notified.

**Comment by dims** [comment] 2016-11-23 22:23
@liggitt : @derekwaynecarr : do we still think this is a release-blocker? if so, what needs to be done to unblock the release?

**Comment by liggitt** [comment] 2016-11-24 06:55
@dims yes, possible fix in https://github.com/kubernetes/kubernetes/pull/37431

I'd really like an automated reproducing test case for this, but the current CI infrastructure doesn't currently set up HA apiserver and HA etcd servers

**Comment by dims** [comment] 2016-11-27 19:58
@liggitt : gotcha. thanks for the update. we can mark this as non-release-blocker (or 1.6) once the fix merges so we can work on the CI stuff later

**Comment by dims** [comment] 2016-11-30 17:27
referenced PR is merged.

**Comment by liggitt** [comment] 2016-11-30 17:33
cherry-pick to the 1.5 branch is still open https://github.com/kubernetes/kubernetes/pull/37629

**Comment by dims** [comment] 2016-12-09 16:08
@wallrj @liggitt Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by ethernetdan** [comment] 2017-03-13 22:41
@wallrj @liggitt can this be closed or moved to 1.7?

**Comment by smarterclayton** [comment] 2017-03-14 03:01
This is such a serious problem that I don't think we can.  We should at least do a quick triage before moving it.

We've seen this in production clusters as well.

**Comment by liggitt** [comment] 2017-03-14 03:09
> We've seen this in production clusters as well.

Not with the "fix" in https://github.com/kubernetes/kubernetes/pull/37431 in place

**Comment by smarterclayton** [comment] 2017-03-14 03:10
"Just wait longer?"

**Comment by liggitt** [comment] 2017-03-14 03:20
I think the analysis in https://github.com/kubernetes/kubernetes/pull/37431#issue-191444266 is still valid (with the possible exception of stale etcd reads being helped by quorum reads being on)

I'm not aware of reoccurrences since #37431 was merged, but it just narrows the circumstances under which a leak can occur, it does not eliminate them (that requires receiving acknowledgement from all admission chains in all active API servers that namespace deletion was observed before starting the cleanup... there didn't seem to be a reasonable way to accomplish that at the time)

**Comment by smarterclayton** [comment] 2017-03-14 21:06
I don't see a better, simpler, global consistency fix.  We can defer this to 1.7 in case we have a better idea.

**Comment by liggitt** [comment] 2017-03-14 21:09
I look forward to having this conversation again in four months

**Comment by smarterclayton** [comment] 2017-03-14 21:20
Maybe we'll have waited long enough.

**Comment by derekwaynecarr** [comment] 2017-03-15 15:45
i acknowledge that we will have this discussion again in 4 mos, and we will discuss if the presence of user api servers makes this better/worse ;-)

**Comment by smarterclayton** [comment] 2017-03-17 04:33
We'll be too busy fixing distributed quota bugs.  Oh, and acl races on
getting access to a namespace

On Mar 15, 2017, at 11:45 AM, Derek Carr <notifications@github.com> wrote:

i acknowledge that we will have this discussion again in 4 mos, and we will
discuss if the presence of user api servers makes this better/worse ;-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/36891#issuecomment-286783833>,
or mute the thread

**Comment by lavalamp** [comment] 2017-05-26 21:54
In or out for 1.7?

**Comment by liggitt** [comment] 2017-05-28 12:50
I don't really see any new options for 1.7

**Comment by deads2k** [comment] 2017-06-02 12:22
> I'm not aware of reoccurrences since #37431 was merged,

Oh wow.  That was *you*?!

**Comment by liggitt** [comment] 2017-06-02 12:31
> Oh wow. That was you?!

You were there too, you've just blocked it out.

**Comment by maroda** [comment] 2019-07-12 22:19
This is happening to me, but I don't recall removing the _istio-system_ namespace when it started, and that's apparently the namespace that got orphaned. The only reason I found it was because it started showing up in my log aggregation, e.g.:

```
{"timestamp":1562969399610,"log":{"level":"info","time":"2019-07-12T22:09:59.505595Z","instance":"accesslog.instance.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"none","destinationApp":"bacque","destinationIp":"192.168.30.204","destinationName":"bacque-v012-6f99d6f697-h52ls","destinationNamespace":"crq","destinationOwner":"kubernetes://apis/apps/v1/namespaces/crq/deployments/bacque-v012","destinationPrincipal":"","destinationServiceHost":"bacque.crq.svc.cluster.local","destinationWorkload":"bacque-v012","grpcMessage":"","grpcStatus":"","httpAuthority":"bacque:9999","latency":"64.368133ms","method":"GET","permissiveResponseCode":"none","permissiveResponsePolicyID":"none","protocol":"http","receivedBytes":613,"referer":"","reporter":"destination","requestId":"e96fdbc7-7b39-9a1e-8da5-3e79eaa1ef86","requestSize":0,"requestedServerName":"","responseCode":200,"responseFlags":"-","responseSize":65,"responseTimestamp":"2019-07-12T22:09:59.569854Z","sentBytes":209,"sourceApp":"craque","sourceIp":"192.168.197.18","sourceName":"craque-v012-6d6f84c774-9f9vt","sourceNamespace":"crq","sourceOwner":"kubernetes://apis/apps/v1/namespaces/crq/deployments/craque-v012","sourcePrincipal":"","sourceWorkload":"craque-v012","url":"/fetch","userAgent":"craquego","xForwardedFor":"0.0.0.0"},"stream":"stdout","docker":{"container_id":"0acbffc89a020e048c26caa10da869607ddfbf506e3cb9014b2d7b54f3b84a5d"},"kubernetes":{"container_name":"mixer","namespace_name":".orphaned","pod_name":"istio-telemetry-79c7f498fb-kbhr2","orphaned_namespace":"istio-system","namespace_id":"orphaned"}}
```

I'm fairly new to kube, so I'm not sure if this is something to expect or not. There's very very little documentation anywhere about "orphaned namespaces".

My functioning _istio-system_ containers are 3 days old, and this orphaned traffic started within the last 24 hours and hasn't stopped this logging, so it must still be there somewhere. I don't know how to get rid of it, it certainly hurts my log volume.

Maybe I'm hitting an edge condition, but how do I get rid of this? I can filter out the logging no problem, but I'm concerned it's eating up resources in my cluster.

**Closed** 2020-04-11 21:02 UTC
Labels: area/HA, area/api, area/apiserver, lifecycle/rotten, priority/important-soon, sig/api-machinery

**Comment by alirezaDavid** [comment] 2022-09-29 07:56
Hey,
We're experiencing the exact issue mentioned here:
Cluster version: 1.21
We deleted a namespace, and it seems the namespace itself has successfully deleted,
(we had to turn off the "finalizer" in order to delete the namespace)

```
> k get ns arangodb
Error from server (NotFound): namespaces "arangodb" not found
```

But the pods/pvcs inside this namespace are stuck at the terminating phase,

```
 k -n arangodb get po -o wide
NAME                                                READY   STATUS        RESTARTS   AGE     IP              NODE                                             NOMINATED NODE   READINESS GATES
acc-arangodb-cluster-agnt-8ekz9d9y-a0e89b           0/1     Terminating   0              <none>           <none>
acc-arangodb-cluster-agnt-bwqwdnii-a0e89b           0/1     Terminating   0             <none>           <none>
acc-arangodb-cluster-agnt-dignjh4o-a0e89b           0/1     Terminating   0             <none>           <none>
acc-arangodb-cluster-prmr-ago5vxvf-a0e89b           0/1     Terminating   0             <none>           <none>
acc-arangodb-cluster-prmr-jrtfk9g5-a0e89b           0/1     Terminating   0             <none>           <none>
pre-upgrade-arangodb-cluster-agnt-fmfzytzb-ab3b5b   0/1     Terminating   0             <none>           <none>
pre-upgrade-arangodb-cluster-agnt-io4fsin7-ab3b5b   0/1     Terminating   0              <none>           <none>
pre-upgrade-arangodb-cluster-agnt-oq7itwew-ab3b5b   0/1     Terminating   0             <none>           <none>
pre-upgrade-arangodb-cluster-prmr-qng5l3xg-ab3b5b   0/1     Terminating   0              <none>           <none>
pre-upgrade-arangodb-cluster-prmr-rgh6fqq3-ab3b5b   0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-agnt-3t84z7a1-d1e132          0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-agnt-khjtyqje-d1e132          0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-agnt-ktx0uw8a-d1e132          0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-prmr-600o5sou-fb74cc          0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-prmr-8ntkvxhv-fb74cc          0/1     Terminating   0             <none>           <none>
prod-arangodb-cluster-prmr-nojlvuwv-fb74cc          0/1     Terminating   0             <none>           <none>
```
