### ISSUE TITLE
Assert() invariants?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3515] opened 2015-01-15 07:05 UTC
Kubelet tests would stay green more often if I could easily assert some invariants at key places (e.g. pod.UID != "").  But this is really only for tests.  Ideas welcome on how to do this in a sane way, or why not to do it at all.

**Comment by davidopp** [comment] 2015-01-15 07:19
Are you talking about invariants that are always true, or just properties that you know should be true at a particular point in the program but not always? From your example, I'm assuming the former. In the cluster management system you know and love at Google, we have RI() functions (stands for representation invariant) defined for each type that assert a laundry list of properties that are always supposed to be true, and these get called periodically (from a timer) as well as explicitly in various spots. These are called in production, not just in tests. Should we try something like that in Kubernetes?

**Comment by thockin** [comment] 2015-01-15 07:26
I'm certainly open to ideas.  I mostly want to blow up when code is called
under test and these properties are not preserved.

**Comment by davidopp** [comment] 2015-01-15 07:28
We could do the RI() thing but only enable it during tests.

**Comment by pmorie** [comment] 2015-01-15 07:46
I'm personally in favor of enforcing test invariants in production and
handling them with fault barriers. An invariant violation ahouldn't
necessarily torpedo your process but it might definitely cause a
transaction to abort or an error to be returned

**Comment by thockin** [comment] 2015-01-15 08:00
The problem with doing it in prod is that it requires a lot of rigor around
transactionality.  Doing it just in test means I can just blow up.

The trigger for this was literally bad test code that did not fill in
"required" fields, that later blew up in very odd ways.  That's not to say
there are not gains to be had from other types of asserts, but those are
not "the go way".

**Comment by ironcladlou** [comment] 2015-01-15 14:47
I too am guilty of creating half-baked test structures. One thing I wondered just now: why don't I subject the API objects I create in tests to the same API validations which external requests are bound by? In general, the components I write (probably unsafely) assume (for the most part) that the API objects they receive are valid, and omit nil checks for fields like Name. Simply running my test fixtures through their related API validators would probably catch a great deal of invalid states.

**Comment by lavalamp** [comment] 2015-01-15 18:59
From the email thread between @thockin & me about this:

> I could see something modeled after glog.

>```go
kl.assert.Must(val < 5).Fatalf("Whoa val was >= 5, context: %v", context)
if kl.assert.Must(val < 5) {
  // Doesn't eval args this way
  kl.assert.Fatalf("Whoa val was >= 5, context: %v", context)
}
kl.assert.Must(val < 5).DPanicf("Whoa val was >= 5, stopping test, context: %v", context)
```

It's not clear how one could figure out in general if you're running under a test or not, though. :/

**Comment by pmorie** [comment] 2015-01-15 19:36
You could encapsulate the assertions behind an interface:

    type Asserter interface {
        Must(bool)
        Fatalf(string, ...interface{})
    }

... and supply a nop implementation in production and the 'real' impl
during tests.

**Comment by zmerlynn** [comment] 2015-01-15 19:41
There's also the "make it a global flag" option, for those of us that like
being able to make our production binaries explode on invariant violations
when we're chasing issues.

**Comment by thockin** [comment] 2015-01-15 22:08
Yeah, maybe simpler really is better, and a flag to enable explosions is
sufficient.  Any objections to a gentle sprinkling of this sort of thing
around the code?

**Comment by pmorie** [comment] 2015-01-15 22:32
@zmerlynn I'm down with a global flag.

**Comment by bgrant0607** [comment] 2015-01-23 08:25
I'm all for assertions during tests, but beware of sending our components into crash loops in production, especially due to bad inputs/responses from users or from other components, which could be caused by bad release or configuration pushes. In those scenarios, we eventually need to fail gracefully, such as by neutralizing objects triggering the problem: nodes, pods, services, whatever.

**Comment by zmerlynn** [comment] 2015-01-23 13:12
My point was simply that offering something like a --debug flag (to
reenable assertions) can sometimes be a benefit to debugging even in
production binaries, and that it offers a simple solution to the problem at
hand, namely that tests always operate in this mode.

It is very coarse debugging at best, but given where we are in the project,
it might actually be the needful thing, too. (I've operated on production
systems that had dynamic assertion twiddles, too, and I think even a more
mature code base would benefit.)

**Comment by thockin** [comment] 2015-01-23 17:00
I think I agree with Zach, after contemplation.  It would be nice to have
them automatically be enabled in test mode, but maybe we can live without
that.  Anyway, I'm not sure how much priority this warrants at the moment,
so I'll let it sit for a while.

**Comment by zmerlynn** [comment] 2015-01-23 17:19
> It would be nice to have them automatically be enabled in test mode, but
maybe we can live without that.

I think you can have single-binary tests enable debug mode safely - I
assumed that was what we would do here. I'm against having a system-wide
mode (i.e. "restart --debug every daemon"), but I don't think that was
necessarily under discussion.

**Comment by davidopp** [comment] 2016-03-17 23:01
why closed?

**Comment by fejta** [comment] 2016-03-17 23:15
Thanks for reopening! I closed a bunch of test-infra bugs because there are a large number of them and I want to draw attention to the ones that are still relevant/important.

Dropping the test-infra label and moving to kubelet based on the description.

**Comment by thockin** [comment] 2016-03-17 23:27
Yeah, I still think we should do this more and that we should have WAAAAAAY more metrics that we expose.  Visibility into apps is way too low.

**Comment by kargakis** [comment] 2017-06-02 23:28
@kubernetes/sig-testing-misc

**Closed** 2018-02-24 03:58 UTC
Labels: area/kubelet, area/test, lifecycle/rotten, priority/awaiting-more-evidence, sig/testing
