### ISSUE TITLE
Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster failed twice today

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#19035] opened 2015-12-22 23:34 UTC
Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:46 Dec 22 15:15:02.489: monitoring using heapster and influxdb test failed

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9994/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9996/

cc @kubernetes/goog-node

**Comment by gmarek** [comment] 2015-12-29 10:44
Dupe of #12765

**Closed by gmarek** 2015-12-29 10:44 UTC
Labels: kind/flake, priority/P0
