### ISSUE TITLE
ServicePort's API schema doesnt match actual response for TargetPort field

### ISSUE THREAD

**Issue by cjellick** [kubernetes/kubernetes#14190] opened 2015-09-18 17:09 UTC
The API schema for ServicePort says that the TargetPort field is a string, but the api actually returns an integer.

This breaks clients generated from the schema for statically type languages. 

Here is the relevant bit of api schema for ServicePort:

```
   "v1.ServicePort": {
    "id": "v1.ServicePort",
    "required": [
     "port",
     "nodePort"
    ],
    "properties": {
      ...
     "port": {
      "type": "integer",
      "format": "int32",
      "description": "the port number that is exposed"
     },
     "targetPort": {
      "type": "string",
      "description": "number or name of the port to access on the pods targeted by the service; defaults to the service port; number must be in the range 1 to 65535; name must be an IANA_SVC_NAME"
     },
    ...
    }
   },
```

And here is an actual example response:

```
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "kubernetes",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/services/kubernetes",
    "uid": "511c1181-5e21-11e5-a63c-12548fd47124",
    "resourceVersion": "6",
    "creationTimestamp": "2015-09-18T16:21:29Z",
    "labels": {
      "component": "apiserver",
      "provider": "kubernetes"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 443,
        "targetPort": 443,
        "nodePort": 0
      }
    ],
    "clusterIP": "10.0.0.1",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}
```

As you can see _targetPort_ is returned as an integer when the API schema declares that this it is a string.

(For random reference, we're trying to generate go structs for the kubernetes model in this project: https://github.com/rancher/kubernetes-model)

**Comment by thockin** [comment] 2015-09-18 20:09
targetPort is an int or string - we accept either.  There are other fields in the API that are similar, and the generated schema seems broken.

@nikhiljindal what can we do?

**Comment by liggitt** [comment] 2015-09-22 02:37
wonder if it also breaks swagger validation in `kubectl create`

**Comment by bgrant0607** [comment] 2015-10-08 03:38
This is basically a dupe of #2971

**Comment by nikhiljindal** [comment] 2016-05-16 19:44
One option is to change this to `type: object` which we are using for custom types. Its generic but at least its not incorrect.

Right now, I think its getting `"type": "string"` from go-restful: https://github.com/emicklei/go-restful/blob/cf20a7d6fefb646f3251bd488b285a192a9d8bd8/swagger/model_builder.go#L142
IntOrString implements json.Marshaler.

A way to fix it might be to add another case to our typeToJSON method: https://github.com/kubernetes/kubernetes/blob/3111985564f4bfc769111c5708a01d9d711edf70/pkg/apiserver/api_installer.go#L937

**Comment by mbohlool** [comment] 2017-04-10 21:34
OpenAPI/Swagger 2.0 document this (and others like this) as IntOrString type. While generators do not understand it yet, but as it is well documented now, I am going to close this issue. (The problem may still exists in swagger 1.2 spec, but that is deprecated and will be removed).

**Closed by mbohlool** 2017-04-10 21:34 UTC
Labels: area/swagger, priority/backlog, sig/api-machinery
