### ISSUE TITLE
node e2e flake no debugging info

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#31327] opened 2016-08-24 05:02 UTC
The node e2e failed, but there are no failing tests, and no relevant debug info that I could find:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/29836/node-pull-build-e2e-test/20915/

**Comment by Random-Liu** [comment] 2016-08-24 17:35
The test failed because exceeding timeout:
```
---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
I0823 17:55:14.715073    2799 e2e_node_suite_test.go:144] Tests Finished

Ran 97 of 125 Specs in 2698.018 seconds
```
The default timeout is 45min (2700s), the pr builder usually only takes 550s

**Comment by Random-Liu** [comment] 2016-08-24 17:45
The pr node e2e is running with #30090, and I saw the same symptom on the failed node:
```
2016-08-23 17:25:16.756214 W | etcdserver: 80% of the file descriptor limit is used [used = 1009, limit = 1024]
2016-08-23 17:25:21.756281 W | etcdserver: 80% of the file descriptor limit is used [used = 1014, limit = 1024]
2016-08-23 17:25:26.756264 W | etcdserver: 80% of the file descriptor limit is used [used = 1019, limit = 1024]
E0823 17:25:28.488913    3095 genericapiserver.go:743] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
2016-08-23 17:25:31.756292 W | etcdserver: 80% of the file descriptor limit is used [used = 1024, limit = 1024]
```
So, I think that is the cause of the test timeout.

**Comment by Random-Liu** [comment] 2016-08-24 17:48
Close this one, since this should have been fixed in https://github.com/kubernetes/kubernetes/pull/31352.

**Closed by Random-Liu** 2016-08-24 17:48 UTC
Labels: component/node-e2e, team/test-infra
