### ISSUE TITLE
pull-kubernetes-federation-e2e-gce flaking because `Your "OAuth 2.0 Service Account" credentials are invalid`

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#49320] opened 2017-07-20 18:53 UTC
Examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49107/pull-kubernetes-federation-e2e-gce/16140/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49266/pull-kubernetes-federation-e2e-gce/16109/

```
/go/src/k8s.io/kubernetes/_output/gcs-stage/v1.8.0-alpha.2.558+6d2ef8a8be76e7/kubernetes-test.tar.gz.sha1 /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.8.0-alpha.2.558+6d2ef8a8be76e7/kubernetes.tar.gz /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.8.0-alpha.2.558+6d2ef8a8be76e7/kubernetes.tar.gz.md5 /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.8.0-alpha.2.558+6d2ef8a8be76e7/kubernetes.tar.gz.sha1 gs://kubernetes-release-pull/ci/pull-kubernetes-federation-e2e-gce/v1.8.0-alpha.2.558+6d2ef8a8be76e7/
I0720 18:45:12.859] Your "OAuth 2.0 Service Account" credentials are invalid. Please run
I0720 18:45:12.860]   $ gcloud auth login
I0720 18:45:12.860] Duplicate type [0:0:4]
I0720 18:45:24.339] CommandException: 1 file/object could not be transferred.
I0720 18:45:24.453] FAILED
I0720 18:45:24.456] 
I0720 18:45:24.460] 
```

**Comment by cblecker** [comment] 2017-07-20 19:13
@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment] 2017-07-20 19:16
the actual failure is `Duplicate type [0:0:4]`

**Comment by yujuhong** [comment] 2017-07-20 19:19
> the actual failure is Duplicate type [0:0:4]

Ah...that's a very subtle error.

**Comment by janetkuo** [comment] 2017-07-20 19:19
Saw this in `pull-kubernetes-e2e-gce-etcd3` as well. 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48746/pull-kubernetes-e2e-gce-etcd3/41868/

**Comment by krzyzacy** [comment] 2017-07-20 19:24
I was suspecting that might be gsutil, haven't took a close look yet.

**Comment by janetkuo** [comment] 2017-07-20 19:46
Another one: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49238/pull-kubernetes-federation-e2e-gce/16157/

**Comment by krzyzacy** [comment] 2017-07-20 20:18
/assign @ixdy 

might wanna look into it

**Comment by krzyzacy** [comment] 2017-07-20 23:25
seems https://github.com/kubernetes/release/blob/master/push-build.sh#L183-L193 should retry, but instead sig ERR is tossed?

cc @kubernetes/release-maintainers

**Comment by dims** [comment] 2017-07-21 01:08
@k8s-oncall i am seeing this in pull-kubernetes-e2e-gce-etcd3 as well

example - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/49299/pull-kubernetes-e2e-gce-etcd3/41874/build-log.txt

**Comment by mattmoyer** [comment] 2017-07-25 21:00
I see it on `pull-kubernetes-kubemark-e2e-gce` as well.

Example: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/49520/pull-kubernetes-kubemark-e2e-gce/41783/build-log.txt

**Comment by ixdy** [comment] 2017-07-25 21:21
The [release notes for gsutil 4.27](https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md#release-427-release-date-2017-06-29) make a reference to authentication which makes me a little suspicious. Trying to figure out when we updated to 4.27 and whether that correlates with these failures.

**Comment by rmmh** [comment] 2017-07-25 21:50
The earliest failure I can find is this:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46893/pull-kubernetes-federation-e2e-gce/14835

**Comment by ixdy** [comment] 2017-07-25 21:53
Yeah, it looks like there were no failures before we updated to gsutil 4.27, so I'm guessing that is the cause.
I'm not sure whether it's possible to pin to a particular version of gsutil.

**Comment by yujuhong** [comment] 2017-07-25 22:55
> I'm not sure whether it's possible to pin to a particular version of gsutil.

You could download a specific `gsutil_<version>.tar.gz` tarball at the beginning of a test run...

**Comment by fejta** [comment] 2017-07-26 00:55
I'm pretty sure gsutil comes as a part of gcloud, so if we install an older gcloud version, we'll also get an older gsutil

**Comment by fejta** [comment] 2017-07-26 06:09
Consider moving discussion over to the gsutil issue: https://github.com/GoogleCloudPlatform/gsutil/issues/446

**Comment by rmmh** [comment] 2017-08-01 16:46
Fixed in kubernetes/test-infra#3746.

**Comment by ixdy** [comment] 2017-08-02 02:56
This just happened again, this time in pull-kubernetes-e2e-kops-aws:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48969/pull-kubernetes-e2e-kops-aws/38787/?log#log
```
I0802 02:45:42.372] Your "OAuth 2.0 Service Account" credentials are invalid. Please run
I0802 02:45:42.372]   $ gcloud auth login
I0802 02:45:42.373] Type position out of range
I0802 02:45:52.338] CommandException: 1 file/object could not be transferred.
I0802 02:45:52.422] FAILED
```

The kops job is pretty weird, running a rather ancient version of kubekins-e2e; it looks like `gcr.io/k8s-testimages/kubekins-e2e:v20170314-bb0669b0` as best I can tell, which I think has gsutil version 4.22.

**Comment by rmmh** [comment] 2017-08-07 21:37
kubernetes/test-infra#3928 should fix this for kops-aws jobs

**Closed by rmmh** 2017-08-07 21:37 UTC
Labels: kind/flake, priority/failing-test, sig/testing
