### ISSUE TITLE
write on closed buffer during scale test

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34219] opened 2016-10-06 09:31 UTC
Observed during kubernetes-e2e-gce-enormous-cluster/156 run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/156

```
E1006 02:23:55.091318    6288 reflector.go:311] k8s.io/kubernetes/test/e2e/framework/util.go:274: Failed to watch *api.Pod: Get https://104.196.125.184/api/v1/watch/namespaces/e2e-tests-density-3x91x/pods?labelSelector=name%3Ddensity60000-0-978f562a-8b9a-11e6-9a6c-0242ac110005&resourceVersion=2517657&timeoutSeconds=535: write on closed buffer
```

It happened during the RC deletion phase of the density test on 2k Node cluster.

This looks like the cache issue. @lavalamp @wojtek-t @xiang90 @kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment] 2016-10-06 09:46
I think it's more related to watch, than to cache, but I would need to dig deeper.

**Comment by lavalamp** [comment] 2016-10-06 22:39
Context?

**Comment by lavalamp** [comment] 2016-10-06 22:39
(i.e. what is "the cache issue"?)

**Comment by xiang90** [comment] 2016-10-06 22:47
Would like to look into this if we can have more context or can get a easy reproduce.

**Comment by wojtek-t** [comment] 2016-10-07 07:45
As I wrote - I don't think it's "cache issue". I think is watch related. I hope I will have time to look into it more next week.

**Comment by gmarek** [comment] 2016-10-07 09:01
I thought about the cache mostly because it's an error that appeared in the reflector, but if @wojtek-t thinks it's the watch, then I'd go by that.

**Comment by gmarek** [comment] 2016-10-07 09:03
@lavalamp - can you assign someone to take a look at this? Whatever it is it looks like a race somewhere in the API server.

**Comment by lavalamp** [comment] 2016-10-07 17:34
Are you sure there's actually a bug in apiserver as opposed to the test doing something wrong?

**Comment by wojtek-t** [comment] 2016-10-07 18:31
@lavalamp - test is just using a reflector and nothing else underneath. So I'm pretty sure it's somewhere in our infrastructure. I can try looking deeper into it next week.

**Comment by smarterclayton** [comment] 2017-06-01 18:45
Closing due to age, reopen if this is re-creatable.

**Closed by smarterclayton** 2017-06-01 18:45 UTC
Labels: sig/api-machinery
