### ISSUE TITLE
cqlsh command is not work

### ISSUE THREAD

**Issue by wbtxd2004** [kubernetes/kubernetes#44317] opened 2017-04-11 08:24 UTC
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**Yes**

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

cqlsh

python

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**BUG REPORT**

**Kubernetes version** (use `kubectl version`):

**1.6**

**What happened**:

When I follow your guide to deployment cassandra cluster, I got this error on step 3. 
```
$kubectl exec cassandra-0 -- cqlsh -e 'desc keyspaces'
No appropriate python interpreter found.
```

**Comment by jayunit100** [comment] 2017-04-13 01:54
I think you're just using a broken cassandra container:  By definition the container should contain the right (3x iirc for cassandra) container.  So I suggest we close this and try a different cassandra image.

**Comment by vaijira** [comment] 2017-04-13 07:37
I'm suffering this issue too, the problem is the container image in the kubernetes example gcr.io/google-samples/cassandra:v12 is not properly build to support cqlsh.

**Comment by jayunit100** [comment] 2017-04-17 03:13
I thinks this is related to cqlsh relying on python probably; which isn't necessary for the example test .   Can you just spin an external cqlsh container for that functionality inside of the same namespace ?  By definition a Cassandra microservice should host a Cassandra node without providing any other functionality I assume.

**Comment by vaijira** [comment] 2017-04-17 19:13
Then the documentation should be changed to say that.

**Comment by jayunit100** [comment] 2017-04-17 19:40
Agree since probably most real Cassandra clusters have csqlsh on at least one node, so should we.

**Comment by mamdouhweb** [comment] 2017-06-14 21:25
Any resolution here on this issue. We're facing the same problem here. if not, what would be a recommended image to replace the one in google-exmaples?

**Comment by surfeurX** [comment] 2017-06-19 22:04
Here is a workaround:
`kubectl run -i --tty --restart=Never --rm --image mikewright/cqlsh cqlsh cassandra-0.cassandra.default.svc.cluster.local -- --cqlversion=3.4.2`
But first you may need to open the thrift port "9160" in https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/cassandra-statefulset.yaml

**Comment by kpostrup** [comment] 2017-07-14 09:41
The `cqlsh` util is included with the previous version of the image:
* `gcr.io/google-samples/cassandra:v11`

**Closed** 2018-03-01 19:11 UTC
Labels: lifecycle/rotten, sig/docs
