### ISSUE TITLE
kubeadm 1.8.0 init fails with "/var/lib/kubelet is not empty"

### ISSUE THREAD

**Issue by wjrogers** [kubernetes/kubernetes#53356] opened 2017-10-03 01:35 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
On a fresh Ubuntu 16.04.3 system booted from the official cloud image, `kubeadm init` fails because `/var/lib/kubelet` exists.
```
root@kubemaster:~# kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.8.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] Some fatal errors occurred:
        /var/lib/kubelet is not empty
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
```

**What you expected to happen**:
kubeadm successfully initializes the cluster

**How to reproduce it (as minimally and precisely as possible)**:
1. Boot a new VM from the latest [Ubuntu Cloud image](https://cloud-images.ubuntu.com/xenial/current/)
1. `apt-get install -y apt-transport-https docker.io`
1. Follow the [kubeadm installation instructions](https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl)
1. `kubeadm init`

**Anything else we need to know?**:
Contents of `/var/lib/kubelet`:
```
/var/lib/kubelet
/var/lib/kubelet/pki
/var/lib/kubelet/pki/kubelet.crt
/var/lib/kubelet/pki/kubelet.key
```

**Environment**:
- Kubernetes version (use `kubectl version`):
    ```
    root@kubemaster:~# kubectl version
    Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    
    root@kubemaster:~# apt search kube
    Sorting... Done
    Full Text Search... Done
    kubeadm/kubernetes-xenial,now 1.8.0-01 amd64 [installed]
      Kubernetes Cluster Bootstrapping Tool
    
    kubectl/kubernetes-xenial,now 1.8.0-00 amd64 [installed,automatic]
      Kubernetes Command Line Tool
    
    kubelet/kubernetes-xenial,now 1.8.0-00 amd64 [installed,automatic]
      Kubernetes Node Agent
    
    kubernetes-cni/kubernetes-xenial,now 0.5.1-00 amd64 [installed,automatic]
      Kubernetes CNI
    ```
- Cloud provider or hardware configuration: Hyper-V generation 1 virtual machine
- OS (e.g. from /etc/os-release):
    ```
    NAME="Ubuntu"
    VERSION="16.04.3 LTS (Xenial Xerus)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 16.04.3 LTS"
    VERSION_ID="16.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
    VERSION_CODENAME=xenial
    UBUNTU_CODENAME=xenial
    ```
- Kernel (e.g. `uname -a`): `Linux kubemaster 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: none
- Others: none

**Comment by liggitt** [comment] 2017-10-03 06:07
This is related to the location where the kubelet persists its certificates: 
* the kubeadm 1.8.0-0 package accidentally used a location that is [erased on reboot](https://github.com/kubernetes/kubernetes/issues/53288)
* the kubeadm 1.8.0-1 package corrected that to use [an appropriate location for the certificates](https://github.com/kubernetes/release/pull/426), but starting the kubelet before running `kubeadm init` causes files to be generated into the folder `kubeadm` expects to be empty

Did you start the kubelet service yourself prior to running `kubeadm init`, or did it start automatically after running `apt-get install -y kubelet kubeadm kubectl`?

It looks like kubeadm will start the kubelet itself, as part of init, after running the pre-init checks.

**Comment by liggitt** [comment] 2017-10-03 06:07
cc @kubernetes/sig-cluster-lifecycle-bugs @luxas

**Comment by surajssd** [comment] 2017-10-03 06:56
@wjrogers I did `kubeadm reset && kubeadm init` it worked for me!

**Comment by liggitt** [comment] 2017-10-03 13:27
> @wjrogers I did kubeadm reset && kubeadm init it worked for me!

On a known clean environment, that's an ok workaround for the moment, but the reason `kubeadm init` checks for existing files/folders is to avoid stomping an existing installation, and running `kubeadm reset` would negate those checks.

**Comment by jpetazzo** [comment] 2017-10-03 13:34
(If you wonder why the deployment scripts that you wrote _yesterday_ stopped working this morning – this is why! :-))

For the time being, I'm going to check if `/etc/kubernetes/admin.conf` exists (since it's created by `kubeadm init`) and if it doesn't, then I'll wipe `/var/lib/kubelet/pki`; but I'd love to know if there are foreseeable pitfalls in this approach.

Thanks! <3

**Comment by liggitt** [comment] 2017-10-03 14:01
> (If you wonder why the deployment scripts that you wrote yesterday stopped working this morning – this is why! :-))

apologies for the churn. we traded a [data loss issue on reboot](https://github.com/kubernetes/kubernetes/issues/53288) for this false-positive fail safe issue. working with @kubernetes/sig-cluster-lifecycle-bugs to determine the best way to resolve this.

**Comment by jpetazzo** [comment] 2017-10-03 14:10
No worries, and thanks for the super-quick turnaround time. Much appreciated!
(I didn't mean to sound snarky or anything; sorry if that how it came out!)

**Comment by vglisin** [comment] 2017-10-03 14:44
This guys are posting new versions without properly testing it. Can you imagine brand new centos 7 installation and then getting: "kubeadm 1.8.0 init fails with "/var/lib/kubelet is not empty"
how disgusting that was and what I was thinking about responsibility and professionalism here?

**Comment by vglisin** [comment] 2017-10-03 14:49
It is even getting better: The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused
you should remove 1.8 and put it do "back to the drawing board" stadium.
It is useless even to test this 1.8

**Comment by liggitt** [comment] 2017-10-03 14:50
I apologize for the issue. Our top priority was to prevent data loss and issues upgrading existing installations that would disrupt already-running workloads. We are working now to resolve this issue with fresh installations.

**Comment by vglisin** [comment] 2017-10-03 14:50
Wish you luck.

**Comment by naseemkullah** [comment] 2017-10-03 14:58
ETA for a fix for this? should i hard code this deletion of contents of  /var/lib/kubelet prior to running kubeadm init in my automation scripts? or simply add the ignore pre flight checks arguement will do the trick?

**Comment by naseemkullah** [comment] 2017-10-03 15:05
ok just to confirm, moving forward, ideally ```kubeadm init``` should not be checking for contents in ```/var/lib/kubelet``` (i.e. having contents is totally fine), or should installing kubelet not populate contenst of ```/var/lib/kubelet``` ?

**Comment by liggitt** [comment] 2017-10-03 15:08
> ok just to confirm, moving forward, ideally kubeadm init should not be checking for contents in /var/lib/kubelet (i.e. having contents is totally fine)

Correct. The `kubeadm` instructions start the kubelet and let it run in a crash loop in the background, waiting for config. In that state, the kubelet is free to write to its directory containing state (`/var/lib/kubelet`), so `kubeadm` should not require that directory to be empty in order to run `kubeadm init`

**Comment by jpetazzo** [comment] 2017-10-03 15:45
(Reposting my earlier tip since it worked like a charm for my automated deployment scripts.)

For the time being, before running `kubeadmin init` or `kubeadmin join`, I'll:
- check if `/etc/kubernetes/kubelet.conf` or `/etc/kubernetes/admin.conf` exists
- if they don't exist, stop kubelet (`systemctl stop kubelet`), and wipe out `/var/lib/kubelet/pki` (`rm -rf /var/lib/kubelet/pki`)

This might or might not be appropriate for your use-cases, but for mine it works great (I'm automatically deploying hundreds of k8s clusters of training purposes). Stopping kubelet is necessary to avoid race conditions where it would recreate the `pki` directory before you run `kubeadm`.

**Comment by rahulmishra** [comment] 2017-10-03 23:44
@liggitt @jpetazzo 

If i wipe out the /var/lib/kubelet/pki directory and do not restart kubelet, the kubeadm init process hangs with 

`kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by that:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
	- There is no internet connection; so the kubelet can't pull the following control plane images:
		- gcr.io/google_containers/kube-apiserver-amd64:v1.8.0
		- gcr.io/google_containers/kube-controller-manager-amd64:v1.8.0
		- gcr.io/google_containers/kube-scheduler-amd64:v1.8.0

You can troubleshoot this for example with the following commands if you're on a systemd-powered system:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'`

When i check the status of kubelet, it's restarting and never starts because 

```
ct 03 13:40:21 vagrant kubelet[15358]: I1003 13:40:21.489907   15358 controller.go:114] kubelet config controller: starting controller
Oct 03 13:40:21 vagrant kubelet[15358]: I1003 13:40:21.490020   15358 controller.go:118] kubelet config controller: validating combination o
Oct 03 13:40:21 vagrant kubelet[15358]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no

```
So, i am guessing my only option is to skip preflight checks, let me try that out..

**Comment by vglisin** [comment] 2017-10-04 10:51
Wish you luck. This is not the only problem:
kubectl cluster-info
Kubernetes master is running at http://localhost:8080

[root@masternode ~]# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.8.0/Documentation/kube-flannel.yml
W1004 06:49:56.291768    2422 factory_object_mapping.go:423] Failed to download OpenAPI (Get http://localhost:8080/swagger-2.0.0.pb-v1: dial tcp [::1]:8080: getsockopt: connection refused), falling back to swagger
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Why did you put this 1.8 version when it is obviously not properly tested.
Or tested at all?

**Comment by vglisin** [comment] 2017-10-04 10:52
Not to forget:
systemctl status firewalld
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

**Comment by liggitt** [comment] 2017-10-04 13:05
> kubectl cluster-info
> Kubernetes master is running at http://localhost:8080

@vglisin kubeadm does not run kubernetes unsecured. following the setup instructions in the output of `kubeadm init` configures `kubectl` to speak to the initialized server:

> To start using your cluster, you need to run (as a regular user):
> 
>   mkdir -p $HOME/.kube
>   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
>   sudo chown $(id -u):$(id -g) $HOME/.kube/config

**Comment by vglisin** [comment] 2017-10-04 14:37
Ok. This worked. Thank you. Node also added by running kubeadm join....
Now the problem is dashboard. I have followed:
https://github.com/kubernetes/dashboard#kubernetes-dashboard
but still don't understand where to start kubectl proxy and max.I god when I try to access dashboard is (https://192.168.4.10:6443/):
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
I am total newbee and anything which is not clear into documentation I can't resolve. I am using this for testing purposes and stil after 10days can't get dashboard nice and clean and then explore full power of kubernetes. Right now it is unusable even for testing.

**Comment by hemaprasad** [comment] 2017-10-04 14:47
Hi All,

Need help here

current i'm installing Kubernetes version: v1.8.0 using the command "kubeadm reset && kubeadm init"
it went hanged state. 
systemctl status kubelet log showing that

Oct 04 20:15:02 cluster-1 kubelet[18203]: W1004 20:15:02.263263   18203 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 04 20:15:02 cluster-1 kubelet[18203]: E1004 20:15:02.263758   18203 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:Net...nitialized
Oct 04 20:15:02 cluster-1 kubelet[18203]: E1004 20:15:02.326988   18203 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.serv...t.service"
Oct 04 20:15:02 cluster-1 kubelet[18203]: E1004 20:15:02.327015   18203 summary.go:92] Failed to get system container stats for "/system.slice/docker.servi...r.service"
Oct 04 20:15:07 cluster-1 kubelet[18203]: W1004 20:15:07.265211   18203 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 04 20:15:07 cluster-1 kubelet[18203]: E1004 20:15:07.265869   18203 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:Net...nitialized
Oct 04 20:15:12 cluster-1 kubelet[18203]: W1004 20:15:12.267033   18203 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 04 20:15:12 cluster-1 kubelet[18203]: E1004 20:15:12.267222   18203 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:Net...nitialized
Oct 04 20:15:12 cluster-1 kubelet[18203]: E1004 20:15:12.332802   18203 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.serv...t.service"
Oct 04 20:15:12 cluster-1 kubelet[18203]: E1004 20:15:12.332830   18203 summary.go:92] Failed to get system container stats for "/system.slice/docker.servi...r.service"
Warning: kubelet.service changed on disk. Run 'systemctl daemon-reload' to reload units.

After that i'm tried to weave it failed with error

 kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1004 18:53:33.930337   16144 factory_object_mapping.go:423] Failed to download OpenAPI (Get http://localhost:8080/swagger-2.0.0.pb-v1: dial tcp [::1]:8080: getsockopt: connection refused), falling back to swagger
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Please anyone can help me on this

**Comment by liggitt** [comment] 2017-10-04 14:49
> After that i'm tried to weave it failed with error
> kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
> The connection to the server localhost:8080 was refused

@hemaprasad, be sure to follow the instructions to add the admin kubeconfig file so kubectl can communicate with the initialized API server:

> To start using your cluster, you need to run (as a regular user):
> mkdir -p $HOME/.kube
> sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> sudo chown $(id -u):$(id -g) $HOME/.kube/config

**Comment by liggitt** [comment] 2017-10-04 14:56
For anyone following this thread, if you encounter issues other than the `/var/lib/kubelet is not empty` message, please report them in a separate issue, to ensure they are triaged and routed appropriately and resolved as quickly as possible.

**Comment by hemaprasad** [comment] 2017-10-04 15:06
@liggiit,  thank you for your quick response
now i'm getting

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
Unable to connect to the server: Forbidden
W1004 20:34:18.925025   20485 factory_object_mapping.go:423] Failed to download OpenAPI (Get https://192.168.1.3:6443/swagger-2.0.0.pb-v1: Forbidden), falling back to swagger
Unable to connect to the server: Forbidden

**Comment by jpetazzo** [comment] 2017-10-04 15:18
@hemaprasad: you seem to be hitting a totally different problem than the one related to `/var/lib/kubelet/pki`; can you please open a different issue? Thank you so much!

**Comment by hemaprasad** [comment] 2017-10-04 15:56
@jpetazzo,even I also faced the same issue'var/lib/kubelet is not empty' after I used the command "kubeadm reset && kubeadm init" it want to hanged state.(if want u can see my above threads).to move to another step I'm trying to install the weave it was failed saying that 
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1004 18:53:33.930337 16144 factory_object_mapping.go:423] Failed to download OpenAPI (Get http://localhost:8080/swagger-2.0.0.pb-v1: dial tcp [::1]:8080: getsockopt: connection refused), falling back to swagger
The connection to the server localhost:8080 was refused - did you specify the right host or port? Can you please help me to solve the issue
Thank in advance

**Comment by liggitt** [comment] 2017-10-04 17:39
pick to 1.8 branch is https://github.com/kubernetes/kubernetes/pull/53448
reopening to track issue until resolved in 1.8.x

**Comment by jpetazzo** [comment] 2017-10-04 18:11
@hemaprasad if you get `The connection to the server localhost:8080 was refused` it means that your kube config file is missing. By default, `kubectl` tries to connect to `localhost:8080`. But when you deploy a cluster with `kubeadm`, the API will be listening on port 6443. So you should see an error relative to port 6443, nor port 8080. If you see an error related to port 8080, it means that you haven't copied the configuration file (`admin.conf`) generated by `kubeadm`. I hope that makes sense.

My piece of advice would be to destroy the machines that you are currently using and restart from scratch (assuming you are using VMs), making sure that you follow each step carefully. Very often it solved the problem for me, because I had forgotten a step, or deviated from the instructions. Especially if something fails, it is often easier to restart from scratch, until you understand fully the technology and each underlying command. Good luck!

**Comment by vglisin** [comment] 2017-10-05 07:14
Hello  hemaprasad,
The problem is that when people know it is hard for them to set their mind to explain things to people who are new in a same area. Explanations given by jpetazzo and liggitt are ok but they are stepping over some steps which they assume but we as newbee do't.
Now, to have kubernetes operational we all should:
-stop the kubelet service, remove /var/lib/kubelet/pki, then run kubeadm init (without starting kubelet service first)
Same goes for nodes:
-stop the kubelet service, remove /var/lib/kubelet/pki, then run kubeadm join (with a token saved from kubeadm init)
Now... how to make dashboard accessible from my workstation which is out of kubernetes cluster?
Suppose for this I should go to some other thread?

**Comment by jpetazzo** [comment] 2017-10-05 09:56
@vglisin your explanations are correct! As for your dashboard question, I have no idea, but I would recommend to open another github issue for that (since the title of this issue is "kubeadm 1.8.0 init fails with "/var/lib/kubelet is not empty""). Thank you!

**Comment by vglisin** [comment] 2017-10-05 12:19
Thank you for fast reply. Also I am trying these innocent commands from documentations:
scp root@<master ip>:/etc/kubernetes/admin.conf .
./kubectl --kubeconfig ./admin.conf get nodes
but I am getting:
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

My guess is that is also the same reason why dashboard over proxy is not working.
Some help?

**Comment by jpetazzo** [comment] 2017-10-05 12:32
@vglisin It looks like you are copying `admin.conf` from a remote host. If it is the case, you also need to edit `admin.conf` to point to that remote host (instead of `localhost`). The tutorials and documentations imply that people will run `kubectl` directly from the master.

**Comment by vglisin** [comment] 2017-10-05 13:17
Nice this is... so why into same documentation exist this:
**Controlling your cluster from machines other than the master**
In order to get a kubectl on some other computer (e.g. laptop) to talk to your cluster, you need to copy the administrator kubeconfig file from your master to your workstation like this... 

Never mind, it is obviously long way to go till this function even in test environment :(

**Comment by vglisin** [comment] 2017-10-05 14:25
Hello all.
Finally dashboard starts working from master node. Please, do NOT use 1GB-2GB on master node, it would behave erratically and services which you expect to start normally... won't. Use at least 4GB and then also be patient. http://localhost:8001/ui/ will respond with strange formed URL so please use copy-paste:
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

That's for today. Hope this will help somebody.

**Comment by dkirrane** [comment] 2017-10-12 18:19
@jpetazzo I've tried you're workaround
```
systemctl stop kubelet
rm -Rf /var/lib/kubelet/pki
kubeadm init
```
But I'm then on kubeadm init I'm hitting this:
```
[kubelet-check] It seems like the kubelet isn't running or healthy.
```

**Comment by liggitt** [comment] 2017-10-12 18:23
this is fixed in v1.8.1

**Closed by liggitt** 2017-10-12 18:23 UTC
Labels: area/kubeadm, kind/bug, milestone/needs-approval, priority/critical-urgent, sig/cluster-lifecycle

**Comment by dkirrane** [comment] 2017-10-13 09:31
After installing 1.8.1 kubelet won't start:
```
kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
```

**Comment by vglisin** [comment] 2017-10-17 10:10
Not only what you mentioned dkirrane, there is a problem with:
https://kubernetes.io/docs/admin/kubeadm/#manage-tokens
They never wrote ANY detail how to add a new Node in a Cluster when your initial Token (which is valid for ... unknown) expired! Not a word. Only if you want to test-and-try yourself. Lovely beta troubleshooting job this is.
Documentation should be much, much better. Especially for somebody not working on Kubernetes dev. team.

**Comment by vglisin** [comment] 2017-10-17 10:12
What is: "Bootstrap Tokens"?
What does it mean as a consequence allowing it or not?
When Token expire how to make a new one to add new Node into Cluster?
These are a normal questions from a newbee who is not a member of Kubernetes dev.team.
Any help?

**Comment by vglisin** [comment] 2017-10-17 10:22
If you try with this you will see that there is no way to use IP address mentioned:
(Text is from: https://kubernetes.io/docs/admin/kubeadm/#manage-tokens)
"To implement this automation, you must know the IP address that the master will have after it is started.....
    kubeadm can generate a token for you:
    kubeadm token generate
Start both the master node and the worker nodes concurrently with this token."

Where to use mentioned IP address?
How to make any useful Node cluster joining after Token has expired?

**Comment by vglisin** [comment] 2017-10-17 10:38
If you try with this you will see that there is no way to use IP address mentioned:
(Text is from: https://kubernetes.io/docs/admin/kubeadm/#manage-tokens)
"To implement this automation, you must know the IP address that the master will have after it is started.....
    kubeadm can generate a token for you:
    kubeadm token generate
Start both the master node and the worker nodes concurrently with this token."

Where to use mentioned IP address?
How to make any useful Node cluster joining after Token has expired?

**Comment by vglisin** [comment] 2017-10-17 13:55
Hello, solved a Token problem.
Documentation really needs to be updated considering newbee mind. Otherwise it is source of frustration. Currently nodes are ok and operational.
If this above helps you... ok.

**Comment by rajendragosavi** [comment] 2019-06-23 16:09
This issue is fixed in the latest version of kubernetes. Just reset the kubeadm and remove the /var/lib/etcd as kubeadm is expecting it to be empty.

Then start the kubeadm init.
It should work fine.
