### ISSUE TITLE
e2e flake: ServiceAccounts should mount an API token into pods [Conformance] [It]

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#21530] opened 2016-02-19 08:03 UTC
[https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/21369/kubernetes-pull-build-test-e2e-gce/29340/build-log.txt](https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/21369/kubernetes-pull-build-test-e2e-gce/29340/build-log.txt)
```
鈥� Failure [11.605 seconds]
ServiceAccounts
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service_accounts.go:124
  should mount an API token into pods [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service_accounts.go:123

  "content of file \"/var/run/secrets/kubernetes.io/serviceaccount/token\": eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJlMmUtdGVzdHMtc3ZjYWNjb3VudHMtY2pkZDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi1ldWE1ZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTQyMjI4ZjEtZDZkMi0xMWU1LWE0MmYtNDIwMTBhZjAwMDAyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmUyZS10ZXN0cy1zdmNhY2NvdW50cy1jamRkMjpkZWZhdWx0In0.T_dLwS5K_x3rrmuC3iP-LY_lmPPiTxTnjais6tQkR-wkSR5XGzTnJW1xBCwsBXS2uGZi97Dug_l6i29cWt8TvRITMgQjLF5IT5Fi68FyRB0JfrBkCcDKRhPP8tH69rSNMWkuntpVZs3cXARlWPPuEXmxUPxUfPuhM8H1baYLg7i0hJveHVqNY5tlWEgYe7ujPUdxNvwUwTWtG3Lna-MgMtq7m5A5iEe9yh5ixeFM8URA_kHoAEQlxdKMR83XVkCfbKJxAUGuTvuA8PQ5fi8Wr6vFz1sAX8_NRTk0hstIYtCh-Y5xa5aHot75bKLkBFcGSFqgtUGX2_4beGIIOxZ3Cg" in container output
  Expected
      <string>: content of file "/var/run/secrets/kubernetes.io/serviceaccount/token": eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJlMmUtdGVzdHMtc3ZjYWNjb3VudHMtY2pkZDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi1vMzZ5OCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTQyMjI4ZjEtZDZkMi0xMWU1LWE0MmYtNDIwMTBhZjAwMDAyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmUyZS10ZXN0cy1zdmNhY2NvdW50cy1jamRkMjpkZWZhdWx0In0.Wy5Iksh4SgXa32ERH5VRVbg-DsZ4SCEdfXGRdM6Nh_a5uhYRRyhCo5w6vRdi39dKeiVTFBwiHVJap2RQUQ6ivMo8_0O_lWlEsbVtFO7CC2cWKIEm-Pjx5958_3sv6kw8QW3ZM6-CWk7669idz-ApGzx-hkrlREvle0HoO2wErPAR4s_X5VIveOjDT5eW1shzazAKSWs1FjxHIw_oeVntyxcRW6i_PDMEDpXOJTC3vjIY2bTYJ9eHDEblXNgiwuIvb3lTQbTnV-1GDs0OPkhB52-jyHMOhK0PzkQp8jerGSF3fffiTu6h47riUWE5UfuCLHAU9RM0AKSZtDx5Z64xPA
      
  to contain substring
      <string>: content of file "/var/run/secrets/kubernetes.io/serviceaccount/token": eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJlMmUtdGVzdHMtc3ZjYWNjb3VudHMtY2pkZDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi1ldWE1ZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTQyMjI4ZjEtZDZkMi0xMWU1LWE0MmYtNDIwMTBhZjAwMDAyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmUyZS10ZXN0cy1zdmNhY2NvdW50cy1jamRkMjpkZWZhdWx0In0.T_dLwS5K_x3rrmuC3iP-LY_lmPPiTxTnjais6tQkR-wkSR5XGzTnJW1xBCwsBXS2uGZi97Dug_l6i29cWt8TvRITMgQjLF5IT5Fi68FyRB0JfrBkCcDKRhPP8tH69rSNMWkuntpVZs3cXARlWPPuEXmxUPxUfPuhM8H1baYLg7i0hJveHVqNY5tlWEgYe7ujPUdxNvwUwTWtG3Lna-MgMtq7m5A5iEe9yh5ixeFM8URA_kHoAEQlxdKMR83XVkCfbKJxAUGuTvuA8PQ5fi8Wr6vFz1sAX8_NRTk0hstIYtCh-Y5xa5aHot75bKLkBFcGSFqgtUGX2_4beGIIOxZ3Cg
```

**Comment by AdoHe** [comment] 2016-02-20 09:44
@janetkuo

**Comment by bgrant0607** [comment] 2016-02-21 07:54
Dupe of #20787

**Closed by bgrant0607** 2016-02-21 07:54 UTC
