### ISSUE TITLE
UnmountVolume failed for volume secret volume with "IsLikelyNotMountPoint(...): stat...no such file or directory"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#37657] opened 2016-11-29 22:34 UTC
In https://github.com/kubernetes/kubernetes/issues/37447 @yujuhong reported: 

> kubelet log is full of errors from the volume manager complaining about non-existent secrets:
> ```
> Nov 29 17:25:34 gke-test-cluster-1-default-pool-44d8ae2f-kpn9 kubelet[2228]: I1129 17:25:34.230648    2228 reconciler.go:188] UnmountVolume operation started for volume "kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp" (spec.Name: "default-token-r4hlp") from pod "fee1aef7-b1ab-11e6-848f-42010a840181" (UID: "fee1aef7-b1ab-11e6-848f-42010a840181").
> Nov 29 17:25:34 gke-test-cluster-1-default-pool-44d8ae2f-kpn9 kubelet[2228]: E1129 17:25:34.232112    2228 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp\" (\"fee1aef7-b1ab-11e6-848f-42010a840181\")" failed. No retries permitted until 2016-11-29 17:27:34.232087714 +0000 UTC (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp" (volume.spec.Name: "default-token-r4hlp") pod "fee1aef7-b1ab-11e6-848f-42010a840181" (UID: "fee1aef7-b1ab-11e6-848f-42010a840181") with: IsLikelyNotMountPoint("/var/lib/kubelet/pods/fee1aef7-b1ab-11e6-848f-42010a840181/volumes/kubernetes.io~secret/default-token-r4hlp"): stat /var/lib/kubelet/pods/fee1aef7-b1ab-11e6-848f-42010a840181/volumes/kubernetes.io~secret/default-token-r4hlp: no such file or directory
> ```
> /cc @kubernetes/sig-storage @saad-ali @jingxu97 to see what could've caused this.

This happened after kubelet restart.

We need to understand why this happens, if it is expected behavior or a bug.

CC @kubernetes/sig-storage

**Comment by dims** [comment] 2016-11-30 00:57
@saad-ali : needs an assignee!

**Comment by saad-ali** [comment] 2016-11-30 01:34
@jingxu97 Can you investigate when you have some bandwidth CC @matchstick

**Comment by dims** [comment] 2016-12-01 13:53
@matchstick p0 release-blocker with no movement at all PTAL

**Comment by jingxu97** [comment] 2016-12-01 18:39
In our current code path, volume unmount will fail if the directories are already deleted. Reconciler just keep trying to unmount periodically. The scenario might happen with the following sequence of events
1. volume reconciler tries to unmount the volume first, 
2. cleanupOrphanedPod process tries to remove the pod directory after checking all volumes are unmounted.
3. volume reconciler tries to check whether the volume directory still mounted or not before it deletes the directory, but failed with errors.

The code path in volume TearDown just fails if directory is not exist. To make it more robust, we can add an extra check for directory existence. 

Now after #37255 is merged, the step 2 should not happen as long as there are volume directories so that this error will not happen. But the fix should make unmount function more robust. Will work on a fix, but I think it should not be p0 and not a release blocker.

**Comment by resouer** [comment] 2016-12-02 04:46
@jingxu97 Encountered this when using Cinder plugin. But I can see reconciler tried twice to `TearDown` the volume, while the second trail will fail due to directory has been removed. I am not quite sure why the second  `TearDown` occurs, because the first one has report success.

**Comment by resouer** [comment] 2016-12-02 13:20
@jingxu97, here's some deep dive of my case:

1. reconciler decides to do UnmountVolume
2. unmount tasks are generated continually by every iterate, but all of them are considered invalid except the first one becomes running
3. the last task is generating
4. the valid unmount task succeed 
5. the last task begin to run, but because the running task with same name has succeed, it is treated as valid.
6. the last task reports dir does not exist 

Here's the log, you can see the sequence:
```
I1202 04:37:48.277859    6619 goroutinemap.go:87] harry task created: kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4
I1202 04:37:48.380267    6619 reconciler.go:117] harry 0 get actual volume: {MountedVolume:{PodName:eb45b8ed-b872-11e6-8160-080027e4bc93 VolumeName:kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4 InnerVolumeSpecName:nginx-persistent-storage OuterVolumeSpecName:nginx-persistent-storage PluginName:kubernetes.io/cinder PodUID:eb45b8ed-b872-11e6-8160-080027e4bc93 Mounter:0xc42163bad0 VolumeGidValue:}}
I1202 04:37:48.427277    6619 operation_executor.go:791] UnmountVolume.TearDown succeeded for volume "kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4" (volume.spec.Name: "nginx-persistent-storage") pod "eb45b8ed-b872-11e6-8160-080027e4bc93" (UID: "eb45b8ed-b872-11e6-8160-080027e4bc93").
I1202 04:37:48.427308    6619 goroutinemap.go:127] harry operationComplete : kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4
I1202 04:37:48.523883    6619 goroutinemap.go:87] harry task created: kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4
I1202 04:37:48.523915    6619 reconciler.go:140] UnmountVolume operation started for volume "kubernetes.io/cinder/f8d5222a-ccb1-44ed-9bf9-2449803889f4" (spec.Name: "nginx-persistent-storage") from pod "eb45b8ed-b872-11e6-8160-080027e4bc93" (UID: "eb45b8ed-b872-11e6-8160-080027e4bc93").
```

**Comment by resouer** [comment] 2016-12-04 09:28
So I can reproduce it on upstream/master `host_path` easily, since it is a race, what I did is just mocking a slow volume plugin : 
1. Adding `time.Sleep(10 * time.Second)` in `host_path.TearDown()`
2. Adding `time.Sleep(1 * time.Second)` in `operation_executor.generateUnmountVolumeFunc()`, this is not necessary, just try to make it easier to race. 

Of course this issue does not break anything, only made log noisy. So no urge on this.

```
I1204 09:15:26.373500   29053 reconciler.go:189] UnmountVolume operation started for volume "kubernetes.io/host-path/1f9f85b3-ba02-11e6-8c4b-42010a8c0003-test-volume" (spec.Name: "test-volume") from pod "1f9f85b3-ba02-11e6-8c4b-42010a8c0003" (UID: "1f9f85b3-ba02-11e6-8c4b-42010a8c0003")
...
E1204 09:15:36.373795   29053 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/host-path/1f9f85b3-ba02-11e6-8c4b-42010a8c0003-test-volume\" (\"1f9f85b3-ba02-11e6-8c4b-42010a8c0003\")" failed. No retries permitted until 2016-12-04 09:15:37.373768906 +0000 UTC (durationBeforeRetry 1s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/host-path/1f9f85b3-ba02-11e6-8c4b-42010a8c0003-test-volume" (volume.spec.Name: "test-volume") pod "1f9f85b3-ba02-11e6-8c4b-42010a8c0003" (UID: "1f9f85b3-ba02-11e6-8c4b-42010a8c0003") with: stat : no such file or directory
...
I1204 09:15:38.975640   29053 reconciler.go:189] UnmountVolume operation started for volume "kubernetes.io/host-path/1f9f85b3-ba02-11e6-8c4b-42010a8c0003-test-volume" (spec.Name: "test-volume") from pod "1f9f85b3-ba02-11e6-8c4b-42010a8c0003" (UID: "1f9f85b3-ba02-11e6-8c4b-42010a8c0003").
```

**Comment by resouer** [comment] 2016-12-04 09:47
We can reproduce it by mocking a **slow plugin** by using HostPath.

1. Sleep 10 secs in `hostPath.TearDown()`
2. Sleep 2 secs in `operation_executor.generateUnmountVolumeFunc()`// just make it easier to create race

Then we can see when the last unmount task try to`MarkVolumeAsUnmounted`, the key of this volume has already been removed by the `right` unmount task. which also means the last unmount task should have be considered as invalid.

Of course this issue does not break anything, so no urge on this.

```
I1204 09:40:45.915725   17213 operation_executor.go:993] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/a57e1dc2-ba05-11e6-a0ae-42010a8c0003-test-volume" (OuterVolumeSpecName: "test-volume") pod "a57e1dc2-ba05-11e6-a0ae-42010a8c0003" (UID: "a57e1dc2-ba05-11e6-a0ae-42010a8c0003"). InnerVolumeSpecName "test-volume". PluginName "kubernetes.io/host-path", VolumeGidValue ""
E1204 09:40:45.915827   17213 operation_executor.go:1006] UnmountVolume.MarkVolumeAsUnmounted failed for volume "kubernetes.io/host-path/a57e1dc2-ba05-11e6-a0ae-42010a8c0003-test-volume" (volume.spec.Name: "test-volume") pod "a57e1dc2-ba05-11e6-a0ae-42010a8c0003" (UID: "a57e1dc2-ba05-11e6-a0ae-42010a8c0003") with: no volume with the name "kubernetes.io/host-path/a57e1dc2-ba05-11e6-a0ae-42010a8c0003-test-volume" exists in the list of attached volumes
```

**Comment by jingxu97** [comment] 2016-12-07 00:14
@resouer thanks for the analysis. As suggested earlier, to make unmount more robust, unmount should not fail over and over if dir no long exists.

**Comment by jingxu97** [comment] 2016-12-07 22:29
@rkouj could you help on this PR?

**Comment by rkouj** [comment] 2016-12-07 23:45
Ack

**Comment by rkouj** [comment] 2016-12-08 01:44
The quick way is to check if the dir exists and based on that we fail.
I'm investigating if there is a better way to do this. (to somehow prevent the race from happening).

Will post if I find something.

**Comment by dims** [comment] 2016-12-09 14:47
@saad-ali @jingxu97 Is it appropriate to move this to the next milestone? (and remove the non-release-blocker tag as well)

**Comment by jingxu97** [comment] 2016-12-09 16:55
@dims, yes, it is not a release blocker

**Comment by saad-ali** [comment] 2016-12-09 18:49
Let's leave the non-release blocker label until the 1.5.0 release is cut

**Comment by rkouj** [comment] 2016-12-09 21:53
Here is the race:

t0: Reconciler gets the [list of unmounted volumes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L161) from actual_state_of_world

t1: A previous [unmount operation is succeeded](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go#L137).

t2: Reconciler issues the [unmount volume operation](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L169)

The reconciler is acting on stale information in this case which causes it to not find the volumes.

**Comment by rkouj** [comment] 2016-12-09 22:54
Discussed with @saad-ali 
Looks like it is by design and each unmount operations (or any operation for that matter) should be idempotent.

The fix would involve two things: Making the TearDown() not to fail if the dir is not found. If dir is not found, it should just log and succeed.

Now there is a potential for the unmount operation to be stuck in a loop and here's how:

1. The valid unmount operation removes the directories **but** fails to update the state.
2. The reconciler would see a mismatch b/w asw and dsw, this would cause it to issue another unmount operation
3. Since the dirs no longer exist, the operation would fail with dirs not found
4. The asw will not get updated because of this and the process repeats from 2.

The fix would involve fixing step 3 to just log as a warning and succeed.

**Closed** 2016-12-20 03:45 UTC
Labels: sig/node, sig/storage, team/cluster (deprecated - do not use)
