### ISSUE TITLE
E2E: [sig-storage] PersistentVolumes Default StorageClass pods that use multiple volumes should be reschedulable [Slow]

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#76008] opened 2019-04-02 07:03 UTC
The test started failing on 2019-03-27:

Sample failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1112912925875507202

@kubernetes/sig-storage-bugs

**Comment by msau42** [comment] 2019-04-02 17:11
duplicate of https://github.com/kubernetes/kubernetes/issues/75775

**Comment by wojtek-t** [comment] 2019-04-11 13:01
And fixed now.

**Closed by wojtek-t** 2019-04-11 13:01 UTC
Labels: kind/bug, sig/storage
