### ISSUE TITLE
Make pause image started in kubelet_perf configurable

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#22876] opened 2016-03-11 21:37 UTC
Right now, the image started in `kubelet_perf` (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go#L70) is hard-coded, and for example makes it impossible to run that `e2e` test on an ARM cluster, where `gcr.io/google_containers/pause-arm:2.0` should be used instead.

The best way of fixing this is by creating a flag for the e2e test (but I don't know if that's possible) or automatically chooses `pause` image based on `runtime.GOARCH`
WDYT?

@yujuhong @ixdy @gmarek @wojtek-t @bgrant0607 @dchen1107

**Comment by ixdy** [comment] 2016-03-11 21:48
How do we handle the core kube containers?

**Comment by ixdy** [comment] 2016-03-11 21:54
We could make it flag-configurable in the e2e tests, but I'd rather it be more automatic than that.

#19905 adds support for including the platform in the version string, so we could use that to detect the correct name to use.

That said, I'm curious if we have a plan for easily maintaining and specifying parallel versions of x86, arm, etc containers - e.g. would we expect the same configs to work regardless of whether the cluster was running on x86 or arm? (Discussion is probably out of scope of this issue.)

**Comment by luxas** [comment] 2016-03-12 09:18
It would be really nice to read the server platform from #19905 and automatically choose image based on that. +1 for that.

> I'm curious if we have a plan for easily maintaining and specifying parallel versions of x86, arm, etc

No I guess there isn't a plan yet, but #17981 is a bit related. I guess we'll convert the parts we think are most important for other arches, like the `docker` and `docker-multinode` deployments and some important addons. For auto-configuration, I have been thinking about if it's worthwhile to add some annotation, label or something on nodes automatically which arch they have, but haven't made up my mind yet, cause in prod all machines will obviously amd64

**Comment by pwittrock** [comment] 2016-03-15 00:51
I believe nodes use the pause container when starting pods.  Does this work as intended generally?

**Comment by luxas** [comment] 2016-03-15 05:47
@pwittrock Yeah, If one specifies `--pod_infra_container_image` to kubelet. But there are discussions about auto-detecting the arch for pause and kubelet defaults to the arch-specific pause image.

But here the `kubelet_perf` spins up `gcr.io/google_containers/pause` without leaving it possible to customize via a flag. That's the issue. But now, when #19905 is merged, it's possible for the `e2e` binary to read server platform and use the right image.

**Closed** 2016-05-28 11:48 UTC
Labels: team/node
