### ISSUE TITLE
node e2e failure, image not found

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#25439] opened 2016-05-10 23:07 UTC
```
The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/tmp-node-e2e-7b8dd770-e2e-node-ubuntu-trusty-docker8-image'
```

Logs: https://00e9e64bac531cb5cad75310c608414ef335529b22eebfe480-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25374%2Fnode-pull-build-e2e-test%2F5146%2Fbuild-log.txt?qk=AD5uMEvI2Cm9eUqjLo34zreXYXJjVr09EnnPBIU2fWkgH1PegbVBe_Dos97WIggPEqpexQMaaIUn3X2BbDrNCPg78RTANb1VsFsvB3DecSJDHjGp7Z6S5qjiPkCXL7BRCeLWFbJTaPfbHyOj-_jt3lipVBjOwWBk58pOw56IhUR7v2nUr2UzriwxKqBlglsVanlOEnHxTaOnQdywB5kb0zXeRo-2Ax4adAnvFv6WSxDxMUN6sCvbtcSW2Yc9Fr1ZBqojbgXCVFMtvFZTvcHWAvVl3UrcgaC1Yu9gQrAfIDjeo8HNhLHfmri3Z6f_XQIJ4DW1ZJLLyqQk76QOAriE8C7q6rPB8dpTW22Gk0VJmtVT8WHMMVEnIJi5BPpKHLrpcK3VVHIr-8DIG0lq6gvU1f68hvx28PMKhbQM6S_KwkyS3SnmFQdJmA2xi81uaxuxoQ7rDQQ2W0l-PVAxQqE8trD6yXBeKZIvX6ZI_gfruLcR1dA09txuP3T1lwDF-hJVjFOONfhsvLXusc_HaWNl4qyEFxSAbG7X3cf6Ifi2frz7yUOdg6EX1MSnOnKNn0fe0Uhstaz3cDU6J8SPmqlxPHXY-yttZiNd9ZMM6kj668oziMAxPhxtd5JjKXWfWdgvKIszjUNrZJVn1amPfW4IQYLNqR8Gc75FRUvEm3-decTNE9M24cRLBn_48uIA1C-BOgDjGh2bP03-JfC22NGhehyZ1Sng7AdQq-QlfxVnqvSFq3T4LX9Lyn05WEjZYV60uK-WVqF5k9Zv6HzOaM6jxGbZN81R6S22qO4qJXtsp02xXpIunz2GJRw3zkuS2s_zH9ijHC-qPbmrgKxKmi6ll0p6MHyW3FKQpw

**Comment by metral** [comment] 2016-05-12 19:09
duplicate of https://github.com/kubernetes/kubernetes/issues/24479

**Comment by yujuhong** [comment] 2016-05-13 19:08
@metral, thanks. Closing as a dup.

**Closed by yujuhong** 2016-05-13 19:08 UTC
Labels: kind/flake, team/test-infra
