### ISSUE TITLE
etcdserver: not capable

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41893] opened 2017-02-22 14:52 UTC
apiserver received an error that is not an metav1.Status: etcdserver: not capable

It's a suspicious message that someone else asked me about before.  Found this time in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-kubemark-e2e-gce/18873/artifacts/k6k-e2e-agent-pr-14-0-master/kube-apiserver.log from the submit queue

@gmarek Can you check to make sure its nothing obvious in kubemark?

**Comment by wojtek-t** [comment] 2017-02-22 14:57
We are using exactly the same apiserver as in real tests. So it's not kubemark specific...

**Comment by gmarek** [comment] 2017-02-23 09:09
It's not kubemark specific - as @wojtek-t wrote we use exactly the same API server binaries we use everywhere. And indeed there are those logs even in our 'normal' 100 node cluster test:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1177/artifacts/e2e-scalability-master/kube-apiserver.log

**Comment by ncdc** [comment] 2017-02-23 15:50
@deads2k isn't this a dupe of #39108? Even though that's closed, I think the underlying issue is https://github.com/kubernetes/kubernetes/issues/37704, which should be fixed once https://github.com/kubernetes/kubernetes/pull/39821 is merged, right?

**Comment by ncdc** [comment] 2017-03-03 21:22
@deads2k bump, can we close this now?

**Comment by liggitt** [comment] 2017-03-04 17:05
I think this is fixed in https://github.com/kubernetes/kubernetes/pull/39821

**Closed by liggitt** 2017-03-04 17:05 UTC
Labels: kind/flake, priority/important-soon, sig/api-machinery
