### ISSUE TITLE
Kubelet tripping over failed pod + Docker daemon, still reporting ready

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/kubernetes#42796] opened 2017-03-09 11:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:30:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- **Kernel** (e.g. `uname -a`): `Linux ip-10-10-111-116 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux`
- **Install tools**: Kops
- **Others**:

**What happened**:
Noticed in the morning Helm could not connect to the tiller pod anymore, but could not see anything wrong with the container at first. Killing the pod to restart a new one worked to the extent that a new pod was launched, but the old one was not terminated. Taking a closer look at the Node I saw it was reported as Healthy, but had a last transition time of 10h ago . Lots of events as well:
```
Message                                       Source                              Sub-object Count  First seen            Last seen
operation timeout: context deadline exceeded  kubelet ip-10-10-74-61.ec2.internal -          203    2017-03-08T23:15 UTC  2017-03-09T09:21 UTC
```
Logging on to the instance, I got no response anymore from `docker ps`. `sudo service docker restart` brought the daemon and node back to life. 

So my first issue would be that kubelet did not pick up on the daemon being down. 
Besides this I checked the kubelet logs and it seems to have tripped over a particular pod: (snippet from around restart time)
```
Mar 08 23:10:40 ip-10-10-74-61 kubelet[1516]: I0308 23:10:40.231219    1516 prober.go:106] Liveness probe for "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0):headless-shell" failed (failure): Get http://100.96.4.67:9222/: net/http: r
Mar 08 23:10:40 ip-10-10-74-61 kubelet[1516]: I0308 23:10:40.231276    1516 kubelet.go:1849] SyncLoop (container unhealthy): "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0)"
Mar 08 23:10:40 ip-10-10-74-61 kubelet[1516]: I0308 23:10:40.534089    1516 docker_manager.go:2074] pod "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0)" container "headless-shell" is unhealthy, it will be killed and re-created.
Mar 08 23:10:40 ip-10-10-74-61 kubelet[1516]: I0308 23:10:40.534138    1516 docker_manager.go:1564] Killing container "eac9505c10a82454ea6711d78c63675915d9e2cc7ed8b1383d6a9b96c2c0c570 headless-shell prod/pagefetcher-prod-2540679047-z7770" with 30 second grace per
Mar 08 23:11:02 ip-10-10-74-61 kubelet[1516]: I0308 23:10:52.231277    1516 prober.go:106] Liveness probe for "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0):pagefetcher" failed (failure): Get http://100.96.4.67:3000/healthcheck: net/
Mar 08 23:12:42 ip-10-10-74-61 kubelet[1516]: I0308 23:11:05.124076    1516 server.go:740] GET /stats/summary/: (31.811319ms) 200 [[Go-http-client/1.1] 10.10.49.138:37732]
Mar 08 23:11:30 ip-10-10-74-61 systemd[1]: Started Kubernetes Kubelet Server.
Mar 08 23:12:44 ip-10-10-74-61 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Mar 08 23:12:44 ip-10-10-74-61 systemd[1]: Stopping Kubernetes Kubelet Server...
Mar 08 23:12:44 ip-10-10-74-61 systemd[1]: Starting Kubernetes Kubelet Server...
Mar 08 23:12:44 ip-10-10-74-61 systemd[1]: Started Kubernetes Kubelet Server.
Mar 08 23:12:44 ip-10-10-74-61 kubelet[5259]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Mar 08 23:12:44 ip-10-10-74-61 kubelet[5259]: Flag --babysit-daemons has been deprecated, Will be removed in a future version.
Mar 08 23:12:44 ip-10-10-74-61 kubelet[5259]: I0308 23:12:44.983841    5259 feature_gate.go:181] feature gates: map[]
Mar 08 23:12:44 ip-10-10-74-61 kubelet[5259]: I0308 23:12:44.984823    5259 aws.go:746] Building AWS cloudprovider
Mar 08 23:12:44 ip-10-10-74-61 kubelet[5259]: I0308 23:12:44.984888    5259 aws.go:700] Zone not specified in configuration file; querying AWS metadata service
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.184620    5259 aws.go:832] AWS cloud filtering on tags: map[KubernetesCluster:k8s.core.example.com]
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.184710    5259 server.go:369] Successfully initialized cloud provider: "aws" from the config file: ""
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.190972    5259 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.191003    5259 docker.go:376] Start docker client with request timeout=2m0s 
``` 
Kubelet goes on to restart after this, coming with the following logs after a while:

```
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.504596    5259 kubelet_network.go:226] Setting Pod CIDR:  -> 100.96.4.0/24
Mar 08 23:12:45 ip-10-10-74-61 kubelet[5259]: I0308 23:12:45.558400    5259 kubelet_node_status.go:358] Recording NodeNotReady event message for node ip-10-10-74-61.ec2.internal
Mar 08 23:12:46 ip-10-10-74-61 kubelet[5259]: I0308 23:12:46.308292    5259 helpers.go:101] Unable to get network stats from pid 7842: couldn't read network stats: failure opening /proc/7842/net/dev: open /proc/7842/net/dev: no such file or directory
Mar 08 23:12:46 ip-10-10-74-61 kubelet[5259]: I0308 23:12:46.307665    5259 manager.go:293] Recovery completed
...
...
Mar 08 23:12:50 ip-10-10-74-61 kubelet[5259]: W0308 23:12:50.760353    5259 prober.go:98] No ref for container "docker://eac9505c10a82454ea6711d78c63675915d9e2cc7ed8b1383d6a9b96c2c0c570" (pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0)
Mar 08 23:12:50 ip-10-10-74-61 kubelet[5259]: I0308 23:12:50.760372    5259 prober.go:106] Liveness probe for "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0):headless-shell" failed (failure): Get http://100.96.4.67:9222/: dial tcp 10
Mar 08 23:12:50 ip-10-10-74-61 kubelet[5259]: I0308 23:12:50.760410    5259 kubelet.go:1849] SyncLoop (container unhealthy): "pagefetcher-prod-2540679047-z7770_prod(58df921f-ff1f-11e6-9692-12b3f43365d0)"
```
And then moving to a "normal" state with some error messages in between:
```
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: I0308 23:15:19.437549    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: I0308 23:15:19.437572    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: W0308 23:15:19.636482    5259 docker_manager.go:1607] Container "eac9505c10a82454ea6711d78c63675915d9e2cc7ed8b1383d6a9b96c2c0c570 headless-shell prod/pagefetcher-prod-2540679047-z7770" termination failed after 2m0.0
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: W0308 23:15:19.636533    5259 docker_manager.go:1611] No ref for pod '"eac9505c10a82454ea6711d78c63675915d9e2cc7ed8b1383d6a9b96c2c0c570 headless-shell prod/pagefetcher-prod-2540679047-z7770"'
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: E0308 23:15:19.636568    5259 docker_manager.go:2155] Error killing container "headless-shell"(id={"docker" "eac9505c10a82454ea6711d78c63675915d9e2cc7ed8b1383d6a9b96c2c0c570"}) for pod "pagefetcher-prod-2540679047-z
Mar 08 23:15:19 ip-10-10-74-61 kubelet[5259]: E0308 23:15:19.636671    5259 pod_workers.go:184] Error syncing pod 58df921f-ff1f-11e6-9692-12b3f43365d0, skipping: failed to "KillContainer" for "headless-shell" with KillContainerError: "operation timeout: context
Mar 08 23:15:20 ip-10-10-74-61 kubelet[5259]: E0308 23:15:20.103307    5259 generic.go:197] GenericPLEG: Unable to retrieve pods: operation timeout: context deadline exceeded
Mar 08 23:15:20 ip-10-10-74-61 kubelet[5259]: I0308 23:15:20.556138    5259 helpers.go:101] Unable to get network stats from pid 7842: couldn't read network stats: failure opening /proc/7842/net/dev: open /proc/7842/net/dev: no such file or directory
Mar 08 23:15:21 ip-10-10-74-61 kubelet[5259]: E0308 23:15:21.334054    5259 kubelet_pods.go:710] Error listing containers: dockertools.operationTimeout{err:context.deadlineExceededError{}}
Mar 08 23:15:21 ip-10-10-74-61 kubelet[5259]: E0308 23:15:21.334087    5259 kubelet.go:1860] Failed cleaning pods: operation timeout: context deadline exceeded
Mar 08 23:15:29 ip-10-10-74-61 kubelet[5259]: I0308 23:15:29.469360    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:15:29 ip-10-10-74-61 kubelet[5259]: I0308 23:15:29.469385    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
```
```
Mar 08 23:16:30 ip-10-10-74-61 systemd[1]: Started Kubernetes Kubelet Server.
Mar 08 23:16:39 ip-10-10-74-61 kubelet[5259]: I0308 23:16:39.311226    5259 helpers.go:101] Unable to get network stats from pid 7842: couldn't read network stats: failure opening /proc/7842/net/dev: open /proc/7842/net/dev: no such file or directory
Mar 08 23:16:39 ip-10-10-74-61 kubelet[5259]: I0308 23:16:39.587627    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:16:39 ip-10-10-74-61 kubelet[5259]: I0308 23:16:39.587652    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:16:49 ip-10-10-74-61 kubelet[5259]: I0308 23:16:49.607282    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:16:49 ip-10-10-74-61 kubelet[5259]: I0308 23:16:49.607310    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:16:55 ip-10-10-74-61 kubelet[5259]: I0308 23:16:55.306375    5259 helpers.go:101] Unable to get network stats from pid 7842: couldn't read network stats: failure opening /proc/7842/net/dev: open /proc/7842/net/dev: no such file or directory
Mar 08 23:16:59 ip-10-10-74-61 kubelet[5259]: I0308 23:16:59.632820    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:16:59 ip-10-10-74-61 kubelet[5259]: I0308 23:16:59.632853    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:05 ip-10-10-74-61 kubelet[5259]: I0308 23:17:05.050940    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:05 ip-10-10-74-61 kubelet[5259]: I0308 23:17:05.050966    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:05 ip-10-10-74-61 kubelet[5259]: I0308 23:17:05.064216    5259 server.go:740] GET /stats/summary/: (18.954343ms) 200 [[Go-http-client/1.1] 10.10.49.138:41478]
Mar 08 23:17:09 ip-10-10-74-61 kubelet[5259]: I0308 23:17:09.647032    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:09 ip-10-10-74-61 kubelet[5259]: I0308 23:17:09.647066    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:12 ip-10-10-74-61 kubelet[5259]: I0308 23:17:12.153612    5259 helpers.go:101] Unable to get network stats from pid 7842: couldn't read network stats: failure opening /proc/7842/net/dev: open /proc/7842/net/dev: no such file or directory
Mar 08 23:17:19 ip-10-10-74-61 kubelet[5259]: I0308 23:17:19.661440    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:19 ip-10-10-74-61 kubelet[5259]: I0308 23:17:19.661463    5259 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 08 23:17:21 ip-10-10-74-61 kubelet[5259]: E0308 23:17:21.103795    5259 generic.go:197] GenericPLEG: Unable to retrieve pods: operation timeout: context deadline exceeded
Mar 08 23:17:21 ip-10-10-74-61 kubelet[5259]: E0308 23:17:21.334322    5259 kubelet_pods.go:710] Error listing containers: dockertools.operationTimeout{err:context.deadlineExceededError{}}
Mar 08 23:17:21 ip-10-10-74-61 kubelet[5259]: E0308 23:17:21.334351    5259 kubelet.go:1860] Failed cleaning pods: operation timeout: context deadline exceeded
```
These logs pretty much kept repeating themselves until I restarted the daemon

**What you expected to happen**:
Kubelet noticing docker daemon had hung and reporting the node as unhealthy, and not to struggle with the failed pod afterwards

**How to reproduce it** (as minimally and precisely as possible):
Have not been able to reproduce it

**Anything else we need to know**:

**Comment by dchen1107** [comment] 2017-03-09 18:56
Shouldn't docker's babysitter / health-monitoring on the node notice docker's hung / unresponsive issue and restart docker? We expect the docker babysitter / health-monitoring can spot such issue and restart the docker. Normally restarting docker daemon can fix most of those problems. If the docker daemon cannot run, Kubelet would eventually spot runtime is down, and reported NodeNotReady. Meanwhile, we introduce Node-problem-detector since 1.3 release, which can be configured to detect the kernel, hardware, etc. problems which requires an external controller or manual interferes.

**Comment by dchen1107** [comment] 2017-03-09 18:57
Or I just realized that you are running on AWS. cc/ @justinsb Are we still having daemon's health-monitoring installed for AWS nodes?

**Comment by bcorijn** [comment] 2017-03-10 08:49
Yes, running the KOPS AMI and standard setup. The fact that Dashboard reported that it had cycled the status around the time kubelet restarted makes me thing it at least figured something out, but didn't react much to it? 
I thought this PR was already in my build, but it seems this is not the case the yet: https://github.com/kubernetes/kubernetes/pull/37865

**Comment by bcorijn** [comment] 2017-03-13 09:56
Just had this again on one of my nodes: kubelet was trying to schedule a pod but couldnt. Error in the UI was:
```Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: operation timeout: context deadline exceeded```
ssh'ing into the host and restarting the daemon fixed it.

**Comment by bcorijn** [comment] 2017-04-04 09:28
Just had this again. Kubelet is posting ready but I see containers that are waiting to be created, and a lot `operation timeout: context deadline exceeded` events. KubeletReady status has last changed 19h ago, which matches with the first occurence of the operation timeout events.
In the meantime I'm running Kubernetes 1.5.4:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by justinsb** [comment] 2017-04-04 14:23
We have had reports that docker-babysitter is not running in recent kops installs, so that could be the cause: https://github.com/kubernetes/kops/issues/2279

**Comment by jsravn** [comment] 2017-10-09 10:33
I'm seeing this same problem, since moving to docker_shim / CRI. Lots of "context deadline exceeded" messages in kubelet, and pods getting stuck trying to create. The symptoms are completely random too - sometimes kubelet reports NotReady, other times it reports ready but pods can't be created. In all cases it seems the docker engine client lib in docker shim is hanging. `docker ps` responds fine though, so docker itself doesn't seem hung - or at least in a way I can easily detect. Restarting kubelet seems to fix it most of the time.

I made https://github.com/kubernetes/kubernetes/issues/53207 for my own issue.

**Closed** 2018-03-12 17:28 UTC
Labels: lifecycle/rotten, sig/aws, sig/node
