### ISSUE TITLE
ci-kubernetes-verify-master failed since 00:37am today

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#46867] opened 2017-06-02 16:42 UTC
https://k8s-testgrid.appspot.com/google-unit#verify-master

I0602 00:51:43.045] +++ /go/src/k8s.io/kubernetes/_tmp_federation/openapi-spec/swagger.json	2017-06-02 00:38:17.595732994 -0700
I0602 00:51:43.045] @@ -2,7 +2,7 @@
I0602 00:51:43.045]    "swagger": "2.0",
I0602 00:51:43.045]    "info": {
I0602 00:51:43.045]     "title": "Generic API Server",
I0602 00:51:43.045] -   "version": "v1.8.0"
I0602 00:51:43.045] +   "version": "v1.7.0"
I0602 00:51:43.046]    },
I0602 00:51:43.046]    "paths": {
I0602 00:51:43.046]     "/api/": {
I0602 00:51:43.046] /go/src/k8s.io/kubernetes/federation/apis/openapi-spec is out of date. Please run hack/update-federation-openapi-spec.sh
I0602 00:51:43.050] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-federation-openapi-spec.sh	137s

I0602 01:18:13.008] +++ /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json	2017-06-02 00:38:17.403732964 -0700
I0602 01:18:13.008] @@ -2,7 +2,7 @@
I0602 01:18:13.008]    "swagger": "2.0",
I0602 01:18:13.009]    "info": {
I0602 01:18:13.009]     "title": "Kubernetes",
I0602 01:18:13.009] -   "version": "v1.8.0"
I0602 01:18:13.009] +   "version": "v1.7.0"
I0602 01:18:13.009]    },
I0602 01:18:13.009]    "paths": {
I0602 01:18:13.009]     "/api/": {
I0602 01:18:13.009] /go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh
I0602 01:18:13.017] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-openapi-spec.sh	134s

This completely blocks any pr being merged. cc/ @kubernetes/kubernetes-release-managers

**Comment by cblecker** [comment] 2017-06-02 16:46
It's also failing on PRs: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-verify

**Comment by justinsb** [comment] 2017-06-02 16:54
Fix in https://github.com/kubernetes/kubernetes/pull/46869

**Comment by mikedanese** [comment] 2017-06-02 16:56
https://github.com/kubernetes/kubernetes/pull/46863 is merged

**Closed** 2017-06-02 16:56 UTC
Labels: priority/critical-urgent, priority/failing-test, sig/release

**Comment by dchen1107** [comment] 2017-06-02 16:58
Thanks! But do we know what is the root cause? Can this step automated in the future for each release, at least have a clear document for such process?

**Comment by david-mcmahon** [comment] 2017-06-05 22:22
Root cause is pending commit - https://github.com/kubernetes/release/pull/328
