### ISSUE TITLE
kubedns not using Authorization header in all requests to the API server

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/kubernetes#40724] opened 2017-01-31 06:43 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): CentOS Linux
- **Kernel** (e.g. `uname -a`): 3.10.0-327.36.3.el7.x86_64
- **Install tools**: from scratch

**What happened**:
One of the things that the `kubedns` container does when it starts up is list and watch the endpoints and services. To do this, the `kubedns` container needs to communicate with the api server. However, some over the calls to the api server are not including the service account token in the request as the `Authorization` header which is causing a timeout. See the logs below.

**What you expected to happen**:
I would expect each request to the api server to be constructed the same way (include the `Authorization` header) and succeed.

**How to reproduce it** (as minimally and precisely as possible):
Bring up the kubernetes dns pod on a fresh cluster with the following config:
```sh
I0131 06:31:27.178764       5 dns.go:42] version: v1.6.0-alpha.0.680+3872cb93abf948-dirty
I0131 06:31:27.179034       5 merged_client_builder.go:122] Using in-cluster configuration
I0131 06:31:27.179168       5 server.go:107] Using https://10.254.0.1:443 for kubernetes master, kubernetes API: <nil>
I0131 06:31:27.179560       5 server.go:63] ConfigMap not configured, using values from command line flags
I0131 06:31:27.179589       5 server.go:113] FLAG: --alsologtostderr="false"
I0131 06:31:27.179597       5 server.go:113] FLAG: --config-map=""
I0131 06:31:27.179602       5 server.go:113] FLAG: --config-map-namespace="kube-system"
I0131 06:31:27.179605       5 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0131 06:31:27.179609       5 server.go:113] FLAG: --dns-port="10053"
I0131 06:31:27.179613       5 server.go:113] FLAG: --domain="cluster.local."
I0131 06:31:27.179668       5 server.go:113] FLAG: --federations=""
I0131 06:31:27.179673       5 server.go:113] FLAG: --healthz-port="8081"
I0131 06:31:27.179677       5 server.go:113] FLAG: --kube-master-url=""
I0131 06:31:27.179681       5 server.go:113] FLAG: --kubecfg-file=""
I0131 06:31:27.179684       5 server.go:113] FLAG: --log-backtrace-at=":0"
I0131 06:31:27.179689       5 server.go:113] FLAG: --log-dir=""
I0131 06:31:27.179693       5 server.go:113] FLAG: --log-flush-frequency="5s"
I0131 06:31:27.179698       5 server.go:113] FLAG: --logtostderr="true"
I0131 06:31:27.179702       5 server.go:113] FLAG: --stderrthreshold="2"
I0131 06:31:27.179705       5 server.go:113] FLAG: --v="10"
I0131 06:31:27.179708       5 server.go:113] FLAG: --version="false"
I0131 06:31:27.179714       5 server.go:113] FLAG: --vmodule=""
```

**Anything else do we need to know**:

Here's the logs. NOTE: some of the requests are formatted correctly (`06:33:00.189354`) and succeed while the ones that attempt to go without the correct header timeout (`06:32:59.189034`):

On the request that is timing out, when I do a curl on the host and add the header (like the request that succeeds), it works.

```sh
E0131 06:32:59.189034       5 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: i/o timeout
I0131 06:32:59.189195       5 round_trippers.go:318] GET https://10.254.0.1:443/api/v1/services?resourceVersion=0  in 30000 milliseconds
I0131 06:32:59.189202       5 round_trippers.go:324] Response Headers:
E0131 06:32:59.189228       5 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: i/o timeout
I0131 06:32:59.276682       5 round_trippers.go:318] GET https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes  in 30000 milliseconds
I0131 06:32:59.276696       5 round_trippers.go:324] Response Headers:
I0131 06:32:59.276730       5 dns.go:176] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: i/o timeout. Sleeping 1s before retrying.
I0131 06:33:00.189184       5 reflector.go:234] Listing and watching *api.Endpoints from pkg/dns/dns.go:145
I0131 06:33:00.189354       5 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXg5Yng1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5ZWI1Njc3Yy1lNzZjLTExZTYtOTVmZC0wMDBkM2ExMDEwZmMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.vU-zOnicHyN1VOsFHMRCDMOqPnH2j8RflMb2OF4OlaYLNh0nyEu2TQ4MH_N-6toBxgfLPGb6DG7ojZfNfvxbrKd6f2PsAx-47apKyjigNR6bGtNSckMxX3nUD3uBKQwq8JPe-3lLubeCphjEiJlICbUYot2SgE1aZDVZ7ur-ObkXUQWp5l0GuVFI-akAHbLe9d2Llb9ptN2q6JvpyhaeSslDo8NZEWXflAbbIqhzRKsGoi7MiqS-HXuMicTXwDgDCoS6lgT_r0Uu7Q88QHybwtDd-y-p5QvVwdnjrn9LIfR9CQ7bpbvphdP5cnmW-N13vrgMGCMKMa05VqzR2sK3rg" -H "Accept: application/json, */*" -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0
I0131 06:33:00.189580       5 reflector.go:234] Listing and watching *api.Service from pkg/dns/dns.go:148
I0131 06:33:00.189661       5 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXg5Yng1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5ZWI1Njc3Yy1lNzZjLTExZTYtOTVmZC0wMDBkM2ExMDEwZmMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.vU-zOnicHyN1VOsFHMRCDMOqPnH2j8RflMb2OF4OlaYLNh0nyEu2TQ4MH_N-6toBxgfLPGb6DG7ojZfNfvxbrKd6f2PsAx-47apKyjigNR6bGtNSckMxX3nUD3uBKQwq8JPe-3lLubeCphjEiJlICbUYot2SgE1aZDVZ7ur-ObkXUQWp5l0GuVFI-akAHbLe9d2Llb9ptN2q6JvpyhaeSslDo8NZEWXflAbbIqhzRKsGoi7MiqS-HXuMicTXwDgDCoS6lgT_r0Uu7Q88QHybwtDd-y-p5QvVwdnjrn9LIfR9CQ7bpbvphdP5cnmW-N13vrgMGCMKMa05VqzR2sK3rg" https://10.254.0.1:443/api/v1/services?resourceVersion=0
I0131 06:33:00.277016       5 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXg5Yng1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5ZWI1Njc3Yy1lNzZjLTExZTYtOTVmZC0wMDBkM2ExMDEwZmMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.vU-zOnicHyN1VOsFHMRCDMOqPnH2j8RflMb2OF4OlaYLNh0nyEu2TQ4MH_N-6toBxgfLPGb6DG7ojZfNfvxbrKd6f2PsAx-47apKyjigNR6bGtNSckMxX3nUD3uBKQwq8JPe-3lLubeCphjEiJlICbUYot2SgE1aZDVZ7ur-ObkXUQWp5l0GuVFI-akAHbLe9d2Llb9ptN2q6JvpyhaeSslDo8NZEWXflAbbIqhzRKsGoi7MiqS-HXuMicTXwDgDCoS6lgT_r0Uu7Q88QHybwtDd-y-p5QvVwdnjrn9LIfR9CQ7bpbvphdP5cnmW-N13vrgMGCMKMa05VqzR2sK3rg" -H "Accept: application/json, */*" https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes
I0131 06:33:04.675500       5 dns.go:515] Query for "kubernetes.default.svc.cluster.local.", exact: false
I0131 06:33:04.675526       5 dns.go:743] Not a federation query: len(["kubernetes" "default" "svc" "cluster" "local"]) != 4+len(["local" "cluster"])
I0131 06:33:04.675542       5 dns.go:634] Found 0 records for [local cluster svc default kubernetes] in the cache
I0131 06:33:04.675549       5 dns.go:641] getRecordsForPath retval=[], path=[local cluster svc default kubernetes]
I0131 06:33:04.675554       5 dns.go:548] No record found for kubernetes.default.svc.cluster.local.
I0131 06:33:05.276147       5 logs.go:41] skydns: failure to forward request "read udp 192.168.225.130:41564->172.16.29.41:53: i/o timeout"
```

**Comment by redbaron** [comment] 2017-01-31 15:50
Looks more like your apiserver is not responding

**Comment by frankgreco** [comment] 2017-01-31 15:52
@redbaron if that were the case than I wouldn't be able to successfully curl the following:

```sh
I0131 06:33:00.189354       5 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXg5Yng1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5ZWI1Njc3Yy1lNzZjLTExZTYtOTVmZC0wMDBkM2ExMDEwZmMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.vU-zOnicHyN1VOsFHMRCDMOqPnH2j8RflMb2OF4OlaYLNh0nyEu2TQ4MH_N-6toBxgfLPGb6DG7ojZfNfvxbrKd6f2PsAx-47apKyjigNR6bGtNSckMxX3nUD3uBKQwq8JPe-3lLubeCphjEiJlICbUYot2SgE1aZDVZ7ur-ObkXUQWp5l0GuVFI-akAHbLe9d2Llb9ptN2q6JvpyhaeSslDo8NZEWXflAbbIqhzRKsGoi7MiqS-HXuMicTXwDgDCoS6lgT_r0Uu7Q88QHybwtDd-y-p5QvVwdnjrn9LIfR9CQ7bpbvphdP5cnmW-N13vrgMGCMKMa05VqzR2sK3rg" -H "Accept: application/json, */*" -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0
```

**Comment by liggitt** [comment] 2017-01-31 16:54
a missing authorization header would result in a 401 or 403, not an i/o timeout

**Comment by frankgreco** [comment] 2017-01-31 17:25
@liggitt 

on my host, when I curl `https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0` I get a timeout error but when I curl: 

```curl -k -v -XGET  -H "Authorization: Bearer <JWT from service token>" -H "Accept: application/json, */*" -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0```

it succeeds. This is the exact behavior that the kubedns pod is experiences (reference the above logs)

The only difference in the two http requests is the header.

**Comment by benjigoldberg** [comment] 2017-05-01 16:03
I seem to be experiencing the same issue on my end. As @frankgreco pointed out above, the `kube-dns` pod gets an i/o timeout, but if I `curl` from the host machine (with the configured iptables) the connection succeeds.

**Comment by benjigoldberg** [comment] 2017-05-03 16:14
Ok, the issue for me was that I'm running `kubenet` but forgot to add `--non-masquerade-cidr` to my kubelet configuration. Doesnt look like a bug on my end.

**Comment by frankruizhi** [comment] 2017-05-12 04:01
Maybe the problem is this,you can refer to this link:https://github.com/kubernetes/kubernetes/issues/32480

**Comment by cmluciano** [comment] 2017-06-22 00:59
@frankgreco Are you still seeing this issue?

**Comment by liggitt** [comment] 2017-09-24 02:33
closing due to lack of information

**Closed by liggitt** 2017-09-24 02:33 UTC
Labels: sig/auth, sig/azure, sig/network
