### ISSUE TITLE
kubectl logs is having issue when updated kubectl to 1.5.0

### ISSUE THREAD

**Issue by iam404** [kubernetes/kubernetes#39354] opened 2017-01-02 14:46 UTC
kubectl logs  client-3127929551-46crx
Error from server (InternalError): an error on the server ("unknown") has prevented the request from succeeding (get pods client-3127929551-46crx)

**Comment by xmik** [comment] 2017-01-02 20:31
Have you tried setting `--kubelet-preferred-address-types` option for apiserver? Example: https://github.com/kubernetes/kubernetes/issues/22770#issuecomment-266215007 . Without that option, on kubernetes 1.5.0-beta3 I was getting the same error as you.

**Comment by kargakis** [comment] 2017-01-14 15:25
Dupe of https://github.com/kubernetes/kubernetes/issues/38774

**Closed by kargakis** 2017-01-14 15:25 UTC
