### ISSUE TITLE
Scheduler incorrectly fails to schedule a pod

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#31977] opened 2016-09-02 14:18 UTC
An investigation of #31971:

Situation is following: before the test on the Node `gke-jenkins-e2e-default-pool-638c464f-sa7g` there were 3 running pods according to Kubelet:

```
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-638c464f-sa7g before test
Sep  2 04:23:57.650: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-638c464f-sa7g from kube-system started at <nil> (0 container statuses recorded)
Sep  2 04:23:57.650: INFO: kube-dns-v17.1-sev0c from kube-system started at 2016-09-02T03:49:41-07:00 (3 container statuses recorded)
Sep  2 04:23:57.650: INFO:  Container dnsmasq ready: true, restart count 0
Sep  2 04:23:57.650: INFO:  Container healthz ready: true, restart count 0
Sep  2 04:23:57.650: INFO:  Container kubedns ready: true, restart count 0
Sep  2 04:23:57.650: INFO: kube-proxy-gke-jenkins-e2e-default-pool-638c464f-sa7g from kube-system started at <nil> (0 container statuses recorded)
```

API server agreed on that list:

```
Sep  2 04:23:57.761: INFO: Pod fluentd-cloud-logging-gke-jenkins-e2e-default-pool-638c464f-sa7g requesting resource cpu=100m on Node gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:23:57.761: INFO: Pod kube-dns-v17.1-sev0c requesting resource cpu=110m on Node gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:23:57.761: INFO: Pod kube-proxy-gke-jenkins-e2e-default-pool-638c464f-sa7g requesting resource cpu=100m on Node gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:23:57.761: INFO: Node: gke-jenkins-e2e-default-pool-638c464f-sa7g has cpu capacity: 1690m
```

But despite that scheduler failed to schedule 3 Pods each requesting 500mCPUs:

```
Sep  2 04:33:58.092: INFO: At {2016-09-02 04:23:57 -0700 PDT} - event for overcommit-3: {default-scheduler } Scheduled: Successfully assigned overcommit-3 to gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:33:58.092: INFO: At {2016-09-02 04:23:57 -0700 PDT} - event for overcommit-6: {default-scheduler } Scheduled: Successfully assigned overcommit-6 to gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:33:58.092: INFO: At {2016-09-02 04:23:57 -0700 PDT} - event for overcommit-7: {default-scheduler } FailedScheduling: pod (overcommit-7) failed to fit in any node
fit failure on node (gke-jenkins-e2e-default-pool-638c464f-sa7g): Insufficient CPU
```

It was happening before, when for some reason one of the system Pods was starting during the test was running. This time it was not the case, as after the test kubelet was claiming that exactly the same Pods (+2 overcommit Pods) were running on the Node:

```
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-638c464f-sa7g
Sep  2 04:33:58.471: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-638c464f-sa7g started at <nil> (0+0 container statuses recorded)
Sep  2 04:33:58.471: INFO: kube-dns-v17.1-sev0c started at 2016-09-02T03:49:41-07:00 (0+3 container statuses recorded)
Sep  2 04:33:58.471: INFO:  Container dnsmasq ready: true, restart count 0
Sep  2 04:33:58.471: INFO:  Container healthz ready: true, restart count 0
Sep  2 04:33:58.471: INFO:  Container kubedns ready: true, restart count 0
Sep  2 04:33:58.471: INFO: kube-proxy-gke-jenkins-e2e-default-pool-638c464f-sa7g started at <nil> (0+0 container statuses recorded)
Sep  2 04:33:58.471: INFO: overcommit-3 started at 2016-09-02T04:23:57-07:00 (0+1 container statuses recorded)
Sep  2 04:33:58.471: INFO:  Container overcommit-3 ready: true, restart count 0
Sep  2 04:33:58.471: INFO: overcommit-6 started at 2016-09-02T04:23:57-07:00 (0+1 container statuses recorded)
Sep  2 04:33:58.471: INFO:  Container overcommit-6 ready: true, restart count 0
```

This might indicate some bug in scheduler cache. @hongchaodeng @davidopp @wojtek-t @pwittrock 

There's another strange line in the scheduler logs:

```
2016-09-02 11:23:57 UTC INFO    priorities.go:39        Combined requested resources 2010 from existing pods exceeds capacity 2000 on node gke-jenkins-e2e-default-pool-638c464f-sa7g
```

It's strange that scheduler sees an overcommited Node in the priorities function, especially in the cluster in which all pods do specify request.

**Comment by davidopp** [comment] 2016-09-03 21:48
Possibly stupid question: why should the third new pod schedule? The log lines you pasted under "API server agreed on that list" show that the already-running pods use 100+110+100 = 310m of CPU, and capacity is 1690m. You said the new pods request 500m each. Wouldn't that mean that after the first two schedule there is only 1690-310-500-500=380m available, thus not enough to schedule the third new pod?

Also, the "another strange line in the scheduler logs" says the node capacity is 2000 (though I'm not sure if it's CPU or memory).

**Comment by gmarek** [comment] 2016-09-03 22:59
1690 = 2000 - 310 (test prints out the remaining capacity), and 2000 is for milicores.

**Comment by wojtek-t** [comment] 2016-09-06 14:44
More context:
- in the same run @gmarek described above there was one more test that failed, and it failed with more-or-less the same reason, but not due to lack of resources, but due to exceeding number of allowed pods per node.

This really seems like a problem with cache in scheduler and it seems like some pods that no longer exist are not removed from it.

However, if pod was scheduled correctly, the its deletion from cache is triggerred by "delete event" coming via watch (which is a standard framework we are using everywhere and I don't believe it doesn't work).
[Potentially we could have a race, but I took a look into cache.go file and it seems that all functions are properly locked.]
So the other possibility is that the pod is assumed, it never gets scheduled correctly, but it remains in the cache. But this path is pretty simple:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L137
and it seems to be correctly handled in the code.

Also note that there are no logs: ```"Failed to bind pod ..."``` in scheduler logs from that run, which confirms that it's not related to that path.

So I still have no clue what is happening there...

**Comment by davidopp** [comment] 2016-09-10 19:03
@xiang90 @hongchaodeng

**Comment by hongchaodeng** [comment] 2016-09-11 16:01
How to reproduce it?

**Comment by gmarek** [comment] 2016-09-12 08:10
I don't know how. My guess is that you need to run some test from the serial suite before the this test, and then it'll happen more often.

**Comment by gmarek** [comment] 2016-09-13 13:12
It happened again in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-staging/6431/

As an error proof I have the list of pods that kubelet thinks are running on the machine:
```
Sep 12 05:22:42.881: INFO: maxp-86 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.881: INFO: 	Container maxp-86 ready: true, restart count 0
Sep 12 05:22:42.881: INFO: maxp-113 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.881: INFO: 	Container maxp-113 ready: true, restart count 0
Sep 12 05:22:42.881: INFO: maxp-155 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.881: INFO: 	Container maxp-155 ready: true, restart count 0
Sep 12 05:22:42.881: INFO: maxp-188 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.881: INFO: 	Container maxp-188 ready: true, restart count 0
Sep 12 05:22:42.881: INFO: maxp-18 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-18 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-38 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-38 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-173 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-173 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-26 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-26 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-95 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-95 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-251 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-251 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-308 started at 2016-09-12T05:12:41-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-308 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-128 started at 2016-09-12T05:12:32-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-128 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-230 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-230 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-20 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-20 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-23 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-23 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-140 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-140 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-152 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-152 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-161 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-161 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-56 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-56 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-146 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-146 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-254 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-254 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-182 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-182 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: kube-dns-v17.1-ff9x4 started at 2016-09-12T04:55:34-07:00 (0+3 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container dnsmasq ready: true, restart count 0
Sep 12 05:22:42.882: INFO: 	Container healthz ready: true, restart count 0
Sep 12 05:22:42.882: INFO: 	Container kubedns ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-293 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-293 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-98 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-98 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-119 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-119 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-122 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-122 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-236 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-236 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-260 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-260 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-36 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-36 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-80 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-80 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-110 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-110 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-131 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-131 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-248 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-248 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-51 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-51 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-59 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-59 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-92 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-92 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-68 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-68 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-74 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-74 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-299 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-299 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: heapster-v1.1.0-2096339923-ed774 started at 2016-09-12T03:22:42-07:00 (0+2 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container heapster ready: true, restart count 0
Sep 12 05:22:42.882: INFO: 	Container heapster-nanny ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-149 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-149 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-218 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-218 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-311 started at 2016-09-12T05:12:41-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-311 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-209 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-209 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-287 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-287 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-14 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-14 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-40 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-40 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-47 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-47 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-170 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-170 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-206 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-206 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-65 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-65 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-77 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-77 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-137 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-137 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-71 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-71 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-266 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-266 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-296 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-296 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-197 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-197 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-275 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-275 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-116 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-116 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-167 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-167 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-242 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-242 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-272 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-272 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: kubernetes-dashboard-v1.1.1-3kr8n started at 2016-09-12T03:22:27-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container kubernetes-dashboard ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-53 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-53 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-221 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-221 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-245 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-245 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-284 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-284 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-278 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-278 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-8 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-8 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-62 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-62 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-176 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-176 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-200 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-200 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-263 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-263 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-194 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-194 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-281 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-281 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-34 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-34 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-104 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-104 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-107 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-107 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-158 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-158 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-191 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-191 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-305 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-305 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-44 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-44 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-101 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-101 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-227 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-227 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-302 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-302 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-83 started at 2016-09-12T05:12:29-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-83 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-212 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-212 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-499125f4-6ncq started at <nil> (0+0 container statuses recorded)
Sep 12 05:22:42.882: INFO: maxp-28 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-28 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-134 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-134 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-203 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-203 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-224 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-224 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-185 started at 2016-09-12T05:12:35-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-185 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-257 started at 2016-09-12T05:12:38-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-257 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-269 started at 2016-09-12T05:12:39-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-269 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: kube-proxy-gke-jenkins-e2e-default-pool-499125f4-6ncq started at <nil> (0+0 container statuses recorded)
Sep 12 05:22:42.882: INFO: maxp-50 started at 2016-09-12T05:12:28-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-50 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-125 started at 2016-09-12T05:12:31-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-125 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-164 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-164 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-179 started at 2016-09-12T05:12:34-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-179 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-290 started at 2016-09-12T05:12:40-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-290 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-314 started at 2016-09-12T05:12:41-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-314 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-239 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-239 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-89 started at 2016-09-12T05:12:30-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-89 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-143 started at 2016-09-12T05:12:33-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-143 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-215 started at 2016-09-12T05:12:36-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-215 ready: true, restart count 0
Sep 12 05:22:42.882: INFO: maxp-233 started at 2016-09-12T05:12:37-07:00 (0+1 container statuses recorded)
Sep 12 05:22:42.882: INFO: 	Container maxp-233 ready: true, restart count 0
```

If you grep 'started at' on it you'll get 108 results: 2 pods from the max.

**Comment by timothysc** [comment] 2016-12-08 00:02
@jayunit100 can you evaluate this and report please.

**Comment by wojtek-t** [comment] 2016-12-08 08:25
Could this be the same problem as https://github.com/kubernetes/kubernetes/issues/37232 (which we fixed)?

**Comment by jayunit100** [comment] 2017-01-04 21:23
I think https://github.com/kubernetes/kubernetes/issues/37232 is sufficient to close this issue since:

- reproducing is non-obvious.
- the suspicion here is that the inconsistency in AssumePod is causing this issue, but that is fixed in the above issue. 
- the patch above forces a clean cache on update/remove

If it crops up again, I'd say we can reliably say its not due to a corrupted cache, and the investigation would be more informed.

**Closed** 2017-01-04 21:50 UTC
Labels: kind/bug, sig/scheduling, team/control-plane (deprecated - do not use)
