### ISSUE TITLE
CPU scheduler can't configure kube-proxy related POD cgroup settings in "static" mode

### ISSUE THREAD

**Issue by P1ng-W1n** [kubernetes/kubernetes#66614] opened 2018-07-25 15:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Kubelet spams syslog with the following messages:

> E0725 08:27:03.880692   55872 remote_runtime.go:302] UpdateContainerResources "8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d" from runtime service failed: rpc error: code = Unknown desc = failed to update container "8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d": Error response from daemon: Cannot update container 8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d: docker-runc did not terminate sucessfully: failed to write 0-1,4-15 to cpuset.cpus: write /sys/fs/cgroup/cpuset/kubepods/besteffort/podec2753a1-88e4-11e8-8dc3-9cb654aebf72/8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d/cpuset.cpus: device or resource busy
> 
> E0725 08:27:03.880718   55872 cpu_manager.go:267] [cpumanager] reconcileState: failed to update container (pod: kube-proxy-dmtlz, container: kube-proxy, container id: 8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d, cpuset: "0-1,4-15", error: rpc error: code = Unknown desc = failed to update container "8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d": Error response from daemon: Cannot update container 8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d: docker-runc did not terminate sucessfully: failed to write 0-1,4-15 to cpuset.cpus: write /sys/fs/cgroup/cpuset/kubepods/besteffort/podec2753a1-88e4-11e8-8dc3-9cb654aebf72/8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d/cpuset.cpus: device or resource busy

**What you expected to happen**:
No error messages

**How to reproduce it (as minimally and precisely as possible)**:
- Setup a base environment with kubeadm
- Make sure that kube-proxy is running fine
- Configure kubelet to use the --cpu-manager-policy=static flags with --kube-reserved
- Deploy a POD with guaranteed QOS
- Examine the syslog messages

**Anything else we need to know?**:
The cpu_manager can't set the cpuset.cpus' value for that POD because kube-proxy configures an additional child group there:

>     /sys/fs/cgroup/cpuset/kubepods/besteffort/podec2753a1-88e4-11e8-8dc3-9cb654aebf72/8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d/cpuset.cpus
>     /sys/fs/cgroup/cpuset/kubepods/besteffort/podec2753a1-88e4-11e8-8dc3-9cb654aebf72/8f2acab777a52bb17ff5884908d635fceae63bcc48ec6e17396cdc93269add4d/kube-proxy/cpuset.cpus

Apparently the cpu_manager does not expect an additional child group to be present there, and thus fails to configure that first before attempting to configure it's parent
So far I experienced this behavior with kube-proxy only.

This might be related to an old kube-proxy issue descibed in https://github.com/kubernetes/kubernetes/issues/17619

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
> 

- Cloud provider or hardware configuration: Self managed cluster, consisting of 8 x HP ProLiant SL210t Gen8 servers
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 

> 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Others: N/A

**Comment by ipuustin** [comment] 2018-08-02 08:18
I think the same problem is also reported to runc: https://github.com/opencontainers/runc/issues/1635. According to the comments in the associated PR, it appears that the correct fix would be to indeed apply the cpuset changes in order.

**Comment by ipuustin** [comment] 2018-08-02 14:15
Could be that the problem is indeed that `kube-proxy` may run in a "resource container", which creates a subdirectory in cgroup hierarchy. See https://github.com/kubernetes/kubernetes/blob/master/pkg/util/resourcecontainer/resource_container_linux.go#L32-L45

The `AllowAllDevices` option there is probably the related to issue https://github.com/kubernetes/kubernetes/issues/54967.

Grepping also indicates that no-one else uses resource containers, and that resource container support in `kube-proxy` is being deprecated, so the current problem might go away by itself soon. One way around this might be to simply check if the container being processed is `kube-proxy` and then skip it. A more complete fix would be to teach CRI to handle resources for complex cgroup trees, maybe with a new option or similar.

**Comment by P1ng-W1n** [comment] 2018-08-02 17:03
Filtering kube-proxy out is more like a workaround in my opinion, as there's no guarantee that other deployments wouldn't want to use the "resource containers".

A more bullet-proof solution (in my opinion) would be to check whether the deployment used cgroup hierarchy is supported by Kubernetes' Container Runtime Interface and throw an exception if there's any issue.

Based on my understanding (correct me if I'm wrong) having this extra layer in the hierarchy is supported (see: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/pod-resource-management.md#cgroup-hierarchy) so I would argue that the latter option would make more sense.

**Comment by ipuustin** [comment] 2018-08-03 12:15
You are right that filtering `kube-proxy` would be definitely a workaround, because the underlying issue (kube-proxy doesn't accept the assigned CPU set) causes the CPU exclusivity promise to be broken.

However, I don't think picture you linked refers to this case. Isn't the cgroup hierarchy here more like this:

    $ROOT
      |
      +- besteffort
      |   |
      |   +- Pod1
      |       |
      |       +- Container1
      |           |
      |           +- kube-root

**Comment by P1ng-W1n** [comment] 2018-08-03 12:46
@ipuustin  You're right.. 
The linked document does not cover this hierarchy level (sorry, it was my mistake). 
In that case a feasible long-term option could be to deprecate RunInResourceContainer() once kube-proxy removes that from it's KubeProxyConfiguration (part of this commit I presume - https://github.com/kubernetes/kubernetes/pull/17621)

**Comment by wanghaibo** [comment] 2018-10-08 07:10
one ugly workaround:
1.kubectl  edit cm kube-proxy -n kube-system
2.change  resourceContainer: "kube-proxy"  to  resourceContainer: "/"
3.kube-proxy will skip resourceContainer when error occur
server.go:468] Failed to start in resource-only container "/": cpuset: cgroup parent path outside cgroup root

**Comment by dannyk81** [comment] 2018-10-12 13:30
@P1ng-W1n I'm a bit confused by this, but we are hitting the same issue with kube-proxy on K8s 1.9.5

According to this: https://github.com/kubernetes/kubernetes/issues/17619 the correct way to avoid this (for now) is to add `--resource-container=""` flag to kube-proxy which is the only way to ensure it doesn't use a Resource Container (I didn't test this, but plan to do so today - will report)

We are deploying K8s with Kubespray and indeed the manifest provided there doesn't set this flag:

```
root     11807 11792  0 02:19 ?        00:01:17 /hyperkube proxy --v=2 --kubeconfig=/etc/kubernetes/kube-proxy-kubeconfig.yaml --bind-address=x.x.x.x --cluster-cidr=y.y.y.y/18 --proxy-mode=iptables --oom-score-adj=-998 --healthz-bind-address=127.0.0.1 --conntrack-max-per-core=0
```

I will file an issue with Kubespray to ensure they add this flag to the kube-proxy default manifest, but seems like this issue has fallen between some chairs 😉 

I guess this should be fixed in kube-proxy?

**Comment by dannyk81** [comment] 2018-10-12 13:55
After adding the `--resource-container=""` flag to kube-proxy, I'm no longer seeing the reported error, however I still see these:

```
Oct 12 13:53:43 blue-kubw-01 kubelet[14354]: E1012 13:53:43.211816   14354 remote_runtime.go:302] UpdateContainerResources "86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03" from runtime service failed: rpc error: code = Unknown desc = failed to update container "86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03": Error response from daemon: Cannot update container 86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03: docker-runc did not terminate sucessfully: failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod51b4fd62c2c6aaea8ee4759008adfad3/86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03/devices.allow: invalid argument
Oct 12 13:53:43 blue-kubw-01 kubelet[14354]: : unknown
Oct 12 13:53:43 blue-kubw-01 kubelet[14354]: E1012 13:53:43.211851   14354 cpu_manager.go:256] [cpumanager] reconcileState: failed to update container (pod: kube-proxy-blue-kubw-01, container: kube-proxy, container id: 86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03, cpuset: "0,3-15", error: rpc error: code = Unknown desc = failed to update container "86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03": Error response from daemon: Cannot update container 86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03: docker-runc did not terminate sucessfully: failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod51b4fd62c2c6aaea8ee4759008adfad3/86b1e9ac66caa620fe1e200f9a3ef153202d70079be5f70b0bd6cd8d9d0fcd03/devices.allow: invalid argument
```

Though I believe this is a separate issue https://github.com/kubernetes/kubernetes/issues/54967, @P1ng-W1n any ideas?

**Closed** 2019-07-22 14:55 UTC
Labels: kind/bug, sig/node
