### ISSUE TITLE
Node reports containerRuntimeVersion docker://Unknown on GCE

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#13080] opened 2015-08-24 06:53 UTC
I'm seeing this on both 1.0.3 on GKE and at head on GCE. When I print out all the info about a node, it gives a value of "docker://Unknown" for the `containerRuntimeVersion` field in the `nodeInfo` struct.

If I SSH to one of the nodes and run `docker version`, I can see that the version is 1.6.2.

For what it's worth, the `status.nodeInfo.machineID` field is showing up as empty on both clusters as well, although I'm not sure whether that's actually an issue.

**Comment by roberthbailey** [comment] 2015-08-24 15:12
@kubernetes/goog-node

**Comment by yujuhong** [comment] 2015-08-24 16:29
I believe @pwittrock was looking into this issue last week, and it had something to do with cadvisor caching the unknown version during initialization.

**Comment by pwittrock** [comment] 2015-08-24 17:06
Thanks for reporting.  This is likely caused by google/cadvisor#862 and should be fixed in cadvisor by google/cadvisor@b7bbefd9b1d4c1032c6afece425a99ba17e43cdb.  The cadvisor fix will get pulled into Kubernetes in a subsequent PR.  I will update this issue with the progress of updating Kubernetes.

**Comment by pwittrock** [comment] 2015-08-25 23:15
kubernetes was updated with the current cadvisor f1e8cb180d475860e8f3e3878125ccec309727fc

**Closed** 2015-08-25 23:18 UTC
Labels: priority/P2, team/node
