### ISSUE TITLE
Failing test 'Kubernetes e2e suite.[sig-node] SSH should SSH to all nodes and run commands' in gce-master-scale-correctness

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#103714] opened 2021-07-15 12:13 UTC
Test 'Kubernetes e2e suite.[sig-node] SSH should SSH to all nodes and run commands' consistently fails in [gce-master-scale-correctness](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness)

![image](https://user-images.githubusercontent.com/29059230/125785950-02e99e5b-988a-43d1-a042-f3b97143ec52.png)

Sample output from https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1415280350170451968
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/ssh.go:45
Jul 14 12:25:05.165: Ran echo "foo" | grep "bar" on , got error error dialing  from bastion: missing port in address, expected <nil>
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

/sig node

**Comment by jprzychodzen** [comment] 2021-07-15 12:19
It seems that #101866 could affect this. 

/assign @saschagrunert

**Comment by saschagrunert** [comment] 2021-07-15 12:28
This seems to be a duplicate of https://github.com/kubernetes/kubernetes/issues/103688

**Closed** 2021-07-15 12:34 UTC
Labels: kind/bug, needs-triage, sig/node
