### ISSUE TITLE
e2e flake: Reboot [Disruptive] each node by ordering unclean reboot and ensure they function upon restart (influxdb crash looping)

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#19189] opened 2015-12-30 08:26 UTC
This failed 5 times in the last 12 hours. Last failure:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-reboot/9752/

@kubernetes/goog-node

**Comment by goltermann** [comment] 2016-01-11 18:23
This is a P0 with no activity in 12d - needs to be fixed or reprioritized.

**Comment by dchen1107** [comment] 2016-01-12 01:16
There are a bunch of reboot flaky tests, and all of them are caused by influxdb container in our cluster addons pod: monitoring-influxdb-grafana:

```
14:52:38 Jan 11 14:52:38.142: INFO: monitoring-influxdb-grafana-v2-wpf4q          e2e-reboot-minion-31hq  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-01-11 14:51:51 -0800 PST ContainersNotReady containers with unready status: [influxdb]}]
```

Sometimes influxdb failed to start, and restart is capped by backoff. Looking into how to fix the test itself.

**Comment by yujuhong** [comment] 2016-01-12 03:19
Although I agree that backoff might have caused the situation to be worse, influxdb seems to have failed way too often though.
```
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Successfully pulled image "gcr.io/google_containers/heapster_grafana:v2.1.1"
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 6d760069ec63
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 6d760069ec63
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulling: pulling image "gcr.io/google_containers/heapster_influxdb:v0.4"
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Successfully pulled image "gcr.io/google_containers/heapster_influxdb:v0.4"
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id ca92c289f631
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id ca92c289f631
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulling: pulling image "gcr.io/google_containers/heapster_influxdb:v0.4"
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Successfully pulled image "gcr.io/google_containers/heapster_influxdb:v0.4"
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 8102e5c14d28
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 8102e5c14d28
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Container image "gcr.io/google_containers/heapster_grafana:v2.1.1" already present on machine
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 9ab898dd9a09
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 9ab898dd9a09
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Container image "gcr.io/google_containers/heapster_influxdb:v0.4" already present on machine
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 98df7a7cda63
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 98df7a7cda63
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} BackOff: Back-off restarting failed docker container
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} FailedSync: Error syncing pod, skipping: not all containers have started: 0 != 1
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 4c5bd9169c31
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 4c5bd9169c31
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id ce646bd4aada
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id ce646bd4aada
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 2f0f3215b136
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 2f0f3215b136
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 81cbb28ba93b
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 81cbb28ba93b
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id d7b9ffdf61e4
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id d7b9ffdf61e4
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Container image "gcr.io/google_containers/heapster_influxdb:v0.4" already present on machine
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Container image "gcr.io/google_containers/heapster_influxdb:v0.4" already present on machine
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id b8b5cd81934a
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id b8b5cd81934a
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Pulled: Container image "gcr.io/google_containers/heapster_grafana:v2.1.1" already present on machine
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id fde473de9be0
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id fde473de9be0
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 30ec763fd67f
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 30ec763fd67f
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} BackOff: Back-off restarting failed docker container
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} FailedSync: Error syncing pod, skipping: not all containers have started: 0 != 1
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id b8a963649e5d
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id b8a963649e5d
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id c154a0e37fa6
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id c154a0e37fa6
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id d3ba26f961a1
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id d3ba26f961a1
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Created: Created container with docker id 49e1ed2e17d1
14:52:38 Jan 11 14:52:38.125: INFO: event for monitoring-influxdb-grafana-v2-wpf4q: {kubelet e2e-reboot-minion-31hq} Started: Started container with docker id 49e1ed2e17d1
```

**Comment by piosz** [comment] 2016-01-13 10:39
Test `each node by dropping all inbound packets for a while and ensure they function afterwards` failed again.
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-reboot/10404/

I'll try to take a look into the problems with influxdb

@mwielgus

**Comment by alex-mohr** [comment] 2016-01-21 00:12
Recent failures for GKE:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10405/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10406/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10399/

And for GCE:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10432/

@dchen1107 If you're not available for this, can you please find someone on the node team to work on this tomorrow?  Merges have been blocked a significant fraction of the time due to these failures.

**Comment by alex-mohr** [comment] 2016-01-21 00:13
@piosz And if you're free earlier due to timezone, that would be wonderful too!

**Comment by yujuhong** [comment] 2016-01-21 00:38
The recent failures in kubernetes-e2e-gce builds exhibited different symptoms than @dchen1107's [comment](https://github.com/kubernetes/kubernetes/issues/19189#issuecomment-170749856).

One of my PRs landed last weekend and exacerbated the situation (due to the change of sync timing in kubelet), and it eventually got reverted. I looked through some builds with reboot test failures in kuberentes-e2e-gce and got two bugs: https://github.com/kubernetes/kubernetes/pull/19436#issuecomment-173030536 The fixes for the two bugs are in waiting to be merged. I expect the test to be more stable after the fixes land.

However, I did not check the gke-ci builds at all and I am not sure if the `monitoring-influxdb` problem is still occurring.

**Comment by dchen1107** [comment] 2016-01-21 01:14
@alex-mohr The failing cases you listed at https://github.com/kubernetes/kubernetes/issues/19189#issuecomment-173409041 are totally different from what I observed from kubernetes-e2e-gce-reboot jenkins project which I commented at https://github.com/kubernetes/kubernetes/issues/19189#issuecomment-170749856

* kubernetes-e2e-gce-reboot is isolated test suite for reboot tests, and the failures are caused by the combination of using docker label for restart_count, influxdb container restart caused by rebooting and crashing, and backoff. The proposed solution I had is introducing knob to disable the backoff for reboot test suite or reset it. 

* kubernetes-e2e-gke-ci show totally different cause. I checked all three cases, all are failed with a similar error message: 

10:34:38 Jan 19 10:34:38.198: INFO: Wanted all 2 pods to be running and ready. Result: false. Pods: [fluentd-cloud-logging-gke-jkns-gke-e2e-ci-b1a0bc33-node-bysw kube-proxy-gke-jkns-gke-e2e-ci-b1a0bc33-node-bysw]

This align with what @yujuhong found and commented at: https://github.com/kubernetes/kubernetes/pull/19436#issuecomment-172982445

**Comment by alex-mohr** [comment] 2016-01-21 18:11
Thanks @dchen1107 and @yujuhong -- one fix merged yesterday and one this morning at 9:30am.  If any more reboot tests fail today, I'll ping here.

**Comment by dchen1107** [comment] 2016-01-21 20:10
@alex-mohr thanks for this.

**Comment by yujuhong** [comment] 2016-01-21 21:06
kubernetes-e2e-gce-reboot/10773 failed for a different reason (not fixed by my PRs). The UID of the static pod, kube-proxy, changed after reboot. This caused kubelet to recreate the mirror pod for kube-proxy.
This is consistent on all three nodes for kube-proxy (UID included in the parenthesis).

```
#node e2e-reboot-minion-cxr0
I0121 17:53:35.439655    3450 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-cxr0_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-cxr0_kube-system(56aa659de8693fa0b702dcf1f45c8e96)"
I0121 18:00:47.207579    3281 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-cxr0_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-cxr0_kube-system(25cc5591090b12de1880be3fd7981dd9)"
I0121 18:11:32.281535    2519 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-cxr0_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-cxr0_kube-system(25cc5591090b12de1880be3fd7981dd9)"

#node e2e-reboot-minion-991e
I0121 17:53:35.982538    3459 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-991e_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-991e_kube-system(56aa659de8693fa0b702dcf1f45c8e96)"
I0121 18:00:46.218200    3299 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-991e_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-991e_kube-system(25cc5591090b12de1880be3fd7981dd9)"
I0121 18:02:13.545131    2467 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-991e_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-991e_kube-system(25cc5591090b12de1880be3fd7981dd9)"
I0121 18:11:34.087638    2526 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-991e_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-991e_kube-system(25cc5591090b12de1880be3fd7981dd9)"

#node e2e-reboot-minion-3iih
I0121 17:53:30.761708    3453 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-3iih_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-3iih_kube-system(56aa659de8693fa0b702dcf1f45c8e96)"
I0121 18:00:13.542159    3191 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-3iih_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-3iih_kube-system(25cc5591090b12de1880be3fd7981dd9)"
I0121 18:02:12.449096    2642 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-3iih_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-3iih_kube-system(25cc5591090b12de1880be3fd7981dd9)"
I0121 18:11:31.323173    2534 kubelet.go:2288] SyncLoop (ADD, "file"): "fluentd-elasticsearch-e2e-reboot-minion-3iih_kube-system(3d933132a83d2b5b74d473a70bfee97f), kube-proxy-e2e-reboot-minion-3iih_kube-system(25cc5591090b12de1880be3fd7981dd9)"
```

The UID is generated using the the md5 hash of the pod object, decoded from the manifest file. I have no idea why this happened on all three nodes and I can't reproduce it with my cluster.

**Comment by yujuhong** [comment] 2016-01-22 01:12
The kube-proxy container image changed after reboot, causing the generated UID to change for the pod. That leads to the mirror pod being recreated and failed the test.

```
Before:

Containers:[{Name:kube-proxy                                                                                                                                                                                                                                                               
Image:gcr.io/google_containers/kube-proxy:8589abba96b1e258b423e750f933dd2b                                                                                                                                                                                                                 
Command:[/bin/sh -c kube-proxy --master=https://e2e-reboot-master                                                                                                                                                                                                                          
--kubeconfig=/var/lib/kube-proxy/kubeconfig --resource-container="" --v=4                                                                                                                                                                                                                  
1>>/var/log/kube-proxy.log 2>&1] 

After:

Containers:[{Name:kube-proxy                                                                                                                                                                                                                                                               
Image:gcr.io/google_containers/kube-proxy:435849c9e76a90dd400f7b4d94e84fd4                                                                                                                                                                                                                 
Command:[/bin/sh -c kube-proxy --master=https://e2e-reboot-master                                                                                                                                                                                                                          
--kubeconfig=/var/lib/kube-proxy/kubeconfig --resource-container="" --v=4                                                                                                                                                                                                                  
1>>/var/log/kube-proxy.log 2>&1] 
```

The image field in the manifest file [is populated by salt](https://github.com/kubernetes/kubernetes/blob/fc6247152bab039705da08f9ec7d180454bc249b/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest#L33).
This type of flake first started in kubernetes-e2e-gce-reboot/10752, so it could've been introduced by a recent change.

/cc @kubernetes/goog-testing

**Comment by dchen1107** [comment] 2016-01-22 01:29
@yujuhong Thanks for looking into this. 

When node reboot, configure-vm.sh will trigger salt run which copies over new tar file to the node when kube-proxy_docker_tag is updated. The problem is that kube-proxy_docker_tag shouldn't be updated since we don't re-build those images (kube-proxy and master components). 

cc/ @ixdy and @ihmccreery

**Comment by yujuhong** [comment] 2016-01-22 02:31
In kubernetes-e2e-gce-reboot/10752, the tests changed in the middle from kubernetes-build/7773 to kubernetes-build/7774

1. The kube-proxy image changes from `gcr.io/google_containers/kube-proxy:d06e45de2d56c8e64f6281da032976d8` to `gcr.io/google_containers/kube-proxy:9b5676b5d844d1a345cd2b70c23d9b30`.
2. The node info dumped after the test failure also shows a version that belongs to kubernetes-build/7774 (`v1.2.0-alpha.6.256+8ed248021ef126`). The build/test started with build kubernetes-build/7773 (`v1.2.0-alpha.6.254+03ecde1277f7c`)

Reassigning to @ixdy to triage.

**Comment by ixdy** [comment] 2016-01-22 02:38
Maybe related to #8705?

**Comment by ixdy** [comment] 2016-01-22 02:39
Though if it's occurring more recently, probably not.

**Comment by dchen1107** [comment] 2016-01-22 17:27
@ixdy They might be the same root cause, but #8705 doesn't have enough information here.

I checked several other failed build with reboot, and they all have the same cause. For example: kubernetes-e2e-gce-reboot/10795, the kube-proxy image changed from gcr.io/google_containers/kube-proxy:9a2221ffc2ba0d47feed59502b7ea301 to gcr.io/google_containers/kube-proxy:70cc5093af0691e37723c7912004ea08

**Comment by yujuhong** [comment] 2016-01-22 18:20
Recent failures from kubernetes-e2e-gce-reboot:
 * Timed out waiting for monitoring-influxdb-grafana pod to be ready: 10798
 * Build version changed before the test completed: 10762, 10768, 10773, 10795

It seems like the old monitoring-influxdb-grafana issue still exists, but it dwarfs in comparison to the frequency of build changes.

**Comment by ihmccreery** [comment] 2016-01-22 19:46
> Build version changed before the test completed: 10762, 10768, 10773, 10795

Wondering if that's related to #19952; looking into it.

**Comment by yujuhong** [comment] 2016-01-22 23:12
The build versioning problem is being handled by @ihmccreery in #8705, and possible cause has been identified (thanks!). 
The two other bugs manifesting via missing mirror pods (https://github.com/kubernetes/kubernetes/pull/19436#issuecomment-173030536) has never appeared since my fixes went in.

This leaves the influxdb crash looping problem --- the original issue identified by @dchen1107. I'll retitle the issue.

**Comment by dchen1107** [comment] 2016-01-26 17:41
Ok, 

* Crashloop heapster was upgraded to a new version.
* #20099 was merged, which can help us to understand more which kube-system pods are not ready and why.
* Version screw fix was merged too. 
* Reboot test suite passed since yesterday late afternoon. 

Close the issue.

**Closed by dchen1107** 2016-01-26 17:41 UTC
Labels: area/monitoring, kind/flake, priority/P0, team/node
