### ISSUE TITLE
why "kubectl port-forward" just binds the 127.0.0.1 but not 0.0.0.0?

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#40053] opened 2017-01-18 02:11 UTC
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
port-forward
---

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"79113147d3cacf4a3c07d13bddff5aa7c0f3fe98", GitTreeState:"dirty", BuildDate:"2017-01-16T03:40:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"79113147d3cacf4a3c07d13bddff5aa7c0f3fe98", GitTreeState:"dirty", BuildDate:"2017-01-16T03:36:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
the "kubectl port-forward" command binds the address 127.0.0.1 which means we can't visit the forward port from outside the server. Why don't we bind the address 0.0.0.0 which can make the forward be visited outside the server? 

**What you expected to happen**:
change the binding address to 0.0.0.0

**Comment by colemickens** [comment] 2017-01-18 02:12
dupe of: https://github.com/kubernetes/kubernetes/issues/36152

**Comment by tianshapjq** [comment] 2017-01-18 02:29
thanks~ @colemickens

**Closed** 2017-01-18 04:07 UTC

**Comment by simonfontana** [comment] 2019-02-14 19:40
@satya541 is correct but you need > v1.13.0. See #46517.
