### ISSUE TITLE
Generate client code using go2idl

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#17468] opened 2015-11-19 00:30 UTC
ref #16560 #15730
Here is the road-map:

Writing Client-gen:
- [x] Generate the common methods, ignore the methods operating on subresources for now
- [x] Unify the signature of the common methods in our individual typed clients
- [x] Make a test type, then write the test against this type instead of every type
- [x] manually add the methods that are not common to all typed clients
- [x] make go2idl track the functions, constants, variables, methods in the input package.
- [x] add a "plural" namer to go2idl

Using Client-gen:
- [x] generate the internalversion clientset, to replace pkg/client/clientset/unversioned
- [x] generate the fake clients to enable testing
- [x] generate versioned client

Using generated clientset:
- [x] replace the pkg/client/unversioned/ in controllers
- [x] replace the pkg/client/unversioned/ in kubelets
- [ ] let controllers use versioned clientset
- [ ] let kubelet use versioned clientset

cc @kubernetes/goog-csi

**Comment by wojtek-t** [comment] 2015-11-19 08:04
Isn't it a duplicate of https://github.com/kubernetes/kubernetes/issues/16560 ?

I agree with the overall plan. However, I have a question what would you do with "subresource-related methods"? Will there be a common file with all of them?

**Comment by caesarxuchao** [comment] 2015-11-19 17:22
> Isn't it a duplicate of #16560 ?

Sort of. I tried to use this one to track the progress. Also 16560 talks about REST setup code, which is not in this issue. I can move the list to 16560 if you think that's better.

> what would you do with "subresource-related methods"? Will there be a common file with all of them?

I haven't thought this through yet. I think leave the methods in separate files is more friendly to the reader.

**Comment by wojtek-t** [comment] 2015-11-19 17:26
>
Sort of. I tried to use this one to track the progress. Also 16560 talks about REST setup code, which is not in this issue. I can move the list to 16560 if you think that's better.

I'm fine with leaving it here if you prefer. Was just asking... :)

>
I haven't thought this through yet. I think leave the methods in separate files is more friendly to the reader.

I think having them together with other methods would be better, but I guess we can improve it over time.

**Comment by wojtek-t** [comment] 2015-11-23 14:00
@caesarxuchao - what is the expected ETA for it? (or when do you plan to start working on it)?

**Comment by caesarxuchao** [comment] 2015-11-23 17:53
@wojtek-t I'm working on it. Have you taken a look at #17534? I'm writing the test for the generated code now.

**Comment by wojtek-t** [comment] 2015-11-24 09:17
Awesome @caesarxuchao - will take a look now.

**Comment by caesarxuchao** [comment] 2015-11-25 19:37
Changes to the client code that we may want to incorporate into the generated code:
ref: https://github.com/kubernetes/kubernetes/pull/17628/files#r45882725

**Comment by smarterclayton** [comment] 2017-06-01 18:11
This is done.

**Closed by smarterclayton** 2017-06-01 18:11 UTC
Labels: priority/important-soon, sig/api-machinery
