### ISSUE TITLE
GKE: Kubelet not configuring CBR0 on 4 of 1000 nodes

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#21401] opened 2016-02-17 17:59 UTC
From head @ Feb 16 ~9am, a 1000 node cluster on GKE had 4 nodes that came up as persistently flapping healthy/unhealthy.  They cycle through a loop where apparently kubelet restarts itself because docker is not running.  Logging details follow with instructions on how to access the node at the end.
```
% gcloud container clusters get-credentials mohr-test --zone=us-central1-c --project=mohr-instance-manager1
% kubectl describe node gke-mohr-test-a83d8da2-node-yv6i
...
 15m           15m             1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      Starting                Starting kubelet.
  15m           15m             1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeHasSufficientDisk   Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeHasSufficientDisk
  15m           15m             1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeReady               Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeReady
  10m           10m             1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeNotReady            Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeNotReady
  5m            5m              1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      Starting                Starting kubelet.
  5m            5m              1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeHasSufficientDisk   Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeHasSufficientDisk
  4m            4m              1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeReady               Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeReady
  51s           51s             1       {kubelet gke-mohr-test-a83d8da2-node-yv6i}                      NodeNotReady            Node gke-mohr-test-a83d8da2-node-yv6i status is now: NodeNotReady
```
I don't understand kubelet and docker setup well enough to debug, so here are logs.  Most telling might be docker.log, full of repeated entries (Note that kube-env has CLUSTER_IP_RANGE: 10.132.0.0/14):
```
time="2016-02-17T17:50:27.304870401Z" level=warning msg="Could not get list of networks during endpoint cleanup: could not find endpoint count key docker/network/v1.0/endpoint_count/3bda6e7914e3c4986a9c7557aef98064035952e8376d1bb1e692dd45fab91e77/ for network bridge while listing: Key not found in store" 
time="2016-02-17T17:50:27.305104444Z" level=error msg="could not find endpoint count key docker/network/v1.0/endpoint_count/3bda6e7914e3c4986a9c7557aef98064035952e8376d1bb1e692dd45fab91e77/ for network bridge while listing: Key not found in store" 
time="2016-02-17T17:50:27.309913613Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to allocate gateway (10.132.184.1): No available addresses on this pool" 
```
From gke-mohr-test-a83d8da2-node-yv6's kubelet.log, there seems to be some strangeness with configuring cbr0:
```
cmdline: /usr/local/bin/kubelet --api-servers=https://104.197.237.207 --enable-debugging-handlers=true --cloud-provider=gce --config=/etc/kubernetes/manifests --allow-privileged=True --v=2 --cluster-dns=10.135.240.10 --cluster-domain=cluster.local --configure-cbr0=true --cgroup-root=/ --system-cgroups=/system --configure-hairpin-mode=true
```
```
W0217 00:23:00.613889    1482 kubelet.go:2687] ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now
I0217 00:23:01.066330    1482 kubelet.go:1018] Adding node label from cloud provider: beta.kubernetes.io/instance-type=n1-standard-1
I0217 00:23:01.066348    1482 kubelet.go:1029] Adding node label from cloud provider: failure-domain.alpha.kubernetes.io/zone=us-central1-c
I0217 00:23:01.066353    1482 kubelet.go:1033] Adding node label from cloud provider: failure-domain.alpha.kubernetes.io/region=us-central1
E0217 00:23:01.067745    1482 kubelet.go:2843] Error getting image list: cannot connect to Docker endpoint
I0217 00:23:01.067778    1482 kubelet.go:2661] Recording NodeHasSufficientDisk event message for node gke-mohr-test-a83d8da2-node-yv6i
I0217 00:23:01.067894    1482 kubelet.go:1066] Attempting to register node gke-mohr-test-a83d8da2-node-yv6i
I0217 00:23:01.074493    1482 kubelet.go:1082] Node gke-mohr-test-a83d8da2-node-yv6i was previously registered
I0217 00:23:01.076974    1482 kubelet.go:3480] Setting Pod CIDR:  -> 10.132.184.0/24
E0217 00:23:01.078254    1482 kubelet.go:2843] Error getting image list: cannot connect to Docker endpoint
E0217 00:23:01.614173    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:02.614561    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:03.615012    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:04.615405    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
I0217 00:23:05.614176    1482 kubelet.go:2287] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now]
E0217 00:23:05.614382    1482 kubelet.go:2617] Container runtime sanity check failed: docker: failed to get docker version: cannot connect to Docker endpoint
E0217 00:23:05.615717    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:06.616077    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:07.616453    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:08.616805    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
E0217 00:23:09.617125    1482 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint
I0217 00:23:10.616219    1482 kubelet.go:2287] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now]
```
List of nodes
```
% kubectl get nodes | grep "NotReady" 
gke-mohr-test-a83d8da2-node-afiv   beta.kubernetes.io/instance-type=n1-standard-1,failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-c,kubernetes.io/hostname=gke-mohr-test-a83d8da2-node-afiv   NotReady   22h
gke-mohr-test-a83d8da2-node-qu7s   beta.kubernetes.io/instance-type=n1-standard-1,failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-c,kubernetes.io/hostname=gke-mohr-test-a83d8da2-node-qu7s   NotReady   22h
gke-mohr-test-a83d8da2-node-xi4t   beta.kubernetes.io/instance-type=n1-standard-1,failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-c,kubernetes.io/hostname=gke-mohr-test-a83d8da2-node-xi4t   NotReady   22h
gke-mohr-test-a83d8da2-node-yv6i   beta.kubernetes.io/instance-type=n1-standard-1,failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-c,kubernetes.io/hostname=gke-mohr-test-a83d8da2-node-yv6i   NotReady   22h
```
I've added @dchen1107 and @thockin and most of the Google team to my project, so you can access the node via the following -- and let me know if you need more.  I'll assign to Dawn to triage, but apologies if someone else should have been assigned; let me know who that would have been and I'll do better next time.
```
% gcloud compute --project "mohr-instance-manager1" ssh --zone "us-central1-c" "gke-mohr-test-a83d8da2-node-yv6i"
```

**Comment by alex-mohr** [comment] 2016-02-17 18:00
@cjcullen and @roberthbailey as fyi too

**Comment by dchen1107** [comment] 2016-02-17 18:08
@alex-mohr thanks for detail information. I cannot ssh into the node:

```
WRITER permissions on the project are required for SSH access.
Error code: 24
Error message: Rate Limit Exceeded
```

**Comment by cjcullen** [comment] 2016-02-17 18:08
Possibly related? https://github.com/docker/docker/issues/18113

**Comment by dchen1107** [comment] 2016-02-17 18:09
@cjcullen That is the exact what I wanted to check here.

**Comment by dchen1107** [comment] 2016-02-17 18:19
If docker/docker#18113 is indeed the root cause, you might hit the problem with the same root cause as https://github.com/kubernetes/kubernetes/issues/20995 which has corrupted checkpoint file during upgrade from docker 1.8.3 to 1.9.1
/var/lib/docker/network/files/local-kv.db 

If that is true, we won't hit the problem in real release since we are going to bake the docker 1.9.1 into the image itself, and there is no upgrade happening. But I need to validate the theory here. Thanks!

**Comment by bprashanth** [comment] 2016-02-17 18:21
Fyi https://github.com/kubernetes/kubernetes/issues/20995 happened ~1/200 nodes too

**Comment by dchen1107** [comment] 2016-02-18 00:27
Ok, we did hit the same #20995

# tail -f docker.log
time="2016-02-18T00:23:21.074823496Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to allocate gateway (10.132.184.1): No available addresses on this pool" 

After I removed the corrupted checkpoint file: /var/lib/docker/network/files/local-kv.db and restart docker daemon, everything works fine. Now bridge cbr0 is created properly:

# ifconfig -a
cbr0      Link encap:Ethernet  HWaddr 12:56:8e:78:8c:18  
          inet addr:10.132.184.1  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:546 errors:0 dropped:0 overruns:0 frame:0
          TX packets:486 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:77364 (75.5 KiB)  TX bytes:152655 (149.0 KiB)

I am going to close this one as dup of #20995.

**Closed by dchen1107** 2016-02-18 00:27 UTC
Labels: dependency/docker, priority/P1, team/cluster, team/gke, team/node
