### ISSUE TITLE
Proposal: Add workload `ClusterSecret` to be used by pods across namespaces

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#113251] opened 2022-10-21 12:15 UTC
### What would you like to be added?

Add a new workload `ClusterSecret` to be used by pods across namespaces (`cluster-scope`), just like the `ClusterRole` and `Role`.

For example, we can just create one `ClusterSecret` image pull secret, to be used by pods across multipe namespaces in the cluster, instead of creating every `namespace-scope` secret (currently) in every namespace which need the secret.

### Why is this needed?

Currently, the secret used by pod just restricted to the same namespace, but we need a new workload `ClusterSecret` to be used across namespaces, just like the `ClusterRole` and `Role`.

For example, we may need a `cluster-scope` image pull secret, to be used by pods across multipe namespaces in the cluster, instead of creating every `namespace-scope` secret (currently) in every namespace which need the secret.

**Comment by liggitt** [comment] 2022-10-22 13:17
Thanks for the request, this looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/70147

/close

**Closed by liggitt** 2022-10-22 13:17 UTC
Labels: kind/feature, sig/apps, triage/duplicate, needs-triage
