### ISSUE TITLE
e2e flake: Generated release_1_3 clientset [It] should create pods, delete pods, watch pods 

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26628] opened 2016-06-01 12:05 UTC
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/26622/kubernetes-pull-build-test-e2e-gce/42787/build-log.txt

```
Failed to query for pods: Get https://130.211.140.201/api/v1/namespaces/e2e-tests-clientset-lwmck/pods?labelSelector=time%3D569192984: dial tcp 130.211.140.201:443: i/o timeout
```

it seems that API server were unresponsive for some time. cc @lavalamp

**Comment by caesarxuchao** [comment] 2016-06-01 17:56
This happened with `kubectl exec` as well: https://github.com/kubernetes/kubernetes/pull/20932.

Not sure if we should dig this up or just retry when i/o timeout occurs.

**Comment by wojtek-t** [comment] 2016-06-02 13:48
So far most of the i/o timeouts that I faced were because apiserver was down at that time.

**Comment by wojtek-t** [comment] 2016-06-02 13:51
But it wasn't the case here...

**Comment by fejta** [comment] 2016-06-02 16:18
@krousey you're randomly assigned this test via the spreadsheet. Please take a look or else update the spreadsheet and assign to @lavalamp

**Comment by krousey** [comment] 2016-06-02 16:30
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26714/kubernetes-pull-build-test-e2e-gce/42787/

I hate that the storage.googleapis.com url isn't browse-able.

**Comment by krousey** [comment] 2016-06-02 16:35
Looking through the api server log, there's no record of that request.

**Comment by krousey** [comment] 2016-06-02 17:15
Any idea of the frequency. Is it frequent? Or is it possible that this is just a transient network issue?

**Comment by gmarek** [comment] 2016-06-02 18:40
I saw this for the first time, so it might be a red herring.

**Comment by caesarxuchao** [comment] 2016-06-02 19:24
Might be caused by running too much tests at once on Jenkins VMs. See https://github.com/kubernetes/kubernetes/issues/26420

**Comment by lavalamp** [comment] 2016-06-03 00:33
look for evidence of apiserver having crashed-- @wojtek-t fixed something
similar recently.

**Comment by krousey** [comment] 2016-06-06 16:53
@lavalamp , @wojtek-t already stated that it wasn't because the apiserver was down in this case.

**Comment by lavalamp** [comment] 2016-06-06 20:42
Yeah, sorry, I somehow missed that.

**Comment by krousey** [comment] 2016-06-10 21:48
Seems to not have re-occurred. Any objections to closing this?

**Comment by krousey** [comment] 2016-06-17 16:16
It's been a week and no more occurences were pointed out. Also no objections were raised.

**Closed by krousey** 2016-06-17 16:16 UTC
Labels: kind/flake, team/CSI-API Machinery SIG
