### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Backoff problem when quickly reverting resize patch

### ISSUE THREAD

**Issue by esotsal** [kubernetes/kubernetes#125843] opened 2024-07-02 14:41 UTC
### What happened?

While working on #125202 , issue with backoff was discovered resulting to slow reconcile when quickly reverting resize patch. This can be reproduced please check https://github.com/kubernetes/kubernetes/issues/125205#issuecomment-2203184854 ,  https://github.com/kubernetes/kubernetes/issues/125205#issuecomment-2143527472.

Backoff issue does not happen on v1.30 or older please check https://github.com/kubernetes/kubernetes/issues/125205#issuecomment-2203224319

### What did you expect to happen?

After patching forwards and patching backwards a pod which has a container whose `resizePolicy` is `RestartContainer`and a container whose `restartPolicy`is `RestartContainer` , pod should reach its initial state without any backoff delay introduced.

### How can we reproduce it (as minimally and precisely as possible)?

<details>

```console
for l in `seq 301 310`; do kubectl patch pod resize-pod --patch "{\"spec\":{\"containers\":[{\"name\":\"c2\", \"resources\":{\"limits\":{\"memory\":\"${l}Mi\"}}}]}}"; sleep 3; done

$ kubectl get pod resize-pod -w
NAME         READY   STATUS    RESTARTS   AGE
resize-pod   3/3     Running   0          14s
resize-pod   3/3     Running   0          21s
resize-pod   3/3     Running   1 (1s ago)   22s
resize-pod   3/3     Running   1 (3s ago)   24s
resize-pod   3/3     Running   2 (2s ago)   26s
resize-pod   3/3     Running   2 (3s ago)   27s
resize-pod   2/3     CrashLoopBackOff   2 (1s ago)   29s
resize-pod   2/3     CrashLoopBackOff   2 (2s ago)   30s
resize-pod   2/3     CrashLoopBackOff   2 (5s ago)   33s
resize-pod   2/3     CrashLoopBackOff   2 (6s ago)   34s
resize-pod   2/3     CrashLoopBackOff   2 (8s ago)   36s
resize-pod   2/3     CrashLoopBackOff   2 (11s ago)   39s
resize-pod   3/3     Running            3 (13s ago)   41s
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.0-alpha.0.19+d591bc54b588b1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0-alpha.2.287+7586ad36136b00
```
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# paste output here
Linux sotiris-Precision-5560 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```
</details>

### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tallclair** [comment] 2024-11-04 18:40
Duplicate of https://github.com/kubernetes/kubernetes/issues/119838
/close

**Closed by tallclair** 2024-11-04 18:40 UTC
Labels: kind/bug, sig/node, priority/important-longterm, triage/accepted
