### ISSUE TITLE
PPC builds are disabled due to a linking error

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25886] opened 2016-05-19 16:41 UTC
#25243 disabled PPC builds due to the following error:

```
+++ [0519 04:51:15] linux/ppc64le: go build started
# k8s.io/kubernetes/cmd/hyperkube
/usr/local/go/pkg/tool/linux_amd64/link: running powerpc64le-linux-gnu-gcc failed: exit status 1
/tmp.k8s/go-link-284905442/go.o: In function `type..hash.[13]k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd.subsystem':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go:1:(.text+0x2005770): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.interhash'
/tmp.k8s/go-link-284905442/go.o: In function `type..eq.[13]k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd.subsystem':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go:1:(.text+0x2005858): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.ifaceeq'
/tmp.k8s/go-link-284905442/go.o: In function `type..hash.struct { a string; b k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/configs.Operator }':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go:1:(.text+0x2005f90): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.strhash'
/tmp.k8s/go-link-284905442/go.o: In function `type..hash.struct { a string; b k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/configs.Action }':
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go:1:(.text+0x2006330): relocation truncated to fit: R_PPC64_REL24 (stub) against `runtime.strhash'
collect2: error: ld returned 1 exit status
```

Additional comments here https://github.com/kubernetes/kubernetes/pull/25243#issuecomment-220357307

**Comment by luxas** [comment] 2016-05-19 16:52
cc @luxas @ixdy @david-mcmahon @bpradipt @seelam @pensu

**Comment by bpradipt** [comment] 2016-05-24 05:38
The issue on PowerPC is both for cross and native-builds. The issue appears to be with the toolchain (golang) and how the linking is being done. The object sections have grown too large to link. We are looking at it
cc @laboger

**Comment by luxas** [comment] 2016-05-25 12:12
@bpradipt Have you tried to upgrade `gcc` to a newer version?
It might or might not help...

You might also try to look at what in the gcc linker differs from `aarch64` for example, where it doesn't fail

**Comment by Pensu** [comment] 2016-06-08 06:05
We are looking into this and it might take some more time. In the meanwhile is it possible to remove hyperkube from the ppc64le builds? All other binaries are building perfectly fine. We can resume the hyperkube for ppc64le build as soon as this issue resolves.

cc: @david-mcmahon

**Comment by luxas** [comment] 2016-06-19 04:13
Ah, this s only partially fixed. Reopening...

**Comment by laboger** [comment] 2016-06-20 14:58
The error occurs because the hyperkube binary is very large and when building the binary, golang is generating a single go.o file with a single text section that is larger than 2^26 on ppc64le.  When there is a call instruction within that section where the call target offset is beyond what can fit in the instruction the relocation truncation error will be generated by the GNU linker.  When there are multiple, smaller text sections sent to the GNU linker for linking, it can generate appropriate call instructions even the call target is beyond that limit.  I'm working on a fix to do that but hitting other issues as a result which I'm working through.

I suspect that this same error will be hit at some point on arm64 unless their linker has another way to handle this situation.  On ppc64le we are very close to the limit and from build to build it varies so that some days it will build and others it won't.

**Comment by luxas** [comment] 2016-06-20 15:12
@laboger Interesting. How does amd64 handle it?

**Comment by laboger** [comment] 2016-06-20 15:47
I don't know for sure how arm64 handles it because I don't have access to a machine that is set up to build for arm64.

I suspect their text section size is not as large as it is on ppc64le so they haven't hit the limit yet.

**Comment by luxas** [comment] 2016-06-20 16:59
Ok, you may easily see what's going on for **arm64** by investigating what `aarch64-linux-gnu-gcc` does in kube-cross.

But I asked about what **amd64** (x86_64) does to prevent this :)
(I'm assuming this will never happen to amd64)

**Comment by laboger** [comment] 2016-06-20 19:00
Sorry I misread your question about amd64...  The call instruction in amd64 has a 32 bit field instead of a 24 bit field in ppc64le for the call target address.  That means they wouldn't hit this error when linking hyperkube until its text section was larger than 2^32.  If you search on "relocation truncated to fit" you will see that this error has happened in the past on x86 with other programming languages.

**Comment by laboger** [comment] 2016-07-08 16:29
Once a fix is ready, how does it need to be provided?

**Comment by luxas** [comment] 2016-07-08 17:36
I saw https://go-review.googlesource.com/#/c/23963/ probably won't make 1.7, and that's sad.

We would just upgrade golang version I think, not really sure what you're asking for

**Comment by laboger** [comment] 2016-07-08 17:45
I assume you only use official golang versions or those provided with distros for your builds?

Are you doing all your builds as cross builds from a golang on an x86?

**Comment by luxas** [comment] 2016-07-08 17:48
Official versions, yes. We're using the `golang:x.y` docker image.
All official builds are built on amd64 hosts.

**Comment by laboger** [comment] 2016-07-25 15:09
Where are you getting this docker image from?
Will you be moving to golang:1.7 when it is released?

**Comment by luxas** [comment] 2016-07-25 17:54
We're using the official `golang` images, and will pick up `1.7` as soon as it is released for testing I think.
Then if the testing and scalability teams think it's safe to use, we'll switch to 1.7

BTW, where is your patch for this? Can you link to it?

**Comment by ixdy** [comment] 2016-08-15 23:13
`kubemark` is also broken right now - see #30384.

**Comment by laboger** [comment] 2016-08-17 12:12
Hi, I'm sorry I missed your last question to me.  Here is the CL for my patch for the PPC64 relocations truncation error.  https://go-review.googlesource.com/#/c/23963/
The error with kubemark is also size related but somewhat different because that one is being built as static.  Just curious, why are some built static and some non-static?

**Comment by ixdy** [comment] 2016-08-23 22:49
just to tie everything together, #30659 disabled linux/ppc64le compilation entirely. hopefully by go1.8 we can reenable it.

**Comment by euank** [comment] 2017-02-02 21:01
Well, we've hit 1.8 I think with #38926

@luxas Want to link to any other relevant issues to kinda tie this one together, and close this if it seems appropriate?

**Comment by ixdy** [comment] 2017-02-02 21:04
yeah, ppc64le builds have been re-enabled for k8s 1.6.

**Closed by ixdy** 2017-02-02 21:04 UTC
Labels: area/build-release, area/release-infra

**Comment by karina-kuu20** [comment] 2023-05-22 13:45
The issue on PowerPC is both for cross and native builds. The issue appears to be with the toolchain (golang) and how the linking is being done. The object sections have grown too large to link. We are looking at it
cc #117804

**Comment by pmur** [comment] 2023-05-22 14:32
@karina-kuu20 this issue is quite old.  Can you provide more context to your comment? Specifically, more detail to help me reproduce. I was unable to find anything related to ppc64le on #117804.
